### ISSUE TITLE
Deprecation notices with PHP 8.1

### ISSUE THREAD

**Issue by sebastianbergmann** [composer/composer#10008]
From https://github.com/sebastianbergmann/phpunit/runs/3111696987:

```
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count()
should either be compatible with Countable::count(): int,
or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
in phar:///home/runner/work/phpunit/phpunit/tools/composer/src/Composer/Repository/ArrayRepository.php:286
```
```
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count()
should either be compatible with Countable::count(): int,
or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
in phar:///home/runner/work/phpunit/phpunit/tools/composer/src/Composer/Repository/WritableArrayRepository.php:286
```
```
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count()
should either be compatible with Countable::count(): int,
or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
in phar:///home/runner/work/phpunit/phpunit/tools/composer/src/Composer/Repository/InstalledFilesystemRepository.php:286 
```

#### Related
* https://github.com/symfony/symfony/issues/42199
* https://github.com/justinrainbow/json-schema/issues/668

**Comment by Seldaek** [comment]
@shivammathur sorry to nag you but as I've been wondering this for a while, I figured this is as good a time as any to ask.. What's the timeline on getting new composer releases to be included by setup-php? Is it dependent on some manual build step you have to do?

I just released 2.1.4 which fixes 8.1 deprecations and it'd be great to get it out to GH actions :)

**Comment by Seldaek** [comment]
@shivammathur Similarly, I have now tried switching to `tools: composer:snapshot` but it seems I get the snapshot from some-time-yesterday and not the latest. It'd be great if snapshot would force it to download the latest always at least and not use the latest container you've built.

**Comment by stof** [comment]
@Seldaek Looking at the setup-php code, it downloads it from https://github.com/shivammathur/composer-cache, which is updated by a cron once a day

**Comment by shivammathur** [comment]
@Seldaek 
Composer builds are cached to [GitHub releases](https://github.com/shivammathur/composer-cache/releases/tag/versions) by a daily cron workflow. This cache is used to download composer phars with getcomposer.org as a fallback. This was done their were noticed random network issues while fetching composer. Using a GitHub releases cache reduces the setup time as well because of server location.

I think a good solution would be adding a flag in setup-php to not use the cache, but use getcomposer.org as the source.

**Comment by stof** [comment]
@shivammathur another thing might also be to increase the frequency of the cron updating the cache (the snapshot on getcomposer.org is not updated only nightly, but when there is activity in the composer repo)

**Comment by Seldaek** [comment]
Right if that was updated hourly for example that would completely solve the issue IMO.

**Comment by shivammathur** [comment]
@Seldaek I will update the cron, and add the flag in the next release.

**Comment by MarkBaker** [comment]
I'm getting deprecation notices with 8.1 as well:
```
PHP Deprecated:  Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/vendor/symfony/console/Helper/HelperSet.php on line 112
Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php:48
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:286
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/src/Composer/Repository/WritableArrayRepository.php:286
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/src/Composer/Repository/InstalledFilesystemRepository.php:286
Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php:48
Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/vendor/symfony/console/Helper/HelperSet.php on line 112
/home/runner/.cache/composer/files
```
I'm not sure that these are directly related though, and if your changes will resolve my deprecation notices

**Comment by shivammathur** [comment]
@MarkBaker Please re-run your workflow, `setup-php` should now install composer 2.1.4 which will not have these warnings.

**Comment by Seldaek** [comment]
> @Seldaek I will update the cron, and add the flag in the next release.

Thanks for the prompt fix as always!

**Comment by sebastianbergmann** [comment]
> ```
> PHP Deprecated:  Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/vendor/symfony/console/Helper/HelperSet.php on line 112
> Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php:48
> Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:286
> Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/src/Composer/Repository/WritableArrayRepository.php:286
> Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/src/Composer/Repository/InstalledFilesystemRepository.php:286
> Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php:48
> Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/vendor/symfony/console/Helper/HelperSet.php on line 112
> /home/runner/.cache/composer/files
> ```
> 
> I'm not sure that these are directly related though, and if your changes will resolve my deprecation notices
> 
> The above was output from
> 
> ```
> composer config cache-files-dir
> ```

This is tracked elsewhere:

* https://github.com/symfony/symfony/issues/42199
* https://github.com/justinrainbow/json-schema/issues/668

**Comment by stratboy** [comment]
Having same notices here, and I didn't really understand how to solve.. Any easy explanation? :) Thank you

**Comment by Pezhvak** [comment]
It seems the merge didn't fix the issue, after upgrading to `8.1` i'm still getting the deprecation notice.

**Comment by Seldaek** [comment]
Please create a new issue with more details.. Saying "me too" when something has been fixed for over six months and nobody had a problem clearly indicates this is either some other issue, or you're doing something wrong in your environment and not using the fix. None of which is going to be solved by writing here that you have the same problem.

**Comment by stratboy** [comment]
> Please create a new issue with more details.. Saying "me too" when something has been fixed for over six months and nobody had a problem clearly indicates this is either some other issue, or you're doing something wrong in your environment and not using the fix. None of which is going to be solved by writing here that you have the same problem.

Honestly, I really didn't understand what the fix should be. None of the aswers seems to explain it step by step. At least to me. I'm not a shell expert. Simply composer has always worked, until I updated system php to v8. Then composer should still work, at least after updating it.
