### ISSUE TITLE
unable to use proxy

### ISSUE THREAD

**Issue by Veeresh-alt** [composer/composer#10007]
E:\wamp64\www\real\1>composer diagnose
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: The Windows OneDrive folder is not supported on PHP versions below 7.2.23 and 7.3.10.
Upgrade your PHP (7.0.33) to use this location with Composer.

Checking git settings: OK
Checking http connectivity to packagist: FAIL
[Composer\Downloader\TransportException] Unable to use a proxy: malformed http_proxy url
Checking https connectivity to packagist: FAIL
[Composer\Downloader\TransportException] Unable to use a proxy: malformed http_proxy url

  [Composer\Downloader\TransportException]
  Unable to use a proxy: malformed http_proxy url

diagnose

**Comment by Seldaek** [comment]
As the error says: `Unable to use a proxy: malformed http_proxy url`. I don't know what you set http_proxy to, but it seems to be an invalid proxy URL.

**Comment by xtc2016xtc** [comment]
I am diagnosing composer and I have this problem "Checking Composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license. "How to solve it

**Comment by Seldaek** [comment]
@xtc2016xtc like it says, define a license. You can do it like this: `composer config license proprietary` for ex, or use MIT or whatever your project's license is.
