### ISSUE TITLE
bring SPI to PHP

### ISSUE THREAD

**Issue by RobberPhex** [composer/composer#10000]
# Background

SPI in Java can achieve a good dependency decoupling: for the provider, implement the interface and register it as a service; for the user, use the ServiceLoader to load the corresponding interface implementations.

However, PHP currently does not have a similar mechanism, so the corresponding plan is drafted.

# How to use

## Service provider
* Define interface
* Declare service in composer.json, associated interface and implementation

```php
// InterfaceA.php
namespace com\example;

interface InterfaceA
{
    function m();
}

// ImplA.php
namespace com\example;

class ImplA implements InterfaceA
{
    function m()
    {
        // TODO: Implement m() method.
    }
}
```
```json
// composer.json
"services": {
  "com\\example\\ImplA": [
    "com\\example\\ImplA"
  ]
},
```

## Service user
* `composer require` scan the provider’s package. Build map of interface -> implementation.
* When user needs to use service, load service, and traverse to get the implementation.

```php
use com\example\InterfaceA;

$loader = \Composer\ServiceLoader::load(InterfaceA::class);

foreach ($loader as $service) {
    /* @var $service InterfaceA */
    // ...
}
```

## Known issues
* There is no generic type in PHP, user needs to manually mark the type.

# Tasks
* When executing `composer require`, it scans the dependent services key and constructs the interface->implementation mapping
* Composer provides the ServiceLoader class at runtime for service locating.

**Comment by stof** [comment]
To me, this is out of scope of Composer. This can be achieved as a plugin instead.

**Comment by Seldaek** [comment]
Yeah this really doesn't seem like something worth adding to Composer at the moment. Note that we do have some support for this already at the package level using virtual packages like `psr/log-implementation` for example which is required by some, and provided by others (https://packagist.org/providers/psr/log-implementation), which lets the end user connect an interface and an implementation. This does no runtime binding/configuration/instantiation though, but that's just a much more complex problem that I am not willing to dive into.
