### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by tfont** [composer/composer#10011]
Can someone explain this?

While still using Composer 1.x which sadly is coming from a project that cannot be updated to Composer 2.x just yet.

```
Deprecation warning: require.ini is invalid, it should have a vendor name, a forward slash, and a package name.
The vendor and package name can be words separated by -, . or _.
The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*".
Make sure you fix this as Composer 2.0 will error.
````

 Much appreciated.

**Comment by Seldaek** [comment]
Package names are supposed to be like `foo/bar`, and `ini` has no slash in it.. I am not sure what you required as "ini", but it won't work in Composer 2.
