### ISSUE TITLE
[Composer\Downloader\TransportException]   curl error 6 while downloading https://repo.packagist.org/packages.json: getaddrinfo() thread failed to start

### ISSUE THREAD

**Issue by prafulwagh31** [composer/composer#10019]
[Composer\Downloader\TransportException]
  curl error 6 while downloading https://repo.packagist.org/packages.json: getaddrinfo() thread failed to start

**Comment by Seldaek** [comment]
This seems to indicate perhaps a firewall issue or other network connectivity issue. Not something we can do much about sorry.
