### ISSUE TITLE
PHP runtime error while creating laravel project

### ISSUE THREAD

**Issue by japanstation1** [composer/composer#10021]
- PHP Version: v8.0.8
- OS: Windows 10
- Composer Version 2.1.4

### Description:

When I run try to create a Laravel project I get the following error (despite the fact that during the installation of composer I had given full path of php.exe present in my OS) : 

```
 [RuntimeException]
  php: does not exist and could not be created.
```
### Steps to Reproduce:

- open cmd as administrator
- run the following command:

```
composer create-project laravel/laravel example-app
```

Attached here is the screenshot of complete output:
![image](https://user-images.githubusercontent.com/78594278/126703195-1c86bf89-0a08-4c1d-8033-6cee3ef43295.png)

**Comment by fahmiidris-labs** [comment]
I also got the same problem. What do I have to do?

**Comment by alexkart** [comment]
This issue is already reported https://github.com/composer/composer/issues/10020

**Comment by alexkart** [comment]
> I also got the same problem. What do I have to do?

You can you composer version 2.1.3, it doesn’t have this issue.

**Comment by gmbhurgri** [comment]
On Windows 10, using xampp with php 8. Same issue here.

When i rolled back composer to version 2.1.3 it doesn't show the error.

**Comment by Seldaek** [comment]
https://github.com/composer/composer/releases/tag/2.1.5 is out with the fix.

**Comment by japanstation1** [comment]
> 
> 
> This issue is already reported #10020, the only difference is that on Windows it can’t create a directory with such name.

in my case the directory was created; to which I was able to navigate using file explorer but still none of the laravel commands worked.
