### ISSUE TITLE
Not valid JSON error from package during composer install from Satis Repo

### ISSUE THREAD

**Issue by bffake1999** [composer/composer#10026]
**Describe the bug**
I get an error when I try to install composer dependencies from a Satis Repo. Both are hosted on my local machine. When I run composer install, it throws an error:

```
 [Seld\JsonLint\ParsingException]
  “http://localhost:4680/p2/symfony/polyfill-mbstring.json” does not contain valid JSON
  Parse error on line 856:
  ...            },     {    “packages”: {
  ---------------------^
  Expected: ‘STRING’ - It appears you have an extra trailing comma
```

This only happens on one Linux machine running Centos 7. It works correctly on my MAC.

**To Reproduce**
Satis.json
```
{
  “name”: “dylan/composermirror”,
  “homepage”: “https://localhost:4680”,
  “repositories”: [
    {
      “type”: “composer”,
      “url”: “https://packagist.org”
    }
  ],
  “require”: {
    “phpunit/phpunit”: “<15.0",
    “behat/behat”: “<20.0",
    “blueday/behat-html-formatter”: “dev-master”,
    “behat/mink”: “1.7.*@stable”,
    “behat/mink-extension”: “<20.0",
    “behat/mink-goutte-driver”: “<20.0",
    “behat/mink-selenium2-driver”: “<20.0",
    “guzzlehttp/guzzle”: “<20.0",
    “rtheunissen/guzzle-log-middleware”: “<10.0",
    “namshi/cuzzle”: “<10.1",
    “psr/log”: “<10.1",
    “monolog/monolog”: “1.*.*“,
    “envms/fluentpdo”: “1.*.*“,
    “allure-framework/allure-behat”: “<10.1",
    “bentools/guzzle-throttle-middleware”: “<10.0",
    “couscous/couscous”: “<10.1",
    “google/apiclient”: “<10.1"
  },
  “require-dependencies”: true,
  “require-dev-dependencies”: true
}
```
Composer.json on client to download from Satis:
```
{
“name”: “tem/p”,
“description” : “test123",
“repositories”: [
    {
        “type” : “composer”,
        “url” : “http://localhost:4680/”
    }
],
    “require”:{
        “sebastian/diff”: “^4.0",
        “behat/behat”: “<20.0"
    },
“config”: {
    “secure-http”:false
 }
}
```

**Outcome**
After running composer install on the client, it should install without problem but I get the error listed above. 

**Additional context**
PHP Version 7.3.28
Composer Version 2+
I have used multiple version of Composer 2.x+ and it happens with all of them.
Does anybody have any ideas about what causes this error? Is it due to a versioning error or a Linux config error? This bugs happens with 99% of packages I add to my dependency list. 
Thanks.

**Comment by bffake1999** [comment]
If I need more info or worded badly, let me know. This is my first issue/bug I have posted here so I am new. Thank you

**Comment by Seldaek** [comment]
Please report satis issues on satis repo, we are not maintaining it anymore.
