### ISSUE TITLE
Composer.org Website Down ?

### ISSUE THREAD

**Issue by ElectroArmy** [composer/composer#10035]
![Screenshot from 2021-08-03 19-15-01](https://user-images.githubusercontent.com/39894962/128017722-fe680463-f852-4c68-a987-6943131ebbcb.png)

ak1337@ak1337-Inspiron:~$ ./getcomposer.sh 
PHP Warning:  copy(https://getcomposer.org/installer): failed to open stream: Connection timed out in Command line code on line 1
PHP Warning:  hash_file(composer-setup.php): failed to open stream: No such file or directory in Command line code on line 1
ERROR: Invalid installer checksum
rm: cannot remove 'composer-setup.php': No such file or directory
ak1337@ak1337-Inspiron:~$ 

My `composer.json`:

```json
...replace me...
```

Output of `composer diagnose`:

```
...replace me...
```

When I run this command: 

```
...replace me...
```

I get the following output: 

```
...replace me...
```

And I expected this to happen:

**Comment by Seldaek** [comment]
As far as I know the website was not down, but maybe there was a temporary network issue between your network and our servers.
