### ISSUE TITLE
Support wildcard in option ignore-platform-req

### ISSUE THREAD

**Issue by dahaupt** [composer/composer#10045]
When installing or updating packages, it would be useful if all platform requirements could be ignored, except for PHP.

Currently, this is only possible by ignoring each extension individually, e.g.: 
`composer update --ignore-platform-req=ext-json --ignore-platform-req=ext-xml`

or by _faking_ platform requirements in `config.platform`, e.g.:
```
"config": {
    "platform": {
        "ext-json": "7.4",
        "ext-xml": "7.4"
    }
},
```

We have this use case when updating composer projects with Renovate. See details in linked issue(s).

So the subject of this issue could also be:
**Installing Composer dependencies in environments without valid platform requirements while respecting the PHP version requirement**

Related: 
- https://github.com/renovatebot/renovate/issues/2355
- https://stackoverflow.com/questions/65367417/is-there-any-way-to-ignore-platform-req-all-but-keep-one-in-composer-json

**Comment by dereuromark** [comment]
So basically you want

    composer update --ignore-platform-req=ext-*
    
Seems reasonable to me, if this kind of wildcard syntax can be parsed into some PHP comparison checks etc.

**Comment by dahaupt** [comment]
@dereuromark Exactly! 

Basically, we need `--ignore-platform-reqs` without ignoring the PHP version. But supporting wildcards would be useful enough and also helpful for other use cases, I think.

**Comment by dereuromark** [comment]
Maybe also the opposite could be useful then for your case, using `-` prefix to invert?

    composer update --ignore-platform-req=-php

Just spitballing some ideas here for the team to assess.

**Comment by dahaupt** [comment]
@dereuromark My tests have shown that a comma separated list is not yet supported.

Correct me If I am wrong, but running 

```
composer update --ignore-platform-req=!php
``` 

on its own would be useless, since all platform requirements are checked by default.

It would make sense, e.g. by running 
```
composer update --ignore-platform-req=*,!php` 
```
or combined with `--ignore-platform-reqs` as
```
composer update --ignore-platform-reqs --ignore-platform-req=!php
```

**Comment by stof** [comment]
a comma separated list is indeed not supported. To pass multiple values, you need to repeat the `--ignore-platform-req=`

**Comment by dereuromark** [comment]
Sure, this was just spitballing some ideas. Would sure be trivial to add and quite useful over the repeating of such config.
I do that also on some configs to allow a list of params the easy way.

But I don't want to derail too much, the initial topic was still about wildcard support, not making multiple values easier.
I just thought they could be combined maybe.

**Comment by Seldaek** [comment]
It's technically feasible I suppose, to add wildcard support. I am not sure it's really worth it though.

If you are interested in sending a PR.. I think replacing the array|bool for $ignorePlatformReqs in Solver and AutoloadGenerator by a PlatformRequirementFilter object which would contain the list and patterns to ignore and then have methods to check if X is ignored, or if all is ignored (the current `bool true` case), would be the best approach. Otherwise it'll just add even more complexity in those places for a fringe feature.

**Comment by dahaupt** [comment]
@Seldaek Thanks for your feedback!

Our actual goal is to update packages, checking only the PHP version requirement. With a wildcard support, it would be possible, because we could directly exclude all extensions at once.

We would also appreciate any other solution supporting our use case, e.g.:
```
composer update --ignore-platform-reqs-except-php
```
would be a great alternative for us.

**Comment by Seldaek** [comment]
Yeah perhaps we could make it a special `--ignore-platform-req=exts` or something, but IMO the cleanup I mentioned above still makes sense regardless. And at that point supporting wildcard isn't adding much complexity anymore, and it's easier to grasp and more intuitive than a special value. I'd rather not add yet another flag for a very specific use case.
