### ISSUE TITLE
Zip archives are not unpacked correctly. ..

### ISSUE THREAD

**Issue by aungyekyaw-50** [composer/composer#10059]
when I install Packages using composer to tag natural language... it downloaded 'stanford-nlp-tagger' package properly. But it cannot install and extract to the downloaded packages.. help me, pls.. 

<C:\xampp\htdocs\tag>composer require patrickschur/stanford-nlp-tagger
Using version ^0.3.0 for patrickschur/stanford-nlp-tagger
./composer.json has been created
Running composer update patrickschur/stanford-nlp-tagger
Loading composer repositories with package information
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking patrickschur/language-detection (v3.4.2)
  - Locking patrickschur/stanford-nlp-tagger (v0.3.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Downloading patrickschur/language-detection (v3.4.2)
  - Downloading patrickschur/stanford-nlp-tagger (v0.3.0)
  - Installing patrickschur/language-detection (v3.4.2): Extracting archive
  - Installing patrickschur/stanford-nlp-tagger (v0.3.0): Extracting archive
Generating autoload files>

![Untitled](https://user-images.githubusercontent.com/60643904/129473723-1f825cab-d8e0-48ad-8980-1efd5b863f0c.png)

**Comment by GrahamCampbell** [comment]
Install the unzip binary or 7-zip to get full support for zip files. Alternatively, use `--prefer-source`.

**Comment by aungyekyaw-50** [comment]
@GrahamCampbell 
I have already installed 7 zip .. but it did not support to extract the downloaded packages.. how would i do? pls...

**Comment by GrahamCampbell** [comment]
The composer debug output says 7zip is not available.

**Comment by aungyekyaw-50** [comment]
@GrahamCampbell 
Yes ,  The output shows that 7zip is not available... In my OS has unzip utility as 7zip. What is another debug may be?
I reinstalled composer-dependencies manager and modified 7zip and install packages. But the output does not change..... I did this process several times.. Pls, Give  me some ideas.

**Comment by Seldaek** [comment]
Where is 7-zip installed? 

And what error are you seeing with extracting archives? I did not see any infromation in your message except "But it cannot install and extract to the downloaded packages" - from the log you pasted it seems all fine to me.
