### ISSUE TITLE
is there any way to ignore expired ssl certified?

### ISSUE THREAD

**Issue by jmbs22** [composer/composer#10068]
I'm traying to deploy a laravel app, but I'm getting an this error:

--------------------------------------------
[Composer\Downloader\TransportException]
  The "https://larapack.io/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Err
  or messages:
  error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
  Failed to enable crypto
  failed to open stream: operation failed
 ----------------------------------------------

 larapack.io have an expired certified since 4 days ago and they haven't renovate it yet, and they aren't answering their git:
 
 https://github.com/larapack/hook-docs/issues/5
 
 This problem isn't allowing me to deploy an already built laravel app at the server.
 
 I know this error isn't related to composer itself, but I can't find a way to bypass this expired certified from larapack.io

**Comment by Seldaek** [comment]
`composer config secure-http false` will disable SSL verification, which I believe will workaround this problem. However, doing this is generally a terrible idea. If you do it temporarily until larapack fixes their repo that's one thing, but you should remember to remove the option and set it back to its default of true, you can use `composer config secure-http --unset` for that.
