### ISSUE TITLE
Composer won't forward `-V` option to scripts

### ISSUE THREAD

**Issue by Bilge** [composer/composer#10066]
When I run this command: 

```
composer ception -- -V
```

I get the following output: 

```
Composer version 2.1.5 2021-07-23 10:35:47
```

Composer outputs its own version information and exits.

And I expected this to happen:

Composer should run the `ception` script, passing along the `-V` option to it.

**Comment by Seldaek** [comment]
Known issue sadly can't fix with symfony/console 2.x, so it'll have to wait for Composer 2.3, feel free to track https://github.com/composer/composer/issues/6552 instead.
