### ISSUE TITLE
Missing class in autoload_classmap as of 2.1.6

### ISSUE THREAD

**Issue by drjayvee** [composer/composer#10067]
As of v2.1.6, `vendor/composer/autoload_classmap.php` is missing one class present in 2.1.5.

The class is one of four in the same file:
```
$ grep -E "^(abstract )?class" src/util/View.php
abstract class View {
abstract class JSModuleView extends View {
abstract class TwigView extends JSModuleView {
class MaskListView extends TwigView {
```

Here's the relevant `composer.json` config
```json
{
    "autoload": {
        "classmap": [
            "src/"
        ],
        "files": [
            "src/util/DateUtils.php",
            "src/util/i18n.php"
        ]
    },
}
```

Here's the output of `2.1.6`
```
$ composer --version
Composer version 2.1.6 2021-08-19 17:11:08

$ composer -vvv dump-autoload
Running 2.1.6 (2021-08-19 17:11:08) with PHP 7.4.16 on Linux / 5.4.0-81-generic
Reading ./composer.json (/app/composer.json)
Loading config file ./composer.json (/app/composer.json)
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Reading /var/www/.composer/composer.json
Loading config file /var/www/.composer/composer.json (/var/www/.composer/composer.json)
Reading /app/vendor/composer/installed.json
Reading /var/www/.composer/vendor/composer/installed.json
Loading plugin SimpleSamlPhp\Composer\ModuleInstallerPlugin (from simplesamlphp/composer-module-installer)
Generating autoload files
Generated autoload files

$ grep JSModuleView vendor/composer/autoload_classmap.php
```

And here's the same with `2.1.5`
```
$ composer --version
Composer version 2.1.5 2021-07-23 10:35:47

$ composer -vvv dump-autoload
Reading ./composer.json (/app/composer.json)
Loading config file ./composer.json (/app/composer.json)
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Reading /var/www/.composer/composer.json
Loading config file /var/www/.composer/composer.json (/var/www/.composer/composer.json)
Reading /app/vendor/composer/installed.json
Reading /var/www/.composer/vendor/composer/installed.json
Loading plugin SimpleSamlPhp\Composer\ModuleInstallerPlugin (from simplesamlphp/composer-module-installer)
Running 2.1.5 (2021-07-23 10:35:47) with PHP 7.4.16 on Linux / 4.19.104-microsoft-standard
Generating autoload files
Generated autoload files

$ grep JSModuleView vendor/composer/autoload_classmap.php
    'JSModuleView' => $baseDir . '/src/util/View.php',
```

I performed a diff of each version's `autoload_classmap.php`, and this missing class is the only difference.

Would it help if I sent the file `View.php`?

**Comment by Seldaek** [comment]
Hey, yes it would definitely help if you can share the source. You can post it to gist.github.com too if it's too huge to have inline here.

**Comment by Seldaek** [comment]
It's most likely a regression from https://github.com/composer/composer/pull/10050 - but without a repro case it's going to be hard to pinpoint :) /cc @jrfnl FYI

**Comment by jrfnl** [comment]
Happy to take a look once I have access to the file.

**Comment by drjayvee** [comment]
I was able to narrow it down thanks to Seldaek's hint about the regression.

```php
<?php

abstract class View {
	
	public function printJavaScript(): void {
		echo <<<EOF

		EOF;
	}
}

abstract class JSModuleView extends View {

	final public function printJavaScript(): void {
		echo <<<EOF
	
EOF;
	}
}
```

Removing *either* `echo` statement fixes the issue.

**Comment by jrfnl** [comment]
@drjayvee Hi Jeroen, thanks for that code sample, that's really helpful.

The problem was with both heredocs using the same delimiter marker. I've got a fix ready. Just adding some more tests to safeguard it.

**Comment by jrfnl** [comment]
@drjayvee I've opened PR #10072 to fix this. It would be great if you would be able to test it,

@Seldaek My apologies for introducing this issue. With the additional tests now added, this should hopefully be prevented in the future.

**Comment by drjayvee** [comment]
@jrfnl I checked out your branch, ran `composer install` in its root, then ran `../jrfnl-composer/bin/composer dump-autoload` in our repo. The missing class is back, so I can confirm the fix, even in our original (vastly more complicated 😄) source.

Thanks for the quick response all!
