### ISSUE TITLE
fatal: repository 'https://github.com/acquia/composer-scaffold.git.git/' not found

### ISSUE THREAD

**Issue by Jiju-chandran** [composer/composer#10081]
When running **ddev composer install** i am getting this issue. For creating drupal 8 project, i am using composer 1.10.22. I have cleared composer cache. But this issue occurs. Also i didnt have any private repo for acquia/composer-scaffold.

issue:

```
 - Installing acquia/composer-scaffold (dev-master 37b9bc8): Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+mars-web+2021-08-28+1530
to retrieve a token. It will be stored in "/home/jiju/.composer/auth.json" for future use by Composer.
Token (hidden):
Token stored successfully.
Cloning 37b9bc857c
    Failed to download acquia/composer-scaffold from source: Failed to execute git clone --no-checkout -- 'https://***:***@github.com/acquia/composer-scaffold.git.git' '/var/www/html/vendor/acquia/composer-scaffold' && cd '/var/www/html/vendor/acquia/composer-scaffold' && git remote add composer -- 'https://***:***@github.com/acquia/composer-scaffold.git.git' && git fetch composer && git remote set-url origin -- 'https://github.com/acquia/composer-scaffold.git.git' && git remote set-url composer -- 'https://github.com/acquia/composer-scaffold.git.git'

Cloning into '/var/www/html/vendor/acquia/composer-scaffold'...
remote: Repository not found.
fatal: repository 'https://github.com/acquia/composer-scaffold.git.git/' not found

    Now trying to download from dist
  - Installing acquia/composer-scaffold (dev-master 37b9bc8): Downloading (failed)
Installation failed, reverting ./composer.json to its original content.


  [Composer\Downloader\TransportException]
  The "https://api.github.com/repos/acquia/composer-scaffold/zipball/37b9bc857c6cbabd796ca0bc7d1ee000b8c91c13" file could not be downloaded (HTTP/1.1 404 Not Found)
```
![composer_issue](https://user-images.githubusercontent.com/89123271/131224808-92b1569b-e885-4616-bf45-292afcf3861d.png)

**Comment by Seldaek** [comment]
Please make sure you renew/delete the github token you created at https://github.com/settings/tokens as the token got leaked here in the trace you posted.

I'd suggest you try using `composer self-update --2` to get the latest Composer version and try again with that though.

**Comment by Jiju-chandran** [comment]
Thanks, I have already deleted that token. In my case drupal 8 support only composer 1.x version. If i update the composer , its leads to dependency issues.

**Comment by Seldaek** [comment]
OK I see.

I had a closer look and it seems the issue is https://github.com/acquia/composer-scaffold is gone. I guess @danepowell or whoever was in charge deleted it or made it private. The package is abandoned too on packagist.org.. I am not sure what you can use instead but hopefully you find a good alternative.

**Comment by danepowell** [comment]
Indeed, that package is abandoned, you should stop using it. It provided no functional benefit anyway, given recent changes to Drupal core.

We marked it as abandoned for a month or two before deleting it from Github, you should have received abandonment notices from Composer during that time. If there's something else I can do to help users in this situation, let me know.

**Comment by Seldaek** [comment]
I guess the best thing to do would have been archiving the repo on github instead of deleting it outright, as that pulls it out from anyone relying on it. But anyway the path forward is clear here I guess, people have to get rid of that dependency.
