### ISSUE TITLE
Classes using Heredoc/Nowdoc not found

### ISSUE THREAD

**Issue by vody105** [composer/composer#10091]
Composer version: 
2.1.6 2021-08-19 17:11:08

PHP Version: 
8.0.5

Type: 
Bug

Problem:
Classes containing Nowdoc or Heredoc in both class attribute and property attribute at the same time are not present in `autoload_classmap.php` when `--classmap-authoritative` is used.

How to reproduce:
Downloading this minimal example https://github.com/vody105/composer-bug and running
 - `composer dump-autoload --classmap-authoritative`
 - `php index.php`

Afaik this issue was introduced in 2.1.6 by https://github.com/composer/composer/pull/10050.

**Comment by Seldaek** [comment]
Should be fixed in snapshot build already (by https://github.com/composer/composer/pull/10072), if you can check with `composer self-update --snapshot` that'd be good.

**Comment by vody105** [comment]
Snapshot build is working fine. 👍
