### ISSUE TITLE
Move credentials for "Inline http-basic" and "Custom token authentication" from composer.json to auth.json

### ISSUE THREAD

**Issue by yaroslawww** [composer/composer#10105]
Is it possible to move functionality (credentials) [Inline http-basic](https://getcomposer.org/doc/articles/authentication-for-private-packages.md#inline-http-basic) and
[Custom token authentication](https://getcomposer.org/doc/articles/authentication-for-private-packages.md#custom-token-authentication) from `composer.json` file to `auth.json` file or `COMPOSER_AUTH` variable (I think this is same as auth.json)?

Sometimes we need to add different credentials for each package separately but use the same domain:
```
"repositories": [
        {
            "type": "vcs",
            "url":  "https://deploy:2DvdfJshdBHsdaa3asd@some.gitlab.instance.com/pr/package1.git"
        },
        {
            "type": "vcs",
            "url":  "https://bot:Imasdfk87asddfass@some.gitlab.instance.com/other-pr/other-package.git"
        }
    ],
```
At the same time we need to bypass any credentials in itself `composer.json` file.

**Comment by Seldaek** [comment]
This isn't currently possible, except by using something like [Private Packagist](https://packagist.com) which can consolidate all your repos with different credentials in one Composer repository that can be used with a single credential then.

**Comment by yaroslawww** [comment]
Thank you.
