### ISSUE TITLE
ComposerRepository::loadAsyncPackages() fails when the network is down

### ISSUE THREAD

**Issue by nicolas-grekas** [composer/composer#10116]
With a warm HTTP cache, I expected composer to still be able to proceed.

But after I shutdown my local network, eg `composer create-project symfony/skeleton` fails with a curl error.

I suspect that the promises in `ComposerRepository::loadAsyncPackages()` are missing the part to reuse the data from the cache when an transport exception occurs.

**Comment by nicolas-grekas** [comment]
(this works in composer 1 btw)

**Comment by Seldaek** [comment]
Setting COMPOSER_DISABLE_NETWORK=1 should fix this in composer 2, but anyway I agree it should behave nicer by default if possible. Will fix this.
