### ISSUE TITLE
composer command incorrect

### ISSUE THREAD

**Issue by raxithrai** [composer/composer#10113]
hello,

can anyone please help me with following command:

"composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.4.2 <install-directory-name>

The syntax of the command is incorrect."

Thanks for all your help!.
![Screenshot (370)](https://user-images.githubusercontent.com/53504686/133882837-9160a3bf-76ef-44f2-9d11-c20e9b013f48.png)

**Comment by SuccessGo** [comment]
hi @raxithrai, please change `<install-directory-name>` to a specific name like `MyName` instead and try again.
