### ISSUE TITLE
Package PHP binaries can not include the correct autoload.php, when installed via PathRepository as symlink

### ISSUE THREAD

**Issue by helhum** [composer/composer#10119]
My `composer.json`:

```json
{
    "repositories": {
        "packages": {
            "type": "path",
            "url": "packages/*"
        }
    },
    "require": {
         "vendor/package-with-bin": "@dev"
    }
}
```

When I run this command:

```
composer update
```

I will get the `vendor/package-with-bin` installed in vendor folder as a symlink, to `packages/` folder.

Now trying to execute the binary (which is linked to `vendor/bin`), the PHP binary usually includes
the autoload.php with code like this:

```php
$files       = [__DIR__ . '/../vendor/autoload.php', __DIR__ . '/../../../autoload.php'];
$loader      = null;

foreach ($files as $file) {
    if (file_exists($file)) {
        $loader = require $file;

        break;
    }
}

```

Now, sine `__DIR__` resolves to `packages/package-with-bin`, the code above fails, as it expects the code to be installed in the vendor folder.

And I expected this to happen:

Currently there is no way for packages with a PHP binary can reliably obtain the path to the correct `autoload.php`, when they are not directly installed (and not symlinked) into the vendor folder.

The only idea I can come up with is to:

1. Always create proxy files for PHP enabled binaries
2. Expose the path to the `autoload.php` in the proxy, which the PHP binary scripts can access

e.g. something like this

```php
#!/usr/bin/env php
<?php

# Proxy file created by Composer

$GLOBALS['__composer_autoload_path'] = __DIR__ . '/../autoload.php';
require __DIR__ . '/../vendor/package-with-bin/php-script';
```

in `vendor/package-with-bin/php-script` it could be checked for `$GLOBALS['__composer_autoload_path']`
and the autoload.php could be included from there like:

```php

$files       = [__DIR__ . '/../vendor/autoload.php', $GLOBALS['__composer_autoload_path'] ?? __DIR__ . '/../../../autoload.php'];
$loader      = null;

foreach ($files as $file) {
    if (file_exists($file)) {
        $loader = require $file;

        break;
    }
}

```

Any thoughts on that?

I'm happy to provide a PR in case this is considered fixing.

**Comment by Seldaek** [comment]
Always creating a proxy isn't as easy as it seems, the current code has to jump through some hoops to get rid of shebangs on top of php files: https://github.com/composer/composer/blob/master/src/Composer/Installer/BinaryInstaller.php#L220-L242

So that means for phar files we could not do this at all.. 

But yes for other files what you suggest should be doable. I just wonder if it's worth it having everything proxied instead of symlinked, and adding even more complexity to this code to solve this use case which is rather an exception.

**Comment by helhum** [comment]
Thanks @Seldaek for having a look at this. My intention for sure isn't to make something more complex to cover an edge case.

I was wondering though, if introducing a new API for PHP enable Composer binaries (which in my experience is the case for 95% of the composer binaries, or is my impression wrong here?), could reduce the complexity of the current binary installer and the code current PHP Composer binaries must use to get hold of the autoload.php/ the class loader.

But you know, what? I could create a Composer Plugin, that implements that, test this in practice and if it turns out to be useful, it could be added to any future Composer version.

**Comment by Seldaek** [comment]
I wouldn't find a plugin replacing the binary installer to be a great idea ;) And doing anything to the binary files after install would probably be super hacky and potentially lead to problems down the line.

What kind of API are you thinking of? Is it just about the autoload.php bootstrapping? Do you see other needs we could help people with?

**Comment by helhum** [comment]
> I wouldn't find a plugin replacing the binary installer to be a great idea ;) And doing anything to the binary files after install would probably be super hacky and potentially lead to problems down the line.

My idea was to define PHP binaries in the extra section and install those into bin-dir as well, not to mess with the current BinaryInstaller or even the installed binaries.

> What kind of API are you thinking of? Is it just about the autoload.php bootstrapping? Do you see other needs we could help people with?

Basically that's it. I was thinking about not defining a binary path, but a class reference, pretty much like in script section. Then Composer (or the plugin) could always create appropriate proxy files.

Something along those lines:

`composer.json`
```json
{
	"name": "vendor/bin-packages",
	"bin": {"class": "Vendor\\Class\\Binary", "bin-name": "vendor-binary"}
}
```

`Binary.php`
```php
<?php
namespace Vendor\Class;

class Binary implements \Composer\BinaryInterface {
    public static function execute(\Composer\ClassLoader $loader)
	{
      // Do stuff here
    }
}
```

`vendor/bin/vendor-binary`
```php
#!/usr/bin/env php
<?php

// Composer generated proxy file

$classLoader = require __DIR__ . '/../autoload.php';

\Vendor\Class\Binary::execute($classLoader);

```

**Comment by Seldaek** [comment]
So looking back at the first commits which added binaries, I can't really see a good reason for using symlink. I think it was just a "why not" thing, but it doesn't seem to add any value, so I suppose we could simply generate proxies always at least for php files, and defining a global var there with the autoloader path shouldn't be too hard.

If you like to take a look at implementing that why not I'd say, just to get a feel for how much code it adds.. but it sounds reasonable. I don't think I'd add a binary interface nor change how binaries are registered though.
