### ISSUE TITLE
Composer 'permission denied' on Windows 7

### ISSUE THREAD

**Issue by papconst** [composer/composer#10111]
When I run this command (Windows 7! Please do not tell me make chmod 775 etc!)
```
composer require kartik-v/yii2-widget-select2
```
(both as admin and my user)

I get the following output: 

```
[ErrorException]
file_get_contents(G:\Composer): failed to open stream: Permission denied
```
Command 'composer create-project --prefer-dist yiisoft/yii2-app-basic basic' worked OK.

In internet there is no way to make this command work, I've tried everything. 
Folder is writeable and not RO, privileges granted to ALL, Composer is reinstalled many times to different folders. I've even tried old version down to 1.10.17.
Similar error was [here](https://github.com/composer/composer/issues/3579), but it is marked as fixed.
Have no idea, what to do.

**Comment by helhum** [comment]
> Have no idea, what to do.

You could start with following the issue template, so that we get more information about your environment and where exactly the error occurs. Especially adding the `-vvv` option and posting the full output is crucial. But also `composer diagnose` helps for a better understanding what is happening.

**Comment by naohwen** [comment]
Windows 7 32bit

**Comment by naohwen** [comment]
![微信图片_20220122165203](https://user-images.githubusercontent.com/82444429/150631831-9857f855-630f-4a6d-a021-74f267349f06.png)
![微信图片_20220122165200](https://user-images.githubusercontent.com/82444429/150631837-c831d575-e5bc-4b17-b105-282180772914.png)
