### ISSUE TITLE
How to get specific branch

### ISSUE THREAD

**Issue by ShadowMonster** [composer/composer#10112]
Hi
I'm pulling my hair over it can someone light me up please. I need get specific branch  from github repo like example https://github.com/joshfraser/PHP-Name-Parser/ i need get _clives-optimizations branch_

My `composer.json`:

I'm trying something like:
```
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "joshfraser/php-name-parser",
                "version": "clives-optimizations",
                "type": "package",
                "source": {
                    "url": "https://github.com/joshfraser/PHP-Name-Parser",
                    "type": "git",
                    "reference": "clives-optimizations"
                }
            }
        }
    ],
```

and
```
    "require": {
        "joshfraser/php-name-parser": "clives-optimizations",
    },
```

It give me error of wrong version. I'm using 2.0.9.

**Comment by stof** [comment]
Versions that are not semver versions are required to start with `dev-`.
The VCS repositories of composer are using `dev-<branch>` as the version for the branch `<branch>`.

Side note: when your git repository contains a composer.json, it is much better to use a VCS repository in your config instead of a package repository. It avoids having to duplicate the whole metadata of the package (for instance, your code snippet misses the autoload configuration). The use case for `type: package` is for when the package source code does not contain the composer.json.

**Comment by ShadowMonster** [comment]
Thank You for this tips.

I try use something like that:

```
"repositories": [
        {
            "type": "package",
            "package": {
                "name": "joshfraser/php-name-parser",
                "version": "dev-clives-optimizations",
                "type": "package",
                "source": {
                    "url": "https://github.com/joshfraser/PHP-Name-Parser",
                    "type": "git",
                    "reference": "clives-optimizations"
                }
            }
        }
    ],

"require": {
        "joshfraser/php-name-parser": "dev-clives-optimizations",
    },
```
But still is getting master branch instead on composer install. I cleaned composer cache.
I try sometime ago VCR on this example but it did nto work - probably because clives-optimizations branch do not have composer.json file.

For now my work around it is adding simple script like:
```
"scripts": {
        "pre-autoload-dump": [
            "cd vendor/joshfraser/PHP-Name-Parser && git checkout clives-optimizations"
        ]
    },
```

But I would like really know how to get targeted branch in first place.

**Comment by stof** [comment]
I tried to reprodue this with this composer.json:

```json
{
"repositories": [
        {
            "type": "package",
            "package": {
                "name": "joshfraser/php-name-parser",
                "version": "dev-clives-optimizations",
                "type": "package",
                "source": {
                    "url": "https://github.com/joshfraser/PHP-Name-Parser",
                    "type": "git",
                    "reference": "clives-optimizations"
                }
            }
        }
    ],

"require": {
        "joshfraser/php-name-parser": "dev-clives-optimizations"
    }
}
```

and I'm properly getting the `clives-optimizations`. So your reproducing case clearly misses something

**Comment by ShadowMonster** [comment]
Thank You for checking it.
I will try get on bottom of it then on my side.
