### ISSUE TITLE
@dev doesn't override prefer-stable

### ISSUE THREAD

**Issue by chx** [composer/composer#10120]
When `composer config prefer-stable true` is set, even with `minimum-stability: dev`, a  composer `require  'drupal/bricks:2.0.*@dev' ` wants to install `2.0.1` instead of `2.0.2-beta2`. (Asking for the specific version install that.)

**Comment by helhum** [comment]
I'd say this is expected. `prefer-stable` means: don't install unstable newer versions unless these newer versions are required in the dependency chain

**Comment by chx** [comment]
If `@dev` doesn't override the preference then what does? Would it be possible to set preference per package?

**Comment by xabbuh** [comment]
`@dev` means that you allow development versions in case the solver is not able to find a stable release. In your case I guess a constraint like `2.0.*@dev,>2.0.1` should do the trick.

**Comment by helhum** [comment]
> If `@dev` doesn't override the preference then what does? Would it be possible to set preference per package?

What is exactly what you want to achieve? If you need version 2.0.2 or higher for your project, tell Composer to have 2.0.2 as minimum requirement e.g. with `composer require 'drupal/bricks:^2.0.2@dev'`

**Comment by helhum** [comment]
> In your case I guess a constraint like `2.0.*@dev,>2.0.1` should do the trick.

AFAIK comma means "or". So this constraint won't enforce version 2.0.2-beta2 to be installed.

**Comment by stof** [comment]
@helhum the comma means "and". The "or" is `||` (or `|` for the legacy format)

**Comment by helhum** [comment]
> @helhum the comma means "and". The "or" is `||` (or `|` for the legacy format)

Ah, of course. Thanks for the heads up!

**Comment by Seldaek** [comment]
Closing as per the above comments which are absolutely right, thanks everyone.

To give more details, there is no way to change the policy (prefer-stable or the default prefer-highest) per package, only the stability can be changed that way. See https://github.com/composer/composer/blob/master/src/Composer/DependencyResolver/DefaultPolicy.php#L31 for details. I don't think this is really something we want to change as it would change assumptions about what stability flags do.
