### ISSUE TITLE
config.cache-dir is taken into account too late

### ISSUE THREAD

**Issue by steevanb** [composer/composer#10125]
Hi,

I think `config.cache-dir` is taken into account a bit too late. Composer cache is written is this directory, it's ok, but first it seems like a directory `$COMPOSER_HOME/cache/repo/https---repo.packagist.org/` is created before reading `config.cache-dir`.

My `composer.json`:

```json
{
    "require": {
        "symfony/options-resolver": "5.3.*"
    },
    "config": {
        "cache-dir": "/app/var/composer/cache"
    }
}
```

Output of `composer diagnose`:

```
Cannot create cache directory /composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 2.1.8
PHP version: 8.0.11
PHP binary path: /usr/bin/php8.0
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
cURL version: 7.68.0 libz 1.2.11 ssl OpenSSL/1.1.1f
zip: extension present, unzip present, 7-Zip not available
```

When I run this command:

```
composer up
```

I get the following output:

```
Cannot create cache directory /composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Updating dependencies
Lock file operations: 4 installs, 0 updates, 0 removals
  - Locking symfony/deprecation-contracts (v2.4.0)
  - Locking symfony/options-resolver (v5.3.7)
  - Locking symfony/polyfill-php73 (v1.23.0)
  - Locking symfony/polyfill-php80 (v1.23.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files
4 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

And I expected this to happen:

First line `Cannot create cache directory...` show `cache.config-dir` is not taken into account, it should be `/app/var/composer/cache/repo/https---repo.packagist.org/` (who is created at the end).

**Comment by Seldaek** [comment]
Can you perhaps run this with `-vvv` to get full debug output? I am assuming it fails when loading the global composer config which is in your COMPOSER_HOME which I assume is `/composer` here. Most likely there is a /composer/composer.json present so it loads it, but there is no cache dir present and it's not writable so it warns about that.

If no composer.json is present there it shouldn't load it at all and thus not warn. I am not sure what your setup looks like exactly, but I think everything behaves as it should.

**Comment by steevanb** [comment]
Hi,

Here is the begin of the result for `composer up -vvv` (don't care about next steps who just download things):

`
Running 2.1.8 (2021-09-15 13:55:14) with PHP 8.0.11 on Linux / 5.4.72-microsoft-standard-WSL2
Reading ./composer.json (/app/composer.json)
Loading config file ./composer.json (/app/composer.json)
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/app): git branch -a --no-color --no-abbrev -v
Executing command (/app): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (/app): git log --pretty="%H" -n1 HEAD
Executing command (/app): hg branch
Executing command (/app): fossil branch list
Executing command (/app): fossil tag list
Executing command (/app): svn info --xml
Reading /composer/composer.json
Loading config file /composer/composer.json (/composer/composer.json)
Cannot create cache directory /composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache`

You're right i have a `composer.json` in `$COMPOSER_HOME`. 
I need to change cache-dir in this `composer.json`. To me it's not a nice fix because i change the `cache-dir` of global `composer.json` but i want to change only the one of my project.

Don't you think Composer should not take `$COMPOSER_HOME/composer.json` `cache-dir` configuration into account when we don't use `composer global`?

**Comment by Seldaek** [comment]
Nope, $COMPOSER_HOME/composer.json is the global composer project and it gets loaded to load global plugins, and it should IMO get loaded with the cache dir that it expects/is configured to run with.

The issue really is that the warning you see is misleading, and possibly should not be there during init but only on cache write. I'll need to take another look if I can fix this.
