### ISSUE TITLE
Error - failed to download. OpenSSL SSL_Connect: Connection reset by peer connection to api.github.com:443

### ISSUE THREAD

**Issue by NNV111** [composer/composer#10124]
Trying to install the apigee_edge module (version 8.x-1.24) via composer in Drupal 9.2.6 
composer require 'drupal/apigee_edge:^1.24'
gettting the below error. 
PHP version - 7.2.24
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/87411570/135023441-1a8f313b-1ec6-4ffa-9f42-df70e3458cd2.png)

Have disabled the tls with the below command. It throws the same error
composer config disable-tls false

Please let me know on what needs to be done to fix this issue.
Thanks much!

**Comment by mvorisek** [comment]
it seems something is broken and request is not retried under some conditions:

https://github.com/atk4/data/runs/4232397249?check_suite_focus=true#step:7:13

```
 Error: curl error 35 while downloading https://repo.packagist.org/packages.json: OpenSSL SSL_connect: Connection reset by peer in connection to repo.packagist.org:443 

                                                                                                                                                                   
  [Composer\Downloader\TransportException]                                                                                                                         
  curl error 35 while downloading 
https://repo.packagist.org/packages.json:
 OpenSSL SSL_connect: Connection reset by peer in connection to repo.packagist.org:443  
```

**Comment by Seldaek** [comment]
See https://github.com/composer/composer/commit/7fc90008349fe3b22f481a795e183f38dbdeab42 - but this will be in 2.2 only.

**Comment by mvorisek** [comment]
thank you ❤️

**Comment by Raxmatillo** [comment]
OpenSSL SSL_connect: Connection was reset in connection to github.com:443
 help Me
