### ISSUE TITLE
Composer\Package\Archiver\ArchiveManager bug generating ZIP file

### ISSUE THREAD

**Issue by lfontana-schema31** [composer/composer#10126]
I'm running SATIS, on MACOS.
All the files in the zip created have "private" prefix (private.gitignore, privatecomposer.json, privatesrc).
I found inside Composer\Package\Archiver
```php
// $filepath = "/private/var/folders/ss/ttbpjpg91pq1853r74cv740c0000gp/T/composer_archive61541dcb55728/.php_cs";
// $sources = "/var/folders/ss/ttbpjpg91pq1853r74cv740c0000gp/T/composer_archive61541dcb55728";

$localname = str_replace($sources.'/', '', $filepath);
```
So $localname will have "private" prefix 

$sources is valued in Composer\Package\Archiver\ArchiveManager so I changed like this
```php
// Directory used to download the sources
            $filepath = sys_get_temp_dir().'/composer_archive'.uniqid();
            $filesystem->ensureDirectoryExists($filepath);
            $splInfo= new \SplFileInfo($filepath);
            $sourcePath = strtr($splInfo->getPath()."/".$splInfo->getFilename(), '\\', '/');
````

I don't know if this a problem of sys_get_temp_dir or SplFileInfo

Sorry for my very bad english

**Comment by Seldaek** [comment]
Seems related to #10099 - could you try to see if changing ZipArchiver line 33 to `        $sources = $fs->normalizePath(realpath($sources));` fixes it? Just adding the realpath there.

**Comment by Seldaek** [comment]
Closing as no feedback..

**Comment by jasonmccreary** [comment]
@Seldaek, I can confirm this fixes the issue for me on MacOS. The underlying culprit is `sys_get_temp_dir()` as it returns `/var/folders/...`, however, `/var/` is a symlink to `/private/var/`.

I would open a PR, but my guess is this needs to be fixed in more places than the `ZipArchiver`.

**Comment by jasonmccreary** [comment]
@Seldaek, I understand. I did look at paid Packagist, but this is kind of a new venture for me and it doesn't generate revenue yet. If it does, I'm glad to consider switching. Just need to understand pricing better (as sliders don't change anything for me)
