### ISSUE TITLE
composer fails to access api.github.com

### ISSUE THREAD

**Issue by shradhabanerjee** [composer/composer#10127]
My issue is composer is unable to access https://api.github.com/. I had lost the access of GitHub as my third party authentication app was lost with my mobile. So I got the access to GitHub after approval of my request. I have a previously generated personal access token which is set in composer's auth.json.

**Note:** I cannot update composer version as it won't work with the project right now. I am using composer in vagrant box.

**composer --version** : Composer version 1.9.0 2019-08-02 20:55:32

My `composer.json`:

{
  "name": ORGANISATION,
  "description": ORGANISATION_DESC,
  "homepage": ORGANISATION_SITE,
  "repositories": [
    {
      "type": "vcs",
      "url": "git@github.com: ORGANISATION/ecommerce-api-php.git"
    },
}

**Output of `composer diagnose`:**

Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.laminas-api-tools/api-tools-configuration : exact version constraints (1.3.3) should be avoided if the package follows semantic versioning
require.googleads/googleads-php-lib : exact version constraints (40.0.0) should be avoided if the package follows semantic versioning
require.dragonmantank/cron-expression : exact version constraints (2.3.0) should be avoided if the package follows semantic versioning
require.bigcommerce/api : exact version constraints (4.0.0) should be avoided if the package follows semantic versioning
require.springimport/magento2-api-v1 : unbound version constraints (*) should be avoided
require.belazor/zf-rate-limit : exact version constraints (1.6.2) should be avoided if the package follows semantic versioning
require.microsoft/microsoft-graph : exact version constraints (1.16.0) should be avoided if the package follows semantic versioning
require.stripe/stripe-php : exact version constraints (7.76.0) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: FAIL
[Composer\Downloader\TransportException] The 'https://api.github.com/' URL could not be accessed: HTTP/1.1 400 Bad Request

Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (1.9.0 => 2.1.8)
Composer version: 1.9.0
PHP version: 7.3.9
PHP binary path: /usr/bin/php7.3

**When I run this command: composer diagnose -vvv**

Reading ./composer.json
Loading config file /home/vagrant/.composer/auth.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/var/www/sando): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /home/vagrant/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 1.9.0 (2019-08-02 20:55:32) with PHP 7.3.9-1+ubuntu18.04.1+deb.sury.org+1 on Linux / 4.15.0-55-generic
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Checking composer.json: Reading ./composer.json
WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.laminas-api-tools/api-tools-configuration : exact version constraints (1.3.3) should be avoided if the package follows semantic versioning
require.googleads/googleads-php-lib : exact version constraints (40.0.0) should be avoided if the package follows semantic versioning
require.dragonmantank/cron-expression : exact version constraints (2.3.0) should be avoided if the package follows semantic versioning
require.bigcommerce/api : exact version constraints (4.0.0) should be avoided if the package follows semantic versioning
require.springimport/magento2-api-v1 : unbound version constraints (*) should be avoided
require.belazor/zf-rate-limit : exact version constraints (1.6.2) should be avoided if the package follows semantic versioning
require.microsoft/microsoft-graph : exact version constraints (1.16.0) should be avoided if the package follows semantic versioning
require.stripe/stripe-php : exact version constraints (7.76.0) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: Executing command (CWD): git config color.ui
Downloading http://repo.packagist.org/packages.json
OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: Downloading https://repo.packagist.org/packages.json
OK
Checking github.com oauth access: Downloading https://api.github.com/
FAIL
[Composer\Downloader\TransportException] The 'https://api.github.com/' URL could not be accessed: HTTP/1.1 400 Bad Request

Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: Downloading https://getcomposer.org/versions
You are not running the latest stable version, run `composer self-update` to update (1.9.0 => 2.1.8)
Composer version: 1.9.0
PHP version: 7.3.9
PHP binary path: /usr/bin/php7.3

**And I expected this to happen:**
I expect to do the composer update / install, let me access the api.github.com and update my vendor directory.
I cannot use new token format of GitHub in auth.json for setting up new token for composer, since the new token format wont work with old composer version & new composer version wont work with my project.
If I use new token format in auth.json I get the following error: 

<img width="825" alt="Screenshot 2021-09-28 at 10 06 26 PM" src="https://user-images.githubusercontent.com/46675689/135259717-ea338d5e-06ae-4554-b0b8-0cf359e748d2.png">
<img width="1434" alt="Screenshot 2021-09-27 at 8 19 11 PM" src="https://user-images.githubusercontent.com/46675689/135259750-28985446-39bc-442f-bcc0-1cc843971306.png">

Thanks in advance.

**Comment by stof** [comment]
> I cannot use new token format of GitHub in auth.json for setting up new token for composer, since the new token format wont work with old composer version & new composer version wont work with my project.

If composer 2 does not work in your project, you could at least update to the latest version of Composer 1.x (with `composer self-update --1`), which also contains the patch for the new github token format.
