### ISSUE TITLE
GPG sign the installer?

### ISSUE THREAD

**Issue by dzuelke** [composer/composer#10139]
Hi!

The hash for `composer-setup.php` recently changed.

It is of course possible to use https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md, where the signature is pulled off a GitHub Pages location, but assuming someone gets hold of the "keys to the kingdom", it may happen that they were able to pivot from getcomposer.org to GitHub Pages, or vice versa.

Wouldn't it be useful to GPG sign the installer {instead,as well} for folks who want to programmatically install Composer?

**Comment by Seldaek** [comment]
Sorry but no I am not going to spend energy on this atm. 

The hash changes rarely, you can also use a hardcoded URL to the installer like https://raw.githubusercontent.com/composer/getcomposer.org/ce25411cc528444e8c3c60775bde77e01921a1ef/web/installer which contains the commit hash and then hardcode the signature, and update that periodically if needed.
