### ISSUE TITLE
Can not update lock file if something wrong with packages

### ISSUE THREAD

**Issue by speller** [composer/composer#10143]
I have a working set of packages with a valid `composer.lock` file. Now I want to add a script to `composer.json` and update the lock file hash without updating dependencies. But it fails:

```
composer update --lock --no-scripts
Gathering patches for root package.
Loading composer repositories with package information
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - amasty/module-banners-lite 1.0.19 requires amasty/base >=1.12.15 -> found amasty/base[1.12.15] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires amasty/module-banners-lite == 1.0.19.0 -> satisfiable by amasty/module-banners-lite[1.0.19].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

Why does it claims anything about packages at all if I just want to update the lock file hash? 
Composer version 2.1.5 in a Magento 2 setup.

If I run `composer update` it works perfectly.

**Comment by speller** [comment]
There were no manual edits. The current lock file was created a couple of months ago. 

Why composer check for dependencies if it was asked for the hash update only? Also, when I run the normal update it resolves all dependencies correctly and finishes without errors.

**Comment by hostep** [comment]
This happens because of [this discussion](https://github.com/composer/composer/discussions/10063).
Amasty is one of those two vendors I was talking about over there and it's super annoying what they are doing ...
