### ISSUE TITLE
Installation failed, reverting ./composer.json and ./composer.lock to their original content.

### ISSUE THREAD

**Issue by biosolex** [composer/composer#10141]
hi,

i try to install one extension via Composer but i have a problem.

i run this command

composer require sparsh/magento-2-advanced-sorting-extension:1.1.0

this message: 

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

and after this message

[RuntimeException]                                                                           
  The `url` supplied for the path (m2/var/composer_home/cache/repo) repository does not exist  

how can i solve?

thanks

My `composer.json`:

```json
...replace me...
```

Output of `composer diagnose`:

```
...replace me...
```

When I run this command: 

```
...replace me...
```

I get the following output: 

```
...replace me...
```

And I expected this to happen:

**Comment by imme-emosol** [comment]
The install guide on https://www.sparsh-technologies.com/magento-extensions/magento-2-advanced-sorting-extension does not seem to mention using composer.
