### ISSUE TITLE
Raising the PHPStan level to 6

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#10159]
I have laid down the ground work for reaching level 6 by typing all class properties and interface methods throughout the codebase, which should already help ensure that types are correct when they get added/copied to getters and such.

I definitely could use help though in reaching level 6, because it's a ton of work left (1465 errors for `src/`, 400 errors for `tests/`).

If you are interested in helping, here is how to go about it:

# Setup a Composer environment first if you haven't

- `git clone https://github.com/composer/composer`
- `cd composer && wget https://getcomposer.org/composer.phar && php composer.phar install`

# Setup the env for PHPStan-usage

This requires PHP 7.4 (it won't run with php8 currently due to reasons, don't try to make it do that)

- `php7.4 composer.phar phpstan-setup` to get phpstan installed in the project - make sure you have a composer.phar or some global composer install to run this command with, you can't run phpstan-setup with bin/composer as it replaces parts of the vendor dir and it'll break the install

# Running PHPStan

- Pick a single sub-namespace and focus work on one area, otherwise it's too many errors and also we risk having multiple people doing the same work. Ideally you can comment here to claim a namespace if you're gonna work on it.
- Change level from 5 to 6 in `phpstan/config.neon`
- Run it with the sub-path you are interested in e.g. `php7.4 vendor/bin/phpstan analyse --configuration=phpstan/config.neon src/Composer/Package/`

# Keep in mind

- If you are unsure about some type, rather leave it undefined/erroring than use `mixed` or something equally vague, leave it for someone else to fill the gap later, because reviewing the whole code to find inappropriate mixed-usage is going to be near impossible.
- The main focus is src/ IMO. Typing the tests can't hurt, but it might be a mess in places as some of that code is very old and using php 5.3-compatible patterns.

Thanks in advance to any volunteer :)

# Status

Pick one that's not checked, and claim below in comments please. 

- [x] src/Composer https://github.com/composer/composer/pull/10213
- [x] ├── Autoload https://github.com/composer/composer/pull/10179
- [x] ├── Command https://github.com/composer/composer/pull/10214
- [x] ├── Config https://github.com/composer/composer/pull/10182
- [x] ├── Console https://github.com/composer/composer/pull/10183
- [x] ├── DependencyResolver https://github.com/composer/composer/pull/10178
- [x] ├── Downloader https://github.com/composer/composer/pull/10193
- [x] ├── EventDispatcher https://github.com/composer/composer/pull/10192
- [x] ├── Exception https://github.com/composer/composer/pull/10192
- [x] ├── Installer https://github.com/composer/composer/pull/10192
- [X] ├──  IO https://github.com/composer/composer/pull/10166
- [x] ├── Json https://github.com/composer/composer/pull/10172
- [x] ├── Package https://github.com/composer/composer/pull/10210
- [x] │   ├── Archiver https://github.com/composer/composer/pull/10195
- [x] │   ├── Comparer https://github.com/composer/composer/pull/10195
- [x] │   ├── Dumper https://github.com/composer/composer/pull/10198
- [x] │   ├── Loader https://github.com/composer/composer/pull/10206
- [x] │   └── Version https://github.com/composer/composer/pull/10199
- [x] ├── Platform https://github.com/composer/composer/pull/10170
- [x] ├── Plugin https://github.com/composer/composer/pull/10194
- [x] ├── Question
- [x] ├── Repository https://github.com/composer/composer/pull/10197
- [x] ├── Script https://github.com/composer/composer/pull/10170
- [x] ├── SelfUpdate https://github.com/composer/composer/pull/10169
- [x] └── Util https://github.com/composer/composer/pull/10190
- [x] tests/Composer/Test/
- [x] ├── Autoload https://github.com/composer/composer/pull/10223
- [x] ├── Command https://github.com/composer/composer/pull/10221
- [x] ├── Config https://github.com/composer/composer/pull/10234
- [x] ├── Console
- [x] ├── DependencyResolver https://github.com/composer/composer/pull/10242
- [x] ├── Downloader https://github.com/composer/composer/pull/10238
- [x] ├── EventDispatcher https://github.com/composer/composer/pull/10235
- [x] ├── Fixtures
- [x] ├── Installer https://github.com/composer/composer/pull/10225
- [x] ├── IO
- [x] ├── Json https://github.com/composer/composer/pull/10222
- [x] ├── Mock https://github.com/composer/composer/pull/10230
- [x] ├── Package https://github.com/composer/composer/pull/10245
- [x] ├── Platform
- [x] ├── Plugin https://github.com/composer/composer/pull/10231
- [x] ├── Question https://github.com/composer/composer/pull/10219
- [x] ├── Repository https://github.com/composer/composer/pull/10227
- [x] ├── Script https://github.com/composer/composer/pull/10220
- [x] └── Util https://github.com/composer/composer/pull/10228

**Comment by Seldaek** [comment]
Ah I wasn't aware it did type inference too, thanks, will definitely try that before wasting anyone's time doing it by hand :)

**Comment by puka-tchou** [comment]
Sorry that it didn't work, I haven't had a chance to test it but I was hoping it could be useful. Good luck then!

**Comment by stof** [comment]
Well, Rector might help for next steps (adding type info in methods) once the properties have types. The main issue today is that *all* types are missing.

**Comment by Seldaek** [comment]
@stof do you mean PHP 7.4 style types properties? Because that's a long way out..

As for var annotations as i wrote in the op i did spend time typing all properties throughout the codebase, which should be enough for static analysis and tools like rector. But it seems to do too much magic with other things which isn't desirable IMO. Maybe I'll try to run it again only with one or two very specific rules.

**Comment by samfelgar** [comment]
Working on src/Composer/Command

**Comment by imme-emosol** [comment]
Working on DependencyResolver ..

**Comment by Seldaek** [comment]
@imme-emosol make sure you rebase on latest `main` branch. But otherwise if you still see problems, feel free to switch to require BasePackage.

**Comment by imme-emosol** [comment]
ghehe.. okay.. :/ Ehwr.. I hope to be able to look at it later this week. Going AFK now..

**Comment by imme-emosol** [comment]
Maybe it could be handy to make an extra checkbox to indicate if a namespace has been merged?

**Comment by b1rdex** [comment]
Working on `src/Composer/Repository/`

**Comment by herndlm** [comment]
I'll work on `src/Composer/Downloader` next

**Comment by herndlm** [comment]
I'll work on `src/Composer/Plugin` next

`src/Composer/Question` seems to be good already

**Comment by herndlm** [comment]
I'll go for `Package`

**Comment by Seldaek** [comment]
Alright we are done here, level 6 is now enabled! 🥳 

Many many thanks to everyone involved here writing and reviewing PRs, that was a great help!

Now only 770 errors left to level 7 😉 But that'll require some more code cleanups I think and will have to wait a little.
