### ISSUE TITLE
FAIL [Composer\Downloader\TransportException]

### ISSUE THREAD

**Issue by antonioreyna** [composer/composer#10153]
Hello, im getting this error when trying to update my project.

$ composer diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: FAIL
[Composer\Downloader\TransportException] curl error 61 while downloading http://repo.packagist.org/packages.json: Unrecognized content encoding type. libcurl understands identity content encodings.
Checking https connectivity to packagist: FAIL
[Composer\Downloader\TransportException] curl error 61 while downloading https://repo.packagist.org/packages.json: Unrecognized content encoding type. libcurl understands identity content encodings.
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.1.9
PHP version: 7.4.13
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
cURL version: 7.63.0 libz  ssl OpenSSL/1.1.1i
zip: extension present, unzip present, 7-Zip present (7z)

**Comment by antonioreyna** [comment]
i had this issue, i was on php7.2 then, i updated and  after some tries it worked but now in the same server, on another project i got that message again, i am able to run composer if i dusable the curl.so extension but for example on one project that extension is necessary for one of the libraries :( i dont know what is going on.

i am able to ping to the packagist.org also curl it manually

**Comment by Seldaek** [comment]
@antonioreyna can you please paste the output of running this in CLI: `php -r 'var_dump(curl_version());'` ? Especially curious to see what is in `libz_version`

**Comment by Seldaek** [comment]
@johnstevenson oh good catch I totally missed/forgot that we hardcode gzip there. This is definitely broken.

**Comment by antonioreyna** [comment]
> `php -r 'var_dump(curl_version());'`

```
$ php -r 'var_dump(curl_version());'
array(14) {
  ["version_number"]=>
  int(474880)
  ["age"]=>
  int(4)
  ["features"]=>
  int(2736789)
  ["ssl_version_number"]=>
  int(0)
  ["version"]=>
  string(6) "7.63.0"
  ["host"]=>
  string(19) "x86_64-pc-linux-gnu"
  ["ssl_version"]=>
  string(14) "OpenSSL/1.1.1i"
  ["libz_version"]=>
  string(0) ""
  ["protocols"]=>
  array(18) {
    [0]=>
    string(4) "dict"
    [1]=>
    string(4) "file"
    [2]=>
    string(3) "ftp"
    [3]=>
    string(4) "ftps"
    [4]=>
    string(6) "gopher"
    [5]=>
    string(4) "http"
    [6]=>
    string(5) "https"
    [7]=>
    string(4) "imap"
    [8]=>
    string(5) "imaps"
    [9]=>
    string(4) "pop3"
    [10]=>
    string(5) "pop3s"
    [11]=>
    string(4) "rtsp"
    [12]=>
    string(3) "smb"
    [13]=>
    string(4) "smbs"
    [14]=>
    string(4) "smtp"
    [15]=>
    string(5) "smtps"
    [16]=>
    string(6) "telnet"
    [17]=>
    string(4) "tftp"
  }
  ["ares"]=>
  string(0) ""
  ["ares_num"]=>
  int(0)
  ["libidn"]=>
  string(0) ""
  ["iconv_ver_num"]=>
  int(0)
  ["libssh_version"]=>
  string(0) ""
}
```

**Comment by Seldaek** [comment]
Haha, of course.. that's problematic.

You can download the file from https://getcomposer.org/composer.phar and replace your composer locally from it.

**Comment by Seldaek** [comment]
It should show something else than 2.1.9 if you're successful overwriting it. Check output of `which composer`
