### ISSUE TITLE
Is composer down right now?

### ISSUE THREAD

**Issue by Vuudi** [composer/composer#10154]
Our servers are not able to reach getcomposer.org right now.
```
> curl getcomposer.org
curl: (7) Failed to connect to getcomposer.org port 80: Connection timed out
> ping getcomposer.org
PING getcomposer.org (54.36.53.46) 56(84) bytes of data.
--- getcomposer.org ping statistics ---
271 packets transmitted, 0 received, 100% packet loss, time 758ms
```
https://downforeveryoneorjustme.com/getcomposer.org confirms the issue.

Somehow I am able to reach the site from my mobile network...

**Comment by vermakhushboo** [comment]
Getting the same error. 
PHP Warning:  copy(https://getcomposer.org/installer): Failed to open stream: Connection timed out in Command line code on line 1

**Comment by erkkki** [comment]
It's up now 🎉

**Comment by mirzazeyrek** [comment]
Use this as temporary solution:

add composer-local:

`curl -sS https://getcomposer.org/installer >> composer-local`

`php composer-local --install-dir=/usr/local/bin --filename=composer`

Probably it will be fixed soon.
