### ISSUE TITLE
Composer issue

### ISSUE THREAD

**Issue by robysalv** [composer/composer#10156]
Hi tried install extension on Magento 2.4.1 with SSH comsand
but i have this issue:

  Problem 1
    - The requested package magento/composer-root-update-plugin (locked at 1.0.0, required as ~1.1) is satisfiable by magento/composer-root-update-plugin[1.0.0] but these conflict with your requirements or minimum-stability.
  Problem 2
    - The requested package dealerdirect/phpcodesniffer-composer-installer (locked at v0.5.0, required as ^0.7.0) is satisfiable by dealerdirect/phpcodesniffer-composer-installer[v0.5.0] but these conflict with your requirements or minimum-stability.

I hope someone help me.
Thank you in advance,

Regards
Roberto

**Comment by successgo** [comment]
Hi @robysalv , your composer.lock file might be outdated, so you may need to run `composer update` command to update composer.lock.
