### ISSUE TITLE
Automatically retry failed Packagist requests

### ISSUE THREAD

**Issue by danepowell** [composer/composer#10161]
I frequently see errors like this when running Composer in CI environments like Travis CI and GitHub Actions:
> curl error 7 while downloading https://repo.packagist.org/p2/drupal/core~dev.json: Failed to connect to repo.packagist.org port 443: Connection refused

These seem to be transient network issues, but they happen frequently enough (especially on a 20-job build matrix) that it can be impossible to get a passing run.

Can Composer automatically retry refused connections a few times before exiting?

**Comment by Seldaek** [comment]
Yup makes sense, we do have some retry mechanism in place already tho which IMO should have retried the case you are mentioning, but anyway I moved it down to a lower level which hopefully makes it more reliable. See #10162 - I'm hoping it'll help.
