### ISSUE TITLE
Are there any deadline for stopping composer v1 repos?

### ISSUE THREAD

**Issue by steve-todorov** [composer/composer#10191]
Hi,

I haven't been able to get any information regarding any deadlines for when composer v1 repositories will stop working.
We are trying to plan the upgrade to v2 within the first few months of 2022.
Are there any plans to stop the services around that time?
Is there any planned deadline for stopping v1 repositories?

**Comment by steve-todorov** [comment]
Thank you very much for the fast and detailed reply! I'll pass this up the chain. If you'd like you can close this or leave it open in case other people might have the same question. :)

**Comment by Seldaek** [comment]
Closing in favor of https://github.com/composer/composer/issues/10340
