### ISSUE TITLE
Multiple autoloaders and performance in WordPress

### ISSUE THREAD

**Issue by AntonyXSI** [composer/composer#10205]
I'm noticing a number of WordPress plugins using the Autoload/ClassLoader.php file and it causing performance issues particularly on large sites with a lot of classes.

The performance issue is specifically related to the file_exists checks performed within classloader.php. Due to the way the parent function is loaded via spl_autoload_register, it's looping over every class, and depending on the site running file_exists checks against thousands of paths.

I have recommend plugin developer's whitelist the needed classes to prevent unnecessary file exists checks, however some plugins appear to be using the same namespace so the whitelist would break the autoloader in other plugins.

Is there a best practice for this type of scenario, perhaps different namespaces of the autoloader within each plugin?

**Comment by AntonyXSI** [comment]
Sorry for digging this up, I'm still working with developers of different plugins in order to get them to update the autoloader. 

Is there an easy way to see if authoritative class maps are in place (from within the contents of the composer directory)?

**Comment by Seldaek** [comment]
At runtime you can check with `$loader = include 'vendor/autoload.php'; $loader->isClassMapAuthoritative();` or looping through `Composer\Autoload\ClassLoader::getRegisteredLoaders()` and doing the same.

Statically, you'd need to inspect vendor/composer/autoload_real.php to see if it contains `$loader->setClassMapAuthoritative(true);` or not.
