### ISSUE TITLE
Introduce an option of `dump-autoload` to fail on PSR uncompliant classes

### ISSUE THREAD

**Issue by Kolyunya** [composer/composer#10241]
I would like to suggest adding an option to the `dump-autoload` command which would force it to fail when it encounters PSR uncompliant classes. This would be very profitable to add this kind of validation to the CI scripts.

Currently, the command just prints to the stdout notices like the following but the return code is always `0` thus there's no straightforward way to automate this important validation process.
```
Class Foo located in ./Foo.php does not comply with psr-4 autoloading standard. Skipping.
```

**Comment by Seldaek** [comment]
This is really not so trivial to add IMO.. So sounds like not really worth the trouble to me.

**Comment by danepowell** [comment]
Agreed, and I'd like to see this option anywhere that a warning can be generated. For instance, you can get the PSR-4 warnings on `composer install` as well. It's hard to have bulletproof CI when problems like this can't be caught.

**Comment by Seldaek** [comment]
Yeah I got a possible solution in the works - hopefully can wrap this up next week

**Comment by Seldaek** [comment]
See https://github.com/composer/composer/pull/10886

**Comment by Kolyunya** [comment]
@Seldaek thank you so much for your work! Looking forward for a release to test it out!

**Comment by Seldaek** [comment]
You can give it a shot with "composer self-update --snapshot" already

**Comment by danepowell** [comment]
Thanks! We've already implemented this in our CI to catch tests with bad class names that Composer would otherwise fail to load.
