### ISSUE TITLE
Changes to proxy loading in 2.1.10 break PHPUnit in PHP <=7.4

### ISSUE THREAD

**Issue by dvdoug** [composer/composer#10246]
My `composer.json`:
https://raw.githubusercontent.com/dvdoug/BoxPacker/master/composer.json

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 2.1.10
PHP version: 7.4.25
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
cURL version: missing, using php streams fallback, which reduces performance
zip: extension not loaded, unzip present, 7-Zip not available
```

When I run this command: 

```
vendor/bin/phpunit
```

I get the following output: 

```
PHP Fatal error:  strict_types declaration must be the very first statement in the script in /tmp/BoxPacker/vendor/phpunit/phpunit/phpunit on line 2
```

And I expected this to happen:
Tests to run

Works fine with Composer 2.1.9

**Comment by herndlm** [comment]
I could confirm this and that via `git bisect` that e1dbd65 is the cause

**Comment by Seldaek** [comment]
Huh very weird, not sure I get why strict types fails here as it should be a per-file declare, how's being included affects it? Is it triggered due to the output buffering? Sounds all strange to me but anyway will try to investigate further when I find time.

**Comment by dvdoug** [comment]
@Seldaek see https://bugs.php.net/bug.php?id=77561, until PHP8 the special-case handling for shebangs only operated on the invoked file

**Comment by Seldaek** [comment]
Ok yes i was aware of that which is why we do output buffering on versions pre 8.0 to get rid of the shebang. I just didn't realize this would cause issues with declare.

The eval solution was also causing issues with magic constant which is why I replaced it.. the only hack left that i can think of is modifying the file to remove strict types and then registering a shutdown handler to restore it when running on PHP 5 or 7. I don't like this at all though.

Maybe for 7.4 we could passthru a new process running the file, but older versions don't have PHP_BINARY so it makes identifying the running PHP an additional problem, and that's assuming passthru would even work without causing more problems, which I'm rather pessimistic about.

**Comment by johnstevenson** [comment]
> that's assuming passthru would even work without causing more problems, which I'm rather pessimistic about.

As you know, xdebug-handler used `passthru` and its only downside was piped output (which messes with tty stuff) so it now uses `proc_open` in a passthru-style that preserves std fds/handles. Does this allay your pessimism?

**Comment by herndlm** [comment]
Another potential solution might be something similar that https://github.com/dg/bypass-finals is doing (using a stream wrapper to modify the file content on access/load). But it feels pretty complicated and I don't know if it would even be a viable solution in that context

**Comment by Seldaek** [comment]
@johnstevenson fair enough, still would rather avoid a new process if possible though, it's rather messy :)

Thanks @herndlm for the tip, stream wrappers is a great hack for this. I did it using a wrapper as while it's slightly more code these have the benefit of being able to be unregistered, while filters don't seem like they can. So it's leaving a bit less mess behind this way..

Anyway https://github.com/composer/composer/pull/10249 should fix this and hopefully there isn't another weird case I forgot to take into consideration :)

**Comment by Seldaek** [comment]
2.1.11 is now out with the fix. If you update though you should make sure to clear the incorrectly-generated proxies (rm the whole bin dir is the easiest) and then `composer install` should recreate them correctly.

**Comment by dvdoug** [comment]
Thanks @Seldaek , fix is working for me 👍
