### ISSUE TITLE
Can't Update outdated dependencies to newest stable version.

### ISSUE THREAD

**Issue by fomoshlo3** [composer/composer#10258]
My `composer.json`:

```json
...replace me...
```

Output of `composer diagnose`:

```
...replace me...
```

When I run this command: 

```
...replace me...
```

I get the following output: 

```
...replace me...
```

And I expected this to happen:

**Comment by fomoshlo3** [comment]
[{
	"resource": "/home/fomoshlo3/.config/composer/composer.json",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "768",
	"severity": 4,
	"message": "Problems loading reference 'http://json.schemastore.org/composer': Unable to load schema from 'http://json.schemastore.org/composer': Not Found. The requested location could not be found.\nThe resource you are looking for has been removed, had its name changed, or is temporarily unavailable.",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}]

**Comment by fomoshlo3** [comment]
It seems it changed to https://schemastore.org/json/composer.json

**Comment by fomoshlo3** [comment]
> ```json
> {
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^7.3|^8.0",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.65",
        "laravel/sanctum": "^2.11",
        "laravel/tinker": "^2.5"
    },
    "require-dev": {
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^5.10",
        "phpunit/phpunit": "^9.5.10"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
> ```

**Comment by fomoshlo3** [comment]
- patch or minor release available - update recommended
- major release available - update possible
egulias/email-validator 2.1.25 3.1.2 A library for validating emails against several RFCs
league/flysystem        1.1.5  2.3.1 Filesystem abstraction: Many filesystems, one API.
psr/container           1.1.2  2.0.2 Common Container Interface (PHP FIG PSR-11)
psr/log                 2.0.0  3.0.0 Common interface for logging libraries
psr/simple-cache        1.0.1  3.0.0 Common interfaces for simple caching

**Comment by Seldaek** [comment]
No idea what is trying to get the schema from schemastore.org, maybe a plugin, but this doesn't look like a Composer problem.

**Comment by fomoshlo3** [comment]
sorry for the nuisance then.

**Comment by fomoshlo3** [comment]
well, on second thought, any composer.jsons tried to connect there, not only the one posted.

**Comment by herndlm** [comment]
Your message listed `/home/fomoshlo3/.config/composer/composer.json`. Could there be something in it that is the reason for this?

**Comment by Seldaek** [comment]
Maybe if you did follow the issue template we could help.. Because running with `-vvv` would show loaded plugins etc. 

If you can repro with any composer.json then make up a very simple one and share the `composer update -vvv` output.

**Comment by fomoshlo3** [comment]
Problem was solved. I couldn't access 127.0.0.1 (default artisan server) because of Fast-Startup Option in Win10 . Sorry for interrupting your work.
