### ISSUE TITLE
CPU Arch requirements

### ISSUE THREAD

**Issue by tomjn** [composer/composer#10251]
We can require versions of PHP, and we can require PHP extensions, it would be good to specify CPU architecture compatibility.

For example, we have packages that add composer subcommands to control software, certain versions of our package are incompatible with Arm/Apple Silicon devices due to unavailable docker images. It would be useful to be able to formally specify this rather than having the package installed and then seeing it fail due to CPU arch issues.

**Comment by Seldaek** [comment]
What do you get for 

```
php -r "var_dump(php_uname('m'));"
```

I get `AMD64` on windows, `x86_64` on linux.. It seems `i386` and `i686` are possible values too.

We'd definitely need to know what value to expect there to be able to make new platform packages for this, not sure what these would be though.

We already have `php` and `php-64bit` for 64bit support. Could perhaps add `php-x86`, `php-x86-64` and `php-arm64`, not sure if we need an arm 32bit? Also not sure what Apple M1 chips are using exactly as architecture..

Overall sounds like a bit of a mess I'd rather not get into, but if someone with enough of a clue is willing to help out we can perhaps add this.

**Comment by tomjn** [comment]
On MacOS I get:

```
❯ php -r "var_dump(php_uname('m'));"
string(6) "x86_64"
~
❯ php --version
WARNING: PHP is not recommended
PHP is included in macOS for compatibility with legacy software.
Future versions of macOS will not include PHP.
PHP 7.3.29-to-be-removed-in-future-macOS (cli) (built: Aug 30 2021 10:56:16) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.29, Copyright (c) 1998-2018 Zend Technologies
~
❯ composer --version
Composer version 2.1.8 2021-09-15 13:55:14
~
❯ 
```

**Comment by Seldaek** [comment]
OK in that case I am guessing your PHP runs in emulation mode and not native ARM?

**Comment by tomjn** [comment]
> OK in that case I am guessing your PHP runs in emulation mode and not native ARM?

That's on an Intel Mac, I'm still procuring Apple Silicon results

> not sure if we need an arm 32bit?

A lot of Raspberry PI's still use 32bit arm, 64bit Raspbian isn't as widespread yet

**Comment by tomjn** [comment]
I'm told:

> `arm64` on a m1, however that’s OS-specific too, under, say, docker + linux on m1, it would be `aarch64`

**Comment by tomjn** [comment]
A Raspberry Pi running 32bit raspbian will return:

```sh
❯ uname -m
armv7l
```

**Comment by Seldaek** [comment]
OK thanks. The question to me is.. if there are so many variants, what's the right amount of granularity that will serve users most? Do we want to just call it x86/arm,  or have exact packages for every CPU arch out there?

**Comment by stof** [comment]
I'm not convinced having one package per architecture will actually be usable. requirements are a AND, not a OR. so if they are separate packages per app, there is no way to define a package supporting `arm64` and `armv71` but not `x86`

**Comment by Seldaek** [comment]
Yeah that's the issue, if you have packages supporting multiple archs it's useless. It only helps if you have very specific things.

I guess one hack would be to have php-arch with the version being dev-arm64 or dev-x86, so you could require multiple architectures.. But that's kind of an ugly mess :D 

I am really unsure if this is worth the trouble, given you're the first person to ask for it @tomjn.

**Comment by tomjn** [comment]
`php-x86` and `php-arm` are already super useful, e.g. golang binaries for `aarch64` run on 64bit Linux and Apple Silicon, and we could declare `php-x86` incompatible and prevent common pitfalls. Even `php-x86` on its own is useful

I was going to suggest `php-{arch}-{bitness}`

**Comment by stof** [comment]
@tomjn but how would you expect to use that then ? If you require one of those packages, your package will be installable  only on that architecture. You cannot do a constraint like `require either package A or package B`

**Comment by tomjn** [comment]
> your package will be installable only on that architecture

This allows us to prevent installation of a number of composer packages on Apple Silicon and other Arm devices that we know for a fact only support x86 CPUs. Newer major versions of the package do not have that issue, but there is nothing preventing composer from installing the older versions on Apple Silicon and other Arm/non-x86 devices

**Comment by Seldaek** [comment]
Fixing older versions is typically pretty hard tho, as you'd have to re-tag every past version, making them incompatible with older Composer versions in the process if we do add a new platform package. Just sounds rather messy.

**Comment by tomjn** [comment]
We have backport bots for that, they're a bit annoying with the email churn internally mind. We also have projects we know have no future on non-x86 machines ( e.g. a composer command for managing a VirtualBox test environment ).

**Comment by stof** [comment]
> This allows us to prevent installation of a number of composer packages on Apple Silicon and other Arm devices that we know for a fact only support x86 CPUs. We can do this by explicitly declaring the conflict

Using those packages in conflict rules rather than requirements means that your package needs to list all the _unsupported_ packages rather than the _supported_ ones. This is quite hard to manage.

**Comment by Seldaek** [comment]
Closing as I don't see how to do this reasonably nor does it seem that broadly useful.
