### ISSUE TITLE
Composer plugin: how to do inherit vendor directories?

### ISSUE THREAD

**Issue by WinterSilence** [composer/composer#10254]
**Note**: I'm know it's not true way, it's more of mental exercise.
How detect parent package if it's not project/root package (sub-package 1-1, sub-package 2-1, sub-package 2-2)?

Vendor directory of project with inherit vendor directories:
- project package 1/
   - vendor/
      - sub-package 1-1/
- project package 2/
   - vendor/
      - sub-package 2-1/
      - sub-package 2-2/

**Comment by Seldaek** [comment]
Sorry but I do not understand what you are asking.

**Comment by WinterSilence** [comment]
@Seldaek I'm have project with tree structure of packages (project/application have packages/modules with sub-packages and etc.) and tried store they as tree of  directories. I'm found elegant solution: the structure of vendor packages remains unchanged. After the changes are completed, installer creates directory containing symbolic links to  a tree structure of packages.

**Comment by Seldaek** [comment]
Still not 100% sure I understand, but IMO it'd be better to use a path repository for this https://getcomposer.org/doc/05-repositories.md#path

**Comment by WinterSilence** [comment]
@Seldaek I'm create symlink() to packages,
in vendor directory:
- `vendor1/module-package-1`
- `vendor1/module-package-1-1`
- `vendor2/module-package-1-2`
- `vendor1/module-package-2`
- `vendor2/module-package-2-1`

in `app/modules` directory:
- `module-package-1/modules` directory:
  - `module-package-1-1` - symlink to `vendor1/module-package-1-1`
  - `module-package-1-2` - symlink to `vendor1/module-package-1-2`
- `module-package-2/modules` directory:
  - `module-package-2-1` - symlink to `vendor1/module-package-2-1`
~~~
