### ISSUE TITLE
Windows bin proxy generation regression

### ISSUE THREAD

**Issue by fritzmg** [composer/composer#10261]
In df6c2ce1db47404d67ce7c2fec03f92cca5d155c the `$binPath` was changed to not use `realpath()` anymore. This causes an issue under Windows, since under Windows any relative paths are not resolved during `include`, at least under PHP 7.4 via the `Composer\BinProxyWrapper`. This means if the proxy script for example includes

```
$binPath = __DIR__ . "/" . '../contao/contao/manager-bundle/bin/contao-setup';
```

then within the included script, `__DIR__` (and `__FILE__`) will contain the same relative path, e.g.

```
…\c412dev\vendor\bin/../contao/contao/manager-bundle/bin
```

This then breaks our PHP binaries under Windows, since the include path to `vendor/autoload.php` (or rather the detection of the project's directory) will fail: https://github.com/contao/contao/pull/3652

So in the above example, the project directory will be `\dirname(__DIR__, 7)` under Windows, but `\dirname(__DIR__, 5)` under *nix.

**Comment by Seldaek** [comment]
Oh wow this just keeps getting weirder and weirder 😄 

I am assuming that with PHP8 the include resolves to the realpath correctly? It's probably a problem of the stream wrapper that the file path isn't realpath'd?

**Comment by fritzmg** [comment]
Yes, under PHP 8 the include resolves correctly to the realpath.

Changing 

https://github.com/composer/composer/blob/3bb78fd1ee8a254878a71cf12c275b5f8303c2b0/src/Composer/Installer/BinaryInstaller.php#L293

to

```php
\$opened_path = realpath(substr(\$path, 21));
```

would fix the issue for example. Not sure what the downside would be though, if there can be any?

**Comment by Seldaek** [comment]
I can't see why that would be a problem really. Looks like that's done internally by the default stream wrapper: https://github.com/php/php-src/blob/083d7f5886fe2f70a5474db3c760b1c9322f982f/main/streams/streams.c#L2053-L2057

https://github.com/php/php-src/blob/083d7f5886fe2f70a5474db3c760b1c9322f982f/main/fopen_wrappers.c#L471-L474

I'll push a fix then.

**Comment by Seldaek** [comment]
2.1.12 is out now with the fix
