### ISSUE TITLE
Documentation about v1 repository metadata in composer v2

### ISSUE THREAD

**Issue by mrblc** [composer/composer#10273]
Hi,
I need to use private repository based on satis which is currently on older version supporting only composer v1 metadata. It's not clear does composer v2 even support v1 metadata, so I tried to run local .phar file with latest version of composer and create new project with template from that repository and it worked.

Could you update documentation to state that composer v2 also supports old repository metadata and if there is deadline for removing that support.

Thank you

**Comment by stof** [comment]
Composer is still supporting the v1 metadata format, but using it is not recommended as it requires more bandwidth (even though for a private satis repository, the total size is probably not that big). This support won't be removed in Composer 2, as it would be a BC break (and so needs to wait for Composer 3, which is not planned yet).
However, note that Satis has already been updated to generate metadata in the new format.

**Comment by Seldaek** [comment]
Yeah sorry but won't spend time on docs updates for minor details like this..
