### ISSUE TITLE
Platform check uses wrong PHP version on Windows

### ISSUE THREAD

**Issue by codemasher** [composer/composer#10282]
Hi! I've just been experimenting with the `scripts` options in `composer.json` and noticed that when running e.g. PHPUnit this way, I run into a PHP version mismatch: `composer.phar` is invoked with a specific PHP executab, usually from within PHPStorm but executes the script with the PHP found in `PATH`. After a bit of digging, i think the culprit is [Symfony's `ExecutableFinder`](https://github.com/symfony/process/blob/5.3/ExecutableFinder.php) (called [around here in `EventDispatcher`](https://github.com/composer/composer/blob/61b50cb7ec87176df389841780e0fd742d4f1780/src/Composer/EventDispatcher/EventDispatcher.php#L281-L289)), which seems to guess the PHP from the environment variables exclusively, ignoring `PHP_BINARY` (which is available since PHP 5.4).

My `composer.json`:

```json
{
	"name": "chillerlan/php-oauth-core",
	"description": "A PHP7.4+ OAuth client core library",
	"homepage": "https://github.com/chillerlan/php-oauth-core",
	"license": "MIT",
	"type": "library",
	"minimum-stability": "stable",
	"keywords": [
		"oauth", "oauth1", "oauth2", "authorization", "authentication",
		"client", "psr-7", "psr-17", "psr-18", "rfc5849", "rfc6749"
	],
	"authors": [
		{
			"name": "smiley",
			"email": "smiley@chillerlan.net",
			"homepage": "https://github.com/codemasher"
		}
	],
	"support": {
		"issues": "https://github.com/chillerlan/php-oauth-core/issues",
		"source": "https://github.com/chillerlan/php-oauth-core"
	},
	"provide": {
		"psr/http-client-implementation": "1.0"
	},
	"require": {
		"php": "^7.4 || ^8.0",
		"ext-curl":"*",
		"ext-json":"*",
		"ext-simplexml":"*",
		"ext-zlib": "*",
		"chillerlan/php-httpinterface": "^5.0",
		"psr/http-client":"^1.0",
		"psr/http-message": "^1.0",
		"psr/log": "^1.1 || ^2.0 || ^3.0"
	},
	"require-dev": {
		"phan/phan": "^5.2",
		"phpunit/phpunit": "^9.5"
	},
	"autoload": {
		"psr-4": {
			"chillerlan\\OAuth\\": "src/"
		}
	},
	"autoload-dev": {
		"psr-4": {
			"chillerlan\\OAuthTest\\": "tests/"
		}
	},
	"scripts": {
		"phpunit": "vendor/bin/phpunit",
		"phan": "vendor/bin/phan"
	},
	"config": {
		"lock": false,
		"sort-packages": true,
		"platform-check": true
	}
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.1.12
PHP version: 7.4.3
PHP binary path: C:\amp\php\7.4.3\php.exe
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
cURL version: 7.68.0 libz 1.2.11 ssl OpenSSL/1.1.1d
zip: extension present, unzip not available, 7-Zip present (7z)
```

When I run this command: 

```
C:\php\8.0.0\php.exe C:/<project>/composer.phar run-script phpunit
```

I get the following output: 

```
> vendor/bin/phpunit
PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.0". You are running 7.4.3. in <path>\vendor\composer\platform_check.php on line 33
```

And I expected this to happen:

I'd expect the script executed by `run-script` to use the same php executable that was used to invoke Composer (8.0.0 instead of 7.4.3 from `PATH` in this case).

**Update**: i added the `@php` to the script line, which seems to have it resolved. However i feel like this is a bit unintuitive.

**Comment by WinterSilence** [comment]
@codemasher  you don't understand jun snow...  `vendor/bin/phpunit` it's other script and it's can use any version of php,if you open your phpunit.bat you can find something like this:
~~~php
@ECHO OFF
setlocal DISABLEDELAYEDEXPANSION
SET BIN_TARGET=%~dp0/../phpunit/phpunit/phpunit
php "%BIN_TARGET%" %*
~~~

**Comment by codemasher** [comment]
@WinterSilence that is not the issue - it is [literally copy/pasted from monolog's composer.json](https://github.com/Seldaek/monolog/blob/main/composer.json#L66-L74). The issue is that Composer runs with the desired PHP executable (the one it has been called with, here 8.0.0) up to a certain point in `EventDispatcher`, were it for whatever reason guesses the executable for the script call from the Windows environment, and unfortunately picks the wrong executable (7.4.3).

The funny thing is that it probably would have gone completely unnoticed if I hadn't added the PHP8-only requirements for `psr/log` and switched PHP to 8 in PHPStorm. Generally I´d expect Composer to run the scripts with the same executable as `composer update` would do but it seems that is not a given. Adding the `@php` feels like a hack here and i wonder if that could be fixed in future.

**Comment by WinterSilence** [comment]
@codemasher you run composer with php 8.0, composer run other script that script can CALL ANYTHING, in your case it's `php "%BIN_TARGET%" %*`, OS find that's `php` base on PATH

**Comment by codemasher** [comment]
The script calls the `phpunit` (php file) not the `phpunit.bat` - both in `/vendor/bin` - with or without `@php`.

**Comment by WinterSilence** [comment]
@codemasher **on Windows** ?

**Comment by codemasher** [comment]
yes.

**Comment by WinterSilence** [comment]
@codemasher what makes you think that? but no matter `phpunit` or `phpunit.bat` - you need understand they run "default" php version base on PATH

**Comment by codemasher** [comment]
I see how the `phpunit.bat` would call the PHP from `PATH`, but the php script obviously doesn't - on windows at least. So what the `@php` seems to do is strip the PHP executable the script was invoked with and replaces it with the current one. Which still doesn't answer why it calls the `.bat` in one case but not the other (which i was mistaken about and corrected above).

**Comment by WinterSilence** [comment]
@codemasher it's not part of composer, [bin](https://getcomposer.org/doc/04-schema.md#bin)

**Comment by codemasher** [comment]
In conclusion: windows is dumb, and so am i. Closing this here.

**Comment by Seldaek** [comment]
The best way to fix this with composer 2.1+ is this:

```
	"scripts": {
		"phpunit": "@php vendor/bin/phpunit",
		"phan": "@php vendor/bin/phan"
	},
```

This will make composer execute the binary with PHP directly instead of letting the shell figure out which PHP process. Composer will reuse the currently running PHP process' path when doing so.

**Comment by codemasher** [comment]
@Seldaek yup, that's what I figured then. May i suggest that you add it in [monolog's composer.json](https://github.com/Seldaek/monolog/blob/main/composer.json#L66-L74) or should i submit a PR? It may save someone a headache. :)

**Comment by WinterSilence** [comment]
@codemasher you can try send PR but it's BC, you can write Composer's [script](https://getcomposer.org/doc/articles/scripts.md) or [plugin](https://getcomposer.org/doc/articles/plugins.md)

**Comment by Seldaek** [comment]
@codemasher updated Monolog

**Comment by codemasher** [comment]
Awesome! Thank you!
