### ISSUE TITLE
[2.3] Add support for completion when on Symfony 5.4

### ISSUE THREAD

**Issue by dkarlovi** [composer/composer#10292]
According to this tweet:
https://twitter.com/seldaek/status/1461670175976169478

Composer 2.3+ will be on [Symfony 5.4 which got support for completion in Console](https://symfony.com/blog/new-in-symfony-5-4-console-autocompletion). See [Symfony 5.4 adding completion to their own commands](https://github.com/symfony/symfony/issues/43594).

The proposal here is to add this feature directly into Composer, allowing custom completion where appropriate, for example
1. `composer require sa<TAB>` could search Packagist for packages with name `sa%`
2. `composer update <TAB>` could complete package names already in `composer.json`

etc.

 The completion script could then be generated and shipped when Composer is distributed as a native package (for example, I'm using a [package prepared by Remi](https://rpms.remirepo.net/rpmphp/zoom.php?rpm=composer)), meaning many users will get DX improvement by default, others can run `composer completion bash > ~/.bash_completion.d/composer.sh` (or similar) once to get the same features.

**Comment by GromNaN** [comment]
I gave a try in #10320. Covering more commands than what was identified in this issue.

**Comment by dkarlovi** [comment]
Added a note about this being available in 2.4 on Remi repo issue tracker (they do RPMs for CentOS, RHEL, Fedora, etc)
https://github.com/remicollet/remirepo/issues/211
