### ISSUE TITLE
Execute Composer in plain-text mode

### ISSUE THREAD

**Issue by nico-apps** [composer/composer#10295]
Hey everyone, I have a bit of a weird issue.

I'm trying to install the package PhpSpreadsheet using Composer. Because of the limits of my server, I'm using php's `exec()` function to access the command line. However, no matter if I execute `composer` or the composer.phar, it will return an empty string. I've tried this with many other commands, and they work fine.

After some research, it appears that the following code:
```
exec($_GET["command"], $out);
foreach($out as $line) {
	echo($line . "<br>");
}
```
returns an empty text, followed by `Content-type: text/html` (most likely because of the `br`, as executing the same code with `\n` returns nothing).

I think this happens because Composer uses formatting like different colored text, which PHP seems to have a bit of an issue with. Is there a way to launch the composer.phar in plain-text mode perhaps?

Thanks in advance

**Comment by staabm** [comment]
I guess you are searching for `--no-ansi`

**Comment by Seldaek** [comment]
There's that and there's the fact we output lots of stuff on stderr and I believe exec will only give you stdout output.

I'd advise you to run it via proc_open so you can also capture stderr, or you can try doing `exec($_GET['command'].' 2>&1', $out);` which will redirect stderr output to stdout. That may fix it.

BTW running exec() on $_GET sounds fairly suicidal, I hope you have this well secured.

**Comment by nico-apps** [comment]
@Seldaek Thank you, that worked! It now returns `[RuntimeException] The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly ` which is better than nothing at least. I'll try to resolve this issue so I can use Composer. Thanks!
