### ISSUE TITLE
"composer search" should return more popular packages first (or better match namespaces in name-only mode)

### ISSUE THREAD

**Issue by dkarlovi** [composer/composer#10325]
Searching for 

```
composer search ^laravel -N
```

returns all sorts of packages, but `laravel/` is the most obvious example what one would like to see here.

If I search

```
composer search ^laravel/ -N
```

I get better matching results. These two queries **should behave basically in the same way**, this type of search is similar to as-you-type auto-suggest you'd get on Google or some e-commerce site.

The reason is in #10320, when you do

```
composer require larav<TAB>
```

it will auto-complete to

```
composer require laravel-
```

because it's offering more than 150 `laravel-`-prefixed packages in front of `laravel/*`.

So, either:

- sort by package downloads by default (?)
- more tightly match namespaces (namely, `laravel/` is a better match to the query `laravel` than `laravel-foo/` is)
- both (?)

**Comment by dkarlovi** [comment]
Thinking about this further, sort by popularity might also not provide the correct behaviour for completion. For example, let's say you actually want `laravue`, you'd never get it because Laravel would always win.

Maybe we need a special search which returns just deduplicated namespaces, then we drill into the namespace with the name search? 🤔

**Comment by Seldaek** [comment]
A special vendor search type might be valuable anyway as it'd make the returned list quite a bit smaller.

**Comment by dkarlovi** [comment]
@Seldaek how would this work? Would Packagist need to get this as a feature and then Composer 2.3 detects / expects it? Not sure how the aligning with Packagist works here.

**Comment by dkarlovi** [comment]
@Seldaek not sure this one should already be closed since it's discussing the sort too, which is AFAIK still in discussion?

**Comment by Seldaek** [comment]
I figured #10320 is enough as we'll need to solve problems there before merging it.
