### ISSUE TITLE
Change in behavior of --with-dependencies in composer 1 and 2?

### ISSUE THREAD

**Issue by Defcon0** [composer/composer#10328]
Hello,

I removed the issue template because the asked info is not needed to answer the question, I think.

My use case is updating a content management system with all of **_its_** dependencies.

In composer 1 I could do that with:

```
composer update cms-acme/* --with-dependencies
```

This lead to cms-acme/* being updated as well as (recursively) all packages which are dependencies of cms-acme/* packages **themselves**.

So let's assume the following composer.json of cms-acme/cms-package1:

```json
{
    "name": "cms-acme/cms-package1",
    "type": "something",
    "require": {
        "some-other-acme/package2": "^1.0"
    }
}
```

Then some-other-acme/package2 is a dependency of cms-acme/cms-package1. But it's also the case vice-versa:

```json
{
    "name": "some-other-acme/package2",
    "type": "something",
    "require": {
        "cms-acme/cms-package1": "^1.0"
    }
}
```

And let's assume another package which is itself a dependency of cms-acme/cms-package1 but **not** vice versa:

```json
{
    "name": "some-other-acme/package3",
    "type": "something",
    "require": {
        "cms-acme/cms-package1": "^1.0"
    }
}
```
So some-other-acme/package3 does depend on cms-acme/cms-package1 but cms-acme/cms-package1 does **NOT** depend on some-other-acme/package3.

Now with **composer 1** running

```
composer update cms-acme/* --with-dependencies
```

would result in

```
Updating cms-acme/cms-package1
Updating some-other-acme/package2
```

whereas in composer 2 now it results in:

```
Updating cms-acme/cms-package1
Updating some-other-acme/package2
Updating some-other-acme/package3
```

When looking in the docs of composer, `--with-dependencies` means:

```
Update also dependencies of packages in the argument list, except those which are root requirements
```

So is the new behavior intended or changed from composer 1 to 2 or is it a bug in my setup. In addition I think the above description of `--with-dependencies` is a bit ambiguous, because "dependencies of packages" can be interpreted in both directions. That would imply, also including packages depending on the packages in the argument list which is wrong in my opinion. I think the behavior in composer 1 was correct.

I hope someone can help in this case :-)

Bye Defcon0

**Comment by Seldaek** [comment]
I have no idea what to tell you here. I'd need a composer.json and composer.lock copy that allows to reproduce the issue, if there is one. But I am fairly sure the Composer 2 behavior is the more correct one.

**Comment by Defcon0** [comment]
Mhm, don't know how to explain it with more detail :-( What in detail is unclear?

I'll try to create a concrete composer.json without business inside info today. It won't be too much different from the pseudo code above though.

**Comment by Defcon0** [comment]
OK, I minimalized the issue and can't reproduce it so I guess the issue lies in my concrete setup. Sorry for the hassle ;-)
