### ISSUE TITLE
Requirment of depreaced Symfony (see description)

### ISSUE THREAD

**Issue by mdziczkowski** [composer/composer#10332]
### System informations:

- **OS**: Debian 10
- **Composer version**: 2.0.9-2

### Done steps:

- installed fresh version of Composer from Debian repository (version as described above)

### Terminal output while usage:

> Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of 
> type int is deprecated in /usr/share/php/Symfony/Component/Console/Input
> /StringInput.php:51
> Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of 
> type int is deprecated in /usr/share/php/Symfony/Component/Console/Input
> /StringInput.php:51
> Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of 
> type int is deprecated in /usr/share/php/Symfony/Component/Console/Input
> /StringInput.php:52
> Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of 
> type int is deprecated in /usr/share/php/Symfony/Component/Console/Input
> /StringInput.php:54
> Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of 
> type int is deprecated in /usr/share/php/Symfony/Component/Console/Input
> /StringInput.php:56
> Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of 
> type int is deprecated in /usr/share/php/Symfony/Component/Console/Input
> /StringInput.php:51
> Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of 
> type int is deprecated in /usr/share/php/Symfony/Component/Console/Input
> /StringInput.php:52
> Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of 
> type int is deprecated in /usr/share/php/Symfony/Component/Console/Input
> /StringInput.php:54
> Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of 
> type int is deprecated in /usr/share/php/Symfony/Component/Console/Input
> /StringInput.php:56
> Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of 
> type int is deprecated in /usr/share/php/Symfony/Component/Console/Input
> /StringInput.php:51
> Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of 
> type int is deprecated in /usr/share/php/Symfony/Component/Console/Input
> /StringInput.php:52
> Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of 
> type int is deprecated in /usr/share/php/Symfony/Component/Console/Input
> /StringInput.php:54
> Deprecation Notice: preg_match(): Passing null to parameter #4 ($flags) of 
> type int is deprecated in /usr/share/php/Symfony/Component/Console/Input
> /StringInput.php:56

**Comment by stof** [comment]
This is known, and will be fixed in Composer 2.3 which will be able to migrate to Symfony 5.4 thanks to dropping support for old PHP versions.
For now, the phar needs to ship with old Symfony versions due to the support of PHP 5.3+.

**Comment by Seldaek** [comment]
That said, the phar is suppressing the deprecation notices. The debian package isn't but that's due to debian packaging policies IMO, and nor our problem. Please install from https://getcomposer.org/download/ if you want support here.

**Comment by mdziczkowski** [comment]
How about to make Composer independant from Symfony? this would solve this kind of problems

**Comment by mdziczkowski** [comment]
maybe there is a possible work around for it?

I'm askng because while trying to install composer from the Debian repositories, I recieve dependancies errors related to Symfony (it requires version Symphony that is unavaliable for my system)

**Comment by Seldaek** [comment]
@mdziczkowski I have no idea what you mean by work around it. We are not in charge of the debian packaging. We made sure we support newer Symfony components ages ago, if packagers decide to package what's in the lock file but don't include the latest code for Composer with fixes for deprecations, that's not our problem.

**Comment by mdziczkowski** [comment]
@Seldaek Do you think that it would be possible to get into cooperation with the maintainers of the repositories listed bellow to get able the composer and it dependancies list are beeing keept up to date?

The repository that provides composer for Debian is maintained by:

Debian PHP PEAR Maintainers <pkg-php-pear@lists.alioth.debian.org>

**Comment by Seldaek** [comment]
If they are interested they can reach out to us, but I don't have time to track down everyone packaging Composer to try and get them to do it the way we would prefer. Distro packaging on linux usually works in a way that is bound to leave you with outdated software, which is fine if you are using only distro packages but I suspect you installed PHP 8.1 from another repository as the default one, and now you have a mismatch between things and you get deprecation warnings you weren't supposed to see. If you don't use all default packages, then as I already wrote above, I suggest you simply install Composer manually vs by using distro packages, that way you get the latest and greatest version of Composer instead of whatever was pinned at the time of your distro's release.

**Comment by mdziczkowski** [comment]
For any case, I had send a message to the maintainers, so in any case they may contact you ;-)
