### ISSUE TITLE
Composer Snapshots Warning

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#10341]
As the release of 2.2.0 approaches, we are also approaching the point where we will drop support for PHP `<7.2` from Composer. See https://github.com/composer/composer/issues/10340

I do want to highlight a possible issue for people relying on installing **snapshots** by downloading `https://getcomposer.org/composer.phar` directly instead of relying on the installer.

Within a few weeks, the snapshot builds will start requiring PHP 7.2.5, so this can mostly be an issue for Continuous Integration targets that rely on snapshots. I am not sure how many of those there are, but I figured it doesn't hurt to try and reach out to people in advance.

The best solution is probably to use the installer, or to at least read the https://getcomposer.org/versions file, loop over the the snapshot key's versions so you can figure out which file is appropriate for the PHP version currently running. I already did the switch there so that PHP <7.2.5 versions will download the latest stable as there likely won't be an LTS snapshot.

If you can think of anyone that needs to know about this, please tag them here or send them the link.

/cc @shivammathur for setup-php please have a look here.

**Comment by stof** [comment]
@Seldaek I suggest also doing a blog post about the upcoming LTS and its impact, as I suspect that the audience following the packagist blog (or the twitter accounts tweeting about the blog post) are not the same than the audience actively following the composer issue tracker to be notified about new issues.

**Comment by Seldaek** [comment]
Yeah that's coming too once we have a release.

**Comment by azjezz** [comment]
maybe a new `https://getcomposer.org/composer-lts.phar` phar could be added so people can keep the same workflow?

**Comment by Seldaek** [comment]
Yeah perhaps, we have https://getcomposer.org/download/latest-2.x/composer.phar so I'd probably add a `latest-2.2.x` variant. I'd rather not use the word lts as we may have more of those in the future, but it conceptually makes sense 👍🏻

**Comment by Seldaek** [comment]
OK https://getcomposer.org/download/ now has a LTS download link, i.e. https://getcomposer.org/download/latest-2.2.x/composer.phar
