### ISSUE TITLE
[2.2.0-RC1] `allow-plugins` and globally installed composer plugins

### ISSUE THREAD

**Issue by boesing** [composer/composer#10350]
I recently talked with some devs about 2.2.0 and the new `allow-plugins` feature. 
I haven't verified this yet, but with this feature and globally installed plugins (which can vary from developer to developer), this might lead to a huge list of plugins which are not even required by the project itself.

So in the end, this will become an issue the same way as `.gitignore` contains non-project related files due to the different OS a developer is using (talking about you, MacOS with your `.DS_Store` files) or with `.editorconfig`.

Is this something which was already discussed?

**Comment by stof** [comment]
@Seldaek maybe globally installed plugins should be allowed based on the global config ?

**Comment by Seldaek** [comment]
The global plugins do prompt you to be enabled like others, and if you say yes the global composer.json will get modified with the allow-plugins. Local plugins cannot be allowed by the global composer.json and vice versa. It should all work as expected IMO so closing but feel free to reopen if you find a concrete issue :)

**Comment by boesing** [comment]
Sounds good, just haven't tested that as I do not have global plugins. Was more a question than a bug report so thanks for clarification.
If global plugins are not required to be allowed in each project, this actually sounds absolutely correct to me.
