### ISSUE TITLE
Bug in `conflict` report on `composer update`

### ISSUE THREAD

**Issue by ThomasLandauer** [composer/composer#10355]
I'm getting this after composer `update` and the second line seems to be a bug ("X conflicts with X"):

>  Problem 1
>    - Root composer.json requires doctrine/dbal ^3.2 -> satisfiable by doctrine/dbal[3.2.0].
>    - easycorp/easyadmin-bundle v3.5.16 conflicts with easycorp/easyadmin-bundle v3.5.16.
>    - Root composer.json requires easycorp/easyadmin-bundle ^3.5.16 -> satisfiable by easycorp/easyadmin-bundle[v3.5.16].

I think what should be reported there is what easyadmin-bundle has in its [composer.json](https://github.com/EasyCorp/EasyAdminBundle/blob/3.x/composer.json#L49):

```json
"conflict": {
        "doctrine/dbal": "<2.10 || >=3.0.0"
    },
```

My `composer.json`:

```json
"doctrine/dbal": "^3.2",
"easycorp/easyadmin-bundle": "^3.5.16",

```
Composer version 2.1.14

**Comment by Seldaek** [comment]
It would help if you could share a composer.json that allows reproducing the error.

**Comment by ThomasLandauer** [comment]
There you go:
```json
{
    "name": "thomas-landauer/composer-issue-10355",
    "type": "project",
    "require": {
        "php": "^7.3",
        "doctrine/dbal": "2.9",
        "easycorp/easyadmin-bundle": "^3.5.16"
    },
    "config": {
        "platform": {"php": "7.3"}
    }
}
```
Output I'm getting from `composer install`:
> Problem 1
    - easycorp/easyadmin-bundle v3.5.17 conflicts with easycorp/easyadmin-bundle v3.5.17.
    - easycorp/easyadmin-bundle v3.5.16 conflicts with easycorp/easyadmin-bundle v3.5.16.
    - Root composer.json requires doctrine/dbal 2.9 -> satisfiable by doctrine/dbal[v2.9.0].
    - Root composer.json requires easycorp/easyadmin-bundle ^3.5.16 -> satisfiable by easycorp/easyadmin-bundle[v3.5.16, v3.5.17].

**Comment by Seldaek** [comment]
Thanks, that was an easy fix it turns out :)
