### ISSUE TITLE
dev-main instead of dev-master for local repositories

### ISSUE THREAD

**Issue by fritzmg** [composer/composer#10360]
When you require a local repository (`type: path`) that does not have a branch info yet (either via the composer.json itself or via git) it still only works with `dev-master`. Since the standard default branch name (on GitHub at least) is `main`, may be Composer could also support `dev-main` on top of `dev-master` as a default repository name?

**Comment by Seldaek** [comment]
Can you give a way to reproduce this? Because I have no idea what you are trying to say sorry :)

**Comment by fritzmg** [comment]
Sure :)

`composer.json`
```json
{
    "name": "foobar/project",
    "type": "project",
    "require": {
        "foobar/package": "dev-main"
    },
    "repositories": {
        "foobar/package": {
            "type": "path",
            "url": "/path/to/package/"
        }
    }
}
```
`/path/to/package/composer.json`
```json
{
    "name": "foobar/package",
    "type": "library"
}
```
```
$ composer update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires foobar/package dev-main, found foobar/package[dev-master] but it does not match the constraint.
```
For repositories with no branch information you still have to use `dev-master`. I would propose that Composer will automatically fall back to `dev-master` _and_ `dev-main` as default branch names.

**Comment by Seldaek** [comment]
Ah I see, if /path/to/package is not a git repo, and version is not defined, we default to dev-master still for BC here https://github.com/composer/composer/blob/95e41ae61c8e18eb24dbce342bbae29c49777503/src/Composer/Repository/PathRepository.php#L209

It should be possible to add an alias, I'll take a look

**Comment by fritzmg** [comment]
@Seldaek has #10372 been reverted again? When requiring a local repository (via `path` I mean), Composer again only expects `dev-master` instead of (also) `dev-main`.

```
Problem 1
    - Root composer.json requires inspiredminds/foobar dev-main, found inspiredminds/foobar [dev-master] but it does not match the constraint.
```

**Comment by stof** [comment]
@fritzmg please open an issue (and provide the requested details) instead of commenting on a PR from 2021

**Comment by fritzmg** [comment]
Hm, weirdly I cannot always reproduce it anyway 🤔

**Comment by M-Zoldak** [comment]
I can confirm the issue. I have to define as `dev-master` on local machine , while on remote, `dev-main` is needed. 
As a workaround, I defined both versions in require:
```json
"require": {
    "foo/bar": "dev-main|dev-master"
}
```

**Comment by stof** [comment]
@M-Zoldak upgrade your composer version on your local machine. This way, it will use `dev-main` as well.
