### ISSUE TITLE
Misleading error message with .NET Core Framework SDK requirement message

### ISSUE THREAD

**Issue by Patrick-Davis-MSFT** [composer/composer#10375]
In the composer, when initializing a new C# Bot, in this case the enterprise people tutorial bot. I received an error message for .NET Core framework is required. When clicking on the link it takes me to the .NET Core 3.1 install page. However, installing this version of the SDK (both 64 and 32 bit) did not resolve the error message. Only after digging though the code did I discover that the Composer is actually looking for .NET (Core) v6.0.1 which is installable from a different link. 

I suggest changing the link on the error pop up from the current .NET Core 3.1 SDK install to the .NET v6.0.1 install site and the associated documentation or add additional trouble shooting guides to the documentation. 

-Current Output with version Release: 2.1.1-nightly.282852.24b070b

With .NET Core v3.1x SDK installed (no .net version)

-I currently get... 

When initializing the Enterprise People Bot, I receive the error message

Composer needs .NET Core SDK with a link to the https://dotnet.microsoft.com/en-us/download/dotnet/3.1 URI

And I expected this to happen:

When Initializing the Enterprise People Bot Tutorial, I receive the error message 

Composer needs .NET Core SDK with a link to the https://dotnet.microsoft.com/en-us/download/dotnet URI (or similar verbiage) 
and in verbose output add the line for the version check (`dotnet user-secrets`) with the expected output when using the -vv flag

**Comment by Patrick-Davis-MSFT** [comment]
This may be as simple as just changing the runtimeErrors.ts file on line ~6-16 and constants.tsx line ~97

**Comment by stof** [comment]
You are reporting that to the wrong place. This repo is about the PHP dependency manager named composer, not about a C# tool

**Comment by Patrick-Davis-MSFT** [comment]
Sorry Wrong Project... Sorry about that
