### ISSUE TITLE
DX: highlight plugin name in error message

### ISSUE THREAD

**Issue by staabm** [composer/composer#10381]
IMO DX wise it would be helpful if the plugin name would be printed in a different color then the rest of the error message

using composer 2.2 on git-bash it is currently hard to see the actual plugin name
![grafik](https://user-images.githubusercontent.com/120441/147084314-c837c4a4-3edf-4298-bba5-9d4804915dad.png)

**Comment by Seldaek** [comment]
I am unsure about this.. On the one hand yes it'd make it easier to scan, but on the other hand I'd really prefer if people read the whole message here rather than skimming it :)

Need to see how easily we can highlight this while keeping the warning background. I don't think we have an additional style that'd look decent yet for this.

**Comment by stof** [comment]
@Seldaek maybe the output should add a blank line between the warnings of each plugin to make things easier to read when multiple plugins are involved. This would make it easier to find the beginning of the new warning for which a question is asked.

**Comment by johnstevenson** [comment]
Or perhaps split the warning from the question, similar to how we elevate on Windows selfupdate.

![selfupdate](https://user-images.githubusercontent.com/881777/147118049-1857deef-8230-4f8a-a760-f3da07774eda.png)

Perhaps it would be clearer to shorthen the question to:
```
Do you trust "plugin name" to execute code and wish to endable it [y, n, d, ?]
```
Then ouput the result of the selection in the next line, for example:
```
plugin has been added to allow_plugins in composer.json
```

**Comment by Seldaek** [comment]
Hopefully this  helps :)

![image](https://user-images.githubusercontent.com/183678/147663376-0955b066-f407-42a5-8616-3b051c819cf9.png)

**Comment by staabm** [comment]
I like it, thx
