### ISSUE TITLE
Composer in crontab

### ISSUE THREAD

**Issue by remco-pc** [composer/composer#10391]
When i run composer in crontab, crontab will use /var/mail/mail as an error message appears. also the output of composer isn't catched by the default php exec command but this will result in the email from crontab.

From root@localhost Wed Dec 22 23:43:02 2021
Return-path: <root@localhost>
Envelope-to: root@localhost
Delivery-date: Wed, 22 Dec 2021 23:43:02 +0000
Received: from root by 0ccb8ae5d8c4 with local (Exim 4.94.2)
        (envelope-from <root@localhost>)
        id 1n0BGA-0000Mm-2i
        for root@localhost; Wed, 22 Dec 2021 23:43:02 +0000
From: root@localhost (Cron Daemon)
To: root@localhost
Subject: Cron <root@0ccb8ae5d8c4> /usr/bin/funda admin taskrunner
MIME-Version: 1.0
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 8bit
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
Message-Id: <E1n0BGA-0000Mm-2i@0ccb8ae5d8c4>
Date: Wed, 22 Dec 2021 23:43:02 +0000

Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files
4 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

And I expected this to happen:
crontab running composer without trying to send an email with the error when no error happens.

**Comment by Seldaek** [comment]
You can run with --quiet if you want to suppress output (execpt errors). Or you can redirect all output to a log file if you don't want crontab to see it.

**Comment by remco-pc** [comment]
actually i have a button which triggers this event too and i want the user to show the composer information, everything else I execute is shown to the user. i will use --quiet until this is fixed not to pollute the /var/mail/mail error log

**Comment by Seldaek** [comment]
We aren't going to fix anything here, there's nothing to be fixed as far as I can tell.

**Comment by stof** [comment]
The issue is that crontab does not only send an email in case of errors. It also sends an email in case of any output of the script. So if you don't want an email, `--quiet` is the solution.
