### ISSUE TITLE
Warn users that don't have git installed?

### ISSUE THREAD

**Issue by javiereguiluz** [composer/composer#10399]
In Symfony Docs we've received [this PR](https://github.com/symfony/symfony-docs/pull/16304/files) to add a caution message telling users that having `git`  installed is mandatory to use Composer.

I don't know if this is true, but if Composer truly requires `git` to work, shouldn't we check that somewhere and output an error message if `git` is not installed? Thanks!

**Comment by stof** [comment]
in most cases, git is not necessary (unless you need to install a package from a git repository directly).

However, the symfony/symfony repo relies on path repositories to manage the Symfony contracts subpackages during development, and the version guessing for path repositories relies on git.

**Comment by Seldaek** [comment]
Right, closing as I don't think we can/need to do anything here.
