### ISSUE TITLE
composer hang even with `--no-interaction` passed

### ISSUE THREAD

**Issue by michael-careplanner** [composer/composer#10393]
My `composer.json`:

```{
    "name": "test/test",
    "require": {
        "composer/package-versions-deprecated": "1.11.99.4"
    }
}
```

Output of `composer diagnose`:

```
For additional security you should declare the allow-plugins config with a list of packages names that are allowed to run code. See https://getcomposer.org/allow-plugins
You have until July 2022 to add the setting. Composer will then switch the default behavior to disallow all plugins.
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.composer/package-versions-deprecated : exact version constraints (1.11.99.4) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (2.2.0 => 2.2.1)
Composer version: 2.2.0
PHP version: 8.1.1
PHP binary path: /usr/local/bin/php
OpenSSL version: OpenSSL 1.1.1l  24 Aug 2021
cURL version: 7.80.0 libz 1.2.11 ssl OpenSSL/1.1.1l
zip: extension present, unzip present, 7-Zip present (7z)
```

When I run this command: 

```
docker run -it --rm --volume ~/tmp/composer-bug2:/app --user $(id -u):$(id -g) composer:2.2.0 install --no-interaction -vvv
```

I get the following output: 

```
Command runs successfully the first time but hangs on subsequent runs.
```

And I expected this to happen:

Command to run to completion on repeated runs. This seems to be related to the handling of the `--no-interaction` flag combined with the changes made in 2.2.0 to add the `allow-plugins` config value (https://github.com/composer/composer/pull/10314).

This runs successfully repeatedly by moving the `--no-interaction` flag before the `install`:
`docker run -it --rm --volume ~/tmp/composer-bug2:/app --user $(id -u):$(id -g) composer:2.2.0 --no-interaction install`
However `composer install --help` suggests that the initial form with `--no-interaction` after `install` should also be valid (and it works the first time it is ran that way).

Another workaround is to remove the `-it` flag from the `docker run`, I guess then composer can detect that it's running in non-interactive mode.

**Comment by Seldaek** [comment]
Can't seem to reproduce without docker.. and I'm not really interested in trying to run this in docker, sorry.

**Comment by michael-careplanner** [comment]
I've done some more digging and found that the issue is in the entrypoint to the docker container - https://github.com/composer/docker/blob/main/2.2/docker-entrypoint.sh#L10

This calls `composer help` with the first argument passed into the container. This is why moving `--no-interaction` before `install` works, it then runs `composer help --no-interaction`.

If running `composer help` is expected to result in an interactive prompt when plugins that aren't in allowed-plugins are detected then I'm happy for you to close this and I'll raise an issue on https://github.com/composer/docker instead.

**Comment by stof** [comment]
To me, this docker entrypoint should be forcing `--no-interaction` when running this `composer help` command, as it hides the output and so won't be compatible with interaction.
so yes, please open an issue on that docker repo (or even better, submit a PR with the fix)
