### ISSUE TITLE
Composer hangs on PHP 8.1 with enabled JIT

### ISSUE THREAD

**Issue by brusch** [composer/composer#10400]
When JIT is enabled in PHP 8.1 e.g. by using  `opcache.jit_buffer_size=256M` any composer command just hangs (including `about` and `diagnose`, even when runing with `-vvv` there's no single byte of output. 

It worked with PHP 8.0. 

The problem is obviously somewhere here: 
https://github.com/composer/composer/blob/main/src/Composer/Command/UpdateCommand.php#L170

If you run composer with `-n` it works just fine even with JIT enabled.

**Comment by Seldaek** [comment]
I don't think the line you pointed to is relevant, as that only triggers if doing an update with `--interactive`. It's not directly related to the -n flag.

Anyway.. seems like a JIT bug that should be reported to PHP itself IMO.

**Comment by Seldaek** [comment]
And FWIW, I can't reproduce it, so if you do report it to PHP try and include more details.
