### ISSUE TITLE
Please make it available for Ubuntu or Linux Mint 

### ISSUE THREAD

**Issue by mhcwebdesign** [composer/composer#10403]
Using Linux Mint 20.1, it's built-in Synaptic Package Manager still uses your old version 1.10.1-1.

Is there any chance that your latest Composer version (e.g.2.2.1) could be made available for Ubuntu or Linux Mint?

I managed to install your latest version manually, thanks to the instructions at https://getcomposer.org/download/  but it would be nice to have your software available for mainstream Linux package managers.

**Comment by Seldaek** [comment]
You can track https://github.com/composer/composer/issues/9830 maybe we'll do it one day
