### ISSUE TITLE
composer outdated ou composer update Fatal error: Uncaught TypeError

### ISSUE THREAD

**Issue by achatpc** [composer/composer#10408]
My `composer.json`:

```json
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.4.3-p1",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "require": {
        "composer/composer": "^1.9 || ^2.0",
        "mageplaza/magento-2-french-language-pack": "dev-master",
        "mageplaza/magento-2-italian-language-pack": "dev-master",
        "mageplaza/magento-2-spanish-language-pack": "dev-master",
        "mageplaza/magento-2-german-language-pack": "dev-master",
        "mageplaza/magento-2-dutch-language-pack": "dev-master",
        "iceshop/icecatconnect": "~2.5",
        "mageplaza/module-smtp": "^4.0",
        "smile/elasticsuite": "~2.10.5",
        "amasty/geoipredirect": "^1.3",
        "shoppingfeed/php-feed-generator": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "shoppingfeed/php-sdk": "^0.2.4",
        "amasty/geoip": "^1.3",
        "amasty/module-gdpr": "^1.5",
        "amasty/base": "^1.9.10",
        "getresponse/magento2-module": "^1.0",
        "geoip2/geoip2": "^2.9",
        "getresponse/magento2": "20.3.*",
        "rubic/magento2-module-clean-checkout": "^2.0",
        "psr/container": "*",
        "magento/module-amazon": "*",
        "infomodus/upslabel": "^8.9.1",    
        "amasty/paction": "^1.1",
        "amasty/ogrid": "^1.2",
        "apptrian/facebook-pixel": "^4.1",
        "amasty/ajax-scroll": "^1.4",
        "amasty/module-mass-order-actions": "1.5.7",
        "magento/services-connector": "1.*",
        "cweagans/composer-patches": "^1.6",
        "geissweb/module-euvat": "^1.12",
        "magento/composer-root-update-plugin": "~1.0",
        "amasty/module-order-status": "^1.0",
        "amasty/module-pdf-customizer": "^1.3",
        "amasty/module-fpc-warmer": "^2.2",
        "webpanda/catalog-url-rewrites": "^1.0",
        "meetanshi/magento2-guest-to-customer": "^1.0",
        "olegkoval/magento2-regenerate-url-rewrites": "^1.5",
        "magento/quality-patches": "^1.0",
        "mirasvit/module-indexer": "*",
        "mirasvit/module-seo": "*",
        "dvdoug/boxpacker": "^3.6.0",
        "magevision/module-mass-email-customers": "^2.3",
        "prince/magento2-paymentfee": "^2.1",
        "squizlabs/php_codesniffer": "~3.5.4",
        "amasty/module-page-speed-optimizer": "^2.0",
        "amasty/xnotif": "1.13.2",
        "trustpilot/module-reviews": "^2.6",
        "classyllama/module-zendesk": "^1.1",
        "onestepcheckout/iosc": "^1.2",
        "magento/product-community-edition": "2.4.3-p1",
        "laminas/laminas-escaper": "2.7.0"
    },
    "require-dev": {
        "allure-framework/allure-phpunit": "~1.4",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.7.0",
        "friendsofphp/php-cs-fixer": "~2.18.1",
        "lusitanian/oauth": "~0.8.10",
        "magento/magento-coding-standard": "*",
        "magento/magento2-functional-testing-framework": "^3.0",
        "pdepend/pdepend": "~2.7.1",
        "phpcompatibility/php-compatibility": "^9.3",
        "phpmd/phpmd": "^2.8.0",
        "phpstan/phpstan": "^0.12.77",
        "phpunit/phpunit": "^9",
        "sebastian/phpcpd": "^6.0.3",
        "squizlabs/php_codesniffer": "~3.5.4",
        "symfony/finder": "^5.2"
    },
    "conflict": {
        "gene/bluefoot": "*"
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": [
                "app/code/"
            ]
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\PhpStan\\": "dev/tests/static/framework/Magento/PhpStan/",
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/"
        }
    },
    "prefer-stable": true,
    "extra": {
        "component_paths": {
            "trentrichardson/jquery-timepicker-addon": "lib/web/jquery/jquery-ui-timepicker-addon.js",
            "components/jquery": [
                "lib/web/jquery.js",
                "lib/web/jquery/jquery.min.js",
                "lib/web/jquery/jquery-migrate.js"
            ],
            "blueimp/jquery-file-upload": "lib/web/jquery/fileUploader",
            "components/jqueryui": [
                "lib/web/jquery/jquery-ui.js"
            ],
            "twbs/bootstrap": [
                "lib/web/jquery/jquery.tabs.js"
            ],
            "tinymce/tinymce": "lib/web/tiny_mce_5"
        }
    },
    "minimum-stability": "stable",
    "repositories": {
        "osc": {
            "type": "composer",
            "url": "https://repo.onestepcheckout.com/"
        },
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/",
            "exclude": [
                "amasty/*",
                "iceshop/*"
            ]
        },
        "amasty": {
            "type": "composer",
            "url": "https://composer.amasty.com/community/"
        },
        "aheadworks": {
            "type": "composer",
            "url": "https://dist.aheadworks.com/"
        },
        "safemage": {
            "type": "composer",
            "url": "https://www.safemage.com/repositories/"
        },
        "geissweb": {
            "type": "composer",
            "url": "https://packages.geissweb.de"
        },
        "mirasvit-far2": {
            "type": "composer",
            "url": "https://@packages.mirasvit.com/"
        },
        "mirasvit-seo2": {
            "type": "composer",
            "url": "https://@packages.mirasvit.com/"
        }
    },
    "config": {
        "allow-plugins": {
            "composer/package-versions-deprecated": true,
            "laminas/laminas-dependency-plugin": true,
            "dealerdirect/phpcodesniffer-composer-installer": true,
            "magento/magento-composer-installer": true,
            "magento/inventory-composer-installer": true,
            "cweagans/composer-patches": true,
            "magento/composer-root-update-plugin": true
        }
    }
}

```

Output of `composer diagnose`:

Fatal error: Uncaught TypeError: Argument 3 passed to Composer\Package\Locker::__construct() must be an instance of Composer\Repository\RepositoryManager, instance of Composer\Installer\InstallationManager given, called in phar:///usr/local/bin/composer/src/Composer/Factory.php on line 446 and defined in /var/www/html/vendor/composer/composer/src/Composer/Package/Locker.php:54
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Factory.php(446): Composer\Package\Locker->__construct()
#1 phar:///usr/local/bin/composer/src/Composer/Factory.php(643): Composer\Factory->createComposer()
#2 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(445): Composer\Factory::create()
#3 phar:///usr/local/bin/composer/src/Composer/Command/BaseCommand.php(65): Composer\Console\Application->getComposer()
#4 phar:///usr/local/bin/composer/src/Composer/Command/BaseCommand.php(150): Composer\Command\BaseCommand->getComposer()
#5 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(211): Composer\Com in /var/www/html/vendor/composer/composer/src/Composer/Package/Locker.php on line 54

```

When I run this command: <!-- run it with `-vvv` added to it ideally to get full debug output -->

```
Running 2.2.2 (2021-12-29 14:15:27) with PHP 7.4.27 on Linux / 5.4.0-91-generic
Reading ./composer.json (/var/www/html/composer.json)
Loading config file /home/magento_user/.config/composer/auth.json
Loading config file ./composer.json (/var/www/html/composer.json)
Loading config file /var/www/html/auth.json
Reading /var/www/html/auth.json
Checked CA file /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a file.
Checked directory /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a directory.
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Reading /home/magento_user/.config/composer/composer.json
Loading config file /home/magento_user/.config/composer/auth.json
Loading config file /home/magento_user/.config/composer/composer.json (/home/magento_user/.config/composer/composer.json)
Loading config file /home/magento_user/.config/composer/auth.json
Reading /home/magento_user/.config/composer/auth.json
Reading /var/www/html/vendor/composer/installed.json
Reading /home/magento_user/.config/composer/vendor/composer/installed.json
Loading plugin PackageVersions\Installer (from composer/package-versions-deprecated)
Loading plugin Laminas\DependencyPlugin\DependencyRewriterPluginDelegator (from laminas/laminas-dependency-plugin)
Activating Laminas\DependencyPlugin\DependencyRewriterV2
Loading plugin Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin (from dealerdirect/phpcodesniffer-composer-installer)
Loading plugin MagentoHackathon\Composer\Magento\Plugin (from magento/magento-composer-installer)
activate magento plugin
Loading plugin Magento\InventoryComposerInstaller\Plugin (from magento/inventory-composer-installer)
Loading plugin cweagans\Composer\Patches (from cweagans/composer-patches)
Loading plugin Magento\ComposerRootUpdatePlugin\Plugin\PluginDefinition (from magento/composer-root-update-plugin)
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Composer\Package\Locker::__construct() must be an instance of Composer\Repository\RepositoryManager, instance of Composer\Installer\InstallationManager given, called in phar:///usr/local/bin/composer/src/Composer/Factory.php on line 446 and defined in /var/www/html/vendor/composer/composer/src/Composer/Package/Locker.php:54
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Factory.php(446): Composer\Package\Locker->__construct()
#1 phar:///usr/local/bin/composer/src/Composer/Factory.php(643): Composer\Factory->createComposer()
#2 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(445): Composer\Factory::create()
#3 phar:///usr/local/bin/composer/src/Composer/Command/BaseCommand.php(65): Composer\Console\Application->getComposer()
#4 phar:///usr/local/bin/composer/src/Composer/Command/BaseCommand.php(150): Composer\Command\BaseCommand->getComposer()
#5 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(211): Composer\Com in /var/www/html/vendor/composer/composer/src/Composer/Package/Locker.php on line 54

Fatal error: Uncaught TypeError: Argument 3 passed to Composer\Package\Locker::__construct() must be an instance of Composer\Repository\RepositoryManager, instance of Composer\Installer\InstallationManager given, called in phar:///usr/local/bin/composer/src/Composer/Factory.php on line 446 and defined in /var/www/html/vendor/composer/composer/src/Composer/Package/Locker.php:54
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Factory.php(446): Composer\Package\Locker->__construct()
#1 phar:///usr/local/bin/composer/src/Composer/Factory.php(643): Composer\Factory->createComposer()
#2 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(445): Composer\Factory::create()
#3 phar:///usr/local/bin/composer/src/Composer/Command/BaseCommand.php(65): Composer\Console\Application->getComposer()
#4 phar:///usr/local/bin/composer/src/Composer/Command/BaseCommand.php(150): Composer\Command\BaseCommand->getComposer()
#5 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(211): Composer\Com in /var/www/html/vendor/composer/composer/src/Composer/Package/Locker.php on line 54

```

I get the following output: <!-- FULL OUTPUT please, not just what you think is relevant -->

```
...replace me...
```

And I expected this to happen:

**Comment by herndlm** [comment]
Hi, this reads like it is related to #10401. Maybe you want to check with the latest composer snapshot

**Comment by achatpc** [comment]
> Salut, cela se lit comme si c'était lié à #10401 . Peut-être que vous voulez vérifier avec le dernier instantané du compositeur

Thank you, composer self-update --rollback fix my issue. Waiting update...

**Comment by Seldaek** [comment]
Yes, 2.2.3 will be available later today with the fix.

**Comment by Seldaek** [comment]
2.2.3 is [out now](https://github.com/composer/composer/releases/tag/2.2.3)

**Comment by achatpc** [comment]
Great. Happy new year.
