### ISSUE TITLE
[ErrorException] chdir(): No such file or directory (errno 2)

### ISSUE THREAD

**Issue by gaillafr** [composer/composer#1041]
Hi,

I am having an issue using composer.
I am trying to use composer on a fresh Ubuntu 12.04 with the following command :

```
php composer.phar create-project symfony/framework-standard-edition /home/francois/www
```

But it does not work, I have this error :

```
[ErrorException]
chdir(): No such file or directory (errno 2)
```

This error only happens when I try to use composer.
Any idea ?

Here is a list of installed packages :

> php-pear
> php5-cli
> php5-common
> php5-curl
> php5-dev
> php5-fpm
> php5-gd
> php5-imagick
> php5-imap
> php5-intl
> php5-mcrypt
> php5-memcache
> php5-ming
> php5-mysql
> php5-ps
> php5-pspell
> php5-recode
> php5-snmp
> php5-sqlite
> php5-tidy
> php5-xcache
> php5-xmlrpc
> php5-xsl

Thank you,
Regards.

**Comment by xl714** [comment]
Hello, I had the same issue with 
`composer create-project symfony/skeleton /my/directory/myproject`
 but simply doing this instead:
```
cd /my/directory
composer create-project symfony/skeleton myproject
```
did the trick
