### ISSUE TITLE
Composer 2 plugin autoloading

### ISSUE THREAD

**Issue by bytestream** [composer/composer#10413]
See https://github.com/Dealerdirect/phpcodesniffer-composer-installer/issues/143

I believe this might be a composer bug as it shouldn't be autoloading application dependencies which is what produces the conflict? The plugin uses composer dependencies, and the stack trace seems to show Composer autoloading the application dependency version of `symony/finder`?

I've observed the issue in Composer 2.0.6, 2.1.10, 2.1.14. Most of the time it works, sometimes it fails, always in the context of CI docker images.

**Comment by Seldaek** [comment]
This should be resolved soon as we migrate to Symfony 5.4, but anyway this should only happen if a plugin depends on symfony/finder, or if you have a php script handler in your composer.json. And in those cases we just have to load the application dependencies to avoid all sorts of other problems, but that sometimes does cause glitches with our deps.

You didn't really provide enough info though so I have no idea what the exact cause is.

**Comment by bytestream** [comment]
Thanks for the insight @Seldaek 

This is `composer.json` `scripts`:
```json
    "scripts": {
        "lint:analyse": [
            "Composer\\Config::disableProcessTimeout",
            "@php vendor/bin/phpcs --standard=phpcs.xml --report=json . > storage/phpcs.txt",
            "@php vendor/bin/sarb remove-baseline storage/phpcs.txt phpcs.baseline storage/phpcs-baseline-removed.txt"
        ],
        "lint:fix": [
            "Composer\\Config::disableProcessTimeout",
            "@php artisan lint:fix"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump"
        ],
        "post-create-project-cmd": [
            "php -r \"copy('.env.example', '.env');\"",
            "php artisan key:generate"
        ],
        "phpstan": [
            "phpstan analyse --memory-limit=-1"
        ]
    },
```

So the `post-autoload-dump` script is what is causing Composer to load the application dependencies.

**Comment by Seldaek** [comment]
Ah well yes that definitely looks like the root cause of the problem. Maybe you can run your CI with `--no-autoloader` to skip that and then run a separate dump-autoload command?

**Comment by bytestream** [comment]
I'm pretty sure I don't actually need the dependency. It's coming via [`slevomat/coding-standard`](https://github.com/slevomat/coding-standard/blob/ebe92fe0e976cd4d7ce4b554bce773c54d4685a4/composer.json#L19) and I'm loading all necessary coding standards manually anyway...

Would using the new `allow-plugins` option fix it?
```json
"allow-plugins": {
  "dealerdirect/phpcodesniffer-composer-installer": false,
  "composer/package-versions-deprecated": true
}
```

**Comment by Seldaek** [comment]
I am not sure if that'll help, as per the above comments the issue is in:

```
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump"
        ],
```

Nothing to do with the plugin as far as I can tell, the plugin is maybe just a symptom of the problem, so you can try disabling it and see if it helps hide the problem for now..

**Comment by bytestream** [comment]
> Would using the new allow-plugins option fix it?

I think this seems to have alleviated the issue. Closing.
