### ISSUE TITLE
Binary proxy installer doesn't handle jar files properly

### ISSUE THREAD

**Issue by gauthierm** [composer/composer#10426]
With Composer 2.2.2 the code in https://github.com/composer/composer/blob/main/src/Composer/Installer/BinaryInstaller.php wraps all installed vendor binaries in a proxy. This is a great idea, but causes problems with package-provided binaries that are JAR files. JAR files get treated as directly executable files rather than just blobs that get passed to `java -jar`. This causes any existing callers of the installed binaries to fail with:

```
Error: Invalid or corrupt jarfile ./vendor/bin/yuicompressor.jar
```

I've noticed this problem with YUI Compressor (yes, it's old and crusty; it's for an old project 😆) , but it likely affects some other packages.

My `composer.json`:

```json
{
  "name": "mynamespace/myproject",
  "require": {
    "packaglist/yuicompressor-bin": "^2.4.8"
  }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Composer version: 2.2.2
PHP version: 7.4.27
PHP binary path: /usr/bin/php
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
cURL version: 7.29.0 libz 1.2.7 ssl NSS/3.53.1
zip: extension present, unzip present, 7-Zip not available
```

When I run this command:

```
composer install
java -jar vendor/bin/yuicompressor-bin.jar
```

I get the following output:

```
Error: Invalid or corrupt jarfile ./vendor/bin/yuicompressor.jar
```

I expected it to run the jarfile. Additionally, running the generated proxy script treats the jar file as directly executable and outputs:

```
[snip]/vendor/packaglist/yuicompressor-bin/bin/yuicompressor.jar: line 1: $'PK\003\004': command not found
[snip]/vendor/packaglist/yuicompressor-bin/bin/yuicompressor.jar: line 2: $'\b\027': command not found
[snip]/vendor/packaglist/yuicompressor-bin/bin/yuicompressor.jar: line 2: $'\277B': command not found
[snip]/vendor/packaglist/yuicompressor-bin/bin/yuicompressor.jar: line 36: syntax error near unexpected token `)'
[snip]/vendor/packaglist/yuicompressor-bin/bin/yuicompressor.jar: line 36: `�ބ֒�`���6yEtVm�a�k.C,�Ia�NuZ�Ĉ���.9��r�����E>R��ʏ4U�����34'P�<�;�?�z�BE�9J�I7��7s
                                                                                                                                                                                    �����1F��
       �8&�!�I�'
```

I assume it's inadvisable to install JAR files with composer in the first place, but given that it does happen, the proxy bin generator should either:

 - ignore jar files and not generate a proxy, or
 - wrap the final call in `java -jar` for jar files

**Comment by stof** [comment]
the expectation for the `bin` section of a package's metadata is to provide executables. Your case is abusing the config, and was already broken on older composer versions for systems that cannot use a symlink.

**Comment by Seldaek** [comment]
Yeah after taking a closer a look, I think this is kinda misuse. It worked accidentally with the symlinks on some envs, but really what the package should have done is add a shell script `bin/yuicompressor` with something like this in it:

```
#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
java -jar "$SCRIPT_DIR/yuicompressor.jar"
```

And then `bin/yuicompressor` goes in the composer.json as bin.

Anyway given this worked in the majority of cases before and as the fix is rather simple, I think we can retain support for .jar here.

**Comment by Seldaek** [comment]
It'd be good if you can check whether the fix works, as I really don't want to install java to verify this :D

You can verify with this:

```
composer selfupdate --snapshot
rm vendor/bin/yui*
composer install
vendor/bin/yuicompressor.jar
```
(possibly adjusting the vendor/bin to whatever your bin dir is)

**Comment by stof** [comment]
@Seldaek your case still does not preserve support for running `java -jar vendor/bin/yuicompressor-bin.jar` (which is the way the file was run before). I don't think anyone expects being able to run `vendor/bin/yuicompressor.jar` directly (that's not possible with jar files)

**Comment by Seldaek** [comment]
Yeah, that indeed won't work. Maybe it's best to revert this hackery and let the packagelist/yuicompressor-bin package be fixed instead.

**Comment by Seldaek** [comment]
Also note that as alternative, if the origin package does not get fixed, you can simply bypass the symlink you were using and call directly `java -jar vendor/packagelist/yuicompressor-bin/bin/yuicompressor.jar` which will work just fine.

**Comment by gauthierm** [comment]
I'm happy with this. Than you for investigating the issue!
