### ISSUE TITLE
Possible false negative in autoloading standard compliance check?

### ISSUE THREAD

**Issue by thomasfw** [composer/composer#10424]
### The Issue

Now that Composer v2 has stopped autoloading classes that it thinks don't comply with the autoloading standard used (`psr-4` in our case), our conditionally declared classes are no longer autoloaded, even though they do adhere to the standard.

```
Class AMCE\Modules\Mail\Compatibility\PHPMailerCompat located in ./{...}/Modules/Mail/Compatibility/PhpMailerCompat.php does not comply with psr-4 autoloading standard. Skipping.
Class AMCE\Modules\Mail\Compatibility\PHPMailerExceptionCompat located in ./{...}/Modules/Mail/Compatibility/PHPMailerExceptionCompat.php does not comply with psr-4 autoloading standard. Skipping.
```

Is this intended behaviour, or a bug caused by the way Composer parses class declarations within files (for an admittedly small edge-case)? From what I can tell, I don't see any reason that a conditionally declared class can't be included within the generated classmap.

---

### Some Background

I'm including this information on the assumption that somebody will inevitably tell me I shouldn't ever make a conditional class declaration.

We have a couple of conditionally declared classes in a (Composer installable) email related WordPress plugin of ours. WordPress recently upgraded the bundled [`PHPMailer`](https://github.com/PHPMailer/PHPMailer) files to a new major release, and the conditional class declarations allow our plugin to be backwards compatible across multiple WordPress versions even where this breaking change exists. 

In our plugin we only type hint against and use our `PHPMailerCompat` / `PHPMailerExceptionCompat` classes directly, and these extend whichever underlying `PHPMailer` classes are available, depending on the installed WordPress version. You can see the full class declarations below...

<details>
  <summary><b>PHPMailerCompat</b></summary>

```php
<?php

namespace AMCE\Modules\Mail\Compatibility;

// PHPMailerCompat always extends/proxies the PhpMailer class installed by the current version of WordPress.
// 
// Load PHPMailer class from WP includes so we can extend it.
// We must include directly from WP filesystem as requiring and loading the package through composer
// may lead to version based compatibility issues.
// 
// Note that since WP 5.5, the path to and namespace for phpmailer has changed, which complicates our
// class inheritance. We now conditionally define the PHPMailerCompat class which either extends (and 
// loads the files for) \PHPMailer or \PHPMailer\PHPMailer\PHPMailer based on the WP version.

if ( version_compare( get_bloginfo('version'), '5.5', '>=' ) )
{
    if ( ! class_exists('\PHPMailer\PHPMailer\PHPMailer', false) ) 
    {
        require_once ABSPATH . WPINC . '/PHPMailer/PHPMailer.php';
        require_once ABSPATH . WPINC . '/PHPMailer/Exception.php';
        require_once ABSPATH . WPINC . '/PHPMailer/SMTP.php';
    }
    class PHPMailerCompat extends \PHPMailer\PHPMailer\PHPMailer 
    {
        public function __construct($exceptions = null) { parent::__construct($exceptions); }
    }
}
else
{
    if ( ! class_exists('\PHPMailer', false) ) 
    {
        require_once ABSPATH . WPINC . '/class-phpmailer.php';
    }
    class PHPMailerCompat extends \PHPMailer 
    {
        public function __construct($exceptions = null) { parent::__construct($exceptions); }
    }
}
```
</details>

<details>
  <summary><b>PHPMailerExceptionCompat </b></summary>

```php
<?php

namespace AMCE\Modules\Mail\Compatibility;

// PHPMailerExceptionCompat always extends/proxies the PhpMailer Exception class installed by the current version of WordPress.
//
// Note that since WP 5.5, the path to and namespace for phpmailer has changed, which complicates our
// class inheritance. We now conditionally define the PHPMailerExceptionCompat class which either extends (and 
// loads the files for) \PHPMailer\PHPMailer\Exception or \phpmailerException based on the WP version.
// We can then use PHPMailerExceptionCompat (mainly for type-hinting/checking) instead of the concrete exception 
// class name.

if ( version_compare( get_bloginfo('version'), '5.5', '>=' ) )
{
    if ( ! class_exists('\PHPMailer\PHPMailer\Exception', false) ) 
    {
        require_once ABSPATH . WPINC . '/PHPMailer/Exception.php';
    }
    class PHPMailerExceptionCompat extends \PHPMailer\PHPMailer\Exception {}
}
else
{
    // The phpmailerException is also defined in the class-phpmailer.php file.
    if ( ! class_exists('\phpmailerException', false) )
    {
        require_once ABSPATH . WPINC . '/class-phpmailer.php';
    }
    class PHPMailerExceptionCompat extends \phpmailerException {}
}
```
</details>

Having tried other more elegant approaches (i.e. conditionally wiring abstractions to the available classes through our DI container), none of them also provide us with the ability to type hint against our `PHPMailerExceptionCompat` when catching mail exceptions. Conditional class declarations seem to be the only way we can achieve the backwards compatibility we need in this case.

Whilst this is far from best practice (not that that matters in WordPress), this is something that is supported by PHP, and therefore shouldn't be invalidated by Composer.

---

### A Workaround

If this isn't considered a bug, I assume the correct workaround would be to exclude these files from Composer's autoloader with [`exclude-from-classmap`](https://getcomposer.org/doc/04-schema.md#exclude-files-from-classmaps), and to register a separate autoloader to load them manually?

```json
{
    "autoload": {
        "exclude-from-classmap": [ "/src/Modules/Mail/Compatibility/" ],
        "psr-4": { "ACME\\": "src/" }
    }
}
```

**Comment by Seldaek** [comment]
so I tried reproducing it and for me it works fine with the condition that I fix the namespace in the php source from AMCE to ACME..

I am not sure how to repro the error. Maybe you can make a sample git repo which reproduces it with just a composer.json and some php files?

**Comment by Seldaek** [comment]
Alternatively you could give the exact path of the PHPMailerCompat.php file (relative from composer.json), and the exact copy of your autoload config. I am fairly sure it's a misconfiguration/misunderstanding.

**Comment by thomasfw** [comment]
@Seldaek my bad.. I think the conditional logic wrapping those classes threw me completely off track. The filenames for the two files also happen to be incorrectly capitalised (`PhpMailerCompat.php` / `PHPMailerCompat.php`) and I'm obviously blind. 

Thanks

**Comment by Seldaek** [comment]
Heh no worries, glad there's no bug on our end ;)
