### ISSUE TITLE
[2.2.x] Binary Proxy Bin Execution No Permissions 

### ISSUE THREAD

**Issue by thefrosty** [composer/composer#10441]
Following up on https://github.com/composer/composer/issues/10433, where we are following the situation found in [has dependencies with vendor binaries](https://getcomposer.org/doc/articles/vendor-binaries.md#what-happens-when-composer-is-run-on-a-composer-json-that-has-dependencies-with-vendor-binaries-listed-). Our bing shell files are "copied" to the root bin "pointing to the actual location instead of previously symlinked. 

Calling the proxied files has Permission denied errors when calling the original bin files as of Composer 2.2.x

Output of `composer diagnose`:

```
Checking composer.json: WARNING
require.<vendor>/wordpress-mu-loader : unbound version constraints (*) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: ***
Dev Public Key Fingerprint: ***

OK
Checking composer version: OK
Composer version: 2.2.3
PHP version: 7.4.12 - Package overridden via config.platform, actual: 7.4.2
PHP binary path: /home/travis/.phpenv/versions/7.4.2/bin/php
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
cURL version: 7.58.0 libz 1.2.11 ssl OpenSSL/1.1.1
zip: extension present, unzip present, 7-Zip not available
```

When I run this command: `composer run-script phpcs`

```
./vendor/bin/phpcs.sh: line 22: /home/travis/build/<vendor>/<project-a>/vendor/<vendor>/<project-b>/bin/phpcs.sh: Permission denied
```

And I expected this to happen: 

Previously running any composer script which called a bin package in project-b worked. With proxying now, it constantly fails.

**Comment by Seldaek** [comment]
I don't quite understand what you are doing here. Can you ensure that phpcs.sh has correct execution permissions in project-b's repository? If that doesn't fix it then I'll need clear repro instructions because as is I have no idea how you get into this state. Ideally if you can do a composer.json which reproduces it with public packages that's great, or a git repo with some packages using a `path` repo perhaps if you need more data.

**Comment by thefrosty** [comment]
I think I may now know what the issue is... `vendor/bin/phpcs` is no longer in the paroject b's bin, but in the main project a's bin, so I have to use the new COMPOSER_BIN_DIR in the project b's phpcs.sh file to call phpcs.

Regardless...

---

The best I can explain for two private repos is:

## Project A (main):
#### composer.json
```json
{
  "name": "<my-vendor>>/project-a",
  "config": {
    "allow-plugins": {
      "<my-vendor>/*": true
    }
  },
  "require": {
    "php": "^7.4",
    "<my-vendor>/project-b": "^2.7"
  },
  "scripts": {
    "phpcs": [
      "bash ./vendor/bin/phpcs.sh"
    ]
  }
}
```

#### .travis.yml
```yaml
jobs:
  include:
    - php: '7.4'
      script:
        - composer phpcs

install:
  - "./.travis/scripts/setup_dependencies.sh"
```

## Project B
#### composer.json
_The shell file just checks for changed *.php files in commit and calls `./vendor/bin/phpcs`. (maybe this is the issue
that needs to be changed)_
```json
{
  "name": "<my-vendor>/project-b",
  "config": {
    "allow-plugins": {
      "*": true
    }
  },
  "bin": [
    "bin/phpcs.sh"
  ],
  "scripts": {
    "phpcs": [
      "bash ./bin/phpcs.sh"
    ]
  }
}
```

#### phpcs.sh
```shell
#!/usr/bin/env bash

set -e

# Based off: https://gist.github.com/Hounddog/3891872
# Go to root of the repository
echo 'Checking PHPCS'

if [[ $(git rev-parse --verify HEAD) ]]; then
  against='HEAD'
elif [[ $(git rev-parse --verify develop) ]]; then
  against='develop'
elif [[ $(git rev-parse --verify master) ]]; then
  against='master'
else
  echo "git can't verify HEAD, develop or master."
  exit 1
fi

baseCommit=$(git merge-base develop ${against})
commitFiles=$(git diff --name-only "$baseCommit")

args="--standard=phpcs.ruleset.xml"
phpFiles=""
phpFilesCount=0
for f in ${commitFiles}; do
  if [[ ! -e ${f} ]]; then
    continue
  fi
  if [[ ${f} =~ \.(php|ctp)$ ]]; then
    phpFilesCount=$((phpFilesCount + 1))
    phpFiles="$phpFiles $f"
  fi
done
if [[ ${phpFilesCount} == 0 ]]; then
  echo "No PHP files updated, nothing to check."
  exit 0
fi

echo "Checking files: $phpFiles"

./vendor/bin/phpcs ${args} ${phpFiles}
```

**Comment by Seldaek** [comment]
The way bash execution works, when your shell script does `./vendor/bin/phpcs ${args} ${phpFiles}` it will execute this relative to the current working directory you are in, not relative to the file. So I think this is fine..

The problem IMO is that your script is not executable and thus you see this permission error. Previously we would make sure the symlink was executable which would fix the permission on your file I believe.

Try running this in project-b's git repo please and see what happens :

```
git update-index --chmod=+x bin/phpcs.sh
git status
```

If this shows the file modified then that should be your fix, commit the change and that's it.

**Comment by thefrosty** [comment]
Closing this out, and I was previously sourcing the our shell script, but since the file is now proxied, we just needed to call it direct without `source`.

**Comment by Seldaek** [comment]
Ah I see, sourcing support was added in https://github.com/composer/composer/commit/6dea58c9f39a1af3dbee8d014cf042aaf5661d25 yesterday - that may help your use case too. https://github.com/composer/composer/releases/tag/2.2.4 is out now with the fix.
