### ISSUE TITLE
WSL W11 PHP8.1 : A connection timeout was encountered

### ISSUE THREAD

**Issue by julienallexandre** [composer/composer#10445]
My `composer.json`:

```json
{
    "type": "project",
    "license": "proprietary",
    "minimum-stability": "stable",
    "prefer-stable": true,
    "require": {
        "php": "^8.1",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "composer/package-versions-deprecated": "1.11.99.4",
        "doctrine/annotations": "^1.0",
        "doctrine/doctrine-bundle": "^2.5",
        "doctrine/doctrine-migrations-bundle": "^3.2",
        "doctrine/orm": "^2.10",
        "phpdocumentor/reflection-docblock": "^5.3",
        "phpstan/phpdoc-parser": "^1.2",
        "sensio/framework-extra-bundle": "^6.1",
        "symfony/asset": "6.0.*",
        "symfony/console": "6.0.*",
        "symfony/dotenv": "6.0.*",
        "symfony/expression-language": "6.0.*",
        "symfony/flex": "^2",
        "symfony/form": "6.0.*",
        "symfony/framework-bundle": "6.0.*",
        "symfony/http-client": "6.0.*",
        "symfony/intl": "6.0.*",
        "symfony/mailer": "6.0.*",
        "symfony/mime": "6.0.*",
        "symfony/monolog-bundle": "^3.1",
        "symfony/notifier": "6.0.*",
        "symfony/process": "6.0.*",
        "symfony/property-access": "6.0.*",
        "symfony/property-info": "6.0.*",
        "symfony/proxy-manager-bridge": "6.0.*",
        "symfony/runtime": "6.0.*",
        "symfony/security-bundle": "6.0.*",
        "symfony/serializer": "6.0.*",
        "symfony/string": "6.0.*",
        "symfony/translation": "6.0.*",
        "symfony/twig-bundle": "6.0.*",
        "symfony/validator": "6.0.*",
        "symfony/web-link": "6.0.*",
        "symfony/yaml": "6.0.*",
        "twig/extra-bundle": "^2.12|^3.0",
        "twig/twig": "^2.12|^3.0"
    },
    "require-dev": {
        "phpunit/phpunit": "^9.5",
        "symfony/browser-kit": "6.0.*",
        "symfony/css-selector": "6.0.*",
        "symfony/debug-bundle": "6.0.*",
        "symfony/maker-bundle": "^1.0",
        "symfony/phpunit-bridge": "^6.0",
        "symfony/stopwatch": "6.0.*",
        "symfony/web-profiler-bundle": "6.0.*"
    },
    "config": {
        "allow-plugins": {
            "composer/package-versions-deprecated": true,
            "symfony/flex": true,
            "symfony/runtime": true
        },
        "optimize-autoloader": true,
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php73": "*",
        "symfony/polyfill-php74": "*",
        "symfony/polyfill-php80": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "6.0.*"
        }
    }
}

```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
require.composer/package-versions-deprecated : exact version constraints (1.11.99.4) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: A connection timeout was encountered. If you intend to run Composer without connecting to the internet, run the command again prefixed with COMPOSER_DISABLE_NETWORK=1 to make Composer run in offline mode.
FAIL
[Composer\Downloader\TransportException] curl error 28 while downloading https://api.github.com/rate_limit: Resolving timed out after 10000 milliseconds
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: xxx
Dev Public Key Fingerprint: xxx
OK
Checking composer version: OK
Composer version: 2.2.3
PHP version: 8.1.1
PHP binary path: /usr/bin/php8.1
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
cURL version: 7.68.0 libz 1.2.11 ssl OpenSSL/1.1.1f
zip: extension present, unzip present, 7-Zip not available
```

When I run this command: 

```
composer update / composer install / composer require
```

I get the following output: 

```
A connection timeout was encountered. If you intend to run Composer without connecting to the internet, run the command again prefixed with COMPOSER_DISABLE_NETWORK=1 to make Composer run in offline mode.
```

**Comment by Seldaek** [comment]
Looks like DNS resolution fails for you.. Can you run `ping api.github.com` from WSL at all? Is this a PHP/curl issue or is your whole WSL distro broken?

**Comment by julienallexandre** [comment]
it pings well

```
PING api.github.com (140.82.121.5) 56(84) bytes of data.
64 bytes from lb-140-82-121-5-fra.github.com (140.82.121.5): icmp_seq=1 ttl=51 time=23.1 ms
64 bytes from lb-140-82-121-5-fra.github.com (140.82.121.5): icmp_seq=2 ttl=51 time=22.9 ms
^C
--- api.github.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 22.930/22.991/23.053/0.061 ms
```

**Comment by Seldaek** [comment]
Then try curl on command line, or file get contents with php then curl with php with some basic test script to see where it starts breaking? If all of that works then maybe it's really a problem in composer but I can't imagine what

**Comment by julienallexandre** [comment]
I did a `curl -vvv https://packagist.org/packages.json` and it works well

**Comment by julienallexandre** [comment]
I have deleted and recreated 0 wsl and still the same problem

**Comment by julienallexandre** [comment]
I can't work on any project anymore, I don't know what to do... I am on `Windows 11 21H2 22000.376 with WSL Ubuntu 20.04.3 LTS then Composer 2.2.4 with PHP 8.1.1`, I have the connection well I can ping everything the only tool that does not work is composer (require, install, update..)

**Comment by Seldaek** [comment]
You can try to run it with the curl extension disabled to see if the fallback to file get contents works? It'll be slower but that may be better than nothing.. Or try to install another php version perhaps? Sorry I don't see what it could be just trying random ideas here

**Comment by Seldaek** [comment]
Other things to consider: Did it use to work? If yes what changed?

**Comment by julienallexandre** [comment]
I tested with version 8.1 and 7.4 I have the same problem on the 2 I use the repo ppa:ondrej/php before it works well but at the beginning of the last update there is the problem how can I remonter him? And I have the impression that it comes from the curl extension of php because when I apt remove php curl and that I launch the commands it seems to work on the other hand effectively it is very long because a composer install lasts 35 minutes, but how to use curl in my code?

**Comment by Seldaek** [comment]
You can report issues at https://github.com/oerdnj/deb.sury.org/issues for his ppa, not sure what else to do here sorry.

**Comment by julienallexandre** [comment]
I'm sorry to have made you lose time. But I found the source of the problem and I'm very annoyed that it took me 3 days to find it. I explain myself I have 2 pc windows 11 and on both I use wsl but I have bitdefender and malwaresbytes installed, I had deactivated them but nothing changed and after a long reflection I decided to reinstall one of the 2 and bingo it works. I did some step by step: 1) malwaresbytes no problem 2) bitdefender PROBLEM! and yes this bitdefender must have done a crappy update on windows 11 that causes me this problem but I can't find it and in the end it's their shitty firewall that needs to be deactivated so I can keep the antivirus but not the firewall I even tested that [https://community.bitdefender.com/en/discussion/82809/bitdefender-firewall-wont-allow-wsl-traffic](https://community.bitdefender.com/en/discussion/82809/bitdefender-firewall-wont-allow-wsl-traffic) but it didn't change anything because I had the connection in short, all that to thank you for taking the time to answer me, next time I won't be looking for 3 days I'll be thinking about this shitty firewall, in short, a happy new year to you and once again, thank you

**Comment by Seldaek** [comment]
OK good to know it's resolved. Another one for crappy antivirus/firewall software :/

**Comment by Suba-IC** [comment]
I am also receiving such error and I have not installed Bitdefender too. I tried disabling Firewall still the issue exist.

**Comment by tomasfejfar** [comment]
I noticed that it seems to be an issue with slow DNS resolving with WSL+docker, rather than not resolving at all. What worked for me was to plainly curl $url, which takes a long time in the container, but finishes successfully. After that it's no longer resolved and composer works. 🤷 So the issue seems to be that the DNS resolution timeout in composer is too low for this super slow resolver :(

**Comment by Abou-fatima** [comment]
Moi c'est mon problème quand j'installe un projet laravel 

A connection timeout was encountered. If you intend to run composer without connecting to the internet, run the command again prefixed with COMPOSER_DISABLE_NETWORK=1 to make composer run in offline mode HTTPS://repo.packagist.org could not be fully loaded (curl error 28 while downloading HTTPS://repo.packagist.org/packagé.json: Resolving timed out After 10027 millisecondes ), package information was loaded from thé local cache and may be out if date
