### ISSUE TITLE
Not composer issue but - integration composer.json & storeschema.org no json schema published

### ISSUE THREAD

**Issue by error-500** [composer/composer#10448]
## JSON schema for IDE

[https://www.schemastore.org/json/](https://www.schemastore.org/json/) - [404 not found](https://json.schemastore.org/composer)

That is not issue but i thik very important for automation processes and developers. I'm will try to make [contributing](https://github.com/SchemaStore/schemastore/blob/master/CONTRIBUTING.md) but i think if you do by your self - it will more usefull for actualize state

## Not `composer.json`:

```json
--- not composer issue ---
```

Output of `composer diagnose`:

```
--- not composer output yet
```

When I run this command: create composer json from scratch in VSCode

```
--- not composer output ---
VScode.output

Package

Problems loading reference 'http://json.schemastore.org/composer': Unable to load schema from 'http://json.schemastore.org/composer': Not Found. The requested location could not be found.
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.(768)
```

I get the following output: 

```
...replace me...
```

And I expected this to happen:
I m think you need contribute composer schema by your self .

**Comment by stof** [comment]
I suspect that this is related to https://github.com/SchemaStore/schemastore/pull/1618

To me, that's a SchemaStore issue if they haven't setup the appropriate redirection. There is nothing to change in composer IMO

**Comment by stof** [comment]
or maybe it's a VSCode issue if they use an outdated schemastore catalog
