### ISSUE TITLE
[RuntimeException] git was not found in your PATH, skipping source download

### ISSUE THREAD

**Issue by webprogrammierer** [composer/composer#10450]
One bad hoster has no git installed.

After
`php composer.phar install`

I get this error message:

```
  [RuntimeException]
  git was not found in your PATH, skipping source download
```

How can I still install my Drupal project using composer directly on the webhosting server per ssh?
Thank you.

**Comment by Seldaek** [comment]
You can install it locally or somewhere with git, then rsync/ftp the files up to your webhosting including the vendor dir.

Or you can use --prefer-dist to force dist installs, but in some rare cases packages may be only installable via git, in which case if you have no git there's nothing Composer can do for you.

**Comment by cmlagatuz** [comment]
You didn't even answer his question.
