### ISSUE TITLE
"abandoned" value in composer.lock doesn't update after first set

### ISSUE THREAD

**Issue by GPHemsley-RELX** [composer/composer#10452]
My project based on Symfony 4.4 has an indirect dependency on "symfony/inflector".

At some point, this package was marked as abandoned (I presume this happens directly on packagist.org?) with the message "use `EnglishInflector` from the String component instead". However, this causes composer to output the message "Use use `EnglishInflector` from the String component instead instead."

Somewhere along the way, the abandonment message was updated to the more correct value "EnglishInflector from the String component", which allows the composer warning to display correctly.

However, when `composer update` is run, composer.lock does not get updated with the new abandoned value. Instead, it is frozen at its original value.

Manually removing the entry from composer.lock will allow `composer update` to retrieve and populate the current version.

**Comment by Seldaek** [comment]
Can you share a lock file and composer.json that allow to reproduce this?

**Comment by Seldaek** [comment]
I cannot reproduce this, I tried editing the abandoned message in lock file and when running an update of that package it gets updated back to the original.
