### ISSUE TITLE
How to require packages from local path repo

### ISSUE THREAD

**Issue by gilbertsoft** [composer/composer#10460]
My `composer.json`:

```json
	"require": {
		"vendor/package": "@dev"
	},
	"repositories": [
		{
			"type": "path",
			"url": "../.."
		}
	],
```

When I run this command:

```
composer validate
```

I get the following output: 

```
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
# General warnings
- require.vendor/package : unbound version constraints (@dev) should be avoided
```

In the TYPO3 community we recommend since years to use `@dev` for packages from a path repository (see https://docs.typo3.org/m/typo3/guide-installation/main/en-us/MigrateToComposer/BestPractices.html#include-your-individual-extensions-from-packages-folder). Now I'm wondering is our recommendation wrong or should the validation be relaxed for this case or is there another possibility which we did not see so far to avoid this warning. I've tested this scenario with Composer 1.10.x, 2.0.x, 2.1.x and 2.2.x, so it looks this behavior didn't change which was my first thought.

I did also some tests by defining `options.versions` of the repository which avoids the warning but does not look very clean to me:

```
	"require": {
		"vendor/package": "0.1-dev"
	},
	"repositories": [
		{
			"type": "path",
			"url": "../..",
			"options": {
				"versions": {
					"vendor/package": "0.1-dev"
				}
			}
		}
	],
```

Thanks for any hints on how to correctly require packages from a local path repository.

**Comment by Seldaek** [comment]
What I usually do is pin the version in the path repo to "1.0.0" if it's a sub-package inside a monorepo at least.

Anyway the validate warning is just a warning, and it is correct that such a constraint is very vague, and if the path repo were to go away it would start installing this package in any random version which would not be good.

So I'd say it works as intended.

**Comment by gilbertsoft** [comment]
So I've tested various scenarios and it looks this is the best solution to recommend if somebody cares for these warnings or uses strict validation:

```
	"require": {
		"vendor/package": "^1.0"
	},
	"repositories": [
		{
			"type": "path",
			"url": "./packages/*",
			"options": {
				"versions": {
					"vendor/package": "1.0.0"
				}
			}
		}
	],
```

Setting the version directly in the sub packages leads to a validation warning in the sub packages afterwards and therefor is a not a solution.
