### ISSUE TITLE
Force update repositories and drop local changes

### ISSUE THREAD

**Issue by fprochazka** [composer/composer#1047]
It would be nice to have a <code>--force</code> option to <code>update</code> command. 

Before the actual update, it would look at all the installed repositories, that are installed from source, for each one output verbose changeslist (just like <code>composer status -v</code>) and promt me for dropping those changes.

I love how it saves me from deleting my work accidentally, but sometimes I wanna do exactly that. Becase I was just trying something out, and finding the exact directory and running <code>git reset composer && git checkout . && git clean</code> is annoying.

This doesn't even have to be an option. It can be a command <code>$ composer clean</code> it would just cleanup my mess :)

**Comment by michallohnisky** [comment]
For those who found this on Google:

Use https://getcomposer.org/doc/06-config.md#discard-changes .
