### ISSUE TITLE
InstalledVersions::getAllRawData() / installed.php yields insufficient meta information about replaced packages

### ISSUE THREAD

**Issue by aedart** [composer/composer#10478]
When attempting to gain package version information for a package that has been replaced, the meta information that is given via `InstalledVersions::getAllRawData()` is not enough to understand what other package has replaced it.

### Context

I am working on upgrading several packages in [Athenaeum project](https://github.com/aedart/athenaeum/tree/6.x), a mono-repository. All packages that are offered are listed inside the root `composer.json`, via the `replace`section. The `replace` section is automatically generated via [Monorepo Builder](https://github.com/symplify/monorepo-builder) - a tool that I use.
E.g.:

```json
{
    "replace": {
        "aedart/athenaeum-acl": "self.version",
        "aedart/athenaeum-audit": "self.version",
        "aedart/athenaeum-circuits": "self.version",
        "aedart/athenaeum-collections": "self.version",
    }
}
``` 
(_Entire `composer.json` is not shown in the above example._)

Finally, I use [jean85/pretty-package-versions](https://github.com/Jean85/pretty-package-versions) to obtain version information, about installed packages. Behind the scene, `\Composer\InstalledVersions::getAllRawData()` delivers the core meta information about packages. Sadly, it appears no longer possible to obtain correct package version information about packages, that have been replaced (_e.g. by the root level package_). This causes some of my CI tests to fail.

### The problem

The generated `vendor/composer/installed.php` file does not contain enough meta information about what other package(s) have replaced a target package. E.g. if I attempt to get the version of `aedart/athenaeum-acl`, the available data inside the `installed.php`, is as follows:

```php
// Inside vendor/composer/installed.php
<?php return array(
    'versions' => array(
        'aedart/athenaeum-acl' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '6.x-dev',
            ),
        ),
    // ... remaining not shown
];
```

The end result: `null` is returned when calling `\Composer\InstalledVersions::getVersion('aedart/athenaeum-support')`. _This may be fine, expected and intended behaviour of the `getVersion()` method_. But, it does not seem possible to figure out what package(s) are replacing the targeted package. The only data available is `0 => '6.x-dev'`, which is not safe enough to compare against other installed packages.

### Possible Solution

The meta information about what package(s) have replaced a targeted package could be expanded. It could contain a little more information about what packages are replacing it, along with a bit more information
Consider the following data structure:

```php
// Inside vendor/composer/installed.php
<?php return array(
    'versions' => array(
        'aedart/athenaeum-acl' => array(
            'dev_requirement' => false,
            'replaced' => array(
                'aedart/athenaeum' => array(
                    'pretty_version' => '6.x-dev',
                    'reference' => '7ffc80ae7b894450a7ccc647c355fc5a1da114cd'
                ),
                // ... other packages that replace target... ?
            ),
        ),
    // ... remaining not shown
];
```

The package _name_ and _reference hash_ are perhaps the most important. From there, it will be possible to query the data structure for additional version information.

### Alternative Solution

If the previous proposed solution is considered breaking or in any other way unfitting, then perhaps the following data structure could work sufficiently enough, without the risk of breaking backwards compatibility.

```php
// Inside vendor/composer/installed.php
<?php return array(
    'versions' => array(
        'aedart/athenaeum-acl' => array(
            'dev_requirement' => false,
            'replaced' => array(
                'aedart/athenaeum' => '6.x-dev',
                // ... other packages that replace target... ?
            ),
        ),
    // ... remaining not shown
];
```

### Onward

I kindly ask the appropriate maintainers to help resolve this matter, as soon as possible. Please do not ask a PR from me, as I lack sufficient time and deep knowledge about composer's architecture (_I simply do not know where to begin, nor how to change generated code, without risking breaking other functionality..._).

**Comment by aedart** [comment]
Another possible issue that I discovered, whilst reviewing the code.
When checking if a package is installed, e.g. `\Composer\InstalledVersions::isInstalled('aedart/athenaeum-support')`, `true` is returned. Yet, as previously mentioned, `null` is returned when attempting to get version information about the package.
Is this the intended behaviour?

**Comment by Seldaek** [comment]
The problem is the version of foo replacing bar does not give you any information about anything. The information is provided by the version range that foo replaces bar in. But that's a version range, so returning it as part of getVersion would be completely wrong.

For this reason, the way to do what you are trying to do here IMO is to use `satisfies` as per https://getcomposer.org/doc/07-runtime.md#knowing-whether-package-x-is-installed-in-version-y 

The will compare the version (or version range) you are interested in with the version (if package A installed) or version range (if package A is replaced by B), and return true if that's a match.

If that does not work for any reason, then you need to explain why, but I can already tell you with 90% certainty that we will not modify this API.

Alternatively if you really want to know what package replaces another one (which IMO is from a dependency management perspective nonsensical, but in the context of your monorepo may make sense for whatever reason), you can load vendor/composer/installed.json and read the complete info from there.

**Comment by aedart** [comment]
@Seldaek Thanks for your reply.

Normally, this shouldn't be a problem at all. The use-case for all of my packages is that you only require what you need and not the entire root package (_aka. the mono-repo_). Thus I expect obtaining a version isn't a problem then.
However, it's only when I'm situated in the context of the root package, e.g. during development, that this somehow becomes a problem for me. `vendor/composer/installed.json` sadly does not contain any of the sub-packages, when situated in the root package.

The [3rd party package](https://github.com/Jean85/pretty-package-versions) that I use for obtaining versions started throwing an exception, each time I requested a package's version that is replaced. Unfortunately, that exception is not able to tell any more information about which package is was replaced by - ... which is why I hoped for some additional meta information inside `installed.php`, because then I could handle it from there. E.g. If the exception or your `installed.php` would contain the requested information about what installed package and version replaces the requested package.

You proposed solution might work. But, it does feel very "hacky". How would you go about this, if your root package context was `laravel/framework` or perhaps `symfony/symfony`? Would your manually check against their root package, each time you request version of one of their sub-packages?
(_In this context, you might actually require their entire frameworks and only ask for the version of a single sub package_).

**Comment by Seldaek** [comment]
I think you need to try and describe your exact use case in more details, because none of this makes sense to me so far. But you're just asking for a solution instead of explaining the goal you're trying to achieve. 

The way I see it you should never care what exact version something is installed in, you only need to know if it's within a given version range if you have some conditional code paths, and for that the InstalledVersions::satisfies is perfectly fine and works with replaces. getVersion IMO should not even exist, the only valid use case for it is for a package to render/output its exact version, as it knows if the code runs it isn't being replaced.

**Comment by aedart** [comment]
I apologise if this is getting inconvenient.

My goal: obtain a pretty version for a sub-package, so that it can be displayed in a CLI application.
This seems not possible, if the package is listed as a "replaced".

I do not need the version for range checks, special code conditions, nor matching of any kind. Just to display any installed package's version, programmatically.

**Comment by Seldaek** [comment]
Then it sounds to me like this should do what you want, e.g. to display the version of `aedart/athenaeum-acl` do:

```php
$version = InstalledVersions::getPrettyVersion('aedart/athenaeum-acl') ?? InstalledVersions::getPrettyVersion('aedart/athenaeum');
```

**Comment by aedart** [comment]
Yes, if it only was for my own packages. But I'm trying to automate that kind of process. To do so, I need more information about what packages are replacing the targeted package:

```php
if (InstalledVersions::isInstalled('xxxx/package-a') && InstalledVersions::getPrettyVersion('xxxx/package-a') !== null) {
    return InstalledVersions::getPrettyVersion('xxxx/package-a');
} else if (InstalledVersions::isInstalled('xxxx/package-a') && /* has replacements...? */) {
    // obtain replacements... if there is only 1 and its installed, return the replacement package's version.
    // if there more replacements... do something else, e.g. throw an exception...
} else {
    // target package is not installed
    return null;
}
```

I could achieve something like the above example, if I knew how to obtain a list of replacements for package `'xxxx/package-a'` (_that are installed of course_).

I'm not trying to change any of your code inside `InstalledVersions`, because I understand that you risk breaking backwards compatibility. I'm just trying to get a little more meta information, so that I myself can deal. If anything, perhaps you might be tempted to add a new method, e.g. `InstalledVersions::replacements(string $package): array` which could return a list of replacements for the target package. If not, then adding a bit more meta information inside `vendor/composer/installed.php` can also do the trick for me.

**Comment by Seldaek** [comment]
The information is available in installed.json if you look for a package with a replace for the package which is replaced. Replace acts as a conflict so there can only be one package replacing something at a time. Provide however can happen in parallel, which highlights the futility of what you are trying to do IMO. It's just impossible to get a single version number for a package if it is provided by another. And even if it replaced package A 1.0.0 can replace package B 5.0.0 so showing A's version when B is replaced by it is entirely meaningless.

Sorry but I'm done here.. I don't know how else to explain it anymore.

**Comment by aedart** [comment]
Thanks
