### ISSUE TITLE
Proxy file generation leads to strange behavior in execution of bin script

### ISSUE THREAD

**Issue by Ahummeling** [composer/composer#10471]
I am running into an issue with the generated proxy files from composer. It seems to occur in a situation rather difficult to describe, so I set up a minimal reproducer for my case. 
The short of it is this. When I have a package that lists a symlink to a .phar file (specifically, phpunit.phar for some reason), the `include <path to symlink>;` statement at the final line of the generated composer file seems to simply quit half way through reading, closing the program gracefully and leaving no hints as to what's going on. If I replace the `include` statement with a `echo shell_exec(<path to symlink>);` I get the normal behavior of the program executing.

The reproducer includes a ci script that outputs the composer.json, composer diagnose, the commands that are run to reproduce the error and the output (or lack thereof). The expected behavior is shown for the 2.1.12 execution, and the breaking behavior is shown for the 2.2.0 and the 2.2.4 test.

[Reproducer link](https://gitlab.com/arend-public/composer-reproducer/-/pipelines/451463136/builds)
[PHPUnit wrapper](https://gitlab.com/arend-public/phpunit-wrapper) This is the package I install to reproduce the error, this repository is also a reproducer meant to help demonstrate the issue.

Please let me know if there's anything I can do to provide more information. I am dying to find out and understand how this is possible and what is going on here. 

My `composer.json`:

```json
{
    "name": "arend/composer-proxy",
    "description": "reproducing a bug i found",
    "type": "library",
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Test\\": "tests/"
        }
    },
    "repositories": {
        "14276532": {
            "type": "composer",
            "url": "https://gitlab.com/api/v4/group/14276532/-/packages/composer/"
        }
    },
    "authors": [
        {
            "name": "Arend Hummeling",
            "email": "arend@adivare.nl"
        }
    ],
    "minimum-stability": "stable",
    "require-dev": {
        "arend-public/phpunit-wrapper": "^1.0"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.2.4
PHP version: 8.0.14
PHP binary path: /usr/local/bin/php
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
cURL version: 7.64.0 libz 1.2.11 ssl OpenSSL/1.1.1d
zip: extension present, unzip present, 7-Zip not available
```

When I run this command: 

```
vendor/bin/phpunit
```

I get the following output: (I am not getting any output)

```
```

And I expected this to happen: (I am getting output):
```
PHPUnit 9.5.11 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.0.14
Configuration: /builds/arend-public/composer-reproducer/phpunit.xml
.                                                                   1 / 1 (100%)
Time: 00:00.003, Memory: 20.00 MB
OK (1 test, 1 assertion)
```

**Comment by johnstevenson** [comment]
PHPUnit phars include the following code:

```php
if (__FILE__ === realpath($_SERVER['SCRIPT_NAME'])) {
    $execute = true;
} else {
    $execute = false;
}

...

if ($execute) {
    if (isset($printManifest)) {
        print file_get_contents(__PHPUNIT_PHAR_ROOT__ . '/manifest.txt');

        exit;
    }

    unset($execute);

    PHPUnit\TextUI\Command::main();
}
```
which means that stuff will only run if the phar has been called directly, and not if it has been included (as is the case when the proxy script is used).

**Comment by Ahummeling** [comment]
That explains everything! 
Thank you for clarifying this. 

I do wonder if this is an intended consequence of changing from symlinks in the bin folder to generating scripts with include statements?
And I'm wondering if I'm the only person encountering this, or if there are perhaps more people as mystified as I am.

**Comment by Ahummeling** [comment]
Should anyone else run into this issue, I've implemented to following solution. 
I replaced the symlink pointing to `phpunit.phar` with an actual php script with the following contents:
```php
#!/usr/bin/env php
<?php
declare(strict_types=1);
$args = $argv ?? [];
$args[0] = __FILE__.'.phar';
$descriptors = [STDIN, STDOUT, STDERR];
$pipes = [];
$proc = proc_open($args, $descriptors, $pipes, getcwd(), null);
if (false === $proc) {
    echo "Failed to start phpunit\n";
    exit(1);
}
do {
    $status = proc_get_status($proc);
    usleep(100);
} while ($status['running']);
proc_close($proc);
exit($status['exitcode']);
```
maybe a little dirty/low-level, but it gets the job done

**Comment by johnstevenson** [comment]
You could alternatively use `symfony/phpunit-bridge`, which downloads the latest phpunit version and runs it (although I don't know what your use case is).

**Comment by Seldaek** [comment]
Right, this does not seem fixable on our end.. but I did open https://github.com/sebastianbergmann/phpunit/pull/4870 which if accepted would I believe make the phar usable again in this context.
