### ISSUE TITLE
Have a way to force a dependency to be dist files and avoid cloning

### ISSUE THREAD

**Issue by jacquesbh** [composer/composer#10491]
As specified here https://github.com/phpstan/phpstan/issues/6413 we have a long long long clone happening with phpstan.
The objects weight is more than 2Go.

Is there a way, or could it be a way, to specify that a specific package MUST NOT be cloned and always be dist files? Even with `--prefer-source` in the command line I mean.

Thank you!

_Big love to all contributors <3_

**Comment by stof** [comment]
in your configuration, you can configure the preferred install mode for specific packages: https://getcomposer.org/doc/06-config.md#preferred-install

**Comment by Seldaek** [comment]
Yes but if you do --prefer-source it will override the config. There is no way around that sorry :) 

If you need to install some packages from source best do it via config, and if you do only need to do that within a CI/build script then best to first call `composer config preferred-install.foo/bar source` before your install.

**Comment by jacquesbh** [comment]
Thank you to both of you!

That's what I was searching for, didn't find it.

❤️
