### ISSUE TITLE
Should plugins run on reinstall ?

### ISSUE THREAD

**Issue by jrfnl** [composer/composer#10508]
This is more a question for which I couldn't find if this had been discussed before.

Code to reproduce can be found here: https://github.com/jrfnl/composer-install-action-bug/tree/testing/composer-reinstall
Test run output: https://github.com/jrfnl/composer-install-action-bug/actions/runs/1790724084

My `composer.json`:

```json
{
    "name": "jrfnl/composer-reinstall",
    "description": "Testing",
    "license": "MIT",
    "require-dev": {
        "php": ">=5.4",
        "phpcsstandards/phpcsextra": "^1.0.0"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "allow-plugins": {
            "dealerdirect/phpcodesniffer-composer-installer": true
        }
    }
}
```

When I run this command: 
```
composer reinstall phpcsstandards/phpcsextra
```

I get the following output: 

```
Run composer reinstall phpcsstandards/phpcsextra -v
  - Removing phpcsstandards/phpcsextra (1.0.0-alpha3)
  - Installing phpcsstandards/phpcsextra (1.0.0-alpha3): Extracting archive
```

And I expected this to happen:

That the Dealerdirect PHPCS Composer plugin, which is installed as as part of the package would run, but it didn't.

Plugin also doesn't run when installed as a root requirement.

As there is no separate "reinstall" event, I would expect `post-install` events to run on reinstall as well.

**Comment by jrfnl** [comment]
Just thinking - a better example of why I'm asking the question would have been running `composer reinstall squizlabs/php_codesniffer` as that would wipe out whatever the PHPCS Composer plugin has set up previously in the `CodeSniffer.conf` file which is stored in that directory.
With the plugin not being triggered to (re-)run on a `compose reinstall`, that would effectively _unregister_ from PHPCS all previously registered standards.

**Comment by Seldaek** [comment]
Hmm I guess we should fire pre-install-cmd/post-install-cmd events around the removal/install. It should already fire pre-package-install/etc events as it happens.

**Comment by jrfnl** [comment]
> Hmm I guess we should fire pre-install-cmd/post-install-cmd events around the removal/install. It should already fire pre-package-install/etc events as it happens.

That would make sense to me.

**Comment by jrfnl** [comment]
Thanks for fixing this @Seldaek !
