### ISSUE TITLE
Show --outdated --direct --PATCH-ONLY

### ISSUE THREAD

**Issue by ScreamingDev** [composer/composer#10503]
My `composer.json`:

```json
{
  "require": { "composer/composer": "1.2.3" }
}
```

When I run this command: 

```
composer show --outdated --direct --minor-only
```

I get the following output: 

(It surely shows that composer 1.10.x or higher is available)

And I expected this to happen:

A new command `composer show --outdated --PATCH-only` (similar for `composer outdated`) would be great for maintenance.
The above would then show that Composer 1.2.4 is avaiable.

Reasons/restrictions exists that a developer want or can only update the patch version of packages. Unfortunately `composer outdated` can not be used to track for new patches, because it does not offer a "--patch-only" option similar to the "--minor-only" option.

**Comment by Seldaek** [comment]
This should be reasonably easy to add by copying what's done for --minor-only, except it should use `~` instead of `^` for the internal constraint. If someone wants to have a try at an implementation.

**Comment by SvyatoslavTregubov** [comment]
May I take it?

**Comment by Seldaek** [comment]
Please :)
