### ISSUE TITLE
Docs on files autoloading should document the order files are included

### ISSUE THREAD

**Issue by joachim-n** [composer/composer#10509]
Looking at the code, it looks like autoload files are loaded in the order of packages given by PackageSorter::sortPackages().

This should be documented in https://getcomposer.org/doc/04-schema.md#files. (Also, I have no idea what the sorting done by PackageSorter::sortPackages() actually is. It says 'dependency weight' but what does that mean?)

**Comment by Seldaek** [comment]
It means if A requires B, B is loaded first, to ensure it is fully available when A is loaded. The project's files are thus loaded last, and if the project must load things before dependencies it should include them before including `vendor/autoload.php`.

**Comment by joachim-n** [comment]
Thanks for the explanation!

If two packages are both dependencies but unrelated, is there a deterministic order for their autoload files?

E.g. if you have:

```
- project/root
-- requires package/foo - includes foo.php
-- requires package/bar - includes bar.php
```

**Comment by Seldaek** [comment]
I'd have to try to make sure. I would say it takes the order they appear in the root composer.json but that may be very outdated knowledge tbh, so I'd not trust myself with this statement :)
