### ISSUE TITLE
`composer show` requires `--no-interaction` if it checks for plugin allowance

### ISSUE THREAD

**Issue by rdohms** [composer/composer#10518]
Currently, it's impossible to run `composer show --ignore-platform-reqs -D -l` on a repository that does not yet have the `allow-plugins` configuration in place, without interacting with the CLI and allowing plugins.

This is odd since the `show` command does not `install` anything per see, so why is it asking if I trust the plugins (that are already installed at this point.)

I think the best fix is to ignore this check in this case.

But failing that, we need to add `--no-interaction support for the `show` command. Not sure how many implications this has.

**Comment by Seldaek** [comment]
Plugins can react to the command event to do any sort of thing, so they could react to the show command being run somehow. So yes we do need to enable plugins when running the show command, and we do need to prompt if the plugins haven't been added to the config yet. 

Either add them to the config or run with -n if you are in a non-interactive context then plugins will be loaded for now, and from July 2022 they will be ignored.

I don't quite understand why you say: 

> But failing that, we need to add --no-interaction support for the show` command

`-n` / `--no-interaction` is supported by all commands (it's a built-in feature of symfony/console so it's supported by all symfony/console-built CLI apps really). What's missing?

**Comment by rdohms** [comment]
It was a combination of factors it seems.

One on end I typo'd `interaction`, shame on me... on the other, the error message offered up:

```
show [--all] [--locked] [-i|--installed] [-p|--platform] [-a|--available] [-s|--self] [-N|--name-only] [-P|--path] [-t|--tree] [-l|--latest] [-o|--outdated] [--ignore IGNORE] [-m|--minor-only] [-D|--direct] [--strict] [-f|--format FORMAT] [--no-dev] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<package>] [<version>]
```
which does not mention it being supported.

**Comment by Seldaek** [comment]
Oh right, that's also part of symfony/console, maybe report it there as a bug, I'd guess default input options should also be included in the error output suggesting available options.
