### ISSUE TITLE
 preg_match() error

### ISSUE THREAD

**Issue by majidashraf81** [composer/composer#10513]
I'm installing new laravel and i'm getting this error

Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, array given in phar:///usr/local/Cellar/composer/2.2.5/bin/composer/vendor/composer/pcre/src/Preg.php:32
Stack trace:

**Comment by majidashraf81** [comment]
@composer

**Comment by Seldaek** [comment]
We need the stack trace otherwise we cannot do anything here. Plus a way to reproduce this if possible. And your PHP version

**Comment by Seldaek** [comment]
Closing as it's unactionable until we get more information
