### ISSUE TITLE
Sort packages in config/allow-plugins if config/sort-packages is true

### ISSUE THREAD

**Issue by Sweetchuck** [composer/composer#10519]
My `composer.json`:

```json
{
    "config": {
        "allow-plugins": {},
        "sort-packages": true
    }
}
```

The `#/config/sort-packages` configuration option has affect over the `#/packages` and `#/packages-dev` entries, but I think it would be useful to sort the package names under the `#/config/allow-plugins` as well.

**Comment by Seldaek** [comment]
There's really no easy way to implement this so I'm gonna have to close as won't fix as it's also not a super valuable improvement. The list of plugins is hopefully not getting that long that orders matters.
