### ISSUE TITLE
Binary file is not created

### ISSUE THREAD

**Issue by pardovimes** [composer/composer#10526]
Hi,

**I did a little project that I want to be able to use it as a vendor *with a binary file.***

When I do the composer require creates the vendor/project folder **but i don't get the binary file created on the vendor/bin folder**

Why is this happening? I think I'm using the bin option correctly.

this is the project and **my composer.json https://github.com/pardovimes/serra/blob/master/composer.json**

**Comment by Seldaek** [comment]
Maybe it's because your 1.0.0 tag contained no information at all? Or are you requiring dev-master? In the master branch it all looks correct to me yes.

**Comment by pardovimes** [comment]
Hi,

1.0.0 tag was for the first commit but when I used composer it downloaded all the code.

Anyway I made a 1.0.1 tag and it does the same. the folder is created but the link is missing for the binary

i'm doing this:

```
composer revoke pardovimes/serra
composer clear-cache
composer require pardovimes/serra --dev
```

Thanks
