### ISSUE TITLE
Wrong vendor subdirectories permissions when using 7z fallback

### ISSUE THREAD

**Issue by fliespl** [composer/composer#10535]
When running `composer install` with missing `unzip` command all directories extracted from zip have permissions set to 0700. That's because 7z doesn't take umask into consideration (requires clean composer without cache & downloaded files). That makes files unreadable for example for php user.

```
$ 7z
7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21

$ umask
0002
```

**Without unzip:**

```
$ stat vendor/twig/twig/
  File: vendor/twig/twig/
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 810h/2064d      Inode: 1240808     Links: 6
Access: (**0700/drwx------**)  Uid: ( 1000/   flies)   Gid: ( 1000/   flies)

$ stat vendor/symfony/symfony/
  File: vendor/symfony/symfony/
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 810h/2064d      Inode: 1348337     Links: 4
Access: (**0700/drwx------**)  Uid: ( 1000/   flies)   Gid: ( 1000/   flies)
```

**With unzip:**

```
$ stat vendor/twig/twig/
  File: vendor/twig/twig/
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 810h/2064d      Inode: 1240620     Links: 6
Access: (**0775/drwxrwxr-x**)  Uid: ( 1000/   flies)   Gid: ( 1000/   flies)

$ stat vendor/symfony/symfony/
  File: vendor/symfony/symfony/
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 810h/2064d      Inode: 1348485     Links: 4
Access: (**0775/drwxrwxr-x**)  Uid: ( 1000/   flies)   Gid: ( 1000/   flies)
```

Probably fallback method should also chmod directories using selected umask.

**Comment by Seldaek** [comment]
Any chance you can try a newer 7zip? I wonder if it might have been fixed in the 6 years since your current release..

It is weird to me as well that it would set 0700 permissions, as this suggests a umask of 0077, it doesn't look like it's not applying the umask at all to me.

**Comment by fliespl** [comment]
@Seldaek I did that and with current one 21.07 (installed manually - cause it's not available in repositories) - it worked flawlessly.

Still, since newer version is not available in official repositories and i.e. Ubuntu 20.04 has EOL set for Apr 2030, maybe it's worth supporting that as well?

**Comment by Seldaek** [comment]
It seems like pre-21.01 7zip was just provided by the p7zip port, which I suppose is buggy.

Ubuntu 22.04 will come with 21.07 though so that's the good news, as long as you install it via 7zip and not p7zip https://packages.ubuntu.com/jammy/7zip

Our recommendation was always to install unzip on linux tho, so I am not sure how likely it is that people end up having problems like you did, and thus I am not super inclined to invest tons of time fixing this. It may be worth a version check to add a warning though if Composer does end up deciding to use `7z` to extract.

**Comment by fliespl** [comment]
That makes sense - thank you! :)

**Comment by Torxed** [comment]
> I am not sure how likely it is that people end up having problems like you did

I just want to say, speaking from experience today, it's likely ^^
\*shakes off hours of debugging*
Thanks for this thread!
