### ISSUE TITLE
[Question] Change order of loading classess

### ISSUE THREAD

**Issue by foremtehan** [composer/composer#10539]
I want to overwrite one of the laravel's helpers in my helper.php file, But the problem is composer loads the laravel file before my helper functions, I did a research and found this [topic in stackoverflaw](https://stackoverflow.com/questions/28474640/overwrite-laravel-5-helper-function) which created 7 years but did not the best solution, I want to If there is elegant to do this in composer ?

```
PHP Fatal error:  Cannot redeclare __() (previously declared in vendor\laravel\framework\src\Illuminate\Foundation\helpers.php:864) in app\Services\helpers.php on line 27
```

**Comment by Seldaek** [comment]
You can include your overrides before including vendor/autoload.php, or you can use something like https://github.com/funkjedi/composer-include-files and declare your overrides with a `files` autoload.
