### ISSUE TITLE
How to `composer install` using a package's composer.lock file

### ISSUE THREAD

**Issue by hbt** [composer/composer#10540]
If I have:

- a fresh project
- no composer.lock
- composer.json like the following 

```
{
    "name": "fresh",
    "type": "library",
    "require": {
        "consolidation/robo": "3.0.3"
    }
}
```

Then run `composer install`
It will install `consolidation/robo` and update the `consolidation/robo` internal dependencies instead of using the `consolidation/robo` internal `composer.lock` to get a known working version of the library. 

How do to get `composer install` to use `https://github.com/consolidation/robo/blob/3.0.3/composer.lock` when installing `consolidation/robo` dependencies instead of running the equivalent of `composer update` on `consolidation/robo`?

Currently, it's retrieving a broken internal dependency and I have to outline it in my root composer.json which internal dependency should be retrieved. Where as the `https://github.com/consolidation/robo/blob/3.0.3/composer.lock` has the working version of the library.

**Comment by Seldaek** [comment]
The lock file is only read from the root package, otherwise it would be impossible to reconcile dependencies when multiple packages depend on the same one and have it locked in different versions.
