### ISSUE TITLE
Feature Request: Support container registry as a source for packages.

### ISSUE THREAD

**Issue by davekok** [composer/composer#10556]
Currently composer supports multiple source types for where composer packages are pulled from. Among others its own package repository system, github, git, and more. These days installing git and a container registry for local (private) development are requirements all ready, and have many competitors. Since composer packages are kind of a nice. There is not much to choose from.

However since composer package are not unlike container images. It would be nice if composer could use container images as the source. Building a container image from scratch and just adding the PHP files would be sufficient for a composer container image I would assume.

Off course, container registry already have all the features like tagging and searching. So these could be used.

I hope a feature like this will simply local development. While retaining a good form of asset management outside git. And still using well supported systems with enough competitors.

**Comment by Seldaek** [comment]
Sorry but this sounds like an insane amount of work and complexity for a use case that I do not remotely see the value of. I am not saying it cannot be valuable to anyone, but it just isn't clear enough to me that this has broad appeal that justifies the work/maintenance.
