### ISSUE TITLE
DX: run mistyped composer script

### ISSUE THREAD

**Issue by staabm** [composer/composer#10559]
composer scripts are an easy way to hide complex commands, which you either run repetitively in daily business or in automation.

when mistyping the command I get nice hints like:
```
$ composer phpstan-baesline
  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "phpstan-baesline" is not defined.

  Did you mean this?
      phpstan-baseline
```

I am wondering whether composer should ask me interactively instead, so I can just answer with "yes" or "no" instead of retyping/copy-pasting the command in question

**Comment by Seldaek** [comment]
In main it already works as this is provided by modern symfony/console

![image](https://user-images.githubusercontent.com/183678/155117111-4f5c67f7-f3dd-448c-9f80-277f1b33c549.png)

Also note that you can use short-form commands so `phpstan` can be called by `p` or `ph` or whatever as long as it's unambiguous.

And you can use `:` to namespace things and be able to short-form that, e.g. if you make your script `phpstan:baseline` instead, you can use `composer p:b` to reach it quickly unambiguously.
