### ISSUE TITLE
Clean up phpdoc @return annotation which duplicate the real return type if they are not adding any description

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#10551]
Anyone has a clue how to automate this? 

Otherwise I guess I can do most of it with regex replacing, but if I can save some time please do tell.

**Comment by localheinz** [comment]
See https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.6.0/doc/rules/function_notation/phpdoc_to_return_type.rst!

**Comment by Seldaek** [comment]
What I'm looking for is rather to remove redundant `@return` and `@param` annotations if they exactly match the types in the code and do not contain a description (i.e. add no value at all)

**Comment by localheinz** [comment]
See https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.6.0/doc/rules/phpdoc/no_superfluous_phpdoc_tags.rst!

**Comment by Seldaek** [comment]
Ahh that's very nice, thanks :)
