### ISSUE TITLE
curl error 92 while downloading ... : HTTP/2 stream 213 was not closed cleanly: REFUSED_STREAM (err 7)

### ISSUE THREAD

**Issue by ametad** [composer/composer#10566]
Looks almost the same as: https://github.com/composer/composer/issues/10462

In this case the reported problem is: REFUSED_STREAM (err 7)

**Comment by Seldaek** [comment]
We already retry error code 92 (CURLE_HTTP2_STREAM). Composer [2.2.5](https://github.com/composer/composer/releases/tag/2.2.5) - are you sure you're using the latest version?

**Comment by ametad** [comment]
Hi @Seldaek 

Yes, I use:

<pre>$ composer -V
<font color="#4E9A06">Composer</font> version <font color="#C4A000">2.2.6</font> 2022-02-04 17:00:38</pre>

**Comment by ametad** [comment]
This was never an issue and when I use an older version (e.g. `2.0.14`) there is no problem.

**Comment by Seldaek** [comment]
And you can reproduce this consistently? Which URL is failing?

**Comment by ametad** [comment]
Yes, me and my colleague we can reproduce consistently.  I am going to try now from which version on will give the error.
The URL that is failing is of our own instance of Gitlab and I am reluctant to disclose the url... Perhaps via an e-mail?

**Comment by Seldaek** [comment]
No it's fine if it's a private URL I can't try it anyway so no need to share. But if you can figure out when the regression happened hopefully we can figure out from the diff what the issue is.

**Comment by ametad** [comment]
Thank you for your time @Seldaek , I think it is not a problem with Composer! My colleague and I both had also done an upgrade of our "environment", namely Laravels Homestead. And there something is also changed and must be the reason it is not working for us at the moment.

I have tried a dozen versions of Composer in the range of 2.0.x , 2.1.x and 2.2.x , all of them are failing inside of Homestead...! But are NOT failing on my host OS Linux. So therefore I think the conclusion is that the problem lies not here at Composer.

Perhaps when you have a look at both Composer diagnostics you would be so kind to let me kow if you see something interesting that could lead to an solution of the problem? That would be great.

## Diagnostics

### Working in Ubuntu 20.04

```
$ composer diagnose

(REDACTED)

Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (2.0.14 => 2.2.6)
Composer version: 2.0.14
PHP version: 7.4.19
PHP binary path: /usr/local/bin/php
OpenSSL version: OpenSSL 1.1.1k  25 Mar 2021
cURL version: 7.76.1 libz 1.2.11 ssl OpenSSL/1.1.1k
zip: extension present, unzip present
```

### NOT Working in Homestead v13.0.1

```
$ composer diagnose

(REDACTED)

Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (2.0.14 => 2.2.6)
Composer version: 2.0.14
PHP version: 7.4.27
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
cURL version: 7.58.0 libz 1.2.11 ssl OpenSSL/1.1.1g
zip: extension present, unzip present
```

**Comment by ametad** [comment]
Strange thing is, Composer is trying a URL that clearly does not exists:

> [Composer\Downloader\TransportException]                                                                                                                                                         
  curl error 92 while downloading https://gitlab.redacted.domain/api/v4/group/35/-/packages/composer/p2/laravel/framework~dev.json: HTTP/2 stream 207 was not closed cleanly: REFUSED_STREAM (err 7)

We host a few package on our Gitlab server. When you look at the URL above it looks like Composer is trying to get information about the Laravel framework on our Gitlab server. That is not right... Could this has to do with some regex going wrong?

**Comment by ametad** [comment]
Today I made some progress, the problem has perhaps to do with a global Composer plugin: slince/composer-registry-manager. This is standard included in Laravel Homestead. When I enable it, the curl error 92 pops up.

After composer self-update from 2.1.* to 2.2.7 I got this question when doing `composer update`:

```
slince/composer-registry-manager (installed globally) contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "slince/composer-registry-manager" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] y
```

I did answer "yes" and after that the curl error 92 is popping up and I got stuck.

**Comment by ametad** [comment]
I am lost right now finding a solution. Because the Homestead instance that once worked with Composer version 2.1.x does not work any more. I did :

* an update to Composer version 2.2.7 
* said "yes" to `Do you trust "slince/composer-registry-manager"`?
* Removed the answer in the global Composer config in `/home/vagrant/.config/composer/composer.json`
* did `composer global remove slince/composer-registry-manager`
* tried `composer update`
* got curl error 92 !
* `composer self-update 2.1.14`
* tried `composer update`
* got curl error 92 !

If someone has an idea about this I am very happy to hear it! I am stuck right now...

**Comment by ametad** [comment]
There is a remedy, re-install Homestead (version 13.2.1) and let it not update Composer to version 2.2.x.

To do this, first comment out the script that updates composer:

`vendor/laravel/homestead/scripts/homestead.rb`

```
#     # Update Composer On Every Provision
#     config.vm.provision 'shell' do |s|
#       s.name = 'Update Composer'
#       s.inline = 'sudo chown -R vagrant:vagrant /usr/local/bin && sudo -u vagrant /usr/local/bin/composer self-update --no-progress && sudo chown -R vagrant:vagrant /home/vagrant/.composer/'
#       s.privileged = false
#     end
```

NOTE This of course is not a real good idea, because you should never change code in the `vendor` map. This is only to illustrate when I come in trouble with Composer and Curl error 92.

After the above do:

* vagrant destroy && vagrant up
* vagrant ssh
* cd code
* composer update

And voila, everything works again!

### Diagnose

```
$ composer diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (2.0.7 => 2.2.7)
Composer version: 2.0.7
PHP version: 7.4.15 - Package overridden via config.platform, actual: 7.4.13
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
cURL version: 7.58.0 libz 1.2.11 ssl OpenSSL/1.1.1g
zip extension: OK

```

**Comment by svpernova09** [comment]
> There is a remedy, re-install Homestead (version 13.2.1) and let it not update Composer to version 2.2.x.
> 
> To do this, first comment out the script that updates composer:
> 
> `vendor/laravel/homestead/scripts/homestead.rb`
> 
> ```
> #     # Update Composer On Every Provision
> #     config.vm.provision 'shell' do |s|
> #       s.name = 'Update Composer'
> #       s.inline = 'sudo chown -R vagrant:vagrant /usr/local/bin && sudo -u vagrant /usr/local/bin/composer self-update --no-progress && sudo chown -R vagrant:vagrant /home/vagrant/.composer/'
> #       s.privileged = false
> #     end
> ```

Please do not modify `homestead/scripts/homestead.rb`, Homestead users should use `composer self-update --rollback` in their `after.sh`

**Comment by ametad** [comment]
> > There is a remedy, re-install Homestead (version 13.2.1) and let it not update Composer to version 2.2.x.
> > To do this, first comment out the script that updates composer:
> > `vendor/laravel/homestead/scripts/homestead.rb`
> > ```
> > #     # Update Composer On Every Provision
> > #     config.vm.provision 'shell' do |s|
> > #       s.name = 'Update Composer'
> > #       s.inline = 'sudo chown -R vagrant:vagrant /usr/local/bin && sudo -u vagrant /usr/local/bin/composer self-update --no-progress && sudo chown -R vagrant:vagrant /home/vagrant/.composer/'
> > #       s.privileged = false
> > #     end
> > ```
> 
> Please do not modify `homestead/scripts/homestead.rb`, Homestead users should use `composer self-update --rollback` in their `after.sh`

You are absolutely right about that @svpernova09 

Good idea to put it in the after.sh script. But only as workaround until you can run Composer `2.2.x` from within a Laravel Homestead running instance, with custom repositories.

**Comment by ametad** [comment]
My day got worse, I got the curl error now also on Windows platform (so not only in Laravel Homestead), with Composer version 2.2.7.

This is the error:

```
https://gitlab.redacted.domain/api/v4/group/14/-/packages/composer/packages.json could not be fully loaded (curl error 92 while downloading https://gitlab.redacted.domain/api/v4/group/14/-/packages/composer/p2/phar-io/version.json: HTTP/2 stream 0 was closed cleanly, but before getting  all response header fields, treated as error), package information was loaded from the local cache and may be out of date


  [Composer\Downloader\TransportException]
  curl error 92 while downloading https://gitlab.redacted.domain/api/v4/group/14/-/packages/composer/p2/phar-io/version.
  json: HTTP/2 stream 0 was closed cleanly, but before getting  all response header fields, treated as error
```

I just don't understand that there are two different urls mentioned in the error:

1. /api/v4/group/14/-/packages/composer/packages.json
1. /api/v4/group/14/-/packages/composer/p2/phar-io/version.json

**Comment by Seldaek** [comment]
The 1st URL is just about which composer repository failed to be loaded, the second one is the URL which effectively failed.

**Comment by ametad** [comment]
Thank you @Seldaek , that makes sense.

**Comment by ametad** [comment]
How about these request that are made when you do `composer udpate`, are these (the responses) cached? 

When I do a `composer clear-cache`, the problem is NOT going away. Also not when I do a `composer seff-update 2.1.x`. But the problem is only going away when I do an `composer rollback` to a earlier version then 2.2.0. 

Does this somehow makes sense..? I have trouble seeing it.

**Comment by ametad** [comment]
Also in version `2.2.9` I encounter this problem:

![image](https://user-images.githubusercontent.com/1582541/160363388-3e555890-ef1b-4dfd-a56c-1f8ac3bd25b1.png)

**Comment by ametad** [comment]
Our Gitlab instance gives a 404 because the url reqested by Composer does not exist on our server:

![image](https://user-images.githubusercontent.com/1582541/160364538-699891e2-5fb0-449c-bfe5-630614e8a897.png)

Why is Composer trying to grab information from our package repo, of a package that clearly resides on Packagist? See: https://packagist.org/packages/doctrine/inflector

**Comment by Seldaek** [comment]
Because it doesn't know what exists where.  See https://getcomposer.org/doc/articles/repository-priorities.md#filtering-packages for a way to fix that (most likely `only` here would help).

But anyway.. if you can try with `composer self-update 2.0.8` and up until you reach one that fails, that would be great, maybe it allows us to figure out which version broke something and find what the problem is. See https://getcomposer.org/download/ for the list of versions.

**Comment by ametad** [comment]
Thank you for the tip about `only`! 

I will put some energie in trying versions, until it give this curl error 92.

**Comment by ametad** [comment]
| Version   |      Error?      |
|----------|:-------------:|
| 2.1.0 |  NO  |
| 2.1.1 |  NO  |
| 2.1.2 |  NO  |
| 2.1.3 |  NO  |
| 2.1.4 |  YES  |

Test result: from version `2.1.4` I get the curl error.

Is this helpful for you @Seldaek ? I hope so.

**Comment by ametad** [comment]
@Seldaek Thank you for the tip about the [`only` filter](https://getcomposer.org/doc/articles/repository-priorities.md#filtering-packages) you gave. The problem can be solved indeed, with the filter in place it has some guidance on what urls are "valid". This way it is not trying other urls on our domain that give not the desired response, resulting in the curl error.

So this is solved in a way.

**Comment by Sanuich** [comment]
I had this issue because on windows composer stopped to store access key into auth.json file
When i did it manually the error disappeared
