### ISSUE TITLE
Can't find dll 

### ISSUE THREAD

**Issue by Friend0001** [composer/composer#10577]
error message 

The PHP exe file you specified did not run correctly:
C:\PHP7\php.exe

The php.ini used by your command-line PHP is: C:\PHP7\php.ini

A setting in your php.ini could be causing the problem: Either the 'extension_dir' value is incorrect or a dll does not exist.

Program Output:
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_pdo_oci' (tried: C:\PHP7\ext\php_pdo_oci (The specified module could not be found.), C:\PHP7\ext\php_php_pdo_oci.dll (The specified module could not be found.))
PHP Warning:  Module 'ldap' already loaded

but C:\PHP7\ext\php_pdo_oci  in ext directory

Any help will be appreciated 

Thank you

**Comment by johnstevenson** [comment]
You need to enable `extension_dir = "ext"` in your php.ini file by removing the leading semi-colon. You also need to search for `extension=ldap` and make sure there is only one entry.

**Comment by Friend0001** [comment]
Thank you, John, but it is already enabled. I check this first.

**Comment by johnstevenson** [comment]
Oh, in that case you probably need to check if you have the other dlls that php_pdo_oci apparently uses available.

**Comment by Friend0001** [comment]
Do you know depended for php_pdo_oci ? Can't find this information

**Comment by staabm** [comment]
Make sure which php.ini your php command is using with `php --ini`.

find the contents of the ini file involved and post it here

**Comment by johnstevenson** [comment]
@staabm 

> The php.ini used by your command-line PHP is: C:\PHP7\php.ini
