### ISSUE TITLE
Add an additional `/` for symlinks to make them Windows friendly

### ISSUE THREAD

**Issue by bilogic** [composer/composer#10578]
Hi,

I'm running Ubuntu as a VirtualBox guest on my Windows 10.

In Windows, there are `SYMLINK`, referring to a file, and `SYMLINKD`, referring to a folder.
The difference between the 2 when accessed from a Linux guest is 

1. SYMLINK - `/path/to/folder/`
2. SYMLINKD - `/path/to/folder//`, note the addtional `/` at the end

Today, `composer` running in Linux creates symlinks using method 1, this causes Windows to interpret it as a file and thus, doesn't allow the user to click into it the folder when in Windows. 

My expected output is that `composer` creates the symlinks with an additional `/`, this then makes both Linux and Windows parse the symlinks correctly.

I'm happy to submit a PR if this makes sense. Thank you.

**Comment by Seldaek** [comment]
Please submit a PR because I don't quite see how that'd work.

**Comment by bilogic** [comment]
Thanks, I'm onto it. 

I tried searching through the codes and found `relativeSymlink` here https://github.com/composer/composer/blob/575fbfb53fcc2388916d554271c99c8281fea782/src/Composer/Util/Filesystem.php#L737

However, no code seems to be calling it (found nothing for `>relativeSymlink` and `::relativeSymlink`).

Could you be so kind as to point me to the spot where composer processes the `repositories` section of `composer.json`? 
I'm specifically looking for the part where it performs symlink or mirror.

Thank you!
