### ISSUE TITLE
Stand with Ukraine🇺🇦

### ISSUE THREAD

**Issue by stop-war-in-ukraine** [composer/composer#10582]
Stop russia! Russia kills civilians!!
Block composer for russians!!! Help!

![Uploading Screenshot 2022-03-01 at 22.40.40.png…]()
https://github.com/stop-war-in-ukraine/stop-russia-it

[pnpm 🇺🇦](https://pnpm.io/) - https://twitter.com/pnpmjs/status/1498306992577957890

**Comment by vipinmittal3** [comment]
<img width="411" alt="composer StandWithUkraine" src="https://user-images.githubusercontent.com/88372787/157036525-dddd07ae-5902-4b45-933f-a0e9e40f8936.png">

**Comment by vipinmittal** [comment]
Update Drupal core

<img width="411" alt="composer StandWithUkraine" src="https://user-images.githubusercontent.com/10655108/157036749-1a55d046-39bf-4288-84b1-4bd6ce7bb56c.png">
