### ISSUE TITLE
Dependency injection in Custom Action

### ISSUE THREAD

**Issue by MdAbidHussain-91** [composer/composer#10588]
Hi Team,

I am referring to this article for running a long running task in background while returning 200 response immediately.
https://github.com/EricDahlvang/ImmediateAcceptAdapter 

Here, instead of Thread.Sleep in Custom Action, I have to make an http call which sometimes takes more than 15 secs.
I need some help in injecting a service with http call in the Sleep Custom Action.

**Comment by Seldaek** [comment]
I have no idea what you are talking about nor how it relates to this repository, sorry.
