### ISSUE TITLE
Stand with Ukraine🇺🇦

### ISSUE THREAD

**Issue by stop-war-in-ukraine** [composer/composer#10583]
BLOCK composer for russians!

Russia kills civilians!! Stop war!!!

https://github.com/stop-war-in-ukraine/stop-russia-it

[pnpm 🇺🇦](https://pnpm.io/) - https://twitter.com/pnpmjs/status/1498306992577957890

[removed graphic content]

**Comment by xbvan** [comment]
no zuo no die

**Comment by Seldaek** [comment]
See https://github.com/composer/packagist/commit/86244a3695fcaaac9c5ba4257a4314eae1c6d981
