### ISSUE TITLE
Plugin not removed from allow-plugins config on remove

### ISSUE THREAD

**Issue by chr-hertel** [composer/composer#10599]
When I remove a plugin which was listed in the `allow-plugins` section of `config`, it is not removed from that section.

Example `composer.json`:

```json
{
    "require": {
        "symfony/flex": "^2.1"
    },
    "config": {
        "allow-plugins": {
            "symfony/flex": true
        }
    }
}
```

After succesfully running the remove cmd: `composer rem symfony/flex`:

```json
{
    "config": {
        "allow-plugins": {
            "symfony/flex": true
        }
    }
}
```

Is my expectation correct that it should be remove in the config as well?

**Comment by Seldaek** [comment]
I guess we could automatically do that on plugin uninstall, I just wonder if that will end up annoying for some use cases.
