### ISSUE TITLE
Require for php-cli

### ISSUE THREAD

**Issue by tenzap** [composer/composer#10590]
I didn't find anywhere in the [documentation](https://getcomposer.org/doc/04-schema.md) how to specify that` php-cli` (the command line interface of PHP) is needed.

For example in debian this is in a separate package.

Is it possible to use composer require for this?

How to write this in composer.json?

**Comment by Seldaek** [comment]
There is no way to require any SAPI right now, and to be honest I don't really see how we could even do this. It's not easy to know which SAPIs are available on a system from within one PHP process. Composer usually is run by php-cli, so we can establish that is present, but that's about it.
