### ISSUE TITLE
Can a Plugin-Path be relative to the vendor-dir?

### ISSUE THREAD

**Issue by dennisbaum** [composer/composer#10594]
```json
{
  "require": {
    "php": ">=7.4.0 <8.2.0",
    "getkirby/cms": "^3.6",
    "beebmx/kirby-env": "^3.0"
  },
  "config": {
    "vendor-dir": "src/vendor",
    "optimize-autoloader": true,
    "allow-plugins": {
      "getkirby/composer-installer": true
    }
  },
  "extra": {
    "kirby-plugin-path": "src/site/plugins"
  }
}
```

```
Checking composer version: OK
Composer version: 2.2.7
PHP version: 8.1.3
```

If i install the above composer.json, it will install to src/vendor as expected.
further it installs the plugin  "beebmx/kirby-env" to src/site/plugin as expected by their composer-installer
https://github.com/getkirby/composer-installer

autoload_static.php
```php
  'Kirby\\' => 
        array (
            0 => __DIR__ . '/..' . '/getkirby/composer-installer/src',
            1 => __DIR__ . '/..' . '/getkirby/cms/src',
        ),
  'Beebmx\\' => 
  array (
      0 => __DIR__ . '/../../..' . '/src/site/plugins/kirby-env/src',
  ),
```

unfortenetly i get a problem with the resulting paths in the autoloader-classes for the plugin, if i am going to host only the contents of 'src' or if i map 'src' to a docker-volume 'var/www/web' autoloader can't find 'src'
is there a way to configure a plugin-path relative to the vendor-dir?
so the plugin is independent of the parent folders name?
```php
 'Beebmx\\' => 
        array (
            //0 => __DIR__ . '/../../..' . '/src/site/plugins/kirby-env/src',
            0 => __DIR__ . '/../..' . '/site/plugins/kirby-env/src',
        ),
```

i would really apreciate some help here!
thx

**Comment by Seldaek** [comment]
I have no idea. kirby-plugin-path is managed by getkirby/composer-installer, please ask on that package's github repo.
