### ISSUE TITLE
Info header included with -q

### ISSUE THREAD

**Issue by GeoffreyDijkstra** [composer/composer#10598]
When running any composer command with --quiet flag the info banner (#standWithUkraine) is not hidden.
Because we use composer scripts in crontab this results in us being spammed with emails because composer now has output where there should be none. Can you guys make it so that the info header be removed when the -q (--quiet) flag is being used?

Tested with 2 composer versions, 2.2.4 (version on our server) and 2.2.7 (latest) same result.

**Comment by Seldaek** [comment]
The Info line goes to STDERR while the json output goes to STDOUT, so it should not break anything.
