### ISSUE TITLE
--no-ansi regression 

### ISSUE THREAD

**Issue by ktomk** [composer/composer#10601]
Since https://github.com/composer/packagist/commit/86244a3695fcaaac9c5ba4257a4314eae1c6d981 here in #10582 composers global `--no-ansi` switch does not work properly any longer for the binary sequence that was introduced by that change.

It looks like composer passes this information unchecked and unfiltered into the users shell.

**Comment by Seldaek** [comment]
Let's be honest, if a repository wants to mess with you, it can serve you URLs to packages with malware in them.. so I think we can assume some amount of good-will here.

**Comment by ktomk** [comment]
Okay, let's be honest: A NUL byte / C0 check would also not turn this into a malware shield. I had more my own terminal messes in mind when injecting control characters than anything else. More error correction than anything else.

So better make the regex pattern filtering out actual ANSI sequences first of all - if anything.
