### ISSUE TITLE
CLEAN Composer released

### ISSUE THREAD

**Issue by masterwto** [composer/composer#10609]
As shown in https://github.com/composer/packagist/commit/86244a3695fcaaac9c5ba4257a4314eae1c6d981, the official Composer project is no longer a purely technical open source project. It has mixed some people's political views and tried to force everyone to accept his political views.

A clean composer has been forked and released for the open-source world. We don't support war, nor any country. We don't care about politics, so we don't want political-related information to appear when using Composer.

https://github.com/open-composer/composer

**Comment by Seldaek** [comment]
I would not recommend anyone use a composer phar file from an untrusted source.. Do so at your own risk.
