### ISSUE TITLE
StandWithJustice

### ISSUE THREAD

**Issue by JiaMorant** [composer/composer#10607]
The recent double standards have really opened my eyes. No one can say who is wrong. You blame Russia, but no one dares to blame NATO countries. Standing with Ukraine? It's really ridiculous. You just stand with your own interests. Ukraine is just a pawn of NATO. Who do you stand with when NATO countries kill civilians in other countries? I suggest you be more direct and say "we just want to kill Russia".

**Comment by Seldaek** [comment]
Spam from newly created users, not suspect at all.
