### ISSUE TITLE
Grab dependencies for upload to server with specific/different PHP version.

### ISSUE THREAD

**Issue by tenzap** [composer/composer#10625]
I use composer to grab the dependencies of the project.
However this will grab the dependencies for my specific version of PHP (7.4) and PHP setup.

Now let's say I want to deploy it on a server that has no access to the internet and not even the possibility to run composer CLI.
This server doesn't run the same version of PHP as on my system. It runs let's say PHP 7.1.

Now my problem is how do I do to get the packages for that specific version of PHP for deployment on that server?

I tried with `--ignore-platform-reqs` but it ignores the requirements of the json file. Actually this is not what I need, it looks like it simply downloads the latest versions without checking if my system can run it. My need is that composer gets the packages for exactly 7.1 so that I can then upload all the files to the server.

I thought there may be an option to simulate an environment, or the PHP version (or with a env. var) but couldn't find anything.

How may I achieve this?

My `composer.json`:

```json
{
    "name": "kalkun-sms/kalkun",
    "description": "Kalkun SMS Manager",
    "type": "project",
    "license": "GPL-3.0",
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/kissifrot/php-ixr"
        }
    ],
    "require": {
        "php": ">5.6",
        "ext-ctype": "*",
        "ext-curl": "*",
        "ext-hash": "*",
        "ext-intl": "*",
        "ext-json": "*",
        "ext-mbstring": "*",
        "ext-session": "*",
        "codeigniter/framework": ">=3.1.13 <3.2",
        "paragonie/random_compat": ">=2",
        "giggsey/libphonenumber-for-php": "^8.12",
        "league/csv": "^8.2 || ^9.5",
        "datto/json-rpc-http": "^4.0 || ^5.0",
        "kissifrot/php-ixr": "1.8.*"
    },
    "require-dev": {
        "phpunit/phpunit": "^7",
        "kenjis/ci-phpunit-test": "^0.17.3",
        "squizlabs/php_codesniffer": "^3.6",
        "friendsofphp/php-cs-fixer": "^3.3",
        "ise/php-codingstandards-codeigniter": "^1.0"
    },
    "suggest": {
        "ext-ldap": "For phonebook_ldap plugin",
        "ext-mysqli": "To connect to a MySQL database",
        "ext-pgsql": "To connect to a PostgreSQL database",
        "ext-sqlite3": "To connect to a SQLite3 database"
    }
}

```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
License "GPL-3.0" is a deprecated SPDX license identifier, use "GPL-3.0-only" or "GPL-3.0-or-later" instead
require.paragonie/random_compat : unbound version constraints (>=2) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Composer version: 2.0.9
PHP version: 7.4.25
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1k  25 Mar 2021
cURL version: 7.74.0 libz 1.2.11 ssl OpenSSL/1.1.1k
zip: extension present, unzip present

```

**Comment by Seldaek** [comment]
What you need is https://getcomposer.org/doc/06-config.md#platform that's also how Composer itself ensures we do not ship dependencies that do not work with our minimum php version https://github.com/composer/composer/blob/a2bdf72fa4af217c7a617ad08ff7a98b8bc0ac11/composer.json#L57-L60

**Comment by tenzap** [comment]
Thanks a lot!
