### ISSUE TITLE
PRE_UPDATE_CMD behavior change between composer1 and 2

### ISSUE THREAD

**Issue by mlocati** [composer/composer#10636]
I maintain a [composer plugin](https://github.com/mlocati/composer-patcher) that allows patching packages installed via composer.

These patches are defined in a custom `extra.patches` section of `composer.json` (see [this package](https://github.com/concrete5/dependency-patches/blob/1.7.0/composer.json#L19-L65) for a sample usage).

Patches may be updated from time to time, so the already patched packages must be uninstalled and reinstalled, so that we have a fresh unpatched copy of them and the new version of the patches can be applied without issues.

In order to do that, my plugin checks (in the `ScriptEvents::PRE_INSTALL_CMD` and `ScriptEvents::PRE_UPDATE_CMD` events) if a package was already patched but we have new version of the patches (see [here](https://github.com/mlocati/composer-patcher/blob/1.2.2/src/Plugin.php#L104-L105)).
In this case, the plugin (via the `UninstallOperation` class) uninstall the package (see [here](https://github.com/mlocati/composer-patcher/blob/1.2.2/src/Plugin.php#L122) and [here](https://github.com/mlocati/composer-patcher/blob/1.2.2/src/Plugin.php#L401)).

In Composer 1 this worked like a charm: my plugin uninstalled the packages and composer re-installed them.

In Composer2, the packages uninstalled by my plugin, aren't re-installed by composer.

For example: here's the relevant output of composer 1 when some packages must be re-installed:

```
Gathering patches from concrete5/dependency-patches (extra.patches).
Removing package laminas/laminas-code so that it can be re-installed and re-patched.
  - Removing laminas/laminas-code (3.4.1)
Removing package lcobucci/jwt so that it can be re-installed and re-patched.
  - Removing lcobucci/jwt (3.4.6)
Removing package league/url so that it can be re-installed and re-patched.
  - Removing league/url (3.3.5)
Removing package sunra/php-simple-html-dom-parser so that it can be re-installed and re-patched.
  - Removing sunra/php-simple-html-dom-parser (v1.5.2)
Package operations: 4 installs, 1 update, 0 removals
  - Installing sunra/php-simple-html-dom-parser (v1.5.2): Loading from cache
  - Installing league/url (3.3.5): Loading from cache
  - Installing lcobucci/jwt (3.4.6): Loading from cache
  - Installing laminas/laminas-code (3.4.1): Loading from cache
Writing lock file
Generating autoload files
Gathering patches from concrete5/dependency-patches (extra.patches).
Applying patch concrete5/dependency-patches/Add PHP 8.1 compatibility to laminas/laminas-code... done.
Applying patch concrete5/dependency-patches/Add PHP 8 compatibility to lcobucci/jwt... done.
Applying patch concrete5/dependency-patches/Add PHP 8.1 compatibility to league/url... done.
Applying patch concrete5/dependency-patches/Fix minus in regular expressions to sunra/php-simple-html-dom-parser... done.
Applying patch concrete5/dependency-patches/Add PHP 8.1 compatibility to sunra/php-simple-html-dom-parser... done.
```

And here's the relevant output when running composer 2:

```
Gathering patches from concrete5/dependency-patches (extra.patches).
Removing package laminas/laminas-code so that it can be re-installed and re-patched.
  - Removing laminas/laminas-code (3.4.1)
Removing package lcobucci/jwt so that it can be re-installed and re-patched.
  - Removing lcobucci/jwt (3.4.6)
Removing package league/url so that it can be re-installed and re-patched.
  - Removing league/url (3.3.5)
Removing package sunra/php-simple-html-dom-parser so that it can be re-installed and re-patched.
  - Removing sunra/php-simple-html-dom-parser (v1.5.2)
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 0 updates, 0 removals
Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
Gathering patches from concrete5/dependency-patches (extra.patches).
```

As you can see, composer2 doesn't install the just-uninstalled packages (and indeed they are not present in the vendor directory).

So, it seems that in composer 2 the `PRE_INSTALL_CMD` and `PRE_UPDATE_CMD` events don't occur before the install and the update commands as [per their description](https://github.com/composer/composer/blob/2.2.9/src/Composer/Script/ScriptEvents.php#L24), but at a later time.

**Comment by Seldaek** [comment]
Have you looked how https://github.com/cweagans/composer-patches does it for Composer 2.x support? Maybe you can inspire yourself again from this, or just use it and stop maintaining your own plugin? I am not sure what the differences are but AFAIK cweagans/composer-patches works well with v2.

The only hint I can give you is to perhaps try to replace https://github.com/mlocati/composer-patcher/blob/1.2.2/src/Plugin.php#L408 by `$installationManager->execute($localRepository, [$uninstallOperation])` - this should make sure the promises are waited on, and the local repository written to disk, which may fix things, I am not sure.
