### ISSUE TITLE
[v2.3-RC1] Process component incompatibility

### ISSUE THREAD

**Issue by IonBazan** [composer/composer#10630]
My `composer.json`:

```json
{
    "name": "test",
    "license": "proprietary",
    "type": "project",
    "autoload": {
        "psr-4": {
            "AppBundle\\": "src/AppBundle"
        },
        "classmap": [
            "app/AppKernel.php",
            "app/AppCache.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        },
        "files": [
            "vendor/symfony/symfony/src/Symfony/Component/VarDumper/Resources/functions/dump.php"
        ]
    },
    "require": {
        "php": ">=7.3",
        "ext-curl": "*",
        "ext-gmp": "*",
        "ext-intl": "*",
        "sensio/distribution-bundle": "^5.0.19",
        "sensio/framework-extra-bundle": "^5.0.0",
        "symfony/symfony": "3.4.*",
    },
    "scripts": {
        "symfony-scripts": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-install-cmd": [
            "@symfony-scripts"
        ],
        "post-update-cmd": [
            "@symfony-scripts"
        ],
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.3.0-RC1
PHP version: 7.4.28
PHP binary path: /opt/homebrew/Cellar/php@7.4/7.4.28_1/bin/php
OpenSSL version: OpenSSL 1.1.1m  14 Dec 2021
cURL version: 7.82.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1m
zip: extension present, unzip present, 7-Zip not available
```

When I run this command: 

```
composer install -vvv
```

I get the following output: 

```
Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in <redacted>/vendor/sensio/distribution-bundle/Composer/ScriptHandler.php on line 310 and defined in phar:///usr/local/bin/composer/vendor/symfony/process/Process.php:143
Stack trace:
#0 <redacted>/vendor/sensio/distribution-bundle/Composer/ScriptHandler.php(310): Symfony\Component\Process\Process->__construct(''/opt/homebrew/...', '/Users/ion/work...', NULL, NULL, '0')
#1 <redacted>/vendor/sensio/distribution-bundle/Composer/ScriptHandler.php(88): Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::executeBuildBootstrap(Object(Composer\Script\Event), ''var'', ''/Users/ion/wor...', '0')
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(388): Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap(Ob in phar:///usr/local/bin/composer/vendor/symfony/process/Process.php on line 143
```

And I expected this to happen:

No error should be produced.

I assume this happens because Composer's included `symfony/process` v5.4 is used instead of already installed v3.4 which have different `Process::__construct()` definition:

https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Composer/ScriptHandler.php#L310

https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Process/Process.php#L144
https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Process/Process.php#L143

I am going to solve it by completely dropping the SensioDistributionBundle but not sure how to keep that working.

**Comment by Seldaek** [comment]
Yeah this is a nasty issue, given sensio distribution bundle here is way outdated and also EOL, you have to drop it or remain on Composer 2.2 LTS for now, sorry I don't think I can do anything to help from this end.

**Comment by Seldaek** [comment]
I'll make note of this though for the final release maybe add it in known issues as it probably will affect others.

**Comment by Seldaek** [comment]
BTW if you do absolutely need the ScriptHandler there you can fork it and change lines 291 & 310 to do this instead:


```
        if (method_exists('Symfony\Component\Process\Process', 'fromShellCommandline')) {
            $process = Process::fromShellCommandline(...args here...);
        } else {
            $process = new Process(...args here...);
        }
```

**Comment by IonBazan** [comment]
@Seldaek thanks for your response and the patch 👏🏻 . Indeed, Symfony 3.4 and the Sensio Distribution Bundle are EOL for log time already so I understand this will not be fixed and Composer LTS should be used for legacy apps. I just wonder:

a) How do legacy project users will be able to stick to v2.2.x when v2.3 is released?
b) Is it possible to prioritize the class from `vendor` instead of the one delivered with Composer?
c) Maybe we can run post-install scripts in separate php process to avoid that?

This particular problem is solvable on the application end but I suppose this behaviour could cause many other issues when executing custom code via composer scripts.

**Comment by Seldaek** [comment]
a) `composer self-update 2.2.9` for example lets you upgrade to that version specifically. You can add a require in your composer.json for `"composer": "<2.3"` (see https://getcomposer.org/doc/articles/composer-platform-dependencies.md#composer-package-composer) to catch mistakes, but I realize this sucks a bit. I think if you cannot upgrade Symfony or get rid of the sensio/distribution-bundle package, I would fork it to make sure you can use latest Composer.
b) Nope this would break Composer.
c) Also not really feasible in Composer itself. The script could have been built that way, but it wasn't, and patching it the way I described is much easier than patching it to execute in a separate process etc I think.

**Comment by IonBazan** [comment]
Thanks, noted!
I think it would also affect many users that use: `curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer` to install Composer during deployment or in CI/CD environment to pull the latest version. Maybe it would be possible to add a deprecation warning there about incoming breaking change so that users preferring to stick to LTS version would start using LTS channel (`--lts` flag) instead of latest?

**Comment by Seldaek** [comment]
I think we'll see how it goes once a final release is out.. If it's a huge mess I can add an lts channel to ease things up. But really the goal is that people upgrade unless they are stuck on an old PHP version. I rather not make it easier to stay stuck behind.
