### ISSUE TITLE
`install --no-dev` installing phpdocumentor/phpdocumentor despite being a dev dependency

### ISSUE THREAD

**Issue by coldacid** [composer/composer#10644]
My `composer.json`:

```json
{
    "name": "coldacid/minimal-test-case",
    "require": {
        "php": ">=7.0",
        "ext-gettext": "*",
        "ext-simplexml": "*",
        "composer/installers": "~1.9.0",
        "james-heinrich/getid3": "~1.9.19",
        "podcastindex/podcastindex-php": "~1.0"
    },
    "require-dev": {
        "friendsofphp/php-cs-fixer": "^3.0",
        "squizlabs/php_codesniffer": "^3.6",
        "phpunit/phpunit": "^9.5",
        "phpdocumentor/phpdocumentor": "^3.0"
    },
    "config": {
        "allow-plugins": {
            "composer/installers": true,
            "symfony/flex": false
        }
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
The version field is present, it is recommended to leave it out if the package is published on Packagist.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.2.9
PHP version: 8.1.4
PHP binary path: C:\tools\php81\php.exe
OpenSSL version: OpenSSL 1.1.1m  14 Dec 2021
cURL version: 7.77.0 libz 1.2.11 ssl OpenSSL/1.1.1m
zip: extension present, unzip present, 7-Zip present (7z)
```

When I run this command: 

```
composer install --prefer-dist --no-dev -vvv
```

I get the following output: 

[composer.log](https://github.com/composer/composer/files/8312616/composer.log)

And I expected this to happen:

Only composer/installers, james-heinrich/getid3, podcastindex/podcastindex-php, and their recursive dependencies (guzzlehttp/guzzle, guzzlehttp/psr7, psr/http-message, ralouphie/getallheaders, symfony/polyfill-intl-idn, symfony/polyfill-intl-normalizer, symfonly/polyfill-php72) would be installed.

![expected installed](https://user-images.githubusercontent.com/130681/159195692-f678e81d-fe68-4643-8324-013181d6f296.png)

Instead:

Not only were the above non-dev dependencies installed, but phpdocumentor/phpdocumentor and all of its dependencies were also installed:

![vendor/ directory](https://user-images.githubusercontent.com/130681/159195376-129375a1-e85f-4dd1-98f4-7dcfb589aba8.png)

**Comment by Seldaek** [comment]
If you run `composer why phpdocumentor/phpdocumentor` after installling, you will see:

```
coldacid/minimal-test-case   dev-master  requires (for development)  phpdocumentor/phpdocumentor (^3.0)
phpdocumentor/phpdocumentor  v3.1.2      replaces                    paragonie/random_compat (2.*)
phpdocumentor/phpdocumentor  v3.1.2      replaces                    symfony/polyfill-iconv (*)
phpdocumentor/phpdocumentor  v3.1.2      replaces                    symfony/polyfill-php56 (*)
phpdocumentor/phpdocumentor  v3.1.2      replaces                    symfony/polyfill-php70 (*)
phpdocumentor/phpdocumentor  v3.1.2      replaces                    symfony/polyfill-php71 (*)
phpdocumentor/phpdocumentor  v3.1.2      replaces                    symfony/polyfill-php72 (*)
symfony/polyfill-intl-idn    v1.25.0     requires                    symfony/polyfill-php72 (^1.10)
twig/twig                    v2.14.11    requires                    symfony/polyfill-php72 (^1.8)
```

Or with `-t` (extract from output):

```
├──phpdocumentor/phpdocumentor v3.1.2 (replaces symfony/polyfill-php72 *)
│  ├──symfony/polyfill-intl-idn v1.25.0 (requires symfony/polyfill-php72 ^1.10)
│  │  ├──guzzlehttp/guzzle 6.5.5 (requires symfony/polyfill-intl-idn ^1.17.0)
│  │  │  └──podcastindex/podcastindex-php 1.0.3 (requires guzzlehttp/guzzle ^6.3)
│  │  │     └──coldacid/minimal-test-case dev-master (requires podcastindex/podcastindex-php ~1.0)
```

So due to podcastindex/podcastindex-php requiring guzzle which requires symfony/polyfill-intl-idn which requires symfony/polyfill-php72 which is *replaced* by phpdocumentor/phpdocumentor, so that means phpdocumentor/phpdocumentor needs to be present to fulfill the non-dev requirements.

This is IMO a bug in phpdocumentor/phpdocumentor, I don't know why they abuse replace there to suppress those polyfill packages, these replace rules definitely should not belong in such a package, it belongs in the root projects' composer.json if at all.

Please report it on https://github.com/phpDocumentor/phpDocumentor, you can reference this issue/comment if needed.

**Comment by Seldaek** [comment]
Or maybe check their README https://github.com/phpDocumentor/phpDocumentor#via-composer-not-recommended
