### ISSUE TITLE
Composer install over SSH fails sometimes

### ISSUE THREAD

**Issue by martin-braun** [composer/composer#10643]
I try to install a very old Laravel project on my server via script. Everything works but composer install fails 1/4 of a time. Right, the issue is not reproducable and I can fix it by simply restarting the command, but I need to fix this so it works reliably. 

I installed composer via script like it is [recommend officially](https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md). Then I build my installer script, but it seems that this command gets stuck only 1/4 of a time: 

```sh
ssh server.prod $HOME/composer.phar install -vvv --no-interaction --no-plugins --no-scripts -d /var/www/example.org
```

If this happens I can simply retry and the next time it probably works again. I can also run this directly on the server without any problems.

Info on server: 

```
# $HOME/composer.phar -V
Composer version 2.2.7 2022-02-25 11:12:27
# cat /etc/debian_version
10.11
```

I invoke this from TypeScript on macOS ([more info](https://stackoverflow.com/questions/71550573/composer-installer-over-ssh-hangs-sometimes)), but I invoke many other commands over SSH, but only composer install fails 1/4 of a time.

My `composer.json`:

```json
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.2.5",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.24",
        "laravel/passport": "^9.3",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^2.2",
        "mailjet/laravel-mailjet": "^3.0",
        "srmklive/paypal": "~1.0"
    },
    "require-dev": {
        "facade/ignition": "2.5.2",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.1",
        "phpunit/phpunit": "^8.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\"",
            "@php -r \"file_exists('.debug') || copy('.debug.example', '.debug');\"",
            "@php -r \"file_exists('.my.cnf') || copy('.my.cnf.example', '.my.cnf');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
```

Output of `composer diagnose`:

```
# $HOME/composer.phar diagnose
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.2.9
PHP version: 7.4.28
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
cURL version: 7.64.0 libz 1.2.11 ssl OpenSSL/1.1.1d
zip: extension present, unzip not available, 7-Zip not available
```

What happens when the same command hangs (1/4):

<img width="931" alt="Screen Shot 2022-03-20 at 9 50 08 PM" src="https://user-images.githubusercontent.com/24259245/159186451-960f93d0-c3bb-40c8-b34a-37fabe2d19d3.png">

**Comment by Seldaek** [comment]
So no output at all even with -vvv? That sounds like it never even starts Composer otherwise it should almost certainly output something before freezing, but who knows.. Especially the fact it's random sounds odd.

**Comment by martin-braun** [comment]
@Seldaek Correct, no output at all, but only 1/4 at the time, which is really odd. I have no clue how I even attempt to approach this problem, since it's looking like only the combination of SSH and composer cause this issue sometimes. As soon as I ditch one of the two methods there are no problems at all. Other commands work via SSH with the same method and composer never hang when running it on the server directly.

**Comment by herndlm** [comment]
Can you run ssh in verbose mode too? Maybe that tells more in case it really hangs already before executing composer

**Comment by martin-braun** [comment]
@herndlm This was a good idea, the behavior gets weirder. Without the `-v` flag it was stuck (waited at least 3 minutes before canceling using CTRL+C), but when I add the flag it will also look like this, for 1-2 minutes, but after that it will run through: 

<img width="922" alt="Screen Shot 2022-03-22 at 1 22 13 AM" src="https://user-images.githubusercontent.com/24259245/159395854-09c7084a-f184-48cb-bb5c-0fadddf28689.png">

So with the SSH verbose flag it will flush all the output eventually and exit with 0. At this point I suspect it's the way I print stdout that might causes the issue, but it makes no sense how the `-v` flag on SSH can fix that composer runs through. I know right now that the way how I output the lines is done right, there is a bug that it will always be one line behind the current stdout until my process finally finishes (and I planned to fix that). I ignored that for now, because I thought it's not big of a deal, so I thought. When running composer over SSH (or probably anything over SSH), my process flushes all output when the process exits and I think this is related. 

This is a problem in my code and Deno and not composer, please give me a day or two to overwork it and see if it fixes that. I will close the issue for now and report back. Thanks!

**Comment by martin-braun** [comment]
@Seldaek @herndlm Since my recent changes in my linked issue the process didn't hang anymore and I invoked it a good 10 to 15 times so far, so I'm pretty confident that the reason for the issue was the way I was piping stdout, but I'm still amazed how this caused issues in the first place only when I would run composer over SSH. Since composers initialization is the slowest of all my remote commands this might be related, but it's not an issue on composer's end.

The Issue is fixed and I will continue my work, thanks for not ignoring my case after all.
