### ISSUE TITLE
Packagist.org adding NON-JSON text to the Composer JSON output.

### ISSUE THREAD

**Issue by WebTigers** [composer/composer#10649]
Running the following command inserts non-JSON text into the output from Packagist.org. This does not happen with private REPO's.

When I run this command:

```
$ php composer.phar show aws/aws-sdk-php --outdated --format=json
```

I get the following output:

```
Info from https://repo.packagist.org: #StandWithUkraine
{
    "name": "aws/aws-sdk-php",
    "description": "AWS SDK for PHP - Use Amazon Web Services in your PHP project",
    "keywords": [
        "amazon",
        "aws",
        "cloud",
        "dynamodb",
        "ec2",
        "glacier",
        "s3",
        "sdk"
    ],
    "type": "library",
    "homepage": "http://aws.amazon.com/sdkforphp",
    "names": [
        "aws/aws-sdk-php"
    ],
    "versions": [
        "3.210.0"
    ],
    "licenses": [
        {
            "name": "Apache License 2.0",
            "osi": "Apache-2.0",
            "url": "https://spdx.org/licenses/Apache-2.0.html#licenseText"
        }
    ],
    "latest": "3.215.0",
    "source": {
        "type": "git",
        "url": "https://github.com/aws/aws-sdk-php.git",
        "reference": "b5cd025eb804a023f4d9fe7a4f6de437b5910a13"
    },
    "dist": {
        "type": "zip",
        "url": "https://api.github.com/repos/aws/aws-sdk-php/zipball/b5cd025eb804a023f4d9fe7a4f6de437b5910a13",
        "reference": "b5cd025eb804a023f4d9fe7a4f6de437b5910a13"
    },
    "path": "/var/www/narware-vendor/vendor/aws/aws-sdk-php",
    "suggests": {
        "aws/aws-php-sns-message-validator": "To validate incoming SNS notifications",
        "doctrine/cache": "To use the DoctrineCacheAdapter",
        "ext-curl": "To send requests using cURL",
        "ext-openssl": "Allows working with CloudFront private distributions and verifying received SNS messages",
        "ext-sockets": "To use client-side monitoring"
    },
    "support": {
        "forum": "https://forums.aws.amazon.com/forum.jspa?forumID=80",
        "issues": "https://github.com/aws/aws-sdk-php/issues",
        "source": "https://github.com/aws/aws-sdk-php/tree/3.210.0"
    },
    "autoload": {
        "psr-4": {
            "Aws\\": "src/"
        }
    },
    "requires": {
        "aws/aws-crt-php": "^1.0.2",
        "ext-json": "*",
        "ext-pcre": "*",
        "ext-simplexml": "*",
        "guzzlehttp/guzzle": "^5.3.3|^6.2.1|^7.0",
        "guzzlehttp/promises": "^1.4.0",
        "guzzlehttp/psr7": "^1.7.0|^2.0",
        "mtdowling/jmespath.php": "^2.6",
        "php": ">=5.5"
    },
    "devRequires": {
        "andrewsville/php-token-reflection": "^1.4",
        "aws/aws-php-sns-message-validator": "~1.0",
        "behat/behat": "~3.0",
        "doctrine/cache": "~1.4",
        "ext-dom": "*",
        "ext-openssl": "*",
        "ext-pcntl": "*",
        "ext-sockets": "*",
        "nette/neon": "^2.3",
        "paragonie/random_compat": ">= 2",
        "phpunit/phpunit": "^4.8.35|^5.4.3",
        "psr/cache": "^1.0",
        "psr/simple-cache": "^1.0",
        "sebastian/comparator": "^1.2.3"
    }
}

```

And I expected this to happen:

NOT HAVE non-JSON text added to the output!

```
Info from https://repo.packagist.org: #StandWithUkraine    <--- THIS IS BAD JSON
{
    "name": "aws/aws-sdk-php",
    "description": "AWS SDK for PHP - Use Amazon Web Services in your PHP project",
    "keywords": [
        "amazon",
        "aws",
        "cloud",
        "dynamodb",
        "ec2",
        "glacier",
        "s3",
        "sdk"
    ],
...
```

**Comment by Madpeterz** [comment]
maybe we could have the info message attach itself to the first package

```
Info from https://repo.packagist.org: #StandWithUkraine    <--- THIS IS BAD JSON
{
    "name": "aws/aws-sdk-php",
```

becomes

```
{
    "meta-not-related-to-package-from-composer": "#StandWithUkraine"
    "name": "aws/aws-sdk-php",
```

**Comment by stof** [comment]
The info message is sent to STDERR, not to STDOUT. So it does not mess with the json.

**Comment by WebTigers** [comment]
Why is the message only error-ing out with Packagist.org and not GitHub?

**Comment by Seldaek** [comment]
If you only use STDOUT output to parse json you won't get any problem. You can also run `composer.phar show aws/aws-sdk-php --outdated --format=json 2>/dev/null` to suppress STDERR in this case.

**Comment by WebTigers** [comment]
Thanks for the tip, Seldaek. That works, BUT I shouldn't have to do this.

**Comment by Seldaek** [comment]
You shouldn't have to thanks to the separation of STDOUT/STDERR by default. If you don't have them separated it's most likely due to something else you do to merge all output..

**Comment by WebTigers** [comment]
It's just the normal output from PHP's `shell_exec()` command. Normally if there is no error, it's empty.

**Comment by stof** [comment]
STDERR is not only about errors in POSIX. It is also meant for diagnostic messages (i.e. any message that does not belong to the actual output of the command, that you would pipe somewhere else).
And btw, POSIX does not even name the streams STDOUT and STDERR but 1 and 2.

> It is VERY COMMON practice to merge STDOUT with STDERR and read the messages as one, which is what is being done here.

if you expect the output to be valid json when using `--format=json` but you merge STDOUT and STDERR together, then the only way this can happen is if STDERR, in which case there is no need to merge them...

**Comment by Seldaek** [comment]
See also https://unix.stackexchange.com/a/336989

**Comment by WebTigers** [comment]
I've already made my point. STDERR is for errors, and within that sense, other diagnostics for sure. 

POSIX is IN, OUT, ERR. Not IN, OUT, WHATEVER. 

With all due respect, you're just making stuff up here. It's a BAD practice. Yes, people do all kinds of crap in programming, this is a prime example. You can post whatever links you like, but if there's no error, leave the STDERR blank. Put your fun little message in the payload as properties we can just ignore but DO NOT break the code.

If I send a flag for --verbose or  --diag sure, shove all the junk you want into STDERR, but outside of that we should not be seeing anything in STDERR.

I'm done, gentlemen. Please stop shoving crap into STDERR when there is no error. Have a nice day.

**Comment by legodion** [comment]
sorry filthy russian shill, you must abide by the console spam of the monopolized php package manager in order to save peoples from putin. if only those tanks had a laptop with a terminal in them to see this heroism they would surely change their minds and turn back to moscow, then we could all live in harmony with non-broken CI workflows.

**Comment by politsin** [comment]
```sh
git clone https://github.com/composer/composer.git --branch 2.4.4  ~/composer-build && \
    composer install  -o -d ~/composer-build && \
    wget https://raw.githubusercontent.com/politsin/snipets/master/patch/composer.patch -q -O ~/composer-build/composer.patch  && \
    cd ~/composer-build && patch -p1 < composer.patch && \
    php -d phar.readonly=0 bin/compile && \
    rm /usr/local/bin/composer && \
    php composer.phar install && \
    php composer.phar update && \
    mv ~/composer-build/composer.phar /usr/local/bin/composer && \
    rm -rf ~/composer-build  && \
    chmod +x /usr/local/bin/composer
```
