### ISSUE TITLE
install laravel/laravel v9.1.2 

### ISSUE THREAD

**Issue by Amin1990s** [composer/composer#10641]
Trying to decide install laravel/laravel v9.1.2 on level 3, even though laravel/laravel-9.1.2.0 was previously decided as 2.                         
  This exception was most likely caused by a bug in Composer.                                                                                          
  Please report the command you ran, the exact error you received, and your composer.json on https://github.com/composer/composer/issues - thank you!

**Comment by Seldaek** [comment]
Yes, as the error message said, `Please report the command you ran, the exact error you received, and your composer.json`. You only included the error message without stack trace or full output, and without composer.json, so we really cannot do much here. Please try again by following the issue template.
