### ISSUE TITLE
[FeatureRequest] Skip dependency version check argument

### ISSUE THREAD

**Issue by YellowPhoenix18** [composer/composer#10654]
As the issue-template is written for bugs and this is a feature-request I do not follow it:

When I locally work on updating packages and want to test them in already existing projects and another dependency in that project is requiring the local package with a specific version you currently need to also have that dependency with a local repository, where it requires the dev-version of the local-package and you need to set that repository in the composer.json of the project to the dev-version, too. This can get very messy if you have many dependencies requiring a specific package and you just want to test a change in a method together with that specific project.

My idea is to add a specific argument to composer require, so that you can skip the version-check of the dependencies, so that you do not have to create multiple local repositories all at once and being in need to link them.

I specifically expect a argument like --skip-dependency-version-check, so that following would happen in the given scenario:

- I have a package called test
- I have a second package called using-test, which has a dependency of test
- And I have a project, which requires both test and using-test (Not as dependencies of each other, project would also use methods of test)

When I would do a local repository for test, as I wanted to change a method and add the repository and after that run the command ``composer require "test @dev" --skip-dependency-version-check`` I would expect, that it would install fine, even when using-test would require a non-dev version of the package test.

**Comment by Seldaek** [comment]
That's exactly what inline aliases are for IMO https://getcomposer.org/doc/articles/aliases.md#require-inline-alias
