### ISSUE TITLE
Memory exhausted even with COMPOSER_MEMORY_LIMIT or memory_limit=-1

### ISSUE THREAD

**Issue by armetiz** [composer/composer#10674]
Output of `composer diagnose`:

![Capture d’écran 2022-03-30 à 16 08 16](https://user-images.githubusercontent.com/1119250/160854992-f3463abb-0af5-4fe1-8733-e0626d3d504a.png)

When I run this command: `COMPOSER_MEMORY_LIMIT=-1 php -d memory_limit=-1 /usr/local/bin/composer install --optimize-autoloader --no-dev --classmap-authoritative --no-interaction -vvv`

* Composer version 2.2.10 2022-03-29 21:55:35
* PHP 7.4.26
* Symfony 5.4.5

I get the following output:

```
> post-install-cmd: Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "config/parameters.yml" file
> post-install-cmd: @auto-scripts
> auto-scripts: Symfony\Flex\Flex->executeAutoScripts
Executing script cache:clear
Executed script cache:clear  [KO]
 [KO]
Script cache:clear returned with error code 255

Error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 32768 bytes)
```

**Comment by Seldaek** [comment]
The memory issue happens within the cache:clear command, which runs as an external process so it does not inherit your new memory limit. This is a symfony issue really.

**Comment by armetiz** [comment]
Hi @Seldaek 

Thank you.

I was thinking that composer forward configured memory_limit to any external process.

The documentation does not mention memory management: https://github.com/composer/composer/blob/main/doc/articles/scripts.md

Do you have any clue to deal with this problem?

**Comment by Seldaek** [comment]
Change your default memory limit in php.ini? 

Sorry, not sure what else.. maybe @nicolas-grekas has a clue on the symfony/flex side what can be done.

**Comment by armetiz** [comment]
Thank you guys for your answer. I'll change memory_limit on CLI to -1.
