### ISSUE TITLE
 Composer 2.3.0 break symfony 3.4 app 

### ISSUE THREAD

**Issue by cbastienbaron** [composer/composer#10671]
### Solution / workaround: 

For such cases where script handlers are so old and unmaintained and won't be fixed by third parties, if you cannot fix them yourself I would highly recommend storing a Composer 2.2 [composer.phar](https://getcomposer.org/download/latest-2.2.x/composer.phar) in your old project directory. You can then use it with `php composer.phar install` or similar to install legacy projects while still having a newer Composer installed globally on the machine for other projects.

For more workaround suggestions read the answers below.

### Original issue below

Hi guys,

we use deployerphp, and we dl for each release the last release of composer for an sf app (3.4) and we encounter this error 

here for 2.3.0 , (fyi no issue with 2.2.9 )

```bash
> symfony-scripts: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap        
                                                                                                   
  In Process.php line 143:                                                                          
                                                                                                   
    [TypeError]                                                                                    
    Argument 1 passed to Symfony\Component\Process\Process::__construct() must                      
    be of the type array, string given, called in /var/www/example.com/releases/20220330124916/vendor/sensio/distribution-bundle/Composer/Scrip                    
    tHandler.php on line 310                                   
```                                     

```bash
Exception trace:                                                                                  
    at phar:///var/www/example.com/releases/20220330124916/composer.phar/vendor/symfony  
  /process/Process.php:143                                                                          
   Symfony\Component\Process\Process->__construct() at /var/www/example.com/releases/20  
  220330124916/vendor/sensio/distribution-bundle/Composer/ScriptHandler.php:310                    
   Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::executeBuildBootstrap() at /var/www/example.com/releases/20220330124916/vendor/sensio/distribution-bundle/Composer/ScriptHa  
  ndler.php:88                                                                                      
   Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap() at phar:///var/www/example.com/releases/20220330124916/composer.phar/src/Composer/EventDispatcher/EventDis  
  patcher.php:391                                                                                  
   Composer\EventDispatcher\EventDispatcher->executeEventPhpScript() at phar:///var/www/example.com/releases/20220330124916/composer.phar/src/Composer/EventDispatcher/EventDispatcher.  
  php:248                                                                                          
   Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///var/www/example.co  
  m/releases/20220330124916/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:108      
   Composer\EventDispatcher\EventDispatcher->dispatch() at phar:///var/www/example.com/  
  releases/20220330124916/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:228        
   Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///var/www/example.co  
  m/releases/20220330124916/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:125      
   Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar:///var/www/example.com/releases/20220330124916/composer.phar/src/Composer/Installer.php:372                        
   Composer\Installer->run() at phar:///var/www/example.com/releases/20220330124916/com  
  poser.phar/src/Composer/Command/InstallCommand.php:137                                            
   Composer\Command\InstallCommand->execute() at phar:///var/www/example.com/releases/2  
  0220330124916/composer.phar/vendor/symfony/console/Command/Command.php:298                        
   Symfony\Component\Console\Command\Command->run() at phar:///var/www/example.com/rele  
  ases/20220330124916/composer.phar/vendor/symfony/console/Application.php:1015                    
   Symfony\Component\Console\Application->doRunCommand() at phar:///var/www/example.com  
  /releases/20220330124916/composer.phar/vendor/symfony/console/Application.php:299                
   Symfony\Component\Console\Application->doRun() at phar:///var/www/example.com/releas  
  es/20220330124916/composer.phar/src/Composer/Console/Application.php:334                          
   Composer\Console\Application->doRun() at phar:///var/www/example.com/releases/202203  
  30124916/composer.phar/vendor/symfony/console/Application.php:171                                
   Symfony\Component\Console\Application->run() at phar:///var/www/example.com/releases  
  /20220330124916/composer.phar/src/Composer/Console/Application.php:130                            
   Composer\Console\Application->run() at phar:///var/www/example.com/releases/20220330  
  124916/composer.phar/bin/composer:83                                                              
   require() at /var/www/example.com/releases/20220330124916/composer.phar:29            
                                                                                                   
  install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev]  
  [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [-v|vv|vvv|--verbose]  
   [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader  
  -prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-r  
  eqs] [--] [<packages>...]                                                                        
                                                                                                   

Exception trace:
  at phar:///usr/local/bin/dep/src/Ssh/Client.php:103
 Deployer\Ssh\Client->run() at phar:///usr/local/bin/dep/src/functions.php:304
 Deployer\run() at phar:///usr/local/bin/dep/recipe/deploy/vendors.php:15
 Deployer\Deployer::Deployer\{closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Task.php:105
 Deployer\Task\Task->run() at phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php:60
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:144
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:924
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/src/Console/Application.php:133
 Deployer\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:265
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:141
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:326
 Deployer\Deployer::run() at phar:///usr/local/bin/dep/bin/dep:136
 require() at /usr/local/bin/dep:4

```

any idea ? 
thanks guys we <3 you ! :)

**Comment by stof** [comment]
The script handler of Sensio\Bundle\DistributionBundle does not seem to be compatible with the newer version of symfony/process shipped in composer 2.3

This is something to be fixed in Sensio\Bundle\DistributionBundle. alternatively, you could drop the `Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap` script entirely (IIRC, the bootstrap file that it generates does not bring any performance benefit on PHP 7+)

**Comment by cbastienbaron** [comment]
Thanks u @stof , 

> The script handler of Sensio\Bundle\DistributionBundle does not seem to be compatible with the newer version of symfony/process shipped in composer 2.3

yup we have couple of scripts which use "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::doSomthing" all ko. 
quick fix for us, is to simlply bring composer 2.2.9 during the time of upgrade sf deps before play with 2.3.0

**Comment by jjmackow** [comment]
I was having similar issues today (march 22nd, release day of 2.3.0 and 2.3.1) while trying to build Drupal 9.3.9 with composer 2.3.1 as well as 2.3.0. (I was getting issues regarding a file called autoload.php).
simply run
composer self-update 2.2.9
in the meanwhile to downgrade to the march 15th, 2022 release.

**Comment by davidteal** [comment]
We've also had this issue in a few of our projects. Similar to @jjmackow, until we remove the sensio/distribution-bundle dependency, our fix was to either do:

`composer self-update 2.2.9`

or pass in the version to the Composer installer

`--version=2.2.9`

**Comment by hkorik** [comment]
Similar issue with our setup but another dependency. We had to hardcode staying on composer `2.2.x` release versions. Using any of the composer `2.3.x` releases produced the following error:

```
In ProcessBuilder.php line 269:
                                                                                
  [Error]                                                                       
  Call to undefined method Symfony\Component\Process\Process::setCommandLine()  
                                                                                

Exception trace:
  at /var/www/html/docroot/themes/custom/emulsify/pattern-lab/vendor/symfony/process/ProcessBuilder.php:269
 Symfony\Component\Process\ProcessBuilder->getProcess() at /var/www/html/docroot/themes/custom/emulsify/pattern-lab/vendor/alchemy/zippy/src/Adapter/VersionProbe/AbstractTarVersionProbe.php:48
 Alchemy\Zippy\Adapter\VersionProbe\AbstractTarVersionProbe->getStatus() at /var/www/html/docroot/themes/custom/emulsify/pattern-lab/vendor/alchemy/zippy/src/Adapter/AbstractAdapter.php:144
 Alchemy\Zippy\Adapter\AbstractAdapter->isSupported() at /var/www/html/docroot/themes/custom/emulsify/pattern-lab/vendor/alchemy/zippy/src/Zippy.php:154
 Alchemy\Zippy\Zippy->getAdapterFor() at /var/www/html/docroot/themes/custom/emulsify/pattern-lab/vendor/pattern-lab/core/src/PatternLab/Fetch.php:84
 PatternLab\Fetch->fetchStarterKit() at /var/www/html/docroot/themes/custom/emulsify/pattern-lab/vendor/pattern-lab/core/src/PatternLab/InstallerUtil.php:561
 PatternLab\InstallerUtil::promptStarterKitInstall() at /var/www/html/docroot/themes/custom/emulsify/pattern-lab/vendor/pattern-lab/core/src/PatternLab/InstallerUtil.php:634
 PatternLab\InstallerUtil::packagesInstall() at /var/www/html/docroot/themes/custom/emulsify/pattern-lab/vendor/pattern-lab/core/src/PatternLab/InstallerUtil.php:529
 PatternLab\InstallerUtil::postUpdateCmd() at /var/www/html/docroot/themes/custom/emulsify/pattern-lab/core/src/PatternLab/Installer.php:92
 PatternLab\Installer::postUpdateCmd() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:391
 Composer\EventDispatcher\EventDispatcher->executeEventPhpScript() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:248
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:125
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar:///usr/local/bin/composer/src/Composer/Installer.php:372
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:270
 Composer\Command\CreateProjectCommand->installProject() at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:167
 Composer\Command\CreateProjectCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:1015
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:334
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:130
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:83
 require() at /usr/local/bin/composer:29

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package> [<directory> [<version>]]]
```

**Comment by trsteel88** [comment]
Same issue here.

**Comment by Seldaek** [comment]
@hkorik yes that would require changes in the PatternLab repo (https://github.com/pattern-lab/patternlab-php/tree/master I guess?) it seems, same as SensioDistributionBundle it is way outdated though and not maintained anymore it seems.

For such cases I would highly recommend storing a Composer 2.2 [composer.phar](https://getcomposer.org/download/latest-2.2.x/composer.phar) in these old project dirs, so you can use that to install them, but still have a newer composer installed on the machine for other projects. Ideally you would migrate away from those outdated projects but I know in reality this is sometimes hard or impossible.

**Comment by WillyBaldy** [comment]
We've also got the issue, thanks to Composer it gave us the kick in the butt needed to finally upgrade our old Symfony 3.4 projects to 5.4, in the next sprint or two 😊 It's mainly the Assetic part that's the real pain.

**Comment by gggeek** [comment]
Same happened to our projects, and I fear the breackage comes not only from SensioDistributionBundle, but from other deps as well, which most likely it is will not get fixed any time soon.

We worked around that by hardcoding the installation of composer in the build pipelines to use `2.2.10`, but it seems that it is not possible to pass version `2.2` or `2.2.*` as parameter to `composer-setup.php`.

@Seldaek Q1: would it make sense to make `composer-setup.php` smarter, so that it allows wildcard matching for selecting the version to install?
And Q2: would it make sense to allow defining a "require-composer" version in the composer file itself, so that composer would be able to check it and bail out immediately if there is a version mismatch? That tag could then be used by other tooling in the future for eg. installing the correct composer version...

**Comment by stof** [comment]
> And Q2: would it make sense to allow defining a "require-composer" version in the composer file itself,

This is possible in composer 2.2+ by specifying a requirement on the `composer` package. And `composer-runtime-api` may be used as well for broader support (but with less precise versions, as composer patch versions don't update the runtime-api version, and minor versions might not always do it).

**Comment by Seldaek** [comment]
Right, just to expand on @stof's answer, that'd look something like:

```
{
    "require": {
        "composer": "2.2.*"
    }
}
```

@gggeek SensioDistributionBundle is unlikely to be fixed, but as per https://github.com/composer/composer/issues/10671#issuecomment-1083120520 I think it can fairly easily be removed from a project even without upgrading Symfony.

**Comment by WillyBaldy** [comment]
> @gggeek SensioDistributionBundle is unlikely to be fixed, but as per [#10671 (comment)](https://github.com/composer/composer/issues/10671#issuecomment-1083120520) I think it can fairly easily be removed from a project even without upgrading Symfony.

We're using the ::clearCache and ::installAssets so it's not that simple.

**Comment by Seldaek** [comment]
You can replace these with direct calls to `app/console`, something like `"scripts": {"post-update-cmd": ["app/console cache:clear"]}`. The distribution bundle indirection adds no value there IIRC.

**Comment by gggeek** [comment]
@stof thanks!

That prompted me to read closely the info in https://getcomposer.org/doc/articles/composer-platform-dependencies.md

Given the fact that the code which stopped working bc of composer 2.3, in class `Sensio\Bundle\DistributionBundle\Composer\ScriptHandler` relies on Composer classes definitions and on Composer being the one invoking its methods, I would say that it does rely on the "composer api" but not on the "composer-runtime-api".

The breackage in this case seems to have happened because that code also makes use of Symfony/Process, and Composer now bundles a newish version of that, which is not compatible any more with DistributionBundle.
I did check the requirements of  sensio/distribution-bundle, and, in the version which we have installed, it does state `"symfony/process": "~2.2"`, so it seems to be doing the right thing (and indeed, we get symfony/process 2.8 installed).

I wonder if the issue here is not so much about whether the version of `composer-plugin-api` should have been bumped, but rather stems from the fact that plugins which are run in-process during the "scripts" phase will have a very hard time loading their expected versions of the Symfony components if Composer ships a different version of the same (short of having Composer do some crazy magic with autoload paths and class aliasing...). Iirc that was already discussed in other tickets, but I don't recall the final decision taken... (on a side note: I always thought that running "composer scripts" in process was too risky, and that running them as forked php processes is a better solution)

**Comment by gggeek** [comment]
@Seldaek thanks for the tip, but most of the code I deal with also uses `eZ\Bundle\EzPublishLegacyBundle\Composer\ScriptHandler`, which in turns extends `Sensio\Bundle\DistributionBundle\Composer\ScriptHandler`, so not as easy to rip out

**Comment by ArthurJam** [comment]
+1

**Comment by Seldaek** [comment]
Closing, hoping most affected people saw this by now.

**Comment by codedokode** [comment]
I think that this is not just a problem with an old version of Symfony, but a larger scale problem with Composer scripts and event handlers in general. Scripts and event handlers cannot expect that any classes from third party libraries will be of versions that are specified in `composer.json`/`composer.lock`. They can only expect that Composer API will match required version and nothing more. So, for example, a script or event handler might be written for library version 1.x, but be provided with a version 9.x.

I think that you should explicitly mention it in docs here: https://getcomposer.org/doc/articles/scripts.md . For example, something like this: 

> Scripts or event handlers implemented as PHP classes **should not** use any third-party libraries because Composer might provide versions different from specified in `composer.json` and incompatible with a handler. If you need to use a third-party library, it is recommended to implement a script or event handler as a CLI command.

@stof 
> In-process scripts indeed have to support the version of the component shipped in the composer phar.

One needs a time machine to support all versions of libraries that Composer might use in future.
