### ISSUE TITLE
Specifying `--version` on the command line when installing doesn't install the specified version.

### ISSUE THREAD

**Issue by bensebborn** [composer/composer#10673]
Specifying `--version` on the command line when installing doesn't install the specified version.

`php -c /etc/php-cli.ini /tmp/composer --install-dir=/usr/local/bin --filename=composer --version=2.2.10`

`composer -V`
`Composer 2.3.0 2022-03-30 11:15:36`

**Comment by Seldaek** [comment]
I don't think it is.. Please make sure what that /tmp/composer is, because I cannot reproduce this:

```
php -c /etc/php/8.0/cli/php.ini web/installer --install-dir=./tmp --version=2.2.8
All settings correct for using Composer
Downloading...

Composer (version 2.2.8) successfully installed to: /var/www/getcomposer/tmp/composer.phar
```

**Comment by stof** [comment]
@bensebborn please run `sha384sum /tmp/composer`. If this file is indeed the installer, the checksum should be `906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8`
