### ISSUE TITLE
Invalid call to `isMatch` in `RootPackageLoader`

### ISSUE THREAD

**Issue by carlalexander** [composer/composer#10689]
I've been running into this error with the latest version of Composer in `RootPackageLoader`:

>Composer\Pcre\Preg::isMatch(): Argument #3 ($matches) must be of type ?array, bool given, called in RootPackageLoader.php on line 247

This is [the code](https://github.com/composer/composer/blob/main/src/Composer/Package/Loader/RootPackageLoader.php#L243-L255) in question:

```php
$match = false;
foreach ($constraints as $constraint) {
    if (Preg::isMatch('{^[^@]*?@('.implode('|', array_keys($stabilities)).')$}i', $constraint, $match)) {
        $name = strtolower($reqName);
        $stability = $stabilities[VersionParser::normalizeStability($match[1])];

        if (isset($stabilityFlags[$name]) && $stabilityFlags[$name] > $stability) {
            continue;
        }
        $stabilityFlags[$name] = $stability;
        $match = true;
    }
}
```

It seems like this is an improper call to `isMatch`. `match` is never an array or null on the first call to the method.

**Comment by Seldaek** [comment]
I don't know which version of composer you are using, but this was fixed in https://github.com/composer/composer/commit/18246212db7103d0a2688febcc336f77183275ee already

**Comment by carlalexander** [comment]
You're @Seldaek. It was my bad. I thought I had 2.3.3 installed, but I didn't. Sorry 😞
