### ISSUE TITLE
Composer Installer does not allow specifying LTS version

### ISSUE THREAD

**Issue by Brandon0** [composer/composer#10682]
With the newest 2.3.X releases breaking on systems running older PHP versions, it would be nice to be able to programmatically install the latest LTS release. Using the installer tool provided, when I run this command:

```
php installer.php --version=2.2.x
```

I get the following output:

```
The defined install version (2.2.x) does not match release pattern.
```

And I expected this to happen:
The latest 2.2.X LTS version to be installed (currently 2.2.10).

Using the latest installer tool:

```
❯ php -r "echo hash_file('sha384', 'installer.php') . PHP_EOL;"
906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8
```

Current workaround is to pin composer to the 2.2.10 version specifically.

**Comment by jrfnl** [comment]
Just came here to open exactly the same issue.

Would be great if the `self-update` command would either accept `2.2` as a version and get the latest in the 2.2.x series or if there would be a `--2lts` option or something like it.

**Comment by Seldaek** [comment]
Yes I plan to add a `--2.2` flag to both installer and self-update.

**Comment by jrfnl** [comment]
@Seldaek I knew you were awesome and just confirmed it once again 💗

**Comment by Seldaek** [comment]
Fixed for self-update in https://github.com/composer/composer/commit/956d44c339a836f6a649dd49c06cdbd030c36712 - available as of 2.2.11 / [2.3.3](https://github.com/composer/composer/releases/tag/2.3.3).

I'll tackle the installer script some other time.

**Comment by jrfnl** [comment]
Much appreciated!

**Comment by Seldaek** [comment]
OK now the installer script finally has --2.2 as well.
