### ISSUE TITLE
I hope to remove the political statement

### ISSUE THREAD

**Issue by augushong** [composer/composer#10686]
I hope to remove the political statement.
Open source projects should not be mixed with politics. As individuals, you can express your position on the social platform, but please don't include it in the open source project.
In the open source project, political issues have no good impact on the development of the project.
People from all over the world are involved in open source projects, which cannot be separated. Once the open source project has a position, tendency and standing in line, it will only harm the whole community and cause division and waste.

Node. JS rolled back inappropriate banner:
https://github.com/nodejs/nodejs.org/pull/4467

**Comment by Seldaek** [comment]
Maybe read https://steemit.com/programming/@crell/free-software-is-political

**Comment by augushong** [comment]
But political issues are complex.
Such a statement is easy to take advantage of.
This is not necessarily a view of justice, it is only rendered as justice.
This will only hurt more people and will not solve any problems.
Politics can't make the world a better place, but open source can.
