### ISSUE TITLE
bin/compile is broken on Windows

### ISSUE THREAD

**Issue by mvorisek** [composer/composer#10693]
with latest `main` I see:

```
Failed to compile phar: [RuntimeException] These files were unexpectedly added to the phar, make sure they are excluded or listed in $extraFiles:
array (
  0 => 'C:\\...\\forks\\composer\\src\\Composer/../../vendor\\phpstan\\phpstan-deprecation-rules\\rules.neon',
  1 => 'C:\\...\\forks\\composer\\src\\Composer/../../vendor\\phpstan\\phpstan-phpunit\\extension.neon',
  2 => 'C:\\...\\forks\\composer\\src\\Composer/../../vendor\\phpstan\\phpstan-phpunit\\rules.neon',
  3 => 'C:\\...\\forks\\composer\\src\\Composer/../../vendor\\phpstan\\phpstan-phpunit\\stubs\\InvocationMocker.stub',
  4 => 'C:\\...\\forks\\composer\\src\\Composer/../../vendor\\phpstan\\phpstan-phpunit\\stubs\\MockBuilder.stub',
  5 => 'C:\\...\\forks\\composer\\src\\Composer/../../vendor\\phpstan\\phpstan-phpunit\\stubs\\MockObject.stub',
  6 => 'C:\\...\\forks\\composer\\src\\Composer/../../vendor\\phpstan\\phpstan-phpunit\\stubs\\Stub.stub',
  7 => 'C:\\...\\forks\\composer\\src\\Composer/../../vendor\\phpstan\\phpstan-phpunit\\stubs\\TestCase.stub',
  8 => 'C:\\...\\forks\\composer\\src\\Composer/../../vendor\\phpstan\\phpstan-strict-rules\\rules.neon',
  9 => 'C:\\...\\forks\\composer\\src\\Composer/../../vendor\\phpstan\\phpstan-symfony\\extension.neon',
...
```

when I run `compile` from `bin` dir

**Comment by Seldaek** [comment]
Can you try again with latest see if https://github.com/composer/composer/commit/d7f07339595d12bb9ac945b1c74fc832b7710f3c highlights an issue?

**Comment by mvorisek** [comment]
I run the compile /wo any shell commands as my php env. does not support them for security reasons.

see https://github.com/mvorisek/composer/commit/73dc9d8de77bfc219ea86cd1e19211624d5903f2

run with:
```
cd bin && php -d phar.readonly=0 .\compile.php
```

and uncomment the problematic line https://github.com/mvorisek/composer/commit/73dc9d8de77bfc219ea86cd1e19211624d5903f2#diff-df7082676f4891241241b23e47108e77b204ff234200bdc4203477d672e1554cR146

the phpstan files should probably be ignored somewhere in https://github.com/mvorisek/composer/commit/73dc9d8de77bfc219ea86cd1e19211624d5903f2#diff-df7082676f4891241241b23e47108e77b204ff234200bdc4203477d672e1554cR100

**Comment by Seldaek** [comment]
Sorry but no. If you want to tweak things it's on you to tweak things correctly. Our build script works fine, and the Compiler class expects a --no-dev install to be done before calling it.

Frankly your OP not mentioning that you run a completely separate build process is a waste of my time and really does not make me want to help any further. I don't know what you are up to, but I don't think it's my responsibility to help out anyone doing anything with this repo.
