### ISSUE TITLE
CLI colors are broken

### ISSUE THREAD

**Issue by mvorisek** [composer/composer#10691]
the following command in Dockerfile

```
RUN mkdir t && (cd t && composer require phpunit/phpunit) && rm -r t/
```

produces:

![image](https://user-images.githubusercontent.com/2228672/161342575-a7aee17e-ba69-4706-984c-cb9b1d4ca636.png)

I belive the font colors should not be random between gray and red.

**Comment by Seldaek** [comment]
I have no idea what's causing this, sorry nor what version of composer you're using. Sorry but I'm not offering docker support, if you figure out the root cause I am happy to help with a fix.

**Comment by mvorisek** [comment]
I can reproduce it consistently with official PHP Docker images, on Debian and Alpine and PHP 7.4 - 8.1.

Dockerfile: https://github.com/mvorisek/image-php/blob/master/data/8.1-debian/Dockerfile#L57
CI: https://github.com/mvorisek/image-php/runs/5796737502?check_suite_focus=true#step:6:103

to repro locally, here is a simplified DockerFile:

```
FROM ghcr.io/mvorisek/image-php:8.1
RUN php --version
RUN composer diagnose
RUN mkdir t && (cd t && composer require phpunit/phpunit)
```

**Comment by Seldaek** [comment]
Yeah as I said I am not supporting docker tho, sorry, I have no interest in wasting my time on that.

I don't know what docker build does to the output, maybe you rather use --no-ansi to suppress colors entirely?

**Comment by mvorisek** [comment]
closing here, probably a Symfony issue
