### ISSUE TITLE
Semantic versioning of composer/composer documentation

### ISSUE THREAD

**Issue by exteon** [composer/composer#10698]
I have a plugin that requires `"composer/composer": "^2.2"`.

With `2.3.0`, and https://github.com/composer/composer/commit/84f0f191122af73039555a3a9381a1a408131422 the signature of `\Composer\Factory::createComposer()` was change to return `|PartialComposer`. This obviously breaks any code using this interface.

I couldn't find any specification regarding `composer/composer` versioning style (if there is such someplace I couldn't find it).

I deduce that "2" refers to frontend major version (compatibility of the `composer` command itself) and "2.3" actually acts as codebase major version and I should have `"composer/composer": "~2.2.0"`. ? Is this correct? Can it be specified somewhere?

**Comment by exteon** [comment]
Thanks for the comprehensive reply,

The issue occurred along these lines:  I have a special type of packages that can have mutual dependencies and a load sequence must be generated in an IoC fashion. I use `createComposer` to create a "partial" Composer instance to inspect the required packages' dependencies. True, it would have probably been simpler and faster to just parse the `composer.json` files, but I went this way for maximum stability and not duplicating Composer internal conventions.

All this already has only support for PHP 8+, so everything is strong typed. So the created `Composer` was marshaled around strong-typed. When it changed type to `PartialComposer` it obviously broke strict type checks. Speaking of this scheme, seems a bit of an anti-pattern that two semantically unrelated classes should be implementing partially a common interface with an implicit convention... I would have expected that the change would have rather produced a `PartialComposerInterface` <- `ComposerInterface` abstraction that is returned. But never mind evangelism.

I asked about the idea about `~2.2.0` because I don't mind going around the yard and doing a manual composer update. But the problem with `^2.2.0` is that a simpler `composer update` made everything crash (including any subsequent `composer` commands). Not a good place to be in. So I'm asking about `~2.2.0` as a synonim to "never a composer update command will crash my plugin depending on composer". I don't mind publishing a dependency update every now and then after I tested everything works, the problem is the system unexpectedly failing. So I would even be willing to nail it down to `=2.2.0`, but usually patch version is for bugfixes and I'm not really looking forward to publish dependency updates for bugfixes :)

I use a local `composer/composer` because of the ancient locked-in Symfony in the phar composer. I need a more up-to-date Symfony environment for my plugin, so I found this way to work reasonably.  It also removes a dependency on a global-versioned tool, which I find actually reassuring for, i.e. a deployment server with multiple projects. In this case, a `composer self-update` would have broken all projects at the same time. But `bin/composer update` broke just one :)

I hope all this context helps describe my use case. I know it's a rarely done thing, but at the same time I imagine i.e. Symfony and Laravel loaders beat around the same bush, more or less, the use cases are not fundamentally different, so I hope my perspective helps a bit.

**Comment by stof** [comment]
A plugin will have to run in the composer process anyway, so you must be compatible with the versions used by composer.

**Comment by Seldaek** [comment]
> I use createComposer to create "partial" Composer instances to inspect the required packages' dependencies.

Yeah you should definitely use Composer\Package\ArrayLoader for this purpose, not load a Composer instance that's absolutely overkill.

For the vendor-dir you should use the Plugin-provided Composer instance to `->getInstallationManager()->getInstallPath($package)` IMO.

Anyway if you want for safety to require ~2.3.0 going forward and then bump minor bumps after testing them, for sure that sounds reasonable to me. Even though 2.3.0 was a bit special and changing more than usual, there is always a chance that new features/small changes inadvertently break such deep integrations, so if you want to be on the safe side pinning to patch is better for sure.

**Comment by exteon** [comment]
> Yeah you should definitely use Composer\Package\ArrayLoader for this purpose, not load a Composer instance that's absolutely overkill.

Thanks, I'll give it a try, haven't stumbled on that.

> For the vendor-dir you should use the Plugin-provided Composer instance to `->getInstallationManager()->getInstallPath($package)` IMO.

I do that, but the idea is that I'm trying to get the path to the nested 

vendor/some/package/**vendor** 

which only exists because `vendor/some/package` is a symlink created because on dev I have `path` type repositories for my own packages. The project root composer should be completely oblivious of the nested `vendor`, which is just an artefact of the symlinked package and only "exists" when `some/package` is the root package. 

Am I missing something? Is there any way to get the symlinked package's `vendor` path (not the project's `vendor` path) without re-instancing a composer (or `ArrayLoader` as you pointed out) rooted on `vendor/some/package` ? 

The reason I'm doing this is two-fold: 
- I run some packaging/syncing tools independent of changes being published through the VCS, and I need to prune the nested vendor dirs or I end up packaging an insanely long deep-nested file log
- PHPStorm still has some problems regarding the same symlink structure (basically indexing forever equivalent symlinks), so until that is fixed, I also have a tool that generates a PHPStorm config to properly exclude nested `vendor` dirs

**Comment by Seldaek** [comment]
> Am I missing something? Is there any way to get the symlinked package's vendor path (not the project's vendor path) without re-instancing a composer (or ArrayLoader as you pointed out) rooted on vendor/some/package ?

No I think in that case you may have to load the package as a Composer instance indeed.
