### ISSUE TITLE
Using composer induces heart problems for some people

### ISSUE THREAD

**Issue by kalmargabor** [composer/composer#10695]
Please implement a command line option, e.g. --twitterize, so one can choose, if they want to see unrelated info about the world, when they are developing on their computers and are in the zone. This option could fetch the trending #StandWith{your-placeholder-here} from Twitter.
I think this could help some people with heart problems, who are trying to keep their peace of mind in this challenging world.
Forking a twitterless composer could implement a security issue in the future, so I don't think that could be an option for the info-challenged people like me.

**Comment by Seldaek** [comment]
Sorry no
