### ISSUE TITLE
Cannot use specified version of symfony/console in composer run scripts

### ISSUE THREAD

**Issue by upyx** [composer/composer#10708]
Hi there :wave: 

There is a cool [feature](https://getcomposer.org/doc/articles/scripts.md#defining-scripts), that's used for run custom PHP code with `composer run-script`. The Composer internally uses the `symfony/console` component of *some* version. So when classes of `symfony/console` used in those scripts, they are loaded from `composer.phar` instead of the `vendor` direcotry.
It's quite unexpectable. And it breaks code *after updating composer*.

I think adding some namespace prefix like it does [easy-coding-standard](https://github.com/symplify/easy-coding-standard/blob/main/src/Application/EasyCodingStandardApplication.php) would be good solution.

**Comment by stof** [comment]
if you use in-process scripts (where Composer calls some PHP callable directly), it indeed has to be compatible with code shipped inside the composer phar instead of using solely the vendor folder.
In that regard, sub-process scripts (where Composer calls some command in a subprocess) are much more robust against changes in the composer phar.

**Comment by upyx** [comment]
Hmm... Sounds reasonable. Nevertheless, Composer was updated in minor version and it broke my "in-process" script. How is it possible to do that scripts are compatible with composer phar?

I think about some options:

- Discribe in documentation how to make "in-process" scripts in propper way.
- Run the scripts in separate process (my favorite one).
- Deprecate and then remove that feature (the simplest way).

**Comment by stof** [comment]
hmm, this documentation page about scripts should indeed describe the fact that PHP callbacks run in the same process than composer and so must be compatible with composer dependencies. And the difference is that Composer 2.3+ has updated the bundled dependencies (thanks to dropping support for old PHP versions, which were forcing to use old versions of symfony/console).

**Comment by upyx** [comment]
Looks like some backward incompatible changes was done without changing the major part of the Composer version. However, we know the exect version and can check it in scripts.

I can't find in documentation that description. The word "callback" hits that the process is the same, but it's not clear.

Really, is the feature usefull while it's so fragile?

**Comment by Seldaek** [comment]
If your code is open source  and you need help migrating please point me to it I'm happy to help with any specific question you may have. This upgrade was indeed bound to break a few use cases, and I'm sorry about that, but it's a necessary evil to allow us to move forward with our (very conservative and minimal) dependencies.

**Comment by upyx** [comment]
@stof I've tried to use interactive shell with `@php -a` in Composer, and it works well! So using callbacks is edge case for interacting with Composer itself (and Composer's dependencies). The most common way to run PHP scripts it's just running it! :rofl: 

@Seldaek I've got what I need. Thank you for your great work! :handshake:
