### ISSUE TITLE
Docker Alpine Linux ARM Segmentation faults on all composer versions below "latest" version

### ISSUE THREAD

**Issue by allexivan** [composer/composer#10709]
All my builds on all legacy php versions (7.0, 7.1) that are using version a composer version under 2.3 are failing with this error:

Segmentation fault (core dumped)

This started to happen today, 5th of April.

It does not matter what is the contents of composer.json. it fails on over 20 different applications.

With the latest version of composer  on php 7.0 and 7.1:

`PHP Fatal error:  Declaration of Composer\IO\BaseIO::hasAuthentication($repositoryName) must be compatible with Composer\IO\IOInterface::hasAuthentication(string $repositoryName) in phar:///root/composer.phar/src/Composer/IO/BaseIO.php on line 20`

**Comment by Seldaek** [comment]
Composer 2.3 requires PHP 7.2.5+ so the failure there is expected. I guess we should add something to the bootstrap script to fail early and more clearly.

The segfault I have no idea what would cause that, nor why it would have started on April 5th given we did not release anything on that day. I suspect it's something in your environment.

**Comment by ilnurshax** [comment]
Same problem on our project with php7.1 :(

**Comment by allexivan** [comment]
php-curl extension was causing Segmentation Fault. I removed extensions one by one and after removing this, it worked. Not sure why, and why it started to happen suddenly.
