### ISSUE TITLE
Self-upgrade from 2.3.3 to 2.3.4 doesn't work if `--2.2` has been used previously

### ISSUE THREAD

**Issue by jrfnl** [composer/composer#10719]
### Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (2.3.3 => 2.3.4)
Composer version: 2.3.3
PHP version: 7.4.28
PHP binary path: C:\wamp\bin\php\php7.4.28\php.exe
OpenSSL version: OpenSSL 1.1.1l  24 Aug 2021
cURL version: 7.70.0 libz 1.2.11 ssl OpenSSL/1.1.1l
zip: extension present, unzip present, 7-Zip not available
Exit code is 0
```

### When I run this command:

```
composer --version
composer self-update
```

### I get the following output:

```
$ composer --version

Composer version 2.3.3 2022-04-01 22:15:35

$ composer self-update

Warning: You forced the install of 2.2.11 via --2.2, but 2.3.4 is the latest stable version. Updating to it via composer self-update --stable is recommended.
Upgrading to version 2.2.11 (2.2.x channel).

Use composer self-update --rollback to return to version 2.3.3
Exit code is 0
```

### And I expected this to happen:

That Composer would update to version 2.3.4.

I can force update to 2.3.4 by using `self-update --2` and that works fine.

After that the behaviour can't be reproduced anymore either, so I get the impression that "somewhere" the last option used with `self-update` is remembered on the system, even though I can't find it saved in any of the Composer global `composer.json`, `config.json` or `auth.json` files.

### To reproduce this consistently:

1. Make sure you are on Composer 2.3.3. If not currently, run `composer self-update 2.3.3`.
2. Run `composer self-update --2.2`
    => This will install Composer 2.2.11 correctly.
3. Run `composer self-update --rollback`
    => Now we're back at Composer 2.3.3 correctly
4. Run `composer self-update`
    => This will install Composer 2.2.11 again instead of installing Compose 2.3.4.

**Comment by Seldaek** [comment]
Yes we do persist the update channel choice to make sure you don't need to specify it every time. I guess the edge case is if you rollback the channel choice doesnt get rolled back but tbh I'm not sure that is a case worth fixing as it would need us to remember the channel for every backed up phar.

I'm hoping the warning is enough hint to allow people to resolve it on their own.

**Comment by jrfnl** [comment]
Thanks for the response @Seldaek! That at least explains it.

To me, this was completely unexpected behaviour and behaviour I hadn't encountered before, even though I regularly use the "channel selection" argument.
I suppose it doesn't persist if you use `snapshot` or `preview` ? Which I'd understand, but also makes the behaviour inconsistent.

It might just be a case of making sure people are made aware of this behaviour. What about each time the channel choice is "changed/remembered", a notification is shown in the screen saying that that channel has now been set as the default and to switch back to another channel, use .... ?

Something along the lines of:

```
Upgrading to version 2.2.11 (2.2.x channel).

The default updated channel has been set to 2.2 LTS. To return to the default channel, run `self-update --2`.
```

**Comment by Seldaek** [comment]
Yes printing something would make sense for sure, but note that snapshot /preview channels are also remembered.

**Comment by jrfnl** [comment]
> Yes printing something would make sense for sure, but note that snapshot /preview channels are also remembered.

Interesting. I'm wonder why I never noticed this behaviour before in that case.

**Comment by stof** [comment]
@jrfnl maybe because most of the time, the preview channel contains the same version that the stable channel (as most of the time, there is no active RC version)
