### ISSUE TITLE
curl error 6 while downloading https://repo.packagist.org/packages.json: Could not resolve host: repo.packagist.org

### ISSUE THREAD

**Issue by mvorisek** [composer/composer#10716]
see https://github.com/atk4/data/runs/5861526212?check_suite_focus=true#step:7:14

It seems on some status codes download is not retried.

**Comment by mvorisek** [comment]
thanks, another issue with code 7 detected - https://github.com/atk4/ui/runs/6012531457?check_suite_focus=true#step:12:16 - but the code 7 is already added, does the retry really work?

**Comment by Seldaek** [comment]
The retry happens silently unless you have `-vvv` so probably it just failed several times and then it stops retrying.

**Comment by mvorisek** [comment]
Would it be possible to some delay between retries? It seems like webservers are not restarted atomically and retries /wo delay fail all. We run hundreds pipelines per hour and even a percentually small failures are a significant number per day.

Like 2nd retry /wo delay, 50 ms for 3rd retry, 100 ms for 4th retry, ... and retry by default at least 8x (eg. 50, 100, 200, 400, 800, 1600 ms = about 3 seconds in total)

**Comment by Seldaek** [comment]
@mvorisek done in https://github.com/composer/composer/commit/da322643d6b107157b5cc2faf67c118016814871 although not with as many retries as this is I think a bit overkill, and we can't easily wait asynchronously - hopefully it helps tho.

**Comment by hasanamane** [comment]
how to solve  while downloading https://getcom/packages.json: Could not reso
  lve host: getcom

**Comment by mvorisek** [comment]
@Seldaek another code that seems to not be retried currently: https://github.com/atk4/ui/actions/runs/5012809144/jobs/8985193894#step:13:19

```
Loading composer repositories with package information
Info from [https://repo.packagist.org:](https://repo.packagist.org/) #StandWithUkraine
https://repo.packagist.org/
 could not be fully loaded (curl error 18 while downloading 
https://repo.packagist.org/p2/symfony/translation.json:
 Recv failure: Connection reset by peer), package information was loaded from the local cache and may be out of date

Error: curl error 18 while downloading https://repo.packagist.org/p2/symfony/translation.json: Recv failure: Connection reset by peer
In CurlDownloader.php line 365:
                                                                               
  curl error 18 while downloading 
https://repo.packagist.org/p2/symfony/trans
  
  lation.json: Recv failure: Connection reset by peer                          

```
