### ISSUE TITLE
`composer.json`: empty string in `autoloader-suffix`

### ISSUE THREAD

**Issue by WinterSilence** [composer/composer#10720]
My `composer.json`:
```json
{
    <...>
    "config": {
        "autoloader-suffix": ""
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
...
Checking composer version: OK
Composer version: 2.3.4
PHP version: 7.4.27
...
```

When I run this command: 

```
composer update -W -o
```

Actual result: `class ComposerAutoloaderInit... {...}`(`autoload_real.php`)

And I expected this to happen: `class ComposerAutoloaderInit {...}`

**Comment by Seldaek** [comment]
IMO having an empty suffix is a bad idea, as the point of the suffix is ensuring different projects get unique class names in case they coexist in the same process. So you can set it to your project's name or something if you like, but don't use empty.

Clarified this in https://github.com/composer/composer/pull/10725

**Comment by WinterSilence** [comment]
@Seldaek in your case, bad idea is same suffix for all loaders - no matter empty suffix or not. But in easy cases when uses single autoloader it's better then useless suffix.

**Comment by Seldaek** [comment]
I understand it's not what you wanted to hear, but I also don't see a huge problem with having this suffix set to something.. This classname shouldn't even appear anywhere in your code.

**Comment by WinterSilence** [comment]
@Seldaek 
> This classname shouldn't even appear anywhere in your code.

Nope. Case: project declare N autoloaders, your code in vendor package. Question: how you get Composer autoloader to get registered namespaces?

**Comment by WinterSilence** [comment]
@Seldaek I don't see a huge problem in omitted suffix in cases like my

**Comment by Seldaek** [comment]
I don't understand exactly your use case, but you can either use spl_autoload_functions() to retrieve it or use `$loader = include 'vendor/autoload.php';` as the ClassLoader is returned from the autoload.php.

**Comment by WinterSilence** [comment]
@Seldaek you right, I miss class of returned object
