### ISSUE TITLE
composer rollup?

### ISSUE THREAD

**Issue by ro0NL** [composer/composer#10733]
Hi,

I'd like to rollup my composer.json file every now and then, but found out it's manual labor :)

Given

```
$ cat composer.json | grep symfony/uid
        "symfony/uid": "^5.3",
$ composer show symfony/uid | grep version
versions : * v5.4.3
```

the idea is to then invoke `composer rollup` which would bump all constraints in composer.json. Thus in this case ` "symfony/uid": "^5.4",` (including patch release is fine also)

WDYT?

**Comment by stof** [comment]
to me, this looks like something that could be experimented with in a plugin first to me.

**Comment by Seldaek** [comment]
Duplicate of https://github.com/composer/composer/issues/7273 sort of
