### ISSUE TITLE
Feature Request: Add possibility to define which script should get forwarded arguments

### ISSUE THREAD

**Issue by alexander-schranz** [composer/composer#10734]
My `composer.json`:

```json
    "scripts": {
        "phpstan": [
            "@php bin/websiteconsole cache:warmup --env=dev",
            "@php vendor/bin/phpstan analyze"
        ],
    }
```

<details>

<summary>Output of `composer diagnose`:</summary>

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.3.5
PHP version: 8.1.2 - Package overridden via config.platform, actual: 8.1.4
PHP binary path: /opt/homebrew/Cellar/php/8.1.4/bin/php
OpenSSL version: OpenSSL 1.1.1m  14 Dec 2021
cURL version: 7.82.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1n
zip: extension present, unzip present, 7-Zip not available
```

</details>

When I run this command: 

```bash
composer phpstan -- src/Kernel.php
```

I get the following output: 

```bash
> @php bin/websiteconsole cache:warmup --env=dev 'src/Kernel.php'


  No arguments expected for "cache:warmup" command, got "src/Kernel.php".


cache:warmup [--no-optional-warmers]

Script @php bin/websiteconsole cache:warmup --env=dev handling the phpstan event returned with error code 1
```

And I expected this to happen:

The error totally make sense. It would be nice to have possibility to define which subcommand should get the arguments. E.g.:

```json
    "scripts": {
        "phpstan": [
            "@php bin/websiteconsole cache:warmup --env=dev",
            "@php vendor/bin/phpstan analyze {args}"
        ],
    }
```

Or something like:

```json
    "scripts": {
        "phpstan": {
            "beforeScripts": [
                "@php bin/websiteconsole cache:warmup --env=dev",
            ],
            "run": [
                "@php vendor/bin/phpstan analyze"
            ]
        },
    }
```

Also there are cases which make sense there that multple entries get the given argument e.g.:

```bash
composer fix -- src/Kernel.php
```

```json
    "scripts": {
        "fix": {
            "@rector",
            "@php-cs-fix"
        },
        "rector": "@php vendor/bin/rector process",
        "php-cs-fix": "@php vendor/bin/php-cs-fixer fix",
    }
```

What do you think about `{args}` or something similar maybe `{composer_args}` (avoid conflicts)  to make this possible?

**Comment by stof** [comment]
Well, when you pass arguments to a composer script, composer passes that argument to each of the executed commands.

**Comment by alexander-schranz** [comment]
@stof sure that is expected and this is as said not a bug just a proposal how this could be changed to be controlled which commands get the arguments and which not.

**Comment by stof** [comment]
your proposal is a BC break though, as it means that scripts would suddenly stop receiving arguments if they don't add `{args}` in their command

**Comment by alexander-schranz** [comment]
@stof I would keep the actually behaviour here if there is no `{composer_args}` all commands are getting the arguments, so it is possible without breaking anything here. Just is more a question if composer wants to support such a thing or not.

**Comment by Seldaek** [comment]
Yeah I can see the value, but I'm not sure how easy it would be to handle in a case like your `fix` example above, which then requires resolving scripts recursively first to then figure out if anything has `{composer_args}` in it. It's certainly doable but is it worth it?

**Comment by willrowe** [comment]
Maybe this could be done in an opt-in manner similar to adding `Composer\\Config::disableProcessTimeout` to disable the timeout?

I have run into an issue where I have a script that needs to be called with a single argument, but before running the application command it corresponds to, the composer dependencies need to be installed. I tried this:
```json
{
    "scripts": {
        "command-name": [
            "@composer install --no-dev",
            "@php app/Console/runner.php command-name"
        ]
    }
}
```

Unfortunately, since calling `composer run-script command-name first-argument` automatically forwards `first-argument` to `composer install --no-dev`, Composer interprets it as requesting a new package and throws the error `Invalid argument first-argument. Use "composer require first-argument" instead to add packages to your composer.json.`.

Ideally, Composer would not automatically forward arguments, but would require it to be more explicit. However, since that ship has already sailed, an alternative could be to allow the auto-forwarding arguments to be disabled and then have some kind of syntax for denoting where arguments should be forwarded/substituted. Something like this:
```json
{
    "scripts": {
        "command-name": [
            "Composer\\Config::disableAutomaticArgumentForwarding",
            "@composer install --no-dev",
            "@php app/Console/runner.php command-name {composer_args}"
        ]
    }
}
```

**Comment by Seldaek** [comment]
@willrowe one workaround for your use case would be to stop argument parsing for composer install by adding --

```
"@composer install --no-dev --",
```

This trick won't work for all things but it should help already.

**Comment by willrowe** [comment]
@Seldaek I tried that, thinking it may ignore the argument, but unfortunately it has no effect and the same error is still thrown.

**Comment by Seldaek** [comment]
Ah yes for install it doens't work because install takes arguments on top of options and `--` only stops option parsing. Then yes having an explicit {args} somewhere would help but see https://github.com/composer/composer/issues/10734#issuecomment-1099285176 above - if someone wants to try it feel free.

**Comment by alexander-schranz** [comment]
Today I just tried to add `#` at the end of the commands I don't want to get the params and it seems to work:

```
    "scripts": {
        "phpstan": [
            "@php bin/websiteconsole cache:warmup --env=dev # ignore params",
            "@php vendor/bin/phpstan analyze"
        ],
    }
```

Only thing I'm not sure if this is compatible with none unix shells.

It also works with `composer install`:

```
         "phpstan": [
             "Composer\\Config::disableProcessTimeout",
-            "@php bin/websiteconsole cache:warmup --env=dev",
+            "@composer install # ignore params",
+            "@php bin/websiteconsole cache:warmup --env=dev # ignore params",
             "@php vendor/bin/phpstan analyze -vvv"
         ],
```

**Comment by danielcavanagh** [comment]
using `#` doesn't seem to work for me. i'd tried it before coming here and composer quotes it which makes the shell treat it as an argument to the command, not a comment mark. i've tried v 2.7.7 in bash and fish and same result

while it's possible to write a custom script outside of composer to handle this case, that's a bit annoying and comes with its own downsides

something like either of these would be good backwards-compatible options i reckon:

```
    "pkg-install": { cmd: "@composer i", args: false }
    # or
    "pkg-install": "@@args:no @composer i"
```
