### ISSUE TITLE
List missing PHP extensions during composer create-project

### ISSUE THREAD

**Issue by gitressa** [composer/composer#10736]
If you run `composer install` in an existing project where one or more PHP extensions are missing, it is explicitly stated which extensions are missing, and the user gets actionable feedback, for example `Root composer.json requires PHP extension ext-gd`.

It would be great if the same functionality was available during creation of a project with `composer create-project`, since the current error message is ambiguous, and could have any number of reasons. For example if `php-gd` is not installed:

**Now**
```
$ composer create-project -n drupal-composer/drupal-project:7.x-dev
Could not find package drupal-composer/drupal-project with version 7.x-dev in a version installable using your PHP version, PHP extensions and Composer version.
```

**Better**
```
$ composer create-project -n drupal-composer/drupal-project:7.x-dev
Root composer.json requires PHP extension ext-gd * but it is missing from your system. Install or enable PHP's gd extension.
```

**Comment by ngdangtu-vn** [comment]
I agree, we should receive a list of what missing. In my pc, I don't have... no idea, still counting, maybe 7 exts and I have to:

1. run composer install
2. receive the missing error for 1 extension
3. search if it not installed or enabled
4. install -> enable
5. go back step 1

I watse 3 steps x 7 times (and keep counting)... This is not good :(

**Comment by kemalyen** [comment]
I've got the same problem. DevOps built a new image and many extensions are missing. But I can't provide them with a list of the missing extensions. Doing this one by one is madness!

**Comment by Seldaek** [comment]
#12120 fixes this for create-project I believe, it shows all warnings now so for example you get this if you have no extensions installed:

![image](https://github.com/user-attachments/assets/2582964f-c6ee-414d-91f6-1f1ec6d8f0b7)

@kemalyen @ngdangtu-vn If you still have more problems in other contexts than create-project please open a new issue with repro details.
