### ISSUE TITLE
Is the ClassLoader class promise backwards compatibility?

### ISSUE THREAD

**Issue by phenaproxima** [composer/composer#10744]
Greetings, Composer folk!

I'm writing some code which needs to reliably detect the vendor directory of a Drupal installation, even if multiple ClassLoader instances have been registered, and ideally without introducing any new third-party dependencies (like webflo/drupal-finder).

I was able to accomplish this goal by taking advantage of `ClassLoader::getRegisteredLoaders()` and how it behaves in Composer 2.3.5 and later; see https://git.drupalcode.org/project/automatic_updates/-/merge_requests/248/diffs#e0aa0dfa529d2147010fc8fae61c870b9f629622_52_53 for the proposed implementation.

Now that code seems to work pretty well for our purposes, but it does depend on the expectation that `ClassLoader::getRegisteredLoaders()` is covered by a backwards compatibility promise, since if the method disappeared entirely, or the keys of the returned array were to change, then...well, the results would be unpredictable at best. So, my question is simple: is that method, or are ClassLoader's public methods in general, considered part of Composer's API from a backwards compatibility standpoint? Or is my code rooting around in internals that may break at any time?

**Comment by stof** [comment]
They are considered as part of the `composer-runtime-api`. So breaking BC in them will not happen without bumping the major version of that special package.
