### ISSUE TITLE
plugin manipulating "extra" broken after 2.3.0 (strict types in JsonManipulator)

### ISSUE THREAD

**Issue by tmotyl** [composer/composer#10742]
I have a composer plugin that manipulates composer.json by adding a branch-alias under "extra" key.

before composer 2.3.0 following (pseudo)code worked fine:

```
$manipulator = new JsonManipulator();
$manipulator->addLink('extra', 'branch-alias', ['dev-main' => '1.9.4.x']);
```
Now it breaks with an error:
```
 Composer\Json\JsonManipulator::addLink(): Argument #3 ($constraint) must be of type string, array given
```
in composer 2.3.0 a string typehint was added to 3rd param.

Is the typehint too strict in this case? or the plugin should use some other means/api to write to "extra" section?

**Comment by Seldaek** [comment]
You probably should be using `$composer->getConfig()->getConfigSource()->addProperty('extra.branch-alias', ['dev-main' => '1.9.4.x']);`, but `$manipulator->addProperty('extra.branch-alias', ['dev-main' => '1.9.4.x']);` will do the job as well.

**Comment by tmotyl** [comment]
Thanks a lot, will try it out!

**Comment by tmotyl** [comment]
works great
