### ISSUE TITLE
What a falling ?

### ISSUE THREAD

**Issue by zorn-v** [composer/composer#10740]
StandWith#Ukraine
Blalalba. We are tech or politics ?
Hype is good word, but infuriates

**Comment by spirehawk** [comment]
[habr](https://habr.com/ru/post/661017/)

**Comment by Seldaek** [comment]
Everything is politics. If you're furious direct it at your government.

**Comment by zorn-v** [comment]
And you are really think that working like that ?

**Comment by zorn-v** [comment]
NOBODY remember about Odessa genocide. Krym - just make a another sanction.
Suck a american dick. Is is tasty I think..

**Comment by zorn-v** [comment]
You say "Everything is politic". 
You get money for this OR you just as others (bet on this) OR MAKE PEACE NO WAR.
If later, Ukraine is not "victim"

**Comment by dddmark** [comment]
Let's not get angry! Let's live in peace!
p.s.
Seldaek - direct it at your government: 
https://en.wikipedia.org/wiki/Timeline_of_United_States_military_operations
