### ISSUE TITLE
Remove #StandWithUkraine from ouput !!!!!!!!!!!

### ISSUE THREAD

**Issue by andrelec1** [composer/composer#10758]
PLS  remove the output `Info from https://repo.packagist.org: #StandWithUkraine`
Its time to stop breaking all CI ...

**Comment by Seldaek** [comment]
If this breaks your CI, you probably got something to fix.. Sorry but I think this will still remain for a little while.

**Comment by Andreas-Schoenefeldt** [comment]
We found a few good solutions to get rid of the SPAM here: https://github.com/composer/composer/discussions/10808
