### ISSUE TITLE
TypeError: escapeshellcmd(): Argument #1 ($command) must be of type string, bool given 

### ISSUE THREAD

**Issue by staabm** [composer/composer#10752]
I tried running `composer config --global --editor` as suggested on https://getcomposer.org/doc/articles/authentication-for-private-packages.md#manually-editing-global-authentication-credentials which turns into a type error

```
$ composer config --global --editor

In ConfigCommand.php line 217:
                                                                               
  [TypeError]                                                                  
  escapeshellcmd(): Argument #1 ($command) must be of type string, bool given  
...
Exception trace:
  at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/ConfigCommand.php:217
 escapeshellcmd() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/ConfigCommand.php:217
 Composer\Command\ConfigCommand->execute() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:1015
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:334
 Composer\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:130
 Composer\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin/composer:88
 require() at C:\ProgramData\ComposerSetup\bin\composer.phar:29

```

using

```
$ composer --version
Composer version 2.3.5 2022-04-13 16:43:00

$ php --version
PHP 8.0.15 (cli) (built: Jan 18 2022 13:43:14) ( NTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.15, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.15, Copyright (c), by Zend Technologies
```

**Comment by usersasha** [comment]
> Я попытался запустить `composer config --global --editor`, как было предложено на https://getcomposer.org/doc/articles/authentication-for-private-packages.md#manually-editing-global-authentication-credentials , что превратилось в ошибку типа.
> 
> ```
> $ composer config --global --editor
> 
> In ConfigCommand.php line 217:
>                                                                                
>   [TypeError]                                                                  
>   escapeshellcmd(): Argument #1 ($command) must be of type string, bool given  
> ...
> Exception trace:
>   at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/ConfigCommand.php:217
>  escapeshellcmd() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/ConfigCommand.php:217
>  Composer\Command\ConfigCommand->execute() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Command/Command.php:298
>  Symfony\Component\Console\Command\Command->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:1015
>  Symfony\Component\Console\Application->doRunCommand() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:299
>  Symfony\Component\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:334
>  Composer\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:171
>  Symfony\Component\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:130
>  Composer\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin/composer:88
>  require() at C:\ProgramData\ComposerSetup\bin\composer.phar:29
> ```
> 
> с использованием
> 
> ```
> $ composer --version
> Composer version 2.3.5 2022-04-13 16:43:00
> 
> $ php --version
> PHP 8.0.15 (cli) (built: Jan 18 2022 13:43:14) ( NTS Visual C++ 2019 x64 )
> Copyright (c) The PHP Group
> Zend Engine v4.0.15, Copyright (c) Zend Technologies
>     with Zend OPcache v8.0.15, Copyright (c), by Zend Technologies
> ```
