### ISSUE TITLE
Invalid credentials error for private repository basic authentification

### ISSUE THREAD

**Issue by MaximilianKresse** [composer/composer#10763]
We found a strange problem when it comes to authentificating to a private repository using basic authentification. To isolate and demonstrate the problem I created a small script which acts as a private repository:

```php
<?php

error_reporting(E_ALL | E_STRICT);
ini_set('display_errors', '1');

$uid = uniqid('', true);

$logMessage = function (string $message) use ($uid) {
    file_put_contents(__DIR__ . '/server.log', '[' . $uid . ']-' . date('c') . '-' . $message . "\r\n", FILE_APPEND);
};

$logMessage('Downloading ' . $_SERVER['REQUEST_URI']);

switch ($_SERVER['REQUEST_URI'] ?? '') {
    case '/packages.json':
        header('Content-Type: application/json');
        echo json_encode([
            'packages' => [
                'my/package' => [
                    '1.0.0' => [
                        'type' => 'library',
                        'name' => 'my/package',
                        'version' => '1.0.0',
                        'dist' => [
                            'url' => 'http://127.0.0.1:1234/my/package.zip',
                            'type' => 'zip',
                        ],
                        "require" => [
                            'my/other-package' => '^1.0',
                        ]
                    ]
                ],
                'my/other-package' => [
                    '1.0.0' => [
                        'type' => 'library',
                        'name' => 'my/other-package',
                        'version' => '1.0.0',
                        'dist' => [
                            'url' => 'http://127.0.0.1:1234/my/other-package.zip',
                            'type' => 'zip',
                        ],
                    ]
                ],
            ]
        ], JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT | JSON_UNESCAPED_SLASHES);
        break;
    case '/my/package.zip':
        $file = __DIR__ . '/my-package.zip';
    case '/my/other-package.zip':
        if (!isset($file)) {
            $file = __DIR__ . '/my-other-package.zip';
        }

        $user = $_SERVER['PHP_AUTH_USER'] ?? '';
        $pw = $_SERVER['PHP_AUTH_PW'] ?? '';
        $logMessage('Trying download with following credentials: ' . $user . ':' . $pw);
        if ($user !== 'test' && $pw !== 'test') {
            $logMessage('Wrong credentials');
            header('HTTP/1.0 401 Unauthorized');
            header('WWW-Authenticate: Basic realm="Please login to access the requested resource"');
            return;
        }

        $logMessage('Sending package');
        header('Content-Type: application/zip');
        echo file_get_contents($file);
        break;
    default:
        $logMessage('Not found');
        header('HTTP/1.0 404 Not Found');
        exit;
}

```

This will just offer to packages "my/package" and "my/other-package" both only available in v1.0.0. "my/package" requires "my/other-package". The problems comes with the basic authentifaction. To download the packages you have to insert as username and password "test".

To test this script yourself you could use: ```php -S 127.0.0.1:1234 index.php```
To have something to download and act as the packages you will have to create two zip files into the same directory "my-package.zip" and "my-other-package.zip".

The composer.json for this looks like this:
```json
{
    "require": {
        "my/package": "^1.0"
    },
    
    "config": {
        "secure-http": false
    },
    
    "repositories": [
        {
            "type": "composer",
            "url": "http://127.0.0.1:1234/"
        }
    ]
}
```

After using "composer install" the authentification triggers:
![image](https://user-images.githubusercontent.com/545671/166719550-73452e78-a40e-4589-bc57-e134cbfbaafa.png)

So far so good. Insert "test" and "test". After this `Do you want to store credentials for 127.0.0.1:1234 in C:/Users/{user}/AppData/Roaming/Composer/auth.json` pops up. The important part is answering "n". After this we get the following error:
```
In AuthHelper.php line 198:

  Invalid credentials for 'http://127.0.0.1:1234/my/package.zip', aborting.
```

Taking a look into the created server.log file contains the following:
```
[62729fde55df49.41975431]-2022-05-04T15:46:38+00:00-Downloading /packages.json
[62729fde6d5a87.52674107]-2022-05-04T15:46:38+00:00-Downloading /my/other-package.zip
[62729fde6d5a87.52674107]-2022-05-04T15:46:38+00:00-Trying download with following credentials: :
[62729fde6d5a87.52674107]-2022-05-04T15:46:38+00:00-Wrong credentials
[62729fde7033e2.26650478]-2022-05-04T15:46:38+00:00-Downloading /my/package.zip
[62729fde7033e2.26650478]-2022-05-04T15:46:38+00:00-Trying download with following credentials: :
[62729fde7033e2.26650478]-2022-05-04T15:46:38+00:00-Wrong credentials
[6272a01f8d5869.19538075]-2022-05-04T15:47:43+00:00-Downloading /my/other-package.zip
[6272a01f8d5869.19538075]-2022-05-04T15:47:43+00:00-Trying download with following credentials: test:test
[6272a01f8d5869.19538075]-2022-05-04T15:47:43+00:00-Sending package
```

So the server didn't got the credentials for "/my/package.zip".

The problem only occurs in this combination. If you answer "Y" everything works fine. It also works fine with an auth.json file. The problem also doesn't occur when one of the packages is in the file-cache or when it's only one package.

We are using Composer "2.3.5" with PHP 8.0.10-x64-nts on Windows 10.

**Comment by Seldaek** [comment]
Thanks for the good repro case :) It was in fact working fine with a single download, but with two in parallel it ended up doing smth like:

- send req1
- send req2
- resp2 403, no auth in IO, prompt user for auth, retry
- resp1 403, auth in IO (as it just prompted), so bail as we assume the credentials are invalid

This code was initially written before we had parallel downloads in which case it happened like:

- send req1
- resp1 403, no auth in IO, prompt user for auth, retry
- retry req1
- resp1 200
- send req2, auth is present so send auth with req
- resp2 200

**Comment by Seldaek** [comment]
Thanks for the great repro case :) It turns out it was failing due to the parallel downloads if you had two or more requests sent at the same time for the same hostname, it did something like this:

- send req1
- send req2
- resp2 403, no auth in IO, prompt user for auth, retry
- resp1 403, auth present in IO (as it just prompted), so bail as we assume the credentials are invalid (but in fact they just weren't sent yet with req1)

The code was written initially for a simpler model where we had sequential downloads:

- send req1
- resp1 403, no auth in IO, prompt user for auth, retry
- send req1 with auth as it is present
- resp1 200
- send req2 with auth as it is present
- resp2 200
-
