### ISSUE TITLE
warning for badly-formed aliases on the CLI is not as good as in composer.json

### ISSUE THREAD

**Issue by joachim-n** [composer/composer#10778]
I did this on the CLI:

`composer require tecnickcom/tcpdf:"^6.4 as 6.2.11"`

(because I have a dependency whose composer.json pins tecnickcom/tcpdf at that version 6.2.11)

I got this error:

```
  [InvalidArgumentException]
  Could not find package as.
```

This was an unclear error message. So I tried adding this to my composer.json:

```
        "tecnickcom/tcpdf": "^6.4 as 6.2.11",
```

When I did `composer update tecnickcom/tcpdf` I got this much clearer error:

```
  [UnexpectedValueException]
  Invalid version string "^6.4" in "^6.4 as 6.2.11", the alias source must be an exact version, if it is a branch name you should prefix it with dev-
```

This clearly explained the problem.

The error with the badly-formed alias require command should give the same detail as the error for the badly-formed composer.json.

**Comment by Seldaek** [comment]
The problem is you quote a random piece of an argument here which makes it parse "as" as a package name (as if you required `tecnickcom/tcpdf ^6.4` and `as 6.2.11`.

If you quote correctly the whole thing is then reports it well:

```
$ composer require "tecnickcom/tcpdf:^6.4 as 6.2.11"
./composer.json has been updated

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

In VersionParser.php line 186:

  Invalid version string "^6.4" in "^6.4 as 6.2.11", the alias source must be an exact version, if it is a branch name you should prefix it with dev-
```

**Comment by joachim-n** [comment]
I used the same CLI quoting at on https://getcomposer.org/doc/articles/aliases.md:

> php composer.phar require monolog/monolog:"dev-bugfix as 1.0.x-dev"

**Comment by Seldaek** [comment]
Ah well then our docs are borked :D Thanks
