### ISSUE TITLE
Skip generate autoload if <nothing to install>

### ISSUE THREAD

**Issue by btxtiger** [composer/composer#10792]
Running `composer install` always runs `composer dump-autoload` afterwards, showing `Generating optimized autoload files`, even if the install output is `Nothing to install, update or remove`.

Always re-generating autoload files is an unnecessary step for us, that consumes too much time when handling docker containers. 

But if we skip this during installation using `--no-autoloader` and there was a package installed, we need to manually run `composer dump-autoload` to update the autoload files.

I could not find any workaround yet. So I guess it should be possible to skip this behavior conditionally, if something/nothing was installed.

**Comment by Seldaek** [comment]
Makes sense, let's try this for 2.4, we may need to keep track of the last autoload dump state (optimizations etc..) to make sure we redump it if the new mode isn't matching the old one.

**Comment by Seldaek** [comment]
After the attempt in #10899 and further consideration I'm gonna have to close this as not worth the risk/trouble.

**Comment by btxtiger** [comment]
@Seldaek Just for clarification: it is also not an option to have this as optional (experimental) flag? The only other option to fix this for me, would be to parse the stdout for "Nothing to install, update or remove" which can break easily if the string was updated.

**Comment by Seldaek** [comment]
It just seems like a giant foot-gun so I'd rather not have it in even as an optional thing. Parsing output of install sounds relatively safe as if it does not match `Nothing to install, update or remove` anymore at worst you'll always redump the autoloader and get back to slower perf until you notice. These strings are really quite stable though.

**Comment by btxtiger** [comment]
Okay, good to know that. Then I'm going forward with this implementation. Thanks
