### ISSUE TITLE
composer scripts, process timeouts while debugging

### ISSUE THREAD

**Issue by staabm** [composer/composer#10793]
In some of our projects we use composer scripts like
```
		"phpunit": [
			"phpunit -c tests/default/config/phpunit.xml",
			"phpunit -c tests/rules/config/phpunit.xml",
			"phpunit -c tests/stringify/config/phpunit.xml",
			"phpunit -c tests/defaultFetchAssoc/config/phpunit.xml",
			"phpunit -c tests/defaultFetchNumeric/config/phpunit.xml"
		]
```

when debugging tests with xdebug this leads sometimes to timeouts:

```
$ composer phpunit
> @putenv DBA_REFLECTOR=pdo-mysql
> @putenv DBA_MODE=replay
> phpunit -c tests/default/config/phpunit.xml
PHPUnit 9.5.20 #StandWithUkraine

...............................................................  63 / 241 ( 26%)
............................................................... 126 / 241 ( 52%)
............................................................... 189 / 241 ( 78%)
....................................................            241 / 241 (100%)

Time: 00:00.072, Memory: 90.00 MB

OK (241 tests, 241 assertions)
> phpunit -c tests/rules/config/phpunit.xml
PHPUnit 9.5.20 #StandWithUkraine

.SESESThe following exception is caused by a process timeout
Check https://getcomposer.org/doc/06-config.md#process-timeout for details

In Process.php line 1204:

  The process "phpunit -c tests/rules/config/phpunit.xml" exceeded the timeout of 300 seconds.
```

couldn't/shouldn't composer use a unlimited/rather long timeout when running with xdebug?

**Comment by Seldaek** [comment]
The cause and a possible solution are here https://getcomposer.org/doc/06-config.md#process-timeout - that said, I am wondering if we shouldn't allow longer/unlimited execution time for scripts running via the exec/run-script commands. These are totally different use cases than the internal git processes we use which we don't want to get stuck forever. That'd remove the need for this disableProcessTimeout hack.

**Comment by Seldaek** [comment]
I think we could add a `script-timeout` config setting which would default to 0 and be used as timeout for those processes. It looks like it'll require a few changes to ProcessExecutor tho, so not sure if it is really reasonable or if you should just use the `disableProcessTimeout` workaround from the docs.

**Comment by Seldaek** [comment]
Yeah I don't see a way to do this clean, so rather close sorry.

**Comment by staabm** [comment]
thx for considering!
