### ISSUE TITLE
[Help Wanted] Increasing test coverage of Command classes

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#10796]
As you can see on this image, Command classes have very poor coverage currently (16% of lines covered in total):

<img src="https://user-images.githubusercontent.com/183678/169980310-62da227b-44ff-4a45-988f-054970436f51.png" width=200>

**Edit: To see latest guidelines on what to work on see https://github.com/composer/composer/issues/10796#issuecomment-1277340969**

Here some examples of how to write sane integration tests for most commands: 

https://github.com/composer/composer/blob/176d25851d1f99345c652a6ecbc7c3787071218d/tests/Composer/Test/Command/RunScriptCommandTest.php#L92-L113

https://github.com/composer/composer/blob/176d25851d1f99345c652a6ecbc7c3787071218d/tests/Composer/Test/Command/ConfigCommandTest.php#L23-L52

https://github.com/composer/composer/blob/70f2dd6eddd5916f70b3d73dd3170a3d2d3a7681/tests/Composer/Test/Command/BumpCommandTest.php#L28-L47

If you feel like helping, PRs are very much welcome, I don't think we absolutely need 100% coverage but having the most common use cases covered would already be very valuable. Please target the `main` branch if you want to contribute some, and feel free to announce it here if you start some larger chunk of work to avoid duplicating efforts.

**Comment by theoboldalex** [comment]
@Seldaek I'd love to take on some of this work. I have opened a first PR here #10932 and will start to work my way through the commands.

**Comment by Seldaek** [comment]
@theoboldalex great, thanks! Maybe wait until I get a chance to review the first one to make sure you don't run off and do more of them with the wrong assumptions. I'll try to get to it soon.

Also note the listing above is a bit outdated as I tried to work on this here and there when touching commands the last few months. But there is still plenty to be done :)

**Comment by ralflang** [comment]
No promises but I may make the occassional PR every now and then.
Might be a good learning exercise. I have been playing around with the Command, Plugin, Capable ... parts of the codebase last month.

**Comment by Seldaek** [comment]
Update, we're at 36% (up from 16!) already now:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/183678/185733135-3854c0b4-dd49-435f-ac6e-626655a36c82.png">

**Comment by tomekpryjma** [comment]
I'd like to help out with this now and again - is there a way to see the current coverage?

**Comment by Seldaek** [comment]
Now at 41%! Here are the classes still needing the most effort IMO:

- BaseDependencyCommand.php (needs to be tested via why/why-not commands)
- CheckPlatformReqsCommand.php
- FundCommand.php
- HomeCommand.php (probably only can test with the --show flag enabled)
- InstallCommand.php
- SuggestsCommand.php
- ValidateCommand.php
- RemoveCommand.php
- UpdateCommand.php with --interactive flag (needs to run the command [in interactive mode](https://github.com/symfony/symfony/blob/3a4166e4e99d437a368ff05edd883a56499ec279/src/Symfony/Component/Console/Tester/ApplicationTester.php#L43) to test the uncovered bits, and use `$applicationTester->setInputs()` to configure/fake the user inputs)
- InitCommand.php & PackageDiscoveryTrait.php (needs to run the command [in interactive mode](https://github.com/symfony/symfony/blob/3a4166e4e99d437a368ff05edd883a56499ec279/src/Symfony/Component/Console/Tester/ApplicationTester.php#L43) to test the uncovered bits, and use `$applicationTester->setInputs()` to configure/fake the user inputs)
- ShowCommand.php (tested quite a bit but still only 40% covered as it is a large one)
- GlobalCommand.php (might be tricky to test as it requires some internal knowledge)
 
These need an install to be run to actual get a working vendor dir:

- StatusCommand.php
- ReinstallCommand.php

**Comment by giulio-Joshi** [comment]
Is this issue still relevant?

**Comment by Seldaek** [comment]
@giulio-Joshi yes for sure, not much happened since my last comment above yours.

**Comment by giulio-Joshi** [comment]
Thanks for your answer.
 I was planning on adding some more tests in the area, but paused the activity since my related PR had no feedback.
I was wondering if there was something wrong about it.

**Comment by Seldaek** [comment]
No it's just been 8 days, I'll get to it :)

**Comment by yesdevnull** [comment]
Putting my hand up to work on tests for `SuggestsCommand`. Will submit a PR with my progress in the next ~24 hours.

**Comment by antoniovj1** [comment]
I'm starting with the RemoveCommand file. I'll try to add a PR asap

**Comment by siims-biz** [comment]
Do you still need help in getting parts of Composer tested?

**Comment by Seldaek** [comment]
@siims-biz yes the list in https://github.com/composer/composer/issues/10796#issuecomment-1277340969 above is still more or less accurate

**Comment by siims-biz** [comment]
@Seldaek What kind of skill/talent/tools are required/useful to contribute with testing?

**Comment by Seldaek** [comment]
@siims-biz knowledge of PHPUnit, some knowledge of composer (from user perspective good, internals better), the easy ones have been covered already though so if you aren't super familiar with all this I would say maybe rather find something else to work on, but up to you :)

**Comment by stof** [comment]
Now at 52%

**Comment by theoboldalex** [comment]
I'm going to make a start on testing `ReinstallCommand` tonight and will try to pick up `StatusCommand` after that if time permits.

**Comment by Seldaek** [comment]
54.4% now, thanks everyone involved so far!

<img width="599" alt="image" src="https://github.com/composer/composer/assets/183678/f4f514f9-557d-409b-9666-51d368ab69eb">

Here are the classes still needing the most effort, but overall we are really in a much better spot now I would say with the most critical commands pretty well covered:

- [ ] BaseDependencyCommand.php (needs to be tested via why/why-not commands)
- [ ] UpdateCommand.php with --interactive flag (needs to run the command [in interactive mode](https://github.com/symfony/symfony/blob/3a4166e4e99d437a368ff05edd883a56499ec279/src/Symfony/Component/Console/Tester/ApplicationTester.php#L43) to test the uncovered bits, and use `$applicationTester->setInputs()` to configure/fake the user inputs)
- [ ] InitCommand.php & PackageDiscoveryTrait.php (needs to run the command [in interactive mode](https://github.com/symfony/symfony/blob/3a4166e4e99d437a368ff05edd883a56499ec279/src/Symfony/Component/Console/Tester/ApplicationTester.php#L43) to test the uncovered bits, and use `$applicationTester->setInputs()` to configure/fake the user inputs)
- [ ] ShowCommand.php (tested quite a bit but still only 40% covered as it is a large one)
- [ ] GlobalCommand.php (might be tricky to test as it requires some internal knowledge)
 
These need an install to be run to actual get a working vendor dir, using packages with type `metapackage` helps making them installable without actual source:

- [ ] StatusCommand.php

**Comment by rad8329** [comment]
Hi @Seldaek, I'd love to continue working on the above checklist, but I'm still waiting for [Tests for base dependency command #11547](https://github.com/composer/composer/pull/11547) feedback, once I've received first feedback I could replicate that same approach in my upcoming PRs, thanks

**Comment by rad8329** [comment]
Will try to complete `show` command test coverage, currently it is 55%

**Comment by stof** [comment]
@Seldaek this should be re-opened. The PR #11547 contributed to this by adding more tests, but we are still not done yet.

**Comment by stof** [comment]
now at 58.11%:
![image](https://github.com/composer/composer/assets/439401/db01ff58-488b-432a-b4c9-7a31223f4509)

**Comment by greew** [comment]
FYI - I'm writing a lot of test for ShowCommand :)

**Comment by mzhubail** [comment]
@Seldaek

I'm thinking about contributing, and currently I have some time to dedicate to this.  I already took a look at how some of the command are tested, just to familiarize myself with how things are done.

I see you mentioned `UpdateCommand.php` with interactive flag, so I'll be starting with it.  For what I see, we have only one case for interacrtive, but I'm not sure what cases are missing currently, so I'm planning on looking into how the command is used.

Just wanted to let you know in case you have any pointers for me.  I might get into other commands I don't get along with the update command :)

**Comment by Seldaek** [comment]
Yeah tbh the easy ones are all gone now so good luck is all I can say :D sorry i don't have much input otherwise.. Looking at code coverage to see what's missing is probably the best.

**Comment by mzhubail** [comment]
I started working on a case that would cover most of `getPackagesInteractively` of `UpdateCommand.php`.  I'll finalize it and send it your way.

Regarding the code coverage, I couldn't get `xdebug` installed.  Working with php environments is a pain.  XAMPP doesn't ship `xdebug`, and I couldn't get versions to work with my usual environment through my distro's package manager.  Do you have any guide on setting an environment, or should I not even bother?

**Comment by Seldaek** [comment]
It's very dependent on your environment so not sure what to say.. I use ondrej's ppa for ubuntu and that's easy.

Anyway don't sweat it if you can't get coverage info.. I care about useful tests covering use cases than covering every line.

**Comment by mzhubail** [comment]
@Seldaek

I'm not sure about it,  I'm not on ubuntu.

Can I suggest that I create a docker image for development purposes as to make it easier for new contributors.

I'm already learning docker and would like to contribute. but I'm not sure if it would be a good idea, and I'm not familiar with the specifics of php environments.

**Comment by mzhubail** [comment]
FYI - I'm writing some tests for interactive mode of `InitCommand`.

**Comment by Seldaek** [comment]
I think we're in a pretty decent spot now with this so I'll close this issue. Many thanks to everyone who contributed!
