### ISSUE TITLE
Old releases should not have the latest flag in gh-release section

### ISSUE THREAD

**Issue by thomasbley** [composer/composer#10802]
Downloading "latest" composer phar from https://github.com/composer/composer/releases/latest/download/composer.phar currently gives version 2.2.13 instead of 2.3.5.

**Comment by stof** [comment]
Well, the issue is that `latest` on Github releases is based only on the date of the release. It is not a flag you can set.

**Comment by Seldaek** [comment]
Yeah, I don't see how I can fix this.. If you want to script it I'd recommend parsing https://getcomposer.org/versions for the stable or `2` key.
