### ISSUE TITLE
Possibly invalid regex in composer-schema.json

### ISSUE THREAD

**Issue by nhedger** [composer/composer#10805]
Since commit https://github.com/composer/composer/commit/44a52e4157eb3a8c529204d6799ae7e0909d4de0, Visual Studio is having trouble validating `composer.json`'s JSON schema. While PHP seems to have no issues compiling the regular expression, javascript sees it as invalid.

<img width="1145" alt="Screenshot 2022-05-28 at 07 10 48" src="https://user-images.githubusercontent.com/649677/170811113-c9423517-3f3c-488e-a48c-b57504ca1e1e.png">

https://github.com/composer/composer/blob/44a52e4157eb3a8c529204d6799ae7e0909d4de0/res/composer-schema.json#L6-L10

Compiling the regex with PHP works and seems to validate as expected : 
- https://3v4l.org/kTnon
- https://regex101.com/r/vBTWRa/1

Compiling the regex with JS produces an error: 
- https://jsfiddle.net/3fjr9ny2/
- https://regex101.com/r/LYG1VC/1

Visual Studio Code uses the following schema for validating the `composer.json` file:

```
https://raw.githubusercontent.com/composer/composer/master/res/composer-schema.json
```

**Edit:**

Some [additional research](https://stackoverflow.com/a/25255810) suggests that JS does not support possessive quantifiers, as used in this pattern. This could probably be fixed by using the initial pattern only in the JSON schema.

**Comment by matronator** [comment]
According to https://github.com/microsoft/vscode/issues/150444#issuecomment-1141204184 the forward slash between `vendor-name/` and package name should be escaped with `\`.
