### ISSUE TITLE
False positive error message for GitLab deploy tokens with username

### ISSUE THREAD

**Issue by jakubboucek** [composer/composer#10800]
I was followed instruction to use GitLab Deploy Tokens for access to private packages from Composer:
**[GitLab Docs: Composer packages in the Package Registry](https://docs.gitlab.com/ee/user/packages/composer_repository/#:~:text=Using%20a%20deploy%20token)**

Composer is now alert warning on any `composer` command:
```
"~/.composer/auth.json" does not match the expected JSON schema, this may result in errors and should be resolved:
 - gitlab-token.gitlab.com : Object value found, but a string is required
```

**Token with Username is for installation works very well**, Composer is using `username` field correctly, but it just is screaming error as above. 
Maybe fix invalid JSON schema.

My `~/.composer/auth.json`:

![](https://cdn.jakub-boucek.cz/screenshot/220525-0obvl.png)

Output of `composer diagnose`:
![](https://cdn.jakub-boucek.cz/screenshot/220525-5c32g.png)

**Comment by pscheit** [comment]
I hit this too, when was the validation added? Cause I cant remember updating my composer version on ci? :/

I use  a personal access token with api level, that did not help as well. Before I couldnt access gitlab private repos without a username as well. Once I added the username of the account that owns the personal access token, it worked.

Happy to help debug

**Comment by pscheit** [comment]
oh .. maybe i missed the update I did:
https://github.com/composer/composer/commit/8e93566c18b1b8b0de32aff64a2204f19f1105f8
This is definitely the source. I clearly don't know why gitlab does need that username to be passed, but passing it, fixes it.

I can revert to 2.3.2 and leave my composer auth to provide username + token to work around it.

**Comment by pscheit** [comment]
dang.. i should read main first ;)

https://github.com/composer/composer/commit/bd6403a6bef36fdbefdb287dc7e26286d5e06e5e

**Comment by webmozart** [comment]
I hit this too and it's breaking our pipelines. :grimacing: 

@Seldaek when do you plan to roll out the fix?
