### ISSUE TITLE
Any chance to remove the #StandWithUkraine ?

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [composer/composer#10807]
My `composer.json`:

```json
...replace me...
```

Output of `composer diagnose`:

```
...replace me...
```

When I run this command: 

```
...replace me...
```

I get the following output: 

```
...replace me...
```

And I expected this to happen:

**Comment by GuySartorelli** [comment]
This probably should be a discussion rather than an issue.

**Comment by Andreas-Schoenefeldt** [comment]
Totally agreed - it just feels strange to see too simplified statement of a very complex situation all the time, while you just want to do your work.

**Comment by Andreas-Schoenefeldt** [comment]
Plus it is such a double standard... where was all the wokeness in the other 10+ wars before Ukraine?

**Comment by GuySartorelli** [comment]
Since you agree this should be a discussion and not an issue, could you please close this issue and [open a discussion](https://github.com/composer/composer/discussions/new) instead?

**Comment by artembeloglazov** [comment]
@Andreas-Schoenefeldt The inclusion of this phrase was a turning point in the fight against the aggressor. One cannot be a supporter of common sense!

**Comment by xieyuheng** [comment]
The message come from packagist.org

You can choose a politic-free mirror from: https://packagist.org/mirrors

For example:

Enable mirror from aliyun.com (from China):

```
composer config -g repo.packagist composer https://mirrors.aliyun.com/composer
```

Disable the mirror:

```
composer config -g --unset repos.packagist
```

**Comment by xieyuheng** [comment]
Or this one: https://packagist.mirrors.sjtug.sjtu.edu.cn/

Which has some english docs.

**Comment by kodima05** [comment]
Another way to remove it is by removing this specific package:
`composer remove ukeloop/stand-with-ukraine`

**Comment by Andreas-Schoenefeldt** [comment]
@kodima05, this is amazingly simple! Thank you so much for the hint!

**Comment by artembeloglazov** [comment]
```
composer self-remove
```

**Comment by politsin** [comment]
```sh
git clone https://github.com/composer/composer.git --branch 2.4.4  ~/composer-build && \
    composer install  -o -d ~/composer-build && \
    wget https://raw.githubusercontent.com/politsin/snipets/master/patch/composer.patch -q -O ~/composer-build/composer.patch  && \
    cd ~/composer-build && patch -p1 < composer.patch && \
    php -d phar.readonly=0 bin/compile && \
    rm /usr/local/bin/composer && \
    php composer.phar install && \
    php composer.phar update && \
    mv ~/composer-build/composer.phar /usr/local/bin/composer && \
    rm -rf ~/composer-build  && \
    chmod +x /usr/local/bin/composer
```

**Comment by evan70** [comment]
> ```shell
> git clone https://github.com/composer/composer.git --branch 2.4.4  ~/composer-build && \
>     composer install  -o -d ~/composer-build && \
>     wget https://raw.githubusercontent.com/politsin/snipets/master/patch/composer.patch -q -O ~/composer-build/composer.patch  && \
>     cd ~/composer-build && patch -p1 < composer.patch && \
>     php -d phar.readonly=0 bin/compile && \
>     rm /usr/local/bin/composer && \
>     php composer.phar install && \
>     php composer.phar update && \
>     mv ~/composer-build/composer.phar /usr/local/bin/composer && \
>     rm -rf ~/composer-build  && \
>     chmod +x /usr/local/bin/composer
> ```

ThX > work like charm @archlinux

**Comment by evan70** [comment]
there is no  /usr/local/bin/composer
@archlinux > /usr/bin/composer ...

**Comment by evan70** [comment]
archlinux archerz use > 
```
git clone https://github.com/composer/composer.git --branch 2.4.4  ~/composer-build && \
    composer install  -o -d ~/composer-build && \
    wget https://raw.githubusercontent.com/politsin/snipets/master/patch/composer.patch -q -O ~/composer-build/composer.patch  && \
    cd ~/composer-build && patch -p1 < composer.patch && \
    php -d phar.readonly=0 bin/compile && \
    rm /usr/local/bin/composer && \
    php composer.phar install && \
    php composer.phar update && \
    mv ~/composer-build/composer.phar /usr/bin/composer && \
    rm -rf ~/composer-build  && \
    chmod +x /usr/bin/composer
```

**Comment by roni-estein** [comment]
> ```shell
> git clone https://github.com/composer/composer.git --branch 2.4.4  ~/composer-build && \
>     composer install  -o -d ~/composer-build && \
>     wget https://raw.githubusercontent.com/politsin/snipets/master/patch/composer.patch -q -O ~/composer-build/composer.patch  && \
>     cd ~/composer-build && patch -p1 < composer.patch && \
>     php -d phar.readonly=0 bin/compile && \
>     rm /usr/local/bin/composer && \
>     php composer.phar install && \
>     php composer.phar update && \
>     mv ~/composer-build/composer.phar /usr/local/bin/composer && \
>     rm -rf ~/composer-build  && \
>     chmod +x /usr/local/bin/composer
> ```
New machine, this is the best answer yet, but you can remove the branch 2.4.4 to get the newest composer.
Thanks @politsin

**Comment by politsin** [comment]
@roni-estein

I updated the text above with the last branch.

When I used the master branch instead of specifying a particular version, I didn't like the console output with the last commit id. And when switching between machines, it was impossible to tell which version of the linker was being used.

In the end, I decided to specify the branch explicitly, and the work became more comfortable.

Maybe there is a way to use the "last" branch instead of the master branch, but I don't know it =)

**Comment by roni-estein** [comment]
You don't need the --branch, it will use "main" which is always merged to the latest one to save you needing to update


Or you could use --branch=main if you don't want to maintain the comment. Cheers 🙂

**Comment by Andreas-Schoenefeldt** [comment]
As the composer team unsurprisingly resolves to censorship on this issue, I opened this on on stackoverflow to rescue the solutions: https://stackoverflow.com/questions/76130997/composer-how-to-remove-standwithukraine-cli-message

**Comment by Winfle** [comment]
No chances, until terrorist state will go out of soverign country. 
You better to support your colleges, who are sitting in shelters sometimes without electricity and pay some respect

**Comment by felloz** [comment]
> The message come from packagist.org
> 
> You can choose a politic-free mirror from: https://packagist.org/mirrors
> 
> For example:
> 
> Enable a mirror from China:
> 
> ```
> composer config -g repos.packagist composer https://mirrors.tencent.com/composer/
> ```
> 
> Disable the mirror:
> 
> ```
> composer config -g --unset repos.packagist
> ```

This repo changed.

**Comment by felloz** [comment]
> The message come from packagist.org
> 
> You can choose a politic-free mirror from: https://packagist.org/mirrors
> 
> For example:
> 
> Enable a mirror from China:
> 
> ```
> composer config -g repos.packagist composer https://mirrors.tencent.com/composer/
> ```
> 
> Disable the mirror:
> 
> ```
> composer config -g --unset repos.packagist
> ```

Saddly, this repo is too damn slow.

**Comment by roni-estein** [comment]
Here is a small update for people using herd...
For your convenience, I've assembled it as a zsh function alias. You can put it in your .aliases or .bashrc or .zshrc or just take any part of it as you like. This is simply the solution from @politsin wrapped with a configuration variable that chooses herd, homebrew or any other service you are serving from to place your updated composer. 

Cheers 🍻 

```zsh
composer:purge-politics() {
    # the keyword local destructs the memory variables so they wont stick around
    # after your function closes to interfere with any other system settings
    # which server are you going to run herd or something else (homebrew, xamp)
    local server="herd"
    local composer_path
    
    # choose the appropriate  path for composer
    [[ $server == "herd" ]] && composer_path="/Users/<your home directory>/Library/Application Support/Herd/bin/composer" || composer_path="/usr/local/bin/composer"
    # ** note change <your home directory>
 
    git clone https://github.com/composer/composer.git  ~/composer-build && \
    composer install  -o -d ~/composer-build && \
    wget https://raw.githubusercontent.com/politsin/snipets/master/patch/composer.patch -q -O ~/composer-build/composer.patch  && \
    cd ~/composer-build && patch -p1 < composer.patch && \
    php -d phar.readonly=0 bin/compile && \
    rm /usr/local/bin/composer && \
    php composer.phar install && \
    php composer.phar update && \
    mv ~/composer-build/composer.phar "$composer_path" && \
    rm -rf ~/composer-build  && \
    chmod +x "$composer_path"
}
```

**Comment by mohssineAboutaj** [comment]
> `alias composer="2> >(grep -av 'StandWith') composer --ansi"`
> 
> > jst one line to ya .bashrc or .zshrc or .wtFrc ...
> > work normaly with out war poltics adds ...
> > no china proxies needed ...
> > jst ya local memory one time loop 4 energy 2 sacrifice
> > our coGnitive resonanse ;)

your solution work perfectly, thank you so much

**Comment by djengis** [comment]
> ```
> composer self-remove
> ```

Acting like a child.

**Comment by djengis** [comment]
@artembeloglazov 
> ```
> composer self-remove
> ```

Acting like a child.

**Comment by artembeloglazov** [comment]
@djengis

> @artembeloglazov
> 
> > ```
> > composer self-remove
> > ```
> 
> Acting like a child.

Acting like a child: using an international it-project for political propaganda and absolute misunderstanding of the situation.

It's been 2 years and it's already clear to everyone that Ukraine is just a way to launder money for US military corporations, and the composer is a dying project that should be gradually removed from their projects.

**Comment by Andreas-Schoenefeldt** [comment]
@artembeloglazov, do you know a working alternative for composer?

Best wishes
Andreas

**Comment by artembeloglazov** [comment]
@Andreas-Schoenefeldt Package repository mirrors have been created separately from packagist.org for a while now. There is no alternative to the client for loading and resolving dependencies yet, but I think it will come soon.

**Comment by Seldaek** [comment]
The message isn't there anymore and you are still bitching? 🤷🏻‍♂️
