### ISSUE TITLE
 Invalid working directory specified, "Z:/existing directory" does not exist.

### ISSUE THREAD

**Issue by alexeyp0708** [composer/composer#10803]
Composer: Composer version 2.0.9 2021-01-27 16:09:27
OS: Windows 10
PHP: 7.4
Command:
`composer -d "D:/existing directory" require vendor/app`
Result:
 ```   
 [RuntimeException]                                                                                                                
  Invalid working directory specified,  "D:/existing directory" does not exist.  
```
Way to solve the problem
`composer -d"D:/existing directory" require vendor/app`
Please note: removed the space in place `-d"D:/`
Result:
`success`

Cause:
https://github.com/composer/composer/blob/d971f2e37ecd89f0210f7d8cd5cc50435dc21328/src/Composer/Console/Application.php#L388
File: Application.php
line: 388
method:  getNewWorkingDir
var: $workingDir
```php
var_dump("D:/existing directory"); //=>true
var_dump(" D:/existing directory");//=>false
```

problem solving in code:

```
//remove left all space and = 
$workingDir=ltrim($workingDir," \n\r\t\v\x00=");
//  or remove all spaces around the edges
$workingDir=trim($workingDir);
```

**Comment by Seldaek** [comment]
That looks like a shell parsing issue more than a Composer issue. Maybe you can try `-d="D:/existing directory"` or `--working-dir="D:/existing directory"`.

In any case we won't trim all values being input  as this makes no sense IMO.

Also try updating Composer to latest, 2.0.9 is old, 2.3.7 uses a more modern version of symfony/console which might have fixed that bug, who knows. `composer self-update` might help.

**Comment by alexeyp0708** [comment]
test and find out if there is a problem in the new version.
If a space comes in that shouldn't be there, then the problem is somewhere in the code.


 your right to live with jambs.

**Comment by alexeyp0708** [comment]
in Version 2.3.7 everything is ok.
But With the equal sign, the problem remained.
@Seldaek `-d="D:/existing directory"` =>`  Invalid working directory specified, =D:/existing directory does not exist.`
Of course, this is a problem in command parsing.
You can edit, or you can wait for the decision of the team of another component and live with the bug.

**Comment by stof** [comment]
@alexeyp0708 Trimming arguments to try to solve parsing bugs after the fact is likely to create more bugs by breaking case where the parsing was not broken before.
