### ISSUE TITLE
Comment to Ukraine defacement

### ISSUE THREAD

**Issue by kolbma** [composer/composer#10837]
Because my #10831 got locked I have to create a new one.

1st this was no joke, but hackers use defacements and this looks like one and there is no info on the websites about this political statement in code!

2nd this broke my CI and I have to modify it.

3rd if you don't want to handle political critics then don't make political statements

**Comment by Seldaek** [comment]
1st yes well sorry, adding info on the website etc takes time too, resources are limited
2nd sorry but at the same time if that breaks CI I think IMO you did something wrong and maybe it's good you get a chance to fix it.
3rd I have had to close many such issues from random russians complaining in various levels of politeness, so I stopped discussing a while back and just close and lock now. Again here, resources are limited

**Comment by kolbma** [comment]
@Seldaek Well it did what it should do, detecting a change in downloading dependencies. Maybe you are simply doing childish stuff and do not handle in the responsibility you should do, when providing such a service.

**Comment by Seldaek** [comment]
Yeah except that any new feature like https://github.com/composer/composer/pull/10798 adding/changing some output of the install/update command would break your CI too, so it's not just "childish stuff". Hence why I think this is not great design for a CI check.

We do offer the lock file to guarantee dependencies are always the same. And/or `composer show --format=json` if you want to see what is installed in a machine readable form.

**Comment by politsin** [comment]
```sh
git clone https://github.com/composer/composer.git --branch 2.4.4  ~/composer-build && \
    composer install  -o -d ~/composer-build && \
    wget https://raw.githubusercontent.com/politsin/snipets/master/patch/composer.patch -q -O ~/composer-build/composer.patch  && \
    cd ~/composer-build && patch -p1 < composer.patch && \
    php -d phar.readonly=0 bin/compile && \
    rm /usr/local/bin/composer && \
    php composer.phar install && \
    php composer.phar update && \
    mv ~/composer-build/composer.phar /usr/local/bin/composer && \
    rm -rf ~/composer-build  && \
    chmod +x /usr/local/bin/composer
```

**Comment by EliasToftHansen** [comment]
I totally agree with the reporter. Why should politics be injected into everything? If I don't "stand with ukraine" I am not allowed to use composer? I am not russian btw. I don't have a problem with Ukraine existing, I DO have a problem with the politics from the west revolving around Ukraine. We just had a three year long pandemic crisis that absolutely wrecked economies of countries all around the world, and now military industrial complexes around the world rile up "do gooders" and ideologes to another round of milking states.
Give us a break please.

**Comment by Winfle** [comment]
@EliasToftHansen you're just pro-russian troll on github and that's it, embraced

**Comment by thenexxuz** [comment]
I just wish there was a way to "opt out" or better yet "opt in" to seeing YOUR personal opinions in MY console. I appreciate the work you've done with these projects but do we really need to have this shoved in our faces EVERYWHERE we go, even the command line!? I get it, you believe one thing, but that doesn't mean everyone needs to hear about it. Imagine if every time you needed to run `grep` it said "Stop Concentration Camps in China" ... the fact that China has them is bad. Period. I don't need the reminder when searching for a file. The same is true here. Putin is an a*****e and shouldn't be invading Ukraine. Period. I don't need to see it when adding a package to my project.
