### ISSUE TITLE
The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed

### ISSUE THREAD

**Issue by sreeraj-ramesh** [composer/composer#10847]
Output of `composer diagnose`:

you are running Composer with SSL/TLS protection disabled.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: WARNING
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
Composer is configured to disable SSL/TLS protection. This will leave remote HTTPS requests vulnerable to Man-In-The-Middle attacks.
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
Checking disk free space: OK
Composer version: 1.6.3
PHP version: 7.2.24-0ubuntu0.18.04.11
PHP binary path: /usr/bin/php7.2

When I run this command: 

while running  ./composer.phar install getting below mentioned error.

I get the following output: 

You are running Composer with SSL/TLS protection disabled.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 91 installs, 0 updates, 0 removals
  - Installing symfony/routing (v4.2.1): Downloading (failed)       
Downloading (failed)       
Downloading (failed)    Failed to download symfony/routing from dist: The "https://api.github.com/repos/symfony/routing/zipball/649460207e77da6c545326c7f53618d23ad2c866" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
    Now trying to download from source
  - Installing symfony/routing (v4.2.1): 
Cloning 649460207e from cache
  - Installing symfony/process (v4.2.1): Downloading (failed)       
Downloading (failed)       
Downloading (failed)    Failed to download symfony/process from dist: The "https://api.github.com/repos/symfony/process/zipball/2b341009ccec76837a7f46f59641b431e4d4c2b0" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
    Now trying to download from source
  - Installing symfony/process (v4.2.1): Cloning 2b341009cc 

And I expected this to happen:

**Comment by Seldaek** [comment]
You seem to have very outdated CA bundle or SSL, I am not sure, but most likely making sure you update PHP, openssl, and possibly your cabundle (see https://manpages.ubuntu.com/manpages/xenial/man8/update-ca-certificates.8.html for ubuntu) is a good idea. I am not sure if Ubuntu 18.04 is still maintained tho.
