### ISSUE TITLE
ANSI output broken with ZOC client for show/info commands

### ISSUE THREAD

**Issue by Gappa** [composer/composer#10842]
ZOC:
- Windows/MacOS SSH client, I'm running it on Windows 10
- https://www.emtec.com/zoc/

My `composer.json`: (isolated test case)

```json
{
    "name": "test/test",
    "require": {
        "php": "^8.0",
        "roave/security-advisories": "dev-master",
        "phpstan/phpstan": "^1.7"
    },
    "autoload": {
        "psr-4": {
            "Test\\Test\\": "src/"
        }
    }
}
```

Output of `composer diagnose`:

```
$ composer diagnose
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest snapshot version, run `composer self-update` to update (2.3.7 => 3e844cc48fb8bdbbdd55a06b7a59312b0cafe764)
Composer version: 2.3.7
PHP version: 8.0.19
PHP binary path: /opt/remi/php80/root/usr/bin/php
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
cURL version: 7.62.0 libz 1.2.7 ssl NSS/3.36
zip: extension present, unzip present, 7-Zip not available
```

When I run this command: 

```
composer info 
```
or
```
composer show
```

I get the following output: 

```
;;https://github.com/phpstan/phpstan/tree/1.7.13phpstan/phpstan;;           1.7.13             PHPStan - PHP Static Analysis Tool
;;https://github.com/Roave/SecurityAdvisories/tree/latestroave/security-advisories;; dev-master bf36209 Prevents installation of composer packages with known security vulnerabilities: no API, simply require it
```

And I expected this to happen:

```
phpstan/phpstan           1.7.13             PHPStan - PHP Static Analysis Tool
roave/security-advisories dev-master bf36209 Prevents installation of composer packages with known security vulnerabilities: no API, simply ...
```

However, when I run the command in Putty, everything is OK. Also, when I run the commands in ZOC with `--no-ansi`, then the output is fine as well.  ZOC runs in xterm emulation mode. I can reach out to the devs, but at this point I need to gather more info :)

Essential info: 
- ZOC 8.04.2
- Composer 2.2.14 and before works as expected. 
- Composer 2.3.0 and greater has this problem.

**Comment by stof** [comment]
I suspect that ZOC does not properly support terminal links (and composer 2.3+ uses them)

**Comment by Gappa** [comment]
Seems like you are spot on. 

[Test command](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#quick-example):

``` bash
printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'
```

ZOC output:
``` 
;;http://example.comThis is a link;;
``` 

Putty output:
``` 
This is a link
``` 

While not (at least by default) clickable in Putty/Kitty, it's not broken.

I'll reach out to ZOC devs.

Thanks :)

**Comment by Gappa** [comment]
It seems that ZOC 8.04.3 (2022-05-07) fixed this issue (the date of release is probably a typo, it should be June, not May - I'll report that, it may get fixed after posting my comment).

- http://www.emtec.com/downloads/zoc/zoc_changes.txt

When I run this command:

`printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'`

I get this:

`This is a link`

Tried `composer info`/ `composer show` - that also works now (i.e. the output is not broken anymore).
