### ISSUE TITLE
FileDownloader does not allow you to specify filename

### ISSUE THREAD

**Issue by mmucklo** [composer/composer#1087]
The simple FileDownloader allows one to specify files, but does not allow one to specify the resultant file name after they are downloaded.  Instead, the url is parsed for a file name at the end.

This behavior is okay as a base case, but an override should be allowable so that one can specify urls that have query strings, or that don't have the actual name of the file in the url.

E.g. this works:

``` json
"dist": {
    "url": "http://www.some-web-site.com/jquery-library-that-you-need.js",
    "type": "file"
}
```

But this fails (especially on Windows which can't even save the file, presumably due to the '?', giving a TrasportException):

``` json
"dist": {
    "url": "http://www.some-web-site.com/somepath.php?some_query_string",
    "type": "file"
}
```

**Comment by anotherjames** [comment]
I agree that being able to specify the target file name to download to, would be very useful.
