### ISSUE TITLE
What is this line??

### ISSUE THREAD

**Issue by nhantr** [composer/composer#10883]
When I ran composer command, I got the line

**Info from https://repo.packagist.org: #StandWithUkraina**

What the hell is that?
Is it a hacker hack the composer?

**Comment by staabm** [comment]
Nope all is fine. 

they just support ukraine 🇺🇦

**Comment by hubertnnn** [comment]
It's a message from the repository. Kinda like a `MOTD` in linux.
Each server can have its own (eg. if you use satis or some kind of proxy).
The official one has this (you can see it in `https://packagist.org/packages.json` as field named `info`)

**Comment by undersound** [comment]
By including this sentence only more division is created. Technical neutrality +1

**Comment by politsin** [comment]
```sh
git clone https://github.com/composer/composer.git --branch 2.4.4  ~/composer-build && \
    composer install  -o -d ~/composer-build && \
    wget https://raw.githubusercontent.com/politsin/snipets/master/patch/composer.patch -q -O ~/composer-build/composer.patch  && \
    cd ~/composer-build && patch -p1 < composer.patch && \
    php -d phar.readonly=0 bin/compile && \
    rm /usr/local/bin/composer && \
    php composer.phar install && \
    php composer.phar update && \
    mv ~/composer-build/composer.phar /usr/local/bin/composer && \
    rm -rf ~/composer-build  && \
    chmod +x /usr/local/bin/composer
```
