### ISSUE TITLE
Argument 2 passed to Composer\Pcre\Preg::isMatch() must be of the type string, null given

### ISSUE THREAD

**Issue by bartlangelaan** [composer/composer#10888]
In the CI (not on my machine) during a `composer create-project`, this error occurs:

```
    Exception trace:
      at /app/.global/composer/composer/vendor/composer/pcre/src/Preg.php:233
     Composer\Pcre\Preg::isMatch() at /app/.global/composer/composer/vendor/composer/composer/src/Composer/Downloader/GitDownloader.php:475
     Composer\Downloader\GitDownloader->updateToCommit() at /app/.global/composer/composer/vendor/composer/composer/src/Composer/Downloader/GitDownloader.php:138
     Composer\Downloader\GitDownloader->doInstall() at /app/.global/composer/composer/vendor/composer/composer/src/Composer/Downloader/VcsDownloader.php:137
     Composer\Downloader\VcsDownloader->install() at /app/.global/composer/composer/vendor/composer/composer/src/Composer/Downloader/DownloadManager.php:279
     Composer\Downloader\DownloadManager->install() at /app/.global/composer/composer/vendor/composer/composer/src/Composer/Installer/LibraryInstaller.php:282
     Composer\Installer\LibraryInstaller->installCode() at /app/.global/composer/composer/vendor/composer/composer/src/Composer/Installer/LibraryInstaller.php:155
     Composer\Installer\LibraryInstaller->install() at /app/.global/composer/composer/vendor/composer/composer/src/Composer/Installer/InstallationManager.php:528
```

I think this is related to https://github.com/composer/pcre/commit/2e56743e50b72279aeb01ed2c9fcbf9f9d7a92d6, #10662 and 0708eb45e5801ef2682f2af8635237eb5f025ddb.

Looking at the code, I could see how this could possibly go wrong:

https://github.com/composer/composer/blob/10cd375cf85dede2ff417ceab517ef9a0dc55407/src/Composer/Downloader/GitDownloader.php#L455-L458
https://github.com/composer/composer/blob/10cd375cf85dede2ff417ceab517ef9a0dc55407/src/Composer/Downloader/GitDownloader.php#L472-L477

So, it seems like the `$branches` var is used while it is null.
However, it's hard for me to check if adding a `&& $branches` to the outer if-statement is enough to fix this issue, because this error only happens in the CI for me. But it seems like a good thing to do anyway.

**Comment by Seldaek** [comment]
Do you not have git installed on CI, or why is it failing to execute `git branch -r`? Or maybe you cache vendor dir but not the .git dirs within?

I mean we need to fix this regardless, but I am curious how you reach this code path.

**Comment by brunoborghi** [comment]
Interesting...

On CI this error occurs:

`[TypeError]
  Argument 2 passed to Composer\Pcre\Preg::matchAll() must be of the type str
  ing, null given, called in phar:///home/storage/1/b4/d8/highprinting/public
  _html/caixabox/composer.phar/vendor/composer/class-map-generator/src/PhpFil
  eParser.php on line 55`

Trace:
`at phar:///.../composer.phar/vendor/composer/pcre/src/Preg.php:67
 Composer\Pcre\Preg::matchAll() at phar:///.../composer.phar/vendor/composer/class-map-generator/src/PhpFileParser.php:55
 Composer\ClassMapGenerator\PhpFileParser::findClasses() at phar:///.../composer.phar/vendor/composer/class-map-generator/src/ClassMapGenerator.php:176
 Composer\ClassMapGenerator\ClassMapGenerator->scanPaths() at phar:///.../composer.phar/src/Composer/Autoload/AutoloadGenerator.php:314
 Composer\Autoload\AutoloadGenerator->dump() at phar:///.../composer.phar/src/Composer/Installer.php:343
 Composer\Installer->run() at phar:///.../composer.phar/src/Composer/Command/UpdateCommand.php:240
 Composer\Command\UpdateCommand->execute() at phar:///.../composer.phar/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar:///.../composer.phar/vendor/symfony/console/Application.php:1028
 Symfony\Component\Console\Application->doRunCommand() at phar:///.../composer.phar/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at phar:///.../composer.phar/src/Composer/Console/Application.php:370
 Composer\Console\Application->doRun() at phar:///.../composer.phar/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///.../composer.phar/src/Composer/Console/Application.php:138
 Composer\Console\Application->run() at phar:///.../composer.phar/bin/composer:88
 require() at /.../composer.phar:29`

I'm using version 2.4.2. Could it have something to do with this error?

**Comment by Seldaek** [comment]
@brunoborghi that is an unrelated issue, but I wonder how that is possible at all. The $contents / arg #2 here https://github.com/composer/class-map-generator/blob/main/src/PhpFileParser.php#L55 should always be a string as php_strip_whitespace can only return a string, and as per https://3v4l.org/r4kMa it seems to be the case even for non-existent paths.

It doesn't make sense to me how it'd be null.
