### ISSUE TITLE
Info from https://repo.packagist.org

### ISSUE THREAD

**Issue by galexth** [composer/composer#10889]
How to remove this?
```
Info from https://repo.packagist.org: #StandWithUkraine
```

**Comment by herndlm** [comment]
You can play around with different output stream redirections. `grep -v` also works quite well to remove single lines I heard.

**Comment by felloz** [comment]
How can I remove this nonsense?

**Comment by geri777** [comment]
I tried `composer remove ukeloop/stand-with-ukraine` and `composer global remove ukeloop/stand-with-ukraine` but composer says, this package is not installed and therefore not removed. To me this is a clear abuse of the info system for non technical purposes.

**Comment by bdaler** [comment]
https://github.com/composer/packagist/pull/1357 :)

**Comment by instance-pro** [comment]
It's time to create a non-political fork

**Comment by mykyta-nikiforov-sombra** [comment]
Remove russia form the map of the world first :)
