### ISSUE TITLE
Config.php ("allow-plugins") : Expected parameter 1 to be an array, bool given

### ISSUE THREAD

**Issue by Striffly** [composer/composer#10907]
**My `composer.json`:**

```json
{
  "config": {
    "allow-plugins": true
  }
}
```

**Output of `composer diagnose`:**

```
array_merge(): Expected parameter 1 to be an array, bool given
```

**When I run this command**:

```
composer install
```

**I get the following output:**

```
In Config.php line 192:
                                                                  
  [ErrorException]                                                
  array_merge(): Expected parameter 1 to be an array, bool given  
                                                                  

Exception trace:
  at phar:///usr/local/bin/composer/src/Composer/Config.php:192
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 array_merge() at phar:///usr/local/bin/composer/src/Composer/Config.php:192
 Composer\Config->merge() at phar:///usr/local/bin/composer/src/Composer/Factory.php:326
 Composer\Factory->createComposer() at phar:///usr/local/bin/composer/src/Composer/Factory.php:615
 Composer\Factory::create() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:470
 Composer\Console\Application->getComposer() at phar:///usr/local/bin/composer/src/Composer/Command/BaseCommand.php:122
 Composer\Command\BaseCommand->tryComposer() at phar:///usr/local/bin/composer/src/Composer/Command/BaseCommand.php:200
 Composer\Command\BaseCommand->initialize() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:1024
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:335
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:130
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:88
 require() at /usr/local/bin/composer:29

install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]
```

[Documentation](https://getcomposer.org/doc/06-config.md#allow-plugins) stated that it would no longer be allowed to have a `null` value as of July 2022. However, this was not supposed to happen with `true`.

**Comment by nlzet** [comment]
Same problem here, for now we can fix it by setting individual plugins to true, instead of just true

So this works:

    "allow-plugins": {
         "test/plugin": true
    }

This doesn't:

    "allow-plugins": true

**Comment by aschempp** [comment]
see https://github.com/composer/composer/pull/10909 for a possible fix

**Comment by beeyev** [comment]
As I see the fix https://github.com/composer/composer/pull/10909 was merged, so when the new version will be released?

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/pull/10909 - and 2.2.15 / 2.3.8 are now released.

**Comment by SvenRtbg** [comment]
Just for the record: The same bug appeared with `allow-plugins: false`, but this also has been fixed.

**Comment by dzuelke** [comment]
I love y'all, @Seldaek and @naderman, but can we maybe agree that **any** time/date based logic like this is a **bad, bad** idea?

On Heroku, PHP apps execute `composer config bin-dir` on startup. Any app deployed within the last ~year (built with a Composer version that includes a3e91b5be6a886da6df701695c8518aba50b8d07) that uses an affected value for `allow-plugins` is now failing to boot until a redeploy that updates the Composer version to either of the latest 2.2/2.3 releases... :(

**Comment by Seldaek** [comment]
Yes, I know I fucked up not testing this thoroughly beforehand.. It was meant as a nice way to get people to migrate more slowly. Live and learn [🤷‍♂️](https://www.youtube.com/watch?v=W2WNYjfvktw)

**Comment by dzuelke** [comment]
Well, it's obviously not trivial to write a test for :)

**Comment by weirdvic** [comment]
Hello I think i was able to reproduce this exact bug today
`Composer version 2.3.9 2022-07-05 16:52:11`
`composer.json` was containing
```
{
  "config": {
    "allow-plugins": true
  }
}
```
Had to use the workaround proposed by @nlzet: manually allow every used plugin

**Comment by Seldaek** [comment]
@weirdvic if you have a way to reproduce it with latest composer version please share more details.

**Comment by keramsey** [comment]
I received this error when attempting to run composer self-update from the folder that contains composer.json and composer.lock. 

I was running composer 2.3.5 at the time. 

I was only able to update composer after switching to my home directory and using sudo:
sudo composer self-update

That allowed me to update composer (non-root).

**Comment by stof** [comment]
Well, composer 2.3.5 was not the latest composer version. It was one of the version containing the buggy code.

**Comment by keramsey** [comment]
Yes, I know. I was not able to update to the latest composer as non-root user without changing to user's home directory and running the composer self-update using sudo. I posted this here in case others have similar issues upgrading composer when using 'allow-plugins: true'.

**Comment by weirdvic** [comment]
@Seldaek
Sorry for the long answer.
My problem was Docker's build cache. After flushing Docker build cache and rebuilding the image the issue has gone.

**Comment by ElectronicKriss** [comment]
> Yes, I know. I was not able to update to the latest composer as non-root user without changing to user's home directory and running the composer self-update using sudo. I posted this here in case others have similar issues upgrading composer when using 'allow-plugins: true'.

Thank you for posting it, cd to root location works
