### ISSUE TITLE
OpenSSL SSL_connect: Connection reset by peer in connection to api.github.com:443

### ISSUE THREAD

**Issue by ayan013** [composer/composer#10905]
I am facing issue while cloning any repository or downloading/installing packages using composer. I think composer is installed properly.  

![image](https://user-images.githubusercontent.com/1405995/176691137-9f0c1a76-b705-4d39-bb71-36d2662a07a6.png)

I am using Corporate VPN and not aware about firewall settings.
Ubuntu - 20.04 and php - 7.4

curl https://github.com
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to github.com:443

openssl s_client -connect github.com:443 -servername github.com
![image](https://user-images.githubusercontent.com/1405995/176691858-db1d6845-048f-4661-8879-8637452eced3.png)

curl -v -I https://github.com
![image](https://user-images.githubusercontent.com/1405995/176692384-4279febc-4bcd-4321-9bac-983b0fd65dee.png)

**Comment by Seldaek** [comment]
If `curl` fails to connect as well it's definitely not a Composer issue, but must be something in your environment/network.

It seems the TLS handshake fails entirely, so I guess it's a network problem.

FYI I get this output from openssl:

```
$ openssl s_client -connect github.com:443 -servername github.com
CONNECTED(00000003)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, CN = DigiCert TLS Hybrid ECC SHA384 2020 CA1
verify return:1
depth=0 C = US, ST = California, L = San Francisco, O = "GitHub, Inc.", CN = github.com
verify return:1
---
Certificate chain
 0 s:C = US, ST = California, L = San Francisco, O = "GitHub, Inc.", CN = github.com
   i:C = US, O = DigiCert Inc, CN = DigiCert TLS Hybrid ECC SHA384 2020 CA1
   a:PKEY: id-ecPublicKey, 256 (bit); sigalg: ecdsa-with-SHA384
   v:NotBefore: Mar 15 00:00:00 2022 GMT; NotAfter: Mar 15 23:59:59 2023 GMT
 1 s:C = US, O = DigiCert Inc, CN = DigiCert TLS Hybrid ECC SHA384 2020 CA1
   i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
   a:PKEY: id-ecPublicKey, 384 (bit); sigalg: RSA-SHA384
   v:NotBefore: Apr 14 00:00:00 2021 GMT; NotAfter: Apr 13 23:59:59 2031 GMT
---
```

**Comment by ayan013** [comment]
I get the right output for google.com or cisco.com but not able to SSL handshake with github.com using openssl

**Comment by Celtiii** [comment]
Thats MY Issue too

**Comment by homayoonprs** [comment]
> Thats MY Issue too

me too, same problem

**Comment by kokabi1365** [comment]
Maybe this will help:
https://stackoverflow.com/a/73877939/579381

**Comment by Davidclintoo** [comment]
Check on your Local Area network , it seems that you are under unauthorized internet connection. I also faced the same problem but I solved it by changing my internet connection. I was using VPN when the error popped up. If that is not the case then you can check on your proxy server.

**Comment by Rishiyogi** [comment]
![image](https://user-images.githubusercontent.com/71979682/226084645-0d550dc9-1c65-40dc-b13d-923f4644838d.png)

**Comment by tinybug-m** [comment]
> When trying to install HYPERLEDGER in Ubuntu WSL2 i was getting openSSL error and unable to pull any ![image](https://user-images.githubusercontent.com/71979682/226084645-0d550dc9-1c65-40dc-b13d-923f4644838d.png)

dudeeee it fixed my problemmm
git config --global  --unset-all remote.origin.proxy

so happy:D
