### ISSUE TITLE
Composer cannot find package. Packagist says it can.

### ISSUE THREAD

**Issue by codeguy** [composer/composer#1090]
I'm triyng to release a new version of my Slim Framework. I've pushed tag 2.0.0 to GitHub. I've force updated Packagist. Packagist now shows it knows about 2.0.0. See:

http://packagist.org/packages/slim/slim

However, when I attempt to install the new version on my local computer, it fails with this error:

```
Loading composer repositories with package information
Installing dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package slim/slim 2.* could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.
```

My composer.json file is:

```
{
    "require": {
        "slim/slim": "2.*"
    }
}
```

Thoughts? Was hoping to launch today but this issue is blocking release.

Thanks!
Josh

**Comment by techqjyd** [comment]
It's broken again.
I submitted this package:
[https://packagist.org/packages/techqjyd/aliyun-oss](https://packagist.org/packages/techqjyd/aliyun-oss)

and then run `composer search techqjyd/aliyun-oss`，the package is not in result list.

**Comment by Seldaek** [comment]
It's there alright: `composer search techqjyd/aliyun-oss -N` shows it, it's just not ranked high in the search results for some reason so without -N it doesn't appear in the first page of results.
