### ISSUE TITLE
Feature: Environment variable to trigger `--prefer-lowest`

### ISSUE THREAD

**Issue by ciaranmcnulty** [composer/composer#10919]
This would be very useful in a CI environment, where currently we are juggling around `COMPOSER_FLAGS` type variables and interpolating them into the CLI

**Comment by Seldaek** [comment]
True :) Should be easy enough to add if you wanna PR.

**Comment by ciaranmcnulty** [comment]
`Should be easy enough to add if you wanna PR.`

Oh I see how it is 😂

**Comment by Seldaek** [comment]
I'll try and get to it if nobody else does as I absolutely do see the value, but not sure if it'll make the cut for 2.4 if it comes down to me.

**Comment by ciaranmcnulty** [comment]
Same here; if I have time to grok the codebase vs other projects
