### ISSUE TITLE
If archive checksum doesn't match try second time before failing

### ISSUE THREAD

**Issue by ghost** [composer/composer#1091]
This exception occured to me twice already. Re-running composer works fine with the same archive. (I am using mobile internet so there may be some lost packets involved?)

**Comment by spengilley** [comment]
This hasn't been commented on for a long time. It looks like this hasn't been implemented in code. I am happy to implement this behaviour

**Comment by Seldaek** [comment]
Oh sorry this is just outdated issues.. Should be closed really, I don't think it's relevant at all anymore.

**Comment by spengilley** [comment]
No problem :)
