### ISSUE TITLE
`psr/log` is not consistent

### ISSUE THREAD

**Issue by kayw-geek** [composer/composer#10911]
> **Note**
> I was making a library that will dispatch composer event into Laravel event, but I get into trouble for `psr/log` of depend on Laravel with `psr/log` of depend on composer version not consistent, so how should I solve it 

```PHP
Declaration of Psr\Log\AbstractLogger::emergency(Stringable|string $message, array $context = []): void must be compatible with Psr\Log\LoggerInterface::emergency($message, array $context = [])
```

**Comment by Seldaek** [comment]
I don't see how this relates to the Composer repository sorry. It looks like you have a half-way synced package or something, if you have a way to reproduce this you can explain but right now i don't see what we can do here.

**Comment by kayw-geek** [comment]
> I don't see how this relates to the Composer repository sorry. It looks like you have a half-way synced package or something, if you have a way to reproduce this you can explain but right now i don't see what we can do here.

The `psr/log` of depend on Composer version is 1.x, because composer still support PHP version 7.2.5, but I dispatched composer script event into Laravel event and  this `psr/log` library depend on `laravel/framework` and that version is 3.x in my library, because the `psr/log` library changed return type of interface, Do you have any goods suggestions?

**Comment by Seldaek** [comment]
Hmm no if you need to run things inside the Composer process I don't see a good suggestion to fix this, I think what happens is the LoggerInterface gets loaded first from Composer sources, and then AbstractLogger gets loaded from vendor dir whenever you load some class relying on it.

**Comment by kayw-geek** [comment]
Thanks your suggestions, it's very helpful  for me.
