### ISSUE TITLE
Official `composer` docker images are not built automatically

### ISSUE THREAD

**Issue by boesing** [composer/composer#10926]
Hey there,

it seems that 2.3.6 was already missing (and reported in #10825), 2.3.7 was then added to dockerhub but 2.3.8 was missing and now is 2.3.9.

I guess 2.3.9 is okayish since its only released for about 2 hours but I am not sure if 2.3.8 should be missing.
Is there a location where contributors can have a look at and probably provide fixes for the problems which might occur?

Is https://github.com/composer/docker the correct repository?
Maybe it is possible to trigger workflows via GHA after a successful release/tag creation so that there is not only created a new issue in that repository?

Happy to be of help.

**Comment by stof** [comment]
https://github.com/composer/docker is indeed where Docker images are managed. And the readme explains the process, showing which steps are automated and which are manual.

**Comment by boesing** [comment]
Ah I see. Maybe consider pushing another image to the github docker image host?
That can be automated (we do that in https://github.com/laminas/laminas-ci-matrix-action and https://github.com/laminas/laminas-continuous-integration-action for example) and thus, the manual process can still stay in-place. 

But it seems to be kinda complicated and even delayed when one has to manually create stuff :-/

**Comment by Seldaek** [comment]
I think it'd be great to automate further if possible, maybe you can talk to @alcohol if you wanna help, I can help setup any credentials needed in the secrets.

**Comment by boesing** [comment]
It seems that it is the process who lets not automate this further.
The question would be if composer is open to publish the images via the current process *PLUS* pushing it to the github docker image hosting platform.

If so, it would be possible to automate the latter while keeping the manual process for the docker official libraries.
But I have no idea if thats something you guys might want to consider or not.

**Comment by Seldaek** [comment]
We already push to two diff dockerhub ones. Official and ours. And then the AWS repo too. So I guess we could add gh.. But I'd like to ensure everything but the official dockerhub gets auto-pushed in sync then otherwise it'll be a mess.

**Comment by boesing** [comment]
All the repos you are listing are actually on built when someone takes manual action within `composer/docker`, right?

If thats the case, I'll try and see how that could be further automated but if its already created automatically, I guess I could simply use the automated ones and thus don't need to use the official docker image for my purpose 👍🏼

**Comment by Wirone** [comment]
@boesing please have in mind composer/docker#250 while looking at this 🙂 

@Seldaek is it possible to publish 2.3.10 to Docker Hub? As far as I see it's not available in [official image](https://hub.docker.com/_/composer) nor [`compose/composer`](https://hub.docker.com/r/composer/composer).

**Comment by stof** [comment]
@Wirone the work on 2.3.10 is not merged yet. See https://github.com/composer/docker/pull/253

**Comment by Seldaek** [comment]
Note that we also push to GitHub docker repo now https://github.com/composer/docker/pkgs/container/docker
