### ISSUE TITLE
Idea: `composer update --bump`

### ISSUE THREAD

**Issue by enumag** [composer/composer#10934]
I just read about the new [`composer bump`](https://php.watch/articles/composer-bump) command in Composer 2.4 and got an idea.

It's relatively often that I find a bug in one of the libraries we're using, then I send a MR to get it fixed and of then of course I need to update my project to use the fixed version. Now this is ofc easily done with `composer update vendor/library`, however the fix is often very much necessary so ideally I need to also change the version constraint in `composer.json` to disallow any older versions. Now with the `bump` command I can instead do this:

```
composer update vendor/library
composer bump vendor/library
```

But it would be nicer to have this simplified to single command like this which would both update the dependency and change the constraint in composer.json to the updated version:

```
composer update vendor/library --bump
```

What do you think?

**Comment by Seldaek** [comment]
I discussed this quite extensively with @naderman and we came to the conclusion we would not do this for now at least. First gather usage experience with `bump` command and then see if this is really needed.

Here are reasons speaking against it:

- Separation means `bump` is a clearly defined step, which can have its own options etc, vs bundling it into the update command which raises complexity there and may have weird side-effects like what should be the effect of --with-all-dependencies on --bump?
- While I see your use case, I don't think it should be the rule that every update requires a bump of dependencies, so hopefully the added step of having to explicitly run the bump command after is not that much of a hurdle.
- The update command currently does not modify the composer.json and changing that would be changing assumptions there, which we aren't super keen on doing without good reason.

So I'll close this for now, let's revisit if someone still thinks it's a total must in a few months I'd say.

**Comment by enumag** [comment]
Thanks for the well written feedback! Those are indeed great points. Revisiting the idea later when the bump command isn't completely new sounds good.

**Comment by curry684** [comment]
I agree these operations should never be merged, as their operation and results could not be separated more.

- `update` by its very definition causes  *instability*. It should be *followed* by extensive testing to check for problems in newly updated libraries.
- `bump` by its very definition causes *stability*. It should be *preceded* by extensive testing to ensure the currently resolved set of packages is a valid baseline which should remain enforced for future updates.

The correct order is updates, test, bump. The operations are thus simply not supposed to be executed one after another, and are therefore no candidates for merging even if you ignore the other, valid, comments made above.

**Comment by naderman** [comment]
Just for the record, if someone else stumbles over this, this eventually got implemented in the form of --bump-after-update and a config flag, see:

- https://github.com/composer/composer/issues/11906
- https://github.com/composer/composer/pull/11942
