### ISSUE TITLE
Including composer.json in a dependency-free library package

### ISSUE THREAD

**Issue by ashipde** [composer/composer#10944]
I am new to Composer and am posting here because I cannot find an answer online. I maintain a single-file, dependency-free PHP library and have been requested to facilitate Composer-based installation of the library by developers who use it for their projects.

The library is not on Packagist but I have set up a Composer-type repository on my server with a packages.json file and zip files of download packages of various versions of my library. Since the library has no dependency, the composer.json only declares the repository information of the library itself. My goal is to facilitate Composer-based update of the library by maintainers of projects that use the library. Is this goal achieved without any problem by including the composer.json file?
```
{
    "name": "my/myLib",
    "type": "library",
    "require": {
        "php": ">=4.4"
    },
    "repositories": [
        {
         "type": "composer",
         "url": "myUrl"
        },
        {
         "type": "composer",
         "url": "myUrlAlt"
        },
    ]
}
```
_Cross-posted on [Stackoverflow](https://stackoverflow.com/questions/72972708/can-i-include-a-composer-json-file-in-the-download-package-of-the-dependency-fre)_

**Comment by Seldaek** [comment]
My first question is why not publish it on packagist.org? If it is open source and you have a git repo somewhere that would be the easiest option.

If it's not open source and you are selling access to the code you may want to look at private packagist (packagist.com/vendors) which is also not free but offers a bunch of ways to manage access as well as host your package and upload it from zip or git etc

If none of that makes sense to you then I wonder why but anyway you can for sure host your own composer repo, in which case you don't even need the composer.json file tbh, the repository just has to provide the package Metadata to make the package installable. You can find more info here https://getcomposer.org/doc/05-repositories.md#composer

**Comment by ashipde** [comment]
Thank you for your thoughts. I am not using Packagist because the free service only supports git/svn/hg repository type, which my package doesn't satisfy, and the paid service is beyond my means.  //  My thought in having a composer.json is that some project that uses the library will have an easier time to update the library since repository information will be in the composer.json file. As someone on Stackoverflow noted, [some](https://github.com/phpstan/phpstan/blob/1.8.1/composer.json) projects do this.

**Comment by stof** [comment]
Having the repositories listed in the composer.json of your library won't help. To be usable, it needs to be listed in the composer.json of projects wanting to use your repo. So that's something to describe on your website instead.

**Comment by ashipde** [comment]
Thank you @stof. So it seems a composer.json won't have any Composer functionality; it'll be just a text file with repo info.
