### ISSUE TITLE
bug / docs error for getInstallPath()

### ISSUE THREAD

**Issue by joachim-n** [composer/composer#10945]
The docs at https://getcomposer.org/doc/07-runtime.md say:

> The getInstallPath method to retrieve a package's absolute install path.

However, with a package that is installed from a local repository, doing 

```
    dump(\Composer\InstalledVersions::getInstallPath('drupal-code-builder/drupal-code-builder'));
```

shows:

> /Users/joachim/Sites/dcb-repos-9/vendor/composer/../drupal-code-builder/drupal-code-builder

It's an absolute path in that it starts from the filesystem route but I'd expect an absolute path to also have the '..' resolved.

My composer.json uses a path repository so that the package is symlinked in:

```
    "repositories": [
        {
          "type": "path",
          "url": "repos/drupal-code-builder"
        },
```

I'm not sure if this is a bug or by design, but if it's by design the docs should mention it.

**Comment by Seldaek** [comment]
That is true, thanks. I hope this clarifies things well enough for you. Path repos are definitely a cause, custom installer plugins returning relative paths or so may also trigger this I believe.

**Comment by joachim-n** [comment]
That's perfect, thanks!
