### ISSUE TITLE
Composer snapshot version outputs false warning message

### ISSUE THREAD

**Issue by alexander-schranz** [composer/composer#10942]
It seems like the current snapshot version does try on composer create-project try to installation old version and outputs a warning. This warning is a little bit strange as it reference to a very old version. Still composer itself behaves correctly install the latest 2.5.0 version. 

My `composer.json`:

None.

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK git version 2.37.0
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.4-dev+37d3e2f44a2f0f7ee3669dac0b587c98f7673cfc
PHP version: 8.1.6
PHP binary path: /opt/homebrew/Cellar/php/8.1.6/bin/php
OpenSSL version: OpenSSL 1.1.1o  3 May 2022
cURL version: 7.83.1 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1o
zip: extension present, unzip present, 7-Zip not available
```

When I run this command: 

```bash
composer self-update --snapshot
composer create-project sulu/skeleton
```

I get the following output: 

```
Cannot use sulu/skeleton's latest version 2.2.4 as it requires php ^7.2 which is not satisfied by your platform
```

![Bildschirmfoto 2022-07-13 um 18 13 26](https://user-images.githubusercontent.com/1698337/178781454-1d55edfc-35d7-49cf-8096-91d2eb0fc114.png)

When do the same with PHP 7.2 it correctly install 2.4.4 and outputs corrects can not install 2.5.0. So the behaviour of composer itself is in all cases correctly just the warning message is strange. This is the tagged: [2.2.4](https://github.com/sulu/skeleton/releases/tag/2.2.4) all looks correctly not sure why it think it is latest version in this case. Even nothing was changed on that tags.

And I expected this to happen:

Not showing this warning.

**Comment by Seldaek** [comment]
Thanks for spotting this. It may be a version order issue or something. I expected it would try them highest to lowest but maybe that's not the case.

**Comment by Seldaek** [comment]
OK it was just a dumb mistake, it filtered out by platform first so you'd get warnings for *every* version. I just didn't notice because I tested with a specific package..

Anyway fixed now in https://github.com/composer/composer/commit/9fbc386a7b88b37c63f93f16d3086cc5baf49683, I'll however leave this issue open because it somehow triggered a bug in github (this issue does not show up in https://github.com/composer/composer/milestone/29 despite it saying there is one issue.. I almost forgot about it 😅) and I'd like them to be able to look at it.

Just in case again: **Please do not close the issue!**

**Comment by Seldaek** [comment]
Well, GitHub says they reindexed the repo but it doesn't seem to have helped and they don't seem to care, so closing :P
