### ISSUE TITLE
Composer trying to install older version despite incompatibility and newer one being available

### ISSUE THREAD

**Issue by Meryl** [composer/composer#10943]
My `composer.json`: 

`
{
}
`

(yes it's supposed to be empty, problem occurs even without a composer.json present in an otherwise empty directory)

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.3.10
PHP version: 8.0.13
PHP binary path: C:\Program Files\PHP\php.exe
OpenSSL version: OpenSSL 1.1.1l  24 Aug 2021
cURL version: 7.76.1 libz 1.2.11 ssl OpenSSL/1.1.1l
zip: extension present, unzip not available, 7-Zip present (7z)
```

When I run this command: 

```
composer require "twig/twig:^3.0"
```

I get the following output: 

```
./composer.json has been updated
Running composer update twig/twig
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires twig/twig 3.0 -> satisfiable by twig/twig[v3.0.0].
    - twig/twig v3.0.0 requires php ^7.2.9 -> your php version (8.0.13) does not satisfy that requirement.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

And I expected this to happen:

It to install a version higher than 3.0 but lower than 4.0 which is compatible with my version of PHP.

**Comment by Seldaek** [comment]
As you can see in "requires twig/twig 3.0" it seems your shell ate the ^ away. IIRC cmd or powershell tends to do that if not quoted somehow. Try ^^ (doubling it) or Google it :)

**Comment by Seldaek** [comment]
Marking this as a bug not because we can fix the shell parsing, but perhaps we could warn if on windows and require receives an exact version (especially if it's not a x.y.z full exact version) then it most likely is an input error.

**Comment by johnstevenson** [comment]
> As you can see in "requires twig/twig 3.0" it seems your shell ate the ^ away

I'm not so sure about this because the caret in `composer require "twig/twig:^3.0"` is not treated as a special character when it is enclosed in double-quotes:

```
// quoted - caret has no special meaning inside double-quotes
$ echo "twig/twig:^3.0"
"twig/twig:^3.0"

// unquoted - caret means next character is treated as literal and the caret is removed
$ echo twig/twig:^3.0
twig/twig:3.0
```

**Comment by Seldaek** [comment]
Yeah we'll need input from @Meryl here but the bottom line is the output indicates composer just received 3.0 as constraint.

**Comment by Meryl** [comment]
I agree with John that it's unlikely it was actually eaten by the shell. I had it quoted and I made a tiny test case (basically a print_r of $argv) and gave that the same input, and that came through just fine. Is there an easy way for me to test what the actual value is that Composer is receiving from the shell?

**Comment by Meryl** [comment]
Never mind. It definitely **is** related to the shell, specifically Powershell in this case. I just tried running it in the regular shell (that is cmd.exe) and it works fine there. What's weird to me is that the problem occurs when the string is quoted and the fact that my test case seems to receive the string just fine.

**Comment by Seldaek** [comment]
Do you have xdebug installed? Could be a bug in the xdebug-handler restart?

Try running with COMPOSER_ALLOW_XDEBUG=1 see if it fixes it.

**Comment by johnstevenson** [comment]
I specifically tested  the xdebug-handler restart before I posted (just in case I had screwed something up there), and it quoted everything fine, with the caret being preserved in the restarted command line args.

@Meryl Try running `echo twig/twig:^3.0` and `echo "twig/twig:^3.0"` in Powershell (echo is a built-in alias for Write-Host). In both cases for me it produces `twig/twig:^3.0`.

**Comment by Meryl** [comment]
> @Meryl Try running echo twig/twig:^3.0 and echo "twig/twig:^3.0" in Powershell (echo is a built-in alias for Write-Host). In both cases for me it produces twig/twig:^3.0.

For me also.

**Comment by Seldaek** [comment]
Just FYI https://github.com/composer/composer/commit/740af2bdb16ce9249da9b7266ee49e67b679f336 should now warn - you can try after a `composer self-update --snapshot` see what happens..

**Comment by Meryl** [comment]
Yeah, I see the warning when I run the command on that version. I'm not sure exactly how much this would've helped me find out it was actually eating my caret-character though. Perhaps the documentation at https://getcomposer.org/constraints could show a warning about this issue so long as it exists? 

As far as the issue itself goes, I'm not entirely convinced it's not solvable. The absolutely minimal test I ran suggests that it's entirely possible to correctly receive these characters. For reference, what I did was create a file cmdline-test.php:

```
<?php

print_r($argv);
```

and ran `php cmdline-test.php "twig/twig:^3.0"` and the output was

```
Array
(
    [0] => cmdline-test.php
    [1] => twig/twig:^3.0
)
```

As expected. Doesn't this suggest that it would be possible for Composer to receive the correct string?

**Comment by Seldaek** [comment]
Yes that does suggest it.. But I am still not sure where it vanishes, as this works fine here for me:

```
$ c req "twig/twig:^3.0"
./composer.json has been updated
Running composer update twig/twig
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 3 installs, 0 updates, 0 removals
  - Locking symfony/polyfill-ctype (v1.26.0)
  - Locking symfony/polyfill-mbstring (v1.26.0)
  - Locking twig/twig (v3.4.1)
```

Have you tried `COMPOSER_ALLOW_XDEBUG=1` in env vars to make absolutely sure it's not the xdebug restart? I just can't imagine what else.. But you can clone Composer and try and figure out where it gets lost otherwise.

**Comment by Meryl** [comment]
I don't have xdebug installed on this machine, so I don't see that making a difference. I tried it nonetheless, but as expected this didn't change anything.

I cloned Composer to see if I could track it down, but the problem doesn't exist there for me. Not by running it out of bin nor as a compiled phar.

**Comment by Seldaek** [comment]
Could it come from the bat file or whatever you're usually using to run composer then? How does that look? `where composer` can help locate it.

**Comment by Meryl** [comment]
That seems to be it. My composer.bat contains:

```
@echo OFF
:: in case DelayedExpansion is on and a path contains ! 
setlocal DISABLEDELAYEDEXPANSION
php "%~dp0composer.phar" %*
```

I replaced `php` with `echo` and I re-ran the command and the output was:

`"C:\ProgramData\ComposerSetup\bin\composer.phar" require twig/twig:3.0`

This is still an escaping issue after all. Turns out to get it to work I have to escape it twice. Probably once for powershell, and once for the bat file. So running `composer require twig/twig:^^^^3.0` results in the correct constraint being received.

**Comment by Seldaek** [comment]
Alright - then maybe it's something to be fixed in the windows exe setup, or maybe you just have a very outdated bat file and it's already been fixed. @johnstevenson will surely know more :)

**Comment by johnstevenson** [comment]
All I know is that I think this is Powershell thing. The `%*` expansion just fowards the command line as is and can be tested by changing the bat file to:

```bat
@echo OFF
:: in case DelayedExpansion is on and a path contains ! 
setlocal DISABLEDELAYEDEXPANSION
php "%~dp0testargs.php" %*
``` 

where `testargs.php` in the same folder is:

```php

<?php

print_r($argv);
```

Using cmd the caret is preserved:

```
$ composer require "twig/twig:^3.0"
Array
(
    [0] => C:\ProgramData\ComposerSetup\bin\testargs.php
    [1] => require
    [2] => twig/twig:^3.0
)
```

But with Powershell it is eaten:

```
$ composer require "twig/twig:^3.0"
Array
(
    [0] => C:\ProgramData\ComposerSetup\bin\testargs.php
    [1] => require
    [2] => twig/twig:3.0
)
```
The only way to get Powershell to preserve the caret is to use 4 of them, either quoted or not: `twig/twig:^^^^3.0`

**Comment by Meryl** [comment]
It seems that Powershell basically passes the arguments to the batch file in such a way that quotes etc. aren't preserved. It would explain why it needs double escaping, once for Powershell and once for the batch file.

Similar issues occurred with other characters that can appear in Composer's version constraints (specifically the space-character, <, > and |) that essentially made the composer command virtually unusable for me from within Powershell.

It can be fixed with this powershell script:
```$cmd = 'composer.bat '
foreach ($a in $args[0..($args.length-1)]) {
    $cmd += " ";
    if ($a -match "[\^\>\<| ]") {
        $cmd += """$a"""
    } else {
        $cmd += $a
    }
}
cmd /C $cmd ```

By placing this in the same folder as composer.bat as `composer.ps1` it fixes everything in Powershell and it doesn't interfere with running it from cmd.

@johnstevenson do you see value in adding this to the windows setup?

**Comment by driesvints** [comment]
@Seldaek is it maybe an idea that Composer auto-replaces the caret symbol behind the scenes from `^` to `^^^^`? That way things should work on all OS I think?

**Comment by RamyTalal** [comment]
@driesvints I think the `^` is stripped before it is passed to Composer.

**Comment by driesvints** [comment]
If it's all the same, I'd like to drop a mention here so the bot doesn't closes it so maybe at some point someone would have any insight in how we can fix this.

**Comment by Thraxll** [comment]
Still an issue.

**Comment by Seldaek** [comment]
Closing as I don't see how we can possibly fix this on our end.. I'd recommend people use WSL and bash instead of cmd, as that makes the CLI on windows much more bearable in more ways than one.

On a more positive note, these days Composer is much better at figuring out the version so you're generally better off using `composer require` without version constraint and let it figure it out.
