### ISSUE TITLE
create-project should explain which platform requirements cannot be met

### ISSUE THREAD

**Issue by stof** [composer/composer#10959]
Currently, when no version of the package is compatible with the platform, `create-project` fails, but there is no way to know why.

It should display the missing extensions, similar to what has been added to `composer require`

**Comment by Seldaek** [comment]
It does seem to work already.. 
<img width="865" alt="image" src="https://user-images.githubusercontent.com/183678/180178457-bd09886b-d039-467c-8868-55beea353a4a.png">
