### ISSUE TITLE
post-drupal-scaffold-cmd do not run because composer aborts when it shouldn't

### ISSUE THREAD

**Issue by webprogrammierer** [composer/composer#10968]
Many people are using Composer with Drupal.

Drupal itself sets the file permissions of the folder `/sites/default` to **555**.
It is not possible to prevent this (it would be possible to use 755 instead, but Drupal overwrites it and sets the permission to 555). 

Therefore on a `composer install` command we always get this composer error:

`Could not delete /web/sites/default/default.settings.php`

This error message is not a real problem, we could ignore it. 
But composer aborts with this error messagen and DOES NOT execute the very important commands listed in
**post-drupal-scaffold-cmd** section of composer.json file.

This is a very great problem that composer does not execute the post-drupal-scaffold-cmd entries!
Composer should not stop executing because of "Could not delete ..," error.

How can this be solved is a sustainable way?
Thank you.

**Comment by Seldaek** [comment]
I am surprised this is the first time this gets reported.. If it was a widespread Drupal issue I imagine I'd have heard of it before. So I'm guessing you're doing something wrong but I have no idea what as I'm rather unfamiliar with Drupal. Hopefully someone can help out.

**Comment by webprogrammierer** [comment]
Thank you for your answer.

I think not many Composer users are using post-drupal-scaffold-cmd .

The second thing is: 
Composer users often use a "file-mapping" entry and set default.settings.php  to "overwrite": false. Therefore the file is not copied and not deleted. This users do not have this problem.

Still hoping for some ideas or solutions for this problem.

**Isn't that a general and big problem when Composer simply aborts the rest of the processing** because of a minor error message?

**Comment by GuySartorelli** [comment]
For your use case not being able to delete that file may be minor, for other use cases not being able to clean up may result in unexpected behaviour. Composer doesn't (and shouldn't) know about every possible use case, so it correctly treats this as an unexpected error and terminates.

**Comment by webprogrammierer** [comment]
I understand.
Is it possible to use the pre-drupal-scaffold-cmd section of composer.json file to insert a command like 
`chomd 755 web/sites/default`
in order to avoid the "Could not delete" error?
Do you have any example for this?

**Comment by GuySartorelli** [comment]
I don't use drupal and I've not played around with writing composer plugins so I can't give any advice on that, sorry.

**Comment by webprogrammierer** [comment]
Is there any pre-**-cmd ?

**Comment by RobinHoutevelts** [comment]
> Drupal itself sets the file permissions of the folder /sites/default to 555.

Set `$settings['skip_permissions_hardening'] = true;` to disable that.

See [example.settings.local.php#L121-131](https://git.drupalcode.org/project/drupal/-/blob/9.4.5/sites/example.settings.local.php#L121-131)

**Comment by webprogrammierer** [comment]
Thank you for your reply.

Maybe this is a solution for development servers, but not for production I think.

Drupal sets the folder `/sites/default to 555`.

What permission would you recommend to use instead of 555 if skip_permissions_hardening is true? Isn't this a security risk on productions servers (Live sites)?

**Comment by webprogrammierer** [comment]
@RobinHoutevelts RobinHoutevelts
Thank you for further reply.

**Comment by RobinHoutevelts** [comment]
I'm sorry, I assumed you were using a local environment because you mentioned it happens during `composer install`. 

I don't have a dockerizerd Drupal running in production.

Good luck!
