### ISSUE TITLE
Allow `bump`ing to happen automatically when updating dependencies

### ISSUE THREAD

**Issue by bendavies** [composer/composer#10963]
Hi there,

The bump commanad added in #10829 is a great addition and goes along way to replace what I've been using [malukenho/mcbumpface](https://github.com/malukenho/mcbumpface) for.

There is one usecase missing however, bumping version constraints during an update.

At the moment, we'll have to do:
```shell
composer update foo/foo
composer bump
```

It would be nice to make this one command, for example
```shell
composer update foo/foo --bump
```
which would replicate what [malukenho/mcbumpface](https://github.com/malukenho/mcbumpface) does

Thanks for the new command!

**Comment by stof** [comment]
See https://github.com/composer/composer/issues/10934

**Comment by bendavies** [comment]
thanks @stof
