### ISSUE TITLE
Completion for some commands should only complete root packages

### ISSUE THREAD

**Issue by dkarlovi** [composer/composer#10964]
My `composer.json`:

```json
{
    "require": {
        "symfony/config": "^6.0"
    }
}

```

When doing

```
composer remove <TAB><TAB>
```

in theory, the only package I can remove is `symfony/console`, right? Currently it completes all the local packages, which I can't remove since they're deps.

```
$ composer remove symfony/<TAB><TAB>
symfony/config                 symfony/deprecation-contracts  symfony/filesystem             symfony/polyfill-ctype         symfony/polyfill-mbstring      symfony/polyfill-php81
$ composer remove symfony/filesystem 
symfony/filesystem is not required in your composer.json and has not been removed
./composer.json has been updated
Running composer update symfony/filesystem
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files
6 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found
Removal failed, symfony/filesystem is still present, it may be required by another package. See `composer why symfony/filesystem`.
```

**Comment by Seldaek** [comment]
Yes and no.. I think *trying* to remove anything that is installed is a valid use case, even tho it will not work, but it then clearly errors and tells you what is going on. So I am a bit mixed on this one.

**Comment by GuySartorelli** [comment]
Imo composer shouldn't encourage users to do things that will elad to errors. To my mind if the autocomplete tells me a package is avoid for use with a command, there should be no errors.

**Comment by Seldaek** [comment]
Yeah I can see that too, as I said I am a bit conflicted but I think we can skip those packages, it sounds fairly harmless and makes the list shorter and more to the point.

**Comment by dkarlovi** [comment]
Agreed, especially since you can still run the `remove whatever`, it will just not complete it for you.

IMO, completion should optimize for the happy path, it doesn't need to cover 100% of the use cases if it means compromising on covering 95%.
