### ISSUE TITLE
completion: `bad option -t` error

### ISSUE THREAD

**Issue by staabm** [composer/composer#10966]
My `composer.json`:

none

Output of `composer diagnose`:

```
composer diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK git version 2.32.1
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.4.0-RC1
PHP version: 8.1.8
PHP binary path: /opt/homebrew/Cellar/php/8.1.8/bin/php
OpenSSL version: OpenSSL 1.1.1q  5 Jul 2022
cURL version: 7.84.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1q
zip: extension present, unzip present, 7-Zip not available
```

When I run this command: 

```
composer completion bash > completion.bash
source completion.bash
composer i<TAB>
```

I get the following output: 

```
➜  redaxo git:(main) ✗ composer i_sf_composer:type:6: bad option: -t
_sf_composer:type:6: bad option: -t
_sf_composer:type:6: bad option: -t
```

And I expected this to happen:
proper autocomplete for the `install` command

I am running on iTerm2 with ohmyzsh on default settings.

**Comment by Seldaek** [comment]
It's called bash completion because it works in bash :) AFAIK zsh does not support advanced bash completions and does not support the symfony script.

**Comment by staabm** [comment]
ohh thats actually a good point. I assumed that the modern bash like tools support everything bash supports :-).

maybe there is something we can do about that: https://docs.haskellstack.org/en/stable/shell_autocompletion/#for-zsh-users

**Comment by Seldaek** [comment]
If you can figure it out, feel free to PR the docs, or PR symfony/console with a fix there if needed.

**Comment by staabm** [comment]
Seems it was added recently. We will need to wait for the next symfony release

**Comment by staabm** [comment]
I am not sure why, but it seem to work now for me.

<img width="464" alt="grafik" src="https://user-images.githubusercontent.com/120441/195976136-b2993a51-2f5b-43ab-ab5d-d2538c1aa126.png">

**Comment by Seldaek** [comment]
OK? :) Well anyway I think closing this for now, we'll see if there is ever more demand for this if we can perhaps backport this stuff, but otherwise I'd rather leave it as is..
