### ISSUE TITLE
DX: provide correct example for allowing a global composer plugin

### ISSUE THREAD

**Issue by dbu** [composer/composer#10978]
This is not really a bug report, but a suggestion how to improve the error message when using global plugins.

I run composer in a github action to install symfony to test the LiipImagineBundle. i install flex globally to then specify the symfony version:

    composer global require --no-interaction --no-progress symfony/flex:^1.11

since plugins now need to be enabled, the ci failed with

    Error: symfony/flex contains a Composer plugin which is blocked by your allow-plugins config. You may add it to the list if you consider it safe.
    You can run "composer config --no-plugins allow-plugins.symfony/flex [true|false]" to enable it (true) or disable it explicitly and suppress this exception (false)

however, the example provided is not accurate - to have a global plugin run, i seem to need to allow it in a global configuration rather than the one of my specific project

    composer global config --no-plugins allow-plugins.symfony/flex true

could composer detect that it was not allowed to load a global plugin and mention that explicitly and provide the correct command? something like:

    Error: Global package symfony/flex contains a Composer plugin which is blocked by your global allow-plugins config. You may add it to the list if you consider it safe.
    You can run "composer global config --no-plugins allow-plugins.symfony/flex [true|false]" to enable it (true) or disable it explicitly and suppress this exception (false)

**Comment by Seldaek** [comment]
Yeah we do detect that and report it correctly when running a non global command, the problem is when you are running a global command it really is running a local command inside the global dir, so it believes it is a local plugin at that point.. Need to see if we can somehow still detect it's global.

**Comment by dbu** [comment]
thanks :tada:
