### ISSUE TITLE
Composer not autoloading files in a local path repository

### ISSUE THREAD

**Issue by vitechliu** [composer/composer#10972]
I have a local library like this 
```
{
    "name": "vitechliu/vcsrpg",
    "type": "library",
    "autoload": {
        "files": [
            "src/Utils/functions.php"
        ],
        "psr-4": {
            "Vitechliu\\Vcsrpg\\": "src/"
        }
    },
    ...
}
```
And a local project loading this library as a repository by 'path' type

```
"repositories": [
        {
            "type": "path",
            "url": "...
        }
    ],
"require": {
     "vitechliu/vcsrpg": "dev-master"
},
```
The psr-4 autoloading is successful while the file "functions.php" not appeal in the project's "autoload_files.php".  and the code in the "functions.php" is simply like 

```
<?php

if (!function_exists('xxx')) {
   function xxx() {}
}

```

**Comment by Seldaek** [comment]
Can you try to make a reproduction case in a demo git repo with the path repo and autoloading etc? Because I feel like it's probably a mistake you made but I don't have enough info to tell you what

**Comment by vitechliu** [comment]
> Can you try to make a reproduction case in a demo git repo with the path repo and autoloading etc? Because I feel like it's probably a mistake you made but I don't have enough info to tell you what

Thanks I have solved this by running composer update vitechliu/vcsrpg. Well changing files in the local library immediately works in psr-4 mode so I forget to run update command :/
