### ISSUE TITLE
Gitlab access token refresh

### ISSUE THREAD

**Issue by tlueder** [composer/composer#10970]
Since Gitlab 15.0 was released I have to enter my username and password almost every time I use composer update.

See here:
https://docs.gitlab.com/ee/integration/oauth_provider.html#access-token-expiration

Please add support for access token refresh.

Thanks

**Comment by Seldaek** [comment]
Gitlab Auth issues are usually not being fixed until someone sends a PR, just FYI if it's important to you maybe have a look, I believe the bitbucket code already handles refreshes.
