### ISSUE TITLE
Split direct/transitive dependencies in two groups: also in `info` command (should be in `outdated` only?)

### ISSUE THREAD

**Issue by leoloso** [composer/composer#10999]
## Explanation

Since v2.4, the new groupings `"Direct dependencies:"` and `"Transitive dependencies:"` [added for the `outdated` command](https://github.com/composer/composer/pull/10779) are being added also for the `info` command.

In the PR #10779 it states it is for the `outdated` command, so I assume this is a bug.

Indeed it broke my continuous integration, since I use `composer info` to retrieve and parse the list of all the packages:

```bash
PACKAGES="$(composer info --name-only --no-dev)"

if [ -n "$PACKAGES" ]; then
    for package in $PACKAGES
    do
        # ... Do something with the package
    done
fi
```

Now it produces an error, since it encounters the string `"Direct dependencies:"` and it treats it like a package too, [making the process fail](https://github.com/leoloso/PoP/runs/7873017765?check_suite_focus=true).

## Debug

When I run this command: 

```
composer info --name-only --no-dev
```

I get the following output: 

```
Direct dependencies:    
graphql-api/plugin-utils                       

Transitive dependencies:                 
symfony/var-exporter                        
symfony/yaml  
```

And I expected this to happen:

```
graphql-api/plugin-utils
symfony/var-exporter                        
symfony/yaml  
```

**Comment by Seldaek** [comment]
Ah yeah sorry that was a mistake, will fix.
