### ISSUE TITLE
In Config.php line 609

### ISSUE THREAD

**Issue by novanfatk** [composer/composer#10991]
http://repo.packagist.org could not be fully loaded (Your configuration does not allow connections to http://repo.packagist.org/packages.json. See https://getcomposer.org/doc/06-config.md#secure-http for details.), package information was loaded from the local cache and may be out of date

In Config.php line 609:
                                                                               
  Your configuration does not allow connections to http://repo.packagist.org/  
  p2/laravel/pint.json. See https://getcomposer.org/doc/06-config.md#secure-h  
  ttp for details.

**Comment by Seldaek** [comment]
I believe you may have a hardcoded `http://repo.packagist.org/` composer repository somewhere either in composer.json or your global composer config. Make sure you remove it or change it to use `https`.
