### ISSUE TITLE
Perform Shallow Clones of Git Repositories

### ISSUE THREAD

**Issue by jamescarr** [composer/composer#1099]
Whenever I specify a git repository for a package I can expect it to take a long time to resolve. I suspect this might have something to do with it making a full clone of the repository when resolving something like dev-master. 

So... I propose making these kind of resolutions use shallow cloning. For great speed improvements

Thoughts?

**Comment by AndrewDryga** [comment]
+1 for this feature, since composer uses too much memory

**Comment by ava-dylang** [comment]
When this gets implemented it should be optional for sure; I just recently learned that you cannot commit on top of a shallow clone.

**Comment by stof** [comment]
@AndrewDryga this feature request has strictly nothing to do with the memory usage of Composer. It won't change it at all (cloning the repo is done by Git, not by the PHP code)

**Comment by springuper** [comment]
+1 for this feature, it takes really a very long time to clone the full repo.

**Comment by ava-dylang** [comment]
Hmm, if you don't need a full checkout you possibly also don't need a checkout at all, implying you're not editing code or utilizing revision checkouts ( though composer might need that).

Perhapse using a disttribution (prefer dist) for the package that you want this for might be a solution.

**Comment by jamescarr** [comment]
Man I commented on this like 3 years ago and I still get notified about it.
I don't even PHP anymore...

**Comment by Seldaek** [comment]
Then maybe you can GitHub and press the unsubscribe button on the bottom of the sidebar here? =^

**Comment by jamescarr** [comment]
Done. :smiley:

**Comment by nicolas-grekas** [comment]
Since git 2.5, it is possible to shallow-fetcn a single commit:
http://stackoverflow.com/questions/14872486/retrieve-specific-commit-from-a-remote-git-repository
If someone wants to work on this...
