### ISSUE TITLE
COMPOSER_IGNORE_PLATFORM_REQS is set. You may experience unexpected errors.

### ISSUE THREAD

**Issue by foremtehan** [composer/composer#11007]
I see this message: `COMPOSER_IGNORE_PLATFORM_REQS is set. You may experience unexpected errors.` whenever i run composer commands, especially in `composer update ...`  (windows 10, composer v2.4.0)

Is it possible to turn it off ?

**Comment by yakatz** [comment]
The way to turn off the message is to not set that environment variable.
