### ISSUE TITLE
--lts switch for composer-setup.php ?

### ISSUE THREAD

**Issue by divinity76** [composer/composer#11022]
currently one can do `php composer-setup.php --2.2` to get the newest LTS version (2.2-something), 
that makes me wonder if a --lts switch for people who just want the newest LTS version would be worthwhile (for people who want the newest lts version, regardless of what that version actually is)

**Comment by stof** [comment]
Well, there is no concept of "newest LTS". 2.2 is a long-term supported version because it is the last version supporting PHP 7.1 and older.
If you run on PHP 7.2+, there is no valid reason to use it. You should be using the stable channel of composer.

**Comment by Seldaek** [comment]
Yeah I'd rather not have a --lts as it would not be clear which version you want.
