### ISSUE TITLE
Config gitlab-domains from global

### ISSUE THREAD

**Issue by o5** [composer/composer#11021]
I started to use [GitLab Package Registry](https://docs.gitlab.com/ee/user/packages/composer_repository/#install-a-composer-package) and there is a mention about settings of local config `gitlab-domains`. Is there any reason, why this value cannot be saved in global scope?

I would like to use
```bash
composer global config gitlab-domains gitlab01.example.com gitlab02.example.com
```

instead of 
```bash
composer config gitlab-domains gitlab01.example.com gitlab02.example.com
```

EDIT: When I use global config I get the same error as using without local set
```
In CurlDownloader.php line 645:

  The "https://gitlab01.example.com/api/v4/group/36/-/packages/composer/packages.json" file could not be downloaded (HTTP/2 404 ):
  {"message":"404 Group Not Found"}
```

**Comment by Seldaek** [comment]
The global config in a way you want to do it should be edited like:

`composer config --global gitlab-domains gitlab01.example.com gitlab02.example.com` (or `-g` for shorts)

If you call `composer global` you are executing a command in the global composer dir, but that file does not have its configuration applied globally. It's unfortunate naming and slightly confusing, but anyway I hope this helps :)
