### ISSUE TITLE
#StandWithUkraine

### ISSUE THREAD

**Issue by itzAnasov** [composer/composer#11031]
![Screenshot_20220828_221718](https://user-images.githubusercontent.com/59410395/187093049-9219c2a9-08c2-4681-909c-9c76481acdd5.png)

i don't really give a single fuck about Ukraine, i don't want it to be in my terminal any more please remove it, Thanks !

**Comment by amethystdev1** [comment]
No one really gives a fuck about you 😔

**Comment by Nek-** [comment]
Already answered in many places such as here: https://github.com/composer/composer/issues/10740#issuecomment-1100935990

You may consider closing your issue.

**Comment by itzAnasov** [comment]
> No one really gives a fuck about you 😔

i know that, but that is not i'm talking about !.

**Comment by itzAnasov** [comment]
> ![Screenshot_20220828_221718](https://user-images.githubusercontent.com/59410395/187093049-9219c2a9-08c2-4681-909c-9c76481acdd5.png)
> 
> i don't really give a single fuck about Ukraine, i don't want it to be in my terminal any more please remove it, Thanks !

i mean why it's not *Libya* or *Iraq* or even *Palestine* !!!

**Comment by Naheem** [comment]
It would be nice to add Palestine as an occasional (even 10% of the time?) message.

It will go to show it isn't "no politics unless it involves US/Europe".
