### ISSUE TITLE
Download-only mode

### ISSUE THREAD

**Issue by Jellyfrog** [composer/composer#11035]
I'm looking to download/cache packages only and it doesn't seem supported.
Digging around in the code it seems like if we `return;` here on line 308:
https://github.com/composer/composer/blob/b6028951b8a2254d4896b4dd13bcbe380a3d51bf/src/Composer/Installer/InstallationManager.php#L304-L316

It would download but not install the packages;

```bash
# composer install --download-only
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 1 install, 0 updates, 0 removals
  - Downloading phpstan/phpstan (1.7.12)
# 
 ```
Another option would be to implement an `DownloadOperation`, and do a `if ($operation instanceof DownloadOperation) continue;` on line 314 above.

Would any of these be an acceptable solution? In that case I'll prepare a PR.

**Comment by Seldaek** [comment]
What's the end goal tho? You run the downloads and then what? Is the point just to prime the cache? We do have `COMPOSER_DISABLE_NETWORK=prime` for this, but it only primes the git caches, I think it still skips curl/http downloads entirely.

**Comment by Jellyfrog** [comment]
The goal is to cache packages so they are ready for usage/install in a later stage :)
Most package managers support this feature, apt, yum, cargo to name a few.

**Comment by Jellyfrog** [comment]
@Seldaek I can take a stab at this, is it worth going the `DownloadOperation` route? or should I keep it simpler as above?

**Comment by Seldaek** [comment]
I think doing the early return on line 308  would probably be a simpler and more localized change. It probably needs a flag like $runScripts ($downloadOnly?) that'd propagate all the way from InstallCommand=>Installer=>InstallationManager

The thing where it gets complicated tho is that the `download` step does not only prime the cache, it also copies the zip files from cache into `vendor/composer/tmp-...`, and in this case if you aren't installing/extracting them afterwards this is kind of a waste, but hopefully the cleanup step should take care of cleaning after itself, so you would still do a bit of extra local IO but it's not as bad as a full install. Fixing this would require a much more invasive change that I am not really keen on doing tbh.

Anyway feel free to have a go at it and let's see what happens.

**Comment by dozer1412131** [comment]
> The goal is to cache packages so they are ready for usage/install in a later stage / for offline use :) Most package managers support this feature, apt, yum, cargo to name a few.

This is strange stuff by one hand.

Why just do not install? Seems it will cache the packages + add libs to project.

By the other, maybe i`m to silly to understand the whole idea. Please, can u explain more?

**Comment by jhg** [comment]
> [...] to understand the whole idea. Please, can u explain more?

Sorry if it's old, but to let an example for anyone wondering same that find it.

Imagine that to deploy you turn a maintenance mode, like `php artisan down`/`php artisan up` or similar. If download late, for example, 15 seconds you could download it before to go to maintenance mode. Then when go to maintenance mode to update things it will be 15 seconds less in maintenance.

That could mean less down time, maybe important if you have a SLA, or less time without one server while update everyone.
