### ISSUE TITLE
Inclusion of optional section in composer.json

### ISSUE THREAD

**Issue by rajeshreeputra** [composer/composer#11054]
Currently we have require section in composer.json like:
```
"require": {
    "me/my_package": "^1.0",
    "me/my_package2": "^1.0"
}
```
in similar manner can we have optional section in composer.json like:

```
"optional": {
    "me/my_package3": "^1.0",
    "me/my_package4": "^1.0"
}
```

When we execute `composer install/update` it should work as it work today.

When we execute with param like `composer install/update --with-optional` it should download optional packages.

**Comment by Seldaek** [comment]
Sorry but I don't see this workable at all as per @stof's comments (and other previous discussions here).
