### ISSUE TITLE
unknown error after host machine update

### ISSUE THREAD

**Issue by valentinomariotto** [composer/composer#11069]
My `composer.json`:

```json
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.0.2",
        "ext-bcmath": "*",
        "ext-filter": "*",
        "ext-gd": "*",
        "ext-intl": "*",
        "ext-json": "*",
        "ext-memcached": "*",
        "ext-mysqli": "*",
        "ext-pcov": "*",
        "ext-pdo_mysql": "*",
        "ext-zip": "*",
        "cknow/laravel-money": "^6.4.0",
        "components/bootstrap": "^4.7",
        "components/jquery": "^3.6",
        "guzzlehttp/guzzle": "^7.2",
        "infyomlabs/laravel-ui-adminlte": "^4.0",
        "laravel/framework": "^9.19",
        "laravel/passport": "^11.0",
        "laravel/pint": "^1.0",
        "laravel/sanctum": "^2.14.1",
        "laravel/tinker": "^2.7",
        "laravelcollective/html": "^6.3",
        "league/flysystem-aws-s3-v3": "^3.1",
        "mikemclin/laravel-wp-password": "^2.0",
        "nesbot/carbon": "^2.58",
        "spatie/laravel-cookie-consent": "^3.2",
        "spatie/laravel-permission": "^5.5",
        "spatie/laravel-schedule-monitor": "^3.0",
        "staudenmeir/laravel-adjacency-list": "^1.0",
        "vlucas/phpdotenv": "^5.4",
        "zoha/laravel-meta": "^2.0"
    },
    "require-dev": {
		"ext-gmp": "*",
		"ext-xdebug": "^3.1",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.15",
		"laravel/telescope": "^4.9",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0",
		"reliese/laravel": "^1.1"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        },
        "files": [
            "app/Helpers/NetworkPointsHelper.php",
            "app/Helpers/PaginationHelper.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}

```

Output of `composer diagnose`:

```
www@95468bef18fe:/var/www$ composer diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: WARNING
Your git version (2.17.1) is too old and possibly will cause issues. Please upgrade to git 2.24 or above
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.4.2
PHP version: 8.1.10
PHP binary path: /usr/bin/php8.1
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
cURL version: 7.58.0 libz 1.2.11 ssl OpenSSL/1.1.1
zip: extension present, unzip present, 7-Zip not available
```

When I run this command: 
```
composer update -vvv
```

I get the following output: 
output trimmed to the maximum allowed number of lines in vsc console history and maximum github post length!

```
Reading /.composer/cache/repo/https---repo.packagist.org/provider-nette~utils~dev.json from cache
Downloading https://repo.packagist.org/p2/nette/utils~dev.json if modified
[304] https://repo.packagist.org/p2/symfony/inflector.json
[304] https://repo.packagist.org/p2/nette/utils.json
[304] https://repo.packagist.org/p2/symfony/inflector~dev.json
[304] https://repo.packagist.org/p2/nette/utils~dev.json
Reading /.composer/cache/repo/https---repo.packagist.org/provider-phpdocumentor~reflection-common.json from cache
Reading /.composer/cache/repo/https---repo.packagist.org/provider-illuminate~pipeline.json from cache
Reading /.composer/cache/repo/https---repo.packagist.org/provider-phpdocumentor~reflection-common~dev.json from cache
Reading /.composer/cache/repo/https---repo.packagist.org/provider-illuminate~pipeline~dev.json from cache
Built pool.
Running pool optimizer.
Pool optimizer completed in 1.961 seconds
Found 14,581 package versions referenced in your dependency graph. 13,335 (91%) were optimized away.
Updating dependencies
Generating rules
Resolving dependencies through SAT
Looking at all rules.
Something's changed, looking at all rules again (pass #1)
Dependency resolution completed in 0.022 seconds
Analyzed 1246 packages to resolve dependencies
Analyzed 9102 rules to resolve dependencies
Nothing to modify in lock file
Generating rules
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.001 seconds
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating optimized autoload files
> post-autoload-dump: Illuminate\Foundation\ComposerScripts::postAutoloadDump
> post-autoload-dump: @php artisan package:discover --ansi
Executing command (CWD): '/usr/bin/php8.1' -d allow_url_fopen='1' -d disable_functions='' -d memory_limit='-1' artisan package:discover --ansi

<comment>In LoadConfiguration.php line 66:</comment>
<error>    </error>
<error>    </error>
<error>    </error>

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

And I expected this to happen:
`php artisan package:discover --ansi` should list my packages and the another `php artisan something` should run to complete the process. Please note that `php artisan package:discover --ansi`  runs successfully if called alone.

Thank you guys for this amazing software. Cheers

**Comment by stof** [comment]
This `artisan` command is part of laravel, not of composer. You should probably report it to them.

**Comment by valentinomariotto** [comment]
> Please note that php artisan package:discover --ansi runs successfully if called alone.

!

**Comment by stof** [comment]
They might still have more info about what's going wrong (for instance knowing what can cause this kind of empty error message).

composer has strictly no knowledge of what is happening inside that command and so cannot debug such weird error.

**Comment by Seldaek** [comment]
```
> post-autoload-dump: @php artisan package:discover --ansi
Executing command (CWD): '/usr/bin/php8.1' -d allow_url_fopen='1' -d disable_functions='' -d memory_limit='-1' artisan package:discover --ansi

<comment>In LoadConfiguration.php line 66:</comment>
<error>    </error>
<error>    </error>
<error>    </error>
```

Try adding --verbose to your artisan command, perhaps the failure will include a stack trace then? Because the above LoadConfiguration.php is AFAIK not in composer. My best guess is the failure is https://github.com/laravel/framework/blob/9.x/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php#L66 - but why that would fail I have absolutely no clue.

**Comment by valentinomariotto** [comment]
thank you for your help, I think you're right, the problem is probably somewhere else. 

in LoadConfiguration.php that exception is called when laravel cannot load the configuration file, which in turn might be due to a problem with the .env file. I can't find what the problem is, but it's probably there.

**Comment by valentinomariotto** [comment]
I worked around this problem by downgrading composer to version 2.0.9
If I update again the problem comes back
It looks like a bug to me, after all

**Comment by Seldaek** [comment]
2.0.9 to 2.4.2 is a big version range.. if you can pinpoint which version exactly caused the problem maybe we can figure it out. `composer self-update 2.3.0` for example to try that version, etc.

**Comment by valentinomariotto** [comment]
it works up to version 2.2.17 and stops working with version 2.3.0

**Comment by Seldaek** [comment]
OK, that's when we updated symfony/process & co from 2.8 to 5.4 in Composer, so possibly something there.

One would need to investigate further what is breaking in the artisan command and then maybe we can have a better guess at what is causing it though. 

@themsaid @driesvints sorry for the spam but anyone from Laravel side perhaps willing to help out here?

**Comment by driesvints** [comment]
Heya, happy to help here. Just want to note that @themsaid doesn't work at Laravel anymore so feel free to ping me in the future.

@valentinomariotto is this issue reproducible with a vanilla Laravel project? Otherwise can you maybe create a repo that reproduces this issue with the command below?

```bash
laravel new bug-report --github="--public"
```

**Comment by valentinomariotto** [comment]
Hi! I apologize for the late reply.

First some context:
- I use Debian LTS in WSL and make extensive use of Docker
- In Debian, the Composer version is 2.0.9 and PHP is v8.1.8
- The docker image I'm trying to use has php 8.1.10 and nginx. The image is heavily customized and based on the work of Jtreminio https://github.com/jtreminio/php-docker
- 


test 1, with my image:
 - in WSL, ran `composer create-project laravel/laravel testV209`, 
 - then `docker compose up` with my custom image
 - in the running container `composer update`, just with the standard composer.json > got the issue

test 2, with my image:
 - in WSL, ran  `docker compose up` with my custom image
 - then in the running container  `composer create-project laravel/laravel testV242`
 - then `composer update`, just with the standard composer.json > got the issue

test 3, with Sail:
 - in WSL, ran `composer create-project laravel/laravel testSail`,  `composer require laravel/sail --dev`, `php artisan sail:install`, `./vendor/bin/sail up`
 - in the running container `composer update`,  just with the standard composer.json > NO ISSUE
 
 
 Therefore, there must be something off with my server. Maybe I'm missing a php extension. 
 Are there any specific requirements for running Composer from version 2.3 onwards?

**Comment by driesvints** [comment]
I cannot provide help with WSL on Windows myself as I don't have a machine sorry.

**Comment by valentinomariotto** [comment]
it's the same as running Debian. Besides, I'm not experiencing the problem in wsl-debian, but inside the docker container.

**Comment by driesvints** [comment]
You seem to be using a custom image with `docker compose up`. This is beyond what we can offer support for as Sail is intended to just be used with `sail up` and its unmodified dockerfiles. If you modify them then we cannot help you.
