### ISSUE TITLE
GitLab authentication issue over HTTPS

### ISSUE THREAD

**Issue by thedayofcondor** [composer/composer#11062]
I have setup composer (v2.4.2) to access a repo from my test gitlab instance over https:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://gitlab.example.com/myproject.git"
        }
    ],
    [...]
}
```

and configured the authentication with:  `composer config --global gitlab-oauth.gitlab.example.com <<TOKEN>>`

(where `<<TOKEN>>` is generated in GitLab with `read_repository` scope)

However `composer install` fails with:

`Failed to execute git clone --mirror -- 'https://xxx...xxx:oauth2@gitlab.example.com/myproject.git`

It looks like composer swaps username and token, possibly here:

https://github.com/composer/composer/blob/7ff288f08187f5c63001f9ad07cde948faaf644e/src/Composer/Util/GitLab.php#L69
https://github.com/composer/composer/blob/7ff288f08187f5c63001f9ad07cde948faaf644e/src/Composer/Util/GitLab.php#L161
https://github.com/composer/composer/blob/7ff288f08187f5c63001f9ad07cde948faaf644e/src/Composer/Util/GitLab.php#L204

Although there is a relevant note here:
https://github.com/composer/composer/blob/7ff288f08187f5c63001f9ad07cde948faaf644e/src/Composer/Util/GitLab.php#L96

Manually issuing `git clone --mirror -- 'https://oauth2:<<TOKEN>>@gitlab.example.com/myproject.git` (ie swapping username and token) works.

I also tried `composer config --global gitlab-token.gitlab.example.com <<TOKEN>>` with similar results:

`Failed to execute git clone --mirror -- 'https://xxx...xxx:private-token@gitlab.example.com/myproject.git'`

Am I doing something wrong?

**Comment by Seldaek** [comment]
I am not sure anymore why we swap these tbh.. but I am fairly sure it did work as is. Not sure if it's a new GitLab change causing issues or if you're misconfiguring it. I'm assuming you've read https://getcomposer.org/doc/articles/authentication-for-private-packages.md#gitlab-oauth ?

**Comment by thedayofcondor** [comment]
Yes, I followed the instructions on that page :(

I am not sure it is a recent change, I have tested on both gitlab 13 (quite old) and the latest gitlab 15

Note that using `"url": "ssh://gitlab.example.com:222/myproject.git"` works - although I am not sure how the token is used in that case

**Comment by Seldaek** [comment]
Ok well I am not sure maybe someone more familiar with GitLab can help here..

**Comment by thedayofcondor** [comment]
I think I have found the isssue - it **is** a misconfiguration on my side

there is a note I missed in the documentation 
> Note: For the gitlab authentication to work on private gitlab instances, the [gitlab-domains](https://getcomposer.org/doc/06-config.md#gitlab-domains) section should also contain the url.

**Comment by Seldaek** [comment]
OK, no worries. As per @glaubinix's suggestion in 2.5+ Composer will auto-configure gitlab-domains/github-domains if auth is present, that would prevent any such mistake from occurring.

See 22bedfd8d
