### ISSUE TITLE
Docker needs COMPOSER_ALLOW_SUPERUSER when running plugins inside Dockerfile since 2.4.2

### ISSUE THREAD

**Issue by robertvanlienden** [composer/composer#11073]
Composer version 2.4.2.

**My `composer.json`:**

```json
{
    "name": "thewebmen/silverstripe-installer",
    "type": "silverstripe-recipe",
    "description": "Extension on the default silverstripe installer",
    "authors": [
        {
            "name": "Robert van Lienden",
            "email": "xx@xx.nl"
        }
    ],
    "require": {
        "php": "7.4.*",
        "silverstripe/recipe-plugin": "^1.2",
        "silverstripe/recipe-cms": "4.11.*@stable",
        "thewebmen/silverstripe-elemental-grid": "^2.0",
        "silverstripe/elemental-fileblock": "^2",
        "silverstripe/userforms": "^5.10",
        "silverstripe/spamprotection": "^3.1",
        "undefinedoffset/silverstripe-nocaptcha": "^2.3",
        "webmen/silverstripe-webp-images": "^0.5.0",
        "wilr/silverstripe-googlesitemaps": "^2.2",
        "gorriecoe/silverstripe-linkfield": "^1.0",
        "unclecheese/display-logic": "^2.0",
        "hubertusanton/silverstripe-seo": "^4.1",
        "robertvanlienden/silverstripe-elemental-advanced-edit": "^1.0",
        "silverstripe/redirectedurls": "^2.1.0"
    },
    "require-dev": {
        "phpunit/phpunit": "^5.7",
        "friendsofphp/php-cs-fixer": "^2.14"
    },
    "config": {
        "process-timeout": 600,
        "allow-plugins": {
            "composer/installers": true,
            "silverstripe/vendor-plugin": true,
            "silverstripe/recipe-plugin": true
        }
    },
    "scripts": {
        "post-create-project-cmd": [
            "php -r \"unlink('app/src/Page.php');\"",
            "php -r \"unlink('app/src/PageController.php');\"",
            "npm install --verbose",
            "npm run build"
        ]
    },
    "extra": {
        "project-files": [
            "app/*",
            "themes/*",
            ".eslintrc",
            "gulpfile.js",
            "package.json",
            "webpack.config.js",
            "docker-compose.override.yml.dist",
            "docker-compose.yml",
            "dev/*",
            ".env.docker",
            ".editorconfig"
        ],
        "public-files": [
            "assets/*",
            "favicon.ico"
        ],
        "resources-dir": "_resources",
        "expose": [
            "themes/xxx/css",
            "themes/xxx/javascript"
        ],
        "project-files-installed": [
            "app/.htaccess",
            "app/_config.php",
            "app/_config/mimevalidator.yml",
            "app/_config/mysite.yml",
            "app/src/Page.php",
            "app/src/PageController.php"
        ],
        "public-files-installed": [
            ".htaccess",
            "index.php",
            "install-frameworkmissing.html",
            "install.php",
            "web.config"
        ]
    },
    "prefer-stable": true,
    "minimum-stability": "dev"
}
```

**Output of `composer diagnose`:**\
(Ran inside `Dockerfile` on `docker-compose up --build`. See below for `composer diagnose` output inside container after getting the container up)

```
 => ERROR [php-fpm 22/26] RUN composer diagnose                                                                                                                                                                                   1.2s
------
 > [php-fpm 22/26] RUN composer diagnose:
#0 0.327 Do not run Composer as root/super user! See https://getcomposer.org/root for details
#0 0.381 Checking composer.json: WARNING
#0 0.385 No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
#0 0.385 Checking platform settings: OK
#0 0.385 Checking git settings: OK git version 2.24.4
#0 0.387 Checking http connectivity to packagist: OK
#0 0.810 Checking https connectivity to packagist: OK
#0 0.914 Checking github.com rate limit: OK
#0 0.989 Checking disk free space: OK
#0 0.989 Checking pubkeys: 
#0 0.991 Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
#0 0.991 Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
#0 0.991 OK
#0 0.991 Checking composer version: OK
#0 1.125 Composer version: 2.4.2
#0 1.133 PHP version: 7.4.14
#0 1.133 PHP binary path: /usr/local/bin/php
#0 1.133 OpenSSL version: OpenSSL 1.1.1i  8 Dec 2020
#0 1.133 cURL version: 7.79.1 libz 1.2.11 ssl OpenSSL/1.1.1l
#0 1.134 zip: extension present, unzip present, 7-Zip not available
------
failed to solve: executor failed running [/bin/sh -c composer diagnose]: exit code: 1

```

**When I run this command (inside `Dockerfile`):** 

```
RUN set -eux; \
    composer dump-autoload --classmap-authoritative --no-dev; \
    composer run-script --no-dev post-install-cmd; \
    composer vendor-expose copy
```

**I get the following output:** 

```
 > [php-fpm 22/25] RUN set -eux;     composer dump-autoload --classmap-authoritative --no-dev;     composer run-script --no-dev post-install-cmd;     composer vendor-expose copy:
#0 0.234 + composer dump-autoload --classmap-authoritative --no-dev
#0 0.299 Do not run Composer as root/super user! See https://getcomposer.org/root for details
#0 0.352 Generating optimized autoload files (authoritative)
#0 1.329 Class SilverStripe\Forms\Tests\IDSegmentFieldModifierTest located in ./vendor/silverstripe/segment-field/tests/SegmentFieldModifier/IDSegmentFieldModifierTest.php does not comply with psr-4 autoloading standard. Skipping.
#0 1.329 Class SilverStripe\Forms\Tests\SlugSegmentFieldModifierTest located in ./vendor/silverstripe/segment-field/tests/SegmentFieldModifier/SlugSegmentFieldModifierTest.php does not comply with psr-4 autoloading standard. Skipping.
#0 1.329 Class SilverStripe\ElementalFileBlock\Tests\Block\FileBlockTest located in ./vendor/silverstripe/elemental-fileblock/tests/php/Block/FileBlockTest.php does not comply with psr-4 autoloading standard. Skipping.
#0 1.329 Class DNADesign\Elemental\GraphQL\SortBlockMutationCreator located in ./vendor/dnadesign/silverstripe-elemental/_legacy/SortBlockMutationCreator.php does not comply with psr-4 autoloading standard. Skipping.
#0 1.329 Class DNADesign\Elemental\GraphQL\Types\ObjectType located in ./vendor/dnadesign/silverstripe-elemental/_legacy/Types/ObjectType.php does not comply with psr-4 autoloading standard. Skipping.
#0 1.329 Class DNADesign\Elemental\GraphQL\AddElementToAreaMutation located in ./vendor/dnadesign/silverstripe-elemental/_legacy/AddElementToAreaMutation.php does not comply with psr-4 autoloading standard. Skipping.
#0 1.329 Class DNADesign\Elemental\GraphQL\ReadOneBlockResolver located in ./vendor/dnadesign/silverstripe-elemental/_legacy/ReadOneBlockResolver.php does not comply with psr-4 autoloading standard. Skipping.
#0 1.329 Class DNADesign\Elemental\GraphQL\DuplicateElementMutation located in ./vendor/dnadesign/silverstripe-elemental/_legacy/DuplicateElementMutation.php does not comply with psr-4 autoloading standard. Skipping.
#0 1.329 Class DNADesign\Elemental\GraphQL\ElementsResolver located in ./vendor/dnadesign/silverstripe-elemental/_legacy/ElementsResolver.php does not comply with psr-4 autoloading standard. Skipping.
#0 1.329 Class DNADesign\Elemental\GraphQL\DeleteBlocksMutation located in ./vendor/dnadesign/silverstripe-elemental/_legacy/DeleteBlocksMutation.php does not comply with psr-4 autoloading standard. Skipping.
#0 1.329 Class DNADesign\Elemental\GraphQL\ReadOneAreaResolver located in ./vendor/dnadesign/silverstripe-elemental/_legacy/ReadOneAreaResolver.php does not comply with psr-4 autoloading standard. Skipping.
#0 1.346 Generated optimized autoload files (authoritative) containing 2908 classes
#0 1.349 + composer run-script --no-dev post-install-cmd
#0 1.390 Do not run Composer as root/super user! See https://getcomposer.org/root for details
#0 1.439 Exposing web directories for silverstripe-recipe thewebmen/silverstripe-installer with method copy:
#0 1.439   - themes/xxx/css
#0 1.439   - themes/xxx/javascript
#0 1.466 + composer vendor-expose copy
#0 1.547 Do not run Composer as root/super user! See https://getcomposer.org/root for details
#0 1.547 Aborting as no plugin should be loaded if running as super user is not explicitly allowed
------
failed to solve: executor failed running [/bin/sh -c set -eux;     composer dump-autoload --classmap-authoritative --no-dev;     composer run-script --no-dev post-install-cmd;     composer vendor-expose copy]: exit code: 1

```

**And I expected this to happen:**

I expect that inside Dockerfile, the `COMPOSER_ALLOW_SUPERUSER` flag is not needed.

**Additional info;**

When I run the exact same commands inside the container (after commenting-out the commands from the `Dockerfile`), the commands will still run fine. Also running as root.

**composer diagnose output when running inside the container**

```
bash-5.0# composer diagnose
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK git version 2.24.4
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.4.2
PHP version: 7.4.14
PHP binary path: /usr/local/bin/php
OpenSSL version: OpenSSL 1.1.1i  8 Dec 2020
cURL version: 7.79.1 libz 1.2.11 ssl OpenSSL/1.1.1l
zip: extension present, unzip present, 7-Zip not available
```

**Comment by stof** [comment]
Maybe you are building your container as root and running it as non-root.

**Comment by robertvanlienden** [comment]
@stof Your right, I'm running docker as root user (as, I've added my user to the `docker` group as mentioned in   https://docs.docker.com/engine/install/linux-postinstall/).

But that should not lead to problems, because Composer was always running fine on Docker with the setup mentioned.

Feels like the changes on `COMPOSER_ALLOW_SUPERUSER` in the latest 2.4.2 release is breaking some stuff in Docker-environments.

**Comment by Seldaek** [comment]
Most likely due to https://github.com/composer/composer/commit/a75fbf0e6a705addc8421d253807be0208588b12 yes. 

Our docker detection is just `file_exists('/.dockerenv')`. Maybe this does not work in whatever you are doing?

I think I see the problem is that you are using a script command alias when running `composer vendor-expose copy` which requires us to load plugin commands to ensure there is no conflict between plugin commands and the script name.. If you ran `composer run-script vendor-expose copy` it should work fine as it will realize this is a composer command (`run-script`) and it will not attempt loading plugins.

That said.. I'd be interested in figuring out if we can improve the docker detection so that things just work.

**Comment by erikfrerejean** [comment]
@Seldaek just to get back to you on your last statement, I've tried that change in the project @robertvanlienden used for this test, but that doesn't seen to work as expected.

```sh
 => ERROR [php-fpm 33/34] RUN composer run-script vendor-expose copy                                                                                                   0.7s
------
 > [php-fpm 33/34] RUN composer run-script vendor-expose copy:
#0 0.582 Do not run Composer as root/super user! See https://getcomposer.org/root for details
#0 0.642 
#0 0.645 In RunScriptCommand.php line 97:
#0 0.645                                                          
#0 0.645   Script "vendor-expose" is not defined in this package  
#0 0.645                                                          
#0 0.645 
#0 0.645 run-script [--timeout TIMEOUT] [--dev] [--no-dev] [-l|--list] [--] [<script> [<args>...]]
#0 0.645 
------
failed to solve: executor failed running [/bin/sh -c composer run-script vendor-expose copy]: exit code: 1
```
It seems that it can't find the command when running through `run-script`, although this also breaks when calling it that way from the running container. So that may be something that is caused by that script itself.

**Comment by stof** [comment]
Then it means that `vendor-expose` is probably a plugin-provided command and not a script.

**Comment by Seldaek** [comment]
> But besides that the root user message also pops up so that would indicate that also in `run-script` there is something not fully working as intended.

Yes as I mentioned we only detect docker with `file_exists('/.dockerenv')` - is this file not existing in your composer container? 

If you find me a more reliable way (without massive overhead) of detecting we're running in docker, great.

If not then you'll have to define COMPOSER_ALLOW_SUPERUSER=1 in your container's env.

**Comment by Seldaek** [comment]
Yeah sorry but that is one for you to figure out 🤷‍♂️

**Comment by erikfrerejean** [comment]
No problem :). It was worth a shot, maybe you knew when that file is added to the container 😉 .

I think that we'll for now run with the `COMPOSER_ALLOW_SUPERUSER` as its only for local development anyway 🤷‍♂️ . So if anyone else runs into this issue then using the flag is probably the only solution at the moment. If we at some point encounter a solution that could _(potentially)_ be used by composer I'll get back to you.

**Comment by kennyj2016** [comment]
Try this: in your Dockerfile, add this line before the composer install command:
`ENV COMPOSER_ALLOW_SUPERUSER=1`

So it should look like this:
`
ENV COMPOSER_ALLOW_SUPERUSER=1`
RUN set -eux; \
...
`
After that, run your `docker compose up --build` again to rebuild the image.

**Comment by techbin** [comment]
> Try this: in your Dockerfile, add this line before the composer install command:
> 
> `ENV COMPOSER_ALLOW_SUPERUSER=1`
> 
> So it should look like this:
> 
> ENV COMPOSER_ALLOW_SUPERUSER=1
> 
> RUN set -eux; \ ...
> 
> After that, run your `docker compose up --build` again to rebuild the image.

![Screenshot from 2022-12-22 09-02-02](https://user-images.githubusercontent.com/10051026/209015166-2b773d95-f87e-49e3-a31f-a7b0b84909e9.png) thanks this worked for me. Adding the above lines in Dockerfile worked for me.

**Comment by ilibilibom** [comment]
👆This for me as well👆

**Comment by ilibilibom** [comment]
> Try this: in your Dockerfile, add this line before the composer install command:
> 
> `ENV COMPOSER_ALLOW_SUPERUSER=1`
> 
> So it should look like this:
> 
> ENV COMPOSER_ALLOW_SUPERUSER=1
> 
> RUN set -eux; \ ...
> 
> After that, run your `docker compose up --build` again to rebuild the image.

👆This one worked for me as well👆

**Comment by Bilge** [comment]
Note that the Docker detection `file_exists('/.dockerenv')` does not work at build time. See: https://github.com/moby/buildkit/issues/4503.

**Comment by mikeschinkel** [comment]
Hey @Seldaek — I just [got bit by this issue](https://github.com/statamic/cms/discussions/10487), but hard! 

I lost two days trying to unravel the root cause of the problem. I has **some suggestions** for things I think you could do to keep anyone else from feeling this kind of pain moving forward.

Here is [my diagnosis of the issue and resolution](https://github.com/statamic/cms/discussions/10487#discussioncomment-10134399), and here is Statamic's [newly-added docs page](https://statamic.dev/troubleshooting/missing-control-panel-assets) for anyone specifically bit by this bug in the futture, at least as it relates to Statmic.

<hr>

I was trying a build a basic Docker container from Statamic CMS source (based on Laravel) — assuming that would be a common thing to —  but after discussions I came away thinking the Statamic devs had never ventured outside the Otwell-provided approach to working with all things Laravel.

The problem exposed itself as a missing `manifest.json` file after a `composer create-project`.  That sent me down a rabbit hole of trying to set up `vite` on Docker and building assets — which I failed at — and then trying to set set up `npm` on Docker and also building asset — which I also failed at.  So then I dove in and spent time xdebugging through `composer create-project`. So much output was being generated it took me a long time to discover that Composer gets to a point where it cannot load a plugin — [the plugin that downloads and untars all the pre-compiled assets](https://github.com/pixelfear/composer-dist-plugin) and the plugin that if it can't load the install has failed — where it outputs a short message and then carries on as if nothing bad had happened. 

Oh, how I wish that `composer create-project` had just failed when it could not load the plugin! 

In hindsight the problem and solution were obvious but given the fact that Statamic's install calls a bunch of scripts during their `composer create-project` and TTY is disabled in a Docker build it took a heck of a lot of xdebug work to find out where that needle existed in that haystack.

The solution I discovered — of course — was to set `ENV COMPOSER_ALLOW_SUPERUSER=1` — which the log output I finally found warns in no uncertain terms against doing.  But unless I am missing something here since Docker builds are always(?) run as `root` I don't think this applies to running composer in Docker, though there is [no caveat to that effect on your warnings page](https://getcomposer.org/doc/faqs/how-to-install-untrusted-packages-safely.md).

<hr>

## Suggestions
So, what are my suggestions?  In order of which I would most advocate for:

1. **Fail when plugins cannot be loaded** — Sure, this would probably break so many builds, but at least add a command line switch like `--fail-on=no-plugins` that allows those like Statamic — whose `create-project` and `install` depend on plugins to succeed — to document to their users to use that switch.  So instead of having this in their docs:

    ```shell
    composer create-project --prefer-dist statamic/statamic example.com
    ```

    The could instead document _(something like)_ this:

    ```shell
    composer create-project --prefer-dist --fail-on=no-plugins statamic/statamic example.com
    ```

2. **Improve your Docker detection** — You mention you need to improve your Docker detection, which if you are checking for `./dockerenv` is definitely something to do, especially since 1.) it is being phased out and 2.) it never existed during `docker build` anyway.   

    Here is [an article explaining how to detect Docker](https://www.baeldung.com/linux/is-process-running-inside-container), and here a function that wraps the most reliable detection method:

        <?php
        
        function is_docker():bool {
            $cgroups = [
                "cgroup v2" => "/proc/self/mountinfo",
                "cgroup v1" => "/proc/1/cgroup",
            ];
            foreach($cgroups as $cgroup) {
                $data = file_get_contents($cgroup);
                if (str_contains($data,"/var/lib/docker/")) {
                    return true;
                }
            }
            return false;
        }

3. **Automatically allow Superuser in a Docker build** — I assume by your mention of Docker detection you may already have been attempting this — just without properly detecting the Docker build.  

    The following is code that correctly identifies a Docker **build** _(vs. **run**)_ correctly in all cases I have checked, but of course that is far from all of them. 

        <?php
        function is_docker_build() {
            if (file_exists('/.dockerenv')) {
                // Absent during build
                return false;
            }
            $cgroupDir = '/sys/fs/cgroup/system.slice/';
            if (is_dir($cgroupDir)) {
                $files = scandir($cgroupDir);
                foreach ($files as $file) {
                    if (str_starts_with($file, 'docker-')) {
                        // Indicates a build
                        return true;
                    }
                }
            }
            return false; 
        }

     Now I think it would be safe to assume that plugins should be able to be run during a Docker build, but I cannot say for 100% certain as I am just not enough of a security expert.  

    But if it _is_ safe to enable plugins during a Docker build, it would be really great if it would be possible to just enable plugins automatically as it is a time that a lot of developers — especially for CI/CD builds — are less likely not to notice the short _"plugins are disabled"_ message — because it does not fail when running on own their machines — and they are instead forced to go down the rabbit hole to figure out why something that appears completely unrelated to composer fails do to composer just disabling plugins.  #fwiw

**Comment by Seldaek** [comment]
> But unless I am missing something here since Docker builds are always(?) run as `root` I don't think this applies to running composer in Docker

AFAIK you can set `USER myuser` in the Dockerfile to use something else. But yes I guess we could document this better.

And thanks a bunch for working out detection code for docker. Finally after years of people complaining someone did this. I'll try to work this into a PR.

**Comment by mikeschinkel** [comment]
@Seldaek — Thank you for the quick follow up.

As for `USER myuser`, yes I guess that would be possible but I suspect that very few people would be doing it _during_ the container **build** process. If they did they would have to set all permissions required to do anything and/or switch back to `root` for anything that would normally require `sudo` as it they would be in a non-interactive session.  So I highly doubt switching users away from `root` during `docker build` this will be a frequent concern.

But whatever the case, my biggest ask is to find a way to ensure that something that can cause a `create-project` and/or `install` to fail cannot easily go unnoticed. And even though I made some suggestions, really however you feel the best way to do that would be a-ok.

Also, if you can give me direction I could possible work on a PR for you. I do not want to be one to ask for updates but then not offer to do the work when doing the work is within my skill set. 🤷‍♂️

**Comment by Bilge** [comment]
>     $cgroupDir = '/sys/fs/cgroup/system.slice/';
Presumably this only works on systemd systems? Being as that's the case, I'm surprised it works in Docker at all, considering they unabashedly claim to be incompatible with systemd.

**Comment by Seldaek** [comment]
Here https://github.com/composer/composer/pull/12062 - if anyone can test it that'd be great, but that'll require cloning my repo, installing deps, running `bin/compile` to get a composer.phar and then use that phar to build a container I guess :)

**Comment by mikeschinkel** [comment]
> Presumably this only works on systemd systems? 

Good catch.

That said, if `is_docker_build()` is only used to limit a behaviour to when `true` is returned then a `false` negative should not be a major concern.

Also, the vast majority of Linux now runs on systemd — Slackware and Gentoo being the only well-known distros I know of that do not — so being able to correctly detect `docker build` on the majority of systems is better than not detecting it on any systems.

Plus, as I said in my first post, I didn't expect this one to be foolproof. I can easily see improving detection as failing use-cases emerge. And that's something I would be happy to sign on to remediate when it occurs.

> I'm surprised it works in Docker at all, considering they unabashedly claim to be incompatible with systemd.

Just to be clear, this is a `cgroups`+`systemd` thing that happens to get exposed within `docker build`, not something Docker actively manages.

See https://medium.com/@charles.vissol/systemd-and-cgroup-7eb80a08234d

**Comment by mikeschinkel** [comment]
> Here #12062 - if anyone can test it that'd be great

Will look at it shortly.

> but that'll require cloning my repo, installing deps, running `bin/compile` to get a composer.phar and then use that phar to build a container I guess :)

Well, since I already had to set all that up to diagnose the bug I ran into, it is not like it will be a big lift for me.  🙂

**Comment by mikeschinkel** [comment]
@Seldaek — I just reviewed your commit and [left a comment](https://github.com/composer/composer/pull/12062/files#r1693719559) suggesting we focus on Docker **`build`** vs. Docker **`run`**. 

Unless of course there are reasons we need Composer during Docker `run`, but that is not common, is it? Besides, with Docker `run` we can use `-it` to get a TTY and bypass the plugin issue.
