### ISSUE TITLE
[FEATURE REQUEST] Fail when COMPOSER_AUTH is malformed

### ISSUE THREAD

**Issue by aurelijusrozenas** [composer/composer#11085]
Hi,

There have been multiple when I stepped on this rake and got hit in the face: `composer install` does not work for private repos. And then I go debugging ssh connections, deployer scripts, docker configuration etc. only to find somewhere in the logs:

> COMPOSER_AUTH environment variable is malformed, should be a valid JSON object

And then everything is obvious and the fix is around the corner.

This time I am thinking maybe there is a better way? One solution could be to make `composer install` (or maybe all composer commands?) to fail when COMPOSER_AUTH is malformed? O maybe add parameter to make it fail?
It would be nice if this never happens to me or my colleague again. If COMPOSER_AUTH is set, it should valid otherwise what's the point of setting it, right?

What do you think? :man_singer:

**Comment by Seldaek** [comment]
Yes I can see if you set it you'd not want it to have it be ignored.. Scheduling for 2.5 tho as it could kinda come as a surprise to people in a patch release.
