### ISSUE TITLE
Help Iranian people

### ISSUE THREAD

**Issue by jabysa** [composer/composer#11080]
Now it's Iran's turn!
for Iranian women
for [#مهسا_امینی](https://twitter.com/hashtag/%D9%85%D9%87%D8%B3%D8%A7_%D8%A7%D9%85%DB%8C%D9%86%DB%8C?src=hashtag_click)
for ....
This message at the end of the commands :
Stay Strong Iran !

**Comment by gh-mahdy313** [comment]
#no_to_sedition
#نه_به_آشوب
#نه_به_اغتشاش
#صلح
#مرگ_بر_آشوبگر

**Comment by Seldaek** [comment]
I fully sympathize with your situation, but unlike in the Russian war on Ukraine, I suspect a message in Composer would hardly reach anyone of interest in Iran. Sorry this will disappoint some of you.

**Comment by jabysa** [comment]
We will continue to fight alone!! But if you pay attention, all the great people of the world understand our situation completely, even the President of Ukraine @Seldaek

**Comment by politsin** [comment]
```sh
git clone https://github.com/composer/composer.git --branch 2.5.4  ~/composer-build && \
    composer install  -o -d ~/composer-build && \
    wget https://raw.githubusercontent.com/politsin/snipets/master/patch/composer.patch -q -O ~/composer-build/composer.patch  && \
    cd ~/composer-build && patch -p1 < composer.patch && \
    php -d phar.readonly=0 bin/compile && \
    rm /usr/local/bin/composer && \
    php composer.phar install && \
    php composer.phar update && \
    mv ~/composer-build/composer.phar /usr/local/bin/composer && \
    rm -rf ~/composer-build  && \
    chmod +x /usr/local/bin/composer
```
