### ISSUE TITLE
[IMPORTANT] Platform check is causing to broke websites with unfair way

### ISSUE THREAD

**Issue by jakubboucek** [composer/composer#11091]
Composer from version 2.3.0 can be application runtime afflicted by unpredicted Composer's platform check.

https://github.com/composer/composer/blob/5770fb027c3af5b29f1542bde0407c37961ee950/src/Composer/Autoload/AutoloadGenerator.php#L888-L894

It is understandable and justified, but completely poorly implemented. **This is same problem as I reported formerly at #9411** and fixed at #9410, #9414 and #9418.

## Problems:

- Web application is stopped and replaced with the some error message, but presented with HTTP `200 OK` status code. This can  ruin SEO reputation!
- In CLI is error message presented simply to standard output instead of error output.
- Developer is not notified because is not any standard error mechanism triggered.

**It's now shutdowns websites across the world.**
Trust me its't very serious problem, try to [search `-echo "Composer 2.3.0 dropped support for autoloading on PHP <5.6 and you are running"`](https://www.google.com/search?q=-echo+%22Composer+2.3.0+dropped+support+for+autoloading+on+PHP+%3C5.6+and+you+are+running%22) for proof.

Please fix that with same way as another platform check (see above to previous PR references):

https://github.com/composer/composer/blob/5770fb027c3af5b29f1542bde0407c37961ee950/src/Composer/Autoload/AutoloadGenerator.php#L849-L868

Please be always very very careful when you adding any check/error message which is fired at autoload runtime! Composer have enormous power, they should also have enormous responsibility.

**Comment by derrabus** [comment]
If you need to stay compatible with ancient versions of PHP (no judgement here), I'd strongly recommend to use Composer 2.2 instead. It's an LTS version that is still maintained to accomodate projects like yours.

The world has moved on and this version check that troubles you right now indicates that the authors of Composer cannot guarantee anymore that the generated autoloader code will be compatible with the PHP version your project is running on.

**Comment by stof** [comment]
@derrabus it would still be a good idea to build it on the same reporting way than the platform checks, which were designed to break in a good way (reporting a 500 error and not a 200 error)

**Comment by jakubboucek** [comment]
@derrabus Dropping support of legacy is OK. This issue is only HOW is dropping implemented.

**Comment by Seldaek** [comment]
Sorry about that. Hopefully resolved by https://github.com/composer/composer/commit/c447c12a70da9f4ad7bf26b3442d00a533c5ce29 - tho it'll still kill websites, just in a nicer way. I guess this is due to shared hosts upgrading things automatically without checking compatibility at all?

**Comment by jakubboucek** [comment]
> tho it'll still kill websites, just in a nicer way.

Yes, it's what I ask. The **fair** kill. Thanks. 

Upgrades are maked automatically by lot of (semi-)automated app hosting, like a clouds and similar one. The problem lies in the detail, here can be not any change in runtime (PHP version, server, atc.), neither app itself, but can be upgraded build tool only (Composer) which is not presented to production. Only modicum od developer expects trap here wen nothich in APP nor Runtime changed.
