### ISSUE TITLE
Is caret version ranges broken?

### ISSUE THREAD

**Issue by judgej** [composer/composer#11114]
My `composer.json`:

```json
"sorry, too much proprietory stuff and project names - hopefully the details below will be enough to say whether it looks good or not"
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
require.consilience/laravel-data-importer : unbound version constraints (@dev) should be avoided
Checking platform settings: OK
Checking git settings: OK git version 2.34.1
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 2.4.2
PHP version: 8.1.11
PHP binary path: /usr/bin/php8.1
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
cURL version: 7.81.0 libz 1.2.11 ssl OpenSSL/3.0.2
zip: extension present, unzip present, 7-Zip not available
```

When I run this command: 

```
all appears to work normally
```

I get the following output: 

```
all appears to work normally
```

And I expected this to happen:

I have these requirements in a project, which has worked fine until updating packages today:

```
$ composer why psr/simple-cache
laravel/laravel          dev-develop requires psr/simple-cache (~2.0)
laravel/framework        v9.35.1     requires psr/simple-cache (^1.0|^2.0|^3.0)
maatwebsite/excel        3.1.43      requires psr/simple-cache (^1.0|^2.0)
phpoffice/phpspreadsheet 1.25.2      requires psr/simple-cache (^1.0 || ^2.0 || ^3.0)
```

Note that `maatwebsite/excel` restricts the version of `psr/simple-cache` to 1.x or 2.x (if I understand correctly).

However, I am now getting `psr/simple-cache` 3.0.0 installed, which is correctly throwing errors against `maatwebsite/excel` when using PHP 8.1. 

`psr/simple-cache` 3.0.0 has been out since 2021, and this has not happened at all so far this year.

So - should `psr/simple-cache` 3.0.0 be installed? I don't think it should. If I put this in the project `composer.json` then it gets downgraded and works, but it worries me what else the caret ranges are now letting in.

**Comment by stof** [comment]
Well, without providing a reproducing case, it is impossible to debug what happens.

And the output of `composer why` indeed indicates that `psr/simple-cache` 2.x should be installed. But you don't provide the output of `composer show` either to show what actually gets installed.

**Comment by judgej** [comment]
I'll try and get a minimal case together.

**Comment by Seldaek** [comment]
Could have been caused by a merge of two lock files with different updates? Perhaps..
