### ISSUE TITLE
Aborting install from plugin

### ISSUE THREAD

**Issue by flavioheleno** [composer/composer#11127]
I'm working on a plugin and am trying to abort the install (either `composer install` or `composer update`) from a `POST_FILE_DOWNLOAD` event handler.

Throwing an exception from the event handler only makes composer write to the stdout that it failed the download of a specific file (the one that triggered the event handler) and that it would instead download from source.

```
$ composer update -W 
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 89 installs, 0 updates, 0 removals
  - Installing flavioheleno/composer-plugin (dev-main): Symlinking from ../composer-plugin
    Failed to download vlucas/phpdotenv from dist: <exception message>
    Now trying to download from source
  - Syncing vlucas/phpdotenv (v5.4.1) into cache

  <execution goes on..>
```

The closest behavior I got was throwing an `IrrecoverableDownloadException`, that would make the whole thing fail.

```
$ composer update -W 
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 89 installs, 0 updates, 0 removals
  - Installing flavioheleno/composer-plugin (dev-main): Symlinking from ../composer-plugin
    0 [--->------------------------]
In Plugin.php line 43:
       
  <exception message>  
       

update [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--no-autoloader] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>...]
```

Although the goal was achieved (aborting the install), the output isn't super user friendly.

Would that be the recommended way to "abort" an installation half way through it or is there a better approach?

Thank you in advance!

**Comment by Seldaek** [comment]
I think right now that's your best bet yes. And while we could add another exception with a slightly nicer name perhaps, doing the abort in a much cleaner way than throwing would be a much bigger change I'm afraid and doesn't sound worth it to me.

**Comment by flavioheleno** [comment]
No worries @Seldaek, thank you for your directions!
