### ISSUE TITLE
Add resolved platform dependencies to composer.lock

### ISSUE THREAD

**Issue by basz** [composer/composer#11122]
This is a possible feature request.

I was playing with (selfhosted) renovate bot on my application source. I have a set php requirement of "^8.0". The app runs in production php v8.0. The composer.lock file is in repo.

I noticed that renovate is using composer with php 8.1 to check its dependencies. This is problematic as my lock file is created with php 8.0.

see also: https://github.com/renovatebot/renovate/discussions/11954

Therefore I had the idea to look inside the composer.lock file to see if resolved platform dependecies used to create the lock file are included insode the lock file. If that were the case renovate could use that to side load the correct php version instead of using the (too) broader platform dependency as defined composer.json.

Is this something to consider as an addition or am I being stupid and should I simply configure my composer.json to require 8.0.0 if I am ok with php 8.0.*?

**Comment by Seldaek** [comment]
Looks like you should configure your platform as per https://getcomposer.org/doc/06-config.md#platform

**Comment by basz** [comment]
Yes, found that too. Thx!

Is there a fundamental reason the used platform specification aren't stored within a lock file? I would assume a lock file tells me everything to reproduce initial state at a point in time. The used runtime seems relevant there.
