### ISSUE TITLE
Verifying downloads, role of the two keys, security considerations

### ISSUE THREAD

**Issue by sebalis** [composer/composer#11129]
Hi,

in the hope of adding some security to a scripted Composer download and installation process, I am looking at https://composer.github.io/pubkeys.html and https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md. Downloading https://getcomposer.org/installer works and matches the checksum mentioned on the website as well as in https://getcomposer.org/installer.sig. As this is just a checksum, my current thinking is that it would be better to change that file’s extension to .sha384 or similar, because no cryptographic signing is involved. The name of the file led me to believe for a while that the two public keys shown on https://composer.github.io/pubkeys.html had something to do with the production of the .sig file – later I realised that that is not the case.

I have understood that these two keys are public RSA keys in OpenSSL format (and ```openssl rsa -noout -text -inform PEM -pubin -in releases.pub``` can be used to inspect them. But what role do they play in verifying any part of the software (either the installer or composer.phar)?

Also, I was wondering if it would be advisable to switch to PGP signatures and distribute the keys via keys.openpgp.org, adding an independent channel for extra security. Because for now the Github account “composer” seems to be a single point of failure, since the contents of getcomposer.org are developed here too (https://github.com/composer/getcomposer.org).

**Comment by Seldaek** [comment]
PGP is a pita to get working cross-platform tho, while openssl is a requirement of Composer anyway and we can verify that in PHP directly.

The .sig name is unfortunate yes but on the other hand we don't want to break that link IMO to avoid breaking scripts, and https://composer.github.io/pubkeys.html clearly mentions that it is a checksum.

The RSA keys are then used by composer self-update to verify following composer.phar.

**Comment by sebalis** [comment]
Thank you for the answers. Yes, PGP adds complexity (I see that there is a PHP module but it requires GnuPG to be installed separately), although I wouldn’t go as far as calling it a pain. In particular as this is a simple PGP use case: It does not require private keys on the verifyer’s side and therefore no real key management, agents, or interactive components. And in any case I’m only thinking about offering this as an option, not demanding that your installer would use it. Come to think of it, it would be good if it did :-)

**Comment by Seldaek** [comment]
PGP on windows is a pain IMO. And what we have works reasonably well, I don't see a need to add complexity and maintenance burden for a minor benefit.

**Comment by sebalis** [comment]
Thanks for the clarification anyway :-)
