### ISSUE TITLE
Incorrect dependencies resolution under certain conditions

### ISSUE THREAD

**Issue by T2L** [composer/composer#11124]
My `composer.json`:

```json
{
    "require": {
        "drupal/core-recommended": "^9.4",
        "drush/drush": "^11.2"
    },
    "repositories": {
        "_drupal": {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "preferred-install": "dist",
        "allow-plugins": {
            "dealerdirect/phpcodesniffer-composer-installer": true
        },
        "platform": {
            "php": "8.0"
        }
    },
    "require-dev": {
        "drupal/core-dev": "^9.4"
    }
}

```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK git version 2.38.0
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest snapshot version, run `composer self-update` to update (68da418f6e229ef6ade29c9c44d0eb05b996f218 => 9ac186bf46b0a7ae015fbcd725c088be4905f2f6)
Composer version: 2.5-dev+68da418f6e229ef6ade29c9c44d0eb05b996f218
PHP version: 8.0 - Package overridden via config.platform, actual: 8.1.11
PHP binary path: /usr/local/Cellar/php/8.1.11/bin/php
OpenSSL version: OpenSSL 1.1.1q  5 Jul 2022
cURL version: 7.85.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1q
zip: extension present, unzip present, 7-Zip not available
```

When I run this command (-vvv does not fit into the issue body limit):

```
composer u 'drupal/core*' -W -vv
```

I get the following output: 

```
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 10 updates, 0 removals
  - Upgrading drupal/core (9.4.8 => 9.5.0-beta2)
  - Upgrading drupal/core-recommended (9.4.8 => 9.5.0-beta2)
  - Upgrading laminas/laminas-diactoros (2.11.3 => 2.14.0)
  - Upgrading laminas/laminas-stdlib (3.7.1 => 3.11.0)
  - Upgrading symfony/polyfill-ctype (v1.25.0 => v1.26.0)
  - Upgrading symfony/polyfill-iconv (v1.25.0 => v1.26.0)
  - Upgrading symfony/polyfill-intl-idn (v1.25.0 => v1.26.0)
  - Upgrading symfony/polyfill-intl-normalizer (v1.25.0 => v1.26.0)
  - Upgrading symfony/polyfill-mbstring (v1.25.0 => v1.26.0)
  - Upgrading symfony/polyfill-php80 (v1.25.0 => v1.26.0)
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 10 updates, 0 removals
  - Upgrading symfony/polyfill-php80 (v1.25.0 => v1.26.0)
  - Upgrading symfony/polyfill-mbstring (v1.25.0 => v1.26.0)
  - Upgrading symfony/polyfill-ctype (v1.25.0 => v1.26.0)
  - Upgrading symfony/polyfill-intl-normalizer (v1.25.0 => v1.26.0)
  - Upgrading symfony/polyfill-intl-idn (v1.25.0 => v1.26.0)
  - Upgrading symfony/polyfill-iconv (v1.25.0 => v1.26.0)
  - Upgrading laminas/laminas-stdlib (3.7.1 => 3.11.0)
  - Upgrading laminas/laminas-diactoros (2.11.3 => 2.14.0)
  - Upgrading drupal/core (9.4.8 => 9.5.0-beta2)
  - Upgrading drupal/core-recommended (9.4.8 => 9.5.0-beta2)
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.
86 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found
```

And I expected this to happen:

As far as I understand, Composer should update to the `9.4.8` version (the latest atm), Composer should not to update `drupal/core` and `drupal/core-recommended` to `9.5.0-beta2`, because 

- it's required as `^9.4` (not like `^9.4@beta`)
- stable releases are preferred

Seems like this happens only with conduction with `drush/drush` package ...

**Comment by Seldaek** [comment]
You'd need to run `composer why-not drupal/core 9.4.8` maybe that gives us a hint..

**Comment by stof** [comment]
My guess is that composer makes a choice for some other package first before choosing the version for drupal packages. As `drupal/core-recommended` looks its dependencies to a *minor* version, it does not allow the latest stable version for many of them in 9.4.8. So this might explain it.

Preferring stable releases to beta ones is not a setting that resolves dependencies multiple times and then chooses between the different solutions based on the total number of unstable packages in them. It is a setting that affect *local* decision when making a choice for each package. And a choice done for one package restrict the choices for the next decisions.
Changing that behavior to be a global behavior would require rearchitecturing the whole dependency solver in a much slower way (as it would have to find _all_ solutions instead of finding _a_ solution, to compare them).

**Comment by T2L** [comment]
> You'd need to run `composer why-not drupal/core 9.4.8` maybe that gives us a hint..

Thanks, but this does not help much

Some additional info, removing:

```
"platform": {
  "php": "8.0"
}
```

.. makes everything work again 😕 . As well, as putting it 8.0.2 or higher (tested with actual PHP runtime `8.0.25` and `8.1.11`). Bug still present if PHP override is 8.0 / 8.0.0 / 8.0.1 (maybe there is more)

**Comment by T2L** [comment]
> Preferring stable releases to beta ones is not a setting that resolves dependencies multiple times and then chooses between the different solutions based on the total number of unstable packages in them. It is a setting that affect _local_ decision when making a choice for each package. And a choice done for one package restrict the choices for the next decisions.
> Changing that behavior to be a global behavior would require rearchitecturing the whole dependency solver in a much slower way (as it would have to find _all_ solutions instead of finding _a_ solution, to compare them).

Yup, sounds harsh, but what about figuring out a version for specified package first and then do all others? Is it already like that?

**Comment by Seldaek** [comment]
Defining platform.php as `8.0` means `8.0.0` which is a bad idea if anything requires `^8.0.1` due to some critical bug for ex then it'll not be able to resolve, and I doubt you're actually running 8.0.0 so rather put the real version you're running. 

> what about figuring out a version for specified package first and then do all others? Is it already like that?

It's just more complex than you think I guess, but that does not sound possible to me, as there might be cases where if we resolve first to the most sensible root dependencies it could then not find transient dependencies to solve what's left. It has to be solved all in one go IMO.

You can also override stability per package so you could require like this and make sure you don't get beta for drupal/core:

```
        "drupal/core-recommended": "^9.4@stable",
        "drupal/core": "^9.4@stable",
```

**Comment by stof** [comment]
Also, if you really expect to use stable package, keeping the composer default behavior (`minimum-stability: stable`) might make more sense than using `minimum-stability: dev, prefer-stable: true`
