### ISSUE TITLE
HTTPS Conectivity & Github rate limit with error  in diagnose

### ISSUE THREAD

**Issue by brendondev** [composer/composer#11138]
As you can see below, I have a problem. First I tried to run the command "composer update" but the problem occurred just below.

![image](https://user-images.githubusercontent.com/47898677/196969200-d6960f46-2fa2-45d3-8052-96e717813760.png)

I looked for help in forums and searched but I didn't get any improvement, below is my "composer diagnose"
![image](https://user-images.githubusercontent.com/47898677/196968127-e259c727-2587-4b8e-b738-f89e941f7c92.png)

Can someone help me please?
Thanks.

**Comment by stof** [comment]
Well, it looks like your system does not managed to make HTTPS requests properly. Do you have a proxy that blocks HTTPS traffic ?

**Comment by brendondev** [comment]
> Well, it looks like your system does not managed to make HTTPS requests properly. Do you have a proxy that blocks HTTPS traffic ?

No, I don't :/

**Comment by Seldaek** [comment]
Perhaps a really really slow network? That's the 10sec connect timeout.. if it can't establish a connection in 10sec that sounds really terrible tho..

**Comment by brendondev** [comment]
> Perhaps a really really slow network? That's the 10sec connect timeout.. if it can't establish a connection in 10sec that sounds really terrible tho..

We managed to solve. The computer's IP was having some delay when renewing, so composer was giving us the error.
