### ISSUE TITLE
Changes to `psr-4` in symlinked package not recognized during `composer update`

### ISSUE THREAD

**Issue by bilogic** [composer/composer#11135]
package's `composer.json`:
```json
    "name": "bilogic/mypackage",
    "autoload": {
        "psr-4": {
            ...
        }
    },
```
project's `composer.json`:
```
  "repositories": [
        {
            "type": "path",
            "url": "path/to/bilogic/mypackage"
        }
    ]
```

1. I modified the `psr-4` section of `bilogic/mypackage`
2. I head over to my project and perform a `composer update`, which completes normally
    ```
    ...
    Lock file operations: 0 installs, 4 updates, 0 removals
      - Upgrading bilogic/mypackage (dev-master 113b4a1 => dev-master 576086e)  
    ...
    ```
3. However, the new namespaces are not found in the autoload_classmap.php/autoload_namespaces.php

And I expected this to happen:

I expected my project to be able to use the new entries when `composer update` is performed.
However, since they are not found in the autoload* files, project was not able to use them.

I had to `remove`, and `require` the package again in order for autoload_classmap.php/autoload_namespaces.php to be correct.

Unsure if this also happens for non symlinked packages

**Comment by stof** [comment]
How are you installing that package in your project ?

**Comment by bilogic** [comment]
@stof 

I have added my project's composer.json to the OP, I'm installing the package by `composer require bilogic/mypackage`

**Comment by stof** [comment]
what is "OP" in your sentence ?

**Comment by bilogic** [comment]
@stof OP = opening post

**Comment by Seldaek** [comment]
I cannot reproduce this:

```
$ cat vendor/composer/autoload_psr4.php
<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Foo\\' => array($vendorDir . '/bilogic/mypackage/src'),
);

$ c upd
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading bilogic/mypackage (dev-main 3322820 => dev-main 8d0c798)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Upgrading bilogic/mypackage (dev-main 3322820 => dev-main 8d0c798): Source already present
Generating autoload files
No security vulnerability advisories found

$ cat vendor/composer/autoload_psr4.php
<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Foo\\' => array($vendorDir . '/bilogic/mypackage/src'),
    'Bar\\' => array($vendorDir . '/bilogic/mypackage/src'),
);
```

After changing composer.json from

```json
{
    "name": "bilogic/mypackage",
    "autoload": {
        "psr-4": {
            "Foo\\": "src/"
        }
    }
}
```

to 

```json
{
    "name": "bilogic/mypackage",
    "autoload": {
        "psr-4": {
            "Foo\\": "src/",
            "Bar\\": "src/"
        }
    }
}
```

So if you need help here we'll need more details and perhaps a way to reproduce it.

**Comment by bilogic** [comment]
Thanks for the example, let me find some time to pin point what makes it happen on my end

**Comment by bilogic** [comment]
Ok, I found what caused the issue. 

>   - Upgrading bilogic/mypackage (dev-main 3322820 => dev-main 8d0c798)

After modifying my package's `composer.json` but not commited into git, I was expecting composer to "detect" the changed PSR-4.

In this case, I suppose it isn't an issue to be fixed, correct?

**Comment by Seldaek** [comment]
I *think* I didn't even have to commit to see the change here..

**Comment by bilogic** [comment]
Well, I was able to reproduce the issue. Then I saw your line which I quoted, and did a commit, then it worked.
Let me try a few more scenarios.

**Comment by bilogic** [comment]
@Seldaek 

1. Composer version 2.4.1 2022-08-20 11:44:50
2. PHP 7.4.32 

Are you using type `path` in ur project?
```
    "repositories": [
        {
            "type": "path",
            "url": "path/to/bilogic/mypackage"
        }
    ],
```

Without a commit, I'm seeing the issue.

**Comment by bilogic** [comment]
> Let me try a few more scenarios.

The other scenario was some of my packages are nested, i.e. i only require `child`, which requires the `parent`. 

It was had the same issue, if `parent` package has no commit, my composer did not update the PSR-4.

**Comment by bilogic** [comment]
Hi, were you guys able to reproduce this?

**Comment by bilogic** [comment]
My steps to reproduce is quite consistent now:

1. If `composer.json` is modified and committed, `composer update` will perform `Upgrading...`
2. If `composer.json` is modified and not committed, `composer update` will not perform `Upgrading...`

Is this by design?

**Comment by Seldaek** [comment]
@bilogic if composer.json is modified but not committed it should cause an update to happen as it should change the source/reference, but only if the path repo is not its own git repository. If it is its own repo then the commit reference takes precedence by default, and so you need to commit to make changes visible.

See the last bit of the https://getcomposer.org/doc/05-repositories.md#path section:
```
{
    "repositories": [
        {
            "type": "path",
            "url": "../../packages/my-package",
            "options": {
                "reference": "config"
            }
        }
    ]
}
```

Setting this would force it to always just read the composer.json to compute the reference, so it would solve this particular case but then it wouldn't update anymore when doing other commits. Which is fine if you are symlinking it I guess, but just overall some trade-off to be aware of.

Anyway if you still have an issue here please build a git repo (or set of repos) that reproduces the problem with clear repro steps.

**Comment by bilogic** [comment]
@Seldaek 

I finally found the root cause. Let me re-explain the whole situation:

1. Package A `composer.json` has `extra.laravel.aliases` and this gets captured in `vendor/composer/installed.json`
2. Now, Package A is symlinked and I decide to make changes to its `extra.laravel.aliases`, however, running `composer update` after does not propagate these changes to `installed.json`
3. Instead, I have to run `composer remove package-a` and `composer require package-a`
4. The problem is that step 3 is very slow

Any ideas?

**Comment by bilogic** [comment]
After a little bit more thought, my quickest workaround is to `rm vendor/composer/installed.json; composer update`, it's abit slower than the normal `composer update`, but saves me going through it 2 times.

**Comment by Seldaek** [comment]
I don't know what `extra.laravel.aliases` is nor what it does sorry, so that makes it a bit harder to help here.

I'll get back to what I wrote above:

> Anyway if you still have an issue here please build a git repo (or set of repos) that reproduces the problem with clear repro steps.

That'd make it way less ambiguous to look at this, because right now I have to assemble some sort of concept of what is going on from 10 comments above, and I can't make sense of it.

**Comment by bilogic** [comment]
@Seldaek 

I think there is no need to understand what `extra.laravel.aliases` does, knowing might actually lead to an overfitted solution.
And yes, I understand this is a long drawn issue, so ignore everything else and just try to follow my explanation here:

1. I'm symlinking some packages in `/vendor`
2. One of them is package A, its `composer.json` has `extra.aaa.bbb.ccc` and when I install it, `extra.aaa.bbb.ccc` gets captured in `vendor/composer/installed.json`
3. How it gets captured is internal to composer and I assume you are familiar
4. Now, as package A is symlinked and I decide to add `extra.ddd.eee.fff` to its `composer.json`
5. I expect `extra.ddd.eee.fff` to appear in `vendor/composer/installed.json` the next time I run `composer update`
6. However, `extra.ddd.eee.fff` does not appear today when I run `composer update`
7. Is my expectation reasonable?

Thanks!

**Comment by bilogic** [comment]
> appear in `vendor/composer/installed.json`

**Comment by Seldaek** [comment]
It sounds like a reasonable expectation yes, but to be able to look into this I need a reproducible setup, and to do that I need to know exactly how you have your path repo configured, because that impacts the updates quite a lot. That is why it would help a lot if you made a dummy git repo with some dummy packages that allow me to reproduce this with a similar setup you have.

**Comment by bilogic** [comment]
Ok, let me setup it thanks!
