### ISSUE TITLE
gcp cloud composer-2.0.29-airflow-2.2.5

### ISSUE THREAD

**Issue by imtiyaz081** [composer/composer#11145]
We have created cloud composer-2.0.29-airflow-2.2.5
when i tried to mount the bucket 
gcsfuse --implicit-dirs $INPUT_FILE_BUCKET gcp_inbound
throws error
Start gcsfuse/0.37.0 (Go version go1.17.2) for app "" using mount point: /home/airflow/gcs/gcp_inbound
Opening GCS connection...
Mounting file system "plexure-raw-data"...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: Mount: mount: running /bin/fusermount: exit status 1
Inbound bucket mount failed, exiting script../home/airflow/gcs/gcp_inbound
please help

```shell
cd ~/gcs/
mkdir -p gcp_inbound
chmod 777 gcp_inbound
sudo ln -s /proc/self/mounts /etc/mtab
fusermount -u gcp_inbound
#gcsfuse --implicit-dirs $INPUT_FILE_BUCKET gcp_inbound
mv gcp_inbound/* ~/gcs/dags/analytics/data_engineering/mountPointDump/

if [[ `ls | grep $INPUT_FILE_DIR_FULL` = $INPUT_FILE_DIR_FULL ]]
  then
    echo "Bucket already mounted."
    cd  gcp_inbound/$INPUT_FILE_DIR_FULL/
    ls -lrt
else
    gcsfuse --implicit-dirs $INPUT_FILE_BUCKET gcp_inbound
    if [ $? != 0 ]
    then
      echo "Inbound bucket mount failed, exiting script.."
      exit -1
    else
      echo "Bucket mounted successfully."
    fi
    cd ~/gcs/gcp_inbound/$INPUT_FILE_DIR_FULL/
    ls -lrt
fi
```

error log:
fusermount: entry for /home/airflow/gcs/gcp_inbound not found in /etc/mtab
 mv: cannot stat 'gcp_inbound/*': No such file or directory
 Start gcsfuse/0.37.0 (Go version go1.17.2) for app "" using mount point: /home/airflow/gcs/gcp_inbound
 Opening GCS connection...
 Mounting file system "plexure-raw-data"...
 daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: Mount: mount: running /bin/fusermount: exit status 1
Inbound bucket mount failed, exiting script..

**Comment by xabbuh** [comment]
This does not look related to this repository to me.
