### ISSUE TITLE
Nothing is returned from "composer outdated" command

### ISSUE THREAD

**Issue by Pasqualle** [composer/composer#11152]
composer outdated command should return some kind of information when every package is using the latest version.

When I run this command: 

```
composer outdated
```

I get the following output: 

```
big nothing
```

And I expected this to happen:

Honestly, I was expecting a little bit of celebration, a message like this would work:
"You lucky bastard, all your packages are fresh as a fart in the pants!"

**Comment by Seldaek** [comment]
I do see more than emptiness here on Composer 2.4+ 

```
$ c out

Direct dependencies required in composer.json:
Everything up to date

Transitive dependencies not required in composer.json:
Everything up to date
```

**Comment by Pasqualle** [comment]
Thank you for fixing this issue, and also thank you for creating composer.
