### ISSUE TITLE
Feature Request: OS Platform Requirements

### ISSUE THREAD

**Issue by donatj** [composer/composer#11168]
Please excuse me if this has been asked for before. I did quite a search of tickets before opening this - #10251 seems the closest but only tangentially related.

I've got a couple of packages that only work on UNIX-like OS's, and no matter how prominent I make it that this *does not work on Windows*, I still get tickets "Hey, I'm getting this weird error on Windows".

It would be fantastic if there were a way to specify something like `php-unix` or `php-!windows` or something. 

I'm taking inspiration from the way Go build tags work - they've got a list of Known OS's 

https://github.com/golang/go/blob/fb4f7fdb26da9ed0fee6beab280c84b399edaa42/src/cmd/go/internal/modindex/syslist.go#L12-L30

and then a special case for "unix" OS which means any of the following

https://github.com/golang/go/blob/27ace7ab9e1b690a672d0f7720680cb99e559854/src/cmd/go/internal/modindex/syslist.go#L35-L48

You'd have to do presumably some special parsing on `php-*` rules? I don't know if that's even the best way to do it.

Beyond that, I don't know how interested composer is on actually figuring out what OS it's running on and enforcing this sort of thing. I'll happily accept being told this isn't practical or doable, but I'd like my interest to be noted at least.

**Comment by donatj** [comment]
I'd also note that I'd be happy to try my hand at implementing it if there were in fact interest in said feature being built.

**Comment by stof** [comment]
To me, this has all of the same issues than #10251 (see my comments and comments from @Seldaek on that issue)

**Comment by Seldaek** [comment]
Yeah it is probably a tad less messy and a bit more broadly useful than cpu architectures, but it is still a niche requirement as generally speaking PHP code is pretty cross platform.

And there's still the issue that you can only require one OS at once, so that'd not fix all problems.

**Comment by donatj** [comment]
> And there's still the issue that you can only require one OS at once, so that'd not fix all problems.

When I was saying "special parsing on `php-*` rules" I was meaning to imply some sort of minor metalanguage, such that you could use it to specify things like `php-unix-!freebsd` or `php-windows-linux` or some such.

That might get messy though.

I don't know if a better option might be just special `"os"` or `"platform"` requirements? 

Anyway, I'm happy to close this if there's no interest in such a feature.

**Comment by Seldaek** [comment]
Yeah if anything I'd do a special `os` package like we have a special `php` one, having special constraints like `php-unix-!freebsd` sounds really like a no-go.

But yes overall I'd tend to say close as this is fairly fringe. IMO you should throw an exception outright in your code if it does not support windows with a clear message, that might help resolve the "weird errors on windows" reports? :)
