### ISSUE TITLE
Could not open input file: composer.phar

### ISSUE THREAD

**Issue by Chrysweel** [composer/composer#1116]
I have a problem! 
I try create a project new symfony2.1. I did the following steps:

1º curl -s http://getcomposer.org/installer | php
2º sudo mv composer.phar /usr/local/bin/composer
3º php composer.phar create-project symfony/framework-standard-edition var/www/myproject

My folder /usrl/local/bin  has a 777 permit

I do in my folder project : php composer.phar

But I have this error: Could not open input file: composer.phar

In my http://localhost/myproject/web/config.php

I have three problems: 
    Vendor libraries are missing. Install composer following instructions from http://getcomposer.org/. Then run "php composer.phar install" to install them.
    Set the "date.timezone" setting in php.ini\* (like Europe/Paris).
    Add "phar" to suhosin.executor.include.whitelist in php.ini*.

But php composer.phar install doesnt run.

Please help me, I have a project in symfony2.0.x and I want update to symfony2.1, but I do not know do it.

**Comment by zidorsml** [comment]
hi everybody! i'm beginer on php and yii2 framework, i have a probem with my composer.phar, i tried yo install a extention of yii2 here is the error message that i got: could not open the input file: composer.phar" so thank to you to help me resolve this problem, remember that i'm beginner in programation world, thank you

**Comment by xabbuh** [comment]
@zidorsml Are you sure that the `composer.phar` file is located in the same directory you are executing the command? Have you successfully download the Composer binary before?

**Comment by zidorsml** [comment]
thank you @xabbuh, i don't know if composer.phar file is located in the same directory, can you help me to verify and set it

**Comment by sathishfreaks5** [comment]
I think you composer may old. so please update with command as "php composer.phar self-update"
