### ISSUE TITLE
getcomposer.org/composer.phar fetching version 2.5-dev

### ISSUE THREAD

**Issue by jassik** [composer/composer#11198]
Related to site getcomposer.org, while fetching from https://getcomposer.org/composer.phar its downloading version "2.5-dev+bd6a5019b3bf5edf13640522796f54accaad789e (2.5-dev) 2022-11-17 10:34:54"
Tried it from different regions in AWS.
If this is the accepted behaviour then please point to the posting about this change and close this. Meanwhile fixing the script to download from:
https://getcomposer.org/download/latest-stable/composer.phar

HTTP header output:
`$ curl -I https://getcomposer.org/composer.phar -X GET
HTTP/2 200
server: nginx
date: Thu, 24 Nov 2022 10:51:58 GMT
content-type: application/octet-stream
content-length: 2832661
last-modified: Thu, 17 Nov 2022 10:34:54 GMT
vary: Accept-Encoding
etag: "63760e4e-2b3915"
accept-ranges: bytes`

**Comment by stof** [comment]
This is totally expected. This URL is the one for the nightly build of the main branch. See the "Manual download" section on https://getcomposer.org/download/ for the various available URLs.

**Comment by stof** [comment]
And this is not a change that has been done. This URL has been the URL download the latest snapshot since the creation of the getcomposer.org website years ago.
