### ISSUE TITLE
Feature request: last update time in `composer.lock`

### ISSUE THREAD

**Issue by zerkms** [composer/composer#11196]
What do you think about having composer.lock generation time?

I run projects in some pretty exotic proprietary environment and I want to alert about projects running with no updates for too old. At the moment there is no reliable timestamp anywhere in composer, having a field in `composer.lock` would be ideal for my use case.

**Comment by stof** [comment]
`git log -1 --pretty="format:%ci" composer.lock` will tell you the date of the last commit that changed the composer.lock file ([thanks StackOverflow](https://stackoverflow.com/questions/22497597/get-the-last-modification-date-of-a-file-in-git-repo)). If you use another VCS instead of git, it probably has a similar feature.
Isn't this enough for your use case ?

**Comment by Seldaek** [comment]
Yeah I would also say please use your VCS. Adding something like a last time modified will just create even more conflicts for not much added value.

**Comment by zerkms** [comment]
@stof 

"Isn't this enough for your use case ?" --- nope, only project files are deployed to the target with no VSC history whatsoever.

**Comment by Seldaek** [comment]
Then as alternative solution check the release date of each package in the lock file to find the latest possible update time, or the filemtime in case that's older than the deploy time.

The release date would be an approximation but probably not the worst if you only want to alert for very outdated files.

**Comment by zerkms** [comment]
@Seldaek exactly, that was my last resort: it would be better than nothing. And after your message that it will create more conflicts - I also agree that merge conflicts with this single line will be annoying people.

**Comment by stof** [comment]
@zerkms then make your deployment process read the time from git and include it in a separate deployed file if you need the precise date without deploying the git metadata.

**Comment by zerkms** [comment]
@stof if there was a simple solution - I wouldn't be here asking this feature request.
