### ISSUE TITLE
Support multiple Gitlab Tokens for the same instance

### ISSUE THREAD

**Issue by AdrienPoupa** [composer/composer#11204]
I am using the Composer repository of a private GitLab instance. I setup a deploy token for group A, so that all projects under A can be accessed, and it works fine. I setup my composer.json and auth.json as described in the GitLab documentation: https://docs.gitlab.com/ee/user/packages/composer_repository/#working-with-deploy-tokens

composer.json
```json
...
  "config": {
    "gitlab-domains": ["gitlab.mydomain.ca"],
  },
...
  "repositories": {
    "A_ID": {
      "type": "composer",
      "url": "https://gitlab.turbulent.ca/api/v4/group/A_ID/-/packages/composer/",
      "only": ["a/*"]
    },
...
```

auth.json
```json
{
    "gitlab-token": {
        "gitlab.mydomain.ca": {
            "username": "deploy-token-group-A",
            "token": "redacted"
        }
    }
}
```

Now, I want to access all packages from group B. I created a new deploy token for group B, and I did this:

composer.json
```json
...
  "config": {
    "gitlab-domains": ["gitlab.mydomain.ca"],
  },
...
  "repositories": {
    "A_ID": {
      "type": "composer",
      "url": "https://gitlab.mydomain.ca/api/v4/group/A_ID/-/packages/composer/",
      "only": ["a/*"]
    },
    "B_ID": {
      "type": "composer",
      "url": "https://gitlab.mydomain.ca/api/v4/group/B_ID/-/packages/composer/",
      "only": ["b/*"]
    },
...
```

But it seems I cannot specify multiple deploy tokens **for the same GitLab instance**.

Ideally I would be able to do something like this, but it seems Composer will only read one token.

auth.json
```json
{
    "gitlab-token": {
        "gitlab.mydomain.ca": [
          {
            "username": "deploy-token-group-A",
            "token": "redacted"
          },
          {
            "username": "deploy-token-group-B",
            "token": "redacted"
          }
        ]
    }
}
```

I guess we could either
- try several tokens as shown above
- maybe specify the group ID in auth.json?

```json
{
    "gitlab-token": {
        "gitlab.mydomain.ca/A_ID": {
            "username": "deploy-token-group-A",
            "token": "redacted"
        },
       "gitlab.mydomain.ca/B_ID": {
            "username": "deploy-token-group-B",
            "token": "redacted"
        }
    }
}
```

**Comment by Seldaek** [comment]
TBH this seems like the kind of complication I'd rather not deal with as it adds even more complexity and maintenance burden to GitLab stuff which is already under-tested.

FWIW [Private Packagist](https://packagist.com/) does support multiple sources (as well as GitLab sync) and can then expose all this nicely to Composer as a repo with a single credential (amongst other nice features). It's not free but it should help here.

**Comment by AdrienPoupa** [comment]
I understand this is a bit beyond the expected scope of the feature :) but I guess the same reasoning would apply to GitHub as well? say you want to access 2 different private repos with different tokens, I am not sure the current implementation makes it possible: https://getcomposer.org/doc/articles/authentication-for-private-packages.md#github-oauth

**Comment by Seldaek** [comment]
Of course, the solution is to ensure you have simple enough permissions that you can access all things with one user/token. If not then you need to group things somehow using an intermediary repository like Private Packagist does.

**Comment by maantje** [comment]
To ensure you can authenticate with both registries using a single token, follow these steps:

-  **Create a service account in GitLab** by following [these instructions](https://docs.gitlab.com/ee/api/group_service_accounts.html#create-a-service-account-user). Once the account is created, navigate through all relevant groups and assign the service account membership to each group.

- In the **GitLab admin UI**, go to "Users," locate the service account user, and create an impersonation token. When generating the token, use scope: `read_api`.

- Finally, use the impersonation token in your `auth.json`, and everything should work smoothly.
