### ISSUE TITLE
WSL docker detection does not work during Buildkit builds

### ISSUE THREAD

**Issue by ciaranmcnulty** [composer/composer#11207]
When running composer during a Buildkit build in WSL2, container environment detection does not work properly

## Reproducer

Dockerfile:
```Dockerfile
FROM composer

WORKDIR /app

RUN composer require phpunit/phpunit
RUN ls -al /
RUN ls -al vendor/bin/
```

Building this on a WSL machine without buildkit (`DOCKER_BUILDKIT=0 docker build .`) outputs:
```
Removing intermediate container 619c712e147b
 ---> 7c84fb83330c
Step 4/5 : RUN ls -al /
 ---> Running in 8689d96b37cd
total 72
drwxr-xr-x   1 root root 4096 Dec  2 16:01 .
drwxr-xr-x   1 root root 4096 Dec  2 16:01 ..
-rwxr-xr-x   1 root root    0 Dec  2 16:01 .dockerenv
drwxr-xr-x   1 root root 4096 Dec  2 16:01 app
drwxr-xr-x   1 root root 4096 Nov 30 22:53 bin
[... snipped ...]
Removing intermediate container 8689d96b37cd
 ---> 6e3ed5bda50e
Step 5/5 : RUN ls -al vendor/bin/
 ---> Running in b6a9e67923f9
total 16
drwxr-xr-x  2 root root 4096 Dec  2 16:01 .
drwxr-xr-x 11 root root 4096 Dec  2 16:01 ..
-rwxr-xr-x  1 root root 3351 Dec  2 16:01 php-parse
-rwxr-xr-x  1 root root 3692 Dec  2 16:01 phpunit
Removing intermediate container b6a9e67923f9
 ---> 33d0891ade68
Successfully built 33d0891ade68
```

However using buildkit (`DOCKER_BUILDKIT=1 docker build .`, or without the env var on later versions) outputs:

```
#7 [4/5] RUN ls -al /
#7 0.715 total 76
#7 0.715 drwxr-xr-x   1 root root 4096 Dec  2 15:58 .
#7 0.715 drwxr-xr-x   1 root root 4096 Dec  2 15:58 ..
#7 0.715 drwxr-xr-x   1 root root 4096 Dec  2 15:58 app
[ ... snipped, no .dockerenv ...]
#7 DONE 0.7s

#8 [5/5] RUN ls -al vendor/bin/
#8 0.652 total 24
#8 0.652 drwxr-xr-x  2 root root 4096 Dec  2 15:58 .
#8 0.652 drwxr-xr-x 11 root root 4096 Dec  2 15:58 ..
#8 0.652 -rwxr-xr-x  1 root root 3351 Dec  2 15:58 php-parse
#8 0.652 -rwxr-xr-x  1 root root  136 Dec  2 15:58 php-parse.bat
#8 0.652 -rwxr-xr-x  1 root root 3692 Dec  2 15:58 phpunit
#8 0.652 -rwxr-xr-x  1 root root  134 Dec  2 15:58 phpunit.bat
#8 DONE 0.7s
```

So even thought we're in a linux docker build, windows files are being created

## Root cause

The relevant code seems to looks for `/.dockerenv` as a clue that the environment is a container, but Buildkit does not provide that

This is possible to work around by setting `bin-compat` to a value other than auto, but for us it triggered a bug that was tricky to find because it's not intuitive that the linux container can have differences in filesystem structure to the ones built by colleagues on other OSes.

## Fix

One option is to change the behaviour on WSL overall, but I've no visibility on whether that'd be bad DX for Windows users.

Otherwise, the detection needs to be improved with some additional check to see if we're running in a docker buildkit build. 

I'm not sure if there's a stable way, but I've seen that `/proc/self/cgroup` contains the phrase `buildkit` on my machine at least - it'd need to be checked by a WSL user

The reliance by various libraries on `.dockerenv` has always been a hack, but maybe enough are doing it now that this should be a buildkit issue? I'll raise on their Slack

**Comment by GeeH** [comment]
Hit me up if anyone needs me to do any testing on WSL system; thanks for reporting.

**Comment by ciaranmcnulty** [comment]
Raised the point with buildx maintainers https://github.com/docker/buildx/issues/1447

**Comment by Seldaek** [comment]
Yeah not much we can do here until upstream provides us with a good way to detect this.. We can add hacks over hacks and add the `buildkit` detection if that works in WSL.. but it's only a band-aid :/

**Comment by ciaranmcnulty** [comment]
Is there a source for discussion of this feature somewhere? I don't want to rake over old ground if it's already been argued out, but the behaviour seems counterintuitive on the surface 

Rather than detecting the container, is there something more directly environmental that can be used to detect WSL that wouldn't be present in a container, maybe?

**Comment by Seldaek** [comment]
Well we need to detect WSL and make it behave as if it was windows by default so that if you run `cmd.exe` or whatever you have the .bat files there and things just work. So we can detect WSL using the /proc/version thing we have now.. 

I am not aware of any other way, and https://github.com/microsoft/WSL/issues/4071 doesn't seem to have much either. Unfortunately Docker doesn't isolate you from the kernel it's running on, so there is some leakage, and Docker also has no great way to detect it.

**Comment by Seldaek** [comment]
We did some docker detection fixes in the last few releases, so hopefully this improved.. And if not well closing anyway until someone comes up with a better detection method 🤷🏻
