### ISSUE TITLE
Minify lockfile

### ISSUE THREAD

**Issue by fruitl00p** [composer/composer#11203]
I'd like to request a feature / improvement for review policies: i'd like to minify the composer.lock file by removing superflous data from it (optionally via --minify-lock or something) Currently when reviewing updates to a lockfile one has to wade through many more differences than necessary due to adding in changes in the:
- authors field (i.e. re-ordering)
- description
- type
- notify
- license
- keywords
- support

By removing these items per package it would allow for far easier reviewing and also decrease the lock file size withouth actually losing functional data... 

I haven't found any previous requests / issues regarding this.

**Comment by stof** [comment]
Removing the license will break the `composer licenses` command. Removing the type will break support for custom installers (as the type is one of the criteria to choose the installer). Removing `notify` will break reporting installs to packagist.

And removing others will have an impact on `composer show` and such commands.

To ease reviews, there are tools providing human-readable diffs:
- Private Packagist has a GitHub integration reporting this in a GitHub comment (look at PRs updating the composer.lock on this repo to have an example)
- https://github.com/davidrjonas/composer-lock-diff is a CLI tool generating such diff in various formats (including markdown that you can paste in a GitHub comment)

I also heard about a similar tool implemented as a composer plugin but I don't remember its name.

**Comment by fruitl00p** [comment]
Thanks! The output of composer-lock-diff is exactly what i'm looking for! This would alleviate the review burdon by ALOT and shows the reviewer exactly what they would like to see.
(we're mostly running on Gitlab so we'll have to create some sort of GL-action that hooks into MR's et al, but we'll figure it out!)

Thanks alot!
