### ISSUE TITLE
Bower Repository

### ISSUE THREAD

**Issue by RobLoach** [composer/composer#1121]
[Bower](http://twitter.github.com/bower/) is a package management system for JavaScript and CSS assets. A list of Bower packages is available here: http://sindresorhus.com/bower-components/ . The source and repositories for these packages is fed from here: http://bower.herokuapp.com/packages

[JamJS](http://jamjs.org/) is another package management system for web assets. Worth mentioning.

Leveraging these repositories from Composer would expose a huge amount of new packages to be consumed.

**Comment by mzgol** [comment]
FWIW, jQuery has been published to npm since 1.11/2.1; it's a regular jQuery, without any Node-specific wrapping.

**Comment by Seldaek** [comment]
Closing as it's very unlikely and not sure it's desirable tbh.

**Comment by lkraav** [comment]
PS in the JS ecosystem, numerous arguments have lately been made towards dropping `bower` in favor of `npm`.

https://github.com/necolas/normalize.css/pull/455
https://gofore.com/stop-using-bower/

etc. For more, google the relevant keywords and notice pull requests all around.
