### ISSUE TITLE
[FeatureRequest] Composer info with Date of the tag

### ISSUE THREAD

**Issue by alexander-schranz** [composer/composer#11225]
To search for a bug which was introduced by one of a vendor package. It would be nice if `composer info` would also display the `date` of when the tag was created for the package. Current output:

```
sulu/sulu                                 2.5.4              Core framework that implements the functionality of the Sulu content management system
sulu/sulu-rector                          0.1.2              Rector upgrades rules for Sulu CMS
sulu/web-twig                             v2.5.6             The web twig extension for web-js component management
```

It would be creat to display side to the version also the date when the tag was created:

```
sulu/sulu                                 2.5.4 (2022-11-29)              Core framework that implements the functionality of the Sulu content management system
sulu/sulu-rector                          0.1.2 (2022-08-18)              Rector upgrades rules for Sulu CMS
sulu/web-twig                             v2.5.6 (2022-10-22)            The web twig extension for web-js component management
```

Additonal it would be nice to sort by that date to show latest at the top.

I current workaround this via `composer install --prefer-source` and [a custom script](https://gist.github.com/alexander-schranz/c9017ea31bf2b789cc366f4503916639).

**Comment by Seldaek** [comment]
I have a feeling like #11119 would be a more useful feature for this use case. 

But perhaps we could add a `--by-date` or something showing the dates and ordering, not sure how messy/hard this would be, the show command is already quite a beast.

**Comment by alexander-schranz** [comment]
> I have a feeling like https://github.com/composer/composer/issues/11119 would be a more useful feature for this use case.

That is create feature. But you first need as I see to know which package does produce the bug before you can do a bisect for that package.

> But perhaps we could add a --by-date or something showing the dates and ordering, not sure how messy/hard this would be, the show command is already quite a beast.

That would be awesome, I'm also not sure if there is anything possible to get the `tag` date, I currently workaround in my custom script to get the `commit` date where the tag is targetting which is not always the date when the tag was created, but is maybe also an edge case which can be ignored.

**Comment by Seldaek** [comment]
Packages have a release date (which is usually the tag/commit date) so we can work with that,

**Comment by Seldaek** [comment]
`composer show -A -l` (sort by age + show latest) now shows you how old the release is so you can see newest packages towards the bottom.
