### ISSUE TITLE
The new install validation changes in 2.5.0 broke Renovate Bot support for Composer

### ISSUE THREAD

**Issue by rarkins** [composer/composer#11232]
@PrinsFrank @Seldaek I think you should consider reverting #11195

Until 2.5.0, Renovate would do these simple things to update a user:
- Make changes to `composer.json` as desired (can be one or multiple changes)
- Run `composer install` + `composer update` to synchronize `composer.lock`

This is no longer possible, and means Renovate can no longer update users with Composer 2.5.0.

Looking at #11154 seems to confirm that this change was undesirable as there's no way to opt out of this new behavior. For example the plan A involves running `composer update` which is acknowledged there as undesirable because will upgraded all locked versions.

The old Composer behavior, which "repairs" a lock file by default if it is out of sync with the package file, was in line with other package managers and should ideally be restored. The new behavior could be behind a flag like `--strict`. If you were to make strict mode default, it should not be done without an accompanying flag to allow non strict mode (old behavior).

**Comment by Seldaek** [comment]
> * Run `composer install` to synchronize `composer.lock`

I don't understand what you mean by this.

If I try with Composer 2.4.4 to run `composer update` to get a lock file, then add a requirement for ex, then run `composer install` I simply get this output:

```
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Nothing to install, update or remove
Generating autoload files
25 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

Note the warning line indicating the composer.lock is not up to date. But it *does not* modify nor synchronize the lock file on install, and it does not install the newly required packages either as it only installs what is in the lock file.

So I am not sure how Renovate could function if it relied on this behavior which as far as I can tell does not exist.

**Comment by Seldaek** [comment]
And it's the same when editing the constraint of an already existing/locked package to bump it e.g. lock file has 3.0 and I change the require to 3.1, I also just get a warning and no update or install done in Composer 2.4.4, 2.5.0 fails indeed as it should IMO.

**Comment by bobvandevijver** [comment]
It is a bit more subtle, the process renovate uses is as follows:

- Change the `composer.json` to update a packages constraint
- Runs `composer install` to make sure dependencies for composer lookup, such as `symfony/flex`, are available as they can limit the resolution of the update command
- Runs `composer update <package>` to actually update the lock file

Now the warning has been converted into an error, this process fails with 2.5.0.

As an example, the command renovate uses for one of my projects:

```
docker run --rm --name=renovate_sidecar --label=renovate_child -v \"/cache/renovate/drenso/repos/gitlab/extern/project\":\"/cache/renovate/drenso/repos/gitlab/extern/project\" -v \"/cache/renovate/drenso/cache\":\"/cache/renovate/drenso/cache\" -e COMPOSER_CACHE_DIR -e COMPOSER_AUTH -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w \"/cache/renovate/drenso/repos/gitlab/extern/project\" docker.io/renovate/sidecar bash -l -c \"
install-tool php 8.1.13 
&& install-tool composer 2.5.0 
&& composer install --ignore-platform-req ext-apcu --ignore-platform-req ext-calendar --ignore-platform-req ext-decimal --ignore-platform-req ext-exif --ignore-platform-req ext-gd --ignore-platform-req ext-imagick --ignore-platform-req ext-intl --ignore-platform-req ext-ldap --ignore-platform-req ext-pdo --ignore-platform-req ext-sodium --ignore-platform-req ext-xsl --ignore-platform-req ext-zip --no-ansi --no-interaction --no-scripts --no-autoloader 
&& composer update doctrine/persistence --with-dependencies --ignore-platform-req ext-apcu --ignore-platform-req ext-calendar --ignore-platform-req ext-decimal --ignore-platform-req ext-exif --ignore-platform-req ext-gd --ignore-platform-req ext-imagick --ignore-platform-req ext-intl --ignore-platform-req ext-ldap --ignore-platform-req ext-pdo --ignore-platform-req ext-sodium --ignore-platform-req ext-xsl --ignore-platform-req ext-zip --no-ansi --no-interaction --no-scripts --no-autoloader
```

So, the new strict behaviour is a bit too strict for this usage (btw, I check our lock validity in our pipelines anyways with `composer validate --no-check-all`), so a flag to either enable/disable this behaviour would be great.

**Comment by Seldaek** [comment]
Ok so it sounds to me like you should do the install *before* modifying the composer.json, and everything then should go according to plan.

**Comment by rarkins** [comment]
Having an option to pass a non-strict flag to the install process would be a user-friendly (not just bot-friendly) solution, if you choose not to revert behavior back to how it was. I still think that keeping non-strict behavior by default and then adding a `--strict` option would have been ideal for a minor release.

**Comment by Seldaek** [comment]
A complete rewrite?! That sounds a little hyperbolic.. 

This was always a broken use case IMO, and the warning highlighted that, but the fact is nobody reads warnings.

The fact that other package managers modify the lock file on install is IMO super strange and unexpected, as it reduces the guarantees of reproducibility and determinism of the outcome when you run an install from a lock file. If you change your requirements and did not update the lock file then clearly something is wrong, and the lock file is not representative of your requirements anymore. Installing that is wrong, and modifying the lock file in any way during install is also conceptually wrong (again IMO..).

I think npm for example does what it does because they didn't start out with a lock file, and it was bolted on later and it wasn't possible to handle this strictly.

@rarkins is there no option for you to install dependencies before you modify the composer.json?

**Comment by rarkins** [comment]
Here's my current thoughts:
- By default, strict mode makes most sense
- Changing from non-strict to strict in a minor release is a breaking change, ideally should not have been done
- If you have strict mode, you need to support non-strict as an option

The way Renovate works, it makes changes to the `composer.json` first itself, and then syncs the `composer.lock` using `composer` itself.

So what we would need to try is something like:
- Make changes to `composer.json`
- Reset/stash changes before running `composer install`
- Reapply changes
- Run `composer update` commands

**Comment by rarkins** [comment]
We can try with `git stash -- composer.json && composer install && git stash pop` as a workaround

**Comment by bobvandevijver** [comment]
@Seldaek I can make a PR to add an `--ignore-lock-errors` switch to the install command, would that something that you would be willing to merge?

**Comment by Seldaek** [comment]
> We can try with `git stash -- composer.json && composer install && git stash pop` as a workaround

That does sound like a workable workaround for sure.

Just as an additional idea though, if you added a setup step which runs before you update the composer.json, you could move the `install-tool php 8.1.13 && install-tool composer 2.5.0 && composer install ...` into that step.

> @Seldaek I can make a PR to add an `--ignore-lock-errors` switch to the install command, would that something that you would be willing to merge?

I'd rather not add this if we can avoid it. Renovate is a specific and niche use case, and I fail to see how this flag would be needed for regular operation of Composer. Until I see more demand and valid use cases I'd rather keep things simpler.

**Comment by rarkins** [comment]
Thanks very much for the quick and helpful responses today. I would like to summarize while closing:
- The error affects `symfony/flex` users only, because that was the only scenario where an install was needed before the updates
- The git stash workaround appears to work, so we'll add this to our code base (for all composer versions)

**Comment by Seldaek** [comment]
Great to hear the workaround works on your end 👍🏻
