### ISSUE TITLE
installing a package from an empty location should error

### ISSUE THREAD

**Issue by gwenya** [composer/composer#11242]
When running `composer install` with a dependency that is set up as a `path` repository which points to an empty directory, composer symlinks or copies that empty directory and then silently deletes it again, without showing any indication in its output that this happened. As far as I can tell, this happens in the `cleanup` function of the `FileDownloader`: https://github.com/composer/composer/blob/d047f38f73629f876226f61331db6b889f4dcafe/src/Composer/Downloader/FileDownloader.php#L322-L339

In my opinion trying to install an empty package should be treated as an error condition instead of pretending that the install was successful.

**Comment by gwenya** [comment]
Yes, correct. The problem occurred because of a mistake in the build process that left the dir empty. 

Thinking about it, this is maybe not an error condition after all, but IMO then the empty directory should not be deleted.

**Comment by Seldaek** [comment]
I cannot reproduce this please send clear repro steps.
