### ISSUE TITLE
When installing composer i get an error saying something is missing in the php.ini file but it doesn't specify what is missing.

### ISSUE THREAD

**Issue by Jhonattan-Rapprecht** [composer/composer#11248]
My `composer.json`:

```json
...replace me...
```

Output of `composer diagnose`:

```
...replace me...
```

When I run this command: 

```
...replace me...
```

I get the following output: 

```
...replace me...
```

And I expected this to happen:

**Comment by xabbuh** [comment]
What is the exact error message that you get?

**Comment by Jhonattan-Rapprecht** [comment]
I dont get an error message. It just says required settings in php.ini ate
not met but then it doesn't specify what requirements are not met.

I solved this by installing php version 8 instead of 8.2. But i would like
to use the latest php version with composer of course but can't seem to
install it.

Op zo 1 jan. 2023 14:14 schreef Christian Flothmann <
***@***.***>:

**Comment by Seldaek** [comment]
If you share the error message maybe someone can help but as such it's pretty hard.. Closing until we get more info
