### ISSUE TITLE
Add support for platform-dev config

### ISSUE THREAD

**Issue by JasonTheAdams** [composer/composer#11253]
We maintain a project that has a platform php version of 7.2. We do, however, use packages for bundling and such that require PHP 7.4 — PHPStan, for example. Presently, this isn't possible to distinguish in Composer.

It would be useful to lock certain packages based on the dev requirements, and lock others based on the application requirements. If there's a conflict — a package is shared by both the application and dev — then it should fall back on the application's needs. If this creates a dependency chain issue, then raise it as an error.

```json
"config": {
  "platform": {
    "php": "7.2"
  }
  "platform-dev": {
    "php": "7.4"
  }
}
```

**Comment by JasonTheAdams** [comment]
Turns out we need this more than I realized. Not only is the platform php version used for managing package versions, but it will also prevent the autoloader from even running if a lesser version is used! This means that if we have a dev dependency that requires 7.4, then the entire application has to run on 7.4. 😬

**Comment by stof** [comment]
Composer does not do separate dependency resolutions for `require` and `require-dev` (because all dependencies have to be compatible together). So this is not possible.

**Comment by JasonTheAdams** [comment]
I can appreciate that it's not currently possible, and may never be in v2. Still, would you say it sounds like a useful/reasonable use-case to consider? My team and I have run into a number of scenarios wherein build needs and application needs are different. Dev tools tend to be more cutting edge (especially in terms of PHP version), while application packages tend to take backwards-compatibility more seriously.

**Comment by stof** [comment]
Well, if tools must run in the same process than your own code (PHPUnit for instance), then it requires using compatible dependencies. And this means it cannot be resolved separately (and so cannot use a different target platform).

For tools that don't need to execute your code in their process (coding standard linters for instance), a solution is to install them separately (and so their dependency resolution is isolated and can use a different target). https://github.com/bamarni/composer-bin-plugin helps achieving that (that's how [scssphp](https://github.com/scssphp/scssphp) installs phpstan for instance as the 1.x branch supports PHP 5.6+).

**Comment by JasonTheAdams** [comment]
Ohhh, PHPUnit is a very good example of when you're both running a tool **and** your own code at the same time. Thank you for pointing out the composer-bin-plugin. I'll give that a look!
