### ISSUE TITLE
PHP Version 8.1.12 installed and but when try to install Composer "PHP version (1.0.0) does not support" error get

### ISSUE THREAD

**Issue by nkuldip** [composer/composer#11261]
**When trying to install the composer get an error.**

![image](https://user-images.githubusercontent.com/12135394/211535643-312243f9-3878-4298-8404-1c7febbb7d1f.png)

**One more issue is when I try to open the Command prompt and check the PHP version then also open the Interactive shell prompt.**

![image](https://user-images.githubusercontent.com/12135394/211535984-5983414f-7ec0-421c-93ae-3cf3831e379e.png)

Please help me how to fix these issues.
Thanks

**Comment by stof** [comment]
it looks like your `php` executable is a weird thing here and not the actual PHP executable. You might need to contact the xampp support about that.

**Comment by Seldaek** [comment]
PHP 1.0.0 🤨

**Comment by Seldaek** [comment]
Pinging @johnstevenson just in case he's got a clue.

**Comment by johnstevenson** [comment]
Sorry, no ideas without a log file, which should tell us where the version info came from.

Please follow the instructions here to provide one: https://github.com/composer/windows-setup/issues/new

**Comment by nkuldip** [comment]
Hello @johnstevenson 
When I re-install xampp on a different folder/drive then the composer was installed and working fine. But after some time suddenly opened **Interactive shell prompt** when I was trying to use composer. 

Uninstalled composer and installed again composer then got an error while installing  **You PHP version(1.0.0) does not support the TLC...etc**
