### ISSUE TITLE
[Help Wanted] Created Package Classes not found

### ISSUE THREAD

**Issue by tuxtux59** [composer/composer#11263]
Hello,

I'm quite new to Composer/Packagist and my PHP experience is bit old.
I created a package that I pushed on packagist.

To test it, I created a PHP project and require my package using composer.

But when I want to use one of classes present in this package, I got a `Class \"MyPackage\\SDK\\MyClass\" not found`.
My current workaround for now is to load directly php file through vendor tree folder.

I've checked into `vendor/composer/autoload_psr4.php` file and I have

```php
'MyPackage\\SDK\\' => array($vendorDir . '/my-package/my-package-php/src'), // seems to be the good path
```
I tried `composer install && composer dump && composer dump-autoload -o` without success

So with these informations I don't understand what wen wrong.
Could it be my original package config ? Or the current project config ?

My `composer.json`:

```json
   "require": {
        "php": ">=7.3",
        "my-package/my-package-php": "dev-develop"
    },
    "minimum-stability": "dev",
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK git version 2.37.1
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: WARNING
Composer is configured to disable SSL/TLS protection. This will leave remote HTTPS requests vulnerable to Man-In-The-Middle attacks.
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: XXX
Dev Public Key Fingerprint: XXX
OK
Checking composer version: Warning: Accessing getcomposer.org over http which is an insecure protocol.
OK
Composer version: 2.5-dev+f07614f1c948a7b961b2da3b91506716a8ba8124
PHP version: 8.1.13
PHP binary path: /usr/local/Cellar/php/8.1.13/bin/php
OpenSSL version: OpenSSL 1.1.1s  1 Nov 2022
cURL version: 7.86.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1s
zip: extension present, unzip present, 7-Zip not available
```

When I run the server using `php -S localhost:4002 index.php`

Here is my index file
```php
<?php
require_once __DIR__ . '/vendor/autoload.php';

// require_once(__DIR__ . '/vendor/my-package/my-package-php/src/MyPackage/MyClass.php'); <- uncommented like fix

use MyPackage\SDK\MyClass;

new MyClass(); <- this fails
```

I get the following output:

```
Class \"MyPackage\\SDK\\MyClass\
```

And I expected no crash and class instance creation.

By the way I also tried with `"vendor_dir": "vendor/"` hoping that __DIR__ in autoload_psr4 file wasn't right

Thanks by advance

**Comment by pjpawel** [comment]
Hi, can you provide an example with any existing package? It can be something wrong with a your package, which is named here as "my-package/my-package-php".

**Comment by Seldaek** [comment]
vendor/my-package/my-package-php/src/MyPackage/MyClass.php should be in vendor/my-package/my-package-php/src/MyClass.php without `MyPackage/` in the middle I believe given the information you gave above. If that doesn't help you'll have to give more accurate info.
