### ISSUE TITLE
Feature Request: Control in which order composer autoloads includes files

### ISSUE THREAD

**Issue by snake-py** [composer/composer#11273]
Hello,

I am maintaining multiple packages which publish via ./src/helper.php some global helper methods. Therefore I have in the composer.json inside the packages defined:

```json
    "autoload": {
        "files": [
            "./src/helpers.php"
        ],
    } 
```
However, inside my Laravel projects, I want to overwrite some of these helpers, therefore I would like that app/helper.php is loaded before vendor/mypackage/src/helper.php

in the laravel project, I have defined:
```json
    "autoload": {
        "files": [
            "./app/helpers.php"
        ],
```
I think currently there is no way to tell composer that it should first load the project base helper file.

A concrete example I am trying to override would be this. In my package for testing (and as a fallback to avoid crashes) purposes I have defined:

```php
if (!function_exists('getEnvironment')) {
    function getEnvironment(): string
    {
        return config('wd.logging.environment', 'DEFAULT_ENV');
    }
}
```
and in my project I need to overwrite it with this function (this function should be used in production):
```php
if (!function_exists('getEnvironment')) {
    function getEnvironment(): string
    {
        return Auth::user()
            ? getSetting(Auth::user()->client->settings, Setting::KEY_SHORT_CODE)
            : null;
    }
}
```

**Comment by stof** [comment]
Composer will require files from a package after the files from all its dependencies (and so the root package is the last one). This ensures that a package file has access to the functions defined in its dependencies.

**Comment by snake-py** [comment]
@stof I understand this and this behavior is solid. However, I would love that I can preload global files to overwrite files from dependencies. I found a composer plug in which does this already, but I thought this should be also be included into the core concept.  
maybe something like:

```json
    "autoload": {
        "perload": [
            "app/helpers.php"
        ]
    },
``` 

this is the plugin I started using to have this behavior https://github.com/funkjedi/composer-include-files

**Comment by Seldaek** [comment]
If you want to override in the project you can include your own files before you include `vendor/autoload.php`, that will ensure they are always loaded first. We are not going to support more fine grained use cases than this because they are IMO bad practices. Perhaps we will one day get native function autoloading that will allow improving the situation..

**Comment by snake-py** [comment]
@Seldaek Could you elaborate on why this is bad practice? It seems that this is how Laravel wants it or do I misunderstand it?

**Comment by Seldaek** [comment]
I just don't think having function helpers is a great thing because it's hard to override them, they're global and cannot easily be dependency injected (I guess you technically can but in practice nobody does..). Classes with dependency injection are way more versatile but it takes a few more characters to write.

**Comment by djmetzle** [comment]
Would there be an appetite for a pull request addressing this?
- https://github.com/composer/composer/pull/12820

The situation described in this issue affects our org, and we are forced to use the [helper plugin](https://github.com/funkjedi/composer-include-files) to address the problem.
