### ISSUE TITLE
Confusing silence on `composer outdated`

### ISSUE THREAD

**Issue by dereuromark** [composer/composer#11280]
When running `composer oudated` on a project that is locked to 7.4+, it shows empty result.
This means that all versions seem to be in the latest major, minor, patch:

```
Direct dependencies required in composer.json:
friendsofcake/bootstrap-ui 3.1.2  4.0.1  Bootstrap front-end framework support for CakePHP

Transitive dependencies not required in composer.json:
symfony/service-contracts  v1.1.2 v2.5.2 Generic abstractions related to writing services
```

But in fact, they are not.
Some, e.g. symfony/* v6 are just skipped because they are 8.0+

I would expect the output to reflect that somehow, with the info why (not possible due to the min PHP version).

One could (re)install https://github.com/soullivaneuh/composer-versions-check which would show the expected outcome:
```
16 packages are not up to date:

  - doctrine/instantiator (1.5.0) latest is 2.0.0

  - friendsofcake/bootstrap-ui (3.1.2) latest is 4.0.1

  - laminas/laminas-diactoros (2.17.0) latest is 2.24.0

  - laminas/laminas-httphandlerrunner (2.2.0) latest is 2.5.0

  - monolog/monolog (2.8.0) latest is 3.2.0

  - psr/cache (1.0.1) latest is 3.0.0

  - psr/log (1.1.4) latest is 3.0.0

  - psr/simple-cache (1.0.1) latest is 3.0.0

  - symfony/config (v5.4.19) latest is v6.2.5

  - symfony/console (v5.4.19) latest is v6.2.5

  - symfony/deprecation-contracts (v2.5.2) latest is v3.2.0

  - symfony/filesystem (v5.4.19) latest is v6.2.5

  - symfony/finder (v5.4.19) latest is v6.2.5

  - symfony/process (v5.4.19) latest is v6.2.5

  - symfony/service-contracts (v1.1.2) latest is v3.2.0

  - symfony/string (v5.4.19) latest is v6.2.5
```

But this plugin is not maintained anymore and throws deprecations all over the place.

It would be best if this was part of the native outdated info IMO instead of creating a false sense of "being fully updated".

PHP: 8.2
Linux
Latest composer version

**Comment by dereuromark** [comment]
I see sth similar been done on https://github.com/composer/composer/pull/11113 for ext topic.
So a separate info (maybe also different block and color) for those could be an option, as well.

**Comment by stof** [comment]
There is a `--ignore-platform-reqs` option in `composer outdated` for that use case.

**Comment by dereuromark** [comment]
Outdated within platform reqs and outdated in general (where updates will be required in the future) are two different things.
I somehow thought this command as replacement for the plugin would handle also the latter.

If that is not the case and not the intend, we can close this as then.

**Comment by stof** [comment]
Symfony 6 being skipped by outdated is precisely because by default `composer outdated` takes platform requirements into account (and so exclude Symfony 6 from candidates when targetting PHP 7.4).
`composer outdated --ignore-platform-reqs` disable that filtering by target platform (and will then show Symfony packages as being outdated due to Symfony 6 being released).

So to me, this works as intended.

**Comment by dereuromark** [comment]
Sure, but even if you run it with that, it does not clarify the reason why it was skipped (or what is blocking it)

```
composer out --ignore-platform-req=php
```
results in
```
Direct dependencies required in composer.json:
friendsofcake/bootstrap-ui        3.1.2   4.0.1  Bootstrap front-end framework support for CakePHP

Transitive dependencies not required in composer.json:
doctrine/instantiator             1.5.0   2.0.0  A small, lightweight utility to instantiate objects in PHP without invoking their constructors
laminas/laminas-diactoros         2.17.0  2.24.0 PSR HTTP Message implementations
laminas/laminas-httphandlerrunner 2.2.0   2.5.0  Execute PSR-15 RequestHandlerInterface instances and emit responses they generate.
monolog/monolog                   2.8.0   3.2.0  Sends your logs to files, sockets, inboxes, databases and various web services
psr/cache                         1.0.1   3.0.0  Common interface for caching libraries
psr/log                           1.1.4   3.0.0  Common interface for logging libraries
psr/simple-cache                  1.0.1   3.0.0  Common interfaces for simple caching
symfony/config                    v5.4.19 v6.2.5 Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                   v5.4.19 v6.2.5 Eases the creation of beautiful and testable command line interfaces
symfony/deprecation-contracts     v2.5.2  v3.2.0 A generic function and convention to trigger deprecation notices
symfony/filesystem                v5.4.19 v6.2.5 Provides basic utilities for the filesystem
symfony/finder                    v5.4.19 v6.2.5 Finds files and directories via an intuitive fluent interface
symfony/process                   v5.4.19 v6.2.5 Executes commands in sub-processes
symfony/service-contracts         v1.1.2  v3.2.0 Generic abstractions related to writing services
symfony/string                    v5.4.19 v6.2.5 Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
```

Similar to the linked PR above regarding ext topic, this could also be something maybe to clarify here in the output.

E.g.

> (PHP 8.0+ in conflict with current 7.4 platform req)

**Comment by stof** [comment]
If you want to understand why a package version was not selected, that is what the `composer why-not` command is about, not the `composer outdated` one.
