### ISSUE TITLE
Package names should be clickable in composer why-not

### ISSUE THREAD

**Issue by stof** [composer/composer#11289]
When running `composer outdated`, package names are clickable in terminals supporting links.

It would be great if they could also be clickable in the output of `composer why-not` (and probably also `composer why` but I haven't checked the current state there), to easily go to the project page of a package that blocks an update for instance.

**Comment by agostinofiscale** [comment]
I thought this was a useful feature so here we go: https://github.com/composer/composer/pull/11308 :)
