### ISSUE TITLE
after install composer,  it doesn't work。program is : In CurlDownloader.php line 646: cURL error: 2 (CURLM_BAD_EASY_HANDLE): cURL message: An easy handle was not good/valid.

### ISSUE THREAD

**Issue by cjzyy** [composer/composer#11299]
it's the version:

![image](https://user-images.githubusercontent.com/23442467/216831771-ca4195dd-39c6-4514-94bf-c017b0407eef.png)

php version:
![image](https://user-images.githubusercontent.com/23442467/216832496-95fe63ad-5d8f-4241-9f1c-1726d6c3c937.png)

then i execute the command : composer self-update. it is show me  the problem。
![image](https://user-images.githubusercontent.com/23442467/216831878-bb1cd655-964e-4d7d-9c92-8ff07f116066.png)

**Comment by Seldaek** [comment]
I've never seen this error and have no idea what it means sorry. I'd suggest updating your PHP though as 8.0.2 is quite early in the 8.x range it might have a bug, and it's anyway quite old.
