### ISSUE TITLE
Vendor scripts do not run under same PHP executable

### ISSUE THREAD

**Issue by coreyworrell** [composer/composer#11293]
My `composer.json`:

```json
{
  "scripts": {
    "test": "php-cs-fixer --version"
  }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK git version 2.39.1
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.5.1
PHP version: 8.1.14
PHP binary path: /usr/bin/php8.1
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
cURL version: 7.81.0 libz 1.2.11 ssl OpenSSL/3.0.2
zip: extension not loaded, unzip present, 7-Zip not available
```

When I run this command: 

```
php7.4 ~/bin/composer test
```

I get the following output: 

```
Reading ./composer.json (/home/USERNAME/projects/PROJECT/composer.json)
Loading config file /home/USERNAME/.config/composer/config.json
Loading config file /home/USERNAME/.config/composer/auth.json
Loading config file ./composer.json (/home/USERNAME/projects/PROJECT/composer.json)
Checked CA file /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a file.
Checked directory /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a directory.
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/home/USERNAME/projects/PROJECT): 'git' 'branch' '-a' '--no-color' '--no-abbrev' '-v'
Failed to initialize global composer: Composer could not find the config file: /home/USERNAME/.config/composer/composer.json

Reading ./composer.lock (/home/USERNAME/projects/PROJECT/composer.lock)
Reading /home/USERNAME/projects/PROJECT/vendor/composer/installed.json
Running 2.5.1 (2022-12-22 15:33:54) with PHP 7.4.33 on Linux / 5.15.0-58-generic
> test: php-cs-fixer --version
Executing command (CWD): php-cs-fixer --version
PHP CS Fixer 3.14.3 Oliva by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.14
```

And I expected this to happen (verbose info removed):

```
> test: php-cs-fixer --version
Executing command (CWD): php-cs-fixer --version
PHP CS Fixer 3.14.3 Oliva by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 7.4.33
```

I have just assumed that vendor install bin scripts would run under the same runtime/executable that the main composer process runs under. Maybe I missed this in the docs, but it seems logical, and I'm just realizing that I must prefix all commands with `@php` now for them to run as I would expect.

```json
{
  "scripts": {
    "test": "@php php-cs-fixer --version"
  }
}
```

I am using `php-cs-fixer` as an example because it has the runtime in its output, but other scripts had similar results (`PHP_VERSION_ID`, etc).

**Comment by Seldaek** [comment]
Yes, we just execute binaries with the shell and the shell decides what they should be executing with, we don't pick the PHP process, unless if you prefix with @php then that tells Composer to explicitly reuse the same PHP process and execute directly bypassing the shell PATH resolution. IMO this is as expected and designed, although I can see this may be surprising at first, but fixing this would mean we have to open the binary and parse the shebang to see if it's a php script at all, not sure I like this.

**Comment by coreyworrell** [comment]
Yes, it does make sense that the scripts would run exactly as provided. I guess I've just never seen examples that prepend `@php` to scripts that call vendor bin files. And now that we're upgrading some applications from 7.4 to 8.1, I'm being specific about which PHP version is being used and this just caught me off guard. I kind of just assumed the script spawn process would inherit the parent PHP process or something. But I see now that all Composer does is update the `PATH` to include `vendor/bin`.
