### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by shyim** [composer/composer#11300]
Hey,

I would like to package more PHP applications for [Nix](https://nixos.org). Currently composer is annoying to execute in an [sandbox environment](https://nixos.wiki/wiki/Nix_package_manager#Sandboxing). In a Sandbox environment (while building a package) is no Internet present to build a package in a reproducible manner.

As we got an `download-mode` the only missing part from Composer is to have an flag, where it does not try to fetch any external file like the [offline mode from yarn](https://classic.yarnpkg.com/blog/2016/11/24/offline-mirror/).

The usage would be like:

- `composer install --download-only` before the packaging
- `composer install --offline` while packaging. As all files should be present locally in the cache, it should just work

**Comment by Seldaek** [comment]
Have you tried env var COMPOSER_DISABLE_NETWORK=1?
