### ISSUE TITLE
method_exists triggers a warning in ClassLoader.php for a string

### ISSUE THREAD

**Issue by istepaniuk** [composer/composer#11305]
My `composer.json`:

```json
{
    "name": "istepaniuk/bug",
    "description": "Class loader test",
    "type": "project",
    "autoload": {
        "psr-4": {
            "Istepaniuk\\Bug\\": "src/"
        }
    },
    "authors": [
        {
            "name": "istepaniuk"
        }
    ],
    "require": {}
}
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK git version 2.38.3
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.5.2
PHP version: 8.2.2
PHP binary path: /usr/local/bin/php
OpenSSL version: OpenSSL 3.0.7 1 Nov 2022
cURL version: 7.87.0 libz 1.2.13 ssl OpenSSL/3.0.7
zip: extension present, unzip present, 7-Zip present (7z)
```

When I run this command: 

```
php ./src/do.php
```

I get the following output: 

```

Warning: Uninitialized string offset 0 in /app/vendor/composer/ClassLoader.php on line 503
bool(false)
```

And I expected this to happen:
```
bool(false)
```

This is the entire contents of do.php:
```php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

$backslash = "\\";

var_dump(method_exists($backslash, 'test'));

```

`$class_name` is assumed not empty, but this demonstrates that it's not always the case.

IMO it doesn't make a lot of sense that the autoloader callback gets invoked with an empty string and this might be a bug in PHP itself, but I am not sure.

This happens since at least PHP 7.0 and composer 1.9.x

**Comment by Seldaek** [comment]
I'd say please report as a bug to the PHP project.

https://3v4l.org/RPQ95 shows that `""` does not trigger the autoloader, so I'm thinking `"\\"` probably shouldn't either.

I'd rather not add a check for this on our end as it's gonna be an unnecessary check in 99.9999999999% of method invocations, so let's spare some cycles :)
