### ISSUE TITLE
#StandWithUkraine Should be removed

### ISSUE THREAD

**Issue by WaqasBukhary** [composer/composer#11324]
Why are we enforced with your personal political views?? Have you ever worked in a diverse environment? 

Kindly chose an appropriate political forum to post your views so you get a fitting response. This is coding platform not a political debate platform.

Kindly explain which Ukraine do you stand with??? The pro Russian Ukraine or the other Ukraine?

The following would be more appropriate tags
WeStandWithIIOJK where even internet is blocked to suppress.
WeStandAgainstSwissBanks which is safe haven for corruption money all of the developing and poor countries 
We have used MuslimOil in our cars all over lives, which WeAreEagerToSteal but AllwaysFail

What an unprofessional attitude

**Comment by theofidry** [comment]
[Code is not apolitical](https://dev.to/awwsmm/code-is-political-5976), so that this is a coding platform will not shield you from political views, opinions or biases.

>Kindly explain which Ukraine do you stand with??? The pro Russian Ukraine or the other Ukraine?

The message and flag is pretty clear on that front, there really isn't any ambiguity.

Also this is OSS: if you're not happy with a maintainer's software you're free to use something else. For example you can join the https://github.com/open-composer/composer club.

**Comment by WaqasBukhary** [comment]
> [Code is not apolitical](https://dev.to/awwsmm/code-is-political-5976), so that this is a coding platform will not shield you from political views, opinions or biases.
> 
> > Kindly explain which Ukraine do you stand with??? The pro Russian Ukraine or the other Ukraine?
> 
> The message and flag is pretty clear on that front, there really isn't any ambiguity.
> 
> Also this is OSS: if you're not happy with a maintainer's software you're free to use something else. For example you can join the https://github.com/open-composer/composer club.

I don't see a flag in the message. I have never seen a Ukraine flag I just googled it. The message is not clear which side you are on. Do you mean the separatist are not Ukranian?

**Comment by servicepipe** [comment]
На столько же сильно западные политики насрали в уши своим гражданам что они насмотревшись телевизора побежали на свои сервисы вешать надписи типо стой с украиной. 

Фашизм процветает во всей красе. И весь мир поддерживает этот фашизм. Да здравствуйте 1941-1945

**Comment by servicepipe** [comment]
I completely agree with the author, if you publicly support fascism here, then I would not want to look at it.

**Comment by politsin** [comment]
```sh
git clone https://github.com/composer/composer.git --branch 2.5.4  ~/composer-build && \
    composer install  -o -d ~/composer-build && \
    wget https://raw.githubusercontent.com/politsin/snipets/master/patch/composer.patch -q -O ~/composer-build/composer.patch  && \
    cd ~/composer-build && patch -p1 < composer.patch && \
    php -d phar.readonly=0 bin/compile && \
    rm /usr/local/bin/composer && \
    php composer.phar install && \
    php composer.phar update && \
    mv ~/composer-build/composer.phar /usr/local/bin/composer && \
    rm -rf ~/composer-build  && \
    chmod +x /usr/local/bin/composer
```

**Comment by CaddyDz** [comment]
> ```shell
> git clone https://github.com/composer/composer.git --branch 2.5.4  ~/composer-build && \
>     composer install  -o -d ~/composer-build && \
>     wget https://raw.githubusercontent.com/politsin/snipets/master/patch/composer.patch -q -O ~/composer-build/composer.patch  && \
>     cd ~/composer-build && patch -p1 < composer.patch && \
>     php -d phar.readonly=0 bin/compile && \
>     rm /usr/local/bin/composer && \
>     php composer.phar install && \
>     php composer.phar update && \
>     mv ~/composer-build/composer.phar /usr/local/bin/composer && \
>     rm -rf ~/composer-build  && \
>     chmod +x /usr/local/bin/composer
> ```

Thanks a ton, macOS users: if you installed Composer via Homebrew
Change `/usr/local/bin/composer` by `/opt/homebrew/bin/composer`
So the command would be
```shell
git clone https://github.com/composer/composer.git --branch 2.5.4  ~/composer-build && \
    composer install  -o -d ~/composer-build && \
    wget https://raw.githubusercontent.com/politsin/snipets/master/patch/composer.patch -q -O ~/composer-build/composer.patch  && \
    cd ~/composer-build && patch -p1 < composer.patch && \
    php -d phar.readonly=0 bin/compile && \
    rm /opt/homebrew/bin/composer && \
    php composer.phar install && \
    php composer.phar update && \
    mv ~/composer-build/composer.phar /opt/homebrew/bin/composer && \
    rm -rf ~/composer-build  && \
    chmod +x /opt/homebrew/bin/composer
```
