### ISSUE TITLE
The DumpAutoload command loads dev plugins

### ISSUE THREAD

**Issue by theofidry** [composer/composer#11325]
Let's consider the following `composer.json`:

```json
{
  "require-dev": {
    "phpstan/extension-installer": "*"
  }
}
```

If you happen to remove the directory `vendor/phpstan/extension-installer`, the _all_ commands will no longer work. The problem being the plugin cannot be loaded (since it is missing its files). Your only choice left is to remove `vendor` for Composer to be able to work again.

IMO it's a weird edge case, because this can only be the result of a user or a software tempering with the `vendor` directory directly. But I still think it is not great that you can get into a state where even `composer diagnose` will just straight up fail.

<hr>

The above is I think the root of the issue, but what I was checking was originally a bit different. Indeed I was trying to run `composer dump-autoload --no-dev` where dev packages had been removed (manually, not via `composer install --no-dev`).

I expected that the `--no-dev` flag would result in dev packages to not be loaded at all, but as shown before, it looks at the very least that dev plugins are.

To give a bit of context as to why this happens, in [Box](https://github.com/box-project/box) a feature that is present since 3.0.0-alpha.0 (so ~5 years ago) is to exclude dev dependencies as well as some extra unnecessary files (e.g. GitHub workflows or test directories), which was done by checking the `composer.json` or `composer.lock`.

As a result, although no dev dependency is installed, the `installed.json` and `installed.php` are not touched and still contain references of the dev packages.

**Comment by Seldaek** [comment]
I can't actually reproduce this.. But the fix  in https://github.com/box-project/box/pull/879 seems like a good change to me if I understood correctly it's running `composer install --no-dev` which is cleaner for sure.

**Comment by theofidry** [comment]
Weird, I'll have another look at that reproducer.

**Comment by theofidry** [comment]
@Seldaek here's a reproducer:

```
composer require iter/nikic
composer require --dev phpstan/phpstan phpstan/extension-installer
rm -r vendor/phpstan
composer # will fail
```

**Comment by Seldaek** [comment]
Well all commands have to enable plugins as they might do stuff that is needed for that command to run. So IMO nothing we can do here.

**Comment by theofidry** [comment]
>Well all commands have to enable plugins as they might do stuff that is needed for that command to run

I guess it's not simple but can't this be done conditionally based on the dev/no-dev? I still find surprising that a plugin installed as a dev dependency would be loaded when passing `--no-dev`.

But might not be worth changing at this point... It does mean I need to alter the `installed.php` or other there to prevent Composer to try to load it though.

**Comment by Seldaek** [comment]
I don't think we should select plugins based on the `--no-dev` of the command, if something is installed it gets enabled always. It's much simpler and will avoid causing potential troubles.
