### ISSUE TITLE
Re-downloading a release leads to "invalid not-modified ETag" error

### ISSUE THREAD

**Issue by GuillaumeRossolini** [composer/composer#11339]
Hi,

This is not related to the use of Composer, but merely to its published URL.

When trying to rebuild a PHP image using Docker, we include the following lines in our `Dockerfile`:
```
ARG COMPOSER_VER="2.4.4"
ADD "https://getcomposer.org/download/${COMPOSER_VER}/composer.phar" /usr/local/bin/composer
```

This works fine but, when trying to rebuild the same image some time later, we occasionally get the following error:
```
ERROR: failed to solve: failed to load cache key: invalid not-modified ETag: "635a7c01-2ae371"
```

Of course, in this case the obvious fix (on my end) is to get the newer 2.5.4 version, leading to a new cache entry for the `ADD` Docker command and allowing my Dockerfile to continue.

But I think perhaps the underlying issue might be that the getcomposer.org server might not serve `ETag` reponse headers that are the same over time for each release, and the Docker cache is really long lived, leading to a mismatch after a while (or possibly after a new release)?

**Comment by Seldaek** [comment]
The archives don't change over time, but the ETag might? I don't know what it's based on exactly for nginx.. I could offer to remove the etags entirely tho if you think that helps?

**Comment by GuillaumeRossolini** [comment]
The current workaround on our side is either to re-host the archive somewhere, or add a timestamp to the URL.

Since I've seen other people mentioning this  behavior and it's a bit puzzling, I thought I'd open an issue and see if you could come up with a fix. I have no clue how removing the header might impact your bandwidth?

Maybe this is strictly about gitlab, and you could conditionally remove the header?
