### ISSUE TITLE
Installation failed, deleting ./composer.json.

### ISSUE THREAD

**Issue by oscarchen-code** [composer/composer#11337]
Installation failed, deleting ./composer.json.

  [RuntimeException]
  No composer.json present in the current directory (./composer.json), this may be the cause of the following exception.

  [LogicException]
  ComposerRepository: Undefined $data. Please report at https://github.com/composer/composer/issues/new.

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...

**Comment by stof** [comment]
Please provide the full info:

- showing which command you ran
- running the command in verbose mode to give more details for the error.
