### ISSUE TITLE
Adding a plugin to the allow-plugins section should be alphabetical if sort-packages is enabled

### ISSUE THREAD

**Issue by hostep** [composer/composer#11348]
Hi there

My `composer.json` contains:

```json
    "config": {
        "allow-plugins": {
            "a/a": true,
            "z/z": true
        },
        "sort-packages": true
    },
```

When I install package `b/b`and that package contains a composer plugin, and I confirm to composer to add it to the allow list, I get:

```json
    "config": {
        "allow-plugins": {
            "a/a": true,
            "z/z": true,
            "b/b": true
        },
        "sort-packages": true
    },
```

And I expected this to happen:

```json
    "config": {
        "allow-plugins": {
            "a/a": true,
            "b/b": true,
            "z/z": true
        },
        "sort-packages": true
    },
```

Now I always need to go manually into the `composer.json` file to sort them alphabetically, and it's becoming a bit tedious after having done this already 20/30 times in the last couple of months, would be nice if this could happen automatically.

Thank you very much! 🙂

**Comment by Seldaek** [comment]
Feel free to PR this, makes sense I guess but I doubt I'll have time for it myself anytime soon.

**Comment by hostep** [comment]
Thank you very much!
