### ISSUE TITLE
Tabs in `composer.lock` if `composer.json` indented using tabs

### ISSUE THREAD

**Issue by maximal** [composer/composer#11341]
I like the way NPM handles lock files indentation: if `package.json` uses tabs then `package-lock.json` also will be indented using tabs, if the former has spaces then the latter will have spaces.

Maybe it would be semantically correct to implement the similar behavior in Composer, so that `composer.lock` was indented the way `composer.json` is.

Also, this issue is linked to #3192

**Comment by Seldaek** [comment]
Yeah I guess we could do that, sounds reasonable although a little work for not much value IMO as the lock file should not really be opened/edited.

**Comment by maximal** [comment]
@Seldaek, at least users using tabs will have much smaller `composer.lock` :-)

I guess, I could do this, I only need to find where the JSON files generation is located.

**Comment by maximal** [comment]
I taught `JsonFile` to preserve indentation when writing files. See #11390.
Maybe this behavior will be enough. Can you check the pull request please?

So, it is sufficient to once reformat `composer.lock` using tabs and then Composer will be preserving tabs in it.

This is not what I originally wanted (in this issue specifically), but at least something to move on. I don’t know yet how to pass `composer.json` indentation to `Locker` instance.

**Comment by Seldaek** [comment]
Closing as IMO https://github.com/composer/composer/pull/11390 is good enough - if you care about this (and not many do I suppose as this is really a machine-readable file mostly) then change your lock file once to tabs by hand.
