### ISSUE TITLE
Ability to define what type of licenses are allowed to be added as dependencies

### ISSUE THREAD

**Issue by SteelzZ** [composer/composer#1136]
Would be nice if I could define global rules for dependencies. In this way I could manage that someone in a team wouldn't put a dependency on a package that requires license. In big project incident like this could cause problems. So if I could define that only X type of licenses are acceptable composer wouldn't allow for someone to install package that has improper license.

**Comment by valioDOTch** [comment]
+1
this would be a very useful feature to me

**Comment by valioDOTch** [comment]
BTW: 
As a "workaround" to get a statistic of licenses in an existing project, use this line
`awk '/license/{getline; print}' composer.lock | sort | uniq -c`

**Comment by stof** [comment]
@valioDOTch to see what is used, there is a much simpler way than searching in the lock file: ``composer licenses``.
This feature request is about a different feature: preventing the package to be selected during the dependency resolution

**Comment by lsmith77** [comment]
I guess one thing to consider is that licenses can of course also change. meaning that there could be a case where a newer or older license matches the license requirement.

**Comment by valioDOTch** [comment]
@stof Thanks you very much! I was not aware about that command.

However I was very well aware about the nature of this feature request ;-)
