### ISSUE TITLE
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255

### ISSUE THREAD

**Issue by ajaypecs** [composer/composer#11361]
When I am running php artisan dump-autoload or php artisan optimize in laravel it is display given error

thrown in G:\test1\live\live\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 879  
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255

in the logfile, it is not display anything

please provide me with support against it.

**Comment by Sharxn13** [comment]
I am currently facing the same issue. Many people online say to delete the vendor folder and run `composer update`. However when i tried this i keep getting back the same error message.

**Comment by Seldaek** [comment]
This is a problem with the artisan script, please report to Laravel.
