### ISSUE TITLE
[FR] Add a `--type` option to the `reinstall` command

### ISSUE THREAD

**Issue by brandonkelly** [composer/composer#11364]
It would be nice if it were possible for the `reinstall` command to filter the searched packages by package type, via a new `--type` option.

```sh
composer reinstall "*" --type craft-plugin
```

That way, `reinstall` could be used to get custom package installers to do whatever custom stuff they need to do across all of the packages relevant to them (in Craft CMS’s case, updating `craftcms/plugins.php`) without any extra overhead.

**Comment by Seldaek** [comment]
Feel free to PR. In the meantime maybe you can do `composer reinstall '*plugin*` hopefully they have a common suffix or something you can use? Worst case it reinstalls a bit more than needed..

**Comment by GromNaN** [comment]
If you can extract the list of package types used, for shell completion. That would be perfect.

**Comment by Seldaek** [comment]
Yeah that shouldn't be very hard but indeed a good addition. However this is a super fringe feature so if nobody sends a PR I doubt it'll get done.

**Comment by brandonkelly** [comment]
Thanks for adding this @Seldaek! ❤️
