### ISSUE TITLE
Values in error messages regarding Github are not properly replaced

### ISSUE THREAD

**Issue by php4fan** [composer/composer#11366]
I ran `composer update` a few times while working on a project. At some point I got this message:

> GitHub API limit **(0 calls/hr)** is exhausted, could not fetch https://api.github.com/repos/avgeeklucky/grafika/contents/composer.json?ref=xxxx. Create a GitHub OAuth token to go over the API rate limit. You can also wait until **?** for the rate limit to reset.

Note the "0 calls/hr" and the "?".
The number of calls/hr shouldn't be zero, and the "?" should be replaced with a date and time.

I actually reported this to the github cli tool assuming the messge was coming from it, but they said it's composer.

**Comment by Seldaek** [comment]
Should be fixed by https://github.com/composer/composer/commit/d3adecf58370cd5961db968c2b49f5f102b0d8de
