### ISSUE TITLE
Windows incompatível.

### ISSUE THREAD

**Issue by otavio-araujo** [composer/composer#11360]
When I try any composer commands, I got the message:

This version of C:\laragon\bin\composer\composer.exe is not compatible with the version of Windows you are running. Check your computer's system information and contact the software vendor.

Does anyone knows what to do?

**Comment by stof** [comment]
what is this `composer.exe` ? Composer is not distributed as an exe file, so it seems likely that your executable is related to a different project that might share the same name.

**Comment by otavio-araujo** [comment]
Thank for tour time! 
Ive Just fresh reinstalled Windows.

Now Its ok.

Thank you!
