### ISSUE TITLE
`composer install` error with Composer 2.5 + cache in CI-pipeline

### ISSUE THREAD

**Issue by tinogo** [composer/composer#11372]
My `composer.json`:

```json
{
  "name": "acp3/cms",
  "description": "ACP3 is a highly customizable and easy to use web content management system based on PHP5 and MySQL.",
  "type": "project",
  "license": "GPL-2.0-or-later",
  "authors": [
    {
      "name": "Tino Goratsch",
      "email": "mail@acp3-cms.net"
    }
  ],
  "support": {
    "email": "mail@acp3-cms.net",
    "issues": "https://gitlab.com/ACP3/cms/issues"
  },
  "minimum-stability": "dev",
  "prefer-stable": true,
  "require": {
    "php": "^8.1",
    "wikimedia/composer-merge-plugin": "^2.0"
  },
  "require-dev": {
    "friendsofphp/php-cs-fixer": "^3.13",
    "phpstan/phpstan": "^1.9.4",
    "phpstan/phpstan-phpunit": "^1.3.2",
    "phpstan/extension-installer": "^1.2",
    "rector/rector": "^0.15.12"
  },
  "replace": {
    "acp3/core": "*",
    "acp3/setup": "*",
    "acp3/tests": "*",
    "acp3/module-acp": "*",
    "acp3/module-articles": "*",
    "acp3/module-articles-menus": "*",
    "acp3/module-articles-search": "*",
    "acp3/module-articles-seo": "*",
    "acp3/module-articles-share": "*",
    "acp3/module-audit-log": "*",
    "acp3/module-captcha": "*",
    "acp3/module-categories": "*",
    "acp3/module-comments": "*",
    "acp3/module-contact": "*",
    "acp3/module-contact-seo": "*",
    "acp3/module-cookie-consent": "*",
    "acp3/module-emoticons": "*",
    "acp3/module-errors": "*",
    "acp3/module-feeds": "*",
    "acp3/module-filemanager": "*",
    "acp3/module-files": "*",
    "acp3/module-files-comments": "*",
    "acp3/module-files-feed": "*",
    "acp3/module-files-search": "*",
    "acp3/module-files-seo": "*",
    "acp3/module-files-share": "*",
    "acp3/module-gallery": "*",
    "acp3/module-gallery-comments": "*",
    "acp3/module-gallery-seo": "*",
    "acp3/module-gallery-share": "*",
    "acp3/module-guestbook": "*",
    "acp3/module-guestbook-newsletter": "*",
    "acp3/module-installer": "*",
    "acp3/module-menus": "*",
    "acp3/module-news": "*",
    "acp3/module-newsletter": "*",
    "acp3/module-news-comments": "*",
    "acp3/module-news-feed": "*",
    "acp3/module-news-search": "*",
    "acp3/module-news-seo": "*",
    "acp3/module-news-share": "*",
    "acp3/module-permissions": "*",
    "acp3/module-polls": "*",
    "acp3/module-search": "*",
    "acp3/module-seo": "*",
    "acp3/module-social-sharing": "*",
    "acp3/module-system": "*",
    "acp3/module-users": "*",
    "acp3/module-wysiwyg-ckeditor": "*",
    "acp3/module-wysiwyg-tinymce": "*",
    "acp3/theme-default": "*",
    "acp3/theme-installer": "*"
  },
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/tinogo/RichFilemanager-PHP"
    },
    {
      "type": "vcs",
      "url": "https://github.com/tinogo/shariff-backend-php"
    }
  ],
  "scripts": {
    "test": "./vendor/bin/phpunit -c ./tests/phpunit.dist.xml",
    "test-windows": ".\\vendor\\bin\\phpunit.bat -c .\\tests\\phpunit.dist.xml",
    "test-with-coverage": "phpdbg -qrr -d memory_limit=-1 ./vendor/bin/phpunit -c ./tests/phpunit.dist.xml --coverage-text --colors=never --log-junit junit-report.xml",
    "lint": "./vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php --dry-run --show-progress=dots -v",
    "lint-windows": ".\\vendor\\bin\\php-cs-fixer.bat fix --config=.php-cs-fixer.dist.php --dry-run --show-progress=dots -v",
    "php-cs-fixer": "./vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php --show-progress=dots -v",
    "php-cs-fixer-windows": ".\\vendor\\bin\\php-cs-fixer.bat fix --config=.php-cs-fixer.dist.php --show-progress=dots -v",
    "phpstan": "php -d memory_limit=-1 ./vendor/bin/phpstan analyse --xdebug",
    "phpstan-windows": ".\\vendor\\bin\\phpstan.bat analyse --xdebug",
    "rector": "php -d memory_limit=-1 ./vendor/bin/rector process"
  },
  "extra": {
    "merge-plugin": {
      "include": [
        "composer.local.json"
      ],
      "require": [
        "./ACP3/Core/composer.json",
        "./ACP3/Modules/*/*/composer.json",
        "./designs/*/composer.json",
        "./installation/composer.json",
        "./tests/composer.json"
      ],
      "recurse": true,
      "replace": false,
      "ignore-duplicates": false,
      "merge-dev": true,
      "merge-extra": false,
      "merge-extra-deep": false,
      "merge-scripts": false
    }
  },
  "config": {
    "allow-plugins": {
      "composer/package-versions-deprecated": true,
      "phpstan/extension-installer": true,
      "acp3/composer-installer": true,
      "wikimedia/composer-merge-plugin": true,
      "php-http/discovery": true
    }
  }
}
```

When I run this command: 

```
composer install -n --prefer-dist --ignore-platform-reqs
```

I get the following output: 

```
- Required package "acp3/core" is not present in the lock file.
- Required package "acp3/module-permissions" is not present in the lock file.
- [..]
```

See also: https://gitlab.com/ACP3/cms/-/jobs/3918038851#L32. This only happens when the CI-pipeline has a "warm"-cache for Composer. When there is no cache yet, the mentioned `composer install`-command works (https://gitlab.com/ACP3/cms/-/jobs/3918034957). Furthermore, this error only occurs with Composer 2.5.x, Composer 2.4.x works flawlessly in both cases.

And I expected this to happen:

The `composer install`-command works with warm cache and without cache in the CI-pipeline (as it did before with Composer 2.4).

**Comment by stof** [comment]
what are you caching in your composer cache ?

**Comment by tinogo** [comment]
Hi @stof,

I'm caching the `$COMPOSER_HOME`-dir and the `vendor`-dir (https://gitlab.com/ACP3/cms/-/blob/6.x/.gitlab/ci/prepare.gitlab-ci.yml).

**Comment by stof** [comment]
A quick investigation seems to suggest that the check added in https://github.com/composer/composer/pull/11195 is the one reporting the error. Maybe it has a bug for required packages that are replaced by the root package (but I don't see why this would happen only for a warm cache)

**Comment by Seldaek** [comment]
Do you have anything in `"composer.local.json"`? Because that gets included, and so once vendor dir is present (warm cache) the plugin will include that file. On initial install it wouldn't include it yet until the plugin is installed so perhaps that accounts for the difference?

**Comment by tinogo** [comment]
Hi @Seldaek,
sorry for the late reply.

No, I have nothing in the `composer.local.json` (i.e. it doesn't even exist).

**Comment by Seldaek** [comment]
OK.. then I cannot reproduce this.. not sure what to say 🤷🏻‍♂️

**Comment by tinogo** [comment]
Okay, I just did some more experiments and it seems, that not Composer itself seems to be problem, but the combination of Composer 2.5.x and the `wikimedia/composer-merge-plugin`.

After uninstalling the `wikimedia/composer-merge-plugin` (https://gitlab.com/ACP3/cms/-/jobs/3959655167), the `composer install`-command WITH the warm cache works (https://gitlab.com/ACP3/cms/-/jobs/3959655854).

So, I'll create a bug report at the composer-plugin's end, I guess?! 😄

**Comment by Seldaek** [comment]
I'll try to take a look on my end next week if I can repro with the plugin active, then it might be fixable in Composer, but anyway let's ping @reedy @bd808 who maintain the plugin maybe they have a clue in the meantime.

**Comment by Seldaek** [comment]
> Do you have anything in `"composer.local.json"`? Because that gets included, and so once vendor dir is present (warm cache) the plugin will include that file. On initial install it wouldn't include it yet until the plugin is installed so perhaps that accounts for the difference?

OK so I tried again with the plugin enabled and it fails for me with:

```
  merge-plugin: No files matched required './ACP3/Core/composer.json'
```

So my question would be what do you have in all these files:

      "require": [
        "./ACP3/Core/composer.json",
        "./ACP3/Modules/*/*/composer.json",
        "./designs/*/composer.json",
        "./installation/composer.json",
        "./tests/composer.json"
      ],

**Comment by tinogo** [comment]
Hi @Seldaek,
you can find all the files in my repository: https://gitlab.com/ACP3/cms/-/tree/feature/test-composer-2.5 (you should eben be able to check if out). :)

But for instance here are the requested files:
* https://gitlab.com/ACP3/cms/-/blob/feature/test-composer-2.5/designs/acp3/composer.json
* https://gitlab.com/ACP3/cms/-/blob/test-composer-2.5/installation/composer.json
* https://gitlab.com/ACP3/cms/-/blob/test-composer-2.5/tests/composer.json
* https://gitlab.com/ACP3/cms/-/blob/test-composer-2.5/ACP3/Core/composer.json
* https://gitlab.com/ACP3/cms/-/blob/test-composer-2.5/ACP3/Modules/ACP3/Acp/composer.json (and many more for the other modules)

**Comment by Seldaek** [comment]
@tinogo I cannot reproduce still.. Do you still experience this with the latest Composer 2.5? As it fixed a bug in a related area maybe it helped for you too..

**Comment by tinogo** [comment]
@Seldaek Thank you for getting back on this topic. 
I'll give it another try in the couple of days and will give you the feedback whether it works or not. 🙂

**Comment by tinogo** [comment]
Hi @Seldaek,

sorry for the late reply. I've just tested it again and now it seems to work flawlessly even with Composer 2.5.

So - I'll close the issue. :)

**Comment by Seldaek** [comment]
Ok great :)
