### ISSUE TITLE
[Dependencies] Cannot update google-ads pypi package

### ISSUE THREAD

**Issue by isisplum12** [composer/composer#11377]
I'm trying to update the version of the pypi package google-ads on Google Cloud Composer.

I need to update google-ads to version 19.0.0, which is required to update the version of Google ads API to v12. When I try to set the version to 19.0.0, version problems start to appear with other libraries, mainly the mysql-connector-python, which is native from composer.

Here is some information about the environment that I'm using. Composer version 2.1.7 | Airflow version 2.4.3

I already tried to change the versions of the conflicting libraries, but mysql-connector-python requires an old version of protobuf and google-ads needs a new one, I stay trapped between those two.

Another attempt was deleting the library mysql-connector-python, which the following cli on cloud shell: gcloud --project=my-project-name composer environments update teste --location us-central1 --remove-pypi-packages mysql-connector-python

But I got the following error:

(gcloud.composer.environments.update) INVALID_ARGUMENT: No change in configuration. Must specify a change to configuration.software_configuration.pypi_dependencies.mysql-connector-python

**Comment by Seldaek** [comment]
This project is the PHP package manager Composer, Google Cloud Composer is .. somewhere else, I don't know if they have an issue tracker sorry.
