### ISSUE TITLE
Writing a dependency plugin for the WordPress ecosystem

### ISSUE THREAD

**Issue by szepeviktor** [composer/composer#11379]
Hello!
I'm writing a plugin for WordPress plugins that reads dependency information from extracted files. (readme.txt)
What object should I use to get the target directory after Composer extracts the package?
(I know it is too late for version conflicts after extraction.)

Thank you!

**Comment by Seldaek** [comment]
Sorry but I have no idea what you are asking here.

**Comment by szepeviktor** [comment]
When you install packages from wpackagist you can install a package that depends on a newer WordPress core than your current one.
I'm trying to prevent that.

**Comment by Seldaek** [comment]
Then that probably would be better in the wpackagist package metadata no? If it included the required WP core version?

But the project would then need to have a `"provide": {"wordpress/core":"..."}` to make packages installable, which I guess would break wpackagist for all existing users..

Anyway I don't know how others have solved this, isn't it a solved problem if using https://roots.io/bedrock/ ? 

I still don't know how I can help you sorry :)

**Comment by szepeviktor** [comment]
The problem is you are thinking about a normal solution 🙃 

Bedrock also uses wpackagist and can install updates requiring "too new" WordPress core.

I'm trying to use Composer's pre/post install event.
