### ISSUE TITLE
Website manual installation incorrect

### ISSUE THREAD

**Issue by theking2** [composer/composer#11395]
The [instructions for manual installation on the website](https://getcomposer.org/download/) are incomplete/incorrect the first line:
```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
```

results in this error message:
```
Warning: copy(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP? in Command line code on line 1

Warning: copy(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP? in Command line code on line 1

Warning: copy(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP? in Command line code on line 1

Warning: copy(https://getcomposer.org/installer): Failed to open stream: No such file or directory in Command line code on line 1
```

**Comment by marlonanjos** [comment]
```Unable to find the wrapper "https" - did you forget to enable it when you configured PHP```

This is a PHP related error. [More info](https://cweiske.de/tagebuch/php-error-https-wrapper.htm).

**Comment by marlonanjos** [comment]
```Unable to find the wrapper "https" - did you forget to enable it when you configured PHP```

This is a PHP related error. [More info](https://cweiske.de/tagebuch/php-error-https-wrapper.htm).

**Comment by stof** [comment]
If you installed PHP without support for openssl (and so without support for https), composer won't be usable anyway, even if you download the installer without using PHP.
