### ISSUE TITLE
Composer u for Drupal 9.5.5 failing

### ISSUE THREAD

**Issue by inwebsol** [composer/composer#11391]
My `composer.json`:

{
    "name": "drupal/recommended-project",
    "description": "Project template for Drupal 9 projects with a relocated document root",
    "type": "project",
    "license": "GPL-2.0-or-later",
    "homepage": "https://www.drupal.org/project/drupal",
    "support": {
        "docs": "https://www.drupal.org/docs/user_guide/en/index.html",
        "chat": "https://www.drupal.org/node/314178"
    },
		"repositories": {
    "drupal": {
			 "type": "composer",
            "url": "https://packages.drupal.org/8"
        		},
	 "packagist": {
            "type": "composer",
            "url": "https://packagist.org"
    },    
     "assets": {
             "type": "composer",
            "url": "https://asset-packagist.org"
        },
	  "github": {
			 "type": "vcs",
	    "url": "https://github.com/ossobuffo/drupal-console-extend-plugin.git"
        },
		"Google": {
            "type": "package",
            "package": {
                "name": "google/charts",
                "version": "45",
                "type": "drupal-library",
                "extra": {
                    "installer-name": "google_charts"
                },
                "dist": {
                    "url": "https://www.gstatic.com/charts/loader.js",
                    "type": "file"
                }
                
            }
        }
	},
    "require": {
        "bower-asset/algolia-places": "^1.19",
        "bower-asset/colorbox": "^1.6",
        "bower-asset/dompdf": "^1.0",
        "bower-asset/elevatezoom": "^2.2",
        "bower-asset/fonticonpicker": "^2.0",
        "bower-asset/jquery-colorpicker": "^1.0",
        "bower-asset/jquery-simple-color": "^1.2",
        "bower-asset/jquery-ui-slider-pips": "^1.11",
        "bower-asset/jquery-zoom": "^1.7",
        "bower-asset/jquery.cycle": "dev-master",
        "bower-asset/jquery.hoverintent": "dev-master",
        "bower-asset/json2": "dev-master",
        "bower-asset/leaflet": "^1.6",
        "bower-asset/smartmenus": "^1.1",
        "bower-asset/spectrum": "^1.8",
        "bower-asset/stacktable.js": "^1.0",
        "composer/installers": "^1.9",
        "cweagans/composer-patches": "^1.6.5",
        "dompdf/dompdf": "^2.0",
        "drupal/addtoany": "^1.14",
        "drupal/addtocal": "^2.0@beta",
        "drupal/addtocalendar": "^3.2",
        "drupal/admin_toolbar": "^3.0",
        "drupal/admin_toolbar_tools": "^2.4",
        "drupal/advanced_text_formatter": "^2.0",
        "drupal/advban": "^1.3",
        "drupal/allowed_formats": "^1.3",
        "drupal/ape": "^1.5",
        "drupal/autoban": "^1.7",
        "drupal/autosave_form": "^1.2",
        "drupal/backup_migrate": "^5.0",
        "drupal/bee": "^1.2",
        "drupal/better_search": "^1.4",
        "drupal/better_social_sharing_buttons": "3.x-dev@dev",
        "drupal/blazy": "^2.1",
        "drupal/block_class": "^1.3",
        "drupal/block_classes": "^1.0",
        "drupal/block_scheduler": "^2.0",
        "drupal/bootstrap": "^3.23",
        "drupal/bootstrap_layouts": "^5.2",
        "drupal/bootstrap_library": "^1.14",
        "drupal/business_rules": "^2.0@beta",
        "drupal/captcha": "^1.1",
        "drupal/charts": "^5.0@alpha",
        "drupal/chosen": "^3.0",
        "drupal/coder": "^8.3",
        "drupal/color": "^1.0",
        "drupal/color_field": "^2.4",
        "drupal/colorbox": "^1.6",
        "drupal/colorbox_inline": "^1.2",
        "drupal/colorbutton": "^1.2",
        "drupal/comment_approver": "^2.0@alpha",
        "drupal/commerce": "^2.27",
        "drupal/commerce_add_to_cart_link": "^2.0",
        "drupal/commerce_add_to_wishlist_link": "^2.0",
        "drupal/commerce_ajax_atc": "^1.0@alpha",
        "drupal/commerce_ajax_cart_message": "^1.1",
        "drupal/commerce_bulk": "^1.0@beta",
        "drupal/commerce_cart": "^2.13",
        "drupal/commerce_cart_advanced": "1.x-dev@dev",
        "drupal/commerce_cart_api": "^1.5",
        "drupal/commerce_cart_flyout": "1.x-dev@dev",
        "drupal/commerce_cart_popup": "^1.0",
        "drupal/commerce_checkout": "^2.13",
        "drupal/commerce_combine_carts": "1.x-dev@dev",
        "drupal/commerce_fee": "1.0.x-dev@dev",
        "drupal/commerce_generate": "^1.0@beta",
        "drupal/commerce_giftcard": "1.0.x-dev@dev",
        "drupal/commerce_ingenico": "^1.0@beta",
        "drupal/commerce_invoice": "^2.0@beta",
        "drupal/commerce_invoice_payment": "1.0.x-dev@dev",
        "drupal/commerce_log": "^2.21",
        "drupal/commerce_mollie": "^1.6",
        "drupal/commerce_order": "^2.13",
        "drupal/commerce_order_autovalidate": "^2.0",
        "drupal/commerce_payment": "^2.13",
        "drupal/commerce_payment_example": "^2.13",
        "drupal/commerce_paypal": "^1.0@RC",
        "drupal/commerce_price": "^2.21",
        "drupal/commerce_product": "^2.13",
        "drupal/commerce_product_limits": "^1.0",
        "drupal/commerce_product_tax": "^1.0@RC",
        "drupal/commerce_promotion": "^2.13",
        "drupal/commerce_reports": "1.x-dev@dev",
        "drupal/commerce_shipping": "^2.0@RC",
        "drupal/commerce_simple_stock": "1.x-dev",
        "drupal/commerce_stock": "^1.0@alpha",
        "drupal/commerce_stock_enforcement": "^1.0@alpha",
        "drupal/commerce_stock_field": "^1.0@alpha",
        "drupal/commerce_store": "^2.13",
        "drupal/commerce_tax": "^2.13",
        "drupal/commerce_variation_add_to_cart": "^1.5",
        "drupal/commerce_variation_cart_form": "^1.2",
        "drupal/commerce_wishlist": "3.x-dev@dev",
        "drupal/commerce_xattributes": "^1.0@beta",
        "drupal/condition_plugins_commerce": "^1.0@beta",
        "drupal/conditional_fields": "1.x-dev",
        "drupal/config_perms": "^2.0",
        "drupal/console": "^1.0.2",
        "drupal/console-extend-plugin": "dev-master as 0.9.4",
        "drupal/contact_storage": "^1.2",
        "drupal/context": "^4.0@beta",
        "drupal/cookieconsent": "^1.6",
        "drupal/cool_message": "^3.0",
        "drupal/core-composer-scaffold": "^9",
        "drupal/core-project-message": "^9",
        "drupal/core-recommended": "^9",
        "drupal/css_editor": "^1.2",
        "drupal/ctools": "^3.4",
        "drupal/d8w3css": "^1.15",
        "drupal/devel": "^4.1",
        "drupal/devel_entity_updates": "^3.0",
        "drupal/devel_generate": "^4.0",
        "drupal/direct_checkout_by_url": "^1.1",
        "drupal/disable_messages": "^2.1@alpha",
        "drupal/download_all_files": "^2.0",
        "drupal/dropdown_language": "^2.6",
        "drupal/dynamic_entity_reference": "^1.12",
        "drupal/easy_install": "^10.4",
        "drupal/editor_advanced_link": "^1.8",
        "drupal/elevate_image_zoom": "9.1.x-dev",
        "drupal/embed": "^1.5",
        "drupal/endroid_qr_code": "^3.0",
        "drupal/entity_clone": "^2.0@beta",
        "drupal/entity_embed": "^1.2",
        "drupal/entity_print": "^2.9",
        "drupal/entity_type_clone": "^2.2",
        "drupal/entity_update": "^3.0@RC",
        "drupal/eu_cookie_compliance": "^1.14",
        "drupal/extlink": "^1.6",
        "drupal/facets": "^2.0",
        "drupal/field_formatter_class": "^1.5",
        "drupal/field_permissions": "^1.1",
        "drupal/fillpdf": "^5.0@alpha",
        "drupal/filter_perms": "^1.0@alpha",
        "drupal/fitvids": "^1.1",
        "drupal/fivestar": "^1.0@alpha",
        "drupal/flag": "^4.0@beta",
        "drupal/fontawesome": "^2.19",
        "drupal/fpa": "^3.0",
        "drupal/gdpr_compliance": "^1.18",
        "drupal/geocoder": "^3.15",
        "drupal/geolocation": "^3.7",
        "drupal/geotimezone": "^3.0",
        "drupal/hal-hal": "^1.0",
        "drupal/imageapi_optimize": "^4.0",
        "drupal/imce": "^2.4",
        "drupal/inline_entity_form": "^1.0@RC",
        "drupal/ip2country": "^1.10",
        "drupal/jquery_colorpicker": "^3.0",
        "drupal/jquery_ui": "^1.4",
        "drupal/layout_builder_at": "^2.12",
        "drupal/layout_builder_modal": "^1.1",
        "drupal/layout_builder_styles": "^1.0@alpha",
        "drupal/layout_library": "^1.0@beta",
        "drupal/leaflet": "^2.2",
        "drupal/leaflet_more_maps": "^2.1",
        "drupal/legal": "^2.0",
        "drupal/linkit": "^6.0@beta",
        "drupal/media_entity_browser": "^2.0@alpha",
        "drupal/menu_item_role_access": "^2.0",
        "drupal/module_filter": "^3.1",
        "drupal/module_missing_message_fixer": "^2.0",
        "drupal/mollie": "^2.1",
        "drupal/node_layout_builder": "^3.0",
        "drupal/page_manager": "^4.0@beta",
        "drupal/panels": "^4.6",
        "drupal/pathauto": "^1.8",
        "drupal/pdf": "^1.1",
        "drupal/permissions_by_term": "^3.1",
        "drupal/permissions_filter": "^1.2",
        "drupal/pfm": "^2.0",
        "drupal/photos": "^6.0",
        "drupal/php": "^1.1",
        "drupal/plupload": "^2.0@beta",
        "drupal/profile": "1.x-dev",
        "drupal/qrfield": "^1.0@alpha",
        "drupal/quick_node_clone": "^1.12",
        "drupal/quicktabs": "dev-3.x",
        "drupal/readonly_field_widget": "^1.4",
        "drupal/recaptcha": "^3.0",
        "drupal/recreate_block_content": "^2.0",
        "drupal/redirect": "^1.6",
        "drupal/redis": "^1.5",
        "drupal/reg_confirm_email": "^1.2",
        "drupal/roleassign": "^1.0@beta",
        "drupal/rules": "^3.0@alpha",
        "drupal/scheduler": "^2.0@RC",
        "drupal/search_api": "^1.18",
        "drupal/search_api_autocomplete": "^1.4",
        "drupal/serial": "^1.0@alpha",
        "drupal/simple_gmap": "^3.0",
        "drupal/slick": "^2.2",
        "drupal/smart_date": "^3.1",
        "drupal/smart_ip": "^4.0",
        "drupal/sshop": "^1.12",
        "drupal/status_messages": "^4.2",
        "drupal/svg_image": "^1.16",
        "drupal/swiftmailer": "^2.0@beta",
        "drupal/symfony_mailer": "^1.0@alpha",
        "drupal/taxonomy_menu": "^3.4",
        "drupal/telephone_validation": "^2.3",
        "drupal/term_csv_export_import": "^3.0@alpha",
        "drupal/tmgmt": "^1.12",
        "drupal/tmgmt_deepl": "^2.1",
        "drupal/token": "^1.7",
        "drupal/token_filter": "^1.3",
        "drupal/tvi": "^1.0@RC",
        "drupal/typed_data": "^1.0@beta",
        "drupal/user_csv_import": "^2.0",
        "drupal/views_autosubmit": "^1.4",
        "drupal/views_bootstrap": "^4.3",
        "drupal/views_bulk_edit": "2.x-dev@dev",
        "drupal/views_bulk_operations": "^4.0",
        "drupal/views_data_export": "^1.0",
        "drupal/views_slideshow": "^4.8",
        "drupal/votingapi": "^3.0@beta",
        "drupal/webform": "^6.0",
        "drupal/wkhtmltopdf": "^1.3",
        "drupal/x_frame_options": "^1.2",
        "drupal/xmlrpc": "^1.0@beta",
        "drush/drush": "^10.6",
        "endroid/qr-code-bundle": "^3.0",
        "enshrined/svg-sanitize": "^0.15.4",
        "geocoder-php/google-maps-provider": "^4.6",
        "geocoder-php/maxmind-provider": "^4.3",
        "geoip2/geoip2": "^2.11",
        "google/charts": "45",
        "kint-php/kint": "^3.3",
        "kint-php/kint-js": "^2.0",
        "kint-php/kint-twig": "^3.0",
        "mikehaertl/phpwkhtmltopdf": "~2.1",
        "npm-asset/bootstrap": "^4.3",
        "npm-asset/chosen-js": "^1.8",
        "npm-asset/color-button": "^1.1",
        "npm-asset/geolite2": "^3.4",
        "npm-asset/toastr": "^2.1",
        "npm-asset/wkhtmltopdf": "^0.3.4",
        "onlyextart/colorbutton": "dev-master",
        "onlyextart/panelbutton": "dev-master",
        "oomphinc/composer-installers-extender": "^2.0",
        "predis/predis": "^1.1",
        "psr/container": "^1.0",
        "psr/http-factory-implementation": "*",
        "tecnickcom/tcpdf": "~6",
        "true/punycode": "^2.1",
        "vlucas/phpdotenv": "^4.0",
        "webflo/drupal-finder": "^1.0.0",
        "webmozart/path-util": "^2.3",
        "willdurand/geocoder": "^4.4",
        "zaporylie/composer-drupal-optimizations": "^1.2"
    },
    "conflict": {
        "drupal/drupal": "*"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "sort-packages": true,
        "allow-plugins": {
            "composer/installers": true,
            "dealerdirect/phpcodesniffer-composer-installer": true,
            "endroid/installer": true,
            "php-http/discovery": true,
            "drupal/console-extend-plugin": true,
            "cweagans/composer-patches": true,
            "drupal/core-composer-scaffold": true,
            "drupal/core-project-message": true,
            "oomphinc/composer-installers-extender": true,
            "zaporylie/composer-drupal-optimizations": true
        }
    },
    "extra": {
        "drupal-scaffold": {
            "locations": {
                "web-root": "web/"
            }
        },
        "installer-paths": {
            "web/core": [
                "type:drupal-core"
            ],
            "web/libraries/{$name}": [
                "type:drupal-library"
            ],
            "web/modules/contrib/{$name}": [
                "type:drupal-module"
            ],
            "web/profiles/contrib/{$name}": [
                "type:drupal-profile"
            ],
            "web/themes/contrib/{$name}": [
                "type:drupal-theme"
            ],
            "drush/Commands/contrib/{$name}": [
                "type:drupal-drush"
            ],
            "web/modules/custom/{$name}": [
                "type:drupal-custom-module"
            ],
            "web/themes/custom/{$name}": [
                "type:drupal-custom-theme"
            ]
        },
        "drupal-core-project-message": {
            "include-keys": [
                "homepage",
                "support"
            ],
            "post-create-project-cmd-message": [
                "<bg=blue;fg=white>                                                         </>",
                "<bg=blue;fg=white>  Congratulations, you’ve installed the Drupal codebase  </>",
                "<bg=blue;fg=white>  from the drupal/recommended-project template!          </>",
                "<bg=blue;fg=white>                                                         </>",
                "",
                "<bg=yellow;fg=black>Next steps</>:",
                "  * Install the site: https://www.drupal.org/docs/8/install",
                "  * Read the user guide: https://www.drupal.org/docs/user_guide/en/index.html",
                "  * Get support: https://www.drupal.org/support",
                "  * Get involved with the Drupal community:",
                "      https://www.drupal.org/getting-involved",
                "  * Remove the plugin that prints this message:",
                "      composer remove drupal/core-project-message"
            ]
        }
    }
}

Output of `composer diagnose`:

```
...replace me...
```

When I run this command: 

```
composer update -vw
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? y
Warning: You should avoid overwriting already defined auth settings for github.com.
zaporylie/composer-drupal-optimizations is disabled for Composer 2
> command: Drupal\Composer\Plugin\Scaffold\Plugin->onCommand
> pre-update-cmd: cweagans\Composer\Patches->checkPatches
Loading composer repositories with package information
Your GitHub credentials are required to fetch private repository metadata (https://github.com/ossobuffo/drupal-console-extend-plugin.git)
When working with _public_ GitHub repositories only, head to https://github.com/settings/tokens/new?scopes=&description=Composer+on+ubuntu.ingiardino.net+2023-03-22+1612 to retrieve a token.
This token will have read-only permission for public information only.
When you need to access _private_ GitHub repositories as well, go to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+ubuntu.ingiardino.net+2023-03-22+1612
Note that such tokens have broad read/write permissions on your behalf, even if not needed by Composer.
Tokens will be stored in plain text in "/data/vhosts/wwwroot/html/java-kitchen-d9/auth.json OR /root/.composer/auth.json" for future use by Composer.
For additional information, check https://getcomposer.org/doc/articles/authentication-for-private-packages.md#github-oauth
A local auth config source was found, do you want to store the token there?
Token (hidden): 
Token stored successfully.

In CurlDownloader.php line 623:
                                                                                                                         
  [Composer\Downloader\TransportException (404)]                                                                         
  The "https://api.github.com/repos/ossobuffo/drupal-console-extend-plugin" file could not be downloaded (HTTP/2 404 ):  
  {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#get-a-repository"}            
                                                                                                                         

Exception trace:
  at phar:///usr/local/bin/composer/src/Composer/Util/Http/CurlDownloader.php:623
 Composer\Util\Http\CurlDownloader->failResponse() at phar:///usr/local/bin/composer/src/Composer/Util/Http/CurlDownloader.php:435
 Composer\Util\Http\CurlDownloader->tick() at phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php:386
 Composer\Util\HttpDownloader->countActiveJobs() at phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php:357
 Composer\Util\HttpDownloader->wait() at phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php:111
 Composer\Util\HttpDownloader->get() at phar:///usr/local/bin/composer/src/Composer/Repository/Vcs/VcsDriver.php:170
 Composer\Repository\Vcs\VcsDriver->getContents() at phar:///usr/local/bin/composer/src/Composer/Repository/Vcs/GitHubDriver.php:483
 Composer\Repository\Vcs\GitHubDriver->getContents() at phar:///usr/local/bin/composer/src/Composer/Repository/Vcs/GitHubDriver.php:540
 Composer\Repository\Vcs\GitHubDriver->fetchRootIdentifier() at phar:///usr/local/bin/composer/src/Composer/Repository/Vcs/GitHubDriver.php:83
 Composer\Repository\Vcs\GitHubDriver->initialize() at phar:///usr/local/bin/composer/src/Composer/Repository/VcsRepository.php:143
 Composer\Repository\VcsRepository->getDriver() at phar:///usr/local/bin/composer/src/Composer/Repository/VcsRepository.php:189
 Composer\Repository\VcsRepository->initialize() at phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:308
 Composer\Repository\ArrayRepository->getPackages() at phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:62
 Composer\Repository\ArrayRepository->loadPackages() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/PoolBuilder.php:385
 Composer\DependencyResolver\PoolBuilder->loadPackagesMarkedForLoading() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/PoolBuilder.php:239
 Composer\DependencyResolver\PoolBuilder->buildPool() at phar:///usr/local/bin/composer/src/Composer/Repository/RepositorySet.php:319
 Composer\Repository\RepositorySet->createPool() at phar:///usr/local/bin/composer/src/Composer/Installer.php:468
 Composer\Installer->doUpdate() at phar:///usr/local/bin/composer/src/Composer/Installer.php:287
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:247
 Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:377
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:141
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:88
 require() at /usr/local/bin/composer:29
      
                                                                                                                        

I get the following output: <!-- FULL OUTPUT please, not just what you think is relevant -->

```
composer update -vw
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? y
Warning: You should avoid overwriting already defined auth settings for github.com.
zaporylie/composer-drupal-optimizations is disabled for Composer 2
> command: Drupal\Composer\Plugin\Scaffold\Plugin->onCommand
> pre-update-cmd: cweagans\Composer\Patches->checkPatches
Loading composer repositories with package information
Your GitHub credentials are required to fetch private repository metadata (https://github.com/ossobuffo/drupal-console-extend-plugin.git)
When working with _public_ GitHub repositories only, head to https://github.com/settings/tokens/new?scopes=&description=Composer+on+ubuntu.ingiardino.net+2023-03-22+1612 to retrieve a token.
This token will have read-only permission for public information only.
When you need to access _private_ GitHub repositories as well, go to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+ubuntu.ingiardino.net+2023-03-22+1612
Note that such tokens have broad read/write permissions on your behalf, even if not needed by Composer.
Tokens will be stored in plain text in "/data/vhosts/wwwroot/html/java-kitchen-d9/auth.json OR /root/.composer/auth.json" for future use by Composer.
For additional information, check https://getcomposer.org/doc/articles/authentication-for-private-packages.md#github-oauth
A local auth config source was found, do you want to store the token there?
Token (hidden): 
Token stored successfully.

In CurlDownloader.php line 623:
                                                                                                                         
  [Composer\Downloader\TransportException (404)]                                                                         
  The "https://api.github.com/repos/ossobuffo/drupal-console-extend-plugin" file could not be downloaded (HTTP/2 404 ):  
  {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#get-a-repository"}            
                                                                                                                         

Exception trace:
  at phar:///usr/local/bin/composer/src/Composer/Util/Http/CurlDownloader.php:623
 Composer\Util\Http\CurlDownloader->failResponse() at phar:///usr/local/bin/composer/src/Composer/Util/Http/CurlDownloader.php:435
 Composer\Util\Http\CurlDownloader->tick() at phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php:386
 Composer\Util\HttpDownloader->countActiveJobs() at phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php:357
 Composer\Util\HttpDownloader->wait() at phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php:111
 Composer\Util\HttpDownloader->get() at phar:///usr/local/bin/composer/src/Composer/Repository/Vcs/VcsDriver.php:170
 Composer\Repository\Vcs\VcsDriver->getContents() at phar:///usr/local/bin/composer/src/Composer/Repository/Vcs/GitHubDriver.php:483
 Composer\Repository\Vcs\GitHubDriver->getContents() at phar:///usr/local/bin/composer/src/Composer/Repository/Vcs/GitHubDriver.php:540
 Composer\Repository\Vcs\GitHubDriver->fetchRootIdentifier() at phar:///usr/local/bin/composer/src/Composer/Repository/Vcs/GitHubDriver.php:83
 Composer\Repository\Vcs\GitHubDriver->initialize() at phar:///usr/local/bin/composer/src/Composer/Repository/VcsRepository.php:143
 Composer\Repository\VcsRepository->getDriver() at phar:///usr/local/bin/composer/src/Composer/Repository/VcsRepository.php:189
 Composer\Repository\VcsRepository->initialize() at phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:308
 Composer\Repository\ArrayRepository->getPackages() at phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:62
 Composer\Repository\ArrayRepository->loadPackages() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/PoolBuilder.php:385
 Composer\DependencyResolver\PoolBuilder->loadPackagesMarkedForLoading() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/PoolBuilder.php:239
 Composer\DependencyResolver\PoolBuilder->buildPool() at phar:///usr/local/bin/composer/src/Composer/Repository/RepositorySet.php:319
 Composer\Repository\RepositorySet->createPool() at phar:///usr/local/bin/composer/src/Composer/Installer.php:468
 Composer\Installer->doUpdate() at phar:///usr/local/bin/composer/src/Composer/Installer.php:287
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:247
 Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:377
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:141
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:88
 require() at /usr/local/bin/composer:29

And I expected this to happen:

Drupal security fixes and dependencies updated as done previously without any issue. Last successful update 07/03/2023

**Comment by Seldaek** [comment]
What is https://github.com/ossobuffo/drupal-console-extend-plugin ? It seems to be 404. Probably you should remove this from your composer.json:

```
"github": {
"type": "vcs",
"url": "https://github.com/ossobuffo/drupal-console-extend-plugin.git"
},
```

**Comment by inwebsol** [comment]
@Seldaek Thank you so much. I have no idea how that got there, but removing it worked. Have a great day!
