### ISSUE TITLE
Environment variable not work with local repo

### ISSUE THREAD

**Issue by aleksandr-shevchenko** [composer/composer#11409]
Composer ver.2.5.5, Win10

Environment variables work in Windows when I use local package with "type": "path", but not work with local repo with "type": "vcs".

My `composer.json`:

```json
    "repositories": [
    {
            "type": "vcs",
            "url": "d:/Rabota/PHP/_packages_/alex"
        }
    ],
    "require": {
        "alex/alex": "dev-master"
    }
```
work fine.

But (when MY_PHP_PATH=d:\Rabota\PHP)

```json
    "repositories": [
    {
            "type": "vcs",
            "url": "$MY_PHP_PATH/_packages_/alex"
        }
    ],
    "require": {
        "alex/alex": "dev-master"
    }
```
not work.

Output of `composer diagnose`:

```
In VcsRepository.php line 191:

  No driver found to handle VCS repository $MY_PHP_PATH/_packages_/alex
```

**Comment by stof** [comment]
I would say that they work in `path` only by luck (and they might not work cross-platform)

**Comment by aleksandr-shevchenko** [comment]
from documentation about `path`

> Leading tildes are expanded to the current user's home folder, and environment variables are parsed in both Windows and Linux/Mac notations.

**Comment by stof** [comment]
OK, then it is not by luck.

However, for VCS repositories, I would say that this not expanding them is done on purpose as the main use case for VCS repositories is to use remove URLs, not local paths.
