### ISSUE TITLE
How can I specify a conflict for all packages by a vendor?

### ISSUE THREAD

**Issue by drubb** [composer/composer#11413]
I'm using Asset Packagist to add libraries to Drupal projects. There are two package types there:

* Bower assets, bower-asset/*
* npm assets, npm-asset/*

which can be installed e.g. by `composer require npm-asset/whatever`

I don't want to use Bower assets at all, so I thought i could add a conflict rule in my composer.json:
```
"conflict": {
    "bower-asset/*": "*"
  },
```
But this doesn't seem to work. Composer (2.5.5) yields the following error:
```
conflict.bower-asset/* is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]?|-{0,2})[  
  a-z0-9]+)*$". 
```
What am I missing here?

**Comment by Seldaek** [comment]
We do not support wildcards in conflict, require or other such rules. And anyway conflict would not work in your case as it would fail dependency resolution.

You could use `"replace": {"bower-asset/foo":"*"}` to get rid of individual bower packages, but that's the best I can offer sorry.
