### ISSUE TITLE
Add support to Symfony/Runtime component for the BinaryInstaller

### ISSUE THREAD

**Issue by llaville** [composer/composer#11416]
#  Add support to [Symfony Runtime Component](https://github.com/symfony/runtime/) on the BinaryInstaller for CLI application that are compatible.

As author of the project https://github.com/llaville/box-manifest, I've recently added (v3.3) support to Symfony Runtime Component.

But when I try to install it as a dependency to another project (see composer.json file below), I get a fatal error at runtime !

My `composer.json` just for demo purpose only

<details>
<summary>contents of `composer.json`</summary>

```json
{
    "name": "bartlett/sandbox",
    "description": "For testing purpose only",
    "type": "project",
    "license": "MIT",
    "autoload": {
        "psr-4": {
            "Bartlett\\Sandbox\\": "src/"
        }
    },
    "authors": [
        {
            "name": "Laurent Laville"
        }
    ],
    "require": {
        "bartlett/box-manifest": "^3"
    },
    "config": {
        "sort-packages": true,
        "allow-plugins": {
            "symfony/runtime": true
        }
    },
    "extra": {
        "runtime": {
            "autoload_template": "vendor/bartlett/box-manifest/autoload_phar_runtime.template"
        }
    }
}
```

</details>

Output of `composer diagnose`:  Not really revelant here because it's a new feature request !

When I run this command:  `vendor/bin/box-manifest -vvv`

I get the following output:

```text
Fatal error: Uncaught TypeError: Invalid return value: callable object expected, "int" returned from "vendor/bin/box-manifest". in /shared/backups/bartlett/sandbox/vendor/autoload_runtime.php:20
Stack trace:
#0 /shared/backups/bartlett/sandbox/vendor/bartlett/box-manifest/bin/box-manifest(36): require_once()
#1 /shared/backups/bartlett/sandbox/vendor/bin/box-manifest(121): include('/shared/backups...')
#2 {main}
  thrown in /shared/backups/bartlett/sandbox/vendor/autoload_runtime.php on line 20
```

And I expected this to happen:  Application Help screen display  (chunk of output below)
```text

    ____                __  ___            _ ____          __
   / __ )____  _  __   /  |/  /___ _____  (_) __/__  _____/ /_
  / __  / __ \| |/_/  / /|_/ / __ `/ __ \/ / /_/ _ \/ ___/ __/
 / /_/ / /_/ />  <   / /  / / /_/ / / / / / __/  __(__  ) /_
/_____/\____/_/|_|  /_/  /_/\__,_/_/ /_/_/_/  \___/____/\__/

Box Manifest version 3.x-dev for Box 4.3.8@5534406

Usage:
  command [options] [arguments]
```

**Reason** The Symfony Runtime requires to return a PHP callable function ! 
In my context, this is a Symfony Console Application => https://github.com/llaville/box-manifest/blob/3.3.1/bin/box-manifest#L26-L40

But when we have a look on the `vendor/bin/box-manifest` file generated by Composer, we get at end of the file 
```
include __DIR__ . '/..'.'/bartlett/box-manifest/bin/box-manifest';
```
So the PHP callable is never returned to the `vendor/autoload_runtime.php`

I suggest this changes, because I've tested it in real condition with my application ! 

Replace the https://github.com/composer/composer/blob/2.5.5/src/Composer/Installer/BinaryInstaller.php#L363
By

```php
<?php

$return = require $binPathExported;

if (\is_callable($return)) {
    return $return;
}
```

**Comment by llaville** [comment]
To be honest, as I've myself an issue about possible autoloader paths (`vendor/autoload_runtime.php`), I've published a 3.3.2 to fix it (to understand https://github.com/llaville/box-manifest/compare/3.3.1...3.3.2#diff-a4efd8588b2c791819cbc6d3080d87668d32b7f838619bd93d79638f22f4028a)

But my fix suggestion on Composer BinaryInstaller is always the same ! (`require` or `include` is great for me too)

**Comment by Seldaek** [comment]
I think always returning probably would be even reasonable, as the point of those PHP proxies is to be fully transparent and behave as if the real file had been included.

**Comment by jankal** [comment]
related to
- https://github.com/box-project/box/pull/1246
- https://github.com/box-project/box/issues/655
- https://github.com/symfony/symfony/issues/49443

for everyone else looking into this.
