### ISSUE TITLE
Package from zip is installed, but not autoloaded

### ISSUE THREAD

**Issue by OnGe333** [composer/composer#11425]
When I put package in zip and set repository, it is downloaded properly, but ignored by autoloader. To be sure it is not bug in my package, I have used psr/cache to replicate issue:

1) without repository set in composer.json (so it is downloaded from packagist) I run composer require psr/cache. Package is installed and autoloaded properly.
2) I create zip of that package, save it localy and set zip repository in composer.json (see above)
3) run following:
composer remove psr/cache
composer composer clear-cache
composer require psr/cache

Now I get package installed from local repository. It is in vendor/psr/cache, files are there, but package is not autoloaded. Tried composer dumpautoload - no change. Any difference I can see is that when package is from zip, it is not autoloaded.

This happened on Windows 10.

My `composer.json`:

```json
{
    "name": "onge/composer-test",
    "type": "project",
    "license": "MIT",
	"repositories": [
		{
			"type": "package",
			"package": {
				"name": "psr/cache",
				"version": "3.0.0",
				"dist": {
					"url": "F:\\package\\psr\\cache.zip",
					"type": "zip"
				}
			}
		}
	],
    "autoload": {
        "psr-4": {
            "Onge\\ComposerTest\\": "src/"
        }
    },
    "require": {
        "psr/cache": "^3.0"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK git version 2.35.1
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.5.5
PHP version: 8.2.2
PHP binary path: F:\wamp\bin\php\php8.2.2\php.exe
OpenSSL version: OpenSSL 3.0.7 1 Nov 2022
cURL version: 7.85.0 libz 1.2.12 ssl OpenSSL/3.0.7
zip: extension present, unzip not available, 7-Zip not available
```

And I expected this to happen:
Package to be installed and autoloaded properly, just as if i download it from packagist.
[cache.zip](https://github.com/composer/composer/files/11185965/cache.zip)

**Comment by Seldaek** [comment]
The package type repository ignores the composer.json entirely and as such you are missing the autoload definition. Use a repo of type `artifact` to load zip archives that will work better. You'll have to define the version in the composer.json inside the archive though.
