### ISSUE TITLE
Failed to download yii2soft from dist using composer

### ISSUE THREAD

**Issue by faridnice** [composer/composer#11432]
![composer](https://user-images.githubusercontent.com/48247960/232672075-bfc95d23-dc30-4a61-9ca5-47a2192dedef.gif)

composer.json cannot be downloaded. Kindly please refer below screenshot. I already used the latest composer version and the latest yii2 framework version.

**Comment by Seldaek** [comment]
Looks like you're using a very old Composer version, and a PHP 8.2 which is too modern for yii2-app-basic  which requires PHP 8.1 or below it seems.

**Comment by stof** [comment]
For the failure to download from dist, the explanation is in the error message, on the second part of the line. You need either the PHP zip extension or a CLI tool able to unzip files, otherwise zip files cannot be used.
