### ISSUE TITLE
Support for @php inside scripts after `||` condition

### ISSUE THREAD

**Issue by alexander-schranz** [composer/composer#11467]
I try to provide a `serve` scripts for my symfony based application. It is common in spiral, yii frameworks to provide such script and to be consistent to whole projects I also wanted to add it to my symfony projects. As symfony recommends using symfony cli for local development, I tried to use that one but fallback to php internal webserver. But the `@php` is only supported at the beginning of the `scripts` not inside the script. Maybe it would be possible to support the usage of `@php` after `||`, for `&&` maybe also but that currently can workaround it by using array of commands. 

My `composer.json`:

```json
{
    "scripts": {
        "serve": "symfony serve || @php -S 127.0.0.1:8000 -t public config/router.php",
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK git version 2.38.1
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.5.5
PHP version: 8.1.16
PHP binary path: /opt/homebrew/Cellar/php@8.1/8.1.16/bin/php
OpenSSL version: OpenSSL 1.1.1t  7 Feb 2023
cURL version: 7.88.1 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1t
zip: extension present, unzip present, 7-Zip not available
```

When I run this command: 

```
composer serve -vvv
```

I get the following output: 

```
> symfony serve || @php -S 127.0.0.1:8000 -t public config/router.php
sh: symfony: command not found
sh: @php: command not found
Script symfony serve || @php -S 127.0.0.1:8000 -t public config/router.php handling the serve event returned with error code 127
```

And I expected this to happen:

```
> symfony serve || php -S 127.0.0.1:8000 -t public config/router.php
sh: symfony: command not found
[Mon May 15 19:45:05 2023] PHP 8.1.16 Development Server (http://127.0.0.1:8000) started
```

The `@php` does currently not work to be used inside the scripts, only at the beginning of the first call.

**Comment by Seldaek** [comment]
Yes these are only supported at beginning because otherwise we have to fully parse the string as if we were a shell and I'm sure this will open up a million edge cases that I'd rather not deal with..

**Comment by alexander-schranz** [comment]
That is something I understand, what would avoid parsing the string would be if a special constant like `"Composer\\Config::disableProcessTimeout"` would switch the current running all command to `or` e.g.:

```json
{
    "scripts": {
        "serve": [
             "Composer\\Config::processFallbacks",
             "symfony serve",
             "@php -S 127.0.0.1:8000 -t public config/router.php"
        ]
    }
}
```

**Comment by Seldaek** [comment]
Yeahh.. that might be doable with some horrible hacks. I am not sure. We'd have to reset the state after handling the event, but what happens if you fire an event during processing an event? Then it's still in fallback mode.. 

Overall not a fan of the idea :)

Not sure what else to do aside from creating an external binary file to handle more complex logic.. Or use `php` without @ and rely on system php..

**Comment by mvorisek** [comment]
I support this feature request as `@php` (`@composer`, ... `@` support in general) is quite important feature of composer. I belive we do not need to parse the shell command completely, we just need to parse strings and then replace `@xxx` after `||`, as `||` has quite high priority, we can ignore parsing `>` (redirection) or `--` (the end of options).

**Comment by Seldaek** [comment]
What about a script like `"@php -r 'echo \"|| @php\";'"` 

Obviously it's nonsensical, but I'm just saying there are possible complexities here.

**Comment by mvorisek** [comment]
That is why I am saying to parse string grammar and skip string's content :)

**Comment by Seldaek** [comment]
Yeah sorry didn't fully see the edits. Anyway for sure it is doable, but is it worth the effort? IMO no, but if someone else wants to do it and it doesn't add a ton of code I need to maintain then ok.
