### ISSUE TITLE
 Is there a plan to discontinue support for HHVM ?

### ISSUE THREAD

**Issue by kitrio** [composer/composer#11469]
Composer main branch source code 
Date : 2023 / May / 18

A few years ago HHVM stopped supporting PHP language 
(2018 year)

[https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html)

Developers, please consider deprecating HHVM support in the next major version of the composer.

**Comment by Seldaek** [comment]
Yes and no.. For a few years after (at least) Hack was still relying on Composer (via PHP) to install dependencies IIRC. @fredemmott do you know if this is still the case / HHVM still needed in Composer?

**Comment by fredemmott** [comment]
Composer is still used at Slack and by the open source ecosystem for Hack in general, without a current alternative; I'm no longer at Meta or working *on* Hack/HHVM, so also cc @wilfred and @paulbiss re future

**Comment by hopeseekr** [comment]
According to my bettergist database:

```
SELECT COUNT(*) FROM packagist_stats WHERE language='Hack';
 count 
-------
   295

SELECT SUM(installs) FROM packagist_stats WHERE language='Hack' LIMIT 5;
   sum   
---------
 9 344 563

SELECT package, installs FROM packagist_stats WHERE language='Hack' ORDER BY installs DESC LIMIT 10;
             package              | installs 
----------------------------------+----------
 craftcms/server-check            |  2386315
 hhvm/hsl                         |   690839
 hhvm/type-assert                 |   682362
 facebook/fbexpect                |   647866
 hhvm/hhast                       |   610812
 facebook/xhp-lib                 |   531822
 hhvm/hhvm-autoload               |   383452
 facebook/hack-codegen            |   372972
 facebook/hh-clilib               |   348715
 fredemmott/hack-error-suppressor |   346599
```

**Comment by Seldaek** [comment]
Yeah then let's close this, it doesn't cost us much to keep this code around..
