### ISSUE TITLE
Unconstrained `require` cmd must not lock the latest major version when not satisfiable

### ISSUE THREAD

**Issue by mvorisek** [composer/composer#11463]
`composer.json` - https://github.com/atk4/ui/blob/1e44990dcfbf976454272f14fb0e18e4272189a8/composer.json

and commands:

```
composer require --no-interaction --no-update phpunit/phpcov
composer update --ansi --prefer-dist --no-interaction --no-progress --optimize-autoloader
```

fail on PHP 8.1+ with [1]:

```
Using version ^9.0 for phpunit/phpcov
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires phpunit/phpcov ^9.0 -> satisfiable by phpunit/phpcov[9.0.0, 9.0.x-dev].
    - phpunit/phpcov[9.0.0, ..., 9.0.x-dev] require phpunit/phpunit ^10.0 -> found phpunit/phpunit[dev-main, 10.0.0, ..., 10.2.x-dev (alias of dev-main)] but it conflicts with your root composer.json require (^9.5.5).

Error: Your requirements could not be resolved to an installable set of packages.
```

I belive the problem is in `composer require` command which adds `phpunit/phpcov` with unsatisfiable version 9.x which requires `phpunit/phpunit` 10.x but such package is restricted to version 9.x (by `^9.5.5` in original composer.json).

I would expect composer to detect the latest SATISFIABLE version before it lock the version. In kinda does so as on PHP 8.0 composer works as expected (`phpunit/phpcov` is locked to version 8.x as 9.x requires PHP >=8.1).

composer version: 2.5.5 / latest

[1] https://github.com/atk4/ui/actions/runs/4968397012/jobs/8890969688?pr=2032#step:7:26

**Comment by Seldaek** [comment]
This works if you do the update as part of the require command, but with --no-update we cannot fully resolve so we do best guess only.

**Comment by mvorisek** [comment]
@Seldaek can I please ask you for a reply here, I still think this can & should be fixed.

**Comment by Seldaek** [comment]
Yeah I agree, the email was in my inbox, it's been 3 days and it was weekend, chill..

**Comment by Seldaek** [comment]
If no-update I guess maybe we could run the solver with all existing packages locked, that shouldn't take too much time/resources, but it may be a huge pain to implement.. So have to see if it's reasonably doable.

**Comment by Seldaek** [comment]
Yeah so I tried and I don't see a way to achieve this without doing a proper update, which would defeat the purpose of --no-update, and without adding a ton of code for this niche use case.

**Comment by Seldaek** [comment]
Yes, we can do an update, but then it updates the lock file too, and you asked --no-update so clearly you don't want that. When not using --no-update we always do a partial update with locked/exact versions anyway, unless --update-with-dependencies is given. So IMO you should not use --no-update in most cases.

**Comment by mvorisek** [comment]
`--no-install` is a partial solution to not have to specify the version manually
