### ISSUE TITLE
Root package version guesser only works when git HEAD is detached at a version tag

### ISSUE THREAD

**Issue by lkrms** [composer/composer#11472]
> My `composer.json`:

Values in `composer.json` don't appear to have a direct bearing on this issue. For the reasons given [in the documentation](https://getcomposer.org/doc/04-schema.md#version), I don't want to add `version` to `composer.json`, although when I do (e.g. in a build script after extracting the correct version from `git describe`), it's not picked up by `composer install` anyway. But for completeness, here's an example:

```json
{
    "name": "lkrms/pretty-php",
    "description": "The opinionated formatter for modern, expressive PHP",
    "license": "MIT",
    "bin": [
        "bin/pretty-php"
    ],
    "require": {
        "php": ">=7.4 <8.3",
        "lkrms/util": "^0.20.12",
        "sebastian/diff": "^4 || ^5"
    },
    "autoload": {
        "psr-4": {
            "Lkrms\\Pretty\\": "src/"
        },
        "files": [
            "bootstrap.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Lkrms\\Pretty\\Tests\\": "tests/"
        }
    },
    "config": {
        "sort-packages": true,
        "allow-plugins": {
            "phpstan/extension-installer": true
        },
        "platform": {
            "php": "7.4.33"
        }
    },
    "require-dev": {
        "clue/phar-composer": "^1.4",
        "phpstan/extension-installer": "^1",
        "phpstan/phpstan": "^1",
        "phpstan/phpstan-deprecation-rules": "^1",
        "phpunit/phpunit": "^9"
    }
}
```

> Output of `composer diagnose`:

The issue surfaces on multiple platforms, but here's what I'm working with today.

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK git version 2.40.1
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.5.5
PHP version: 7.4.33 - Package overridden via config.platform, actual: 8.2.6
PHP binary path: /usr/local/Cellar/php/8.2.6/bin/php
OpenSSL version: OpenSSL 1.1.1t  7 Feb 2023
cURL version: 8.1.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1t
zip: extension present, unzip present, 7-Zip present (7z)
```

When I run this command in a clean working tree (empty `git status` output) with a detached HEAD at the v0.4.7 tag (commit 9c3418b):

```
composer install -vvv
```

I get the following output:

```
Running 2.5.5 (2023-03-21 11:50:05) with PHP 8.2.6 on Darwin / 22.4.0
Reading ./composer.json (/Users/lina/Code/lk/pretty-php/composer.json)
Loading config file /Users/lina/.composer/config.json
Loading config file /Users/lina/.composer/auth.json
Loading config file ./composer.json (/Users/lina/Code/lk/pretty-php/composer.json)
Checked CA file /usr/local/etc/ca-certificates/cert.pem: valid
Executing command (/Users/lina/Code/lk/pretty-php): 'git' 'branch' '-a' '--no-color' '--no-abbrev' '-v'
Executing async command (/Users/lina/Code/lk/pretty-php): git rev-list main..9c3418b8106f5e1e2b9a5b3de1a3e9b82d72d6c3
Executing async command (/Users/lina/Code/lk/pretty-php): git rev-list develop..9c3418b8106f5e1e2b9a5b3de1a3e9b82d72d6c3
Executing async command (/Users/lina/Code/lk/pretty-php): git rev-list remotes/origin/main..9c3418b8106f5e1e2b9a5b3de1a3e9b82d72d6c3
Executing async command (/Users/lina/Code/lk/pretty-php): git rev-list remotes/origin/develop..9c3418b8106f5e1e2b9a5b3de1a3e9b82d72d6c3
Executing command (/Users/lina/Code/lk/pretty-php): git describe --exact-match --tags
Reading /Users/lina/.composer/composer.json (/Users/lina/Nextcloud/Settings/Private/composer/composer.json)
Loading config file /Users/lina/.composer/config.json
Loading config file /Users/lina/.composer/auth.json
Loading config file /Users/lina/.composer/composer.json (/Users/lina/Nextcloud/Settings/Private/composer/composer.json)
Loading config file /Users/lina/Nextcloud/Settings/Private/composer/auth.json
Reading /Users/lina/Nextcloud/Settings/Private/composer/auth.json
Reading /Users/lina/Code/lk/pretty-php/vendor/composer/installed.json
Reading /Users/lina/.composer/vendor/composer/installed.json
Loading plugin PHPStan\ExtensionInstaller\Plugin (from phpstan/extension-installer)
Loading plugin ComposerLink\Plugin (from sandersander/composer-link, installed globally)
[ComposerLink]	Plugin is activating
Reading ./composer.lock (/Users/lina/Code/lk/pretty-php/composer.lock)
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Reading ./composer.lock (/Users/lina/Code/lk/pretty-php/composer.lock)
Built pool.
Generating rules
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.000 seconds
Nothing to install, update or remove
Generating autoload files
43 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> post-install-cmd: PHPStan\ExtensionInstaller\Plugin->process
phpstan/extension-installer: Extensions installed
```

And this at the top of `vendor/composer/installed.php`:

```
    'root' => array(
        'name' => 'lkrms/pretty-php',
        'pretty_version' => 'v0.4.7',
        'version' => '0.4.7.0',
        'reference' => '9c3418b8106f5e1e2b9a5b3de1a3e9b82d72d6c3',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
```

Running the same command with the same working tree, at the same commit, but with the `main` branch checked out, I get this output:

```
Running 2.5.5 (2023-03-21 11:50:05) with PHP 8.2.6 on Darwin / 22.4.0
Reading ./composer.json (/Users/lina/Code/lk/pretty-php/composer.json)
Loading config file /Users/lina/.composer/config.json
Loading config file /Users/lina/.composer/auth.json
Loading config file ./composer.json (/Users/lina/Code/lk/pretty-php/composer.json)
Checked CA file /usr/local/etc/ca-certificates/cert.pem: valid
Executing command (/Users/lina/Code/lk/pretty-php): 'git' 'branch' '-a' '--no-color' '--no-abbrev' '-v'
Reading /Users/lina/.composer/composer.json (/Users/lina/Nextcloud/Settings/Private/composer/composer.json)
Loading config file /Users/lina/.composer/config.json
Loading config file /Users/lina/.composer/auth.json
Loading config file /Users/lina/.composer/composer.json (/Users/lina/Nextcloud/Settings/Private/composer/composer.json)
Loading config file /Users/lina/Nextcloud/Settings/Private/composer/auth.json
Reading /Users/lina/Nextcloud/Settings/Private/composer/auth.json
Reading /Users/lina/Code/lk/pretty-php/vendor/composer/installed.json
Reading /Users/lina/.composer/vendor/composer/installed.json
Loading plugin PHPStan\ExtensionInstaller\Plugin (from phpstan/extension-installer)
Loading plugin ComposerLink\Plugin (from sandersander/composer-link, installed globally)
[ComposerLink]	Plugin is activating
Reading ./composer.lock (/Users/lina/Code/lk/pretty-php/composer.lock)
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Reading ./composer.lock (/Users/lina/Code/lk/pretty-php/composer.lock)
Built pool.
Generating rules
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.000 seconds
Nothing to install, update or remove
Generating autoload files
43 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> post-install-cmd: PHPStan\ExtensionInstaller\Plugin->process
phpstan/extension-installer: Extensions installed
```

And this at the top of `installed.php`:

```
    'root' => array(
        'name' => 'lkrms/pretty-php',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '9c3418b8106f5e1e2b9a5b3de1a3e9b82d72d6c3',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
```

...where I would have expected to see references to `v0.4.7`.

(The outcome is the same in a clean environment without Composer extensions or global config files, by the way.)

This behaviour seems to come from here:

https://github.com/composer/composer/blob/main/src/Composer/Package/Version/VersionGuesser.php

I guess the first question should be: is this the desired behaviour? I'm using `InstalledVersions::getRootPackage()` to resolve the running application's version at runtime, but the current behaviour makes this unreliable (I'm getting by with an ugly `git checkout` in my [build script](https://github.com/lkrms/pretty-php/blob/main/scripts/build.sh) for now).

And the second question: if it's not the desired behaviour, what is? Should the version tag appear if the current commit is a match and the working tree is clean, or should it be more relaxed? Are you open to a PR to get this working?

**Comment by stof** [comment]
Well, if you are on the main branch, it is totally expected to guess the version as being `dev-main`, i.e. the version corresponding to the `main` branch.

**Comment by lkrms** [comment]
> Well, if you are on the main branch, it is totally expected to guess the version as being `dev-main`, i.e. the version corresponding to the `main` branch.

That makes sense in general, of course, but when the HEAD of the current branch has a version tag, shouldn't it be used for the purpose of identifying the package at that point in time?

Is there another way of preparing packages for distribution where VCS version tags are honoured at build time?

**Comment by Seldaek** [comment]
I would say you could use the COMPOSER_ROOT_VERSION env var to set the root package's version if you know you're building it for a given tag. Or make sure you run the tag builds with a checkout of the tag, and not the main branch at the tag's revision.

**Comment by lkrms** [comment]
Thanks for your feedback so far, @stof and @Seldaek. I really appreciate it!

> I would say you could use the COMPOSER_ROOT_VERSION env var to set the root package's version if you know you're building it for a given tag. Or make sure you run the tag builds with a checkout of the tag, and not the main branch at the tag's revision.

This is one of the methods I tested. It works for setting the version number, but I couldn't find a way to preserve the Git commit reference, which I extract and return with the version number at runtime whenever a value like "MyApplication v1.3.2-adf32abe" is required. (I know, I don't want much, do I... 😬)

I can't confirm this right now, but I believe the outcome is the same with `composer create-project`.

If a value like COMPOSER_ROOT_REFERENCE could also be passed at build time, this solution would be perfect. Being able to build the package outside of the working tree would make the process more robust too.

I know other mechanisms could be established for this, but they all require downstream effort to propagate version information that should--ideally--only need to appear in a VCS tag and be carried through to the distributable package automatically from there.

Would a PR to check for, validate and include a reference from the environment if COMPOSER_ROOT_VERSION be worth spending some time on?

**Comment by stof** [comment]
Which build time are you talking about ?

**Comment by lkrms** [comment]
> Which build time are you talking about ?

Apologies for the slow reply.

In this case, the build time I'm talking about is "when generating an executable phar for distribution as the official X.X.X release of a package".

I'm trying to determine the best method for getting the root package's version--and commit reference--from Git and into Composer's package metadata so it can be used at runtime to determine which version of the package is running.

Using the detached HEAD method might be what's needed, but it seems "hacky" in the absence of documentation, hence enquiring about the indented/desired behaviour.

**Comment by Seldaek** [comment]
If it's about phar packaging.. Isn't this something that box 
(https://github.com/box-project/box) solves?

We also embed the release date in Composer phars for ex by passing that 
in parsed from `git log -n1 --pretty=%ct HEAD` (using detached head 
checkouts to generate phars because IMO it's easier). This could well be 
done for the reference too.

I am just not entirely clear still what your problem is here or how we 
could help, I don't see how the version guessing of Composer has much to 
do with your build process (unless you use a Composer plugin or smth to 
build?).

**Comment by lkrms** [comment]
Sorry, I'm just getting back into this now. Apologies for taking so long to respond (again).

I've experimented with Box, which does indeed offer a solution of sorts, as long as one is content to use placeholder replacement to embed the relevant values. For my use case, this would require downstream packages to (a) use Box and (b) include something like `{"git-tag": "git_tag"}` in their `box.json` files.

I'm hoping for a solution that relies entirely on Composer's root package metadata--which is already present in every root package--to provide the version number and VCS reference, because one of my standard libraries extracts it from there, and abstracting it in this way means one less thing for downstream packages to implement.

It already works as described when `composer install` runs in a detached `HEAD` checkout, which is great but also requires running the build process in the repository itself, so Composer's version guesser can pick up the tag that's checked out. In some scenarios, building the package outside of the repository is preferable/necessary, which leaves passing the root package version and commit reference to Composer via the environment.

This is partially implemented courtesy of `COMPOSER_ROOT_VERSION`, but passing it to `composer install` leaves the reference value empty, so an additional variable is needed, e.g. `COMPOSER_ROOT_REFERENCE`, as suggested above.

I don't expect anyone to implement this for me, but should I add the functionality and open a PR?

**Comment by Seldaek** [comment]
So you would set COMPOSER_ROOT_VERSION=1.0.0 COMPOSER_ROOT_REFERENCE=9c3418b8106f5e1e2b9a5b3de1a3e9b82d72d6c3 when running composer install, and would expect that the root reference is then set as if you were running in a git repo? Is that the goal?

If so, yes it could be done pretty easily in RootPackageLoader line 93ish, where COMPOSER_ROOT_VERSION is also handled. Plus adding it to the cli.md docs. If you can do that then I think it sounds reasonable although a bit of a fringe use case.
