### ISSUE TITLE
Clarify that exact constraints are exact in problem output

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#11479]
`{"require":{"php":"8.2"}}` for ex will output:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires php 8.2 but your php version (8.2.3) does not satisfy that requirement.
```

The 8.2 bit there isn't very clear, maybe if we detect a short pinned version like that we could add warning/suggestion, and generally add a `=` in front of all pinned versions like `requires php =8.2` for clarity? Assuming this would bring clarity 😄

**Comment by naderman** [comment]
Maybe `requires PHP 8.2 exact version match (8.2, 8.2.0 or 8.2.0.0)`, just a bit verbose, but clear?
