### ISSUE TITLE
Handle better nullable file reference in \Composer\Json\JsonFile::validateSyntax()

### ISSUE THREAD

**Issue by mxr576** [composer/composer#11483]
When `\Composer\Json\JsonFile::validateSyntax()` called without a second parameter (e.g, via `\Composer\Json\JsonFile::parseJson('foo')`) it generates a cryptic exception message like

> "" does not contain valid JSON
Parse error on line 1:
warning: log for 'HE
^
Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['

Notice how the message start `"" does not contain valid JSON`.

https://github.com/composer/composer/blob/2.5.7/src/Composer/Json/JsonFile.php#L339-L347

**Comment by Seldaek** [comment]
I agree not ideal, but what would be better? `"string" does not contain valid JSON`?
