### ISSUE TITLE
Wrong return type on Classloader::getPrefixes

### ISSUE THREAD

**Issue by ciaranmcnulty** [composer/composer#11482]
I haven't PRed because I'm not sure what the type is in all cases but `string[]` appears to be incorrect, we get a multidimensional array back

https://github.com/composer/composer/blob/52f6f74b7c342f7b90be9c1a87e183092e8ab452/src/Composer/Autoload/ClassLoader.php#L116

**Comment by Seldaek** [comment]
Oh yeah this is outdated as hell :D 

The property has the type `array<string, array<string, string[]>>`. It's `array('F (first letter)' => array('Foo' => array('path', 'path2')))`

Then we array_merge all of the prefixes together so it should return `array('Foo' => array('path', 'path2'))` i.e. `array<string, list<string>>`?

**Comment by stof** [comment]
The `@return` of fallback dirs getters are also broken (but `@psalm-return` has the right one)
