### ISSUE TITLE
Problem with dev-master

### ISSUE THREAD

**Issue by aliqasemzadeh** [composer/composer#11491]
Hi
I have to package with the name  aliqasemzadeh/livewire-bootstrap-modal and   aliqasemzadeh/jetadmin when I try `composer require aliqasemzadeh/jetadmin' in clean project I get:
````
Problem 1
    - Root composer.json requires aliqasemzadeh/jetadmin dev-master -> satisfiable by aliqasemzadeh/jetadmin[dev-master].
    - aliqasemzadeh/jetadmin dev-master requires aliqasemzadeh/livewire-bootstrap-modal dev-master -> found aliqasemzadeh/livewire-bootstrap-modal[dev-master] but it does not match your minimum-stability.
````

what is my problem?
All package has public repository and you check them in my github.

**Comment by fredden** [comment]
Looking at https://packagist.org/packages/aliqasemzadeh/livewire-bootstrap-modal and https://packagist.org/packages/aliqasemzadeh/jetadmin, neither package has any released versions. The problem identified by this text in the output you quoted: "it does not match your minimum-stability." You should either specify a lower minimum-stability, or release actual versions of these packages. I recommend using semantic versioning where feasible.

References:
- https://getcomposer.org/doc/articles/versions.md
- https://getcomposer.org/doc/articles/troubleshooting.md#package-not-found
- https://getcomposer.org/doc/04-schema.md#minimum-stability
- https://semver.org/

**Comment by aliqasemzadeh** [comment]
@fredden 
Now I get:
````
  Problem 1
    - Root composer.json requires aliqasemzadeh/jetadmin * -> satisfiable by aliqasemzadeh/jetadmin[V1].
    - aliqasemzadeh/jetadmin V1 requires aliqasemzadeh/livewire-bootstrap-modal dev-master -> found aliqasemzadeh/livewire-bootstrap-modal[dev-master] but it does not match your minimum-stability.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require aliqasemzadeh/jetadmin:*" to figure out if any version is installable, or "composer require aliqasemzadeh/jetadmin:^2.1" if you know which you need.
````

I really don't know why this happen.

**Comment by fredden** [comment]
@aliqasemzadeh I can see you're experimenting with version constraints in your packages. You can see the current problem by running `composer validate` on your package.

**Comment by aliqasemzadeh** [comment]
@fredden  
I change all versions to "*" and now it works well.
Does it make any problem in future?

**Comment by fredden** [comment]
I think the Composer documentation explains the problem with using unbound constraints such as `*` fairly well:

> **Note:** Be careful when using unbounded ranges as you might end up unexpectedly installing versions that break backwards compatibility. Consider using the [caret](https://getcomposer.org/doc/articles/versions.md#caret-version-range-) operator instead for safety.

Reference: https://getcomposer.org/doc/articles/versions.md#version-range

**Comment by aliqasemzadeh** [comment]
But I want to work with all version and user don't need to update every time.
