### ISSUE TITLE
Running a binary from a script with @php fails on Windows

### ISSUE THREAD

**Issue by gilbertsoft** [composer/composer#11490]
My `composer.json`:

```json
{
	"name": "vendor/package",
	"description": "",
	"require": {
		"php": "^7.4 || ^8.0",
		"phpunit/phpunit": "^8.5.14 || ^9.5.5"
	},
	"require-dev": {
		"composer/composer": "^2.0",
		"phpspec/prophecy-phpunit": "^1.1 || ^2.0.2"
	},
	"minimum-stability": "dev",
	"prefer-stable": true,
	"scripts": {
		"tools:tests:unit": "@php phpunit --testsuite \"Unit Test Suite\""
	}
}
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK git version 2.40.1
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.5.7
PHP version: 8.1.10
PHP binary path: C:\PHP\current\php.exe
OpenSSL version: OpenSSL 1.1.1q  5 Jul 2022
cURL version: 7.77.0 libz 1.2.12 ssl OpenSSL/1.1.1q
zip: extension present, unzip not available, 7-Zip present (7z)
```

When I run this command: 

```
composer ci:tests:unit -vvv
```

I get the following output: 

```
> tools:tests:unit: @php phpunit --testsuite "Unit Test Suite"
Executing command (CWD): C:\PHP\current\php.exe -d allow_url_fopen=1 -d disable_functions="" -d memory_limit=1536M C:\Users\<my user>\Dev\PhpDevTools\phpunit-tools\vendor\bin\phpunit.BAT --testsuite "Unit Test Suite"
@ECHO OFF
setlocal DISABLEDELAYEDEXPANSION
SET BIN_TARGET=%~dp0/phpunit
SET COMPOSER_RUNTIME_BIN_DIR=%~dp0
php "%BIN_TARGET%" %*
```

And I expected this to happen:

Instead of running the `phpunit` binary, the content of the proxy file `phpunit.bat` is printed. The problem is located in the EventDispatcher (https://github.com/composer/composer/blob/7528c86e58884f5676d5851d52cd94c67372d609/src/Composer/EventDispatcher/EventDispatcher.php#L348-L356) where the `.BAT` extension is added.

A quick workaround for me was to define the full relative path to the `phpunit`:

```
"scripts": {
	"tools:tests:unit": "@php vendor/bin/phpunit --testsuite \"Unit Test Suite\""
}
```

Discovered today while running CI on a Windows runner at GH, works fine on Linux and Mac, see workflow run (https://github.com/PhpDevTools/phpunit-tools/actions/runs/5142833446/jobs/9258327038), step `Unit Tests`.

**Comment by Seldaek** [comment]
Weird tho that it wouldn't find it in the PATH with `phpunit`, because I assume both `phpunit` and `phpunit.bat` exist.. 

In any case we probably should fix this if possible because executing a .bat with php never makes sense.

**Comment by gilbertsoft** [comment]
Thanks for the quick fix @Seldaek . I can confirm, with 2.5.8 it works like expected now on Windows.
