### ISSUE TITLE
Git remote isn't updated when git server changed

### ISSUE THREAD

**Issue by hopeseekr** [composer/composer#11498]
Affects composer up to v2.5.7:

## The Problem

We changed git repos in March, from a self-hosted git to github.com. The self-hosted server was decomissioned completely.

All mentions of the old git URL have been replaced in both the `composer.json` and the `composer.lock` for 3 months now. All new composer installs download dependencies from github.com as expected, and use the latest version.

With every legacy install, however, composer silently ignores the new github.com route and installs from cache the old self-hosted git repo.

Legacy:
```
source   : [git] git@git.[self-hosted]:[redacted].git 6dd91e8ada75b6a2570defc99bc8bc81bda09697
```
New:
```
source   : [git] git@github.com:[redacted].git 6dd91e8ada75b6a2570defc99bc8bc81bda09697
```

## The Workaround

The only way I have found to mitigate the problem is to do:

```
rm -rf vendor/vendor-name/package
composer install
```

Then composer pulls from github.com instead.

**Comment by fredden** [comment]
As the package content is identical (same hash), why is this something that you are investigating / worrying about? It sounds like there's nothing for `composer install` to do (as the packages are already installed in `vendor/`).

The description suggests that packages are coming from Composer's cache, but also says that a work-around is to delete the package from `vendor/`. I'm confused about what the behaviour is and what you're trying to achieve. Maybe you want to run `composer clear-cache`?
