### ISSUE TITLE
Composer Windows Installer Problem

### ISSUE THREAD

**Issue by ElsevarAsadov** [composer/composer#11515]
I wanna install composer using windows installer it says me you need to provide some requirements.First time i add some dependencies to php.ini file then i click back and next this time there is no requirements but still the installer doesnt let me download composer.

![Annotation 2023-06-17 213646](https://github.com/composer/composer/assets/125838640/7b5fb47d-255c-4ada-9f30-84999c67b260)

**Comment by ElsevarAsadov** [comment]
i deleted temp files in windows but still not works

**Comment by ElsevarAsadov** [comment]
this is my fault because my **extension_dir** path was wrong

**Comment by johnstevenson** [comment]
Glad you sorted this, but I'm a bit concerned that you got such a useless error message. It would be useful to review the install logs if you still have them, as per the instructions here: https://github.com/composer/windows-setup/issues/new

**Comment by ElsevarAsadov** [comment]
sorry i do not have the logs.

**Comment by johnstevenson** [comment]
No worries, and thanks for replying.
