### ISSUE TITLE
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

### ISSUE THREAD

**Issue by kevalvadadoriya** [composer/composer#11518]
My `composer.json`:

```json
...replace me...
```

Output of `composer diagnose`:

```
...replace me...
```

When I run this command: 

```
...replace me...
```

I get the following output: 

```
...replace me...
```

And I expected this to happen:

**Comment by Seldaek** [comment]
Issues in artisan are not Composer related, please report to Laravel.
