### ISSUE TITLE
Allow for archive downloads without extension

### ISSUE THREAD

**Issue by imme-emosol** [composer/composer#11513]
FileDownloader.php its getFileName seems to extract an extension based on the given url.

Recently I came across an archived package publication to a extensionless file name, e.g. ".../download".

Upon inspecting the curl-headers I saw the response included a Content-Disposition header, which I used to detect the extension, which seems to affect the chosen unarchiving procedure.
Later I thought about that Content-Type might be more widely used/available.

Anyway, perhaps a feature to consider adding into composer.

I temporarily resolved my issue by this replacing getFileName its content with this pile of characters.

With php hilighting (as that seems to get lost in the ```diff):
```php
    protected function getFileName(PackageInterface $package, string $path): string
    {
        $extension = $this->getDistPath($package, PATHINFO_EXTENSION);
        if (!$extension) {
            $context=stream_context_create(['http'=>['method'=>'HEAD',],]);
            $headers = get_headers($package->getDistUrl(),true,$context);
            if ($headers['Content-Disposition']){
                $disposition = explode(';', $headers['Content-Disposition']);
                $disposition = array_map('trim', $disposition);
                foreach ($disposition as $k => $e) {
                    $f=explode('=',$e);
                    unset($disposition[$k]);
                    $disposition[$f[0]]=$f[1]??null;
                }
                if (isset($disposition['filename*'])) {
                    $fileName = str_replace('UTF-8\'\'', '', $disposition['filename*']);
                    $extension = pathinfo($fileName, PATHINFO_EXTENSION);
                }
                elseif (isset($disposition['filename'])) {
                    $fileName = substr($disposition['filename'], 1, -1);
                    $extension = pathinfo($fileName, PATHINFO_EXTENSION);
                }
            }
        }
        return rtrim($this->config->get('vendor-dir') . '/composer/tmp-' . md5($package . spl_object_hash($package)) . '.' . $extension, '.');
    }
```

The ```diff:
```diff
    protected function getFileName(PackageInterface $package, string $path): string
    {
-        return rtrim($this->config->get('vendor-dir') . '/composer/tmp-' . md5($package . spl_object_hash($package)) . '.' . $this->getDistPath($package, PATHINFO_EXTENSION), '.');
+        $extension = $this->getDistPath($package, PATHINFO_EXTENSION);
+        if (!$extension) {
+            $context=stream_context_create(['http'=>['method'=>'HEAD',],]);
+            $headers = get_headers($package->getDistUrl(),true,$context);
+            if ($headers['Content-Disposition']){
+                $disposition = explode(';', $headers['Content-Disposition']);
+                $disposition = array_map('trim', $disposition);
+                foreach ($disposition as $k => $e) {
+                    $f=explode('=',$e);
+                    unset($disposition[$k]);
+                    $disposition[$f[0]]=$f[1]??null;
+                }
+                if (isset($disposition['filename*'])) {
+                    $fileName = str_replace('UTF-8\'\'', '', $disposition['filename*']);
+                    $extension = pathinfo($fileName, PATHINFO_EXTENSION);
+                }
+                elseif (isset($disposition['filename'])) {
+                    $fileName = substr($disposition['filename'], 1, -1);
+                    $extension = pathinfo($fileName, PATHINFO_EXTENSION);
+                }
+            }
+        }
+        return rtrim($this->config->get('vendor-dir') . '/composer/tmp-' . md5($package . spl_object_hash($package)) . '.' . $extension, '.');
    }
```

**Comment by imme-emosol** [comment]
If Content-Disposition , this might be interesting: https://github.com/cardinalby/phpContentDisposition .

**Comment by Seldaek** [comment]
Yeah I am not sure.. That seems pretty messy to me to do a request just to get the headers, and then do another request with the download after, also you may not have the proper auth setup at that point etc. Just overall not a workable generic solution.

Just out of curiosity though, what's the problem you were seeing without this? As far as I know the downloader/archive extraction used is defined by the dist type of the package and the filename/extension has no actual impact, only cosmetic.

**Comment by Seldaek** [comment]
Ok I guess this is a problem of the PharData class needing an extension to identify the file format. Can you try manually opening one of those files with PharData to see if passing Phar::TAR explicitly to $format or some other value would help fix this? See https://www.php.net/manual/en/phardata.construct.php

**Comment by stof** [comment]
maybe the code could reuse the same logic than for the cache to add the extension

**Comment by Seldaek** [comment]
@stof sorry but what code do you mean?

**Comment by imme-emosol** [comment]
I saw this message passing by with composer i -vvv
```
Writing /tmp/cache/files/acme/package/084c61ce0b7c660b97a1866d9ea2ae23103c4c81.tar into cache from /app/vendor/composer/tmp-dac7ef442f58594e6ad1da088dff7cdb
```
Seems to be from https://github.com/composer/composer/blob/c7bbd606216d2a5ceea93e6a536c39f6636a1f90/src/Composer/Cache.php#L198

**Comment by Seldaek** [comment]
Yeah found the code in question https://github.com/composer/composer/blob/c7bbd606216d2a5ceea93e6a536c39f6636a1f90/src/Composer/Downloader/FileDownloader.php#L130 - it's kinda chance that the dist type matches the extension phardata expects though. There is no smarts here about content types or whatever.

**Comment by Seldaek** [comment]
But yes, probably could make sure that if there is no file extension in url we at least append the dist type to the file name.. That'd be an easy fix and might help.

**Comment by Seldaek** [comment]
Ok please try with `composer self-update --snapshot` if it solves it for you :)

**Comment by imme-emosol** [comment]
Just remembered the archive is also gzip`ed, but adding that to the PharData::__construct does not work either.

It seems that PharData does not look at the file contents at all.
As apparently the file did no longer exist, but PharData did not throw anything about that.

Putting an empty file into PharData seems to throw another type off message, it seems:
```sh
touch f.tar

Fatal error: Uncaught UnexpectedValueException: internal corruption of phar "/app/f.tar" (truncated entry) in Command line code:1
```

re: if solved: yes, it does solve it for me +1 :smiley:

**Comment by imme-emosol** [comment]
Thanks!

**Comment by Seldaek** [comment]
Ok cool, yes PharData isn't the smartest cookie it seems, but that's all we got to handle tar (and tbh that's one of the reasons we prefer the zip format even tho github does tgz as well..).

**Comment by imme-emosol** [comment]
There seems to be a php-native untar.
https://packagist.org/packages/splitbrain/php-archive
https://github.com/splitbrain/php-archive/blob/master/src/Tar.php

But I can imagine this is not high on the list, as most systems able to produce `.tar` are capable of `.zip` as well.

**Comment by Seldaek** [comment]
Yeah also this doesn't support tar compression without the zip extension though so it's only so useful..
