### ISSUE TITLE
Allow custom downloaders to be installed on the project level

### ISSUE THREAD

**Issue by mxr576** [composer/composer#11514]
I built a custom "foo" downloader plugin implementation that is responsible for downloading and installing packages from a special "foo" repository. The package install on an existing project works as designed, but when a project is set up from scratch via `composer install` it fails with:

```

In DownloadManager.php line 121:
                                                                                                                                 
  Unknown downloader type: foo. Available types: git, svn, fossil, hg, perforce, zip, rar, tar, gzip, xz, phar, file, path.  

```

Unless the plugin is globally installed...

Based on what I currently understand from how Composer works behind the scenes and considering that [there are already special plugin feature flags](https://getcomposer.org/doc/articles/plugins.md#plugin-extra-attributes), maybe the list could be extended with a new feature flag that would force Composer to download packages with downloader implementations first, install them and only try to install other packages afterward when the other downloaders are already active.

Of course, the limitation of this design would be that downloaders must be stored in one of the built-in downloaders (`git, svn, fossil, hg, perforce, zip, rar, tar, gzip, xz, phar, file, path`), unless every downloader install could restart the process and ensure that a freshly installed downloader is available for the rest of the process. In that case, only the order/priority of downloaders would be needed to be adequately specified.

**Comment by Seldaek** [comment]
I believe using `plugin-modifies-downloads` here would perhaps solve it? But yes these kind of chicken-and-egg-dilemma plugins are often problematic, and installing them globally or refraining from building such things is often better.
