### ISSUE TITLE
Proposal: use `XDG_DATA_DIRS` for finding pubkeys

### ISSUE THREAD

**Issue by drupol** [composer/composer#11510]
Hello,

I have encountered an issue while using the PHAR distribution of Composer. When I execute the `diagnose` command, I have the following error message:

![](https://github.com/composer/composer/assets/252042/98d03fb4-54d1-49d7-baba-c80358a1dce1)

Upon reviewing the code, I noticed that [Composer searches for certain keys](https://github.com/composer/composer/blob/bbea3e5284fd859373c292c7f696f9647f9a59ef/src/Composer/Command/DiagnoseCommand.php#L152) in the user's home directory.

With this issue, I would like to start a discussion regarding the potential for Composer of finding these keys in one of the XDG variables (see [XDG Base Directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)), rather than in the user's home directory. I'm leaning towards `XDG_DATA_DIRS`.

Let me know what you think of this, I might be proposing a PR fixing this.

**Comment by Seldaek** [comment]
Did you install Composer with the installer, or are you just running the phar file after downloading it directly? Because if you have not run the installer then yeah the keys aren't setup.

Composer should use XDG to find the config dir and use that as Composer home (`~/.config/composer` typically). For sure one could argue the keys should be in data dir instead, but that'd break things and doesn't really seem worth the breakage or the trouble of keeping it BC IMO.

**Comment by drupol** [comment]
Upon reviewing my initial post, I identified a minor error.

The concept I intended to convey involves a mechanism for resolving a configuration file. When provided with a list of directories, the mechanism would examine the first directory for the config file. If it's absent, it would proceed to the subsequent directories on the list. Additionally, I aimed to implement the same resolution mechanism for configuration files within Composer.

Here's a rough PHP implementation of the concept. (_Note: Replace `<HOME>` with the current username_):

<details>

```php
$configDirectories = [ 
    '<HOME>/.local/share/composer', // Corresponds to XDG_DATA_HOME
    '<HOME>/.config/composer', // Corresponds to XDG_CONFIG_HOME
    '<HOME>/.state/composer', // Corresponds to XDG_STATE_HOME
    '/usr/local/share/composer', // Includes all entries from XDG_DATA_DIRS
    '/usr/local/config/composer' // Includes all entries from XDG_CONFIG_DIRS
];

$configDirectory = array_reduce(
    $configDirectories,
    function (?string $carry, string $directory): ?string {
        if (null !== $carry) {
            return $carry;
        }

        if (file_exists($directory) && is_dir($directory)) {
            return $directory;            
        }

        return $carry;
    },
    null
);
```

</details>

Let me know what you think.

**Comment by Seldaek** [comment]
Yeah we already have something similar, we just do not consider XDG_DATA_HOME right now https://github.com/composer/composer/blob/06b4923c475dfb33589dff644ff184ec30e722f6/src/Composer/Factory.php#L57-L96 - What composer puts in home is more config than "data" (whatever that means) IMO. We use XDG_CACHE_HOME for the cache as well. I feel like we're in an ok position on this topic...
