### ISSUE TITLE
Error While installing the composer 

### ISSUE THREAD

**Issue by harshnapatel** [composer/composer#11529]
PHP Warning:  copy(https://getcomposer.org/installer): failed to open stream: Connection timed out in Command line code on line 1

**Comment by Tim-Obert** [comment]
Same here. Happens in our Pipeline since yesterday.

**Comment by Seldaek** [comment]
Still happening? I'm guessing it was a temporary network issue but hard to tell from here.

**Comment by Tim-Obert** [comment]
Nope doesn't happen anymore 👍🏻 Thank you!
