### ISSUE TITLE
Running composer not possible on Windows cross-domain

### ISSUE THREAD

**Issue by lyrixn** [composer/composer#11538]
Steps to reproduce:
1. Files (mediawiki) are on a network path (domain1)
2. domain1-s network path is a network share on domain2
3. running `composer update --no-dev` from domain2 while having authenticated via SMB using domain1's credentials on mediawiki files results in an error: `B:\wiki\w\includes/../vendor/autoload.php exists but is not readable`
running `php8 composer-setup.php` also results in a similar error `The installation directory "B:\wiki\w" is not writable`

Problem: composer thinks I don't have access to domain1's path because I've authenticated via SMB to access that network path from domain2 with domain1's credentials. The directory is perfectly writable, but composer doesn't know at which user's contest.

So:
Network share: \\domain1\web
Network share permissions read/write: user@domain1

Network share being accessed from domain2 via Windows SMB as user@domain2
Using credentials of user@domain1 while prompted
composer being run from domain2 as user@domain2 while authenticated via SMB as user@domain1

**Comment by fredden** [comment]
This doesn't sound like a problem that's specific to Composer. What do you get when you run `php8 -r 'var_dump(is_writeable("B:\\wiki\\w\\"), is_writeable("B:\\wiki\\w\\test.php"), is_writeable("B:\\wiki\\w\\includes/../vendor/autoload.php"));'`

Ref: https://github.com/composer/getcomposer.org/blob/main/web/installer#L748-L749

**Comment by lyrixn** [comment]
Apologies for the delay.
`PHP Parse error:  syntax error, unexpected token "\" in Command line code on line 1

Parse error: syntax error, unexpected token "\" in Command line code on line 1`

**Comment by lyrixn** [comment]
I found a solution that works for me (maybe not the best method to approach this, but I'll share it anyway).
1. Add the following to php.ini's `disabled_functions`: `is_writable,is_readable`
2. Create custom php script for is_writable and is_readable:
```
<?php
function is_readable($file)
{
    if(file_exists($file) && is_file($file))
    {
        $f = @fopen($file, 'rb');
        if(fclose($f))
        {
            return true;
        }
    }

    return false;
}

function is_writable($file)
{
    $result = false;
    if(file_exists($file) && is_file($file))
    {
        $f = @fopen($file, 'ab');
        if(fclose($f))
        {
            return true;
        }
    }

    return false;
}
?>
```
3. Add custom script to php.ini's `auto_prepend_file`: `C:\location\to\script\custom.php`

I hope this helps someone else in the future.
