### ISSUE TITLE
Feature Request: Support private repositories (e.g. in GitLab) recursively

### ISSUE THREAD

**Issue by moezkorkmaz** [composer/composer#11537]
Private repositories are not resolved&loaded recursively (https://getcomposer.org/doc/faqs/why-cant-composer-load-repositories-recursively.md).

Uploading the sources to an external repository (e.g. private packagist) is not an option in the company.

Will this be supported in near future?

**Comment by Seldaek** [comment]
Nope, very unlikely we add support for this sorry, it's just not compatible with proper package resolution IMO.
