### ISSUE TITLE
Difference between COMPOSER_MEMORY_LIMIT=X and memory_limit=X

### ISSUE THREAD

**Issue by jontjs** [composer/composer#11540]
I suspect this is expected behaviour, but I think it might be worth pointing out in the documentation (https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors).

When running `php -d memory_limit=X /usr/local/bin/composer install` I get a memory limit error when it runs Symfony's `cache:clear` under `auto-scripts`. I understand this is because composer does not pass its PHP options to the the `cache:clear` external process, which is fair enough.

However, when running `COMPOSER_MEMORY_LIMIT=X composer install` I do not run into the memory limit error. I guess this is because the environment variable exists for all processes triggered by the command, which is also fair enough.

I think it's worth mentioning this distinction in the documentation at https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors.

**Comment by Seldaek** [comment]
You are correct that the env var propagates while the flag does not, but I'm not sure why symfony's cache:clear would respect Composer's memory limit env var. That seems weird.

**Comment by Seldaek** [comment]
We definitely could mention in the docs that this will only fix Composer specific memory issues though, and child processes are on their own and should be fixed where relevant.

**Comment by abreel** [comment]
@Seldaek Has this been handled? Can I look into this?

**Comment by Seldaek** [comment]
If you like to PR the docs as per my last comment above feel free yes.

**Comment by abreel** [comment]
okay, @Seldaek 

I will look into that and revert

**Comment by abreel** [comment]
@Seldaek, made pr

https://github.com/composer/composer/pull/11624
