### ISSUE TITLE
curl error 55 on macOS Ventura 13.4 when using a custom package repository 

### ISSUE THREAD

**Issue by MarcoPNS** [composer/composer#11560]
When I try to perform a composer update then composer try to find every package on my gitlab package repository. After getting a 404 it try to find the package on the offical repository. This is fine but after a while it drops this error

```
https://gitlab/api/v4/group/16/-/packages/composer/packages.json could not be fully loaded (curl error 55 while downloading https://gitlab/api/v4/group/16/-/packages/composer/p2/zendframework/zend-eventmanager.json: Failed sending data to the peer), package information was loaded from the local cache and may be out of date

In CurlDownloader.php line 365:
                                                                                                                                                                        
  curl error 55 while downloading https://gitlab/api/v4/group/16/-/packages/composer/p2/zendframework/zend-eventmanager.json: Failed sending data to the peer  
                                                                                                                                                                        
```

This error is not exclusive to this package. When I clear the composer cache, the fail happens at a different package. 

For context: I'm using a gitlab v16.1.2-ee instance for my own packages. I reference the repo lik this:

```json
    "repositories": {
        "gitlab/16": {
            "type": "composer",
            "url": "https://gitlab/api/v4/group/16/-/packages/composer/packages.json"
        }
    }
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
require.foo/bar : unbound version constraints (@dev) should be avoided
Checking platform settings: OK
Checking git settings: OK git version 2.40.1
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.5.8
PHP version: 8.1.21
PHP binary path: /opt/homebrew/Cellar/php@8.1/8.1.21/bin/php
OpenSSL version: OpenSSL 3.1.1 30 May 2023
cURL version: 8.2.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/3.1.1
zip: extension present, unzip present, 7-Zip not available

```

Also I would like to mention that even on a clean Mac with Ventura 13.4 that never touched php and a composer before I could replicate this issue. But again on a different machine with an older macOS Ventura 13.0.1 the error does not happen. Also an older cURL Version is installed on the older version. (cURL version: 7.86.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1s)

I'm a little stumped right now as to where exactly to look for the problem. Is it Gitlab? Is it Ventura 13.4? Is it cURL? Is it Composer? Downgrading Composer doesn't fix the problem either unfortunately

**Comment by fredden** [comment]
Guess: maybe the remote server isn't happy with the number of connections / requests being made there. I suggest monitoring the remote web server for errors / capacity while the `composer` command runs.

**Comment by MarcoPNS** [comment]
Thanks for the guess @fredden - I had the same guess and tried to composer update on two devices at the same time. the older mac can run it every time without issue, the newer one not.

Is there a way to modify the cURL Version that composer is using?

**Comment by Seldaek** [comment]
https://github.com/composer/composer/pull/11543 might have fixed this, please try after a `composer self-update --snapshot`

**Comment by MarcoPNS** [comment]
@Seldaek This actually solves my problem. Thanks for the hint. Even if I know that this is a very temporary solution actually.
