### ISSUE TITLE
Is downloading the source of a SINGLE package (without any of its dependencies) possible using composer?

### ISSUE THREAD

**Issue by connecteev** [composer/composer#11561]
I am trying to download the source of a SINGLE premium package "xyz/abc" that I pay for (say it is hosted at https://premium-package-repo.com, but the website doesn't have a UI to download the package directly). I want to download the source of just this one premium package, without any of its dependencies.

Here's how I currently install the package (using `composer.json` and `auth.json` which has my premium credentials). 

My `composer.json`:
```json
{
    "require": {
        "xyz/abc": "*"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://premium-package-repo.com"
        }
    ]
}

```

My `auth.json`:

```json
{
    "http-basic": {
        "premium-package-repo.com": {
            "username": "username@gmail.com",
            "password": "xxxxxxxxxxxxxxxxxxxxxx"
        }
    }
}
```

When I run this command: 

```
composer update
```

the package gets downloaded to my vendor directory, along with a HUGE list of the package's dependencies.
That's not what I want...I want just the source of the premium package without any of its dependencies. Also, I want to keep the package updated as new releases are made (I would expect that I would need to run a command manually from time to time).

Note: I did already look at https://github.com/composer/composer/pull/4946 (not the same), and tried the --no-install and --download-only flags. Neither of these solved my problem.

Is there a composer command to do this?

**Comment by Seldaek** [comment]
You could try `composer archive xyz/abc 1.0.0 -f zip`. That should download the package and rearchive it so you should end up with a zip in the current directory.

**Comment by Seldaek** [comment]
The alternative would be to use the create-project command to download and extract the package, with `--no-install` and `--repository=https://premium-package-repo.com` (it'd require you have auth configured globally, or set in COMPOSER_AUTH tho).

**Comment by connecteev** [comment]
@Seldaek very helpful, thank you!

Here's the exact command / script that I ended up using:

```
#!/bin/bash

DIR_NAME=my_dir_name
composer archive packageowner/packagename --format=tar --file $DIR_NAME  # To get the latest version of the package (with specified .tar file name)
#composer archive packageowner/packagename 1.0.0 --format=tar --file laravel_nova_package  # To get a specific version of the package (with specified .tar file name)
```

**Comment by connecteev** [comment]
Thanks for clarifying!
