### ISSUE TITLE
Support custom constraints in the `require` command

### ISSUE THREAD

**Issue by ethanclevenger91** [composer/composer#11572]
Somewhat like #6816, which proposed adding an option to the `require` command to get `~` instead of `^` as the version constraint for a package. The impetus was projects that don't follow semver.

But ignoring upstream, sometimes in user-land there are scenarios in which you want a custom constraint, but also don't know the current version of a package off-hand. 

For example, on a WordPress project, I may want to require a plugin and always want updates applied if we run `composer update` because, well, WordPress. So I would do something like:

`composer require wpackagist-plugin/mailgun:'>=1.0'`

Though I may use this plugin all the time, I might not remember what its latest version is. The above command will definitely get me the latest version of the plugin, but having an older version in `composer.json` increases the time Composer takes to run `update`, as I understand it, because it'll be trying more combinations.

I _could_  do the above, followed by a `composer bump`, but a QOL improvement would be to combine my constraint configuration with Composer's magic auto-resolution of the latest package version:

`composer require --constraint='>=' wpackagist-plugin/mailgun`

Which would get me the latest version of the plugin in my lockfile, with the `>=` constraint rather than `^`.

**Comment by Seldaek** [comment]
Much like for #6816, I'd rather not add complexity here to enable sub-par use cases to proliferate. Using `>=` is a bad idea generally speaking and something we discourage as it is unbounded.

Why not use `composer require wpackagist-plugin/mailgun` and let it guess the appropriate version? As of 2.5 Composer does this very reliably even if the latest version has incompatibilities with your project (which used to cause problems).

**Comment by stof** [comment]
Note that using `>=` is unsafe for *any* package (whether they follow semver or no). So in all cases, it is worst than using `^`
