### ISSUE TITLE
Error when trying to install laravel 

### ISSUE THREAD

**Issue by mrzM7md** [composer/composer#11573]
In CurlDownloader.php line 365:

  curl error 28 while downloading https://repo.packagist.org/packages.json:    
  SSL connection timeout 

my php 8, last version of composer, used xampp

**Comment by abreel** [comment]
@Seldaek Can I look into this?

**Comment by fredden** [comment]
@mrzM7md please can you supply the information requested in the issue template. This is the content that you deleted when creating this issue. For your reference, you can find a copy here: [https://github.com/composer/composer/blob/main/.github/ISSUE_TEMPLATE.md](https://github.com/composer/composer/blob/75ae504b2c8a7ee8533c69788c3bbdbf3740e610/.github/ISSUE_TEMPLATE.md?plain=1)

I imagine that the output of `composer diagnose` may be helpful here.
