### ISSUE TITLE
git authentication errors are not displayed

### ISSUE THREAD

**Issue by tp971** [composer/composer#11570]
`Composer version 2.5.8 2023-06-09 17:13:21`

I tried to use a git repository like this:

```json
{
    ...
    "repositories": [
        {
            "type": "vcs",
            "url": "https://username:password@example.com/some/repo.git"
        }
    ],
    ...
}
```

If the git authentication fails for any reason, composer does not display an error, but rather just prompts for username and password on the console, even with `-vvv`. I would expect to be able to see the authentication error on the console, at least when I start composer with `-v`.

**Comment by Seldaek** [comment]
Please try again after a `composer self-update --snapshot`, it should now output before asking for credentials if you have `-v`.
