### ISSUE TITLE
[Tests] Suggestion: make command related tests CLI independent

### ISSUE THREAD

**Issue by jrfnl** [composer/composer#11598]
When running the test suite locally in a CLI client which supports colors, a bunch of tests (89 of them) will fail due to the captured output containing colors, while the tests do not expect color in the captured output.

I'd like to suggest adjusting the test suite to either strip the color markers from the output before asserting anything òr to run the test commands with whatever setting is needed to suppress the automatic color detection in Composer, to make running the tests locally more accessible for contributors.

**Comment by Seldaek** [comment]
Sorry can you explain more how you get this? If I run `composer test` it works for me in my terminal which definitely supports colors.

<img width="322" alt="image" src="https://github.com/composer/composer/assets/183678/502848cf-f1a4-47aa-8a2a-5d2013ed60b4">

**Comment by stof** [comment]
If you run tests in a ConEmu-enabled environment, it is indeed possible that the color support guessing will report colors as supported for the collected output in the tests, as the detection of ConEmu is not based on the actual output but on an environment variable.

**Comment by jrfnl** [comment]
@stof Interesting.

Either way, feel free to ignore (or close) this issue, just thought it was something you should be aware of as something which _may_ be problematic to some contributors.

**Comment by Seldaek** [comment]
Yeah ConEmu is kind of a weird mutant in terms of CLI.. I've used it for many years but I gotta say I'm glad I left it and its weird "almost-linux" problems behind. Using WSL2 + Windows Terminal now which is great. 

But anyway I committed an attempt at fixing, please confirm if it helps @jrfnl

**Comment by jrfnl** [comment]
@Seldaek Just ran the test suite again. Works like a charm! ♥️
