### ISSUE TITLE
COMPOSER_DISABLE_NETWORK aware `diagnose` checks

### ISSUE THREAD

**Issue by ktomk** [composer/composer#11596]
Given `COMPOSER_DISABLE_NETWORK=1`, when `diagnose` then non-zero exit status (2; meaning: Error) and multiple stack traces in the console (cf. _Details_).

I'd like to change the behaviour and think it is better to display a diagnostic message that a Composer network dependent diagnosis has been skipped because the Composer network is disabled.

I've written a functional patch for this but would like to clarify a couple of things before suggesting it:

1. **changes in the exit status** -- I'd go from 2 to 0 (OK), and think it's very ok to do given the output shows SKIP for those checks and a message, so it should be visible in user reports sharing the `diagnose` output:

   _"Checking https connectivity to packagist: SKIP Composer network is disabled by COMPOSER_DISABLE_NETWORK=1."_

   ![Selection_297](https://github.com/composer/composer/assets/352517/b5810977-9148-4c9a-9f77-b99e31ffb72e) .

   This might be received a bit subjective, so an alternative I've been thinking about is, given COMPOSER_DISABLE_NETWORK is true, then have a check before the affected checks that warns about that fact and effectively raises exit status to 1. Another variant is to have them all as warning, but this is less aligned with successive `allow_url_fopen` checks [as in private checkConnectivity()][cc] which are on the info level.

[cc]: https://github.com/composer/composer/blob/f605389dc3101c903081ed0e95f9a872a8bfc930/src/Composer/Command/DiagnoseCommand.php#L733-L741

2. **versions to patch** -- `COMPOSER_DISABLE_NETWORK` is since [2.0.0-alpha1] and next to having this in main, I'd like to see it as well in stable, 2.2 and if there are still updates for 2.0 therein as this is for building and different channels could then expect the same behaviour. Against which versions should I test my patch? So far I'm only on top of main and already seen that the change-log is at 2.5.x. As far as the contribution guide tells me, main is fine? But then I'd like to offer more in case it's wanted, just let me know what would be best.

   [2.0.0-alpha1]: <https://getcomposer.org/changelog/2.0.0-alpha1> "released 2020-06-03 (changlog)"

3. ~~**understanding `COMPOSER_DISABLE_NETWORK=prime`** -- My practical knowledge of this variant is very limited - and current check is for truthyness only (looked it up in the HTTP downloader) if Composer network is disabled and therefore skipping a diagnostic check - but as far as I understand [the value of "`prime`" by the docs](https://getcomposer.org/doc/03-cli.md#composer-disable-network)~~

   > If set to `prime`, GitHub VCS repositories will prime the cache, so it can then be used fully offline with `1`.

   ~~all diagnostic checks should run identical as before and should not be skipped. I already know that the HTTP downloader is not leading for "`prime`" so will modify my patch, just asking for confirmation.~~

   Edit: Irrelevant for diagnose checks, erroneous behaviour is aligned with HTTP Downloader, so the check must be the same.

And yes, the stack traces are really a mess:

<details>

~~~console
$ COMPOSER_DISABLE_NETWORK=1 composer diagnose
Composer version 2.6-dev+f605389dc3101c903081ed0e95f9a872a8bfc930 (2.6-dev) 2023-08-16 12:05:14
Checking composer.json: WARNING
The version field is present, it is recommended to leave it out if the package is published on Packagist.
Checking platform settings: OK
Checking git settings: OK git version 2.34.1
Checking http connectivity to packagist: Unhandled promise rejection with Composer\Downloader\TransportException: Network disabled, request canceled: http://repo.packagist.org/packages.json in phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php:326
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php(296): Composer\Util\HttpDownloader->startJob()
#1 phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php(110): Composer\Util\HttpDownloader->addJob()
#2 phar:///usr/local/bin/composer/src/Composer/Command/DiagnoseCommand.php(265): Composer\Util\HttpDownloader->get()
#3 phar:///usr/local/bin/composer/src/Composer/Command/DiagnoseCommand.php(104): Composer\Command\DiagnoseCommand->checkHttp()
#4 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(298): Composer\Command\DiagnoseCommand->execute()
#5 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#6 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#7 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(382): Symfony\Component\Console\Application->doRun()
#8 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun()
#9 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(145): Symfony\Component\Console\Application->run()
#10 phar:///usr/local/bin/composer/bin/composer(88): Composer\Console\Application->run()
#11 /usr/local/bin/composer(30): require('...')
#12 {main}
FAIL
[Composer\Downloader\TransportException] Network disabled, request canceled: http://repo.packagist.org/packages.json
Checking https connectivity to packagist: Unhandled promise rejection with Composer\Downloader\TransportException: Network disabled, request canceled: https://repo.packagist.org/packages.json in phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php:326
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php(296): Composer\Util\HttpDownloader->startJob()
#1 phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php(110): Composer\Util\HttpDownloader->addJob()
#2 phar:///usr/local/bin/composer/src/Composer/Command/DiagnoseCommand.php(265): Composer\Util\HttpDownloader->get()
#3 phar:///usr/local/bin/composer/src/Composer/Command/DiagnoseCommand.php(107): Composer\Command\DiagnoseCommand->checkHttp()
#4 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(298): Composer\Command\DiagnoseCommand->execute()
#5 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#6 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#7 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(382): Symfony\Component\Console\Application->doRun()
#8 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun()
#9 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(145): Symfony\Component\Console\Application->run()
#10 phar:///usr/local/bin/composer/bin/composer(88): Composer\Console\Application->run()
#11 /usr/local/bin/composer(30): require('...')
#12 {main}
FAIL
[Composer\Downloader\TransportException] Network disabled, request canceled: https://repo.packagist.org/packages.json
Checking github.com oauth access: Unhandled promise rejection with Composer\Downloader\TransportException: Network disabled, request canceled: https://api.github.com/ in phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php:326
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php(296): Composer\Util\HttpDownloader->startJob()
#1 phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php(110): Composer\Util\HttpDownloader->addJob()
#2 phar:///usr/local/bin/composer/src/Composer/Command/DiagnoseCommand.php(330): Composer\Util\HttpDownloader->get()
#3 phar:///usr/local/bin/composer/src/Composer/Command/DiagnoseCommand.php(118): Composer\Command\DiagnoseCommand->checkGithubOauth()
#4 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(298): Composer\Command\DiagnoseCommand->execute()
#5 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#6 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#7 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(382): Symfony\Component\Console\Application->doRun()
#8 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun()
#9 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(145): Symfony\Component\Console\Application->run()
#10 phar:///usr/local/bin/composer/bin/composer(88): Composer\Console\Application->run()
#11 /usr/local/bin/composer(30): require('...')
#12 {main}
FAIL
[Composer\Downloader\TransportException] Network disabled, request canceled: https://api.github.com/
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: Unhandled promise rejection with Composer\Downloader\TransportException: Network disabled, request canceled: https://getcomposer.org/versions in phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php:326
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php(296): Composer\Util\HttpDownloader->startJob()
#1 phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php(110): Composer\Util\HttpDownloader->addJob()
#2 phar:///usr/local/bin/composer/src/Composer/SelfUpdate/Versions.php(112): Composer\Util\HttpDownloader->get()
#3 phar:///usr/local/bin/composer/src/Composer/SelfUpdate/Versions.php(89): Composer\SelfUpdate\Versions->getVersionsData()
#4 phar:///usr/local/bin/composer/src/Composer/Command/DiagnoseCommand.php(429): Composer\SelfUpdate\Versions->getLatest()
#5 phar:///usr/local/bin/composer/src/Composer/Command/DiagnoseCommand.php(157): Composer\Command\DiagnoseCommand->checkVersion()
#6 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(298): Composer\Command\DiagnoseCommand->execute()
#7 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#8 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#9 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(382): Symfony\Component\Console\Application->doRun()
#10 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun()
#11 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(145): Symfony\Component\Console\Application->run()
#12 phar:///usr/local/bin/composer/bin/composer(88): Composer\Console\Application->run()
#13 /usr/local/bin/composer(30): require('...')
#14 {main}
FAIL
[Composer\Downloader\TransportException] Network disabled, request canceled: https://getcomposer.org/versions
Composer version: 2.6-dev+f605389dc3101c903081ed0e95f9a872a8bfc930
PHP version: 8.2.9
PHP binary path: /usr/bin/php
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
cURL version: 7.81.0 libz 1.2.11 ssl OpenSSL/3.0.2
zip: extension present, unzip present, 7-Zip present (7z)
~~~

</details>

**Comment by ktomk** [comment]
For what it's worth and after I've realized that the "prime" value is irrelevant for the `diagnose` command - it needs to be aligned with the HTTP Downloader to prevent the exact reason of the stack-traces, I've filed the current patch as PR #11597.

This is how it looks like (from a test with _"disable-tls": true_):

~~~console
$ COMPOSER_DISABLE_NETWORK=1 ../../composer/bin/composer --version
Composer version 2.6.999-dev+source @release_date@
$ COMPOSER_DISABLE_NETWORK=1 ../../composer/bin/composer diagnose
You are running Composer with SSL/TLS protection disabled.
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK git version 2.34.1
Checking http connectivity to packagist: SKIP Composer network is disabled by COMPOSER_DISABLE_NETWORK=1.
Checking https connectivity to packagist: SKIP Composer network is disabled by COMPOSER_DISABLE_NETWORK=1.
Checking github.com oauth access: SKIP Composer network is disabled by COMPOSER_DISABLE_NETWORK=1.
Checking disk free space: OK
Composer version: 2.6.999-dev+source
PHP version: 8.2.9
PHP binary path: /usr/bin/php
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
cURL version: 7.81.0 libz 1.2.11 ssl OpenSSL/3.0.2
zip: extension present, unzip present, 7-Zip present (7z)
~~~

And for those who prefer colors:

![Selection_298](https://github.com/composer/composer/assets/352517/49f9649c-7ed1-464a-84a9-7002e67f802c)

Raise any concerns here on more general matters or request code changes on the PR itself as you see fit.

**Comment by ktomk** [comment]
Could it be that must have been recently then?

In any case, here after I updated the PR from your feedback another screenshot with an allow_url_fopen=0 test:

![image](https://github.com/composer/composer/assets/352517/79ef5f1c-2ff6-42b1-a9e5-7d3bab1c4372)

It shows how those checks look like with the new SKIP messages. @Seldaek

**Comment by ktomk** [comment]
> Yes I fixed this earlier today.

That's nice. Hopefully I could contribute a little to it, now as everything is merged seeing the commit message is out of date for _that_ part which nudged me most (as so often with docs, isn't it?) But most importantly the improvement is in.

Thanks again for all your hard work @Seldaek

What about other major.minors? I've quickly checked with 2.2 and 2.5 and it's a cherry pick, but regardless, what actually is the current doing/wanting for back porting or what are the current channels? I'd love to see this in other versions, too, but this is merely a wish, I can always take the composer version I need, but I've also noticed that there is value to pin the composer version for stable project builds.

More specifically the reason I ask about other versions is, because I'd like to make use of `diagnose` more general, e.g. having it within build pipelines of the many kinds including offline steps (compare #11300 just for one potential use case that is not entirely mine) so that build logs can easily capture the view of environment / platform specs in a composer'esque manner.

Now given matrix builds across different PHP versions (php >= 5.3.3 - or was it 5.3.6 now for Composer?), to do this sanely (= not ignoring exit status < 2 with `diagnose`), to be transparent from my current understanding, it would at least need to be in the 2.2 branch (and all other upwards to the extend what humble yours policy is).

By the way, I like the summary `diagnose` gives, it is quite useful for PHP related (build) stuff in general, and often already at hand, too!

**Comment by Seldaek** [comment]
I can look at backporting for 2.2, but the other branches are EOL. My goal is releasing 2.6.0 asap right now.

**Comment by ktomk** [comment]
> I can look at backporting for 2.2, but the other branches are EOL. My goal is releasing 2.6.0 asap right now.

Thanks.
