### ISSUE TITLE
Failed requirement 'lib-libsodium' does not provide enough information to resolve

### ISSUE THREAD

**Issue by thg2k** [composer/composer#11592]
Using current version 2.5.8 I get the following output from composer install/update:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - lib-libsodium is present at version 1.0.17 and cannot be modified by Composer
    - You can only install one version of a package, so only one of these can be installed: lib-libsodium[1.0.17].
```

This does not provide any useful information. I would expect to see:
1) Which package is requiring a different version (there is nothing in the composer.json file)
2) Which version I am supposed to install
3) If composer itself is requiring a different version, why?

**Comment by fredden** [comment]
@thg2k it seems that the [issue template on GitHub](https://github.com/composer/composer/blob/main/.github/ISSUE_TEMPLATE.md) has been ignored, which makes helping you much more difficult. Please can you follow the instructions at the top of that template. You can see the text here: https://raw.githubusercontent.com/composer/composer/main/.github/ISSUE_TEMPLATE.md

When you have provided some more information (like a `composer.json` file and the command you ran to get that output, with `-vvv` added as instructed), we may be able to help you further.
