### ISSUE TITLE
Define constrained compatibility with package without install 

### ISSUE THREAD

**Issue by dennisverspuij** [composer/composer#11610]
Hi, I have a question I could not find an answer for nor here, in the documentation, and elsewhere, sorry if I overlooked.

Lets say **my/library** can optionally accept and do things with stuff from **some/dependency: _constraints_**. I can declare this compatibility by adding the dependency with given constraints to the **require** section of my composer.json. But when an application requires **my/library** this would actually install **some/dependency** (and all its dependencies recursively). My question is, how can I prevent this from happening when using **some/dependency** is actually entirely optional? In this case I would rather want the application to require the dependency itself - within the constraints - if it actually wants to use it.

It is not just disk space that is wasted at that point, the dependency might introduce constraints on other libraries that do not need to be there when the dependency is not used.

Of course I would add the dependency to my **require-dev** with conformant constraints to write unit tests with it.
And I would add the dependency to the **suggest**, which is meant for this.
But neither would prevent an application from requiring my library together with a version of the dependency that is incompatible with my library.

So in fact I might be looking for a new composer section **"compatible"**: { "my/library": "_constraints_" }. ?

Thanks for consideration!

**Comment by stof** [comment]
Use `conflict` to forbid incompatible versions of `my/library`

**Comment by dennisverspuij** [comment]
> Use `conflict` to forbid incompatible versions of `my/library`

Indeed, the inverse a bit counterintuitive, but this is it I overlooked, thanks!
