### ISSUE TITLE
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 5.6.30. in C:\phpServer\Laravel\Project1\vendor\composer\platform_check.php on line 25

### ISSUE THREAD

**Issue by lalos1234** [composer/composer#11628]
My `composer.json`:

```json
...replace me...
```

Output of `composer diagnose`:

```
...replace me...
```

When I run this command: 

```
...replace me...
```

I get the following output: 

```
...replace me...
```

And I expected this to happen:

**Comment by lalos1234** [comment]
I created a Laravel project using composer. I installed composer in PHP v 8.2. Once I open my public file, it shows the mentioned error.

**Comment by Seldaek** [comment]
You need to run with PHP 8.1 or above, it seems your web server is configured to run with PHP 5.6, which is very old..

**Comment by gilangrizkyr** [comment]
PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.30. in C:\laragon\www\belajar1\vendor\composer\platform_check.php on line 24

**Comment by xabbuh** [comment]
@gilangrizkyr Run Composer using PHP 8.1 instead of 8.0.
