### ISSUE TITLE
Adjust the rules in the ConfigValidator

### ISSUE THREAD

**Issue by chrfritsch** [composer/composer#11625]
Hi,

I want to adjust the rules of the `ConfigValidator::class` used in the `ValidateCommand::class` in my composer plugin, but I don't see any possibility.

Do I miss something?

**Comment by stof** [comment]
What do you mean by "I want to adjust the rules" ?

**Comment by chrfritsch** [comment]
I would like to change some checks of the `ValidatingArrayLoader::class` because they do not apply to my project.

And as far as I can see, all these classes `ValidateCommand::class`, `ConfigValidator::class`, and `ValidatingArrayLoader::class` are very tightly coupled and there is no possibility to adjust some checks inside.

**Comment by stof** [comment]
Well, there is indeed no extension points for plugins in those places right now.
Which checks would you like to disable ?

**Comment by chrfritsch** [comment]
I would like to disable the unbound version constraint for some packages, but not for all. And I would like to validate that "packagist : false" is set in the repository section since we are maintaining our own composer endpoint.

**Comment by chrfritsch** [comment]
What should the extension points for this look like? I would be happy to provide a PR

**Comment by Seldaek** [comment]
Ignoring unbound version constraints I'd rather not even allow this, there is no good reason for this IMO.

As for checking for packagist:false, I guess you could hook into the command event with a plugin to check before validate runs, but you could also simply run your own validation after `composer validate` in your CI, that'd probably be a lot simpler to achieve.
