### ISSUE TITLE
make PrePoolCreateEvent $packages array keyed by package name

### ISSUE THREAD

**Issue by joachim-n** [composer/composer#11637]
The PrePoolCreateEvent class has an array of packages, but this and thus the return value of getPackages() is keyed numerically.
It would be useful to have this keyed by package name.

My use case is that I want to tweak the requirements of all drupal-module type packages so they will install when the drupal/core package is set to a development branch. I'd like to check the current version of drupal/core. Currently, that requires an additional loop through all of $packages to find the drupal/core package.

**Comment by stof** [comment]
In a pool, you can have multiple packages with the same package name (with different versions). So this is not possible.

**Comment by Seldaek** [comment]
Yeah IMO this cannot be changed in a BC way. Also if you want to check the current version you probably should query `$composer->getRepositoryManager()->getLocalRepository()->findPackages('drupal/core')` instead. That will give you one or more packages (if there are version aliases involved) to check.

**Comment by joachim-n** [comment]
Ah ok. 
How do you get a $composer from inside a script? I assumed my only point of access was the event object, and I can't see a method on that.

**Comment by joachim-n** [comment]
It's a script defined in the root composer.json: https://github.com/joachim-n/drupal-core-development-project/blob/main/src/ComposerCoreVersionsLeniency.php

There's no way to get information about currently-installed versions in that code?

I could make it a plugin that installs from the same codebase with a relative path repo, but that's more fiddly!

**Comment by Seldaek** [comment]
Well maybe it works if drupal/core 11.x is required i guess you'll have a strict require for that and not any other drupal versions loaded in the pool, then you can know for sure it'll be installed in that version

**Comment by stof** [comment]
@joachim-n in pre-pool-create, you cannot know the version of the package that will be installed as this is **before** the solver is running to choose it (the pool being created is the *input* of the solver)

**Comment by joachim-n** [comment]
I mean the version of packages which are already installed.

The problem my script is trying to solve is that when drupal/core is installed from a path repo and on branch 11.x, Composer will quite rightly refused to install packages which require 'drupal/core: ^10'. So I want to check what version the installed drupal/core is.

**Comment by stof** [comment]
Well, the resolution of package is explicitly designed to avoid depending on what is already installed in your vendor directory, because that caused lots of issues in Composer 1.x

However, note that a path repository is not the same than an installed package. It will impact the list of available packages in the pool before the solver is run.
To be compatible with different setups, your script should account for the fact that the list of packages could contain *multiple* versions of `drupal/core` (when using a path repository, you would only have one, but for other cases, there would be multiple).
