### ISSUE TITLE
I can't require php-ml/php-ai

### ISSUE THREAD

**Issue by Osemensilas** [composer/composer#11645]
I keep getting this error while trying to require php-ml/php-ai using composer:
https://repo.packagist.org could not be fully loaded (curl error 6 while downloading https://repo.packagist.org/packages.json: Could not resolve host: repo.packagist.org), package information was loaded from the local cache and may be out of date

**Comment by stof** [comment]
This looks like a network issue on your side as the DNS resolution fails.
