### ISSUE TITLE
Sometimes new package version isn't getting updated to, unless you manually force to update that package

### ISSUE THREAD

**Issue by hostep** [composer/composer#11641]
This is on a Magento project, but I'm using a mirror repository that doesn't require authentication, so this is reproducible without having to register an account.

My `composer.json`:

```json
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "config": {
        "allow-plugins": {
            "dealerdirect/phpcodesniffer-composer-installer": true,
            "laminas/laminas-dependency-plugin": true,
            "magento/*": true,
            "php-http/discovery": true
        },
        "preferred-install": "dist",
        "sort-packages": true
    },
    "version": "2.4.6-p2",
    "require": {
        "magento/product-community-edition": "2.4.6-p2",
        "magento/composer-root-update-plugin": "~2.0",
        "magento/composer-dependency-version-audit-plugin": "~0.1"
    },
    "autoload": {
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ],
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "psr-0": {
            "": [
                "app/code/",
                "generated/code/"
            ]
        },
        "psr-4": {
            "Magento\\": "app/code/Magento/",
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/"
        }
    },
    "require-dev": {
        "allure-framework/allure-phpunit": "^2",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.7",
        "dg/bypass-finals": "^1.4",
        "friendsofphp/php-cs-fixer": "^3.8",
        "lusitanian/oauth": "^0.8",
        "magento/magento-coding-standard": "*",
        "magento/magento2-functional-testing-framework": "^4.3.1",
        "pdepend/pdepend": "^2.10",
        "phpmd/phpmd": "^2.12",
        "phpstan/phpstan": "^1.9",
        "phpunit/phpunit": "^9.5",
        "sebastian/phpcpd": "^6.0",
        "symfony/finder": "^5.4",
        "sebastian/comparator": "<=4.0.6",
        "symfony/process": "<=v5.4.23"
    },
    "conflict": {
        "gene/bluefoot": "*"
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\PhpStan\\": "dev/tests/static/framework/Magento/PhpStan/",
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/"
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true,
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo-magento-mirror.fooman.co.nz/"
        }
    ],
    "extra": {
        "magento-force": "override"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
The version field is present, it is recommended to leave it out if the package is published on Packagist.
Defining autoload.psr-0 with an empty namespace prefix is a bad idea for performance
require.magento/product-community-edition : exact version constraints (2.4.6-p2) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK git version 2.42.0
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest snapshot version, run `composer self-update` to update (2.6.2 => 3bc72f75cbfc43b25ba4fb6013449b69cf29fc66)
Composer version: 2.6.2
PHP version: 8.2.9
PHP binary path: /opt/local/bin/php82
OpenSSL version: OpenSSL 3.1.2 1 Aug 2023
cURL version: 8.2.1 libz 1.3 ssl OpenSSL/3.1.2
zip: extension present, unzip present, 7-Zip not available
```

Steps to reproduce:
```
$ composer install
$ ...
$ composer show magento/magento-coding-standard | grep version
versions : * 31
$
$ composer update --dry-run
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package sebastian/phpcpd is abandoned, you should avoid using it. No replacement was suggested.
132 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found
$
$ composer update magento/magento-coding-standard --with-all-dependencies
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 2 installs, 2 updates, 9 removals
  - Removing symfony/polyfill-ctype (v1.28.0)
  - Removing symfony/polyfill-intl-grapheme (v1.28.0)
  - Removing symfony/polyfill-intl-idn (v1.28.0)
  - Removing symfony/polyfill-intl-normalizer (v1.28.0)
  - Removing symfony/polyfill-mbstring (v1.28.0)
  - Removing symfony/polyfill-php72 (v1.28.0)
  - Removing symfony/polyfill-php73 (v1.28.0)
  - Removing symfony/polyfill-php80 (v1.28.0)
  - Removing symfony/polyfill-php81 (v1.28.0)
  - Upgrading magento/magento-coding-standard (31 => 32)
  - Locking phpcsstandards/phpcsutils (1.0.8)
  - Upgrading rector/rector (0.15.25 => 0.17.12)
  - Locking symfony/polyfill (v1.28.0)
$
$ composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 9 installs, 2 updates, 2 removals
  - Removing phpcsstandards/phpcsutils (1.0.8)
  - Removing symfony/polyfill (v1.28.0)
  - Downgrading magento/magento-coding-standard (32 => 31)
  - Downgrading rector/rector (0.17.12 => 0.15.25)
  - Locking symfony/polyfill-ctype (v1.28.0)
  - Locking symfony/polyfill-intl-grapheme (v1.28.0)
  - Locking symfony/polyfill-intl-idn (v1.28.0)
  - Locking symfony/polyfill-intl-normalizer (v1.28.0)
  - Locking symfony/polyfill-mbstring (v1.28.0)
  - Locking symfony/polyfill-php72 (v1.28.0)
  - Locking symfony/polyfill-php73 (v1.28.0)
  - Locking symfony/polyfill-php80 (v1.28.0)
  - Locking symfony/polyfill-php81 (v1.28.0)
```

This is kinda weird, there is a version 32 of magento/magento-coding-standard, however composer only wants to update to it when explicitly asking it to, and not with a regular 'update' command. Also once it's at 32 and you run a full 'update' it downgrades it again to version 31.
If I have to guess, it may have something to do with that symfony/polyfill package that replaces all those individual ones.
It's not really expected in my opinion, but maybe there is a reason for this behavior? Or is this a bug?

Tested with:
- composer 2.5.8
- composer 2.6.2
- composer snapshot 3bc72f75cbfc43b25ba4fb6013449b69cf29fc66

**Comment by hostep** [comment]
See my `composer.lock` file in attachment (in case some new versions of packages get released in the future that no longer make this a valid report)

[composer.txt](https://github.com/composer/composer/files/12601185/composer.txt)

**Comment by Seldaek** [comment]
I cannot explain this with 100% certainty but I believe it is due to the fact magento/magento-coding-standard 32 requires symfony/polyfill which replaces all other polyfills, and version 31 requires no polyfill, but then various polyfills are installed by dependencies. Then the solver somehow prefers the solution with v31, but if you update only that package then it upgrades it to 32 and drops the individual polyfills.

Both solutions are technically valid, but I'm not sure why the v31 one is preferred.

In any case, changing the requirement to `>=32` instead of `*` resolves the problem.

**Comment by Seldaek** [comment]
For reference, here is the smallest repro case:

```
{
    "config": {
        "allow-plugins": false
    },
    "require": {
        "magento/product-community-edition": "2.4.6-p2"
    },
    "require-dev": {
        "magento/magento-coding-standard": "31|32",
        "magento/magento2-functional-testing-framework": "4.3.4"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo-magento-mirror.fooman.co.nz/"
        }
    ]
}
```

In this state it resolves magento/magento-coding-standard to 31. 

Doing `composer up magento/magento-coding-standard -W --dry-run` after it always upgrades to 32.

Removing either of the other two dependencies solves it as well (upgrades magento/magento-coding-standard to 32).

Unfortunately both magento/product-community-edition and magento/magento2-functional-testing-framework have a TON of dependencies, so it makes this minimal case still not that minimal.

**Comment by hostep** [comment]
Thanks for the research and tips everybody. The info has been passed to the Magento team.
The [ticket](https://github.com/magento/magento-coding-standard/issues/467) Christophe created is indeed an alternate solution that most likely will fix this as well.

@Seldaek : do you want me to close the issue, or do we leave it open to figure it out one day if this can be improved in composer? (although it sounds like this might be complex to figure out)

**Comment by stof** [comment]
this looks complex to figure out because Composer is technically right here: it selects a valid solution. It probably comes down to the order in which it selects packages. It looks like composer first made a decision to use one of the individual polyfill packages and tries to find a solution this way. As it finds one, it does not backtrack to use the solution involving the replacer package.
When composer is selecting the `magento/magento-coding-standard` version first, it tries first to use its highest version and this leads to selecting a different solution. And the partial update which unlocks `magento/magento-coding-standard` and its dependencies probably uses a different order of decisions in the solver.

Note that this is the same kind of root cause why composer could still select a dev version even when using `--prefer-stable`, even if choosing a different (older) release of another package could allow to find a solution involving only stable packages.

**Comment by Seldaek** [comment]
It's very odd, if I replace the `magento/magento2-functional-testing-framework` require by its requirements, then everything works fine for example.. Must really be some oddball solver behavior where the order of things make it take this path and then it finds a valid solution and stops there. I doubt we can fix this so I will close, hopefully magento moves to the proper polyfill package which perhaps fixes it.

Just for reference, I stripped down the requirements from `magento/magento2-functional-testing-framework` to just the one that makes it fail, but that one still has quite a bit of transitive dependencies so it is still a huge set of packages.

Should keep doing this down the tree until we can isolate things to just a few packages then maybe we could reason about it.. but it is very time consuming so I'll stop here :)

```
{
    "config": {
        "allow-plugins": false
    },
    "require": {
        "magento/product-community-edition": "2.4.6-p2"
    },
    "require-dev": {
        "magento/magento-coding-standard": "31|32",
        "magento/magento2-functional-testing-framework": "4.3.4"
    },
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "magento/magento2-functional-testing-framework",
                "version": "4.3.4",
                "require": {
                    "allure-framework/allure-phpunit": "^2"
                }
            }
        },
        {
            "type": "composer",
            "url": "https://repo-magento-mirror.fooman.co.nz/"
        }
    ]
}
```

**Comment by Seldaek** [comment]
> changing the requirement to `>=32` instead of `*` resolves the problem.

And finally just a last note, doing this would be preferable from a performance point of view as it makes sure composer will not look at all 31 previous versions and all their dependencies, so it reduces the scope of packages quite a bit.
