### ISSUE TITLE
Warn if ext-json is listed

### ISSUE THREAD

**Issue by ro0NL** [composer/composer#11651]
> As of PHP 8.0.0, the JSON extension is a core PHP extension, so it is always enabled.

Would be nice if composer tells us when listed :)

**Comment by javiereguiluz** [comment]
It seems that there's no option to disable the bundling of the JSON extension when compiling PHP from source (See https://www.php.net/manual/en/configure.about.php). So, it looks like you can't have PHP without `ext-json` even if you compile it from source.

**Comment by ro0NL** [comment]
This also applies to `ext-spl` etc.

Im not sure if composer wants to maintain the list? :pleading_face:

**Comment by ro0NL** [comment]
i've filtered them out :)
