### ISSUE TITLE
Check if all latest stable packages are allowed by root composer.json

### ISSUE THREAD

**Issue by mvorisek** [composer/composer#11656]
In our projects, we manually add a compatible packages like:
```
"psr/log": "^1.0",
```

but when next major version (v2.0) is released, we have to notice it first, eg. monitor the all deps or wait until someone reports it.

This is a feature request to be able to use composer directly in CI (in develop branch) to check if the allowed deps permit all latest stable deps.

The expected result is a non-zero exit code of composer command if the allowed deps by root composer.json does not permit one or more latest deps to be installed.

**Comment by GromNaN** [comment]
`composer outdated` is able to tell you if a new version available. Is it enough for this need?
https://getcomposer.org/doc/03-cli.md#outdated

**Comment by mvorisek** [comment]
> `composer outdated`

The command has every option I need to be supported, thank you!
