### ISSUE TITLE
Do not create another time bomb

### ISSUE THREAD

**Issue by chx** [composer/composer#11655]
https://getcomposer.org/changelog/2.6.3

> Added audit.abandoned config setting. Can be set to ignore, report (current default) or fail (future default in 2.7)

composer 2.7 will, again, fail builds. This will result in a rehash of  https://github.com/composer/composer/issues/10912

do not do this.

Rather, version composer.json

**Comment by Seldaek** [comment]
Composer will fail builds for people running `audit` explicitly with failure checks and having abandoned packages and not reading warnings or changelogs for a few months.. Given audit is still newish I think this is acceptable. Also it is not a time-bomb it is a new-minor-version bomb, that is very different IMO. You may disagree, or you may just set the new config to the desired value now so you don't have problems when the default changes.
