### ISSUE TITLE
Create configuration for scripts to directly accept all the arguments without argument escaping `--`

### ISSUE THREAD

**Issue by kaznovac** [composer/composer#11661]
This would be helpful for frameworks to expose their cli tools via composer (I like to have single entry point for project - something like old Makefiles)

let this be composer.json
```json
{
  "scripts": {
    "app": [
      "@php bin/console"
    ]
  },
  "scripts-pass-arguments": [
    "app"
  ]
}
```

or something like
```json
{
  "scripts": {
    "app": [
      "Composer\\Config::passArguments"
      "@php bin/console"
    ]
  }
}
```

so I can call `composer app cache:clear` instead of `composer app -- cache:clear` or `composer -- app cache:clear`

--

the other approach would be when composer is given script as an argument all composer arguments are required to be before the script name. e.g.
`composer app --version` would return app version, but `composer --version app` will return composer version  (this is quite common, for example `docker` uses this approach)

**Comment by Seldaek** [comment]
Composer is a dependency manager though, we have a few helpful things like that which can be convenient for simple things, but if you need a complex CLI IMO it makes more sense to build your own entry point like Symfony has `bin/console` for example.

It just is very complex to make this work IMO, especially as we rely on symfony/console for the arg parsing we do have some limitations.

What you can try doing though is having `"app": "src/MyConsoleCommand.php"` as script, and that class would be a symfony Command class. You can then accept any argument/params as input (See Composer's GlobalCommand for an example), and then execute the bin/console script with the proper args as an external process.

Accepting `--version` after tho will not work as this gets handled by symfony/console before composer commands ever get called..
