### ISSUE TITLE
Ability to ignore dependency inversion for libraries

### ISSUE THREAD

**Issue by boesing** [composer/composer#11671]
Hey there,

as a library developer, I wonder if it is possible to "ignore" dependency inversion somehow.
We do have `laminas/laminas-cache` which requires a specific `laminas/laminas-cache-storage-implementation`.
So only components like `laminas/laminas-cache-storage-adapter-redis` are providing (via `provide`) these dependencies.

We now also have other satellites, such as `laminas/laminas-cache-storage-adapter-test` and `laminas/laminas-cache-storage-adapter-benchmark`. 
These are used to provide benchmark and test dependencies to each adapter.
Those packages only require `laminas/laminas-cache` as they interact with interfaces provided by the base cache component.
Sadly, due to the dependency inversion of `laminas/laminas-cache`, those components (`test` and `benchmark`) do also have to require at least one of the cache adapters.

I do have two solutions now:

- require-dev one of the adapter to fulfill dependency inversion (thats what we are doing right now)
- create a dummy adapter within the package and use that via `require-dev`

The current solution leads to problems whenever we want to upgrade major versions of the base package (`laminas/laminas-cache`)  as then, usually the `require-dev` dependencies are not migrated or vice-versa.

I wonder if the best and recommended solution would be to have a dummy package registered in a dedicated folder which is not populated with the component to upstream but consumed during CI, etc.

Another thought was  to actually ignore `provide` in non-`project` type components?

Would love to have some feedback about this topic.
Thanks in advance.

----

My `composer.json`:

```json
{
     "name": "vendor/package",
     "type": "library",
     "require": {
         "laminas/laminas-cache": "^3.11"
     }
}
```

**Comment by stof** [comment]
`provide` in non-project types is a totally valid use case. So ignoring it would break the ecosystem.

**Comment by boesing** [comment]
What I mean is, I do not want to provide anything in non-project if downstream requires an implementation. 
Imho it breaks the ecosystem more if libraries require (I.e. via dev) an implementation and work against that rather than against the contract.

**Comment by fredden** [comment]
@boesing you may like to investigate adding https://github.com/maglnet/ComposerRequireChecker to your workflow.

**Comment by stof** [comment]
To me, it looks like the root cause of the issue is that `laminas/laminas-cache` forces you to install an implementation instead of letting you install only the interface. And this is something to be solved (or rejected) by laminas

**Comment by boesing** [comment]
The component itself makes no sense without an implementation but maybe I'll change that with the next major as most projects are now using implementations. 
But imho thats still a common use-case or do we use it wrong? 🤔

**Comment by stof** [comment]
Well, for projects, an implementation is indeed needed to be useful. But for _libraries_, it might totally make sense to install only the package defining interface (to have type checking and to potentially mock the interface directly instead of using a mock implementation).
For instance, none of the psr packages defining their interfaces are requiring their corresponding implementation virtual package.

**Comment by boesing** [comment]
That is what I am talking about.
In libraries, I do not want to fulfill the virtual package requirements as that would require me to require (at least via `require-dev`) a concrete implementation.
In projects, I see the virtual packages to be required as a MUST.

But maybe we (I) used dependency inversion incorrect and should have omitted the virtual package in `laminas-cache` (https://github.com/laminas/laminas-cache/blob/76cc49af422a9cf5deff9cd0f63cbda29ae88d14/composer.json#L38) in the first place.

**Comment by Seldaek** [comment]
As far as I understand your issue (of which I am really not sure..) I think the conclusion is correct that laminas/laminas-cache should not require an implementation of it's own interfaces. Things that require an implementation to function should require that virtual package. If laminas-cache does require an implementation to function (which is very possible, I just have no clue), then the require is fine, but then sure you'll have to update the required versions across implementors when a major changes happens.. I still don't really get the problem there.

If you want more help maybe it'd help if you show the dependency graph you have before/after a major version upgrade, like

- laminas-cache:
  - requires X
- providers:
  - provides X
  - requires X

Then maybe with the overview it makes a bit more sense to us who are not familiar with laminas and all those package names and whatever satellites you speak of.

**Comment by boesing** [comment]
`laminas-cache` can function on its own but it would be useless until a concrete cache backend provides an actual implementation.

So yes, I can require `laminas-cache` without anything else and nothing will break. But it will be a useless component to projects as laminas-cache without a cache backend is unable to cache anywhere.

So we have all those cache backends in dedicated satellites:
- redis
- memcache
- mongodb
- etc.

Those satellites do require `laminas-cache` to actually:
- implement the `StorageInterface`
- `provide` via `composer.json` the actual `laminas/laminas-cache-storage-implementation`

Those satellites do **also** require `laminas-cache-storage-adapter-test` and `laminas-cache-storage-adapter-benchmark` to have shared tests and shared benchmarking logic for CI.

`laminas-cache-storage-adapter-test` and `laminas-cache-storage-adapter-benchmark` do require `laminas-cache` to actually "consume" the `StorageInterface`.

Since `laminas-cache` does require the virtual package `laminas/laminas-cache-storage-implementation`, both benchmark and test components do have to somehow ensure that this requirement is fulfilled (i.e. requiring one of the real implementations such as `redis`, `memcache`, etc.).

Now the dependency graph would look like:

- `laminas-cache`
   - requires: `laminas-cache-storage-implementation`
- `laminas-cache-storage-adapter-redis`
   - provides: `laminas-cache-storage-implementation`
   - requires: `laminas-cache-storage-adapter-test`
   - requires: `laminas-cache-storage-adapter-benchmark`
-  `laminas-cache-storage-adapter-benchmark`
  - requires: `laminas-cache`
  - requires transitive `laminas-cache-storage-implementation` due to the requirement to `laminas-cache` and therefore requires (dev) i.e.`laminas-cache-storage-adapter-redis`
- `laminas-cache-storage-adapter-test`
  - requires: `laminas-cache`
  - requires transitive `laminas-cache-storage-implementation` due to the requirement to `laminas-cache` and therefore requires (dev) i.e.`laminas-cache-storage-adapter-redis`


Bumping `laminas-cache` to a new major now requires the following flow:

1. bump `laminas-cache` to new major
2. go into  `laminas-cache-storage-adapter-benchmark` and bump `laminas-cache`
    1. will break  due to incompatibility with transitive `laminas-cache-storage-implementation` which has to be fulfilled by requiring `laminas-cache-storage-adapter-redis`
    2. but okay, lets bump `laminas-cache-storage-adapter-redis` then to support new major of `laminas-cache`
        1. will break due to incompatibility with `laminas-cache-storage-adapter-benchmark` as it does not support new major version of `laminas-cache` which cannot be properly supported since it has to require `laminas-cache-storage-adapter-redis` (circular dependency)

**Comment by fredden** [comment]
Perhaps the way forward here is to move `laminas-cache-storage-implementation` from "require" to "suggest" within `laminas-cache`. Each of the "adaptor" packages are correct to **require** `laminas-cache` as this contains the interfaces that they implement. (ComposerRequireChecker would complain about this if it were missing.) However, `laminas-cache` itself doesn't strictly **require** any implementation, but **suggest**ing an implementation seems helpful. Yes, `laminas-cache` won't be very useful _by itself_, but neither is `psr/log` useful _by itself_ / without a corresponding implementation.
