### ISSUE TITLE
PHPStan 1.10.37 

### ISSUE THREAD

**Issue by greew** [composer/composer#11679]
The newest PHPStan version 1.10.37 creates an invalid error in `src/Composer/Command/DiagnoseCommand.php`.

You can see that they acknowledge the eror in https://github.com/phpstan/phpstan/compare/1.10.36...1.10.37#diff-f82562b3295f9d8749ee0ff7a565948e494f758b66507e14db92e4088c209f7dR3. 

What do you think the fix should be:

- Adding // @phpstan-ignore-next-line on the line
- Updating the baseline.neon file?

**Comment by stof** [comment]
To me, this is a bug in phpstan. The key `xdebug_profile` could exist in the `$warnings` array: https://github.com/composer/composer/blob/64c5bdd55b7d95d263c87b5a1c6e187b3f0ac01e/src/Composer/Command/DiagnoseCommand.php#L589

**Comment by Seldaek** [comment]
Yup, I just saw this failure and will report this to phpstan

**Comment by greew** [comment]
@stof I absolutely agree. I just mentioned it, because they clearly already know this, and have ignored the error in their own repo.

**Comment by greew** [comment]
Both me and my colleague ran into it with #11677 and #11678 , so I just wanted to let you know of it :)

**Comment by stof** [comment]
Well, ignorting it in their own repo was the wrong decision IMO. They missed the opportunity to recognize that their new version was buggy.
In the meantime, it is better to use the baseline than the comment IMO.

**Comment by ondrejmirtes** [comment]
Hello everyone, I'm sorry, I glanced at the report and thought it's a legit issue in Composer source code. I'll welcome a bug report about this with a reproduction, thank you 😊

**Comment by greew** [comment]
@ondrejmirtes Done - I hope it's an easy fix! :) 

https://github.com/phpstan/phpstan/issues/9985
