### ISSUE TITLE
Error messages for private packages

### ISSUE THREAD

**Issue by MaximilianKresse** [composer/composer#11673]
We host our own private repository for our customers. The repository requires an authentication and not every user is allowed to download every package. 

Previously an error message looked like this:

```
In CurlDownloader.php line 630:

  The "https://test-domain/downloads/670464/test-package.zip" file could not be downloaded (HTTP/1.1 404 No valid license found.)

```

We "mis-used" the http status reason text here to show an individual error message why the package couldn't be downloaded. But because we updated our web server and we do now support HTTP/2 the reason text is not anymore available. Currently the error message looks like this:
```
In CurlDownloader.php line 630:

  The "https://test-domain/downloads/670464/test-package.zip" file could not be downloaded (HTTP/2 404 )

```

Is it currently possible to display any custom error messages if a package cannot be downloaded?

And if not - is it possible to get an option for this? Maybe an extra http header could be used for this like 'Composer-Error'. 
Are you open for a pull request in this direction?

**Comment by adeildo-jr** [comment]
We are getting the same error but for public repositories instead. I think this is a Github issue.

**Comment by yassinebridi** [comment]
This might be related to this: #8710

**Comment by vtsykun** [comment]
Seems you may put the message in JSON response, insead of using custom message in HTTP response status code

```
In CurlDownloader.php line 630:
                                                                                                                                                              
  The "https://demo.packeton.org/zipball/okvpn/packeton/425ebaf4f906993bbb792f37d7fa88be2fb361a8.zip" file could not be downloaded (HTTP/2 404 ):  
  {"status":"error","message":"No valid license found"}     
```

**Comment by stof** [comment]
When the error response uses a JSON content-type, Composer already displays it (well, it displays the first 200 bytes of the response so keep your message short): https://github.com/composer/composer/blob/d2bd9836a604f5b475013c077706e6dc6f420e35/src/Composer/Util/Http/CurlDownloader.php#L626-L628

**Comment by MaximilianKresse** [comment]
Ok thank you - this works! I didn't found it in the code.
