### ISSUE TITLE
Inclusions of git pack files when installing via git

### ISSUE THREAD

**Issue by gms8994** [composer/composer#11680]
We recently hit #11662 which caused composer to fall back to downloading/installing things via the `git clone` method.

```
17:34:26  Downloading https://api.github.com/repos/phpstan/phpstan/zipball/e4545b55904ebef470423d3ddddb74fa7325497a
17:34:26  [403] https://api.github.com/repos/phpstan/phpstan/zipball/e4545b55904ebef470423d3ddddb74fa7325497a
17:34:26  Executing command (CWD): git config github.accesstoken
17:34:26      Failed to download phpstan/phpstan from dist: Could not authenticate against github.com
17:34:26      Now trying to download from source
17:38:10    - Installing phpstan/phpstan (1.10.28): Cloning e4545b55904ebef470423d3ddddb74fa7325497a
17:38:10  Executing command (CWD): git clone --no-checkout -- 'https://github.com/phpstan/phpstan.git' '/var/www/html/vendor/phpstan/phpstan' && cd '/var/www/html/vendor/phpstan/phpstan' && git remote add composer -- 'https://github.com/phpstan/phpstan.git' && git fetch composer && git remote set-url origin -- 'https://github.com/phpstan/phpstan.git' && git remote set-url composer -- 'https://github.com/phpstan/phpstan.git'
17:41:01  Executing command (/var/www/html/vendor/phpstan/phpstan): git remote set-url --push origin -- 'git@github.com:phpstan/phpstan.git'
17:41:01  Executing command (/var/www/html/vendor/phpstan/phpstan): git branch -r
17:41:01  Executing command (/var/www/html/vendor/phpstan/phpstan): (git checkout '1.10.28' -- || git checkout -B '1.10.28' 'composer/1.10.28' --) && git reset --hard 'e4545b55904ebef470423d3ddddb74fa7325497a' --
```

This leads to files like `vendor/phpstan/phpstan/.git/objects/pack/pack-8a308b7138496856c9b5f2e982acc202f7bfadcb.pack` in our filesystem which is a file with size `4459569360`.

Is there something that I don't have configured properly? I feel like these files shouldn't be included in the `vendor` folder. If I'm configured correctly, is there a safe way to clean these up when this happens?

<details>
<summary>composer.json (truncated for brevity and security)</summary>

```
{
    "require": {
        "ext-json": "*",
        "ext-filter": "*",
        "ext-gd": "*",
        "ext-zip": "*",
        "ext-pdo": "*",
        "ext-curl": "*",
    },
    "config": {
        "optimize-autoloader": true,
        "platform": {
            "php": "8.2.6"
        },
        "allow-plugins": {
            "phpro/grumphp": true
        }
    },
    "require-dev": {
        "phpstan/phpstan": "^1.0"
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}
```

</details>

<details>
<summary>composer download and install instructions</summary>

```
RUN curl -sS https://getcomposer.org/installer -o composer-setup.php \
    && php composer-setup.php --version=2.6.4 \
    && mv composer.phar /usr/local/bin/ \
            && ln -s /usr/local/bin/composer.phar /usr/local/bin/composer

RUN git config --global url."https://github.com/".insteadOf 'git@github.com:'
RUN composer install --prefer-dist --no-interaction -o -vvv --no-cache
```

</details>

**Comment by gms8994** [comment]
As a note, phpstan isn't the only repo that is affected in this way - `aws/aws-sdk-php`, `phpmyadmin/sql-parser`, `mockery/mockery`, `giggsey/libphonenumber-for-php`, `phpseclib/phpseclib`, `guzzlehttp/guzzle` and more; those are just the pack files that were over 1mb in our resulting docker image.

**Comment by gms8994** [comment]
I don't know if this is somehow related or not, but we later have a webpack compilation step that failed on build attempts that fell down to `git clone`:

```
14:44:48  ERROR in /var/www/html/vendor/phpstan/phpstan/playground-api/handler.ts
14:44:48  1:51-65
14:44:48  [tsl] ERROR in /var/www/html/vendor/phpstan/phpstan/playground-api/handler.ts(1,52)
14:44:48        TS2307: Cannot find module '@sentry/node' or its corresponding type declarations.
14:44:48  ts-loader-default_e3b0c44298fc1c14
14:44:48  
14:44:48  ERROR in /var/www/html/vendor/phpstan/phpstan/playground-api/handler.ts
14:44:48  2:35-44
14:44:48  [tsl] ERROR in /var/www/html/vendor/phpstan/phpstan/playground-api/handler.ts(2,36)
14:44:48        TS2307: Cannot find module 'aws-sdk' or its corresponding type declarations.
14:44:48  ts-loader-default_e3b0c44298fc1c14
```

This, to me, suggests something isn't being set properly somewhere with `git clone`, as when the install via zipball succeeds, we don't receive these messages.

**Comment by stof** [comment]
Well, the `playground-api` folder is probably excluded from the archive in the phpstan repo (as it is about the phpstan website, not about the local usage).
When cloning the repo, this will be on your filesystem (as it is part of the repo content). And my guess is that your webpack compilation tries to compile the typescript code that is in this folder, which looks suspicious to me as config: why would your config automatically discover typescript files in the `vendor` folder to include them in your build ? Your setup should compile your own code.

**Comment by gms8994** [comment]
There's actually nothing in my webpack.config.js or tsconfig.json (or anything else that I can see) that should be including the `vendor` folder.

I'm more pointing out that the `git clone` step is keeping around files that it feels like shouldn't be kept; there are lots of items in `phpstan/phpstan`'s .gitattributes that are marked as `export-ignore`. It feels like (in the fallback to `git clone` scenario only, imho) that there should be a `git archive` step that performs the extract to the `vendor/<package>` folder.

**Comment by stof** [comment]
`git clone` keeps everything that is part of the git repo. Otherwise, the next time composer wants to change the version, it would detect that the git repo has uncommitted changes.

**Comment by gms8994** [comment]
I understand that. I'm not saying not to do `git clone` - I'm saying that in the case of a fallback where `--prefer-dist` is used, there should be a `git archive` step added that performs the extract to `vendor/namespace/package` so that the resulting fileset matches (at least as closely as possible) what would have come from downloading a zipball as the dist.

**Comment by fredden** [comment]
Might it be feasible to use `--depth=1` (to create a shallow clone) when running `git clone`?

**Comment by Seldaek** [comment]
Yeah shallow + git archive would be more equivalent to a dist install, but it'd mean a bunch more complexity in the GitDownloader for an edge case really as normally dist should work.. So I'm not so keen on doing this sorry.
