### ISSUE TITLE
Downloading composer issues

### ISSUE THREAD

**Issue by danillediane04** [composer/composer#11685]
My `composer.json`:

```json
...replace me...
```

Output of `composer diagnose`:

```
...replace me...
```

When I run this command: 

```
...replace me...
```

I get the following output: 

```
<img width="565" alt="Screenshot 2023-10-12 at 12 57 51 PM" src="https://github.com/composer/composer/assets/147760222/bbdf0c77-9ee6-4aea-b2b2-9b6b2ccc0ab3">

...replace me...
```

And I expected this to happen:

I am trying to download composer for the first time and I am getting this message. What am i doing wrong. Thank you 

('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'e21205b207c3ff031906575712edab6f13eb0b361f2085f1f1237b7126d785e826a450292b6cfd1d64d92e6563bbde02') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
zsh: command not found: php
zsh: command not found: php
zsh: command not found: php
zsh: command not found: php

**Comment by emotality** [comment]
Mine just hangs here:

```bash
$ php composer-setup.php --install-dir=/usr/local/bin --filename=composer
All settings correct for using Composer
Downloading...
```

Then I tried downloading it directly with `wget` and it still hanged:

```bash
$ wget https://getcomposer.org/download/2.6.5/composer.phar
--2023-10-19 00:55:24--  https://getcomposer.org/download/2.6.5/composer.phar
Resolving getcomposer.org (getcomposer.org)... 2001:41d0:302:1100::8:104f, 54.36.53.46
Connecting to getcomposer.org (getcomposer.org)|2001:41d0:302:1100::8:104f|:443... ^C                                                                  ~1m:33s  exit:130 
```

Then I saw it's connecting to IPv6, so I forced IPv4, and it worked:

```bash
$ wget https://getcomposer.org/download/2.6.5/composer.phar -4
--2023-10-19 00:57:02--  https://getcomposer.org/download/2.6.5/composer.phar
Resolving getcomposer.org (getcomposer.org)... 54.36.53.46
Connecting to getcomposer.org (getcomposer.org)|54.36.53.46|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2861347 (2.7M) [application/octet-stream]
Saving to: ‘composer.phar’
```

Not sure if it's my side or not? >.<

**Comment by stof** [comment]
See https://getcomposer.org/doc/articles/troubleshooting.md#operation-timed-out-ipv6-issues- for the documented guide on working around IPv6 issues.
But anyway, if the workaround works, the last advice (reporting it to your ISP so that they fix their IPv6 routing) is a good idea.
