### ISSUE TITLE
[RFC] Vendor bundles

### ISSUE THREAD

**Issue by vtsykun** [composer/composer#11682]
This feature helps group packages into vendor bundles to make versions updating more easier. This will be useful in tests when you need to test the application on different framework versions (4.4.*, 5.4.*, 6.4.*) 

### Problem
There is currently no easy way to update framework dependencies together.

```json
{
    "require": {
        "symfony/framework-bundle": "^4.4 || ^5.4 || ^6.0 || ^7.0",
    },
    "require-dev": {
        "symfony/browser-kit": "^4.4 || ^5.4 || ^6.0 || ^7.0",
        "symfony/console": "^4.4 || ^5.4 || ^6.0 || ^7.0",
        "symfony/monolog-bundle": "^3.2"
    }
}
```  

For example, if I want to test the application on Symfony versions 4.4, 5.4, 6.1, 6.4 I need to manually specify the version for each package in the composer update command.
 
```
composer update --with='symfony/browser-kit:5.4.*'  --with='symfony/console:5.4.*' ... ...
```

 1). Example [flysystem-bundle](https://github.com/thephpleague/flysystem-bundle/blob/3.2.0/.github/workflows/test.yaml#L37)

Alternative ways 
2) install 3rd party plugin, depending on framework (like `symfony/flex`) 
3) Use hacks like `sed` to update composer.json  [KnpMenuBundle build](https://github.com/KnpLabs/KnpMenuBundle/blob/v3.2.0/.github/workflows/build.yaml#L67)

### Proposal

I'd like to propose to add `vendor-bundles` to simplify grouping and update packages

```json
{
    "require": {
        "symfony/framework-bundle": "^4.4 || ^5.4 || ^6.0 || ^7.0",
    },
    "require-dev": {
        "symfony/browser-kit": "^4.4 || ^5.4 || ^6.0 || ^7.0",
        "symfony/console": "^4.4 || ^5.4 || ^6.0 || ^7.0",
        "symfony/monolog-bundle": "^3.2"
    },
    "vendor-bundles": {
        "symfony": {
            "env": "SYMFONY_REQUIRE",
            "packages": ["symfony/*", "!symfony/contracts", "!symfony/*-contracts", "!symfony/monolog-bundle"]
        }
    }
}
``` 
Where `!` - means that this package should be excluded, if for some packages the version numbering does not match the framework numbering.

Example Usage:

```bash
composer update --with='symfony:5.4.*'
```

with env using 
```bash
SYMFONY_REQUIRE="5.4.*" composer update
```

**Comment by Seldaek** [comment]
This seems frankly a bit overcomplicated to me, to solve a use case which is valid sure but usually a prefer-lowest + highest build give you already quite a lot of coverage.. And if you want more specific for symfony flex is an option, or doing it like in the flysystem bundle seems reasonable to me.
