### ISSUE TITLE
composer config --unset "repositories.1.exclude" does not work

### ISSUE THREAD

**Issue by chx** [composer/composer#11696]
```
{
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        },
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8",
            "exclude": [
              "drupal/amp"
            ]
        },
```

`composer config --unset "repositories.1"` nukes the entire section but `composer config --unset "repositories.1.exclude` does not remove exclude alone.

**Comment by chx** [comment]
I have been the maintainer of Drupal form API for well over a decade. Nested arrays hold no terror for me :D If you could give me a few pointers of where config unset happens, I could probably take a stab.

**Comment by Seldaek** [comment]
Closing here as I don't think anyone will ever look into this. It's just too fringe.
