### ISSUE TITLE
Stand with Palestine against Israel occupation

### ISSUE THREAD

**Issue by ahmadms-dev** [composer/composer#11707]
Hi
We stand with Ukraine against Russia occupation and we need you to stand with 🇵🇸  against Israel occupation

**Comment by Seldaek** [comment]
Sorry but we are not going to do that. The issue is IMO much more complex than the one of Russia invading Ukraine, and I don't feel comfortable picking sides here.

**Comment by ahmadms-dev** [comment]
It is morral situation here .
 no complexity the situation is a group of people occupate other people land and the occupation kill a thousands of occupated people ,you must have the humanity side.

**Comment by AmjadAldya** [comment]
> Sorry but we are not going to do that. The issue is IMO much more complex than the one of Russia invading Ukraine, and I don't feel comfortable picking sides here.

**You only have to be human to stand with the civilian people whose land and lives were stolen (🇵🇸)
Be free and do not make your humanity dependent on political positions**

**Comment by amjad1233** [comment]
@Seldaek, is your stance still the same? Or do you want the number of Palestinian 🇵🇸 civilians killed to exceed 50k or something?
