### ISSUE TITLE
Factor out the whole file rewrite from JsonConfigSource::manipulateJson into a static helper 

### ISSUE THREAD

**Issue by chx** [composer/composer#11708]
I wrote https://github.com/chx/drupal-issue-fork/blob/main/src/DrupalIssueForkCommand.php and the `writeConfig` method is copy-pasted from `JsonConfigSource::manipulateJson`. Would you accept a PR moving this code into a static helper somewhere, `JsonFile` maybe?

**Comment by Seldaek** [comment]
I guess that sounds ok.. Just the hardest bit as usual is naming it ;) But I'd rather keep it as static func on that class where it is tho btw
