### ISSUE TITLE
Could not find package doctrine/dbal. It was however found via repository search, which indicates a consistency iss   ue with the repository.

### ISSUE THREAD

**Issue by Doombah** [composer/composer#11715]
please help

**Comment by fredden** [comment]
@Doombah please can you fill out the template that you deleted when you created this issue. For reference, you can see a copy of what you removed here: https://raw.githubusercontent.com/composer/composer/main/.github/ISSUE_TEMPLATE.md

Without more information it's incredibly difficult to help you.
