### ISSUE TITLE
Add the time a package was released in `composer show` command

### ISSUE THREAD

**Issue by javaDeveloperKid** [composer/composer#11737]
It would be helpful to output the release time next to the package in `composer show` (or  only when running with `--outdated` option) command to see how old the current packages are. Having this info condensated in the package list would help to draw conclusions whether some packages need upgrade.

I would use the relative time like `1 month ago`(or make it configurable via composer.json `extra` key?) - it better affects humans. I would create a new option to sort desc/asc (from oldest to latest and vice versa) based on release time.

We could also add this info to the output of `composer show <package>`.

We already have info about release time in composer.lock.

**Comment by Seldaek** [comment]
See https://github.com/composer/composer/pull/11762
