### ISSUE TITLE
When to expect composer 2.7?

### ISSUE THREAD

**Issue by keulinho** [composer/composer#11736]
Is there already an ETA for 2.7?

Currently 2.6 is not compatible with symfony 7 when you want to excecute composer commands from inside your symfony 7 application.

The issue was already fixed here: https://github.com/composer/composer/commit/c66894278c03bf88ccae12fa3d8f3a9d68e64495
But the change is only to be released with composer 2.7.

As symfony 7 now is also generally available this incompatibility might affect more and more projects.

**Comment by matthiaz** [comment]
Composer 2.5 does not have the bug, so if you can pin composer to v2.5 (and not 2.6) you should be good to go.
But I agree, 2.7 preferably needs to be rolled out fast.

**Comment by keulinho** [comment]
Even though the bug might not be there, composer 2.5 is not marked as compatible with symfony 7 either:
```
  Problem 1
    - Root composer.json requires composer/composer ~2.5.0 -> satisfiable by composer/composer[2.5.0, ..., 2.5.8].
    - composer/composer[2.5.0, ..., 2.5.8] require symfony/console ^5.4.11 || ^6.0.11 -> found symfony/console[v5.4.11, ..., v5.4.32, v6.0.11, ..., v6.4.0] but it conflicts with your root composer.json require (~7.0.0).
```

**Comment by shawnachieve** [comment]
We're seeing this issue in our CI/CD pipelines which install composer 2.6.x as part of the build process.  Installing a clean 2.6 version of composer installs Symfony 7 which breaks all of the composer commands.

Updating our pipeline to install composer 2.5.8 has temporarily resolved the issue.

**Comment by Seldaek** [comment]
See https://github.com/composer/composer/issues/11741#issuecomment-1847572878

**Comment by keulinho** [comment]
Hey @Seldaek thanks for the update and taking care.

Not sure what is still needed for full symfony 7 support, but the decision to only add support in a new minor version is understandable.

However the "fix" to the 2.6 branch does solve only a particular use case, meaning you require symfony and composer at the same time and then get `symfony/console v6.x`. However another issue still exists that when you require symfony console 7.x explicitly then composer with happily install composer v2.6.5 (the old unfixed version) as that was marked as compatible with symfony console 7.x, leading again to the errors described in https://github.com/composer/composer/issues/11741.

So in that case limiting the supported symfony console versions to 6.x for composer 2.6.6 only makes things worse IMHO. You can't put the genie back in the bottle.

**Comment by Seldaek** [comment]
@keulinho for those that need symfony console 7.x there are two options: Require composer/composer `^2.7@dev` or stop requiring composer because why are you doing this it's usually the wrong thing to do :D

And the reason I don't want to add it in 2.6 is that to support it we need to add return types which technically is a BC break, I don't think it'll affect anyone but if so I still rather break stuff in a minor than a patch release.

**Comment by keulinho** [comment]
As i said that reasoning is understandable. 

Our use case is pretty sure uncommen, but i think valid, as we build a framework based on symfony and wanna upgrade to the latest symfony version, therefore we require symfony 7. And as we provide an extension system based on composer we need to require composer in order to run composer commands from inside the application when you install an extension.

Can you give at least a rough ETA for composer 2.7? That would help us to decide if we can continue with the symfony update or if it needs to wait for our next major release.

**Comment by Seldaek** [comment]
Sorry I have no idea about ETA.. but I guess if this is blocking people I could tag a 2.7 some time in january. We don't have a strict roadmap.

**Comment by keulinho** [comment]
Thanks for the info, that already helps us a lot!

**Comment by Seldaek** [comment]
https://github.com/composer/composer/releases/tag/2.7.0 is out

**Comment by extasy7610** [comment]
symfony/flex v1.18.7 + composer v2.7.0:
`PHP Fatal error:  Declaration of Symfony\Flex\Command\RemoveCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Composer\Command\RemoveCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /usr/local/var/www/xc-ngrok/next/src/service-tool/vendor/symfony/flex/src/Command/RemoveCommand.php on line 30
Fatal error: Declaration of Symfony\Flex\Command\RemoveCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Composer\Command\RemoveCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /usr/local/var/www/xc-ngrok/next/src/service-tool/vendor/symfony/flex/src/Command/RemoveCommand.php on line 30`

**Comment by xabbuh** [comment]
@extasy7610 You need to update Symfony Flex (1.18.7 is quite old, the current release is 2.4.4).

**Comment by extasy7610** [comment]
@xabbuh, yes, I know. It's already done, thank you. I wrote my comment because there are problems with compatibility with new version of composer

**Comment by fredden** [comment]
@extasy7610 see #11839 for the issue you're experiencing.

**Comment by Seldaek** [comment]
This is another issue altogether, it's about the Flex command classes not declaring a return type in this outdated flex version. It has nothing to do with #11839 nor this issue. As @xabbuh wrote you just need to update flex and move on :)

**Comment by Seldaek** [comment]
@romainnorberg you need to update symfony/flex to a more recent version that is compatible with latest Composer & Symfony.
