### ISSUE TITLE
Add colors to problem list in composer require and update

### ISSUE THREAD

**Issue by javaDeveloperKid** [composer/composer#11730]
When installing or upgrading dependencies the problem list might be long enough. Every problem has a set of hyphens that explain what the context of the problem.This hyphen list has positive, negative and informational elements. 
It would be very nice to use colors depending on what type of information it is, because it would help to filter the output out by eye and give a better DX overall. 

Example for `composer update`:
```sh
  Problem 1
    - Root composer.json requires phpunitgen/console ^5.0 -> satisfiable by phpunitgen/console[5.0.0].
    - phpunitgen/console 5.0.0 requires php ~8.0.12 || ~8.1.0 || ~8.2.0 -> your php version (8.3.0RC6) does not satisfy that requirement.
  Problem 2
    - phpspec/prophecy dev-master requires php ^7.2 || 8.0.* || 8.1.* || 8.2.* -> your php version (8.3.0RC6) does not satisfy that requirement.
    - phpspec/prophecy 1.x-dev is an alias of phpspec/prophecy dev-master and thus requires it to be installed too.
    - Root composer.json requires phpspec/prophecy 1.x-dev -> satisfiable by phpspec/prophecy[1.x-dev (alias of dev-master)].
```  

Here we have:
- Problem 1 hyphen 1 is a positive information. It could be green.
- Problem 1 hyphen 2 is a negative information. It could be red.
- Problem 2 hyphen 1 is a negative information. It could be red.
- Problem 2 hyphen 2 is informational. It could be white.
- Problem 2 hyphen 3 is a positive information. It could be green.

**Comment by Seldaek** [comment]
I tried but tbh I don't think it's possible. Some messages are informational in some contexts and the root cause of the problem in other contexts, so highlighting may cause more confusion than anything. The full output is needed and we try to deduplicate useless bits already.. Users will just have to learn to read a bit more than 3 words to find a solution :)
