### ISSUE TITLE
add ability to declare path repositories en masse

### ISSUE THREAD

**Issue by joachim-n** [composer/composer#11732]
I have a local project where I work on Drupal contrib modules. To do so, I clone the module to a ./repos folder, then declare it as a path repo in my project's composer.json like this:

```
        {
            "type": "path",
            "url": "repos/some-module"
        },
```

However, this gets pretty repetitive.

I'd like to be able to declare the parent folder as containing *multiple* path repos like this:

```
        {
            "type": "path",
            "url": "repos"
        },
```

**Comment by joachim-n** [comment]
I was wondering if creating a packages.json file with the `metadata-url` property might work, but it doesn't:

```
  The "repos/drupal/subrequests~dev/composer.json" file could not be downloaded: Failed to open stream:
  No such file or directory
```

It looks like Composer is trying to find a composer.json file for all versions?

**Comment by tobyzerner** [comment]
You can use a glob in the path to include all subdirectories:

```
        {
            "type": "path",
            "url": "repos/*"
        },
```

**Comment by joachim-n** [comment]
Nice! I can confirm this works!

But it's not documented. Should I repurpose this issue, or close this one and open a new one?

**Comment by Seldaek** [comment]
It technically is in the docs:

> **Note:** Repository paths can also contain wildcards like `*` and `?`.
> For details, see the [PHP glob function](https://php.net/glob).

But yeah.. easy to miss. I converted a couple examples to use wildcard, hopefully it makes it a little more visible.
