### ISSUE TITLE
Give plugin events access to Composer and the IO

### ISSUE THREAD

**Issue by joachim-n** [composer/composer#11745]
Events such as PrePoolCreateEvent have Composer\EventDispatcher\Event as their base class.

Script events however, have as parent Composer\Script\Event which is a child of Composer\EventDispatcher\Event. This class adds methods such as getComposer() and getIO().

It would be useful if plugin events had access to these too.

**Comment by joachim-n** [comment]
I'm listening to this event in a script rather than a plugin.

**Comment by Seldaek** [comment]
Yeah that's a problem :)

What's the use case exactly?

**Comment by joachim-n** [comment]
This is an example of a script listening to the PrePoolCreateEvent plugin event: https://github.com/joachim-n/drupal-core-development-project/blob/main/src/ComposerCoreVersionsLeniency.php

I can't remember what I was working on that needed the Composer object - I'll need to dig around my various bits of work in progress.

**Comment by joachim-n** [comment]
I've found the code I was working on. Now I look at it, it could be done as a Composer plugin -- I was developing it as a script because it's easier to just add a script to a project than to create a new package for a plugin, install it, etc -- that's another use case there -- portability between scripts and plugins that listen to the same events.

The use case for my code is perhaps less important, but here it is anyway: Suppose I have a Drupal project which has some Drupal contrib modules installed as Composer packages. I find a bug in one of the modules. I want to fix it, in the context of my project. So the thing to do would be:

1. clone the contrib module's repo
2. add a Composer path repository to the project's composer.json that points to the git clone
3. run composer update for drupal/somemodule, so Composer changes the project's copy of the package to a symlink
4. fix the bug
5. submit a PR to drupal.org
6. switch back to the dist package of drupal/somemodule, and use https://github.com/cweagans/composer-patches to apply the MR diff as a patch, in the hope that the PR is merged and in the future I can switch to a new release and remove the patch.

However, lots of Drupal contrib modules don't have a composer.json file in their git repo. The composer.json is added automatically by drupal.org's packagist (https://packages.drupal.org/8).

So step 3 fails because Composer can't see a package in the git clone.

So I wanted to create a script that acts on the pre-pool-create event to fake a package -- to add a Package object to the pool which says that the drupal/somemodule package is located in the git clone path repository. (I couldn't get it to work BTW but that's a whole other story.)

One of the things I needed in this script was access to the project's composer.json, to check whether the current pre-pool-create event was for a Drupal module which has a path repository defined in the composer.json -- hence the need for the Composer object.

**Comment by fredden** [comment]
Could you ignore Composer for a moment to create the patch? I've done this on other occasions, where I go to into `vendor/` and replace the relevant directory with a `git clone ...` and then create a patch which is (submitted upstream and then) applied with composer-patches (vaimo or cweagans).

Something like:
- `composer update drupal/somemodule`
- `cd vendor/drupal/somemodule`
- `find -delete`
- `git clone git@github.com:drupal/somemodule.git .` (note the important `.` at the end)
- `git remote rename origin upstream`
- `git add remote origin git@github.com:yourname/drupal-somemodule.git`
- fix the bug
- open pull request
- add a `patches` section (or modify the existing) to add the new patch with `https://github.com/drupal/somemodule/pull/11745.diff` as the patch file
- remove the locally-modified version with `rm -rf vendor/drupal/somemodule` - this step might not be strictly necessary.
- `composer update drupal/somemodule` (to make sure that the `content-hash` is updated)

Adding a `git` repository source for such a time-limited task seems overkill. Adding a Composer script to support this workflow seems overkill.

**Comment by joachim-n** [comment]
That's the sort of workflow I've used before -- in the root of the project I'll create two folders, 'composer moved' and 'git clones' and I'll swap package folders in and out of those two.
But it's a bit fiddly, and in my experience, if Composer sees a git clone in /vendor when you do a Composer operation like a require or update, it thinks it can do what it wants with it. The technique of using a path repository and a symlink while working on a fix is better, as Composer doesn't make any changes to git clone it symlinks in like that.
Also, I can define a single path repo of 'repos/*' and anything beneath that is taken to be a path repo, so I don't need to add a new repo.

> Adding a Composer script to support this workflow seems overkill.

I'm a programmer, I like to automate things! :)
