### ISSUE TITLE
`composer require --dry-run` creates composer.json if not exist

### ISSUE THREAD

**Issue by takaram** [composer/composer#11747]
My `composer.json`: does not exist

When I run `composer require --dry-run psr/log` (or any other packages), the command runs successfully, but it creates `composer.json`.

```console
$ ls -a
.  ..
$ composer --version
Composer version 2.6.5 2023-10-06 10:11:52
$ composer require --dry-run psr/log
./composer.json has been created
Running composer update psr/log
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking psr/log (3.0.0)
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing psr/log (3.0.0)
No installed packages - skipping audit.
Using version ^3.0 for psr/log
$ ls -a
.  ..  composer.json
$ cat composer.json
{
}
```

I expect dry-run not to create/modify any files.

**Comment by takaram** [comment]
[This line](https://github.com/composer/composer/blob/da83d29d8ac634783bc70b0f3b7847bae3e081d9/src/Composer/Command/RequireCommand.php#L143) creates the file. It does not respect `dry-run` flag.

**Comment by Seldaek** [comment]
Right, the file is needed at runtime even in dry run mode we cannot really do without it, but it will now be deleted after the run is complete.
