### ISSUE TITLE
Segmentation fault php8.2 installing composer

### ISSUE THREAD

**Issue by Theprim0** [composer/composer#11740]
`php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"`

This commands returns:

`Segmentation fault (core dumped)`

**Comment by fredden** [comment]
I've been able to reproduce the segfault with just running `php -i` in the reported environment, which suggests this isn't anything to do with Composer.

**Comment by ToguyC** [comment]
If even running `php -i` in the environment raise a segfault it might be a more problematic issue :sweat_smile:.
Would it be interesting to report it even higher in the chain like to PHP or xdebug ? (I don't think xdebug accepts issues atm tho)

**Comment by stof** [comment]
they do: http://xdebug.org/reporting-bugs

**Comment by paul-thebaud** [comment]
Hello,
I got the same problem today on a Docker image building.
