### ISSUE TITLE
composer82 remove axyr/silverstripe-flashmessage

### ISSUE THREAD

**Issue by erangaddd** [composer/composer#11759]
I have installed the package axyr/silverstripe-flashmessage using the command composer82 require axyr/silverstripe-flashmessage

The package did not functioned as I expected. So I have removed the package using composer82 remove axyr/silverstripe-flashmessage.

Then I realised that all the content in the root folder also has been deleted.  Please check the package content and make sure it has a bug. 

Log:
$ composer82 remove axyr/silverstripe-flashmessage
./composer.json has been updated
Running composer update axyr/silverstripe-flashmessage
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 0 updates, 1 removal
  - Removing axyr/silverstripe-flashmessage (0.0.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 0 updates, 1 removal
  - Removing axyr/silverstripe-flashmessage (0.0.2)
    Uninstall of axyr/silverstripe-flashmessage failed

In Filesystem.php line 314:

  Could not delete /themes/newgoldmountain:

remove [--dev] [--dry-run] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|-                                                -update-with-dependencies] [-W|--update-with-all-dependencies] [--with-all-dependencies] [--no-update-with-dependencies] [--unused] [--ign                                                ore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader                                                ] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]

**Comment by GromNaN** [comment]
This package uses a custom installer, that doesn't seems to be in composer/installers package.
https://github.com/axyr/silverstripe-flashmessage/blob/4ea72c2d3d1305204d1fae0d4db3ff954fab4828/composer.json#L28

You should report to the package author.

**Comment by erangaddd** [comment]
@alcohol Sorry for the mistake. It was actually the project folder. The **composer remove** command has no way deleting the project but after I run composer82 remove axyr/silverstripe-flashmessage it deleted everything in my project folder. Quite strange. I do not know what content you should check but I am a bit worried that how it happened and someone else may also face this.

**Comment by fredden** [comment]
I have tried to reproduce this by running `composer require axyr/silverstripe-flashmessage` in an empty directory. After this runs, I have the two expected `composer.json` and `composer.lock` files, as well as the `vendor/` directory. In addition to these, there is a `resources/` directory.

After running `composer remove axyr/silverstripe-flashmessage`, the contents of the `resources/` directory remains unchanged.

@erangaddd please can you share some more information about your set-up? The template that you removed when creating this issue on GitHub asks for the contents of `composer.json`, for example. It may also be useful to include any globally-installed Composer plug-ins which may be manipulating files outside of Composer's normal operations.

**Comment by erangaddd** [comment]
@fredden I did exactly what you have done. I am using this on Silverstripe. 

It was a strange incident. I have never seen the composer command do such thing. By the way I will try to install the plugin again later and will report more information if it happens again. 

Thank you.
