### ISSUE TITLE
What artifact to check within a Composer project?

### ISSUE THREAD

**Issue by theofidry** [composer/composer#11751]
Hi! Hopefully an easy question!

In the context of [Box](https://github.com/box-project/box), I need to extract some information about the packages used by the project. Back in the days there was only `composer.json` and potentially `composer.lock` and if I recall correctly there was cases where the `composer.lock` was not created (e.g. if you had no dependencies).

Since then a lot changed, the format of the `composer.lock` evolved and there is `installed.{json,php}`. I am wondering what artefacts should be taken for getting the following information:

- The extensions used*
- The extensions provided*
- The conflicting extensions*
- The PHP version required*

*: for the project as a whole, i.e. for both the project root and its dependencies. Figuring out the final output of it (e.g. that `ext-iconv` is not necessary because a polyfill is not desired (Box need to do that later with details as to who requires/provides/conflicts with what).

Which artefacts should I take a look at?

**Comment by stof** [comment]
what box could do is turning on the generation of the full platform checks, which will then be executed when loading the composer autoloader.

Note that installed.php should be included in the phar in case the project relies on the composer runtime API.

**Comment by theofidry** [comment]
Thanks for the answers and suggestions, I'll work with that.
