### ISSUE TITLE
problem in install composer-setup.exe on win10

### ISSUE THREAD

**Issue by MrEveryThingSafdar** [composer/composer#11752]
![Untitled](https://github.com/composer/composer/assets/106355034/20bdcb58-2d19-4318-ad5b-994aa4980556)

I have a problem with install composer

its version is latest, I downloaded it now from https://getcomposer.org/download/

my internet connection is ok, it's ok with loading sites.

I disabled proxy on my windows 10.

I turned off firewall 

I don't know what I have to do else!!! please help me
![Untitled](https://github.com/composer/composer/assets/106355034/40d31dbd-a9b1-4354-b6a1-360eea88937c)

**Comment by johnstevenson** [comment]
Please open an issue here: https://github.com/composer/windows-setup/issues/new and we will try to help.

**Comment by johnstevenson** [comment]
Issue resolved: https://github.com/composer/windows-setup/issues/156
