### ISSUE TITLE
Option to disable fund message

### ISSUE THREAD

**Issue by shyim** [composer/composer#11765]
I would love to have an option like `--no-fund` like on [NPM](https://docs.npmjs.com/cli/v7/commands/npm-install#fund) to disable that message and the data aggregation.

I just like to have my terminal output clean 😅

**Comment by alcohol** [comment]
> the data aggregation

Can you elaborate?

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/pull/11779
