### ISSUE TITLE
Suggestion: How about automatic hash generation for download scripts?

### ISSUE THREAD

**Issue by debiru** [composer/composer#11778]
## Suggestion

https://getcomposer.org/download/ says the following:

```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'e21205b207c3ff031906575712edab6f13eb0b361f2085f1f1237b7126d785e826a450292b6cfd1d64d92e6563bbde02') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
```

How about automatic generation of the hash part?

```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === file_get_contents('https://composer.github.io/installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
```

If you dare to write the hash directly, please tell me why.

## Background

Someone has written the installation manual for composer in an another document, but the hash part is written directly, and the version upgrade has created a situation where that script does not work as expected. This is due to the fact that https://getcomposer.org/download/ describes the hash directly.

Wouldn't it be useful to automatically generate the hash part so that the script can be used forever?

**Comment by fredden** [comment]
> write the hash directly, please tell me why.

Listing the hash directly means that it can be verified more easily / better. Here are some benefits off the top of my head:
- There are multiple ways of generating a hash of a file. (eg, Using the `sha384sum` command on many GNU/Linux systems.)
- It allows verifying the hash offline. (Although running the installer needs a connection, so this is a weak argument.)
- It's possible to verify that the expected hash is the same from multiple network locations / devices. It is possible for a compromised device to display an incorrect hash to create a false sense of security for the user of that device.

> Someone has written the installation manual for composer in an another document

Please refer them to the warning on the page they have attempted to reproduce:

![Screenshot_2023-12-27_09-05-36](https://github.com/composer/composer/assets/334786/b78ae7e8-83b9-4eb5-82ff-5551a9c192d0)

> automatically generate the hash part so that the script can be used forever?

The instructions you are reading are a quick-start guide for humans to follow. If you are looking to automate the installation process, there's [a dedicated page for that](https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md) linked at the top of [the page you are looking at](https://getcomposer.org/download/).

![Screenshot_2023-12-27_08-58-11](https://github.com/composer/composer/assets/334786/364a7e31-901c-41f3-a834-60a5c8473e97)

**Comment by debiru** [comment]
@fredden 

Thank you for your advice! It was very helpful for me.

> The instructions you are reading are a quick-start guide for humans to follow. If you are looking to automate the installation process, there's [a dedicated page for that](https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md) linked at the top of [the page you are looking at](https://getcomposer.org/download/).

I missed that description. The page mentioned something about automate the installation process.

Please forget about my suggestion.
