### ISSUE TITLE
Allow composer to run with files other than composer.json.

### ISSUE THREAD

**Issue by t-terashima0815** [composer/composer#11776]
Allow different packages to be used within the same project by specifying a file name suffix.

Option name
Full name: --file-suffix
Abbreviation: -S

If "temp" is specified as the suffix

* composer.json
* composer.lock
* vendor/

These will be renamed as follows

* composer-temp.json
* composer-temp.lock
* vendor-temp/

**Comment by t-terashima0815** [comment]
Sorry, this feature is so difficult.
I can't develop it.

**Comment by Seldaek** [comment]
You can use the COMPOSER env var to control the name and full path of the composer.json, or --file

So `COMPOSER=composer-temp.json composer install` will use composer-temp.json and composer-temp.lock. The vendor dir you would have to rename yourself by setting vendor-dir: vendor-temp in composer-temp.json though.
