### ISSUE TITLE
Feat: Show which repository was used to obtain metadata

### ISSUE THREAD

**Issue by vtsykun** [composer/composer#11799]
I have 3 private composer repositories in composer.json config and sometimes it is difficult to understand which repository was used to install a package. I want to have a feature that shows the selected repository to get metadata for each package.

For example
```
composer info --repos
```

```
willdurand/jsonp-callback-validator             v1.1.0    https://packagist.com/acme
willdurand/negotiation                        3.1.0       https://packeton.org
xemlock/htmlpurifier-html5                      v0.1.10   https://repo.packagist.org
```

**Comment by Seldaek** [comment]
We cannot do this as we do not retain this information at all. Packages have no reference to their source repository after they're installed.

**Comment by vtsykun** [comment]
Ok I understood, then we can dynamic show which repositories will be used as if we had executed the update command. I can create a PR for this feature if this solution is acceptable

**Comment by Seldaek** [comment]
Yeah maybe it's doable, but it would not necessarily match what happened at the time you created the lock file, so I am not sure about the value of this.
