### ISSUE TITLE
Add support to configure the preferred protocol on composer type repositories

### ISSUE THREAD

**Issue by MajPay** [composer/composer#11808]
When hosting your own instance of gitlab and using the composer repository you have to add a composer type repository to your composer.json

```json
{
  "repositories": {
    "name": {
      "type": "composer",
      "url": "https://your.gitlab/api/v4/group/groupname/-/packages/composer/packages.json"
    }
  }
}
```

gitlab added the support with https+token authentication some time ago and everything worked perfectly.

With a recent change gitlab introduced a breaking change by changing the source url in their repository json to the git-url. So you need to be able to authenticate via ssh. Composer supports that but in our use-case we run php/composer inside docker and dont want that container to connect via ssh. So we want to force the https+token url.

I already opened a issue in the gitlab tracker, they should rollback their change, so everything continues to work. But in my opinion the best option would be a repository config in my composer.json because in one scenario i may want to run natively and simply connect via ssh and in another situation i would prefer to use the https+token protocol.

The gitlab issue i opened: https://gitlab.com/gitlab-org/gitlab/-/issues/438698

My proposed change for composer itself would be something like:

```json
{
  "repositories": {
    "name": {
      "type": "composer",
      "url": "https://your.gitlab/api/v4/group/groupname/-/packages/composer/packages.json",
      "protocol": "https"
    }
  }
}
```

I am going to reference this issue on gitlab as well.

**Comment by Seldaek** [comment]
Yeah sorry this sounds like a lot more complexity than I'd like to deal with, given the small edge case here.

I'm just gonna say that at [private packagist](https://packagist.com/) we do not pull breaking changes on our users, and we support dists which should download faster anyway than cloning everything.
