### ISSUE TITLE
Sort root entries in composer.json

### ISSUE THREAD

**Issue by javaDeveloperKid** [composer/composer#11804]
We have `config.sort-packages` option but we don't have any option for sorting root keys of composer.json schema, e.g. `sort-keys: true` or sth. I have to admit I'm really tired of reading different composer.json files where every has keys in different order. I know some IDEs are smart enough to search for json keys just like for methods in PHP class but it's not always practical or some people just like to read the actual file content, not the popup GUI provided by IDE. Also let's remember about cases outside of IDE like code reviews or online VSC repositories).

Wouldn't this be nice to have it formated phisically in the file?

Optional: extend this feature to every nested option, e.g.
```json
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true,
        // allow-plugins should be first
        "allow-plugins": {
            "symfony/flex": true
        }
    },
```

**Comment by fredden** [comment]
You may be interested in https://github.com/ergebnis/composer-normalize

**Comment by Seldaek** [comment]
Yeah please use composer-normalize if this is something you care about, I don't want to replicate all that work nor maintain it :)
