### ISSUE TITLE
sudo composer self-update segmentation fault

### ISSUE THREAD

**Issue by utqinadhif** [composer/composer#11815]
![image](https://github.com/composer/composer/assets/10701527/cdc26821-98e3-4aa7-b5bf-d558837f41a8)

sudo composer self-update segmentation fault

Os: debian
Repo: php.sury.org
Php version: 8.3

**Comment by fredden** [comment]
@utqinadhif please can you provide some more information. The information you have currently provided isn't enough to help you.
Here's a set of example questions:
- What PHP version are you running? Is this the same version used when you use `sudo`?
- What version of Composer are you running? Where is this located on disk?
- What operating system / platform are you using (Linux, Windows Subsystem for Linux, MacOS)?
- Can you reliably run other `php` scripts as root?
- Does Composer work as expected when not run as root?
- Does Composer work as expected when run as root? (Other than the self-update command which seems to be causing you issues.)

**Comment by utqinadhif** [comment]
> @utqinadhif please can you provide some more information. The information you have currently provided isn't enough to help you. Here's a set of example questions:
> 
> * What PHP version are you running? Is this the same version used when you use `sudo`?
> * What version of Composer are you running? Where is this located on disk?
> * What operating system / platform are you using (Linux, Windows Subsystem for Linux, MacOS)?
> * Can you reliably run other `php` scripts as root?
> * Does Composer work as expected when not run as root?
> * Does Composer work as expected when run as root? (Other than the self-update command which seems to be causing you issues.)

Edited

**Comment by fredden** [comment]
> Edited

I can't reproduce with the information provided. I am using Debian 12 with PHP v8.3.2 (from the sury repository) and Composer v2.6.6. I have no problem running PHP scripts as my user and as root, and running `composer self-update` (and `sudo composer self-update`) reports success.

**Comment by utqinadhif** [comment]
so, that's error because i'm installed php8.3-swoole, after remove swoole, its work! sorry
