### ISSUE TITLE
should give more control to the user

### ISSUE THREAD

**Issue by djh42** [composer/composer#11823]
I just downloaded composer and ran

$ php composer.phar global require "linc/nitro-porter"

It said

"Cannot use linc/nitro-porter's latest version v3.3.0 as it requires php >=8.0 which is not satisfied by your platform."

and then proceeded to "Installing linc/nitro-porter (v2.5)"

IMHO, it should have stopped and given me the choice of aborting the installation (since v2.5 won't do what I need). Installing an old version without giving the user control is BAD! Now I need to go clear up the mess.

**Comment by xabbuh** [comment]
If you omit the version number, you are telling Composer to choose a version that matches your environment:

> If you do not specify a version constraint, composer will choose a suitable one based on the available package versions.

If you want to tell composer which version it should install (if possible), you can pass a version constraint like this: `php composer.phar global require "linc/nitro-porter:^3.3"`

**Comment by djh42** [comment]
Thanks. Where do I find the text you quoted?

And what if the composer.json contradicts the command line? I presume the command line wins? Are the rules specified somewhere?

**Comment by xabbuh** [comment]
The quoted paragraph is part of the output of `composer require -h`.

Your `composer.json` file is modified according to what you call `require` with.
