### ISSUE TITLE
Got error during creating a step for flow

### ISSUE THREAD

**Issue by Omkartomar93** [composer/composer#11820]
### Discussed in https://github.com/composer/composer/discussions/11819

<div type='discussions-op-text'>

<sup>Originally posted by **Omkartomar93** January 29, 2024</sup>
Hey ... i got this error on my console -   RingleSoft\LaravelProcessApproval\ProcessApproval::createStep(): Argument #1 ($flowId) must be of type int, string given, called in C:\php8\htdocs\Prog-HRM\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 356
</div>

**Comment by xabbuh** [comment]
Your error does not look related to Composer. You should rather seek for help in one of the Laravel support channels.

**Comment by Seldaek** [comment]
Sorry but this does not seem related to Composer at all.
