### ISSUE TITLE
Composer prefer lowest does not stop running

### ISSUE THREAD

**Issue by dereuromark** [composer/composer#11834]
See https://github.com/dereuromark/cakephp-geo/actions/runs/7828997507/job/21360025738
It is the cake4 branch only (not master) for some reason

The command is https://github.com/dereuromark/cakephp-geo/blob/a85771296f2d152b43accad680174b6f1511b7d8/.github/workflows/ci.yml#L60

I made a PR for easier test run: https://github.com/dereuromark/cakephp-geo/pull/74

**Comment by stof** [comment]
Are you sure that the failing command is the one you linked or `composer require --dev dereuromark/composer-prefer-lowest:dev-master` that you also run in the same step of the workflow for prefer-lowest ? Can you try splitting that as 2 different steps to know which one is failing ?

**Comment by stof** [comment]
Btw, I suggest you to cancel this job to stop the infinite loop of execution (which will also allow us seeing the beginning of the logs)

**Comment by Seldaek** [comment]
From the log here https://github.com/dereuromark/cakephp-geo/actions/runs/7828997507/job/21360025738 - it seems to be running an update in a loop.

```
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package laminas/laminas-zendframework-bridge is abandoned, you should avoid using it. No replacement was suggested.
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
Generating autoload files
35 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

This block repeats forever..

So I am not sure, it looks to me like maybe you have a buggy plugin that does an update at the end of an update, and ends up looping forever, probably they fixed it in a newer version but with --prefer-lowest you get a buggy version.

You could confirm with `--no-plugins` if that fixes it.. Then look at which plugins are enabled and try to figure out what is causing this.

**Comment by dereuromark** [comment]
--no-plugins doesnt seem to fix it

**Comment by Seldaek** [comment]
So I tried locally and --no-plugins does fix it. I narrowed it down to https://github.com/php-http/discovery/pull/214 which fixed it in php-http/discovery 1.15.1, so all releases before that are borked and endless loop. 

This is pulled in via:

geocoder-php/common-http 4.4.0 requires php-http/discovery (^1.6)

I don't know what you can do about it except add a conflict rule for `php-http/discovery <1.15.1`. I'd also let geocoder know so that they bump their requirement to a version that is not borked.

**Comment by dereuromark** [comment]
Thanks a lot!
I guess also not much composer itself can do to prevent a never ending loop
I just imagine that pipelines that run on money per minutes, it could become quite expensive over night ;)

**Comment by Seldaek** [comment]
Yeah, I mean if a plugin wants to run and endless loop there is not much we can do about it :P
