### ISSUE TITLE
Error when running composer-setup.php

### ISSUE THREAD

**Issue by mosleim** [composer/composer#11837]
My `php --version`:

```
PHP 8.3.2 (cli) (built: Jan 16 2024 13:46:41) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.2, Copyright (c), by Zend Technologies
```

Output of `php composer-setup.php`:

```
PHP Parse error:  syntax error, unexpected token "::", expecting variable in mypath/lara/composer-setup.php on line 1341

Parse error: syntax error, unexpected token "::", expecting variable in mypath/lara/composer-setup.php on line 1341
```

or when i use bash script:

```
Installer verified
PHP Parse error:  syntax error, unexpected token "::", expecting variable in /Users/mosleim/codes/rsud-waluyo-jati/lara/composer-setup.php on line 1341

Parse error: syntax error, unexpected token "::", expecting variable in /Users/mosleim/codes/rsud-waluyo-jati/lara/composer-setup.php on line 1341
```

code on line 1341:

```
class HttpClient {

    /** @var null|string */
    private static self::$caPath;  <------------- line: 1341

    private $options = array('http' => array());
    private $disableTls = false;
```

**Comment by jdavidbakr** [comment]
I'm getting this as well, running php 8.2.

**Comment by vkoudela** [comment]
Same here. Running PHP 8.1.

**Comment by matheusjohannaraujo** [comment]
That's right!

Just run this: ```php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"```

And you get this damn ```self::$caPath;```

**Comment by erdemkeren** [comment]
Same with 7.4

**Comment by dereuromark** [comment]
`https://getcomposer.org/installer` itself seems broken and causes this.

**Comment by davelima** [comment]
Same here. Last entry on the Composer changelog is of 2023-12-08 tho, that's really weird

**Comment by ThomasBerends** [comment]
The installer is in another repo. Issue here: https://github.com/composer/getcomposer.org/pull/230

Possibly fixed according to that issue.

**Comment by serge-tseiko** [comment]
fixed in https://github.com/composer/composer/issues/11835

**Comment by Seldaek** [comment]
It's fixed now, sorry for the trouble 😅  It was simply a typo I missed in an installer script change, the composer.phar file was fine.

**Comment by mosleim** [comment]
i can install with some changes ini setup-composer.php

```
class HttpClient {

    /** @var null|string */
    private static $caPath;   <------------- this line: 1341
    
 ```

**Comment by ImAARIX** [comment]
Great! It was fixed quickly!
