### ISSUE TITLE
Document Plugin API version bump

### ISSUE THREAD

**Issue by InvisibleSmiley** [composer/composer#11838]
It seems the plugin API version was bumped from 2.3.0 to 2.6.0 in Composer version 2.6.0:
https://github.com/composer/composer/commit/16bdfe4dae0d6ef151d71441849e735f3b0a93c8

That is however neither reflected in the 2.6.0 release notes:
https://github.com/composer/composer/releases/tag/2.6.0
nor the changelog:
https://github.com/composer/composer/blob/main/CHANGELOG.md?plain=1#L68
nor in the plugin documentation:
https://github.com/composer/composer/blob/main/doc/articles/plugins.md?plain=1#L42

**Comment by Seldaek** [comment]
I updated the docs and release now, but I don't really see why this is such a problem? I would be curious to hear what the trouble was, if it's more than just purely for correctness.

**Comment by InvisibleSmiley** [comment]
I was trying to install a plugin which stated that it cannot be installed with Composer plugin API versions beyond 2.2.x.
Turned out that was [on purpose](https://github.com/laminas/laminas-dependency-plugin/issues/61) but at the time I was very confused because the official Composer plugin documentation stated that the latest version was 2.3.0 and none of the changelogs mentioned any version bump. So it appeared like a bug to me. That's all.

**Comment by Seldaek** [comment]
Ok I see, thanks and sorry for the confusion :)
