### ISSUE TITLE
getcomposer.org/installer fails this morning (with output)

### ISSUE THREAD

**Issue by dcaillon** [composer/composer#11835]
When my Bitbucket pipeline CI script runs this command :
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

it fails this morning (successfull on previous days) :

PHP Parse error:  syntax error, unexpected token "::", expecting variable in Standard input code on line 1341

Any other way to install Composer ?
Thanks ;)

**Comment by ubi-fcornu** [comment]
Same

And nothing new on the GA changelog. Which is even weirder

**Comment by hdomos** [comment]
Same for me

**Comment by serge-tseiko** [comment]
```php
class HttpClient {

    /** @var null|string */
    private static self::$caPath; 
```

**Comment by lgladdy** [comment]
@dcaillon Any chance you could update this issue title to something more global, not just about docker so folks can find it and not open dupes?

**Comment by serge-tseiko** [comment]
PHP Parse error: syntax error, unexpected token "::", expecting variable in Standard input code on line 1341

Any other way to install Composer ?

```bash
curl -sS https://getcomposer.org/installer | ack 's/private static self::\$caPath;/private static $caPath;/' | php -- --install-dir=/usr/local/bin --filename=composer
```

**Comment by jakubstephan** [comment]
the same for me, php 8.2.

In CI/CD i've just switch to previous version:

```
php -r "copy('https://getcomposer.org/download/2.6.5/composer.phar', 'composer-setup.php');"
```

**Comment by Seldaek** [comment]
It's fixed now, sorry for the trouble 😅

**Comment by ubi-fcornu** [comment]
A good question for (not so) later :

How the hell did that land on the GA release, and without a changelog entry

Thanks for the quick fix and good luck on the investigation

**Comment by serge-tseiko** [comment]
> How the hell did that land on the GA release, and without a changelog entry

> @Seldaek
> It's fixed now, sorry for the trouble 😅 It was simply a typo I missed in an installer script change, the composer.phar file was fine.

**Comment by Seldaek** [comment]
How did it happen? Like always: seemed like a minor change, review missed the typo entirely. I'll make sure I add a step checking the installer works on a basic level before it gets deployed.

And it was not in changelog or anything because it was just in the installer, not a new composer release.

**Comment by vaiil** [comment]
@Seldaek Maybe it's time to set up some test/deploy pipeline for the installer after the accident.

**Comment by ubi-fcornu** [comment]
> How did it happen? Like always: seemed like a minor change, review missed the typo entirely. I'll make sure I add a step checking the installer works on a basic level before it gets deployed.
> 
> And it was not in changelog or anything because it was just in the installer, not a new composer release.

"just the installer" :)
*just* a publicly available deliverable downloaded by thousands, daily

IMHO the installer's delivery process needs to be strengthened. 
Keep a stiff upper lip, guys !

**Comment by Seldaek** [comment]
Yeah, don't worry seeing 10 open issues in 15min and scrambling to fix things ASAP convinced me already that I needed some checks in place there.

It's done now https://github.com/composer/getcomposer.org/commit/9b8078e2764b09dd2017b8625bf4c733577b0a26

This file hardly ever changes, so usually I check changes are valid manually, but this one time I slipped up because it was such a small change.. Shit happens.

**Comment by ubi-fcornu** [comment]
> Yeah, don't worry seeing 10 open issues in 15min and scrambling to fix things ASAP convinced me already that I needed some checks in place there.
> 
> It's done now [composer/getcomposer.org@9b8078e](https://github.com/composer/getcomposer.org/commit/9b8078e2764b09dd2017b8625bf4c733577b0a26)
> 
> This file hardly ever changes, so usually I check changes are valid manually, but this one time I slipped up because it was such a small change.. Shit happens.

Mistakes is what makes us human, among other things. That's why we need those machines to check after us :)

**Comment by dcaillon** [comment]
thanks all of you guys, my initial command getcomposer.org/installer run well now :)
