### ISSUE TITLE
Composer 2.7.0 breaks PHP Stan

### ISSUE THREAD

**Issue by evs-xsarus** [composer/composer#11843]
Composer 2.7.0 breaks QA checks, e.g. PHP Stan:

> Fatal error: Declaration of Magento\ComposerRootUpdatePlugin\Plugin\Commands\OverrideRequireCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Composer\Command\RequireCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /sites/rol_upgrade/current/magento/vendor/magento/composer-root-update-plugin/Plugin/Commands/OverrideRequireCommand.php on line 173

In 2.6.6, the PHP Stan works as intended.

**Comment by Seldaek** [comment]
This is not breaking PHPStan nor is it related to #11839, it is a signature issue in the magento/composer-root-update-plugin. I sent them a PR to fix it here https://github.com/composer/composer/issues/11843

**Comment by fredden** [comment]
Sorry! My mistake.

**Comment by Seldaek** [comment]
No worries, but anyway it's not something we can resolve. You'll have to downgrade to Composer 2.6.6 with `composer self-update 2.6.6` until the plugin repo is fixed and you can upgrade both that and Composer then.

**Comment by namespacebrian** [comment]
> This looks like a duplicate of #11839

That looks like a different issue.. relating to running as root user..?  Or at least I don't see the similarity
