### ISSUE TITLE
Stand with Palestine against the occupation

### ISSUE THREAD

**Issue by ventuinha** [composer/composer#11865]
Hello,
I wanted to propose this because since last time in #11707 the situation was considered "much more complex"
Things are much clearer now don't you think?

I think we should keep that in mind for the rest of the community, since there are so many attempts to cover it all in the rest of the places

If "Stand with Palestine" is considered too much for some of you, we could at the very least place "Stand with Gaza" to highlight the attrocities happening there

Please, consider this

**Comment by Seldaek** [comment]
Sorry but no. We won't revisit this decision.
