### ISSUE TITLE
in swoole projects, class_exists() causes "include" the same class more than once

### ISSUE THREAD

**Issue by yespire** [composer/composer#11877]
In swoole projects, when using class_exists(ClassName), the following line will try to include class file everytime when class_exists() is run:

https://github.com/composer/composer/blob/main/src/Composer/Autoload/ClassLoader.php#L576

* Question: is there a reason to prefer "include" over "include_once" ?  Is there a downside of using "include_once" here ?

**Comment by Seldaek** [comment]
Last time I checked include works faster than include_once as it does less checks, and it seems to works for everything not messing with the process at least. I'm not sure what the actual cause of the issue with Swoole is, but I'm also pretty sure others have successfully worked with class_exists AND swoole, so maybe it's something else.

**Comment by yespire** [comment]
@Seldaek 

Thank you for taking a look at this matter !

1. could you please provide some details on how much is the performance gain of using "include" over "include_once ? or point me to a resource I can find out more on the relevant studies ?

For most PHP projects, the performance difference impacted by "include_once" should be insignificant, especially comparing to other things like database queries, algorithm choices, and network latency. If "include" and "include_once" performance matters in a project, shouldn't the project be implemented with C++ or Rust instead ? Please correct me if there are other consideration involved or I am missing something ...

2. if composer use "include" on line 576, does composer implement its own double inclusion prevention ?

3. May I suggest refactoring this to be project level configuration ? ie: adding a new key in composer.json "include_mode"
- I for one would prefer include_once over include, this solve the issue I am encountering currently
- when using swoole, the process is long running, so the repeat loading is unnecessary


---

You may wonder how I come to suspect the code in ClassLoader.php (Line 576), I setup a exception if the same class being loaded for the 2nd time:

![image](https://github.com/composer/composer/assets/1065882/ce7b0c4b-557a-42da-9ad9-a15a8ed59496)

On 2nd load, the above code produce the following stack trace:
```
HP Fatal error:  Uncaught Exception: src/Server/Websocket/Route/Context.php in src/Server/Websocket/Route/Context.php:9
Stack trace:
#0 vendor/composer/ClassLoader.php(576): include()
#1 vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('...  file-path ...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Server\\Websocket\\Route\\Context')
#3 vendor/main/app-lib/src/Lib/Stateful/Finder.php(910): class_exists('\\Server\\Websocket\\Route\\Context')
```

---

You mentioned that there could be other causes ? Could you please elaborate what you would check or suspect in this situation ?

Thank you for your help !

**Comment by Seldaek** [comment]
Yeah no sorry this is the same issue as `class_exists('\\')`, you have to ensure this is called correctly, or if anything PHP should error out. It's not our job to validate this and error IMO, and it would just slow down every class loading call in every project using Composer which is a lot of wasted CPU cycles for a rare mistake.

**Comment by Seldaek** [comment]
But glad you found out the problem..
