### ISSUE TITLE
JSON Format when sending to discord like discohook

### ISSUE THREAD

**Issue by Jueshh** [composer/composer#11887]
Is there anyway to use json and it will display like discohook?
when I send a json formatted message it will just display the json

**Comment by fredden** [comment]
@Jueshh what's a discohook?

**Comment by stof** [comment]
I suspect that this has nothing to do with the composer project living in this repository.

**Comment by stof** [comment]
This answer confirms my intuition: it is totally unrelated to this project. You are asking for help in the wrong place.
