### ISSUE TITLE
Communicating the updated/changed packages to an post event

### ISSUE THREAD

**Issue by sstok** [composer/composer#1189]
When using the Symfony-standard package, the SensioDistributionBundle is executed for every install and update. Executing the bootstrap building process, even tho the Symfony package is not updated.

Currently the Event only communicates the event name, IO and Composer instance.
I don't now if there is a way to get a list of installed/updated packages of in the current process? But adding an method to the Event class would make this possible and cut some time when updating.

**Comment by Seldaek** [comment]
pre/post-package-install and post-dependencies-solving now receive all operations, closing.
