### ISSUE TITLE
[feature] Add native NPM support

### ISSUE THREAD

**Issue by razvanphp** [composer/composer#11899]
I will not follow the issue template as this is rather a (bold) idea, that seems was not discussed before.

For some projects we (as in PHP developers) need (an easy way) to include some FE libraries like jquery, bootstrap and more recently HTMX.

It would be nice to have the possibility to include them natively from `composer.json`, following the npm registry names. 

Similar working solutions include:
- https://asset-packagist.org/
- https://github.com/fxpio/foxy
- https://github.com/fxpio/composer-asset-plugin

While those projects are great, I would rather not rely on a 3rd party to maintain a bridge repository, as it can pose long-term maintainability and security issues.

Sample usage:
```
"require": {
    "npm-asset/bootstrap": "^5.0",
    "npm-asset/jquery": "^2.2"
}
```

Can we open a discussion about joining hands with the JS community? 🙂 

Thank you!
R

**Comment by stof** [comment]
To me, I only see 2 solutions for that:

- using a bridge repository (exactly what https://asset-packagist.org/ is doing) to convert the npm metadata in the Composer metadata format. This is already solved by asset-packagist (and I don't see the benefit of duplicating that work to be done by the composer core team, which is quite small)
- making composer work directly with the npm registry by becoming an npm client. This is a *huge* amount of work as composer and npm work totally differently, and the composer team probably does not have the resources to implement and maintain such solution (with all the related complexity).

**Comment by Seldaek** [comment]
I don't see a reason to be honest.. It's a lot of work for a minor use case of some packages requiring some frontend stuff.

I'm not entirely sure how Symfony UX packages solved this, but somehow they do it without needing asset-packagist or other worse hackery like composer-asset-plugin (as far as I know..).

In all the projects I work on we have npm for frontend dependencies and very little interaction between the two and that works quite fine. Others have had a need and have solved it for themselves, but I don't feel the need enough to want to write or maintain such a solution.

**Comment by stof** [comment]
Symfony UX solved that by relying on the Flex plugin, which operates in 2 different modes, both of them relying on UX bundles having a `package.json` file defining their npm dependency:

- when using symfony/asset-mapper, Flex will register those dependencies in the AssetMapper ImportMap system
- when using the npm-based setup (with `@symfony/webpack-encore`), Flex will add `file:` dependencies referencing the package.json in the vendor folder (and then tell you to run a yarn/npm update to install the updated dependencies).

Symfony UX never relies on using Composer to perform the installation of the frontend packages from the npm ecosystem.
