### ISSUE TITLE
Composer validate: keywords invalid value, must match regex

### ISSUE THREAD

**Issue by SvenRtbg** [composer/composer#11897]
My `composer.json`:

```json
{
    "name": "testcase/keywords",
	"description":"Testcase for keywords",
	"license": "proprietary",
    "require": {},
	"keywords": ["foo:"]
}

```

Output of `composer diagnose`:

```
Composer could not detect the root package (testcase/keywords) version, defaulting to '1.0.0'. See https://getcomposer.org/root-version
Checking composer.json: WARNING
keywords.0 : invalid value (foo:), must match [\p{N}\p{L} ._-]+
Checking platform settings: OK
Checking git settings: OK git version 2.25.1
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking HTTP proxy: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking Composer version: OK
Checking Composer and its dependencies for vulnerabilities: OK
Composer version: 2.7.2
PHP version: 7.4.33
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
cURL version: 7.68.0 libz 1.2.11 ssl OpenSSL/1.1.1f
zip: extension present, unzip present, 7-Zip not available

```

When I run this command: 

```
composer validate --strict
```

I get the following output: 

```
Composer could not detect the root package (testcase/keywords) version, defaulting to '1.0.0'. See https://getcomposer.org/root-version
Composer could not detect the root package (testcase/keywords) version, defaulting to '1.0.0'. See https://getcomposer.org/root-version
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
# General warnings
- keywords.0 : invalid value (foo:), must match [\p{N}\p{L} ._-]+

```
and exit code 1.

And I expected this to happen:

No complaint about the keywords because the composer schema does not restrict the string at all.

Comment: The keywords are apparently a sensitive topic because as I learned in https://github.com/composer/composer/issues/4087 they are parsed for the search engine on packagist. The preg_match regex in the error message is probably the most permissive in terms of allowing unicode characters - unless you want to use the colon, because that isn't allowed.

However, the composer schema file at https://getcomposer.org/schema.json does not mention any restriction for the keywords at all:

```json
        "keywords": {
            "type": "array",
            "items": {
                "type": "string",
                "description": "A tag/keyword that this package relates to."
            }
        },
```

Other parts make use of the pattern restriction, so it isn't a case of "specific string restrictions are never encoded into the schema", more like "composer validate may complain about additional things even though they are not really documented anywhere".

Looking at the part explaining keywords at https://getcomposer.org/doc/04-schema.md#keywords :

> An array of keywords that the package is related to. These can be used for searching and filtering.
> 
> Examples:  logging, events, database, redis, templating
> 
> Note: Some special keywords trigger composer require without the --dev option to prompt users if they would like to add these packages to require-dev instead of require. These are: dev, testing, static analysis.
> 
> Optional.

It does not state anywhere that keywords are in fact restricted to unicode letters or numbers, space, dot, underscore and dash.

I cannot categorize what part of the world I'd like to see fixed. I understand that keywords are generally understood to be useable however I want, hence no restriction in the schema, and no mentioning of restrictions in the documentation. But then the composer validate output comes as a surprise and shouldn't happen.

If however the validation being free of warnings is the prerequisite to be able to publish anything via Packagist, then I suppose the restrictions for keywords should be a bit more obvious, i.e. they should at least be documented, and preferably be added to the schema as well.

**Comment by Seldaek** [comment]
Yes, fair enough it should probably be in the docs. I don't think it can be in the schema because unicode character classes aren't necessarily well supported across various languages. So the schema is kinda basic correctness validation and the validate command goes in more depth in many ways.

Feel free to send a PR for the docs.

**Comment by SvenRtbg** [comment]
Are there any implications publishing a package with invalid keywords on Packagist?

**Comment by Seldaek** [comment]
`:` IIRC mess with the searches, it introduces difficulties as they have to be escaped. I don't remember exactly the details anymore now.

But frankly I don't see how this is necessary in keywords. These should be simple everyday words that are understandable. I allowed unicode for non-english keywords but if it weren't for that I'd have made this `[a-z0-9 ]` frankly. Anything else seems like too much for me for the intent of this feature.
