### ISSUE TITLE
[RFC] Automatically bump requirements when updating packages, with type=project or with an option in the configuration

### ISSUE THREAD

**Issue by lyrixx** [composer/composer#11906]
Hello,

1️⃣ On **projects** (as opposed on libraries ; `"type": "project"`), I think we could run automatically `composer bump` after each `composer update`

2️⃣ If this is too intrusive, could we at least have a new configuration flag in the `composer.json` to configure this behavior 

```json
    "config": { "bump-after-update": true }
```

3️⃣ We could even have something in the middle : 2️⃣ + with `true` as default value. So if someone doesn't want to to bump, they could turn it out

**Comment by fredden** [comment]
Why should this be a built-in feature of Composer rather than a case of running `composer update && composer bump` ?

**Comment by lyrixx** [comment]
More or less the same arguments each times but:

1. Some bots does not bump by default, so it would fix it
2. Some colleagues does not bump some times, so it would fix them
3. To ensure it's always bumped
4. To avoid typos
5. To automate things
