### ISSUE TITLE
Windows 11/PHP8.3.3 install fails - missing or invalid info (exit code -1073741643)

### ISSUE THREAD

**Issue by schmidtl4** [composer/composer#11900]
My `composer.json`: attempting to install from the latest Composer-Setup.exe download

Can't run `composer diagnose`, not installing

When I run this command: 

Can't run composer, not installing

I get the following output: 
Can't run composer, not installing

Synopsis:
I had composer running just fine with PHP 7.4
I recently upgraded php to 8.3.3  
Composer wasn't working (phar file not associated with files) so I uninstalled composer and tried to re-install it.
That's when I get this error:
The PHP exe file you specified did not run correctly [exit code -1073741643]:
C:\php8.3.3\php.exe
Required information is missing or invalid

I have no idea what information is missing or invalid.  PHP8.3.3 works fine to render php pages etc. so it would seem it is not about the PHP installation.

Also, I confirmed that PHP is properly included in the Path Environment Variable.

Where to look?  How to identify the missing or invalid information?

**Comment by Seldaek** [comment]
Please report it here and include the log file as requested in the issue template https://github.com/composer/windows-setup/issues/new
