### ISSUE TITLE
curl error 23 when updating custom repository

### ISSUE THREAD

**Issue by cappuc** [composer/composer#11913]
### Edit: How to Fix

Run `brew reinstall curl` to get the latest curl and fix this issue

----

Hi,

from yesterday composer started giving me this error when I'm using a custom repository:

```
curl error 23 while downloading https://<private-repo-url>/packages.json: Failed writing received data to disk/application
```

After many tries to fix this problem, I found that removing [this line](https://github.com/composer/composer/blob/b12a88b7f3313e9dbae5b58085323b8328d10296/src/Composer/Util/Http/CurlDownloader.php#L207) from `CurlDownloader` fixes the problem:

```
curl_setopt($curlHandle, CURLOPT_ENCODING, ""); // let cURL set the Accept-Encoding header to what it supports
```

I encountered this problem only on my mac, I tried with docker and it works.

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK git version 2.44.0
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK does not expire
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking Composer version: OK
Checking Composer and its dependencies for vulnerabilities: OK
Composer version: 2.7.2
PHP version: 8.3.4
PHP binary path: /opt/homebrew/Cellar/php/8.3.4/bin/php
OpenSSL version: OpenSSL 3.2.1 30 Jan 2024
cURL version: 8.7.1 libz 1.2.12 ssl (SecureTransport) OpenSSL/3.2.1
zip: extension present, unzip present, 7-Zip not available
```

When I run this command: 

```
composer update --no-cache -v
```

I get the following output: 

```
Loading composer repositories with package information

In CurlDownloader.php line 389:
                                                                                                                             
  [Composer\Downloader\TransportException]                                                                                   
  curl error 23 while downloading https://<private-repo-url>/packages.json: Failed writing received data to disk/application  
                                                                                                                             

Exception trace:
  at phar:///usr/local/bin/composer/src/Composer/Util/Http/CurlDownloader.php:389
 Composer\Util\Http\CurlDownloader->tick() at phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php:392
 Composer\Util\HttpDownloader->countActiveJobs() at phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php:363
 Composer\Util\HttpDownloader->wait() at phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php:114
 Composer\Util\HttpDownloader->get() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:1486
 Composer\Repository\ComposerRepository->fetchFile() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:1195
 Composer\Repository\ComposerRepository->loadRootServerFile() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:823
 Composer\Repository\ComposerRepository->hasProviders() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:484
 Composer\Repository\ComposerRepository->loadPackages() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/PoolBuilder.php:401
 Composer\DependencyResolver\PoolBuilder->loadPackagesMarkedForLoading() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/PoolBuilder.php:251
 Composer\DependencyResolver\PoolBuilder->buildPool() at phar:///usr/local/bin/composer/src/Composer/Repository/RepositorySet.php:326
 Composer\Repository\RepositorySet->createPool() at phar:///usr/local/bin/composer/src/Composer/Installer.php:495
 Composer\Installer->doUpdate() at phar:///usr/local/bin/composer/src/Composer/Installer.php:292
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:251
 Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:385
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:145
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:93
 require() at /usr/local/bin/composer:29
```

**Comment by CodeWithDennis** [comment]
I've encountered the same problem today, and I'm also using MacOS.

```
In CurlDownloader.php line 389:
curl error 23 while downloading https://redacted.pub/composer/packages.json: Failed writing received data to disk/application
  ```

**Comment by boris-glumpler** [comment]
I'm also getting the same error on a new Mac M3 Pro. Satis repositories are not affected, tho, and install just fine.

**Comment by jdecool** [comment]
I've the same error on one of my computers.

When I compare the `composer diagnose`, the problem seems to be related to the `cURL version`.

Works with `cURL version: 8.6.0 libz 1.2.12 ssl (SecureTransport) OpenSSL/3.2.1` but not with `cURL version: 8.7.1 libz 1.2.12 ssl (SecureTransport) OpenSSL/3.2.1`

**Comment by jdecool** [comment]
After running `brew reinstall curl` on my machine, it seems the error disappear.

**Comment by boris-glumpler** [comment]
Disappeared for me as well after `brew reinstall curl` just now. I ran this a couple times yesterday, tho, and it didn't work then.

**Comment by cappuc** [comment]
`brew reinstall curl` worked for me too.

**Comment by Seldaek** [comment]
Ok then looks like it's a curl or brew bug. I'll leave the issue open for now so people find it more easily, but I don't think we should act on it.

**Comment by ssx** [comment]
I'm thankful I've found this - same issue for me today! Cheers for leaving open Jordi.

**Comment by sedattcom** [comment]
I've been having this problem for a week and I couldn't solve it.
I cannot update curl on the server where Whm is installed.
Do you have a different solution suggestion?

**Comment by craigvc** [comment]
issue is still there with reinstall curl

**Comment by riskihajar** [comment]
`brew reinstall curl` not working for me.

i'm using laravel herd btw.
i think the problem after herd update php 8.3, curl module using version 8.7.1.

for awhile i'm isolated to php8.2 which use curl 8.6.0 then run `herd composer update` its works ✅

**Comment by plompd** [comment]
I also use Herd. No idea how to downgrade cUrl on a mac. Anyway, downgrading to version 3..6.6 is working. Then it is downloading...

**Comment by Seldaek** [comment]
@plompd version 3.6.6 of what software?

**Comment by plompd** [comment]
Sorry, I thought I was on a specific package repo...
This was regarding installing a package in Laravel.

**Comment by temp** [comment]
Same problem here, on a M1 macbook with macports. Works with curl 8.6.0, fails with curl 8.7.1

**Comment by maximierung** [comment]
I have the same problem on Windows 11, but it doesn't run with either curl 8.4.0, 8.6.0 or 8.7.1. I tried Herd php8.2 and 8.3 and still got the same error.

**Comment by maximierung** [comment]
I had the same error on Windows 11, here's how I fixed it.

Run composer install on php8.3.

Change Herd to php8.1 (cURL 8.4.0) & run composer install --ignore-platform-reqs.

Then you should be fine, to change it back once all the installing is done, atleast I was.

If you don't have Herd just use a php version that uses the older curl versions.

**Comment by craigvc** [comment]
> I had the same error on Windows 11, here's how I fixed it.
> 
> Run `composer install` on php8.3.
> 
> Change Herd to php8.1 (cURL 8.4.0) & run `composer install --ignore-platform-reqs`.
> 
> Then you should be fine, to change it back once all the installing is done, atleast I was.
> 
> If you don't have Herd just use a php version that uses the older curl versions.

thats not really a solution as some packages on our project need 8.2 or 8.3
@maximierung

**Comment by maximierung** [comment]
> thats not really a solution as some packages on our project need 8.2 or 8.3 @maximierung

For me it worked since all the packages with the error didn't need it, but ig you're right tough. 👍

**Comment by mpociot** [comment]
For those of you who are curious why a `brew reinstall` fixes the issue despite no new version of curl being released: Homebrew manually applies this patch, which fixes the issue: https://github.com/curl/curl/commit/b30d694a027eb771c02a3db0dee0ca03ccab7377

**Comment by pxlrbt** [comment]
@mpociot Is there also a fix when using `herd composer`? I guess that requires a new release for the PHP binary?

**Comment by Seldaek** [comment]
This is a curl regression in https://github.com/curl/curl/commit/463472a2d6e3301c1468b5323b856cb67a91f579 meaning curl 8.7.0 and 8.7.1 are affected. 8.7.2 is planned to be released on May 22, 2024.

As that's kinda far off, and it seems to affect a bunch of people.. I tried to publish a workaround. Can someone affected please try if `composer self-update --snapshot` resolves it? I am not sure if hardcoding the Accept-Encoding header to `gzip` fixes it as well or if we really need to disable compression altogether.

Once confirmed I'll try to get a release out..

**Comment by pxlrbt** [comment]
Since reinstalling curl fixed this, I don't think I can test this 🙈

**Comment by zupolgec** [comment]
> This is a curl regression in [curl/curl@463472a](https://github.com/curl/curl/commit/463472a2d6e3301c1468b5323b856cb67a91f579) meaning curl 8.7.0 and 8.7.1 are affected. 8.7.2 is planned to be released on May 22, 2024.
> 
> As that's kinda far off, and it seems to affect a bunch of people.. I tried to publish a workaround. Can someone affected please try if `composer self-update --snapshot` resolves it? I am not sure if hardcoding the Accept-Encoding header to `gzip` fixes it as well or if we really need to disable compression altogether.
> 
> Once confirmed I'll try to get a release out..

This solved the issue for me, while reinstalling curl didn't work. Thanks @Seldaek

**Comment by fabianpnke** [comment]
> This is a curl regression in [curl/curl@463472a](https://github.com/curl/curl/commit/463472a2d6e3301c1468b5323b856cb67a91f579) meaning curl 8.7.0 and 8.7.1 are affected. 8.7.2 is planned to be released on May 22, 2024.
> 
> As that's kinda far off, and it seems to affect a bunch of people.. I tried to publish a workaround. Can someone affected please try if `composer self-update --snapshot` resolves it? I am not sure if hardcoding the Accept-Encoding header to `gzip` fixes it as well or if we really need to disable compression altogether.
> 
> Once confirmed I'll try to get a release out..

This worked for me as well. Not like the curl reinstall.

**Comment by DanielvdSpoel** [comment]
Anyone that knows how to solve this? I'm using composer 2.7-dev, with php 8.3.9 and curl 8.7.0-DEV

**Comment by DanielvdSpoel** [comment]
I added a new version of curl on Windows, Composer (and PHP) are still using the one that comes with windows, how can i make it use the newer one?

**Comment by john-aspire** [comment]
Hi,

I managed to fix it like this for right or wrong on Windows:

1) c:\windows\system32\curl.exe -> rename it to _curl.exe. You can do this by 'taking ownership' of the file, then giving yourself permission to rename the file.
2) Download the latest curl.exe and put it in a directory like c:\curl. 
3) Add the c:\url to the system environment settings 'path'
4) In your php.ini comment out the curl extension
5) Run the composer again with the --ignore-platform-req=ext-curl option (eg: composer --ignore-platform-req=ext-curl require archilex/filament-filter-sets)
6) In your php.ini re enable the curl extension

This is how I worked around it for now.

**Comment by mohdaftab** [comment]
> 5\. --ignore-platform-req=ext-curl

Thank you so much, this worked for me.
