### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by Dantechdevs** [composer/composer#11911]
php composer.phar install 
I tried to install composer via brew per:

In usr/local/bin (which was not on Mavericks and I had to make it personally) I did.

brew tap josegonzalez/homebrew-php
brew install josegonzalez/php/composer
I can run php composer.phar, but when I do php composer.phar install, I get the error:

Composer could not find a composer.json file in /usr/local/bin To initialize a project, please create a composer.json file as described in the http://getcomposer.org/ "Getting Started" section`

**Comment by Seldaek** [comment]
You need to run composer in the directory where a composer.json is, so if you are in your project's directory just run `composer` as it is in /usr/local/bin it should be in your PATH and just work.

**Comment by Dantechdevs** [comment]
@Seldaek thank you ❤️
