### ISSUE TITLE
[RFC] Remove `v` from version numbers in the output table of `composer show`

### ISSUE THREAD

**Issue by ThomasLandauer** [composer/composer#11925]
When running `composer show`, some packages are prefixing their version number with a `v`, while others don't:

```
symfony/yaml  v7.0.3  Loads and dumps YAML files
vimeo/psalm   5.23.1  A static analysis tool for finding errors in PHP applications
``` 

IMO, this just adds noise, so I'm suggesting to automatically remove any `v` prefix from the version number.

I already suggested this for Symfony, but it got rejected cause it's useful for selecting git branches: https://github.com/symfony/symfony/issues/52135

**Comment by Seldaek** [comment]
I am also not so happy to do this tbh.. The package pretty version should represent the tag, and we shouldn't mess with it IMO.

**Comment by derrabus** [comment]
Maybe we could add a flag to the `composer show` command that makes Composer output a normalized version string instead instead of the rendering the tag verbatim.

**Comment by Seldaek** [comment]
Yeah I am not so sure, I'd rather avoid options/flags for such minor things. Either we do it or we don't IMO. I had a closer look and it seems easy to do in a way that it shouldn't mess with any automation, so only "fixing" the listing outputs where different packages are shown next to each other and various versioning schemes may end up with this noisy difference. I wouldn't touch the data for a single package, nor the json output.

**Comment by derrabus** [comment]
Fair enough.
