### ISSUE TITLE
composer install is taking nearly 3 hours on mac 

### ISSUE THREAD

**Issue by AdvaithRaj** [composer/composer#11926]
I am running the composer install on mac and it is taking nearly 3 hours to complete  the dependencies installation . 
I have increased the limit to ulimit -n  65535, but still seeing the same slowness  Could any one please help on the issue. 
it was working fine previously and after upgrading the OS to SONOMA 14.4 facing the issue. 

Composer version 2.7.2 
PHP version 8.1.27 (/usr/local/Cellar/php@8.1/8.1.27_1/bin/php)

**Comment by fredden** [comment]
@AdvaithRaj please complete the issue template. This is the text which you deleted when you created this issue. For reference, see https://github.com/composer/composer/blob/main/.github/ISSUE_TEMPLATE.md?plain=1

The template intentionally asks questions which will enable us to help you.
