### ISSUE TITLE
Allow --lock file to be created for lock false case

### ISSUE THREAD

**Issue by dereuromark** [composer/composer#11930]
My `composer.json`:

```json
"config": {
        "lock": false,
```
as the vendor library usually doesn't need the lock file, so it is just noise.

But in rare occasions, e.g. when wanting to look into installed repos, it can be useful to manually create it.
Is there a better way than to remove the config here?

Would be nice if there was a command way to quickly do that.

I tried
```
composer update --lock
```
as I would expect this to then allow this, but

> Cannot update lock file information without a lock file present. Run `composer update` to generate a lock file.

So a bit of a chicken/egg problem on CLI here. As that statement is wrong - or impossible to generate it either.

We could also have a new
```
composer install --lock
```
For this maybe if the current command need to stay as is? But then the above message should read correctly:

> ... Run `composer install --lock` to generate a lock file overriding your config setting `lock` set to `false`.

**Comment by Seldaek** [comment]
I'd recommend looking in vendor/composer/installed.json instead if you just want to inspect stuff, it is almost the same format as the lock file. I don't see the point of an extra flag there, and especially we already have a --lock flag for update that does something else.
