### ISSUE TITLE
The Composer installer script was not successful [exit code 1].

### ISSUE THREAD

**Issue by nazaninabedifar77** [composer/composer#11935]
I have the error ,when installing composer.i tried to install composer from git but the same error happened.

The Composer installer script was not successful [exit code 1].
Your proxy settings may be causing this error.

Script Output:
The "https://getcomposer.org/versions" file could not be downloaded: Failed to open stream: No connection could be made because the target machine actively refused it

what should i do?

**Comment by johnstevenson** [comment]
> Your proxy settings may be causing this error.

It looks like you have misconfigured your proxy settings.

If you cannot fix this, open an issue here https://github.com/composer/windows-setup/issues/new and supply a log file (as per the issue template).
