### ISSUE TITLE
Archive exclude does not work on GitHub nor Packagist

### ISSUE THREAD

**Issue by dakujem** [composer/composer#11949]
I added `archive.exclude` rules into my composer.json scheme to at least 2 packages, and the archives generated by GitHub (also privately hosted GitLab CE 16.10) still **do contain the excluded files**, both GitHub Actions config files and test files.
![Screenshot 2024-04-24 143515](https://github.com/composer/composer/assets/443067/0c6a2714-155d-44ab-a30b-1c53ed1f5671)

Consequently, the test files and CI config files end up in the vendors of projects, which is what the `archive.exclude` is supposed to mitigate.

My `composer.json` ([github link here](https://github.com/dakujem/cumulus/blob/2.0.1/composer.json))

```json
{
  "name": "dakujem/cumulus",
...
  "archive": {
    "exclude": [
      "/tests",
      "/.github"
    ]
  }
}
```

The generated archive can be found [here](https://github.com/dakujem/cumulus/releases/tag/2.0.1). As can be seen, both `/tests` and `/.github` dirs are present in the archives.

In comparison, my other package does not suffer from this issue, visible here: [tag created for purpose of this issue](https://github.com/dakujem/oliva/releases/tag/xx-foo). I assumed the difference was that the exclude had been added prior to creating any tag/release, but this is not the case, as the [first alpha release archive](https://github.com/dakujem/oliva/releases/tag/1.0.0-alpha1) _does_ contain the tests, but the later ones do not. This is even more strange, since the first alpha tag points to a commit that excludes the test files. Does this imply some sort of caching issues? If so, how come it affects 4 platforms independetly (GitHub, GitLab, Packagist, privately hosted Satis).

Locally, I observe the rules being effective, as I  run `composer archive` and the excluded directores are absent as I add them to `composer.json`.

I'm sorry, I have no idea where else to report this issue.

**Comment by glaubinix** [comment]
The archive configuration in your composer.json file is only used to create archive files via `composer archive`. If you want to make sure those folders aren't included in the default ZIP files created by GitHub and GitLab then the recommend way is to exclude them via [. gitattributes](https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes#:~:text=export%2Dignore,via%20the%20export%2Dignore%20attribute.).

**Comment by dakujem** [comment]
My bad! 🤦‍♂️

Indeed you are correct. It is the missing `.gitattributes`. Thank you so much for this advice.
