### ISSUE TITLE
PHP Fatal error: Uncaught exception 'PharException' with message manifest

### ISSUE THREAD

**Issue by jehtik** [composer/composer#1194]
PHP Fatal error: Uncaught exception 'PharException' with message manifest cannot be larger than 100 mb in phar

while trying to install composer.phar through command line , got an error

**Comment by furryablack** [comment]
any changes in composer.phar forbidden to configure?

**Comment by Startxl** [comment]
[Composer\Downloader\TransportException]                                                      
  The "https://packagist.phpcomposer.com/packages.json" file could not be downloaded: php_netw  
  ork_getaddresses: getaddrinfo failed: Temporary failure in name resolution                    
  failed to open stream: php_network_getaddresses: getaddrinfo failed: Temporary failure in na  
  me resolution

**Comment by isabelle12345** [comment]
i have the same problem :PHP Fatal error: Uncaught exception 'PharException' with message manifest cannot be larger than 100 mb in phar
while trying to install composer.phar through command line , got an error
And even when I take  composer.phar from https://getcomposer.org/composer.phar
Can somebody help me?
Thank you!

**Comment by iyeoluwa** [comment]
Has anybody been able to solve this issue I’m also experiencing it
