### ISSUE TITLE
Plugin install promise must be scheduled after all required package promises are done

### ISSUE THREAD

**Issue by mvorisek** [composer/composer#11941]
I am developing https://github.com/roundcube/plugin-installer/pull/50 and it seems `roundcube/roundcubemail` package is installed\* after the plugin installer.

steps to reproduce:

https://github.com/roundcube/plugin-installer/blob/9b0dffcc1b/.github/workflows/ci.yml#L93-L105

\* by installed I mean available on filesystem to be used

Reproducible on linux only, I was not able to reproduce it locally on Windows.

When I revert https://github.com/roundcube/plugin-installer/commit/4204c4b356 the issue is gone. But the repository is the same, the difference is only how the repo is installed, newly installed using zip, previously installed using git.

**Comment by Seldaek** [comment]
Yes.. as roundcube/roundcubemail requires roundcube/plugin-installer, we have to install the plugin first.

We always install dependencies first, so that when a package is installed what it depends on is ready to be used.

The only difference with git is that it might have cloned the repo already in the download step (where as zip downloads into the cache), but the package is not technically installed.

**Comment by mvorisek** [comment]
> Yes.. as roundcube/roundcubemail requires roundcube/plugin-installer, we have to install the plugin first.

Thank you. I missed this circular dependency.

> The only difference with git is that it might have cloned the repo already in the download step (where as zip downloads into the cache), but the package is not technically installed.

Git is always cloned to a cache first. Shouldn't the "download phase" for git be aligned with zip to do the "extraction" (from a git cache) at the "install phase" then?

**Comment by Seldaek** [comment]
I think it's a bit more complicated than that, and extracting it all would be possible but a bunch of work which really does not matter too much..

**Comment by mvorisek** [comment]
How can I schedule the https://github.com/roundcube/plugin-installer/blob/331e0791b3/src/ExtensionInstaller.php#L78 promise either after full install or at least after some specific package is installed?

**Comment by Seldaek** [comment]
I'd say try to get the event dispatcher and register a post-install-cmd/post-update-cmd listener that will do the needed work. You can't achieve this with promises here.
