### ISSUE TITLE
Have a non-zero exit code when curl fails

### ISSUE THREAD

**Issue by bilogic** [composer/composer#11954]
![image](https://github.com/composer/composer/assets/946010/fd98ac2c-e714-4073-b868-5879943e619b)

I'm running `composer update` in my ci/cd action file.

Sometimes, `curl` fails (see image), but it would appear composer exits with `0` code (which is why the `Setup dependencies with composer` has a green tick.

Possible to exit with a non-zero instead?

My `composer.json`:

```json
...replace me...
```

Output of `composer diagnose`:
```
...replace me...
```

When I run this command:

```
composer update
```

I get the following output: 

```
Loading composer repositories with package information
https://repo.packagist.org could not be fully loaded (curl error 7 while downloading https://repo.packagist.org/p2/symfony/debug.json: Failed to connect to repo.packagist.org port 443 after 3507 ms: Connection refused), package information was loaded from the local cache and may be out of date
::error ::curl error [7](https://example.com/example/example-project/actions/runs/2034#jobstep-4-7) while downloading https://repo.packagist.org/p2/symfony/debug.json: Failed to connect to repo.packagist.org port 443 after 3507 ms: Connection refused
In CurlDownloader.php line 3[8](https://example.com/example/example-project/actions/runs/2034#jobstep-4-8)[9](https://example.com/example/example-project/actions/runs/2034#jobstep-4-9):
                                                                               
  curl error 7 while downloading https://repo.packagist.org/p2/symfony/debug.  
  json: Failed to connect to repo.packagist.org port 443 after 3507 ms: Conne  
  ction refused                                                                
                                                                               
update [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--no-autoloader] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-m|--minimal-changes] [-i|--interactive] [--root-reqs] [--] [<packages>...]


```

And I expected this to happen:
a non-zero exit code

**Comment by Seldaek** [comment]
I cannot reproduce this..

```
$ composer update
Loading composer repositories with package information
https://repo.packagist.org could not be fully loaded (curl error 7 while downloading https://repo.packagist.org/packages.json: ), package information was loaded from the local cache and may be out of date

In CurlDownloader.php line 372:

  curl error 7 while downloading https://repo.packagist.org/p2/arcanedev/log-viewer.json:


update [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--no-autoloader] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-m|--minimal-changes] [-i|--interactive] [--root-reqs] [--] [<packages>...]

$ echo $?
1
```

Maybe your CI or whatever you use to call composer there is swallowing the exit code?

**Comment by bilogic** [comment]
@Seldaek I found the culprit swallowing the exit code. Thank you!

**Comment by bilogic** [comment]
@Seldaek on a related note, is there a way to specify retries after a backoff period? the exit code 1 might not be enough for me to know it is a packagist connection issue .

**Comment by Seldaek** [comment]
There is backoff here https://github.com/composer/composer/blob/bcab1c4b8ecf7b239dd9e08fc07c5458cf80cb0a/src/Composer/Util/Http/CurlDownloader.php#L615

I fixed the return type now so it should use 255 for http/curl errors.

**Comment by bilogic** [comment]
@Seldaek as usual, I really appreciate your openness to suggestions and feedback.

I did some quick googling for standardized exit codes and it would appear 255 and some others are reserved https://tldp.org/LDP/abs/html/exitcodes.html#AEN23549

1. https://www.cyberciti.biz/faq/linux-bash-exit-status-set-exit-statusin-bash/ not sure what this is based on, but it has 100-102 for network problems
2. https://stackoverflow.com/a/1535733/3872647 there is 68 and 76

Would you like me to look for a suitable number?

**Comment by Seldaek** [comment]
Packagist should not do rate limiting no, so I'm not sure why these failures occur.

Unfortunately I cannot really set a code <255 without breaking a bunch of internal code relying on the exception codes being http codes.

Exception::getCode is final so I can't do hackery there to return another code when symfony/console's Application class requests it. So I had to resort to another level of hackery.. but https://github.com/composer/composer/commit/762f2a37f595fce402a3a418f2e2f3d1a70688f8 should do the job.

**Comment by bilogic** [comment]
Ok, 255 it is. Thank you!

**Comment by Seldaek** [comment]
100 it is ;)

The CI failure is just php 8.4.
