### ISSUE TITLE
--strict-psr Doesn't warn about about classes where namespace is not set or does not start with configured namespace

### ISSUE THREAD

**Issue by PrinsFrank** [composer/composer#11957]
My `composer.json`:

```json
{
    "name": "example/example",
    "description": "",
    "license": "MIT",
    "autoload": {
        "psr-4": {
            "Foo\\": "src/"
        }
    }
}
```

Output of `composer diagnose`:

<details>
Checking composer.json: OK<br>
Checking platform settings: OK<br>
Checking git settings: OK git version 2.39.3<br>
Checking http connectivity to packagist: OK<br>
Checking https connectivity to packagist: OK<br>
Checking github.com rate limit: OK<br>
Checking disk free space: OK<br>
Checking pubkeys: <br>
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642<br>
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952<br>
OK<br>
Checking Composer version: OK<br>
Checking Composer and its dependencies for vulnerabilities: OK<br>
Composer version: 2.7.4<br>
PHP version: 8.3.3<br>
PHP binary path: /opt/homebrew/Cellar/php/8.3.3_1/bin/php<br>
OpenSSL version: OpenSSL 3.2.1 30 Jan 2024<br>
cURL version: 8.6.0 libz 1.2.12 ssl (SecureTransport) OpenSSL/3.2.1<br>
zip: extension present, unzip present, 7-Zip not available<br>
</details>

When I run this command: 

```
composer du --strict-psr --optimize
```

With the two following classes:

`src/Bar.php`
```php
<?php
class Bar {}
```

`src/Boop.php`
```php
<?php
namespace Boop;
class Boop {}
```

I get the following output: 

```
Generating optimized autoload files
Generated optimized autoload files containing 1 classes
```

And I expected this to happen:

```diff
Generating optimized autoload files
+ Class Bar located in ./src/Bar.php does not comply with psr-4 autoloading standard. Skipping.
+ Class Boop\Boop located in ./src/Boop.php does not comply with psr-4 autoloading standard. Skipping.
Generated optimized autoload files containing 1 classes
```

Only classes that are outside the configured for a folder get ignored. So if `src/` is configured with namespace `Foo\\`, if the class misses a namespace or is in a totally different namespace like `Bar\\`, it doesn't trigger any errors when running with --strict-psr.

**Comment by Seldaek** [comment]
Alright finally got it built into Composer via https://github.com/composer/composer/commit/dc857b4f9148def53cb5c182dbb965aaac76d947
