### ISSUE TITLE
Error gcloud crashed (InvalidDataFromServerError) received while set up connection 

### ISSUE THREAD

**Issue by rlbabyuk** [composer/composer#11952]
Image Version 
**composer-2.5.2-airflow-2.6.3**

I didn't have steps for reproducing, but as additional info, the connection works fine for composers created for some time, and this error is received from the newly created one.
Restart didn't help

gcloud version - 392.0.0

Error is 
`  
ERROR: gcloud crashed (InvalidDataFromServerError): Error decoding response "{
  "clusters": [
    {
      "name": "us-central1-bff3922f-gke",
.......    
.......
"nodePoolDefaults": {
        "nodeConfigDefaults": {
          "gcfsConfig": {
            "enabled": true
          },
          "loggingConfig": {
            "variantConfig": {
              "variant": "DEFAULT"
            }
          }
        }
      },
      "loggingConfig": {
        "componentConfig": {
          "enableComponents": [
            "SYSTEM_COMPONENTS",
            "WORKLOADS"
          ]
        }
      },
      "monitoringConfig": {
        "componentConfig": {
          "enableComponents": [
            "SYSTEM_COMPONENTS",
            "STATEFULSET",
            "STORAGE",
            "HPA",
            "POD",
            "DAEMONSET",
            "DEPLOYMENT"
          ]
        },
        "managedPrometheusConfig": {
          "enabled": true
        },
        "advancedDatapathObservabilityConfig": {
          "enableMetrics": true
        }
      },
      "etag": "eadaa88f-5dd3-4b61-8619-dc0a891dd1c5",
      "securityPostureConfig": {
        "mode": "BASIC",
        "vulnerabilityMode": "VULNERABILITY_BASIC"
      },
      "enterpriseConfig": {
        "clusterTier": "STANDARD"
      }
    }
  ]
}
" as type ListClustersResponse: Repeated values for field enableComponents may not be None`

**Comment by Seldaek** [comment]
I think this is another composer repo you are looking for? We are the php package manager.
