### ISSUE TITLE
package installation issue 

### ISSUE THREAD

**Issue by amruthasoman14** [composer/composer#11973]
composer require guzzlehttp/guzzle 
anything that i install uisng composer with my project  the below error message is came.
 
  file_get_contents(C:\ProgramData\ComposerSetup\bin): Failed to open stream:  
   Permission denied  
   
   how to solve this??

**Comment by hosjir** [comment]
ile_get_contents(C:\ProgramData\ComposerSetup\bin): Failed to open stream:
Permission denied

**Comment by hosjir** [comment]
ile_get_contents(C:\ProgramData\ComposerSetup\bin): Failed to open stream:
Permission denied

same problem. just installed composer and tried to install the phpseclib library

how to solve this??
