### ISSUE TITLE
About Composer plugin

### ISSUE THREAD

**Issue by ajiho** [composer/composer#11977]
For Composer plugin type Composer packages, during installation, the user will be prompted to Do you trust "xxxx" to execute code and wish to enable it now? (writes "allow plugins" to composer. json) [y, n, d,?]

Can I listen to the user's selection? If the user chooses n, I would like to directly stop or uninstall the installation of the package

If Composer provides this scenario, what should I do?

**Comment by Seldaek** [comment]
Nope there is no way to do anything, it just skips activating the plugin. I don't think uninstalling it would fit well with composer's dependency model as it would try to install it again on the next composer install run.

**Comment by Mohanraj2622** [comment]
Unable to use a proxy: unable to find proxy host in http_proxy?
