### ISSUE TITLE
Consistently use (or don't use) FQCN functions

### ISSUE THREAD

**Issue by kkmuffme** [composer/composer#11985]
```
Composer version 2.7.6 2024-05-04 23:03:15
PHP version 7.4.33 (/usr/bin/php)
```

(same with newer PHP versions)

e.g. composer/InstalledVersions.php uses FQCN for some but not all functions

```
\count(
\call_user_func_array(
```

but 
```
$packages[] = array_keys(
return array_keys(array_flip(
```

There are a couple more.

**Comment by Seldaek** [comment]
Yes, that's because we only prefix those that get optimized by the PHP compiler using https://cs.symfony.com/doc/rules/function_notation/native_function_invocation.html 's compiler_optimized option.

The rest is useless visual noise IMO

**Comment by Seldaek** [comment]
Sure, if you can do that then you can also just run whatever code you want. I am not interested in protecting against people shooting themselves in the foot.
