### ISSUE TITLE
Composer's bash completion breaks Apt bash completion

### ISSUE THREAD

**Issue by 1ma** [composer/composer#12015]
Steps to reproduce:

1. On a fresh Debian install (with an empty `/etc/bash_completion.d/` folder), check that apt completion works:
```shell
$ sudo apt install php<tab><tab>
Display all 2403 possibilities? (y or n)
```

2. Install Composer's bash completion script as described in `$ composer help completion`:

```shell
$ composer completion bash | sudo tee /etc/bash_completion.d/composer
```

3. Open a new shell and test both Composer's and Apt's autocompletion. The former works but the latter do not.
```shell
$ composer in<tab><tab>
info     init     install  
$ sudo apt install php<tab><tab>
```

**Comment by Seldaek** [comment]
I can reproduce on Ubuntu 24.04 as well.. Very weird. It can complete `sudo apt in` to install, but then it stops working.

@GromNaN do you have any clue what could cause this?

**Comment by Seldaek** [comment]
Found the root cause I believe https://github.com/symfony/symfony/pull/57853

**Comment by 1ma** [comment]
Whoa, truly like a needle in a haystack. Impressive.

**Comment by Seldaek** [comment]
Have you tried commenting that line out? Does it also fix it for you?

**Comment by Seldaek** [comment]
Waiting for a symfony release to update the code here, then I'll mark this fixed.
