### ISSUE TITLE
Composer 2.7.7 getting error with PHPUnit 10 command

### ISSUE THREAD

**Issue by nishant04412** [composer/composer#12014]
**Summary:**

I am trying to upgrade my application from PHPUnit 9 to 10 and PHPUnit 10 has many backward incompatible changes and I am getting error while trying to extend composer file from default package.

My `composer.json`:

```json
{
  "name": "app/composer",
  "require": {
    "php": "~7.4.0||~8.1.0||~8.2.0||~8.3.0",
    "composer/composer": "^2.0",
    "symfony/console": "~4.4.0||~5.4.0||~6.4.0"
  },
  "require-dev": {
    "phpunit/phpunit": "^9 || ^10"
  },
}
```

When I run this command: 

```
1. composer install
2. vendor/bin/phpunit
```

I get the following output: 

```
PHP Fatal error:  Uncaught Error: Call to a member function unregister() on null in /opt/homebrew/var/www/phpunit10/composer/vendor/composer/composer/src/Composer/Console/Application.php:139
Stack trace:
#0 /opt/homebrew/var/www/phpunit10/composer/vendor/phpunit/phpunit/phpunit(104): Composer\Console\Application->__destruct()
#1 /opt/homebrew/var/www/phpunit10/composer/vendor/bin/phpunit(122): include('/opt/homebrew/v...')
#2 {main}

Next Error: Call to a member function unregister() on null in /opt/homebrew/var/www/phpunit10/composer/vendor/composer/composer/src/Composer/Console/Application.php:139
Stack trace:
#0 /opt/homebrew/var/www/phpunit10/composer/vendor/phpunit/phpunit/phpunit(104): Composer\Console\Application->__destruct()
#1 /opt/homebrew/var/www/phpunit10/composer/vendor/bin/phpunit(122): include('/opt/homebrew/v...')
#2 {main}
  thrown in /opt/homebrew/var/www/phpunit10/composer/vendor/composer/composer/src/Composer/Console/Application.php on line 139

Fatal error: Uncaught Error: Call to a member function unregister() on null in /opt/homebrew/var/www/phpunit10/composer/vendor/composer/composer/src/Composer/Console/Application.php:139
Stack trace:
#0 /opt/homebrew/var/www/phpunit10/composer/vendor/phpunit/phpunit/phpunit(104): Composer\Console\Application->__destruct()
#1 /opt/homebrew/var/www/phpunit10/composer/vendor/bin/phpunit(122): include('/opt/homebrew/v...')
#2 {main}

Next Error: Call to a member function unregister() on null in /opt/homebrew/var/www/phpunit10/composer/vendor/composer/composer/src/Composer/Console/Application.php:139
Stack trace:
#0 /opt/homebrew/var/www/phpunit10/composer/vendor/phpunit/phpunit/phpunit(104): Composer\Console\Application->__destruct()
#1 /opt/homebrew/var/www/phpunit10/composer/vendor/bin/phpunit(122): include('/opt/homebrew/v...')
#2 {main}
  thrown in /opt/homebrew/var/www/phpunit10/composer/vendor/composer/composer/src/Composer/Console/Application.php on line 139
```

And I expected this to happen:

All required Unit Tests are passing but I am also getting above error after tests info. I wanted it to run smoothly with correct phpunit output. It shows error in `vendor/composer/composer/src/Composer/Console/Application.php`

I am not sure whether this is an error from phpunit or if composer is incompatible with PHPUnit 10. Any help/insights would be appreciated.

**Comment by fredden** [comment]
When I follow the steps provided, I get an error at the `composer install` step about the contents of `composer.json` not being valid JSON. When I fix this and successfully run `composer update`, I get PHPUnit version 10.5.20 installed. With this installed, running `vendor/bin/phpunit` gives usage information for PHPUnit and not the error described here. Please can you update the steps provided to demonstrate the error you're getting?

**Comment by Seldaek** [comment]
Do you somehow mock the application class? The only way that I see this error would happen is if the Application constructor was not executed, but then __destruct gets executed and that signalHandler property is null. https://github.com/composer/composer/blob/11e5237ad9d9e8f29bdc57d946f87c816320d863/src/Composer/Console/Application.php#L139

**Comment by nishant04412** [comment]
@Seldaek Thank you for the suggestion. It was indeed the issue that Application constructor was not getting executed. There was a test which was using Application class mock for some functionality check.

@fredden Thank you for trying to reproduce the issue and for your insights.

The issue is resolved now so closing this issue.
