### ISSUE TITLE
Your lock file does not contain a compatible set of packages. Please run composer update.

### ISSUE THREAD

**Issue by ankitvermauae** [composer/composer#12023]
Problem 1
    - Root composer.json requires php ^8.1 but your php version (8.0.30) does not satisfy that requirement.
  Problem 2
    - brick/math is locked to version 0.12.1 and an update of this package was not requested.
    - brick/math 0.12.1 requires php ^8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 3
    - doctrine/event-manager is locked to version 2.0.1 and an update of this package was not requested.
    - doctrine/event-manager 2.0.1 requires php ^8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 4
    - doctrine/lexer is locked to version 3.0.1 and an update of this package was not requested.
    - doctrine/lexer 3.0.1 requires php ^8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 5
    - egulias/email-validator is locked to version 4.0.2 and an update of this package was not requested.
    - egulias/email-validator 4.0.2 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 6
    - laravel/framework is locked to version v10.48.14 and an update of this package was not requested.
    - laravel/framework v10.48.14 requires php ^8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 7
    - laravel/prompts is locked to version v0.1.24 and an update of this package was not requested.
    - laravel/prompts v0.1.24 requires php ^8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 8
    - lcobucci/jwt is locked to version 5.3.0 and an update of this package was not requested.
    - lcobucci/jwt 5.3.0 requires php ~8.1.0 || ~8.2.0 || ~8.3.0 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 9
    - league/csv is locked to version 9.16.0 and an update of this package was not requested.
    - league/csv 9.16.0 requires php ^8.1.2 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 10
    - league/uri is locked to version 7.4.1 and an update of this package was not requested.
    - league/uri 7.4.1 requires php ^8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 11
    - league/uri-interfaces is locked to version 7.4.1 and an update of this package was not requested.
    - league/uri-interfaces 7.4.1 requires php ^8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 12
    - monolog/monolog is locked to version 3.6.0 and an update of this package was not requested.
    - monolog/monolog 3.6.0 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 13
    - nette/schema is locked to version v1.3.0 and an update of this package was not requested.
    - nette/schema v1.3.0 requires php 8.1 - 8.3 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 14
    - ramsey/collection is locked to version 2.0.0 and an update of this package was not requested.
    - ramsey/collection 2.0.0 requires php ^8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 15
    - rollbar/rollbar-laravel is locked to version v8.0.1 and an update of this package was not requested.
    - rollbar/rollbar-laravel v8.0.1 requires php ^8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 16
    - spatie/laravel-backup is locked to version 8.8.1 and an update of this package was not requested.
    - spatie/laravel-backup 8.8.1 requires php ^8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 17
    - spatie/laravel-ignition is locked to version 2.8.0 and an update of this package was not requested.
    - spatie/laravel-ignition 2.8.0 requires php ^8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 18
    - symfony/console is locked to version v6.4.8 and an update of this package was not requested.
    - symfony/console v6.4.8 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 19
    - symfony/deprecation-contracts is locked to version v3.5.0 and an update of this package was not requested.
    - symfony/deprecation-contracts v3.5.0 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 20
    - symfony/error-handler is locked to version v6.4.8 and an update of this package was not requested.
    - symfony/error-handler v6.4.8 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 21
    - symfony/event-dispatcher is locked to version v6.4.8 and an update of this package was not requested.
    - symfony/event-dispatcher v6.4.8 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 22
    - symfony/event-dispatcher-contracts is locked to version v3.5.0 and an update of this package was not requested.
    - symfony/event-dispatcher-contracts v3.5.0 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 23
    - symfony/finder is locked to version v6.4.8 and an update of this package was not requested.
    - symfony/finder v6.4.8 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 24
    - symfony/http-foundation is locked to version v6.4.8 and an update of this package was not requested.
    - symfony/http-foundation v6.4.8 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 25
    - symfony/http-kernel is locked to version v6.4.8 and an update of this package was not requested.
    - symfony/http-kernel v6.4.8 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 26
    - symfony/mailer is locked to version v6.4.8 and an update of this package was not requested.
    - symfony/mailer v6.4.8 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 27
    - symfony/mime is locked to version v6.4.8 and an update of this package was not requested.
    - symfony/mime v6.4.8 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 28
    - symfony/process is locked to version v6.4.8 and an update of this package was not requested.
    - symfony/process v6.4.8 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 29
    - symfony/routing is locked to version v6.4.8 and an update of this package was not requested.
    - symfony/routing v6.4.8 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 30
    - symfony/service-contracts is locked to version v3.5.0 and an update of this package was not requested.
    - symfony/service-contracts v3.5.0 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 31
    - symfony/string is locked to version v6.4.8 and an update of this package was not requested.
    - symfony/string v6.4.8 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 32
    - symfony/translation is locked to version v6.4.8 and an update of this package was not requested.
    - symfony/translation v6.4.8 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 33
    - symfony/translation-contracts is locked to version v3.5.0 and an update of this package was not requested.
    - symfony/translation-contracts v3.5.0 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 34
    - symfony/uid is locked to version v6.4.8 and an update of this package was not requested.
    - symfony/uid v6.4.8 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 35
    - symfony/var-dumper is locked to version v6.4.8 and an update of this package was not requested.
    - symfony/var-dumper v6.4.8 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 36
    - watson/validating is locked to version 8.2.0 and an update of this package was not requested.
    - watson/validating 8.2.0 requires php ^8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 37
    - symfony/cache is locked to version v6.4.8 and an update of this package was not requested.
    - symfony/cache v6.4.8 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 38
    - symfony/cache-contracts is locked to version v3.5.0 and an update of this package was not requested.
    - symfony/cache-contracts v3.5.0 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 39
    - symfony/filesystem is locked to version v6.4.8 and an update of this package was not requested.
    - symfony/filesystem v6.4.8 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 40
    - symfony/http-client is locked to version v6.4.8 and an update of this package was not requested.
    - symfony/http-client v6.4.8 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 41
    - symfony/http-client-contracts is locked to version v3.5.0 and an update of this package was not requested.
    - symfony/http-client-contracts v3.5.0 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 42
    - symfony/options-resolver is locked to version v6.4.8 and an update of this package was not requested.
    - symfony/options-resolver v6.4.8 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 43
    - symfony/stopwatch is locked to version v6.4.8 and an update of this package was not requested.
    - symfony/stopwatch v6.4.8 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 44
    - symfony/var-exporter is locked to version v6.4.8 and an update of this package was not requested.
    - symfony/var-exporter v6.4.8 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
  Problem 45
    - symfony/deprecation-contracts v3.5.0 requires php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
    - fakerphp/faker v1.23.1 requires symfony/deprecation-contracts ^2.2 || ^3.0 -> satisfiable by symfony/deprecation-contracts[v3.5.0].
    - fakerphp/faker is locked to version v1.23.1 and an update of this package was not requested.

C:\xampp\htdocs\snipe-it>

**Comment by stof** [comment]
All those problems seem related to the same root cause, which is clearly described in the first one: you are running composer using PHP 8.0.30 while the project requires PHP >=8.1
