### ISSUE TITLE
How to recover composer

### ISSUE THREAD

**Issue by xubinzhai** [composer/composer#12022]

**Comment by dumprino** [comment]
**composer update**

**Comment by dumprino** [comment]
passo a passo 👍 
- composer install
- composer update
- clear cache
logo apos isso, você ficará livre de possíveis erros, bag´s etc .......
( CASO PRA VOCÊ NÃO FUNCIONE ) 
poste aqui os Erros recebidos

**Comment by Seldaek** [comment]
Sorry but no clue how to help here..
