### ISSUE TITLE
updating only the url of a local package does not update installed.json - breaks later `composer status` 

### ISSUE THREAD

**Issue by gggeek** [composer/composer#12034]
Using composer 7.2.2 as starting point, i did the following:

1. have this in composer.json

```
        {
            "type": "package",
            "package": {
                "type": "wordpress-plugin",
                "name": "woocommerce/woocommerce-checkout-field-editor",
                "version": "1.7.12",
                "dist": {
                    "url": "packages/woocommerce-checkout-field-editor.zip",
                    "type": "zip"
                }
            }
        },
```

2. set up the app via `composer install`
3. later, bump some deps and change the above block to use the same version, but a different zip file:
```
        {
            "type": "package",
            "package": {
                "type": "wordpress-plugin",
                "name": "woocommerce/woocommerce-checkout-field-editor",
                "version": "1.7.12",
                "dist": {
                    "url": "packages/woocommerce-checkout-field-editor-1.7.12.zip",
                    "type": "zip"
                }
            }
        },
```
4. run `composer update`
5. modify a php file within the installed woocommerce-checkout-field-editor package
6. upgrade to composer 2.7.7
7. run `composer status` -> all ok: the modified file is reported (nb: this led to a crash with composer 2.7.2)
8. run `composer status -v` -> I get an error message: `Failed to detect changes: [Composer\Downloader\TransportException] The "packages/woocommerce-checkout-field-editor.zip" file could not be downloaded: Failed to open stream: No such file or directory`

A little investigation points in the direction of `vendor/composer/installed.json` not having been updated at step 4, whereas `composer.lock` did get updated properly

**Comment by Seldaek** [comment]
If you run composer update / step 4 with composer 2.7.7 does it work? If yes then it's fixed IMO. If not I might need to look into it.

**Comment by gggeek** [comment]
Lol crafty response.
I did not try that back-to-the-future approach as it would not have helped my situation but I agree that it could be considered an issue-resolver.
Will give it a try

**Comment by Seldaek** [comment]
If you know which file you modified you could still run the update with new composer then make sure the file is still containing your changes then run status again.. But otherwise you can also edit the url in installed.json directly to update it yourself if running composer update with latest composer is not an option

**Comment by gggeek** [comment]
Ok, new test done:

all with Composer 2.7.7:
- started with `composer.json`, `composer.lock` and `installed.json` in sync
- manually changes the name of the file used as package source (tarball) in composer.json
- run `composer update the/package`. Got:
        Loading composer repositories with package information
        Updating dependencies
        Nothing to modify in lock file
        Writing lock file
        Installing dependencies from lock file (including require-dev)
        Nothing to install, update or remove
        Generating autoload files
        35 packages you are using are looking for funding.
- composer did update `composer.lock`, `installed.php` but not `installed.json`
- manually modified a file in the package which was installed from the local tarball
- ran `composer status` and `composer status -v`
- in both cases, the original error was not triggered, and the modified file was reported correctly

So it seems that the bug is fixed - even though the `installed.json` file still does not get updated with the renamed tarball "url".

I guess this ticket can be closed - I'll open a new one if I manage to find another similar weird corner case :-)

**Comment by Seldaek** [comment]
Yeah I find it surprising that it would all work except for installed.json not updating, that sounds weird, but I cannot easily reproduce without access to all your stuff, so I guess yes let's close for now.
