### ISSUE TITLE
Try to set up stripe in person payment

### ISSUE THREAD

**Issue by alejandroisla97** [composer/composer#12030]
Hi, I'm new to stripe integration using php, I don't have the slightest idea what I'm doing. I was following the guide using compose and I couldn't get anything to work
https://docs.stripe.com/terminal/quickstart
This is the guide I'm trying to follow. I have some doubts, should the "vendor" folder be in the root next to "public"? I am using xampp as a php server in my physical store, any recommendations?

I have tried several things, first the system did not start and gave an error, I solved this using php -S 127.0.0.1:4242 --docroot=htdocs/public while starting the code from the php console. After that I have followed several guides and nothing, I can't get it to do anything at all, the worst thing is that it doesn't show errors or anything to be able to solve them, it doesn't do anything

I am trying to use WisePos e in my physical store using a php page

![Captura de pantalla 2024-07-01 163616](https://github.com/composer/composer/assets/174385042/581c332f-f5bb-4c36-bc0e-88a80d3b6d43)
This is my htdocs folder for xampp, I don't know if "vendor" goes there because following the steps in the guide the folder was originally created in the xampp root

**Comment by Seldaek** [comment]
> I don't have the slightest idea what I'm doing

At least you warned us.. but really this github repo has nothing to do with stripe.

vendor does not have to be in the htdocs/public folder IMO, as it will make it publicly accessible, which is typically bad practice. The vendor files need to be accessible on the web server once you upload it there, but typically you would have your project setup like this for security reasons:

```
/project-path
  /src
    /projectCode.php
  /web // configure the web server to load files from this directory (document root)
    /index.php // this is the so-called front controller which would include and run the application code, and is usually the only php file present in the web accessible directory
  /vendor
```
