### ISSUE TITLE
Possibility to temporary disable the dev autoloaded dependencies

### ISSUE THREAD

**Issue by alexander-schranz** [composer/composer#12040]
I'm using the Symfony framework and use the lint container command to check if my container builts correctly. Accidently it did appear that I did use "dev" dependency inside a service which did fail then on prod without being catched by lint:container command in the CI.

So I currently worked around it by using before the lint prod container command `composer dump-autoload --optimize --no-dev` and after it `composer dump-autoload`. This sadly has sideeffects for the developer experience example I run my `composer lint` command parallelly locally to `composer test` (phpunit) and changing the autoloader does fail when using this:

My `composer.json`:

```json
{
     "scripts": {
        "lint": [
            "@lint-composer",
            "@lint-container"
        ],
        "lint-composer": "@composer validate --no-check-publish --strict",
        "lint-container": [
            "@php bin/console lint:container --env dev",
            "@php bin/console lint:container --env test",
            "@composer dump-autoload --optimize --no-dev",
            "@php bin/console lint:container --env prod",
            "@composer dump-autoload"
        ]
     }
}
```

So I'm thinking if it may be possible to disable the DevAutoloader only for the a specific process without have to redump it:

```json
{
    "scripts": {
        "lint": [
            "@lint-composer",
            "@lint-container"
        ],
        "lint-composer": "@composer validate --no-check-publish --strict",
        "lint-container": [
            "@php bin/console lint:container --env dev",
            "@php bin/console lint:container --env test",
            "Composer\\Config::disableDevAutoloader",
            "@php bin/console lint:container --env prod"
        ]
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK git version 2.45.2
Checking http connectivity to packagist: OK
Checking https connectivity to packagist:
OK
Checking github.com oauth access: OK expires on 2025-01-14 23:00:00 UTC
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking Composer version: OK
Checking Composer and its dependencies for vulnerabilities: OK
Composer version: 2.7.7
PHP version: 8.1.25 - Package overridden via config.platform, actual: 8.3.9
PHP binary path: /opt/homebrew/Cellar/php/8.3.9/bin/php
OpenSSL version: OpenSSL 3.3.1 4 Jun 2024
curl version: 8.8.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/3.3.1
zip: extension present, unzip present, 7-Zip not available
```

When I run this command: 

```
composer lint
```

I get the following output: 

```
All fine
```

And I expected this to happen:

Fail if lint:container would not find the dev class and have possibility to maybe disable dev dependencies being loaded even if they are dumped.

**Comment by Seldaek** [comment]
Not really possible without major rework IMO, as we do not keep track of which packages/files/configs are for dev and non-dev dependencies in the autoloader configs.. So a full redump is required right now, and I don't see this changing any time soon sorry :)

**Comment by alexander-schranz** [comment]
@Seldaek Still thank you for the feedback, I understand was not sure how difficult it may be is  and how the dev dependencies are handled in the autoloader, but if it require major I understand to not add it.
