### ISSUE TITLE
Add composer audit --ignore-abandoned or --abandoned=ignore

### ISSUE THREAD

**Issue by nicolas-grekas** [composer/composer#12070]
That'd make it easier to integrate `composer audit` into CIs (the env var is not always as convenient nor explicit depending on how they're setup on CIs)

**Comment by mzhubail** [comment]
I think this can be added with the precedence of "command line option" > "environment variable" > "config".

I can pick this up, but I'll wait first for the project maintainers assessment.

**Comment by Seldaek** [comment]
Yup sounds good to me. If you want to PR please do :)

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/pull/12091
