### ISSUE TITLE
Local symlinked repository creates absolute symlink even with `relative: true`

### ISSUE THREAD

**Issue by janedbal** [composer/composer#12074]
Consider following setup:

- Main app located in `app`
- Dependency package `some/dep` located in `dep`
- Docker setup in `app/docker-compose.yml` uses following volumes:
```yml
volumes:
      - ./:/app/:cached
      - ../dep/:/dep/:cached
```
- Composer setup in `app/composer.json` uses the dependency as symlink:

```json
{
    "require": {
         "some/dep": "*",
    },
    "repositories": [
        {
            "type": "path",
            "url": "../dep/",
            "options": {
                "symlink": true,
                "relative": true
            }
        }
    ]
}
```

Now, running `composer install` inside docker causes **the symlink to be created with absolute path**. This results in:

```bash
# inside docker
$ file vendor/some/dep
vendor/some/dep: symbolic link to /dep/
```

```bash
# outside docker
$ file vendor/some/dep
vendor/some/dep: broken symbolic link to /dep/
```

This causes **PHPStorm** (running outside docker) **not to be able to find the dependency** and marks all symbols as unknown.

---------

After some debugging I found that this got broken by [this hacky thing](https://github.com/composer/composer/pull/11169). Removing [those lines](https://github.com/composer/composer/blob/d3d378184bf1ae88abb1c3c9f8d0c26de5ea2744/src/Composer/Util/Filesystem.php#L473-L476) from composer's source fixes the issue and the symlink is created properly, using relative definition (working both inside and outside of docker):

```bash
$ file vendor/some/dep
vendor/some/dep: symbolic link to ../../../dep/
```

-------

Can you guide me how the fix PR should look like to be accepted? Thanks

**Comment by Seldaek** [comment]
See #12092 - if you can try it and confirm whether that fixes it for you that would be great.

**Comment by janedbal** [comment]
Thanks! 

Is there an easy way to download composer.phar built from latest main branch?

**Comment by Seldaek** [comment]
Yes - `composer self-update --snapshot`

**Comment by janedbal** [comment]
I can confirm latest snapshot fixes the issue, thank you!
