### ISSUE TITLE
Recreate missing binary symlinks/proxy files

### ISSUE THREAD

**Issue by Sgoettschkes** [composer/composer#1209]
If a binary symlink or binary proxy file is missing after install/update, it should be recreated.

For me this would be expected behaviour. If a binary symlink is missing for some reason, it should be there after an install or update. 

The reason I'm asking is because I deleted one of the binary files (composer-php) and pdepend could not be executed anymore. Executing composer once more could not solve the problem.

**Comment by ccharles** [comment]
:+1:

I suppose that the work [started in April, 2013](https://github.com/composer/composer/issues/1209#issuecomment-17150581) by @Sgoettschkes has stalled?

**Comment by Sgoettschkes** [comment]
Yeah, the task was a bit to much for me. I started working through the code base but could not really figure it out. Maybe I'll give it another try but not anytime soon. If somebody would like to take over, please do!
I am sorry I did not get back in time, I really forgot about it tbh.

**Comment by fcastillo-es** [comment]
:+1:

**Comment by mauricios** [comment]
+1

**Comment by pfuhrmann** [comment]
+1

**Comment by edvinasme** [comment]
@pfuhrmann I have tested this, and it's enough to remove only `vendor/` directory inside your project to get symlinks in `bin/` folder regenerated.

**Comment by geshan** [comment]
this will be a good feature to have.

**Comment by ethanpooley** [comment]
+1. In my case, while testing Vagrant on Windows hosts, there was a problem with the file share that resulted in no symlinks being created on the first run of `composer install`. Yet on the second run, after the problem was fixed, Composer thought everything was fine.

**Comment by JakeWorrell** [comment]
+1 here too. I want to set up my deployment scripts to copy the previous vendor directory and then let composer recreate the bin directory when running `composer install`. Copying the previous vendor directory makes a massive difference to deployment times, but this bin directory issue causes us serious problems

**Comment by Hendra-Huang** [comment]
+1

**Comment by christopher-hopper** [comment]
Once this new feature is completed it would be good to have some `composer update` and `composer install` parameters or switches that allowed:

- Overwrite existing vendor binaries if there is a name conflict
- Force recreate of vendor binaries

I ran into this problem where, during a `composer install` the vendor binaries were not created for the project I was in because composer reported:

    Skipped installation of bin foobar for package foo/bar: name conflicts with an existing file

While your new feature will help to resolve this, it would be nice to also just force the overwrite using a command-line parameter or switch.

**Comment by KamilKopaczyk** [comment]
Maybe there should be some disclaimer in the documentation, until the issue gets fixed?
It took me a while to track this problem down.

**Comment by mbrevda** [comment]
+1 - having issues with Wercker CI when running tests locally in docker. As many here have reported, the vendor/ dir is included in the container, but all the bin links point to the wrong place. While it would seem that a simple workaround would be to just reinstall dependencies from source, this makes debugging 1000x harder.

**Comment by j0k3r** [comment]
I've started something here: https://github.com/composer/composer/pull/5127
