### ISSUE TITLE
Update autocompletion documentation

### ISSUE THREAD

**Issue by bobvandevijver** [composer/composer#12099]
The documentation current forwards to an external project to install console autocompletion

https://github.com/composer/composer/blob/e4038e5e3bffe22cb815dc1663ea76be96d4222e/doc/03-cli.md?plain=1#L1089

But shouldn't that either refer to `composer help completion` or contain an example such as `composer completion bash | sudo tee /etc/bash_completion.d/composer`?

**Comment by Seldaek** [comment]
Oh yes that's very outdated thanks :D
