### ISSUE TITLE
`COMPOSER_ROOT_VERSION` seems to have stopped working

### ISSUE THREAD

**Issue by sebastianbergmann** [composer/composer#12101]
Dependencies of `phpunit/phpunit` such as `sebastian/code-unit` have a `requires-dev` dependency on `phpunit/phpunit`, see https://github.com/sebastianbergmann/code-unit/blob/main/composer.json#L22-L24.

At the `11.3.3` tag, `phpunit/phpunit` has a dependency on `sebastian/code-unit` version `^3.0.1`, see https://github.com/sebastianbergmann/phpunit/blob/11.3.3/composer.json#L41.

In the CI pipeline of `sebastian/code-unit` we set `COMPOSER_ROOT_VERSION` (see https://github.com/sebastianbergmann/code-unit/blob/main/.github/workflows/ci.yaml#L9-L10) to the branch alias configured in `composer.json` (see https://github.com/sebastianbergmann/code-unit/blob/main/composer.json#L47-L49).

Here is the error I get:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpunit/phpunit[11.3.0, ..., 11.3.3] require sebastian/code-unit ^3.0.1 -> satisfiable by sebastian/code-unit[dev-main, 3.0.1, 3.0.x-dev (alias of dev-main)] from composer repo (https://repo.packagist.org) but sebastian/code-unit is the root package and cannot be modified. See https://getcomposer.org/dep-on-root for details and assistance.
    - Root composer.json requires phpunit/phpunit ^11.3 -> satisfiable by phpunit/phpunit[11.3.0, 11.3.1, 11.3.2, 11.3.3].
```

I can reproduce the above with Composer 2.7.2-2.7.9:

- https://github.com/sebastianbergmann/code-unit/actions/runs/10749822313
- https://github.com/sebastianbergmann/code-unit/actions/runs/10749849753
- https://github.com/sebastianbergmann/code-unit/actions/runs/10749854528
- https://github.com/sebastianbergmann/code-unit/actions/runs/10749866240
- https://github.com/sebastianbergmann/code-unit/actions/runs/10749871782
- https://github.com/sebastianbergmann/code-unit/actions/runs/10749879653
- https://github.com/sebastianbergmann/code-unit/actions/runs/10749881159
- https://github.com/sebastianbergmann/code-unit/actions/runs/10749882723

I did not go further back in time than Composer 2.7.2, sorry.

I also get the error when `actions/checkout` is configured to fetch all history for all branches and tags as can be seen here: https://github.com/sebastianbergmann/code-unit/actions/runs/10749929725

**Comment by sebastianbergmann** [comment]
I just noticed that if I set `COMPOSER_ROOT_VERSION=3.0.1` (https://github.com/sebastianbergmann/code-unit/commit/0e262fc998a4dcfb52358723cb531705ece1078a) then Composer 2.7.9 installs PHPUnit 11.3.3 (https://github.com/sebastianbergmann/code-unit/actions/runs/10750098718/job/29815834216).

With `COMPOSER_ROOT_VERSION=3.0-dev` (https://github.com/sebastianbergmann/code-unit/commit/fdf04f0141423b70ad7f5924f4de443bff414013), Composer 2.7.9 installs PHPUnit 11.2.6 (https://github.com/sebastianbergmann/code-unit/actions/runs/10750099649/job/29815836370). This must be last version where `^3.0` was used as the version constraint for `sebastian/code-unit` (https://github.com/sebastianbergmann/phpunit/blob/11.2.6/composer.json#L41).

This very likely means that the change in behaviour I observed today is not caused by change in Composer, but rather by changing the version constraint from `^3.0` to `^3.0.1`. If that is the case, then this is, of course, not a bug report but rather a support request: considering the fact that I do not want to bump the value `COMPOSER_ROOT_VERSION` is set to in CI whenever a new release is made, how should I proceed? Thank you!

**Comment by sebastianbergmann** [comment]
I just stumbled upon https://github.com/sebastianbergmann/php-code-coverage/pull/1040 by @localheinz. Applying the same change (https://github.com/sebastianbergmann/code-unit/commit/07fc317291d7c7cf1abb980b7aa0d92862bc13a9) seems to have solved this problem for me (https://github.com/sebastianbergmann/code-unit/actions/runs/10750170615/job/29816005537).

Sorry for the noise, I feel really stupid now.

**Comment by Seldaek** [comment]
Yeah ok I see what happened here I think.

3.0.x-dev has an internal representation of 3.0.9999999.9999999-dev

While 3.0-dev has an internal representation of 3.0.0.0-dev. The .x is key here.

Now in branch-aliases, and when parsing branch names, for convenience and because we know what people mean in those contexts, we add the .x automatically before normalizing.

But when you use COMPOSER_ROOT_VERSION we don't do that, it just takes it as a plain version to be normalized. Possibly we should also auto-append the .x there as the main use of this env var is CI, and also it's unlikely you'd ever want `3.0-dev` to mean `3.0.0-dev` in that context as well.

Reopening to keep track of this.
