### ISSUE TITLE
Ctrl+C does not cancel interactive prompts

### ISSUE THREAD

**Issue by cweiske** [composer/composer#12106]
Pressing Ctrl+C in interactive inputs does not exit composer.

----

My `composer.json`: irrelevant

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK git version 2.37.0
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK does not expire
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking Composer version: OK
Checking Composer and its dependencies for vulnerabilities: OK
Composer version: 2.7.9
PHP version: 7.4.30 - Package overridden via config.platform, actual: 8.3.10
PHP binary path: /usr/bin/php8.3
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
curl version: 7.81.0 libz 1.2.11 ssl OpenSSL/3.0.2
zip: extension present, unzip present, 7-Zip present (7z)
```

When I run this command:

```
composer instlal
```

I get the following output:

```

                                     
  Command "instlal" is not defined.  
                                     

 Do you want to run "install" instead?  (yes/no) [no]:
 > ^C^C^C^C^C^C^C^C^C^C^C
```

And I expected this to happen:

As soon as I press Ctrl+C, composer shall exit.
Pressing Ctrl+C in interactive inputs does not do that.

I press Ctrl+C and then have to press return/enter to exit composer.

**Comment by Seldaek** [comment]
I can reproduce, but this is something that should be tackled in symfony/console, if it is fixable at all.

https://github.com/symfony/symfony/pull/48287 has related work, but it seems kinda stalled, so I wouldn't hold my breath here, and I'll close the issue here in the meantime as I don't really see what I can do about it.

**Comment by Seldaek** [comment]
Looks like it's a problem with signal handlers + ctrl-C while fgets is blocking.

This script reproduces it:

```php
<?php

pcntl_async_signals(true);
pcntl_signal(SIGINT, function () {
    echo 'CAUGHT CTRL-C';
    exit(1);
});

echo 'Enter something or Ctrl-C: ';
var_dump(fgets(STDIN, 100));
```

The core of the problem in Composer is this here https://github.com/composer/composer/blob/main/src/Composer/Console/Application.php#L111-L115 - removing that fixes it, but I'm not entirely sure yet that it has no negative impact.
