### ISSUE TITLE
Integrate PSR-3 logger to autoloader

### ISSUE THREAD

**Issue by Chi-teck** [composer/composer#12118]
This could be handy for tracing application performance. Especially when configuring autoload-map or preload script.
Also it might be useful for integrating with some tracing tools like open telemetry.

By default composer could use some sort of NullLogger allowing users to  pass real logger.

**Comment by Seldaek** [comment]
Also make sure you follow the guidelines here to ensure optimal autoload speed https://getcomposer.org/doc/articles/autoloader-optimization.md - then it should really be no concern how many classes you load IMO.

**Comment by Chi-teck** [comment]
Yep, just found similar workaround.
```php
$autoloader = require_once 'autoload.php';
\spl_autoload_register(function($class) {
  var_dump('Loading '.$class);
}, prepend: true);
```
Unfortunately this won't help to trace whether class was loaded from class map or from PSR-4 rule.

**Comment by Seldaek** [comment]
Right, but if you properly optimize it does not matter as psr-4 rules get converted to classmap as well, so there is no overhead to psr-4 at runtime.

**Comment by Chi-teck** [comment]
On my application the class loading is a bottleneck.

Here is what I did to test it.

1. Put  PHP classes in use (~1300) to class map and dumped autoload configuration with `--apcu` option.
2. I checked with xdebug that autoloader takes classes from the generated class map.
3. Added the following snippet to index.php file of my site (Drupal 10)
```php
$autoloader = require_once 'autoload.php';

$app_start = microtime(true);
$autoload_duration = 0.0;
$total_classes = 0;

$autoloader->unregister();
spl_autoload_register(function ($class) use ($autoloader, &$autoload_duration, &$total_classes) {
  $start = microtime(true);
  $autoloader->loadClass($class);
  $end = \microtime(true);
  $autoload_duration += ($end - $start);
  $total_classes++;
});
```
4. Opened the front page as anonymous (without xdebug)

Here is the result
```
Application duration: 17.060 ms
Autoload duration: 4.772 ms
Total classes: 649
```

The "autoload duration" varies a big deal. Some times it goes up to 10 ms. However, if I request the page often it always goes down to 1-2 ms. That might be due some microcache on file system level. This inconsistency in results make it hard to make a benchmark with load testing tools like k6.

For the record. Here are the benchmark with `opcache.preload` enabled
```
Application duration: 14.944 ms
Autoload duration: 0.055 ms
Total classes: 5
```

**Comment by Chi-teck** [comment]
> The "autoload duration" varies a big deal. Some times it goes up to 10 ms. However, if I request the page often it always goes down to 1-2 ms.

Found the reason, that was caused by to low `opcache.revalidate_freq` (2 sec).

**Comment by Seldaek** [comment]
Yeah opcache should ideally not revalidate for high performance, and be manually cleared on deploy. Or use preload of course.
