### ISSUE TITLE
Increase funding awareness

### ISSUE THREAD

**Issue by stefanak-michal** [composer/composer#12130]
I would like to suggest a feature. Right now when you install packages which has option for donate/funding, composer just informs you how many packages has this property. It would be nice if we can raise awareness about it and I was thinking, maybe it shouldn't be just information poping into console, but it would be a question, something like this:

```
There are 12 packages looking for funding, would you like to contribute? [Yes/No]:
```

Default answer would be yes, if you just press enter.

The question is, what happens next. I'm not so sure about it but I thought it would open website with list of these packages. Each package would have checked checkbox and there will be input for money to donate. After sending it will be split equally between these checked packages.

_And because composer is used to perform this action it could be always included in that list._

**Comment by Seldaek** [comment]
Sorry but while I appreciate the good intentions here, I don't think it's reasonable to either block install/update with some prompt, nor to expect us to build a portal to pay money to random packages. This opens up a ton of legal / tax issues which I don't have time to explore, and even GitHub Sponsors is very handwavy about. There are enough platforms that exist if people want to pay maintainers, and one more warning is not gonna move the needle there I am afraid.
