### ISSUE TITLE
`--strict-ambiguous` not working for some duplicates within project

### ISSUE THREAD

**Issue by janedbal** [composer/composer#12140]
I really like this [new option](https://github.com/composer/composer/pull/12119) in 2.8, but I think it should be much more strict. 

Documentation states:

```
--strict-ambiguous: Return a failed exit code (2) if the same class is found in multiple files.
```

But that is sadly **not true if the duplicate is present within my project** and not in vendor. Currently, I'm using [name-collission-detector](https://github.com/shipmonk-rnd/name-collision-detector) to find duplicates to ensure no ambiguity, but I think it would much be better to have such check within composer itself.

--------

Here is reproduction repository: https://github.com/janedbal/composer-class-ambiguity-test

**Comment by stof** [comment]
please provide a reproducing cases.

**Comment by stof** [comment]
Looking at your reproducer, the file in `tests` will not report ambiguity because Composer excludes a few folders names from this check: https://github.com/composer/class-map-generator/blob/465b1b0a7a5f3f73e7e4ab1aed3e529ff9bcfb76/src/ClassMapGenerator.php#L194C1-L194C23

However, not reporting the 2 classes in `src` looks weird to me (unless this is because the class is first registered in `tests` and so both classes in `src` are compared to the one in `tests` instead)

**Comment by janedbal** [comment]
Removing the test one make it work. Why do we have such condition there? Feels like some unwanted hack to me.

**Comment by Seldaek** [comment]
I think it's because sometimes test suites redeclare classes to override/mock them.. But that's just a distant memory.. I'll have to check more in depth tomorrow if we can fix this.

**Comment by janedbal** [comment]
> I think it's because sometimes test suites redeclare classes to override/mock them

Would that matter? Everything works even for those kind of craziness, no? They just get bunch of warnings.

**Comment by Seldaek** [comment]
Well the point would be to not warn for patterns we clearly identify as ok/not gonna cause problems in prod. But if two of the same class in src/ don't warn that sounds like a real problem altho there as well there might be valid use cases like conditionally declared classes depending on php versions etc.

**Comment by janedbal** [comment]
Would you consider at least `--strict-ambiguous` to be 100% strict (without excludes like that)?
