### ISSUE TITLE
My composer init is failing to create a composer.json file

### ISSUE THREAD

**Issue by AbispaAsh** [composer/composer#12141]
I downloaded the latest version of composer using composer-setup.exe. 
Now when I try to do composer init, it asks for the basic inputs, and then it gives an error.

```
INFO: Could not find files for the given pattern(s).

                                            
  Welcome to the Composer config generator  
                                            


This command will guide you through creating your composer.json config.

Package name (<vendor>/<name>) [asus/testcomp]:
Description []:
Author [n to skip]: n
Minimum Stability []:
Package Type (e.g. library, project, metapackage, composer-plugin) []:
License []:

In SpdxLicenses.php line 202:
                                         
  Array or String expected, NULL given.  
                                         

init [--name NAME] [--description DESCRIPTION] [--author AUTHOR] [--type TYPE] [--homepage HOMEPAGE] [--require REQUIRE] [--require-dev REQUIRE-DEV] [-s|--stability STABILITY] [-l|--license LICENSE] [--repository REPOSITORY] [-a|--autoload AUTOLOAD]
```

I have tried uninstalling and reinstalling composer but the outcome remains the same. How do I fix this?

**Comment by antalaron** [comment]
the error is in https://github.com/composer/composer/blob/d5e75c21ceeb6829918a75ed63b56c576b4a6261/src/Composer/Command/InitCommand.php#L403

the default value is null, but the validator library does not accept null as argument. it needs to be fixed.

quick fix: downgrade or fill in the license or set the `COMPOSER_DEFAULT_LICENSE` environment variable to a valid license.
