### ISSUE TITLE
Improve diagnose to check the ownership of the `.git` folder

### ISSUE THREAD

**Issue by chadyred** [composer/composer#12158]
Hello,

`composer diagnose` could take care of what `git status` to make things easier to debug.

Actually, we have to find out that git does not trust the git project directory we're in, which isn't communicated in any way when running `composer install` and the error is not related to that at all.

IMO, append more information into the `composer diagnose` in order to indicate if something is wrong with git and the ownership of the .git could be good. In fact, if our repository is not added as safe in git, nothing indicate that.

The error in that case : 

```
fatal: detected dubious ownership in repository at '/app'
To add an exception for this directory, call:

	git config --global --add safe.directory /app
```

To reproduce it is required to git clone `symfony/symfony` for example and mount it on a PHP docker container and make a `composer update`.

See : https://github.com/symfony/symfony/issues/44678#issuecomment-1199411530

If you need more information, don't hesitate to ping me.

**Comment by Seldaek** [comment]
I'd be happy to get more infos yes, what's the symptom of this then, do I understand correctly that it is not able to detect the root package version correctly because git refuses to run on that directory, and then it fails dependency resolution?

If so we could perhaps detect this and warn in the version guessing process.

**Comment by stof** [comment]
@Seldaek yes. In that case, guessing the root version fails, while we are inside a git repository (there is a `.git` folder).

**Comment by chadyred** [comment]
@Seldaek When I want to install dependencies : I run `docker compose run --rm --build php sh -c "git config --global --add safe.directory /workspace &&  composer install"`, in workspace "symfony" project live, it is shared with the ".git", so it is at this moment that composer can't install dependencies because of this ownership. A diagnose to indicate "composer can't install your deps as the ownership of .git is not safe, run a `git status` for more information" something like that.

**Comment by Seldaek** [comment]
Added some warnings/errors, I don't think we can do much more than that but hopefully it helps diagnose the problem quicker.

**Comment by rick1906** [comment]
After this update I started getting 'The repository at "..." does not have the correct ownership and git refuses to use it:' message on every composer install/update for the project running in docker container. My project dev dir with '.git' is mapped from host to that container, and the ownership is unsurprisingly broken inside.

Actually I don't want composer to even use the .git dir on install/update, but it still tries to use it. Workaround is to set "version" explicitly in composer.json.
