### ISSUE TITLE
--dry-run option is missing 

### ISSUE THREAD

**Issue by dseguy** [composer/composer#12182]
When running the following command : 

```
composer dump-autoload --dry-run --optimize --strict-psr
```

The output is 

```
The "--dry-run" option does not exist
```
And I expected the execution of the command without a fatal error.

Composer version was 2.8.2. 
It was working as expected with version 2.8.1  (we reverted to this version to get it running again). 

It doesn't work on Alpine 3.20.  It was run on a Docker environment : 

```
FROM composer/composer:2-bin AS composer_upstream
FROM php:8.3.8-fpm-alpine3.20 AS php_base
```

The command was also tested on OSX, and it works as expected with composer 2.8.1 and 2.8.2.

**Comment by bcremer** [comment]
```Composer version 2.2.24 2024-06-10 22:51:52
backofficedev@backofficedev ~/current (integration) $ composer dumpautoload --optimize --strict-psr --no-interaction


  [Symfony\Component\Console\Exception\RuntimeException]
  The "--strict-psr" option does not exist.

**Comment by alcohol** [comment]
Can you please try again after pulling `composer/composer:2-bin` again? Due to a small mistakes yesterday, the LTS images was also tagged as major version `2`. This has been remedied this morning.

**Comment by alcohol** [comment]
Update: the workflow was not triggered earlier, it has been now, my bad sorry. It should actually be resolved now.
