### ISSUE TITLE
Dockerimage composer/composer:2-bin contains outdated version

### ISSUE THREAD

**Issue by bcremer** [composer/composer#12183]
Pulling the `composer/composer:2-bin` contains a very outdated composer version.
Until yesterday it contained a recent version.

```
$ cat Dockerfile
FROM php:8-alpine

COPY --from=composer/composer:2-bin /composer /usr/bin/composer

$ docker build . -t composer
[+] Building 0.7s (8/8) FINISHED                                                             docker:orbstack
 => [internal] load build definition from Dockerfile                                                    0.0s
 => => transferring dockerfile: 157B                                                                    0.0s
 => [internal] load metadata for docker.io/library/php:8-alpine                                         0.6s
 => [internal] load metadata for docker.io/composer/composer:2-bin                                      0.0s
 => [internal] load .dockerignore                                                                       0.0s
 => => transferring context: 2B                                                                         0.0s
 => FROM docker.io/composer/composer:2-bin                                                              0.0s
 => [stage-0 1/2] FROM docker.io/library/php:8-alpine@sha256:78f6a736e1df608c670b1c5b92627fbaf766dd4a6  0.0s
 => CACHED [stage-0 2/2] COPY --from=composer/composer:2-bin /composer /usr/bin/composer                0.0s
 => exporting to image                                                                                  0.0s
 => => exporting layers                                                                                 0.0s
 => => writing image sha256:475e153fa8ac38fe3cd464cb93256eaef9588025a706cf2abdc018f70ca60205            0.0s
 => => naming to docker.io/library/composer                                                             0.0s

$ docker run -it composer composer -V
Composer version 2.2.24 2024-06-10 22:51:52
```

Link to Dockerhub: https://hub.docker.com/layers/composer/composer/2.2-bin/images/sha256-d4f478663588c206504f28001738742111d9f65409f5af6328dbe2a9e19d7dfe?context=explore

Latest image was published by @alcohol about an hour ago.

Workaround:

Pulling `composer/composer:2.8-bin` contains the correct version:
```
$ docker run -it composer composer -V
Composer version 2.8.2 2024-10-29 16:12:11
```

**Comment by alcohol** [comment]
This mistake was introduced by a PR I merged yesterday and fixed by a PR merged this morning. Also the more relevant repository for issues pertaining to the containers can be found at https://github.com/composer/docker

**Comment by alcohol** [comment]
Sorry, the relevant workflow was not triggered. Oversight on my part. Should be resolved in a moment.

**Comment by bcremer** [comment]
Can confirm, I'm getting the newest version now. Thanks.
`$ docker build --no-cache --pull . -t composer
[+] Building 2.6s (8/8) FINISHED                                                                                             docker:orbstack
 => [internal] load build definition from Dockerfile                                                                                    0.0s
 => => transferring dockerfile: 157B                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/php:8-alpine                                                                         1.2s
 => [internal] load metadata for docker.io/composer/composer:2-bin                                                                      1.9s
 => [internal] load .dockerignore                                                                                                       0.0s
 => => transferring context: 2B                                                                                                         0.0s
 => FROM docker.io/composer/composer:2-bin@sha256:edce3c39c93452b17920181bc13e75fc06883dfd4c835eafa182877772880af3                      0.5s
 => => resolve docker.io/composer/composer:2-bin@sha256:edce3c39c93452b17920181bc13e75fc06883dfd4c835eafa182877772880af3                0.0s
 => => sha256:edce3c39c93452b17920181bc13e75fc06883dfd4c835eafa182877772880af3 6.17kB / 6.17kB                                          0.0s
 => => sha256:4098abaf5a32b518633b04897198d3bdb8708b119d4e942ef4b2435f4c9221d0 1.02kB / 1.02kB                                          0.0s
 => => sha256:3c716281e6b08399410805d8c38c9137dc7a2732e7ee5a2900e2b05714e74c92 449B / 449B                                              0.0s
 => => sha256:52c05adedf5171f26d27a431625bb832312a877d1a221dbab0c0ea4166cec558 738.85kB / 738.85kB                                      0.3s
 => => extracting sha256:52c05adedf5171f26d27a431625bb832312a877d1a221dbab0c0ea4166cec558                                               0.0s
 => CACHED [stage-0 1/2] FROM docker.io/library/php:8-alpine@sha256:78f6a736e1df608c670b1c5b92627fbaf766dd4a63200d52b7ffd435bc186b24    0.0s
 => [stage-0 2/2] COPY --from=composer/composer:2-bin /composer /usr/bin/composer                                                       0.0s
 => exporting to image                                                                                                                  0.0s
 => => exporting layers                                                                                                                 0.0s
 => => writing image sha256:4c258d81e271f8c7c44af9bc843e51afacbc9082e0c19317a86adc850effcdfc                                            0.0s
 => => naming to docker.io/library/composer                                                                                             0.0s

$ docker run -it composer composer -V
Composer version 2.8.2 2024-10-29 16:12:11
PHP version 8.3.13 (/usr/local/bin/php)
Run the "diagnose" command to get more detailed diagnostics output.
```
