### ISSUE TITLE
Contents of installed.php should be more deterministic

### ISSUE THREAD

**Issue by ondrejmirtes** [composer/composer#12197]
[PHPStan's result cache](https://phpstan.org/user-guide/result-cache) relies on `installed.php` contents to stay the same if the installed packages are the same.

If the contents of installed.php change to convey the same information, PHPStan's result cache is invalidated. Which isn't a big issue, but I guess the fix should be easy enough.

The specific thing that changed between installations with the same lock file is:

```
*** 1145,1156 ****
          'psr/log-implementation' => 
          array (
            'dev_requirement' => false,
            'provided' => 
            array (
!             0 => '1.0.0',
!             1 => '1.0|2.0',
            ),
          ),
          'psr/simple-cache' => 
          array (
            'pretty_version' => '1.0.1',
--- 1145,1156 ----
          'psr/log-implementation' => 
          array (
            'dev_requirement' => false,
            'provided' => 
            array (
!             0 => '1.0|2.0',
!             1 => '1.0.0',
            ),
          ),
          'psr/simple-cache' => 
          array (
            'pretty_version' => '1.0.1',

```

So the order of versions in `provided` key. I guess they should be ordered before exporting.

Original issue: https://github.com/phpstan/phpstan/issues/12027

**Comment by sp-alberto-lopez** [comment]
Maybe just a ksortRecursive here?

https://github.com/composer/composer/blob/main/src/Composer/Repository/FilesystemRepository.php#L330

**Comment by ondrejmirtes** [comment]
Thank you!

**Comment by sp-alberto-lopez** [comment]
Super fast! Thanks!
