### ISSUE TITLE
Higher deps versions chosen for non-hard versions  requirements without looking at other dependencies' dependencies

### ISSUE THREAD

**Issue by AlexSkrypnyk** [composer/composer#12215]
Composer picks a higher version of a dependency's dependency and will not consider if another dependency has a release that has a lower version required. This results in getting outdated dependencies that actually have newer versions available.

I discovered this with `drupal/coder` being resolved to `8.3.13` but actually having `8.3.25` available.

My `composer.json` (no lock file):

```json
{
    "name": "myorg/myproject",
    "require": {
        "php": ">=8.2",
        "drupal/core-recommended": "~11"
    },
    "require-dev": {
        "drupal/core-dev": "~11",
        "phpspec/prophecy-phpunit": "^2"        
    },
    "config": {
        "allow-plugins": {
            "php-http/discovery": true,
            "tbachert/spi": true,
            "phpstan/extension-installer": true
        }
    }
}
```

Output of `composer diagnose`:

```
Composer version: 2.8.3
PHP version: 8.3.14
```

**Actual**

Given I run `composer install`
When I run `cat composer.lock |grep 'name": "drupal/coder' -A2`
Then I see
```
"name": "drupal/coder",
"version": "8.3.13",
"source": {
```
When I run  `cat composer.lock |grep 'name": "phpstan/phpdoc-parser' -A2`
Then I see
```
"name": "phpstan/phpdoc-parser",
        "version": "2.0.0",
        "source": {
```

**Expected**

Given I run `composer install`
When I run `cat composer.lock |grep 'name": "drupal/coder' -A2`
Then I see
```
"name": "drupal/coder",
"version": "8.3.25",
"source": {
```
When I run  `cat composer.lock |grep 'name": "phpstan/phpdoc-parser' -A2`
Then I see
```
"name": "phpstan/phpdoc-parser",
        "version": "1.33.0",
        "source": {
```

**Investigation**

1. `drupal/core-dev` requires multiple packages that require `phpstan/phpdoc-parser: ^1 || ^2` . **There are no packages with a hard version `2` requirement.**
2. `phpstan/phpdoc-parser` has versions 1 and 2 available. 
3. `drupal/coder:8.3.25` requires `slevomat/coding-standards` which requires `phpstan/phpdoc-parser: ^1`
4. `drupal/coder:8.3.13` does not require `slevomat/coding-standards`

```
Root Project (myorg/myproject)
├── drupal/core-recommended (~11)
├── drupal/core-dev (~11)
│   ├── Requires multiple packages
│   │   └── phpstan/phpdoc-parser (^1 || ^2)
│   └── drupal/coder (^8)
│       ├── 8.3.25 ── Requires slevomat/coding-standards
│       │              └── Requires phpstan/phpdoc-parser (^1)
│       └── 8.3.13 ── Does not require slevomat/coding-standards
└── phpspec/prophecy-phpunit (^2)
    ├── Requires multiple packages
        └── phpstan/phpdoc-parser (^1 || ^2)

Available Versions:
- phpstan/phpdoc-parser:
  - v1.x (compatible with drupal/coder 8.3.25 and other packages)
  - v2.x (defaulted to by other dependencies)

Resolution (Actual):
- Composer selects:
  - drupal/coder 8.3.13 (to avoid requiring phpstan/phpdoc-parser ^1)
  - phpstan/phpdoc-parser 2.0.0 (compatible with ^1 || ^2)
```

**Workaround**
Explicitly add `phpstan/phpdoc-parser: ^1`  to `require-dev` of my **root** `composer.json` to force V1 for other dependencies resolutions.

---

**Questions:**
1. Is this a known behaviour to pick the higher version?
2. There was no messages or any other indication that my project had an outdated version of `drupal/coder` package installed. I now do not know if my project has the latest dependencies installed. What can be done to mitigate this during `composer install`?

**Comment by Seldaek** [comment]
To your questions:

1. Yes
2. I don't think we can do much. Running `composer outdated` combined with `composer why drupal/coder` or `why-not drupal/coder 8.3.25` to try to understand why a newer version of drupal/coder was not selected, that might help. But there is really nothing we can automatically do to detect such cases. If you upgrade drupal/coder you'll have to downgrade phpstan/phpdoc-parser, so in both cases you have some outdated dependency, and that's totally fine. The two solutions are equally valid, and it just picks one.. Sometimes you won't agree with what it picks and then you need to refine your requirements to provide more guidance.
