### ISSUE TITLE
InstalledVersions::getInstalledPackagesByType() returns duplicates

### ISSUE THREAD

**Issue by Chi-teck** [composer/composer#12225]
## Steps to reproduce

Create small project like this

_composer.json_
```json
{
    "require": {
        "psr/log": "^3.0"
    }
}
```

_index.php_
```php
<?php

require __DIR__ . '/vendor/autoload.php';

print_r(Composer\InstalledVersions::getInstalledPackagesByType('library'));
```

Run the script
```
php index.php
```

Output
```
Array
(
    [0] => __root__
    [1] => psr/log
    [2] => __root__
    [3] => psr/log
)
```

Note that entries are duplicated.

**Comment by Chi-teck** [comment]
Here are the commands to reproduce in empty directory without dependencies.
```
$ ls -lh
total 0
$ echo '{}' > composer.json
$ composer install
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Writing lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files
$ echo "<?php
require __DIR__ . '/vendor/autoload.php';
print_r(Composer\InstalledVersions::getInstalledPackagesByType('library'));"  > index.php
$ php index.php 
Array
(
    [0] => __root__
    [1] => __root__
)
```

**Comment by Seldaek** [comment]
Yeah that does not do it for me. Can you try again adding --no-plugins to all composer commands you run?

**Comment by Chi-teck** [comment]
Same result with `--no-plugins`.

**Comment by Chi-teck** [comment]
I do not quite comprehend the logic but it feels like the condition in this line is wrong.
https://github.com/composer/composer/blob/2.8.3/src/Composer/InstalledVersions.php#L353

**Comment by stof** [comment]
@Chi-teck Can you try to dump `array_keys(ClassLoader::getRegisteredLoaders())` ?

**Comment by Chi-teck** [comment]
```
Array
(
    [0] => /tmp/test/vendor
)
```

**Comment by Chi-teck** [comment]
In my case duplicates appear because method `getInstalled` fills the resulting array twice.
[Line 333](https://github.com/composer/composer/blob/2.8.3/src/Composer/InstalledVersions.php#L333)
[Line 354](https://github.com/composer/composer/blob/2.8.3/src/Composer/InstalledVersions.php#L354)

**Comment by Seldaek** [comment]
Yeah that kinda makes sense, I just don't understand yet why it does not happen for me.

**Comment by jrfnl** [comment]
Came here to report the same. This does not appear to be fixed.

I've created a minimal reproduction example:

* Clone the https://github.com/PHPCSStandards/composer-installer repo
* Check out the `feature/composer-12225-reproduction-case` branch
* Run `composer install`

At the bottom of the output, I see the following (I added the `var_dump()` to show the issue):
```
Use the `composer fund` command to find out more!
array(2) {
  [0]=>
  string(34) "phpcompatibility/php-compatibility"
  [1]=>
  string(34) "phpcompatibility/php-compatibility"
}
PHP CodeSniffer Config installed_paths set to ../../phpcompatibility/php-compatibility
```

**Comment by Seldaek** [comment]
Alright this is a composer-runtime specific bug.. nasty stuff, with a nasty fix, but it should work now with https://github.com/composer/composer/pull/12361 thanks for reporting @jrfnl

**Comment by jrfnl** [comment]
@Seldaek My hero 💞 I hope the reproduction sample helped track this down.

**Comment by Seldaek** [comment]
Yes it did, although it didn't quite trigger for me for some reason, it definitely hinted at the fact this was a runtime issue as it only happens during post-install-cmd user-land event handlers 👍🏻
