### ISSUE TITLE
private packagist packages don't install if zip extension isn't present

### ISSUE THREAD

**Issue by prescriptionlifeline** [composer/composer#12236]
My `composer.json`:

```json
{
    "name": "prescriptionlifeline/test",
    "authors": [
        {
            "name": "prescriptionlifeline"
        }
    ],
    "require": {
        "backpack/pro": "^2.2"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.backpackforlaravel.com/"
        }
    ]
}
```

My auth.json (with sensitive info redacted) is as follows:

```json
{
    "http-basic": {
        "backpackforlaravel.com": {
            "username": "...",
            "password": "..."
        }
    }
}

```

Output of `composer diagnose`:

```
Composer could not detect the root package (prescriptionlifeline/test) version, defaulting to '1.0.0'. See https://getcomposer.org/root-version
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking composer.lock: OK
Checking platform settings: OK
Checking git settings: OK git version 2.44.0
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking connectivity to https://repo.backpackforlaravel.com/: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking Composer version: OK
Checking Composer and its dependencies for vulnerabilities: OK
Composer version: 2.8.4
PHP version: 8.4.1
PHP binary path: c:\php\php.exe
OpenSSL version: OpenSSL 3.0.15 3 Sep 2024
curl version: 8.10.1 libz 1.3.1 ssl OpenSSL/3.0.15
zip: extension not loaded, unzip not available, 7-Zip not available
```

When I run this command:

```
composer -vvv install
```

I get the following output: 

See https://pastebin.com/6a7YMU68 (github.com gives me a `There was an error creating your Issue: body is too long (maximum is 65536 characters).` error if I try to embed the contents of that pastebin.com link)

The key takeaway is that before it asks me for my GitHub credentials it says this, over and over and over again:

```
    Failed to download symfony/polyfill-php80 from dist: The zip extension and unzip/7z commands are both missing, skipping.
The php.ini used by your command-line PHP is: C:\php\php.ini
```

And I expected this to happen:

I expected it to just install the package. Indeed, the package does get installed, without issue, if I have `extension=zip` in my php.ini, but if I don't, I get asked for a GitHub token vs trying to use what is in my auth.json.

The zip extension is, apparently, not a hard requirement for public packagist packages but if it's a requirement for private packagist package then maybe that's what the error ought to say vs asking for a GitHub auth token.

**Comment by stof** [comment]
Maybe your private package does not provide a way to install from source (which is what public packages hosted on GitHub will use if you cannot unzip a dist archive). If a package only provides a dist archive but no source, there is no way to install it on systems that don't meet the requirements for the zip downloader (btw, `ext-zip` is only one of the available options)

**Comment by stof** [comment]
Note that Backpack may be doing that intentionally: it is probably easier for them to give you access only to archive downloads managed in their repo than to support source installations, which would require giving you read access on their (private) git repositories.

**Comment by prescriptionlifeline** [comment]
@stof - that makes sense.

Thanks for the feedback! Learning new things every day!
