### ISSUE TITLE
custom commands

### ISSUE THREAD

**Issue by till** [composer/composer#1234]
Just wanted to start this here – let's say I want to add a `till` command to composer. Now I realize no one else has a use for this command, but at the same time, I wouldn't want to maintain a fork where I backport changes from upstream when they start to collide.

Do you guys have any idea how we could add a new type `composer-command` which I can declare as a vendor and then it just registers that command?

Till

**Comment by tleb** [comment]
Isn't this solved by [custom commands](https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands)?

**Comment by till** [comment]
@tleb I wanted something where I can hook into composer, not just a task-runner.

**Comment by tleb** [comment]
Well, [scripts](https://getcomposer.org/doc/articles/scripts.md#command-events) are still the answer, right?

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/pull/3377#issuecomment-215548870
