### ISSUE TITLE
Recursive option for depends command

### ISSUE THREAD

**Issue by igorw** [composer/composer#1237]
Currently the depends command only shows direct children of a package. It would be nice to have a `--recursive|-r` option that traverses `requires` and finds packages indirectly depending on yours.

Given that:

    A requires B
    B requires C
    C requires D

Before:

    $ composer depends A
    B

After:

    $ composer depends A
    B
    C (via B)
    D (via C, B)

**Comment by Seldaek** [comment]
I believe this is now solved (locally) by `depends --tree` 
![image](https://cloud.githubusercontent.com/assets/183678/14476120/da2f130c-00fd-11e6-99fb-80df318d6816.png)

Plus we have the dependents listing on packagist.
