### ISSUE TITLE
UnexpectedValueException

### ISSUE THREAD

**Issue by tomjamescn** [composer/composer#1242]
zend framework 2, Get the Skeleton Application.[page url](http://framework.zend.com/downloads/skeleton-app)

If run the following in win 7:

```
php composer.phar install
```

will get exception:

```
 [UnexpectedValueException]
'D:\dir_path/5f571512cefc7c06ec6784a7820763ea.3' is not a zip archive.
```

**Comment by Raaghu** [comment]
Might be composer is unable to authenticate the download URL , Please update your [auth.json](https://getcomposer.org/doc/articles/http-basic-authentication.md)
