### ISSUE TITLE
Add an ability to show package Changelog between stable versions

### ISSUE THREAD

**Issue by gena01** [composer/composer#1261]
Add an abitlity to show package Changelog (release notes/summary) between stable package versions.

The idea is to be able to know what has changed between versions (without reading commit messages) to see if there's a reason to upgrade or not.

Pear/Pecl provide a means for doing this already and provide a changelog. Should I will submit the Pear changelog support as a separate issue?

**Comment by Seldaek** [comment]
Could be done as a plugin if someone really cares, going to close this here as I don't think we want to do it and maintain it..

**Comment by ctf0** [comment]
@Seldaek sorry for bringing this up again, i was thinking of creating a package that does exactly that but am trying to understand some points

### idea

<pre>
package root
  | changelog
      | v1.0.0.txt
      | v1.0.1.txt
      | version.json
</pre>

inside the `version.json` you add the version & file name ex.
```js
{
// version : changelog file
"1.0.0": "1.0.0.txt",
"1.0.1": "1.0.1.txt" 
}
```

and now on each time a package gets updated, 
- we run a script to check if it has a changelog folder and if yes 
- we check `if the currently installed version == to the last line of **version.json**` then show its file content, incase the package author didnt add changelog for the current release

### questions

- does composer currently have such an option where we can get the currently updated packages and its installation dir 'vendor or custom` ? so we check them recursively
- if not , is there a way around to get that kind of info ?

i know that GH tickets are for issues, but i dont know where else to add this.
