### ISSUE TITLE
Memory isue on hosted server

### ISSUE THREAD

**Issue by verschoof** [composer/composer#1274]
Hi,

I'm trying to deploy my symfony 2 site.
I have ssh, but no sudo. (so can't do mutch :( )

I clone my project from git.

after I run:

```
php composer.phar install
```

then I get the next error:

```
Loading composer repositories with package information
Installing dependencies                               

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 71 bytes) in phar:///home/dir/domains/symfony/composer.phar/src/Composer/DependencyResolver/RuleWatchGraph.php on line 47
```

so, ok I need more memory..
now I edited the composer.phar to tell php my memory limit:

```
ini_set('memory_limit', '1528M');
```

And now I get the next error:

```
Fatal error: Uncaught exception 'PharException' with message 'phar "/home/dir/domains/symfony/composer.phar" SHA1 signature could not be verified: broken signature' in /home/dir/domains/symfony/composer.phar:15
Stack trace:
#0 /home/dir/domains/symfony/composer.phar(15): Phar::mapPhar('composer.phar')
#1 {main}
  thrown in /home/dir/domains/symfony/composer.phar on line 15
```

How to fix this?
and why I can't tell my composer how many memory he can use?

**Comment by alphyon** [comment]
I same this error and I download many times the composer.phar from the site and not solve, would I edit this file sorrry I am newbie from use composer
