### ISSUE TITLE
Autosuggest package name (when not found)

### ISSUE THREAD

**Issue by bendavies** [composer/composer#1287]
I recently spent a good hour trying to debug and fix a non issue, because i had mistyped a package name.

It would be a nice feature if composer suggested a package name to you, if the one required was not found.

If a list of all package names of known at the time, it should be trivial with a levenstein distance.

**Comment by Seldaek** [comment]
Don't think it's really so worth it so closing. We have `composer require`  alone with the package search if you don't know exactly what you are requiring.
