### ISSUE TITLE
Multithreaded/Multiprocess Install/Update

### ISSUE THREAD

**Issue by Petah** [composer/composer#1298]
A nice feature to have would be enabling composer to work on multiple threads/processes.

Each thread/process could download (git pull) 1 dependency. 

I know it would be possible because I have implemented it in PHP before. 

They way I have done it (although not very elegant) is:

Create a temp bash/batch file (linux/windows) that executes the git command and pipes the output to another temp file, then outputs an exit signal to the file.

The main thread executes the scripts in the background (using `&` on linux, and spawning a `cmd` process on windows) and then scans the temp files for the exit signal. 

I know this might be a hard thing to implement but I thought I would just put it on the record as a nice to have in the future. 

An exert  of the script I made is at: https://gist.github.com/4034927

**Comment by estheban** [comment]
+1

**Comment by de-cix** [comment]
+1

**Comment by nitso** [comment]
https://github.com/hirak/prestissimo

**Comment by khromov** [comment]
@nitso Prestissimo does unfortunately not have multithreaded update, only install. See:

https://github.com/hirak/prestissimo/issues/17

**Comment by nitso** [comment]
@khromov just FYI.

**Comment by dbjpanda** [comment]
Any update on this issue ?? :)

**Comment by staabm** [comment]
Parallel downloads are already implemented in the 2.0 branch

**Comment by grekpg** [comment]
Why just uploads - i have 16 procesor cores , and see that composer use 100 % one of them . I wait few minutes to update...   Why composer don not run backgroud threads ? i think is like first post of this topic. Every git repo should try run in next thread. So if its possible it run on next core.

**Comment by diegosucaria** [comment]
I'm trying to speed up some cloud builds...
My bottleneck is composer install
I'm also running on a 16cores and 32gb ram VM, yet I have not seen much speed improvements.

Are there any guidelines for multi-core composer install?

**Comment by Seldaek** [comment]
composer 2.0 does this mostly
