### ISSUE TITLE
Improve git repo caching by cloning with `--reference` to a local `--mirror` clone

### ISSUE THREAD

**Issue by patcon** [composer/composer#1323]
As per #915, @Seldaek and @chEbba were interested in the idea of using `git clone --reference` and `--mirror` to cache git repositories and decrease build time.

More information is available on the git-clone man page:
http://git-scm.com/docs/git-clone

To be fair, the idea isn't my own and comes from how Drupal's drush CLI tool handles caching for Drupal modules pulled in from git repos:
https://github.com/drush-ops/drush/blob/master/commands/pm/package_handler/git_drupalorg.inc#L56-89

This appears to have been implemented by @msonnabaum, so perhaps he has input.

**Comment by alexislefebvre** [comment]
I had the same idea while seeing that Travis CI clone git repositories for each build, which takes a lot of time. The Travis CI cache could be used to store these git mirrors and it would greatly speed up Composer.

Will this idea be implemented in the future? Thanks.

**Comment by barryvdh** [comment]
In that case it would be better to download archives, without using the api as discussed in https://github.com/composer/composer/pull/4737 and cache that.

**Comment by Seldaek** [comment]
Closing in favor of  #3722
