### ISSUE TITLE
Package with pending changes/commits gets deleted without warning

### ISSUE THREAD

**Issue by mneuhaus** [composer/composer#1337]
There's a certain case where composer deletes a package with not pushed changes and/or unstaged files without any warning.

Here's how it seems to happen:

- Working on a project with a composer.json for dependencies
- creating a new package inside that project and/or add a package 'manually'
- add that package as a requirement and update

At this point composer seems to delete the existing package folder and fetches it completly fresh, resulting in deleting any unpushed/commited changes.

I know, it probably shouldn't be done this way with adding packages manually, but it can also happen with new packages where you push an initial commit, forget to push the latest changes, add it as a requirement and boom, your changes are gone.

**Comment by Seldaek** [comment]
This has been widely fixed now, unpushed and uncommitted changes are detected in the majority of cases.
