### ISSUE TITLE
More contextual information about solving Problems

### ISSUE THREAD

**Issue by mneuhaus** [composer/composer#1362]
Hey,

i've got a case of resolving issue that i can't figure out currently.

The Problem is, that the package with conflict is used by quite some included packages and i don't know which two require incompatible versions. In the end i get this Problem output:

    Your requirements could not be resolved to an installable set of packages.
    
      Problem 1
        - Conclusion: remove symfony/dom-crawler dev-master
        - Conclusion: don't install symfony/dom-crawler dev-master
        - Installation request for famelo/poltergeist * -> satisfiable by famelo/poltergeist dev-master.
        - Conclusion: don't install symfony/symfony dev-master
        - don't install symfony/symfony 2.2.x-dev|install symfony/symfony dev-master
        - Installation request for symfony/dom-crawler dev-master -> satisfiable by symfony/dom-crawler dev-master, symfony/symfony dev-master, symfony/symfony 2.2.x-dev.

the main incompatible package seems to be the dom-crawler, but i have no idea from which the conflicting version requirements came :/
To better understand where/how to fix this a little bit information about the context/requiring package would be nice. For example like this (uppercase is new):

        - Installation request for famelo/poltergeist * FROM FAMELO/STANDALONE -> satisfiable by     famelo/poltergeist dev-master.
        - Installation request for symfony/dom-crawler dev-master FROM FABPOT/GOUTTE -> satisfiable by symfony/dom-crawler dev-master, symfony/symfony dev-master, symfony/symfony 2.2.x-dev.

btw, you could reproduce this like this:

```
composer create-project famelo/standalone standalone
cd standalone
composer require --dev famelo/poltergeist
```

(non-dev context works without a problem)

**Comment by Seldaek** [comment]
Reporting has been improved quite a bit.
