### ISSUE TITLE
PEAR package repository parser doesn't support uri based dependencies

### ISSUE THREAD

**Issue by jakzal** [composer/composer#1401]
I was trying to install PHPBrowserMobProxy from [element-34 PEAR channel](http://element-34.github.com/pear/ ). 

Here's my composer.json:

```json
{
    "repositories": [
        {
            "type": "pear",
            "url": "http://element-34.github.com/pear",
            "vendor-alias": "element-34"
        }
    ],
    "require": {
        "element-34/PHPBrowserMobProxy": "*"
    }
}
```

When I run composer install I get a warning: **PEAR repository from http://element-34.github.com/pear could not be loaded. Undefined index: channel**:

```bash
./composer.phar install
Loading composer repositories with package information
Initializing PEAR repository http://element-34.github.com/pear
PEAR repository from http://element-34.github.com/pear could not be loaded. Undefined index: channel
Installing dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package element-34/phpbrowsermobproxy could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

I checked [packagesinfo.xml](http://element-34.github.com/pear/rest//c/Default/packagesinfo.xml) file and looks like some dependencies use uri instead of a channel. [PackageDependencyParser expects a channel](https://github.com/composer/composer/blob/5eead93250b6855f688bec7ede193afe4648fa89/src/Composer/Repository/Pear/PackageDependencyParser.php#L232).

**Comment by dol** [comment]
Today I ran into the same issue because PEAR_PackageFileManager_Git don't have any channel name.
We fixed the issue by skipping the Package if no channel name was found.
