### ISSUE TITLE
"data" role from package.xml

### ISSUE THREAD

**Issue by till** [composer/composer#1402]
So, I tried to install [HTTP_Request2](http://pear.php.net/package/HTTP_Request2) using composer and the installation seems to _work_, but parts of it did not work as expected.

So, e.g. — somewhere in the CookieJar, a file is included — the class constructs the path to it and this path does not exist on my system:

    /project/vendor/pear-pear.php.net/HTTP_Request2/data/HTTP_Request2/public-suffix-list.php

The following path works though:

    /project/vendor/pear-pear.php.net/HTTP_Request2/data/public-suffix-list.php

So I am guessing the data role from package.xml needs to be handled in the [PearPackageExtractor]( 
https://github.com/composer/composer/blob/master/src/Composer/Downloader/PearPackageExtractor.php). Instead of `package/data/`, it needs to create `package/data/package`.

**Comment by Seldaek** [comment]
Closing as it likely won't ever be fixed.
