### ISSUE TITLE
Option to ignore requirements when installing

### ISSUE THREAD

**Issue by davidwinter** [composer/composer#1426]
A thread has turned up on the doctrine/mongodb repo, where there is a requirement for the mongo extension to be installed for PHP. However, if you're using Vagrant, or a setup where the version of PHP you're using to work with Composer isn't the one that'll be used to run your project, there should be a way to ignore these requirements so you can continue with installing the dependencies.

You can read the background to the discussion here: https://github.com/doctrine/mongodb/issues/88

**Comment by bumstik** [comment]
+1

**Comment by vesper8** [comment]
so this --ignore-platform-reqs works with create-project, install and update.. but it doesn't work with require??

I tried composer require --ignore-platform-reqs on a package that uses mongodb and am still getting the same errors.. any workaround ?

my provisioning script uses composer require and I want to run it in my osx environment (but the project itself is only used in my vagrant environment)
