### ISSUE TITLE
post-install and post-update-cmd not autoloadable when installed as dev dependency

### ISSUE THREAD

**Issue by jeremykendall** [composer/composer#1430]
I've started work on a project that will write a ctags file for composer dependencies.  If I install it as a regular dependency, the associated script works fine.  If I install it as a dev dependency, I get the following error:

`Class PhpCtagger\Composer\Script\Ctagger is not autoloadable, can not call post-update-cmd script`

The dependency is `"jeremykendall/phpctagger": "0.0.1"`, and the script is `"PhpCtagger\\Composer\\Script\\Ctagger::ctag"`.

Both post-install-cmd and post-update-cmd are failing.  I have not tested with any other events besides those.  My composer version is 34df394.

Thanks for your help.

**Comment by Seldaek** [comment]
Don't really think we need this so closing.
