### ISSUE TITLE
Composer-Setup Warning: "openssl extension is missing"  

### ISSUE THREAD

**Issue by blackopz** [composer/composer#1440]
Trying to install Composer dependency management tool on Win7/64 + WampServer 2.2 via the Setup Installer and I am getting the following message:

The openssl extension is missing, which will reduce the security and stability of Composer. If possible you should enable it or recompile php with --with-openssl

So here is what I did...
1. From my Wamp icon in Tray, clicked php > php extensions > php_openssl
2. This showed that task was completed by placing a check mark beside the extension
3. I then restarted WampServer
4. Then from the Wamp icon in tray, I clicked php > php.ini and searched for openssl to verifiy it was NOT commented) out. It was not.
5. I then went back to Composer-Setup.exe and tried again. Same Warning Message: "openssl extension is missing"
6. Having never worked with OpenSSL, I'm not sure what is supposed to be set, so I tried to browse to one of my local sites using https. It Failed.

What am I missing? Should I ignore this and keep going? 

Please advise.

sleeper

**Comment by satizkumar** [comment]
1.Open the xampp/php/php.ini file
2.Find the " ;extension=php_openssl.dll " then remove the semicolon from starting of line....

**Comment by Judder** [comment]
when running the Composer installer, it looks for a php.ini in the same folder as the php.exe it is running (it shows the path to this on step1 of the install)

If there is no php.ini in this directory, as with UwAmp, then this will fail, even if it is configured correctly for Apache

Simple copy the Apache php.ini to the bin directory, and the process will work

**Comment by djgerhab** [comment]
Thank you Judder!!! You are spot on, I just assumed the php_initial.ini is what it would read from to begin with. It appears that with newer versions of Uwamp, php.ini is not present in that folder but rather php_initial.ini and php.ini-development and php.ini-production. I assumed after reading your post that php_initial.ini could just be copied and renamed but it uses local path variables that Composer also doesn't handle. So you do need to copy whats in the Apache folder. 

On a side note, I understand that uncommenting that line worked for most people but please don't repeat over and over again that that is the real solution when people already tried that...

**Comment by samratrocks** [comment]
The problem for me seemed to be that PHP couldn't actually find the extension. 

This fixed it for me:
1. Open the php.ini file
2. Find the "extension=php_openssl.dll " then change it to "ext/php_openssl.dll"

**Comment by relipse** [comment]
@samratrocks Thanks for the tip, that fixed it for me also. (I'm not using wamp nor xampp, just plain php download)

**Comment by Emat12** [comment]
I have read bunch of stuffs here , but none of them helped me up to resolve this bug ..ugrr!:-(

**Comment by stof** [comment]
@samratrocks a better fix for you would probably to configure the ``extension_dir`` setting

**Comment by blackopz** [comment]
Thanks for all the ideas and suggestions. Check out this stack response: http://stackoverflow.com/a/14265815/676127

**Comment by bi40** [comment]
Hey , I have the same problem with CLI , I am using actually PHP 7.
![capture](https://user-images.githubusercontent.com/5985410/46374147-4335f500-c690-11e8-8293-9e55d539c8b3.PNG)
