### ISSUE TITLE
partial update : dist url not updated

### ISSUE THREAD

**Issue by jaugustin** [composer/composer#1458]
Hi,

I run a partial update :

```
composer.phar update propel/propel-bundle
```

I change my propel-bundle version from `1.1.x-dev@dev` to `1.1.x-dev#9faeb85693d5f1d0e1c268acd19b1b9c6c83b37a` to force update to last revision

the update work fine but the lock file was only partially updated :

```json
        "name": "propel/propel-bundle",
            "version": "1.1.x-dev",
            "target-dir": "Propel/PropelBundle",
            "source": {
                "type": "git",
                "url": "https://github.com/propelorm/PropelBundle",
                "reference": "9faeb85693d5f1d0e1c268acd19b1b9c6c83b37a"
            },
            "dist": {
                "type": "zip",
                "url": "https://github.com/propelorm/PropelBundle/archive/fa0a8f77ace23513cd5ca5641805505b4debcddc.zip",
                "reference": "9faeb85693d5f1d0e1c268acd19b1b9c6c83b37a",
                "shasum": ""
            },
```

the dist url was not updated during the process

**Comment by bonswouar** [comment]
Same problem here : I'm using Satis and just changed my `repositories` `url`, but I can't update my `composer.lock` file, it's always using the old `dist` URLs as the versions didn't change.

**Comment by cyrrill** [comment]
Any updates on this issue? I am having an issue when using Laravel Envoyer which I believe is related:

I have a private Github repo that is installed into the application via composer, such as:

```
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
  (...)
        "company/privaterepo": "v1.5.0"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:company/privaterepo.git"
        },
```


When I do the Envoyer deploy onto the server, I've seen that code installed is not the latest version (1.5.0) which was pegged in composer.json


composer.lock shows:
```
            "name": "company/privaterepo",
            "version": "v1.5.0",
            "source": {
                "type": "git",
                "url": "git@github.com:company/privaterepo.git",
                "reference": "master"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/company/privaterepo/zipball/4cf727d24bee68f1cdbd556f578d1a4d84814a2d",
                "reference": "4cf727d24bee68f1cdbd556f578d1a4d84814a2d",
                "shasum": ""
            },
```

So it seems like the code deployed should have been 1.5.0, but when SSH'ing into server, I see an older code being used, missing the latest version updates.

Is this a problem with the Zipball? When I enter the dist url into the browser, I get: 

```
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
```

 Any ideas?

**Comment by Seldaek** [comment]
@cyrrill not sure what that problem is about, but not related to this issue, which was fixed a while back anyway. Just forgot to close it.

Regarding your issue if the lock file says 1.5.0 it should be installed that. Except it has master as source.reference which is odd as it should never do that I am pretty sure, seems like you edited the file by hand? 4cf727d24bee68f1cdbd556f578d1a4d84814a2d should be the git reference matching the v1.5.0 tag. I am not familiar at all with Envoyer so I don't know if it does strange things or not.

**Comment by cyrrill** [comment]
"source.reference" was exactly the issue. It wasn't actually edited by hand, but rather the company/privaterepo/composer.json file had a superfluous source section with master specified. That was removed and things are fixed. Thanks for your help in identifying that @Seldaek
