### ISSUE TITLE
Add DirectoryRepository for local dependency installs

### ISSUE THREAD

**Issue by pauliwang** [composer/composer#1462]
It would be great to be able to add a package that resides on the local filesystem by just pointing to the directory that it's located in.  The url could be a file url that points to the local directory with the composer.json file.

For example
``` javascript
"repositories": [
  {
    "type": "directory"
    "url": "file:///path/to/dir/that/contains/composer.json/"
    "symlink": true
  }
]
```

The 'symlink' attribute would control whether the files are copied or symlinks to the original.  The advantage of providing the 'symlink' attribute is if you control the package that you are dependent upon but don't want to have to go through the hassle of updating the root package every time you make a change to the dependent package.  This option would aid in speeding up development.

**Comment by Seldaek** [comment]
See https://getcomposer.org/doc/05-repositories.md#path
