### ISSUE TITLE
Consider Ignoring Platform Packages

### ISSUE THREAD

**Issue by schmittjoh** [composer/composer#1468]
This is a follow-up of #1171.

So far, the approach was to use the provide section of the root package to "fake" installed platform packages. In theory, it should work to fake not-installed dependencies, but fails for dependencies which are installed, but where the version does not satisfy the requirement of some package.

**Comment by killerwolf** [comment]
i am in the same situation as @renanbr

````
php composer.phar check-plataform-packages
````

would be great
