### ISSUE TITLE
Composer fails when installing a dependency of a dependency, but not when the dependency is installed directly.

### ISSUE THREAD

**Issue by vierbergenlars** [composer/composer#1478]
Composer fails when installing a dependency (Let's call it package A) that has another dependency (package B).
When package B is put in the composer.json of the root package (exactly the same line), everything installs fine.

This is the output composer generates: 

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for remotecp/common dev-crypto@dev -> satisfiable by remotecp/common dev-crypto.
    - remotecp/common dev-crypto requires asymmetricrypt/asymmetricrypt dev-master@dev -> no matching package found.
```

(note: remotecp/common is package A and asymmetricrypt/asymmetricrypt is package B)

**Comment by karimsamir** [comment]
a quick question what is the difference between set require to "dev-master" and "@dev"?

**Comment by stof** [comment]
`@dev` is a requirement on `*` (i.e. allowing any version), with a min-stability override to allow using versions with stability `>= dev`. Note that `@dev` is actually a shortcut for `*@dev`.
`dev-master` is an exact-match requirement allowing only the `dev-master` version (and as the requirement version is a dev one, it implicitly adds a stability override too (making the same than `dev-master@dev`).
So the `dev-master` requirement forbids using stable releases of the package.

Also note that the stability override thing is a root-only feature. When a package is installed as a dependency, it is not allowed to override stability settings (so the `@dev` part of the constraint is a no-op then, and you have to hope that the root project still allows using dev versions if stable versions cannot match the requirement)
