### ISSUE TITLE
Provide install routine to check non-trivial environment dependencies.

### ISSUE THREAD

**Issue by ircmaxell** [composer/composer#1488]
Currently, you can check php version dependencies. But you cannot do arbitrary things like check for installed extensions, or do OR based dependencies (if you have A or B, we're fine). Note, I'm talking about rejecting an install and not determining which to install. So it's less about resolving which dependencies to install, and more about determining if the current package is installable.

For example, I have a project which normally requires 5.3.7, but in certain cases (Debian and Redhat packages), older versions work ok: https://github.com/ircmaxell/password_compat/issues/10

My solution was to pull the PHP version requirement. But I'd like the ability to do the check in a pre-install check. So perhaps something like this:

```
{
    "pre-install": {
        "file": "install/check.php",
        "callback": "check_requirements"
    }
}
```

Which would load install/check.php and execute `check_requirements()`. If the pre-install hook raises an exception, the install would be aborted with the error message from the exception. Otherwise it would continue on.

```
<?php // check.php
function check_requirements(Composer\Installer $installer) {
    if (!extension_loaded('mcrypt') && !extension_loaded('openssl')) {
        throw new \LogicException("This package requires either the OpenSSL or MCrypt extensions to be installed");
    }
}
```

**Comment by aoberoi** [comment]
i have a package that manages to run without an extension (in this case `ext-apc`) locally, but then does require that extension remotely (on Heroku). the local implementation writes to the filesystem and the production instance writes to the APC, this is all conditionally implemented in my code. i need a way to declare `ext-apc` when i push to heroic and to *not* require it locally.

@Seldaek any hints at how this can be accomplished?

**Comment by slbmeh** [comment]
@aoberoi if your application can function without APC locally IMO it should be able to function without APC on Heroku. You should instead check for the availability of the extension and utilize it if present. Then your package can use suggests instead of require. If it actually needs APC you can ignore the the platform dependency locally with `--ignore-platform-reqs`, this is useful for build servers packaging and running certain tests. Just keep in mind the pieces requiring the extension will be broken.

**Comment by Seldaek** [comment]
Yup --ignore-platform-reqs is the only sane answer here I think.. or just install APC locally :)
