### ISSUE TITLE
Composer fails to load tarballs created using bsdtar

### ISSUE THREAD

**Issue by njh** [composer/composer#1492]
I have been confused for a little while about why I have been unable to load tarball archives in composer. I see the following error message:

```
[UnexpectedValueException]                                                                                                           
phar error: "/Users/humfrn01/Sites/njh.me/vendor/easyrdf/easyrdf/af066b6053af1defabdd6e19e901905e.gz" is a corrupted tar file (chec  
ksum mismatch of file "17 gid=287753940                                                                                              
18 uid=1451698731                                                                                                                    
20 ctime=1358347997                                                                                                                  
20 atime=1358347996                                                                                                                  
38 LIBARCHIVE.creationtim")                                                                                                          
```

The tar.gz in question was created on Mac OS 10.7.5 using the command `tar zcf easyrdf-0.8.0.tar.gz easyrdf-0.8.0`.

I then tried creating a tar.gz using the same command on a Linux box and found that Composer works fine. After that I used the gnutar command on Mac OS X and that also worked.

So I have come to the consolation that phar only supports 'tars' that are generated by GNU Tar and not BSD tar.

I don't know if Composer can do anything about this, but it is certainly a (confusing) pain point.

**Comment by andkirby** [comment]
I got the same problem (PHP last 5.4.x and last 5.6.x) on Windows. 
I really don't understand this library cannot read simple file??? :((( I've lot of time how to get round this! :(
Asked support to update out GitLab repository to get branches in ZIP. I hope there ain't stupid errors!
A cry from the heart....
