### ISSUE TITLE
Allow custom ClassLoader

### ISSUE THREAD

**Issue by Petah** [composer/composer#1493]
It would be nice to be able to specify a custom class loader with out having to hack composer.

http://stackoverflow.com/questions/14351001/custom-composer-autoloader/14369641#14369641

This is so I could implement a custom feature such as a static constructor like:

```

    public function loadClass($class)
    {
        if ($file = $this->findFile($class)) {
            include $file;
            if (method_exists($class, '__static')) {
                call_user_func(array($class, '__static'));
            }

            return true;
        }
    }
```

**Comment by Soullivaneuh** [comment]
> @Petah another option that's quite easy is the following:

@Seldaek Could you please elaborate a little bit? What is the difference between this auto-loader and the composer one? Thanks.

**Comment by Seldaek** [comment]
That one wraps the composer one, and it just calls `$classname::__static` after loading a class if that method is defined.

**Comment by Soullivaneuh** [comment]
Yes, but what is the goal? What is the difference between this and the official loader?

I had an issue conflict with the loader in https://github.com/puli/cli/pull/21#issuecomment-148438983 and BTW, remove the `__static` call from your custom loader works too.

**Comment by Seldaek** [comment]
The goal was to have static initializers as that was why custom autoloaders
were requested in this issue. It was just an example of how to wrap the
composer one, I'm not saying doing this is a good idea and I'm not sure
what puli does.

**Comment by dbalabka** [comment]
I'm also found static constructor useful. A custom class loader is only one way how to implement it. There was RFC to create such a feature on PHP level:
https://wiki.php.net/rfc/static_class_constructor
This RFC describes other possible workarounds how it can be achieved.

Here is a discussion: https://externals.io/message/85779
