### ISSUE TITLE
Composer cache makes developers life hard

### ISSUE THREAD

**Issue by markushausammann** [composer/composer#1496]
We're constantly annoyed by the composer cache. We constantly run into issues where some way or another one or another repo doesn't update or install properly until we delete the cache. This is on Windows7.

**Comment by cxj** [comment]
Cache still broken when using @dev version of Github hosted packages:

`Composer version 1.2.1 2016-09-12 11:27:19`

```sh
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing level-2/transphporm (dev-master 2110304)
    Cloning 2110304c512958797508ea08e0d78c4336494b41 from cache
```

```sh
$ git log origin
commit 0ada294c2ecd1698782985a23f3c90c142fab7b4 (refs/remotes/origin/master, refs/remotes/origin/HEAD, refs/remotes/composer/master)
Author: Tom Butler <tom@r.je>
Date:   Tue Sep 13 15:51:36 2016 +0100

    #124 - fixed bug with empty value

commit 2110304c512958797508ea08e0d78c4336494b41 (HEAD -> refs/heads/master)
Author: Richard <solleer@hotmail.com>
Date:   Fri Aug 12 08:17:02 2016 -0400

    Removed unused class properties
```

Note how Composer pulled old version 2110304 from Aug 12 from cache, instead of grabbing version 0ada294c from Github.

**Comment by Seldaek** [comment]
@cxj please report a new issue rather than resurrecting an old one and spamming 15 people. I don't think this has any relation to the cache, so we'll need more details and repro steps. Locking this thread now.
