### ISSUE TITLE
(possibly) update RootPackageLoaderTest

### ISSUE THREAD

**Issue by xrstf** [composer/composer#1508]
Inside the ```RootPackageLoaderTest```, the issue sebastianbergmann/phpunit-mock-objects#81 has been referenced:

> Can do away with this mock object when https://github.com/sebastianbergmann/phpunit-mock-objects/issues/81 is fixed

The issue has been closed 8 days ago, so maybe the test can be cleaned up.

**Comment by alcohol** [comment]
@stof is this still applicable?
