### ISSUE TITLE
Feature: Install only packages that work up to a certain PHP version

### ISSUE THREAD

**Issue by finishingmove** [composer/composer#1522]
So, the problem I encountered is the following:

I have a development environment where I use PHP 5.4.7 and a staging environment which only supports PHP 5.3.10 for now. When I deploy my project to the staging environment, the composer hook automatically executes, but sometimes for "*" it resolves to a new version of a package that implements some 5.4.7 features, hence the install fails...

It would be good to be able to specify a top-limit php version and install only packages that work under that version, rather than going through all the problematic packages and downgrading their version manually.

So, instead of "vendorX/packageX": "version-that-works-with-php-5.3.10", i want to do just "vendorX/packageX": "*" and have a general setting like "php-version-available" : "5.3.10".

Regards,

Arsen.

**Comment by Tobion** [comment]
:+1:

**Comment by postalservice14** [comment]
:+1:

**Comment by postalservice14** [comment]
Do you think a composer plugin could accomplish this?  I'm not sure where in the composer event chain this could happen.  Maybe on a `pre-dependencies-solving` event it could remove package versions that are above the specified PHP platform or something?

**Comment by slbmeh** [comment]
@postalservice14 you could make sort of a decorator repository that wraps a composite repository and filters the results in the what provides phase. Then your plugin can replace the installed repositories with your composite containing the original.

**Comment by Seldaek** [comment]
Done https://github.com/composer/composer/pull/2990#issuecomment-97597919

**Comment by emillosanti** [comment]
:+1:
