### ISSUE TITLE
Exclude packages

### ISSUE THREAD

**Issue by infastra** [composer/composer#1549]
Hi,

few days ago I gave composer a chance and tried this tool. The tool works very well for me, but I'm missing one feature. In comparison to maven, I would like to exclude some libraries for downloading. For example, I'm using zend-http, but only a small part of it. Unfortunately composer load the complete framework. Ok, composer does only that what it will find in the composer.json-file. Can I manipulate this behaviour or could it be a new feature in composer?

Thanks and best wishes
Mathias

**Comment by kenorb** [comment]
I've found the workaround to exclude the packages by using `replace`. Here is the example:

```
{
    "require": {
        "radic/tmp-underscore-php": "1.2.0"
    },
    "replace": {
      "patchwork/utf8": "*"
    }
}
```

In above example, normally `patchwork/utf8` should be installed, however `replace` excludes the given package telling Composer that we've this package already, so it'll ignore it.
