### ISSUE TITLE
Point a dependency to my own fork

### ISSUE THREAD

**Issue by Svish** [composer/composer#1551]
I have the dependency `"torophp/torophp": "dev-master"`  in my `composer.json`. When I ran `composer install` it pulled the latest code from [github.com/anandkunal/ToroPHP](https://github.com/anandkunal/ToroPHP).

I have now created a fork at [github.com/Svish/ToroPHP](https://github.com/Svish/ToroPHP) and committed a fix. I've sent a pull request, but is there a way I can point Composer to my own version instead of the original? In case it takes a while before the pull request is accepted or I find more things I'd like to fix.

**Comment by marlocorridor** [comment]
@eyecatchup  thanks for http://getcomposer.org/doc/05-repositories.md#vcs link. :)

**Comment by crmpicco** [comment]
@eyecatchup Thanks for the write-up. :+1:
