### ISSUE TITLE
Require Command duplicates Dependencies into an uninstallable Set of Packages

### ISSUE THREAD

**Issue by digitalkaoz** [composer/composer#1560]
i think there is something wrong with the require-command:

original composer.json:
``` json
    "require": {
        "php": ">=5.3.2",
        "symfony/framework-bundle": ">=2.1,<2.3-dev"
    },

    "require-dev": {
        "kriswallsmith/buzz": ">=0.7"
    },
```

after `composer require symfony/framework-bundle:2.1.* --prefer-source --dev`

``` json
    "require": {
        "php": ">=5.3.2",
        "symfony/framework-bundle": ">=2.1,<2.3-dev"
    },

    "require-dev": {
        "kriswallsmith/buzz": ">=0.7",
        "symfony/framework-bundle": "2.1.*"
    },
```

`require` says: install 2.2,  `require-dev` says install 2.1 but 2.2 ist already installed...

i think it should replace the dependency in the `require` section instead.

An Example can be found here: https://travis-ci.org/liip/LiipMultiplexBundle/jobs/4571345

**Comment by curry684** [comment]
Shouldn't this just merge a dev-install to `2.1.* && >=2.1 && <2.3-dev`, thus installing the latest of the `2.1` stables?

**Comment by Seldaek** [comment]
Don't think it's such an issue in practice, doesn't seem to come up ever so let's close.
