### ISSUE TITLE
Show available higher versions in status command (was: Add Ignored Package Warning to --verbose?)

### ISSUE THREAD

**Issue by jpalawaga** [composer/composer#1563]
#### Edited!
See my reply to igor below regarding this bug/feature request.

Summary: If composer ignores a more recent version of a package due to a missing dependency, is it possible to have composer say so when the --verbose flag is specified? This would help to make sure that installations are properly maintained, when an external line of communication does not exist to otherwise notify someone that their package needs a (possible critical) update.

#### Original
__Title__ composer ignores revisions > .9?
I'm trying to fetch a new bundle tagged 1.1.10, but composer keeps fetching 1.1.9.

Without having to dig through source, can anyone tell me what is happening? Is composer really evaluating '1' to '9' and then deciding to grab the earlier revision? Is there any solution other than tagging revisions using a double-digit number (.09, .10)?

Is this expected behaviour? Took a look through the issues, but couldn't find anything relevant.

**Comment by Seldaek** [comment]
Referencing #5028 which should fix this.

**Comment by jpalawaga** [comment]
@Seldaek fabulous, thanks!

**Comment by Seldaek** [comment]
`composer show -l` or `composer outdated` now do the job.
