### ISSUE TITLE
Windows executable behind corporate proxy

### ISSUE THREAD

**Issue by gplusdotgr** [composer/composer#1564]
Hello,
I am trying to install Composer in Windows 7, but as I am behind a proxy, the executable fails to download the packages needed.
Are there any workarounds on that? Any full installation executable I can use?

**Comment by ahamrani** [comment]
Hello,

I have the same problem with the latest version of the windows executable, I tried to set variable http_proxy but nothing changed, I have this error want I run composer executable : 

Connection Error [ERR_CONNECTION]: Unable to connect to getcomposer.org

Request to http://getcomposer.org/installer failed with errors:
Php_network_getaddresses: getaddrinfo failed: Hôte inconnu. . Failed to open stream: php_network_getaddresses: getaddrinfo failed: Hôte inconnu. 

Hôte inconnu == Unknown host

Thanks
