### ISSUE TITLE
Cannot download dependency : composer cloning failed using an ssh key for authentication, enter your Github credentials to access private access

### ISSUE THREAD

**Issue by jvanbouchaute** [composer/composer#1570]
For a certain  package, I cannot download it via composer.
I get following error : 

Updating dev dependencies
- Installing bugplaytix/phantomjs-test (dev-master ea57108)
  Cloning ea5710874716de7a29af760fe202aa0eaed6874f
  Cloning failed using an ssh key for authentication, enter your Github credentials to access private repos.

Then it asks for a username / pwd.

The lib that fails to download is : 
https://packagist.org/packages/buyplaytix/phantomjs-test

I referenced it in our projects composer.json as : 

 "require-dev":{
        "buyplaytix/phantomjs-test": "dev-master"
    },

Composer version aa1c093

Any idea how to solve this ?
Many other dependencies do download correctly via composer.

Thanks.

**Comment by ramphy** [comment]
You need install first "GIT"

apt-get install git

and then composer again.
