### ISSUE TITLE
Speed up generated autoloaders

### ISSUE THREAD

**Issue by dlsniper** [composer/composer#1585]
Hello,

I've did some research with a friend, @talpah, and, as expected, the generated autoloaders can be improved in terms of speed by removing the 

```
// autoload_classmap.php generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);
```

part of the `autoload_classmap.php` and `autoload_namespaces.php` and replacing them with real paths and no concatenation instead.

The benefits should be quite clear, especially for large arrays, as for each entry in them instead of having two operations done, we'll do only one.

I've yet to test it on what happens when using op-code caching but since not all people can benefit from it, I think it would be a nice addition.

What's the opinion on this? Would this be a good addition? Aside from the cases where you move the application without regenerating the autoloaders, I don't see many problems.

Also, any pointers on how this could be done in a clean manner?

Thank you!

**Comment by dincho** [comment]
> composer install --optimize-autoloader --with-absolute-paths, or composer install -o -a, but also for composer update, of course.

It would be better $vendorDir to be passed as parameter, so you can generate the classmap on "deployer" machine for other/production machines.

Something like: 

```
composer install --optimize-autoloader --with-absolute-path=/home/production/app/vendor
```

Just FYI, I see this is old and closed.

**Comment by sebastien-fauvel** [comment]
@dincho could you open a new issue with your proposal?

**Comment by dincho** [comment]
I'm not sure that It's OK to do so once it's already closed. IMO the contributor that closed it should take that decision. In this case @Seldaek. I don't want to flood with new issues with the same subject.

**Comment by Seldaek** [comment]
Feel free to open a new issue for this yes.
