### ISSUE TITLE
Tool for validating repository packages.json

### ISSUE THREAD

**Issue by weierophinney** [composer/composer#1608]
We build our own packages.json file for packages.zendframework.com. On several occasions we have had syntax/schema issues in our file. These are relatively easy to catch by adding a repository entry to a composer.json pointing to a local dev server... except for when packagist.org is unresponsive. In that situation, because composer times out when trying to grab package information, we are unable to find out if our packages.json file is well-formed, as a different error is raised (if at all).

I'd like to see a complement to the "validate" command, "validate-repository", that can validate a packages.json file. This would allow us to automate our processes and prevent issues in the future.

**Comment by Seldaek** [comment]
Don't think it's really needed.
