### ISSUE TITLE
Lock file not updated when only repo pathes change

### ISSUE THREAD

**Issue by edorian** [composer/composer#1620]
When the URL of a repository changes (but not the commit/file sha) the lock file doesn't get updated when running `composer update`.

This leads to failing installs on systems that only install from the lock file.
### Reproduce:

```
echo "1" > /tmp/foo.php
zip /tmp/foo.zip /tmp/foo.php
cp /tmp/foo.zip /tmp/bar.zip
mkdir composer-1620 && cd composer-1620
vi composer.json
```

using this composer.json file:

```
{
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "foo/bar",
                "version": "1.0.0",
                "dist": {
                    "url": "/tmp/foo.zip",
                    "type": "zip"
                }
            }
        }
    ],
    "require": {
        "foo/bar": "*"
    }
}
```

Running `composer install` results in this `lock` file:

```
{
    "hash": "ffd99334693f19c1133026fc14a8f303",
    "packages": [
        {
            "name": "foo/bar",
            "version": "1.0.0",
            "dist": {
                "type": "zip",
                "url": "/tmp/foo.zip",
                "reference": null,
                "shasum": null
            },
            "type": "library"
        }
    ],
    "packages-dev": null,
    "aliases": [

    ],
    "minimum-stability": "stable",
    "stability-flags": [

    ]
}
```

now going back to the composer json changing the `"url"` from `foo` to `bar` field to:

```
                "dist": {
                    "url": "/tmp/bar.zip",
                    "type": "zip"
                }
```

and running `composer update` will not change the lockfile.

Which means removing the old "repo" and reinstalling fill fail

```
rm -rf /tmp/foo.zip ./vendor ~/.composer/cache
composer install
```

now results in:

```
Loading composer repositories with package information
Installing dependencies from lock file
  - Installing foo/bar (1.0.0)
    Downloading: 100%         

  [Composer\Downloader\TransportException]                                                           
  The "/tmp/foo.zip" file could not be downloaded: failed to open stream: No such file or directory
```
### Basic gist:

Running

```
composer update
rm -rf ./vendor/ ~/.composer/cache
composer install
```

should not result in the update working but reinstalling failing.
### Expected:

Lock file gets updated and the `url` now reads `/tmp/bar.zip`.
### Actual

Lock file stays the same.
### Workaround

Deleting the lock file and running `composer install` produces the correct lock file but it ofc changes all the other versions. 

Editing the lock file manually (or removing that section and running update) works too.

---

Thank you!

**Comment by ianfp** [comment]
@fazy Thanks for the `rm -rf` trick -- that's a nice workaround.

**Comment by archon810** [comment]
Just spent an hour trying to figure out why even after we updated a zip download to a git checkout, composer was still installing the zip version. Updating a source should generate at least a warning and at best realize it and update the lock file.

**Comment by clphillips** [comment]
Also ran into this issue when changing the URL for satis from **http** to **https**. Got a bunch of errors like:

```
Installing phpunit/php-code-coverage (2.2.4)
Failed to download phpunit/php-code-coverage from dist: Your configuration does not allow connections to http://urltosatisserver/
```

**Comment by arusa** [comment]
It cost me sooooo much time. Why is composer doing this?

I change the URL and composer doesn't update it in composer.lock.
I update it manually in composer.lock and `composer update` just changes it back.

grep -r now exposed where composer cached the old URL:

./vendor/composer/installed.json

**Comment by c33s** [comment]
sadly this is still a thing. moving repo urls should not be such a thing. the error message in the ci has not really helped me at first. had to debug it quite a while.

```
Failed to extract c33s/robofile: (9) '/usr/bin/unzip' -qq '/builds/.robo/vendor/composer/tmp-ef64f8d6b64e60d01466e25da95814ed.zip' -d '/builds/.robo/vendor/composer/c326349e'
[/builds/.robo/vendor/composer/tmp-ef64f8d6b64e60d01466e25da95814ed.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /builds/.robo/vendor/composer/tmp-ef64f8d6b64e60d01466e25da95814ed.zip or
        /builds/.robo/vendor/composer/tmp-ef64f8d6b64e60d01466e25da95814ed.zip.zip, and cannot find /builds/.robo/vendor/composer/tmp-ef64f8d6b64e60d01466e25da95814ed.zip.ZIP, period.
    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class
    Install of c33s/robofile failed
                                                                                                                                     
  [UnexpectedValueException]                                                                                                         
  '/builds/.robo/vendor/composer/tmp-ef64f8d6b64e60d01466e25da95814ed.zip' is not a zip archive
```

removing the package, update it and readd it wasn't a good solution because all dependencies also where updated, which wasn't the desired result in my case.

the `rm -rf package` solution worked fine though.

is there anything composer can do about this?


wouldn't this be possible?:
- getting an error because it is no valid zip
- check the current url in the lock file against the remote info on packagist
- autofix the url in the lock file

**Comment by stof** [comment]
@c33s please open a new issue describing exactly your situation instead of commenting on an issue closed since 3 years
