### ISSUE TITLE
Process blocked in "Updating dependencies"

### ISSUE THREAD

**Issue by fesja** [composer/composer#1632]
From 2 days ago, I'm having an error updating the dependencies with Composer. It fails (sometimes) both with Capifony and executing the following script: 

```
php composer.phar update --no-scripts --verbose --prefer-dist

 ** [out :: server.com] Loading composer repositories with package information
 ** [out :: server.com] Reading composer.json of oryzone/media-storage (v2.0.0)
 ** [out :: server.com] Importing tag v2.0.0 (2.0.0.0)
 ** [out :: server.com] Reading composer.json of oryzone/media-storage (master)
 ** [out :: server.com] Importing branch master (dev-master)
 ** [out :: server.com] Reading composer.json of oryzone/media-storage-bundle (v2.0.0)
 ** [out :: server.com] Importing tag v2.0.0 (2.0.0.0)
 ** [out :: server.com] Reading composer.json of oryzone/media-storage-bundle (2.0)
 ** [out :: server.com] Importing branch 2.0 (2.0.x-dev)
 ** [out :: server.com] Reading composer.json of oryzone/media-storage-bundle (master)
 ** [out :: server.com] Importing branch master (dev-master)
 ** [out :: server.com] Updating dependencies
```

And there it blocks (the php process stops after 1.45min but it doesn't show anything here).

Any idea on what could it be? Problems with the memory? Problems with Composer? I've added this to composer.json it doesn't affect.

```
"config": {
    "process-timeout": "1000"
},
```

**Comment by Ronan-Lenor** [comment]
i got also this problem. And then i restared my computer, and did not start any VPN service. then it work well.

i'm not sure that it was the reason of the problem, but you can still try this if you are stuck.

**Comment by staabm** [comment]
PHP has some bugs in timing out SSL/HTTPS connections. Because of those your script might block endless.
