### ISSUE TITLE
I'm trying to download composer and am unsure where my php.exe will be located

### ISSUE THREAD

**Issue by Admin-UK** [composer/composer#1686]
If anyone could help please? :)
When I clicked download composer it asked stated it needed to check my PHP and path settings. 
It then asked me to select where my php.exe is located and press next. 
No items match my search when I searched for it in my start menu.  
I know this will sound very simple to you guys but I'm just starting out so learning as I go! 
I'm on wordpress and have a hosting company at one.com I'm not sure how relevant that is! 
Thanks 
George

**Comment by navneet1v** [comment]
go to this address if you use WAMP SERVER , the n you can find the php.exe file
C:\wamp\bin\php\php5.4.12\php.exe

this is where i found the php.exe thanks MohammadHeydari

**Comment by Aldanzein** [comment]
on xampp you can find the php.exe file C:\xampp\php

**Comment by mosleim** [comment]
nothing php.exe on C:\xampp\php
it's just php-win.exe and php-cgi.exe.
when i use command php-win.exe nothing return.

**Comment by Clemant007** [comment]
well well well . Where is Admin-UK I think i can help you cuz we have same prob.
Just start installing the composer okay when they ask for php.exe follow the link
C:\wamp\bin\php\php version (eg 5.3.10)\php . You will see php and not php.exe.
Select the php and when you take open it will appear as php.exe. Then we are good.

**Comment by rairajbir17** [comment]
I am facing same problem. I have installed mysqlworkbench. Am i need to install to Wamp? to find php.exe.

**Comment by SedemQuame** [comment]
Had the same problem finding the path of the php.exe file, finally did it.
I use xampp as my local server has php already in the package so all u need to do is locate php folder
in xampp folder, and click the php.exe file once u open it..
*Path:* xampp -> php -> php.exe
hope this helped somebody ;)

**Comment by fajaede** [comment]
C:\mamp\bin\php\php version (eg 8.1.)\php.exe
