### ISSUE TITLE
"failed to open stream" : can't do anything when connected to office network (proxy)

### ISSUE THREAD

**Issue by picks44** [composer/composer#1706]
Hello,

I'm using Composer to manage Symfony bundles, and I have a big issue : when I'm on my office network, I can't do anything with Composer (self-update, update...). I have to either use my mobile phone network or go home to be able to dowload/update my bundles... It's not very convenient. My office network uses a .pac (proxy auto-config) file or a proxy to connect to the internet

I always get the same error on my console : 
`The "http://getcomposer.org/version" file could not be downloaded: failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`

Any clue ?

**Comment by pravinady** [comment]
Awesome... saved me ton of time!!!

**Comment by naumankhan** [comment]
I have the same issue, can you write your solution here please

**Comment by engtobe** [comment]
i have the same issue too, please i need help
