### ISSUE TITLE
Add a diff option when changes are detected during an update.

### ISSUE THREAD

**Issue by Petah** [composer/composer#1708]
It would be nice if a diff option was added when changes are detected during an update.

    - Updating vendor/project dev-master (7d85ba5 => cba8a7c)
      The package has modified files:
      M some-file.php
      Discard changes [y,n,v,s,?]? ?
      y - discard changes and apply the update
      n - abort the update and let you manually clean things up
      v - view modified files
      s - stash changes and try to reapply them after the update
      ? - print help

**Comment by Pictor13** [comment]
:+1: Same. Would be really useful and absolutely time-saving!

**Comment by TomasVotruba** [comment]
:+1:

**Comment by Seldaek** [comment]
This is present for uncommitted changes in VCS installed packages. Not feasible for the others, so closing.
