### ISSUE TITLE
Generation of autoloader incorrect 

### ISSUE THREAD

**Issue by rejinka** [composer/composer#1710]
I get really strange "class not found"-fatal-errors with composer since my last composer::selfupdate. Standard classes of symfony/symfony like the ParameterBag or Request could not be found.

Yesterday i had a small chat with apanek in the composer channel in freenode. He told me to give you everything in the following gist with hope someone can "shed some light on that": https://gist.github.com/rejinka/5186727

Right now with my autoload-files "Assetic\Extension\Twig\AsseticExtension" can not be found.

P.S.: Composer version d929a0813ae473272d151d9ebb2af7ebae451e48

**Comment by mclemme** [comment]
Ran into the exact same issue, Ubuntu 12.04 LTS (server) w/ PHP 5.4.36.

`sudo service php5-fpm restart` after running composer install made it work again.
