### ISSUE TITLE
Generating autoload files even though nothing changed

### ISSUE THREAD

**Issue by mac-cain13** [composer/composer#1715]
I noticed that composer always generates the autoloader after a `composer install`, even if nothing changed in the dependencies. Since I use `composer install --optimize-autoloader` with each deploy on the server generating the optimized autoloader takes a little time.

Is there a specific reason for regenerating the autoloaders even if nothing was updated or newly installed? I think it would make things a little faster if this was skipped. People can use the `composer dumpautoload` command if they need to force gegeneration of the autoloader.

Would this be a good update or is there something I'm missing?

**Comment by staabm** [comment]
As I just found this issue via google: the requested feature of this issue was implemented in https://github.com/composer/composer/commit/8429a48dac648dd77cbb5883995c0175e63dd02d
