### ISSUE TITLE
Add SvnExportDownloader (was: composer still installs .svn sub folders)

### ISSUE THREAD

**Issue by gbaumgart** [composer/composer#1716]
we encountered the same issue as described here : https://groups.google.com/forum/?fromgroups=#!topic/symfony2/bqPKez8DkG4. 

however, we had a huge mess updating to svn 1.7 just to satisfy composer but : NO, its still installing .svn subfolders. 

Any ideas ?

**Comment by CrashSensei** [comment]
For those that are interested I have written a composer plugin that adds the SvnExport feature.  You can find it at [linearsoft/composer-svn-export](https://packagist.org/packages/linearsoft/composer-svn-export)

**Comment by Seldaek** [comment]
Closing as the plugin does the job I suppose.
