### ISSUE TITLE
Composer on Windows 7 (x64)

### ISSUE THREAD

**Issue by mstraczkowski** [composer/composer#1720]
I'm not new in composer and PHP I already used it a lot of time on Linux and on Windows too, but today I encountered a problem.

Today I tried to use composer update / composer install on my Windows 7 and then I got an exception: "Composer could not find the config file:" it is strange, because it was working few days ago.

I tried use the newest composer.phar and also tried use composer installed by Composer-Setup.exe, also I tried put composer.phar on different location (project location etc) it always throwing me the same exception.

When I run composer validate command I've got: ./composer.json is valid, so composer.json was found and is valid.

Thanks for all answers

**Comment by jrm1987** [comment]
After removing the environment variable (if at all you added it in the first place), make sure you restart the CygWin terminal.

**Comment by romaricsylvain** [comment]
Have a same probleme "(include_path='.;C:/laragon/etc/php/pear')"
