### ISSUE TITLE
Scripts doc should mention that scripts must be PSR-0 autoloadable

### ISSUE THREAD

**Issue by igorw** [composer/composer#1726]
Also applies to custom installers. These need to be PSR-0 autoloadable, and the docs should reflect that.

**Comment by alcohol** [comment]
@Seldaek is this still an issue? I think scripts cover more now and the documentation is quite extensive?

**Comment by Seldaek** [comment]
They're still exclusively psr-0/4 autoloadable which is covered in docs I suppose but one day, I have a dream that we will autoload anything at any time :p

**Comment by Seldaek** [comment]
Closing as we support classmap + psr-0/4 now
