### ISSUE TITLE
composer require does not show versions available for a package

### ISSUE THREAD

**Issue by cjunge** [composer/composer#1731]
When using composer require Composer used to show the versions available to install for a package, now it doesn't anymore.

For example:
```composer require perbility/bcrypt-bundle``` used to display a list of available versions with numbers next to them to select, now it just asks `"Please provide a version constraint for the perbility/bcrypt-bundle requirement:"` which leaves it up to the user to search Packagist for the version they want to use.

**Comment by Seldaek** [comment]
We fixed this now by automatically generating a requirement.
