### ISSUE TITLE
Wrong paths to autoloaded files/folder when composer is ran from symlink folder in windows

### ISSUE THREAD

**Issue by crissi** [composer/composer#1744]
if the folder you run composer from is a symlink in windows

It will generate wrong paths to autoloaded folders/files. This was working fine in earlier versions.

It is appending the first dir twice like this: \develop\develop\autoloadedFolder\file.php

Where the path should have been: \develop\autoloadedFolder\file.php

**Comment by Seldaek** [comment]
Closing as it hasn't popped up in years.. if it is still an issue please let me know and i'll reopen.

**Comment by emerinohdz** [comment]
This is still an issue. Many setups use symlinks, so our autoloaders are broken when used like this.

**Comment by martin55** [comment]
Still an issue

**Comment by Seldaek** [comment]
If you still have an issue here please open a new issue with details about what is happening and how to exactly reproduce it.
