### ISSUE TITLE
VCS repo should take package name from branch

### ISSUE THREAD

**Issue by igorw** [composer/composer#1761]
Scenario:
- user forks an upstream repo on github
- creates a feature branch with some changes
- updates the package name in his feature branch
- tries to install his feature branch on a project via vcs repo
- it fails "could not find package"

The problem is that composer gets the package name from the master branch and no the feature branch. so the renaming has no effect.

This should be fixed.

**Comment by sun** [comment]
@Seldaek The documentation change in https://github.com/composer/composer/commit/4a5f1babf7524cca1e942cc31751128ac9126b68 does not actually state what you stated in https://github.com/composer/composer/issues/1761#issuecomment-15821781 — especially the most important part is missing:

> The name is always taken from master (or whatever the default branch is)

We just spent a lot of time to debug a dependency – this simple truth was the missing puzzle piece which is not actually stated in the documentation.  Any chance to add that?
