### ISSUE TITLE
preferred-install from ~/.composer/config.json not recognized

### ISSUE THREAD

**Issue by schmunk42** [composer/composer#1780]
I set my preferred install method for my local machine to `source` in `~/.composer/config.json`:

```
 {
     "config": {
         "preferred-install": "source",
         "github-protocols": ["https","http","git"],
         [...]
     }
 }
```

But when I try to create my project with `composer.phar create-project phundament/app`. I get the following package from cache and not as a repo:

```
- Installing crisu83/yii-bootstrap (1.2.0)
  Loading from cache
```

But when I run `composer.phar create-project --prefer-source phundament/app`. I get:

```
- Installing crisu83/yii-bootstrap (1.2.0)
  Cloning 524486d5ecedd42d8a0d5e3e8756a16ca4e2b3e3
```

I also remove my caches and tried again, but with the same behavior.

Composer Version: a0d1d59868adfd07385e95b6b6999b1fc3e023ce updated today

**Comment by logig** [comment]
composer Version 1.6.5
There is still the same problem.

Some packages have only dist and no source, In order not to report errors in `composer install`, I must `composer install --prefer-dist`, `composer config -g preferred-install dist` does not work.
