### ISSUE TITLE
can't install composer (problem with "php_checkuid" in php5ts.dll

### ISSUE THREAD

**Issue by Fnorb** [composer/composer#1785]
Hi.
Tried to install composer. It says something about a procedure entry point "php_checkuid" not found in the file "php5ts.dll".

Said file is on my system in C:\xampp\php\php5ts.dll .

Anyone got any advice?

**Comment by Eccenux** [comment]
Had this problem when I had 3 versions of PHP installed and the one in pointed by system variables was PHP 5.2. Composer tried to use old version of PHP even though I've pointed it to PHP 5.5.

To resolve this I had to change my settings and manually make PHP 5.5 the default version.
