### ISSUE TITLE
composer install is slow in virtualized shared folders

### ISSUE THREAD

**Issue by nu7hatch** [composer/composer#1787]
Hi guys! I'm trying to run `composer install` on my CentOS 6.3 powered vagrant box with composer being installed globally and it runs super slow. Script basically hangs for minute or more on `Extracting archive` step. It's not a problem of the network as downloading runs very fast (we have 100mb fiber here), it's not a problem of the resources neither, box has 480mb of ram and does not use more than 80 while running composer. Composer is installed in the newest version. 

Running with --prefer-dist also doesn't help. 

The same version of composer runs normally on Mac and on Ubuntu, so I assume that's a CentOS related problem or some quirk with Vagrant/VirtualBox. To make sure I'll set up a Vagrant box based on Ubuntu and test it out. Meanwhile, maybe someone can check it out on real installation of CentOS 6.3?

**Comment by Seldaek** [comment]
This has been fixed a while ago we now always extract in the vendor dir.
