### ISSUE TITLE
Different autoload_classmap.php on different servers resulting in fatal errors

### ISSUE THREAD

**Issue by TiGR** [composer/composer#1790]
I get similar "Cannot redefine class" errors on server (not on local machine). Composer is of the same version on both machines - 894f530. PHP version differs. Everything is okay on PHP 5.4.6 and the error triggers at PHP 5.3.13.

composer.json (minified to only bogus library):

    {
        "require": {
            "nusphere/nusoap": "0.9.5"
        },
        "repositories": [
            {
                "type": "package",
                "package": {
                    "name": "nusphere/nusoap",
                    "version": "0.9.5",
                    "dist": {
                        "url": "http://downloads.sourceforge.net/project/nusoap/nusoap/0.9.5/nusoap-0.9.5.zip",
                        "type": "zip"
                    },
                    "autoload": {
                        "classmap": ["lib/"]
                    }
                }
            }
        ]
    }

Files autoload_classmap.php are different. Here is the difference:

```diff
-     'nusoap_base' => $vendorDir . '/nusphere/nusoap/lib/class.nusoap_base.php',
-     'nusoap_client' => $vendorDir . '/nusphere/nusoap/lib/class.soapclient.php',
+     'nusoap_base' => $vendorDir . '/nusphere/nusoap/lib/nusoap.php',
+     'nusoap_client' => $vendorDir . '/nusphere/nusoap/lib/nusoap.php',
...
-     'soapclient' => $vendorDir . '/nusphere/nusoap/lib/class.soapclient.php',
+     'soapclient' => $vendorDir . '/nusphere/nusoap/lib/nusoap.php',
```

nusoap.php file is compilation of all classes in that directory. I understand that this kind of files do not look really well, but different behavior on different machines is alarming and should not happen.

**Comment by cordoval** [comment]
just in case if someone else runs into this, please do not create a package of your own, there are already plenty of these https://packagist.org/search/?q=nusoap and it is not fun cc @Seldaek

**Comment by Seldaek** [comment]
We now have warnings for conflicting classmap resolutions which should alert users to this sort of issue so they can take action.
