### ISSUE TITLE
Renaming SVN parent folder breaks SvnDriver since it has a higher revision number

### ISSUE THREAD

**Issue by mimez** [composer/composer#1806]
Howdy,

i`ve got a strange behavoir. i got a setup with a own repository:

```
{
    "name": "symfony/framework-standard-edition",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-0": { "": "src/" }
    },
    "repositories": [
        
        {
            "type": "vcs",
            "url": "svn://svn-server/99999/symfony/twig-bundle"
        }
    ],
    "require-all": true,
    "license": "proprietary"
}
```

i tried to rename the svn-path from svn://svn-server/99999/symfony/twig-bundle to svn://svn-server/99999/anotherpath/twig-bundle. of course i also changed the subversion path (svn rename). after that i got that error:

```
[Composer\Repository\InvalidRepositoryException]
  No valid composer.json was found in any branch or tag of svn://lighty-dev/99999/anotherpath/twig-bundle, could not load a package from it.
```

i tested a lot of things (cache clearing, another user, other machines) but i always got the same error. so i debugged composer and found following: My composer.json was on revision 6480, and composer sets this revision to the base revision. the problem is, in this revision the renamed folder doesnt exist, so it breaks up.

my solution was, that i updated my composer.json to get a higher revision in that the folder has its current name.

**Comment by Seldaek** [comment]
Doubt anyone will address this as svn is getting less and less use.. so closing to clean up the issue tracker.
