### ISSUE TITLE
Make Composer use the "Download as ZIP" feature for github projects

### ISSUE THREAD

**Issue by dracony** [composer/composer#1810]
A lot of packages are hosted on Github, why not make composer download zips for those projects instead of cloning. This would make composer not require installation of git + make downloads a bit faster.

**Comment by DarioSwain** [comment]
@stof @Seldaek it is possible to use prefer-dist option with Atlassian Stash or Bitbucket? Or this feature support only GitHub?

**Comment by kamilsk** [comment]
@DarioSwain it is support by git: https://git-scm.com/docs/git-archive

**Comment by DarioSwain** [comment]
Just to clarify.

I store my private packages in Stash repository (with Satis), I try to use --prefer-dist but it doesn't work. My packages always are loaded via git clone.

I want to know, how --prefer-dist option works. Is it using GitHub API to get dist url in Satis/Packagist?

**Comment by davidmaes** [comment]
I have the same exact problem as DarioSwain. I opened a [StackOverflow](http://stackoverflow.com/questions/38923832/using-prefer-dist-with-composer-will-result-in-not-found-the-source-however-c) question about it.
