### ISSUE TITLE
Consider adding basic inheritance support for composer.json

### ISSUE THREAD

**Issue by schmittjoh** [composer/composer#183]
Opening at Jordi's request as discussed on FOSRestBundle.

This would come in handy for testing a bundle against multiple different vendors without duplicating the entire file.

``` json
// composer.json
{
    require: { 
        "symfony/symfony": "2.*", 
        // ... more dependencies
    }
}
```

``` json
// tests/composer-2.0.json
{
    inherit: "../composer.json",
    require: { "symfony/symfony": "2.0.*" }
}
```

``` json
// tests/composer-2.1.json
{
    inherit: "../composer.json",
    require: { "symfony/symfony": "2.1.*" }
}
```

**Comment by nadar** [comment]
+1

**Comment by maximilianredt** [comment]
+1

**Comment by bgallagher** [comment]
:+1:

**Comment by RobinRadic** [comment]
+1 i would use this a lot during development

**Comment by legoktm** [comment]
For MediaWiki we have developed a [composer-merge-plugin](https://github.com/wikimedia/composer-merge-plugin) to add this feature.

The core MediaWiki repo has a composer.json file which includes a composer.local.json file if it exists. Since some MediaWiki extensions also have dependencies installed via composer, a sysadmin would source those composer.json files in their composer.local.json file, and running "composer update" would fetch everything.

**Comment by marcegarba** [comment]
+1

Project inheritance (similar to what Maven does) would be wonderful.

**Comment by gpupo** [comment]
+1

**Comment by Zoddo** [comment]
+1

**Comment by onlab** [comment]
+1

**Comment by maechler** [comment]
+1

**Comment by cansik** [comment]
+1

**Comment by johnitvn** [comment]
+1

**Comment by masasron** [comment]
+1

**Comment by secondtruth** [comment]
This is extremely useful for the use case that @gggeek described. Contrary to @schmittjoh's suggestion, for this use case a `include(s)` field should be preferred ([see here](https://github.com/composer/composer/issues/2480)). A structure like the one that the [composer-merge-plugin](https://github.com/wikimedia/composer-merge-plugin) uses, seems very good.

Another project that, I think, would like to use this feature is [Roundcube Webmail](https://github.com/roundcube/roundcubemail). They use Composer for their [plugin system](https://plugins.roundcube.net/). And I prefer this solution for [my own framework-like project](https://github.com/FlameCore/Infernum), too.

**Comment by aequasi** [comment]
+1

**Comment by haydenk** [comment]
+1

This could be a lot more useful than the local directories feature. You could include subprojects similar to how you can in gradle.

**Comment by etiennemarais** [comment]
+1

**Comment by dashdanw** [comment]
+1 this solves a very particular problem we're having at my company right now using composer with multiple projects.

**Comment by matt-schwartz** [comment]
+1 This would make it a lot simpler for app installations to have custom additions, e.g. for installing plugins.  In Symfony this would make adding multiple 3rd party bundles easier.

**Comment by peter-mw** [comment]
+1

**Comment by ocasta** [comment]
+1 This would make it much simpler to maintain a core docker wordpress image and then add application specific plugins in a dependant container/image

**Comment by andrew-kamenchuk** [comment]
+1

**Comment by lpalgarvio** [comment]
this would be a great addition for drupal when using profiles and features

**Comment by mikebronner** [comment]
+1 I would love this feature for usage with package development as submodules, but then pull in their composer.json to the main project. This would make CI so much easier. (If there's a work-around for this already, please let me know.)

**Comment by alloylab** [comment]
+1

**Comment by dashdanw** [comment]
@mikebronner we have been dealing with similar issues at our job, myself and @matt-schwartz would love to hear if you ever figure out a reliable solution.

**Comment by DracoBlue** [comment]
:+1:

**Comment by bd808** [comment]
@mikebronner [composer-merge-plugin](https://github.com/wikimedia/composer-merge-plugin) should work pretty well for the use case of a main project that wants to aggregate the composer.json files from a number of child packages that are included via git submodules or even embedded in a larger git repo.

Something this simple might do all the work needed:
```
"require" : {
  "wikimedia/composer-merge-plugin": "dev-master"
}
"extra": {
  "merge-plugin": {
    "include": [ "*/composer.json" ]
  }
}
```

This would look for a `composer.json` file in every top level subdirectory of the project and include the contents of all the files found (e.g. `foo/composer.json`, `bar/composer.json`) in the internal Composer configuration at runtime.

composer-merge-plugin was originally only concerned with processing require and require-dev configuration but has been expanded to support [many other configuration sections](https://github.com/wikimedia/composer-merge-plugin#include).

If we can keep this kind of complex use case support out of Composer proper but make it easily available for advanced use cases through the plugin mechanism that seems like a net win for Composer itself in terms of both code complexity and extensiblity. That being said I'd be more than happy to see a core implementation proposed and merged that made composer-merge-plugin obsolete.

**Comment by RyanThompson** [comment]
@Seldaek if this could be included in the plugin API as well, that would be epic. 

My only use case is Pyro but in this particular use case, addons are composer packages (at least in spec, not necessarily on Packagist or anything). So being able to run an update from the project root and let it be aware of the dependencies of each addon would be pretty amazing.

Being that things are moving more and more towards packages and decoupling, I think will be more and more of an important feature.

Ryan

**Comment by quazardous** [comment]
+1

**Comment by kilhage** [comment]
+1

**Comment by PhiloNL** [comment]
+1

**Comment by indrek-k** [comment]
+1

**Comment by snsmurf** [comment]
+1 
For my implementation, we were hoping to be able to have each addon a self contained package that can be dropped in with it's own vendor directory, otherwise we'd need to start allowing customers to rebuild the main composer which is not something we wanted to do.

**Comment by jorgemurta** [comment]
+1

**Comment by curry684** [comment]
Please stop posting +1 all over and use the thumbs up on the main PR post: https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

**Comment by quazardous** [comment]
@curry684 obviously github should be able to catch +1 like they catch #<issue> ...

**Comment by keithy** [comment]
if you use multiple composer.json files with different vendor-dir you end up with two vendor directories. 
lib.json  with vendor-dir /lib
composer.json with vendor-dir /vendor

Then have the lib one include "files":[ "vendor/autoload.php" ]
and have your code include "lib/autoload.php".

generate the /lib directory like so:
env COMPOSER=lib.json composer install

This allows your code to be managed by lib.json
And the user gets their own composer.json with require and require-dev dependencies.

K.

**Comment by Seldaek** [comment]
I just don't see us working on this anytime soon, or ever, so I'm going to close as won't-fix, with the understanding that the [composer-merge-plugin](https://github.com/wikimedia/composer-merge-plugin) is a good solution for those who absolutely need this.
