### ISSUE TITLE
 File could not be downloaded behind a proxy

### ISSUE THREAD

**Issue by pschirch** [composer/composer#1839]
Hi,

I can't download any git repos behind a proxy with composer since few days. Composer can update itselfs, but no other git repos.

For example:

``` bash
$ php composer.phar create-project symfony/framework-standard-edition path/ 2.2.1
```

results in:

```
[Composer\Downloader\TransportException]
The "https://api.github.com/repos/symfony/symfony-standard/zipball/v2.2.1" file could not be downloaded (HTTP/1.0 500 Internal Server Error)
```

**System configuration:**
- configured enviroment `http_proxy` & `https_proxy`
- PHP 5.4.14
- Composer 81d55544f714cca03d5eb784d67a06f8148bcb15

The proxy configuration works fine (Mozilla, Thunderbird, ...). Downloading the file with `wget` or `curl` works too:

``` bash
$ wget https://api.github.com/repos/symfony/symfony-standard/zipball/v2.2.1
```

Any advice?

**Comment by sentenza** [comment]
@pschirch [here](https://github.com/composer/composer/issues/1839#issuecomment-18679885) solved my proxy problems. Thanks!
