### ISSUE TITLE
Uncaught exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory'

### ISSUE THREAD

**Issue by kimdcottrell** [composer/composer#1849]
COMMAND RAN AND ERRORS THROWN
[root@s15937355 htdocs]# php composer.phar update laravel/*
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory' in phar:///var/www/vhosts/defaul
t/htdocs/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:975
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'proc_open(): fo...', 'phar:///var/www...', 975, Array)
#1 phar:///var/www/vhosts/default/htdocs/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(975): proc_open('stty -a | grep

 ...', Array, NULL, NULL, NULL, Array)
#2 phar:///var/www/vhosts/default/htdocs/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(853): Symfony\Component\Console

\Application->getSttyColumns()
#3 phar:///var/www/vhosts/default/htdocs/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(818): Symfony\Component\Console

\Application->getTerminalDimensions()
#4 phar:///var/www/vhosts/default/htdocs/composer.phar/vendor/symfony/console/Symfony/Component/Console/App in phar:///var/www/vhosts/default/htdocs/co

mposer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php on line 975

COMPOSER.JSON FILE CALLED WHEN UPDATING LARAVEL
{
    "name": "laravel/framework",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "authors": [
        {
            "name": "Taylor Otwell",
            "email": "taylorotwell@gmail.com"
        }
    ],
    "require": {
        "php": ">=5.3.0",
        "classpreloader/classpreloader": "1.0._",
        "doctrine/dbal": "2.4.x",
        "ircmaxell/password-compat": "1.0._",
        "filp/whoops": "1.0.4",
        "monolog/monolog": "1.5._",
        "nesbot/carbon": "1._",
        "patchwork/utf8": "1.1._",
        "predis/predis": "0.8._",
        "swiftmailer/swiftmailer": "4.3._",
        "symfony/browser-kit": "2.3._",
        "symfony/console": "2.3._",
        "symfony/css-selector": "2.3._",
        "symfony/debug": "2.3._",
        "symfony/dom-crawler": "2.3._",
        "symfony/event-dispatcher": "2.3._",
        "symfony/finder": "2.3._",
        "symfony/http-foundation": "2.3._",
        "symfony/http-kernel": "2.3._",
        "symfony/process": "2.3._",
        "symfony/routing": "2.3._",
        "symfony/translation": "2.3._"
    },
    "replace": {
        "illuminate/auth": "self.version",
        "illuminate/cache": "self.version",
        "illuminate/config": "self.version",
        "illuminate/console": "self.version",
        "illuminate/container": "self.version",
        "illuminate/cookie": "self.version",
        "illuminate/database": "self.version",
        "illuminate/encryption": "self.version",
        "illuminate/events": "self.version",
        "illuminate/exception": "self.version",
        "illuminate/filesystem": "self.version",
        "illuminate/foundation": "self.version",
        "illuminate/hashing": "self.version",
        "illuminate/http": "self.version",
        "illuminate/html": "self.version",
        "illuminate/log": "self.version",
        "illuminate/mail": "self.version",
        "illuminate/pagination": "self.version",
        "illuminate/queue": "self.version",
        "illuminate/redis": "self.version",
        "illuminate/routing": "self.version",
        "illuminate/session": "self.version",
        "illuminate/support": "self.version",
        "illuminate/translation": "self.version",
        "illuminate/validation": "self.version",
        "illuminate/view": "self.version",
        "illuminate/workbench": "self.version"
    },
    "require-dev": {
        "aws/aws-sdk-php": "2.2._",
        "iron-io/iron_mq": "1.4.4",
        "pda/pheanstalk": "2.0._",
        "mockery/mockery": "0.7.2",
        "phpunit/phpunit": "3.7._"
    },
    "autoload": {
        "classmap": [
            ["src/Illuminate/Queue/IlluminateQueueClosure.php"]
        ],
        "files": [
            "src/Illuminate/Support/helpers.php"
        ],
        "psr-0": {
            "Illuminate": "src/"
        }
    },
    "extra": {
        "branch-alias": {
            "dev-master": "4.0-dev"
        }
    },
    "minimum-stability": "dev"
}

PHP MEMORY LIMIT
[root@s15937355 htdocs]# php -r "echo ini_get('memory_limit').PHP_EOL;"
1024M

FREE MEMORY (in megabytes)
[root@s15937355 htdocs]# free -m
                                   total       used       free     shared    buffers     cached
Mem:                          2048        357       1690          0          0        237
-/+ buffers/cache:        119       1928
Swap:                          0          0          0

PHP VERSION
[root@s15937355 htdocs]# php -v
PHP 5.5.0beta4 (cli) (built: Apr 25 2013 15:28:50) 

Any ideas?

**Comment by blue7wings** [comment]
@rfanjul Thanks!

**Comment by BugraDayi** [comment]
@rfanjul Thanks a lot, it works

**Comment by cakpep** [comment]
@rfanjul its cool
