### ISSUE TITLE
GitHub API Limitations when Using Composer on Pagoda Box

### ISSUE THREAD

**Issue by sanderson** [composer/composer#1861]
# Composer, Pagoda Box, & the GitHub API
Composer recently switched from using GitHub's http interface to using the GitHub API to load dependencies ([commit 259a25](https://github.com/composer/composer/commit/259a25344dcb694b1f58b92b36ffe30690474dc4)). When using Composer on Pagoda Box, dependencies are loaded each time an app is deployed. With 100s of Pagoda Box users using Composer and deploying often, calls to the GitHub API add up fast.

By default, Composer's requests to the GitHub API are unauthenticated. GitHub limits unauthenticated API requests to 60 per hour per IP. This means that more people using Composer on Pagoda Box (or any other multi-tenant service provider), the faster the request limit is reached and the more users will be unable to download their dependency libraries. Apps will not deploy on Pagoda Box until dependencies can be successfully downloaded.

Pagoda Box reached out GitHub for possible solutions. Below is GitHub's official response:

>We really wish Composer would use Git instead of the GitHub API because it's far more efficient for this use case.
>
>Are you supplying a GitHub API token [1] in your config? Here's a guide [2] that might help. Be sure to create your token WITHOUT ANY SCOPES [3] if it will be visible to anyone outside your organization.
>
>[1]: http://getcomposer.org/doc/04-schema.md#config
>[2]: http://blog.simplytestable.com/creating-and-using-a-github-oauth-token-with-travis-and-composer/
>[3]: http://developer.github.com/v3/oauth/#scopes"

## Solution
In order for users of any multi-tentant service provider, like Pagoda Box, to be able to successfully and consistently use Composer, Composer will either need to switch to using Git as opposed to GitHub's API, or Composer users will need to include a GitHub API token in their repos.

**Comment by Seldaek** [comment]
Closing as this is a very old issue and not extremely relevant anymore.
