### ISSUE TITLE
i have a server, is there somekind of mirroring?

### ISSUE THREAD

**Issue by adamramadhan** [composer/composer#1866]
is there any mirroring that we can help?

im at indonesia, me and my community would love to use a local repository to update things,  is there something like it available? how can we setup the mirror server?

**Comment by djmattyg007** [comment]
Your reply on the same day to mention repository mirroring on #1233 say that this is possible using some combination of settings. For some reason that wasn't mentioned here, and in neither place did you mention what the settings actually are or where to find documentation on how to do it. I don't think it's acceptable for a major open source project to simply point to a proprietary paid service when someone specifically asks how to do this themselves.

**Comment by curry684** [comment]
Why would that be unacceptable? Ever considered that perhaps Seldaek wants to pay his mortgage too at the end of the month?

Open source is often confused with 'free'. [That's wrong](http://www.gnu.org/philosophy/free-sw.en.html).

> “Free software” means software that respects users' freedom and community. Roughly, it means that the users have the freedom to run, copy, distribute, study, change and improve the software. Thus, “free software” is a matter of liberty, not price. To understand the concept, you should think of “free” as in “free speech,” not as in “free beer”. We sometimes call it “libre software” to show we do not mean it is gratis.

Composer is free and open source. The power tools to enhance it or enterprise-harden it aren't. Not quite unlike just about every other quality open source product out there. [Not even Linux is free when you go enterprise](https://www.redhat.com/wapps/store/catalog.html).

**Comment by djmattyg007** [comment]
As I just pointed out on #1889, no one is demanding that the core development team implement this functionality themselves. People who don't belong to the composer project can also submit pull requests.

If documentation exists (as was implied on #1233), then surely it's incumbent upon the maintainer to link to said documentation, or at the very least point us in the right direction? It's not asking for much. I'm not saying Saldaek shouldn't mention Toran Proxy, just that he should also link to (or at the very least mention where to find) the relevant documentation for the open source alternative that is also available.

**Comment by Seldaek** [comment]
@djmattyg007 first of all my nickname is Seldaek, if you don't want to use auto-completion at least please check your typing.

Then.. the intricacies of mirroring is not something I am willing to spend time documenting, it would benefit very few people and those that really need to implement it themselves can reach out for help if needed or look at how it's done in toran for example. If you have specific questions ask away (in a new issue please, hijacking old stuff that's been closed is quite annoying as it spams everyone that was involved in them). Just blaming us for not doing things how you would have done it and throwing *SHOULDs* around is not the most likely way to get anyone to help you.
