### ISSUE TITLE
Consider making packages autoloadable as soon as they have been installed

### ISSUE THREAD

**Issue by schmittjoh** [composer/composer#187]
This would help with custom installers as they would already have access to all classes of the packages that they are about to install. 

For custom installers themself, Composer currently generates and registers a class map loader. However, these installers might also have dependencies which at the time when the installer is executed are not autoloadable. So, this ticket would solve that issue as well.

I'm not familar enough with the internals, but I think we could just copy the autoloader code which currently resides in the InstallerInstaller class to the LibraryInstaller class and generate a class map loader for each package. What do you think?

**Comment by Seldaek** [comment]
Closing as it's so old and doesn't seem extremely needed after all.

**Comment by nicoschoenmaker** [comment]
@Seldaek it's not extremely needed, but it would save a plugin for having to write code like [this](https://github.com/hostnet/entity-plugin-lib/blob/master/src/Installer.php#L142-L164) :smile:.
