### ISSUE TITLE
Allow "composer require --no-dev"

### ISSUE THREAD

**Issue by chillu** [composer/composer#1874]
`composer require` implicitly calls "composer update", but there's no way to pass through a "--no-dev" flag. `composer require --no-update <module> && composer update --no-dev <module>` is a workaround, but very clumsy.

The `composer update` behaviour was changed at https://github.com/composer/composer/pull/1644.

Context is that we want to promote "composer require" as a preferred way to install modules, but our dev requirements only apply to a small fraction of our devs (e.g. those running behaviour tests through behat)

**Comment by tgr** [comment]
Apparently there's an `--update-no-dev` option these days.

**Comment by iamCristYe** [comment]
@tgr `--update-no-dev` will update other `no-dev` packages, while `composer require --no-update <module> && composer update --no-dev <module>` won't, so there's still slight difference
