### ISSUE TITLE
Composer mirror support

### ISSUE THREAD

**Issue by radmiraal** [composer/composer#1889]
Hey all,

Currently github has issues with a file server causing some repositories to return a 503 status code. This made me think about mirrors and composer. Searching the issues I found some related ones, but not one really only about mirroring.

Of course things like a meta URL or multiple source URLs could be part of a real solution, but in general the lock file still locks to one specific source.

Are there any plans / thoughts regarding mirroring?

**Comment by djmattyg007** [comment]
The original poster of this issue wasn't asking about mirroring. Pointing to a proprietary paid service when someone is asking for a feature in this open source project is not acceptable.

**Comment by djmattyg007** [comment]
I note that my previous comment on this thread, which was simply pointing out that the original poster's question was not directly answered, was deleted. Is there no interest in this functionality? No one is demanding that you implement this functionality yourself. This should be an attempt to gauge interest in the functionality, and knowledge of what the core development team would expect should someone choose to implement this.

**Comment by Seldaek** [comment]
@djmattyg007 you pasted the same comment on 3 issues, which is absolutely unhelpful and borderline spam. There is a discussion ongoing on #1866 where you have been answered so I deleted the rest.
