### ISSUE TITLE
composer update: can't change repository for a vcs dependency

### ISSUE THREAD

**Issue by meonkeys** [composer/composer#1908]
If I change the URL for a dependency, `composer update` won't change composer.lock. 

Use case: 

* install dependency with composer 
* find a bug 
* patch it, send pull request 
* switch to my fork 
* once they apply my patch, switch back 

[Here's a script to demonstrate the problem](https://gist.github.com/meonkeys/5570869).

-Adam 

P.S.:

* [This](http://stackoverflow.com/questions/14636936/change-composer-git-source-for-a-package) is similar, but didn't answer my question.
* Same with [this](https://github.com/composer/composer/issues/1551#issuecomment-12978227), (which seems like a crosspost of the [stackoverflow post](http://stackoverflow.com/questions/14636936/change-composer-git-source-for-a-package)).
* [Crosspost](https://groups.google.com/d/msg/composer-dev/hbO15jcLa-g/BYw3VncTKlUJ).

**Comment by Seldaek** [comment]
Closing as I believe it has been fixed a while back
