### ISSUE TITLE
Git private repo dependencies defined in a dependency issue

### ISSUE THREAD

**Issue by rrajkomar** [composer/composer#1913]
Hello,
All the libraries referred to below are located on same repository, the paths were correctly provided the only issue is on the dependency's dependencies retrieval.

I have a library A which has a dependency on library B's dev-master@dev version with a min-stab set to stable.

The project B itself has another dependency on library C 's dev-master@dev version also with a min-stab set to stable.

When trying to composer install library A, composer can retrieve all dependencies (even those on the git repository) that are defined directly in A's composer.json.
But it throws an error when trying to retrieve library B saying that it can't find library C.

Here are samples of what the composer.json files from A and B look like : 

A : 
"repositories": [
        {
            "type": "git",
            "url":  "git@gitSRV:/gitrepo/B.git"
        },
        {
            "type": "git",
            "url":  "git@gitSRV:/gitrepo/D.git"
        },
        {
            "type": "git",
            "url":  "git@gitSRV:/gitrepo/E.git"
        }
    ],
    "require": {
        "php": "5.3.10",
        "doctrine/common": "2.3.0",
        "B": "dev-master@dev",
        "D": "dev-master@dev",
        "E": "dev-master@dev"
    } 

B : 
"repositories": [
        {
            "type": "git",
            "url":  "git@gitSRV:/gitrepo/D.git"
        },
        {
            "type": "git",
            "url":  "git@gitSRV:/gitrepo/C.git"
        },
        {
            "type": "git",
            "url":  "git@gitSRV:/gitrepo/E.git"
        }
    ],
    "require": {
        "php": "5.3.10",
        "doctrine/common": "2.3.0",
        "D": "dev-master@dev",
        "C": "dev-master@dev",
        "E": "dev-master@dev"
    }

From those types of composer.json files, when composer installing A's composer.json content, only D and E can be retrieved and C can only be retrieved if specified in A's composer.json.

Note this might be normal behaviour but it wasn't expected.

Thanks for any help/light you could provide on this.

**Comment by stof** [comment]
@logical-and see https://getcomposer.org/doc/faqs/why-can%27t-composer-load-repositories-recursively.md

**Comment by logical-and** [comment]
> You may run into problems when using custom repositories because Composer does not load the repositories of your requirements, so you have to redefine those repositories in all your composer.json files

Yeap, quite convenient to redefine the full list :)
