### ISSUE TITLE
Don't scan all svn branches when branch name is set

### ISSUE THREAD

**Issue by ivol84** [composer/composer#1949]
The problem appears when we specify requirement such as:
"annwn_libs/lib": "dev-feat_2457_job_data_error_page@dev".
Composer starts scanning for all branches. And it doesn't stop when find it.
So, for big repository it tooks near 10 minutes.

**Comment by christhomas** [comment]
it's totally possible to circumvent, if there is a branch name and this branch name is found, use it, skip the scanning process altogether.

why is composer scanning a possibly massive list of branches for a match, when a direct lookup could just reveal the branch name exists and use it without the massive overhead, also, hitting githubs api rate limit unnecessarily.
