### ISSUE TITLE
Running an update just hangs

### ISSUE THREAD

**Issue by DaMitchell** [composer/composer#1959]
I can see from running "php composer.phar -vvv update" that it is reading the cache files in ".composer/cache/repo/https---packagist.org" but it just hangs there and doesn't do anything after its finished reading them.

Any ideas whats happening?

**Comment by anoopmd** [comment]
I am also facing a similar problem. (I am on W7.)
composer install does nothing.
The task manager shows a php process running at 50%.
I guess it would be better if the CLI shows some indication that progress is happening and that to give an estimated time for completion.
Npm is better at this.

**Comment by anoopmd** [comment]
As per above comments,I solved the problem by mentioning the version numbers clearly.
And composer started installing dependencies within 10 sec :-)

**Comment by enekochan** [comment]
Although this is an old issue I was facing this same thing and the problem was that I had left the PHPStorm debug connections listener on because I had been debugging some console commands before. That made PHPStorm stop on first PHP line but didn't show me anything.

**Comment by dukhanin** [comment]
I used 
`composer.phar require ... -vvv`
syntax and got the same problem

after some unseccessful tries i've checked the php version  - it was 56 (pretty old, huh?)

7.0.14 version of php solved my one problem
`/usr/bin/php7.0.14 -f ~/bin/composer.phar require ...`

and yes, clear composer cache for sure before update/require:
`/usr/bin/php7.0.14 -f ~/bin/composer.phar clear-cache`

**Comment by kwisatz** [comment]
```
Resolving dependencies through SAT
```

I don't think it's RAM in my case, I have 6Gb in total and still 1.5 Gig free. It's been like this for the past 8 hours…

**Comment by kaiwa** [comment]
@kwisatz kudos for your patience xD

**Comment by kwisatz** [comment]
I'd completely forgotten about it. In my case I think it's upgrading phpmd, or at least trying to, but I have yet to confirm.

**Comment by kwisatz** [comment]
Here's some strace output, maybe that helps:

```
lstat("/etc/php5/cli/conf.d/20-xdebug.ini", {st_mode=S_IFLNK|0777, st_size=31, ...}) = 0
readlink("/etc/php5/cli/conf.d/20-xdebug.ini", "../../mods-available/xdebug.ini", 4096) = 31
lstat("/etc/php5/cli/conf.d/../../mods-available/xdebug.ini", {st_mode=S_IFREG|0644, st_size=25, ...}) = 0
open("/etc/php5/mods-available/xdebug.ini", O_RDONLY) = 6
fstat(6, {st_mode=S_IFREG|0644, st_size=25, ...}) = 0
lseek(6, 0, SEEK_CUR)                   = 0
fstat(6, {st_mode=S_IFREG|0644, st_size=25, ...}) = 0
read(6, "zend_extension=xdebug.so\n", 8192) = 25
read(6, "", 8192)                       = 0
read(6, "", 8192)                       = 0
close(6)                                = 0
lstat("/tmp/CnDEX3", {st_mode=S_IFREG|0600, st_size=0, ...}) = 0
open("/tmp/CnDEX3", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 6
fstat(6, {st_mode=S_IFREG|0600, st_size=0, ...}) = 0
lseek(6, 0, SEEK_CUR)                   = 0
write(6, "[PHP]\n\n;;;;;;;;;;;;;;;;;;;\n; Abo"..., 8192) = 8192
write(6, "aution)\n;   Off = Disabled\n;   I"..., 8192) = 8192
write(6, "tal errors)\n; E_PARSE           "..., 8192) = 8192
write(6, "ty will cause PHP to use the val"..., 8192) = 8192
write(6, " or ftp://) as files.\n; http://p"..., 8192) = 8192
write(6, " in /etc/services or the\n; compi"..., 8192) = 8192
write(6, "nt_severity = 10\n\n; Set per-cont"..., 8192) = 8192
write(6, " URL rewriter will look for URLs"..., 8192) = 8192
write(6, "rresponding encode setting. When"..., 7505) = 7505
close(6)                                = 0
open("/usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache", O_RDONLY) = 6
fstat(6, {st_mode=S_IFREG|0644, st_size=26258, ...}) = 0
mmap(NULL, 26258, PROT_READ, MAP_SHARED, 6, 0) = 0x7fcf4e0c1000
close(6)                                = 0
futex(0x7fcf4ae978f8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
pipe2([6, 7], O_CLOEXEC)                = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fcf4e09aa10) = 11056
close(7)                                = 0
fcntl(6, F_SETFD, 0)                    = 0
read(6, Loading composer repositories with package information
Updating dependencies (including require-dev)
```

With xdebug disabled, I see it actually making break syscalls (to increase the heap?) and then it just stops responding:

```
brk(0x1a1e7000)                         = 0x1a1e7000
brk(0x1a227000)                         = 0x1a227000
brk(0x1a267000)                         = 0x1a267000
brk(0x1a2a7000)                         = 0x1a2a7000
brk(0x1a2e7000)                         = 0x1a2e7000
brk(0x1a327000)                         = 0x1a327000
lstat("/usr/bin/composer", {st_mode=S_IFREG|0755, st_size=1836198, ...}) = 0
lstat("/usr/bin", {st_mode=S_IFDIR|0755, st_size=69632, ...}) = 0
lstat("/usr", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/usr/bin/composer", O_RDONLY)     = 6
fstat(6, {st_mode=S_IFREG|0755, st_size=1836198, ...}) = 0
lseek(6, 0, SEEK_CUR)                   = 0
lseek(6, 312967, SEEK_SET)              = 312967
read(6, "<?php\n\n\n\n\n\n\n\n\n\n\n\nnamespace Compo"..., 8192) = 8192
lseek(6, 318752, SEEK_SET)              = 318752
lseek(6, 318752, SEEK_SET)              = 318752
close(6)                                = 0
```

**Comment by kwisatz** [comment]
In my case, what seems to be causing this is either `phpspec` or a combination of `phpspec` with the remaining items in my devDependencies:

```
"require-dev": {
        "phpspec/phpspec": "~3.0",
        "phploc/phploc": "~2.1",
        "squizlabs/php_codesniffer": "~2.0",
        "phpmd/phpmd": "~2.6",
        "sebastian/phpcpd": "~2.0",
        "sebastian/phpdcd": "~1.0",
        "mayflower/php-codebrowser": "~1.1"
    },
```

Whenever I try to upgrade from phpspec ~2.0 to ~3.0, compose hangs forever at the "Resolving dependencies through SAT" stage.

**Comment by Seldaek** [comment]
@kwisatz this sort of case happens, it's rare but sadly it does, and sadly it's a property of the algorithm that it may not terminate. Not really something that is fixable. What I'd suggest is bumping most require/require-dev to address their latest version directly (like `^3.0.1` for phploc/phploc instead of `~2.1`) to reduce the amount of packages being looked at. That might help.

**Comment by kwisatz** [comment]
@Seldaek Thanks for the advice. It definitely seems to be the amount of lookups it has to do. Setting all devDeps to `^` and (temporarily) removing most deps made it find a solutions rather quickly. I'll try that again with deps set to their latest version that works for this app once I've got some work done.

**Comment by mkamranmalik72** [comment]
composer hangs on "Updating dependencies (including require-dev)"
when i run composer install --prefer-dist Or composer install or composer update
before this problem i instal redis server on macbook please help me to fix the issue.
thanks is advance 

my composer.json file have

{
    "name": "labs64/laravel-boilerplate",
    "description": "Laravel 5 Boilerplate",
    "type": "project",
    "keywords": ["php", "framework", "laravel", "laravel5", "admin", "theme", "starter", "bootstrap", "boilerplate", "docker", "template", "social-login", "nodejs"],
    "homepage": "https://github.com/Labs64/laravel-boilerplate",
    "license": "MIT",
    "authors": [
        {
            "name": "Labs64 GmbH",
            "email": "info@labs64.com",
            "homepage": "http://www.labs64.com"
        }
    ],
    "support": {
        "email": "info@labs64.com",
        "issues": "https://github.com/Labs64/laravel-boilerplate/issues",
        "wiki": "https://github.com/Labs64/laravel-boilerplate",
        "source": "https://github.com/Labs64/laravel-boilerplate",
        "docs": "https://github.com/Labs64/laravel-boilerplate"
    },
    "require": {
        "php": ">=7.0",
        "albertcht/invisible-recaptcha": "^1.4",
        "arcanedev/log-viewer": "~4.0",
        "creativeorange/gravatar": "~1.0",
        "davejamesmiller/laravel-breadcrumbs": "^3.0",
        "devdojo/chatter": "0.2.*",
        "graham-campbell/markdown": "^9.0",
        "kyslik/column-sortable": "^5.4",
        "labs64/netlicensingclient-php": "^2.3",
        "laravel/framework": "5.5.*",
        "laravel/socialite": "^3.0",
        "laravel/tinker": "~1.0",
        "laravelcollective/html": "5.5.*",
        "nahid/talk": "^2.2",
        "yajra/laravel-datatables-oracle": "~8.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~6.0",
        "barryvdh/laravel-debugbar": "^2.1",
        "barryvdh/laravel-ide-helper": "^2.2",
        "doctrine/dbal": "^2.5",
        "filp/whoops": "~2.0"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        },
        "files": [
            "config/Constants.php",
            "app/helpers.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "prefer-stable": true
}
