### ISSUE TITLE
Actual git reference is not checked

### ISSUE THREAD

**Issue by Dundee** [composer/composer#1967]
Hi,
I have found out that composer install or update is not checking the actual reference of git dependencies which is quite confusing.

Usecase:
1. project with one dependency, which is a git repository
2. go to dependency dir and checkout it to another commit/branch/tag (to try if our application is working with this commit). I want to do this directly via git because is much faster and more straightforward.
3. run composer install in project dir to checkout dependency back to where it should be => "Nothing to install or update"

Expected behaviour: Composer should check actual reference of git repositories (similar way as git submodule update do this) and checkout correct commit.

**Comment by smichaelsen** [comment]
Have my +1 for this issue.

**Comment by Seldaek** [comment]
With #1968 fixed you can now at least use `composer status` to see if anything changed. I am kinda reluctant to do this by default on composer install because it makes things quite a bit slower due to all the git subprocesses but let's leave it open for now.

**Comment by slbmeh** [comment]
I think in many cases where vendors have been changed, it was done for a reason unable to be determined programatically. The output from `composer status` does help to get things back to where they should, and an wiping out vendor and clean install as mentioned in #4227 is easy enough. A force flag maybe, but I don't think it's enough of an inconvenience to do the workaround.

**Comment by Seldaek** [comment]
Closing here, feel free to track https://github.com/composer/composer/issues/563 which is I believe the same issue.
