### ISSUE TITLE
"The lock file does not contain require-dev information" returned when I run composer install without --dev

### ISSUE THREAD

**Issue by rjmunro** [composer/composer#1970]
Using the latest version of composer, when I run:

```
php composer.phar install
```

I get the error:

> The lock file does not contain require-dev information, run install without --dev or run update to install those packages.

even though I am not using the `--dev` option.

This happens with Composer version 1a7f734bc78df99553a742dfac6651a4863c00c6 (downloaded today), but didn't happen with the previous version of composer I had installed 68cb9c6606b0bc4741a251f02d849d3514ab8afe, downloaded on 2013-02-01.

It may just be that the error message copy is misleading, and the problem is that my composer.lock file is out of date and needs updating, but IMHO if that's the case it should be fixed.

**Comment by natsu90** [comment]
Just a head up, getting same issue when doing `composer require`, but need to use `--update-no-dev` instead.
