### ISSUE TITLE
Allow comments in composer.json

### ISSUE THREAD

**Issue by gggeek** [composer/composer#1988]
I know comments are not allowed in the json spec, but some parsers are more tolerant than others.
And being able to annotate composer.json would be of great use (f.e. when playing around commenting different parts of composer.json without having to commit, stash or save to a different file)

**Comment by leonex-cstoller** [comment]
+1 for this request, as it is helpful to explain overrides or aliases (like it is user [here](http://mnapoli.fr/overriding-dependencies-with-composer/)).

**Comment by bassrock** [comment]
:+1:

**Comment by KuenzelIT** [comment]
+1 comments would be really useful!

**Comment by claytondaley** [comment]
+1 for comments

**Comment by ryanmc2033** [comment]
+1 for comments

**Comment by RQuadling** [comment]
Maybe composer should switch to yaml for the config?

**Comment by whitehat101** [comment]
I was re-reading through this thread, and one of the links to why composer **shouldn't** support composer, seems to indicate the **opposite**.

https://plus.google.com/+DouglasCrockfordEsq/posts/RK8qyGVaGSr

> Suppose you are using JSON to keep configuration files, which you would like to annotate. Go ahead and insert all the comments you like.
>
> -Douglas Crockford

Douglas Crockford seems to be endorsing comments, not prohibiting them by design.

**Comment by aaukt** [comment]
You left out a very important part:

>Suppose you are using JSON to keep configuration files, which you would like to annotate. Go ahead and insert all the comments you like. Then pipe it through JSMin before handing it to your JSON parser.﻿

Comments are not in the specification for JSON (so they actually are pohibited by design), so you would need to run the annotated JSON through another tool that outputs a valid JSON file.

**Comment by gggeek** [comment]
I know code bloat is bad, but given the amount of developers asking for support of this feature, maybe implementing a strip-comments-from-json component in composer could be an acceptable compromise?
Iiirc there are dozen of jsmin implementations in php out there, one could f.e. get bundled and activated via a cli switch to composer...

**Comment by kravcik** [comment]
+1

**Comment by ryanmc2033** [comment]
This is what one of our devs is doing to add comments
... },
    "//provide ext-pcntl": "Allow composer update to work on windows which does not have ext-pcntl",
    "provide": {
      "ext-pcntl": "0.01"
    }

**Comment by countergram** [comment]
+1 for real comments. Uncommented config by design is not a good idea, and using keys with strings does not allow for commenting out configuration and is awkward in general.

**Comment by frenck** [comment]
+1

**Comment by aight8** [comment]
+1

**Comment by Venzon** [comment]
+1 asap

**Comment by juanvillegas** [comment]
+1

**Comment by whitehat101** [comment]
A co-worker pointed out the humor in my situation:

I'm currently receiving *comment* notifications from the Composer repo by users who want to use *comments* in their `composer.json`, even though Composer forbids *comments*.

**Comment by RQuadling** [comment]
Oh the irony!

**Comment by lhridley** [comment]
+1

**Comment by EJTH** [comment]
+1 Either allow other markup languages for composer config, or implement comment stripping before parsing. Comments in config files is a MUST!

**Comment by adamramadhan** [comment]
+1

**Comment by barryo** [comment]
+1

**Comment by therealmikz** [comment]
+1

**Comment by sormy** [comment]
+1

**Comment by larrykluger** [comment]
+1 Comments in config files is a requirement. Maybe not to a computer scientist, but certainly for any software developer.

**Comment by machinez** [comment]
+1

**Comment by jgautheron** [comment]
+1

**Comment by bjdelange** [comment]
+1

**Comment by SlvrEagle23** [comment]
+1 for comment support directly within Composer.

As a programmer-type person, I understand the tendency of other programmer-type people to say "But it's easy! You just pipe this script through another script that you have to go out and find, integrate into your build process, and then our software works exactly as intended."

However, as a person using this tool in real-world settings as a means of making my life *easier*, I don't see this as a suitable answer. At all.

I get the lecture about how JSON having comments might encourage "bad behavior", but in this case, the markup for an essential configuration file being chained to a format that refuses to support commentary seems genuinely boneheaded. That strikes me as *better* behavior than the two current options, the first being avoiding documentation altogether, and the second being bolting a cumbersome process just to force composer to accept what it should be accepting in the first place.

What I see in this ticket is *years* of problems encountered by real-world users of this tool, met with either a blunt "you're doing it wrong" or some other easy refusal to change the status quo.

Why is this always the way the dialogue goes in open source?

**Comment by sormy** [comment]
I think it's easier and better to make composer.yml support =)

**Comment by potherca** [comment]
I think @sormy is on to something here. It's obvious that comments for the `composer.json` are not likely to be supported. Regardless whether or not you agree with the arguments given *against* the case, the maintainers of Composer have the final say and they say "no".

However, they may be swayed to support a `composer.yml` file which *would* allow comments.

If more people deem this an acceptable solution it might be worth opening a ticket to have a dialog with the maintainers.

Thoughts? @gggeek @Seldaek

**Comment by sormy** [comment]
Actually, *rquadling* mentioned firstly about Yaml support. 
I think implementation of yaml support will be easy - just add auto scan for composer.yml together with composer.json, reading/wring could be done with Symfony Yaml component.

**Comment by JamesRezo** [comment]
Yaml support, this is the idea :-)

**Comment by rquadling** [comment]
@sormy - Yep! Jan 22nd!

I use Phinx (PHP based database migration tool). That uses Symfony/Config that supports yaml, json, xml, ini, array, DB, etc.

The choice is very wide.

But by supporting everything, the composer consumer is given the freedom.

**Comment by paoloavezzano** [comment]
**+1**
Comments are vital in any non-trivial project.
YAML is another option for sure.

**Comment by stof** [comment]
@rquadling by supporting everything, Composer will kill performance of reading metadata, because it will have to lookup for many files in each branch of the repo instead of only one per branch (and also decide about the priority order in case several formats are there).

**Comment by rquadling** [comment]
@stof, then yaml it is then!

**Comment by sormy** [comment]
**stof*** you can keep composer.json for repositories, but for local projects yaml will gave features without any performance loss

**Comment by potherca** [comment]
Then maybe it is time someone created an issue to "officially" request this feature :wink:

**Comment by andrerom** [comment]
Symfony's Yaml Component is rather widely used by now, the only real solution to this issue is to switch to to using it for Composer 2.0*(future version)*, and also backport to 1.0 and deprecate json which is kept as fallback in 1.0 branch.

*yes I'm aware 1.0 is not strictly stable by now, but in terms of worldwide use it is, no matter how @Seldaek might feel about that ;)*

**Comment by Taluu** [comment]
https://github.com/igorw/composer-yaml

just saying.

**Comment by potherca** [comment]
@Taluu Awesome! Very acceptable solution, no faffing about with two json files, uses existing infrastructure. I'm in. Using this as of NOW. :grinning:

**Comment by bassrock** [comment]
I can't get the phar to build upon that link. Would be great to get https://github.com/igorw/composer-yaml forked and actively maintained.

**Comment by gerrywastaken** [comment]
Oh you guys: https://github.com/bower/bower/issues/1059

I agree! Why would anybody possibly want to document why they have added a package to a project. Completely useless suggestion. A format that doesn't support comments is CLEARLY the right choice for something as trivial as a projects dependency configuration.

**Comment by ThaDafinser** [comment]
A nasty trick i saw today
https://github.com/Seldaek/monolog/blob/master/composer.json#L31

**Comment by marcinant** [comment]
> Oh you guys: bower/bower#1059
> 
> I agree! Why would anybody possibly want to document why they have added a package to a project. Completely useless suggestion. A format that doesn't support comments is CLEARLY the right choice for something as trivial as a dependency configuration.

Composer can contain scripts on 'post-update-cmd' etc. these could require some comment

**Comment by boussou** [comment]
Frankly, I would love seeing yml file as default format for composer.
Json become boring,.. to many { }   

;-)

**Comment by marcinant** [comment]
scripts in yml.... arrrghhhh hell no!

**Comment by boussou** [comment]
It is not script, it is a stupid config file. Am i missing something?

**Comment by marcinant** [comment]
@boussou Yes you are.
Some folks use Composer to more advanced stuff than just "stupid config".
https://getcomposer.org/doc/04-schema.md#scripts
https://getcomposer.org/doc/articles/scripts.md

Do you really want to mess with **yml** here?

**Comment by potherca** [comment]
@marcinant I wouldn't want to mess Yaml anymore than I like messing with JSON, as far as the `script` section is concerned :stuck_out_tongue:

**Comment by gerrywastaken** [comment]
@marcinant My comment contained maximum sarcasm.

**Comment by boussou** [comment]
@marcinant ok !

(Still I find the composer.json file painfull)

**Comment by gerrywastaken** [comment]
What we need is some magical file type that supports, comments, simple config structures and more advanced scripts. Hmmm if only **PHP** supported such a file type.

**Comment by gggeek** [comment]
@gerrywastaken been there, done that.
Using php for config files is fragile and not quite as readable as yaml.
Plus, I'm honestly not sure I'd put any script inline in the config file. All I want to put there is either a cli command or the name of php class or method...

**Comment by boussou** [comment]
yes, mixing script & config is a bad idea. refering to a script by its name look safer.
see what debian do with their .deb packages.

**Comment by gerrywastaken** [comment]
I just want some damn comments. That's all I really care about

**Comment by boussou** [comment]
it is some kind of german thinking there. 
They do not want to allow it because they think you might act very bad.
like using it.
Crazy. ;-)

**Comment by JorisDebonnet** [comment]
I also need this, and several good solutions have already been suggested, so I'll just ...

+1

**Comment by aaron-cardenas** [comment]
+1

**Comment by Saeven** [comment]
+1,  to have my team add packages in an organized manner would be paradise.  A few comments would go a long way.
