### ISSUE TITLE
Add config.http-proxy setting (was: I am behind a proxy , can't use composer)

### ISSUE THREAD

**Issue by akumar** [composer/composer#1991]
Hi,
I have installed the compose and composer is working ,
What i did i downloaded composer.phar and i added a batch file (composer.bat) in my c:\xampp\php , Now i can use composer by composer command . When i run composer on command prompt it shows the options for composer . 

But my problem is when i am trying to install a project the composer returns an exception see below..
------------------------------
C:\xampp\htdocs\akumar\Frameworks\doctrine2-tutorial>composer install
Loading composer repositories with package information

  [Composer\Downloader\TransportException]
  The "https://packagist.org/packages.json" file could not be downloaded: fai
  led to open stream: No connection could be made because the target machine
  actively refused it.

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-c
ustom-installers] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--opt
imize-autoloader]

C:\xampp\htdocs\akumar\Frameworks\doctrine2-tutorial>

-------------------------------------------

I am behind a proxy and i don't have admin privileges ,Please let me know how i can use the composer ?

**Comment by Polzme** [comment]
It would be great so we can use composer in phing exec task properly.

**Comment by 4ir4o** [comment]
@iyus1705 solution works for me. Thanks.

**Comment by lightwaxx** [comment]
Type this in composer cmd
_set http_proxy=http://domain.ext:port_
Have no space before and after =

**Comment by hopik007** [comment]
Is not good using set env variable. Because all communication will be via proxy. It can be problem with other application running on system.
It is very bewildering that Composer don't have any possibility how to call with proxy. 
It mean that Composer is not good for any production env. without this very basic functionality.

**Comment by juliandavidmr** [comment]
Type this in console:
`git config --global --unset http.proxy`

_from [5125608](https://stackoverflow.com/a/10334096/5125608)_

**Comment by gitressa** [comment]
Even after defining both `http_proxy` and `https_proxy`, I couldn't download Composer with PHP behind a proxy, but cURL worked:

Defining `http_proxy` and `https_proxy`:
```
$ export http_proxy="http://proxy.example.org:7149/"
$ export https_proxy="http://proxy.example.org:7149/"
```
Checking
```
$ env | grep proxy
http_proxy=http://proxy.example.org:7149/
https_proxy=http://proxy.example.org:7149/
```
Downloading with PHP doesn't work:
```
$ php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
https://getcomposer.org/installer): failed to open stream: Connection refused in Command line code on line 1

```
Downloading with `cURL` works:
```
$ curl https://getcomposer.org/installer > composer-setup.php
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  257k  100  257k    0     0   938k      0 --:--:-- --:--:-- --:--:--  939k
```

**Comment by kwisatz** [comment]
I keep running into that same problem. `http(s)_proxy` variables are set and exported, and yet composer strictly refuses to use them while other tools like curl, wget, etc all do.

**Comment by Kp5576** [comment]
I romove my proxy from composer but problem is not solve 
the problem is comes out in composer 

https://repo.packagist.org could not be fully loaded (Unable to use a proxy: malformed http_proxy url), package information was loaded from the local cache and may be out of date

  [Composer\Downloader\TransportException]
  Unable to use a proxy: malformed http_proxy url

**Comment by Audran-wol** [comment]
Non of your solutions are working damn!

**Comment by Tamas-hi** [comment]
Is there any progression here? I think it is still a valid feature idea that Composer should support a config file where the proxy can be set (just like npm)
