### ISSUE TITLE
composer: command not found

### ISSUE THREAD

**Issue by msutyak** [composer/composer#2000]
Hello,

I have successfully download composer, and moved it to the directory usr/local/bin using:

sudo mv composer.phar /usr/local/bin/composer 

the output is:  mv: rename composer.phar to /usr/local/bin/composer: Not a directory.

I then try to run composer from the root folder I am using for my project by using: composer install.  

I only receive the error: composer: command not found.  

I do not know what the issue is?  I am using Mac OS X lion version 10.7.5

**Comment by khaledWebdev** [comment]
Also after all maybe it's helpful to open a new console cause the alias has no effect on current one.
