### ISSUE TITLE
bin/ scripts not working across OS

### ISSUE THREAD

**Issue by Tobion** [composer/composer#2003]
I have a windows maschine and a CentOs vagrant box. I need to update vendors on the box because since symfony 2.3 the installed ICU component depends on the available intl extension. So it creates symlinks for the scripts in `bin/`. But they don't work on windows.
So when I for example use the https://github.com/squizlabs/PHP_CodeSniffer as pre commit hook, I cannot commit locally because bin/phpcs does not work.

Before symfony 2.3 it wasn't a problem because it didn't matter whether I update vendors locally or on the box. But now you basically cannot use both environments equally.

So I hope there is a way to make bin/ scripts work across OS.

**Comment by Seldaek** [comment]
See https://getcomposer.org/doc/06-config.md#bin-compat
