### ISSUE TITLE
Composer\Downloader\TransportException HTTP request failed!

### ISSUE THREAD

**Issue by yacreo** [composer/composer#2012]
I'm trying to install some bundles in my symfony2 project but since about 3 weeks I'm getting this error. I've updated my composer(php composer.phar selfupdate). The error is: 

```
[Composer\Downloader\TransportException]
  The "http://packagist.org/p/symfony/proxy-manager-bridge$f7de372e6b43dd757e20984960b0236af56fdadd9e68c926bdf215976d93362d.json" file could not be downloaded: failed to open stream: HTTP request failed!
```

I've tried from 3 different Internet Connections but the same issue.

Any help?????

Thanks !

**Comment by xuyangbao3** [comment]
Checking http connectivity to packagist: FAIL

I have the same problem .  why?

**Comment by Seldaek** [comment]
@xuyangbao3 please open a new issue with more details. This is very old.
