### ISSUE TITLE
require-prod configuration directive

### ISSUE THREAD

**Issue by nibynool** [composer/composer#2016]
I'm currently developing a fairly large project and have a number of modules that I don't want in my development environment, but I do want it in my production environment.

It would be really useful if as well as having "require" and "require-dev" there was also a "require-prod" option.

As it is I have to keep remembering to modify my composer.json prior to installing in my staging environment.

**Comment by quazardous** [comment]
@Seldaek +1 for require-prod

`require-prod` could be very usefull when dealing with optimization/cache dependencies.

ie: Say you nead memcached for your powerfull prod.
But memcached is hard to even install on OSX so developpers with OSX have to mess with the composer.json in order to `composer install`. It's a source of bug when you have a composer.json you cannot easily pull/push ...

**Comment by quazardous** [comment]
maybe it should be a general purpose require-env directive for additionnal dependencies

```json
...
require-env {
    "server1": {
        "ext-memcached": "*",
        "ext-pcntl": "*"
    }
}
...
```

    composer install --require-env server1

**Comment by curry684** [comment]
On your staging environment you could just set the [`COMPOSER` environment variable](https://getcomposer.org/doc/03-cli.md#composer) to `composer-staging.json`.

**Comment by quazardous** [comment]
ok i get it.

but the suggest is not suitable for a real-life-project when you give your project to install to the sysadmin team... they need STOP or GO process.

    COMPOSER=composer-other.json php composer.phar install

it's a good starting point but it lacks #183 because maintain parallel composer.json is not good too...

**Comment by curry684** [comment]
To have different dependencies on different production environments isn't good either  :)

You could of course also have a fake root package like `mycompany/production-deployment` which could then require `mycompany/actuallibrary` and `ext-memcached`. That would keep it pure from Composer's perspective where a package's dependencies are fixed for that package and its version. You'd just be introducing a new package with its own unique dependencies, giving hard errors when devops screw it up.

**Comment by quazardous** [comment]
@curry684 different dependencies are common when dealing with modular software. Devloppers don't need to know all the the optim stuff or if the software is install on mysql or oracle. but fake root is a good point :p

**Comment by curry684** [comment]
I completely agree with you on the point of separation of concerns, but just saying that the logical consequence of that is that `composer.json`, being the developers' domain, shouldn't be bothered with deployment details  :)

The developers put in `composer.json` what they expect, require and support. It's up to the sysop/devop to build deployments from that. Whether he elects to do that via apt packages, installer scripts or fake composer roots is up to him. In this case I'd definitely stick with the fakeroot.
