### ISSUE TITLE
Add ability use env variables in project composer.json

### ISSUE THREAD

**Issue by Koc** [composer/composer#2036]
We have smth like this

``` json
    "scripts": {
        "post-install-cmd": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "php app/console cache:clear",
            "php app/console cache:clear -e prod",
            "php app/console assetic:dump -e prod"
        ]
    },
```

but on production we should use `php54` instead of `php`. It would be nice add support something like `{%ENV:PHP_INTERPRETER%} app/console cache:clear`

**Comment by fgilio** [comment]
+1

**Comment by thiagomorato** [comment]
@Seldaek How can I use this? "Composer's config already supports vars in the form of {$name}" I have searched a lot but I couldn't find any reference of it, if you can point me in the right direction it would be much appreciated.

**Comment by Seldaek** [comment]
See https://github.com/composer/composer/blob/1.1/src/Composer/Config.php#L34-L39 for some examples. We also have env var support as $VAR or %VAR% in https://github.com/composer/composer/blob/1.1/src/Composer/Util/Platform.php#L33 but we only do those for paths.

I'm not so sure if it's really useful though, in 3 years 2-3 people were interested, sounds like unneeded cruft to me.

**Comment by phramz** [comment]
I'd like to see some kind of `{$env:FOO}` feature as well. I'm trying to pass a checksum hash to `autoloader-suffix` to get deterministic build-artifacts, which is kind of impossible. Setting a static suffix wouldn't help much, because i'd like to keep the cache-buster for opcache.

Another way (at least for the 'config' section) would be to have another CLI argument to overwrite the config like `-- config autoloader-suffix=FOO` or something`.

**Comment by Seldaek** [comment]
@phramz sounds like you can just do `composer config autoloader-suffix $FOO` before your install?

**Comment by phramz** [comment]
hmm, yes right :) ... that should do it as well, but would modify my `composer.json` and leave my git-repo dirty on the build host. So an env-var in the `composer.json` or an arg on the CLI would be more suitable ... at least in my case. But thx for the hint, maybe I could just automatically `git reset` the repo afterwards.

**Comment by Seldaek** [comment]
Rethinking this further, as it was proposed like 3 years ago and is indeed adding a bunch of complexity (as per discussion and #5837) and possible disasters when third party composer.json are loaded as dependencies, it doesn't seem worth doing. Closing.

**Comment by lchachurski** [comment]
I just came across similar issue,  for anyone trying figure this out:

> A script, in Composer's terms, can either be a PHP callback (defined as a static method) or any command-line executable command. Scripts are useful for executing a package's custom code or package-specific commands during the Composer execution process.
[source](https://getcomposer.org/doc/articles/scripts.md)

Therefore this will work `$PHP_INTERPRETER app/console cache:clear`

For lazy people who use .env file (eg. laravel)

`export $(cat .env | xargs) && $PHP_INTERPRETER app/console cache:clear`

It works well if you want to have one common script to install all dependencies like yarn/npm compiling routes assets and others.

```
"scripts": {
  "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize",
            "yarn install",
            "php artisan laroute:generate",
            "export $(cat .env | xargs) && npm run $DEFAULT_SCRIPT_NAME"
        ],
}
```
