### ISSUE TITLE
more commands to modify composer.json from the CLI

### ISSUE THREAD

**Issue by lsmith77** [composer/composer#2038]
When I run the tests for https://github.com/jackalope/jackalope/blob/master/composer.json I would prefer if I could make either of the following adjustments via the CLI:
 * remove the require on "jackalope/jackalope-transport"
 * add a provide on "jackalope/jackalope-transport"

For the first I envision we could add a flag to the require command to remove rather than add. For provide we could add an analogous command as we have for require. We might also want to have something like that for suggest just for good measure?

**Comment by dantleech** [comment]
As #2479 is merged can this be closed now?

**Comment by Seldaek** [comment]
Yup I don't think provide/replace/conflict/suggest are hardly common enough to have their own commands to set/unset, but require/remove does the job.
