### ISSUE TITLE
Project directory /path is not empty installing zend framework 2  

### ISSUE THREAD

**Issue by greatcrypter** [composer/composer#2044]

**Comment by AngeIII** [comment]
+1 for force..

**Comment by MateuszKowalewski** [comment]
@stof How git handles things isn't an excuse for not having a demand feature in composer.

A possible solution would be to do all the things needed to init a directory in a temp dir first and only on success move the temp dir to the right place. On error you can save delete the temp dir. The temp dir is actually empty right after creation, the way git likes it.

Step by step it would be:
1. create “build-dir”
2. git clone repo into build-dir, or do whatever is needed to get the source (e.g. ftp and zip extract in build-dir)
3. copy contents of “target-dir” (the directory the user wants actually to install to) into build-dir, (that's the thing all the people do by hand after composer install…)
4. if there haven't been any errors, you can save delete the target-dir and move the build-dir to its place.
5. if there have been errors (maybe target-dir content would overwrite something in build dir, or that like) the build dir can be save deleted, target-dir content stays untouched.

That would also solve the problems mentioned in the discussion about issues #2278

Could something like this be considered for future development? Package managers like apt works alike to avoid leaving the system in an undefined state. Extracting new packages to temp dirs, and switching the dirs, after everything is configured in the temp dir. I think it's a proven concept.

So please make it possible to install into non empty dirs!

**Comment by michaelprflores** [comment]
+1
