### ISSUE TITLE
`status` should check for unpushed changes

### ISSUE THREAD

**Issue by asgrim** [composer/composer#2046]
We have had a couple of (thankfully minor) cases where we have run `php composer.phar up` and our components we had changed, committed, but not pushed to our Git server.

I know when you do `php composer.phar status`, it will tell you if you have uncommitted changes, but is there a way it can tell us if we are ahead of master branch (i.e. have not pushed changes / have not merged into origin) ?

This may help prevent cases where we change our component, commit but haven't yet pushed changes to our origin repo.

**Comment by Seldaek** [comment]
unpushed changes are detected when doing an update of the given package now, which IMO is good enough to prevent missing data accidentally, closing here.
