### ISSUE TITLE
Class Twig_SimpleTest not in autoload

### ISSUE THREAD

**Issue by ghost** [composer/composer#2051]
I'm not deep dive into the issue to find if is Twig or Composer related.
Anyway, clean install of Twig and Composer, then

```
php composer.phar dump-autoload -o
```

and looking in the `autoload_classmap.php` there isn't

```
`Twig_SimpleTest' => $vendorDir . '/Twig/lib/Twig/SimpleTest.php`
```

This generate a Fatal Error thrown by:
    PHP Fatal error:  Class 'Twig_SimpleTest' not found in /vendor/twig/twig/lib/Twig/Extension/Core.php on line 206

**Comment by rayward** [comment]
@Seldaek This is an issue for me as I want to use the `classmap-authoritative` setting to improve performance.

I don't think composer should be making decisions about what to include in the classmap if the path is explicitly specified in the `autoload` configuration.

If users want test classes to be/not be autoloadable, then the `autoload-dev` option is there.
