### ISSUE TITLE
Weird resolution when the same package appears in require and require-dev

### ISSUE THREAD

**Issue by stof** [composer/composer#2056]
Behat Symfony2Extension has ``symfony/symfony: ~2.1`` as a dev requirement. On Travis, it requires it with a more strict requirement (to test against different versions).
This was working properly 24 days ago (for the previous Travis build) but it is failing today with a weird output: it installed 2.3.1 and then tried to find 2.2.*.

See https://travis-ci.org/Behat/Symfony2Extension/jobs/8623568 for the output.

The latest composer is used as it runs ``self-update`` at the beginning of the build.

**Comment by Seldaek** [comment]
Closing as it's very old.
