### ISSUE TITLE
Allow set of multiple URLs for file dist type

### ISSUE THREAD

**Issue by Rarst** [composer/composer#2057]
Currently `dist` in package can handle archives of multiple files and individual files (`"type":"file"`), but not case of _several_ individual files. I see no way to achieve it, other than create package for every file separately. It might make sense if this was supported.

Example use case - third party JS library project on GitHub can total several megabytes of sources, test, documentation and stuff.

While what I actually want from it are final results of the build - two (unminified and minified for example, but might be more) script files.

So rather than create package for every file it would be nice to create one package with list of URLs for all of them.

Maybe something along:
```json
"dist" : {
"url" : [
    "https://raw.github.com/vendor/project/master/dist/script-version.js",
    "https://raw.github.com/vendor/project/master/dist/script-version.min.js"
    ],
"type": "file"
}
```

**Comment by gabrielzerbib** [comment]
Probably just as many other users of Composer and static assets, I have solved this situation with my own code: https://github.com/gabrielzerbib/asseteer
(check the **More** section at bottom of README)
It provides a perfect solution for me, but alas isn't intuitive enough, it would be much better if it was part of the standard `composer.json` format.

Comments are welcome!

**Comment by Seldaek** [comment]
Closing as there are plugins and others doing it and it's overall not something I see as likely to be supported.
