### ISSUE TITLE
Run single commands or create custom command-events for  

### ISSUE THREAD

**Issue by KeKs0r** [composer/composer#2059]
I am currently trying to figure out a good deployment on Pagodabox and ran into some limitations. Most of my composer post-install-cmds dont need to be run after my deployment, because I run them manually. But there are commands that can only be run by composer but not as an inividual command. (e.g. "Mopa\\Bundle\\BootstrapBundle\\Composer\\ScriptHandler::postInstallSymlinkTwitterBootstrap" from https://github.com/phiamo/MopaBootstrapBundle/blob/master/Composer/ScriptHandler.php)

In order to achieve it it should either be possible to run a single individual command with composer --run-scripts:

```
composer.phar --run-scripts Mopa\\Bundle\\BootstrapBundle\\Composer\\ScriptHandler::postInstallSymlinkTwitterBootstrap
```

Another Solution could be to define custom script-groups in composer.json and allow them to be run by the --run-scripts command:

```json
"scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Mopa\\Bundle\\BootstrapBundle\\Composer\\ScriptHandler::postInstallSymlinkTwitterBootstrap"
        ],
        "custom-deploy-cmd": [
            "Mopa\\Bundle\\BootstrapBundle\\Composer\\ScriptHandler::postInstallSymlinkTwitterBootstrap"
        ]
    }
```

And this could then be run by
``` 
php composer.phar --run-scripts custom-deploy-cmd
```

**Comment by Seldaek** [comment]
There's a run-script command now
