### ISSUE TITLE
Composer should allow to include or exclude paths from package.

### ISSUE THREAD

**Issue by marcinant** [composer/composer#2064]
Example:

I've got git repository called 'testpackage' with maven like structure:

/doc
/src/main/php
/src/main/resources
/src/test
etc.

Than I can use this repo as composer package and I get:

testvendor/testpackage/src/main/php/Somespace/Someclass.php

Then I need to define psr-0 with path prefix: /src/main/php to make autoload work properly.

I can exclude doc's and test directories but I cannot avoid this irrevelant subfolders.

Composer should allow to define package directories just like Maven defines assemblies with support for include/exclude/root path.

In this way we could avoid prefixing dirs in autoloader and create simple structures like:
testvendor/testpackage/Somespace/Someclass.php

**Comment by jfarrell** [comment]
+1 to git filter-branch as an option. Apache Thrift hits this use case with a 30mb download for the full repo and people using the php client library only need 500K of that, any possibility of making this an option
