### ISSUE TITLE
Disable suggest output

### ISSUE THREAD

**Issue by henrikbjorn** [composer/composer#2066]
When doing a deploy and installing with composer there could be **a lot** of suggest output, especially for something like Symfony Components or Monolog, having a parameter to disable this would make it less verbose but still allow developers to see the suggested packages when installed for development.

It could also be skipped when doing a --no-dev install.

**Comment by nifr** [comment]
Any updates here?

**Comment by staabm** [comment]
the related PR was closed with the following summary[1]:

>Closing this one as composer only shows suggested packages if we are --dev.
>https://github.com/composer/composer/blob/master/src/Composer/Installer.php#L244


[1] https://github.com/composer/composer/pull/2068#issuecomment-133886703

**Comment by Seldaek** [comment]
Yeah a `composer install --no-dev` (which you should do in deploys) skips the suggests, IMO that's good enough and adding the cruft of an extra flag for this isn't really needed.

**Comment by jcrombez** [comment]
I need the dev requirements during the CI test phase (i bring phpunit this way) and i'd like to avoid almost 100 suggestion lines in my logs, if i understand this issue correctly, there is no way to achieve that ?

**Comment by Seldaek** [comment]
That is correct. You could use `composer install --quiet` I guess to suppress output entirely. For now that even suppresses exceptions I think but that's something I am looking to fix soon.

**Comment by jcrombez** [comment]
Ok, thank you Seldaek.

**Comment by chandan07cse** [comment]
Have you fixed it yet Seldaek ?

**Comment by Seldaek** [comment]
Yeah that's been fixed for a while now :)

**Comment by lifeofguenter** [comment]
I am in the similar situation with @jcrombez, e.g. within our CI we do need to install dev-packages to ease certain tasks (like running tests), but we remove them after running tests by running `composer install --no-dev`.

`--quiet` would be too quiet as we do like to check quickly what package versions were installed, but we would like to remove the suggestions to minimise the noise as much as possible.

Maybe something like `--no-suggestions` ?

**Comment by brunocascio** [comment]
`--no-suggest` is the option.

**Comment by pehbehbeh** [comment]
Is there a config setting to disable suggestions via `composer.json`? I would like to disable suggestions by default when installing new packages for example.

**Comment by rgpublic** [comment]
Hmmm. When I run:
`
composer create-project drupal/drupal . --no-interaction --ansi --no-suggest
`
I get:
`
The "--no-suggest" option does not exist. 
`
When I remove that option and run the command I get lots of trash like:
`
symfony/http-kernel suggests installing symfony/config ()
symfony/http-kernel suggests installing symfony/finder ()
symfony/http-kernel suggests installing symfony/var-dumper ()
easyrdf/easyrdf suggests installing ml/json-ld (~1.0)
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/class-loader suggests installing symfony/polyfill-apcu (For using ApcClassLoader on HHVM)
`

**Comment by bm13kk** [comment]
Why this is closed?
Option `--no-suggest` exists, but i still have suggestions with it.

**Comment by rgpublic** [comment]
Hmm. I see this is closed as WontFix, but IMHO this decision should be reevaluated. I'm doing a lot of automation with Composer (Install scripts etc.). Many times I need to enable dev packages but I dont want to have all the suggestions. It's helpful for automated bash scripts when there is *some* output, because Composer can be quite slow sometimes so the user knows that sth.'s going on. But of course it is quite ugly when there are huge blocks of  useless "suggests" scrolling by. And I don't see quite the connection between dev packages and suggests. I think, this feature requests makes total sense and should be independent of any --dev switch.
