### ISSUE TITLE
Composer install: Cannot allocate memory

### ISSUE THREAD

**Issue by dietervds** [composer/composer#2067]
Hi guys,

When performing 'composer install' on a Laravel 4 project I receive a memory exhaustion error. To be fair, this happens only in constrained environments:
- Vagrant virtualbox with 1gig memory allocated
- Amazon EC2 micro instance

The error itself:
http://cl.ly/image/3w433g1h2L1F

When, for example, I allocate 2 gigs of memory to the Vagrant box, it works fine.
But what I wanted to know: is there a way around it using too much memory for a micro instance to handle? It would be a shame to not be able to use them.

(Right now I use a medium one to do the installation, and then launch an image of that one into micro, but it's a bit of a workaround)

Edit: as memory serves, I saw this issue before, but it said back then it was resolved so it could work on a micro instance again. Yet in my case that doesn't seem to be the case?

**Comment by gautamkeshri** [comment]
my composer.lock file dose not have --dev details. so what is solution in such case ?

**Comment by pborreli** [comment]
@gautamkeshri you could try https://composer.borreli.com/
