### ISSUE TITLE
ClassLoader with additional predictor characters.

### ISSUE THREAD

**Issue by donquixote** [composer/composer#2112]
Composer's ClassLoader is smart in that it groups registered prefixes by their first character, to avoid too long loops.

Unfortunately, it can happen that most prefixes have the same first character. E.g. "D" for "Drupal", if a bunch of Drupal module namespaces is registered.

[Benchmarks](https://github.com/donquixote/autoload-bench) show that this situation can be improved a lot, by having one or more additional predictor characters at strategic positions.
https://github.com/donquixote/autoload-bench/blob/demo/src/Seld/AutoloadBench/Loader/ComposerSmarter.php

E.g. for <code>Drupal\\*</code>, a predictor index at 7 can do the trick.

Every additional predictor index comes at a cost, so there is a trade-off to consider. Having more than one additional index is only worth it if there is really a lot of registered namespaces. But one additional index can easily pay off.

Proposal:
When generating the autoloader, determine a strategic predictor index based on the prefix map, and estimate whether this would bring a benefit. If yes, generate the loader with the additional predictor logic.

**Comment by Seldaek** [comment]
Closing as --optimize-autoloader is now the best thing we can achieve I think.
