### ISSUE TITLE
Passing arguments to scripts

### ISSUE THREAD

**Issue by boldtrn** [composer/composer#2135]
I wonder if it's possible to pass arguments to scripts that are called from the `composer.json`?

E.G.

```
"scripts" : {
        "post-update-cmd" : [
            "Mopa\\Bundle\\BootstrapBundle\\Composer\\ScriptHandler::postInstallSymlinkTwitterBootstrap"
        ]
}
```

Now I want to pass the argument `--no-symlink` to the script. But it doesn't work by adding `--no-symlink`.

**Comment by simonbergmann** [comment]
@boldtrn if you want to pass the argument --no-symlink to a script you can do this:
composer post-update-cmd -- --no-symlink
more info here: https://getcomposer.org/doc/articles/scripts.md

**Comment by FGM** [comment]
Creative use of xargs in the script definition might help, by echoing the flags you want and having the script command be "xargs original_command"

**Comment by pmgouveia** [comment]
@FGM can you elaborate? thanks! 👍

**Comment by olivertappin** [comment]
This still seems to be an issue in the latest version of Composer (v1.8.5)
