### ISSUE TITLE
file could not be downloaded: failed to open stream: Cannot connect to HTTPS server through proxy

### ISSUE THREAD

**Issue by stefanmerk** [composer/composer#2169]
Hey there,

I am trying to run composer on a company server which is behind a firewall.
I already set `HTTP_PROXY` and `HTTPS_PROXY` (+ both in lowercase), it doesn't seem to help.
Also the `REQUESTFULLURI` flags are set to false! (both HTTP and HTTPS)
(I can however connect to HTTPS and HTTP with CURL)

I already googled everything that could help me, unfortunately with no success for my particular problem.

Also the Server runs OpenSSL with `v1.0.0` from March 2012

I also ran composer diag:

```
Checking platform settings: FAIL

Your PHP (5.3.3) is quite old, upgrading to PHP 5.3.4 or higher is recommended.
Composer works with 5.3.2+ for most people, but there might be edge case issues.
Checking http connectivity: FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: Cannot connect to HTTPS server through proxy
Checking HTTP proxy: FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: Cannot connect to HTTPS server through proxy
Checking HTTP proxy support for request_fulluri: FAIL
Unable to assert the situation, maybe packagist.org is down (The "http://packagist.org/packages.json" file could not be downloaded (HTTP/1.0 400 Bad Request))
Checking HTTPS proxy support for request_fulluri: FAIL
Unable to assert the situation, maybe github is down (The "https://api.github.com/repos/Seldaek/jsonlint/zipball/1.0.0" file could not be downloaded: failed to open stream: Cannot connect to HTTPS server through proxy)
Checking composer.json: OK
Checking disk free space: OK
Checking composer version:


  [Composer\Downloader\TransportException]
  The "https://getcomposer.org/version" file could not be downloaded: failed to open stream: Cannot connect to HTTPS server through proxy



diagnose
```

**Comment by laddhoffman** [comment]
On my system it looks like it's trying to use IPv6 and my firewall was blocking that.

**Comment by spotatoes** [comment]
I know this issue is closed, but there are no definitive recommendations and I am also having this issue when trying to install. I am 99% sure it's not a DNS or firewall issue as I've made no significant changes to either from a clean install of Ubuntu 16.04.

```bash
All settings correct for using Composer
Downloading...
The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: Connection timed out
Retrying...
The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: Connection timed out
Retrying...
The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: Connection timed out
The download failed repeatedly, aborting.
```

Although `All settings correct for using Composer`, when I run `composer diag` I get the following error before the same `/versions` URL issue as above:

```bash
Checking http connectivity to packagist: WARNING
[Composer\Downloader\TransportException] The "http://packagist.org/packages.json" file could not be downloaded: failed to open stream: Connection timed out
```

Is there anything I can look into?

**Comment by asanoturna** [comment]
i have same problem that @spotatoes

**Comment by vedro-compota** [comment]
similar problem on ubuntu 16.04 -- suddenly after nornal working (may be github block downloading)?

```
Loading composer repositories with package information

                                                                               
  [Composer\Downloader\TransportException]                                     
  The "https://api.github.com/repos/it-for-free/FileUploader" file could not   
  be downloaded: failed to open stream: Connection timed out                   
                                                                               

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

```

**Comment by gbryant200** [comment]
I'm having this same issue - has anyone found a fix?  I'm leaning toward an openSSL issue with PHP but don't know how to fix it.  I can file_get_contents and curl successfully on my local network.  I have my HTTP and HTTPS proxies set.

from the command line to test:
curl https://packagist.org/packages.json  ----> works
php -r "echo file_get_contents('https://packagist.org/packages.json');" ----------> fails to open stream
php -r "echo curl_exec(curl_init('https://packagist.org/packages.json'));" ---------> works

OpenSSL 1.0.2g 1 Mar 2016
PHP 7.0.22-0ubuntu0.16.04.1 (cli)

HELP!
&
THANKS!

**Comment by vedro-compota** [comment]
@gbryant200 in my case all started work after some time by itself.

Your examples works for me too, e.g.:
```
php -r "echo file_get_contents('https://packagist.org/packages.json');"
```

give:
```
{"packages":[],"notify":"\/downloads\/%package%","notify-batch":"\/downloads\/","providers-url":"\/p\/%package%$%hash%.json","search":"\/search.json?q=%query%&type=%type%","provider-includes":{"p\/provider-2013$%hash%.json":{"sha256":"056ceb64027ee92bd10ba9c39d9cf34377c693047708dc6dad6f5c20f1efd63d"},"p\/provider-2014$%hash%.json":{"sha256":"b7c785fb309ae1a62fe2a4683b0567608b658978ef1423d70b70169ab00e4217"},"p\/provider-2015$%hash%.json":{"sha256":"265500a9d9b53aa41bbc2fa8a96d0bf9363b65421c7841514e8567577438bbc8"},"p\/provider-2016$%hash%.json":{"sha256":"ed9dcc23638cd306b496c12637d1498ff71d5c05def146048c57b3b376f97749"},"p\/provider-2017$%hash%.json":{"sha256":"8a86eaff6c826b8229d20d607d548781879e988a80a656b8c643cc721ba1ec56"},"p\/provider-2017-04$%hash%.json":{"sha256":"c86648e90aa74c610ec54b5ea294565afba1966dd7baebae3f438dcf17d3a719"},"p\/provider-2017-07$%hash%.json":{"sha256":"03550112a6a614bc28fe977a7ec947138d42246e0d1c9f8b316a01e67e536d76"},"p\/provider-2017-10$%hash%.json":{"sha256":"b33ccb6ea356a746c217f60371a330e2794c5b73b8145b415210c5e518109370"},"p\/provider-archived$%hash%.json":{"sha256":"8b133134b93da87586d9fb3504cf769ed67211cead8fe9cf451545f3a75447b1"},"p\/provider-latest$%hash%.json":{"sha256":"85ecf6b30739e2628f7e18899298eb1fd03973df1734299d603242c921b6dcf5"}}}
```

**Comment by site-me** [comment]
OK, in my case there was a problem with IPv6, solved it by disabling it in `/etc/sysctl.conf`
by adding in the bottom
```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```
and running `sudo sysctl -p` to reload config 

[source](https://medium.com/@lifez/solved-apt-get-update-stuck-connecting-to-security-ubuntu-com-dbe41eeb5a0b)

**Comment by eduan** [comment]
> I'm having this same issue - has anyone found a fix? I'm leaning toward an openSSL issue with PHP but don't know how to fix it. I can file_get_contents and curl successfully on my local network. I have my HTTP and HTTPS proxies set.
> 
> from the command line to test:
> curl https://packagist.org/packages.json ----> works
> php -r "echo file_get_contents('https://packagist.org/packages.json');" ----------> fails to open stream
> php -r "echo curl_exec(curl_init('https://packagist.org/packages.json'));" ---------> works
> 
> OpenSSL 1.0.2g 1 Mar 2016
> PHP 7.0.22-0ubuntu0.16.04.1 (cli)
> 
> HELP!
> &
> THANKS!

did you solve that? I'm facing the same issue.

**Comment by gbryant200** [comment]
I had proxy authentication issues.  Curl has its own proxy settings; Apt has its own proxy settings and they don't all parse the strings the same way - very frustrating.

`export http_proxy=http://domain\\username:password@proxy.address:port"` typically works.  Look up proxy settings for curl; I can't recall but I think they were different.

same for https_proxy; however some require the \ to be escaped, some utilities didn't.  I tried "" the string, etc.  This was back on Ubuntu 16.04.

**Comment by drug200221** [comment]
The problem appeared after replacing the switch (apparently some connection settings were lost)
I tried to set it up but in the end
Connected from the modem and everything worked ...
But another problem appeared - the docker loads packages for a long time at such a speed
