### ISSUE TITLE
Read a package from a relative local path.

### ISSUE THREAD

**Issue by Vittel** [composer/composer#2171]
**Add a repository type: dir/file/local that accepts a local relative path as source**

**Let me point out the requirement context a little bit:**
We have a working deployment system up and running, deploying needed code to the exact right versions and positions in file system.
Now we try to enable composer on certain parts of the code that we identified as packages and to resolve further dependencies and autoload the contained classes.
Its not an option for us to break our deployment system, but it shouldn't be necessary when we could just read the prepared package from a local path (where it was deployed).
This is currently not possible. All existing repository configurations expect the repo to be remote or be accessible with a remote URL.
This is only the first step of our composer migration, and we are already stumbling.

**Comment by jreinke** [comment]
Just gave a solution for this on another related issue: https://github.com/composer/composer/issues/1299#issuecomment-88861371

**Comment by Vittel** [comment]
@jreinke even though your solution might work for most people, symlinking files instead of just reading them from their original location is not a solution for this problem.

**Comment by slbmeh** [comment]
I work with a handful of 100+ dependency projects so I'll give my two cents.

I'm not quite sure how well a relative path repository declaration would work in the context of a project. Suppose someone checks out your project and doesn't have the same path structure. It generally works better for large teams and CI to have your repositories declared elsewhere. The file protocol works in some circumstances, but if you're working with a VCS repo you need to commit your work for it to be updated anyhow, why not just push it to a central location on some experimental branch.

With development and testing uncommitted changes we use an alternative composer file that excludes the codependencies from the require section and places their relative paths in `autoload-dev`. This also needs to have the child dependencies to be placed as a direct dependency of the root package.

@laurentj `Unfortunately, It seems there is no way to indicate to Composer: "include in my project this local package, which is in this directory (without copying it somewhere)".`: the approach in the second paragraph does exactly that.

**Comment by Vittel** [comment]
The main advantage here is not the "composition" part (since everything is in the place to be), 
but letting composer generate one autoload-file for all projects that are required, without duplicating or symlinking any of the code into each other project.

just like: forget about the packages, i managed that. but please take care of the autoloading for me

**Comment by timglabisch** [comment]
i am playing with a local repository type.
companies like google and facebook are working this way, so it should scale =)

https://github.com/timglabisch/composer_local_downloader_demo

**Comment by far-blue** [comment]
Something like this along with the ability to merge in a 'composer.local.json' config would be a huge boon to me and my department. We develop a number of applications and the packages they share simultaneously and composer simply doesn't support such a basic workflow. At the moment we have to resort to manual symlinks. We mainly use SVN so local git repos aren't really an option and even when we can do this, having to commit every change in a package and then compose update really isn't a great workflow.

**Comment by webmozart** [comment]
Putting myself on the list of "people who needed this" :) I'd love to point a repository to a relative path.

**Comment by claudio-silva** [comment]
Is this a solution for this problem?
[Composer's repository 'path' type](https://getcomposer.org/doc/05-repositories.md#path)

**Comment by jurajseffer** [comment]
For those of you who need this because you want to have projects and libraries in a monolithic repository, you can use Conductor, it seamlessly hooks into composer processes
https://github.com/mybuilder/conductor

**Comment by staabm** [comment]
@Seldaek as noted above, I guess this one can be closed.

**Comment by TomasVotruba** [comment]
@claudio-silva It is! New feature in composer (in that time of your comment).

**Comment by stephan-v** [comment]
@TomasVotruba I have tried using your solution but I still get:

> Cloning 7a1b88ba32 from cache

Shouldn't this actually be symlinking it like it says here:

https://getcomposer.org/doc/05-repositories.md#path

Even trying to force it, there seems to be no change:

    "options": {
        "symlink": false
    }

**Comment by TomasVotruba** [comment]
@stephan-v I'm not sure how "symlink" options works. I never used it and everything works fine for me.

Might be OS. I use Linux Ubuntu 16.10.

What about you?

**Comment by stephan-v** [comment]
@TomasVotruba  nevermind I had to throw away my `composer.lock` file for this to work. Thanks for replying anyways 👍

**Comment by TomasVotruba** [comment]
@stephan-v Good to know. I will share this information next time I will see similar issue.

Thanks and have fun :)

**Comment by brianreese** [comment]
Works:
