### ISSUE TITLE
"API" for install path

### ISSUE THREAD

**Issue by gossi** [composer/composer#2174]
Disclaimer: This issue is not intended for an end-users. Instead it focuses on tooling support for composer (such as the [Composer-Eclipse-Plugin](https://github.com/pulse00/Composer-Eclipse-Plugin))

When packages installed, they are typically installed in the vendor directory. Though especially custom-installers change the path. One of the main features of the Eclipse-Composer-Plugin is to automatically manage the build-path, so that code-assist works seamlessly without any further user-interaction. For now, packages installed with a custom install path can't be automatically managed.

For these cases an install path "API" (maybe be another property in one of the json-files) would be handy and welcome to provide tooling support.

Thanks
gossi

**Comment by Seldaek** [comment]
Is this still relevant? I am thinking if we got by without for so long it might be unnecessary complexity.

**Comment by gossi** [comment]
It still is, can't implement until this thing is done.

**Comment by Seldaek** [comment]
Have you looked at @hason's PR and perhaps tried it?

**Comment by gossi** [comment]
Actually, I only have noticed his PR... See my question there.

**Comment by Seldaek** [comment]
In composer v2, `install-path` will be present on every package entry in installed.json

**Comment by Dbhardwaj99** [comment]
Hey, I can contribute to this... Can someone guide me?

**Comment by Seldaek** [comment]
This has been done, it's now available in installed.json and through the InstalledVersions class at runtime

**Comment by t-boye** [comment]
I want to Contribute to this... can someone please guide me through the process

**Comment by Seldaek** [comment]
@t-boye this is available at https://getcomposer.org/doc/07-runtime.md#knowing-the-path-in-which-a-package-is-installed
