### ISSUE TITLE
GitDownloader fails on composer.json update, when there is packages added as git repositories

### ISSUE THREAD

**Issue by shivas** [composer/composer#2202]
```
[exec] [0m[31m*** [err :: internal.xxx.com] [RuntimeException]
     [exec] [0m[31m*** [err :: internal.xxx.com] Failed to execute git remote set-url composer 'ssh://xxx@xxx.xxx.com/home/repositories/xxx.git' && git fetch composer && git fetch --tags composer
     [exec] [0m[31m*** [err :: internal.xxx.com] 
     [exec] [0m[31m*** [err :: internal.xxx.com] Error reading response length from authentication socket.
     [exec] [0m[31m*** [err :: internal.xxx.com] Permission denied, please try again.
     [exec] [0m[31m*** [err :: internal.xxx.com] Permission denied, please try again.
     [exec] [0m[31m*** [err :: internal.xxx.com] Permission denied (publickey,password).
     [exec] [0m[31m*** [err :: internal.xxx.com] fatal: The remote end hung up unexpectedly
```

Looking at code i see only one option that there is no composer remote setup yet, and he trying to set url for that...?

its in composer.phar/src/Composer/Downloader/GitDownloader.php:74

**Comment by frederikbosch** [comment]
@jkobus @shivas Could you clone the code in this PR (https://github.com/composer/composer/pull/3608) and see if the bug is still there? I have investigated quite some time now in GitDownloader and helper classes. If the problem still occurs, I might be able to help fixing the problem.

**Comment by EagleEyeJohn** [comment]
i'm getting this issue.  my token got revoked, after months of use. using 

```composer config -g github-oauth.github.com myoathtoken```

'worked', but when running ```composer update``` again, it still tried to use the old token and fails.  As I've provided a token, why doesn't composer prompt me to update it if it's not working?   And as it doesn't, where is the config file stored on Windows so I can change the token manually?

**Comment by frederikbosch** [comment]
What happends if you remove your vendor folder and then composer update again?

**Comment by EagleEyeJohn** [comment]
Now you tell me!...   I've just returned to post that that is indeed the solution to the problem.  There must be a way for Composer to deal with this automatically?  I've now got to delete vendor directories on 20+ projects.

**Comment by frederikbosch** [comment]
I already submitted a pull request for this issue a while ago. It has not been merged yet. From what I understand, there are other problems that need more attention at this moment.

**Comment by frederikbosch** [comment]
@EagleEyeJohn Could you actually confirm that PR  #3608 fixes your problem? The steps to test it would be clone https://github.com/frederikbosch/composer, run composer install for the composer package, and then try to redo the steps of your problem with composer binary from my PR (bin/composer).

**Comment by cnizzdotcom** [comment]
This happened when I changed the branch I am requiring. To get past this error I deleted the project in the vendor directory and ran composer update.

**Comment by frederikbosch** [comment]
@cnizzdotcom If this happends again, I am interested if #3608 solves the problem. Could you try with the same instructions I gave to @EagleEyeJohn?

**Comment by Seldaek** [comment]
Closing as it doesn't seem extremely relevant anymore.

**Comment by ShayanAliProgrammar** [comment]
Hey I was getting this error:
```bash
Failed to execute git show-ref --head -d

  fatal: detected dubious ownership in repository at 'C:/Users/NTEch/AppData/Roaming/Composer/vendo
  r/doctrine/inflector'
  'C:/Users/NTEch/AppData/Roaming/Composer/vendor/doctrine/inflector' is owned by:
        'S-1-5-32-544'                                                                                
  but the current user is:
        'S-1-5-21-3269338778-2856369246-3259115991-1002'                                              
  To add an exception for this directory, call:

        git config --global --add safe.directory C:/Users/NTEch/AppData/Roaming/Composer/vendor/doctrine
  /inflector
```
I fixed that error using: `git config --global --add safe.directory C:/Users/NTEch/AppData/Roaming/Composer/vendor/doctrine/inflector`
