### ISSUE TITLE
Composer\Downloader\TransportException

### ISSUE THREAD

**Issue by tracymazelin** [composer/composer#2214]
Whenever I run php composer.phar install I get an "Composer\Downloader\TransportException The "http://packagist.org....json" file could not be downloaded.

It doesn't matter what dependencies I have in composer.json, it still throws this error every time.  I'm a new user and trying to get up and running with composer.  I have the latest version.

**Comment by maiorano84** [comment]
Can confirm that FortiClient was causing the same problem for one of our other developers. Interestingly, I can download everything without issue on my own machine with FortiClient running, but our other developer can't. Not sure what the exact root cause is.
