### ISSUE TITLE
composer.lock file environment dependant

### ISSUE THREAD

**Issue by arnaugm** [composer/composer#2226]
Is it possible to use different lock files depending on the environment where I'm installing the application?
My deployment process runs "composer install --no-dev" but it doesn't take effect if the lock file, generated in devel, says that the devel related packages have to be installed. I end up with uneeded devel packages in production.

If that's not possible, which would be the correct approach?

**Comment by gggeek** [comment]
Sorry if this is not the good place to discuss this - but I seem to find little info on Google about using composer in a context where different packages/package-versions get deployed/tested to different environments.

Is that a scenario which is encouraged/supported/prevented by composer? Is it better to look elsewhere for doing the configuration mgmt in that case?

**Comment by arnaugm** [comment]
Having different packages/package-versions make the project different, at least potentially, as it can behave differently due to the difference in the third party code. In this case I would play with different git branches (if you use git) and every branch can have its own composer file.

**Comment by gggeek** [comment]
@arnaugm thanks for chiming in.
In fact I found a similar issue here: https://github.com/composer/composer/issues/3293
As far as I see, there are at least 3 possibilities:
- keep different composer.json files next to each other, and use and env var to pick the one you use
- use different git branches
- use some CI script which builds the final composer.lock at runtime by calling 'composer require xxx/v1.2.3)
It remains to be seen which one will make the team more productive and reduce deployment snafus...
