### ISSUE TITLE
SSL in Windows 8

### ISSUE THREAD

**Issue by iboxgithub** [composer/composer#2233]
Hi,

I am not able to download packages with Composer from my system (Win 8). So just in case I specify that I uncommented the openssl lib in the Apache and PHP directory from Wamp. Then I set up a particular ssl conf to remove the problem from the cache 'SSLCache'. So my server is running good, if I want to access localhost through https it works so in this case I guess I didn't write the good code for my virtual host, and maybe I don't get it because I spend too much time on my computer but anyway I need help =)
So here's the code from my custom ssl file : 

```
Listen 443

SSLCipherSuite HIGH:MEDIUM:!aNULL:!MD5
SSLPassPhraseDialog  builtin
SSLSessionCache        "shmcb:c:/wamp/ssl_scache(512000)"
SSLSessionCacheTimeout  300

<VirtualHost *:443> 
    ServerAdmin some@email.com 
    DocumentRoot "C:/wamp/www/Symfony" 
    ServerName 127.0.0.1:443 
    ServerAlias domain.com:443 
    ErrorLog "logs/anyFile-error.log" 
    CustomLog "logs/anyFile-access.log" common 
    SSLEngine on
    SSLCertificateFile "C:/wamp/bin/apache/Apache2.4.4/conf/server.cert"
    SSLCertificateKeyFile "C:/wamp/bin/apache/Apache2.4.4/conf/server.key" 
</VirtualHost>
```

Than you for your help!

**Comment by AndyDiazValdiviezo** [comment]
@yanrivera thanks! xD i had **""**c:\Servidor\php\ext" instead of "c:\Servidor\php\ext"...
