### ISSUE TITLE
Composer Offline Mode (or equivalent)

### ISSUE THREAD

**Issue by ghost** [composer/composer#2244]
Every now and then i keep hitting gitHub's api limit when doing 
`Composer Install`

is it possible to have a either an offline mode, similar to bower or a fall back, ie if there is an error/no connection/api limit reached then utilise cache?

this would also help out in low connectivity areas (planes/bad wifi locations)

**Comment by drzraf** [comment]
I wish this could be reopened: It's 2025 and a global vision of "offline-mode" needs to be captured.
It's been ten years later and everything is getting harder today: auth/tokens, captcha, quotas, IP blacklisting, hidden wars between cloud-services/hosting providers, DNS messes.

GitHub downtimes are not rare anymore, even in EU and anyone using composer in production results in new challenges. `composer` should really come out of the box with commands/options to deal with the "offline repositories" scenarios.
- One dependency's update can't be fetched => how to fallback. And if a whole repository doesn't responds: ?
- How to force offline install (from the latest version **locally available**)?
- How to regenerate the autoload from cached version of the deps' only?
- etc etc...
