### ISSUE TITLE
Prevent Git update if head has diverged from remote

### ISSUE THREAD

**Issue by Burgov** [composer/composer#2253]
My colleague lost some work today (not too much luckily), after committing, but not pushing changes to a vendor library. To reproduce it, follow these steps:

1. have two copies of the vendor library in different projects
2. in copy A do a commit and push it
3. in copy B do a commit, but do not push it
4. in project B do a composer update

composer then executes a reset --hard in the library directory, effectively removing the commit from the face of the earth.

Suggested fix: just like when there are pending changes found in the library, and composer asks if you want to squash, reset or whatever, I think composer should detect diverged branches and ask you what to do with it (reset, rebase, etc.)

**Comment by Seldaek** [comment]
Closing as #3633 is merged.
