### ISSUE TITLE
Composer doesn't find private dependencies of a private dependency

### ISSUE THREAD

**Issue by luisdalmolin** [composer/composer#2260]
I'm having this problem: 

I have a project, who have a private dependency: 

``` json
"require": {
    "vendor/dependency-1": "dev-master"
},

 "repositories": [
    {
         "type": "git",
         "url": "git@github.vendor/dependency-1.git"
    }
],
```

In my **dependency-1** repository, I have this `composer.json`.

``` json
"require": {
    "vendor/dependency-2": "dev-master", 
    "vendor/dependency-3": "dev-master"
},

 "repositories": [
    {
         "type": "git",
         "url": "git@github.vendor/dependency-2.git"
    }, 
    {
         "type": "git",
         "url": "git@github.vendor/dependency-3.git"
    }
],
```

If I just run `composer install` in my project, I get this error: 

```
Problem 1
    - Installation request for vendor/dependency-1 dev-master -> satisfiable by vendor/dependency-1[dev-master].
    - vendor/dependency-1 dev-master requires vendor/dependency-2 dev-master -> no matching package found.
```

And If I add the private repositories address in my first project `composer.json` and run `composer install`, works fine.

``` json
"require": {
    "vendor/dependency-1": "dev-master"
},

 "repositories": [
    {
         "type": "git",
         "url": "git@github.vendor/dependency-1.git"
    }, 
    {
         "type": "git",
         "url": "git@github.vendor/dependency-2.git"
    }, 
    {
         "type": "git",
         "url": "git@github.vendor/dependency-3.git"
    }
],
```

I don't really want to my project knowing 'where' is the other dependencies repositories.

I think when a dependency has private dependencies, Composer do not look for the repositories key in the private `composer.json` file.

My Composer installation is up to date.

Is that a bug or I'm doing something wrong?

**Comment by johnrobertporter** [comment]
This is madness. And very infuriating.

**Comment by BrianIsSecond** [comment]
Yeah... this is something that I really wish they would change. I am having the same issue.
