### ISSUE TITLE
`composer [global] require`: Parse git urls as package name argument

### ISSUE THREAD

**Issue by patcon** [composer/composer#2276]
(Did some searching and I couldn't find this suggestion in the queues.)

Context #2172

Wow, the `global` wrapper and `require` command are *rocking my world*.

I'm thinking that they might be just the thing that was needed to possibly make composer a viable option for drush's recommended install method :)

Anyhow, so I'm working on a composerfying PR right now, and realizing that it would be really easy to allow someone to test my feature branch if this were possible:

```
composer global require https://github.com/patcon/drush:dev-pear-composer
```

Thanks so much guys. I'll investigate and update this thread!

cc: @robloach @drush-ops

**Comment by Seldaek** [comment]
Closing as not really worth the trouble it seems as it's not been done :)
