### ISSUE TITLE
Make it possible to build without downloading composer.phar

### ISSUE THREAD

**Issue by weierophinney** [composer/composer#2291]
From a security perspective, I'm a bit reluctant to download the `composer.phar` file in order to install dependencies so that I can then build... `composer.phar`. Right now, there's no way for a developer to verify sources before building.

Ideally, the project should provide a shell script or similar for fetching required dependencies, or a set of instructions so that developers can manually fetch and install dependencies and set up autoloading.

**Comment by Seldaek** [comment]
We improved the installer quite a bit so that you can now verify you get the right installer / composer.phar at least. Of course you still have to trust us, but that's gonna be the case either way IMO, so closing.
