### ISSUE TITLE
Packagist about page should be moved to composer docs

### ISSUE THREAD

**Issue by igorw** [composer/composer#2301]
I hope this isn't a duplicate.

This page: https://packagist.org/about contains quite a bit of information that either already exists in the composer docs or *should* exist there. Instead of duplicating it and potentially getting out of sync, all of that should be moved over to the official docs.

The packagist about page should *only* contain a link to the composer docs and packagist-specific info.

**Comment by jadjoubran** [comment]
Shouldn't this be created on [packagist's repository](https://github.com/composer/packagist)?

**Comment by stof** [comment]
Well, the Packagist about page has been rewritten entirely since 2013. So I guess this issue is not really relevant anymore
