### ISSUE TITLE
make svn based dependencies work flawless if project itself is svn managed

### ISSUE THREAD

**Issue by Flyingmana** [composer/composer#2307]
Had just a case in irc composer-dev, where a install/update of a package did fail with an 

```
Package could not be downloaded, svn: E155000: Revision 4782 doesn't match existing revision 3152 in ....
```

problem occurred, because the project itself is managed via svn and the dependency got fetched via svn, too.
I assume some conflict with how svn manages external svn repositories inside of an project.

full paste of composer install -vvv:
http://pastebin.com/6LggFrMc

**Comment by Seldaek** [comment]
See https://packagist.org/packages/linearsoft/composer-svn-export which hopefully fixes it.
