### ISSUE TITLE
composer hangs after Installing dependencies statement

### ISSUE THREAD

**Issue by godbout** [composer/composer#2310]
``` command
php composer.phar self-update
You are using the latest composer version.
```

``` command
php composer.phar diagnose
Checking platform settings: OK
Checking http connectivity: OK
Checking composer.json: FAIL
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking disk free space: OK
Checking composer version: OK.
```

``` command
php composer.phar --profile --verbose install
[13.3MB/0.17s] Loading composer repositories with package information
[28.0MB/11.15s] Updating dependencies (including require-dev)
```

Freezes after. Ran for 1 full night. Cpu goes crazy.
I'm on ubuntu 12.04, php 5.3.10 (the one coming with ubuntu).
No composer.lock by the way.
Cleared cache also.

Any chance to give more debug info?

**Comment by puru991** [comment]
So after "composer install", just right click on wamp icon and click 'refresh' and it will start the update. Figured out by a happy accident.

**Comment by jehzlau** [comment]
Same here. But I just left it and it moved after 15 minutes. :D Then it just started installing stuff :D

**Comment by ofembe** [comment]
There is a good chance it did not hang. Wait for a few minutes.

**Comment by MilitaruC** [comment]
For me was composer vendor. I did just `composer -vvv update`
