### ISSUE TITLE
requires composer-plugin-api 1.0.0 -> no matching package found.

### ISSUE THREAD

**Issue by joshribakoff** [composer/composer#2324]
I'm getting this on projects that previously worked. If I chose to depend on you, please don't break my stuff!!

requires composer-plugin-api 1.0.0 -> no matching package found.

I don't see the package anywhere here: https://packagist.org/search/?q=composer-plugin-api

The documentation here shows evidence that this package SHOULD exist, but it obviously does not. http://getcomposer.org/doc/articles/plugins.md#creating-a-plugin

**Comment by chrisx84** [comment]
2016 and im now getting this error everytime i update my laravel 5.2 project

**Comment by harikt** [comment]
@chr0n1x is your composer upto latest version ?

You may probably provide more details of the outputs for the below command if you are still experiencing the same ?

`composer update -vvv`

`composer diagnose`

**Comment by chrisx84** [comment]
`Basic usage: composer <command>
For more information just type "composer".

C:\Users\Christopher\Documents\Laravel Based sites\dwc>composer diagnose
The "franzl/studio" plugin requires composer-plugin-api 1.0.0, this *WILL* break in the future and it should be fixed ASAP (require ^1.0 for example).
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: FAIL
You are not running the latest version, run `composer self-update` to update
`

**Comment by curry684** [comment]
> The "franzl/studio" plugin requires composer-plugin-api 1.0.0, this WILL break in the future and it should be fixed ASAP (require ^1.0 for example).

Pretty dead giveaway there isn't it? The most recent builds referencing `1.0.0` are from March 25th 2015, and appear unmaintained.

Please update to the [current `dev-master` build of that plugin](https://packagist.org/packages/franzl/studio#dev-master) which is 7 days old and has the correct dependency in place.

**Comment by chrisx84** [comment]
ok how do i do that? im using laravel 5.2

**Comment by curry684** [comment]
`composer install franz/studio:@dev` should work. Keep in mind that you should also `composer self-update` before to fix the pubkeys per the end of the message.

**Comment by atayahmet** [comment]
We getting the below error after the transition to the composer new version 1.1.0 .

`  - composer/installers v1.0.22 requires composer-plugin-api 1.0.0 -> no matching package found.
[212.154.38.58:1223] out: `

I have examined the above recommendations but useful not. 

What exactly are the solution to this problem?

**Comment by stof** [comment]
latest version of ``composer/installers`` is 1.0.25, which is also fine. The requirement was fixed in the 1.0.23 release.

you should update all your composer plugins

**Comment by chrisx84** [comment]
i dont get the error now and im now using 1.1.0 on my new server. thnx for the help and fix.

**Comment by gtkhub** [comment]
same problem, don't know how to solve.

**Comment by bryanEcuador** [comment]
I am trying to use the composer but at the moment of doing the installation in the folder C: \ xampp \ htdocs it gives me the following error. Installation request for fxp / composer-asset-plugin 1.0.0-beta3 -> satisfactory for fxp / composer-asset-plugin [v1.0.0-beta3].
- fxp / composer-asset-plugin v1.0.0-beta3 requires composer-plugin-api 1.0.0 -> no matching packages were found.

**Comment by mikeyc7m** [comment]
i just hit this error, had to run a `composer update composer/installers` to proceed.

**Comment by QSoto** [comment]
I'm experiencing the same issue
    - symfony/thanks v1.0.1 requires composer-plugin-api ^1.1 -> no matching package found

is there any solution? i've already tried whole solutions in this post without success

**Comment by curry684** [comment]
Run `sudo composer self-update`.

**Comment by madhavi007** [comment]
After sudo composer self-update I am getting this Command "self-update" is not defined.

**Comment by xabbuh** [comment]
@madhavi007 This message is usually related to a Composer version that is shipped by Linux distributions through their package manager. I suggest to not use that version then if they do not allow to update to a recent version, but install Composer yourself [as described in the documentation](https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx).

**Comment by nt-thanh1996** [comment]
I installed this corrupted laravel, who support help?.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/thanks v1.0.1 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/thanks v1.0.0 requires composer-plugin-api ^1.1 -> no matching package found.
    - Installation request for symfony/thanks ^1.0 -> satisfiable by symfony/thanks[v1.0.0, v1.0.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by xabbuh** [comment]
You need to update your Composer version as explained above.

**Comment by pixiuPL** [comment]
@xabbuh Sorry, not true; when `sudo composer self-update` I got red box saying that `Command is not defined`. So, stop misleading people and admin that you (other devs also) have **not get any clue where the bug is**.

As its now, it cannot (and shouldnt) be called serious development.

**Comment by Seldaek** [comment]
The problem is that you need to update composer using whichever way you installed it. If you install via apt-get or similar, then perhaps the distro chose not to ship a phar file, instead shipping composer sources. In that case, the `self-update` command does not exist.

If you installed composer from getcomposer.org using a phar file then you  must have the self-update command. If you don't see it, check that you are indeed running the composer version you think you are. Check `which composer` for example.

**Comment by pixiuPL** [comment]
@Seldaek `which composer` gives absolute path to `composer`executable.....wise man
You didnt read my post carefully.... I installed via getcomposer.org (written in bold)...

**Comment by stof** [comment]
@pixiuPL the one downloaded from the official site **has** the `self-update` command. So if you are getting this `Command is not defined` message, there is a mistake somewhere. Are you sure that the composer pointed by the path returned by `which composer` is actually the one you installed from the website (you might have 2 different locations on your system).
Also, make sure you don't have a `composer` alias in your bash config which could hijack the command being run.

**Comment by pixiuPL** [comment]
@stof Im sure I have only one and thats this installed via website.
Alias `composer`is non-existing.

**Comment by stof** [comment]
what is the output of `composer --version` ?

**Comment by pixiuPL** [comment]
`Composer version 1.6.2 2018-01-05 15:28:41`

**Comment by pixiuPL** [comment]
Sorry all, but its composer who slows us down; we will look for sth else or write our own script for managing dependencies. We are serious about our business and dont have time to investigate whats wrong with composer - not to mention we are not its developers/contributors.

**Comment by harikt** [comment]
@pixiuPL Hire someone if you are not sure what to do. 

There is paid support for composer over : https://toranproxy.com/ or host at https://packagist.com/

They will fix it for you. Your arrogant replies to open-source projects don't help getting any answers or support. This is not paid support. 

If you are editing answers, we will not see it reflected on the email. They are replying from the email itself. So don't blame them for the same.

**Comment by pixiuPL** [comment]
@harikt we will hire **noone**. Rather than hiring, we sooner would like to start our own internal dep manager.

**Comment by LasseRafn** [comment]
You have to search long for such stupidity.

**Comment by LasseRafn** [comment]
@pixiuPL if you dislike it so much, then ask for a full refund of your payment to the dev team. I think they’ll happily refund every cent you paid.

**Comment by curry684** [comment]
@pixiuPL please thoroughly read the [Code of Conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html) applicable to this project. Specifically *"insulting/derogatory comments, and personal attacks"* are not welcome here, and will, if continued, result in a report to Github administrators. Be civilized to us, and we will be civilized to you.

So to get back to your issue: Composer 1.6.2 most definitely has a `self-update` command for everyone in the world, except apparently you. This could be caused by a corrupted plugin, or a typo on your end, or a PATH issue on your development system, or possibly other less obvious issues. You may even be running into a rare bug nobody is else is encountering. Very capable and very expensive people are trying to help you for free in this issue by asking diagnostic questions. I would recommend answering their questions and looking into their suggestions, as it is most likely the quickest way to a solution for your problem. Dumping your frustration on us is most definitely the slowest as we will simply stop helping, which in the end only harms one person: you.

**Comment by pixiuPL** [comment]
@curry684 Sorry for those who feels offended, but please understand me. Im in the middle of working on project and, out of sudden, one of its components (composer) turns out to be faulty. Not to mention deadline due in **3** days. Thats what hell looks like.

**Comment by curry684** [comment]
The frustration is understandable, I'm only saying it's counterproductive to vent it on the few people that can actually help :wink:

**Comment by harikt** [comment]
@pixiuPL paste your composer.json if you want us to look into the error you are having. Let us look into what you are facing with the error.

**Comment by curry684** [comment]
I'm most interested to see whether `composer list` shows the `self-update` command, as that overview is generated from the actual list of available command implementations. It's technically impossible for the command to show up there and not work.

**Comment by DronaCrus** [comment]
same problem here as pixiuPL

**Comment by rekah4** [comment]
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

**Comment by djodjo02130** [comment]
Same problem :/ 

- symfony/flex v1.0.9 requires composer-plugin-api ^1.1 -> no matching package found.

**Comment by pixiuPL** [comment]
@rekah4 sorry; this doesnt work

**Comment by korent** [comment]
try running 
"sudo composer self-update"
"sudo composer install"

**Comment by curry684** [comment]
**Do not run `composer install` as root as recommended above** unless you know extremely well what you are doing.

It will result in some to all of your packages being (partially) installed in your local project owned by root, thus causing later installs/upgrades to fail seemingly randomly with file permission errors.

The **only command you should ever run with `sudo` or otherwise as root is `composer self-update` when you installed Composer globally**.

**Comment by pixiuPL** [comment]
@chrisx84 don't teach sysadmin(s) risks of running commands with elevated privileges......
As of them, you can always change ownership later-on and get rid of errors......

**Comment by curry684** [comment]
Those who know how to fix it are least likely to follow the wrong advice in the first place.

To everyone - please stop posting potentially harmful "solutions" in this issue, and create a new one if you have problems.

**Comment by pixiuPL** [comment]
@curry684 whats harmful here in your opinion?
