### ISSUE TITLE
Get project name when create-project

### ISSUE THREAD

**Issue by piotrooo** [composer/composer#2328]
Hi, 
I have question about `create-project` command. Is there any possibility to get created project name (`targetDir`)?

I try to get this value like this:

```
"scripts": {
        "post-create-project-cmd": "Installer\\PostCreateProject::changePrefix"
    }
```

And method:

``` php
public static function changePrefix(Event $event)
    {
        $prefixSystem = $event->getComposer()->getPackage();
        $a = print_r($prefixSystem, true);
        file_put_contents('/tmp/test1', $a);
    }
```

I call command: `composer.phar -vvv create-project vendor/name:dev-master myproject`

But field with `targetDir` is empty.

**Comment by angular-tools** [comment]
To get the install dir, use this:

    $installedPackage = $event->getOperation()->getPackage();
    $installDir = $event->getComposer()->getInstallationManager()->getInstallPath($installedPackage);
