### ISSUE TITLE
errors php composer.phar install

### ISSUE THREAD

**Issue by royepperson** [composer/composer#2331]
I've been using composer with Doctrine 2 on Windows and now trying to use composer to install Doctrine 2 on a hosting service Unix php installation and their support staff isn't familiar with composer. 

I downloaded composer.phar 1.0.0-alpha7 and placed it in the directory where I want to install Doctrine

My php version is:

roye@ptah:~/cnrepperson_com$ /usr/local/php53/bin/php -v
PHP 5.3.12 (cli) (built: May  6 2012 12:16:29)
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies
    with the ionCube PHP Loader v3.3.14, Copyright (c) 2002-2010, by ionCube Ltd.

When I try to execute composer, I get:

roye@ptah:~/cnrepperson_com$ /usr/local/php53/bin/php -c /home1/r/roye/conf/php.ini composer.phar install
PHP Warning:  PHP Startup: memcache: Unable to initialize module
Module compiled with module API=20060613
PHP    compiled with module API=20090626
These options need to match
 in Unknown on line 0
PHP Deprecated:  Directive 'register_globals' is deprecated in PHP 5.3 and greater in Unknown on line 0

Deprecated: Directive 'register_globals' is deprecated in PHP 5.3 and greater in Unknown on line 0
PHP Deprecated:  Directive 'magic_quotes_gpc' is deprecated in PHP 5.3 and greater in Unknown on line 0

Deprecated: Directive 'magic_quotes_gpc' is deprecated in PHP 5.3 and greater in Unknown on line 0
PHP Fatal error:  require(): Failed opening required 'phar://composer.phar/bin/composer' (include_path='.:/usr/local/php5/lib/php') in /nfs/ank/home1/r/roye/cnrepperson_com/composer.phar on line 14

Fatal error: require(): Failed opening required 'phar://composer.phar/bin/composer' (include_path='.:/usr/local/php5/lib/php') in /nfs/ank/home1/r/roye/cnrepperson_com/composer.phar on line 14

I'm at a lost how to get this to work.  Thanks in advance for any assistance!

Roy

**Comment by DAMskill** [comment]
Ok so how doi fix this?

I'm encountering the same problem when trying to get "https://github.com/drupalcommerce/project-base" to work.

I'm a noob when it comes to these stuf. So sorry if the question seems funny.
