### ISSUE TITLE
Document setting up a github oauth token

### ISSUE THREAD

**Issue by igorw** [composer/composer#2366]
We don't really have anywhere properly documenting how to do:

```
composer config -g github-oauth '{"github.com": "oauthtoken"}'
```

When it is needed, and where to get that oauth token in the first place.

Which is kinda important for deployment machines and such.

**Comment by lferro9000** [comment]
I would prefer to have a proper global configuration or one under the current user home folder. I don't think it is good to send authorization tokens into configuration files that can end up being distributed on GitHub or other source repos, because they will end up as such, eventually.

**Comment by ranjankumar077** [comment]
![7234-screenshot_2018-02-18-19-05-04-532](https://user-images.githubusercontent.com/4502555/36638408-2a7e25e6-1a1a-11e8-982e-cb6c9198f4cd.jpeg)
