### ISSUE TITLE
Composer Website Down. Unable to install composer.

### ISSUE THREAD

**Issue by thenetimp** [composer/composer#2390]
Since there's no where else to send this message, I will use this.

The get composer website is down.  The instructions to install source require me to get the composer.phar  See the problem?  I recently re-installed my operating system because I installed a new hard drive.  I have work that is due tonight, and need to install Symfony 2 vendors modules for what I am doing.  This requires composer, but because the website is down I can't install it from there, and since you're instructions to install from source require composer.phar I can't even install it from the repository.  

Please add instructions to install from source without composer.phar so that if the website goes down again there is a 2nd option for installing composer.

**Comment by djmattyg007** [comment]
Using composer in your toolchain right now seems to introduce a lot of single points of failure. This really should be looked in to.

**Comment by curry684** [comment]
Both [Toran Proxy and Satis](https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md) can mirror all of Packagist to a local server or even your local computer. Packagist is only an SPOF if you want it to. Apart from that - if Packagist happens to be down you're only prevented from updating or adding previously unknown packages. Even installing should be fine from local caches.

**Comment by djmattyg007** [comment]
I think the point is that you should be able to build composer without it needing to talk to any repository, mirror or otherwise.

**Comment by curry684** [comment]
Perhaps @Seldaek can convince someone at Amazon Cloudfront or the like to sponsor a CDN frontend to Packagist and Getcomposer. But barring a big-budgetted sponsor I doubt that's going to happen  :)

**Comment by djmattyg007** [comment]
Why is it not possible to create a shell script that has access to a separate record of where dependencies are stored, so that it can download them from there and avoid the need to talk to packagist during the build process? I'd be happy to look into making this possible.
