### ISSUE TITLE
using HTTP directory

### ISSUE THREAD

**Issue by TekTimmy** [composer/composer#2391]
First i wanna say that composer is a great tool with a very good documentation! Thank you for that!

We would like to use composer in combination with apache archiva and drop our composer dependencies into an archiva folder. The benefit of archiva is that it just provides the files accessible by HTTP listing with digest authentication.

This is the current composer.json:

```
{
    "name": "vendor_name/package_name",
    "description": "description_text",
    "minimum-stability": "stable",
    "authors":
        [
            {
                "name": "author's name",
                "email": "email@example.com"
            }
        ],
    "require": {
        "phpunit/phpunit": "3.7.28",
        "phpmd/phpmd": "1.5.0",
        "squizlabs/php_codesniffer": "1.5.0RC4"
    },
    "repositories": [
        {
            "packagist": false
        }, {
            "type": "artifact",
            "url": "http://username:password@ourserver.com/archiva/repository/phpcomposer/"
        }
    ]
}
```

the error message I get is: "failed to open dir: not implemented"

Is there a chance to make the repository type "artifact" able to use HTTP directorys?

greets
Timmy

**Comment by Marqin** [comment]
I also stumbled across this problem, and created [Python script](https://github.com/Marqin/compository) that generates `packages.json` file, so you can use your zip directory as composer repo (instead of `artifact`s) via HTTP.
