### ISSUE TITLE
Error while running Laravel composer quickstart

### ISSUE THREAD

**Issue by thallisphp** [composer/composer#2403]
When I run the Laravel Framework quickstart command,I get the following error:

```
composer create-project laravel/laravel test-project --prefer-dist
```

```
[Composer\Repository\RepositorySecurityException]
The contents of http://packagist.org/p/swiftmailer/swiftmailer$c85462b1cb2a
b50df812424c10be241b455785157c9580c9e252b805a49ba80a.json do not match its
signature. This should indicate a man-in-the-middle attack. Try running com
poser again and report this if you think it is a mistake.
```

![image](https://f.cloud.github.com/assets/754918/1490798/86bf34a8-479c-11e3-92fa-76b52ddcb9ee.png)

My composer is up-to-date

![image](https://f.cloud.github.com/assets/754918/1490814/eec3e6f2-479c-11e3-9611-1a891af027cd.png)

**Comment by thirunjuguna** [comment]
Fix `composer config --global repo.packagist composer https://packagist.org`

**Comment by xlcrr** [comment]
vagrant reload worked for me
