### ISSUE TITLE
Installed JSON overrides package information

### ISSUE THREAD

**Issue by cs278** [composer/composer#2416]
When I run `composer update nothing` on a project I'm getting a bunch of distribution URLs being changed in the lock file. This is happening where the distribution URL has changed *after* I've installed the package locally, the old URL is stored in `installed.json` and that value is being replacing the correct value in the lock file. I've been working around the issue by editing the `installed.json` file.

**Comment by Seldaek** [comment]
This should be fixed now by #3985
