### ISSUE TITLE
Requiring a private git Bitbucket repository fails to find valid composer.json

### ISSUE THREAD

**Issue by mcfdn** [composer/composer#2418]
I'm trying to reference a private git repository from Bitbucket in my project's composer.json:

```
{
    "require": {
        "vendor/my-private-package": "dev-master"
    },
    "repositories": [
        {
            "type": "git",
            "url": "git@bitbucket.org:vendor/my-private-package.git"
        }
    ]
}
```

The remote repository has the following composer.json:

```
{
    "name": "vendor/my-private-package",
    "autoload": {
        "psr-0": {
            "NS_": "src/"
        }
    }
}
```

I'm receiving the following error:

```
[Composer\Repository\InvalidRepositoryException]
No valid composer.json was found in any branch or tag of git@bitbucket.org:vendor/my-private-package.git, could not load a package from it.
```

Is this expected behavior? My understanding is that I should just be able to reference a remote git repository and have composer install it with or without a remote composer.json.

**Comment by aldee07** [comment]
I know this is a bit old, but for some that might encounter this issue, this is how it works for me.

Clear the composer cache.

`composer clearcache`

Rerun the satis build script.

**Comment by hisenbergguj** [comment]
@aldee07  it doesnt  work for me any otheridea?

can you post your private package JSON file?

**Comment by jUnG3** [comment]
@aldee07 
Thx for the idea. I encountered the same problem and the `composer clearecache` command helped.

**Comment by bradleygreen** [comment]
'composer self-update' seems to have solved the problem for me. I did try 'composer clearcache' first, and also tried deleting C:\users\username\AppData\Local\Composer\*.

The suggestions I found didn't seem to work for me, but updating my composer did. Best of luck to you all!
