### ISSUE TITLE
Wierd speed issue with xdebug enabled

### ISSUE THREAD

**Issue by AlexeyKupershtokh** [composer/composer#2425]
I've measured `composer update` speed in 3 environments:
- xdebug not even loaded
- xdebug loaded but doesn't do anything
- xdebug loaded and xdebug.profiler_enabled=1
  In two cases:
- empty vendor dir, but the packages are cached
- just updated vendor dir

And the timings are the following:

| vendor | empty | full |
| --- | --- | --- |
| xdebug off | 7.84s | 7.61s |
| xdebug loaded | 12.17s | 17.32s |
| profiling enabled | 27.5s | 66.0s |

This usually tell about that there are maaany fast operatons that are made slow drastically by xdebug (it adds some constant time to each fn call).

Also xdebug profiling files very differ in size:

| vendor | empty | full |
| --- | --- | --- |
| cachegrind file size | 142mb | 488mb |

That tells the same: composer has ~4 times more function calls when the vendor dir is full and actual. So I wonder why does it perform extra work.

**Comment by amenk** [comment]
It is annoying BTW :-)
