### ISSUE TITLE
JsonFileTest::testParseErrorDetectSingleQuotes() fails on some systems / ubuntu accepting invalid json.

### ISSUE THREAD

**Issue by donquixote** [composer/composer#2457]
[JsonFileTest::testParseErrorDetectSingleQuotes()](https://github.com/composer/composer/pull/79/files#diff-8cb1270fe3ea5757065f612d612cd07bR27) expects that [json_encode()](http://www.php.net/manual/en/function.json-encode.php) fails if keys are enclosed with single quotes instead of double quotes.

This test passes just fine on a Debian with PHP 5.4.13 and json version 1.2.1.
However, it fails (for me) on an LMDE (Linux Mint Debian Edition) with PHP 5.5 and json 1.3.1.

Maybe relevant: In the system where json_encode() accepts the single quotes, I get 

```
$ php --info | grep "json\|JSON"
/etc/php5/cli/conf.d/20-json.ini,
json
json support => enabled
json version => 1.3.1
JSON-C headers version => 0.11
JSON-C library version => 0.11
```

@igorw says this is because some systems (Ubuntu) have their own json which behaves differently. I am on LMDE which is supposed to be not based on Ubuntu, but maybe there is still this evil json extension.

@igorw also says we are not going to fix this in Composer, but we can add a comment.

**Comment by t128** [comment]
im getting the same error:

```
There was 1 failure:

1) Composer\Test\Json\JsonFileTest::testParseErrorDetectSingleQuotes

/home/thomas/workspace/composer/tests/Composer/Test/Json/JsonFileTest.php:213
/home/thomas/workspace/composer/tests/Composer/Test/Json/JsonFileTest.php:60

FAILURES!
Tests: 1310, Assertions: 2057, Failures: 1, Skipped: 1.
```

```
$ cat /etc/issue
Ubuntu 14.04.1 LTS \n \l


$ php --version
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10)

$ php --info | grep "json\|JSON"
/etc/php5/cli/conf.d/20-json.ini,
json
json support => enabled
json version => 1.3.2
JSON-C version (bundled) => 0.11
json support => no
```

**Comment by Seldaek** [comment]
Well no there is no easy way to disable just that one I think. I would say just ignore it or temporarily delete it if you're working on a patch and it annoys you.

I am not sure if we can detect this bad lib and it should apparently be fixed in an upcoming release of jsonc so I would say let's ignore it for now.

**Comment by t128** [comment]
hmm, ok, so i disabled testing on my Jenkins machine.
