### ISSUE TITLE
AutoloadGenerator refactoring - strategy talk

### ISSUE THREAD

**Issue by donquixote** [composer/composer#2460]
I still would like to refactor the AutoloadGenerator. It is so messy and huge. But I want to wait until PSR-4 lands, https://github.com/composer/composer/pull/2459

Previous attempts:
- https://github.com/composer/composer/pull/2142
- https://github.com/composer/composer/pull/2298

Now, before I give this another try, I would like to discuss some strategy.

I made some strategical decisions in the previous attempts, and would like to know which of these you agree with and which you don't.
#### 1. Introduce separate classes for different parts of the generated autoload stuff.

One for PSR-0, one for PSR-4, one for classmap, one for include paths, etc. In the second PR I called this "aspects", but discussion showed this was a stupid and misleading choice of word. Maybe "Plugin" is better?

Each of these classes can do two things: Dump a file, and return a php snippet for the ComposerAutoloaderInit::getLoader() method. This can be defined in an interface they all implement.

In the second PR this used to be in the same method, but we can easily split this up to be two separate methods.

One question is which data to provide to those "plugins". The main algorithm should just iterate over all registered plugins and give each the chance to dump a file and add a php snippet. Here they should all receive the same parameters. However, they could have different constructor parameters.
#### 2. Turn some variables into protected object properties

Some of the variables in AutoloadGenerator are passed around all over the place. E.g. $basePath, $vendorPath, $targetDir, $appDirBaseCode, stuff like that.

I generally believe in reducing the visibility of state and variables as much as possible. An object or method that does not need a given variable, should not get its hand on it. However in this case I don't think that all the passing around really helps anyone.

It would be easier if at least some of the variables were somehow bundled in an object. This can either be the main object where all the work happens, so you would do $this->vendorPath.

Or it could be a service object that is passed around, to provide everyone with the paths. This could also take care of the calculation of relative paths from one base to another.
#### 3. Have an object that represents the process

Atm the AutoloadGenerator itself does not remember anything about the generation process. All the information about the generation process is passed in to the dump() method, and will be forgotten afterwards.

I am suggesting a different approach: An object that receives all the information on construction time, and that only lives as long as the generation process.

This object could either contain all the generation logic, or it could just be a helper to be passed around.

We should not change the interface of AutoloadGenerator, so this new object would be something else, instantiated from AutoloadGenerator->dump().
#### 4. LazyEvaluationContainer similar to a DIC

This was an idea I used in the second PR, that I also like to use "at home" in other projects.

It is meant for a situation where you want to calculate a number of values with a dependency graph. You want to make sure that each value is only calculated once, and you want to make sure that values are calculated in the correct order so that if B depends on A, then A will be calculated before B. The values are all part of the same instance of the problem, they will all be recalculated if the instance parameters change.

Technically the solution I use works very much like a compiled DIC like in e.g. Symfony2.

I am still not sure this is an idea that can be generally recommended, e.g. @igorw had some valid concerns. I also [asked on stackoverflow](http://stackoverflow.com/questions/19620868/lazy-evaluation-container-for-dynamic-programming) to get some useful feedback, but not sure I asked the right question.

**Comment by Seldaek** [comment]
Just not really worth it anymore IMO, the code is pretty stable and changing rarely, no huge benefit in refactoring with possibility of adding regressions.
