### ISSUE TITLE
Be more flexible with "local_cert"-option

### ISSUE THREAD

**Issue by rejinka** [composer/composer#2462]
This option seems to rely on a hardcoded string. I'd rather like to set "local_cert" to sth like "{$home}/auth/cert.pem" to allow windows and linux developers to use the same path in the configuration.

I have two other options:
- Store the key somewhere in the project-structure, which i don't think of is good practice (as the key could be needed in more than one project)
- Every developer needs to modify the composer.json, so there needs to be some kind of composer.json.dist

Both options don't look really nice...

It does not need to be the solution, i suggested, but i think this is important to fix this somehow in order to use private repositories properly.

**Comment by aminin** [comment]
> but not sure that it is real case

I wasn't sure too, until faced it
