### ISSUE TITLE
Defining multiple composer.json files

### ISSUE THREAD

**Issue by oscarotero** [composer/composer#2480]
Hi.
I'd like to know if I can define other dependencies defined in local folders by hand. For example: I have this structure:

```
composer.json
subfolder/composer.json
```

And I want to install the dependencies of both folders. If I install individually, composer will create two vendors folders. I'd like something like:

``` json
{
"require": { ... },
"include": ["subfolder/composer.json"]
}
```

This allows to merge both json files, so all packages, will be stored in the same folder.

**Comment by ashrafimanesh** [comment]
you can use use :
`{
"autoload" : {
    "classmap" : [ 
        "subfolder/"
    ]
}
}`
