### ISSUE TITLE
Add a .gitignore rule (vendor/.git) to ignore all the vendor .git folders.

### ISSUE THREAD

**Issue by n1c01a5** [composer/composer#2506]
I will push all my repository with vendors to my github repository but the repository .git and file .gitignore in submodules make untracked their repository. That's a problem with Capifony when I will deploy all my app from githup repository.

I use these commands to remove GIT in the submodules:

```
find vendor/ -type d -name .git -exec rm -rf {} \;
find vendor/ -name .gitignore -exec rm {} \;
```

but I would not delete GIT in submodules to avoid any problems with dependencies from disk prior to running a composer update.

Any issue (http://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md) is to add a .gitignore rule (vendor/.git) to ignore all the vendor .git folders.

Yes, but how?

**Comment by ElijahLynn** [comment]
Worth noting that at least with git 2.17.1, step 4 (http://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md) to ignore .git folders does not work in the .gitignore file.
