### ISSUE TITLE
Composer Too slow becuase of just `git clone`

### ISSUE THREAD

**Issue by dev-mraj** [composer/composer#2513]
me and many out there may have slow internet connection.... when installing dependencies via composer.json and if some of them are from vcs like git.. then why composer.phar run `git clone`

i have ~40KBPS (500 kbps) speed and downloading https://github.com/twbs/bootstrap have taken too long time.

i think instead of `git clone` it should either use `git clone --depth=0` or something like `git archive` or should give us option for that.

**Comment by DeeJaVu** [comment]
im using the latest version and i have the same problem it takes ages just for 5 repositories
is there a fix for this ?

**Comment by slbmeh** [comment]
@DeeJaVu this ticket wasn't really an issue, so aside from the methods mentioned there isn't a fix.

What is the issue you are trying to address?
