### ISSUE TITLE
Support for users without SSH access

### ISSUE THREAD

**Issue by ilhanyumer** [composer/composer#2545]
Because most of the projects require Composer I have a hard time installing PHP application. This is because I don't have SSH access to my shared hosting. Sadly Composer makes PHP projects for only rich people who can buy hostings with SSH access. Can you please make Composer so that it does not require SSH. http://stackoverflow.com/questions/20894518/how-do-i-install-composer-on-a-shared-hosting

**Comment by ryanwohara** [comment]
This isn't really an issue with composer and should be closed. 

>Sadly Composer makes PHP projects for only rich people who can buy hostings with SSH access.
That's entirely untrue as Digital Ocean sells VPS for $5/month and Linode sells them for $10/month.

**Comment by vanilla-thunder** [comment]
> That's entirely untrue as Digital Ocean sells VPS for $5/month and Linode sells them for $10/month.
and this shows us you got absolutely no real world experience and therefore no idea what you are talking about.
first: 5$ digital ocean vps got only 512mb ram. This is barely enough for starting some small composer project. Composer eats RAM like fat kids eat bacon. You need about 4gb ram to resolve ~15 dependencies and 4gb ram vps costs at the moment 40$ at digital ocean.
second: even 40$ digita ocean vps is unmanaged. This means: unless you are a dev or sys admin, you will be forced to invest hundreds hours into crap you seriosly do not want and do not need to know for your business or to pay for managed hosting, which cost you about 75-150$. 
And now imagine you were poor indian guy earning 250$/month.

**Comment by vanilla-thunder** [comment]
> That's entirely untrue as Digital Ocean sells VPS for $5/month and Linode sells them for $10/month.

and this shows us you got absolutely no real world experience and therefore no idea what you are talking about.
first: 5$ digital ocean vps got only 512mb ram. This is barely enough for starting some small composer project. Composer eats RAM like fat kids eat bacon. You need about 4gb ram to resolve ~15 dependencies and 4gb ram vps costs at the moment 40$ at digital ocean.
second: even 40$ digita ocean vps is unmanaged. This means: unless you are a dev or sys admin, you will be forced to invest hundreds hours into stuff you seriosly do not want and do not need to know for your business or to pay for managed hosting, which cost you about 75-150$.
And now imagine you were poor indian guy earning 250$/month.
