### ISSUE TITLE
Update lock file to currently checked out versions

### ISSUE THREAD

**Issue by jkufner** [composer/composer#2561]
When developing application with Composer-managed plugins (ordinary Composer dependencies), there is no way to update lock file to currently installed versions of the plugins.

**Scenario looks like this:**

I developing a plugin and application together. When some feature is done, I commit & push plugin changes and then I commit & push application changes.

With git submodules, I see that there are new commits in the plugin and reference to exact commit is commited along with application changes.

**Problem:**

When using Composer, replacing git submodules, there is no way to propagate current commit ID of the plugin back to application lock file.

It is possible to run `composer update`, but it will download new version from a git server. When somebody pushes new commits to plugin's master before the `composer update` is done, it will result in unwanted local modification.

**Solution:**

There should be a command (`composer update --lock` or something like that) to get current commit ID from local Git repositories and write them to lock file. This command would not modify anything but the lock file, so it can be used just before creating application commit. This way, the new commit can be consistent without need to fetch new versions too early (there may be little incompatibilities I want fix tomorrow, but I want working nightly builds today for testers).

This also eliminates a need to communicate with server at all, so consistent commits can be done offline. Having correct content of the lock file is useful when using `git bisect` to locate source of errors, where application and plugin needs to be in correct revisions.

All this is relevant only during developement. When application is done, you can release new version of plugin and let application to depend on it. But when current version is "master", it is not possible.

**Comment by Seldaek** [comment]
Don't think we're going to do that, but it could be done as a plugin I suppose if someone really wants to.
