### ISSUE TITLE
Timeout error for required lib

### ISSUE THREAD

**Issue by yellowmamba** [composer/composer#2564]
Hi folks,

I am running into a problem where installing a dependency has timed out. The error is something like this:

```
Updating dependencies (including require-dev)
  - Installing symfony/filesystem (v2.4.1)
    Downloading: 100%

  - Installing symfony/config (dev-master bde2f71)
    Cloning bde2f7192a52dfd07cf5484ad65d719da28effba



  [Symfony\Component\Process\Exception\ProcessTimedOutException]
  The process "git clone 'git://github.com/symfony/Config.git' '/Users/<username>/symfonyConfig/vendor/symfony/config/Symfony/Component/Config' && cd '/Users/username/symfonyConf
  ig/vendor/symfony/config/Symfony/Component/Config' && git remote add composer 'git://github.com/symfony/Config.git' && git fetch composer" exceeded the timeout of 300 seconds.
```

I noticed there's a difference between downloading or cloning a repo by Composer. The weird thing is when cloning a repo, it runs `git clone git://something` which usually prompts for a key. But it didn't happen here for some reason, which is why I think it times out. Any suggestions?

**Comment by Wilmar2015** [comment]
thats right

**Comment by Wilmar2015** [comment]
you need to type: "composer config process-timeout 1200"  en segundos
