### ISSUE TITLE
Failure if unzip is not installed (as happens on a clean Ubuntu 13.10 install)

### ISSUE THREAD

**Issue by roderik** [composer/composer#2565]
## Short situation:

I was trying to do a create-project using composer on a Ubuntu 13.10 clean vm. PHP 5.5 installed using Chef with https://github.com/Kunstmaan/chef-php/blob/master/recipes/package.rb (irrelevant for the issue) that mostly just does apt-get install php5-cgi php5 php5-dev php5-cli php-pear, ext-zip is built in.

## The issue:

```
  - Installing doctrine/common (2.3.0)
Downloading https://api.github.com/repos/doctrine/common/zipball/d1c7d4334e38cad603a5c863d4c7b91bb04ec6b2
    Downloading: 100%         
Writing /home/vagrant/.composer/cache/files/doctrine/common/d1c7d4334e38cad603a5c863d4c7b91bb04ec6b2.zip into cache
    Extracting archive
Executing command (CWD): unzip '/home/projects/test/data/test/vendor/doctrine/common/a259fc31d4f248f87439a5515c6aa490' -d 'vendor/composer/25117f89' && chmod -R u+w 'vendor/composer/25117f89'
Reading ./composer.json


                                                             
  [RuntimeException]                                         
  There was an error extracting the ZIP file. Corrupt file?  
                                                             


Exception trace:
 () at phar://composer.phar/bin/../src/../src/Composer/Downloader/ZipDownloader.php:76
 Composer\Downloader\ZipDownloader->extract() at phar://composer.phar/bin/../src/../src/Composer/Downloader/ArchiveDownloader.php:43
 Composer\Downloader\ArchiveDownloader->download() at phar://composer.phar/bin/../src/../src/Composer/Downloader/DownloadManager.php:182
 Composer\Downloader\DownloadManager->download() at phar://composer.phar/bin/../src/../src/Composer/Installer/LibraryInstaller.php:155
 Composer\Installer\LibraryInstaller->installCode() at phar://composer.phar/bin/../src/../src/Composer/Installer/LibraryInstaller.php:86
 Composer\Installer\LibraryInstaller->install() at phar://composer.phar/bin/../src/../src/Composer/Installer/InstallationManager.php:153
 Composer\Installer\InstallationManager->install() at phar://composer.phar/bin/../src/../src/Composer/Installer/InstallationManager.php:140
 Composer\Installer\InstallationManager->execute() at phar://composer.phar/bin/../src/../src/Composer/Installer.php:510
 Composer\Installer->doInstall() at phar://composer.phar/bin/../src/../src/Composer/Installer.php:210
 Composer\Installer->run() at phar://composer.phar/bin/../src/../src/Composer/Command/CreateProjectCommand.php:176
 Composer\Command\CreateProjectCommand->installProject() at phar://composer.phar/bin/../src/../src/Composer/Command/CreateProjectCommand.php:143
 Composer\Command\CreateProjectCommand->execute() at phar://composer.phar/bin/../src/../vendor/symfony/console/Symfony/Component/Console/Command/Command.php:241
 Symfony\Component\Console\Command\Command->run() at phar://composer.phar/bin/../src/../vendor/symfony/console/Symfony/Component/Console/Application.php:881
 Symfony\Component\Console\Application->doRunCommand() at phar://composer.phar/bin/../src/../vendor/symfony/console/Symfony/Component/Console/Application.php:191
 Symfony\Component\Console\Application->doRun() at phar://composer.phar/bin/../src/../src/Composer/Console/Application.php:117
 Composer\Console\Application->doRun() at phar://composer.phar/bin/../src/../vendor/symfony/console/Symfony/Component/Console/Application.php:121
 Symfony\Component\Console\Application->run() at phar://composer.phar/bin/../src/../src/Composer/Console/Application.php:83
 Composer\Console\Application->run() at phar://composer.phar/bin/composer:43
 include() at /usr/local/bin/composer.phar:15
```

No clear indication what's wrong, but when trying to run the command by hand I noticed that "unzip" is not installed by default.

## The culprit in composer

https://github.com/composer/composer/blob/20a18dcb6068e3a05cf51927bd609f62539c4476/src/Composer/Downloader/ZipDownloader.php#L41

## The solution

For me to fix my problem, I just added "unzip" to my chef recipe for composer and everything works great. 

In general, I believe a test for the availability of the "unzip" command should be added

**Comment by p-blomberg** [comment]
I also have problems with ZipArchive. 
I have a repo hosted on github containing symbolic links. When the unzip command extracts the archive, it works fine. But when unzip is not available, I get regular files containing the path to the link target, instead of an actual link. I get no warning or error about this.
Maybe ZipArchive can be fixed, but to me it seems fine to require unzip to be installed.

**Comment by andrerom** [comment]
Had the same problem on Debian 8, execution permissions of extracted files where not kept like also reported in #4471, installing `unzip` helped. A way to require this platform agnostic, or getting Composer to detect this would be great to avoid that users get stuck on this.

**Comment by Seldaek** [comment]
I am not sure what we can do tbh. We can't force people to install unzip. If there is no way to fix it by tweaking our usage of ZipArchive I'd suggest at least reporting it to bugs.php.net.

**Comment by curry684** [comment]
> We can't force people to install unzip.

We already force them to install `git` for git source dists, why not force `unzip` for zipball dists?

**Comment by Seldaek** [comment]
Because generally speaking people can install with purely php, if both git AND zip require some external util then that's not true anymore..

**Comment by andrerom** [comment]
So fixing it at the source in ZipArchive it is then, any takers? :)

**Comment by curry684** [comment]
We could take a middle road in implementing a warning when ZipArchive errors occur that they may disappear when installer a proper `unzip` implementation (akin to `Console::hintCommonErrors`).

**Comment by curry684** [comment]
I implemented the warning for when the first zipfile is downloaded. We can't really show it when issues arise as we can only detect the file corruption, not the permission issues.

**Comment by HammamiOussama** [comment]
got the same problem here and that was just about open_basedir restirctions
added /usr/bin to open_basedir in /etc/php/php.ini to solve it
