### ISSUE TITLE
Can't authenticate

### ISSUE THREAD

**Issue by Pajamaman** [composer/composer#2574]
I created an account on Packagist.org. When I try to `php composer.phar install`, I get the prompt:

    Authentication required (packagist.org):
      Username: SuperSecret
      Password:

The prompt repeats indefinitely, regardless of how many times I type in the correct password.

Also, I must admit I am confused why authentication is needed to download a package in the first place.

Edit: I am behind a proxy, but am skeptical about setting an environment variable containing my password ala [this](http://blog.bobbyallen.me/2013/03/15/using-gitcomposer-on-windows-7-via-an-authenticated-proxy-server/).

**Comment by nd4c** [comment]
I'm being a router that blocks access to facebook.  

I have an account at packagist.org and sign in when composer asks me.  But I get the following error:

[Composer\Downloader\TransportException]
Invalid credentials for 'http://packagist.org/p/facebook/webdriver$5d1a2ad9
1133127c18903ff8ad94c24a2225a38982bd1caaad63eee047566b2b.json', aborting.

Note that it's trying to access a folder named facebook - not good!!

**Comment by xabbuh** [comment]
@nd4c This is probably due to the fact that some of your requirements depend on the `facebook/webdriver` package.

**Comment by nd4c** [comment]
Yeah.  I'm going to have to try all this at home.  I'm currently doing some research at work so I don't want to ask to bypass some of the online access restrictions they have unless I'm sure that's the problem.  Thanks.

**Comment by Wiich0** [comment]
Hi, I use composer in windows 7 and I solved it, setting PROXY like:

**$ export HTTP_PROXY=http://x.x.x.x:port**

**example:**
$ export HTTP_PROXY=http://123.123.123.123:8080

And diagnostic composer with: 
**$ composer diagnose**
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: Warning: Accessing packagist.org over http which is an insecure protocol.
OK
Checking https connectivity to packagist: OK
Checking HTTP proxy: OK
Checking HTTP proxy support for request_fulluri: OK
Checking HTTPS proxy support for request_fulluri: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B
OK
Checking composer version: OK

**Comment by sivajik34** [comment]
For me also same issue.everything is ok with diagnose.but still no idea causing an issue.
at the time of diagnose command also its asking authentication.
I'm using docker with windows as a host,ubuntu as a virutual machine.

**Comment by Kharismatics** [comment]
same on me even if i run composer diagnose i got user and pass required too
and i dont know what kind of the right pass and user

**Comment by Ericzhiluo** [comment]
i have the same issue can't pass over it.

**Comment by iamNikitaValty** [comment]
**Please for help !**
Does Anyone has new idea ?

I tried all the above proposals and those found [Here](https://github.com/composer/composer/issues/5825) but no result.

I'm not running a Proxy
My http port is free
composer diagnose marks everything as ok

But i get this when running ` curl -I -L packagist.phpcomposer.com`

HTTP/1.1 403 Forbidden
Server: nginx
Date: Thu, 11 Oct 2018 17:30:41 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 11
Connection: keep-alive
X-Req-Id: A4E5D61D6C83DA0B
Age: 0
Via: http/1.1 ORI-CLOUD-HUADONG-BFP-195 (jcs [cMs f ]), http/1.1 GZ-CT-1-BFP-61 (jcs [cMs f ])
X-Trace: 403-1539279041703-0-0-0-76-76;403-1539279041638-0-0-0-166-166

**Comment by iamNikitaValty** [comment]
My problem was due to this `packagist.phpcomposer.com` which is a fake website (i guest because visiting it, i found lot of junk chineese-like test...).

After checking my composer config at this path : C:\Users\[UserName]\AppData\Roaming\Composer\config.json, i found that the url  _"https://packagist.org"_  was replaced by this dummy site :  _"packagist.phpcomposer.com"_. 
So, i just reverted the url to  _"https://packagist.org"_  and i could run composer install again.
My  machine must have been infected with a worm or sthg else.
Hope this can help somebody.

**Comment by bossikill** [comment]
use this:
composer config -g repo.packagist composer https://packagist.laravel-china.org
