### ISSUE TITLE
Issues resolving dependency on "php" package under HHVM.

### ISSUE THREAD

**Issue by jmalloc** [composer/composer#2575]
In this HHVM [travis build](https://travis-ci.org/recoilphp/recoil/jobs/16557680#L30), (with the latest version of composer from master) I'm getting the errors:

    - The requested package php could not be found in any version, there may be a typo in the package name.
    - evenement/evenement v2.0.0 requires php >=5.4.0 -> no matching package found.

The exact composer command is:

    composer install --dev --no-progress --no-interaction --ansi

Does composer do anything special in regards to solving PHP version dependencies? and/or is this a bug?

**Comment by skyzyx** [comment]
I'm noticing this happening in Composer running on OS X, but not on CentOS (for example). Identical versions of PHP, same physical directory (using Vagrant and NFS), the install command works in CentOS but not in OS X. For me, this happens irrespective of HHVM usage.
