### ISSUE TITLE
Add a command to show updates excluded by current constraints.

### ISSUE THREAD

**Issue by realityking** [composer/composer#2576]
Once you get to a significant amount of dependencies it gets hard to track releases for everything. I'd like to see a command to list all packages for which there is a newer version than allowed for the current constraints.

For example, one of my composer.json contains the following requirement:

```
"jeremykendall/php-domain-parser": "0.0.*",
```

Now by pure chance I discovered that a few weeks ago version 1.0.0 and 1.1.0 have been released.

**Comment by Seldaek** [comment]
Closing as duplicate of #1563, will be fixed by #5028 I believe.
