### ISSUE TITLE
Config cli command fails to update repositories when repositories is in array form

### ISSUE THREAD

**Issue by Stasmo** [composer/composer#2601]
While attempting to add a repository via command line with the command

```
php composer.phar config repositories.foo vcs https://github.com/xyz
```

The command failed each time returning this error:
  [ErrorException]
  Parameter 1 to Composer\Config\JsonConfigSource::Composer\Config{closure}() expected to be a reference, value given

This is exception message is thrown after the update fails and the [fallback function call fails](https://github.com/composer/composer/blob/master/src/Composer/Config/JsonConfigSource.php#L122), but has nothing to do with the real issue.

The real issue here is that composer will fail to add a repository to the composer.json file if the repositories section is in array form.

It should either return a proper error message or add the repo to the array, unless it's a duplicate. Maybe add a warning to the [documentation](http://getcomposer.org/doc/03-cli.md#modifying-repositories) that it does not work if the repos are in array form.

For the record I think this is the first bug I've submitted to an open source project so have mercy on me :D

**Comment by vbojan** [comment]
I discovered a similar issue with Composer v1.2.1 where current composer.json looks like this:
```json
{
    "require-dev": {
    },
    "require": {
        "monolog/monolog": "1.0.*"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/xyz"
        }
    ]
}
```

I run this:

```php
php composer.phar config repositories.foo vcs https://github.com/xyz
```

Composer modified composer.json, so it looks like this:
```json
{
    "require-dev": [],
    "require": {
        "monolog/monolog": "1.0.*"
    },
    "repositories": {
        "0": {
            "type": "vcs",
            "url": "https://github.com/xyz"
        },
        "foo": {
            "type": "vcs",
            "url": "https://github.com/xyz"
        }
    }
}
```

The good part is that it automatically converted repositories to object and appended "0" to existing VCS repository.
BUT it also converted "require-dev" from object to array producing an invalid composer.json:
```php
  [Composer\Json\JsonValidationException]
  "./composer.json" does not match the expected JSON schema:
   - require-dev : Array value found, but an object is required
```

I guess it's related to this issue: https://github.com/composer/composer/issues/3543 and Jordi's comment:
> ... If it changed that it means it failed to insert the new requirement "softly" and had to re-encode the whole file. The bug needs to be fixed when re-encoding but maybe I can also solve a bug in the soft-transformer...

I upgraded to Composer v1.2.2 (2016-11-03 17:43:15) and the issue persists.

I've searched through existing issues and this one appears to be the closest.
Let me know if I should create a new issue in case you don't want to re-open this one.

**Comment by Seldaek** [comment]
@vbojan this is a double edge case really because you transition from array to object on the repos, and you have an empty require-dev key which means it gets turned into an array. If you had anything in it it'd be fine. Not sure it's worth fixing, but if you care enough about it then please create a new issue.
