### ISSUE TITLE
Plugin API - Hard to setup a testing environment

### ISSUE THREAD

**Issue by evert** [composer/composer#2610]
I'm looking at writing a composer plugin, but so far I've hit a rather silly stumbling block.

I want to create a little test environment that allows me to test my new plugin. The intention is to add a custom command to the composer cli. I'm not yet sure if composer plugins can do this. I didn't get that far.

The problem is that it's hard to get a testing environment up and running. Plugins are loaded only when they are dependencies. So I wanted to get a simple composer instance up and running for easy testing.

The relevant bits look like this:

```php
// run the command application
$application = new Application();

$composer = $application->getComposer();
$pluginManager = $composer->getPluginManager();
$pluginManager->addPlugin(new MyPlugin());

$application->run();
```

This does not work ;)

`$application->getComposer()` requires `$application->io` to be initialized. This property gets initialized in `$application->run()`.

This leaves me with a chicken and egg situation. Plugins must be loaded before running the application, but the application must be started before I can add plugins.

I would propose setting up the `$io` property in the constructor, and therefore remove the $input and $output arguments from run() and doRun().

Or add a getter for $io, which automatically initializes a default ConsoleIO the first time it's called.

**Comment by Seldaek** [comment]
For commands registration see #2761 and #3377 - as for the dev environment for plugins I think the `path` repo now serves this purpose quite well so closing.
