### ISSUE TITLE
`composer global require` is not able to set minimum stability option

### ISSUE THREAD

**Issue by Hywan** [composer/composer#2611]
Hello :-),

Is there any reasons that `composer global require` is not able to set the minimum stability option? I didn't find any mention in the documentation and I don't even know if it is possible.

Thank you!

**Comment by nelson6e65** [comment]
This is old, but I got here by **Google** search... It should be pointed that in the currently composer version, `v1.4.2`, you can run the following command to perform this:

```sh
composer global config minimum-stability dev # Sets minimum-stability to "dev"
```
