### ISSUE TITLE
Add new configuration parameter "repositories-dev" to compliment "require-dev"

### ISSUE THREAD

**Issue by df-jablan** [composer/composer#2619]
My use case is as follows:

I'm developing a supplemental library for an existing system. The existing system relies on the PEAR repository, and therefore requires a PEAR entry in my `repositories` (which is god-awfully slow to load...). 

However, when the new package is installed into the existing system, there is no need for the PEAR repository entry, much like there will be no need for the packages defined in `require-dev`.

My thought was that a new section called `repositories-dev` that would be ignored if the `--no-dev` option was used when installing/updating a package. Essentially, it would be the `repositories` section to be used by the packages defined in the `require-dev` section. If `--no-dev` was used, these repositories would be ignored. Obviously, the any existing `repositories` would be recognized and utilized in all installations/updates.

Make sense?

**Comment by tarekadam** [comment]
@df-jablan Great request.  Would be so helpful when dealing with repo type=path and type=vcs.  Wish they understood.

**Comment by Benew** [comment]
@tarekadam exactly my use case. I can't commit my composer.json and composer.lock because of this. I'm using a symlinked package in dev and a vcs repository in prod.
@Seldaek @stof don't you think this is legit ? Do you have a workaround this?

**Comment by daison12006013** [comment]
@Seldaek shouldn't we consider @armellarcier's comment? By switching if the `path` exists and ignore the `vcs`
