### ISSUE TITLE
Support private BitBucket repos via API (was: Bitbucket repo's don't seem to be loaded from cache)

### ISSUE THREAD

**Issue by AydinHassan** [composer/composer#2635]
Hi I've got a few private Bitbucket repositories I'm using in a project. I am using them by adding the repositories to my composer.json file like so:

    {
        ...
        "require": {
            "jhhello/some-package": "1.0.0"
        },
        ...
        "repositories": [
            {
                "type": "vcs",
                "url": "git@bitbucket.org:jhhello/some-package.git"
            }
        ],
    }

If I remove the package from my vendor directory and run `composer update` composer will clone it again. This can't be said for Github packages where I think a zip of the tag is downloaded and cached. 

Bitbucket does support downloads of tags like Github, (I think).

So I think this is kinda two questions:
1. Why isn't the cahced repository loaded when updating a Bitbucket repository?
2. Does composer not support dist downloading from Bitbucket?

I can see the cached repository in my `.composer/cache/repo/git-bitbucket.org-jhhello-jh-magento-composer-autoloader.git` cache but Composer still clones it freshly:

![composer-nocache](https://f.cloud.github.com/assets/2817002/2004132/6613c042-869a-11e3-82f4-aa217f09f04f.png)

Whereas a Github project successfully installs from cache when removed from the vendor directory: 

![composer-cache](https://f.cloud.github.com/assets/2817002/2004133/7cc2a7cc-869a-11e3-81b9-2da7fc96a04c.png)

The only reason I brought this up is because some of these packages I am using are quite large and are used in multiple projects at the same time and it would save a lot of time for us being able to load from cache as a lot of these packages will never change.

Thanks!

**Comment by ezekg** [comment]
@Seldaek are private BitBucket repos still not supported? My team just moved all of our projects over from GitHub, and now all of our deployments are broken because the `composer.lock` file replaces our SSH urls defined in our `composer.json` with HTTPS urls. If it didn't do that, everything would work fine (as it works when edited manually, as long as we have SSH keys set up).

**Comment by tonivdv** [comment]
@ezekg  Not sure what you're doing, but we use private repos in bitbucket too and it works perfectly. This post is more about supporting caching for private repos.

**Comment by Seldaek** [comment]
We have bitbucket support now so closing, although it might be broken but there are other issues discussing this already.
