### ISSUE TITLE
Pool::isPackageAcceptable optimisation breaks whatProvides() in Problem class

### ISSUE THREAD

**Issue by naderman** [composer/composer#2661]
The problem class uses the following code to inform the user that a package with a particular name does not exist at all. However since we no longer even load packages into the pool which cannot be useful in solving the dependency question (via `isPackageAcceptable`), `whatProvides` will incorrectly return no results, even if the package exists but was skipped when adding the repository.

                if (!$this->pool->whatProvides($job['packageName'])) {
                    return "\n    - The requested package ".$job['packageName'].' could not be found in any version, there may be a typo in the package name.';
                }

We should probably keep around a simple list of names of all packages for errors, or provide a mechanism to retroactively search all repositories in an error case.

**Comment by starrychloe** [comment]
This is broken again: http://stackoverflow.com/questions/36818363/composer-is-broken-class-fxp-composer-assetplugin-repository-npmrepository-does

I'm using fxp/composer-asset-plugin (v1.1.4) and Composer version 1.0.2 2016-04-21 12:30:18.

**Comment by starrychloe** [comment]
Had to remove `vendor/` and `composer.lock` and `~/.composer`, then re-install `fxp/composer-asset-plugin` globally, then `composer install` would work.

http://stackoverflow.com/a/36672628/148844
