### ISSUE TITLE
composer status doesn't show dependencies with new files

### ISSUE THREAD

**Issue by Lumbendil** [composer/composer#2664]
When calling `composer status`, if you have added new files but haven't modified any, it'll show `No local changes`. I think it should show the directories where you have added files, in addition to those where you have edited files, to ease up working with code in the vendor folder.

**Comment by PowerKiKi** [comment]
I agree with @Lumbendil ``composer status`` should show something if new files were added. It makes it much easier to see if a package was tempered with.

@Seldaek do you have any specific package in mind that create files ?

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/commit/b31052fcdec1e17a50475ac17d0c23d3a263392f
