### ISSUE TITLE
Missing options: key, name, region, secret.

### ISSUE THREAD

**Issue by stewarty** [composer/composer#2692]
Hi There,

I'm having a little issue with composer installed globally.

Running any composer command results in - 

```
Missing options: key, name, region, secret.
```

OSX 10.9.1 & PHP 5.4.17

**Comment by noxidsoft** [comment]
Yup, I get this error when following composer portal's own documentation, would be great if it was fixed? Running MacBook Pro Yosemite 10.10.3. https://getcomposer.org/doc/00-intro.md

**Comment by patrick-wc** [comment]
Reinstalling composer globally fixed this for me. Instructions for Windows Subsystem Linux WSL https://www.jeffgeerling.com/blog/2018/installing-php-7-and-composer-on-windows-10-using-ubuntu-wsl
