### ISSUE TITLE
More useful AutoloaderInit class.

### ISSUE THREAD

**Issue by donquixote** [composer/composer#2699]
Currently the AutoloaderInit class has one method that does everything: Create a class loader and initialize it.

It would be useful to split it up.
Why?
So that if you have two instances of Composer, they can still use the same class loader instance.

```php

    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInit92462a247bf83504e990c5f706f228cc', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader();
        spl_autoload_unregister(array('ComposerAutoloaderInit92462a247bf83504e990c5f706f228cc', 'loadClassLoader'));

        self::initLoader($loader);
        return $loader;
    }
  
    public function initLoader(ClassLoader $loader)
    {
        $vendorDir = dirname(__DIR__);
        $baseDir = dirname(dirname($vendorDir));
        [..]
    }
```

Here is a use case:
https://drupal.org/comment/8477867#comment-8477867

The idea here is to have two instances of Composer running. One with the elementary packages for Drupal core, and another for packages that are needed by enabled modules, which might be updated at runtime when the other stuff is already available.

I don't think Composer should waste too much attention on a use case like this, but the suggested change looks fairly simple and reasonable..

(of course, while saying that, I realize it involves changing of a bunch of test cases etc)

**Comment by Seldaek** [comment]
Doesn't seem to be that needed after all so closing.
