### ISSUE TITLE
Allowed memory size of 536870912 bytes exhausted

### ISSUE THREAD

**Issue by tkensiski** [composer/composer#2704]
tkensiski$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 64 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Rule.php on line 50

Did a composer self-update and issue still remains.
Heres my composer.json http://pastebin.com/dcmvPJNw

Let me know anymore info you need

Also on another note its been taking forever for it run updates and installs lately.

Mac 10.9
PHP 5.5.9 (cli) (built: Feb 10 2014 13:12:02)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies

**Comment by ckahle33** [comment]
@lerox +1

**Comment by murum** [comment]
@lerox +1, a big thanks to you!

**Comment by VolodymyrChornohal** [comment]
thanks)

**Comment by LuiggiMS** [comment]
Thanks ! :D

**Comment by bartfeenstra** [comment]
I have an up-to-date Composer install, but sometime during week I started getting memory issues. I can't even install https://gist.github.com/ anymore with a PHP memory limit lower than 1024MB. Without the Behat dependency I couldn't even install with 512MB (there were around 10 resolved dependencies then).

Is this an expected change, or is this a bug? If the latter, what other details should I provide that can be useful?

**Comment by stevemind** [comment]
Bonjour,

J'ai des problèmes avec 1&1 sur mes Wordpress :

http://www.aubeuf-hacquin-yoann.fr/
http://www.stevemindmagicien.fr/
http://www.evenements-animations-artistiques.fr/

voici l 'erreur :
Fatal error: Out of memory (allocated 82051072) (tried to allocate 32 bytes) in 

Pouvez vous m'aider à optimiser mes wordpress avec le php.ini + techniques ?

**Comment by kabylzki** [comment]
@lerox : It didn't help ... just said : "You are already using composer version eadc167b121359986f542cc9cf976ecee3fcbf69."

And when i tried to update again I had the same problem.

**Comment by ramcorreio** [comment]
+1
See erro below
Reading C:/Users/Rodrigo/AppData/Local/Composer/repo/http---packagist.org/provider-kriswallsmith$spork.json from cache
PHP Fatal error:  Out of memory (allocated 2001993728) (tried to allocate 24 bytes) in phar://C:/wamp/bin/composer/composer.phar/src/Composer/DependencyResolver/RuleWatchNode.php on line 41

Fatal error: Out of memory (allocated 2001993728) (tried to allocate 24 bytes) in phar://C:/wamp/bin/composer/composer.phar/src/Composer/DependencyResolver/RuleWatchNode.php on line 41

php -v
PHP 5.3.13 (cli) (built: May  8 2012 18:50:09)
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies

php -r "echo ini_get('memory_limit').PHP_EOL;"
3G

**Comment by Balancer** [comment]
Same error with latest composer:
```
$ composer update
Loading composer repositories with package information                                Updating dependencies (including require-dev)         PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 32 bytes) in phar:///home/balancer/bin/composer/src/Composer/DependencyResolver/Decisions.php on line 78

Fatal error: Allowed memory size of 3221225472 bytes exhausted (tried to allocate 32 bytes) in phar:///home/balancer/bin/composer/src/Composer/DependencyResolver/Decisions.php on line 78
```

**Comment by ByScripts** [comment]
Same problem here. Same problem here with 1G limit. I had to run `php -d memory_limit=-1 composer install`

Way to much memory used I think.

**Comment by alanchavez88** [comment]
Where is the issue happening? If someone can point me to the right direction I'll be more than happy to volunteer my time and try to fix it. Right now, this is a roadblock in my deployment process, and running it with `php -d memory_limit-=1` is only but a temporary solution.

**Comment by devsdmf** [comment]
Hello everyone, same problem here in OSX when I try to update my project dependencies, here's some useful information:

PHP version:
```
PHP 5.6.13 (cli) (built: Sep 27 2015 14:21:35) (DEBUG)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
memory_limit => 1024M => 1024M
```

My composer.json (I removed some informations because it's a company project):
```json
{
    "autoload": {
        "psr-0": {
            "": "src/"
        }
    },
    "require": {
        "php": "~5.6",
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "1.0.*",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "symfony/symfony": "2.3.*",
        "symfony/dependency-injection": "2.3.*",
        "symfony-cmf/routing-bundle": "dev-master",
        "sensio/distribution-bundle": "~2.3",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "sensio/generator-bundle": "~2.3",
        "incenteev/composer-parameter-handler": "~2.0",
        "knplabs/knp-menu-bundle": "~2",
        "slice/http": "~1.1.5",
        "devsdmf/datamonkey": "~1.1",
        "zendframework/zend-cache": "~2.0",
        "sebastian/money": "~1.3",
        "mandrill/mandrill": "~1.0",
        "mercadopago/sdk": "^0.3.4"
    },
    "require-dev": {
        "dvelopment/firephp-bundle": "dev-master",
        "phpunit/phpunit": "~4.8",
        "fabpot/php-cs-fixer": "~0.5"
    },
    "minimum-stability": "stable",
}
```

The installation log:
```
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted at /private/tmp/php5620150927-5620-aztyv6/php-5.6.13/Zend/zend_objects_API.c:118 (tried to allocate 67108864 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php on line 214
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/composer:0
PHP   2. require() /usr/local/bin/composer:25
PHP   3. Composer\Console\Application->run() phar:///usr/local/bin/composer/bin/composer:43
PHP   4. Symfony\Component\Console\Application->run() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:82
PHP   5. Composer\Console\Application->doRun() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   6. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:147
PHP   7. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   8. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP   9. Composer\Command\UpdateCommand->execute() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
PHP  10. Composer\Installer->run() phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:143
PHP  11. Composer\Installer->doInstall() phar:///usr/local/bin/composer/src/Composer/Installer.php:232
PHP  12. Composer\DependencyResolver\Solver->solve() phar:///usr/local/bin/composer/src/Composer/Installer.php:522
```

Thanks for the support!

**Comment by referenceurseo** [comment]
Bonjour,
J'ai des problèmes avec 1&1 sur mes Wordpress :
CMS Wordpress Developpement : http://www.cms-wordpress-developpement.fr/
Magiciens Mentalistes Paris 75 ile de France : http://www.magiciens-mentaliste.paris/
Consultant Referenceur SEO paris 75 : http://www.consultant-referenceur-seo.paris/
Strategie Marketing Paris 75 : http://www.strategie-marketing-digital.fr/
Creation Applications mobiles paris 75 : http://creation-applications-mobiles.fr/
voici l 'error :
Fatal error: Out of memory (allocated 82051072) (tried to allocate 32 bytes) in
Pouvez-vous m'aider à optimiser mes WordPress avec le php.ini + techniques ?

**Comment by jbenoit2011** [comment]
I've encountered an memory limit issue. I have got  the same error callstack as @devsdmf pasted [here](https://github.com/composer/composer/issues/2704#issuecomment-151567084)
Disabling Xdebug did not help me to workaround the bug.

@referenceurseo GitHub is not intended to advertise your websites.
And, if you have questions about Wordpress optimization, first of all read Wordpress Codex and various blog around the web, then the PHP documentation.

**Comment by curry684** [comment]
@devsdmf I cannot reproduce your issue with the supplied composer.json:

    [132.2MB/34.55s] Memory usage: 132.18MB (peak: 525.07MB), time: 34.55s

525MB is a lot but not excessive given that you're depending on quite a lot of (semi-)outdated packages, that complicates the solving process a lot. Also I am running xdebug on my dev machine.

If you or @jbenoit2011 still have this issue please run the offending command with profiling and maximum verbosity, for example `composer install --profile -vvv`, and share the output and a `composer.json` that can reproduce it for us in a [Gist](https://gist.github.com/).
