### ISSUE TITLE
Open SSL Issue - Error : "You must enable the openssl extension to download files via https"

### ISSUE THREAD

**Issue by evivz** [composer/composer#2713]
Hi,
I am trying to run composer install on Windows 8.1 for laravel.

I am running AMPPS server for php.

Can anybody help me to sort this issue out?

I have installed OpenSSL and have also un-commented extension=php_openssl.dll  from php.ini.

Thanks

**Comment by bagedi** [comment]
Ampps have 2 ini files in php 5.5: php.ini-production & php.ini-development and no *.ini so decide what to use then start installation install package of Composer looking for "php_openssl.dll"  in root  C://PHP/...  so must create C:\PHP\ & copy all from C:\Ampps\php-5.5\ext\ new php folder in my root dir. and select from Ampps dir. php 5.5 all goes well and it's working fine ...

**Comment by mdrodgers97** [comment]
Thanks, Bagedi. I was stumped with this for hours and your answer solved my problem.

**Comment by kingjamesegun** [comment]
@bagedi pls I don't get you
