### ISSUE TITLE
[Composer\Downloader\TransportException]

### ISSUE THREAD

**Issue by eddiejaoude** [composer/composer#2724]
Composer update fails & has worked fine up until yesterday (18th Feb 2014). Composer install still works

```
> php composer.phar update
[Composer\Downloader\TransportException]
  The "https://api.github.com/authorizations" file could not be downloaded (HTTP/1.1 422 Unprocessable Entity)
```

Note: Install works fine

```
> php composer.phar diagnose
Checking platform settings: FAIL

The xdebug extension is loaded, this can slow down Composer a little.
Disabling it when using Composer is recommended, but should not cause issues beyond slowness.
Checking git settings: OK
Checking http connectivity: OK
Checking composer.json: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking composer version: OK
```

In the Github channel on IRC, they said composer is sending the wrong parameters?

**Comment by terbooter** [comment]
Why this bug closed?
**It still doesn't fixed!**
```Bash
root@2ef711112b83:/app# composer --version
Composer version 1.0-dev (a32c91914558a3ff293d83f7b99c49f4a7931798) 2015-04-18 18:11:12
root@2ef711112b83:/app# composer install --prefer-source --no-interaction
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
  - Installing sebastian/version (1.0.4)
    Cloning a77d9123f8e809db3fbdea15038c27a95da4058b

  - Removing sebastian/environment (1.2.2)
  - Installing sebastian/environment (1.2.1)
    Downloading: Connecting...

                                             
  [Composer\Downloader\TransportException]   
  Could not authenticate against github.com  
                                             
```

**Comment by dodwmd** [comment]
Because this wasn't covered and if you don't know you need a oauth token to access certain repo's on github. To add this you need to create a auth.json file in ~/.composer/ with 600 mask. The file should look like the following:

~/.composer/auth.json
{
    "github-oauth": {
        "github.com": "some_random_key_get_from_account_on_github"
    }
}

**Comment by AlNahari** [comment]
locate cacert.pem

vi /usr/local/lib/php.ini

#add this

openssl.cafile=/usr/local/share/perl5/Mozilla/CA/cacert.pem

#esc 
:wq #enter

curl -sS https://getcomposer.org/installer | php -- —version=1.0.0-alpha10

mv composer.phar /usr/local/bin/composer

alias composer='/usr/local/bin/composer'

composer -V

php /usr/local/bin/composer global self-update

cd .composer/
composer init

**Comment by daniele-orlando** [comment]
My **Travis-CI** builds fail randomly due to this problem.

**Comment by feeekkk** [comment]
+1 RE my travis-ci build failing now with this error

**Comment by donatj** [comment]
My Drone CI builds started failing this way today inexplicably. The PHP 7.0.1 builds are fine, but the 5.5.30 builds all started spitting 
```
 [Composer\Downloader\TransportException]   
  Could not authenticate against github.com  
```

**Comment by curry684** [comment]
This issue was closed as the core issue at hand was resolved. If issues still remain we should consider them new bugs to be investigated, so please open a new issue with full details. Posting in a closed issue with just "I still have an issue" without details does not get attention.

**Comment by Seldaek** [comment]
@zq597950 please see #6342 about content-length mismatch, this issue is unrelated and closed for ages.
