### ISSUE TITLE
[Solver] If php extension was the problem suggest to check php.ini file

### ISSUE THREAD

**Issue by stloyd** [composer/composer#2756]
When Composer checks the loaded PHP extensions it uses CLI, but when the extension is not found it can lead to confusion for end users as ~~always~~ most of time CLI uses different `php.ini` file than webserver.

IMO if there is problem, that solver couldn't find the PHP extension, it should give a hint to user, that he should look into `php.ini` file used by CLI (with location of it).

Refs https://github.com/guzzle/guzzle/issues/575.

**Comment by michallohnisky** [comment]
:+1:

**Comment by seyfer** [comment]
Looks good
