### ISSUE TITLE
Cannot install PHPUnit 3.7 with Composer

### ISSUE THREAD

**Issue by sebastianbergmann** [composer/composer#2757]
Something broke somewhere and now I cannot install PHPUnit 3.7 with Composer anymore (4.0 and 4.1 work fine). Do you have an idea what's going on here?

    $ php composer.phar --version
    Composer version 234be0b5e31b2e590c69824ac7239b185e42360c 2014-02-24 11:49:09

    $ php composer.phar install
    Loading composer repositories with package information
    Initializing PEAR repository http://pear.php.net
    Installing dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - Installation request for pear-pear/pear 1.9.4 -> satisfiable by pear-pear.php.net/PEAR[1.9.4].
        - pear-pear.php.net/PEAR 1.9.4 required pear-pear.php.net/archive_tar >=1.3.7.0 -> no matching package found.

    Potential causes:
     - A typo in the package name
     - The package is not available in a stable-enough version according to your minimum-stability setting
       see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

    Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by Seldaek** [comment]
Closing as it seems nobody cares enough to fix this, and PEAR is really on the way out at this point anyway. Most pear.php.net PEAR packages are on packagist already or will be added as necessary.

**Comment by glensc** [comment]
I care for a fix, but obviously I can not pressure anyone to make the fix.

Non-active PEAR packages are not packagist, and users of such packages are left in the dark.

**Comment by xabbuh** [comment]
@glensc If such packages are not actively maintained anymore, imho it' a better idea to find someone who takes over the maintenance. It's not unlikely that those packages do require other updates as well.

**Comment by glensc** [comment]
I should rather move away from abandoned packages, but until then don't want extra obstacles to use the existing versions.
