### ISSUE TITLE
Github protocols

### ISSUE THREAD

**Issue by middric** [composer/composer#2786]
It seems that the github-protocols command does not work when repository type is set to "vcs". The code here 
https://github.com/composer/composer/blob/master/src/Composer/Downloader/GitDownloader.php#L315 does a regex test which must pass in order to set the protocol you wish to use. However the URL it checks against is always in the git@github.com.... format rather than git:// or https://. Setting the repository type to "git" solves the problem, but then I get issues authenticating with github for private repos.

My composer.json (repo name changed - its private anyway):
```json
{
    "name": "middric/middric",
    "license": "proprietary",
    "version": "1.4.0",
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/middric/middric.git"
        }
    ],
    "require": {
        "middric/middric": "dev-composer-test"
    },
    "config": {
       "github-protocols": ["https"]
    }
}
```

**Comment by Seldaek** [comment]
Took a while sorry, but now ` "github-protocols": ["https"]` should bypass the first `git@` attempt for private github repos. Hopefully you can confirm this helps but maybe you have worked around this by now.
