### ISSUE TITLE
Error running Composer Installer on Windows

### ISSUE THREAD

**Issue by fernando1419** [composer/composer#2799]
Getting error 
"Composer Error [ERR_STATUS]: Unexpected exit code from Composer (255)" while installing composer for laravel framework from https://getcomposer.org/Composer-Setup.exe

**Comment by GameXG** [comment]
I encountered the same problem

D: \ xampp \ php>
D: \ xampp \ php> php -r "readfile ( 'https://getcomposer.org/installer');" | php

D: \ xampp \ php> php -r "readfile ( 'https://getcomposer.org/installer');" | php

D: \ xampp \ php> php -r "echo getenv ( 'APPDATA');"
C: \ Users \ GameXG \ AppData \ Roaming
D: \ xampp \ php>

XAMPP v3.2.2
windows 10 x64

**Comment by GameXG** [comment]
PHP version 5.6.15
      D:\xampp\php\php.exe

Add to System path variable:
      D:\xampp\php

Add to System path variable:
      C:\ProgramData\ComposerSetup\bin

Shell Menus: 
      Do not install

Composer Error [ERR_STATUS]: Unexpected exit code from Composer (-1073741819)

**Comment by curry684** [comment]
-1073741819 is hexcode `0xC0000005`, the Windows global error code [`E_ACCESS_VIOLATION`](http://blogs.msdn.com/b/calvin_hsia/archive/2004/06/30/170344.aspx). PHP code can never cause that unless PHP itself is corrupted. I would recommend reinstalling XAMPP, good reason to upgrade to the PHP 7 versions too.

**Comment by GameXG** [comment]
@curry684 Thank you very much, reinstall xampp this error no longer occurs.
