### ISSUE TITLE
With *.tar.xz format not work ;(

### ISSUE THREAD

**Issue by samokspv** [composer/composer#2804]
Can't extract .tar.xz format
<code>
{
"type": "package",
"package": {
"name": "wkhtmltopdf2/wkhtmltopdf2",
"version": "0.12.0",
"dist": {
"url": "http://downloads.sourceforge.net/project/wkhtmltopdf/0.12.0/wkhtmltox-linux-amd64_0.12.0-03c001d.tar.xz",
"type": "tar"
}
}
}
</code>

<code>
composer update --no-dev
</code>
<code>
Loading composer repositories with package information
Updating dependencies
  Installing wkhtmltopdf2/wkhtmltopdf2 (0.12.0)
    Downloading: 100%
[UnexpectedValueException] 
internal corruption of phar "/var/www/test.dir.dev/vendor/wkhtmltopdf2/wkhtmltopdf2/6f9b4ecfd1a68d66942c056e93ea34f0.xz"  
(__HALT_COMPILER(); not found)
</code>

**Comment by Seldaek** [comment]
There's now support for `"type": "xz"` to extract xz files.
