### ISSUE TITLE
No vendor binaries are installed at all if package defines a bin-stub

### ISSUE THREAD

**Issue by chr0n1x** [composer/composer#2807]
I have a package with a file, `bin/stub`. In my `composer.json` I have `{ "bin": "bin/stub" }`. This package also requires phpunit.

When I composer install/update, there is no `vendor/bin`, let alone a `vendor/bin/phpunit`.

Not sure if intended or not. This is on release alpha8

**Comment by Seldaek** [comment]
That bin config is invalid, current composer shows this:

```
  [Composer\Json\JsonValidationException]
  "./composer.json" does not match the expected JSON schema:
   - bin : String value found, but an array is required
```

Once fixed to be an array, all seems to be well. Closing this.
