### ISSUE TITLE
Inconsistent state

### ISSUE THREAD

**Issue by Bilge** [composer/composer#2816]
Every time `composer update` is run with the following `composer.json` file it installs different packages.

On first run it installs `symfony/symfony` even though this is not required in any of the definitions and does not satisfy all of the dependencies.

On the next run it removes `symfony/symfony` and replaces it with `symfony/dom-crawler` and `symfony/css-selector` as requested. This is the only valid state.

Every subsequent run toggles it between these two states. That is, if run again, it removes `symfony/css-selector` and `symfony/dom-crawler` and replaces them with `symfony/symfony` again.

Despite how big this `composer.json` is, I've tried to slim it down as much as possible. It does not happen if I remove the reference to my vcs repo, remove Monolog or remove Twig. It seems as if there's a three-way tug-of-war going on somewhere.

```
{
        "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/Bilge/mongodb-odm"
        }],
        "require": {
                "zendframework/zendframework": "2.2.1",

                "doctrine/mongodb-odm": "*@dev",
                "doctrine/doctrine-mongo-odm-module": "*",

                "twig/twig": "1.*",

                "monolog/monolog": "1.*"
        },
        "require-dev": {
                "symfony/dom-crawler": "*",
                "symfony/css-selector": "*"
        }
}
```

**Comment by Seldaek** [comment]
Closing as tbh this doesn't seem to be a common issue
