### ISSUE TITLE
Investigate git 1.9 shallow repo support improvements

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#2833]
Repos created with --depth can now be worked with, so it may be an option to clone dev-master versions with --depth 1 and then check the commit hash and then fetch if the hash is not the latest, but it may not make any sense if we consider that an update will fetch anyway. Needs testing.

**Comment by ogmueller** [comment]
Any news on that one?

**Comment by Seldaek** [comment]
Duplicate of #3449
