### ISSUE TITLE
Parallel download of dist archives

### ISSUE THREAD

**Issue by h4cc** [composer/composer#2847]
When using dist files for downloading, it would be very cool to have a parallel download of these archives.

Is there any chance to add such a feature?

**Comment by Koc** [comment]
is #7904 closes this issue?

**Comment by stof** [comment]
@Koc no. That one implemented parallel downloading inside the Composer repository, which is a place managing a bunch of downloads on its own.
Supporting parallel downloading of archives requires refactoring the InstallationManager (as the current API deals with only 1 download at a time). I think this will be done only after the refactoring of the solver architecture is completed. Lower-level APIs of the downloaders have already been prepared for the parallel downloading in #7904 though.

**Comment by Seldaek** [comment]
Fixed by 006985a0ea7135408d9760125a74d862c17409cb
