### ISSUE TITLE
Cannot Resolve Host: getcomposer.org

### ISSUE THREAD

**Issue by gutensite** [composer/composer#2854]
Perhaps the public wifi I'm on is blocking this site somehow, but I can't access the website or server via command line, e.g.:

Command: curl -sS https://getcomposer.org/installer | php
Results in: curl: (6) Could not resolve host: getcomposer.org

Is this just me?

**Comment by BallisticPain** [comment]
I'm having this happen in my docker container but I can ping it outside the container... :(

**Comment by stof** [comment]
@BallisticPain then it means that the bug is in your docker setup, not in the composer DNS setup

**Comment by BallisticPain** [comment]
@stof Thanks! I figured it out and yes I simply had to re-build my docker and all was well. This job is my first experience with docker so I'm learning.

**Comment by honey-HL** [comment]
I got this error too
