### ISSUE TITLE
`update` keeps switching between repositories/commits

### ISSUE THREAD

**Issue by rjkip** [composer/composer#2860]
We're switching back from a fork of Imagine to the original repository. We have our fork referenced in a private Composer repository. To integrate the original Imagine back into our software, I added the original as a VCS repository. Basically, Composer now knows Imagine from Packagist, then from our fork in our private Composer repository and then again from the original.

When `composer update`-ing to `0.6.*@dev`, Composer keeps switching between the fork and the original as seen below. My expectation is that it picks the last repository (original VCS).

To reproduce the problem use the below configuration. I replaced the private Composer repository with a VCS reference. It's not the exact same situation, but the problem is reproduced.

``` json
{
    "name": "composer/composer-update-switches",
    "repositories": [
        { "type": "vcs", "url": "https://github.com/reprovinci/Imagine" },
        { "type": "vcs", "url": "https://github.com/avalanche123/Imagine" }
    ],
    "require": {
        "imagine/Imagine": "0.6.*@dev"
    },
    "minimum-stability":"stable"
}
```

``` shell-session
[user@host composer-switch]$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Updating imagine/imagine dev-develop (e0c1de0 => 2ab2237)
    Checking out 2ab2237f2445ea30fdf00fdd2ff4f2d8072e87ec

Writing lock file
Generating autoload files
[user@host composer-switch]$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Updating imagine/imagine dev-develop (2ab2237 => e0c1de0)
    Checking out e0c1de0ec91f9e7073068500357d7374b73a7607

Writing lock file
Generating autoload files
```

[I've included verbose output in this gist](). The update output was generated using `composer update -vvv --no-ansi`.

**Comment by Seldaek** [comment]
Closing as very old..
