### ISSUE TITLE
Running composer in a jailkit chrooted environnement

### ISSUE THREAD

**Issue by alexdruhet** [composer/composer#2867]
Hi, I'm trying to install composer for my ISPConfig 3 chrooted users on a Debian Wheezy, without suceeded. 
My first attempt was to install it globally : 

``` shell
$ curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/share
$ mv /usr/share/composer.phar /usr/local/bin/composer
$ chgrp staff /usr/local/bin/composer
```

Then I've added following conf in /etc/jailkit/jk_init.ini :

```
[php]
comment = the php interpreter
executables = /usr/bin/php, /usr/bin/php5
directories = /usr/share/php, /etc/php5/, /etc/snmp, /usr/share/mibs, /usr/share/snmp
includesections = extendedshell

[mysql-client]
comment = mysql client
executables = /usr/bin/mysql

[composer]
comment = Dependency Manager for PHP
executables = /usr/local/bin/composer
directories = /usr/share/composer
includesections = php 
```

After, I creates a new website with a new ssh user (chrooted with jailkit, of course). I log in without any problems and I can see composer has an available command. The problem is here : calling composer is doing nothing at all, no response, no error, no log, no traces, nada, absolument rien...

So I've test the env, creating a small php executable:

```
#!/usr/bin/env php
<?php
phpinfo();
?>
```

I call it : 

```
$ ./test_php
```

And it returns php informations, there's no problem here...

I have also tried to install it locally. Composer.phar is downloaded, I call it:

```
php composer.phar
// or
php composer.phar diagnose
```

And I obtain also absolutely nothing...

Does somebody have experience with this kind of installation ? I'm blocked, any help is welcome !
Thanks

**Comment by fulopattila122** [comment]
I don't exactly know how many more hours did you save for me, but I've been sending at least 2 so far.. Same here with Plesk chroot, and your solution just works.

**Comment by skonsoft** [comment]
@Pixopat : Thank you ! it works for me :+1:

**Comment by iRbouh** [comment]
The solution for me was editing the jailkit.ini file and add a section for PHP at the end of the file:
Open the jk_init.ini file with an editor:

`nano /etc/jailkit/jk_init.ini`

and paste the following lines at the end of the file:

```
[php]
comment = the php interpreter and libraries
executables = /usr/bin/php5
directories = /usr/lib/php5, /usr/share/php, /usr/share/php5, /etc/php5, /usr/share/php-geshi, [B]/usr/share/zoneinfo[/B]
includesections = env

[env]
comment = environment variables
executables = /usr/bin/env
```

Then run the command:

`jk_init -c /etc/jailkit/jk_init.ini -f -k -j /var/www/clients/client1/web1 php`
