### ISSUE TITLE
Install yiisoft/yii2 

### ISSUE THREAD

**Issue by khangnguyen** [composer/composer#2873]
I have been trying to install yiisoft/yii2 with composer but haven't been successful yet.

I am using the command 
`php composer.phar require "yiisoft/yii2:*"`
and keep getting the error

```
Problem 1
    - The requested package yiisoft/yii2 could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
```

I have changed my mim stability to `dev` in composer.lock but that didn't make any change. Any idea?

**Comment by baiyulong** [comment]
U need run this

composer global require "fxp/composer-asset-plugin:~1.0.0"

The problem will be solved.
