### ISSUE TITLE
force a restart of the current operation, if a plugin gets installed/update/removed

### ISSUE THREAD

**Issue by backbone87** [composer/composer#2879]
since you can manipulate the root package, with the new plugin API, you are able to inject additional provide into the root package for example. doin this may result in a different solver solution, than this of the current run.

therefore it would be nice, if there were a possibility to restart the current operation, each time a plugin gets installed/updated/removed.

for the concrete implementation there may be used flags checked or new methods on the  plugin API to be checked, or something like a "interrupted exception" to be thrown.

**Comment by aschempp** [comment]
+1

**Comment by backbone87** [comment]
@Seldaek closed because implemented already or because its in "wont fix" state?

**Comment by Seldaek** [comment]
Yeah it's rather won't fix sorry.
