### ISSUE TITLE
installation broken, if a update/install fails after some packages were already deployed

### ISSUE THREAD

**Issue by backbone87** [composer/composer#2880]
if you update/install an installation and the process fails, when there were some packages already deployed, you end up in a broken installation, because a) there may be packages deployed that are incompatible to one or another and b) the autoload wasnt dumped.

this happens for example, when a download of a package fails due to remote network issues.

solutions:
- in short term, you may be able to separate the download process of each package and execute them before the packages are installed (download all packages, then install all packages)
- in the long run, it would be nice if the installation is done into a new "temp vendor" and after all is set and done, a rename of this "temp vendor" dir is done and the old one unlinked.

**Comment by Seldaek** [comment]
Composer 2.0 fixes this mostly by downloading everything beforehand, it is not 100% guaranteed the rest then will work but I think it's the most we're prepared to do on this front.
