### ISSUE TITLE
local package --prefer-source  option

### ISSUE THREAD

**Issue by alexey-baranov** [composer/composer#2885]
Most time interesting install my own packages with --prefer-source option to be able to modify and test them and then update remote repository from main project.

But if I use --prefere-source command line option all other packages install the same way and lose very much time/ 

Is it possible to specify few packages with --prefer-source option? Thanks!

**Comment by motin** [comment]
A workaround to achieve this is to install all packages using `--prefer-dist` first, then remove the directory of a specific few packages from under the vendor directory. Run install again but with `--prefer-source` and only the missing packages will be installed from source.

**Comment by afraca** [comment]
I just bumped into this as well, and barryvdh got me here. (Shame on me for not finding this.... ) 

Any update on this? The reasons are pretty much: dist is nice to save bandwidth and is faster, but I've got some of my own packages where it would be nice to edit them in the /vendor folder and push.

**Comment by RdeWilde** [comment]
Would like this too, can't be difiicult right, because all the functionality already exists.

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/pull/3790
