### ISSUE TITLE
SOCKS proxy support

### ISSUE THREAD

**Issue by denis-sokolov** [composer/composer#2900]
I couldn't find any mention how to make Composer work with a SOCKS proxy.
I presume Composer does not support such mode of operation.
Is there any chance it will be added?

I don't assume I know anything about how Composer works,
but based on [use of `stream_context_create`](https://github.com/composer/composer/blob/60dd4f865ff335a5c17687588077550b2be9b8cd/src/Composer/Util/StreamContextFactory.php#L119), and PHP documentation [not mentioning SOCKS](http://php.net/manual/en/context.http.php), I assume the feature is unlikely?

(Yes, I can create a tiny HTTP proxy to forward through SOCKS, but it's some extra bother)

**Comment by juanmf** [comment]
Has it been a while already? :) I can access Internet only through the -D port options of ssh

**Comment by ilanco** [comment]
I got composer to use a SOCKS proxy with `proxychains`. `tsocks` didn't work for me.

**Comment by Seldaek** [comment]
Closing as I don't see this happening anytime soon and demand isn't exactly high.

**Comment by TheAliAbbasi** [comment]
+1
same proxy issue in my country makes composer unusable

**Comment by emieza** [comment]
it wold be nice for our educational center too, to have this feature. We are behind a really strict proxy server that makes us really difficult to work with composer :(

**Comment by dstensnes** [comment]
Ability to fetch via ssh with the "-D" option would be very nice. Sometimes having that ability makes things so much easier. Our router has died at work, so we have been using ssh with the -D option as a workaround so people can actually work while we restore this router. The only stuff that is holding back this temporary workflow is composer. Socks support is a very nice feature to have when you have to access something in a slightly unusual network perspective, and the protocol itself it very simple so I don't see it going away anytime soon. If composer is using curl internally, then it should be very simple to implement as well. Can this issue please be reopened?

**Comment by cgicgi** [comment]
> 
> 
> I got composer to use a SOCKS proxy with `proxychains`. `tsocks` didn't work for me.

thx ilanco. After years (!) of struggeling with a company's proxy, proxychains is the ultimate solution for me. Works like a charm!

**Comment by alphaoumeric** [comment]
seriously though, why this can't use curl library??? why rely on openssl????

**Comment by alphaoumeric** [comment]
> We are behind a really strict proxy server that makes us really difficult to work with composer :(

I hate composer project - i just want to download and require_once only

**Comment by Seldaek** [comment]
@alphaoumeric we do use curl nowadays, so you can maybe try setting your proxy url using `socks5://` as protocol. Not sure if that's allowed internally or not..

And if you have such strict firewall maybe you should consider running a self hosted version of Private Packagist https://packagist.com/pricing/self-hosted - which your dev machines can then talk to? Maybe it helps..
