### ISSUE TITLE
probleme with curl and ssl

### ISSUE THREAD

**Issue by zimzim62000** [composer/composer#2902]
hello,

I have a fresh install on debian 7 wheezy.

I use symfony for my job so i need composer.

but i have a trouble for get the file ( composer.phar )

When i use the option -sSlv for get more information, i see the ssl connexion sleep after the first  client hello and after long time fail .

is what has happened to someone?

my config 

```
curl --version

curl 7.26.0 (i486-pc-linux-gnu) libcurl/7.26.0 OpenSSL/1.0.1e zlib/1.2.7 libidn/1.25 libssh2/1.4.2 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: Debug GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP



```

```
root@srv-dev:/tmp# curl -sSlv https://getcomposer.org/installer
* About to connect() to getcomposer.org port 443 (#0)
*   Trying 87.98.253.108...
* connected
* Connected to getcomposer.org (87.98.253.108) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
( after long time ) 
* Unknown SSL protocol error in connection to getcomposer.org:443
* Closing connection #0
curl: (35) Unknown SSL protocol error in connection to getcomposer.org:443

```

 i don't have any troubles with other https ( google, github . )

sorry for that and thanks if you can help me.

**Comment by Ritesh-Sharma** [comment]
Hi @zimzim62000 , 

Could you please  elaborate what exactly the issue was ? am facing the same issue while connecting my clients with servers .

**Comment by parisk** [comment]
Found a workaround by tweaking Docker's MTU: https://github.com/composer/composer/issues/6538#issuecomment-328311429.
