### ISSUE TITLE
How to use create-project with private repositories?

### ISSUE THREAD

**Issue by igorsantos07** [composer/composer#2920]
I've implemented a Satis repository and I'm trying to use `create-project` to startup a new system based on a skeleton package from Satis.

I've added the repository to my `~/.composer/composer.json` file, and thus `composer global search myself/skeleton` works fine and it can find the given package, even require and install it as well. That repository currently has two tags (1.0 and 1.0.1), those are showing fine in the Satis page.

However, `composer global create-project -s dev myself/skeleton` does not work. I've tried using different stability and version flags, and all those return a similar error: "Could not find package myself/skeleton with version 1.0.1", or stability etc.

How is the best way to use `create-project` with private repositories? Is there any way to use the command without issuing the `global` one first? Finally, is it a bad behaviour adding the repository in the user's `composer.json`?

**Comment by Seldaek** [comment]
You can now pass --repository which can also be a full json object including any repo option available: `{"type":"...", etc..}`
