### ISSUE TITLE
Support for packages which have a C and PHP implementation

### ISSUE THREAD

**Issue by stof** [composer/composer#2923]
Pimple will have a C implementation in its v2, being a drop-in replacement for the PHP code: https://github.com/fabpot/Pimple/pull/121

Composer should have a way to know how to deal with it. A requirement on ``pimple/pimple:~1.0`` should conflict with the extension as it implements the v2 for instance.

The clean way would be to consider that ``ext-sensiolabs_pimple`` (may become ``ext-pimple`` as the discussion just started) replaces ``pimple/pimple:self.version``. But given that an extension cannot embed informations for composer currently other than its version, it would require hardcoding such knowledge in the PlatformRepository, which does not scale well.
This also causes some issues regarding the locking of dependencies, as the lock file would have to be different based on the availability of the C extension.

**Comment by Seldaek** [comment]
Closing as in practice it doesn't seem to be very necessary or all that common.
