### ISSUE TITLE
cant install composer neither update an existing one

### ISSUE THREAD

**Issue by fmo** [composer/composer#2964]
Hello, when i try to install composer i get this error below

curl -sS https://getcomposer.org/installer | php
# !/usr/bin/env php

All settings correct for using Composer
Downloading...
Download failed: file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Operation now in progress
Downloading...
Download failed: file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Operation now in progress
Downloading...
Download failed: file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Operation now in progress
The download failed repeatedly, aborting.

and 

php -r "readfile('https://getcomposer.org/installer');" | php
PHP Warning:  readfile(https://getcomposer.org/installer): failed to open stream: Operation now in progress in Command line code on line 1
PHP Stack trace:
PHP   1. {main}() Command line code:0
PHP   2. readfile() Command line code:1

Warning: readfile(https://getcomposer.org/installer): failed to open stream: Operation now in progress in Command line code on line 1

Call Stack:
    0.0001     218664   1. {main}() Command line code:0
    0.0001     219320   2. readfile() Command line code:1

and there is in some other project 

php composer.phar update
Warning: This development build of composer is over 30 days old. It is recommended to update it by running "composer.phar self-update" to get the latest version.
Loading composer repositories with package information

  [Composer\Downloader\TransportException]
  The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: Operation now in progress

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [packages1] ... [packagesN]

and diagnose...

composer.phar diagnose
Warning: This development build of composer is over 30 days old. It is recommended to update it by running "composer.phar self-update" to get the latest version.
Checking platform settings: FAIL

The xdebug extension is loaded, this can slow down Composer a little.
Disabling it when using Composer is recommended, but should not cause issues beyond slowness.
Checking git settings: OK
Checking http connectivity: FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: Operation now in progress
Checking composer.json: FAIL
name : is missing and it is required
description : is missing and it is required
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking disk free space: OK
Checking composer version:

  [Composer\Downloader\TransportException]
  The "https://getcomposer.org/version" file could not be downloaded: failed to open stream: Operation now in progress

I am not behind at any proxy or something... and it says http connectivity FAIL...

What it would be the problem? I have checked every a bit related ticket but nothing solved the problem so far.

**Comment by liuzexin** [comment]
Thanks a lot.@jakoch
