### ISSUE TITLE
`composer install` should install newly added packages to already existent composer.json

### ISSUE THREAD

**Issue by d-ph** [composer/composer#2969]
Hello,

currently, if I want to add an another package to my project, I need to edit `composer.json` and run `composer update nameOf/Package` to install it and to regenerate `composer.lock`.

I think it's quite cumbersome, and it would be easier to just run `composer install` instead of `composer update nameOf/Package`, which should:

a) respect `composer.lock`, but also
b) be smart enough to detect, that I've just added one or more new packages to my project, which need to be downloaded and installed, but also
c) act reasonably (ie. give meaningful info and fail), when the newly added packages need newer versions of currently installed packages, which in turn are locked to older version by `composer.lock`

What do you think?

**Comment by sshymko** [comment]
Hi,

The proposed behavior of the `composer install` would be excellent for automated deployments.
Actually, it's not possible to automate running `composer require vendor/package` when deploying a project where all dependencies are declared in `composer.json` under the version control.
Could you please suggest how to install only newly added dependencies in `composer.json`.

Thanks

**Comment by xabbuh** [comment]
@sshymko You should add your composer.lock file to your VCS and then run `composer install` during deployment.

**Comment by sshymko** [comment]
@xabbuh, I think I understand what you're saying: basically, use whatever method to make the changes to `composer.json` and ultimately to `composer.lock` that are both under the VCS.

Is `composer install` going to work for a deployment algorithm that doesn't start from scratch by rather need to apply the delta to the existing environment? Or does the deployment script need to explicitly drop the `vendor` directory and run `composer install` after wards?

**Comment by d-ph** [comment]
@sshymko As long as there is `composer.lock` file around, you are guaranteed, that `composer install` will JustWorkTM . 

Try it yourself: remove a couple of deps from the `vendors` and run `composer install` again. Composer will ensure that `vendors` has exactly what's in the `.lock` file.

**Comment by sshymko** [comment]
@d-ph, yes I know, the question was how to avoid removing anything from the vendor directory separately from running the composer commands.

**Comment by xabbuh** [comment]
@sshymko You do not have to remove anything from the `vendor/` directory. Composer will update your packages if the version in the lock file differs from the installed version.

**Comment by poncianodiego** [comment]
May I suggest as well simply adding dependencies to composer.json and using `composer update`?

That has worked for me just fine.

**Comment by TangMonk** [comment]
I think composer should learn from `Bundler` and `npm`
