### ISSUE TITLE
Add plugin::deactivate() method

### ISSUE THREAD

**Issue by therealmikz** [composer/composer#3000]
I've encountered really strange behavior of composer. When custom installer is removed from dependencies, I get an error saying that its class can't be found. I may be wrong but, as far as I see in composer source, first it is registered as an installer in Composer\Plugin\PluginManager::registerPackage() and then it gets phisically removed.
Steps to reproduce:
1. Initialize empty composer.json
2. Add custom installer, In my case bug occured with robloach/component-installer 0.0.12 so the line would be:
"robloach/component-installer": "0.0.12"
3. Run composer install
4. Remove requirement
5. Run composer update
PHP Fatal error:  Class 'ComponentInstaller\Process\CopyProcess' not found in /home/mikz/temp/composerTest/vendor/robloach/component-installer/src/ComponentInstaller/Installer.php on line 160

**Comment by nevvermind** [comment]
Yeah, this happens to me, too. Not sure about a solution here.  Composer starts with a PHP class, stores its object, then deletes the PHP script, then tries to use it the class.

You can replicate going to an empty folder and running `composer require some/plugin && composer remove some/plugin`. The plugin should hook into a `post-` event.

Even if the plugin was removed from `composer.json`, Composer has no idea about this yet, and it will still register the plugin prior to actually delete it. Then the post-install/update event is triggered.

Maybe it needs to unregister a Plugin right here: https://github.com/composer/composer/blob/9fb2d4f2d642a0749decb41bc2fe4be2bf8bef7a/src/Composer/Installer/LibraryInstaller.php#L122, before actually deleting the files. But then you'll have a half-baked update process, with the plugin hooks triggering in the "pre plugin physical delete" state, and not after.

I think @therealmikz was right: we should compare `composer.json` with `composer.lock` before registering plugins. Or, to make it simpler, maybe store a separate key in `composer.lock` _just for plugin packages **and their constraints**_ and compare _that_ with what's in `composer.json`. The version constraint check is also need, as one can have a plugin version 1.x triggered pre-update, the plugin itself gets update to 2.x, the post-update hooks would be running on entirely different classes, hence the possibility of another fatal error.

**Comment by Seldaek** [comment]
If you are removing a plugin the best is to call update with --no-plugins as the plugin documentation notes for updating or uninstalling a plugin. In the future we may treat this better by adding a `PluginInterface::deactivate()` method so they get unloaded properly before being uninstalled.

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/pull/7995 for 2.0
