### ISSUE TITLE
Detect `files` autoload conflicts when a second autoloader gets called

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#3003]
Not sure if possible but should be investigated, to solve cases like https://github.com/guzzle/guzzle/issues/676

**Comment by itafroma** [comment]
What about just changing [L585 in AutoloadGenerator.php](https://github.com/composer/composer/blob/8e9659bd8317ad3f623c4d17940380443cf8772c/src/Composer/Autoload/AutoloadGenerator.php#L585) to `require_once` instead of require? We ran into this issue and making that change solved the problem.

**Comment by stof** [comment]
@itafroma this won't help to solve the issue of @PommeVerte. A global install will have a **different** file containing the same code, as you will have it installed globally and locally.

The **only** solution for that is to have a safeguard in the file checking whether functions can be defined safely (until the day we have function autoloading in PHP to be able to load them on-demand like classes)

**Comment by stof** [comment]
@samdark the content of ``autoload_files.php`` does not end up in the Composer autoloader, as the files strategy is actually not doing autoloading but preloading (and is used for cases where autoloading is not possible in PHP)

**Comment by itafroma** [comment]
@stof Perhaps it wouldn't solve @PommeVerte's issue, but it would solve the issue as originally reported. `require_once` is a construct designed for this purpose: why shouldn't Composer only `require_once` in this case?

**Comment by stof** [comment]
@itafroma the original issue is when having the same library installed globally and locally. So ``require_once`` will not solve anything here as you have 2 **different** files defining the same function.

**Comment by Seldaek** [comment]
Fixed by #4186
