### ISSUE TITLE
Getting  zlib_decode(): data error when trying to "composer install".

### ISSUE THREAD

**Issue by ghost** [composer/composer#3006]
Trying to follow the Doctrine2 tutorial on http://docs.doctrine-project.org/en/latest/tutorials/getting-started.html I ran into a problem:

```
Loading composer repositories with package information
Installing dependencies (including require-dev)
zlib_decode(): data error
http://packagist.org could not be fully loaded, package information was loaded f
rom the local cache and may be out of date



  [ErrorException]
  zlib_decode(): data error



install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-p
lugins] [--no-custom-installers] [--no-scripts] [--no-progress] [-v|vv|vvv|--ver
bose] [-o|--optimize-autoloader] [packages1] ... [packagesN]
```

After a non successful attempt at stackoverflow.com here http://stackoverflow.com/questions/23719738/zlib-decode-data-error-using-composer-in-the-doctrine2-tutorial it has been suggested that I should post this as an issue over here.

**Comment by fridoon** [comment]
Its because of slow internet and not inerupted internet.

**Comment by mslotema** [comment]
Hi,
My internet connection is pretty solid. I have this error too when using composer.

~~~
Composer version 1.0-dev (c6cc6dd6070871f4b198ed39f76dd8047c116b02) 2015-07-21
~~~

I am running composer on OSX 10.10 and PHP 5.6

Anyone know what can be wrong?

**Comment by ieatcode** [comment]
I had this error when I forgot to run composer init first
