### ISSUE TITLE
Save whether --dev or --no-dev is installed

### ISSUE THREAD

**Issue by gossi** [composer/composer#3008]
Hi,

I would like to request to save whether the install/update command is run with --dev or --no-dev option.

Background: I would like to add tooling support for this on the composer-eclipse-plugin. To add the respective (autoload or autoload-dev) into the build path, so contents are available for content assist.

Thank you very much

**Comment by dezlov** [comment]
+1 for `--no-dev` configuration flag, a must have feature.

```json
{
    "config": {
        "no-dev": "true"
    }
}
```

**Comment by Azuka** [comment]
:+1:

**Comment by lkraav** [comment]
Hopefully github improves with https://github.com/isaacs/github/issues/9 but until then +1 here

**Comment by xabbuh** [comment]
@lkraav You know that you simply can press the "subscribe" button at the right?

**Comment by lkraav** [comment]
> You know that you simply can press the "subscribe" button at the right?

Absolutely. But for some unknown reason, github doesn't let people understand the level of interest by displaying the number of people Subscribed. At the same time you only get added as visible and counted Participant once you have commented something. Complete bummer. In general +1 only on things that I really really would like to see happen.

**Comment by Seldaek** [comment]
The initial feature request is about saving in installed.json whether the last update was done as dev or not, it's got nothing to do with adding a config value for no-dev, which is not a feature I would like to include to be honest.

**Comment by fabarea** [comment]
+1 to make it configurable. `--no-dev` is easily forgettable (and must be taught) and implies a lot of unnecessary downloads.

**Comment by Seldaek** [comment]
OP could be done in 2.0 by adding `WritableArrayRepository::write($dev)` and we can store that in the file as well. Not sure if we really need this though.

As for the `no-dev` config option that's not going to happen IMO but anyway please stop discussing that here as it is an unrelated issue.

**Comment by paul-m** [comment]
+1 for storing this info in installed.json. Drupal core allows you to put your vendor directory under docroot, and we want to mitigate by warning our users so they don't have `composer install --dev` in production.

See: https://www.drupal.org/project/drupal/issues/2830880

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/pull/7999 for 2.0

**Comment by marxangels** [comment]
How ?
