### ISSUE TITLE
Allow multithreading for tasks like downloading

### ISSUE THREAD

**Issue by kaystrobach** [composer/composer#3015]
with pthreads time consuming tasks like downloading the repositories can be done in parallel instead of one after another.
I know, that not everything in composer can be done in parallel, but downloads should be doable in parallel, afterwards the dependencies can be recalculated and then the next round of downloads can be started ...

**Comment by Seldaek** [comment]
Closing as we have other issues tracking parallel downloading and so on.. multi-threading is kinda similar but not going to happen I believe.
