### ISSUE TITLE
DOC: How to develop modular application in one IDE project/folder ?

### ISSUE THREAD

**Issue by mcd-php** [composer/composer#3016]
Please create documentation page fully dedicated to development of modular application.

What if i want to start an application with framework/CMS supporting modules, and i clearly realize what my application should be split into multiple composer packages, and that packages will be valuable for community to reuse ?

How should i lay out my folders and organize my process ?
- Put packages in separate folders and then what ? Zip up with Phing and then install with `artifact` ? Git submodules ? Play push/pull with git server on developer's local machine ?
- Develop in `/vendor` ? Git submodules ? Push from under `/vendor` and then reinstall just over it ? Does `composer` warn on update if changes under `/vendor` are committed but not yet pushed ?
- Should i never do this, and always develop in fully separate projects, connected only by some kind of composer repository ? If so, for what reasons ?

**Comment by jakoch** [comment]
Extracted some additional questions for this topic from https://github.com/composer/composer/issues/2896#issuecomment-40726320
- Configuration files in the dependency tree? = (untracked working files)
   - Is it a good idea to create files in dependency tree that are specifically ignored by the vcs?
   - What would be the best way to handle configuration between a main project and its dependencies ?

**Comment by craigh** [comment]
I'm wondering if there might be a way to allow for "sub" composer.json files that are included based on a regex string for paths (like phpunit finds tests). Composer could collect any random number of composer files in addition to the "main" file and then work out dependencies, etc.

**Comment by RSully** [comment]
@Seldaek I've been out of the loop on PHP development but still watching this issue - has this been documented, and if so could you provide a link for anyone finding this issue on Google?

**Comment by Seldaek** [comment]
I merely decided to cull some old issues which don't seem like they'll ever move forward to clean things up. Sorry no good news here.
