### ISSUE TITLE
Fatal error: Access to undeclared static property: $loader in autoload_real.php

### ISSUE THREAD

**Issue by andriansandi** [composer/composer#3022]
I'm developing a web application using CodeIgniter and composer, after upgrading xcode version to 5.x.x i have issue that composer always give me warning every time I saved code change. Sometimes reload 1x or 3x the error will disappear, mostly I run composer dump-autoload but there's no luck. This issue also affect to my laravel application, so I think this is not CodeIgniter issue.

The error like this:
Fatal error: Access to undeclared static property: ComposerAutoloaderInit148f5c35df7cd20bc0488dd962d12240::$loader in /Users/blelele/Sites/experiment/cicomposer/vendor/composer/autoload_real.php on line 23

I will appreciate who help me out with this error.

Thanks

**Comment by loncool** [comment]
We met the same problem,    
here is our  system environment:
PHP Version 5.3.6 with fpm
with apc extension
