### ISSUE TITLE
Support multiple paths from an installer

### ISSUE THREAD

**Issue by slbmeh** [composer/composer#3037]
I'm creating a plugin to act as an Expression Engine installer.  I want to take the dist zipball and put different pieces in different places.

The `InstallerInterface` describes the return value as a string, and certain things rely on that being a string.

I can check all of my paths in the installer for `InstallerInterface::isInstalled`. I'm not sure the intent and current usage of `getInstallPath()`, but it doesn't quite fit right in this use case. My thought is leave the folder that has the bulk of the core code as the return for `InstallerInterface::getInstallPath` and possibly add an additional interface for installers that split up the packages into multiple locations.  Essentially I'm dealing with libs installed in one location, and assets/front controller proxy installed in a configurable webroot location.

**Comment by Seldaek** [comment]
Seems to edge-casey so closing.
