### ISSUE TITLE
"composer update" fails @OpenSSL error on linux/64, updating from packagist

### ISSUE THREAD

**Issue by ghost** [composer/composer#3045]
This error appears earlier for OSX, with old(er) openssl version, @naderman     https://github.com/composer/composer/issues/2841

```
lsb_release -rd
    Description:    openSUSE 13.1 (Bottle) (x86_64)
    Release:        13.1

openssl version
    OpenSSL 1.0.1h 5 Jun 2014

php -v
    PHP 5.6.0-dev (cli) (built: Jun 10 2014 23:28:47) 
    Copyright (c) 1997-2014 The PHP Group
    Zend Engine v2.6.0-dev, Copyright (c) 1998-2014 Zend Technologies
        with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies

composer -V
    Composer version ac497feabaa0d247c441178b7b4aaa4c61b07399 2014-06-10 14:13:12

composer update
    Loading composer repositories with package information
    The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
    error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
    Failed to enable crypto
    failed to open stream: operation failed
    https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
    Updating dependencies (including require-dev)



      [Composer\Downloader\TransportException]                                                                          
      The "http://packagist.org/p/sebastian/version$b6c1f93fb83c45709290db2cc6a5f0dbfb6c5e0d594e467f069c068f89e43903.j  
      son" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:                      
      error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed                                 
      Failed to enable crypto                                                                                           
      failed to open stream: operation failed             
```

**Comment by dipakkolhe** [comment]
> I do have the latest packages. But, nonetheless updating to latest ca-certificates to be sure,
> 
> ```
> update-ca-certificates -v -f
> ```
> 
> then, @ exec, still see the error. here's verbose console output,
> 
> ```
> composer -vvv update
>     Reading ./composer.json
>     Loading config file /root/.composer/config.json
>     Loading config file ./composer.json
>     Executing command (CWD): git describe --exact-match --tags
>     Loading composer repositories with package information
>     Downloading https://packagist.org/packages.json
>     Downloading https://packagist.org/packages.json
>     Downloading https://packagist.org/packages.json
> 
> 
> 
>       [Composer\Downloader\TransportException]
>       The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
>       error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
>       Failed to enable crypto
>       failed to open stream: operation failed
> 
> 
> 
>     Exception trace:
>      () at phar:///usr/local/bin/composer/src/Composer/Util/RemoteFilesystem.php:290
>      Composer\Util\RemoteFilesystem->get() at phar:///usr/local/bin/composer/src/Composer/Util/RemoteFilesystem.php:83
>      Composer\Util\RemoteFilesystem->getContents() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:665
>      Composer\Repository\ComposerRepository->fetchFile() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:485
>      Composer\Repository\ComposerRepository->loadRootServerFile() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:297
>      Composer\Repository\ComposerRepository->hasProviders() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:95
>      Composer\DependencyResolver\Pool->addRepository() at phar:///usr/local/bin/composer/src/Composer/Installer.php:354
>      Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:214
>      Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:123
>      Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:241
>      Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:892
>      Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:191
>      Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:117
>      Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:121
>      Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:83
>      Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
>      require() at /usr/local/bin/composer:15
> 
> 
>     update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [packages1] ... [packagesN]
> ```
> 
> fwiw, this is
> 
> ```
> openssl version
>     OpenSSL 1.0.1h 5 Jun 2014
> ```

Thank You so much
