### ISSUE TITLE
Composer site should be HTTPS-only

### ISSUE THREAD

**Issue by zackw** [composer/composer#3047]
The official Composer website (getcomposer.org) needs to be made strictly HTTPS-only.  In this case I would go so far as to say that you shouldn't even have 301 redirections from HTTP to HTTPS -- there should be nothing listening on port 80 at all.  And you need to send [Strict-Transport-Security](https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security) headers.

This is because apparently the official way to install Composer is

    curl -sS https://getcomposer.org/installer | php

which is a one-character typo (`https` to `http`) away from allowing an active attacker to replace the installer with something malicious.  This is possible even if `http://` redirects to `https://`, which is why there shouldn't be anything on port 80 at all.

**Comment by Seldaek** [comment]
Closing as the http/https situation is a lot better now.
