### ISSUE TITLE
Physical git repository was deleted when symlinked under vendor

### ISSUE THREAD

**Issue by rchavik** [composer/composer#3050]
Running ``composer install`` deleted and destroy the original git working directory of  a symlinked directory under `vendor`.  I don't think this is the proper behavior.  I lost all my local wip branches which unfortunately have not been pushed anywhere.

I think the proper action is to abort, or remove the soft link from the vendor directory only.  The original directory should not be destroyed.

**Comment by Seldaek** [comment]
Interesting.. but I wonder if this is just due to that custom installer doing something wrong or if this behavior is reproducible with any composer package (I mean one that would end up in vendor/foo/bar)?

**Comment by rchavik** [comment]
Hmm.. you might be right.

I tested with an empty project and `vendor/monolog/monolog` symlinked to `/tmp/monolog` at `1.14.0`.
After `composer install`, `vendor/monolog/monolog` is replaced with a directory, but `/tmp/monolog` still exists and its .git dir is not removed.

https://asciinema.org/a/dur5n6jtmkf2gtgo359oz7scu

Is there anything in the custom installer that might have caused this?
