### ISSUE TITLE
Merge two vendors directories (one is symlinked) for autoloading

### ISSUE THREAD

**Issue by koemeet** [composer/composer#3070]
Hi,

How can Composer handle multiple `vendors` directories? One `vendors` directory is symlinked and is used as a `shared library`.

I've made a Stackoverflow question with some more information:

https://stackoverflow.com/questions/24355342/composer-two-vendor-directories-one-of-them-is-symlinked-shared-library-aut

**Comment by ttimot24** [comment]
Does this "provide" function still working in latest releases of composer? It seem to me that it's don't.

**Comment by fruitl00p** [comment]
We're also looking into this and it seems that the `provide`-d list of packages is still being installed ...  ?
