### ISSUE TITLE
Add ability to require specific PHP settings

### ISSUE THREAD

**Issue by fracz** [composer/composer#3103]
There is an ability to require specific PHP version and particular extensions to be available so project can work:

```json
"require": {
    "php": ">=5.4",
    "ext-mbstring": "*",
    "ext-ldap": "*"
}
```

Running `composer install` can then be used to verify if the environment meets all specific criteria for the project to run.

It would also be nice to have an ability to specify some settings to have desired values, for example to require the `short_open_tag` php.ini setting to have `On` value.

**Comment by phansys** [comment]
For your use case, I think you could provide a [.user.ini.dist file](http://php.net/manual/en/configuration.file.per-user.php) with your required/suggested PHP settings. Regardless your project is executed or not by a CGI, this way should be consistent enough to encourage the users to apply the config exposed in this file.
