### ISSUE TITLE
composer-plugin-api package is ignored

### ISSUE THREAD

**Issue by etki** [composer/composer#3108]
Hi.  
I'm building a custom installer, but it looks like Composer is ignored the package mentioned above: it isn't downloaded, Composer tells me "Nothing to install or update" on update or install call, `composer depends composer-plugin-api` results in `[InvalidArgumentException]: Could not find package "composer-plugin-api" in your project. `. I've tried listing it in both `require` and `require-dev` to exclude any typo cases, but that didn't help (while codeception from the same section was installed successfully). composer.lock doesn't contain string 'plugin' at all.

`composer --version` output:
> Composer version e77435cd0c984e2031d915a6b42648e7b284dd5c 2014-07-02 15:44:54

require/require-dev part of composer.json:
```
    "require": {
        "composer-plugin-api": "1.0.0"
    },
    "require-dev": {
        "codeception/codeception": "dev-master"
    }
```

**Comment by farhanwazir** [comment]
Really helpful ;)
