### ISSUE TITLE
Composer/Installer/LibraryInstaller.php constructor needs $type

### ISSUE THREAD

**Issue by jaypatel512** [composer/composer#3113]
I am working on creating a custom installer, which actually handles more than one type. E.g. 

magento2-module
magento2-theme
magento2-library, etc.

The installer for that is similar, the only small difference is in the locations used in mapping. The constructor right now uses $type as one string argument. Now sure which to pick. The logic where it decides if the installer supports the type is in supports method. Why do we need $type in constructor then ? 

Thank you so much for helping.

**Comment by Seldaek** [comment]
If you override supports() you can put anything in the parent's $type property.
