### ISSUE TITLE
autoload-dev does not work

### ISSUE THREAD

**Issue by divsmith** [composer/composer#3114]
autoload-dev does not seem to be working. When my composer.json reads

``` js
"autoload": {
    "psr-4": {
        "Namespace\\": "src/"
    }
},
"autoload-dev": {
    "prs-4": {
        "Namespace\\Tests\\": "tests/"
    }
}
```

and I run

``` sh
composer dump-autoload
```

My /vendor/composer/autoload_prs4.php file appears as 

``` js
// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Namespace\\' => array($baseDir . '/src'),
);
```

and autoloading the Namespace\Tests namespace does not work. But when I change my composer.json to

``` js
"autoload": {
    "psr-4": {
        "Namespace\\": "src/",
        "Namespace\\Tests\\": "tests/"
    }
}
```

and run

``` sh
composer dump-autoload
```

my autoload_psr4.php file reads

``` js
// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Namespace\\Tests\\' => array($baseDir . '/tests'),
    'Namespace\\' => array($baseDir . '/src'),
);
```

and the testing namespace is autoloaded correctly. I am using composer version e77435cd0c984e2031d915a6b42648e7b284dd5c.

**Comment by easy-system** [comment]
Same issue.
The file `autoload_psr4.php` not contains the namespace from `autoload-dev ` section. 
This is the latest version of `composer.phar`.

**Comment by Josantonius** [comment]
Same issue.

`composer require vendor/namespace`

The file autoload_psr4.php not contains the namespace from autoload-dev section only from autoload.

`    
"autoload": {
        "psr-4": {
            "Namespace\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Namespace\\Tests\\": "tests/"
        }
    }
`
`
// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Namespace\\' => array($baseDir . '/src'),
);
`

**Comment by xabbuh** [comment]
@Josantonius Only the `autoload-dev` section from your project's `composer.json` file is taken into account: https://getcomposer.org/doc/04-schema.md#autoload-dev

**Comment by zaniar** [comment]
I'm trying to autoload my class for development purpose.

When I use this one

```
"scripts": {
  "serve": "Dev\\Task::serve"
    },
  "autoload-dev": {
    "psr-4": {
      "Dev\\": "dev/"
    }
}
````
It didn't work. Composer said that Dev\Task is not autoloadable.

but, when I use this one

```
"scripts": {
  "serve": "Dev\\Task::serve"
    },
  "autoload": {
    "psr-4": {
      "Dev\\": "dev/"
    }
}
```
It worked as expected.

I'm using Composer version 1.1.2 and my composer.json is in project's root directory.

Did I do it wrong? If I'm not, then it's a bug then.

**Comment by curry684** [comment]
Please include the exact command you're using. Makes quite a difference in this case whether you're running `composer install --no-dev` or `composer install`.

**Comment by zaniar** [comment]
I'm ran `composer create-project` at the beginning of my project. That was some days ago. As I remember, I didn't pass the `--no-dev` option.

My `require-dev` section is working, so I believe I'm on `dev` environment.

After I modified composer.json like I mentioned above, I run `composer dump-autoload`. Then I run `composer serve`. I got `Class Dev\Task is not autoloadable, can not call serve script` when I use `autoload-dev`.

**Comment by Great-Antique** [comment]
The same.
```json
...
    "autoload": {
        "psr-4": {
            "": "src/"
        },
        "classmap": [
            "app/AppKernel.php",
            "app/AppCache.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/",
            "Dist\\": "dist/Dist/"
        }
    },
...
    "scripts": {
        "qaBuild": "Dist\\QA\\ScriptHandler::build"
    },
...
```
```
$ composer -V
Composer version 1.2.0 2016-07-19 01:28:52
$ composer install
$ composer run-script qaBuild
Class Dist\QA\ScriptHandler is not autoloadable, can not call qaBuild script
```
It works when I move `psr-4` section from `autoload-dev` to `autoload`
