### ISSUE TITLE
Don't delete first and download after on update

### ISSUE THREAD

**Issue by avenirer** [composer/composer#3118]
Hello.

I propose that you make a change on composer, so that when someone does a "composer update" the script doesn't delete the files and then try to download the updated files. I tried to do a "composer update", and it happened that the composer couldn't download a folder, but first it deleted the old folder.

**Comment by Seldaek** [comment]
Closing as we might do it while refactoring the install process to do multiple downloads at once, but that's tracked already in other issues.
