### ISSUE TITLE
Always Recommend a Global Installation

### ISSUE THREAD

**Issue by weaverryan** [composer/composer#3125]
Hi guys!

This is an RFC to always propose that Composer is installed in some global way so that you can just run commands like `composer install`.

This would also be consistent with other package managers, like npm.

#### Current Problem

Currently, some people install Composer globally and some just download the phar. So, depending on how you install, your commands look different:

```bash
composer install
php composer.phar install
```

The problem is that this little inconsistency makes documentation on libraries harder to write/understand. For example, if I have a library, I would love to just say:

"Run the following command to install"

```bash
composer require cool-name/cool-lib
```

I've seen beginners see this command, copy it, get a command not found, and get confused :).

What do you think? And can we do this consistently over all OS's? Can we use `~/bin/composer` on all systems? This would avoid needing to sudo some command to move the phar file there.

Btw, @stof proposed this:

```bash
$ curl -sS https://getcomposer.org/installer | php -- --bin-dir ~/bin/composer
```

**Comment by Seldaek** [comment]
Closing as I don't think we can really do so much here. Best would be to get composer pre-installed with php or at least available as distribution packages. I think it's getting there (distros) slowly and the 1.0 stable should help.
