### ISSUE TITLE
Equivalent of `git submodule foreach`

### ISSUE THREAD

**Issue by jkufner** [composer/composer#3126]
Hello,
I find `git submodule foreach` very useful when working on application wich uses a lot of plugins, so there is simultaneous developement in multiple repositories. 

Examples:

`composer foreach git pull --rebase`
  - To get all changes in all repositories and integrate them with local commits.

`composer foreach git push`
  - To push local changes in all plugins to server.

`composer foreach make tests`
  - To test everything.

Example implementation:

    composer show -iP | while read p d
    do
        echo "$p ($d)"; ( cd $d && [ -d .git ] && git pull --rebase ) ; echo
    done

Please note this implementation have many flaws, but hopefuly it demonstrates expected behavior.

There should be options to run specified command only on given repository type and to match given vendor. Example: `composer foreach --git --vendor me git pull --rebase`, or `composer foreach --mine git pull --rebase` to run command only on my repositories (same vendor?). Anyway, these options are not important as long as failed command will not stop the foreach loop.

**Comment by Seldaek** [comment]
Thanks for the suggestion but I don't think it is really a good idea as in most contexts you should be running composer update to update code and not go meddle in the vendor dir directly. I understand that in some internal projects it might be a thing but for that an external tool like the one you built does the job just fine.
