### ISSUE TITLE
Working directory as a command

### ISSUE THREAD

**Issue by Keeehi** [composer/composer#3139]
Hi!
According to composer list the right order is `composer [options] command [arguments]`, so I created `composer -d /var/www/git-deploy-projects/main/ install` but for that I got 
```[InvalidArgumentException]                                    
  Command "/var/www/git-deploy-projects/main/" is not defined.
```
If I reorder it `composer install -d /var/www/git-deploy-projects/main/` then it works well, but it is not right according to help.

All in all, I think, that both possibilities should work.

**Comment by Seldaek** [comment]
Migrated the issue to symfony repo
