### ISSUE TITLE
Can i update project without checking php exts?

### ISSUE THREAD

**Issue by a-x-** [composer/composer#3145]
// Excuse my beginner's English.

Hello!

Can i ask?

I develop my project on the Windows machine with cygWin (i'm not a freak, i forced to this).
And i have installed php for executing composer.
My app executing on the remote testing and production Linux-based machines with full web stack.

I want run `composer update` on the my developing Windows machine, but some dependencies have `ext-curl` dependency, which not installed on the developing Windows machine (and it's not planning).

```
paypal/rest-api-sdk-php v0.8.3 requires ext-curl * -> the requested PHP extension curl is missing from your system
```

**Comment by sonitwilli** [comment]
@Seldaek  Thanks
