### ISSUE TITLE
Prefer `wget` rather than `curl` in docs

### ISSUE THREAD

**Issue by maximal** [composer/composer#3152]
`wget` is installed by default in vast majority of Linux systems, like Ubuntu, Debian and so on.

`curl` needs to be installed additionally.

I propose using
`wget -O - https://getcomposer.org/installer | php`
instead of
`curl -sS https://getcomposer.org/installer | php`
in Composer documentation.

I can make a pull request for this if needed.

What do you think?

**Comment by Seldaek** [comment]
This is outdated, no more curl anyway.

**Comment by maximal** [comment]
Yeah. Thanks.
