### ISSUE TITLE
Simplify to switch branches with different composer dependencies

### ISSUE THREAD

**Issue by sun** [composer/composer#3167]
#### Scenario
1. [PHPUnit](https://github.com/sebastianbergmann/phpunit) 4+ uses Composer, and it's in the process of major refactoring.
1. In `master`, several utility classes have been split into separate, decoupled packages (or replaced with other 3rd party libs) that are pulled back in via Composer.
1. In stable branches, those utility classes still exist and the additional Composer dependencies do not.
1. The target branch for each PR varies a lot, depending on potential BC breaks, so the first thing you do before you do anything is to switch to a different target branch.

#### Problem / Use-case
Currently, I need to perform the following procedure whenever I'm switching branches:

1. Remove the auto-generated `composer.lock` file (PHPUnit has none by default)

  ```sh
  $ rm composer.lock
  ```
1. Run `composer install` to switch dependencies: (cleaned up for brevity)

    ```diff
    --- switch-to-master.txt
    +++ switch-to-stable.txt
    @@
     $ composer install
     Loading composer repositories with package information
     Installing dependencies (including require-dev)
       - Updating sebastian/environment
    -    Checking out (1.0.0 => dev-master 10c7467)
    +    Checking out (dev-master 10c7467 => 1.0.0)
     
       - Updating phpunit/php-token-stream
    -    Checking out (1.2.2 => dev-master a080256)
    +    Checking out (dev-master a080256 => 1.2.2)
     
       - Updating phpunit/php-code-coverage
    -    Checking out (2.0.9 => dev-master 9171bca)
    +    Checking out (dev-master 9171bca => 2.0.9)
     
    -  - Installing ocramius/lazy-map
    -    Cloning (dev-master 5c77102)
    +  - Removing ocramius/lazy-map
    +    Was (dev-master)
     
    -  - Installing ocramius/instantiator
    -    Loading (1.0.0) from cache
    +  - Removing ocramius/instantiator
    +    Was (1.0.0)
     
       - Updating phpunit/phpunit-mock-objects
    -    Checking out (2.1.5 => dev-master f9f31b9)
    +    Checking out (dev-master f9f31b9 => 2.1.5)
     
       - Updating sebastian/exporter
    -    Checking out (1.0.1 => dev-master eb54a69)
    +    Checking out (dev-master eb54a69 => 1.0.1)
     
       - Updating sebastian/diff
    -    Checking out (1.1.0 => dev-master ac84cfd)
    +    Checking out (dev-master ac84cfd => 1.1.0)
     
       - Updating sebastian/comparator
    -    Checking out (1.0.0 => dev-master e54a01c)
    +    Checking out (dev-master e54a01c => 1.0.0)
     
       - Updating symfony/yaml
    -    Checking out (v2.5.2 => dev-master 07ff901)
    +    Checking out (dev-master 07ff901 => v2.5.2)
     
     Writing lock file
     Generating autoload files
    ```

In particular, the suboptimal part:

Some dependencies are removed entirely (and added back when switching back):
>  - Removing ocramius/lazy-map
>  - Removing ocramius/instantiator

Coincidentally, for some reason, those two deps also seem to be supplied by dist instead of by source.  Not sure why that is.  If they were git clones, I can only assume that switching branches would take even longer, because the entire repo would be removed and re-cloned from scratch.

#### Proposed solution

1. `composer install --no-remove` — New option to not clean up extraneous vendor packages and retain them in-place, as-is.

1. Optionally for UX: `composer switch` — New built-in command; controlled way for switching between branches.  Under the hood:
  1. Determine whether `composer.lock` is under VCS control.  If not, delete it.
  1. Invoke `composer install --no-remove`.
  1. …possibly further A.I. improvements…

Thoughts?

##### Notes

I don't know whether there is a recommended solution or workaround for this, or whether I'm doing something wrong — didn't find anything in the docs; searching existing issues didn't yield anything either.

In any case:  It takes quite some time to figure out how to use Composer correctly for this (very common?) scenario, so just in case it's deemed to have to be so hard and no functional changes will be considered, we should at least consider to add a dedicated documentation section about the topic of switching between branches.

##### Closely related issues
* #1083 Git post-checkout/post-merge hook integration. (status unclear)
* #197 New dedicated `clean` command. (rejected)

##### Marginally related issues
* #1013 composer.json inheritance. (WIP)
* #2129 / #2325 Support multiple environments. (rejected)

**Comment by mindyk** [comment]
how come people ore not voting for this like crazy. I have different dependencies in every branch, this would help a lot

**Comment by MichaelMackus** [comment]
+1 this would be very helpful

**Comment by toddmcbrearty** [comment]
+1 needs......

**Comment by biwerr** [comment]
+1

**Comment by Seldaek** [comment]
Sounds like it could be done as a plugin once #3377 lands, or eventually as an external tool instrumenting composer. It isn't really mainstream enough to warrant inclusion IMO.

As for the --no-remove, that's a bit weird feature to have, and not very necessary as if you switch a lot reinstalling takes little time as the zip files are in the cache.

**Comment by chintogtokh** [comment]
Was this ever implemented? It's still a problem if you're running off vagrant with the vendor directory shared. Reading/writing to/from the cache can be very hit and miss speed-wise.
