### ISSUE TITLE
Add the ability to create custom repository types

### ISSUE THREAD

**Issue by francoispluchino** [composer/composer#3180]
It would be really interesting to give to the plugin, the ability to add custom repository types.

Currently, a plugin can add a custom repository type, but an error is thrown before the initialization of the plugin, if you add to your `composer.json` file, a repository with a nonexistent type.

Example:
```json
{
    "repositories": [
        {
            "type": "custom-type",
            "url":  "https://example.org/foobar"
        }
    ]
}
```

For a concrete example, I realized the plugin [composer-asset-plugin](https://github.com/francoispluchino/composer-asset-plugin) that allows you to manage project assets (css, js, etc.) in your `composer.json` without installing NPM or Bower (works by transposing package information from NPM or Bower to a compatible version for Composer).

To operate, it create custom VCS repository types (npm-vcs, bower-vcs). However, to use private repositories, we can not add the custom repository types directly in the `repositories` section (because the custom type does not exists before the initialization of the  plugin), and we are therefore obliged to create a `extra.repositories` section to make it work ; but it's a duplication (see the issue francoispluchino/composer-asset-plugin#10).

> **Note:**
> The PR #3178 proposed this approach, but it does not work if the plugin is not already present before initialization Composer.

**Proposed solution:**

Require: #3082

The PR #3082 performs a first pass to only install plugins and their dependencies, then into the second passage, launches the analysis of the dependencies of the root file `composer.json`.

To add this new feature, it would just add the following mechanism:

During the first passage (only the plugins installation), not include the repository types that do not exist, and in the second passage, include all custom repository types.

This solution would work in "global" mode and "project" mode.

**Comment by ZZromanZZ** [comment]
Any progress in this issue ? Gitlab support would be a very usefull !

**Comment by Seldaek** [comment]
Don't think we really want this after all so closing.

**Comment by andkirby** [comment]
We really need to be able to add a custom repository type. Why this issue has been closed?
Is there some exists way to do this?

**Comment by vercotux** [comment]
Has anyone found a workaround for this yet?

**Comment by andkirby** [comment]
@vercotux, I use my own package for this. [andkirby/multi-repo-composer]
Try to consider [andkirby/multi-repo-composer/blob/master/src/MultiRepoPlugin.php](MultiRepoPlugin.php)

**Comment by Javlopez** [comment]
Hey everyone I'm having an issue with composer + teamcity + private repositories so we are going to use composer repositories type "path", but locally works fine using repositories type "git", I think would be good to have a mutiple types,  in this way we can to have some options to choose the right repository 


```javascript
  "repositories": [
    [
      {
        "type": "path",
        "url": "../my-repo"
        "priority": 0
      },
      {
        "type": "git",
        "url": "git@github.com:myuser/myrepo.git",
        "priority": 1
      }      
    ]
]
```

**Comment by curry684** [comment]
The priority you suggest is already implicit because of declaration order. Beside that please do not 'kick' old closed issues to suggest new features but create a new issue.
