### ISSUE TITLE
composer doesn't seem to respect semantic versioning

### ISSUE THREAD

**Issue by keithfancher** [composer/composer#3181]
I'm running a fairly recent version of composer:
```
$ composer --version
Composer version 4ecdbf89c4a3d1e5dfe73c57e3202a5e2a18c87e 2014-07-28 20:12:27
```

When I attempt to install the latest PHPUnit 3.x, which *should* be 3.7.37, I instead get 3.7.9. I tried requiring `3.*`, `~3.7`, `<4.0`, and various other version strings, but all resulted in 3.7.9 being installed. I had to specify `3.7.37` specifically to get the correct version.

With semantic versioning, 3.7.9 < 3.7.37 (because 9 < 37).

**Comment by PatchRanger** [comment]
@cs278 Sorry, I missed the point. Do you mean that there is no bug and this is just a particular use case with affordable workaround?

Composer version 1.0-dev (f10c71475167a4661225b14560ca0a400d730829) 2015-03-29 14:37:42
Composer version dealing differs from command line and with `composer update` when `minimum-stability` is set to `dev` (`composer update` erroneously takes very old branch `<version-dev` though there are other affordable branches with newer commits), see https://github.com/nizsheanez/yii2-asset-converter/pull/13 .

**Comment by beck** [comment]
Another way that composer does not respect semantic versioning, say you have:

```
"package": "1.2.3-zeta.3",
```

Throws:
>   [UnexpectedValueException]
  Could not parse version constraint 1.2.3-zeta.3: Invalid version string "1.2.3-zeta.3"

From semantic versioning:
> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]

Composer respects "alpha" "beta" and "dev", but that's it.

**Comment by Seldaek** [comment]
The initial behavior is explained well by https://github.com/composer/composer/issues/3181#issuecomment-50959939 

@beck we decided not to support these as they are not easily sortable and comparable given our current methods of doing this, plus it's not really widespread usage, and +metadata lets you do anything you want already if needed for dummy suffixes.
