### ISSUE TITLE
Output option for tabs as indentation

### ISSUE THREAD

**Issue by dereuromark** [composer/composer#3192]
Refs https://github.com/composer/composer/issues/1788

There should be an option for outputting the composer.json file with a tab as indentation, as well.
Not just 4 spaces.

**Comment by Seldaek** [comment]
I don't think we need the pretty printer, we can just replace the generated 4-space indent by tabs fairly easily. As json doesn't support multi-line strings it's quite safe.

So if someone wants to add a --tabs to the InitCommand I'd say why not. I don't think the other commands need it, the cases where we re-dump the whole file in require and so on are extremely rare (if any is left..).

**Comment by Seldaek** [comment]
Closing as it doesn't seem important enough for anyone to do the job.

**Comment by maximal** [comment]
Hi, guys? @dereuromark, @Seldaek

Do you mind if I implement this issue?

**Comment by Seldaek** [comment]
@maximal feel free if it's not adding too much code cruft I'm not strongly against it.
