### ISSUE TITLE
Adding custom plateform package

### ISSUE THREAD

**Issue by nuxwin** [composer/composer#3193]
Hello ;

We have a main application which provide an installer written in Perl. This installer must allow users to choose some addons to install. Here, each addon is a composer package.

The problem here is that we want only show the list of packages which are compatible with our main application. This mean that we have to build a list of available packages by doing some filtering.

To get the list of available packages we run "composer.phar search vendorname"

However, it's not sufficient. We want only retrieve the list of packages which are compatible with the version of our main application. To do so, we want add a platform package which allow our addons (composer packages) to define a version constraint on our main application such as

"require": {
"applicationName": "~1.2"
}

The question here is: How add our how platform virtual package which will provide the version constraint for our main application without providing our how version of composer.phar.

I'm wondering if I can achieves this by creating a plugin as stated here: https://getcomposer.org/doc/articles/plugins.md

Here, it seem that I can register some listeners easily on the PluginEvents::COMMAND event which is triggered when the search command is run. The only thing that I'm not aware is how to retrieve the PlatformRepository object to add my own platform package. As I see, the PlatformRepository is not passed as argument to listeners which listen to the PluginEvents::COMMAND. Thus, the only way I see is to provide a listener which will redefine the https://github.com/composer/composer/blob/master/src/Composer/Command/SearchCommand.php#L55 logic and exit.

I must say here that our main application is not managed by composer. The composer.json file is generated by our main application installer according the user choices.

Thanks

**Comment by Seldaek** [comment]
I guess you solved this somehow by now, but if not, I'd suggest just requiring the application package's name/version in the addons, then you don't need anything special.
