### ISSUE TITLE
create-project ignoring --repository-url for dependencies

### ISSUE THREAD

**Issue by kissifrot** [composer/composer#3200]
Hello,

I'm using a satis server to mirror packages in out internal network. Mirrored packages are build correctly on the server.

But when we use commands such as

```
composer create-project --repository-url=http://internal.server:8080 symfony/framework-standard-edition sf2/ "2.5.*"
```

The symfony/framework-standard-edition package is correctly downloaded from the satis server, but when fetching depandancies of the project

```
Installing symfony/framework-standard-edition (v2.5.3)
  - Installing symfony/framework-standard-edition (v2.5.3)
    Downloading: 100%

Created project in ./sf2
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing twig/twig (v1.16.0)
```

Starting with twig and others, they are all fetched from packagist.
Shouldn't --repository-url option override this?

**Comment by Seldaek** [comment]
IMO the repository should be part of either your global config or the composer.json of the project you are running create-project against.

Alternatively, if you want to script it to use stock `symfony/framework-standard-edition` as a package, you could run create-project with `--no-install` and then `composer config repo....` to configure the repository and finally a `composer install`.
