### ISSUE TITLE
Catchall autoloader

### ISSUE THREAD

**Issue by davidkuridza** [composer/composer#3202]
I've come across an interesting case of  "catchall" autoloader. When a package has following autoload configuration

```json
"autoload": {
    "psr-0": { "": "src/" }
}
```

generated `autoload_namespaces.php` contains

```php
return array(
    '' => array($vendorDir . '/pkg/pkg/src'),
);
```

When using `install -o` or `dump-autoload` directly, `autoload_classmap.php` contains:

```php
return array(
    'Pkg\\Pkg\\Class' => $vendorDir . '/pkg/pkg/src/Class.php',
);
```

However, `autoload_namespaces.php` is still unchanged, resulting in trying to autoload every class which fails other loaders.

I can't find any reference in the documentation whether this is by design or not. Is it a feature or a bug?

Much obliged.

**Comment by Seldaek** [comment]
See the above 3 commits for a few things that should enable this at the composer level. The short story is that `composer validate --strict --with-dependencies` should now return a non-zero exit code for such autoloaders (or any other issue with your dependencies).

**Comment by davidkuridza** [comment]
@Seldaek :+1: much obliged

**Comment by b01** [comment]
Those are some welcome additions; I will definitely be adding the --validation --strict commands to our build/push process. Thanks!
