### ISSUE TITLE
Https Proxy Problems

### ISSUE THREAD

**Issue by susannemoog** [composer/composer#3204]
Hi,

I'm trying to install TYPO3 via composer and have the following problems:

The package typo3/cms-composer-installers contains:

<pre><code>
public function __construct(\Composer\IO\IOInterface $io, $jsonUrl = 'https://get.typo3.org/json') {
    $this->file = new \Composer\Json\JsonFile($jsonUrl, new \Composer\Util\RemoteFilesystem($io));
}
</code></pre>

Proxy settings are:
<pre><code>http_proxy=http://http-proxy:1234
https_proxy=http://https-proxy:1234
</code></pre>
composer diagnose says:
<pre>
Checking git settings: OK
Checking http connectivity: OK
Checking HTTP proxy: OK
Checking HTTP proxy support for request_fulluri: OK
Checking HTTPS proxy support for request_fulluri: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking composer version: OK
</pre>

composer install then fails with:

<pre>
[Composer\Downloader\TransportException]                                                  
  The "https://get.typo3.org/json" file could not be downloaded (HTTP/1.1 400 Bad Request)
</pre>

wget and curl both work, also installing other packages works. 

From what I understood by debugging, the problem is in ''/var/www/work/composer/src/Composer/Util/StreamContextFactory.php->getContext()'' which always returns the http_proxy and never switches to the https one.

Can you tell me how to solve this or what else I could do to workaround the problem?

Thanks, 

Susanne

**Comment by khaefeli** [comment]
@Seldaek 
is that also working for things like:
https://github.com/TYPO3/CmsComposerInstallers/blob/master/Classes/TYPO3/CMS/Composer/Installer/CoreInstaller/GetTypo3OrgService.php#L48

because I've this error problem with TYPO3 & http proxy:
https://github.com/TYPO3/CmsComposerInstallers/issues/8

**Comment by psychomieze** [comment]
It's working for TYPO3 installations - that was exactly my problem. 

To get it working I had to set the env var: HTTPS_PROXY_REQUEST_FULLURI to false.

**Comment by khaefeli** [comment]
ok I see. Works now also for me. 
I would prefer to set the default to "false" because:

http://php.net/manual/de/context.http.php

    request_fulluri boolean
    When set to TRUE, the entire URI will be used when constructing the request. (i.e. GET http://www.example.com/path/to/file.html HTTP/1.0). While this is a non-standard request format, some proxy servers require it.
    Defaults to FALSE.

**Comment by AiDirex** [comment]
@Seldaek This bug still exists in your installer script fetched from https://getcomposer.org/installer
https://bugs.php.net/bug.php?id=63519
