### ISSUE TITLE
Memory limit

### ISSUE THREAD

**Issue by RSully** [composer/composer#3208]
Recently I've been consistently hitting composer's 512M limit, so I've created a wrapper `composer-infmem` that I can use instead.

For slightly bigger projects is it common to consistently hit the limit (on updates/requires)? Is it time to consider lifting the limit from 512M?

(Also worth tagging homebrew/homebrew-php#1210)

**Comment by Seldaek** [comment]
limit is now 1GB and we have improved on memory usage quite a bit so closing
