### ISSUE TITLE
Composer uses PSR-0 directory structure when optimizing

### ISSUE THREAD

**Issue by rickard2** [composer/composer#3224]
It seems like the `composer dump-autoload --optimize` command also identifies classes using the PSR-0 directory structure when using PSR-4 autoloading in `composer.json`.

I've set up this test to show the difference when using `--optimize` and when not. In my example, test.php works when optimizing but not when you're not. 

https://github.com/rickard2/composer-test

````
$ composer --version
Composer version 1e27ff5e22df81e3cd0cd36e5fdd4a3c5a031f4a 2014-08-11 15:46:48
````

**Comment by Seldaek** [comment]
I don't know if we can really fix this, at least it doesn't seem to be a major issue as most PSR-0/4 users use that in development and will notice problems pretty quickly, so not really worth the work IMO.
