### ISSUE TITLE
Replace json by NEON parser, fully YAML & JSON compatible

### ISSUE THREAD

**Issue by hrach** [composer/composer#3228]
There were [a few](https://github.com/composer/composer/issues/159#issuecomment-7674252) [notes](https://github.com/composer/composer/issues/440#issuecomment-7674290) about neon, however without any relevant response. Also it was at the times that the NEON didn't have own repository.

I suggest replacing json parser by [**NEON parser**](https://github.com/nette/neon), which is **fully compatible with JSON** and YAML. NEON's primary format is much more cleaner and readable, also **supports comments**. _Also trailing commas will be never you problem again._

You can play with it at http://ne-on.org/.

**Comment by hason** [comment]
It is possible to use a composer plugin, e.g. https://github.com/webuni/composer-neon-plugin
