### ISSUE TITLE
The "https://packagist.org/packages.json" file could not be downloaded:

### ISSUE THREAD

**Issue by etudor** [composer/composer#3235]
Hi.

After trying to update composer i got this error: 

Loading composer repositories with package information
The "https://packagist.org/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Th
is is usually a temporary error during hostname resolution and means that the local server did not receive a response fr
om an authoritative server.
failed to open stream: php_network_getaddresses: getaddrinfo failed: This is usually a temporary error during hostname r
esolution and means that the local server did not receive a response from an authoritative server.
https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date.

After asking on laravel's irc channel it seems for others packagist.org website is working fine.

**Comment by ravindrasingh22** [comment]
Why to run composer from container? It can be run from host machine, right?

**Comment by xhaile** [comment]
I happen to it

**Comment by xhaile** [comment]
it's different from windows and Linux when I type in 'composer diagnose'. windows is ok, but linux show these:The "https://packagist.org/packages.json" file could not be downloaded:network is unreachable!!!
