### ISSUE TITLE
Composer update does not prompt for private repo credentials, install does

### ISSUE THREAD

**Issue by ReservedDeveloper** [composer/composer#3243]
Trying to run `composer update my_vendor/my_package -vvv`, where `my_vendor/my_package` is a private repository outside of the GitHub/BitBucket ecosystem. Running that command, I am not prompted for credentials.

Cloning a bare repo and running `composer install`, I am properly prompted for credentials and the repo is properly downloaded. If I immediately run update after, it fails out with the following:

```
 [RuntimeException]                                                                                                                         
  Failed to clone http://MY_REPO_URL.git, could not read packages from it                     

  Cloning into bare repository '/home/vagrant/.composer/cache/vcs/MY_REPO.git'...  
  fatal: repository 'http://MY_REPO.git/' not found   
```

**Comment by ne0h12** [comment]
@mattzuba, I have the same problem. How do you resolved her?

**Comment by DBX12** [comment]
This is only partly related to the error described by OP, but if you use a **bitbucket** repository as private repo, you must set the type to `git-bitbucket` for updates. Using just `git` seems to work on the first install but fails on updates.

**Comment by bradleygreen** [comment]
> This is only partly related to the error described by OP, but if you use a **bitbucket** repository as private repo, you must set the type to `git-bitbucket` for updates. Using just `git` seems to work on the first install but fails on updates.

THANK YOU! I have been struggling to find a good answer to this problem for two weeks. Sometimes I have been able to update Oauth, or change composer version, and get it to work, but it has been an inconsistent struggle. 

For me, this appears to have been the answer I needed.

**Comment by vlad88sv** [comment]
Just ran into this with composer 2.6.6 it only tells you it can't update the dependency, even using -W fails without major details about the cause (expired GH token in my case)
