### ISSUE TITLE
Skip unavailable repositories

### ISSUE THREAD

**Issue by iainp999** [composer/composer#3250]
Hi everyone,

I have a question I'm hoping someone here can answer.  I've searched the web and could not find an answer.

We're looking to configure some private repos using satis, and subsequently described to composer in a ~/.composer/config.json file.  We'd like to have both a localhost satis repo and a centralized satis repo defined in the composer config.json.  

The localhost repo may not always exist - in this case, we want composer to skip this repo and "fall back" to the central repo.  However, composer fails with a TransportException if the localhost repo cannot download packages.json from localhost.

Can anyone advise on this?

Many thanks in advance.

**Comment by kop** [comment]
I would like to reopen this issue or maybe to ask for some advice.

Let me describe my use case first.
I'm running some CI jobs that are using Composer in the Kubernetes cluster.
I also have a ToranProxy deployed in the same cluster.

Now, I want to be able to connect to the same ToranProxy by different URLs.
Inside of CI runners it will be available at `http://toran-proxy` - direct hi speed connection.
Outside of cluster it will be available at `http://toran-proxy.domain.com` - this connection will leave cluster first and will enter via the load balancer, slowing down connection speed and loading my load balancer.

Ofcourse, I could map `http://toran-proxy.domain.com` to `http://toran-proxy` on the CI node somehow, but it looks like a hack to me. Maybe there are something else I'm missing?

Thank you!

**Comment by Seldaek** [comment]
@kop I think setting toran-proxy.domain.com in /etc/hosts to whatever internal IP you got for that server would be best really, because it's not just about unavailable repositories here, in CI you probably want to install from composer.lock and that will contain whatever URLs you used to install the packages outside of the CI network.. Having multiple URLs really just causes a lot of troubles.

**Comment by kop** [comment]
Thank you, @Seldaek.
I think I will go with a proposed solution.
