### ISSUE TITLE
Skip symlinked vendor packages when updating

### ISSUE THREAD

**Issue by noccy80** [composer/composer#3254]
To avoid cluttering my git repositories with lots of small changes, I often symlink libraries into the vendors directory of the app that uses them while I'm working on both. This causes problems when doing a `composer update`. It would be great if composer was aware of this, and could take the appropriate action:

- Without `--force` just print out "ignoring symlinked package foo/bar..."
- With `--force`, unlink the symlink and install the package fresh

**Comment by Seldaek** [comment]
The new path repository (https://getcomposer.org/doc/05-repositories.md#path) lets you do this cleaner now.

**Comment by dantleech** [comment]
This would still be good imo. 

I often work on a project and its multiple dependencies simultaneously - and those dependencies are projects in their own right in their own workspaces. So duplicating them and working in `vendor` is just somewhat confusing/frustrating - as I am then working on the same project in two different places. Hence I prefer to symlink.

**Comment by Seldaek** [comment]
@dantleech there is the path repo or https://github.com/franzliedke/studio that can do it cleanly, I'm not really willing to add dirt hacks like ignoring all symlinks.
