### ISSUE TITLE
Infinite loop on composer init and Ctrl+C

### ISSUE THREAD

**Issue by flaviojs** [composer/composer#3273]
I was starting a new project with `composer init` and canceled with Ctrl+C in the first step, "Package name", to do something else first.
The result was an infinite loop displaying:
`Package name (<vendor>/<name>) [flaviojs/xxx]: Aborted`

If I do Ctrl+C in the next step, "Description", it terminates as expected with:
```
[RuntimeException]
Aborted
```

-----

I'm running xampp with Windows 7 64-bit:
```
# composer --version
Composer version d79f2b0fd33ee9b89f3d9f1969f43dc3d570a33a 2014-09-10 15:11:05
# php --version
PHP 5.5.11 (cli) (built: Apr  8 2014 15:07:14)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
```

**Comment by Seldaek** [comment]
I can not reproduce this sorry, if you can provide more info then perhaps we can look into it if you are still experiencing the issue with latest composer.
