### ISSUE TITLE
Vendor PATH mechanism ?

### ISSUE THREAD

**Issue by Adirelle** [composer/composer#3281]
Would it possible to add a kind of vendor PATH mechanism ?

Goals:
* reuse packages amongst several installation,
* ease development of packages.

The idea is the following:
 * vendor paths can be configured in the root package,
 * once Composer determined the version of a package to use, it checks the vendor paths:
   * if the required version of the package is found in one of the paths, it is used, 
   * else, Composer installs the package in the local vendor folder, as usual.

Vendor paths can be defined for specific package, a vendor or by default, using:
* `vendor/name`: location of that specific package.
* `vendor/*`: location of all package from `vendor`,
* `*`: default location.

Missing items (vendor, name and verison) are appended to the path to look for. E.g.: 

<table>
<tr><th>Required package</th><th>Vendor configuration</th><th>Searched path</th></tr>
<tr><td>"foo/bar": "1.0.0"</td><td>"foo/bar": [ "/some/path" ]</td><td>"/some/path/1.0.0"</td></tr>
<tr><td>"foo/bar": "1.0.0"</td><td>"foo/*": [ "/some/path" ]</td><td>"/some/path/bar/1.0.0"</td></tr>
<tr><td>"foo/bar": "1.0.0"</td><td>"*": [ "/some/path" ]</td><td>"/some/path/foo/bar/1.0.0"</td></tr>
<tr><td>"foo/bar": "dev-master"</td><td>"*": [  "/some/path" ]</td><td>"/some/path/foo/bar/dev-master</td></tr>
</table>

**Comment by Seldaek** [comment]
This is now possible as the `path` repo https://getcomposer.org/doc/05-repositories.md#path
