### ISSUE TITLE
Problems installing Laravel.

### ISSUE THREAD

**Issue by lexito** [composer/composer#3289]
Hello. I am having issues installing laravel. I have followed the first two methods, (composer global require "laravel/installer=~1.1") and (composer create-project laravel/laravel --prefer-dist) on this site( http://laravel.com/docs/installation ) and they failed.
I guess upon looking through the forums i need to output my result for compose diag......
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity: OK
Checking HTTP proxy: OK
Checking HTTP proxy support for request_fulluri: FAIL
Unable to assert the situation, maybe packagist.org is down (The "http://packagist.org/packages.json" file could not be downloaded (HTTP/1.0 400 Bad Request))
Checking HTTPS proxy support for request_fulluri: OK
Checking disk free space: OK
Checking composer version: OK

1. I want to know why i cannot install laravel with these two methods.
2. I am using a proxy. Yes. But i don't know what reques_fulluri means and what it does.

**Comment by DALIHILLARY** [comment]
https://github.com/DALIHILLARY/laravelInstaller
