### ISSUE TITLE
Running interactive scripts as composer script doesn't work as expected

### ISSUE THREAD

**Issue by deresh** [composer/composer#3299]
When running a standalone script as part of post-{install,update}-cmd script then interactive scripts doesn't stop at prompt, it just passes through.

For example if i put a phing in post-install-cmd as "phing setup" and setup task in phing requires user input it just loops through (as if i was pressing enter continuosly) in an infinite loop (because phing required that some fields are filled).

if you need aditional info, just ask ;)

**Comment by mbrodala** [comment]
I also think that this could be done for non-Windows plattforms only. I see no reason to cripple scripts just because one platform is broken. The check itself can be performed with `Platform::isWindows()` unless I'm missing something.

**Comment by zArubaru** [comment]
Any update on this, or is this going anywhere :o?

**Comment by stormeyes** [comment]
same, any update on this?

**Comment by khalwat** [comment]
I'm curious on this as well.

**Comment by SherinBloemendaal** [comment]
Update?

**Comment by neelbhanushali** [comment]
Bump

**Comment by neelbhanushali** [comment]
Can use this
https://pantheon.io/blog/writing-composer-scripts

**Comment by pyrsmk** [comment]
Idem, this is really a must have for me to be able to handle correctly my workflow for many projects.

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/commit/f5726366286b9e2765dfe4947fa825701f306737 for 2.0
