### ISSUE TITLE
Error when installing composer using windows installer

### ISSUE THREAD

**Issue by ghost** [composer/composer#3324]
I am getting this error when I am trying to install composer on xampp using windows installer:

The PHP exe file you specified did not execute correctly: 
C:\xampp\php\php.exe

Running it from the command line might highlight the problem.
Internal Error [ERR_INVALID], exit code 1

**Comment by tads421** [comment]
Good Evening, i am just trying to install composer so i can use Laravel..... i have downloaded the windows installer and i get a php settings error....

The PHP exe file you specified did not execute correctly: 
C:\xampp\php\php.exe

Running it from the command line might highlight the problem.
Internal Error [ERR_RESULT], exit code 1

i have done the log like above and it failes here

2015-04-02 20:42:11.091   DEBUG:: Checking php: C:\xampp\php\php.exe
2015-04-02 20:42:11.194   DEBUG:: Calling cmd.exe with params: /c "C:\xampp\php\php.exe setup.php -- --php --debug > C:\Users\M<username>\AppData\Local\Temp\is-ALSTC.tmp\result.txt"
2015-04-02 20:42:11.309   DEBUG:: Checking php: error [ERR_RESULT]
2015-04-02 20:42:12.844   Deinitializing Setup.

and result.txt was empty.

i can not even install from CLI.

Hope someone can help

i am running;
xampp
Windows 8.1 64bit

Thanks
Kev

**Comment by johnstevenson** [comment]
Hi, sorry you are having difficulties.

What errors do you get if you install from the CLI, rather than the windows installer?

**Comment by tads421** [comment]
if i do php readfile command i get nothing.... nothing downloads or anything.... if i put the composer.phar in a folder and run php composer.phar install i get nothing nothing happens atall... i have rebooted pc a few time but nothing makes a difference.

so on CLI i get no errors as it dose nothing lol.

Thanks for your reply.

**Comment by petermac-** [comment]
I got a similar error with an exit code of 0 and resolved the issue by un-commenting the following line in php.ini:
```php
extension_dir = "ext"
```

**Comment by Ziggizag** [comment]
In case there is a slightest PHP configuration error, Composer won't install. Double check you have no extension configuration issue in PHP startup logs. In my case I was unable to intall Composer as php_oci8.dll was missing (I switched to higher version and forgotten to remove the entry form php.ini). Funny enough - it was no issue untill I tried to install Composer!

**Comment by calvimor** [comment]
I solved this issue write full path for extension_dir and browscap in php.ini. It works fine in win 8.1 and xampp

**Comment by alexlopezit** [comment]
Thanks calvimor, this solved the issue

**Comment by maninderjitSingh** [comment]
Just wanted to add my situation too as it might help someone.
run <strong>php.exe</strong> via <strong><em>Command Prompt</em></strong>
and it should list your problem.

My problem was I activated <strong>php_mbstring.dll</strong> twice in my <strong><em>php.ini</em></strong> file

**Comment by pahom-berdyansk** [comment]
Thanks calvimor, this solved the issue! [2]

**Comment by pahom-berdyansk** [comment]
Thanks, maninderjitSingh!

**Comment by TangHao1987** [comment]
I encountered the same problem when installing on by using installer. I guess the problem is installer is trying to running php but not as a administrator so it's showing "command promote stop working..", which is same as running php in cmd.

**Comment by rquadling** [comment]
For WIndows users, there is a really useful set of free tools that I use to help diagnose issues with applications misbehaving. https://technet.microsoft.com/en-gb/sysinternals/bb842062.aspx A LOT of tools here. For this issue, ``procmon`` is what I would recommend. It allows you to watch registry and file changes as they happen, filtered by many criteria (say by process name is ``php.exe`` for example). By looking in the info column, you can see things like permission issues. So, when things fail, you can get a good idea of what the problem is. Fixing is another issue. That depends upon the problem.

**Comment by warcryta** [comment]
I had this problem too:

log.txt:

2015-11-18 11:45:49.047   Log opened. (Time zone: UTC-03:00)
2015-11-18 11:45:49.047   Setup version: Inno Setup version 5.5.4 (u)
2015-11-18 11:45:49.047   Original Setup EXE: C:\Composer-Setup.exe
2015-11-18 11:45:49.047   Setup command line: /SL5="$1209A0,220038,119296,C:\Composer-Setup.exe" /LOG=C:\log.txt
2015-11-18 11:45:49.047   Windows version: 6.1.7601 SP1  (NT platform: Yes)
2015-11-18 11:45:49.047   64-bit Windows: Yes
2015-11-18 11:45:49.047   Processor architecture: x64
2015-11-18 11:45:49.047   User privileges: Administrative
2015-11-18 11:45:49.055   64-bit install mode: No
2015-11-18 11:45:49.062   Created temporary directory: C:\Users\ADMINI~1\AppData\Local\Temp\is-HDCHS.tmp
2015-11-18 11:45:49.076   Extracting temporary file: C:\Users\ADMINI~1\AppData\Local\Temp\is-HDCHS.tmp\composer
2015-11-18 11:45:49.093   Extracting temporary file: C:\Users\ADMINI~1\AppData\Local\Temp\is-HDCHS.tmp\setup.class.php
2015-11-18 11:45:49.095   Extracting temporary file: C:\Users\ADMINI~1\AppData\Local\Temp\is-HDCHS.tmp\setup.php
2015-11-18 11:45:49.097   DEBUG:: Getting path info from registry
2015-11-18 11:45:52.550   DEBUG:: User selected Shell Menus: Do not install
2015-11-18 11:46:00.929   DEBUG:: Checking php: C:\xampp\php\php.exe
2015-11-18 11:46:01.110   DEBUG:: Calling cmd.exe with params: /c "C:\xampp\php\php.exe setup.php -- --php --debug > C:\Users\ADMINI~1\AppData\Local\Temp\is-HDCHS.tmp\result.txt"
2015-11-18 11:46:01.375   DEBUG:: Checking php: error [ERR_INVALID]

---

result.txt:


Warning: PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_oauth.dll' - %1 no es una aplicación Win32 válida.
 in Unknown on line 0
3ECDC245-751A-4962-B580-B8A250EDD1CF5.5.30
3ECDC245-751A-4962-B580-B8A250EDD1CFChecking php values, success

---
My OS is 64bit , so install oauth for that architecture before composer.

Solve this by changing  'php_oauth.dll' to 32 ( 86 )

**Comment by jeffstahlin** [comment]
petermac's solution above fixed it for me running Windows 10 with MAMP

**Comment by jozephoftl** [comment]
in your php.ini file uncomment the line : extension_dir = "ext"

**Comment by briedis** [comment]
Fresh windows 10 here, uncommenting `extension_dir = "ext"` solves the problem!

**Comment by Seldaek** [comment]
@briedis how did you install php though? You should report it to wherever you got it from so that they fix their default IMO.

**Comment by briedis** [comment]
@Seldaek I downloaded ZIP file from php.net, and just extraced to a directory. The thing is, that composer at first said that PHP is missing openssl extension. I uncommented it and tried again, but then it gave this ambiguous error message. If composer could detect missing openssl, proably it could detect missing module path too...

**Comment by curry684** [comment]
The PHP zips from php.net themselves are indeed a steaming pile of poo to configure out of the box. I don't understand the issue though, when I comment that line back out in my config `composer update` responds with:

```
  [RuntimeException]                                                                                                   
  The openssl extension is required for SSL/TLS protection but is not available. If you can not enable the openssl ex  
  tension, you can disable this error, at your own risk, by setting the 'disable-tls' option to true.          
```
What is ambiguous about that and what could be improved?

**Comment by briedis** [comment]
@curry684 The missing openssl error is fine, and as I said - uncommenting that line solved that particular error, BUT, the error for commented out extension_dir line is very unclear:
```
Running it from the command line might highlight the problem.
Internal Error [ERR_RESULT], exit code 1
```
And if you look up the log files, it contains no useful information too:
```
DEBUG:: Checking php: C:\xampp\php\php.exe
DEBUG:: Calling cmd.exe with params: /c "C:\xampp\php\php.exe setup.php -- --php --debug > C:\Users\M\AppData\Local\Temp\is-ALSTC.tmp\result.txt"
DEBUG:: Checking php: error [ERR_RESULT]
Deinitializing Setup.
```

That's how I got here, I googled `Checking php: error [ERR_RESULT]` and came upon this issue.

**Comment by curry684** [comment]
I'm confused. First you say you downloaded from http://windows.php.net/download/, which is also where I installed from. And the errors are very clear if you screw that up as I showed.

Your logs however show you installed [XAMPP](https://www.apachefriends.org/index.html), which most definitely has defaults predefined et al. I am unsure right now how to reproduce your issue, and I can't fix what I can't reproduce. As far as I can see this is an issue on XAMPP's end right now.

**Comment by briedis** [comment]
@curry684 

That XAMPP was from a comment from above. It is the same message as for a pure php install (unzip)

Ok, here are the steps just now I was able to reproduce this:

1. Download 5.6 ZIP (http://windows.php.net/download#php-5.6) 
2. Extrat to a directory
3. Run windows composer installer: https://ziedlejas.lv/screenshots/img.2016.02.11.sK96bQ.jpg
4. Get this error: https://ziedlejas.lv/screenshots/img.2016.02.11.YqQ88t.png
5. In the php directory, rename `php.ini-development` to `php.ini`
6. In `php.ini` un-comment `extension=php_openssl.dll` line
7. Run setup again and get this: `https://ziedlejas.lv/screenshots/img.2016.02.11.hgaILE.png`

The last step is where I don't know what to do, because the error message does not help.

**Comment by curry684** [comment]
This is what I get at step 7 when I follow your steps:
![verbose-php-error](https://cloud.githubusercontent.com/assets/1455673/12992196/43daaf2a-d113-11e5-9561-a6d4130b160a.png)

I don't have a fully clean Windows machine here though, and it's a development machine, so it may be in some way polluted.

**Comment by briedis** [comment]
@curry684 

Ok, you get this error if openssl extensions is *un*-commented, but `extension_dir` is commented-*out*?

**Comment by curry684** [comment]
I cleaned up a bit on my test machine and can reproduce it now indeed. I've also found the issue (after a freaking hour of notepad-debugging), in https://github.com/composer/windows-setup/blob/master/src/composer.iss#L1881

What happens: the specific combination of enabling the openssl DLL, but at the incorrect path, causes a startup error as quoted a few issues back, and as we both renamed `php.ini-development` the value for `display_startup_errors` is `on`. So [`setup.php`](https://github.com/composer/windows-setup/blob/master/src/setup.php) is executed, and it finds the system perfectly capable of running Composer so it gives return code `0`. BUT, the first line of output is not a GUID with a PHP-version behind in this case:
```
$ cmd /c "C:\Program Files\PHP\5.6\php.exe" setup.php -- --php
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\php\php_openssl.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'C:\php\php_openssl.dll' - The specified module could not be found.
 in Unknown on line 0
3ECDC245-751A-4962-B580-B8A250EDD1CF5.6.15
```
So [these rules kick in next](https://github.com/composer/windows-setup/blob/master/src/composer.iss#L1894):
```
  {
   * Possible errors:
   * Internal error - cmd did not run [ERR_CMD]
   * Internal error - cmd did not create output file run [ERR_CMD_EX]
   * ExitCode: 0 - Php check passed
   * ExitCode: 1 - Php check failed
   * ExitCode: ? - Php program error [ERR_STATUS] (Test=p1, Test=p2)
   * Results file, empty: [ERR_RESULT] (Test=p3)
   * Results file, non-matching guid: [ERR_INVALID] (Test=p4)
   * Results file, ExitCode 0, multiline [ERR_LOGIC] (test=p5)
   * Results file, ExitCode 1, guid only [ERR_LOGIC] (test=p6)
  }
```
ExitCode 0 says the PHP check passed,  but the Results file does not match the GUID, hence the cryptic `ERR_INVALID` we're seeing without any extra information - nothing went wrong technically apart from unexpected sparse output.

The problem is that this needs 2 fixes, and I can only confidently do one of them:

1. `setup.php` has to check for `openssl` to be installed.
2. The installer has to better handle unexpected startup errors, as now any thorough PHP misconfiguration will cause this vague output.

Pinging @johnstevenson in here as he might be able to fix the second one, and I can't build or deploy the installer anyway.

**Comment by johnstevenson** [comment]
The Composer installer includes a flag for allowing non-https downloads, so I will need to incorporate that into the ComposerSetup installer, in some way.

@curry684 As you have noted, this is already explained in [issue #36](https://github.com/composer/windows-setup/issues/36)

In the meantime, although not ideal, follow the instructions in the error message:

>The Php exe file you specified did not execute correctly:
>path/to/php.exe
>
>Running it from the command line might highlight the problem

So type something like ```path/to/php.exe -v``` into your command window.

**Comment by Aloha276** [comment]
Thanks @maninderjitSingh this solved my issue.

**Comment by thalesreis** [comment]
@maninderjitSingh Thanks!

**Comment by TMMC** [comment]
I had similar problem with Windows 10 x64 (PHP 7.0.6 VC14 x64 Thread Safe as Apache Module + Apache 2.4.20 x64) and Composer version 1.0.3. 
```
The PHP exe file you specified did not run correctly [exit code 1]
```
Cleaning with `cleanmgr.exe` and _CCleaner_ + system restart helped and I was able to install Composer.

**Comment by Mohannadz** [comment]
tried @pmaingi link in it worked fine for me on Win10.

**Comment by deanclarkeinfotech** [comment]
![image](https://cloud.githubusercontent.com/assets/19689776/16172898/4cf5b67a-3560-11e6-8d1b-a94a212d0bcf.png)


Having this issue. please assist

**Comment by johnstevenson** [comment]
The original issue is closed. Could you report this new one here please: [https://github.com/composer/windows-setup](https://github.com/composer/windows-setup). It would be helpful if you can include the log file, as described in the _Troubleshooting_ section in the README.

**Comment by Jany-M** [comment]
Had the same issue, but fixed it like this:
Make sure that in your `php.ini`, there's always the HDD letter before the xampp folder, in every relative path.

eg. `browscap = **"D:**\Dropbox\__WORK_IN_PROGRESS__\__xampp__\php\extras\browscap.ini"`

**Comment by weiwait** [comment]
i has the issue too. finally, i setting a new windows user, because the previous windows user name has a & character, the & character is specially. may be you can reference.

**Comment by johnstevenson** [comment]
@weiwait What particular issue did you have? This thread mentions many.

**Comment by allyg90** [comment]
I got error:
**The PHP exe file you specified did not run correctly [exit code 1]:
C:\xampp\php\php.exe

No output was returned.**

The solution was what @weiwait said.
I set up a new user without any "&" involved in the windows user and it worked!!

**Comment by johnstevenson** [comment]
@allyg90 Could you please attach your log file, as described here: https://github.com/composer/windows-setup#Troubleshooting

Alternatively you could open a new issue: https://github.com/composer/windows-setup/issues

**Comment by pt67** [comment]
I got same problem with window 10 64bit OS.

The PHP exe file you specified did not run correctly:
C:\xampp\php\php.exe

The php.ini used by your command-line PHP is: C:\xampp\php\php.ini

A setting in your php.ini could be causing the problem: Either the 'extension_dir' value is incorrect or the dll does not exist.

Program Output:
PHP Warning:  PHP Startup: Unable to load dynamic library 'interbase' (tried: C:\xampp\php\ext\interbase (The specified module could not be found.), C:\xampp\php\ext\php_interbase.dll (The specified module could not be found.)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'oci8_12c' (tried: C:\xampp\php\ext\oci8_12c (The specified module could not be found.), C:\xampp\php\ext\php_oci8_12c.dll (The specified module could not be found.)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_firebird' (tried: C:\xampp\php\ext\pdo_firebird (The specified module could not be found.), C:\xampp\php\ext\php_pdo_firebird.dll (The specified module could not be found.)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_oci' (tried: C:\xampp\php\ext\pdo_oci (The specified module could not be found.), C:\xampp\php\ext\php_pdo_oci.dll (The specified module could not be found.)) in Unknown on line 0
PHP Warning:  Module 'openssl' already loaded in Unknown on line 0
MIB search path: c:/usr/share/snmp/mibs
Cannot find module (IP-MIB): At line 0 in (none)
Cannot find module (IF-MIB): At line 0 in (none)
Cannot find module (TCP-MIB): At line 0 in (none)
Cannot find module (UDP-MIB): At line 0 in (none)
Cannot find module (HOST-RESOURCES-MIB): At line 0 in (none)
Cannot find module (SNMPv2-MIB): At line 0 in (none)
Cannot find module (SNMPv2-SMI): At line 0 in (none)
Cannot find module (NOTIFICATION-LOG-MIB): At line 0 in (none)
Cannot find module (UCD-SNMP-MIB): At line 0 in (none)
Cannot find module (UCD-DEMO-MIB): At line 0 in (none)
Cannot find module (SNMP-TARGET-MIB): At line 0 in (none)
Cannot find module (NET-SNMP-AGENT-MIB): At line 0 in (none)
Cannot find module (DISMAN-EVENT-MIB): At line 0 in (none)
Cannot find module (SNMP-VIEW-BASED-ACM-MIB): At line 0 in (none)
Cannot find module (SNMP-COMMUNITY-MIB): At line 0 in (none)
Cannot find module (SNMP-FRAMEWORK-MIB): At line 0 in (none)
Cannot find module (SNMP-MPD-MIB): At line 0 in (none)
Cannot find module (SNMP-USER-BASED-SM-MIB): At line 0 in (none)
Cannot find module (SNMP-NOTIFICATION-MIB): At line 0 in (none)
Cannot find module (SNMPv2-TM): At line 0 in (none)

**Comment by dasri-cpu** [comment]
![IMG-20200425-WA0001](https://user-images.githubusercontent.com/64216262/80273471-76b9f380-86fc-11ea-841c-54756f05cde9.jpeg)
What the purpose,?

**Comment by curry684** [comment]
....so you took a screenshot by photographing your screen at this angle?

The error indicates you have no working network and/or DNS servers.
