### ISSUE TITLE
vcs (git) + file:// URIs makes composer throw different kind of exceptions

### ISSUE THREAD

**Issue by ktomk** [composer/composer#3338]
Exceptions in issue:

1. [RuntimeException] Directory does not exist: <path>
2. [ErrorException] proc_open(): CreateProcess failed, error code - 267

I don't know if this a regression (#3285 <del>#3294</del>).

> Composer version 73e9db5d9952d52a46ecbc20a269a8c5f9c5b011 2014-10-07 15:03:19

Taking the following composer.json as base:

    {
        "repositories": [
            {
                "type": "vcs",
                "url": "file:///c:/Users/DB/PhpstormProjects/Net_URL2/.git/"
            }
        ],
        "require": {
            "pear/net_url2": "dev-topics/composer-for-pear"
        }
    }

will report this exception:

    $ composer install
    Loading composer repositories with package information

      [RuntimeException]
      Directory does not exist: /c:/Users/DB/PhpstormProjects/Net_URL2/.git/

    [...]

at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Repository/Vcs/GitDriver.php:230

albeit:

    $ php -r 'var_dump(is_dir("file:///c:/Users/DB/PhpstormProjects/Net_URL2/.git/"));'
    bool(true)

This was the first problem I encountered. Removing the trailing slash:

    ...
    "repositories": [
        {
            "type": "vcs",
            "url": "file:///c:/Users/DB/PhpstormProjects/Net_URL2/.git"
        }
    ],
    ...

 makes composer wanting to do more:

    $ composer install
    Loading composer repositories with package information
    
    
    
      [ErrorException]
      proc_open(): CreateProcess failed, error code - 267
    
    [...]

This now is at

Executing command (/c:/Users/DB/PhpstormProjects/Net_URL2/.git): git show-ref --tags

    Exception trace:
     () at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/process/Symfony/Component/Process/Process.php:287
     Composer\Util\ErrorHandler::handle() at n/a:n/a
     proc_open() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/process/Symfony/Component/Process/Process.php:287
     Symfony\Component\Process\Process->start() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/process/Symfony/Component/Process/Process.php:20
    4
     Symfony\Component\Process\Process->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Util/ProcessExecutor.php:62
     Composer\Util\ProcessExecutor->execute() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Repository/Vcs/GitDriver.php:183
     Composer\Repository\Vcs\GitDriver->getTags() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Repository/Vcs/GitDriver.php:86
     Composer\Repository\Vcs\GitDriver->initialize() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Repository/VcsRepository.php:86
    ...

I can reproduce both exceptions as well in cmd, not only in git bash. Windows 8.

**Comment by Seldaek** [comment]
Any clue if this is still relevant?

**Comment by ktomk** [comment]
@Seldaek: I would need to review it. I'm not so motivated right now for a review on Windows. But so far I checked it against a Linux for some URLs and they do work:

- file:///path/to/PhpstormProjects/Net_URL2/.git/
- /path/to//PhpstormProjects/Net_URL2/.git/

When it comes to percent-encodings, still no driver is found to handle VCS repository:

- file:///path/to/PhpstormProjects/N%65t_URL2/.%67it/

**Comment by Seldaek** [comment]
Well yeah we don't do any URL decoding.. It's a path, not a web server :)

I'm pretty sure local paths wokr on windows though, maybe without file:// prefix, or maybe just with file:// (no triple slash). Anyway I'll close for now, if you can reproduce it for real feel free to reopen.

**Comment by ktomk** [comment]
Percent encoding has nothing to do with a web-server at all, the URI is about identifying a resource, not fetching it. Here is a command-line example, no web-server involved:

    $ git clone file:///path/to/PhpstormProjects/N%65t_URL2/.%67it/ test
    ...
    (works as intended)

This is different to the local path syntax:

    $ git clone /path/to/PhpstormProjects/N%65t_URL2/.%67it/ test
    fatal: repository '/path/to/PhpstormProjects/N%65t_URL2/.%67it/' does not exist
    (errors as expected)

So you're wrong on the URL decoding: As long as you're processing an URL you need to adhere to it's encoding if you access the encoded information from it. This involves decoding, and some may suggest as well normalization, however as the git-clone-example shows, normalization is not done by git (at least in the version I used).

**Comment by Seldaek** [comment]
What I meant by it's not a web server is that the only way these URLs get into a composer.json is if a human puts it there, and generally these will be either URLs to a remote server (in which case I suspect we should pass the url-encoding along), or it's a local path (in which case I don't see why one would have url encoding in there, except to cause issues willingly). That's why IMO it's not worth fixing.

**Comment by ktomk** [comment]
Yeah, in the end, alll data entered into a computer was once by a human. That was just about proper URL-encoding and just a note in the margin, and obviously not about the original report you asked about.

It was just I had a *nix system at hand, but not a windows box.

I now found some time and opportunity to check this against a fine, oldskool non-virtualized, original fresh pale Windowze sys and a fresh composer setup (composer version 1.0.1 2016-04-18 21:14:28), [getcomposer.org/download does not give a hint nor link to upgrade to the unstable channel btw. if you're interested to get feedback from early adopters, I dunno].

And the exception has shifted. It's now:

~~~
PLACEHOLDER (edit and paste from the windows box here)
~~~

As you can see I tested this against a pre Win7 system with fine spaces in the path of which you require not to have any encoding of as PHP itself won't handle percent-encoded spaces (%20) properly. The `is_dir` test with the PHP stream `file://` wrapper still stands:

~~~
PLACEHOLDER (edit and paste from the windows box here)
~~~

So just in case you really wanted to know how this report changed over time.

As the manual tests show, it's still a "true" (tm) issue. You most likely will continue to say it's not worth fixing (I guess, no pun intended) and I have to admit at this point, even I still have that system at hand for testing, it's really somewhat remote. I don't have this problem practically as a developer at the moment, so you can keep this issue closed (despite a bug, IMHO you  should fix this for the underlying issue (in the long run) but it's an encoding problem that is inherited into composer at some and different places).

Full backtrace to complete the report:

~~~
PLACEHOLDER (edit and paste from the windows box here)
~~~

**Comment by Seldaek** [comment]
OK so there were two issues here, one which was a real bug was that we didn't handle `file:///c:/` as a valid path, while it seems php accepts it. The other one which is more of a mis-use on your part but is easy enough to handle so might as well fix it, is that vcs repos are supposed to point to the repository directory, not its .git directory directly.

These are now fixed (see commits linked above).

**Comment by Seldaek** [comment]
Note that spaces in paths have no impact whatsoever, unless you url-encode them maybe, I didn't check that as I still don't think that's worth even considering :)

**Comment by ktomk** [comment]
Thanks for the quick patches, I need to test them on that system which I haven't yet but I could find the time to review the changes and your comments.

I do see the trailing slash "issue" and how you encountered it, IMHO, if a local path and a directory POSIX allows to remove the trailing slash. If not a directory, the path should not end with a directory separator. So that should be safe.

I could however test without the trailing slash and get a different error then in my version:

~~~
{
    "repositories": [
        {
            "type": "vcs",
            "url": "file:///c:/Dokumente und Einstellungen/mot/PhpstormProjects/Net_URL2/.git"
        }
    ],
    ...
~~~

> proc_open(): CreateProcess failed, error code - 267

That is for the directory 

> `/c:/Dokumente und Einstellungen/mot/PhpstormProjects/Net_URL2/.git`

which does not exists ([error code reference and PHP example](http://stackoverflow.com/questions/30296288/php-warning-proc-open-createprocess-failed-error-code-267)).

The error is given because of the leading slash, removing it like in:

~~~
{
    "repositories": [
        {
            "type": "vcs",
            "url": "file://c:/Dokumente und Einstellungen/mot/PhpstormProjects/Net_URL2/.git"
        }
    ],
    ...
~~~

does alleviate the problem.

----

About the spaces in the paths: IIRC (can't excavate any reports from bugs.php.net right now) For a correct URL they need percent-encoding. But the PHP file://-wrapper does not support percent-encoding.

A quick test does confirm this, with spaces accepted by the PHP file-wrapper, URL-encoded denied:

~~~
$ php -r 'var_dump(is_dir("file:///c:/Dokumente und Einstellungen/mot/PhpstormProjects/Net_URL2/"));'
bool(true)
~~~

Percent-encoding according to RFC 3986:

~~~
$ php -r 'var_dump(is_dir("file:///c:/Dokumente%20und%20Einstellungen/mot/PhpstormProjects/Net_URL2/"));'
bool(false)
~~~

Worth considering? At least you should know about this detail. I can only say that sometime this will need a fix here or there or at least some treatment.

**Comment by ktomk** [comment]
Tested against 1.0.2 and it now works without the  - 267 error. Also tested with a bare repository named .git ;) - Works so far.
