### ISSUE TITLE
pear bundled projects / shared vendor / PSR-0 autoloading combined

### ISSUE THREAD

**Issue by ktomk** [composer/composer#3340]
while adding composer support to pear packages, it is that for each pear library a single project folder is created within the `vendor/pear` folder.

as pear has a lot of old code pre-dating autoloading the include_path setting in combination with `require_once` is used.

this was not much of a problem within pear because it created one big tree, so one include-path directory entry was sufficient for whole pear.

now when picking exemplary the `pear/http_request2` package which depends on `pear/net_url2` and `pear/pear_exception` this will put three additional paths into the include path setting. all of these three are pretty similar:

    string(218) "C:\Users\DB\Temp\test-neturl2-composer\vendor/pear/pear_exception;C:\Users\DB\Temp\test-neturl2-composer\vendor/pear/net_url2;C:\Users\DB\Temp\test-net
    url2-composer\vendor/pear/http_request2;.;c:\Program Files\php\pear"
    include_path has 5 path(s):
     # 00 'C:\Users\DB\Temp\test-neturl2-composer\vendor/pear/pear_exception'
     # 01 'C:\Users\DB\Temp\test-neturl2-composer\vendor/pear/net_url2'
     # 02 'C:\Users\DB\Temp\test-neturl2-composer\vendor/pear/http_request2'
     # 03 '.'
     # 04 'c:\Program Files\php\pear'

this is most likely the reason why the include-path setting is deprecated.

is there anything (feature/flag/installer) that could lift this situation? these projects all follow PSR-0 and are similarly configured for auto-loading:

    vendor/pear/http_request2/composer.json:
        "autoload": {
            "psr-0": {
                "HTTP": "./"
            }
    vendor/pear/net_url2/composer.json:
        "autoload": {
            "psr-0": {
                "Net": ""
            }
    vendor/pear/pear_exception/composer.json:
        "autoload": {
            "psr-0": {
                "PEAR": ""
            }

so if there would be some kind of new option to merge PSR-0 paths per vendor or similar would already do it.

**Comment by Seldaek** [comment]
I don't think this is going to happen if we're realistic here, PEAR packages that are still useful can and definitely should be upgraded to drop this require_once legacy. Old tags remain there for old users, and new tags can be made available to Composer only and not published on PEAR.

**Comment by ktomk** [comment]
Jup, it's not so easy in practice because of the requirements on each other. However, I guess progress is there, just slowly. I suggested patches upstream so that it works better. For anyone interested the references are:

- https://github.com/pear/HTTP_Request2/pull/11
- https://github.com/pear/HTTP_Request2/commit/0b422776d1f01725a30f0f586ee73e3afb678bb8
- http://stackoverflow.com/questions/31484814/warning-require-oncenet-url2-php-failed-to-open-stream

just in case it's a helpful pattern for others to follow. now just waiting for upstream http_request2 to release with composer support.
