### ISSUE TITLE
Should post-install / post-update scripts run even on a failure, if >=1 packages were installed / updated

### ISSUE THREAD

**Issue by driskell** [composer/composer#3341]
Hi,

I'm using magento-composer-installer installer module. Maybe this issue is more their side but I thought I'd start a discussion here.

To save on running tasks on every package install, magento-composer-installer seems to listen to the post-package events to queue up tasks, and then perform them in bulk on post-install / post-update.

Now, this works perfectly fine if everything runs swimmingly. However, if one of the packages fails to install - for example, due to connectivity issue to the repository - the post-install / post-update script is never called, and composer exits with an error. I've seen this happen on the last package, and thus when you run composer again, it only needs to installs THAT package - but when post-install / post-update runs the magento-module-installer only knows of that one package, and thus the tasks for the others were never called.

My question is: should composer be signalling the post-install / post-update scripts even if it fails, if the number of package installs / updates is not zero? I'm willing to assist with a patch if this is reasonable. Maybe there should also be an additional argument to this event, stating success/failure?

It could just be that the method magento-composer-installed uses to bulk the tasks at the end is the problem. But maybe in this case, implementing the post-install / post-update even on failure could be the better resolution, as it will mean the installer can still bulk tasks at the end.

*NB: I found a workaround, which is to run the magento-module-deploy extra command provided by the magento-module-installer. However, it feels like I'm taping over a crack - if composer ran successfully and we still run this, we've run the tasks twice - and if composer didn't run successfully, we're still doubling SOME of the tasks. Luckily they're all idempotent but that's not a requirement.*

Thanks!

Jason

**Comment by Seldaek** [comment]
I see your point but I am not sure how to best handle this, as calling it as usual when it actually failed could lead to bad outcomes as well in some cases I imagine, where people have built things with an expectation that things ran fine. We could perhaps add a new event name on failure, but then people would need to listen to both which is also not ideal. I'm open to suggestions.
