### ISSUE TITLE
extend global command to update the path env var

### ISSUE THREAD

**Issue by jakoch** [composer/composer#3350]
The [global command](https://getcomposer.org/doc/03-cli.md#global) can be used to install CLI utilities, like php-cs-fixer globally into the `$COMPOSER_HOME/vendor/` folder.  A shortcut for the util is created at `$COMPOSER_HOME/vendor/bin`. 
But this folder is not automatically added to the $PATH environment variable. 

I'm suggesting 
- [ ] to add a check, if `$COMPOSER_HOME/vendor/bin` is already on $PATH
- [ ] if not, provide a dialog to ask the user, whether to add it or not
- [ ] provide "--no-interactive" with the default behaviour of appending to the PATH

A call like `php composer.phar global require fabpot/php-cs-fixer:dev-master --no-interactive`
would result in a working on path installation of `php-cs-fixer` without any user interaction required.

**Comment by Seldaek** [comment]
I think modifying the PATH is maybe over-reaching and too hard to achieve but what could be a nice improvement is just outputting a warning with the global bin-dir absolute path so that people get easy access to it and see that it should be added.
