### ISSUE TITLE
Missing Support for Stability Flags in 'require' Command

### ISSUE THREAD

**Issue by jonmchan** [composer/composer#3367]
```bash
$ composer.phar require "vierbergenlars/php-semver": "dev-master@dev"


                                                                                                                                                  
  [InvalidArgumentException]                                                                                                                      
  Could not find package dev-master@dev at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability 
```

It would appear stability flags @dev, @stable, etc. is not supported with the require command. When I manually add the line with stability flags to composer.json and then run ```composer.phar update``` it updates as expected applying the stability flags.

I believe it would be good to have consistent behavior with the stability flags across both the ```require``` command and the ```update``` command.

**Comment by aivus** [comment]
Have the same issue

**Comment by sibprogrammer** [comment]
Looks like invalid report.

You should remove the space between package name (after colon) and version.
Right: composer require "doctrine/orm":"2.5.*@dev"
Wrong: composer require "doctrine/orm": "2.5.*@dev"

**Comment by pjcdawkins** [comment]
I wasn't adding the extra space, but this now appears to work. It looks like the behaviour of `require` has changed quite a bit (https://github.com/composer/composer/commit/859c8f5bb3b8998e351c1dd52aab8d46e81cb222)

**Comment by krewetka** [comment]
@sibprogrammer - thanks for hint :+1: 

I copied package path from packagist, for example :https://packagist.org/packages/sonata-project/media-bundle

and there is always space in ``"sonata-project/media-bundle": "2.4.*@dev"``

**Comment by stof** [comment]
@krewetka Packagist gives you the line to put in the composer.json file, not the arguments for the ``composer require`` command.
such spaces are perfectly valid in JSON.

**Comment by krewetka** [comment]
Ok, I know but still message about "Could not find package [...] at any version for your minimum-stability (stable)" is a bit misleading :)

When I found a new package and wanted to add it without changing composer.json file and updating it I was using require. I copied names of packages from packagist as this was the easiest way :)

**Comment by ianchanning** [comment]
I've just stumbled on this too - trying to use the commands from packagist to run a `composer global require ...`

**Comment by robinclark007** [comment]
i try 
composer require doctrine\dbal   //not work at all
but after I add sudo .it works for me 
sudo composer require doctrine\dbal ////woking

**Comment by pjcdawkins** [comment]
As suggested above, https://github.com/composer/composer/issues/3367#issuecomment-74987207, this is an invalid issue.

robinclark007: you are using a backslash, it should be a forward slash (`doctrine/dbal`).

**Comment by nevvermind** [comment]
I don't see this as a bug, just slightly confusing for people who don't know how args work or who don't know that the "require" command _can_ take an array or args (which are separated by spaces).   
In which case the problem becomes obvious: composer thinks you're passing _multiple_ packages, hence the
`Could not find package dev-master@dev at any version for your minimum-stability (stable).` error, because you're sending **two** args: `vierbergenlars/php-semver:` and `dev-master@dev`.

Other valid ways are `"vierbergenlars/php-semver:dev-master@dev"` and `"vierbergenlars/php-semver":\ "dev-master@dev"`.

But I agree that the text in packagist is a little misdirecting.

**Comment by ianchanning** [comment]
@nevvermind cheers for fixing it

**Comment by sitetester** [comment]
I was facing the same issue while installing pdfparser. Fixed it by using "sudo composer global require smalot/pdfparser"

**Comment by nevvermind** [comment]
@Seldaek - I think you can close this.

**Comment by Seldaek** [comment]
Right I missed that when taking care of the PR, thanks

**Comment by khyrulimam** [comment]
composer require vendor/package=dev-master

**Comment by duyngha** [comment]
@khyrulimam It's working. But I wonder why we need "=dev-master" at the end of command line? Whether I can create a package and require it without "=dev-master"?

**Comment by ajcastro** [comment]
READ THIS FYI.
https://igor.io/2013/02/07/composer-stability-flags.html

**Comment by darrensapalo** [comment]
@ajcastro for some reason, the link you posted above is dead.
