### ISSUE TITLE
[RFC] "namespace" composer global  require.

### ISSUE THREAD

**Issue by lyrixx** [composer/composer#3370]
### The problem 1:

If I run
```
composer global require phpunit/phpunit
# and a package that depends on symfony/http-request, or directly
composer global require symfony/http-foundation
```

I got a new phpunit and http-foundation package.
So, I my test suite, If I forgot to install vendor, the following code

```php
    public function testSupportNok()
    {
        $bitbucket = new Bitbucket();



$reflector = new \ReflectionClass('Symfony\Component\HttpFoundation\Request');
echo $reflector->getFileName();
die;
        $this->assertFalse($bitbucket->support(new Request()));
    }
```

will output:

```
[...]
/home/greg/.composer/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Request.php
```

So, first, it's hard to understand If you are not aware of this `global` behavior

### Probleme 2

If 

* package A depends on symfony-console 2.3 (no ~2.3)
* package B depends on symfony-console 2.5

=> It will not be possible to install both packages.

### Solution:

Instead of sharing everything, composer should namespace each package.
So something like that:

```
├── bin
│   ├── gh -> gh/bin/gh
│   └── phpunit -> phpunit/phpunit.php
├── gh
│   ├── bin
│   │   └── gh
│   ├── src
│   │   └── SensioLabs
│   │       └── Gh
│   │           └── Application.php
│   └── vendor
│       └── symfony
│           └── console
└── phpunit
    ├── phpunit.php
    ├── src
    └── vendor
        ├── phpunit
        └── symfony
            ├── console
            └── yaml
```

What do you think?

**Comment by Seldaek** [comment]
I think this could be built as an external tool fairly easily using the --working-dir (-d) argument to change the working directory, all you need is something like:

`zomg install phpunit phpunit/phpunit` => calls `mkdir -p ~/.composer/phpunit/ && composer -d ~/.composer/phpunit/ require phpunit/phpunit`

Done :p
