### ISSUE TITLE
i want to download all of the package of https://packagist.org/ to make a local mirror is there a good way to do ?

### ISSUE THREAD

**Issue by HelloLin** [composer/composer#3373]
i want to download all of the package of https://packagist.org/. so i can use composer install without a internet. is there a good way?
i hope you can help me ,thank you.

**Comment by imatsu** [comment]
I'm looking for the same solution

For example , in some Latin American countries there is no Internet connection, it is for this reason that some of us turn to make mirrors of Linux distributions like Debian to have it on hand in case we need to install a package , just as happens in application development .

Imagine for a moment that you have a laptop and the only place where you can access an internet connection is at work or university, then you take your laptop every day you require a new package and we all know that programmers are more productive at night; you are also exposed to being robbed or even killed for you take your laptop .

**Comment by minkbear** [comment]
I'm looking for that as well.

Is it possible to use composer archive command to create offline package and then use artifact for composer update?

**Comment by Seldaek** [comment]
No there is no real way to mirror except https://toranproxy.com that will do it on the fly for the packages you use. Mirroring everything has been done by some Chinese folks http://pkg.phpcomposer.com/ but I don't think any script is available publicly.
