### ISSUE TITLE
Inline alias of branch alias

### ISSUE THREAD

**Issue by mpoiriert** [composer/composer#3374]
I am trying to use a branch-alias set in the dev-master as a inline alias all of those don't work

```JSON
{ 
  "require": { 
    "company/package": "dev-3.1 as dev-feature" ,
    "company/package": "3.1@dev as dev-feature" ,
    "company/package": "3.1.*@dev  as dev-feature",
    "company/package": "dev-3.1.*@dev  as dev-feature",
    "company/package": "dev-3.1.*  as dev-feature",
    "company/package": "3.1.*@  as dev-feature",
    "company/package": "3.1 as dev-feature"
  }
}
```

If i am not using a inline alias this does work

```JSON
{ 
  "require": { 
    "company/package": "3.1.*@dev"
  }
}
```

When I say it does work it mean that it can be dowloaded but if i am using another package that need the company/package with the branch dev-feature it doesn't work since both cannot be installed...

I am expecting those to work:

```JSON
{ 
  "require": { 
    "company/package": "3.1.*@dev  as dev-feature",
    "company/package": "dev-3.1.*  as dev-feature"
  }
}
```

Is it a bug OR a configuration problem on my side ?

**Comment by Seldaek** [comment]
This has been fixed since. You now get a proper exception for unclear alias sources:

```
  Could not parse version constraint * as 2.0: Invalid version string "*" in "* as 2.0", the alias source must be an
  exact version, if it is a branch name you should prefix it with dev-
```

And for the `dev-master#gitref as 2.5.0`, that is now supported.
