### ISSUE TITLE
RequireCommand does not take php-version into account

### ISSUE THREAD

**Issue by staabm** [composer/composer#3381]
I have a project, which requires PHP 5.3 (which is defined in its `composer.json`) . yeah... I know...

I used `composer require` cli command to add a new package to it. This worked without any errors.
The package added required at least PHP 5.4 (which was also defined in its `composer.json`), therefore I later on got errors on my php5.3 servers.

I expected composer to at least warn me at the moment I installed the new package using `composer require`.
ATM I only relalized the php version problem while testing on our legacy php 5.3 servers - which was rather late, because a big part of the software was already built and a lot of time was wasted.

Of course, this problem is not limited to the old php version we are using, and could have happend with a mix auf 5.5 or 5.6 etc.

**Comment by elazar** [comment]
@Intrepidity I can't say that's been my experience. See satooshi/php-coveralls#81.

**Comment by Seldaek** [comment]
This will be fixed by #2990 IMO which I hope to merge in the nearish future.

**Comment by staabm** [comment]
fixed with  #2990
