### ISSUE TITLE
[feature] Warn option that warns user before completing an update

### ISSUE THREAD

**Issue by 2upmedia** [composer/composer#3396]
Here's a use case.

You wrote a package, made it public, for some reason you introduced a bug, time passed by and now people rely on the bug and have written their own workaround to deal with it. You realize the bug needs to be fixed, but that it will NOT be "technically" backwards compatible. So you write the hotfix and publish it as an emergency fix. User runs composer update and BAM, their software breaks so they frantically try to figure out why.

It would be nice if there was a warn option where you specify the affected versions and before upgrading from those. There would be an interactive warning message that would not allow the user to complete the update unless they confirm they understand. There should also be support for ignoring this interactive prompt for things like continuous integration, etc.

**Example**

Client composer.json:

```json
{
    "require": {
        "namespace/package": "~0.2"
    }
}
```

Current version in lock file is 0.2.3

Package composer.json:
```json

{
    "name": "namespace/package",
    "version": "0.2.9",
    "require": {
        "php": ">=5.4"
    },
    "warn": {
        "~0.1.0; ~0.2.0": "0.2 is not backwards compatible",
        ">=0.2,<=0.2.8": "The mandatory hotfix for side-effect bug is backwards incompatible. Please see changelog for more information before upgrading"
    }
}
```

    $ composer update
    Warning: You are upgrading "namespace/package" from 0.2.3. Versions >=0.2,<=0.2.8 are affected. The mandatory hotfix for side-effect bug is backwards incompatible. Please see changelog for more information before upgrading.

Once they get the warning, they perhaps decide they don't have time to deal with removing their workaround so they would then just specify the specific version that's still BC compatible in their composer.json file.

```json
{
    "require": {
        "namespace/package": "0.2.8"
    }
}
```

    $ composer update
    [...]
    Generating autoload files

**Warn format**

    "warn": {
        "AFFECTED_VERSION(S) [ ; TO_VERSION(S) ]": "[WARNING MESSAGE]"
    }

Omitting the TO_VERSIONS would mean any version higher than the ones in AFFECTED_VERSIONS.

Unless I'm missing something, right now, the only real options for the above are "suggest", but that doesn't stop an update and you're most-likely not going to read it. It's also not semantically correct to use in this situation. The other option is just warning through the README, which wouldn't stop an update from introducing the backwards incompatible version.

Thoughts?

**Comment by Seldaek** [comment]
IMO the way to warn is to release a major release, as that is clearly advertised to people as BC-breaking, they are more likely to check the changelog before upgrading blindly. Having all sorts of random warnings from various packages would just end up being ignored by people..
