### ISSUE TITLE
[Feature] Adding processing autoloading sections to the command line interface

### ISSUE THREAD

**Issue by nyamsprod** [composer/composer#3398]
As of now, the only way to interact with the autoloading sections in the `composer.json` file is to used the `dump-autoload` command. If the following commands are implemented the `composer.json` file could be better handle using the command line utility:

## require-autoload

The `require-autoload` command adds new namespace or path to the composer.json file from the current directory.

```bash
php composer.phar require-autoload psr4 "My\\Awesome\\Package\\" "src/" 
php composer.phar require-autoload psr0 "My\\Awesome\\Package\\" "src/" 
php composer.phar require-autoload classmap "src/"
php composer.phar require-autoload files "src/MyLibrary/functions.php"
```

After adding/changing the autoload, an implicit `dump-autoload` should be run

### Options

- **--dev:** changes affect the `autoload-dev` section

## remove-autoload

The `remove-autoload` command removes namespaces or path to the composer.json file from the current directory.

```bash
php composer.phar remove-autoload psr4 "My\\Awesome\\Package\\"
php composer.phar remove-autoload psr0 "My\\Awesome\\Package\\"
php composer.phar remove-autoload classmap "src/"
php composer.phar remove-autoload files "src/MyLibrary/functions.php"
```

After adding/changing the autoload, an implicit `dump-autoload` should be run

### Options

- **--dev:** changes affect the `autoload-dev` section

## Adding the commands to the interactive Init routine

The `require-autoload` command should be added to the interactive init routine to ease `composer.json` creation.

## Open questions:

- The `require-autoload` could be named `add-autoload`. For consistency, I've chosen to call it this way to align with the `require` command.
- The argument order for the `psr4/psr0` could be changed in the `require-autoload` command to make it more consistent with `classmap/files` addition.

In this alternative, the path is always listed after the chosen autoloading type.

```bash
php composer.phar require-autoload psr4 "src/" "My\\Awesome\\Package\\" 
php composer.phar require-autoload psr0 "src/" "My\\Awesome\\Package\\" 
php composer.phar require-autoload classmap "src/"
php composer.phar require-autoload files "src/MyLibrary/functions.php"
```

Thoughts and comments are welcomed

**Comment by jmleroux** [comment]
Is there any WIP PR on this subject ?

**Comment by curry684** [comment]
Isn't it for complex modifications like this far more practical to just script it yourself?
```php
$myFile = json_decode(file_get_contents('composer.json'));
$myFile['autoload']['psr-4']["My\\Awesome\\Package\\"] = 'src/';
file_put_contents('composer.json', json_encode($myFile, JSON_PRETTY_PRINT));
```
I don't really see all that much point to add separate commands for every kind of modification possible - it's a JSON file so everybody can (machine) modify it easily.

**Comment by Seldaek** [comment]
Yup I don't think we really want to offer this from CLI it's gonna be a bunch of code for very limited use as typically this is done once on package creation.

**Comment by ktomk** [comment]
JSON is not so easy to deal with from command-line. Mabye based on @curry684 suggestion it's possible to have some *"json"* command so composer is providing it on it's own to the command-line?

**Comment by docteurklein** [comment]
I would be interesting in a built-in solution in composer CLI as well, but since it seems not to be a wanted feature, I ended up writing a one-liner for this:

`cat composer.json | jq --indent 4 '.autoload."psr-4" |= . + {"Test\\NS": "src"}' | tee composer.json`

or a more generic, reusable approach to put in your `~/.*shrc` :

```
function composer-autoload {
    local script=$(cat <<JQ
    .autoload."psr-4" |= . + {"$1": "$2"}
JQ
)
    cat composer.json | jq --indent 4 "$script" | tee composer.json > /dev/null && composer dump-autoload
}
```

**Comment by docteurklein** [comment]
Sorry for the necrothread, but I find current state of autoload handling a bit complicated (coming up with a valid autoload section in the first try is not something I achieve often).


Would it be amazing if composer provided a way to **guess** autoload ?

   composer guess-autoload src/Test.php

where `src/Test.php` contains

```php
<?php namespace Acme\App { class Test {} }
```
would add an autoload entry containing:

```json
"psr-4": { "Acme\\App\\": "src" }
```

**Comment by hparadiz** [comment]
I'm writing a command line tool for my framework to initialize (bootstrap) a new project.
![image](https://user-images.githubusercontent.com/195216/40266776-0c2279f8-5b1f-11e8-9527-df31be18c9ab.png)

I ended up using this code for it:
```php
file_put_contents($composer, json_encode($json, JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));
```

The file comes out fine. Perfectly acceptable even for a brand new project. I am weary of running this on existing large projects however as I'm not sure about how this will end up ordering the json data.

**Comment by KEINOS** [comment]
> PS: It's kinda horrible to edit json by hand @docteurklein 

I agree. Hate to think about slash and escape from JSON. It's a horror.

So far @curry684 's [suggestion](#issuecomment-203443135) is reasonable for me.

But I +1 for this feature though. Since many documents tell us to edit and add by hand (via editor).

**Comment by CaliforniaMountainSnake** [comment]
The one-liner for set some autoload path in `composer.json`:

```bash
php -r '$json = json_decode(file_get_contents ("composer.json"), true);$json["autoload"]["psr-4"]["CaliforniaMountainSnake\\SomePackage"] = "CaliforniaMountainSnake/SomePackage/";file_put_contents("composer.json", json_encode($json, JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT));'
```

**Comment by devnll** [comment]
+1 for this feature. It seems odd this exists for `repositories` and `extra` but not `autoload` :(

On my system, using `json_decode`/`encode` as suggested causes subsequent use of `composer require` to fail because it expects this (object):
```json
"require": {},
```
but `composer.json` contains this (array):
```json
"require": [],
```

The solution is to decode to an object (instead of an array), which also means adding the autoload section via object properties (instead of array indexes):
```php
$json = json_decode(file_get_contents("composer.json"));  // object, not array (no second arg)
$json->{"autoload"}->{"psr-4"}->{"DevNll\\Package\\"} = "src/";  // object properties, not array indexes
file_put_contents("composer.json", json_encode($json, JSON_PRETTY_PRINT));'
```

**Comment by devnll** [comment]
+1 for this feature. It seems odd this exists for `repositories` and `extra` but not `autoload` :(

Something I encountered, in case it might be helpful:

On my system, using `json_decode`/`encode` as suggested results in a `composer.json` that causes subsequent use of `composer require` to fail because it expects this (object):
```json
"require": {},
```
but `composer.json` contains this (array):
```json
"require": [],
```

I got it working by decoding to an object (instead of an array), which also meant adding the autoload section via object properties (instead of array indexes):
```php
$json = json_decode(file_get_contents("composer.json"));  // object, not array (no second arg)
$json->{"autoload"}->{"psr-4"}->{"DevNll\\Package\\"} = "src/";  // object properties, not array indexes
file_put_contents("composer.json", json_encode($json, JSON_PRETTY_PRINT));'
```

**Comment by 4n70w4** [comment]
Hi! The same issue! I use a lot of automation and really need an easy way to add new values to autoload.

**Comment by 4n70w4** [comment]
Workaround:

```bash
cat <<< $(jq --indent 4 '.autoload."psr-4" += { "Modules\\": "Modules/" }' composer.json) > composer.json
```
