### ISSUE TITLE
composer require asks for authentication whereas composer update does not.

### ISSUE THREAD

**Issue by jacobkiers** [composer/composer#3400]
We have a private satis instance with HTTP Basic authentication. This authentication is globally added with:

``` bash
composer config --global repositories.example composer https://packages.example.org
composer config --global http-basic.packages.example.org username password
```

When performing `composer update`, no credentials are asked (as expected). When using `composer require`, credentials _are_ asked.

How can we solve this?

**Comment by frederikbosch** [comment]
Tried to replicate this behaviour with the changes in this pull request https://github.com/composer/composer/pull/3608. It seems solved now. After storing the authentication details in auth.json, ```composer install```, ```composer update``` and ```composer require``` do not ask again for credentials. This bug can be closed after merging the PR.

**Comment by frederikbosch** [comment]
Congrats on Composer 2 @Seldaek. You and @naderman deserve a whole lot of credits for it!
