### ISSUE TITLE
Exception when cloning from private mercurial repo & temp clone folder : windows path limitation ? 

### ISSUE THREAD

**Issue by jvanbouchaute** [composer/composer#3403]
Hi,

composer version : 

Composer version 1.0-dev (ffffab37a294f3383c812d0329623f0a4ba45387) 2014-11-05 06:04:18
Hg version : Mercurial Distributed SCM (version 3.1.2)
OS : Win7 x64

when adding a dependency from a local mercurial repository, composer clones it to a temp directory. However the temp-folder name is a concatenation of the http url of the repo. The total combination of this base path + the contents of the mercurial repo leads to the facts that mercurial hits a windows NTFS limit on folder name length / path depth.

Another temp folder naming strategy should be chosen to avoid such issues on Windows OS  : 

Log : 
  [RuntimeException]
  Failed to clone http://hgwebrdx.nce.mycompany.net/hg/mbo_mo1_mof_gui/integration/arch_frontend_head/, could not read packages from it
  transaction abort!
  rollback completed
  abort: C:\Users\xxxxxxxxxxx\AppData\Local\Composer\vcs\http---hgwebrdx-nce-mycompany-net-hg-mbo-mo1-mof-gui-integration-arch-frontend-head-.hg/store\data/src/_xxxxxxxxx/_common/_architecture_front_end_bundle/_dependency_injection/_architecture_front_end_exte
  nsion.php.i: The system cannot find the path specified

Exception trace:
 () at phar://D:/ws/etr-head/ecgui/composer.phar/src/Composer/Repository/Vcs/HgDriver.php:66
 Composer\Repository\Vcs\HgDriver->initialize() at phar://D:/ws/etr-head/ecgui/composer.phar/src/Composer/Repository/VcsRepository.php:78
 Composer\Repository\VcsRepository->getDriver() at phar://D:/ws/etr-head/ecgui/composer.phar/src/Composer/Repository/VcsRepository.php:113
 Composer\Repository\VcsRepository->initialize() at phar://D:/ws/etr-head/ecgui/composer.phar/src/Composer/Repository/ArrayRepository.php:170
 Composer\Repository\ArrayRepository->getPackages() at phar://D:/ws/etr-head/ecgui/composer.phar/src/Composer/DependencyResolver/Pool.php:170
 Composer\DependencyResolver\Pool->addRepository() at phar://D:/ws/etr-head/ecgui/composer.phar/src/Composer/Installer.php:361
 Composer\Installer->doInstall() at phar://D:/ws/etr-head/ecgui/composer.phar/src/Composer/Installer.php:218
 Composer\Installer->run() at phar://D:/ws/etr-head/ecgui/composer.phar/src/Composer/Command/UpdateCommand.php:130

Failing command : 

Executing command (C:/Users/xxxxxxxxxxx/AppData/Local/Composer/vcs): hg clone --noupdate "http://hgwebrdx.nce.mycompany.net/hg/mbo_mo1_mof_gui/integration/arch_frontend_head/" "C:/Users/xxxxxxxxxxx/AppData/Local/Composer/vcs/http---hgwebrdx-nce-mycompany-net-hg-
mbo-mo1-mof-gui-integration-arch-frontend-head-/"

**Comment by jvanbouchaute** [comment]
Any news on this topic ?

**Comment by Seldaek** [comment]
No idea if this is still relevant. I suppose it is and yeah we maybe should just hash the repo URL in some way if it's too long on windows. If anyone wants to work on this.

**Comment by weltling** [comment]
@jvanbouchaute that's obviously a long path issue. Could you please check this PR https://github.com/php/php-src/pull/1854 ? PHP Windows builds are linked in the description.

Thanks.

**Comment by Seldaek** [comment]
Closing as it's very old and PHP7.1 should hopefully fix long path problems.
