### ISSUE TITLE
[Feature] Allow SSH/HTTPS context options to be configured globally

### ISSUE THREAD

**Issue by fazy** [composer/composer#3404]
To make Composer connect to a private repo secured by SSH, I need to specify the location of certain security credentials. For SSH it's `username`, `pubkey_file` and `privkey_file`. For HTTPS, you probably need `local_cert`, `verify_peer`, maybe more.

(BTW I don't know why the public key is needed (OpenSSH command line can SSH to a remote box with just the private key locally, public key remote), but in testing that seems to be true in PHP's SSH implementation too, so not just a composer thing.)

Here's an example:

```
{
    "type": "composer",
    "url": "ssh2.sftp://satis.example.net:/satis/web",
    "options": {
        "ssh2": {
            "username": "composer",
            "pubkey_file": "/home/username/.ssh/id_satis.pub",
            "privkey_file": "/home/username/.ssh/id_satis"
        }
    }
}
```

The problem is I don't want to specify the path of the SSH keys in the committed (shared) composer.json, because each user will have a different location. 

Even if `~/.ssh/id_satis` worked (it doesn't), it's still a bit prescriptive on each user.

(Username could be an issue in some cases, but in my setup composer is a shared account with no shell access, so I just add each user's public key to authorized_keys.)

I could just use `ssh/id_satis`, but then I need to update the build scripts to make sure this always gets copied or linked in, and update .gitignore to stop an accidental commit. Even then, the build script needs to either gain another config option (location of files), or always assume names like `~/.ssh/id_satis`, effectively just working around the fact that `~` doesn't work. Not very elegant.

Perhaps as there's already a `~/.composer/auth.json` file for "http-basic" and "github-oauth", there can be a section in there? Something like this:

```
"ssh": {
    "example.org": {
        "username": "username",
        "pubkey_file": "/path/to/pub_key",
        "privkey_file": "/path/to/priv_key"
    }
}
```

**Comment by andrewhowdencom** [comment]
+1

**Comment by netroby** [comment]
Why not using your ssh config file , by default, ssh will find /etc/ssh/ssh_config and ~/.ssh/config files.

**Comment by nickma** [comment]
+1 Have the same issue/need.

**Comment by redshark1802** [comment]
+1
additionally: it would great if you could also specify the full URI of the archive instead of just the domain.

**Comment by OZZlE** [comment]
> Why not using your ssh config file , by default, ssh will find /etc/ssh/ssh_config and ~/.ssh/config files.
@netroby can you explain more?

I added but made no difference:

    Host *
        IdentityFile ~/.ssh/id_rsa
