### ISSUE TITLE
gitignore parser: regex failed

### ISSUE THREAD

**Issue by mplx** [composer/composer#3408]
Using satis I found a problem within the gitignore parser which seems to be related to composer than satis itself:

Quoting https://github.com/composer/satis/issues/181

> I came along a few internal packages where satis build failed with an error message:
> `Skipping Exception 'preg_match(): Unknown modifier '[''.`
> 
> I'm sorry I didn't have too much time to dig further into this issue, but in the end the error is caused  by the pattern `.#*` in `.gitignore` files. My best guess is that you use `#` for delimiting the regex so any `#`  characters inside have to be escaped.
> 
> Steps to reproduce:
> put a line `.#*` into .gitignore, commit/push, satis build

Probably the delimiter has just to be escaped in `GitExcludeFilter.php` like it's done in `HgExcludeFilter.php` (and to add it to the unit test).

**Comment by rfussien** [comment]
A PR that fix the problem exists : https://github.com/composer/composer/pull/3380

**Comment by Seldaek** [comment]
Closing as this is a very old issue and not extremely relevant anymore.
