### ISSUE TITLE
Read composer.json Files for "replaced" Modules

### ISSUE THREAD

**Issue by buskamuza** [composer/composer#3410]
Hi,

`composer.json` file has section `replace`. Then when `composer install/update` is run, Composer just assumes that these libraries are already included in the project.

But if these components also depend on something, Composer will not read it and will not install.

Example: https://github.com/symfony/symfony
You can see  in its root `composer.json` that it replaces `symfony/monolog-bridge`.
If you go to the directory with this [component](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bridge/Monolog), you'll find that it requires `monolog/monolog`.
Root `composer.json` doesn't require `monolog/monolog`, so if I'll clone the repository and run `composer install`, `monolog/monolog` will be missing, while it's required by the project.
```
$ composer install --dry-run --no-dev
Loading composer repositories with package information
Installing dependencies
  - Installing doctrine/lexer (dev-master 83893c5)
  - Installing doctrine/annotations (dev-master 3b6668f)
  - Installing doctrine/collections (dev-master 38ed66e)
  - Installing doctrine/cache (dev-master 912e8a1)
  - Installing doctrine/inflector (dev-master 8a0b96e)
  - Installing doctrine/common (dev-master 559a805)
  - Installing twig/twig (dev-master b87cf88)
  - Installing psr/log (dev-master a78d650)
```

So either either something will be broken for the user or the owner of the repository must go through all sub-components and include all their dependencies in the root `composer.json`. And as soon as any component's dependencies are updated, root `composer.json` must be updated as well.

Looks like both ways are quite unreliable.

Is there any way or any plans to implement an ability to specify where this "replacing" component is located? And make Composer read `composer.json` (if exists) there as well?

UPD: just realized that `symfony/symfony` is a lib, so it doesn't make sense to clone it. But it doesn't change anything. I tried to use it as a dependency in a project and it is not going to download `monolog/monolog` anyway.
Just in case, here is my simple `composer.json`:
```
{
    "name": "olga/something",
    "type": "project",
    "require": {
        "symfony/symfony": "2.5.6"
    }
}
```

I run 
```
composer install --no-dev --dry-run
Loading composer repositories with package information
Installing dependencies
  - Installing psr/log (1.0.0)
  - Installing twig/twig (v1.16.2)
  - Installing doctrine/lexer (v1.0)
  - Installing doctrine/annotations (v1.2.1)
  - Installing doctrine/collections (v1.2)
  - Installing doctrine/cache (v1.3.1)
  - Installing doctrine/inflector (v1.0)
  - Installing doctrine/common (v2.4.2)
  - Installing symfony/symfony (v2.5.6)
```

**Comment by alcohol** [comment]
Something that `replace`s another lib might have other requirements than the original. So your request does not really make sense. More often than not, `replace` is used to indicate a replacement for a deprecated library. Also in your scenario, `symfony/symfony` includes `psr/log` and leaves it up to the user to determine how they will fulfil any actual logging implementation (monolog is **not** a requirement on purpose).

**Comment by slbmeh** [comment]
The `replace` section very narrowly acts this way with subtree splits. In this manner it is a way to define the projects included. The `symfony/symfony` package is very large and as alcohol mentioned has intentionally left out dependencies because they aren't needed for every usage of it.  IMO it should have a `suggests` section describing the packages it intentionally left out and the functionality you would need it for.

Another scenario that utilizes `replace` would be forks and alternatives. They may initially have the same dependencies initially, and generally serve the same underlying purpose, but the actual dependencies for the selected package may differ slightly.

I could have a shim package that does all logging to `Psr\Log\NullLogger` and two different logging packages that log differently such as push to a message queue vs log to a file with monolog. My application depends on a library that depends on the shim. If I'm going to be deploying my application to a server that has the amqp extension installed I will require the amqp implementation which `replaces` the null shim.

**Comment by buskamuza** [comment]
@alcohol 
> Something that replaces another lib might have other requirements than the original.
Even if dependencies are different, how does it change my request? Let's say there is package "package1" (requires "package0") and in my project I implement alternative for it and it's located in folder `my/package1` (requires "my-package0"). If in scope of my project I consider it as a replacement of "package1", I may want to keep everything related to it inside its folder, including `composer.json`. So I'd declare in `my/package/composer.json` dependency on "my-package0".
Yes, this is a use case when only part of my package is a replacement for another package. Is it some non-recommended/unused use case?

@slbmeh , thanks for mentioning subtree, I need look at it once again.
About Symfony - ok, got it. But if a library will just use suggestions, it will require additional actions from the user to get anything working. Do I understand it correctly?

My use case is: as a contributor to Symfony project, I want to perform some modifications in multiple libraries, commit it to a single repository and make one pull request. Same for a core Symfony developer.

What are other cases for using a whole pack of libraries? I assume that if some specific libraries are required, then only these libraries will be declared as dependencies.

If this is a case with replacing a deprecated library, why do I need to install replacement and not make it working (install it w/o necessary dependencies)? I don't consider here replacement for logging, it's different question - in this case a separate library should not declare it as a hard dependency.

One more note: if a bundle of libraries does not want to enable all of them upon installation, let it be also possible. I don't propose to add any restrictions. I'd like just to have an ability to install dependencies required by my replacements automatically and to avoid duplication.

**Comment by slbmeh** [comment]
It doesn't necessarily require user interaction to enable features from a suggestion. The package could be configured to use an APC caching mechanism by default if the extension and class are available.

The use case you describe is what projects like symfony do. If you look at the description on the repositories for the symfony components they say they are read only subtree splits and the master is at symfony/symfony.

Frameworks and large projects with supporting pieces that are useful standalone are where you would see that style of replaces. A large project example off the top of my head was Guzzle3.

The other form of replacement packages would be forks, deprecated, and abandoned packages. Those three types more commonly provide the same functionality but potentially in a different way. 

Another usage of replace would be for transition packages. A scenario here could be you have a project that relies on a large monolithic framework such as an older version of cake or codeigniter. You could create a transition repository that has pieces of the legacy code you still depend on alongside the newer replacement libraries you have migrated to. In a general scenario installing two versions of a package would conflict and it is not supported. You could leverage the replace functionality to have the ability to provide what you need from each version in a way that you have ensured won't conflict.

Another concept, that I have yet to see in the community is the concept of backports of packages. I don't think it's a good idea, and definitely goes against semantic versioning. I have a package that requires features from throughout the doctrine 2.5 development cycle prior to bumping the php version requirement. I've tagged a forked release on an internal repo and I'm pulling in bug fixes from upstream.

With those different potential usages of replace, I don't see how composer can make the determination of what dependencies it should install and what ones it shouldn't. Partial replacements are not supported. I don't really see a practical use case for installing dependencies of a package that you do not have installed.

**Comment by Seldaek** [comment]
This is not really something we can fix, I get that it sucks in the case of symfony as the replace is a bit over-reaching and it doesn't really replace everything since it's missing some requires, but that's just a problem in symfony and not composer.
