### ISSUE TITLE
`composer status` for non-CVS packages

### ISSUE THREAD

**Issue by TriAnMan** [composer/composer#3433]
For my mind it is great if `composer status` can warn user about packages that are not under any CVS (e.g. installed with --prefer-dist) and has changed files, so user can reinstall such packages or something...
This can be done with md5 or sha1 of files or directories...
Maybe it should be done with another command, e.g. `composer status-complete` or `composer status --non-cvs`

**Comment by ewgRa** [comment]
+1 This is very important also from security reason, to check if there is any changes in files.
It can be done by check cache versions for example.

**Comment by Seldaek** [comment]
Yeah that's not really gonna happen it would be insane for us to keep track of the whole state of all files and then check them all.. If you want that for all dependencies just use --prefer-source and then you have git clones for everything.
