### ISSUE TITLE
Deletion issues with Deps of Deps removed

### ISSUE THREAD

**Issue by auroraeosrose** [composer/composer#3434]
1. Have a project with chained dependencies (a dep1 that has a dep2)
2. Have the dep1 package delete dep2
3. update composer.json for new dep1 if necessary and composer update dep1 on the project

The dep2 will NOT be deleted from the .lock file in the project

4. delete composer.lock from the project
5. composer install on project

The dep2 will still be added to the .lock file

either
6. composer delete dep2
or
6. rm vendor/
or
6. possibly composer clearcache (didn't try this one)

7. composer install on project

NOW dep2 is finally not added to the .lock file

Merge new .lock and composer.json to a different branch in the project
deploy of branch to different machine does composer install using new .lock and composer.json

Old dep2 remains in vendor directory on machine

You have to delete the vendor and do the composer install again or delete the package manually or try cache clearing to get that old dep2 to go away

Things that are not required anymore should be removed on install if they do not exist in the composer.lock file

**Comment by Seldaek** [comment]
Tried this again just to make sure and it works for me, plus works in our tests, so without further info I'm closing this..
