### ISSUE TITLE
composer update can revert silently previous update

### ISSUE THREAD

**Issue by ghost** [composer/composer#3439]
For example in this scenario

developer1:
```sh
composer update namspace-a/packacge-a
git commit -am "update package-a"
git push
```

developer2:
```sh
git pull
composer update namspace-a/packacge-b
git commit -am "update package-b"
git push
```

Since the developer2 didn't run `composer install` before `composer update` the update of the developer1 is reverted. 

To prevent to revert by mistake an update from another developer, composer should at least raise a warning in this case. Simply verifying if the current installed package versions correspond to the one in composer.lock before an update and bring a warning if it isn't should suffice.

**Comment by Seldaek** [comment]
I did an alternative PR now at #3986 which actually fixes the problem I believe, I only checked with the automated tests so if you wanna give it a go with real conditions that'd be great.
