### ISSUE TITLE
Add support for git shallow clones

### ISSUE THREAD

**Issue by sbuzonas** [composer/composer#3449]
When working with a large repository it would be nice to opt for a clone depth of 1 to still leverage git to patch dependencies for a project

**Comment by slbmeh** [comment]
A similar state to a shallow clone can be to git init, set remote, fetch desired sha.

**Comment by GromNaN** [comment]
Interesting idea @slbmeh. Do you know the command to run to fetch only the desired commit ?

**Comment by slbmeh** [comment]
@GromNaN you can fetch any treeish object so just fetch the hash directly

**Comment by slbmeh** [comment]
actually, it doesn't appear to work like that anymore... i'll do further investigation, i was sure it worked for me like that git 1.6 era or so... there's a way to do it with the plumbing rather than the porcelain commands

**Comment by Seldaek** [comment]
Please check https://github.com/composer/composer/pull/4961

**Comment by shqear93** [comment]
any updates on this?

**Comment by Seldaek** [comment]
I think this isn't as needed anymore now that we clone from the cache dir, so we do local clones which are pretty fast.

**Comment by hetii** [comment]
This issue should be reopened. For CI/CD purpose or docker/kubernetes world where we start always from clean scratch there is no shared cache and for more complex project it's a waste of time to get all full repositories instead what is needed.

**Comment by ondrejmirtes** [comment]
@hetii Wouldn’t your problem be solved with --prefer-dist?

**Comment by hawkeyetwolf** [comment]
@ondrejmirtes yes indeed, but in my case the private packagist wasn't making the `dist` output available. I'm still working on that, but here's some thoughts for others:

If your private packagist isn't building `dist` output, see docs [here](https://getcomposer.org/doc/articles/handling-private-packages.md#downloads).

If your private packagist is mirroring a private GitHub (or BitBucket?) instance, you may just need to edit your private packagist's `satis.json` and change the repository type from `vcs` to `github` (or `git-bitbucket`) to force Composer into making `dist` available from those services.
