### ISSUE TITLE
Classloader on-demand namespaces don't work

### ISSUE THREAD

**Issue by chx** [composer/composer#3463]
```
if (!class_exists('Myvendor\foo\bar')) {
  $classLoader->addPsr4('Myvendor\foo\\', 'path/to/foo');
}
new Myvendor\foo\bar;
```

Good luck, the first `class_exists` triggers the following code in `findFile` which caches that the class doesn't exist:
```
            // Remember that this class does not exist.
            return $this->classMap[$class] = false;
```

**Comment by Seldaek** [comment]
Closing this as I don't really think it's a use case we need to support. It's always an option to register your own class loader on top of the existing composer one.

**Comment by chx** [comment]
So we should write our own classloader because addPsr doesn't reset a cache...???

**Comment by Seldaek** [comment]
Well resetting the cache cleanly means looping over the entire classmap to find entries to remove. Typically you configure the autoloader then run the app, it's such an uncommon case to reconfigure it at runtime that I am not sure if it makes much senes to add the overhead to it.
