### ISSUE TITLE
Revert composer.json to original content after RuntimeException

### ISSUE THREAD

**Issue by InFog** [composer/composer#3464]
Using **composer require** to install packages usually reverts composer.json to it's original content when something goes wrong, like **no matching package found**.

But when a RuntimeException is thrown, due to access denied to a repository, for example, composer.json keeps the changes.

I think it would be better to revert composer.json, since the changes were not done.

**Comment by slbmeh** [comment]
In theory it [does](https://github.com/composer/composer/blob/master/src/Composer/Command/RequireCommand.php#L161). Perhaps that `$installer->run()` should be in a try/catch because it appears that the installer catches and throws exceptions it would receive.

**Comment by InFog** [comment]
Unfortunately that's what happens :(
