### ISSUE TITLE
Error when using composer

### ISSUE THREAD

**Issue by brasileric** [composer/composer#3470]
Hi,
It looks so simple, so installed Composer without problems, but now when I want to install Omnipay by Composer I get this error:

$ php composer.phar install
Loading composer repositories with package information
file_put_contents(/home/hericadmin/.composer/cache/repo/https---packagist.org/packages.json): failed to open stream: Permission denied
https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
Installing dependencies (including require-dev)

  [Composer\Repository\RepositorySecurityException]
  The contents of http://packagist.org/p/omnipay/2checkout$9483edd00d6d9c3fc7ca6c3e4cb1a6b290c4f4d37ef4f01fdb41e33a24404d29.json do not match its signature. This should indicate a man-in-the-mid
  dle attack. Try running composer again and report this if you think it is a mistake.

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [packages1] ... [packagesN]

**Comment by mohsenuss91** [comment]
@brasileric  how to do that please!

**Comment by chocopowwwa** [comment]
@brasileric  THANK YOU!!

@mohsenuss91 
see this for the cache dir:
https://getcomposer.org/doc/06-config.md#cache-dir

in my case simply chown the cache dir

**Comment by AleksandarSavic95** [comment]
@mohsenuss91 I used this command for the `cache` folder:
    `sudo chmod -R a+rw /home/USERNAME_HERE/.composer/cache`

**Comment by mateuszgwozdz** [comment]
@AleksandarSavic95 for current user:
`sudo chmod -R a+rw  ~/.composer/cache`
