### ISSUE TITLE
Bug finding packages

### ISSUE THREAD

**Issue by aequasi** [composer/composer#3473]
Hey @Seldaek, think i found a bug for you.

![HUGE ASS BUG](http://content.screencast.com/users/aequasi/folders/Jing/media/5c0377a9-535a-4766-a6cb-2c2331879e3e/00000198.png)

When doing a `composer require`, and it asks "Enter package # to add, or the complete package name if it is not listed []"

It doesn't actually seem to allow you to put in a valid package name.

**Comment by Seldaek** [comment]
Seems not actual anymore

![image](https://cloud.githubusercontent.com/assets/183678/13374140/e1f85452-dd73-11e5-91f7-3b9c699f60b9.png)

**Comment by aequasi** [comment]
Thanks!

Aaron Scherer




On Sat, Feb 27, 2016 at 9:02 AM -0800, "Jordi Boggiano" <notifications@github.com> wrote:












Seems not actual anymore

**Comment by curry684** [comment]
Should it really also be searching the PlatformRepository though? Seems weird here.

**Comment by Seldaek** [comment]
Sounds fine to me.. Why not and let's be honest with any kind of real
search term you're unlikely to get any hits.

**Comment by cs278** [comment]
Indeed no reason why not, it's perfectly valid to add a requirement on a platform package.

**Comment by curry684** [comment]
Yeah it's valid but I don't think really the obvious use case of going interactive there. Doesn't really matter, better question: why does `php` match `k`?

**Comment by cs278** [comment]
> why does php match k?

Now that is a good question, I thought maybe the description but:

```
$ composer show php | grep -i k
keywords : 
```

**Comment by Seldaek** [comment]
Because the description of the package is `Package overridden via config.platform (actual: 7.0.3)` here as I have an config.platform override :)
