### ISSUE TITLE
Replacing package from private repository with package from packagist

### ISSUE THREAD

**Issue by sectus** [composer/composer#3509]
I think that it's common way that users use private and public repositories (packagist.org) at the same time. But villain could discover vendor and package name of your private package(I do not think that this information has to be private) and create new evil one on packagist with the same vendor and package name, but with higher version.  It will substitute private package without any notice (changing of version only) . I think that is security issue.

My proposals(easy):
Add note to the documentation: using private and public repositories at the same time could be dangerous.
Add source of installed to an output of composer install or update.
Attract attention when source of package changed.

(hard):
Change logic of composer. Add possibility to choose repository of package.

**Comment by fouzes** [comment]
There is an idea to have named repositoreis and use these names in package names (like Portage in Gentoo). For example, packagist.org by default will be named as packagist. Other repositories will be named at "repositories" block:
```
    "repositories": [
        {
            "name": "example",
            "type": "composer",
            "url": "http://packages.example.com"
        }
```
Then I can require the package from "example" repo:
```
    "require": {
        "my/package-one": "~1.0",
        "my/package-two::example": "~1.0",
        "my/package-three::packagist": "~1.0"
    }
```
In this case my/package-one will be installed using current logic, my/package-two will be installed from "example" repo and my/package-three will be installed from packagist.org.

**Comment by zxqfox** [comment]
@fouzes Naming of used repositories is pretty simple yet powerful idea. But better to make possible to provide some data into packages itself:
```
"require": {
  "my/package-one": { "version": "~1.0", "repositories": "example" }
}
```
And by default we should use `any` repository (as it works for now).

**Comment by Seldaek** [comment]
I have a tentative fix for this in #3982 - much easier than this named repo stuff as it works for everyone by default. We'll see if anyone has feedback but otherwise I think it'd be a good fix.

**Comment by theodorejb** [comment]
Thank you so much for fixing this!

**Comment by sectus** [comment]
@Seldaek , sounds great. Thanks. It's important for me.
