### ISSUE TITLE
composer could not find the config file

### ISSUE THREAD

**Issue by mjoyshuvo** [composer/composer#3514]
Every time I want to install laravel I get this 

composer could not find the config file C:\Program data \Composer Setup\bin
To initialize, project please create a composer.json file as desctibed in the https://getcomposer.org/ getting started section.
Any advice ?

**Comment by cometofsky** [comment]
thanks sharif! it worked for me.... but why do i need this "COMPOSER=composer.json" part, how can i write command for composer without that part?

**Comment by yanwushu** [comment]
@I-Am-AhmadSharif  hi , i have executed the command , but the system give me this response:
```
[InvalidArgumentException]
command "=composer.json" is not defined.
```
how should i do?

**Comment by stof** [comment]
The way to set environment variables when launching a command is different on Windows. So if you are using Windows, you should use the windows way.
