### ISSUE TITLE
change php version?

### ISSUE THREAD

**Issue by craigh** [composer/composer#3537]
I'm sorry to both you with a support question in the tickets here. I don't know where else to ask. I'm not really that good at understanding CLI stuff - I'm a php guy.

So a long time ago, I installed and have been happily using composer on my mac. At the time I installed it, I followed some additional instructions I found online in order to get it so that when I want to use it, I just type

`$ composer update`

but I am now running several instances of PHP on my machine: I use MAMP PRO to change versions when I need. I assume that composer is using php from some source on my machine - and likely the one that ships with the OS - not the one I am actually using in MAMP.

I've looked for an alias setting or something somewhere that tells me how I am using composer without typing

`$ php composer.phar update`

but I can't find anything - I have no `.bash_profile` file. I have no alias setting in my `.tcshrc` file.

so, how does composer know which php instance to use and how do I change it? (or is it not using php?)

**Comment by davidlyons24** [comment]
That's really usefull for Plesk servers, just add the following line into the .bashrc file from your user folder:
export PATH=/opt/plesk/php/5.6/bin:$PATH

It's works fins with composer

**Comment by Ash-Radwan** [comment]
Thanks @alcohol that works fine, I needed to run composer while specifying which php version will be used like the following:
 php-7.0 /usr/local/bin/composer update

**Comment by Glideh** [comment]
Also don't forget to update this part in `composer.json`

```yml
"config": {
    "platform": {
        "php": "5.6.31"
    }
},
```

I wasted hours searching where composer was getting this version

**Comment by alansary** [comment]
Composer uses the default php version in your terminal, you can easily manage that using phpbrew and switch between the different versions of php in your terminal.
Alternatively, you can edit ~/.bashrc and add aliases to the php version you want to use and to composer as well
For me, I added the following lines in ~/.bashrc
alias php7.0='/usr/bin/php7.0'
alias composer='/usr/local/bin/composer'
then,
php7.0 composer install
is used as an alternative to /usr/bin/php7.0 /usr/local/bin/composer install

**Comment by shamank** [comment]
1. Download composer.phar into your project root:
`$ wget https://getcomposer.org/composer.phar`
2. Create the alias in your `~/.bash_aliases`:
`alias lcomposer='/usr/bin/php7.1 composer.phar'`
3. You're done. Just use `lcomposer` for whatever you need in your project:
`$ lcomposer`

**Comment by shamank** [comment]
1. Create the alias in your `~/.bash_aliases`:
`alias lcomposer='/usr/bin/php7.1 /usr/local/bin/composer'`
2. You're done. Just use `lcomposer` for whatever you need:
`$ lcomposer`

**Comment by juanpablo321** [comment]
Thank you guys. After a while I got it:

/opt/plesk/php/7.0/bin/php /usr/lib64/plesk-9.0/composer.phar update

**Comment by zaibigits099** [comment]
I Updated php path in my Environment variable than ran composer and reset it to default. I've to do this every time i update composer package to run with the latest php path.
