### ISSUE TITLE
Composer Update Fails due to Github Authorization

### ISSUE THREAD

**Issue by fiatux** [composer/composer#3542]
During composer update I am asked for my github credentials repeatedly. What may be causing this?

> An existing OAuth token for Composer is present and will be reused
> 
> Could not fetch https://api.github.com/authorizations, enter your GitHub credentials to go over the API >rate limit
> The credentials will be swapped for an OAuth token stored in /Users/[USER]/.composer/auth.json, your >password will not be stored
> To revoke access to this token you can visit https://github.com/settings/applications

Yes, I am entering my password correct, I have tried several different accounts and I can get authorization from Github if I use curl from cmdline.

**Comment by yoanisgil** [comment]
@hugofonseca Thanks!

**Comment by Commifreak** [comment]
The global Token config does not work (as mentiod in Post 3):

```
C:\Users\robin.kluth>composer diag
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity: OK
Checking HTTP proxy: OK
Checking HTTP proxy support for request_fulluri: OK
Checking HTTPS proxy support for request_fulluri:
Could not fetch https://api.github.com/repos/Seldaek/jsonlint/zipball/1.0.0, ent
er your GitHub credentials to go over the API rate limit
The credentials will be swapped for an OAuth token stored in C:/Users/robin.klut
h/AppData/Roaming/Composer/auth.json, your password will not be stored
To revoke access to this token you can visit https://github.com/settings/applica
tions
Username:
```

while in %appdata%\Composer\auth.json:

```
{
    "http-basic": {},
    "github-oauth": {
        "github.com": "my_token"}
}

```

If I add the token to projects composer.json, it is working as expected.

**Comment by webdevilopers** [comment]
So the solution is to put the token into the `composer.json` directely instead of relying on the `auth.json`?

Will this be solved as suggested in the latest issue https://github.com/composer/composer/issues/3566 @Seldaek ?

Because as Malcolm Fell @emarref mentions:
`If you're working on a collaborative project, you should not commit your key in the project source control. The alternative is to set your key in your home directory...`
https://coderwall.com/p/kz4egw/composer-install-github-rate-limiting-work-around

**Comment by Commifreak** [comment]
Hi,

I figured out, that the auto-generated token (via composer) ist not accepted. If I create the key via GitHub's WebUI and replace the old one in composer.json, it is working.

**Comment by webdevilopers** [comment]
Have you tried that within the `auth.json` or `config.json` too?

**Comment by midan888** [comment]
I pasted in ocmposer json of the project and it worked, thanks to hugofonseca 
`{  
  "config": {
    "github-oauth": {
      "github.com": "<TOKEN>"
      }
    }
} `

**Comment by webdevilopers** [comment]
Ok, so the important point is that the token has to be added to the `composer.json' file.

The attempt with `auth.son` of Composer is no longer supported by the curernt GitHub API:
https://github.com/composer/composer/issues/3566

**Comment by webdevilopers** [comment]
It looks like @Seldaek added a fix for the original issue by @fiatux :
https://github.com/composer/composer/pull/3651

**Comment by fakixlix** [comment]
Gracias fonsecas72, funciona :D 

composer clear-cache 

composer global require "fxp/composer-asset-plugin:1.0.0-beta4" 

composer config --global github-oauth.github.com <TOKEN>

 composer create-project --prefer-dist yiisoft/yii2-app-advanced yii-application

Así me funcionó para Yii2 Advanced Template.

**Comment by Peter74** [comment]
Hi I was face same problem.
Solution for me was:
```
composer config --global github-oauth.github.com <TOKEN>
```
thanks @fonsecas72 
...and as a result of it was writing token at auth.json  : 
```
{  
  "config": {
    "github-oauth": {
      "github.com": "<TOKEN>"
      }
    }
}
```
...but not in composer.json - that was just mistake in explanation, but if you run 
```
composer config --global github-oauth.github.com <TOKEN>
```
- you will be OK.

**Comment by marcozs84** [comment]
Posted by codekman at 

http://www.yiiframework.com/forum/index.php/topic/60340-issue-while-installing-yii-2/

Please see the line above the cmd, here you will find the url and visit this url and you will git the token and paste the token. 
- it worked for me at least

**Comment by o5** [comment]
Is possible to remove auth token via `composer config -g` command? I mean something like `composer config -g --unset repositories.betsys` but for `auth.json`. 

Sure, I can remove by fe [jg](https://stedolan.github.io/jq) but build-in support in composer should be cool.

**Comment by Seldaek** [comment]
This will do it for example: `composer config --global --auth --unset github-oauth.github.com`

**Comment by breakline87** [comment]
Can you guys make something which works without extensive modifications even for a beginner?

**Comment by saxsax1995** [comment]
solved by use this cmd: composer config --global --auth github-oauth.github.com <create your token here>
for example : composer config --global --auth github-oauth.github.com 123456

**Comment by ew5yte5ye** [comment]
If you are facing Github token error then open composer.json file and paste below code 

"github-oauth": {
          "github.com": "b25bea6b9e67903735d1fcc40d9dd9c68d0a98e0"
          }

**into**

"config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true,
        "github-oauth": {
          "github.com": "b25bea6b9e67903735d1fcc40d9dd9c68d0a98e0"
          }
    }


And then update composer
> composer update

**Comment by mijaelsaban** [comment]
The issue is that my token it has an underscore which is never valid according to this logic.

Which here it fails.

```
 
foreach ($githubOauth as $domain => $token) {
            if (!preg_match('{^[.a-z0-9]+$}', $token)) {
                throw new \UnexpectedValueException('Your github oauth token for '.$domain.' contains invalid characters: "'.$token.'"');
            }
            $this->checkAndSetAuthentication($domain, $token, 'x-oauth-basic');
        }

```

**Comment by Seldaek** [comment]
@mijaelsaban make sure you  update Composer to the latest version before reporting error, this was fixed last week.

**Comment by Boby** [comment]
I am running on composer 2 and having this issue, anyway we can remove it make it just ask for auth again? as I am running in docker and cant get it cleaned up

**Comment by b-hayes** [comment]
yeah, I ran into this on composer 2 as well . Have to manually update the token to the auth.json

**Comment by Loukili-Rachid** [comment]
the solution is here : [](https://stackoverflow.com/questions/31766546/composer-error-with-github-oauth-token-on-fresh-laravel-homestead-provision/72911657#72911657)

**Comment by MrAnassBaba** [comment]
Otherwise run this command `composer diagnose` to checking composer status 
check recommendation alert at finally updated `composer using composer self-update`

**Comment by dishansa** [comment]
@fonsecas72 thanks a lot.

**Comment by OCHIENGHerman** [comment]
> You can solve it by creating a new github token to authenticate your composer requests. You can do this two ways:
> 
> By defining your token globally:
> 
> ```
> composer config --global github-oauth.github.com <TOKEN>
> ```
> 
> Or by defining your token in a project composer.json:
> 
> ```json
> {  
>   "config": {
>     "github-oauth": {
>       "github.com": "<TOKEN>"
>       }
>     }
> }
> ```
> 
> More information about the problem and how to generate github tokens: [Composer troubleshooting](https://github.com/composer/composer/blob/master/doc/articles/troubleshooting.md#api-rate-limit-and-oauth-tokens)

**Comment by OCHIENGHerman** [comment]
Thanks it worked.
