### ISSUE TITLE
Problems with packages using composer/installers

### ISSUE THREAD

**Issue by dirkbloessl** [composer/composer#3557]
When using the latest version from master, there is a problem using packages, that will be installed to different locations using composer/installers

That problem is related to @Seldaek 's changes in cc4223e6f9f66cd7c8ba78dc7a8442d1029ab2d2

The packages will be purged even though, they exist on the filesystem already, but in a different path, than in vendor/.

Those folders will be removed from the filesystem as well, even if there are any changes in the folder.

On composer install it fails with the following error:
`fatal: destination path 'modules/foobar' already exists and is not an empty directory.`

**Comment by zxqfox** [comment]
Just caught this on version `Composer version 1.0-dev (eea42c4df7b08f914f26dcb1bc5763222ba683a9) 2015-05-25 10:30:12` while accessing private gitlab repo via ssh.

Looks like Composer executes `git clone ...` twice...
