### ISSUE TITLE
Destination path already exists after failed installation

### ISSUE THREAD

**Issue by tim-heinsohn** [composer/composer#356]
After failed installation attempts due to bad configuration (.zip format on an example URL in my case), Composer should try to clean up any files that might have been stored within the vendors pathes. As it didn't, after fixing the configuration git was not able to clone the repository and Composer crashs with a RuntimeException:

```
Failed to execute git clone '...' '...' && cd '...' && git checkout '...' && git reset --hard '...'  
```

where it would be nice of Composer to evaluate the actual step of failure and report an error explaining possible reasons, or better assure a clean VCS state before installing/updating, and clear up failed installations.

**Comment by duke7able** [comment]
i am getting this bug in composer 2.x
```
In Git.php line 471:
                                                                                                                
  Failed to execute git clone --no-checkout '/root/.cache/composer/vcs/https---github.com-Simpleminds-Technol   
  ogies-LLP-laravel-shopify.git/' '/mnt/f/shipturtle/shipturtle-api/vendor/osiset/laravel-shopify' --dissocia   
  te --reference '/root/.cache/composer/vcs/https---github.com-Simpleminds-Technologies-LLP-laravel-shopify.g   
  it/' && cd '/mnt/f/shipturtle/shipturtle-api/vendor/osiset/laravel-shopify' && git remote set-url origin --   
   'https://github.com/Simpleminds-Technologies-LLP/laravel-shopify.git' && git remote add composer -- 'https   
  ://github.com/Simpleminds-Technologies-LLP/laravel-shopify.git'                                               
                                                                                                                
  
  fatal: destination path '/mnt/f/shipturtle/shipturtle-api/vendor/osiset/laravel-shopify' already exists and   
   is not an empty directory.
```

**Comment by EPGDigital-MW** [comment]
I'm was getting this issue too with a git installed package, I'm using docker:

```                                                                                                                                                                                                                     
  fatal: destination path '/application/vendor/foo/bar' already exists and is not an empty directory.    
```

my /application folder is a docker volume, the actual error git was throwing when I ran the git commands manually was:

```
fatal: detected dubious ownership in repository at '/application/vendor/foo/bar'
To add an exception for this directory, call:

        git config --global --add safe.directory /application/vendor/foo/bar
```

I updated my docker build to run this once I'd installed everything else for the container

`
RUN git config --global --add safe.directory /application/vendor/foo/bar`

This fixed composer install for me.

**Comment by aaronlp** [comment]
> RUN git config --global --add safe.directory /application/vendor/foo/bar

Same issue here inside docker, fixed the same way. Thanks @EPGDigital-MW
