### ISSUE TITLE
Update to the new GitHub Authorizations API (breaking change)

### ISSUE THREAD

**Issue by ptoomey3** [composer/composer#3566]
The [GitHub Authorizations API](https://developer.github.com/v3/oauth_authorizations/) will no longer return `token` as of sometime next year (likely around March). You can read more on the [developer blog](https://developer.github.com/changes/2014-12-08-removing-authorizations-token/). The [login logic](https://github.com/composer/composer/blob/60ac971419ba4e8130b401757894b6b5636cf4e6/src/Composer/Util/GitHub.php#L77) will need to be updated to use something more like https://developer.github.com/v3/oauth_authorizations/#get-or-create-an-authorization-for-a-specific-app-and-fingerprint.

**Comment by webdevilopers** [comment]
:+1:

**Comment by webdevilopers** [comment]
There is some discussion going on related to this issuue I think, but the issue was already closed:
https://github.com/composer/composer/issues/3542
