### ISSUE TITLE
Show downloading package speed

### ISSUE THREAD

**Issue by ihor-sviziev** [composer/composer#3568]
For now when I add some package and it size is really big (i'm installing Magneto 1.x via composer) - we have only basic information:

```
  - Installing magento/core (1.9.1.0)
Downloading https://api.github.com/repos/bragento/magento-core/zipball/e98ff4ed632c70be2c42168338af3e8a68a5f989
    Downloading: 15%
```

Would be great add there download speed and estimated time (like in wget).

**Comment by stratdes** [comment]
Working on this.

**Comment by stratdes** [comment]
#5360

**Comment by Seldaek** [comment]
Closing as I don't think we want to do this.
