### ISSUE TITLE
No interaction flag not always respected on installation

### ISSUE THREAD

**Issue by hamiltont** [composer/composer#3572]
In a brand new VM, I'm trying to run `php composer.phar install --no-interaction --dry-run` for the JSON below. 

I am interrupted by this message, which causes an infinite hang unless I answer the question. Personally, I would expect that with `--no-interaction` composer would auto-accept the fingerprint

```
The authenticity of host 'github.com (192.30.252.129)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)?
```

and then by this message, which I would think could be addressed by operating at a much lower rate of API interaction (perhaps with a warning message that this will take a while and including github credentials would speed things along) instead of halting the installation process

```
Failed to clone the git@github.com:jquery/jquery.git repository, try running in interactive mode so that you can enter your GitHub credentials
```

here's the JSON for reference: 

```
rameworks/PHP/php-yii2$ cat composer.json
{
    "minimum-stability": "dev",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "*",
        "bower-asset/jquery": "@stable"
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}
```

If anyone has suggestions on what I can do to use composer inside a public bash script that needs to be non-interactive without exposing my personal github credentials that would be great!

**Comment by tbal** [comment]
@alcohol suggestion works fine.

You could also run this instead:
`ssh-keyscan -H github.com >> ~/.ssh/known_hosts`

**Comment by drdouglasghd** [comment]
The ssh-keyscan is a good option... 

I had to remove `-H` and use the `-t` for it to work correctly. 

`ssh-keyscan -t rsa,dsa github.com >> ~/.ssh/known_hosts`
