### ISSUE TITLE
Add support for loading autoload.files when executing scripts

### ISSUE THREAD

**Issue by tomzx** [composer/composer#3578]
Hi,

At the moment, it seems that the `EventDispatcher::getScriptListeners` is only permitting psr-0/4 classes from being loaded when excuting scripts. This is great, but this causes problems if any of your scripts are using libraries which use the `autoload.files` (specified in `composer.json`) feature as those files will not be loaded.

From the little I know about composer, my guess would have been that once you attach the composer autoloader, you could attach the autoloader of the project you're in. But taking a look at the `EventDispatcher` code, it seems that if a `loader` was already assigned, this one would be unregistered and a new one would be created. I have no idea in what context that happens, but it tells me that we want the old loader gone and we want to generate a new one each time `getScriptListeners` is called.

Is it possible to have composer load the `autoload.files` when executing scripts? If not, what are the possible alternative to get a script that relies on these files to work (would that require manually `require`-ing the files)?

**Comment by Seldaek** [comment]
Closing as per discussion on #5714 - not worth the mess it introduces, and not really nicely fixable anyway. Avoid requiring files autoload in event/script handlers and all is well.
