### ISSUE TITLE
more documentation for repository providers: gitattributes and prefer-lowest

### ISSUE THREAD

**Issue by dbu** [composer/composer#3582]
it would be nice to have articles for best practices when providing a repository. notable, the new prefer-lowest feature to test with the oldest permitted dependencies should be documented, and the [.gitattributes](http://stackoverflow.com/questions/17049313/how-to-ignore-directories-with-composer) to not install tests or documentation in production.

**Comment by JanTvrdik** [comment]
> we should use it in many places to avoid installing documentation or tests on production systems

Currently you can try to use https://github.com/dg/composer-cleaner.
