### ISSUE TITLE
composer update to the version a422d67e2701860a44a4634f62f88b58b8636468

### ISSUE THREAD

**Issue by ruikc** [composer/composer#3586]
when i finish update to the version a422d67e2701860a44a4634f62f88b58b8636468,command the composer update show the error as follow
PHP Fatal error:  Uncaught exception 'PharException' with message 'phar "/usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar" has a broken signature' in /usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar:23
Stack trace:
#0 /usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar(23): Phar::mapPhar('composer.phar')
#1 {main}

  thrown in /usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar on line 23

Fatal error: Uncaught exception 'PharException' with message 'phar "/usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar" has a broken signature' in /usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar:23
Stack trace:
#0 /usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar(23): Phar::mapPhar('composer.phar')
#1 {main}

  thrown in /usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar on line 23

how can i do ??

**Comment by eferuzi** [comment]
I am running ubuntu 14.10 and I am getting the same error. I have installed the latest version but still I am getting the same error.

**Comment by alcohol** [comment]
Can you describe your install process?

**Comment by tienvx** [comment]
Reinstall does not help
* composer self-update
```
Updating to version 2e73811211b7ea6de8de578fa50746fe679f2297.
    Downloading: 100%         
Use composer self-update --rollback to return to version a32c91914558a3ff293d83f7b99c49f4a7931798
PHP Fatal error:  Uncaught exception 'PharException' with message 'phar "/home/dev/bin/composer" has a broken signature' in /home/dev/bin/composer:23
Stack trace:
#0 /home/dev/bin/composer(23): Phar::mapPhar('composer.phar')
#1 {main}
  thrown in /home/dev/bin/composer on line 23
PHP Fatal error:  Uncaught exception 'PharException' with message 'phar "/home/dev/bin/composer" has a broken signature' in /home/dev/bin/composer:23
Stack trace:
#0 /home/dev/bin/composer(23): Phar::mapPhar('composer.phar')
#1 {main}
  thrown in /home/dev/bin/composer on line 23
```
* cd /home/dev/bin/
* rm composer
* curl -sS https://getcomposer.org/installer | php
* mv composer.phar composer
* chmod a+x composer
* composer self-update
```
PHP Fatal error:  Uncaught exception 'PharException' with message 'phar "/home/dev/bin/composer" has a broken signature' in /home/dev/bin/composer:23
Stack trace:
#0 /home/dev/bin/composer(23): Phar::mapPhar('composer.phar')
#1 {main}
  thrown in /home/dev/bin/composer on line 23
```
