### ISSUE TITLE
Exception when parsing version string like ^2.5.0

### ISSUE THREAD

**Issue by dmitryvakulenko** [composer/composer#3591]
[RuntimeException]  
  Could not load package egeloen/ckeditor-bundle in http://packagist.org: [UnexpectedValueException] Could not parse version constraint ^2.0.5: Invalid version string  
  "^2.0.5"

**Comment by ramcorreio** [comment]
I'm using the latest version and throws this exception. How can I do?

**Comment by xabbuh** [comment]
@ramcorreio What's the output of `composer --version`? How does your `composer.json` file look like and what is the exact error message you receive?

**Comment by ramcorreio** [comment]
root@packs:~# php /var/www/www/remote/bin/satis build /var/www/www/remote.json /var/www/www/remote/web
Scanning packages



  [RuntimeException]
  Could not load package egeloen/ckeditor-bundle in https://packagist.org: [UnexpectedValueException] Could not parse version constraint ^2.0.5: Invalid ver
  sion string "^2.0.5"






  [UnexpectedValueException]
  Could not parse version constraint ^2.0.5: Invalid version string "^2.0.5"



build [--no-html-output] [--skip-errors] [file] [output-dir] [packages1] ... [packagesN]


root@packs:~# composer --version
Composer version 1.0-dev (0662036f5ebc0bd33b4300fa68c3263c5e4ef584) 2015-01-11 23:38:42

**Comment by stof** [comment]
Well, you are getting the error when running Satis, not when running Composer. This is an important information to give. Satis is not using the latest Composer currently. @Seldaek you should probably update the deps in Satis

**Comment by Seldaek** [comment]
done

**Comment by ramcorreio** [comment]
wow!!! 
Now, thats ok.
Thanks a lot
