### ISSUE TITLE
Optimized autoloader is slow (compared to MediaWiki's autoloader)

### ISSUE THREAD

**Issue by legoktm** [composer/composer#3603]
Hi,

We've recently started using composer on Wikimedia sites, and have noticed that the optimized composer autoloader is significantly slower than [MediaWiki's autoloader](https://github.com/wikimedia/mediawiki/blob/master/includes/AutoLoader.php#L38).

@tstarling observed that composer takes about 63µs per class, and MediaWiki takes about 7µs per class. This was causing an overhead of about 13% of CPU time on short requests like API calls.

For now we've set prepend-autoloader: false, since most of our classes are in MediaWiki's autoloader, and are more likely to be found. However this will continue to cause issues as we start migrating more and more code to use composer's autoloader.

Some data:

On my local MediaWiki install running in a Ubuntu VM:
* Using prepend-autoloader: true: http://p.defau.lt/?WLSEpunDkWl_5BmCaW5KxQ
* Using prepend-autoloader: false: http://p.defau.lt/?924vZrq5d1XDMiQskeOGwg

On Wikimedia production:
* https://performance.wikimedia.org/xenon/svgs/daily/2014-12-31.svgz

**Comment by bd808** [comment]
The preliminary analysis in wmde/WikidataBuilder#32 may be of use in finding optimizations:
> An optimized autoloader does appear to put all PSR-0/4 classes that were registered with the current instance of composer in the class map. But it does not omit the PSR-0/4 string processing or prefix lists. So for a class that is not in either the class map or PSR-0/4, it will check the class map, then check the prefix lists, then finally return control to the rest of the spl_autoload_register() queue.

**Comment by bd808** [comment]
Looking at the [generated classloader for the Wikidata extension](https://github.com/wikimedia/mediawiki-extensions-Wikidata/blob/wmf/1.25wmf12c/vendor/composer/ClassLoader.php), the implementation of `ClassLoader::findFile` seems like the most likely place to make a significant optimization.

```
 public function findFile($class)
{
    // work around for PHP 5.3.0 - 5.3.2 https://bugs.php.net/50731
    if ('\\' == $class[0]) {
        $class = substr($class, 1);
    }

    // class map lookup
    if (isset($this->classMap[$class])) {
        return $this->classMap[$class];
    }

    $file = $this->findFileWithExtension($class, '.php');
    // Search for Hack files if we are running on HHVM
    if ($file === null && defined('HHVM_VERSION')) {
        $file = $this->findFileWithExtension($class, '.hh');
    }
    if ($file === null) {
        // Remember that this class does not exist.
    return $this->classMap[$class] = false;
    }
    return $file;
}
```

**Comment by JanTvrdik** [comment]
Currently the best you can do when using optimized autoloader is to avoid loading `vendor/autoload.php` entirely and do sth like:

~~~php
$clasmap = require __DIR__ . '/vendor/composer/autoload_classmap.php';
spl_autoload_register(function ($classname) use ($clasmap) {
	if (isset($clasmap[$classname])) {
		require $clasmap[$classname];
	}
});
~~~

**Comment by stof** [comment]
The case which is slow is indeed the case of classes which are not handled by the Composer autoloader (classes handled by the Composer autoloader should all be in the class map if you haven't created them after the generation of the optimized class loader).
The reason why Composer does not remove the PSR-0/4 handling in the optimized autoloader is precisely to avoid breaking the autoloading if new files are added after the generation (which is likely to happen locally) or were not detected by the classmap generation (weird edge cases).

So having a config flag for this might be an option indeed
