### ISSUE TITLE
Cli has stopped working - php 5.6

### ISSUE THREAD

**Issue by vincenzoraco** [composer/composer#3604]
When I run the commands composer install & composer update in Windows 8, using php 5.6, CLI stop to work.

**Comment by Seldaek** [comment]
Can you describe a bit more what you mean by the CLI stops working? Also did it work before? What changed?

**Comment by vincenzoraco** [comment]
I installed MAMP for Windows, after I installed Composer and I selected the php version 5.6, enabled openssl too. I installed Laravel 5 framework and works well., but when I use composer install (to install Laravel 5 fvendor) and try to download symfony/var-dumper a windows error appeared: CLI has stopped to working... and the download of laravel vendors in CMD stopped. I tried to use the php version 5.5.12 and works well. Maybe a bug with the 5.6 version?

**Comment by Seldaek** [comment]
Well as far as I know it works fine with 5.6, other people use it without problem. Do you see anything in the php error log or something? Without more details it's a bit hard to fix anything.

**Comment by vincenzoraco** [comment]
I'm so sorry. Now works well. I don't know why now works. I only enable error_log ... I clear the AppData/Local/Composer/files folder to be sure that Composer download again the vendors and I don't know now works!

Thanks anyway!

**Comment by Seldaek** [comment]
eh well, strange but good if it works I guess.

**Comment by dvrcthewrld** [comment]
I have this issue, and nothing I have tried has resolved it.

I'm running Wnmp (https://github.com/wnmp/wnmp), which includes PHP 5.6.5.
I have successfully installed Composer via the Windows installer and manually via the command line.

The problem comes up when is run `composer install` in a directory with a composer.json.  I get:

>Loading composer repositories with...
>Installing dependencies (including require-dev)
> - Installing gregwar/captcha (v.1.0.12)

And the moment that last line appears, a windows pops up notifying me that "CLI has stopped working".

**Comment by Seldaek** [comment]
@dvrcthewrld could it be an issue/bug in the way wnmp is built? Might be good to check with them if they have any issues with composer

**Comment by Sleavely** [comment]
In case of future googlers I had this issue too:

Upgrading to [PHP 5.6.7](http://windows.php.net/download/) by replacing the contents in `C:\Wnmp\php` solved it.

**Comment by SuperKiwi** [comment]
I'm having exactly the same issue  as @dvrcthewrld .
I'm running MAMP on Windows.
Any idea ?

**Comment by Sleavely** [comment]
@SuperKiwi Which version of PHP are you running (`php -v` in your console)? Did you try updating to the latest release for your version?

**Comment by SuperKiwi** [comment]
@Sleavely I'm using php 5.6.3

**Comment by Sleavely** [comment]
@SuperKiwi I suggest updating PHP (see my previous comment).

/Joakim Hedlund

**Comment by murraybiscuit** [comment]
Same issue here with wnmp - updating to latest php (5.6.7) solved it, as per earlier post.

**Comment by pete01** [comment]
I have the same issue with php 5.6.8 (latest) running on Windows 7 with opcache and xdebug 2.3.2 (latest) enabled.  When I try to install composer I get a "CLI has stopped working" error.

The composer installer command I'm using is straight from the composer getting started docs.

    php -r "readfile('https://getcomposer.org/installer');" | php

Here are the details of the "CLI has stopped working" error from Windows:

> Problem signature:
>  Problem Event Name:	APPCRASH
>  Application Name:	php.exe
>  Application Version:	5.6.8.0
>  Application Timestamp:	552ee168
>  Fault Module Name:	php_opcache.dll
>  Fault Module Version:	5.6.8.0
>  Fault Module Timestamp:	552ee392
>  Exception Code:	c0000005
>  Exception Offset:	00006cec
>  OS Version:	6.1.7601.2.1.0.256.48
>  Locale ID:	2057
>  Additional Information 1:	0a9e
>  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
>  Additional Information 3:	0a9e
>  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

This indicates the opcache is causing the problem, but it seems like a problem with having both opcache and xdebug enabled, as if I turn either of these extensions off the composer installer command works fine.

I've also found that Composer will still install when both opcache and xdebug are enabled, but only when not using the pipe command, e.g.

    php -r "readfile('https://getcomposer.org/installer');" > composerinstaller.php
    php composerinstaller.php

Maybe someone else knows what is going on?

**Comment by pete01** [comment]
I've raised a new issue about this problem here #3971

**Comment by quantuumsnot** [comment]
I've added a bug for this problem, it looks like the problem is in opcache dll, not in the composer. We'll see if they fix it in PHP 7 :D

**Comment by ivansf** [comment]
Running as an Administrator fixed it for me.

**Comment by hotrodfl** [comment]
Running as administrator didn't fix for me, neither opcache.enable_cli = 0.
I had to download the composer setup file and install it again. After that, the error was gone and I could run composer install with no problem.
Windows 8.1, MAMP, PHP 5.6.8

**Comment by julmot** [comment]
I had the same issue and updated from 5.6.4 to 5.6.10 and the issue was solved...!
![cli_doesnt_work_anymore](https://cloud.githubusercontent.com/assets/8310677/8504260/9c3e62fa-21ce-11e5-99d4-dc4ba40b9c21.jpg)

**Comment by hydrosquall** [comment]
+1, CLI stops working after installing the first required dependency ( vlucas/phpdotenv v1.1.1 )

Running PHP 5.6.8 included with MAMP

**Comment by thstarshine** [comment]
Same issue here using WNMP 2.1.8 (bundled with PHP 5.6.8).

By uncommenting **opache** extension in **php.ini** solved this problem.

```
zend_extension=php_opcache.dll
```

**Comment by nickdbush** [comment]
I can confirm that uncommenting the **opache** fixes the problem.

**Comment by imuller** [comment]
I also can confirm that this fixes the issue.

**Comment by philipgiuliani** [comment]
For me it also fixed the issues in MAMP. Thanks!

**Comment by haitonghn** [comment]
confirmed uncommenting the opache works for me with MAMP.

**Comment by dubl0dude** [comment]
Removing the comment for zend_extension=php_opcache.dll in php.ini worked! Thank you!

**Comment by zer0pants** [comment]
As above: Removing the comment for zend_extension=php_opcache.dll in php.ini worked for me. 

Environment:
Windows 10, PHP 5.6.8, running MAMP

**Comment by amelkikh** [comment]
Try opcache.enable_cli=1 or zend_extension=php_opcache.dll

**Comment by quantuumsnot** [comment]
amelkikh, why are you suggesting that when it's not working? No comment

**Comment by amelkikh** [comment]
@quantuumsnot, i tried it yesterday and i got. Why do you insist that it is not working?

**Comment by maikosoft** [comment]
Thanks thstarshine

uncommenting opache extension in php.ini solved this problem for me.

**Comment by razuro** [comment]
> zend_extension=php_opcache.dll

Thanks @thstarshine this works for me too. 
MAMP, PHP 5.6.8, Opcache OFF, Win 10

**Comment by youpixxl** [comment]
Thanks @thstarshine, this solved the issue for me as well

**Comment by joeygallegos** [comment]
Can confirm, doing the above has fixed the CLI crashing. Thanks @thstarshine!

**Comment by chucheria** [comment]
Thanks @thstarshine! Your solution works with Windows MAMP too! =)

**Comment by tconte252** [comment]
I'm using MAMP PHP 7 on Windows 8 and un-commenting zend_extension=php_opcache.dll does not resolve the issue for me. Am I missing something?

**Comment by quantuumsnot** [comment]
Which web-server and version - Apache or NginX?

**Comment by suraj-k** [comment]
![untitled](https://cloud.githubusercontent.com/assets/16421814/12018042/fdd01df6-ad83-11e5-83d3-6324416e74de.png)

Please help me

**Comment by quantuumsnot** [comment]
LOL :D

**Comment by poovarasanvasudevan** [comment]
![image](https://cloud.githubusercontent.com/assets/8036283/15731512/508646d0-2893-11e6-8e14-7c6fbc745818.png)


same as me when using composer update it stops in composer install it works .....

**Comment by desbest** [comment]
I'm having the same problem with wamp 2.5 and php 5.5.12
Please help.

**Comment by poovarasanvasudevan** [comment]
@desbest  composer selfupdate with solves my problem

**Comment by curry684** [comment]
Please do not kick old issues with "I also have this problem". This issue is closed and thus ignored. Open a new issue with *proper* information if you are experiencing *similar* issues.
