### ISSUE TITLE
Composer\Json\JsonValidationException

### ISSUE THREAD

**Issue by sportarc** [composer/composer#3605]
Hi,

Starting today composer doesn't validate the .json file properly.

Starting from scratch:
- Download composer: url -sS https://getcomposer.org/installer | php
- Create the following JSON:
{
    "require": {
        "monolog/monolog": "1.2.*"
    }
}
- Run:
$> ./composer.phar install
- Get follow error:
$> 
  [Composer\Json\JsonValidationException]                     
  "./composer.json" does not match the expected JSON schema:  
   - the property name is required                            
   - the property description is required                     
                                                              
It was working fine before now it doesn't.

Cheers

**Comment by LordRalex** [comment]
This is the same issue that was found with https://github.com/composer/composer/issues/3606
