### ISSUE TITLE
Required package name and description breaking old composer.json files

### ISSUE THREAD

**Issue by DaneEveritt** [composer/composer#3606]
The changes commited in b20153111b8c5256120d1383ab2303b65b8c5d9a have broken `composer.json` files that do not include the name or description. The documentation on the composer website does not list these as being needed for a basic composer setup, as as such they were not included in our shipped product since we were using composer solely to handle dependencies. With this change older versions of our software cannot be installed correctly since composer expects the `name` and `description` parameters to be there, and throws an error if they are not.

Is there a reason why this change was just now pushed and breaks old configurations without warning?

```
  [Composer\Json\JsonValidationException]                     
  "./composer.json" does not match the expected JSON schema:  
   - the property name is required                            
   - the property description is required   
```

**Comment by domhnallw** [comment]
Yep, I've just been bitten by this too. I can't do `composer global update` with version ddc1d377d7e07625cc1d0532dbbca881af141ad2

**Comment by driesvints** [comment]
I can confirm that this is now happening to our deployments as well. Ping @Seldaek

**Comment by driesvints** [comment]
Was it this commit that broke it perhaps? Merged today. b20153111b8c5256120d1383ab2303b65b8c5d9a

**Comment by domhnallw** [comment]
Yep, as identified above by the OP.

**Comment by ryan-senn** [comment]
Can confirm, if this is going to be a requirement `composer init` should at least add a default description.

**Comment by assertchris** [comment]
And the first `composer require` that creates a blank `composer.json`...

**Comment by Seldaek** [comment]
Works fine again now, sorry for the breakage.
