### ISSUE TITLE
auth.json refers to "github.com" instead of "api.github.com" for authenticated api calls

### ISSUE THREAD

**Issue by EdwardDrapkin** [composer/composer#3609]
I recently ran into a rate limit issue when I was running a composer update on a laravel project.  

I logged in via my credentials when prompted and had no luck.  I made sure the OAuth token in auth.json was correct, still no luck.

It finally worked when I noticed that the auth.json was mapping the OAuth token to github.com requests rather than api.github.com... so I created a new auth.json entry with the same OAuth token instead pointing to api.github.com, and voila, everything works as expected.

**Comment by Commifreak** [comment]
Ive tested your method, but had no luck:

```
{
    "http-basic": {},
    "github-oauth": {
        "api.github.com": "my_token"}
}

```

I still get:

```
C:\Users\robin.kluth>composer diag
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity: OK
Checking HTTP proxy: OK
Checking HTTP proxy support for request_fulluri: OK
Checking HTTPS proxy support for request_fulluri:
Could not fetch https://api.github.com/repos/Seldaek/jsonlint/zipball/1.0.0, ent
er your GitHub credentials to go over the API rate limit
The credentials will be swapped for an OAuth token stored in C:/Users/robin.klut
h/AppData/Roaming/Composer/auth.json, your password will not be stored
To revoke access to this token you can visit https://github.com/settings/applica
tions
Username:
```

I used the auth.json mentioned in this warning.

**Comment by alcohol** [comment]
You should not put `api.github.com` as the key but `github.com`. So:

```
{
    "http-basic": {},
    "github-oauth": {
        "github.com": "__TOKEN__"}
}
```

**Comment by alcohol** [comment]
On a side note, this issue should be closed as it presents false information.

**Comment by webdevilopers** [comment]
I have the same problem @EdwardDrapkin . I tried your solution but failed like @Commifreak .

I edited my `auth.json` trying `api.github.com` as key but the token was not accepted.

I still get:
```
  * An existing OAuth token for Composer is present and will be reused
  * Could not fetch https://api.github.com/authorizations, enter your GitHub credentials to go over the API rate limit
  * The credentials will be swapped for an OAuth token stored in .../.composer/auth.json, your password will not be stored
  * To revoke access to this token you can visit https://github.com/settings/applications
```

After entering my credentials the `auth.json` will again receive the `github,com` entry with the same token.

But Composer simply doesn't accept it and again wants me to enter my credentials.

I have tested this on two totally different servers and misc permissions.

**Comment by webdevilopers** [comment]
The following issues provide more information:
- https://github.com/composer/composer/issues/3542
- https://github.com/composer/composer/issues/3566

**Comment by cero25** [comment]
Super genial si funciono:

composer config -g --unset github-oauth.api.github.com
composer config -g github-oauth.github.com __TOKEN__

**Comment by kenorb** [comment]
Related: [Document setting up a github oauth token](https://github.com/composer/composer/issues/2366).

**Comment by Ianluyon** [comment]
[UnexpectedValueException]
  Your github oauth token for github.com contains invalid characters: "__TOKEN__"

**Comment by rolansoliz12** [comment]
> [UnexpectedValueException] 
> Su token de github oauth para github.com contiene caracteres no válidos: " **TOKEN** "

hola como lo pudiste soucionar?
yo tengo ese mismo error

**Comment by smelike** [comment]
> You should not put `api.github.com` as the key but `github.com`. So:
> 
> ```
> {
>     "http-basic": {},
>     "github-oauth": {
>         "github.com": "__TOKEN__"}
> }
> ```
> 
> Edit the file manually or run:
> 
> ```
> composer config -g --unset github-oauth.api.github.com
> composer config -g github-oauth.github.com __TOKEN__
> ```

Fix the issue. Thanks a lot.

**Comment by tronganh1994** [comment]
composer config -g --unset github-oauth.api.github.com
composer config -g github-oauth.github.com __TOKEN__
After following and:   [UnexpectedValueException]
  Your github oauth token for github.com contains invalid characters: "__TOKEN__"

**Comment by urbanovich** [comment]
@tronganh1994 

I did this:

`rm -rf ~/composer/auth.json
composer clearcache
Do you want to store credentials for bitbucket.org in /root/.composer/auth.json ? [Yn] n`

for me it works

**Comment by amadu80** [comment]
Updating composer fixed the issue for me:

`` composer self-update`
