### ISSUE TITLE
Downloader emitts a Backspace-character even when `--no-ansi` supplied.

### ISSUE THREAD

**Issue by staabm** [composer/composer#3612]
Shouldn't the downloader only emit this `BS` chars, when ansi is allowed?

![composer](https://cloud.githubusercontent.com/assets/120441/5612550/2c39aa8e-94d7-11e4-9298-ac0575c6764f.png)

PS: these `BS` chars are only visible with my editor, those are not rendered like that. Its a regular BS char.

**Comment by stof** [comment]
hmm, maybe the ``--no-progress`` option should be impplied when using ``--no-ansi``. What do you think @Seldaek ?

**Comment by staabm** [comment]
Is a non cli environment relevant for composer? If so, the progress indication should be aware of cli vs. non-cli environments - at least to not print the `BS` based progress-chars in non-cli sapis.

**Comment by Seldaek** [comment]
I don't think SAPI based is good because even in a web context you might want fully formatted output for some reasons (there are js renderers for ansi codes etc).

Anyway I'll push a fix shortly.

**Comment by staabm** [comment]
fix confirmed, thanks @Seldaek !

**Comment by vlakoff** [comment]
With these changes, overwrites are disabled on Windows CLI… I tried `--ansi` but it produces garbage.

Although not a big deal, could it be corrected?

**Comment by Seldaek** [comment]
@vlakoff to get full ANSI support on windows I'd recommend you use [ConEmu](https://conemu.codeplex.com/) as terminal or alternatively you can install [ansicon](https://github.com/adoxa/ansicon) which will add ANSI support to the cmd.exe or other terminals.

**Comment by vlakoff** [comment]
Thank you for the tips :) Though, the less I have to install/store/maintain/memorize, the better I feel :blush:

I simply mentioned the issue because Windows CLI was working fine previously. But this "shell" is so shitty it doesn't deserve much care ;)

**Comment by Seldaek** [comment]
Well I do care about windows as I use it myself but it makes things more 
complex for "nothing" if we need to have different flags for colors and 
overwrite. If you develop on windows IMO having ansicon or a proper 
terminal is a must.

**Comment by dzuelke** [comment]
Wait, so c58b7d9 fixes this on its own, correct? Because the side effect of e0d36e1 is that it also disables  progress for piped output, see #3715.

Question is if ANSI == decoration and piping != decoration (done through `posix_isatty` on the stream) should really be treated the same?

And why not just use `\r` instead of backspaces; does that not do the trick?

**Comment by dzuelke** [comment]
> And why not just use `\r` instead of backspaces; does that not do the trick?

Actually, that doesn't work if e.g. `composer install` is piped through anything that writes stuff to the beginning of the line (for indenting, logging, ...), so ignore that idea.

**Comment by dzuelke** [comment]
But e0d36e1 could still be backed out, no, @Seldaek? /cc @alcohol

**Comment by alcohol** [comment]
Ah, interesting. Was not aware of this. That would explain it though. Not sure what the best fix would be. Also, please don't ask me, cause I'm totally biased and I would say "tough luck for the Windows users". :D

**Comment by Seldaek** [comment]
Well.. the question is whether a backspace char should be considered as fancy ANSI or not. If not then we can revert e0d36e19eb8a5c96ccad3d145faf9024727e856c and @dzuelke is happy but @staabm's initial issue comes back. 

The other question is what was the initial issue. It appears that windows actually supports the backspaces just fine natively as per @vlakoff's messages, so it's not a windows issue, but for @staabm it failed. So what was the use case there? If it's when piping output to an editor that you see "garbage" well I would say that's normal and not really an issue we need to take care of and maybe you can sed the backspaces away if it's really important.

I would tend towards revert but I'd like to hear from @staabm first.

**Comment by staabm** [comment]
@Seldaek I did experience the issue while rendering composers output into a website (while doing the php-consoles' melody-script integration)

**Comment by stof** [comment]
@staabm the [ansi-to-html converter](https://github.com/sensiolabs/ansi-to-html) written by SensioLabs supports backspace chars AFAIK

**Comment by dzuelke** [comment]
> Well.. the question is whether a backspace char should be considered as fancy ANSI or not. If not then we can revert e0d36e1 and @dzuelke is happy but @staabm's initial issue comes back.

I don't think it comes back, @Seldaek, because c58b7d9 works around it as well.

**Comment by dzuelke** [comment]
> I did experience the issue while rendering composers output into a website (while doing the php-consoles' melody-script integration)

How did you embed the output, @staabm? `exec()`? `passthru()`? `system()`?

**Comment by dzuelke** [comment]
Don't forget to revert the related 331425bcb3cd13a5d5d807c13c6a651229b56ac8 as well, @Seldaek!

**Comment by staabm** [comment]
> How did you embed the output, @staabm? exec()? passthru()? system()?

The code which required those changes is here: https://github.com/Seldaek/php-console/pull/43

Composer is called using `exec()`, see https://github.com/Seldaek/php-console/pull/43/files#diff-9961bb8261d1f98eab87bc0270ac8a8eR21

**Comment by dzuelke** [comment]
And how did you render the output to HTML, @staabm? Specifically, where do the black "BS" codes come from? Is the screenshot you provided from a website (`<pre>` block or whatever), or from a console?

**Comment by staabm** [comment]
The screen in the description of this PR is the right panel of the "website" you see in Seldaek/php-console#43 description.

The text was rendered into a `<div>`

**Comment by dzuelke** [comment]
Well, that's a feature then. https://github.com/Seldaek/php-console/releases/tag/1.4.0

**Comment by staabm** [comment]
> Well, that's a feature then. https://github.com/Seldaek/php-console/releases/tag/1.4.0

You are right. It was me who contributed the feature ;).

My initial request asked about if the `BS` char is "valid" when `no-ansi` is supplied.
In case its valid I would solve my problem within php-console differently.

**Comment by dzuelke** [comment]
Nope, `BS` is ASCII `08h`. Not ANSI.

**Comment by dzuelke** [comment]
ANSI escapes are more complicated and used for formatting; say `1Bh` (`ESC`), then `[`, then e.g. `31m` to switch to red text color.

**Comment by Seldaek** [comment]
Alright back to normal with overwrites, I hope you find a way to work around this @staabm :)

**Comment by danielbachhuber** [comment]
For the next person to stumble on this thread trying to disable the backspace character:

```
# Run composer update and capture to untracked log file
composer update --no-progress --no-dev --no-interaction |& tee vendor/update.log
UPDATE=$(cat vendor/update.log | col -b)
```
