### ISSUE TITLE
Feature: allow registration of autorun in packages

### ISSUE THREAD

**Issue by Addvilz** [composer/composer#3613]
Idea is to add optional key "autorun" to composer.json which could contain a class name::method to be registered as auto-run-able. Composer would aggregate such "autorun" classes and allow to get list of the classes and packages that want's to be automatically executed. It would be then up to each individual user to decide which packages would be run this way. 

Could be a neat way to provide extensions/modules/etc that automatically registers themselves when installed etc. 

This might be out of scope of composer, but as it's so widely used, I guess that this idea could be, at the very least, considered.

**Comment by Seldaek** [comment]
https://getcomposer.org/doc/04-schema.md#files is sort of autorun for code, but I see it's not exactly what you mean. Such a tool could definitely built as third party package though so I'd rather keep it out of Composer itself (we have enough to maintain already..).
