### ISSUE TITLE
Installation fails on Windows: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

### ISSUE THREAD

**Issue by blemaire** [composer/composer#3615]
Hi all.

I am trying to install composer for the first time on a windows machine. 
I use the command line version and here is the error message:

./php -r "readfile('https://getcomposer.org/installer');" | ./php

Warning: readfile(): SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol in Command line code on line 1
Call Stack:
0.0010     117200   1. {main}() Command line code:0
0.0010     117312   2. readfile() Command line code:1
Warning: readfile(): Failed to enable crypto in Command line code on line 1
Call Stack:
    0.0010     117200   1. {main}() Command line code:0
    0.0010     117312   2. readfile() Command line code:1
Warning: readfile(https://getcomposer.org/installer): failed to open stream: operation failed in Command line code on line 1
Call Stack:
    0.0010     117200   1. {main}() Command line code:0
    0.0010     117312   2. readfile() Command line code:1

If I use HTTP instead, I get the following error:

./php -r "readfile('http://getcomposer.org/installer');" | ./php

#!/usr/bin/env php
All settings correct for using Composer
Downloading...
Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed
Downloading...
Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed
Downloading...
Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed
The download failed repeatedly, aborting.

./php -v
PHP 5.5.12 (cli) (built: Apr 30 2014 11:20:55)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans

NOTE I use the HTTP_PROXY User Variable. (same result without it)

Thanks a lot for your help.
Bastien

**Comment by daragilroy** [comment]
Hi #blemaire, I was getting the same issue but found that using this on the command line worked:

echo "<?php echo file_get_contents('https://getcomposer.org/composer.phar') ?>" | php > composer.phar

**Comment by daragilroy** [comment]
Hi #blemaire, I was getting the same issue but found that using this on the command line worked:

echo "<?php echo file_get_contents('https://getcomposer.org/composer.phar') ?>" | php > composer.phar

**Comment by blemaire** [comment]
Hi, thanks a lot, this allowed me to donwload the composer.phar file but now I cannot install it.

I run php composer.phar install and get the following:
Warning:file_get_contents():SSL operation failed with code 1. OpenSSLErrormessages:
error:140770FC:SSLroutines:SSL23_GET_SERVER_HELLO:unknown protocol in - on line 1
CallStack:
0.00101205121.{main}()-:0
0.00101206242.file_get_contents()-:1
Warning:file_get_contents():Failed to enable crypto in - on line 1
CallStack:
0.00101205121.{main}()-:0
0.00101206242.file_get_contents()-:1
Warning:file get_contents(https://getcomposer.org/composer.phar):failed to open stream:operation failed in - on line 1
CallStack:
0.00101205121.{main}()-:0
0.00101206242.file_get_contents()-:1


PHP 5.5.12
Zend Engine v2.5.0
with Xdebug v2.2.5
On windows 7 professional 32bit

Thanks a lot

**Comment by Seldaek** [comment]
It looks like your php's openssl config is broken somehow. Or perhaps your proxy is doing stupid things. Quoting stackoverflow:

> You will get such error message when you request HTTPS resource via wrong port, such as 80. So please make sure you specified right port, 443, in the Request options.

So I'd guess your proxy connects to port 80 and php tries to open an ssl connection and that fails, or something similar.

**Comment by LenChi0723** [comment]
Try “http://getcomposer.org/composer.phar”

**Comment by kssalanio** [comment]
Hi, I am encountering the same problem and my suspicion is that the proxy uses a self-signed certificate. Is there a way to disable SSL verification for composer? Maybe that will work.

**Comment by ryanwohara** [comment]
This is not an issue with composer and should be closed.

**Comment by salarmehr** [comment]
@blemaire I has the same issue. specify cert path on php.ini  `openssl.cafile="D:\...\cacert.pem"` (http://curl.haxx.se/ca/cacert.pem).

@Seldaek I think this should be mentioned on the installation guild.
