### ISSUE TITLE
Conditional requirements

### ISSUE THREAD

**Issue by Crash--** [composer/composer#3618]
Actually, we've to deal with PHP 5.4 (for instance with APC), 5.5+ (for instance without APC), soon 7 and HHVM (with some broken PHP extensions). 

With composer, we can not have conditional requirements based on the PHP engine or PHP version. So I suggest to had it to composer. 

We can imagine something like : 

```
"require": {
        "php": ">=5.4",
        "ext-mcrypt" : "*"
},
"require-if" : {
        "php >= 5.5" : { 
            "ext-apcu" : "*" 
        },
        "php < 5.5" : {
            "ext-apc" : "*" 
        }
}
```

What guys do you think about that?

**Comment by stof** [comment]
This looks like a special case for https://github.com/composer/composer/issues/751

**Comment by alcohol** [comment]
On a side note, `ext-apcu` could be considered as a "replaces" or "provides" for `ext-apc`. That could partially solve it. But these virtual packages are hard-coded in composer in some form if I am not mistaken, so not sure how feasible this would be.

**Comment by hazardland** [comment]
I even tweeted this ext-apc/ext-apcu case to composer developer but seems they are having hard life...

: D

**Comment by Seldaek** [comment]
See #3865 - requiring ext-apc is enough as apcu marks apc as being loaded as well

**Comment by sminnee** [comment]
Note that I've created a new "conditional dependencies" ticket at #4168, that isn't catered to by the provides or alternatives approaches.
