### ISSUE TITLE
configuration for dependency injection in composer.json

### ISSUE THREAD

**Issue by downsider** [composer/composer#3619]
This is a proposal for an addition to composer.json to allow modules installed by composer to define dependency injection service configuration.
The purpose is to avoid having to set up DI configuration in every application that a module is used in (as much as possible). This would be analogous to how composer deals with autoloading.

For example, if I have three classes in a module, A, B and C, where C is a dependency of B and B is a dependency of A, I would want the module to be able to define the configuration for this so that the application could simply load the module and have the services available automatically.
I wouldn't expect the module itself to implement DI as this is the remit of the application itself, but being able to have composer create a list of configuration or bootstrap files would let a specific DI implementation import the files and process them.

In composer.json, this would look something like the following:

    {
      "name": "foo/bar",
      "description": "a module for use in an application",
      ...
      "dependency-injection": {
        "pimple/pimple": [
          {
            "path": "[path to bootstrap file]"
          }
        ],
        "symfony/dependency-injection": [
          {
            "path": "[path to services file]"
          }
        ]
      }
    }
Composer would auto-generate a class which contains an array of all the configuration files. This  could be accessed statically from within the application, returning a list of all configuration files for a specific key.

The keys in "dependency-injection" reference the DI module that an application may be using, allowing for an implementation to look for it's own configuration. In this example, I've used package names as these are likely to be collision free, but this is not technically a requirement; DI implementations could look for any key they want to in the array.

I can foresee issues with service name collisions within the configuration files when importing multiple modules, which may need some sort of alias system and I'm sure there are other considerations, but do you think this is a good idea, or is it not something that composer should be doing?

**Comment by Flyingmana** [comment]
I think its more suited for a plugin, as it is not a general usecase and different for every framework.

**Comment by stof** [comment]
This should indeed be handled by a plugin reading such information from a key inside the ``extras`` element of the composer config (https://github.com/Incenteev/ParameterHandler/ is doing it for instance)

**Comment by downsider** [comment]
Ok, I can see your logic. Thanks for your feedback.
