### ISSUE TITLE
Host Port in composer.json Missing from composer.lock

### ISSUE THREAD

**Issue by seydu** [composer/composer#3621]
My Statis server is listening on a non standard port, so I had to put the port in the composer.json.
But in the generated composer.lock the port is stripped (9877), so my downloads fail
```json
{
    "name": "...",
    "description": "...",
    "repositories": [ 
      { "type": "composer", "url": "http://packagist.my-company.net:9877" },
      { "type": "composer", "url": "https://packagist.org" }
    ],
    "require": {
        "my-company/my-repo":                                      "0.1.1"
    },
    "minimum-stability": "dev"
}
```

**Comment by Seldaek** [comment]
What do you see in the composer.lock? Is it in the source/dist:url key that the repo is missing the :9877?

**Comment by seydu** [comment]
The port is not reported in composer.lock. This is what I have:
```json
{
    "name": "my-company/my-repo",
    "version": "0.1.1",
    "source": {
        "type": "git",
        "url": "git@bitbucket.org:my-company/my-repo.git",
        "reference": "e35f6c9457b40bbab150cfab2962c92fcc4fbb56",
        "mirrors": [
            {
                "url": "/git/mirrors/%package%/%normalizedUrl%.%type%",
                "preferred": true
            }
        ]
    },
    "dist": {
        "type": "zip",
        "url": "http://toranproxy.my-company.net/repo/private/dists/my-company/my-repo/0.1.1.0/e35f6c9457b40bbab150cfab2962c92fcc4fbb56.zip",
        "reference": "e35f6c9457b40bbab150cfab2962c92fcc4fbb56",
        "shasum": null,
        "mirrors": [
            {
                "url": "http://toranproxy.my-company.net/repo/private/dists/%package%/%version%/%reference%.%type%",
                "preferred": true
            }
        ]
    }

**Comment by Seldaek** [comment]
Are you using toran, satis or packagist? You mention satis but have a packagist.foo domain in the composer.json above and a toran one in the composer.lock so I am not quite sure.

**Comment by seydu** [comment]
In my bug report I mentioned Stais, but I have the same behavior for Toran Proxy.
I did not install packagist.
packagist.my-company.net is my Statis webserver
toranprox.my-company.net is my Toran Proxy.
Since I was testing both satis an Toran Proxy, the composer.json sample comes from my Statis install and the composer.lock comes from my Toran Proxy .
From now on I will use samples from Toran Proxy. 
This is the composer.json (only the port and the DNS name changes):
```json
{
    "name": "...",
    "description": "...",
    "repositories": [ 
      { "type": "composer", "url": "http://toranproxy.my-company.net:9876" },
      { "type": "composer", "url": "https://packagist.org" }
    ],
    "require": {
        "my-company/my-repo":                                      "0.1.1"
    },
    "minimum-stability": "dev"
}
```

**Comment by Seldaek** [comment]
OK so for Toran if you configure the `toran_http_port` parameter in `app/config/parameters.yml` to `9877` it should work fine. After changing it though you should make sure you empty `app/cache/prod` and re-run the bin/cron command to regenerate private package urls.

After that, in your composer project you should empty the vendor dir and run a `composer update` to generate a new `composer.lock` file that contains the new urls and not cached urls from the installed vendors.

I tested that here and it seems to work fine.
