### ISSUE TITLE
Using composer require in console downloads .json slow but instantaneous in browser

### ISSUE THREAD

**Issue by MauJFernandez** [composer/composer#3623]
I'm using composer require to download a package and it's super slow, I used -vvv to see what's going on and it's really slow to download a .json (like http://packagist.org/p/symfony/http-foundation$dbdc943fa7072059de0ae44f7afbc1f8289b30edd58cdb9e89e8ae35caca556d.json) but if I open that link in the browser it loads in a second, what's happening?

**Comment by Seldaek** [comment]
When you see in the output a list of "Downloading lala..." it doesn't do *only* that. It also loads packages in those files etc, so it can take some CPU time in between downloads.
