### ISSUE TITLE
Composer command not found

### ISSUE THREAD

**Issue by TheGeekdu74** [composer/composer#3625]
Hello, I have a problem : I am on Ubuntu 14.04, I do ALL steps to install the composer, but I can't do a composer command. In my Path, I have /usr/local/bin/. Anybody can help me ?

**Comment by stof** [comment]
is the ``/usr/local/bin/composer`` file executable ?

**Comment by TheGeekdu74** [comment]
I don't udnerstand. The folder composer got all permissions but why is file executable

**Comment by stof** [comment]
Folder ? If you follow the instructions to install Composer globally, ``/usr/local/bin/composer`` is a file (a phar archive), not a folder

**Comment by TheGeekdu74** [comment]
Phar archive ? So I need to install composer into composer.phar ?

**Comment by TheGeekdu74** [comment]
Ok so, I have the file "composer", it's a script file. I need to do "php composer.phar install" but when I do that, the CMD tell me "Could not open input file composer.phar"

**Comment by stof** [comment]
OK, so is your composer script file executable or no ? If it is in your PATH and is executable, your OS should find it

**Comment by stof** [comment]
and no, if you install it globally, you won't run ``php composer.phar install``. You will run ``composer install``. ``php composer.phar install`` is for local installs (when you have the composer phar executable in the current folder)

**Comment by TheGeekdu74** [comment]
Ok, so I can create a folder named "Composer", put in the composer script file, create the file composer.json with monolog and do "compsoer install" right ?

**Comment by hugofonseca** [comment]
Undo whatever you did and try:
```curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer```
good?

**Comment by TheGeekdu74** [comment]
Ok I gonna try that

**Comment by TheGeekdu74** [comment]
Ok, I have a script file named "composer", and now ?

**Comment by hugofonseca** [comment]
So, you still don't have composer?
What's the output of ```composer --version``` ?
And ```cat /etc/environment```?

**Comment by TheGeekdu74** [comment]
For composer --version : 1.0-dev
For cat /etc/environnement : I need to do this command ? Because she doesn't work

**Comment by stof** [comment]
Well, if you get the output for ``composer --version``, it means you have composer, as you just managed to run it

**Comment by TheGeekdu74** [comment]
I passed under Debian. I hate this ******** sudo

**Comment by mahendranmails** [comment]
I get into the same issue even after moving the `composer.phar` to '/usr/local/bin/composer' using the following command in amazon linux.

`mv composer.phar /usr/local/bin/composer`

I used the following command to create a alias for the composer file. So now its running globally. 

**`alias composer='/usr/local/bin/composer'`**

Hope this will help someone.

**Comment by CuriouslyGeorge** [comment]
Thank you Mahendranmails!! I have been wracking my brains and the internet over this one.
On my Centos 6 system, following all of the directions to install composer, it would still not work.
The Alias command sorted out
alias composer='/usr/local/bin/composer'
Good job +1

**Comment by andriynichik** [comment]
zxc

**Comment by AmrEmara** [comment]
@Mahendran-Sakkarai i'm facing the same problem and i moved the composer.phar executable to usr/local/bin/composer but whenever i execute composer it does not recognise the command , i used the last command you added "alias composer='/usr/local/bin/composer'" first it did not work as composer is a file directory and not an executable so i added composer.phar to the path it looked like "alias composer='/usr/local/bin/composer/composer.phar'" and finally it worked , but the problem is that whenever i logout and login i have to go through the whole process again , so do you have any idea how do i make the alias name permanent so that i won't have to type the alias command everytime i want to use the composer ?!

**Comment by Mahendran-Sakkarai** [comment]
@AmrEmara 

You need to add the alias into **.bash_aliases** file to make it work whenever you open the terminal.

First navigate to your user path using the bellow command.

>cd ~

Then create or open a file named **.bash_aliases** in the home user  path using the following command.

>nano .bash_aliases

Then add the **alias composer='/usr/local/bin/composer/composer.phar'** to that file and save it. So it will be work even after you restarting the system.

**Comment by AmrEmara** [comment]
Thank you so much @mahendran-sakkarai

**Comment by aboutvale** [comment]
Thanks @Mahendran-Sakkarai

**Comment by pratika2395** [comment]
@fonsecas72 , I too have the same issue. when i run -"**composer --version**" it is telling "**command not found**" and for "**cat /etc/environmen**t" the path was "**PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games**"

what should i do now?

**Comment by fonsecas72** [comment]
@pratika2395  how did you installed composer?  

Did you ran the following?
`curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer`

What's the output of `test -e /usr/local/bin/composer && echo WORKING || echo NOT WORKING` ?

**Comment by fonsecas72** [comment]
If it doesn't work you can also try these instruction https://getcomposer.org/download/

**Comment by pratika2395** [comment]
@fonsecas72 , I used this command only -"**curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer**"

when i ran this command -"**test -e /usr/local/bin/composer && echo WORKING || echo NOT WORKING**" i got this -" **WORKING**"

i should run this test -e command in my current working directory right?

**Comment by fonsecas72** [comment]
@pratika2395  could you run `sudo chmod +x /usr/local/bin/composer` and try `composer --version` again?

I'm running out of options. It should be working by now :thinking:

**Comment by pratika2395** [comment]
Composer version 1.6.3 2018-01-31 16:28:17

**Comment by affanahmed70** [comment]
try to give executable permission to /usr/local/bin/composer 
run this command in terminal : sudo chmod 777 -R  /usr/local/bin/composer
