### ISSUE TITLE
Composer is pulling very strange classnames into the autoloader

### ISSUE THREAD

**Issue by deltamualpha** [composer/composer#3629]
We have an issue where composer is adding strange, duplicate, and inaccurate classnames to the autoload_classmap.php file, as well as missing at least one file. One example:

`'for' => $baseDir . '/webroot/models/authbackend.php',`
`'AuthBackend' => $baseDir . '/webroot/models/authbackend.php',`

the `for` being the obvious error. We cannot duplicate this on our local machines, only on our build server, and all environments are running the most recent version of composer (c58b7d917c65692eeb00c22b2fbaaa251cb390dc as of this moment). We're stumped as to what's going on. Have you ever seen this behavior, and can you give us any tips on how to debug it?

**Comment by deltamualpha** [comment]
It's also not reading and including one file from within the directory, but I have a feeling that's a symptom and not a cause.

**Comment by alcohol** [comment]
Resolved: [php.net/php_strip_whitespace](php.net/php_strip_whitespace) does not work on files that make use of short tags (`<?` vs `<?php`).

**Comment by deltamualpha** [comment]
Or, at the very least, if you don't have the proper setting turned on in `php.ini`. (Which you shouldn't, because Short Tags Are Evil™
