### ISSUE TITLE
Require all

### ISSUE THREAD

**Issue by lordjim666** [composer/composer#3634]
I would appreciate something like "require all" in composer.json, so I could install everything in packagist.org.

**Comment by lordjim666** [comment]
Yes, but there's no size. Ok, then it could at least generate some nice network of dependencies between packages. Of course again no use case :)

**Comment by stof** [comment]
the network of dependencies between packages would be totally unreadable (especially if you keep in mind that dependencies can be different for each version of a package, so you don't need to display the 47000 packages but the 200000 versions). Such dependency graph must be restricted to a subset of packages (for instance, http://hhvm.h4cc.de/graphs/symfony_2_6.png which displays the graph of resolved dependencies for the symfony standard edition 2.6 only)

**Comment by Seldaek** [comment]
Indeed I don't see the point of having this in composer, if anything it's something another tool should do, the data is there in the open, https://packagist.org/packages/list.json - have fun :)
