### ISSUE TITLE
Repository Security Exception 

### ISSUE THREAD

**Issue by harshitj2005** [composer/composer#3637]
hi, when entering the command composer global require "fxp/composer-asset-plugin:1.0.0-beta4"
i am having this problem

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>composer global require "fxp/composer-asset-plugin:1.0.0-
beta4"
Changed current directory to C:/Users/Administrator/AppData/Roaming/Composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

[Composer\Repository\RepositorySecurityException]
The contents of http://packagist.org/p/fxp/composer-asset-plugin$d32cc21e8445e6a298ce3d43eedc79e599dfd5d477d6a1126364b7c886eee7ed.json do not match it
s signature. This should indicate a man-in-the-middle attack. Try running c
omposer again and report this if you think it is a mistake.

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update]
[--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-
packages] [packages1] ... [packagesN]

i am this issue as given above. this is my console output.
i am working on windows 7 64 bit OS and using php version 5.4.27,
i have also enable extension=php_openssl.dll in php.ini,
also have updated my composer by composer update command,
have tried others solutions also but not working like
composer config -g github-oauth.github.com {output: syntax error}
composer config -ge adding lines 
"repositories": {
"packagist": { "url": "https://packagist.org", "type": "composer" }
}
still problem persits.

thanks in advance.

**Comment by Seldaek** [comment]
This is usually caused by proxies modifying web traffic. It's quite hard to debug remotely as we can not reproduce it, but if you can try to run the same command from another network

**Comment by harshitj2005** [comment]
but i need to run the same command from my PC and i am not able to get proxies modifying web traffic. i am having seprate ip asigned for my PC. and i dont have any shared server.

**Comment by Seldaek** [comment]
Maybe you could try with a VPN?

**Comment by Seldaek** [comment]
Hopefully fixed by https://github.com/composer/composer/commit/ed954485239ad88f94bcee80a6a648d7943932f8
