### ISSUE TITLE
Random access error for a particular project with weird workaround

### ISSUE THREAD

**Issue by Hypoaristerolactotherapist** [composer/composer#3638]
When refreshing project `predis/predis dev-master`, I randomly get the following error message on a nice looking red background.

```
 [RuntimeException]                                                                      
  Failed to clone git@github.com:nrk/predis.git via git, https, ssh protocols, aborting.  
  - git://github.com/nrk/predis.git                                                       
    From git://github.com/nrk/predis                                                      
       28accc9..b8decc7  master     -> composer/master                                    
    error: there are still refs under 'refs/remotes/composer/v1.0'                        
     ! [new branch]      v1.0       -> composer/v1.0  (unable to update local ref)        
  - https://github.com/nrk/predis.git                                                     
    error: there are still refs under 'refs/remotes/composer/v1.0'                        
    From https://github.com/nrk/predis                                                    
     ! [new branch]      v1.0       -> composer/v1.0  (unable to update local ref)        
     * [new tag]         v1.0.1     -> v1.0.1                                             
  - git@github.com:nrk/predis.git                                                         
    Permission denied (publickey).                                                        
    fatal: Could not read from remote repository.                                         
                                                                                          
    Please make sure you have the correct access rights                                   
    and the repository exists. 
```

If I add the very verbose option (`-vvv`) to understand what's going on, composer refreshes correctly the project with the last version.
I tried deleting the cache but it does not solve anything. Just add `-vvv`.
It is going for some time now so it is now worth solving.

**Comment by Seldaek** [comment]
As far as I can tell this happened because the predis git repo had a force push that created a conflict with what you had locally. Removing vendor/predis/predis and reinstalling the package should fix it. I am not sure if we can or should handle this automatically really, sounds likely to backfire in unexpected ways and it's not like it happens often anyway.

**Comment by nrk** [comment]
A few days ago I had a minor screw-up with the master branch of Predis while applying some patches that resulted in a few duplicated commits but still nothing that involved a forced push. On the contrary, I purposely resisted the itch to rewrite the history to remove the duplicated commits thus avoiding a _push -f_.

**Comment by Seldaek** [comment]
Eh well I don't know what exactly happened then.

**Comment by Hypoaristerolactotherapist** [comment]
Your solution of removing and reinstalling Predis doesn't change the issue.

No clue of what's going on.

**Comment by Seldaek** [comment]
@Hypoaristerolactotherapist can you post exact steps to reproduce this?
