### ISSUE TITLE
Add new command: composer which

### ISSUE THREAD

**Issue by ikhsan017** [composer/composer#3640]
I have a situation where I install laravel and require [oauth2-server-laravel](https://github.com/lucadegasperi/oauth2-server-laravel)

when running ```artisan db:seed```, the command calls the DatabaseSeeder class, but instead calling the laravel's default seeder located in 
``` 
app/database/seeds/DatabaseSeeder.php 
```
it calls DatabaseSeeder from oauth package which located in 
``` 
vendor/lucadegaseri/oauth2-server-laravel/seeds/DatabaseSeeder.php
```

both are registered in root composer.json and package's composer.json as classmap, and no warning appear when generating autoload/optimized autoload file.

this issue is to propose addition of  simple command ```composer which ClassName``` to resolve the file where those class is defined.

What do you all think about this?

additional info:
composer version:
```1.0-dev (e172cd81a146666d844d2b7b37b5feccb89e2b61) 2015-01-02 07:55:29```

regards
Ikhsan

**Comment by slbmeh** [comment]
I've run in to this problem before, but generally by the time you are far enough in to troubleshooting that you pinpoint what class is causing the issue there isn't much more to determine.

Ideally it should be a `conflicts` or `replaces` resolution between the competing packages, or one of them shouldn't use a namespace they aren't authoritative over. I don't know enough about Laravel myself to know if that's commonplace to overwrite classes within their implementation space.

**Comment by Seldaek** [comment]
I agree this isn't very valuable for the amount of work so closing.
