### ISSUE TITLE
Private repositories: cannot change username and/or password

### ISSUE THREAD

**Issue by frederikbosch** [composer/composer#3644]
Beacuse the password is hardcoded in the composer remote (.git/config), the user is not able to change authentication credentials in auth.json. The only way to do this is by removing the vendor folder and run `composer install` again.

PR #3608 fixes this issue.

**Comment by midan888** [comment]
Wow man thanks.

**Comment by AndreKR** [comment]
I was bitten by this today and I traced it back to this part:

https://github.com/composer/composer/blob/fdcae616b0bdf57b1460491badb4501906a83044/src/Composer/Util/Git.php#L57-L61

For each dependency, credentials are stored once in `.git/config` **and then will forever take precedence over any credentials set in `auth.json`**.

I wholeheartedly agree with the comments by @frederikbosch here: https://github.com/composer/composer/pull/3608/files#r23305353

I think the current behavior is confusing, useless and dangerous. It should be removed and _if_ it actually breaks an existing automated flow, then this flow was broken to begin with: Why would any flow rely on credentials that are secretly cached inside the dependency directory. On the other hand, removing this code would open up a much more reasonable flow: Set credentials (which can be a temporary CI token) in `auth.json` and use those same credentials for _both_ installing new dependency as well as updating existing ones. (Currently the credentials from `auth.json` are used for new/deleted dependencies and the cached credentials are used for existing ones.)

**Comment by Seldaek** [comment]
Sorry this took so long but should be fixed in the next 1.9 release, you can run `composer self-update --snapshot` to try it now if you'd like to confirm the fix.
