### ISSUE TITLE
More dev friendly global installation

### ISSUE THREAD

**Issue by mikeSimonson** [composer/composer#3645]
One of the very common issue using composer to develop a cli utility is that the dev only takes into account the case where his tool is directly required into the composer.json of the project it's ussed for.

So in the main executable they only require something like that : 
```php
require __DIR__ . /../../vendor/autoload.php;
```

And they completely forget that the composer generated autoload file could be in another location if the tool is installed globally.

I am wondering if it would work and if it would be a good idea, if composer would automatically create a vendor/autoload.php symlink at the right place to make sure that the require works ?

**Comment by stof** [comment]
Your argument is flawed. A global installation is just a special project in ``$HOME/.composer`` which is requiring the package as a dependency. So the path to the autoload file is not different from the case where it is installed in your project (but it will indeed not know about the autoload of your own project when doing a global install, given that the global install is not tied to your project)

**Comment by stof** [comment]
however, your code snippet is indeed wrong, but this *also* forgets the case of the tool being installed as a project dependency

**Comment by mikeSimonson** [comment]
Well how do you explain this then : 

https://github.com/sensiolabs/insight/blob/master/bin/insight#L14-L18
```php
// installed via composer?
if (file_exists($a = __DIR__.'/../../../../../autoload.php')) {
    require_once $a;
} else {
    require_once __DIR__.'/../vendor/autoload.php';
}
```

**Comment by mikeSimonson** [comment]
@stof It's a real question. I get am wondering what I am missing.

**Comment by stof** [comment]
@mikeSimonson the first case is about being installed as a dependency (locally or globally does not matter) while the second case is about being the root package

**Comment by mikeSimonson** [comment]
Thanks.
So basically, having both always make sense right ?

**Comment by stof** [comment]
yes.
