### ISSUE TITLE
composer and elastic search

### ISSUE THREAD

**Issue by Blackhawk2165** [composer/composer#3650]
Hello,

I am trying to download and use composer to install the php client for elastic search and then run php scripts against elastic search. I have ubuntu server 14.04 set up on a mac mini. I have elastic search installed and started up. I also have a composer.json created. Here is what my composer.json looks like:
{
            "require": {
                       "elasticsearch/elasticsearch":  "1.3.*"
             }
}

When I run php composer.json install I get this:

Loding composer repositories with package information
Installing dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
 - elasticsearch/elasticsearch v1.3.2 requires ext-curl * -> the requested PHP extension curl is missing from your system.
- elasticsearch/elasticsearch v1.3.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
- elasticsearch/elasticsearch v1.3.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
- Installation request for elasticsearch/elasticsearch 1.3.* -> satisfiable by elastic search/elasticsearch[v1.3.0, v1.3.1, v1.3.2]

The strange part about all of this is that I have elasticsearch-1.3.2 downloaded and running. 

Let me know if anyone has any suggestions.

**Comment by stof** [comment]
Well, composer tells you that you are missing the curl extension. Make sure you enable the extension in your CLI php.ini too

**Comment by aakashnunna** [comment]
@stof   Thank's Alot....

**Comment by Blackhawk2165** [comment]
Okay I got that figured out and ran the composer but it isn't autoloading the classes I want. I am getting an error when I run my php script saying that Elasticsearch isn't a class. I put the file path to the autoload.php in my script with the require and I have the correct class in my script any suggestions?
