### ISSUE TITLE
Composer self update fails

### ISSUE THREAD

**Issue by HriBB** [composer/composer#3653]
This happens on several machines, looks like https://getcomposer.org/download/update/composer.phar is missing.

    bojan@linux:~/Downloads$ sudo composer self update
    Updating to version update.
        Downloading: 0%           

                                                                                                                         
      [Composer\Downloader\TransportException]                                                                           
      The "https://getcomposer.org/download/update/composer.phar" file could not be downloaded (HTTP/1.1 404 Not Found)  
                                                                                                                         

    self-update [-r|--rollback] [--clean-backups] [--no-progress] [version]

    bojan@linux:~/Downloads$ which composer
    /usr/local/bin/composer

    bojan@linux:~/Downloads$ composer diag
    Checking platform settings: FAIL

    The xdebug extension is loaded, this can slow down Composer a little.
    Disabling it when using Composer is recommended, but should not cause issues beyond slowness.
    Checking git settings: OK
    Checking http connectivity: OK
    Checking github.com oauth access: OK
    Checking disk free space: OK
    Checking composer version: OK

**Comment by Seldaek** [comment]
The command is `self-update` or `selfupdate`, if you type `self update` you request an update to th version `update` as it shows in the first line of output: `Updating to version update.`. Obviously it can't find that version so it fails.
