### ISSUE TITLE
Directory repository type and local stability

### ISSUE THREAD

**Issue by yguedidi** [composer/composer#3658]
First of all, thank you for composer!

But currently it's a pain to work localy on packages that depend on each other. You must run `composer update` each time a dependency of a package you work on is updated.

That's why I propose to have a repository type `directory`, with a `path` option. And they have only the `local` stability. If the directory exists locally, then composer create a symlink to that directory in vendors.

#### Exemple 1:
Here the repo must be defined in `~/.composer/config.json`, but this allow the contributor to put it where he want on his machine (usage between windows and linux)
```json
// ~/.composer/config.json
{
    "repositories": [
        {
            "type": "directory",
            "path": "/path/to/my/local/repo"
        }
    ]
}
```
```json
// /myrepo/composer.json
{
    "require": "myother/repo@local"
}
```
An error is throwed when the local repository is not available.

#### Exemple 2:
Here the required repo **must** be at the same level of the current one, in a `repo2` directory.

```json
// /myrepo/composer.json
{
    "repositories": [
        {
            "type": "directory",
            "path": "../repo2"
        }
    ],
    "require": "myother/repo@local"
}
```
---
I hope I'm understandable... Any thoughts?

**Comment by alcohol** [comment]
Composer already supports (local) directories as repository sources. These however are used as actual repositories.

Your issue is a common one and could easily be resolved by simply creating symlinks yourself for example.

See also related issues: #601, #1299, #2171, #3254 (and probably more)

**Comment by torches** [comment]
@yguedidi I agree, this is a pain, on one hand composer allows for rapid development with what it provides, but if you want to continue that rapid development, while working in a packaged module structure (keeping your in house modules split out) it becomes a cumbersome effort.
There should be an easy way to define the local path to your code without overriding the autoloader inside your front controller, or using symlinks.
I think a drop in file as suggested above that would allow you to specify the local static path of your module namespace makes perfect sense.
A good option for some is to have an "app" which has all of your modules included and their namespaces defined, but this is only practical for some projects.

+1 on this feature.

**Comment by jreinke** [comment]
Just gave a solution for this on another related issue: https://github.com/composer/composer/issues/1299#issuecomment-88861371

**Comment by Seldaek** [comment]
The path repo helps with this so closing, could be we have a better solution eventually but right now that's it https://getcomposer.org/doc/05-repositories.md#path

**Comment by mreschke** [comment]
Yes the https://getcomposer.org/doc/05-repositories.md#path solution works almost 100%...except for the version issues it has.  See https://github.com/composer/composer/issues/4635
