### ISSUE TITLE
Private git repository authentication fail

### ISSUE THREAD

**Issue by vpassama** [composer/composer#3660]
Hi,

It may not be an issue but I don't know how to solve this problem :

According to the documentation at https://getcomposer.org/doc/articles/http-basic-authentication.md :

"[...] There is a second way to provide these details and it is via interaction. If you don't provide the authentication credentials composer will prompt you upon connection to enter the username and password."

But when I use the command it says : 

```
./composer.phar update company/my-bundle
Failed to update http://my/repo/projectname, package information from this repository may be outdated (Failed to execute git remote set-url origin 'http://my/repo/projectname' && git remote update --prune origin

error: The requested URL returned error: 500 while accessing http://my/repo/projectname/info/refs
fatal: HTTP request failed
error: Could not fetch origin
)
```

In composer.json : 
```
"repositories": [
{   
    "type" : "git",
    "url" : "http://my/repo/projectname"
}]
"require": {
    "company/my-bundle": "dev-master"
}
```

When I write http://user:password@my/repo/projectname in the composer.json it works but I would like to use the interaction mode and get the user-ask/pass-ask from my repo.

```Composer version 1.0-dev (825b4b9c63a29c586d005de8dbbcfdfeb86bbf6f) 2015-01-20 16:39:06```

Thank you.

**Comment by alcohol** [comment]
It seems your server does not respond with a proper status code for the url that requires authentication when none is provided (500 is internal server error, whereas a 401 or 403 is expected).

**Comment by vpassama** [comment]
You are right, and this behavior is strange.

From one server I get 401 when using git clone http://git/repo/projectname (with empty user/pass) and from the actual server where I use composer if I do the same, I get interactive ask for user/pass and then if I let them empty I get 500 error.

From other server :
```
git clone  http://git/repo/projectname
Initialized empty Git repository in /home/user/projectname/.git/
error: The requested URL returned error: 401 while accessing  http://git/repo/projectname/info/refs

fatal: HTTP request failed
```

From the server using composer :
```
git clone  http://git/repo/projectname
Cloning into 'projectname'...
Username for ' http://git': 
Password for 'http://git': 
error: The requested URL returned error: 500 while accessing http://git/repo/projectname/info/refs
fatal: HTTP request failed
```

So I guess this is totally not an issue for composer ^^. Thank you for the answer.
