### ISSUE TITLE
Composer runs out of memory when trying to install Sylius on Windows

### ISSUE THREAD

**Issue by aguzmans** [composer/composer#3664]
Good day, This is the error I am getting:

PS D:\web\wamp\www> composer create-project -s dev sylius/sylius-standard shop
Installing sylius/sylius-standard (dev-master 2315b5ca19b7f2fcbdbf204e8a7964daec1c3953)
  - Installing sylius/sylius-standard (dev-master master)
    Cloning master

Created project in shop
Loading composer repositories with package information
Installing dependencies (including require-dev)

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 32 bytes) in phar://C:/ProgramData/Comp
oserSetup/bin/composer.phar/src/Composer/DependencyResolver/RuleSetGenerator.php on line 126

Call Stack:
    0.0035     399912   1. {main}() C:\ProgramData\ComposerSetup\bin\composer.phar:0
    0.0036     402816   2. require('phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin/composer') C:\ProgramData\
ComposerSetup\bin\composer.phar:25
    0.0272    3969672   3. Composer\Console\Application->run() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin
/composer:43
    0.0299    4341176   4. Symfony\Component\Console\Application->run() phar://C:/ProgramData/ComposerSetup/bin/composer
.phar/src/Composer/Console/Application.php:83
    0.0309    4485464   5. Composer\Console\Application->doRun() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/v
endor/symfony/console/Symfony/Component/Console/Application.php:126
    0.0320    4586104   6. Symfony\Component\Console\Application->doRun() phar://C:/ProgramData/ComposerSetup/bin/compos
er.phar/src/Composer/Console/Application.php:146
    0.0321    4586496   7. Symfony\Component\Console\Application->doRunCommand() phar://C:/ProgramData/ComposerSetup/bin
/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:195
    0.0322    4586920   8. Symfony\Component\Console\Command\Command->run() phar://C:/ProgramData/ComposerSetup/bin/comp
oser.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:874
    0.0326    4592384   9. Composer\Command\CreateProjectCommand->execute() phar://C:/ProgramData/ComposerSetup/bin/comp
oser.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
    0.0347    4788272  10. Composer\Command\CreateProjectCommand->installProject() phar://C:/ProgramData/ComposerSetup/b
in/composer.phar/src/Composer/Command/CreateProjectCommand.php:131
   19.2308   37076840  11. Composer\Installer->run() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/
Command/CreateProjectCommand.php:171
   19.2691    9676240  12. Composer\Installer->doInstall() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Com
poser/Installer.php:225
   20.8330   10503504  13. Composer\DependencyResolver\Solver->solve() phar://C:/ProgramData/ComposerSetup/bin/composer.
phar/src/Composer/Installer.php:503
   20.8331   10511448  14. Composer\DependencyResolver\RuleSetGenerator->getRulesFor() phar://C:/ProgramData/ComposerSet
up/bin/composer.phar/src/Composer/DependencyResolver/Solver.php:171
   27.1101  135663792  15. Composer\DependencyResolver\RuleSetGenerator->addRulesForJobs() phar://C:/ProgramData/Compose
rSetup/bin/composer.phar/src/Composer/DependencyResolver/RuleSetGenerator.php:333
   27.1149  135856456  16. Composer\DependencyResolver\RuleSetGenerator->addRulesForPackage() phar://C:/ProgramData/Comp
oserSetup/bin/composer.phar/src/Composer/DependencyResolver/RuleSetGenerator.php:293
   47.9578  536549896  17. Composer\DependencyResolver\RuleSetGenerator->createConflictRule() phar://C:/ProgramData/Comp
oserSetup/bin/composer.phar/src/Composer/DependencyResolver/RuleSetGenerator.php:246

PS D:\web\wamp\www>

**Comment by jrobeson** [comment]
change the issue title (via the "Edit" Button) to say something like: "Composer runs out of memory when trying to install Sylius on Windows", thus the problem will be more clear when people read over the issues list.

**Comment by RobQuistNL** [comment]
Did you check https://github.com/composer/composer/issues?q=is%3Aissue+is%3Aopen+sort%3Acomments-desc ?

It shows these issues on top;
https://github.com/composer/composer/issues/1898
https://github.com/composer/composer/issues/2704

**Comment by jakoch** [comment]
Ok, i tired to reproduce this on Windows
`composer create-project sylius/sylius-standard shop --stability dev --prefer-dist --profile -vvv`
The package doesn't resolve - with and without stability dev.
`[726.0MB/20.25s] Your requirements could not be resolved to an installable set of packages.`
`[197.1MB/21.15s] Memory usage: 197.1MB (peak: 726.3MB), time: 21.15s`

The mem peak is around 726MB - if you set a 1GB memory limit, you are fine.

**Comment by jrobeson** [comment]
composer alpha 10 should be using 1GB by default as per: https://github.com/composer/composer/commit/8e6f62e76923c0936cbde64e359cabca1bfa23bb

**Comment by aguzmans** [comment]
With symfony projects I found out that even 1 GB is not enough most of the time. Last time I created a project I had to change my php.ini for it to work if bad don't remember?  Has the memory size been changed to what ever the php.ini has Or was it always like all along?

**Comment by RobQuistNL** [comment]
@Seldaek I believe you've closed this as its a duplicate of the issues #1898 and #2704 ? Or does this have another reason?

**Comment by Seldaek** [comment]
Yeah sorry but it just doesn't make much sense to have such issues opened. We know that memory is an issue for some large projects/dependency sets, but it's not something we can directly fix right now, and yes there are many other related issues still opened.
