### ISSUE TITLE
The windows installer creates a wrong composer.bat

### ISSUE THREAD

**Issue by patrickse** [composer/composer#3666]
Hi,

I´ve just installed composer with the windows installer and it actually created a composer.bat inside my programs folder. This batch had a problem with a missing line feed.

It looked like this
```bat
@ECHO OFFphp "%~dp0composer.phar" %*
```

So if I try to run it, it simply pops up a new window.

I´ve corrected it to this
```bat
@ECHO OFF
php "%~dp0composer.phar" %*
```
and now it works.

Patrick

**Comment by RobQuistNL** [comment]
This is probably just a linux line ending while you're using a windows line ending IDE.

**Comment by patrickse** [comment]
I think so... It looked like it was causing a problem on my windows machine. My main problem was a faulty php installation ;)... so we can forgot about this one... 

Thanks for your help..
