### ISSUE TITLE
[RFC] use require-dev as additional constraints when --no-dev

### ISSUE THREAD

**Issue by nicolas-grekas** [composer/composer#3667]
Obviously, packages are tested with `require-dev` deps loaded. That means that installing with `--no-dev` is never proved to be working (because never tested).

What about using `require-dev` as optional constraints, with this logic:
in --no-dev mode, if a dep D is to be installed because of the require of **an other** package and that dep D is not in `require` but in `require-dev`, then version constraints in `require-dev` are applied.

Thinking about it, I'd always enable this mode. And you?

**Comment by nicolas-grekas** [comment]
An other way to formulate my point would be: generate a complementary conflict rule for each require-dev.

**Comment by stof** [comment]
-1 for generating such conflict rules automatically. It might introduce weird dependency resolution conflicts for something you don't actually need (dependencies on behat, phpunit or phpspec for instance, used by testsuites of your dependencies), and will make the dependency resolution more complex for the solver (thus slower)

**Comment by GromNaN** [comment]
Since you should lock your dependencies with "--dev" packages, installing only "--no-dev" packages will not install different versions.

**Comment by Seldaek** [comment]
+1 for what @GromNaN says. You can install **from composer.lock** with --no-dev and you'll get exactly the same deps as if in --dev but without the require-dev ones. If you install prod without lock file you're gonna run into issues eventually regardless of this.
