### ISSUE TITLE
cannot install (unexpected T_SL in - on line 820) latest

### ISSUE THREAD

**Issue by vincentkersten** [composer/composer#3668]
Hello composers,
```
 php -r "readfile('https://getcomposer.org/installer');" | php

Parse error: syntax error, unexpected T_SL in - on line 820

```

Anyone any idea? According to http://www.phpsadness.com/sad/7 a known issue, but i am unable to resolve it. 

Running:
Debian 6

PHP 5.2.14 (cli) (built: Nov  3 2010 14:54:46) 
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.2.0, Copyright (c) 1998-2010 Zend Technologies

**Comment by xabbuh** [comment]
Do you really use PHP 5.2? I'm afraid installing Composer will not the only impossible thing to do with this version.

**Comment by vincentkersten** [comment]
Did not really have a look at the minimum version, was in a rush to upgrade my 'drush' for drupal. Sounds like there is some more work ahead then :(
Ah, yes it is there: Composer requires PHP 5.3.2+ to run.
Sorry for the bother, i'll close it then, and thanks for the quick reply!
