### ISSUE TITLE
installer-path not honored for subpackages

### ISSUE THREAD

**Issue by WanWizard** [composer/composer#3670]
Our applications are modularized to be able to maximize the re-use of components. We (want to) use composer to manage the complete dependency tree of our applications, but we've bumped into a few issues.

First is that if a sub-package (or one deeper in the tree) defines a custom install-path, that path is ignored. If you run `composer update` on the sub-package itself, everything installs fine, so the json is fine.

Second is that composer doesn't seem to be able to deal with installing the same package multiple times. It seems that no-one has thought about packages that contain more than only PHP classes (and even for those you might have a need for multiple installations, for example one component requiring version A, and one requiring version B). We have separate packages with supporting assets (which can be anything, not only PHP source), that are used by multiple application components (= sub-packages), and use the install-path to have them installed in the correct location. I can't see how I can get this to work.

**Comment by alcohol** [comment]
Trying to turn composer into your silver bullet solution for everything will not work.

Composer serves a somewhat specific purpose (which already is quite broad) and it serves it well. For everything else, you're on your own. Be creative, don't constrain yourself to using just one tool. If building a house only took a hammer, we'd all be building houses ourselves.

**Comment by WanWizard** [comment]
This is a pretty easy answer, isn't it?

Composer supports "unlimited" nested packages, but a lot of the features simply don't work in sub-packages. In your analogy, the toolbox allows for building a multi-storey house, but most the tools, including your hammer, only work on the ground floor. 

Sorry, wrong answer.

**Comment by alcohol** [comment]
Well then if you want to stick to the analogy, does it make sense for all
your floors to come with a kitchen installed? Or a front door?

Anyway, good luck with that, and your attitude.

**Comment by WanWizard** [comment]
Your attitude you mean?

I report a bug, or at least unexpected behavior. Then I expect a serious answer, and not your "you're on your own, bro" response.

If "install-paths" are not supposed to work in sub-packages, amend the docs and make that configuration item "root-only". If they are supposed to work, I tell you now it doesn't, so it has to be fixed.

What is so difficult about this?

**Comment by alcohol** [comment]
They work.

```
13:56:52 /tmp/foo $ cat ../bar/composer.json
{
    "name": "test/test",
    "require": { "alcohol/iso3166": "@stable" },
    "target-dir": "foo/bar/baz/works",
    "minimum-stability": "stable"
}
13:56:58 /tmp/foo $ composer install
Loading composer repositories with package information                                                                                                                                                                   Installing dependencies (including require-dev)
  - Installing alcohol/iso3166 (dev-master 42ac9b6)
    Cloning 42ac9b606f208f9470307cb7c9365f78fc233eb1

  - Installing test/test (dev-master 77868eb)
    Cloning 77868eb94de96a3037808a555898cbbf47ac3267

Writing lock file
Generating autoload files
13:57:05 /tmp/foo $ tree
.
├── composer.json
├── composer.lock
└── vendor
    ├── alcohol
    │   └── iso3166
    │       ├── composer.json
    │       ├── composer.lock
    │       ├── LICENSE
    │       ├── phpunit.xml.dist
    │       ├── README.md
    │       ├── source
    │       │   └── ISO3166.php
    │       └── tests
    │           └── ISO3166Test.php
    ├── autoload.php
    ├── composer
    │   ├── autoload_classmap.php
    │   ├── autoload_namespaces.php
    │   ├── autoload_psr4.php
    │   ├── autoload_real.php
    │   ├── ClassLoader.php
    │   └── installed.json
    └── test
        └── test
            └── foo
                └── bar
                    └── baz
                        └── works
                            └── composer.json

12 directories, 17 files
```

So unless you can give me something to reproduce your 'not working' scenario with, we can assume you just made a mistake somewhere.

As for why composer does not support installing the same package multiple times, that's because it is a dependency manager. Much like the package managers of linux distributions don't let you install the same version of nginx or git or any other package multiple times. It simply does not make sense to do that.

**Comment by WanWizard** [comment]
That is not reflecting the issue I reported.

I was taking about "installer-paths", which are in the extra section, and which are relative to the root package installation root (and not the direct parent installation root, what my original problem is).

You use "target-dir" in your example, which is a path relative to the current package root, which is not the same.

It is not only an issue with "installer-paths" btw, the same problem happens when you use custom installers (like we do in the example below). The path defined in the custom installer (in case of a static mapping), or returned by getInstallPath() is also relative to the root package, not to the package that defines the dependency. 

As an example: I have a root package (original is much larger than this):
```
{
    "name": "project/name",
    "repositories": [
        {
            "type": "composer",
            "url": "http://packages.our.domain"
        }
    },
    "require": {
        "php": ">=5.5",
        "composer/installers": "~1.0",
        "applications/app-a": "dev-master",
        "applications/app-b": "dev-master",
        "applications/app-c": "dev-master"
    }
```

which requires application packages (which have a custom installer to install them in "applications" instead of in the vendor folder):
````
{
    "name": "applications/app-a",
    "type": "company-application",
    "license": "proprietary",
    "repositories": [
        {
            "type": "composer",
            "url": "http://packages.our.domain"
        }
    ],
    "require": {
        "php": ">=5.5",
        "composer/installers": "~1.0",
        "company/application-installer": "dev-master",
        "subapplication/subapp-a": "dev-master"
    },
    "extra": {
        "installer-paths": {
            "subapps/{$name}": ["subapplication/subapp-a"]
        }
    }
}
````

This setup completely ignores this "installer-path", composer will install "subapplication/subapp-a" in the global vendor folder.

Next thing we tried was a custom installer. We removed the extra section above, and defined the subapps like so:
````
{
    "name": "subapplication/subapp-a",
    "type": "company-subapplication",
    "license": "proprietary",
    "repositories": [
        {
            "type": "composer",
            "url": "http://packages.our.domain"
        }
    ],
    "require": {
        "php": ">=5.5",
        "composer/installers": "~1.0",
        "company/subapplication-installer": "dev-master"
    }
}
````
where this custom installers installPath() method would return "subapps/subapp-a".

This will install the subapp in the "subapps" folder of the root package, and not in the application package, which for me is a bug in the solver.

Resume:

Expected tree:
````
.
├── composer.json
└── applications
    ├── app-a
    └── subapps
        └── subapp-a
````

Actual result in case of using the extra installer path:
````
.
├── composer.json
├── applications
│  ├── app-a
└── vendor
     └── subapp-a
````

Actual result in case of using a custom installer:
````
.
├── composer.json
├── applications
│  ├── app-a
└── subapps
     └── subapp-a
````

**Comment by alcohol** [comment]
You left out the most important part, your custom installer. 

- Can you share with us the `composer.json` belonging to your installer?
- Did you install your installer as a composer plugin prior to trying to install any of the above scenarios described?

**Comment by WanWizard** [comment]
Those are two completely different scenario's, they are and were not mixed. We tried to switch to a custom installer after we had noticed the installer-path didn't work. When we switched, we removed the "extra" section from the json. So absolutely no interference between the two options.

the `compser.json` for the application installer (the others are identical):
````
{
	"name": "company/application-installer",
	"type": "composer-installer",
	"license": "propriatary",
	"require": {
		"php": ">=5.5"
	},
	"autoload": {
		"psr-4": { "Company\\ApplicationInstaller\\": "src/" }
	},
    "extra": {
        "class": "Company\\ApplicationInstaller\\Installer"
    }
}
````
This is as standard as can be, and identical to all other installers I've created for Composer.

I tried some clever bits in the installer, but since the Composer API doesn't expose the package hierarchie (it flattens it), and doesn't determine paths until installation, there is no way your custom installPath() method could determine the correct installation path based on it's environment.

This problem also means you can not develop and test the different apps in isolation, since the (absolute) install paths  of the subapps are different depending on what the root package is.

I agree with your final conclusion, if only because honouring a custom path at the sub-package level implies the posibility of installing the same package multiple times, and since packages seem to have to be unique within composer, supporting that scenario would mean an arcchitecture rewrite.

Another issue that this problem brough to light is the fact that because there is a dependency from app to subapp, composer wants to install subapp first. Which is impossible, since it needs to be installed inside the app, which isn't installed yet at that point.

We might have to switch for something more mature and versatile, like RPM.

**Comment by Seldaek** [comment]
`installer-path` is not a standard composer feature BTW, it's something from the composer/installers custom installer, and it only works for packages that get installed by it, so they need a custom type and they need to require the installer.. Then they do work, AFAIK.
