### ISSUE TITLE
Feature Request: list scripts

### ISSUE THREAD

**Issue by Sequoia** [composer/composer#3671]
I wish there were some way to list available scripts (as defined in `scripts` in composer.json).  Substack wrote a [nice article](http://substack.net/task_automation_with_npm_run) about using scripts in npm configs; I've been trying to carry it over to Composer for basic tasks that don't require a `.php` file/class definition.

`composer run-script --list`
`composer list-scripts`

**Comment by alcohol** [comment]
```
/srv/git/github/composer (feature/list-scripts*) $ bin/composer run-script --list
scripts:
  test
```

Would that suffice?

**Comment by alcohol** [comment]
If you run `composer` in a directory that contains a composer.json with scripts, you also have the following output available:

```
composer | grep 'as defined in composer.json'
 checkstyle       Run the checkstyle script as defined in composer.json.
 clean            Run the clean script as defined in composer.json.
 test             Run the test script as defined in composer.json.
```

**Comment by Sequoia** [comment]
Thanks!! This makes much more viable the possibility of @substack style lightweight build scripting with composer. yay! :smile_cat:

**Comment by alcohol** [comment]
Not sure how it makes it more viable, but enjoy (assuming it gets merged).

**Comment by Sequoia** [comment]
You're probably right... :smile:  My thinking was that by significantly easing the *discovery* of such scripts, it removes a barrier to using the tool.  I can package & in docs write "`composer run-script test` to test, `composer run-script build` to build, see `composer run-script --list` to see other tasks."

I imagine a world where one clones a composer package/`create-projects` & can quickly discover the built in tasks without learning/building a 3rd tool like e.g. `artisan`.  Basically in composer run-script vs. artisan I see npm scripts vs. gulp/grunt/etc.: in many cases the tool-we-already-have-installed can take care of a requirement with a minimum of overhead. I see this assuming it's merged as promoting that workflow.  But you're right it's just an idea so far... :) thanks!

**Comment by alcohol** [comment]
Actually, to run most of such scripts, you don't even need to use `run-script`. You could just do `composer test`.

**Comment by Sequoia** [comment]
👏👏👏😁

**Comment by alcohol** [comment]
This will also give you somewhat odd results (if you have them) such as:
```
$ composer run-script --list
scripts:
  post-install-cmd
  post-update-cmd
```
