### ISSUE TITLE
dev-master is not able to match dev-master if the commit hash is tagged

### ISSUE THREAD

**Issue by jails** [composer/composer#3673]
I'm no quite sure if it's a bug or a missunderstanding but the behavior was weird enough to let me thing that's probably a bug.

Last year I created a [test framework](https://github.com/crysalead/kahlan) and I splitted all dependencies into some dedicated repo. I used "dev-master" everywhere and everything worked fine.

Today I wanted to tag one repository. So I went on the [first one](https://github.com/crysalead/set) and I tagged it:

```
git tag 1.0.0
git push origin --tag
```
After that I tried to run `composer update` and I had the following error:

```
Problem 1
    - Can only install one of: crysalead/set[dev-master, 1.0.0.0].
    - Can only install one of: crysalead/set[dev-master, 1.0.0].
    - crysalead/kahlan dev-master requires crysalead/set dev-master -> satisfiable by crysalead/set[dev-master].
    - Installation request for crysalead/kahlan dev-master -> satisfiable by crysalead/kahlan[dev-master].
    - Installation request for crysalead/set 1.0.0.0 -> satisfiable by crysalead/set[1.0.0.0].
```
I didn't understand why dev-master doesn't match 1.0.0 since I specifically added in the composer.json the following branch alias:
```json
    "extra": {
        "branch-alias": {
            "dev-master": "1.0.x-dev"
        }
    }
```
However after poking around during a couple of hours I just added an extra commit in the repository and runned  `composer update` again and it worked 8-| ...

Step to reproduce:
```
git clone git@github.com:crysalead/set.git
cd set
composer update #<- it doesn't work
touch junkfile
git add junkfile
git commit -m "extra commit"
composer update #<- it works !!!
```
Did I missed something somwhere ?

Thanks

**Comment by stof** [comment]
Well, if your library request the 1.0.0 version as an exact match, it is expected that ``1.0.x-dev`` does not match it. You should depend on ``1.0.*`` or ``~1.0``

**Comment by jails** [comment]
I'm not sure to understand because I didn't changed any composer.json and all dependencies rely on `dev-master`. But as soon as I tag my repository (i.e. with `git tag 1.0.0`), composer fail to resolve the `dev-master` depencendy required by the test framework library.

Ps: Also tried to set the `branch-alias` to `~1.0` but it produces the following error on packagist "extra.branch-alias.dev-master : the target branch (~1.0) must end in -dev".

**Comment by alcohol** [comment]
I think this is because when you checkout `crysalead/set` you get `1.0.0` technically (same commit reference). Since by default it tries to include the dev dependencies when running composer install or update, you get a dependency chain of `set (1.0.0)` -> `kahlan (dev-master)` -> `set (dev-master)`. They cannot be installed side by side. When creating a new commit it will no longer reference the `1.0.0` tag so you are back to matching `dev-master`.

I can't prove this is the case since I am not intimately familiar with how the dependency chain is resolved, but I suspect this is the case.

**Comment by jails** [comment]
Thanks guys, so yeah seems to be a bug since a `dev-master` requirement should be able to be resolved as long as the installed package match the `dev-master` hash, not matter the hash has a tag associated or not.

Tried to poke around the solver without much success so if somebody know how this part of the core work, I would really appreciate it if he could shed some light on it, thanks !

**Comment by alcohol** [comment]
No you don't seem to understand. The problem is that your current `set` checkout is version `1.0.0`. It has a dependency on `kahlan`. But `kahlan` has a dependency on `set` with version `dev-master`. It tries to install `dev-master`, but it cannot install that as a `1.0.0` version is already present (your checkout). It's not a bug, it's a result from the circular dependency (which is a terrible design flaw in your application).

**Comment by jails** [comment]
Yeah I don't understand... composer don't need to install another `dev-master` since the installed `1.0.0` **is** the `dev-master`. I don't see any flaw here or please explain me how to start tagging a recursive dependency if  `dev-master` is not able to match  `dev-master` as soon as a tag is associated to the `dev-master` hash.

**Comment by alcohol** [comment]
Eh I don't know how else to explain it. I thought I made it pretty clear.

Anyway, get rid of your circular dependency. It doesn't make any sense for `set` to depend on `kahlan` when `kahlan` depends on `set`.

**Comment by jails** [comment]
To me it makes sense since `set` is a library, `kahlan` a testing framwork which use `set` and composer a dependency manager but anyway thanks for your time ;-)

**Comment by alcohol** [comment]
Testing a library using a testing framework that uses that library makes sense? lol..

**Comment by jails** [comment]
Sure, in compilers land it's called [Bootstrapping](http://en.wikipedia.org/wiki/Bootstrapping_%28compilers%29). And without this bug it would work great !

**Comment by stof** [comment]
@jails this use case is the reason why Composer supports the ``COMPOSER_ROOT_VERSION`` env variable to force the root version instead of relying on guessing.

**Comment by jails** [comment]
Awesome !!! Thanks a bunch @stof, exactly what I looked for !
