### ISSUE TITLE
Foreach problem

### ISSUE THREAD

**Issue by wojtas** [composer/composer#3679]
After updating to the latest version I have a problem while issuing composer update. But, to be honest, it happened on some of my developers' machines even two months ago after issuing self-update; we've just reverted the Composer version back then, because we had no time to dig into this and work needed to be done.

But now I updated again and in the dev-master version, the problem still occurs:

```
www-data@mordor:/var/satis/auto_refresh_scripts$ ./refresh_misc.sh



  [ErrorException]
  Invalid argument supplied for foreach()



build [--no-html-output] [--skip-errors] [file] [output-dir] [packages1] ... [packagesN]
```

(this refresh_misc.sh script is just issuing a satis command, which in turn issues the composer update command; I get the same error after every composer update with this version, on any project. So it's not a faulty script that's the case.).

I've tracked down the problem by running composer with verbose logging enabled, and the reason is line no 130 in UnixPipes.php in the Symfony Process Component - have a look at it here https://github.com/symfony/Process/blob/e42521d38b122a2ad8a0efb4f9ccaad9dd04b90b/Pipes/UnixPipes.php#L130 .

For some reason, it clears the array $r , which results in the foreach https://github.com/symfony/Process/blob/e42521d38b122a2ad8a0efb4f9ccaad9dd04b90b/Pipes/UnixPipes.php#L145 being iterating over an empty array.

I don't know pretty much anything about the stream_select function in PHP, and I don't know the Process component either to an extent enough that I could fix that myself. Of course I've debugged the output and I know that this function filters available streams based on some criteria - so if nobody will know the case, I'll try to dig deeper into that.

Temporarily, I've commented out lines 130 - 138 in this file and Composer begun working again. Seems not to make any observable difference.

I don't know if it's a Composer-related problem or a Process component-related problem - so I'm submitting it here. But if you think it belongs more to the Process component, tell me and I'll create an issue in Symfony/Symfony also. Still I think it should stay here in composer issues, in case anyone googles a similar problem, which at first seems to be a Composer-related one.

**Comment by stof** [comment]
Please run the command in verbose mode to see the stack trace of the exception

**Comment by stof** [comment]
Thus, iterating over an empty array is perfectly valid in PHP, so your diagnostic does not look right

**Comment by wojtas** [comment]
Yeah, right, empty array is not a problem in PHP. I've made a mistake - it's NULL in this case. 

```



  [ErrorException]
  Invalid argument supplied for foreach()



Exception trace:
 () at /var/satis/vendor/symfony/process/Symfony/Component/Process/Pipes/UnixPipes.php:174
 Composer\Util\ErrorHandler::handle() at /var/satis/vendor/symfony/process/Symfony/Component/Process/Pipes/UnixPipes.php:174
 Symfony\Component\Process\Pipes\UnixPipes->readAndWrite() at /var/satis/vendor/symfony/process/Symfony/Component/Process/Process.php:1381
 Symfony\Component\Process\Process->readPipes() at /var/satis/vendor/symfony/process/Symfony/Component/Process/Process.php:1323
 Symfony\Component\Process\Process->updateStatus() at /var/satis/vendor/symfony/process/Symfony/Component/Process/Process.php:302
 Symfony\Component\Process\Process->start() at /var/satis/vendor/symfony/process/Symfony/Component/Process/Process.php:208
 Symfony\Component\Process\Process->run() at /var/satis/vendor/composer/composer/src/Composer/Util/ProcessExecutor.php:62
 Composer\Util\ProcessExecutor->execute() at /var/satis/vendor/composer/composer/src/Composer/Package/Loader/RootPackageLoader.php:197
 Composer\Package\Loader\RootPackageLoader->guessGitVersion() at /var/satis/vendor/composer/composer/src/Composer/Package/Loader/RootPackageLoader.php:178
 Composer\Package\Loader\RootPackageLoader->guessVersion() at /var/satis/vendor/composer/composer/src/Composer/Package/Loader/RootPackageLoader.php:58
 Composer\Package\Loader\RootPackageLoader->load() at /var/satis/vendor/composer/composer/src/Composer/Factory.php:270
 Composer\Factory->createComposer() at /var/satis/vendor/composer/composer/src/Composer/Factory.php:488
 Composer\Factory::create() at /var/satis/src/Composer/Satis/Console/Application.php:62
 Composer\Satis\Console\Application->getComposer() at /var/satis/src/Composer/Satis/Command/BuildCommand.php:151
 Composer\Satis\Command\BuildCommand->execute() at /var/satis/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
 Symfony\Component\Console\Command\Command->run() at /var/satis/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /var/satis/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /var/satis/src/Composer/Satis/Console/Application.php:52
 Composer\Satis\Console\Application->doRun() at /var/satis/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /var/satis/bin/satis:9
```

**Comment by wojtas** [comment]
By placing the following code after this stream_select function has been invoked:

```
var_dump(gettype($r));die();
```

I got:

```
www-data@mordor:/var/satis/auto_refresh_scripts$ ./refresh_misc.sh
string(4) "NULL"
```

**Comment by alcohol** [comment]
I suggest you clone the [Process](/symfony/process) component, recreate the issue with a test, and then fix it (and submit a PR).
