### ISSUE TITLE
make composer use a local packages cache to resolve dependencies

### ISSUE THREAD

**Issue by kevindperezm** [composer/composer#3680]
I just ran `composer update -vvv` and noticed that it downloads each `composer.json` file from each package to resolve dependencies before downloading any real code, which is really slow on my Internet connection. What about having a local packages cache (like the dpkg one, for example) where to check for dependencies resolution and only touch the remote server when downloading packages?

**Comment by RQuadling** [comment]
Your cache will be stale fairly quickly as packages move forward.

**Comment by alcohol** [comment]
Composer does cache a lot of those composer.json files. So I sincerely doubt that it downloaded each and every single one of them. How about providing us some actual output from the command you ran?

**Comment by kevindperezm** [comment]
@alcohol I ran `composer update -vvv --profile` three times in a row. The first time it downloaded the majority of composer.json files with a bunch of them being loaded from cache. The second time it loaded practically all the files from the cache. Same with the third time.

First time output: https://gist.github.com/kevindperezm/2de5a8262dafff6482a7
Second time output: https://gist.github.com/kevindperezm/a4b08f9bbc457cc32e36
Third time output (this one with `--profile`): https://gist.github.com/kevindperezm/1ca6260446da9406e10a

I've been running `composer update` in my project a lot of times, but composer doesn't always behave like the third time. Maybe because of a cache-expiration mechanism?

**Comment by Seldaek** [comment]
@kevindperezm it has to redownload some jsons if the metadata for package X or Y has changed, that's normal behavior and there isn't a whole lot we can do it about it..
