### ISSUE TITLE
Composer install with lock file and existing vendor/workingcopy doesnt reset source

### ISSUE THREAD

**Issue by ro0NL** [composer/composer#3682]
Hi,

I'm not sure this is expected behavior, so I hope you can clarify on this.

We have a composer.lock file with a specific vendor set on a specific commit. Whenever I locally change the vendor working copy via `git commit` (ie 1 commit up as to the lock file) or `git reset` (ie 1 commit down as to the lock file) and then run `composer install` my workingcopy is still 1 commit up or down, ie the workingcopy is not reset to the commit in the lock file.

Is this expected behavior? If so.. can we force an alternative behaviour like so `composer install --force-reset`?

Thanks,

**Comment by alcohol** [comment]
I suspect the solution for #3689 will solve this as well (implement more strict checking for changes in vendor packages).

**Comment by ro0NL** [comment]
Assuming it's default behaviour.

It's indeed development workflow related, however  a simple `--reset` option on the `install` command would satisfy our needs.

Our workflow is as follow;
```
composer install
# develop/commit
# update build
cp composer.* build/
cp -r vendor build/
cd build && composer install # this install can be problematic
```

We re-use an existing vendor directory for building, however the 2nd `composer install` doesnt adhere the lock file. When building we always want the vendors to be the same as when you run a fresh install.

**Comment by alcohol** [comment]
Then why are you copying the vendor directory at all?

**Comment by alcohol** [comment]
`install` has some trouble with committed changes in vendor packages. If you want install to behave as expected in this situation, don't copy your `vendor/` directory. Just start clean.
