### ISSUE TITLE
Support autoloading functions, constants, and typedefs on HHVM

### ISSUE THREAD

**Issue by fredemmott** [composer/composer#3683]
This is supported via the HH\autoload_set_paths() function, described here: https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/hh/ext_hh.php#L18-40

**Comment by fredemmott** [comment]
Example usage: https://github.com/hhvm/asio-utilities;  this would also require it to recognize generics

**Comment by Seldaek** [comment]
Not sure we really want to add this right now, it's very HHVM specific and might clash with future PHP functionality (one can hope :P). Closing for now.

**Comment by fredemmott** [comment]
In case anyone else is interested, I have a composer extension that creates a vendor/hh_autoload.php file: https://packagist.org/packages/fredemmott/hhvm-autoload
