### ISSUE TITLE
Loading private subversion repository with credentials with Vagrant on Windows fails

### ISSUE THREAD

**Issue by HriBB** [composer/composer#3687]
On linux it works without problems. I think the reason might be in having code in vagrant shared drive. Not really sure, but it does not work on windows machines ...

    vagrant@ifdaq:/var/www/web/protected$ sudo composer update
    Loading composer repositories with package information Updating dependencies (including require-dev) 
     - Installing fmd/yii (dev-trunk)
     Checking out //generator/@57

     
     [RuntimeException] 
     Package could not be downloaded, svn: E200030: sqlite[S10]: disk I/O error 
     svn: E200030: Additional errors: 
     svn: E200030: sqlite[S10]: disk I/O error 
     

    update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]

    vagrant@ifdaq:/var/www/web/protected$

**Comment by alcohol** [comment]
This is not a composer issue.

**Comment by Seldaek** [comment]
According to http://stackoverflow.com/questions/18782941/tortoisesvn-checkout-sqlite-disk-i-o-error-s10 it seems like maybe a problem with shared partitions, or maybe because you're in vagrant?
