### ISSUE TITLE
Fatal error after creating project and running command specified in post-create-project-cmd

### ISSUE THREAD

**Issue by emodric** [composer/composer#3690]
In my `composer.json`, I have a custom script defined in `post-create-project-cmd` array.

When creating the project from such repo, everything works fine until the post create project script needs to run. I get the following fatal error:

```
Do you want to remove the existing VCS (.git, .svn..) history? [Y,n]? y
PHP Fatal error:  Call to undefined method Symfony\Component\Console\Event\ConsoleCommandEvent::commandShouldRun() in phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php on line 880
eddie@abyss: ~/www $
```

Unfortunatelly, I can't show you the `composer.json` file or the repo as they're private.

EDIT:

This happens on the latest Composer version

```
Composer version 1.0-dev (269767366623bc7ff74cf048d00c96307c65bf34) 2015-01-28 15:17:56
```

**Comment by alcohol** [comment]
Does your project also contain an instance of Symfony Console? And if so, what version?

**Comment by emodric** [comment]
Hi @alcohol

Yes it does, it's a website built with [eZ Publish](https://github.com/ezsystems/ezpublish-community) and Symfony full stack framework.

The console version is 2.5.9 and, unfortunately, I can't upgrade it to 2.6.x as the 2014.11 version of eZ Publish I'm using is not compatible with Symfony 2.6.x

**Comment by alcohol** [comment]
Well, it seems that the method called did not exist yet in 2.5 but it does exist in 2.6.
https://github.com/symfony/Console/compare/2.5...2.6#diff-9
Not sure why this would confuse Composer though...

Where did you install the composer binary? How did you run it? Can you share with us the exact steps you took to run into this error?

**Comment by emodric** [comment]
I have Composer installed in `/usr/local/bin/composer`.

And I'm running it like this:

```
$ composer create-project netgen/demo-site --repository-url=http://my.custom.repo.com --no-dev demosite
```

After creating the project, installing vendors and specifying default parameters, I get the error from the issue description.

**Comment by alcohol** [comment]
I'm under the impression that for some reason, Composer is trying to use a Console component from your project install, rather than from within the Phar. But that doesn't really make sense to me. It's impossible for me to debug this problem properly though since your project is private.

**Comment by alcohol** [comment]
Are you sure that your ez publish does not support Console 2.6? Cause it is backwards compatible with 2.5. And the current ez publish repo has a require for symfony/symfony 2.6 even. So you must be running an older version then?

If it really does have a hard require on 2.5, then I suggest you simply alias 2.6 like so:
```
"require": {
  "symfony/console": "~2.6 as 2.5"
}
```

**Comment by emodric** [comment]
It's compatible in master, but not in latest officially released version which is 2014.11.

I get the following error when trying to alias `symfony/console`:

`invalid version constraint (Could not parse version constraint ~2.6 as 2.5: Invalid version string "~2.6" in "~2.6 as 2.5", the alias source must be an exact version, if it is a branch name you should prefix it with dev-)`

**Comment by alcohol** [comment]
Ok, seriously, I don't mind being helpful, but this error you could have solved yourself within a minute. Navigate to github, check what the latest 2.6 tag is (that would be `2.6.3`), and use that instead of `~2.6`. Voila.

**Comment by emodric** [comment]
Ok, sorry. I have other stuff and projects on my mind, it didn't occur to me.

Anyways... Aliasing Symfony Console with 2.6.3 solves the problem.

**Comment by alcohol** [comment]
Ok, that is both good and bad news. Good news, your issue is solved. Bad news, no idea why it is autoloading the wrong package.

**Comment by emodric** [comment]
I'll try to reproduce the error in an example eZ Publish repo and will let you know.

**Comment by Seldaek** [comment]
If it loads the eZ console  package it might be because of a pre/post-something script in the composer.json that loads one class from there before composer needs it?

**Comment by Seldaek** [comment]
We'd need to debug this further to see when which class is loaded and from where, it should be easy to trace that in the autolaoder but I don't really have time to investigate this now.

**Comment by emodric** [comment]
> If it loads the eZ console package it might be because of a pre/post-something script in the composer.json that loads one class from there before composer needs it?

That might be the case. I'll investigate client's code further.
