### ISSUE TITLE
Strange non–verbose fail on Win PHP 5.3 console

### ISSUE THREAD

**Issue by Rarst** [composer/composer#3692]
I have Composer working perfectly on my local computer with PHP 5.6. I needed to check an install issue in a project with PHP 5.3 environment and it gives cryptic corrupt output.

```bash
C:\server>c:\UniServerZ\core\php56\php.exe -v
PHP 5.6.0 (cli) (built: Aug 27 2014 11:54:39)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies

C:\server>c:\UniServerZ\core\php56\php.exe c:\ProgramData\ComposerSetup\bin\composer.phar --version
Composer version 1.0-dev (71f83599bb66d9ae38eada9e230e1207a74a2f11) 2015-01-29 12:44:11
```
But:
```bash
C:\server>c:\UniServerZ\core\php53\php.exe -v
PHP 5.3.29 (cli) (built: Aug 21 2014 06:25:58)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2014 Zend Technologies

C:\server>c:\UniServerZ\core\php53\php.exe c:\ProgramData\ComposerSetup\bin\composer.phar --version
?? ◄??
```
Git checkout of Composer master seems to work off the same PHP binary:

```bash
C:\server\composer>c:\UniServerZ\core\php53\php.exe bin/composer --version
Composer version @package_branch_alias_version@ (@package_version@) @release_date@
```

**Comment by Seldaek** [comment]
Works for me with 5.3.28 and the phar.. So I'd guess you have a bad phar setting, or detect_unicode or something. Run the installer with your php53 so it checks your local settings

**Comment by Rarst** [comment]
Bingo. :)

```
Some settings on your machine make Composer unable to work properly.
Make sure that you fix the issues listed below and run this script again:

The detect_unicode setting must be disabled.
Add the following to the end of your `php.ini`:
    detect_unicode = Off
```

It's peculiar that default behavior is different (it wasn't _on_ in config, just not present).

Anything phar could possibly do to handle such case, or it's wontfix?

**Comment by stof** [comment]
@Rarst I'm not sure the phar can change it. It might be too late already

**Comment by Seldaek** [comment]
I'm afraid it's wontfix, but not such a common problem anymore these days I believe.
