### ISSUE TITLE
Possibility to require the specific Composer version to act on project?

### ISSUE THREAD

**Issue by Rarst** [composer/composer#3696]
I have a peculiar not–quite–dependency issue. I have used [composer-php52](https://bitbucket.org/xrstf/composer-php52) package in a project for PHP 5.2 compatible autoload.

That package extends `Composer\Autoload\AutoloadGenerator`. Recently signature of one of extended methods in it changed, so it fatals (looking at history seems like this happened before too).

Rolling back to earlier Composer version (`composer selfupdate 1.0.0-alpha9`) works as workaround until fix. But there is no way that I see to "version" which Composer is required to build the project.

It is same runtime, but it's "outside" of the project dependencies, not "inside".

PS "earlier than" might seem like too much of an edge case, but similar logic applies to "later than" when `composer.json` is using features newer than Composer installed knows about (such as recent addition of `^` to versions).

cc @xrstf

**Comment by alcohol** [comment]
If you want to use a fixed composer binary (version) for your project, commit composer inside your repository. That is the only option.
