### ISSUE TITLE
Provide interface for lazy repositories.

### ISSUE THREAD

**Issue by slbmeh** [composer/composer#3708]
Some repositories are very large to load all at once. There is a special case in the resolver pool for composer repositories that have providers. I find myself extending the ComposerRepository class and recreating the VCS repository class for a plugin I'm working on.

**Comment by slbmeh** [comment]
The ComposerRepository approach isn't really an ideal approach either, in this scenario there's only one provider. I invert the provider/package convention internally for performance reasons. The `getPackages()` approach is really only ideal for scenarios such as array repository derivatives where you have all of the packages available upfront, or vcs repository (still an array repository but very different) where you scan for a composer.json and end up with all of the package information determining if the repo is valid.

**Comment by Seldaek** [comment]
Not sure what to say here.. not really enough info to make an informed opinion, but it doesn't sound like something we can work in easily.

**Comment by sbuzonas** [comment]
Hitting a wall here again. Extending ComposerRepository and replacing all of the internals feels wrong.

What I had in mind before was define an interface for the public api of ComposerRepository where certain things treat it differently such as Pool and ShowCommand.
