### ISSUE TITLE
Composer freezes when running Git command

### ISSUE THREAD

**Issue by thasmo** [composer/composer#3710]
Running `composer diagnose -vvv` gives:
```shell
Checking platform settings: OK
Checking git settings: Executing command (CWD): git config color.ui
```
And then it just hangs forever.

Same goes for `composer global require -vvv "laravel/installer=~1.1"`:
```shell
Changed current directory to /home/thasmo/.composer
Reading ./composer.json
Loading config file ./composer.json
Executing command (CWD): git describe --exact-match --tags
```
After printing the line `Executing command (CWD): git describe --exact-match --tags` it hangs.

Any idea what the problem could be?

**Comment by thasmo** [comment]
Ah, forgot the mention that this runs with Git 2.1.4 using Cygwin on Windows 8.

**Comment by thasmo** [comment]
Actually it times out after some time with this error:
```shell
[Symfony\Component\Process\Exception\ProcessTimedOutException]
The process "git config color.ui" exceeded the timeout of 300 seconds.
```
But running `git config color.ui` manually works just fine and returns `auto`.

**Comment by thasmo** [comment]
Found the *problem*. Running the Cygwin PHP version doesn't have the constant `PHP_WINDOWS_VERSION_BUILD` set, but it seems that without it, the piping stuff for the command/process handling doesn't work, obviously. As a workaround I'm using the PHP setting `auto_prepend_file` to set the constant manually. I'd love to see Cygwin supported, but that's probably more of a Symfony related topic.

**Comment by stof** [comment]
It is actually a Cygwin topic. They should compile PHP properly to advocate the fact that it runs on Windows.
