### ISSUE TITLE
PackageInterface::getPrettyName guidance

### ISSUE THREAD

**Issue by slbmeh** [composer/composer#3712]
What is the intent of this method? Is it simply for display purposes?

I have a custom repository that supplies wordpress packages.  If I were to return the name from the plugin/theme metadata e.g. `My Cache Plugin` instead of a `vendor/package` convention, would that be a bad thing?

**Comment by stof** [comment]
the pretty name is the name preserving the case used by the package author (while the actual package name is always lowercased). It is indeed meant for display purpose.

**Comment by slbmeh** [comment]
So if I do something weird with it, such as show something completely different from the actual package name I can be fairly confident that composer itself won't try to do anything with it other than spit it out?

**Comment by Seldaek** [comment]
Yup it should not really care what's in the pretty name
