### ISSUE TITLE
Create accessor for IOInterface on Cache

### ISSUE THREAD

**Issue by slbmeh** [composer/composer#3714]
There isn't a way to access the IOInterface on the Cache class and it is in private scope.

**Comment by stof** [comment]
What is the use case for this accessor ?

**Comment by slbmeh** [comment]
I can't remember my original use case for it. I have an extension of the Cache class for a repository and wanted to output a couple of different message in various verbosity levels about gc sweeps, cache purging, hits, and misses.

I ended up grabbing it in an overridden constructor and assigning it to a property I could access.

**Comment by Seldaek** [comment]
If it really matters feel free to send a PR changing $io to protected.
