### ISSUE TITLE
Composer updates but installation fails

### ISSUE THREAD

**Issue by rcc26** [composer/composer#3717]
Composer version: latest available to present date.

    sudo php composer.phar update

    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Updating TO_UPDATE (dev-master 6fb0f62 => VERSION)
    Checking out TOKEN
    Writing lock file
    Generating autoload files

    sudo php composer.phar install

    Loading composer repositories with package information
    Installing dependencies (including require-dev) from lock file
    Nothing to install or update
    Generating autoload files

What might be wrong here?

**Comment by slbmeh** [comment]
When you do an update it does the installation of packages. So if you try to install after and your lock file hasn't changed since running the update there should be nothing to install.

**Comment by rcc26** [comment]
I already solved it, the error happened due to some tweaks I tried to make
Em 15/02/2015 09:37, "Steve Buzonas" <notifications@github.com> escreveu:

**Comment by stof** [comment]
@rcc26 can you close this issue then ?
