### ISSUE TITLE
unable to use private github repos with 2 factor auth

### ISSUE THREAD

**Issue by staabm** [composer/composer#3718]
I am running into ..
http://imgur.com/gr4vuss

Even after "Token successfully created" I am getting re-asked for authentication and cannot proceed with private reposes while 2-factor auth is enabled?

I am on
```
root@8754e3e995ce:/dvl/amp-chat# php7 ../composer.phar
Composer version 1.0-dev (07c644ac229a21df80180598d8bb9aaba232eecb) 2015-02-03 12:51:10
```
but running composer via php7

**Comment by alcohol** [comment]
As mentioned in my comment in my PR, can you try and see if the same issue occurs with a stable version of PHP?

**Comment by staabm** [comment]
the issue hidden behind those messages was missing write access to a public repos on github, because it was linked using `git@github.com:kelunik/parsedown`

this fixed commit fixed the issue for me: https://github.com/rdlowrey/amp-chat/commit/6df2fbc49595d43ce97b94983fe5b81556d4a145

I found the underlying problem, while running `composer info` which rendered the following exception:
```
  [RuntimeException]
  Failed to execute git clone --mirror 'git@github.com:kelunik/parsedown' '/root/.composer/cache/vcs/git-github.com-kelunik-parsedown/'

  Cloning into bare repository '/root/.composer/cache/vcs/git-github.com-kelunik-parsedown'...
  Permission denied (publickey).
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
```

It seems that `composer install` misses some error handling for write problems in this conditions?

**Comment by alcohol** [comment]
The commit you linked to returns a 404 for me.

Could you also specify during which command you run into problem? Update? Install? And is this a new setup? Or did things suddenly break in an existing setup?

**Comment by staabm** [comment]
> The commit you linked to returns a 404 for me.

sorry, I linked a private repos. here is the actual diff

```diff
diff --git a/composer.json b/composer.json
index e668b83..82a5961 100644
--- a/composer.json
+++ b/composer.json
@@ -36,10 +36,6 @@
     {
       "type": "git",
       "url": "git@github.com:amphp/redis.git"
-    },
-    {
-      "type": "git",
-      "url": "git@github.com:kelunik/parsedown"
     }
   ],
   "minimum-stability": "dev",
```


> Could you also specify during which command you run into problem? Update? Install? And is this a new setup? Or did things suddenly break in an existing setup?

my initial problem occured while runnig `php7 composer install`, on a project after a clean checkout.

**Comment by alcohol** [comment]
Uh, but this behaviour is to be expected in that case.
Why would you use a private repo url in your composer.json if you don't have access?

**Comment by staabm** [comment]
> Uh, but this behaviour is to be expected in that case.
> Why would you use a private repo url in your composer.json if you don't have access?

I would expect a error message while running `composer install` that this is the case. ATM it told me that I need to add additional auth-info.

> Why would you use a private repo url in your composer.json if you don't have access?
we are working with several people on a private project and the one who added this dependency inside composer.json had the rights for the repos, but other devs dont..
In other words, this issue happend while I was working on a private repos, with a php-app which required another component which was also a private repos (and I dont had rights for this dependency).

**Comment by alcohol** [comment]
Actually, you must be doing something else wrong. It works for me without any problems.

```
cat composer.json
{
    "repositories": [
        { "type": "git", "url": "git@github.com:kelunik/parsedown" }
    ],
    "require": {
        "erusev/parsedown": "@dev"
    }
}
```
```
/srv/git/github/test $ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing erusev/parsedown (dev-master cb8cc57)
    Cloning cb8cc57742546648bb5461e66e35a92f2f89538b

Writing lock file
Generating autoload files
```

**Comment by alcohol** [comment]
Can you give me anything I could use to reproduce this issue with?

**Comment by staabm** [comment]
> Can you give me anything I could use to reproduce this issue with?

using the composer.json you posted on https://github.com/composer/composer/issues/3718#issuecomment-73504091 I can reproduce the issue.
My configured 2 factor auth might be the reason for that.

**Comment by staabm** [comment]
update: using php 5.4.4 stable it is not reproducable.

**Comment by alcohol** [comment]
Uh, okay. I don't know enough about the changes coming up in 7 yet to see why this would factor into the whole flow. I suggest leaving this open until 7 reaches stable and it becomes a version that composer actually supports. As it is right now there is no testing done against 7 (see `.travis.yml`). So support will also not be provided until this changes.

**Comment by Seldaek** [comment]
Not relevant anymore I think, as we don't do token auth from the CLI anymore
