### ISSUE TITLE
The weight of circular dependencies is not calculated accurately

### ISSUE THREAD

**Issue by olvlvl** [composer/composer#3719]
Hi,

Last year I submitted a PR for an improved package sorting method, that was merged:

https://github.com/composer/composer/pull/2644

Unfortunately, today I found a bug in the way the weight of packages with circular dependencies is calculated.

As you can see in the code, I use `$computing` to check for circular dependencies while computing the weight of a package. The problem is that I return 0 it that case, which causes the calculation to be inaccurate. For instance, `A` uses `B` and `B` uses `A`, we need to compute `B` in order to compute `A`, but because `B` needs `A` and it's a circular dependency case, `B` will get 0 as weight for `A`, thus the calculation is incorrect.

In the following code I use a new array to collect circular dependencies, and add the final values to packages using them. It's working for me but it's not pretty, and I'm looking for a better solution.

``` php
        $computing = array();
        $computed = array();
        $additional = array();
        $computeImportance = function ($name) use (&$computeImportance, &$computing, &$computed, &$additional, $usageList) {
            // reusing computed importance
            if (isset($computed[$name])) {
                return $computed[$name];
            }

            $computing[$name] = true;
            $weight = 0;

            if (isset($usageList[$name])) {
                foreach ($usageList[$name] as $user) {
                    if (isset($computing[$user])) {
                        echo "circual detection: $user (from $name)\n";
                        $additional[$name][] = $user;
                        $weight -= 1;
                        continue;
                    }

                    $weight -= 1 - $computeImportance($user);
                }
            }

            unset($computing[$name]);
            $computed[$name] = $weight;

            return $weight;
        };

        $weightList = array();

        foreach ($packages as $name => $package) {
            $weight = $computeImportance($name);
            $weightList[$name] = $weight;
        }

        foreach ($additional as $name => $users) {
            foreach ($users as $user) {
                echo "adding {$weightList[$user]} to $name\n";
                $weightList[$name] += $weightList[$user];
            }
        }
```

What do you think?

**Comment by Seldaek** [comment]
If you can submit a real PR with a test case that demonstrates the improvement that would be great!

**Comment by Seldaek** [comment]
Closing for now.. seems to work well enough in practice, so if there is really an issue please submit or PR :)
