### ISSUE TITLE
Added dependencies will be ignored by install command

### ISSUE THREAD

**Issue by bestform** [composer/composer#3720]
To reproduce:

1. install composer dependencies creating a composer.lock file
2. add a new dependency to composer.json
3. run composer install again

Expected:
Error indicating that the new dependency isn't available

Actual:
"Nothing to install or update"

Note:
Composer does complain about changed version constraints of already installed packages, that cannot be met by the versions saved in the composer.lock file.

I've looked into this issue and found out, that composer does indeed complain about the newly added dependency, but only if you specify an extra/branch-alias in the composer.json. This will result in the `RootPackage` being a `RootAliasPackage` instead of a `RootPackage` - which seems like a bug to me, as `RootPackageLoader::Load()` should return `$realPackage` instead of `$package` in https://github.com/composer/composer/blob/master/src/Composer/Package/Loader/RootPackageLoader.php#L109

If you patch this, the branch-alias will no longer cause composer install to complain about the newly added dependency - which in turn is not what I would expect from it at all - but at least the error is now happening constantly, no matter whether a branch-alias is being configured or not.

I've not yet had the time to look into it more deeply, but I guess, composer should complain about the new dependency like it does about changed and not met version constraints.

**Comment by Seldaek** [comment]
require/branch-alias probably should be part of the lock file to prevent such issues, so that an install from lock file always succeeds no matter if you changed your json. On the other hand it's sort of a misuse and it's caught already by the warning about the lock file being out of date with composer.json, so that should indicate you must run an update instead of an install

**Comment by bestform** [comment]
I see that the warning should be enough, but then again, composer does complain about changed version constraints. So whatever it does to warn the user about inconsistencies, it should handle it at least consistently - so, if you show an error should the version constraints change, an additional dependency should trigger an error, too. Currently it is just being ignored.
