### ISSUE TITLE
Set json with empty values as invalid

### ISSUE THREAD

**Issue by yourwebmaker** [composer/composer#3723]
Unintentionally, I leave the "minimum-stability" blank so for all commands I've tried composer shown the following message:

![screen shot 2015-02-09 at 8 24 22 pm](https://cloud.githubusercontent.com/assets/812971/6117138/b395d380-b099-11e4-9715-859518d20cf5.png)

The JsonParser finds this json is valid, but it isn't in composer world.

What do you guys think is better to solve this?
I guess setting up some properties as required must solve this problem in an elegant way.

Here is my composer.json:

```json
{
    "name": "yourwebmaker/test",
    "description": "nono no no",
    "minimum-stability": "",
    "license": "proprietary",
    "authors": [
        {
            "name": "Daniel Lima",
            "email": "yourwebmaker@gmail.com"
        }
    ],
    "require": {}
}
```

**Comment by alcohol** [comment]
Empty string is not a valid documented value: https://getcomposer.org/doc/04-schema.md#minimum-stability

I suppose a more descriptive error would be nice to have though.

**Comment by yourwebmaker** [comment]
Sure @alcohol . The json is valid but we need some specific Exception/ErrorMessage where this error is raised.

What would do you'd like? @Seldaek

**Comment by Seldaek** [comment]
We could change the json-schema to match a set of values perhaps? I can't remember if this is possible but it'd be the best to catch it early.

**Comment by yourwebmaker** [comment]
There's an option on json-schema that sets a set of properties as required:
http://json-schema.org/example2.html (search for "required")

**Comment by yourwebmaker** [comment]
I did some tests using `JsonSchema\Validator` + the `res/composer-schema.json` + `composer.json` above and the validator stills saying the json is valid, even if I add "minimum-stability" on `required` schemas's array.

I suggest working here:
https://github.com/composer/composer/blob/master/src/Composer/Package/Loader/RootPackageLoader.php#L131

Something like:
`BasePackage::getStability($stability)` or `BasePackage::getMinimumStability()`

**Comment by alcohol** [comment]
Did you consider using a regex pattern to treat is as an enum of sorts?

http://json-schema.org/latest/json-schema-validation.html#anchor33

something like `dev|alpha|beta|rc|stable` ( might need grouping `()` and non capturing `?:` )

**Comment by alcohol** [comment]
For example, I get this error for the above composer.json:

```
  [Composer\Json\JsonValidationException]
  "./composer.json" does not match the expected JSON schema:
   - minimum-stability : does not match the regex pattern ^(dev|alpha|beta|rc|RC|stable)$
```

By simply adding
```
diff --git i/res/composer-schema.json w/res/composer-schema.json
index 4c40bdf..1bb1487 100644
--- i/res/composer-schema.json
+++ w/res/composer-schema.json
@@ -284,7 +284,8 @@
         },
         "minimum-stability": {
             "type": ["string"],
-            "description": "The minimum stability the packages must have to be install-able. Possible values are: dev, alpha, beta, RC, stable."
+            "description": "The minimum stability the packages must have to be install-able. Possible values are: dev, alpha, beta, RC, stable.",
+            "pattern": "^(dev|alpha|beta|rc|RC|stable)$"
         },
         "prefer-stable": {
             "type": ["boolean"],
```

**Comment by alcohol** [comment]
I'm sure someone can come up with a nicer regex though... @Seldaek ;-)
