### ISSUE TITLE
Moving dependancy library on github isn't reflected in Satis

### ISSUE THREAD

**Issue by MatthewHarrigan** [composer/composer#3727]
Hello

We've moved a library in github and url has changed. We've updated our Satis repo composer.json with the new location but it fetches the library and stores it under the old github alias so when we update our local compser.json with the new location it's not found on Satis. I'm guessing this a GitHub redirect issue, but is there anyway to force satis to download a library under a particular location/alias?

**Comment by alcohol** [comment]
https://github.com/composer/satis/issues/ ?

**Comment by MatthewHarrigan** [comment]
Moved across.
