### ISSUE TITLE
Feature Request: "init --plain" that doesn't use the internet for anything (like git init)

### ISSUE THREAD

**Issue by jlem** [composer/composer#3728]
I just recently started a composer project just so I could get access to an autoloader. I didn't define *any* dependencies, but still attempted to contact packagist anyway. The problem is, that packagist was having some serious performance problems, so what should have been an instantaneous setup of the composer vendor and autoloader, took several minutes.

I want the ability to setup a blank composer project like I can with `git init` - simply include the vendor/composer directory from local cache, as well as the autoloader. Then even if I don't have internet access (say, on a plane), I can easily get the autoloader and a blank project which I can then modify later.

**Comment by slbmeh** [comment]
You can put `"packagist": false` in a repositories section of your `$COMPSER_HOME/config.json` to disable packagist. And as long as you don't have any repositories defined that require internet access you should get the result you are describing.

**Comment by jlem** [comment]
But that's a global configuration, meaning for all future projects and all repository calls, it's going to disable packagist, isn't it? I don't want to disable it globally, I simply want to choose when I don't want to use it.

**Comment by Seldaek** [comment]
No you can actually disable it per-composer.json as well as globally. `composer config repo.packagist false` will turn it off locally (as of today with #3749 merged).

I don't think it's such a common use case that we really need an additional flag for this.

**Comment by jlem** [comment]
Fair enough that you can do it locally, but I whole-heartedly disagree that this is not a common use-case. Imagine not being able to do `git init` ;)

**Comment by Seldaek** [comment]
git init does a bit more than `echo "{}" > composer.json` :) I know composer init too but for the few times you don't have internet you probably won't be able to install anyway since composer isn't extremely good at operating fully from cache.. You can also use `composer require --no-update foo/bar:~2.0` btw

**Comment by jlem** [comment]
`composer config repositories.packagist false` does not appear work:

Get this error:

```[RuntimeException]                                                                                       
  You must pass the type and a url. Example: php composer.phar config repositories.foo vcs http://bar.com
```

I guess I'll ask my question a different way:

Why doesn't composer come packaged with a gzip of its autoloader by default? Why does it have to get its autoloader from packagist every time?

**Comment by Seldaek** [comment]
@jlem I have no idea what you mean about the autoloader, you can definitely do that offline like `composer dump-autoload`

As for the error, have you run `composer self-update` to get the latest build?
