### ISSUE TITLE
Remove all trace of Composer

### ISSUE THREAD

**Issue by Bucklash** [composer/composer#3730]
Hi.
If this not correct place for the question I apologise...

I would like to remove / delete/ uninstall all trace of Composer

Any tips

Thanks

**Comment by Faryshta** [comment]
which system are you using?

**Comment by Bucklash** [comment]
Hi
I'm on iMac OSX Yosemite
I installed Composer to install Drush which is for Drupal CMS
It's all going pear shaped so want to start from scratch

**Comment by Bucklash** [comment]
I can see:
Macintosh HD/usr/local/bin/composer.phar
Users/[my username]/.composer

Do I just delete these ?

Thanks for helping :)

**Comment by Faryshta** [comment]
yes, delete both, one is the executable file, the other is the configuration folder

**Comment by Bucklash** [comment]
Thanks Faryshta

Appreciate your assistance, most kind

**Comment by Faryshta** [comment]
close this issue please :)

2015-02-10 17:57 GMT-06:00 Jon Buckner <notifications@github.com>:
