### ISSUE TITLE
Command Aliases

### ISSUE THREAD

**Issue by slbmeh** [composer/composer#3731]
I type `composer udpate` so often that I have `"scripts": { "udpate": "composer update" }` in a lot of my composer json files.  It would be nice to be able to set this in the config.json, as my typographical errors may differ to others working on the same project.

Would it be beneficial to have an aliases section for commands, or a way to define scripts in the configuration?

Expanding on this idea, people might have a `"test": "phpunit"` in their config as a common use case. If this is an acceptable feature, would it be limited to the scripts added as command aliases.  I could see a case for npm or bower install in a `post-update-cmd` to be set globally.  This may become difficult for the php class type of tasks.

**Comment by alcohol** [comment]
You could always ask your employer to sponsor a typing course for you?

**Comment by Seldaek** [comment]
@slbmeh I don't think having this globally really makes sense for most cases. What I suggest instead is:

- type `composer up` which is a whole lot easier, or even just `u` will work.
- open an issue on symfony to make the console auto-correct names and prompt if the guessed one should be executed. Right now it just does:

```
  [InvalidArgumentException]
  Command "udpate" is not defined.
  Did you mean this?
      update
```

But if it went like: `Command does not exist, but we think you meant update, run this? [Yn]` it might be nicer :)

**Comment by Seldaek** [comment]
@slbmeh I don't think having this globally really makes sense for most cases. What I suggest instead is:

- type `composer up` which is a whole lot easier, or even just `u` will work.
- open an issue on symfony to make the console auto-correct names and prompt if the guessed one should be executed. Right now it just does:

```
  [InvalidArgumentException]
  Command "udpate" is not defined.
  Did you mean this?
      update
```

But if it went like: `Command does not exist, but we think you meant update, run this? [Yn]` it might be nicer :)

**Comment by hkdobrev** [comment]
@Seldaek Git goes a step further and actually executes the corrected command if you don't type a character in 0.x seconds.

**Comment by stof** [comment]
@hkdobrev this could be submitted as a feature request against the Symfony Console component

**Comment by alcohol** [comment]
While on the subject, alternatively you could also look at shell completion for bash/zsh/etc. These also support auto correcting spelling mistakes and such.
