### ISSUE TITLE
ArchivableFilesFinder / GitExcludeFilter

### ISSUE THREAD

**Issue by kryptychon** [composer/composer#3733]
Hi there,

I'm running a private package repository with satis and git.

While rebuilding the packages, I noticed, some packages are not containing all the files I get doing "git clone /foo/bar".
I did some research ending up in https://github.com/composer/composer/blob/1d8f05f1dd0e390f253f79ea86cd505178360019/src/Composer/Package/Archiver/ArchivableFilesFinder.php#L48

The cause for the "missing stuff" in the packages is the GitExcludeFilter, parsing the .gitignore files and preventing the ignored stuff to show up in the packages.

Is there a way to prevent this behavior e.g with an option during the satis build process?

Regards,
Kryp

**Comment by cs278** [comment]
You have files added in your repository but is mentioned in your gitignore file? You could fix your ignore file so it makes sense.

Composer shouldn't be consulting the ignore file for archives though.

**Comment by cs278** [comment]
@naderman Was there any reason to deviate from Git's behaviour in #1567?

**Comment by naderman** [comment]
I don't remember that to be honest. From today's perspective I would say it should respect gitattributes but gitignore should have no impact on it.

**Comment by cs278** [comment]
@naderman It has occurred to me that it might be to try and account for a dirty repository. Perhaps it would be safer to abort if `git status --ignored` is not empty.

**Comment by kryptychon** [comment]
Hi,

maybe I'm missing something.
Why is satis trying to be "intelligent" by parsing the .gitignore stuff?
Isn't that the part of git itself when comitting?

In my judgment, satis should build packages from what it checkouts from the git repository.

**Comment by kryptychon** [comment]
Further investigation turnes out, the .gitignore is not properly parsed.
Any progress on that issue?

**Comment by Seldaek** [comment]
Can you give details as to why/how it is not properly parsed? Otherwise there is no chance anyone can fix this.

**Comment by marcaube** [comment]
I've hit the same problem with a package that I don't *own*.

```bash
$ composer archive leafo/scssphp 0.0.7
Searching for the specified package.
Found an exact match leafo/scssphp v0.0.7.
Creating the archive into ".".
  - Installing leafo/scssphp (v0.0.7)
    Downloading: 100%         

Created: ./leafo-scssphp-e5a79218c349cbc03dc99004fbad938c7b82391f-zip-0db3e8.tar
```

Open the archive and the file `scss.inc.php` is missing. If you check in the [GitHub archive](https://github.com/leafo/scssphp/archive/v0.0.7.zip), `scss.inc.php` is present. This mismatch is problematic as we have to leave that one single dependency outside of Satis, rendering the whole exercise pointless. If GitHub goes down, we go down too.

**Comment by Seldaek** [comment]
@marcaube [Toran Proxy](https://toranproxy.com) does not have that issue AFAIK as it uses the zip files from github when available. Maybe consider switching over?
