### ISSUE TITLE
Travis build problem

### ISSUE THREAD

**Issue by kuczek** [composer/composer#3735]
I've problem with building project with travis.

Here you have response:
https://travis-ci.org/lexik/LexikTranslationBundle/jobs/50459586

Can it be some problem with composer? Any idea how to fix it.

**Comment by slbmeh** [comment]
It appears to be a very complex dependency graph when you hit the Symfony 2.6 constraint. See #1959. Here's the profiler output on a 12 core Mac Pro with 64 GB of memory:
`Memory usage: 195.85MB (peak: 806.48MB), time 605.41s`

You can put `travis_wait` in front of the `composer update -vvv` command in your `.travis.yml` to prevent it from timing out after 10 minutes with no output.

**Comment by kuczek** [comment]
@slbmeh https://travis-ci.org/kuczek/LexikTranslationBundle/jobs/50986266 or
