### ISSUE TITLE
[Feature / Option] Tell require to load a specific composer.json file

### ISSUE THREAD

**Issue by Taluu** [composer/composer#3738]
When using require, it uses the `Factory` to locate a composer.json file (if there is a value in a `COMPOSER_HOME` env variable, or the basic one). But this is not extensible.

How about allowing a new option to the `require` command (and possibly the install / update commands) that points on a composer.json  (or equivalent), and if it is not set, point to the current behavior, such as `composer require --json my/json.file` ? The option name is of course not fixed

**Comment by cs278** [comment]
This is already possible using the [`COMPOSER` environment variable](https://getcomposer.org/doc/03-cli.md#composer).

**Comment by Taluu** [comment]
> When using require, it uses the `Factory` to locate a composer.json file (if there is a value in a `COMPOSER_HOME` env variable, or the basic one). But this is not extensible.

This also applies for the `COMPOSER` cariable... I need to be able to use the require mechanism without going through a command line mechanism (extending the require command in fact). The mechanism you describe here applies only from a cli call

**Comment by cs278** [comment]
Well the simplest way would be to `putenv('COMPOSER=./my-composer.json');`.

**Comment by alcohol** [comment]
Have you heard about `composer -d other/directory [install|update|etc]` ?

Though to be honest, from the sounds of what you are saying, you are not using composer, but rather a modified project of your own extending composer. If that is indeed the case, you should provide your own support.

**Comment by Taluu** [comment]
Mmh indeed, I didn't know this option existed. This should solve what my problem was.
