### ISSUE TITLE
Vendor\Package is not autoloadable, can not call post-update-cmd script

### ISSUE THREAD

**Issue by doublemcz** [composer/composer#3739]
I am getting Class Vendor\AppComponents\Composer\PostUpdate is not autoloadable, can not call post-update-cmd script.

In file autoload_classmap.php is the class registered properly.

```php
<?php
// autoload_classmap.php @generated by Composer
$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Vendor\\AppComponents\\Composer\\PostUpdate' => $vendorDir . '/vendor/app-components/src/Composer/PostUpdate.php',
);
```

Composer.json
```json
{
  ...
  "scripts": {
    "post-update-cmd": "Vendor\\AppComponents\\Composer\\PostUpdate::copyClientSide"
  }
}
```

Class
```php
namespace Vendor\AppComponents\Composer;

class PostUpdate
{
	public static function copyClientSide()
	{
		// Code..
	}
}
```

**Comment by slbmeh** [comment]
What do your autoload blocks look like in your composer.json? Is there anything else declared within them?

**Comment by doublemcz** [comment]
There is not any autoload block in the composer.json where is the "scripts" tag defined (root composer.json). The autoload is definied in the .json feature that is defined in the "require" block (at root composer.json). Is that correct or the autoload must be defined in the root composer.json to use scripts?

**Comment by slbmeh** [comment]
That error spits out verbatim the class name it did the `class_exists` on. You can define scripts from dependency repositories. A common example of that is in symfony standard. The class map is the first place to look then it tries path resolution from namespaces. I'm not sure. May sound like a silly question, but are you sure the file is in the location the map says it is? I know there can be strange behavior if you update a dependency that has a script and it moves or has a typo or anything like that.

If you do `composer dump-autoload` and then the update does the script run? The other possible scenario I can think of is that when you ran the update you had the script defined, but the autoload wasn't. It would be updated in the update command, but the context composer would be initialized in prior to that being generated wouldn't know how to load that class.

**Comment by doublemcz** [comment]
I checked the file path and it is correct. I also run composer `dump-autoload` and then I tried to run scripts manually by `composer run-script post-update-cmd` but the result is the same. Is there any possible way how can I debug the composer? I am using `php composer.phar` now.

**Comment by slbmeh** [comment]
@doublemcz you could check out the source project and use the bin in it instead. Then you can modify the composer source to dump out information that could be helpful.

**Comment by bigwhoop** [comment]
I'm having the same problem. Here's a simple use-case:

    composer run-script pre-install-cmd
    Class Test\Build\ComposerHooks is not autoloadable, can not call pre-install-cmd script

**composer.json**

    {
        "name": "test/test",
        "autoload": {
            "classmap": [
                "build"
            ]
        },
        "scripts": {
            "pre-install-cmd": "Test\\Build\\ComposerHooks::preInstall"
        }
    }

**build/ComposerHooks.php**

    <?php
    namespace Test\Build;
    
    use Composer\Script\Event;
    
    class ComposerHooks
    {
        public static function preInstall(Event $event)
        {
            exit('here');
        }
    }

**vendor/composer/autoload_classmap.php**

    <?php
    
    // autoload_classmap.php @generated by Composer
    
    $vendorDir = dirname(dirname(__FILE__));
    $baseDir = dirname($vendorDir);
    
    return array(
        'Test\\Build\\ComposerHooks' => $baseDir . '/build/ComposerHooks.php',
    );

* **Platform:** Windows 7
* **Composer Version:** e5985a9b559747a5f3868361ff26c31818d8c184

Happy to provide further information. Thanks guys.

**Comment by domnulnopcea** [comment]
I experience the same issue

**Comment by stof** [comment]
@bigwhoop IIRC, the classmap autoloading is indeed not supported for scripts. Building a classmap is an heavy work, and doing it after each package install to be able to dispatch the event would slow down composer. On the other hand, using PSR-0 or PSR-4 makes the autoloader creation very cheap.

**Comment by domnulnopcea** [comment]
still it should be provided. not all packages are psr-4. a lot of them have autoloading by classmap. thus, the functionality provided by those packages can not be used in the scripts. this is a MUST

you do not run composer instal/update every 5 minutes, so this operation begin heavy is not a reason

thanks

**Comment by slbmeh** [comment]
@domnulnopcea I'm not sure you understand, it being heavy isn't a per run type of problem. It is a per package type of problem. You would need to regenerate the autoloader classmap after every package was installed.

**Comment by domnulnopcea** [comment]
Hi @slbmeh Yes, I got this. But you see, you do not install a new package every 5 seconds! so waiting a little bit more would do no harm...

once you got your list of requirements in composer.json, how often is it that you add another one? (maybe once a week, every 2 weeek, once a month?)

you are limiting the functionality offered by a lot of composer packages that load their classes by "classmap"!!

**Comment by slbmeh** [comment]
@domnulnopcea if you're doing active development on a framework with a number of components you may be doing composer update a few times a day to pull in changes to the components.

My framework has a few hundred dependencies so recompiling the classmap for each package would be extremely expensive and time consuming.

**Comment by stof** [comment]
@domnulnopcea the issue is that when doing a single composer run, it could require building classmaps hundred times, which is a major performance issue.

@Seldaek the documentation should explain that packages providing composer scripts must use a PSR autoloading. I don't think it is mentionned in the doc currently

**Comment by JohnyDays** [comment]
Would it be possible to support "files" autoloading in this case, or would it also be a performance issue?

**Comment by stof** [comment]
@JohnyDays well, for files, it might be possible to do something

**Comment by Seldaek** [comment]
We support classmap autoload for scripts/plugins now.
