### ISSUE TITLE
private toranproxy repo and composer

### ISSUE THREAD

**Issue by vincentaubert** [composer/composer#3741]
Hello,

I have a private git repository under toranproxy.

When I try to install this project as a dependency via composer with a version constraint to dev-master.

This error appears when i'm in the -vvv mode of composer install (update does the same)

<my toran proxy git repo>/info/refs?service=git-upload-pack not found: did you run git update-server-info on the server?

The refs folder is not present at this place but at this one : <my toran proxy repo>/refs

my composer version : 

Composer version 1.0-dev (1d8f05f1dd0e390f253f79ea86cd505178360019) 2015-02-11 11:31:57

Is it possible to correct this?

thanks

**Comment by stof** [comment]
This looks like an issue with ToranProxy rather than Composer.

**Comment by Seldaek** [comment]
I assume you misconfigured the git settings in toran, but there isn't quite enough data here to say for sure. Closing this as it is indeed toran related and not composer.
