### ISSUE TITLE
change install path

### ISSUE THREAD

**Issue by ramin2nt2** [composer/composer#3743]
{
        "name": "raminious/user",
        "authors": [
            {
                "name":  "",
                "email": ""
            }
        ],
    
        "autoload": {
            "psr-4": {
                "raminious\\user\\": ""
            }
        },
    
        "minimum-stability": "dev"
    }

Above composer.json will copy the package too: <b>app/vendor/raminious/user</b><br>
But I need my packages (that are modules) create to app/vendor/raminious/<b>modules</b>/user<br>

How could I change the json file to achieve this?
Is it possible with composer?

**Comment by slbmeh** [comment]
I'm not sure I understand. That `composer.json` won't copy anything anywhere without dependencies. If you want your dependencies to install in a different location you can look into the `vendor-dir` settings on the root package, or if you control the dependencies you can try different things with `target-dir` or put another `/` in the package name for the simpler solutions.

Generally when it comes down to fine tuning specific locations for specific packages your best bet is a [Custom Installer](https://getcomposer.org/doc/articles/custom-installers.md)

**Comment by stof** [comment]
the composer/installers package already provide some custom installers, and it allows controlling where the package will be installed: http://composer.github.io/installers/
