### ISSUE TITLE
Invalid version string "~1.*"

### ISSUE THREAD

**Issue by schel4ok** [composer/composer#3745]
these 2 commands
>composer dump-autoload
and 
>composer update

gives me the same error

```
  [UnexpectedValueException]
  Could not parse version constraint ~1.*: Invalid version string "~1.*"
```

whereas

>composer self-update
You are already using composer version 781d8cb9255505b49266a34e17fd9e9acd56cfd7.

**Comment by slbmeh** [comment]
The `composer self-update` command updates the `composer.phar`, it doesn't load your local repository. `~1.*` is an invalid version string, use either `1.*` or use the `~` with a real version number. For instance `~1.1` is equivalent to `>=1.1 <2.0` see [Package Versions](https://getcomposer.org/doc/01-basic-usage.md#package-versions)
