### ISSUE TITLE
replace behaviour

### ISSUE THREAD

**Issue by alcohol** [composer/composer#3754]
Discussion: Is the following desired behaviour? Should this conflict or not?
Priority: low

While resolving, `replace` doesn't seem to be taken into account, or at least not in a manner which one might expect. For example, I expect the following to either conflict or not install the separate component. But composer does so happily.

In other words, replace allows you to install the same library in different versions potentially.

```
$ composer require symfony/symfony:2.4.10 symfony/http-foundation:2.6.4
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing psr/log (1.0.0)
    Loading from cache

  - Installing symfony/http-foundation (v2.6.4)
    Downloading: 100%

  - Installing twig/twig (v1.18.0)
    Loading from cache

  - Installing doctrine/lexer (v1.0.1)
    Loading from cache

  - Installing doctrine/annotations (v1.2.3)
    Loading from cache

  - Installing doctrine/collections (v1.2)
    Loading from cache

  - Installing doctrine/cache (v1.4.0)
    Loading from cache

  - Installing doctrine/inflector (v1.0.1)
    Loading from cache

  - Installing doctrine/common (v2.4.2)
    Loading from cache

  - Installing symfony/icu (v1.2.2)
    Downloading: 100%

  - Installing symfony/symfony (v2.4.10)
    Downloading: 100%

Writing lock file
Generating autoload files
```

Normally composer does not allow you to install different versions of the same library.

/cc @naderman @Seldaek

**Comment by Seldaek** [comment]
BTW the second use case is a bug in require if anything. I mean if you require twice the same in one `require` command it should possibly error, and for sure it should overwrite in the json file and not end up with twice the same. But again that's a misuse thing which isn't so important.

**Comment by Seldaek** [comment]
As for the first use case, I think either we conflict or we leave it as is now, but we can not possibly treat a replace of 2.4.10 as replacing 2.6.4 as if something required that they probably/should have a good reason.

**Comment by alcohol** [comment]
It didn't end up in the composer.json twice. Those are two seperate examples. One where I used the require command, and one where I manually generated a composer.json. Sorry if that wasn't clear enough. I'll modify the post.

**Comment by bestform** [comment]
As discussed on IRC, I strongly think, that should result in a conflict.
Having both versions installed will result in problems, that won't be apparent immediately. The autoloader might or might not chose the correct version for your case.
There shouldn't be any way that allows installing the same library in two different versions. Composer normally won't do this anyway, so why should it allow it in this scenario?

**Comment by slbmeh** [comment]
My thought back in #1965 was that autoloads could possibly be considered.  The replace case where the package is an alternative might not be a conflict.  May be bad usage of replace imo, but potentially necessary in some scenarios.

I can't clearly think out an example right now, but I remember dealing with such a scenario 2 years ago.

**Comment by stof** [comment]
@Seldaek replace is explicitly described as being provide+conflict. And previous versions of Composer used to handle the conflict properly. I'm quite sure the change is related to the optimizations of the solver trying to limit the data being added in the solver based on root requirements. I don't think this optimization works well for conflicts.

**Comment by naderman** [comment]
@stof a conflict with the version it replaces, not a conflict with a different version, which is what is being discussed here?

**Comment by naderman** [comment]
e.g. foo 1.0 replaces bar 1.2, is the same as foo 1.0 provides bar 1.2 and foo conflicts with bar 1.2, but bar 1.4 does not conflict with foo 1.0 because of this.

**Comment by alcohol** [comment]
But then shouldn't it still limit to install ONE version only (e.g. the highest allowed) and not install both versions side by side?

**Comment by stof** [comment]
@naderman but symfony/console 2.3 is meant to conflict with symfony/console 2.5 according to the concept of packages, no ? So replace should provide the version it replaces (which should be an exact match as you cannot really replace multiple codebases with a single one IMO), but it should conflict with any version of the pacjage

**Comment by stof** [comment]
With the current buggy optimization, I can now have 2 versions of the symfony/console code being installed, which can create very nasty bugs if some classes are loaded from one version and others from the other version (and it can also break other libraries if the autoloading loads the old version of the code while it depends on new features)

**Comment by alcohol** [comment]
This is also the principle that we were discussing in #composer.

I's not possible to do `composer install symfony/console:2.3.0 symfony/console:2.5.0`.
However, thanks to replace, it **is** possible.

Now one could argue that it's not the same scenario. Technically you are right, but from a higher level perspective, it seems logically wrong and undesirable.

**Comment by bestform** [comment]
What @stof said. The current behavior might help some people out when trying to install conflicting packages this way. But that will result in the described bugs that in most cases won't even be recognized immediately. It will cause bugs, that happen some time at runtime when the wrongly autoloaded class suddenly doesn't look like the caller is expecting it to.
Installing two conflicting versions at the same time is not possible in composer for a good reason. I see no reason why this case should be an exception. Or am I missing something?

**Comment by stof** [comment]
@naderman please try this same case with composer 1.0-alpha7. I'm quite sure that you will see that it prevents such case by making rules conflict properly. The root package optimizations added in alpha8 are what is making this weird case possible IMO.

**Comment by naderman** [comment]
@stof From what I understood this issue is not about two versions of one package being installed, but one version of a package and a replacer of a different version of that package. This has nothing to do with the optimisations.

**Comment by naderman** [comment]
Oh wait I think I see what you mean now, even the provided symfony/console version should conflict with the other symfony/console version, that's a bug indeed, will have to take a look.

**Comment by stof** [comment]
@seldaek @naderman I think it is actually related to https://github.com/composer/composer/commit/b4698568d2575a3f3d0851a38d27cf8a5cccb706#diff-f789056a465cafc0e4066a2dea6254ac: this commit explicitly changed this behavior as can be seen by the test change

**Comment by stof** [comment]
And the next commit updated the test description saying the new behavior is a bad idea: https://github.com/composer/composer/commit/5d3c7ab6b783d3867735b0ae947bf5f880e43658. @Seldaek why not keeping the previous behavior ?

**Comment by bestform** [comment]
@stof the original test was written by me to test the behavior I expected composer to show. So it came in with my pull request, but @Seldaek decided, that the tests should confirm the current behavior until we have a look at it in another issue (read: here).

**Comment by stof** [comment]
@bestform was your test passing before you patch or no ?

**Comment by bestform** [comment]
@stof no, they just confirmed the "bug".
Quote from the original PR (https://github.com/composer/composer/pull/3746): "This PR currently just contains two tests, that reproduce the problem. No fix has been implemented, yet."

**Comment by stof** [comment]
well, merging a test enforcing the wrong behavior is a bad idea IMO.

**Comment by alcohol** [comment]
@naderman is this still something to consider for 2.0 or have things changed since I opened this? I don't quite recall what has happened in the mean time.

**Comment by alcohol** [comment]
Great, then I will close this issue.
