### ISSUE TITLE
Windows 8.1 => ErrorException for ZipArchive

### ISSUE THREAD

**Issue by Daijobou** [composer/composer#3755]
I get a error with install on windows 8.1 64Bit

~~~~~
cmd>composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing phpunit/phpunit-mock-objects (2.3.0)
    Downloading: connection...    Downloading: 0%
    Downloading: 5%
.....
    Downloading: 100%

  [ErrorException]
  ZipArchive::extractTo(C:\Users\Username\Folder\SphinxQL-Query-Builder/vendor/composer/d057307a/sebastianbergmann-phpunit-mock-objects-c63d236\tests\MockObject/namespaced_class_implementing_interface_call_parent_constructor.phpt): failed to open stream: Invalid argument
~~~~~

You can see that path change "\" to "/" many times.

~~~~~
cmd>composer -V
Composer version 1.0-dev (5d3c7ab6b783d3867735b0ae947bf5f880e43658) 2015-02-17 14:43:09
~~~~~

**Comment by pborreli** [comment]
maybe the character file path limit is reached ? I don't think it has to do with the \ and /, Windows knows how to handle with it most of the time

**Comment by alcohol** [comment]
Could you try running the composer testsuite on Windows 8.1? I think it includes some archive tests.

```
git clone https://github.com/composer/composer
cd composer
composer install
bin/vendor/phpunit
```

Alternatively, as a quick work around, run `composer install --prefer-source`. The zip archives come with a dist install.

**Comment by Daijobou** [comment]
I have uninstalled Composer and re-installed again. Working now and with "Shell menu" is very easy. Thanks.

**Comment by Daijobou** [comment]
The workaround "composer install --prefer-source" have the same error message. Unfortunately, with a testsuite I can't help. I have tried it, but ...
I have downloaded composer-master.zip, extracted it, startet CMD.exe and in composer-master folder I typed "composer install". After this a vendor in root of this folder was successfuly created. A folder with "bin/vendor/phpunit" not exists. Sory, but I don't use "git" and composer for first time.

**Comment by pborreli** [comment]
try to move the project to `c:\test` and rerun composer

**Comment by alcohol** [comment]
Sorry that should have been `vendor/bin/phpunit`, not ~~`bin/vendor/phpunit`~~

**Comment by fstfrognation** [comment]
FYI - in case anyone else runs across this problem.  I had a similar issue and tried doing the composer install in a top level directory "c:\blah" and it worked just fine.  As I increased the depth of the project's directory, it eventually failed - so some part of the flow just doesn't handle the deep hierarchy all that well.  I even tried to copy the eventual results back to my original directory and Windows file manager choked on the number of characters.

**Comment by alcohol** [comment]
I have no idea if this could be related, but there seems to be a limit to the [maximum length of a path](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#maxpath).

**Comment by fstfrognation** [comment]
Yup... that's it.  Apparently composer will sometimes tell you the path
length is too long, other times it won't.  I stumbled across this thread
before i found the other one.

**Comment by alcohol** [comment]
I'm not entirely convinced it is related, since the length of the path mentioned in the opening post of this issue was less than the maximum length described in that document. It might be worth investigating though.

**Comment by Seldaek** [comment]
Yeah
