### ISSUE TITLE
HTTP Header

### ISSUE THREAD

**Issue by jonnyxe** [composer/composer#3756]
Please integrate the possibility to set the http header for individual repositories. Thx

**Comment by Seldaek** [comment]
What do you mean by http header exactly?

**Comment by jonnyxe** [comment]
By adding an individual repository the option to set its header when curling to the packages.json file. If you want to have an authentication / user based (e.g. with an api token) packages.json file.

If you could define header fields for the repository (e.g. API-TOKEN) than you could generate a user based packages.json file. Nevertheless by settings a repository with https, the header fields would be encrypted, too. That would be very useful!

**Comment by Seldaek** [comment]
You can configure that per-domain using the http-basic config https://getcomposer.org/doc/04-schema.md#config for http basic authentication.

**Comment by jonnyxe** [comment]
Right, but there is no option to set other header fields

**Comment by Seldaek** [comment]
I think you can actually configure it in the repository using stream options like in https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md#security but providing http > headers instead of ssh2. Haven't tried but it should work if we don't do anything dumb later on to prevent it (which could well be..).

**Comment by jonnyxe** [comment]
Do you have an example / does it work? Tried things like:

```json
{
            "type": "composer",
            "url": "http://ex.com/",
            "options": {
	            "headers":{
		            "API":"asd"
	            }
            }
        }
```


OR

```json
{
            "type": "composer",
            "url": "http://ex.com/",
            "options": {
	            "http":
		            "headers":{
		                    "API":"asd"
	                    }
		    }
            }
        }
```

each with "headers" and "header" and it didn't work :(

**Comment by jonnyxe** [comment]
OK, found it :D It does already work! But please put that in your documentation! :)
```json
{
            "type": "composer",
            "url": "http://ex.com/",
            "options": {
	            "http":{
		            "header":[
		            	"API-TOKEN: asd"
		            ]
	            }
            }
        }
```
