### ISSUE TITLE
Composer commands with a hyphen (self-update, clear-cache, etc.) don't require anything after the hyphen (self, clear, etc.)

### ISSUE THREAD

**Issue by dlancea** [composer/composer#3757]
Running the command `composer self` or `composer self-upda` is the same as running `composer self-update`.

Just a weird side effect of using hyphens in the command, I assume the rest of the command is interpreted as options, which are ignored(?).

Not a big deal to leave this un-fixed, but it could lead to confusion.

**Comment by alcohol** [comment]
You can shorten any command as much as you'd like (as long as isn't ambigious). For example, `composer ins` will `install`, `composer ini` will run `init`, `composer u` will run `update`. This is a feature of Symfony Console component, not Composer.

**Comment by dlancea** [comment]
Whoops, I stand corrected. Thanks.
