### ISSUE TITLE
Replace deprecated TableHelper and DialogHelper before updating Composer dependencies

### ISSUE THREAD

**Issue by alcohol** [composer/composer#3760]
Components affected:
- [TableHelper](http://symfony.com/doc/current/components/console/helpers/tablehelper.html)
- [DialogHelper](http://symfony.com/doc/current/components/console/helpers/dialoghelper.html)

Replacements:
- [Table](http://symfony.com/doc/current/components/console/helpers/table.html)
- [QuestionHelper](http://symfony.com/doc/current/components/console/helpers/questionhelper.html)

These are deprecated as of 2.5.x. Composer is currently using 2.6.x. 
As of 2.7.x these will actually trigger errors.
- See TableHelper [here](https://github.com/symfony/Console/blob/2.7/Helper/TableHelper.php#L40)
- See DialogHelper [here](https://github.com/symfony/Console/blob/2.7/Helper/DialogHelper.php#L34)

The TableHelper is already replaced in the following PR's: #3593 and #3715
The QuestionHelper has no open PR's

**Comment by stof** [comment]
the issue with these 2 PRs is that they are bumping the Console requirement to 2.5+ (without doing it properly), which would prevent Packagist from depending on Composer.

**Comment by alcohol** [comment]
Good catch. I can remove the specific commit from my own PR (#3715) and leave a comment on #3593 regarding this, or create a new PR from my commit and include an updated composer.json requirement. What would you suggest?

**Comment by stof** [comment]
@alcohol given that your own PR is about a totally different change, it should not include the replacement anyway (mixing different changes in the same PR is making the review harder)

**Comment by alcohol** [comment]
Yeah, it's just something I ran into while updating all the files. I explicitly committed it separately so it would be easy to remove. I'll go do that right now.

**Comment by Seldaek** [comment]
@alcohol if you have time to tackle the DialogHelper > QuestionHelper part of this that'd be great.

**Comment by alcohol** [comment]
Yeah I got time. I think I had some questions regarding it though, but I can't recall at the moment. They will probably resurface as I dive into it again.
