### ISSUE TITLE
Assignment in if statement

### ISSUE THREAD

**Issue by wriver4** [composer/composer#3763]
inside Vendor/composer/ClassLoader.php around line 320
~~~php
    /**
     * Loads the given class or interface.
     *
     * @param  string    $class The name of the class
     * @return bool|null True if loaded, null otherwise
     */
    public function loadClass($class)
    {
~~~
if ($file = $this->findFile($class))
~~~php
        {
            includeFile($file);

            return true;
        }
    }
~~~

**Comment by RQuadling** [comment]
No different to ...

```
$file = $this->findFile($class);
if ($file) { ... }
```

**Comment by slbmeh** [comment]
It's a pretty common practice to do something with the return result of a method or something else if it does not return usable value.  What is the issue you are seeing?

**Comment by wriver4** [comment]
Sorry I didn't get back quicker. Besides being not my preferred coding practice. I am getting tired of fixing it because it keeps showing as an error in netbeans.

**Comment by RQuadling** [comment]
Ah. There's your problem! <ducks>
