### ISSUE TITLE
Better (softer) handling of php version constraint

### ISSUE THREAD

**Issue by mindplay-dk** [composer/composer#3767]
I just wasted an hour trying to install a package that had a version constraint like `php >=5.4.8` - the error message didn't make any sense. It makes it sound like there is no package (out there) fulfilling that requirement.

It took me a while to understand that the available version number on the virtual php package is not in fact dependent on what's available "out there", but is based on checking the version number of my command-line PHP processor.

First of all, the error message is confusing and doesn't make any sense - it explain that your local PHP version does not satisfy the requirement.

Secondly, I believe this should be a warning, not an error that aborts the package installation - in my case, I actually do have PHP 5.6 installed and running as my CGI processor. I just happened to still have PHP 5.4.7 running as my command-line processor, because I run other (third party) PHP command-line tools that do not yet work with PHP 5.6.

Why is sort of besides the point though - the point is, even though the package I was installing had a requirement on that version of PHP, the installation of the package itself does not depend upon any specific version of PHP, only on the version required to run Composer.

So I don't believe there's any real reason to stop me dead in my tracks here?

Or if there is a (good) reason to abort the installation, at least I think this confusing error message needs to be cleared up.

**Comment by jakoch** [comment]
I could imagine, that you might be looking for the CLI option `--ignore-platform-reqs`, e.g. `composer install --ignore-platform-reqs`. This allows an installation, even if the local machine does not fulfill these.

And yes, you are right. The error message given is not really helpful.

Ok, you are talking about the following error message:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package php could not be found in any version, there may be a typo in the package name.
```
Yes, the message is not really indicating, that it is a local env requirement.
Maybe something like this is better to guide the user:
`The project requires PHP {$version}, but your local PHP version does not satisfy the requirement. You can disable this check by using --ignore-platform-reqs.`

**Comment by mindplay-dk** [comment]
That sounds like an appropriate error message, yes :+1:

**Comment by Seldaek** [comment]
You are right this is kinda sub-par.

New messages:

```
  Problem 1
    - This package requires php >=6.0 but your PHP version does not satisfy that requirement.
  Problem 2
    - This package requires hhvm 5 but you are running this with PHP and not HHVM.
  Problem 3
    - Installation request for foo/bar * -> satisfiable by foo/bar[3.0].
    - foo/bar 3.0 requires php 7.0 -> your PHP version does not satisfy that requirement.
  Problem 4
    - Installation request for foo/bar2 * -> satisfiable by foo/bar2[3.0].
    - foo/bar2 3.0 requires hhvm 4.0 -> you are running this with PHP and not HHVM.
```
