### ISSUE TITLE
Composer Install error

### ISSUE THREAD

**Issue by exptom** [composer/composer#3769]
Just updated composer to the latest version and now get the following error executing a composer install:

`Argument 5 passed to Composer\Installer\PackageEvent::__construct() must be an instance of Composer\Installer\PolicyInterface, instance of Composer\DependencyResolver\DefaultPolicy given, called in phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php on line 111`

**Comment by anvanza** [comment]
sudo composer self-update

**Comment by Seldaek** [comment]
Yup sorry I messed up and fixed right after so you just had the wrong version at the wrong time..

**Comment by exptom** [comment]
No worries, all working now. Thanks for the quick fix :)
