### ISSUE TITLE
tarball dist extract broken on hhvm

### ISSUE THREAD

**Issue by rk3rn3r** [composer/composer#3773]
hello.

to speed up composer I used to run composer with hhvm (3.5.0 from facebook ubuntu ppa).
now we switched our medusa satis for external packages mirrored to our own servers to provide dist tarballs.
there must be something weird happening when the tarball is extracted with composer running with hhvm, because some directories and it's content are moved to the root of the package directory (under ./vendor/symfony/symfony/). So instead of heaving UPGRADE\*.md files, composer.json and only the src directory there, I have some Tests related directories and classes and some DependencyInjection dirs/classes on the root level, what lead to a broken psr-0/4 autoloading.
Running composer dists install with native PHP 5.4.* is totally fine result.

Very weird. I already checked composer code for something that can go wrong here, but couldn't find it.

Probably I also have to open a ticket on hhvm for this, but I wanted to let you know.

**Comment by Seldaek** [comment]
Closing as it's kinda old and I don't have HHVM to try and reproduce, but if it's still relevant and you have more details to provide to help us fix it please let us know.
