### ISSUE TITLE
Composer violates license term.

### ISSUE THREAD

**Issue by remicollet** [composer/composer#3776]
composer.phar includes various libraries.

For example, from symfony/process license:

     The above copyright notice and this permission notice shall be included in all
     copies or substantial portions of the Software.

But composer.phar doesn't include the LICENSE of each bundled library, which is required by the term of these licenses (MIT or BSD).

**Comment by remicollet** [comment]
Example from PHPUnit:

     # phar list -f /usr/local/bin/phpunit.phar  | grep LIC
     | \-phar:///usr/local/bin/phpunit.phar/doctrine-instantiator/LICENSE
     | \-phar:///usr/local/bin/phpunit.phar/php-code-coverage/LICENSE
     | \-phar:///usr/local/bin/phpunit.phar/php-file-iterator/LICENSE
     | |-phar:///usr/local/bin/phpunit.phar/php-text-template/LICENSE
     | |-phar:///usr/local/bin/phpunit.phar/php-timer/LICENSE
     | |-phar:///usr/local/bin/phpunit.phar/php-token-stream/LICENSE
     | |-phar:///usr/local/bin/phpunit.phar/phpdocumentor-reflection-docblock/LICENSE
     | |-phar:///usr/local/bin/phpunit.phar/phpspec-prophecy/LICENSE
     | \-phar:///usr/local/bin/phpunit.phar/phpunit-mock-objects/LICENSE
     | |-phar:///usr/local/bin/phpunit.phar/sebastian-comparator/LICENSE
     | |-phar:///usr/local/bin/phpunit.phar/sebastian-diff/LICENSE
     | |-phar:///usr/local/bin/phpunit.phar/sebastian-environment/LICENSE
     | \-phar:///usr/local/bin/phpunit.phar/sebastian-exporter/LICENSE
     | |-phar:///usr/local/bin/phpunit.phar/sebastian-global-state/LICENSE
     | \-phar:///usr/local/bin/phpunit.phar/sebastian-recursion-context/LICENSE
     | |-phar:///usr/local/bin/phpunit.phar/sebastian-version/LICENSE
       |-phar:///usr/local/bin/phpunit.phar/symfony/LICENSE

**Comment by Seldaek** [comment]
That was an oversight indeed. Fixed now as far as I can tell.

**Comment by EvanDotPro** [comment]
@Seldaek Nice. I'm clearly [too slow](https://github.com/EvanDotPro/composer/commit/05c365315a58c06ebfff25fb671141377270f812) for this game. :stuck_out_tongue:

**Comment by Seldaek** [comment]
Also you clearly did not test it because the /src in the paths below prevent it from working :P

**Comment by EvanDotPro** [comment]
@Seldaek Guilty. Though, I was going to try it before opening a PR (especially after not seeing unit tests for the Compiler), plus I had to re-clone and update my fork before I could even start!

I was destined to lose.

**Comment by Seldaek** [comment]
Heh ;) Yeah I figured I might as well fix it before people start piling 
up with outrage.

**Comment by remicollet** [comment]
# phar list -f /usr/local/bin/composer.phar  | grep LIC
    |-phar:///usr/local/bin/composer.phar/LICENSE
      |   |-phar:///usr/local/bin/composer.phar/vendor/justinrainbow/json-schema/LICENSE
      |   |-phar:///usr/local/bin/composer.phar/vendor/seld/jsonlint/LICENSE
        |       |-phar:///usr/local/bin/composer.phar/vendor/symfony/console/Symfony/Component/Console/LICENSE
        |       |-phar:///usr/local/bin/composer.phar/vendor/symfony/finder/Symfony/Component/Finder/LICENSE
                |-phar:///usr/local/bin/composer.phar/vendor/symfony/process/Symfony/Component/Process/LICENSE

Fixed.
Thanks.
