### ISSUE TITLE
create an alpha10 version

### ISSUE THREAD

**Issue by schmunk42** [composer/composer#3779]
The support of the caret operator is an important feature IMO (https://github.com/Seldaek/composer/commit/d4523119ea09ab8a063e27836a638d094b7cf3bb)

And I really prefer to stay on an alpha tag than on dev-master.

**Comment by stof** [comment]
:+1:

**Comment by narcoticfresh** [comment]
+1.. 
The caret operator and the `>=0.13 <2` syntax (without comma) both fail in alpha9..  A quick alpha10 would help us a lot..

**Comment by airlanggadurenworks** [comment]
Please consider another tag/checkpoint releases that contains several important feature from master.
I lock composer download to version alpha9 because I need reproducible build with docker.
Living with bleeding edge have hit me several time in the past.

**Comment by hairmare** [comment]
:+1:

**Comment by schmunk42** [comment]
To add two cents more here ... I'd like to see a new alpha tag about every 4 weeks.

**Comment by dlondero** [comment]
I must :+1: this now as caret operator is being used in some libraries and alpha9 does not support that. I can offer some beers for that @Seldaek :)

**Comment by Seldaek** [comment]
It's out at last
