### ISSUE TITLE
Consider consulting plugins in Factory::createDefaultRepositories

### ISSUE THREAD

**Issue by slbmeh** [composer/composer#3783]
Currently a plugin can't register a repository class with the repository manager and have repositories configured in the global config because of the fallback support to get repositories from `Factory::createDefaultRepositories`.

One thing that would need to be addressed is the `InvalidArgumentException` thrown by `RepositoryManager` when the repository type is not registered in the case of being run with `--no-plugins`.  It should probably still be an error when plugins are initialized, but downgraded to a warning when `--no-plugins` is called.

**Comment by slbmeh** [comment]
This might be fixed with #3377 loading the plugins much earlier. A lot of places where it hits the `Factory::createDefaultRepositories` may become dead code if composer is initialized much earlier.

The exception with no plugins, however, will still be present.

**Comment by Seldaek** [comment]
Closing as I don't really think it's a great idea to allow this. We can always revisit once the plugin system permits it of course and if a valid use case comes up.
