### ISSUE TITLE
Non error messages are written to stderr

### ISSUE THREAD

**Issue by cjsewell** [composer/composer#3787]
I think e0ce559 needs to be reviewed. Info messages are written to stderr when they should go to stdout?

**Comment by slbmeh** [comment]
It was an intentional change to allow `stdout` to be more consistent when piping to another application.

**Comment by Seldaek** [comment]
Indeed, as written on the commit, and for reference here to anyone else finding themselves confused by this change, read more at https://github.com/composer/composer/issues/1905#issuecomment-41631659 and https://github.com/composer/composer/pull/3715#issuecomment-73271923 for details.

**Comment by cjsewell** [comment]
Ah OK. Thanks.
