### ISSUE TITLE
'writeError' sending Error messages for non errors

### ISSUE THREAD

**Issue by AlexStansfield** [composer/composer#3792]
I use deployer.org to deploy my code and yesterday deployments stopped working. I've looked into it and it seems to be because of this change in composer:
https://github.com/composer/composer/commit/cb336a5416595efa321c024735e6452c9c7df106

Now pretty much every message is given as an error. Deployer.org sees the error and assumes the composer command failed, rolls back the deployment and sends the error to me.

I can't deploy anything any more because "Loading composer repositories with package information" is seen as an error. 

Deployer.org will download a fresh copy of composer.phar if one is not found in the repo, so pretty much anyone who is using this software with projects that use composer will have been hit by this.

Was the intention of this commit to really make everything an error message or has it been a bit overzealous?

**Comment by slbmeh** [comment]
Duplicates #3787. This was intentional. Output to `stderr` doesn't mean an error message. It's pretty common for unix style applications to display user messages to `stderr` and the basic application output to `stdout`. The proper way to detect if an error has occurred is the exit code. A non zero exit code is an error.

**Comment by slbmeh** [comment]
Looking at the deployer code, it appears https://github.com/deployphp/deployer/blob/dc939056edee6ec7fe9a73fcae568df2c55d5825/src/functions.php#L223-227 may be your issue.  The `runLocally` variant uses `symfony/process` and calls `isSuccessful` which checks the exit code.  The `run` command appears to assume that output means an error if `isDebug` returns true.

**Comment by AlexStansfield** [comment]
Thanks I'll add all of this to the deployer.org issue

**Comment by AlexStansfield** [comment]
Well seems there has been a fix pushed to deployer.org. Sorry for troubling you.

**Comment by slbmeh** [comment]
Can you close the issue please if it is resolved.
