### ISSUE TITLE
Composer update hangs with 100% CPU usage

### ISSUE THREAD

**Issue by SchumacherFM** [composer/composer#3793]
OSX 10.10.2
PHP 5.5.22 from Liip
Composer version 1.0-dev (e5985a9b559747a5f3868361ff26c31818d8c184) 2015-02-25 19:44:34

Out of the blue when running: `$ php composer.phar -vvv update --no-scripts --no-plugins && say "Composer update has been successfully finished!"`

```
...
Updating dependencies (including require-dev)
...
Downloading https://packagist.org/p/provider-latest$272a5f849cf08c246b9ad98e8d077894c21339bc7cdcf43377db0631f6c7a50d.json
...
Downloading http://packagist.org/p/whatthejeff/fab$c9f39b61f51044121927b4e16c694bebb092655582baef9742bb79acfbe248df.json
Writing /Users/xxx/Sites/zzz-releases/.composer/repo/https---packagist.org/provider-whatthejeff$fab.json into cache
```

with the last write to disk composer hangs and CPU load goes up to 100% and never finishes :-(

All caches cleared, etc but always getting the same result :-(

Cannot post here composer.json file.

Would be great if someone knows what is going on or has the same problem :-)

**Comment by slbmeh** [comment]
How long do you consider it hanging? Full CPU sounds to me like the solver is hard at work. What do your dependencies look like in your `composer.json`. Some complex dependency graphs can take 15 minutes or more to resolve the dependencies.

**Comment by CoreTex** [comment]
I have the same problem. Please reopen this issue. It is still an bug. It cannot be that the software is doing nothing and produces 100% load.

**Comment by SchumacherFM** [comment]
Switch to HHVM or PHP7 that may speed up the dependency calculation.

**Comment by vedmant** [comment]
Weird, I'm on php7.2 just upgrading Laravel from 5.5 to 5.6, and composer works already like 10 minutes with 100% cpu load.
