### ISSUE TITLE
ZipDownloader omits directory structures

### ISSUE THREAD

**Issue by t128** [composer/composer#3796]
Hi,

my zip archive looks like this:
- src/MyClassA.php
- src/MyClassB.php

(there is no other file, but the "src" directory)

after installation with the *ZipDownloader*, it looks so:
- vendor/myname/mypackage/MyClassA.php
- vendor/myname/mypackage/MyClassB.php

it should extract to this:
- vendor/myname/mypackage/src/MyClassA.php
- vendor/myname/mypackage/src/MyClassB.php

What causes the autoloader to fail.

**Comment by stof** [comment]
I think this is related to the code handling zip archives where the root is a folder containing the whole repository, as done for github. If there is only a folder, composer will assume that your archive is in this case too.

**Comment by Seldaek** [comment]
Yup that's a known issue with single-dir zip archives. Best solution is to add another file in there like a composer.json which wouldn't hurt to have..
