### ISSUE TITLE
Bad autoload generation in latest version (for symfony components)

### ISSUE THREAD

**Issue by fgreinus** [composer/composer#3797]
I just upgraded from version 825b4b9c63a29c586d005de8dbbcfdfeb86bbf6f to e5985a9b559747a5f3868361ff26c31818d8c184. After that i wanted to update my laravel 4.2 (4.2.16 to 4.2.17) application by using composer update (simply that).

So everything went fine, until I tried to reach the site... this is what the logs say:

> FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'Symfony\Component\Finder\Adapter\AbstractFindAdapter' not found in /var/www/clockin-server/www/vendor/symfony/finder/Symfony/Component/Finder/Adapter/GnuFindAdapter.php on line 25

After rolling back the composer and re-doing autoload generation, everything wents fine.

**Comment by Seldaek** [comment]
If I install symfony/finder 2.6.4 that class autoloads fine with latest composer so I'm gonna need more info here..

**Comment by fgreinus** [comment]
Seems like laravel 4.2 uses symfony/finder 2.5.*
https://github.com/laravel/framework/blob/4.2/composer.json#L31

**Comment by Seldaek** [comment]
OK but still same outcome :)

```
php -r 'include "vendor/autoload.php"; var_dump(class_exists("Symfony\Component\Finder\Adapter\AbstractFindAdapter"));'
bool(true)
```

**Comment by fgreinus** [comment]
Very strange. I'll have a look at this later. Thanks for the feedback so far +1

**Comment by fgreinus** [comment]
Doesn't seem to be reproducable for me... really strange, but without being reproducable this issue won't have sense any more :laughing:
