### ISSUE TITLE
Method signature change

### ISSUE THREAD

**Issue by damien-biasotto** [composer/composer#3800]
Hi,

4 days ago, in commit 3efed220a, we can see you "aliased" `\Composer\Script\PackageEvent` as `\Composer\Installer\PackageEvent` but in the same time, the signature of the constructor drastically changed: new parameters where added but in the middle of the older ones, making it not backward compatible.

Consequences are that externals packages using this class are broken like in there: https://github.com/bragento/bragento-composer-installer/blob/develop/src/Bragento/Magento/Composer/Installer/Deploy/Strategy/AbstractStrategy.php#L278

So what is the solution? Should the externals packages adapt themselves to the new signature or is this a regression?

**Comment by Seldaek** [comment]
Adapting would be a lot better if you can yes, the event stuff was quite messy and I tried to consolidate it and clean up.. Note that some event classes are also marked `@deprecated` so it would be advisable to stop using those.

The question is why you are dispatching such events at all though :) I wouldn't really consider it public API for composer, but I am curious to know exactly what's going on.

**Comment by damien-biasotto** [comment]
I will let @davidverholen explain it :)

**Comment by davidverholen** [comment]
we decided to make the whole deployment of files in the after install event for some different reasons.

I dispatched the Events there to get some Access Points and more flexibility

**Comment by Seldaek** [comment]
Ok but maybe it'd be best to use your own events names and maybe even classes then? That would make it more robust over time I guess.

**Comment by davidverholen** [comment]
I did use own event names.
I also made an own event class now.
Thanks for the help!

**Comment by Seldaek** [comment]
Ah ok I missed that fact, well great then I hope this can be marked resolved :)
