### ISSUE TITLE
composer self-update writes "You are already using composer version ...." to stderr

### ISSUE THREAD

**Issue by onnomarsman** [composer/composer#3808]
I'm using a cron job to do a composer self-update but the cron sends me e-mails every day telling me:

"You are already using composer version ...."

I could redirect stderr to /dev/null but then I also wouldn't get any emails when the command would produce actual errors.
I feel that this particular message is no error, and just a potential valid result of the self-update command, so, in my opinion, it should be written to stdout.

**Comment by stof** [comment]
stderr is not only about reporting errors. It is about reporting information meant for humans while stdout is for the output of the command (something you would pass to the next program). See the discussion in https://github.com/composer/composer/issues/3787

**Comment by dzuelke** [comment]
I wonder though if "updating to version ..." should be written to stdout, or a separate "Updated from $oldversion to $newversion" message. Ping @alcohol.

**Comment by alcohol** [comment]
I am on vacation, so feel free to pick it up. Otherwise I'll have a looksie
when I get back :-)

**Comment by onnomarsman** [comment]
So how should I put this in a cron so it only emails me when a real error occurs?
With any other command it's ok to just put > /dev/null behind it. And I thought this is the normal way to do it.
An alternative might be to add some command line option to only produce output when errors occur.

**Comment by stof** [comment]
@onnomarsman use the exit code to detect failures, not the output

**Comment by dzuelke** [comment]
@onnomarsman Messages on `stderr` do not mean an error occurred. Take e.g. any "curl ... > file" command which will send the downloaded contents to stdout (piped to `file`) and write a progress bar to `stderr`.

Use the exit status of the command instead (available in `$?` after the command has finished, or you do e.g. `composer self-update || { echo "update failed"; exit 1; }`. There are plenty of tutorials on Unix pipelines and status codes around the Internets if you need help with it.

**Comment by onnomarsman** [comment]
Ok, I understand. I guess the term stderr is a bit misleading then. Thanks for the suggestion.

**Comment by stof** [comment]
@onnomarsman bash scripting does not call it stderr AFAIK

**Comment by Luke-Wang** [comment]
My problem is every time when I use composer command, it says "warning this development build of composer is over 60 days old", but when I self-update it's like "this development build of composer is over 60 days old" , what the hell !

**Comment by alcohol** [comment]
Insufficient information, cannot help.
