### ISSUE TITLE
composer clear-cache not working

### ISSUE THREAD

**Issue by cerberus478** [composer/composer#3810]
When I try to use composer clear-cache at the end I get "Cache directory does not exist (cache-vcs-dir)"

**Comment by stof** [comment]
Well, it is just an info message telling you that this folder did not exist at all, and so there was nothing to do to clear. It does not mean that it does not work.
The message might be confusing though.

**Comment by cerberus478** [comment]
Then how do I get it working. Because I need to clear it to test something, so I don't know any other way to clear it

**Comment by stof** [comment]
hmm, there is indeed a weird code here. @Seldaek any reason to return from the command when 1 one of the cache paths does not exist ?

**Comment by Seldaek** [comment]
Nope this seems kinda silly. I'll fix.

**Comment by Seldaek** [comment]
Ok should work after a composer self-update
