### ISSUE TITLE
I am integrating stripe payment api 

### ISSUE THREAD

**Issue by Faheem1234** [composer/composer#3812]
Fatal error: Class 'Stripe_Charge' not found in E:\xampp\htdocs\strip_payment\testStrip.php on line 92

**Comment by Faheem1234** [comment]
I am trying to integrate stripe  throughout PHP i found this sort of issue so if any body have solution please provide me that solution i will be thankful for that

**Comment by dzuelke** [comment]
Hello @Faheem1234,

This is the issue tracker for the Composer project, not a support forum for problems with packages installed through Composer.

Thank you.

P.S. you probably want `Stripe\Charge`. Please read the usage info at https://github.com/stripe/stripe-php and the docs.

**Comment by Faheem1234** [comment]
Hello@dzuelke
I have downloaded this api's files menualy so should i install this api by using composer..?

**Comment by Faheem1234** [comment]
i have installed latest api packages and followed by all the steps 
Fatal error: Class 'Stripe' not found in E:\xampp\htdocs\Teststripe\test.php on line 4
this error is showing on browser what would be solution of this sort of problem

**Comment by stof** [comment]
@Faheem1234 ask support to the maintainers of the package you are using, not to the composer team. This is not a general support forum about PHP packages.

Btw, if you installed the package manually instead of using composer, you will have to register the autoloading manually too.

**Comment by Faheem1234** [comment]
@stof i have install composer which command line should i pass in composer by which this api start to download in system?

**Comment by xabbuh** [comment]
@Faheem1234 I suggest to read the [Composer documentation](https://getcomposer.org/doc/) if you want to learn how to manage your dependencies with Composer.

**Comment by Faheem1234** [comment]
OK thanks allot i have successfully integrated stripe with my app
