### ISSUE TITLE
RFC: Asking for a revert

### ISSUE THREAD

**Issue by jails** [composer/composer#3815]
The following commit introduces some confusions (for me at least) on how Composer output should be parsed: https://github.com/composer/composer/commit/cb336a5416595efa321c024735e6452c9c7df106

Indeed now Composer use stderr to display, info, warning, error, as well as regular message which seems unconsistent.

The one I'm more concerned about is [the following one](https://github.com/composer/composer/blob/cb336a5416595efa321c024735e6452c9c7df106/src/Composer/Installer.php#L517).

Ansible is looking for this [specific ouput in stdout](https://github.com/ansible/ansible-modules-extras/blob/devel/packaging/language/composer.py#L104) to check if something new as been installed or not.

So I wanted to know if there's some outputing "logic/strategy" behind this recent commit change so I can rely on it to fix the Ansible composer module ?

**Comment by xabbuh** [comment]
@jails I think you can best start with reading https://github.com/composer/composer/issues/3787#issuecomment-76167739 (and the referenced comments).

**Comment by jails** [comment]
Thanks for the head up @xabbuh
