### ISSUE TITLE
Regression: run-script and composer-test no longer includes "vendor/bin"

### ISSUE THREAD

**Issue by Krinkle** [composer/composer#3820]
I updated from 1.0.0-alpha9 825b4b9c63a29c586d005de8dbbcfdfeb86bbf6f to b8ac790b4f2db1f718e640015636f005401c1c71 today and most project builds are failing due to `vendor/bin` no longer being part of the subshell path that `composer run-script` and `composer test` use.

Code like the following worked for over a year until this week:
```json
{
	"require-dev": {
		"jakub-onderka/php-parallel-lint": "0.8.*",
		"phpunit/phpunit": "3.7.*",
		"squizlabs/php_codesniffer": "1.*"
	},
	"scripts": {
		"test": [
			"parallel-lint --exclude vendor .",
			"phpunit",
			"phpcs . --standard=./test/codesniffer --ignore=vendor/* --tab-width=4"
		]
	}
}
```
Affecting local builds, Jenkins, and Travis CI. Afaik this is documented behaviour according to https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands. And matches npm's behaviour (https://docs.npmjs.com/misc/scripts#path) which I imagine its inspired by..

**Comment by legoktm** [comment]
git bisect points to be22a87d9cf64895e96ea12b3aee89c1d282e520.

**Comment by Seldaek** [comment]
Thanks for the diagnosis @legoktm, allowed me to get what went wrong immediately. It's now fixed.
