### ISSUE TITLE
disable downloading all packages' json while "composer update/require/remove particular/package"

### ISSUE THREAD

**Issue by wppd** [composer/composer#3821]
When update/require/remove a particular package, composer will  always download all packages' json files. 

For me, this behavior doesn't make sense. It should just check out the dependencies of that particular package, right?

Is there an option to disable such behavior?

I know, this isn't an issue for you guys. But it's a big deal for people living in China....

**Comment by slbmeh** [comment]
That's how it discovers the available versions of the packages that you are updating/requiring.

**Comment by wppd** [comment]
@slbmeh 

I know there are some json files containing all packages meta data.

But I mean, all packages I've installed in my box:

for example:
Downloading http://packagist.org/p/guzzlehttp/streams$920e9591cfc08af64c3b2453eae8b3cd561eed19f8556ea0d0aaab6dc62e3f03.json
Downloading http://packagist.org/p/illuminate/workbench$7440fe941c62b5b72fa3908fd18e2d7cd49d82dad313399b6ab01f4f23c1bda3.json

If I want to remove a package that doesn't have any dependency, why it needs to download those files?

**Comment by stof** [comment]
@wppd because the optimization suggested in #3672 is not implemented yet.

@Seldaek @naderman this issue should be closed as duplicate

**Comment by wppd** [comment]
@stof thanks for your info.
