### ISSUE TITLE
Support autoloading enums in Hack code

### ISSUE THREAD

**Issue by fredemmott** [composer/composer#3823]
eg:

```Hack
<?hh

enum Foo: int {
  BAR = 1;
  BAZ = 2;
}
```

Hack Enums are syntactic sugars around classes, and can be autoloaded like classes via spl_autoload_register() (or HH\autoload_set_paths)

Tokens are T_ENUM (388) followed by T_STRING (class name)

**Comment by stof** [comment]
is it about the classmap generator or the classloader itself (i.e. does it work already for PSR-0 or PSR-4 autoloading) ?

**Comment by fredemmott** [comment]
Classmap generator. When it's being loaded, it's identical to a class, so should already work for PSR0/4.

**Comment by stof** [comment]
This would be a matter of updating the regex on https://github.com/composer/composer/blob/b80038804ff791a9d4608d737ad937b6033b0bae/src/Composer/Autoload/ClassMapGenerator.php#L157 to add ``|enum`` on HHVM (similar to the way traits are added on PHP 5.4+)
