### ISSUE TITLE
Windows artifacts problem

### ISSUE THREAD

**Issue by financedemo** [composer/composer#3832]
Our team consists of both windows and linux machines. We use artifacts to store some dependencies.
We download the artifacts to a folder and then run ```composer update```. In linux machines composer.lock is generated correctly with correct paths to artifacts e.g. ```app/artifacts/some_artifact.zip``` but when they are generated from windows the path is ```app/artifacts\\some_artifact.zip``` and linux machines have a problem finding the artifacts.
I do not know if its a bug or not but if there is a solution please suggest one.

**Comment by jakoch** [comment]
Can not reproduce :) Please provide more details.

Are you using some custom installer or script triggered via `post-install-cmd` or `post-package-install`, which handles the "artifact install"? Does your `composer.json` contain a script execution, which might cause this?

**Comment by financedemo** [comment]
we have only symfony post install scripts

we have configured
```
"repositories": [
        {
            "type": "artifact",
            "url" : "app/artifacts"
        }
],
```

If, in linux, I download artifacts and install them then the composer.lock file is correct.
Once the artifacts are installed/updated in windows the composer.lock shows invalid path and artifacts cannot be autoloaded
