### ISSUE TITLE
Windows installer behind firewall won't pull from https://getcomposer.org

### ISSUE THREAD

**Issue by cornelison** [composer/composer#3833]
Our Windows 7 PC behind our corporate firewall.
We usually have no problems with https pulls -- with Windows env. variables set for:
HTTP_PROXY= ... 
HTTPS_PROXY= ... 

Not sure what else can remedy this problem!

The Composer  *.msi is failing with a download error: 

Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Cannot connect to HTTPS server through proxy
Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Cannot connect to HTTPS server through proxy
Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Cannot connect to HTTPS server through proxy
The download failed repeatedly, aborting.

**Comment by jakoch** [comment]
Hey Lee,

please take a look at your `php.ini` and make sure that the paths to your SSL certs are defined.
Something like this should do it:
```
curl.cainfo=c:\full\path\to\ssl\certs\ca-bundle.crt
openssl.cafile=c:\full\path\to\ssl\certs\ca-bundle.crt
```

Then try again `curl -sS https://getcomposer.org/installer | php`.
If this doesn't resolve the issue, please post your PHP version and the openssl info from `php -i`.

**Comment by cornelison** [comment]
Added certs path -- but curl still won't resolve SSL certs.  

Do I need a CA from composer.org on my WIndows box?


CORNELISON@MM202831-PC /c/Program Files (x86)/Drush/Php
$ curl   -sS   https://getcomposer.org/installer  | php
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.






-----------------------------------------------------------------------------------------------------------------
CORNELISON@MM202831-PC /c/Program Files (x86)/Drush/Php
$ pwd
/c/Program Files (x86)/Drush/Php

CORNELISON@MM202831-PC /c/Program Files (x86)/Drush/Php
$ ./php.exe  -version
PHP 5.3.6 (cli) (built: Mar 17 2011 10:48:37)
Copyright (c) 1997-2011 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2011 Zend Technologies

CORNELISON@MM202831-PC /c/Program Files (x86)/Drush/Php
$

CORNELISON@MM202831-PC /c/Program Files (x86)/Drush/Php
$ tail  php.ini
extension=php_pdo_sqlite.dll
extension=php_imap.dll
extension=php_tidy.dll

extension=php_pdo_sqlsrv.dll

extension=php_sqlsrv.dll
; Add SSL support per composer Tech Support
curl.cainfo=C:\Users\cornelison\curl-ca-bundle.crt
openssl.cafile=C:\Users\cornelison\curl-ca-bundle.crt

**Comment by jakoch** [comment]
Thank you. 
It looks like the openssl extension is not loaded. Please add `extension=php_openssl.dll` to `php.ini`.
If it's really the cert, then fetch this one: http://curl.haxx.se/ca/cacert.pem

**Comment by cornelison** [comment]
Hi, still trying to complete a windows install through a corporate proxy server.

1.  downloaded .pem file from curl.haxx.se

2.  updated php.ini; checked php.ini 

extension=php_openssl.dll
extension=php_curl.dll
; Add SSL support per composer Tech Support
;curl.cainfo=C:\Users\cornelison\curl-ca-bundle.crt
;openssl.cafile=C:\Users\cornelison\curl-ca-bundle.crt
curl.cainfo=C:\Users\cornelison\cacert.pem
openssl.cafile=C:\Users\cornelison\cacert.pem


 3.  Tried install via curl ....

$ ping  getcomposer.org

Pinging getcomposer.org [87.98.253.108] with 32 bytes of data:
Reply from 87.98.253.108: bytes=32 time=448ms TTL=47
Reply from 87.98.253.108: bytes=32 time=431ms TTL=47
Reply from 87.98.253.108: bytes=32 time=360ms TTL=47


cornelison@MM202831-PC ~
$ php -i  |grep openssl
openssl

cornelison@MM202831-PC ~
$ curl   -sS  https://getcomposer.org/installer | php
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

cornelison@MM202831-PC ~
$ curl   -k  https://getcomposer.org/installer | php
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 48919    0 48919    0     0  24301      0 --:--:--  0:00:02 --:--:-- 24301
curl: (23) Failed writing body (233 != 16384)

cornelison@MM202831-PC ~
$

**Comment by slbmeh** [comment]
Just passing by, could the `SSL3_GET_SERVER_CERTIFICATE` piece indicate an outdated version of curl/libcurl/php_curl? SSL3 is phased out most places because of poodle.

**Comment by jakoch** [comment]
Yes, Steve, the PHP version used is 5.3.6 from 2011.
cURL is probably outdated, too, when even `curl -k` isn't working.
Hopefully the error vanishes after updating PHP, cURL (and maybe OpenSSL).

**Comment by cornelison** [comment]
I am taking from your side-conversation that I should not be using an older PHP 5.3.x when installing Composer on Windows ....   meaning the Composer posted instructions are outdated & misleading?

https://getcomposer.org/doc/00-intro.md#installation-windows

 "System Requirements#

  Composer requires PHP 5.3.2+ to run. A few sensitive php settings and compile flags are also required, but when using the installer you will be warned about any incompatibilities."

**Comment by slbmeh** [comment]
5.3.2 is the bare minimum requirement, but is a very old version. Composer should work with it, but I believe the issue is that other parts of the internet won't work with it. Many security fixes and bug patches have occurred since 5.3.6. The wide spread fix POODLE in particular killed SSL3, and your curl implementation is trying to use it. TLS has surpassed SSL for quite a few years, and now has completely replaced it. You should upgrade your curl implementations to protect yourself against it, if you prefer to leave the hole there... you at least need a version that can negotiate an SSL handshake with servers that have patched for the CVE.

**Comment by vukanac** [comment]
Similar problem with SSL "unable to get local issuer certificate"... was solved by putting

    [curl]
    curl.cainfo = "d:/wamp/bin/php/php5.5.12/cacert.pem"

in file `d:\wamp\bin\apache\apache2.4.9\bin\php.ini`.
Note forward slash!

**Comment by RishiKulshreshtha** [comment]
That's exactly the same issue I'm facing. While installing the Composer Installer on my Windows 7 machine I'm getting the below error:
```
The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
```
Tried this:
```
$ curl -sS https://getcomposer.org/installer | php
stdin is not a tty
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```
And this:
```
$ ping getcomposer.org

Pinging getcomposer.org [87.98.253.108] with 32 bytes of data:
Reply from 87.98.253.108: bytes=32 time=137ms TTL=47
Reply from 87.98.253.108: bytes=32 time=127ms TTL=47
Reply from 87.98.253.108: bytes=32 time=127ms TTL=47
Reply from 87.98.253.108: bytes=32 time=127ms TTL=47

Ping statistics for 87.98.253.108:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 127ms, Maximum = 137ms, Average = 129ms
```
My PHP version is:
```
$ php -v
PHP 5.5.37 (cli) (built: Jun 22 2016 16:14:46)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```
I've enabled the following list in my php.ini:
```
extension=php_curl.dll
extension=php_openssl.dll
curl.cainfo="C:/xampp/php/extras/certs/cacert.pem"
openssl.cafile="C:/xampp/php/extras/certs/cacert.pem"
```
Where I've downloaded the cacert.pem from https://curl.haxx.se/ca/cacert.pem

**Comment by ayvarot** [comment]
I successfully used the same config as @RishiKulshreshtha except for the cacert that was from my corporation:
```
[PROXY]
; include the lines below in your php.ini
extension=php_curl.dll
extension=php_openssl.dll
curl.cainfo = corporate-cacert.crt
openssl.cafile= corporate-cacert.crt
```
Notes:
- I got my corporate-cacert.crt downloading it using the browser (green lock icon).
- I used encodeURIComponent('my password with special characters') from browser's console to get the encoded password to use in the "http://user:password@IP:port/" proxy string.

My env:
```
λ php --version
PHP 7.3.5 (cli) (built: May  1 2019 13:16:56) ( NTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans
```
```
λ systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 7 Professional
OS Version:                6.1.7601 Service Pack 1 Build 7601
```
