### ISSUE TITLE
Can't update with composer

### ISSUE THREAD

**Issue by LeoLR** [composer/composer#3834]
Hi,

First, sorry for my english. 
I start to work with Symfony and i've some problem with Composer and the http connectivity...
I've found a lot of topic about problems like mine but ... 
When i write "php composer.phar diag" we can see this: 

![new issue composercomposer - google chrome](https://cloud.githubusercontent.com/assets/10087588/6593080/543474b6-c7d5-11e4-8a81-f07fe3db85de.jpg)

I've try to fix the problem with the command "set http_proxy" and configure the git proxy but it doesn't work... 

And when i try to update a test project, i've this error:

![mingw32cwampwwwtest](https://cloud.githubusercontent.com/assets/10087588/6593157/eeabfdfc-c7d5-11e4-9bc9-abe8205c9f5d.jpg)

I hope you can help me :+1: 

Bye

**Comment by stof** [comment]
Looks like you have a network issue (and looks like there is a bug in the DiagnoseCommand in such case)

**Comment by LeoLR** [comment]
How can i fix it?
