### ISSUE TITLE
Composer <any_command> fopen() error

### ISSUE THREAD

**Issue by alexandrupetrescu94** [composer/composer#3835]
I installed composer from composer-setup (Windows), with the php.exe(5.5.12) from a wamp server (D:\) and he generated me the paths and everything. But when i try any command this fopen appears.
When I create a new project it downloads the laravel/laravel and after that it says the same thing.
```
[ErrorException]
 fopen(): Filename cannot be empty
```
When I try diagnose platform fails and then:
```
Checking git settings:
  [ErrorException]
  fopen(): Filename cannot be empty
```
Anyone knows what is the problem here? Thank you.

It's not my first time using composer, I had it before but I uninstalled because he throwed me every time I updated composer on my project the auth credentials for packagist (needed for doctrine inflector). And I thought it's my configuration problem. I deleted the paths after uninstalling.

**Comment by sstok** [comment]
Please run composer with `-vvv` so you get the full exception stack which makes it easier to debug.
like: `composer diagnose -vvv`

**Comment by alexandrupetrescu94** [comment]
``` Exception trace:
 () at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/proc
ess/Symfony/Component/Process/Pipes/WindowsPipes.php:55
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 fopen() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony
/process/Symfony/Component/Process/Pipes/WindowsPipes.php:55
 Symfony\Component\Process\Pipes\WindowsPipes->__construct() at phar://C:/Progra
mData/ComposerSetup/bin/composer.phar/vendor/symfony/process/Symfony/Component/P
rocess/Pipes/WindowsPipes.php:172
 Symfony\Component\Process\Pipes\WindowsPipes::create() at phar://C:/ProgramData
/ComposerSetup/bin/composer.phar/vendor/symfony/process/Symfony/Component/Proces
s/Process.php:1263
 Symfony\Component\Process\Process->getDescriptors() at phar://C:/ProgramData/Co
mposerSetup/bin/composer.phar/vendor/symfony/process/Symfony/Component/Process/P
rocess.php:275
 Symfony\Component\Process\Process->start() at phar://C:/ProgramData/ComposerSet
up/bin/composer.phar/vendor/symfony/process/Symfony/Component/Process/Process.ph
p:208
 Symfony\Component\Process\Process->run() at phar://C:/ProgramData/ComposerSetup
/bin/composer.phar/src/Composer/Util/ProcessExecutor.php:62
 Composer\Util\ProcessExecutor->execute() at phar://C:/ProgramData/ComposerSetup
/bin/composer.phar/src/Composer/Command/DiagnoseCommand.php:154
 Composer\Command\DiagnoseCommand->checkGit() at phar://C:/ProgramData/ComposerS
etup/bin/composer.phar/src/Composer/Command/DiagnoseCommand.php:79
 Composer\Command\DiagnoseCommand->execute() at phar://C:/ProgramData/ComposerSe
tup/bin/composer.phar/vendor/symfony/console/Symfony/Component/Console/Command/C
ommand.php:253
 Symfony\Component\Console\Command\Command->run() at phar://C:/ProgramData/Compo
serSetup/bin/composer.phar/vendor/symfony/console/Symfony/Component/Console/Appl
ication.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/ProgramData/
ComposerSetup/bin/composer.phar/vendor/symfony/console/Symfony/Component/Console
/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar://C:/ProgramData/Compose
rSetup/bin/composer.phar/src/Composer/Console/Application.php:147
 Composer\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bi
n/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php
:126
 Symfony\Component\Console\Application->run() at phar://C:/ProgramData/ComposerS
etup/bin/composer.phar/src/Composer/Console/Application.php:84
 Composer\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/
composer.phar/bin/composer:43
 require() at C:\ProgramData\ComposerSetup\bin\composer.phar:25 ```

**Comment by stof** [comment]
Getting an empty filename here is weird.

Can you run the following command and paste the output ?

```
php -r "var_dump(tempnam(sys_get_temp_dir(), 'sf_proc_stdout'));"
```

**Comment by alexandrupetrescu94** [comment]
bool(false) - it sounds like a problem :-<

**Comment by alexandrupetrescu94** [comment]
I solved it. There was a Path change, I don't know why. They var_dump still was in error but the composer works. Thank you for helping me with this tips!

**Comment by ashnazg** [comment]
@stof 's tempdir question helped me solve this issue, where I saw the same symptom, but *only* when composer was executed by a local user via a Jenkins job.  Running composer as the user directly in a shell would succeed, as would running composer via ant via shell.

Setting an explicit sys_temp_dir in php.ini solved the issue.  Since my searches for the symptoms brought me only to this issue#, I hope this extra info proves helpful.

**Comment by rowanrh** [comment]
@ashnazg :thanks for your solution - after reading it I discovered that the sys_temp_dir entry was pointing to a missing directory <sigh> 

One day wasted - my bad - but at least Composer is now working !

**Comment by stof** [comment]
@ashnazg when there is no explicit config, PHP relies on env variables to detect the temp dir. Your shell might have this env variable while the Jenkins job does not

**Comment by thasneemilm** [comment]
@rowanrh 
can you please tel me waht should i do sys_temp_dir entry?

**Comment by rowanrh** [comment]
1. Create a temporary directory e.g. [in Windows] C:\Temp;
2. Point to sys_temp_dir entry in php.ini to the temporary directory e.g. sys_temp_dir=C:\Temp

That's it !

**Comment by thasneemilm** [comment]
@rowanrh 
ya worked, really thanks :)

**Comment by rowanrh** [comment]
I'm glad to have been able to assist.

Go well
