### ISSUE TITLE
Show a list of all dependencies

### ISSUE THREAD

**Issue by evert** [composer/composer#3836]
It would be nice if I could ask composer to give me a list of all dependencies and their version constraint, including system packages.

This would allow me for example quickly find out what the minimum PHP version is based on what every package needs.

This can be either considered a feature request or a support question =)

**Comment by jakoch** [comment]
You might be looking for the CLI command `show` - https://getcomposer.org/doc/03-cli.md#show

- `composer show --platform` - lists your platform/env = PHP + Extensions
- `composer show --installed` - lists your platform/environment on top of all available packages
- `composer show --self` - basically the output of composer.json of your project
   - see `require` section, `php`
- `composer show monolog/monolog` - package details
- `composer show monolog/monolog 1.2.3` - package details (specific version)

**Comment by evert** [comment]
None of that does what I asked.

I would like to see a list of actual dependencies plus their version constraints, `composer show` just shows how those dependencies were resolved.

To reiterate an example of an actual use-case:

> This would allow me for example quickly find out what the minimum PHP version is based on what every package needs.

**Comment by Seldaek** [comment]
The best I got is this.. it's not absolutely safe because it doesn't only look at lines in require, but it's pretty close:

```
$ for pkg in `composer show -i --name-only`; do composer show -i $pkg | grep 'php '; done
php >=5.3.2
php >=5.3,<8.0-DEV
php >=5.3.2
php >=5.3.3
...
```

**Comment by evert** [comment]
That does help =) thnx

**Comment by XedinUnknown** [comment]
I would like to see this functionality too. I'm using the [`composer-merge-plugin`](https://github.com/wikimedia/composer-merge-plugin) which is basically a critical part of my solution. I need to see a list of all dependencies, including those merged. But even without the plugin, it would be very useful to get a list of dependencies, and their version constraints. Also, this would help me resolve issue #4497.

**Comment by XedinUnknown** [comment]
To be honest, I would like to see more options of getting structured output in a machine-readable format. Besides allowing other CLI utilities to use Composer output, it would also make the creation of a web interface possible.

**Comment by Seldaek** [comment]
In any case, this isn't very hard to implement, the main question is how to define the interface, I'd rather not have a command that only lists dependencies otherwise we end up with a million commands, having a good generic interface to query this data would be nice. Someone has to spend the work to think and spec it out though.

**Comment by XedinUnknown** [comment]
Sure.

Currently, useful information is normally extracted using the `show` command. A `-d` or `--dependencies` flag could be added to it, which would meant that the command is meant to show dependencies. `-d` is different from `-r`, which commonly means "recursion", so it will help to avoid confusion.

Also, an `-o` or `--output` (or maybe `--output-type`) could be added as a generic flag. For supported command+flag combinations, it could mean the type of output to generate. It could have the default value of `human`. Another possible value `json` could be added, which would mean that the output generated will be in a structured format, specifically JSON. This could serve as a good basis for plugins to add their own output formats.

Neither of these command+flag combinations are currently documented, so I assume they are not used.

**Comment by Seldaek** [comment]
The --tree arg for show command kinda helps with this: `composer show -i -t | grep php` is simpler and has no risk of showing irrelevant stuff. I'm not sure if it can be considered enough, but I don't know if we really want to do much more there. @gomboc do you have an example of your PR's output vs a --tree? Is it really worth adding the code?

**Comment by gomboc** [comment]
```composer show -i -t | grep php``` will produce:
```ssh
$ composer show -i -t | grep php
`--php ^5.3.2 || ^7.0
`--php >=5.3.2
`--php >=5.3.2
`--php >=5.3
`--php ^5.3 || ^7.0
`--php >=5.3
`--php >=5.3.9
`--php >=5.3.9
`--php >=5.3.9
`--php >=5.3.9
phpunit/phpunit-mock-objects 2.3.0 Mock Object library for PHPUnit
|  `--php >=5.3,<8.0-DEV
|--php >=5.3.3
`--phpunit/php-text-template ~1.2
   `--php >=5.3.3
phpunit/phpunit 4.8.16 The PHP Unit Testing framework.
|--php >=5.3.3
|--phpspec/prophecy ^1.3.1
|  |  `--php >=5.3,<8.0-DEV
|  |--phpdocumentor/reflection-docblock ~2.0
|  |  `--php >=5.3.3
|     |--php >=5.3.3
|     |  `--php >=5.3.3
|        |--php >=5.3.3
|           `--php >=5.3.3
|--phpunit/php-code-coverage ~2.1
|  |--php >=5.3.3
|  |--phpunit/php-file-iterator ~1.3
|  |  `--php >=5.3.3
|  |--phpunit/php-text-template ~1.2
|  |  `--php >=5.3.3
|  |--phpunit/php-token-stream ~1.3
|  |  `--php >=5.3.3
|  |  `--php >=5.3.3
|--phpunit/php-file-iterator ~1.4
|  `--php >=5.3.3
|--phpunit/php-text-template ~1.2
|  `--php >=5.3.3
|--phpunit/php-timer >=1.0.6
|  `--php >=5.3.3
|--phpunit/phpunit-mock-objects ~2.3
|  |  `--php >=5.3,<8.0-DEV
|  |--php >=5.3.3
|  `--phpunit/php-text-template ~1.2
|  |--php >=5.3.3
|  |  `--php >=5.3.3
|     |--php >=5.3.3
|        `--php >=5.3.3
|  `--php >=5.3.3
|  `--php >=5.3.3
|  |--php >=5.3.3
|     `--php >=5.3.3
|  `--php >=5.3.3
   `--php >=5.3.9
```

```composer show -c``` will produce
```ssh
php                               >=5.3.9        symfony/yaml
ext-tokenizer                     *              phpunit/php-token-stream
sebastian/recursion-context       ~1.0           sebastian/exporter
sebastian/diff                    ~1.2           phpunit/phpunit
sebastian/exporter                ~1.2           phpunit/phpunit
doctrine/instantiator             ^1.0.2         phpspec/prophecy
phpunit/php-text-template         ~1.2           phpunit/phpunit
phpunit/php-file-iterator         ~1.4           phpunit/phpunit
phpunit/php-token-stream          ~1.3           phpunit/php-code-coverage
sebastian/environment             ^1.3.2         phpunit/php-code-coverage
sebastian/version                 ~1.0           phpunit/phpunit
phpdocumentor/reflection-docblock ~2.0           phpspec/prophecy
sebastian/comparator              ~1.1           phpunit/phpunit
ext-dom                           *              phpunit/phpunit
ext-json                          *              phpunit/phpunit
ext-pcre                          *              phpunit/phpunit
ext-reflection                    *              phpunit/phpunit
ext-spl                           *              phpunit/phpunit
phpspec/prophecy                  ^1.3.1         phpunit/phpunit
phpunit/php-code-coverage         ~2.1           phpunit/phpunit
phpunit/php-timer                 >=1.0.6        phpunit/phpunit
phpunit/phpunit-mock-objects      ~2.3           phpunit/phpunit
sebastian/global-state            ~1.0           phpunit/phpunit
symfony/yaml                      ~2.1|~3.0      phpunit/phpunit
```

It will produce list of all dependencies and their minimum required versions.

**Comment by gomboc** [comment]
Maybe it's worth considering :)

**Comment by evert** [comment]
`--tree` is awesome! From my perspective this ticket may be closed!

**Comment by XedinUnknown** [comment]
`--tree` requires a more complicated, custom logic to parse its output.

With regard to the `-c` option output, am I correct in assuming that the columns are "Dependency", "Dependency Version" and "Dependent Library", in this order? If so, then I like it.

On the other hand, the output of `--tree` is much more comprehensive and structured. Although, I don't know what the below is:

```
|  |--phpdocumentor/reflection-docblock ~2.0
|  |  `--php >=5.3.3
|     |--php >=5.3.3
|     |  `--php >=5.3.3
|        |--php >=5.3.3
|           `--php >=5.3.3
```

To me, looks like unnormalized dependencies. If they were normalized, and in a more machine-readable format (e.g. JSON), this would be the solution.

Also, with regard to both solutions, do they reflect the actual state of the dependencies, or only what's written in `composer.json`?

**Comment by stof** [comment]
@XedinUnknown this is a partial output of the tree, as you applied grep on it. This is why it looks a bit weird

**Comment by gomboc** [comment]
@XedinUnknown you are right about the columns (dependency, dependency version, dependent library)

Upgrade could be to display more dependent libraries if the certain dependency can be found in more than one library, or maybe the third column is unnecessary.

The code for `-c` is extracted from ShowCommand to a new class, and the output can be exported easy to json, xml, html .....  with `--output-type` / `--output` parameter.

**Comment by Seldaek** [comment]
I actually saw that it's pretty easy to tweak the `depends` command so that you can do this for example:

```
$ composer depend php
composer/composer requires php (^5.3.2 || ^7.0)
composer/semver requires php (^5.3.2 || ^7.0)
composer/spdx-licenses requires php (>=5.3.2)
doctrine/instantiator requires php (>=5.3,<8.0-DEV)
justinrainbow/json-schema requires php (>=5.3.2)
phpdocumentor/reflection-docblock requires php (>=5.3.3)
phpunit/php-code-coverage requires php (>=5.3.3)
phpunit/php-file-iterator requires php (>=5.3.3)
phpunit/php-text-template requires php (>=5.3.3)
phpunit/php-timer requires php (>=5.3.3)
phpunit/php-token-stream requires php (>=5.3.3)
phpunit/phpunit-mock-objects requires php (>=5.3.3)
phpunit/phpunit requires php (>=5.3.3)
sebastian/comparator requires php (>=5.3.3)
sebastian/diff requires php (>=5.3.3)
sebastian/environment requires php (>=5.3.3)
sebastian/exporter requires php (>=5.3.3)
sebastian/global-state requires php (>=5.3.3)
sebastian/recursion-context requires php (>=5.3.3)
seld/cli-prompt requires php (>=5.3)
seld/jsonlint requires php (^5.3 || ^7.0)
seld/phar-utils requires php (>=5.3)
symfony/console requires php (>=5.3.9)
symfony/filesystem requires php (>=5.3.9)
symfony/finder requires php (>=5.3.9)
symfony/polyfill-mbstring requires php (>=5.3.3)
symfony/process requires php (>=5.3.9)
symfony/yaml requires php (>=5.3.9)
...
```

It's a better way IMO, no grepping, and it target dependents while show targets packages and optionally shows what they require.

**Comment by nrctkno** [comment]
> 
> 
> It would be nice if I could ask composer to give me a list of all dependencies and their version constraint, including system packages.
> 
> This would allow me for example quickly find out what the minimum PHP version is based on what every package needs.
> 
> This can be either considered a feature request or a support question =)

I know this issue is old and closed, but had to deal with the same situation and made this gist in PHP: https://gist.github.com/nrctkno/ecaa664305b3fd8b0c86128d99056255 . You need the composer.lock file to list the dependencies.

**Comment by cgmafia** [comment]
If you are installing Composer, here is the list for macosx
Fetching dependencies for composer: apr, openssl@1.1, apr-util, libnghttp2, pcre2, httpd, argon2, aspell, m4, autoconf, gettext, libidn2, libssh2, openldap, rtmpdump, cmake, lz4, xz, zstd, curl, libtool, unixodbc, freetds, libpng, freetype, mpdecimal, readline, sqlite, libffi, python, fontconfig, nasm, jpeg-turbo, bison, berkeley-db, gdbm, perl, help2man, flex, doxygen, python@3.11, docutils, pygments, sphinx-doc, giflib, highway, imath, libtiff, little-cms2, openexr, webp, jpeg-xl, ninja, meson, libvmaf, yasm, aom, libavif, gd, gmp, icu4c, krb5, libpq, libsodium, libzip, automake, oniguruma, tidy-html5 and php
