### ISSUE TITLE
Feature to bypass version constraints (e.g. I know a newer version still works but another dependency forces the older version)

### ISSUE THREAD

**Issue by AndreasA** [composer/composer#3837]
I think it would be good to be able to bypass certain dependencies of requirements, e.g.
if I verified the requirement dependency still works with a newer version but there is a depency that still forces the old version.

This feature would only make sense for the composer.json where composer install/update is called.

Example: 
TYPO3 7.1 if I create a project hat has 7.1 as dependency and use composer.typo3.org as repository to install "typo3-ter/realurl": "1.12.*"
I get the error that realurl requires TYPO3 6.2.x
However, if I install TYPO3 7.1 and install the core extension compatiblity6 realurl would still work.

**Comment by stof** [comment]
Well, this would mean making Composer explicitly disable its main feature. This looks weird.

the right solution for this case would be to fix the constraint in the dependency (and this is where semver helps a lot because a library could allow future minor versions of its dependencies thanks to the semver contract, meaning that you would be less likely to hit such case).

**Comment by AndreasA** [comment]
Normally, I agree but one does not always have access to the dependency constraint.
And if it is the main composer.json I will only do so if I want and then I am responsible for the consequences.

That is why I said this should only be possible in the main composer.json

Btw. example is not completely perfect that one would not work but there are others.


Also what if I want to use a not working version but provide a patch to get it working via post-install-scripts or something similiar? Here the constraint wouldn't work either.

**Comment by AndreasA** [comment]
For TYPO3 I now add the corresponding EXT that fails as package directly, where I then just don't have to define the dependencies.

**Comment by stof** [comment]
@AndreasA providing a patch via a post-install script is a huge hack, and it will let people run broken code in case they run composer with the ``--no-scripts`` command. And it is fragile (what if the patch does not apply cleanly anymore after an update ?).
A better way to solve this is to maintain a repo with the patched version of the code (and the updated constraint in the composer.json) and make composer read the package from this repository: https://getcomposer.org/doc/05-repositories.md#vcs
The goal being of course that this repo is only a temporary solution until the patch is merged upstream

**Comment by AndreasA** [comment]
Usually the update should fix what the patch was supposed to do anyway.
And not every code is available in a way to fork as repository temporarily, though it is, of course the preferred way or due to licensing or ...
