### ISSUE TITLE
Proposal: composer fear (lock constraints)

### ISSUE THREAD

**Issue by schmunk42** [composer/composer#3839]
While in the subject `fear` is only a working title, it could also be `lock` or something similar.

Inspired by https://github.com/jonathanong/ferver I thought about the following functionality:

```
composer fear
```

Replace constraints in your `composer.json` file with values from the current `composer.lock` file.
This would lock down your app and you ~~would never get updates at all~~ no updates for your root packages - functionality could be extended to lock a single package or subtree or even with dependencies.

You could still then make manual changes to the composer.json file and bring back a constraint. Or simply require it.

This could help a lot, if you want restrict the updates, eg. after deployment.

Any thoughts?

**Comment by maxcal** [comment]
Why not just use stricter version constraints in your `composer.json`?

**Comment by stof** [comment]
@schmunk42 I don't understand your reason. Ensuring to have consistent versions selected is the role of the composer.lock. Why would you turn the composer.json into a composer.lock too ?

**Comment by schmunk42** [comment]
For sure I can do this manually or by parsing composer.lock on my own.
The basic idea is just to slow down updates intentionally, with a helper function.

But maybe out of scope of composer, will close the issue.
