### ISSUE TITLE
Package not installed when composer.lock is present

### ISSUE THREAD

**Issue by israelshirk** [composer/composer#3844]
I'm having a bit of an odd issue with a package not being installed when composer.lock is present.

### Reproduction
* Use composer.lock and composer.json in the gist below.
* Run `composer install --prefer-source --no-interaction --dev -v -v -v -v` (or any number of variants I've tried).
* Apply `ls vendor`; observe that the path `vendor/wimg` is present.
* Remove vendor directory.
* Run `composer install --prefer-source --no-interaction --dev -v -v -v -v` again.
* Observe that `vendor/wimg` alone is missing.

### Observations
* Composer version is: 
```
israel@retina ~/_yeti/git-repos/backend (master) $ composer --version
Composer version 1.0-dev (d57187446151ef84b28cb9f6b3ed38cc2cffc597) 2015-03-09 23:06:06
```
* PHP version:
```
israel@retina ~/_yeti/git-repos/backend (master) $ php --version
PHP 5.6.5 (cli) (built: Jan 29 2015 00:11:43) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
```
* OS and version (latest OS X):
```
israel@retina ~/_yeti/git-repos/backend (master) $ uname -a
Darwin compy.dev 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64
```
* Also happens on CircleCI builds (Ubuntu), same behavior.
* Clearing out ~/.composer has no effect
* wimg/php-compatibility (the package I'm noticing) installs when it is one of the first packages installed (happening to always occur after composer.lock has been removed); when it is one of the last packages to install (happening to always occur when composer.lock is present), it does not install.  Maybe irrelevant.
* Flags on composer don't seem to make a difference.  Have tried variations including `composer install`; `composer install --prefer-dist`; `composer install --prefer-source --no-interaction`; `composer install --prefer-source --no-interaction --dev`; `composer install --dev`.
* Tried previous version as well:
```
Composer version 1.0-dev (8db7420f025b5c4705ce6f66b65c6d2b52d27813) 2015-01-12 23:02:29
```
* When using `--prefer-dist`, inspecting the composer cache reveals that the downloaded zip is present and populated the same regardless of composer.lock's presence.

### Relevant log excerpts
_starting from clean path, only composer.json present...  scroll right to catch overflow..._
```bash
israel@retina ~/_yeti/git-repos/backend (master *) $ composer install --prefer-source --no-interaction --dev -v -v -v -v
You are using the deprecated option "dev". Dev packages are installed by default now.
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing pragmarx/google2fa (v0.1.0)
    Cloning 705c2ff3e59212636fdfe31405e0e667a4f31514
 
  - Installing squizlabs/php_codesniffer (1.5.6)
    Cloning 6f3e42d311b882b25b4d409d23a289f4d3b803d5
 
  - Installing wimg/php-compatibility (dev-master 9ebe475)
    Cloning 9ebe475ea4a46b8c90a5567ebba2c733ac51a86d
 
  - Installing symfony/finder (v2.6.4)
    Cloning 16513333bca64186c01609961a2bb1b95b5e1355
 
...  Skip to end of command running ...
Writing lock file
Generating autoload files
israel@retina ~/_yeti/git-repos/backend (master) $ ls vendor
autoload.php   classpreloader danielstjules  doctrine       illuminate     jakub-onderka  laravel        monolog        nesbot         phpdocumentor  phpunit        psr            sebastian      squizlabs      symfony        wimg
bin            composer       dnoegel        fzaninotto     ircmaxell      jeremeamia     league         mtdowling      nikic          phpspec        pragmarx       psy            simplyadmire   swiftmailer    vlucas
israel@retina ~/_yeti/git-repos/backend (master) $ 
israel@retina ~/_yeti/git-repos/backend (master) $ rm -rf vendor
israel@retina ~/_yeti/git-repos/backend (master) $ composer install --prefer-source --no-interaction --dev -v -v -v -v
You are using the deprecated option "dev". Dev packages are installed by default now.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing fzaninotto/faker (dev-master 5f91d63)
    Cloning 5f91d63d78036ee445601ce0c606cdceb0be55d2

........Skip a few, to the very last couple of packages.........
 
  - Installing simplyadmire/composer-plugins (1.0.3)
    Cloning 15ba187d9dd973ddefeb32ee0619d74a3dff51a9
 
  - Installing wimg/php-compatibility (dev-master 9ebe475)
    Cloning 9ebe475ea4a46b8c90a5567ebba2c733ac51a86d
 
symfony/var-dumper suggests installing ext-symfony_debug ()

# ...Skip...

Generating autoload files
israel@retina ~/_yeti/git-repos/backend (master) $ ls vendor/
autoload.php   classpreloader danielstjules  doctrine       illuminate     jakub-onderka  laravel        monolog        nesbot         phpdocumentor  phpunit        psr            sebastian      squizlabs      symfony
bin            composer       dnoegel        fzaninotto     ircmaxell      jeremeamia     league         mtdowling      nikic          phpspec        pragmarx       psy            simplyadmire   swiftmailer    vlucas
```

More-complete terminal logs are available here; logs start with composer.lock present (failure to install wimg/php-compatibility); continue to composer.lock removal and re-running composer (success - package appears in vendor directory); then complete with running composer one more time with composer.lock present (failure to install wimg/php-compatibility):
https://gist.github.com/israelshirk/c8073abdaa5b5da8c70b

### Conclusion
Whiskey Tango?  And thanks in advance for the assistance.

**Comment by Seldaek** [comment]
Not sure what the issue was, but I can't reproduce. If I install your json as you said I end up with wimg/php-compatibility installed in vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PhpCompatibility/ as it should. Nothing in vendor/wimg ever.
