### ISSUE TITLE
Wrong Requires version ?

### ISSUE THREAD

**Issue by juliensantos87** [composer/composer#3848]
Hi, 

I update my composer with this configuration:

    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.6.x-dev",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0",
        "sensio/framework-extra-bundle": "~3.0",
        "incenteev/composer-parameter-handler": "~2.0",
        "doctrine/doctrine-fixtures-bundle": "~2.2",
        "sonata-project/admin-bundle": "~2.3",
        "sonata-project/doctrine-orm-admin-bundle": "~2.3",
        "jms/serializer-bundle": "0.13.*",
        "sonata-project/media-bundle": "~2.3",
        "a2lix/translation-form-bundle": "~2.0",
        "knplabs/doctrine-behaviors": "~1.0",
        "sonata-project/cache-bundle": "~2.2",
        "ongr/elasticsearch-bundle": "dev-master",
        "lexik/mailer-bundle": "dev-master",
        "lexik/translation-bundle": "~2.0"
    },

So sonata/admin-bundle in 2.3.1 require sonata/block-bundle <= 2.2.7
https://packagist.org/packages/sonata-project/admin-bundle#2.3.1

But composer install the block-bundle 2.3.0.
Is there an issue on compatibility check here?

edit:
Composer version 1.0-dev (d57187446151ef84b28cb9f6b3ed38cc2cffc597) 2015-03-09 23:06:06

**Comment by stof** [comment]
Can you provide the output of ``composer show -i`` ?

**Comment by juliensantos87** [comment]
This is the composer show from this morning. because a fix on sonata-admin just been released https://github.com/sonata-project/SonataAdminBundle/commit/ed1882b7cb79c1f406a37dc8556e98da5bee35c9#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R34

But ~2.2,>=2.2.7 is not suppose to be handle by composer ? 

    a2lix/translation-form-bundle            2.0.4              Translate your doctrine objects easily with some helps
    cocur/slugify                            v1.0               Converts a string into a slug.
    doctrine/annotations                     v1.2.3             Docblock Annotations Parser
    doctrine/cache                           v1.4.0             Caching library offering an object-oriented API for many cache backends
    doctrine/collections                     v1.2               Collections Abstraction library
    doctrine/common                          v2.4.2             Common Library for Doctrine projects
    doctrine/data-fixtures                   v1.0.0             Data Fixtures for all Doctrine Object Managers
    doctrine/dbal                            v2.5.1             Database Abstraction Layer
    doctrine/doctrine-bundle                 v1.4.0             Symfony DoctrineBundle
    doctrine/doctrine-cache-bundle           v1.0.1             Symfony2 Bundle for Doctrine Cache
    doctrine/doctrine-fixtures-bundle        v2.2.0             Symfony DoctrineFixturesBundle
    doctrine/inflector                       v1.0.1             Common String Manipulations with regard to casing and singular/plural rules.
    doctrine/lexer                           v1.0.1             Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
    doctrine/orm                             v2.4.7             Object-Relational-Mapper for PHP
    elasticsearch/elasticsearch              v1.3.3             PHP Client for Elasticsearch
    facebook/xhprof                          dev-master 6bf0072 XHProf: A Hierarchical Profiler for PHP
    friendsofsymfony/rest-bundle             1.5.3              This Bundle provides various tools to rapidly develop RESTful API's with Symfony2
    guzzle/guzzle                            v3.9.2             Guzzle is a PHP HTTP client library and framework for building RESTful web service cl...
    imagine/imagine                          0.6.2              Image processing for PHP 5.3
    incenteev/composer-parameter-handler     v2.1.0             Composer script handling your ignored parameter file
    jdorn/sql-formatter                      v1.2.17            a PHP SQL highlighting library
    jms/metadata                             1.5.1              Class/method/property metadata management in PHP
    jms/parser-lib                           1.0.0              A library for easily creating recursive-descent parsers.
    jms/serializer                           0.16.0             Library for (de-)serializing data of any complexity; supports XML, JSON, and YAML.
    jms/serializer-bundle                    0.13.0             Allows you to easily serialize, and deserialize data of any complexity
    jns/xhprof-bundle                        dev-master 2a0651a Symfony JnsXhprofBundle
    knplabs/doctrine-behaviors               v1.0.3             Doctrine2 behavior traits
    knplabs/gaufrette                        v0.1.9             PHP5 library that provides a filesystem abstraction layer
    knplabs/knp-menu                         v2.0.1             An object oriented menu library
    knplabs/knp-menu-bundle                  v2.0.0             This bundle provides an integration of the KnpMenu library
    kriswallsmith/assetic                    v1.2.1             Asset Management for PHP
    kriswallsmith/buzz                       v0.13              Lightweight HTTP client
    lexik/mailer-bundle                      dev-master e4fc220 This bundle allow you to manage some HTML email templates stored in your database. Te...
    lexik/translation-bundle                 v2.1.1             This bundle allow to import translation files content into the database and provide a...
    michelf/php-markdown                     1.5.0              PHP Markdown
    monolog/monolog                          1.13.1             Sends your logs to files, sockets, inboxes, databases and various web services
    nelmio/api-doc-bundle                    2.8.0              Generates documentation for your REST API from annotations
    ongr/elasticsearch-bundle                dev-master d091a04 elasticsearch php client bundle for Symfony 2.
    phpcollection/phpcollection              0.4.0              General-Purpose Collection Library for PHP
    phpoption/phpoption                      1.4.0              Option Type for PHP
    pimple/pimple                            v3.0.0             Pimple is a simple Dependency Injection Container for PHP 5.3
    psr/log                                  1.0.0              Common interface for logging libraries
    sensio/distribution-bundle               v3.0.18            Base bundle for Symfony Distributions
    sensio/framework-extra-bundle            v3.0.4             This bundle provides a way to configure your controllers with annotations
    sensio/generator-bundle                  v2.5.2             This bundle generates code for you
    sensiolabs/security-checker              v2.0.1             A security checker for your composer.lock
    sonata-project/admin-bundle              2.3.1              Symfony SonataAdminBundle
    sonata-project/block-bundle              2.3.0              Symfony SonataBlockBundle
    sonata-project/cache                     1.0.4              Cache library
    sonata-project/cache-bundle              2.2.0              This bundle provides caching services
    sonata-project/core-bundle               2.3.1              Symfony SonataCoreBundle
    sonata-project/doctrine-extensions       1.0.2              Doctrine2 behavioral extensions
    sonata-project/doctrine-orm-admin-bundle 2.3.1              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
    sonata-project/easy-extends-bundle       2.1.9              Symfony SonataEasyExtendsBundle
    sonata-project/exporter                  1.3.4              Lightweight Exporter library
    sonata-project/intl-bundle               2.2.1              Symfony SonataIntlBundle
    sonata-project/media-bundle              2.3.1              Symfony SonataMediaBundle
    sonata-project/notification-bundle       2.3.0              Symfony SonataNotificationBundle
    swiftmailer/swiftmailer                  v5.4.0             Swiftmailer, free feature-rich PHP mailer
    symfony/assetic-bundle                   v2.6.1             Integrates Assetic into Symfony2
    symfony/icu                              v1.2.2             Contains an excerpt of the ICU data and classes to load it.
    symfony/monolog-bundle                   v2.7.1             Symfony MonologBundle
    symfony/swiftmailer-bundle               v2.3.8             Symfony SwiftmailerBundle
    symfony/symfony                          2.6.x-dev be05344  The Symfony PHP framework
    twig/extensions                          v1.2.0             Common additional features for Twig that do not directly belong in core
    twig/twig                                v1.18.0            Twig, the flexible, fast, and secure template language for PHP
    willdurand/jsonp-callback-validator      v1.1.0             JSONP callback validator.
    willdurand/negotiation                   1.3.4              Content Negotiation tools for PHP provided as a standalone library.

**Comment by xabbuh** [comment]
@juliensantos87 `~2.2` is equivalent to `>=2.2.0,<3.0.0`. If you just want to have `>=2.2.0,<2.3.0`, you should probably use `~2.2.0` instead (note the presence of the patch version part here).

**Comment by juliensantos87** [comment]
@stof @xabbuh my bad, I was thinking composer handle it. anyways they fixed it  with a new release
