### ISSUE TITLE
composer update triggers changes in unrelated packages when using --prefer-source

### ISSUE THREAD

**Issue by khromov** [composer/composer#3849]
To replicate:

1.)  
Create a composer project with a dependency on two projects hosted on GitHub, for example: 
```
khromov/foo
khromov/bar
```

(Names are made up, but they should be configured as VCS sources.)

2.)  
Run:

```
composer update --prefer-source
```

3.)  
Load the first dependency (via the vendor folder) into a git client and make a commit and push.

4.)  
Do the same thing for the second dependency.

5.)  
Run:  
```
composer update khromov/foo
```

Expected:  
composer.lock file changes the dist reference hash on khromov/foo to the latest HEAD.

Actual:  
composer.lock changes the dist reference hash on both khromov/foo and khromov/bar to the latest HEAD, although we explicitly told it to only update khromov/foo in the update command.

Composer seems to be reading the git repository when using --prefer-source, and overrides the update command when a single package is specified.

**Comment by craue** [comment]
Only using `--prefer-source`? I've also noticed this behavior with dependencies added with `--prefer-dist` (in step 2) and even when no packages are going to be updated (e.g. by calling `composer update nothing` in step 5). Just the `dist` `url` in the lock file will be set to the latest commit hash if an update is available for that dependency. Seems to be related to #4126.

**Comment by khromov** [comment]
@craue What I believe is happening is that if you check out packages with ``--prefer-source``, it makes Composer check the .git folder rather than Github (or your whichever VCS host you have) and prefer those changes rather than the upstream ones. But more crucially, it triggers *updates* in unrelated packages. The ticket you linked is something we have also observed but is related to the GitHub API, and not this issue.

**Comment by craue** [comment]
Now I'm not sure anymore if we talk about the same issue. I can reproduce it as follows...

1. In a clean folder, run `composer -n init --require composer/composer:dev-master#2f69faf2521b3aa5a00f05d8650fc1ce28c9d037` (which points to an older commit, not the latest one).
1. Run `composer update`. It doesn't matter if you explicitly add `--prefer-source` or `--prefer-dist` here. Both will reveal the glitch.

Now the `dist` `url` for `composer/composer` will point to the latest hash, not the one actually required and installed.

@khromov: Is this your issue as well?
