### ISSUE TITLE
Multiple private repo requires aren't working

### ISSUE THREAD

**Issue by DrRoach** [composer/composer#3851]
Hi,

I have a composer.json file that requires a private repo on bitbucket and in there, another private repo on bitbucket again is required. Running `composer install` on the main repo gives a error saying: `Your requirements could not be resolved to an installable set of packages.`. But if I run `composer install` on the repo that is giving the error it installs fine. Any help is much appreciated.

Both of the repos are in `require` and not `require-dev`

**Comment by aaukt** [comment]
Composer only supports repositories in the root package.

> Repositories are only available to the root package and the repositories defined in your dependencies will not be loaded.

https://getcomposer.org/doc/05-repositories.md#repository

https://getcomposer.org/doc/faqs/why-can't-composer-load-repositories-recursively.md

**Comment by DrRoach** [comment]
Thanks!!
