### ISSUE TITLE
Feature request: "requires-before"

### ISSUE THREAD

**Issue by andytson** [composer/composer#3856]
Would a "requires-before" directive be an acceptable way for projects to install installers before packages, to ensure their available before the package's post-install?

Otherwise do you consider this the job of the package to define it's installers?

Reason I brought this up is that firegento modules don't tend to require magento-composer-installer, and so if the installer package runs after the module package, it doesn't run the post-install process for them, so they aren't available

**Comment by jakoch** [comment]
Hey Andy!

> Do you consider this the job of the package to define it's installers?

Yes. The packages could declare a custom type and require the needed installer.
The type `magento-module` is not part of `composer/installers`.
Modules would need to require the fork `magento-hackathon/magento-composer-installer` to handle the `magento-module` installation. Using "suggest" is not an option.

This should do it:
```
"type": "magento-module",
"require": {
    "magento-hackathon/magento-composer-installer": "*"
},
```
