### ISSUE TITLE
Diagnose command fails with php errors

### ISSUE THREAD

**Issue by xrogers** [composer/composer#3859]
PHP version: PHP 5.6.6-1~dotdeb.1 (cli) (built: Feb 20 2015 19:57:36)
Sample output:
php composer.phar diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity: FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: SSL: Handshake timed out
Failed to enable crypto
failed to open stream: operation failed
Checking github.com rate limit: PHP Fatal error:  Cannot use object of type Composer\Downloader\TransportException as array in phar:///xxx/composer.phar/src/Composer/Command/DiagnoseCommand.php on line 103

Fatal error: Cannot use object of type Composer\Downloader\TransportException as array in phar:///xxx/composer.phar/src/Composer/Command/DiagnoseCommand.php on line 103

**Comment by bexter989** [comment]
try this in your terminal:
export http_proxy=yourproxy.com:port
export https_proxy=yourproxy.com:port
