### ISSUE TITLE
[ErrorException] file_put_contents(/usr/bin/doctrine)               

### ISSUE THREAD

**Issue by julianjjo** [composer/composer#3860]
I can not install doctrine generates this error:
<code>
[ErrorException]                                                             
file_put_contents(/usr/bin/doctrine): failed to open stream: Permission denied  
</code>

**Comment by xabbuh** [comment]
@julianjjo What exactly did you do? I cannot think of a standard use case where Composer does want to write to `/usr/bin/doctrine` if you didn't configure anything special in your project.

**Comment by julianjjo** [comment]
A few days ago in Codeship not run tests for this error, run in local composer as root to install the bundles, but in the continuous integration server is not possible.

This my composer.json:

<code> 
{
    "name": "symfony/framework-standard-edition",
    "license": "MIT",
    "type": "project",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-0": { "": "src/" }
    },

    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "jquery/jquery",
                "version": "1.11.1",
                "dist": {
                    "url": "http://code.jquery.com/jquery-1.11.1.js",
                    "type": "file"
                }
            }
        }
    ], 

    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.4.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~2.3",
        "sensio/framework-extra-bundle": "~3.0",
        "sensio/generator-bundle": "~2.3",
        "incenteev/composer-parameter-handler": "~2.0",
        "doctrine/doctrine-fixtures-bundle": "dev-master", 
        "doctrine/data-fixtures": "dev-master",
        "braincrafted/bootstrap-bundle": "dev-master",
        "twbs/bootstrap": "3.2.*",
        "jquery/jquery":  "1.11.*",
        "oyejorge/less.php": "dev-master",
        "ddeboer/data-import": "@stable"
    },
    "require-dev": {
        "phpunit/phpunit": "4.3.*"
    },
    "scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ]
    },
    "config": {
        "bin-dir": "/usr/bin"
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": {
            "dev-master": "2.4-dev"
        }
    }    
}
</code>

**Comment by stof** [comment]
@julianjjo the issue is the fact that you specify ``"bin-dir": "/usr/bin"``. this requires ``/usr/bin`` to be writable by Composer so that it can put bins in it.

**Comment by julianjjo** [comment]
Thanks, I didn't see this change in my project.
