### ISSUE TITLE
Error requiring nested dependencies from vcs repos

### ISSUE THREAD

**Issue by andig** [composer/composer#3863]
I've started refactoring a component of our app into a separate repo as this component requires a higher PHP version. Now, requiring that `andig/volkszaehler-httpd` component (https://github.com/andig/volkszaehler-httpd) I'm stuck with composer:

    composer require andig/volkszaehler-httpd:dev-master

	./composer.json has been updated
	Loading composer repositories with package information
	Reading composer.json of andig/volkszaehler-httpd (master)
	Updating dependencies (including require-dev)
	Your requirements could not be resolved to an installable set of packages.

	  Problem 1
	    - Installation request for andig/volkszaehler-httpd dev-master -> satisfiable by andig/volkszaehler-httpd[dev-master
	].
	    - andig/volkszaehler-httpd dev-master requires marcj/php-pm dev-dependencies -> no matching package found.

andig/volkszaehler-httpd is tied to a private, non-packagist repo in our application (https://github.com/andig/volkszaehler.org/blob/react-server/composer.json):

    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/andig/volkszaehler-httpd"
        }
    ],
    
andig/volkszaehler-httpd itself requires marcj/php-pm which is on packagist but with defects. I have a local dependencies branch where I've fixed those. This is what andig/volkszaehler-httpd composer.json looks like (https://github.com/andig/volkszaehler-httpd/blob/master/composer.json):

	{
	    "name": "andig/volkszaehler-httpd",
	    "type": "library",
	    "homepage": "http://www.volkszaehler.org/",
	    "license": "GPL-3.0",
	    "support": {
		"wiki": "http://wiki.volkszaehler.org/",
		"email": "volkszaehler@lists.volkszaehler.org"
	    },
	    "require": {
		"php": ">=5.4.0",
		"symfony/console": "2.6.*",
		"symfony/http-kernel": "2.6.*",
		"react/react": "0.4.*",
		"marcj/php-pm": "dev-dependencies"
	    },
	    "require-dev": {
		"phpunit/phpunit": "4.1.*",
		"jenssegers/proxy": "~2.2"
	    },
	    "autoload": {
		"psr-4": {
		    "VolkszaehlerHttpd": "src/"
		}
	    },
	    "repositories": [
		{
		    "type": "vcs",
		    "url": "https://github.com/andig/php-pm"
		}
	    ],
	    "bin": [
		"httpd.php"
	    ]
	}

Apparently, the andig/php-pm vcs repo for marcj/php-pm is not being picked up by composer. This setup (overriding the published marcj/php-pm with local vcs repo) did work before I've starting splitting the packages.

**Comment by aaukt** [comment]
Composer supports repositories only in the root package.

> Repositories are only available to the root package and the repositories defined in your dependencies will not be loaded.

https://getcomposer.org/doc/05-repositories.md#repository

https://getcomposer.org/doc/faqs/why-can't-composer-load-repositories-recursively.md

**Comment by andig** [comment]
Understood, and workaround of defining VCS repos in the root perfectly viable here. 
Thank you!

**Comment by andig** [comment]
Update- sorry I have to reopen this one. I have now added all VCS repos to the parent package:

        {
            "type": "vcs",
            "url": "https://github.com/andig/volkszaehler-httpd"
        },
        {
            "type": "vcs",
            "url": "https://github.com/andig/php-pm"
        }

However, requiring the suggested andig/volkszaehler-httpd dependecy I'm still faced with the exact error message as in the initial post, so still the repo is not used. 

Apparently I can define it but it does not apply to child packages? I cannot require that child package on the parent as it is itself requiring a higher PHP version that I need and is really not required but optional.

If this does not work and to come back to the actual problem: is there an alternative for factoring out non-vital depencies (adapters etc) where the dependency requires use of VCS repo?

**Comment by andig** [comment]
Any more ideas? Is there a way to make child packages use vcs-aliased repos?

https://getcomposer.org/doc/05-repositories.md#repository does mention that: 

> Repositories are only available to the root package and the repositories defined in your dependencies will not be loaded.

...but it does not clarify how those repos apply to child packages.

**Comment by stof** [comment]
@andig your issue is different now. It is not related to the fact that the VCS repo is not read (it is now if you read the output) but to the fact that you force a dependency on a dev version, and your root package does not allow dev versions for ``marcj/php-pm``. The package stability is also under control of the root package

**Comment by andig** [comment]
@stof thank you so much. Solved by combining `minimum-stability` and `prefer-stable`. Discovering new wonders of composer every time....
