### ISSUE TITLE
hhvm error I had to persist the lock files to make it work

### ISSUE THREAD

**Issue by cordoval** [composer/composer#3864]
https://travis-ci.org/gushphp/gush/jobs/55336441

```
[RuntimeException]                                                                                                                     
          The lock file does not contain require-dev information, run install with the --no-dev option or run update to install those packages.  
```

**Comment by Seldaek** [comment]
That error kinda explains it, I don't really get what you're saying.. it could be you had an old lock file in there or you ran update --no-dev and stored that lock file so it didn't contain dev requires.. Anyway I don't see how this is a composer issue.

**Comment by cordoval** [comment]
I never stored any locks on my project. Gush now it is storing it on the repo in order to bypass this problem only occurring in hhvm environment in travis. Again I only run composer install in projects and never use update tbh. I think the issue is genuine. cc @sstok

**Comment by Seldaek** [comment]
But many projects don't store the lock file and test on hhvm and never had that issue so I am wondering what's up..

**Comment by cordoval** [comment]
a key difference i see is that i use autoload-dev which I have not seen many other projects do, could this be related?

**Comment by Seldaek** [comment]
I doubt it, autoload rules have nothing to do with installation really

**Comment by sstok** [comment]
https://github.com/rollerworks/RollerworksSearch/blob/master/composer.json#L33 (autoload-dev)
https://travis-ci.org/rollerworks/RollerworksSearch/jobs/54372488 (hhvm)

Does HHMV with Travis use some sort of cache? (note. Gush doesn't use the docker container).

**Comment by sstok** [comment]
I noticed just now that Gush uses the nigthly, not the stable one. so it could be a bug in HHMV also.

**Comment by sstok** [comment]
https://travis-ci.org/gushphp/gush/jobs/55689511

Its seems to be an issue with bldr, it uses composer-embedded and it creates its own lock file bldr.lock but for some reason this lock file is used by composer? It can be an issue with Bldr or with HHVM using an evaluation cache or something. Hmm, does Composer use any constants?

**Comment by cordoval** [comment]
@sstok yes the lock file is used by composer embedded. I believe is more of an issue of composed embedded which disappears after we don't use bldr. Perhaps bldr and hhvm yeah, not composer. Because I don't like having opened issues I will close since we have resolved this removing bldr on hhvm for now. Thanks Jordi :+1:
