### ISSUE TITLE
ext-apc provides ext-apcu

### ISSUE THREAD

**Issue by hazardland** [composer/composer#3865]
**exc-apc** is a package supported by PHP version < 5.5:
1. Provides a framework for caching and optimizing PHP intermediate code.
2. Functions for storing user cache data
http://pecl.php.net/package/APC

**exc-apcu** is a package supported by PHP version > 5.5:
1. Provides only functions for storing user cache data. Functions for user cache in **ext-apcu** are 100% same as in **ext-apc**.
http://pecl.php.net/package/APCu

Therefore we can say that **ext-apc 100% provides ext-apcu**.

The problem is if my application relies on apc user cache functions and if I require ext-apc I loose PHP 5.5 users, but if I require ext-apcu I loose PHP 5.4 and PHP 5.3 users. Because one can not compile ext-apc for PHP 5.5 and one cant compile ext-apcu for PHP 5.4 and PHP 5.3.

So is there a possibility that **ext-apc** provided **ext-apcu**? As I know this php extension virtual packages are hardcoded.

This would solve any problems related to this case if I correctly understand how provide keyword works. If I require **ext-apcu** and user has installed **ext-apc** because he has older version of PHP then **require ext-apcu** will not generate dependency error.

**Comment by stof** [comment]
@hazardland APCU advocates itself as APC being loaded (``extension_loaded('apc')`` returns true when using APCU, unless you compiled it without the APC layer, in which case it does not provide APC at all).
So just require ``ext-apc`` in your config, and people using ext-apcu will be fine

**Comment by hazardland** [comment]
@stof thanks !

Installed only **ext-apcu** and after:
```
composer show --platform
```
Returns this:
```
ext-apc             4.0.7    The apc PHP extension
ext-apcu            4.0.7    The apcu PHP extension
```
So just **require ext-apc** deals with both cases.
