### ISSUE TITLE
Composer update

### ISSUE THREAD

**Issue by m4a1fox** [composer/composer#3870]
Hi all. Today notice that composer update became tooooooo slow. Can anyone explain that? Before today all work fine. Was quick and fancy.

**Comment by stevebauman** [comment]
Noticed this as well, travis-ci builds are taking ages to finish. I'm assuming they're running maintenance or something along those lines hopefully.

**Comment by iusik** [comment]
Same problem composer update is very... very slow today!

**Comment by rgeraldporter** [comment]
Same here!

**Comment by Hakadel** [comment]
Me too :(

**Comment by ciaranmaher** [comment]
Same here :(

**Comment by rgeraldporter** [comment]
Seems to be a bit better now

**Comment by ryanwohara** [comment]
This isn't really an issue with composer itself and should probably be closed.
