### ISSUE TITLE
brew not linking composer.phar

### ISSUE THREAD

**Issue by grosch** [composer/composer#3875]
When installing composer via brew on a mac, a shell script is created.    The allow_url_fopen is the default on all PHP, so there's not a need for that.  I'm told the detect_unicode is only necessary to be set to off during installations, so shouldn't that just be part of the binary?

The *true* issue here though is you do not link composer.phar into /usr/local/bin and some tools, like PhpStorm, explicitly run composer.phar via the path to PHP, which makes the shell script just echo the output.

So, please add a symlink for composer.phar to the brew formula.  I know I can add one manually myself, but as soon as I upgrade composer via brew I'm pointing at an old version.

Thanks!

**Comment by alcohol** [comment]
Don't install composer via brew. Thanks.

**Comment by Seldaek** [comment]
We are not responsible for brew installs so please report brew specific issues with the phpbrew project
