### ISSUE TITLE
When changing the repository URL of a package, the old URL is still generated to the lock file

### ISSUE THREAD

**Issue by ondrejmirtes** [composer/composer#3876]
Steps to reproduce:

1) Have a package that is not on Packagist in the composer.json `require` section and a corresponding record in the `repositories` section.
2) Change the corresponding repository URL to a different one (a fork, for example).
3) Run `composer update`.

Expected result: The new composer.lock file will contain the new repository URL.
Actual result: The new composer.lock file contains the old repository URL.

If I delete the package directory from vendor-dir before running `composer update` (step 3) then the new composer.lock is fine.

**Comment by DHager** [comment]
Sounds like the same thing as #3874

**Comment by Tomdarkness** [comment]
I just got caught out by this. We moved the location of our git repos and updated the git urls in our composer.json and ran update. However, it did not actually update the URL in composer.lock so anyone trying to run composer install on a fresh clone would try and fetch the libraries from the old location.

**Comment by Seldaek** [comment]
This should have been fixed over a month ago by #3985, @Tomdarkness are you sure you were using an up to date dev build of composer? The fix is not in alpha10 I'm afraid.

**Comment by arusa** [comment]
It cost me sooooo much time. Why is composer doing this?

I change the URL and composer doesn't update it in composer.lock.
I update it manually in composer.lock and `composer update` just changes it back.

grep -r now exposed where composer cached the old URL:

./vendor/composer/installed.json
