### ISSUE TITLE
pull symlinking functionality out of LibraryInstaller

### ISSUE THREAD

**Issue by jakoch** [composer/composer#3881]
It would be nice, if the symlinking functionalites of the `LibraryInstaller` would be pulled out of the class and maybe into a new `Composer/Util/Symlink`. Please let the main methods (installBin or symlinkBin) be `public`, so that one can reuse the symlinking or binary copy functionality (e.g. from postInstall events) or from outside.

@kocsismate I've seen you working on the "bin-compat" config directive for symlinks. So, while you are at it and before the feature gets merged :) - would it be possible to address this, too? Easy pick.

**Comment by kocsismate** [comment]
Sure I can, but I became uncertain about your intentions when started coding. Basically, I don't know how granular should the Symlink class be:

So is it something like you imagined?

```php
class Symlink
{
    protected $filesystem;

    /**
     * Initializes the symlinkking utility.
     *
     * @param Filesystem  $filesystem
     */
    public function __construct(Filesystem $filesystem = null)
    {
        $this->filesystem = $filesystem ?: new Filesystem();
    }

    /**
     * Creates a symlink for a binary file at a given path.
     *
     * @param string $binPath The path of the binary file to be symlinked
     * @param string $link The path where the symlink should be created
     * @throws \ErrorException
     */
    public function symlinkBin($binPath, $link)
    {
        $cwd = getcwd();

        $relativeBin = $this->filesystem->findShortestPath($link, $binPath);
        chdir(dirname($link));
        $result = symlink($relativeBin, $link);

        chdir($cwd);
        if ($result === false) {
            throw new \ErrorException();
        }
    }
}
```

Or would you like me to pull out the full ``installSymlinkBinaries()`` (with the exception handler), the ``installUnixyProxyBinaries()`` and the ``installFullBinaries()`` methods? Or am I totally mistaken?

I am looking forward to hearing about your thoughts :)

**Comment by jakoch** [comment]
Hey Máté! 

Yes, this is a good. This makes symlinkBin() re-useable from the outside, which is my main idea for this request. My request included "binary copy functionality", but it's too early - let's shift that to "later".

The Symlink class has a clear name, a single responsibility and allows for better testing (less exec paths). A standalone Symlink class is also good, because this allows to move "symlink"-related functions from the Filesystem class over to this class (in the future), thereby reducing the method size of Filesystem. This helps in grouping related functionality.

> Or would you like me to pull out the full installSymlinkBinaries() (with the exception handler), the installUnixyProxyBinaries() and the installFullBinaries() methods?

No, a full extraction will not work at this point in time.
The idea is nice, but would only work out, if installFullBinaries would have less arguments.
When the method is declared public with a high number of arguments, it's likely to be a future BC break and it's also hard to reuse the method standalone (odd $package pass-around).
Cleanups and method extraction first, public declaration last. 

(Once the code used to be just a basic `else { symlink($bin, $link) }` - now it's true patch code, which evolved over time. It's becoming hard to maintain and integrate new features. It's also hard to test, because with this amount of paths, you will not get a decent coverage without losing your main hair.)

**Comment by kocsismate** [comment]
Hey Jens,

I pushed my changes to https://github.com/composer/composer/pull/3704/files, but there is a small merge conflict:

My conflicting $this->io->write(...) method invocation should rather be $this->io->writeError(...). That's all. Could you resolve it?

And thank you for the long explication! It really makes sense! I also had doubts about pulling out the 3 methods that I mentioned, but I couldn't decide if you really want to pull out multiple methods ("main methods"), or not. Now, everything is clear!

**Comment by jakoch** [comment]
Yes, it's no problem for Jordi to resolve it. The io streaming feature affects every unaccepted PR, which used io->write regardless of streams, anyway... 

How to keep your fork and feature-branch (with PR) in sync? 
What you are describing is the "best way" i think. 
You are merging from upstream/master to your local master branch and into your feature-branch (with PR). This might put you in a situation, where you might need to resolve a merge conflict.
Then you push to origin (your forked repo). This push will update origin/master and orign/feature-branch (including the commits of the PR).

> I don't feel this solution so nice as I can end up even more merge conflicts if my pull request stays unaccepted even longer.

You need to resolve merge conflicts only, if you want to improve your feature or have to work more on it, because of the PR discussion. When they are pleased with the PR, then merging the PR and resolving conflicts is the task of the maintainer. Most maintainers are quite experienced in merging and have good diff tools. They can pick PRs, select individual commits and resolve not only minor merge conflicts locally before they push.

**Comment by kocsismate** [comment]
Thank you again :) I didn't know that individual commits can be merged from the pull requests! Have a nice weekend

**Comment by Seldaek** [comment]
That PR has been merged and we now have a Composer\Util\Filesystem::relativeSymlink
