### ISSUE TITLE
Feature request: composer --need-self-update

### ISSUE THREAD

**Issue by ross-p** [composer/composer#3887]
It would be nice to have a programmatic way to know if composer is outdated and in need of a self-update.

For example I'd like to be able to run some code like this:

```bash
if composer --need-self-update; then
  composer self-update
fi
```

Or maybe something like

```bash
if test $(composer --days-since-self-update) -gte 30; then
  composer self-update
fi
```

Basically I don't want to be forced to `composer self-update` all the time.  But when it gets time that composer itself starts complaining that it should be updated, I'd like to update it then.

**Comment by jakoch** [comment]
Hey Ross,

Maybe the following script fits your intention? 

`getComposerWarningTime.php`
```
<?php
$p = new Phar('composer.phar', 0, 'composer.phar');
$stubString = $p->getStub();
preg_match("#COMPOSER_DEV_WARNING_TIME\'\,\s(\d+)#", $stubString, $matches);
echo $matches[1]; // timeout
```
The returned value is the compilation time of the Composer.phar plus 30 days.
Composer is outdated, when the timeout value is lower than current time (`if (time() > $timeout)...`).
You might retrieve the value in a bash script and do the comparison.

**Comment by ross-p** [comment]
@jakoch Thanks for the suggestion.  I am doing something similar:

```bash
if ! test $(grep --text COMPOSER_DEV_WARNING_TIME /path/to/composer | egrep '^\s*define' | sed -e 's,[^[:digit:]],,g') \> $(php -r 'echo time();'); then
  composer self-update
fi
```

Source: https://github.com/saltstack-formulas/php-formula/blob/master/php/composer.sls#L31

While that is working, I fear that composer may change the formatting of their code or the name of the constant or who knows what, which will then break any/all attempts such as yours and mine to grep this feature out of the code.

An explicit export of the data would be very welcome.

**Comment by jakoch** [comment]
I think we need to discuss the return value of the command.
It has to be consistent (also in regard to the install --needed request).

In your first script you are using the command for testing based on the exit code, where
Exit code 0 (success) means update needed and 1 (error) means no update needed, right?
Code 0 equals an empty string `""` and the condition evals to true if string is empty.

Should 1 indicate the need to update? (string comparison required)
Should this be a short or full sentence output? (string comparison or match/grep required)
What's better from your perspective?

**Comment by ross-p** [comment]
It's an interesting question.

While using exit codes makes for nice bash scripting, a non-zero exit code can usually mean any number of things have gone wrong.  For example, if the command 'composer' is unable to be executed, the shell will return non-zero, which is actually an error and not an indication that `composer self-update` needs to be executed.  The same is true for #3888 (`--is-install-needed`).

Furthermore if you decide to assign specific meanings to the exit codes then you'd have to ensure that it is consistent throughout the application, and cross shell/platform.  It's doable but it might be a bigger issue than it is worth.

It might be easier in this case to output text, with guaranteed constant output.  That output could be captured and compared.

Possible alternate usage:

```bash
if "YES" = "$(composer --need-selfupdate)"; then
  echo "Composer recommends that you run self-update";
fi
```

This sort of gets around the grep problem, because you're making a contract with people that you'll always return either "YES" or "NO", that output will never change, and any other output (or lack thereof) should be considered an error.  Any error in program execution surely won't result in "YES" being the only output.

That frees you up to change your STDOUT in normal cases however you want, to add/remove lines, translate them, whatever you feel is necessary to make it easier for humans to look at, because machines should be checking `--need-selfupdate` rather than trying to read human text.

I'm sure there are many other suitable ways to solve the problem as well.  My only real concern is that there is a separation between machine data/status and human-read data/status, so that when the human-read stuff changes (as it should), the machines don't break.

**Comment by ross-p** [comment]
Applying @fprochazka 's suggestion in #3888 a better solution here might be `--only-if-severely-outdated` (choose a better description :)

Meaning, I don't want to update composer every single time there is an update.  But if it's to the point where it is going to start complaining to me every time I run it, then update it in that case.

That seems cleaner, and no need to reserve output for comparison by the machine-user.

**Comment by jakoch** [comment]
`composer self-update --if-outdated` will respond with `Your composer version is not outdated, yet.` when your Composer version is still in the 30 days range (ignoring any possible newer/latest version). It's kind of a minimum update strategy for Composer. This will also lower the number of request to `getcomposer.org/version`, if it gets integrated and used.

**Comment by ross-p** [comment]
That's awesome.  Can't wait to use it.  :)

**Comment by jakoch** [comment]
Glad you like it. I don't know if and when it gets merged. It depends on the maintainers.
Regarding the option name "--if-outdated": i guess, we will have to come up with something "better", because of https://github.com/composer/composer/pull/3899#issuecomment-88427704

**Comment by alcohol** [comment]
`--if-stale`
`--30`
`--[if-]older-than X` (optional value defaulting to 30)

**Comment by Seldaek** [comment]
I'd rather not add extra cruft for this, it will resolve itself once we get out of alpha and default to installing stable releases on self-update.

**Comment by ross-p** [comment]
@seldaek OK, closing issue then.  Thanks for the feedback.

**Comment by fmonts** [comment]
I know this issue is old but search results still point here. 

I think something like this in composer.json would be useful:

    "require": {
        "composer": "^2.2",
    }

to ensure all team member and deployment servers are using an up-to-date version of composer.
