### ISSUE TITLE
Add --force-revert option

### ISSUE THREAD

**Issue by aleemb** [composer/composer#3889]
This issue has come up before via #1047 and #466.

My use-case is this. I have dozens of servers across which I deploy and update via scripts. I also have a facility to rollback my production environment should any kind of critical bugs arise. Sometimes after rolling back and then going back to master, I run into the "has uncommitted changes" error which seems to be annoying a lot of other users as well.

The alternative is for me to delete the vendor folder which would slow down my auto-deploy scripts significantly. Hope you can consider this option and implement it. I am sure there are other use cases where users just want to force ahead.

**Comment by stof** [comment]
There is already a way to do it through the  [``COMPOSER_DISCARD_CHANGES`` environment variable](https://getcomposer.org/doc/03-cli.md#composer-discard-changes) or through a config setting. I don't think a CLI option is necessary for that

**Comment by tremby** [comment]
That env variable doesn't work for me. Without env variable:
```
$ composer -n install
...
  [RuntimeException]
  Source directory /home/ubuntu/project/vendor/developer/package has uncommitted changes.
```

With env variable:
```
$ COMPOSER_DISCARD_CHANGES=true composer -n install
...
  [RuntimeException]
  Failed to execute git checkout 'abc123abc123' && git reset --hard 'abc123abc123'
  error: Your local changes to the following files would be overwritten by checkout:
  	src/somefile.php
  	src/otherfile.php
  Please, commit your changes or stash them before you can switch branches.
  Aborting
```

**Comment by aleemb** [comment]
Yup and it's quite cumbersome to set env variables in deploy tool. I wish this would become a command line arg to make things simple. It's a fairly common use-case and this issue comes up. I have even seen some people respond to it by suggesting the vendor folder be deleted and composer re-run (on Stackoverflow I am pretty sure).

**Comment by Seldaek** [comment]
Could not reproduce so I'll assume it's been fixed since

```
$ c require --prefer-source seld/jsonlint:1.* -n
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Updating seld/jsonlint (1.0.0 => 1.4.0)

Installation failed, reverting ./composer.json to its original content.


  [RuntimeException]
  Source directory vendor\seld\jsonlint has uncommitted changes.
```

```
$ COMPOSER_DISCARD_CHANGES=1 c require --prefer-source seld/jsonlint:1.* -n
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Updating seld/jsonlint (1.0.0 => 1.4.0)
    Checking out 66834d3e3566bb5798db7294619388786ae99394

Writing lock file
Generating autoload files
```
