### ISSUE TITLE
Adding header: Accept: application/*

### ISSUE THREAD

**Issue by elmosgot** [composer/composer#3892]
I don't know if this is a bug a problem with my Apache2 instalation, but the main problem I have. I get 403 forbidden when you don't specify the 'accept' header for json and tar files.

I got this when adding a private repository.

I managed to resolve this by applying the following patch:

[patch]
`diff --git a/src/Composer/Util/RemoteFilesystem.php b/src/Composer/Util/RemoteFilesystem.php`
`index 7c72c21..67654a3 100644`
`--- a/src/Composer/Util/RemoteFilesystem.php`
`+++ b/src/Composer/Util/RemoteFilesystem.php`
`@@ -142,7 +142,9 @@`
` `
`             unset($additionalOptions['retry-auth-failure']);`
`         }`
`-`
`+        if (preg_match( '/\.json|tar$/i', $fileUrl)) {`
`+        	$additionalOptions['http']['header'] = 'Accept: application/*';`
`+        }`
`         $options = $this->getOptionsForUrl($originUrl, $additionalOptions);`
` `
`         if ($this->io->isDebug()) {`
[patch]

I hope somebody can add these lines so I don't need to create my own composer.phar.

Thanks in advance!

**Comment by alcohol** [comment]
Sorry but this seems to be a bug with your apache configuration.
