### ISSUE TITLE
private Repo on Bitbucket without installed GIT don't work 

### ISSUE THREAD

**Issue by mad99** [composer/composer#3893]
Hi together, 
Composer is a really cool tool. Thank you very much for this!

There's a point, that left me stuck. Contao's Plugin System is use of Composer. There an error was thrown because I used the included credentials »username:password@« without installed or wrong installed GIT on publish Server. The Error could be from Composer itself.
 
There is a private Repository on Bitbucket. I would like to use it with the username:password@ included url in composer.json like :
"repositories": [        
        {
            "type": "vcs",
            "url": "https://username:password@bitbucket.org/ownername/reponame.git"
        },
        {
            "type": "artifact",
            "url": "packages"
        }
    ]
On the publish Server, there is no GIT installed nor SSH-KEY file create-able. So the error printout from Composer is:
Failed to clone https://username:***@bitbucket.org/ownername/reponame.git, git was not found, check that it is installed and in your PATH env. git: not found

In Contao-Community (https://community.contao.org/de/showthread.php?56354-funktioniert-Composer-mit-privatem-Bitbucket-Repository-ohne-SSH-Key-auf-Server) a nice guy told me, it could appear because the regular expression in https://github.com/composer/composer/blob/f10c71475167a4661225b14560ca0a400d730829/src/Composer/Repository/Vcs/GitBitbucketDriver.php#L146.

Maybe you could change the Regex, so the username:password@ possibility would work also without installed GIT. Or maybe you could deliver an different Error-Message: Like "Composer can't use your included credentials password:username@ in the url. Please use the auth.json instead of it."

Thanks to michael.g I found a workaround with the auth.json, so I can use the private Bitbucket Repo without installed or wrong installed GIT OR SSH-KEY on the public server. But without Michael I would stuck for a long time ...

Kind regards and thank you very much for your work on composer
Martin

**Comment by GromNaN** [comment]
The **auth.json** is the preferred method to handle authentication. You should never commit your credentials. Composer should have asked you the credentials.

See also: http://seld.be/notes/authentication-management-in-composer

**Comment by frederikbosch** [comment]
@mad99 Use auth.json as @GromNaN is saying. But I guess your setup will not work anyway. ```git was not found, check that it is installed and in your PATH env. git: not found```. You cannot use the GitBitbucketDriver on a server that has no git. You should consider changing your deployment strategy.

**Comment by kfreiman** [comment]
May be, `--prefer-dist` will be helpful

**Comment by frederikbosch** [comment]
@kfreiman ```--prefer-dist``` is not useful: he is using a vcs (git repo) and not a composer repository.

**Comment by mad99** [comment]
Thank you for your help. 
Strangely, on the server - according to the support - the Git-binary is under /usr/local/bin installed. An <?php var_dump(exec('echo $ PATH')?); produces the output: 
string(60) "/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin".
So everything should be correct. 
Nevertheless, the auth.json is a good way.

@frederikbosch : > You should consider changing your deployment strategy. 
That could be a very good idea :o)). Can you recommend a good »deployment strategy overview« link for composer or in general? I would love to optimize.

**Comment by frederikbosch** [comment]
@mad99 My advice was meant for the case you do not have git on your server. If this issue is not relevant anymore, please close it.
