### ISSUE TITLE
Commit 3efed220 breaks existing ScriptHandlers

### ISSUE THREAD

**Issue by uwej711** [composer/composer#3898]
The mentioned commit changes the event from CommandEvent to Event for ScriptHandlers, which breaks my own handlers and also those of SensioDistributionBundle. You get this if you do a simple composer self-update.

Is this intentionally?

**Comment by jakoch** [comment]
Please post the full hash, so that Github can automatically link it. Thanks.

**Comment by stevelacey** [comment]
Just needs to be in a comment not a title, boom 3efed220

**Comment by alcohol** [comment]
https://github.com/composer/composer/blob/master/src/Composer/Script/CommandEvent.php#L18

**Comment by uwej711** [comment]
Anyway, this makes it impossible to use composer with older ScriptHandlers

**Comment by alcohol** [comment]
That's ok, composer is still an alpha, incompatible changes will happen. Upgrade your scripthandlers.

**Comment by Seldaek** [comment]
I think it only breaks if you had incorrect (too loose?) type hints. For most people the BC layer worked, in a few cases yes there is breakage and I am sorry but I think updating and releasing a new version of those few script handlers is probably not so hard. On the other hand we had a huge mess here so it had to be cleaned up.

**Comment by uwej711** [comment]
Im affected as a user of SensioDistributionBundle. Will there be an update?

**Comment by alcohol** [comment]
Check with [them](https://github.com/sensiolabs/SensioDistributionBundle/issues)?

**Comment by uwej711** [comment]
I conclude this was intentionally and there is currently no way to resolve this other than stopping updating composer for a while.

**Comment by alcohol** [comment]
Because asking the maintainer of the broken package to fix it is not an option..? Ok..

**Comment by uwej711** [comment]
Well no, that is not the problem. But as you said, it needs to be fixed there. So closing this.

**Comment by alcohol** [comment]
Though https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Composer/ScriptHandler.php to me looks to be using proper typehints, so the BC layer provides for that. I see no reason why SensioDistributionBundle would not work.

**Comment by uwej711** [comment]
@alcohol you are right, thanks for pointing me to the right direction. The mistake was in our own code not using type hints for the events at all. Please accept my apologies.

Uwe
