### ISSUE TITLE
composer show -s shows wrong version when using git-flow

### ISSUE THREAD

**Issue by janoszen** [composer/composer#3901]
Currently, when using git-flow style release branches, `composer show -s` shows the wrong version:

    $ git checkout v1.0
    Switched to branch 'v1.0'
    $ composer show -s |grep -i ver
    versions : * 1.0.9999999.9999999-dev

    $ git checkout release/v1.0
    Switched to branch 'release/v1.0'
    $ composer show -s |grep -i ver
    versions : * dev-release/v1.0

As this version is used in the build process in some cases, consistency would be nice. Please consider recognizing the `release/` and `release/v` prefixes for determining the version

**Comment by phansys** [comment]
See #3662.

**Comment by Seldaek** [comment]
You can use the branch-alias feature to map `dev-release/v1.0` to `1.x-dev`, see https://getcomposer.org/doc/articles/aliases.md#branch-alias - or you could drop release/ from the branch name and use simply `1.0` or `1.x` because it gives enough info really and is supported by composer just fine.
