### ISSUE TITLE
github token auth password entry broken?

### ISSUE THREAD

**Issue by andig** [composer/composer#3905]
I've hit the github rate limit during testing:

	C:\andi\htdocs\vz>composer update
	Loading composer repositories with package information

	Could not fetch https://api.github.com/repos/volkszaehler/httpd, enter your GitHub credentials to go over the API rate l
	imit
	A token will be created and stored in "C:/Users/.../AppData/Roaming/Composer/auth.json", your password will never be
	stored
	To revoke access to this token you can visit https://github.com/settings/applications

However, I cannot enter my password:

	Username: andig
	Password:
	Bad credentials.
	You can also manually create a personal token at https://github.com/settings/applications
	Add it using "composer config github-oauth.github.com <token>"
	Username:

When entering the (correct!) password, nothing happens on hitting *return*. With the second *return* process continues and displays error above. The second return being required is fishy and I'm suspecting my entered password is not read at all?

composer is at current f10c71475167a4661225b14560ca0a400d730829, this is on Win7x64.

**Comment by andig** [comment]
The problem should be somewhere in here: https://github.com/composer/composer/blob/master/src/Composer/IO/ConsoleIO.php#L253

**Comment by andig** [comment]
Update 2: looking at ConsoleIO, I do have cygwin/bash installed as well which might get in the way of the bash detection magic?

**Comment by ryanwohara** [comment]
Can you confirm if $shell is empty when it reaches line 308 in ConsoleIO?

**Comment by frederikbosch** [comment]
@andig What happends if you remove your vendor folder, and try again?

**Comment by andig** [comment]
Right now I can't do any of the tests as I'm under the rate limit again. Is there an easy way to get above the rate limit for continued testing?

@frederikbosch I've cloned composer to take a look and the error came up installing it's dependencies as well. I guess the vendor folder was clean after fresh git clone.

@ryanwohara will add debug statements once I'm hitting the rate limit again.

**Comment by jakoch** [comment]
> Is there an easy way to get above the rate limit for continued testing?

Yes, you might run `composer config github-oauth.github.com <oauthtoken>` on the CLI to set the token. That's the same as adding the following lines to your `composer.json` manually:
```
"config": {
    "github-oauth": {
        "github.com": "your-oauth-token"
    }
 }
```
If you want to set the token globally: `composer config -g github-oauth.github.com <oauthtoken>`.

**Comment by alcohol** [comment]
Running this from the CLI will get you over the limit quickly enough I reckon;

``` bash
for i in `seq 1 60`; do curl https://api.github.com/nonexistant ; done
```

**Comment by andig** [comment]
@ryanwohara 

> Can you confirm if $shell is empty when it reaches line 308 in ConsoleIO?

I don't reach that line as I'm running on windows. Anything else to test? Problem is back, I'd like to help find the cause rather than treating the symptoms.

**Comment by andig** [comment]
I can confirm \Seld\CliPrompt doesn't show this problem anymore.
