### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by justechn** [composer/composer#3908]
I know this isn't a composer problem, but I am hoping one of you can help me solve it.

I am getting this error when I run composer install
```
[RuntimeException]
  Failed to execute git clone --no-checkout "https://git-wip-us.apache.org/repos/asf/logging-log4php.git" "C:\Projects\SI\ext\apache\log4php" && cd /D "C:\Projects\SI\ext\apache\log4php" && git remote add composer "https://git-wip
  -us.apache.org/repos/asf/logging-log4php.git" && git fetch composer
  Cloning into 'C:\Projects\SI\ext\apache\log4php'...
  fatal: unable to access 'https://git-wip-us.apache.org/repos/asf/logging-log4php.git/': SSL certificate problem: unable to get local issuer certificate
```

thanks

**Comment by frederikbosch** [comment]
@ryanmc2033 Are you able to clone the repo without composer? I can do that without any problems. My guess is that this has [nothing to do with composer](https://www.google.com/search?q=git+unable+to+get+local+issuer+certificate).

**Comment by spotwilliams** [comment]
Hi, i had the same problem. Try to configure git to doesnt check SSL certificates.

Use this command before to run composer update/install:

git config --global http.sslverify false


Regards!

**Comment by padraic** [comment]
@spotwilliams Not really the kind of solution to be suggesting to people... This disables TLS verification as a global setting for git.

**Comment by spotwilliams** [comment]
Thnaks @padraic. You can enable it over the command of composer completes the installation/update. That could improve the quality of solution.

Regards!

**Comment by shivanraptor** [comment]
Seems this problem come back with the latest version of Composer. Even disabling SSL verification doesn't solve the problem... still asking for Username & Password, though pressing "Enter" in both fields can execute the `git clone` command, but still ends up with connection timed out problem.

Problematic server : git-wip-us.apache.org when cloning log4php

Mac OS X 10.12.6 , Composer v1.5.2
