### ISSUE TITLE
including a forked package fails

### ISSUE THREAD

**Issue by hrvanderlingen** [composer/composer#3912]
I have cloned zf-commons/zfc-user in github and made some changes, I want to use this project in composer but nothing seems to work: either zf-commons/zfc-user itself is loaded or the package is not found. Example below. 

"repositories": [{
    "type": "git",
    "url": "https://github.com/hrvanderlingen/ZfcUser.git"
     }],
    
    "require": {
    
        "zf-commons/zfc-user": "dev-master"
       
    },

**Comment by alcohol** [comment]
Did you read https://getcomposer.org/doc/articles/aliases.md#require-inline-alias ?

**Comment by hrvanderlingen** [comment]
This did work:

"repositories": [{
    "type": "vcs",
    "url": "https://github.com/hrvanderlingen/ZfcUser"
     }],
    
    "require": {
       
        "zf-commons/zfc-user": "dev-bugfix as 1.0.0"
       
    },
With branchname bugfix
Thanks!
