### ISSUE TITLE
CLI stopped working - MAMP Windows

### ISSUE THREAD

**Issue by SuperKiwi** [composer/composer#3914]
I'm running MAMP on Windows and when I run 'composer install' in a folder where containing a composer.json file, CLI stops working.

Here are the command lines : 
______________________________________________
Loading composer repositories with package information
Installing dependencies <including require-dev>
    - Installing stripe/stripe-php <v2.1.1>
______________________________________________
And then CLI stops working and installation is not completed.
Thank you

**Comment by rajankur** [comment]
@SuperKiwi How did you fix the issue? I'm facing the similar issue and is frustrated to not resolve it since past few hours.

**Comment by SuperKiwi** [comment]
@rajankur it was 2 years ago, so pretty long time.
I decided to switch to XAMPP, it was working much better.
