### ISSUE TITLE
Composer version number ordering issue

### ISSUE THREAD

**Issue by Jamesking56** [composer/composer#3915]
Hey guys,

I was updating Codeception today through composer (I have it listed in `require-dev`) and I found a weird issue with Composer's way of working out versioning.

I started off by using Codeception on dev-master and I wanted to use the latest version in the `2.0` branch.

So I added `codeception/codeception: 2.0.*` and that installed version `2.0.9` after running `composer update`. The latest `2.0` branch version in codeception is `2.0.12`.

So I tried changing it to `codeception/codeception: ~2.0` which again installed `2.0.9`.

In the end I've had to hard-code the version number to `2.0.12`.

Why does composer think `2.0.9` is newer than `2.0.12`?

Just to add, I am running the latest composer build.

**Comment by theravel** [comment]
@Jamesking56 what other dependencies do you have? Probably other packages require exactly 2.0.9

**Comment by Jamesking56** [comment]
@theravel My composer json is: https://gist.github.com/Jamesking56/33a1fd086210e9e204b0

**Comment by alcohol** [comment]
First of all, dev-master will use their master branch, not their 2.0 branch.

When using dev-master, you get the latest commit of the master branch. So why you are expecting a tagged release (2.0.12) I don't know, but that is not how dev-master works.

Also noteworthy,
Their master has an alias to 2.1.x-dev.
Their master branch is numerous commits behind on their 2.0 branch.
Their 2.0 branch has an alias to 2.1.x-dev.

**Comment by Jamesking56** [comment]
Yes but when I changed that to ~2.0 I got 2.0.9 and not 2.0.12

**Comment by alcohol** [comment]
That's because your composer.json requirements result in installing phpunit/phpunit version 4.6.1, which is not allowed by codeception/codeception version 2.0.11 and upwards (they only allow ~4.5.0). Because of this conflict, a lower version of codeception is resolved as a result. 2.0.10 only allows 4.4.*. 2.0.9 allows ~4.0.

Please close this issue and move over to their issues section and ask them why they are so horrible at dependency management.

**Comment by alcohol** [comment]
To summarise, it doesn't think that `2.0.9` is the latest version. It is simply the highest version allowed when taking all other requirements into account.
