### ISSUE TITLE
Is this a SSH problem? Can't clone a private repository

### ISSUE THREAD

**Issue by yeeeen** [composer/composer#3919]
I've been getting this problem

![image](https://cloud.githubusercontent.com/assets/10379846/7053295/9f51d1d0-de66-11e4-9e47-4f8e90e99eb8.png)
  
My bitbucket SSH is fine
![image](https://cloud.githubusercontent.com/assets/10379846/7053310/bac76614-de66-11e4-9e2f-65b984995f81.png)

except when I ssh-add
![image](https://cloud.githubusercontent.com/assets/10379846/7053321/d27ea984-de66-11e4-947c-a49b40a65a50.png)

Also, I tried cloning but
![image](https://cloud.githubusercontent.com/assets/10379846/7053397/6dbf4336-de67-11e4-86d5-682094fbd7b4.png)

**Comment by alcohol** [comment]
Most likely it's a Windows problem. Did you try installing Linux?

**Comment by frederikbosch** [comment]
@alcohol Haha, that is really helpful.
@yeeeen This is most defenitely not composer, [google your problem](https://www.google.nl/search?q=could+not+read+from+remote+repository) and close this thread.
