### ISSUE TITLE
PHP Fatal error when trying to install wp-cli with Homebrew (composer install cause the error)

### ISSUE THREAD

**Issue by jsalamin** [composer/composer#3920]
Here is the situation, I'm trying to install `wp-cli` with Homebrew as following:

    brew install wp-cli

But during the installation process, the following error occurs:

> **PHP Fatal error**:  Allowed memory size of 262144 bytes exhausted (tried
> to allocate 29889 bytes) in Unknown on line 0

Homebrew first download the appropriate package:

    ==> Downloading https://github.com/wp-cli/wp-cli/archive/v0.18.0.tar.gz

And then the process use Composer to proceed the installation:

    ==> /usr/local/bin/composer install

That causes the above `PHP Error` and I haven't find any solution to fix this problem (I followed the instructions described [here][1] but no success).

I understand the error message and tried to increase the memory limit in the `php.ini` file (I also tried 1G):

    memory_limit = 512M

But without any success even after having restarted the server in order to be sure that my modification was taken into account.

Here are some information about my configuration:

    > php -v
    PHP 5.5.23 (cli) (built: Mar 23 2015 01:47:37)
    
    > brew -v
    Homebrew 0.9.5
    
    > composer -v
    Composer version 1.0-dev (f10c71475167a4661225b14560ca0a400d730829) 2015-03-29 14:37:42
    
    > php --ini
    Configuration File (php.ini) Path: /usr/local/etc/php/5.5
    Loaded Configuration File:         /usr/local/etc/php/5.5/php.ini
    Scan for additional .ini files in: /usr/local/etc/php/5.5/conf.d
    Additional .ini files parsed:      /usr/local/etc/php/5.5/conf.d/ext-mcrypt.ini
    
Thinking about a memory overload, I also cleaned the cache of Composer with the following command (because error message occurs during the `composer install` process):

    > composer clearcache

That was still useless in my situation, of course every used tools are up-to-date:

    > brew update
    > brew upgrade
    > composer selfupdate

I probably missed something simple but I didn't find the cause of my problem.

  [1]: http://stackoverflow.com/questions/12769982/reference-what-does-this-error-mean-in-php/12770179#12770179

**Comment by alcohol** [comment]
1. Please submit this issue at the brew project.
2. Don't use brew for composer.

**Comment by alcohol** [comment]
Also, why don't you just follow the install instructions at http://wp-cli.org/ ? They're much better than brew.

**Comment by jsalamin** [comment]
My goal is to centralize my tools and brew is a very interesting solution for that. It is easier to have one place to install/update/delete all the tools I need instead of having multiple independant tools with their own update commands/process.

Why are you suggesting to not use brew for composer? I don't have any issue with the other tools I'm using with brew and it was also working well with composer.... since now and this PHP Error :-(

As answer to your second question, I've installed `wp-cli` by following the instructions on the website but in my desire to regroup my tools and simplify the management of them, I wanted to install it using brew (listed as alternative install process: https://github.com/wp-cli/wp-cli/wiki/Alternative-Install-Methods).

**Comment by alcohol** [comment]
Because brew gets things wrong, more often than not. And then people come reporting issues here, which have nothing to do with the actual tool. You can see how that becomes tiresome after a while. For simple tools like this, I recommend just using their default install instructions.

**Comment by jsalamin** [comment]
Oky I'll follow your advice and install composer/wp-cli with the default install instructions instead of using homebrew.
I was not aware about this "brew layer" and the fact that such kind of tools may be affected like so.

Thank you for your explanation.
