### ISSUE TITLE
Production issue with autoload-dev > files

### ISSUE THREAD

**Issue by kirkbushell** [composer/composer#3922]
If you have autoload-dev configuration on production, and make a composer install like so:

    composer install --no-dev --optimize-autoloader

You'll encounter problems. Basically, composer is still loading in autoload-dev files, but if you have those files depend on dev-only installs, then you'll encounter missing files/classes errors.

However, this is avoided by doing:

    composer install --no-dev
    composer dumpautoload --optimize

So, there appears to be a bug with the optimize autoloader during an install prociess, if no-dev is provided.

**Comment by alcohol** [comment]
Can you provide a composer.json and step by step process to reproduce this? I'm willing to take a look, if you actually have something for me to look at.

**Comment by valorin** [comment]
Thanks @alcohol. I've been working with @kirkbushell on this one, and he was going to post some more information, but had to hop on a plane and won't be back online for many hours.

I'm trying to build a simple test case that will allow you to replicate the issue we're experiencing. I can replicate it 100% within our application, but I'm having trouble getting a working test-case with code I can actually share with you... I'm not sure yet if that means it's an issue with our app, or if it's an issue with composer that only shows up under specific circumstances.

I'll keep you posted :-)

**Comment by valorin** [comment]
@alcohol & @kirkbushell, this isn't technically a composer bug. 

Laravel 5's `php artisan optimize` command runs the `composer dump-autoload` command itself and has no way of knowing if it needs to add the `--no-dev` option or not - so it assumes dev and reloads the autoloader using both.

Is there a way for Composer to know if the dependencies were loaded with `--no-dev` or not, and have `dump-autoload` respect that automatically? 
I can't think of a single use case where you'd want to `composer install --no-dev` but purposely run `composer dump-autoload` without `--no-dev`.

**Comment by alcohol** [comment]
Can you share your composer json?

**Comment by valorin** [comment]
No worries, here is a simplified version of our composer.json:

```
{
    "require": {
        "php": ">=5.6.0",
        "curl/curl": "1.2.0",
        "erusev/parsedown": "1.5.*",
        "illuminate/html": "dev-master",
        "kirkbushell/eloquence": "~1.3",
        "laravelcollective/annotations": "~5.0",
        "laravel/framework": "5.0",
        "tectonic/laravel-localisation": "1.0.1",
        "tectonic/localisation": "dev-master"
    },
    "require-dev": {
        "league/factory-muffin": "~2.1",
        "league/factory-muffin-faker": "dev-master",
        "mockery/mockery": "dev-master@dev",
        "phpunit/phpunit": "^4.5.0"
    },
    "autoload": {
        "classmap": [
            "database/migrations"
        ],
        "psr-4": {
            "App\\": "app"
        },
        "files": [
            "app/Library/helpers.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/Tests",
            "Tests\\Unit\\": "tests/Unit",
            "Tests\\Integrated\\": "tests/Integrated",
            "Features\\": "tests/Features"
        },
        "files": [
            "tests/Features/Setup/Factories/definitions.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "post-create-project-cmd": [
            "php -r \"copy('.env.example', '.env');\"",
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}
```

The important bits to note are:

```
autoload-dev -> files -> tests/Features/Setup/Factories/definitions.php
```

and 

```
scripts -> post-install-cmd -> php artisan optimize
```

Running php after `composer install --no-dev`, results in this:

```
PHP Fatal error:  Class 'League\FactoryMuffin\Facade' not found in /.../tests/Features/Setup/Factories/definitions.php on line 7
```

The `php artisan optimize` command in `post-install-cmd` is not aware of the `--no-dev` flag is set, and cannot pass the flag on when it runs `composer dump-autoload --optimize` internally.

Does that make sense?

**Comment by alcohol** [comment]
Ok, I'm sorry to say this, but basically you don't have an issue, you are just doing it wrong.
Let me elaborate on that, because this statement probably seems a bit blunt.

You are using dumb script hooks, and by dumb I mean, they are not context aware. They are simple shell commands that are ran when composer reaches a certain point in its execution flow. So it makes perfect sense that your `php artisan optimize` is not aware of the `--no-dev` flag. It simply cannot be in this setup. Thus in turn, `composer dump-autoload` cannot be aware of this either. Therefor it will run with `--dev`, because this is the default.

So this is not a bug. This is simply the expected behaviour given this situation.

If you want your script hooks to be able to be context aware, you will need to write actual php scripts ([see here](https://getcomposer.org/doc/articles/scripts.md)).

**Comment by kirkbushell** [comment]
@alcohol yes - @valorin had already covered it and said what's going on ;)
