### ISSUE TITLE
VCS repository only loads dependencies in require, ignores require-dev

### ISSUE THREAD

**Issue by xeeeveee** [composer/composer#3924]
I'm including a private git repository hosted on bitbucket in a project by declaring it as a vcs repository.

This is all working perfectly, however the public dependencies of the private package are not loaded when using `composer install` unless they are in `require` - `require-dev` is ignored.

I am attempting to load in `codeception/codeception` via `require-dev` but it only works if it's in `required`

I can see codeception listed as `require-dev` when using `composer show vendor/package`

The below output of `composer show vendor/package` runs, But does not include codeception

    composer show vendor/package
    name     : vendor/package
    descrip. : Forms library
    keywords :
    versions : dev-master, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3
    type     : library
    license  :
    source   : [git] git@bitbucket.vendor/package.git c0b591e7852bf95fbda54c6a7d76a06b7316cafa
    dist     : []
    names    : vendor/package
    
    autoload
    classmap
    src/

    requires (dev)
    codeception/codeception *
    
The below output of `composer show vendor/package` setup runs and loads codeception and all it's dependencies

    composer show vendor/package
    name     : vendor/package
    descrip. : Forms library
    keywords :
    versions : dev-master, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3
    type     : library
    license  :
    source   : [git] git@bitbucket.vendor/package.git 4e6bff9782aa9b9c1ab0be1257984ea0cd272b72
    dist     : []
    names    : vendor/package
    
    autoload
    classmap
    src/
    
    requires
    codeception/codeception *

The default for `composer install` is to include `require-dev` and the project includes it's `require-dev` items, but the private package doesn't, it also states in the output that it is including `require-dev`:

    composer install -v
    Loading composer repositories with package information
    Reading composer.json of vendor/package (0.0.3)
    Importing tag 0.0.3 (0.0.3.0)
    Reading composer.json of vendor/package (0.0.4)
    Importing tag 0.0.4 (0.0.4.0)
    Reading composer.json of vendor/package (0.0.5)
    Importing tag 0.0.5 (0.0.5.0)
    Reading composer.json of vendor/package (0.0.6)
    Importing tag 0.0.6 (0.0.6.0)
    Reading composer.json of vendor/package (0.0.7)
    Importing tag 0.0.7 (0.0.7.0)
    Reading composer.json of vendor/package (0.0.8)
    Importing tag 0.0.8 (0.0.8.0)
    Reading composer.json of vendor/package (master)
    Importing branch master (dev-master)
    Installing dependencies (including require-dev)

Composer.json content of private package (Working):

    {
        "name": "vendor/package",
        "description": "Description",
        "type" : "library",
        "authors": [
            {
                "name": "Jack Neary",
                "email": "jack.neary@company.co.uk"
            }
        ],
        "require": {
            "codeception/codeception": "*"
        },
        "autoload": {
            "classmap": [
                "src/"
            ]
        },
        "autoload-dev": {
            "classmap": [
                "tests/"
            ]
        }
    }

Composer.json content of private package (Not working):

    {
        "name": "vendor/package",
        "description": "Description",
        "type" : "library",
        "authors": [
            {
                "name": "Jack Neary",
                "email": "jack.neary@company.co.uk"
            }
        ],
        "require": {},
        "require-dev": {
            "codeception/codeception": "*"
        },
        "autoload": {
            "classmap": [
                "src/"
            ]
        },
        "autoload-dev": {
            "classmap": [
                "tests/"
            ]
        }
    }

Is this intended behaviour or is there anything I have missed? Happy to supply more details on request.

Thanks,
Jack

**Comment by alcohol** [comment]
This is a case of basic reading 101:
https://getcomposer.org/doc/04-schema.md#require-dev

```
Certain fields only apply when in the root package context. One example of this is the config field. Only the root package can define configuration. The config of dependencies is ignored. This makes the config field root-only.
```

```
require-dev (root-only)
```

**Comment by xeeeveee** [comment]
Thanks for the fast response and clearing this up.

Sorry it was so simple in the end :/
