### ISSUE TITLE
Help for newbie

### ISSUE THREAD

**Issue by zoneclown** [composer/composer#3925]
![screenshot from 2015-04-11 12 01 09](https://cloud.githubusercontent.com/assets/11893405/7098212/d7f3ddec-e007-11e4-87b7-cf1c9b66e26f.png)

can you help me for fix this problem..??

i was tried for 3 times but got same problem..

please newbie want to learn

**Comment by phansys** [comment]
Duplicated of #3499.

**Comment by zoneclown** [comment]
problem solved

**Comment by alcohol** [comment]
Can you close it then?
