### ISSUE TITLE
require-dev / autoload-dev confusion

### ISSUE THREAD

**Issue by ancpru** [composer/composer#3926]
The docs says that require-dev and autoload-dev are root-only.

How can i trigger composer to include the require-dev and autoload-dev options of a package. For example:   Project "foo" requires a the package "bar". When i run composer update with --dev, all development packages and options from the foo-composer.json are handled. But I would also like to have the autoload-dev of the required package "bar" included, when i run composer. Is there a way to tell composer, that a required package is *also* needed with development-options? I cannot find anything in the docs. Or do I need to copy the -dev options from the package into the root-composer.json?

**Comment by phansys** [comment]
@ancpru, the "dev" requirement/autoloading are intended to be only for the (root) project that you are developing. That means 3rd party packages, libs, etc. are out of scope of your work (at least from "foo" project point of view).
If "foo" project also needs any requirement that are listed as dev in any of its dependencies, you must to explicitly require them for "foo".

**Comment by alcohol** [comment]
In sort, you need to copy the -dev options from the child package to your root package if those are absolutely required.

All signs in this case point to a broken dependency setup though. You are probably confused on what you should be putting in -dev and what not.

**Comment by ancpru** [comment]
Hi,

Well.. not really. The point is, that I try to develop (enhance and debug) a package as part of a project. Basically the package is independend and has it's own test-suits, so stand-alone development with --dev option is working fine.  Now the package get's some enhancements during the main project development, so I would like to have the development dependencies and paths of the sub-package used, too.

A flag to tell a requirement, that it should inherit the --dev setting of the parent project would be nice, e.g. requires    {"bar": "dev-master ?inheritdev"}  (or something like that). Anyway, it's no show-stopper if this is not possible.

**Comment by alcohol** [comment]
Not going to happen no. Also, -dev is for dependencies during development of a package. You should not be developing inside your `vendor/` directory.

**Comment by ancpru** [comment]
Yes, I know that I *should* not do it, but it's sometimes easier, if a basically independend package envolves as part of a product.
