### ISSUE TITLE
Parallel downloads for packages

### ISSUE THREAD

**Issue by nicolas-grekas** [composer/composer#3930]
This week-end, I played with adding concurrent downloads to the Installer of composer.
Using pcntl_fork(), I'm able to go from 4,5 minutes to 30s on some project. But that does not work well enough for this to go mainstream: errors in forks are not handled and state changes that happen during the install/update steps are hard to replicate on the parent process.

Thus, I may try a React based approach, plugged in the Installer loop (just here). Would that be an acceptable choice to you if I manage to go somewhere this way?

**Comment by alcohol** [comment]
Someone started on this quite a while ago. Never really finished it though. React is interesting and if you are willing to take the time, then by all means, do try.

Actually, it looks to be closed. See #3474

**Comment by carnage** [comment]
This might provide another aproach which may work: https://nikic.github.io/2012/12/22/Cooperative-multitasking-using-coroutines-in-PHP.html

**Comment by stof** [comment]
@carnage PHP 5.5+ is not an option for Composer. thus, if we keep using file_get_contents to download things, coroutines won't help us given that it is a blocking call.

**Comment by nicolas-grekas** [comment]
See #3951

**Comment by TomasVotruba** [comment]
@nicolas-grekas Awesome work!

**Comment by FractalizeR** [comment]
Yep. And there is a [Seldaek's response](https://github.com/composer/composer/pull/3951#issuecomment-111171316) also:

**Comment by nitso** [comment]
https://github.com/hirak/prestissimo

**Comment by TomasVotruba** [comment]
@nitso :+1:

**Comment by nicolas-grekas** [comment]
Note that it's not the same since this PR parallelized both HTTP requests and git fetches. But that's really nice to have a clean solution for HTTP!

**Comment by alcohol** [comment]
Well [hirak/prestissimo](/hirak/prestissimo) is more of a cache warm-up utility. Quite nice nonetheless. But as it depends on the cURL extension, Composer has not adopted such an approach itself.

**Comment by barryvdh** [comment]
It would be nice to have parallel downloads for the packagist info and zip archives, which should be possible for 5.3+ with curl_multi, like @hirak did.

**Comment by alcohol** [comment]
@barryvdh But that would add a dependency on the cURL extension, which some archaic hosting platforms do not support/offer. I think that is one of the major reasons why it was never used originally.

**Comment by barryvdh** [comment]
Yes but this can be detected right, so different drivers can be used. Like in #1628 and #2696 etc. I'm not sure what the percentage of people not having cURL installed is, but even if it's just 90%, it would give a huge boost to those benefiting. (In addition to other problems that people have with fil_get_contents, like #704 and #3772 etc)

**Comment by hirak** [comment]
I can rewrite "optional" curl_multi pre-fetch. It accelerate composer and not break BC.
I'd like to contribute my prestissimo's code.

```php
if (extension_loaded('curl')) {
  // execute pre-fetch by curl_multi
  if ($failure) {
     // do nothing
  }
}

//...

// fallback to Composer\Util\RemoteFilesystem
```

**Comment by TomasVotruba** [comment]
@hirak That would be really great. Thanks for looking at this

**Comment by barryvdh** [comment]
It would be smart to discuss your approach with @Seldaek before putting too much work into this.

**Comment by barryvdh** [comment]
It would also be nice to parallel download the package data from packagist, which are not big but by itself but do need to connect/transfer one by one..

**Comment by alcohol** [comment]
Yes, addressing something like this right before a 1.0 release is not a good time I think. To do it right, a lot of the downloading related code has to be refactored in order to avoid a ton of ugly `if ext_loaded then .. else ..` stuff (using adapters instead for example).

**Comment by barryvdh** [comment]
IMHO we should do this before the 1.0 stable release, because now we can make breaking changes more easily..

**Comment by alcohol** [comment]
Well, take it up with @Seldaek. I think it would be better suited for a 2.x release though, as it might require quite some effort. By releasing 1.0 first our users will have a stable version to hold on to (and different channels to update through).

**Comment by Seldaek** [comment]
Yeah there is no way this will happen before 1.0. If the download speed matters to you so much please use @hirak's plugin for now. It's a good stop-gap solution, and for sure we'll work towards including it in composer eventually but I rather take it slow and do it right than rush things through, the current situation isn't *that* bad given the local cache and so on.

**Comment by Koc** [comment]
is #7904 closes this issue?

**Comment by alcohol** [comment]
Among other things, yes. It is already closed.

**Comment by WyriHaximus** [comment]
Since composer v2 is out, I suppose this can be closed? Really enjoying the download and install performance improvements 🎉 !
