### ISSUE TITLE
Separate out platform packages from require

### ISSUE THREAD

**Issue by kayladnls** [composer/composer#3932]
Currently, [platform packages](https://getcomposer.org/doc/02-libraries.md#platform-packages) are treated the same as user-land dependencies. This seems a bit clunky to me, for a number of different reasons. 

For one, they're really different things. Secondly, it can be a bit difficult to correctly sort the packages https://github.com/composer/composer/pull/3872

It seems like it would make more sense to have them live separately. `require`, `require-dev`, `require-platform`. 

Thoughts? I'd be happy to submit a PR to accomplish this, if there is enough interest for such a thing.

**Comment by coderabbi** [comment]
Wouldn't you need ```require-platform``` and ```require-platform-dev``` as it's conceivable that there are platform dependencies unique to dev? It strikes me that platform dependencies are subsets of the context dependencies.

**Comment by kayladnls** [comment]
Why/how would your platform differ from dev to production? Can you give me an example? I would think that ideally you'd want your platform to be identical between the two.

**Comment by auroraeosrose** [comment]
Sadly we don't live in an ideal world - but for example I might have some dependencies on extensions that are only used for testing purpose (xdebug comes to mind) or profiling (uprofiler) in which case I do NOT want them dep'd on prod but DO want them on dev

**Comment by phansys** [comment]
I have a use case where for quality/performance reasons, PROD uses ```ext-imagick``` while DEV uses ```ext-gd```.

**Comment by kayladnls** [comment]
So, being that production and dev can vary, is it worth having `require-platform` and `require-platform-dev`, or is that too much complexity?

**Comment by coderabbi** [comment]
I pointed out the need for two additional dependency groups to emphasize the complexity. It seems like a lot simply to enable a 'cleaner' list. :shrug:

**Comment by tpavlek** [comment]
I personally don't see the clunkiness. Requiring a "provider" (as in omnipay or etc.) doesn't seem any different to me than any other dependency. You're still just pulling down additional classes to fill a need.

Or definitely not different enough to warrant another key (or two, as @coderabbi mentioned). Downvote from me on this one.

One solution I *would* support is potential grouping of requirements. eg:
```json
"require" {
    "omnipay": [
       "omnipay/stripe": "1.0.4",
       "omnipay/google-wallet": "~2.5"
    ],
    "other-dep/as-per-normal": "~1.0"
}
```json

Might add a bit more sanity without significantly increasing complexity.

**Comment by alcohol** [comment]
You say they are really different things. Are they not requirements then?

**Comment by localheinz** [comment]
:+1: for this proposal!

The difference between and `require` (or `require-dev`) and `require-platform` would be this:

You can actually pull in the requirements in `require` and `require-dev` with Composer.
You can't pull in the platform requirements with Composer.




```

**Comment by alcohol** [comment]
> You can't pull in the platform requirements in `require-platform` with Composer.

Not yet... #3897

**Comment by Seldaek** [comment]
I agree with @alcohol (man that nickname.. :p), there is no clear benefit so I'd rather avoid changes. Requirements are requirements.
