### ISSUE TITLE
Make composer terminal beep on interaction

### ISSUE THREAD

**Issue by michaelcullum** [composer/composer#3938]
When it asks for interactions such as for discarding changes to vendor files cause the terminal to beep

**Comment by alcohol** [comment]
I guess that would be the [Bell](http://en.wikipedia.org/wiki/Bell_character) character?

This could become highly annoying I reckon...

**Comment by Seldaek** [comment]
Yeah that sounds like the most annoying thing ever.

**Comment by kuiche** [comment]
Could be annoying if composer asked for prompting often. Idk about you though, but for regular usage I wouldn't expect it to beep much and may be a useful prompt for some.

**Comment by TomasVotruba** [comment]
:-1:

**Comment by alcohol** [comment]
Maybe present some arguments as to why this feature would be useful?

**Comment by slbmeh** [comment]
Interesting idea. It could indeed be an annoyance, but I know where it could be useful. I use guard to composer update on any changes detected to my composer.json, I keep my guard running in a background tab of my terminal. If interaction is required it will hang until notice it, which may be days later. A bell character would trigger my tab to flash and taskbar icon to bounce (visual bell configured in lieu of audio bell) and I could take care of it more promptly.

**Comment by kanariezwart** [comment]
Maybe it should more of a symfony2 thing? add an option like ```--audiobell``` to the console command?
```sh
tput bel
```

**Comment by Seldaek** [comment]
Indeed sounds like it'd be a nice improvement to Output command if done at symfony level and configurable via env var or something. Don't really want to take this responsibility on.
