### ISSUE TITLE
Composer init Author name not valid.

### ISSUE THREAD

**Issue by CupOfTea696** [composer/composer#3948]
Hi,

Whenever I run composer init and want to accept the default suggestion for Author, composer says it's an invalid author string. I know this is because my Github username has numbers in it, but I always manually modify the composer.json to add those anyway. Could the validation be modified so that it also accepts numbers in the Author string?

**Comment by alcohol** [comment]
This makes no sense.

https://github.com/composer/composer/blob/master/src/Composer/Command/InitCommand.php#L41-L56

Can you maybe tell us what error you are actually receiving? And what value for "author" you are submitting?

**Comment by CupOfTea696** [comment]
I'm sorry if I wasn't clear. I just took a screenshot you'll be able to see immediately what I meant.

![screen shot 2015-04-20 at 12 00 09](https://cloud.githubusercontent.com/assets/7327050/7228805/e3115520-e754-11e4-90c6-7121734e8f7a.png)

**Comment by alcohol** [comment]
Ok, I see why. I'll have a solution soon.

**Comment by alcohol** [comment]
On a side note, I recommend you use your actual real name in the author field, not some nickname. Author is the same as vendor, they do not have to match.

**Comment by CupOfTea696** [comment]
Yeah, that makes sense. Regardless, this way I can quickly accept it and then manually change the Author name and I don't have to type my email anymore :p

**Comment by shaikhAli** [comment]
hello , CupOfTea696 
did u get the solution for this as i am alsogetting the same error in composer init coomand

**Comment by alcohol** [comment]
@shaikhAli this issue has been resolved and you should no longer get this error (unless you are using an ancient version of Composer).

**Comment by shaikhAli** [comment]
thanx @alcohol 
issue is solved

**Comment by presslive** [comment]
hello everyone.. I have just installed composer and I have the same issue 
could someone help me please 
![Capture](https://user-images.githubusercontent.com/43686368/60408783-9e196000-9bc0-11e9-805c-75b46671ecbb.PNG)
