### ISSUE TITLE
Custom Installer Paths for some, not all, packages

### ISSUE THREAD

**Issue by digisavvy** [composer/composer#3949]
Hey there,
I read the doc on configuring custom install_paths for certain packages. If i'm understanding right, then this code aught to do the trick. I tried re-installing everything and the paths I defined are ignored. So I'm not sure what I may be doing wrong.

````
{
	"config": {
	       "vendor-dir": "library/vendors/composer"
	   },
    "require-dev": {
        "squizlabs/php_codesniffer": "2.*",
        "zamoose/themehookalliance": "dev-master",
        "tgm/plugin-activation": "dev-master",
        "wp-coding-standards/wpcs": "dev-master"
    },
    "scripts": {
        "post-install-cmd": [
            "library/vendors/composer/bin/phpcs --config-set installed_paths library/vendors/composer/wp-coding-standards/wpcs/"
        ]
    },
    "extra": {
        "installer-paths": {
            "library/vendors/{$name}": ["tgm/plugin-activation"],
            "library/vendors/{$name}": ["zamoose/themehookalliance"]
        }
    }
}

````

**Comment by slbmeh** [comment]
The `installer-paths` extra configuration directive is [composer/installers](https://github.com/composer/installers) not [composer/composer](https://github.com/composer/composer). That being said, it isn't a feature for arbitrary package installation, it's for recognized package types.

**Comment by digisavvy** [comment]
Thanks for the feedback. Muchly appreciated. =)
