### ISSUE TITLE
PHP Fatal Error: Failed opening required phar://composer.phar/bin/composer

### ISSUE THREAD

**Issue by andremaha** [composer/composer#395]
$ curl -s http://get composer.org/installer | php
# !/usr/bin/env php

All settings correct for using Composer

Composer successfully installed to: /full/path/here/composer.phar
Use it: php composer.phar

Whenn I do, I get the PHP Fatal Error. 
What to do?

**Comment by viper12345** [comment]
need your help,
i have a problem with composer, it was successfully installed

curl -s https://getcomposer.org/installer | php -d suhosin.executor.include.whitelist=phar
#!/usr/bin/env php
All settings correct for using Composer
Downloading...

Composer successfully installed to: /home/ploescat/laravel/composer.phar
Use it: php composer.phar

But when i do some command with composer.phar it was doing nothing
It was empty only return nothing 

$engine1# php composer.phar help
$engine1# php composer.phar install
$engine1# php composer.phar update
$engine1#

Any clues??

**Comment by oshanz** [comment]
same here, because of the Suhosin extension. 
i modified /etc/php5/fpm/conf.d/suhosin.ini file suhosin.executor.include.whitelist="phar"
solved

**Comment by stof** [comment]
@viper12345 if you modify the php config dynamically to pass the composer requirements, you also need to make the *same* change when calling composer.
