### ISSUE TITLE
Error Installing Composer on Windows 7 64-bit with Wampserver 2.5

### ISSUE THREAD

**Issue by LeoFelipe** [composer/composer#3950]
I'm trying to install the Composer on W7 64x. Using the installer for Windows that the site Composer provides (Composer-setup.exe).

I have installed the Wampserver 2.5 with php5.5.12 and Apache2.4.9. The openssl is enabled in php.ini.

I'm having the following errors in the installation:

Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error
messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation
failed
Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error
messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation
failed
Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error
messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation
failed
The download failed repeatedly, aborting.

**Comment by jakoch** [comment]
Hey,

it seems, that your system cert is outdated.
The error might resolve, after fetching a new certificate bundle.
- download http://curl.haxx.se/ca/cacert.pem and save as `ca-bundle.crt`
- update `php.ini` 
- add `curl.cainfo=/path/ssl/certs/ca-bundle.crt`
- add `openssl.cafile=/path/ssl/certs/ca-bundle.crt`
- retry installation

Alternatives:
- download [composer.phar](https://getcomposer.org/composer.phar) manually
- use a Windows server stack that ships Composer out-of-the-box, e.g. [WPN-XM](http://wpn-xm.org/)

**Comment by stof** [comment]
@jakoch your alternatives are not good. If the cafile is outdated, issues will happen again after that when using composer for the same reason (composer also needs to access https urls)

**Comment by jakoch** [comment]
ok

**Comment by alcohol** [comment]
See https://help.github.com/articles/error-ssl-certificate-problem-verify-that-the-ca-cert-is-ok/
