### ISSUE TITLE
Bump composer-plugin-api version?

### ISSUE THREAD

**Issue by legoktm** [composer/composer#3955]
We're currently in the process of updating our [composer-merge-plugin](https://github.com/wikimedia/composer-merge-plugin) to work with the latest alpha release and master and encountered a BC break (https://github.com/wikimedia/composer-merge-plugin/issues/22).

Does it make sense to bump the composer-plugin-api version for this? I didn't really look to see if there have been any other similar BC breaks.

**Comment by stof** [comment]
the constructor of the InstallerEvent is not part of the plugin-api IMO. Plugins are not responsible for instantiating the event but for listening on them

**Comment by Seldaek** [comment]
I'd tend to agree with @stof here, this refactoring was done carefully with regard to event listeners so we hopefully don't break anything (and it seems it mostly worked except for a couple people with wrong type hints that had issues).
