### ISSUE TITLE
I'm getting troubles with my routes but I don't know why! please help!

### ISSUE THREAD

**Issue by Jexaox** [composer/composer#3957]
Hello!

I don't have any problem when I try to access to http://learn.app/ or http://learn.app/home
but I cannot access to http://learn.app/api/todos.

I am getting this error in the browser:
![screen shot 2015-04-21 at 7 06 57 am](https://cloud.githubusercontent.com/assets/10733917/7251901/2c9e4a36-e7f5-11e4-9c8f-b73d125a9354.png)

and this is my routes.php:
![screen shot 2015-04-21 at 7 04 06 am](https://cloud.githubusercontent.com/assets/10733917/7251916/51dceb18-e7f5-11e4-9f91-4071e5c613e6.png)

I used 'php artisan route:list' to check my routes but I was getting an error in the terminal, I didn't know why but I solved that problem by commenting these two lines:
![screen shot 2015-04-20 at 2 31 53 pm](https://cloud.githubusercontent.com/assets/10733917/7251984/008ba33e-e7f6-11e4-9540-6a6deeba65ac.png)

and these are my results of 'php artisan route:list':
![screen shot 2015-04-20 at 2 27 36 pm](https://cloud.githubusercontent.com/assets/10733917/7251997/24cd78bc-e7f6-11e4-9a7a-a4f7c37e8c34.png)

I am so confused, can someone help me please?

**Comment by alcohol** [comment]
Uh..... hi, welcome to [composer/composer](https://github.com/composer/composer), here we answer all your **composer related** questions.

How can we help you?

**Comment by Bittarman** [comment]
Theres a couple of problems with this issue...

First up, this is a support request, its a bit rude to open bug tickets for a support request.

Secondly, its against the wrong project.

I'd suggest you close this, and pop into #laravel on freenode IRC, or post this on the laravel forums
