### ISSUE TITLE
Bundling composer with php distributions?

### ISSUE THREAD

**Issue by beporter** [composer/composer#3958]
This is a difficult topic [to google for](https://www.google.com/search?q=php+distributions+should+include+composer), so I thought I'd ask:

I dream of a day when on any machine, for a new enough version of PHP, if `$ php -v` works, `$ composer --version` also works. In other words: Installing PHP also installs composer.

Ruby, for example, eventually bundled RubyGems into the distribution of Ruby itself [as of v1.9](https://www.ruby-lang.org/en/libraries/). Golang is another example where the package management system [is a 1st party tool](https://golang.org/cmd/go/#hdr-Download_and_install_packages_and_dependencies) instead of a separate community addition.

It would be great to be able to guarantee that for a new enough version of PHP, I also always had composer available, "out of the box."

I realize there are probably all sorts of bureaucratic obstacles to this, not to mention a few technical ones, and I won't be surprised if this thread turns into an exhaustive explanation of why this will never happen, but I thought it would be worth asking.

**Comment by TomasVotruba** [comment]
IMO it's matter of time (months? years?), but I like the idea. I rarely found some packages that do not support composer by default, or are event against it, but it very very rare (1 so far).

I'm also glad you opened discussion. It's not easy to talk about, but would easy the build process to PHP newcomers in the future.

**Comment by Seldaek** [comment]
I agree it would be nice, but it's not something we can do here. This is about php internals endorsing it and then distros/installers (xampp & friends) bundling composer.
