### ISSUE TITLE
Ability to disable download percentage

### ISSUE THREAD

**Issue by jazzfog** [composer/composer#3961]
Since recently, composer started to display download status in percents

Now when you update your dependencies you see something like this:

>  Removing symfony/console (v2.6.5)
>  Installing symfony/console (v2.6.6)
>    Downloading: connection...
>    Downloading: 0%
>    Downloading: 5%
>    Downloading: 10%
>    Downloading: 15%
>    Downloading: 20%
>    Downloading: 25%
>    Downloading: 30%
>    Downloading: 35%
>    Downloading: 40%
>    Downloading: 45%
>    Downloading: 50%
>    Downloading: 55%
>    Downloading: 60%
>    Downloading: 65%
>    Downloading: 70%
>    Downloading: 75%
>    Downloading: 80%
>    Downloading: 85%
>    Downloading: 90%
>    Downloading: 95%
>    Downloading: 100%
>    Downloading: 100%
>
>  Removing symfony/dependency-injection (v2.6.5)
>  Installing symfony/dependency-injection (v2.6.6)
>    Downloading: connection...
>    Downloading: 0%
>    Downloading: 5%
>    Downloading: 10%
>    Downloading: 15%
>    Downloading: 20%
>    Downloading: 25%
>    Downloading: 30%
>    Downloading: 35%
>    Downloading: 40%
>    Downloading: 45%
>    Downloading: 50%
>    Downloading: 55%
>    Downloading: 60%
>    Downloading: 65%
>    Downloading: 70%
>    Downloading: 75%
>    Downloading: 80%
>    Downloading: 85%
>    Downloading: 90%
>    Downloading: 95%
>    Downloading: 100%
>    Downloading: 100%
>
>  Removing symfony/translation (v2.6.5)
>  Installing symfony/translation (v2.6.6)
>    Downloading: connection...
>    Downloading: 0%
>    Downloading: 5%
>    Downloading: 10%
>    Downloading: 25%
>    Downloading: 30%
>    Downloading: 35%
>    Downloading: 40%
>    Downloading: 45%
>    Downloading: 50%
>    Downloading: 60%
>    Downloading: 65%
>    Downloading: 70%
>    Downloading: 75%
>    Downloading: 80%
>    Downloading: 90%
>    Downloading: 95%
>    Downloading: 100%

It is inconvenient because
- It's hard to overview all updates in one glance
- If update is large - on windows you can't scroll up and see all the log - it loses it
- Sometimes you want to keep your dependencies in VCS and commit updates with comment containing composer log, sou you can see easily what was updated. With such output - it's hard to get readable list of changes.

Please, add ability to disable this percentage.
Some console key would be great way out.

**Comment by pborreli** [comment]
did you tried `composer update --no-progress` ?

**Comment by hkdobrev** [comment]
@jazzfog You could use the `--no-progress` option. As far as I know this hasn't changed recently, but some shells (or if you pipe your output) would print every step of the download on a new line instead of updating it on the same line.

**Comment by padraic** [comment]
It's handled internally. The IO class could check if the Symfony Output object isDecorated() evaluates to true or false, and then change how this is handled. Either disabling or perhaps modifying the rate at which the download progress see an attempted overwrite.

See https://github.com/composer/composer/blob/master/src/Composer/Util/RemoteFilesystem.php#L330

**Comment by jazzfog** [comment]
@pborreli, @hkdobrev i did not try, it is not show when you execute `composer --help`
Thank you, this is what I needed!

**Comment by pborreli** [comment]
it shows when you run `composer help update` 
glad it helped you

**Comment by pborreli** [comment]
could you please close this issue ?

**Comment by jazzfog** [comment]
Thank you!
