### ISSUE TITLE
Private package dependencies

### ISSUE THREAD

**Issue by michaeljs1990** [composer/composer#3964]
Just seeing if this is intended functionality or just not a use case that many people run into so the feature hasn't been developed.

example:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/secret/repo"
        }
    ],
    "require": {
        "secret/repo": "dev-master"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

```json
{
     "name": "secret/repo",
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/secret/repo2"
        }
    ],
    "require": {
        "secret/repo2": "dev-master"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

When I go to install the first package it doesn't seem to take into account the second repository but if i add that repository into the repository array of the first package everything works. It seems odd to me that composer should ignore this.

Thanks,

**Comment by frederikbosch** [comment]
This expected behaviour, see [the last paragraph of the repositories documentation](https://getcomposer.org/doc/05-repositories.md#repository).

Continue reading on setting up Satis, and close this issue.

**Comment by michaeljs1990** [comment]
Thanks will do :+1:
