### ISSUE TITLE
using different composer.json files

### ISSUE THREAD

**Issue by benyitzhaki** [composer/composer#3968]
I have my project on a single repository with 2 branches - master (for production) and dev for tests. each of those branches should use different version of the same dependencies. The way i thought to achieve this was using 2 different composer.json files (composer.json & composer.dev.json) and later on run the composer install using one those (depending on a server variable). is it possible?

to sum it up.. the following command could be awesome (like in grunt):
"composer install --file composer.dev.json"

**Comment by bamarni** [comment]
you could simply have a different composer.json file on each branch no?

**Comment by benyitzhaki** [comment]
that's an option,however, it also says that whenever i merge any branch into the master i have to make sure that the composer.json file is not being merged also.. as they should always be different. sounds to me like bad behavior.. ain't there a better way?

**Comment by Henk8** [comment]
How did you solved this problem, I ran into the same problem? Can you include the composer.json?

**Comment by quantumpacket** [comment]
@Henk8 just visit the above link. It's nothing to do with a composer.json setting, but rather setting the COMPOSER environment variable to specify the name of the composer.json file to use. So you just set it to use your whatever_name.json file.
