### ISSUE TITLE
Support composer.json as dotfile

### ISSUE THREAD

**Issue by marcinant** [composer/composer#3972]
'composer.json' is file which is unrelated to project source code and should be considered as so called "dotfile".

Is it possible to change current convention or add an option to support '.composer.json', '.composerrc' or just '.composer' instead of 'composer.json' (and 'composer.lock')?

These files should be hidden by default as they are not part of project.

**Comment by Seldaek** [comment]
We could eventually do it for the lock file, but changing the name for composer.json would take a whole lot more load on the github API usage as we'd have to check two paths.

That said, changing filenames is a pain for tooling as many other things expect the files to be called the way they are, and getting everyone to update takes time so unless it's really worth it I'd tend to be against it.
