### ISSUE TITLE
Composer doesn't recognize tagged version

### ISSUE THREAD

**Issue by sergeylukin** [composer/composer#3973]
Hi,

I have following package repo: https://github.com/openmvc/codeception-openmvc-module
Most recent tag is named `0.1.12`
Packagist successfully recognized it: https://packagist.org/packages/openmvc/codeception-openmvc-module

However, following command fails to install:

```
composer require openmvc/codeception-openmvc-module@0.1.12
```

while following succeeds:

```
composer require openmvc/codeception-openmvc-module@0.1.11
```

What's wrong with 0.1.12? Is there anything I'm doing wrong?
Thanks

**Comment by Seldaek** [comment]
I fixed it by hitting the force update button on your package which triggered an update of the json metadata files packagist uses. I don't know if that was a race condition in the db or what, haven't seen this before so hopefully it won't come up again.

**Comment by sergeylukin** [comment]
Thank you!
