### ISSUE TITLE
drop ext/ctype dependency

### ISSUE THREAD

**Issue by staabm** [composer/composer#3976]
requiring less dependencies is a good thing for a fundamental tool like composer is.

what do you think about rewriting stuff to "simple" sanity checks instead of relying on ext/ctype?
could provide a PR if you agree with it.

**Comment by rdlowrey** [comment]
:+1:

`ext/ctype` is a constant source of annoyance in php projects for folks who compile custom php builds. `--disable-all` is a common build option and it breaks userland libs that rely on the largely superfluous `ctype_*()` functions.

Whenever possible it's useful to avoid this dependency.

**Comment by staabm** [comment]
side-note: `ext/filter` could be dropped in a separate PR

**Comment by marc-mabe** [comment]
It looks like `symfony/yaml` is using the ctype extension, too:
```
grep -iHrn 'ctype_' *
src/Composer/Package/Loader/ArrayLoader.php:150:           $time = ctype_digit($config['time']) ? '@'.$config['time'] : $config['time'];
vendor/symfony/yaml/Symfony/Component/Yaml/Inline.php:124: case ctype_digit($value):
vendor/symfony/yaml/Symfony/Component/Yaml/Inline.php:483: case ctype_digit($scalar):
vendor/symfony/yaml/Symfony/Component/Yaml/Inline.php:488: case '-' === $scalar[0] && ctype_digit(substr($scalar, 1)):
```

**Comment by staabm** [comment]
@marc-mabe thanks for pointing that out. Will PR their, too.

**Comment by marc-mabe** [comment]
@staabm I currently noted `symfony/yaml` is only used in development note so no issue there -> but indeed `symfony/yaml` should add that to it's require section.

**Comment by marc-mabe** [comment]
@staabm I already provided a PR as it was a one liner and I currently was on the code ;)

**Comment by Seldaek** [comment]
I'm fine with this one but I'd rather keep the filter ext.

**Comment by staabm** [comment]
@marc-mabe thx looks good.

**Comment by staabm** [comment]
@marc-mabe as discussed I added a PR which drops ext/ctype in symonfy/yaml see https://github.com/symfony/symfony/pull/14509
