### ISSUE TITLE
Autoload: Add support to check right case of files and classes

### ISSUE THREAD

**Issue by marc-mabe** [composer/composer#3979]
This is a feature request to add support to throw an exception if a class was loaded with wrong case (on case-insensitive filesystems).

This would be helpful for a wide range of developers:
 * developing on OSX/Windows (even if using a VM+shared folder) and deploy to unix like servers
 * developing libs on OSX/Windows

By sure this additional check should only be in development phase!

How to check:
* Is the file available in the right case before including it
  * this could be done like `$file === realpath($file)`
* after loading a class the real loaded class name should be checked
 * this could be checked using `get_declared_classes()` `get_declared_interfaces()` `get_declared_traits()` like this:
    ```php
class test {}
$class = 'TEST';

$table = get_declared_classes() + get_declared_interfaces() + get_declared_traits();
$table = array_change_key_case(array_combine($table, $table), CASE_LOWER);
if ($class === $table[strtolower($class)]) ...
    ```
  * .. or using `ReflectionClass`
  * using `::class` doesn't work -> see http://3v4l.org/sWCcA

**Comment by Seldaek** [comment]
You don't need composer for that, you can easily wrap the composer autoloader and do detection after calling it every time.

i.e.

```php
$loader = include 'vendor/autoload.php';
$loader->unregister();
spl_autoload_register(function($class) use ($loader) {
    if ($loader->loadClass($class)) {
        // ... magic here ... 
    }
});
```

**Comment by stof** [comment]
FYI, the Symfony Debug component already provides such logic in its DebugClassLoader (alongside some other checks). It is usable in any project
