### ISSUE TITLE
Unexpected exit code from Composer (255)

### ISSUE THREAD

**Issue by mathewhany** [composer/composer#3980]
I was using composer with no problem when something happened and I thought there was a problem with my version of composer, so I ran "composer self-update", and this cause some kind of error, therefore I delete C:\ProgramData\ComposerSetup, and I'm now trying to reinstall composer, but I get this error "Unexpected exit code from Composer (255)", and when I download ComposerSetup.exe again from the site I get network error!

This is really annoying. I don't know what happened!

**Comment by Seldaek** [comment]
Can you try to download https://getcomposer.org/download/1.0.0-alpha10/composer.phar with your browser and then run `php composer.phar diagnose` to see if that works?

**Comment by mathewhany** [comment]
I can't download it, It fails.

I think there is a problem with composer servers because I can't download ComposerSetup.exe or composer.phar or any file!

**Comment by Seldaek** [comment]
What do you mean it fails? What do you see in your browser? Can I see a screenshot or something of the error? Can you access https://getcomposer.org at all?

**Comment by mathewhany** [comment]
Yes, I can access https://getcomposer.org! But I can't download any file!  However, I could download it form github, and I tried "composer require slim/slim", it took 2 hours and for some reason nothing happened, It didn't download anything, it didn't show any error! I tried composer self-update again! and here what I get:

Fatal error: Uncaught exception 'PharException' with message 'phar "C:\ProgramDa
ta\ComposerSetup\bin\composer.phar" has a broken signature' in C:\ProgramData\Co
mposerSetup\bin\composer.phar:23
Stack trace:
#0 C:\ProgramData\ComposerSetup\bin\composer.phar(23): Phar::mapPhar('composer.p
har')
#1 {main}
  thrown in C:\ProgramData\ComposerSetup\bin\composer.phar on line 23

**Comment by Seldaek** [comment]
Network error.. that's not quite descriptive :/

Do you have curl on the command line by any chance? If not you can get one of the free versions from http://www.confusedbycode.com/curl/ to get it installed, and then if you can run `curl -v https://getcomposer.org/version` and paste the output it'd be great.

**Comment by mathewhany** [comment]
*   Trying 87.98.253.108...
* Connected to getcomposer.org (87.98.253.108) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:\Users\Mathew\AppData\Local\Apps\cURL\bin\curl-ca-bundle.crt
  CApath: none
* TLSv1.2, TLS Unknown, Unknown (22):
* TLSv1.2, TLS handshake, Client hello (1):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Server hello (2):
* NPN, negotiated HTTP1.1
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, CERT (11):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Server key exchange (12):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Server finished (14):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Client key exchange (16):
* SSLv2, Unknown (20):
* TLSv1.2, TLS change cipher, Client hello (1):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Unknown (67):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Finished (20):
* Unknown SSL protocol error in connection to getcomposer.org:443
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to getcomposer.org:443

**Comment by Seldaek** [comment]
Can you also try `curl -v https://packagist.org/packages.json` see if that errors out the same?

**Comment by mathewhany** [comment]
*   Trying 87.98.253.214...
* Connected to packagist.org (87.98.253.214) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:\Users\Mathew\AppData\Local\Apps\cURL\bin\curl-ca-bundle.crt
  CApath: none
* TLSv1.2, TLS Unknown, Unknown (22):
* TLSv1.2, TLS handshake, Client hello (1):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Server hello (2):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, CERT (11):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Server key exchange (12):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Server finished (14):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Client key exchange (16):
* SSLv2, Unknown (20):
* TLSv1.2, TLS change cipher, Client hello (1):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Finished (20):
* SSLv2, Unknown (20):
* TLSv1.2, TLS change cipher, Client hello (1):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*        subject: C=CH; ST=Z?rich; L=Z?rich; O=Nelmio AG; CN=packagist.org
*        start date: 2014-06-30 00:00:00 GMT
*        expire date: 2017-08-01 12:00:00 GMT
*        subjectAltName: packagist.org matched
*        issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*        SSL certificate verify ok.
* SSLv2, Unknown (23):
> GET /packages.json HTTP/1.1
> Host: packagist.org
> User-Agent: curl/7.42.0
> Accept: */*
>
* SSLv2, Unknown (23):
< HTTP/1.1 200 OK
< Server: nginx
< Date: Thu, 30 Apr 2015 09:03:35 GMT
< Content-Type: application/json
< Content-Length: 1072
< Connection: keep-alive
< Last-Modified: Thu, 30 Apr 2015 09:00:24 GMT
< Accept-Ranges: bytes
<
{"packages":[],"notify":"\/downloads\/%package%","notify-batch":"\/downloads\/","providers-url":"\/p\/%package%$%hash%.json","search":"\/search.json?q=%query%","provider-includes":{"p\/provider-2013$%hash%.json":{"sha256":"21b82eaf50053f0ae3b84950a29a6c49bae9dc4f535f20986577ef411908d8b7"},"p\/provider-2014$%hash%.json":{"sha256":"4736b8e831f9c890479e7659d83d9f8947b5c2b44df95de580bebffea902258a"},"p\/provider-2014-07$%hash%.json":{"sha256":"f7def7da976f2df230ffd5e1b5ea0b4603ddaa3e3c377942ee226702c303a320"},"p\/provider-2014-10$%hash%.json":{"sha256":"c124288226dd6809d5707d25519c171e13a903152b61bea5cbd27a3072c420ed"},"p\/provider-2015-01$%hash%.json":{"sha256":"a58aa874f0d4fdc621ae0ba4cfde7ddc3a72acaf70cf3807c7d8438583243a94"},"p\/provider-2015-04$%hash%.json":{"sha256":"b5190d79fe044148a07e7b1e485083fd306a23cef10811db7a8993af0ae2c163"},"p\/provider-archived$%hash%.json":{"sha256":"9cf66c7784274c6616b3d24de00b79125648cd7d720435d5c3c208e537be6190"},"p\/provider-latest$%hash%.json":{"sha256":"0d387225ca15b8c083de354b85e9025f1954a1874860f2dffbb9a068f53b0cd9"}}}* Connection #0 to host packagist.org left intact

**Comment by Seldaek** [comment]
Ok interesting.. can you try again the getcomposer one please? I tweaked the SSL config a bit to see if that helps.

**Comment by mathewhany** [comment]
Still the same error

**Comment by mathewhany** [comment]
Hay! I don't know what happened but I have another error now in ComposerSetup.exe

Connection Error [ERR_CONNECTION]: Unable to connect to getcomposer.org

Request to https://getcomposer.org/installer failed with errors:
SSL: An existing connection was forcibly closed by the remote host.
. Failed to open stream: HTTP request failed!

**Comment by Seldaek** [comment]
Damn ok. I'm not sure what's causing this from the output it's not quite clear to me. 

@rdlowrey sorry to nag you every time but if you have any clue it'd be appreciated :)

**Comment by mathewhany** [comment]
Oh! I don't know how but now every thing works perfectly :smiley: :+1:

I really mean every thing ComposerSetup.exe and https://getcomposer.org and everything, whatever you did, THANK YOU!

**Comment by Seldaek** [comment]
Well the funny thing is I didn't do anything, but I am glad it works.. I wonder if it's your internet provider doing funky things to SSL traffic.
