### ISSUE TITLE
AuthHelper askAndValidate Always Causes exception

### ISSUE THREAD

**Issue by daum** [composer/composer#3987]
In AuthHelper where it asks if you want to store the credentials (https://github.com/composer/composer/blob/master/src/Composer/Util/AuthHelper.php#L39) it passes through "false" for the third option to the IO helper (https://github.com/composer/composer/blob/master/src/Composer/IO/ConsoleIO.php#L247) to pass it as a false to the Symfony\Component\Console\Question\Question class which results in an InvalidArgumentException being thrown as seen here: https://github.com/symfony/Console/blob/master/Question/Question.php#L194

This means any time that the helper asks that question it will cause an exception to be caused, breaking any install/update that is currently being run.  Will make PR momentarily.

**Comment by alcohol** [comment]
My bad. I'll give the whole src another thorough look for calls to `askAndValidate`.

**Comment by alcohol** [comment]
Never mind, seems that was the only one I missed. Thanks. 

@Seldaek please merge asap. Sorry for the inconvenience.

**Comment by Seldaek** [comment]
Thanks @daum!
