### ISSUE TITLE
Circular dependancy doesn't register

### ISSUE THREAD

**Issue by hackzilla** [composer/composer#3990]
After trying to push an update to a private bundle this morning, I noticed that Composer was completely ignoring.  I thought it was a corrupted version, but it wouldn't install any previous versions.

Some how my bundle had itself as a dependancy, which the last time I install it worked (March 2015).

```
git clone https://github.com/hackzilla/TestBundle.git test
cd test
composer install
```

Whilst agree that this shouldn't install itself, it should issue a warning/error, and not silently ignore it.

**Comment by Seldaek** [comment]
Seems fine to me.. you require a package that is already there so it doesn't install it. It also doesn't tell you it's not installing php or any other package you already have when you do an install/update.

**Comment by hackzilla** [comment]
in this example it is a bit pointless. 

However try and use that bundle as a dependancy.
You will not be able to install / update it.

**Comment by hackzilla** [comment]
e.g.

```
cat composer.json 
{
    "name": "hackzilla/test-project",
    "description": "",
    "repositories": [
        {
          "type": "vcs",
          "url":  "git@github.com:hackzilla/TestBundle.git"
        }
    ],
    "require": {
        "hackzilla/test": "dev-master"
    },
    "authors": [
        {
            "name": "Daniel Platt",
            "email": "github@ofdan.co.uk"
        }
    ]
}

composer install

Loading composer repositories with package information
Installing dependencies (including require-dev)       
Nothing to install or update
Generating autoload files
```

**Comment by Seldaek** [comment]
Ah I see.. That is weird indeed.

Not really a real use case though so not exactly an urgent problem right?

**Comment by hackzilla** [comment]
Not urgent.

However I lost 3 hours of my morning, trying to debug this.
No idea how the dependancy got put into my bundle, but it potentially could help others.

The strange thing is only stopped working sometime in the last 2 months.

**Comment by naderman** [comment]
@hackzilla can you test if this is fixed with the latest version of composer?

**Comment by hackzilla** [comment]
I can confirm its working with composer version 6d1e8ebf90542a7c65ac6661f6c47b1d655641d9

Cheers.
