### ISSUE TITLE
No ending composer update with --prefer-lowest

### ISSUE THREAD

**Issue by Soullivaneuh** [composer/composer#3993]
`--prefer-lowest` option does not work anymore. Composer still blocking on dependencies update:

```bash
$ composer update --prefer-dist --no-interaction --prefer-lowest
Loading composer repositories with package information
Updating dependencies (including require-dev)
# Composer does nothing more starting here
```

With latest composer version:

```
Composer version 1.0-dev (b7c827c2e5cc407496ea90e3334ad41124b93da5) 2015-05-01 14:50:01
```

You can see the same problem on Travis: https://travis-ci.org/hwi/HWIOAuthBundle/jobs/61021341#L111

**Comment by Soullivaneuh** [comment]
Works with the following version:

```
Composer version 1.0-dev (a32c91914558a3ff293d83f7b99c49f4a7931798) 2015-04-18 18:11:12
```

**Comment by Soullivaneuh** [comment]
Any new @Seldaek?

**Comment by Soullivaneuh** [comment]
Have you any fix or, at least, any clue?

A concrete sample with a Travis job: https://travis-ci.org/sonata-project/SonataUserBundle/jobs/66214832

**Comment by slbmeh** [comment]
It just takes a bit of time. E.g. longer than 10 mins.

Use travis_wait http://docs.travis-ci.com/user/build-timeouts/

```
working in ~/projects/gh-3993/HWIOAuthBundle on (HEAD detached from 97e3c15)
$ time sudo nice -n -10 composer update --prefer-dist --prefer-lowest
Loading composer repositories with package information
Updating dependencies (including require-dev)
<< snip >>
Writing lock file
Generating autoload files

real    18m56.301s
user    18m8.750s
sys     0m14.220s
```

**Comment by slbmeh** [comment]
That's with hwi/HWIOAuthBundle#773 applied to `97e3c15` btw...

**Comment by Soullivaneuh** [comment]
@slbmeh Well, thanks for the trick I'll test it.

But I'll let this issue opened. 20 minutes for a lowest deps install, it's a little bit to much, isn't it?

Regards.

**Comment by Seldaek** [comment]
I don't really see any commit between those two you mentioned as working/non-working that could cause such a solving time difference. And I tried comparing your two commits to latest master and there is no large difference in solving time (which is around 6minutes for me with `composer update --prefer-dist --prefer-lowest --dry-run`)

The main issue is the large amount of possible versions you require.. Simply bumping all symfony/* requirements to ~2.3 helps a great deal, bringing the time down to 40seconds for me.

**Comment by Soullivaneuh** [comment]
> Simply bumping all symfony/* requirements to ~2.3 helps a great deal

Well yes. But it does not solve the concerned issue, it is?

**Comment by Seldaek** [comment]
I don't know if we can solve the concerned issue at all, you are asking 
for performance improvement in general. Yes we can work on that, but 
this has nothing to do with your package or this issue in particular.

And given that symfony 2.1/2.2 have been out of support for quite a 
while, I don't think releasing a new version of your bundle that does 
not support these anymore is such a big deal.

**Comment by Soullivaneuh** [comment]
Yeah I'm not talking about Symfony version but composer managment itself.

Thanks for the clue anyway. :+1:

**Comment by jvasseur** [comment]
I think removing the minimum-stability flag and only allowing specific packages to get a dev version would improve the performances in this case.

**Comment by Soullivaneuh** [comment]
@Seldaek Another timeout issue on Travis: https://travis-ci.org/sonata-project/SonataUserBundle/jobs/66365243#L107

And no Symfony `<2.3` dependencies here. Any idea? Thanks.

> I think removing the minimum-stability flag and only allowing specific packages to get a dev version would improve the performances in this case.

@jvasseur This is just a workaround, not a fix. But thanks for the indication.

**Comment by Seldaek** [comment]
@Soullivaneuh that one with --dry-run finished for me in 53seconds but it uses quite a bit of RAM so it might be swapping on travis leading to extremely slow resolution, or perhaps it's the amount of packages that get installed with --prefer-source taking too long to clone. Have you considered using --prefer-dist and enabling the travis cache for the composer dir?

**Comment by Soullivaneuh** [comment]
> Have you considered using --prefer-dist and enabling the travis cache for the composer dir?

It's under discussion with @rande because in need GitHub token for that. :-)

**Comment by Soullivaneuh** [comment]
But --prefer-dist would change package download system only, not resolution, isn't it @Seldaek?

**Comment by Seldaek** [comment]
Yes sure, but for me the resolution takes 50seconds which is reasonable 
given the dependency set IMO.. Whether that's too much RAM for travis I 
do not know.

**Comment by Soullivaneuh** [comment]
Stop me if I'm wrong, but each Travis build has 3GB of ram, is that not enough for composer?

How much RAM was used on your side?

**Comment by Seldaek** [comment]
just under 1GB so yeah that should be enough.

**Comment by slbmeh** [comment]
I've noticed with our builds that depend on symfony each release is a large jump in time to solve.  I generally fix it by tightening the version constraints.  I fortunately have a large amount of freedom to have strict/tight requirements on packages because they aren't publicly consumed.
