### ISSUE TITLE
Connection error when installing composer

### ISSUE THREAD

**Issue by JackShannon** [composer/composer#3995]
Platform: Windows

I have composer installed, when I run 'composer self-update', I get the following:

[Composer\Downloader\TransportException]
The "https://getcomposer.org/version" file could not be downloaded: failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed b
ecause connected host has failed to respond.

So I then tried to reinstall composer with the windows installer, I get the following:

Connection Error [ERR_CONNECTION]: Unable to connect to getcomposer.org

Request to https://getcomposer.org/installer failed with errors:
Failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

Is the server down?

**Comment by lqsun** [comment]
It seems internet connect need proxy, however, this win installer only supports connect directly.

**Comment by agwidarsito** [comment]
Install a Windows level VPN or proxy switcher that acts as the default route. Try CyberGhost

**Comment by lqsun** [comment]
thx a lot

**Comment by JulietaCD** [comment]
I got this error

Help me please

The “https://getcomposer.org/versions” file could not be downloaded: failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
