### ISSUE TITLE
How to create autoloaders for nested dependencies?

### ISSUE THREAD

**Issue by marcinant** [composer/composer#3996]
I would like to create staging server for wordpress development with 'composer' and 'composer-installers'

1. I created composer.json which installs:
- wp core to /wordpress dir
- some wp-plugins which goes to /wp-content/plugins
2. In this way I got WP structure ready to use with some server Apache/Nginx/whatever

Thing is that I would like to develop wp-theme which is composer package as well.
I can add this theme as another dependency and while it's "type":"wp-theme" it's going to be installed to /wp-content/themes/

However my theme has some dependencies as well and has it's own autoloader.
Unfortunately these dependencies are not fetched and installed. Is there a simple way to force composer to download dependencies for nested package and regenerate it's autoloader?

**Comment by stof** [comment]
Well, if the theme declares its dependencies in its composer.json, Composer will install them and autoload them.

**Comment by marcinant** [comment]
@stof Problem is that autoloader is generated in project root.

So, folder structure is:
```
/wp
/wp-content
/wp-content/themes/sometheme
/vendor
/vendor/autoloader.php
```
While I would like to get:
```
/wp
/wp-content
/wp-content/themes/sometheme
/wp-content/themes/sometheme/vendor/autoloader.php
/wp-content/themes/someothertheme
/wp-content/themes/someothertheme/vendor/autoloader.php
/vendor
```

Themes cannot depend on autoloader located elsewhere. They need to contain dependencies and autoloader in their own folder.

**Comment by slbmeh** [comment]
The theme shouldn't have to depend on an autoloader if it's a composer package, your autoloader should already be included by your application, such as your wordpress front controller.

**Comment by vburlak** [comment]
+1 Have the same issue

**Comment by marcinant** [comment]
> The theme shouldn't have to depend on an autoloader if it's a composer package, your autoloader should already be included by your application, such as your wordpress front controller.

There are two different situations:

1. When I would like to use `composer` with custom installers to install wordpress instance + themes + plugins and set up fully workable website

2. Another thing is that I would like to develop some classes and use them as a part of theme.

So, when I join above then I got a problem. I can use composer to compose wordpress website with plugins and themes. Unfortunately these themes don't get their dependencies recursively and are useless/broken. I could define these dependencies in point 1 however this is not a solution as WP themes are separate packages and can be distributed as zip files which need to be selfcontaining (autoloader + dependencies).

**Comment by slbmeh** [comment]
If your theme has it's dependencies declared in the composer.json they will be installed under vendor for the root package, and the autoloader will be aware of them.

**Comment by marcinant** [comment]
>If your theme has it's dependencies declared in the composer.json they will be installed under vendor for the root package, and the autoloader will be aware of them.

It's not true.

There are two `composer.json` files.
One for website.
Second for theme in theme subdirectory.

When I run `composer install` or `composer update` in website dir then dependencies from `composer.json` in theme subdirectory are not loaded/installed.

**Comment by slbmeh** [comment]
@marcinant why two files?

**Comment by fulippo** [comment]
+1 I have the same identical issue. When installing the root package only dependencies declared at root level are satisfied.

I am using composer-installers too.

**Comment by slbmeh** [comment]
@fulippo can you give me more details?  What does your `composer.json` look like?

**Comment by fulippo** [comment]
@slbmeh [here](https://gist.github.com/fulippo/426d664d51a7bcb05b4f) you can find a gist with both composer.json files.

When composer tries to install `company/wp-unit-tests` from `require-dev` only the package sources are installed. As you can see from the gist, the package depends on `phpunit/phpunit` which is not installed ignoring its dependencies.

If you move `company/wp-unit-tests` to the `require` node of root's composer.json everything works fine.

Is that a know/wanted behaviour?

**Comment by fulippo** [comment]
Sorry, my fault. It was one of the script interfering. Do not consider the message above.

Thank you
