### ISSUE TITLE
Composer update not working

### ISSUE THREAD

**Issue by duikb00t** [composer/composer#3997]
composer update -v

                                                          
  [Symfony\Component\Process\Exception\RuntimeException]  
  The process has been signaled with signal "5".          
                                                          

Exception trace:
 () at phar:///usr/local/bin/composer/vendor/symfony/process/Symfony/Component/Process/Process.php:367
 Symfony\Component\Process\Process->wait() at phar:///usr/local/bin/composer/vendor/symfony/process/Symfony/Component/Process/Process.php:210
 Symfony\Component\Process\Process->run() at phar:///usr/local/bin/composer/src/Composer/Util/ProcessExecutor.php:62
 Composer\Util\ProcessExecutor->execute() at phar:///usr/local/bin/composer/src/Composer/Package/Loader/RootPackageLoader.php:320
 Composer\Package\Loader\RootPackageLoader->guessSvnVersion() at phar:///usr/local/bin/composer/src/Composer/Package/Loader/RootPackageLoader.php:188
 Composer\Package\Loader\RootPackageLoader->guessVersion() at phar:///usr/local/bin/composer/src/Composer/Package/Loader/RootPackageLoader.php:58
 Composer\Package\Loader\RootPackageLoader->load() at phar:///usr/local/bin/composer/src/Composer/Factory.php:268
 Composer\Factory->createComposer() at phar:///usr/local/bin/composer/src/Composer/Factory.php:486
 Composer\Factory::create() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:222
 Composer\Console\Application->getComposer() at phar:///usr/local/bin/composer/src/Composer/Command/Command.php:53
 Composer\Command\Command->getComposer() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:86
 Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:146
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:83
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:25

How can I solve this? 

Thanks a lot.

**Comment by Seldaek** [comment]
Please check https://github.com/composer/composer/issues/2146#issuecomment-69469119 and try to run `composer diagnose` as well.

**Comment by thepipecat** [comment]
+1
