### ISSUE TITLE
ClassLoaderTest fails all the time

### ISSUE THREAD

**Issue by SpacePossum** [composer/composer#3999]
When running the tests local I keep on running into this problem.
(running tests on master @ 42a9561ae23b236da1d5a4acf50f7ea96ebe68aa)

`phpunit tests/Composer/Test/Autoload/ClassLoaderTest.php `

```
PHPUnit 4.6.6 by Sebastian Bergmann and contributors.

Configuration read from /home/possum/work/composer/phpunit.xml.dist

E.......

Time: 67 ms, Memory: 5.50Mb

There was 1 error:

1) Composer\Test\Autoload\ClassLoaderTest::testLoadClassDotPhp
include(/home/possum/work/composer/tests/Composer/Test/Autoload/Fixtures/DirDotPhp/psr4/Dir.php): failed to open stream: No such file or directory

/home/possum/work/composer/tests/Composer/Test/Autoload/ClassLoaderTest.php:19
phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:152
phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:104

FAILURES!
Tests: 8, Assertions: 7, Errors: 1.
```

```
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans
```

Any ideas?

**Comment by stof** [comment]
have you installed PHPUnit from composer ? If yes, have you used an uptodate composer for that ?

When PHPUnit is installed from Composer, it will load the ClassLoader from its setup and so the unit tests of the ClassLoader class will use this class rather the class available in the current codebase (as the class is already defined). If your PHPUnit setup was done with composer before the bugfix was merged in Composer, you are testing that the non-fixed ClassLoader fails the regression test

**Comment by Seldaek** [comment]
Yup most likely you have a global phpunit for which you just need to re-dump the autoloader using `composer global dump-autoloader` or similar.

**Comment by SpacePossum** [comment]
Thanks @stof and @Seldaek. I did a `composer update-self` and a re-install on the project. This test now runs fine :)  :+1:
