### ISSUE TITLE
Composer install fails on last line

### ISSUE THREAD

**Issue by ckosloff** [composer/composer#4002]
I am following instructions here to install composer globally:
https://www.drupal.org/node/1791676
I get error when I get to the last line:
source ~/.bash_profile
No such file or directory.
I tried installing in a VM running latest Debian stable (now v. 8, jessie).
I also tried in my local server running on the Debian testing branch, not much difference between them and got same error.

**Comment by Seldaek** [comment]
Soo.. first of all this is a mistake in the drupal instructions, and has nothing to do with composer.

But then .bash_profile missing is not entirely failing composer, composer still should work globally, it just won't include that global composer binaries in the PATH, which I don't think their installer would do anyway as the `export PATH=...` line doesn't really store it anywhere as soon as you logout the path entry would be gone. I'd suggest pinging the drupal folks about this.

**Comment by ckosloff** [comment]
Jordi,

Thank you very much for answer.
I have already opened an issue with drupal.org here:
https://www.drupal.org/node/2483461
That is the page for the composer module, not exactly the one for the 
instructions.
I would have to edit that one but need some help.
I have composer.phar already moved to|/usr/local/bin/composer.
How should I proceed from there?
Best regards,

Carlos Kosloff
|

**Comment by Seldaek** [comment]
Well to get drush to work you need the global composer home dir's bin-dir to be in the PATH environment varialbe, that directory can be obtained using: `composer global config --absolute bin-dir`. Adding that dir to the PATH though is a very much platform dependent thing, .bash_profile will work on linux/OSX for people using bash, it might work for windows users using cygwin/msys, but not anyone else. Basically it requires that people have a clue what env vars are and how to change them on their machine, which isn't always the case.

**Comment by ckosloff** [comment]
Please I need more clarifications I am using Debian, latest stable (very 
recent) or testing are pretty much the same.
I have never had to need to set env vars in my machine so don't know how 
to change them
Running |composer global config --absolute bin-dir| as root throws error:
[RuntimeException]
   File "composer.json" cannot be found in the current directory
There is no .bash_profile in my home directory.
Please explain how I should proceed.
Thank you.

**Comment by ckosloff** [comment]
I created an empty .bash_profile in my home dir.
Then followed instructions in the drupal page and it installed, no errors.
so I installed drush with command:
composer global require drush/drush:dev-master
then
composer global update
no errors so far, but...
command drush throws error
bash: drush: command not found
Please help.

**Comment by ckosloff** [comment]
Sorry, me again.
Composer definitely works as user.
|composer global config --absolute bin-dir|
yields
Changed current directory to /home/ckosloff/.composer
However there is no such directory in my home and my .bash_profile is empty.
So, please what is syntax to get drush working, since composer could not 
download it from git (not installed yet) but did download from project.
Thank you.

**Comment by ckosloff** [comment]
SOLVED!!  .bash_profile is not for Linux, .bashrc is, it is in the 
drush.org instructions.
