### ISSUE TITLE
Composer requests SSH key file password multiple times for private repos

### ISSUE THREAD

**Issue by eComEvo** [composer/composer#4004]
For each private repo referenced in the composer.json file, Composer will ask for the SSH key password 2-3 times, even if password is correct, before proceeding with an update.

Composer version: 1.0-dev (4d8b37190836a22028c4e4d2c0538f1ed98ee7df)

Screenshot of the issue:
http://prntscr.com/71zw8g

**Comment by frederikbosch** [comment]
@eComEvo What OS are you on? Are you aware of [this bug in Ubuntu 13.10](https://bugs.launchpad.net/ubuntu/+source/libpam-ssh/+bug/1247169)? Just maybe it solves your problem.

**Comment by eComEvo** [comment]
@frederikbosch I'm on Ubuntu 14.04.

**Comment by frederikbosch** [comment]
@eComEvo Could you try to include the passpharse in the repository options [as suggested by the first reply of this thread](http://php.net/manual/en/wrappers.ssh2.php)? So like this.

```json
{
    "repositories": [
        {
            "type": "composer",
            "url": "ssh2.sftp://example.org",
            "options": {
                "ssh2": {
                    "username": "composer",
                    "password": "passphrase of key file",
                    "pubkey_file": "/home/composer/.ssh/id_rsa.pub",
                    "privkey_file": "/home/composer/.ssh/id_rsa"
                }
            }
        }
    ]
}
```

Of course this would not be a working solution, because you do not want to commit your keyfile passphrase. However, if it works, we can create a prompt in composer and insert it manually into the stream context options. If the suggestion does not work, then I guess the amount of work to get this done will be much greater, because composer has to setup a ssh2 context using the ssh2 library.

**Comment by slbmeh** [comment]
composer doesn't cache credentials for ssh keys. It should ask twice iirc, I can't remember the details of why and when. this is what ssh-agent is for, holding your decrypted key for a defined amount of time. Otherwise it will ask each time it needs the key.

**Comment by eComEvo** [comment]
@slbmeh I used ssh-agent to add my key and now it asks for the key password twice instead of three times.

**Comment by frederikbosch** [comment]
@eComEvo Did you also try my suggestion?

**Comment by eComEvo** [comment]
@frederikbosch Just tried it and it now asks for the password three times again. Strange.

**Comment by frederikbosch** [comment]
@eComEvo Never mind, the comments on php.net are not the best resource in my experience. Maybe you could find out which commands cause the prompts.

You could clone composer, run ```composer install``` inside the cloned folder (composer installs itself) and run ```/path/to/cloned/composer/bin/composer install```` in your code folder. Beforehand, you should at some debugging to [GitDownload.php](https://github.com/composer/composer/blob/master/src/Composer/Downloader/GitDownloader), [GitUtil](https://github.com/composer/composer/blob/master/src/Composer/Util/Git.php) or other file executing git commands. This might be helpful in getting to the root of the problem.

**Comment by eComEvo** [comment]
So, figured out a way around this. As it turns out, I did not in fact have ssh-agent running and configured on Vagrant where I was running the project (I had it enabled on the host system, which was an oversight).

After enabling that, I followed these instructions and all is well:
https://confluence.atlassian.com/display/BITBUCKET/Set+up+SSH+for+Git
