### ISSUE TITLE
Composer update says local files have changed. It lies.

### ISSUE THREAD

**Issue by rquadling** [composer/composer#4007]
Hi.

I've got a repo on BitBucket that my colleagues and I use. I have an entry for a vendor/bin file.

On Windows, I'm getting the 2 versions of this file (app and app.bat sort of thing). All is good and is as expected.

On my colleagues Ubuntu Mate setup, he has just 1 symlinked file. This looks to be correct from what I've read.

When I make changes to the repo on my machine and push to bitbucket and then get him to run ```composer update``` to get those changes, he is told that there are changes to a local file. I tell him to discard the changes and the update continues successfully.

But the thing is, there are no changes. I think he said that the file is the symlinked one. I'm waiting on getting a screen copy of the issue.

Regards,

Richard Quadling.

**Comment by stof** [comment]
The change may be a chmod change. Make sure that any file listed in the ``bin`` section of your package is executable (Windows does not care about these permissions, but Unixy systems do)

**Comment by rquadling** [comment]
How do I make that happen from windows? Real windows. Not Cygwin?

**Comment by stof** [comment]
@rquadling when running the gitbash installer, it asks you whether you want it in the path or no: 
![git bash installer](https://camo.githubusercontent.com/97c2f013eeff10a89a225b23d7b18cf4f88d6b96/687474703a2f2f692e696d6775722e636f6d2f554f6b7833356a2e706e67)

**Comment by rquadling** [comment]
Ah. I use Sourcetree and it installs a unix shell.

So, on Windows, git really is run under emulation/unix shell. Ha! Didn't even think of that! Thank you. Will test it out.

**Comment by rquadling** [comment]
The current state shows ...

```
RichardQ@DIGIDEV /c/wamp/www/TidyPMP (hotfix/TidyPMPExecutable)
$ cd bin

RichardQ@DIGIDEV /c/wamp/www/TidyPMP/bin (hotfix/TidyPMPExecutable)
$ ls -al
total 3
drwxr-xr-x    3 RichardQ Administ        0 Apr 29 17:51 .
drwxr-xr-x    1 RichardQ Administ     4096 Apr 30 11:19 ..
-rwxr-xr-x    1 RichardQ Administ      743 Apr 29 17:51 tidypmp
```

I've not actually changed anything for this. Just ran the terminal from Sourcetree and listed the files.

So, from what I'm seeing the file IS executable.

When my colleague is able to run the bin file quite happily once he says discard to the alleged changes.

Could it be an owner/group issue? If so, what owner/group should it be?

**Comment by rquadling** [comment]
He does have to run ```sudo composer update```. I wonder if he should be rooted? This is an area I don't really know much about.

**Comment by Seldaek** [comment]
To make sure the file is executable from windows you can do `git update-index --chmod=+x path/to/file` and then a git commit should seal it.

**Comment by rquadling** [comment]
That certainly made a difference from my end. I can see the commit with the action. Testing against colleagues setup.

**Comment by rquadling** [comment]
Hmm. Upon ```composer update```, he gets ...

```
glenn@glenn-desktop:~/development/dev4/digitickets (develop) ^$ sudo composer update
[sudo] password for glenn: 
Loading composer repositories with package information
Updating dependencies (including require-dev) 
- Updating digitickets/tidypmp dev-master (2381deb => 586a123)
The package has modified files:
M bin/tidypmp
Discard changes [y,n,v,s,?]? 
```

We discard changes and the update happens.

Looking at the files now present, they all look OK.

```
glenn@glenn-desktop:~/development/dev4/digitickets (develop *) ^$ ls -la vendor/bin/
total 8
drwxr-xrwx 2 root root 4096 May 6 15:01 .
drwxrwxrwx 20 glenn glenn 4096 May 6 15:01 ..
lrwxrwxrwx 1 root root 28 May 6 09:40 phinx -> ../robmorgan/phinx/bin/phinx
lrwxrwxrwx 1 root root 39 Feb 25 10:22 phpunit -> ../phpunit/phpunit/composer/bin/phpunit
lrwxrwxrwx 1 root root 34 May 6 15:01 tidypmp -> ../digitickets/tidypmp/bin/tidypmp

glenn@glenn-desktop:~/development/dev4/digitickets (develop *) ^$ ls -la vendor/digitickets/tidypmp/bin/
total 12
drwxr-xr-x 2 root root 4096 May 6 15:01 .
drwxr-xr-x 5 root root 4096 May 6 09:40 ..
-rwxr-xr-x 1 root root 743 May 6 15:01 tidypmp
```

```composer status``` says there are no local changes.

Added a simple whitespace change to a non related file in the repo and asked him to pull that and added verbosity.

And all good.

No question about differences.

Thank you!!!
