### ISSUE TITLE
php composer.phar install --no-dev fails.

### ISSUE THREAD

**Issue by mojostelar** [composer/composer#4008]
Whenever I try to run this command I get this error message. 
[RuntimeException]
  Failed to clone git://git.kolab.org/git/pear/Net_LDAP3, git was not found,
  check that it is installed and in your PATH env.
  sh: 1: git: not found

and idd Net_LDAP3 vanished, so could you guys give me the command that works ?
ty !

**Comment by stof** [comment]
Well, given that git is not installed on your system (or at least not available in the PATH), there won't be any working command. You need to fix your Git setup
