### ISSUE TITLE
Allow autoloading of files with configurable extension.

### ISSUE THREAD

**Issue by phpwutz** [composer/composer#4013]
## Gist
Using composer to psr-4 autoload classes with a file ending other than '.php' does not work, unless 'composer dump-autoload -o' is used.
We should add support to search for custom file extensions.

## Reasoning

When using the psr4 autoloading and generating the optimized autoloader ( composer dump-autoload -o ) it is already possible to have php files with a file extension other than .php autoloaded by composer.

In the ClassLoader.php, i see that files are searched with this call:
```php
$file = $this->findFileWithExtension($class, '.php');
```
Also, Hack files are explicitly supported with
```php
// Search for Hack files if we are running on HHVM
if ($file === null && defined('HHVM_VERSION')) {
    $file = $this->findFileWithExtension($class, '.hh');
}
```
When consulting the specification of psr4( http://www.php-fig.org/psr/psr-4/ ), i could not find an explicit requirement for class files having the file extension '.php'.

I therefore suggest to add a configuration parameter to the autoload section of composer.json:
```json
{
  "autoload": {
    "additionalFileExtensions": [".inc", ".whateveryouneed"],
    "psr-4": {
      "PackageName\\": "packageFolder/"
    }
  }
}
```

The parameter "additionalFileExtentions" would then be considered by the "findFile" method and also find files with the specified extensions.

If there is a chance this will be added to the composer core, I am willing to provide a patch for this functionality.

**Comment by stof** [comment]
Taken from the PSR-4 spec:

> - A contiguous series of one or more leading namespace and sub-namespace names, not including the leading namespace separator, in the fully qualified class name (a "namespace prefix") corresponds to at least one "base directory".
> - The contiguous sub-namespace names after the "namespace prefix" correspond to a subdirectory within a "base directory", in which the namespace separators represent directory separators. The subdirectory name MUST match the case of the sub-namespace names.
> - The terminating class name corresponds to a file name ending in ``.php``. The file name MUST match the case of the terminating class name.

It explicitly says that the file extension should be ``.php``

**Comment by stof** [comment]
and btw, the fact that such file is parsed when dumping the optimized autoloader is a bug IMO

**Comment by phpwutz** [comment]
Hi, thanks for answering. Apparently I overlooked the requirement for files to have the `.php` ending.
Is there any chance, as `.hh` is already supported as extension, to accept also other file extensions depending on configuration?

**Comment by stof** [comment]
Well, ``.hh`` is here so that Hack users can continue to use Composer for their autoloading.

However, adding other extensions for the PSR-4 resolution would get a -1 vote from me:

- it would degrade performance in case prefixes are not enough to find the right folder directly because it would require checking multiple places in the first folder before giving up (one per extension)
- if you use a different extension, you don't comply with PSR-4 anyway, so trying to use the PSR-4 autoloading config to load your classes is a wrong config anyway.

Note that the classmap generator will also look for classes in ``.inc`` files for compatibility with legacy libraries.

**Comment by nelson6e65** [comment]
I have the same issue with `*.inc`. But, thank you for you explanation, @stof. I understand that I'm violating PSR4 using another extension than `php`. :pensive: I'll change to solve this. :smile:

**Comment by Seldaek** [comment]
Closing as I don't think it's going to happen. Using .php is the standard and has been for ages. Anything else is historical remnants and fixing this isn't extremely difficult.
