### ISSUE TITLE
Faster create-project by allowing use of pre generated archives

### ISSUE THREAD

**Issue by andrerom** [composer/composer#4023]
General idea would be to replicate the speed improvements [symfony installer](https://github.com/symfony/symfony-installer) did for installation of symfony but in a standardized way, the other features of the installer can be covered by composer.json events.

Would there be an idea to create a command or flag *(ala --prefer-dist-with-vendors)* to create-project to pick tags *(by some convention)* that already contains vendors for faster install? I'm not 100% sure on how the convention would be to avoid the normal calls from picking these packages, so might be better ways.

**Comment by Seldaek** [comment]
It's not really a use case I feel we should support, it's gonna be a lot of code for an edge-casey use-case and tbh not so huge benefit.
