### ISSUE TITLE
composer can't be used by Dockerfile

### ISSUE THREAD

**Issue by billycyzhang** [composer/composer#4024]
INFO[0001] The command [/bin/sh -c /usr/local/bin/composer -n create-project laravel/laravel sourcecode 4.2.* --prefer-dist] returned a non-zero code: 255

**Comment by indeyets** [comment]
I definitely use composer with docker, by inheriting from https://registry.hub.docker.com/u/composer/composer/ so it can be done.

**Comment by alcohol** [comment]
255 indicates an error. But you have not shown us any errors. With this limited amount of information we cannot help you. Saying "it doesn't work" is not very helpful. Please contribute more information regarding your problem. Run composer in very verbose mode for example (by using the `-vvv` flag).

**Comment by reesew** [comment]
I'm not seeing the error either, only that there is an error
```
Step 7 : RUN cd /var/www/html/ &&     php composer.phar -vvv install
 ---> Running in 3cfd8ceb478f
The command '/bin/sh -c cd /var/www/html/ &&     php composer.phar -vvv install' returned a non-zero code: 255
```

**Comment by alcohol** [comment]
We can't help you without more information.
