### ISSUE TITLE
SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify

### ISSUE THREAD

**Issue by HamidDarash** [composer/composer#4025]

**Comment by HamidDarash** [comment]
C:\xampp\htdocs>composer selfupdate



  [Composer\Downloader\TransportException]
  The "https://getcomposer.org/version" file could not be downloaded: SSL ope
  ration failed with code 1. OpenSSL Error messages:
  error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify
  failed
  Failed to enable crypto
  failed to open stream: operation failed



self-update [-r|--rollback] [--clean-backups] [--no-progress] [version]

hi, i'm is Novice in laraval. my problem is by create-project at composer.please help

**Comment by stof** [comment]
Looks like you have an outdated version of openssl in your system, or a misconfigured CA file for your openssl setup.

**Comment by HamidDarash** [comment]
thanks

**Comment by Neve12ende12** [comment]
I am getting the same error.  I have no idea how to go about updating openssl on windows 8

**Comment by padraic** [comment]
@Neve12ende12 https://github.com/padraic/humbug#self-update-request-debugging

There shouldn't be errors if both of these settings are in place, unless openssl itself is buggy. You should mention your PHP + openssl version if there are still issues.

**Comment by Neve12ende12** [comment]
So I am using PHP 5.6.3 (xampp).  I have no idea how to check the openssl

**Comment by padraic** [comment]
@Neve12ende12 And you have the certificate path set per the link, and verified there's a file at the path given?

**Comment by Neve12ende12** [comment]
Yes, I specified the certificate path in my php.ini file and ensured that the file exists in the location specified (C:\portables\xampp\php\ext\cacert.pem).

**Comment by stof** [comment]
@Neve12ende12 your phpinfo should display the OpenSSL version

**Comment by Neve12ende12** [comment]
@stof 

openssl

OpenSSL support  enabled  
OpenSSL Library Version  OpenSSL 1.0.1l 15 Jan 2015  
OpenSSL Header Version  OpenSSL 1.0.1m 19 Mar 2015

**Comment by markushausammann** [comment]
I even get this for fresh puPHPet vagrant boxes with PHP 5.6. It seems non-trivial. I agree with @padraic that it shouldn't happen but it does, even if the conditions he states are fulfilled.

**Comment by AMOSoft** [comment]
We have the same issue with SSL. Composer can't retrieve the dists from our Satis server.
It's not a recent deployment, everything worked fine until now.
