### ISSUE TITLE
What can I do to NOT install dev packages on production environment.

### ISSUE THREAD

**Issue by rquadling** [composer/composer#4026]
Hi.

Is there a way to have composer "know" that some environment/machines are development (and therefore, ```composer update``` or ```composer install``` for a new developer) and production (and therefore ```composer install --no-dev``` only).

Absolutely no idea if this is the right way to go, but basically, our dev tools are locked to our lan on our private repo hub. Our production servers have no need of these tools and fails to install them due to no ssh keys for the repo being present on the production servers.

Regards,

Richard.

**Comment by stof** [comment]
Well, the common approach is to use ``--no-dev`` in your deployment script used by the prod environment.
The only way to configure this in Composer is through the ``--no-dev`` flag. there is nothing based on environment variables or global config.

**Comment by rquadling** [comment]
Aha. That's where we're going wrong. Too much manual stuff! Thanks.
