### ISSUE TITLE
Unable to find class unless I run dump-autoload --optimize

### ISSUE THREAD

**Issue by ptheofan** [composer/composer#4027]
Library real-path (under vendor)
vendor/angry-panda-soft/saas-clients

Class real-path under vendor
vendor/angry-panda-soft/saas-clients/auth

Class namespace
angrypandasoft\saasclients\auth\AccessEntity

Composer autoloader is not able to load the class when 
new angrypandasoft\saasclients\auth\AccessEntity\AccessEntity();

however if I run
composer dump-autoload --optimize

everything works fine.

My composer version is bc45d9185513575434021527d7756420e9f4b2cf

In my composer.json file I have no autoloading section (just contains basic author info etc.)

**Comment by nkconnor** [comment]
I have the same issue

`Composer version 1.0-dev (9fb2d4f2d642a0749decb41bc2fe4be2bf8bef7a) 2015-06-05 13:07:39`

```
{
    "autoload": {
        "psr-4": {
          "Refactor\\": "refactor/"
        },
        "files": [
          "includes/utils.php",
          "includes/redirect.php"
        ]
    },
 ...
```

**Comment by stof** [comment]
Can you show the composer.json of your ``angry-panda-soft/saas-clients`` package ? It may be an autoloader config issue in this package
