### ISSUE TITLE
Cannot read the PHP version

### ISSUE THREAD

**Issue by rougin** [composer/composer#4029]
Hello! I try to install a package of my own but I got this message instead:

```bash
This package requires php 5.2.4 but your PHP version (5.5.9-1ubuntu4.9) does not satisfy that requirement.
```

I am confused because my current PHP version is 5.5.9 yet it *does not satisfy that requirement*. Here is my ```composer.json```:

```json
{
    "require": {
        "php": "5.2.4",
        "rougin/combustor": "dev-master"
    }
}
```

Did I make a mistake in here?

**Comment by padraic** [comment]
You have it tied to just one version `5.2.4` instead of a range like `>=5.2.4` which also accepts higher versions (incl. PHP 7 in this case).

**Comment by rougin** [comment]
Oh right. I Forgot to add a range about it. This is embarrassing. Thanks! :smile:
