### ISSUE TITLE
Composer classpreloader/classpreloader URL incorrect

### ISSUE THREAD

**Issue by hallshouse** [composer/composer#4030]
Hi:
When installing Composer I get the following error:
  - Installing classpreloader/classpreloader (1.0.2)
    Downloading: Connecting...    Failed to download classpreloader/classpreloader from dist: The "https://api.github.com/repos/mtdowling/ClassPreloader/zipball/2c9f3bcbab329570c57339895bd11b5dd3b00877" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
This makes any apps I run fail.
In Ubuntu 14.04, I ran sudo composer install and consistently get this error.
Is there an alternative installation process I can use?
Best Regards,

**Comment by slbmeh** [comment]
You can use `--prefer-source`... the github zipballs only have a duration up to some time period unknown to me.  If you use prefer source it will download it with git and circumvent the need to grab the zipball from the github api.

**Comment by nevvermind** [comment]
> the github zipballs only have a duration up to some time period
@slbmeh - What do you mean exactly?

**Comment by slbmeh** [comment]
@nevvermind Actually, I was incorrect in that remark.  I was thinking about an error I've had before that is unrelated.

Installing with `--prefer-source` will not download the dist.  But it appears the issue with the dist is that it isn't on the api url anymore.  `https://github.com/mtdowling/ClassPreloader/archive/2c9f3bcbab329570c57339895bd11b5dd3b00877.zip` is what the github driver should be returning perhaps?

**Comment by stof** [comment]
the issue is that the repo was renamed from ``mtdowling/ClassPreloader`` to ``ClassPreloader/ClassPreloader``, and Github does not redirect API URLs yet (they have this redirection in a preview version of their API).

**Comment by cwarwicker** [comment]
Having the same issue trying to use Composer to install LearningLocker.

Is this something I can change on my end to point to the correct repo, or does it need a fix on Composer's end?

**Comment by ryansmith94** [comment]
Thanks @stof.

**Comment by Seldaek** [comment]
In general to fix these errors caused by redirects the best is to run a composer update and not install as that should update the URL to the latest known one (if they cared to update the URL on packagist..)

**Comment by shrestha2015** [comment]
But now it is saying
