### ISSUE TITLE
get the tree of dependencies with composer

### ISSUE THREAD

**Issue by voxsim** [composer/composer#4031]
This is not a real issue, it's more like a nice to have: is it possible to have the tree of dependencies like https://docs.npmjs.com/api/ls ?

Thanks,
voxsim

**Comment by gabrieletondi** [comment]
we are working on it with voxsim: https://github.com/voxsim/composer/commits/ls_command

Pull request soon :-)

**Comment by Seldaek** [comment]
This is probably solved by #2600 once merged

**Comment by jeremyFreeAgent** [comment]
@Seldaek true. By the way nice hat ^^

**Comment by jeremyFreeAgent** [comment]
I think we can close this one!

**Comment by Seldaek** [comment]
Yup, `composer show --tree / -t package/name` or `composer show -ti` for all installed tree.
