### ISSUE TITLE
Parameter for custom composer.json

### ISSUE THREAD

**Issue by PhillippOhlandt** [composer/composer#4033]
Hey,

it would be cool if there were a parameter to specify the composer.json file which composer will use. E.g. composer.dev.json (that file don't require my own packages because they are already under development in the vendor folder)

**Comment by nevvermind** [comment]
https://getcomposer.org/doc/03-cli.md#composer

**Comment by PhillippOhlandt** [comment]
Oh didn't seen that. That solves my problem! Thanks!
