### ISSUE TITLE
Composer writes debug data into stderr instead of stdout

### ISSUE THREAD

**Issue by FractalizeR** [composer/composer#4034]
We were performing a deploy using SaltStack to one of our servers and noted, that composer writes insignificant data into stderr (and some more from the same command to stdout). Composer version is `Composer version 1.0-dev (bc45d9185513575434021527d7756420e9f4b2cf) 2015-05-11 14:49:39`

I think this should not be an intended behaviour.

```
----------
          ID: run_composer_install
    Function: cmd.run
        Name: composer install --prefer-dist --no-dev --no-interaction
      Result: True
     Comment: Command "composer install --prefer-dist --no-dev --no-interaction" run
     Started: 16:20:12.554394
    Duration: 3143.24 ms
     Changes:
              ----------
              pid:
                  19162
              retcode:
                  0
              stderr:
                  Loading composer repositories with package information
                  Installing dependencies from lock file
                  Nothing to install or update
                  Generating autoload files
              stdout:
                  Generating optimized class loader
                  Compiling common classes
```

**Comment by slbmeh** [comment]
This is the intended behavior. Relatively standard for unix commands to have only their standard output in stdout and ancillary messages depending on verbosity to stderr. Check the exit code if you want to know if it failed.

https://github.com/composer/composer/issues/3787#issuecomment-76167739 has more details as to why it has changed.

**Comment by FractalizeR** [comment]
I see. Thanks.

Refs for further readers: #1905, #3715
