### ISSUE TITLE
PDF Book link is broken

### ISSUE THREAD

**Issue by edomato** [composer/composer#4037]
I tried to download the PDF version of the book but the resulting page gives the error:

Sorry, the page you are looking for could not be found.

**Comment by TomasVotruba** [comment]
Where?

**Comment by edomato** [comment]
Sorry, I miss to put that information :-)

The link appears in: https://getcomposer.org/doc/ in the section "PDF Docs"
and points to https://getcomposer.org/book.pdf

Thanks.

**Comment by xabbuh** [comment]
@edomato see composer/getcomposer.org#81

**Comment by edomato** [comment]
Ohhh... didn't know that the website has own issues part :-)
