### ISSUE TITLE
Allow to define default packages for virtual ones

### ISSUE THREAD

**Issue by sagikazarmark** [composer/composer#4039]
The virtual package feature is pretty useful. However in some cases it would be nice to define defaults if no package providing that virtual package is marked for installation. In some cases when you don't care what is going to be installed just want it working.

Here is an example syntax:
``` json
{
    "defaults": {
        "virtual/package1": "package/implementation1",
        "virtual/package2": [
            "package/implementation2.1",
            "package/implementation2.2"
        ]
    }
}
```

This allows to define concrete implementations for virtual packages. Version constraint is not needed, it should be calculated from the required virtual package version.

However I don't think they should be installed by default if requirements don't meet. I would add a `--defaults` option to install such packages:

`$ composer install --defaults`

WDYT?

**Comment by stof** [comment]
@sagikazarmark where would this list of default implementations be stored ?

**Comment by sagikazarmark** [comment]
Either in the root or the extta

**Comment by stof** [comment]
If the user has to specify the default in the project, what is the benefit over choosing an implementation directly ?

**Comment by sagikazarmark** [comment]
It's not a requirement, only a possible feature. The point is that you can
choose an implementation or stick to a default on if you wish.
2015. jún. 7. 13:04 ezt írta ("Christophe Coevoet" <notifications@github.com

**Comment by ct-jensschulze** [comment]
For this, you would have to define for a virtual package the interfaces somewhere or else you could not rely on the implementation to work properly (possible different namespaces, classes etc.) . And then you could also define one interface repository and all implementations require the interface repository just like the PSR repositories. (e.g. https://packagist.org/packages/psr/http-message and https://packagist.org/packages/guzzlehttp/psr7).

**Comment by Seldaek** [comment]
IMO defaults for the root should just be in require-dev, as that's the main use case for libraries that require virtual packages. Not sure I see how this would work generally for the other use cases as two things might have conflicting defaults and so on. Sounds more complex than it's worth.

**Comment by joelwurtz** [comment]
Wanted to do something similar, is this a fixed choice ? or can i propose a more complete solution with (hopefully) all use case for each possibility ?

**Comment by Seldaek** [comment]
@joelwurtz you can always try but I am pretty set on avoiding unneeded (read edge-case only) complexity.
