### ISSUE TITLE
Composer archive

### ISSUE THREAD

**Issue by voxsim** [composer/composer#4040]
I want to create an archive to deploy my application to my hosting infrastructure, but I have some issues:

1) I can't have the vendor directory in my archive because I have this directory in my .gitignore.
RIght now, for what I understand, the ArchiveComand doesn't include the files filtered by .gitignore (https://github.com/composer/composer/blob/1d8f05f1dd0e390f253f79ea86cd505178360019/src/Composer/Package/Archiver/ArchivableFilesFinder.php#L48).
I think this is a wrong behaviour because I followed the composer's documentation: https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md

2) When I create my archive it will be very useful to export only the used files instead of packages'  documentation, tests or other waste for production deployed code.
Right now I export the used files from the vendor directory with this script:
```
$loader = require $basePath . '/vendor/autoload.php';
$includeFiles = require $basePath . '/vendor/composer/autoload_files.php';

$files = array_merge(array_values($loader->getClassMap()), $includeFiles);
foreach($files as $file) {
  $pos = strpos($file, 'vendor/');
  if($pos !== false) {
    // Copy my file in the right place
  }
}
```

I opened this issue to understand your point of view. I did some modifications to composer, maybe I can open some pull requests if you are interested.

References to other issues: https://github.com/composer/composer/issues/3733

cheers,
voxsim

**Comment by alcohol** [comment]
Try looking at `git archive` instead of `composer archive`.

Composer archiving is for libraries, not projects. It creates an archive which can be used to install your lib in another application.

**Comment by Seldaek** [comment]
What you describe sounds more like packaging/deployment stuff than what composer is really made for. There are other tools more suited to the creation of archives.
