### ISSUE TITLE
What is the best approach to use composer for system wide installations? 

### ISSUE THREAD

**Issue by ronlinet** [composer/composer#4041]
I have executed 
```
composer global update
```

With bellow list of php packages in my /root/.composer/composer.json : 

```
{
    "require": {
        "squizlabs/php_codesniffer": "*",
        "phploc/phploc": "*",
        "pdepend/pdepend" : "*",
        "phpmd/phpmd" : "*",  
        "nikic/php-parser" : "*", 
        "theseer/phpdox": "*", 
        "sebastian/phpcpd": "^2.0"
    }    
}       

```

I can see the php packages all installed in 
```
/root/.composer/vendor 
```
directory with symbolic links pointing ton 
```
/root/.composer/vendor
```

However the commands are system wide accessible only to root user and I can't access any of the executable as soon as I log as a user with no root privileges. 

I have tried to create symbolic links from /usr/bin or /usr/local/bin and I have even tried to change the user permissions of the executable files in 
```
/root/.composer/vendor/bin
```
to 777 . 
None of the hack works and I am getting “command not found” for symlinks and “Permission denied” if I try to execute the programs directly. 

OS: Ubuntu 12.04 LTS

**Comment by nevvermind** [comment]
By "system wide" do you mean "for every user" (bad idea, btw) or a global `composer` command (explained [here](https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx), in the "Globally" section).

It seems you installed/chmod'd to `root`. Don't. You should use your deployment user, or a user from a "web" group instead (like the `www-data` group).

Install composer again using a non-root user.

**Comment by ronlinet** [comment]
I understood the global composer installing. 
The point is how to install a cross system packages through the composer. 
A standard linux web server settings is set of different users with specific access to different virtual hosts. All of these users belongs to one common group “www-data” and I want each of theses users be able to use the packages installed by composer. 
This is supposed to be  the same as when you install php packages via the “apt-get install” command ( php5-xsl, php5-cli .. ), such packages are installed once and may be reused across the system.
Do you really mean that we are supposed to redundantly installing composer packages for each specific user?

**Comment by laszlof** [comment]
composer is typically setup on a per-project basis. So yes, you would want to have a separate composer setup for each site.

**Comment by alcohol** [comment]
I usually also install tools such as phpmd, phpcs and phpunit globally on my machines.

```
$ cat /opt/composer/composer.json
{
    "require": {
        "phpunit/phpunit": "@stable",
        "squizlabs/php_codesniffer": "~2.0@dev",
        "kherge/box": "@stable"
    },
    "config": {
        "bin-dir": "/usr/local/bin"
    }
}
```

```
$ sudo composer install
...stuff...
```

Done.

Now every user can run phpunit etc.

**Comment by ronlinet** [comment]
Thank you for your advice alcohol. I have used your layout for my composer:

```bash
{
    "require": {
	  "phpunit/phpunit-selenium": ">=1.2",
	  "phpunit/dbunit": ">=1.2"
        "squizlabs/php_codesniffer": "~2.0@dev",
        "kherge/box": "@stable"        
	  "squizlabs/php_codesniffer": "*",
        "phploc/phploc": "*",
        "pdepend/pdepend" : "*", 
        "phpmd/phpmd" : "*", 
        "nikic/php-parser" : "*", 
        "theseer/phpdox": "*", 
        "sebastian/phpcpd": "*
    },
    "config": {
        "bin-dir": "/usr/local/bin"
    }
}
```

And I have installed all packages : 
```bash
composer install
```
I can see that system creates links in /usr/local/bin but again the packages are still accessible only for root superuser. I can't access or even list them as soon as a switch to any other user. Can you please explain why it works in your case and not in mine?
```bash 
ls -l /usr/local/bin/
total 4164
-rwxr-xr-x 1 root root 1104838 May 31 20:00 composer
lrwxrwxrwx 1 root root      20 May 31 19:09 eclipse -> /opt/eclipse/eclipse
lrwxrwxrwx 1 root root      54 May 31 20:07 pdepend -> /root/.composer/vendor/pdepend/pdepend/src/bin/pdepend
lrwxrwxrwx 1 root root      63 May 31 20:07 phpcbf -> /root/.composer/vendor/squizlabs/php_codesniffer/scripts/phpcbf
lrwxrwxrwx 1 root root      46 May 31 20:08 phpcpd -> /root/.composer/vendor/sebastian/phpcpd/phpcpd
lrwxrwxrwx 1 root root      62 May 31 20:07 phpcs -> /root/.composer/vendor/squizlabs/php_codesniffer/scripts/phpcs
lrwxrwxrwx 1 root root      57 May 31 20:07 phpdox -> /root/.composer/vendor/theseer/phpdox/composer/bin/phpdox
lrwxrwxrwx 1 root root      43 May 31 20:07 phploc -> /root/.composer/vendor/phploc/phploc/phploc
lrwxrwxrwx 1 root root      48 May 31 20:07 phpmd -> /root/.composer/vendor/phpmd/phpmd/src/bin/phpmd
-rwxr-xr-x 1 root root 3146137 May 29 07:01 phpunit```
```
Thanks.

**Comment by alcohol** [comment]
That's weird, usually /usr/local/bin is also accessible by normal users. Are you sure your normal users have a default `PATH`? Usually something like `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`. You can check by typing `echo $PATH` as a normal user.

**Comment by ronlinet** [comment]
Hi Alcohol, 
My path variable was correct:
```bash
echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

I have corrected the phpunit typo in the above comment and I confirm that phpunit works as required:
```bash 
phpunit --version
PHPUnit 4.6.9 by Sebastian Bergmann and contributors. 
```

The real issue was in composer.json location. In my case was the file sitting in /root/.composer/ directory. Moving the composer.json to /opt/composer/ directory and reinstalling the packages fix the problem,. 

I would like to also underline that your initial answer for this issue is the right system wide installations approach.  

So the solution is : 
```bash
$ cat /opt/composer/composer.json
{
    "require": {
        "phpunit/phpunit": "@stable",
        "squizlabs/php_codesniffer": "~2.0@dev",
        "kherge/box": "@stable"
    },
    "config": {
        "bin-dir": "/usr/local/bin"
    }
}

$ sudo composer install
```

**Comment by alcohol** [comment]
Oh yes. If it installed inside `/root/.composer/` then all the files it symlinked to were owned by and located inside the root user home directory. That's not a very suitable location.

I guess that is probably because you still used the `global` keyword when doing an install? You don't need that for this approach :-).

**Comment by alcohol** [comment]
Anyway, if this resolves the issue for you, please close it.

**Comment by kenorb** [comment]
I'm using the following configuration by specifying global vendor and bin dirs:

	{
	    "config": {
	        "vendor-dir": "/var/lib/vendor",
	        "bin-dir": "/usr/local/bin"
	    },
	}

Hope that helps.
