### ISSUE TITLE
curl: (56) SSLRead() return error -9806

### ISSUE THREAD

**Issue by markknochen1** [composer/composer#4042]
Hi,
i can't download composer, i always get the error:
curl: (56) SSLRead() return error -9806
php on macOS has SSL Version => OpenSSL/1.0.1e

what's wrong?

Mark

**Comment by padraic** [comment]
It's a curl error, so I assume this was curl from the command line, to download the installer? Sounds like a DNS timeout. Can you ensure you have no downloads running, and perhaps try to increase the timeout on that command?

I don't use Mac, but Windows can throw around DNS errors all the time if you have something another download in the background. I've heard Macs can sometimes have similar issues (or worse). Linux tends to be much more reliable.

**Comment by markknochen1** [comment]
Mh, don't know what i havt to do

**Comment by markknochen1** [comment]
i found this:
http://stackoverflow.com/questions/26461966/curl-post-to-https-url-returns-sslread-error

but it will not work

Mark

**Comment by odro** [comment]
I got the same error. Nothing helps.
Installed new PHP 5.5, curl with openssl on Mac OS.
The above post Form stackoverflow does not help. Getting after New curl with openssl Transport Exception via http from composer.

**Comment by padraic** [comment]
If this is the installer download (curl on command line), simplest solution is to just download Composer using your browser, or even download the current PHAR directly from https://getcomposer.org/composer.phar if you would normally meet all of the criteria for running Composer.

**Comment by odro** [comment]
Did u try to download the PHAR directly? 
The brwoser is running and running and running ... without a download from https://getcomposer.org/composer.phar .

```
wget  -S https://getcomposer.org/composer.phar
--2015-05-31 08:50:26--  https://getcomposer.org/composer.phar
Resolving getcomposer.org... 87.98.253.108
Connecting to getcomposer.org|87.98.253.108|:443... connected.
HTTP request sent, awaiting response...
```

**Comment by padraic** [comment]
It's definitely something wrong on your local non-PHP setup - wget has nothing to do with PHP. Try again with Safari/Chrome or similar, if available, for the PHAR.
