### ISSUE TITLE
Autoload class alias

### ISSUE THREAD

**Issue by thunderer** [composer/composer#4043]
I got an idea for new autoloading method to (for example) effortlessly maintain BC. It would need a new key in `autoload` inside `composer.json`, namely `class-alias`. It'd look like that:

```json
"autoload": {
    "class-alias": {
        "Foo\\Bar": "Baz\\Qux",
        "Sample": "Namespaced\\Other"
        }
    }
```

For every item on that list Composer's autoloader would call `class_alias($name, $alias)` on the first call and from that on PHP would handle everything automatically. If you think that it's a good idea I can work on this and submit PR.

BTW I'm aware of the [autoload-files](https://getcomposer.org/doc/04-schema.md#files) feature where I could put all those aliases.

Context: I'm working on a [project](https://github.com/thunderer/Shortcode) which started as a small set of classes in the same namespace. Since then I got new feature ideas that outgrew that structure and I'm currently refactoring everything to accomodate for future. I was serious about maintaining BC even in 0.x releases to which I needed to make [such](https://github.com/thunderer/Shortcode/blob/master/src/ParserInterface.php) a [terrible](https://github.com/thunderer/Shortcode/blob/master/src/Syntax.php) [mess](https://github.com/thunderer/Shortcode/blob/master/src/Extractor.php). I'll remove all those placeholders in newer versions but with that feature I wouldn't even need those files.

**Comment by stanvass** [comment]
You can add your alias autoloader via spl_autoload_register() without Composer's involvement.

**Comment by Seldaek** [comment]
IMO it's ok to break BC in the 1.0 and clean up the mess, you can provide a file that people can include with a bunch of class_aliases if they want to ease up the upgrade path?
