### ISSUE TITLE
2 dependencies infinite loop.

### ISSUE THREAD

**Issue by bweston92** [composer/composer#4044]
```
{
  "require": {
    "laravel/framework": "5.0.*",
    "atrauzzi/laravel-doctrine": "1.0.0"
  },
  "minimum-stability": "dev"
}
```

I've had this running over 30 minutes, no errors just 100% CPU usage. Any ideas?

**Comment by nevvermind** [comment]
Post your `composer --version` and the command you're having troubles with in verbose mode (e.g. `composer install -vvv`. Let it run until you see something wrong. If not, post the whole output here anyway.

**Comment by bweston92** [comment]
Version
```
Composer version 1.0-dev (42a9561ae23b236da1d5a4acf50f7ea96ebe68aa) 2015-05-02 23:10:29
```

Downloads a lot of json files and puts them into cache (I've tried removing cache folder) it freezes after getting `symfony/config` which could just be the last lookup.

**Comment by nevvermind** [comment]
@bweston92, that's not the output, that's your recollection of it. You needn't post the whole json-fetching process, but the last 10-20 lines maybe? Also, what command do you actually run? `composer clearcache && composer install -vvv` or whichever command you use to install. What about `--prefer-dist` vs `--prefer-source` when installing?

**Comment by bweston92** [comment]
I have tried both dist and source.
Here is output: https://gist.github.com/bweston92/3329b2d6e6b281342b1d

**Comment by slbmeh** [comment]
It don't think it's hanging. It first downloads all of the package metadata for all of the repositories it is aware of to discover the versions.  Then the dependency resolver steps in and starts crunching to determine which versions will satisfy all constraints.

With very little specificity in your composer.json, I wouldn't be surprised to see it take a significant amount of time.

**Comment by nevvermind** [comment]
@slbmeh - What do you mean by "very little specificity"? The constraints seem very specific to me.

**Comment by bweston92** [comment]
I actually had this running for an hour whilst on break, this didn't complete.

The lack of information in the `composer.json` file is irrelevant. I can install other packages with even less (just the require key).

**Comment by nevvermind** [comment]
Used the same json, and it got stuck at
```
[lots of JSON parsed...]
Reading /Users/nsfw/.composer/cache/repo/https---packagist.org/provider-illuminate$view.json from cache
Downloading http://packagist.org/p/symfony/config$0bb533b901bd7128943839d07240dacdadb9209dfcc132d503f044bed1c06640.json
Writing /Users/nsfw/.composer/cache/repo/https---packagist.org/provider-symfony$config.json into cache
```
I ran it using `php -dxdebug.auto_trace=1 -dxdebug.collect_params=0 composer.phar install -vvv`. After waiting for the trace file to get to 1GB (10-15 seconds), I stopped it.

Looking at the trace file, the following _group of calls_ seems to repeat thousands of times, until the very end. Not sure if this is normal.
```
  108.3527  214864368                             -> Composer\DependencyResolver\Decisions->decidedInstall() phar:///Users/nsfw/work/delete/composer.phar/src/Composer/DependencyResolver/Solver.php:708
  108.3528  214864416                               -> abs() phar:///Users/nsfw/work/delete/composer.phar/src/Composer/DependencyResolver/Decisions.php:76
  108.3528  214863976                             -> count() phar:///Users/nsfw/work/delete/composer.phar/src/Composer/DependencyResolver/Solver.php:686
  108.3528  214863976                               -> Composer\DependencyResolver\RuleSet->count() phar:///Users/nsfw/work/delete/composer.phar/src/Composer/DependencyResolver/Solver.php:686
  108.3528  214863976                             -> count() phar:///Users/nsfw/work/delete/composer.phar/src/Composer/DependencyResolver/Solver.php:687
  108.3528  214863976                               -> Composer\DependencyResolver\RuleSet->count() phar:///Users/nsfw/work/delete/composer.phar/src/Composer/DependencyResolver/Solver.php:687
  108.3528  214863928                             -> Composer\DependencyResolver\Rule->isDisabled() phar:///Users/nsfw/work/delete/composer.phar/src/Composer/DependencyResolver/Solver.php:694
  108.3528  214864368                             -> abs() phar:///Users/nsfw/work/delete/composer.phar/src/Composer/DependencyResolver/Solver.php:708
```

**Comment by alcohol** [comment]
Allowing dev mode **greatly** increases the amount of combinations that composer has to check against before being able to find the most optimal match of combined requirements. Did you try benchmarking this against allowing stable only?

**Comment by slbmeh** [comment]
@bweston92 I wouldn't be surprised if it would take a few hours. What the minimum stability to dev is doing is potentially adding every commit of every repository of dependencies and child dependencies as version candidates.

Having just the require key is a tighter version constraint and implies greater specificity.  The rule decisions being called thousands of times is normal when you introduce thousands of possible combinations.

**Comment by slbmeh** [comment]
I put some debugging output in the solver, pool, decisions, and problem classes... And it was churning away for over an hour trying to calculate a resolvable decision.

If you have a more explicit `composer.json` say by explicitly adding `"illuminate/support": "4.*"` which is on your second dependency it eliminates the entire possibility of `"atrauzzi/laravel-doctrine": "dev-master"` which introduces a much wider range of doctrine/orm candidates.

**Comment by nevvermind** [comment]
@slbmeh - Nicely done. I'm afraid I'll be in the same situation as @bweston92 at some point and those debugging info would be very helpful. Do you think some of that information would be helpful if logged to console on debug level?

**Comment by slbmeh** [comment]
@nevvermind it is extremely verbose to the extent that when I pushed it to a file it got to 7gb in around 5 minutes. It would be helpful, there is a `DebugSolver` class that I don't know how to incorporate, so I believe there may have been some similar effort at one point.

My output is a bunch of rough printf statements and an occasional var_dump. I don't know what messages that I output when I'm working with solver related plugins would be beneficial to a user.

I think it would be nice to change some of the output statements to a monolog stream so certain messages can be logged to channels that are not displayed by default.

**Comment by nevvermind** [comment]
I don't think 7GB is too much in debug mode, debug being _after_ very verbose and all. Have you seen mod_rewrite with debug level logging? :stuck_out_tongue: 

Yes, I know that DebugSolver class but I was in the same situation as you, not knowing how to use it. I guess when developing _Composer_.

> I don't know what messages that I output when I'm working with solver related plugins would be beneficial to a user.

And I don't know what _can_ be logged in there.

PS: This happens and the solving state, right? Once that is done (the lock file is created), composer doesn't have to re-think again, is it?

**Comment by slbmeh** [comment]
Output isn't readily available for the most part, which is why I resort to printf and var_dump.  If you want to know that it's still doing something there's a few places you need to put output to catch the different states of the loops.

I know where to barf out data to see that it's still going, but I don't know enough about the solver logic to have truly meaningful output.  I think maybe dispatching events in some of the solver classes might be a clean way to do it.  Then you can have event listeners simply output a dot on the screen when an event is called, or do something more complex like tracing the steps of each solution.

**Comment by stof** [comment]
@slbmeh the dev stability does not allow any commit to be used. Dev versions are only branches, not every commits (Packagist does not keep metadata for each commit. It would be insane)

**Comment by Seldaek** [comment]
So I am not sure why you end up in an infinite loop, for me it ends after 15seconds in a conflict, because atrauzzi/laravel-doctrine 1.0.0 requires illuminate/support 4.* and you require laravel/framework which replaces illuminate/support in version 5.*, so that can't be installed together.

Requiring atrauzzi/laravel-doctrine dev-master fixes it for me, since that one is based on L5.

**Comment by bweston92** [comment]
@Seldaek it still doesn't work if I take what is there. Also maybe when we're asking for a verbose output we can output some information to guide us on this?

**Comment by Seldaek** [comment]
@bweston92 I am not sure what to say if I can't reproduce the issue at all here :/
