### ISSUE TITLE
Resetting a tag

### ISSUE THREAD

**Issue by umulmrum** [composer/composer#4046]
I have run into the following situation:
- I created a (annotated) tag 1.0.3 in my package
- I composer-updated a project where that package is a dependency
- I realized there's still a bug in the code, so I fixed it
- I re-created that tag (didn't want to use a new tag number as the repository is part of a larger application where exactly that version is to be released) by resetting the branch or by deleting and re-tagging.

Packagist then updated that package again and it looked fine.

I updated the project again, expecting composer to recognize the changed hash of the tag and therefore update the package once more. However, composer said there was nothing to update.

So there arise two questions:
1. Does composer work correctly in that case?
2. If yes, is there a better way to deal with my problem? Is it an option to use a four-part version number, like 1.0.3.1?

Thank you!

**Comment by slbmeh** [comment]
The 1.0.3.1 will work. Also, explicitly specifying the hash for the tag should work also `1.0.3#aa46728f` or whatever...

I don't know the intended behavior for this specific case, but I believe it to be undesirable and incorrect. The lock file acts on a hash, if the repository has a different hash for the same version it should at the very least give you a message.

**Comment by padraic** [comment]
It's a correct behaviour for Composer. The concept of tags is that they are never altered once there's some external entity depending on them. You can create a tag with the 4th integer for truly minor mistakes to overcome that, but avoid replacing existing tags.

Ideally, Composer would report an error in this scenario, not simply to push you into a new tag correctly, but also as a warning that a dependency did have its tag replaced for some reason.

**Comment by umulmrum** [comment]
ok thanks @slbmeh @padraic  - I will go with the 4-part version.
