### ISSUE TITLE
composer and perl

### ISSUE THREAD

**Issue by 19anti91** [composer/composer#4048]
Hello guys I currently have Perl to manage my extensions but I am thinking of using composer. If I install composer would it delete everything from Perl? Or everything I'll be left the same? Thanks

**Comment by GromNaN** [comment]
Composer does not install PHP extensions, if it is what you are talking about.

It only check the required PHP extensions are installed.

**Comment by 19anti91** [comment]
So by installing composer it won't mess any Perl package up?

**Comment by slbmeh** [comment]
Do you mean pear or pecl by chance?  Perl packages normally come from CPAN and have nothing to do with PHP so there would be no issue.

**Comment by 19anti91** [comment]
My bad guys i typed this form my phone and autocorrect kills it. I meant PEAR, lol. :/

**Comment by GromNaN** [comment]
Then Composer can install PEAR packages in the vendor dirof your project. It never alter PEAR packages installed by PEAR system.

**Comment by 19anti91** [comment]
Perfect. I am new to this so I had that doubt. Thank you so much guys!!!!
