### ISSUE TITLE
Global namespace pollution.

### ISSUE THREAD

**Issue by SamMousa** [composer/composer#4052]
Currently the composer autoloader uses a function in the global namespace to include files.

Wouldn't a better alternative be to use a Closure for this? (I'm assuming the function wraps require to create a scope)

Now:

        foreach ($includeFiles as $file) {
            composerRequire4d217f203f86e1fb71e7b245f0ae45ab($file);
        }

My proposal:

        $require = function($file) {
            require $file;
        };

        foreach ($includeFiles as $file) {
            $require($file);
        }

To me this seems to be a cleaner approach.

**Comment by alcohol** [comment]
Probably done for the same reason as this [ClassLoader.php#L405-L409](https://github.com/composer/composer/blob/master/src/Composer/Autoload/ClassLoader.php#L405-L409)

**Comment by SamMousa** [comment]
Yes however in static functions there is no scope for closures so this should be fine.
Also in php 5.4+ you can use ::bind to explicitly set (or remove) a scope.  

In any case there is no need for it in this scenario.

**Comment by alcohol** [comment]
But Composer supports 5.3 and up. So can't depend on 5.4 features/functionality.

**Comment by SamMousa** [comment]
In 5.3 closures have no $this or self so there it is not an issue at all.

**Comment by alcohol** [comment]
I don't know, check #2667 for specifics.

**Comment by Seldaek** [comment]
Rather not do this because it works right now and we can't really fix this for 5.3 while having 5.4+ safety IMO. One global function with a garbled name isn't a problem realistically.
