### ISSUE TITLE
Ability to tie composer options to environment.

### ISSUE THREAD

**Issue by rquadling** [composer/composer#4054]
Hi.

Is there a way such that when we say ```composer install``` on our production server, it will automatically be capable of using the ```--no-dev``` option?

Something that can be configured in ```composer.json``` would be really nice.

**Comment by aaukt** [comment]
duplicate of #4026?

**Comment by rquadling** [comment]
Oh dear. Brain is fried. Is it Saturday yet? In my defence, my wife is expecting our first baby. So things like composer having the ability to differentiate between production and development is probably not getting as much focus as it should.

**Comment by aaukt** [comment]
Looks like it's getting too much focus ;)

All the best for you 3!

**Comment by rquadling** [comment]
Ha!! Ta!
