### ISSUE TITLE
Documentation Link in JSON Schema

### ISSUE THREAD

**Issue by bbatsche** [composer/composer#4055]
It would be nice if I could specify a link to my API documentation within the schema of my `composer.json` file. Something along the lines of:

```json
"support": {
    "documentation": "http://example.com/api/master/index.html"
}
```

Ideally, then packagist.org would add that link to the heading for my package along side of canonical, source, homepage, etc.

**Comment by slbmeh** [comment]
That's what I use the `source` section of support for, I suppose if your canonical URL didn't point to somewhere you can actually browse source code you might want a different link to place.

**Comment by bbatsche** [comment]
Sounds like a good work around, but also just that: a work around.

**Comment by alcohol** [comment]
What about putting it under the "wiki" value? I know, you'll feel guilty because it is not literally a "wiki" -- but it's a source of information, is it not?

/cc @Seldaek does documentation warrant adding another item under "support" ?

**Comment by Seldaek** [comment]
Hmm yes maybe we should add a support.docs, sounds reasonable I am not sure why we don't have it :)

**Comment by alcohol** [comment]
@bbatsche I'll submit a PR to packagist today. So, soon(tm) you can use `support.docs` :-).

**Comment by alcohol** [comment]
@bbatsche composer/packagist#501 has been merged and deployed.
