### ISSUE TITLE
One of the repositories is not being mapped the present classes

### ISSUE THREAD

**Issue by hackin88** [composer/composer#4066]
========
en_US
========

Hello

Good Night

I'm having the following problem:

One of the repositories is not being mapped the present classes

1)

Composer.json created a file with the following content

	{
		"repositories": [
		    {
		        "type": "package",
		        "package": {
		            "name": "moiplabs/moip-php",
		            "version": "master",
		            "source": {
		                "type": "git",
		                "url": "https://github.com/moiplabs/moip-php.git",
		                "reference": "master"
		            },
		            "autoload": {
		                "classmap": ["lib"]
		            }
		        }
		    }
		],
		"require": {
		    "moiplabs/moip-php": "dev-master"
		}
	}

Saved and run the following command in the terminal

	composer clear-cache update && composer

In

	/vendor/composer/installed.json

We have

	[
		{
		    "name": "moiplabs/moip-php",
		    "version": "master",
		    "version_normalized": "9999999-dev",
		    "source": {
		        "type": "git",
		        "url": "https://github.com/moiplabs/moip-php.git",
		        "reference": "master"
		    },
		    "type": "library",
		    "installation-source": "source",
		    "autoload": {
		        "classmap": [
		            "lib"
		        ]
		    }
		}
	] 

Where we see that we have been mapped classes that library

2)

Composer.json created a file with the following content

	{
		"repositories": [
		    {
		        "type": "package",
		        "package": {
				    "name": "braspag/braspagapiphpsdk",
				    "version": "master",
				    "source": {
				        "url": "https://github.com/Braspag/BraspagApiPhpSdk.git",
				        "type": "git",
				        "reference": "master",
				        "autoload": {
							"classmap": [
								"Models",
								"BraspagApiIncludes.php"
							]
				        }
				    }
		        }
		    }
		],
		"require": {
		    "braspag/braspagapiphpsdk": "dev-master"
		}
	}

Saved and run the following command in the terminal

	composer clear-cache update && composer

In

	/vendor/composer/installed.json

we have

	[
		{
		    "name": "braspag/braspagapiphpsdk",
		    "version": "master",
		    "version_normalized": "9999999-dev",
		    "source": {
		        "type": "git",
		        "url": "https://github.com/Braspag/BraspagApiPhpSdk.git",
		        "reference": "master"
		    },
		    "type": "library",
		    "installation-source": "source"
		}
	]

Where we see that NOT been mapped classes that library

Thus I can not call the same

3)

Can anyone help me?

---

========
pt_BR
========

Ola

Boa Noite

Estou tendo o seguinte problema:

Um dos repositórios não está sendo mapeada as classes presente

1)

Criei um arquivo composer.json com o seguinte conteúdo

	{
		"repositories": [
		    {
		        "type": "package",
		        "package": {
		            "name": "moiplabs/moip-php",
		            "version": "master",
		            "source": {
		                "type": "git",
		                "url": "https://github.com/moiplabs/moip-php.git",
		                "reference": "master"
		            },
		            "autoload": {
		                "classmap": ["lib"]
		            }
		        }
		    }
		],
		"require": {
		    "moiplabs/moip-php": "dev-master"
		}
	}

Salvei e execute o seguinte comando no terminal

	composer clear-cache && composer update

Em 

	/vendor/composer/installed.json

Temos

	[
		{
		    "name": "moiplabs/moip-php",
		    "version": "master",
		    "version_normalized": "9999999-dev",
		    "source": {
		        "type": "git",
		        "url": "https://github.com/moiplabs/moip-php.git",
		        "reference": "master"
		    },
		    "type": "library",
		    "installation-source": "source",
		    "autoload": {
		        "classmap": [
		            "lib"
		        ]
		    }
		}
	] 

Onde vemos que foi mapeado as classes dessa biblioteca

2)

Criei um arquivo composer.json com o seguinte conteúdo

	{
		"repositories": [
		    {
		        "type": "package",
		        "package": {
				    "name": "braspag/braspagapiphpsdk",
				    "version": "master",
				    "source": {
				        "url": "https://github.com/Braspag/BraspagApiPhpSdk.git",
				        "type": "git",
				        "reference": "master",
				        "autoload": {
							"classmap": [
								"Models",
								"BraspagApiIncludes.php"
							]
				        }
				    }
		        }
		    }
		],
		"require": {
		    "braspag/braspagapiphpsdk": "dev-master"
		}
	}

Salvei e execute o seguinte comando no terminal

	composer clear-cache && composer update

Em 

	/vendor/composer/installed.json

Temos

	[
		{
		    "name": "braspag/braspagapiphpsdk",
		    "version": "master",
		    "version_normalized": "9999999-dev",
		    "source": {
		        "type": "git",
		        "url": "https://github.com/Braspag/BraspagApiPhpSdk.git",
		        "reference": "master"
		    },
		    "type": "library",
		    "installation-source": "source"
		}
	]

Onde vemos que NÂO foi mapeado as classes dessa biblioteca

Dessa forma não consigo chamar as mesmas

3)

Alguém pode me ajudar ?

**Comment by alcohol** [comment]
In scenario number 2: "autoload" should not be part of "source".

Compare your package definition of scenarion 1 and scenarion 2 and you will find the difference.
