### ISSUE TITLE
Featurerequest: add require and env for ci

### ISSUE THREAD

**Issue by geki007** [composer/composer#4073]
Hi,

i would like to have an extra require like require and require-dev for ci (require-ci or require-test).
I think you need also a new env for this change.
At the moment thinks like phpmd, phpcpd are in my require-dev but i think no developer needs it, only the testserver

**Comment by alcohol** [comment]
We've had a similar request (#3932); and it was decided that there will be no such additional require(-dev) sections, unless you can provide a very strong argument. Polluting the composer.json schema is not something that should be done lightly.

In this case, I'd say this is a definite no :-1: .

The require-dev section is perfectly fine for this.
