### ISSUE TITLE
Support requiring a dependency without its own dependencies

### ISSUE THREAD

**Issue by kherge** [composer/composer#4079]
In my project, I rely on `symfony/framework-bundle` for maybe 1-2 self-contained classes. Because I only need those two classes, I don't want the 10+ other dependencies that `symfony/framework-bundle` has.

Does Composer have a configuration setting I can use to prevent the other dependencies from being installed?

**Comment by stof** [comment]
this is asking Composer to stop doing its job. this looks totally wrong to me.

**Comment by kherge** [comment]
I think it comes down to which philosophical principle I want to violate. Do I want to reinvent the wheel when it comes to two well maintained classes (Not Invented Here), or do I want to have a configurable option of disabling part of a package manager is meant to do?

Considering that the latter wouldn't affect normal use and could arguably lead to better performance as well, I think it's practical to support the latter option.

**Comment by renanbr** [comment]
@kherge why not to open an issue at sf repository for that? this problem is not related to Composer

**Comment by kherge** [comment]
@renanbr You're right it's not a problem with Composer. I am asking that this feature/enhancement be added.

I'll open an issue at that repository, but I would still like to see this feature be added to Composer. I may run across another package that puts me in a similar position where the devs are less likely to resolve open issues.

**Comment by stof** [comment]
@kherge the feature you are asking to add in Composer is a way to tell composer to stop doing its own job. This looks like a very bad idea.

**Comment by alcohol** [comment]
Why do you even care? If you don't use those other classes, they are not going to bother you. They're just there, in `vendor/`, minding their own business. You should not consider `vendor/` a part of your projects codebase. You could even setup your build job for your release package to remove the classes that you do not use from `vendor/`. So really, this is not an "issue".
