### ISSUE TITLE
Version constraint matching alpha,beta,rc releases does not work as expected

### ISSUE THREAD

**Issue by cebe** [composer/composer#4080]
Consider the following version constraint:

`>=2.7.0-dev,<2.7.0`

this should include every development version and alpha,beta,rc release that comes before the 2.7.0 release. the match works for the first part:
http://semver.mwl.be/#?package=symfony%2Fsymfony&version=%3E%3D2.7.0-dev&minimum-stability=dev
But as soon as the second part is added the constraint does not match anything:
http://semver.mwl.be/#?package=symfony%2Fsymfony&version=%3E%3D2.7.0-dev,%3C2.7.0&minimum-stability=dev

I also tried this with the following composer.json to verify the bug is not only on `semver.mwl.be`:

```json
{
	"minimum-stability": "dev",
    "require": {
        "symfony/symfony": ">=2.7.0-dev,<2.7.0"
    }
}
```

```
# composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package symfony/symfony could not be found in any version, there may be a typo in the package name.
```

See https://github.com/FriendsOfPHP/security-advisories/pull/72#discussion_r31214680 for more details. /cc @stof

**Comment by alcohol** [comment]
Given constraint resolves to:

```
class Composer\Package\LinkConstraint\MultiConstraint#5 (3) {
  protected $constraints =>
  array(2) {
    [0] =>
    class Composer\Package\LinkConstraint\VersionConstraint#3 (3) {
      private $operator =>
      string(2) ">="
      private $version =>
      string(11) "2.7.0.0-dev"
      protected $prettyString =>
      NULL
    }
    [1] =>
    class Composer\Package\LinkConstraint\VersionConstraint#4 (3) {
      private $operator =>
      string(1) "<"
      private $version =>
      string(11) "2.7.0.0-dev"
      protected $prettyString =>
      NULL
    }
  }
  protected $prettyString =>
  string(18) ">=2.7.0-dev,<2.7.0"
  protected $conjunctive =>
  bool(true)
}
```

It is pretty obvious these conflict with each other. What I don't understand yet is why <2.7.0 has the -dev suffix in the constraint suddenly.

**Comment by alcohol** [comment]
For some reason writing the constraint as `>=2.7.0-dev,<2.7.0-stable` solves it. It no longer appends the `-dev` suffix in the less than comparison constraint.

**Comment by alcohol** [comment]
I *think* these are the offending lines: [VersionParser.php#L332-L338](https://github.com/composer/composer/blob/master/src/Composer/Package/Version/VersionParser.php#L332-L338)

Not sure yet why `-dev` is always added to a version if there is no stability suffix.

**Comment by alcohol** [comment]
These seem to be the offending lines: [VersionParser.php#L442-L444](https://github.com/composer/composer/blob/master/src/Composer/Package/Version/VersionParser.php#L442-L444)

**Comment by Seldaek** [comment]
The reason is that most people when they write >=1.0 for example they mean to include any 1.0 including -dev, and similarly <2.0 they generally mean to exclude all from 2.0-dev, not just 2.0-stable (as 2.0-dev, 2.0-alpha and so on are *under* 2.0-stable). This resolved a lot of WTF situations, but yes in this particular edge case it doesn't help, and you need to disambiguate with `>=2.7.0-dev,<2.7.0-stable` (or I would think `2.7.0.*@dev` also works). It's not quite a common constraint though, so I am not sure we need to facilitate this. Documenting it however sounds fair enough ;)

**Comment by alcohol** [comment]
Not quite, `2.7.0.*@dev` will also match tag of `2.7.0` (which is considered stable). So the only working example seems to be appending `-stable`.

**Comment by fduch** [comment]
@Seldaek i ran some tests and need some clarification..

If i call `composer require symfony/routing ">=2.6 <2.7"` inside the project with such composer.json:

```
{
    "name": "test/test",
    "minimum-stability": "dev",
    "require": {}
}
```
it installs `symfony/routing (2.6.x-dev dc9df18)`. Should it be `2.7.0-BETA2` since 2.7.0-BETA2 < 2.7.0?

If i change `minimum-stability` to for example `alpha` and run the same command it installs `symfony/routing (v2.6.8)`. For now it's perfectly not `dev` version, but again, should it be `2.7.0-BETA2` instead?

**Comment by Seldaek** [comment]
That is correct, because as I said above `<2.7` gets expanded to `<2.7-dev` as most people just don't realize that `2.7-beta` matches `<2.7` until you tell them that yes `2.7-beta` is lower than `2.7-stable` and `2.7` means `2.7-stable`. 

There are IMO very few cases where you actually mean `<2.7-stable` when you write `<2.7`, so we do the least surprising thing and let the odd cases be explicit.

**Comment by fduch** [comment]
Ahh, i missed your point for the first time. Now it's clear, thank you!

**Comment by sminnee** [comment]
OK, so this passes: https://gist.github.com/a023829dafc9712b43e3

Which suggests that the OP can use this as their dependency string:

    >=2.7.0-dev,<2.7.0-stable

Shall we close the ticket then?

**Comment by sminnee** [comment]
Ooh, one question, should `>=2.7.0` include pre-releases or not? That would be consistent with "number-only comparison always treat both the stable and pre-releases as a single unit, included or excluded in their entirety". It would also make the lower bound of the comparsion the same as for `~2.7.0`, which seems logical.

That would be a code change. Should I patch it?

**Comment by alcohol** [comment]
@sminnee nooooo, you really don't want to do that.

**Comment by alcohol** [comment]
By the way, `~2.7.0` does not include pre-releases. I don't know what gave you that impression.

**Comment by Seldaek** [comment]
@alcohol why nooooo? It sounds like a consistency fix to me. Also >= is rarely useful so I doubt it would have that big of an impact.

**Comment by alcohol** [comment]
Consistency where? I'm saying no because it wouldn't be consistent.

**Comment by sminnee** [comment]
@alcohol regarding the `~2.7.0` comparison:

 * Here's my PR from a couple of years back that changed it: https://github.com/composer/composer/pull/1881
 * Here's the relevant test in master: https://github.com/composer/composer/blob/master/tests/Composer/Test/Package/Version/VersionParserTest.php#L315

The rationale when a I made the change to `~2.7` was to make it consistent with `2.*`

If you don't want pre-release packages, set min-stability to stable.

**Comment by alcohol** [comment]
Then why doesn't it include `-dev`?

**Comment by alcohol** [comment]
Never mind, it does include `-dev`, the phrasing of "include pre-releases" caught me off-guard.

**Comment by sminnee** [comment]
There are a few principles that I'm advocating.

First, something that should be uncontroversial, is that the following comparisons should have the same lower bound:

 * `>=2.1.0`
 * `2.1.*`
 * `~2.1`

Second, which is a little more controversial, but for `2.1.*` and `~2.1` has been implemented functionality for years, is that if you have selected to install pre-release packages of a particular stability level, that these releases should be just as suitable for resolving a dependency as their subsequent stable release.

**Comment by alcohol** [comment]
If all the lower boundaries assume `-dev` by default that would make sense. I retract my statement about inconsistency. Just don't say "pre-releases" anymore please :p

**Comment by sminnee** [comment]
Sorry, what's the best noun for that? I can fix in the docs.

**Comment by alcohol** [comment]
"non-stable" ?

**Comment by alcohol** [comment]
Shouldn't the behaviour of ranges be adjusted too though then?

E.g. `1.0-2.0` becomes `>=1.0.0-dev, < 2.1.0-dev`?

**Comment by Seldaek** [comment]
Doesn't it already?

**Comment by sminnee** [comment]
I'll check.

**Comment by sminnee** [comment]
I'm struggling with docs; how does this read?

If you are using range comparisons when selecting non-stable packages, and you
specify a numeric version number (that is, no suffix indicating alpha, beta,
rc, or stable), then both non-stable and stable versions of a particular
release number will be treated as equally valid.

 * `>=`/`<=` will accept non-stable releases as well as the stable release.
 * `<`/`>` will reject non-stable releasese as well as the stable release.
 
If you wish to consider only the stable release in the comparison, add the
suffix `-stable` to the version number.

Here are some examples:

 Example         | Interpretation
 --------------- | --------------
`>=1.0.0`        | Any release, stable or non-, of 1.0.0 will be allowed
`>=1.0.0-stable` | Only the stable release of 1.0.0 will be allowed
`<2.0.0`         | Neither release, stable or non-, of 2.0.0 will be allowed
`<2.0.0-stable`  | Only stable release of 2.0.0 will be disallowed; non-stable releases will be allowed

**Comment by sminnee** [comment]
Looking at the range comparisons, there's an inconsistency with how point versions are interpreted, and I'm not quite sure why

Compare this:

            array('1 - 2',                new VersionConstraint('>=', '1.0.0.0-dev'),   new VersionConstraint('<',  '3.0.0.0-dev')),

To this:

            array('1.3 - 2.1.3',          new VersionConstraint('>=', '1.3.0.0-dev'),   new VersionConstraint('<=', '2.1.3.0')),

The outcome seems to be the same, though: both of these include non-stable releases.

**Comment by alcohol** [comment]
So..

`>1.0` is `>1.0.0-stable` ?
`<2.0` is `<2.0.0-dev`?

And..

`>=1.0` is `>=1.0.0-dev` ?
`<=2.0` is `<=2.0.0-dev` ?

I'd include a line btw emphasising once more that the packages matched by these constraints **are** also still checked against the `minimum-stability` setting.

**Comment by sminnee** [comment]
Internally, it's the following:

 * >1.0 is >1.0.0.0
 * <2.0 is <2.0.0.0-dev
 * >=1.0 is >=1.0.0.0-dev
 * <=2.0 is <=2.0.0.0

**Comment by alcohol** [comment]
Well, no suffix is equal to `-stable` so I just added those for clarity.

**Comment by sminnee** [comment]
Yep - you got the 4th one wrong, though ;-)

**Comment by alcohol** [comment]
No I already fixed it :p did just realise that as I ran them through my head again.

**Comment by Seldaek** [comment]
Sam regarding the 1.3 - 2.1.3, it is just because we follow npm strictly 
and it says if you define a full semver version it is a <= to that, if 
you define a partial then it appends a .* to it sort of so in that case 
we go <(n+1)-dev although I am not sure if I make any sense at this 
point but anyway the current behavior looks correct to me.

**Comment by sminnee** [comment]
Yeah, I agree.
