### ISSUE TITLE
Dependency solver issue with pinned commits

### ISSUE THREAD

**Issue by kdambekalns** [composer/composer#4082]
In the course of working on https://github.com/doctrine/migrations/issues/261 I stumbled over this, which seems to be a bug in the dependency solver.

I pinned the required doctrine/migrations to a version not yet conflicting with doctrine/orm 2.3. A first composer update works fine, but further updates result in
```
  [Composer\DependencyResolver\SolverProblemsException]
    Problem 1
      - Installation request for typo3/flow 2.3.* -> satisfiable by typo3/flow[2.3.4].
      - doctrine/migrations 1.0.x-dev conflicts with doctrine/orm[v2.3.6].
      - typo3/flow 2.3.4 requires doctrine/orm 2.3.* -> satisfiable by doctrine/orm[v2.3.6].
      - Installation request for doctrine/migrations 1.0.x-dev#f623eff82515f55d18199706851895ced831cba0 -> satisfiable by doctrine/migrations[1.0.x-dev].
```
It seems the dependency solver of composer looks at the 1.0.x-dev dependencies, not those of the pinned hash.

Here is a graph of all the dependencies in that project: https://www.dropbox.com/s/btsg9xivkhulnlt/flow-2.3-project-dependencies.pdf?dl=0

**Comment by alcohol** [comment]
That's not a bug. See also this thread: [issues/3918#issuecomment-91204245](https://github.com/composer/composer/issues/3918#issuecomment-91204245)

**Comment by kdambekalns** [comment]
Ok, thanks. We'll solve it by using the closest tag then. Not the same, but should work out.
