### ISSUE TITLE
Plugins can only declare one exact Plugin API version

### ISSUE THREAD

**Issue by nevvermind** [composer/composer#4085]
### The problem
Currently, plugin developers can only specify an **exact** version of the Plugin API on which their functionality depends:
```json
{ "require": { "composer-plugin-api": "1.0.0" } }
```
### Why is it a problem
Scenario: Plugin `PLUG1` was originally created with `"composer-plugin-api": "1.0.0"`. After a while, the Composer plugin API evolves, changing its version to `1.1.0`. Because `1.1.0` implies no BC break, `PLUG1` should still work with this version. But it cannot specify that.  
The developer can only set _either_ `1.0.0` (possibly breaking when used with a newer Composer), or `1.1.0` (possibly breaking with an older Composer). Ideally, the developer should be able to mention that `PLUG1` works with _both_ `1.0.0` and `1.1.0`. Or even up until `1.9.9`. Or, if generic enough, across major versions of the plugin API.

One other consequence is that, on the next Plugin API _minor_ version bump, _all_ plugins will trigger a warning (Composer still registers them).  

### Considerations
1. **BC!** :grimacing: Whatever we end up changing, the old style of declaring an API version (`"composer-plugin-api": "1.0.0"`) *must* continue to function as expected. And by "expected" I mean, up until - and including - `1.9.9.9-stable`.
2. From looking in the codebase, plugins are still registered, even if the version didn't match, triggering a warning. This behaviour should be changed, as the next major Plugin API version could, by definition, break old plugins if they're allowed to be loaded. Mismatches should _not_ be registered.
3. Some plugins _can_ be so generic that they would work even across _major_ API version changes. We should avoid automatically assuming that a plugin made initially for `1.0.0` will not work with `2.3.4` or `12.0.1`. This is the developer's say.

#### 1. API version as API version _interval_ (constrained)
@Seldaek said [this](https://github.com/composer/composer/pull/3377#issuecomment-76076235):
> Regarding the version that is indeed a problem but I think it's one we need to fix in a different way, we probably need to provide the API in version <=1.1.0 and then load all plugins that require those versions, because technically you could install a new plugin and then run it with an old composer and it should just skip plugins that are installed but not loadable instead of crashing.

If I understood correctly, this suggests changing [the plugin API version](https://github.com/composer/composer/blob/e64470c987fdd6bff03b85eed823eb4b865a4152/src/Composer/Plugin/PluginInterface.php#L30) to be _an interval_. I know @Seldaek said that having BC in mind, but I don't think this should be done, because a version and an interval (or constraint) are two different things. Plugins, and not the API, should state the interval.

Also, this would be really awkward to work with, when bumping the API version. How will the version look like on `2.0`? `^2.0`? What if my plugin works with `2.0` still?

#### 2. Plugins declare their version as a version constraint (BC safe)
That is, instead of _the API_ declaring an interval, _the plugin_ actually declares on which version(s) it can work. Some valid examples:
```json
{ "require": { "composer-plugin-api": "^1.0" } }
{ "require": { "composer-plugin-api": "2.0.*" } }
{ "require": { "composer-plugin-api": "1.0.0" } }
{ "require": { "composer-plugin-api": ">=1.0.0 <3.1" } }
```
Basically, we leverage the version parsing and matching abilities of Composer. It's still a package version, right?

I already begun work on this, mainly focusing on this behaviour [here](https://github.com/composer/composer/blob/e64470c987fdd6bff03b85eed823eb4b865a4152/src/Composer/Plugin/PluginManager.php#L132). I had some success with this change [here](https://gist.github.com/nevvermind/4932a246079f59cea5a8#file-pluginmanager-php-L24-L27).  To keep it BC, I assumed the old version style - `1.0.0` - to be equivalent to `^1.0`. I'm guessing that's the normal expectations anyway. If a `2.0` API breaks a `1.0.0` plugin, that's semver-normal.

But then I hit a wall realising that the _Solver_ wasn't fixed. Filtering the plugins was the easy part. If I change the Plugin API version - e.g. `const PLUGIN_API_VERSION = '1.9.9';` - on install/update, I'm getting errors like 
```
some/package dev-master requires composer-plugin-api 1.0.0 -> no matching package found.
```
And that's normal I guess, considering that Composer interprets `1.0.0` as _exactly_ that version. 

This is where I got stuck. Can we make the Solver think that non-platform `composer-plugin-api` package versions are to be interpreted as `^1.0` if the actual version is exactly `1.0.0`? Is this a good idea? Is it hard to implement? Can we internally use AliasPackages here? 

PS: Hopefully, fixing this will partially unblock https://github.com/composer/composer/pull/3377.

**Comment by Seldaek** [comment]
Regarding your solver question at the end, I think that'd require hijacking the require in ArrayLoader or such so that the ^1.0 require is an integral part of the in-memory package.

**Comment by nevvermind** [comment]
Thanks, @Seldaek. You pointed me in the right direction and now I have a working draft.

The problem is now testing. I want to be able to mock the Plugin API's version as well. It's not possible atm because of `\Composer\Plugin\PluginInterface::PLUGIN_API_VERSION`. Keeping it in a constant is the cleanest, but the least testable.  

So far, the constant is used in a) [the PluginManager](https://github.com/composer/composer/blob/45b1f356c24d87788a339f6a50d6d78bef464c47/src/Composer/Plugin/PluginManager.php#L132) and b) [the PlatformRepository](https://github.com/composer/composer/blob/fa398e14c78954319fb6c8ff19ef80129cc1fc85/src/Composer/Repository/PlatformRepository.php#L65-L66).

So I created [a new method in Config](https://github.com/composer/composer/pull/4089/files#diff-f875ecd8aa064838453235334aa52b2fR350) to get the Plugin API version - hoping that that's a reasonable place to put the getter. This was made purely for mocking abilities, nothing more.
