### ISSUE TITLE
config set command needs an output

### ISSUE THREAD

**Issue by magnetik** [composer/composer#4092]
I do some automated `composer config -g` using ansible, but since it doesn't have any output, I can say if the config have been changed or not. 

It would be useful to have an output like "Key <XX> changed" for instance.

**Comment by nevvermind** [comment]
You shoudln't rely on the _output_ the check if the command ran succesfully or not, but on the exit code instead.

**Comment by Seldaek** [comment]
Indeed if the exit code is 0 then the key has been set correctly.
