### ISSUE TITLE
Composer deletes regular files from bin on package removal

### ISSUE THREAD

**Issue by noccy80** [composer/composer#4094]
**Problem:**

If an executable is installed by composer as a symlink into `bin` as part of a library, and the library is later removed, the item matching the filename will be purged from `bin` without checking if it is a symlink or a regular file substituted after install.

**To replicate:**

1. add `phpunit/phpunit` to the `composer.json` of a Symfony project.
2. do `composer install` -- a symlink will be created as `bin/phpunit` to the phpunit executable.
3. unlink `bin/phpunit` and replace it with `phpunit.phar` renamed to `phpunit`.
4. remove `phpunit/phpunit` from your `composer.json`.
5. do `composer update` -- the regular file `bin/phpunit` will be deleted even if it is not the symlink that was created in step 2.

**Suggestion:**

A check if the item in `bin` is indeed a symlink before deleting/unlinking would be a good idea, as this could wipe any local modifications and/or potentially cause a lot of confusion.

**Comment by nevvermind** [comment]
##### Problem
Replace your original bin file. This will leave you open for inconsistencies between the executable and the lib its basing itself on.

##### Suggestion
Stop that. Wy do you do that anyway?

**Comment by stof** [comment]
The thing is that Composer does not always use symlinks to install bins. So checking whether the removed file is a symlink would actually break composer.

I send @nevvermind. you should not be replacing files managed by composer (just like you should not mess up with your vendor folder directly generally. If you install from dist, composer will not be able to warn you either)

**Comment by noccy80** [comment]
To clarify, this wasn't introduced by me but rather by pulling updates to a shared project. Someone upstream thought it was better to bundle the various tools, breaking pretty much everything until a hard reset was done. Also, this is re. files *no longer* being managed by composer.

Really, nothing should break by a check to make sure the file being unlinked is a symlink *on platforms where symlinks are supported*.

**Comment by alcohol** [comment]
You're asking for a fix to a scenario that should not happen? We can't help people being creative. It doesn't mean we have to provide solutions for everything though. Some situations just result in stuff breaking, cause they should.

**Comment by stof** [comment]
@noccy80 if you tell composer that it should put its managed bins in ``bin/``, you should not put other files in the same folder (and especially not with the same name).

And even on platforms where symlinks are supported, you can still ask Composer to avoid using symlinks on install.
