### ISSUE TITLE
Bug when using dev-* with a non-HEAD #ref fails to install when HEAD has different requirements

### ISSUE THREAD

**Issue by phindmarsh** [composer/composer#4099]
Sorry for the rubbish title, I couldn't think of a better way to describe the issue I'm experiencing.

I have a project with the following dependency `"silex/silex": "dev-master#279c773342c6c4d141ebd5236b18518c96505e00"`.

Just recently Silex was updated to require PHP 5.5.9, where we only run 5.4.29. Normally this wouldn't be a problem since we are using a pinned version of the Silex repository where that requirement has not been introduced yet. However, attempting to install/update with this version constraint now fails because the machine does not have 5.5.9 even though that pinned commit does not require it. I assume this is because composer is checking out the repository at `HEAD` and evaluating the PHP version (as 5.5.9) before checking out `279c773` (which is 5.3.9). This means a composer.json that was working can't be updated with new (even unrelated) packages because Silex can not be resolved correctly.

I've prepared a test composer.json that illustrates the issue, and the output of attempting to install using this file:

composer.json:
```json
{
    "name": "phindmarsh/composer-test",
    "description": "Testcase for checking dependencies bug",
    "require": {
        "silex/silex": "dev-master#279c773342c6c4d141ebd5236b18518c96505e00"
    },
    "authors": [
        {
            "name": "Patrick Hindmarsh",
            "email": "patrick@hindmar.sh"
        }
    ]
}
```
Output:
```
$ php -v
PHP 5.4.29 (cli) (built: Mar 29 2015 15:05:16) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.3.0, Copyright (c) 2002-2015, by Derick Rethans
$ composer --version
Composer version 1.0-dev (65dd1f7137abf80b08a1dac29379bf266a425474) 2015-06-02 13:47:52
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for silex/silex dev-master#279c773342c6c4d141ebd5236b18518c96505e00 -> satisfiable by silex/silex[dev-master].
    - silex/silex dev-master requires php >=5.5.9 -> your PHP version (5.4.29) does not satisfy that requirement.
```
[Verbose output of composer install](https://gist.github.com/phindmarsh/bad92fecec97c367cff5).

For now I've worked around this by specifying the package manually in the repositories section of the projects composer.json, but I would have expected this to work out of the box as is.

**Comment by alcohol** [comment]
Not a bug.

Related, #4082 - and see also this thread: [issues/3918#issuecomment-91204245](https://github.com/composer/composer/issues/3918#issuecomment-91204245)

**Comment by phindmarsh** [comment]
Ah right, makes sense now. Thanks for the explanation, its a hard thing to google for!

**Comment by alcohol** [comment]
Yeah I think we need to look into documenting this more properly. Maybe a common pitfalls page or something. There are some other "issues" that keep coming back.

**Comment by phindmarsh** [comment]
Yeah, I took a look through open issues and a quick scan of the closed ones but didn't see anything obvious.

**Comment by alcohol** [comment]
Yeah you kind of need to know what to look for.

**Comment by phindmarsh** [comment]
Perhaps link to somewhere from the [guidelines for contributing](https://github.com/composer/composer/blob/master/CONTRIBUTING.md) which shows up in the Github UI when making a new issue, I suspect that will catch most people. Even just a list of links to common issues as you suggested :smile:
