### ISSUE TITLE
Erroneous(?) proc_open() fork memory error (RAM not exhausted)

### ISSUE THREAD

**Issue by pioneerwebsites** [composer/composer#4102]
This is different to #945 in that the machine has 4gb RAM and 4gb swap. The free RAM is never exhausted, let alone the available/cached RAM, and the swap isn't touched!

```
# free -m
              total        used        free      shared  buff/cache   available
Mem:           3788         594        1757          54        1436        2887
Swap:          3967          19        3948
```
update --dry-run completes: 
`[203.2MB/138.93s] Memory usage: 203.23MB (peak: 482.12MB), time: 138.93s`

Here's the error with --profile (no dry-run)

```
[481.2MB/143.01s]   - Installing sybio/image-workshop (2.0.8)
[203.7MB/143.70s] The following exception is caused by a lack of memory and not having swap configured
[203.7MB/143.70s] Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details

Fatal error: Uncaught exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory' in phar:///home/username/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:974
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'proc_open(): fo...', 'phar:///home/sm...', 974, Array)
#1 phar:///home/username/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(974): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 phar:///home/username/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(784): Symfony\Component\Console\Application->getSttyColumns()
#3 phar:///home/username/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(745): Symfony\Component\Console\Application->getTerminalDimensions()
#4 phar:///home/username/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(675): Symfony\Component\Console\Application->getTerm in phar:///home/username/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php on line 974
```

The same project runs update no problems on our CentOS/CloudLinux 6.x machine with similar (smaller) specs. This machine is CentOS/CloudLinux 7.1.

**Comment by Seldaek** [comment]
I am not entirely sure but I think at the point where it forks it might require double the RAM it currently uses, so 481MB x 2 that's almost a gig, but indeed you seem to have enough free memory. Could be another system limit I don't know of like a CentOS protection against processes taking too much RAM? The bottom line though is that as usual you really should run install from a composer.lock file and not an update, so that it takes virtually zero memory.

**Comment by pioneerwebsites** [comment]
Thanks Seldaek!

I have tried all sorts of desperate attempts like removing shell fork protection, removing the user from the CloudLinux CageFS, creating a temporary swap file, running `# php -dmemory_limit=1G ../composer.phar update --no-scripts --prefer-dist`. 

Just now I've also tried disabling OOM (Linux out of memory killer) `sysctl vm.overcommit_memory=2`. Then I tried with PHP permanently reconfigured with 2G memory (although previous server 512M worked with same project). Same problem, same spot, FWIW, ` - Installing sybio/image-workshop (2.0.8)`.

I'm revisiting with the primary developer on why we can't install from the composer.lock file but my gut says it's not actually a memory issue - nothing else could be causing the memory error message to fire, incorrectly?

**Comment by nevvermind** [comment]
Try this in an empty folder:
- `strace -f -o composer_trace.wtf composer require sybio/image-workshop:2.0.8`
- `cat composer_trace.wtf | grep -n "stty`

Do you see interesting things in there? Also, what PHP version is that? I've seen people having problems with proc and updating PHP solved them.

**Comment by pioneerwebsites** [comment]
Thanks nevvermind. I was just compiling a response after further tests. But to answer your question:
PHP 5.5.25 (cli) (built: May 20 2015 16:34:40)
And thanks for the trace suggestion, will keep that up our sleeve.

Looks like it was a 'memory issue' - with CloudLinux limiting the user memory. 

Limit was set to 1G, as it was on the previous server, so even if it were a double 482M that's still not 1G, but there must be something to it, as when I raise it to 2G, composer updates.

The PHP memory limit is fine at 512mb.

Overall, I'm putting it down to each successive CentOS version using significantly more memory, on a per user/php level. I now recall noticing this when moving from 5 to 6 as well, but it's all a bit much really...
