### ISSUE TITLE
Repositories not honoring changes in composer.json

### ISSUE THREAD

**Issue by JoelLarson** [composer/composer#4104]
```
{
    "name": "vagrant/test-project",
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "positivezero/google-api-php-client",
                "version": "0.6.7",
                "source": {
                    "url": "https://github.com/positivezero/google-api-php-client.git",
                    "type": "git",
                    "reference": "v0.6.7"
                },
                "autoload": {
                    "classmap": [
                        "src/Google_Client.php"
                    ]
                }
            }
        }
    ],
    "require": {
        "positivezero/google-api-php-client": "0.6.7"
    }
```

Whenever a change is made to the classmap autoload, it does not actually propagate through the composer autoloader.

```
"classmap": [
    "src/Google_Client.php",
    "src/contrib/Google_DriveService.php"
]
```

It will just treat it like there were no changes in `composer.json` even when running a `composer update`. The only way it will acknowledge them is by deleting the `composer.lock` file, the `vendor` directory, and then doing a `composer install`.

Is this intended functionality?

**Comment by stof** [comment]
If you don't bump the version of your package, Composer will not consider it needs to update the package, and so the installed package will stay the old one (with the old autoload config).
This is one of the reason making the ``package`` repository a huge pain to handle (I try to avoid it at all cost, considering a very last resort).

Given that https://github.com/positivezero/google-api-php-client contains a composer.json file, you should use the ``vcs`` type instead, to read the composer metadata from the repo (or use packagist if the package is registered on it)
