### ISSUE TITLE
[Feature request]install global tools in isolation from each other

### ISSUE THREAD

**Issue by greg0ire** [composer/composer#4110]
As @lyrixx pointed out [here](https://github.com/FriendsOfPHP/Sismo/issues/120#issuecomment-63335460) some time ago, installing dev tools like phpmd, phpcs, or sismo globally is not so great because it ties together packages that could have different versions of their common dependencies… the more tools you install globally, the this problem can arise…

I don't think you can tell `create-project` to symlink binaries in, for instance, `$HOME/bin` like you can with `global`.

I think a `bin-dir` option to `create-project` would be great.

**Comment by alcohol** [comment]
I don't see how create project relates to this?

Create project is for when you want to download and install some dependencies upon which you will continue to build a project.

You're simply talking about installing packages such as phpunit or phpcs, in a global manner. That doesn't require a create project call.

Instead, consider the following:

```
$ cat /opt/composer/composer.json
{
    "require": {
        "phpunit/phpunit": "@stable",
        "phpmd/phpmd": "@stable",
        ...etc...
    },
    "config": {
        "bin-dir": "/usr/local/bin"
    }
}
```

Alternatively, if you want to split them up cause of fear that common dependencies will conflict:

```
$ cat /opt/phpunit/composer.json
{
    "require": {
        "phpunit/phpunit": "@stable"
    },
    "config": {
        "bin-dir": "/usr/local/bin"
    }
}
```

```
$ cat /opt/phpunit/composer.json
{
    "require": {
        "phpmd/phpmd": "@stable"
    },
    "config": {
        "bin-dir": "/usr/local/bin"
    }
}
```

etc...

**Comment by greg0ire** [comment]
> if you want to split them up cause of fear that common dependencies will conflict

That is the point of this issue : conflicts and also preventing the installation of a recent version of one of the dependencies because another dependency requires an older version of a common dependency.

I have considered your method, it is a good workaround but I really feel there should be a better way that would allow the installation to be easier, like an option or maybe an environment variable. Here, you need to do many two things before actually calling composer : 

- deciding where you are going to install the tool (here, in `/opt`)
- create the directory, and in your case, deal with permissions in the process (but you could have chosen to install this in your `home`)
- create a `composer.json`, always with the same `config` option

A bit tedious isn't it ?

**Comment by alcohol** [comment]
It's only tedious because your use case requires it. For me, a single composer.json has always been sufficient. We can't make every scenario in the world be as easy as the next one.

**Comment by alcohol** [comment]
Adding a `bin-dir` option to `create-project` certainly doesn't change things though.

**Comment by greg0ire** [comment]
Another solution would be to have a `composer_global.json` listing tools to install in `~/.composer`, in separate projects, and leave `create-project` alone.

**Comment by greg0ire** [comment]
> Adding a bin-dir option to create-project certainly doesn't change things though.

I feel this is not the best solution indeed, maybe the way `global` behaves should be changed ?

**Comment by alcohol** [comment]
I don't think so. As it is right now, your best approach really is my second example (a `composer.json` per binary package that you want to install stand-alone). This treats them exactly as you want, at the added cost of more configuration/management on your end. It's simply a trade-off you will have to make.

**Comment by greg0ire** [comment]
> As it is right now, your best approach really is my second example (a composer.json per binary package that you want to install stand-alone).

I think that is true, but it is so costly that I'm sticking with a single, global, `composer.json`.

> This treats them exactly as you want, at the added cost of more configuration/management on your end. It's simply a trade-off you will have to make.

I beg to disagree because lazyness, but feel free to close this if you think this is out of the scope of Composer.

**Comment by alcohol** [comment]
Like I said, a trade-off. Can't have both. This is indeed out of the scope of composer.

**Comment by alcohol** [comment]
Many tools that can be installed globally now a days offer a Phar binary by the way. Look at phpunit, php-cs-fixer, etc. Simply download those directly to /usr/local/bin (or some other global `PATH` directory) and you're set.

**Comment by greg0ire** [comment]
Guess I'll do that. Thanks!
