### ISSUE TITLE
ssl

### ISSUE THREAD

**Issue by romeox6x66** [composer/composer#4116]
Fatal error: Uncaught exception 'GuzzleHttp\Ring\Exception\RingException' with message 'cURL error 1: Protocol "https" not supported or disabled in libcurl' in /home/gdbtc/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php:126 Stack trace: #0 /home/gdbtc/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php(90): GuzzleHttp\Ring\Client\CurlFactory::createErrorResponse(Object(GuzzleHttp\Ring\Client\CurlHandler), Array, Array) #1 /home/gdbtc/vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php(78): GuzzleHttp\Ring\Client\CurlFactory::createResponse(Object(GuzzleHttp\Ring\Client\CurlHandler), Array, Array, Array, Resource id #89) #2 /home/gdbtc/vendor/guzzlehttp/ringphp/src/Client/Middleware.php(54): GuzzleHttp\Ring\Client\CurlHandler->__invoke(Array) #3 /home/gdbtc/vendor/guzzlehttp/ringphp/src/Client/Middleware.php(30): GuzzleHttp\Ring\Client\Middleware::GuzzleHttp\Ring\Client\{closure}(Array) #4 /home/gdbtc/vendor/guzzlehttp/guzzle/src/RequestFsm.php(129): GuzzleHttp\Ring\Client\Middleware::GuzzleHttp\Ring\Client\{closure in /home/gdbtc/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 51

please help

**Comment by jakoch** [comment]
Your question is in the wrong place. Ask over at [Guzzle](https://github.com/guzzle/guzzle/issues/new) or [StackOverflow](http://stackoverflow.com/questions/ask?tags=php,guzzle) and close this ticket. Thanks
