### ISSUE TITLE
PEAR's @package-name@ is not resolved

### ISSUE THREAD

**Issue by alecpl** [composer/composer#4119]
See http://pear.php.net/bugs/bug.php?id=20527

**Comment by alcohol** [comment]
These seem to be the default placeholders that get replaced: [PearInstaller.php#L64-L72](https://github.com/composer/composer/blob/e0ce559838e0cd7a01404b4b85d2a2768d0ec1e9/src/Composer/Installer/PearInstaller.php#L64-L72).

Looking at the issue, the path specified in [PinEntry.php#L320-L321](https://github.com/pear/Crypt_GPG/blob/3f24905839720b2f433f241289b3d03210b2a74e/Crypt/GPG/PinEntry.php#L320-L321) is not going to work even if Composer would replace `@package_name@`, as `@data_dir@` already covers the full path to `/data` (appending `@package_name@` and an additional `/data` would result in a path that does not exist).

Looks to me like Crypt_GPG needs to fix their `package.php`/`package.xml` configuration.

**Comment by alcohol** [comment]
That package hasn't been worked in well over a year however, so I wouldn't expect them to fix it any time soon.

**Comment by alecpl** [comment]
Hmm... indeed the path will be .../Crypt_GPG/data/Crypt_GPG/data and this directory exists, but I suppose you're right that maybe Crypt_GPG package.xml file is invalid (and the code to set the path should not use @package-name@ at all). Thanks, I'll point on this in the PEAR bugtracker.

Anyway, I think the request to resolve @package-name@ is still valid.

**Comment by alecpl** [comment]
I'm not sure it's the package.xml issue. I found another package which /data directory is installed in the same fashion, i.e. vendor/.../Console_CommandLine/data/Console_CommandLine/data. Maybe related https://github.com/composer/composer/issues/1402

**Comment by alcohol** [comment]
Please, PEAR, why are you doing this to us. Go die already.

![pitchforks](https://bigeastmeadow.files.wordpress.com/2013/04/simpsons-angry-villagers.jpg)

**Comment by alcohol** [comment]
On a more serious note, the way the PEAR installer (read: actual PEAR installer, not the Composer counter-part) shuffles directories around seems inconsistent or arbitrary. Do you know if there is any documentation that actually explains how PEAR package directory structures are managed?

**Comment by alcohol** [comment]
It looks to me almost as if Composer would be better of not replacing `@data_dir@`, as most PEAR packages have a fallback (e.g. [CookieJar.php#L435-L445](https://github.com/pear/HTTP_Request2/blob/trunk/HTTP/Request2/CookieJar.php#L435-L445) in HTTP_Request2 and [PinEntry.php#L325-L328](https://github.com/pear/Crypt_GPG/blob/master/Crypt/GPG/PinEntry.php#L325-L328) in Crypt_GPG) where they see themselves as being installed from vcs (which is what Composer does basically I think?).

/cc @Seldaek you probably know more about PEAR than me though.

**Comment by Seldaek** [comment]
Maybe we should skip the data_dir replace, I am not sure what that means though, I also don't know a whole lot about the PEAR stuff. All I know is the less I need to touch it the better. I kinda wish those old PEAR packages would juts be brought up to speed and drop all the `@pear_thingies@` as it is less and less relevant.

**Comment by Seldaek** [comment]
Closing as PEAR things likely won't ever be fixed.
