### ISSUE TITLE
Updated URLs in the lock file should already point to the right commit

### ISSUE THREAD

**Issue by stof** [composer/composer#4126]
Since https://github.com/composer/composer/commit/d426246b8000c503ad047186eb7fb5315bcf9771 (and the previous PR), dist URLs are updated for github packages to account for repo renamings, relying on the fact that the downloader will update the URL based on the reference being locked.
This causes unnecessary updates of the lock file (and WTFs for people not knowing that the downloader will change the URL later). It would be much better to generate the right URL here directly before updating the lock file, leaving the lock file in a consistent state.

Btw, the same rewriting logic could be applied for URLs corresponding to a Github Enterprise setup (the ``github-domains`` config param) as we are also able to update the commit ref in the URL. And we should check whether bitbucket (and Gitlab later once we integrate it) also have URLs with the commit ref in them directly.

**Comment by wimvds** [comment]
Bitbucket seems to have support for commit refs in the urls : ```https://bitbucket.org/{user}/{repo}/get/{tag or branch or commit ref}.zip``` seems to work for me.

**Comment by renan** [comment]
Yes please!

The current behavior is very un-intuitive. It makes you think that when using `--prefer-dist` it will install the version as described in the `"url"` and not the one in `"reference"`.

Perhaps updating the url to not include the hash but maybe a placeholder would a simple way of solving it?
