### ISSUE TITLE
Dot in branch name seems to break dev-branchname version constraint

### ISSUE THREAD

**Issue by DominikTo** [composer/composer#4127]
Composer can't install a dependency in a "version number" branch (e.g a branch with the name `1.0`) using `dev-1.0` as the version constraint.

Trying a `composer install` (Running Composer version 1.0-dev (4f80e7ff68466cab970c22b425725b8058c32970) 2015-06-09 00:03:48) with the following `composer.json` reproduces the problem:

```
{
    "require": {
        "dominik/composer-test": "dev-1.0 as 1.5"
    },
    "repositories": [
        {"type":"vcs", "url":"https://github.com/DominikTo/composer-test"}
    ],
    "minimum-stability": "dev"
}
```

Requiring e.g. the `feature` branch works fine though:

```
{
    "require": {
        "dominik/composer-test": "dev-feature as 1.5"
    },
    "repositories": [
        {"type":"vcs", "url":"https://github.com/DominikTo/composer-test"}
    ],
    "minimum-stability": "dev"
}
```

So the problem seems to be with version number branches. Maybe composer interprets them as a tag?

**Comment by nevvermind** [comment]
Run `composer show dominik/composer-test` in your folder. You'll see something like `versions : dev-master, 1.0.x-dev, dev-feature`. Those are the valid versions Composer found for your repo.

From the [docs](https://getcomposer.org/doc/articles/aliases.md): 
> If you alias a non-comparable version (such as dev-develop) dev- must prefix the branch name. You may also alias a comparable version (i.e. start with numbers, and end with **.x-dev**),

**Comment by DominikTo** [comment]
Thanks, that helps! Closing this one. Not a bug. :-)
