### ISSUE TITLE
POST_PACKAGE_UPDATE event does not fire, when calling `composer update --dry-run`.

### ISSUE THREAD

**Issue by kewlar** [composer/composer#4128]
It would be nice to be able to get PackageEvents even when running Composer with --dry-run option. For example, it could be used to augment `composer update --dry-run` output to solve #1261 with a plugin or a script, without cluttering Composer's code needlessly.

I'm pretty sure Composer does not fire these events on --dry-run mode on purpose, and enabling it may break some of the existing scripts... but then again, I don't think it would do much harm.

Or are there serious reasons against having PackageEvents fire on --dry-run mode?

**Comment by slbmeh** [comment]
The definition of dry run is a rehearsal.  I think it would be confusing to do an action on a flag that traditionally does nothing.

**Comment by kewlar** [comment]
Yes, it's a rehearsal, and I agree that a command under --dry-run should not apply any changes to a project files, but it's slightly misleading to say the command does nothing at all. The `composer update --dry-run` outputs a list of changes to be applied, so it's also performs a diagnostic function. It already downloads files and performs dependency resolving -- why not allow plugins to augment it, to be able to output more useful information, if needed? The plugin could (should, in this case) check for --dry-run option itself -- for example, via CommandEvent.

My question now is, could Composer allow PackageEvents on --dry-run (and leave the dry-mode checking, and allowing/preventing changes, to the plugins/scripts), or it should absolutely not be done, because it could break some projects?

**Comment by stof** [comment]
it performs dependency resolution, but it does not download the new code. ``POST_PACKAGE_UPDATE`` is triggered after downloading the new code of the package, so there is no reason to trigger it in dry-run mode as the package never gets updated

**Comment by kewlar** [comment]
It does not download code, even though does download package definitions -- the provider*.json files -- but that's nitpicking.

I get it that the package never gets actually updated. Still, would there be no benefit in having the event there?

**Comment by stof** [comment]
well, why would you trigger an event after the update of the package if you don't perform the update of the package ?

**Comment by kewlar** [comment]
In short, to be able to output a changelog, or a link to changelog, or release notes for the packages that could be updated. I.e., instead of just:

  - Updating symfony/symfony (v2.5.6) to symfony/symfony (v2.5.7)

I could get, for example:

  - Updating symfony/symfony (v2.5.6) to symfony/symfony (v2.5.7)
    - CHANGELOG: https://github.com/symfony/symfony/compare/v2.5.6...v2.5.7

That would be useful in a sense that would save time for me, the programmer, to find out what's changed in the package and decide if it should be updated, or it should be avoided (in ideal world the packages don't break functionality, and the project should be covered by tests, but that option is not always there, and that's a different question).

Also, there are things like #1261, that could be also attempted to solve with a plugin on this event.

**Comment by Seldaek** [comment]
I think it's a pretty dangerous idea because post-update handlers typically would expect that the source of the package is there to be modified or whatever crazy things people do in script handlers :)

**Comment by kewlar** [comment]
I was hoping it might work, but, oh, well. Thanks for explaining it :)
