### ISSUE TITLE
Class is not autoloadable - Full example

### ISSUE THREAD

**Issue by r34ch** [composer/composer#4135]
Trying to understand how composer uses name-spacing and auto-loading to execute scripts. The documentation is pretty good until scripts and autoloading...

Anyone have a link to a git repository which has a composer.json in the project root that uses (post install or such) scripts (and follows PSR-0 standards)?

The vendor repos I have found explain that once included, to add a scripts section to the composer.json (which one?). However, these vendor repos themselves include a composer.json with the exact scripts they are mentioning already included.

If I do a composer update/install, they are not triggered. If I add them to my projects composer.json, I get nothing but "Class is not autoloadable" errors. I have lost days to this.

**Comment by alcohol** [comment]
See the Symfony standard edition for a good example: [composer.json#L25-L47](https://github.com/symfony/symfony-standard/blob/2.8/composer.json#L25-L47)

**Comment by r34ch** [comment]
Thank you for your patience.

The 'vendor' composer.json seems to work fine if I clone it as a separate project and run composer install / update. The script executes fine. It's just when I use it as a vendor package and try the same in the root composer. I think it is the 'autoload' line in the root folder.

Structure
```
├── composer.json    <- root
├── composer.lock
├── README.md
├── vendor
│   ├── autoload.php
│   ├── composer
│   │   ├── autoload_classmap.php

...

│   └── companyname
│       └── wp-deploy-script
│           ├── composer.json  <- vendor
│           ├── README.md
│           └── src
│               └── Companyname
│                   └── Deploy
│                       └── Installer.php
├── wp-config.php
└── wp-content
    └── plugins
```


Installer.php
```
<?php
namespace Companyname\Deploy;

class Installer {

	public static function postInstall() {
		echo "\n\n\ntest script loaded...\n\n\n";
	}
```

Vendor composer.json
```
{
  "name": "testname",
  "description": "testdesc",
  "type": "composer-plugin",
  "license": "GPL-2.0+",
  "minimum-stability": "dev",
  ],
  "autoload": {
    "psr-0": {
      "Companyname\\Deploy\\": "src/"
    }
  },
  "scripts": {
    "pre-install-cmd": [
      "Companyname\\Deploy\\Installer::preInstall"
    ],
    "post-install-cmd": [
      "Companyname\\Deploy\\Installer::postInstall"
    ]
  }
}
```

Root composer.json
```
{
  "repositories": [
    {
      "type": "composer",
      "url": "http://wpackagist.org"
    },
    {
      "type": "package",
      "package": {
        "name": "companyname/wp-deploy-script",
        "version": "dev-master",
        "type": "package",
        "source": {
            "url": "git@bitbucket.org:companyname/wp-deploy-script.git",
            "type": "git",
            "reference": "master"
        }
      }
    }
  ],
  "require": {
    "php": ">=5.3.2",
    "composer/installers": "~1.0.21",
    "companyname/wp-deploy-script":"dev-master"
  },
  "extra": {
    "installer-paths": {
      "wp-content/mu-plugins/{$name}/": ["type:wordpress-muplugin"],
      "wp-content/plugins/{$name}/": ["type:wordpress-plugin"],
      "wp-content/themes/{$name}/": ["type:wordpress-theme"]
    }
  },
  "autoload": {
    "psr-0": { "": "src/" }
  },
  "scripts": {
    "pre-install-cmd": [
      "Companyname\\Deploy\\Installer::preInstall"
    ],
    "post-install-cmd": [
      "Companyname\\Deploy\\Installer::postInstall"
    ]
  }
}
```

**Comment by stof** [comment]
The issue is that ``pre-install-cmd`` runs before the install command, so the vendors are not yet available (they have not been downloaded yet). Anything in ``pre-install-cmd`` or ``pre-update-cmd`` needs to live in the root package to be available at the time the script is used.

**Comment by r34ch** [comment]
Ignore the pre-install-cmd in that case as it fails on the post-install-cmd as well.

**Comment by r34ch** [comment]
Thanks to Seldaek on IRC who found the main issue. The vendor repository needed to be pulled in as a 'vcs' rather than a package. The vendor composer.json needed its type removed and the class added in extras. All works perfectly now. 

Root composer.json
```
{
  "repositories": [
    ...
    {
      "type": "vcs",
       "url": "git@bitbucket.org:companyname/wp-deploy-script.git",
    }
  ],
   ...
```

vendor composer.json
```
...
 "extra": {
    "class": "Companyname\\Deploy\\Installer"
  }

```
