### ISSUE TITLE
Classmaps generated with -o don't consistently include files from autoload-dev

### ISSUE THREAD

**Issue by elazar** [composer/composer#4138]
According to the Options sections of the docs for the [`dump-autoload`](https://getcomposer.org/doc/03-cli.md#dump-autoload), [`install`](https://getcomposer.org/doc/03-cli.md#install), and [`update`](https://getcomposer.org/doc/03-cli.md#update) Composer CLI commands, their `-o` flag should "convert PSR-0/4 autoloading to classmap."

However, it appears that classes referenced in [`autoload-dev`](https://getcomposer.org/doc/04-schema.md#autoload-dev) aren't consistently included in this classmap, even if `--no-dev` is not specified.

[This gist](https://gist.github.com/elazar/29d42163cbbb116ca3b8) contains an example where code from `autoload-dev` (specifically `Dev\Foo` as defined in `dev/Foo.php` per the PSR-4 autoloader configured in `autoload-dev`) _does_ appear to be included in the classmap.

[This repo](https://github.com/elazar/phantestic) is an example where code from `autoload-dev` (specifically classes under `Phantestic\Tests` as defined within the `tests` directory per the PSR-4 autoloader configured in `autoload-dev`) _does not_ appear to be included in the classmap, but does contain classes from the `evenement/evenement` dependency and from the PSR-4 autoloader defined in `autoload`.

From a related discussion with @Seldaek:

```
I think it just was omitted when we added autoload-dev. shouldn't be too hard tbh.
down the line it's just something in AutoloadGenerator somewhere. if you search
for psr in that file you should stumble upon it.
```

**Comment by stof** [comment]
The optimized autoloader does not include classes with a name containing ``Test``, to avoid adding all test files in the classmap making it much bigger (many libraries have test classes in a location when it is autoloaded by the main autoloading rule too). this is why ``Phantestic\Tests`` classes are omitted

**Comment by elazar** [comment]
@spof Can you cite what code is responsible for this? I was curious if that was the case as well and did a cursory search of the repo, but the only thing I turned up was where [`Composer\Compiler` excludes tests from `composer.phar`](https://github.com/composer/composer/blob/69210d5bc130f8cc9f96f99582a041254d7b9833/src/Composer/Compiler.php#L112-113). Also, assuming this is in fact the current behavior, is there a way to override it?

**Comment by Seldaek** [comment]
This is the responsible code, and while the whitelist needs to stay because we only want to include classes matching the given namespace prefix, the test ones probably shouldn't be excluded anymore.. https://github.com/composer/composer/blob/master/src/Composer/Autoload/AutoloadGenerator.php#L185-189

**Comment by legoktm** [comment]
So, is there a way for packages using the PSR-4 autoloader to exclude their test files from being added to the autoloader?

**Comment by elazar** [comment]
Put the test in a separate namespace under autoload-dev and specify the
--no-dev flag when issuing the composer command to generate your autoloader.
