### ISSUE TITLE
zip archivers without empty folders?

### ISSUE THREAD

**Issue by legendhb** [composer/composer#4149]
eg.
the structure of my project was 
frontend/
--controllers/
----MyController.php
--models/
--views/
----tpl.php
as shown above,directory "frontend/models" was an empty folder.
when i  archived this project to a "zip", and i found that "frontend/models" was missing in the archiver.
according to the source, this may caused by line 88,"return !$this->getInnerIterator()->current()->isDir();" in class "ArchivableFilesFinder" ?

i wonder if any suggestions about this problem?

sorry about my English.^_^

**Comment by slbmeh** [comment]
I believe the name implies that the intent is to find files and not directories. Placing a file in the directory would keep it for you.  For instance an empty `.keep` file.

**Comment by legendhb** [comment]
@slbmeh 
I see, just like an .gitkeep file, thx.
Maybe method "Phar::addEmptyDir()" should be another way, thought I havn't had a try.

**Comment by Seldaek** [comment]
Closing in favor of #4865 which has more info and discussion about this.
