### ISSUE TITLE
Local override of project defined source repositories

### ISSUE THREAD

**Issue by rrajkomar** [composer/composer#4152]
From the composer documentation : 
"You may put a config.json file into the location which COMPOSER_HOME points to. Composer will merge this configuration with your project's composer.json when you run the install and update commands.

This file allows you to set configuration and repositories for the user's projects.

In case global configuration matches local configuration, the local configuration in the project's composer.json always wins."

Why is the chosen behaviour set like this? Usually you'll want to locally override the source for a package used in a project (for example when applying local changes that are not ready yet to be pushed to a remote repository), so the local config.json should taken precedence over the project composer.json file.

For example : I have a library A used in a project B. In the composer.json file for project B,  the source for library A is set to a remote git repository. When I'm making changes to my local library A, I want them to be seen on local project B immediately, I should then be able to use the config.json file to override the setting in the composer.json for project B to use the local repository for library A instead of the remote one.

**Comment by rrajkomar** [comment]
P.S. : Is there no way to use a locally SVN checked out project as a dependency ? Using an absolute path or a relative one does not seem to work.

**Comment by alcohol** [comment]
I'm sorry but your comment makes no sense.

> Why is the chosen behaviour set like this? Usually you'll want to locally override the source for a package used in a project (for example when applying local changes that are not ready yet to be pushed to a remote repository), so the local config.json should taken precedence over the project composer.json file.

The project composer.json is **local**. Your $COMPOSER_HOME/config.json is **global**. There is no **local** config.json, only composer.json.

**Comment by rrajkomar** [comment]
Sorry if it wasn't clear, what I meant is :
The composer.json is indeed in your project and therefore commited with it >> It is shared between developers.
The config.json file is unique for each developer.

So my question is why not use the reverse behaviour (compared to the current one) : allow developers to override the shared composer.json defined repositories with a "local" one (/personal) using config.json allowing in that manners developers to use their changes immediately without having to commit their changes before being able to do so.

**Comment by nevvermind** [comment]
I'm guessing because the term "global" refers to multiple _local_ projects which use `composer.json`, instead of multiple distributed `composer.json`'s of the same project.

But yeah, I guess this is like `.gitignore` (distributed) vs `.git/info/exclude` (local).

**Comment by Seldaek** [comment]
The reason it is like that mainly made sense for config settings I guess, because you can have defaults set per machine in the global config.json but still have some more specific overrides in every compoesr.json per-project. For repos it's the same IMO, you might have global repos but down the line every project should still retain some control over what is being installed or your global settings might just have too many weird side effects.

I get what you are trying to do though, and yes for that particular use case the other way would make more sense, but IMO it's best achieved with something more explicit and less painful to setup than global repositories, like #601 which I am sure we will finally get to at some point :)

**Comment by thursdaybw** [comment]
Hey 2015, This is me from 2023 and looks like we have a solution for this these days: https://github.com/wikimedia/composer-merge-plugin I'm checking it out now.
But this looks designed to do exactly what this issue requests
