### ISSUE TITLE
Segfault while generating optimized autoload files

### ISSUE THREAD

**Issue by sebastien-fauvel** [composer/composer#4153]
I'm using the latest composer (8e9659bd8317ad3f623c4d17940380443cf8772c) with PHP 5.6.8 under RHEL 6.6.

Running `composer install --no-dev -o` on this [composer.lock](https://gist.github.com/sebastien-fauvel/cfb813e82fc0cfa3f2e2) leads to a reproducible segmentation fault during the step `Generating optimized autoload files`.

It works fine with `composer install --no-dev`, though, and I couldn't reproduce the issue in a different environment (composer 1.0.0-alpha10 with PHP 5.4.42 under MacOS X Yosemite).

Here a link to the [composer.json](https://gist.github.com/sebastien-fauvel/284be9b012cff16dea22).

@Seldaek can you reproduce this issue? Do you have any idea about what could lead to a segfault during/after the optimization of the autoloader?

**Comment by nevvermind** [comment]
@sebastien-fauvel - could you use pastie.org for your composer.lock above. It's quite the file. Also, composer.json would be better.

Use `strace` or XDebug trace to find out where is stops.

**Comment by sebastien-fauvel** [comment]
It doesn't work on Pastie – `Your paste cannot be larger than 64 kb. Sorry.` – but I've created a gist: https://gist.github.com/sebastien-fauvel/cfb813e82fc0cfa3f2e2

**Comment by nevvermind** [comment]
I'm guessing you can't edit your first post?

**Comment by sebastien-fauvel** [comment]
The `strace` output is ending like this:
```
lstat("/var/lib/openshift/537b33/app-root/runtime/repo/tests/FCTest/Smart/Controller/Mail/InboundControllerTest.php", {st_mode=S_IFREG|0600, st_size=795127, ...}) = 0
lstat("/var/lib/openshift/537b33/app-root/runtime/repo/tests/FCTest/Smart/Controller/Mail", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
lstat("/var/lib/openshift/537b33/app-root/runtime/repo/tests/FCTest/Smart/Controller", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
lstat("/var/lib/openshift/537b33/app-root/runtime/repo/tests/FCTest/Smart", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
lstat("/var/lib/openshift/537b33/app-root/runtime/repo/tests/FCTest", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
lstat("/var/lib/openshift/537b33/app-root/runtime/repo/tests", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
gettimeofday({1434444856, 846333}, NULL) = 0
gettimeofday({1434444856, 846467}, NULL) = 0
lstat("/var/lib/openshift/537b33/app-root/runtime/repo/tests/FCTest/Smart/Controller/Mail/InboundControllerTest.php", {st_mode=S_IFREG|0600, st_size=795127, ...}) = 0
lstat("/var/lib/openshift/537b33/app-root/runtime/repo/tests/FCTest/Smart/Controller/Mail", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
lstat("/var/lib/openshift/537b33/app-root/runtime/repo/tests/FCTest/Smart/Controller", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
lstat("/var/lib/openshift/537b33/app-root/runtime/repo/tests/FCTest/Smart", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
lstat("/var/lib/openshift/537b33/app-root/runtime/repo/tests/FCTest", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
lstat("/var/lib/openshift/537b33/app-root/runtime/repo/tests", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
open("/var/lib/openshift/537b33/app-root/runtime/repo/tests/FCTest/Smart/Controller/Mail/InboundControllerTest.php", O_RDONLY) = 12
fstat(12, {st_mode=S_IFREG|0600, st_size=795127, ...}) = 0
fstat(12, {st_mode=S_IFREG|0600, st_size=795127, ...}) = 0
fstat(12, {st_mode=S_IFREG|0600, st_size=795127, ...}) = 0
mmap(NULL, 795127, PROT_READ, MAP_SHARED, 12, 0) = 0x7f2bb80e7000
mmap(NULL, 1052672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2bb7fe6000
munmap(0x7f2bb80e7000, 795127)          = 0
close(12)                               = 0
mmap(NULL, 1052672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2bb7ee5000
munmap(0x7f2bb7fe6000, 1052672)         = 0
brk(0x357d000)                          = 0x357d000
mmap(NULL, 1839104, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2bb7fe9000
munmap(0x7f2bb7ee5000, 1052672)         = 0
mmap(NULL, 1839104, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2bb7e28000
--- SIGSEGV (Segmentation fault) @ 0 (0) ---
--- SIGSEGV (Segmentation fault) @ 0 (0) ---
+++ killed by SIGSEGV +++
Segmentation fault
```

**Comment by nevvermind** [comment]
Yeah, that's not telling me too much. What about an xdebug trace?

**Comment by sebastien-fauvel** [comment]
Small note: The problem occurs as a test file is being parsed, which has been introduced in 8e9659bd8317ad3f623c4d17940380443cf8772c if I understand correctly.

**Comment by sebastien-fauvel** [comment]
This file contains a very long line (700 KB), maybe this is the problem?

**Comment by nevvermind** [comment]
Do you mean that, if you take that file out, or use a Composer version before that commit, it doesn't segfault? Not sure how a long line would influence things (except maybe memory).

**Comment by Seldaek** [comment]
@sebastien-fauvel could you share that long file? It sounds like it's a regex issue in the ClassMapGenerator so it'd definitely help if I can try and reproduce it so I can hope to work on a fix.

**Comment by sebastien-fauvel** [comment]
Here you go: https://gist.github.com/sebastien-fauvel/e335fc7946dedaccc481

It should be encoded with UTF-8.

**Comment by sebastien-fauvel** [comment]
Yep, it could be `preg_replace('{"[^"\\\\]*(\\\\.[^"\\\\]*)*"|\'[^\'\\\\]*(\\\\.[^\'\\\\]*)*\'}s', 'null', $contents)` that is causing a segfault on such big strings. Maybe you could optimize it using [possessive quantifiers](http://www.regular-expressions.info/possessive.html)?

**Comment by sebastien-fauvel** [comment]
I've solved the problem (for my part) by moving these long strings to separate json files, that are not being parsed by composer.

Still I would suggest:
- To use possessive quantifiers to replace strings in a memory effective way: `preg_replace('{"[^"\\\\]*+(\\\\.[^"\\\\]*+)*+"|\'[^\'\\\\]*+(\\\\.[^\'\\\\]*+)*+\'}s', 'null', $contents)`
- Not to include test files in the optimized autoloader when the `--no-dev` option is being used

**Comment by Seldaek** [comment]
Yeah I got the fix already here together with a test that used to segfault using your file, but I am checking if I can add more possessive quantifiers in other places to make it a bit faster. I'll push that in a bit. Thanks for the details.

As for not including test files in optimized autoloader, you should move your tests autoloading to autoload-dev that way they're excluded in --no-dev. Excluding with a pattern like we used to do isn't great I think because it might not match everything and might have false positives.

**Comment by sebastien-fauvel** [comment]
`autoload-dev` definitely makes sense, thank you! It's not going to work with the old versions of Zend Framework 2.3.9 and of Symfony 2.7.1 I'm using, though... but ok!

**Comment by Seldaek** [comment]
Yeah those dependencies having tests mixed in within the src/ folder are a problem, but I don't really see how we can fix them right now. For others though, autoload-dev stuff of your dependencies are never included in your classmap.

**Comment by sebastien-fauvel** [comment]
In my case only 7% of the autoloader is made up of test classes, so it's not critical imo. zf2 has already been using `autoload-dev` since the 2.4 release, and other frameworks will follow...
