### ISSUE TITLE
Composer scripts binary path

### ISSUE THREAD

**Issue by alexandernst** [composer/composer#4156]
Composer is trying to run

`php composer.phar run-script ...`

if there are any scripts, but this is not quite right. On Linux, one would (usually) install composer via a package manager, which means that the right thing to do is to run

`composer run-script ...`

**Comment by stof** [comment]
Where is composer trying to run ``php composer.phar run-script ...`` ?

**Comment by alexandernst** [comment]
Oops, sorry. This was actually my fault. Closing as this is invalid.
