### ISSUE TITLE
time out on OsX

### ISSUE THREAD

**Issue by Grazulex** [composer/composer#4157]
Hello,

From the last days, I have always a timeout when I try to use composer (self-update, update,...)
I'm under OsX 10.10.3.

```
[Composer\Downloader\TransportException]                                                                        
  The "https://getcomposer.org/version" file could not be downloaded: failed to open stream: Operation timed out 
```
Sometime, when I download again the caret.pem file (wget http://curl.haxx.se/ca/cacert.pem) I can used Composer but the day after, I have again a timeout...

I have try to install again Composer (curl -sS https://getcomposer.org/installer | php) but I have the same timeout...
```
All settings correct for using Composer
Downloading...
Download failed: file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Operation timed out
```

Can somebody help me ?

thank

**Comment by prochor666** [comment]
Same issue on Debian Wheezy x64, all updated, ispconfig3, using this [setup](https://www.howtoforge.com/perfect-server-debian-wheezy-apache2-bind-dovecot-ispconfig-3)

PHP 5.4.41-0+deb7u1 (cli) (built: May 22 2015 12:49:18)

**Comment by quentincurtet** [comment]
Same issue on Gnome 15.04

**Comment by oldtimeguitarguy** [comment]
Same here latest OSX

**Comment by joshreisner** [comment]
Same here latest OSX

**Comment by Grazulex** [comment]
I have reinstall my OS X but I have the same issue....
only solution : each time ofter used composer, paste a "clean" copy of composer.phar.

**Comment by gmarquet** [comment]
I had the same problem and i fixed it by disabling ipv6 on Ubuntu 14.04. Check the discussion #4142

**Comment by Grazulex** [comment]
Hello,

That 's the solution..I have disabling IPv6 and everything is ok now

**Comment by Seldaek** [comment]
If you experience timeouts that are solved by disabling IPv6, please run a `traceroute6 packagist.org`,  see where it gets stuck and try to talk to whoever's network is at fault, most likely it's your ISP. Disabling IPv6 is *not* a solution, fixing routing rules is.

**Comment by ilamp** [comment]
I have traced this back to IPv6 and using OpenDNS's DNS servers. Turning IPv6 off or using my ISP's DNS servers have fixed the issue.

**Comment by Grazulex** [comment]
on OsX traceroute6 packagist.org : 
connect: No route to host
is it normal ?

**Comment by ilamp** [comment]
@Grazulex No, that's not normal. Is it trying to content to IPv4? or IPv6 address? If it's IPv6 than try disabling IPv6 on your modem/router.

**Comment by Seldaek** [comment]
@Grazulex if you disabled ipv6 then traceroute6 is not gonna work that's to be expected.

@ilamp That is odd because opendns (the first one) seems to resolve correctly (second is default for comparison)

```
# dig AAAA packagist.org @208.67.222.222
packagist.org.          600      IN      AAAA    2001:41d0:a:7b19::

# dig AAAA packagist.org
packagist.org.          600     IN      AAAA    2001:41d0:a:7b19::
```

**Comment by mmucklo** [comment]
This problem showed up for me on an OS 10.10.4 machine.

I had to do this:

    networksetup -setv6off Ethernet

as a work-around...

(s/Ethernet/Wi-Fi/ or whatever your connection name is, mine was 'Ethernet')

**Comment by benmirkhah** [comment]
@mmucklo your advice worked, thanks. 
After using composer I switched IPv6's setting back to normal: networksetup -setv6automatic Wi-Fi

**Comment by ligerzero459** [comment]
Confirming that this is still an issue. Is there a fix planned, because this affects not only the install, but any downloads from packagist

**Comment by Seldaek** [comment]
It's not something we can fix. IPv6 routing is messed up in some networks and the only way to get it fixed is to **nag your network provider**.
