### ISSUE TITLE
Command composer licenses assumes version 1.0.0 if not defined

### ISSUE THREAD

**Issue by ravage84** [composer/composer#4158]
Composer version 1.0-dev (b2173d28fc8b56236eddc8aa10dcda61471633ec) 2015-06-16 10:43:55

Nitpicking here, but just wanted to report it.

Our project ``composer.json`` defines no version.
But when I execute ``composer licenses`` I get the following:

````
Name: vendor/project
Version: 1.0.0
Licenses: proprietary
Dependencies:

Name                                         Version  License
<snip for brevity>
````

Aparently if no version is set, it assumes version ``1.0.0``.
I would prefer if it would show ``no version defined`` or something like that.

Relevant line:
https://github.com/composer/composer/blob/1.0.0-alpha10/src/Composer/Command/LicensesCommand.php#L73

I couldn't find a test that this behavior is wanted or to be expected:
https://github.com/composer/composer/blob/1.0.0-alpha10/tests/Composer/Test/Package/Version/VersionParserTest.php#L31-L68

Thanks for your great work and keep it up!

**Comment by stof** [comment]
All composer packages need to have a version, including the root package (necessary in case of circular references). the logic to determine the root package version is available here: https://github.com/composer/composer/blob/74e7c5fe22dc456336a2b20c7b12a9a83fc4af09/src/Composer/Package/Loader/RootPackageLoader.php#L53-66

**Comment by ravage84** [comment]
OK, fine and thanks for enlighten me :cool: 
Nonethless, the statement printed is wrong for me.
How about printing ``No version defined, 1.0.0 assumed``?

**Comment by stof** [comment]
Well, the thing is that the LicensesCommand is right: the root package version is 1.0.0 as far as it is concerned.

**Comment by ravage84** [comment]
There are two views on this:
Composer's point of view and the user's point of view.

You are right, as far as it concerns for Composer, 1.0.0 might be correct.
But not for me as a user.

I was somewhat confues and thus this issue.

If Composer would be *sligthly* more verbose, as proposed, there would be no or at least less confusion.

**Comment by stof** [comment]
but there is no way for the command to know it should display this more verbose info, except by reading the composer.json file again manually
