### ISSUE TITLE
add a class map fallback strategy

### ISSUE THREAD

**Issue by llaville** [composer/composer#4159]
To explain the need and have a good understand of why compose should have a class map fallback strategy, is with an example.

In one of my project, I've added in my local composer install a (optional) dependency to 
[bartlett/monolog-growlhandler](https://github.com/llaville/monolog-growlhandler) that depends of PEAR/Net_Growl package.

When I run local instance, I've got no problem because when the optional resource is asked, composer load the Net_Growl_* classes with the class map rules.

```php
<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Net_Growl' => $vendorDir . '/pear-pear.php.net/Net_Growl/Net/Growl.php',
    'Net_Growl_Application' => $vendorDir . '/pear-pear.php.net/Net_Growl/Net/Growl/Application.php',
    'Net_Growl_Exception' => $vendorDir . '/pear-pear.php.net/Net_Growl/Net/Growl/Exception.php',
    'Net_Growl_Gntp' => $vendorDir . '/pear-pear.php.net/Net_Growl/Net/Growl/Gntp.php',
    'Net_Growl_GntpMock' => $vendorDir . '/pear-pear.php.net/Net_Growl/Net/Growl/GntpMock.php',
    'Net_Growl_Icon' => $vendorDir . '/pear-pear.php.net/Net_Growl/Net/Growl/Icon.php',
    'Net_Growl_Response' => $vendorDir . '/pear-pear.php.net/Net_Growl/Net/Growl/Response.php',
    'Net_Growl_Udp' => $vendorDir . '/pear-pear.php.net/Net_Growl/Net/Growl/Udp.php',
    'SebastianBergmann\\Version' => $vendorDir . '/sebastian/version/src/Version.php',
);
```
 
Issue come with a phar version of my project when I did not embedded the optional dependencies (pear/net_growl in my case).

When optional resource is asked the phar distrib raised an error, because it cannot load classes corresponding to rules declared in `autoload_classmap.php`.

I've found a solution, and I hope to have at least such similar approach included in base code of  composer.

In phar stub, I've added a fallback strategy that will remove some class map entries, to let ability to check if resources are installed in the global vendor dir (and more in include_path).

```php
/**
 * Ability to use global composer packages installed, then include_path,
 * for optional dependencies not provided by the phar distribution (e.g: pear/Net_Growl)
 */
$home = getenv('COMPOSER_HOME');
if (!$home) {
    if (defined('PHP_WINDOWS_VERSION_MAJOR')) {
        if (getenv('APPDATA')) {
            $home = strtr(getenv('APPDATA'), '\\', '/') . '/Composer';
        }
    } else {
        if (getenv('HOME')) {
            $home = rtrim(getenv('HOME'), '/') . '/.composer';
        }
    }
}
if ($home) {
    $fallbackNetGrowlDir = $home . '/vendor/pear-pear.php.net/Net_Growl';

    $fallbackClassMap = function ($classMap, $classPrefix) {
        array_walk(
            $classMap,
            function (&$value, $key, $userData) {
                if (strpos($key, $userData) !== false) {
                    // will remove this entry in class map
                    $value = null;
                }
            },
            $classPrefix
        );
        return $classMap;
    };
}
```
NOTE: the generic code is `$fallbackClassMap` closure.

Use is in the `bin\phpreflect` command 

```
$loader = require_once $vendorDir . '/autoload.php';
$loader->setUseIncludePath(true);
if (\Phar::running()) {
    if ($home) {
        // when optional resources are not embedded in phar distribution,
        // avoid PHP Warnings, and lookup first in global vendor dir (COMPOSER_HOME) if exists
        $classMapfiltered = $fallbackClassMap($loader->getClassMap(), 'Net_Growl');
        $loader->addClassMap($classMapfiltered);
        // try to find PEAR Net_Growl classes package in folder $fallbackNetGrowlDir (see phar-stub.php)
        $loader->add(false, $fallbackNetGrowlDir);
    }
}

```
  
Full patch of my project is on commit https://github.com/llaville/php-reflect/commit/0b376188b8613851d7788783b14423708c8f4ffa

**Comment by stof** [comment]
IMO, a much cleaner way would be to generate the autoloader for usage inside the phar without the dev requirements if you don't bundle the dev requirements

**Comment by llaville** [comment]
But what do you do, when you have some dev requirements that add additional features and others optionals

E.g:
```json
    "require": {
        "php": ">=5.3.2",
        "ext-libxml": "*",
        "ext-pcre": "*",
        "ext-spl": "*",
        "ext-json": "*",
        "ext-pdo_sqlite": "*",
        "bartlett/php-reflect": "~3.1"
    },
    "require-dev": {
        "doctrine/cache": "~1.3",
        "psr/log": "~1.0",
        "monolog/monolog": "~1.10",
        "bartlett/monolog-callbackfilterhandler": "~1.0",
        "bartlett/monolog-growlhandler": "~1.0",
        "bartlett/phpunit-loggertestlistener": "~1.5",
        "bartlett/umlwriter": "~1.0"
    },
```
Cache, logging and uml features are not really mandatory but add a real additionl power, while the growl notification is considered as optional.

**Comment by stof** [comment]
well, either you bundle everything in the phar or nothing IMO, but not a mix. It would be quite impossible to understand for users if the phar contains half of the optional deps. Building an extension system allowing to load plugins from outside the phar seems better

**Comment by llaville** [comment]
Sorry, but I don't agree with you on bundle strategy. 
With my two main dev-requirements categories : really usefull (cache, log, uml) and optional (growl, logger test listener), With the same autoloader produced by composer I'm able to build a phar version that will build a manifest ( https://github.com/llaville/php-compat-info/blob/master/phar-manifest.php) for final user 
```
phpcompatinfo --manifest
```
that identify which dependencies is bundled
```
bartlett/php-compatinfo: 4.3.0
bartlett/php-reflect: 3.1.0
doctrine/collections: v1.3.0
justinrainbow/json-schema: 1.4.2
nikic/php-parser: v1.3.0
phpdocumentor/reflection-docblock: 2.0.4
sebastian/version: 1.0.5
seld/jsonlint: 1.3.1
symfony/console: v2.7.1
symfony/dependency-injection: v2.7.1
symfony/event-dispatcher: v2.7.1
symfony/finder: v2.7.1
symfony/stopwatch: v2.7.1
bartlett/umlwriter: 1.0.0
doctrine/cache: v1.4.1
monolog/monolog: 1.13.1
psr/log: 1.0.0
```
And I've already a load plugin system (for growl notification) that load the notifier (https://github.com/llaville/php-reflect/blob/master/src/Bartlett/Reflect/Plugin/Notifier/GrowlNotifier.php) on demand (with a json conf)

E.g:
```json
    "plugins": [
        {
            "name": "Notifier",
            "class": "Bartlett\\Reflect\\Plugin\\NotifierPlugin",
            "options" : "Bartlett\\Reflect\\Plugin\\Notifier\\GrowlNotifier"
        }
    ],
```

**Comment by alcohol** [comment]
A Phar should provide everything, regardless of wether it is optional or not. That's commonly accepted as the best approach. Look at PHPUnit and such for similar examples. It should be able to function as a completely stand alone binary.

**Comment by llaville** [comment]
@alcohol PHPUnit is a different use case. All optional dependencies (phpunit/* or sebastian/*) may be used without any other additional dependencies.

In my case, my optional feature is notification via a plugin and growl (that used the PEAR package) but I may also used any other notification solution rather than growl.

I don't think it's a best idea to bundle all possible notification plugins in my case, but perharps rather use sub-packages. Anyway, I've proposed a fallback strategy that match my need and be usefull for other users. If @Seldaek Jordi think it's not acceptable, this issue may be closed.

I've just shared my use case !

**Comment by alcohol** [comment]
In this case I would suggest you offer a download page where users can download pre-compiled different flavors (using different notification systems), or alternatively, built a composite on the fly depending on what options the user has selected. In the end, the result should be the same, a single binary that contains everything.

**Comment by Seldaek** [comment]
@llaville I don't think this is really composer's problem, sounds too specific and edge case to me, but it also sounds like something you can resolve from the outside somehow. Have you looked at https://github.com/dflydev/dflydev-embedded-composer ? Maybe @simensen can expand on that, but it sounds to me like maybe a use case for it with regard to having plugins and so on..
