### ISSUE TITLE
no matching package found error after composer selfupdate

### ISSUE THREAD

**Issue by statista** [composer/composer#4160]
After we upgraded to a new version of composer we are getting the following error:
requires aws/aws-sdk-php 2.7.27 -> no matching package found.
the aws-sdk-php seems to be in place.

**Comment by samdark** [comment]
https://github.com/francoispluchino/composer-asset-plugin/issues/126

**Comment by samdark** [comment]
Broken somewhere between these https://github.com/composer/composer/compare/8e9659b...74e7c5fe22dc456336a2b20c7b12a9a83fc4af09

**Comment by samdark** [comment]
I guess it's https://github.com/composer/composer/commit/3e85f82373aa7a05c7cc85a7f6d4725690713197

**Comment by Seldaek** [comment]
Can anyone give me the complete composer.json so I can try and reproduce this here? Just requiring aws/aws-sdk-php 2.7.27 seems to work for me.

**Comment by temp** [comment]
Same here with 74e7c5fe22dc456336a2b20c7b12a9a83fc4af09.

Minimal composer json that breaks:
```
{
    "minimum-stability": "dev",
    "require": {
        "brainbits/fugue-icons-bundle": "dev-master"
    }
}
```

**Comment by temp** [comment]
With a rollback to version 2015-06-16_10-43-55-b2173d2 it works...

**Comment by Seldaek** [comment]
We reverted the bad commit so self-update or rollback should bring you back to a working state

**Comment by SamBurns-awin** [comment]
That was quick.  Cheers, @Seldaek!

**Comment by samdark** [comment]
Works. Thanks!

**Comment by statista** [comment]
works. thanks a lot
