### ISSUE TITLE
 composer self-update to version #74e7c5 > Illegal string offset 'versions'

### ISSUE THREAD

**Issue by calinpristavu** [composer/composer#4162]
After self-update, I get the following

    [ErrorException]                  
    Illegal string offset 'versions'

    Exception trace:
     () at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:524
     Composer\Util\ErrorHandler::handle() at phar:///usr/local/bin/composer/src/Composer/Repository /ComposerRepository.php:524
     Composer\Repository\ComposerRepository->loadIncludes() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:477
     Composer\Repository\ComposerRepository->loadDataFromServer() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:373
     Composer\Repository\ComposerRepository->initialize() at phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:128
     Composer\Repository\ArrayRepository->addPackage() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:387
     Composer\Repository\ComposerRepository->addPackage() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:353
     Composer\Repository\ComposerRepository->loadName() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:129
     Composer\Repository\ComposerRepository->loadRecursively() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:148
     Composer\DependencyResolver\Pool->loadRecursively() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php:182
     Composer\DependencyResolver\Solver->solve() at phar:///usr/local/bin/composer/src/Composer/Installer.php:505
     Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:230
     Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:140
     Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
     Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
     Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
     Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:146
     Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
     Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:82
     Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
     require() at /usr/local/bin/composer:25

If I do a rollback, everything is fine. the problem occured today at arround 12:00 - 14:00.

My best guess is that this merge https://github.com/composer/composer/commit/3e85f82373aa7a05c7cc85a7f6d4725690713197 is the problem.

This is quite critical, as our deployment scripts always self-update.

By the way, we use toran proxy over composer

**Comment by stof** [comment]
@calinpristavu update again as this broken merge has been reverted

**Comment by calinpristavu** [comment]
thank you @stof Closed.
