### ISSUE TITLE
scripts:post-update|install-cmd requires proc_open

### ISSUE THREAD

**Issue by staabm** [composer/composer#4164]
Installation of composer works even when `proc_open` is not allowed by php.ini.
Until now we got now problems on the server, which disallows `proc_open`.

As we changed our `composer.json` to include a "scripts" section, composer runs into a exception:

```
[Symfony\Component\Process\Exception\RuntimeException]
The Process class relies on proc_open, which is not available on your PHP installation.

Exception trace:
 () at phar:///usr/local/bin/composer/vendor/symfony/process/Symfony/Component/Process/Process.php:148
 Symfony\Component\Process\Process->__construct() at phar:///usr/local/bin/composer/src/Composer/Util/ProcessExecutor.php:59
 Composer\Util\ProcessExecutor->execute() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:174
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:91
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar:///usr/local/bin/composer/src/Composer/Installer.php:342
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php:131
 Composer\Command\InstallCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:146
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:83
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:25
```

Should the initial installation of composer fail when `proc_open` is not available? I guess not.

Not sure if we can improve the situation here. Maybe composer should have told me that `proc_open` is required, because I defined a "post-install-cmd"?

**Comment by Seldaek** [comment]
Thing is in ideal conditions (dist downloads only, and zip extension available) we can install without proc_open, so we indeed should not require it. But yes if you have scripts that invoke external processes those won't work without proc_open.. We could soft-skip them with a warning I guess, not sure if it's better than failing hard. Given you are in control of which scripts run I feel like it's ok to leave the user in control of whether to remove the scripts or not. Or you can run with --no-scripts

**Comment by staabm** [comment]
Ok, I think we mostly agree here.

Whats about the last note:
>Maybe composer should have told me that proc_open is required, because I defined a "post-install-cmd"?

So just adding more information to the exc. Msg, so user gets a feeling that everything but the post-cmd worked?

**Comment by Seldaek** [comment]
Oh sure I missed that, but yes that would make sense.

**Comment by Seldaek** [comment]
We could add checks in the VCS downloader and before dispatching cmd scripts

**Comment by staabm** [comment]
just had a look at the source again.

The exception we are talking about is not typed properly, so we cannot distinguish it from other RuntimeExceptions sfProcess might throw.

Therefore I dont see much room for improvement here.

**Comment by xiaoshu896448** [comment]
php -n composer,the -n option will ignore the default php.ini file setting's disable_functions list which include the proc_open function.

**Comment by ichabodphp** [comment]
In **php.ini** file,there is a disable_functions list,you can search "disable_functions" and find that,then remove it;

like this:

```
; This directive allows you to disable certain functions for security reasons.
; It receives a comma-delimited list of function names.
; http://php.net/disable-functions
disable_functions = passthru,exec,system,chroot,scandir,chgrp,chown,shell_exec,popen,ini_alter,ini_restore,dl,openlog,syslog,readlink,symlink,popepassthru,stream_socket_server
```

**Comment by maxdeviper** [comment]
you can use php -d disable_function= composer install
