### ISSUE TITLE
--prefer-dist is ignored when used with --keep-vcs

### ISSUE THREAD

**Issue by gennadiylitvinyuk** [composer/composer#4166]
I want to create new project with `composer create-project`. 
The main project should come from SVN, and dependencies from dists.

Earlier I could use
```
composer create-project namespace/project --keep-vcs --prefer-dist -s dev
```

Now it is impossible to get dist versions of dependent packages.

Look like 98b339e introduced this problem

**Comment by Seldaek** [comment]
Oh I didn't see this issue, but anyway as you probably saw in the other thread, I fixed it earlier.
