### ISSUE TITLE
Bin installation fails if there is bin-dir in config.json

### ISSUE THREAD

**Issue by TriAnMan** [composer/composer#4173]
1. Use linux
2. Logon with a root account.
3. Create a `/root/.composer/composer.json` file with 
```
{
    "config": {
        "bin-dir": "/root/bin"}
}

```

in it.
4. Run `composer init` for your project
5. Run `composer require phpunit/phpunit` or any other package with binaries.
6. Drop a `vendor` dir in your project.
7. Run `composer install` for your project

You will see something like that in console:
_Skipped installation of bin phpunit for package phpunit/phpunit: name conflicts with an existing file_
And there will be no `phpunit` symlink into `vendor/bin` folder for your project. But there will be symlink to phpunit ino the `/root/bin` directory.

I think that composer should differ global or local config either for binaries.
So the expected behavior is the following:
Composer installs binaries for the project and not installs its globally.
If I run `composer global install` or `composer global require phpunit/phpunit` composer handles global parameters from the `/root/.composer/composer.json`.

**Comment by Seldaek** [comment]
Actually the global config is ~/.composer/config.json, and ~/.composer/composer.json is just a composer file.. If you do it like you described at step 3 there you should not have conflicts between global and local configs. Only if you put it in the global config will it apply to everything.

That said I think adding /root/.composer/bin to your PATH and using `"bin-dir":"bin/"` would be a better way than having an absolute path in there which we don't always support well.

**Comment by TriAnMan** [comment]
Sorry, I've mistyped. I mean /root/.composer/config.json not /root/.composer/composer.json of cause.

But why should global config override settings for local projects? Even it should, id do it in a wrong way here...
It creates two symlinks for one binary. First at the project vendor/bin directory and second at /root/bin directory.

For my mind it is a kind of a glith. If the global config should override the local one there should be only one link at /root/bin, otherwise if the global config applies only for `composer global` commands it should be only one link at project/vendor/bin directory.

**Comment by Seldaek** [comment]
The global config (config.json) changes the defaults globally, and then every composer.json can change those defaults again if needed. The solution is pretty simple just follow step 1, 2, 3 like you outlined above but actually put the "bin-dir" config inside /root/.composer/composer.json and **not config.json**.  That way the bin-dir will apply only to the global dependencies, and local ones will just go as usual in vendor/bin only

**Comment by TriAnMan** [comment]
@Seldaek thanks a lot! You solution is pretty good for me.

It also seems that I've not tested my issue scenario. Seems that two symlinks (one in the project bin dir and another in the root bin dir) comes from historical reasons of my project and I've not tested it from the scratch. For current version of composer everything works as expected. Sorry for bothering you.

**Comment by TriAnMan** [comment]
@Seldaek What if the documentation or the `composer help` command should be more specific about the difference between `composer global config` and `composer config --global`, shouldn't they?
