### ISSUE TITLE
Get an aggregate list of suggestion from cli

### ISSUE THREAD

**Issue by Grummfy** [composer/composer#4175]
Hello,
When you run ```composer show vendor/package``` You have the list of suggestions for the package. 

But, you can't have an aggregate view of all packages suggestion.

So I propose this command ```composer suggests``` to make a aggregation of suggestion like we have on composer install.

**Comment by Seldaek** [comment]
If you'd like to take #2819 as base, fix stof's comments and send a new PR with that, I think it might be good to go.

**Comment by Grummfy** [comment]
yep. Happy that someone already do this and with the same command name ;)
