### ISSUE TITLE
zlib_decode(): data error for Update

### ISSUE THREAD

**Issue by BloomPhilippe** [composer/composer#4176]
Bonjour,

Dés que j'update mon vendor Symfony j'ai une erreur Zlib_decode...

Diagnos est parfait!

J'ai essayer sur Ubuntu, Windows et j'ai la même erreur...

Merci d'avance pour votre aide

Bonne soirée,
Phil

**Comment by BloomPhilippe** [comment]
Hello,

Whenever I update my vendor Symfony I Zlib_decode a mistake ...

Diagnos is perfect!

I try on Ubuntu , Windows, and I have the same error ...

Thank you in advance for your help

Good night,
PS: sorry for my english traduction :)
Phil

**Comment by GromNaN** [comment]
Sorry but we can't help with so few information.
You can check other issues related to `zlib_decode`: https://github.com/composer/composer/search?q=Zlib_decode&type=Issues&utf8=%E2%9C%93

**Comment by frederikbosch** [comment]
@BloomPhilippe See issue #4121. You could help by downloading and running the script  I posted there. Please share your results in that issue.

**Comment by Seldaek** [comment]
Closing as duplicate
