### ISSUE TITLE
Manual Install on Yosemite

### ISSUE THREAD

**Issue by mvgregory** [composer/composer#4179]
The download is timing out through the command line ("all settings correct for using composer"), so I downloaded the "composer.phar", and stuck it @ /usr/local/bin/composer.phar. When I type "composer" in the terminal:

Michaels-MacBook-Pro:~ mgregory$ composer
-bash: /usr/local/bin/composer: No such file or directory

What is the problem? How do I fix it?

**Comment by alcohol** [comment]
https://getcomposer.org/doc/00-intro.md#globally

You have to rename it, not just move it. Please follow the instructions completely :-)

**Comment by mvgregory** [comment]
You're going to have to break it down a little more than pointing me to the instructions I already failed at using...

**Comment by slbmeh** [comment]
@mvgregory the file name you mention is `composer.phar`, you should rename that to be just `composer` in order for composer to be found in your path as composer.

**Comment by mvgregory** [comment]
I did actually try that. See my second comment for the less than stellar results 

Michael

**Comment by alcohol** [comment]
Did you also apply the required permissions?

```
sudo chmod +x /usr/local/bin/composer
```

**Comment by slbmeh** [comment]
The don't really have anything more than the response by @alcohol

Not having the executable bit set would result in permission denied.

The second error when you tried to run it with `sudo` sounds like you probably don't have `PATH` in your `env_keep` of the sudoers configuration.

**Comment by alcohol** [comment]
Have you managed to get it working?

**Comment by mvgregory** [comment]
Turns out the ultimate solution was to try the "curl..." command from home, where it downloaded automatically, and installed like it should have. Got to say, the manual install instructions need some help... Thanks for trying though!

 <http://moderninterface.com/>	Michael Gregory <https://www.linkedin.com/profile/view?id=365564598> production coordinator
moderninterface.com <http://moderninterface.com/>
503.241.8234 <tel:+1-503-241-8234>

**Comment by alcohol** [comment]
I actually have an open PR in regards to the documentation. Could you maybe expand on why the existing documentation was not clear for you? I can take that into consideration then.

**Comment by mvgregory** [comment]
Well, first off, there are no instructions for manual install for *nix systems, only windows. I did the following, which never did work for me

Download composer.phar
Move into /usr/local/bin/
rename to? (I tried "composer", but it didn't register as an executable, and wouldn't run. This is the step that I never could figure out, I also tried running "php composer.phar" but that didn't work either)


 <http://moderninterface.com/>	Michael Gregory <https://www.linkedin.com/profile/view?id=365564598> production coordinator
moderninterface.com <http://moderninterface.com/>
503.241.8234 <tel:+1-503-241-8234>

**Comment by alcohol** [comment]
I think you are mistaken.. there are clear instructions for a manual install on [*nix](https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx) systems, which is then divided into [local](https://getcomposer.org/doc/00-intro.md#locally) and [global](https://getcomposer.org/doc/00-intro.md#globally).

Perhaps the commands are too complicated for someone unfamiliar with the command line. What about the following?

> For a global install on almost any *nix OS:
> ```
> curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
> ```
>
> You just need to make sure that **/usr/local/bin** is part of your `PATH` environment.

**Comment by stof** [comment]
@alcohol the issue with this is that it makes you run the downloaded installer file as root, which is precisely why it is not advocated this way

**Comment by mvgregory** [comment]
So, I'm not a command line Jedi yet, and I think I see what you're doing, but I can't actually translate that into what I would have needed to do.

If you have just the composer.phar file, downloaded off the website, what would you need to do to actually make it install. I'm going to take a stab at what I think it would take.

put composer.phar into /usr/local/bin
cd /usr/local/bin
composer.phar sudo php -- --intall-dri=usr/local/bin --filename=composer

> You just need to make sure that /usr/local/bin is part of your PATH environment.
> 

I had to look up instructions on how to do this. Sure, it may be something everyone knows (for very small values of everyone), but for someone who is new to command line, it's like saying "just follow the recipe for monkey armadillo cakes"




 <http://moderninterface.com/>	Michael Gregory <https://www.linkedin.com/profile/view?id=365564598> production coordinator
moderninterface.com <http://moderninterface.com/>
503.241.8234 <tel:+1-503-241-8234>

**Comment by alcohol** [comment]
@mvgregory actually that is not going to work if you downloaded the composer.phar directly (missing an action or two). I guess there aren't any instructions really taking that scenario into account. I mean, in practical terms there are.. but oh well. Will think about this tomorrow when I look at the docs.

**Comment by alcohol** [comment]
@stof the installer is completely public. Anyone can look at it. So I don't see the harm in demonstrating it as one of the multitude of available options.
