### ISSUE TITLE
Composer hangs when cloning SSH repository with enabled ControlMaster

### ISSUE THREAD

**Issue by astehlik** [composer/composer#4180]
This is a really strange bug.

I'm using the ControlMaster setting of SSH to speed up connections to our Git server:

```
Host mygitserver
	ControlMaster auto
	ControlPath ~/.ssh/master-%r@%h:%p
	ControlPersist 1h
```

I can manually access the Server with SSH and clone repositories without a problem.

But when I use composer and the master file does not exist, composer just stops working on this command:

```
git clone --no-checkout 'git@mygitserver:mydir/myrepo.git' '/the/target/dir' && cd '/the/target/dir' && git remote add composer 'git@mygitserver:mydir/myrepo.git' && git fetch composer
```

When I look at the process tree, I see this:

```
php /usr/local/bin/composer.phar -vvv update
  \_ [sh] <defunct>
```

When I open a connection to the SSH server **before** running composer and the master file already exists the composer command runs without problems.

**Comment by cs278** [comment]
Eureka, I've been having this problem for ages never occurred to me it might be down to SSH connection multiplexing. This would explain why I don't see it very often and a SIGINT and re run always works.

**Comment by astehlik** [comment]
I'm glad I'm not the only one ;)

As a workaround I'm using a script that does a ```ssh -t mygitserver``` before the composer run.

**Comment by slbmeh** [comment]
This has been a bug in SSH for a while with control persist.

https://bugzilla.mindrot.org/show_bug.cgi?id=1988

**Comment by astehlik** [comment]
Thanks for the pointer.

Since this does not seem to be a composer bug, maybe this should be added to the troubleshooting section in the docs?

**Comment by alcohol** [comment]
Odd, I use roughly the same settings but I have never had any trouble with it.

```
Host *
    TCPKeepAlive no
    ServerAliveInterval 10
    ServerAliveCountMax 3
    ControlMaster auto
    ControlPath ~/.ssh/ssh-%r@%h:%p
    ControlPersist 2h
    GSSAPIAuthentication no
```

**Comment by staabm** [comment]
@alcohol maybe you dont use a ssh version which is affected by the bug (see bugreport)

**Comment by alcohol** [comment]
rob@robbast ~ (master) $ ssh -V
OpenSSH_6.8p1, OpenSSL 1.0.2c 12 Jun 2015

**Comment by cs278** [comment]
By the sounds of things it was never fixed in SSH they just added the `-E` option so you could stop it opening stderr. So I suspect unless that option is being used it should be present in all versions that support multiplexing.

@alcohol I'm using 6.6 and can reproduce the problem, the difference is I use a time out of 10 minutes rather than your much longer 2 hours. I think I'll bump mine up for GitHub.

Console output on my machine: https://gist.github.com/cs278/7e60c231159bc2249cd8

Steps to reproduce are basically:

```bash
cd "$(mktemp -d)"
ssh -O exit git@github.com
composer require --prefer-source psr/log '*'
```

**Comment by alcohol** [comment]
Eh your steps to reproduce doesn't really work for me...

```
rob@emac019 ~/Music (master) $ cd "$(mktemp -d)"
rob@emac019 /var/folders/q2/s6l2p2gj36l710r752smh96c0000gp/T/tmp.4dok4Aw4Dv $ ssh -O exit git@github.com
Control socket connect(/Users/rob/.ssh/ssh-git@github.com:22): No such file or directory
rob@emac019 /var/folders/q2/s6l2p2gj36l710r752smh96c0000gp/T/tmp.4dok4Aw4Dv $ composer require --prefer-source psr/log '*'
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing psr/log (1.0.0)
    Cloning fe0936ee26643249e916849d48e3a51d5f5e278b

Writing lock file
Generating autoload files
```

**Comment by stof** [comment]
@alcohol you should also force composer to use the ssh url when cloning the repo. If it clones over https, it will of course not be impacted. and by default, SSH is the last protocol: https://getcomposer.org/doc/06-config.md#github-protocols and https://github.com/composer/composer/blob/84661296ffe281b6238cc29b39526b31f26f3918/src/Composer/Config.php#L30

**Comment by alcohol** [comment]
I see. So I guess his internal server doesn't support the git and https protocol, hence the ssh fallback.

**Comment by slbmeh** [comment]
I have the issue with private repos. I have my environment set up to point GIT_SSH to a wrapper that spawns a control master if the socket isn't available. Then calls ssh.

**Comment by Seldaek** [comment]
Closing as it's not clear what we can do to help.
