### ISSUE TITLE
composer install fails on hhvm

### ISSUE THREAD

**Issue by mseshachalam** [composer/composer#4182]
https://github.com/Shippable/support/issues/1610

**Comment by aderuwe** [comment]
@mseshachalam As the message says, I think your composer is pretty old. ;)

**Comment by mseshachalam** [comment]
@aderuwe I am updating the composer. The before step to install is ```composer self-update```

**Comment by aderuwe** [comment]
Ah, you're right, I missed that. The self-update is somehow not completing, then, I guess...
