### ISSUE TITLE
Files are not automatically autoloaded for triggered scripts

### ISSUE THREAD

**Issue by jeskew** [composer/composer#4184]
I'm using a static method as a `post-autoload-dump` script and found that files are not automatically loaded.  This can be resolved by explicitly requiring the Composer autoloader, but I wasn't sure if this was intentional. Essentially, in order to use a function in static method being used as a post-autoload-dump hook, I have to `require 'vendor/autoload.php'` even though the autoloader is the one calling the method.

The [AWS Symfony Bundle](https://github.com/aws/aws-sdk-php-symfony/blob/master/build/DocumentationUpdater.php#L22) has to explicitly require the autoloader in a triggered script.

**Comment by alcohol** [comment]
>For any given event:
>
>* Scripts execute in the order defined when their corresponding event is fired.
>* An array of scripts wired to a single event can contain both PHP callbacks and command-line executable commands.
>* PHP classes containing defined callbacks must be autoloadable via Composer's autoload functionality.

It's because the `autoload.php` file is not used for the `scripts` part, but rather the autoloader functionality itself. This can resolve classes, but indeed it does not implicitly load the `files` autoload definitions.

I'm not even sure if `require 'vendor/autoload';` would work on an initial install. It depends on whether or not the autoload files are dumped before or after the event gets triggered. So your workaround might not even work in all scenarios. Did you try and see if it covers all event types?

**Comment by jeskew** [comment]
That's a good point, but there's already a disclaimer on the documentation page. https://github.com/composer/composer/blame/master/doc/articles/scripts.md#L64

**Comment by alcohol** [comment]
That disclaimer is about Composer managed dependencies though. So say your script requires a class from `symfony/console` which is in your `require` section. Composer cannot guarantee that that package is already installed when your event gets called. 

I guess it's sort of related to what I was hinting at. However, this does not depend on when the autoloader gets dumped, but purely on the event type you are using and whether or not it gets triggered before or after said package is installed.

**Comment by jeskew** [comment]
Right; one can't be certain of the state of your dependencies before install or update has been called. Those dependencies might include autoloaded files. As the documentation is written, I believe it's clear that scripts that rely on external dependencies only make sense to run after install or update has run.

**Comment by jeskew** [comment]
Solved by #4186 and #4187. Thanks!
