### ISSUE TITLE
Fixed version of composer.phar on GitHub - SHA1 signature could not be verified: broken signature

### ISSUE THREAD

**Issue by nuxwin** [composer/composer#4188]
Hello ;

We wanted push a fixed version of composer.phar in our own GitHub repository but when we do, we get the following error when using that fixed version ( pulled from our repository):

```shell
root@jessie:/usr/local/src/imscp-1.2.x# php /var/www/imscp/engine/setup/composer.phar --no-ansi -d=/var/cache/imscp/packages update --prefer-dist
PHP Fatal error:  Uncaught exception 'PharException' with message 'phar "/var/www/imscp/engine/setup/composer.phar" SHA1 signature could not be verified: broken signature' in /var/www/imscp/engine/setup/composer.phar:23
Stack trace:
#0 /var/www/imscp/engine/setup/composer.phar(23): Phar::mapPhar('composer.phar')
#1 {main}
  thrown in /var/www/imscp/engine/setup/composer.phar on line 23
```

We suspects that some files are changed while commiting the composer.phar archive into our GitHub repository because that .gitattributes file:

```
.gitattributes export-ignore
.gitignore export-ignore
* text eol=lf
*.gif binary
*.jpg binary
*.mo binary
*.mgc binary
*.png binary
*.sfd binary
*.ttf binary
```

but we're not really sure.. Could you advise us regarding this issue?

BTW: We want really store a fixed version of composer.phar for safety reasons, e.g in case the upstream composer site is down.

Thanks you.

**Comment by nuxwin** [comment]
Does something like

```
*.phar binary
```

in our .gitattributes file could solve the problem?

Thanks you

**Comment by alcohol** [comment]
The best way to find out is often just trying it yourself :-). Did you try it?

Honestly though, even if upstream does go down, you could always get Composer from GitHub. So there is no need to store Composer inside your own GitHub repository ;-).

**Comment by nuxwin** [comment]
Loving such answer... This is not processed by an human so getting un-archived composer files from github is a no go... I ask here because you manage that SHA1 but ok, I'll try to figure out alone...

**Comment by alcohol** [comment]
We don't manage the SHA1. It's an internal mechanic of the Phar signature process. See also [php.net/phar.setsignaturealgorithm](http://php.net/manual/en/phar.setsignaturealgorithm.php). 

I'm simply telling you to try it yourself because I have personally never stored a Composer.phar inside a repository. Therefor I do not know whether or not text mode or binary mode makes a difference. I'm not trying to be rude, it's just the best answer I can offer you right now :-).

**Comment by nuxwin** [comment]
Fine, I prefers that answer ;) Can you at least say me what line separator you're using in your files (LF or CRLF)?

Thanks

**Comment by alcohol** [comment]
Composer source files use LF (see [.gitattributes](https://github.com/composer/composer/blob/master/.gitattributes)). However, the compiled `composer.phar` file should probably be considered binary (I did some Google digging).

**Comment by nuxwin** [comment]
Thanks.

**Comment by alcohol** [comment]
Did you manage to get it working using the binary attribute?

**Comment by nuxwin** [comment]
Hello ;

I'll give a try today ;)

**Comment by mrmoree** [comment]
is there any solution for the singing error?
i try to get to work the yeoman generator for typo3
but when it comes to build:Shell cmd "composer.phar install" an error is thrown "SHA1 signature could not be verified: broken signature' "

**Comment by bbbb** [comment]
how to create google map in yii2 and tag the places
