### ISSUE TITLE
Can't catch an existing stable package.

### ISSUE THREAD

**Issue by Soullivaneuh** [composer/composer#4194]
I got the following error:

```
The requested package sonata-project/core-bundle ~2.2,>=2.2.6 could not be found.
```

But the minimum needed package exists: https://packagist.org/packages/sonata-project/core-bundle#2.2.6

Is this error due to another problem? Which one in this case?

composer.json file: https://github.com/sonata-project/SonataNotificationBundle/pull/142/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

Related Travis job: https://travis-ci.org/sonata-project/SonataNotificationBundle/jobs/68768768#L346

Regards

**Comment by alcohol** [comment]
I'm sorry but I am unable to reproduce this issue. Also, your linked diff shows `~2.2,>2.2.4` being raised to `~2.2,>2.2.5`, neither of which matches `~2.2,>=2.2.6` from the error you supplied. Are you sure the link and the error are related?

**Comment by alcohol** [comment]
Also you currently (`master` branch) have the same package in both `require` and `require-dev`, this is not possible. One will replace the other.

**Comment by alcohol** [comment]
What is more confusing is, why does it even throw a solver error _after_ installing everything? 

It would make sense that after installing `2.2.5` that `2.2.6` is not available (you passed --prefer-lowest). But I don't know where this `~2.2,>=2.2.6` requirement is coming from.

**Comment by Soullivaneuh** [comment]
> Are you sure the link and the error are related?

Yes. It was updated, was `~2.2,>=2.2.6`.

> Also you currently (master branch) have the same package (sonata-project/core-bundle) in both require and require-dev. This is not possible, one will replace the other.

Found this recently indeed. Don't know why it was like this.

Removing it from `require-dev` works, thanks!

**Comment by alcohol** [comment]
Oh, ok. You're welcome.

**Comment by Soullivaneuh** [comment]
> What is more confusing is, why does it even throw a solver error after installing everything?

Yes. This is why I was lost. Resolving issue should be thrown **before** package installation.

Very strange.

**Comment by alcohol** [comment]
Maybe the `--no-interaction` flag changes that behaviour, I'm not sure to be honest.

**Comment by Soullivaneuh** [comment]
Nope, ran it without this option on my local, same issue (after installation).

**Comment by stof** [comment]
well, composer does a second resolution when generating the lock file, with only the installed packages in it, and only the require constraint, to be able to know whether a package should go in the ``packages`` or ``packages-dev`` section of the lock file.
If a package is defined in both require and require-dev, it might indeed create weird behavior at this point in some cases.

**Comment by Soullivaneuh** [comment]
@stof Thanks for the explanation. :+1:
