### ISSUE TITLE
autoload-dump optimize throws ambiguous class error

### ISSUE THREAD

**Issue by bazo** [composer/composer#4195]
the latest composer build throws ambiguous class error when optimizing the autoloader. it says Class was found in both File1 and File2, but File1 === File2 amd the class is certainly not declared twice

before the update i didn't see this at all

Composer version 1.0-dev (943107cfe717a74aa791f57b87fa514c88582b0d) 2015-06-26 13:40:26

**Comment by alcohol** [comment]
@Seldaek your ninja commit seems to have raised several issues over the weekend :-(

**Comment by alcohol** [comment]
@bazo can you confirm or deny if you are mixing `psr-0` and `classmap` definitions (or any other mix)?

**Comment by bazo** [comment]
yes, looks like the packages mix classmap and (psr-4 or psr-0)

**Comment by staabm** [comment]
> throws ambiguous class error

does it throw actuall errors or warnings?

**Comment by alcohol** [comment]
They are actually simply text message on `stderr` with `<warning></warning>` markup.

**Comment by alcohol** [comment]
@bazo mixing those and using the `optimize` option will most likely result in duplicates as I also pointed out [in this comment](/composer/composer/commit/943107cfe717a74aa791f57b87fa514c88582b0d#commitcomment-11905750).

**Comment by domhnallw** [comment]
I'm seeing this as well. My composer.json only uses a psr-4 autoloader but the composer package that's causing the problem (TCPDF) uses the classmap approach.

**Comment by stof** [comment]
@domhnallw can you show how your composer.json look like ?

**Comment by domhnallw** [comment]
Have to leave out names etc. as it's a commercial product, but:

```php
{
    "name": "mycompany/myproject",
    "description": "My Project",
    "licence": "proprietary",
    "type": "project",
    "homepage": "http://www.mywebsite.com/",
    "version": "1.0",
    "require": {
        "twig/twig": "1.*",
        "twig/extensions": "~1.1.0",
        "analog/analog": "1.*",
        "ircmaxell/password-compat": "~1.0",
        "tecnick.com/tcpdf": "~6.2",
        "phpoffice/phpexcel": "1.*",
        "ramsey/array_column": "1.*",
        "lightopenid/lightopenid": "~0.7",
        "slim/slim": "2.*",
        "pear-pear.php.net/Math_Stats": "0.8.5",
        "pear-pear.php.net/SOAP": "*",
        "textmagic/smsphp": "dev-master",
        "jpgraph/jpgraph": "dev-master",
        "google/apiclient": "1.0.4-beta",
        "phpmailer/phpmailer": "~5.2"
    },
    "require-dev": {
        "corneltek/getoptionkit": "~2.0",
        "pear-pear.php.net/HTTP_Request2": "2.*",
        "illuminate/database": "~5.0",
        "league/climate": "~2.6"
    },
    "autoload": {
        "psr-4": { "MyApp\\": "classes/"}
    },
    "repositories": [
        {
            "type": "pear",
            "url": "http://pear.php.net"
       }
    ],
    "minimum-stability": "stable"
}

```

**Comment by alcohol** [comment]
For some reason `tecnick.com/tcpdf` has a `classmap` that contains `include/` as a directory, but also entries such as `include/<filename>` which when optimized would create duplicates.

**Comment by stof** [comment]
I suggest you to send them a PR cleaning their classmap

**Comment by domhnallw** [comment]
That's all well and good but the previous version of composer didn't have an issue with it?

**Comment by alcohol** [comment]
I didn't **report** an issue. Subtle difference. It now reports the issue that was previously hidden, giving the user a chance to correct any mistakes that might be his own wrong doing, but the behaviour doesn't really change in the end.

**Comment by stof** [comment]
and btw, Composer does not throw any error. It still considers that the autoloader dumping worked. It only tells you that something might be wrong with the package, and that it could create weird things.

and telling you that something might create issues is better than doing nothing and then letting people spend lots of time trying to understand these issues when they happen IMO.

**Comment by domhnallw** [comment]
I should be careful with using the word "issue", sorry. I meant that it didn't generate any warnings or error messages until now.

And I would *much* prefer to have something complain about a potential... complication? rather than stay silent :)

**Comment by ntomka** [comment]
So [in my case](https://github.com/composer/composer/commit/943107cfe717a74aa791f57b87fa514c88582b0d#commitcomment-11889683) I should tell HybridAuth developers to look in to this issue?

**Comment by alcohol** [comment]
@ntomka that would be the best course of action.

**Comment by alcohol** [comment]
But please, keep in mind that this is a warning, not an error. If you understand the reasoning / technical details behind it, you'll see that it's not a major issue. In **most** cases, it simply means you have overlapping autoload definitions (which resolves into duplicates when you `optimize` them).

**Comment by GrzegorzDrozd** [comment]
This is a serious problem for me. I used git bisect to locate this commit as a source of a regression: i have autoload-dev pointing to different directory with overrides for some of the classes and now this warning shows me that composer found duplicates BUT it will use one from vendor not from autoload-dev config. Can it use autoload-dev with higher priority ?

**Comment by alcohol** [comment]
It sounds to me like you are misusing (abusing) the purpose of autoload and
autoload-dev respectively. Maybe consider implementing these overrides in a
proper way?

**Comment by GrzegorzDrozd** [comment]
I am developing a library that is used in a project. I had a project composer.json autoload-dev point to a library home so that I don't have to push and update code on every change. What is a proper way then?

**Comment by Seldaek** [comment]
@GrzegorzDrozd you could for example include that library's vendor/autoload.php file after including your project's and then it should load the classes first.

**Comment by GrzegorzDrozd** [comment]
Is there a way for me to know, in the /vendor/autoload.php file, if the project is in "developer" mode or not ?

**Comment by alcohol** [comment]
That depends on what you consider to be developer mode. Most times people configure this via some config setting (be it in json, xml, yaml or .env). Composer shouldn't not really be a part of that. It's a tool that makes development processes easier and faster (managing dependencies and such), but I would recommend against making it a part of your application logic.

**Comment by GrzegorzDrozd** [comment]
Yes it does. For example with --dev and --no-dev flags :) And you must admit it is a big difference in contents of a vendor directory and autoload if the project is installed with dev or no-dev flag.

**Comment by alcohol** [comment]
Yes. But I think you misunderstood the point I am trying to make. --dev is used to install libraries you might depend on during development (such as phpunit, codesniffer). Things you normally would not deploy to production. It shouldn't be used to "overload" regular libraries.

**Comment by GrzegorzDrozd** [comment]
But my library only lives in other projects. And as I mentioned: i need to develop/test it. So for that I am deploying it on my machine, in dev mode, and them change the code and ... develop. I need my project to know that it is in dev mode and to load additional class map. I would like to have a simple flag/constant for example than changing the code manually every time it goes to deployment - to remove that additional requirement from outside of the vendor. 

Also this is a pretty big change, you can say it is a backward compatibility break and a regression, yet there were no warning, no version released. You ask us to update composer every 30 days and you are breaking stuff in a process without warning :( It took me several hours to pin point that change :(

**Comment by alcohol** [comment]
Well.. Composer isn't a stable product yet. Also, you are relying on undocumented and inconsistent behaviour, which was never intentionally designed to be used like that.

**Comment by alcohol** [comment]
I still feel like your workflow could be improved. If your library is only used in other projects, then it deserved a proper API/interface definition. And it's easy to write a proper test suite once you have defined that. No need to install your library in another project to "test" it then.

**Comment by GrzegorzDrozd** [comment]
@Seldaek my library does not have its own vendor directory. It has composer with dependencies but it is required by other projects and it lives only there. (So it does not have "vendor/autoload.php" on it owns). 

Also putting it first on autoload classmap list also does not help. Vendor dir is always first in the scan for class map.

**Comment by GrzegorzDrozd** [comment]
@alcohol But what about a simple development? Simple F5 in the browser? It will force us to work in TDD and ... "Composer shouldn't not really be a part of that. It's a tool that makes development processes easier and faster (managing dependencies and such)" :)

**Comment by alcohol** [comment]
Ehm, ok. It sounds like it shouldn't be a library by itself then to begin with. Why not just make it a part of your application?

**Comment by GrzegorzDrozd** [comment]
It is a common code that is used across multiple applications: api, web and command line for background processing/workers. It is like a core of few applications. 

I noticed that order of included libraries, classmap generation is an problem that occur quite often among the issues here. Maybe we can add a directive to a composer schema? It would solve the issue once and for all ?

{
"autoload-priority": {
    "autoload-dev":{
         "psr-4" : <weight>,
         "psr-0": <weight>,
         "classmap": <weight>
    },
    "autoload":{
         "psr-4" : <weight>,
         "psr-0": <weight>,
         "classmap": <weight>
    }
}

And the weights would be global counter ? from 99 to -99 for example ? I might get on to it in next few days if there will be will to discuss/merge such solution ?

**Comment by seyfer** [comment]
Have same error now

```
php composer.phar dump-autoload -o
Generating optimized autoload files
Warning: Ambiguous class resolution, "SQLBuilder\Universal\Syntax\AlterTableDropIndex" was found in both "/home/seyfer/www/site.loc/vendor/corneltek/sqlbuilder/src/SQLBuilder/Universal/Syntax/AlterTableDropIndex.php" and "/home/seyfer/www/site.loc/vendor/corneltek/sqlbuilder/src/SQLBuilder/Universal/Syntax/AlterTableDropForeignKey.php", the first will be used.
Warning: Ambiguous class resolution, "SQLBuilder\Exception\IncompleteSettingsException" was found in both "/home/seyfer/www/site.loc/vendor/corneltek/sqlbuilder/src/SQLBuilder/Exception/CriticalIncompatibleUsageException.php" and "/home/seyfer/www/site.loc/vendor/corneltek/sqlbuilder/src/SQLBuilder/Exception/IncompleteSettingsException.php", the first will be used.

```

Proposed above priorities solution looks good.

**Comment by stof** [comment]
@seyfer this is not an error at all. It is just a warning message telling you that you *may* face issues if the selected class definition is not the one you expect to be used (better than silently handling this case).

**Comment by stof** [comment]
and in this case, it probably highlights mistakes in the library btw. I don't think the duplicate class name was intended. Rather a copy-paste mistake

**Comment by keradus** [comment]
I am facing this concern and all refs are linking this issue in the end.
let say I want to install symfony 3.1.x, but with console component locket to 3.0.x and yaml to 3.2.x:
`composer require symfony/symfony:~3.1.0 symfony/console:~3.0.0 symfony/yaml:~3.2.0 -o`

```
$ composer info -D
symfony/console v3.0.9  Symfony Console Component
symfony/symfony v3.1.10 The Symfony PHP framework
symfony/yaml    v3.2.12 Symfony Yaml Component
```

I got warnings like:
```
Warning: Ambiguous class resolution, "Symfony\Component\Console\Output\OutputInterface" was found in both "/tmp/asd/vendor/symfony/console/Output/OutputInterface.php" and "/tmp/asd/vendor/symfony/symfony/src/Symfony/Component/Console/Output/OutputInterface.php", the first will be used.

Warning: Ambiguous class resolution, "Symfony\Component\Yaml\Dumper" was found in both "/tmp/asd/vendor/symfony/yaml/Dumper.php" and "/tmp/asd/vendor/symfony/symfony/src/Symfony/Component/Yaml/Dumper.php", the first will be used.
```

I am **fine** with those warnings, my question is:
Does the order of solving what will be autoloaded stable? Would I always get loaded console 3.0 and yaml 3.2, or it may happen that I will end up using 3.1 from root symfony package ?

**Comment by alcohol** [comment]
What you are doing is unsupported. It only "works" because of the way the solver deals with the replace directive. Autoloading goes in first found first served order (which is generally alphabetical order). So for the yaml component, the classes from symfony/symfony would be used. But for the console component, symfony/console comes before symfony/symfony.

**Comment by alcohol** [comment]
See #3754 for more discussion on the replace issue.

**Comment by keradus** [comment]
I was exactly expect this behaviour that you described and crossed out, yet then saw it's working differently.
Thanks for link, I'm eager to have it figured out, yet my question from this thread remains valid .

**Comment by prafful-panwar** [comment]
Warning: Ambiguous class resolution, "Ambiguous class" was found in both "File1" and "File2", the first will be used.
but there is no File2. how to resolve this.
I tried with cleared all cache, composer dump-autoload but still same Warning is coming after composer update command.
Thanks in advance

**Comment by pedroskakum** [comment]
I have the same problem: "Warning: Ambiguous class resolution". What is the solution?

**Comment by ghizlanekhattari** [comment]
i have same ya problem ;'Warning: Ambiguous class resolution, "Fruitcake\Cors\HandleCors" was found 2x: in "C:/xampp/htdocs/ng4Laravel55/vendor/barryvdh/laravel-cors/src/HandleCors.php" and "C:/xampp/htdocs/ng4Laravel55/vendor/fruitcake/laravel-cors/src\HandleCors.php", the first will be used.; i need help
