### ISSUE TITLE
Allow adding repository other than packagist on composer init command

### ISSUE THREAD

**Issue by reyostallenberg** [composer/composer#4200]
When I want to use 'composer init' for non packagist packages, I have to complete the init proces, add my private repository and add a required package afterwards. I can't search my private list as I can when executing 'composer require'. It would be nice if I could do this at once. Like I can with 'composer create-project some-vendor/some-package --repository-url=http://myrepository.org'

Is this a good idea? Then I will produce a PR for it.

**Comment by alcohol** [comment]
Can you elaborate? Cause I'm not sure I understand what you're trying to achieve.

**Comment by reyostallenberg** [comment]
I shall try to make myself more clear.
In my example I have a private satis repository server (for example http://myrepository.org) and I want to init a new project that requires one of my private packages (for example my-vendor/my-private-package). 

Currently I have to execute 3 commands to init my new project like that:
1. 'composer init' and answer all the questions in interactive mode (but I can't select my-vendor/my-private-package in this interactive mode as it isn't on packagist)
2. composer config repositories.myrepository composer http://myrepository.org
3. composer require my-vendor/my-private-package

I would like to do it like this:
'composer init --repository-url=http://myrepository.org' and answer all the questions in interactive mode, being able to select my-vendor/my-private-package in this interactive mode when defining the requirements

**Comment by alcohol** [comment]
So in what regard does the currently `--repository-url` option fall short?

**Comment by reyostallenberg** [comment]
It's not an option in 'composer init'

**Comment by alcohol** [comment]
I thought we were talking about `create-project`, sorry.

**Comment by reyostallenberg** [comment]
All right, I would like to have it in the same manner as in create-project, but as optiojn on init

**Comment by alcohol** [comment]
I see. One way I could think of right now would be to add an option/argument to specify additional repositories, which adds these to the repos which `getRepos()` returns. That should be all that is necessary really.

**Comment by alcohol** [comment]
I'll write up a PR. Can you test it for me if I do so? I don't have any custom repositories myself.

**Comment by reyostallenberg** [comment]
That's nice. I will test it.

**Comment by alcohol** [comment]
There you go. Just clone composer/composer, then use:

```
/path/to/clone/bin/composer init --repository-url=X
```

**Comment by reyostallenberg** [comment]
Thank you, basicly it's working, so I can search packages in my private satis server.

There still one thing that's not correct, the repostiry is not listed in the 'repositories' setting in the resulting composer.json, so a 'composer install' afterwards will fail.

**Comment by alcohol** [comment]
Ah, right, good call. I'll look into that.

**Comment by alcohol** [comment]
Adding the repository to the composer.json is not that easy.. have to determine type and what not. Will look more into this tomorrow.

**Comment by Seldaek** [comment]
You can now pass --repository which can be a simple URL to a composer repository, or a full json object including any repo option available: like `{"type":"...", etc..}` for vcs repos and such.
