### ISSUE TITLE
Using error suppression operator with @date_default_timezone_get() - hides rare, but fatal php error with no further output

### ISSUE THREAD

**Issue by yurakaras** [composer/composer#4203]
### No output while running the `php composer.phar`, with dozens of various settings, cause of using the @ operator with @date_default_timezone_get()

I had no success to get some output from composer.phar, on debian linux with php
5.5.21-1+deb.sury.org~precise+2

 
`curl -sS https://getcomposer.org/installer | php -- --check` 
output was "All settings correct for using Composer" 

*Contrary - i tested few phar files from popular CMS/CMF - they'd worked fine - with output and executing commands.*

While i can't at the moment update php version, and still addicted (in goodway) to Composer, so i stucked with old shared hosting. Recently i made more deep reversing of composer.phar on that debian machine, extracting the composer.phar and ran 'bin/composer' "by hand".

Appeared that i always had **php fatal error, which Composer was always hiding from me**.

*I know it's incorrect setup of php by server admin.*

**Fatal error: date_default_timezone_get(): Timezone database is corrupt - this sh
ould *never* happen! in /home/karas/tmp2/c/src/Composer/Console/Application.php
on line 66**

**Here is the code src/Composer/Console/Application.php**

```
  public function __construct()
    {
        if (function_exists('ini_set') && extension_loaded('xdebug')) {
            ini_set('xdebug.show_exception_trace', false);
            ini_set('xdebug.scream', false);
        }
        if (function_exists('date_default_timezone_set') && function_exists('date_default_timezone_get')) {
            date_default_timezone_set(@date_default_timezone_get());
        }
        parent::__construct('Composer', Composer::VERSION);
    }
```

**If someone with php timezone corrupted/wrong setup, he would no simple hint, just silence**

Proposal - remove the silence operator, and either stop on Fatal Error, or if the version of PHP is new, process it through some error handler - and give user the output.

p.s.

I know this is rare issue, with more then 5 years of PHP i'd never that this fatal error exists.

Thanks

**Comment by alcohol** [comment]
I'm not sure what a decent alternative would be though. If you still have access to that environment, can you see if wrapping the `date_default_timezone_get()` call in a try/catch statement provides better results?

**Comment by stof** [comment]
the issue is that without the silencing operator, any setup which does not define the timezone in the php.ini would get a warning here (and the default php.ini file does not define it)

**Comment by yurakaras** [comment]
@alcohol Well i've tried few options - 
```error_get_last()```
Nothing

```ini_set('track_errors',1);
    global $php_errormsg;
...
     $result = @date_default_timezone_get();
        if (!$result) {
            echo '<p>Error' . htmlspecialchars($php_errormsg) . '</p>';
        }
...
   var_dump($php_errormsg);
```
Nothing

`try catch` 
Nothing

May be because custom error handler was already set up... Dunno

@stof I understand the reason to use silencing operator (even it's often consider bad approach imho), the warning about no default timezone is far much popular, than **Timezone database is corrupt - this sh
ould never happen!**

**Comment by legoktm** [comment]
`@` will suppress any error messages related to fatals, but your code will still fatal. In MediaWiki, we use [at-ease](https://github.com/wikimedia/at-ease) to suppress expected warnings, but still let fatals through.

**Comment by slbmeh** [comment]
change the error reporting level around that statement perhaps?
