### ISSUE TITLE
Failed to download files - Failed to clone git

### ISSUE THREAD

**Issue by Starfish777** [composer/composer#4204]
I am trying to install composer using the command line in the root, but I am getting many "Failed" exception messages. In my search for the solution. I have tried deleting the "Vendor" folder and trying to install again, but I get the same failure messages. I also get an HTTP/1.1 404 Not Found for the [Composer\Downloader\TransportException] --> https://api.github.com/repos/lespoilus/spyc/zipball/5a5bacdef1e514bdbb30701f13d9867140a6a21b (file could not be downloaded).  

I'm using Apache for Windows, PHP 5.6.10. Composer
![composer-fail-errors](https://cloud.githubusercontent.com/assets/13037090/8462825/6d3a7906-2004-11e5-8d31-e658ed84c2c3.png)

**Comment by alcohol** [comment]
Well for starters, it would probably help a lot if you installed Git properly. Could you give that a try?

**Comment by Starfish777** [comment]
Hi alcohol. Thanks for your support. I have installed the Git, but still having trouble with the cloning. I'm really new to Git so I thank you for taking the time to help me. Maybe this will also help someone else too. Should I be using the Git Shell instead of the PowerShell? I used the PowerShell, changed directory to my root and then used the following command: git clone git://github.com/jdorn/php-reports.git.  Here are my results:
![2ndtrygitclone](https://cloud.githubusercontent.com/assets/13037090/8476831/2fd59912-2093-11e5-848e-bbb45fe8a3d6.png)

**Comment by Starfish777** [comment]
Hi alcohol. Thanks for your support. I was able to install Git and used the Git Shell to follow all of the "Getting Started" instructions. It is working now. I'm very new to Git so sorry for the newbie questions. :) Hopefully, it can help someone else just starting out with Git too.
