### ISSUE TITLE
ssh2 option for using the SSH agent for authentication?

### ISSUE THREAD

**Issue by melon-babak** [composer/composer#4206]
```json
"repositories": [
        {
            "type": "composer",
            "url": "ssh2.sftp://satis@satis.example.com",
            "options": {
                "ssh2": {
                    "username": "satis"
                }
            }
        }
    ]
```

Is there an option to make composer use the agent for SSH authentication?

(I think it would need to call ```ssh2_auth_agent()``` after establishing a session with ```ssh2_connect()```)

**Comment by alcohol** [comment]
Not currently, no. Implementing this is no small task I imagine.

**Comment by melon-babak** [comment]
Can someone please point me to where the SSH connection gets created? I grepped everywhere but couldn't find SSH related code. Is it even in ```composer/composer``` source?

**Comment by alcohol** [comment]
Well it doesn't, not really no. For the most part, it just calls git directly with either a git, https or ssh url. If the user running composer has his agent setup and everything, it actually should just work out of the box.

**Comment by melon-babak** [comment]
On this page,

https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md

> Example using a custom repository using SSH (requires the SSH2 PECL extension)

The SSH2 PECL extension requirement made me think that it must be establishing SSH connections somewhere...

**Comment by alcohol** [comment]
I honestly have no idea..

/cc @Seldaek maybe legacy documentation? A remnant of a past long forgotten? Can you shed some light on this?

**Comment by Seldaek** [comment]
As far as I know the ssh2 pecl ext just defines a few stream wrappers as per https://secure.php.net/manual/en/wrappers.ssh2.php#refsect1-wrappers.ssh2-options so you can use it and the ssh connection is opened by the stream wrapper. Whether it supports ssh agent or not I have no clue sorry.

**Comment by Seldaek** [comment]
Ok it seems it can be done if you do an actual connection with http://php.net/manual/en/function.ssh2-auth-agent.php but maybe not with the stream wrapper..

**Comment by Seldaek** [comment]
Closing as it's really an niche feature that's unlikely to get implemented. If someone does it we can rediscuss.
