### ISSUE TITLE
Unexpected char and parse error in installer input are fatal

### ISSUE THREAD

**Issue by mpulier** [composer/composer#4215]
Could not install via ssh in linux remote system (Daily Razor).

gpulier@psymeet.com [~]# curl -sS https://getcomposer.org/installer | php

Warning: Unexpected character in input:  '\' (ASCII=92) state=1 in - on line 574

Parse error: syntax error, unexpected T_SL in - on line 849

**Comment by Seldaek** [comment]
I think that means your default `php`  on the command line is older than 5.3?
