### ISSUE TITLE
Composer needs npm like repo model

### ISSUE THREAD

**Issue by steelbrain** [composer/composer#4216]
The whole architecture of it is invalid, You download manifest files of all the packages of the world and then extract what you need. I mean seriously? I recently moved to a mountainy area and the internet speed here is capped at 50kbps, while npm works great for me, composer does not, it always times out after several minutes downloading it's provider json files like `https://packagist.org/p/provider-2015-04$da5412fe8928dca28189cf2ed14d0101542c6b35e910db4acd695aa6efe30c0e.json`
I fail to see how difficult it would be to implement a central server who serves all the requests with appropriate information. I mean a $20 server from DO with a double threaded node js http server will be able to serve millions daily.

**Comment by pborreli** [comment]
You could have some valid points but being agressive close the door to any discussion, you suck. Enjoy your weekend.

**Comment by steelbrain** [comment]
I didn't mean it in an aggressive way, I meant it in a depressed manner, I am sorry for being like that.

**Comment by HiroshiHorie** [comment]
first of all, your internet connection sucks.

**Comment by steelbrain** [comment]
@HiroshiHorie I know right :smile:

**Comment by steelbrain** [comment]
and thank you for just telling me that my internet sucks and not proposing a solution :)

**Comment by alcohol** [comment]
While you may raise a valid point (it's probably not a perfect solution), saying that it sucks and not contributing any useful solutions doesn't help us much either. If you want to get a discussion started, there are better ways to do so.

Now I personally am not experienced enough in this field to come up with elegant solutions to a distribution problem such as this one. But I can imagine that offloading computational processes to Packagist would put a severe strain on server resources considering the amount of requests it processes.

On top of that, it is hard to change an existing architecture. If the Packagist API were to change, Composer would have to change too, but Packagist would still also have to remain backwards compliant for the many **many** users out there that don't update their Composer binary on a regular schedule.

There are a lot of things to take into consideration here.

On a brighter side of the discussion, this is an issue that has been taken into consideration and steps are being made to improve it. See #3994 and #4163.

**Comment by steelbrain** [comment]
@alcohol Thank you for pointing at those PRs. While it's a good thing that composer's network efficiency is being worked on, A centralized server would be even better, and about backward compatibility; I don't expect this change to break backward compatibility as the users who don't upgrade composer will use the previous architecture and new users will use the new one. 
and about traffic, I agree that the repo will get loads of traffic, but like I said, a simple nodejs http multi-threaded server in just a few or maybe less than a hundred lines of code would work great and will be able to serve millions if properly tweaked. It's purpose is gonna be very specific so it should eat those requests like a piece of cake.

**Comment by alcohol** [comment]
@steelbrain well like I said, I don't have enough experience to comment on this myself.

It might be interesting to see if we could open a dialog with the maintainers of npm and maybe get some insight into how their architecture works and what benefits and/or caveats there might be.

Right now Packagist runs on PHP, and you see view the source @ [composer/packagist](/composer/packagist).

**Comment by steelbrain** [comment]
@alcohol I have been working with both php and nodejs for years and here's what I've experienced so far

 - Use NodeJS for stuff that you can put on the event loop and make operations simpler for yourself (like tcp, http and stuff)
 - Use PHP for everything else

Is `npm`'s architecture open source? @iarna 

Do you have any advice for us from your experience with `apm`? @thedaniel

**Comment by aaukt** [comment]
packagist.org IS the centralized server and AFAIK in most cases it is just serving plain files, because all the json files are physically available on the server. maybe this can be speeded up with a varnish/nginx.

there are multiple efforts to parallelize the download process of metadata/dist and cloning the repositories (one of the advantages of npm/node), but that won't help much with a bad connection.

apart from that npm and the registry had/have their fair share of problems too ;)

**Comment by steelbrain** [comment]
@aaukt I am against serving all the registry of the world to user when the user only wants to install one package, and I am sure I'm not alone :)
Parallelizing the processes or implementing nginx or varnish cache will not reduce the downloaded bytes, would it?
It isn't really that difficult to implement a structure like that, 'cause packagist already has most of it done, it just needs an update in the serving method, nothing complex.

**Comment by alcohol** [comment]
@steelbrain Packagist doesn't serve "all the registry of the world". It does serve a few master files which it needs to be able to do dependency resolving. Even with just once package it still needs to know what is actually available.

@aaukt Adding a Varnish cache would do little to improve the situation on the client side. Also, the files update quite frequently, especially for the more popular (development wise) projects. So then we'd have to worry about properly invalidating cached results. On the server side things are OK right now as far as I know. The only thing @Seldaek is looking to improve is pre-gzipping files so that Nginx doesn't have to do it on the fly (as in, have both a .json and json.gz available).

**Comment by aaukt** [comment]
@steelbrain sure it won't help with reducing download size, but so won't just putting stuff "in the event loop" in a few lines of code.
i believe composer devs put quite some thought into this and it's not an easy issue to cover caches/cache-busting etc. but maybe this can be solved with a 5$ DO instance and a small node server.

**Comment by steelbrain** [comment]
@aaukt I am not sure you understand the problem here, caching won't help here even by a 0.01% 'cause the download will still happen from the internet and my idea is to save those bytes.
My suggestion about "the event loop" and a small DO instance was, that packagist already uses mysql for repo storage, It'll be super-easy to serve the user only what it needs, without having a server like nginx in the middle thus improving RPS (Requests per second). Here's what it might look like
```js
var HTTP = require('http')
var URL = require('url')
var Driver = require('mariasql-promise')
var MySQL = new Driver
MySQL.connect({
  host: '127.0.0.1',
  user: 'root',
  password: '',
  db: 'packagist'
}).then(function(){
  HTTP.createServer(function (request, response) {
    var url = URL.parse(request.url, true)
    Promise.resolve().then(function() {
      if (!url.query.name || !url.query.name.length) throw new Error("Please specify a package name")
      return MySQL.query("Select repo from packages where name = :name LIMIT 1", {name: url.query.name})
    }).then(function(results){
      if(!results.length) throw new Error("No package found with information specified")
      response.writeHead(200, {'content-type': 'application/json'})
      response.write(JSON.stringify({status: 1, 'repo': results[0].repo}))
    }).catch(function(error){
        response.writeHead(400, {'content-type': 'application/json'})
        response.write(JSON.stringify({status: 0, message: error.message}))
      })
    response.end()
  }).listen(8124, "0.0.0.0")
})
```

**Comment by iarna** [comment]
The older npmjs couchdb architecture is open source (https://www.npmjs.com/package/npm-registry-couchapp). I'm not sure that's the hard problem here, but of course composer folks would be welcome to use it if they wanted to.

TBH, it's plausible that composer might be able to publish *to* the npm registry, though probably only after we get better organizational tools in place. (Like, if you're searching for javascript modules, you probably don't want php and vice versa.) It wouldn't be my decision, but it also doesn't sound unreasonable either.

**Comment by aaukt** [comment]
@steelbrain i do understand the problem. i meant the client-side caching and validation (that's why these hashes are there).
i just don't think the server is the bottleneck but the architecure that composer currently uses, and i believe it is not that easy to change that.

don't get me wrong, i'm all for making it faster, i was just a little put of by your initial issue title and the fact that the first thing you suggets for the php-package manager is to use node :smile: but no hard feelings, i get that things like this can be frustrating with a connection like yours.

**Comment by steelbrain** [comment]
@aaukt I am not the person that hits everything like a nail when he has a hammer in hand :)
I use and suggest what's efficient and best for solving the problem under discussion.

**Comment by steelbrain** [comment]
@iarna Your idea of publishing the packages to npm is quite appealing, I mean npm now supports tags and we could store all the composer packages under `#composer` or something, it'll help during the search.
Does npm allows a search with a tag AND a term?

**Comment by alcohol** [comment]
What benefit would that provide us? Where does Composer/Packagist fail whereas npm shines? In other words, this sounds like an area to look into perhaps, but please elaborate. Cause I am not familiar with the architecture of npm.

**Comment by steelbrain** [comment]
@alcohol the main benefit would be maintainability of composer itself and it's packages, You will be saved from re-inventing the wheel and will choose a package manager that handles more than a billion package installs monthly and will provide us the amazing `npm` cli utility.
We could have a function named `import` ('cause require is already defined by php runtime) that is provided by composer to it's consumer that imports some exported interfaces of a module like.
```hack
$vultr_api = import('vultr_api')
$vultr_api->createServer(['DCID' => 2, 'OSID' => 178])
```
composer will then paths and require that module's main file, we will keep the autoloading to the modules themselves or provide them an easy way to do that, like we're doing now.
Publishing a new version will be a piece of cake, all you have to do is bump version and run `npm publish`, a utility that most already have installed. You don't have to have any tags for it.
Man! I am starting to love the concept of it already!

**Comment by alcohol** [comment]
I'm sorry, but most of what you said made little sense to me. Maybe I'm missing some context here, but I don't see how npm could replace Composer. You have to realise that Composer does a lot more than just dependency solving. There are plugins and installers for frameworks, features that npm simply cannot replace out of the box. It's too big of a change to even remotely consider it.

**Comment by steelbrain** [comment]
I guess You are right. The change I've requested will break composer on a lot of places. What is your opinion about having a `ppm` (PHP Package Manager) that is composer, but with npm. So you can keep the composer users happy and those who want the coolness of that can use it.

**Comment by alcohol** [comment]
I think we are drifting off-topic. Your main issue is the amount of information that Composer has to download to be able to do what it does best, solving dependencies. As I pointed out earlier, efforts are being made to reduce the amount of data that is transferred over http. This should be a good step in the right direction. Lets focus on that for now.

**Comment by steelbrain** [comment]
Right. Thanks for those efforts to reduce network usage. For the love of Mother Portability, I'm gonna invent that PPM when I have enough time.

**Comment by stof** [comment]
And you need to understand also that some architectural choices done in NPM are totally incompatible with constraints necessary for PHP. PHP requires class and function names to be unique. This means it is totally impossible to install several versions of the same package. This is why Composer has a complex dependency resolution algorithm to find versions fulfilling the requirements of all packages. NPM on the other hand can install multiple versions of the same packages (or many times the same version of a package btw, which is changing in npm 3 to make installed dependencies much less messy).

and btw, moving the dependency resolution to the server would make it impossible to use other sources than Packagist, which would break lots of cases, especially for big companies which have lots of private packages.

and regarding using node.js on the server, it is not worth it. All files downloaded by Composer from Packagist are static json files (generated by a cron). And I doubt a node.js app will actually serve them faster than Nginx does. Nginx is very good at serving static files.

**Comment by seydu** [comment]
Thank you @stof and @alcohol
