### ISSUE TITLE
Checking composer.json: FAIL - Why?

### ISSUE THREAD

**Issue by kotoponus** [composer/composer#4222]
Why do I get this error message?  I can see it clearly read into the composer.json as it does not give me the license warning anymore by having one.  This may seems basic, and I guess it must be (sorry), but I can't see for the life of me what can cause it.  I would be grateful if you can please give me a pointer.

>ubuntu$ composer diag
>**Checking composer.json: FAIL**
>the property name is required
>the property description is required
>Checking platform settings: OK
>Checking git settings: OK
>Checking http connectivity to packagist: OK
>Checking https connectivity to packagist: OK
>Checking HTTP proxy: OK
>Checking HTTP proxy support for request_fulluri: OK
>Checking HTTPS proxy support for request_fulluri: OK
>Checking github.com rate limit: OK
>Checking disk free space: OK
>Checking composer version: FAIL
>You are not running the latest version

>ubuntu$ ls -la
>total x
>drwxr-xr-x 11 6226 6226  4096 Jul  7 14:57 .
>drwxr-xr-x 16 root root  4096 Jul  6 16:50 ..
>...
>-rw-rw-rw-  1 root root    84 Jul  7 14:57 composer.json
>...

>ubuntu$ vim composer.json
>{
>    "license": "MIT",
>    "require": {
>        "monolog/monolog": "1.0.*"
>   }
>}

BTW it is a global install of Composer and the composer.json sits at /var/www/folder/.

**Comment by alcohol** [comment]
Run `composer validate` to see why it fails. It's not necessarily something to worry about. It basically checks if your composer.json validates against the schema.

**Comment by kotoponus** [comment]
Hi, alcohol,
Thanks for your reply - I have tried the validation and I got the following, which matches to your comment.

>ubuntu$ composer validate
>./composer.json is valid for simple usage with composer but has
>strict errors that make it unable to be published as a package:
>See https://getcomposer.org/doc/04-schema.md for details on the schema
>the property name is required
>the property description is required

Can I be cheeky and ask you why I get:

>ubuntu$ composer diag
>...
>**Checking composer version: FAIL**
>**You are not running the latest version**

when I actually seems to be passing all the connectivity and proxy connections?

**Comment by kotoponus** [comment]
Am I right to say the following command updates the composer version?

>ubuntu$ composer self-update

In return I get:

>ubuntu$ composer self-update
>Updating to version dbdd4978a7dd4cd29d0d7dfc912aab404245b736.
>    Downloading: 100%         
>                                                                              
>  [ErrorException]                                                             
>  rename(/home/kotoko/.composer/cache/composer-temp.phar,/usr/local/bin/composer): Permission denied                                                      
> self-update [-r|--rollback] [--clean-backups] [--no-progress] [version]

My installation is global, so I take running without sudo would do it?

**Comment by kotoponus** [comment]
>ubuntu$ sudo composer self-update
>[Composer\Downloader\TransportException]                                     
>The "https://getcomposer.org/version" file could not be downloaded: failed to open stream: >Connection timed out
>self-update [-r|--rollback] [--clean-backups] [--no-progress] [version]
Hum.

**Comment by kotoponus** [comment]
>drupal:/usr/local/bin$ ls -la
>total x
>drwxr-xr-x  2 root root    4096 Jul  7 09:19 .
>drwxr-xr-x 12 root root    4096 Feb  7  2014 ..
>-rwxr-xr-x  1 me me 1112650 Jul  7 09:17 composer

Will this do?  If I chown it to: root:root, then I should run self-update as sudo.  But if I do that, I am still getting the connection time out error...

**Comment by alcohol** [comment]
Hey, running `composer self-update` with sudo should do the trick. But it's weird that you are getting a timeout. Could you retry it? Does it consistently timeout?

**Comment by alcohol** [comment]
And yes you are right to assume that `self-update` updates composer.

**Comment by kotoponus** [comment]
>me@/var/www/somesite$ whoami
> me

>me@/var/www/somesite$ ls -la /usr/local/bin/
>total x
>drwxr-xr-x  2 root root    4096 Jul  7 09:19 .
>drwxr-xr-x 12 root root    4096 Feb  7  2014 ..
>-rwxr-xr-x  1 root root 1112650 Jul  7 09:17 composer
>me@ubuntu$ sudo composer self-update
>[sudo] password for me:
>[Composer\Downloader\TransportException]
>The "https://getcomposer.org/version" file could not be downloaded: failed to open stream: Connection timed out
>self-update [-r|--rollback] [--clean-backups] [--no-progress] [version]

>me@/var/www/somesite$ composer self-update
>[Composer\Downloader\FilesystemException]
>Filesystem exception:
>Composer update failed: the "/usr/local/bin/composer" file could not be written
>self-update [-r|--rollback] [--clean-backups] [--no-progress] [version]

>me@/var/www/somesite$ sudo chown me:me /usr/local/bin/composer
>me@/var/www/somesite$ ls -la /usr/local/bin/
>total x
>drwxr-xr-x  2 root   root      4096 Jul  7 09:19 .
>drwxr-xr-x 12 root   root      4096 Feb  7  2014 ..
>-rwxr-xr-x  1 me me 1112650 Jul  7 09:17 composer

>me@/var/www/somesite$ sudo composer self-update
>[Composer\Downloader\TransportException]
>The "https://getcomposer.org/version" file could not be downloaded: failed to open stream: >Connection timed out
>self-update [-r|--rollback] [--clean-backups] [--no-progress] [version]

>me@/var/www/somesite$ composer self-update
>Updating to version 5d7036e7403377e4c06ecae1e52139fd00809246.
>Downloading: 100%
>[ErrorException]
>rename(/home/me/.composer/cache/composer-temp.phar,/usr/local/bin/composer): Permission denied
>self-update [-r|--rollback] [--clean-backups] [--no-progress] [version]

>me@/var/www/somesite$ ls -la /home/me/.composer/cache/
>total 20
>drwxrwxr-x 4 me me 4096 Jul  9 08:30 .
>drwxrwxr-x 3 me me 4096 Jul  8 14:21 ..
>drwxrwxr-x 2 me me 4096 Jul  7 09:38 files
>-rw-rw-r-- 1 me me   13 Jul  7 09:38 .htaccess
>drwxrwxr-x 3 me me 4096 Jul  7 09:38 repo

Should you see composer-temp.phar in above directory?  The last self-update seems like the nearest to complete.  Any thoughts?

**Comment by alcohol** [comment]
I honestly don't understand why you get timeouts as root but it downloads just fine as a regular user. Might be some weird security settings on your environment. You could try a `sudo mv ~/.composer/cache/composer-temp.phar /usr/local/bin/composer`.

**Comment by alcohol** [comment]
For a long term solution though I would investigate why the user root cannot download the composer.phar from getcomposer.com.

**Comment by kotoponus** [comment]
Ah good point - since I have not got the file....

>me@/var/www/somesite$ touch ~/.composer/cache/composer-temp.phar
>me@/var/www/somesite$ mv ~/.composer/cache/composer-temp.phar /usr/local/bin/composer
>mv: cannot move ‘/home/kotoko/.composer/cache/composer-temp.phar’ to ‘/usr/local/bin/composer’: Permission denied

Which is in line with the error I get with the last self-update command without the sudo.

>me@/var/www/somesite$ sudo mv ~/.composer/cache/composer-temp.phar /usr/local/bin/composer

Then it does the job.  So, it seems like sodo should do the job.  As you say, if I can rectify the issue with connection timeout, this should sort the whole thing out.  

Ok, thanks for helping me to narrow down the issue.  I will investigate why I get the connection time out.  Sorry about rather lame nature of this investigation!  Completely new to the composer so I am not too sure what it does when I run some commands behind the scenes.  I am grateful you fill that information in for me!

**Comment by alcohol** [comment]
No problem, we are here to help :-).
I hope you figure out what causes the timeouts.

**Comment by kotoponus** [comment]
When I find out, I will post just in case it may save someone else's time.

**Comment by Seldaek** [comment]
Closing as it's kinda resolved but feel free to add details if you ever get more info.

**Comment by urbanlegion** [comment]
Hi, is this thread still watched?
I have the same error:

```
Checking composer version: FAIL
You are not running the latest stable version, run `composer self-update` to update (37a1e12672a5781__________________dc0fe4537 => 1.0.0-beta2)
```

**Comment by ilbeygi** [comment]
i have this problem when install every package : 
`[Composer\Downloader\TransportException]
The "https://packagist.org/packages.json" file could not be downloaded: fai led to open stream: Connection refused`

please help me !!!

OS : ubuntu 16.04

[stackoverflow](https://stackoverflow.com/questions/50449226/composer-error-when-install-package?noredirect=1#comment87939716_50449226) link
