### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by weboAp** [composer/composer#4225]
composer issuing error
Fatal error: Out of memory (allocated 280494080) (tried to allocate 64 bytes) in
 phar:///home/username/bin/composer.phar/src/Composer/DependencyResolver/RuleSetG
enerator.php on line 126
php 5.6
any tips? or suggestions? thanks

**Comment by alcohol** [comment]
* Give composer more memory.
* Manage your dependencies better.

Please share your composer.json with us.

**Comment by augusteiner** [comment]
~256MB isn't a bit too much?

**Comment by alcohol** [comment]
It can easily consume a 1GiB or more, if your don't manage your dependencies properly.

**Comment by weboAp** [comment]
sorry for the delay
i stripped my composer to the minimum, but still getting the same issue 
my composer.json 

{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "intervention/image": "~2.2",
        "intervention/imagecache": "~2.2",
        "kodeine/laravel-acl": "1.0.x-dev",
        "baum/baum": "~1.1"
        
        
      
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
           
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ],
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "stable"
    },
     "minimum-stability": "stable"
}

in my php ini i had set memory_limit = 1024M      ;
but still getting just 256m but for the packages im pulling

**Comment by staabm** [comment]
Does it work in ithout your artisan hook scripts?

**Comment by weboAp** [comment]
No same issue! but i discovered right now that it depend on the package that's been downloaded, (i guess the size)
took off 
"intervention/image": "~2.2",
"intervention/imagecache": "~2.2",
it worked without issues,
replaced it with laravel/cashier
stopped the download at %30 then gave the same issue.

**Comment by Seldaek** [comment]
Out of memory means out of physical memory, not that the memory limit is too low, so I would advise you increase the available memory of your dev box if you can, and in case you are running this in production make sure you run `install` and not `update` and that you have a composer.lock file committed in the git repo so that install runs with low memory usage.

**Comment by garek007** [comment]
Anyone figure this out? I am having the same problem using CLI access to Web Hosting Hub server.

**Comment by curry684** [comment]
Never run update on your hosting server. Resolve and lock dependencies locally, and either upload your vendor dir or run composer install. Working from a lock requires nearly no memory and is far better practice.

**Comment by garek007** [comment]
curry684 I am running require on the hosting server. If I remove the .json file from the hosting server, will composer use the .lock file?

**Comment by curry684** [comment]
Require is even worse than update. Why would you do that?

**Comment by garek007** [comment]
I was trying to set my site up on the web host first, instead of locally. I need to get something online quickly and then I'll build my Dev environment. Yes, I know backwards, but it is what it is. So what should I use? Drush doesn't have an install command, they use Require only.

**Comment by garek007** [comment]
alright will do it locally then try that. Thanks.

**Comment by curry684** [comment]
It's backwards for sure. It means you are using your prod machine as a dev machine, and that means it should have dev configuration (at least temporarily). That means, to use Composer, a memory limit of at least 1GB for PHP CLI invocations, preferably more, most preferably no limit. It's how it is.

**Comment by garek007** [comment]
Yes I would not normally work this way, but I need an online prototype fast and I don't have time to worry about deployment so I'm doing it this way. I only need a barebones site, and when it's in place, I'll pull everything down and clone. I did set my CLI to 1GB limit with this command _php -dmemory_limit=1G_ but it still didn't work. I'll try locally.

**Comment by curry684** [comment]
That command only overrides the default config for that single invocation, it doesn't change the configuration for subsequent commands using PHP.

**Comment by garek007** [comment]
I tried to do this locally and drush said it needs php 5.6. I had 5.5 on my web server. I think that could be the reason, but I can't test locally because my Wamp is using version 5.5. I tried to manually update but I'm having no luck. Unfortunately, I'm not willing to install the new version of wamp and risk screwing up my dev environment, so for now, I'll have to survive without Drush :(

**Comment by curry684** [comment]
You are aware that PHP 5.5 went end-of-life [over a year ago](http://php.net/supported-versions.php)?

Your dev environment is already screwed if locked to a platform that's not even getting security updates anymore.

**Comment by garek007** [comment]
I was not aware. Once I get through this push, I will update. Thanks.
