### ISSUE TITLE
"composer.phar install" silently ignores vendors updated with --prefer-source

### ISSUE THREAD

**Issue by Pictor13** [composer/composer#4227]
When using the option `--prefer-source` on some *vendor* then `composer.phar install` has no effect on them and, even if these have a specific *git* commit checked out, there will be no restore/checkout of the commit specified in the *composer.lock*.
I can understand the behaviour, but i disagree with silently skipping the repository letting the checked out commit untouched.
For a developer would be nice any kind of message that highlights the vendor commit to be different from the one in *composer.lock* (that would be the expected one after running `./composer.phar install`).

**Comment by alcohol** [comment]
Uh, what is `make install`? Cause it certainly is not a `composer` command.

**Comment by Pictor13** [comment]
Sorry, I mixed stuff. Now should be correct ;)

**Comment by alcohol** [comment]
I'm not sure I fully follow the scenario you are describing. Can you give a step by step description of the actions you are taking, the resulting outcome, and the expected outcome?

**Comment by Pictor13** [comment]
Ok, let's try to explain this:

* I run composer to install *vendors*
* I update one specific vendor using the ```--prefer-source``` option, so that I could have the git repository in my vendor subdirectory.
* I got to this specific vendor repository and checkout another branch, and maybe I add also a new commit
* then I come back to the project root and I run ```composer.phar install```, so I would expect that all the vendors will be reset to the version/commit specified into the *composer.lock*.
* BUT the specific vendor (that I copied as Git repository, and that I changed at step 3) doesn't restore the commit from *composer.lock*. It silently lets everything untouched, not restoring the commit on my deired git-repository/vendor and I don't get what I would expect from the *compose.lock*.

Is the problem more understandable?

**Comment by slbmeh** [comment]
I believe the issue here is related to #1967 #1968 #3265 #3788

**Comment by graste** [comment]
The not adhering to composer.lock is what bothers me as well in such situations. An improvement with at least mentioning the state of the repository is really necessary.

**Comment by Pictor13** [comment]
:+1:

**Comment by Seldaek** [comment]
IMO if you modify your vendors you have to know what you are doing, and if you made a mess an easy way is to wipe the vendor dir and install from lock. Making composer install check every dependency's exact state will add a bunch of code to fix an edge case situation that is ultimately self-inflicted and not something we claim to support.
