### ISSUE TITLE
Pear vendor-alias doesn't work (shame as documentation)

### ISSUE THREAD

**Issue by Garfield-fr** [composer/composer#4237]
Hi,

I would like to install package on pear channel with vendor-alias, but it doesn't work with vendor-alias parameter on repository. I show this information in documentation.

My partial composer:
```
{
    ...
    "repositories": [
        {
            "type": "pear",
            "url": "pear.php.net",
            "vendor-alias": "pear"
        }
    ],
    "require": {
        ...
        "pear/PEAR_Exception": "1.0.0",
        "pear/File_MARC": "1.1.1"
    },
}
```

Error with this config:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package pear/file_marc could not be found in any version, there may be a typo in the package name.
```
Documentation for vendor-alias: https://getcomposer.org/doc/05-repositories.md#custom-vendor-alias

Do you have any suggestion ?

Thank's

**Comment by alcohol** [comment]
"doesn't work" is not a helpful statement.

Does it sit on the couch all day eating Cheetos and ignoring the classifieds?


We can't help you if you don't tell us what your problem is.

**Comment by alcohol** [comment]
If you want to install packages from the default pear channel, you don't need to add any repository definition by the way.

**Comment by Garfield-fr** [comment]
ok,

if i don't specified the vendor-alias and use the default, it work.

Config:
```
{
    ...
    "repositories": [
        {
            "type": "pear",
            "url": "pear.php.net"
        }
    ],
    "require": {
        "pear-pear.php.net/PEAR": "~1.9.5",
        "pear-pear.php.net/PEAR_Exception": "~1.0.0",
        "pear-pear.php.net/File_MARC": "~1.1.1",
        "pear-pear.php.net/Validate_ISPN": "~0.6.1"
    }
}
```
but in folder vendor in my projet, i have a folder "pear-pear.php.net".

To clean this, i would like to have a folder name "pear".

**Comment by alcohol** [comment]
You don't have to clean that up. `vendor/` is not something you have to manage. Don't worry about it.

**Comment by Garfield-fr** [comment]
ok. Thanks
