### ISSUE TITLE
issue in adding new packages in zf2

### ISSUE THREAD

**Issue by navneetccna** [composer/composer#4238]
php composer.phar require ripaclub/zf2-mailman mandrill/mandrill

Package "ripaclub/zf2-mailman" listed for update is not installed. Ignoring.

using latest version
Composer version 1.0-dev (39e6f51bef3a4b148d9f35a0ae7a082e9aed97f4) 2015-07-09 11:04:41

**Comment by Seldaek** [comment]
I can not reproduce this, not sure what exactly you are doing. If you can reproduce it consistently can you paste your composer.json as it is before running the command and the exact command you run? Ideally try to reproduce it from an empty directory.

**Comment by navneetccna** [comment]
yes it is coming consistently

my json is


{
    "name": "zendframework/skeleton-application",
    "description": "Skeleton Application for ZF2",
    "license": "BSD-3-Clause",
    "keywords": [
        "framework",
        "zf2"
    ],
    "homepage": "http://framework.zend.com/",
    "require": {
        "php": ">=5.3.3",
        "zendframework/zendframework": "2.2.*",
        "ripaclub/zf2-mailman": "0.3.0",
        "ripaclub/zf2-mailman": "0.3.0"
    },
    "minimum-stability": "alpha",
    "require": {
        "doctrine/doctrine-mongo-odm-module": "dev-master"
    }    
}

**Comment by navneetccna** [comment]
i added following item using require command

"zendframework/zendframework": "2.2.*",
"ripaclub/zf2-mailman": "0.3.0",

other are old packages

**Comment by Seldaek** [comment]
You have two `"require"` blocks in your composer.json, that is likely to result in errors as the second one will just override the first. Just merge the two lists in one and use `composer validate` to check if your file is valid.

**Comment by navneetccna** [comment]
ok let me try
