### ISSUE TITLE
Repositories in a composer.json dependency

### ISSUE THREAD

**Issue by bmancone** [composer/composer#4242]
Hello,

I'm having a problem with "repositories" defined in dependencies of my project.

### My dependencies

I have the following dependencies (code on private repositories on bitbucket.org) :

> SF2 App -----------[depends on]-------------> Some custom bundle

I added the necessary information in "repositories"  of the composer.json of the App.

> Bundle -------------[depends on]-------------> Some php lib

I added the necessary information in "repositories"  of the composer.json of the Bundle.

### Issue

Unless I specifically add the necessary repository information in the __App composer.json__ , the dependency for the custom php lib cannot be resolved.

I thought that the "repositories" key in the Bundle would be parsed, it is not ?

Thanks

**Comment by jvasseur** [comment]
That's how it's supposed to work : https://getcomposer.org/doc/faqs/why-can%27t-composer-load-repositories-recursively.md

**Comment by bmancone** [comment]
@jvasseur, oh, did not read that part of the faq..thanks!
