### ISSUE TITLE
Platform Config - Emulating PHP version still installs incorrect dependencies

### ISSUE THREAD

**Issue by postalservice14** [composer/composer#4243]
If I tell my composer.json to emulate my production version of PHP. e.g.

```json
platform: {
   "php": "5.3.13"
}
```

When I run `composer require guzzlehttp/guzzle`, it installs version 6.0.2, which doesn't support php 5.3.13.

I would have expected it to either suggest a lesser version that does work with 5.3.13 or throw an error so I can manually set the version to something that will support 5.3.13

**Comment by alcohol** [comment]
Can you show your actual composer json? Complete, not just partial?

**Comment by postalservice14** [comment]
Sure...

```json
{
    "name": "postalservice14/test",
    "platform": {
        "php": "5.3.13"
    }
}
```

Just to note, the PHP version on my laptop (where I'm running the command) has 5.6.10.  Which is what I'm guessing it's using to determine the version of Guzzle to install, instead of the platform config.

**Comment by alcohol** [comment]
Well.... https://getcomposer.org/doc/06-config.md#platform

platform is part of config, you're missing a parent attribute there.

**Comment by postalservice14** [comment]
Ah crap, you're right....  Works as expected.

Thanks.

**Comment by alcohol** [comment]
No problem, we're here to help :-).

**Comment by postalservice14** [comment]
@alcohol is there anyway that you know of to ignore the platform specified for dev dependencies?  Seems like it should only restrict on regular dependencies since it's meant for emulating production systems.

**Comment by alcohol** [comment]
No. But you can also use the `--ignore-platform-reqs` flag for update or install actions.

**Comment by nelson6e65** [comment]
> @alcohol : No. But you can also use the --ignore-platform-reqs flag for update or install actions.

Good to know! :handshake:
