### ISSUE TITLE
composer require should have an --optimize-autoloader switch

### ISSUE THREAD

**Issue by tgr** [composer/composer#4244]
`composer install` has an `--optimize-autoloader` switch which makes it include every class in the classmap, but when it is invoked internally via `composer require` there is no way to trigger it. This is especially problematic for installations using the `classmap-authoritative` configuration flag, which will be broken by any invocation of `composer require` as it will regenerate the classmap but exclude PSR4 and similar files.

So, there should either be an `--optimize-autoloader` switch for `composer require`. (Alternatively, composer could always optimize when `classmap-authoritative` is enabled.)

**Comment by tgr** [comment]
> So, there should either be an `--optimize-autoloader` switch for `composer require`. (Alternatively, composer could always optimize when `classmap-authoritative` is enabled.)

Probably the latter since `composer remove` and whatever else uses the installer internally also breaks authoritative classmaps.

**Comment by Seldaek** [comment]
Fixed by #4245
