### ISSUE TITLE
yiisoft/yii2 2.0.5 Update Problem

### ISSUE THREAD

**Issue by mmshlrfsh** [composer/composer#4246]
Hi,
I run the following commands and both of them made below error:

composer require yiisoft/yii2 2.0.5
composer update

[Composer\Repository\RepositorySecurityException]
The contents of http://packagist.org/p/provider-2015-01$3ef41d7cfe40ac83e7cb4aa1d2fe2ca5f215cb33a897f6c57ddad6d8cd8933a6.json do not match its signature. This should indicate a man-in-the-middle attack.
Try running composer again and report this if you think it is a mistake.

So, what's the problem? Yii2 just released 2.0.5 update today and I cannot update my project.
This problem is mandatory because it's a security update.

**Comment by Seldaek** [comment]
This is usually due to bad proxies that modify files.

**Comment by salang238** [comment]
Tried to install yii2 2.0.5 with composer but failed with the following message:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2 2.0.x-dev requires bower-asset/jquery.inputmask 3.1.* -> no matching package found.
    - yiisoft/yii2 dev-master requires bower-asset/jquery.inputmask 3.1.* -> no matching package found.
    - yiisoft/yii2 2.0.5 requires bower-asset/jquery.inputmask 3.1.* -> no matching package found.
    - Installation request for yiisoft/yii2 >=2.0.5 -> satisfiable by yiisoft/yii2[2.0.5, dev-master, 2.0.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/commit/ed954485239ad88f94bcee80a6a648d7943932f8
