### ISSUE TITLE
Unable to run composer update due to Connection timed out

### ISSUE THREAD

**Issue by mrbinr** [composer/composer#4247]
Hi
Since last friday i'm trying to use composer and i always have a Connection timed out problem ...
I was looking for some answer with gg or here on github but without result ... :( 
When i run :
curl -sS https://getcomposer.org/installer | php
i have this reponse : 
#!/usr/bin/env php
All settings correct for using Composer
Downloading...
Download failed: file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Connection timed out
Downloading...
Download failed: file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Connection timed out
Downloading...
Download failed: file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Connection timed out
The download failed repeatedly, aborting.

As mentionned in some post i have downloaded cacert.pem and run commane
curl -sS https://getcomposer.org/installer | php -- --cafile=cacert.pem
but i get same answer as above

Here is composer diagnose : 
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity: FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: Connection timed out
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: SSL: Handshake timed out
Failed to enable crypto
failed to open stream: operation failed
Checking disk free space: OK
Checking composer version: 
                                                                             
[Composer\Downloader\TransportException]                                                                         
The "https://getcomposer.org/version" file could not be downloaded: failed to open stream: Connection timed out  

I've seem i'm not the only one with problem with composer since some days k0pernikus posted an issue https://github.com/composer/composer/issues/4212 with similar problem 

I really don't know what to do ...
Thanks for your help

Best Regards 
Pascall

diagnose

**Comment by mrbinr** [comment]
additional information i'm using PHP 5.6.7-1 on Debian GNU/Linux 7 (wheezy)

**Comment by mrbinr** [comment]
ok ... i have modified my php.ini by adding lines : 
curl.cainfo=/path/to/ssl-certs/ca-bundle.crt
openssl.cafile=/path/to/ssl-certs/ca-bundle.crt

and now i have this error : 

PHP Notice:  Undefined variable: caBundle in - on line 821

**Comment by mrbinr** [comment]
on line 821 there is : 
if ($configured && strlen($configured) > 0 && is_readable($caBundle) && validateCaFile(file_get_contents($caBundle))) {

and $caBundle is not defined i think i must be changed to : 

if ($configured && strlen($configured) > 0 && is_readable($configured) && validateCaFile(file_get_contents($configured))) {

**Comment by mrbinr** [comment]
when i run wget command to get composer.phar : 
wget https://getcomposer.org/composer.phar
--2015-07-12 10:01:08--  https://getcomposer.org/composer.phar
Résolution de getcomposer.org (getcomposer.org)... 2001:41d0:a:7b19::, 87.98.253.108
Connexion vers getcomposer.org (getcomposer.org)|2001:41d0:a:7b19::|:443...échec: Connexion terminée par expiration du délai d'attente.
Connexion vers getcomposer.org (getcomposer.org)|87.98.253.108|:443...connecté.
requête HTTP transmise, en attente de la réponse...200 OK
Longueur: 1113024 (1,1M) [application/octet-stream]
Sauvegarde en : «composer.phar»

100%[====================================================================================================================>] 1 113 024    408K/s   ds 2,7s    

2015-07-12 10:02:18 (408 KB/s) - «composer.phar» sauvegardé [1113024/1113024]


it seems to have problem with ipV6 ?

**Comment by Seldaek** [comment]
We enabled ipv6 recently, if you have problems please contact your ISP (I guess you're on free.fr? A few people already reported issues there, but I am not sure if anyone contacted free yet). Let them know which domain/IP you are trying to reach and maybe provide them with a traceroute6 output to see where it breaks down.

**Comment by mrbinr** [comment]
Hi,
yes my ISP is free.fr ... :( i don't know if contacting them may help us to find solution ... i gonna try but without hope ...

**Comment by mrbinr** [comment]
It seems that something changes : 

wget  https://getcomposer.org/composer.phar
--2015-07-12 19:19:09--  https://getcomposer.org/composer.phar
Résolution de getcomposer.org (getcomposer.org)... 2001:41d0:a:7b19::, 87.98.253.108
Connexion vers getcomposer.org (getcomposer.org)|2001:41d0:a:7b19::|:443...connecté.
requête HTTP transmise, en attente de la réponse...200 OK
Longueur: 1113632 (1,1M) [application/octet-stream]
Sauvegarde en : «composer.phar»

100%[====================================================================================================================>] 1 113 632   65,6K/s   ds 12s     

2015-07-12 19:19:26 (87,5 KB/s) - «composer.phar» sauvegardé [1113632/1113632]

IPV6 seems to work now ...

**Comment by mrbinr** [comment]
humm .. but composer problem is not solved : 

#!/usr/bin/env php
All settings correct for using Composer
Downloading...
Download failed: file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Connection timed out
Downloading...
Download failed: file_get_contents(): SSL: Handshake timed out
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed
Downloading...
Download failed: file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Connection timed out
The download failed repeatedly, aborting.

**Comment by mrbinr** [comment]
I've tried wget again ... and now it doesn't work as this morning : 

--2015-07-12 19:40:09--  https://getcomposer.org/composer.phar
Résolution de getcomposer.org (getcomposer.org)... 2001:41d0:a:7b19::, 87.98.253.108
Connexion vers getcomposer.org (getcomposer.org)|2001:41d0:a:7b19::|:443...échec: Connexion terminée par expiration du délai d'attente.
Connexion vers getcomposer.org (getcomposer.org)|87.98.253.108|:443...connecté.
requête HTTP transmise, en attente de la réponse...200 OK
Longueur: 1113632 (1,1M) [application/octet-stream]
Sauvegarde en : «composer.phar.4»

100%[====================================================================================================================>] 1 113 632   68,8K/s   ds 13s     

2015-07-12 19:41:28 (84,6 KB/s) - «composer.phar.4» sauvegardé [1113632/1113632]

**Comment by mrbinr** [comment]
Is there a solution to continue using ipv4 instead of ipv6 , cause now i can't continue my work ... :(

**Comment by mrbinr** [comment]
I have disable IP v6 on my computer 

#disable ipv6
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 1

wget works with ipv4 

wget  https://getcomposer.org/composer.phar
--2015-07-12 20:07:19--  https://getcomposer.org/composer.phar
Résolution de getcomposer.org (getcomposer.org)... 87.98.253.108, 2001:41d0:a:7b19::
Connexion vers getcomposer.org (getcomposer.org)|87.98.253.108|:443...connecté.
requête HTTP transmise, en attente de la réponse...200 OK
Longueur: 1113632 (1,1M) [application/octet-stream]
Sauvegarde en : «composer.phar.5»

100%[====================================================================================================================>] 1 113 632   69,4K/s   ds 17s     

2015-07-12 20:07:39 (64,6 KB/s) - «composer.phar.5» sauvegardé [1113632/1113632]

but i still have problem with composer using curl

curl -sS https://getcomposer.org/installer | php
#!/usr/bin/env php
All settings correct for using Composer
PHP Notice:  Undefined variable: caBundle in - on line 821
Downloading...
Download failed: file_get_contents(): SSL: Handshake timed out
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed
Downloading...
Download failed: file_get_contents(): SSL: Handshake timed out
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed
Downloading...
Download failed: file_get_contents(): SSL: Handshake timed out
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed
The download failed repeatedly, aborting.

**Comment by mrbinr** [comment]
using composer.phar downloaded with wget give me error : 

  [Composer\Downloader\TransportException]                                                          
  The "https://packagist.org/packages.json" file could not be downloaded: SSL: Handshake timed out  
  Failed to enable crypto                                                                           
  failed to open stream: operation failed

**Comment by mrbinr** [comment]
here is php composer.phar diag : 

Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: Connection timed out
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: SSL: Handshake timed out
Failed to enable crypto
failed to open stream: operation failed
Checking disk free space: OK
Checking composer version: 

                                                                                                
  [Composer\Downloader\TransportException]                                                      
  The "https://getcomposer.org/version" file could not be downloaded: SSL: Handshake timed out  
  Failed to enable crypto                                                                       
  failed to open stream: operation failed

**Comment by mrbinr** [comment]
Ok so after hours of investigation i've seen that bind9 was not install on my computer ... why ? i don't know .. but after having reinstall it composer diag works ...

php composer.phar diag : 

Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking composer version: OK

composer self-update and composer update too ... but it's really really slow .. (composer update hasn't finish yet ... )

**Comment by mrbinr** [comment]
hi,
my problem with composer is not solved ... now i can launch it but it is very very very ... slow ... and i really donc know where is the problem.

I have talk about it on free.fr user forum, but without any answer ...

**Comment by alcohol** [comment]
You can try forcing ipv4 connectivity. But if it is really slow over ipv6 that would indicate issues with your ISP.

**Comment by hugosoltys** [comment]
I have the same problem when i run a composer diag (Debian 7.8)

Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: failed to open stream: Connection timed out
Checking disk free space: OK
Checking composer version: OK

**Comment by alcohol** [comment]
That does not look to be the same problem. You have trouble connecting to github.com, while you have no trouble connecting to packagist.org.

**Comment by hugosoltys** [comment]
Okay, i opened a new issue here 
https://github.com/composer/composer/issues/4292

I must say that ssh -T git@github.com successfully authenticate me on github. 
Maybe can you help me ?

**Comment by AlNahari** [comment]
locate cacert.pem

vi /usr/local/lib/php.ini

#add this

openssl.cafile=/usr/local/share/perl5/Mozilla/CA/cacert.pem

# press esc then type
:wq #enter

curl -sS https://getcomposer.org/installer | php -- —version=1.0.0-alpha10

mv composer.phar /usr/local/bin/composer

alias composer='/usr/local/bin/composer'

composer -V

php /usr/local/bin/composer global self-update

cd .composer/
composer init

**Comment by calamarino** [comment]
Just in case it helps someone 
https://getcomposer.org/doc/articles/troubleshooting.md#operation-timed-out-ipv6-issues-
Workaround Linux
sudo sh -c "echo 'precedence ::ffff:0:0/96 100' >> /etc/gai.conf"

**Comment by zawzawzaw** [comment]
Thanks a lot calamarino! I been googling for answer to that question for a long while.. thank god that i read your comment!

**Comment by alcohol** [comment]
@zawzawzaw and you never considered reading our documentation (which contains exactly that answer)? Any reason why? Is the documentation hard to find? Not easy to navigate? Is the lack of a search functionality severely hindering its use? (honest questions)

**Comment by zawzawzaw** [comment]
@alcohol well if I knew documentation has those fixes for common problems I would have go there straight. But normally I use documentation while I am coding on new platform or framework. Never consider documentation as problem solving site like stackoverflow anyway I guess you know what I mean. But while I am googling about it there was no match result to documentation site though.

**Comment by alcohol** [comment]
Maybe the documentation regarding this needs more context. That might help aid Google results. Unfortunately, it is difficult to determine how much context it might need and what would be considered relevant and what not. Thanks for the answer regardless :-)

**Comment by alteringres** [comment]
https://getcomposer.org/doc/articles/troubleshooting.md

Here you can find the workaround for some issues,  disabling IpV6 worked for me just fine, please take a look at documentation.

**Comment by lankasenanayaka** [comment]
Thanks @calamarino it worked

**Comment by psarankeylent** [comment]
```shell
sudo ufw allow ssh
sudo ufw enable
sudo service php{version-number}-fpm restart
sudo service php8.1-fpm restart
sudo service apache2 restart

``` 
These cmd was helpfull for me
