### ISSUE TITLE
Can't run update and self update

### ISSUE THREAD

**Issue by Lisio** [composer/composer#4249]
Running composer selfupdate returns the error:
`[Composer\Downloader\TransportException]`
`"https://getcomposer.org/download//composer.phar" appears broken, and returned an empty 200 response`

Also receive 404 when trying to open https://getcomposer.org/download//composer.phar in browser.

Running composer update returns the error:
`[ErrorException]`
`Invalid argument supplied for foreach()`

**Comment by alcohol** [comment]
Are you still experiencing issues?

**Comment by Lisio** [comment]
Yes. To reproduce you can run "composer update" using php 5.5 and after that do the same with php 5.4.

**Comment by alcohol** [comment]
I'm sorry but I cannot reproduce your issue.

Can you share your composer.json configuration with us?

Also please note that `composer update` is not the same as `composer self-update`. The former tries to update your defined dependencies to their latest versions. The latter tries to update Composer itself.

**Comment by Lisio** [comment]
Sure,

composer.json
```javascript
{
  "require": {
      "videlalvaro/php-amqplib": "2.5.*"
  }
}
```

Running "composer install" with php 5.5.27
```
lisio@server:/web/www/composer$ php -v
PHP 5.5.27 (cli) (built: Jul 10 2015 20:51:49) (DEBUG)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

lisio@server:/web/www/composer$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing videlalvaro/php-amqplib (v2.5.1)
    Loading from cache

Writing lock file
Generating autoload files
```

Running "composer update" with php 5.4.43
```
lisio@server:/web/www/composer$ php -v
PHP 5.4.43 (cli) (built: Jul 12 2015 22:32:58) (DEBUG)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

lisio@server:/web/www/composer$ composer update
Loading composer repositories with package information


                                           
  [ErrorException]                         
  Invalid argument supplied for foreach()  
                                           


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]
```

Running "composer update" with php 5.6.11
```
lisio@server:/web/www/composer$ php -v
PHP 5.6.11 (cli) (built: Jul 10 2015 21:13:12) (DEBUG)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

lisio@server:/web/www/composer$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

Also, I can't just install composer itself using php 5.4.43
```
root@server:/web/www/composer# php -v
PHP 5.4.43 (cli) (built: Jul 12 2015 22:32:58) (DEBUG)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

root@server:/web/www/composer# curl -sS https://getcomposer.org/installer | php
#!/usr/bin/env php
Some settings on your machine may cause stability issues with Composer.
If you encounter issues, try to change the following:

PHP was compiled with --with-curlwrappers which will cause issues with HTTP authentication and GitHub.
Recompile it without this flag if possible

Downloading...
Download failed: 

Composer successfully installed to: /web/www/composer/composer.phar
Use it: php composer.phar

root@server:/web/www/composer# ls -l composer.phar
-rwxr-xr-x 1 root root 0 Jul 22 09:58 composer.phar
```
As you can see composer.phar is empty.

But with php 5.5.27 and 5.6.11 it works just fine
```
root@server:/web/www/composer# php -v
PHP 5.5.27 (cli) (built: Jul 10 2015 20:51:49) (DEBUG)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

root@server:/web/www/composer# curl -sS https://getcomposer.org/installer | php
#!/usr/bin/env php
Some settings on your machine may cause stability issues with Composer.
If you encounter issues, try to change the following:

PHP was compiled with --with-curlwrappers which will cause issues with HTTP authentication and GitHub.
Recompile it without this flag if possible

Downloading...

Composer successfully installed to: /web/www/composer/composer.phar
Use it: php composer.phar

root@server:/web/www/composer# ls -l composer.phar
-rwxr-xr-x 1 root root 1116327 Jul 22 09:59 composer.phar
```

**Comment by alcohol** [comment]
Can you show us the `composer --version` you were using for these actions?

**Comment by Lisio** [comment]
```
root@server:/web/www/composer# composer --version
Composer version 1.0-dev (c36d2a2e501315934b6968efa3cea41dd27f2511) 2015-07-13 13:28:10
```

```
lisio@server:/web/www/composer$ composer update -vvv
Reading ./composer.json
Loading config file /home/lisio/.composer/config.json
Loading config file /home/lisio/.composer/auth.json
Loading config file ./composer.json
Executing command (CWD): git describe --exact-match --tags
Executing command (CWD): git branch --no-color --no-abbrev -v
Executing command (CWD): hg branch
Executing command (CWD): svn info --xml
Reading /home/lisio/.composer/composer.json
Loading config file /home/lisio/.composer/config.json
Loading config file /home/lisio/.composer/auth.json
Loading config file /home/lisio/.composer/composer.json
Loading config file /home/lisio/.composer/auth.json
Executing command (CWD): git describe --exact-match --tags
Executing command (CWD): git branch --no-color --no-abbrev -v
Executing command (CWD): hg branch
Executing command (CWD): svn info --xml
Loading plugin Fxp\Composer\AssetPlugin\FxpAssetPlugin
Loading composer repositories with package information
Downloading https://packagist.org/packages.json
Writing /home/lisio/.composer/cache/repo/https---packagist.org/packages.json into cache
Downloading http://packagist.org/packages.json
Writing /home/lisio/.composer/cache/repo/https---packagist.org/packages.json into cache
Downloading http://packagist.org/packages.json
Writing /home/lisio/.composer/cache/repo/https---packagist.org/packages.json into cache


                                           
  [ErrorException]                         
  Invalid argument supplied for foreach()  
                                           


Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:529
 Composer\Util\ErrorHandler::handle() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:529
 Composer\Repository\ComposerRepository->loadIncludes() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:483
 Composer\Repository\ComposerRepository->loadDataFromServer() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:379
 Composer\Repository\ComposerRepository->initialize() at phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:178
 Composer\Repository\ArrayRepository->getPackages() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:171
 Composer\Repository\ComposerRepository->getPackages() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:104
 Composer\DependencyResolver\Pool->addRepository() at phar:///usr/local/bin/composer/src/Composer/Installer.php:395
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:230
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:140
 Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:146
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:82
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:25


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]
```

**Comment by alcohol** [comment]
That is peculiar. It's writing the same file three times into the cache. Even though looking at the code in the context there, it should not. Can you show us what it actually stored in `/home/lisio/.composer/cache/repo/https---packagist.org/packages.json` ?

**Comment by Lisio** [comment]
It was empty. I've just recompiled php 5.4.43 without --with-curlwrappers option and now everything works as expected.

**Comment by alcohol** [comment]
It could be that the write() in the Cache class was throwing an Exception, but it got caught in the fetchFile() try/catch while loop. It is misleading cause it outputs that it is writing to the cache before actually doing it, rather than after the action has finished. Something we could improve (I think for read actions, we should notify before, for write actions, notify after).

/cc @Seldaek possible point of improvement? Should I open an issue for that?

**Comment by Seldaek** [comment]
I'm not sure that's a good idea, because then you wouldn't have had any `Writing ..` output as a clue of what it was doing when it failed.

**Comment by alcohol** [comment]
True. But it seems like an exception other than ErrorException is thrown (or the message does not match the regex it is trying to match against, which results in a re- throw of the ErrorException in that case). But then the try/catch in fetchFile() hides it. So not sure what exactly the exception is at this point since it doesn't output it :-(

**Comment by vdespa** [comment]
I am having a similar issue like @Lisio -  the Exception trace seems identical.

Some tech details:

    $ composer --version
    Composer version 1.0-dev (c83650f299cfff1049cd61ea72ee5345bd4f92d3) 2015-08-04 13:59:03

$ composer install -vvv
Reading ./composer.json
Loading config file /Users/[USERNAME]/.composer/config.json
Loading config file ./composer.json
Executing command (CWD): git describe --exact-match --tags
Executing command (CWD): git branch --no-color --no-abbrev -v
Executing command (CWD): hg branch
Executing command (CWD): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /Users/[USERNAME]/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Loading composer repositories with package information
Downloading http://example.com/tools/composer/packages.json
Writing /Users/[USERNAME]/.composer/cache/repo/http---example.com-tools-composer/packages.json into cache
Downloading http://example.com/tools/composer/packages.json
Writing /Users/[USERNAME]/.composer/cache/repo/http---example.com-tools-composer/packages.json into cache
Downloading http://example.com/tools/composer/packages.json
Writing /Users/[USERNAME]/.composer/cache/repo/http---example.com-tools-composer/packages.json into cache

  [ErrorException]
  Invalid argument supplied for foreach()

Exception trace:
 () at phar:///usr/local/Cellar/composer/1.0.0-alpha8/libexec/composer.phar/src/Composer/Repository/ComposerRepository.php:529
 Composer\Util\ErrorHandler::handle() at phar:///usr/local/Cellar/composer/1.0.0-alpha8/libexec/composer.phar/src/Composer/Repository/ComposerRepository.php:529
 Composer\Repository\ComposerRepository->loadIncludes() at phar:///usr/local/Cellar/composer/1.0.0-alpha8/libexec/composer.phar/src/Composer/Repository/ComposerRepository.php:483
 Composer\Repository\ComposerRepository->loadDataFromServer() at phar:///usr/local/Cellar/composer/1.0.0-alpha8/libexec/composer.phar/src/Composer/Repository/ComposerRepository.php:379
 Composer\Repository\ComposerRepository->initialize() at phar:///usr/local/Cellar/composer/1.0.0-alpha8/libexec/composer.phar/src/Composer/Repository/ArrayRepository.php:178
 Composer\Repository\ArrayRepository->getPackages() at phar:///usr/local/Cellar/composer/1.0.0-alpha8/libexec/composer.phar/src/Composer/Repository/ComposerRepository.php:171
 Composer\Repository\ComposerRepository->getPackages() at phar:///usr/local/Cellar/composer/1.0.0-alpha8/libexec/composer.phar/src/Composer/DependencyResolver/Pool.php:104
 Composer\DependencyResolver\Pool->addRepository() at phar:///usr/local/Cellar/composer/1.0.0-alpha8/libexec/composer.phar/src/Composer/Installer.php:395
 Composer\Installer->doInstall() at phar:///usr/local/Cellar/composer/1.0.0-alpha8/libexec/composer.phar/src/Composer/Installer.php:230
 Composer\Installer->run() at phar:///usr/local/Cellar/composer/1.0.0-alpha8/libexec/composer.phar/src/Composer/Command/InstallCommand.php:131
 Composer\Command\InstallCommand->execute() at phar:///usr/local/Cellar/composer/1.0.0-alpha8/libexec/composer.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/Cellar/composer/1.0.0-alpha8/libexec/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/Cellar/composer/1.0.0-alpha8/libexec/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/Cellar/composer/1.0.0-alpha8/libexec/composer.phar/src/Composer/Console/Application.php:146
 Composer\Console\Application->doRun() at phar:///usr/local/Cellar/composer/1.0.0-alpha8/libexec/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///usr/local/Cellar/composer/1.0.0-alpha8/libexec/composer.phar/src/Composer/Console/Application.php:82
 Composer\Console\Application->run() at phar:///usr/local/Cellar/composer/1.0.0-alpha8/libexec/composer.phar/bin/composer:43
 require() at /usr/local/Cellar/composer/1.0.0-alpha8/libexec/composer.phar:25

**Comment by Seldaek** [comment]
@vdespa do you also have a php compiled with `--with-curlwrappers`? You can check on phpinfo or `php -i | grep curlwrap`

**Comment by vdespa** [comment]
No, my PHP seems not to be compiled with "--with-curlwrappers".

**Comment by Seldaek** [comment]
@vdespa ok I added some more debugging info could you try again with -vvv? you should get warnings after the "Writing ... into cache" lines, maybe they help.

**Comment by vdespa** [comment]
@Seldaek After a composer self-update I am no longer able to replicate the issue.

**Comment by Seldaek** [comment]
Meh ok :/ I'm glad it's fixed though..

**Comment by vdespa** [comment]
@Seldaek Thanks for looking into it. Sorry to disappoint. :P

**Comment by davidecheta599** [comment]
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
The "http://packagist.org/p/symfony/event-dispatcher%24b691b3c505c584f0929db40cbf5e81e2440d1e5f9bffe8b940932769cf66edc0.json" file could not be downloaded: failed to open stream: HTTP request failed!
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date

SOMEBODY PLS HELP ME HELP ME

**Comment by curry684** [comment]
Call your system administrator, "HTTP request failed" is his problem, not ours.
