### ISSUE TITLE
Inconsistent replace behavior

### ISSUE THREAD

**Issue by astehlik** [composer/composer#4250]
This behavior of composer seems wrong to me:

Given I need two libraries in my project:

```json
{
    "name": "vendor/myproject",
    "type": "project",
	"require": {
		"vendor/lib-dependency": "*",
		"vendor/lib-depends": "*",
	}
}

```

The package ```vendor/lib-depends``` depends on a library, that is replaced by ```vendor/lib-dependency```. The ```composer.json``` of ```vendor/lib-dependency``` looks like this:

```json
{
	"name": "vendor/lib-dependency",
	"type": "library",
	"replace": {
		"vendor-original/lib-dependency": "self.version"
	}
}
```

The ```composer.json``` file of ```vendor/lib-depends``` looks like this:

```json
{
	"name": "vendor/lib-depends",
	"type": "library",
	"require": {
		"vendor-original/lib-dependency": ">=1.0.0"
	}
}
```

The ```vendor-original/lib-dependency``` package is **not available at any repository**.

When I run a ```composer update``` with this I get an dependency error because no matching package is found for ```vendor-original/lib-dependency```.

When I follow these steps, I can install the package:

1. Remove the dependency for ```vendor/lib-depends```
2. Run ```composer update``` (the package ```vendor/lib-dependency``` is installed without problems)
3. Add the dependency for ```vendor/lib-depends```
4. Run ```composer update``` again, now no dependency error occurs.

I would expect composer to resolve the replace configuration of all packages that should be installed. Not only of the installed packages.

**Comment by astehlik** [comment]
The same seems to apply for the ```provide``` configuration.

**Comment by stof** [comment]
The issue with the behavior you are suggesting (which is the one originally implemented in Composer btw) is that it allows any package registered in the repository to hack projects by replacing other packages (targetting big frameworks for instance) with higher version numbers that the real package so that they are considered newer. This is a severe security risk for projects.

This is why Composer requires to explicitly require the replacer package before selecting it to fulfill the dependency.

**Comment by astehlik** [comment]
Thanks for the reply.

I'm totally fine with explicitly requiring the replacing package and I understand the reasons. But this is not the problem I'm facing.

Event if I explicitly require the replacing package in the composer.json file of my project the dependency is not fulfilled until the replacing package is installed locally.

**Comment by Seldaek** [comment]
@astehlik can you post a reproduce case for the problem you describe? Ideally using a "package" repository like in https://github.com/composer/composer/blob/master/tests/Composer/Test/Fixtures/installer/replace-root-require.test (which BTW seems to be exactly what you described in the first post), so this can be easily dropped in the test suite.

**Comment by astehlik** [comment]
I just tried to reproduce the bug and collect some example repositories but I'm not getting the error any more. Really strange. Well, self fixing bugs, great stuff :) Closing this one for now.

Thank you for taking care!
