### ISSUE TITLE
Composer out of memory error

### ISSUE THREAD

**Issue by psddp** [composer/composer#4253]
Hi

While running a composer update, I get a Composer out of memory error. The Composer doc suggest to create an issue here if such case occurs (https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors).
![composer_error](https://cloud.githubusercontent.com/assets/7760275/8660836/51125920-2981-11e5-867c-0e8db793c2b8.png)

**Comment by dustingraham** [comment]
Just hit this on an orocrm update as well with 1GB of memory.
