### ISSUE TITLE
Composer does not remove autoload_files.php when related packages are removed

### ISSUE THREAD

**Issue by hlubek** [composer/composer#4254]
How to reproduce:

    composer require guzzlehttp/guzzle "~5.2"

This creates a `autoload_files.php` that requires `react/promise`.

    composer remove guzzlehttp/guzzle
    composer update

This will remove the `autoload_files.php` from `autoload_real.php` but does not remove the file itself. This  is of course correct if you just rely on `autoload_real.php`. In the Flow framework we use a custom class loader that includes `autoload_files.php` directly if it exists. For this case it would be very helpful if Composer would remove the missing package from `autoload_files.php`.

**Comment by KingCrunch** [comment]
Hi @Seldaek 

This seems to be fixed in #4359 and can get closed.

**Comment by Seldaek** [comment]
Yup thanks
