### ISSUE TITLE
EventDispatcher writes debugs as errors

### ISSUE THREAD

**Issue by ppankowski** [composer/composer#4255]
EventDispatcher::doDispatch 

```php
if ($this->io->isVerbose()) {
  $this->io->writeError(sprintf('> %s: %s', $event->getName(), $exec));
} else {
  $this->io->writeError(sprintf('> %s', $exec));
}
```

EventDispatchet::executeEventPhpScript
```php
if ($this->io->isVerbose()) {
  $this->io->writeError(sprintf('> %s: %s::%s', $event->getName(), $className, $methodName));
} else {
  $this->io->writeError(sprintf('> %s::%s', $className, $methodName));
}
```

These debug information is returned as error (write to STDERR), causing a problem when running composer remotely using phing and ssh command. $this->io->writeError should be used only for real errors.

**Comment by stof** [comment]
Writing something to STDERR does **not** mean it is an error. It means it is not part of the main output of the script. any informational message should go to STDERR.
If your tool relies on the usage of STDERR to detect failure, it is your tool being broken, not Composer. Detecting failures must rely on the exit code

**Comment by alcohol** [comment]
See comments on #3715 for rationale behind this choice.
