### ISSUE TITLE
Branch Alias not working with vcs Repository

### ISSUE THREAD

**Issue by privatmamtora** [composer/composer#4258]
I have a local package(glas/getallstuff) which I am working on
In the package I have this in `composer.json`
```JSON
"extra": {
        "branch-alias": {
            "dev-develop": "0.6-dev"
        }
    }
```
In another package(glas/FormatStuff) I have this in the `composer.json`
```JSON
"repositories": [
        {
            "type": "vcs",
            "url": "../GetAllStuff"
        }
    ]
```
Now while I am in root of `formatStuff` and execute `composer show glas/getallstuff` it is not picking up the alias for `dev-develop`.

Alias works if it is a published package but not local (or vcs).

**Comment by alcohol** [comment]
Is "dev-develop" an actual existing branch? Or did you mean "develop" maybe?

**Comment by davidverholen** [comment]
just tested this and it works with the local repository.
I think your branch alias has to be like this to work:

```json
"extra": {
    "branch-alias": {
        "dev-develop": "0.6.x-dev"
    }
}
```

**Comment by alcohol** [comment]
Well, then you have to require "dev-dev-develop", since the "dev-" prefix is virtual, not literal. See [documentation](https://getcomposer.org/doc/02-libraries.md#branches) for details.

**Comment by davidverholen** [comment]
ah ok, didn't know that.

Maybe it fails because the develop branch is not checked out locally?
When I delete the local develop branch composer falls back to packagist.org. 
When I then deactivate the packagist repo it fails
