### ISSUE TITLE
Use of __DIR__ in including vendor/autoload.php still best practice?

### ISSUE THREAD

**Issue by spencerbaynton** [composer/composer#4259]
In #3902 the `__DIR__` constant was added to the example code for including `vendor/autoload.php`. However, that section of the introduction documentation was removed in #4172. If the best practice is still to use `__DIR__` when including `vendor/autoload.php` then the example code in [Basic usage](https://getcomposer.org/doc/01-basic-usage.md#autoloading) should be update to:
```php
require __DIR__ . '/vendor/autoload.php';
```

**Comment by alcohol** [comment]
I don't think this makes a difference really. Everyone should know how the `require` function works. It should be up to the user whether or not they want to use an absolute or relative path. This is PHP knowledge, not Composer knowledge.

**Comment by glensc** [comment]
btw, i think one must always use absolute path, otherwise relative path searches matches from php include path and may match something else, it's also performance wise better to use absolute paths (include path search will not be performed)
