### ISSUE TITLE
Unable to install Laravel through composer 400 bad request on http

### ISSUE THREAD

**Issue by dblackw** [composer/composer#4261]
I am getting an issue of 400 bad request connecting over http, and it seems the package only wants to be installed via http. I tried an override in composer.json as tried by others as workaround to force https - but that doesn't seem to work 

composer diagnose
Checking composer.json: FAIL
the property name is required
the property description is required
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: FAIL
[Composer\Downloader\TransportException] The "http://packagist.org/packages.json" file could not be downloaded (HTTP/1.1 400 Bad Request)
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking composer version: OK

**Comment by dblackw** [comment]
error when running composer global require laravel/laravel 
                                                                                                                                               
  [Composer\Downloader\TransportException]                                                                                                     
  The "http://packagist.org/p/provider-2013$c2596c5d04e7701561420666ba120ede9429a69c75b732a5a01b18ebb3d64e53.json" file could not be downloaded (HTTP/1.1 400 Bad Request)

**Comment by hmert** [comment]
:+1:

**Comment by MAZEN-Kenjrawi** [comment]
If anyone has this issue on windows, try this solution on StackOverFlow:
https://stackoverflow.com/a/49147518/3317006

**Comment by almounkez** [comment]
same with you. and i found the way to resolve it (for window 10) on internet. 
1 - go to folder PATH\xampp\apache 
and run makecert.bat
 2 - add this script to composer.json file


"repositories": [
        {
            "type": "composer",
            "url": "https://packagist.org"
        },
        {
            "packagist": false
        }
    ]
