### ISSUE TITLE
changing require-dev to require fails on [update]

### ISSUE THREAD

**Issue by wjaspers** [composer/composer#4266]
Version: `Composer version 1.0-dev (5d7036e7403377e4c06ecae1e52139fd00809246) 2015-07-08 17:10:35`

**create composer.json**
```
{
"require-dev": {
   "my/private-repo": "dev-master"
}
}
```

`composer.phar install`

**Oops!** My dependency is always needed.

`rm -Rf vendor`

**update composer.json**

```
{
"require": {
    "my/private-repo": "dev-master"
}
}
```

**Run update**
`composer.phar update`

**output**
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
...
```

- Is this the expected behavior when calling `update` instead of `install`?
- Should said change always require re-installation?

**Attempt reinstallation**

```
rm -Rf vendor
composer.phar install
```

**output**

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
```

**Comment by slbmeh** [comment]
Where is composer getting the information about the package `my/private-repo`?

**Comment by wjaspers** [comment]
under the repositories key

**Comment by slbmeh** [comment]
What is the contents of your composer.json, and what is the reason(s) it spits out when it says it could not resolve an installable set of packages?
