### ISSUE TITLE
Failed to Install Data-Fixtures with Composer and Symfony2

### ISSUE THREAD

**Issue by NadjibBELLOUNDJA** [composer/composer#4270]
I am currently working on a Symfony project. I added the doctrine-fixtures and the doctrine-fixtures-bundle to my dependencies in the composer.json, as follow:

{ 
"require": { "php": ">=5.3.3", "symfony/finder": "2.3.*", 
"doctrine/orm": "~2.2,>=2.2.3", 
"doctrine/doctrine-bundle": "~1.2", 
"doctrine/data-fixtures": "~1.1", 
"doctrine/doctrine-fixtures-bundle": "~2.2"
}

And then I did php-cli composer.phar update, which worked and displayed the right message on my terminal:

"Loading composer repositories with package information Updating dependencies (including require-dev) - Updating doctrine/data-fixtures (dev-master bd44f6b => v1.1.1) Checking out bd44f6b6e40247b6530bc8abe802e4e4d914976a

Writing lock file

Generating autoload files"

Bu when I go to the folder vendor/doctrine, I cannot find any data-fixtures repository. What is the issue? Why does composer not load it and why does it display success messages if it doesn't load the doctrine-dixture folder?

(PS: My solution was to download and add the doctrine-fixture repository manually but it doesn't solve the composer issue).

**Comment by phansys** [comment]
@NadjibBELLOUNDJA, ```doctrine/doctrine-fixtures-bundle``` already has a requirement for ```doctrine/data-fixtures```, so there is no need for redeclaring it.
Could you please run the command again adding more verbosity via ```-vvv``` argument?

**Comment by NadjibBELLOUNDJA** [comment]
@phansys Hi Javier,

I solved my issue. The composer.phar was in the folder "../" of my application whereas it should have been in the application folder. Sorry for the bothering. Thank you for your reply.

**Comment by alcohol** [comment]
Closing this as it seems to have been resolved already :-).
