### ISSUE TITLE
Repositories keyword shouldn't be root only

### ISSUE THREAD

**Issue by Enelar** [composer/composer#4273]
That's odd, i should track of requirement library requirements?

I know that i should be able override sub-module keywords, but why you would ignore this?
Only sub-module know whats best for him, and when.

**Comment by alcohol** [comment]
As explained on IRC @ #composer; this is for a valid reason which is explained [here](https://getcomposer.org/doc/faqs/why-can%27t-composer-load-repositories-recursively.md).

**Comment by Enelar** [comment]
@alcohol Yes, sorry for duplication. I landed IRC hours later than issue report.
