### ISSUE TITLE
Composer installation on travis fail

### ISSUE THREAD

**Issue by mickaelandrieu** [composer/composer#4274]
```
$ curl -s http://getcomposer.org/installer | php
PHP Parse error:  syntax error, unexpected end of file, expecting variable (T_VARIABLE) or heredoc end (T_END_HEREDOC) or ${ (T_DOLLAR_OPEN_CURLY_BRACES) or {$ (T_CURLY_OPEN) in - on line 1980
Parse error: syntax error, unexpected end of file, expecting variable (T_VARIABLE) or heredoc end (T_END_HEREDOC) or ${ (T_DOLLAR_OPEN_CURLY_BRACES) or {$ (T_CURLY_OPEN) in - on line 1980

```
https://travis-ci.org/backbee/BackBee/jobs/71724398

I guess this is not related to composer but maybe to Symfony component (I have reported issue on this component that is broken since 2.7.2), do you need help @Seldaek ?

**Comment by alcohol** [comment]
Weird. It seems you received an incomplete installer. Connection issue perhaps? This has nothing to do with Symfony components by the way. The installer script is pure plain PHP.

FYI; composer is installed on Travis by default if you are using the php environments. So there is no need to install it manually.

**Comment by mickaelandrieu** [comment]
@alcohol thank for help, I have also update the BackBee travis configuration in order to remove this useless installation step (https://github.com/backbee/BackBee/pull/508)

**Comment by alcohol** [comment]
I see that now you are receiving the dreaded `zlib_decode()` error. Can you try and see if switching to the new docker architecture of Travis has an impact on your builds?

Simply add `sudo: false` to your .travis.yml config to let travis know that it can build your project on their new docker infrastucture.

Relevant link: http://docs.travis-ci.com/user/workers/container-based-infrastructure/

**Comment by mickaelandrieu** [comment]
yes, I tried and receive composer update failures.

So, I have added COMPOSER_ROOT_VERSION as suggested in composer docs. The build is green again :) 

Thank you for help :)

**Comment by alcohol** [comment]
Uh..... what?

**Comment by mickaelandrieu** [comment]
Without COMPOSER_ROOT_VERSION set to "dev-master", composer was unable to install my dependencies: I think travis-ci install an outdated build of composer :/

**Comment by alcohol** [comment]
I believe COMPOSER_ROOT_VERSION is to be used in case one of your dependencies depends on your root project. Not sure how it is related to the issues you reported earlier.

**Comment by mickaelandrieu** [comment]
hmmm, it works for now but I didn't totaly understand why... :/ 

In all cases, thank you. I close to not spam @Seldaek with useless notifications ;)
