### ISSUE TITLE
Loading required packages from pear repository fails

### ISSUE THREAD

**Issue by ComaVN** [composer/composer#4275]
I used to be able to load pear packages from the default pear repository (pear.php.net), but this no longer works: I get `The requested package pear-pear/pear could not be found in any version`

See https://github.com/ComaVN/ComposerPearTest for my `composer.json`

I have also tried:
 - lowering `minimum-stability` to `dev`
 - requiring other pear packages like `pear-pear/mail` and `pear-pear/mail_mime`
 - explicitly requiring the latest version `1.9.5`
 - explicitly requiring the `dev` or `dev-master` version

None of this worked.

I have also tried skipping the pear repository, and using packagist instead: https://packagist.org/packages/pear/pear

However, this gave me a warning: `Warning: Ambiguous class resolution, "PEAR_ErrorStack" was found in both "/Users/foo/git/ComposerPearTest/vendor/pear/pear/PEAR/ErrorStack.php" and "/Users/foo/git/ComposerPearTest/vendor/pear/pear/PEAR/ErrorStack5.php", the first will be used.`.

What am I doing wrong here?

    % ./composer.phar self-update
    You are already using composer version 417516098edb9b3c9d433c9b6527b0f1492362f4.
    % ./composer.phar update -vvv
    Reading ./composer.json
    Loading config file /Users/foo/.composer/config.json
    Loading config file /Users/foo/.composer/auth.json
    Loading config file ./composer.json
    Executing command (CWD): git describe --exact-match --tags
    Executing command (CWD): git branch --no-color --no-abbrev -v
    Failed to initialize global composer: Composer could not find the config file: /Users/foo/.composer/composer.json
    To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
    Loading composer repositories with package information
    Initializing PEAR repository http://pear.php.net
    Downloading http://pear.php.net/channel.xml
    Downloading http://pear.php.net/rest/c/categories.xml
    Downloading http://pear.php.net/rest/c/Audio/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Authentication/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Benchmarking/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Caching/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Configuration/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Console/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Database/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Date+and+Time/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Encryption/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Event/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/File+Formats/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/File+System/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Gtk+Components/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Gtk2+Components/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/GUI/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/HTML/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/HTTP/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Images/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Internationalization/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Logging/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Mail/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Math/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Multimedia/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Networking/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Numbers/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Payment/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/PEAR/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/PEAR+Website/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/PHP/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Processing/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/QA+Tools/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Scheduling/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Science/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Search+Engine/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Security/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Semantic+Web/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Streams/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Structures/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/System/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Testing/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Text/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Tools+and+Utilities/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Validate/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Version+Control/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/Web+Services/packagesinfo.xml
    Downloading http://pear.php.net/rest/c/XML/packagesinfo.xml
    Could not load Auth 1.3.0r5: Invalid version string "1.3.0r5"
    Could not load Auth 1.3.0r4: Invalid version string "1.3.0r4"
    Could not load Auth 1.3.0r3: Invalid version string "1.3.0r3"
    Could not load Auth 1.3.0r2: Invalid version string "1.3.0r2"
    Could not load Auth 1.3.0r1: Invalid version string "1.3.0r1"
    Could not load Auth_PrefManager2 2.0.0dev1: Invalid version string "2.0.0dev1"
    Could not load Contact_AddressBook 0.1.0dev1: Invalid version string "0.1.0dev1"
    Could not load Gtk_ScrollingLabel 0.1.0dev1: Invalid version string "0.1.0dev1"
    Could not load Image_Graph 0.3.0dev4: Invalid version string "0.3.0dev4"
    Could not load Image_Graph 0.3.0dev3: Invalid version string "0.3.0dev3"
    Could not load Image_Graph 0.3.0dev2: Invalid version string "0.3.0dev2"
    Could not load Image_Graph 0.3.0dev1: Invalid version string "0.3.0dev1"
    Could not load Net_MPD 0.1.0dev1: Invalid version string "0.1.0dev1"
    Could not load PEAR 1.9.5dev1: Invalid version string "1.9.5dev1"
    Could not load Structures_DataGrid 0.9.1dev1: Invalid version string "0.9.1dev1"
    Could not load Structures_DataGrid_DataSource_Array 0.2.0dev1: Invalid version string "0.2.0dev1"
    Could not load Structures_DataGrid_DataSource_DataObject 0.2.2dev1: Invalid version string "0.2.2dev1"
    Could not load Structures_DataGrid_DataSource_XML 0.2.1dev1: Invalid version string "0.2.1dev1"
    Could not load Structures_DataGrid_Renderer_CSV 0.1.5dev1: Invalid version string "0.1.5dev1"
    Could not load Structures_DataGrid_Renderer_XML 0.1.4dev1: Invalid version string "0.1.4dev1"
    Could not load Structures_Form 0.8.0devel: Invalid version string "0.8.0devel"
    Could not load Structures_Form_Gtk2 0.8.0devel: Invalid version string "0.8.0devel"
    Could not load Structures_DataGrid_DataSource_PDO 0.1.1dev1: Invalid version string "0.1.1dev1"
    Could not load Text_PathNavigator 0.1.0dev2: Invalid version string "0.1.0dev2"
    Could not load Text_PathNavigator 0.1.0dev1: Invalid version string "0.1.0dev1"
    Could not load Services_Pingback 0.2.0dev2: Invalid version string "0.2.0dev2"
    Downloading https://packagist.org/packages.json
    Writing /Users/foo/.composer/cache/repo/https---packagist.org/packages.json into cache
    Updating dependencies (including require-dev)
    Reading /Users/foo/.composer/cache/repo/https---packagist.org/p-provider-2013.json from cache
    Reading /Users/foo/.composer/cache/repo/https---packagist.org/p-provider-2014.json from cache
    Reading /Users/foo/.composer/cache/repo/https---packagist.org/p-provider-2014-10.json from cache
    Reading /Users/foo/.composer/cache/repo/https---packagist.org/p-provider-2015-01.json from cache
    Reading /Users/foo/.composer/cache/repo/https---packagist.org/p-provider-2015-04.json from cache
    Reading /Users/foo/.composer/cache/repo/https---packagist.org/p-provider-2015-07.json from cache
    Reading /Users/foo/.composer/cache/repo/https---packagist.org/p-provider-archived.json from cache
    Reading /Users/foo/.composer/cache/repo/https---packagist.org/p-provider-latest.json from cache
    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - The requested package pear-pear/pear could not be found in any version, there may be a typo in the package name.

    Potential causes:
     - A typo in the package name
     - The package is not available in a stable-enough version according to your minimum-stability setting
       see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

    Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by alcohol** [comment]
The warning was introduced recently and is nothing more than just that, a warning. See [#4260](/composer/composer/issues/4260#issuecomment-121931483) for more details. I don't know why pear-pear/pear will not install though.

**Comment by stof** [comment]
try using ``pear-pear.php.net/pear`` instead (i.e. the channel name rather than the channel alias). I think channel aliases are broken

**Comment by ComaVN** [comment]
using `pear-pear.php.net/pear` works, thanks
