### ISSUE TITLE
Dependency resolving not working with "branches version" after two nesting level

### ISSUE THREAD

**Issue by DarioSwain** [composer/composer#4276]
Hi guys,

I have three packages now, with next dependencies: one <----- two <----- tree.
All packages use dev-master versions of nested package.

For example:

Package one:

```json
{
  "name": "dario_swain/dependency-level-one",
  "type": "library",
  "require": {
    "dario_swain/dependency-level-two":    "dev-master"
  }
}

```

Package two:

```json
{
  "name": "dario_swain/dependency-level-two",
  "type": "library",
  "require": {
    "dario_swain/dependency-level-three":    "dev-master"
  }
}

```

Package tree:

```json
{
  "name": "dario_swain/dependency-level-three",
  "type": "library",
  "require": {
    "dario_swain/re-captcha-library":    "1.0.*"
  }
}
```

Next i want to update dependencies on my package one, i execute composer update command on package one

```bash
git clone https://github.com/DarioSwain/dependency-level-one.git one
cd one
composer update
```

In this case i receive next output:

```bash
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for dario_swain/dependency-level-two dev-master -> satisfiable by dario_swain/dependency-level-two[dev-master].

    - dario_swain/dependency-level-two dev-master requires dario_swain/dependency-level-three dev-master -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
``` 

It seems like a problem with minimum-stability functional, nested dependency mark as dev package and can't resolve it. But as I understand from the documentation, if we use branch name like a version this must mark package like a stable?

You can reproduce this issue with [this repository](https://github.com/DarioSwain/dependency-level-one).

**Comment by alcohol** [comment]
I believe that `dev-master` is still considered to be of stability "dev".

In the root package it is allowed even if `minimum-stability` is defaulting to stable, as you explicitly overrule it. Since you own the root package, Composer assumes you know what you are doing.

However, for dependencies this is not allowed as it would be considered unsafe (e.g. if you are not the maintainer of those dependencies) to automatically allow "dev" dependencies. You explicitly need to allow those by lowering the minimum-stability, or by including the same package in your root composer.json.

The following works without requiring you to lower minimum-stability:

```javascript
{
  "name": "dario_swain/dependency-level-one",
  "type": "library",
  "require": {
    "dario_swain/dependency-level-two": "dev-master",
    "dario_swain/dependency-level-three": "dev-master"
  }
}
```

/cc @Seldaek am I correct in my assumption?

**Comment by Seldaek** [comment]
That is correct yes, The root package controls all package stabilities.

**Comment by DarioSwain** [comment]
@alcohol @Seldaek Guys thanks for your response!

But it's not clear for me, for example in my root package i want to use dev package, with minimum-stability = stable by default, I can use it.
My package is dev, this is mean, i can use dev packages inside my first level dev package. 

What i want to see in this case

```json
{
  "name": "dario_swain/dependency-level-one",
  "type": "library",
  "require": {
    "dario_swain/dependency-level-two": "dev-master", // I add this package to my root like a stable, i understand all risks 
  }
}
```

In my two level package

```json
{
  "name": "dario_swain/dependency-level-two",
  "type": "library",
  "require": {
    "dario_swain/dependency-level-three":    "dev-master", // I see this dependency and understand all risks, before this i add dev version of package one in my root composer.json! 
    "some/stable-package": "1.0.0"
  }
}
```

I want to receive next packages:
 "dario_swain/dependency-level-two": "dev-master"
"dario_swain/dependency-level-three":    "dev-master"
"some/stable-package": "1.0.0"

But if i setup minimum-stability to dev i can receive:
 "dario_swain/dependency-level-two": "dev-master"
"dario_swain/dependency-level-three":    "dev-master"
"some/stable-package": "1.x-dev"

I don't want to receive "some/stable-package" in dev stability, i want to receive what is described in composer.json for package dario_swain/dependency-level-two, it is possible?
It's a correct assumption?

**Comment by alcohol** [comment]
Like I said, this will allow you to do that:

composer.json (root / level-one)
```javascript
{
  "name": "dario_swain/dependency-level-one",
  "type": "library",
  "require": {
    "dario_swain/dependency-level-two": "dev-master",
    "dario_swain/dependency-level-three": "dev-master"
  }
}
```

**Comment by stof** [comment]
@DarioSwain either you whitelist the packages for which you want to allow dev versions (this can be done either with a ``dev-master`` requirement or with a ``@dev`` requirement to give more flexibility on the ``dependency-level-two`` to change its constraint), or you set minimum-stability to dev and you set ``prefer-stable`` to ``true``, which means that Composer will use dev versions only when necessary

**Comment by DarioSwain** [comment]
@stof it's work like i said, many thanks guys!
