### ISSUE TITLE
Internal Error [ERR_INVALID], exit code 0 - XAMPP

### ISSUE THREAD

**Issue by languorous001** [composer/composer#4277]
I try to install Composer in XAMPP then error exit code 0.

I find the old issue 

https://github.com/composer/composer/issues/3324
http://abuango.net/2014/08/16/how-to-install-composer-on-windows-with-xampp/

and i edit config in php.ini

extension_dir="E:\Projects\1.IDE\XAMPP\php\ext"
browscap="E:\Projects\1.IDE\XAMPP\php\extras\browscap.ini"

but not work, I need recommend to install Composer in XAMPP

**Comment by languorous001** [comment]
I find the issue -> I install sqlsrv driver in XAMPP and I try uninstall sqlsrv driver -> I install Composer to success

**Comment by alcohol** [comment]
Does this mean you solved the problem..?

**Comment by languorous001** [comment]
Yes :')

**Comment by ZamanOof** [comment]
I Have the same problem :( any one know how to solve it @languorous001

**Comment by languorous001** [comment]
@ZamanOof first, you must check on error in php.exe. if have error you should fix it and next install composer.

**Comment by ZamanOof** [comment]
thank u @languorous001 
I solve it 
for windows 8 and above if they not install it in C partition 
they face the same issue so they should install composer in C partition and after install it they can       re install it in another partition 
i think its because of CMD permission 
regards
