### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages: in Ubuntu

### ISSUE THREAD

**Issue by piyushpallaw** [composer/composer#4281]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sensiolabs/security-checker v2.0.5 -> satisfiable by sensiolabs/security-checker[v2.0.5].
    - sensiolabs/security-checker v2.0.5 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 2
    - sensiolabs/security-checker v2.0.5 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - sensio/distribution-bundle v4.0.0 requires sensiolabs/security-checker ~2.0 -> satisfiable by sensiolabs/security-checker[v2.0.5].
    - Installation request for sensio/distribution-bundle v4.0.0 -> satisfiable by sensio/distribution-bundle[v4.0.0].

**Comment by alcohol** [comment]
Please share your composer.json when reporting an issue. We cannot identify the problem without any additional relevant information.

**Comment by piyushpallaw** [comment]
composer create-project symfony/framework-standard-edition SampleSymfonyProjectFirst

**Comment by alcohol** [comment]
Oh sorry I wasn't reading properly. You don't have the curl extension installed. Install it using your OS package manager or whichever way is most suitable on your environment.

**Comment by piyushpallaw** [comment]
Thanks, Its get installed."Some parameters are missing. Please provide them. database_port:"
What would be the database port value.
