### ISSUE TITLE
Passing auth credentials to Composer in non-interactive mode?

### ISSUE THREAD

**Issue by marcovtwout** [composer/composer#4285]
We are using Composer to require self-hosted svn packages. Normally, when running a `composer install`, the interactive prompt asks me to supply a username and password for Satis, svn, possibly a github token.

Now I want to run a `composer install` in non-interactive mode. The only way I found to do this, is to pre-configure these credentials in `auth.json` (according to https://getcomposer.org/doc/articles/http-basic-authentication.md). But this requires this file to be stored to disk (with the passwords in plaintext), and I don't want that.

Is there a way to pass these credentials directly to a composer command, without storing them in auth.json? I could imagine something like:
```
composer install --no-interaction --config http-basic {"example.org": {"username": "alice", "password": "foo"}
```

**Comment by slbmeh** [comment]
Writing them to a file and deleting it afterward is more secure than passing them on the command line IMO.

**Comment by Seldaek** [comment]
We could support a COMPOSER_AUTH env var that contains a json blob similar to auth.json, but yeah I am not sure if this is really needed or beneficial. Having them in the CLI means it appears in `ps aux` output and might end up stored in bash history etc. A user-read-only file is fairly safe in comparison.

**Comment by koenpunt** [comment]
In comparison; Bundler supports environment variables:

> CREDENTIALS FOR GEM SOURCES
       Bundler allows you to configure credentials for any gem source, which allows you to avoid putting secrets into your Gemfile.

>     bundle config SOURCE_HOSTNAME USERNAME:PASSWORD

> For example, to save the credentials of user claudette for the gem source at gems.longerous.com, you would run:

>     bundle config gems.longerous.com claudette:s00pers3krit


> Or you can set the credentials as an environment variable like this:

>     export BUNDLE_GEMS__LONGEROUS__COM="claudette:s00pers3krit"

**Comment by koenpunt** [comment]
I'm current using it in my CI setup like so:

```
composer config -a -g http-basic.packages.domain.com \
 $COMPOSER_PACKAGES__DOMAIN__COM_USERNAME $COMPOSER_PACKAGES__DOMAIN__COM_PASSWORD
```

And then I just set those 2 environment variables. 

But it would be great if this was "natively" supported.

**Comment by marcovtwout** [comment]
What is option -a in that scenario?

**Comment by koenpunt** [comment]
`--auth`

**Comment by hgati** [comment]
> 

Great Tip !
