### ISSUE TITLE
An autoload_classmap file path has changed with recent composer versions

### ISSUE THREAD

**Issue by phpguru** [composer/composer#4287]
We ran into a situation where running `composer selfupdate` has broken our vendor/composer/autoload_classmap.php file for one specific path in our dependency chain, and thus our web app gives a WPOD.

We tried running composer install on several known/good/working prior versions of composer.json & composer.lock on our project on several PHP versions and OSes, and definitely narrowed it down to the composer.phar version and not the composer.lock file.

We have narrowed it down to this version range - it works on and before Composer version 1.0-dev (8a154d73001f8d94a15618315a6831fed3266c85) 2015-04-14 22:51:12 but the behavior appears to have changed since then. Specifically, we need Cake app controller to come from 

`'AppController' => $baseDir . '/app/app_controller.php',`

...and after Apr 14, it appears composer is creating this path instead:

` 'AppController' => $vendorDir . '/gitaccount/framework/cake/libs/controller/app_controller.php',`

...and we can find no other changes to our dependencies that would indicate why this might have changed. Until we figure out why/what has changed, we're forced to use that specific version (8a154d73001f8d94a15618315a6831fed3266c85) of composer on our deploys. (There may be newer versions of composer that work; we didn't get that far in testing.)

Possibly related to #1790 or 943107cfe717a74aa791f57b87fa514c88582b0d

**Comment by alcohol** [comment]
That means your autoload definitions are a mess. You should look into cleaning them up :-).

**Comment by alcohol** [comment]
You will probably also see a lot of warnings during your autoload generation, notifying you about "Ambiguous class resolution".

**Comment by Seldaek** [comment]
Closing as there was no feedback, but if you do have those warnings please take a look at them and ask if you need help. If there were no warnings then it sounds horribly broken but I doubt you would be the only one to experience it then.
