### ISSUE TITLE
composer generated ClassLoader.php references non-existent LICENSE file

### ISSUE THREAD

**Issue by legoktm** [composer/composer#4288]
After building a composer autoloader, the `vendor/composer/ClassLoader.php` file has the following heading:
```
/*
 * This file is part of Composer.
 *
 * (c) Nils Adermann <naderman@naderman.de>
 *     Jordi Boggiano <j.boggiano@seld.be>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
```

but there is no LICENSE distributed. It may make sense to just include a url to the license instead.

**Comment by alcohol** [comment]
Maybe we just should not put this in said file. They are programmatically generated after all.

**Comment by stof** [comment]
@alcohol the file is just copied from the Composer source code unmodified.

**Comment by Seldaek** [comment]
I guess a search/replace while copying to point to the LICENSE file on github would be good enough yes. Anyone up for a PR? :)

**Comment by alcohol** [comment]
Or you could put the LICENSE file in `vendor/composer/` ?

**Comment by Seldaek** [comment]
Or that yes :) Anyway should be an easy fix.

**Comment by legoktm** [comment]
woot, thanks!
