### ISSUE TITLE
Implement option to ignore indirect platform requirements

### ISSUE THREAD

**Issue by curry684** [composer/composer#4289]
We are developing a framework which optionally supports using Mongo databases via Doctrine. Package `doctrine/mongodb` has a platform dependency on `ext-mongo`, which is fine and correct when installed directly (see https://github.com/doctrine/mongodb/issues/88). In our case however the availability of mongo is checked at runtime when its usage is configured. It's therefore fine to install the framework on a server that does not have `ext-mongo` yet, but we don't want to make it a suggested package either as it would require manual installation steps when it is needed later on. We prefer just showing the runtime error that Mongo is not available without the PHP module.

It makes sense in the case of frameworks and libraries to have the option to depend on libraries without failing on recursively discovered platform requirements. 

Ideally the option would switch nested platform requirements to 'Suggests' instead of 'Requires' so it still shows up during install/update, and issue warnings instead of errors when a platform requirement is installed but not of the correct version.

Right now we use `--ignore-platform-reqs` to install the entire framework on servers not using the Mongo facilities, but this is of course a weak solution as it also ignores the PHP version requirements and hard extension dependencies of the framework itself, and it disallows using central installer scripts or package managers. So it should be either a global switch for all nested dependencies, or configurable per dependency. I would argue the first as it's safer if a formerly safe library suddenly changes its config, or one of its own dependencies does.

My suggestion would be to add a [config option](https://getcomposer.org/doc/06-config.md) called `soften-platform-reqs`, defaulting to `false`, when enabled introducing this behaviour on all dependencies discovered below the current package (obviously not including the current package).

**Comment by alcohol** [comment]
No, you should just suggest `doctrine/mongodb` as a package to install with your framework. You should not automatically install it and then only use it if mongo is available.

**Comment by curry684** [comment]
That's one solution to the problem, and as explicitly said one that we chose with very good reason not to implement, as it would break our standardized APT-based deployments. We don't want our system administrators to know what Composer is, let alone use it, that's why we build the APT packages. In your solution he would have to issue specific composer commands on specific servers, in our solution he can just stick to the tools he knows at the sysadmin level. You're thinking from the perspective where every server is managed by a developer, which it neither is nor should be.

From a framework/library developer's perspective, the suggested solution makes perfect sense as it allows including third party libraries which may or may not be used depending on environment. And it fits in nicely with the existing platform requirement system as from the perspective of the `doctrine/mongo` developers it is completely correct to require the extension if someone explicitly references the library. The indirect reference by another package which consciously takes responsibility for it by setting the option is a completely logical and common scenario.

**Comment by curry684** [comment]
Also, I just realized, `suggests` is a completely broken solution for this issue as it has no version constraints. That will *terribly* break in a library like Doctrine.

**Comment by naderman** [comment]
If your library does not rely on doctrine/mongodb it should not specify it as a requirement. The only correct way I can see here is that you should have two projects, resulting in two APT packages. One that uses mongodb and requires the library as well as the extension and one that doesn't use mongodb and doesn't require either the library or extension. And then you simply deploy the APT package you want to actually use to respective servers?

**Comment by alcohol** [comment]
Exactly what @naderman said. You could implement such an approach perhaps by using metapackages as sources for your various apt builds.

I understand you want to streamline your process for a specific setup where certain people have specific roles and specific knowledge, but we simply cannot cater to each and every scenario imaginable.

**Comment by curry684** [comment]
Right, I'll just keep the `--ignore-platform-reqs` hack in the installer scripts. Beats me why that's an acceptable feature on the command line and not in the config, but not my call.

> I understand you want to streamline your process for a specific setup where certain people have specific roles and specific knowledge

This is **not** a specific setup where certain people have specific roles. In **every** big company out there the sysops and developers are different people. They think on different levels, they act on different levels. And most of all, they don't want to interfere (or oft even talk) with eachother. That's why developers make configurations and installers, so sysadmins can just run them, and return to their daily business of managing networks and SANs that programmers don't want to care about. That's why tools like Composer need to support advanced deployment options to become accepted in the corporate world.

**Comment by alcohol** [comment]
I have worked at big companies where that is not the case, so please do not try to argue your case by making things up. I understand this is your current situation and you are frustrated that things do not work the way you want them to work. But sometimes you have to accept that that is just the way things are. There are always alternatives.

Also, have you looked at https://getcomposer.org/doc/06-config.md#platform? If you must, you can pretend ext-mongodb is always installed by putting the following in your composer.json

```javascript
{
    ....
    "config": {
        "platform": { "ext-mongodb": "1.0" }
    }
}
```
