### ISSUE TITLE
Composer doesn't use the Git Data API for files over 1Mb

### ISSUE THREAD

**Issue by RMcLeod79** [composer/composer#4290]
When trying to do a composer update it keeps failing and asking for a GitHub OAuth token, this is entered but doesn't work.

Output of `composer update -vvv`

```
Reading ./composer.json
Loading config file /Users/richard/.composer/config.json
Loading config file /Users/richard/.composer/auth.json
Loading config file ./composer.json
Executing command (CWD): git describe --exact-match --tags
Executing command (CWD): git branch --no-color --no-abbrev -v
Reading /Users/richard/.composer/composer.json
Loading config file /Users/richard/.composer/config.json
Loading config file /Users/richard/.composer/auth.json
Loading config file /Users/richard/.composer/composer.json
Loading config file /Users/richard/.composer/auth.json
Executing command (CWD): git describe --exact-match --tags
Executing command (CWD): git branch --no-color --no-abbrev -v
Loading composer repositories with package information
Downloading http://packages.firegento.com/packages.json
Writing /Users/richard/.composer/cache/repo/http---packages.firegento.com/packages.json into cache
Reading /Users/richard/.composer/cache/repo/http---packages.firegento.com/include-all$8b15d40e226dbd6422e35f3ffa828378947f973b.json from cache
Executing command (/Users/richard/.composer/cache/vcs/git-github.com-WeareJH-magento-composer-autoloader.git/): git rev-parse --git-dir
Executing command (/Users/richard/.composer/cache/vcs/git-github.com-WeareJH-magento-composer-autoloader.git/): git remote -v
Executing command (/Users/richard/.composer/cache/vcs/git-github.com-WeareJH-magento-composer-autoloader.git/): git remote set-url origin 'git@github.com:WeareJH/magento-composer-autoloader.git' && git remote update --prune origin
Executing command (/Users/richard/.composer/cache/vcs/git-github.com-WeareJH-magento-composer-autoloader.git/): git show-ref --tags
Executing command (/Users/richard/.composer/cache/vcs/git-github.com-WeareJH-magento-composer-autoloader.git/): git branch --no-color --no-abbrev -v
Executing command (/Users/richard/.composer/cache/vcs/git-github.com-WeareJH-magento-composer-autoloader.git/): git branch --no-color
Executing command (/Users/richard/.composer/cache/vcs/git-github.com-WeareJH-magento-composer-autoloader.git/): git show 'master':composer.json
Executing command (/Users/richard/.composer/cache/vcs/git-github.com-WeareJH-magento-composer-autoloader.git/): git log -1 --format=%at 'master'
Reading composer.json of wearejh/magento-composer-autoloader (1.0.0)
Reading /Users/richard/.composer/cache/repo/git-github.com-WeareJH-magento-composer-autoloader.git/13b3ca0899fc86317574ef780e0c2313a6e8f224 from cache
Importing tag 1.0.0 (1.0.0.0)
Reading composer.json of wearejh/magento-composer-autoloader (1.0.1)
Reading /Users/richard/.composer/cache/repo/git-github.com-WeareJH-magento-composer-autoloader.git/60acce646b7850f8357e75c1c1620b93a4d59a80 from cache
Importing tag 1.0.1 (1.0.1.0)
Reading composer.json of wearejh/magento-composer-autoloader (v0.1)
Reading /Users/richard/.composer/cache/repo/git-github.com-WeareJH-magento-composer-autoloader.git/adf8123a403d0380150b939efc5e71da80dda393 from cache
Importing tag v0.1 (0.1.0.0)
Reading composer.json of wearejh/magento-composer-autoloader (master)
Reading /Users/richard/.composer/cache/repo/git-github.com-WeareJH-magento-composer-autoloader.git/4ba22d24f7d82ade87baec66687d836ba07150dc from cache
Importing branch master (dev-master)
Downloading https://api.github.com/repos/WeareJH/magento-ce
Downloading https://api.github.com/repos/WeareJH/magento-ce/contents/composer.json?ref=1.9

Could not fetch https://api.github.com/repos/WeareJH/magento-ce/contents/composer.json?ref=1.9, please create a GitHub OAuth token to go over the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+Richards-iMac.local+2015-07-24+1323
to retrieve a token. It will be stored in "/Users/richard/.composer/auth.json" for future use by Composer.
Token (hidden):
```
I then ran `composer diagnose` and the OAuth token came back as okay.

Looking further into the issue I tried going to the url of the package `https://api.github.com/repos/WeareJH/magento-ce/contents/composer.json?ref=1.9` and got the following error from GitHub.
```
{
  "message": "This API returns blobs up to 1 MB in size. The requested blob is too large to fetch via the API, but you can use the Git Data API to request blobs up to 100 MB in size.",
  "errors": [
    {
      "resource": "Blob",
      "field": "data",
      "code": "too_large"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/repos/contents/#get-contents"
}
```
The file size is 2.8M which is why it is failing. So it seems composer doesn't deal with this error correctly.

**Comment by alcohol** [comment]
wow.. that is really big.

I think it asks for your token because of the error the API returns. We only check the http status code, not the actual error. This is not an error I have seen before. We will have to find a way to deal with this particular scenario. 

On the other hand, I looked at the composer.json in that repository and I am pretty sure that it not a composer.json for a library.

/cc @stof do you know what it is? A Composer repository file maybe?

**Comment by alcohol** [comment]
Can you share your composer.json with us?

**Comment by RMcLeod79** [comment]
Looked into a bit further if you look at the `contents` payload for a repo there are a number of URLs
```
{
    "name": "composer.json",
    "path": "composer.json",
    "sha": "0542db1f1dcdf0b5868d6936a42b6cf25942e58f",
    "size": 2788473,
    "url": "https://api.github.com/repos/WeareJH/magento-ce/contents/composer.json?ref=1.9",
    "html_url": "https://github.com/WeareJH/magento-ce/blob/1.9/composer.json",
    "git_url": "https://api.github.com/repos/WeareJH/magento-ce/git/blobs/0542db1f1dcdf0b5868d6936a42b6cf25942e58f",
    "download_url": "https://raw.githubusercontent.com/WeareJH/magento-ce/1.9/composer.json",
    "type": "file",
    "_links": {
      "self": "https://api.github.com/repos/WeareJH/magento-ce/contents/composer.json?ref=1.9",
      "git": "https://api.github.com/repos/WeareJH/magento-ce/git/blobs/0542db1f1dcdf0b5868d6936a42b6cf25942e58f",
      "html": "https://github.com/WeareJH/magento-ce/blob/1.9/composer.json"
    }
```
I'm guessing composer is using either `url` or `self`which is failing, whereas if it used `git_url` or `git` it would work.

The reason the composer.json file in the repo is so large is that it contains a lot of mappings which are needed

**Comment by alcohol** [comment]
What does it need the mappings for? Cause those files literally just point to themselves. Like, pretty much all of them as far as I can tell.

**Comment by AydinHassan** [comment]
@alcohol It's retro-fitting into a tool which uses the mappings to install the library, it's something we have to use at the minute, we have a better solution in the pipe-line.

**Comment by AydinHassan** [comment]
Ok i've gotten around this by using the `no-api` flag for GitHub repo's. I'm guessing we can at least improve the error messages here if we don't provide a proper fix? Willing to chime in :)

**Comment by Seldaek** [comment]
AFAIK we never fetch the the dir listing, we just try to fetch composer.json via the contents API like https://api.github.com/repos/WeareJH/magento-ce/contents/composer.json (failing) or https://api.github.com/repos/composer/composer/contents/composer.json (working). So to fix this we need to detect catch that special 403 and treat it differently (probably we need to list the contents of the repository root and then fetch the composer.json via the git_url or something). The easy workaround would be if we get that 403 we just revert to using git (via `$this->setupGitDriver()`).

**Comment by AydinHassan** [comment]
Yo @Seldaek I just had a look at your proposition and it seems that `\Composer\Util\RemoteFilesystem::callbackGet` switches the error code, and at this point we have no other context. So all we have is a `403` error. So composer attempts to auth with GitHub when it doesn't need to, I think this is so because we don't actually have access to the github response, just the error code.

**Comment by Seldaek** [comment]
Yeah I can see that the question is what can we do about it, and should we
care at all? Because it's quite an edge case.

**Comment by AydinHassan** [comment]
I'm not bothered if we don't fix it, `no-api` does the trick and this is a temporary thing anyway. You can probably close this :)
