### ISSUE TITLE
Composer problem

### ISSUE THREAD

**Issue by ahmedeg** [composer/composer#4291]
when ever i try to install any thing i get

omposer create-project laravel/laravel BackEnd --prefer-dist

                                                                               
  [Composer\Downloader\TransportException]                                     
  The "http://packagist.org/p/provider-2013$194b38e7f969c856ab4678664fbce078a  
  7c83a974ea368b99cd07b5dfc90bb4f.json" file could not be downloaded (HTTP/1.  
  1 400 Bad Request)                                                           
                                                  

doing 
composer diagnose 

i get

Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: FAIL
[Composer\Downloader\TransportException] The "http://packagist.org/packages.json" file could not be downloaded (HTTP/1.1 400 Bad Request)
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking composer version: OK

While my machine can access it without issue

curl -S http://packagist.org/packages.json

{"packages":[],"notify":"\/downloads\/%package%","notify-batch":"\/downloads\/","providers-url":"\/p\/%package%$%hash%.json","search":"\/search.json?q=%query%","provider-includes":{"p\/provider-2013$%hash%.json":{"sha256":"194b38e7f969c856ab4678664fbce078a7c83a974ea368b99cd07b5dfc90bb4f"},"p\/provider-2014$%hash%.json":{"sha256":"5ac255ec8107d2df26c9251eb4779130e1dce580f9e46669cfb50b8ee826fd48"},"p\/provider-2014-10$%hash%.json":{"sha256":"e91d9ff029bb5291e1bb257a9573397477b74bd1b1c332c4311301764831522e"},"p\/provider-2015-01$%hash%.json":{"sha256":"b01cd82c45683677cea20b77654367abdcbab0c5c936cfc010398cc1d4cee41e"},"p\/provider-2015-04$%hash%.json":{"sha256":"68cb0755e536e9735a1485171dc19253eaef5df3e033e1cef6dacfd397589b1c"},"p\/provider-2015-07$%hash%.json":{"sha256":"c9e13a74023e36dea28653f9d140eb4ea0ee07f2bb232d164a98c18ca0f9a499"},"p\/provider-archived$%hash%.json":{"sha256":"dfa1d92d2697fc375a1d522ab573634ee18807646f4abc322b6933157a07b829"},"p\/provider-latest$%hash%.json":{"sha256":"38f748e3cf5530f3e279080e939c72cea4aecea19e7ace8c42ebae838acc7ab9"}}}

**Comment by vkollin** [comment]
Same Problem here with version 1.0.0-alpha10. With version 1.0.0-alpha9 it works fine.

with version 1.0.0-alpha10:
```
composer diagnose
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Failed to enable crypto
failed to open stream: operation failed
Checking HTTP proxy: FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Failed to enable crypto
failed to open stream: operation failed
Checking HTTP proxy support for request_fulluri: OK
Checking HTTPS proxy support for request_fulluri: FAIL
Unable to assess the situation, maybe github is down (The "https://api.github.com/repos/Seldaek/jsonlint/zipball/1.0.0" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Failed to enable crypto
failed to open stream: operation failed)
Checking github.com oauth access: FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/user/repos" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Failed to enable crypto
failed to open stream: operation failed
Checking disk free space: OK
Checking composer version: 

                                                                                                                                 
  [Composer\Downloader\TransportException]                                                                                       
  The "https://getcomposer.org/version" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:  
  error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol                                                            
  Failed to enable crypto                                                                                                        
  failed to open stream: operation failed                                                                                        
                                                                                                                                 


diagnose
```
I'm behind a proxy and we listened on the destination port 443 of our proxy - but no  requests where send somewhere ...

**Comment by ahmedeg** [comment]
Composer version 1.0-dev (c6cc6dd6070871f4b198ed39f76dd8047c116b02) 2015-07-21 13:46:38

and no proxy

**Comment by ahmedeg** [comment]
Composer version 1.0.0-alpha10 2015-04-14 21:18:51
work fine with me

After that

sudo composer selfupdate
Updating to version c6cc6dd6070871f4b198ed39f76dd8047c116b02.
    Downloading: 100%         
Use composer self-update --rollback to return to version 1.0.0-alpha10

composer --version
Composer version 1.0-dev (c6cc6dd6070871f4b198ed39f76dd8047c116b02) 2015-07-21 13:46:38

composer --version
Composer version 1.0-dev (c6cc6dd6070871f4b198ed39f76dd8047c116b02) 2015-07-21 13:46:38
DaTas-MacBook-Air:UmrahForThem-BackEND DaTa$ composer diag
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: FAIL
[Composer\Downloader\TransportException] The "http://packagist.org/packages.json" file could not be downloaded (HTTP/1.1 400 Bad Request)
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking composer version: OK


SO it's a version specific
