### ISSUE TITLE
not possible to set version using init command 

### ISSUE THREAD

**Issue by X-Coder** [composer/composer#4295]
The parameter for setting the version number is missing which makes it impossible to set the package version using the init command through console or API.

Its because https://github.com/composer/composer/blob/master/src/Composer/Command/InitCommand.php#L57 is commented out.

Maybe the line is commented out because "--version" conflicts with composer's other parameter showing its built version.

How can this be solved for the CLI?

By using the API I currently use this manual way as workaround which works:
```PHP
      $file = Factory::getComposerFile();
      $json = new JsonFile($file);
      $contents = file_get_contents($json->getPath());
      $manipulator = new JsonManipulator($contents);
      $manipulator->addMainKey('version', $newVersionNumber);
      file_put_contents($json->getPath(), $manipulator->getContents());
```

**Comment by alcohol** [comment]
Why would you need version anyway?

**Comment by X-Coder** [comment]
"Version" is in the composer.json specification + there is a init command for CLI for batch scripts, so I see no reason why the API should not fully support it through CLI.

In this case, I needed it, to initialize the version when I create a new package using the composer API, and later to update it. (Both using a batch script)

**Comment by alcohol** [comment]
Storing the version in composer.json should only be done if you cannot use proper versioning through tags, for example. In most cases, you do **not** want to actually put the version in your composer.json. See here for details: https://getcomposer.org/doc/02-libraries.md#specifying-the-version

**Comment by alcohol** [comment]
But I guess we could add support for it. Though it is bad practice, and generally we do not want to encourage bad practice.

**Comment by X-Coder** [comment]
I understand now, I will look into how can I optimize my build process.
