### ISSUE TITLE
Releasing without composer.json

### ISSUE THREAD

**Issue by RonRademaker** [composer/composer#4297]
Hi,

I'd like to be able to release our projects in production without a composer.json file. Of course in production none of us ever use composer update anyway (right? ;) ), so we should be able to work with just a composer.lock file. I see two advantages to being able to remove composer.json from our production environment: nobody will be able to accidentally break things by doing a composer update (or another composer command that changes the setup) and I think that combined with composer-installer this could lead to having a release process that involves uploading a single file (composer.lock) and executing composer install.

**Comment by alcohol** [comment]
In production you should not use composer at all. Nor git (git is not a deployment tool).

You should package your application in either an archive format such as tar, or use for example specfiles to turn it into an RPM or whichever package format your OS uses.

Your package should not contain any artifacts from your development environment. So remove configuration files for composer, git, etc. Delete all .git directories.

**Comment by RonRademaker** [comment]
Thanks, I guess that makes sense, even though I see a long road ahead to make something like that a reality.

**Comment by stof** [comment]
note that composer.lock alone is not enough to perform the full installation. The composer.json is still needed to get info about the root package, as they don't get duplicated into the composer.lock

**Comment by jagarsoft** [comment]
Excuse me @stof , but, why is not enough? Please consider
[https://www.engineyard.com/blog/composer-its-all-about-the-lock-file](url)
Thanks in advanced

**Comment by alcohol** [comment]
@jagarsoft `composer.json` contains more than just your requirements. It also contains a `config` section, and various other attributes, that are not stored in your `composer.lock` file. The `composer.json` file will always be more important than the `composer.lock` file.
