### ISSUE TITLE
Composer Download Error (Composer Setup Installer on Windows 7)

### ISSUE THREAD

**Issue by deviantpsyche** [composer/composer#4300]
When I try to install the Composer on Windows 7 I get the following errors:

Download failed: file_get_contents(): SSL: Handshake timed out
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed
Download failed: file_get_contents(): SSL: Handshake timed out
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed
Download failed: file_get_contents(): SSL: Handshake timed out
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed
The download failed repeatedly, aborting.

Can anybody please help with this?

My settings:
Windows 7 64-bit
PHP Version 7.0.0beta2 (I tired with version 5.5 and I'm getting the same error)
Apache 2.4.16

php.ini

openssl enabled
openssl.cafile=C:\php\certs\cacert.pem
openssl.capath=C:\php\certs

**Comment by deviantpsyche** [comment]
After 6 hours of frustration, I found the solution for this, I hope to save others from this nightmare:

Solution: In php.ini:

Change this:
default_socket_timeout = -1

To something like this:
default_socket_timeout = 360

**Comment by deviantpsyche** [comment]
I'm not sure why I had it set to -1, I just realized it's supposed to be set to 60 by default.....

**Comment by alcohol** [comment]
`-1` means it will never timeout if I am not mistaken. It is weird that setting an actual timeout value solved the problem for you. Did it immediately download after you changed the timeout? Or did it take a really long time to finish the install script?

**Comment by deviantpsyche** [comment]
Yes that's what I thought -1 meant as well, it pretty much immediately downloaded when I changed the timeout value.

**Comment by NeXTs** [comment]
Weird!
I had similar issue but my `default_socket_timeout` property was by default **60**
Once I've changed it to 360, composer has been immediately installed
