### ISSUE TITLE
Composer error when loading anything from github

### ISSUE THREAD

**Issue by geoffreymwangian** [composer/composer#4301]
I have previously being using composer without any troubles but an hour ago problems started when it requests for password tokens from github.After login in to github and getting the access token the transport exceptio error now shows

**Comment by alcohol** [comment]
Can you show us the actual errors and commands you are running? Please provide as much details as possible for us. So if you are trying to install or update, please run those commands like:

```
composer install|update -vvv --profile
```

Provide us with the full output (do not worry about the length).
