### ISSUE TITLE
Issue: Setting the COMPOSER Env has no effect on composer config repositories statement

### ISSUE THREAD

**Issue by henrikthesing** [composer/composer#4302]
Regarding to the documentation https://getcomposer.org/doc/03-cli.md#composer it should be possible to change the name of the configuration file from the default value composer.json to another filename (e.g. my-configuration.json). This works fine for command line statements like

COMPOSER=my-configuration.json php ./composer.phar require vendorname/my-package:dev-master

which will add the vendorname/my-package package to the require block in my my-configuration.json file.

But if I try to add a new repository for vendorname/my-package (because its a private package which is not available at packagist.org) with the following statement

COMPOSER=my-configuration.json php ./composer.phar config repositories.vendorname/my-package git https://url-to-my-private-git-repository.git

this information always will be written to the composer.json file which is located in the same directory as the my-configuration.json file.

Its seems that the COMPOSER Env setting variable has no effect on the [config] option.

**Comment by alcohol** [comment]
That is probably because `config` has the `--file` argument which you can use to specify a different configuration file. I suppose for consistency perhaps it would be nice if `COMPOSER` was also read and/or supported. For the time being you could use `--file $COMPOSER`?

**Comment by henrikthesing** [comment]
The --file workaround works pretty good. Thank you!
