### ISSUE TITLE
Composer update "package" downloads too many unnecessary stuff and become slow

### ISSUE THREAD

**Issue by ptheofan** [composer/composer#4308]
Hey guys,

When I run composer update with specific package
i.e.
```
composer update -vvv "angry-panda-soft/saas-clients"
```

I expect composer to download 
1. the target package
2. the dependencies of the package
3. other packages that reference this package as dependency and are listed in the project repo (composer.json)

these should be enough to properly resolve and update anything related.
Running in verbose mode I see that it actually downloads tons of stuff that are totally not needed or related to that package in any way.

Is this behaviour expected?
Needless to say this makes the update painfully slow over not so great connections.

**Comment by stof** [comment]
it downloads tons of stuff because some possible optimizations for partial updates are not yet implemented. See #3672

**Comment by ptheofan** [comment]
Makes sense! Thanks for the reference!
