### ISSUE TITLE
How do I remove composer?

### ISSUE THREAD

**Issue by dvichris** [composer/composer#4309]
Is there a way to completely delete it from my system? (osx) I've tried google and nothing shows up.

**Comment by milesj** [comment]
How did you install it? If you installed it through homebrew, just `brew uninstall composer`.

**Comment by dvichris** [comment]
I guess I installed it globally not with homebrew, am I safe to just delete the script from my /usr/local/bin?

**Comment by milesj** [comment]
I believe there's the executable and the `~/.composer/` folder. If anyone else has some input, feel free to chime in.

**Comment by dvichris** [comment]
Deleting the composer script cleared it up I guess, I had already deleted the .composer folder in my home directory but was still getting a return from the composer command.
