### ISSUE TITLE
Can't reinstall composer on Windows

### ISSUE THREAD

**Issue by mladenp** [composer/composer#4311]
I uninstalled composer from Windows and installed wamp instead of xampp and while installing composer i choose php.exe from wamp but composer still tells me i have it inside xampp and i can't install it again?
I don't have php inside my PATH.
So.. how to reinstall composer on windows?

**Comment by johnstevenson** [comment]
>but composer still tells me i have it inside xampp and i can't install it again

In what way exactly? What error message does the installer give you?

@alcohol Yup, the installer looks in the System and User paths for ```php.exe```

**Comment by mladenp** [comment]
i checked i didn't have php or composer in my paths, but after windows restart everything worked fine :) 
So i am guessing restart after uninstalling composer is a solution.

**Comment by johnstevenson** [comment]
@mladenp A Windows restart is not normally necessary, because the installer checks the current state of the paths via the registry (rather than reading cached data like some programs do).

Whatever, I'm pleaed you sorted it.
