### ISSUE TITLE
composer.json entry ignored when a replace package was previously used

### ISSUE THREAD

**Issue by Micr0mega** [composer/composer#4312]
# The issue
I'm having an issue where a package was used, which uses the 'replace' option. That package was replaced in the composer.json file, but composer.lock won't update properly. It keeps using the previously used package, which is not in the composer.json file anymore.

Additionally, when manually replacing composer.lock with a correct one, the incorrect package is still referenced by installed.json and autoload files.

# Steps to reproduce
These are the actual packages I am having trouble with.

composer.json:
```json
{
    "require": {
        "php-di/php-di": "5.*"
    }
}
```
Then run:
```bash
$ composer install
```
This results in the correct installation of the php-di package and its 3 dependencies, and a correct composer.lock file. Note that the php-di/php-di package replaces the mnapoli/php-di package.

Now, this is where the fun/trouble starts. When I switch to the mnapoli/php-di package, composer seems to ignore this. Here goes.

Update composer.json:
```json
{
    "require": {
        "mnapoli-di/php-di": "4.*"
    }
}
```
Then run:
```bash
$ composer update
```
Which results in the following output:
```
$ composer update 
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
```
Nothing to install or update? But I just replaced an entry in my composer.json...

```bash
$ composer show -i
container-interop/container-interop 1.1.0 Promoting the interoperability of container objects (DIC, SL, etc.)
php-di/invoker                      1.0.0 Generic and extensible callable invoker
php-di/php-di                       5.0.1 The dependency injection container for humans
php-di/phpdoc-reader                2.0.0 PhpDocReader parses @var and @param values in PHP docblocks (supports namespaced class names with the same resolution rules as PHP)
```
Hmm those are the packages from my previous composer.json file.

Well then, maybe generating a new composer.lock file will help:
```bash
$ rm composer.lock
$ composer install
```
But nope, this results in `Nothing to install or update` again with the same composer.lock file, and the exact same output for `composer show -i`. That being the wrong packages, the ones that were installed with the first composer.json file.

And even stranger, when I do have a correct composer.lock file which belongs to the second composer.json file (the one with mnapoli/php-di) and `composer install` is run, a mix of dependent packages is installed, but **not** the mnapoli/php-di package:
```bash
$composer show -i
container-interop/container-interop 1.1.0  Promoting the interoperability of container objects (DIC, SL, etc.)
doctrine/annotations                v1.2.6 Docblock Annotations Parser
doctrine/cache                      v1.4.1 Caching library offering an object-oriented API for many cache backends
doctrine/lexer                      v1.0.1 Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
mnapoli/phpdocreader                1.3.0  
myclabs/php-enum                    1.4.1  PHP Enum implementation
ocramius/proxy-manager              0.5.2  A library providing utilities to generate, instantiate and generally operate with Object Proxies
php-di/invoker                      1.0.0  Generic and extensible callable invoker
php-di/php-di                       5.0.1  The dependency injection container for humans
php-di/phpdoc-reader                2.0.0  PhpDocReader parses @var and @param values in PHP docblocks (supports namespaced class names with the same resolution rules as PHP)
zendframework/zend-code             2.5.2  provides facilities to generate arbitrary code using an object oriented interface
zendframework/zend-eventmanager     2.5.2  
zendframework/zend-stdlib           2.6.0  
```
The generated autoload files have php-di/php-di listed, while it is not in the composer.json or composer.lock file! His is a big issue for our production environment.

# Thoughts
This all seems to be related to the php-di/php-di package replacing mnapoli/php-di, and the fact that composer keeps track of installed packages in vendor/composer/installed.json. When removing the 'replace' entry, or deleting the file as a whole, things work as expected. But this is clearly not something that I prefer or can to do in a production environment.

**Comment by alcohol** [comment]
Composer also keeps tracks of what is installed in an `installed.json`. Since you still have the same library installed that replaces the library you just specified, technically speaking there is no need to do anything (current set of installed packages fulfills your requirements), so hence nothing happens.

**Comment by Micr0mega** [comment]
Right, that explains why the composer.lock keeps listing the replacing library when running `composer update`. It doesn't explain though, when using a lock file with the replaced package and running `composer install`, it still keeps the replacing package in my autoload files. The lock file contains the exact packages I want to use and I expect the autoload files to be generated accordingly. Is it intended behaviour not to?

**Comment by alcohol** [comment]
Why should it replace it? The existing package "replaces" the package you require. So it is valid. No action needs to be taken.

**Comment by Micr0mega** [comment]
Because I assume the composer.lock file to be leading in which packages should be used by the project, not a incidentally previously installed package. Is this an incorrect expectation?

**Comment by alcohol** [comment]
There are no correct expectations to be had when you deviate from normal install procedures. Composer tries to fulfil expectations to the best of its abilities. In this case, there is nothing to do.

**Comment by Micr0mega** [comment]
How am I deviating from normal install procedures? Having the same lock file can lead to different packages being used under these circumstances (e.g. in development vs production). I thought it to be the lock file's "job" to prevent this. I am not trying to prove you wrong, I am just hoping to understand what I am not getting here :-)

**Comment by masoninthesis** [comment]
Was there any solution to this? What IS the proper procedure? I keep deleting my .lock, installing/updating my .json, yet my .lock doesn't update.

**Comment by curry684** [comment]
Right now Composer prefers installed packages, derived from the `installed.json` file. So as long as the replacement is valid, it will indeed keep generating the same solution and thus lock. This is just because that's how Composer works internally.

To 'reset' it completely and make it rethink its installed packages (before it automatically 'corrects' because of package updates) you'd have to remove `vendor/composer/installed.json` as well as the lock. This will trigger a complete reevaluation of dependencies and reinstall. You could also just go for the full cleanup then and delete the entire vendor directory.

**Comment by masoninthesis** [comment]
Perfect. Worked like a charm. I've been trying to figure out for a couple weeks where it was pulling the old dependencies from. I hadn't looked inside the vendor folder. Thanks mate!

**Comment by Seldaek** [comment]
Note that generally deleting the offending dependency folder (i.e. the vendor/foo/bar) is sufficient, no need to wipe the whole vendor dir. Before updating, the packages from vendor/composer/installed.json are checked to be still present and if not they're removed from the installed repository before we proceed with the update.

**Comment by driskell** [comment]
I'm having this problem on several CI environments and many development machines. Some are using one package, some are using another.

Initially was required module-a which replaced module-old. I removed the requirement on module-old and it never removed it, so I had to wipe and set it up again and now the lock is all fine, fresh installs are perfect. However, all other existing installs on all other machines are still using the module-a, even though it is not references in the JSON or LOCK in any way. How do I remove it?

I even tried adding conflict on module-a but it seems to completely ignore it. I'm at a loss. All I can think is to go around all the machines and wipe everything but that will take a while. Any thoughts?

**Comment by Seldaek** [comment]
Most likely migrating to Composer 2.0 snapshots would fix it, but that's not quite ready for prime time so do at your own risk: `composer self-update --snapshot`

**Comment by driskell** [comment]
Ah thanks @Seldaek - do you know if there's any other workaround? I tried conflicts but no dice.
Issue is even using snapshot I'm going to have to update several production CI environments and track down several remote developers to update too.

I'm wondering if my only resort is to detect the module-a in vendor and try remove it in the build somehow before we run composer. But if there's any workaround within composer itself that'll simplify things.

**Comment by Seldaek** [comment]
Nope sorry it's a design flaw in Composer v1 that the installed packages are taken into account when doing dependency resolution, which sometimes leads to edge cases like what I assume you're seeing.

**Comment by driskell** [comment]
Thanks for confirming. I'll try to wrap the build tooling so it cleans up. :+1:
