### ISSUE TITLE
Blended repositories on composer require !

### ISSUE THREAD

**Issue by dlepaux** [composer/composer#4322]
Hi,

I'm trying to deploy my project with capistrano. And i use the command composer require [package].

![capture du 2015-07-31 09 40 01](https://cloud.githubusercontent.com/assets/3735879/9002789/662b2432-3768-11e5-83f3-f4e617f61627.png)

The hash of package is of an other package 

![capture du 2015-07-31 09 43 11](https://cloud.githubusercontent.com/assets/3735879/9002823/baac1cb4-3768-11e5-84d7-5a19744c4742.png)

So composer download really an other package !

Before i was make a mistake in the module-love-live-music, in the composer.json i had put the name of dynamix/harnak package. But this problem is solved for a long time.

I don't understand... What can i do?

Thank you

**Comment by alcohol** [comment]
Can you share your composer.json with us?

**Comment by stof** [comment]
wait, ``composer require`` as a deployment command ? this does not make sense.

**Comment by dlepaux** [comment]
Yes !

I think it's not realy necessary because in my deployment script. I use a platform for my projet, so i had by this may my modules..

```
{
	"name": "dlepaux/dynamix",
	"description": "Based on the Laravel Framework, it is an awesome CMS for anyone !",
	"keywords": ["cms", "framework", "laravel", "dynamix"],
    "authors": [
        {
            "name": "David Lepaux",
            "email": "d.lepaux@gmail.com"
        },
  		{
            "name": "Jordane Jouffroy",
            "email": "contact@jordane.net"
        }
	],
	"license": "MIT",
	"require": {
		"laravel/framework": "4.2.*",
		"nesbot/Carbon": "*",
		"phpunit/phpunit": "4.5.*",
		"dynamix/core": "1.*",
		"dynamix/i18n": "1.*",
		"dynamix/pager": "1.*"
	},
	"autoload": {
		"classmap": [
			"app/models",
			"core/controllers",
			"core/libraries",
			"app/database/migrations",
			"app/database/seeds",
            "workbench",
            "theme"
		]
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	},
	"extra": {
        "installer-paths": {
            "theme/{$name}": ["type:laravel-library"]
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}
```

**Comment by dlepaux** [comment]
Why @stof ?
