### ISSUE TITLE
Class Composer\Console\Application not found

### ISSUE THREAD

**Issue by XedinUnknown** [composer/composer#4323]
Hi,

I used PHP's `exec()` to install Composer locally, like this:
```
"\path\to\php.exe" "\path\to\composer-installer.php" --filename="composer.phar" --install-dir="\local\path\to\composer" --no-ansi 2>&1
```

After this, I extract the PHAR archive into the same directory.  
Then, I created a composer.json file that looks like this
```json
{
    "name": "My Name <and@email.com>",
    "require": {
        "monolog/monolog": "1.0.*"
    }
}
```
The first time I run `"\path\to\php.exe" "bin\composer"` in CLI to dependencies, it seems to run correctly
```
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing monolog/monolog (1.0.2)
    Loading from cache

Writing lock file
Generating autoload files
```

However, if I run the exact same command immediately after, it doesn't work
```
PHP Fatal error:  Class 'Composer\Console\Application' not found in \local\path\to\composer on line 42
PHP Stack trace:
PHP   1. {main}() \local\path\to\composer:0

Fatal error: Class 'Composer\Console\Application' not found in \local\path\to\composer on line 42

Call Stack:
    0.0003     337352   1. {main}() \local\path\to\composer:0
```

Any subsequent attempts produce the same result, which obviously doesn't change if I add more verbosity, since this happens in the very beginning of execution. Overwriting all extracted files again allows me to run the `install` command once again, and ending up in the same way. I noticed that after I run `install`, vendor/composer/autoload_namespaces.php changes.

Was
```php

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
'Symfony\\Component\\Process\\' => array($vendorDir . '/symfony/process'),
'Symfony\\Component\\Finder\\' => array($vendorDir . '/symfony/finder'),
'Symfony\\Component\\Console\\' => array($vendorDir . '/symfony/console'),
'JsonSchema' => array($vendorDir . '/justinrainbow/json-schema/src'),
'Composer' => array($baseDir . '/src'),
);
```

After `install`
```php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Monolog' => array($vendorDir . '/monolog/monolog/src'),
);
```

I imagine, the main `Application` class is not being found because the Composer path is no longer included in the autoloader list. However, I can't figure out why. Perhaps I didn't install it right? When I run `install` with `-vvv` the first time, one of the lines is as follows:
```
Failed to initialize global composer: Composer could not find the config file: C:/Users/my_username/AppData/Roaming/Composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
```

**Comment by alcohol** [comment]
> After this, I extract the PHAR archive into the same directory.

What do you mean by that?

**Comment by XedinUnknown** [comment]
@alcohol,

```php
$archive = new Phar( $archivePath );
$archive->extractTo( $this->getComposerDir(), null, true );
```

**Comment by alcohol** [comment]
Well that explains it... you extracted Composer's source code, and then overwrote its dependencies with your own project dependencies. I have no idea why you would do that, cause it certainly is not documented anywhere.

Just run `php composer.phar install`.

**Comment by XedinUnknown** [comment]
I run `"path\to\php.exe" "\paht\to\composer.phar" install 2>&1`, but this instructs Composer to install dependencies, which I have none of, since this is a PHAR archive newly downloaded by your install script, and nothing else. What dependencies did I overwrite, if there were never any?

I extract Composer because I would like to also use some if it's procedures from within my PHP application. It's not documented anywhere, but running a PHAR is the same thing really, it's just bundled.

**Comment by alcohol** [comment]
You are not making any sense, sorry. If you want to use Composer internals, then you should add composer as a dependency to your project. But you should not extract the composer binary. There is a difference between using it as a library and using it as an application. You cannot do both with the same set of files.

**Comment by XedinUnknown** [comment]
Fair enough. What would be the best way then to interface with selected components of Composer from a PHP application, while still having those components perform their tasks as expected?

One of the things that I would like to do is to have multiple composer.json files in different directories, one per module of my application, which altogether will provide a description of what is required for the whole project to run. Once in a while, I would like Composer to update it's local, centralized cache, e.g. the _vendor_ folder, with the libraries from that description. After each update, I would like to be able to programmatically acquire information about what it did during the last update. Based on this I would like to update some metadata on my modules, create some symlinks to directories within the _vendor_ folder etc. I would also like to be able to get information on each individual installed package, such as what version it is currently at, whether it can be updated according to the composer.json definition, etc. Could you kindly point me in the right direction?

Also, is there a specific reason why Composer cannot be used when extracted? Perhaps there are just some environment variables that need to be set? The current working directory maybe?

Thanks a lot in advance. The product is awesome. I was just hoping that I could use it in PHP, much like other PHP tools for PHP.

**Comment by alcohol** [comment]
> Also, is there a specific reason why Composer cannot be used when extracted? Perhaps there are just some environment variables that need to be set? The current working directory maybe?

I think you are missing the point I am trying to make. There is a difference between using Composer as a tool to manage your dependencies, and using it as a dependency in your project (a library you "require"). You make it sound like you can only do one of the two. But you can do both. You can download Composer, and then use Composer to install "composer/composer" as one of the dependencies of your project. They are not the same things.

**Comment by XedinUnknown** [comment]
Nono, I got that from your previous post. But if I install "composer/composer" as a dependency, then I won't be able to use it for managing dependencies. I'm going to have to use the Phar binary for that. They are not the same thing, as you said. Or am I misunderstanding something again?

Maybe I should rephrase: I want to use Composer to manage dependencies, but I want to hook into it to possibly change the way it does some things, and also to use some of it's functions in my own application.

**Comment by alcohol** [comment]
I would recommend against that. Composer internal API is not set in stone and is subject to change. You could instead wrap Composer using the symfony/process library if you really want to do something like this.

**Comment by XedinUnknown** [comment]
Right. So, it seems that the only way is to create a PHP wrapper for the CLI tool.
But what about the questions I ask [here](https://github.com/composer/composer/issues/4323#issuecomment-126948051)? Do you have any advice as to what CLI commands are best suited for that?

**Comment by XedinUnknown** [comment]
I think I've found something that could at least provide both a CLI interface, and make the Composer classes available to me in PHP, [here](https://github.com/eviweb/composer-wrapper/blob/master/src/evidev/composer/Wrapper.php).

**Comment by alcohol** [comment]
Regarding your question earlier, while I understand what you want to accomplish, I have to tell you that Composer simply was not meant for such scenarios. I am not saying it cannot be done. But it simply is not the goal of Composer to provide for such use-cases.

**Comment by XedinUnknown** [comment]
Ok. If you wish, you can close this thread. I would, however, like to comment about my findings later on, when I accomplish what I want.

**Comment by Seldaek** [comment]
Closing then but yes feel free to add new comments.
