### ISSUE TITLE
How to retrieve all versions of packages in a Repository?

### ISSUE THREAD

**Issue by MalteWunsch** [composer/composer#4328]
[In alpha6 and earlier, FilesystemRepository->write() used $this->getPackages()](https://github.com/composer/composer/blob/1.0.0-alpha6/src/Composer/Repository/FilesystemRepository.php#L77), resulting in all versions of same named packages being dumped.

That changed in https://github.com/composer/composer/commit/5264d0637be7c0d16a6265fa504ae226ee4bcf01. Now it's $this->getCanonicalPackages(), resulting in only one version per package name being dumped. In #4324 I thought this might be an error at first, but the failing tests are an indication it's now meant to be that way. Of course, composer is alpha, so there might be API changes.

But for our internal Satis-like composer packages repository, we still need a method that dumps all the versions of same named packages. Is there any replacement API-wise or should I implement my own Filesystem(or whatever)Repository?

**Comment by alcohol** [comment]
The internal API is indeed not stable. We understand there are use-cases, but at this point in time we cannot hard-commit to maintaining backwards compatibility. There is quite some work planned on improving this in the future, but it's a step-by-step process :-)

Sticking to the alpha releases is your best bet for now, but even those can contain BC breaking changes. So, always test before upgrading.

**Comment by Seldaek** [comment]
@MalteWunsch the composer code assumes that a writable repo only ever has one of each package at most as this is a constraint of composer, so it might be safer for you to implement your own, or extend and overwrite the write() function, it doesn't have a whole lot of logic anyway so it's not so bad to duplicate IMO.

**Comment by MalteWunsch** [comment]
Thanks to both of you - extending and overwriting that's exactly what I've done.
