### ISSUE TITLE
Support letters in version strings

### ISSUE THREAD

**Issue by binarykitchen** [composer/composer#4330]
This bug report over there explains all
http://trac.roundcube.net/ticket/1490475

Version strings such as `1.3.0r5` should be supported.

**Comment by alcohol** [comment]
To some extend we want to add support for metadata. 

We were actually discussing this earlier today [here](/composer/semver/pull/13/files#r36172250).

What falls under metadata is subjective though. Should we just ignore everything appended to a M.m.p (Major.minor.patch) version string, with the exception of recognized stability modifiers and such, or only allow certain patterns?

**Comment by binarykitchen** [comment]
i recommend to follow the semversioning rules. look at chapter 10 in http://semver.org

*Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.*

**Comment by alcohol** [comment]
I agree. But then the versions mentioned in your trac ticket would still be considered invalid. `1.3.0r5` does not follow the definition of metadata. Nor any of the other definitions listed on http://semver.org.

**Comment by binarykitchen** [comment]
then it is time to contact the maintainers of these bad packages - who does this and "teaches" them?

**Comment by alcohol** [comment]
They might already be following semver rules for their new versions. On the other hand, they're PEAR packages, so I wouldn't hold my breath. Either way, this error will keep showing up in verbose mode because Composer will just keep ignoring old versions. it's not all that big of a deal.

**Comment by stof** [comment]
@alcohol the issue with ignoring silently anything we can't parse by taking the beginning of the string as version number is that it makes it harder to spot typos or thing like that, as they would just be accepted differently.
So I would suggest sticking to semver metadata here.

**Comment by alcohol** [comment]
@stof that would definitely have my preference too :-)

**Comment by Seldaek** [comment]
As far as I can tell, those warnings are all from ages-old PEAR packages, which have old tags that are invalid. The fact that they are invalid is not a big deal as these old tags probably don't have composer.json files in them so they would anyway be ignored. Those warnings are there for debugging purposes and do not mean that anything is wrong really.

**Comment by stof** [comment]
@Seldaek they should maybe be moved to a higher verbosity level though, so that they only appear when you are debugging, not when you want to see the list of changes)

**Comment by Seldaek** [comment]
Yeah that's a good point, done

**Comment by binarykitchen** [comment]
great, thanks
