### ISSUE TITLE
provide/replace/conflict ignored in repositories

### ISSUE THREAD

**Issue by nazar-pc** [composer/composer#4334]
```json
{
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "modules/Http_server",
                "version": "0.15.0+build-24",
                "require": {
                    "react/http": "0.4.*"
                },
                "dist": {
                    "url": "/web/cscms.org/www/components/modules/Composer/empty.zip",
                    "type": "zip"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "modules/WebSockets",
                "version": "0.31.0+build-49",
                "provide": {
                    "react/socket": "0.4.1",
                    "react/stream": "0.4.1"
                },
                "dist": {
                    "url": "/web/cscms.org/www/components/modules/Composer/empty.zip",
                    "type": "zip"
                }
            }
        }
    ],
    "require": {
        "modules/Http_server": "0.15.0+build-24",
        "modules/WebSockets": "0.31.0+build-49"
    }
}
```
Even though fake package `modules/WebSockets` provides both `react/socket` and `react/stream` of proper versions, original versions are still installed, while this is not correct.
Initially reported as https://github.com/francoispluchino/composer-asset-plugin/issues/132, but turns out to be Composer issue.

**Comment by alcohol** [comment]
What exactly are you trying to achieve? I am sure this is not your actual real life use-case. So could you share the real scenario with us?

**Comment by nazar-pc** [comment]
#### Here is complete story:
I'm author of [CleverStyle CMS](https://github.com/nazar-pc/CleverStyle-CMS) (which has Composer integrated), it comes with bundled jQuery, UIkit and some other required frontend libraries out of the box (these versions sometimes patched for proper WebComponents support, so they are just present here).

In addition to Composer itself I've integrated [Composer asset plugin](https://github.com/francoispluchino/composer-asset-plugin) to achieve flawless integration of Bower and NPM packages dependencies just like regular Composer dependencies for CleverStyle CMS's packages.

But here is the trick, many Bower packages depend on jQuery, this causes a huge time penalty when resolving dependencies due to downloading multiple jQuery versions and choosing suitable one, while I already have jQuery in place.

This was initial issue - to ignore packages, that already present due to whatever reason, but this doesn't work and root issue is Composer itself, not Composer asset plugin [as I thought initially](https://github.com/francoispluchino/composer-asset-plugin/issues/132).

CleverStyle CMS has own internal packaging system and Composer is not the only way to specify dependencies, so `composer.json` is actually generated on-fly and doesn't interact with user at all, everything happens automatically under the hood (if there are no unresolvable conflicts). That is why I need a way to ignore some packages by marking them as already present.

**Comment by alcohol** [comment]
Yikes.

**Comment by nazar-pc** [comment]
Short story is simpler: I have packages definitions under `repositories` key and provide/replace/conflict keys in package definition are ignored, while I expected them to work. So this is a bug I think.

**Comment by stof** [comment]
``provide`` does not forbid to have the actual package to be installed at the same time. It is not meant to be used to replace existing packages

**Comment by nazar-pc** [comment]
https://getcomposer.org/doc/04-schema.md#provide
> List of other packages that are provided by this package. This is mostly useful for common interfaces. A package could depend on some virtual logger package, any library that implements this logger interface would simply list it in provide.

Doesn't this mean that only one package that provides something can be installed at a time? Also, same story about `replace` and `conflict` keys - they are all ignored completely.

For instance, https://getcomposer.org/doc/04-schema.md#conflict
> Lists packages that conflict with this version of this package. They will not be allowed to be installed together with your package.

But they are successfully installed.

**Comment by stof** [comment]
> Doesn't this mean that only one package that provides something can be installed at a time?

no. You can install many loggers providing implementations of the same interface.

**Comment by nazar-pc** [comment]
Well, this sounds weird, because finally two packages will be responsible for the same class/interface in autoloader.
At least `conflict` is clear, but it doesn't work either.

**Comment by stof** [comment]
@nazar-pc ``provide`` is not for the package defining the interface. It is for packages providing an implementation

**Comment by nazar-pc** [comment]
Thanks for clarification.
Just checked with recent version, `replace` seems to work indeed.
