### ISSUE TITLE
Unable to downgrade deps with ^ requirements

### ISSUE THREAD

**Issue by hanovruslan** [composer/composer#4337]
For example if there is a dep 

```
{
   "some/package": "^x.y"
}
```

or

```
{
   "some/package": "x.y.*"
}
```

then it's unable to rollback by command

```
composer require some/package:^x.(y-1)
```

But next command works fine

```
composer require some/package:x.(y-1).*
```

P.S.: -vvv option show no errors
P.P.S.: Occurs on symfony/symfony package for me

**Comment by stof** [comment]
@hanovruslan ``^1.2`` means ``>= 1.2, < 2.0``. ``^1.1`` means ``>= 1.1, < 2.0``, which still allows the 1.2 version. Given that Composer uses the highest allowed version, it does not force a downgrade as the latest version is still allowed by your constraint

**Comment by hanovruslan** [comment]
@stof thanks! Sorry for misunderstanding.
