### ISSUE TITLE
Composer Truck Factor

### ISSUE THREAD

**Issue by gavelino** [composer/composer#4338]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Composer** and obtained a value of **2**.

The developers responsible for this TF are:

Jordi Boggiano - author of 64% of the files
Nils Adermann - author of 17% of the files

To validate our results, we would like to ask **Composer** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Composer**?

(b) Do you agree that **Composer** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Composer** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by alcohol** [comment]
The following is merely my personal opinion;

a) I think that is a reasonable statement to make. They have contributed by far the most and paved the way for the rest of us.

b) As an open source project, Composer is not that susceptible I believe. Yes, their knowledge is invaluable and would be hard to replace, but not impossible. (Lack of) Ownership could present issues though.

c) The fact that it is PHP, and open source, both contribute to that. The most complex part of Composer would definitely benefit from some documentation however (read: the solver), and I don't just mean basic API documentation.

**Comment by Seldaek** [comment]
Closing as IMO @alcohol has answered it just fine.
