### ISSUE TITLE
artifacts not correctly used/priorized

### ISSUE THREAD

**Issue by Flyingmana** [composer/composer#4339]
https://travis-ci.org/Cotya/magento-composer-installer/jobs/74691383

json file in one of the fullstack Tests

https://github.com/Cotya/magento-composer-installer/blob/3.0/tests/MagentoHackathon/Composer/FullStack/Regression/Issue139Test.php#L30

I create an artifact with version 999.0.0 before the tests are run.

in earlier versions that worked.
Now not, because of reasons I dont understand. It now takes version 3.0.5 instead.
`Installing magento-hackathon/magento-composer-installer (3.0.5)`

Update:

I tried a more simple case.

composer.json:  
```json
{
    "repositories": [
        {
            "type": "composer",
            "url": "http://packages.firegento.com"
        },
        {
            "type": "artifact",
            "url": "/work/magento/composer-installer/tests/FullStackTest/artifact/"
        }
    ],
    "require": {
        "magento-hackathon/magento-composer-installer": "*"
    },
    "extra": {
        "magento-deploysttrategy": "copy",
        "magento-force": "override",
        "magento-root-dir": "./"
    }
}
```

some output:   
```
...
Found package magento-hackathon/magento-composer-installer (99.5.0) in file magento-hackathon-magento-composer-installer-99.5.0.zip
...
Found package magento-hackathon/magento-composer-installer (999.0.0) in file magento-hackathon-magento-composer-installer-999.0.0.zip
...
  - Installing magento-hackathon/magento-composer-installer (3.0.5)
    Downloading: 100%         
    Extracting archive
```

I have two versions in my artifact directory which are higher as you see, still it installs the `3.0.5`

**Comment by alcohol** [comment]
Move your artifact above your composer repo.

**Comment by Flyingmana** [comment]
I see, that works for the simple case, but it seems not for all the cases in my tests.
