### ISSUE TITLE
A feature request: Add a possibility chosen files within "autoload_files" to be loaded conditionally based on PHP version.

### ISSUE THREAD

**Issue by ivantcholakov** [composer/composer#4340]
I am making a platform that is distributed publicly, it covers PHP 5.3 - PHP 5.6. Certain demo tests are disabled in lower PHP version easyly - I can avoid loading classes. But some packages like Guzzle (version 6) https://github.com/guzzle/guzzle contain 'autoload_files' directive and on PHP 5.3 system these files cause PHP parser error because of the short array syntax.

Is it possible the 'autoload_files' directive to extended somehow, so selected files to be loaded only when the PHP version of the actual machine matches or it is greater than the specified for each file? I mean as a target the composer.json of the application, not the packages.

**Comment by alcohol** [comment]
That does not make sense. Guzzle 6 does not run on 5.3, so Composer would never install it if your environment is running 5.3.

**Comment by ivantcholakov** [comment]
It makes sense. The platform is distributed publicly, it has the ability to detect what is supported on a concrete machine. And demo/test pages are enabled accordingly. Minimal required version for Composer is 5.3.2 as far as I know. If the machine version is lower, the Composer autoloader file simply is not loaded, nothing fails.

The problem is that this logic can not be applied for immediately loaded by Composer files, they can not be disabled on condition.

**Comment by alcohol** [comment]
I think you misunderstood what I meant.
A `composer install` would not install Guzzle 6 if the environment was running PHP 5.3.

**Comment by ivantcholakov** [comment]
I don't use Composer as a deployment tool. I commit within the distribution package composer.json, composer.lock and the whole vendor/ directory. I develop on PHP 5.6 and test on PHP 5.3, etc.

**Comment by alcohol** [comment]
You should instead release different distributions of your application based on target platform. What you are asking for is simply not something Composer supports.

**Comment by Seldaek** [comment]
@alcohol I think you missed the point here :)

@ivantcholakov as far as I understand, what you want to do is define the minimum target platform in the composer.json like we do for composer itself: https://github.com/composer/composer/blob/master/composer.json#L40-L44 

Once you do that, if you do composer update it'll make sure to install only packages that work with php 5.3, so you don't get bad surprises from using guzzle in development on 5.6 and then it breaks for the 5.3 users.

**Comment by alcohol** [comment]
@Seldaek as I understood it, he wants to load different libraries based on what target platform his (prepackaged) distribution gets installed on, which is something Composer does not support.

**Comment by ivantcholakov** [comment]
Not on my platform, but on a temporary testing project I can use the "all (on PHP >= 5.5) or nothing" approach https://github.com/ivantcholakov/codeigniter-restserver-test/blob/v2.7.2.11/application/config/config.php#L133

But this is not the solution, because possibility other packages with lower supported PHP version to be installed should remain.


Here is an ugly idea for illustration of the problem, if this
https://github.com/ivantcholakov/codeigniter-restserver-test/blob/v2.7.2.11/application/vendor/composer/autoload_real.php#L52
was:

```php
if (!function_exists('composerRequire54058c9d5fd9edc6c7a76b6c9c5c789d'))
{
    function composerRequire54058c9d5fd9edc6c7a76b6c9c5c789d($file)
    {
        require $file;
    }
}
```
then I could have made my own version of this function that would scan for these 3 file names:
https://github.com/ivantcholakov/codeigniter-restserver-test/blob/v2.7.2.11/application/vendor/composer/autoload_files.php#L9
for avoiding including them if PHP < 5.5. This is the ugly way I can see.

**Comment by Seldaek** [comment]
Ok then I guess I missed the point too :) Anyway @ivantcholakov what you could do if you are shipping a custom application is to skip including the vendor/autoload.php and instead include a copy of it that you make and modify. It should be fairly safe as this stuff does not change all too much, and you should still benefit from the vendor/composer/autoload* files generation from composer.

**Comment by ivantcholakov** [comment]
Thank you, both of you.
