### ISSUE TITLE
Composer Update Issue

### ISSUE THREAD

**Issue by narangrishab** [composer/composer#4341]
Your github oauth token for github.com contains invalid characters: "Composer"          
I'm facing this issue using Laravel 5.1 after updating composer. 

@alcohol

**Comment by alcohol** [comment]
Can you show the contents of ~/.composer/auth.json (and/or config.json) ?

**Comment by narangrishab** [comment]
@alcohol Hey. I fixed the issue. The issue was coming with Oauth token for composer. I never came across this issue before. Nevertheless, thank you.

**Comment by alcohol** [comment]
Ok, glad to hear you resolved it yourself :-).

**Comment by Ianluyon** [comment]
hey how u resolve it

**Comment by JR0122** [comment]
how do you resolve the issue?

**Comment by palomamtnez** [comment]
In my case, I deleted the file `~/.composer/auth.json`, so when I ran the `composer update` command, it asked me for the token again and saved it successfully in the same location.

**Comment by freddiegar** [comment]
Maybe you need this because: https://github.blog/changelog/2021-03-31-authentication-token-format-updates-are-generally-available/

`composer self-update`

> @see https://getcomposer.org/changelog/2.0.12

**Comment by hkbertoson** [comment]
> on my case I had a wrong ~/.composer/auth.json line. Just remove the line:
> 
> ```
>     "github-oauth": {
>         "github.com": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
>     },
> ```
> 
> and run composer again

This worked great in my case.
