### ISSUE TITLE
dump-autoload --no-dev should not dump require-dev packages and dependents

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#4343]
Issue spawned from #4252 - This can be used for the implementation https://github.com/composer/composer/blob/master/src/Composer/Installer.php#L285-L304 but it should first be made a bit more reusable (probably still needs to be on the Installer itself though as it depends on so much of its internal methods, and refactoring that is another task than this issue).

**Comment by SpacePossum** [comment]
:+1: anyone working on this? I might take a look when I find the time...
