### ISSUE TITLE
composer config -g: "--file and --global can not be combined"

### ISSUE THREAD

**Issue by furey-imagination** [composer/composer#4344]
As of this morning (having worked without issue for the past 5 months), when running…

```
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer
composer config -g github-oauth.github.com <TOKEN>
```

…at the end of a Docker build process, composer has started throwing the following error:

```
[RuntimeException]                       
--file and --global can not be combined  
```

Has there been an update to composer in the past 24 hours that may be causing this new exception?

Any help would be greatly appreciated.

**Comment by petrabarus** [comment]
+1

**Comment by mstrazds** [comment]
+1 same issue

**Comment by digital-syd** [comment]
+1

**Comment by petrabarus** [comment]
Is there a way to install certain version of composer? My previous working composer was `c83650f299cfff1049cd61ea72ee5345bd4f92d3`

**Comment by petrabarus** [comment]
For quick fix, I added this line.
```
composer self-update 1.0.0-alpha10
```

**Comment by michalmoczynski** [comment]
+1

**Comment by damiandennis** [comment]
+1

**Comment by furey-imagination** [comment]
@petrabarus Your quick fix is a great work around. Thanks!

Hopefully an official patch/explanation will be released soon?

(ping @Seldaek)

**Comment by nr404** [comment]
+1

**Comment by dansoap** [comment]
+1

**Comment by Seldaek** [comment]
Sorry folks, just woke up over here, but given the simplicity of the fix I am a bit disappointed nobody cared to look at the code and sent a PR instead of +1ing away :)

Anyway composer self-update should get you back to a fully working state.

**Comment by furey-imagination** [comment]
@Seldaek Appreciate the fix. Cheers!

**Comment by nr404** [comment]
@Seldaek thank you

**Comment by mstrazds** [comment]
@Seldaek Thank you! Very good point.
