### ISSUE TITLE
curl SSLRead() return error -9806

### ISSUE THREAD

**Issue by tschroeter** [composer/composer#4346]
Hello, since a few hours i am unable to execute on my local network:

curl -vsS https://getcomposer.org/installer | php

After some time:  SSLRead() return error -9806 occurred.

My server doesn't have this problem !?

**Comment by tschroeter** [comment]
after getting a new ip address the first request curl -vsS https://getcomposer.org/installer responds and the second doesn't !? What the hell happens here !?

**Comment by alcohol** [comment]
Are you on OSX?

**Comment by tschroeter** [comment]
yes i'm on OSX. now in the office it works. i try it again at home in the evening. but it seems there's any issue with my fritz box router at home because after getting an new ip address the first request responds and the second not

**Comment by wdrews** [comment]
@tschroeter : any news on this? i noticed the same problem here ...
