### ISSUE TITLE
Version 1.0-dev?

### ISSUE THREAD

**Issue by hanxue** [composer/composer#4348]
Hello,

When I look at the list of tags (releases), the latest is `1.0.0-alpha10`. However, running `self-update` will update it to `1.0-dev`. 

```
$ composer self-update
Updating to version a979cc78ed141855a76b7f196d24205c41107bbc.
    Downloading: 100%         
Use composer self-update --rollback to return to version 1.0.0-alpha10
$ composer --version
Composer version 1.0-dev (a979cc78ed141855a76b7f196d24205c41107bbc) 2015-08-11 10:20:39
```

Is this an unofficial release? If yes, I can create a new version for the Homebrew-PHP formula.

**Comment by stof** [comment]
it is the nightly build

**Comment by alcohol** [comment]
Nightly isn't exactly accurate. It's just the master branch (alias: `"dev-master": "1.0-dev"`).

**Comment by stof** [comment]
@alcohol true. It is build after each commit, not only each night
