### ISSUE TITLE
'Support' properties not working

### ISSUE THREAD

**Issue by joeconradt** [composer/composer#4349]
I have a test repo that has support properties defined in the composer.json per spec: https://getcomposer.org/doc/04-schema.md#support

    "support": {
        "email": "joseph.conradt@coursebit.net",
        [...]
    },

However, these properties don't seem to be passed in to CompletePackage::setSupport(). I'm using the post-package-install script to get package info like this:

composer.json

    "post-package-install": [
        "Inkstand\\Component\\Composer\\PackageEvents::postPackageInstall"
    ]

Then:

    public static function postPackageInstall(PackageEvent $packageEvent)
    {
        $installedPackage = $packageEvent->getOperation()->getPackage();
        $support = $installedPackage->getSupport(); // <- Empty array
    }

Yet the support info is populated on packagist:
https://packagist.org/packages/coursebit/inkstand-plugin-test 

And I have confirmed the support part of the config is not being passed in if I print out the $config array in ArrayLoader::load()

    [12-Aug-2015 03:58:44 Europe/Berlin] Array
    (
        [name] => coursebit/inkstand-plugin-test
        [version] => dev-master
        [version_normalized] => 9999999-dev
        [source] => Array
            (
                [type] => git
                [url] => https://github.com/CourseBit/InkstandPluginTest.git
                [reference] => 3d0aebb030fc15ec308d4c062026bcf1a6bbb9ef
            )

        [dist] => Array
            (
                [type] => zip
                [url] => https://api.github.com/repos/CourseBit/InkstandPluginTest/zipball/3d0aebb030fc15ec308d4c062026bcf1a6bbb9ef
                [reference] => 3d0aebb030fc15ec308d4c062026bcf1a6bbb9ef
                [shasum] =>
            )

        [time] => 2015-08-10 03:28:28
        [type] => library
        [extra] => Array
            (
                [bundle_title] => Plugin Test
                [bundle_class] => Inkstand\Bundle\InkstandPluginTest\InkstandPluginTestBundle
            )

        [installation-source] => source
        [autoload] => Array
            (
                [psr-4] => Array
                    (
                        [Inkstand\Bundle\InkstandPluginTest\] =>
                    )

            )

        [notification-url] => https://packagist.org/downloads/
        [authors] => Array
            (
                [0] => Array
                    (
                        [name] => Joseph Conradt
                        [email] => joseph.conradt@coursebit.net
                        [homepage] => http://www.coursebit.net
                        [role] => Developer
                    )

            )

        [description] => This plugin is used for testing the plugin management within Inkstand LMS
        [homepage] => http://www.coursebit.net
    )

Is this a bug? Am I configuring support incorrectly? Any help is greatly appreciated!

**Comment by Seldaek** [comment]
The problem is just that this information is not sent out of packagist in https://packagist.org/p/coursebit/inkstand-plugin-test.json - that saves some network traffic and memory. Not really sure what we can do to fix this or if we should..

**Comment by joeconradt** [comment]
That makes sense. Thank you for clarifying. I'm utilizing composer as a plugin management system with composer scripts/events, and `support` would be nice for additional links in a table of installed plugins. The support info would be in each version, so I can see why that would add bloat.

**Comment by Seldaek** [comment]
If this is about showing info for installed plugins, then maybe you should consider reading out the data directly from the composer.json in every plugin's install dir? You can get the install dir using `$event->getComposer()->getInstallationManager()->getInstallPath($installedPackage)` and then look in there if there is a composer.json and look for support info in there. I hope this helps.

**Comment by joeconradt** [comment]
@Seldaek Great idea, thanks!
