### ISSUE TITLE
Use phpseclib for SSH transfers

### ISSUE THREAD

**Issue by mbrodala** [composer/composer#4352]
A lot of people recommend [phpseclib](https://packagist.org/packages/phpseclib/phpseclib) for SSH transfers which provides an implementation in pure PHP.

The greatest benefit is not depending on the SSH2 PHP extension being installed on every system using Composer repositories via SSH/SFTP.

Please consider integrating this library for SSH transfers.

**Comment by mbrodala** [comment]
It seems like even a [stream wrapper](https://github.com/phpseclib/phpseclib/blob/ed6f754137f8849667147e0f1eae3129451f3dea/phpseclib/Net/SFTP/Stream.php) is provided which should allow for URLs like `sftp://user@host:port/`.

**Comment by Seldaek** [comment]
Doesn't seem likely that someone will implement this as it's pretty niche so I'll close it, but if someone is really interested in working on it we can still discuss.
