### ISSUE TITLE
Multiple private composer repositories for redundancy purposes

### ISSUE THREAD

**Issue by P0rnflake** [composer/composer#4354]
Hi,

I am wondering whether it is possible to define multiple repositories of the type "composer" to provide an easy way to support development and productive satis servers.

In my case I have two satis repository servers (dev-repo.company.com & prod-repo.company.com) which should be used in each of our composer.json like this:
```
...
    "repositories": [
        { "packagist": false },
        { "type": "composer", "url": "http://dev-repo.company.com/" },
        { "type": "composer", "url": "http://prod-repo.company.com/" }
    ],
    "require": {
        "php": ">=5.5",
        "company/samplelib": "1.0.0"
    }
...
```

Our dev/staging team has only access to dev-repo.company.com and they can update it by their own.
The same applies for the distribution team for the productive repository server.

My problem is that it depends on the machine where the application is installed whether one or the other server is reachable - both provide more or less the same packages only that the productive server should archive everything, even dev versions.

Currently I am facing the issue that if one of the repository servers is not reachable by the machine there is an exception like this:
```
[Composer\Downloader\TransportException]                                     
  The "http://prod-repo.company.com/packages.json" file could not be downloade  
  d: php_network_getaddresses: getaddrinfo failed: Name or service not known   
  failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known  
```

Another  problem I think I could face is that the composer.lock files are generated during development of the application so the referenced repository will probably be the dev-repo server.

Is there any possible configuration to achieve the described scenario, maybe by defining one meta repository with multiple urls which will be checked by priority?

Notice: In our case is not possible to define just one repository url and decide by routing which server should be used.

**Comment by stof** [comment]
Well, this cannot be achieved as ``composer update`` needs to load all repositories to know what is available.
and repositories are only used during updates. Install from lock does not read repositories but downloads packages from the URL in the locked metadata.

What you should do is using the mirroring feature to specifying multiple download URLs for the package: for each package, the dev-repo.company.com repository should include download URLs on prod-repo.company.com as mirrors so that Composer can try downloading the package from both servers (meaning it will need to be able to access at least one of them). And prod-repo.company.com would not be a composer repository anymore. It would only be a place to download archives (it does not need the JSON files with metadata as you should never run ``composer update`` in prod anyway). The way to handle this would be to upload archives to the prod-repo server once they are generated in the composer repository (but without removing old dev archives if you need to keep them)

Satis does not support specifying mirror URLs currently though.

**Comment by P0rnflake** [comment]
Thank you for the reply.

Your approach is currently not practicable in our environment because the productive machines are not able (and of obviousely they shall not be able) to access the dev-repo at network level.

Is this feature planned for the future or am I the only one facing this kind of problem?

In my opinion this is a major issue, due most of the productive environments shall not be impacted by the current development progress, even if it is "only" the package repository.

I could mention a solution with multiple urls defined for one "meta" or "virtual" repository, f.e.:
```
....
    "repositories": [
        { "packagist": false },
        { "type": "composer", "url": "http://dev-repo.company.com/", "meta-repository": "company", "priority" : 1},
        { "type": "composer", "url": "http://prod-repo.company.com/", "meta-repository": "company", "priority" : 2}
    ],
...
```
Internally composer could reference to the meta repository and even in the lock files could be stored multiple urls for one distribution of a package.

Could you imagine taking this approach into consideration?

**Comment by stof** [comment]
@P0rnflake the productive machine does not need to be able to access the dev-repo:

- they should never need to read the package metadata (they should only be installing from lock, right ?)
- to download dists, they would fallback to the mirror to download

The actual issue you need to solve is that **package downloads** must come from a different location. Trying to solve that by getting package metadata from elsewhere is wrong because it means you have to update deps with a different repository instead of using the lock file.
you are confusing the URL of the composer repository and the URL of the package downloads (for Packagist, dist archives are downloaded from Github or Bitbucket, not from Packagist for instance)

**Comment by P0rnflake** [comment]
Sorry, now I exactly understood what you mean.
You are right the download location can be distributed by the lock file. I am wondering what happens if for whatever reason (f.e. hotfixing) a productive machine should run a `php composer.phar update` on a specific package with the hotfixed version. In this case we would need to redeploy the whole application (because the new lock file must be changed) and after that we would have to run composer install (?) again.

Is this the best practice for this kind of problem or just a workaround?

Could you please provide me the documentation of the mirror feature from satis, I just found the "prefix-url" option for the "archive" feature which doesn't provide multiple download locations.

**Comment by stof** [comment]
@P0rnflake you should never change the lock file in a prod machine directly. this must be done on the computer of a dev (are you writing the patch in prod directly ?). a deployment process should **never** run the ``update`` command as it means deploying a different codebase than the one you tested previously (locally, in CI server and in staging environment)

**Comment by P0rnflake** [comment]
@stof Ok, I will try the approach with the different download location for the packages so that productive machines don't need access to the repository server. Is the "prefix-url" for the satis-archive feature the configuration you described for the mirror-feature to specifying multiple download URLs for the package, or is there any other configuration for satis? Thank you in advance, this helped me a lot!

**Comment by stof** [comment]
No, as I said above, Satis does not yet support this feature (it would not be difficult though)

**Comment by P0rnflake** [comment]
Is the feature of multiple dist locations supported by composer? cannot find anything about it, only another open issue #2847

**Comment by stof** [comment]
@P0rnflake I'm not sure it is documented, but it is supported: https://github.com/composer/composer/commit/77163f66fc19de8a4df39ad421cce6205001df12

**Comment by P0rnflake** [comment]
@stof thanks a lot!

**Comment by P0rnflake** [comment]
@stof I was working on a pull request for satis to support the mirror feature of composer when I discovered that composer currently doesn't support the mirrors for the ArchiveDownloader (https://github.com/composer/composer/blob/2438105e11da443f72628fb9d4bf4e089d229c6c/src/Composer/Downloader/ArchiveDownloader.php). Is there a point why it is not supported? Shall I create a pull request for that too if it works for me locally?

**Comment by stof** [comment]
@P0rnflake it does. See ``parent::download``

**Comment by P0rnflake** [comment]
@stof today I compiled a composer.phar with enhanced output for debugging purposes. It does seem like the package passed to the downloader do not contain the distMirror configuration provided by the packages.json.

Each package of my packages.json (created by a modified version of satis) contains: 
```
        "dist": {
                    "type": "zip",
                    "url": "http://notreachable.company.com/dist/symfony-yaml-2e257c292cfce88bf6c894a03d0fe8d782055aee-zip-3bc6a9.zip",
                    "reference": "2e257c292cfce88bf6c894a03d0fe8d782055aee",
                    "shasum": "482f4a6f0973ecaf15139ee56cfe86a6513caf84",
                    "mirrors": [
                        {
                            "url": "http://example.org"
                        },
                        {
                            "url": "http://reachable.company.com"
                        }
                    ]
                }, 
```
In the output of the composer.phar in the progress of installing the packages I can see that the distMirrors are correctly set by the JsonLoader (@see https://github.com/composer/composer/blob/master/src/Composer/Package/Package.php#L316).

But in the download step $this->distMirrors is not initialized anymore (@see https://github.com/composer/composer/blob/master/src/Composer/Package/Package.php#L332).

So every time there is just the unreachable base dist url which is requested 3 times and after the TramsportException the package is downloaded from source, not from any of the mirrors.

Do you have an idea how to get this to work or what the actual problem is?

**Comment by P0rnflake** [comment]
@stof Figured out what the problem is:
The distMirrors are getting overwritten by https://github.com/composer/composer/blob/master/src/Composer/Repository/ComposerRepository.php#L571 with null. Is this a bug?

**Comment by stof** [comment]
this indeed looks weird.

**Comment by P0rnflake** [comment]
@stof maybe the idea behind that was, that the repository itself "could" overwrite each package mirror config by a global repository specific mirrors config. I am currently testing it with the repository mirror configuration. Keeping you up to date...

**Comment by stof** [comment]
but the implementation looks flawed anyway, as the mirrors URL cannot be the same for each package anyway

**Comment by P0rnflake** [comment]
@stof funny story, with the mirrors configuration at package.json root level, like
```
{
    "packages": [],
    "includes": {
        "include/all$d561b5fde58604f594abc5d2f816f31e85a1e859.json": {
            "sha1": "d561b5fde58604f594abc5d2f816f31e85a1e859"
        }
    },
    "mirrors": [
        {
            "dist-url": "http://example.org"
        },
        {
            "dist-url": "http://reachable.company.com"
        }
    ]
}
```
composer installation takes the mirrors into consideration, but now the problem is, that the url of the mirrors is not parsed correctly, it just tries to download the root url without path or package name and fails at the checksum verification, because it was not a zip which was downloaded. o.O

**Comment by P0rnflake** [comment]
@stof Ok, there seems to be url-placeholder for %package%', '%version%', '%reference%', '%type% which are replaced for each package, but I dont know whether the ArchiveManager creates names which can be matched by this pattern. 
Strange behaviour, I wonder how this was solved by ToranProxy.

**Comment by P0rnflake** [comment]
@stof Shall this issue be classified as a bug, or shall I create a new bug issue? This could be (hot-) fixed pretty easily with an isset in the composer repository which would solve my problems and opens the way for the satis mirror feature, but I don't know exactly if this would blow up something else.

**Comment by discordier** [comment]
IMO This should be classified as bug.
Essentially it seems to render the usage of mirrors useless if I understood you correctly.

**Comment by Seldaek** [comment]
ToranProxy sets it like:

```
"mirrors": [{
"dist-url": "https://TORAN/repo/packagist/dists/%package%/%version%/%reference%.%type%",
"preferred": true
}],
```

And then yes substitution happens to build per-package mirror URLs. The point is that this way you only need to specify the mirror URL once and not modify every package's dist section. It was never thought to accept mirror URLs inline in the package definitions.

**Comment by P0rnflake** [comment]
@Seldaek I am not familar with this issue anymore, but I can remember that I couldn't achieve the file name pattern of the archive manager with the provided placeholders -> so i basically couldn't mirror the generated files.

**Comment by Seldaek** [comment]
Ok well if nobody knows anymore what this issue is there for I'll close for now :)

**Comment by mnpenner** [comment]
How are we supposed to use `"type": "path"` with a fallback? e.g.

```json
  "repositories": [
    {
      "type": "path",
      "url": "../pdoplus"
    },
    {
      "type": "hg",
      "url": "https://bitbucket.org/mycompany/pdoplus"
    },
```

I have `pdoplus` installed on my machine because I'm the one maintaining that project, but my co-workers don't. They should pull from BitBucket.

Right now Composer just fails if it can't find the project locally instead of falling back to the next repo in the list.

Is there no way to handle this? I don't want to have to add and remove the "path" repo from composer.json every time I work on that project.

**Comment by Seldaek** [comment]
@mnpenner if it's just for you and not everyone relies on the path repo then you maybe should look into https://github.com/franzliedke/studio instead.
