### ISSUE TITLE
php composer.phar validate composer.json produces diff results from php bin/composer validate composer.json

### ISSUE THREAD

**Issue by PMPP** [composer/composer#4355]
(With composer 1.0.0-alpha9)
Hello,

We have been using composer/satis for a while to build a proxy. After a while we started noticing warnings like the following:

```
Reading composer.json of composer/composer (master)
Skipped branch master, Could not parse version constraint ^1.4.4: Invalid version string "^1.4.4"
```

But when running `php composer.phar validate` it does not produce that error. BUT if clone composer/composer, and run `php bin/composer validate`, then I get the same sort of warning thrown by [VersionParser.php](https://github.com/composer/composer/blob/master/src/Composer/Package/Version/VersionParser.php#L95).

Opening the composer.phar shows me the code of VersionParser is the same. So something strange is going on, but I haven't been able to figure it out for a single reason, I'm not sure how to debug properly the phar file. =)

Thanks in advanced for your time.

**Comment by PMPP** [comment]
New findings (as I found out how to compiler the phar), if I do a `php .bin/compile` to produce a `composer.phar` then `php composer.phar validate` I get the same error. The .phar gotten with `$ curl -sS https://getcomposer.org/installer | php` continues to pass the validation.

**Comment by PMPP** [comment]
So, I've been using alpha 9, but alpha 10 has this issue solved. Sorry.

**Comment by stof** [comment]
@PMPP this is because the support for the ``^``  operator in version constraints was implemented after the alpha9 release. alpha9 is very old
