### ISSUE TITLE
Running scripts only on dev environments

### ISSUE THREAD

**Issue by Taluu** [composer/composer#4358]
Hello,

Just an idea, as I was working with the `autoload-dev` for a project, how about having a `scripts-dev` section in the composer.json file to run scripts only if the `--no-dev` option is **not** present ? It would then be run after the `scripts` section.

WDYT ?

**Comment by alcohol** [comment]
Can you describe a use-case where this might come in handy?

**Comment by Taluu** [comment]
E.g, we had the composer incenteev script running, but on out prod environments, we had a somewhat different config (a shared directory in which we're using the same version for each deployment). So basically, running this script on our `--non-dev` environment was messing with our linked directories.

So the thing here, could be to put this script only on dev (non symlinked envs), which is run only on `--dev` scripts

**Comment by alcohol** [comment]
Well to be honest, it is discouraged to run Composer on production at all.
Neither Composer nor Git are substitutes for a proper release procedure. So
I'm personally not really convinced this is a feature that Composer needs.
But you're always free to write a PR with suggested changes/implementation.

**Comment by Taluu** [comment]
Well we do need to install our dependency, and we install it on dist so we're not using git when we can help it (with the cache, etc) through a capistrano process (and never had any problems with it, while we had some on `--prefer-source` (git) installations).

I'll try to work on that when I'll have some time then, until then, I think I need to overwrite Incenteev's parameter handler with something of my own to run it only on `dev` mode...

**Comment by Seldaek** [comment]
Another way to install in prod is to run with --no-scripts, then you can still use composer run-script to run anything that really needs to run. That gives you more control and I'd say it's a better way than making the composer.json more complex.

**Comment by Taluu** [comment]
And there is also s simple plugin for that, and it's not really a courant use-case i'd say
