### ISSUE TITLE
New parameter: composer install --oauth-token=1a28a1635df52c1b03212b7edcff8aa961c0491c

### ISSUE THREAD

**Issue by agarb7** [composer/composer#4360]
Sometimes you have to share the Vagrant VM. Composer require storage key in the configuration file on the disk. No simple and secure way completely wipe file after installation, because of journalling FS. I think the option (like in the title) for single key using during installation (without writing to disk) would be useful.

**Comment by alcohol** [comment]
I would personally prefer to see this as an environment variable than yet another option/argument that we would have to add to install/update/etc.

**Comment by ronanguilloux** [comment]
IMHO, 
Vagrant/Docker now being able to handle and even share ENV params from host to guest,
this issue may not be relevant.

tip:

```bash
GITHUB_TOKEN=$(composer config -g github-oauth.github.com)
```

**Comment by cs278** [comment]
https://github.com/composer/composer/pull/4546 this probably closes it off.
