### ISSUE TITLE
Composer.json validation exception: "/.composer.json" doesn't match the expected JSON schema.

### ISSUE THREAD

**Issue by RokaFogtaCsukaFarka** [composer/composer#4363]
Hello!

I would like to ask, if my jsonlint.com validation tool accepts the JSON I wrote, the composer json validator why not. I didn't find a mistake either. The problem is: "an arrayvalue found but an object is required".

Danke sehr schön,
Balint

**Comment by stof** [comment]
Well, can you post the composer.json file ? Without it, it is hard to help you debugging this

**Comment by RokaFogtaCsukaFarka** [comment]
Hello!

This is the complett JSON file.

[
    {
        "name": "bharmath/pseudodoodle",
        "description": "It's a framework that is like Doodle. It's name is: Fake Doodle",
        "keywords": [
            "css",
            "js",
            "less",
            "mobile-first",
            "responsive",
            "front-end",
            "framework",
            "web",
            "behaviour driven development"
        ],
        "authors": [
            {
                "name": "Balint Harmath"
            }
        ],
        "used frameworks": [
            "Bootstrap",
            "jQuery",
            "Behat",
            "Mink"
        ],
        "type": "project",
        "require-dev": {
            "behat/behat": "^3.0",
            "behat/mink": "^1.6",
            "behat/mink-extension": "^2.0",
            "behat/mink-goutte-driver": "^1.1",
            "behat/mink-selenium2-driver": "^1.2"
        },
		"extra": {
			"branch-alias": {
				"dev-master": "3.3.x-dev"
			}
		},
		"replace": {
			"twitter/bootstrap": "self.version"
		}
    }
]

Bye,
Balint

**Comment by stof** [comment]
Well, the formatting of your JSON is off as you haven't used a markdown codeblock, but I can already spot the issue: the top-level element of your JSON is an array, but a composer.json file is an object at top-level, not an array.

The difference is that jsonlint just checks whether the JSON format is valid. ``composer validate`` checks that it is a valid composer.json file, based on the JSON schema and some specialized validation.

**Comment by RokaFogtaCsukaFarka** [comment]
Thank you very much. It really works!

I’m grateful for your help!
