### ISSUE TITLE
InvalidRepositoryException - No valid composer.json was found in any branch or tag

### ISSUE THREAD

**Issue by sviiiter** [composer/composer#4364]
Hello,
I'm stuck on git-repositories part's update using composer in my Yii2 project on Windows 7.

The next part of my composer.json in conflict:
  >>"repositories": [
    {
      "type": "git",
      "url": "https://github.com/Mirocow/yii2-apns-gcm.git"
    }

1)  I found the next exception occured on executing "composer update" in project's directory:  

>>[Composer\Repository\InvalidRepositoryException]
  No valid composer.json was found in any branch or tag of https://github.com/Mirocow/yii2-apns-gcm.git, could not load a package from it.

2) On "composer update -vvv" next bunch of command executed right before exception:

>>Loading composer repositories with package information
Executing command (C:/Users/Zebra/AppData/Local/Composer/vcs/https---github.com-Mirocow-yii2-apns-gcm.git/): git rev-parse --git-dir
Executing command (CWD): git clone --mirror "git://github.com/Mirocow/yii2-apns-gcm.git" "C:/Users/Zebra/AppData/Local/Composer/vcs/https---github.com-Mirocow-yii2-apns-gcm.git/"
Executing command (C:/Users/Zebra/AppData/Local/Composer/vcs/https---github.com-Mirocow-yii2-apns-gcm.git/): git show-ref --tags
Executing command (C:/Users/Zebra/AppData/Local/Composer/vcs/https---github.com-Mirocow-yii2-apns-gcm.git/): git branch --no-color --no-abbrev -v
Executing command (C:/Users/Zebra/AppData/Local/Composer/vcs/https---github.com-Mirocow-yii2-apns-gcm.git/): git branch --no-color
Executing command (C:/Users/Zebra/AppData/Local/Composer/vcs/https---github.com-Mirocow-yii2-apns-gcm.git/): git show "master":composer.json

3) I tried to execute a banch of git commands by yourself. Get into "C:/Users/Zebra/AppData/Local/Composer/vcs/https---github.com-Mirocow-yii2-apns-gcm.git/" and execute "git show "master":composer.json". The composer.json is there:
>>{
    "name": "mirocow/yii2-apns-gcm",
    "description": "Yii 2 Apns and Gcm together",
    "type": "yii2-extension",
    "version": "0.0.1",
    "keywords": ["yii2"," extension"," apns"," gcm"],
    "license": "MIT",
    "authors": [
        {
            "name": "Bryan Jayson Tan",
            "email": "bryantan16@gmail.com"
        },
        {
            "name": "Mirocow",
            "email": "mr.mirocow@gmail.com"
        }
    ],
    "minimum-stability": "stable",
    "require": {
        "yiisoft/yii2": ">=2.0.5",
        "duccio/apns-php": "dev-master",
        "php-gcm/php-gcm": "1.1.1"
    },
    "autoload": {
        "psr-4": {
            "mirocow\\apnsgcm\\": ""
        }
    }
}

4) Trying to do "D:\Composer\composer.bat diagnose":
>>Checking composer.json: FAIL
require.yiisoft/yii2 : unbound version constraints (>=2.0.4) should be avoided
require.yiisoft/yii2-bootstrap : unbound version constraints (*) should be avoided
require.yiisoft/yii2-swiftmailer : unbound version constraints (*) should be avoided
require.mirocow/yii2-apns-gcm : unbound version constraints (dev-master) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking composer version: OK

5) Yes, "php D:\Composer\composer.phar global require "fxp/composer-asset-plugin:1.0.0""  has already executed successfully.
In my composer.json: 

>>{
    "name": "yiisoft/yii2-app-advanced",
    "description": "Yii 2 Advanced Project Template",
    "keywords": ["yii2", "framework", "advanced", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "dev",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": ">=2.0.4",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*", 
         "mirocow/yii2-apns-gcm": "dev-master"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*"
    },
    "config": {
        "process-timeout": 1800
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    },
  "repositories": [
    {
      "type": "git",
      "url": "https://github.com/Mirocow/yii2-apns-gcm.git"
    }
  ]
}

Can you describe me please why is this happened?
Thanks in advance.

**Comment by stof** [comment]
Can you run it with ``-vv`` to see the verbose output of the VCS repository itself but without seeing the debugging output showing all commands being run (or paste the full output in a gist to be able to see everything from it)

**Comment by stof** [comment]
and when trying to add the repository in a test project, I'm not getting this exception, so I'm unable to reproduce it.

On a side note, you should use ``vcs`` as type rather than ``git`` to let Composer use the github API to read metadata rather than cloning the repo locally for that.

**Comment by sviiiter** [comment]
Hello, thanks for sharing.

Here is "composer -vv":
>>D:\Sites\WORK\advanced>D:\Composer\composer.bat update -vv
Loading composer repositories with package information
>>
>>[Composer\Repository\InvalidRepositoryException]
  No valid composer.json was found in any branch or tag of https://github.com/Mirocow/yii2-apns-gcm.git, could not load a package from it.
>>
>>Exception trace:
 () at phar://D:/Composer/composer.phar/src/Composer/Repository/VcsRepository.php:264
 Composer\Repository\VcsRepository->initialize() at phar://D:/Composer/composer.phar/src/Composer/Repository/ArrayRepository.php:179
 Composer\Repository\ArrayRepository->getPackages() at phar://D:/Composer/composer.phar/src/Composer/DependencyResolver/Pool.php:104
 Composer\DependencyResolver\Pool->addRepository() at phar://D:/Composer/composer.phar/src/Composer/Installer.php:407
 Composer\Installer->doInstall() at phar://D:/Composer/composer.phar/src/Composer/Installer.php:232
 Composer\Installer->run() at phar://D:/Composer/composer.phar/src/Composer/Command/UpdateCommand.php:140
 Composer\Command\UpdateCommand->execute() at phar://D:/Composer/composer.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at phar://D:/Composer/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar://D:/Composer/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar://D:/Composer/composer.phar/src/Composer/Console/Application.php:146
 Composer\Console\Application->doRun() at phar://D:/Composer/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar://D:/Composer/composer.phar/src/Composer/Console/Application.php:82
 Composer\Console\Application->run() at phar://D:/Composer/composer.phar/bin/composer:43
 require() at D:\Composer\composer.phar:25
>>
>>
>>update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-r
eqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]

**Comment by stof** [comment]
Are you running the latest version of composer ?

**Comment by sviiiter** [comment]
Yes, that's right.
>> Checking composer version: OK

**Comment by sviiiter** [comment]
Any advice?

**Comment by stof** [comment]
Well, I'm totally unable to reproduce the issue (it works fine for me when I try). So I don't understand what goes wrong in your case

**Comment by sviiiter** [comment]
I'm using:
XAMPP v3.2.1 on Windows 7 x64.  
PHP Version 5.5.19
git version 1.8.4

Maybe it helps.

**Comment by sviiiter** [comment]
Hi
This issue is clear for me from now. The problem has described once a time here https://github.com/composer/composer/issues/2418
I found it first but ignored it figuring out as not my case cause a decision is described not in obvious way. I was wrong.

---
## Introduction:
Cmd.exe starts from C:\Users\Me by default.
But I had a tuned custom location path on start cmd "D:\Sites" and this was my problem.

## Here is the the decision.
Check your regedit paths
>HKLM\Software\Microsoft\Command Processor\AutoRun
>HKCU\Software\Microsoft\Command Processor\AutoRun

Remove all Autorun keys if it exists. I had one.
