### ISSUE TITLE
composer doesn't clone forked git repo anymore

### ISSUE THREAD

**Issue by videni** [composer/composer#4366]
as [change-composer-git-source-for-a-package](http://stackoverflow.com/questions/14636936/change-composer-git-source-for-a-package) suggests we can force composer to clone a forked git repo, I did this 
```
  "require": {
    "cuab/phpcrawl":"0.8.1"
  },
  "repositories": [
 {
      "url": "git@github.com:videni/phpcrawl.git",
      "type": "git"
    }
]
```

but it still clone the original repo `https://github.com/sminnee/phpcrawl`, it worked a month ago , now it doesn't , is there something I did wrong, or we need extra work to make it work again?

**Comment by slbmeh** [comment]
Where is your repository declaration that has a package named `cuab/phpcrawl` with that specified version?

**Comment by videni** [comment]
I posted a wrong url , I have corrected it,this is not relevant to this trouble, I copied wrong code from my composer.json file.

**Comment by alcohol** [comment]
Why do you assume this would work?

First of all, do not use type `git`, use type `vcs` (not related so much to the issue at hand, but just FYI).

Second, since you did not change the package name, it is hard for composer to pick between your fork and the original. If you were to create a branch on your fork, it would be much easier. E.g. if you create a branch named `bugfix`, then you can simply require `"cuab/phpcrawl": "dev-bugfix"`. You are instead using a tag right now that exists on both your fork and the original repo. There is no difference between them.

Of course, you should submit your changes upstream through a PR and see that they get merged instead. What you are doing now should only be done for the short term, it is not a long term solution.

**Comment by videni** [comment]
thanks, I thought, if we add

 ```
{
      "url": "git@github.com:videni/phpcrawl.git",
      "type": "git"
    }
```
composer would  think that phpcrawl is  stored in  `git@github.com:videni/phpcrawl.git`, no longer clones it from original url. the force url has a high  priority than the original one. now I understand composer doesn't work this way.
  I create a branch in my forked repo, change that version to the new created branch ,it works now. very appreciate your help.

**Comment by alcohol** [comment]
It should have higher priority. I'm not intimately familiar yet with the inner workings of repositories so I cannot comment on how the prioritisation process works or what could have affected it in this particular situation. But by making things less ambiguous you guarantee success :-).

**Comment by vnagara** [comment]
+1 @videni Your config implies to use package from repo first if it exists.

**Comment by alcohol** [comment]
> +1 @videni Your config implies to use package from repo first if it exists.

This is not always true. Please do not make assumptions, instead, read the documentation :-)

**Comment by vnagara** [comment]
@alcohol from documentation https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository :
`Composer will correctly pick your package over the original one since the custom repository has priority over packagist.`
So @videni change __type__ to __vcs__ and reverify.

**Comment by vnagara** [comment]
@videni I see the __type__ __git__ also possible.

**Comment by alcohol** [comment]
@vnagara that part of the documentation also mentions using a custom branch. So like I said, it depends on the scenario. If you want to use master, or a tag that exists in both repositories, it becomes more complicated.

**Comment by vnagara** [comment]
@alcohol Yeah, but with different branch name you don't need any precedence as in that case this version doesn't exist  in composer.
So It should work as it was and any can comprehend without documentation or at least make documentation clearer.
Thanks

**Comment by alcohol** [comment]
No, because as it was he was using a version that existed in both his fork and the original repository. After he switched to a custom branch per my suggestion, it worked as expected :-)

**Comment by videni** [comment]
@vnagara , you are right, change 
```
{
      "url": "git@github.com:videni/phpcrawl.git",
      "type": "git"
    }
```
to 
```
{
      "url": "git@github.com:videni/phpcrawl.git",
      "type": "vcs"
  }
```
the precedence works like we expected , it is better than  creating a new branch.
