### ISSUE TITLE
[RuntimeException] Failed to clone git@github.com:my/private-repo.git via....

### ISSUE THREAD

**Issue by yusufpolat** [composer/composer#4367]
Hey there, 

I googled this error and tried results but nothing happened. I have two machine. Same version of composer, same composer.json and same project. When i try to composer install on my ubuntu laptop everything is ok. But on my osx when i try to composer install, composer starts to installing packages. When trying to clone my private repos ;

 [RuntimeException]                                                                                             
  Failed to clone git@github.com:myOrganization/myRepo.git via git, https, ssh protocols, aborting.                
  - git://github.com/myOrganization/myRepo.git                                                                     
    Cloning into '/Users/yus/Desktop/websites/h-s/vendor/xx/cache-bundle/xx/CacheBundle'...  
    fatal: remote error:                                                                                         
      Repository not found.                                                                                      
  - https://github.com/myOrganization/myRepo.git                                                                   
    Cloning into '/Users/yus/Desktop/websites/h-svendor/xx/cache-bundle/xx/CacheBundle'...  
    remote: Invalid username or password.                                                                        
    fatal: Authentication failed for 'https://github.com/myOrganization/myRepo.git'                               
  - git@github.com:.myOrganization/myRepo.git                                                                       
    Cloning into '/Users/yus/Desktop/websites/h-s/vendor/xx/cache-bundle/xx/CacheBundle'...  
    Permission denied (publickey).                                                                               
    fatal: Could not read from remote repository.                                                                
                                                                                                                 
    Please make sure you have the correct access rights                                                          
    and the repository exists.   

As i mentioned before on my other machine same composer.json working great. 

P.S. when i m cloning this private repos with gitclone without any error.  So there is no permission error i think  And i already tried self-update

**Comment by alcohol** [comment]
Are you running this as your own user or as sudo? It **is** a permission issue clearly. Just need to pinpoint where it goes wrong.

**Comment by yusufpolat** [comment]
Thanks for your reply. Using with sudo.

**Comment by alcohol** [comment]
And when you run git clone, do you also use sudo?

**Comment by yusufpolat** [comment]
With or without sudo i can clone successfully that repo.  But when try sudo  composer install it fails Rob.

**Comment by alcohol** [comment]
Weird, I was thinking that maybe your root user does not have a valid ssh key. But if you can `git clone` and `sudo git clone` your private repo that would indicate they both have valid ssh keys. Can you give us the output of a `composer install -vvv` ?

**Comment by poizon001** [comment]
+1 facing the same issue
[RuntimeException]

Failed to clone git@github.com:myOrganization/myRepo.git via git, https, ssh protocols, aborting.

git://github.com/myOrganization/myRepo.git
Cloning into '/Users/yus/Desktop/websites/h-s/vendor/xx/cache-bundle/xx/CacheBundle'...
fatal: remote error:
Repository not found.
https://github.com/myOrganization/myRepo.git
Cloning into '/Users/yus/Desktop/websites/h-svendor/xx/cache-bundle/xx/CacheBundle'...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/myOrganization/myRepo.git'
git@github.com:.myOrganization/myRepo.git

Cloning into '/Users/yus/Desktop/websites/h-s/vendor/xx/cache-bundle/xx/CacheBundle'...

Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights

and the repository exists.
