### ISSUE TITLE
Use of zip files as dependencies

### ISSUE THREAD

**Issue by oscarotero** [composer/composer#4371]
Hello.
I have a package with a custom repository that you can [see here](https://github.com/oscarotero/psr7-unitesting/blob/master/composer.json#L20)
This repository points to a zip file with a java library, needed to execute some functionalities. This works fine if this package is root, but not if it's a dependency (the most of the time), because custom repositories only works for root packages. Is there any way to provide this dependency without include it in my repository?. I think an option to allow download external files directly would be great. Something like:
```json
{
    "require": {
        "https://github.com/validator/validator/releases/download/15.6.29/vnu.jar_15.6.29.zip": "dest-dir"
    }
}
```

**Comment by alcohol** [comment]
What you propose is currently not supported and unlikely will ever be supported. It's better to document in your lib's README that it depends on this java lib and how the user can get it (via custom repository, download elsewhere, or offer it as part of your package).

**Comment by oscarotero** [comment]
Thank you for yor response.

Searching for similar projects like [node-validator-nu](https://github.com/hiroaki-yamamoto/node-validator-nu), [gulp-html](https://github.com/watilde/gulp-html) or [grunt-htmllinkt-http](https://github.com/branneman/grunt-htmllint-http), all of these packages contains the java library, instead an external reference to download, so maybe is the best option right now.

Anyway, I think it would be great to have a way to download binary files. Currently composer has the `bin` key to create symlinks to files. Maybe extending this to accept also urls is a better aproach. For example:
```json
{
    "bin": [
        "scripts/install",
        "https://phar.phpunit.de/phpunit.phar",
        "https://github.com/validator/validator/releases/download/15.6.29/vnu.jar_15.6.29.zip"
    ]
}
```

**Comment by alcohol** [comment]
Well, as it creates just symlinks, that is not really going to work. It will need to download them, to somewhere. Maybe it is something that could be looked into. But to me that looks rather insecure. A user adds a package, and suddenly this package starts downloading things that the user might not be expecting. Much better to solve this at the package level than let Composer handle it, in my humble opinion.

**Comment by oscarotero** [comment]
I got your point, but IMHO, having to download the package manually or providing a copy in the package is like going back to the pre-composer days. I don't think download a package is more insecure than provide it in the package (maybe yes, I'm not an expert). But this can be handled with an user confirmation: `The package X is going to download the binary file Y. Are you agree? (Y,n)` or with a key like `minimum-stability` but for downloads `"allow-bin-downloads": false`

**Comment by alcohol** [comment]
Alright. There might be a use case for this. But I suggest you open up a new issue then clearly describing the use case and proposed functionality. This issue is too far off-topic to be flagged as a feature request at this point.

**Comment by oscarotero** [comment]
Yes, I have to think about it. I'll create a new issue with a propose. Thanks
