### ISSUE TITLE
Connection Error [ERR_CONNECTION] - Installing composer

### ISSUE THREAD

**Issue by tnaffh** [composer/composer#4372]
For the past few weeks I have been trying to install composer on my windows 10 PC, but with no luck for success. 

- I tried downloading ComposerSetup.exe, my preferred way for instalation, failed downloading with the ERR_CONNECTION
- I tried downloading Composer.phar - Failed with same error
- Checked and verified my system, (php 5.6, open_ssl enabled, everything looks OK)

=> Seems to me like its something to do with SSL, since even accessing  [Installer](https://getcomposer.org/installer) OR [CompserSetup](https://getcomposer.org/Composer-Setup.exe) from anywhere over HTTPS doesn't work BUT works over HTTP. So I also tried to download using HTTP but still HTTPS is strictly enforced.

I am developing web applications using Laravel, which requires Composer, so I can do much without it. Please help.

ComposerSetup.exe Error:
    
Connection Error [ERR_CONNECTION]: Unable to connect to getcomposer.org

Request to https://getcomposer.org/installer failed with errors:
SSL: Handshake timed out. Failed to enable crypto. Failed to open stream: operation failed

**Comment by aleary06** [comment]
I'm having the same issue on a Windows Server 2008 R2 machine. Was this issue ever resolved? I have no issue navigating to the ComposerSetup or Installer pages over https but am still getting the same error.

**Comment by aleary06** [comment]
I figured out the issue...at least for my setup. There was a proxy setup in IE. Disabling that allowed the download to go through.
