### ISSUE TITLE
Fatal error: Allowed memory size of 1073741824 bytes exhausted

### ISSUE THREAD

**Issue by videni** [composer/composer#4373]
```
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 72 bytes) in phar:///usr/local/Cellar/composer/1.0.0-alpha8/libexec/composer.phar/src/Composer/DependencyResolver/RuleSetGenerator.php on line 126
```

This problems happens  lots of  times since I use Composer .even though  the `composer diagnose  ` gives a good result,
```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking composer version: OK
```

I have set php memory unlimited, this error still goes, any one has a solution for this?

**Comment by Canta** [comment]
Have you tried using the PHP's command line parameter (instead of the INI value) for setting the memory limit?

Like this:
`php -d memory_limit=-1 composer.phar install`

It's a known issue. Composer sets the memory limit to 1G.
https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors

**Comment by alcohol** [comment]
Can you share your composer.json with us?

**Comment by videni** [comment]
@Canta, your solution works, thanks

**Comment by skillberto** [comment]
Guys, I still have this problem, but with Travis.
I've read a lots of solution, but nothing worked yet. And if I know well, "php -d memory_limit" not supported in Travis.
Could you please tell me a good solution for Travis?

This is the "require" sections from my "composer.json":

> "require":
>  {
>     "php": ">=5.5",
>     "doctrine/doctrine-bundle": "~1.6",
>     "symfony/framework-bundle": "~2.3",
>     "symfony/console": "~2.3",
>     "jupeter/doctrine-dump-fixtures-bundle": "dev-master"
>   },
>   "require-dev": {
>     "doctrine/orm": "~2.3",
>     "satooshi/php-coveralls": "~0.6.1",
>     "phpunit/phpunit": "~4"
>   },

**Comment by alcohol** [comment]
Options I see:

- Use the `php -d memory_limit` option (Travis **does** support this).
- Commit a `composer.lock` in your repository and simply run `composer install` on Travis. Composer does not have to do any dependency resolution for an install from a lock file (which is what normally requires so much memory).
- Do not use a `dev-master` version constraint.

**Comment by skillberto** [comment]
I try it.
But, I checked some repository, and in a most of case `composer.lock` doesn't commited, and `php -d memory_limit` also not exists in `travis.yml`. But these repos are use more dependency. Why is not there a problem?

**Comment by cs278** [comment]
@skillberto do you really want to test against dev versions of every package? Installing [your bundle](https://github.com/skillberto/ConsoleExtendBundle/) takes 1.4GiB of memory to do the dependency resolution, if you change the minimum stability to stable it only takes 400MiB and is a good 100 seconds faster.

**Comment by skillberto** [comment]
@cs278 Thank you very much, it's a good idea! I change it. :)

**Comment by guijianshi** [comment]
you need to require a exact version . It can decrease memory request

**Comment by Insafchihi** [comment]
Allowed memory size of 1610612736 bytes exhausted (tried to allocate 32 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php on line 220 whaat should I do i can't install any bundle

**Comment by curry684** [comment]
Just raise the limit, 1.5GB is tight for big projects. In general -1 is not a bad idea for CLI on dev machine.

**Comment by mrdejam** [comment]
try this:
`update symfony/symfony --with-dependencies`

**Comment by stepotronic** [comment]
Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 18446603534624354304 bytes) in phar:///usr/bin/composer/src/Composer/DependencyResolver/Pool.php on line 106

even with -1 I still don't have enough hardware...

**Comment by curry684** [comment]
That's really quite a lot hehe. You could try raising your dependencies to reduce the number of options available. Especially for libraries that have a lot of dependencies themselves it could help a lot to tighten it down, ie. `symfony/symfony:^3.4.12` is functionally equivalent to `symfony/symfony:^3.4` but reduces the number of versions to consider from 13 to 1 right now, without compromising the dependency resolution process. I'm not sure how much it could help but it certainly helps at least a bit.

**Comment by Lartex** [comment]
> try this:
> `php -d memory_limit=-1 composer.phar update symfony/symfony --with-dependencies`

Finally i've found the solution, thanks!

**Comment by EmmanuelYao** [comment]
Vous avez ce genre de problème avec la command: " composer update "

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 67108864 bytes) in phar://C:/wamp/www/symfcom/composer.phar/src/Composer/DependencyResolver/Solver.php on line 223

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.

Faites la commande: "  **php -r "echo ini_get('memory_limit').PHP_EOL;"**  "    
pour voir la valeur actuelle de " _memory_limit_ " généralement elle est: 128M

Ensuite allez dans le disque où vous avez installer wampserver exemple :\wamp\bin\php\php7.2.14

dans le fichier wampserver  entrez dans le dossier  \bin\php que vous utilisez,
 dans le dossier en question cherchez le fichiez php.ini, 
dans le fichier php.ini cherchez la ligne "  Memory_limit " changer la valeur 128M à -1

Enfin retournez dans votre Cmd et refaites la commande : "   composer update " et chekebouuum la solution 👍 👍

**Comment by mayurnag123** [comment]
export COMPOSER_MEMORY_LIMIT=-1

This will solve the problem

**Comment by Raouiaa** [comment]
> > try this:
> > `php -d memory_limit=-1 composer.phar update symfony/symfony --with-dependencies`
> 
> Finally i've found the solution, thanks!

this worked for me as well!!! thankssss

**Comment by webtamizhan** [comment]
> export COMPOSER_MEMORY_LIMIT=-1
> 
> This will solve the problem

This is worked for me well

**Comment by Stalin99** [comment]
WHAT FOR WINDOWS?

**Comment by samreenq** [comment]
memory_limit =-1 in php.ini
this solve my issue.

**Comment by YisalKhan** [comment]
> try this:
> `php -d memory_limit=-1 composer.phar update symfony/symfony --with-dependencies`

aresymfony/symfony directory names

**Comment by kalevivek19** [comment]
I had the same issue on windows > wampp server.
**Solution: change memory_limit =-1 + check your php version on cli (php -v) and set the system environment variables path according to your php version**
