### ISSUE TITLE
Uncaught exception 'UnexpectedValueException' with message 'Could not parse version constraint ^1.3.2: Invalid version string "^1.3.2"'

### ISSUE THREAD

**Issue by waxim** [composer/composer#4374]
It seems when calling ``Composer\Package\Version\VersionParser::normalize`` it is failing to normalise constraints (versions starting with `^`) I think it should make an attempt as a last resort to draw a version number from any string. 

I was able to avoid throwing the error my adding another check.

```php
$version = str_replace("^", "", $version);
```

Maybe, this could b added to an is_numberic check to return the value straight away and leave the script now we have a normal value?

**Comment by alcohol** [comment]
You are probably using a very old checkout of Composer.

**Comment by stof** [comment]
``^`` is valid in version constraints since December 2014. Update your composer version
