### ISSUE TITLE
Different vendor-dir

### ISSUE THREAD

**Issue by Henk8** [composer/composer#4382]
We have a project that builds on an own framework. Furthermore we use severall packages.
I wan't to install our own framework in another directory than the packages.

So basically I wan't to define two different vendor-dirs in composer.json. Is this possible? Or is there another way that I can install our framework in another directoty than the packages?

**Comment by stof** [comment]
You would have to use custom installers for any package you want to put in a non-standard location.

However, we generally encourage to let Composer install all dependencies in the place it want and write code in a way which does not depend on particular installation paths. It makes things much easier to maintain than having to use custom installers.

**Comment by alcohol** [comment]
Does it matter what directory your framework is in though? Any application now a days should not really be depending on a specific path or location. What is the rationale behind your use-case?

**Comment by Henk8** [comment]
You are right, the location does not matter. We thought it was better to make a distinction between our own framework and the packages we use.
How does composer know where to put the code? Is it always in a vendor folder?
I have created a composer.json. Is it possible to define the installation path?

**Comment by Henk8** [comment]
I have solved the 'problem' using: https://github.com/mnsami/composer-custom-directory-installer
