### ISSUE TITLE
Stash option is gone, reports changes in the wrong file

### ISSUE THREAD

**Issue by mindplay-dk** [composer/composer#4384]
The "stash and update" option seems to have disappeared? But what's much stranger, is this:

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing mindplay/stately (dev-master)
    The package has modified files:
    M src/Controllers/ShowFrontpage.php
    Discard changes [y,n,v,d,?]?
```

What's odd here, is that `src/Controllers/ShowFrontpage.php` isn't part of the `mindplay/stately` package at all! There is no file by that name in the package - that's a file in the parent project, which is also under source-control, but that's a completely different source tree.

I could try to stash and then update, but I'm scared to, as last week I lost an entire source-tree after doing `composer update`. This has happened twice now recently, but I don't know how to report that as a bug, since, after it happens, there is no evidence of me having done any work at all. Twice now, I have committed my work, then ran `composer update`, and all my changes up to the last push or pull, were wiped out, even from the source history.

These problems appeared to start recently, perhaps with the introduction of the "composer" remote? When did composer start adding it's own remote? It seems to cause problems, like for one, when I'm ready to push a change set, often, it'll appear as though I'm about to push changes made, not by me, but by other team members - doing an extra fetch brings things back in sync, but it's really confusing. I should note that we use custom Git repositories in our project, for many of our internal dependencies, maybe that's a factor?

**Comment by mindplay-dk** [comment]
What the...

```
$ cd vendor/mindplay/stately
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   ../../../src/Controllers/ShowFrontpage.php

no changes added to commit (use "git add" and/or "git commit -a")
```

How does a file three folders up get tracked as belonging to this vendor package?

**Comment by alcohol** [comment]
I've seen Git get confused about parent and child repositories before. But I've yet to find a explanation for this behaviour. These kind of issues are also very hard to reproduce. Since Composer relies on Git for this functionality to work properly, there is not much we can do on the side of Composer, as it is Git that is misbehaving in this scenario, not Composer.

**Comment by stof** [comment]
I suspect that you installed the package from source and then deleted the ``.git`` folder in it (deleting the git repo). this means that any git command will run for the project repo (as this is the nearest ancestor with a ``.git`` folder).

Deleting ``.git`` folders in the vendor directory is not a supported case for ``composer update``

**Comment by mindplay-dk** [comment]
> there is not much we can do on the side of Composer, as it is Git that is misbehaving in this scenario, not Composer.

Is that a given?

Perhaps if console commands were written to a log-file or something, we could validate that it isn't sending the wrong git commands. Or, maybe there's a verbosity setting that will cause it to output the git commands?

> Deleting .git folders in the vendor directory is not a supported case for `composer update`

I'm positive I've never done that. (I can't even think of a reason to do that...)

**Comment by alcohol** [comment]
If you run the composer command with -vvv verbosity, it should show the command it is running in the background.

**Comment by mindplay-dk** [comment]
Ok, I will try that next time...

**Comment by stof** [comment]
> I'm positive I've never done that. (I can't even think of a reason to do that...)

well, it is easy to check: do you have a ``vendor/mindplay/stately/.git`` folder ?

**Comment by Seldaek** [comment]
BTW the composer remote has been there for ages so I doubt that's the issue.

If this happens again, I'd run a `git rev-parse --show-toplevel` in vendor/mindplay/stately to see what git repo it is picking up, because it sure sounds weird that it'd track files out of it, it sounds more likely it picks up your main project repo as the current repo for some obscure reason (if as you claim the .git dir was still there in the vendor/mindplay/stately)

**Comment by mindplay-dk** [comment]
> if as you claim the .git dir was still there

come to think of it, it might *not* have been there *before* I can `composer update`, which might have put it back in place - I can't know that!

**Comment by boan2010** [comment]
I have the same issue:

```
vagrant@vagrant-ubuntu-trusty-32:~/www/teatapp/modules/laughs$ git st
On branch master
Your branch is up-to-date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        ../../config/cli-config.php

nothing added to commit but untracked files present (use "git add" to track)
vagrant@vagrant-ubuntu-trusty-32:~/www/teatapp/modules/laughs$ git diff
vagrant@vagrant-ubuntu-trusty-32:~/www/teatapp/modules/laughs$ cd ..
vagrant@vagrant-ubuntu-trusty-32:~/www/teatapp/modules$ cd laughs/
vagrant@vagrant-ubuntu-trusty-32:~/www/teatapp/modules/laughs$ git rev-parse --show-toplevel
/home/vagrant/www/teatapp
vagrant@vagrant-ubuntu-trusty-32:~/www/teatapp/modules/laughs$ ls -la
total 9
drwxrwxrwx 1 vagrant vagrant 4096 Sep  2 06:56 .
drwxrwxrwx 1 vagrant vagrant    0 Sep  2 06:56 ..
drwxrwxrwx 1 vagrant vagrant    0 Sep  2 06:56 assets
-rwxrwxrwx 1 vagrant vagrant  388 Aug 31 11:16 composer.json
drwxrwxrwx 1 vagrant vagrant 4096 Sep  2 08:19 .git
-rwxrwxrwx 1 vagrant vagrant    9 Aug 31 11:16 .gitignore
drwxrwxrwx 1 vagrant vagrant    0 Sep  2 06:56 src
drwxrwxrwx 1 vagrant vagrant    0 Sep  2 06:56 templates
vagrant@vagrant-ubuntu-trusty-32:~/www/teatapp/modules/laughs$ cd .git/
vagrant@vagrant-ubuntu-trusty-32:~/www/teatapp/modules/laughs/.git$ ls -la
total 8
drwxrwxrwx 1 vagrant vagrant 4096 Sep  2 08:19 .
drwxrwxrwx 1 vagrant vagrant 4096 Sep  2 06:56 ..
drwxrwxrwx 1 vagrant vagrant    0 Sep  2 08:19 objects
vagrant@vagrant-ubuntu-trusty-32:~/www/teatapp/modules/laughs/.git$ cd objects/
vagrant@vagrant-ubuntu-trusty-32:~/www/teatapp/modules/laughs/.git/objects$ ls -la
total 4
drwxrwxrwx 1 vagrant vagrant    0 Sep  2 08:19 .
drwxrwxrwx 1 vagrant vagrant 4096 Sep  2 08:19 ..
drwxrwxrwx 1 vagrant vagrant    0 Sep  2 06:56 pack
vagrant@vagrant-ubuntu-trusty-32:~/www/teatapp/modules/laughs/.git/objects$ cd pack/
vagrant@vagrant-ubuntu-trusty-32:~/www/teatapp/modules/laughs/.git/objects/pack$ ls -la
total 45
drwxrwxrwx 1 vagrant vagrant     0 Sep  2 06:56 .
drwxrwxrwx 1 vagrant vagrant     0 Sep  2 08:19 ..
-r-xr-xr-x 1 vagrant vagrant  9528 Aug 31 11:16 pack-9d46a2f533a07cea6e8347e898671248b016c66e.idx
-r-xr-xr-x 1 vagrant vagrant 36229 Aug 31 11:16 pack-9d46a2f533a07cea6e8347e898671248b016c66e.pack
vagrant@vagrant-ubuntu-trusty-32:~/www/teatapp/modules/laughs/.git/objects/pack$
```

**Comment by Seldaek** [comment]
That's not a complete .git directory, it's got a few files missing, I don't know the specifics but you need at least a HEAD and refs then there's usually more things like index/config/hooks/info/... not just a couple object files. So that's why it's skipped, but the question is why is it incomplete.

**Comment by mindplay-dk** [comment]
> the question is why is it incomplete

For the record, @boan2010 is at the desk next from me - having just run into the same issue, I asked him to follow up on this thread.

The only thing we're sure of, is that this has something to do with `composer update` - I had told him about the issue, and so when it happened to him after he ran `composer update`, he asked me about it.

If nobody else has reported this or any similar issue, it's probably something specific to our precise composer configuration, which is pretty complex. Should I post copies of our `composer.json` files or how can we get to the bottom of this?

**Comment by Seldaek** [comment]
One question is whether the .git dir in this dependency was fully 
correct *before* composer update ran, or if the files have been wiped by 
something else.

Then if it is indeed composer wiping random files off of the git dir, 
the question is why because before an update it should either wipe the 
whole directory or nothing at all, not bits and pieces inside .git only.

One thing could be VM shared folder driver issues, although I haven't 
seen that in ages, it happened in the past that faulty virtualbox 
extensions or such were trashing the filesystem.

**Comment by mindplay-dk** [comment]
> One thing could be VM shared folder driver issues

I think we can rule out anything environment-specific - I'm on a Windows box, and my colleague is on a Linux system, so we have completely different setups.

**Comment by Seldaek** [comment]
Any progress here? Otherwise I'd rather close as it lacks actionable points.

**Comment by mindplay-dk** [comment]
I don't think I have run into this issue again since my last post six months ago. Maybe it cleared up somehow. Could have been a git issue or a Composer issue that cleared up with some other change...
