### ISSUE TITLE
First time user invalid json????

### ISSUE THREAD

**Issue by jasemilly** [composer/composer#4386]
Hi
I am using composer for the first time so if I shouldn't be posting here I am very sorry.

I am following a youtube tutorial on the paypal api I have installed composer and created the json file the same as the example. composer.json is saved in the root folder for the website.  the structure is below.  composer diagnose composer.json: fail and property name is required.

```
{
    "require": {
        "paypal/rest-api-php": "1.5.1"
    }
}
```

thank you for any help

**Comment by Seldaek** [comment]
composer diagnose should just warn you that name is required to publish the package, but it's not a hard failure per se, you should still be able to run composer install/update just fine.

**Comment by jasemilly** [comment]
Hi my mistake missed sdk from the name thanks

-------- Original message --------
