### ISSUE TITLE
search without composer.json does not use auth.json

### ISSUE THREAD

**Issue by glensc** [composer/composer#4392]
so i run search, which uses repository using credentials, i let save the credentials, i search again, it does ask again credentials

```
$ composer --version
Composer version 1.0-dev (afd98b74f13b9def1b2447f16fd0bfd4d96dff94) 2015-08-31 09:58:50

$ composer search nada
No composer.json found in the current directory, showing packages from whatever
    Authentication required (whatever):
      Username: glen
      Password: 
Do you want to store credentials for whatever in /home/vagrant/.composer/auth.json ? [Yn] Y

$ composer search nada
No composer.json found in the current directory, showing packages from whatever
    Authentication required (whatever):
      Username: glen


$ ls -l composer.json ~/.composer/auth.json
ls: cannot access composer.json: No such file or directory
-rw------- 1 vagrant vagrant 155 sept   2 10:58 /home/vagrant/.composer/auth.json
```

**Comment by alcohol** [comment]
You probably used sudo (or su) at some point but left that out of your summary. There is no way the file would otherwise end up being owned by root:root.

**Comment by glensc** [comment]
oh sorry, i did not notice file is root owned. but that is not the issue, i ran the test actually with root. i will modify ticket to show it's vagrant user not root

**Comment by alcohol** [comment]
Uhm no. Please don't. Just remove the file and retry.

**Comment by glensc** [comment]
@alcohol what? the bugreport is correct now!

**Comment by shochdoerfer** [comment]
@glensc Could you please check again with the latest version of Composer? I tried to re-produce your problem but I am not able to. Works as intended on my local machine.

**Comment by glensc** [comment]
for the reference, show your `--version`!

**Comment by shochdoerfer** [comment]
@glensc done. Any news on your side?

**Comment by glensc** [comment]
sorry, not yet!

**Comment by glensc** [comment]
yes, the problem is still present:

$ composer --version
Composer version 1.0-dev (afd98b74f13b9def1b2447f16fd0bfd4d96dff94) 2015-08-31 09:58:50

care to post your output? perhaps you do not even have present repository asking http auth?

```json
# cat ~/.composer/config.json
{
    "config": {},
    "repositories": {
        "whatever": {
            "type": "composer",
            "url": "https://localhost/satis"
        },
        "packagist": false
    }
}
```

**Comment by shochdoerfer** [comment]
Ok, I can re-produce the problem now. It worked for me because I had the repositories config in my root composer.json file not in the global config file. In that case the authentication detection seems to work. When I add the repositories config in the global config file Composer always asks for the credentials. I think the problem is located somewhere in the merging logic of the different config files.

**Comment by shochdoerfer** [comment]
It is sufficient to create an empty aka "{}" root composer.json file to make it work when searching.

**Comment by alcohol** [comment]
Let me look into this. I do believe there is some logic regarding storing auth credentials in the global auth.json, and not locally. But they should be available for subsequent searches after initially storing them. Perhaps the search command doesn't properly chain-load all the config files.

**Comment by glensc** [comment]
@shochdoerfer yes of course, that was the original bugreport: *search without composer.json*

**Comment by glensc** [comment]
:+1: :100: :1234:
