### ISSUE TITLE
Request: add command to download the source of a package

### ISSUE THREAD

**Issue by Kapeli** [composer/composer#4394]
Given a package name and a version, add a command that would download the source of the package and nothing else.

Something like this:
```
composer download/get/fetch package_name package_version
```

**Comment by alcohol** [comment]
So basically, you want a shortcut for git clone?

**Comment by Kapeli** [comment]
Yes, and `hg`, `svn` and whatever else composer supports.

**Comment by alcohol** [comment]
Doesn't use git? You mean downloading a zip file of the branch/release instead?

Well, you can just go to an empty directory and do `composer require vendor/package`, but that will put it in the `vendor` directory. Other than that, I see no use-case for a download command to just download any package directly. You can do that yourself, composer is not made to fill that gap.

**Comment by Kapeli** [comment]
> Doesn't use git? You mean downloading a zip file of the branch/release instead?

Yes, and whatever else composer does (if anything).

> Well, you can just go to an empty directory and do composer require vendor/package, but that will put it in the vendor directory

That also downloads the dependencies though. Which is not something I need for my use.

> Other than that, I see no use-case for a download command to just download any package directly

I need this for [Dash](http://kapeli.com/dash) (an API documentation browser app), although I can work around it. Basically I let users generate docs for any package on packagist.org. To do this, I need a reliable way to download the package's source.

> You can do that yourself

I did, but it's a bit hacky and unreliable. I just thought I should ask as you've already done the work and (from the outside) it seemed like something easy to add. I can see why this is something extra you'd need to support along the way, which might not be worth it.

> composer is not made to fill that gap.

I understand. I'm not even sure this is something a package manager should do to be honest. The only other package manager I know that does this is Ruby Gems, which has `gem fetch` and `gem unpack`.

**Comment by Seldaek** [comment]
This could be achieved by a plugin potentially once we allow them to provide custom commands, or it can be done just using composer classes by requiring it as a dependency. I think it's rather unlikely we'll provide it in composer itself as the use case is pretty limited so I'll close this.
