### ISSUE TITLE
Composer ignores dependency changes in branch

### ISSUE THREAD

**Issue by Brainshack** [composer/composer#4396]
Hello,

I create a new branch of my package. In this branch, I changed the version of a dependency, for example version 5.3 of guzzle to version 6.0. I push my branch and update it on packagist (internal installation of packagist). The branch is shown in packagist, but the depdency is still on 5.3. When I try to install the specific branch of the package, it still tries to install guzzle 5.3., It seems like, composer is looking only into the master branch of the package, to check for dependecies. This also is somewhat annoying, when you start a new package and want to upload it to packagist. We use git-flow and until the first real release for a package, the might be no master branch. Packagist wont recognize a package however, until there is a master branch available.

**Comment by stof** [comment]
Can you link to an affected package ? Composer is handling different requirements per branch since day 1.

**Comment by Brainshack** [comment]
Unfortunatly this happened on a non public package, but I will try to set
up a repro case.

2015-09-03 12:02 GMT+02:00 Christophe Coevoet <notifications@github.com>:

**Comment by Brainshack** [comment]
Okay, this might be an issue with our internal packagist installation.
Can't reproduce it on packagist.org. Will test further.

2015-09-03 12:23 GMT+02:00 Christian Loock <brainshack@gmail.com>:

**Comment by Brainshack** [comment]
Okay, it turns out I'm just dumb.

**Comment by stof** [comment]
@Brainshack what was the cause of the issue ?

**Comment by Brainshack** [comment]
Me being stupid and forgetting to push the changes to the repo. I feel silly

2015-09-03 14:15 GMT+02:00 Christophe Coevoet <notifications@github.com>:
