### ISSUE TITLE
Add --file parameter to the archive command.

### ISSUE THREAD

**Issue by tobiastom** [composer/composer#4397]
This is kind of related to #4379. As the filename is more or less hard to guess, I'd like to add a parameter `--file` that will take the name that should be used for the archive. 

With this it would be easier to automate the next step that could happen after an archive is created (e.g. by a build server).

I could also add a pull request, I just want to check if this would get accepted.

**Comment by Seldaek** [comment]
Sounds good to me, if you want to PR it.

**Comment by MakiCode** [comment]
I can make a PR for this.

**Comment by tobiastom** [comment]
@MakiCode That would be awesome. I'm burried in tasks right now.

**Comment by Seldaek** [comment]
Done in #4479

**Comment by tobiastom** [comment]
Thank you @MakiCode. Seems to work fine for me!

**Comment by MakiCode** [comment]
@tobiastom You're welcome!
