### ISSUE TITLE
github-oauth equivalent for Bitbucket?

### ISSUE THREAD

**Issue by ppaulis** [composer/composer#4398]
Hello!

I'm trying to use private Bitbucket repositories as dependencies using an oauth token, but can't find the equivalent to the "github-oauth" config option for Bitbucket. After digging a bit in the composer sources, it seems, that the only option currently is http-basic for Bitbucket?
If that's the case, is there a particular (technical?) reason, why this isn't supported?

Thanks a lot!

**Comment by vaclavvanik** [comment]
Useful for bitbucket users. +1

**Comment by stof** [comment]
@ppaulis nobody has contributed it yet. This is the reason

**Comment by MakiCode** [comment]
I'm going to attempt to make a pull request for this.

**Comment by nifr** [comment]
+1

**Comment by wenkepaul** [comment]
I'll develop this feature.

**Comment by vaclavvanik** [comment]
@wenkepaul +1

**Comment by Seldaek** [comment]
This has been implemented so closing
