### ISSUE TITLE
Composer does not use bash aliases

### ISSUE THREAD

**Issue by lukasoppermann** [composer/composer#4401]
Hey, 

is there a way to get composer to use aliases i specify in my bash_profile?
I have the following problem:

On my server, the default php version on the cli is 4, however, I need 5.6. On my server I can use `php56` to run something on php 5.6, but my dev environment (homestead & mac machine) do not understand `php 5.6` so I can not change this in the composer.json scripts part.

I would like to do this, but it will not work locally. However, I can not change the composer.json file on the server, because it will be overwritten, because I deploy via git. Is there any solution to this problem?

```
"scripts": {
        "post-install-cmd": [
            "php56 artisan clear-compiled",
            "php56 artisan optimize"
        ],
```

**Comment by alcohol** [comment]
How on earth did you manage to even find a server still running php 4?

Why do you assume that composer does not use aliases specified in bashrc/profile?

**Comment by lukasoppermann** [comment]
Hey, my server generally runs php56 and you get it on the cli as well but somehow their stupid cli runs php4 as a default. Don't ask me why, I would love it to change.

However when I add an alias like this

```
alias php="php56"
php -v 
PHP 5.6.0 (cli)
```

But in the composer.json when I add `php -v` I still get `PHP 4.4 (cli)`.

**Comment by alcohol** [comment]
It uses Process for running such commands. It could be that it does not inherit the environment of your shell. To be honest I can't quickly think of a nice solution that supports both your broken and normal environment. Let me ponder for a bit.

**Comment by alcohol** [comment]
It probably does inherit your PATH. Why not just fix the PATH to make sure /usr/bin/php or /usr/local/bin/php comes before wherever your PHP 4 binary is located? Or created a symlink that refers to the correct version in any of those directories.

**Comment by lukasoppermann** [comment]
Hey, so my path is already like this (I actually do not need the alias, I just tried if that worked for composer). This should work, correct? It does not, however.

```
export PATH="/usr/local/bin/php56:/usr/local/bin/php5-56LATEST-CLI:$PATH"
```

**Comment by alcohol** [comment]
If php56 is the binary and not a directory, then no, your PATH is wrong. It should only contain directories, not binaries.

**Comment by alcohol** [comment]
But that means you need to call it using `php56`. What does `/usr/local/bin/php` symlink to? Or `/usr/bin/php` ?

**Comment by lukasoppermann** [comment]
Well, thats the problem, its `PHP 4.4.9 (cgi). :(

**Comment by alcohol** [comment]
Can you modify that symlink?

**Comment by lukasoppermann** [comment]
No, I have no permissions for that. Tried that already.

**Comment by alcohol** [comment]
Where does /usr/local/bin/php56 symlink to?

**Comment by stof** [comment]
well, create a ``php`` symlink in a place where you are allowed to do it, and add that folder at the beginning of the PATH, so that php is found here before finding the 4.4.9 bin.

**Comment by alcohol** [comment]
Yes, that is probably the most elegant solution. Most times users add ~/bin to their path at the front. In there, just symlink to /usr/local/bin/php56. Then make sure to restart your shell or export the new PATH value. Then try again.

**Comment by lukasoppermann** [comment]
Wow, that is a extremely simple solution, how did I miss it. ;( Thanks it works like a charm now. Thank you for the very quick support.

**Comment by alcohol** [comment]
You're welcome.
