### ISSUE TITLE
Composer SVG logo?

### ISSUE THREAD

**Issue by royduin** [composer/composer#4403]
Does someone have a SVG version of the Composer logo? I'd like to add it to https://github.com/websiddu/technology-icons

**Comment by alcohol** [comment]
I only know of these https://github.com/composer/getcomposer.org/tree/master/web/img

@seldaek do you happen to have an original somewhere?

**Comment by Seldaek** [comment]
I have one but I think it'll need some work before it can be used as a font, might as well just draw a simplified version over the existing one for the font IMO, but anyway I'll try and upload it later..

**Comment by gilbarbara** [comment]
:+1:

**Comment by Seldaek** [comment]
There, but as I said it's probably way too complex for a font icon.. Anyway that should simplify the work of cleaning it up :) https://dl.dropboxusercontent.com/u/1634226/composer_original.svg

**Comment by royduin** [comment]
Thank you!

**Comment by websiddu** [comment]
Thanks for the icon.. I optimized a bit and added to the webfont. Check it out here..

https://github.com/websiddu/technology-icons

**Comment by Seldaek** [comment]
Yup that's probably detailed enough already :) Thanks

**Comment by stephenkeable-allies** [comment]
For anyone who got here and dropbox link above no longer works -

https://github.com/gilbarbara/logos/blob/master/logos/composer.svg
