### ISSUE TITLE
Psr4 load classes from parent directory

### ISSUE THREAD

**Issue by trompx** [composer/composer#4404]
Hello,

Case 1 : I try the following
```
		"psr-4": {
			"": "../common/"
		}
```
Outputs in autoload_psr4.php
```
return array(
    '' => array('/common'),
);
```

Case 2 : while 
```
		"psr-4": {
			"": ".../common/"
		}
```
Outputs in autoload_psr4.php
```
return array(
    '' => array($baseDir . '/.../common'),
);

```

Expected outputs for the case 1
```
return array(
    '' => array($baseDir . '/../common'),
);
```

Same if I try to add a file with 
```
		"files": [
			"../common/MyFunctions.php"
		],
```

Is there an easy way to get the expected result with composer or I have to hardcode it somewhere in my app ?

Thank you

**Comment by alcohol** [comment]
What is the problem? All of those are correct.

**Comment by trompx** [comment]
The problem is that for case 1 the return array is :
```
 '' => array('/common'),
```
which does not point to the parent directory. While I'd like and expect (based on case 2) :
```
'' => array($baseDir . '/../common'),
```

I have the following structure :
```
common
    MyFunctions.php
app
    composer.json
```

**Comment by alcohol** [comment]
Do you understand how PSR4 works?

**Comment by trompx** [comment]
I think I do, I mean. The thing is I try to share functions between multiple laravel apps and based on this blog post it seems to work : http://juliebandy.com/laravel-lumen-a-database-and-shared-code/
But when trying to reproduce it just doesn't.

**Comment by alcohol** [comment]
Well, it works for me.

```
rob@macbookpro /tmp/test $ pwd
/tmp/test
rob@macbookpro /tmp/test $ cat composer.json
{
    "require": {
        "alcohol/iso3166": "^3.0"
    },
    "autoload": {
      "psr-4": {
        "Applications\\": "../test2"
      }
    }
}
rob@macbookpro /tmp/test $ cat vendor/composer/autoload_psr4.php
<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Applications\\' => array($baseDir . '/../test2'),
    'Alcohol\\' => array($vendorDir . '/alcohol/iso3166'),
);
```

What does your file MyFunctions.php contain though? If they are just functions, then you cannot use any autoload type except for "files". PSR-0/4 and Classmap are for files containing classes only.

**Comment by trompx** [comment]
Wow wierd.
Yeah I know I oversimplified it just for here but the path is common/Models/MyModel.php wich are files containing classes.

I just don't get why it does not output those ```/../```
I composer self-update just in case but still not working...

**Comment by alcohol** [comment]
Can you give us more details, e.g. what operating system, what command are you using the "generate your expected results", etc?

**Comment by trompx** [comment]
So first here is my full composer.json :
```
{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
	"require": {
		"laravel/framework": "5.0.*",
		"imagine/imagine": "dev-develop",
		"nesbot/carbon": "*",
		"elasticsearch/elasticsearch": "~1.0",
		"aws/aws-sdk-php-laravel": "~2.0"
	},
	"require-dev": {
		"orangehill/iseed": "dev-master",
		"fzaninotto/faker": "1.4.*@dev"
	},
	"autoload": {
		"classmap": [
			"database/",
			"bootstrap"
		],
		"psr-4": {
			"App\\": "app/",
			"Common\\": "../common/Models/"
		}
	},
	"autoload-dev": {
		"classmap": [
			"tests/TestCase.php"
		]
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php -r \"copy('.env.example', '.env');\"",
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	}
}
```

I have a ubuntu 14.04 VM (dockerhost) in which I run docker container :
- one for the laravel app
- one container that has all the dev tools
I mount the app code from the dockerhost to both containers.

On the command line of the devtools container I ```composer dump-autoload``` and the generated autoload_psr4.php is :
```
// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'XdgBaseDir\\' => array($vendorDir . '/dnoegel/php-xdg-base-dir/src'),
    'Symfony\\Component\\Filesystem\\' => array($vendorDir . '/symfony/filesystem'),
    'Symfony\\Component\\EventDispatcher\\' => array($vendorDir . '/symfony/event-dispatcher'),
    'SuperClosure\\' => array($vendorDir . '/jeremeamia/SuperClosure/src'),
    'Stringy\\' => array($vendorDir . '/danielstjules/stringy/src'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'League\\Flysystem\\' => array($vendorDir . '/league/flysystem/src'),
    'Illuminate\\' => array($vendorDir . '/laravel/framework/src/Illuminate'),
    'Elasticsearch\\' => array($vendorDir . '/elasticsearch/elasticsearch/src/Elasticsearch'),
    'Common\\' => array('/common/Models'),
    'ClassPreloader\\' => array($vendorDir . '/classpreloader/classpreloader/src'),
    'Aws\\Laravel\\' => array($vendorDir . '/aws/aws-sdk-php-laravel/src'),
    'App\\' => array($baseDir . '/app'),
);
```

**Comment by alcohol** [comment]
Uh, I have no idea how that docker setup works directory wise and stuff. It might very well be that your setup is broken. Clearly it is not a conventional directory structure. You have to deal with mounts and such.

**Comment by trompx** [comment]
Any idea if there is a way to hardcode  the needed ``` 'Common\\' => array('$baseDir . '/../common/Models'),``` as a temporary solution ?
Thanks anyway to have looked at my issue, and I'll let you know if I find a fix.

**Comment by trompx** [comment]
I think I get it.
My app and common folders are both mounted in the devtools container at the root. So when I set in the composer.json ```"Common\\": "../common/Models/"``` it must get the path from the docker container and see that ```../common/Models/``` == ```/common/Models/``` which is of course false on the docker host as app and common folder are located in /var/www folder.
Is there a way to force the path to stay relative ? that would solves this :)

**Comment by trompx** [comment]
Great, my assumptions were right.
I changed my mounted volumes in the devtools container to match thoses of the app container.
```
var
    www
        app
            composer.json
        common
            Models
```

Once I did this, I got
```
'' => array($baseDir . '/../common/Models')
```

That was a tricky one.

**Comment by alcohol** [comment]
Glad you resolved it. Docker and VM's can be nice for development flows, but they can also introduce unforeseen issues if you're not careful :-)

**Comment by trompx** [comment]
Yes, it adds a lot of complexity when you have to setup everything but after that it is great :)
I would still consider my solution more as a workaround, as some people would maybe have their application folder at the root. The best would be that composer does not convert relative path to an absolute one based on the folder tree, or have an option to force relative path.

**Comment by Seldaek** [comment]
This is most likely due to Filesystem::normalizePath or Filesystem::findShortestPath basically seeing the absolute path as the best way to access this. In case anyone wants to dig in there.

**Comment by curry684** [comment]
The only way I see to fix this is to entirely disable absolute paths on systems with flexible mountpoints. That sounds like a draconic solution to a problem that only occurs in a pretty exotic scenario.

**Comment by Seldaek** [comment]
Yup I am not sure if it's really fixable either. Re-dumping the autoload on the real system would be the easiest fix, or making sure you don't have root paths + autoloads that go to parent directories. It's kinda edge case so let's close it.

**Comment by townxelliot** [comment]
> This is most likely due to Filesystem::normalizePath or Filesystem::findShortestPath basically seeing the absolute path as the best way to access this. In case anyone wants to dig in there.

This is fixable in normalizePath(), but only really by removing all the path collapsing code, e.g.

```
diff --git a/src/Composer/Util/Filesystem.php b/src/Composer/Util/Filesystem.php
index 419d62be4..ddcfba73d 100644
--- a/src/Composer/Util/Filesystem.php
+++ b/src/Composer/Util/Filesystem.php
@@ -561,14 +561,9 @@ public function normalizePath(string $path)
             $path = substr($path, 1);
         }
 
-        $up = false;
         foreach (explode('/', $path) as $chunk) {
-            if ('..' === $chunk && (\strlen($absolute) > 0 || $up)) {
-                array_pop($parts);
-                $up = !(\count($parts) === 0 || '..' === end($parts));
-            } elseif ('.' !== $chunk && '' !== $chunk) {
+            if ('.' !== $chunk && '' !== $chunk) {
                 $parts[] = $chunk;
-                $up = '..' !== $chunk;
             }
         }
```

I'm not sure if this would have an impact on other parts of composer, or if this would mean that file accesses are far less efficient (I know nothing about how PHP would resolve the paths).
