### ISSUE TITLE
Windows silent install option

### ISSUE THREAD

**Issue by rbos** [composer/composer#4405]
Hi!

I just downloaded Composer-Setup.exe and am putting together a package to deploy it to a bunch of computers. I'm so far unable to figure out how to get it to run unattended.

/s, /qb!, /silent, /q, /v"/qb!", no dice so far.

I can extract the file contents with 7zip but there's no msi inside; the "[0]" file is 540KiB but there's no obvious way to extract it. Probably a dumb approach anyway.

**Comment by rbos** [comment]
Giving it /? gave me a list of options, like /SILENT and /VERYSILENT, both of which throw up the error message "The file you specified does not exist".

**Comment by rbos** [comment]
I'm guessing there isn't one. Backup plan, maybe it'll work to just deploy c:\ProgramData\ComposerSetup and ensure that c:\ProgramData\ComposerSetup\bin is on the path. It'll be ugly but oh well.

**Comment by alcohol** [comment]
@johnstevenson do you know if this is possible? Would it be hard to add if not yet available?

**Comment by alcohol** [comment]
@rbos can you also elaborate a little bit more on your use-case. What are you trying to achieve?

**Comment by johnstevenson** [comment]
@rbos As you worked out, there isn't an option for a silent/unattended install. Sorry.

@alcohol It is certainly possible to add this feature. I shied away from it initially, because there are so many things that can go "wrong" with an installation - PHPs in different places, multiple path entries etc - and the user has to browse for PHP themselves if it is not found in their path. So there are a few things to consider.

@rbos What is your setup here - has PHP already been added to the system path for each machine?

**Comment by rbos** [comment]
@alcohol: I have a bunch of computers without Composer. I want to put Composer on them without having to go around physically or remotely and go through the tedious business of logging in, copying, and running the installer and clicking several buttons. I'm not sure what my use case would be, otherwise. :)

@johnstevenson: thanks for the clarification. It seems to work with my hack of rar'ing up the installed folder and putting it into the same location on the target PCs, which I'm not really happy with, but will cope with. PHP is on the system path. Composer is also on the system path.

Thanks for the responses.

**Comment by stof** [comment]
I suggest discussing such stuff in the repo of the windows installer though: https://github.com/composer/windows-setup

**Comment by rbos** [comment]
@stof: Thanks. That was not obvious from my casual glance-through looking where to file a ticket.

**Comment by Seldaek** [comment]
Closing here, please reopen on windows-setup repo if still relevant.

**Comment by Cryental** [comment]
Please use this if you need silent install:

Composer-Setup.exe /VERYSILENT /NOCANCEL /NORESTART /SP- /ALLUSERS
