### ISSUE TITLE
UnexpectedValueException not a zip archieve

### ISSUE THREAD

**Issue by Sarav-S** [composer/composer#4407]
When I try requiring my package I get the following error

composer.phar require sarav/multiauth dev-master
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing sarav/multiauth (dev-master 8df6fed)
    Cloning 8df6fed41daab9f76b179787db796e040f5565cc
    8df6fed41daab9f76b179787db796e040f5565cc is gone (history was rewritten?)
    Failed to download sarav/multiauth from source: Failed to execute git checkout '8df6fed41daab9f76b179787db796e040f5565cc' -- && git reset --hard '8df6fed41daab9f76b179787db796e040f5565cc' --

fatal: reference is not a tree: 8df6fed41daab9f76b179787db796e040f5565cc

    Now trying to download from dist
  - Installing sarav/multiauth (dev-master 8df6fed)
    Downloading: 100%         
    Invalid zip file, retrying...
  - Installing sarav/multiauth (dev-master 8df6fed)
    Downloading: 100%         
    Invalid zip file, retrying...
  - Installing sarav/multiauth (dev-master 8df6fed)
    Downloading: 100%         

                                                                               
  [UnexpectedValueException]                                                   
  '/var/www/html/testing/vendor/sarav/multiauth/0ae88b9e715ae3ee41f35b6aea3a8  
  a23' is not a zip archive.                                                   
                                                                               

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [packages1] ... [packagesN]

**Comment by stevenhilder** [comment]
Where did the package name `sarav/multiauth` come from? The name in your Git repository and on Packagist is `sarav/laravel-multi`, which installs fine for me.

Somehow `sarav/multiauth` is pointing to a non-existent commit - did you delete a branch or a tag?

**Comment by Sarav-S** [comment]
Sorry. I deleted the package and recreated it once again. The issue was instead of submitting ssh url, I submitted https. I think that was the mistake. Anyways. thank you so much.
