### ISSUE TITLE
Env var or (global) config option for defaulting to --no-dev?

### ISSUE THREAD

**Issue by beporter** [composer/composer#4408]
I've read @Seldaek's post on [the switch to "--dev by default"](http://seld.be/notes/composer-installing-require-dev-by-default) as well as the discussion there, and it makes sense that `--dev` is the default since your production deploys should be scripted and should include `--no-dev` explicitly. Unfortunately, the use of a command line flag makes it difficult to share the same provisioning scripts between a dev environment (like vagrant) and a production (or staging, or QA or testing) environments where this command line switch needs to be specifically present or absent depending on the exact environment's needs.

It would greatly simplify things in this regard if it was possible to either:

1. Use an environment variable, something like `COMPOSER_NODEV`, where the presence of such changed composer's **default** behavior for all relevant commands (install, update, etc) on production machines. For example:
    ```shell
    # In ~/.profile
    export COMPOSER_NODEV=1
    
    # All `composer install` commands act like `composer install --no-dev`
    ```
    This would operate similarly to [`COMPOSER_NO_INTERACTION`](https://getcomposer.org/doc/03-cli.md#composer-no-interaction), for example, which likely exists for an extremely similar reason already.

2. Allow the default behavior to be overridden in the (global) config file using a `"dev": false` flag. At the global level it would help out a ton in production-like environments since a pre-written `$COMPOSER_HOME/config.json` file on those machines could disable dev requirements for that entire environment. 

    (I personally don't see a case for doing this in an individual project's `composer.json`-- maybe there's a use case for that too but it's not relevant to me in this context.)

    This would operate similarly to [`notify-on-install`](https://getcomposer.org/doc/06-config.md#notify-on-install), for example.

With either approach, your singular provisioning scripts could maintain simple `composer install` commands for all envs and correctly include or exclude dev dependencies by using an "external" marker instead of having to alter the command (and scripts) for each env.

Hopefully since there are existing precedents for this type of concession in composer already it's not too much of stretch to imagine the usefulness here.

**Comment by alcohol** [comment]
Or.. you could script your deploy script to not include --dev if COMPOSER_NO_INTERACTION is set to true for example. Just thinking of alternative quick wins :-). Adding an environment variable for every option/argument in composer is going to lead to a lot of clutter over time.

**Comment by beporter** [comment]
Yeah very true and it's an excellent suggestion but it's not perfect. In fact, in the case of a development "box", the provisioning script is running inside of vagrant, where --no-interaction is critical because we don't have shell access, but "--dev" is likewise critical because it's a developer's box. Since the whole point of my request is to remove environment-specific customization from the scripts (instead leaving the customizations to each actual runtime environment), using  COMPOSER_NO_INTERACTION to toggle both behaviors won't work in all cases.

I looked at the code to see what it would take to implement and test this (as an env var). For comparison, non-interactive can be controlled in a single place, but `setDevMode()` gets called from every Command class that supports it.

I understand the "don't let things get too messy" argument and actually I agree with it. I only humbly request that reasonable consideration be given to what side of the line this particular case falls on: worth the mess, or not? Would a speculative PR increase the persuasive power of my case? (Or at the very least make it easier to discuss the impact?)

**Comment by beporter** [comment]
My alternative right now is to:

* implement a `composer-wrapper` script, 
* make sure it's universally installed into each env whenever composer is,
* call it instead (exclusively), 
* make the script recognize such an env var to selectively include --no-dev when appropriate
* and still pass all other command line args through faithfully to the real composer. 

That's probably not quite as much work as adding the var to composer directly, but boy is it an order of magnitude worse on the Ugly Scale. :-)

**Comment by alcohol** [comment]
Well, my 2 cents on the subject..

Your build process should be configured on your CI server (jenkins, bamboo, etc). It should create a deployable package (tar/gz, or OS specific, such as rpm for redhat, deb for debian/ubuntu) for anything other than development. This package should be easily deployable to QA / integration / testing / production machines. Running composer on anything other than development really is not recommended. Any specific configuration for these target environments can be taken care of by your CI tooling.

The above is completely unrelated from your development setup process and should have no impact on that.

**Comment by beporter** [comment]
While I don't disagree with you, I also don't think it should be up to composer to prescribe "the right way" for people to deploy their projects (or dictate how they manage their development environments.) I work for a company that consults on many client projects. As much as we try to standardize our processes and push towards "best practices" (for whatever definition of "best" in _en vogue_ this month), it's not always possible, so we have an understandable appreciation for flexibility.

That said, my problems are not your problems. Message received; I'm on my own. Thanks for the responses. :+1:

**Comment by beporter** [comment]
Taking matters into my own hands resulted in a powerful (but forceful/dangerous) wrapper script: https://gist.github.com/beporter/21f7777ccd647cc30be6

The "[simple](https://gist.github.com/beporter/21f7777ccd647cc30be6#file-composer-nodev)" version of the script amounts to this:

```bash
#!/usr/bin/env bash
# Save this script in $PATH as `composer`, make it
# executable and use it instead of composer.phar.
composer.phar ${COMPOSER_NODEV+"--no-dev"} "$@" <&0
```

Even `composer selfupdate` will continue to function as expected.

The "[advanced](https://gist.github.com/beporter/21f7777ccd647cc30be6#file-composer)" version works as a near drop-in replacement for the official composer installation instructions:

`$ curl -sS https://gist.githubusercontent.com/beporter/21f7777ccd647cc30be6/raw/composer > composer && bash composer`

:warning: **This is of course wildly dangerous and you shouldn't trust my gist blindly, _or probably at all_ since I could change that script to do anything to your system.** :warning: It does however work extremely well for my use case of getting a "version" of composer that recognizes a `COMPOSER_NODEV` env var installed into environments that are themselves in the process of getting bootstrapped.

The wrapper script ensures `composer.phar` is always installed (installing it for you if necessary). It will also install itself into your PATH during any other usage if it isn't already there. So once the wrapper is in, as long as you use `composer` consistently, this version will always know about `COMPOSER_NODEV` and continue to function like the "stock" edition in all other regards.

**Comment by axel-rutz** [comment]
+1 from me. I really would love to see this reopened.

**Comment by axel-rutz** [comment]
Also, some commands now have --update-no-dev options to care for.

**Comment by schmunk42** [comment]
Same here, this should a setting in the global `composer.json`  and ENV variable.

Related discussions:
- https://github.com/mikehaertl/php-shellcommand/pull/31#issuecomment-366233070
- https://github.com/composer/composer/issues/3008
