### ISSUE TITLE
Some words about installed.json

### ISSUE THREAD

**Issue by olvlvl** [composer/composer#4410]
Hi,

I can't find information about the `installed.json` file on [getcomposer.com](http://getcomposer.com/), it's a shame because the file looks very interesting. Are packages ordered by weight in this one? That would be great because I wouldn't have to [_cheat_](https://github.com/ICanBoogie/ICanBoogie/blob/3.0/lib/Autoconfig/FakeAutoloadGenerator.php) in order to get packages and that would save me [a lot of work](https://github.com/ICanBoogie/ICanBoogie/blob/3.0/lib/Autoconfig/Hooks.php#L26) during `autoload-dump` event.

Can you comment on this feature and maybe add it to the doc?

Best,

Olivier

**Comment by Seldaek** [comment]
I don't think you can or should really rely on this file's ordering, although they might be after an initial install, I am not sure if that remains true after updates, and we certainly offer no guarantees of that right now.

**Comment by olvlvl** [comment]
Well that's too bad because guarantying that the `installed.json` file is created from ordered packages would allow third parties to parse the file without relying on a composer event and resorting to sorcery: https://github.com/ICanBoogie/ICanBoogie/blob/3.0/lib/Autoconfig/Hooks.php#L26

We could make sure that packages are ordered in `installed.json` and that it stays that way.

**Comment by Seldaek** [comment]
Yes that would be an option, if you'd like to look into it, should just be a matter of ordering things in the FilesystemRepository::write() I believe, and extracting that sorting logic out of the AutoloadGenerator into a re-usable standalone class as well probably.

**Comment by olvlvl** [comment]
I'm already investigating :)

**Comment by reedy** [comment]
+1 to keeping it in order. It's annoying for repos where you commit the resultant repo for it to remove the whole block from installed.json and append it to the bottom. It's just extra noise in the diff

The lock file keeps things in order, and updates the relevant rows, which is much easier to review

**Comment by olvlvl** [comment]
@reedy The thing is, `installed.json` (like the `vendor` directory) shouldn't be commited, only `composer.lock`.

**Comment by reedy** [comment]
Yet, it seems many people do commit the vendor repo for varying reasons. See also #4717

https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md

"The general recommendation is no."


But many people do, purely for ease of building repo trees for deployment purposes. I'd rather not run composer arbitrarily on production servers. I'd rather run it in a known good environment, checking it into a repo where you then know what you're deploying

See https://github.com/wikimedia/mediawiki-vendor for an example

If we can just kill the installed.json (or rather, git rm, then git ignore it), that's a workaround. But it seems strange that it just removes it from the middle, and appends to the end anyway.

If you look on github, I'd wager many people are committing them

**Comment by olvlvl** [comment]
What I mean to say it that changes to the `installed.json` file are irrelevant. What matters is the `composer.json` file.

**Comment by reedy** [comment]
No, but committing my vendor repo isn't going to have my install owned

**Comment by legoktm** [comment]
`composer.lock` and `installed.json` have different semantic meanings. The lock file represents what *should* be installed, whereas the installed file represents what *is* installed. Given that our use case requires us to commit the composer dependencies into a git repo, we commit `installed.json` too, since it's part of what composer generated. MediaWiki also reads the `installed.json` file to display what composer libraries are installed on our [Version page](https://www.mediawiki.org/wiki/Special:Version).

**Comment by olvlvl** [comment]
@legoktm Would you mind if packages were sorted by weight, or is it irrelevant for you? That is packages most used would be first in the file `installed.json` file.

**Comment by legoktm** [comment]
The order doesn't really matter, we just want it deterministic in some way so that running `composer update` doesn't randomly change the order of unrelated packages that stayed the same.

**Comment by frob** [comment]
@legoktm If the order of things in this files doesn't matter then why don't we just alphabetize the modules. That would at least solve the issue of consistency for those of us that need to have vendor in the repo.

Sounds like this could also be handled by a composer plugin.

**Comment by legoktm** [comment]
That sounds good to me. I proposed #6696 to alpha-sort the file.
