### ISSUE TITLE
process-timeout - What happens to the process ?

### ISSUE THREAD

**Issue by TasneemLo** [composer/composer#4411]
As I understand it, composer sets it's own timeout using the process-timeout config (https://getcomposer.org/doc/06-config.md#process-timeout)

The docs say that composer "assumes they [the process] died out". What exactly happens to the process ? Do they continue running in the background ? Does composer send it a signal like SIGKIL or SIGINT ? Does it send the signal and then check that the process actually terminated ?

I am running static code analysis using `phpcs` - and my task manager says that even after timing out, `phpcs` still continues to run and takes up ~ 70% CPU resources.

**Comment by Seldaek** [comment]
In case of timeout, it [appears](https://github.com/symfony/symfony/blob/73bbaa6cc7d706b0e945107657fbd240efec0c97/src/Symfony/Component/Process/Process.php#L805) that the process will get a SIGTERM followed by SIGKILL and then all pipes are closed. If the process is still alive after that, I am not sure why to be honest.

**Comment by TasneemLo** [comment]
I see, maybe the application is doing something weird then.

Thanks !
