### ISSUE TITLE
Document new path repository type

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#4412]
C.f. #4365

**Comment by sroze** [comment]
I'll do it today.

**Comment by sroze** [comment]
Follows up in #4416

**Comment by potherca** [comment]
There is no mention in the docs about the fact that Composer will create a symlink (when possible). Should I open a PR to add this information?

**Comment by sroze** [comment]
Any PR is welcome :)

**Comment by potherca** [comment]
I'll do that right now... Saves me from having to write a blogpost :-)

**Comment by potherca** [comment]
Details added in PR #4612
