### ISSUE TITLE
Poor performance due to duplicate findFileWithExtension calls

### ISSUE THREAD

**Issue by RyanThompson** [composer/composer#4415]
Hello everyone,

I am developing PyroCMS v3 and have been tracking down some performance issues. So far, everything leads to the autoloading. Which is composer in this case. It would appear that findFileWithExtension is being called multiple times, in multiple instantiations of the ClassLoader class causing high CPU usage because the class map is large.

Here is a Blackfire profile: https://blackfire.io/profiles/edbeb001-c72c-4c89-9e9f-d76f5edccacd/graph

Here is a dump of the $class property requested from findFileWithPath: http://cl.ly/text/2x0H2P06012o

As you can see the method is getting BURNED through and multiple times for the same class. With a large class_map this is wreaking havoc on load times. The StoreModuleServiceProvider class for instance is checked 18 times!! Yowzers..

Any ideas on how to avoid this? Seems like, if this method is used multiple times the $class => $file should have a simple runtime cache to prevent looking up the file / checking existence multiple times.

**Comment by alcohol** [comment]
Is this profile for one request?

**Comment by Seldaek** [comment]
![image](https://cloud.githubusercontent.com/assets/183678/9848227/0882f156-5ad7-11e5-85c8-1c8d5b7389ce.png)

This bit seems to say that the autoloader is triggered 845 times but then it calls ClassLoader::loadClass 2986 times, which makes no sense to me, unless you got the same loader registered several times or something. But even then once the class is loaded once it should stop calling the others, so that doesn't make sense unless you are trying to autoload many classes that don't exist *and* have the classloader registered several times?

In any case, something doesn't seem very normal here.. might be in your setup/bootstrap, or might be what your code does, but AFAIK the class loader itself doesn't call findFileWithPath in a loop for no reason.

**Comment by alcohol** [comment]
Can you pastebin the contents (exactly as-is, the entire file) of `./bootstrap/cache/compiled.php` from the environment which you profiled for us?

**Comment by RyanThompson** [comment]
@alcohol yes it is one request. Also I am not using a compiled file in order to monitor code changes as I was snooping around.

@Seldaek I am unsure how I would end up with multiple instances of it unless I am resolving it incorrectly. I am extending it with a singleton class here: 

https://github.com/anomalylabs/streams-platform/blob/1.0/develop/src/Addon/AddonLoader.php

I have tried simply injecting it (through the service container) and have experienced the same.

Should I be accessing the ClassLoader differently?

**Comment by alcohol** [comment]
If you can tell me how I could create a working environment to reproduce the issue I might be able to do some debugging. But otherwise it's all going to be guess-work and there isn't much we can do to help you any further.

**Comment by RyanThompson** [comment]
You can install the software if you like:

composer create-project pyrocms/pyrocms=3.0-beta1 --prefer-dist

See: https://www.pyrocms.com/docs/pyrocms/setup/installation#installing-pyrocms

Just give write permissions to bootstrap/cache, storage, public/assets and hit the app url to fire up the installer.

That will give you the same issue and the full codebase to dig around in if you like. Feel free to ping me here or directly at ryan@pyrocms.com if you want. Happy to help out as much as I can. I am making a slight change right now that might help eliminate the variable in how I am accessing the class loader:

https://github.com/anomalylabs/streams-platform/commit/9b01a4fc60964db863394f8dd63931548d722cfd

**Comment by alcohol** [comment]
That change looks horrible. It does not seem safe at all to rely on the return value of `spl_autoload_functions()[1][0]` blindly like that :-(.

**Comment by RyanThompson** [comment]
Lol it's not final - I am trying to eliminate possible anomalies at this point. Ill change it in a sec to loop and look for the instance.

**Comment by alcohol** [comment]
Oh ok. Maybe better not to include it in the conversation then :)

**Comment by RyanThompson** [comment]
I've improved it a bit ^_^

Looks like there was little to know change however.

**Comment by RyanThompson** [comment]
@Seldaek any idea on what to look for in trying to identify this issue? I have to assume at this point that there is an error in code or something but aside from the performance hit - it's operating fine. Any caveats or anything I could look for would help a lot.

**Comment by Seldaek** [comment]
Sorry but not really no. I'd say try to reproduce this in isolation adding piece by piece to see at which point it goes bonkers.

**Comment by RyanThompson** [comment]
@alcohol / @Seldaek 

I have narrowed this down to DEFINITELY how the addons are registering. The findFile($class) method works perfect up till the first extension and it's repeating 5 times.

Consider the following print of what it's finding:

```
Illuminate\Console\Scheduling\Schedule
Anomaly\Streams\Platform\View\ViewOverrides
Anomaly\Streams\Platform\Http\Middleware\MiddlewareCollection
Anomaly\Streams\Platform\Support\Collection
Anomaly\Streams\Platform\View\ViewMobileOverrides
Anomaly\Streams\Platform\Model\EloquentCollection
Anomaly\ActivationSecurityCheckExtension\ActivationSecurityCheckExtension
Anomaly\ActivationSecurityCheckExtension\ActivationSecurityCheckExtension
Anomaly\ActivationSecurityCheckExtension\ActivationSecurityCheckExtension
Anomaly\ActivationSecurityCheckExtension\ActivationSecurityCheckExtension
Anomaly\ActivationSecurityCheckExtension\ActivationSecurityCheckExtension
Anomaly\ActivationSecurityCheckExtension\ActivationSecurityCheckExtension
Anomaly\Streams\Platform\Addon\Extension\Extension
Anomaly\Streams\Platform\Addon\Extension\Extension
Anomaly\Streams\Platform\Addon\Extension\Extension
Anomaly\Streams\Platform\Addon\Extension\Extension
Anomaly\Streams\Platform\Addon\Extension\Extension
Anomaly\Streams\Platform\Addon\Extension\Extension
Anomaly\Streams\Platform\Addon\Addon
Anomaly\Streams\Platform\Addon\Addon
Anomaly\Streams\Platform\Addon\Addon
Anomaly\Streams\Platform\Addon\Addon
Anomaly\Streams\Platform\Addon\Addon
Anomaly\Streams\Platform\Addon\Addon
```

Before: Perfect
After: Hogwash

What could I possibly be doing wrong? The logic in there is pretty simple:

I recurse over the addon paths 1 time per: https://github.com/anomalylabs/streams-platform/blob/1.0/develop/src/Addon/AddonManager.php#L122

And load 1 time per: https://github.com/anomalylabs/streams-platform/blob/1.0/develop/src/Addon/AddonLoader.php#L44

The AddonLoader is also a singleton class.. 

Halp meh.. Im so confused as to why this is binding up like this.

**Comment by RyanThompson** [comment]
In fact, ANYTHING and everything out of composer at that point is duplicated. Addon classes, core classes, aliases, illuminate stuff.. All of it after that point.

**Comment by RyanThompson** [comment]
Ok.. so looks like this was caused from addons providing their own ClassLoader instance.. Ill need to go go through and make the AddonLoader read the composer.json files and register them with the ClassLoader it's got injected. 

Next question would be, is there a better way. Perhaps adding the class map into the AddonLoader->loader instance instead of require_once it..

**Comment by Seldaek** [comment]
I think every addon defining a class loader would be kinda ok, if they don't all load the classmap.. If they only have a simple config for one psr-0 or psr-4 namespace prefix, then going through them would be pretty quick. Still slower than hitting just one properly configured class loader though of course.
