### ISSUE TITLE
Configuration to add confirmation to commands

### ISSUE THREAD

**Issue by ejunker** [composer/composer#4424]
There are lots of people that still do not understand the difference between install and update. I ran into an issue where composer update was ran in production instead of composer install. I think it would be nice if there would be a way to add a configuration option to composer.json where you could define commands that require a confirmation and/or possibly an message to display to the user. In general, I'm just looking for a way to prevent composer update from being ran in production.

**Comment by alcohol** [comment]
Simple, don't use Composer on production environments. You really should not :-).

**Comment by Seldaek** [comment]
IMO this is an education issue, and I think if anything adding a new article to the docs that explains the whole lock / update / install issue in details that can be linked to would be a good thing. Adding the feature you describe though I think it's a bit of feature creep for not so much benefit. People don't read warnings and just will confirm blindly.

**Comment by ejunker** [comment]
I think adding more explicit documentation about composer best practices would be a great idea. Focusing on things such as when to run update vs install and that you should check your composer.lock in to source control. Also things like how dev-master is not recommended.
