### ISSUE TITLE
Absolute instead of relative path in lock file

### ISSUE THREAD

**Issue by jyggen** [composer/composer#4439]
I updated Composer today and it seems like a recent commit changed the behaviour of the path repository. Previously the relative path to the package was stored in the lock file, this is reflected in the `composer update` output as well:

```
- Installing vendor/package (dev-develop)
    Symlinked from ./components/package
```

`composer.lock` looks like this:

```
"dist": {
    "type": "path",
    "url": "./components/package",
    "reference": "",
    "shasum": null
},
```
Now if I update Composer and remove an already installed "path package" (or add a new one) it'll use the absolute path instead, once again reflected in the output:

```
- Installing vendor/package (dev-develop)
    Symlinked from /absolute/path/to/components/package/
```

`composer.lock` looks like this:

```
"dist": {
    "type": "path",
    "url": "/absolute/path/to/components/package/",
    "reference": "",
    "shasum": null
},
```

This makes it impossible to do a `composer install` of the project on another machine, since Composer will complain that it can't find the absolute path. I've been trying to figure out the cause, but with Composer being a phar and all it's not so straightforward (for me at least).

Is this change of behaviour intended or did it accidentally make it into the code? Makes it kind of hard to use path repositories for anything that lives on more than one machine :)

Thanks!

**Comment by cs278** [comment]
Confirmed, if I revert 3ef222c9201e990aa380930802678467c558401f the lock file has the relative path stored in it.

**Comment by Seldaek** [comment]
@dennisbirkholz @sroze could you please have a look at this?

**Comment by sroze** [comment]
Didn't see @dennisbirkholz's PR about the path repository (#4422), and it's effectively breaking the relative paths. I let @dennisbirkholz digging into that as I won't be able to do that today.

**Comment by dennisbirkholz** [comment]
The thing is: I added 3ef222c after I was told the stored URL should be absolute. But after inspecting the latest changes before my changes this seems to be an oversight. [Pull 4444](https://github.com/composer/composer/pull/4444) makes the stored URLs relative again, sorry.
