### ISSUE TITLE
Incorrect dist-url from Github for reference

### ISSUE THREAD

**Issue by ValeriyLiquid** [composer/composer#4442]
Hi, I've tried to update ``google/apiclient`` with this ``composer.json``:

```JSON
{
    "name": "owox/test",
    "authors": [
        {
            "name": "Валерий Маслеников",
            "email": "v.maslenikov@owox.com"
        }
    ],
    "require": {
        "google/apiclient": "dev-master#066668986ea099d406098ba0bb2a61cc51f5a0de"
    }
}
```
So, I run ``composer update`` ([log](https://gist.github.com/ValeriyLiquid/da0345299d11fbda2b26)) and got ``composer.lock`` with this content:
```JSON
        ...
        {
            "name": "google/apiclient",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/google/google-api-php-client.git",
                "reference": "066668986ea099d406098ba0bb2a61cc51f5a0de"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/google/google-api-php-client/zipball/2bc00ec4e8fa1a5eec793d800fac339f30b730db",
                "reference": "066668986ea099d406098ba0bb2a61cc51f5a0de",
                "shasum": ""
            }
```          
Expectation | Real
--------------- | ----------
066668986ea099d406098ba0bb2a61cc51f5a0de | 066668986ea099d406098ba0bb2a61cc51f5a0de
https://api.github.com/repos/google/google-api-php-client/zipball/066668986ea099d406098ba0bb2a61cc51f5a0de|https://api.github.com/repos/google/google-api-php-client/zipball/2bc00ec4e8fa1a5eec793d800fac339f30b730db

**Comment by alcohol** [comment]
It's not relevant.

**Comment by s-chizhik** [comment]
@alcohol, can you explain(maybe is there any doc, or manual) usage of `url`?

**Comment by alcohol** [comment]
It's internal only, so it does not need to be documented. Don't worry about it. The above will still install what you expect it to install.

**Comment by ValeriyLiquid** [comment]
Ok, thank you, I was really surprised (and confused) when did this operations and got this result :)
