### ISSUE TITLE
Describe composer API

### ISSUE THREAD

**Issue by DanielHreben** [composer/composer#4445]
It will be great if somebody describe how to use composer programmatically (instantiate $composer and use his object interface) in documentation. It's enough regular task, [here](https://github.com/composer/composer/issues/3425) and [here](https://github.com/composer/composer/issues/4399) is already a similar questions was asked. 

Most package managers like [CPAN](http://search.cpan.org/~andk/CPAN-2.10/lib/CPAN.pm) or [NPM](https://github.com/npm/npm#using-npm-programmatically) has this features and it's described.

**Comment by alcohol** [comment]
https://getcomposer.org/apidoc/master/index.html

But in general, my recommendation is, don't use it.

**Comment by SDSWanderer** [comment]
it's better than nothing, but it does not give much more than just view the source code.
I think that CPAN docs much friendly.

**Comment by joachim-n** [comment]
I've done a bit of dabbling, and this works (I have it in a standalone script right now for fast prototyping, hence the include statement)

```
use Composer\IO\NullIO;
use Composer\Factory;
use Composer\Repository\InstalledRepository;

require 'vendor/autoload.php';

$io = new NullIO();
$composer = Factory::create($io);

$rootPkg = $composer->getPackage();
$installedRepo = new InstalledRepository(array($composer->getRepositoryManager()->getLocalRepository()));


$packages = $installedRepo->getPackages();
dump($packages);
```

$packages is an array of Composer\Package\CompletePackage which looks like it has useful data.

It would be nice to have this sort of thing documented somewhere.

**Comment by Seldaek** [comment]
The thing though is we do offer better ways to address packages already like https://getcomposer.org/doc/07-runtime.md#installed-versions - and if that's not enough the best thing generally is to come talk to us and ask, so we can hopefully find a way to help the whole community build better, instead of everyone building their own hacky mess on top of our APIs which are not necessarily supported in the way they expect.

**Comment by joachim-n** [comment]
That looks great -- thank you!

I'd searched on google and this issue was one of the top hits.

**Comment by Seldaek** [comment]
Ah well, good thing it has a correct pointer in it now then :)
