### ISSUE TITLE
Error message missing openssl extension

### ISSUE THREAD

**Issue by picardowoods** [composer/composer#4447]
I have tried to download composer prior to downloading propel (as recommended) but the following error message keeps appearing. Any help would be very welcomed.

Some settings on your machine make Composer unable to work properly.
Make sure that you fix the issues listed below and run this script again:

The openssl extension is missing, which means that secure HTTPS transfers are impossible.
If possible you should enable it or recompile php with --with-openssl

I presume it's obvious, to some at least, I have tried reload php5.5 but this hasn't helped.

Regards

Picardowoods

**Comment by stof** [comment]
well, try running ``php -m`` to list all loaded extension to see whether openssl is in it. If it is not, enable the openssl extension. Without it, your PHP setup is unable to make HTTPS requests, which is why composer complains.

**Comment by picardowoods** [comment]
Hi Chris


Thanks for your response, the openssl file is in the extras/ssl folder on its own, how can I enable it? it appears to be correct, though it appears to want to open in dreamweaver, should it open with something else?


Regards


Carl


Mr Carl Woods

mk1militaria.com (mk1militaria on ebay)

Juniper House, 33 Main Street, Croxton Kerrial, Grantham, Lincs.

01476 870498 or mob 07740 290790


________________________________

**Comment by FranckBlanchard** [comment]
I have the same problem, and the php_openssl is enable. I'm working on window 7, with wamp.
Thanks

**Comment by picardowoods** [comment]
Hi Frank,

I'm happier (slightly) that it's not just me!


Carl


Mr Carl Woods

mk1militaria.com (mk1militaria on ebay)

Juniper House, 33 Main Street, Croxton Kerrial, Grantham, Lincs.

01476 870498 or mob 07740 290790


________________________________

**Comment by FranckBlanchard** [comment]
Hi i found a solution. Check your php.ini that the line who load the extension is uncomment. It must work !

**Comment by picardowoods** [comment]
Hi Franck


I guess this is what you meant? I opened the php.ini file in notebook, the are lots of extension files. So I presume you mean extension=msql.dll or extension=modulename.extension?


If you wish to have an extension loaded automaticly, use the following
; syntax:
;
;   extension=modulename.extension
;
; For example, on Windows:
;
;   extension=msql.dll
;
; ... or under UNIX:
;
;   extension=msql.so
;
; Note that it should be the name of the module only; no directory information
; needs to go here.  Specify the location of the extension with the
; extension_dir directive above.

;Windows Extensions
;Note that MySQL and ODBC support is now built in, so no dll is needed for it.
;
;extension=php_bz2.dll
;extension=php_ctype.dll
;extension=php_cpdf.dll
;extension=php_curl.dll
;extension=php_cybercash.dll
;extension=php_db.dll
;extension=php_dba.dll
;extension=php_dbase.dll
;extension=php_dbx.dll
;extension=php_domxml.dll
;extension=php_dotnet.dll
;extension=php_exif.dll
;extension=php_fdf.dll
;extension=php_filepro.dll
;extension=php_gd.dll
;extension=php_gettext.dll
;extension=php_hyperwave.dll
;extension=php_iconv.dll
;extension=php_ifx.dll
;extension=php_iisfunc.dll
;extension=php_imap.dll
;extension=php_ingres.dll
;extension=php_interbase.dll
;extension=php_java.dll
;extension=php_ldap.dll
;extension=php_mbstring.dll
;extension=php_mcrypt.dll
;extension=php_mhash.dll
;extension=php_ming.dll
;extension=php_mssql.dll
;extension=php_oci8.dll
;extension=php_openssl.dll
;extension=php_oracle.dll
;extension=php_pdf.dll
;extension=php_pgsql.dll
;extension=php_printer.dll
;extension=php_sablot.dll
;extension=php_snmp.dll
;extension=php_sybase_ct.dll
;extension=php_xslt.dll
;extension=php_yaz.dll
;extension=php_zlib.dll
;extension=php_w32api.dll



Mr Carl Woods

mk1militaria.com (mk1militaria on ebay)

Juniper House, 33 Main Street, Croxton Kerrial, Grantham, Lincs.

01476 870498 or mob 07740 290790


________________________________

**Comment by FranckBlanchard** [comment]
Hi
I presume you are under Windows OS
uncomment this line
;extension=php_openssl.dll
so it become 
extension=php_openssl.dll
Hope I help
Franck

**Comment by ashumalaviya** [comment]
Thank you

**Comment by donatieneric** [comment]
ztg
