### ISSUE TITLE
Problem on the dist attribute when using the API url

### ISSUE THREAD

**Issue by ninhdh0** [composer/composer#4449]
The dist attribute in composer.lock

If the url formated like: 
```
"dist": {
    "type": "gzip",
   "url": "https://gitlab.example.co/api/v3/projects/example-project/repository/archive?private_token=XXXXX"
}
```
My url return example-project.tar.gz, composer can not extract the package or download.

Error output
Executing command (CWD): gzip -cd 'mypath...../archive' > 'vendor/composer/3ec89de9/arch'

**Comment by alcohol** [comment]
Can you give as some steps to reproduce this?
