### ISSUE TITLE
How to specify `vendor-dir` and `bin-dir` from the command-line?

### ISSUE THREAD

**Issue by kenorb** [composer/composer#4450]
I'd like to specify `vendor-dir` or `bin-dir` as argument when running `composer update`, instead of in the JSON config:

    "config": {
        "vendor-dir": "/var/lib/vendor",
        "bin-dir": "/usr/local/bin"
    },

It's possible? Or it needs to be implemented?

**Comment by kenorb** [comment]
Solved as [jonhattan](https://github.com/drush-ops/drush/issues/1628#issuecomment-143177058) suggested:

    COMPOSER_BIN_DIR=/usr/local/bin COMPOSER_VENDOR_DIR=/var/lib/vendor sudo composer update

Optionally plus `COMPOSER_HOME` to specify where to keep `.composer` dir.

**Comment by xserrat** [comment]
I have a question about that. How to change a local config key/value from the command-line?

```json
"config": {
       "my-config-variable": "new-value"
}
```

I tried ```$ composer config my-config-variable=new-value``` but not work. 

Are there any solution?

**Comment by stof** [comment]
Pass 2 arguments:

```bash
$ composer config my-config-variable new-value
```
