### ISSUE TITLE
composer update throws InvalidArgumentException when using 'path' type repository

### ISSUE THREAD

**Issue by juanpescador** [composer/composer#4451]
With a 'path' type repository, defined as following in the project's `composer.json`:

    ...
    "repositories": [
        {
            "type": "composer",
            "url": "http://wpackagist.org"
        },
        {
            "type": "path",
            "url": "../private-packages/theme/"
        }
    ],
    "require": {
        "php": ">=5.5",
        "composer/installers": "~1.0.12",
        "vlucas/phpdotenv": "^2.0.1",
        "johnpbloch/wordpress": "4.3",
        "vendor/theme": "1.0.0"
    },
    "extra": {
        "installer-paths": {
            "web/app/mu-plugins/{$name}/": ["type:wordpress-muplugin"],
            "web/app/plugins/{$name}/": ["type:wordpress-plugin"],
            "web/app/themes/{$name}/": ["type:wordpress-theme"]
        },
        "wordpress-install-dir": "web/wp"
    }
    ...

I'm getting an error message when running `composer update`, during installation of a `wordpress-theme` type package, both from Windows and from Linux. The message is<sup>1</sup>:

    [InvalidArgumentException]
      $from (web/app/themes/theme/) and $to (/vagrant/private-packages/theme) must
      be absolute paths.
    Exception trace:
     () at phar:///usr/lib/composer/composer.phar/src/Composer/Util/Filesystem.php:312
     Composer\Util\Filesystem->findShortestPath() at phar:///usr/lib/composer/composer.phar/src/Composer/Downloader/PathDownloader.php:51
     Composer\Downloader\PathDownloader->download() at phar:///usr/lib/composer/composer.phar/src/Composer/Downloader/DownloadManager.php:201
     Composer\Downloader\DownloadManager->download() at phar:///usr/lib/composer/composer.phar/src/Composer/Installer/LibraryInstaller.php:156
     Composer\Installer\LibraryInstaller->installCode() at phar:///usr/lib/composer/composer.phar/src/Composer/Installer/LibraryInstaller.php:87
     Composer\Installer\LibraryInstaller->install() at phar:///usr/lib/composer/composer.phar/src/Composer/Installer/InstallationManager.php:152
     Composer\Installer\InstallationManager->install() at phar:///usr/lib/composer/composer.phar/src/Composer/Installer/InstallationManager.php:139
     Composer\Installer\InstallationManager->execute() at phar:///usr/lib/composer/composer.phar/src/Composer/Installer.php:600
     Composer\Installer->doInstall() at phar:///usr/lib/composer/composer.phar/src/Composer/Installer.php:233
     Composer\Installer->run() at phar:///usr/lib/composer/composer.phar/src/Composer/Command/UpdateCommand.php:143
     Composer\Command\UpdateCommand->execute() at phar:///usr/lib/composer/composer.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
     Symfony\Component\Console\Command\Command->run() at phar:///usr/lib/composer/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:874
     Symfony\Component\Console\Application->doRunCommand() at phar:///usr/lib/composer/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:195
     Symfony\Component\Console\Application->doRun() at phar:///usr/lib/composer/composer.phar/src/Composer/Console/Application.php:147
     Composer\Console\Application->doRun() at phar:///usr/lib/composer/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:126
     Symfony\Component\Console\Application->run() at phar:///usr/lib/composer/composer.phar/src/Composer/Console/Application.php:82
     Composer\Console\Application->run() at phar:///usr/lib/composer/composer.phar/bin/composer:43
     require() at /usr/lib/composer/composer.phar:25

The error is throwing from [findShortestPath()][FindShortestPathErrorSource]; the `$from` path seems to incorrectly be passed in as relative instead of absolute.

Changing the repository type to 'artifact', zipping the `theme` package and changing the `url` property to the correct directory results in a successful `composer update`; the theme ends up in `web/app/themes/theme`.

If this is low-hanging fruit I could attempt a fix over the weekend if you can point me in the right direction, though I don't have a PHP development environment set up.

## Appendix

I don't think it's relevant, as the package installs correctly with the artifact repository type, but here's the package's `composer.json`:

    {
        "name": "vendor/theme",
        "version": "1.0.0",
        "type": "wordpress-theme",
        "description": "A private WordPress theme."
    }

<sup>1</sup>On Windows the `/vagrant/private-packages/theme` absolute path is replaced with the Windows equivalent, so I don't think it's a platform issue.

[FindShortestPathErrorSource]: https://github.com/composer/composer/blob/e8d84a1a296057e197579eff5287debdbb406ca4/src/Composer/Util/Filesystem.php#L312
[RootsBedrock]: https://github.com/roots/bedrock/blob/master/composer.json

**Comment by alcohol** [comment]
The `path` repository type is quite new. I don't think anyone anticipated that this would be used for plugins. We can look into this.

**Comment by antzhdanov** [comment]
I think we could just make sure we work with absolute paths before https://github.com/composer/composer/blob/master/src/Composer/Downloader/PathDownloader.php#L51
If agree, I have a working example that I can turn into pull request.

**Comment by alcohol** [comment]
No, relative paths must be supported by the Path repository. Especially since absolute paths can cause issues on VM's/Docker images etc.

**Comment by dennisbirkholz** [comment]
> I mean, you can use it for finding the shortest path, but I'm not sure how that will work in the above scenarios, where host and guest paths are not identical (when resolving the absolute path).

In this case, the second parameter ``/vagrant/private-packages/theme`` should not have been made absolute at all (as it is relative in the repository definition) and the ``findShortestPath()`` method needs to be adjusted to also accept two relative paths for its calculations (but mixed relative/absolute paths don't make sense IMHO).

**Comment by jeremyzahner** [comment]
+1

**Comment by rkaralkin** [comment]
+1

**Comment by joshdaws** [comment]
+1

**Comment by Seldaek** [comment]
I believe this isn't relevant anymore using the latest version of the path repo code but I might be mistaken. Can someone confirm?

**Comment by antzhdanov** [comment]
Nope, I've got the same error message.

**Comment by Seldaek** [comment]
OK so it's still broken to the custom installer I guess.. Not sure if this is fixable without fixing up the installer, but thanks for confirming anyway.

**Comment by schlessera** [comment]
I have encountered this issue as well, and fixed it to simplify my local development. I am not sure whether this is the best approach, but it seems to work for my use cases so far.

It seems like there are no unit tests for `PathDownloader` so far, so I didn't check/update these.
