### ISSUE TITLE
Composer not using oAuth for private repository

### ISSUE THREAD

**Issue by AndrzejFR** [composer/composer#4453]
Composer is not able to download private repositories, we have them in our own packagist. Everything works fine if there is ssh key set but we want composer to authenticate using github oauth. 

```
  - Installing footballradar/thrift-installer-plugin (dev-master 7a378a4)
    Cloning 7a378a4a01a3cd14ad556a91b1a9fde12d342836
Executing command (CWD): git clone --no-checkout 'git://github.com/footballradar/thrift-installer-plugin.git' '/var/www/sbs/vendor/footballradar/thrift-installer-plugin' && cd '/var/www/sbs/vendor/footballradar/thrift-installer-plugin' && git remote add composer 'git://github.com/footballradar/thrift-installer-plugin.git' && git fetch composer
Executing command (CWD): git clone --no-checkout 'https://github.com/footballradar/thrift-installer-plugin.git' '/var/www/sbs/vendor/footballradar/thrift-installer-plugin' && cd '/var/www/sbs/vendor/footballradar/thrift-installer-plugin' && git remote add composer 'https://github.com/footballradar/thrift-installer-plugin.git' && git fetch composer
Executing command (CWD): git clone --no-checkout 'git@github.com:footballradar/thrift-installer-plugin.git' '/var/www/sbs/vendor/footballradar/thrift-installer-plugin' && cd '/var/www/sbs/vendor/footballradar/thrift-installer-plugin' && git remote add composer 'git@github.com:footballradar/thrift-installer-plugin.git' && git fetch composer
Executing command (CWD): git --version
Failed: [RuntimeException] Failed to clone git@github.com:footballradar/thrift-installer-plugin.git via git, https, ssh protocols, aborting.

- git://github.com/footballradar/thrift-installer-plugin.git
  Cloning into '/var/www/sbs/vendor/footballradar/thrift-installer-plugin'...
  warning: expected SRV RR, found RR type 1
  fatal: remote error: 
    Repository not found.

- https://github.com/footballradar/thrift-installer-plugin.git
  Cloning into '/var/www/sbs/vendor/footballradar/thrift-installer-plugin'...
  remote: Invalid username or password.
  fatal: Authentication failed for 'https://github.com/footballradar/thrift-installer-plugin.git/'

- git@github.com:footballradar/thrift-installer-plugin.git
  Cloning into '/var/www/sbs/vendor/footballradar/thrift-installer-plugin'...
  Permission denied (publickey).
  fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.



                                                                                                                     
  [RuntimeException]                                                                                                 
  Failed to clone git@github.com:footballradar/thrift-installer-plugin.git via git, https, ssh protocols, aborting.  
  - git://github.com/footballradar/thrift-installer-plugin.git                                                       
    Cloning into '/var/www/sbs/vendor/footballradar/thrift-installer-plugin'...                                      
    warning: expected SRV RR, found RR type 1                                                                        
    fatal: remote error:                                                                                             
      Repository not found.                                                                                          
  - https://github.com/footballradar/thrift-installer-plugin.git                                                     
    Cloning into '/var/www/sbs/vendor/footballradar/thrift-installer-plugin'...                                      
    remote: Invalid username or password.                                                                            
    fatal: Authentication failed for 'https://github.com/footballradar/thrift-installer-plugin.git/'                 
  - git@github.com:footballradar/thrift-installer-plugin.git                                                         
    Cloning into '/var/www/sbs/vendor/footballradar/thrift-installer-plugin'...                                      
    Permission denied (publickey).                                                                                   
    fatal: Could not read from remote repository.                                                                    
                                                                                                                     
    Please make sure you have the correct access rights                                                              
    and the repository exists.                                       
```

We did run `composer.phar config -g  github-oauth.github.com <token>`,
we tried putting token in composer.json as well but no difference.

Maybe the problem is in our packagist configuration but we have no idea what to look for.

**Comment by alcohol** [comment]
Did you set https://github.com/composer/packagist/blob/master/app/config/parameters.yml.dist#L29 ?

**Comment by alcohol** [comment]
Are you running packagist scripts as the same user you set the oauth token for?

**Comment by alcohol** [comment]
Actually never mind. As far as I know, the oauth token is only used for the API rate limit. I don't believe it is used for authentication. You have to use a valid ssh key.

**Comment by AndrzejFR** [comment]
That is very counterintuitive. I would expect oauth token to handle authentication as name suggest. Is it something you plan to support in the future?

**Comment by alcohol** [comment]
We support oauth tokens.

**Comment by AndrzejFR** [comment]
You wrote that they are not used for authentication, only for api limit, and that we have to use ssh keys. So I am asking if you will support authentication with oauth in the future?

**Comment by stloyd** [comment]
Git clone never used oauth tokens as this is not job done by composer, but by git applications, they commonly use SSH or username + password authentication, but they (IIRC) can't use tokens.

Token based authentication can be used (and it is already) to use Github API calls, which in fact are all calls to Github website (downloading etc.).

**Comment by alcohol** [comment]
For accessing repositories you need to use it like described here: https://help.github.com/articles/git-automation-with-oauth-tokens/

Which means it requires user input.

**Comment by Seldaek** [comment]
I think it'll attempt to use the oauth token for clones right now, as per https://github.com/composer/composer/blob/master/src/Composer/Util/Git.php#L100-L106 - you can check if it does by running composer with -vvv and see which git commands get executed.

But yeah it seems that maybe this is not good enough for github (anymore?).

**Comment by AndrzejFR** [comment]
The output with -vvv is as posted above. 

Providing token in prompt is not a solution as the problem is when building a project :/

Btw it used to work. We had successful builds, i am sure it worked on 4th of September. Not sure when exactly it started to fail, i thought it could be packagist issue as we have updated it in the meantime.

**Comment by alcohol** [comment]
Should still work. Are you positive your token is still valid?

You can try it manually: git clone https://<token>@github.com/<username>/<repository>

**Comment by AndrzejFR** [comment]
yes, i am positive

i run `git clone https://github.com/footballradar/thrift-installer-plugin.git` and used token as password and it got downloaded.

**Comment by alcohol** [comment]
Well, that's not the same as the way I described. Please take examples literal. Don't adjust them.

Regardless, I think it's safe to assume the token is valid. Which leaves just one option: you are running your build scripts as a different user, or you simply did not configure the token properly for that user.

**Comment by AndrzejFR** [comment]
can i set username to be used in composer config?

**Comment by alcohol** [comment]
You don't need a username. That is the point that I was making with my example.

As the user of your build jobs, simply run: `composer config -g github-oauth.github.com <oauthtoken>`

**Comment by AndrzejFR** [comment]
I did run it,
i can see my token in `~/.composer/auth.json` and still see same error. As i wrote in first post i tried putting it in composer.json as well (it is not there now, i removed it) but no difference.

**Comment by alcohol** [comment]
Are **you** running the build jobs?

**Comment by AndrzejFR** [comment]
`git clone https://<token>@github.com/footballradar/thrift-installer-plugin.git` works

I am running it in docker container that i build locally, but that is same container that gets build by jenkins.

**Comment by alcohol** [comment]
Please, are you at all familiar with users on Linux systems?

**Comment by alcohol** [comment]
Did you try making `composer config -g github-oauth.github.com <oauthtoken>` part of your build process? You can assign the token value to a global Jenkins variable and replace this in your build step. That way you can be sure it is setup for the right user, and if you change it you only have to change it in one place.

**Comment by AndrzejFR** [comment]
yes i am. Our docker container has only one user and it is root, everything is run as root.
Yes we run `composer config ...` as part of build process.
This is from our DockerFile
```
RUN /usr/local/bin/composer config -g github-oauth.github.com <token>
RUN /usr/local/bin/composer install --verbose --prefer-dist --optimize-autoloader --no-dev
```
Does user i am running as really matter? As long as i run `composer config...` and `composer install` as same user that should work, right?

**Comment by ZAYEC77** [comment]
Hi, I think my problem is related with this issue.
When I run `composer update`,  I get message:

```
Your GitHub credentials are required to fetch private repository metadata (git://github.com/DmitryBaranovskiy/eve.git)
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+F1-laptop+2015-10-08+0043
to retrieve a token. It will be stored in "/home/USER/.composer/auth.json" for future use by Composer.
Token (hidden):
```
but token has already exist:
```json
{
    "github-oauth": {
        "github.com": "0000000000000000000000000000000"
    }
}
```
And when I use the same token, it continue to work.

I think that composer doesn't reuse this token.

**Comment by Cayan** [comment]
Did anyone figure it out? Are tokens the best solution for private repositories within a docker container?

**Comment by antonmarin** [comment]
Seems like problem still exists
```
Failed to clone the git@github.com:DmitryBaranovskiy/eve.git repository, try running in interactive mode so that you can enter your GitHub credentials

                                                                                                                                                                            
  [RuntimeException]                                                                                                                                                        
  Failed to execute git clone --mirror 'https://***:***@github.com/DmitryBaranovskiy/eve.git' '/home/user/.composer/cache/vcs/git-github.com-DmitryBaranovskiy-eve.git/'  
  error: The requested URL returned error: 403 Forbidden while accessing https://***:***@github.com/DmitryBaranovskiy/eve.git/info/refs                                     
  fatal: HTTP request failed
```

**Comment by martinAtLs** [comment]
In case someone still have issue with that I follow travis way if doing in our docker process and it worked !

https://docs.travis-ci.com/user/private-dependencies/#API-Token
