### ISSUE TITLE
Use different branches in different environments

### ISSUE THREAD

**Issue by Henk8** [composer/composer#4457]
We are using composer to pull our own framework into the project. We have several environments, stages, for our project where we pull different branches.

For our release candidate we have a git branch that we wan't to pull when deploying to our release candidate servers.

"require":{
    "Framework":"dev-RC"
}

If the project is build and verified on the release candidate we wan't to release it for live. But then we use another branch, the master.
So for the actual release I wan't to use the master instead of the RC.

"require":{
    "Framework":"dev-master"
}

Is there a possibility to request the RC branch for our release candidate environment and the master branch for our live release?

**Comment by alcohol** [comment]
You are actually happy with this workflow that you have?

**Comment by Henk8** [comment]
We are looking for the best possible solution and thougth this would work. Do you have any suggestions?

**Comment by alcohol** [comment]
Yes, it's called semantic versioning. It's pretty popular now a days. You can read more about it on [semver.org](http://semver.org).

**Comment by Henk8** [comment]
Thanks! We do something like it. but the article is great.
