### ISSUE TITLE
Configuration defined for http.basic configuration values is not listed as expected with composer config

### ISSUE THREAD

**Issue by kypfr** [composer/composer#4459]
Hello everybody,

composer config does not display the appropriate value for http-basic when we use composer config -l.
See the example bellow:

```
echo "{}" > composer.json
rm auth.json
test -f composer || (curl -sS https://getcomposer.org/installer | php -- --filename=composer)
./composer self-update
./composer config -a -f composer.json http-basic.subdomain.domain.com "username" "password";
./composer config -a -f composer.json http-basic.subdomain2.domain.com "username2" "password2";
cat auth.json
```
```
{
    "http-basic": {
        "subdomain.domain.com": {
            "username": "username",
            "password": "password"
        },
        "subdomain2.domain.com": {
            "username": "username2",
            "password": "password2"
        }
    }
}
```
 ```
./composer config -l -f composer.json | grep http-basic
```
```
[http-basic.composer.subdomain.domain.com.username] username
[http-basic.composer.subdomain.domain.com.password] password
[http-basic.composer.subdomain.domain.subdomain2.domain.com.username] username2
[http-basic.composer.subdomain.domain.subdomain2.domain.com.password] password2
```

i expect it to be:

```
[http-basic.composer.subdomain.domain.com.username] username
[http-basic.composer.subdomain.domain.com.password] password
[http-basic.composer.subdomain2.domain.com.username] username2
[http-basic.composer.subdomain2.domain.com.password] password2
```

This is a problem when we try to scripting these configuration values.

**Comment by alcohol** [comment]
I modified your post so its a bit easier to read.

It might appear to be a strange bug in the way the json file is manipulated. I'll see if I can reproduce it using a testcase. Possibly related to using the same key suffix multiple times.

**Comment by alcohol** [comment]
My bad, I misread your post. So.. listing the values is not working as expected?

**Comment by alcohol** [comment]
Upon further reading, your post is quite confusing.

* You are removing the `auth.json` file. 
* Then you are manipulating the `composer.json` file (`-a` only affects `--editor`). 
* And then somehow magically there is stuff in your `auth.json` file?
* And then you continue to list the contents of your `composer.json` file.

**Comment by alcohol** [comment]
Definitely a bug there. Has to do with how it passes on the key from the previous iteration somehow. Can reproduce it. Just need to figure out how to solve it now.

**Comment by alcohol** [comment]
Managed to fix it. No idea what the consequences are though. Need to investigate that or test it more thoroughly.

**Comment by alcohol** [comment]
On a side note: this is not a problem for scripting these values. It's a purely visual/cosmetic issue. The configuration is still correct so you can use it without any problems.

**Comment by kypfr** [comment]
For me this is not onlyn a cosmetic value:
with the example above,
```
./composer config -l | grep http.basic | grep subdomain.domain.com
```
will not return the same output than
```
./composer config -l | grep http.basic.subdomain.domain.com
```

**Comment by alcohol** [comment]
So you want to use the output and pass that to something else? Ok. Don't you have the values available from when you put them in there? Also, you could just use php for this instead of grep. It's not exactly output suited for piping into other processes.

**Comment by kypfr** [comment]
No:  this check is included in a MakeFile and so it's much easier to parse configuration used instead of  parse /project/path/composer.json, /project/path/auth.json, or ~/.composer/auth.json.

**Comment by alcohol** [comment]
Ok, but what is the actual use-case? I mean, if you are using grep, I guess that means you know what you are looking for already? So what is the point? You just want to verify it? Can you explain?

**Comment by kypfr** [comment]
Yes for sure: I want during the make test step to check if there is some credentials for a dedicated composer repository.

**Comment by Seldaek** [comment]
You could run `composer config http-basic.composer.subdomain2.domain.com.password` and check the exit code, if it's missing it'll be non-zero.

**Comment by kypfr** [comment]
Just to reply to your post seldaek

When reading your post, I've seen that when replacing domain name used, I've made a mistake;
this is well subdomain.domain.com and subdomain2.domain.com in the example above.

So to fetch it this is http-basic.subdomain2.domain.com.password but... It doesn't work!
If I try to the subdomain.domain.com to fetch the username:
```
./composer config http-basic.subdomain.domain.com.username
```
throw:
```
[RuntimeException]                                  
  http-basic.subdomain.domain.com.username is not defined 
```
```
./composer config -l | grep "http-basic.subdomain.domain.com.username"
[http-basic.subdomain.domain.com.username] a_username
```
the version used:
``
 ./composer --version
Composer version 1.0-dev (5ccaad92c19ac673435dbb2858ae20d14f34950d) 2015-09-30 10:52:04
```

the account is defined not in composer.json but in global auth.json file.

**Comment by alcohol** [comment]
It does work if you use it right. You just have to make sure that you consistently operate on the same files.

**Comment by alcohol** [comment]
I take it back.. it seems retrieving config values also breaks it a key contains multiple colons. Christ why weren't there any tests written for this :')

**Comment by alcohol** [comment]
`composer config http-basic.subdomain.domain.com` will work. It returns the array/hash of username and password. Not sure why you cannot select one of those specifically though.

**Comment by alcohol** [comment]
Should be fixed by #4470. Again, weird logic involving flawed assumptions around where '.' can occur or not occur.

**Comment by Seldaek** [comment]
Merged the fix, still no tests for it though ;)

**Comment by alcohol** [comment]
The problem is that there are virtually no tests at all for any of the Command classes. Maybe it they contained less logic, implying we move the logic to more specific purpose classes, testing would be easier also.

**Comment by Seldaek** [comment]
Yes of course moving the logic out of the commands would make sense 
before testing them. And yes testing them would be nice. Just takes some 
time :)

**Comment by Lewiscowles1986** [comment]
:+1: @alcohol 
`composer config http-basic.subdomain.domain.com username password` helped my iterate my magento2 vagrant, although it is hella annoying of repo providers to require login to install their SW, it's great that composer provides ways to allow me to continue to automate this.
