### ISSUE TITLE
composer diagnose fail when global composer file does not exists

### ISSUE THREAD

**Issue by kypfr** [composer/composer#4460]
Hello,

I encounter some errors when running diagnose. it fail with the following error:
**Checking composer.json: Reading ./composer.json**

```
pwd
```
/home/matthieu
```
ll /home/matthieu/.composer/composer.json
```
ls: Unable to read /home/matthieu/.composer/composer.json: File does not exists
```
ll /var/www/composer.json
```
-rw-r--r-- 1 matthieu matthieu 1089 sept. 29 09:14 /var/www/composer.json*
```
./composer diagnose -vvv --working-dir=/var/www/;
```
Changed CWD to /var/www
Reading ./composer.json
Loading config file /home/matthieu/.composer/auth.json
Loading config file ./composer.json
Executing command (/var/www): git describe --exact-match --tags
Executing command (/var/www): git branch --no-color --no-abbrev -v
Executing command (/var/www): hg branch
Executing command (/var/www): svn info --xml
**Failed to initialize global composer: Composer could not find the config file: /home/matthieu/.composer/composer.json**
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Loading plugin MagentoHackathon\Composer\Magento\Plugin
you may want to add the packages.magento.com repository to composer.
add it with: composer.phar config -g repositories.magento composer https?://packages.magento.com
activate magento plugin
**Checking composer.json: Reading ./composer.json
FAIL**
require.magento-hackathon/magento-composer-installer : unbound version constraints (@stable) should be avoided
Checking platform settings: OK
Checking git settings: Executing command (CWD): git config color.ui
OK
Checking http connectivity to packagist: Downloading http://packagist.org/packages.json
OK
Checking https connectivity to packagist: Downloading https://packagist.org/packages.json
OK
Checking github.com rate limit: Downloading https://api.github.com/rate_limit
OK
Checking disk free space: OK
Checking composer version: Downloading https://getcomposer.org/version
OK
```
echo $?
```
1

The validation of composer.json work fine.

```
./composer validate -vvv  /var/www/composer.json
```
Reading /var/www/composer.json
Reading /var/www/composer.json
Loading config file /home/matthieu/.composer/auth.json
Loading config file /var/www/composer.json
Executing command (/home/matthieu): git describe --exact-match --tags
Executing command (/home/matthieu): git branch --no-color --no-abbrev -v
Executing command (/home/matthieu): hg branch
Executing command (/home/matthieu): svn info --xml
**Failed to initialize global composer: Composer could not find the config file: /home/matthieu/.composer/composer.json**
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /var/www/composer.lock
Reading /var/www/composer.lock
/var/www/composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
require.magento-hackathon/magento-composer-installer : unbound version constraints (@stable) should be avoided
```
echo $?
```
0

It seems that diagnose try to load a composer.json file in my .composer folder. Why?

**Comment by kypfr** [comment]
```
./composer --version
```
Composer version 1.0-dev (c41079192f38f0fc446b17baa8f628dcb3b61e7d) 2015-09-28 09:38:16

**Comment by alcohol** [comment]
It always does that. It's fine. The exit codes not matching is the issue more likely.

**Comment by alcohol** [comment]
If you run validate in strict mode, it will return 1 too. Because diagnose considers the warning an error, but validate does not unless you run it in strict mode.

**Comment by kypfr** [comment]
Ok you says this is the default behaviour.

But why composer diagnose return 1?
My composer.json generate only warnings on versions defined for requirements, so composer diagnose should return 0. Why does it return 1?

**Comment by alcohol** [comment]
No. You are confusing two commands.

Diagnose is not validate. Diagnose will return an error code whenever something doesn't seem right and it might potentially cause issues. It goes beyond checking just your composer.json schema and also does connectivity tests and such.

Validate is strictly about validating the schema of your composer.json (and optionally also your .lock file). It will not throw an error code on warnings unless you tell it to, cause strictly speaking warnings are not a problem that can prevent you from submitting a composer.json to packagist.

**Comment by kypfr** [comment]
Hello,

I think ticket must not be closed: I provided you the composer validate output because in a previous issue regarding composer diagnose you said that perhaps it was a problem in project composer.json syntax.

So to be sure: diagnose will always fail (return code != 0) when there is no ~/.composer/composer.json file. that's right?

But I'm quite confuse: I don't exactly understand the aim role of this ~/.composer/composer.json file?
Why is it a requirement?

I run this diagnose in a makefile to ensure that everything is fine to process install.
Is there a way to diagnose without check this file?

regards

**Comment by alcohol** [comment]
No. Diagnose doesn't care about that. Diagnose returned error code 1 cause of the warning from validating your composer.json.

I've been trying to tell you, the missing ~/.composer/composer.json (also known as the global composer.json) is not an issue and it is not the reason for the exit status.

**Comment by alcohol** [comment]
To demonstrate, on one of my own projects:

```
rob@macbookpro /srv/git/github/iso3166 (master) $ composer diag -vvv
Reading ./composer.json
Loading config file /Users/rob/.composer/config.json
Loading config file /Users/rob/.composer/auth.json
Loading config file ./composer.json
Executing command (/srv/git/github/iso3166): git describe --exact-match --tags
Executing command (/srv/git/github/iso3166): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /Users/rob/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Checking composer.json: Reading ./composer.json
OK
Checking platform settings: OK
Checking git settings: Executing command (CWD): git config color.ui
OK
Checking http connectivity to packagist: Downloading http://packagist.org/packages.json
OK
Checking https connectivity to packagist: Downloading https://packagist.org/packages.json
OK
Checking github.com oauth access: Downloading https://api.github.com/user/repos
OK
Checking disk free space: OK
Checking composer version: Downloading https://getcomposer.org/version
OK
rob@macbookpro /srv/git/github/iso3166 (master) $ echo $?
0
```

See how I also don't have a global composer.json? It's not something that will cause an error exit code though.

**Comment by alcohol** [comment]
To be completely specific, diagnose returned an error because of this reason:

> require.magento-hackathon/magento-composer-installer : unbound version constraints (@stable) should be avoided

**Comment by kypfr** [comment]
Hello Alcohol,

oh ok thanks you.

So is it possible to have the same options for diagnose than validate:

 --no-check-all           Do not make a complete validation
 --no-check-lock          Do not check if lock file is up to date
 --no-check-publish       Do not check for publish errors

regards
