### ISSUE TITLE
Push URLs changed?

### ISSUE THREAD

**Issue by mindplay-dk** [composer/composer#4461]
Something changed with regards to Git push URLs in the past couple of months?

Anything that comes from GitHub via Composer into my vendor folder now has an `origin` with a push URL like, say, `git@github.com:mindplay-dk/middlemark.git`, which doesn't work on Windows - I get some error message like "no authentication methods available". I have to change the remote to, say, `https://github.com/mindplay-dk/middlemark.git`, before I can push.

My coworkers on Linux have no problems.

This didn't use to be a problem, and I think it started around the time #4384 started cropping up - could they be related?

Note that I don't use any certificates or anything like that, I just use my GitHub username/password.

**Comment by stof** [comment]
Well, it *can* work on windows if you configure your SSH access: https://help.github.com/categories/ssh/

Composer always tried several remote URLs for github repos (https, ssh and git). It may have selected a different one.

**Comment by alcohol** [comment]
This is most likely an environment issue, not Composer.

**Comment by mindplay-dk** [comment]
My point is, this used to work "out of the box" on Windows - standard Git install with default settings, standard Composer install, no additional changes required to get up and running.

I'm a casual Git user, I don't really want to know a bunch of stuff about Git or SSH - stuff I'd have to learn just so I can make certain changes once and get things to work.

In the past, this was a big factor that made me a somewhat late adapter of Composer - it wasn't until this stuff just worked, straight up, that I was willing/able to commit to it. I'm committed now, and I will have to go through the ropes, if that's what it takes to get it to work now, but -- if this is the experience Windows users are going to have now, with a default Git and Composer install, we have a problem; a lot of casual new users, if things don't work "out of the box", are going to simple give up.

I think this sort of thing was historically a big issue and a roadblock for Composer adoption...

**Comment by alcohol** [comment]
It is perhaps because your coworkers committed a lock file which contains a `git@...` source rather than a `https://...` source url. However, since you shared very little to no useful information with us, this is merely speculation. We have no `composer.json` nor a `composer.lock` or any log output to go by.

If you can give us the output of a `composer install` or `composer update` while running it with `-vvv` verbosity, we could be of more assistance perhaps.

**Comment by mindplay-dk** [comment]
Gotcha.

Okay, then - starting in an empty folder, with a simple `composer.json`:

```json
{
	"require": {
		"mindplay/kisstpl": "dev-master"
	}
}
```

Install it:

```
$ composer install -vv
Loading composer repositories with package information
Installing dependencies (including require-dev)
Analyzed 59 packages to resolve dependencies
Analyzed 54 rules to resolve dependencies
  - Installing mindplay/kisstpl (dev-master e0e3c1a)
    Cloning e0e3c1aebddcdb960fda7a5afe175ab8eea7a609

    REASON: Required by root: Install command rule (install mindplay/kisstpl dev-master)

Writing lock file
Generating autoload files
```

Resulting `composer.lock` looks like this:

```
{
    "_readme": [
        "This file locks the dependencies of your project to a known state",
        "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file",
        "This file is @generated automatically"
    ],
    "hash": "443bf9e900dd0507f5d745381c9ed9b8",
    "packages": [
        {
            "name": "mindplay/kisstpl",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/mindplay-dk/kisstpl.git",
                "reference": "e0e3c1aebddcdb960fda7a5afe175ab8eea7a609"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/mindplay-dk/kisstpl/zipball/e0e3c1aebddcdb960fda7a5afe175ab8eea7a609",
                "reference": "e0e3c1aebddcdb960fda7a5afe175ab8eea7a609",
                "shasum": ""
            },
            "require": {
                "php": ">=5.3"
            },
            "require-dev": {
                "mindplay/benchpress": "@dev",
                "mindplay/testies": "dev-master",
                "phpunit/php-code-coverage": "2.*"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "mindplay\\kisstpl\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "LGPL-3.0+"
            ],
            "authors": [
                {
                    "name": "Rasmus Schultz",
                    "email": "rasmus@mindplay.dk"
                }
            ],
            "description": "View service / template engine for plain PHP templates",
            "time": "2015-09-03 14:03:17"
        }
    ],
    "packages-dev": [],
    "aliases": [],
    "minimum-stability": "stable",
    "stability-flags": {
        "mindplay/kisstpl": 20
    },
    "prefer-stable": false,
    "prefer-lowest": false,
    "platform": [],
    "platform-dev": []
}
```

Checking the contents of `vendor/mindplay/kisstpl/.gif/config`:

```
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
	hideDotFiles = dotGitOnly
[remote "origin"]
	url = git://github.com/mindplay-dk/kisstpl.git
	fetch = +refs/heads/*:refs/remotes/origin/*
	pushurl = git@github.com:mindplay-dk/kisstpl.git
[branch "master"]
	remote = origin
	merge = refs/heads/master
[remote "composer"]
	url = git://github.com/mindplay-dk/kisstpl.git
	fetch = +refs/heads/*:refs/remotes/composer/*
```

For `remote "origin"` the `pushurl` has been set to `git@github.com:mindplay-dk/kisstpl.git`.

Comparing with a local project from January, it appears to be configured the same way.

So this is not due to any change in Composer, as far as I can figure - it must be due to changes made in Git for Windows? As said, I'm a casual Git user - I have no idea what could have changed, or why it affects Composer in this way.

But if I clone the same project myself:

```
$ git clone https://github.com/mindplay-dk/kisstpl.git
Cloning into 'kisstpl'...
remote: Counting objects: 143, done.
Receiving objects:  85% (122/143)    3 (delta 3), pack-reused 139
Receiving objects: 100% (143/143), 32.68 KiB | 0 bytes/s, done.
Resolving deltas: 100% (85/85), done.
Checking connectivity... done.
```

And then check the contents of `.git/config`:

```
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
	hideDotFiles = dotGitOnly
[remote "origin"]
	url = https://github.com/mindplay-dk/kisstpl.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

There's no `pushurl` configured for `remote "origin"`, and I have no problems.

Why does Composer configure the `pushurl` differently from a standard `git clone`?

(and please don't take that question the wrong way - I'm not being facetious, I genuinely do not know.)

**Comment by alcohol** [comment]
But the push url should be irrelevant. Composer will never push code from `vendor/`. It's just automatically setup cause it is tracking the remote branch. The actual difference that could have an impact though is the `git` vs `https` protocol.

**Comment by mindplay-dk** [comment]
> Composer will never push code from `vendor/`

I know Composer won't - the problems occur when I manually push code from a vendor-folder.

I frequently have to work on a package that is installed in the vendor folder - like if I'm adding a new feature or refactoring something that affects my current project, I often work directly on the vendor package. That's when I have these issues.

(we work in a modular environment - often one project has several related dependencies, like, say, a user API package, and a user management package; two different packages, but development goes hand-in-hand, at least until we're past prototyping and such...)

**Comment by Seldaek** [comment]
We chose that push URL because it's the most likely to work well, https is kinda unusable if you have 2-factor-auth on github I believe, and in any case ssh key auth is just easier to setup IMO granted that you have an ssh key anyway to access servers etc. It's indeed nothing new.

I think the possible solutions are:

- set up an ssh key so you can use git@ URLs (I work on windows too so that's definitely possible), see https://help.github.com/articles/generating-an-ssh-key/
- run `git remote set-url origin https://lalala --push` to override the push URL, composer shouldn't mess it up on further updates, as it only does that on the initial package install. It's a bit annoying but if it's just that one vendor you need adjusted it might be the easier way to go.

**Comment by cs278** [comment]
Another option is to use `pushInsteadOf` to change the push URL, something like the following in `~/.gitconfig`:

```
[https://github.com/]
pushInsteadOf = git@github.com:
```

**Comment by Seldaek** [comment]
Oh that's pretty cool, thanks.
