### ISSUE TITLE
HG Driver bug in pull/update : update forgotten?

### ISSUE THREAD

**Issue by bninassi** [composer/composer#4464]
Hi, 

It seems that the HG Driver ( composer/src/Composer/Repository/Vcs/HgDriver.php ) is missing the "update" command : with mercurial, "hg pull" is insufficient (unlike git), you need also to do an "hg update" to update the local repository with the latest code previously pull with "hg pull".

It may only be missing something like this line 54 :                 
if (0 !== $this->process->execute('hg update', $output, $this->repoDir)) {
  $this->io->writeError('<error>Failed to update '.$this->url.', package information from this repository may be outdated ('.$this->process->getErrorOutput().')</error>');
}

Best regards,

**Comment by alcohol** [comment]
I honestly don't know anyone using mercurial, so I will have to take your word for it. I'm surprised nobody has ever reported this before though. What made you realise/aware of this? Like, can you describe a scenario of steps to reproduce this and what the expected outcome and actual outcome were?

**Comment by bninassi** [comment]
We use a private mercurial repository to store our symfony2 bundles, and we just started using composer to deploy them.

Deployment is fine (ie automatic hg clone via composer in vendors directory), but when we modify our bundles on our repository and then run a "php composer.phar update" on our servers, nothing happen (the bundles aren't updated).

The only solution we have is to manually delete the "vendors/ourbundles" directories, and then run a "php composer.phar install", wich make a "hg clone" so the latest version of our bundles are deployed.

I found some posts on stackoverflow from people having the issue.
You can also correct this by simply change line 52 : 'hg pull' by 'hg pull --update' like mercurial documentation explain.

**Comment by alcohol** [comment]
Have you tried running composer in -vvv mode to see what is happening in the background and potentially debug whatever the issue might be? Unfortunately, with very little information at hand right now, there is not much else I can offer or suggest to you.

**Comment by alcohol** [comment]
Can you compile a composer.phar from my PR and see if it actually solves your use-case?

**Comment by alcohol** [comment]
@bninassi any update on the above patch?

**Comment by bninassi** [comment]
Sorry, 
I managed to find out that we wasn't using composer correctly. We where using repositories of type "packages" instead of "hg" (or "vcs") and that's why the update wasn't working.

I don't know why, but it seem's that this PR isn't needed (can't understand why the command hg pull here update even without the --update option, though), but it's also working (tried with and without this PR, same result).

I have some issues with mercurial authentication though (using the syntaxe https://username:password@repourl ) but that's another story :-)

Thanks for your time, and sorry again !
