### ISSUE TITLE
post-package-install/update script events don't use PackageEvent

### ISSUE THREAD

**Issue by neonics** [composer/composer#4465]
Hello! 

When specifying `post-package-install` and/or `post-package-update` scripts in `package.json`,
these scripts get executed, but the `Event` parameter is not a `PackageEvent` but a `Composer\Script\Event`, which lacks package information. This used to work, and is [documented here](https://getcomposer.org/doc/articles/scripts.md).

Here's an excerpt from `package.json`:

    "scripts": {
            "post-package-install": "MyComposerTool::localize_package",
            "post-package-update" : "MyComposerTool::localize_package"
    },

and here's the `MyComposerTool.php`:

    use Composer\Script\Event;
    class MyComposerTool {
        public static function localize_package( Event $event ) {
            echo "Event: " . get_class( $event ) . " " . $event->getName() . "\n";
       }
    }

which outputs:

    Event: Composer\Script\Event post-package-install

I used to be able to retrieve the package using this:

      $op = $event->getOperation();
      switch ( $op->getJobType() )
      {
        case 'install': return $op->getPackage();
        case 'update' : return $op->getTargetPackage();
        default: ....
      }

Is this broken, or is there another way to get the current package being installed/updated/uninstalled using scripted events that I am not aware of?

Thanks!

Btw: Composer version 1.0-dev (c41079192f38f0fc446b17baa8f628dcb3b61e7d) 2015-09-28 09:38:16

**Comment by stof** [comment]
this is because of your typehint. Given that event classes have changed several times in Composer, the event dispatcher has some logic to convert the event to other classes to keep BC.

Update your typehint to ``Composer\Installer\PackageEvent`` (or ``Composer\EventDispatcher\Event`` for the base event class)

**Comment by neonics** [comment]
@stof: thanks! I just figured that out by tracing the Composer call stack and was about to close the issue :-)
