### ISSUE TITLE
Package name same as dependency

### ISSUE THREAD

**Issue by greeny** [composer/composer#4468]
I recently created new package and copied composer.json file from another project. Unfortunately, i forgot to rename it in `name` filed. One of new dependencies I added there was the package from which i copied composer.json.

I run `composer update` and got some weird behavior there. I think it would be good to throw some exception when you require the package in which you currently are. (since I cannot think about any case where this could be useful and it can also lead to some recursion)

**Comment by alcohol** [comment]
No thanks. Composer does not have to be fool-proof. I think it's fair to expect some modicum of common sense and intelligence from our users.

**Comment by stof** [comment]
a direct self-dependency indeed does not make sense. This is something which could be added in ``composer validate``.

note however that circular dependencies are a supported use case in Composer.

**Comment by greeny** [comment]
Its not about fool-prof composer, its about the behavior. I got "unresolveable set of packages" error, but all packages listed there were actually resolvable and in any other project it will work correctly.

(The problem is that in composer.json, there is e.g. vendor/package@1.0.0 and because in name is vendor/package and no tag exists, composer gets confused about not having && having 1.0.0 version. Its hard for me to describe this, since I am not native english speaker, but I hope you understand me.)

**Comment by alcohol** [comment]
I'm sorry, but no, I don't quite understand. Can you share the composer.json that was causing issues?

**Comment by greeny** [comment]
I will try to explain on 2 fictive packages: greeny/packageA and greeny/packageB:

****

packageA composer.json (this is correct, valid and working composer.json && package):

```json
{
    "name":"greeny/packageA",
    "require": {
        "someValid/dependency": "1.0.0",
        ...
    }
}
```

packageA also has stable tag `1.0.0` at git.

****

packageB composer.json (this is the invalid composer.json because of name):

```json
{
    "name":"greeny/packageA",
    "require": {
        "greeny/packageA": "1.0.0",
        ...
    }
}
```

packageB has only dev-master on git (and because of that, its not stable, but dev only).

****

Now for the problem, when I run `composer update/install` on packageB, it ends up with unresolveable set of dependencies.

I think composer is somehow confused because packageB (but named as packageA) does not have version 1.0.0, but packageA (also named as packageA) has stable version 1.0.0.

I hope everything is clear now

**Comment by greeny** [comment]
Also as @stof mentioned earlier, at least `composer validate` should care about direct self-dependency.

**Comment by alcohol** [comment]
Composer validate is mostly about the schema though. Adding "checks" for silly human-errors will just pollute the code-base over time. People are very creative when it comes to finding ways to break even the simplest applications. We can't account for all of these scenarios. It detracts from focusing on real issues.

**Comment by greeny** [comment]
Okay then. I got your point, thanks for your time. Closing issue.

**Comment by stof** [comment]
@alcohol no. ``composer validate`` checks much more things than the schema (for instance, unbound constraints are triggering a warning)

**Comment by alcohol** [comment]
That is still more about validity and less about human error though. It's to prevent bad practice. But adding checks for every single mistake a user could make, is just going to end up being a tedious and mostly pointless process.
