### ISSUE TITLE
Wrong permission after extracting zip

### ISSUE THREAD

**Issue by thommyhh** [composer/composer#4471]
**OS:** Debian 7 "Wheezy"
**Software:** No "unzip" binary installed
**Composer version:** 1.0-dev (d831c86bcb385d51307e56e4b8667d267e781165) 2015-08-19 23:44:57
**Problem:** In our package we have a dependency that is downloaded as zip from GitHub. After composer extracted the zip from its cache there were some permission missing, in this case the "+x". After trying some different systems and conditions, we found out, that this only happens, when there is no "unzip" binary installed, that can be used for extraction. I assume, composer uses some internal mechanism to extract the zip archive but fails to preserve the permissions set in the zip.

**Comment by alcohol** [comment]
If `unzip` is not available it will attempt to use `http://php.net/manual/en/ziparchive.extractto.php`. I see no mention of permissions there however, and whether or not it honors them.

**Comment by alcohol** [comment]
> The Info-ZIP implementations of the .ZIP format adds support for Unix filesystem features, such as user and group IDs, file permissions, and support for symbolic links. The Apache Ant implementation is aware of these to the extent that it can create files with predefined Unix permissions. The Info-ZIP implementations also know how to use the error correction capabilities built into the .ZIP compression format. Some programs (such as IZArc) do not, and will fail on a file that has errors.

Source: https://en.wikipedia.org/wiki/Zip_(file_format)

---

It would seem that `zip` archives by default do not support permissions very well, and it is likely that PHP's `ZipArchive` does not include this information. I suggest installing `unzip`.

**Comment by thommyhh** [comment]
Ok, thank you for this information, we installed "unzip", but we thought that this is bug in composer, what obviously it is not. It's more a missing feature in the PHP ZipArchive library.

I think the issue can be closed then.
