### ISSUE TITLE
Feature Request - Change how the repository is fetched based on status

### ISSUE THREAD

**Issue by alexbowers** [composer/composer#4473]
Similar to require-dev and require, however, it will allow the same repository to be referenced in both, but for dev to be fetched from a different location.

The use case for this is to allow during development the ability to use a path to reference a project, but when live, to allow it to be fetched by version (as per current workings), from github, bitbucket etc.

**Comment by alcohol** [comment]
So why don't you add the path repository to your global config.json (`~/.composer/config.json`) ?

**Comment by alexbowers** [comment]
Ah did not know about this. Does global act as an override for local, or
does local override global?

**Comment by alcohol** [comment]
I don't know, I never use it to be honest.

**Comment by Seldaek** [comment]
local repositories precede the global ones, but global will still precede packagist.
