### ISSUE TITLE
[Feature Request]Have determineRequirements take the current php version into account

### ISSUE THREAD

**Issue by greg0ire** [composer/composer#4474]
Currently, it appears that if you require `phpunit/phpunit` on a machine with php 5.3, [an incompatible version of phpunit is installed](https://travis-ci.org/sonata-project/SonataAdminBundle/jobs/83453730#L130). It would be great if composer could automatically add the detected php platform and version to the requirement when trying to find the best candidate.

**Comment by alcohol** [comment]
The problem I see with this though is that we don't really want to make `require` depend on the environment context. Too often it is used on an environment that is not equal to the production or release environment. Hence, it makes more sense to depend on people making smart choices about what they want to require and install. If you do not provide a version, you will simply end up with the latest release (that does not conflict with other required packages). The current platform is not taken into account.

**Comment by alcohol** [comment]
So I personally don't see any added value here. But if someone is willing to pitch it, we might consider including it.

**Comment by alcohol** [comment]
Also, another quick way around this is to actually provide a version (in the form of '@stable'), then it will simply resolve to the latest stable release that your platform supports when you run update.

```
composer require phpunit/phpunit:@stable --no-update
composer update
```

**Comment by greg0ire** [comment]
Very interesting, thanks! It is indeed for a build process and it looks like it is going to be used (see referencing PR)

**Comment by Soullivaneuh** [comment]
Indeed, works like a charm, thanks! :+1:

**Comment by Seldaek** [comment]
That's something I'd like to do anyway, because as more packages require higher php versions this will become a problem. IMO it should check the config.platform.php or fallback on current php version. Just like the solver would.

**Comment by alcohol** [comment]
Isn't this covered by 507415e now?

**Comment by greg0ire** [comment]
@Soullivaneuh : not sure if you can retry the build, or if we always use the very last version of Composer, but if you can, and we do, and the build passes, it should answer @alcohol 's question

**Comment by Seldaek** [comment]
Yes I think it is, I also just fixed it for the create-project cmd. Just comment/reopen in case it isn't, but I'm assuming it is and closing.
