### ISSUE TITLE
make archive command to create offline package(artifact)

### ISSUE THREAD

**Issue by minkbear** [composer/composer#4476]
I have face the offline situation (https://github.com/composer/composer/issues/3373#issuecomment-145323469) 
for example my production server is not allow to connect to internet.
I do not know how to solve this. 

One solution that I think is use composer archive to create any offline package that my application need into artifact format (https://getcomposer.org/doc/05-repositories.md#artifact)

For more clear, the workflow should be:
1. use this command in environment that having internet ex. dev machine
```
composer archive vendor/package 1.0.0 --format=zip --dir=path/ --artifact 
```
The result: vendor-package-1.0.0.zip will be create in path/
more info: --artifact should be add version:"1.0.0" in vendor/package/composer.json as well (changed in local file before zip)
2. manually copy vendor-package-1.0.0.zip to artifact path(https://getcomposer.org/doc/05-repositories.md#artifact) in non internet environment ex. production server
3. run
```
composer update
```
composer will update package as mention in https://getcomposer.org/doc/05-repositories.md#artifact

This is my proposal. What do you think? if there is any solution please advice.

Thanks.

**Comment by alcohol** [comment]
You should not be using and/or running Composer on production anyway. It is not a deployment tool. It would be much better to just create production ready release packages using tar/gzip or your operating system packaging solution (rpm/deb/etc) of your entire application.

**Comment by minkbear** [comment]
@alcohol yes you're right. thanks
