### ISSUE TITLE
Call to undefined method parseLinks()

### ISSUE THREAD

**Issue by yaman-jain** [composer/composer#4481]
Updating to version fcce52b169799fc5973d080d31c27532ca41b7b8 from 15face5432d7b7334db6ac69fac0190971cafa6e
gives fatal error : Call to undefined method Fxp\Composer\AssetPlugin\Package\Version\VersionParser::parseLinks()

**Comment by alcohol** [comment]
This method was dropped in `composer/semver` since it has already been marked as deprecated for quite a while.

Use [this method](/composer/composer/blob/1328d9c3b2fbe2d71079c5009b2d5204ce956c2e/src/Composer/Package/Loader/ArrayLoader.php#L227) instead.

**Comment by stof** [comment]
Well, you should open the issue on the AssetPlugin repository according to the namespace appearing in the error

**Comment by alcohol** [comment]
I'm pretty sure that was already fixed in the AssetPlugin a while ago. You are probably running an out-of-date version.

**Comment by yaman-jain** [comment]
Thanks guys. Fixed it.
