### ISSUE TITLE
Composer does not check if commit still exists

### ISSUE THREAD

**Issue by fre5h** [composer/composer#4483]
Some time ago Zend moved their packages to another place. I had next piece of JSON in my composer.lock

```json
"name": "zendframework/zend-version",
"version": "2.0.8",
"target-dir": "Zend/Version",
"source": {
    "type": "git",
    "url": "https://github.com/zendframework/Component_ZendVersion.git",
    "reference": "6f53b05c81bdd1a8ede01d4381c0b64efe33851c"
},
"dist": {
    "type": "zip",
    "url": "https://api.github.com/repos/zendframework/Component_ZendVersion/zipball/6f53b05c81bdd1a8ede01d4381c0b64efe33851c",
    "reference": "6f53b05c81bdd1a8ede01d4381c0b64efe33851c",
    "shasum": ""
},
```

So I executed `composer update zendframework/zend-version --with-dependencies` and this piece of JSON changed to

```json
"name": "zendframework/zend-version",
"version": "2.0.8",
"target-dir": "Zend/Version",
"source": {
    "type": "git",
    "url": "https://github.com/zendframework/zend-version.git",
    "reference": "6f53b05c81bdd1a8ede01d4381c0b64efe33851c"
},
"dist": {
    "type": "zip",
    "url": "https://api.github.com/repos/zendframework/zend-version/zipball/751b20d0737831b1c300de238278f9233b2eff23",
    "reference": "6f53b05c81bdd1a8ede01d4381c0b64efe33851c",
    "shasum": ""
},
```

Lines which were changed:
from
```json
"url": "https://github.com/zendframework/Component_ZendVersion.git",
```
to
```json
"url": "https://github.com/zendframework/zend-version.git",
```

and from
```json
"url": "https://api.github.com/repos/zendframework/Component_ZendVersion/zipball/6f53b05c81bdd1a8ede01d4381c0b64efe33851c",
```
to
```json 
"url": "https://api.github.com/repos/zendframework/zend-version/zipball/751b20d0737831b1c300de238278f9233b2eff23",
```

Repository moved to another URL but it is still exists on packagist, URL was updated to actual, so no problem here. After that I noticed that `dist.url` hash of commit `751b20d0737831b1c300de238278f9233b2eff23` does not match the `dist.reference` = `6f53b05c81bdd1a8ede01d4381c0b64efe33851c`. As I found in issue #4442 it also means OK and (I hope) will be fixed soon.
But another thing happened here. When I tried on deploy my project on staging during the composer install I get next error
```
- Installing zendframework/zend-version (2.0.8)
   Cloning 6f53b05c81bdd1a8ede01d4381c0b64efe33851c
   6f53b05c81bdd1a8ede01d4381c0b64efe33851c is gone (history was rewritten?)
```

I don't know what happened with this commit. Maybe it was rebased or removed. It happens rarely but can happen as you see.

**According to this case would be nice to have an option for composer to check if all commits (hashes) from composer.lock still exists. What do you think?**

**Comment by alcohol** [comment]
That is weird though. Cause 2.0.8 is actually `751b20d0737831b1c300de238278f9233b2eff23`. So I wonder where you got `6f53b05c81bdd1a8ede01d4381c0b64efe33851c` from.

**Comment by stof** [comment]
@alcohol probably from their lock file.

When moving Zend Framework away from the monolith repository, they rewrote the history entirely in component repos (because they were not doing proper subtree splits before that for their component repos), which means they probably broke all lock files depending on ZF components out there because they have not kept a legacy branch making the old commits available for people cloning the repo.
/cc @weierophinney

**Comment by fre5h** [comment]
My composer.lock wasn't updated for years. In composer.json there is
```json
"zendframework/zend-feed": "2.0.*",
```
(zend-feed has zend-version as dependency)
So after some composer update in the past this package was locked to commit 6f53b05c81bdd1a8ede01d4381c0b64efe33851c. But at some point in the past something happened with this commit (squashed, removed, updated). And today the last commit for "2.0.*" is `751b20d0737831b1c300de238278f9233b2eff23`

But when I executed `composer update zendframework/zend-feed` yesterday, Composer updated only the dist.url, but didn't check if commit still exists. And I get the error during the deploy on staging, because there we haven't cache for Composer and Composer tried to download package by the commit `6f53b05c81bdd1a8ede01d4381c0b64efe33851c`.

So the idea is to have an option for Composer to check all locked commits from composer.lock if they still exist, something like `composer validate --check-existence-of-locked-commits`. What do you think? Does it make some sense? Or it is very rare case and doesn't need to pay attention to it?

**Comment by alcohol** [comment]
I'm more curious why the url got updated but the dist ref did not. It's the dist ref that is important, not the url. Is your Composer version up to date?

**Comment by stof** [comment]
@alcohol Composer is able to update Github URLs to account for repo renamings. But the implementation is currently flawed: as it relies on the fact that the downloader will automatically update the github download URL based on the reference (making the downloader compatible with the ``dev-master#<commit>`` installer hack for github repos), it does not bother doing the same replacement before changing the URL in the lock file, leading to a ref mismatch there (and unecessary diffs each time you do a partial update of a package using dev versions btw)

**Comment by fre5h** [comment]
@alcohol After I got this error I updated Composer and get the same

**Comment by weierophinney** [comment]
All component repos have a "legacy" branch at this time, with the contents
and commits from the original repos; we did this within days of the switch,
after reports from users. Tests at the time indicated the solution worked.
I'm not sure what else we can do from our end.

**Comment by alcohol** [comment]
@fre5h to answer your question though, regarding implementing a "existing commit" check. No, I don't see any reason to do so. Any proper testing/CI environment should be able to catch this before your product hits your production environment. Irregardless, Composer cannot fix this for you. If a commit is gone, it is gone. It cannot decide for you what to replace it with or what to do next. So human interaction is required anyway.

**Comment by fre5h** [comment]
@alcohol thank you for your answer. I think this issue can be closed

**Comment by stof** [comment]
@weierophinney it seems that the commit of the non-rewritten 2.0.8 tag of the zend-version component is not reachable through the legacy branch though
