### ISSUE TITLE
composer_autoload.php can require files that do not exists.

### ISSUE THREAD

**Issue by daiglej** [composer/composer#4484]
If in composer.json of you requirement contains like this 
"autoload": {
"file":["src/somefile.php"]
}

In the HEAD of it's repository, but you have required a commit hash that is older than the HEAD (One that does not yet contain the file). The file will still be part of the composer_autoload.php.

then when in your code when you will "require vendor/autoload.php".

You will get a fatal error :  

Fatal error: require(): Failed opening required '.../vendor/cloudinary/cloudinary_php/src/Helpers.php' in .../vendor/composer/autoload_real.php on line 59

Note : you can reproduce this issue by doing : 
./composer.phar require cloudinary/cloudinary_php  dev-master#62c4da6

**Comment by stof** [comment]
The ``dev:master#...`` syntax is an installer-level hack. Metadata downloaded from Packagist are not available for each commits (this would be insane, and would require running Composer with 1TB RAM to resolve dependencies). This is why the metadata contain the new autoload requirements.

My recommendation is to never use this syntax. If you want to use older versions, you should rely on tags instead.

**Comment by alcohol** [comment]
It is known that using a #ref in your version constraint comes with various caveats. You simply have to learn to live with those. There is no intention on "fixing" any of this. Using a #ref in your version constraint is very bad practice and should be avoided at all times.

**Comment by stof** [comment]
@alcohol I suggest adding a warning for this in ``composer validate`` (we already warn for unbound constraints). what do you think ?

**Comment by alcohol** [comment]
That is definitely a good idea :-)

**Comment by alcohol** [comment]
@stof #4485 if you don't pick it up I will, this weekend probably :-)
