### ISSUE TITLE
Add warning to `validate` if a version constraint contains a commit reference

### ISSUE THREAD

**Issue by alcohol** [composer/composer#4485]

**Comment by legoktm** [comment]
Why?

**Comment by alcohol** [comment]
Because this is bad practice, just like using unbound version constraints, for which we also issue a warning.

**Comment by legoktm** [comment]
To clarify, is this about using a requirement like `dev-master#[git sha1]`?

Given that that pins the version to a specific sha1, which provides a lot more [data integrity](https://en.wikipedia.org/wiki/SHA-1#Data_integrity) than a mutable tag, why is it discouraged?

**Comment by alcohol** [comment]
Yes, it's about that behaviour.

Because of reasons: #4484 #4082 #3918 
See also the big blue note at the end of this section: https://getcomposer.org/doc/04-schema.md#package-links

In short, you should never use it. It's a dirty hack that does not work as people expect it to work.
