### ISSUE TITLE
Installing plugin from "path" but assign "type" to it.

### ISSUE THREAD

**Issue by jeremyzahner** [composer/composer#4486]
Hi there! I have a quite complex request:

For a project i use a MVC Wordpres Plugin Framework (https://github.com/getherbert/herbert) with wich i am having the following situation:

Project is "live" on a staging server, including the plugin.
Plugin is still under development but locally linked as a symlink
Deployment happens via Capistrano
My Problem: I need to add the plugin and its repo in the main projects composer.json so it gets deployed right onto the staging server. On the other hand i dont want composer to overwrite my local symlink every time i run composer update.

I managed to install the plugin locally by just adding a "path" repo. But now i got two more issues:

1. I don't want the "Path" repo to be active on the remote server.
2. If i use "Path", i can not set the type, wich should be "wordpress-plugin" so it gets installed into the right directory.

Is there a easy way for this? I assume that im not the first person having this issue.

Thanks for you best practices!

```
  "repositories": [
    {
      "type": "path",
      "url": "/Users/me/Workflow/misc/plugin"
    }
  ],
  "require": {
    "php": ">=5.4",
    "composer/installers": "~1.0.12",
    "vlucas/phpdotenv": "^2.0.1",
    "johnpbloch/wordpress": "4.3.1",
    "jshmrtn/plugin": "dev-master"
  },
  "extra": {
    "installer-paths": {
      "web/app/mu-plugins/{$name}/": ["type:wordpress-muplugin"],
      "web/app/plugins/{$name}/": ["type:wordpress-plugin"],
      "web/app/themes/{$name}/": ["type:wordpress-theme"]
    },
    "wordpress-install-dir": "web/wp"
  }
```

**Comment by alcohol** [comment]
Looking at the issue list, you are the first. Or the first that has asked this question. It's not really a Composer problem though, it's a workflow problem.

**Comment by jeremyzahner** [comment]
@alcohol Im well aware that this is not a composer "problem".

Actually i think monolithic architecture is a thing. And i'm not the only one.

Also in the documentation there is this sentence:

> This can be especially useful when dealing with monolith repositories.

Thats what im trying to do basically. Im just trying to figure out in what ways this could be improved.

**Comment by alcohol** [comment]
The problem is that you want to change your flow depending on the environment, which is not very practical.

**Comment by jeremyzahner** [comment]
@alcohol Correct me if im wrong:

- If on the remote server composer can not find the provided path, then it should fall back to the next repo?

For the local installation i would actually just need to assign the package inside the "path" a "type".

**Comment by alcohol** [comment]
I'm confused btw. Type here relates to repository, not the package. A repository cannot be of type plugin.

What you can do is use the following on your development machine:

```
git config -g repositories.<somename> path /path/to/repo
```


And the following on your other environment(s):

```
git config -g repositories.<somename> vcs url/to/repo
```

But if you commit your lock file, I honestly have no idea what this might lead to.

**Comment by jeremyzahner** [comment]
About the type thing; in the same project i use the following:

```
"repositories": [
    {
      "type": "package",
      "package": {
        "name": "advanced-custom-fields/advanced-custom-fields-pro",
        "version": "5.3.0",
        "type": "wordpress-plugin",
        "dist": {
          "type": "zip",
          "url": "http://connect.advancedcustomfields.com/index.php?p=pro&a=download&k=KEY"
        }
      }
    }
```

So if i could declare a package sitting at a specific path the same way im declaring the package here than that would solve at least one problem.

i.e. like:

"repositories": [
    {
      "type": "package",
      "package": {
        "name": "jshmrtn/plugin",
        "version": "dev-master",
        "type": "wordpress-plugin",
        "dist": {
          "type": "path",
          "url": "/Users/me/Workflow/misc/plugin"
        }
      }
    }
```

**Comment by alcohol** [comment]
You're doing it all wrong. You are declaring type on the wrong level.

Also, you should only use the type `package` for a repository if the target has no `composer.json`.

**Comment by jeremyzahner** [comment]
Of course i know it isn't the right way to achieve what im trying to do.
Thats why i opened this issue.

So you are basically telling me that composer isn't meant to achieve this?
I can live with that! But then i would need to use something like https://github.com/mybuilder/conductor.

Tough i would like to stay with composer as is.

**Comment by alcohol** [comment]
I don't think you understand what I am saying. But by all means, use conductor.

**Comment by jeremyzahner** [comment]
No offense! I didn't mean to be demanding. =)

I enjoy composer really much as it is!
I was just trying to point out the "problem" they are trying to address.

Could you suggest something to what im trying to do while being composer compilant?

**Comment by jeremyzahner** [comment]
Okay.

Now i actually got that type thing: Declare it in the child projects composer.json right?

Silly me

**Comment by alcohol** [comment]
Yes. When you use a repository of type package, you have to provide all the normal composer.json values inside of the definition of this repository, because it will not read your composer.json even if you have one (package repository assumes you do not have one). If you use a repository of type vcs or path, it will simply read the package definition from the composer.json inside of it.

**Comment by jeremyzahner** [comment]
So. I managed to get to a point where i think i get it.

So i got one more question for this issue then we might close it (tough i got hit by bug https://github.com/composer/composer/issues/4451, but i will report that there).

Can you confirm, that since path is a repo declaration like vcs, if i.e. my remote servers composer isn't able to find the package (or any kind of file) at the path then it will just go on looking after it in the next occurring repo?

Anyway. You can close this issue after that, because that would probably solve all my "problems".

Thanks for your time anyway!

**Comment by alcohol** [comment]
I don't know about that because I don't use repositories in such a way. I imagine you'd sooner get an answer by just applying TIAS, rather than waiting for a reply from me (or someone else) :-)

**Comment by jeremyzahner** [comment]
So i just found out it isn't working that way. It just fails on the Server if it isn't able to find the path. 
Just so you know. So i guess im going to handle it as a git submodule. Probably the safest way for now.
So thank you for the support anyway!
