### ISSUE TITLE
New class for "depends" calculation

### ISSUE THREAD

**Issue by Soullivaneuh** [composer/composer#4487]
The goal is to extract this logic: https://github.com/composer/composer/blob/7a9eb02190d334513e99a479510f87eed18cf958/src/Composer/Command/DependsCommand.php#L85-L96

Onto an another class, to calculate which packages require this one.

Could be useful for my issue I think. :-)

https://github.com/Soullivaneuh/composer-versions-check/issues/13

**Comment by Soullivaneuh** [comment]
Ok maybe a `PackageInterface::getDepends()` method. But the packages build system should be review if I'm right.

**Comment by alcohol** [comment]
A lot of the `Command` classes need to be refactored so that logic can be moved to logical classes. It's on my to-do list, or anyone else that feels like they want to pitch in.

**Comment by Soullivaneuh** [comment]
I could maybe take a look @alcohol. Could you tell me if `PackageInterface::getDepends()` methods is a good idea?

**Comment by stof** [comment]
@Soullivaneuh no it is not: a package cannot know which package depend on it. Knowing it requires to process all packages of all repositories (which is highly inefficient btw, if you do this on all repositories instead of the repository of installed packages only, as you would have to load the whole Packagist data)

**Comment by Soullivaneuh** [comment]
@stof What is your proposition so? A hole new class?

**Comment by alcohol** [comment]
Regarding where to move it to; I do not know to be honest, I would have to invest some time.

**Comment by stof** [comment]
@Soullivaneuh yes, it would have to be a dedicated class containing the logic to query this info from the repository it receives.

Btw, you cannot run this logic on the whole Packagist metadata. Composer will throw an exception in ``getPackages`` when using a composer repository using the features avoiding to load all the repository at once.

**Comment by Seldaek** [comment]
Closing as it's not extremely urgent and it might just happen if we extract logic from commands some day.

**Comment by Soullivaneuh** [comment]
@Seldaek Even if this is not yet on your roadmap, why not leaving this open for future implement?

Would you accept some PR for that?

Thanks.

**Comment by Seldaek** [comment]
If you send a reasonable PR yes I guess why not
