### ISSUE TITLE
Get extra options for plugin

### ISSUE THREAD

**Issue by Soullivaneuh** [composer/composer#4494]
Is there a way to get options from the `extra` key like we do for composer scripts but for plugins?

If yes, how? I have to admit I am a bit lost for this.

Concrete need: https://github.com/Soullivaneuh/composer-versions-check/issues/13#issuecomment-147082251

Thanks.

**Comment by alcohol** [comment]
`$extra = $this->composer->getPackage()->getExtra();` ?

**Comment by Soullivaneuh** [comment]
Oh, I was looking on `getConfig()`.

Will check that.

**Comment by Soullivaneuh** [comment]
Ok this will give me the extra config of the root package.

But what if I want to get extra from `$HOME/.composer/composer.json` file?

**Comment by alcohol** [comment]
The global composer config? Uh... I don't think you should ever put "extra" in there.

**Comment by Soullivaneuh** [comment]
@alcohol Well, check my link on my first command. You will see that having a global config make more sense for this plugin.

What is your suggestion?

**Comment by alcohol** [comment]
No, it doesn't.

Global composer.json is only for global packages. It has nothing to do with your local package (your project/root package). You cannot treat local as an extension of global. It does not work like that. It's nothing like npm or the sorts. This is why I personally feel like the whole "global" thing should just be deprecated and removed. It serves no real purpose and just confuses a lot of people.

**Comment by Soullivaneuh** [comment]
The plugin **is** globally installed. It's a tools to check outdated packages.

> I personally feel like the whole "global" thing should just be deprecated and removed.

I hope not, I use global require for dev tools and composer plugins. This would be painful to require it on each projects...

But this is another debate. I ensure you my plugin aims to be installed globally and so have a global config. Nothing possible this way?

**Comment by alcohol** [comment]
The plugin manager does get an instance of a "global" Composer (thats how global plugins can be loaded). However, it never passes it to the interface method `active()`. This only receives the local Composer instance. Hence you cannot get the "global" local package, and thus you cannot retrieve the "extra" values.

**Comment by alcohol** [comment]
> I hope not, I use global require for dev tools and composer plugins. This would be painful to require it on each projects...

I certainly do not want to remove plugin capabilities. But there are many ways to globally install dev tools and such. I just find the entire *global* concept in its current state very misleading. People often get the wrong impression/idea (because of the name, perhaps).

**Comment by Soullivaneuh** [comment]
> But there are many ways to globally install dev tools and such.

I know, and global requirement is the best I found for the moment. So yes, I hope it will be kept.

**Comment by Soullivaneuh** [comment]
So if I understand, there is no way for global config though composer?

If I want mine, I'll have to manage it externally.

**Comment by alcohol** [comment]
Not currently, no. It would be a very small change. However, I don't think it would be backwards compatible, and that is an issue.

Have a look here:
* https://github.com/composer/composer/blob/master/src/Composer/Plugin/PluginManager.php#L56
* https://github.com/composer/composer/blob/master/src/Composer/Plugin/PluginManager.php#L86

As you can see, passing the `$globalComposer` along would solve your issue. However, there are two issues here:

1. In most cases `$globalComposer` will be `null`, and thus pointless to pass it on.
2. Adding it as an extra argument to `activate()` is not BC (unless we leave the interface unchanged and simply pass it as a third argument, which would be ignored by methods only accepting 2 arguments).

There are other options of course, but I am not sure what the desired approach would be.

/cc @seldaek feedback?
/cc @nevvermind @slbmeh you two were discussing/working a lot on refactoring plugin stuff, care to weigh in here?

**Comment by Seldaek** [comment]
Another option that might be a bit more BC is add a getGlobalComposer to the Composer instance, so you can call it on the one you get, but it might be null of course. Not sure if it would simplify or complexify the rest of the code dealing with this.

**Comment by Seldaek** [comment]
That said, adding it to `activate()` would be best, but to keep it clean we would need to break BC, so it can only be done in the 2.0 plugin API. Until then I would say the best is to just load the json file at `$composer->getConfig()->get('home') . '/composer.json'` and read the extra key from there. It's just a couple lines of code in your plugin, not too bad.

**Comment by Soullivaneuh** [comment]
Thanks a lot for the tips @Seldaek, I'll check that soon. :+1:

**Comment by Seldaek** [comment]
Closing, we have `PluginManager::getGlobalComposer()` now
