### ISSUE TITLE
Intro assertion about global

### ISSUE THREAD

**Issue by EmanueleMinotto** [composer/composer#4495]
> By default it will never install anything globally.

Is this assertion still valid considering the `composer global`?

Ref: https://github.com/composer/composer/blob/master/doc/00-intro.md#dependency-management

**Comment by alcohol** [comment]
Global is not default. Not does a `composer global install` do the same thing as an npm global install for example. You cannot include global libraries into your local project just like that. Global serves a different purpose for Composer.

**Comment by EmanueleMinotto** [comment]
Probably I didn't explain well what I mean, sorry.

I don't mean that composer installs system-wide commands nor that the default behaviour is to install the dependencies globally (like PEAR does), I mean that it *could* download dependencies globally, and *could != never*.

Maybe it's just pedantry ^^' but starting from that info, newcomers looking for system-wide solutions could switch to PEAR-like solutions without going ahead with the composer documentation, imo.

**Comment by alcohol** [comment]
There is a lot of phrasing in the documentation that could be considered ambiguous or not misleading. Unfortunately, nobody has the time to really go through it all and rewrite it.
