### ISSUE TITLE
Check for dependencies status

### ISSUE THREAD

**Issue by XedinUnknown** [composer/composer#4497]
Hi,

I need to find out if the installed dependencies are up to date with the required ones. Unfortunately, there doesn't seem to be any way of doing that, except running `composer update`. Of course, this would update dependencies, while all I want to do is *check* if they are up to date, e.g. to determine *whether* `composer update` needs to be run. I'm not familiar with the internals of Composer; however, something tells me that this is already being done internally. Am I missing something? Can this be done? If so, how?

Thanks!

**Comment by alcohol** [comment]
No, Composer does not do this cause there is no real need for it. There is a plugin that does what you are looking for though.

**Comment by XedinUnknown** [comment]
@alcohol, thanks for the reply. Would you be able to hint at the name of the plugin please?

**Comment by alcohol** [comment]
Try https://github.com/Soullivaneuh/composer-versions-check/

**Comment by XedinUnknown** [comment]
Thanks for the suggestion. Unfortunately, this is not what I need, because it compares installed package versions with most recent package versions. What I need is to be able to know whether the dependencies declared in `composer.json` are installed, and optionally whether the current version installed is up to date with what is declared in composer. I imagine that essentially this compares all packages in `composer.json` with all packages in `composer.lock`; a FULL OUTER join of sorts. Additionally, the solution you suggest shows analysis **after** update. In my case, I want to determine if an update is necessary. For example, I ran `install` and `update`, but one of the dependencies wasn't found. How can I, afterwards, at an arbitrary point in time, know that my project does not have the required dependencies?

**Comment by alcohol** [comment]
I'm sorry but you are not making much sense.

Have a composer.json but no vendor/ directory and no lock file? 
`> composer install`
Have a composer.json and composer.lock but no vendor/ directory?
`> composer install`
Have all of the above but want to check for (not install) newer versions? 
`> composer update --dry-run`
Have all of the above but want to check for (and install) newer versions? 
`> composer update`

**Comment by XedinUnknown** [comment]
> Why would you proceed to work on a project if it's in a broken state?
Exactly. I wouldn't. But how can I know?

**Comment by alcohol** [comment]
> But how can I know?

I think the error that Composer throws in your face whenever something goes wrong makes it quite obvious?

**Comment by XedinUnknown** [comment]
To find out if something is wrong, I have to attempt an install or update. I want to know if something is wrong before that.

I'm not sure what it is that is so complicated or ridiculous about my question. Would you be able to explain what (or if) can be done using my example?

## Recap ##

Let's say, I have this configuration in my new project:

```
{
    "name": "xedinunknown/test-deps",
    "description": "Testing whether or not my project state is as described in configuration",
    "require": {
        "monolog/monolog": "1.0.*"
    },
    "license": "MIT",
    "authors": [
        {
            "name": "Xedin Unknown",
            "email": "xedin.unknown@gmail.com"
        }
    ],
    "minimum-stability": "dev"
}
```

#### composer install ####
```
$ php composer.phar install --no-dev
Loading composer repositories with package information
Installing dependencies
  - Installing psr/log (dev-master 9e45edc)
    Cloning 9e45edca52cc9c954680072c93e621f8b71fab26

  - Installing monolog/monolog (1.0.2)
    Loading from cache

Writing lock file
Generating autoload files
```

Now, I want to require `xedinunknown/data` at version `1.0`, so I add it to my `composer.json`. This package is hosted in my corporate repository at xedinunknown.me. But I haven't added it to the `repositories` section of the config.

#### composer update ####
```
$ php composer.phar update --no-dev
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package xedinunknown/data could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

Now, I go work on other stuff. In the meantime, my colleague John comes to work on the project. He wants to know if the project has all the required dependencies, because he is getting `class not found` errors.

#### composer install ####
```
$ php composer.phar install --no-dev
Loading composer repositories with package information
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Nothing to install or update
Generating autoload files
```

Oh! He should run `composer update`, because the lockfile is out of date. But if he runs that, then 
the versions of the dependencies may change, and may break the software even more. And, even if he does that,  At this point, if John could run `composer diff` (or something) and get a response similar to below, this could instantly solve his issue:

```
$ php composer.phar diff
Your lockfile is out of date.

Package                     Config - Lockfile
monolog/monolog              1.0.2 - 1.0.2
xedinunknown/data              1.0 - [absent]
```

When John sees this, he immediately knows that the problem is that a required dependency is for some reason not installed. Then, he can revise the configuration file.

Further, let's say that instead of adding a proprietary package, I changed the version requirement of the `monolog/monolog` package. Then, John could get this useful information:

```
$ php composer.phar diff
Your lockfile is out of date.

Package                    Config - Lockfile
monolog/monolog             <1.15 - 1.0.2
```

Looking at the above output, John could know that the version of a particular package in the config file is not the same as what is installed, and it is safe for him to run `composer update`.

## Conclusion ##

As you can hopefully see, this could be very useful during development. To be honest, I just assumed that there is already a way to see if my project dependencies are up to date with the dependency specification, because... duh... it just makes sense. In fact, I thought that the `status` command does that before I read the docs for it.

Also, I see now that `composer update --dry-run` kinda does something similar. However, it is not really the same, since it will also list dependencies of dependencies that would be installed, and is meant to be entirely human-readable, from what I can see. Also, most importantly, it would show me updates even if I haven't changed anything in `composer.json`, like if a new version comes out that matches my requirement, or if one of my dependencies changes its own dependencies. Besides, your point was that what I want to do is not useful. I hope you can see now how it could be useful. Of course, Composer cannot be expected to do everything. Perhaps, I will write a plugin then.

Thanks for your time.

**Comment by alcohol** [comment]
Well for starters, your story does not make sense, unless you and John are working on the same computer. Because I doubt you would commit your composer.json and composer.lock changes after composer just told you it could not manage to install your new requirement. Also, how can you be writing code and using classes that you failed to install? So where does this class not found error come from? You decided to just go ahead and pretend you installed something even though you clearly failed to install it?

You see now how dumb this sounds? None of this makes sense.

If you install a new package on a Linux server and it fails, do you just proceed and pretend it has been installed too? What about on Windows? You try to install a game and it fails, do you still try to play it?

If composer throws an error, you fix it. Simple as that.

**Comment by alcohol** [comment]
And if you want to know if vendor/ contains what your lock file says it should contain, just run `composer install`. Either it will tell you there is nothing to install or update, or it will install or update whatever is missing.

**Comment by vovimayhem** [comment]
For example, when cloning a project and having an automation script that installs dependencies if they are not present...

There's no clean way to know if dependencies are installed or not! Plus, by running  a script that always runs `composer install` every time a Laravel app (in development mode) starts... there's a lot of time  spent by artisan optimizing the class loader:

```
# Emulating a startup script that installs dependencies if missing (or not) and then starts the server:
app@8cc777be84a4:~$ composer install && php artisan serve
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize
Generating optimized class loader
```

**Comment by gggeek** [comment]
I think that `php composer.phar status -v` might be what is being looked for ?

**Comment by gggeek** [comment]
@alcohol besides the user story detailed above, I can see many scenarios where having composer checking for *any* discrepancy between composer.lock and what is in the vendor/ folder is useful

**Comment by XedinUnknown** [comment]
I stopped replying because got tired of being ridiculed. So it's good to see that others recognize the need for this. I'm here, if any further details are necessary.

**Comment by vovimayhem** [comment]
@XedinUnknown I feel ya, bro! Don't take it personal. Maybe he was in a hurry or something.

I know that `composer` was heavily inspired by Ruby's `bundler`. It may seem pretty obvious for me that there's a command akin of `bundle check`, which exits with a status 1 if a dependency is missing, making it suitable to do something like this (where `bundle check` is quick and `bundle install` is not):

```
bundle check || bundle install
```

This is why a command like this on `composer` would be awesome.

**Comment by bouk** [comment]
Just for those finding this issue in search of a solution, use the following command in your script:

```
composer install --dry-run 2>&1 | grep -q "Nothing to install or update"
```

**Comment by alexpott** [comment]
Other package managers supply this feature. For example with yarn can do `yarn check -s 2>/dev/null` and the check the status of that command. It'd be really helpful for tools to be able to check this and tell the user to run composer install with the tool itself having to run composer install.

+1 for this feature.

Yes the suggestion from @bouk will work but that'll fragile and will break the moment the text changes.
