### ISSUE TITLE
Vendor binaries not executable from dist when symlinks not supported

### ISSUE THREAD

**Issue by sjparkinson** [composer/composer#4498]
I'm trying to use composer in a docker container, which unfortunately when using the out of the box virtualbox driver doesn't support symlinks.

I believe there's an issue when downloading from dist in such a situation which leaves the vendor binaries as not executable:

```
[09:20:37] $ ls -lha vendor/doctrine/dbal/bin/
total 16
drwxr-xr-x  4 Samuel  staff   136B 12 Oct 09:16 .
drwxr-xr-x  9 Samuel  staff   306B 12 Oct 09:16 ..
-rw-r--r--  1 Samuel  staff    66B 12 Oct 09:16 doctrine-dbal
-rw-r--r--  1 Samuel  staff   2.3K 12 Oct 09:16 doctrine-dbal.php
```

What I am running:

```bash
docker run -it --rm \
-v $(pwd):/app \
-v ~/.composer:/root/composer \
-v ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro \
-v ~/.ssh/known_hosts:/root/.ssh/known_hosts:ro \
composer/composer:master --no-interaction install -vvv
```

Output from the above docker command: https://gist.github.com/sjparkinson/b93d1c7802dfd418b6ae

**Comment by alcohol** [comment]
Uhm, why wouldn't it support symlinks?

**Comment by alcohol** [comment]
Look in `vendor/bin`, this is the default directory for vendor binaries.

**Comment by sjparkinson** [comment]
So I'm just trying an update to virtualbox, 5.0.4 to 5.0.6, there _might_ have been a bug, but from my reading on the weekend the configuration my just not support symlinks in the docker volume mounts.

It's currently creating the proxy files in vendor/bin correctly, but what they point to are not executable.

**Comment by alcohol** [comment]
Well that is a Docker issue then, not Composer. Sorry, but there is not much I can do here. I don't personally use Docker. I have heard of and helped other people using Docker, but they never reported this as an issue. The quickest fix I can think of is to just run `chmod 755 vendor/bin/*` after the `composer install` has finished. I simply don't have enough information to go on to suggest anything else.

**Comment by sjparkinson** [comment]
> The quickest fix I can think of is to just run chmod 755 vendor/bin/* after the composer install has finished.

Thanks for the suggestion, but I'd rather avoid the hack. It looks like after updating virtualbox to 5.0.6, then [manually enabling symlinks on the virtual machine][1] everything is working again!

I mainly opened this though as I believed everything should still have worked without symlinks, I should have mentioned that using `--prefer-source` worked as I'd expect and the vendor binaries were the correct permissions. So something about installing from dist meant the permissions were not preserved at a guess.

[1]: http://www.ahtik.com/blog/fixing-your-virtualbox-shared-folder-symlink-error/

**Comment by alcohol** [comment]
Oh, you're using a shared directory. Yeah that almost always causes issues in some way or another (weird absolute/relative path issues also for example). There really is nothing Composer can do about that.

**Comment by sjparkinson** [comment]
> Yeah that almost always causes issues in some way or another (weird absolute/relative path issues also for example).

Ah yea, noticed that last week :persevere:. Thanks anyway!
