### ISSUE TITLE
[Proposal] "Vendor"

### ISSUE THREAD

**Issue by shehi** [composer/composer#4499]
https://www.gnu.org/philosophy/words-to-avoid.html#Vendor

I will just quote:
> Please don't use the term “vendor” to refer generally to anyone that develops or packages software. Many programs are developed in order to sell copies, and their developers are therefore their vendors; this even includes some free software packages. However, many programs are developed by volunteers or organizations which do not intend to sell copies. These developers are not vendors. Likewise, only some of the packagers of GNU/Linux distributions are vendors. We recommend the general term “supplier” instead.

**Comment by alcohol** [comment]
That's great, except it is just an opinion, nothing more. We're not the first dependency manager to be using vendor, and surely won't be the last either. So in this case I think convention trumps opinion.
