### ISSUE TITLE
[Feature] Force install/update specific library

### ISSUE THREAD

**Issue by rdohms** [composer/composer#450]
Add an option to forcefully update or install a specific library. For example, i have a library added in vendors, which i usually edit in-place, when i'm ready to push this upstream i need to run composer to update locks and installs, it does not pickup the library change because its local git repo is already "up-to-date".

The only way i found around this is to remove from the installed.json and then re-run the install command. Would be great if we can force this and also if we can aim at a single library instead of a json-wide update. For example it should read dependecies for that lib and only update those.

Does this make sense?

**Comment by dylanbaxter** [comment]
All these years and I still cannot get composer to install/update a single package. Instead it starts messing with all the other packages, forcing me to go out and find old oauth tokens to connect to repositories and update libraries I'm not even using. Composer won't focus on the task I asked of it. What's so hard about that?
