### ISSUE TITLE
Dodgy code in Solver

### ISSUE THREAD

**Issue by alcohol** [composer/composer#4503]
See https://github.com/composer/composer/blob/master/src/Composer/DependencyResolver/Solver.php#L675-L678

The curious part is that `runSat()` is always explicitly called with `true` ([see here](https://github.com/composer/composer/blob/master/src/Composer/DependencyResolver/Solver.php#L220)), but this is effectively completely negated by this array assignment.

Potentially this means a whole bunch of dead code could be removed.

/cc @naderman any thoughts/ideas on the history behind this?

**Comment by naderman** [comment]
@alcohol looks like a left over from the C version of the solver that I never got to properly look at. I mean we can assume that our solver works as desired at this point and just optimize based on actual usage, or we could look at the original C source and see why that's there.

**Comment by naderman** [comment]
For the record, code is in https://github.com/openSUSE/libsolv/blob/master/src/solver.c

**Comment by naderman** [comment]
Only place that functon is called I could even find is https://github.com/openSUSE/sat-solver/blob/7188175c80d3d89f9165d6ee2d9d774c6ee7ec3c/src/problems.c#L177 - not sure where it's ever called with a true value.

**Comment by naderman** [comment]
Sorry misremember all of this a bit, it's been a while. By default https://github.com/openSUSE/libsolv/blob/6806d31042c836b34cbfbea225b7268f3c479f71/src/solver.c#L3985 it gets run with `$disableRules = true` - some of the libs using libsolv then use the other thing to rerun it to generate confliction resolution suggestions, which I don't think we do/need to do.

**Comment by naderman** [comment]
So I'm not really sure which one to pick :-)

**Comment by carnage** [comment]
Conflict resolution suggestions would be a nice feature :p

**Comment by naderman** [comment]
@carnage that doesn't really work since we don't handle the system is already setup + installing some software case, but rather build an entire reproducible package configuration from scratch each time

**Comment by carnage** [comment]
From what I recall of aptitude; when it fails a dependency graph resolution, it suggests the smallest possible changes that you can make to your requirements to resolve the situation.. As an example:

Request for SymfonyFooBundle 1.7 requires Symfony >2.7.0 <3.0.0, you require Symfony 2.6.0:
- Suggestion: require symfony 2.7.0
- Suggestion: require SymfonyFooBundle 1.6

**Comment by Seldaek** [comment]
Seems this was cleaned up in 2.0 branch
