### ISSUE TITLE
how to find proper version constraint for repo in github ?

### ISSUE THREAD

**Issue by videni** [composer/composer#4505]
I am trying to install package [Payum/PayumBundle](https://github.com/Payum/PayumBundle.git),  the lastest tag for it is not published to packigist, so I have  to add 

```
{
      "url": "https://github.com/Payum/PayumBundle.git",
      "type": "vcs"
    }
```

to  the repositories part of composer.json, then I add 

```
"require-dev": {
    "Payum/PayumBundle": "1.0.0-BETA2"
  },
```

to indicate I also need to download dev version.

this still gives me an error:

     Problem 1
    - The requested package payum/payumbundle could not be found in any version, there may be a typo in the package name.

    Potential causes:
     - A typo in the package name
     - The package is not available in a stable-enough version according to your minimum-stability setting
       see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

what I did wrong? can you show me the right way to do it please?

**Comment by stof** [comment]
The package name is ``payum/payum-bundle` not ``Payum/PayumBundle``. so you indeed have a typo in your package name.

**Comment by makasim** [comment]
@videni  FYI you dont have to define repository explicitly, the tag is published https://packagist.org/packages/payum/payum-bundle

**Comment by videni** [comment]
@stof, you are right , the package name is wrong, thanks for correcting me.

**Comment by videni** [comment]
@stof , @makasim  I thought it is resolved, but it is still the same, what I did is :   
1. correct package name from "Payum/PayumBundle" to "payum/payum-bundle"
2. change the version constraint to "1.0.*@beta" , "1.0.0" , "1.0.*@beta" ,"1.0.*@dev"


the result is still the same 

     Problem 1
    - The requested package payum/payum-bundle could not be found in any version, there may be a typo in the package name.

the latest tag for this project is 	
    1.0.0-BETA2

what is the correct version constraints? this [post](https://getcomposer.org/doc/02-libraries.md#specifying-the-version) explains what a version constraint can be , but it doesn't explain how to find the right version constraint from git tag.

**Comment by makasim** [comment]
not sure why it does not work, try to set `1.0.0-BETA2` as a version.

**Comment by videni** [comment]
@makasim ,       "1.0.0-beta2" works, I think  1.0-dev should work too,because there is a alias for master branch , which tells us when we point the version as 1.0-dev, Composer will download code in master branch, but when I tries this ,  it turns out that I am wrong, do you have any idea about this? do you know how to find a version from git tag or branch ?

    "extra": {
        "branch-alias": {
            "dev-master": "1.0-dev"
        }
    },

**Comment by alcohol** [comment]
Oddly enough, the documentation seems misleading here.

According to https://getcomposer.org/doc/articles/aliases.md#branch-alias we should be able to install `dev-master` (which is aliased to `1.0.x-dev`) by simply requiring `1.0.*`. This does not work however. Neither does requiring `1.0@dev` nor `1.0.0@dev` nor `1.0.*@dev`. If however we explicitly set `minimum-stability` to `dev`, then `1.0.*` will install `dev-master`. Perhaps this should be included as a note in the documentation. I'm confused though why the `@dev` modifier has no effect.

/cc @seldaek any idea?

**Comment by Seldaek** [comment]
`1.0@dev` / `1.0.0@dev` just really means you require exactly 1.0.0 so that's normal. The `@dev` there doesn't do anything useful. `1.0.*@dev` though should definitely install `1.0.x-dev` so if that's not the case I'll try to have a look.

**Comment by alcohol** [comment]
Yeah that's what I thought too, but I still figured I'd mention them in case I was wrong. I really expected `1.0.*@dev` to work though.

**Comment by makasim** [comment]
1.0.*@dev works for me, never tried 1.0@dev.

**Comment by alcohol** [comment]
Really? On the latest version of Composer?

**Comment by alcohol** [comment]
```
$ composer require 'payum/payum-bundle:1.0.*@dev'
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - payum/payum-bundle 1.0.x-dev requires payum/core 1.0.*@dev -> no matching package found.
    - payum/payum-bundle 1.0.0-BETA2 requires payum/core 1.0.*@dev -> no matching package found.
    - payum/payum-bundle 1.0.0-BETA1 requires payum/core 1.0.*@dev -> no matching package found.
    - Installation request for payum/payum-bundle 1.0.*@dev -> satisfiable by payum/payum-bundle[1.0.0-BETA1, 1.0.0-BETA2, 1.0.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.
```

**Comment by alcohol** [comment]
Same happens if I create a composer.json and put that requirement with that constraint in there and run `composer install`.

**Comment by alcohol** [comment]
Never mind, I'm being dumb. I just realized it depends on core which is not allowed.

**Comment by Seldaek** [comment]
`composer require 'payum/payum-bundle:1.0.*@dev'` ran through just fine for me so closing this.
