### ISSUE TITLE
 latest Composer  undefined method VersionParser::parseLinks()

### ISSUE THREAD

**Issue by xiaomeng11** [composer/composer#4506]
version message:Composer version 1.0-dev (a54f84f05f915c6d42bed94de0cdcb4406a4707b) 2015-10-13 13:09:04

composer global require "fxp/composer-asset-plugin:1.0.0-beta4"
composer global update

Fatal error: Call to undefined method Composer\Package\Version\VersionParser::parseLinks() in C:\Users\xxx\AppData\Roaming\Composer\vendor\fxp\composer-asset-plugin\Repository\VcsPackageFilter.php on line 270

Call Stack:
    0.0093     259304   1. {main}() C:\ProgramData\ComposerSetup\bin\composer.phar:0
    0.0096     258336   2. require('phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin/composer') C:\ProgramData\ComposerSetup\bin\composer.phar:25
    0.0657    2709976   3. Composer\Console\Application->run() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin/composer:43
    0.0736    2965312   4. Symfony\Component\Console\Application->run() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:82
    0.0758    3061216   5. Composer\Console\Application->doRun() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:126
    0.0788    3141104   6. Symfony\Component\Console\Application->doRun() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:147
    0.0789    3141200   7. Symfony\Component\Console\Application->doRunCommand() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:195
    0.0789    3141448   8. Composer\Command\GlobalCommand->run() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:874
    0.0855    3304536   9. Composer\Console\Application->run() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/GlobalCommand.php:80
    0.0855    3304536  10. Symfony\Component\Console\Application->run() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:82
    0.0856    3304616  11. Composer\Console\Application->doRun() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:126
    0.0870    3306184  12. Symfony\Component\Console\Application->doRun() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:147
    0.0871    3306184  13. Symfony\Component\Console\Application->doRunCommand() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:195
    0.0871    3306200  14. Symfony\Component\Console\Command\Command->run() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:874
    0.0876    3308712  15. Composer\Command\RequireCommand->execute() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
    0.0880    3310080  16. Composer\Command\Command->getComposer() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/RequireCommand.php:96
    0.0880    3310208  17. Composer\Console\Application->getComposer() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/Command.php:53
    0.0880    3310360  18. Composer\Factory::create() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:225
    0.0880    3310432  19. Composer\Factory->createComposer() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Factory.php:490
    0.7488    5690864  20. Composer\Plugin\PluginManager->loadInstalledPlugins() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Factory.php:296
    0.7488    5691016  21. Composer\Plugin\PluginManager->loadRepository() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Plugin/PluginManager.php:68
    0.7511    5714032  22. Composer\Plugin\PluginManager->registerPackage() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Plugin/PluginManager.php:141
    0.7538    5825816  23. Composer\Plugin\PluginManager->addPlugin() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Plugin/PluginManager.php:256
    0.7538    5826008  24. Fxp\Composer\AssetPlugin\FxpAssetPlugin->activate() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Plugin/PluginManager.php:86
    0.7548    5869488  25. Fxp\Composer\AssetPlugin\Repository\VcsPackageFilter->__construct() C:\Users\xxx\AppData\Roaming\Composer\vendor\fxp\composer-asset-plugin\FxpAssetPlugin.php:84
    0.7551    5879288  26. Fxp\Composer\AssetPlugin\Repository\VcsPackageFilter->initialize() C:\Users\xxx\AppData\Roaming\Composer\vendor\fxp\composer-asset-plugin\Repository\VcsPackageFilter.php:70
    0.7551    5879592  27. Fxp\Composer\AssetPlugin\Repository\VcsPackageFilter->initInstalledPackages() C:\Users\xxx\AppData\Roaming\Composer\vendor\fxp\composer-asset-plugin\Repository\VcsPackageFilter.php:243

**Comment by alcohol** [comment]
Please update the plugin you are using. This is not a Composer issue.

**Comment by stof** [comment]
1.0-beta4 of the plugin is 1 year old, and it is indeed not compatible anymore. Use the latest stable version of the plugin instead.
