### ISSUE TITLE
Composer fails installing due to dependency conflict, reason not clearly given

### ISSUE THREAD

**Issue by andig** [composer/composer#4507]
I've got a working application the I'd like to add a package to:

    composer require -v influxdb/influxdb-php:dev-master

Your requirements could not be resolved to an installable set of packages.

	  Problem 1
	    - Can only install one of: guzzlehttp/guzzle[6.1.x-dev, 5.3.0].
	    - Can only install one of: guzzlehttp/guzzle[6.1.x-dev, 5.3.0].
	    - Can only install one of: guzzlehttp/guzzle[6.1.x-dev, 5.3.0].
	    - influxdb/influxdb-php dev-master requires guzzlehttp/guzzle 6.* -> satisfiable by guzzlehttp/guzzle[6.1.x-dev].
	    - Installation request for influxdb/influxdb-php dev-master -> satisfiable by influxdb/influxdb-php[dev-master].
	    - Installation request for guzzlehttp/guzzle == 5.3.0.0 -> satisfiable by guzzlehttp/guzzle[5.3.0].

My problem is that the root cause remains hidden:

Same message after removing `composer.lock`

  1. there is the repeated message about the conflict
  2. its clear what influx requires, but its not clear what/who requires guzzle 5.3 -> it would be helpful to get a message where that requirement comes from 

This is the `composer.json`:

    {
        "name": "volkszaehler/volkszaehler",
        "type": "project",
        "description": "volkszaehler is a free smart meter implementation with focus on data privacy",
        "homepage": "http://www.volkszaehler.org/",
        "license": "GPL-3.0",
        "support": {
            "wiki": "http://wiki.volkszaehler.org/",
            "email": "volkszaehler@lists.volkszaehler.org"
        },
        "minimum-stability": "dev",
        "prefer-stable": true,
        "require": {
            "php": ">=5.4.0",
            "doctrine/orm": "2.4.*",
            "doctrine/dbal": "2.5.*",
            "andig/dbcopy": "dev-master",
            "symfony/console": "2.6.*",
            "symfony/http-kernel": "2.6.*",
            "symfony/http-foundation": "2.6.*",
            "cboden/ratchet": "0.3.*",
            "react/socket": "0.4.*",
            "react/http": "0.4.*",
            "guzzlehttp/guzzle": "^5.0",
            "guzzlehttp/streams": "^3.0@dev",
            "andig/jsonstreamingparser": "dev-master"
        },
        "require-dev": {
            "phpunit/phpunit": "4.4.*",
            "react/socket-client": "0.4.*"
        },
        "autoload": {
            "psr-4": {
                "Volkszaehler\\": "lib/",
                "Tests\\": "test/"
            }
        }
    }

**Comment by andig** [comment]
Update: I believe I do understand now that "guzzlehttp/guzzle": "^5.0" is the culprit as it won't match the 6.0 versions. Yet I would never have guessed that as a) it wasn't clear that was a parent composer.json requriement and b) the messages pointed to 5.3 (which is installed) but not ^5.0 (which was required).

Is there any chance making the errors more explicit/ talking?

**Comment by alcohol** [comment]
It's on the to-do list.

**Comment by alcohol** [comment]
"duplicate" (sort of) of #1362
