### ISSUE TITLE
Optimized autoload with --no-dev add autoload for dev dependencies

### ISSUE THREAD

**Issue by clemgrim** [composer/composer#4511]
Hello, 

I have the following composer.json

```json
{
    "name": "packagename",
    "require": {
        "jeremeamia/superclosure": "~2.0",
        "twig/twig": "~1.0",
        "facebook/php-sdk-v4": "^5.0",
        "kriswallsmith/assetic": "^1.3",
        "meenie/javascript-packer": "^1.1",
        "natxet/cssmin": "^3.0"
    },
    "config": {
        "vendor-dir": "library/vendor"
    },
    "require-dev": {
        "zendframework/zendframework1": "^1.12"
    }
}
```

When I run `composer dump-autoload --no-dev` it is ok, I don't have autoload for Zend.
But when i run `composer dump-autoload -o --no-dev`, the autoload for Zend is generated...

How can I solve this ?
Thank you

**Comment by alcohol** [comment]
Is it installed when you run it?

**Comment by alcohol** [comment]
I think you are confused about the purpose of `--no-dev`. The option documentation clearly states:

> Disables autoload-dev rules.

autoload-dev! !== require-dev

**Comment by alcohol** [comment]
Both `composer dump-autoload` and `composer dump-autoload -o` generate autoload rules for the Zend package. But they're different. Without `-o` it's just one `psr-0` entry. With `-o` Composer scans all directories that fall under that `psr-0` definition and adds them to the classmap.

**Comment by clemgrim** [comment]
I think you're right, I misunderstood this option.
Thank you for the explanation.

Do you know how can I do (if it is possible) for excluding my dev dependencies autoload in production (`dump-autoload -o`) ?

Actually, I find this solution but I would like to know if there is an easier/more practice way :
- Remove my `vendor` directory
- run `composer install --no-dev -o`

But when I need my dev-dependencies (for testing), I have to re-install dependencies to include the dev one, etc...

I don't know if I'm very clear (sorry for my bad english :/)
Thank you

**Comment by alcohol** [comment]
You can just run `composer install --no-dev` when everything is already installed. That will uninstall the dev dependencies. You don't have to remove your whole `vendor/` directory. After that you can run `composer dump -o`. Reinstalling dev dependencies is just a matter of running `composer install` again.

I recommend using `--prefer-dist` on production. It makes caching easier/faster.

**Comment by clemgrim** [comment]
Thank you very much for this quick/useful responses.
I think you can close this issue

**Comment by alcohol** [comment]
Alright, I hope that helped.
