### ISSUE TITLE
Repository type path do not update

### ISSUE THREAD

**Issue by joelwurtz** [composer/composer#4512]
I'm using the new repository type path and any update done to the composer.json of the dependency is not used when updating the root library, i.e : 

composer.json of root package

```
{
    "require": {
         "vendor/my-lib": "*@dev"
    }
    "repositories": [
        {
            "type": "path",
            "url": "../my-lib"
        }
    ],
}
```

composer of my-lib : 

```
{
     "name": "vendor/my-lib",
     "require": 

     ...
}
```

It work fine at installation, if i update the composer.json (adding a dependency, changing the autoload, ....) when i want to update the root package no changes are made.

The only workaround is to force a new version in both composer.json

root package :

```
require: { "vendor/my-lib": "new-version"}
```

my lib package :

```
"version": "new-version"
```

Then the dependancy is correctly updated.

After some searching, i found that the composer.lock of the root package always include the old version of my-lib dependency, is there some kind of cache ? (doing composer clearcache does not solve this)

**Comment by alcohol** [comment]
I don't really understand the issue.

Can you give a step by step description of how to reproduce your problem?

**Comment by joelwurtz** [comment]
I have a repository with multiples application / package linked together : 

 * projects/common : A common library
 * projects/application : A web application
 * projects/webapp : Another application

Each application and library has a composer.json. 
Composer.json of applications contain has a dependency on the common library by using the repository type "path"

```
{
    "name": "vendor/application",
    "license": "proprietary",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "symfony/symfony": "~2.7.5",
         ...
        "vendor/common": "*@dev"
    },
    "repositories": [
        {
            "type": "path",
            "url": "../common"
        }
    ]
}
```

The library have also its own composer.json with dependencies : 

```
{
    "name": "vendor/common",
    "license": "proprietary",
    "authors": [
        {
            "name": "Joel Wurtz",
            "email": "jwurtz@jolicode.com"
        }
    ],
    "autoload": {
        "psr-4": {
            "Vendor\\Common\\": "src/",
        }
    },
    "require": {
        "egeloen/http-adapter": "dev-master"
    }
}
```

Everything work fine on the initial composer install or subsequent composer update. 

However when i change the composer.json of my common library, by adding a namespace to psr4, a new dependency, etc... : 

```
{
    "name": "vendor/common",
    "license": "proprietary",
    "authors": [
        {
            "name": "Joel Wurtz",
            "email": "jwurtz@jolicode.com"
        }
    ],
    "autoload": {
        "psr-4": {
            "Vendor\\Common\\": "src/",
            "Namespace\\New\\": "library/"
        }
    },
    "require": {
        "egeloen/http-adapter": "dev-master"
    }
}
```

Running a composer update on the application will never apply changes from my common library (the autoload will never add the new namespace in this case) In fact the composer.lock of the application does not upgrade the content of the common library composer.json

**Comment by alcohol** [comment]
o... I don't know about that. I don't use the path repository. Sounds like a bug potentially. Maybe I'll give it a spin this weekend.

**Comment by joelwurtz** [comment]
I will try to provide a unit test also this weekend (this is often the best explanation)

**Comment by joelwurtz** [comment]
Having a hard time to find the cause of this :s. I have a supposition but not sure of it. 

How does composer will take the action of update ? 

If it compare the composer.json installed as the one from the repository this may cause the bug as it will always be equals since this is as symlink and so composer never trigger update for this package.

If it compare from the installed.json file then i have no clue :/

PS : i have found a better workaround by removing the installed.json file in vendor/composer which will correctly update the package

**Comment by joelwurtz** [comment]
Good for me don't have this anymore with the merge and the associated commit, thanks for the support.

**Comment by XedinUnknown** [comment]
I am still getting this issue.
```
$ sudo composer self-update
You are already using composer version d6ae9a0529e1f39c4c7f9b2f29fff019d79cd1fb.
```

**Comment by quazardous** [comment]
@joelwurtz 

same here

in the local repo if you set up a psr-4 like

```json
"autoload" : {
        "psr-4" : {
            "Foo\\Bar\\" : "src/Bar"
        }
    }
...
...
```

the autoload_psr4.php is wrong:

```php
...
'Foo\\Bar\\' => array($vendorDir . '/johndoe/mypack/src'),
...

```

should be:

```php
'Foo\\Bar\\' => array($vendorDir . '/johndoe/mypack/src/Bar'),
```
