### ISSUE TITLE
PathDownloader regression on Windows because of #4426

### ISSUE THREAD

**Issue by Mischi** [composer/composer#4516]
Hi all, 

i'm having some trouble with "path" repositories on Windows 10.
The problems seems to be that the $path argument to findShortestPath in https://github.com/composer/composer/blob/master/src/Composer/Downloader/PathDownloader.php#L51 is a relative path.

If i revert the changes made in #4426 everything seems to work fine.

@sroze do you know how to convert $path to an absolute path before calling findShortestPath?

Regards,
Fabian

Error Message:
```
composer require fami-sites/fami-one *@dev
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing fami-sites/fami-one (dev-master)

  [InvalidArgumentException]
  $from (web/app/themes/fami-one/) and $to (C:\Users\fraetz.BAG\Documents\Projects\fami-sites\packages\fami-one) must
   be absolute paths.

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [packages1] ... [packagesN]
```

**Comment by alcohol** [comment]
It's important to point out that this only affects plugin installers, not normal use of path repository.

**Comment by Seldaek** [comment]
I don't think this is relevant anymore with latest version of the code so I'll close but feel free to say if that's mistaken.
