### ISSUE TITLE
Exception when uninstalling a plugin

### ISSUE THREAD

**Issue by pyrech** [composer/composer#4520]
Hi,

When I want to uninstall a plugin, composer will still try to run it at the end of the command (because it was registered in the eventListener by the plugin manager). The problem is that some classes were not autoloaded before the uninstall operation, so the autoloader will fail when running the plugin.

Shouldn't composer unregister the plugin before removing it? If yes, I'm not sure where this should be done tough.

You can reproduce it easily by running:

``` bash
composer global require "pyrech/composer-changelogs"
```

then:

``` bash
composer global remove "pyrech/composer-changelogs"
```

You should get the following output:

```
Changed current directory to /home/mike/.composer
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing pyrech/composer-changelogs (v1.1.1)
Writing lock file
Generating autoload files
PHP Fatal error:  Class 'Pyrech\ComposerChangelogs\Version' not found in /home/mike/.composer/vendor/pyrech/composer-changelogs/src/OperationHandler/UninstallHandler.php on line 54

Fatal error: Class 'Pyrech\ComposerChangelogs\Version' not found in /home/mike/.composer/vendor/pyrech/composer-changelogs/src/OperationHandler/UninstallHandler.php on line 54
```

The issue is related to pyrech/composer-changelogs#14

**Comment by alcohol** [comment]
Much easier would probably be to add a `--no-plugins` to `require`/`remove` (`install` has it already).

**Comment by Seldaek** [comment]
Yeah I am pretty sure we should have a way to unregister plugins, and tell them to unload themselves too. Otherwise that sounds pretty dangerous for plugin updates as well.

Having a --no-plugin on top of it is even better but these are two separate problems IMO.

**Comment by pyrech** [comment]
I don't have a big knowledge of Composer's internal but maybe overriding the `uninstall` method in the PluginInstaller could be a good start.

**Comment by pyrech** [comment]
FYI I found a workaround for my plugin. In https://github.com/pyrech/composer-changelogs/pull/22 I force the autoload of  classes so that they exists when the plugin need them.

**Comment by Seldaek** [comment]
2.0's PluginInterface has `deactivate` and `uninstall` methods which if implemented correctly should let us do graceful updates/uninstalls.
