### ISSUE TITLE
Ability to install only dev packages

### ISSUE THREAD

**Issue by ihor-sviziev** [composer/composer#4522]
Hi,

We using phpunit as require-dev package, also we have some other "require" dependencies.
For now we using ```composer update --no-dev``` before committing our changes to VCS (no need to track that phpunit updated some minor version), so when I try to use ```composer install``` - it give me message like this: 
> The lock file does not contain require-dev information, run install with the --no-dev option or run update to install those packages.

Is there any ability to install "require-dev" packages without updating "require" packages?

**Comment by alcohol** [comment]
Why don't you just use `composer install --no-dev` to uninstall the dev packages (or not install them on your production environment). That way you don't use .lock information and you can simply run `composer install` to re-install them.

**Comment by ihor-sviziev** [comment]
@alcohol in this case we had a lot of conflicts during merge different branched in "require-dev" section of "composer.lock" file, so we stoped commit "dev" packages to git.

**Comment by alcohol** [comment]
That is probably because you are using `composer update` too much, and should be using `composer install` more often instead.

**Comment by ihor-sviziev** [comment]
@alcohol we're using changing composer.json file (if needed) + composer update --no-dev to update __our__ "require" packages that we develop. We have a lot conflicts in composer.lock file with "require" packages, we don't wont have conflicts also in "require-dev" section. Any ideas to prevent this situation or ability to install only "dev" packages?

**Comment by alcohol** [comment]
Yeah. Just don't commit your `composer.lock` file.

**Comment by ihor-sviziev** [comment]
@alcohol but in this case when you didn't commit composer.lock file - you haven't ability to install __same__ version on local machine and on prod, coz same dev module version can be associated to different commits.

**Comment by alcohol** [comment]
Correct. But if you're updating it every day, then it does not really matter, don't you agree?

**Comment by alcohol** [comment]
Ok, regarding your actual question, since this drifted off-topic:

You _cannot_ "install" require-dev packages without installing require packages.
You **can** "update" require-dev packages without updating require packages.

E.g.

```
composer update vendor/package
// or
composer update 'vendor/*'
```

**Comment by lkraav** [comment]
:thinking: 

In the case of developing a library, that is only testable by requiring it in an upstream project, which will take care of installing runtime deps - for development, I'd love to only install dev tools.

Right now, this library's `vendor/` folder and lock file sort of get "polluted" by a bunch of stuff. Can I somehow make a require-dev-only lock file?
