### ISSUE TITLE
composer require doesn't run pre-install-cmd

### ISSUE THREAD

**Issue by oligriffiths** [composer/composer#4523]
I've noticed that running `composer require vendor/package` doesn't trigger the `pre-install-cmd` or `pre-update-cmd` scripts to run. Is there a way to run a script `pre-require` I don't see anything in the docs about this? I am using the pre-install and pre-update hooks to update a composer proxy cache, so need this to run before anything is installed/updated.

**Comment by elazar** [comment]
@oligriffiths Can you run `composer --version` and post the output here? I'm not able to replicate your problem with f85d965732d9505b69242a070dc0b381c9f6bbab: `pre-update-cmd` is triggered for me.

```json
{
    "scripts": {
        "pre-install-cmd": "echo \"pre-install-cmd\\n\"",
        "pre-update-cmd": "echo \"pre-update-cmd\\n\""
    }
}
```

```
$ composer require "phergie/phergie-irc-parser"
Using version ^2.1 for phergie/phergie-irc-parser
./composer.json has been updated
> echo "pre-update-cmd\n"
pre-update-cmd

Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing phergie/phergie-irc-parser (2.1.0)
    Loading from cache

Writing lock file
Generating autoload files
```

**Comment by oligriffiths** [comment]
Ok, so, I have this in my composer.json:
```
"repositories":[
        { "packagist": false }
    ],
```
And in my pre-install and pre-update hooks I'm dynamically adding the path to a repository if the repository is online, else I add the default packagist host in.

It seems that when doing a require without a version, composer is attempting to contact the repositories in order to resolve this dependency to the latest version. As I have packagist disabled, and no pre-* hooks are being fired, it can't resolve it and as such fails.

Any suggestions?

**Comment by elazar** [comment]
> I'm dynamically adding the path to a repository

Adding the path to what? Can you give a rough example of what you're doing and how?

**Comment by Seldaek** [comment]
Yeah it makes sense the require command (and many others) fetch the packages directly from the available repositories. I think for a generic solution you should rethink your approach, maybe just *always* register the repos in your plugin::activate()? That sounds a lot safer to me.

**Comment by oligriffiths** [comment]
@Seldaek This is in the root `composer.json` can one still use plugins there? I didn't find the docs very helpful on that.

**Comment by Seldaek** [comment]
Ah you just use a script, yeah I don't think you can use a script that'll run always, we don't have that. You could turn it into a plugin though.

**Comment by oligriffiths** [comment]
Happy to do so, how does one register a plugin at the root level?

**Comment by Seldaek** [comment]
You just create the plugin and require it as a dependency
