### ISSUE TITLE
Composer isn't using auth.json to authenticate against private repositories

### ISSUE THREAD

**Issue by jdiefenbach83** [composer/composer#4524]
Hello, I'm facing a problem with composer using a private git repository that needs authentication to download the packages,

We have a private apache server with remote git repositories. It was configured to authenticate using HTTP-Basic and we have a repository with a composer package.

I've created a __composer.json__ according the manual and internet examples, I've got this:

	{
	  "name": "teste/teste",
	  "description": "teste",        
	  "license": "proprietary",    
	  "repositories": [
		{
		  "type": "vcs",
		  "url": "http://git.green.com.br/sisconex.git"
		}
	  ],
	  "require": {
	  "wtm/sisconex": "0.9.0"
	  }
	}

and I've created a __auth.json__ as well:

	{
		"http-basic": {
			"git.green.com.br": {
				"username": "myuser",
				"password": "mypassword"
			}
		}
	}

When I run __composer install -vvv__ It ouput:
![image](https://cloud.githubusercontent.com/assets/11763719/10647792/52bd235e-7819-11e5-9ff4-6b9e350e4ef5.png)

Full output:

	Reading ./composer.json
	Loading config file ./composer.json
	Loading config file /home/jefferson/testecomposer/auth.json
	Executing command (/home/jefferson/testecomposer): git describe --exact-match --tags
	Executing command (/home/jefferson/testecomposer): git branch --no-color --no-abbrev -v
	Executing command (/home/jefferson/testecomposer): hg branch
	Executing command (/home/jefferson/testecomposer): svn info --xml
	Failed to initialize global composer: Composer could not find the config file: /home/jefferson/.composer/composer.json
	To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
	Loading composer repositories with package information
	Executing command (CWD): git clone --mirror 'http://git.green.com.br/sisconex.git' '/home/jefferson/.composer/cache/vcs/http---git.green.com.br-sisconex.git/'
	Executing command (CWD): git --version

																																								 
	  [RuntimeException]                                                                                                                                         
	  Failed to execute git clone --mirror 'http://git.green.com.br/sisconex.git' '/home/jefferson/.composer/cache/vcs/http---git.green.com.br-sisconex.git/'  
	  Cloning into bare repository '/home/jefferson/.composer/cache/vcs/http---git.green.com.br-sisconex.git'...                                                
	  fatal: unable to access 'http://git.green.com.br/sisconex.git/': The requested URL returned error: 500                                                    
																																								 

	Exception trace:
	 () at phar:///usr/local/bin/composer/src/Composer/Util/Git.php:222
	 Composer\Util\Git->throwException() at phar:///usr/local/bin/composer/src/Composer/Util/Git.php:151
	 Composer\Util\Git->runCommand() at phar:///usr/local/bin/composer/src/Composer/Repository/Vcs/GitDriver.php:80
	 Composer\Repository\Vcs\GitDriver->initialize() at phar:///usr/local/bin/composer/src/Composer/Repository/VcsRepository.php:86
	 Composer\Repository\VcsRepository->getDriver() at phar:///usr/local/bin/composer/src/Composer/Repository/VcsRepository.php:113
	 Composer\Repository\VcsRepository->initialize() at phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:179
	 Composer\Repository\ArrayRepository->getPackages() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:104
	 Composer\DependencyResolver\Pool->addRepository() at phar:///usr/local/bin/composer/src/Composer/Installer.php:408
	 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:232
	 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php:134
	 Composer\Command\InstallCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
	 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
	 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
	 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:147
	 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
	 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:82
	 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
	 require() at /usr/local/bin/composer:25

	install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [packages1] ... [packagesN]

I tried to run __composer install -vvv__ without __auth.json__ It's should ask for the credentials but some errors are shown. It output:
![image](https://cloud.githubusercontent.com/assets/11763719/10647849/a47f3902-7819-11e5-9510-be118e4d7ab7.png)

Full output:

	Reading ./composer.json
	Loading config file ./composer.json
	Executing command (/home/jefferson/testecomposer): git describe --exact-match --tags
	Executing command (/home/jefferson/testecomposer): git branch --no-color --no-abbrev -v
	Executing command (/home/jefferson/testecomposer): hg branch
	Executing command (/home/jefferson/testecomposer): svn info --xml
	Failed to initialize global composer: Composer could not find the config file: /home/jefferson/.composer/composer.json
	To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
	Loading composer repositories with package information
	Executing command (CWD): git clone --mirror 'http://git.green.com.br/sisconex.git' '/home/jefferson/.composer/cache/vcs/http---git.green.com.br-sisconex.git/'
	Executing command (CWD): git --version

																																								 
	  [RuntimeException]                                                                                                                                         
	  Failed to execute git clone --mirror 'http://git.green.com.br/sisconex.git' '/home/jefferson/.composer/cache/vcs/http---git.green.com.br-sisconex.git/'  
	  Cloning into bare repository '/home/jefferson/.composer/cache/vcs/http---git.green.com.br-sisconex.git'...                                                
	  fatal: unable to access 'http://git.green.com.br/sisconex.git/': The requested URL returned error: 500                                                    
																																								 

	Exception trace:
	 () at phar:///usr/local/bin/composer/src/Composer/Util/Git.php:222
	 Composer\Util\Git->throwException() at phar:///usr/local/bin/composer/src/Composer/Util/Git.php:151
	 Composer\Util\Git->runCommand() at phar:///usr/local/bin/composer/src/Composer/Repository/Vcs/GitDriver.php:80
	 Composer\Repository\Vcs\GitDriver->initialize() at phar:///usr/local/bin/composer/src/Composer/Repository/VcsRepository.php:86
	 Composer\Repository\VcsRepository->getDriver() at phar:///usr/local/bin/composer/src/Composer/Repository/VcsRepository.php:113
	 Composer\Repository\VcsRepository->initialize() at phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:179
	 Composer\Repository\ArrayRepository->getPackages() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:104
	 Composer\DependencyResolver\Pool->addRepository() at phar:///usr/local/bin/composer/src/Composer/Installer.php:408
	 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:232
	 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php:134
	 Composer\Command\InstallCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
	 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
	 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
	 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:147
	 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
	 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:82
	 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
	 require() at /usr/local/bin/composer:25

	install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [packages1] ... [packagesN]

When I just use __git clone__, using the same sintax extracted from previous images, git asked me username and password:

![image](https://cloud.githubusercontent.com/assets/11763719/10647875/e2a4e31c-7819-11e5-9bf5-a14b3fab155f.png)

I followed 3 ways as described in composer documentation https://getcomposer.org/doc/articles/http-basic-authentication.md, but just the first way worked to me, when I put my username and password as part of URL.

I tested the access from a web browser and I was prompted asking my credentials:

![image](https://cloud.githubusercontent.com/assets/11763719/10648015/c3e7cf4c-781a-11e5-8846-f5027515c9a2.png)

Please, could you verify this case? If I am making mistakes, could you please show me where It is?

Thank you so much.

**Comment by alcohol** [comment]
Can you actually manually clone it from the command line using `git`?

**Comment by Seldaek** [comment]
One thing that is strange here is that your server returns a 500 error, so maybe that's why composer doesn't detect it as needing authentication and doesn't prompt for the password.

We detect auth failures and try to authenticate when we receive back one of these in the git output: `array('fatal: Authentication failed', 'remote error: Invalid username or password.')`

So it sounds like a misconfiguration of the server to me.

**Comment by jdiefenbach83** [comment]
Hello, yes I can clone it manually alcohol. It works fine!

**Comment by jdiefenbach83** [comment]
Hi Seldaek, the 500 error from HTTP server is given when you input invalids username/password. In this case we're using Redmine integrate with git running over an apache server.

Does the composer detect if it needs username/password based on authentication fails?

When I execute __composer install__, it should've ask for inputing username/password but it gives me the error straightforwardly.

**Comment by alcohol** [comment]
A 500 is an internal server error. It makes no sense to return that if auth is invalid. Please follow standards like the rest of the internet does. :(

**Comment by alcohol** [comment]
Composer is expecting a `fatal: Authentication failed`, and your server is returning a `fatal: unable to access`.

**Comment by jdiefenbach83** [comment]
Guys, you're right! I found a error in my server configuration. I fixed it and worked properly!

I could learn so much in this case!

Thank you so much.

**Comment by alcohol** [comment]
Glad to hear that :-)

**Comment by Mon-Tea** [comment]
I got the same issue, how did you fix it ?

**Comment by sanjay-code-debug** [comment]
composer.json file 
 ==============
 "repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "gitlab.codilar.in/277": {
            "type": "composer",
            "url": "https://gitlab.test.in/api/v4/group/277/-/packages/composer/packages.json"
        }
    },
    
    auth.json
    =======
    {
    "gitlab-token": {
        "gitlab.privateinstance.com": "bjC2RG4J4tcYksZRsxMZ"
    }
}
php version = 8.1 
magento version = 2.4.6 

composer install
         |--------------------------It is not working getting below error 
                                                     |
       In CurlDownloader.php line 623:
                                                                                                                                             
  The "https://gitlab.test.in/api/v4/group/277/-/packages/composer/packages.json" file could not be downloaded (HTTP/1.1 404 Not Found):  
  {"message":"404 Group Not Found"}   
  
  
  - Any solution will be help full

**Comment by shabana-7860** [comment]
iam facing gatehub authentication error
