### ISSUE TITLE
Reopen #1988 (concerning annotations/comments)

### ISSUE THREAD

**Issue by JorisDebonnet** [composer/composer#4528]
Could you reopen #1988 please? 

Since January 2014, barely a month has gone by without a reply there. It was already closed then, so people are probably ending up there through searches for this feature request. Perhaps the original suggestion is not feasible, but clearly a lot of people want this, so *some* solution deserves to be found. Even if it ends up being something completely different: several ideas have been suggested. 

A debate about this would work better in an *open* ticket. :)

**Comment by alcohol** [comment]
No.

**Comment by whitehat101** [comment]
I've been a big fan of issue  #1988. I enjoyed seeing the countless "+1"s flow through my inbox. I must say, despite this policy being massively unpopular with the community, the composer team is firmly defending their product from feature creep by having a well defined policy on comments:

> No.
>
> No further comments.

**Comment by quazardous** [comment]
+1
