### ISSUE TITLE
Release a new alpha

### ISSUE THREAD

**Issue by paladox** [composer/composer#4532]
Hi please can you release a new alpha since it has been along time since you released a alpha you last released one in april but that seems to show as stable.

**Comment by Seldaek** [comment]
Updated the changelog.. I'll try and make a release soon as well.

**Comment by paladox** [comment]
Thanks.

**Comment by paladox** [comment]
When you release a new version do you also update the Windows build to.

**Comment by alcohol** [comment]
Composer releases are OS agnostic. The Windows installer is just an installer, it is not bound to a specific version.

**Comment by paladox** [comment]
Oh ok.

**Comment by rjmunro** [comment]
Any chance of a *beta* release one day?

**Comment by Seldaek** [comment]
Chances, sure. It's a goal, but there are some things left I'd like to get done first.. not that it really matters to most people what the version is though.

**Comment by paladox** [comment]
Hi do you have a date on when a new release will be released.

**Comment by paladox** [comment]
Hi do you have a date on when a new release will be released.

**Comment by Seldaek** [comment]
When it's done, and asking more just wastes everyone's time really :/
