### ISSUE TITLE
Connection Error [ERR_CONNECTION]: Unable to connect to getcomposer.org

### ISSUE THREAD

**Issue by AlaaSyria** [composer/composer#4533]
Connection Error [ERR_CONNECTION]: Unable to connect to getcomposer.org

Request to https://getcomposer.org/installer failed with errors:
Failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

i install with xampp,windows 7 64bit

**Comment by alcohol** [comment]
Is this still an issue?

**Comment by AlaaSyria** [comment]
yes,it is not work.
