### ISSUE TITLE
Defining Virtual Packages interactively

### ISSUE THREAD

**Issue by Swader** [composer/composer#4535]
Suggest upgrading Composer to detect when we're dealing with a virtual package (https://packagist.org/providers/php-http/client-implementation) so that rather than saying it cannot resolve a package, the `composer require php-http/client-implementation` command would actually add the VP into the require block and not complain.

For additional "safety check", after detecting it's dealing with a virtual package, Composer could prompt the user for an implementation of it and suggest putting it into `dev`:

> php-http/client-implementation seems to be a virtual package. Would you like to add a concrete implementation into require-dev?

**Comment by sstok** [comment]
:+1:

**Comment by Seldaek** [comment]
We can't do version guessing for those though as there are no versions, and we'd need a specific way to query them from packagist, which is a bit of a PITA and packagist-specific features aren't great.

I agree it sounds good but it sounds like a lot of added complexity for a minor improvement down the line.

**Comment by Seldaek** [comment]
Closing as #6758 would allow fixing this to some extent and I also don't really agree this is a problem that needs addressing in itself.
