### ISSUE TITLE
Satis repository build fails because Composer JsonFile hungs lots of memory

### ISSUE THREAD

**Issue by bvis** [composer/composer#4537]
When executing a simple "build" command of a satis repository I'm experiencing this error:

    PHP Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 8972426 bytes) in /project_root/satis/vendor/composer/composer/src/Composer/Json/JsonFile.php on line 123

My solution will be double the memory assigned to PHP processes, but I think this is not a sustainable solution. What I see in the problematic line is:

    file_put_contents($this->path, static::encode($hash, $options). ($options & self::JSON_PRETTY_PRINT ? "\n" : ''));

Couldn't be used another strategy less memory aggressive?
My proposal is to use a loop to store the data in the file instead of use *file_put_contents()*

**Comment by alcohol** [comment]
Try upping your memory limit to 512M. It's a build process, it's ok to consumer a bit more than your average web request.

**Comment by omansour** [comment]
indeed. we add 2G of memory to build our private satis http://tech.m6web.fr/composer-installation-without-github.html (old post). 

this issue is not solved but not very annoying.

**Comment by stof** [comment]
@bvis the issue with your proposal is that it would require to create the json content by hand to build it by chunks instead of using json_encode. This can be quite error-prone
