### ISSUE TITLE
How to supply a file that does NOT end up in vendor directory.

### ISSUE THREAD

**Issue by rquadling** [composer/composer#4544]
Hi.

I've got a package which I uses ``vlucas/phpdotenv``. I want to supply an example file for this package, such that, when the user installs the package, they get an example file in their project root.

Is this an acceptable approach? If so, what do I put in my package's composer.json file to do that.

**Comment by alcohol** [comment]
Is your package a "library" or a "project" type?

**Comment by rquadling** [comment]
A project type. It is a --dev only package that allows my development team to optimize a PHPMaker file. But each developer has a slightly different setup, so I want to use a .env file to allow them to configure their specifics without having to put them on the command line, or in a shell/batch script.

**Comment by rquadling** [comment]
And didn't realise there was a composer.json entry for ``"type":"project"``. Just seeing how I can work my magic with this.

**Comment by alcohol** [comment]
No I think you misunderstood. You can define a "type" in your composer.json. By default this is always library. And from what you've told me so far, this sounds like it is indeed a library, not a project. A project type is used when you want the repository to be your project root.

As for the answer to your question then, you don't/can't.

Your project should contain the .env.example file; see https://github.com/alcohol/paste.robbast.nl/ for example.

**Comment by rquadling** [comment]
Thank you. Basically documented the requirement. Much easier!
