### ISSUE TITLE
How about implement conditionnals requirements ? 

### ISSUE THREAD

**Issue by mickaelandrieu** [composer/composer#4545]
Hi,

I was thinking about conditionals requirements.

For instance, let's imagine we want to provide only one `composer.json` file but the requirements may differs according to the user platform.

```
require-php53 : {
    "foo": "5.3",
},
require-php54 : {
    "foo": "5.4",
},
require-php70 : {
    "foo7": "2.0"
}
...
```

This kind of feature would solve the issues we can meet with package from community to provide missing feature from old PHP versions (like [https://github.com/ircmaxell/password_compat](password_compat) for instance.
 
A second use case is different and may (should ?) be solved by an "or" operator. Let's imagine you provide some picture treatment features and you have 2 adaptors (this is a pb we actualy have in elcodi project https://gitter.im/elcodi/elcodi).

If you have the gd extension, the gd adaptor is activated, if you have the imagemagick extension the related adaptor is also available: *but you have to require one of them*.

A nice way to describe this case should be:

```
require-or: {
    {
        "ext-gd": "*",
        "ext-imagemagick": "*",
    },
    {
        "foo": "^1.0",
        "bar": "~2.0",
    }, 
}
```

To be honest, I don't know how the others languages solve this kind of issue, and there is probably a workaround to already solve it.

What do you think ?

May be related: 
- https://github.com/composer/composer/issues/4168 (Conditional requirements)
- https://fedoraproject.org/wiki/Packaging:DistTag (package according to the Fedora distribution version)
- https://github.com/composer/composer/issues/751 (some discussions about it)
- https://github.com/composer/composer/issues/2940 (conditional platforms, perfect use case =>  the Symfony Polyfill component)

**Comment by alcohol** [comment]
No thank you.

**Comment by mickaelandrieu** [comment]
o_O maybe an explanation can be useful for the record ?

**Comment by alcohol** [comment]
If you have taken the time to read the various replies on the issues you've already listed, you would know this is unlikely to be introduced.

**Comment by mickaelandrieu** [comment]
I did (I'm probably one of the "rare" persons to take time to look at the history before post an issue, but thanks :/), and I'm aware how hard this can be.

More, #2940 tag this feature for "Later" milestone, not "never ever".

Can you explain me why the Composer core team change this mind, and if there a workaround to address theses issues ?

Regards,

**Comment by alcohol** [comment]
Not never, indeed. But unlikely. And there is no need to duplicate existing issues. Submitting multiple requests for the same feature does not make it more likely to be introduced.

It's a complex and completely edge-case scenario. There are other ways to overcome some of these inconveniences.

We simply do not want to turn Composer into this:
![over-engineered](http://www.thisiswhyimbroke.com/images/ultimate-swiss-army-knife1.jpg)

**Comment by mickaelandrieu** [comment]
I understand your point, I just want to summarize others issues with complete and "real" uses cases to help you figure out how to solve this.

You seems to have in mind some workaround, can you please tell me about it ? I don't say Composer HAVE TO solve everything (and after a complete search, python and ruby package manager don't deal with conditional requirements), I'm just looking for a workaround.

I'm ok to make a docs pull request to help others figure out with theses issues, I just have no idea on how to solve it nicely :/

If you don't have time it's OK, but please don't close it: maybe some have ideas or workarounds...

**Comment by alcohol** [comment]
Most of this can be solved on a programming level. Your application can simply require both dependencies and then during runtime use whichever implementation is applicable.

**Comment by mmoreram** [comment]
@alcohol I'm sorry but answering "No thank you", closing the issue without any kind of explanation is not the kind of behavior any open source project should have.

Please, be polite and constructive.

**Comment by mmoreram** [comment]
About this issue, we have a prob about that because we are trying to install Elcodi in Heroku, and they only work with composer requirement blocks.

This is only a RFC, and the most weird ideas can be the most useful ones after some discussions.

**Comment by mmoreram** [comment]
BTW, I think that this idea is not the best approach. Keeping composer as simple as possible is one of the things the project should work for.

Thanks @mickaelandrieu for the proposal :)

**Comment by alcohol** [comment]
@mmoreram If someone says "no thank you", maybe they just literally mean "no thank you"? I don't see how that is impolite.

**Comment by mmoreram** [comment]
Okay, maybe the problem is that you don't see it :)

Cheers!

**Comment by mickaelandrieu** [comment]
@alcohol @mmoreram it's ok, I'm focused on the issue and I know all of you are nice guys.

The solution (for elcodi project) is probably more on the Heroku's platform side than the Composer side.

Thanks for your answers.

**Comment by alcohol** [comment]
@mmoreram Well, you're the one making a problem out of it. I was happy to provide @mickaelandrieu with a reason when he asked for it. I simply don't have the time to assume everyone needs closure. This is an open source project after all and not my day time job. We have roughly 4 people that have to deal with hundreds of issues and pull requests. So forgive me for being brief sometimes, but unless you can magically increase my productivity by a tenfold during the same timespan, I will stick to brevity rather than verbosity.
