### ISSUE TITLE
www-data can't find composer command

### ISSUE THREAD

**Issue by Schnapse** [composer/composer#4547]
Morning everyone,

I'm developing a PHP application which need to launch composer command. Unfortunately, www-data user is unable to find this command. I'm able to call this command wherever I am thanks to global aliases, but not www-data user.

Composer is successfully installed in ```/user/loca/bin/composer.phar``` and I added a global aliases in ```/etc/profile.d/00-aliases.sh``` which is ```alias composer='/usr/local/bin/composer.phar'```.  Is there a specific manipulation to do for www-data user ?

Thanks in advance.

MR.

**Comment by cs278** [comment]
Scripts in `/etc/profile.d` are only invoked for login shells. You'd be better off renaming `composer.phar` to `composer` or creating a symlink so you can use both paths.

**Comment by alcohol** [comment]
Aliases are also not a good way to make `composer` available. There are known issues related to this. It's also unlikely that `/usr/local/bin` is in the `PATH` of your **www-data** user. I recommend you move `composer` to the `bin` directory of your application.

**Comment by alcohol** [comment]
This is not a Composer issue though. This is a Linux environment issue. I suggest you study up the subject.
