### ISSUE TITLE
Composer: can't create project.

### ISSUE THREAD

**Issue by grabowskikamil** [composer/composer#4549]
Hi.

I am now studying Laravel.
I am using Windows 7 and XAMPP.

I have tried command "composer create-project laravel/laravel cats --prefer-dist". 
But I have got error as following:

[Composer\Downloader\TransportException]
  The "https://packagist.org/packages.json" file could not be downloaded: SSL
   operation failed with code 1. OpenSSL Error messages:
  error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
  Failed to enable crypto
  failed to open stream: operation failed

I have already set HTTP_PROXY and HTTPS_PROXY.
Now, How can I solve this problem?

Please help me.

Thanks.

**Comment by grabowskikamil** [comment]
I am using Composer version 1.0-dev.

**Comment by alcohol** [comment]
Most likely cause is your PHP openssl extension.

**Comment by alcohol** [comment]
This is not a Composer issue though.

**Comment by grabowskikamil** [comment]
Then how can I fix it?

**Comment by alcohol** [comment]
Update your php installation, recompile the extension, develop in a virtualbox image with an operating system more suitable for development, or Google for a solution.

Take your pick.

**Comment by grabowskikamil** [comment]
now my openssl version is as following:
OpenSSL support  -> enabled
OpenSSL Library Version -> OpenSSL 1.0.1l Jan 2015
OpenSSL Header Version -> OpenSSL 1.0.1m 19 Mar 2015

any other upgrade is needed?

**Comment by alcohol** [comment]
Maybe you have a proxy or a firewall in between that does something weird. Still not a Composer issue.
