### ISSUE TITLE
Updating a single package on an outdated composer.lock leads to misleading errors

### ISSUE THREAD

**Issue by vdespa** [composer/composer#4550]
## Description

Prerequisite: The lock file is not up to date with composer.json (outdated dependencies)

Updating just a package fails with unexpected error:

    composer update vendor/package

Your requirements could not be resolved to an installable set of packages.

Example errors:

 - The requested package phpunit/phpunit == 4.5.0.0 could not be found.

Basically it appends one 0 to the required version and fails to find it. Composer mysteriously appends 0 to package version.

## Expected result:

composer update vendor/package should graciously fail with a more human readable error.  

## Replicating the error

1. composer.json

	{
	    "require": {
	        "phpunit/phpunit": "4.5.0",
	        "justinrainbow/json-schema": "1.4.3"
	    },
	    "minimum-stability": "stable"
	}
2. composer install (runs without any errors)

3. manually modify the  composer.json and "phpunit/phpunit" to  "4.6.0"

4. run 

    composer update justinrainbow/json-schema

5. Will get the error

  Problem 1
    - The requested package phpunit/phpunit == 4.5.0.0 could not be found.

Who requested phpunit/phpunit with the version 4.5.0.0 ?

**Comment by alcohol** [comment]
Your scenario does not make sense. We cannot prevent people from doing things that don't make sense.

As for the version number, internally all versions are normalized to a a.b.c.d format.

**Comment by vdespa** [comment]
Thanks for your quick reply. I agree, manually running the above steps do not make sense. I presented a way to replicate it, not a real-life scenario. 

My scenario is much more complex and there is no need to explain the whole thing (basically multiple jobs interested in updating a dependency inside a larger project). Anyway, after looking into this for a couple of hours and not understanding the error messages composer was throwing, I guessed it would be a good idea to send you a bug report. 

If you do not see it as a bug, no problem. Thanks for composer and keep up the good job.

**Comment by alcohol** [comment]
I think you might be running into the issue where you need to run `composer update vendor/package1 vendor/package2 vendor/packageEtc --with-dependencies`. 

I could be mistaken though.

**Comment by vdespa** [comment]
Yes, the place where I had this error was indeed executed --with-dependencies, but upon testing the command, it presented the same error even without using --with-dependencies.

**Comment by alcohol** [comment]
Oh, I actually meant that using `--with-dependencies` might solve it. But if you were already using it, then I was wrong. I cannot really provide alternative suggestions as the scenario described above is simply wrong/broken. If you can give me the full gist of your real use-case scenario maybe I can comment further.
