### ISSUE TITLE
Update GitBitbucketDriver

### ISSUE THREAD

**Issue by alcohol** [composer/composer#4552]
The `Composer\Repository\Vcs\GitBitbucketDriver` class should probably be refactored to make use of the Bitbucket API version 2.0 where possible/applicable instead of version 1.0.

Relevant:
[src/Composer/Repository/Vcs/GitBitbucketDriver.php](/composer/composer/blob/master/src/Composer/Repository/Vcs/GitBitbucketDriver.php)
https://confluence.atlassian.com/bitbucket/version-2-423626329.html

**Comment by stof** [comment]
@alcohol the link to the source is broken

**Comment by stof** [comment]
I don't see anything in the v2 API allowing to get the list of tags or branches of a repo (and this is almost everything we use), making it impossible to migrate for now

**Comment by alcohol** [comment]
Forgot a leading slash, my bad.

**Comment by alcohol** [comment]
You are correct though. They've only deprecated a bunch of calls we don't use so far.
