### ISSUE TITLE
Deprecation Notice when running composer update

### ISSUE THREAD

**Issue by DestructionOfPlanetJupiter** [composer/composer#4555]
```
Deprecation Notice: The Composer\Package\LinkConstraint\VersionConstraint class is deprecated, 
use Composer\Semver\Constraint\Constraint instead. 
in phar:///var/www/w/yyy/composer.phar/src/Composer/Package/LinkConstraint/VersionConstraint.php:17
Deprecation Notice: The Composer\Package\LinkConstraint\LinkConstraintInterface interface is deprecated, 
use Composer\Semver\Constraint\ConstraintInterface instead. 
in phar:///var/www/w/yyy/composer.phar/src/Composer/Package/LinkConstraint/LinkConstraintInterface.php:17
```
Is this something I should worry about? 
How do I get rid of it?

**Comment by xabbuh** [comment]
Please run the command with `-vvv` again and paste the output here.

**Comment by DestructionOfPlanetJupiter** [comment]
Reading ./composer.json
Loading config file ./composer.json
Executing command (/var/www/w/yyy): git describe --exact-match --tags
Executing command (/var/www/w/yyy): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /home/someuser/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Loading plugin Wikimedia\Composer\MergePlugin
> pre-update-cmd: ComposerHookHandler::onPreUpdate
Deprecation Notice: The Composer\Package\LinkConstraint\VersionConstraint class is deprecated, use Composer\Semver\Constraint\Constraint instead. in phar:///var/www/w/yyy/composer.phar/src/Composer/Package/LinkConstraint/VersionConstraint.php:17
Stack trace:
 phar:///var/www/w/yyy/composer.phar/vendor/composer/ClassLoader.php:412
 phar:///var/www/w/yyy/composer.phar/vendor/composer/ClassLoader.php:301
 /var/www/w/yyy/includes/composer/ComposerPackageModifier.php:53
 /var/www/w/yyy/includes/composer/ComposerPackageModifier.php:36
 /var/www/w/yyy/includes/composer/ComposerPackageModifier.php:28
 /var/www/w/yyy/includes/composer/ComposerHookHandler.php:33
 /var/www/w/yyy/includes/composer/ComposerHookHandler.php:16
 phar:///var/www/w/yyy/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:211
 phar:///var/www/w/yyy/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:167
 phar:///var/www/w/yyy/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:92
 phar:///var/www/w/yyy/composer.phar/src/Composer/Installer.php:196
 phar:///var/www/w/yyy/composer.phar/src/Composer/Command/UpdateCommand.php:143
 phar:///var/www/w/yyy/composer.phar/vendor/symfony/console/Command/Command.php:256
 phar:///var/www/w/yyy/composer.phar/vendor/symfony/console/Application.php:838
 phar:///var/www/w/yyy/composer.phar/vendor/symfony/console/Application.php:189
 phar:///var/www/w/yyy/composer.phar/src/Composer/Console/Application.php:147
 phar:///var/www/w/yyy/composer.phar/vendor/symfony/console/Application.php:120
 phar:///var/www/w/yyy/composer.phar/src/Composer/Console/Application.php:82
 phar:///var/www/w/yyy/composer.phar/bin/composer:43
 /var/www/w/yyy/composer.phar:25
Deprecation Notice: The Composer\Package\LinkConstraint\LinkConstraintInterface interface is deprecated, use Composer\Semver\Constraint\ConstraintInterface instead. in phar:///var/www/w/yyy/composer.phar/src/Composer/Package/LinkConstraint/LinkConstraintInterface.php:17
Stack trace:
 phar:///var/www/w/yyy/composer.phar/vendor/composer/ClassLoader.php:412
 phar:///var/www/w/yyy/composer.phar/vendor/composer/ClassLoader.php:301
 phar:///var/www/w/yyy/composer.phar/src/Composer/Package/LinkConstraint/VersionConstraint.php:23
 phar:///var/www/w/yyy/composer.phar/vendor/composer/ClassLoader.php:412
 phar:///var/www/w/yyy/composer.phar/vendor/composer/ClassLoader.php:301
 /var/www/w/yyy/includes/composer/ComposerPackageModifier.php:53
 /var/www/w/yyy/includes/composer/ComposerPackageModifier.php:36
 /var/www/w/yyy/includes/composer/ComposerPackageModifier.php:28
 /var/www/w/yyy/includes/composer/ComposerHookHandler.php:33
 /var/www/w/yyy/includes/composer/ComposerHookHandler.php:16
 phar:///var/www/w/yyy/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:211
 phar:///var/www/w/yyy/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:167
 phar:///var/www/w/yyy/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:92
 phar:///var/www/w/yyy/composer.phar/src/Composer/Installer.php:196
 phar:///var/www/w/yyy/composer.phar/src/Composer/Command/UpdateCommand.php:143
 phar:///var/www/w/yyy/composer.phar/vendor/symfony/console/Command/Command.php:256
 phar:///var/www/w/yyy/composer.phar/vendor/symfony/console/Application.php:838
 phar:///var/www/w/yyy/composer.phar/vendor/symfony/console/Application.php:189
 phar:///var/www/w/yyy/composer.phar/src/Composer/Console/Application.php:147
 phar:///var/www/w/yyy/composer.phar/vendor/symfony/console/Application.php:120
 phar:///var/www/w/yyy/composer.phar/src/Composer/Console/Application.php:82
 phar:///var/www/w/yyy/composer.phar/bin/composer:43
 /var/www/w/yyy/composer.phar:25
Loading composer repositories with package information
Downloading https://packagist.org/packages.json
Writing /home/someuser/.composer/cache/repo/https---packagist.org/packages.json into cache
Updating dependencies (including require-dev)
Reading /home/someuser/.composer/cache/repo/https---packagist.org/p-provider-2013.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/p-provider-2014.json from cache
Downloading http://packagist.org/p/provider-2015-01%2491ae59c6f59e46ed5fed6fabab242db635a3d359d0aee3eaffaddf7eb665f546.json
Writing /home/someuser/.composer/cache/repo/https---packagist.org/p-provider-2015-01.json into cache
Downloading http://packagist.org/p/provider-2015-04%24aa468bbc3422a4ed3dcfae73e9442cff7d666c84528e19b32b2d11f836762433.json
Writing /home/someuser/.composer/cache/repo/https---packagist.org/p-provider-2015-04.json into cache
Downloading http://packagist.org/p/provider-2015-07%24f501e05499b3508afc3b2a0494bd263271f7d7f3db9aefecab00c370442625c6.json
Writing /home/someuser/.composer/cache/repo/https---packagist.org/p-provider-2015-07.json into cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/p-provider-2015-10.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/p-provider-archived.json from cache
Downloading http://packagist.org/p/provider-latest%245dc921feaff35af6b07f053c6a0ac3b5f0a137006099e9532127735fe052f79f.json
Writing /home/someuser/.composer/cache/repo/https---packagist.org/p-provider-latest.json into cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-wikimedia$composer-merge-plugin.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-cssjanus$cssjanus.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-leafo$lessphp.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-liuggio$statsd-php-client.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-oojs$oojs-ui.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-psr$log.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-wikimedia$cdb.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-wikimedia$utfnormal.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-zordius$lightncandy.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-composer$installers.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-onoi$event-dispatcher.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-onoi$cache.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-onoi$message-reporter.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-serialization$serialization.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-data-values$interfaces.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-data-values$data-values.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-data-values$validators.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-data-values$common.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-param-processor$param-processor.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-mediawiki$validator.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-data-values$geo.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-squizlabs$php-codesniffer.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-mediawiki$mediawiki-codesniffer.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-jakub-onderka$php-parallel-lint.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-phpunit$php-text-template.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-phpunit$php-timer.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-phpunit$php-file-iterator.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-phpunit$phpunit-mock-objects.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-phpunit$php-token-stream.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-phpunit$php-code-coverage.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-symfony$yaml.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-phpunit$phpunit.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-justinrainbow$json-schema.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-twitter$bootstrap.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-less.php$less.php.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-mediawiki$bootstrap.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-mediawiki$chameleon-skin.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-monolog$monolog.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-onoi$callback-container.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-onoi$http-request.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-onoi$blob-store.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-mediawiki$parser-hooks.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-mediawiki$semantic-media-wiki.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-mediawiki$core.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-oyejorge$less.php.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-roundcube$plugin-installer.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-shama$baton.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-mediawiki$data-values.json from cache
Reading /home/someuser/.composer/cache/repo/https---packagist.org/provider-mediawiki$semantic-mediawiki.json from cache
Analyzed 1259 packages to resolve dependencies
Analyzed 9916 rules to resolve dependencies
Nothing to install or update
Reading ./composer.lock
Generating optimized autoload files
Warning: Ambiguous class resolution, "lessc" was found in both "/var/www/w/yyy/vendor/leafo/lessphp/lessc.inc.php" and "/var/www/w/yyy/vendor/less.php/less.php/lessc.inc.php", the first will be used.

**Comment by xabbuh** [comment]
Looks like you should update your `ComposerPackageModifier.php` file. This is no serious issue as Composer will still work as before but adapting the changes from the Composer API makes your code forward compatible.

**Comment by DestructionOfPlanetJupiter** [comment]
And how do I update this file?

**Comment by xabbuh** [comment]
As the message states you should use the `Composer\Semver\Constraint\Constraint` class instead of `Composer\Package\LinkConstraint\VersionConstraint`.

**Comment by DestructionOfPlanetJupiter** [comment]
Yes, I have read this ... but can I do this with a terminal command or is it in an entry in the vendor folder?

**Comment by xabbuh** [comment]
I don't understand your question. The `/var/www/w/yyy/includes/composer/ComposerPackageModifier.php` file is part of your project, isn't it? So you can simply edit its contents.

**Comment by DestructionOfPlanetJupiter** [comment]
Yes, was actually quite easy. Have changed added a ```use Composer\Semver\Constraint\Constraint``` and edited the instantiation. 

I an quite tired, so I did not look that much at the error code ... it had been a long day. 

Can be closed.

**Comment by xabbuh** [comment]
@DestructionOfPlanetJupiter You can close this yourself as you opened it. :)

**Comment by dereuromark** [comment]
I also get

```
Deprecation Notice: The Composer\Package\LinkConstraint\MultiConstraint class is deprecated, use Composer\Semver\Constraint\MultiConstraint instead. in phar:///var/www/site/composer.phar/src/Composer/Package/LinkConstraint/MultiConstraint.php:17
Deprecation Notice: The Composer\Package\LinkConstraint\LinkConstraintInterface interface is deprecated, use Composer\Semver\Constraint\ConstraintInterface instead. in phar:///var/www/site/composer.phar/src/Composer/Package/LinkConstraint/LinkConstraintInterface.php:17
Deprecation Notice: The Composer\Package\LinkConstraint\VersionConstraint class is deprecated, use Composer\Semver\Constraint\Constraint instead. in phar:///var/www/site/composer.phar/src/Composer/Package/LinkConstraint/VersionConstraint.php:17
```
now when using the phar file (updated via selfupdate to latest available version).

**Comment by xabbuh** [comment]
@dereuromark And what is the output when running it with `-vvv`?

**Comment by dereuromark** [comment]
```
Deprecation Notice: The Composer\Package\LinkConstraint\MultiConstraint class is deprecated, use Composer\Semver\Constraint\MultiConstraint instead. in phar:///var/www/site/composer.phar/src/Composer/Package/LinkConstraint/MultiConstraint.php:17
Stack trace:
 phar:///var/www/site/composer.phar/vendor/composer/ClassLoader.php:412
 phar:///var/www/site/composer.phar/vendor/composer/ClassLoader.php:301
 /var/www/site/Vendor/composer/installers/src/Composer/Installers/CakePHPInstaller.php:61
 /var/www/site/Vendor/composer/installers/src/Composer/Installers/CakePHPInstaller.php:40
 /var/www/site/Vendor/composer/installers/src/Composer/Installers/Installer.php:157
 /var/www/site/Vendor/composer/installers/src/Composer/Installers/Installer.php:116
 phar:///var/www/site/composer.phar/src/Composer/Installer/InstallationManager.php:105
 phar:///var/www/site/composer.phar/src/Composer/Installer/InstallationManager.php:127
 phar:///var/www/site/composer.phar/src/Composer/Factory.php:471
 phar:///var/www/site/composer.phar/src/Composer/Factory.php:301
 phar:///var/www/site/composer.phar/src/Composer/Factory.php:488
 phar:///var/www/site/composer.phar/src/Composer/Command/ValidateCommand.php:89
 phar:///var/www/site/composer.phar/vendor/symfony/console/Command/Command.php:256
 phar:///var/www/site/composer.phar/vendor/symfony/console/Application.php:838
 phar:///var/www/site/composer.phar/vendor/symfony/console/Application.php:189
 phar:///var/www/site/composer.phar/src/Composer/Console/Application.php:147
 phar:///var/www/site/composer.phar/vendor/symfony/console/Application.php:120
 phar:///var/www/site/composer.phar/src/Composer/Console/Application.php:82
 phar:///var/www/site/composer.phar/bin/composer:43
 /var/www/site/composer.phar:25
Deprecation Notice: The Composer\Package\LinkConstraint\LinkConstraintInterface interface is deprecated, use Composer\Semver\Constraint\ConstraintInterface instead. in phar:///var/www/site/composer.phar/src/Composer/Package/LinkConstraint/LinkConstraintInterface.php:17
Stack trace:
 phar:///var/www/site/composer.phar/vendor/composer/ClassLoader.php:412
 phar:///var/www/site/composer.phar/vendor/composer/ClassLoader.php:301
 phar:///var/www/site/composer.phar/src/Composer/Package/LinkConstraint/MultiConstraint.php:23
 phar:///var/www/site/composer.phar/vendor/composer/ClassLoader.php:412
 phar:///var/www/site/composer.phar/vendor/composer/ClassLoader.php:301
 /var/www/site/Vendor/composer/installers/src/Composer/Installers/CakePHPInstaller.php:61
 /var/www/site/Vendor/composer/installers/src/Composer/Installers/CakePHPInstaller.php:40
 /var/www/site/Vendor/composer/installers/src/Composer/Installers/Installer.php:157
 /var/www/site/Vendor/composer/installers/src/Composer/Installers/Installer.php:116
 phar:///var/www/site/composer.phar/src/Composer/Installer/InstallationManager.php:105
 phar:///var/www/site/composer.phar/src/Composer/Installer/InstallationManager.php:127
 phar:///var/www/site/composer.phar/src/Composer/Factory.php:471
 phar:///var/www/site/composer.phar/src/Composer/Factory.php:301
 phar:///var/www/site/composer.phar/src/Composer/Factory.php:488
 phar:///var/www/site/composer.phar/src/Composer/Command/ValidateCommand.php:89
 phar:///var/www/site/composer.phar/vendor/symfony/console/Command/Command.php:256
 phar:///var/www/site/composer.phar/vendor/symfony/console/Application.php:838
 phar:///var/www/site/composer.phar/vendor/symfony/console/Application.php:189
 phar:///var/www/site/composer.phar/src/Composer/Console/Application.php:147
 phar:///var/www/site/composer.phar/vendor/symfony/console/Application.php:120
 phar:///var/www/site/composer.phar/src/Composer/Console/Application.php:82
 phar:///var/www/site/composer.phar/bin/composer:43
 /var/www/site/composer.phar:25
Deprecation Notice: The Composer\Package\LinkConstraint\VersionConstraint class is deprecated, use Composer\Semver\Constraint\Constraint instead. in phar:///var/www/site/composer.phar/src/Composer/Package/LinkConstraint/VersionConstraint.php:17
Stack trace:
 phar:///var/www/site/composer.phar/vendor/composer/ClassLoader.php:412
 phar:///var/www/site/composer.phar/vendor/composer/ClassLoader.php:301
 /var/www/site/Vendor/composer/installers/src/Composer/Installers/CakePHPInstaller.php:62
 /var/www/site/Vendor/composer/installers/src/Composer/Installers/CakePHPInstaller.php:40
 /var/www/site/Vendor/composer/installers/src/Composer/Installers/Installer.php:157
 /var/www/site/Vendor/composer/installers/src/Composer/Installers/Installer.php:116
 phar:///var/www/site/composer.phar/src/Composer/Installer/InstallationManager.php:105
 phar:///var/www/site/composer.phar/src/Composer/Installer/InstallationManager.php:127
 phar:///var/www/site/composer.phar/src/Composer/Factory.php:471
 phar:///var/www/site/composer.phar/src/Composer/Factory.php:301
 phar:///var/www/site/composer.phar/src/Composer/Factory.php:488
 phar:///var/www/site/composer.phar/src/Composer/Command/ValidateCommand.php:89
 phar:///var/www/site/composer.phar/vendor/symfony/console/Command/Command.php:256
 phar:///var/www/site/composer.phar/vendor/symfony/console/Application.php:838
 phar:///var/www/site/composer.phar/vendor/symfony/console/Application.php:189
 phar:///var/www/site/composer.phar/src/Composer/Console/Application.php:147
 phar:///var/www/site/composer.phar/vendor/symfony/console/Application.php:120
 phar:///var/www/site/composer.phar/src/Composer/Console/Application.php:82
 phar:///var/www/site/composer.phar/bin/composer:43
 /var/www/site/composer.phar:25

```

**Comment by Seldaek** [comment]
@dereuromark that was an issue in composer/installers. I tagged a new release fixing that.
