### ISSUE TITLE
composer install fails on class map

### ISSUE THREAD

**Issue by DQNEO** [composer/composer#4557]
Hi, I found a RuntimeException on composer instsall

```
Composer version 1.0-dev (c557715669ba8dd2dc6c63859f919351a4aa5e2f) 2015-10-28 14:13:03
```

composer.json

```
{
  "require": {
    "predis/predis": "v0.8.5"
  },
  "autoload": {
    "classmap": [
      "vendor/predis/predis/Predis.php"
    ]
  }
}
```

`composer install` fails
```
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing predis/predis (v0.8.5)
    Loading from cache

predis/predis suggests installing ext-phpiredis (Allows faster serialization and deserialization of the Redis protocol)
Writing lock file
Generating autoload files



  [RuntimeException]
  Could not scan for classes inside "vendor/predis/predis/Predis.php" which does not appear to be a file nor a folder
```

# Environment
* OSX  10.10.5  PHP 7.0.0RC3
* CentOS 6.7 PHP 5.6.14

**Comment by alcohol** [comment]
No, this is a PEBKAC error. Classmap accepts one or multiple directories as argument. You are specifying a file. I wonder what could be wrong there..?

**Comment by DQNEO** [comment]
Thank you for the quick response.

But in the document, 
https://getcomposer.org/doc/04-schema.md#classmap

> You can use the classmap generation support to define autoloading for all libraries that do not follow  PSR-0/4. To configure this you specify all directories or files to search for classes.
> Example:
```
{
    "autoload": {
        "classmap": ["src/", "lib/", "Something.php"]
    }
}
```

they say classmap can take files as arguments, right?

**Comment by alcohol** [comment]
Yes but the file has to exist. If you had taken the time to look inside `vendor/predis/predis/` you would see that this is not the case.

Also, why on earth are you adding a classmap for one of your dependencies? Your dependency already specifies the correct autoload rules.

If you specify it manually, then you need to update it every time the library changes or renames files/paths.

**Comment by DQNEO** [comment]
> Yes but the file has to exist. If you had taken the time to look inside vendor/predis/predis/ you would see that this is not the case.

Sorry, my example above is bad.
I created a repo which we can reproduce this issue easily. 
https://github.com/DQNEO/composer-exception

**Comment by alcohol** [comment]
I'm sorry but none of that makes any sense. I don't know what you are doing or why you are doing it, but it is a waste of my time and I have nothing further to contribute.

**Comment by alcohol** [comment]
https://github.com/nrk/predis/tree/v0.8.5

As you can see, tag 0.8.5 does not have a file called "Predis.php" in the root directory (which would be `vendor/predis/predis/` when installed by composer). So the error composer returns is completely valid. You have a file in your classmap that does not exist.

**Comment by DQNEO** [comment]
OK , thanks anyway.
I see.
