### ISSUE TITLE
Escaping of output styles in commit messages

### ISSUE THREAD

**Issue by xelan** [composer/composer#4558]
When composer shows the commit messages for installed or updated dependencies, output style tags (e.g. `<info>`, `<error>`, ...) appearing in the text are not escaped properly.

Example: When doctrine/migrations is updated, the commit https://github.com/doctrine/migrations/commit/93a81ff0dcc858de4df5c17d97f2f24b3bfa3c36 causes the rest of the output to have the comment style.

![style-escaping-example](https://cloud.githubusercontent.com/assets/5080535/10812380/d2f91bca-7e15-11e5-9fb9-5a1650f6a9aa.png)

**Comment by alcohol** [comment]
Please don't only share screenshots. Copy and paste the full output of the command you were running in `-vvv` mode, otherwise we cannot assist you.

**Comment by xelan** [comment]
The text output doesn't make sense here, as it doesn't contain the color which is the problem!
You can reproduce the issue by creating a composer.json with a old version of doctrine/migrations as requirement, then updating it.
