### ISSUE TITLE
~ version problems

### ISSUE THREAD

**Issue by ivol84** [composer/composer#4561]
One dependency(https://github.com/wsdl2phpgenerator/wsdl2phpgenerator) from my project requires "symfony/option-resolver" : "~2.6". But composer install 2.7.6 version.  
Also I clone wsdl2phpgenerator. After I made composer install and got 2.7.6 version of option-resolver.

**Comment by alcohol** [comment]
`~2.6` allows `2.7.6`.

https://getcomposer.org/doc/articles/versions.md#tilde
