### ISSUE TITLE
Autoload creation issues

### ISSUE THREAD

**Issue by AndreasA** [composer/composer#4562]
Since the commit 1160b782c80b3243ab8fb8a1b02f6cb67741fd4b (Deduplicate classmap creation and add support for loading classmaps ...)

there is an issue with autoload generation.

It seems that autoload is trying to be generated now prior to any installation which might fail if you install packages (via tar etc.) and want to have the autoload be executed afterwards (could include autoload section in packages part but would be easier otherwise).

Futerhermore, --no-autoloader still tries to execute autoload at the beginning because I get the same error "could not scan".

**Comment by alcohol** [comment]
I'm sorry, can you be a bit more elaborate, steps to reproduce perhaps?

**Comment by alcohol** [comment]
I think I understand your issue; https://github.com/composer/composer/commit/1160b782c80b3243ab8fb8a1b02f6cb67741fd4b#commitcomment-14066769

Is my assumption correct?

**Comment by alcohol** [comment]
It would still help to have a log output of a command running in `-vvv` thats shows this specific issue.

**Comment by AndreasA** [comment]
Let's say I have the following composer.json:
```json
"repositories": [
		{
			"package": {
				"name": "typo3-ter/static-info-tables",
				"version": "dev-master",
				"type": "typo3-cms-extension",
				"replace": {
					"static_info_tables": "*"
				},
				"source": {
					"reference": "master",
					"type": "git",
					"url": "git://git.typo3.org/TYPO3CMS/Extensions/static_info_tables.git"
				}
			},
			"type": "package"
		}
],
"require": {
		"typo3/cms": "dev-master#671d0b70e737fa96a4e1526b7c90b87061ab61df",
		"typo3-ter/tt-address": "dev-master#26baa2897457a60a9d3ff92964a71bd53a1f36c2"
},
"autoload": {
	"classmap": [
		"typo3conf/ext/tt_address/pi1/"
	]
}
```
Now composer fails with at the beginning:
```text
[RuntimeException]                                                                                                 
Could not scan for classes inside "typo3conf/ext/tt_address/pi1/" which does not appear to be a file nor a folder.
```
Because autoload is now loaded before the package is installed.

However, even if that might be OK, it even fails with the same message when calling
```shell
composer install --no-autoloader
```

**Comment by alcohol** [comment]
But that composer.json makes no sense. The autoload definition should be inside the package definition. Can you re-try that?

Also, I asked for a full `-vvv` output of the command you are running. I still don't see any.

**Comment by AndreasA** [comment]
Log output:
```
composer install -vvv
Reading ./composer.json
Loading config file /home/andreas/.composer/config.json
Loading config file /home/andreas/.composer/auth.json
Loading config file ./composer.json
Reading /home/andreas/.composer/composer.json
Loading config file /home/andreas/.composer/config.json
Loading config file /home/andreas/.composer/auth.json
Loading config file /home/andreas/.composer/composer.json
Loading config file /home/andreas/.composer/auth.json
Executing command (/home/andreas/apache/www/wienxtra-typo3): git describe --exact-match --tags
Executing command (/home/andreas/apache/www/wienxtra-typo3): git branch --no-color --no-abbrev -v


                                                                                                                     
  [RuntimeException]                                                                                                 
  Could not scan for classes inside "typo3conf/ext/tt_address/pi1/" which does not appear to be a file nor a folder  
                                                                                                                     


Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:68
 Composer\Autoload\ClassMapGenerator::createMap() at phar:///usr/local/bin/composer/src/Composer/Autoload/AutoloadGenerator.php:299
 Composer\Autoload\AutoloadGenerator->generateClassMap() at phar:///usr/local/bin/composer/src/Composer/Autoload/AutoloadGenerator.php:393
 Composer\Autoload\AutoloadGenerator->createLoader() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:349
 Composer\EventDispatcher\EventDispatcher->getScriptListeners() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:300
 Composer\EventDispatcher\EventDispatcher->getListeners() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:146
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:92
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar:///usr/local/bin/composer/src/Composer/Installer.php:196
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php:134
 Composer\Command\InstallCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:838
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:147
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:82
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:25


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...
```

**Comment by AndreasA** [comment]
Even if it makes no sense. It worked fine prior.
Also it should at aleast work with --no-autoloader because autoload shouldn't be called at all, shouldn't it?

**Comment by AndreasA** [comment]
But I guess it should work if I do this:
```
"package": {
				"name": "typo3-ter/tt-address",
				"replace": {
					"tt_address": "*"
				},
				"source": {
					"reference": "master",
					"type": "git",
					"url": "git://git.typo3.org/TYPO3CMS/Extensions/tt_address.git"
				},
				"type": "typo3-cms-extension",
				"version": "dev-master",
				"autoload": {
				  "classmap": [
					"pi1/"
				  ]
				}
			}
```

Will modify it accordingly because it makes more sense that way anyway but I still think that at least "--no-autoloader" should have worked previously too.

**Comment by alcohol** [comment]
Sometimes, just because things "worked" before, does not mean that you're doing things the right way. Even if we revert the change, it does not change the fact that your configuration is simply put, wrong.

I'm investigating the issue though, but so far have been unable to reproduce it myself. But I don't use broken configuration to reproduce it, because I don't intend to support broken configuration. If you can give me a proper example that should work properly but fails, I would appreciate that.

The flag `--no-autoloader` simply means it will not generate an autoloader. It's unrelated to the functionality that is causing this issue though.

**Comment by alcohol** [comment]
Do you have any plugins installed or script definitions in your composer.json?

**Comment by AndreasA** [comment]
Ah, OK. I thought it will bypass the whole autoloading scanning too?

But if I move the autoload above to repositories it seems to work.
The only issue might be if one uses a git repository with a composer.json, so only the url and that composer.json is missing the autoload section.
But then again as the composer.json is buggy it makes more sense to use repository in the way above anyway.

**Comment by AndreasA** [comment]
Just to let you know using this:
```
"package": {
                "name": "typo3-ter/tt-address",
                "replace": {
                    "tt_address": "*"
                },
                "source": {
                    "reference": "master",
                    "type": "git",
                    "url": "git://git.typo3.org/TYPO3CMS/Extensions/tt_address.git"
                },
                "type": "typo3-cms-extension",
                "version": "dev-master",
                "autoload": {
                  "classmap": [
                    "pi1/"
                  ]
                }
            }
```
in the repositories section works as expected.

**Comment by alcohol** [comment]
If you use a repository of type git with a url to a repository, and that repository contains a composer.json, you just put the autoload definition in that composer.json.

**Comment by alcohol** [comment]
Can you please answer my question regarding plugins or scripts.

**Comment by AndreasA** [comment]
Yes. there are scripts.
It works without using scripts.

**Comment by alcohol** [comment]
Thought so. It creates an autoloader when you have scripts, because they might use classes that could be loaded from your autoload definitions. This happens before it starts installing anything. Your root package autoload definitions should always belong to your root package files only.

**Comment by AndreasA** [comment]
It kind of makes sense but only if you have pre script things :)

**Comment by alcohol** [comment]
Thanks for reporting it. This is a bit of an edge-case that probably will not happen often. We should still deal with it on Composer's side as well. Not sure yet what the best answer is though. Will discuss with @Seldaek .

**Comment by Seldaek** [comment]
As far as I know the autoloader generated on the fly is done only for
packages that are installed fully so I'm thinking the code is fine as is,
it just means you can't have an autoload rule that points inside one of
your dependencies' folder. I'm not sure if that's a valid use case under
some circumstances. If so  we could just check for dir existence before
scanning in the on the fly loader creation but not in the dumping process.
I'd say let's wait and see if anyone comes up with such an issue and has a
legitimate use case.

**Comment by nelsonko** [comment]
I am facing the same issue. How would I set a autoload rule that points inside one of the folders created through "require"?

For example

    "require": {
        ...
        "adodb/adodb": "5.18",
        "smarty/smarty": "3.1.21",
        ...
    }
    "autoload": {
        ...
        "classmap": [
            "vendor/adodb/adodb/",
            "vendor/smarty/smarty/libs/sysplugins/smarty_security.php"
        ]
        ...
    }

**Comment by alcohol** [comment]
@nelsonko you don't have to. `adodb/adodb-php` (did you spell the package-name wrong, cause I couldn't find the one you mentioned) has an autoload definition in its composer.json so it should work properly out of the box.

**Comment by CyExy** [comment]
@Seldaek @alcohol I'm having a similar problem with autoload, and a legitimate use case. We have a `pre-autoload-dump` script that replaces temporary packages in vendor with symlinks to real sources to allow local packages in a single git repository. More details can be found here https://github.com/mybuilder/conductor

**Comment by CyExy** [comment]
I think I should have created a new ticket, but I'll wait for your response. But in short `pre-autoload-dump` scripts are not runned before `Generating autoload files`. Tried both `composer install` and `composer dumpautoload`

**Comment by alcohol** [comment]
Sorry, your use-case is not something directly supported by Composer.

You should probably also look into using the `path` repository type.

**Comment by CyExy** [comment]
@alcohol `pre-autoload-dump` should be runned pre autoload not post.

**Comment by alcohol** [comment]
What makes you think it is not running pre, but post?

**Comment by CyExy** [comment]
Because it doesn't run the script pre autoload.

**Comment by alcohol** [comment]
Based on what?

**Comment by CyExy** [comment]
Ok, I'll create a simple repo demonstrating it, I might be wrong but even the `-vvv` output indicates that

```
...
Generating autoload files
> pre-autoload-dump: ../../bin/conductor symlink -c ../..
Executing command (CWD): ../../bin/conductor symlink -c ../..
...
```

**Comment by alcohol** [comment]
The output indicates nothing specifically, it's just output.

The first thing the dumper does is run the pre- scripts, [see here](https://github.com/composer/composer/blob/2e4157145b59a02e92b0ee1f85a382ba870c7839/src/Composer/Autoload/AutoloadGenerator.php#L79-L81).

**Comment by CyExy** [comment]
So this doesn't work:

```json
{
    "name": "sten/autoload",
    "autoload": {
        "classmap": [
            "Foo.php"
        ]
    },
    "scripts": {
        "pre-autoload-dump": [
            "echo '<?php class Foo {}' > Foo.php"
        ],
        "post-autoload-dump": [
            "rm Foo.php"
        ]
    }
}
```

Add the Foo.php manually and it works, run `composer install --no-autoloader` works again.

**Comment by CyExy** [comment]
I can run bisect on composer if you like to pinpoint the commit that caused it.

**Comment by alcohol** [comment]
You misunderstand what is going wrong though. Because you have a `script` definition, composer already instantiates an autoloader before doing anything else at all, because the `scripts` can contain references to classes that belong to your root package. If `Foo.php` does not exist yet at that point, it will throw an error. That error is completely unrelated to autoload generation/dumping, and only related to the classloader that is being instantiated for the scripts section.

**Comment by CyExy** [comment]
The changeset that broke it is this https://github.com/composer/composer/commit/1160b782c80b3243ab8fb8a1b02f6cb67741fd4b

So what you are saying is that having `autoload: "classmap"` should change the `pre-autoload-dump` behaviour because if you take out the `classmap` from autoload it works. Looks like a accidental bug to me.

So https://github.com/composer/composer/commit/1160b782c80b3243ab8fb8a1b02f6cb67741fd4b#diff-33037407f7f293f37df2258567b56598R391 should then at least ignore unreachable files.

**Comment by alcohol** [comment]
It's not broken. Please read my comments.

**Comment by CyExy** [comment]
Ok, you are saying that composer does a "preflight" instance of `ClassLoader` in case the `scripts` contain a reference to a class within the project, regardless which script this is, e.g. `pre-install-cmd` would have the same problem. I understand that, and it makes sense for plugins and scripts.

Am I right that the "preflight" autoloader is not used for the final autoload dump?

The only one that has this problem is `classmap` by nature `psr-4` and `psr-0` does not share this issue. Adding a `file_exists($dir)` filter to the "preflight" before `addClassMap` shouldn't be an issue for existing or future projects, plugins and script. And all the composer test pass after the change.

**Comment by alcohol** [comment]
1. I guess that is sort of an accurate statement. Except that it doesn't matter what `scripts` contains, just the mere presence of the `scripts` section will trigger this "preflight" instance as you call it.

2. Yes, you are right.

3. The problem is that we cannot do this check inside the `ClassLoader`. Because it really should be an error normally.

**Comment by CyExy** [comment]
I looked into the `path` repo type it does the same job as https://github.com/mybuilder/conductor but better so I'm going to kill this project, and therefore `conductor` wouldn't qualify as a legitimate use case.

Agree, doing it inside `ClassLoader` would be a mistake. Although changing fatal error to a warning might be a viable option. And it looks like `AutoloadGenerator::createLoader` is only used by the "preflight" autoloader, so issuing a warning if dir/file doesn't exist and not adding it to the "preflight" `ClassLoader`, but still throwing a fatal error on final dump.

I still think that generating classes on the fly is a good option to have. And `classmap` would be the only option to load generated bootstrap cache files – e.g. symfony2 `bootstrap.php.cache`. And admittedly a dying problem but legacy active record ORMs can have a problem if the base classes are generated using composer `scripts` on the fly, and when the generated classes do not conform to either `psr-4` nor `psr-0`. Although you can always add a folder that has a `.gitkeep` where the ORM dumps its base classes.
