### ISSUE TITLE
Better selection of stable version when release candidate appears

### ISSUE THREAD

**Issue by weierophinney** [composer/composer#4563]
I've experienced the following situation a few times:

- Package publishes in `0.x` versions. Requiring such packages does not require setting a stability flag (yay!).
- Package subsequently publishes a `1.0.0rc1` (or later RC) version. Requiring such packages immediately fails, indicating no stable packages are available.

This is problematic, particularly for "project" style packages, as the documentation for how to install the package then needs to change temporarily during the RC stage to indicate the `-s rc` flag is needed, and automating such changes to install instructions is problematic.

Ideally, I'd like to see one of the following:

- Given:
  - no stability flag is provided (to either `create-project` or `require`), AND
  - `0.x` versions are available, AND
  - 1 or more RC-stability packages are available
- Then:
  - composer should install the latest stable `0.x` version available, OR
  - composer should install the latest RC available.

I'm not 100% sure which makes the most sense, to be honest. I personally get irritated that I need to provide the `-s rc` flag when a package updates to RC status, as RC indicates API stability, and would thus lean in the latter direction (installing the RC version).

Ideally, the same behavior would be true for the RCs of subsequent major versions.

**Comment by alcohol** [comment]
None of the above takes into account that composer works purely based on version constraints. You haven't specified any of them. So I'm not sure what you are asking for.

**Comment by weierophinney** [comment]
@alcohol — I thought by using the `create-project` and `require` verbiage, I was being clear. Let me be explicit about my usage:

```bash
$ composer require vendor/package
# OR
$ composer create-project vendor/project
```

In such cases, you're not typically providing a version constraint; you're letting composer select the most recent stable version. Those are the scenarios that cause the problem I'm observing.

**Comment by Seldaek** [comment]
I actually changed the behavior of the version selection in https://github.com/composer/composer/commit/507415e40477c79527751fddbac21cbe617af16c so that it always picks the most stable available, so with latest composer if you have 0.1.0 and 1.0.0-rc, it'll pick 0.1.0. I think this fixes your concerns?

**Comment by alcohol** [comment]
@weierophinney Well, yes and no. Using those commands with a version specified by you, means you default to the version constraint that composer will generate. This constraint simply looks at the latest stable release. But after that, my comment still applies. If you end up with a constraint for `^0.4` for example, there is no possible way it would ever allow installing a `1.0.0-rc` candidate. Hence why I am not sure what you are asking for, so I was hoping you could clarify what exact scenario you were talking about and what the current outcome is and what your expected or desired outcome is.

**Comment by weierophinney** [comment]
@alcohol — I **have** provided those details. The `require` and `create-project` commands listed are exactly as you will find in just about any package install instructions; the point is to grab the latest stable version. As I've indicated, those instructions fail during the transition from a `0.x` version to a 1.0.0rc1 version, as composer no longer considers any packages as stable. I am specifically *not* talking about updates after a package and version constraint are already in the composer.json; I'm talking about the commands that create a project or add a requirement to the composer.json *only*. 

@Seldaek — that looks like it should work; I'll give it a try and report back in a bit.

**Comment by alcohol** [comment]
@weierophinney I'm sorry but I find your explanation incredibly confusing. I think I get the gist now, but please correct me if I am wrong (and try explaining again).

You have a package with the following (fictional) tags:

- 0.1.0
- 0.2.0
- 0.3.0
- 1.0.0rc1

In this particular scenario, running `composer require vendor/package` does not work for you because it cannot resolve a stable version constraint you say?

**Comment by Seldaek** [comment]
Yes that's what he is saying I think. Because before my patch it would have
selected the 1.0rc1, turned it into a ^1.0 constraint, and then failed to
install if you have a minimum stability of stable.

Now with the patch it should pick 0.3 and use that to create the constraint.

**Comment by weierophinney** [comment]
@alcohol and @Seldaek — yes, that's exactly the scenario. `create-project` and `require` work fine with that series of versions *until* version 1.0.0rc1 is introduced; at that moment, no stable version is found, and boom! broken!

@Seldaek — just did a `composer self-update` and executed a `create-project` on one such affected repo, and it did in fact select the last stable `0.x.y` version, which is far better than blowing up. I can live with telling folks to pass `-s rc` to opt-in to release candidates.

Thanks!

**Comment by Seldaek** [comment]
Yeah one problem left though is that we always prefer the most stable now.
-s rc won't actually help. I'm thinking we should fix that.

**Comment by Seldaek** [comment]
Ok I fixed it so now `create-project -s rc` will pick stable, or RC if it's available in a higher version!
