### ISSUE TITLE
Finding the $baseDir location for composed packages.

### ISSUE THREAD

**Issue by rquadling** [composer/composer#4565]
Hi.

If I've got a package that a user has included in their project via composer, how, in my package, can I location the ``$baseDir``? I want to use a .env file (https://github.com/vlucas/phpdotenv) and I would like to use that directory to load the .env file.

Ideally I want ``Composer::$baseDir`` (or something simple and similar). I know I could use a lot of ``dirname(__DIR__)``, but that feels hacky and means I'm not able to use the same code locally (as the package does not sit inside ``vendor`` whilst I am developing it).

**Comment by alcohol** [comment]
This is how we solved it in Composer itself (the spdx-licenses package specifically).

https://github.com/composer/spdx-licenses/blob/master/src/SpdxLicenses.php#L179

**Comment by rquadling** [comment]
Fair enough.
