### ISSUE TITLE
How to make a PHP version for developement different from the config

### ISSUE THREAD

**Issue by karimennassiri** [composer/composer#4566]
Hi,
I'm trying to install the Facebook PHP V5.* that require a version of php > 5.4 or i deploy on a server requiring a vesrion of php 5.3. What i need to know how can i merge two versions of PHP in my local development (5.3 and 5.6) environment to let the Facebook SDK work and deploying without losing my other libraries. 

Thanks

**Comment by xabbuh** [comment]
I am not sure if I completely understood your issue. Are you looking for something like the [platform](https://getcomposer.org/doc/06-config.md#platform) option?

**Comment by karimennassiri** [comment]
So if id this {"php": "5.3.26", "ext-something": "5.6.3"} so some libraries will you PHP 5.6.3 and others 5.3.26 ?

**Comment by alcohol** [comment]
It's one thing to make Composer believe you are running a different version on your development machine than you actually are. It's entirely different to deploy packages to production that do not support the PHP version you are running there. Don't do this.

**Comment by karimennassiri** [comment]
So, there's no solution to have what i need? i can do this in my local dev environment

**Comment by alcohol** [comment]
```
{
  "require": { ... },
  "config": {
    "platform": { 
      "php": "5.6.14" 
    }
  }
}
```

The above would make Composer think you are running PHP version `5.6.14`. This will let you install packages that require `>=5.4` for example. But if your system is **actually** running `5.3` in production, then this would be an incredibly risky situation as things might explode when you deploy to production.

**Comment by karimennassiri** [comment]
Yes i know that's risky but there's no way to resolve the problem

**Comment by alcohol** [comment]
Update machine or use another library.

**Comment by stof** [comment]
Well, if the Facebook SDK requires PHP 5.4+, you won't be able to deploy code using it on a server using PHP 5.3. It will simply not work. This is precisely why we have php version requirements in libraries.

The valid use case for the platform config is to force composer to know about your prod PHP version even if you have a newer one locally. But configuring it explicitly to something different than the prod version looks wrong to me.
