### ISSUE TITLE
Autoload problem with and without -o flag

### ISSUE THREAD

**Issue by ssi-anik** [composer/composer#4570]
I'm using Laravel 5.1. Under the classmap array, I've added the psr-4. 

    {
        "psr-4": {
            "Library\\": "app/Library"
        }
    }

When I run composer dump-autoload, it doesn't include thoses classes inside that dir. But added to the autoload_psr4. Then instead, if I run composer dump-autoload -o. this includes the namespaces and files on accordingly. What is the problem? Am I doing anything wrong?

**Comment by xabbuh** [comment]
That's exactly how it's supposed to work. Dumping an optimized autloader means that Composer creates the big class map to speed up the look up for classes. However, this is not really convenient, for example, during development as you would need to dump the autoloader again again everytime you add new classes. So Composer is searching your class by a defined naming strategy when you use PSR-4 (or PSR-0) autoloading and uses the registered namespace prefix to search in just a subtree of your project's filesystem.

**Comment by xabbuh** [comment]
Actually, my answer was not completely right. Adding a new class when having an optimised dumped autoloader still works as it falls back to search the registered PSR-0/PSR-4 namespaces. You just don't get the optimised lookup.

**Comment by ssi-anik** [comment]
@xabbuh Thanks. :)

**Comment by SvenRtbg** [comment]
Issue closed?

**Comment by stof** [comment]
@xabbuh there is an option to disable the fallback to PSR-0/PSR-4 file lookup though
