### ISSUE TITLE
Make --sort-packages a default?

### ISSUE THREAD

**Issue by Anahkiasen** [composer/composer#4572]
I'm very grateful for the `--sort-packages` flag, however I keep wondering why it isn't simply the default like it is in some others package managers like NPM. Sorted packages make for easier diffs while I can't think of any benefits to having randomly sorted packages besides seeing which order packages were added in (which Git can also already tell you).

Is there any argument I'm not thinking of in favor of the current behavior?

**Comment by Seldaek** [comment]
The order of packages actually matters in some cases as they are installed following that order + the dependency weight.

I for one find it clearer to have dependencies grouped in whichever way I like, and I don't really see how this makes diffs easier?

**Comment by ryanaslett** [comment]
The diffs that are hard to read is when the entire composer.lock file appears to have changes in it, because everything has been reordered, even though there was just one new package required.

**Comment by Seldaek** [comment]
@ryanaslett this is unrelated to this issue and anyway it's not an issue anymore and hasn't been for a long time as the lock file is ordered by name always. You might find it has a lot of changes if you update a very old lock file that wasn't ordered though.
