### ISSUE TITLE
composer install crashes computer

### ISSUE THREAD

**Issue by 1e4** [composer/composer#4574]
After adding a new package, I ran `composer install`, it then gave the man in the middle attack error. Restarted PC, still same issue, I then went to add/remove programs -> change -> reinstall composer.

After this I ran `composer install` again, PC then crashed. Tried 3 times, everytime is crashed everything. Not sure what debug I can give or where to get it.

Any ideas for this? Cheers

EDIT: Completely uninstalling and reinstalling seems to fix the crash however the man in the middle attack still remains

```
[Composer\Repository\RepositorySecurityException]
 The contents of http://packagist.org/p/laravel/framework%248bb9d6c2db00f3d8a067c5f3a3aa4d4a13cac1cd1ef0d3b11803c9fe9329a2d8.json do not match its signature
 . This should indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.
```

**Comment by alcohol** [comment]
You probably have a bad proxy or firewall running/in your network.

**Comment by Seldaek** [comment]
Still shouldn't crash the machine though, that's real weird :|

As an alternative, can you try to run this:

`composer config -g repos.packagist composer https://packagist.org`

This will force it to use https always for packagist, it probably will help if you have an idiotic proxy in the network as it can't mess with your https traffic. Please let us know if it helps, if so we should probably add that to the troubleshooting page.

**Comment by 1e4** [comment]
@Seldaek It's been a few months but the crash is back

composer.json

```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "laravelcollective/html": "^5.1",
        "predis/predis": "^1.0",
        "zizaco/entrust": "^1.5",
        "yajra/laravel-datatables-oracle": "^6.0",
        "barryvdh/laravel-ide-helper": "^2.1",
        "barryvdh/laravel-debugbar": "^2.1",
        "guzzlehttp/guzzle": "^6.1",
        "yaap/theme": "^2.2",
        "cviebrock/eloquent-sluggable": "^3.1",
        "rcrowe/twigbridge": "^0.9.2",
		"thujohn/twitter": "~2.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ],
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}
```

Both times when using `composer update` it caused [this](http://i.imgur.com/C4sXqrA.png), once a coincidence, but twice, when the second time the only thing running was git bash running `composer update`. It seems pretty bizarre, any ideas?

**Comment by Seldaek** [comment]
So you run update and it crashes your machine.. That is still quite unseen before (except on your machine). Let's try and stab in the dark here..

It crashes while installing or before it even installs any packages?

From https://support.microsoft.com/en-gb/kb/2028504

> This scenario usually indicates a problem with the hardware. To help isolate the problem, check the following items:
> Overclocking: Disable overclocking to see whether the issue occurs when the system is run at the correct speed.
> Check the memory: Verify the memory by using a memory checker. Verify that each memory chip is the same speed and that it is configured correctly in the system.
> Power supply: Make sure that the power supply has enough wattage to appropriately handle the installed devices. If you added memory, installed a newer processor, installed additional drives, or added external devices, such devices can require more energy than the current power supply can provide consistently.
> Overheating: Check whether the system is overheating by examining the internal temperature of the hardware.
> Defaults: Reset the system back to the system defaults to see whether the issues occur when the system is running in its default configuration. 

Wonder if overheating could be a cause, as a composer update can do some CPU intensive tasks. Could you watch the temperature with SpeedFan or something maybe? Memory check also sounds interesting, as we do use a lot of memory.

**Comment by 1e4** [comment]
It hangs almost instantly after `composer update` after it says 'Updating dependencies (including require-dev)' then it dies. So it's before it get's to downloading it seems. It happens across all projects, it's not specific to one configuration. 

Ran update, this time it didn't crash it came up with an [error](http://i.imgur.com/A5c6pwe.png). Nothing unusual about temperature, it peaked briefly at around 6% CPU usage, a few percent more than normal.

**Comment by Seldaek** [comment]
That error might be due to the crash occurring while it was writing to the cache, ending up with a corrupt cache entry? Can you try to `composer clear-cache` and then `composer update -vvv` (the -vvv should show you what it's doing when it crashes..)

**Comment by 1e4** [comment]
`composer diagnose` is all good as seen [here](http://i.imgur.com/othPTsS.png)

Cleared the cache and run the update with -vvv [here](http://i.imgur.com/BRu88xD.png). Not sure why it didn't crash though

**Comment by Seldaek** [comment]
OK a few notes:

- you have pre-update-cmd hooks so these *might* cause issues too, not only composer code in the game
- you got this random zlib_decode() error, that.. sounds weird. not sure why suddenly one, no proxy you said, maybe a flaky network?
- then it fails because it tries to reach packagist.org by IP and not hostname. That really confuses me as I don't think we do that ever?!

Could you run `composer self-update --snapshot` to make sure you get the latest composer build and then try again the updat ewith -vvv?

**Comment by 1e4** [comment]
Ran with `--snapshot` [here](http://i.imgur.com/cVyIi2O.png)

Pre update is just the default Laravel hooks, just tried on another project, get's to roughly the same point but errors at phpunit [here](http://i.imgur.com/AhvoYS0.png)

**Comment by Seldaek** [comment]
OK.. so no more crash? I see you're on php 7.0.1.. might be worth upgrading to the latest. But otherwise I really have no clue what's going on with the download degrading to an IP there.

**Comment by 1e4** [comment]
Nope, super weird, however the error still displays and composer fails to update.

**Comment by 1e4** [comment]
Can also confirm if run not without verbose mode it will crash PC, if run with verbose it doesn't crash.

**Comment by Seldaek** [comment]
That makes even less sense :/ Did you try to upgrade php to 7.0.5?

**Comment by curry684** [comment]
Did you ever run [memtest](http://www.memtest.org/)?

**Comment by Seldaek** [comment]
Auto-closing as this hasn't been updated in over 6months and is marked as a support request. If there is a real bug to consider please let us know.

**Comment by YosuCadilla** [comment]
I'm having this same issue in several AWS VPSs
It looks like it crashes cause it becomes unresponsive and further network connections via SSH are refused, however if you give it A LOT of time, it seems to follow through...

:/path/to/dir/html# composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)

And it stays there for a very long time...
and it finally, after a couple hours or so responds with:

Killed

And the server comes back up.

**Comment by jaykepeters** [comment]
@YosuCadilla same...

**Comment by j-ledoux** [comment]
I'm recently having the same issue on MacOS 10.15.6 but only when using composer through Docker. I've tried several docker images of my own that used to work (and still working on other Linux environments), and also official Docker images composer:1.10.
I've tried with or without environment variable COMPOSER_MEMORY_LIMIT=-1, the only difference is that composer crashes sooner with memory limit on.

It always behave the same:
 - output gets stuck on "Updating dependencies (including require-dev)" for a while
 - when it reaches Docker's max allocated memory it crashes (Docker probably kills it)

I'm using Docker Desktop 2.3.0.3 (Docker engine 19.03.8) allocated ram memory is 2GB for Docker.

When I use composer locally without Docker, it's working fine. 
I'll try to increase Docker allocated memory to 4GB and let you know.

**Comment by j-ledoux** [comment]
Increasing Docker allocated memory fix this issue.
I guess if composer exceeds max memory usage on a computer or a VM it will probably crash it, just like it does with a Docker container...

**Comment by curry684** [comment]
All computers crash in some weird way when they REALLY run out of memory. Most never do because they have 'virtually infinite' swap memory, causing the computer to grind to a halt through swap overuse before dying of out of memory. For miniature VMs or resource-constrained containers however, out-of-memory is generally fatal.

You may want to read https://docs.docker.com/config/containers/resource_constraints/#understand-the-risks-of-running-out-of-memory and https://www.kernel.org/doc/gorman/html/understand/understand016.html

**Comment by j-ledoux** [comment]
My bad I’ve run to conclusions too quickly

**Comment by jredli93** [comment]
After having multiple failures, I've tried running `composer update` and it worked fine.
