### ISSUE TITLE
[ErrorException] Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by lfluvisotto** [composer/composer#4575]
[ErrorException]                         
Invalid argument supplied for foreach()

X-Powered-By: PHP/5.5.26
Content-type: text/html

Warning: Composer should be invoked via the CLI version of PHP, not the cgi-fcgi SAPI
<br />
<b>Notice</b>:  Undefined index: argv in <b>phar:///home/u844794008/public_html/composer.phar/vendor/symfony/console/Input/ArgvInput.php</b> on line <b>53</b><br />
<br />
<b>Warning</b>:  array_shift() expects parameter 1 to be array, null given in <b>phar:///home/u844794008/public_html/composer.phar/vendor/symfony/console/Input/ArgvInput.php</b> on line <b>57</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>phar:///home/u844794008/public_html/composer.phar/vendor/symfony/console/Input/ArgvInput.php</b> on line <b>283</b><br />

**Comment by alcohol** [comment]
[CONTRIBUTING.md](/composer/composer/blob/master/CONTRIBUTING.md)
