### ISSUE TITLE
Checking composer.json: FAIL in Windows # Why ?

### ISSUE THREAD

**Issue by gunadat** [composer/composer#4576]
When I run composer to install Laravel, it shows Composer\Downloader\TransportException error:
this is the result of 
composer diag
Checking composer.json: FAIL
name : The property name is required
description : The property description is required
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: FAIL
The xdebug extension is loaded, this can slow down Composer a little.
 Disabling it when using Composer is recommended.
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking composer version: OK

**Comment by alcohol** [comment]
Please read the [contributing guidelines](/composer/composer/blob/master/CONTRIBUTING.md) when opening an issue.

**Comment by Chealer** [comment]
I reported a similar issue in ticket #5601 .
