### ISSUE TITLE
Improve script configuration by defining aliases or groups

### ISSUE THREAD

**Issue by giosh94mhz** [composer/composer#4578]
I think that the script section can be improved a bit, with some minor change, to allow DRY.

I often find myself writing composer.json files which are like:

```json
{
	"scripts" : {
		"post-deploy-cmd" : [
			"Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget",
			"bower install -q"
		],
		"post-install-cmd" : [
			"Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget",
			"bower install -q"
		],
		"post-update-cmd" : [
			"Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget",
			"bower update -q"
		]
	},
}
```

This is very very chatty and also prone to configuration error, since many command need to be in multiple script.

A simple solution to this is to write an alias like this:

```json
{
	"scripts" : {
		"common-install-cmd" : [
			"Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget",
		],
		"post-deploy-cmd" : [
			"@common-install-cmd",
			"bower install -q"
		],
		"post-install-cmd" : [
			"@common-install-cmd",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
			"bower install -q"
		],
		"post-update-cmd" : [
			"@common-install-cmd",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
			"bower update -q"
		]
	},
}
```
I've used an `@` prefix just to highlight the concept. I know that I can call the `composer` script recursively, but I think this is not optimal since the command line options cannot be copied.

What do you think?

**Comment by alcohol** [comment]
What's wrong with this?

```
{
    "require": { ... },
    "scripts": {
        "yolo": [ "touch yolo" ],
        "post-install-cmd": [ "composer run-script yolo" ]
    }
}
```

**Comment by giosh94mhz** [comment]
Absolutely nothing "wrong" and this is what I'm about to do in my configuration right now. There are some annoyance, though.

For example, the command may be `/usr/local/bin/composer` or `php ./composer.phar` and is not a good idea to hardcode it. Also some common parameters need to be propagated to "nested" instances; for example `--quiet`, `--verbose` and `--no-interaction`.

I'll give you more feedback after I tested the approach you suggested.

**Comment by giosh94mhz** [comment]
I can confirm that the options are not passed down, but the environment is (of course).

So the issue by using your approach seems to reduce to:
* resolve the correct command for composer
* propagate "symfony/console" options to nested script.

A simpler solution could be providing a composer command variable '$composer`, which expand to (e.g.) `/usr/local/bin/composer --ansi --verbose`; this will allow a more portable:

```yml
{
    "require": { ... },
    "scripts": {
        "yolo": [ "touch yolo" ],
        "post-install-cmd": [ "$composer run-script yolo" ]
    }
}
```

**Comment by Seldaek** [comment]
Yeah I think an easy way to reference another script (or group of..) would be a good thing, it's quite messy in many projects right now. We just have to find the right syntax. @ sounds not too bad as it is familiar and I guess it won't clash with any bash command or anything, but I'm open for other suggestions.
