### ISSUE TITLE
pcntl does not exist as option for windows

### ISSUE THREAD

**Issue by barryaprogrammer** [composer/composer#4584]
I have an error which traces down to:
    - d11wtq/boris v1.0.10 requires ext-pcntl * -> the requested PHP extension pcntl is missing from your system.  (for composer)
I am working on a wamp system. Have installed github and composer. Go to execute and it doesn't work.
the thing is i have researched pcntl and it says this is not avialalbe on windows - i have seen some bizarre explanations but not a clear explanation of what needs to be done.
thanks

**Comment by xjchengo** [comment]
The PCNTL function which is required to run Boris is not available on Windows platforms. If you must use it, run in Linux.

**Comment by alcohol** [comment]
This is not a composer issue. You are using a package that has a dependency on an extension that is not available for your platform. The story ends there. You simply cannot use it.

**Comment by barryaprogrammer** [comment]
understand thanks.

**Comment by barryaprogrammer** [comment]
ok thanks - i'll keep investigating and share with you -

**Comment by barryaprogrammer** [comment]
any thoughts on setting up a virtual machine on something like azure -
i probably can get them to configure however i want  for a minimal monthly
price ($5 a month or something like that) - chekcing on options with
digitalocean also

**Comment by steve-todorov** [comment]
Sorry to be opening an old topic, but I ran into this issue recently. I'm working on a personal project which will use php-pm to start processes on Linux machines. However, I'm currently using windows while developing the actual application. During the development stage I can easly work on the project without using php-pm on Windows at all - I can simply just use PHP's built in server and forget about it. 
This brings me to my next question - are there any plans to add an option to "ignore" missing extensions? It would be nice if Composer asks you what to do when it rans into this problem.

**Comment by alcohol** [comment]
`--ignore-platform-reqs`

**Comment by MsDataScience** [comment]
Alcohol, thank you for this code --ignore-platform-reqs following the installation works like a charm

**Comment by mkhleel** [comment]
[https://sourceforge.net/projects/laragon/files/addon/ext/7.1/php_pcntl-0.1-7.1-ts-vc14-x64.zip/download](php_pcntl-0.1-7.1-ts-vc14-x64.zip)

**Comment by scratcher28** [comment]
does anyone have a php7.2-x64 build?

**Comment by hassanuos** [comment]
> [php_pcntl-0.1-7.1-ts-vc14-x64.zip](https://sourceforge.net/projects/laragon/files/addon/ext/7.1/php_pcntl-0.1-7.1-ts-vc14-x64.zip/download)

@mkhleel this is not working. I tried it.

![image](https://user-images.githubusercontent.com/13483548/72217784-f3f19c00-3543-11ea-95da-e07143ea70af.png)

**Comment by KrisRoofe** [comment]
Refer to [PHP pcntl module installation](https://stackoverflow.com/a/41597346/6521116)

**Comment by MOHAMED-LAAGUILI** [comment]
does any one has ocntl for php 8.2 and  8.3
