### ISSUE TITLE
Composer error ScriptHandler::clearCache

### ISSUE THREAD

**Issue by EsteveGR** [composer/composer#4585]
Can't Generate autoload files.... 

Loading composer repositories with package information
Updating dependencies (including require-dev)
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  The service "security.firewall.map.context.api" has a dependency on a non-existent service "security.token_storage"
  .

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated
 with an exception

  [RuntimeException]
  An error occurred when executing the ""cache:clear --no-warmup"" command.

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers]
 [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader]
 [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--] [<packages>]...

**Comment by EsteveGR** [comment]
With --verbose option...

----------------------------


PS C:\AppWorkflow\workflow_backend> composer update --verbose
Loading composer repositories with package information
Updating dependencies (including require-dev)
Analyzed 5431 packages to resolve dependencies
Analyzed 199012 rules to resolve dependencies
Generating autoload files
> post-update-cmd: Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> post-update-cmd: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> post-update-cmd: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache



  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  The service "security.firewall.map.context.api" has a dependency on a non-existent service "security.token_storage"
  .



Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated
 with an exception



  [RuntimeException]
  An error occurred when executing the ""cache:clear --no-warmup"" command.



Exception trace:
 () at C:\AppWorkflow\workflow_backend\vendor\sensio\distribution-bundle\Sensio\Bundle\DistributionBundle\Composer\Scrip
tHandler.php:220
 Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::executeCommand() at C:\AppWorkflow\workflow_backend\vendor\sen
sio\distribution-bundle\Sensio\Bundle\DistributionBundle\Composer\ScriptHandler.php:86
 Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache() at phar://C:/ProgramData/ComposerSetup/bin/compos
er.phar/src/Composer/EventDispatcher/EventDispatcher.php:211
 Composer\EventDispatcher\EventDispatcher->executeEventPhpScript() at phar://C:/ProgramData/ComposerSetup/bin/composer.p
har/src/Composer/EventDispatcher/EventDispatcher.php:167
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Com
poser/EventDispatcher/EventDispatcher.php:92
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src
/Composer/Installer.php:349
 Composer\Installer->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/UpdateCommand.p
hp:143
 Composer\Command\UpdateCommand->execute() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/conso
le/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfon
y/console/Application.php:838
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/s
ymfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Co
nsole/Application.php:147
 Composer\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/A
pplication.php:120
 Symfony\Component\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Cons
ole/Application.php:82
 Composer\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin/composer:43
 require() at C:\ProgramData\ComposerSetup\bin\composer.phar:25


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers]
 [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader]
 [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--] [<packages>]...


PS C:\AppWorkflow\workflow_backend>

**Comment by alcohol** [comment]
Read the error, not a Composer issue.

**Comment by EsteveGR** [comment]
I don't know why? but updating symfony version on composer.json solve the problem. new version is "symfony/symfony": "~2.4",

Thanks.
