### ISSUE TITLE
Make repository optional

### ISSUE THREAD

**Issue by razbakov** [composer/composer#4586]
## Current situation

For example I have magento module and I have to write each time `repositories` and `require` in my README:

```
{
    "repositories": [
        {"type": "git", "url": "https://github.com/kirchbergerknorr/Milople_Cms"},
    ],

    "require": {
        "kirchbergerknorr/Milople_Cms": "~2.0"
    }
}
```

## Desired way

It would be much better if i can write in README:

```
composer require kirchbergerknorr/Milople_Cms ~2.0
```

## Right now the process looks like that:

1. Create new repo in github
2. Add readme with example of composer.json with `repositories` and `require` section
3. Add module to firegento repository
4. Replace `repository` in readme with firegento repository

## Solution

- Make composer to look-up github repo with the name of required module. 
- Use `repository` section to overwrite github-name-based modules with custom repos.

## Benefits

- It would bring more and more users to use composer because it will become just one-simple-command-installation of any needed module
- It will minimize composer.json and make it more readable

**Comment by xabbuh** [comment]
You do not have to use the `repository` option. Just make sure to enable the Packagist hook in your Gitub repository. Your package will then be available on packagist.org and Composer will find it when it is referenced in a user's `composer.json` file.

**Comment by alcohol** [comment]
Please read the documentation.
