### ISSUE TITLE
How to get list of updated packages in post-update-cmd?

### ISSUE THREAD

**Issue by pilot911** [composer/composer#4587]
Hello! Please explane way to get list of updated packages in post-update-cmd. We should make some extra-work with publish assets, migrations, etc.

Thanks.

**Comment by Seldaek** [comment]
This is not possible, you should rather listen to post-package-install to get them one by one or post-dependencies-solving to get the whole update list at once. Then you can store it and process it when post-update-cmd fires I guess.
