### ISSUE TITLE
composer.local.json

### ISSUE THREAD

**Issue by Swader** [composer/composer#4590]
Sometimes, when using VMs in particular, a custom vendor location is necessary to improve performance - certain frameworks and apps are just too IO heavy to survive in shared folders.

In those cases, moving vendor out of the shared folder path speeds things up dramatically. However, other than with `COMPOSER_VENDOR_DIR` on the command line prefixing every `install`, `update` or `require` command, there is no way to change the vendor dir _for the current project only_ without making global changes (exporting `COMPOSER_VENDOR_DIR` system-wide). Well, there is a way - change `composer.json`, but then there could be conflicts when sharing the projects, as not everyone would agree that having it in the location _you_ prefer would be best for them. Besides, the location on my machine might differ from the location on another's due to difference in username, despite being _relatively_ identical.

Proposed solution:
1. When executing composer commands, Composer checks if there's a `composer.local.json` file present. 
2. If not, goto 3. If yes, it merges the values from that file with those in the main `composer.json` file, overriding the main file's values.
3. It proceeds as usual.

This would allow for custom locations of the vendor and bin folder, custom scripts, etc. If needed, there could be limits on what the local file could contain (no author, no require blocks, etc).

The local file would go into `.gitignore` files.

Thoughts?

**Comment by alcohol** [comment]
What's wrong with just setting COMPOSER_VENDOR_DIR in the VM?

**Comment by Swader** [comment]
That would only work in a one-project-per-VM environment. Multiple projects per VM are sometimes necessary. Re-setting the env var for each before using composer commands would be tedious.

**Comment by rquadling** [comment]
What about using ``.projectA.env``, ``.projectB.env``, etc. files and then use ``source .projectA.env`` prior to your ``composer install``? Or something along those lines?

**Comment by rquadling** [comment]
Maybe as part of a pre-install-cmd script within composer.json?

**Comment by Swader** [comment]
This would work, but only if the projects on that VM were all of the type which supports these pre commands and custom env files. Use one that doesn't (i.e. a fresh require anywhere else) and those pulled packages will end up installed in the last used project's vendor folder. Chaos.

**Comment by Mihailoff** [comment]
You can have multiple json files merged together: https://github.com/wikimedia/composer-merge-plugin

**Comment by GaryJones** [comment]
I wanted to give another example for this.

I want to have just some of my required dependencies to include their `.git` directories when working locally, as these are custom packages I wrote and want to work on, in the context of a whole local site. On production, all packages should prefer dist.

Two approaches:

* Using `composer install --prefer-source` on local gives me a `.git` for every package, so it works, but is painfully slow.
* The `composer-merge-plugin` plugin doesn't work, as it [doesn't support merging of the `config` section](https://github.com/wikimedia/composer-merge-plugin/issues/132) which is where the `preferred-install` key goes that would allow me to set to use source on a per repo basis.

**Comment by vctls** [comment]
This also conflicts with global requires.
For example, I tried installing hirak/prestissimo globally on a container where COMPOSER_VENDOR_DIR is set. Whenever I run `composer install` in my project, Prestissimo gets removed. If I run `composer global install`, project dependencies get removed.

**Comment by sajphon** [comment]
this would be SO useful.

**Comment by vctls** [comment]
Since this has been closed, is there any integrated solution now with Composer 2?
Not that I really care personally, I was using global require for Prestissimo, which is now deprecated, but it might be useful for someone else indeed.
