### ISSUE TITLE
composer require issue: man-in-the-middle

### ISSUE THREAD

**Issue by sharifghaderi** [composer/composer#4593]
I tried to download a laravel package via: composer require illuminate/html and i get this error:
[Composer/Repository/RepositorySecurityException]
The contents of http://packagelist.org/p/provider-2013%.................json do not match its signature.
This should indicate a man-in-the-middle attack. Try running composer again and report this if you think it as  a mistake.

I was working with it a few weeks ago and there was no problem. I uninstalled composer and installed it again. I turned off my antivirus and firewall and tried I checked any solution but it's not working.
Please give a solution. I'm working on an important project and I can't loose my time please help me fix this problem.
Thanks

**Comment by Seldaek** [comment]
Can you try to run this:

`composer config -g repos.packagist composer https://packagist.org`

This will force it to use https always for packagist, it probably will help if you have a broken proxy in the network as it can't mess with your https traffic. Please let us know if it helps, if so we should probably add that to the troubleshooting page.

**Comment by sharifghaderi** [comment]
Hi, 
Fortunately I didn't see your answer and as I said, because time was pushing I was forced to format my machine. After that I installed composer once again and guess what? It's now working really fine. I didn't get where the problem was and I didn't have time to experiment with different solutions but I will save your solution for future problems. Thanks a lot for your fast response. I certainly will continue using composer because it's the easiest tool I've seen for this kind of work and I love it. Just If you could please resolve this kind of problems, it would be very great because people who are using it are mostly if not all, working in big MVC projects where time is money and you know this problem took me nearly 12 hours to solve and I solved it finally in the painful way(format). I'm sure that the problem was somewhere in my compser.json or .lock or .... but I suggest to implement some reset commands where you can be sure that it resets and builds all the configuration files from new and also some analysis commands where you can check the source of the errors.
But again thanks for the fast response and also thanks for your nice job.

**Comment by Seldaek** [comment]
Ok well closing this then..
