### ISSUE TITLE
Cannot exclude for classmaps generated from a parent directory

### ISSUE THREAD

**Issue by ockcyp** [composer/composer#4595]
composer.json path: ``/project-dir/sub/composer.json``

I am adding files to classmap from ``/dir``. This all works fine. But when I try to exclude some paths from the classmap it doesn't work at all

I have a directory ``/project-dir/a/b/c/unwanted-dir`` which I want to exclude from classmap

I added the following to `composer.json`:

```
"exclude-from-classmap": [
    "**/unwanted-dir"
]
```

After some debugging I discovered composer directory gets added into the regex that matches paths to exclude.

```
$blacklist:
string(35) "{(/dir/sub/.+?/skeleton)}"
```

I think this is a bug, but until it gets fixed, is there any other way of getting excludes working than moving ``composer.json`` to ``/project-dir``?

**Comment by alcohol** [comment]
I'm sorry, but... what?

**Comment by ockcyp** [comment]
File tree:
```
.
├── a
│   └── b
│       ├── c
│       │   └── unwanted-dir
│       │       └── MyUnwantedClass.php
│       └── MyClass.php
└── subdir
    ├── composer.json
    ├── src
    │   ├── MyOtherClass.php
    │   └── other-unwanted-dir
    │       └── MyOtherUnwantedClass.php
    └── vendor
```

composer.json:
```json
{
    "autoload": {
        "classmap": ["../a/", "src/"],
        "exclude-from-classmap": ["**/unwanted-dir", "**/other-unwanted-dir"]
    }
}
```

Classmap generated:
```php
return array(
    'MyClass' => $baseDir . '/../a/b/MyClass.php',
    'MyOtherClass' => $baseDir . '/src/MyOtherClass.php',
    'MyUnwantedClass' => $baseDir . '/../a/b/c/unwanted-dir/MyUnwantedClass.php',
);
```

``MyUnwantedClass`` is in the classmap even though I excluded it using ``exclude-from-classmap``

**Comment by rquadling** [comment]
OOI, can you try ...

```
{
    "autoload": {
        "classmap": ["../a/", "src/"],
        "exclude-from-classmap": ["/**/unwanted-dir", "/**/other-unwanted-dir"]
    }
}
```

**Comment by rquadling** [comment]
And what version of composer are you using? This feature was added relatively recently. So if you are using an old version of composer, then YMMV.

**Comment by ockcyp** [comment]
@rquadling doesn't work even with the change you suggested
I am using the latest version. It works for ``MyOtherUnwantedClass`` as seen in the sample code. So the option is not completely ignored.

See the project I created as an example:
https://github.com/ockcyp/composer-autoload-issue-4595

**Comment by Seldaek** [comment]
We consider composer.json as the root of the project, so that'll get prepended to the classmap paths. Have you tried with `"../a/**/unwanted-dir"` though? That would match the classmap path and possibly works but I'm afraid it won't because we don't resolve this path so ../ probably doesn't get parsed as such, it'll just do a preg_match on it which won't actually match. 

It's quite an edge case and I'm not sure if there is anything we can do about it except special-casing the leading ../ and removing bits from the auto-prepended path to resolve it.

**Comment by ockcyp** [comment]
@Seldaek I tried that one as well. it doesn't work. You're right as project root gets prepended to excludes it doesn't match any of the paths. I'll try to prepare a PR for this.
