### ISSUE TITLE
Composer should be able to detect system libaries

### ISSUE THREAD

**Issue by rugk** [composer/composer#4598]
We have a project which requires libsodium-php to work. This can be added as a dependency so that is no problem.
However libsodium-php requires a system library named libsodium to work.

However Composer currently cannot detect system libraries, but this would be necessary here to make sure both libsodium-php and libsodium are installed as you may say that libsodium-php depends on libsodium. 

See https://github.com/jedisct1/libsodium-php/issues/68

**Comment by stof** [comment]
this does not look like something for composer though, as it is about ensuring that your PHP runtime is not broken.
Btw, several extensions are simply failing to load if the necessary library cannot be found anymore (for instance the amqp ext fails to load if librabbitmq is not there anymore). If the same happens in libsodium-php (not sure if it is the case), composer will tells you that ext-libsodium is missing.

**Comment by Seldaek** [comment]
This is not really an option right now, and as scott said in the other issue if you install the php ext it won't let you compile without the dependency, so if you then remove that dependency you are definitely asking for trouble. It's not our role to babysit people.. The require on ext-libsodium should be enough to force the extension is there, and that's as far as we are going to go I'm afraid. [pickle](https://github.com/FriendsOfPHP/pickle) is about installing exts and while it's not fully ready yet it should hopefully help with this in the future and can maybe eventually check for libs too.

**Comment by rugk** [comment]
Okay, thanks for the explanation.
