### ISSUE TITLE
dev-master#xyz syntax results in refusing to install package

### ISSUE THREAD

**Issue by c33s** [composer/composer#4600]
using the syntax ```dev-master#6dd565dacb6e668b9bcfa216a2acca356949375c``` can lead in failing to install packages.

so it looks like, composer is using the ```dev-master``` ```composer.json``` and not as required, the ```composer.json``` of ```dev-master#6dd565dacb6e668b9bcfa216a2acca356949375c```

project composer.json 

    ---snip---
    "c33s/core-bundle": "0.99.1",
    "cedriclombardot/admingenerator-generator-bundle": "dev-master#6dd565dacb6e668b9bcfa216a2acca356949375c",
    ---snip---

c33s/core-bundle: "0.99.1"
https://github.com/c33s/CoreBundle/blob/v0.99.1/composer.json

    ---snip--- 
    "components/font-awesome": "3.2.*",
    ---snip---
    
admingenerator-generator-bundle old version ```#6dd565dacb6e668b9bcfa216a2acca356949375c```
https://github.com/symfony2admingenerator/AdmingeneratorGeneratorBundle/blob/6dd565dacb6e668b9bcfa216a2acca356949375c/composer.json

    ---snip---
    "components/font-awesome": "~3.2"
    ---snip---
    
admingenerator-generator-bundle current ```dev-master```
https://github.com/symfony2admingenerator/AdmingeneratorGeneratorBundle/blob/master/composer.json
currently master is equivalent
https://github.com/symfony2admingenerator/AdmingeneratorGeneratorBundle/blob/58008ec61746da9e6829d0e9b94b8f39589a623f/composer.json

    ---snip---
    "components/font-awesome" : "~4.0"
    ---snip---
    
 
composer run

    composer update
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - Installation request for c33s/core-bundle 0.99.1 -> satisfiable by c33s/core-bundle[v0.99.1].
        - Installation request for cedriclombardot/admingenerator-generator-bundle dev-master#6dd565dacb6e668b9bcfa216a2acca356949375c -> satisfiable by cedriclombardot/admingenerator-generator-bundle[dev-master].
        - cedriclombardot/admingenerator-generator-bundle dev-master requires components/font-awesome ~4.0 -> satisfiable by components/font-awesome[4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.1.0, 4.2.0, 4.3.0, 4.4.0].
        - Can only install one of: components/font-awesome[4.0.0, 3.2.0].
        - Can only install one of: components/font-awesome[4.0.1, 3.2.0].
        - Can only install one of: components/font-awesome[4.0.2, 3.2.0].
        - Can only install one of: components/font-awesome[4.0.3, 3.2.0].
        - Can only install one of: components/font-awesome[4.1.0, 3.2.0].
        - Can only install one of: components/font-awesome[4.2.0, 3.2.0].
        - Can only install one of: components/font-awesome[4.3.0, 3.2.0].
        - Can only install one of: components/font-awesome[4.4.0, 3.2.0].
        - c33s/core-bundle v0.99.1 requires components/font-awesome 3.2.* -> satisfiable by components/font-awesome[3.2.0, 3.2.1].
        - Conclusion: don't install components/font-awesome 3.2.1

**Comment by cs278** [comment]
This is the correct behaviour, the `#sha` constraint is a hack. See the note in the docs: https://getcomposer.org/doc/04-schema.md#package-links

**Comment by alcohol** [comment]
This is known and expected behaviour.
