### ISSUE TITLE
Add --phar Option to Install/Update

### ISSUE THREAD

**Issue by mcordingley** [composer/composer#4601]
It would be nice to be able to have a `--phar` option that generates a `vendor.phar` file after performing all other actions.

The reason for this is that some environments, such as shared hosting, do not allow shell access. Uploading the `vendor/` folder then means uploading a giant folder with perhaps thousands of files. Updates to the folder are messy and best done by uploading a `vendor_new` folder and renaming `vendor` and `vendor_new` after the upload is complete. What would be nice is to be able to run `composer install -a --no-dev --phar` and then just upload the one archive file.

The logic to build a phar file out of the vendor folder is fairly short and straight-forward. I'd include a PR, but I'm having difficulty finding where to hook this in.

    $base = dirname(__FILE__); // Or however Composer determines where it is being run.
    
    $archive = new Phar($base . '/vendor.phar');
    $archive->buildFromIterator(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($base . '/vendor')), $base);
    $archive->setStub(Phar::createDefaultStub('vendor/autoload.php'));

**Comment by alcohol** [comment]
Sorry, but there are applications already specifically for this. Such as Box. Composer doesn't need to expand it's feature-set for this. Also, shared hosting setups like that are a dying breed. You can get so much more for very little now a days from solid providers such as digital ocean or amazon.
