### ISSUE TITLE
Failing requirement does not trigger error

### ISSUE THREAD

**Issue by Cog-g** [composer/composer#4603]
Hi, it seems that when Composer cannot resolve packages, it does not return an error. App like Capistrano does not sees that as an error and continue the deployment, where it should stop and rollback.

    ...
    [distant-server] executing command
    ** [out :: distant-server] Loading composer repositories with package information
    ** [out :: distant-server] Installing dependencies (including require-dev)
    ** [out :: distant-server] Your requirements could not be resolved to an installable set of packages.
    ** [out :: distant-server]
    ** [out :: distant-server] Problem 1
    ** [out :: distant-server] - The requested package wpackagist-plugin/taxonomy-images could not be found in any version, there may be a typo in the package name.
    ** [out :: distant-server]
    ** [out :: distant-server] Potential causes:
    ** [out :: distant-server] - A typo in the package name
    ** [out :: distant-server] - The package is not available in a stable-enough version according to your minimum-stability setting
    ** [out :: distant-server] see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
    ** [out :: distant-server]
    ** [out :: distant-server] Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
    command finished in 7199ms
    triggering after callbacks for `deploy:run_composer'
    ...

In this case, it's because, for whatever reason, a wordpress plugin became inactive on wpackagist.org.

Composer is up-to-date with today's commit.

**Comment by alcohol** [comment]
Can you show us which command it actually executed? Because as far as I know this definitely is an error and Composer exits with an error code also at this point.

**Comment by alcohol** [comment]
```
rob@macbookpro /tmp $ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package alcohol/iso3166 could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
rob@macbookpro /tmp $ echo $?
2
```

**Comment by alcohol** [comment]
Your Capistrano configuration or deployment process must be misconfigured, cause this is evidently not a Composer issue.

**Comment by Cog-g** [comment]
The command is:

    2015-11-11 15:23:30 executing `deploy:run_composer'
    * executing "cd /var/www/vhosts/my-path/releases/20151111142330 && composer install 2>&1 | tee /var/www/vhosts/my-path/releases/20151111142330/COMPOSER-LOG"

**Comment by Cog-g** [comment]
I tried without Caspitrano. Directyl on the server:

    Loading composer repositories with package information
    Installing dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - The requested package wpackagist-plugin/taxonomy-images could not be found in any version, there may be a typo in the package name.

    Potential causes:
     - A typo in the package name
     - The package is not available in a stable-enough version according to your minimum-stability setting
       see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

    Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
    me@server /var/www/vhosts/my-path/releases/20151111142330 $ echo $?
    0

**Comment by Cog-g** [comment]
Please also note that the plugin exists in wpackagist, but it's "inactive". I don't know why.

**Comment by Cog-g** [comment]
Hum weird, I tried many times again from the server, and now `echo $?` returns `2` same as you every time... Indeed it not seems to be a Composer issue.

I'll go see Capistrano ;)

Thank you for your time.

**Comment by alcohol** [comment]
It's because you're piping the command, so you don't get the exit status of `composer`, but of `tee`.
