### ISSUE TITLE
exclude-files-from-classmaps Skipping Symlinks

### ISSUE THREAD

**Issue by rfpludwick** [composer/composer#4604]
The feature described in https://getcomposer.org/doc/04-schema.md#exclude-files-from-classmaps is ignoring files that are symlinks. I have tried to include both the source and symlink filenames in the exclusion and the autoloader still tries to include them in my classmap.

**Comment by Seldaek** [comment]
Can you provide a concrete example of file names etc and how you try to exclude them? But yes it's not surprising since we ignore based on the realpath of the files on a file by file basis it's unlikely to work well with symlinks.

**Comment by rfludwick** [comment]
Example line (the first entry is symlinked to the second):

```
		"exclude-from-classmap": [
			"lib/server/php/<lib>/IndexController.php",
			"/mnt/sync/<lib>/IndexController.php"
		]
```

Example Composer output:

```
Generating optimized autoload files
Warning: Ambiguous class resolution, "IndexController" was found in both "/mnt/sync/<lib>/IndexController.php" and "/mnt/sync/<otherlib>/IndexController.php", the first will be used.
```
