### ISSUE TITLE
Multiple Composer packages with the same namespace

### ISSUE THREAD

**Issue by jslegers** [composer/composer#4605]
## Introduction ##

I recently released the first libraries / packages of a PHP framework called [**`PHP Powertools`**](https://github.com/PHPPowertools). The framework includes its own zero-config [**`PSR-0 loader`**](https://github.com/PHPPowertools/Loader), but I would like to add `Composer` support considering it's the most popular approach towards dependency management in PHP today.

While I know `PSR-0` is supposed to be deprecated, I really hate the `PSR-4` standard and prefer to stick to old-school `PSR-0` conventions for the time being. I also don't like the idea of using multiple namespaces for different packages / libraries that are part of the same framework. Both of these decisions allow me to keep things so much simpler in many ways.

Anyway, these choices imply that I want to have multiple composer packages with the same namespace, autoloaded with PSR-0. The simplified schematics of the composer.json files are as follows.

## PHPPowertools / packageA composer.json ##

    {
        "name": "powertools/packagea",
        "require": {
            "php": ">=5.4.0"
        },
       "autoload": {
            "psr-0": {
                "PowerTools\\": "src/PowerTools/"
            }
        }    
    }

## PHPPowertools / packageB composer.json ##

    {
        "name": "powertools/packageb",
        "require": {
            "php": ">=5.4.0",
            "powertools/packagea": "~1.0.0"
        },
       "autoload": {
            "psr-0": {
                "PowerTools\\": "src/PowerTools/"
            }
        }    
    }

## PHPPowertools / packageC composer.json ##

    {
        "name": "powertools/packagec",
        "require": {
            "php": ">=5.4.0",
            "powertools/packagea": "~1.0.0"
        },
       "autoload": {
            "psr-0": {
                "PowerTools\\": "src/PowerTools/"
            }
        }    
    }

## ThirdParty / app composer.json ##

    {
        "name": "thirdparty/app",
        "require": {
            "php": ">=5.4.0",
            "powertools/packageb": "1.1.0",
            "powertools/packagec": "1.0.0"
    	}
    }

## The Question ##

So, `powertools/packagea`, `xxxxx/packageb` & `xxxxx/packagec` each have a `PowerTools` namespace located in their respective `vendor/PowerTools/` directories.

* Does this approach actually work?
* If yes, are there any performance drawbacks to this approach?
* If yes to either question, are there any alternate approaches that do NOT force me to use a different namespace for each package?!

**Comment by stof** [comment]
This approach works, as it is perfectly valid to have multiple roots for the same namespace (as long as you don't use the same class names in both packages of course).
Using a more specific prefix for each package can improve performance a bit when the optimized autoloader is not used (as it would allow to know in which package to look for the file instead of doing IO several times). But when using the optimized autoloader (which should be done in production), there will be no performance impact.

**Comment by alcohol** [comment]
As @stof said, that will work just fine. Though you probably will not want to use "vendor" in the path as that would be confusing and possibly also conflicting. But I am going to assume that this was simply an example and not actual configuration.

Also, psr-4 is hardly any different from psr-0, and it can do exactly the same thing. It's just fancier and more flexible (no need for a directory that directly translates to the namespace, you can use an alias instead, e.g. `"PowerTools\\": "src"`).

**Comment by jslegers** [comment]
> This approach works, as it is perfectly valid to have multiple roots for the same namespace (as long as you don't use the same class names in both packages of course).

Awesome!

> Using a more specific prefix for each package can improve performance a bit when the optimized autoloader is not used (as it would allow to know in which package to look for the file instead of doing IO several times). But when using the optimized autoloader (which should be done in production), there will be no performance impact.

In which cases shouldn't I use the optimized autoloader? Why not always use it?

> Though you probably will not want to use "vendor" in the path as that would be confusing and possibly also conflicting. But I am going to assume that this was simply an example and not actual configuration.

I did use the `vendor` path to put the source of my libraries, but I fixed that yesterday. Now it uses the `scr` folder instead. I also just edited my question.

> Also, psr-4 is hardly any different from psr-0, and it can do exactly the same thing. It's just fancier and more flexible

I prefer to use old-school name conventions like `\PowerTools\Event_Listener` or ` \PowerTools\DOM_Document`, where each underscore character in the `CLASS NAME` is converted to a `DIRECTORY_SEPARATOR`. PSR-0 supported this, but in PSR-4 underscores no longer have any special meaning.

The reason why I prefer this naming convention, is because this allows me to use a hierarchic folder structure for my libraries while avoid using namespaces altogether when referencing different packages / libraries of the same framework, which IMO results in more readable & cleaner code.

**Comment by cs278** [comment]
> PSR-0 supported this, but in PSR-4 underscores no longer have any special meaning.

PSR-0 supported this because it was the pre PHP 5.3 way of doing namespaces, if you want to keep this archaic convention alive carry on using PSR-0 nobody is stopping you.

**Comment by alcohol** [comment]
@jslegers regarding when to use the optimized autoloader: in general you would use non-optimized in development mode, as you tend to add new classes during that phase and you want the autoloader to be able to load them without having to re-compile the optimized classmap every time.

In production however we always recommend using an optimized classloader, as your library will not suddenly gain new classes there, and as such having a classmap that maps classes directly to files will give you a small performance win.

**Comment by SvenRtbg** [comment]
Note that the optimized autoloader currently simply writes a classmap file for every class it finds in all dependencies. This is probably faster if the amount of classes is small, and it is slower than unoptimized if you have a big number of classes, which you don't use in every request.

Bottom line: Optimization is a tradeoff (here: upfront memory consumption vs. file system access), and there may be a situation where optimizing things decreases performance. MEASURE your performance gains or losses if you optimize something.

**Comment by SvenRtbg** [comment]
@jslegers Why don't you switch to PSR-4?

You have this

        "psr-0": {
            "PowerTools\\": "src/PowerTools/"
        }

Switching to PSR-4 would be like this:

        "psr-4": {
            "PowerTools\\": "src/PowerTools/PowerTools/"
        }

No other change needed. However it has paths like this: `src/PowerTools/PowerTools/MainClass.php` for a class `PowerTools\MainClass` - note the duplicate "PowerTools" directory that does not say very much. 

With PSR-4 you can get rid of it if you like. `PowerTools\MainClass` can be in `src/MainClass.php` if you define your PSR-4 to be `"PowerTools\\": "src/"`.

Additionally, it will benefit performance if you use one or more prefixes that are as long as possible for any given package. Otherwise you will make Composer search in multiple directories to look for classes with the same prefix. Composer will try to optimize it internally and stop looking in paths that are known to not exist, but the first lookup still has to be done.

I wouldn't expect your packages to include random namespaces, because that would certainly violate architectural style. Also, it is a good thing to use sub namespaces to keep classnames from conflicting with other packages (even if they are under your own control). This allows you to define a longer prefix for any of your packages, while they all share the same parent namespace.

**Comment by jslegers** [comment]
@cs278

> PSR-0 supported this because it was the pre PHP 5.3 way of doing namespaces, [...]

Just because PHP has namespaces now, that doesn't mean the old convention has no use anymore. It's still a practical way to organise your files for classes that are part of the same namespace. It makes no sense to me to make every folder a seperate namespace. IMO, this makes code less readable, less maintainable, etc.

> [...] if you want to keep this archaic convention alive carry on using PSR-0 nobody is stopping you.

I know. It just complicates autoloading without Composer, because I now have to implement multiple conventions (instead of just one) in my autoloader. Also, there's the stigma that comes with using a standard that is deprecated, even if it's a perfectly reasonable (and IMO more practical) standard.

------------

@alcohol

> in general you would use non-optimized in development mode, as you tend to add new classes during that phase and you want the autoloader to be able to load them without having to re-compile the optimized classmap every time.

Makes sense!

It also helps me understand better what's the difference between both. I'm still not very familiar with the Composer way of autoloading. It's hard to give up my old way of "just drop your files in the vendor folder and everything works out of the box".

------------

@SvenRtbg

> Note that the optimized autoloader currently simply writes a classmap file for every class it finds in all dependencies. This is probably faster if the amount of classes is small, and it is slower than unoptimized if you have a big number of classes, which you don't use in every request.

Makes sense!

So the optimized autoloader is really only optimized for smaller projects with a limited amount of classes, then?!

> Why don't you switch to PSR-4?

... because (1) I want to be able to use a hierarchic folder structure to put my PHP classes in and (2) I don't want to use a different namespace for every folder. 

PSR-0 allows you to do this by allowing the `_` as a folder separator. PSR-4 removed this and requires that each folder has its own namespace. Without the ability to use relative namespaces in PHP (eg. referencing `..\LibraryY\ClassB` from class `Framework\LibraryX\ClassA`), I find that a totally ridiculous and convoluted convention and really a step backward (from PSR-0) instead of forward!

Not only that, but it totally breaks backward compatibility with PSR-0 to PSR-3.

> No other change needed. However it has paths like this: `src/PowerTools/PowerTools/MainClass.php` for a class `PowerTools\MainClass` - note the duplicate "PowerTools" directory that does not say very much.

Well, I don't want that. I don't want the unnecessary extra folder OR use a different namespace for every folder in my folder hierarchy.

> With PSR-4 you can get rid of it if you like. `PowerTools\MainClass` can be in `src/MainClass.php` if you define your PSR-4 to be `"PowerTools\\": "src/".`

... which means that PSR-4 favors `configuration over convention` instead of `convention over configuration`. That's another thing I hate about PSR-4.

With PSR-0 to PSR-3, you could use a single, high-performance autoloader that is capable of loading ANY class from any package of any library of any framework without any configuration. Just drop it in your vendor folder and it works... out-of-the-box... just like that... without ANY configuration at all!

With PSR-4, every library can use its own autoloading conventions, which means you are now forced to have either multiple loaders or a classmap. This increases complexity and decreases performance for no good reason.

> Additionally, it will benefit performance if you use one or more prefixes that are as long as possible for any given package. Otherwise you will make Composer search in multiple directories to look for classes with the same prefix.

If you don't use the "optimized" autoloader, yes. However, I explicitly do NOT want multiple namespaces within the same framework. I want every class in my framework to use the same `\PowerTools` namespace, even if they're part of a different library. So I guess I'll have to live with the performance drawback then...

> Also, it is a good thing to use sub namespaces to keep classnames from conflicting with other packages (even if they are under your own control). This allows you to define a longer prefix for any of your packages, while they all share the same parent namespace.

What you're saying, is that I should name my classes `\PowerTools\Event\Listener` and `\PowerTools\DOM\Document` instead of `\PowerTools\Event_Listener` and `\PowerTools\DOM_Document`.

Well, I don't want that. I don't want statements like `use PowerTools\Event\Listener As EventListener` throughout my project... and I don't want to use the fully qualified name `\PowerTools\Event\Listener` either. I prefer to use references like `Event_Listener` without namespaces and without `use` statements whenever I'm refering to a class within the same framework.

**Comment by SvenRtbg** [comment]
>>No other change needed. However it has paths like this:  src/PowerTools/PowerTools/MainClass.php  for a class  PowerTools\MainClass  - note the duplicate "PowerTools" directory that does not say very much.

> Well, I don't want that. I don't want the unnecessary extra folder OR use a different namespace for every folder in my folder hierarchy.

I probably failed to say that you currently must have that. If you don't, then your autoloader is configured wrong.

**Comment by jslegers** [comment]
> I probably failed to say that you currently must have that. If you don't, then your autoloader is configured wrong.

For PSR-4, that's true. For PSR-0, that's not true.

Suppose you have a folder structure that looks like this :

Project 
  |__ Index.php
  |__ App
       |__ Controllers
       |__ Models
       |__ Views

**Comment by jslegers** [comment]
> I probably failed to say that you currently must have that. If you don't, then your autoloader is configured wrong.

For PSR-4, that's true. For PSR-0, that's not true.

Suppose you have a folder structure that looks like this :

````
Project 
  |__ Index.php
  |__ App
       |__ Controller
            |__ Default.php
       |__ Model
       |__ View
Vendor 
  |__ Symfony
  |__ Zend
  |__ PowerTools
````

Suppose you want your default controller in the `Default.php` file. PSR-0 allows you to name it either `App\Controller\Default` or `App\Controller_Default`.

With PSR-4, that second option is no longer possible.

**Comment by SvenRtbg** [comment]
You failed to understand my point. I'm not arguing with ANY PSR-4 here.

You have this definition:

    "autoload": {
        "psr-0": {
            "PowerTools\\": "src/PowerTools/"
        }
    }

Assuming there is a class named `PowerTools\Event_Emitter`, by the definition above and according to PSR-0 it MUST be in this file (relative to the position of composer.json): `src/PowerTools/PowerTools/Event/Emitter.php`.

Using optimized autoloaders will hide this problem, because the classmap dumper will look into the path `src/PowerTools` and detect ANYTHING inside, so that above class, while being unaccessible via PSR-0 rules, still gets an entry in the classmap stating that `PowerTools\Event_Emitter` is located in `src/PowerTools/Event/Emitter.php`.

**Comment by jslegers** [comment]
> Assuming there is a class named PowerTools\Event_Emitter, by the definition above and according to PSR-0 it MUST be in this file (relative to the position of composer.json): src/PowerTools/PowerTools/Event/Emitter.php.

So if I want my class `\PowerTools\Event_Emitter` to reside in the file `src/PowerTools/Event/Emitter.php`, I suppose I need to replace this :

````
"autoload": {
    "psr-0": {
        "PowerTools\\": "src/PowerTools/"
    }
}
````

with this :
````
"autoload": {
    "psr-0": {
        "PowerTools\\": "src/"
    }
}
````

Right?!

**Comment by SvenRtbg** [comment]
Right.

**Comment by jslegers** [comment]
> Right.

Thanks! :+1:

Gonna fix that now!

**Comment by jslegers** [comment]
After further research, I'm pretty sure the following is correct, though, for a class named `\PowerTools\Event_Emitter` and located at `src/PowerTools/Event/Emitter.php`

````
"autoload": {
    "psr-0": {
        "PowerTools\\": "src/PowerTools/"
    }
}
````

That's what I conclude from eg. [this article](https://jtreminio.com/2012/10/composer-namespaces-in-5-minutes/) and [this StackOverflow question](http://stackoverflow.com/questions/18146057/composer-autoloader-psr-0-namespaces).

**Comment by SvenRtbg** [comment]
Thah should be easy to verify:

    composer init
    composer require powertools/event
    
    <?php
    require "vendor/autoload.php";
    use \PowerTools\Event_Emitter as Event_Emitter;
    $emitter = Event_Emitter::factory();

I would expect a "class not found" fatal error.

**Comment by jslegers** [comment]
@SvenRtbg :

:+1: 

It would be that easy if I had Composer installed on this machine. 
Thanks for the tip, though. I will run the test as soon as I install Composer.

**Comment by cryode** [comment]
@jslegers As an observation: you keep mentioning how PSR-1, 2 and 3 have not broken backwards compatibility with PSR-0. Those PSRs have nothing to do with autoloading, so of course they do not affect any functionality. It doesn't make much sense to use them as an argument about BC.

**Comment by jslegers** [comment]
@cryode :

> As an observation: you keep mentioning how PSR-1, 2 and 3 have not broken backwards compatibility with PSR-0. Those PSRs have nothing to do with autoloading, so of course they do not affect any functionality.

Valid point.

I actually kinda forgot what was in PSR-1 to PSR-3, because there are pretty irrelevant for my projects. Thank you for refreshing my memory!
