### ISSUE TITLE
Question Helper from Custom Installer?

### ISSUE THREAD

**Issue by zim32** [composer/composer#4606]
Can't figure out how to access  "question" helper from inside custom installer class.
I need access to all features of Symfony Output component not only of that provided by IOInterface.

Is it possible? Thanks.

**Comment by zim32** [comment]
Now I need to manually construct them. It works but I think I am doing something wrong )

$input = new ArgvInput();
$output = new ConsoleOutput();
$questionHelper = new QuestionHelper();
$question = new ConfirmationQuestion('Are you sure?');
$questionHelper->ask($input, $output, $question);

**Comment by Seldaek** [comment]
You can use $event->getIO()->ask(), see our IOInterface.

**Comment by Seldaek** [comment]
Oh sorry if you need raw access to it I'd recommend extending ConsoleIO, you could read the properties from Composer's IO instance if you extend it, and then do what you want, but it's not really a use case we support well and I doubt we want to change that.
