### ISSUE TITLE
  The process has been signaled with signal "5".  

### ISSUE THREAD

**Issue by aaron-goshine** [composer/composer#4608]
`composer install ` in a directory where there is no instance of symfony or no reference to symfony .. is throwing an Exception. 
Why is `composer install` throwing this exception and is composer linked with Symfony in some bizzar way which is not obvious to me     
                                           
`  [Symfony\Component\Process\Exception\RuntimeException]  
  The process has been signaled with signal "5".  `

**Comment by stof** [comment]
Composer uses the Symfony Process component internally to run commands.

Please post the output of composer in verbose mode (``composer install -vvv``), to be able to see what is the failing command

**Comment by aaron-goshine** [comment]
@stof  thank for your help  here: goes the log: 
``  [identity-toolkit-php-master] --➤ composer install -vv 


                                                          
  [Symfony\Component\Process\Exception\RuntimeException]  
  The process has been signaled with signal "5".          
                                                          


Exception trace:
 () at phar:///usr/local/bin/composer/vendor/symfony/process/Symfony/Component/Process/Process.php:367
 Symfony\Component\Process\Process->wait() at phar:///usr/local/bin/composer/vendor/symfony/process/Symfony/Component/Process/Process.php:210
 Symfony\Component\Process\Process->run() at phar:///usr/local/bin/composer/src/Composer/Util/ProcessExecutor.php:62
 Composer\Util\ProcessExecutor->execute() at phar:///usr/local/bin/composer/src/Composer/Package/Version/VersionGuesser.php:206
 Composer\Package\Version\VersionGuesser->guessSvnVersion() at phar:///usr/local/bin/composer/src/Composer/Package/Version/VersionGuesser.php:75
 Composer\Package\Version\VersionGuesser->guessVersion() at phar:///usr/local/bin/composer/src/Composer/Package/Loader/RootPackageLoader.php:68
 Composer\Package\Loader\RootPackageLoader->load() at phar:///usr/local/bin/composer/src/Composer/Factory.php:269
 Composer\Factory->createComposer() at phar:///usr/local/bin/composer/src/Composer/Factory.php:488
 Composer\Factory::create() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:225
 Composer\Console\Application->getComposer() at phar:///usr/local/bin/composer/src/Composer/Command/Command.php:53
 Composer\Command\Command->getComposer() at phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php:84
 Composer\Command\InstallCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:147
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:82
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:25


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [packages1] ... [packagesN]


``

**Comment by bozerkins** [comment]
Good day. 
Quite similar issues has been reported a few years ago: https://github.com/composer/composer/issues/2146

In the end an exception was caused by custom git build, provided by Xcode. 
I guess the same behavior can be altered by an enabled debugging tool, Xdebug for example.
