### ISSUE TITLE
Composer on QNAP NAS

### ISSUE THREAD

**Issue by Andrewkha** [composer/composer#4609]
Hello!

I'm trying to install Composer to my QNAP NAS. 
As per instructions I execute a command `curl -sS https://getcomposer.org/installer | php` but get the following error:
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
of Certificate Authority (CA) public keys (CA certs). If the default
bundle file isn't adequate, you can specify an alternate file
using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
the bundle, the certificate verification probably failed due to a
problem with the certificate (it might be expired, or the name might
not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
the -k (or --insecure) option.
```
Then I tried to use --insecure option to skip the certificate validation, but get another certificate related error:
```
#!/usr/bin/env php
All settings correct for using Composer
Downloading...
Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed
Downloading...
Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed
Downloading...
Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed
The download failed repeatedly, aborting.
```
Any ideas to fix it?

**Comment by pborreli** [comment]
`curl -sS http://getcomposer.org/installer | php`

**Comment by Andrewkha** [comment]
the same...

[~] # curl -sS http://getcomposer.org/installer | php
#!/usr/bin/env php
All settings correct for using Composer
Downloading...
Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed
Downloading...
Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed
Downloading...
Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
file_get_contents(): Failed to enable crypto
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: operation failed
The download failed repeatedly, aborting.

**Comment by pborreli** [comment]
`curl -sS http://getcomposer.org/installer | php -- --disable-tls`

**Comment by Andrewkha** [comment]
Well, this solved issue with installation, but composer self-update again returns SSL error. I found another thread https://github.com/composer/composer/issues/2798 but it's too complicated to the newbie like me.... As far as I understand I need to install the CA certificate somehow... I would appreciate if you could advise how I can do that...

**Comment by SvenRtbg** [comment]
I'd say that the PHP environment you want to use is currently unable to do so. This likely is beyond the scope of Composer, and clearly not an issue to be solved withing Composer. The install script will complain about any settings being wrong, and if TLS is unusable, everything breaks.

The question you should be asking is "How do I update/upgrade/fix PHP on my NAS server?", and it should be directed to a forum or mailing list dealing with Linux install problems or your NAS vendor.
