### ISSUE TITLE
Not able to update

### ISSUE THREAD

**Issue by sinhadeepak** [composer/composer#4611]
when running composer update i am getting this exception
The contents of http://packagist.org/p/provider-archived%24b8d95293bf08dcf12d7eeb4e107e04a296566bfb50f00c01ea4cc462
  aaa22b2b.json do not match its signature. This should indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.

**Comment by alcohol** [comment]
Please read [CONTRIBUTING.md](/composer/composer/blob/master/CONTRIBUTING.md) before opening an issue.
