### ISSUE TITLE
Deprecation Notice: The Composer\Package\LinkConstraint\MultiConstraint class is deprecated

### ISSUE THREAD

**Issue by starrychloe** [composer/composer#4613]
Just updated composer. Now I'm getting these warnings. 

```
Deprecation Notice: The Composer\Package\LinkConstraint\MultiConstraint class is deprecated, use Composer\Semver\Constraint\MultiConstraint instead. in phar:///usr/local/bin/composer/src/Composer/Package/LinkConstraint/MultiConstraint.php:17
Deprecation Notice: The Composer\Package\LinkConstraint\LinkConstraintInterface interface is deprecated, use Composer\Semver\Constraint\ConstraintInterface instead. in phar:///usr/local/bin/composer/src/Composer/Package/LinkConstraint/LinkConstraintInterface.php:17
```

```
$ composer self-update
You are already using composer version d7d91269ec4fb0da171a1c38fa1a47c493627dc0.
```

**Comment by stof** [comment]
Run composer in verbose mode to see which code is using the deprecated classes (it will display the beginning of the stack trace)

**Comment by alcohol** [comment]
You are probably using a plugin that is out of date. But to be sure, do as @stof said, run the command with the `-vvv` flag.

**Comment by alcohol** [comment]
As a side-note, deprecation notices do not interrupt the functionality of Composer. They merely are there to make plugin authors aware of deprecations so they can update their code.

**Comment by indera** [comment]
If you happen to use composer with vagrant it will stop the 'vagrant up' process. 
You have to do 
$ composer install -q
to silence it.
