### ISSUE TITLE
Question: Why create-project doesn't prompt to keep VCS

### ISSUE THREAD

**Issue by jelofson** [composer/composer#4617]
Hello,
I was using `composer create-project vendor/package` and kept expecting it to ask me if I want to keep the VCS. I did not get the prompt and had to specify --keep-vcs to maintain the .git data. I realized later that when specifying the stability of dev, `composer create-project -s dev vendor/package` then I do get prompted. I am wondering why there is the assumption that if I get the most stable, I don't want the vcs? Perhaps that is true in most cases, but why not just ask each time?  Or maybe the documentation for create-project could include this distinction? I didn't find it anywhere.

Again, this isn't an issue per se. Just a curiosity. Thanks.

**Comment by stof** [comment]
@jelofson if you get a stable release, Composer will install it from dist by default, not from source (same than for dependencies), and there is no VCS metadata to keep in such case

**Comment by jelofson** [comment]
@stof Makes perfect sense. Thanks for the reply.
