### ISSUE TITLE
"Failed to decode zlib stream" when install 

### ISSUE THREAD

**Issue by PrinC** [composer/composer#4619]
Get error when install composer with curl -sS https://getcomposer.org/installer | php
```
#!/usr/bin/env php
All settings correct for using Composer
Downloading...
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Failed to decode zlib stream' in -:574
Stack trace:
#0 -(417): HttpClient->get('https://getcomp...')
#1 -(112): installComposer(false, false, 'composer.phar', false, false, false)
#2 -(14): process(Array)
#3 {main}
  thrown in - on line 574
```

**Comment by alcohol** [comment]
Duplicate of #4121

**Comment by hdl** [comment]
This is network connection issue.

**Comment by creativeshuvo** [comment]
Failed to decode zlib stream
how to solve this issue

**Comment by codebeautiful** [comment]
may be you should use this command at ubuntu
sudo apt-get install zlibc

good luck

**Comment by Rbingo** [comment]
how to solve the issue,in windows system?

**Comment by ekasolusi** [comment]
In windows, change
zlib.output_compression=Off to on in php.ini file
good luck

**Comment by Loetfi** [comment]
hi ekasolusi thanks.

**Comment by AslanLau** [comment]
thanks @ekasolusi

**Comment by standibi** [comment]
thanks @ekasolusi

**Comment by milyas77** [comment]
on my php.ini file zlb.output_compression is by default off but still the issue remain

**Comment by SamoKaku** [comment]
Thanks it work

**Comment by Riowaldy** [comment]
> 
> 
> In windows, change
> zlib.output_compression=Off to on in php.ini file
> good luck

Thank you so much @ekasolusi

**Comment by mrdalem** [comment]
> In windows, change
> zlib.output_compression=Off to on in php.ini file
> good luck

Thanks its work! Great

**Comment by abkisakye** [comment]
https://github.com/composer/composer/issues/4619#issuecomment-309631946

thanks this works

**Comment by wahyusa** [comment]
> In windows, change
> zlib.output_compression=Off to on in php.ini file
> good luck

Thankyou
It work! but first time i've just write **"On"** and still error 
the value is **must be "on"**

**Comment by muhammadabdelsalam2** [comment]
thanks this works

**Comment by khalidJA** [comment]
Try to enable` fileinfo` extension from` ini file `

**Comment by Arikowid31** [comment]
> In windows, change zlib.output_compression=Off to on in php.ini file good luck

i was about to make this change, but i press retry previously and then it worked, is mine gonna have bug or something?
im worried lol

**Comment by yasyaindra** [comment]
what if it happened in Docker?

**Comment by hhaswan** [comment]
> may be you should use this command at ubuntu
> 
> ```
> sudo apt-get install zlibc
> ```
> 
> good luck

It works in some case,
I've installed  `apt-get install zlibc` on-premise server but Not Works.
it also depending on your **Internet Provider and Firewall** 😄 make sure http not blocked and your internet provider or firewall (i.e Fortigate) doesn't limit anything

**Comment by inuitviking** [comment]
I know this is closed, old and from 2015, but for Debian Bookworm, this seems to solve the issue:

```bash
sudo apt install zlib1g
```

**Comment by dilhanchandrasiri** [comment]
Make sure zip extension is installed too.

`sudo apt install php-zip`

**Comment by facesses** [comment]
> In windows, change zlib.output_compression=Off to on in php.ini file good luck

it works! thank you.
