### ISSUE TITLE
Option to disable xdebug warning

### ISSUE THREAD

**Issue by koenpunt** [composer/composer#4622]
I want to keep using xdebug, and disable this warning, but currently there is no way to disable this warning.

Or is there a way so that only composer doesn't load xdebug? An alias and a separate php ini maybe?

**Comment by Seldaek** [comment]
As I mentioned in #4615 one easy way around it is to create an alias for composer (or a shell script calling composer) that goes something like:

`php -n -dextension=openssl.so -dextension=mbstring.so -dextension=intl.so /path/to/composer`

Or alternatively if you want to have another php.ini you could do:

`php -c /path/to/php.ini /path/to/composer`

**Comment by koenpunt** [comment]
On second thought, reconfiguring PHP to prevent certain errors in Composer seems cumbersome. Even more when you have  `ext-*` dependencies in your `composer.json` like me, because now I have to make sure that all that extensions are also available in my "custom" composer php alias

**Comment by Seldaek** [comment]
I see that, but it's IMO not about preventing the error but rather about getting full performance. If performance really isn't an issue for you then ignore the warning.. and yes I guess we'll have to add a flag to hide it if it gets too annoying.

**Comment by koenpunt** [comment]
On regular execution the warning doesn't really bother me, but it is also showing on autocomplete...

![image](https://cloud.githubusercontent.com/assets/351038/11319969/b0c5e48e-908a-11e5-920c-56f2d3720de1.png)

**Comment by Seldaek** [comment]
Oh yeah I see. I added a COMPOSER_DISABLE_XDEBUG_WARN env var that should at least be defined by shell completion scripts.. or at the user level if you just want to always ignore it.

**Comment by koenpunt** [comment]
Cool, thanks!

**Comment by Soullivaneuh** [comment]
@Seldaek If I try your solution, I got this:

```bash
$ php -n -dextension=xdebug.so composer
PHP Warning:  Xdebug MUST be loaded as a Zend extension in Unknown on line 0
Could not open input file: composer
```

Any idea?

**Comment by Soullivaneuh** [comment]
Oh I misunderstood the usage. Now I got this:

```bash
$ php -n -dextension=php_openssl.dll -dextension=php_mbstring.dll -dextension=php_intl.dll composer
$ php -n -dextension=php_openssl.dll -dextension=php_mbstring.dll -dextension=php_intl.dll /usr/local/bin/composer 
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/php_openssl.dll' - /usr/lib/php5/20131226/php_openssl.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/php_mbstring.dll' - /usr/lib/php5/20131226/php_mbstring.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/php_intl.dll' - /usr/lib/php5/20131226/php_intl.dll: cannot open shared object file: No such file or directory in Unknown on line 0

Fatal error: Call to undefined function Composer\Console\json_decode() in phar:///usr/local/bin/composer/src/Composer/Console/Application.php on line 148
```

**Comment by Soullivaneuh** [comment]
Well, this will work better with correct extension file. Need to sleep, sorry for that.

**Comment by greg0ire** [comment]
Here is [what SO and I came up with to automate that](http://stackoverflow.com/questions/31083195/disabling-xdebug-when-running-composer)

**Comment by Soullivaneuh** [comment]
@greg0ire see also https://github.com/composer/composer/pull/4637.

**Comment by greg0ire** [comment]
Oh yeah this is quite good. I use docker and I have one container for php-fpm and one for php-cli, so I can quite easily disable xdebug only on php-cli, and then use your nice trick. Thank you for that, I think I will use this, it's way less ugly than my solution :)

**Comment by Soullivaneuh** [comment]
You're welcome.

I'm interested by your local dev docker env. If you have 5 minutes to tell me how you do by e-mail... ;-)

**Comment by greg0ire** [comment]
No need to send an email, this environment is already open-sourced under the name of [dockerony](https://github.com/greg0ire/dockerony). One of my colleague is currently using your trick and should write a PR in the following days :)

**Comment by Soullivaneuh** [comment]
Ok thanks, will test it one day! :-)

**Comment by greg0ire** [comment]
Glad to hear that! It has a focus on development, but tries to be as close to my production environment as possible, which means that I don't use the latest php  or the latest ubuntu version. I think it might be a good source of inspiration if you want to build your own env based on docker-compose though.

**Comment by fmarkwong** [comment]
I wrote a simple wrapper script that disables xdebug , runs composer, then reenables it.  I only recommend this for non shared dev environments as php5dismod works by disabling symlinks to php.ini files.  As far as I know, this is only supported on Debian distros.

```bash
#!/bin/sh

sudo  php5dismod xdebug
composer $1
sudo  php5enmod xdebug
```

**Comment by Soullivaneuh** [comment]
@fmarkwong good catch, I would suggest you to use `"$@"` instead of `$1` to manage multiple argument.

**Comment by fmarkwong** [comment]
@Soullivaneuh Ah, thanks! Updated my comment.

**Comment by RobinRadic** [comment]
The way @fmarkwong mentions will disable xdebug during the time composer is run. This will make you unable to run xdebug during that time. which can take up quite a bit of time.

On ubuntu/mint (or any other linux using something similair as this) you can achieve disabling xdebug by:
```sh
# Copy the cli config for php
cp -r /etc/php5/cli/* ~/.php-composer/

# These are symlinks that are now dead, so remove them
rm ~/.php-composer/conf.d/*.ini 

# copy all non-symlink config files 
cp /etc/php5/mods-available/*.ini ~/.php-composer/conf.d/

# Remove xdebug.ini and any other ini file that you don't want to use when running composer
rm ~/.php-composer/conf.d/xdebug.ini
```

Then, add a bash `alias` 
```sh
alias composer="export PHP_INI_SCAN_DIR='~/.php-composer/conf.d'; php -c ~/.php-composer /usr/local/bin/composer"
```

**Comment by plehatron** [comment]
@RobinRadic Thanks for the tip. Instead of coping conf.d ini files you could just symlink them. Also, export part in composer alias should be `export PHP_INI_SCAN_DIR=~/.php-composer/conf.d`, otherwise `~` doesn't resolve to home dir.
