### ISSUE TITLE
man-in-the-middle attack

### ISSUE THREAD

**Issue by andycapp90** [composer/composer#4624]
It tried to add a dependany on composer.json and after updating using composer by typing in this command: composer --profile --verbose update...I get the stack trace below...what is really the issue

```
[8.5MB/0.25s] > pre-update-cmd: php artisan clear-compiled
[8.6MB/0.38s] Loading composer repositories with package information
[9.1MB/1.40s] Updating dependencies (including require-dev)


                                                                                                   
  [Composer\Repository\RepositorySecurityException]                                                
  The contents of http://packagist.org/p/illuminate/cookie%248a59edee8fd62671eb80a023db0f8f4cc041  
  16861a6e0017d653039dea0aad50.json do not match its signature. This should indicate a man-in-the  
  -middle attack. Try running composer again and report this if you think it is a mistake.         
                                                                                                   


Exception trace:
 () at /usr/share/php/Composer/Repository/ComposerRepository.php:610
 Composer\Repository\ComposerRepository->fetchFile() at /usr/share/php/Composer/Repository/ComposerRepository.php:304
 Composer\Repository\ComposerRepository->whatProvides() at /usr/share/php/Composer/DependencyResolver/Pool.php:199
 Composer\DependencyResolver\Pool->computeWhatProvides() at /usr/share/php/Composer/DependencyResolver/Pool.php:188
 Composer\DependencyResolver\Pool->whatProvides() at /usr/share/php/Composer/DependencyResolver/RuleSetGenerator.php:221
 Composer\DependencyResolver\RuleSetGenerator->addRulesForPackage() at /usr/share/php/Composer/DependencyResolver/RuleSetGenerator.php:330
 Composer\DependencyResolver\RuleSetGenerator->getRulesFor() at /usr/share/php/Composer/DependencyResolver/Solver.php:208
 Composer\DependencyResolver\Solver->solve() at /usr/share/php/Composer/Installer.php:522
 Composer\Installer->doInstall() at /usr/share/php/Composer/Installer.php:232
 Composer\Installer->run() at /usr/share/php/Composer/Command/UpdateCommand.php:143
 Composer\Command\UpdateCommand->execute() at /usr/share/php/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /usr/share/php/Symfony/Component/Console/Application.php:878
 Symfony\Component\Console\Application->doRunCommand() at /usr/share/php/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /usr/share/php/Composer/Console/Application.php:147
 Composer\Console\Application->doRun() at /usr/share/php/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /usr/share/php/Composer/Console/Application.php:82
 Composer\Console\Application->run() at /usr/bin/composer:44
```

**Comment by alcohol** [comment]
Does this persistently happen, or did it happen just once?

**Comment by andycapp90** [comment]
It always happens...I have tried it severally

**Comment by stof** [comment]
Are you running composer behind a proxy ?

**Comment by andycapp90** [comment]
Certainly not.

**Comment by alcohol** [comment]
Is the url that fails (`http://packagist.org/p/illuminate/cookie%248a59edee8fd62671eb80a023db0f8f4cc041  
  16861a6e0017d653039dea0aad50.json`) the same on every attempt?

**Comment by andycapp90** [comment]
yes the URL is always the same

**Comment by alcohol** [comment]
That's weird, cause it's a 404. It shouldn't be trying this URL anymore cause it got updated.

Could you try a `composer clear-cache`?

**Comment by andycapp90** [comment]
I will try and give you a heads-up

**Comment by andycapp90** [comment]
I get the same error even after clearing the cache

**Comment by alcohol** [comment]
Can you give us your composer.json and a full log output of `composer update -vvv` (exactly that command) ?

**Comment by andycapp90** [comment]
**This is the output for composer update -vvv:**
Reading ./composer.json
Loading config file /home/aabwoga/.composer/config.json
Loading config file /home/aabwoga/.composer/auth.json
Loading config file ./composer.json
Executing command (/home/aabwoga/znccia): git describe --exact-match --tags
Executing command (/home/aabwoga/znccia): git branch --no-color --no-abbrev -v
Executing command (/home/aabwoga/znccia): hg branch
Executing command (/home/aabwoga/znccia): svn info --xml
Reading /home/aabwoga/.composer/composer.json
Loading config file /home/aabwoga/.composer/config.json
Loading config file /home/aabwoga/.composer/auth.json
Loading config file /home/aabwoga/.composer/composer.json
Loading config file /home/aabwoga/.composer/auth.json
Executing command (/home/aabwoga/znccia): git describe --exact-match --tags
Executing command (/home/aabwoga/znccia): git branch --no-color --no-abbrev -v
Executing command (/home/aabwoga/znccia): hg branch
Executing command (/home/aabwoga/znccia): svn info --xml
> pre-update-cmd: php artisan clear-compiled
Executing command (CWD): php artisan clear-compiled
Loading composer repositories with package information
Downloading https://packagist.org/packages.json
Writing /home/aabwoga/.composer/cache/repo/https---packagist.org/packages.json into cache
Updating dependencies (including require-dev)
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/p-provider-2013.json from cache
Downloading http://packagist.org/p/provider-2014%24a0f25164ffb3d608d86ba1f2884592f1ab48b7caf6b42cfe77baa11568ed9509.json
Writing /home/aabwoga/.composer/cache/repo/https---packagist.org/p-provider-2014.json into cache
Downloading http://packagist.org/p/provider-2015-01%249fb95c2c33d472d421f1496daf9bf5816058f97223484b26204bce07a319d4d4.json
Writing /home/aabwoga/.composer/cache/repo/https---packagist.org/p-provider-2015-01.json into cache
Downloading http://packagist.org/p/provider-2015-04%247a9d9ea74da7d4a10cea52220dfdf0d2bacd5fb9075594d2a3fd18f62fdd08d2.json
Writing /home/aabwoga/.composer/cache/repo/https---packagist.org/p-provider-2015-04.json into cache
Downloading http://packagist.org/p/provider-2015-07%24779365415df426d94de577240b0ec47195d3a9eba7c344fb0115a15c94fa4ae5.json
Writing /home/aabwoga/.composer/cache/repo/https---packagist.org/p-provider-2015-07.json into cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/p-provider-2015-10.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/p-provider-archived.json from cache
Downloading http://packagist.org/p/provider-latest%24a1b3507c4a57b018b6153ff09d418da4b32c978a28acda546ca122d197b24c22.json
Writing /home/aabwoga/.composer/cache/repo/https---packagist.org/p-provider-latest.json into cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-vlucas$phpdotenv.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-symfony$var-dumper.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-symfony$translation.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-symfony$routing.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-symfony$process.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-psr$log.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-symfony$debug.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-symfony$http-foundation.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-symfony$event-dispatcher.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-symfony$http-kernel.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-symfony$finder.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-symfony$dom-crawler.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-symfony$css-selector.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-symfony$console.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-swiftmailer$swiftmailer.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-jakub-onderka$php-console-color.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-jakub-onderka$php-console-highlighter.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-dnoegel$php-xdg-base-dir.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-nikic$php-parser.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-psy$psysh.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-paragonie$random-compat.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-nesbot$carbon.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-mtdowling$cron-expression.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-monolog$monolog.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-league$flysystem.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-jeremeamia$superclosure.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-doctrine$inflector.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-danielstjules$stringy.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-classpreloader$classpreloader.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-laravel$framework.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-fzaninotto$faker.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-hamcrest$hamcrest-php.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-mockery$mockery.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-sebastian$version.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-sebastian$global-state.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-sebastian$recursion-context.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-sebastian$exporter.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-sebastian$environment.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-sebastian$diff.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-sebastian$comparator.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-symfony$yaml.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-doctrine$instantiator.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-phpdocumentor$reflection-docblock.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-phpspec$prophecy.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-dflydev$markdown.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-phpunit$php-text-template.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-phpunit$phpunit-mock-objects.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-phpunit$php-timer.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-phpunit$php-token-stream.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-phpunit$php-file-iterator.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-phpunit$php-code-coverage.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-phpunit$phpunit.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-phpspec$php-diff.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-phpspec$phpspec.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-laravel$laravel.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-symfony$filesystem.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-phpunit$dbunit.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-ocramius$instantiator.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-ocramius$lazy-map.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-zizaco$entrust.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-illuminate$console.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-illuminate$support.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-illuminate$contracts.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-symfony$config.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-league$flysystem-sftp.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-illuminate$auth.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-illuminate$broadcasting.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-illuminate$bus.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-illuminate$cache.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-illuminate$config.json from cache
Reading /home/aabwoga/.composer/cache/repo/https---packagist.org/provider-illuminate$container.json from cache
Downloading http://packagist.org/p/illuminate/cookie%2400cbb2be725a9da63cab59280395a1500a34b27f597f98aa569bb20f6b13b2f7.json
Downloading http://packagist.org/p/illuminate/cookie%2400cbb2be725a9da63cab59280395a1500a34b27f597f98aa569bb20f6b13b2f7.json
Downloading http://packagist.org/p/illuminate/cookie%2400cbb2be725a9da63cab59280395a1500a34b27f597f98aa569bb20f6b13b2f7.json


                                                                                  
  [Composer\Repository\RepositorySecurityException]                               
  The contents of http://packagist.org/p/illuminate/cookie%2400cbb2be725a9da63ca  
  b59280395a1500a34b27f597f98aa569bb20f6b13b2f7.json do not match its signature.  
   This should indicate a man-in-the-middle attack. Try running composer again a  
  nd report this if you think it is a mistake.                                    
                                                                                  


Exception trace:
 () at /usr/share/php/Composer/Repository/ComposerRepository.php:610
 Composer\Repository\ComposerRepository->fetchFile() at /usr/share/php/Composer/Repository/ComposerRepository.php:304
 Composer\Repository\ComposerRepository->whatProvides() at /usr/share/php/Composer/DependencyResolver/Pool.php:199
 Composer\DependencyResolver\Pool->computeWhatProvides() at /usr/share/php/Composer/DependencyResolver/Pool.php:188
 Composer\DependencyResolver\Pool->whatProvides() at /usr/share/php/Composer/DependencyResolver/RuleSetGenerator.php:221
 Composer\DependencyResolver\RuleSetGenerator->addRulesForPackage() at /usr/share/php/Composer/DependencyResolver/RuleSetGenerator.php:330
 Composer\DependencyResolver\RuleSetGenerator->getRulesFor() at /usr/share/php/Composer/DependencyResolver/Solver.php:208
 Composer\DependencyResolver\Solver->solve() at /usr/share/php/Composer/Installer.php:522
 Composer\Installer->doInstall() at /usr/share/php/Composer/Installer.php:232
 Composer\Installer->run() at /usr/share/php/Composer/Command/UpdateCommand.php:143
 Composer\Command\UpdateCommand->execute() at /usr/share/php/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /usr/share/php/Symfony/Component/Console/Application.php:878
 Symfony\Component\Console\Application->doRunCommand() at /usr/share/php/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /usr/share/php/Composer/Console/Application.php:147
 Composer\Console\Application->doRun() at /usr/share/php/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /usr/share/php/Composer/Console/Application.php:82
 Composer\Console\Application->run() at /usr/bin/composer:44


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--] [<packages>]...

**And below...is the composer.json file**

{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1",
        "zizaco/entrust": "dev-laravel-5"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "znccia\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ],
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}

**Comment by alcohol** [comment]
So clearly the URL is not identical on every attempt. Please don't blindly answer questions without actually validating your answer.

Unfortunately I was unable to reproduce the issue with your composer.json. Everything installs as expected. It seems you have a pretty bad internet connection.

**Comment by andycapp90** [comment]
I have a very good internet connection. I don't think that is the issue.

**Comment by netroby** [comment]
This happend very often. i have no idea how to resolve it. why not download using https instead?

**Comment by carnage** [comment]
Just a thought, could an overzealous firewall/AV product be trying to "protect" you from an XSS session hijacking attack? 

The cookie url parameter followed by a hex string would match an attack designed to steal a session cookie.

**Comment by andycapp90** [comment]
I think the only way to go around this is a fresh installation of Laravel and transfer all my configurations and other files to the new installation. It is a pain...but i have to do it

**Comment by andycapp90** [comment]
Guys! I found the solution here: http://vijayan.tomrain.com/solution-for-repository-security-exception-issue-occuring-while-laravel-installation/

By adding json snippet to the end of my composer.json file
 “repositories”: {
“packagist”: { “url”: “https://packagist.org”, “type”: “composer” }
}

**Comment by chrisharrison** [comment]
That's not a "solution". That's just avoiding the issue.
