### ISSUE TITLE
Make Composer independent of PHP

### ISSUE THREAD

**Issue by mseshachalam** [composer/composer#4625]
The development process using PHP is changing with the tools like Vagrant, Docker(?). Making composer run independent of PHP env makes it easier to setup dev env. (To use laravel's homested we have to composer i.e PHP on dev machine and on the VM). 

Are there any ways to compile/convert .phar to native binary ?

**Comment by alcohol** [comment]
I don't see how we could ever make Composer run on any platform that does not have PHP installed, unless PHP suddenly becomes available as a portable binary (then maybe we could package it together somehow).

Not quite sure I understand your need for this though, or use-case?

**Comment by mseshachalam** [comment]
Yeah, one thought is to rewrite composer in golang and distribute the binary :)

**Comment by alcohol** [comment]
I don't quite see how that would help? You would need a system capable of running applications written in Go then. 

This makes very little sense, considering Composer is aimed towards the PHP community. It is much more likely that someone using Composer has a system capable of running applications written in PHP.

**Comment by mseshachalam** [comment]
Yes, agreed on the second paragraph. Binaries that are built using golang doesn't need go to run.

**Comment by Flyingmana** [comment]
composer will not be able to run without php, as the plugin architecture is based on php.
Also it will be very unlikely to use composer in an environment, which is not having php existent.

**Comment by mseshachalam** [comment]
@Flyingmana One situation where composer will be used without PHP, while developing using laravel's homestead. Just to run homestead commands we need to have composer(and PHP). Lets say If composer doest have dependency on PHP, then we dont have to install PHP on main machine.

**Comment by stof** [comment]
> Just to run homestead commands we need to have composer(and PHP).

even if composer was written in go, this would not change anything for homestead commands. The homestead CLI is written in PHP (and it does not depend on composer to run commands, only to install dependencies of the project itself, which could be avoided by providing it as a phar archive)

**Comment by mseshachalam** [comment]
Yeah :+1:
