### ISSUE TITLE
Scripts hooked to "autoload-dump" not executes on "install" command

### ISSUE THREAD

**Issue by Strate** [composer/composer#4626]
Hi!
c0b49d09f300dde5f88a4bea19a9d32806de6886 breaks execution of "pre-autoload-dump" and "post-autoload-dump" while executing "install" command.

**Comment by alcohol** [comment]
Thanks for the fix

**Comment by craigh** [comment]
I'm not certain this is fixed :frowning: My build is still not executing postAutoloadDump scripts. see https://github.com/RobLoach/component-installer/issues/94 and https://github.com/zikula/core/issues/2649

**Comment by craigh** [comment]
@Strate do I need to do anything differently in order to enable your fix? I cannot seem to get this to work.

**Comment by alcohol** [comment]
@craigh can you be more specific? I do not have the time to dive into issues on other repositories.

**Comment by craigh** [comment]
@alcohol 

in our CI build we were using
`composer install  --prefer-dist --no-dev --no-scripts --ignore-platform-reqs`
which obviously is not intended to run the scripts, but despite this, it would run the `ComponentInstaller\Installer::postAutoloadDump` anyway. I don't know if our build script is corrupt/badly written or if it is a problem with either composer or component-installer.

a couple days ago, this stopped working - the `ComponentInstaller\Installer::postAutoloadDump` no longer ran and many of our assets were not installed.

I have now changed our build script to 
`composer install  --prefer-dist --no-dev --ignore-platform-reqs`
and the scripts are running (for obvious reasons). but I still don't know what changed or why it changed.

I'm not sure if this is now the better solution anyway. But the whole thing has been strange.

**Comment by Strate** [comment]
@craigh I think you need to take a look here: #3194
