### ISSUE TITLE
[ERR_CONNECTION] even after adding getcomposer.org to the whitelist

### ISSUE THREAD

**Issue by mcp84** [composer/composer#4629]
I still try to install composer but it won't download the installer even after adding the site to the whitelist. All I get is this:

Connection Error [ERR_CONNECTION]: Unable to connect to getcomposer.org

Request to https://getcomposer.org/installer failed with errors:
Failed to open stream: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte. (A connection could not be established, because the target computer refused access.)

I get the same message using php -r "readfile('https://getcomposer.org/installer');" | php in a shell (Set the HTTP_PROXY in the shell).
Tried this on Windows 8 and Windows 2012 R2. When I call https://getcomposer.org/installer in a browser I can download the installer-file.

Why don't you simply include the file into the download with the windows-installer? This way these issues won't exist in the first place. 

Is there a place where I can put the downloaded installer-file so the windows-installer does not try to download the file.

**Comment by stof** [comment]
well, even if this file gets included, Composer still need to be able to download things. So you would still need to configure your proxy settings properly to let PHP download files

**Comment by alcohol** [comment]
Unless you plan on manually downloading all your dependencies as well, you should really fix your proxy setup instead, like @stof suggested.

**Comment by stof** [comment]
and if you download everything manually, it means you don't use composer

**Comment by mcp84** [comment]
Found a link to the composer.phar and used it manually. What I don't get ist that the proxy works fine for everything else. Even when I set the HTTP_PROXY in the console i can download stuff (installed Cakephp 3) but it just won't work on the windows-installer.

**Comment by Seldaek** [comment]
The HTTP_PROXY has to be set in your environment variables at the system level not just in the console for it to work with the installer.. But anyway closing this as I don't think we can do much more than we already do.
