### ISSUE TITLE
Reading a composer.json property

### ISSUE THREAD

**Issue by simesy** [composer/composer#4634]
I'm looking for way to read a miscellaneous value from the composer.json.

```
$ composer property --self somekey
```

**Comment by alcohol** [comment]
This is currently not possible.

`composer config -l` will show you all the supported config keys (most of those are config related, not necessarily in your `composer.json`).

**Comment by simesy** [comment]
That gets me close... thanks for the clarification!

**Comment by Seldaek** [comment]
Closing as duplicate of #1411 and btw we have #2415 that really should be merged in some form or another one day :)
