### ISSUE TITLE
Path Repository and local version issues

### ISSUE THREAD

**Issue by mreschke** [composer/composer#4635]
EDIT:  At first, I assumed the path repo was not resolving sub composer.json dependencies (bug), but it does work properly as long as all versions match your local git branches...which is NOT practical...see the other posts below for version issues...

For local package development, the https://getcomposer.org/doc/05-repositories.md#path is absolutely ideal...except a sub composer.json dependency is not being symlinked even though the master composer.json has it in the path repository.

Example, main project composer.json
    
    "repositories": [
        {"type": "path", "url": "../Modules/*"},
    ],

    "require": {
        "mrcore/wiki": "*@dev",
    }

The WILL infact symlink properly in `vendors/mrcore` to ``../../../Modules/Wiki``

BUT that `Modules/Wiki/composer.json` has its own dependencies, each of which ARE actually in the same Modules folder, but of course they are using their proper ~1.0 version numbers not *@dev

``Modules/Wiki/composer.json``

    "require": { 
        "mrcore/foundation": "~1.0",
    },

Ideally, this would recognize ``mrcore/foundation`` is also sitting in my local `Modules` folder and symlink it properly in the main ``vendor/mrcore`` dir...but it doesn't, it just pulls it in from packagist instead.

So it seems that all sub composer.json dependencies whould also look to the master ``repositories`` and use that path if exist, not packagist.  Basically I want all my local packages to be symlinked if they were listed in a ``path``.

**Comment by stof** [comment]
@mreschke your minimum-stability does not allow to use dev versions of the modules, and your path repository only contains dev versions. This is why composer takes these packages from packagist.
Can you try again with a minimum-stability set to dev ?

**Comment by mreschke** [comment]
Yes it is indeed a version issue, so ``path`` repo does recurse into submodules as excepted as long as your versions are proper and match your current git repo (develop, master...).  So the issue is the sub (modules) composer.json files have ``~1.0`` in them (which they should for public consumption on packagist), but my local repo is git ``develop`` branch.  If I edit the sub ``composer.json`` files to say ``*@dev``, then it does symlink them...or if I left at ``~1.0`` and switched my local git branch to '1.0' it works.... I don't see how thats practical for development though.  Does that mean I have to maintain a local dev composer.json (for each submodule) which says ``*@dev``?

So I guess now it's a question of, how can I have different version requirements while in local dev to fit my local ``develop`` git branch, vs when I upload to packagist, without swapping my composer.json files each time I commit?

Example:
Main apps ``composer.json``

    "repositories": [
        {"type": "path", "url": "../Modules/*"},
    ]
    "minimum-stability": "dev",
    "require": {
        "mrcore/wiki": "*@dev"
    },

Which works fine and symlinks ../Modules/Wiki as expected.

Now in ``../Modules/Wiki`` folder, the composer.json file as it sits on packagist right now would say ``~1.0`` for public consumption like so

	"require": {
		"mrcore/foundation": "~1.0"
		"mrcore/auth": "~1.0"
		"mrcore/parser": "~1.0"
	},

BUT, **this is why the symlinks are NOT being populated**, because the actual local code in ``../Modules/*`` is on the ``develop`` git branch, so its not compatible.  If I switch all my local git branches to ``1.0`` it works and all is symlinked...OR if I set the above dependencies to ``"*@dev"`` then it utilizes the local ``develop`` branch and all is symlinked perfectly.  But having to edit the composer.json of each Module to ``*@dev`` or work out of a ``1.0`` branch **doesn't seem like the right solution.**  I have tried "~1.0@dev" to hopefully use dev first if local ``develop`` branch exist, then 1.0 on packagist...or even tried adding all the same packages "require-dev" with ``*@dev`` in that section...none of those 2 work...it just pulls in packagist version, not symlinked.

I am sooo close and have been fiddling with this type of solution for weeks...what am I doing wrong?

**Comment by mreschke** [comment]
Only way I can get everything to symlink properly through all sub composer.json files is to set all sub composer.json file local dependencies to version ``*``, instead of what I would like them to be in packagist as ``~1.0``

**Comment by alcohol** [comment]
Why don't you just use a git or vcs repository then? You know you can specify a local path for those right? Sure, it wont symlink, instead it will actually install the specified version for you in `vendor/`.

If you want symlinks, then the path repository is for you. But the path repository just points to the remote directory. It's not going to checkout a different version or anything.

**Comment by mreschke** [comment]
Yes I have messed with vcs repo, and have tried `url: ../Modules/Wiki` which  just clones `../Modules/Wiki` into `vendor/mreschke/wiki`...that means to actually live code the package I have to make a change, commit, then composer update....not nearly as good as a direct symlink.  This is no different than just coding directly in the `vendor` directory.

**Comment by mreschke** [comment]
Something right in between is https://github.com/composer/installers

This lets you keep your code at `../Modules/Wiki` (which is git) and instead of cloning into `vendors/` you can define a custom `installer-paths` which points to `../Modules/Wiki` and will recognize its `git` and just use that folder live, no symlinks, no cloning.  Ill have to experiment which this method and see if it works with all the version vs git branch differences Im trying to solve.

**Comment by mreschke** [comment]
When using `path repo` and a packages is indeed local (../Modules/Wiki), if composer would simply ignore the local git branch while comparing versions then this entire problem would be solved.  Basically if you use `path repo` and a dependency says `1.0` but your local code branch is sitting on `develop`, composer shouldn't care...it should just symlink regardless.

**Comment by mreschke** [comment]
Here is a quick **screencast** I made explaining my issue exactly with the way the `path repo` "determines" what to symlink and all the version issues describe above.  Am I going crazy here?  If the path is found locally, just symlink it, regardless.  This entire `path repo` system for local development is soooo close to being perfection.

Check it out
https://youtu.be/6A8xIJw6_DU

**Comment by weitzman** [comment]
@mreschke Did you find a good solution to the issue? Your last comment sounds like a useful addition for the problem I'm facing right now.

**Comment by mreschke** [comment]
Not really, I struggle with these issues every time I add more local code to my composer.json.

**Comment by NamelessCoder** [comment]
Terribly sorry to ping this issue back to life, but this is still a major problem and like @mreschke I'm usually wasting excessive amounts of time simply getting "composer install" to work.

Please consider:

> if composer would simply ignore the local git branch while comparing versions then this entire problem would be solved

If this was the case when *any custom repository was added with type `path`* there would be no issue whatsoever.

Furthermore, I'm having the additional issue that for whatever reason, composer does not recognise *some* branches on local path repositories, but others just fine. For example, `dev-master` works flawlessly and symlinks when I'm checked out on `master`. But `dev-development` does not work (clones from github even though I'm correctly checked out on `development`. And finally, `dev-somethingelse` fails completely even though I'm checked out on that branch (I assume because `somethingelse` does not exist on the remote).

So there's something very awry going on. The GitDownloader gets selected when it shouldn't, and recognising which path is checked out seems to be a bit wonky and yields bad results.

@mreschke Please re-open this issue. It was not solved by the linked commit.

**Comment by NamelessCoder** [comment]
Part of the story is this:

```php
// do not compare against other feature branches
if ($candidate === $branch || !preg_match('{^(master|trunk|default|develop|\d+\..+)$}', $candidate, $match)) {
    continue;
}
```

The assumption of which branch names are used for main branch(es) causes the check for "is feature branch" to fail.

**Comment by NamelessCoder** [comment]
Pull request to add option to configure that list of expected feature branch names: https://github.com/composer/composer/pull/6475

Not sure if it helps you solve your issue - but solves mine perfectly!

**Comment by tylerssn** [comment]
Where is an example of how this works?

I've cloned my package into `dev/composer-dev/package-name` for development. Followed by `git checkout develop`

Then, in my app I have composer.json:

```json
  "repositories": {
    "composer-local-development": {
      "type": "path",
      "url": "./dev/composer-dev/*",
      "options": {
        "symlink": true
      }
    },
```

`composer require package-name:@dev` and `composer require package-name:dev-master` does not work when other dependencies require a specific version of the package.
