### ISSUE TITLE
Path Repository Type: Add option / flag to force mirroring instead of symlinking

### ISSUE THREAD

**Issue by DanielSchwiperich** [composer/composer#4636]
There are scenarios where symlinking is not appropriate / best solution.
It would be nice to be able to set a flag to force mirroring:

```
{
    "repositories": [
        {
            "type": "path",
            "url": "../../packages/my-package",
            "symlink": false
        }
    ],
    "require": {
        "my/package": "*"
    }
}
```

If we take the following example project (vcs) structure: 
```
-  composer.json
- composer.lock
- build.xml
- Dockerfile
- ...
- packages
\_ my-package1
  \_ composer.json
\_ my-package2
  \_ composer.json
```

A project for a portal. Using a cms and a forum software.
The main composer.json has dependencies on Contao Standard Edition for example and phpbb

We now want to build an installable package:
- Run `composer install` to get contao and phpbb
- Create a build folder and put contao and phpbb from the vendor dir in it
- Now we add our custom packages / bundles to it and do the following in the build folder on the contao composer.json: 
 - composer config repositories.cms-bundles path ../packages/*
 - composer require  package1 package2
 - ...

At the end we want to deploy the build folder on a Docker Instance / Server or whatever.
The problem then is, that the symlinks are broken and the path packages missing.

We can get around if we zip the custom packages during build process and use the `artifcat` type. 
Sure we could also put all packages in their own git repos, but then we would have an almost empty main repos only containing meta data and multiple very small extension repositories also resulting in a lot of administration overhead regarding CI.

**Comment by alcohol** [comment]
If you don't want to symlink, then just use the vcs or git type.

**Comment by DanielSchwiperich** [comment]
vcs type does not work on sub directories. The above example is already a git repository containing the subpackages. 

From the `build` - dir perspective
```
 "repositories": {
        "0": {
            "type": "path",
            "url": "path/to/repos/packages/my-package1"
        },
    },
```
This works, but creates a symlink. Splitting of the build dir for deployment will break the symlink

```
 "repositories": {
        "0": {
            "type": "vcs",
            "url": "/path/to/repos/packages/my-package1"
        },
    },
```
does not work because `/path/to/repos` is the git repository and only the `/path/to/repos/composer.json` can be accessed but not  `/path/to/repos/packages/my-package-1/composer.json`

**Comment by alcohol** [comment]
If they are already subdirs of your root package, why even use a path repository? Just add the proper autoload definitions into your root composer.json for those directories.

**Comment by DanielSchwiperich** [comment]
I tried to explain this in the OP. The composer.json of the root package ist not the one use to build the application. 

The root composer.json has a dependency on the Contao Standard Edition CMS.  
The build process runs `composer install` on the root package. 
This way we make sure we get Contao at the version we need.
We then create the build folder and put the Contao System from the vendor dir therein. 
We then run `composer install` on the Contao System and have now a clean Contao System in the build dir. So far so good. 
We now want to apply our modules (package1, package2 from the subdirs) on Contao. The first step is to make the modules accessible and Contao uses composer for that. 
Therefore the build process adds our packages as dependcies with `composer require package1` etc
At the end the CI Server will push the build dir to a server to run the application. So we need the packages inside the `build` dir, which is not the case if symlinked.

**Comment by alcohol** [comment]
It sounds to me like your architecture/build process is completely broken. Maybe you should look at how proper applications do it, like the Symfony framework?

**Comment by DanielSchwiperich** [comment]
For sure it does not sound like a clean, proper way. I spend 2 days finding a good solution. 

Contao is a Symfony Application and the ugly part is yet to come, meaning registering the bundles by overwriting / injecting the AppKernel.php.
Problem is Contao wants its modules / bundles to be in the vendor dir which is / should be managed by composer.
This is ok for a normal module / extensions / bundle whatever. 

Not so ok for some (small), cusommade extensions  which are part of *the* customer project and should not split in several repositories.
I could just copy the bundles into the vendor dir without composer during build process and everything would be fine / running.

I wanted to use composer partially for building the system and maybe that was the wrong idea. 

So if my scenario is the only one benefiting from such a flag / option it may not worth it. 
Nevertheless thanks for your time :)

**Comment by stof** [comment]
IMO, if Contao is not able to register bundles which are part of the root project, it is an architecture mistake of contao. You should ask them for a way to register bundles which are part of the root project

**Comment by Seldaek** [comment]
Now doable via

```
    "repositories": [
        {
            "type": "path",
            "url": "../../packages/my-package",
            "options": {
                "symlink": false
            }
        }
    ]
```
