### ISSUE TITLE
feature request: $package->isCached() and $package->getCacheFilename()

### ISSUE THREAD

**Issue by jakoch** [composer/composer#4644]
Hey :)

i'm in a plugin trying to check if a package is cached, but i want to avoid copying [these lines of code](https://github.com/composer/composer/blob/master/src/Composer/Downloader/FileDownloader.php#L123-L127) from the FileDownloader class. It would be nice to abstract / refactor these lines, to provide a function `isCached()` as part of the public API of a package and have cleaner code in the FileDownloader and plugins.

Regarding [`getCacheKey()`](https://github.com/composer/composer/blob/master/src/Composer/Downloader/FileDownloader.php#L242-L249): i have to copy the private function into the plugin, too. Because i'm not working with the FileDownloader, but the "is cached" condition check depends on it and i need to build the value for `$cacheFolder` to have the target position.

```
$cacheFile     = $this->getCacheKey($package);
$cacheFolder   = $this->cacheFilesDir . '/' . $cacheFile;
```

It would be nice to discuss the position of the function and whether it makes sense to add a function `getCacheFilename()` to the public package API - to expose the target file of the package in the cache more cleanly. Somehow the key isn't that interesting, if one can get the target path. 
Maybe we could move the private function getCacheKey() to the package class? 

After the changes, it should be possible to work with the "package cache" related Composer API from inside a plugin using the following three methods:
- `getDistUrl()` (source URL), 
- `isCached()` (test, if a package is cached), 
- `getCacheFilename()` (target location: file of the package in the cache)

in the following away:

```
if( ! $package->isCached()) {
  $this->download($package->getDistUrl(), $package->getCacheFilename());
}
```

Best, Jens

**Comment by stof** [comment]
``isCached`` in the Package object looks wrong to me. This would mean making the package aware of the cache, which does not make sense.

**Comment by jakoch** [comment]
What about the Cache object then? `$cache->isCached($package)`  `$cache->getFilename(package)`?

**Comment by Seldaek** [comment]
`getPackageCacheKey($package)` on the cache sounds reasonable as it seems we only have that function implemented once on FileDownloader. Then `isCached($package)` also sounds reasonable on the Cache.
