### ISSUE TITLE
Call to undefined method

### ISSUE THREAD

**Issue by onman** [composer/composer#4645]
I just self-updated composer and then tried updating my project using 'composer update' and 'composer update prefer-dist'. In both cases I got the following error:
Fatal error: Call to undefined method Fxp\Composer\AssetPlugin\Package\Version\VersionParser::parseLinks() in C:\Users\Onno\AppData\Roaming\Composer\vendor\fxp\composer-asset-plugin\Repository\VcsPackageFilter.php on line 272

Any ideas on how to fix or workaround this?

**Comment by xabbuh** [comment]
Looks like the Composer Asset Plugin needs to be updated to reflect the changes from 14d1f0f3f65a12b37800cd2c6ea0647940111a03.

**Comment by Seldaek** [comment]
@onman just update your global plugins `composer global update` and you should be fine I think.

**Comment by onman** [comment]
Thanks for your advice, it put me on the right track.
The command 'composer global update' did not work on this plugin as it also made that call to the undefined function. The steps I took:
1. manually remove the global 'composer.lock' and the fxp/composer-asset-plugin
2. run 'composer global update' to reflect the new situation
3. re-install the fxp/composer-asset-plugin

**Comment by alcohol** [comment]
@onman you could also have run `composer global update --no-scripts`

**Comment by xabbuh** [comment]
see also francoispluchino/composer-asset-plugin#169
