### ISSUE TITLE
Update event with --dry-run option

### ISSUE THREAD

**Issue by Soullivaneuh** [composer/composer#4650]
Actually, if we launch `update` command with `--dry-run` option, absolutely [no script events is launched](https://github.com/composer/composer/blob/master/src/Composer/Installer.php#L193-L197).

I think those events should be dispatched in any case, but with the `--dry-run` option value inside or, at least, add another events like `PRE_DRY_UPDATE_CMD` / `POST_DRY_UPDATE_CMD`.

This will permit plugins to get information about dry run install and update commands.

**Comment by Soullivaneuh** [comment]
I tested by forcing event launch. This produce obviously side effects.

I think that other events would be better.

**Comment by thewilkybarkid** [comment]
https://github.com/wikimedia/composer-merge-plugin/issues/55 is related

**Comment by Seldaek** [comment]
Closing as per discussion on #4651
