### ISSUE TITLE
Is "description" property in composer.json mandatory for all packages?

### ISSUE THREAD

**Issue by javiereguiluz** [composer/composer#4652]
**Doc** says that *"[description is] required for published packages (libraries)."*
Source: https://getcomposer.org/doc/04-schema.md#description

**Code** says that *"description is always required, no matter what"*
Source: https://github.com/composer/composer/blob/master/res/composer-schema.json#L6

Should we update the docs or should we relax the `description` requirement?

**Comment by alcohol** [comment]
Neither. The situation is fine as-is. Description is required by Packagist. But locally you can do whatever you want. Hence the requirement is for published packages specifically.

**Comment by stof** [comment]
@javiereguiluz the JSON schema describes required properties for published libraries. For the lax validation, Composer unsets some stuff from the schema: https://github.com/composer/composer/blob/b6bac0c2d31e4f84d607638277322d8d256e61af/src/Composer/Json/JsonFile.php#L155

**Comment by javiereguiluz** [comment]
I don't know what to say. If you create a new Symfony project with the installer and run `composer diagnose` you get an error. Is this error OK?

![composer_error](https://cloud.githubusercontent.com/assets/73419/11472865/b2b443d0-976f-11e5-8702-cd2e4982a6e5.png)

**Comment by stof** [comment]
@javiereguiluz ``composer diagnose`` always validates the schema in strict mode

**Comment by alcohol** [comment]
@javiereguiluz you can run it using `--no-check-publish` I think.

**Comment by stof** [comment]
@alcohol you confuse ``composer validate`` and ``composer diagnose``.

**Comment by alcohol** [comment]
Oh right.. he probably wants to be running `validate` though, not `diagnose`, judging by context.

**Comment by javiereguiluz** [comment]
Same error with `composer validate`:

![composer_validate](https://cloud.githubusercontent.com/assets/73419/11473716/4c77529c-9774-11e5-87c3-0c5ba7202eed.png)

In my opinion this behavior is very confusing, but it you agree that this is correct, we can close this issue as "won't fix" then. Thanks!

**Comment by stof** [comment]
@javiereguiluz read the output: it tells you there errors are for publishing the package

**Comment by alcohol** [comment]
@javiereguiluz that is why I told you to run `validate` with the `--no-check-publish` flag.

**Comment by Seldaek** [comment]
Not really an issue IMO. Reading the full output is required to understand the output :)

Diagnose probably shouldn't check with the strict schema though, I'll fix that because that indeed leads to confusion and diagnose should only report real issues.
