### ISSUE TITLE
phpunit / xdebug alias in docs doesn't work well with Homebrew or PATH for vendor-provided phpunit

### ISSUE THREAD

**Issue by deviantintegral** [composer/composer#4653]
Over at https://github.com/composer/composer/pull/4637 docs were added with workarounds to conditionally enable xdebug when running phpunit. The aliases there don't work with homebrew's PHP, as /usr/local/bin/phpunit is a bash script that sets up a few other INI configs. Updating the alias to point to the phar works, but leads to a more general problem where aliases override $PATH variables adding per-project vendor/bin directories to paths.

Does anyone have any easy workarounds for this? I'm sure it's possible to have system-specifc shell functions to figure everything out, but it would be better to have something as simple as the current docs that's more portable.

**Comment by alcohol** [comment]
Homebrew PHP has nothing to do with `/usr/local/bin/phpunit`.

**Comment by deviantintegral** [comment]
By Homebrew PHP I'm referring to https://github.com/Homebrew/homebrew-php which has a brew for phpunit to install system-wide.

**Comment by alcohol** [comment]
So, basically you should be asking this question on the Homebrew issue tracker. :-)

**Comment by deviantintegral** [comment]
Fair enough. I've filed a PR over there at https://github.com/Homebrew/homebrew-php/pull/2726. Thanks!
