### ISSUE TITLE
Can't find dependency defined as a package (zip)

### ISSUE THREAD

**Issue by lysenkobv** [composer/composer#4654]
Hi.
I have added a package to packagist (`p1`). In another project (`p2`) I added this package to dependencies and after I run `composer install` error `no matching package found` appears. 
`install` works ok if I run it in `p1` locally and in Travis.

```json
{
  "require": {
    "maxmind-mmdb/city": "~1.0"
  },
  "repositories": [
    {
      "type": "package",
      "package": {
        "name": "maxmind-mmdb/city",
        "version": "1.0.0",
        "dist": {
          "url": "http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz",
          "type": "gzip"
        }
      }
    }
  ]
}
```

**Comment by alcohol** [comment]
I can only make assumptions since you provided almost no useful information. But I am guessing that p1 contains the repositories definition you included above. And you are including p1 in p2. The repositories definition is `root-only` if you read our documentation. So this means that p2 does not see the repositories definition that p1 contains.

**Comment by lysenkobv** [comment]
Is there only one way to this is to use [event script](../blob/master/doc/articles/scripts.md)?

**Comment by alcohol** [comment]
No, simply add the repositories definition to p2 also.

**Comment by lysenkobv** [comment]
That's a problem.
`maxmind-mmdb/city` is a dependency of `p1`, and `p2` don't have to take care about this.

**Comment by alcohol** [comment]
It does in this situation, since you are using a custom source/repository.

**Comment by lysenkobv** [comment]
It would be great if the composer will download it.

**Comment by stof** [comment]
I suggest you to read the documentation about why Composer does not load repositories recursively: https://getcomposer.org/doc/faqs/why-can't-composer-load-repositories-recursively.md

**Comment by lysenkobv** [comment]
@alcohol, @stof thank you for help
