### ISSUE TITLE
Async download/update/remove of packages

### ISSUE THREAD

**Issue by halaxa** [composer/composer#4655]
This is more of a discussion. Would it be possible to alter `DownloaderInterface`, so that an implementation could download packages asynchronously? If i get it right `DownloaderInterface::download/update/remove` is called sequentially and passed packages ordered by their dependencies. Maybe it could be modified to also accept array of packages which would represent whole level of dependencies where order of installation of those packages doesn't matter and thus may be done asynchronously? Maybe it would be better to add another method or a completely different interface like `MultipleDownloaderInterface`. I dont know. Any ideas on this?

**Comment by staabm** [comment]
there are already open PRs which add parallel processing for http requests, but those did never land as the changes are too intrusive.

see e.g. #3930 #3951

**Comment by alcohol** [comment]
There are longstanding open issues and pull requests that aim for/work towards async implementations. Please use the search functionality to find those. Closing as duplicate.

**Comment by halaxa** [comment]
Thank you. I tried to search with no success. My bad. Sorry.
