### ISSUE TITLE
Lock file with extended package name

### ISSUE THREAD

**Issue by Cyruxx** [composer/composer#4664]
We have a project with a invalid name for public (abc/xyz/mypackage instead of abc/mypackage). This is causing an issue when no composer.lock file exists - composer can't resolve any dependencies.

For a greater understanding what exactly is wrong here's a example:

This is not working without a composer.lock file:

    {
      "name" : "example/module/name",
      "require" : {
        "dependency/dependency" : "~1.0",
      }
    }

Composer would output something like:

    Your requirements could not be resolved to an installable set of packages.
    
    Problem 1
    dependency/dependency 1.0 => satisable by dependency/depency
    
    Suggest: don't install dependency/dependency

But when I change the package name to something like this:

    "name": "example/name"

Then it would resolve the dependency.

After it wrote the composer.lock file you could easily change back the name to `example/module/name` and composer would update the dependencies.

**Comment by alcohol** [comment]
Please, do not share any "something like this" examples. Give us actual literal examples that fully reproduce an issue.

**Comment by Cyruxx** [comment]
Actually this seems to be only an issue in a specific project; I'll close this for now.
