### ISSUE TITLE
relativeSymlink() error: $from (public) and $to (htdocs) must be absolute paths.

### ISSUE THREAD

**Issue by vercotux** [composer/composer#4667]
When calling [relativeSymlink()](https://getcomposer.org/apidoc/master/Composer/Util/Filesystem.html#method_relativeSymlink) with relative paths the following exception occurs:
```
[InvalidArgumentException]                               
$from (public) and $to (htdocs) must be absolute paths.
```

Not sure if this is intentional or not, but it is highly counter-intuitive that a method called *relative*Symlink() is unable to handle ... relative symlinks.

**Comment by alcohol** [comment]
No, it is perfectly capable of handling relative symlinks. It does not handle creating a relative symlink between one or two relative paths, since it does not know what those paths are relative to. Please, if you're going to link to the API docs, at least also read them.

**Comment by vercotux** [comment]
> It does not handle creating a relative symlink between one or two relative paths, since it does not know what those paths are relative to.

And is this written in the docs I have linked to? No? Then please, go back and read them before accusing others of not doing the same.

**Comment by alcohol** [comment]
It does not have to be. That is common knowledge and unrelated to php or Composer. We do not have to document things that we can generally expect developers to know.

**Comment by vercotux** [comment]
Right, it is certainly not poor method naming, confusing error messages or inadequate documentation.

**Comment by alcohol** [comment]
I am so sorry that you ran into a problem. I am confident that taking it out on someone else will help you deal with it properly. Please, by all means, continue.

**Comment by vercotux** [comment]
I have not ran into any problems. I ran into a naming/documentation issue and took the time to publish my findings here. Please refrain yourself from commenting if you have nothing valuable to add yourself.
