### ISSUE TITLE
version 1.0-dev resolving namespaces differently than 1.0.0-alpha10?

### ISSUE THREAD

**Issue by matthiasschroeder** [composer/composer#4669]
composer.json:

```
  {
    "config": {
      "vendor-dir": "Packages/Libraries"
    },
    "require-dev": {
      "typo3-ci/typo3sniffpool": "~2.1",
      "typo3-ci/typo3cms": "~6.2"
    }
  }
```
-> composer install

Composer version 1.0.0-alpha10 2015-04-14 21:18:51
-> creates: ```Packages/Libraries/squizlabs/php_codesniffer/CodeSniffer/Standards/TYPO3CMS```
-> creates: ```Packages/Libraries/squizlabs/php_codesniffer/CodeSniffer/Standards/TYPO3SniffPool```

Composer version 1.0-dev (dc5f8cfbaabb571c54cd4d21091a5c45bd9eaa14) 2015-12-03 10:43:39

creates

```php
Packages/Libraries/typo3-ci/typo3cms
```
and
```php
Packages/Libraries/typo3-ci/typo3sniffpool
```

Why?

**Comment by alcohol** [comment]
I'm sorry, but your subject and your information do not even relate to each other. You are talking about namespaces, and you are showing us file paths. On top of that, you do not even have an actual question.

**Comment by matthiasschroeder** [comment]
Why does Composer version 1.0.0-alpha10 2015-04-14 21:18:51 install the package 
```php
"typo3-ci/typo3cms": "~6.2"
````
 to 
```php
Packages/Libraries/squizlabs/php_codesniffer/CodeSniffer/Standards/TYPO3CMS
```
and Composer version 1.0-dev (dc5f8cf) 2015-12-03 10:43:39 to the different directory 
```php
Packages/Libraries/typo3-ci/typo3cms?
```

Namespaces and file path correspond in a way right?

**Comment by alcohol** [comment]
Those are not the same packages you are talking about.

`squizlabs/php_codesniffer` !== `typo3-ci/typo3cms`

**Comment by matthiasschroeder** [comment]
Thanks, alcohol.

**Comment by alcohol** [comment]
If you run a `composer install -o`, does Composer complain about duplicate class names?

**Comment by matthiasschroeder** [comment]
No, everything seems fine.
I can't figure out, why my coding sniffer definitions from typo3-ci/typo3cms were placed in squizlabs/php_codesniffer/CodeSniffer/Standards/TYPO3CMS before.

But it's no composer-issue.
