### ISSUE TITLE
Path repository referencing a package with the latest commit tagged does not count as "dev-master"

### ISSUE THREAD

**Issue by tobscure** [composer/composer#4673]
Given the directory structure:

```
app/
|-- composer.json

extensions/
|-- some-package/
    |-- composer.json
```

`app/composer.json` contains:

```
    "require": {
        "vendor/some-package": "dev-master"
    },
    "repositories": [
        {
            "type": "path",
            "url": "../extensions/*"
        }
    ]
```

`extensions/some-package` is a git repo which is checked out to the latest commit in the `master` branch. This commit happens to *also* be tagged with a version (e.g. `v0.1.0`).

In this scenario, running `composer update` in `app/` will install `vendor/some-package` from Packagist, not the local path. As far as I can tell, this is because of [this line in PathRepository](https://github.com/composer/composer/blob/master/src/Composer/Repository/PathRepository.php#L132); the VersionGuesser is able to guess a version for the package from the tag, so even though the `master` branch is checked out, the local package is not counted as `dev-master`.

Not a huge issue, can be easily worked around by:

* referencing the tagged version in app/composer.json
* making a dummy commit so master has an untagged latest commit

But thought it was worth bringing up nonetheless, because it caused me some grief.

**Comment by alcohol** [comment]
When master and the latest tag are equal, I've run into some weird scenarios too in the past. The situation rarely occurs, but yeah might be worth looking into.
