### ISSUE TITLE
Stability for "external Libraries"

### ISSUE THREAD

**Issue by tschechniker** [composer/composer#4679]
Hi,

i have the following situation: I'm developing many "internal" and also using some "external" composer packages.

While developing i want all my internal packages to be checked out as dev-master. After my development has been finished my idea was to switch the minimum-stability back from dev to stable and all my packages get installed as stable version. This works totaly fine for my internal packages. But if i add an external one i also get the "unstable" version of the external package while development. Is there a way to say that only my internal packages are getting cloned and all other once will be downloaded at the latest stable (also the requires of these "external" packages) or whatever i was requesting?

For all my dependencies i'm using a private satis repository.

Thanks for your help

**Comment by stof** [comment]
I think that the ``prefer-stable`` config setting is exactly what you need here

**Comment by tschechniker** [comment]
Hi,

from my side i wanted to have an easy switch to go into package development and back. So i didn't define the require as dev-master. Currenty my require looks like "package":"*" (of course only for my internal packages). This works totaly fine for me when i set the minimum-stability to dev composer will clone my package. If i set the minimum-stability to stable composer will download the latest stable. If i set the prefer-stable to true composer will always download the latest stable. Only if i set the required version to dev-master it would do the trick but then i also have to change the Version in the require every time i want to "release" the app. Otherwise it would not find any package whicht fits the requirements. There must be the possibility to set the prefer-stable flag to single requirements and not just globaly. Is there a trick to do this?

**Comment by alcohol** [comment]
Add the `@stable` flag to your external dependencies.

**Comment by tschechniker** [comment]
This is not working. The dependencies of the external package are getting cloned as dev version. Only the external package itself will be stable

**Comment by alcohol** [comment]
Well, Composer was not designed to do what you are trying to achieve, and I'm fresh out of ideas.

**Comment by Seldaek** [comment]
The only way I can see to address this is requiring your internal packages with `some.version.*@dev`.
