### ISSUE TITLE
Bad URL when downloading gitlab repo from group

### ISSUE THREAD

**Issue by andy-b-84** [composer/composer#4680]
Steps to reproduce :
* Have a project on gitlab, in a group, with a valid composer.json (let's call it groupName/libraryName);
* Have a second project, with a dependency over that first project (let's call it otherGroupName/projectName);
* launch "composer install" in the second project's : you should have a message like this:
```
$ composer install
Loading composer repositories with package information
  [Seld\JsonLint\ParsingException]
  "http://gitlab.server/api/v3/projects/groupName%2FlibraryName" does not contain valid JSON
  Parse error on line 1:
  <!DOCTYPE html><htm
  ^
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...
```
My machine :
Mac OS X Yosemite
PHP : 5.4.42 (from Liip)
composer : 1.0-dev (44bc8e019f8b4ac711b647b0693f84061ac7bb38) 2015-12-07 16:56:35

Gitlab :
GitLab 8.2.2
GitLab Shell 2.6.8
GitLab API v3
Ruby 2.1.7p400
Rails 4.1.12

I could still fetch those dependencies using an older composer version, though : the one I get using homebrew (brew install composer), which is version 1.0.0-alpha10 2015-04-14 21:18:51.

**Comment by stof** [comment]
Looks like the gitlab API is returning some HTML instead of JSON. This might mean there is a bug in the gitlab integration in composer (or there is a bug in gitlab, as returning HTML for a call to the API is quite weird)

alpha10 does not use the gitlab API at all, as it does not support gitlab (meaning it will just use the generic git driver)

**Comment by andy-b-84** [comment]
Thank you for your reply,
which just reminded me some more details might help you :
All of my projects' visibilities are set to "internal" on Gitlab, which means I have to use an ssh key pair in order to clone any of my repositories.
I tried to follow this "bad url" myself :Gitlab asked me to log in, and when I did, I s

**Comment by alcohol** [comment]
Well then you have to specify your repository as a `git@` URL to force Composer to try using the native git protocol first (which should use ssh). As you can see right now it is trying `http` which of course will always fail when your project visibility is set to internal.

**Comment by stof** [comment]
@andy-b-84 this should still be reported as a bug in gitlab though. Redirecting to the login page is wrong for an API

**Comment by jdforsythe** [comment]
I reported this behavior at https://gitlab.com/gitlab-org/gitlab-ce/issues/15084
