### ISSUE TITLE
Can I install dev dependencies from my composer.json but ignore them for others?

### ISSUE THREAD

**Issue by Revisor** [composer/composer#4682]
Is it possible to

* Install dev dependencies from my `composer.json` and at the same time
* Ignore dev dependencies of my dependencies?

**Comment by assoum891** [comment]
i don't think that's possible.
there is the --no-dev option that will ignore the require-dev, all of them including your root projet dependencies. But if you try to require or update dev dependencies of you root project you'll get this exception i think 
<pre>
 The lock file does not contain require-dev information, run install with the --no-dev option or run update to install those packages
</pre>

**Comment by alcohol** [comment]
Dev-dependencies of your dependencies are always ignored.

**Comment by Revisor** [comment]
I apologize for my question, I was confused by something else.
In the end it was really our dependency. :)

Thanks.
