### ISSUE TITLE
"Composer require" check package requirements

### ISSUE THREAD

**Issue by myspulin** [composer/composer#4686]
I have tried to install new package by "composer require" and get the message:
```
[InvalidArgumentException]
Could not find package monkey-data/online-store-xml-feed-generator at any
version for your minimum-stability (stable). Check the package spelling or 
your minimum-stability
```
Even if I change the minimum stability to dev, it does not help.

When I added the package manually to the json and run composer update, get this error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for
monkey-data/online-store-xml-feed-generator ^1.0.
->> satisfiable by monkey-data/online-store-xml-feed-generator[1.0.1].
    - monkey-data/online-store-xml-feed-generator 1.0.1 requires php >=5.5.9 ->
your PHP version (5.5.8) or "config.platform.php" value does not satisfy that re
quirement.
```
I have used the php ver. 5.5.8 so requirements was not met. That is ok. But it would be nice to have this information during the instalation.

Could you please check this issue.

Thanks for your time, love this tool:-)

**Comment by alcohol** [comment]
Can you please provide an exact copy paste of our input + output from your console (please do NOT filter anything out of it, just give us the raw version).

**Comment by myspulin** [comment]
Sure, no problem. Tha bad news is that I reported problem to the creator of the package as well and they changed the minimum php version requirement, so now it works on my configuration. I cannot reproduce it any more.

First command was: composer require monkey-data/online-store-xml-feed-generator

I have Composer version 1.0-dev (44bc8e019f8b4ac711b647b0693f84061ac7bb38) 2015-12-07 16:56:35

I have reported the whole output in previous message. I can do some more test on lower version PHP and try to reproduce the issue again.

Thank for your time.

**Comment by alcohol** [comment]
I was just wondering if you adjusted the verbosity of the command, whether or not it would include more information then.

**Comment by Seldaek** [comment]
I think the easy way to fix this is in RequireCommand when we call the VersionGuesser if it returns nothing we should call it again but without specifying a php version to check if there are any versions available that aren't installable due to current php version then we can give a clearer error to the user.
