### ISSUE TITLE
Githhub rate limit reached error

### ISSUE THREAD

**Issue by benzid-wael** [composer/composer#4688]
How can I solve the Github API rate limit problem ?

[https://travis-ci.org/benzid-wael/angular-formly-rest/builds/96075735](https://travis-ci.org/benzid-wael/angular-formly-rest/builds/96075735)

**Comment by pborreli** [comment]
composer (this repository) has nothing to do with npm

**Comment by alcohol** [comment]
https://getcomposer.org/doc/articles/troubleshooting.md#api-rate-limit-and-oauth-tokens

**Comment by stof** [comment]
@alcohol this won't help as composer is not involved at all in the Travis build linked above. This issue should just be closed (and the guy should read the documentation link available in the error message displayed in the build, to know how to solve it for the tool he is using)

**Comment by alcohol** [comment]
Well at least it explains you can use a token. I hope he can figure out the rest from there :d
