### ISSUE TITLE
Global Namespace Conflicts When Running “Composer Update”

### ISSUE THREAD

**Issue by pihish** [composer/composer#4689]
I recently ran composer update on my machine. Through one of my required libraries, I am automatically bringing in the Patchwork library. This library redefines the built-in mb_convert_encoding() method at the global scope. The Patchwork library isn't being affected when I run composer update which means I've been running the latest version for some time.

I also have Laravel as a required library in composer.json. I specifically listed a Laravel release I want (4.2.17 in my case). But I am guessing Laravel has its own internal composer.json and requires and this is bringing in updated Symphony packages. There is one new Symphony package along with the updated ones called symphony/polyfill-mbstring - which also redefines mb_convert_encoding() in the global scope.

Since both libraries try to define the same function, I get a conflict during composer update and composer never gracefully finishes. As a result, I am unable to launch my Laravel app since garbage collection probably never finished.

How do I go about to resolving this conflict?

**Comment by stof** [comment]
@pihish the issue you have is that patchwork/utf8 loads it own mbstring polyfill as soon as the extension is not loaded, even if another polyfill was loaded first.

The symfony polyfill got it right by checking the availability of the function. I suggest you to open an issue on patchwork to request a fix for that. /cc @nicolas-grekas 

In any case, this is not something Composer can solve by itself

**Comment by pihish** [comment]
Thanks, doesn't seem like I can add an issue in Patchwork's repo.  I am hoping @nicolas-grekas will take a look at this and update the library accordingly

**Comment by cs278** [comment]
@pihish https://github.com/tchwork/utf8/issues

**Comment by Seldaek** [comment]
Closing as it's really not an issue here.
