### ISSUE TITLE
Composer does not respect dependencies target

### ISSUE THREAD

**Issue by maboiteaspam** [composer/composer#4692]
Hi,

Given that composer.json

```json
{
  "name": "im/event-dispatcher",
  "description": "Implemented - Standard Event Interface for PHP",
  "type": "st",
  "license": "WTF",
  "authors": [
    {
      "name": "maboiteaspam",
      "email": "no@where.com"
    }
  ],
  "minimum-stability": "dev",
  "require": {
    "php": ">=5.5.0",
    "st/event-dispatcher": "dev-master#v1.0.1"
  },
  "repositories": [
    {
      "type": "git",
      "url": "git@github.com:maboiteaspam/st-event-dispatcher.git"
    }
  ]
}
```

With this particular line,
```
"st/event-dispatcher": "dev-master#v1.0.1"
```

Composer won t respect the `#v1.0.1` when the tag on the remote repo does not exists.

The command i ran was,

```
composer install -v
```

I would have expected it to fail, but it seems it installed master@HEAD instead.

```
composer --version
Composer version 1.0-dev (2f069bffd2e9c9acfebf993cc2a6d08ec867b52e) 2015-11-14 16:19:45

git --version
git version 1.9.5.msysgit.0

php -v
PHP 5.5.12 (cli) (built: Apr 30 2014 11:20:58)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
```

Maybe i m doing something wrong. It s totally possible..

**Comment by alcohol** [comment]
You are doing something wrong.

Please read:

- https://getcomposer.org/doc/articles/versions.md
- https://getcomposer.org/doc/04-schema.md#package-links

**Comment by alcohol** [comment]
I don't know where you got the impression that `"dev-master#v1.0.1"` is a valid notation, but this is not documented anywhere and I have no idea what you expect that to do.

**Comment by maboiteaspam** [comment]
ok. its possible. composer json gives me pain, so that i got it wrong is more than possible. 

BTW, how to reference a git tag then ?

**Comment by stof** [comment]
@maboiteaspam ``"st/event-dispatcher": "1.0.1"``

**Comment by maboiteaspam** [comment]
:+1: thanks for consideration and tips ! Seems to work like a charm with [v1.0.x] !

Do i close the ticket or will you keep it to harden the input ?

BTW², have you ever considered `composer link ../local-dependency` command to ease the workflow ?

**Comment by alcohol** [comment]
@maboiteaspam that is called a path repository, and it is already supported.

May I suggest you take the time to thoroughly read the documentation on http://getcomposer.org/doc/ ?

**Comment by alcohol** [comment]
Closing this as the original question has been answered. Feel free to continue the discussion though (even while it is closed). Any questions you have we will be happy to answer.

**Comment by maboiteaspam** [comment]
yes. never mind i did my own weeks ago. thanks again for the links.
