### ISSUE TITLE
Clean temporary dirs that are created on tests during teardown

### ISSUE THREAD

**Issue by luisfaceira** [composer/composer#4694]
On a quick run of phpunit, I've detected that the following dirs in /tmp/ are created and remain after the tests concluded successfully:
> cmptest-2003111fcf4331c420d8c61ef429410f
> cmptest-3c7103f6ac29a4865b351466a4a730da
> cmptest-a71ac06271f7e35caa3c05f03206e459
> composer-test
> composer_testdir
> composer_test_file
> composer-xz-test-vendor
> composer-zip-test-vendor

Some of them I've detected to be in GitDownloaderTest, but others are being created elsewhere (I haven't had the opportunity to look into it). Also, although it's unlikely I'm not sure if other directories are being created in other tests in other places other than /tmp/ which would be a lot worse.

As @staabm proposed in the context of [#4685](https://github.com/composer/composer/pull/4685/files#r47354731), it would be best to remove such directories during the teardown of the related tests. 

I detected a similar fix to one specific test that was done in the past: 8d3b40ff8ee5b8f550e187b141df4d00626aefed . I think the same approach could be easily replicated to other tests.

**Comment by stof** [comment]
``composer-zip-test`` and ``composer-xz-test`` are related to the ZipDownloader and the XzDownloader (a simple search on the source code detects them).

``cmptest-...`` are for GitDownloaderTest, HgDownloaderTest and AutoloadGeneratorTest

and then, ``Composer\Util\Filesystem`` tests are also creating temp files.

And ``composer-test`` is used in many tests, but only some of them are removing it

**Comment by chorry** [comment]
whoops, sorry for the mess - had no idea `--force push` will leave footprints here instead of replacing commit :(

**Comment by stof** [comment]
@chorry force push creates a new commit. but this does not change the fact that the old commit references the PR.

**Comment by chorry** [comment]
is it ok to close old pull request, and start a new one?

**Comment by stof** [comment]
@chorry this is the issue, not the PR. the PR itself is clean (but not referenced here as you haven't referenced the issue in it), as it is about the branch, which is updated when doing a force push

**Comment by Seldaek** [comment]
Fixed by #4702
