### ISSUE TITLE
Composer fails for HTTP Basic Auth protected Git repositories

### ISSUE THREAD

**Issue by shochdoerfer** [composer/composer#4697]
We have a local Satis server which is protected with HTTP Basic Auth, also our git repositories referenced in the Satis configuration are also protected with HTTP Basic Auth. My auth.json file is empty and I do not have a .netrc file in my $HOME directory.

When I run the composer require command I get asked for the username / password to access our Satis server. I do not get asked for the username / password for the git repository, instead Composer fails with a "Failed to execute git clone" error. Instead of failing I would love to see the dialog asking me for my credentials (plus storing them in the auth.json file).

If I manually add the HTTP Basic Auth credentials for the failing git repository to my auth.json file the Composer checkout works fine.

**Comment by alcohol** [comment]
Can you be a bit more generous with your information? E.g. I cannot tell from the above if you have 2 domains which both require authentication or if you have the same domain with 2 authentication barriers?

**Comment by shochdoerfer** [comment]
Good point ;) Yes, statis and git run on two different sub-domains and this Composer needs to deal with 2 different authentication barriers. But that`s not the real problem. I was able track down the issue and it seems that in our case the webserver does respond with a slightly different error message than expected by Composer. Which means that Composer is not able to react on the authentication failure.
I will prepare a PR to fix this problem.

**Comment by alcohol** [comment]
Well if it is anything like #4524 then you need to fix your server setup. But without knowing the actual response you are receiving (you did not include any verbose logging output), there isn't much else I can contribute to this issue.

**Comment by shochdoerfer** [comment]
Seems I have run into a similar issue as #4524. Did not realize that the server issues an 500 error.

**Comment by alcohol** [comment]
I had a hunch, but wasn't sure. Hope you have been able to resolve it :-)
