### ISSUE TITLE
Bad side effect with the replace feature

### ISSUE THREAD

**Issue by jderusse** [composer/composer#4699]
Actualy, the `${package}.json` file provided by `packagist.org` take into account the replacements declared in other packages (which seem legit).
But the side effect, is, that the file's size is growing up, which slow down `composer update` or `composer require`. Blackfire report 20% of the time in `json_decode` in some cases.

For instance the project [magento2-community-edition](https://github.com/bibumathew/magento2-community-edition/blob/master/composer.json#L33) says it replace symfony/yaml, that why almost 1Mo of the [symfony/yaml.json](https://packagist.org/p/symfony/yaml.json) is talking about magento

Another bad side effect, is: Somebody can create a fake project which replace almost everything, which crash composer for every developers which use almost on of the replaced library (memory limit issue for instance)

**Comment by Seldaek** [comment]
This is a known issue that will be addressed by #4163 in v2 but we can't fix it right now as it would break a lot of internal composer APIs that some plugins rely on.
