### ISSUE TITLE
Composer with authenticated proxy

### ISSUE THREAD

**Issue by wildabyss** [composer/composer#4701]
I'm using RHEL 6 behind a company proxy. I've set up the env variable (in csh) as follows:

```
setenv http_proxy "http://<user>:<pwd>@<addr>:<port>/"
setenv https_proxy "https://<user>:<pwd>@<addr>:<port>/"
```

When running composer, I get the following errors:

> Failed to enable crypto

The proxy settings work fine with curl or wget, but fail with composer. Is this a bug with composer? Is there a non ad-hoc way of making this work?

**Comment by wildabyss** [comment]
Sorry, the environment variables should say:

setenv http_proxy "http://username:pwd@addr:port/"

**Comment by alcohol** [comment]
Can you provide full output (run the command in `-vvv` mode)?

**Comment by wildabyss** [comment]
> php composer -vvv update

Reading ./composer.json
Loading config file ./composer.json
Executing command (/ehome/b0536560/ReportFinder/pdfparser): git describe --exact
-match --tags
Executing command (/ehome/b0536560/ReportFinder/pdfparser): git branch --no-colo
r --no-abbrev -v
Executing command (/ehome/b0536560/ReportFinder/pdfparser): hg branch
Executing command (/ehome/b0536560/ReportFinder/pdfparser): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /
ehome/b0536560/.composer/composer.json
To initialize a project, please create a composer.json file as described in the
https://getcomposer.org/ "Getting Started" section
Loading composer repositories with package information
Downloading https://packagist.org/packages.json
Downloading https://packagist.org/packages.json
Downloading https://packagist.org/packages.json



  [Composer\Downloader\TransportException]
  The "https://packagist.org/packages.json" file could not be downloaded: SSL
   operation failed with code 1. OpenSSL Error messages:
  error:140770FC:SSL routines:func(119):reason(252)
  Failed to enable crypto
  failed to open stream: operation failed



Exception trace:
 () at phar:///var/www/composer.phar/src/Composer/Util/RemoteFilesystem.php:297
 Composer\Util\RemoteFilesystem->get() at phar:///var/www/composer.phar/src/Comp
oser/Util/RemoteFilesystem.php:84
 Composer\Util\RemoteFilesystem->getContents() at phar:///var/www/composer.phar/
src/Composer/Repository/ComposerRepository.php:601
 Composer\Repository\ComposerRepository->fetchFile() at phar:///var/www/composer
.phar/src/Composer/Repository/ComposerRepository.php:415
 Composer\Repository\ComposerRepository->loadRootServerFile() at phar:///var/www
/composer.phar/src/Composer/Repository/ComposerRepository.php:246
 Composer\Repository\ComposerRepository->hasProviders() at phar:///var/www/compo
ser.phar/src/Composer/DependencyResolver/Pool.php:99
 Composer\DependencyResolver\Pool->addRepository() at phar:///var/www/composer.p
har/src/Composer/Installer.php:412
 Composer\Installer->doInstall() at phar:///var/www/composer.phar/src/Composer/I
nstaller.php:232
 Composer\Installer->run() at phar:///var/www/composer.phar/src/Composer/Command
/UpdateCommand.php:143
/UpdateCommand.php:143
or/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///var/www/composer.ph
ar/vendor/symfony/console/Application.php:838
 Symfony\Component\Console\Application->doRunCommand() at phar:///var/www/compos
er.phar/vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at phar:///var/www/composer.phar
/src/Composer/Console/Application.php:147
 Composer\Console\Application->doRun() at phar:///var/www/composer.phar/vendor/s
ymfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at phar:///var/www/composer.phar/s
rc/Composer/Console/Application.php:82
 Composer\Console\Application->run() at phar:///var/www/composer.phar/bin/compos
er:43
 require() at /var/www/composer.phar:24


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock]
 [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-
progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader]
 [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--pre
fer-lowest] [--] [<packages>]...

**Comment by alcohol** [comment]
It looks like your php + openssl extension setup is broken.

**Comment by wildabyss** [comment]
Thanks for your reply.

I'm not sure what's wrong with the OpenSSL extension. Seems to work ok. phpinfo shows that it's enabled correctly.

I can also do the following with no problem:

```PHP
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,"https://git-scm.com/");
curl_setopt($ch, CURLOPT_PROXY, "https://<addr>:<port>");
curl_setopt($ch, CURLOPT_PROXYUSERPWD, "<usr>:<pwd>");
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_HEADER, 1);
$curl_scraped_page = curl_exec($ch);

echo $curl_scraped_page;

curl_close($ch);
```

Page returned code 200.

**Comment by alcohol** [comment]
We don't use the curl wrapper in php, we use `file_get_contents()`.

**Comment by Seldaek** [comment]
Any luck resolving this @wildabyss?

**Comment by wildabyss** [comment]
Some more update, here's the full error output:

```
[Composer\Downloader\TransportException]
  The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
  error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
  Failed to enable crypto
  failed to open stream: operation failed
```

**Comment by wildabyss** [comment]
And another update, I did a little tester:

```PHP
$auth = base64_encode('$USER:$PASS');
$context = array(
        'http' => array(
                'proxy' => 'tcp://$PROXY:$PORT',
                'request_fulluri' => true,
                'header'=>"Proxy-Authorization: Basic $auth"
        )
);
$a = file_get_contents('https://packagist.org/packages.json', false, stream_context_create($context));
echo $a;
```

Works fine too.

**Comment by alcohol** [comment]
I'm confused, in your opening post you were using http and https proxies. In your latest example code you are using a tcp proxy.

**Comment by wildabyss** [comment]
That's the recommended setting from the http context php manual. Not sure why it needs to specify the transport layer under the http options, but that's what works for me.

**Comment by Seldaek** [comment]
@wildabyss did you try `composer diagnose`? Otherwise I'm not sure.. try running composer from source if you can, and printing out all variables that go into the stream context, maybe that helps to figure out what the difference is with your test and what causes the issue.

**Comment by wildabyss** [comment]
The problem appeared to be that I had both http_proxy and https_proxy env set up. Removing the https_proxy solved the problem. Didn't have time to fully diagnose the root cause. But at least it works now.
