### ISSUE TITLE
[RFC] Extra type of "prefer-stable" to ignore first stable major release

### ISSUE THREAD

**Issue by rvanlaak** [composer/composer#4703]
The two configuration parameters `minimum-stablility` and `prefer-stable` are great to ensure stable packages. To be even more safe I'd like to have your opinion on introducing another type of check, one that will ignore the first stable release of a new major version.

For our project this would only apply to semver'd packages that follow their release scheme really well; packages like Symfony, Twig and Doctrine. We would really like to update to these packages as soon as possible, but want to be able to let Composer skip the first stable release (e.g. Symfony 3.0.0, Twig 2.0.0).

If I'm correct the `+` is not used in the [version specification](https://getcomposer.org/doc/articles/versions.md), so would there be anything against using that one? That would result in the following:

     2.8+    ->   >=2.8.1;>=3.0.1

     3+      ->   >=3.0.1

Next to that it would also be great if packages could specify they use semver in their `composer.json`, so composer could give a more clear notification in it's output when an update to a major version was made.

**Comment by Seldaek** [comment]
I don't really see the value here. 2.8+ is a crazy constraint as you can't know that your package works with 3.0 until you tested it (so you'd have to wait for 3.0.1 to be released before you test it?) then once you tested it.. you might as well just say `^2.8||^3.0` which is pretty clear IMO.

There is also the question of.. where does this stop? Is `2.8+` also allowing `>=4.0.1`? If not why not?

Overall it seems more complex than helpful to me.

Regarding the notification about new releases, for now you can use https://github.com/Soullivaneuh/composer-versions-check to get this sort of feature.

**Comment by rvanlaak** [comment]
You are right, it is way too complex and now I think about it again definitely not a problem that Composer should have to solve. Did hope Github would have new version notifications without having to follow everything that is going on over there.

**Comment by Seldaek** [comment]
Yup that'd be nice I agree, you can use versioneye.com to get notifications AFAIK. Or ping github support just so they know, having RSS feeds or something would be nice.
