### ISSUE TITLE
Composer Cannot work in my win 10, no any warnings or tips

### ISSUE THREAD

**Issue by hao203** [composer/composer#4705]
I have successfully intalled composer, but when I use it in cmd, no content come up
just like the below.No tips or warnings!

Microsoft Windows [版本 10.0.10586]
(c) 2015 Microsoft Corporation。保留所有权利。

C:\Users\google>composer -v

C:\Users\google>

I'm sure the path was added to the environment.
C:\ProgramData\ComposerSetup\bin

**Comment by hao203** [comment]
![qq 20151215084958](https://cloud.githubusercontent.com/assets/6681974/11798831/8e22c514-a309-11e5-885a-4b2bf5cb5e4d.jpg)
just like this

**Comment by alcohol** [comment]
What does `php -r 'print ini_get("date.timezone");'` return?

**Comment by hao203** [comment]
Thanks for your support
I don't know if your code` php -r 'print ini_get("date.timezone");'  `was wrong? When  I run it in cmd, it shows that 
C:\Users\google>php -r 'print ini_get("date.timezone");'
PHP Parse error:  syntax error, unexpected ''print' (T_ENCAPSED_AND_WHITESPACE), expecting end of file in Command line code on line 1
![qq 20151216075548](https://cloud.githubusercontent.com/assets/6681974/11827930/f26c995c-a3ca-11e5-8b9e-f712212c6103.jpg)


Maybe I think the code is` php -r "print ini_get('date.timezone');" `
it shows:
C:\Users\google>php -r "print ini_get('date.timezone');"
Asia/Shanghai

**Comment by alcohol** [comment]
I guess windows has difficulty with copy-pasting quote characters. But that is not really relevant to the issue. You figured out a way to make it run regardless.

Ok;

@seldaek I honestly don't really know how to debug stuff on Windows. Does Windows have something similar to `which` on Linux, which could tell us whether or not `composer` can actually be found in his path?

**Comment by stof** [comment]
@alcohol it is not difficulties. Single quotes are simply not allowed in the windows cmd shell to enclose arguments

@hao203 can you download the composer installer script at https://getcomposer.org/installer, and then  run ``php installer --check`` to make it check all PHP requirements ?

And then, please also post the output of ``where composer``

**Comment by hao203** [comment]
@alcohol Thanks buddy, I now realize that coding on windows is not a good choice!
@stof Ok I 'll upload it later. Because of GFW in China you know, images are always failed  to up load! Thank you so much

**Comment by hao203** [comment]
@stof 
`where composer `output

C:\Users\google>where composer
C:\Users\google\composer.bat
C:\Windows\System32\composer.bat
C:\ProgramData\ComposerSetup\bin\composer
C:\ProgramData\ComposerSetup\bin\composer.bat

So how can  i fix  it?
Thank you

**Comment by hao203** [comment]
This error has been solved 
Thank u
@alcohol 
@stof
