### ISSUE TITLE
Composer fails vcs checkouts somehow

### ISSUE THREAD

**Issue by benv666** [composer/composer#4707]
I'm trying to get RoundCube's plugin installer up and running, so I installed composer for that specific vhost. However, for some reason composer keeps failing the install command on git repositories.
I tried to run the test suite, but I can't get it to work either because of the same issue.

What happens when I run composer install is that it fails somehow with an UnexpectedValueException because it can't open a directory.

I've attached the output of composer diagnose and composer -vvv install of the composer git tree.

Running the git commands manually works fine (also through php), so I have no idea why it fails.

Anyone? :)
[composer-diagnose-install.txt](https://github.com/composer/composer/files/62280/composer-diagnose-install.txt)

**Comment by alcohol** [comment]
Not sure what exactly you are trying to do.

What is `/opt/composer/composer-git`?
Does `/opt/composer/composer-git/vendor/composer/semver` exist, and if yes, what are the permissions/owner/group of this directory?

**Comment by stof** [comment]
The commands listed there are weird:

```
unzip '/opt/composer/composer-git/vendor/composer/semver/61bec6be076153db140544e8fe965866' -d '/opt/composer/composer-git/vendor/composer/71b36cdf' && chmod -R u+w '/
opt/composer/composer-git/vendor/composer/71b36cdf'
```

It should be creating a ``vendor/composer/semver`` folder, not ``vendor/composer/71b36cdf``.
this seems like a bug in the custom installer you are using, so it should be reported to this plugin.

**Comment by benv666** [comment]
I just tried to do a checkout of https://github.com/composer/composer and run the testsuite, which I can't get to since composer install fails.
/opt/composer/composer-git is the result of git clone https://github.com/composer/composer
../composer.phar is from 'wget  https://getcomposer.org/composer.phar' followed by php composer.phar update

Don't know what custom installer you guys mean?

**Comment by stof** [comment]
well, you said you installed an installer plugin

**Comment by stof** [comment]
btw, why are you cloning the composer source code and trying to install composer from source ? This is totally unrelated to using a plugin

**Comment by benv666** [comment]
Because I see the same problems when trying to install the roundcube plugin installer, so I figured I'd follow https://github.com/composer/composer/blob/master/CONTRIBUTING.md to see if the test suite would provide answers.

Anyhow, is there anything I can do to get to the bottom of this?
I tried using strace, but all I can tell from that is that git works fine but somehow the directory gets rm -rf'ed anyway.
Output of this command attached: strace -fvv -e open,execve,stat php -c /usr/src/php-5.5.30/php.ini-production ../composer.phar -vvv install > composer-install.txt 2>&1
[composer-install.txt](https://github.com/composer/composer/files/62342/composer-install.txt)

**Comment by benv666** [comment]
Just for completeness, here's the output of composer -vvv install and the same thing run through strace on the roundcube plugin installer.
[composer-install.txt](https://github.com/composer/composer/files/62351/composer-install.txt)
[composer-install-strace.txt](https://github.com/composer/composer/files/62352/composer-install-strace.txt)

**Comment by Seldaek** [comment]
Did you ever get to the bottom of this?

**Comment by benv666** [comment]
Nope, still need to figure it out one of these days.
