### ISSUE TITLE
List dependencies preventing package update

### ISSUE THREAD

**Issue by mbrodala** [composer/composer#4708]
If you try to update a package via `composer update foo/bar` Composer may chose to skip the update silently if the newer version also needs to update other packages.

This can be fixed by issuing `composer update foo/bar --with-dependencies` but there is no hint at this during execution.

Suggestion: List the packages not whitelisted during update which hold back the update of a package. Also hint at the `--with-dependencies` switch.

**Comment by Seldaek** [comment]
This is quite difficult to do automatically, but will be easier to achieve manually at least using the new why-not command from #4917 once it's merged. Closing this as I don't think we can reasonably do it.

**Comment by mbrodala** [comment]
@Seldaek Thanks, I'll watch that issue.

**Comment by curry684** [comment]
With the code from that PR, if my `composer.json` contains:
```
    "require": {
        "omnipay/rabobank": "^2.0",
        "symfony/symfony": "^2.8"
    },
```
I can run:
```
$ composer why-not symfony/symfony 3
 __root__       -      requires symfony/symfony (^2.8)
 guzzle/guzzle  v3.9.3 requires symfony/event-dispatcher (~2.1)
 omnipay/common v2.4.1 requires symfony/http-foundation (~2.1)
```
Let me know if that works for you  :)
