### ISSUE TITLE
Dependecy dependent dependencies

### ISSUE THREAD

**Issue by carnage** [composer/composer#4711]
:)

Given the significant differences between php 5.x and 7.x there could be a project which requires different dependencies dependent on which platform it is running on eg: requiring random_compat if php is less than 7. It would be quite useful if composer could support this directly to avoid libraries having to maintain multiple versions.

Syntax for this would need to be reasonably complex something like

"require-if": {
{ "require": {"random_compat":"1.0.0"}, "if": {"php": "<7.0.0"}}
}

**Comment by Seldaek** [comment]
Please see https://github.com/composer/composer/issues/4168 or https://github.com/composer/composer/issues/4545 - this isn't really something we want to do for various reasons but mostly keeping complexity low. It's generally not an big issue to have a package installed that's unnecessary if you run on php7+. It just won't be used then.
