### ISSUE TITLE
Psr4 Issue on XAMPP compared to Vagrant or Local Server

### ISSUE THREAD

**Issue by daison12006013** [composer/composer#4712]
The PSR4 on my vagrant works well, without calling the **--optimize** argument to transform classes into a classmap.

I installed XAMPP on my computer, then viewing my website, a **class not found error** compared on my vagrant.

I tried to extract declared classes using **get_declared_classes()**, then ofcourse my class is not listed there as it is a wildcard in the PSR4 feature.

To make it work, I'm always running **composer dumpautoload --optimize** and die and dumping again **get_declared_classes()**, my class is listed, checking the **autoload_classmap.php** in the vendor and the class is there, all things works well as expected, no errors occurred.

However, the problem is that, the behavior of psr4 in vagrant[ubuntu, nginx] compared to XAMPP[windows, apache]. 

Or I am not aware that this is normal for XAMPP users?

I've been searching for the same issue, the same error with this http://laravel.io/forum/02-18-2014-class-monologlogger-not-found?page=1, in which they were always calling *--optimize*

**Comment by xabbuh** [comment]
Does this only happen for some classes and if so is it always failing with the same classes?

**Comment by daison12006013** [comment]
@xabbuh, this only occur when a dependency package is declared as PSR4 to their composer.json

I guess there is something wrong when using XAMPP along composer that xampp could not do a wildcard search for the class, while ubuntu[nginx] could.

I'll try to check the CheckLoader class and find out what is happening in the **addPsr4()** function.
