### ISSUE TITLE
How can I add custom config option ?

### ISSUE THREAD

**Issue by 0m3r** [composer/composer#4714]
I was search in magento-composer-installer manual interesting example
https://github.com/Cotya/magento-composer-installer#install-a-module-in-your-project
~~~
configure your magento root dir, the directory where your magento resides:
composer config extra.magento-root-dir composer "htdocs/"
~~~
but it return exception
~~~
[InvalidArgumentException]                                                         
  Setting extra.magento-root-dir does not exist or is not supported by this command
~~~

**Comment by stof** [comment]
This should be reported to the magento-composer-installer package, not to composer, as you say that the broken instruction is there.

**Comment by 0m3r** [comment]
That command with magento is just an example. Do not take it into considuration.
Can you tell me is it possible to add some my custom option in section 'extra' for composer.json using command line?
If yes, please, help me with proper command.

**Comment by simesy** [comment]
@0m3r is asking if it is possible to use CLI to inject configuration into the `extra` section of a composer.json file, rather than manually editing it.

**Comment by simesy** [comment]
I don't think it is possible, except there is a workaround mentioned here:
http://stackoverflow.com/questions/33568749/use-composer-cli-to-add-data-to-the-extra-property

**Comment by 0m3r** [comment]
Thanks for your advise.

workaround
jq --indent 4 '.extra.foo = "bar"' composer.json

**Comment by frans-beech-it** [comment]
Just for others that are searching for this see https://getcomposer.org/doc/03-cli.md#modifying-extra-values

It's possible now `php composer.phar config extra.foo.bar value`
