### ISSUE TITLE
sort-packages as config settings

### ISSUE THREAD

**Issue by hanovruslan** [composer/composer#4715]
Hi!

For many (our) projects we run 

```
composer require --sort-packages some/package:@some-version 
```

so it will be nice to have sort-packages as global settings with false by default according to the current RequireCommand options

I've already created some PR (not pushed to this repo for now) but i stacked at the test stuff

Did not find test for command RequireCommand

So what what should i do?

P.S.: Is there any existing PR with such behaviour ? did not found such

**Comment by alcohol** [comment]
I'm personally not a fan for having each command line argument/flag also available as configuration option. But if anyone is willing to spend time on this, go ahead I guess.

**Comment by hanovruslan** [comment]
@alcohol done
