### ISSUE TITLE
autoload_real.php can more simple

### ISSUE THREAD

**Issue by cmmer** [composer/composer#4718]
```
<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitfef3b27bbea16132f0c9421700acd66f
{
    private static $loader;

    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }
        
        require __DIR__ . '/ClassLoader.php';
        self::$loader = $loader = new \Composer\Autoload\ClassLoader();

        $map = require __DIR__ . '/autoload_namespaces.php';
        foreach ($map as $namespace => $path) {
            $loader->set($namespace, $path);
        }

        $map = require __DIR__ . '/autoload_psr4.php';
        foreach ($map as $namespace => $path) {
            $loader->setPsr4($namespace, $path);
        }

        $classMap = require __DIR__ . '/autoload_classmap.php';
        if ($classMap) {
            $loader->addClassMap($classMap);
        }

        $loader->register(true);

        return $loader;
    }
}
```

**Comment by cmmer** [comment]
```
<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitfef3b27bbea16132f0c9421700acd66f
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInitfef3b27bbea16132f0c9421700acd66f', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader();
        spl_autoload_unregister(array('ComposerAutoloaderInitfef3b27bbea16132f0c9421700acd66f', 'loadClassLoader'));

        $map = require __DIR__ . '/autoload_namespaces.php';
        foreach ($map as $namespace => $path) {
            $loader->set($namespace, $path);
        }

        $map = require __DIR__ . '/autoload_psr4.php';
        foreach ($map as $namespace => $path) {
            $loader->setPsr4($namespace, $path);
        }

        $classMap = require __DIR__ . '/autoload_classmap.php';
        if ($classMap) {
            $loader->addClassMap($classMap);
        }

        $loader->register(true);

        return $loader;
    }
}

```
there is a bug here,
$firstTime = ComposerAutoloaderInitfef3b27bbea16132f0c9421700acd66f::getLoader();
$secondTime = ComposerAutoloaderInitfef3b27bbea16132f0c9421700acd66f::getLoader();

$firstTime != $secondTime;
the tow result are not equal! （i think the tow result equal is better）

**Comment by alcohol** [comment]
Not sure what you are talking about... I get the same loader instance in both cases.

```
rob@macbookpro /srv/git/github/composer (master) $ cat test.php
<?php

$a = require __DIR__.'/vendor/autoload.php';
$b = require __DIR__.'/vendor/autoload.php';

var_dump($a === $b);

rob@macbookpro /srv/git/github/composer (master) $ php test.php
bool(true)
```

**Comment by jakoch** [comment]
1. I can't reproduce the `$a != $b`  `::getLoader()` issue, too.
2. But, the inital request of simplifying the generated `autoloader_real.php` file seems to be valid:

Very brief: He replaces the autoloading of `ClassLoader.php` with a direct include.

The `autoloader_real.php` file is generated by the AutoloadGenerator. 
He removed the [`public static function loadClassLoader`](https://github.com/composer/composer/blob/bda2c0f9b7dfc24616fe273d06f816a61abec9ef/src/Composer/Autoload/AutoloadGenerator.php#L551-L556). This function is registered as autoloading function (on top of the stack) with `spl_autoload_register()`, then `new ClassLoader` triggers the autoloading, so the `ClassLoader.php` file gets required, then the autoloading function is unregistered from the autoloading stack. 

I don't get the reason behind using `spl_*` to register an autoloader for including just one class/file.
The ClassLoader doesn't include/use other classes.
Is it a left-over or circumventing a cache or scope issue?

**Comment by stof** [comment]
> Very brief: He replaces the autoloading of ClassLoader.php with a direct include.

This was done in the past, and caused issues when loading several composer autoload files (for instance the global composer install and the project composer install)

**Comment by Seldaek** [comment]
The issue with the direct include was that APC failed in odd ways.. I think we can drop it at some point as hopefully opcache is now the standard on all high traffic site, but it doesn't hurt a whole lot to keep it either.
