### ISSUE TITLE
Cannot change ssl downgrade option for packagist (or at least reported wrong)

### ISSUE THREAD

**Issue by kleijnweb** [composer/composer#4721]
Only if the key is nested though. This:

```bash
-bash-4.2$ composer config --global discard-changes false && composer config --global --list | grep discard-changes
[discard-changes] false
-bash-4.2$ composer config --global discard-changes true  && composer config --global --list | grep discard-changes
[discard-changes] true
-bash-4.2$ 

```
.. works.

However, this:

```bash
composer config --global repositories.packagist.allow_ssl_downgrade false  && composer config --global --list | grep repositories.packagist.allow_ssl_downgrade
[repositories.packagist.allow_ssl_downgrade] true
```
Fails to change the option in --list, as you can see. The value *does* actually seem to be stored correctly:

```bash
$ cat $HOME/.composer/config.json 
{
    "config": {
        "cache-dir": "/data/satis/cache",
        "process-timeout": 120,
        "discard-changes": true},
    "repositories": {
        "packagist": {
            "allow_ssl_downgrade": false
        }
    }
}

```

If I change 'false' to 'true' (which reportedly it is already at), things get weirder:

```
                                                                                                           
  [RuntimeException]                                                                                       
  You must pass the type and a url. Example: php composer.phar config repositories.foo vcs http://bar.com  
```

So apparently there is an alternate syntax for repos, which is actually in the documentation:

```
composer.phar config repositories.foo vcs https://github.com/foo/bar
```

Error message starts to make a little sense now. Except that I still cant be confident the option is changed and respected.

If I try ` composer config --global repositories.packagist allow_ssl_downgrade false`, 'allow_ssl_downgrade' is blindly accepted as a 'vcs' option too. and 'false' as the URI. The allow_ssl_downgrade option is now completely gone (reflected in both `config.json` and `--list`).

```bash
composer config --global --list | grep reposi
[repositories.packagist.type] allow_ssl_downgrade
[repositories.packagist.url] false
-bash-4.2$ 
```

Which probably made sense at some point before the ssl downgrade option was added.

I guess I can just set `composer config --global repositories.packagist composer https://packagist.org`, but as far as DX goes, this falls short.

**Comment by alcohol** [comment]
This is because the packagist repository is added by default through code, not configuration. By adding this flag but not the default options associated with this repository (such as url), you are essentially overriding it with no values. The default url associated with packagist is `https?://packagist.org` (the `?` allows the http <---> https switching).

**Comment by Seldaek** [comment]
Yup the way to do that is simply to redefine the packagist repo as such:

`composer config --global repositories.packagist composer https://packagist.org`

Then the default one won't be added.
