### ISSUE TITLE
updating dependencies

### ISSUE THREAD

**Issue by sonkengmaldini15** [composer/composer#4722]
Hi, 
I wonder whether it's possible to update depencencies online 
For an existing and  working web site ?

**Comment by alcohol** [comment]
Yes, but it is not recommended.

**Comment by sonkengmaldini15** [comment]
I asked this because on my working website i have introduced composer autoloader 
and then i have added my folder to the autoloader but not working online but local it's clean.

**Comment by alcohol** [comment]
I don't understand?

**Comment by sonkengmaldini15** [comment]
You know went you want to add a folder to composer autoload like : ````php "autoload": {
       "psr-4": {"MicroCMS\\": "src"}
   },
Ok this infact works to local but online it's the case.

**Comment by fesor** [comment]
@sonkengmaldini15 you want to modify composer from WEB? Maybe just run `exec('composer dump -o')`, but this may lead to potential security issues.

**Comment by sonkengmaldini15** [comment]
Yes @fesor ! But where will i put the command you gave to me?
