### ISSUE TITLE
Could not stash changes

### ISSUE THREAD

**Issue by pedrambehroozi** [composer/composer#4723]
I run `composer update`. It warns me that two files are modified. I type `s` to stash changes and try to reapply them after the update. I get this error:

    [RuntimeException]                                                                 
      Could not stash changes                                                            
      :Usage: git stash list [<options>]                                                 
         or: git stash show [<stash>]                                                    
         or: git stash drop [-q|--quiet] [<stash>]                                       
         or: git stash ( pop | apply ) [--index] [-q|--quiet] [<stash>]                  
         or: git stash branch <branchname> [<stash>]                                     
         or: git stash [save [--patch] [-k|--[no-]keep-index] [-q|--quiet] [<message>]]  
         or: git stash clear

Composer version: `1.0-dev (c9501a4cc164b176de48e44b239e619cfd5f14e5) 2015-12-16 18:51:41`

**Comment by alcohol** [comment]
Did you try to manually stash the changes? It could be you are in the middle of a merge conflict, in which case git will not allow you to stash any changes.

**Comment by pedrambehroozi** [comment]
Yes, I can manually stash changes:

    Saved working directory and index state WIP on master: 10eebb5 links in mobile nav translation
    HEAD is now at 10eebb5 links in mobile nav translation

**Comment by alcohol** [comment]
That does not really make sense. Can you still reproduce the issue, while running the command in `-vvv`? That will allow you to see the actual git command that Composer is executing.

**Comment by pedrambehroozi** [comment]
Yes, I reproduced the issue. Here's the output of `php composer.phar update -vvv`:

    Executing command (/public_html/vendor/Vendor1/package): git stash --include-untracked
                                                                                         
      [RuntimeException]                                                                 
      Could not stash changes                                                            
      :Usage: git stash list [<options>]                                                 
         or: git stash show [<stash>]                                                    
         or: git stash drop [-q|--quiet] [<stash>]                                       
         or: git stash ( pop | apply ) [--index] [-q|--quiet] [<stash>]                  
         or: git stash branch <branchname> [<stash>]                                     
         or: git stash [save [--patch] [-k|--[no-]keep-index] [-q|--quiet] [<message>]]  
         or: git stash clear                                                             
                                                                                         
    Exception trace:
     () at phar:///public_html/composer.phar/src/Composer/Downloader/GitDownloader.php:334
     Composer\Downloader\GitDownloader->stashChanges() at phar:///public_html/composer.phar/src/Composer/Downloader/GitDownloader.php:163
     Composer\Downloader\GitDownloader->cleanChanges() at phar:///public_html/composer.phar/src/Composer/Downloader/VcsDownloader.php:112
     Composer\Downloader\VcsDownloader->update() at phar:///public_html/composer.phar/src/Composer/Downloader/DownloadManager.php:253
     Composer\Downloader\DownloadManager->update() at phar:///public_html/composer.phar/src/Composer/Installer/LibraryInstaller.php:196
     Composer\Installer\LibraryInstaller->updateCode() at phar:///public_html/composer.phar/src/Composer/Installer/LibraryInstaller.php:108
     Composer\Installer\LibraryInstaller->update() at /public_html/vendor/magento-hackathon/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Installer.php:225
     MagentoHackathon\Composer\Magento\Installer->update() at phar:///public_html/composer.phar/src/Composer/Installer/InstallationManager.php:172
     Composer\Installer\InstallationManager->update() at phar:///public_html/composer.phar/src/Composer/Installer/InstallationManager.php:139
     Composer\Installer\InstallationManager->execute() at phar:///public_html/composer.phar/src/Composer/Installer.php:604
     Composer\Installer->doInstall() at phar:///public_html/composer.phar/src/Composer/Installer.php:232
     Composer\Installer->run() at phar:///public_html/composer.phar/src/Composer/Command/UpdateCommand.php:143
     Composer\Command\UpdateCommand->execute() at phar:///public_html/composer.phar/vendor/symfony/console/Command/Command.php:259
     Symfony\Component\Console\Command\Command->run() at phar:///public_html/composer.phar/vendor/symfony/console/Application.php:841
     Symfony\Component\Console\Application->doRunCommand() at phar:///public_html/composer.phar/vendor/symfony/console/Application.php:192
     Symfony\Component\Console\Application->doRun() at phar:///public_html/composer.phar/src/Composer/Console/Application.php:167
     Composer\Console\Application->doRun() at phar:///public_html/composer.phar/vendor/symfony/console/Application.php:123
     Symfony\Component\Console\Application->run() at phar:///public_html/composer.phar/src/Composer/Console/Application.php:98
     Composer\Console\Application->run() at phar:///public_html/composer.phar/bin/composer:43
     require() at /public_html/composer.phar:25

**Comment by alcohol** [comment]
What happens if you manually run `git stash --include-untracked` ?

**Comment by pedrambehroozi** [comment]
Couldn't stash with `git stash --include-untracked`. Output:

    error: unknown option for 'stash save': --include-untracked
           To provide a message, use git stash save -- '--include-untracked'
    Usage: git stash list [<options>]
       or: git stash show [<stash>]
       or: git stash drop [-q|--quiet] [<stash>]
       or: git stash ( pop | apply ) [--index] [-q|--quiet] [<stash>]
       or: git stash branch <branchname> [<stash>]
       or: git stash [save [--patch] [-k|--[no-]keep-index] [-q|--quiet] [<message>]]
       or: git stash clear

**Comment by alcohol** [comment]
What version of `git` do you have?

**Comment by pedrambehroozi** [comment]
1.7.1

**Comment by alcohol** [comment]
Ouch.. that's old. It does not seem to support the flag we are using.

**Comment by Seldaek** [comment]
I think we have to define a minimum reasonable version at some point. Keeping git up to date is pretty easy and also a good idea.

**Comment by alcohol** [comment]
I would be in favor of that. Having to do version detection and multiple codepaths depending on detected version sounds like a recipe for just more bugs. Alternatively, we could look at whether or not there is an existing php git library that abstracts all of this already and that is well tested and supported (though it's unlikely we will find one that still supports php 5.3).

**Comment by Seldaek** [comment]
I'd say we can just close this.. unless someone wants to work on adding version detection. It's not really a widespread issue, and I hope @pedrambehroozi can simply upgrade git and move on :)

**Comment by alcohol** [comment]
@seldaek one peculiarity I just noticed, our error returned:

```
[RuntimeException]                                                                 
  Could not stash changes                                                            
  :Usage: git stash list [<options>]                                                 
     or: git stash show [<stash>]                                                    
     or: git stash drop [-q|--quiet] [<stash>]                                       
     or: git stash ( pop | apply ) [--index] [-q|--quiet] [<stash>]                  
     or: git stash branch <branchname> [<stash>]                                     
     or: git stash [save [--patch] [-k|--[no-]keep-index] [-q|--quiet] [<message>]]  
     or: git stash clear
```

but when he ran the same command manually he got back:

```
error: unknown option for 'stash save': --include-untracked
       To provide a message, use git stash save -- '--include-untracked'
Usage: git stash list [<options>]
   or: git stash show [<stash>]
   or: git stash drop [-q|--quiet] [<stash>]
   or: git stash ( pop | apply ) [--index] [-q|--quiet] [<stash>]
   or: git stash branch <branchname> [<stash>]
   or: git stash [save [--patch] [-k|--[no-]keep-index] [-q|--quiet] [<message>]]
   or: git stash clear
```

Why did we not include that error line? That would have made it much easier/quicker to spot what went wrong. Perhaps something wrong in our parsing of and/or output gathering?

**Comment by Seldaek** [comment]
Maybe some of it went to stderr and some to stdout in git?

**Comment by pedrambehroozi** [comment]
@Seldaek Agree. But my user on this server I'm working with doesn't have root privileges, so I can't upgrade git. I'm going to ask them to upgrade it for me, but since composer doesn't need any super privilege, it would be nicer if we could just download and use it.

**Comment by alcohol** [comment]
> it would be nicer if we could just download and use it

@pedrambehroozi and you can do that :-)

But we simply cannot keep supporting outdated software forever. This has little to do with root privileges, and more with finding proper hosting parties that don't serve their users outdated environments.

**Comment by pedrambehroozi** [comment]
@alcohol Fair enough :)
