### ISSUE TITLE
composer diagnose should not fail, when using latest release

### ISSUE THREAD

**Issue by schmunk42** [composer/composer#4724]
Currently `composer diagnose` checks only if the installed version is the same as [latest](https://github.com/composer/composer/blob/dc0627617935da9208124e580b9f0e39dd214ae5/src/Composer/Command/DiagnoseCommand.php#L312) and reports an error if eg. `alpha11` is installed.

I think latest and **latest release** should be OK.

**Comment by alcohol** [comment]
Since there are no stable releases yet, I disagree.

**Comment by schmunk42** [comment]
@alcohol Is there an issue about a stable release? Personally, I had more problems with `dev-master` than with `alphaXY` in the past, but it's a valid point.

Related discussions:
- https://github.com/composer/composer/issues/3707
- https://github.com/composer/composer/issues/3779

**Comment by curry684** [comment]
This is going to be fixed through channels in https://github.com/composer/composer/issues/4960. The separate issues leading up to that conclusion can be closed imo.
