### ISSUE TITLE
Command "self-update" is not defined.

### ISSUE THREAD

**Issue by Lemmmy** [composer/composer#4725]
I am using the latest composer on apt. When running `composer require intervention/image`, I get the following output:

![](http://ichi.lemmmy.pw/commissions_batch.png)

When running `composer self-update` or `sudo composer self-update`, I get this:

![](http://ichi.lemmmy.pw/cigarette_packets.png)

I have tried reinstalling composer, but the same happens.

```PHP 5.6.11-1ubuntu3.1 (cli)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans```

**Comment by alcohol** [comment]
Can you show actual console output, including the input (command) that you are using, instead of screenshots?

Also, please share your composer.json with us. I was unable to find the `4.x.x` constraint your error reported in the composer.json of `intervention/image`.

**Comment by stof** [comment]
> Also, please share your composer.json with us. I was unable to find the 4.x.x constraint your error reported in the composer.json of intervention/image.

Look at the 1.4.0 release of the package. It has such requirement. I guess this fails because of an old version of composer being used, not able to normalize this version.

Regarding ``self-update``, it might not be available in your composer is not installed as a phar.

**Comment by Lemmmy** [comment]
I'll try uninstalling composer from apt and install it via phar instead.

**Comment by Lemmmy** [comment]
I couldn't fetch the old input since I reinstalled a lot of stuff on the system since my report, but installing composer as a phar fixed the issue. I guess the version on `wily`'s apt is out of date?

**Comment by stof** [comment]
I did not even know there was an apt version of composer. And I'm 100% sure it is not an official installation channel

**Comment by Lemmmy** [comment]
Well that probably explains it.

**Comment by denners777** [comment]
Maybe if you run the command 'apt-get update' work.

**Comment by josephdpurcell** [comment]
Here is how I solved it:

```
vagrant@sites:~$ which composer
/home/vagrant/.config/composer/vendor/bin/composer
vagrant@sites:~$ composer global update composer/composer
Changed current directory to /home/vagrant/.config/composer
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing composer/composer (1.2.0)
  - Installing composer/composer (1.3.2)
    Downloading: 100%         

Writing lock file
Generating autoload files
vagrant@sites:~$ composer --version
Composer version 1.3.2 2017-01-27 18:23:41
```

**Comment by stof** [comment]
well, ``self-update`` is indeed only available when you install composer as a phar, not as a dependency in the global project

**Comment by vkalchenko** [comment]
yum upgrade composer also helps

**Comment by imakeinternet** [comment]
If you're using Ubuntu then `sudo apt-get upgrade composer` did the trick for me.
