### ISSUE TITLE
"path" repositores brokes lock on windows

### ISSUE THREAD

**Issue by stas-dovgodko** [composer/composer#4726]
```
"repositories": [
        {
            "type": "path",
            "url": "./lib/project5*"
        }
    ],
```

lock file after update on win looks like

```
"dist": {
                "type": "path",
                "url": "./lib/project5\\",
                "reference": "27b2e43f5e70ca8761ab2d9e0194c237",
                "shasum": null
            },
```

and does not work on linux after

**Comment by alcohol** [comment]
@seldaek did we actually test globbing support for the path repository? Could it be that it behaves differently on Windows?

**Comment by Seldaek** [comment]
I didn't test it.. And yes I guess it could be as glob would likely return windows paths with backslashes.

**Comment by curry684** [comment]
Happened to have a perfect test case lying around, and yes it does. PR coming up in a second.
