### ISSUE TITLE
when I install composer php 7 automatically deleted.

### ISSUE THREAD

**Issue by MicroDreamIT** [composer/composer#4728]
Its vise versa. When i install composer php7 deleted, and when i install php7 composer deleted. How can i merge them together working? Any idea or suggestion?

**Comment by stof** [comment]
how are you installing them ?

**Comment by MicroDreamIT** [comment]
@stof brother, 
almost its look like,
sudo apt-get install composer 
sudo apt-get install php7
sudo apt install php7-mysql

in apache

**Comment by alcohol** [comment]
apt packages are not an official install procedure supported by composer. They probably have dependencies declared that are invalid, which results in the removal/conflict with php7.

Simply install php7 and then install composer using a Composer supported install procedure:
https://getcomposer.org/download/

**Comment by MicroDreamIT** [comment]
@alcohol if i install composer later then php7 deleted because in composer, install.json has require php>=5.5.9, so its automatically delete php7 and install php5 again.

**Comment by xabbuh** [comment]
@MicroDreamIT This will not happen when you download and install Composer from https://getcomposer.org/download/.

**Comment by MicroDreamIT** [comment]
@xabbuh @alcohol @stof brother finally solve this problem. So if you want to use php7 then you can not use command sudo apt-get install composer. But its working together after download install using curl.

**Comment by alcohol** [comment]
@MicroDreamIT Yes. Composer will never install/uninstall PHP versions. It simply cannot do that. The apt packages however might be configured differently. This is why we do not recommend using them.
