### ISSUE TITLE
update --root option for only updating root packages

### ISSUE THREAD

**Issue by davidbarratt** [composer/composer#4729]
It would be really helpful if there was a `--root` option for `composer update` that would allow you to just update the packages in the root composer.json file. Using `--root` with `--with-dependencies` is the same as using `composer update` without those options.

The reason I'm asking for this, is that it's difficult to determine which root packages need updating (and therefor need more testing as they are direct dependencies) vs. which are just dependencies of root packages. The only way you can do this right now is by manually comparing the output you get with `composer update` with what you have in your `composer.json` file.

**Comment by davidbarratt** [comment]
@sethcardoza,

I think this would help us out a lot.

**Comment by alcohol** [comment]
So what do you propose Composer should do when it tries to update a dependency in your root composer.json which has new requirements that require Composer to also update some sub dependencies? Should it not update your root dependency? Should it still update those sub dependencies (current behaviour)? Should it only update the root dependency and consequently leave your `vendor` directory in a state of conflict?

**Comment by davidbarratt** [comment]
@alcohol,

It should have the same behavior as white listing a list of packages, and not using `--with-dependencies`. Basically the `--root` option would just be a white list of packages from the root `composer.json` file.

I believe in the scenario you describe, Composer throws an exception. Since this is exiting behavior, adding the option should be somewhat trivial. I didn't want to code this without buy-in from a maintainer though.

**Comment by Seldaek** [comment]
Sounds like an ok feature addition, but I'm not too happy with --root as I initially didn't understand what you meant before reading the description in detail. --root sounds to me like you're updating the root package itself which is nonsensical :) 

Not sure what a better name would be though, in a way it's like a `--depth=0`. That would be more flexible too but I'm not sure if there is a point in doing `--depth=1` for example. Maybe `--top-level`? `--root-reqs`?

**Comment by davidbarratt** [comment]
@Seldaek,

Awesome. I took the `--root` from here:
https://getcomposer.org/doc/04-schema.md#root-package
I assumed that that "root" was an already defined term...
but maybe `--root-only` would be better?

**Comment by Seldaek** [comment]
Yeah I just mean that the root package is *your* application package in a way, and updating that doesn't mean anything to me.. I would imagine that would do a `git pull` on your repo or some-such :) What you really mean is updating only the root requirements without their requirements, at least that sounds clearer to me ;)

**Comment by davidbarratt** [comment]
@Seldaek,

Oh I see what you are saying. That makes more sense.
