### ISSUE TITLE
Issue with Yii2

### ISSUE THREAD

**Issue by TanglerDS** [composer/composer#4734]
Hello, I have a strange problem here. Composer loads and installs Yii 1.1.16 perfectly, but absolutely refuses to load Yii2. Says "could not find stable version". Tried to set minimum-stability to "dev" - nothing. Server: apache. What could cause such an issue?

**Comment by alcohol** [comment]
Please provide some actual information. 

- What command did you try to run? 
- What was the output Composer returned? 
- What does your composer.json look like?

**Comment by TanglerDS** [comment]
First, I try it as it is stated on yii official site: composer create-project yiisoft/yii2-app-basic basic 2.0.6
Then I try the following:
composer create-project yiisoft/yii2
composer create-project yiisoft/yii2-app-basic
composer create-project yiisoft/yii2-app-basic 2.0.*
composer require "yiisoft/yii2-app-basic" : "@dev"
Nothing seems to work, the output is: could not find package, check your spelling or minimum-stability.
However, the commend: composer create-project yiisoft/yii - works perfectly and installs Yii 1.1.16
json file in root has this in it:
{
    "minimum-stability": "dev", "require": {
        "fxp/composer-asset-plugin": "~1.1.1"
    }
}
First I thought it may be issue with minimum-stability, but the current version of Yii2 looks to be stable
Thanks in advance

**Comment by osavchenko** [comment]
@TanglerDS could you show extended error message?

**Comment by xabbuh** [comment]
It looks like Yii2 needs the Composer Asset plugin (see https://github.com/yiisoft/yii2-framework#installation) to be able to install Bower packages through Composer. Imho that's more a documentation issue of Yii itself. They should make it more clear that you need the plugin. At least, it's not related to Composer itself.

**Comment by lichunqiang** [comment]
You should delete the `vendor` folder firstly and run:

* composer self-update
* composer global require  fxp/composer-asset-plugin=~1.1.1 
* composer install

**Comment by TanglerDS** [comment]
Problem solved - my PHP version was outdated. Thank you all for your answers

**Comment by xabbuh** [comment]
@TanglerDS Please close the issue then.
