### ISSUE TITLE
composer update: allow_url_fopen must be enabled in php.ini

### ISSUE THREAD

**Issue by younishd** [composer/composer#4740]
When I run `composer update` I get the following message:

```
Loading composer repositories with package information

[Composer\Downloader\TransportException]

The "http://packagist.org/packages.json" file could not be downloaded: allow_url_fopen must be enabled in php.ini (http:// wrapper is disabled in the server configuration by allow_url_fopen=0 failed to open stream: no suitable wrapper could be found)
...
```

I never had this bug before (didn't change my `php.ini` either) and I definitely don't want to enable `allow_url_fopen` to use composer.

Using `Composer version 1.0.0-alpha11 2015-11-14 16:21:07`

__Edit:__ Downgrading to `alpha10` solved it so far.

**Comment by alcohol** [comment]
`allow_url_fopen` has been a requirement for quite a long time, considering Composer internally uses `file_get_contents()` all over the place (which requires `allow_url_fopen` for url's). 

It seems rather unlikely that downgrading to alpha10 actually solves anything, since the code hasn't really changed in that regard since then (or even before that).

**Comment by younishd** [comment]
I have an issue with the `alpha11` on several machines and each time I had to downgrade.

On another machine I have the following problem (which is as well related to some `php.ini` settings)

```
% composer update
PHP Warning:  Phar::mapPhar(): open_basedir restriction in effect. File(/usr/bin/composer) is not within the allowed path(s): (/home/web/:/tmp/:/usr/share/pear/:/usr/share/webapps/:/etc/webapps/) in /usr/bin/composer on line 23
PHP Warning:  require(): open_basedir restriction in effect. File(composer.phar) is not within the allowed path(s): (/home/web/:/tmp/:/usr/share/pear/:/usr/share/webapps/:/etc/webapps/) in /usr/bin/composer on line 24
PHP Warning:  require(phar://composer.phar/bin/composer): failed to open stream: phar error: invalid url or non-existent phar "phar://composer.phar/bin/composer" in /usr/bin/composer on line 24
PHP Fatal error:  require(): Failed opening required 'phar://composer.phar/bin/composer' (include_path='.:/usr/share/pear') in /usr/bin/composer on line 24
```

I get this kind of error with any command (not just `update`).

Downgrading to `alpha10` does solve it as well.

```
% yaourt -U /var/cache/pacman/pkg/php-composer-1.0.0.alpha10.411-1-any.pkg.tar.xz 
loading packages...
warning: downgrading package php-composer (1.0.0.alpha11-1 => 1.0.0.alpha10.411-1)
...
```

Then

```
% composer update
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "/usr/bin/composer self-update" to get the latest version.
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing erusev/parsedown (1.6.0)
    Loading from cache

  - Installing erusev/parsedown-extra (dev-master 0db5cce)
    Cloning 0db5cce7354e4b76f155d092ab5eb3981c21258c

  - Installing younishd/endobox (1.0.0)
    Loading from cache

Writing lock file
Generating autoload files
```

Tadaaa.

**Comment by staabm** [comment]
Did you check `composer diagnose`?

**Comment by younishd** [comment]
```
% composer diagnose
PHP Warning:  Phar::mapPhar(): open_basedir restriction in effect. File(/usr/bin/composer) is not within the allowed path(s): (/home/web/:/tmp/:/usr/share/pear/:/usr/share/webapps/:/etc/webapps/) in /usr/bin/composer on line 23
PHP Warning:  require(): open_basedir restriction in effect. File(composer.phar) is not within the allowed path(s): (/home/web/:/tmp/:/usr/share/pear/:/usr/share/webapps/:/etc/webapps/) in /usr/bin/composer on line 24
PHP Warning:  require(phar://composer.phar/bin/composer): failed to open stream: phar error: invalid url or non-existent phar "phar://composer.phar/bin/composer" in /usr/bin/composer on line 24
PHP Fatal error:  require(): Failed opening required 'phar://composer.phar/bin/composer' (include_path='.:/usr/share/pear') in /usr/bin/composer on line 24
```

**Comment by staabm** [comment]
Does it work when you disable the open-basedir restrictions?

**Comment by xabbuh** [comment]
Imho it looks strange to save the phar file in a directory that isn't included in your `open_basedir` settings.

**Comment by fabienwang** [comment]
Tested over here with the same package (php-composer) on ArchLinux:

with latest package
php-composer-1.0.0.alpha11
`composer update` fails as indeed it asks for allow_url_fopen to be On
php-composer-1.0.0.alpha10.411-1-any.pkg.tar.xz
-> any `composer update` just works, even though I disabled allow_url_fopen in my /etc/php/php.ini

So @younishd is right, something is messed up with the current alpha11 we have on Arch Linux.

**Comment by alcohol** [comment]
Please, do not post here with issues about Composer binaries provided through OS package managers. These are unsupported and not created/maintained by the Composer developers. There is really no need to use those are the installation instructions of Composer are very straight forward. Any issues raised here are quite rudimentary and easy to solve.

**Comment by younishd** [comment]
@alcohol Nice…
As I said, the same thing happens when you try to install composer the official way using the installation instructions from the website, so it is _not_ a distro problem or anything like that (besides the fact that it all works with `alpha10` and fails with `alpha11`).

**Comment by alcohol** [comment]
`open_basedir` is a PHP setting and not something Composer can modify. This is up to the end user. If you do not know what `open_basedir` does or how you can change it, then you should read into the basics of configuring PHP. This is outside of the scope of what the Composer project aims to document.

**Comment by younishd** [comment]
That's why the exact same PHP config works for some version of composer and fails for another.

**Comment by alcohol** [comment]
> That's why the exact same PHP config works for some version of composer and fails for another.

Unlikely, and unless you can provide us with reproducible steps, please refrain from making statements that cannot be validated.

**Comment by younishd** [comment]
You're right.

I'll just leave [this](https://wiki.archlinux.org/index.php/PHP#Configuration) here for anyone who runs into the same issue on ArchLinux:

> Tip: Prior to 22 November 2015, php-composer kept its settings in a separate file in /usr/share/php-composer/php.ini
