### ISSUE TITLE
Composer installation error shows php file not executing correctly on xampp

### ISSUE THREAD

**Issue by vignesh137** [composer/composer#4741]
I am trying install composer but can't. help me sortout the issue.
The PHP exe file you specified did not execute correctly: 
E:\xampp\php\php.exe

Running it from the command line might highlight the problem.
Internal Error [ERR_STATUS], exit code -1073741819

**Comment by nutandevjoshi** [comment]
Buddy, Composer has worst documentation and worst coding, I found the proper way.

php -r "readfile('https://getcomposer.org/installer');" | php
>> This used to give me some errors like xampp/php_*xyz extension is not installed.

I am pretty smart. I did it myself. I use normally D drive for XAMPP. Now moved it to C drive and your 2nd solution worked.
