### ISSUE TITLE
Autoload files wildcarding 

### ISSUE THREAD

**Issue by northborndesign** [composer/composer#4742]
This is a feature request for autoloading files by wildcard. Using `fnmatch` patterns, autoloading functions (and other non-class) definitions would be made considerably easier.

``` javascript
"autoload": {
    "files": ["src/**/functions.*"]
}
```

The above example would recursively load all files under `src` matching `functions.*` (such as `functions.php`, `functions.inc`, etc.)

**Comment by alcohol** [comment]
I believe just recently `exclude-from-classmap` was added, which has support for wildcards ([see docs](https://getcomposer.org/doc/04-schema.md#exclude-files-from-classmaps)). I imagine the same could easily be applied to `classmap`/`files`.

**Comment by stof** [comment]
@alcohol ``exclude-from-classmap`` contains a regex to build the blacklist regex. It does not contain a glob. the doc is wrong here (it is documented an implementation from the initial PR submission, not the final codebase)

**Comment by alcohol** [comment]
Well I didn't merge it, so I absolve myself from all blame :d

But, that probably should be adjusted/fixed then.

**Comment by cs278** [comment]
@stof Use of regex is an implementation detail, you cannot use a regex in the config: https://github.com/composer/composer/blob/72cd6afdfce16f36a9fd786bc1b2f32b851e764f/src/Composer/Autoload/AutoloadGenerator.php#L713-L718

**Comment by northborndesign** [comment]
I had a reasonably naive implementation that I put together as a hook script, pointed to `AutoloadBuilder::buildAutoloader`. It did similarly with the regex translation for recursive glob patterns:

```php
final class AutoloadBuilder
{

    /**
     *
     * @param Event $event
     * @return void
     */
    public static function buildAutoloader(Event $event)
    {
        $composer = $event->getComposer();
        $package = $composer->getPackage();
        $autoloadMap = $package->getAutoload();
        if (empty($autoloadMap['files'])) {
            return;
        }
        $path = realpath(sprintf('%s/..', $composer->getConfig()->get('vendor-dir')));
        $filenameArray = [];
        foreach ($autoloadMap['files'] as $pattern) {
            foreach (static::getFilenameGenerator($path, $pattern) as $filename) {
                $filenameArray[] = $filename;
            }
        }
        $autoloadMap['files'] = $filenameArray;
        $package->setAutoload($autoloadMap);
    }

    /**
     *
     * @param string $pattern
     * @return string
     */
    private static function transformPattern($pattern)
    {
        $transformedPattern = preg_replace_callback('(([*]{2}|[*]|[?]|[/\\\\]|[^*/\\\\?]+))', function ($matchArray) {
            $match = current($matchArray);
            switch ($match) {
                case '**': return '(?:.*?)';
                case '*': return '(?:[^/\\\\]*?)';
                case '?': return '(?:[^/\\\\])';
                case '\\':
                case '/': return '(?:[/\\\\])';
            }
            return preg_quote($match, '()');
        }, $pattern);
        return sprintf('((?:%s)$)', $transformedPattern);
    }

    /**
     *
     * @param string $path
     * @param string $pattern
     * @return Generator
     */
    private static function getFilenameGenerator($path, $pattern)
    {
        $directoryIterator = new RecursiveDirectoryIterator($path);
        $iteratorIterator = new RecursiveIteratorIterator($directoryIterator);
        $regexIterator = new RegexIterator($iteratorIterator, static::transformPattern($pattern));
        foreach ($regexIterator as $file) {
            yield $file->getPathName();
        }
    }

}
```

**Comment by Seldaek** [comment]
Related to #4383 which is the same request for psr-0/psr-4. Not really sure it's so valuable though, being explicit is also an advantage sometimes.

**Comment by Seldaek** [comment]
Closing as quite unlikely to be worked on sorry
