### ISSUE TITLE
GitLab driver uses ssh instead of https when using --prefer-source

### ISSUE THREAD

**Issue by aadmathijssen** [composer/composer#4744]
When the GitLab driver is used to install a module using `--prefer-source`, ssh is used instead https:
```
$ composer config repositories.foo-bar vcs https://gitlab.com/foo/bar
$ composer require foo/bar --prefer-source
```

When ssh is not set up, the last command gives the following result:

```
Using version ~1.0 for foo/bar
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing foo/bar (v1.2.3)
    Cloning 9876543210fedcba9876543210fedcba
    Failed to download foo/bar from source: Failed to execute git clone --no-checkout 'git@gitlab.com:foo/bar.git' '/path/to/project/vendor/foo/bar' && cd '/path/to/project/vendor/foo/bar' && git remote add composer 'git@gitlab.com:foo/bar.git' && git fetch composer

Cloning into '/path/to/project/vendor/foo/bar'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    Now trying to download from dist
```

I can understand that ssh used as a fallback, but not when the repository url is specified with https and a source download is explicitly requested.

**Comment by alcohol** [comment]
I think that if you run it in `-vvv` mode, you will see that Composer tries multiple protocols before actually giving up.

**Comment by aadmathijssen** [comment]
I tried that, but it shows that only one git clone command (using ssh) is executed.

The only extra info in the output between the "Cloning and "Failed to download" lines (disregarding error messages that are repeated later on), is the following:

```
Executing command (CWD): git clone --no-checkout 'git@gitlab.com:foo/bar.git' '/path/to/project/vendor/foo/bar' && cd '/path/to/project/vendor/foo/bar' && git remote add composer 'git@gitlab.com:foo/bar.git' && git fetch composer
Executing command (CWD): git --version
```

**Comment by Seldaek** [comment]
This is what determines the URL used for source installs https://github.com/composer/composer/blob/master/src/Composer/Repository/Vcs/GitLabDriver.php#L176 and as you can see  it uses the ssh URL there https://github.com/composer/composer/blob/master/src/Composer/Repository/Vcs/GitLabDriver.php#L150 - I am not sure if that's the best way or how to improve it as I have no clue how gitlab works. Ping @gromnan

**Comment by GromNaN** [comment]
The usage of HTTP or SSH as repository URL could be detected in the `init` method and stored in an attribute. Then the method `getRepositoryUrl` would return the ssh_url_to_repo or http_url_to_repo

**Comment by aadmathijssen** [comment]
Hi @GromNaN,

I wanted to implement your suggestion of detecting whether it's best to return `ssh_url_to_repo` or `http_url_to_repo` as the repository url, but before doing that I was curious to see how the other git drivers determined the url for source installs.

This is the url that is returned as the `'url'` part of the result of the `getSource` method for the different git drivers:
* GitDriver: `$this->url`
* GitBitBucketDriver: `$this->url`
* GitHubDriver:
  * `$this->url` when the `no-api` option is set
  * HTTPS url for public repositories
  * SSH url for private repositories or when attempting a non-interactive clone fallback when a 404 or 403 occur occurred
* GitLabDriver: SSH url

Do you know if there is any reason why we can't just use `$this->url` just as in the GitDriver and GitBitBucketDriver implementations?

Thanks.

Aad

**Comment by alecpl** [comment]
@GromNaN: I think that's not as simple as that. I see problem is in fetchProject().

**Comment by alecpl** [comment]
Gitlab ticket about making their API accessible for non-authenticated users https://gitlab.com/gitlab-org/gitlab-ce/issues/14213

**Comment by aadmathijssen** [comment]
To me, PR https://github.com/composer/composer/pull/5591 makes the situation more confusing: not only an SSH url is used when a private GitLab repository is specified using HTTP (which was already the case), but now also an HTTP url is used when a public GitLab repository is specified using SSH.

I understand that the url needs to be changed when using `--prefer-dist`, but not when using `--prefer-source`.

**Comment by mlncn** [comment]
I think this is biting me also.  I *want* to use the SSH URL which i've specified, and it's getting switch to an HTTPS URL.

**Comment by Seldaek** [comment]
If it's so important I'd suggest you use "type":"git" instead of `vcs` to force it to do a git clone.

**Comment by mlncn** [comment]
@Seldaek tried that; and it still was not working so i've been writing up another issue: #7771

Thanks!

**Comment by mlncn** [comment]
I was wrong and Saldaek was right— i had been failing to delete my composer.lock file and was (uncharacteristically for me) testing with composer install rather than composer update.  Using type git instead of type vcs does work!

**Comment by bradjones1** [comment]
Refs https://github.com/composer/composer/pull/8001
