### ISSUE TITLE
composer my nightmare

### ISSUE THREAD

**Issue by emiglobetrotting** [composer/composer#4745]
i don't know how to make it work; i'm trying to install a project that requires a composer installation. when i try to install the composer i'm having the is error

```
Some settings on your machine make Composer unable to work properly.
Make sure that you fix the issues listed below and run this script again:

The json extension is missing.
Install it or recompile php without --disable-json

The phar extension is missing.
Install it or recompile php without --disable-phar

The filter extension is missing.
Install it or recompile php without --disable-filter

The hash extension is missing.
Install it or recompile php without --disable-hash

The openssl extension is missing, which means that secure HTTPS transfers are impossible.
If possible you should enable it or recompile php with --with-openssl
```

To solve the openssl extension missing problem; i've installed openssl 1.0.1q and link ssl/bin/openssl to usr/bin/openssl;  meanwhile openssl is in my usr/local/src/php-5.6.13/ext.

The other missing i enabled them via the ./configure command option with, --enable-filter, --enable-hash, --enable-json, --enable-phar. To be precise you will find the configuration

./configure \
    --prefix='/usr/local/src/php-5.6.13' \
    --disable-cgi \
    --with-libdir='/lib/x86_64-linux-gnu/' \
    --with-config-file-path='/etc/php5' \
    --with-zlib \
    --with-pcre-regex \
    --with-mysql \
    --with-pdo-mysql \
    --with-mysqli \
    --enable-simplexml \
    --enable-xml \
    --enable-mysqlnd \
    --enable-pcntl \
    --enable-debug \
    --enable-maintainer-zts \
    --enable-mbstring \
    --enable-bcmath \
    --enable-exif \
    --enable-ftp \
    --enable-soap \
    --enable-sockets \
    --enable-opcache \
    --enable-zip \
    --enable-embedded-mysqli \
    --with-fpm-user=www-data  \
    --with-fpm-group=www-data \
    --enable-fpm \
    --enable-session \
    --enable-sysvmsg \
    --enable-sysvsem \
    --enable-sysvshm \
    --enable-xmlreader \
    --enable-xmlwriter \
    --enable-phar \
    --enable-json \
    --enable-hash \
    --enable-libxml \
    --enable-filter \
    --with-openssl \
    --with-curl

I've done the following below before running the ./configure and when i run make && make install i'm having this underneath some long running text that stops then this message appears. the message is this "No rule to make target `pharcmd', needed by `all'. Stop."

rm ./configure
rm -rf autom4te.cache/
rm -rf aclocal.m4
./buildconf --force
make clean.

Please how can i solve my problem.

**Comment by staabm** [comment]
You also need to load the extensions in your php.ini

**Comment by nutandevjoshi** [comment]
Buddy, Composer has worst documentation and worst coding, I found the proper way.

php -r "readfile('https://getcomposer.org/installer');" | php
>> This used to give me some errors like xampp/php_*xyz extension is not installed.

I am pretty smart. I did it myself. I use normally D drive for XAMPP. Now moved it to C drive and your 2nd solution worked.

**Comment by alcohol** [comment]
Composer has nothing to do with how you compile PHP. It simply points out what it needs/expects. If your compiled version does not offer that, then either recompile, or use any of the common default binaries provided for Linux/OSX/Windows which do contain everything that is necessary.

This issue is more about installing and configuring PHP though, so I'm closing it.

**Comment by gilcierweb** [comment]
Composer is garbage this kind of mistake should not happen, error unacceptable.
