### ISSUE TITLE
Do I Need Ph.D. in Composer to install it? Usless & Impossible Installation!! Can't installation and document be at least 1% proper?

### ISSUE THREAD

**Issue by nutandevjoshi** [composer/composer#4746]
This is useless time pass thing or what?????

I tried installing your so called Composer in 10000000 different ways, and guess what its NOT installing. And better your document is Nothing! It just has 3 lines, do this 1st way do that 2nd way.

You SHOULD have How to troubleshoot section which elaborates how to solve your composer installation issues.

Your lack of good documentation wasted my(and 1000000 other people's) time.

Now back to my point.
Your 1st way to install

curl -sS https://getcomposer.org/installer | php
>> Says : 'curl' is not recognized as an internal or external command,
operable program or batch file.

Now your 2nd way 
php -r "readfile('https://getcomposer.org/installer');" | php
xyzabcdef extension is not installed etc.

I DONT NEED your BAD documentation, I did it myself. I use normally D drive for XAMPP. Now moved it to C drive and your 2nd solution worked.

For lord Buddha, Jesus sake , TELL THE PEOPLE THAT YOU SHOULD HAVE XAMPP Directory in C driver only . Or tell them your weak PHP coding skills cant determine XAMPP location https://getcomposer.org/installer file always assumes your xampp is on on C drive.

Post this somewhere so you wont waste 10000000 hours of people.

And overall NOT happy with your BAD coding skills.

**Comment by Mika56** [comment]
The doc already indicates the existence of the [Windows Installer](https://getcomposer.org/Composer-Setup.exe).

**Comment by farazdagi** [comment]
Sometimes I wish there was some kind of exam, which you are required to pass, before you are able to share your thoughts publicly.

P.S. I secretly hope that it is all just a bad and tasteless joke.

**Comment by blazarecki** [comment]
http://todogroup.org/opencodeofconduct/ 

> Be careful in the words that we choose: we are a community of professionals, and we conduct ourselves professionally. Be kind to others. Do not insult or put down other participants. Harassment and other exclusionary behavior aren’t acceptable.

And a happy new year.

**Comment by MarkBaker** [comment]
Nobody is forcing you to use Composer

If you feel that the developers of Composer have such bad coding skills, then I'm surprised that you even want to use it, clearly somebody who can recognise such incompetence is somebody who could develop their own far superior alternative.

**Comment by mdwheele** [comment]
Happy New Year, @Seldaek! Remember the "ounce of truth" in every issue in Open Source and maybe consider that now *might* be the right time for you to start that online education career you always wanted. A Ph.D. in Composer *might just be* what saves us all.

All kidding aside, have a good one. Love me some Composer!

**Comment by motanelu** [comment]
I remember laughing my ass off during @Seldaek's presentation at Symfony Con 2015 when talking about this kind of behaviour. I hope this guy gets included in the new version of his slides :)))

**Comment by bobmajdakjr** [comment]
This guy sounds like most of the people I get on my Skyrim mods.

**Comment by chrisatsc** [comment]
> You SHOULD have How to troubleshoot section which elaborates how to solve your composer installation issues.

You SHOULD be able to read documentation that clearly delineates the separate installation instructions for Linux/Unix/Mac OS and Windows and follow those instructions appropriate for the operating system on which you're installing composer.

**Comment by belisarh** [comment]
@Seldaek thank you for your amazing work :).

**Comment by nutandevjoshi** [comment]
Sorry, I went a little far. Hi @Mika56 , last night I even tried https://getcomposer.org/Composer-Setup.exe as well. But it says php exe not found like that. :) And by the way I properly gave path like D:\xampp\php\php.ini(I copy pasted from file explorer). Can you please make documentation suggesting solution. It works when I have XAMPP on C drive but doesn't when its on D.

Can you please consider it as an issue/bug. Or you still believe there is no issue in composerinstaller exe file. Please accept it as a bug and post my solution(xampp should be in C drive), rather than saying 'no no, we dont have bug in our exe file, please read documentation and all'. Thank you. I hope you will experiment the same xampp drive issue in your system, and post in documentation 'have xampp in c drive'. 

This would help many users who struggle installing composer. 

Thank you again ! Have a nice year ahead, and please start accepting the truth that there may be bugs in installer, and there is nothing to be ashamed of.

![composer](https://cloud.githubusercontent.com/assets/6582341/12073220/719ada84-b138-11e5-9a3e-4de9cc095f0c.png)

**Comment by Seldaek** [comment]
@nutandevjoshi please open an issue on https://github.com/composer/windows-setup/issues with details as to how to reproduce that failure if php is installed on D: instead of C:. And please remain civil if you want people to help you.

As for enabling extensions, yes we do require some extensions to be enabled for core functionality, and there is a clear message saying that and telling you to enable them in php.ini file. Maybe reporting a bug over at the XAMPP project would be a good idea too, because if they still ship a php without openssl extension enabled by default (we really don't require much else..) that's a terrible idea and a disservice to their users.
