### ISSUE TITLE
Internal Error [ERR_CMD]: The system cannot find the file specified

### ISSUE THREAD

**Issue by henrytran9x** [composer/composer#4747]
Hi i install Composer for windows 7 ! I had error "Internal Error [ERR_CMD]: The system cannot find the file specified". How did fixed it ? 

Thank you !

**Comment by xabbuh** [comment]
Did you see https://getcomposer.org/doc/articles/troubleshooting.md#-the-system-cannot-find-the-path-specified-windows-?

**Comment by henrytran9x** [comment]
Thanks ! I done it !
