### ISSUE TITLE
Get devMode from plugin

### ISSUE THREAD

**Issue by gossi** [composer/composer#4749]
I wanted to know from a plugin whether devMode is enabled or not, via the passed `--(no-)dev` flag. There was no such simple `getDevMode()` method on any available methods of the  `$composer` or `$io` params you get for a plugin (At least, what content-assist by my IDE has to offer me). So I hacked around this code:

```php
$autoloadGenerator = $composer->getAutoloadGenerator();
$ref = new \ReflectionClass($autoloadGenerator);
$devModeProp = $ref->getProperty('devMode');
$devModeProp->setAccessible(true);
$devMode = $devModeProp->getValue($autoloadGenerator);
```
which is very ugly and also very unsafe. I was wondering if there is a better way to inspect this? Or if there can be added one.

**Comment by alcohol** [comment]
Afaik it's only set on the installer which is indeed not really accessible from plugins.

@Seldaek got any ideas here?

**Comment by Seldaek** [comment]
The [event](https://github.com/composer/composer/blob/master/src/Composer/Script/Event.php) class has `isDevMode()`. That should be usable no?

**Comment by alcohol** [comment]
Do the plugin event classes extend from that one though?

**Comment by stof** [comment]
@alcohol what are you talking about with "plugin event classes" ?

**Comment by alcohol** [comment]
The installer event classes, sorry.

**Comment by Seldaek** [comment]
They don't all run with that class, some things don't have a dev mode, but most do, check https://getcomposer.org/doc/articles/scripts.md#defining-scripts at the bottom there is a full list of event classes with API docs.

**Comment by alcohol** [comment]
@gossi does that help?

**Comment by gossi** [comment]
Given the example plugin class from here: https://getcomposer.org/doc/articles/plugins.md#plugin-class

```php
<?php

namespace phpDocumentor\Composer;

use Composer\Composer;
use Composer\IO\IOInterface;
use Composer\Plugin\PluginInterface;

class TemplateInstallerPlugin implements PluginInterface
{
    public function activate(Composer $composer, IOInterface $io)
    {
        $installer = new TemplateInstaller($io, $composer);
        $composer->getInstallationManager()->addInstaller($installer);
    }
}
```

How do I access `devMode` from within the `activate()` method? I don't see how an event can help here?

**Comment by alcohol** [comment]
I would suggest you also read https://getcomposer.org/doc/articles/plugins.md#event-handler

Your `activate()` method is more for setup related stuff.
