### ISSUE TITLE
Fail to require third party libraries

### ISSUE THREAD

**Issue by yobichi** [composer/composer#4750]
My php file locates at /Applications/XAMPP/xamppfiles/htdocs/test.php and I installed composer at  /usr/local/bin/composer. When I run the code, it is said that:
Fatal error: require(): Failed opening required '/vendor/autoload.php' (include_path='.:/Applications/XAMPP/xamppfiles/lib/php') in /Applications/XAMPP/xamppfiles/htdocs/test.php on line 3

How to fix it? Thank you in advance!

**Comment by xabbuh** [comment]
Did you install your project's dependencies running `composer install`?

**Comment by yobichi** [comment]
@xabbuh Thanks for reply! Just type `composer install` in the terminal? Yes I did it.

**Comment by yobichi** [comment]
@xabbuh  If you meant  ` php composer.phar install`， I got an error `Could not open input file: composer.phar`

**Comment by alcohol** [comment]
Are you on OSX?

If so, just run `composer install` literally.

This is assuming you indeed installed composer at `/usr/local/bin/composer` (run `which composer` to verify) and that `/usr/local/bin` is part of your `$PATH` (run `echo $PATH` to verify).

**Comment by yobichi** [comment]
@alcohol  Thanks for your reply! 
When I run echo $PATH, I got `/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`. Is it right? And yes, I am on ox s 10.10

**Comment by alcohol** [comment]
Yes that looks right. `/usr/local/bin` is in your path.

What happens if you run: `which composer` ?
What happens if you run: `composer --version` ?

**Comment by yobichi** [comment]
@alcohol Tons of thanks! The problem is fixed now!

**Comment by alcohol** [comment]
Oh, ok.
