### ISSUE TITLE
After create-project - update not working: “Nothing to install or update

### ISSUE THREAD

**Issue by schoolphp** [composer/composer#4751]
I create new site with "composer create-project schoolphp/framework". But when project changes - "composer update" doesn't update it with message "nothing to install or update", but project must be update with new files! Full my action-logs:

1) I upload my project to github: https://github.com/schoolphp/framework . After upload to packagist.org .

2) Install my project to local-site: composer install schoolphp/framework

3) Change package on github and make commit & push: http://i.stack.imgur.com/oaI0u.jpg

4) I make also "new release" on github. Update it on packagist.

5) Now I run composer update on my local project and see: "nothing to install or update":
http://my.jetscreenshot.com/7950/20151223-elqt-171kb.jpg

6) I try to do: delete composer.lock , change composer.json:

```
    "require": {
        "php": ">=5.6.0",
        "schoolphp/framework": "*",
        "schoolphp/library": "dev-master"
    },
```

But still "nothing to update". P.S. But update works to schoolphp/library, when I change and do the same (vendor require).

How can I update my project after create-project? (new version available, i wanna update index.php in root-directory, old version with bug).

UPDATE:
I can do it with native GIT:
```bash
git init
git pull https://github.com/schoolphp/framework
```
So, it`s work correctly, can i do something like this with composer ? Or composer only for packages in project, but not for root-project?

**Comment by schoolphp** [comment]
I can do it with native GIT:
```bash
git init
git pull https://github.com/schoolphp/framework
```
So, it`s work correctly, can i do something like this with composer ?

**Comment by rquadling** [comment]
It looks like you are in the project already. ``composer update`` is for dependencies, not for updating the repo with changes you've made locally.

Have you set github to push notify packagist when you make a release/tag?

What about using ``--prefer-source`` if I'm wrong about you being in your project directory?

**Comment by alcohol** [comment]
@schoolphp composer is indeed only for dependencies, and not for the root project.

**Comment by liub1993** [comment]
@schoolphp Hi, have you solved the problem?  I met that too recently...

**Comment by rquadling** [comment]
The "problem" is that the composer doesn't manage your project, only the dependencies to your project.

So, for example, I have a digital ticketing app. It requires packages/components from Symfony, Omnipay, etc. I use composer for the dependencies.

The main application code is my responsibility and I use git for that.

**Comment by liub1993** [comment]
I have solved my issue, because of the 'type' in composer.json is not appropriate. 
That what I did: 
     "type": "metapackage", 

And I set it to default value 'library', and it works fine.

**Comment by Neosono** [comment]
Hi guys please assist, I am working on laravel 5, and I cant seem to find the most basic problem, to add laravelcollective html5, I have added :

"require": {
    "laravelcollective/html": "5.1.*"
}
and added the ff to app.php : 

 Collective\Html\HtmlServiceProvider::class,

and the aliases :

 'Form'=> Collective\Html\FormFacade::class, 
 'Html'=> Collective\Html\HtmlFacade::class,

but when I run composer update : it says nothing to update or install ...May someone help the novice me in laravel ...anyway am new to Laravel framework, I do think its best for people to leave Laravel because of this basic problem... I use Java Spring 4.0, doing this is a very basic thing in Java, can someone help!
