### ISSUE TITLE
Require a package which depends on a branch-aliased package fails

### ISSUE THREAD

**Issue by kminh** [composer/composer#4753]
Hi,

I must be missing something pretty basic here, but this setup doesn't seem to work:

**There are 3 packages:**

```
pkg1\composer.json

{
    "name": "test/pkg1",
    "repositories": [
        {
            "type": "vcs",
            "url": "../pkg2"
        },
        {
            "type": "vcs",
            "url": "../pkg3"
        }
    ],
    "require": {
        "test/pkg2": "~1.0"
    }
}

pkg2\composer.json

{
    "name": "test/pkg2",
    "repositories": [
        {
            "type": "vcs",
            "url": "../pkg3"
        }
    ],
    "require": {
        "test/pkg3": "1.0.*@dev"
    }
}

pkg3\composer.json

{
    "name": "test/pkg3",
    "extra": {
        "branch-alias": {
            "dev-master": "1.0.x-dev"
        }
    }
}
```

All packages are git repositories, `pkg2` has a `1.0.0` tag.

This is the output of `composer update --no-plugins`:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for test/pkg2 ~1.0 -> satisfiable by test/pkg2[1.0.0].
    - test/pkg2 1.0.0 requires test/pkg3 1.0.x-dev -> no matching package found.
```

If I add `"test/pkg3": "1.0.*@dev"` to the `require` block of `pkg1` it works fine. So is it required that any branch-aliased dependencies must be added to the root composer.json?

Thanks for any insight.

**Comment by alcohol** [comment]
See point 2 of https://getcomposer.org/doc/articles/troubleshooting.md#package-not-found

**Comment by kminh** [comment]
@alcohol ah yes, forgot to mention but I've tried that too and it works, but I don't think it's an ideal solution.

So I take that this is expected and I must either set the `minimum-stability` to `dev` or require the aliased package explicitly? I wonder why though, since the documentation doesn't say anything about the `branch-alias` being root-only.

**Comment by Seldaek** [comment]
branch-alias isn't root only, but this line explains it:

    - test/pkg2 1.0.0 requires test/pkg3 1.0.x-dev -> no matching package found.

pkg2 requires pkg3 in a **dev** version, which is not allowed by your minimum stability. The branch-alias isn't root only, but stability management is, the reason is simply that every project/person needs to be in control of the stability of the packages they install, and the packages they require can not change it for them. Some companies have strict policies about avoiding unstable packages for example.
