### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by CismE97** [composer/composer#4758]
I want to install composer... but i'have an error and i don't know why ?

bash-4.2$ curl -sS https://getcomposer.org/installer | php
bash: php: command not found
curl: (77) Problem with the SSL CA cert (path? access rights?)

Can you help me ? thanks

**Comment by Seldaek** [comment]
Seems you don't have php accessible on CLI.. and also curl does not have proper SSL certs in place.

**Comment by CismE97** [comment]
And how can I solve this problem ? 

(I have disable certs SSL on the config to the server and always the same error.)

I'm lost sorry...

**Comment by Seldaek** [comment]
Well you'd have to install php and possibly fix your ssl cert situation 
or just fetch the composer.phar file from your browser at 
https://getcomposer.org/composer.phar

**Comment by curry684** [comment]
> or just fetch the composer.phar file from your browser

That won't do much good if PHP isn't available in the user's path.

@CismE97 for further assistance you will at least need to share which OS you are using, and in the case of Linux which distribution and which version.
