### ISSUE TITLE
Private repositories from required project requires reference in main project?

### ISSUE THREAD

**Issue by craigstanton** [composer/composer#4762]
Project A requires project B.
Project B requires project C, which comes from a private repo.

Running Composer for project A works.
Running Composer for Project A fails because it can't find project C.

This can be worked around by adding the repository reference into project A's composer.json.

**Comment by schmunk42** [comment]
Explained here: https://getcomposer.org/doc/faqs/why-can%27t-composer-load-repositories-recursively.md

**Comment by alcohol** [comment]
This is documented.
