### ISSUE TITLE
Detect versions in package repository

### ISSUE THREAD

**Issue by Rudloff** [composer/composer#4763]
Hello,

When using a package repository, it is quite tedious to update the *version* and *reference* fields when you need to update the dependency.
It would be a lot easier if we could do something like this:
```
{
	"name": "rudloff/bar",
	"description": "Lorem ipsum",
    "license": "GPL-3.0",
	"require": {
		"foo": "~1.0.0"
	},
	"repositories": [{
		"type": "package",
		"package": {
			"name": "foo",
			"source": {
				"url": "http://example.com/foo",
				"type": "git"
			}
		}
	}]
}
```
and let Composer find the semver tags without having to specify the reference manually.

**Comment by cs278** [comment]
Use a VCS repository: https://getcomposer.org/doc/05-repositories.md#vcs

```json
"repositories": [
    {"type": "vcs", "url": "http://example.com/foo"}
]
```

**Comment by Rudloff** [comment]
The VCS repository will not work if the repository does not contain a composer.json file.

**Comment by alcohol** [comment]
What is stopping you from adding one?

**Comment by Rudloff** [comment]
Obviously I don't have control over all the repositories I use for my dependencies. (And maintaining forks would be even more work than having to update the reference.)
I guess the thing to do is to ask the maintainers to add a composer.json but they don't always answer.

**Comment by curry684** [comment]
But exactly how do you expect this to work? We'd need to pull all branches, switch to all of them, find and parse `composer.json` files if present, then get a list of tags and branches, inspect all of them and merge them normalized into the list, and then finally start solving. That's going to be lethal if you have many of them.

Isn't it just easier to grab Satis and build a custom script for this yourself to do the conversion?

**Comment by Seldaek** [comment]
This is just not a use case we want to facilitate even further IMO as it's usually used for edge cases and not worth the time implementing and maintaining this code.
