### ISSUE TITLE
autoload_files not to loaded on script runs

### ISSUE THREAD

**Issue by derhasi** [composer/composer#4764]
When trying to call GuzzleHttp\Client in a run-script, it fails with

> Fatal error: Call to undefined function GuzzleHttp\choose_handler() in /Users/derhasi/temp/guzzle-test/vendor/guzzlehttp/guzzle/src/HandlerStack.php on line 40

It seems that composer does not include the files from the autoload part in the case of a script (or plugin).

To reproduce the error I set up a small repo for testing: https://github.com/derhasi/guzzle-test

In this case running `_helper/vendor/bin/composer guzzle-test -vvv` leads to:

```
Reading ./composer.json
Loading config file /Users/derhasi/.composer/config.json
Loading config file /Users/derhasi/.composer/auth.json
Loading config file ./composer.json
Executing command (/Users/derhasi/temp/guzzle-test): git describe --exact-match --tags
Executing command (/Users/derhasi/temp/guzzle-test): git branch --no-color --no-abbrev -v
Reading /Users/derhasi/.composer/composer.json
Loading config file /Users/derhasi/.composer/config.json
Loading config file /Users/derhasi/.composer/auth.json
Loading config file /Users/derhasi/.composer/composer.json
Loading config file /Users/derhasi/.composer/auth.json
> guzzle-test: derhasi\GuzzleTest\Scripts::test

Fatal error: Call to undefined function GuzzleHttp\choose_handler() in /Users/derhasi/temp/guzzle-test/vendor/guzzlehttp/guzzle/src/HandlerStack.php on line 40

Call Stack:
    0.0041     242472   1. {main}() /Users/derhasi/temp/guzzle-test/_helper/vendor/composer/composer/bin/composer:0
    6.8381    3260560   2. Composer\Console\Application->run(???, ???) /Users/derhasi/temp/guzzle-test/_helper/vendor/composer/composer/bin/composer:44
    6.8541    3650120   3. Symfony\Component\Console\Application->run(???, ???) /Users/derhasi/temp/guzzle-test/_helper/vendor/composer/composer/src/Composer/Console/Application.php:98
    6.8578    3801104   4. Composer\Console\Application->doRun(???, ???) /Users/derhasi/temp/guzzle-test/_helper/vendor/symfony/console/Application.php:117
    6.8624    3982824   5. Symfony\Component\Console\Application->doRun(???, ???) /Users/derhasi/temp/guzzle-test/_helper/vendor/composer/composer/src/Composer/Console/Application.php:167
    6.8627    3983456   6. Symfony\Component\Console\Application->doRunCommand(???, ???, ???) /Users/derhasi/temp/guzzle-test/_helper/vendor/symfony/console/Application.php:186
    6.8627    3984000   7. Symfony\Component\Console\Command\Command->run(???, ???) /Users/derhasi/temp/guzzle-test/_helper/vendor/symfony/console/Application.php:787
    6.8646    3989992   8. Composer\Command\ScriptAliasCommand->execute(???, ???) /Users/derhasi/temp/guzzle-test/_helper/vendor/symfony/console/Command/Command.php:256
    7.2997    8798720   9. Composer\EventDispatcher\EventDispatcher->dispatchScript(???, ???, ???, ???) /Users/derhasi/temp/guzzle-test/_helper/vendor/composer/composer/src/Composer/Command/ScriptAliasCommand.php:66
    7.3002    8822296  10. Composer\EventDispatcher\EventDispatcher->doDispatch(???) /Users/derhasi/temp/guzzle-test/_helper/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php:94
    7.3023    8840776  11. Composer\EventDispatcher\EventDispatcher->executeEventPhpScript(???, ???, ???) /Users/derhasi/temp/guzzle-test/_helper/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php:179
    7.3026    8841312  12. derhasi\GuzzleTest\Scripts::test(???) /Users/derhasi/temp/guzzle-test/_helper/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php:225
    8.8714    8967856  13. GuzzleHttp\Client->__construct(???) /Users/derhasi/temp/guzzle-test/src/Scripts.php:16
    8.8733    9028392  14. GuzzleHttp\HandlerStack::create(???) /Users/derhasi/temp/guzzle-test/vendor/guzzlehttp/guzzle/src/Client.php:65
```

**Comment by alcohol** [comment]
If I am not mistaken, during the `scripts` step, Composer only loads psr-0/psr-4 definitions. Not classmap or files definitions.

/cc @seldaek please correct me if I am wrong.

**Comment by alcohol** [comment]
Actually, I have to correct myself. I loads all autoload definitions. But nothing more than that. So any files definitions aren't actually included at that point. They are simply only "known". So while psr-0/4 and classmap definitions should work as expected, files will not.

**Comment by alcohol** [comment]
See https://github.com/composer/composer/blob/bda2c0f9b7dfc24616fe273d06f816a61abec9ef/src/Composer/Autoload/AutoloadGenerator.php#L401

**Comment by Seldaek** [comment]
Yeah classmap works but not files autoload.

**Comment by derhasi** [comment]
Do you see a way to fix that?

**Comment by Seldaek** [comment]
We could easily include all the autoload_files I guess but that means they MUST support being included multiple times, which I doubt is the case right now, so we would probably break a bunch of projects.

**Comment by alcohol** [comment]
Yeah I see no easy fix for this. As an alternative, for this specific use-case, I suggest you could instead create a client directly that has the right handler and everything, thus avoiding the need for the factory-like methods declared in the files.

**Comment by stof** [comment]
@alcohol this would not solve it. Guzzle also uses functions later than the building of the client. Sending requests also involve some functions

**Comment by alcohol** [comment]
@stof ok.

**Comment by jasiekmiko** [comment]
Hi @Seldaek,

Has this issue been solved? It's not very clear to me why it was closed.
I'm currently getting the same error while on the fresh composer version (1.6.3 (stable channel)) and Guzzle 6.3.2. It'd be great if you could clarify if this is to be expected and if so, is there a known work-around?

**Comment by greg-1-anderson** [comment]
I am using the following workaround:
```
public static function loadGuzzleFunctions()
{
    $vendor = __DIR__ . '/../vendor';
    require_once "$vendor/guzzlehttp/guzzle/src/functions_include.php";
    require_once "$vendor/guzzlehttp/psr7/src/functions_include.php";
    require_once "$vendor/guzzlehttp/promises/src/functions_include.php";
}
```
This workaround is, of course, fragile, and may stop working if Guzzle changes the set of function include files it declares in its composer.json file. Potential superior solutions would include:

1. Have your composer script `exec` a program that you package separately that can call guzzle normally.

1. Look for the Guzzle file includes in the autoloader, and include those found.

1. Enhance Composer to allow the top-level composer.json to declare which projects' autoload files should be included for Composer scripts (`guzzlehttp/guzzle`, `guzzlehttp/psr7` and `guzzlehttp/promises` in this example).

1. Fix guzzle to provide the functionality from the include files in static PHP classes. The existing functions in the include files could call through to the new static PHP classes for backwards compatibility.

Of these, only #3 is applicable to this issue queue. I don't know if I will or will not pursue any of these options.

**Comment by jasiekmiko** [comment]
Thanks @greg-1-anderson!
In my case it turned out that running `composer dump-autoload` forced it into working! :)

**Comment by WyriHaximus** [comment]
> We could easily include all the autoload_files I guess but that means they MUST support being included multiple times, which I doubt is the case right now, so we would probably break a bunch of projects.

@Seldaek any change this will be fixed in v2 or v3?

**Comment by stof** [comment]
v2 does not change this.

The hard point here is that the autoloader for script is regenerated many times (due to having a `post-package-install` hook running after each package is installed and needing to know about the packages installed at this point). This makes it hard to deal with file includes (we cannot include the same file multiple times, otherwise PHP will break, but we might also have conflicts between function definitions between 2 different versions of a package, with the old one being removed and the new one being installed, at some point of the process)

**Comment by WyriHaximus** [comment]
Hmm ok, my personal use would be during the `pre-autoload-dump` event tho. But I suppose the same reasoning applies there?

**Comment by Seldaek** [comment]
Yeah this is something that can't really be fixed IMO at this point due to the amount of packages which might rely on the existing behavior.

**Comment by greg-1-anderson** [comment]
@Seldaek You could still do:

> 3. Enhance Composer to allow the top-level composer.json to declare which projects' autoload files should be included for Composer scripts (guzzlehttp/guzzle, guzzlehttp/psr7 and guzzlehttp/promises in this example).

If Composer only autoloaded files when the top-level composer.json opted in, then folks could add that if they needed to use Guzzle from a Composer script, but other projects wouldn't break.

Not super high priority IMO, but might be nice.

**Comment by WyriHaximus** [comment]
@greg-1-anderson alternatively I or someone else can create a plugin to do that :)
