### ISSUE TITLE
 [RuntimeException]   Failed to clone git@github.com:magento/composer.git, git was not found, che   ck that it is installed and in your PATH env.

### ISSUE THREAD

**Issue by mmannanmasood** [composer/composer#4765]
Command: composer install

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing magento/composer (1.0.2)
    Downloading: 100%
    Failed to download magento/composer from dist: The checksum verification of
the file failed (downloaded from https://api.github.com/repos/magento/composer/z
ipball/1be267e71debac6e0d9fae4e5144f6095cffbe89)
    Now trying to download from source
  - Installing magento/composer (1.0.2)
    Cloning 1be267e71debac6e0d9fae4e5144f6095cffbe89

  [RuntimeException]
  Failed to clone git@github.com:magento/composer.git, git was not found, che
  ck that it is installed and in your PATH env.
  'git' is not recognized as an internal or external command,
  operable program or batch file.

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-p
lugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress
] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative]
 [--ignore-platform-reqs] [--] [<packages>]...

**Comment by alcohol** [comment]
Install git.

**Comment by mmannanmasood** [comment]
Thanks alcohol for your replay. Just installed git 10 mins before your reply.. and it worked.. :)

**Comment by alcohol** [comment]
Alright :-)
