### ISSUE TITLE
composer update fails on staging server for private github package - no prompt for un/pw

### ISSUE THREAD

**Issue by chrisgoddard** [composer/composer#4766]
I've found some posts for similar issues, but no fixes have worked.

I'm using composer as part of the Bedrock WordPress setup which uses Composer Installers to defined install paths. Server is a Digital Ocean LAMP stack (Ubuntu Trusty)

I have a custom WordPress plugin in a private GitHub repository and I have defined that in composer.json:

![screen shot 2016-01-12 at 3 19 19 pm](https://cloud.githubusercontent.com/assets/4922472/12280129/89bdf082-b940-11e5-8ff6-648fe0e6345a.png)

When I run composer update, this is the result:

![screen shot 2016-01-12 at 3 21 47 pm](https://cloud.githubusercontent.com/assets/4922472/12280146/a2f3aa1a-b940-11e5-967a-372107e7fc58.png)

It says invalid username and password, though it never prompts me for it.

I have tried setting the username and password using: 
```
composer config http-basic.github.com username password
```

As well as setting a GitHub token using:
```
composer config --global github-oauth.github.com <TOKEN>
```

Nothing has worked.

I would rather not have any authentication stored on the server - I'd just like it to prompt me for my username/password.

Also, as I've seen this been asked before, I can manually clone the repo with no issue - it just asks for my username/password and then works fine.

Forgive me if I'm missing something really obvious. Let me know if you need more info.

Cheers!

**Comment by cs278** [comment]
Have you got the `COMPOSER_NO_INTERACTION` environment variable set?

**Comment by chrisgoddard** [comment]
@cs278: No, not variables or custom config other than trying to set the http-basic username and password for Github.

**Comment by chrisgoddard** [comment]
Hi there - sorry to bug you guys - any ideas on this?

**Comment by Seldaek** [comment]
Any luck figuring it out @chrisgoddard? For private repos we usually [define the github URL as `git@github.com:user/repo.git`](https://github.com/composer/composer/blob/master/src/Composer/Repository/Vcs/GitHubDriver.php#L118-L121) as this uses your ssh key for cloning. Maybe using that in your package repos would fix it?
