### ISSUE TITLE
name

### ISSUE THREAD

**Issue by xcl3721** [composer/composer#4767]
when the package name "packagenamexxxx"
the require list have "packagenamexxxx" package
the composer will not download the packagenamexxxx package

suggest add an tips that :

the require have the same name of current package ignore download

it's wast me two hour to find out:why the package was not download to vendor

**Comment by alcohol** [comment]
I'm sorry, but the language barrier is a bit too much for me here. I do not really understand what you are trying to say. Perhaps someone else does?

**Comment by cs278** [comment]
I think the issue is saying if you try and require your root package from your root package it won't be installed in vendor. Like this:

```
composer init -n --name="foo/bar"
composer require -n foo/bar:@dev
ls -l vendor # No foo directory
```

Which is to be expected.

**Comment by alcohol** [comment]
Yeah that was my assumption too. However, that is not really worth documenting because it makes no sense.

**Comment by xabbuh** [comment]
Would it be easily possible to just trigger and error if any of the required packages (just the ones listed in the project's `composer.json` file) has the same name as the project?

**Comment by xcl3721** [comment]
thanks！

**Comment by curry684** [comment]
Much as I hate to admit it the request is valid. What Composer does makes sense - it ignores circular dependencies when encountered, as it does not maintain hierarchy. So if A and B depend on eachother it can safely ignore the recursion, and the end result will be that both A and B are installed as expected.

This makes the issue at hand a special one, the dependency is ignored but does **not** result in an installed package. That at least makes it an anomaly enough to warrant a hard error.

Also, the use case is not even nonsensical enough never to happen. Imagine someone new to Composer, wanting to start Symfony development with a test project. As `composer init` asks him to provide a two-part slash separated name for his project he enters `symfony/symfony`. And then follows the tutorial with:

    composer require symfony/symfony:@dev

This will, right now, succeed silently with not a single package installed, nor a hint what happened. Not good. It gets even better if he follows a better tutorial, leaving out `@dev`. Copy/paste:

> Your requirements could not be resolved to an installable set of packages.
>
>  Problem 1
>  - The requested package symfony/symfony No version set (parsed as 1.0.0) could not be found.
>
>Potential causes:
> - A typo in the package name
> - The package is not available in a stable-enough version according to your minimum-stability setting
>   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

So yes, this should definitely throw a hard error. PR coming up  :)
