### ISSUE TITLE
Find project dependencies from a given Composer repository

### ISSUE THREAD

**Issue by greg0ire** [composer/composer#4768]
Like many, I use packages from packagist, but also packages coming from a private repository. When a newcomer joins a project, I need to grant him access to the private packages used in the project. For the moment, I solved the project with this fragile approach : `grep 'git.universcine.com' --before-context=4 composer.lock|grep '"name"'|cut --delimiter=':' --fields=2|sed --expression='s/ "\(.\+\)",/\1/'` . Is there a more Composerish way to achieve this? Should there be?

**Comment by alcohol** [comment]
This sounds more like an organisational problem, and not really programming/Composer related.

I can't really think of a more "Composerish" way to do the above, merely similar alternatives. But to be honest I'm not even sure what kind of output you are looking for exactly.

**Comment by greg0ire** [comment]
I'm looking for something like this : 

```
composer some_command my_private_repo

my/private-lib
my/other-private-lib
my/third-private-lib-depency-of-the-first-one
```

I want to answer the question : "what repositories do I need to grant access to my coworker to ?"

**Comment by cs278** [comment]
`composer show --self`?

**Comment by alcohol** [comment]
```
composer show -i -N | grep vendorname
```

Replace _vendorname_.

**Comment by greg0ire** [comment]
Ok you're right, it's an organizational problem. We thought it would be "clever" to use package groups as vendor names, like "security", "forms", instead of "my". Closing, sorry.
