### ISSUE TITLE
Segmentation fault after "Generating autoload files" with php-7.0.2

### ISSUE THREAD

**Issue by seaneble** [composer/composer#4769]
It seems as though #2774 was not really fixed very well. At least I encounter the exact problems on RHEL 7 with PHP 7.0.2.

    $> php composer.phar dump-autoload
    Generating autoload files
    Segmentation fault

What could I do to analyse this?

**Comment by stof** [comment]
Segmentation faults are bug in PHP itself (or in one of the extension), as they are crashes in the C code. So this question should be asked to the PHP support, not to composer

**Comment by seaneble** [comment]
Yeah, I would have done that, only that I don't know where in composer the sementation fault occurs. I was hoping somebody could support me as far as to follow it to a specific class etc.

**Comment by stof** [comment]
What you could start doing is trying to disable your PHP extensions one by one to identify which extension is causing a segfault.
Then, I don't know how to identify where the segfault occurs. this would involve a C debugging tool.

**Comment by seaneble** [comment]
It seems like my PHP is broken, as I discovered a number of other segmentation faults across my software as well. Sorry for taking your time, I will generate a core dump and open a bug report with PHP.
