### ISSUE TITLE
Uninstall issues

### ISSUE THREAD

**Issue by Fredericld** [composer/composer#4773]
Hi,

I have never used composer before and tried to install manually by placing composer.bat ( @php "%~dp0composer.phar" %* ) and composer.phar in windows/system32/ . Running the prompt, I received an error about a phar class not found on line 23. I then realised there was a windows executable to install composer. When I run it, it says a version of composer exists in windows/system32/ although I have since deleted the .bat and .phar files. Does composer create any files in the background? It is hard to say as windows/system32/ is huge and I can not see anything obvious when sorting files by date midified

Fred

**Comment by osavchenko** [comment]
Why you need to place composer into `Windows/system32` folder? You can use composer installer and install it to `ProgramData` and add to PATH variable and use it from cmd as `composer`.

**Comment by Fredericld** [comment]
I placed it in windows/system32/ to do a quick test, but I realise now there is an windows installer. Unfortunately, the installer does not let me install it and says composer is already installed. what do I have to do to remove composer? I only copied composer.phar and ran it once via CMD.

**Comment by osavchenko** [comment]
Try to remove composer from system32 folder and install via installer

**Comment by Fredericld** [comment]
I did that, but the installer says it is still there .... :(

**Comment by jakoch** [comment]
Hey Fred,

dropping stuff in the windows system folder is never a good idea. You could have created a folder for Composer and appended your environment path variable. Anyway..let's fix the install situation now.

> Does composer create any files in the background?

Yes, it does. Even if you removed the phar file manually, some bits and pieces might still be around.
And the Composer-Installer does a StartCheck() and looks for these folders to find an old installation. 

I suggest to remove the following folders and then re-run the installer:
- `C:\Users\<USERNAME>\AppData\Roaming\Composer` (contains configs, certs, old composer phars)
- `C:\Users\<USERNAME>\AppData\Local\Composer` (contains package cache)

Best, Jens

**Comment by Fredericld** [comment]
thanks. issue fixed
