### ISSUE TITLE
Windows installer Error?

### ISSUE THREAD

**Issue by Zortex04** [composer/composer#4776]
Hey I was Recently making an Habbo hotel using AzureWeb (Doesent matter if you dont know what it means) Basicly AzureWeb Is a cms that comes with its own Webserver so when i open the .bat (webserver) i cant type stuff like php and stuff recently i found out theres a composer.json i need to install (never used composer before) so i went to getcomposer.org and downloaded the windows installer (Cause im using windows) But in the installer it says i have to choose a php.exe is there anyway just to install the part like in cmd composer.json install or something like that? i know this is more of an Question Not an error  Btw i also thought why not just make another json with the installer and copy the text from the one theres orginally there but when i sellect the php.exe and press next it says something about openssl which is on there so please help???

**Comment by Seldaek** [comment]
It sounds like your php.ini has openssl disabled when used in the command line at least.. you need to fix that somehow, I am not sure what you used to install php on your machine but look for any php.ini and make sure the openssl extension line is enabled.

**Comment by Zortex04** [comment]
as Far As Ive seen it is enabled 


extension = php_openssl.dll

**Comment by Seldaek** [comment]
What if you type `php -m` in a terminal/cmd.exe? If you don't see openssl in the list then it's not enabled.

**Comment by Seldaek** [comment]
And if it isn't enabled, that's probably because the php you use on command line isn't the same as the one you're checking..

**Comment by Zortex04** [comment]
Hmmm One thing tho i dont have php Installed as a windows thing this php came with the thing / Azureweb

**Comment by Seldaek** [comment]
Well I have no idea how that works, but your best bet is to do as I explained above, use `where php` to find where it is, and locate the php.ini next to it and make sure it has openssl enabled in there.
