### ISSUE TITLE
Move http support behind a secure-http flag

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#4777]
As per discussion on #4056 - adding a flag that disables http unless the flag is set to false would be good. I'm thinking `secure-http: false` reads more dangerous than `https-only: false` so might be preferable. Anyway this should be fairly easy to add in Config/ConfigCommand and check for in the RemoteFilesystem file if someone wants to help.

**Comment by Seldaek** [comment]
Implemented in #4907 /cc @stormtide ;)

**Comment by davecarlson** [comment]
Please note, this breaks a lot of projects without config changes. 

For example, any project that uses wordpress packages, and calls wpackagist.org, needs changes to be able to be installed. This is pretty serious if your stack have auto-scaling,  resulting in failure.

**Comment by Seldaek** [comment]
Yes I am sorry for the eventual breakage but it's a security fix and as such not fixing it would also be a bad situation.

**Comment by davecarlson** [comment]
That's fine - although should there not have been some kind of announcement regarding this, seeing as though it's a breaking change?

**Comment by Seldaek** [comment]
I did https://twitter.com/seldaek/status/705415089357266944 on top of the actual beta1 release with the changelog and warning on the first line.

**Comment by davecarlson** [comment]
fair enough - you're now followed :)
