### ISSUE TITLE
Composer install is broken

### ISSUE THREAD

**Issue by perk11** [composer/composer#4780]
After update I get the same error as in #4779 just by running `composer install` or `composer update`

     Argument 5 passed to Composer\Repository\VcsRepository::__construct() must be of the type array, object given, called in phar:////opt/bin/composer.phar/src/Composer/Repository/RepositoryManager.php on line 108 and defined

**Comment by Nilz11** [comment]
+1

**Comment by Seldaek** [comment]
Should be fixed now please try again with last version

**Comment by perk11** [comment]
Getting a different error now:

	PHP Fatal error:  Call to undefined method ReflectionParameter::getType() in phar:///opt/bin/composer/src/Composer/Repository/RepositoryManager.php on line 110
	PHP Stack trace:
	PHP   1. {main}() /opt/bin/composer:0
	PHP   2. require() /opt/bin/composer:25
	PHP   3. Composer\Console\Application->run() phar:///opt/bin/composer/bin/composer:43
	PHP   4. Symfony\Component\Console\Application->run() phar:///opt/bin/composer/src/Composer/Console/Application.php:98
	PHP   5. Composer\Console\Application->doRun() phar:///opt/bin/composer/vendor/symfony/console/Application.php:123
	PHP   6. Symfony\Component\Console\Application->doRun() phar:///opt/bin/composer/src/Composer/Console/Application.php:167
	PHP   7. Symfony\Component\Console\Application->doRunCommand() phar:///opt/bin/composer/vendor/symfony/console/Application.php:192
	PHP   8. Symfony\Component\Console\Command\Command->run() phar:///opt/bin/composer/vendor/symfony/console/Application.php:840
	PHP   9. Composer\Command\InstallCommand->execute() phar:///opt/bin/composer/vendor/symfony/console/Command/Command.php:259
	PHP  10. Composer\Command\Command->getComposer() phar:///opt/bin/composer/src/Composer/Command/InstallCommand.php:84
	PHP  11. Composer\Console\Application->getComposer() phar:///opt/bin/composer/src/Composer/Command/Command.php:53
	PHP  12. Composer\Factory::create() phar:///opt/bin/composer/src/Composer/Console/Application.php:243
	PHP  13. Composer\Factory->createComposer() phar:///opt/bin/composer/src/Composer/Factory.php:513
	PHP  14. Composer\Package\Loader\RootPackageLoader->load() phar:///opt/bin/composer/src/Composer/Factory.php:289
	PHP  15. Composer\Factory::createDefaultRepositories() phar:///opt/bin/composer/src/Composer/Package/Loader/RootPackageLoader.php:124
	PHP  16. Composer\Repository\RepositoryManager->createRepository() phar:///opt/bin/composer/src/Composer/Factory.php:183

	Fatal error: Call to undefined method ReflectionParameter::getType() in phar:///opt/bin/composer/src/Composer/Repository/RepositoryManager.php on line 110

**Comment by Seldaek** [comment]
Yeah sorry my fix was working only on php7.. Pushed a new fix now :)

**Comment by peterrehm** [comment]
Issue is fixed with latest version.
