### ISSUE TITLE
Class 'Composer\Util\Factory' not found

### ISSUE THREAD

**Issue by youssefhad** [composer/composer#4781]
when i test my project in travis it gives me this error :

PHP Fatal error:  Class 'Composer\Util\Factory' not found in phar:///home/travis/.phpenv/versions/5.5.21/bin/composer/src/Composer/Util/GitHub.php on line 42

https://travis-ci.org/fiesta-framework/Fiesta/jobs/102823592

**Comment by dereuromark** [comment]
Yeah got the same for all my repos today:
https://travis-ci.org/dereuromark/cakephp-shim/jobs/102825916#L135
etc

**Comment by dereuromark** [comment]
Refs https://github.com/composer/composer/issues/4779#issuecomment-172240377

**Comment by alcohol** [comment]
I pushed a hotfix to master. It should be resolved now.

**Comment by dereuromark** [comment]
Yeah starting to look good. Thx!

**Comment by SilverFire** [comment]
Thank you, fixed the problem

**Comment by youssefhad** [comment]
Thnx ! problem solved
