### ISSUE TITLE
Undefined variable caBundle

### ISSUE THREAD

**Issue by jacmoe** [composer/composer#4785]
When downloading and installing latest composer I get this notice:
~~~
Notice: Undefined variable: caBundle in - on line 892
~~~
While the installation proceeds and succeeds, I get this error whenever I use composer:
~~~
[ErrorException]              
  Undefined variable: caBundle  
~~~

It seems to be something that you changed in the last weeks.

Linux is Netrunner 17 based on Ubuntu (Kubuntu).
I may or may not have ipv6 disabled, but the error is in your script.

Edit:
PHP v5.6.14

**Comment by alxpub** [comment]
Updated to latest version, after update can`t do anything in composer.. 
Gets error
[ErrorException]
  Undefined variable: caBundle

**Comment by alcohol** [comment]
Can you please grab a copy of the latest dev-master phar from https://getcomposer.org/composer.phar (assuming `self-update` doesn't work anymore for you right now). It should be fixed I believe.

**Comment by jacmoe** [comment]
The problem that I have is that it happens with the latest. :(
The composer from November in the releases does not work for me either because of the asset plugin.

**Comment by staabm** [comment]
fixed with https://github.com/composer/composer/commit/22d8b5dff497368a1a42bfbffc989c77031f04c6

**Comment by alcohol** [comment]
@jacmoe are you sure you are on the latest?

**Comment by alcohol** [comment]
```
$ composer --version
Composer version 1.0-dev (22d8b5dff497368a1a42bfbffc989c77031f04c6) 2016-01-18 07:59:12
```

**Comment by jacmoe** [comment]
Awesome ! :+1: 
That fixed it for me - thanks a lot @staabm :)

@alcohol I grabbed the latest before Markus' fix. :)

**Comment by jacmoe** [comment]
I did download it right after you telling me to @alcohol but I guess there was a slight delay.

Thank you for being so supportive! :)

I will not close this issue because I think it would be a good idea to see if it is fixed for @alxpub as well. ;)

**Comment by Gemorroj** [comment]
:+1:
