### ISSUE TITLE
Satis repository with self-signed certificate broken

### ISSUE THREAD

**Issue by alcaeus** [composer/composer#4786]
After upgrading to the most recent version, `composer update` no longer works for a repository with `local_cert` and a self-signed server certificate.

Here's the repository config from composer.json:
```
    "repositories":[
        {
            "type":"composer",
            "url":"https://packages.vendor.com/vendor",
            "options": {
                "ssl": {
                    "verify_peer": true,
                    "allow_self_signed": true,
                    "cafile": "scripts/build/config/cert/vendor.ca.pem",
                    "local_cert": "scripts/build/config/cert/client.pem"
                }
            }
        }
    ]
```

And here the output of a composer update call:
```
$ /usr/local/bin/composer --version
Composer version 1.0-dev (22d8b5dff497368a1a42bfbffc989c77031f04c6) 2016-01-18 07:59:12
$ /usr/local/bin/composer update
Loading composer repositories with package information
The "https://packages.vendor.com/vendor/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
https://packages.vendor.com/vendor could not be fully loaded, package information was loaded from the local cache and may be out of date
```

**Comment by alcohol** [comment]
@Seldaek related to your changes I presume? Not sure if this belongs here or on `composer/satis`.

**Comment by cs278** [comment]
Almost certainly it's an issue with the RFS changes.

@alcaeus Does the CN of your self signed certificate match the domain name for your repository? i.e. in your example does the CN equal `packages.vendor.com`.

**Comment by alcaeus** [comment]
> Does the CN of your self signed certificate match the domain name for your repository?

Yes, the CN is exactly that but the server relies on SNI to serve the correct host.

**Comment by Seldaek** [comment]
@alcaeus please check but I believe that will do the job :)

**Comment by alcaeus** [comment]
@Seldaek wow, that was quick. Your commit fixed it :+1:
