### ISSUE TITLE
Composer self-update thrown an error

### ISSUE THREAD

**Issue by harikt** [composer/composer#4787]
Hi, 

I was trying to update the composer and got an error as 

```
sudo composer self-update
[sudo] password for hari: 
Updating to version .
    Downloading: 0%           
                                                                               
  [Composer\Downloader\TransportException]                                     
  The "https://getcomposer.org/download//composer.phar" file could not be dow  
  nloaded (HTTP/1.1 404 Not Found)                                             

self-update [-r|--rollback] [--clean-backups] [--no-progress] [--] [<version>]
```

I did checked if the file exists there and it was giving a 404.

Talked with Jordi Boggiano https://twitter.com/seldaek/status/689056956393324544 .

To give more information about the error I did tried with -vvv

```
sudo composer self-update -vvv
[sudo] password for hari: 
Downloading https://getcomposer.org/version
Updating to version a2fc502c208fcb3ac4700b934057a33ca130644b.
Downloading https://getcomposer.org/composer.phar
    Downloading: 100%         
Use composer self-update --rollback to return to version c9501a4cc164b176de48e44b239e619cfd5f14e5
```

But this time I noticed the url was pointing to https://getcomposer.org/composer.phar instead of https://getcomposer.org/download//composer.phar .

Not sure what caused this bug and seems cannot reproduce it again.

Thank you.

**Comment by Seldaek** [comment]
Sounds like it got an empty https://getcomposer.org/version and then proceeded with that. I think the fix should prevent that from happening again.

**Comment by harikt** [comment]
Thank you @Seldaek . I wasn't sure if that is a bug or website related issue.
