### ISSUE TITLE
Composer cache on AmazonS3

### ISSUE THREAD

**Issue by tkleinhakisa** [composer/composer#4788]
Hello,

I've been trying to setup composer cache in an s3 bucket in order to share the cache between multiple servers in the same cluster.

I have created a pre-install command that register the s3 stream wrapper from the aws sdk and set the cache dir in my composer.json to s3://mybucket/myfolder

With this settings i endup with a folder called s3:/ at the root of my application

Is it a bug or am i misusing something ? Should i look deeper into composer plugins to achieve that ?

Thank you
Tom

**Comment by alcohol** [comment]
I don't think our codebase currently supports overriding the cache directory like that.

@Seldaek am I mistaken?

**Comment by Seldaek** [comment]
I really don't know if it has been tried. I can't think of why it wouldn't work though.

**Comment by tkleinhakisa** [comment]
I've made a few more tests but could not get it work, here's a part of my composer.json file

```
"config": {
        "cache-dir": "s3://bucket/composer-cache",
        ...
},
"scripts": {
    "pre-install-cmd": "Hakisa\\Bundle\\AwsBundle\\Composer\\S3Cache::registerStreamWrapper"
},
```

And the S3Cache file:
https://gist.github.com/tkleinhakisa/d9daffbfe3bd5e39c845

After running composer install the s3 folder only contains my test files from the S3Cache class and the composer cache is on my local file system in the `s3:` folder

**Comment by stof** [comment]
@tkleinhakisa the event might already be too late to register the stream wrapper. try using a composer plugin.

**Comment by fntlnz** [comment]
What about solve this problem at system level? Something like a shared mount point using FUSE    to mount s3 might be a good option. https://github.com/s3fs-fuse/s3fs-fuse

**Comment by tkleinhakisa** [comment]
I created a plugin to register the stream wrapper, added to composer with composer global require, and i can see it is activate when i do composer install in my main project (a file is uploaded to s3 using the copy function)
But the result is the same composer creates an s3: directory on my filesystem

Maybe composer uses the rename function to move downloaded files to the cache, this function only works on a give stream context so you can't mix file:// and s3://
If it's not required to be atomic it can be replace by copy+unlink

Any idea to go further is welcome, thanks

**Comment by Seldaek** [comment]
That's the cache handling code:

https://github.com/composer/composer/blob/master/src/Composer/Cache.php#L79

I'd advise you run composer from source and try to figure out what 
causes it to bypass your stream handler.

**Comment by tkleinhakisa** [comment]
The config value is given to a realpath method which adds a baseDir before the config value

https://github.com/composer/composer/blob/master/src/Composer/Config.php#L192

What do you think of adding a check for `://` in the realpath method ?
https://github.com/composer/composer/blob/master/src/Composer/Config.php#L344

**Comment by Seldaek** [comment]
Sounds good, let me know if the patch helps.

**Comment by tkleinhakisa** [comment]
Hello @Seldaek and thank you for the patch which is working fine, my cache dir is now correct

Unfortunately, i wasn't able to set my cache folder to an s3 directory because the plugins are loaded after the Cache class has been instantiated, so i guess the patch would work for native handled scheme only (like file or ftp)

i'll have to find another way :(

**Comment by Seldaek** [comment]
You could change the cache dir after initialization using a plugin as well
I guess but it's getting a bit nasty.
