### ISSUE TITLE
Composer archive latest stable

### ISSUE THREAD

**Issue by tschechniker** [composer/composer#4794]
Hi,

is there a way to tell composer archive to use the latest stable version? I already tried the following:

```
composer archive --format=zip slim/slim * --> 1.6.0
composer archive --format=zip slim/slim @stable --> 1.6.0
```

I'm always getting Version 1.6.0.

as a test i also tried to get a dev version:

```
composer archive --format=zip slim/slim @dev --> 1.6.0
```

Work works if you add the exact version to the command:

```
composer archive --format=zip slim/slim 2.6.2 --> 2.6.2
```

Seems like the version constraint is not working as expected?

My composer.json:

```
{
    "name": "test/test",
    "require": {}
}

```

**Comment by alcohol** [comment]
`@stable` is not exactly a version constraint, it's rather a stability flag. I think it could be adjusted though to pick the latest, rather than the earliest.
