### ISSUE TITLE
Timing and execution of composer plugins

### ISSUE THREAD

**Issue by mindplay-dk** [composer/composer#4796]
We use a custom installer, as per the [instructions](https://getcomposer.org/doc/articles/custom-installers.md#creating-an-installer) in the documentation - a package of type `composer-plugin`.

I noticed that, when an installer/plugin gets installed, updates are not necessarily processed in order.

For example:

```
$ composer update
HELLO from version 1 of my plugin!
Loading composer repositories with package information
  - Updating my/installer (dev-master 07751bb => 0.1.1)
    Checking out c9dbd396a55742638c0b60df8b1f7c81e4350b2a
...
Writing lock file
Generating autoload files

$ composer update
HELLO from version 2 of my plugin!
...
Generating autoload files
```

This output was doctored to demonstrate a point - `composer update` doesn't update my `composer-plugin` before running the installation, and on a subsequent `composer update`, with no changes made to anything, it will be running the newer version of the plugin, which it should have been running first.

As I understand, Composer resolves the entire dependency graph before installing anything, right?

Why doesn't it recognize that updates were made to `composer-plugin` packages?

These packages should need to be installed/updated/removed prior to installing/updating/removing anything else - otherwise, there's a good chance you're running a version of an installer (or some other plugin) that isn't actually compatible with packages being installed by it.

Perhaps `composer-plugin` type packages should be treated as dependencies of Composer - there's typically nothing in those packages relevant to anything other than the Composer tool itself, isn't that correct? Have the installer itself installed as a dependency of my project, with autoloading configured etc., is typically pretty uninteresting - a Composer plugin doesn't contain neither library nor project code. It doesn't typically contain consumer code at all, just stuff for Composer.

Or am I missing something?

**Comment by alcohol** [comment]
Yes, I believe you are missing something. When updating a plugin, you should simply run `composer update vendor/plugin --no-plugins --no-scripts`; that way no plugins or scripts are executed while simply updating that plugin. Afterwards you can run your install or update as usual.

**Comment by Seldaek** [comment]
Possibly related to #3791 but in any case, if all packages depending on the installer require the installer package, then it should be updated before the packages are. That's the best solution currently.

**Comment by mindplay-dk** [comment]
Was this fixed?

**Comment by Seldaek** [comment]
No but it's tracked in #3791 and possibly others so I closed this sorry for now explaining :)

**Comment by mindplay-dk** [comment]
:+1:
