### ISSUE TITLE
composer asset plugin can't install

### ISSUE THREAD

**Issue by Leffka** [composer/composer#4797]
Hello all. 
I want to set yii2.
Install composer, no problem.
In yiiframework.com written : "install the Composer Asset Plugin"
In console I write : composer global require "fxp/composer-asset-plugin:~1.1" and get : 
scrin shot http://pixs.ru/showimage/1jpg_2622563_20311454.jpg
where problem? 
I user Windows 7, php 5.6, apache 2.4

**Comment by alcohol** [comment]
Sorry, no clue. Looks like a CA error to me. Does your php have ssl support?

**Comment by Leffka** [comment]
Yes, in php.ini : extension=php_openssl.dll and folder '/php/ext' have file php_openssl.dll

**Comment by alcohol** [comment]
Can you retry with the latest Composer version?

**Comment by Leffka** [comment]
I can only download new version composer from getcomposer.org
who owns the composer on Windows? You can find /tmp/composer-cacert.pem in his system? I will be happy if you just give a link to the file, if it exists.

**Comment by alcohol** [comment]
https://getcomposer.org/download/ bottom of the page.

**Comment by curry684** [comment]
Your screenshot shows the `composer-cacert.pem` file being accessed from the `/tmp/` folder, which of course doesn't exist on Windows. That path is constructed in https://github.com/composer/composer/blob/master/src/Composer/Util/RemoteFilesystem.php#L785 with:

    $targetPath = rtrim(sys_get_temp_dir(), '\\/') . '/composer-cacert-' . $hash . '.pem';

Therefore `sys_get_temp_dir` is returning `/tmp` on your system. On Windows this should be `C:\Windows\Temp` or something instead which is actually compatible with Windows filesystems.

*However*, this can be overridden in 2 ways:
 1. In your `php.ini` file with the `sys_temp_dir` option. You can check this in the output of `phpinfo()`
 2. In your environment with the `TMPDIR` variable. You can check this by entering `echo %TMPDIR%` in a command prompt

In both cases this is a system misconfiguration on your dev machine and not an issue on Composer's end.

**Comment by Leffka** [comment]
Thank you! 
in php.ini : sys_temp_dir = "/tmp"
system variable $tmpdir don't exist

I did in php.ini : sys_temp_dir = "C:/Windows/temp"
in cmd : composer global require "fxp/composer-asset-plugin:~1.1"
and download is done.

**Comment by curry684** [comment]
@Leffka I would in general recommend commenting that line entirely, it's set up to default to a platform-correct value. Doesn't matter now as it's working but it's a setting that shouldn't be tampered with unless special needs arise.

**Comment by arfo90** [comment]
I had same issue and solved by skiping installing plug-in at all, maybe you can try 'composer install no-plugin' and manually install required php extension

**Comment by Leffka** [comment]
i wrote as i removed the earlier problem
