### ISSUE TITLE
Composer creates local directory called "~"

### ISSUE THREAD

**Issue by seggen-ibuildings** [composer/composer#4802]
Hi,

Composer started doing this weird thing a few days ago. I have no idea why, but instead of using /home/seggen/.composer for caching, it creates /path/to/project/~/.composer. Yes, it creates a directory called "~".

I'm on Mac OS X El Capitan (10.11.2) and Composer version 1.0-dev (4dd388074ede58361055925f709c36194d6aa5a4) 2016-01-19 12:24:00

This is not an urgent problem, by the way, I can use composer without any other issues.

**Comment by Seldaek** [comment]
Can you paste here the output of these two commands?

```
env | grep -e 'COMPOSER|HOME=|XDG'
composer config -l
```

**Comment by seggen-ibuildings** [comment]
```
$ env | grep -E 'COMPOSER|HOME=|XDG'
HOME=/Users/scatoeggen
COMPOSER_HOME=~/.composer
```

```
$ composer config -l
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
[repositories.packagist.type] composer
[repositories.packagist.url] https?://packagist.org
[repositories.packagist.allow_ssl_downgrade] true
[process-timeout] 300
[use-include-path] false
[preferred-install] auto
[notify-on-install] true
[github-protocols] [git, https, ssh]
[vendor-dir] vendor (/Users/scatoeggen/Workspace/ippz/ippz-hogthrob/vendor)
[bin-dir] bin (/Users/scatoeggen/Workspace/ippz/ippz-hogthrob/bin)
[cache-dir] ~/.composer/cache (/Users/scatoeggen/.composer/cache)
[data-dir] ~/.composer (/Users/scatoeggen/.composer)
[cache-files-dir] {$cache-dir}/files (/Users/scatoeggen/.composer/cache/files)
[cache-repo-dir] {$cache-dir}/repo (/Users/scatoeggen/.composer/cache/repo)
[cache-vcs-dir] {$cache-dir}/vcs (/Users/scatoeggen/.composer/cache/vcs)
[cache-ttl] 15552000
[cache-files-ttl] 15552000
[cache-files-maxsize] 300MiB (314572800)
[bin-compat] auto
[discard-changes] false
[autoloader-suffix]
[sort-packages] false
[optimize-autoloader] false
[classmap-authoritative] false
[prepend-autoloader] true
[github-domains] [github.com]
[disable-tls] false
[cafile]
[github-expose-hostname] true
[gitlab-domains] [gitlab.com]
[store-auths] prompt
[archive-format] tar
[archive-dir] .
[home] ~/.composer
```

**Comment by seggen-ibuildings** [comment]
come to think of it, I've added COMPOSER_HOME recently, will check that first ;)

**Comment by seggen-ibuildings** [comment]
yes, changing `export COMPOSER_HOME="~/.composer"` to `export COMPOSER_HOME="$HOME/.composer"` fixed it

thnx!

**Comment by Seldaek** [comment]
Hmm.. odd though, we should support both. I think it used to work.

**Comment by seggen-ibuildings** [comment]
Maybe it's an OS X thing

**Comment by Seldaek** [comment]
Does it actually store anything in that $project/~/.composer it creates or  is it only creating it empty (with a .htaccess I'd guess)?

**Comment by seggen-ibuildings** [comment]
Actually, it's just the .htaccess, you're right

**Comment by Seldaek** [comment]
OK I see the problem then I think. Give me a minute..

**Comment by seggen-ibuildings** [comment]
```
$ find ./~
./~
./~/.composer
./~/.composer/.htaccess
./~/.composer/cache
./~/.composer/cache/.htaccess
```

**Comment by Seldaek** [comment]
Can you try after self-update if it keeps creating those dirs if you put COMPOSER_HOME back to ~/.composer?

**Comment by Seldaek** [comment]
Also `composer config -l` should show the properly resolved value for `home` now I think and not `~/.composer`

**Comment by seggen-ibuildings** [comment]
I just updated to 395d115d9b40d799dadc9f4c5b73cd54820112e3, but I still get ./~

composer config -l gives me:
```
[home] ~/.composer (/Users/scatoeggen/.composer)
```

**Comment by seggen-ibuildings** [comment]
wait...

**Comment by seggen-ibuildings** [comment]
after removing ./~ and running it another time, it didn't appear anymore
