### ISSUE TITLE
Broken tree symbols in Windows shell

### ISSUE THREAD

**Issue by Rarst** [composer/composer#4803]
Getting tree pseudographics broken on Windows. CMD shell with ansicon. I can see them fine in source and echo in shell explicitly, so not yet sure at which point it goes wrong.

```
C:\server\ext>composer show -i -t
patchwork/jsqueeze v1.0.7 Efficient JavaScript minification in PHP
тФФтФАтФАphp >=5.1.4
devster/ubench 1.2.0 Micro PHP library for benchmarking
phpmd/phpmd 2.3.2 PHPMD is a spin-off project of PHP Depend and aims to be a PHP equivalent of the well known Java tool PMD.
тФЬтФАтФАpdepend/pdepend ~2.0
тФВ  тФЬтФАтФАphp >=5.3.7
тФВ  тФЬтФАтФАsymfony/config ^2.3.0
...
```

**Comment by Seldaek** [comment]
Not sure what's up..

In raw cmd.exe I get this:

![image](https://cloud.githubusercontent.com/assets/183678/12447644/247bd228-bf69-11e5-8b03-1082e6cb3c81.png)

With ansicon I see it like you all garbled..

![image](https://cloud.githubusercontent.com/assets/183678/12447726/74a34ede-bf69-11e5-8f05-33adb0bcb522.png)

And in conemu with bash and all I see it properly:

![image](https://cloud.githubusercontent.com/assets/183678/12447715/6427899e-bf69-11e5-8b53-1b1a57f46c3c.png)

I don't really have the motivation to check why ansicon is borked though.. I suggest using a proper terminal app on windows and not cmd. Or use --no-ansi as workaround to force the degraded mode.

**Comment by Rarst** [comment]
Seems to be ansicon issue, reported there. `--no-ansi` works fine for the record.

> I suggest using a proper terminal app on windows and not cmd.

There is nothing improper about cmd as for me \*shrug\*. :)

**Comment by rquadling** [comment]
Just for the record, Windows 10 x64, ANSICON V1.70, CHCP set to 65001 ...

![image](https://cloud.githubusercontent.com/assets/12801/12476656/b9fe281e-c022-11e5-95c8-3a6b77af3914.png)

If you are shelling to multiple shells, MAYBE ANSICON is getting loaded more than once?

My HKLM Autorun registry is set to ``(if %ANSICON_VER%==^%ANSICON_VER^% "C:\Tools\x64\ansicon" -p)``
