### ISSUE TITLE
Issue in composer.lock when requires a specific commit.

### ISSUE THREAD

**Issue by bibich** [composer/composer#4810]
I'm working on [Thelia](http://github.com/thelia/thelia), and for this project we're using composer to manage our requirements. For a library (Propel) we need a specific version (commit).

In our `composer.json` you have this requirement : 

```json
...
"require": {
        "propel/propel": "dev-master#793aea6b762d9a72b083bfc49c74c574f67650c8",
        ...
}
```
    
and in our `composer.lock` :

```json
{
    "name": "propel/propel",
    "version": "dev-master",
    "source": {
        "type": "git",
        "url": "https://github.com/propelorm/Propel2.git",
        "reference": "793aea6b762d9a72b083bfc49c74c574f67650c8"
    },
    "dist": {
        "type": "zip",
        "url": "https://api.github.com/repos/propelorm/Propel2/zipball/2951d2241fc69f3fb925ddc3d087cba0a04bed9a",
        "reference": "793aea6b762d9a72b083bfc49c74c574f67650c8",
        "shasum": ""
    }
    ...
```

Here, the `source` is ok, but the `dist` value is not correct IMHO. The reference is good but the URL points to the wrong commit. The consequence is that if we execute a `composer install --prefer-dist` the wrong version is used.

An other problem is when we execute a `composer require .../...` the composer.lock is updated and the URL of the dist part of propel/propel is updated to the last version of the dev-master.

Is it a desired behavior or an issue, or something that done do correctly ?

**Comment by cs278** [comment]
This is expected, the documentation advises not to use it long term for this very reason.

**Comment by alcohol** [comment]
See also https://github.com/composer/composer/pull/4713/files#diff-228c6b20c0d1da4d1c06be15037e0063R85

@Seldaek can you merge that so I can start linking to the actual page?

**Comment by bibich** [comment]
Ok. Thanks.
As a workaround, I think I will fork the repo and tag it properly, and require this fork instead of the main repo.
