### ISSUE TITLE
Composer update: output correct, but vendors not updated

### ISSUE THREAD

**Issue by edrush** [composer/composer#4816]
Hi, 

I searched for a while but could not find a related issue...plus it's maybe a local problem that we caused ourselves:

I forked a project, added a vcs entry to the repositories section of my composer.json...pull-request is done, I'm ready to move back. So I deleted the vcs entry for the project. Running *composer update* looked perfectly, it showed exactly what I was expecting to see...checked out current original release...but my vendor folder is stuck on my last commit of my fork.

I tested running *composer install/update* in an empty directory, worked great, our deployment servers also apply the .lock fine. The vendor folder is not a git repo anymore. But in my local folder it is, *git remote -v* points to the original repo.

I have to admit that in my local vendor folder I manually added another remote to work on it. Maybe that caused the issue? I know I should not touch the vendors, right?

Thanks! Wolfram

**Comment by alcohol** [comment]
Touching the directories inside `vendor` is not advised but should not necessarily break something. Adding remotes and switching tracking branches might confuse Composer though or leave that particular  directory in a state of limbo. Try running `rm -rf vendor/{vendor}/{package} && composer install`.

**Comment by edrush** [comment]
Thanks for your answer! That was what I thought, too. Ok!
