### ISSUE TITLE
BitBucket private repos not supported?

### ISSUE THREAD

**Issue by ghost** [composer/composer#482]
Given the following `composer.json`:

    {
        "name": "vendor/private-bundle",
        "type": "symfony-bundle",
        "require": {
            "php": ">=5.3.2",
            "vendor/other-private-bundle": "*",
            "symfony/framework-bundle": "2.1.*"
        },
        "repositories": [
            {
                "type": "vcs",
                "url": "git@bitbucket.org:vendor/other-private-bundle.git"
            }
        ],
        "autoload": {
            "psr-0": {
                "Vendor\\PrivateBundle": ""
            }
        },
        "target-dir": "Vendor/PrivateBundle"
    }

and calling `php composer.phar install` results in:

    Installing dependencies
    Your requirements could not be solved to an installable set of packages. 
    Problems:
    *The requested package "vendor/other-private-bundle" with constraint [] could not be found.*

I also tried to define repo url in other forms:
- `https://vendor@bitbucket.org/vendor/other-private-bundle.git`
- `https://bitbucket.org/vendor/other-private-bundle`
- `https://bitbucket.org/vendor/other-private-bundle.git`
without success :(

Dependency `vendor/other-private-bundle` has its own `composer.json` definition file.

**How can I use private bitbucket repository as a dependency?**
Am I doing something wrong or private repos are currently not supported?

**Comment by dalevink** [comment]
**Seems to work now.**
The Bitbucket SSH url for private repos is working for me.   As in the initial example:
`git@bitbucket.org:vendor/other-private-bundle.git`

Nice work somebody!

**Comment by SoboLAN** [comment]
I tried this with `composer 1.0.0-alpha11` on Windows 7 using a *private* BitBucket GIT repository.

Using the URL like this works:

```json
{
    "type": "git",
    "url": "https://vendor@bitbucket.org/vendor/project.git"
}
```

But using the URL like this does not:

```json
{
    "type": "git",
    "url": "git@bitbucket.org:vendor/project.git"
}
```

Changing the type from `git` to `vcs` makes no difference.

So I don't know how solved this really is. Or maybe I'm doing something wrong.

---

PS: This is not an actual problem I ran into, I just wanted to reproduce the issue to see if it still exists :) .

**Comment by Seldaek** [comment]
@SoboLAN thanks but please try after a `composer self-update` so you get the very latest version. Both should work really as long as you have SSH key authentication enabled and your ssh key is present on bitbucket.

**Comment by scippio** [comment]
Still not supported? :-1:

**Comment by Seldaek** [comment]
Closing as bitbucket should be supported and #5055 just added support for oauth even. If there's still an issue please report a new one to avoid spamming people here.
