### ISSUE TITLE
Is composer the recommended package manager for PHP?

### ISSUE THREAD

**Issue by schmunk42** [composer/composer#4826]
This is question arised from here https://github.com/docker-library/php/issues/177#issuecomment-174606577

I know that it's not an official one, but it's also the de-facto package manager for PHP. I think to official one is PEAR, although I think composer has much more attention nowadays.

Has there been a discussion about this?

I thought I ask here first, before maybe going to ask the question at a PHP mailing list, like http://news.php.net/group.php?group=php.standards

**Comment by alcohol** [comment]
I think PEAR served its purpose back in the day, but it has lost a lot of ground to Composer. I dare say that Composer is probably more popular now a days. There is no push however to make Composer the official _anything_. It's there for anyone to use. Installing it takes but a few seconds. The choice is up to the end users :-)

**Comment by Seldaek** [comment]
Moving that discussion over to the docker issue I think it makes more sense :)
