### ISSUE TITLE
Source reference missing from `RootPackage`

### ISSUE THREAD

**Issue by Ocramius** [composer/composer#4828]
When querying `$composer->getPackage()`, the source/dist references are missing:

```php
$package = $composer->getPackage();

var_dump($package->getVersion()); // 2.0.9999999.9999999-dev
var_dump($package->getSourceReference()); // NULL
var_dump($package->getDistReference()); // NULL
```

This seems to be due to the `RootPackageLoader` just looking into the guessed version (via `VersionGuesser#guessVersion()`), but additional information such as the current commit number/hash is missing from git/hg repositories.

**Comment by curry684** [comment]
To clarify: this occurs in a plugin using the POST_INSTALL_CMD and POST_UPDATE_CMD events.

**Comment by sashman** [comment]
I'd like to help out with this, but I'm fairly new to the composer internals. I've had a look at `RootPackageLoader` and `VersionGuesser`. Am I correct in thinking that (using git) `git branch --no-color --no-abbrev -v` output can be used to determine the source commit hash? So to fix this, it should be a case of extending `VersionGuesser` to parse the hash out too?

**Comment by Seldaek** [comment]
I think this kinda has to be done out of the VersionGuesser, or as a new method to it at least, as it's not really related to the version per se it's just the commit hash. It would be nice to be able to do it without adding one more call to an external git process though as these just make our bootstrapping process slower and slower.

**Comment by Seldaek** [comment]
I guess we could read .git/HEAD if present then resolve the reference to find the commit hash, probably faster than spinning up a git process.

**Comment by sashman** [comment]
Awesome, was thinking along the same lines. So either make VersionGuesser method that would return an array with `version`, `commit`, etc data in it or an object like VersionInfo? Another way would be to do the gathering of the data on construct? Not too sure about the latter though...

**Comment by Seldaek** [comment]
I'd say returning an array of version and reference sounds good.

**Comment by Ocramius** [comment]
> would return an array 

Make it a tiny object plz - had already 3 or 4 failures due to keys missing in various places :-P

**Comment by Seldaek** [comment]
Well you wouldn't have to use it, the RootPackageLoader uses it and if the reference is present will just set it on the root package.

**Comment by Ocramius** [comment]
:+1:
