### ISSUE TITLE
Documentation for Plugins a bit obscure.

### ISSUE THREAD

**Issue by Gisleburt** [composer/composer#4830]
I recently created a plugin for composer to register incoming modules. The documentation for plugins is mostly pretty good with the exception of how to handle events. There is one example, and no part of it is actually explained.

I initially posted the question to StackOverflow but was able to answer it myself: http://stackoverflow.com/questions/34995427/composer-plugin-post-autoload-dump-fires-too-late/34996030#34996030

Please consider updating the example section with the following:

To register a method to an event, simply return an array where the key is the event name ([listed here](https://getcomposer.org/doc/articles/scripts.md#event-names)) and the value is the name of the method in this class to be called.
```php
/**
 * @return array
 */
public static function getSubscribedEvents()
{
    return [
        'post-autoload-dump' => 'methodToBeCalled',
        // ^ event name ^         ^ method name ^                   
    ];
}
```
By default, the priority of an event handler is set to 0. The priorty can be changed by attaching a tuple where the first value is the method name, as before, and the second value is an integer representing the priority. Higher integers represent higher priorityes therefore, priortity 2 is called before priority 1, etc.
```php
/**
 * @return array
 */
public static function getSubscribedEvents()
{
    return [
        // Will be called before events with priority 0
        'post-autoload-dump' => ['methodToBeCalled', 1] 
    ];
}
```
If multiple methods should be called, then an array of tupples can be attached to each event. The tupples do not need to include the priority. If it is omitted, it will default to 0.
```php
/**
 * @return array
 */
public static function getSubscribedEvents()
{
    return [
        'post-autoload-dump' => [
            ['methodToBeCalled'      ], // Priority defaults to 0
            ['someOtherMethodName', 1], // This fires first
        ]
    ];
}
```

**Comment by Seldaek** [comment]
Please send a pull request to update https://github.com/composer/composer/blob/master/doc/articles/plugins.md - that'd make it a lot easier to apply your changes :)

**Comment by Gisleburt** [comment]
Want me to keep the old array syntax?

**Comment by Seldaek** [comment]
Probably best for now yes please.

**Comment by Gisleburt** [comment]
Hopefully that's ok.

**Comment by Seldaek** [comment]
Yup that's great thanks, I just wrapped the text in c4df3ec0d4394e7cd4e55b6b076b62888d05c3d2 to follow our ~80char lines convention
