### ISSUE TITLE
Could not get default port for unknown scheme: ssh2.sftp 

### ISSUE THREAD

**Issue by AlbertKozlowski** [composer/composer#4835]
After last changes we can not longer use Satis repositories using ssh repositories. Exception is thrown at: 

    Util/RemoteFilesystem.php:1010

Error:

     Could not get default port for unknown scheme: ssh2.sftp

**Comment by Seldaek** [comment]
Can you try again with latest?

**Comment by AlbertKozlowski** [comment]
Thanks for fast fix, it works now.
