### ISSUE TITLE
Question - repeated "man-in-the-middle attack" error, forced to use Chinese mirror

### ISSUE THREAD

**Issue by akfarrington** [composer/composer#4836]
I live in China. I'm trying to install Laravel, but have been forced to use a Chinese mirror because every attempt with packagist.org and https://packagist.jp, a Japanese mirror, have failed.

This might be a stupid question, and I'm sorry if it is, but I don't know. Is http://packagist.cn/ a valid mirror, and is there any way to tell? After that Chinese tampered with xcode appstore virus thing, I'm a bit wary to use anything downloaded in China that can't be verified.

I'm using an up to date composer, and using keys found at https://composer.github.io/pubkeys.html if that makes any difference.

**Comment by alcohol** [comment]
To answer your question(s);

- packagist.org is the *only* repository maintained by the Composer team,
- the keys you referenced are only used to check whether or not the Composer phar/installer has been tampered with.

There is no official mirror in China. I do believe various third parties are attempting to setup mirrors though.

It is also worth mentioning that Packagist (and said mirrors) merely serve meta content. The actual packages you install are usually downloaded from Github.

**Comment by akfarrington** [comment]
Well, after comparing https://packagist.org/packages/laravel/laravel and https://packagist.org/packages/laravel/laravel, they *look* the same. Sounds like I should be fine. Thanks for your response!
