### ISSUE TITLE
Missing pubkeys: FAIL after self-update

### ISSUE THREAD

**Issue by Steveorevo** [composer/composer#4839]
After running self-update, we're getting pubkeys: FAIL. This appears to be a cross platform issue (we're seeing on Mac, Linux, and UNIX). What do we need to do to resolve this issue? 
```
scarroll@win8-testing-vm ~/Documents/Websites/www.example.dev
$ composer diagnose
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking composer version: FAIL
You are not running the latest version, run `composer self-update` to update

scarroll@win8-testing-vm ~/Documents/Websites/www.example.dev
$ composer self-update
Updating to version 593b88e41487f481d4368a4d331146914c1c2981.
    Downloading: 100%
Use composer self-update --rollback to return to version 96ff17c520b398d2a102d08      2bf0d4df3bd5c18a8

scarroll@win8-testing-vm ~/Documents/Websites/www.example.dev
$ composer diagnose
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
```

**Comment by curry684** [comment]
Run composer self-update --update-keys to set them up

Did you do that?

**Comment by Steveorevo** [comment]
Running the suggested self-update with --update-keys prompts for information; not sure what to supply and google's the "--update-keys" expression is tricky (at best).

**Comment by Steveorevo** [comment]
Open https://composer.github.io/pubkeys.html to find the latest keys. 

Resolved!

**Comment by curry684** [comment]
I asked because I can indeed reproduce your issue on my Linux boxes, but it says:

    # composer self-update --update-keys
    Open https://composer.github.io/pubkeys.html to find the latest keys
    Enter Dev / Snapshot Public Key (including lines with -----): 

So I would start at https://composer.github.io/pubkeys.html  ;)

**Comment by Seldaek** [comment]
That was kinda bad luck there.. The keys are setup automatically on the
next selfupdate next time there's an update. Anyway glad you figured it
out. Wasn't the link to the keys displayed when doing --update-keys btw? I
thought it was. Can't check right now but if it isn't we need to fix that.

**Comment by Seldaek** [comment]
Ah yes it does indeed. Missed the last email on my phone. Good then.

**Comment by Steveorevo** [comment]
The links were displayed, and the public keys are present in inside composer.phar/src/Composer/Command/SelfUpdateCommand.php

On a virgin system the user folder does not contain .composer/keys.dev.pub or .composer/keys.tags.pub files. 

Is it the intension for composer to prompt for the contents, even if the current source already contains them? Assuming that composer.phar came from a trusted source, should it write the default keys if none are present?

**Comment by Seldaek** [comment]
@Steveorevo the thing is on a virgin system when you install composer the installer will set up the keys. Otherwise if you already have composer the first time you self-update to a version with the keys nothing happens except in diagnose it starts to complain about keys, *next* time you self-update though it will see that the keys are missing and set them up. It's kind of an edge case intermediate situation you found yourself in, I just didn't expect people to run diagnose as religiously as you seem to do :) But anyway I think this will solve itself within a few days as people update and the keys get set up so I'd rather close.

**Comment by narainsagar** [comment]
Hello everyone, I am facing this same issue with my gitlab deployment pipeline.. how can I update latest keys from https://composer.github.io/pubkeys.html on my pipeline via scripts automatically ?

<img width="815" alt="screen shot 2018-04-29 at 10 55 51 pm" src="https://user-images.githubusercontent.com/13800762/39409452-bd8fe9ba-4c00-11e8-8cb8-097a0af6e03e.png">

**Comment by Seldaek** [comment]
@narainsagar you can download those keys from the links on that page, or you could just set up composer using https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md so you get the latest keys installed automatically.
