### ISSUE TITLE
Warning message "composer-plugin-api"

### ISSUE THREAD

**Issue by camfindlay** [composer/composer#4841]
Have had a number of SilverStripe CMS community members report seeing this warning message when using composer to manage module dependancies etc.

**The "composer/installers" plugin requires composer-plugin-api 1.0.0, this *WILL* break in the future and it should be fixed ASAP (require ^1.0 for example).**

Would be great to get some understanding on this message and what should be done to resolve this. We have seen it across multiple OS and multiple versions of PHP.

Thanks in advance.

**Comment by Seldaek** [comment]
Oh I didn't realize composer/installers was violating this.. sorry :) 1.0.23 release of it fixes this, if you update it it should stop nagging you.
