### ISSUE TITLE
Autoloader different OS platforms

### ISSUE THREAD

**Issue by ciprogrammer** [composer/composer#4844]
I added composer to an app built on a linux box and now that it has been deployed to a windows box, the autoloader does not work. Does the windows box need to have composer installed and have "composer install" or "composer update" be run to rebuild the autoloader under the windows environment?

Thanks

**Comment by Seldaek** [comment]
Usually it shouldn't no, but there might be edge cases where it needs to. I  am not sure, without any specifics as to what goes wrong or why it's a bit hard to help.. Check the vendor/composer/autoload* files to see how they look and what might be wrong?

**Comment by ciprogrammer** [comment]
I just added composer to the windows box, deleted the composer.lock file, and ran composer install to rebuild the deps from the composer.json and I get the same error in my app, that the classes are not available. All using the same codebase that finds the classes in a linux environment so the call to the autoloader must be right. Please advise.

**Comment by ciprogrammer** [comment]
The lib is league/oauth2 and appears to be psr-4 so can I force the autoload of the files?

**Comment by ciprogrammer** [comment]
I deleted the vendor dir and composer.lock and ran composer install on the win server and everything downloaded and built a working autoloader.

**Comment by cs278** [comment]
You shouldn't be deleting the `composer.lock` unless you want different packages to what you developed on. https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file

**Comment by Seldaek** [comment]
Well now that you have a working one on windows and on linux you could compare the autoload config files as I suggested above and see what's different between them because it shouldn't be needed AFAIK.

**Comment by ciprogrammer** [comment]
@cs278  I deleted it, along with the vendor directory, to get a fresh set of files for debugging purposes.

@Seldaek Where did you suggest such a comparison above? Thanks but I had to build a Windows development VM for other reasons, such as connecting to an Azure db via the native Windows sqlsrv driver anyway so this was solved by developing on the Windows VM.

**Comment by Seldaek** [comment]
@ciprogrammer I was referring to:

> Check the vendor/composer/autoload* files to see how they look and what might be wrong?

If you compare the windows and linux ones then you might notice what is off and causing this.
