### ISSUE TITLE
 [ErrorException] fopen(tmp/composer-cacert-39eaf16e26c08cc90d728865f1c60406ee5d864d5963f72ed > e2a1cbb127f95ca.pem): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by blackdogg** [composer/composer#4854]
Hello, i get the following exception when running any composer command on my Windows 7 system with php-5.6.17-Win32-VC11-x86 on it, i tried both ways of getting composer, with installer exe and with the command line, it is installed but anytime i run it i have this
> [ErrorException]
> fopen(tmp/composer-cacert-39eaf16e26c08cc90d728865f1c60406ee5d864d5963f72ed
> e2a1cbb127f95ca.pem): failed to open stream: No such file or directory

**Comment by alcohol** [comment]
Please modify your php.ini and make sure that the temporary directory setting is not set to `/tmp` (instead, leave it blank).

**Comment by blackdogg** [comment]
Hello thanks for the answer, but it is set in php.ini sys_temp_dir = "./tmp" i tried multiple setups even reinstalling composer, but still same error, i am totally lost on this one.

**Comment by alcohol** [comment]
Did you read what I said?

**Comment by blackdogg** [comment]
Oh man i am sorry, i just woke up lol, INDEED it fixed the issue thanks a lot, i would've never thought of that. THANKS !!

**Comment by alcohol** [comment]
No problem :-)

**Comment by richardhj** [comment]
Hey, this error occurs in my environment. `composer.phar` is up-to-date and `sys_temp_dir` is `(no value)`
```
example@vsrv12345:/html/contao/composer$ /bin/php-5.6 composer.phar install --dry-run
                                                                                                                                                      
  [ErrorException]                                                                                                                                    
  fopen(/tmp/composer-cacert-300c74d6960d46715ffed607c8e36acfa7cbcad49862bb1b67d3c43dea9bfb40.pem): failed to open stream: No such file or directory  
```

Where to start diagnostics?

**Comment by sreebash** [comment]
I have same problems here!! Solving method explain briefly please ?[ErrorException]
  fopen(C:\Users\sreebash\AppData\Local\Temp;C:\xampp\php/composer-cacert-e62a07e61e5870effa81b430e1900778943c228bd7d
  a1259dd6a955ee2262b47.pem): failed to open stream: Invalid argument
