### ISSUE TITLE
Security Exception

### ISSUE THREAD

**Issue by DavidKohav** [composer/composer#4855]
[Composer\Repository\RepositorySecurityException]                                                    
  The contents of http://packagist.org/p/provider-2014%24c3169c455742834b6a166fcde2c14e3dafcdfacaad27  
  1c03b7056125c89547da.json do not match its signature. This should indicate a man-in-the-middle atta  
  ck. Try running composer again and report this if you think it is a mistake.

**Comment by alcohol** [comment]
Did you try running it again?

**Comment by DavidKohav** [comment]
Yesterday Yes, several times.
I'll try again now.

**Comment by DavidKohav** [comment]
Now it works, thanks
