### ISSUE TITLE
PHP Strict Standards: Declaration of Composer\Console\Application::renderException()

### ISSUE THREAD

**Issue by paladox** [composer/composer#4856]
In https://phabricator.wikimedia.org/rCICP297dd5a1fcac3cb31977503b302947ef9663245b

It is getting this error

PHP Strict Standards:
 Declaration of Composer\Console\Application::renderException() should be
 compatible with that of Symfony\Component\Console\Application::renderException()
 in
 integration/composer/vendor/composer/composer/src/Composer/Console/Application.php
 on line 38

**Comment by cs278** [comment]
Fixed on master: https://github.com/composer/composer/commit/2491679ba3584886c191f5869303b9c431af3b91 Alternatively using `symfony/console` < 3 should resolve the issue.

**Comment by alcohol** [comment]
This should be resolved already as @cs278 pointed out. Can you confirm (and close this issue)?

**Comment by paladox** [comment]
Yes. I will re open if problem happends. Thanks for suggesting an alternative fix and also saying that it was fixed in master.
