### ISSUE TITLE
Terminate composer config generator

### ISSUE THREAD

**Issue by scion4581** [composer/composer#4858]
Sorry guys, mb this question not very relate with Composer itself, 

anyway how can I stop creating composer.json? 

My actions:

1)I'd typing command composer init
2)Then composer requires set package name,author...

What I need use of command to stop this, sure I could exit from terminal but is there any ways? 

Thanks

**Comment by alcohol** [comment]
In most terminals, the key combination of `ctrl` + `c` will suffice.
