### ISSUE TITLE
Take `autoload` into account for Locker::getContentHash()

### ISSUE THREAD

**Issue by pyrech** [composer/composer#4859]
Following #4515 and https://github.com/composer/composer/commit/6c9b161c43fe7e3f2094911ae69a9f850fd70dba, I wonder if the `Composer\Package\Locker::getContentHash()` method should take into account the `autoload` key (and maybe `autoload-dev`)? Because if I modify the autoload information of a package inside a monolyth repository (with the `path` type), then my package is not updated because composer think nothing changed.

Would you accept a PR for changing this? (not sure if changing this method has impact elsewhere tough)

**Comment by stof** [comment]
The autoload of the root package does not impact the dependency resolution at all.

If your issue is related to the usage of path repositories, it means ``repositories`` should be taken into account.

**Comment by alcohol** [comment]
@pyrech `path` generally uses symlinks. So there is nothing to update. Simply run `composer dump-autoload` again.

**Comment by pyrech** [comment]
Hmm, let's explain it more clairly:

- I have a git repository which contain two packages : A and B
- Package B requires A with a path repository ;
- When I change the autoload section of A, even after updating B, the packageB/vendor/composer/installed.json still contains the old information of A (with old autoload section)

I have to manually remove the package info from the vendor/composer/installed.json of B to refresh its information about A.

I really think this comes to https://github.com/composer/composer/commit/6c9b161c43fe7e3f2094911ae69a9f850fd70dba#diff-620a11fbfc7f8f33cc6bc0b1ebc253b4L125 : the `reference` does not change because autoload is not taken into account by the locker, so obviously composer does not see any change. Is that more clear?

**Comment by alcohol** [comment]
Alright, can you see if #4863 fixes it?

**Comment by pyrech** [comment]
Thanks! :-)
