### ISSUE TITLE
PHP version requirements problem on Ubuntu

### ISSUE THREAD

**Issue by skillberto** [composer/composer#4860]
I've got a following error, when I tried to update a package:

> ******** requires php >=5.5 -> your PHP version (5.5.9-1ubuntu4.14) or value of "config.platform.php" in composer.json does not satisfy that requirement.

Why does it wrong? "5.5.9" is higher than "5.5" (Or not?).
Or composer can not match "5.5.9" from "5.5.9-1ubuntu4.14" ?

**Comment by curry684** [comment]
I cannot reproduce this with `5.6.17-0+deb8u1` using `>=5.6`. Everything behind the hyphen should also be ignored. So uhm:

> or value of "config.platform.php"

Did you [define this](https://getcomposer.org/doc/06-config.md#platform)?

**Comment by cs278** [comment]
`composer show --platform` will tell you what PHP version Composer has detected and if it has been overridden by config.

**Comment by curry684** [comment]
Just did a practical test in PlatformRepository, replacing the given strings into PHP_VERSION for the version parser to normalize, and `5.5.9-1ubuntu4.14` normalizes to `5.5.9.0` just fine as it should.

**Comment by skillberto** [comment]
Thank you guys!
Ok, I found it. My `composer.json` has a platform config... :unamused:
