### ISSUE TITLE
failed to connect to network - error installing

### ISSUE THREAD

**Issue by edionmelarosa** [composer/composer#4862]
I can't install successfully. Im getting curl: (7) Failed to connect to getcomposer.org port 443: Network is unreachable after running curl -sS https://getcomposer.org/installer | php -- --install-dir=bin --filename=composer

This is my curl details:
curl --version
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP 

Thanks

**Comment by harikt** [comment]
@edionmelarosa I wonder whether it is related to your network. 

You can also download from https://getcomposer.org/composer.phar . 

If you have wget installed you can try 

```
wget https://getcomposer.org/composer.phar
```

also.

**Comment by curry684** [comment]
Failed to connect to getcomposer.org port 443: Network is unreachable

That is most certainly a local network issue. Things to try:

1. Does `ping 87.98.253.108` start pinging an IP? If not, your network is broken
2. Does `ping getcomposer.org` start pinging an IP? If not, your DNS is broken.
3. Does `curl -sS https://www.google.com` give useful output, being some lines of HTML? If not, your outgoing port 443 for HTTPS has issues.

In any of these cases you may be on a corporate network with proxy requirements. Your network administrator will be able to help you in that case.

**Comment by edionmelarosa** [comment]
Sorry for the late reply. Yes this was a network issue. Thanks

**Comment by wawneeds** [comment]
Hey @curry684 , I'm having the same issue, however none of the troubleshooting steps listed above produce errors, 1, 2 and 3 are all successful.

Can you help ?

**Comment by curry684** [comment]
Assuming Linux, please run the following set of commands:
```sh
ping -c 3 87.98.253.108
ping -c 3 getcomposer.org
curl -sS https://www.google.com
traceroute getcomposer.org
```
Please provide full output in [a gist](https://gist.github.com/), feel free to replace identifiable data like your username or the first IP of the trace with dummy data.

**Comment by wawneeds** [comment]
Actually it's Windows here's the output: https://gist.github.com/wawneeds/ac03b2270966def21471231964611daf, but apparently there was some kind of problem with the server, which seems to have been solved now without any changes from my end. here's the output I had earlier when running self-update:

```
> C:\ProgramData\Composer\bin\composer.bat self-update
Updating to version 1.2.0 (stable channel).

                                                                                                                       
  [Composer\Downloader\TransportException]                                                                             
  The "https://getcomposer.org/download/1.2.0/composer.phar.sig" file could not be downloaded: failed to open stream:  
   A connection attempt failed because the connected party did not properly respond after a period of time, or establ  
  ished connection failed because connected host has failed to respond.
```                                                
but now it works as expected:
```
Updating to version 1.2.0 (stable channel).
    Downloading: 100%
Use composer self-update --rollback to return to version a33b205561ddeb8c262a453dc64e158379c1ee5e
```
I should mention also that earlier I was able to download composer.phar using a browser but not with curl or self-update.

**Comment by curry684** [comment]
Ok, problem solved then  😄

**Comment by vanthanhkok** [comment]
Just do it : `echo ipv4 >> ~/.curlrc`
