### ISSUE TITLE
Composer clones non-required vcs.

### ISSUE THREAD

**Issue by MrEliasen** [composer/composer#4864]
I have a composer.json file which looks like this:
```
{
    "repositories": [
        {
            "type": "vcs",
            "name": "(redacted)/(redacted)",
            "url": "git@bitbucket.org:(redacted).git"
        },
        {
            "type": "vcs",
            "name": "(redacted)/(redacted)/(redacted-1)",
            "url": "git@bitbucket.org:(redacted).git"
        },
        {
            "type": "vcs",
            "name": "(redacted)/(redacted)/(redacted-2)",
            "url": "git@bitbucket.org:(redacted).git"
        }
    ],
    "require": {
        "php" : ">=5.5",
        "components/jquery" : "1.*",
        "components/modernizr" : "*",
        "components/font-awesome" : "*",
        "components/normalize.css" : "*",
        "(redacted)/(redacted)" : "*",
        "(redacted)/(redacted)/(redacted-1)" : "*"
    },
    "discard-changes": true,
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

The problem is, all repo's are private and can only be access with a read-only deployment key, and not all installations should have access to each package (in this case "redacted-2). Even if the package is not specified in `require `, composer tries to download and cache the "redacted-2" package - which of cause fails:

```
[RuntimeException]
Failed to execute git clone --mirror 'git@bitbucket.org:(redacted-2).git' '/root/.composer/cache/vcs/(redacted-2).git/'
Cloning into bare repository '/root/.composer/cache/vcs/(redacted-2).git'...
conq: repository access denied. deployment key is not associated with the requested repository.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

Am I missing some setting or this is a bug? It does not seem logical that a package not specified as a requirement or dependency should be cached. Or am I missing the bigger picture here?

Thanks!

Edit:
Composer Version: `cff35071b68e286f68ac64908c990c15b3ac4a0d.`
OS: `Ubuntu 14.04.3 x64` - Fresh install

Edit:
The reason packages which may or may not get accessed from a particular installation is because we wanted to keep a single repo for the main package, and if anything needed to be added to a specific installation, simply add the deployment key and add the required package to the require.

At this point you might think that why not just add the package when adding the package to require? It's to avoid issues with members of the team not knowing JSON syntax and or composer, to simply add the vender/package to the require list to keep things simple.. well that is the intention.

**Comment by alcohol** [comment]
Since it is a VCS repository, Composer will clone it locally before doing starting the dependency resolution. It **needs** to do this because that is the only way it can read the tags from the repository or detect any `composer.json` files (which it needs to determine what package(s) it can actually find in that repository).

So no, this is not a bug but expected behaviour rather.

**Comment by MrEliasen** [comment]
Alright, but why would it need to pull down the repo when it's not required? I mean, why  read the composer.json of a VCS repo if it's not defined as being a required package? Sorry if I am missing something obvious.

I am still getting around understanding how Composer works, so if there are any alternative ways to go about this I am all ears :). I just need it to be able to check for a version in the composer file and update if needed. Would "package" be suitable for this? I thought I read something about it not using composer.json for packages?

Thanks for the reply, much appreciated!

**Comment by alcohol** [comment]
Again, because it has no information about the repository beforehand. It does not know if it is required or not because it does not know what is inside of it. Hence it will first read the information from the repository, and then it will process your require directives.

**Comment by MrEliasen** [comment]
Ah right, I get it now. Thanks.

**Comment by alcohol** [comment]
If you are worried about modification of the composer.json being too complex, you can dynamically add new repositories and requirements to a project composer.json with the CLI commands too:

```
composer config repositories.vendor_package vcs 'git@bitbucket.org/vendor/package'
composer require vendor/package
```

See https://getcomposer.org/doc/03-cli.md#modifying-repositories for more details.

**Comment by MrEliasen** [comment]
Ah, that might be a solution. Thanks for the help, much appreciated.

**Comment by alcohol** [comment]
Note that the name of the repository does not need to match the actual package hosted in the repository (they can, but it is not a requirement).
