### ISSUE TITLE
what for "--prefer-dist" command

### ISSUE THREAD

**Issue by scion4581** [composer/composer#4867]
Sorry about newbie question, but I dont understand what for command "--prefer-dist"

This I'd read from docs but still confused
--prefer-dist: Install packages from dist when available.

in some tutorials peoples writes 
"composer create-project laravel/laravel myproject --prefer-dist"

and other same only without "--prefer-dist" - so what the differents?

 thanks

**Comment by hkdobrev** [comment]
`--prefer-dist` would try to download and unzip archives of the dependencies using GitHub or another API when available. This is used for faster downloading of dependencies in most cases. It doesn't download the whole VCS history of the dependencies and it should be better cached. Also archives on GitHub could exclude some files you don't need for just using the dependency with `.gitattributes` exclude directive.
`--prefer-source` would try to clone and keep the whole VCS repository of the dependencies when available. This is useful when you want to have the original VCS repositories cloned in your `vendor/` folder. E.g. you might want to work on the dependencies - modify them, fork them, submit pull requests etc. while also using them as part of the bigger project which requires them in the first place.

The default is `--prefer-dist` as far as I know. The method which would be used depends also on what is saved as available sources for this dependency in the `composer.lock` file.

As you see these are only preferences, if a dependency is required using a VCS repository which does not provide archives such as GitHub API, then the only available option is to clone the repository.

**Comment by scion4581** [comment]
Thank you very much for this clear answer! Now this issue has to be closed

**Comment by xabbuh** [comment]
@scion4581 You can close yourself. :)

**Comment by stof** [comment]
@hkdobrev no, the default is the "auto" mode, which uses dist for any release (be it alpha, beta, RC or stable) and source for dev branches.

**Comment by hkdobrev** [comment]
@stof Thanks for the clarification!

**Comment by Qasmi2** [comment]
complete information about the composer and also  --prefer-dist and --prefer-source  
https://getcomposer.org/doc/03-cli.md#install

**Comment by umandalroald** [comment]
Update "Removing Automation Pieces" Section

Added:

   * `.ci`
   * `bitbucket-pipelines.yml`
   * `build-providers.json`
   * `.gitlab-ci.yml`
