### ISSUE TITLE
Separate info fetching from updating

### ISSUE THREAD

**Issue by chx** [composer/composer#4871]
At least apt-get and pacman (and probably a lot other) package managers have separate phases for downloading information vs acting on that information. This of course results in much better speed.

**Comment by cs278** [comment]
That's not really feasible, it's all down to the volume of metadata and frequency which that metadata changes.

On my Debian Jessie system 64MiB of metadata is required, 62MiB of that is static for about 3 months (between point releases.) Obviously the updates data will grow in time but not significantly.

Packagist doesn't make just one version available it makes *all* versions available, so the volume of metadata is much greater and as a consequence Packagist effectively has 20 times more packages than Debian. The Packagist metadata is updated frequently, roughly 6000 updates were made in January.

**Comment by curry684** [comment]
> At least apt-get and pacman (and probably a lot other) package managers have separate phases for downloading information vs acting on that information.

So does Composer. 

    composer update --dry-run    # Updates metadata but does not execute
    composer update   # Uses cached metadata from previous command and act on it

This makes it equivalent to running `apt-get update && apt-get -y upgrade`. Composer just chooses to do things differently, but as an experienced Debian sysadmin I can tell you that I have aliased that macro on every machine I have root on just to get the behavior that `composer update` does by default.

> This of course results in much better speed.

No it doesn't. Serializing serialized operations has no impact on speed unless other measures are also taken.

You're in general also wildly off in comparing composer to apt-get. One is a dependency manager, the other is a package manager. Whilst it may seem identical in a lot of ways their use cases differ, causing different architectural choices.

>  (Yes, I'd rather prefer not using composer because of its speed issues but my hand is forced now.)

Adding that line to 3 issues in a row is not going to get your issues taken any more seriously, if anything the opposite. Please act at the same professional level you expect the responses to be.

**Comment by Seldaek** [comment]
Nothing to add here, thanks @curry684.
