### ISSUE TITLE
Use a database instead of storing JSON files

### ISSUE THREAD

**Issue by chx** [composer/composer#4872]
Conveniently SQLite now has a JSON extension and it's way more faster querying that than reparsing JSON for everything.

**Comment by staabm** [comment]
Using sqlite would harm the developer experience a lot, as the contents are a lot harder to change/adjust in comparison to simple json files.

Also composer spents the most of its time in other parts, so such a change wouldnt buy us a lot.

**Comment by curry684** [comment]
@staabm your comment is also short-sighted, as the developer experience only depends on the root package's `composer.json` and `composer.lock` files. The parsing/generation impact of those 2 files is minimal in the grand scale of things.

Now type the following command on *nix:

    find ~/.cache/composer/ -name "*.json"

Or visit file://%LOCALAPPDATA%\Composer\repo on Windows. On the average dev machine that's a shitload of JSON files being used all the time during the resolving process.

The real problems are that a) Composer is incredibly hardcoded on all those JSON files and b) SQlite extensions are not enabled by default on any PHP distribution I'm aware of. The first is the consequence of Composer growing far bigger than anyone had probably ever predicted all those years ago when the current codebase was launched, but could be tackled with a lot of work. The second however makes it totally unfeasible except as an obscure configurable setting which would only be used by @chx.

**Comment by chx** [comment]
In this race to the bottom mockingly called PHP renaissance we are all forced to use composer now so if composer used the JSON extension then I guess even the internals people would be forced to listen to their users for once and get that in.

**Comment by curry684** [comment]
> we are all forced to use composer now

You're not. Fork it, make it better, make it work for your situation, and if your changes are really cool - be a cool guy and push it back. Composer is MIT licensed, you don't even need to do the last part.

I can see that you're frustrated about something, and I don't know what, but I do know that taking out your frustrations here on the Composer community is not helping. Be constructive, say what's wrong and why you want to change it. Make a PR if you see how things can be better. But don't just come here and abuse people that are not even getting paid for developing this product you apparently loathe so much. Go pay @Seldaek $100/hr for 3 months and I'm pretty sure he can build you the best Composer you'd ever want.

**Comment by alcohol** [comment]
@curry684 the cache might contain a lot of files, but if you run any Composer command in `-vvv` mode you will see which files it actually reads from, which really isn't a note-worthy amount.

I personally don't think switching to SQLite will make any significant impact. The performance "issues" a lot of users perceive are mostly in the solver (during updates/initial install -- this is simply an incredibly complex process), and in the sequential download jobs.

**Comment by curry684** [comment]
I doubt it as well. The true optimizations can be done in the solver indeed, and in parallellization of the downloads and installs. I was merely pointing out that Composer is juggling a lot more JSON files than the developer ever sees.

**Comment by Seldaek** [comment]
This isn't realistic IMO, and the benefits are anyway hardly proven, so closing for now.
