### ISSUE TITLE
Stream wrappers with autoload / ClassLoader

### ISSUE THREAD

**Issue by sekjun9878** [composer/composer#4876]
Hello,

Currently there is no way to specify a stream wrapper to be used at the autoloader, either in the composer.json or as a Composer plugin. The only way I believe this can be done is by manually patching the ClassLoader.php after receiving the post-autoloader-dump hook, which is messy and isn't ideal.

Is there a possibility for stream wrappers to be specified in composer.json in such a way that this is possible:
```json
{
    "autoload": {
        "Vendor\\Package": "stream://src/"
    }
}
```

**Comment by cs278** [comment]
What's the use case for this? I'm a bit sceptical as allowing this would allow packages to do scary things like this:

```json
{
  "autoload": {
    "files": ["http://example.com/do.evil"]
  }
}
```

**Comment by sekjun9878** [comment]
I think one way to solve that issue would be to have a field like "allowed-wrappers" that is only gathered from the root project / 1 parent up, and if any package / library has an autoload that uses a wrapper that is not in it, Composer would generate an error upon autoloader dumping?

e.g.

```json
{
  "autoload": {
    "psr-4": {
      "Namespace": "service://src/"
    }
  },
  "extra": {
    "allowed-streams": [
      "service"
    ]
  }
}
```

Another approach would be some sort of a plugin API hook, but I'm not sure how to go about that.

The use case is for PHP preprocessors such as https://github.com/marcioAlmada/yay/issues/11, where we need to process the file before the Composer autoloader includes it.

**Comment by staabm** [comment]
Couldnt you just define a "simple" autoloader which then includes your special stream-wrapper etc stuff?

**Comment by curry684** [comment]
> where we need to process the file before the Composer autoloader includes it.

Shouldn't you just do that with a plugin and a [`pre-autoload-dump`](https://getcomposer.org/doc/articles/scripts.md#event-names) event?

**Comment by sekjun9878** [comment]
@curry684 That event is only called when the autoloader is dumped, so in the end it would require overwriting the files themselves.

But anyway, I was able to get around this issue by manually eval'ing the file so that no autoloader modification is required. e.g.
```php
<?php

require_once __DIR__.'/vendor/autoload.php';

preprocessor_example_compile(__FILE__); __HALT_COMPILER();
```
