### ISSUE TITLE
Unable to install composer! 

### ISSUE THREAD

**Issue by AhmedLuLu** [composer/composer#4879]
Hello!
Firstly this is my first post in this world :)

When I try to install the Composer on Windows 7 I get this error : 

> Connection Error [ERR_CONNECTION]: Unable to connect to getcomposer.org
> 
> Request to https://getcomposer.org/installer failed with errors:
> SSL: Handshake timed out. Failed to enable crypto. Failed to open stream: operation failed

so.. I tried again to connect in cmd, but the result is :
> 
> C:\xampp\php>php -r "readfile('https://getcomposer.org/installer');" | php
> 
> Warning: readfile(): SSL operation failed with code 1. OpenSSL Error messages:
> error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify faile
> d in Command line code on line 1
> 
> Warning: readfile(): Failed to enable crypto in Command line code on line 1
> 
> Warning: readfile(https://getcomposer.org/installer): failed to open stream: ope
> ration failed in Command line code on line 1

I really don't know what to do ...

**Comment by flaith-nycd** [comment]
Got the same issue, how did you solve it?
