### ISSUE TITLE
composer self-update error - win 8.1 with XAMPP

### ISSUE THREAD

**Issue by elizabethmeyer** [composer/composer#4888]
When I run the command composer self-update from command line I get the following error:

[Composer\Downloader\TransportException]
The "https://getcomposer.org/version" file could not be downloaded: failed to open stream: a connection attempt failed because the connected party did not properly respond after a period of time or established connection failed because connected host has failed to respond.

When I ping https://getcomposer.org/ from the command line, I get the response:

Ping request could not find host https://getcomposer.org. Please check the name and try again.

Although I am able to open the URL in my browser.

I am also unable to use composer to install or update packages as I get a similar message. (I downloaded my Laravel installation from LaraPack due to the same issues).

**Comment by curry684** [comment]
Ping works on hostname, so try `ping getcomposer.org` without the rest of the URL.

If the URL works in the browser but not from command-line tools your browser is likely configured to access the web via a proxy. You can configure [Composer to do the same](https://getcomposer.org/doc/03-cli.md#http-proxy-or-http-proxy).

**Comment by elizabethmeyer** [comment]
Thanks for the response curry684. I can ping getcomposer.org succesfully as well.

I definitely don't have a proxy setup on my machine, but thanks for the tip.

I've read things on the internet regarding composer and ipv6 and / or SSL certificates. None of which I could make work - I don't know if the problem maybe lies in this direction?

**Comment by curry684** [comment]
It could be, but I think it would give a different error. The message you posted points towards a general network issue on the client side, something like a firewall or throttler, or DNS poisoning.

Does `composer -vvv self-update` show more information? It should show a message like `Checking CA file: <path>`, if so does the file it points to exist, and contain a large number of certificates? It should look pretty much identical to https://curl.haxx.se/ca/cacert.pem

**Comment by elizabethmeyer** [comment]
The response I get is:

`PS C:\Users\Elizabeth> composer -vvv self-update
Downloading https://getcomposer.org/version



  [Composer\Downloader\TransportException]
  The "https://getcomposer.org/version" file could not be downloaded: failed to open stream: A connection attempt fai
  led because the connected party did not properly respond after a period of time or established connection failed be
  cause connected host has failed to respond.



Exception trace:
 () at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Util/RemoteFilesystem.php:297
 Composer\Util\RemoteFilesystem->get() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Util/Remote
Filesystem.php:84
 Composer\Util\RemoteFilesystem->getContents() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Com
mand/SelfUpdateCommand.php:83
 Composer\Command\SelfUpdateCommand->execute() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/c
onsole/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfon
y/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/s
ymfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Co
nsole/Application.php:146
 Composer\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/S
ymfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Cons
ole/Application.php:82
 Composer\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin/composer:43
 require() at C:\ProgramData\ComposerSetup\bin\composer.phar:25


self-update [-r|--rollback] [--clean-backups] [--no-progress] [version]`

**Comment by cs278** [comment]
What output do you get from `composer diagnose`?
Do you have a firewall or internet security product that maybe denying network access to PHP?

**Comment by elizabethmeyer** [comment]
Nope, nothing. No firewall, no proxy, no internet security product. Even Avast is disabled.

When I run `composer diagnose` I get the following output:

Warning: This development build of composer is over 60 days old. It is recommended to update it by running "C:\ProgramDa
ta\ComposerSetup\bin\composer.phar self-update" to get the latest version.
Checking platform settings: FAIL
The xdebug extension is loaded, this can slow down Composer a little.
 Disabling it when using Composer is recommended.
Checking git settings: OK
Checking http connectivity to packagist: FAIL
[Composer\Downloader\TransportException] The "http://packagist.org/packages.json" file could not be downloaded: failed t
o open stream: A connection attempt failed because the connected party did not properly respond after a period of time o
r established connection failed because connected host has failed to respond.

Checking https connectivity to packagist: FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: failed
to open stream: A connection attempt failed because the connected party did not properly respond after a period of time
or established connection failed because connected host has failed to respond.

Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: failed to
 open stream: A connection attempt failed because the connected party did not properly respond after a period of time or
 established connection failed because connected host has failed to respond.

Checking disk free space: OK
Checking composer version:


  [Composer\Downloader\TransportException]
  The "https://getcomposer.org/version" file could not be downloaded: failed to open stream: A connection attempt fai
  led because the connected party did not properly respond after a period of time or established connection failed be
  cause connected host has failed to respond.



diagnose

(Sorry, I'm battling to copy and paste from Windows powershell - I hope this is sufficient?)

**Comment by curry684** [comment]
The first part shows even outgoing http traffic on port 80 is blocked. I am very tempted to say that Windows Firewall has a block on application level. Can you run services.msc and disable the Windows Firewall Service there temporarily, then try again?

It would also be helpful if you could provide the exact version number of the build you're running - as it says it's over 60 days old and as such the line numbers in the call stack are only useful to us if we can look at the same version of the code.

**Comment by elizabethmeyer** [comment]
'composer --version' response:
Composer version 1.0-dev (9859859f1082d94e546aa75746867df127aa0d9e) 2015-08-17 14:57:00

I still get exactly the same error. Even with Windows Firewall Service disabled, `composer self-update` responds with:

  [Composer\Downloader\TransportException]                                     
  The "https://getcomposer.org/version" file could not be downloaded: failed   
  to open stream: A connection attempt failed because the connected party did  
   not properly respond after a period of time or established connection fail  
  ed because connected host has failed to respond.                             
                                                                               
self-update [-r|--rollback] [--clean-backups] [--no-progress] [version]

**Comment by curry684** [comment]
That makes it really fascinating  :)  What is the output of:

    php -r "var_dump(strlen(file_get_contents('http://www.google.com')));"

On a regular command line?

**Comment by elizabethmeyer** [comment]
I'm glad it's fascinating - I'm starting to feel very frustrated. :-)

Ah. This IS interesting. This is what I get:

PS C:\Users\Elizabeth> php -r "readfile('http://www.google.com');"

Warning: readfile(http://www.google.com): failed to open stream: A connection attempt failed because the connected party
 did not properly respond after a period of time or established connection failed because connected host has failed to r
espond.
 in Command line code on line 1

Call Stack:
    0.0001     118240   1. {main}() Command line code:0
    0.0001     118336   2. readfile() Command line code:1

**Comment by curry684** [comment]
That's what I expected, as it proves the problem has nothing to do with Composer  :)  Your `php.exe` is prohibited in some way from initiating any kind of network activity whatsoever. I can't say whether that's malware, another firewall on your computer, or some kind of Norton-like internet security fakeware, but I can assure you it's not a problem on 'our' end here.

I would recommend seeking assistance from a local system administrator or computer expert, as the problem is in your local computer's configuration. I would start by looking through the list of Windows Services one by one and disabling any that may be related, and running HijackThis.

**Comment by staabm** [comment]
Maybe php.exe is not allowed to access the internet by your windows firewall

**Comment by wawneeds** [comment]
Hello @curry684 I'm facing the same problem. however I'm able to get the html content of the index page of google through `php -r "readfile('http://www.google.com');"` which means there's no restriction on php at the firewall level. but running php -r "readfile('https://getcomposer.org/versions');" returns the following error: `Warning: readfile(https://getcomposer.org/versions): failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. in Command line code on line 1
`

I've tried uninstalling composer and reinstalling using the windows installer and it fails with the error:
`The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
`

opening https://getcomposer.org/versions with a navigator returns a json file with composer versions.

Please advise.

**Comment by curry684** [comment]
Try `php -r "readfile('https://google.com');"` (note the `https`) to eliminate SSL level issues first.

**Comment by wawneeds** [comment]
That worked fine also.

After hours of looking around and a bit of luck I came across this: https://getcomposer.org/doc/articles/troubleshooting.md#operation-timed-out-ipv6-issues-

Disabling IPV6 on my windows machine made composer run normal again. Isn't it weird though that for a service to function changes to the OS have to be made ?

**Comment by curry684** [comment]
No, that makes it an ISP or local network issue. `getcomposer.org` properly exports IPv6 addresses and it is reachable on them, apparently your local network couldn't provide routing there, and you now fixed it by forcing your computer to use IPv4 instead.

**Comment by jlcd** [comment]
@4ssil thanks for pointing that out. I'm on a Mac and had the same error. `php -r "readfile('https://google.com');"` was healthy while `php -r "readfile('https://getcomposer.org/versions');"` wasn't.

It took me a few days to find this answer, so for all of those in need of a similar [solution](https://github.com/composer/composer/issues/4888#issuecomment-243923706), I'll leave some keywords here:

**Checking http connectivity to packagist**
**Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info**
**The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: Operation timed out**

**Comment by McScreech** [comment]
@curry684 What does an empty return from either command indicate?
I am assuming I should see the plain text html from the request, correct?

I used both the following variants when nothing was written to console and both returned empty files.
php -r "readfile('http://www.google.com');" > test1.html
php -r "readfile('https://www.google.com');" > test2.html

**Comment by curry684** [comment]
Both commands should output the full HTML of Google's homepage on stdout. Your PHP likely has the stream wrappers disabled and error suppression enabled.

You can check the relevant settings with the `-i` command line variable:
```
# php -i | grep " PHP Stream"
Registered PHP Streams => https, ftps, compress.zlib, php, file, glob, data, http, ftp, phar
# php -i | grep error_re
error_reporting => 22527 => 22527
```

**Comment by cromasystem** [comment]
I added php.exe into Kaspersky Internet Security trusted list and problem solved.

**Comment by davekiss** [comment]
Thanks, running this works for me on MacOS Sierra 10.12.6

`sudo networksetup -setv6off wi-fi`

**Comment by phpguru** [comment]
I'm not sure what changed for me, but on Mac OS X today all of a sudden I have no connectivity on https to packagist.org. I ran `sudo networksetup -setv6off Wi-Fi` and restarted terminal. Here is the output:

```
geoffh@rxmg-macbookpro ~ $ composer diagnose -vvv
Loading config file /Users/geoffh/.composer/config.json
Loading config file /Users/geoffh/.composer/auth.json
Reading /Users/geoffh/.composer/composer.json
Loading config file /Users/geoffh/.composer/config.json
Loading config file /Users/geoffh/.composer/auth.json
Loading config file /Users/geoffh/.composer/composer.json
Loading config file /Users/geoffh/.composer/auth.json
Reading /Users/geoffh/.composer/auth.json
Checked CA file /private/etc/ssl/cert.pem: valid
Executing command (/Users/geoffh/.composer): git branch --no-color --no-abbrev -v
Executing command (/Users/geoffh/.composer): git describe --exact-match --tags
Executing command (/Users/geoffh/.composer): git log --pretty="%H" -n1 HEAD
Executing command (/Users/geoffh/.composer): hg branch
Executing command (/Users/geoffh/.composer): fossil branch list
Executing command (/Users/geoffh/.composer): fossil tag list
Executing command (/Users/geoffh/.composer): svn info --xml
Reading /Users/geoffh/.composer/vendor/composer/installed.json
Loading plugin Studio\Composer\StudioPlugin
Running 1.6.5 (2018-05-04 11:44:59) with PHP 7.2.5 on Darwin / 17.5.0
Checking platform settings: OK
Checking git settings: Executing command (CWD): git config color.ui
OK
Checking http connectivity to packagist: Downloading http://packagist.org/packages.json
OK
Checking https connectivity to packagist: Downloading https://packagist.org/packages.json

The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: Operation timed out
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
Downloading https://packagist.org/packages.json
OK
Checking github.com rate limit: Downloading https://api.github.com/rate_limit
OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: Downloading https://getcomposer.org/versions
OK
Composer version: 1.6.5
PHP version: 7.2.5
PHP binary path: /usr/local/Cellar/php/7.2.5/bin/php
```

**Comment by AlexanderChoudhury** [comment]
![composer diagnose](https://user-images.githubusercontent.com/28726954/45670017-e1cc3d00-bb4b-11e8-873b-75a8b01ff939.png)

i also have this issue with my composer can anyone help me thank you

**Comment by SPL3S** [comment]
Same here, spent a whole day figuring out why composer didn't work, tried HTTP https, then thought something wrong with SSL setup with OpenSSL. After reading this thread just disabled IP6 and it works flawlessly

Centos7 
Apache
