### ISSUE TITLE
Composer diagnose test: FAIL on connectivity with packagist.org

### ISSUE THREAD

**Issue by Varun006** [composer/composer#4890]
Hello,

I am trying to diagnose composer but i am getting this error.

```
Checking http connectivity to packagist: FAIL
[Composer\Downloader\TransportException] The "http://packagist.org/packages.json" file could not be downloaded: failed to open stream: Connection timed out
```

I have also added this code in composer.json as i found this solution on the internet.

```
"repositories": [
        {
             "type": "composer", 
             "url": "https://packagist.org"
        },
        { "packagist": false }
    ]
```
 It is also failing on connectivity with HTTPS request. 

Is there something wrong with my server or its configuration??

Or my composer.json has some errors.??

**Comment by curry684** [comment]
Your issues are similar to https://github.com/composer/composer/issues/4888, can you check the diagnostics suggested there?

**Comment by Masab-M** [comment]
i am facing this issue of 
"[Composer\Downloader\TransportException] Unable to use a proxy: malformed http_proxy url"

**Comment by Masab-M** [comment]
I reset the proxy as well but it didn't work

**Comment by abchois** [comment]
I am also facing the same situation
"[Composer\Downloader\TransportException] Unable to use a proxy: malformed http_proxy url"

It is at home : Windows10 'Localhost' 'D:\Apache24\htdocs\'
Tried to http://127.0.0.1 but it didn't work.

**Comment by blorconsult** [comment]
I have the same problem : also Windows 10.

**Comment by blorconsult** [comment]
I have done the following and it works. 
SETX HTTPS_PROXY ""

SETX HTTPS_PROXY ""

**Comment by murraygunn** [comment]
Where exactly do you add those settings? @blorconsult

**Comment by blorconsult** [comment]
Sorry, but this is a request from December 2020. I'm not in this problem anymore.

Best regards.

Benoit

De : murraygunn ***@***.***>
Envoyé : mercredi 2 novembre 2022 16:10
À : composer/composer ***@***.***>
Cc : blorconsult ***@***.***>; Mention ***@***.***>
Objet : Re: [composer/composer] Composer diagnose test: FAIL on connectivity with packagist.org (#4890)


Where exactly do you add those settings? @blorconsult<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fblorconsult&data=05%7C01%7C%7C40a634e055b54ad0e22a08dabce45607%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638029986126680192%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vFFHyX7znFP8gcAE%2B1JjNWflQK%2F5ZQ5mO8ii%2B5v4ThI%3D&reserved=0>

-
