### ISSUE TITLE
Composer/Source User-Agent

### ISSUE THREAD

**Issue by chosroes** [composer/composer#4893]
Hi,

On the packages.json download (by file_get_contents), the user agent seems to be "Composer/Source" and this is a problem in my case since the server doesn't allow this user-agent and I don't know why and at which level...
My question is: Is it possible to specify another user agent on composer install/update ?

Thanks

**Comment by alcohol** [comment]
This is currently not possible. Is there a particular reason this user agent is not allowed on your server?

**Comment by chosroes** [comment]
@alcohol Hosting provider is responsible. I think for security reasons... But he doesn't want to change this behavior.

**Comment by alcohol** [comment]
Do you mean, as an outgoing connection, it is not allowed? E.g. composer is not able to connect to packagist.org? Can you give us the output of a `composer -vvv update` on your project?

**Comment by Seldaek** [comment]
Then please consider using another hosting provider.. seriously sorry but this is just a waste of time for everyone involved because of some bad actor. Not setting a proper user-agent would be bad practice for us.

**Comment by curry684** [comment]
I agree it's bad on the hosting provider's part, and just breaking standards for fake security. But as an environment variable I think it may even be more used than stuff like `COMPOSER_DISABLE_XDEBUG_WARN` that's also in there. Not saying it should be any kind of priority, but if someone (@chosroes?) were to issue a PR to properly implement `COMPOSER_USER_AGENT` I think it would be fine to merge  :)

**Comment by chosroes** [comment]
To be more specific, I have installed Satis on the server and I use composer on my dev environment with this Satis as composer repository.
But, between my computer and the Satis server, there is a "firewall" server where the problem is.

So, when I update, composer sends those headers: 
"Connection: close"
"Accept-Encoding: gzip"
"User-Agent: Composer/6eb50623e6e00bac4ed893802836e50b62c83434 (Linux; 4.2.0-27-generic; PHP 5.6.11)"

The composer file_get_contents on the Satis packages.json doesn't fail, but retrieve an html:
`"<HTML>
<HEAD><TITLE>Index of /</TITLE></HEAD>
<BODY BGCOLOR="#99cc99" TEXT="#000000" LINK="#2020ff" VLINK="#4040cc">
<H2>Index of /</H2>
<PRE>
mode  links  bytes  last-changed  name
<HR>dr-x   2        4096  Jan 31  2015  <A HREF="/./">.</A>/
dr-x   7        4096  Sep 16 11:26  <A HREF="/../">..</A>/
</PRE></BODY>
</HTML>
"`
So the parse json fail (and this is normal considering the request result).
Apache seems to not accept the user agent (because it works with the one settled in php.ini).

**Comment by alcohol** [comment]
It looks more like your server/virtualhost is not setup properly. You appear to be receiving a directory listing. This has nothing to do with the user-agent (I don't know where you even get the impression from).

**Comment by curry684** [comment]
As there's a firewall/proxy in between it could have to do with anything. It could perfectly well have a rule that says 'if user agent does not appear to be a normal browser redirect to this server with only empty vhosts'. I doubt it, but it's possible. At any rate it's not Composer's problem and a local network issue (and a good reason to switch to a professional hosting provider, if this is their doing and they don't want to fix it they deserve to go out of business asap).

**Comment by alcohol** [comment]
Have you tried to validate if your satis instance is actually reachable? E.g. did you try accessing the generated files using a browser or curl?

**Comment by chosroes** [comment]
@curry684 I figured out the origin of the problem. It's a rule anti ddos:

`if( ( !req.http.user-agent || req.http.user-agent ~ "(?i)PHP|WordPress" ) && !
req.http.referer )
  {
    set req.url = "/";
    unset req.http.Cookie;
    set req.http.X-Cache = "on";
    return(lookup);
  }`

The problem was the word "PHP" in the user agent. (Returned by php_uname('r')).
Remove PHP from this test is not really a good idea in this case.

@alcohol Yes Satis is reachable in every other case.

**Comment by alcohol** [comment]
That looks like a Varnish rule to me. Not Composer related.
