### ISSUE TITLE
Composer looking repo in lowercase

### ISSUE THREAD

**Issue by AstRonin** [composer/composer#4899]
In composer.json I write:
_"bower-asset/jQuery-contextMenu": "*",_ - https://github.com/swisnl/jQuery-contextMenu, last v2.1.0

but `composer update` brings other repo:
_Installing bower-asset/jquery-contextmenu (v0.5.2)_ - https://github.com/nitinuttarwar/jquery-contextmenu

**Comment by stof** [comment]
composer package names are case insensitive. If bower asset names are not, this means that the bower plugin for composer needs to handle this. But this should be reported to this plugin, not to composer.

**Comment by AstRonin** [comment]
ok, left issue to composer-asset-plugin
https://github.com/francoispluchino/composer-asset-plugin/issues/188

**Comment by francoispluchino** [comment]
@stof I cannot manage this problem in the plugin, because Composer automatically converts any package names. It would necessary that the Solver of Composer does not force the search of package names in lowercase. (given that it is already done in the constructor of the Package class).
