### ISSUE TITLE
 Missing argument 3 for Composer\Downloader\FileDownloader::clearCache()

### ISSUE THREAD

**Issue by vstepanyuk** [composer/composer#4901]
Missing argument 3 for Composer\Downloader\FileDownloader::clearCache(), called in composer/src/Composer/Downloader/ArchiveDownloader.php on line 46 and defined

**Comment by xabbuh** [comment]
should be fixed by 8808638ea993633a6f9e5af240bfcf9714b9201a

**Comment by Seldaek** [comment]
Yes indeed please run self-update again
