### ISSUE TITLE
install fails due to certificate CN mismatch

### ISSUE THREAD

**Issue by Arunass** [composer/composer#4902]
I'm trying to install composer on a hosted system and find some surprising challenges.  The biggest appears that the certificate name appears not to match:
```
$ curl -sS https://getcomposer.org/installer | php
curl: (51) SSL: certificate subject name 'packagist.org' does not match target host name 'getcomposer.org'
```
I can overcome this by supplying the -k flag to curl, but this just results in php complaining about the same thing.
```

Downloading...
Download failed: file_get_contents(): Peer certificate CN=`packagist.org' did not match expected CN=`getcomposer.org'
file_get_contents(): Failed to enable crypto
```

**Comment by curry684** [comment]
The error is completely valid, the question is why the hell your system is trying to use the Packagist certificate to validate GetComposer.org, as they both have have unique certificates with own Subject Alternate Name settings. They're not even on the same IP, so it's not an [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication)-conflict either.

Can you check which IP getcomposer.org resolves to (`dig getcomposer.org` or just ping it), the first line of `curl -V` (capital V) and the output of `openssl version`?

**Comment by Arunass** [comment]
It's indeed very odd as the names resolve to different IP addresses.

The system is centOS 5.  Open SSL .9.8b, which doesn't support newer TLS.

```
$  curl -sS https://getcomposer.org/installer
curl: (51) SSL: certificate subject name 'packagist.org' does not match target host name 'getcomposer.org'
[portionality@web70 ~]$ dig getcomposer.org

; <<>> DiG 9.3.6-P1-RedHat-9.3.6-25.P1.el5_11.6 <<>> getcomposer.org
;; global options:  printcmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 841
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;getcomposer.org.		IN	A

;; ANSWER SECTION:
getcomposer.org.	86385	IN	A	87.98.253.108

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Feb 12 17:46:57 2016
;; MSG SIZE  rcvd: 49

$ dig packagist.org

; <<>> DiG 9.3.6-P1-RedHat-9.3.6-25.P1.el5_11.6 <<>> packagist.org
;; global options:  printcmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22180
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;packagist.org.			IN	A

;; ANSWER SECTION:
packagist.org.		43200	IN	A	87.98.253.214

;; Query time: 150 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Feb 12 17:47:05 2016
;; MSG SIZE  rcvd: 47

$ curl -V
curl 7.15.5 (i386-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5
Protocols: tftp ftp telnet dict ldap http file https ftps 
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz 

```

**Comment by Seldaek** [comment]
Can you try using the new installer instructions on https://getcomposer.org/download/ ? It doesn't use curl anymore so might be more widely compatible with such old platforms as CentOS5

**Comment by Arunass** [comment]
Well, this seems nicer until the second line tries to match the hash and it fails with 'installer corrupt'.

So running the first line again:

`php56 -r "readfile('https://getcomposer.org/installer');" > composer-setup.php`

and then looking at the output:
```
$ cat composer-setup.php 

Warning: readfile(): Peer certificate CN=`packagist.org' did not match expected CN=`getcomposer.org' in Command line code on line 1

Warning: readfile(): Failed to enable crypto in Command line code on line 1

Warning: readfile(https://getcomposer.org/installer): failed to open stream: operation failed in Command line code on line 1
```
It appears to have the same problem.  If it's a result of openSSL issues, then it's not surprising that PHP vs curl would have the same results, phpinfo() reports:

```
openssl

OpenSSL support => enabled
OpenSSL Version => OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008

```
I wonder whether since it's using an older version of openssl that doesn't support the latest encryption schemes that it's getting a different certificate?  Is it possible that there's an older certificate lingering in the server configuration?  From my desktop Mac it works as expecte

**Comment by Arunass** [comment]
I just can't fathom that openSSL, or my web host would be making up stuff about the certificate, like adding a completely different domain name....

**Comment by curry684** [comment]
It's not really a 'completely different' domain name, they're quite obviously related, so it's not unlikely that some cached stuff is conflicting.

CentOS 5 is, as Seldaek already mentioned, extremely old. Your build of OpenSSL is nearly 8 years old, making it about as secure as plain HTTP. CentOS 5 doesn't even ship with PHP 5.3 officially, the required minimum for Composer.

All in all - you may want to consider seeking a new host, instead of installing a new site on this one.

**Comment by AshleyPinner** [comment]
It should be noted, like it or not, that CentOS 5 is *still supported* by CentOS until March 31st, 2017. It thus seems reasonable that Composer will need to at least be installable and runnable on it.

The PHP version isn't an issue, looking at their call method it looks like they're using PHP 5.6 from an external repo.

The OpenSSL versions is manually patched by CentOS to have the latest 0.9.8 fixes in it. It also supports `TLS_DHE_RSA_WITH_AES_256_CBC_SHA` at TLS 1.0, which getcomposer.org lets it use, and this is a modern cipher, so it *should* support connections to getcomposer.org.

@Arunass I would suggest to run something like `openssl s_client -connect getcomposer.org:443 -showcerts -bugs -no_ssl3` and see what it thinks the cert chain is.

**Comment by cs278** [comment]
Hmm, could be hosts file as dig just queries DNS. What's the output of `curl -vsS https://getcomposer.org/installer >/dev/null`?

Works for me on a RHEL5 server which should be near identical:

```
$ curl -V
curl 7.15.5 (x86_64-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5
Protocols: tftp ftp telnet dict ldap http file https ftps 
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz 

$ openssl version
OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008

$ curl -vsS https://getcomposer.org/installer >/dev/null
* About to connect() to getcomposer.org port 443
*   Trying 87.98.253.108... connected
* Connected to getcomposer.org (87.98.253.108) port 443
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSLv2, Client hello (1):
SSLv3, TLS handshake, Server hello (2):
SSLv3, TLS handshake, CERT (11):
SSLv3, TLS handshake, Server key exchange (12):
SSLv3, TLS handshake, Server finished (14):
SSLv3, TLS handshake, Client key exchange (16):
SSLv3, TLS change cipher, Client hello (1):
SSLv3, TLS handshake, Finished (20):
SSLv3, TLS change cipher, Client hello (1):
SSLv3, TLS handshake, Finished (20):
SSL connection using DHE-RSA-AES128-SHA
* Server certificate:
* 	 subject: /C=CH/ST=Z\xC3\xBCrich/L=Z\xC3\xBCrich/O=Nelmio AG/CN=getcomposer.org
* 	 start date: 2014-06-30 00:00:00 GMT
* 	 expire date: 2017-08-01 12:00:00 GMT
* 	 subjectAltName: getcomposer.org matched
* 	 issuer: /C=US/O=DigiCert Inc/CN=DigiCert SHA2 Secure Server CA
* SSL certificate verify ok.
snip
```

**Comment by Arunass** [comment]
@AshleyPinner , @cs278 
 - It seems pretty convinced that all is about packagist.org.  But the important difference may be in the output of the command that curl -vsS provided.  Namely my host is apparently preferring to use IPV6.
Which may be the real difference, and then it's unhappy about the same name mismatch:

```
curl -vsS https://getcomposer.org/installer > /dev/null
* About to connect() to getcomposer.org port 443
*   Trying 2001:41d0:a:7b19::1... connected
* Connected to getcomposer.org (2001:41d0:a:7b19::1) port 443
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
...
* Server certificate:
* 	 subject: /C=CH/ST=Z\xC3\xBCrich/L=Z\xC3\xBCrich/O=Nelmio AG/CN=packagist.org
* 	 start date: 2014-06-30 00:00:00 GMT
* 	 expire date: 2017-08-01 12:00:00 GMT
* SSL: certificate subject name 'packagist.org' does not match target host name 'getcomposer.org'

```

**Comment by AshleyPinner** [comment]
Try the curl command again, but this time with `--ipv4` added to the argument list.

**Comment by cs278** [comment]
@Arunass so getcomposer.org and packagist.org use the same IPv6 address requiring SNI support which you don't have, hence the error.

@Seldaek any reason IPv6 uses the same address?

**Comment by Seldaek** [comment]
Maybe I assumed anyone with v6 support would have a modern enough system to deal with SNI. Or maybe there was something else. I remember vaguely having troubles making ubuntu accept new v6 IPs. I guess I can give it another shot.

**Comment by Seldaek** [comment]
OK @Arunass can you try again with ipv6? It should now direct packagist to 2001:41d0:a:7b19::3 and getcomposer to 2001:41d0:a:7b19::2, hopefully no more SNI then.

**Comment by Arunass** [comment]
@seldesk, yes, thanks, that wowrks!
