### ISSUE TITLE
Composer should ignore empty path repositories 

### ISSUE THREAD

**Issue by cinamo** [composer/composer#4903]
Use case: when using Composer in local development, it's great to have a directory of local packages (so devs can work on them simultaneously), which can then be defined in `composer.json` as a Path repository. Great! (It can't be defined in the global `config.json`, because it wouldn't take priority over other repositories defined in `composer.json`.)

However, let's assume that on the production server, we don't want this directory to exist, because we're pulling the packages from the next available, lower-priority repository.

This almost works ... except that Composer gives an error when the path repository is empty (or doesn't exist):

> [RuntimeException]
>  No `composer.json` file found in any path repository in "../empty-path/*/*"

The solution could be to add an option to the Path repository to explicitly ignore errors when no `composer.json` could be found. What do you guys think?

**Comment by curry684** [comment]
I ran into it as well last week, and also thought - why the hell is that check there, an empty repository should be completely valid and perfectly acceptable.

**Comment by curry684** [comment]
I don't see the reason for adding another config flag for this, so I just removed the check and exception. Composer repositories also don't throw an exception when empty, why should Path repositories have different handling?

**Comment by cinamo** [comment]
The only think I can think of, is that there might be two different reasons why there would be an error: either the path doesn't exist OR there's nothing in there. In the first case, the error that it gives now is quite useful - in the second case, not so much. Therefore I thought the config flag would be the better way to go.

**Comment by Seldaek** [comment]
Fixed by #4904
