### ISSUE TITLE
adding repositories to global composer config is ignored by project; project's local config is used

### ISSUE THREAD

**Issue by pgnd** [composer/composer#4909]
referred/redirected by:
https://github.com/drupal-composer/drupal-packagist/issues/49#issuecomment-182369660

If I add packagist repo to global config

    composer global config repositories.drupal composer https://packagist.drupal-composer.org
    cat ~/.composer/composer.json
        {
            "repositories": {
                "drupal": {
                    "type": "composer",
                    "url": "https://packagist.drupal-composer.org"
                }
            }
        }

any subsequent package require fails

    cd <drupalroot>
    composer require  drupal/big_pipe:8.1.0-beta3

        ./composer.json has been updated
        Loading composer repositories with package information
        Updating dependencies (including require-dev)
        Your requirements could not be resolved to an installable set of packages.

          Problem 1
            - The requested package drupal/big_pipe could not be found in any version, there may be a typo in the package name.

        Potential causes:
         - A typo in the package name
         - The package is not available in a stable-enough version according to your minimum-stability setting
           see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

        Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

        Installation failed, reverting ./composer.json to its original content.

But if I add the repo locally

    composer config repositories.drupal composer https://packagist.drupal-composer.org
    cat ./composer.json
        ...
          "repositories": {
            "drupal": {
              "type": "composer",
              "url": "https://packagist.drupal-composer.org"
            }
          }
        }

all packages install with no issue

    composer require  drupal/big_pipe:8.1.0-beta3
        ./composer.json has been updated
        Loading composer repositories with package information
        Updating dependencies (including require-dev)
          - Installing drupal/big_pipe (8.1.0-beta3)
            Loading from cache

        > Drupal\Core\Composer\Composer::vendorTestCodeCleanup
        Writing lock file
        Generating autoload files
        > Drupal\Core\Composer\Composer::preAutoloadDump
        > Drupal\Core\Composer\Composer::ensureHtaccess

Iiuc, global configs should be respected.

Is there additional config needed here? or is the use of global config broken?

**Comment by cs278** [comment]
You want to use `composer config --global`, using `composer global config` only affects the config for other [compser global commands](https://getcomposer.org/doc/03-cli.md#global). I can appreciate your confusion though!

**Comment by pgnd** [comment]
@cs278 

That does the trick.  using --global, the repository data's added to my $COMPOSER_HOME/config.json, not to my PROJECT_ROOT/composer.json.

Subsequent 'composer require' installs in my PROJECT_ROOT, *do* find/use that now-global repository.

So ... there's BOTH

    composer --global config ...
    composer global config ...

in different contexts' usage?  Confusion is right!  Back to find the docs on both.

Thanks.

**Comment by alcohol** [comment]
`composer global` basically runs the composer command as if you were in your composer home directory (which is usually `~/.composer` on most *nix systems). So it will switch context (cwd), but still run a plain command (`composer config`).

`composer config --global` on the other hand, specifically requests that you alter the global configuration (which unfortunately, is also located in your composer home directory).

I do believe `composer global` has a very misleading meaning considering how most people interpret it. I am not certain that any documentation changes will remedy this.
