### ISSUE TITLE
Using "#" in required branch name does not work

### ISSUE THREAD

**Issue by HeahDude** [composer/composer#4915]
Same error as #935 when try to use a branch with "#" in its name.

Working on a patch on my symfony branch of 2.7 :

```json
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/HeahDude/symfony"
    }
],
"require": {
    "symfony/symfony": "dev-fix-#17292 as 2.7-dev",
},
```

Throws the error :
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package symfony/symfony dev-fix-#17292 as 2.7-dev could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

Creating another branch with the name "test-fix-17292" and code below works fine :
```json
"require": {
    "symfony/symfony": "dev-test-fix-17292 as 2.7-dev",
},
```

**Comment by Seldaek** [comment]
I think we'll have to close this one as a won't fix. It's an unfortunate edge case but using # in branch names is really not common and I don't really see how we can work around this when parsing the dependencies as at that point we have no clue about the git repo linked to that package we can't know if you try to require a specific commit hash or are using a branch name with a hash in it.

**Comment by HeahDude** [comment]
@Seldaek understood, thank you.
