### ISSUE TITLE
Composer scripts are subject to the process-timeout config (default 300s)

### ISSUE THREAD

**Issue by grifx** [composer/composer#4918]
Composer scripts are subject to the process-timeout config.

While it can be useful to have a process timeout on `composer install`. I think it shouldn't be applied to the custom scripts since they can be long-running scripts.

Error:
`COMPOSER_PROCESS_TIMEOUT=1 composer run api-server -vvv`
```
[Symfony\Component\Process\Exception\ProcessTimedOutException]                                           
  The process "#" exceeded the timeout of 1 seconds.
```

**Comment by staabm** [comment]
why do you pass the timeout to the process when you expect it will run very a long time?

**Comment by grifx** [comment]
By default it's set to 300sec. I didn't want you to wait that long.

My main point is that unlike npm scripts, composer scripts are not convenient for long running scripts since they have a default timeout.

I can see two easy solutions to alleviate this problem:
- Having dev env variables with long timeout.
- Change process-timout in the config.

I believe the process-timeout config shouldn't be applied when running custom scripts.
Maybe we could split this into two configs:`install-timeout` and `script-timeout`.

**Comment by curry684** [comment]
In general scripts shouldn't hang either, and remain protected unless specifically overridden for a single script.

Isn't `composer run api-server --ignore-timeout` what you are really looking for?

**Comment by curry684** [comment]
Referenced PR will allow you to do `composer run api-server --timeout=0` when merged.

**Comment by grifx** [comment]
Thanks

**Comment by mirao** [comment]
I needed int in `composer exec` and had to used this: `COMPOSER_PROCESS_TIMEOUT=0 composer exec -v ...`
`composer exec` doesn't seem to have `--timeout` option
