### ISSUE TITLE
Remove options on RIGHT CLICK

### ISSUE THREAD

**Issue by SYNTAG** [composer/composer#4923]
Hello, I was wondering how I can remove the options on the right click menu?
http://i.imgur.com/zPwAlnu.png

**Comment by curry684** [comment]
Uninstall from Windows then reinstall with the option disabled.

**Comment by SYNTAG** [comment]
Is that the only way of accomplishing this?

**Comment by curry684** [comment]
You could hack the registry yourself, but this is kind of standard procedure  :)  You installed the shell extensions, they have to be uninstalled now to be removed. The installer does not have a 'change install' option, so reinstalling is actually the easiest, should be done in a few minutes.

**Comment by SYNTAG** [comment]
Haha, I definitely don't want to mess around with the registry :) I'll do the reinstall then. Cheers! :coffee:
