### ISSUE TITLE
composer-setup fails to check for required mbstring

### ISSUE THREAD

**Issue by stuartm** [composer/composer#4929]
Installed composer via composer-setup but when composer is run it errors because mbstring isn't installed. Composer-setup checks for other required dependencies but not for mbstring.

**Comment by curry684** [comment]
It shouldn't have to, as it includes `symfony/console` which itself includes [`symfony/polyfill-mbstring`](https://packagist.org/packages/symfony/polyfill-mbstring), which should make it obsolete. What errors are you getting exactly?

**Comment by stuartm** [comment]
```
$ composer.phar status

PHP Fatal error:  Call to undefined function Symfony\Polyfill\Mbstring\iconv() in phar:///{install_path}/composer.phar/vendor/symfony/polyfill-mbstring/Mbstring.php on line 513

Fatal error: Call to undefined function Symfony\Polyfill\Mbstring\iconv() in phar:///{install_path}/composer.phar/vendor/symfony/polyfill-mbstring/Mbstring.php on line 513
```

**Comment by alcohol** [comment]
It shouldn't look for `iconv()` in `Mbstring`. This is peculiar.

**Comment by alcohol** [comment]
It looks more to me like `iconv()` is not available on your system. But there is a polyfill for that too.

**Comment by stuartm** [comment]
I agree, on a second look it does appear that it's iconv which it's failing to find. I just installed mbstring and moved on without giving it much thought.

**Comment by curry684** [comment]
That seems an issue on Symfony's end, as [`symfony/polyfill-iconv`](https://packagist.org/packages/symfony/polyfill-iconv/dependents) isn't referenced at all by any Symfony project. It would make sense for `polyfill-mbstring` to use it.

**Comment by rquadling** [comment]
According to the comment on https://github.com/symfony/polyfill/blob/master/README.md#usage, maybe composer should be requiring ``symfony/polyfill-iconv``.

**Comment by barryvdh** [comment]
They explicitly removed the iconv-polyfill, because `iconv` is available by default. See https://github.com/symfony/symfony/issues/16778 and  https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md#all-components

**Comment by curry684** [comment]
Hmm in that case Composer should either load the polyfill itself, or check for it in the installer indeed, as it can't recursively enforce `ext-iconv` on itself like Symfony. Ping @Seldaek

**Comment by stof** [comment]
We also removed it because the iconv polyfill is huge, so installing it for anyone which already has iconv would be a bad idea. People who removed iconv from their own PHP build can still require the polyfill themselves.

But given that composer does not include the iconv polyfill, it should probably add a check for the system having either ext-iconv or ext-mbstring available.

**Comment by rquadling** [comment]
Is it feasible to have composer support the nature of polyfills for missing extensions? Select or recommend a best of breed alternative to the extension? ext-mbstring => symfony/polyfill-mbstring sort of idea. ... Though, really, would it be worth the effort? How many people work in environments that are missing standard extensions?

**Comment by alcohol** [comment]
It can already do this to some extend by letting packages specify extensions as part of their requirements, and having suggestions outputted to the console. It still requires user action from that point on though. #3897 is also interesting in regards to this topic, but I am not sure if any progress is still being made on that, or if has been abandoned.

**Comment by matt-wallis** [comment]
I have hit this bug while installing OntoWiki  - https://github.com/AKSW/OntoWiki. OntoWiki's Makefile issues the following commands:

    $ curl -o composer.phar "https://getcomposer.org/composer.phar"
    $ php composer.phar self-update
    
    Fatal error: Uncaught Error: Call to undefined function Symfony\Polyfill\Mbstring\iconv() in phar:///Library/Server/Web/Data/Sites/Default/OntoWiki/composer.phar/vendor/symfony/polyfill-mbstring/Mbstring.php:513

Now, I see above that this bug has been fixed and closed by @Seldaek on Feb 17, but am I right in thinking that the fix has not made it as far as https://getcomposer.org/composer.phar ? 

Is there a workaround I can use? (I know nothing of PHP development - I'm just trying to use OntoWiki!).

**Comment by alcohol** [comment]
@matt-wallis it seems your system does not provide the `iconv` extensions by default, unlike the majority. Enable it through your `php.ini`.

**Comment by matt-wallis** [comment]
Thanks @alcohol. I should have said that my platform is Mac OS/X 10.10. I found the php.ini file, but couldn't easily find out (after brief web search) how to enable iconv. So, I guessed another solution, based on your suggestion, and recorded it below in case it helps anyone else.

I am using [PHP7.0 from macports] (https://www.macports.org/ports.php?by=library&substr=php70). The solution was to install two further ports:

    $ port install php70-iconv    
    $ port install php70-openssl

Now the `php composer.phar self-update` succeeds :-)

As I said before, I'm not a PHP developer. The management of dependencies seems to require manual intervention. Thanks again for pointing me in the right direction.

**Comment by diskerror** [comment]
For PHP 5.6 install
```
sudo port install php56-iconv
sudo port install php56-openssl
sudo port install php56-mbstring
```

**Comment by CoolGoose** [comment]
For windows, you need to install http://gnuwin32.sourceforge.net/packages/libiconv.htm if you've installed composer using the installer, and the php binaries from php.net

**Comment by napestershine** [comment]
What about centos 6.8 ?

**Comment by iman2420** [comment]
`yum install ea-php56-php-iconv
`
