### ISSUE TITLE
Validate only platform requirements

### ISSUE THREAD

**Issue by mathop** [composer/composer#4931]
I'm trying to setup a CI server and I don't want to install or update anything inside the server. I just want to check if all platform requirements specified in the `composer.json` are satisfied by the server, if not, return an exit code in order to stop the build. Is there a way to just validate the platform requirements?

I thought that the `composer validate -A` would perform that, but it doens't seem validating the platform requirements.

**Comment by curry684** [comment]
`validate` just checks the syntax of the definition files, and `-A` recursively checks it for the dependencies.

I'm not sure I understand your use case right though. If you just perform `composer install` it will fail right away on the missing platform requirements, so why doesn't that work for you?

**Comment by alcohol** [comment]
`validate` does not check requirements. It merely checks if your composer.json (and those of your dependencies when using `-A`) conforms to the schema we have defined in `res/composer-schema.json` and some other validation rules.

You could try running a `composer install --dry-run` and checking the exit-code of that process. However, that will not specifically tell you why it failed, when it fails.

**Comment by curry684** [comment]
Actually this is a good scenario to add to #4917 - running `composer why-not` **without** package could check the *root* package for reasons why it will not be installed. That will effectively do exactly what @mathop is requesting. He will have to script the exit code around it though, as that command will technically not 'fail'.

**Comment by mathop** [comment]
Totally forgot about the `--dry-run`, I think wold be good to have a specific command for this purpose in composer but, for now, that works pretty well. Thanks very much @alcohol @curry684

**Comment by curry684** [comment]
I've looked into implementing this in the `why-not` command but essentially that would down to internally aliasing it to `install --dry-run`, except that the installer is hardcoded at that point to also go verbose and output all other pending actions. That makes the amount of changes required not worth the result right now in my opinion.

@alcohol I recommend closing this, or moving to the 'Later' milestone.
