### ISSUE TITLE
Composer Cache Injection vulnerability on 1.0.0-alpha11 ???

### ISSUE THREAD

**Issue by bourdeau** [composer/composer#4932]
Hi all,

Versioneye reported me this security issue: https://www.versioneye.com/php/composer:composer/1.0.0-alpha11

I use dev-master but versioneye suggest  dev-newrepo which doesn't seem to exist... (can't find it on Packagelist or Github)

Is true or is it a Versioneye bug?

Thanks for your help

**Comment by curry684** [comment]
http://flyingmana.de/blog_en/2016/02/14/composer_cache_injection_vulnerability_cve_2015_8371.htm:
> The Vulnerability was fixed on 10.02.2016 in the source of composer.

`dev-master` is therefore not affected.

**Comment by bourdeau** [comment]
Yeah I've seen the fix, what I don't understand is the dev-newrepo thing (https://www.versioneye.com/php/composer:composer/dev-newrepo) that is suggested in my repo (https://www.versioneye.com/user/projects/56ae02f37e03c700377e0056).

**Comment by staabm** [comment]
@bourdeau I guess this was the branch the fix was developed in

**Comment by bourdeau** [comment]
@staabm Ja wahrscheinlich

Anyway, it's doesn't seem to be a composer issue, so I guess I can close this ticket.

Have a nice day all and TGIF ;)

**Comment by reiz** [comment]
@bourdeau I just removed the version `dev-newrepo` from VersionEye. Currently VersionEye is only reading the Versions from Packagist/GitHub, but removed branches/tags are currently not removed automatically from VersionEye. That's on my ToDo list ;) /cc @staabm @curry684
