### ISSUE TITLE
Composer fails to contact rate limit endpoint on Github Enterprise

### ISSUE THREAD

**Issue by mirfilip** [composer/composer#4934]
# Environment
- Running the newest composer available:
```
$ composer self-update
You are already using composer version 9e623f50e7c883a1108352dd61c3d77a65e41130.
```
- I have a project with a `composer.json` like:
```
(...)
"repositories": [
    {
      "type": "vcs",
      "url": "https://my.github.enterprise.org/vendor/package"
    }
  ],
"require": {
    "vendor/package": "*",
},
"config": {
    "preferred-install": "dist",
    "github-domains": [
      "my.github.enterprise.org"
    ]
  }
```
The config is made up but reflects the situation. 
- I have a working Github Enterprise instance at https://my.github.enterprise.org. I can access both its API and the project site https://my.github.enterprise.org/vendor/package.

- I have no `composer.lock` to simplify the scenario.
- My `~/.composer/auth.json` looks like:
```
{
    "github-oauth": {
        "github.com": "XXXXX"
    }
}
```
with the permissions: `-rw-------  1 me  staff   119B Feb 19 15:58 /Users/me/.composer/auth.json`

# The problem
When I do `composer install` I am hitting GHE rate limit and I'm asked to add a token:
```
Loading composer repositories with package information

Could not fetch https://my.github.enterprise.org/api/v3/repos/vendor/package, please create a GitHub OAuth token to go over the API rate limit
Head to https://my.github.enterprise.org/settings/tokens/new?scopes=repo&description=Composer+on+me+2016-02-19+1618
to retrieve a token. It will be stored in "/Users/me/.composer/auth.json" for future use by Composer.
Token (hidden):
```
I already have a token generated. When I paste it and hit enter, it asks me again for it, as if the token is wrong. After second try it crashes out with:
```
[Composer\Downloader\TransportException]
  The "https://my.github.enterprise.org/api/v3/rate_limit" file could not be downloaded (HTTP/1.1 404 Not Found)
```

I am sure the token is valid though. I know that because when I manually edit my `auth.json` and make it look like:
```
{
    "github-oauth": {
        "github.com": "XXXXX",
        "my.github.enterprise.org": "MyValidTokenHere"

    }
}
```
and then do `composer install`, it works fine then. I'm also able to manually "ping" the GHE endpoints, no 404s.

**Comment by curry684** [comment]
Is the `auth.json` file modified/created at all when you enter the token during the process?

**Comment by mirfilip** [comment]
No, it isn't. Neither content or file modification date are changed.

**Comment by alcohol** [comment]
I believe the github domains configuration is only used to check if the Github driver can be used. To associated your token with your enterprise domain, you need to add it for said domain (your auth only shows it for github.com).

Unless I am mistaken, but it shouldn't take you more than a minute to determine if that is the case :-)

**Comment by mirfilip** [comment]
@alcohol See my previous answer :).

**Comment by alcohol** [comment]
Hrm weird. The error implies that the token you specified was not correct. Are you sure your clipboard content was clean (e.g. no erroneous newline or anything)?

What if you run this from the command line?

```
curl --header 'Authorization: token <TOKEN>' https://my.github.enterprise.org/api/v3/rate_limit

// or

curl --header 'Authorization: token <TOKEN>' https://my.github.enterprise.org/rate_limit
```

**Comment by mirfilip** [comment]
@alcohol More info:
```
$ curl --header 'Authorization: token <TOKEN>' https://my.github.enterprise.org/api/v3/rate_limit -I | grep 'HTTP/'
HTTP/1.1 404 Not Found
$ curl --header 'Authorization: token <TOKEN>' https://my.github.enterprise.org/api/v3/rate_limit
{
  "message": "Rate limiting is not enabled.",
  "documentation_url": "https://developer.github.com/enterprise/2.3/v3"
}
```

I didn't notice that before. Going through the [docs](https://developer.github.com/enterprise/2.3/v3/#rate-limiting) I didn't notice anything about possibility of rate limiting to be turned off.

That fact aside, it's still weird that I hit the rate limit if it's disabled. Similarly, weird that adding the token to `auth.json` works.

**Comment by alcohol** [comment]
Well that is definitely peculiar.

In your OP you mentioned that when you hit the rate limit, it asks for a token. Do you immediately hit the rate limit, or does it happen after X packages have been processed already?

**Comment by mirfilip** [comment]
I hit the rate limit as soon as composer reaches the point to download a package from my GHE.

**Comment by alcohol** [comment]
That might actually imply that it receives some sort of `40x` error, which gets wrongly interpreted as a rate limit error. I will have to further investigate this. Unfortunately that might prove somewhat difficult since I do not have access to a GHE environment.

**Comment by stof** [comment]
@alcohol you might ask github for a developer license of GHE through their developer program: https://developer.github.com/program/ (it requires having a paid github account though)

**Comment by alcohol** [comment]
I don't have a paid account so that is a no-go.

**Comment by mirfilip** [comment]
@alcohol @stof I will track the situation some more. I want to check if I really get some kind of rate limit, or is this some missing feature/bug. Stay tuned.

**Comment by alcohol** [comment]
I'm pretty confident it is in fact not a rate limit error, but Composer merely interprets it as such.

**Comment by mirfilip** [comment]
I'm currently debugging the issue. I have some new info:
1. Same `composer.json` as before. When I add `"no-api": true`, it tries to fetch `https://my.github.enterprise.org/api/v3/repos/vendor/package/zipball/<<hash>>` and it asks for token. After putting the token in, I get
```
Failed to download vendor/package from dist: The "https://my.github.enterprise.org/api/v3/rate_limit" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
```
**and downloading from source succeeds**
2. Even though I have given the token to composer and it promised to save it to `auth.json`, it didn't happen. Even though the above process was successful.
3. I noticed I didn't mention that before but `vendor/package` is a **private repository** so some kind of token is needed regardless rate limit. Does that change the picture?

I'm progressing with debugging but would appreciate the info - is any of above the expected behaviour @alcohol ?

**Comment by mirfilip** [comment]
Ok. It looks to me like an unhandled case:
1. `\Composer\Util\RemoteFilesystem::callbackGet` reaches `STREAM_NOTIFY_AUTH_RESULT` case with `$messageCode = 403` and `retryAuthFailure` set to true.
2. It calls `\Composer\Util\RemoteFilesystem::promptAuthAndRetry` which calls `\Composer\Util\GitHub::authorizeOAuthInteractively`. It prompts for token. Token is properly received. It tries to call `rate_limit` endpoint [this catch block](https://github.com/composer/composer/blob/49d7d65933c78e163354c2c580883926f1c8daee/src/Composer/Util/GitHub.php#L110).
3. From now on it's treated as a bad token (and thus retries).

It all boils down to a fact that the package is private and needs auth. Rate limit itself is not enabled and never reached.

**Comment by alcohol** [comment]
> 3. I noticed I didn't mention that before but vendor/package is a private repository so some kind of token is needed regardless rate limit. Does that change the picture?

Correct, private repos need a form of authentication.

**Comment by alcohol** [comment]
Sounds like you discovered a bug. The use-case is a bit exotic because we normally always have to deal with `rate_limit`. Until now I did not even know this could be turned off (which makes sense though for a GHE install I guess). Documentation is not very clear about that. E.g. it does not mention that this endpoint will return a `404` when it is turned off.

**Comment by alcohol** [comment]
Thanks for the debugging work @mirfilip. I will look into resolving this as soon as I have some spare time again. In the meanwhile, if you think you have a solution yourself, please feel free to submit a pull request :-)

**Comment by alcohol** [comment]
From a very quick look though, it seems to me that the `catch` block you linked simply needs another conditional that prevents the exception from being re-thrown; e.g. if the status is a 404 and the origin != api.github.com. It will then proceed to write the token into the auth.json. However, we haven't really verified at that point if it is actually valid (which is what the rate_limit endpoint is used for). So not sure how elegant this solution is :-/

**Comment by alcohol** [comment]
Actually, can you give me the results of:

```
curl --header 'Authorization: token <YOURTOKEN>' \
    https://my.github.enterprise.org/api/v3
```

and

```
curl --header 'Authorization: token invalidtoken' \
    https://my.github.enterprise.org
```

**Comment by mirfilip** [comment]
> However, we haven't really verified at that point if it is actually valid (which is what the rate_limit endpoint is used for). So not sure how elegant this solution is :-/
@alcohol :
I don't get the full picture of the flow yet but `\Composer\Repository\Vcs\GitHubDriver::fetchRootIdentifier` already gathers the info if the package is private. If it is, you surely need to authenticate somehow. After gathering the auth details (let it be from git config, auth.json or interactive prompt), you can set the authentication straight away. 

List of endpoints:
```
$ curl --header 'Authorization: token <YOURTOKEN>' "https://my.github.enterprise.org/api/v3/"
{
  "current_user_url": "https://my.github.enterprise.org/api/v3/user",
  "current_user_authorizations_html_url": "https://my.github.enterprise.org/settings/connections/applications{/client_id}",
  "authorizations_url": "https://my.github.enterprise.org/api/v3/authorizations",
  "code_search_url": "https://my.github.enterprise.org/api/v3/search/code?q={query}{&page,per_page,sort,order}",
  "emails_url": "https://my.github.enterprise.org/api/v3/user/emails",
  "emojis_url": "https://my.github.enterprise.org/api/v3/emojis",
  "events_url": "https://my.github.enterprise.org/api/v3/events",
  "feeds_url": "https://my.github.enterprise.org/api/v3/feeds",
  "following_url": "https://my.github.enterprise.org/api/v3/user/following{/target}",
  "gists_url": "https://my.github.enterprise.org/api/v3/gists{/gist_id}",
  "hub_url": "https://my.github.enterprise.org/api/v3/hub",
  "issue_search_url": "https://my.github.enterprise.org/api/v3/search/issues?q={query}{&page,per_page,sort,order}",
  "issues_url": "https://my.github.enterprise.org/api/v3/issues",
  "keys_url": "https://my.github.enterprise.org/api/v3/user/keys",
  "notifications_url": "https://my.github.enterprise.org/api/v3/notifications",
  "organization_repositories_url": "https://my.github.enterprise.org/api/v3/orgs/{org}/repos{?type,page,per_page,sort}",
  "organization_url": "https://my.github.enterprise.org/api/v3/orgs/{org}",
  "public_gists_url": "https://my.github.enterprise.org/api/v3/gists/public",
  "rate_limit_url": "https://my.github.enterprise.org/api/v3/rate_limit",
  "repository_url": "https://my.github.enterprise.org/api/v3/repos/{owner}/{repo}",
  "repository_search_url": "https://my.github.enterprise.org/api/v3/search/repositories?q={query}{&page,per_page,sort,order}",
  "current_user_repositories_url": "https://my.github.enterprise.org/api/v3/user/repos{?type,page,per_page,sort}",
  "starred_url": "https://my.github.enterprise.org/api/v3/user/starred{/owner}{/repo}",
  "starred_gists_url": "https://my.github.enterprise.org/api/v3/gists/starred",
  "team_url": "https://my.github.enterprise.org/api/v3/teams",
  "user_url": "https://my.github.enterprise.org/api/v3/users/{user}",
  "user_organizations_url": "https://my.github.enterprise.org/api/v3/user/orgs",
  "user_repositories_url": "https://my.github.enterprise.org/api/v3/users/{user}/repos{?type,page,per_page,sort}",
  "user_search_url": "https://my.github.enterprise.org/api/v3/search/users?q={query}{&page,per_page,sort,order}"
}
```

Invalid token:
```
$ curl --header 'Authorization: token invalidtoken' \
    https://my.github.enterprise.org
{
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/enterprise/2.3/v3"
}
```

And at last, I fully agree, Github Enterprise docs doesn't make the matter easier.

**Comment by alcohol** [comment]
@mirfilip pushed a tiny fix. Can you run a `composer self-update` and verify that this resolves your issue?

**Comment by alcohol** [comment]
It should now ask for your token and properly store it and proceed, if it is valid.

**Comment by mirfilip** [comment]
@alcohol No, it doesn't work. It asks for the token twice and tries to `https://my.github.enterprise.org/api/v3`

Notice that:
```
$ curl "my.github.enterprise.org/api/v3"
{"error":"Not Found"}
```
while
```
$ curl "my.github.enterprise.org/api/v3/"
// ok
```

**Comment by alcohol** [comment]
O, trailing `/` is necessary?

**Comment by alcohol** [comment]
Should be resolved now then. Sorry about that.

**Comment by mirfilip** [comment]
@alcohol It works now as supposed. Both downloading and storing token in `auth.json`. Thanks for the work!

**Comment by alcohol** [comment]
You're welcome, thanks for helping us find this bug :-)
