### ISSUE TITLE
Fatal error: GitLabDriver::generateSshUrl() missing

### ISSUE THREAD

**Issue by shochdoerfer** [composer/composer#4935]
While trying to let our Satis instance use the GitlabDriver I ran into a fatal error:
```
PHP Fatal error:  Call to undefined method Composer\Repository\Vcs\GitLabDriver::generateSshUrl() in /srv/satis/vendor/composer/composer/src/Composer/Repository/Vcs/GitLabDriver.php on line 270
```

**Comment by Seldaek** [comment]
Make sure you update composer, this was fixed a while back IIRC.

**Comment by Seldaek** [comment]
Yup, 64b0d721838cdceef679761c5cf69a0d070d14c9

**Comment by shochdoerfer** [comment]
@Seldaek Tried to update the composer/composer dependency for Satis (where error originated for me) but I did not get the latest version with the GitlabDriver. Do you need to create a new tag first?

**Comment by staabm** [comment]
@shochdoerfer `composer self-update` on cli

**Comment by Seldaek** [comment]
https://github.com/composer/satis/blob/master/composer.json#L23 seems to say it depends on dev so it should fetch latest dev-master.
