### ISSUE TITLE
Feature to have something similar to npm version & npm publish commands

### ISSUE THREAD

**Issue by kabirbaidhya** [composer/composer#4939]
[npm](https://www.npmjs.com/) has some really cool features like the ability to release a new version and publish a package right from the command line using commands: `npm version` and `npm publish`. 

The `npm version` command  bumps the version and writes new data back to package.json. 
Furthermore, if run in a git repo, it also creates a version commit and tag. And we can use `-m` or `--message` option to provide the commit message. 
https://docs.npmjs.com/cli/version

Similarly, the `npm publish` command publishes a package to the registry. 
https://docs.npmjs.com/cli/publish

Composer is a lot more similar like `npm`. I think it would be a **nice to have feature** to add `version` and `publish` commands just like those of `npm` to make maintaining and publishing packages to packagist even more easier. 

Currently, in order to publish a composer package you need to go to the packagist website and submit a package: https://packagist.org/packages/submit. 

It would be great if we could just do `composer version` and `composer publish` right from the command line to publish a new version of our package to the packagist and also tag a release in github. Just like this https://docs.npmjs.com/getting-started/publishing-npm-packages

Although, it's not a must have thing. But I would say, it's a "nice to have" feature to think about to make package development and release even easier.

**Comment by alcohol** [comment]
"Cool" is a relative term. I personally see very little added value for both of the suggested commands. Submitting a package on Packagist does not take much effort. Adding this functionality to the Composer binary means we will need to make it aware of Packagist user accounts, which seems like overkill to me. The version command I cannot really find any use-case for. All you need is a git tag. Furthermore, Composer is not a release management tool. This should be part of your CI flow in my humble opinion.

**Comment by Seldaek** [comment]
We have been working with git tags and branches as opposed to version uploads. It's quite a different model and not really compatible so I don't think this is likely.
