### ISSUE TITLE
Default to --prefer-source if no utilities available to unpack archives

### ISSUE THREAD

**Issue by kelunik** [composer/composer#4943]
Currently, composer retries downloading dist files again and again if the `zip` extension is missing. Instead, it should recognize that it's missing the extension and directly fall back to cloning via `git` for all following packages.

![Screenshot](http://i.imgur.com/UI98xja.png)

**Comment by curry684** [comment]
I'm not sure I agree. Missing unzip facilities is a pretty serious error as it forces you to use the MUCH slower source clones, so it's not a bad thing really it's shoved in the user's face this bad that he has to fix it. If you consciously want to cope with this, you are free to use the `--prefer-source` option on the command line.

I looked into implementing your request, and it's not all that hard, but it would result in a warning *before* the output, not after, so it's likely going to be missed in backscroll.

The error itself could be better though, as `apt-get install unzip` or a similar package manager command will also remove this warning - you don't actually need the zip extension, on *nix it happily prefers the `unzip` CLI tool.

**Comment by alcohol** [comment]
Well admittedly it does not make much sense to even attempt to download archived sources if we cannot unpack archives. So I do agree with OP that this logic could be altered. I think the quickest solution would be to simply implicitly enable `--prefer-source` in the installer in this situation.

**Comment by curry684** [comment]
That's not a valid solution as `dist` type could also be rar, tar or gzip which can all be separately unavailable for different reasons.

**Comment by alcohol** [comment]
We know the dists from Github will always be a zip. So to assume otherwise doesn't make much sense to me.

**Comment by kelunik** [comment]
We know it for GitHub, but there might be other platforms using different formats.

Another alternative would be to use https://github.com/splitbrain/php-archive as long as `zlib` is available but not `zip`.

**Comment by curry684** [comment]
I was already looking into a proper solution, where all Downloader classes can declare whether they are supported in the current environment, that would make it clean, but as said that would issue a warning on top of the output where it might be missed. If we don't consider that an issue I can just implement it (actually wrote half of it last night).

**Comment by kelunik** [comment]
Why not just put the warnings to the end of the output?

**Comment by curry684** [comment]
The part of the code where it's triggered doesn't really have any kind of persistence about it, just an `OutputInterface`. So buffering the warnings would require a lot of extra trickery.

Don't think it's too much of an issue, if a developer doesn't watch the output of something invasive like this he deserves to be punished, and I think the best implementation would still issue a `Skipping dist type "zip" as it is not supported` line to every installation where it's relevant.

**Comment by Seldaek** [comment]
I tweaked it so it's a bit less verbose and it aborts *before* downloading the zip file which makes it faster too.

```
Installing dependencies (including require-dev) from lock file
    Failed to download seld/jsonlint from dist: The zip extension and unzip command are both missing, skipping
    Now trying to download from source
  - Installing seld/jsonlint (1.4.0)
    Cloning 66834d3e3566bb5798db7294619388786ae99394
```

As an added bonus this adds unzip command support on windows in case you have it, which will run faster too :)

I can see that your solution would be cleaner strictly speaking @curry684 but it's also a bunch more code for a non-issue as 99% of dists are zip and 99% of source are git, I don't think we'd benefit much from adding full support for checking which downloaders are supported etc etc

**Comment by curry684** [comment]
The amount of extra code wouldn't have been too much as I was introducing it in `addDownloader` centrally in the downloadmanager, but I'm fine with this alternative implementation.

**Comment by zhilevan** [comment]
#### just try to install zip and unzip package on your server , 

`sudo apt-get install zip unzip`

### worked for me.
