### ISSUE TITLE
Repositories in dependencies are ignored

### ISSUE THREAD

**Issue by RonRademaker** [composer/composer#4948]
Hi,

If you use a fork of some package that is on packagist, you need to add the repository to your composer.json to make sure your fork is installed instead of the version from packagist. However, if I use that component (with the composer.json with the fork repository) as a dependency in some project, composer will not use the defined repository. Instead the package from packagist will be installed. As a result, the component will have other versions of its dependencies when used within a project (which is particularly annoying if you decided to make the fork because the package in question is not following semver :wink: ).

**Comment by stof** [comment]
repositories are root-only. this is documented, and there is even a page in the doc explaining why it works this way (short version: it would be a nightmare to make it working, and could even lead to case where it is impossible to handle things): https://getcomposer.org/doc/faqs/why-can't-composer-load-repositories-recursively.md

**Comment by RonRademaker** [comment]
Thanks!
