### ISSUE TITLE
Thanks for making my life a lot harder

### ISSUE THREAD

**Issue by Markkemp** [composer/composer#4949]
I HATE COMPOSER

Every single application now only includes a composer install.

Which makes it a nightmare to install anything on a web server. Not everyone is a command line wizz kid.

Thanks for making the lives of a small elite easier, at the expense of every beginner.

Where do the silent majority send their hatemail to?

**Comment by curry684** [comment]
They just go to https://getcomposer.org/doc/01-basic-usage.md, discover the application is really easy to use, and decide they don't want to send any hatemail over a tool that makes their lives a lot easier instead of harder.

**Comment by Seldaek** [comment]
If you have specific complaints feel free to open another issue, but if you just need to vent I suggest you do it elsewhere.
