### ISSUE TITLE
Possible to use parent composer.json PHP minimum rather than installed version when installing/updating

### ISSUE THREAD

**Issue by alanhartless** [composer/composer#4954]
Is it possible to tell composer to check against the minimum PHP version defined in the parent composer.json rather than the installed PHP version? From a dev point of view, this might help from digging through the composer.lock file to ensure some dependency didn't inadvertently bump the PHP minimum while also not requiring the dev to keep the project's minimum PHP version installed on their machine.

Forgive me if this has already been addressed/discussed!

**Comment by alcohol** [comment]
What do you mean by parent composer.json?

The only way to tell Composer to assume a different PHP version than you actually have installed, is by using the platform configuration, which can only be done from your root composer.json.

https://getcomposer.org/doc/06-config.md#platform

**Comment by alcohol** [comment]
Wait I think I misread.. you mean for example, your project has `require: { php: "~5.3" }`, and one of your dependencies has `require: { php: "~5.4" }`, hence your minimum php requirement is `5.4` (but you want it to remain `5.3`?).

**Comment by finwe** [comment]
I had a similar issue yesterday:

Locally, I have PHP `7.0.3` installed and my project has a dependency on `"doctrine/migrations": "^1.1"` which in turn has a dependency on `"ocramius/proxy-manager ^1.0|^2.0"`. 

No matter what I put into the required version of PHP in my `composer.json` (have tried `>=5.6` and `^5.6 || ^7.0`), on my machine with 7.0, the `2.0` version of proxy-manager is installed and it has a dependency on `ocramius/package-versions` which is supported on `7.0` only. Therefore, when committing `composer.lock` and installing on a machine with `5.6`, composer cannot perform an installation.

This seems to me as a bug, however I can be missing something with PHP requirements defintion.

Hint with platform setting above works, however I would assume that projects PHP requirements would be taken into consideration when resolving versions of packages.

**Comment by alcohol** [comment]
No that makes sense. If you know your target environment is a specific version and will not change anytime soon, then you should definitely make use of the platform config directive and specify `5.6` as your php version.

**Comment by finwe** [comment]
@alcohol Ok, thanks for clearing this up!

**Comment by alcohol** [comment]
@alanhartless any feedback on the questions I raised?

**Comment by alanhartless** [comment]
@alcohol Sorry for the delay!

Yes, in our project's composer file we have 
```
    "require": {
        "php": ">=5.3.7",
```

Which just fine when installing from source and of course wanted and expected behavior.

But when we were packaging things up for a distribution zip, we noticed that one of the dependencies installed a dependency that had a minimum requirement for 5.4 which then bumps our project's minimum requirement. So we had to scour the composer.lock to see what all was installed with PHP minimum's greater than our own project's and add specific versions to our project's composer.json file. 

We of course keep track of our direct dependencies but in this case, it's more of a problem with the dependency dependencies that became the headache.  

So I was thinking how helpful it would be to this scenario if composer would yell at us if a dependency or a dependency's dependency had a PHP minimum requirement greater than the project's minimum.  Maybe a flag or something?

It might just have to be something we have to deal with but thought I'd ask anyway! ;-)

**Comment by curry684** [comment]
When packaging you should use the method mentioned to fake the PHP installed version lower through platform config. The requirements themselves are meaningless outside their package as they are all resolved during dependency resolution within the grand scale of the host platform. Packaging implies you want to limit that beforehand, which is achieved by letting Composer know you want it to act as if running under, in your case, PHP 5.3.4 probably.

**Comment by alanhartless** [comment]
ah! Perfect. Thanks!
