### ISSUE TITLE
[Question] When new composer release going to be published?

### ISSUE THREAD

**Issue by vancoz** [composer/composer#4956]
Hi, http://flyingmana.de/blog_en/2016/02/14/composer_cache_injection_vulnerability_cve_2015_8371.html this issue is fixed in develop, but it is not in 1.0.0-alpha11. May I know when release of 1.0.0-alpha12 is scheduled? 

Thank you.

**Comment by Seldaek** [comment]
Updated the changelog to prepare the release, I'll try and do that early next week, after all the changes today we need a few days to check for regressions before calling it a release.

In the meantime if you like to use the latest build you can always run `composer self-update`

**Comment by vancoz** [comment]
Hi @Seldaek, thank you for the answer. Unfortunately I can not use self-update, because we use composer as dependency in our application.

**Comment by alcohol** [comment]
@vancoz the equivalent would be using `dev-master` and running a `composer update` to fetch the latest version.
