### ISSUE TITLE
Stability handling improvements for 1.0

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#4960]
- [x] self-update should have a notion of channels with stable/preview/snapshot and a way to upgrade to a given channel, see https://getcomposer.org/versions
- [x] figure out a way for channels to be php-version specific
- [x] composer diagnose version check has to be updated to work with channels

Fixes #3707

**Comment by curry684** [comment]
Considering #4979 - by all means consider having 3 channels, on `master`, a dev branch kept slightly behind, and tags. As many developers are likely to stay on dev if you only separate into stable/dev and fresh crashers are better left to an inner circle of volunteers willing to accept 'edge' failing hard.

**Comment by barryvdh** [comment]
Yeah or perhaps a build script that makes sure only commits which are run by Travis CI and pass, are published to the self-update channels.

**Comment by curry684** [comment]
To rely on that we'd need to install a code coverage monitor first and write a shitload of unit tests. Right now according to my PhpStorm the regular tests cover 68% of lines in `src`, which is nowhere near the 90+% you'd want to be able to rely on that (or even 80% would be a good start).

**Comment by barryvdh** [comment]
Yes but a check that it run the most common commands like init/install/command, with syntax errors, would prevent at least the most serious errors.
