### ISSUE TITLE
[Composer\Downloader\TransportException] and Checking http connectivity to packagist: FAIL

### ISSUE THREAD

**Issue by brandontamm** [composer/composer#4963]
I have been using a project for many months now with no problems, but today I am getting a strange error on my local development machine when I run 'composer update' :
[Composer\Downloader\TransportException]
  Your configuration does not allow connection to http://packages.firegento.com. See https://getcomposer.org/doc/06-config.md#secure-http for details.

Running 'composer diagnose' :
Checking http connectivity to packagist: FAIL

I use Docker and noticed this issue after upgrading to the most recent version of Docker (via Brew)

**Comment by curry684** [comment]
> See https://getcomposer.org/doc/06-config.md#secure-http for details.

Did you read the information at that link?

A configuration option was deployed 11 hours ago (https://github.com/composer/composer/pull/4907) enforcing HTTPS connections to remote repositories by default, as HTTP repositories are sensitive to MITM attacks injecting malicious code.

As https://packages.firegento.com/ is also available with HTTPS you can just change the repository declaration to `https` in your config.

**Comment by Seldaek** [comment]
Please switch to https://packages.firegento.com/ as @curry684 said.

cc @SchumacherFM @airbone42 I'm not sure who is responsible for that firegento repo but please make sure it displays the https:// URL in the instructions on top.

**Comment by brandontamm** [comment]
@curry684 & @Seldaek - Thank you I was beating my head against the wall :)

**Comment by curry684** [comment]
No prob, I also submitted the PR already over at Firegento (https://github.com/magento-hackathon/composer-repository/issues/364) and it's already been merged hehe.

**Comment by dimkir** [comment]
Sorry for commenting here, but  I have `file` type dist, and switching to `https` still yields in the same error:
```
    "repositories" : [
        {
            "type" : "package",
            "package" : {
                "name" : "jquery/jquery",
                "version" : "1.11.1",
                "dist": {
                    "type":  "file",
                    "url" : "https://code.jquery.com/jquery-1.11.1.js"
                }
            }
        }
    ],
```

and this is the error message I get (on heroku build). I have checked links to firegento fixes and there repository of type `composer` is used, but not `file` .. maybe that's the case?

```
remote:          - Installing jquery/jquery (1.11.1)
remote:            Downloading: Connecting...    Downloading: Connecting...    Downloading: Connecting...
remote:                                                                                                                                                         
remote:          [Composer\Downloader\TransportException]                                                                                                       
remote:          Your configuration does not allow connection to http://code.jquery.com. See https://getcomposer.org/doc/06-config.md#secure-http for details.  
```

**Comment by Seldaek** [comment]
@dimkir that's because you need to update the file URL in the composer.lock file as well, and possibly in vendor/composer/installed.json - or the easy way is to wipe the vendor dir and composer.lock and install from scratch.

**Comment by dimkir** [comment]
@Seldaek Thank you Jordi, for pointing in  the right direction

Deleting vendor dir and composer.lock surely works, but that would upgrade all the locked dependencies, which sometimes can be tricky.

The simplest steps which I found work without rebuilding `composer.lock` would be: 

1) delete `vendor` dir         (to get rid of `vendor/composer/installed.json` which cached all repository urls)
2) edit `composer.lock`      (because this file will be used during deployment via `composer install`)
3) edit `composer.json`      (simply to bring in sync with `composer.lock`)
4) run `composer install`

**Comment by flik** [comment]
Here is simple solution:
`composer config -g secure-http false`

**Comment by curry684** [comment]
@flik do you also recommend people to remove all the locks from their house when a key is bent?

The command you issues **completely removes all validation of network level security from Composer system wide and permanently**. Please do not recommend others to do so without warning of the potentially grave dangers involved.

The true fix is to fix the repository site, not remove security from Composer.

**Comment by wadiebo** [comment]
Here is  solution: Desactive Antivirus (web shield ..)
