### ISSUE TITLE
Secure HTTP check bypassed when composer.lock exists in project root

### ISSUE THREAD

**Issue by prometheas** [composer/composer#4968]
Interestingly, it seems that the `secure-http` setting is ignored when a `composer.lock` file is present in the project root. To reproduce, attempt to install a dependency hosted on a non-secure respository (like from wpackagist.org) without allowing non-secure HTTP connections, and see that it will fail.

Then `touch composer.lock` and attempt again; Composer will install the deps anyway!

Originally found by the handsome @rca.

**Comment by Seldaek** [comment]
I can not reproduce this.. Could you please show complete reproduce steps? I have a lock file with a package that's http based and it installs only if I disable secure-http for me.

**Comment by Seldaek** [comment]
Ping @rca @prometheas? I want to believe you and fix this, but as it stands I don't see why it should behave like that, and I can not reproduce.

**Comment by rca** [comment]
@Seldaek here's what we've seen from behavior on two existing projects:

- a project with insecure http sources, such as http://wpackagist.org/, in `composer.json` lacking `"secure-http": false` in its config _will_ build if `composer.lock` already exists.
- a project with insecure http sources, such as http://wpackagist.org/, in `composer.json` lacking `"secure-http": false` in its config _will not_ build, nor will it create `composer.lock` with `composer update` if `composer.lock` _does not_ already exist.

Composer info:

```
root@fc93d8751d45:~# composer --version
Composer version 1.0-dev (2f638c7d96a69116b98799a49b54e2537ddc53e0) 2016-02-25 21:16:48
```

If it makes a difference, composer is being run within a Docker container.

Thanks!

**Comment by Seldaek** [comment]
OK I got that *but* as I said I can not reproduce it. Can you share an example composer.json + composer.lock that composer will install successfully without secure-http:false?

**Comment by rca** [comment]
I must defer to @prometheas on that one.

**Comment by rca** [comment]
One additional bit I can provide is the command being run to install is: `/usr/local/bin/composer install --prefer-source`

Perhaps it has to do with the `--prefer-source` flag?

Thanks!

**Comment by Seldaek** [comment]
Oh well yes, we don't really check for git/svn URLs to be https/ssh. That is correct. I guess we should but that's gonna hurt a lot more people it seems according to the wpackagist repo.

cc @tamlyn @lavoiesl is there any chance you get wpackagist to use https URLs for the svn repos (and well.. as much stuff as you can) in the source.url and dist.url of all packages?

**Comment by Seldaek** [comment]
@tamlyn @lavoiesl that would include serving the repository over https btw.. Which is already going to be a problem with the current code, so you should fix that ASAP.

**Comment by Seldaek** [comment]
If you can confirm that it is indeed failing for you after a self-update that'd be appreciated. Git & co should now also stop accepting insecure protocols /cc @StormTide

**Comment by prometheas** [comment]
:heart:
