### ISSUE TITLE
composer init explicitly requires filling of optional fileds

### ISSUE THREAD

**Issue by AnrDaemon** [composer/composer#4969]
https://getcomposer.org/doc/04-schema.md#authors

The "authors" field is optional, but composer demand it filled.
This is highly inconvenient when you just need to establish an environment to quickly check something (i.e. tracking a regression through a multitude of library versions).

**Comment by curry684** [comment]
You know the interactive init is completely optional right? If in an empty directory you just type:
```sh
composer require phpunit/phpunit
```
It will automatically create the following `composer.json`:
```json
{
    "require": {
        "phpunit/phpunit": "^5.2"
    }
}
```
The `init` command is more for setting up real libraries interactively.

**Comment by AnrDaemon** [comment]
No, I didn't know it is optional. Thanks for the hint.

**Comment by curry684** [comment]
Thing is that all properties `init` asks for are actually optional for local projects, like [`name` and `description`](https://getcomposer.org/doc/04-schema.md#name):

> Required for published packages (libraries).

There are technically no required properties for local projects, even the absence of `require` just means you intend to install nothing - you may want to use just the `autoload` sections for example.

**Comment by Seldaek** [comment]
You were right that author couldn't easily be skipped, I fixed that.

**Comment by AnrDaemon** [comment]
Thank you, much appreciated!
