### ISSUE TITLE
__DIR__ constant in "require" Command seems to be broken

### ISSUE THREAD

**Issue by boesing** [composer/composer#4975]
I am facing some strange issue while executing `composer require <vendor>/<package>` where it doesn't matter which package I require.

As you can see, the "absolute" path to the "standards" directory seems to be within the `composer.phar` which I put into `/usr/bin/` directory.
However, I only get this issue while in `require` Command. If I use `install` or `update`, anything works as expected.

Its quite confusing since the `__DIR__` constant should always contain the absolute directory to the current File, never to the executing PHAR? 
Is this a PHP Bug executing a PHAR-File or something during `composer require` command?

---

`composer --version`
Composer version 1.0-dev (070ee506937170bb81a2e352aa444eaf29f0a2f6) 2016-02-28 14:08:43

Here is the path detection in the `InstallerPlugin` Class:

```
        $standards = __DIR__ . '/standards/';
        $iterator = new DirectoryIterator($standards);
```

The `composer.json`

```
{
  "name": "myvendor/codestandard",
  "minimum-stability": "stable",
  "type": "composer-plugin",
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/composer/composer.git"
    }
  ],
  "require": {
    "composer-plugin-api": "^1.0",
    "squizlabs/php_codesniffer": "2.*"
  },
  "require-dev": {
    "composer/composer": "~1.0@dev"
  },
  "autoload": {
    "psr-4": {
      "C24\\Composer\\CodeStandard\\": ""
    }
  },
  "extra": {
    "class": "C24\\Composer\\CodeStandard\\InstallerPlugin",
    "branch-alias": {
      "dev-master": "1.0.x-dev"
    }
  }
}
```

`composer require <vendor>/<package> -vvv`

```
Generating autoload files

Installation failed, reverting ./composer.json to its original content.

                                                                                                                                 
  [UnexpectedValueException]                                                                                                     
  DirectoryIterator::__construct(phar:///usr/bin/composer/src/Composer/Plugin/standards/): failed to open dir: operation failed  
                                                                                                                                 

Exception trace:
 () at phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php(174) : eval()'d code:53
 DirectoryIterator->__construct() at phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php(174) : eval()'d code:53
 C24\Composer\CodeStandard\InstallerPlugin_composer_tmp0->symlinkStandards() at n/a:n/a
 call_user_func() at phar:///usr/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:166
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:94
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar:///usr/bin/composer/src/Composer/Installer.php:333
 Composer\Installer->run() at phar:///usr/bin/composer/src/Composer/Command/RequireCommand.php:170
 Composer\Command\RequireCommand->execute() at phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///usr/bin/composer/src/Composer/Console/Application.php:166
 Composer\Console\Application->doRun() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///usr/bin/composer/src/Composer/Console/Application.php:99
 Composer\Console\Application->run() at phar:///usr/bin/composer/bin/composer:43
 require() at /usr/bin/composer:25
```

**Comment by alcohol** [comment]
FYI: You don't have to add `composer/composer` as a repository, it's available through Packagist.

As for your "standards" package. Do you have a repository URL so we can see some actual code of your installer plugin? It's not very clear to me what you are doing.

**Comment by boesing** [comment]
Nope, the package is private but I can post the InstallerPlugin to a gist.
[InstallerPlugin.php](https://gist.github.com/boesing/e574f84d21138c5b37c9)

**Comment by curry684** [comment]
The gist isn't working. I do see your problem however - Composer loads the plugin classes with `eval` in `PluginManager:174`, and that breaks your code as the magic constants like `__DIR__` cannot work in that construct. I'm not really sure how to circumvent this, other than using another mechanism to package those support files in your installer.

**Comment by boesing** [comment]
Well, but the same code is being executed for `composer install` or `composer update` and there is no issue with `__DIR__` constant.

**Comment by alcohol** [comment]
Did you try putting a debug statement near `$standards = __DIR__ . '/standards/';` to see what it actually contains? E.g. a simple `var_dump()`. Then re-run install, update and require, and see if the content differs or not.

**Comment by boesing** [comment]
Yes. In `require` command it contains the path you can see in the above exception. In `install` or `update` command it contains the path to the `vendor/myvendor/codestandard/standards/` directory.
This is exactly what I've expected.

**Comment by alcohol** [comment]
I'm honestly not sure. I don't use the plugin architecture enough to understand what is going on here. Maybe /cc @Seldaek does.

**Comment by Seldaek** [comment]
Please try again with latest composer. I don't really like the fix but I think it'll do the job and has fairly low chances of causing regressions.

**Comment by boesing** [comment]
Works like a charm. Thanks for that quick response!

**Comment by alcohol** [comment]
@Seldaek any idea though why it would previously work during install/update, but not require?

**Comment by Seldaek** [comment]
It basically fails whenever the plugin gets loaded twice. Require loads composer twice first to resolve the version to require and then to run the update, so the second time it has to use this eval trick and that fails.
