### ISSUE TITLE
Require PHP 7 fails on HHVM

### ISSUE THREAD

**Issue by sebastiankraus** [composer/composer#4976]
Hello,

when I require PHP >=7.0 in my composer.json `composer install` fails on Travis CI with HHVM (3.11.0, so PHP 7 is supported). Everything's working fine with PHP 5.x.
This is the error message:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php >=7.0 but your HHVM version does not satisfy that requirement.
```

Is there any way to require a PHP **or** HHVM version via Composer? Or do I have to give up on the require-statement / use `--ignore-platform-reqs`?

**Comment by curry684** [comment]
HHVM is [definitely not fully compatible with PHP7 yet](https://github.com/facebook/hhvm/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A%22php7+incompatibility%22+), so I'm afraid there's not much we can do.

I don't have HHVM machines at my disposal, but what does it even report for `PHP_VERSION`, or in `c show -p | grep php`?

**Comment by Seldaek** [comment]
We can't really fix that.. Until they release something that ships a PHP_VERSION indicating they are php7 compatible then they will be treated as incompatible.

**Comment by sebastiankraus** [comment]
Oh, well, I wasn't aware of those issues - thanks for linking them!

I guess I'll just move hhvm to the allow_failures list at Travis and use `--ignore-platform-reqs` until HHVM's PHP 7 compatible.
