### ISSUE TITLE
Requiring dev dependencies of a package

### ISSUE THREAD

**Issue by greg0ire** [composer/composer#4981]
I would like to test integration of SonataAdminBundle with symfony. At the moment, foreach version of symfony, we use `composer require "symfony/symfony:${SYMFONY_VERSION}"`, but that is not really good enough since an install of symfony can have other (potentially conflicting) dependencies.

> composer require "symfony/framework-standard-edition:${SYMFONY_VERSION}"

would be better, but again, it is not enough, because conflict can also arise with development dependencies.

For instance, the admin bundle uses `sensio/generator-bundle`, and to be sure we are compatible with symfony, we would have to see whether our requirement for this bundle is compatible with the dev requirement in `symfony/framework-standard-edition`. This is not so hypothetical by the way, we were bit by this in the recent past : see https://github.com/sonata-project/SonataAdminBundle/issues/3596

Is there a way to require the development dependencies of a package? I think I could parse the output of composer show symfony/framework-standard-edition, but that would not be very robust, would it ?

**Comment by curry684** [comment]
This is not possible today, as `require-dev` is specifically [marked root only](https://getcomposer.org/doc/04-schema.md#require-dev). It's just never considered for nested packages.

Merging the dev-requirements is pretty trivial though, I think you'd just want the `composer.json` of Symfony SE with the dev requirements of Sonata merged in?

**Comment by greg0ire** [comment]
> Merging the dev-requirements is pretty trivial though, I think you'd just want the composer.json of Symfony SE with the dev requirements of Sonata merged in?

Yes, but I'd like to do that programmatically, because I'm testing several versions of symfony. See https://github.com/sonata-project/SonataAdminBundle/blob/master/.travis.yml#L52

**Comment by greg0ire** [comment]
In fact, I don't really want to merge, if the version specified in sonata admin is compatible with the one in symfony standard, I want the build to fail without going any further.

**Comment by Seldaek** [comment]
It seems like what you want to test is installing sonata admin bundle within a symfony standard edition.. so why not do just that? Run a create-project of standard edition and then require sonata admin in it? You can even run a require with --no-update then run `composer update --dry-run` and see if that returns 0 all should be fine with your dependencies. If you get non-0 you can assume there is a problem. The --dry-run will skip installation and only do dependency resolution which should run faster.

I don't really see what else we can do here. It sounds like a task for a dedicated test tool, not something we need to add to composer, so I'll close this.

**Comment by greg0ire** [comment]
I did think about that, but dismissed it since I want to run tests afterwards, which implies also installing the dev dependencies of the bundle. And since both dev dependencies might be incompatible, that does not seem reasonable now that I think of it, so I'll just do as you suggested and not try to do both things in one go. Thanks!
