### ISSUE TITLE
Windows10 and composer

### ISSUE THREAD

**Issue by avijit1258** [composer/composer#4985]
Windows installer for composer is not compatible with windows10. When will you solve this.

**Comment by curry684** [comment]
It most certainly is, used it twice on Windows 10 last month. Which problems are you experiencing in detail?

**Comment by avijit1258** [comment]
When i run composer windows installer it says can not open this, contact a
version for this

**Comment by curry684** [comment]
What am I supposed to debug from "contact a version for this"? That's not a message from our end to be sure.

If you want us to look at your issue provide details we can actually use. The installer works out of the box on Windows 10 for thousands of users, so if it doesn't for you there's something special on your computer. We can only analyze that with a full list of steps required for reproduction, an exact description of the problem, and exactly copy/pasted error messages, or screenshots as pictures oft say more than a thousand words.

So please provide more information than "it doesn't work" - you need to help us help you.

**Comment by avijit1258** [comment]
Exact reply is To find  a version for your pc, check with software
publisher.

**Comment by Seldaek** [comment]
Please report this at https://github.com/composer/windows-setup/issues and try to include more details because I doubt the information here will be enough.

**Comment by avijit1258** [comment]
Sorry . Actually when i am downloading composer-setup.exe(from getcomposer.com) from windows 10 the file size is 40 kb. But the actual size is 640 kb . this is the problem i have faced.
