### ISSUE TITLE
Windows 8.1 GPU Issue

### ISSUE THREAD

**Issue by blakethepatton** [composer/composer#4986]
Hi there, I'm just wanting to make aware that I'm facing facing an issue that cripples my GPU. To reproduce: I'm on Windows 8.1, Using the eomposer-setup.exe to install it and then restarting my computer/going into sleep/hibernate. I'm pretty sure it has to do with the composer installer because when I do a manual install there are no issues. 

Additionally I do have WAMP installed and doesn't start on startup. I'm not sure that that would cause a GPU crash though. If there's any way that I can fix this I'd love to know but until then I'll just be using composer via the manual install

**Comment by curry684** [comment]
I don't understand what issues you are experiencing and how and why they would be related to your GPU. Please provide more detailed steps to reproduce the issue, and describe in more detail what happens on your computer.

**Comment by blakethepatton** [comment]
I installed composer through the exe and it works fine up until the point that I do a system reboot/hibernate/sleep.  When my computer resumes after composer has been installed, my screen will randomly go black for a few seconds and when it comes back, Windows notifies me that my graphics card has just recovered from a crash.

**Comment by blakethepatton** [comment]
If it helps: 
GPU-Z: http://imgur.com/wO59ReE

**Comment by stof** [comment]
Well, composer itself does not do anything related to the GPU, so this looks weird.

**Comment by Seldaek** [comment]
Yeah I never thought I'd see a GPU related issue in a php project :) Anyway cc @johnstevenson in case you have a clue as it seems windows setup related.

**Comment by blakethepatton** [comment]
No it certainly isn't a php issue. I am able to run composer via the manual install perfectly fine. I think the issue has something to do with the windows installer or however it's functioning.

**Comment by staabm** [comment]
> Yeah I never thought I'd see a GPU related issue in a php project :)

@Seldaek lets talk again when we parallalize the solver in the GPU ;-)

**Comment by johnstevenson** [comment]
Wow! Composer-Setup.exe doesn't do anything GPU related apart from display the setup wizard whilst it is running. But since the problem occurs after this, it could be something the installer has done that upsets the GPU drivers. So here are some thoughts:

1. Did you install the shell menus. This feature adds registry keys that invoke a dll when you bring up a context-menu in the File Manager. So if you did install them, do they work okay before you reboot etc? Perhaps its CLSID ```{9DF9AD0B-5D99-485a-840E-858003F87478}``` conflicts with something?

2. Did Composer-Setup need to change your path? If so, take a look at what it did, just in case it has completely screwed up and overwritten something the GPU needs.

**Comment by blakethepatton** [comment]
Rest assured I got no issues when installing composer. Just after it was installed. In response:
1. I didn't install shell menus. (Sorry it sounded like a promising reason)
2. I believe that composer updated the path for PHP the first time I installed it but that was it. 

For the record I would just like to point out that I am running WAMP and Git Bash and accessing composer through Git bash but this issue occurs even with git closed. I have a feeling that the issue has something to do with how composer hooks into Windows so that you can call composer anywhere. Sadly I'm not super fluent in writing Windows apps or I'd have a better idea of how this happens. The issue does come and go with composer being installed and I really couldn't believe something written for PHP was crashing my GPU so I reinstalled it three times just to be sure.

**Comment by johnstevenson** [comment]
When you say "The issue does come and go with composer being installed" do you mean when you have used Composer-Setup or installed manually (or both)?

There is nothing unusual how "composer hooks into Windows". When you run the ```composer``` command, your path is searched for a folder that contains a file that can execute the command - for Git Bash it will find the *composer* shell script, for cmd.exe the *composer.bat*.

Have you searched online for generic graphics card issues and updated your drivers?

**Comment by blakethepatton** [comment]
Comes and goes only with the Composer-Setup being installed. I have absolutely no issues with the manual install. 
As far as my graphics card goes I'm running the latest version of the driver from AMD and Windows but I haven't looked up generic graphics card issues. I've had my computer for a number of years and I've never had the graphics card just freeze up and crash like this. It was alarming. What sort of generic graphics card issues would you suggest I start looking into?

**Comment by blakethepatton** [comment]
Also is there some software I could run to get bug reports or debug info from my graphics card that could help indicate the root of the problem?

**Comment by johnstevenson** [comment]
Take a look in your Event Log: *Windows Logs -> Application* for critical errors. It might give you some clues.

**Comment by blakethepatton** [comment]
Alright, I reinstalled composer-setup and almost immediately after rebooting got my screen to go black and freeze up. The only thing in my event log related to the incident was this: `Display driver amdkmdap stopped responding and has successfully recovered.` Which is what I already knew. The application logs had only informational entries which are attached as txt to this comment.
[crash.txt](https://github.com/composer/composer/files/155909/crash.txt)

**Comment by blakethepatton** [comment]
It seems to have been my driver. Sorry for all the fuss there was a new driver that was waiting and it fixed the issues.
