### ISSUE TITLE
error on updating package

### ISSUE THREAD

**Issue by tatenen** [composer/composer#4987]
https://yadi.sk/i/hQBrJj__pqVRX

Composer version 1.0-dev (ef6b7cdf12dc0331ed1aa9fde8be04e18c8e07e2) 

in older versions it was work

**Comment by barryvdh** [comment]
So perhaps related to https://github.com/composer/composer/commit/be4d385942cce9b0d1116aba985a99380c7a53d1 ?

Can you add some more information, like the composer.json  used, git version (`git --version`) and verbose output (`composer update -vvv`) ?

**Comment by tatenen** [comment]
git version 2.5.0
composer.json
in section "repositories" i am using private repo
{
	"type": "vcs",
	"url": "git@bitbucket.org:dfsru/dfs_common.git"
}

in section require
"dfs/common": "1.1.10", 


repo dfs/common  has tags 1.1.1 ... 1.1.10

composer update -vvv see in screenshot https://yadi.sk/i/q6Rcf9JWpqZQh

if i remove vendor/dfs/common and then composer update install package successful
local package has not uncommitted chanages

**Comment by tatenen** [comment]
find version that has no error on updating package version 
Composer version 1.0-dev (618190027a1f2e7acd0a819a5b7cdd3cfdc1f3f3)

**Comment by tatenen** [comment]
https://yadi.sk/i/0z1PFVVIpqcHi

**Comment by curry684** [comment]
Is this issue consistently reproducable with a Composer less than a week old? That commit @barryvdh  mentions went in 6 days ago and is causing the error, just trying to determine whether this is some sort of corruption on your end interfering or a fundamental issue.

**Comment by Seldaek** [comment]
So it looks like `git rev-parse --abbrev-ref HEAD` returned `heads/1.1.10`. I don't get in which circumstances git will do that. I can't reproduce it here even by checking out a tag. I always get `HEAD` when I am on a tag here. But anyway I rewrote the whole logic to be hopefully more resilient. Please confirm if it works for you now.

**Comment by tatenen** [comment]
after update composer to revision e94066967ce136c55e3c3a575e480fab34538c59 problem is gone.
thanks
