### ISSUE TITLE
Specific repository in composer.json behind firewall

### ISSUE THREAD

**Issue by timalbert** [composer/composer#4991]
Is there a way to have a specific repository in my composer.json to be downloaded through my org's proxy without setting env variables? The problem is certain remote urls are passed through a firewall and others through a proxy.

**Comment by curry684** [comment]
Sorry, this seems to be quite an exotic case that Composer does indeed not support, nor would it see much use to add as a feature. I would recommend contacting local system administration so they can adjust the routing rules accordingly.

**Comment by Seldaek** [comment]
What type is your repo? If it's a composer repo (toran proxy or satis) then you should be able to load settings in the repo like https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md#security via `options > http > proxy`. That should propagate down to package downloads coming from that repo as well.

If it's something else like VCS I'm afraid we don't have a solution right now.

**Comment by timalbert** [comment]
Thanks for the tip...it is a wordpress-plugin. Would that still work? Would it look like this:

```
"repositories": [
  {
    "type": "package",
    "package": {
      "name": "deliciousbrains/wp-migrate-db-pro",
      "type": "wordpress-plugin",
      "version": "1.5.5",
      "dist": {
        "type": "zip",
        "url": "https://deliciousbrains.com/dl/wp-migrate-db-pro-latest.zip?licence_key=xxx"
      },
      "options": {
        "https_proxy" : "xxx"
      }
    }
  }
]
```

**Comment by Seldaek** [comment]
Hmm no I don't think the package repository supports it. Wouldn't be too hard to add support for though.

**Comment by Seldaek** [comment]
Yeah so you can do it like this now:

```
"repositories": [
  {
    "type": "package",
    "package": {
      "name": "deliciousbrains/wp-migrate-db-pro",
      "type": "wordpress-plugin",
      "version": "1.5.5",
      "dist": {
        "type": "zip",
        "url": "https://deliciousbrains.com/dl/wp-migrate-db-pro-latest.zip?licence_key=xxx"
      },
      "transport-options": {
        "http": {
            "proxy" : "xxx"
         }
      }
    }
  }
]
```

See http://php.net/manual/en/context.http.php for more details about other options you can give it.
