### ISSUE TITLE
Composer not working after self-update to 1.0.0-beta1

### ISSUE THREAD

**Issue by dmitriy-luch** [composer/composer#4997]
I'm not able to download packages via composer after self-update
The error is
Installation failed, reverting ./composer.json to its original content.
  [ErrorException]                       
  Illegal offset type in isset or empty 

Here are some details from my command 
`composer require "borales/yii2-phone-input" "*"`
Adding VCS repository bower-asset/jquery
Downloading https://api.github.com/repos/jquery/jquery-dist
Downloading https://api.github.com/repos/jquery/jquery-dist/contents/bower.json?ref=master
Downloading https://api.github.com/repos/jquery/jquery-dist/commits/master
Downloading https://api.github.com/repos/jquery/jquery-dist/tags?per_page=100
Downloading https://api.github.com/repositories/28825109/tags?per_page=100&access_token=09d90c1d9dffcb23527e9abf293c48e350566f19&page=2
Downloading https://api.github.com/repos/jquery/jquery-dist/git/refs/heads?per_page=100

Installation failed, reverting ./composer.json to its original content.

                                         
  [ErrorException]                       
  Illegal offset type in isset or empty  
                                         

Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Package/Version/VersionParser.php:26
 Composer\Util\ErrorHandler::handle() at phar:///usr/local/bin/composer/src/Composer/Package/Version/VersionParser.php:26
 Composer\Package\Version\VersionParser->parseConstraints() at /home/wl-dr/.composer/vendor/fxp/composer-asset-plugin/Repository/FilterUtil.php:41
 Fxp\Composer\AssetPlugin\Repository\FilterUtil::getVersionConstraint() at /home/wl-dr/.composer/vendor/fxp/composer-asset-plugin/Repository/VcsPackageFilter.php:214
 Fxp\Composer\AssetPlugin\Repository\VcsPackageFilter->satisfyVersion() at /home/wl-dr/.composer/vendor/fxp/composer-asset-plugin/Repository/VcsPackageFilter.php:164
 Fxp\Composer\AssetPlugin\Repository\VcsPackageFilter->satisfy() at /home/wl-dr/.composer/vendor/fxp/composer-asset-plugin/Repository/VcsPackageFilter.php:151
 Fxp\Composer\AssetPlugin\Repository\VcsPackageFilter->doSkip() at /home/wl-dr/.composer/vendor/fxp/composer-asset-plugin/Repository/VcsPackageFilter.php:131
 Fxp\Composer\AssetPlugin\Repository\VcsPackageFilter->skip() at /home/wl-dr/.composer/vendor/fxp/composer-asset-plugin/Repository/AssetVcsRepository.php:83
 Fxp\Composer\AssetPlugin\Repository\AssetVcsRepository->initTag() at /home/wl-dr/.composer/vendor/fxp/composer-asset-plugin/Repository/AssetVcsRepository.php:65
 Fxp\Composer\AssetPlugin\Repository\AssetVcsRepository->initTags() at /home/wl-dr/.composer/vendor/fxp/composer-asset-plugin/Repository/AssetVcsRepository.php:44
 Fxp\Composer\AssetPlugin\Repository\AssetVcsRepository->initialize() at phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:179
 Composer\Repository\ArrayRepository->getPackages() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:104
 Composer\DependencyResolver\Pool->addRepository() at /home/wl-dr/.composer/vendor/fxp/composer-asset-plugin/Repository/Util.php:60
 Fxp\Composer\AssetPlugin\Repository\Util::addRepositoryInstance() at /home/wl-dr/.composer/vendor/fxp/composer-asset-plugin/Repository/Util.php:39
 Fxp\Composer\AssetPlugin\Repository\Util::addRepository() at /home/wl-dr/.composer/vendor/fxp/composer-asset-plugin/Repository/AbstractAssetsRepository.php:139
 Fxp\Composer\AssetPlugin\Repository\AbstractAssetsRepository->whatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:199
 Composer\DependencyResolver\Pool->computeWhatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:188
 Composer\DependencyResolver\Pool->whatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleSetGenerator.php:168
 Composer\DependencyResolver\RuleSetGenerator->whitelistFromPackage() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleSetGenerator.php:322
 Composer\DependencyResolver\RuleSetGenerator->getRulesFor() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php:208
 Composer\DependencyResolver\Solver->solve() at phar:///usr/local/bin/composer/src/Composer/Installer.php:515
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:219
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/RequireCommand.php:170
 Composer\Command\RequireCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:166
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:99
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:25

require [--dev] [--prefer-source] [--prefer-dist] [--no-plugins] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

By the way, I tried to install different packages and the same error occurred.

**Comment by Seldaek** [comment]
It seems to be related to a version or something that is provided by the fxp assets plugin.

**Comment by Seldaek** [comment]
I mean.. please report it over at https://github.com/francoispluchino/composer-asset-plugin/issues and if you do have more details for us we can maybe look at a fix if there is indeed a bug, but AFAIK everything works fine in composer using packagist.

**Comment by curry684** [comment]
FXP has a tendency to break on every Composer update, same error in #4957. Not much we can do about it - it 'hacks' into Composer at very low level, and as it's a reverse dependency (Composer installs it instead of other way around) it's on them to keep it up to date with changes on this end asap.

**Comment by curry684** [comment]
Solution at https://github.com/francoispluchino/composer-asset-plugin/issues/191#issuecomment-188842380 btw.

**Comment by dmitriy-luch** [comment]
Thanks. Update of fxp assets plugin to dev-master resolved the issue.
Sorry to bother you.
