### ISSUE TITLE
Path repo: need to be able to symlink based on env

### ISSUE THREAD

**Issue by appeltaert** [composer/composer#5003]
The path repo is a good solution for the monolithic repos and local development without needing to resolve to manual symlinking or working in the vendor map.

But I have a problem with it atm, deployment often involves `releases` and a `current` src folder so that you can revert to a previous version when opted for. Now this wouldn't be a problem with symlinks off, but you need symlinks to be on in the dev environment.. So either im doing it wrong?

Maybe some option for the extras?

**Comment by appeltaert** [comment]
Not just that, but this would also mean clones of repos that might have no meaning to exist on its own, like core libraries on a production server.

Being able to change repository locations based on dev would be a solution too. But im probably doing it wrong, asking for dev-repos would be evil..

**Comment by Seldaek** [comment]
I am not sure I understood what you're saying, but you could add the path repo in your global config for example to make it "local" only somehow, except then the lock files you generate won't be installable by others I think, so that's also not great. If you decide to use path repo you gotta use it in prod as well I suppose. Maybe other people actually using it have more clue :)

**Comment by curry684** [comment]
You gave the answer yourself partially:

> The path repo is a good solution for the monolithic repos and local development

It is imho mostly the second. The path repo allows you to easily develop multiple interdependent packages on a local machine without having to update all the time. It was most certainly never a real good fit for actual production deployments, as it introduces messy version constraints and vague local filesystem dependencies that do not belong in a controlled environment.

There are several outstanding feature requests for config file inheritance, that could solve this easily by having a `composer-dev.json` which you could use on the dev machine, and which would extend the real `composer.json` by just adding the path repository. This way your production environment would remain pure.

**Comment by Seldaek** [comment]
@curry684 that's only assuming the lock file for prod is not created on a dev machine but on some build box without path repo... Not great IMO.

**Comment by curry684** [comment]
Essentially path repos are a mess (or one waiting to happen) when not used only for local development hehe. It's brilliant for that though.

For deploying monolithic repos you're likely still better off with package repo instead, or just Satis.

**Comment by appeltaert** [comment]
@Seldaek Sry I should've posted this on stackoverflow, but while we are on it.. I got project X that relies on company libs A,B,[..]. Workflow right now looks like this:

1. Startup script that `rm -f company/*` and symlinks for company/* to the local sources, since changes are usually made on both sides.

2. Do work on both sides, commit and push.

3. Deployment:

- Remove the symlinks and update company/*
- Update company/*
- [Finite other common deployment tasks]
- Then the new source is cloned in a `current` directory, old source is moved to `releases/datesomething`

Now locally the path repo would be perfectly fine, but for remote it's not practical.

**Problems**

**A)** The relative directory isn't the same in common deployment strategies.

**Local**

```
Folder
  > Project X
  > Lib A
  > Lib ...
```
**Remote**

```
Folder
  > Project X
    > current
    > releases
    > shared
    > ...
  > Lib A
  > Lib ...
```

**B)** I would need those libs to be cloned on that same server, which have no standalone use at all, just dependencies. Besides that I would need to have them updated and stuck on basically dev-master all the time.

**C**) Older releases of Project X needs to be isolated from any changes..With symlinks it's not possible to rollback.

**Possible solutions**

If somehow the path and symlink was variable by either a `composer-dev.json` or an option in the extras, it would fix the some issues.

But the most fitting solution would be the possibility to have multiple sources for a repo such as:

```
"repositories": [
  {
    "type": "path",
    "url": "../libA.git"
  },
  {
    "type": "vcs",
    "url": "git@somevcs:...libA.git"
  },
}
```

Not that this fixes `path` in remote, but it still allows to use a normal vcs as a fallback option. But this doesn't seem possible? The path is written to .lock. Do I need to take a look at Satis?

**Comment by Seldaek** [comment]
I don't really know what we can do to address this. It seems to be a workflow issue and the proposed fixes are quite conflicting with the way composer works.
