### ISSUE TITLE
composer create-project does not work with custom repositories without SSL

### ISSUE THREAD

**Issue by ArminVieweg** [composer/composer#5004]
Since I've updated to latest composer version I get the error

>  Your configuration does not allow connection to http://insecure.composer-repo.org. See https://getcomposer.org/doc/06-config.md#secure-http for details.

when I perform

`composer create-project vendor/project ./ --repository-url=http://insecure.composer-repo.org`.

But I am not able to set **secure-http** to **false** for the create-project command. I can put it into composer.json but then my *vendor/project* package is a dependency instead of a created project.

Also set the flag in global config has no effect.

Is there a way to use the **create-project** command with insecure repositories?

**Comment by ClaudiuCreanga** [comment]
`composer config -g secure-http false `
works for me, but wonder why they stop accepting http? Plenty of host providers accross the world still don't support ssl.

**Comment by stof** [comment]
@ClaudiuCreanga the idea is to be more secure by default. and thanks to Let'sEncrypt, supporting SSL is not hard anymore (and is free).
Note that composer does not force you to support SSL on the project you are building. It expects SSL support (by default) for the hosting of packages.

**Comment by ArminVieweg** [comment]
Thanks @ClaudiuCreanga this works for me as well. I tried `composer global config` first, I didn't know that -g does not equal global.
