### ISSUE TITLE
Windows installer does not see Denwer's virtual drive

### ISSUE THREAD

**Issue by Marat-Tanalin** [composer/composer#5007]
Cannot install Composer using its Windows installer: it requests for php.exe location, but just does not see the virtual drive created by [Denwer](http://www.denwer.ru/) (WAMP-type web-server popular in Russia).

FWIW, Denwer uses Windows' built-in `subst.exe` utility to create virtual drives.

**Comment by curry684** [comment]
Please report this issue in https://github.com/composer/windows-setup instead.

**Comment by Marat-Tanalin** [comment]
[Done](https://github.com/composer/windows-setup/issues/49), thanks.
