### ISSUE TITLE
mixed up unrelated packages when php composer.phar require njasm/container

### ISSUE THREAD

**Issue by njasm** [composer/composer#5011]
hello,
suddenly users of my package ``njasm/container`` are unable to install the package through composer.
my package is being mixed up with ``vaibhavpandeyvpz/katora`` since last few weeks.

I've never used nor reference that package and the only package in common is the ``container-interop/container-interop``

Example of a composer.json:
```json
{
    "require": {
        "njasm/container": "1.2.11"
    }
}
```  
Example from command line:
```bash
[admin@nms001 container-teste]$ php composer.phar require njasm/container 1.2.11
Warning: This development build of composer is over 30 days old. It is recommended to update it by running "composer.phar self-update" to get the latest version.
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)



  [RuntimeException]
  Could not load package vaibhavpandeyvpz/katora in http://packagist.org: [UnexpectedValueExcepti
  on] Could not parse version constraint ^1.1: Invalid version string "^1.1"
```

in fact that parse error is found on the katora package composer.json, but my question is why installing my package, is composer searching for that one?

thanks for the help.

**Comment by Seldaek** [comment]
Please upgrade composer to latest version because yours is over one year old and is missing some essential features which is what causes this bug. You can use "composer selfupdate" for that.

**Comment by njasm** [comment]
@Seldaek updating composer seems to fix the issue!

thanks!
