### ISSUE TITLE
Semantic version constraint @dev doesn't give the expected result

### ISSUE THREAD

**Issue by patkar** [composer/composer#5013]
| Q | A
| --- | ---
| Bug? | yes
| Version Used | `3cea62b6ed8220cca53721a3210fbf64a08170dc`
| Feature request? | no

#### Expected Behavior

For testing bundles on Travis with the latest 3.x.y-dev version of Symfony I execute

    composer require symfony/symfony:^3.0@dev --no-update

and a following `composer update` should install the current 3.1.x-dev and if in the future available 3.2.x-dev and so on. Thus I don't need do update all Travis configs every half year for the new minor release.

#### Actual Behavior

Actually I only get 3.0.x-dev installed:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing symfony/filesystem (v3.0.3)
  - Removing symfony/process (v3.0.3)
  - Removing symfony/config (v3.0.3)
  - Removing symfony/dependency-injection (v3.0.3)
  - Removing symfony/translation (v3.0.3)
  - Removing symfony/templating (v3.0.3)
  - Removing symfony/stopwatch (v3.0.3)
  - Removing symfony/security-core (v3.0.3)
  - Removing symfony/security-csrf (v3.0.3)
  - Removing symfony/routing (v3.0.3)
  - Removing symfony/finder (v3.0.3)
  - Removing symfony/debug (v3.0.3)
  - Removing symfony/http-foundation (v3.0.3)
  - Removing symfony/event-dispatcher (v3.0.3)
  - Removing symfony/http-kernel (v3.0.3)
  - Removing symfony/class-loader (v3.0.3)
  - Removing symfony/asset (v3.0.3)
  - Removing symfony/framework-bundle (v3.0.3)
  - Installing doctrine/collections (v1.3.0)
    Downloading: 100%         

  - Installing doctrine/inflector (v1.1.0)
    Downloading: 100%         

  - Installing doctrine/common (v2.6.1)
    Downloading: 100%         

  - Installing twig/twig (v1.24.0)
    Downloading: 100%         

  - Installing symfony/polyfill-intl-icu (v1.1.0)
    Loading from cache

  - Removing symfony/yaml (v3.0.3)
  - Installing symfony/symfony (3.0.x-dev 4a08c88)
    Cloning 4a08c887557d00887e61554e83e3754a1335951c

Writing lock file
Generating autoload files
```

#### Steps to Reproduce

* Given the following `composer.json`:

```
{
    "name": "pulse00/ffmpeg-bundle",
    "type": "symfony-bundle",
    "description": "Symfony bundle to provide PHP-FFmpeg as a Symfony service (https://github.com/alchemy-fr/PHP-FFmpeg)",
    "keywords": ["multimedia", "video processing", "video", "audio processing", "audio", "avconv", "ffmpeg", "avprobe", "ffprobe"],
    "license": "MIT",
    "authors": [
        {
            "name": "Robert Gruendler",
            "email": "r.gruendler@gmail.com"
        }
    ],
    "require": {
        "php": "^5.3.9 || ^7.0",
        "php-ffmpeg/php-ffmpeg": "^0.5 || ^0.6",
        "symfony/dependency-injection": "^2.3 || ^3.0",
        "symfony/framework-bundle": "^2.3 || ^3.0"
    },
    "require-dev": {
        "matthiasnoback/symfony-dependency-injection-test": "~0.7",
        "phpunit/phpunit": "^4.8"
    },
    "autoload": {
        "psr-4": { "Dubture\\FFmpegBundle\\": "" }
    }
}
```

* Execute `composer require symfony/symfony:^3.0@dev --no-update`

* Modifies it to:

```
    [...]
    "require": {
        "php": "^5.3.9 || ^7.0",
        "php-ffmpeg/php-ffmpeg": "^0.5 || ^0.6",
        "symfony/dependency-injection": "^2.3 || ^3.0",
        "symfony/framework-bundle": "^2.3 || ^3.0",
        "symfony/symfony": "^3.0@dev"
    },
    [...]
```

* And `composer update` installs `3.0.x-dev`

```
  - Removing symfony/yaml (v3.0.3)
  - Installing symfony/symfony (3.0.x-dev 4a08c88)
    Cloning 4a08c887557d00887e61554e83e3754a1335951c
```

##### Alternate try

I even tried it with a simplified one:

```
    [...]
    "require": {
        "php": "^5.3.9 || ^7.0",
        "php-ffmpeg/php-ffmpeg": "^0.5 || ^0.6",
        "symfony/symfony": "^2.3 || ^3.0"
    },
    [...]
```

And then `composer require symfony/symfony:^3.0@dev --no-update && composer update`, same result.

**Comment by Seldaek** [comment]
With only the requires from the simplified use case, after installing then running the require & update, I get:

> - Updating symfony/symfony (v3.0.3) to symfony/symfony (dev-master b868feb)
> - Installing psr/cache (1.0.0)

This looks like a correct outcome to me. However when adding the require-dev, then it fails and installs 3.0.x-dev as you mentioned.

`composer why-not symfony/symfony:3.1.x-dev` yields nothing which is strange.

Trying with master shows what requires symfony, and indeed nothing seems to block 3.1
```
composer why-not symfony/symfony:dev-master -v
__root__                                          dev-master  requires  symfony/symfony (^3.0@dev)
alchemy/binary-driver                             1.6.0       requires  symfony/process (^2.0|^3.0)
matthiasnoback/symfony-config-test                v1.4.0      requires  symfony/config (~2.0|~3.0)
matthiasnoback/symfony-dependency-injection-test  v0.7.6      requires  symfony/dependency-injection (^2.0.5|~3.0)
neutron/temporary-filesystem                      2.2.0       requires  symfony/filesystem (^2.3 || ^3.0)
phpunit/phpunit                                   4.8.23      requires  symfony/yaml (~2.1|~3.0)
symfony/polyfill-intl-icu                         v1.1.0      requires  symfony/intl (~2.3|~3.0)
```

--ignore-platform-reqs also does not change anything, so it's really starting to look like a bug to me.

**Comment by Seldaek** [comment]
@naderman if you get a chance to have a look.. I hope I didn't miss something silly.

**Comment by naderman** [comment]
symfony 3.1.x-dev conflicts with "phpdocumentor/reflection-docblock": "<3.0" which is a requirement of PHPUnit 4.8.

See https://github.com/symfony/symfony/blob/master/composer.json#L92

So if you want phpunit 4.8 you can't also have symfony 3.1.x-dev.

**Comment by naderman** [comment]
@Seldaek maybe we should entirely disallow running update without --no-dev (would simplify the code as well) to avoid potential differences in log files caused by running update with or without --no-dev

**Comment by Seldaek** [comment]
I am not sure how the --no-dev relates to this issue at all. But yeah we generate a pretty unusable lock file when you do that and it warns you then when you try to install with dev, so I don't think the flag is a big issue.

Regarding the conflict.. It seems to me like the `why-not` command should have shown this. Room for improvement there :)

**Comment by naderman** [comment]
@Seldaek basically, the definition of require-dev items influences how the regular requirements are fulfilled. If you run update with --no-dev you'll end up with symfony 3.1.x, if you run with --dev (or default) you end up with symfony 3.0.x. Since dev dependencies are considered "independent" of regular dependencies, I don't think that difference is desired behaviour.

**Comment by naderman** [comment]
Hence --dev/--no-dev should ony impact installation, not lock generation. Only way this bug is related is by highlighting the (potentially non-obvious) differences dev-requirements can make to dependency resolution of regular requirements.

**Comment by Seldaek** [comment]
Much better :)

```
$ c why-not symfony/symfony:3.1.x-dev
symfony/symfony  3.1.x-dev  conflicts  phpdocumentor/reflection-docblock (<3.0)
```

@naderman I'd say open new issue or PR if you really want to do this. I don't think it's really a big issue (at least it hasn't seemed like on according to support issues we get..) and I am sure removing the flag will get *someone* *somewhere* to go crazy :)

**Comment by patkar** [comment]
> symfony 3.1.x-dev conflicts with "phpdocumentor/reflection-docblock": "<3.0" which is a requirement of PHPUnit 4.8.

Ah, damn. Shame on me, I didn't see that. Thanks @naderman for the hint and @Seldaek for fixing why-not :)

**Comment by curry684** [comment]
> It seems to me like the why-not command should have shown this. Room for improvement there :)

I didn't implement that there as it's inherently flawed and this is one of the few use cases where it's applicable hehe, as both packages are already accidentally loaded. The problem with conflicts detection is mainly that you also want to be able to `why-not <not-installed-package>` and we'd need to do a full solution for that.

This is really part of a bigger problem that affects more front-end commands that we have to be able to do a real solution to implement certain behaviors easily. Which all in the end comes down to that we really have to work on that middleware between the commands and the core.

**Comment by Seldaek** [comment]
Yeah I can see that it won't work in many cases for sure but still more coverage is a good thing.

**Comment by curry684** [comment]
Oh agreed on that, I honestly didn't expect this specific case to actually happen in the wild (one version of a package conflicting with one that's needed in another version of the same package), that's why I didn't bother with it at first hehe.
