### ISSUE TITLE
unzip warnings should be ignored (non-Windows platform)

### ISSUE THREAD

**Issue by nazar-pc** [composer/composer#5014]
unzip might return status code `1` instead of `0` in case of warnings. Warnings are not critical (in my case this is just and empty but valid zip file), so I think this should be taken into account.
This issue happens with `1.0.0-beta1` while worked fine with git version `1.0-dev (6eb50623e6e00bac4ed893802836e50b62c83434) 2016-02-08 19:03:10`.

It can be fixed by splitting [command](https://github.com/composer/composer/blob/master/src/Composer/Downloader/ZipDownloader.php#L62) into 2 stages by checking exit code of both commands separately, while allowing `unzip` to have status code either `0` or `1`, because I'm afraid a bit of Bash will not be cross-platform.

**Comment by Seldaek** [comment]
I'm not sure.. docs say

> 1 one or more warning errors were encountered, but processing completed successfully anyway. This includes zipfiles where one or more files was skipped due to unsupported compression method or encryption with an unknown password.

This includes a bunch of pretty valid sounding errors or things you'd not want to ignore.

Can I ask why you're installing empty zip files anyway? That sounds a bit strange.

**Comment by nazar-pc** [comment]
I'm generating `composer.json` on fly with structure like following:
```json
{
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "modules/Composer",
                "version": "1.0.0-beta1+cs-1.0.0",
                "require": [],
                "dist": {
                    "url": "/web/cscms.org/www/components/modules/Composer/empty.zip",
                    "type": "zip"
                },
                "replace": []
            }
        },
        {
            "type": "package",
            "package": {
                "name": "modules/Http_server",
                "version": "0.20.1+build-34",
                "require": {
                    "react/http": "0.4.*"
                },
                "dist": {
                    "url": "/web/cscms.org/www/components/modules/Composer/empty.zip",
                    "type": "zip"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "modules/WebSockets",
                "version": "0.47.2+build-74",
                "require": {
                    "cboden/ratchet": "0.3.*",
                    "ratchet/pawl": "0.1.*"
                },
                "dist": {
                    "url": "/web/cscms.org/www/components/modules/Composer/empty.zip",
                    "type": "zip"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "plugins/Composer_assets",
                "version": "1.2.0+build-22",
                "require": {
                    "fxp/composer-asset-plugin": "^1.1.2",
                    "oyejorge/less.php": "~1.7",
                    "leafo/scssphp": "^0.6.2"
                },
                "dist": {
                    "url": "/web/cscms.org/www/components/modules/Composer/empty.zip",
                    "type": "zip"
                },
                "replace": []
            }
        }
    ],
    "require": {
        "modules/Composer": "1.0.0-beta1+cs-1.0.0@alpha",
        "modules/Http_server": "0.20.1+build-34@alpha",
        "modules/WebSockets": "0.47.2+build-74@alpha",
        "plugins/Composer_assets": "1.2.0+build-22@alpha"
    }
}
```
My primary goal is to basically normalize requirements that are taken from multiple sources and do not ignore some of them, so I can't merge them into single array easily (or I'm not aware how to do it reliably without losing any restrictions). Simpler alternative would be to allow packages without `dist` key.

**Comment by Seldaek** [comment]
OK I see, in that case what you want to do is to put a type:metapackage inside the package definitions, which will make it skip the installation of the packages' dist. Then you can skip dist definition too. e.g.

```
{
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "modules/Composer",
                "version": "1.0.0-beta1+cs-1.0.0",
                "require": [],
                "type": "metapackage"
            }
        }
    ]
}
```
