### ISSUE TITLE
show "<packagename>" gives "InvalidArgumentException"

### ISSUE THREAD

**Issue by Fruchuxs** [composer/composer#5015]
Hello everyone,

I use composer with Netbeans and Netbeans runs the following command ( e.g. if I select the "jms/serializer" lib):

`composer.phar "--no-interaction" "--no-ansi" "show" "jms/serializer"`

So this has worked at all times before, but I have used an outdated composer version. I decided to run self update to get the newest version of composer. Now I get with the same command the following error:

```
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug

                                    
  [InvalidArgumentException]        
  Package jms/serializer not found  
                                    

show [--all] [-i|--installed] [-p|--platform] [-a|--available] [-s|--self] [-N|--name-only] [-P|--path] [-t|--tree] [--] [<package>] [<version>]
```

I have pointed out, if I use the --all parameter, it works as before.
Is that an intended behavior?

**Comment by Seldaek** [comment]
Yes we changed the show command to only show installed packages by default as it makes it a lot faster and it's usually what people mean. So I think the netbeans composer handling probably would need to be adjusted if the goal is to show info from any package there.

**Comment by Fruchuxs** [comment]
Okay, thank you.
I only mentioned netbeans to explain the whole context. It's obvious that the netbeans module needs to be adjusted. I will create a ticket in the NB Tracker - but I would ask here before.
