### ISSUE TITLE
CLI 'require-dev' command

### ISSUE THREAD

**Issue by cjaoude** [composer/composer#5018]
How about adding a `require-dev` as a command in the CLI ?

`composer require yada/yada --dev`
vs
`composer require-dev yada/yada`

it just seems easier, and for me at least, less chance of forgetting the --dev flag, then having to edit the composer.json

tnx

**Comment by Seldaek** [comment]
IMO require --dev is the way to go, it's not really warranting a new command just to save 2chars :/
