### ISSUE TITLE
Rollback doesn't delete backup file if corrupted

### ISSUE THREAD

**Issue by vlakoff** [composer/composer#5020]
When doing `composer self-update --rollback`, if Composer detects that the backup file is corrupted, it displays this error:

> $io->writeError('<error>The backup file was corrupted ('.$err->getMessage().') **and has been removed**.</error>');

However, because of a conditional in `setLocalPhar` method, the file isn't deleted actually.

Just tell me what is the expected behaviour and I could submit a PR accordingly. When trying to rollback to the latest backup, and that file is corrupted, should it be deleted?

See: [SelfUpdateCommand.php](https://github.com/composer/composer/blob/master/src/Composer/Command/SelfUpdateCommand.php)

**Comment by alcohol** [comment]
It seems to me this message is wrong. Normally a tmp file would be downloaded, and the current active phar would be moved to the target backup location, after which the tmp file replaces the current file. But in the case of a rollback the tmp file is a backup file, so there is no backup target.

It does not remove anything in the case that the tmp file (existing backup) is corrupted. I think the error message should be adjusted for this; or alternatively in case of an error we could remove the corrupted file and retry with an older backup.

I would go with simply adjusting the error message though.

**Comment by vlakoff** [comment]
Agree. A file corruption is very unlikely to happen at this stage (download are checked with signature, and only valid phars are copied to backup). Though, if ever it was to happen, making sure the corrupted file is not installed is sufficient.
