### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by razmo** [composer/composer#5022]
Hi,

After update of composer i have this error :
```
The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
```

The version is fe134d3359ff6533f5462743cada35eabaf2350f.

**Comment by alexbilbie** [comment]
If you run `openssl s_client -connect packagist.org:443` and you get an error then your CA certificate store is likely out of date.

Run `[brew / apt-get / yum] install ca-certificates`

**Comment by razmo** [comment]
@alexbilbie thx for your fast answer.
There is no package named ```install ca-certificates``` in homebrew

**Comment by alcohol** [comment]
I think on OSX you should install the latest version of openssl and then reinstall php with the homebrew openssl lib.
