### ISSUE TITLE
Dependency clash - guzzlehttp/guzzle

### ISSUE THREAD

**Issue by SimonDeconde** [composer/composer#5023]
Hi there

I'm trying to use the "predictionio/predictionio" in my project, but I have a Guzzle dependency issue with the "zendesk/zendesk_api_client_php" package that I'm also using.

predictionio/predictionio requires guzzlehttp/guzzle: ~5.0
zendesk/zendesk_api_client_php requires guzzlehttp/guzzle: ~6.0

Which results in a composer error: "Can only install one of: guzzlehttp/guzzle[6.1.0, 5.3.0]."

Is there a way around this?

Thanks for your help.

**Comment by barryvdh** [comment]
Yes, update either of those packages to support both versions, or convince predictionio to upgrade.

**Comment by SimonDeconde** [comment]
Thanks Barry. 
I've sent a request ticket to the predictionio team, but I'm not confident they'll upgrade at all, as the Guzzle 5.x version is maintained for now.

When you say "update either of those packages to support both version", what do you mean exactly?

**Comment by barryvdh** [comment]
I mean, open an issue on the repositories ;) Depending on the use case, the differences between 5 and 6 can be small enough to support 2 versions. But that's an issue with those 2 packages, so I suggest you close this and continue on the issue you created there.

**Comment by SimonDeconde** [comment]
Thanks for the clarification. I'll try to lobby the predictionio team for upgrade. Thanks for your help!
