### ISSUE TITLE
fatal: Unable to look up <MYUSERNAME>(port 9418) (No such host is known. )

### ISSUE THREAD

**Issue by rishabhsrana** [composer/composer#5027]
Hi there,

I created a new repo on myGithub as "webdevS2016". Now I trying to push code to OpenShift which is in sync with Github, BUT it throws the error:

"fatal: Unable to look up rishabhsrana (port 9418) (No such host is known. )"

I have trying to resolve this relentlessly but couldn't do it.

Kindly help. Your help would be much appreciated.

Regards,
Rishabh

**Comment by curry684** [comment]
Your error is related to you pushing to the host `rishabhshrana` which cannot be resolved on your local computer. You should use a fully qualified domain name instead, and check the syntax you're using for your `git push` command.

This issue has nothing to do with Composer.
