### ISSUE TITLE
Exclude files from autoload_files.php ?

### ISSUE THREAD

**Issue by danimalweb** [composer/composer#5029]
I have a dependancy which has an autoload files block in their composer.json. For example:

```
"autoload": {
    "files": ["ot-loader.php"]
  }
```

Is there a way I can exclude this file from being autoloaded? I've had a play around with exclude-from-classmap but I don't think can exclude files like this?

```
"exclude-from-classmap": [
      "/vendor/valendesigns/option-tree/ot-loader.php"
    ],
```

Thanks! :)

**Comment by Seldaek** [comment]
Nope there is no way to do this.. and really I don't see why you'd need to. I don't think we want to allow this level of micro-management of the dependencies as it's bound to fail eventually when you update them.

**Comment by danimalweb** [comment]
FYI my use case was that I have a dependency which has some WordPress specific functionality and another dependency which needs to be run outside of the WordPress environment (e.g. phpcs via a CLI).

With both of these autoloaded, calling my non-WordPress dependency results in many fatal PHP errors (```Fatal error: Call to undefined function```) when called.

I was simply looking for a way to keep the dependencies together in /vendor but not autoload the WordPress one for obvious reasons.

Thanks anyway.

**Comment by jawittdesigns** [comment]
This is issue may have been closed, but I totally agree with @danimalweb. I've ran into this same type of issue before that forced me to exclude the composer autoload and I had to make my own that did give my that type of control. 

Having the option to exclude files would be a welcomed feature.

**Comment by mcaskill** [comment]
I've also run into this issue with a "theme dependency" (that expects to be bootstrapped inside a theme directory) but the `composer.json` was outside of WordPress.

Ultimately, I developed a Composer plugin—[mcaskill/composer-exclude-files](https://packagist.org/packages/mcaskill/composer-exclude-files)—that allows one to ignore a package's `files` from inclusion in `autoload_files.php`. This way, one can (if they need it) explicitly require those `files` later on where needed.

Example:

`composer.json`
```json
"require": {
  "soberwp/controller": "~9.0.0-beta.4"
},
"autoload": {
  "exclude-from-files": [
     "soberwp/controller/controller.php"
  ]
}
```

`/public/themes/foobar/functions.php`
```php
require $vendorDir . '/soberwp/controller/controller.php'
```
