### ISSUE TITLE
Not install mongodb

### ISSUE THREAD

**Issue by Vagabondtq** [composer/composer#5033]
When i run: _composer require mongodb/mongodb_
has Problem 1:

>     - mongodb/mongodb 1.0.1 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.0.0 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
>     - Installation request for mongodb/mongodb ^1.0 -> satisfiable by mongodb/mongodb[1.0.0, 1.0.1].

I'm try: **composer show -p**

> .....
> ext-json            1.3.2     The json PHP extension
> ext-libxml          0         The libxml PHP extension
> ext-mbstring        0         The mbstring PHP extension
> ext-mcrypt          0         The mcrypt PHP extension
> ext-mhash           0         The mhash PHP extension
> ext-mongo           1.6.12    The mongo PHP extension
> ext-mysql           1.0       The mysql PHP extension
> ext-mysqli          0.1       The mysqli PHP extension
> ext-openssl         0         The openssl PHP extension
> ext-pcntl           0         The pcntl PHP extension
> ext-pcre            0         The pcre PHP extension
> ext-PDO             1.0.4dev  The PDO PHP extension
> .....

Why?

**Comment by Vagabondtq** [comment]
i'm run:

`sudo apt-get install libpcre3-dev`

then:
`pecl install mongodb`

and add: `extension=mongodb.so` to bottom line of `cli/php.ini`

is ok

**Comment by curry684** [comment]
This is actually in the [README](https://packagist.org/packages/mongodb/mongodb) for `mongodb/mongodb`.
