### ISSUE TITLE
[question] Install fail, but update is successfull

### ISSUE THREAD

**Issue by jmleroux** [composer/composer#5034]
Hello,

I thought that `composer install` was the same thing as `composer update` when there is no composer.lock file.

But it seems i was wrong. :(

I struggled to test a composer.json with the Akeneo project : 

```
{
    "name": "jml/foobar",
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/akeneo/pim-community-dev.git",
            "branch": "master"
        }
    ],
    "require": {
        "akeneo/pim-community-dev": "1.5.*",
        "doctrine/migrations": "1.0.0-alpha3@alpha"
    }
}
```

I created a folder with just this file and tried to install it with `composer install` and i always get the same error : 

> Loading composer repositories with package information
> Installing dependencies (including require-dev)                                           
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - akeneo/pim-community-dev v1.5.1 requires doctrine/doctrine-bundle 1.2.0 -> satisfiable by doctrine/doctrine-bundle[v1.2.0].
>     - akeneo/pim-community-dev v1.5.0 requires doctrine/doctrine-bundle 1.2.0 -> satisfiable by doctrine/doctrine-bundle[v1.2.0].
>     - Conclusion: don't install doctrine/doctrine-bundle v1.2.0
>     - Installation request for akeneo/pim-community-dev 1.5.* -> satisfiable by akeneo/pim-community-dev[v1.5.1, v1.5.0].

I have searched for bad dependencies, but didn't find them.
And finally, i just tried a `composer update` and it worked !

So what can be the difference between these two commands and why would `install` fail ?

Thanks for reading,

JM

**Comment by fitn** [comment]
Just to link it with the PR: https://github.com/composer/composer/issues/5034
