### ISSUE TITLE
Composer can't find commands from vendor/bin on windows

### ISSUE THREAD

**Issue by Nayjest** [composer/composer#5045]
### Overview
When running  commands defined in "scripts" section from vendor/bin via `composer <command>` on windows, composer can't find it.

### Environment
**OS:** Windows 7
**PHP:** php 5.6.12
**Composer**:  
* 1.0-dev (8bf46768f3f5397c259b77321b2e887a53624adb) 2016-03-10 16:31:09 installed locally (.phar)
* 1.0-dev (1dce6442ed2518855d096d1123f04472d9b6f764) 2016-03-11 10:30:26 installed globally via ComposerSetup.exe

### Steps to reproduce
1. Create composer package
2. Add package that has scripts in "bin" section of its composer.json to dependencies (I used phpunit)
```javascript
"require": {
    "phpunit/phpunit": "^4||^5"
}
```
3. Install dependencies
4. Define command in composer.json of created package
```javascript
"scripts": {
       "test": "phpunit"
}
```
5. Run command (`php composer.phar test -vvv` in my example)

### Expected result
Command is executed

### Actual result
phpunit command is not found

##### Output example
```
C:\Users\Vitaliy Stepanenko\Dropbox\!CODE\lib\testing-helpers>php composer.phar test -vvv
Reading ./composer.json
Loading config file C:/Users/Vitaliy Stepanenko/AppData/Roaming/Composer/config.json
Loading config file C:/Users/Vitaliy Stepanenko/AppData/Roaming/Composer/auth.json
Loading config file ./composer.json
Checking CA file C:\Users\Vitaliy Stepanenko\AppData\Local\Temp\composer-cacert-39eaf16e26c08cc90d728865f1c60406ee5d864d5963
f72ede2a1cbb127f95ca.pem
Executing command (C:\Users\Vitaliy Stepanenko\Dropbox\!CODE\lib\testing-helpers): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: C:/Users/Vitaliy Stepanenko/AppData/Roaming/C
omposer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" s
ection
Reading C:\Users\Vitaliy Stepanenko\Dropbox\!CODE\lib\testing-helpers/vendor/composer/installed.json
> test: phpunit
Executing command (CWD): phpunit
"phpunit" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
Script phpunit handling the test event returned with an error


  [RuntimeException]
  Error Output: "phpunit" не является внутренней или внешней
  командой, исполняемой программой или пакетным файлом.


Exception trace:
 () at phar://C:/Users/Vitaliy Stepanenko/Dropbox/!CODE/lib/testing-helpers/composer.phar/src/Composer/EventDispatcher/Event
Dispatcher.php:204
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar://C:/Users/Vitaliy Stepanenko/Dropbox/!CODE/lib/testing-help
ers/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:94
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar://C:/Users/Vitaliy Stepanenko/Dropbox/!CODE/lib/testing-
helpers/composer.phar/src/Composer/Command/ScriptAliasCommand.php:59
 Composer\Command\ScriptAliasCommand->execute() at phar://C:/Users/Vitaliy Stepanenko/Dropbox/!CODE/lib/testing-helpers/comp
oser.phar/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar://C:/Users/Vitaliy Stepanenko/Dropbox/!CODE/lib/testing-helpers/co
mposer.phar/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/Users/Vitaliy Stepanenko/Dropbox/!CODE/lib/testing-helpe
rs/composer.phar/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar://C:/Users/Vitaliy Stepanenko/Dropbox/!CODE/lib/testing-helpers/comp
oser.phar/src/Composer/Console/Application.php:166
 Composer\Console\Application->doRun() at phar://C:/Users/Vitaliy Stepanenko/Dropbox/!CODE/lib/testing-helpers/composer.phar
/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar://C:/Users/Vitaliy Stepanenko/Dropbox/!CODE/lib/testing-helpers/compos
er.phar/src/Composer/Console/Application.php:99
 Composer\Console\Application->run() at phar://C:/Users/Vitaliy Stepanenko/Dropbox/!CODE/lib/testing-helpers/composer.phar/b
in/composer:43
 require() at C:\Users\Vitaliy Stepanenko\Dropbox\!CODE\lib\testing-helpers\composer.phar:25

test [--dev] [--no-dev] [--] [<args>]...

```
### Additional notes:
If I specify command as "vendor\\\\bin\\\\phpunit" it works, but not for unix, "vendor/bin/phpunit" does not works for windows. So the only way to specify command that will work for both windows and unix is "php vendor/phpunit/phpunit/phpunit" but I have no guarantee that vendor will keep this file in same place in further releases becouse it's not designed to be used this way.

**Comment by Nayjest** [comment]
**UPD**: This does not works also for my another project (it worked before!).
I use there local composer.phar: 1.0-dev (f2d606ae0c705907d8bfa1c6f884bced1255b827) 2016-03-03 12:44:49

**Looks like something broke after global composer installation via SomposerSetup.exe**

**Comment by curry684** [comment]
Known issue of the Windows Installer: https://github.com/composer/windows-setup/issues/37

**Comment by Nayjest** [comment]
@curry684 I'm not sure that it's same issue: in my case composer can't find scripts placed locally in \<project\>/vendor/bin folder

**Comment by beverloo** [comment]
I'm also seeing this on Windows 10. The `bin-dir` of the current project is not being added to the PATH when running custom scripts, which should be the case according to the documentation:

https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands

**Comment by rquadling** [comment]
I've added ``.\vendor\bin`` to my path for Windows. Should work for you.

**Comment by Seldaek** [comment]
It should definitely work without users tweaking the path themselves. AFAIK it works for me on win8. For example:

```
seld:~/monolog
$ composer exec 'echo "%PATH%"'
"C:\Users\seld\monolog\vendor\bin;C:\Users\seld\...."
```

You see the current-dir/vendor/bin was pushed on top of the PATH. Can those experiencing the issue try and run that command? `composer exec 'echo "%PATH%"'`

**Comment by Seldaek** [comment]
There was an issue where if you had only an env var called `Path` (not PATH) it wasn't recognized, this is now fixed.
