### ISSUE TITLE
Shared packages [question]

### ISSUE THREAD

**Issue by andrewtch** [composer/composer#5046]
Well, this is a bit of philosophical question, but it comes from live environment. Imagine a server, hosting multiple versions of the same app. The apps have dependencies, like so:

```
/var/www/app1.1/
/var/www/app1.1/vendor/depencency_a1.3
/var/www/app1.1/vendor/depencency_b1.0
/var/www/app1.1/vendor/depencency_c2.7

/var/www/app1.2/
/var/www/app1.2/vendor/depencency_a1.3
/var/www/app1.2/vendor/depencency_b1.1
/var/www/app1.2/vendor/depencency_c2.8

/var/www/app2.0/
/var/www/app2.0/vendor/depencency_a2.0
/var/www/app2.0/vendor/depencency_bdev-master
/var/www/app2.0/vendor/depencency_c2.9
```

The problem is that Opcache has waaaay to may vendors, and is basically going mad and not working. Is there any possibility (googled, didn't find) to make composer install vendors like that:

```
/var/www/vendors
/var/www/vendors/dependency_a
/var/www/vendors/dependency_a/1.3
/var/www/vendors/dependency_a/2.0
/var/www/vendors/depencency_b/1.0
/var/www/vendors/depencency_b/1.1
/var/www/vendors/depencency_b/dev-master

/var/www/app2.0/
/var/www/app2.0/vendor/autoload.php (with links to needed direcotries).
```

Of course, vendors are never uninstalled in this case, but this is a minor issue.

Can this be implemented without major composer rewrite?

**Comment by curry684** [comment]
This is not a scenario we remotely support natively, or would want to support. With a lot of symlink magic and path repository hackery you could probably get something like this to work, but my core question would still be *why*? All you're doing right now is moving packages, the total number of used files is still identical, so if opcache was dying before it will still die in your proposed solution. You would get a very small benefit from eliminating identical version packages in different app versions, but I doubt that's going to be all that many of them.

You're probably better off [finetuning OpCache](http://php.net/manual/en/opcache.configuration.php) I think.

**Comment by andrewtch** [comment]
The reason is about ~1000 virtual hosts sharing 5-6 common versions. So, merging vendors together reduces file count to cache ~200x.

Current "ugly" way by discarding composer at all and parse composer.lock to get up-to-date version in shared dir (generating, again, autoload by hand) reduces impact on opcache ~80-120x.

**Comment by curry684** [comment]
Oh I misunderstood then. Your example illustraties *"one big bag of dependencies"* while you're actually looking to share *identical* dependencies 200 times. You can solve that but the folder structure would end up different:
```sh
mkdir -p /var/dependencies/app1.1
cd /var/dependencies/app1.1
cp /var/www/app1.1/composer.* .
composer install
```
Now in all 200 installs of 1.1 put this in `composer.json`:
```sh
"repositories": [
  {
    "type": "path",
    "url": "/var/dependencies/app1.1"
  }
]
```
Now a `composer install/require` will not just find all dependences in the central folder, but also use **symlinks** to install them. Which are normalized by PHP internally, and thus opCache, so all should be using the same cache now.

**Comment by andrewtch** [comment]
Ok, this sounds usable, however lacks automation a bit.

I'll try this approach soon. Thanks!

**Comment by curry684** [comment]
I would try symlinking just the vendor first, it should just work as I've tested before that opCache properly normalizes away symlinks.

**Comment by alcohol** [comment]
You can automate adding repositories using

```
composer config -g repositories.foo path "/var/dependencies/app1.1/vendor/*/*"
```

I recommend using `-g` if the same user is used all the time, that way you don't have to modify the composer.json of each install.

**Comment by Seldaek** [comment]
Closing as I don't think we can really do anything here but feel free to keep discussing as needed.

**Comment by andrewtch** [comment]
Ok, fair enough. I've ended up using out approach - separate installer to parse composer.lock and install vendors to shared folder, regenerating autoload accordingly.

If this ever goes mature enough, I'll return for a review.

**Comment by Seldaek** [comment]
@andrewtch that sounds like something that'd be valuable as an open third-party tool. A bunch of people have the same problem I assume in shared-host-like settings or companies doing large scale hosting of small sites in non-containerized envs. I doubt we want to take the burden of maintaining it in composer itself but I'd definitely encourage you to release it as we can then point others who ask there and you could collaborate with them on a good solution.

**Comment by andrewtch** [comment]
@Seldaek , yes. We tried to implement it as a composer plugin, but it breaks the very idea of composer, and is not flexible by definition, so separate tool is a separate tool.

**Comment by alcohol** [comment]
Isn't the idea very similar though to what @beberlei tried to accomplish with [beberlei/composer-monorepo-plugin](/beberlei/composer-monorepo-plugin)? I know you cannot use this plugin specifically, but maybe you could write a derivative of it that serves your use-case?

**Comment by andrewtch** [comment]
My thought is that shared packages are against composer's ideology at all (even more, having multiple versions of shared packages is even more against composer itself).

I quite doubt that is ever to be a part or a plugin for composer.

**Comment by alcohol** [comment]
Composer is a dependency manager, it has no ideology. It was build with a single purpose, and has grown a lot since then. But it simply cannot provide for every imaginable use-case. That is where plugins or additional tooling come into play.

I can see lots of merits to shared dependencies. But as soon as you introduce different versions as well things become exponentially more complex. It simply is outside of the scope of what we can maintain and provide for.

**Comment by curry684** [comment]
Composer does have a single 'ideology' - it manages one project, and one project only. That makes it fundamentally unfit to manage multiple versions of the same package per project, a logical choice given the limitations of namespaces and autoloaders. Apart from that shared packages are just that: shared. Composer couldn't care less where it loads its code, as long as the autoloaders it generates can find it. The `PathRepository` is a prime example of this, sharing code out of the box, and I [still think it could solve your issues](https://github.com/composer/composer/issues/5046#issuecomment-195365008).

**Comment by alcohol** [comment]
True, you could create a metapackage (see [types](https://getcomposer.org/doc/04-schema.md#type)) which contains all your **shared** dependencies for example, then have all your projects require that metapackage instead. You could then install a project that _only_ requires said metapackage to e.g. `/srv/http/shared` (or whatever you prefer), and use that as a shared source.

**Comment by andrewtch** [comment]
Yes, and if two projects depend on symfony 2.8 (both), but one requires sonata-admin-bundle 2.1, and athoner - sonata-admin-bundle 2.2?

Having _multiple_ package versions with only matching versions shared will lead either to terribly tight binding (all to symfony 2.8) and hellish upgrades or so-called "dll hell" (or "pear hell", which composer was built to avoid).

**Comment by curry684** [comment]
Yeah hence my suggestion to keep separate trees ('metapackages') for the identical app versions. You shouldn't try to intermix those at any cost.

**Comment by andrewtch** [comment]
Ok, but with new app version metapackages double disk space (even if they are bound to the same hash), and the point still is that if 1000 apps are bound to sf 2.7.1, then I want only one copy of 2.7.1, shared.

**Comment by curry684** [comment]
```sh
mkdir -p /var/dependencies/app1.1
cd /var/dependencies/app1.1
composer require symfony/symfony:2.7.1
```

```php
$config = json_decode(file_get_contents('/var/dependencies/app1.1/composer.json'));
$config['repositories'] = [
    "type" => "path",
    "url" => "/var/dependencies/app1.1/vendor/*/*",
];
file_put_contents('/var/dependencies/app.1.1.json', json_encode($config));
```
And now in all 1000 folders:
```sh
ln -s /var/dependencies/app.1.1.json composer.json && composer install
```

**Comment by andrewtch** [comment]
Ok, I upgrade one of the instances to 1.2. It requires the same symfony 2.7.1, but twig one minor version higher.

Now I have symfony 2.7.1 installed to /var/deps/app1.1 and /var/deps/app1.2 and still a lot of symlinks.

**Comment by curry684** [comment]
Yep, but a lot less diskspace wasted than 2000. Sorry but the only way to make this as ridiculously flexible as you'd want it is to write your own resolver tool at this level.

**Comment by andrewtch** [comment]
We already have, unfortunately, not a resolver, but a plain "composer.lock" executor, to say so.

**Comment by curry684** [comment]
I think the Path repository could do that as a whole actually, but you'd need to have a preloader mirroring script in place.
