### ISSUE TITLE
Is there an option to disable symlinks on composer install?

### ISSUE THREAD

**Issue by nebulousGirl** [composer/composer#5048]
The new version now supports symlinks on Windows for "path" repositories, but because of those symlinks my build script now fails.

I use phing to create builds that copy the composer.json and lock to a new folder and make a fresh install using `--prefer-dist --no-dev --no-script`. The script also copies my application files.

The problem is that on each new build, I delete everything in the build folder and, because of the symlinks, all my packages get deleted in the process.

Is there a way to make composer install without symlinks without having to set each repository's symlinks option: https://getcomposer.org/doc/05-repositories.md#path ?

Or, maybe an easy way to get rid of them in the build process?

**Comment by nebulousGirl** [comment]
Just tried adding symlink: false to my repositories it is not working.

        {
            "type": "path",
            "url": "../shared/Pages",
            "options": {
                "symlink": false
            }
        },

**Comment by nebulousGirl** [comment]
I am using Windows 10 with the latest version of composer. I just rolled back to the older version that does not mess with my build script.

**Comment by curry684** [comment]
Looking at the code I think the `"symlink": false` option is only considered on a fresh install. If you remove the package manually and then `install` or `update` it should mirror correctly.

Not sure I like that behavior but right now it's a solution for you.

**Comment by alcohol** [comment]
Also, on another note, it sounds more to me like your cleanup job is broken. It shouldn't recurse into symlinks when deleting everything in your `build/` directory.

**Comment by curry684** [comment]
On Windows cleaning up folders should just be `rmdir <root>` as you might otherwise get screwed by hardlinks or junctions which are both used.

**Comment by pursehouse** [comment]
this gives me an error

```
Loading composer repositories with package information
[ErrorException]
stream_context_create(): options should have the form ["wrappername"]["optionname"] = $value
```

with the config...

```
"vendor/package": {
    "type": "path",
    "url": "/path/to/vendor/package",
    "options" : {
    	"symlink" : false
    }
}
```

**Comment by pitpit** [comment]
you could run:
```
COMPOSER_MIRROR_PATH_REPOS=1 composer install
```

https://getcomposer.org/doc/03-cli.md#composer-mirror-path-repos

**Comment by henrypenny** [comment]
> Just tried adding symlink: false to my repositories it is not working.
> 
> ```
>     {
>         "type": "path",
>         "url": "../shared/Pages",
>         "options": {
>             "symlink": false
>         }
>     },
> ```

I found I had to delete composer.lock and reinstall everything.

**Comment by vehsakul** [comment]
It's symlinked for me even with `COMPOSER_MIRROR_PATH_REPOS=1` or `"symlink": false`, even after a fresh install

**Comment by LeoniePhiline** [comment]
That's correct. https://getcomposer.org/doc/03-cli.md#composer-mirror-path-repos says the following:

> As it is the default strategy being set it can still be overwritten by repository options.

**Comment by jigarius** [comment]
@vehsakul try deleting the `vendor` directory and then do a `composer install`.
