### ISSUE TITLE
COMPOSER_BIN_DIR during installation should be remembered

### ISSUE THREAD

**Issue by nazar-pc** [composer/composer#5050]
For instance, I'm installing cs-fixer:
```
sudo composer COMPOSER_BIN_DIR=/usr/local/bin global remove fabpot/php-cs-fixer
```
Since I want to be able to call if from CLI without additional pain - it is installed into `/usr/local/bin`.

However, I need to add to add `COMPOSER_BIN_DIR=/usr/local/bin` during upgrade and removal as well, otherwise broken symlink will reside at `/us/local/bin` forever.

My feeling is that `COMPOSER_BIN_DIR` should be remembered on per-package basis so that:
```
sudo composer global remove fabpot/php-cs-fixer
```
Will make system clean regardless of options used during installation.

**Comment by curry684** [comment]
I think it's not `COMPOSER_BIN_DIR` that needs to be remembered but 'installed stuff for package'. So when globally installing `fabpot/php-cs-fixer` the global repo remembers that it made that symlink. Similar result, lot cleaner from an 'installer' perspective.

**Comment by alcohol** [comment]
ENV variables are only applied at runtime. If you want to change the bin-dir for consecutive runs, you need to adjust the configuration instead (`composer config bin-dir /usr/local/bin`).

**Comment by nazar-pc** [comment]
But what if configuration was changed since you've installed something last time? Expectation is that package removal will clean everything created during installation anyway, so there is still a problem here.
