### ISSUE TITLE
Autoloader.php outside vendor map

### ISSUE THREAD

**Issue by roydekleijn** [composer/composer#5051]
Hello,

I have multiple website, they all make use of the same dependencies. I hope someone can advice me to achieve the following:

```
- website1
-- classes
-- autoloader.php
-- composer.json (poiting to the class files and vendor folder)
- website2
-- classes
-- autoloader.php
-- composer.json (poiting to the class files and vendor folder)
- website3
-- classes
-- autoloader.php
-- composer.json (poiting to the class files and vendor folder)
-vendor
--all kinds of dependencies
```

Please advice

**Comment by curry684** [comment]
The second approach in https://github.com/composer/composer/issues/5046#issuecomment-195365008 should work well for this.

**Comment by Seldaek** [comment]
Closing as I don't think we can really do anything here but feel free to keep discussing as needed.
