### ISSUE TITLE
Junction content still gets deleted after composer update

### ISSUE THREAD

**Issue by TSVisopta** [composer/composer#5053]
This is similar to #4955, but happens only on consecutive updates, **if** the dependency composer.json has been updated. All the junction content is gone after this:

```
Updating dependencies (including require-dev)
  - Removing test/a (dev-master)

  [RuntimeException]
  Package test/a cannot install to "... src\Test\A" inside its source at "... src\Test\A"

Exception trace:
 () at phar://composer.phar/src/Composer/Downloader/PathDownloader.php:45
 Composer\Downloader\PathDownloader->download() at phar://composer.phar/src/Composer/Downloader/DownloadManager.php:213
 Composer\Downloader\DownloadManager->download() at phar://composer.phar/src/Composer/Downloader/DownloadManager.php:260
 Composer\Downloader\DownloadManager->update() at phar://composer.phar/src/Composer/Installer/LibraryInstaller.php:198
 Composer\Installer\LibraryInstaller->updateCode() at phar://composer.phar/src/Composer/Installer/LibraryInstaller.php:110
 Composer\Installer\LibraryInstaller->update() at phar://composer.phar/src/Composer/Installer/InstallationManager.php:172
 Composer\Installer\InstallationManager->update() at phar://composer.phar/src/Composer/Installer/InstallationManager.php:139
 Composer\Installer\InstallationManager->execute() at phar://composer.phar/src/Composer/Installer.php:592
 Composer\Installer->doInstall() at phar://composer.phar/src/Composer/Installer.php:219
 Composer\Installer->run() at phar://composer.phar/src/Composer/Command/UpdateCommand.php:173
 Composer\Command\UpdateCommand->execute() at phar://composer.phar/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar://composer.phar/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at phar://composer.phar/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar://composer.phar/src/Composer/Console/Application.php:166
 Composer\Console\Application->doRun() at phar://composer.phar/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar://composer.phar/src/Composer/Console/Application.php:99
 Composer\Console\Application->run() at phar://composer.phar/bin/composer:43
 require() at composer.phar:24
```

Junction lstat is as follows:
```php
Array
(
    [0] => 4
    [1] => 0
    [2] => 0
    [3] => 1
    [4] => 0
    [5] => 0
    [6] => 4
    [7] => 0
    [8] => 1457828772
    [9] => 1457828772
    [10] => 1457828772
    [11] => -1
    [12] => -1
    [dev] => 4
    [ino] => 0
    [mode] => 0
    [nlink] => 1
    [uid] => 0
    [gid] => 0
    [rdev] => 4
    [size] => 0
    [atime] => 1457828772
    [mtime] => 1457828772
    [ctime] => 1457828772
    [blksize] => -1
    [blocks] => -1
)
```

And this is the premise: (On Windows 10)

```json
# composer.json
{
    "repositories": [
        {"type": "path", "url": "src/Test/*"}
    ],

    "require": {
        "test/a": "@dev"
    }
}

# src/Test/A/composer.json
{
    "name": "test/a",
    "description": "test"
}
```

1. Run `composer update`
2. Modify description in src/Test/A/composer.json
3. Run `composer update`
4. src/Test/A is empty, while the junction vendor/test/a remains

**Comment by TSVisopta** [comment]
I don't know whats going on.. the problem does not appear when i try it with xdebug..

**Comment by curry684** [comment]
That's really weird, that should have no influence at all. Is it completely reproducable with xdebug disabled?

**Comment by TSVisopta** [comment]
Yes.
Running it normally (`composer update`) throws the error mentioned above.
Running it with xdebug (`php -dzend_extension=php_xdebug.dll path/to/composer update`) works just fine..

**Comment by alcohol** [comment]
Is that the exact command you use to run it with xdebug (does it contain **all** the flags you pass)?

**Comment by curry684** [comment]
Package test/a cannot install to "... src\Test\A" inside its source at "... src\Test\A"

This error is really weird inside this context. Have you created a path repository with a glob that matches both the install source and destination, ie. `"url": "vendor/yourname/*"`?

**Comment by alcohol** [comment]
Didn't even notice that yet, good catch @curry684.

However, his issue should be reproducible with the given two composer.json files and directory structure (for anyone running Windows), as that does not seem to have a conflicting source/install path.

**Comment by TSVisopta** [comment]
I removed every single xdebug configuration, so yes, thats the whole command.

The is no special repository - I can literally create these two files in a new directory, run `composer update`, modify the description and run it again for the error to appear.

**Comment by curry684** [comment]
What the problem is with the junctioning is that the Symfony filesystem components does not know them, and contains a lot of fallback code for when cleanly removing a folder fails, using RecursiveDirectoryIterator instead, obviously cleaning out the source as well as the target. Thus we needed to have some extra patches in place to prevent that from happening at all costs.

I'll try reproducing the test case when I have time, I'm running PHP7 on Win10 as well so should be possible.

**Comment by curry684** [comment]
I can't reproduce your issue sadly, but I just noticed the true culprit:
```
Updating dependencies (including require-dev)
  - Removing test/a (dev-master)
```
This is where it start going wrong, the rest is just symptoms, as it should log explicitly about the junction:
```
Updating dependencies (including require-dev)
  - Removing junction for test/a (dev-master)
```
Can you doublecheck that at that point the folder in Explorer shows a little junction arrow?

If so please share the output of:
```sh
php -r "var_dump(is_dir('vendor/test/a'));"
php -r "var_dump(is_link('vendor/test/a'));"
php -r "var_dump(lstat('vendor/test/a'));"
```

**Comment by TSVisopta** [comment]
Yes it is definitely still a junction. (Restoring the source content also restores it in the junction.)

```
is_dir('vendor/test/a') => bool(true)
is_link('vendor/test/a') => bool(false)

array(26) {
  [0]=>
  int(4)
  [1]=>
  int(0)
  [2]=>
  int(0)
  [3]=>
  int(1)
  [4]=>
  int(0)
  [5]=>
  int(0)
  [6]=>
  int(4)
  [7]=>
  int(0)
  [8]=>
  int(1457950456)
  [9]=>
  int(1457950456)
  [10]=>
  int(1457950456)
  [11]=>
  int(-1)
  [12]=>
  int(-1)
  ["dev"]=>
  int(4)
  ["ino"]=>
  int(0)
  ["mode"]=>
  int(0)
  ["nlink"]=>
  int(1)
  ["uid"]=>
  int(0)
  ["gid"]=>
  int(0)
  ["rdev"]=>
  int(4)
  ["size"]=>
  int(0)
  ["atime"]=>
  int(1457950456)
  ["mtime"]=>
  int(1457950456)
  ["ctime"]=>
  int(1457950456)
  ["blksize"]=>
  int(-1)
  ["blocks"]=>
  int(-1)
}
```

Meanwhile I've been checking on my own. If I run composer with xdebug or print anything inside Filesystem::isJunction before the !is_dir | is_link check, lstat mode is **60230** otherweise its 0.

**Comment by TSVisopta** [comment]
I meant the other way around sorry.. 60230 if I dont do anything and just check the mode after the lstat, 0 otherwise.

**Comment by curry684** [comment]
Hang on, so what you are describing now is that this script:
```php
<?php
$path = 'vendor/test/a';
var_dump(lstat($path)['mode']);
var_dump(is_dir($path) && !is_link($path));
var_dump(lstat($path)['mode']);
```
1. Gives different output depending on whether xdebug is enabled
2. Both show `true` in the middle
3. With xdebug disabled outputs 60230 and 0 first and last
4. With xdebug enabled outputs 0 both first and last

Is this correct?

**Comment by TSVisopta** [comment]
Nono, I meant composer itself, not that. I still ran the script though, and it's as expected `0`, `true`, `0` both times.

By modifying the source in Filesystem::isJunction i get the following:
`var_dump($stat['mode']);` before the return statement prints `int(60320)`

Except if I run it with xdebug or add e.g. `echo 'x';` before the !is_dir || is_link condition. Then it prints `int(0)`.

**Comment by curry684** [comment]
I understand what's happening now and will issue a PR shortly. Would appreciate if you could test it.

**Comment by Seldaek** [comment]
You can run self-update and try with latest composer now.

**Comment by TSVisopta** [comment]
Yep that works. - Thanks a lot!

**Comment by curry684** [comment]
It's a really fubar situation as a whole hehe. The problem is that without xdebug the stat cache is far more aggressive, and in this specific case you are running into the issue that Composer core itself creates a placeholder folder for all packages it wants to install, with PHP's native functions. The junctions however need to be created via ProcessExecutor as PHP has not wrapped them. So at some point during execution `vendor/test/a` was a real directory for sure, and PHP never saw it change as we went to the system. So the caches still think it's not a junction while it is during the rollback... chaos ensures, oops.

**Comment by TSVisopta** [comment]
Yea absolutely confusing.. :P
I still don't understand how printing something cleared the cache though. Especially because it had to be before the condition, which was never true - and didn't do anything before lstat itself.
Do you have any idea why that happened?

**Comment by curry684** [comment]
To be honest I haven't a clue on that haha. The stat caches are internal magic and the bad part about magic is that it's just as hard to see why it's working as why it's not.

**Comment by staabm** [comment]
sounds like magic of a tick-function or error-handler or something

**Comment by curry684** [comment]
Could even be output buffering causing file IO that triggers a stat cache overflow causing it to be reloaded correctly.

**Comment by TSVisopta** [comment]
I thought I might try that and indeed, using PHP NTS without cache clearing would've worked.
