### ISSUE TITLE
Installer corrupt?

### ISSUE THREAD

**Issue by Drifti** [composer/composer#5054]
If i try the command line installation of Composer like advised on https://getcomposer.org/download/

php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php
php -r "if (hash('SHA384', file_get_contents('composer-setup.php')) === '41e71d86b40f28e771d4bb662b997f79625196afcca95a5abf44391188c695c6c1456e16154c75a211d238cc3bc5cb47') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

I get "Installer corrupt".

With TurboSFV I get the following SHA384 hash to the composer-setup.php:
7eb633a82832c1daa18009a2c9561c0049f22319bc35ecb92f08ca9b8aecf105f60e01a77bc95d47ef7175b44cc10c89

Does the SHA384 hash need an update or is the file realy corrupt?

**Comment by Seldaek** [comment]
Works for me:

```
$ php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php
$ php -r "if (hash('SHA384', file_get_contents('composer-setup.php')) === '41e71d86b40f28e771d4bb662b997f79625196afcca95a5abf44391188c695c6c1456e16154c75a211d238cc3bc5cb47') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
Installer verified
```

I'd suggest you download the installer file with your browser, and then try to run the rest from CLI, maybe you have more luck that way. If not then please share the file so I can run a diff and see what's wrong on your end.

**Comment by Drifti** [comment]
attached the composer-setup.php I got with

|$ php -r "readfile('https://getcomposer.org/installer');" > 
composer-setup.php|



Am 13.03.2016 um 17:13 schrieb Jordi Boggiano:
>
> Works for me:
>
> |$ php -r "readfile('https://getcomposer.org/installer');" > 
> composer-setup.php $ php -r "if (hash('SHA384', 
> file_get_contents('composer-setup.php')) === 
> '41e71d86b40f28e771d4bb662b997f79625196afcca95a5abf44391188c695c6c1456e16154c75a211d238cc3bc5cb47') 
> { echo 'Installer verified'; } else { echo 'Installer corrupt'; 
> unlink('composer-setup.php'); } echo PHP_EOL;" Installer verified |
>
> I'd suggest you download the installer file with your browser, and 
> then try to run the rest from CLI, maybe you have more luck that way. 
> If not then please share the file so I can run a diff and see what's 
> wrong on your end.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/composer/composer/issues/5054#issuecomment-195988366>.
>



Warning: readfile(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in Command line code on line 1

Warning: readfile(https://getcomposer.org/installer): failed to open stream: no suitable wrapper could be found in Command line code on line 1

**Comment by Drifti** [comment]
[composer-setup.zip](https://github.com/composer/composer/files/171155/composer-setup.zip)

**Comment by curry684** [comment]
Isn't that warning pretty self-explanatory?

**Comment by Drifti** [comment]
Shure.
But how can i get a file with:

$ php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php

with a different SHA384 hash, as displayed on the same site:
https://getcomposer.org/download/

**Comment by Seldaek** [comment]
Silly php outputting errors on STDOUT :/

Anyway as the output says in the composer-setup.php, you need to enable allow_url_fopen in your php.ini otherwise composer won't work anyway.

**Comment by curry684** [comment]
What is the size of the created file and what happens if you open it with less?

**Comment by Seldaek** [comment]
@curry684 the file only contains this I think:

> Warning: readfile(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in Command line code on line 1
>
> Warning: readfile(https://getcomposer.org/installer): failed to open stream: no suitable wrapper could be found in Command line code on line 1

Which makes sense as this will block the readfile from working.. It should just be output on STDERR ideally so it wouldn't be gobbled up by the `>`

**Comment by Drifti** [comment]
just to avoid misunderstanding: This Warning just result from from sending the php file directly (not zipped) as attachement to github via email (which does not work, that's my fail, sorry), but this is not the concern of this Issue. 
_____________________________________
Warning: readfile(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in Command line code on line 1

Warning: readfile(https://getcomposer.org/installer): failed to open stream: no suitable wrapper could be found in Command line code on line 1
__________________________________________

**Comment by Drifti** [comment]
yes, You are right, the file only contains the 2 warnings.
The file has only 275 bytes.
So the files wasn't really downloaded.
No corrupted file.
I have to enable allow_url_fopen in my php.ini

Thanks a lot

Maybe its possible to get another output, if this happens.
(.....This installer script will simply check some php.ini settings, 
warn you if they are set incorrectly....)


Am 13.03.2016 um 20:20 schrieb Jordi Boggiano:

**Comment by curry684** [comment]
Our code never gets executed as that warning is because of it not being downloaded, so we cannot handle this better.

**Comment by Drifti** [comment]
Maybe it's possible to add a line in the advise on the site https://getcomposer.org/download/

Command-line installation
Run this in your terminal to get the latest Composer version:
???....Add the php.ini test line here.........???
Or in the If......

**Comment by curry684** [comment]
The instructions are kind of weird anyway - use `readfile` to download then rely on output piping to write it to file. I'll have a look.

**Comment by alcohol** [comment]
Unfortunately that would make the installation instructions almost an entire script by itself, which defeats the purpose of a one-liner that you can copy and paste.

**Comment by Seldaek** [comment]
We could change this:

```
-php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php
+php -r "file_put_contents('composer-setup.php', file_get_contents('https://getcomposer.org/installer'));"
```

It's just a bit longer, but at least it would show you the errors I guess if it fails, and it's still easy to inspect.

Any thoughts?

**Comment by alcohol** [comment]
But if the https wrapper is disabled, I think that would still fail?

**Comment by Seldaek** [comment]
Of course it'll fail, but this is a lot more obvious:

```
$ php -dallow_url_fopen=0 -r "file_put_contents('composer-setup.php', file_get_contents('https://getcomposer.org/installer'));"

Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in Command line code on line 1

Call Stack:
    0.0001     360160   1. {main}() Command line code:0
    0.0001     360272   2. file_get_contents() Command line code:1


Warning: file_get_contents(https://getcomposer.org/installer): failed to open stream: no suitable wrapper could be found in Command line code on line 1

Call Stack:
    0.0001     360160   1. {main}() Command line code:0
    0.0001     360272   2. file_get_contents() Command line code:1
```

than:

```
$ php -dallow_url_fopen=0 -r "readfile('https://getcomposer.org/installer');" > composer-setup.php
```

Where the error output is captured into the file, which then fails after.

**Comment by Drifti** [comment]
Yes, it would still fail without wrapper, that's correct. And in this spezial case there one more problem. It's a managed linux server and even If the php.ini file is changed für allow_url_fopen, it isn't still allowed in command line mode.
Worked for me:
Installer download in Windows Firefox Browser:
https://getcomposer.org/installer
Rename to installer.php
Upload with filezilla to linux server in a new directory called composer.
Then in command line:

/usr/bin/php56 -d allow_url_fopen=On installer.php

In here the allow_url_fopen=On was set on the fly in PHP 5.6 and download and installation works fine.
I just think about, if it is still nessassay to have allow_url_fopen=On in the php.ini file too for later usage of composer. Or will it be enought to give each composer command with allow_url_fopen=On on the fly? And is 755 really necessary for composer.phar?

**Comment by curry684** [comment]
When I tried this yesterday the output went on STDERR btw so that system has some peculiar configs anyway.

I think the obvious solution would be to add the wget/curl workarounds to the docs for the first line.

**Comment by Seldaek** [comment]
@Drifti yes, allow_url_fopen is needed for operating composer, and having it disabled is a silly relic of "security" anyway so best to just enable.

@curry684 for me it goes to STDOUT on php7.. Anyway I'd suspect it's not so critical as it's the first such report, so maybe best to just close for now.

**Comment by Rajasekark** [comment]
if i put this comand in my terminal ubuntu16.04 
   php -r "if (hash('SHA384', file_get_contents('composer-setup.php')) === '41e71d86b40f28e771d4bb662b997f79625196afcca95a5abf44391188c695c6c1456e16154c75a211d238cc3bc5cb47') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

i got this   "Installer corrupt"

    how to solve this .....any one help me ........thanks

**Comment by ducnguyenhuy** [comment]
I've got the same issue today and I went to download page https://getcomposer.org/download/ and saw that SHA384 is changed to: `aa96f26c2b67226a324c27919f1eb05f21c248b987e6195cad9690d5c1ff713d53020a02ac8c217dbf90a7eacc9d141d`. Then I've updated the install Composer script and it works.

**Comment by habachi89** [comment]
The mistake is that the PHP script checks that PHP is installed and configured correctly.
This includes all additions
      .PHP> = 5.6.4
     .OpenSSL PHP Extension
     .PDO PHP Extension
     .Mbstring PHP Extension
     .Tokenizer PHP Extension
     .XML PHP Extension


To check if all extentions are installed
Run php -m

To install missing extentions
Run sudo apt-get install php-extention name ex. Xml extention
Sudo apt-get install php-xml
and then run the PHP script to install compuser

**Comment by SunilEver** [comment]
Did you replace the SHA key with the one found on https://composer.github.io/pubkeys.html

**Comment by Hybrid-ghost** [comment]
Hello everyone, I have a similar problem to install and I do not know what the solution is?
Somebody could help me. Below is detailed;

win10_@Anonymous /cygdrive/c/wamp/www
composer create-project symfony/framework-standard-edition cursoweb/ “3.4.*”

I get this:

PHP Fatal error: Uncaught Error: Class ‘Phar’ not found in /cygdrive/c/ProgramData/ComposerSetup/bin/composer.phar:23
Stack trace:
#0 {main}
thrown in /cygdrive/c/ProgramData/ComposerSetup/bin/composer.phar on line 23

And in composer.phar the line says this:

Linea 23 Phar::mapPhar('composer.phar');
Linea 24 require 'phar://composer.phar/bin/composer';

What would be the solution?
Regards,

**Comment by collinsmwiti** [comment]
For Debian users, you can solve the issue using the following, it really solved my problem.

To make Composer (globally) available on Debian:

 1. $ cd /usr/src
 2. $ sudo apt-get install curl php5-cli
 3. $ curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

To Verify installation:
$ composer --version

**Comment by Yavdhesh** [comment]
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

they seem to have changed sha384 key.. Run these it worked for me.

**Comment by suraj575** [comment]
Instead of using 'https://getcomposer.org/installer' use 'http://getcomposer.org/installer'.  php -r "copy('http://getcomposer.org/installer', 'composer-setup.php');"
