### ISSUE TITLE
validate should report abandoned packages

### ISSUE THREAD

**Issue by greg0ire** [composer/composer#5060]
Step to reproduce : 

1. `git clone https://github.com/Seldaek/monolog`
1. `git checkout v1.18.1`
1. `cd monolog`
2. `composer validate`

Expected output : 

> Package videlalvaro/php-amqplib is abandoned, you should avoid using it. Use php-amqplib/php-amqplib instead.

Actual output : 

> ./composer.json is valid

Not sure this can be done efficiently though

**Comment by curry684** [comment]
I don't think we should do this. The purpose of `validate` is only to verify syntax and schema for correctness, not do any content checks. If we were to implement this check we would also, for consistency and predictability, have to:
- Check that all requirements point to valid packages
- Check that all recursive requirements are not abandoned either.
- Check that all recursive requirements can be loaded

And well by that time we're just mirroring `install --dry-run` again. It doesn't make sense in my opinion to do just this one content check.

**Comment by greg0ire** [comment]
I was wondering if the `abandoned` information appears in the `.lock` file. If it is the case, this operation could in fact be quick, couldn't it?

**Comment by curry684** [comment]
But it would then make the behavior inconsistent between running with and without a lock file.

**Comment by greg0ire** [comment]
> without a lock file

Does this happen a lot ?

Granted it would make the behavior inconsistent between running with and without a lock file, but maybe this is just one out of many useful checks that could be run from the lock file.

**Comment by Seldaek** [comment]
We have the --with-dependencies / -A flag that validates all dependencies.. I think doing a call up to the repos in this case to see if it's not abandoned might be ok, but then it'll also slow the command down quite a bit. Might be better to roll it together with a composer outdated cmd (#3771) as that would have to call up to the repo already.

**Comment by greg0ire** [comment]
> the behavior inconsistent between running with and without a lock file.

TIL , very interesting

> Might be better to roll it together with a composer outdated cmd

Might be better indeed, feel free to close this. And if #3771 gets implemented, maybe a message pointing to it could be added to the output or to the help of validate.

**Comment by barryvdh** [comment]
@greg0ire Something like this? https://github.com/composer/composer/pull/5068

**Comment by greg0ire** [comment]
I was thinking about "validate", but the more this message appears, the better :)

**Comment by Seldaek** [comment]
`composer outdated` now shows it, I think that's good enough tbh. Between that and updates it's alright :)
