### ISSUE TITLE
Possible feature: branch-alias "self.version"

### ISSUE THREAD

**Issue by andrerom** [composer/composer#5062]
Some typical issues we have with aliases is:

1. Some ci systems don't handle branching of forks in a good way so Composer is not able to extract version number to match when pulling in dependencies that have version requirements on self
  1. This problem is even more so on forks of forks
3. For above reason we need to hard code inline alias when doing behat testing (injecting self into project setup via `repositories` pointing to local repo and `composer require <package>:dev-tmp_travis_branch as 1.3.x-dev`)

What if there instead was possibility to say something like:
```
{
    "extra": {
        "branch-alias": {
            "self.version": "1.0.x-dev"
        }
    }
}
```
*Either `self.version`, `self.branch` or `this` to signify current branch*.

This would allow us to set this per version branch, and when people fork a given version, this will stay with them. It will also allow us to remove inline alias use, and branch alias that sometimes breaks on fork and forks of forks. 

*Given the slightly different nature of this, I think specific branch names in `branch-alias` should have precedence if found.*

**Comment by andrerom** [comment]
Note: Issue 1. is solvable by using `COMPOSER_ROOT_VERSION="1.0.x-dev"` env variable, however it won't work with 2.

**Comment by Seldaek** [comment]
1. Yes please use COMPOSER_ROOT_VERSION there
2. If you require `X as Y`, can't you make it have the right alias? Or maybe setup a package repository so you can specify the exact version?

The problem is self.version would mean anything is always aliased as anything will match it, so that sounds like a pretty bad idea to fix an edge case :/

**Comment by andrerom** [comment]
> If you require X as Y, can't you make it have the right alias? Or maybe setup a package repository so you can specify the exact version?

I'm not following, the issue I describe is that we have to hard code a version in the first place in ci script to alias the branch. But I realize `self.version` won't fix that as it won't force composer to pick the specific branch on local repo over the once on remote repo on same version.
