### ISSUE TITLE
[Critical] Composer's behavior changed today: it does not run post-install-cmd on first installation

### ISSUE THREAD

**Issue by Nayjest** [composer/composer#5067]
### Steps to Reproduce
1. Clone repository with post-install-cmd available (For example, use this: https://github.com/view-components/view-components)
2. Run 'composer install --prefer-source --no-interaction'

### Expected Behavior
Composer runs  post-install-cmd

If you will test it using view-components package, expected output:
```
> ViewComponents\ViewComponents\Installer::postComposerInstall
Installation finished.
```
Travis CI logs of last successful build [here](https://travis-ci.org/view-components/view-components/jobs/116118333#L309) (see ViewComponents\ViewComponents\Installer::postComposerInstall in output)
### Actual Behavior
It does not runs post-install-cmd

Travis CI logs of view-components package build failed becouse of this bug [here](https://travis-ci.org/view-components/view-components/jobs/116160279#L308)

### Details

**If run installation again, or perform "composer update" before installation, it will work as described.**

### Environment

* Composer version **with bug**: a363df5087b6e01bbfc133581be5f11930fb7744

* PHP: Any
* OS: Any

* Latest Composer version **that works fine**:  653326e21589a209c444ed3f5d3ee9ecf0fcfdb5

**Comment by Nayjest** [comment]
Temporary fix for Travis CI configuration:
```yaml
before_script:
- travis_retry composer self-update 1.0.0-beta1

**Comment by curry684** [comment]
Related to #5066

**Comment by Seldaek** [comment]
Yeah you want to listen to the post-create-project-cmd for doing this, not post-install-cmd, as that depends on having a composer.lock file in the project.
