### ISSUE TITLE
post-install-cmd not executed after installation

### ISSUE THREAD

**Issue by wagnert** [composer/composer#5070]
We faced a weird problem that our post-install-cmd script will not be executed after an `self-update` to the latest composer version. The installation process itself does not show any error message nor does it throw an exception. With composer build

```sh
Composer version 1.0-dev (101fca907197703aee87f314053edf205870b2c6) 2016-02-05 22:46:05
```
everything works fine, with the latest version nothing happens. But, when i invoke the install command a second time, the `post-install-cmd` script is executed as expected.

Has anything changed since that version, that could influence the execution of the `post-install-cmd` script.

To reproduce the problem, you may have a look at our project under https://github.com/appserver-io/appserver. Simple clone the repository and execute

```sh
composer install --prefer-dist --no-dev --no-interaction --optimize-autoloader
```

Best Regards

**Comment by barryvdh** [comment]
See https://github.com/composer/composer/issues/5066

**Comment by Seldaek** [comment]
Either duplicate it in post-update-cmd, or ship a lock file with your app so that install actually installs and not updates.
