### ISSUE TITLE
Composer Error [ERR_STATUS]: Unexpected exit code from Composer (255)

### ISSUE THREAD

**Issue by ansh011** [composer/composer#5072]

**Comment by ansh011** [comment]
Composer Error [ERR_STATUS]: Unexpected exit code from Composer (255)

**Comment by ansh011** [comment]
solve it problems

**Comment by Seldaek** [comment]
Any details? When is this happening?

**Comment by johnstevenson** [comment]
If this is still unresolved, try the current `Composer-Setup.exe` which has been updated to provide better error information in such scenarios.
