### ISSUE TITLE
How to "unreplace" / override subpackage e.g. Symfony components?

### ISSUE THREAD

**Issue by teohhanhui** [composer/composer#5078]
See https://gist.github.com/teohhanhui/d23eeb1b1509304fd4b3 for:

- autoload_psr4.php
- composer.json
- composer.lock
- `composer show -i` log
- `composer update -vvv` log

The update was run with an empty vendor directory, empty composer cache and with no `composer.lock`. Composer version is 1.0-dev (3933a7f) 2016-03-07 01:50:41

I'm trying to use my own fork of `symfony/doctrine-bridge`, but `autoload_psr4.php` contains this line:
```php
'Symfony\\Bridge\\Doctrine\\' => array($vendorDir . '/symfony/symfony/src/Symfony/Bridge/Doctrine', $vendorDir . '/symfony/doctrine-bridge'),
```

How do I make sure the original path from `symfony/symfony` is not included in the autoload?

**Comment by teohhanhui** [comment]
The weird thing is that this works fine in the case of the other overrides for Symfony packages:

- `symfony/framework-bundle`
- `symfony/http-foundation`
- `symfony/property-info`

as you can see from the attached files.

How should I achieve the desired outcome?

**Comment by Jean85** [comment]
You should override the repository from which the package is provided, like this:

```
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/yourUser/YourFork.git"
        },
```

This repo will override Packagist as a source.

**Comment by teohhanhui** [comment]
@Jean85 I'm already doing that. See https://gist.github.com/teohhanhui/d23eeb1b1509304fd4b3#file-composer-json-L76-L79

**Comment by teohhanhui** [comment]
The package is getting installed just fine. The question is, how do I make sure the original path is not being autoloaded?

**Comment by Jean85** [comment]
That's transparent and you can't "force" it in any way, that's the point of this feature of composer and of autoloaders in general.
The only other thing that you can do is require a specific commit or a specific branch that exists only in the fork.

**Comment by teohhanhui** [comment]
@Jean85 Try comparing https://gist.github.com/teohhanhui/d23eeb1b1509304fd4b3#file-autoload_psr4-php-L22-L24 and https://gist.github.com/teohhanhui/d23eeb1b1509304fd4b3#file-autoload_psr4-php-L28

vs

https://gist.github.com/teohhanhui/d23eeb1b1509304fd4b3#file-autoload_psr4-php-L35

All of these are overrides to the `symfony/symfony` package. Why is it only `symfony/doctrine-bridge` that has the original path from `symfony/symfony` being autoloaded too?

My goal is to figure out how to get the correct behaviour (if it's possible), whether I'm doing something wrong / different for this specific case, and whether this is a bug or it's documented somewhere.

**Comment by Jean85** [comment]
This may depend on how the Symfony package is being defined. IIRC, Symfony is moving those bundles inside the main package, and replacing those definition in its composer.json. I think you should take a look on that, and avoid requiring symfony/symfony directly if you wish to override single components.

**Comment by teohhanhui** [comment]
I've discovered that this is because of the PSR-4 rule of `symfony/symfony` here: https://github.com/symfony/symfony/blob/4af15567e0c92a8c93771643629cdf7effcdbfa6/composer.json#L92

whereas the PSR-4 rule in `symfony/doctrine-bridge` has the same namespace (i.e. is no more specific): https://github.com/symfony/doctrine-bridge/blob/688945134c2e456ac1d885256d632cdcf406f74c/composer.json#L46

I tried using `exclude-from-classmap` without any success, but got it to work following @Seldaek's advice here: https://github.com/composer/composer/issues/4732#issuecomment-186834692

**Comment by Seldaek** [comment]
Sooo @teohhanhui is it resolved then? Should we close this?
