### ISSUE TITLE
composer fail with psiphon proxy ?? 

### ISSUE THREAD

**Issue by mikimaine** [composer/composer#5080]
With the following proxy setting in the system variable : http_proxy and https_proxy  set properly 

When I run this command:composer diagnose

I get this output:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version:

  [Composer\Downloader\TransportException]
  The "https://getcomposer.org/version" file could not be downloaded: failed to open stream: A connection attempt failed because the connected party did not properly
   respond after a period of time, or established connection failed because connected host has failed to respond.


diagnose
```

And I expected this to happen:

Checking https connectivity to packagist: OK  because i have set https_proxy 

And also, all those urls work fine using my web browser

Thanks!

**Comment by Seldaek** [comment]
Did you figure this out? I don't really know what to tell you, if it can't connect it must be some sort of misconfiguration of the proxy, but it's hard to help from outside your network and without knowledge of your proxy settings.

**Comment by mikimaine** [comment]
YES! i have found the problem !
by running set http_proxy="127.0.0.1:portno" as administrator every time i start a new composer windows and set http_proxy in windows environment .

**Comment by Seldaek** [comment]
OK great. But if you set the http_proxy as environment in the system env vars then it should not reuqire you to set it every time you open a new window. Might just need a restart.
