### ISSUE TITLE
Composer update dont work

### ISSUE THREAD

**Issue by APdevelopments** [composer/composer#5082]
I need to run composer update at my hosting so I log in with ssh and try to run comand:

composer update
 inside /www folder where I have laravel and composer instalation

but I get error: http://i.stack.imgur.com/FGC01.png

in contact with my hosting provider they tell me to run command:

php -d memory_limit=512M composer update
 I run this command but I get: "Could not open file: composer"

What to do? What is the soluton here?

**Comment by dzuelke** [comment]
This is an issue tracker, not a support system.

There is no file "composer" that you can feed PHP to run. It's an executable on the path. You probably want to run `php -d memory_limit=512M $(which composer) update` instead.

**Comment by Seldaek** [comment]
Read up on https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file - you should not run composer update in production.
