### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by tr33m4n** [composer/composer#5083]
Yo,

Obviously Composer is awesome, however I think there are places where (especially the installer script) they need cleaning up, for example:
```php
foreach ($argv as $key => $val) {
        if (0 === strpos($val, '--install-dir')) {
            if (13 === strlen($val) && isset($argv[$key+1])) {
                $installDir = trim($argv[$key+1]);
            } else {
                $installDir = trim(substr($val, 14));
            }
        }

        if (0 === strpos($val, '--version')) {
            if (9 === strlen($val) && isset($argv[$key+1])) {
                $version = trim($argv[$key+1]);
            } else {
                $version = trim(substr($val, 10));
            }
        }

        if (0 === strpos($val, '--filename')) {
            if (10 === strlen($val) && isset($argv[$key+1])) {
                $filename = trim($argv[$key+1]);
            } else {
                $filename = trim(substr($val, 11));
            }
        }

        if (0 === strpos($val, '--cafile')) {
            if (8 === strlen($val) && isset($argv[$key+1])) {
                $cafile = trim($argv[$key+1]);
            } else {
                $cafile = trim(substr($val, 9));
            }
        }
    }
```

Could possibly need a little https://secure.php.net/manual/en/function.getopt.php ? Willing to take it on, but not sure of the proper proceedure

Cheers

**Comment by curry684** [comment]
Fork the repo, fix the code, make a PR  :smile: 

https://help.github.com/articles/using-pull-requests/

**Comment by alcohol** [comment]
Yes, a simple pull request is the best approach. We do recommend to keep the changeset small. If you have something big planned, best to ask/discuss it first before starting something that might never see the light of day.

**Comment by Seldaek** [comment]
Closing as there is no real bug or anything here, if you send a PR great, if not the current code will live on happily :)
