### ISSUE TITLE
Storing cached packages uncompressed

### ISSUE THREAD

**Issue by pamil** [composer/composer#5085]
Hello!

Travis build I'm currently maintaining is currently installing dependencies for ~80 standalone packages, whereas most of them have common dependencies. I'm using `--prefer-dist` option, so they are cached as a zip files. However, installing them still takes about 3-4 minutes and a huge part of that time is spent extracting the same archives once and again. Is there any way to store the packages not as zip files but as directories?

**Comment by curry684** [comment]
Nope, they're just cached as they are coming in.

**Comment by alcohol** [comment]
If your lock file does not update frequently, you could add `vendor/` to the cached directories on Travis. Composer will detect your packages as installed then, which makes the whole process much faster.

**Comment by pamil** [comment]
@alcohol I've done it for one package, but for ~80 packages it will take way too much space.

Is it possible for a Composer plugin to manipulate the way packages are cached?

**Comment by staabm** [comment]
@pamil did you try `cache: vendor/` in the travis.yml ?

**Comment by pamil** [comment]
@staabm the thing is, that I have a lot of packages that need to be tested standalone and each one has their own vendor directory, so I can't cache them all. They share a lot of common dependencies and it would be an overkill.

Let's say I've got `symfony/framework-bundle` cached at `~/.composer/cache/files/symfony/framework-bundle/7aea8c39bd812b21a233f0aa547f872c51ff4c0b.zip`. All I want to achieve is to have it cached not as an archive, but as a regular directory - `~/.composer/cache/files/symfony/framework-bundle/7aea8c39bd812b21a233f0aa547f872c51ff4c0b/*`. This way, if ten of my packages require it, it won't be extracted ten times, but only copied (or even better - symlinked).

**Comment by alcohol** [comment]
There is no alternative available (currently). The choice is yours :-)

**Comment by Seldaek** [comment]
I don't think this is something we're gonna support, too edge case, and really it's a problem of the build system not our cache IMO.

**Comment by pamil** [comment]
All right, it's understandable. Is there any way to implement this behaviour via Composer plugin?

**Comment by Seldaek** [comment]
@pamil not really no, at least I can't think of an easy way.. You could by adding a custom installer and overriding tons of logic but it's gonna be pretty ugly :/
