### ISSUE TITLE
Replaced package is installed in two different versions

### ISSUE THREAD

**Issue by janedbal** [composer/composer#5089]
With the following composer, dibi library is installed twice. 

```json
{
    "require": {
        "tharos/leanmapper": "2.2.*",
        "lightools/transaction-nesting": "dev-master"
    }
}
```

Once for leanmapper (depends on ```dg/dibi ~2.0```, installed version is 2.3.5) and once for transaction-nesting (depends on ```dibi/dibi >=2.0.0```, installed version is 2.1.0). Then I get warning about many ambiguous classes.

Library ```dibi/dibi``` contains ```"replace": {"dg/dibi": "self.version"}``` [since version 2.2](https://github.com/dg/dibi/commit/32518eca549a43ff630c5671c0de2f3ea8eb8202).

I would expect that only ```dibi/dibi``` in version 2.3.5 will be installed.

**Comment by alcohol** [comment]
Know issue with replace; see also #3754

Not sure how to work around it in this case. Seems like `leanmapper` is out of date though. Either update the version you are using (if newer is available) or submit a pull request to their codebase updating the dependency.

**Comment by janedbal** [comment]
Thanks for fast response, easiest workaround I found was adding direct dependency on ```dibi/dibi``` to my composer.json.

**Comment by alcohol** [comment]
I was thinking about suggesting that, but honestly was not sure how that would work out. Glad it fixed the issue though, I will keep that in mind :-)
