### ISSUE TITLE
SVN download not succesful

### ISSUE THREAD

**Issue by grappler** [composer/composer#5090]
We realized there was a problem after updating the SVN URLS to HTTPS.

There is an error when trying to run `--prefer-source`. I did not have this error when running composer from "2016-03-11".

https://github.com/outlandishideas/wpackagist/pull/148

I am not sure how I can download composer.phar from specific dates to work out which day it error starts to occur.

**Comment by stof** [comment]
> I am not sure how I can download composer.phar from specific dates to work out which day it error starts to occur.

@grappler you cannot download them for any date. You would have to rebuild them from source, for different composer commits.

**Comment by Seldaek** [comment]
Not sure what to say here, SVN failing to download from the server with an SSL error does not really sound like a composer error. Either the server is borked or more likely the client has an outdated SSL CAbundle in which the WP CA is not present.
