### ISSUE TITLE
composer command not found in GitBash

### ISSUE THREAD

**Issue by jgodwin13** [composer/composer#5091]
I have `C:\Composer\` in System PATH variables.

I use **gitbash  v2.7.12** 

When I run this command:

```
php composer.phar -V (1.0.0-alpha1)
```
OR
```
composer -V (1.0.0-alpha1)
```
I get this output:

```
bash: composer: command not found
```

And I expected this to happen: 
```

 ✘ ಠ︵ಠ凸[20:22:03]-<pid|⚑167>13022010*>>@SERVER:/c$ composer -V
 Composer version 1.0.0-alpha11 2015-11-14 16:21:07

 ✘ ಠ︵ಠ凸[20:22:06]-<pid|⚑168>13022010*>>@SERVER:/c$

```
I even tried to add  `export PATH=$PATH:/c/composer/` in my `bashrc` but it didnt work! Although in Windows Command Prompt it workd like a charm.

**Comment by garethellis36** [comment]
What is in `C:\Composer\`? If you `cd /c/composer/` in Git Bash, can you run `composer -v`?

**Comment by jgodwin13** [comment]
when i `cd` to composer and run `composer -v` it doesnt work. I have tried with different versions of gitbash ( v2.7.12, v.2.7.4)

**Comment by garethellis36** [comment]
You can't run .bat files in Git Bash, so Git Bash is looking for a file called "composer", which doesn't exist. You could rename composer.phar to just composer and it would work in Git Bash. 

I would personally recommend deleting the whole folder and reinstalling composer using the official installer. This will take care of setting your PATH correctly.

**Comment by Bradltr95** [comment]
Renaming the file did not seem to do anything as you get composer and composer.phar with the install. You will need to delete and re-install composer from their website using the Composer-Setup.exe

**Comment by AmitPatelAlbiorix** [comment]
Composer-Setup.exe move download folder to Desktop then install otherwise not getting system variable and not install in c:/programmefile/ folder .

**Comment by DJMaide4** [comment]
yo le escribo composer update y no me dunciona

**Comment by euginekoyo** [comment]
HP@HACKBOOTH245 MINGW64 /c/xampp/htdocs
$ composer create-project laravel/laravel skytracks 
bash: composer: command not found  
what could be the problem

**Comment by Hsqman** [comment]
Remove "c:/composer" from yout path environement variable and add this : "C:\ProgramData\ComposerSetup\bin"
