### ISSUE TITLE
handle json_encode _empty_ gracefully please

### ISSUE THREAD

**Issue by ofbeaton** [composer/composer#5092]
So I just ran into this problem while making a satis repository script for composer. I don't see a good solution. The problem has to do with `""` keys getting turned into `"_empty_"` using json_encode when provided an object. 

There is a bug on php.net about this, but it sounds like DONTFIX-ACTUALLYAFEATURE: https://bugs.php.net/bug.php?id=46600

If I `$composerJson = json_decode($composerJson, true)` into associative arrays, manipulate it, then `json_encode($composerJson)` then my 
  `"require-dev": {}`
turns into
  `"require-dev": []`
which composer chokes on. So obviously I can't read the composer file as associative arrays! That isn't this bug, I just want to show upfront that using the associative array parameter on my json_decode cannot solve my problem.

So I do: `$composerJson = json_decode($composerJson, false)` and turn it into objects to manipulate it. Except the most common composer.json contains something like this:
```
  "autoload": {
    "psr-4": {
      "": "src/"
    }
  }
```

it reads it in fine, but when I do `json_encode($composerJson)` again... I get:
```
  "autoload": {
    "psr-4": {
      "_empty_": "src/"
    }
  }
```

which composer then chokes on because of course "_empty_" has a different meaning than "", and it thinks I mean the namespace `_empty_` AND it's missing the mandatory trailing `\\` slashes..

So I'm stuck doing a json_encode then using a hack, `$composerJson = str_replace('"_empty_":', '"":', $composerJson)` before writing it to file again.

The _empty_ key does not seem to me to be the right answer here. Should composer change the way composer files for virtually all projects be written? Is this a composer bug?

Or should json_encode and json_decode objects reproduce a blank key? Will this ever be fixed upstream or should composer just implement the hack for me?

**Composer could replace the "_empty_" into "" for me when it reads it in a composer.json**

I hope upstream would fix, but I doubt it. I read somewhere composer isn't getting much development, so may it will not get fixed here either. For now I have my hack.

**Comment by curry684** [comment]
Attached PR should patch this.

> I read somewhere composer isn't getting much development

You could've made this 3-line PR yourself  :wink:

**Comment by ofbeaton** [comment]
@stof I'm OK leaving my `str_replace` hack in place,and closing this issue.

The issue here is since:

```
$json = file_get_contents('composer.json');
$json = json_decode($json, false);
$json = json_encode($json);
file_put_contents('composer.json', $json);
```

results in an invalid `composer.json`, due to the `_empty_` "feature" from PHP. 

I looks to me like there is no agreement on if an empty key is valid json or not in this case, and at least to my eyes, it does not appear like PHP is going to fix this.

So I was wondering if maybe composer could silently fix it for me. It really is non-intuitive that it would fail.

But I understand if PHP says DONTFIX and composer says DONTFIX, then I'll just leave my hack in place in my own programs.

This problem took me by surprise as it only showed itself after I moved from Symfony 2.x to Symfony 3.0.x and it changed to PSR-4, and all of a sudden my automated satis rewrite scripts started producing a `composer.json` that composer didn't like.

Thank you for your consideration.
