### ISSUE TITLE
sometimes trait autoload does not work

### ISSUE THREAD

**Issue by svycka** [composer/composer#5096]
when I do `composer update` or `composer install` everything updates succesfuly but when I try to access my page I get this error:

> PHP Fatal error:  Trait 'Application\\Traits\\BlameableEntity' not found in /var/www/farm-catalog/module/FarmCatalog/src/FarmCatalog/Entity/Manufacturer.php on line 14

`BlameableEntity` is just simple trait and Manufacturer.php on line 14 is simple `use BlameableEntity` also `Manufacturer` is doctrine entity(this maybe not related)

I would think that I misconfigured something, but executing `composer dump-autoload -o` solves my problem also enabling optimizer for update like this `composer update -o` also solves it. So I am not sure what is wrong and how to debug the problem.

Any suggestions how to find the problem?

in composer I have configured them both like this:
```
...
    "autoload": {
        "psr-4": {
          ...
          "Application\\": "module/Application/src/Application",
          "FarmCatalog\\": "module/FarmCatalog/src/FarmCatalog",
          ...
        }
    },
...
```

**Comment by stof** [comment]
This may mean that the path to the file does not match the PSR-4 convention, while still being in the folder (meaning that the classmap generator finds the class when building the optimized autoloader, even if it does not actually respect psr-4).
Can you paste the path to the file in which the trait is defined ?

**Comment by svycka** [comment]
BlameableEntity:
```
namespace Application\Traits;
/var/www/farm-catalog/module/Application/src/Application/Traits/BleamableEntity.php
```
Manufacturer:
```
namespace FarmCatalog\Entity;
/var/www/farm-catalog/module/FarmCatalog/src/FarmCatalog/Entity/Manufacturer.php
```

@stof but I don't see how this does not match the PSR-4 convention and how optimizing fixes it if it's the case.

**Comment by stof** [comment]
you have a typo in the filename: ``BleamableEntity.php`` vs ``BlameableEntity`` (note the location of the ``e``)

**Comment by svycka** [comment]
@stof omg you are right :D thanks, but how can it work when I enable optimize?

**Comment by stof** [comment]
@svycka when building the optimized classmap, Composer looks for any class defined in the folder to add them in the classmap. Currently, it does not validate whether the path matches the PSR conventions or no.

**Comment by svycka** [comment]
@stof ok that explain why thanks. 

Maybe worth adding the check because not everyone has eagle eyes? :D

**Comment by stof** [comment]
There is already an issue discussing this IIRC (I haven't searched it to confirm).

On a side note, the Symfony Debug component has several handy debugging features, and one of them is an autoloader wrapper (compatible with the composer autoloader) which detects such mistakes when it can (I'm not sure it would have been able to detect this particular case in details, but it could have given more details): http://symfony.com/doc/current/components/debug/index.html

**Comment by curry684** [comment]
This is also sideways related to https://github.com/composer/composer/issues/5092 in that we "let too much crap through". I think it would be good to validate a lot of autoloading stuff during generation, they're cheap checks, and people don't `validate` in practice.

**Comment by stof** [comment]
@curry684 this case has nothing to do with ``composer validate``, as it is not related to mistake in the composer.json file.

**Comment by curry684** [comment]
@stof that was also my point in that the other case shouldn't have to do with `composer validate` either, as both are part of the more general "Composer should fail a lot harder on invalid configurations". Generating invalid autoloaders is as wrong as generating invalid classmaps.
