### ISSUE TITLE
Possibly change install/update sequence.

### ISSUE THREAD

**Issue by rquadling** [composer/composer#5097]
Hi.

Currently, (and I hope I've got this right), ``composer install`` loops through each package that is required, based upon ``composer.lock`` and does the following steps:

1. Delete package from ``vendor``
2. Download package from repo/online
3. Install package into ``vendor``

When finished, the autoloader is created.

During this time, the application is unusable.

Is there any possibility of changing the sequence to ...

1. Download all packages into cache, ready to be installed. If a package cannot be downloaded, quit and there is no damage.
2. Install all packages into alternative ``new_vendor``. Again, if there is a problem, quit with no damage.
3. Build autoloader, taking into account that ``new_vendor`` is really ``vendor``
4. If, all is OK at this point,
 1. Rename ``vendor`` to ``old_vendor``
 2. Rename ``new_vendor`` to ``vendor``
 3. Drop ``old_vendor``

When the upgrades are only minor or patch (or at least compatible with existing application source), you won't get any downtime.

Admittedly, attempting to do all this in a production environment is scary, but, for the time being, that's what we have to do.

**Comment by barryvdh** [comment]
You should probably just put your site in maintenance mode, or create a deploy script that creates a new folder for a new version, and rename/symlink when your deployment is finished/validated.

**Comment by rquadling** [comment]
Yeah. I know. Probably easier all round.

**Comment by curry684** [comment]
There are a lot of potential issues with defaulting to your proposed solution: https://github.com/composer/composer/issues/4736#issuecomment-183991947

In general, it's easiest to just enable maintenance mode, or if a few minutes of downtime are really that vital follow the deploy script approach.

**Comment by alcohol** [comment]
I think the primary issue here is that Composer is used as a deployment tool, which it is not. Composer is for developers, not for production environments. There is no need to makes things more clever than necessary. There is tooling available already that is much better equipped to handle deployment/distribution of an application.

**Comment by stof** [comment]
@rquadling your proposal would not make composer suited for prod deployment either, because you forgot one piece of the puzzle: the code of your project. Your project already contains the new codebase at the beginning of the scenario, but with the old vendor folder, which is also a broken case.

Using dedicated deployment tools is indeed a better idea.

**Comment by rquadling** [comment]
Thank you for your comments. Our infrastructure is growing and so we need to learn new tools (new for us).

**Comment by alcohol** [comment]
I personally have never tried it out yet, but http://deployer.org/ seems interesting in this regard.
