### ISSUE TITLE
Updating composer.json after install does not affect output of composer.lock

### ISSUE THREAD

**Issue by jtreminio** [composer/composer#5098]
With the following composer.json:

    {
        "require": {
            "COMPANYNAMESPACE/core"                  : "2.3.0"
         },
        "repositories": [
            {
                "type": "package",
                "package": {
                    "name": "COMPANYNAMESPACE/core",
                    "version": "2.3.0",
                    "source": {
                        "type": "git",
                        "url": "ssh://git@url.to.our.private.repo.git",
                        "reference": "COMPANYNAMESPACE-2_3_0-016"
                    }
                }
            },
        ]
    }

I run `composer install` which installs requirements in `composer.lock` as it should.

`composer.lock`:

    {
        "_readme": [
            "This file locks the dependencies of your project to a known state",
            "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file",
            "This file is @generated automatically"
        ],
        "hash": "dd6fb331bbaa77aea7ef73a9a4c3a1d3",
        "content-hash": "59e7fa79ec38eb564e94ef45af34d0c5",
        "packages": [
            {
                "name": "COMPANYNAMESPACE/core",
                "version": "2.3.0",
                "source": {
                    "type": "git",
                    "url": "ssh://git@url.to.our.private.repo.git",
                    "reference": "core-2_3_0-016"
                },
                "type": "library"
            }
        ],
        "packages-dev": [],
        "aliases": [],
        "minimum-stability": "stable",
        "stability-flags": [],
        "prefer-stable": false,
        "prefer-lowest": false,
        "platform": [],
        "platform-dev": []
    }

Then I change `composer.json` to the following:

    {
        "require": {
            "COMPANYNAMESPACE/core"                  : "2.3.0"
         },
        "repositories": [
            {
                "type": "package",
                "package": {
                    "name": "COMPANYNAMESPACE/core",
                    "version": "2.3.0",
                    "source": {
                        "type": "git",
                        "url": "ssh://git@url.to.our.private.repo.git",
                        "reference": "COMPANYNAMESPACE-2_3_0-015"
                    }
                }
            },
        ]
    }

and run `composer update -vvv`:

    $ composer update -vvv
    Reading ./composer.json
    Loading config file /Users/jtreminio/.composer/config.json
    Loading config file /Users/jtreminio/.composer/auth.json
    Loading config file ./composer.json
    Checking CA file /usr/local/etc/openssl/cert.pem
    Executing command (/Users/jtreminio/www/PATH_TO/site): git branch --no-color --no-abbrev -v
    Failed to initialize global composer: Composer could not find the config file: /Users/jtreminio/.composer/composer.json
    To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
    Reading /Users/jtreminio/www/PATH_TO/site/vendor/composer/installed.json
    Loading composer repositories with package information
    Downloading https://packagist.org/packages.json
    Writing /Users/jtreminio/.composer/cache/repo/https---packagist.org/packages.json into cache
    Updating dependencies (including require-dev)
    Reading /Users/jtreminio/.composer/cache/repo/https---packagist.org/p-provider-2013.json from cache
    Reading /Users/jtreminio/.composer/cache/repo/https---packagist.org/p-provider-2014.json from cache
    Reading /Users/jtreminio/.composer/cache/repo/https---packagist.org/p-provider-2015.json from cache
    Reading /Users/jtreminio/.composer/cache/repo/https---packagist.org/p-provider-2015-04.json from cache
    Reading /Users/jtreminio/.composer/cache/repo/https---packagist.org/p-provider-2015-07.json from cache
    Reading /Users/jtreminio/.composer/cache/repo/https---packagist.org/p-provider-2015-10.json from cache
    Reading /Users/jtreminio/.composer/cache/repo/https---packagist.org/p-provider-2016-01.json from cache
    Reading /Users/jtreminio/.composer/cache/repo/https---packagist.org/p-provider-archived.json from cache
    Downloading http://packagist.org/p/provider-latest%2485f56f240956bdcc55deae4b5c5e52227623ad35541c2e73fe0cbc0bfe293b32.json
    Writing /Users/jtreminio/.composer/cache/repo/https---packagist.org/p-provider-latest.json into cache
    Analyzed 65 packages to resolve dependencies
    Analyzed 65 rules to resolve dependencies
    Nothing to install or update
    Reading /Users/jtreminio/www/PATH_TO/site/vendor/composer/installed.json
    Reading ./composer.lock
    Generating autoload files

`composer.lock` has not been updated with the new tag:

    {
        "_readme": [
            "This file locks the dependencies of your project to a known state",
            "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file",
            "This file is @generated automatically"
        ],
        "hash": "dd6fb331bbaa77aea7ef73a9a4c3a1d3",
        "content-hash": "59e7fa79ec38eb564e94ef45af34d0c5",
        "packages": [
            {
                "name": "COMPANYNAMESPACE/core",
                "version": "2.3.0",
                "source": {
                    "type": "git",
                    "url": "ssh://git@url.to.our.private.repo.git",
                    "reference": "core-2_3_0-016"
                },
                "type": "library"
            }
        ],
        "packages-dev": [],
        "aliases": [],
        "minimum-stability": "stable",
        "stability-flags": [],
        "prefer-stable": false,
        "prefer-lowest": false,
        "platform": [],
        "platform-dev": []
    }

My current composer version:

    $ composer --version
    Composer version 1.0-dev (a8e9df55dc62d8806360be2f79ad112b8678d397) 2016-03-17 11:42:19

The same thing happens if I manually `rm -f composer.lock` and run `composer update`.

I must manually `rm -rf vendor/PATH_TO_LIBRARY` to get this to actually respect the changes made in `composer.json`. Afterward, running `composer update` pulls in the correct version of the library.

**Comment by alcohol** [comment]
I think that is because for dependency resolving, composer looks at the version, not the source of it. Your version requirement has not changed at all. So why would it reinstall the same version?

**Comment by stof** [comment]
when changing metadata of a ``package`` repository type, you indeed need to update its version (or use a dev version as version, and update the ``time`` property).

If the git repo is under your control, I stringly suggest you to put a composer.json file inside the git repo and to use the ``vcs`` repository type instead, which works much better than the ``package`` one thanks to composer using the git metadata (and the fact that you cannot change the composer.json in the git repo without making a new commit and so updating these data)
