### ISSUE TITLE
Question on creating plugin

### ISSUE THREAD

**Issue by hiqsol** [composer/composer#5101]
I want to create plugin that cancels processing of certain dependencies. 

For example:
```
"require": {
...
  "the-prefix/option-a": "xxx", 
  "the-prefix/option-b": "yyy",
... 
} 
```

I want to collect information of all required 'options' (including dependent packages) but I don't want composer to resolve those fake packages. 

Can you please give me idea how this can be done?

**Comment by curry684** [comment]
There are no events allowing you to plug in at this point of operation.

I suspect a huge [XY problem](http://meta.stackexchange.com/a/66378/219504) here though - you're asking help with your proposed solution to a problem, and not the actual problem. So: what are you trying to achieve?

**Comment by alcohol** [comment]
Yes, please tell us your actual problem. The OP is not something we can help you with. But maybe we can help you solve whatever it is you are really trying to achieve.

**Comment by hiqsol** [comment]
Ok :)
The actual problem is [fxp/composer-asset-plugin](https://packagist.org/packages/fxp/composer-asset-plugin) (which is cool thing anyway).
What I want to achieve is to create plugin that will substitute fxp plugin for existing packages currently depending on that plugin (yii2 framework paricularly).

Fxp plugin enables using special dependencies like:

```json
"require": {
    "bower-asset/bootstrap": "x.x",
    "npm-asset/something": "y.y",
}
```

and it enables Composer to resolve and install those dependencies.

I want my plugin to work with those already existing packages (without changing them) but install bower and npm packages with original NodeJS bower/npm or bowerphp - this part I've already tested to work in [hiqdev/composer-asset-plugin](https://github.com/hiqdev/composer-asset-plugin).

So what's left to do is to collect list of those bower/npm-asset/packages and to tell composer to not to process them.

I see 3 possibilities:

- completely remove those dependencies (didn't find a way)
- provide fake registry with fake packages for those dependencies (very not easy - didn't succeed for the moment)
- use `provide` feature (didn't try yet)

So I'll be grateful for any ideas.

**Comment by curry684** [comment]
First and foremost: the Composer architecture is currently not really fit for plugging in this kind of things. The FXP asset plugin appears to solve a real world issue for a lot of users, but inside is a really ugly piece of work hacking into Composer's lowest level internals. It's also caused a few issues there over time where it crashed because Composer had internal changes it couldn't work with.

At which point during processing do you know which packages need to be cancelled? Is it an entire group or just a fixed list?

**Comment by hiqsol** [comment]
> At which point during processing do you know which packages need to be cancelled? Is it an entire group or just a fixed list?

Not a fixed list. All bower-asset/* and npm-asset/* required in root and all required packages.

**Comment by curry684** [comment]
That disqualifies the `provide` option as it doesn't have wildcards. Not really sure on the best option to achieve this otherwise....

**Comment by hiqsol** [comment]
Not really cause I can add all the necessary `provide`s dynamically to root package for example, I just don't know will it work :)

**Comment by stof** [comment]
@hiqsol the issue is about determining the list of necessary provides, as you would have to do it before the dependency resolution, and so you don't know the dependencies yet

**Comment by curry684** [comment]
Indeed, and that leaves a custom repository as just about the only option, it could expand the pool with dummy packages as it resolves.

**Comment by hiqsol** [comment]
Yes, that's what I wanted to know if there is a simpler way then create a custom repository.
Additional question is it a good (reliable) practice? I don't want to repeat fxp story.

**Comment by hiqsol** [comment]
@stof as far as I understand it's impossible to determine necessary provides before dependency resolution (on PRE_DEPENDENCY_SOLVING) cause at the moment composer knows only requirements of the root package.

**Comment by hiqsol** [comment]
I just tried to dynamically determine required asset packages with help of custom repository (this works) and add necessary `provides` to the root package - that doesn't work cause I think they are not taken into account by resolver.
Don't you know how to make those `provides` to work?

**Comment by curry684** [comment]
The `provide` route won't work then because the root package is already parsed at that point, including its replacements. You would have to keep a list of obsoleted package in the repository and return empty packages when they are requested.

**Comment by hiqsol** [comment]
I've found and implemented entirely different solution. I hope it may be interesting for you:

https://asset-packagist.org/
