### ISSUE TITLE
Internal Error [ERR_INVALID], exit code 0

### ISSUE THREAD

**Issue by Ronaiza** [composer/composer#5102]
Não consigo instalar o Composer na minha máquina. Primeiro estava apontando o erro do openssl, resolvi e depois disso deu esse erro que coloquei no título

**Comment by curry684** [comment]
Please ask your question in English if you want us to help.

**Comment by Ronaiza** [comment]
I Can not Install Composer on my machine. First it was pointing the OpenSSL error , and after that I decided to give This Error That put the title

**Comment by Ronaiza** [comment]
Internal Error [ERR_INVALID], exit code 0

**Comment by curry684** [comment]
I cannot even begin to help if I don't know more specifics. What OS are you trying to install on which way, what was the full output, at what stage etc.

Just copy/pasting an error message is like going to a doctor only saying "I have pain" and expecting him to know what's wrong.

**Comment by Ronaiza** [comment]
Im using W8 64b

**Comment by Ronaiza** [comment]
the output is after a chose the php

**Comment by Ronaiza** [comment]
Thank you for your attention and sorry to take your time . I managed to solve the problem :)

**Comment by curry684** [comment]
Good to hear  :smile:   please close the issue when it is no longer relevant.
