### ISSUE TITLE
Cannot get composer to install

### ISSUE THREAD

**Issue by krazykhris875** [composer/composer#5103]
I've been googling this for an hour and nothing's working. I've got PHP added to my windows path variable, and everytime I run this:
```
php composer.phar install --no-dev --optimize-autoloader
```
I get this: 
```
Fatal error: Uncaught exception 'PharException' with message 'unable to open phar for reading "composer.phar"' in composer.phar:23
Stack trace:
#0 composer.phar(23): Phar::mapPhar('composer.phar')
#1 {main}
  thrown in composer.phar on line 23
```
I have no idea what's going on, I'm working on a git repository, the website doesn't work without composer, it was working fine recently then I tried to run a command and it doesn't work so I wiped my repository and re-cloned, now it won't reinstall

**Comment by alcohol** [comment]
Maybe @Seldaek or @curry684 can help you here. I have no idea why it would fail. I tried Googling the specific error message, but I mostly find posts from other Windows users. I don't use Windows, so I cannot really provide further assistance.

**Comment by curry684** [comment]
It seems ordinary file corruption to me. The phar bootstrap code is working but then unable to unpack itself apparently.

If you open the `composer.phar` with notepad it may show evidence of what's wrong.

**Comment by Seldaek** [comment]
One way would be to re-run the install instructions from https://getcomposer.org/download/ (or use the windows installer..)
