### ISSUE TITLE
Feature request: --no-interact only for credentials prompts

### ISSUE THREAD

**Issue by psylosss** [composer/composer#5107]
It is impossible to disable only prompts to store credentials, only globally using `COMPOSER_NO_INTERACTION`. It would be useful to set `--no-interact` only for credentials prompts. 

Request comes from [stackoverflow question](http://stackoverflow.com/questions/36183708/how-to-disable-prompt-to-store-credentials-in-composer).

**Comment by curry684** [comment]
I missed something in my SO answer - the `--no-interaction` flag is provided by `symfony/console` so obviously I didn't find it in the code. That one [already exists](https://getcomposer.org/doc/03-cli.md#composer-no-interaction) though.

It will default all questions though, not just credentials, however Composer doesn't ask that many other questions so I doubt a separate `--no-auth` or something is useful.

**Comment by Seldaek** [comment]
That doesn't really seem worth the trouble IMO of having even more configuration.
