### ISSUE TITLE
Composer misleadingly reports 100% download on failed connections.

### ISSUE THREAD

**Issue by cxj** [composer/composer#5111]
With the following composer.json:

```json
{
   "repositories": [
        {
            "type": "composer",
            "url": "https://phppkg.example.com"
        }
    ],

    "require": {
        "cxj/phpsyslog": "^1.0"
    },
}
```

When I run this command:

```
composer install -vvv
```

I get this output:

```
> composer install -vvv
Reading ./composer.json
Loading config file ./composer.json
Executing command (CWD): git describe --exact-match --tags
Executing command (CWD): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /home/cxj/.composer/composer.json
To initialize a project, please create a composer.json file as described in the http://getcomposer.org/ "Getting Started" section
Reading ./composer.lock
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Reading ./composer.lock
  - Installing cxj/phpsyslog (v1.1.3)
Downloading https://phppkg.example.com/dist/cxj-phpsyslog-59f6b758ed5db303a72644e892b91bbe8c829a56-zip-9b043e.tar
    Downloading: 100%
    Download failed, retrying...
Downloading https://phppkg.example.com/dist/cxj-phpsyslog-59f6b758ed5db303a72644e892b91bbe8c829a56-zip-9b043e.tar
    Downloading: Connecting...^C
```

And I expected this to happen:

```
   Downloading: 0%
```

**Comment by curry684** [comment]
The message is factually correct - the percentage is supposed to represent a predictable progress indication of the active operation, indicating when to expect a full response.

As the hostname cannot resolve the download fails immediately, and is thus 100% completed - there's nothing left to be done. Sure, for aesthetic purposes it could leave out that line but console progress output is tricky as it is hehe.

**Comment by cxj** [comment]
I disagree.  

The line contains the word "Downloading" and hence the percentage displayed generally refers to the amount of data downloaded.  Therefore, the message is misleading.

If instead the line said "Progress:  100%" then your argument would have some validity, although it would remain user un-friendly.  One does not normally run composer with `-vvv`.  Without that extra verbose output, all that is seen is:

```
  - Installing cxj/phpsyslog (v1.1.3)
  Downloading:  100%
  Downloading:  100%
  Downloading:  100%
  ...
```
Does that look like success?  Or failure?  It is in fact repeated network failures.

**Comment by curry684** [comment]
Valid point, but I only indicated the message is *factually* correct. The download operation is complete. I won't contest that it's slightly user-unfriendly and unintuitive hehe.

**Comment by curry684** [comment]
On my Windows dev machine the progressive logging doesn't work because of non-decorated shells and thus it's much clearer, so I'll leave 'fixing' this to someone else.

**Comment by Seldaek** [comment]
I solved it as I could.. but not sure if I caught all cases, if you still encounter it please give a complete reproduce case.
