### ISSUE TITLE
"composer install" excruciatingly slow on a Windows machine

### ISSUE THREAD

**Issue by garethellis36** [composer/composer#5115]
I have one app where `composer install` is run on the production server as part of the deploy process. I know this isn't ideal and I'm in the process of putting together a proper build process with a Jenkins server, but in the meantime, Composer is very slow on this Windows server. The same project will run composer install very quickly on my dev machine. 

The particularly slow points I have noticed:
- When updating a dependency version, removing the existing version from the file system takes ages. Often I have to kill composer, manually delete the existing dependency from the file system and re-run (composer install is running in a repo folder separate from the prod app, so no panic there folks :-))
- I have one dependency which is from a private Git repository on Bitbucket. It's installed as a VCS repo, not as a package. When installing this, it is very slow. It is quite slow to clone the repo but even slower when it reaches the `git checkout` stage. The repo is not large in size (a few MB) but has a few hundred files. I can sit and watch the files dropping into the folder in Windows Explorer and it takes a couple of seconds for each file. Installing packages is quick.
- While all of this is happening PHP CPU usage is really high and the whole system slows down. I can only run composer install on the weekend when no one is using the app because it kills the web server performance while it's running.

The server is running Windows Server 2008 R2, has the latest Composer and the latest Git for Windows (2.7.4). PHP 5.6.13 with opcache, no xdebug. Git seems otherwise snappy on the server (e.g. when pulling updates for the main app repo).

Any ideas please on how to investigate this? I ran `composer diagnose` and the only problem it came up with was the license.

**Comment by alcohol** [comment]
Sorry, but no clue to be honest. The only thing that would really provide insight in a situation like this, is actually running it with xdebug profiling or the blackfire profiler, and reviewing the profile.

**Comment by Seldaek** [comment]
No idea either. It runs fine on windows in general, but Server 2008 hasn't been tested much AFAIK. It's mostly used on dev machines on windows, and few devs work on win server I guess. Closing as I have no idea what we can do, but if you do figure anything out please update with details.

**Comment by ducktype** [comment]
Hello, after running composer with the following parameters:
`php composer.phar update --prefer-dist --verbose -vvv --profile --no-interaction`
I've noted that after every line like this:
`[158.8MB/9.37s] Downloading http://packagist.org/p/socialconnect/openid%24703c30dacb37fc8ff100f7a3897e15d7fb80bed731f1206ef8a4603e26df1eb4.json`
composer go totally idle (cpu/disk/net) waiting for something and when a timeout occurs then resume.
This happens many times in a single run.
So after trying to track the problem with the help of ProcessMonitor i've found that before going idle some ipv6 network event occurs.
So i've tried to disable ipv6 on my windows machine with this reg option (needs restart) and now all works fast as expected:
```
REGEDIT4

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters]
"DisabledComponents"=dword:ffffffff
```

I think Composer or curl php extension is doing something wrong between ipv4 and ipv6, someone can verify this?

**Comment by Seldaek** [comment]
@ducktype see https://getcomposer.org/doc/articles/troubleshooting.md#operation-timed-out-ipv6-issues- - IPv6 issues occur sometimes but they are generally due to user networks being broken rather than on our side as IPv6 works fine for many people on our end.
