### ISSUE TITLE
 Call to undefined method Composer\Installer\LibraryInstaller::initializeBinDir()

### ISSUE THREAD

**Issue by chromax** [composer/composer#5117]
"the json is private as it points to internal company repo's"
When I run this command:
composer install
composer command -vvv (please include -vvv!)
Composer version 1.0-dev (f542b0f32d044a9cc958510303b299685f7e7cc1) 2016-03-26 09:49:28
I get this output:
Call to undefined method Composer\Installer\LibraryInstaller::initializeBinDir()
And I expected this to happen:
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Generating autoload files

**Comment by rockcoolt** [comment]
Use version :  1.0.0-alpha11 (2015-11-14)

 it work ! 

https://getcomposer.org/download/

**Comment by chromax** [comment]
i use it :+1:  , but i wished to note the issue.

**Comment by Seldaek** [comment]
Please run with `composer install -v` and post the output you get including the stack trace of the error because I don't quite see where this call comes from.

**Comment by chromax** [comment]
sure , here is the output
E:\sources\########>php composer.phar install -v
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Dependency resolution completed in 0.001 seconds
Analyzed 66 packages to resolve dependencies
Analyzed 101 rules to resolve dependencies
############################
###########################

  - Installing pear-pear.php.net/log (1.9.3)
    Loading from cache
PHP Fatal error:  Call to undefined method Composer\Installer\LibraryInstaller::initializeBinDir() in phar://E:/sources/#######/composer.phar/src/Composer/Installer/PearInstaller.php on line 55

Fatal error: Call to undefined method Composer\Installer\LibraryInstaller::initializeBinDir() in phar://#########/composer.phar/src/Composer/Installer/PearInstaller.php on line 55

i hashtagged the private parts knowngly that the composer version 1.0.0-alpha11 is working perfectly

**Comment by Seldaek** [comment]
Can you try after a `composer self-update` again? I think it's fixed but would be good to know for sure.

**Comment by ted0xff** [comment]
Thank you !
I have no link to all of this, I was just installing Roundcube on my personnal site and fall in this bug when installing plugins :)

This works.
