### ISSUE TITLE
Could not find package * at any version for your minimum-stability (stable). Check the package spelling or your min   imum-stability

### ISSUE THREAD

**Issue by ivantree** [composer/composer#5118]
With the following composer.json:

```json
{
    "name": "ivantree/yii2-vticker",
    "description": "Vertical News Ticker",
    "type": "yii2-extension",
    "keywords": ["yii2","extension"],
    "license": "Apache-2.0",
    "authors": [
        {
            "name": "Ivantree",
            "email": "cxmiaomu@qq.com"
        }
    ],
    "require": {
        "yiisoft/yii2": "*"
    },
    "autoload": {
        "psr-4": {
            "ivantree\\vticker\\": ""
        }
    }
}
```

When I run this command:

php composer.phar require  "ivantree/yii2-vticker": "*" -vvv
composer command -vvv (please include -vvv!)
```

I get this output:

Reading ./composer.json
Loading config file C:/Users/Buybuy/AppData/Roaming/Composer/config.json
Loading config file C:/Users/Buybuy/AppData/Roaming/Composer/auth.json
Loading config file ./composer.json
Checking CA file C:\Users\Buybuy\AppData\Local\Temp\composer-cacert-39eaf16e26c08cc90d728865f1c60406ee5d864d5963f72ede2a1cbb127f95ca.pem
Executing command (D:\wamp\buybuy): git branch --no-color --no-abbrev -v
Executing command (D:\wamp\buybuy): git describe --exact-match --tags
Reading C:/Users/Buybuy/AppData/Roaming/Composer/composer.json
Loading config file C:/Users/Buybuy/AppData/Roaming/Composer/config.json
Loading config file C:/Users/Buybuy/AppData/Roaming/Composer/auth.json
Loading config file C:/Users/Buybuy/AppData/Roaming/Composer/composer.json
Loading config file C:\Users\Buybuy\AppData\Roaming\Composer/auth.json                   
Reading D:\wamp\buybuy/vendor/composer/installed.json
Reading C:/Users/Buybuy/AppData/Roaming/Composer/vendor/composer/installed.json
Loading plugin yii\composer\Plugin
Loading plugin Fxp\Composer\AssetPlugin\FxpAssetPlugin
Downloading https://packagist.phpcomposer.com/packages.json
Writing C:/Users/Buybuy/AppData/Local/Composer/repo/https---packagist.phpcomposer.com/packages.json into cache
Downloading https://packagist.phpcomposer.com/p/all%2447fd69b4c720d0f9b9aaa6857cc58136c90af2e9b2f7981d7c353f94b1dd9b80.json
Writing C:/Users/Buybuy/AppData/Local/Composer/repo/https---packagist.phpcomposer.com/p-all.json into cache


  [InvalidArgumentException]
  Could not find package * at any version for your minimum-stability (stable). Check the package spelling or your min
  imum-stability


Exception trace:      () at phar://D:/wamp/buybuy/composer.phar/src/Composer/Command/InitCommand.php:642
 Composer\Command\InitCommand->findBestVersionForPackage() at phar://D:/wamp/buybuy/composer.phar/src/Composer/Command/InitCommand.php:365                                                                                                      Composer\Command\InitCommand->determineRequirements() at phar://D:/wamp/buybuy/composer.phar/src/Composer/Command/RequireCommand.php:108                                                                                                       Composer\Command\RequireCommand->execute() at phar://D:/wamp/buybuy/composer.phar/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar://D:/wamp/buybuy/composer.phar/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at phar://D:/wamp/buybuy/composer.phar/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar://D:/wamp/buybuy/composer.phar/src/Composer/Console/Application.php:166
 Composer\Console\Application->doRun() at phar://D:/wamp/buybuy/composer.phar/vendor/symfony/console/Application.php:123                                                                                                                        Symfony\Component\Console\Application->run() at phar://D:/wamp/buybuy/composer.phar/src/Composer/Console/Application.php:99
 Composer\Console\Application->run() at phar://D:/wamp/buybuy/composer.phar/bin/composer:43                            
  require() at D:\wamp\buybuy\composer.phar:25

And I expected this to happen:

**Comment by Seldaek** [comment]
The problem is your command `composer require "ivantree/yii2-vticker": "*"`, you shouldn't have a space there, because it sees it as two package names then. Use `require "ivantree/yii2-vticker:*"`

**Comment by ivantree** [comment]
Problem 1
    - The requested package ivantree/yii2-vticker could not be found in any version, there may be a typo in the package name.

**Comment by Seldaek** [comment]
That's because https://packagist.org/packages/ivantree/yii2-vticker only exists in dev-master and that is too unstable for your minimum-stability, the error message isn't clear but will be fixed by #5120

**Comment by olubunmi708** [comment]
Thanks to Seldaek it worked.

**Comment by Prashantq** [comment]
[InvalidArgumentException]
  Could not find package magearray/restrictshippingpayment at any version for your minimum-stability (alpha). Check t
  he package spelling or your minimum-stability

**Comment by xabbuh** [comment]
There simply is no such package on packagist.org. If this package is provided by another repository, you need to add this repository explicitly to your `composer.json` file.

**Comment by superwebdeveloper** [comment]
this is an issue that comes up when trying out composer for a project the first time.

**Comment by ahuggins** [comment]
Yeah, @superwebdeveloper I think when you first create a repo and connect to Packagist, you need to create a "release" in Github. If not, it defaults to "dev-master" which if the repo/project you are trying to add to has "stable" as the minimum stability, it causes problems here. But if you go into Github for your new repo and navigate to "Release" and create a new release, even one tagged "0.0.1" then Packagist (Composer) will accept that as a satisfactory minimum-stability match.

**Comment by superwebdeveloper** [comment]
@ahuggins thank you for the response. I did create a release with my test package and.... ok I got a different error, I will be working on that one later. thanks, for the reply.

**Comment by woshixieming** [comment]
Thanks for everyone!

**Comment by omitobi** [comment]
As for me with similar issue, my fix was putting the `~` before the package name. For example `composer require "pack/package ~0.0.1"`. This was after I created a Release 0.0.1 on Github

**Comment by menasheh** [comment]
This feels wrong - how do you set minimum stability differently?

**Comment by RGZorzo** [comment]
Have a look at yout **composer.lock**, you'll find a line like:  

`"minimum-stability": "stable",`

**Comment by huchunguang** [comment]
@ahuggins your answer is very helpful.to fixed the problem spend any time until see your answer

**Comment by tantana5** [comment]
I have encountered the same problem
I can not require my package via composer

I did all the above but failed:

- add "minimum-stability": "dev" to composer.json - **FAILED**
- composer require "tantana5/laravel-settings": "*" - **FAILED**
- composer require "castlepointanime/brancher @dev" - **FAILED**

Finally, I found the cause. **Github is not the main Composer repository**, but the **packagist.org**
You must submit your package with [https://packagist.org/packages/submit](url)
You can manual update in packagist or use webhook in github automaticaly

[curl \
  -X POST \
  -H 'Content-Type: application/json' \
  -d '{"repository":{"url":"https://github.com/tantana5/laravel-settings"}}' \
  'https://packagist.org/api/update-package?username=tantana5&apiToken=MY_API_TOKEN']

Of course, You must git push tag and release version in github

[https://jameshfisher.com/2017/11/06/how-to-release-a-composer-package.html](url)
Hope to help some one.

**Comment by pawankparmar** [comment]
> Yeah, @superwebdeveloper I think when you first create a repo and connect to Packagist, you need to create a "release" in Github. If not, it defaults to "dev-master" which if the repo/project you are trying to add to has "stable" as the minimum stability, it causes problems here. But if you go into Github for your new repo and navigate to "Release" and create a new release, even one tagged "0.0.1" then Packagist (Composer) will accept that as a satisfactory minimum-stability match.

Thank You...

**Comment by abdoevs** [comment]
> I ended up [flagging the dependency](https://igor.io/2013/02/07/composer-stability-flags.html) with `@dev` like this:
> 
> ```
> composer require "castlepointanime/brancher @dev"
> ```

thank you 👍 :)

**Comment by RomanMahiiovych** [comment]
you must register at **packagist.org**, not packagist.com

**Comment by augustofagioli** [comment]
It is worth to be said this issue disappears when calling the "composer require ..." from the root directory of the project.

**Comment by sneakyx** [comment]
And I had to wait 2 Minutes after releasing tag 0.01...

**Comment by traster100** [comment]
use
```
composer create-project --stability=dev castlepointanime/brancher
```

**Comment by litto** [comment]
I also encountered same problem. But Can solve by doing the following steps.
1) Check Atleast one tag or release has been created for that Repo. If no, create one
2) Make sure webhook has been enabled for packagist by generating token . This will ensure all your push changes to git repo will be merged with packagist.
3)Now in composer for installation put like:-  

composer require username/reponame:version

for eg: composer require litto/message:v1.0

This will install the repo
