### ISSUE TITLE
Can't re-install or self-update composer

### ISSUE THREAD

**Issue by keithslater** [composer/composer#5131]
```
composer self-update
Updating to version e8b1a5f35772e39ca21ab855a278bd84a0a534b2.
    Downloading: 100%


  [ErrorException]
  openssl_verify(): Don't know how to get public key from this private key

```

```
php composer-setup.php
All settings correct for using Composer
Downloading...
PHP Warning:  openssl_verify(): Don't know how to get public key from this private key in /Users/keith/composer-setup.php on line 495
PHP Stack trace:
PHP   1. {main}() /Users/keith/composer-setup.php:0
PHP   2. process() /Users/keith/composer-setup.php:13
PHP   3. installComposer() /Users/keith/composer-setup.php:111
PHP   4. openssl_verify() /Users/keith/composer-setup.php:495

Warning: openssl_verify(): Don't know how to get public key from this private key in /Users/keith/composer-setup.php on line 495

Call Stack:
    0.0027     698816   1. {main}() /Users/keith/composer-setup.php:0
    0.0029     699376   2. process() /Users/keith/composer-setup.php:13
    0.0040     701312   3. installComposer() /Users/keith/composer-setup.php:111
    1.9883    2293248   4. openssl_verify() /Users/keith/composer-setup.php:495

PHP Warning:  openssl_verify(): supplied key param cannot be coerced into a public key in /Users/keith/composer-setup.php on line 495
PHP Stack trace:
PHP   1. {main}() /Users/keith/composer-setup.php:0
PHP   2. process() /Users/keith/composer-setup.php:13
PHP   3. installComposer() /Users/keith/composer-setup.php:111
PHP   4. openssl_verify() /Users/keith/composer-setup.php:495

Warning: openssl_verify(): supplied key param cannot be coerced into a public key in /Users/keith/composer-setup.php on line 495

Call Stack:
    0.0027     698816   1. {main}() /Users/keith/composer-setup.php:0
    0.0029     699376   2. process() /Users/keith/composer-setup.php:13
    0.0040     701312   3. installComposer() /Users/keith/composer-setup.php:111
    1.9883    2293248   4. openssl_verify() /Users/keith/composer-setup.php:495

Signature mismatch, could not verify the phar file integrity
```

This has been running on my computer for a few years and I have been able to do self-updates regularly in the past.

OpenSSL 1.0.2f  28 Jan 2016

**Comment by curry684** [comment]
Would appear your CA's are outdated. Have you tried running `update-ca-certificates`?

**Comment by keithslater** [comment]
I don't believe OS X has that command. I did remove any expired certificates from keychain before submitting this issue but it didn't solve the problem.

**Comment by curry684** [comment]
Ah didn't notice OSX, know nothing of that. @alcohol a clue?

**Comment by rquadling** [comment]
http://kb.kerio.com/product/kerio-connect/server-configuration/ssl-certificates/adding-trusted-root-certificates-to-the-server-1605.html

**Comment by keithslater** [comment]
What root certificate would I need to add?

**Comment by rquadling** [comment]
https://curl.haxx.se/ca/cacert.pem (convert to .crt)

**Comment by alcohol** [comment]
Never had such an issue on OSX myself. Haven't tried the new installer yet though to be honest. Will give it a go later today maybe.

**Comment by Seldaek** [comment]
I don't think this has anything to do with CA or SSL in general. It fails at https://github.com/composer/getcomposer.org/blob/6e22159d7594645726af6a9fb05b52f063eab06d/web/installer#L489-L499 which is just the verification of the phar's signature against the composer pubkey.

The error makes no sense to me though as it talks about a private key, but it is given a public key.. http://stackoverflow.com/questions/11399613/issues-with-openssl-on-php-different-behaviour-for-different-versions seems to suggest it's outdated ssl libs. 

I don't know where the SSL version you posted comes from, is that the PHP openssl version? If so that sounds recent enough. Which PHP version do you have though?

**Comment by keithslater** [comment]
PHP 5.4.45 (cli) (built: Dec 13 2015 11:13:28)

The SSL version is from openssl on the command line.

php -i -
OpenSSL Library Version => OpenSSL 0.9.8zh 14 Jan 2016
OpenSSL Header Version => OpenSSL 1.0.2e 3 Dec 2015

**Comment by Seldaek** [comment]
It's weird that the two versions don't match there. I have this:

OpenSSL Library Version => OpenSSL 1.0.2f  28 Jan 2016
OpenSSL Header Version => OpenSSL 1.0.2f  28 Jan 2016

Not sure if that mismatch is causing the bug.. Have you tried reinstalling or otherwise upgrading php?

**Comment by keithslater** [comment]
For some reason it randomly works today.. Not sure what changed.

**Comment by rquadling** [comment]
Cosmic rays probably.

**Comment by marvinGitHub** [comment]
I have observed similar error when upgrading composer to latest version.

```
  [ErrorException]
  openssl_verify(): Don't know how to get public key from this private key
```
PHP 5.3.29 (cli) (built: Aug 15 2014 19:17:16)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2014 Zend Technologies

OpenSSL/1.0.0e

**Comment by rdubigny** [comment]
When I run `curl -sS http://getcomposer.org/installer | php`, I get:
```
PHP Warning:  openssl_verify(): supplied key param cannot be coerced into a public key in - on line 576
PHP Warning:  openssl_free_key() expects parameter 1 to be resource, boolean given in - on line 577
Signature mismatch, could not verify the phar file integrity
```

As I workaround for my dev env, I used `curl -sS http://getcomposer.org/installer | php -- --disable-tls`.

PHP 5.6.23-1+deprecated+dontuse+deb.sury.org~trusty+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

OpenSSL 1.0.1f 6 Jan 2014

**Comment by janokary** [comment]
I just run
`sudo composer self-update --update-keys`
and followed the instructions about coping the keys from
https://composer.github.io/pubkeys.html

It worked for me nicely.
