### ISSUE TITLE
Checking composer.json: FAIL

### ISSUE THREAD

**Issue by urbanlegion** [composer/composer#5132]
Hi, I tried to continue the previous thread with this error but it was closed.

In anycase, this is what im getting:

```
Checking composer version: FAIL
You are not running the latest stable version, run `composer self-update` to update (37a1e12672a57813d34251c640be1e3dc0fe4537 => 1.0.0-beta2)
```

**Comment by curry684** [comment]
Did you run `composer self-update` to update to the latest stable version?

**Comment by alcohol** [comment]
The description of the issue is quite self-explanatory I believe?
