### ISSUE TITLE
Composer Installation

### ISSUE THREAD

**Issue by LarryTX** [composer/composer#5133]
When I attempt to install Composer (downloaded today) running composersetup.exe on Windows 10, I get this error message: Your PATHEXT environment variable is missing a required value: .BAT.

My PATHEXT variable definition looks like this: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.MSC

Clearly .BAT is and has always been a part of the PATHEXT variable. At this point, I am completely blocked because the installer does not recognize something that is clearly there. How can I proceed?

**Comment by alcohol** [comment]
Best to submit this issue to [composer/windows-setup](/composer/windows-setup).

/cc @johnstevenson

**Comment by johnstevenson** [comment]
@LarryTX Did you solve this? The error happens when a User PATHEXT variable has been set, which overrides the System one. What was/is in your System one?

**Comment by LarryTX** [comment]
I gave my System PATHEXT variable in the original posting, and it includes .BAT. The problem was that I had installed Ruby and didn't realize that it set a User PATHEXT variable with just .RB and .RBW in it. This whole thing is really interesting because the User PATHEXT variable didn't seem to interfere with the .EXE or .PHP extensions but did with the .BAT extension. Both .EXE and .PHP were in the System PATHEXT but not in the User PATHEXT.

**Comment by johnstevenson** [comment]
Thanks, you info has been very helpful. I have just tried the latest rubyinstaller and it now does this to the User PathExt:

- `%PATHEXT%;.RB;.RBW`, which pulls in the System values and works

However, I wasn't expecting an expandable value, so I need to change this in Composer-Setup. I may also prepend `%PATHEXT%` to the user variable if it is missing, or at least give a more useful error message. 

Incidentally, .PHP isn't in your PathExt (from your example). It is invoked because the `php.exe` is in your Path.

**Comment by LarryTX** [comment]
Actually, my User variable had %PATHEXT% in it. It specifically caused Composer-Setup to fail. I had to delete the User variable and add the Ruby extensions to the System variable. When I did that, it worked like a charm. (We might should make sure of how Windows versions are involved. I'm on Windows 10.) Sorry about the PHP thing. I was writing in a hurry.

**Comment by johnstevenson** [comment]
Right, so I definitely screwed it up for you! Sorry.

**Comment by LarryTX** [comment]
Hey, you didn't screw anything up. We're all just floundering out here as Microsoft screws around with us and fails to give us information that we need. (It would help if the Ruby installer didn't go behind our backs as well and not tell us what its doing.)  Actually, I found this statement on StackOverflow: System environment variables are global to all users, while users environment variables are specific only to the currently logged in user.

Statements like that can get the novice user into a lot of trouble because they don't take into account when the same variable name is used for User and System variables. (Actually, to make matters worse, that same StackOverflow entry contains a statement that makes it look like the User variable automatically inherits from the System variable. And that's the answer that got the most points!) Go figure.

Anyway, thanks for your response. Most folks don't bother.

**Comment by johnstevenson** [comment]
Yeah, it would be nice if this stuff could be easily found on MSDN (it is probably in there somewhere). I don't know when the rubyinstaller prepended the %PATHEXT% - I don't think it used to. Anyway, I should have programmed more defensively.

**Comment by Radmation** [comment]
Hi. I found this thread and I am having the same problem. I also have the %PATHEXT% which makes sense because I have ruby installed. So the solution if I am understanding this correctly is to remove that? What should I replace it with so Ruby still functions correctly?

**Comment by johnstevenson** [comment]
Apologies for not having fixed this yet. If you add `;.RB;.RBW` to your System PathExt then delete your User one, everything will still work.

**Comment by lingeors** [comment]
I have met the problem just now, and it help me a lot, thank you!
