### ISSUE TITLE
BC broken - cannot install fxp/composer-asset-plugin

### ISSUE THREAD

**Issue by DirtyB** [composer/composer#5140]
With the latest version of composer I cannot install fxp/composer-asset-plugin
(https://github.com/francoispluchino/composer-asset-plugin)

running 

`composer global require fxp/composer-asset-plugin`

I get
                                                                                   
  [ReflectionException]                                                             
  Class Fxp\Composer\AssetPlugin\Repository\NpmRepository does not exist            
  [ErrorException]                                                                  
  Declaration of Fxp\Composer\AssetPlugin\Repository\AbstractAssetsRepository::wha  
  tProvides() should be compatible with Composer\Repository\ComposerRepository::wh  
  atProvides(Composer\DependencyResolver\Pool $pool, $name, $bypassFilters = false  
  )                                                                                 
                

it looks like plugin's error, but if I do the same on elder version of composer it works

**Comment by Seldaek** [comment]
Of course it does... Every change breaks that godforsaken plugin :/

See https://github.com/francoispluchino/composer-asset-plugin/pull/206 for a fix of the plugin.
