### ISSUE TITLE
Fix GitHub token persistence

### ISSUE THREAD

**Issue by nikolay** [composer/composer#5143]
When I run this command:

```Bash
composer config -g github-oauth.github.com "${GITHUB_TOKEN}"
```

the above is being called an automated script, the file `auth.json` is blank. When I run the same command from the CLI, it works and the token gets into `auth.json`.

Please, advise!

**Comment by Seldaek** [comment]
I guess your automated script whatever it is has no $HOME env var defined, so it doesn't know where to store it?

**Comment by nikolay** [comment]
@Seldaek It surely does though.

**Comment by curry684** [comment]
Can you provide output with -vvv option enabled?
