### ISSUE TITLE
Add parameter to specify json file

### ISSUE THREAD

**Issue by fanky10** [composer/composer#5145]
I want a different composer.json file name to distinguish between dev / test / prod environments

I wan to run this (kind of) command:

```
composer install --filename=composer-test.json
```

And I expected this to happen:
Use the file provided

**Comment by xabbuh** [comment]
You can use the `$COMPOSER` environment variable for that: https://getcomposer.org/doc/03-cli.md#composer

**Comment by Seldaek** [comment]
Yup, `COMPOSER=composer-test.json composer install` will do what you want. Having per-environment dependencies is not really something that's recommended though, beyond the require/require-dev.

**Comment by fanky10** [comment]
thanks everyone for the super quick response. I will work with that then.
