### ISSUE TITLE
Loading repositories recursively - warning

### ISSUE THREAD

**Issue by duzymaju** [composer/composer#5149]
I had the same situation as @maidmaid in #4754 and I spent a lot of time trying to figure out what's wrong. The only information I received was that `no matching package found` (even with `-vvv` flag). I think it could be a good idea to add any kind of warning about prohibition of loading repositories recursively during `composer update` and it could saves a lot of time of many developers who don't know Composer very much.

**Comment by curry684** [comment]
But how are we going to warn about it? The conceptual problems are huge - we can't know we're ignoring a repository until we selected the version referencing it, which likely is never going to happen if you expect it to include packages that it cannot find. It's the chicken and the egg all over again.

Also, it's just not an error. It's well documented that it's being ignored, like many other configuration options, outside root. It doesn't make sense for them to be present outside of root. Why should we throw a warning on something that's explicitly not *wrong*?

**Comment by alcohol** [comment]
Composer is not capable of providing more feedback in this scenario. If you feel that the documentation is inadequate however, please submit a pull request with suggested changes.

**Comment by duzymaju** [comment]
I know that it isn't any Composer's error - it's definitely user's problem so I just think that it could be helpful to let him know that he's wrong just displaying simple warning. According to @curry684 I understand that Composer ignore `vcs` sources anywhere except "first level" so there is no information if any of it contains defined package (and Composer hasn't got enough data) but in my opinion warning could appear in case of using any unsupported `vcs` source and it could inform user (in verbose mode only) that this particular `vcs` source isn't supported (with reference to documentation which is very adequate) - Composer have all necessary information in this case, right?

**Comment by stof** [comment]
@duzymaju but defining repositories in a package to use them during the development of the tool is also a valid usage. And it should not show a warning to anyone using it.

**Comment by alcohol** [comment]
> could be a good idea to add any kind of warning about prohibition of loading repositories recursively

The problem is that we don't load repositories recursively, so we don't even know about their existence.

So even if we determine that we cannot find a package (because we are missing this deeply nested repository), we cannot know that it is because of the aforementioned reasons.

**Comment by duzymaju** [comment]
@stof: It's valid in "first level of dependency", but it isn't supported on next "levels".

@alcohol: Let's use @maidmaid example from #4754: in `vendor/root` package we have `vendor/a` repository added as `vcs` and in this repository Composer can find `root/a` package (or `vendor/a` - I'm confused a little bit but it doesn't matter) with another `vcs` repository in it. So Composer "knows" only that inside `root/a`/`vendor/a` package there is `git@vendor.com:vendor/b.git` repository added as `vcs` and because it's second "level", it should (in my opinion) notify user that

> Repository `git@vendor.com:vendor/b.git` was omitted because adding repositories recursively is prohibited. See https://getcomposer.org/doc/faqs/why-can%27t-composer-load-repositories-recursively.md for details

And then of course Composer can return an error about missed `root/b`/`vendor/b` package like it is today.
What do you think?
