### ISSUE TITLE
Invoke composer command from script

### ISSUE THREAD

**Issue by neomerx** [composer/composer#5153]
How can I refer composer command in `scripts` section?

Something like below to invoke my command and then dump optimized autoload.
```json
{
    "scripts": {
        "build": ["...", "@dump -o"],
    }
}
```

**Comment by alcohol** [comment]
Most of the time this is not necessary. Can you explain your use-case more elaborately? Cause right now I don't see any need for this. You can just pass the `--optimize-autoloader` flag to install or update.

**Comment by neomerx** [comment]
I'd like to have a set of simple commands in the app for testing, docker, app optimization, etc. Some of the are combinations of pure composer commands with composer scripts e.g. `\MyScrips::doSomething` and scripts like command line.  Currently composer can combine command line and PHP scripts but not his own commands. It would be nice to have an ability to combine them in order to have
```
$ composer build
```
rather than
```
$ composer update && composer my-command1 && composer dump -o && composer dump-my-cache
```

**Comment by neomerx** [comment]
_commands as first class citizens in composer_ if formulate it as a slogan :smile:

**Comment by Seldaek** [comment]
See https://github.com/composer/composer/commit/60ce2324bcf0b784d66444760c6f996b4a6ca902 - you can call them with `@composer ...` now.

**Comment by neomerx** [comment]
Thanks a lot! This feature is super cool! Composer could be used as a replacement for basic UI instead of Symfony console.
