### ISSUE TITLE
composer-setup.php does not find valid CA

### ISSUE THREAD

**Issue by popovicidinu** [composer/composer#5157]
Hi.

When I try to run "php composer-setup.php" I get the following error:

```
All settings correct for using Composer
PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /local/www/htdocs/composer-setup.php on line 664
PHP Warning:  file_get_contents(): Failed to enable crypto in /local/www/htdocs/composer-setup.php on line 664
PHP Warning:  file_get_contents(https://getcomposer.org/versions): failed to open stream: operation failed in /local/www/htdocs/composer-setup.php on line 664
PHP Warning:  Invalid argument supplied for foreach() in /local/www/htdocs/composer-setup.php on line 447
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'There is no version of Composer available for your PHP version (5.6.16)' in /local/www/htdocs/composer-setup.php:456
Stack trace:
#0 /local/www/htdocs/composer-setup.php(112): installComposer(false, false, 'composer.phar', false, false, false, 'stable')
#1 /local/www/htdocs/composer-setup.php(13): process(Array)
#2 {main}
  thrown in /local/www/htdocs/composer-setup.php on line 456
```

I'm not entirely sure what is happening here. A similar issue was raised by our sysadmin not long ago ( https://github.com/composer/composer/issues/5017 ), but that one was fixed and indeed it used to work (until now). The machine we're using has PHP 5.6.16. 

Any thoughts?

**Comment by alcohol** [comment]
Fixed formatting, I think the error should be rather self-explanatory now.

As for why your openssl setup is not working properly, I cannot provide an immediate answer. There could be numerous reason. Try looking through our issue list for other openssl errors and what kind of solutions users have previously attempted.

**Comment by stof** [comment]
I suspect using an old version of openssl, as the message tells that it tries to connect with SSLv3

**Comment by popovicidinu** [comment]
Our system admin has managed to find the issue (in the end). It seems that the openssl.capath setting was missing from /local/php5/etc/conf.d/openssl.ini.
