### ISSUE TITLE
composer install writes non-error output to stderr

### ISSUE THREAD

**Issue by prometheas** [composer/composer#5159]
So, long story short, I'm writing some nodejs-based CLI tooling for my dev team which uses does a composer install along the way, and discovered during my debugging that composer writes the following data out to `stderr` (even though there is NO error reported, and execution returns a `0` status code):

```
Loading composer repositories with package information\nUpdating dependencies (including require-dev)
  - Installing get-composed-tests/generic-library (1.0.0)
    Symlinked from /var/project/test/data/composer-registry/packages/generic-library/

  - Installing get-composed-tests/example-plugin (1.8.3)
    Symlinked from /var/project/test/data/composer-registry/packages/example-plugin/

  - Installing get-composed-tests/example-muplugin (1.22.3)
    Symlinked from /var/project/test/data/composer-registry/packages/example-muplugin/

  - Installing get-composed-tests/example-theme (1.22.3)
    Symlinked from /var/project/test/data/composer-registry/packages/example-theme/

Writing lock file
Generating autoload files
```

Is this intended?

**Comment by alcohol** [comment]
Yes this entirely intentional. Please use the search functionality next time before asking a question. This is not the first time this topic has been brought up :-)

**Comment by curry684** [comment]
http://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout

**Comment by prometheas** [comment]
Gah! Guilty as charged, @alcohol 😆 

And thanks for that link, @curry684—it sheds some really useful light on design decisions I'm currently messing with in my current project ❤️
