### ISSUE TITLE
why jquery asset do not follow the rule?

### ISSUE THREAD

**Issue by huxingbang** [composer/composer#5167]
jqueryAsset
do not follow the AssetManager  hashCallback settings?
if set AssetManager.hashCallback = function($path){
  return "v2";
}

v2/jquery.js will not found . but v2/yii.js is ok.

**Comment by huxingbang** [comment]
it's sad when i have mutilple machine run yii2 which with not same file path

**Comment by staabm** [comment]
sounds like this is a plugin issue and you should report it to the plugin..

**Comment by alcohol** [comment]
Wrong issue tracker.
