### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by yorickkooy20** [composer/composer#5168]
Hi Guys,

I try to install composer on my macbook. But it seems i have some issues to connect to getcomposer.org. It takes like ~30 second to load the website. On my pc next to my macbook same internet are no issues at all. Same for downloading composer. On my pc it will install directly. On the macbook i get the following error: curl: (56) SSLRead() return error -9806

When I run this command:

```
curl -sS https://getcomposer.org/installer | php
```

I get this output:

```
curl: (56) SSLRead() return error -9806
```

**Comment by alcohol** [comment]
Looks like you have a broken SSL setup on your Mac. Please search the issue tracker on Github for reference material.
