### ISSUE TITLE
Missing Shell Menu at Installation

### ISSUE THREAD

**Issue by tomhklab** [composer/composer#5169]
Hi,

I am attempt to install Composer with Shell Menu, but it doesn't seem to have that option in the installer. is there anyway I can add this feature after installing?

Thanks.

**Comment by curry684** [comment]
No, the feature was completely removed in the new installer.

**Comment by alcohol** [comment]
Please move this to [`composer/windows-setup`](/composer/windows-setup). :-)

**Comment by samihijlawi** [comment]
same problem :(

**Comment by NgYueHong** [comment]
Why it is removed? It is a very important & useful feature that enable us to directly use the composer on the selected folder.

**Comment by Seldaek** [comment]
Please see https://github.com/composer/windows-setup/issues/53#issuecomment-270747101
