### ISSUE TITLE
secure-http option bites with git-type urls git://

### ISSUE THREAD

**Issue by ktomk** [composer/composer#5173]
I'm using composer as  a dependency and just moved it to ^1.0.0. It must have been at an older state where the secure-http option was not yet available.

Now when downloading a git-type package with a git://... URL, I get the following error:

> Your configuration does not allow connections to git://github.com/OpenMage/magento-mirror.git. See https://getcomposer.org/doc/06-config.md#secure-http for details.

Which does not make much sense to me as it's not HTTP.

The error has been recorded: https://travis-ci.org/ktomk/n98-magerun/jobs/122019645

The error message however is correct when HTTP URLs are used (here with xdebug and more verbose): https://circleci.com/gh/ktomk/n98-magerun/253

Just wanted to report it as the error message does not make much sense to me. I understand this is non-standard composer use.

**Comment by ktomk** [comment]
As I need to have HTTP in this case, I had set the secure-http option in config to false. Now the error reported does not appear any longer (before_script section in https://travis-ci.org/ktomk/n98-magerun/jobs/122022682) which is expected.

And just seeing that **git** is listed as a known insecure protocol:

~~~
        // Throw exception on known insecure protocols
        if (in_array($parsed['scheme'], array('http', 'git', 'ftp', 'svn'))) {
            throw new TransportException("Your configuration does not allow connections to $url. See https://getcomposer.org/doc/06-config.md#secure-http for details.");
        }
~~~

Therefore closing as bogus.

**Comment by curry684** [comment]
I'll clarify as I typed that comment hehe. Please refer to https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols:

> Next is the Git protocol. This is a special daemon that comes packaged with Git; it listens on a dedicated port (9418) that provides a service similar to the SSH protocol, but with **absolutely no authentication**. [...]

> The downside of the Git protocol is the lack of authentication. It’s generally undesirable for the Git protocol to be the only access to your project. Generally, you’ll pair it with SSH or HTTPS access for the few developers who have push (write) access and have everyone else use git:// for read-only access. 

As Composer isn't just about *read* access, but actually *downloading code that you intend to put on production servers* using plain `git://` is just well.... pretty much terribly insecure, and therefore restricted.

**Comment by ktomk** [comment]
Yeah, I finally realized that, I also see it's possible to replace git://... with https://... for Github type git but next to Github links we also have Sourceforge ones and their mirror network does not support 100% HTTPS. At least we do checksum verification of downloaded packages (thanks to composer donwloader :+1: :) ).

Exceptional thanks to you @curry684 for references, quote and heads-up.

**Comment by patrickconroy** [comment]
I'm leaving a comment here instead of opening another issue since it's kind of related (let me know if I *should* open an issue. Right now, composer doesn't parse your ssh config, so it just assumes anything that doesn't contain `https` in the URL isn't secure. The way I (and I'm sure many others) have projects set up is that my connection URL starts with an alias that is in my ssh config. The connection itself is secure and uses authentication, but composer doesn't think it does. (And sorry if this has been brought up before, I searched issues and couldn't find anything similar.) E.g.:

```
pconroy ~$ cat ~/.ssh/config
Host git
   HostName privategitenterpriseserver.com
   User git
   Port 22
```

I have a satis server running, which has a `satis.json` that looks like this:
```
"repositories": [
        {"type": "vcs", "url": "git:Department/Repo.git"}
...
```
So, when I run an update/install it uses the ssh config to know where my enterprise server is. That works fine, *except* that composer is saying it's not secure. Is there any way composer can first parse the config instead of assuming it's insecure?

**Comment by stof** [comment]
@patrickconroy please open a dedicated issue for this, as it is a different case than the ``git://`` protocol (your case is probably caused by the fact that the code detects it wrongly as a ``git://`` protocol)

**Comment by ktomk** [comment]
Just commenting despite a new issue: I guess this is `parse_url`. But it's not a correct URL, perhaps putting `ssh://` scheme in front already solves it.

**Comment by curry684** [comment]
Yep, we use `parse_url` for this at `Config.php:415`. The URL is however just more or less malformed right now so you can hardly expect us to act differently:
```sh
$ php -r "print_r(parse_url('git:Department/Repo.git'));"
Array
(
    [scheme] => git
    [path] => Department/Repo.git
)
```
I'm not really sure how to circumvent this though, as `ssh://git:Department/Repo.git` isn't parsed at all for being totally malformed. Definitely makes this a different issue though. If you know of a reliable way to differentiate this link style from regular URLs do share.

**Comment by ktomk** [comment]
I have compiled the source from git-clone and the ietf rfc on the scheme syntax into a small helper class and put it into a PR (#5195). The rules to differ between the alternative scp-like syntax and local files is given in the git-clone manual page.
