### ISSUE TITLE
Install error 255

### ISSUE THREAD

**Issue by Rouzax** [composer/composer#5175]
**System info**
OS: Windows 2012 R2
PHP: PHP 7.0.5 X64
![image](https://cloud.githubusercontent.com/assets/4103090/14425855/b1eaf776-ffea-11e5-8ed4-cf93b625f51f.png)
![image](https://cloud.githubusercontent.com/assets/4103090/14425863/bf573848-ffea-11e5-8557-96214ec42749.png)

When I point to my 5.6.20 X86 php install it works like expected.

**Comment by Seldaek** [comment]
cc @johnstevenson

**Comment by Rouzax** [comment]
Just to add, if I after the install change my Path environment to change the PHP 5.6 version back to PHP 7.0 composer does not work.
Changing back the Path Environment to PHP 5.6 and Composer works.

**Comment by Seldaek** [comment]
Can you explain "compoesr does not work"? It definitely works with php7, so it might be something in your setup.

**Comment by Rouzax** [comment]
The install of composer does not work when I point to PHP 7.0 and the "does not work" part is in regards to my Ampache setup.
When I do `composer install --prefer-source --no-interaction` from my Ampache install it does nothing.
If I point the Path to 5.6 composer will install all dependencies.
```
c:\inetpub\wwwroot\ampache>composer install --prefer-source --no-interaction
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing wikimedia/composer-merge-plugin (v1.3.0)
    Cloning bfed1f8d4eb97e9ba80eee57ea46229d7e5364d9

  - Installing afterster/php-echonest-api (dev-master master)
    Cloning master

  - Installing symfony/process (v2.8.3)
```

**Comment by Seldaek** [comment]
It does nothing? No error no nothing? I have no idea what an ampache install is, but if it doesn't even print out errors that sounds very broken and not a proper PHP7 IMO.

**Comment by Rouzax** [comment]
With Ampache I mean this: https://github.com/ampache/ampache

This is weird somehow now it works when I point the Path to the 7.0 version.
Still have the issue though with the installer that won't work with the 7.0

**Comment by johnstevenson** [comment]
It looks like you are using the MS Web Platform Installer, which has already been the cause of a previous issue https://github.com/composer/windows-setup/issues/52. It doesn't help things by installing to the Program Files directory, because you can only edit the php.ini as an admin.

Composer-Setup writes a log file to your temp directory, as described here: https://github.com/composer/windows-setup/#troubleshooting 

It might give us a clue.

**Comment by Rouzax** [comment]
Yes, that is correct I'm using WPI but I've have disabled UAC so there is no issue to edit the PHP.ini

I already restarted the server so the log was already cleared but to test I uninstalled Composer and did the install again and now it goes through without an error :confused:

**Comment by Seldaek** [comment]
OK then I guess let's close as yet another unsolved mystery :)
