### ISSUE TITLE
composer update not picking up new versions of repos

### ISSUE THREAD

**Issue by guyradford** [composer/composer#5178]
With the following composer.json:

```json
{
    "repositories": [
        {
            "type": "git",
            "url": "https://git.arincsbb.net/arinc/custom-constraints.git"
        }
    ],
    "require": {
        "php": ">=5.5",
	"arinc/custom-constraints" : ">=1.0 <2.0"
    }
}
```

When I run this command:

```
composer install -vvv 
```

I get this output:

```
Reading composer.json of arinc/custom-constraints (v1.5.1)
Reading /Users/GuyRadford/.composer/cache/repo/https---git.arincsbb.net-arinc-custom-constraints.git/7973c909e419217b7b78e9f8c2acf9270dd1953a from cache
Importing tag v1.5.1 (1.5.1.0)
Reading composer.json of arinc/custom-constraints (v1.5.2)
Reading /Users/GuyRadford/.composer/cache/repo/https---git.arincsbb.net-arinc-custom-constraints.git/dc497e71350c027d4ac594ae30c8b67ddc9074ab from cache
Importing tag v1.5.2 (1.5.2.0)
Reading composer.json of arinc/custom-constraints (v1.6.0)
Reading /Users/GuyRadford/.composer/cache/repo/https---git.arincsbb.net-arinc-custom-constraints.git/1f7154dffb4189b4c0055edc66c3b599404b0e9b from cache
Skipped tag v1.6.0, tag (1.6.0.0) does not match version (1.0.0.0) in composer.json
Reading composer.json of arinc/custom-constraints (v1.6.1)
Reading /Users/GuyRadford/.composer/cache/repo/https---git.arincsbb.net-arinc-custom-constraints.git/21ac10dc4480b8d957c4ae4f4afe90a4eb3d6cc7 from cache
Skipped tag v1.6.1, tag (1.6.1.0) does not match version (1.0.0.0) in composer.json
Reading composer.json of arinc/custom-constraints (v1.6.2)
Reading /Users/GuyRadford/.composer/cache/repo/https---git.arincsbb.net-arinc-custom-constraints.git/8e7f09244aad2a744777ff0597fa25ad601a01e4 from cache
Skipped tag v1.6.2, tag (1.6.2.0) does not match version (1.0.0.0) in composer.json
Reading composer.json of arinc/custom-constraints (v1.6.3)
Reading /Users/GuyRadford/.composer/cache/repo/https---git.arincsbb.net-arinc-custom-constraints.git/0ebb66a787791e34efa41116b587fc23a1465295 from cache
Skipped tag v1.6.3, tag (1.6.3.0) does not match version (1.0.0.0) in composer.json
Reading composer.json of arinc/custom-constraints (v1.6.4)
Reading /Users/GuyRadford/.composer/cache/repo/https---git.arincsbb.net-arinc-custom-constraints.git/7bbb710b16de1baccd6799036e8bfaee6b8bb269 from cache
Skipped tag v1.6.4, tag (1.6.4.0) does not match version (1.0.0.0) in composer.json
Reading composer.json of arinc/custom-constraints (master)

```

Composer can see all the version tags, but from v1.6.0 it stopped being able to process them and skips them. We cant see why this is suddenly happening. We have checked the tags.. this is also happening across other repos. This now means that we cant use the latest version of the repo as composer picks the last version that can be processed.

If we manually update the composer.lock file we can force composer to install the correct version.

Thank you
Guy

**Comment by alcohol** [comment]
It looks to me like your tags contain a `composer.json` which has a hardcoded `version` specified which does not match the actual tag, and therefor it fails to be accepted by Composer.

**Comment by guyradford** [comment]
@alcohol , the version is set to a range **">=1.0 <2.0"** so should accept any version from 1 to 2. unless I am mistaken?

I did try setting the composer.json file to the version we wanted, composer lists all the versions it can understand. See below:

```
The requested package arinc/custom-constraints 1.6.3 exists as arinc/custom-constraints[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.1.0, v1.2.0, v1.3.0, v1.4.0, v1.5.0, v1.5.1, v1.5.2] but those are rejected by your constraint.
```
But cant install the version we want as it skips it as it does not understand the version number.

**Comment by Seldaek** [comment]
```
Skipped tag v1.6.0, tag (1.6.0.0) does not match version (1.0.0.0) in composer.json
```

That means that in tag `v1.6.0`, your composer.json declares itself as being `"version": "1.0.0"`, and composer skips that tag as that conflicting information looks dodgy. Best to remove the "version" from composer.json in those tags if you need to install them.

**Comment by alcohol** [comment]
@guyradford as @seldaek also pointed out, I was talking about the composer.json of your tagged library, not the project that requires it. They are not the same :-)

**Comment by guyradford** [comment]
Thank you for you help, that makes sense now :) someone had slipped in the version key in the composer.json. 

All working now.
