### ISSUE TITLE
Make IOInterface implement LoggerInterface

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#5180]
Right now it's done hackishly at the BaseIO level to avoid breaking the contract, but this should be fixed in 2.0, see https://github.com/composer/composer/commit/b1723644e0a713ac3d25e5a0d429aceed76699ce#diff-720ae6fee5a71e118e1f8899f16741d1R14

**Comment by curry684** [comment]
Is breaking stuff to go in master branch directly?

**Comment by Seldaek** [comment]
Nope, breaking stuff is not to go anywhere right now :) master is targetting 1.1 and 1.0 targets 1.0.x.

I think before breaking things we should clean up the issue tracker and merge existing new features PR that are not breaking.

**Comment by curry684** [comment]
That's what I thought hehe :+1:
