### ISSUE TITLE
Composer and Bitbucket.

### ISSUE THREAD

**Issue by msaprykin** [composer/composer#5181]
Hello.
I updated the composer.json and pushed to Bitbucket.
This repo is private.

I try install my project to server.
Console command:
`composer create-project myname/myproject main --repository '{"type":"git","url":"https://bitbucket.org/myname/myproject"}'`

Composer give me error:

```
[InvalidArgumentException]                                                  
  Could not find package myname/myproject with stability stable
```

what should I do order to composer knew what my branch?
mybe added TAG with version?
I added TAGs: "**v0.0.1**", "**0.0.1**", "**stable**".
But it does not work
Thanks!

**Comment by vaclavvanik** [comment]
You should run `composer -sdev create-project myname/myproject main --repository '{"type":"git","url":"https://bitbucket.org/myname/myproject"}'`

Eg. add param *stability dev* https://getcomposer.org/doc/03-cli.md#create-project

**Comment by msaprykin** [comment]
Hello,
thanks for reply.
i write:
`composer -sdev create-project myname/myproject main --repository '{"type":"git","url":"https://bitbucket.org/myname/myproject"}'`
I give error:
` [InvalidArgumentException]                                               
  Could not find package myname/myproject with stability dev.`

**Comment by alcohol** [comment]
Please share your composer.json with us.
