### ISSUE TITLE
[ErrorException]   chmod(): No such file or directory

### ISSUE THREAD

**Issue by sneha2011** [composer/composer#5186]
Hi Everyone,

On Installing symfony via composer I am getting following error on command prompt : 

[ErrorException]
  chmod(): No such file or directory

What I have done :  Have downloaded and installed composer in subfolder name i.e project under root directory of wamp server but on running : 
composer create-project symfony/framework-standard-edition my_project_name 

I am getting  exception No such file or directory

Kindly help.

PS : I am new to symfony
Thanks in advance

**Comment by Seldaek** [comment]
Please run it again with like `composer create-project symfony/framework-standard-edition my_project_name -vvv` (with -vvv!), that way you get a stack trace and maybe we can help, because that error alone is really not specific enough.

**Comment by sneha2011** [comment]
Thanks Seldaek - Please find the Exception trace below :

Exception trace:

 () at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Util/RemoteFilesystem.php:811

 Composer\Util\ErrorHandler::handle() at n/a:n/a

 chmod() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Util/RemoteFilesystem.php:811

 Composer\Util\RemoteFilesystem->getTlsDefaults() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Util/RemoteFilesystem.php:63

 Composer\Util\RemoteFilesystem->__construct() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Factory.php:567

 Composer\Factory::createRemoteFilesystem() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Repository/RepositoryFactory.php:101

 Composer\Repository\RepositoryFactory::defaultRepos() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/CreateProjectCommand.php:255

 Composer\Command\CreateProjectCommand->installRootPackage() at 
phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/CreateProjectCommand.php:155

Composer\Command\CreateProjectCommand->installProject() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/CreateProjectCommand.php:142

 Composer\Command\CreateProjectCommand->execute() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Command/Command.php:259

 Symfony\Component\Console\Command\Command->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:844

 Symfony\Component\Console\Application->doRunCommand() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:192

 Symfony\Component\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:181

 Composer\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:123

 Symfony\Component\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:99

 Composer\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin/composer:43

 require() at C:\ProgramData\ComposerSetup\bin\composer.phar:25

**Comment by curry684** [comment]
Did you misconfigure the system temp folder in your php.ini file by any chance?

**Comment by sneha2011** [comment]
No I haven't touched php.ini moreover while running composer init ( in
order to get composer.json ) I am getting :
 [Symfony\Component\Process\Exception\RuntimeException]
  A temporary file could not be opened to write the process output to,
verify that your TEMP environment variable is
  writable

so I have checked sys_temp_dir in php.ini of wamp server so its showing the
path : /tmp  Have checked the rights as well but no success

Can't install symfony through installer and composer both .

Thanks


On Wed, Apr 13, 2016 at 10:19 PM, Niels Keurentjes <notifications@github.com

**Comment by sneha2011** [comment]
Thanks for the command Niels - I got the exact location of temp folder and have given full access rights  to it . Symfony is installed and running fine on my machine now.

The only thing I want to know that how can change path of temp folder as right now its using windows temp folder which is not secure and I tried changing path also in php.ini of wamp server ( under sys_temp_dir ) but no success kindly help.

Thanks in advance

**Comment by curry684** [comment]
See `sys_temp_dir` at http://php.net/manual/en/ini.list.php

**Comment by Shymoney** [comment]
please i am having similar issue with the composer, when i run the composer update command it shows me this error i dont know to fix this. i need help urgently

thanks

**Comment by curry684** [comment]
Please open a new issue with full relevant information. Kicking an issue that was solved 2 years ago is not helpful.
