### ISSUE TITLE
cacert.pem is missing in latest snapshot of composer.phar

### ISSUE THREAD

**Issue by fritzmg** [composer/composer#5188]
The `cacert.pem` copy was removed from the master branch in https://github.com/composer/composer/commit/592374ea937322b97bb885b673e6b1443fc02604 , however as far as I understand it, the latest snapshot of the compiled `composer.phar` should still include it (as evidenced in the `composer.json` and `composer.lock` files). It is however completely missing from the [latest snapshot](https://getcomposer.org/composer.phar).

**Comment by Seldaek** [comment]
As far as I can tell it is in it.. snapshot is built from master which now includes the composer/ca-bundle dependency instead of having the cacert directly in. It's path inside the phar changed though. That might be what trips you up?!

**Comment by fritzmg** [comment]
Yes, you are right. The new path is `composer/ca-bundle/res/cacert.pem`. However, one should probably use
```php
CaBundle::getBundledCaBundlePath()
```
instead - or better
```php
CaBundle::getSystemCaRootBundlePath()
```
to auto-detect the ca bundle, as you mentioned [here](https://github.com/composer/composer/pull/5177#issuecomment-208416720)
