### ISSUE TITLE
comoser is is blocked when i execute composer update.

### ISSUE THREAD

**Issue by simoziyadi** [composer/composer#5189]
With the following composer.json:

composer update -vvv (please include -vvv!)

I get this output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
```

it works fine in my windows 8 but when i get to my VM centos 7 it blocks.
is there any solution for this problem.

**Comment by curry684** [comment]
Please specify what you mean with 'blocks'. Your VM may just be much slower, did you wait it out a while?

**Comment by alcohol** [comment]
More info required.

**Comment by simoziyadi** [comment]
i gave my virtual machine mor RAM and my and set the memory_limit to 1500 M and it worked fine but  before the composer install finish it gives me this error:
 [Symfony\Component\Debug\Exception\ContextErrorException]                                                                                                                                                                                                                                                                                                                                  
  Warning: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.
                                                                                                                                                                                                                                                                                                                                                                                             

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception


  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:




    [Symfony\Component\Debug\Exception\ContextErrorException]



    Warning: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *require
  d* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and
   you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' fo
  r now, but please set date.timezone to select your timezone.

**Comment by stof** [comment]
Well, the error given by PHP explains the issue: you are missing the timezone configuration in your php.ini, and PHP 5.x does not like it. The fix is to update your php.ini to satisfy PHP.

**Comment by curry684** [comment]
Or update your PHP, in 7.0 this (pretty moronically) required setting has a proper default.

https://wiki.php.net/rfc/date.timezone_warning_removal

**Comment by simoziyadi** [comment]
Thank you guys for your help.It worked fine after i configured the timezone parameter in my php.ini
