### ISSUE TITLE
Autoloading fails on HHVM with repo authoritative mode

### ISSUE THREAD

**Issue by TJ09** [composer/composer#5192]
As of fd2f51cea8e5f1ef978cd8f90b87b69dc1778976, composer now generates an autoload_static.php file. In this file, there's a call to `Closure::bind()`, which doesn't work at all in HHVM under repo authoritative mode, and per facebook/hhvm#1203, isn't something HHVM can reasonably support in repo-auth mode.

Simplest fix may be to just give HHVM the same behavior as PHP<5.6 in this case; I don't know if the optimization is even as valuable on HHVM as it is on the stock PHP runtime.

Though, looking at the generated initializer code (https://github.com/composer/composer/commit/fd2f51cea8e5f1ef978cd8f90b87b69dc1778976#diff-33037407f7f293f37df2258567b56598R754), it doesn't seem that `Closure::bind()` is even necessary?

**Comment by alcohol** [comment]
It would be great if you could submit a PR with a test that reproduces this.

**Comment by stof** [comment]
> it doesn't seem that Closure::bind() is even necessary?

it is necessary to be able to access private properties.

But I totally agree that disabling this optimization on HHVM looks sensible (HHVM does not run OPCache anyway)

**Comment by Seldaek** [comment]
Fixed by 0b44662087a6cbf0838fccc30d4453c7329e953d

**Comment by asuth** [comment]
I've been doing some profiling, and noted that more than half of all memory usage in my HHVM runs (in repo authoritative mode) are coming from loading this file the slow way. So I believe that this fix was not ideal.

Is there an alternative workaround that could let hhvm have this perf optimization too?

**Comment by TJ09** [comment]
HHVM in repo auth mode fundamentally cannot support `Closure::bind()`, so the handling of `autoload_static` would need to be rewritten to avoid that binding.

Alternatively, I think the main cause of memory usage is because the arrays in `autoload_{psr4,classmap,namespaces}.php` are in the global scope, so HHVM probably can't dedupe them between requests. If those moved to be generated as static class properties, that might help. But I'm not familiar enough with HHVM internals to be confident in saying that.

**Comment by stof** [comment]
the handling of autoload_static cannot be rewritten. Writing the array in the private property directly is precisely what allows a major performance boost with OPCache.
