### ISSUE TITLE
composer.json not found in svn if parent folder has higher revision then composer.json

### ISSUE THREAD

**Issue by kwebble** [composer/composer#5194]
An error occurs with a svn repository for a dependency where composer.json of that dependency was moved to a newer parent folder in svn.

The component in svn was moved from :

    /repo/project/braches/dev/component

to a new folder:

    /repo/new-project/trunk
 
The revision of the parent folder is now higher then the revision of composer.json In my case the versions were 1560 and 1606.

composer.json of the main project has a svn repository defined for the component:
`https://svn.example.com/repo/new-project`

The commands `composer install` and `composer update` try to retrieve composer.json from the *branches*, *tags* and *trunk* folders of the repository:

    svn cat --non-interactive "https://svn.example.com/repo/new-project/component/trunk/composer.json@1606"

This fails because there is no version of composer.json with the revision number of the parent folder. The output of the command is: 

    svn: warning: W160013: '/!svn/bc/1606/new-project/trunk/composer.json' path not found
    svn: E200009: Could not cat all targets because some targets don't exist
    svn: E200009: Illegal target for the requested operation

The result is an error message from Composer:
*No valid composer.json was found in any branch or tag of http://svn.example.com//repo/new-project/trunk/component, could not load a package from it.*

I can't reproduce command output because I fixed the problem. The fix is to update composer.json of the component and commit a new version.

It seems [this satis issue](https://github.com/composer/satis/issues/310) is related. At least that's what got me thinking about the situation and solve the problem.

**Comment by alcohol** [comment]
I do not have sufficient SVN knowledge to say whether or not this is to be expected. It sounds like something Composer cannot really deal with gracefully. But then again it is SVN... graceful does not really apply in this context.

All bias aside, someone with SVN knowledge should look at this. So it is up to the community, since most of the Composer members use Git.

**Comment by Seldaek** [comment]
This is a known issue I think, it's been reported in the past but there is really no way for us to fix this nicely, the only way to fix it on your end is if you move the whole repo you should do a dummy commit to the composer.json to bring it back to a newer repo than its parent dir.
