### ISSUE TITLE
Transfer namespace to organisation from employee

### ISSUE THREAD

**Issue by bbrala** [composer/composer#5197]
I have a little question about namespace ownership. A colleague of mine added a package quite a while ago (https://packagist.org/packages/swisnl/bigregister-soap) which has since been deleted. Now we have a account for our company (swisnl) to manage our packages on packagist. The problem is that is I try to submit a package I get the following error:

“The vendor is already taken by someone else. You may ask them to add your package and give you maintainership access. The packages already in that vendor namespace can be found at swisnl”

Which is confusing, since there is no way on his account to move this. The original fork doesn’t exsist anymore on the swisnl github so can’t really do anything with access there.

Is it possible to transfer ownership of the namespace to the other account? Or maybe just delete the swisnl/bigregister-soap package (since it is only used internally)?

Best regards, Björn

**Comment by alcohol** [comment]
Best to submit issues related to Packagist on the [Packagist](/composer/packagist) issue tracker. @Seldaek can resolve this for you, when he has some time available.

**Comment by Seldaek** [comment]
Package is gone, go ahead and submit the new ones :)

**Comment by bbrala** [comment]
Im sorry @alcohol and thank you @Seldaek for resolving this! :)
