### ISSUE TITLE
Composer install triggers an error

### ISSUE THREAD

**Issue by ypereirareis** [composer/composer#5199]
When I run this command:

```
composer install -vvv
```

I get this output:

```
Fatal error: Class undefined: Composer\Autoload\ComposerStaticInitComposerPhar1460728627 in phar://composer.phar/bin/../src/../vendor/composer/autoload_real.php on line 50
```

And I expected this to happen: install my deps

**Comment by Seldaek** [comment]
If you are using HHVM, please run `self-update` again. If not.. we're gonna need more detalis.

**Comment by inakianduaga** [comment]
Same happened to me just now, running hhvm

**Comment by ypereirareis** [comment]
Updating to version 0b44662087a6cbf0838fccc30d4453c7329e953d.
    Downloading: 100%         
Use composer self-update --rollback to return to version 4071b09091057db749a851322dea4273be3c1297

Fatal error: Class undefined: Composer\Autoload\ComposerStaticInitComposerPhar1460728627 in phar://composer.phar/bin/../src/../vendor/composer/autoload_real.php on line 50
make: *** [composer-install] Erreur 255

**Comment by inakianduaga** [comment]
@Seldaek 

> If you are using HHVM, please run self-update again. If not.. we're gonna need more details.

What do you mean, the error comes AFTER running `composer -n self-update`

**Comment by inakianduaga** [comment]
"Fix" for me (running inside hhvm docker container 3.9) is NOT to run `composer self-update`. But basically something is broken in the release

**Comment by Seldaek** [comment]
@inakianduaga well how should I know? The OP does not mention self-update at all.

Anyway I spotted the error, will push a fix shortly.

**Comment by inakianduaga** [comment]
@Seldaek 

> well how should I know? The OP does not mention self-update at all.

Sorry, you're right, read it quickly and thought he was in the same situation as me, so I assumed the "context" of the error was the latest version.

Cool you'll push a fix.

**Comment by ypereirareis** [comment]
Yes Sorry, I did not mention the sefl-update in my first post.

But thanks for the fix and for your awesome work @Seldaek

**Comment by Seldaek** [comment]
NP, I just assumed it was a manifestation of #5192 that I just fixed so I figured if you self-update it'll work, but it seems the fix actually caused this regression :)

Anyway fix is pushed. self-update should go fine again.

**Comment by ypereirareis** [comment]
Everything is fine now !!!!

**Comment by inakianduaga** [comment]
tx!
