### ISSUE TITLE
Is it possible to override one or multiple classes using composer?

### ISSUE THREAD

**Issue by spiritix** [composer/composer#5200]
In the main project in ``composer.json`` I have:

```
{
    "require": {
        "vendor/package1": "1.0",
        "other-vendor/package2": "1.0"
    }
}
```

Then in ``vendor/package1`` the ``composer.json`` contains:

```
{
    "autoload": {
        "psr-4": {
            "Libraries\\": "src/Libraries/"
        }
    }
}
```

And in ``other-vendor/package2`:

```
{
    "autoload": {
        "psr-4": {
            "Libraries\\Database\\Oracle\\": "src/Libraries/Database/Oracle/"
        }
    }
}
```

What I want to achieve is overriding the class ``Libraries\\Database\\Oracle\\Query.php`` with my own, modified implementation of this class.
At the moment it looks like this is not working.

Is this possible? Or is there another way to do that?

I know that this is not the proper way to extend / modify a class, but unfortunately in the package I am trying to override the class is hardcoded.

**Comment by curry684** [comment]
No, this isn't behaviour that Composer can or will support. You should just fork the existing package and modify it there, and use it from an artifact, path or VCS repository.

https://getcomposer.org/doc/05-repositories.md

**Comment by Seldaek** [comment]
It's not a great practice, but it's *possible*. If you define a psr-4 autoload rule for `"Libraries\\Database\\Oracle\\"` (or a more specific namespace) in your project then that will win over the dependency's definition.
