### ISSUE TITLE
Update seld/cli-prompt dependency when https://github.com/Seldaek/cli-prompt/pull/2 is merged

### ISSUE THREAD

**Issue by lauripiisang** [composer/composer#5209]
Currently, composer exposes passwords on bash/zsh/csh/ksh-less *nix systems due to Seld/CliPrompt not supporting `sh`. I added `sh` support and I'm pushing to get it merged so people don't expose their passwords when connecting to protected repositories.

**Comment by Seldaek** [comment]
Fixed in snapshot channel via b01829235729d0f723140bb80c9447478fdae013
