### ISSUE TITLE
composer depends --match-constraint --with-replaces equivalent?

### ISSUE THREAD

**Issue by Soullivaneuh** [composer/composer#5213]
This issue is especially for @curry684.

You did a complete rewrite of the `depends` command on #4917.

Now, `--mathc-constraint` and `--with-replaces` are gone.

I could understand your issue (#4911), but those options had a specific usage.

Example: Find any package that is not ready for Symfony 3 and maybe propose contributions to fix them.

In case of Symfony, it's a package **and** components. The goal of those option is to have something like this:

```bash
$ composer depends --with-replaces symfony/symfony
a2lix/translation-form-bundle requires symfony/symfony (>=2.3)
behat/behat requires (dev) symfony/process (~2.1)
behat/behat requires symfony/class-loader (~2.1)
behat/behat requires symfony/config (~2.3)
behat/behat requires symfony/console (~2.1)
behat/behat requires symfony/dependency-injection (~2.1)
behat/behat requires symfony/event-dispatcher (~2.1)
behat/behat requires symfony/translation (~2.3)
behat/behat requires symfony/yaml (~2.1)
```

I'm trying to deal with the new options:

```bash
$ composer depends symfony/symfony --tree --recursive
symfony/symfony v2.8.4 The Symfony PHP framework
├──a2lix/translation-form-bundle 1.3 (requires symfony/symfony >=2.3)
│  └──nexylan/project dev-master (requires a2lix/translation-form-bundle ^1.3)
└──nexylan/project dev-master (requires symfony/symfony 2.8.*)
```

But this shows now only `symfony/symfony` package, not components.

Do you have a solution with the actual state of composer?

If not, we have to consider putting back this option in some way, with considering #4911.

I'm a bit surprised that this kind of modification is accepted without regarding if needed use cases are still usable.

Regards.

**Comment by Soullivaneuh** [comment]
BTW:

> Dropped `--with-replaces` parameter as it caused nonsensical indirect hits. Direct replaces are always shown though

Related to your command: https://github.com/composer/composer/issues/4911#issuecomment-183966204

This was not the goal. It should be used with `symfony/symfony` package for this case, not `symfony/console` like I said on the previous post.

For other cases, this option should simply not be used.

**Comment by stof** [comment]
> I'm a bit surprised that this kind of modification is accepted without regarding if needed use cases are still usable.

The issue is that the intended usage of the option was not documented anywhere, and none of the reviewers was remembering the original goal. We were missing the context you just gave in your comment above.
And there was no test which would have given this context either.

**Comment by Soullivaneuh** [comment]
> The issue is that the intended usage of the option was not documented anywhere

The documentation was added in #4761.

Anyway, I re-read the issues and PR again, and it seems it could be possible to have again this with antoher design.

Let's take profit to discuss about that on this issue. :+1:

**Comment by Seldaek** [comment]
@Soullivaneuh your use case was taken into account, and it still works IMO, via the prohibits/why-not command:

```
$ c why-not symfony/symfony:3.0
__root__                    dev-master  requires  symfony/symfony (^2.7.5)
linkorb/database-manager    v2.0.0      requires  symfony/console (~2.5)
linkorb/haigha              v2.4.0      requires  symfony/console (~2.4)
sensio/distribution-bundle  v3.0.35     requires  symfony/process (~2.2)
sensio/generator-bundle     v2.5.3      requires  symfony/framework-bundle (~2.2)
snc/redis-bundle            1.1.10      requires  symfony/yaml (^2.1)
```

**Comment by Soullivaneuh** [comment]
@Seldaek interesting. Does it works for sub-dependencies (e.g. `__root__` requires `package1` that requires `package2` that requires `symfony/console:^2.3`?

**Comment by Seldaek** [comment]
Yup:

```
$ c dep linkorb/database-manager -t
linkorb/database-manager v2.0.0 Database Management utilities: connectivity, backups, fixtures, etc
└──linkorb/haigha v2.4.0 (requires linkorb/database-manager ~2.0)
   └──__root__ dev-master (requires (for development) linkorb/haigha ^2.2)
```

**Comment by Soullivaneuh** [comment]
Oh ok. But you mean:

```bash
$ composer why-not -t symfony/symfony:3.0
symfony/symfony v2.8.4 The Symfony PHP framework
├──friendsofsymfony/user-bundle v2.0.0-alpha3 (requires symfony/twig-bundle ~2.3) (circular dependency aborted here)
├──genemu/form-bundle dev-master (requires symfony/framework-bundle ~2.6) (circular dependency aborted here)
├──lexik/paybox-bundle v2.0.1 (requires symfony/options-resolver ~2.7) (circular dependency aborted here)
├──nexylan/cloudflare dev-master (requires symfony/options-resolver ~2.7)
│  └──nexylan/project dev-master (requires nexylan/cloudflare dev-master)
└──nexylan/project dev-master (requires symfony/symfony 2.8.*)
```

Right?

**Comment by Seldaek** [comment]
I don't know what you are asking. I don't mean anything else than I pasted above. I didn't use the tree flag but you could as well yes. Doesn't matter a whole lot. In any case I think we can close this?

**Comment by Soullivaneuh** [comment]
I think so yes. Thanks!

**Comment by curry684** [comment]
@Soullivaneuh the point of the rewrite was that `depends` tried to merge both use cases, while they are highly different in implementation, for example in the way `replaces` is handled. Hence the split in `why` and `why-not` (aliased to `depends` and `prohibits`) not to confuse the user with several options that only make sense when combined.

As you can see `why-not` is now a shortcut for the old `-i -m` behaviour without the option to specify only one of them.

**Comment by Soullivaneuh** [comment]
@curry684 Yeah I saw that. Thanks for your help. :+1:
