### ISSUE TITLE
Exposing Composer packages

### ISSUE THREAD

**Issue by mindplay-dk** [composer/composer#5214]
I'd like to request/propose some means of exposing package installation paths at run-time.

Needing to know the root path of a package installation folder is quite a common requirement, such as when you need to specify paths to template files or other assets.

Presently, as far as I can figure, there is no reliable way to do that?

`ClassLoader` doesn't expose anything, and as far as my understanding, we really shouldn't depend on `ClassLoader` in the first place - it's an implementation detail, and there's actually no guarantee that it's always singleton.

The best solution I've been able to find, is using reflection to get the path to a known class or interface from the package, and then `dirname()` up from the `src` folder to the package installation root. This approach is pretty clumsy and creates random dependencies on arbitrary class/interface-names just for the sake of locating a package root.

Even if you know the path of the `vendor` root folder, and the `{vendor}/{package}` folder name convention, there is no guarantee that's always where packages are installed - something like [composer-installers](https://github.com/composer/installers) or other custom installers could affect the installation paths. Also, under test, when a package is the root/project package, of course the assumption about the `vendor` folder is always wrong.

There are package names in `composer.lock`, but no root paths.

There are paths, but no package names in the generated auto-loader.

And yeah, now we get things like [puli](https://github.com/puli/repository), which is great, if what you want is another huge, complicated framework abstracting the file system with virtual paths, repository types, resources, etc.

I really don't want that complexity - I favor simplicity.

All I really need/want, is a means of asking for the root path for a given package name, which doesn't really seem like a tall order? :-)

How come Composer doesn't offer that functionality?

**Comment by Seldaek** [comment]
Composer doesn't offer that because.. Composer doesn't offer everything imaginable? :) 

https://github.com/Ocramius/PackageVersions kinda goes in this direction, but it only has vendor name/version. If the install path was added it'd do what you want I think. I prefer to keep this sort of stuff as plugins because then it can cater to the needs of everyone (and I don't need to maintain it..).

**Comment by Seldaek** [comment]
Ah also you could whip something up using `composer show -P` :)

**Comment by mindplay-dk** [comment]
Yeah, plugins, I thought of that - that's not going to work, I think.

The order in which plugins are installed/loaded/updated is rather unpredictable - and, as explained, other plugins could themselves affect the installation path, that's part of the challenge here.

Composer *has* the package paths at the time of installation/update, but it appears this information is discarded and e.g. `composer show -P` actually recomputes the paths from scratch?

Would it be a big maintenance burden to simply dump the paths in `composer.lock` so that e.g. a separate package can pick it up and enumerate packages and locations?

I'd rather not have to depend on the entire composer package for that, which seems like the only real option at this time. (?)

**Comment by Seldaek** [comment]
Well a plugin could do what composer show -P does pretty easily, do it at the end of the update and install command, then it doesn't matter when your plugin gets installed.

**Comment by mindplay-dk** [comment]
Wait, would listening for `post-autoload-dump` do it?

At that point, all packages have been installed, so a plugin might be able to do this after all?

**Comment by Seldaek** [comment]
I would do it in post-install-cmd and post-update-cmd, because that's just the right place to do it. If someone runs a composer autoload-dump there is no reason for you to re-generate, and if someone runs install with --no-autoloader for whatever reason your thing would break then.

**Comment by mindplay-dk** [comment]
Yeah, makes sense.

Am I really the first person to ever ask for this?

Everyone else is perfectly happy using `dirname(dirname(...))` or `ReflectionClass` to locate templates and other assets?

Just wondering if I should keep trying to find this package, in case somebody already wrote it (if it exists, I haven't been able to find it) or if I should go ahead and build it myself...

IMO, mapping a new virtual file system to the physical file system (puli) really is doubling the problem rather than solving it. (I have read their posts and asked questions and still, honestly, don't have the faintest clue what real problem they're trying to solve with this...)

**Comment by Seldaek** [comment]
I'm not sure if you are the first, I guess a couple might have asked, but it's definitely not a massively useful feature IMO. AFAIK there is no existing plugin doing this (aside from puli, but I agree with you that it is possibly going too far). If you publish one link it here please :)

**Comment by mindplay-dk** [comment]
[bam!](https://github.com/mindplay-dk/composer-locator)

**Comment by Seldaek** [comment]
Cool. Just a couple notes:

- I think you should have the function file already in the repo just so 
it's autoloadable before it's done dumping, in case we ever support 
files autoload for plugins that'll avoid some breakage :) It doesn't 
have to be functional, but it should be present.

- I'd return null rather than throw as a package being missing isn't 
really an exceptional condition IMO.. That way you could use it for 
testing package presence as well.

**Comment by mindplay-dk** [comment]
> I think you should have the function file already in the repo

Good point. Done.

> I'd return null rather than throw as a package being missing isn't
> really an exceptional condition IMO.. That way you could use it for
> testing package presence as well.

That was my first impulse, but I decided against it - returning `null` would very likely lead to unexpected (and potentially dangerous) results.

The 99% use case is to get the path and concatenate it with a relative path - since `null` can be concatenated with a relative path, quietly ignoring package paths that can't be resolved seems risky.

I can't actually think of a case where I think it would be a good idea to check at run-time for the existence of a package. And in that marginal case, there are ways to do that already, with `class_exists()`, etc.

I could always add a different means of checking for the existence of a package, but at the moment, that's not what this is for, and I don't really believe I'll need it.

**Comment by Seldaek** [comment]
Fair enough :)

**Comment by mindplay-dk** [comment]
Hmm, one thing is missing... the root project/package itself isn't in the list of packages returned by `getPackages()` from the local repository - how do I get the root project/package?

**Comment by stof** [comment]
@mindplay-dk ``$composer->getPackage()`` is the root package

**Comment by Seldaek** [comment]
I wouldn't trust getInstallPath on that though, at least I have no idea 
what it'll return. Best to dump getcwd() as the path.

**Comment by mindplay-dk** [comment]
> I wouldn't trust getInstallPath on that though 

Yeah, it returns a non-existent path, it just concats `__root__` to the vendor dir, heh.

Is `getcwd()` the safest way? What if I'm not in the project root and run `composer update`?

There's no API point that provides the root project path?

**Comment by Seldaek** [comment]
getcwd() is safe, we rely on it being the project root in a bunch of places.

**Comment by mindplay-dk** [comment]
Alright, [this should do it](https://github.com/mindplay-dk/composer-locator/commit/6cfa503f778ee172b8bbc5461c6cafec847a2ff8) - this was one of the main goals with this actually, being able to get the absolute path to a package root, regardless of whether that package is currently the root or not.

Sweet :-)

Anything else before I slap a 1.0 on it?

**Comment by Seldaek** [comment]
Looks good to me.

**Comment by mindplay-dk** [comment]
Heh, okay, not 24 hours after defending the `throw` thing, it turns out I need to check if a package is installed, haha, shame on me ;-)

I'm also thinking somebody might want the list of installed packages, e.g. the whole package/path map.

So I'm already thinking `2.0`, because I don't want to overload a single function to do all that.

What do you think of an API like this?

```php
composer::path("foo/bar"); // => look up path (like composer_path does now)

composer::installed("foo/bar"); // => true/false

composer::list(); // => array of package names

composer::map(); // => array where $package_name => $path
```

Would you be opposed to my using the pseudo-namespace `composer` for these functions?

**Comment by Seldaek** [comment]
I'm not gonna stop you because I have better things to do than policing people's code :) But I'd personally go for something like  `Packages::getPath/getPaths/isInstalled/getPackages`.

**Comment by mindplay-dk** [comment]
Alright, [here it is](https://github.com/mindplay-dk/composer-locator/blob/master/src/ComposerLocator.tpl.php) - any comments?

**Comment by Seldaek** [comment]
Looks good to me!

**Comment by mindplay-dk** [comment]
I probably ought to put the generated class in the package namespace instead of just `\ComposerLocator` though?

**Comment by Seldaek** [comment]
Up to you really, I don't mind if it's there as it's very composer-centric and won't conflict with our namespaced class names.

**Comment by mindplay-dk** [comment]
Cool.

Would you consider adding a link to it somewhere in the documentation?

**Comment by Seldaek** [comment]
I have a list of such "things" I wanna add somewhere. I haven't found the best place yet :)
