### ISSUE TITLE
Bootstrap autoloading for packages

### ISSUE THREAD

**Issue by mindplay-dk** [composer/composer#5216]
In a few, rare, but painfully unavailable instances, a package requires some form of bootstrapping - by which I mean, some kind of global initialization that isn't really pertinent until the package is actually used.

I will provide two examples.

First example: a global translation facility, e.g. a replacement for `gettext()`, such as [this one](https://github.com/mindplay-dk/lang). A package that uses this facility, needs to [bootstrap](https://github.com/mindplay-dk/kissform/blob/master/src/bootstrap.php) the translation facility with a root path for the translation files. Presently, I need to do that by [forcing](https://github.com/mindplay-dk/kissform/blob/master/composer.json#L22) a bootstrap script to load, unconditionally, even though there is really no need to bootstrap the language file paths for this module until one of it's classes need it.

I could sprinkle `require_once` statements throughout every file in the codebase - but that doesn't really work, because somebody might wish to override the language file path and use a custom set of translation files specific to their project. I could inject some kind of translator object and pass that around, requiring consumers to obtain the translator and pass it to every validator, which is dependency hell. I could introduce a factory class or DI container and make that responsible for creating and injecing the dependency, which would kill IDE support and static analysis. None of those solutions are really appealing to me.

Second example: packages that have certain specific pre-conditions, e.g. specific php.ini settings, which should be checked and/or set when the package is loaded. Again, you could sprinkle `require_once` statements everywhere, but it's not really appealing.

What I would suggest instead, is a new type of `autoload` setting in `composer.json`, e.g.:

```json
    "autoload": {
        "bootstrap": [
            "src/bootstrap.php"
        ]
    },
```

The class-loader would delay loading this script until the first time a type from this package is auto-loaded, so that bootstrapping specific packages can happen conditionally and as late as possible.

Is this a crappy idea? I'm totally open to alternatives/ides - I just have not been able to come up with a sane and satisfying alternative.

What do you think?

**Comment by hkdobrev** [comment]
You could use a dependency injection container which could have initialisation of a class instance which would be executed only once and only when the dependency is needed. Take a look at http://pimple.sensiolabs.org/ for a micro dependecy injection container.

**Comment by stof** [comment]
I suggest you to check https://github.com/swiftmailer/swiftmailer/ to see how they handle their need for a global initialization before any class of the package can be used.
My advice would still be to try avoiding this need whenever possible instead.

And so, I don't think this belongs to the Composer ClassLoader itself.

**Comment by mindplay-dk** [comment]
> You could use a dependency injection container which could have initialisation of a class instance which would be executed only once and only when the dependency is needed

@hkdobrev As said, no - not really.

My field objects and validator objects are created by the user, on demand, because the library doesn't offer every conveivable field type or validator, e.g. can't offer fields or validations that are domain-specific.

In other words, I can't use a central facility (DI container or factor class) for the creation or injection of these objects - they have to be entirely user-generated, otherwise the library becomes totally inflexible.

Expecting the user to manually inject dependencies is pretty much out of the question as well.

IMO, translation is one of the few and very rare cases where dependency injection doesn't actually make any sense, for two reasons: first, the need for translation could arise pretty much anywhere, at any time - it's incredibly hard to predict this and design your way around that. And secondly, translations *are* global - no matter how you structure the code, in the end, the string comes from a static language file somewhere, so there is absolutely no point in having more than one instance.

I use dependency injection for almost everything daily, but not for this - I have never seen an instance-based translation facility work out in practice, it always turns out a complete mess.

> I don't think this belongs to the Composer ClassLoader itself.

@stof I agree - this has nothing to do with loading per se, and probably doesn't belong in `ClassLoader`.

I would be more than happy with a separate package of some sort, which would offer this functionality - but I don't think that's even possible, if the mapping from package name to root folder gets discarded at the time of installation/update and isn't recorded or available, in some form, anywhere, at all?

**Comment by mindplay-dk** [comment]
> I suggest you to check https://github.com/swiftmailer/swiftmailer/ to see how they handle their need for a global initialization

@stof as shown, that's what I'm doing now - that approach doesn't really scale though, if you install 25 packages and every one of them adds another `autoload.files`, that's an performance hit for every single request, even though the majority of requests probably don't use e.g. swiftmailer, or translation strings from every installed package, during the same request...

**Comment by mindplay-dk** [comment]
I apologize, I think I'm partially commenting out of context here - I'm thinking in part of #5214 which isn't really directly related to this.

Anyways, what I'm highlighting here, is that e.g. swiftmailer and myself currently resort to *unconditionally* bootstrapping various globals, even when those globals are not needed.

That's the core of my issue here.

**Comment by stof** [comment]
no. Swiftmailer is bootstrapping the globals only the first time one of its classes is autoloaded, which is precisely why I told you to look at the way it does

**Comment by mindplay-dk** [comment]
er, but...

https://github.com/swiftmailer/swiftmailer/blob/5.x/composer.json#L24

**Comment by stof** [comment]
sure, but have you check the content of this file ? It does not initialize the globals. It registers a custom class loader which will do it before loading the classes.

**Comment by mindplay-dk** [comment]
> It registers a custom class loader

and that's global state - that's the kind of bootstrapping I'm talking about :-)

**Comment by mindplay-dk** [comment]
You know, thinking about this, part of me thinks it's "wrong" - but then, if I think about it some more, it's no more or less wrong than autoloading per se, in the sense that it's automating some bootstrapping without which your types wouldn't load and your code wouldn't work.

I think the main difference is that people are used to autoloaders and familiar with the PSR conventions - if you didn't know about these things, nothing you could find in any Composer package would actually work for you.

In my honest opinion, the "correct" solution to this proble, is to add the `require_once` statement to the top of every file that requires this bootstrapping, because it's explicit.

However, it's impossible to do that without violating PSR-1

> Files SHOULD either declare symbols (classes, functions, constants, etc.) or cause side-effects (e.g. generate output, change .ini settings, etc.) but SHOULD NOT do both.

Which leaves me to conclude that there really isn't much of a choice.

**Comment by Seldaek** [comment]
Closing as I think this doesn't really belong in Composer, and I don't think even a generic solution would make much sense as the amount of packages that require this sort of heavy initialization are few and far between.

**Comment by mindplay-dk** [comment]
In case you're wondering why I needed this, here's [a real thing](https://github.com/mindplay-dk/lang/blob/master/src/lang.php#L208) - a simple translation facility that uses a convention of looking for language files in a `lang` folder in your package by default :-)
