### ISSUE TITLE
update --lock  is broken

### ISSUE THREAD

**Issue by Comrade42** [composer/composer#5217]
With the following composer.json:
```json
{
        "some-vendor/some-package": "dev-master",
}
```
When I run this command:
```
composer update --lock --no-scripts
```
to suppress the warning message after a git merge I expected that the reference for this package will not be updated, but it does. If I run this command:
```
composer install --prefer-source --no-scripts
```
right after the previous, I'll get an updated version of the package.

This is reproduced with the latest build of composer [1.0.1 2016-04-18 21:14:28]. With an older one [1.0-dev (bb2e29ba28980676e5728ebbd3020ab02d8dcc86) 2015-11-27 10:56:32] this works fine.

**Comment by Seldaek** [comment]
If you have a chance to set up composer from source and try my branch at https://github.com/composer/composer/pull/5210 that would be cool. I'm curious to see if it fixes that problem.

**Comment by ypereirareis** [comment]
Hi ! Same problem here.

With the build from master every dependencies fixed as `dev-master` or `@dev` are updated when executing a `composer update vendro/lib` or `composer update lock`

Trying to try your "fixing" branch...

**Comment by Seldaek** [comment]
If you `composer self-update --snapshot` you should get a version with a fix included. Please confirm, if so I'll make a 1.0.2 release tomorrow.

**Comment by Seldaek** [comment]
Fixed by c7c8335b8be4ba53e4034fbfd59eaf18ca4c52de btw.

**Comment by Comrade42** [comment]
Hi! Yes, I've tested this with the latest snapshot build 2062070be953edf5d980311f32f5928fd40ddb3a and I got pretty expectable composer.lock file without any reference issues. Thanks for fix.

**Comment by Seldaek** [comment]
OK thanks for confirming

**Comment by Seldaek** [comment]
1.0.2 is out now including this fix btw
