### ISSUE TITLE
Unnable to download packages after updating composer

### ISSUE THREAD

**Issue by Henk8** [composer/composer#5218]
When I run this command:

```
composer.phar update -vvv
```

I get this output:

```
Downloading https://packagist.org/packages.json
Writing /var/www/developers/ralph/.composer/cache/repo/https---packagist.org/packages.json into cache
Updating dependencies (including require-dev)
Downloading http://packagist.org/p/provider-2013%24a5524abc639838848fa3566204cf4dc193ea35b92eb70ec74d759287a6e04a4b.json
Downloading http://packagist.org/p/provider-2013%24a5524abc639838848fa3566204cf4dc193ea35b92eb70ec74d759287a6e04a4b.json
Downloading http://packagist.org/p/provider-2013%24a5524abc639838848fa3566204cf4dc193ea35b92eb70ec74d759287a6e04a4b.json


  [Composer\Downloader\TransportException]
  Content-Length mismatch


Exception trace:
 () at phar:///usr/bin/composer.phar/src/Composer/Util/RemoteFilesystem.php:282
 Composer\Util\RemoteFilesystem->get() at phar:///usr/bin/composer.phar/src/Composer/Util/RemoteFilesystem.php:99
 Composer\Util\RemoteFilesystem->getContents() at phar:///usr/bin/composer.phar/src/Composer/Repository/ComposerRepository.php:645
 Composer\Repository\ComposerRepository->fetchFile() at phar:///usr/bin/composer.phar/src/Composer/Repository/ComposerRepository.php:558
 Composer\Repository\ComposerRepository->loadProviderListings() at phar:///usr/bin/composer.phar/src/Composer/Repository/ComposerRepository.php:289
 Composer\Repository\ComposerRepository->whatProvides() at phar:///usr/bin/composer.phar/src/Composer/DependencyResolver/Pool.php:204
 Composer\DependencyResolver\Pool->computeWhatProvides() at phar:///usr/bin/composer.phar/src/Composer/DependencyResolver/Pool.php:193
 Composer\DependencyResolver\Pool->whatProvides() at phar:///usr/bin/composer.phar/src/Composer/Installer.php:841
 Composer\Installer->processDevPackages() at phar:///usr/bin/composer.phar/src/Composer/Installer.php:492
 Composer\Installer->doInstall() at phar:///usr/bin/composer.phar/src/Composer/Installer.php:228
 Composer\Installer->run() at phar:///usr/bin/composer.phar/src/Composer/Command/UpdateCommand.php:173
 Composer\Command\UpdateCommand->execute() at phar:///usr/bin/composer.phar/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///usr/bin/composer.phar/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/bin/composer.phar/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///usr/bin/composer.phar/src/Composer/Console/Application.php:181
 Composer\Console\Application->doRun() at phar:///usr/bin/composer.phar/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///usr/bin/composer.phar/src/Composer/Console/Application.php:99
 Composer\Console\Application->run() at phar:///usr/bin/composer.phar/bin/composer:43
 require() at /usr/bin/composer.phar:24

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

```

And I expected this to happen:
That the dependencies are updated.

After I updated composer to version 1.0.1 I receive the error above. 
If I downgrade the composer to 1.0.0 everything works fine.

I already have tried to clear the cache.

**Comment by Iruwen** [comment]
Same here. I fixed this for my satis repo by disabling deflate/gzip, but now it fails on packagist. Caused by d716c73333d72478b58768b7ced44c43972ef356?

**Comment by alcohol** [comment]
It could be because now a days `mb_strlen` automatically overloads `strlen` (see [here](http://php.net/manual/en/mbstring.overload.php)).

@Seldaek perhaps using `mb_strlen($string, '8bit')` is safer?

**Comment by Seldaek** [comment]
The content-length for gzipped content should be sent according to the size of the gzipped response, not the original size. 

```
$ curl -H'Accept-encoding:deflate,gzip' -v http://packagist.org/p/provider-2013%24a5524abc639838848fa3566204cf4dc193ea35b92eb70ec74d759287a6e04a4b.json > response; /bin/ls -l response

> GET /p/provider-2013%24a5524abc639838848fa3566204cf4dc193ea35b92eb70ec74d759287a6e04a4b.json 
> Accept-encoding:deflate,gzip

< Content-Length: 384469
< Content-Encoding: gzip
-rw-r--r-- 1 seld seld 384469 Apr 19 15:13 response
```

```
$ curl -v http://packagist.org/p/provider-2013%24a5524abc639838848fa3566204cf4dc193ea35b92eb70ec74d759287a6e04a4b.json > response; /bin/ls -l response

> GET /p/provider-2013%24a5524abc639838848fa3566204cf4dc193ea35b92eb70ec74d759287a6e04a4b.json 

< Content-Length: 787030
-rw-r--r-- 1 seld seld 787030 Apr 19 15:14 response
```

As you can see the gzipped and non-gzipped responses match their exact content-size (pre-unzipping).


@Henk8 @Iruwen can you paste the output of `php -i | grep mbstring.func`? And also.. are you using any proxy?

**Comment by Henk8** [comment]
the output of `php -i | grep mbstring.func` is mbstring.func_overload => 3 => 3. I am not using any proxy

**Comment by Seldaek** [comment]
OK so you are overloading strlen and it probably counts the bytes as utf8 then.. I'll push a fix.

**Comment by Iruwen** [comment]
Same here, thanks.

**Comment by dzuelke** [comment]
Sorry for that oversight. I actually considered that case, got distracted, and then forgot to cover it in the code :<

**Comment by Seldaek** [comment]
Alright. If you `composer self-update --snapshot` you'll get the latest including the patch. Or it'll be included in 1.0.2 when that comes out.

**Comment by Iruwen** [comment]
Confirmed working, thanks.

**Comment by bourdeau** [comment]
Works. Thanks.

**Comment by bourdeau** [comment]
Hum might be my own mistake but I did have this bug yesterday, I did update snapshot composer yesterday and it fixed it. But today I added some new packages to my composer.json and the bug came out again. I did snapshot again and it didn't fix the problem this time.
Any idea?
Thanks

```
mbstring.func_overload => 0 => 0

Composer version 1.1-dev (6146f7aded4af85022b4d04e53143ee6bca6b456) 2016-04-28 21:38:38
```

**Comment by zetta** [comment]
I have the same bug with the version 6146f7aded4af85022b4d04e53143ee6bca6b456. (I just rolled back to stable one), composer was complaining with **Your configuration does not allow connections** but when i add the 

```json
    "config":{
      "secure-http": false
    }
```
It start throwing that exception
```
  [Composer\Downloader\TransportException]
  Content-Length mismatch
```

**Comment by zetta** [comment]
nvm, I ran it again and it works... that's weird

**Comment by dzuelke** [comment]
That indicates either a very spotty connection, @zetta, or a man-in-the-middle (especially if you get HTTPS related warnings). Same with @bourdeau.

Are you using custom non-packagist repositories?

I suggested to @Seldaek that we could add verbose logging to the retry events that read out the `Content-Length` header value as well as the downloaded content size.

**Comment by bourdeau** [comment]
@dzuelke quite possible as we are usin satis and connect trough VPN. Anyway I can’t try to reproduce the bug as I don’t work there any more. Thanks for your help.

**Comment by Zjmainstay** [comment]
Try add another packagist like this: composer config -g repo.packagist composer https://packagist.phpcomposer.com

**Comment by mr-agusismail** [comment]
This Problem :
![screen shot 2017-03-25 at 1 58 35 am](https://cloud.githubusercontent.com/assets/2625413/24309499/9a6e447e-10fe-11e7-9cbc-ef358f0ef0d6.png)

Slove with :
http://stackoverflow.com/questions/38635257/composer-content-length-mismatch

**Comment by curry684** [comment]
Please supply output when running with -vvv flags.

**Comment by peter-gribanov** [comment]
Same problem

```
$ composer install --prefer-dist --no-interaction --no-scripts --no-progress -vvv
Reading ./composer.json
Loading config file /home/travis/.composer/config.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/home/travis/build/gpslab/enum): git branch --no-color --no-abbrev -v
Executing command (/home/travis/build/gpslab/enum): git describe --exact-match --tags
Failed to initialize global composer: Composer could not find the config file: /home/travis/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 1.4.2 (2017-05-17 08:17:52) with PHP 7.1.5 on Linux / 4.8.12-040812-generic
Loading composer repositories with package information
Downloading https://packagist.org/packages.json
Writing /home/travis/.composer/cache/repo/https---packagist.org/packages.json into cache
Updating dependencies (including require-dev)
Downloading http://packagist.org/p/provider-2013%24442e1d5fa0fdbf77855cc363b024994a3e92a2f5099e5138b9c5777ae486703c.json
Downloading http://packagist.org/p/provider-2013%24442e1d5fa0fdbf77855cc363b024994a3e92a2f5099e5138b9c5777ae486703c.json
Downloading http://packagist.org/p/provider-2013%24442e1d5fa0fdbf77855cc363b024994a3e92a2f5099e5138b9c5777ae486703c.json
                                            
  [Composer\Downloader\TransportException]  
  Content-Length mismatch                   
                                            
Exception trace:
 () at phar:///home/travis/.phpenv/versions/7.1.5/bin/composer/src/Composer/Util/RemoteFilesystem.php:289
 Composer\Util\RemoteFilesystem->get() at phar:///home/travis/.phpenv/versions/7.1.5/bin/composer/src/Composer/Util/RemoteFilesystem.php:101
 Composer\Util\RemoteFilesystem->getContents() at phar:///home/travis/.phpenv/versions/7.1.5/bin/composer/src/Composer/Repository/ComposerRepository.php:664
 Composer\Repository\ComposerRepository->fetchFile() at phar:///home/travis/.phpenv/versions/7.1.5/bin/composer/src/Composer/Repository/ComposerRepository.php:576
 Composer\Repository\ComposerRepository->loadProviderListings() at phar:///home/travis/.phpenv/versions/7.1.5/bin/composer/src/Composer/Repository/ComposerRepository.php:296
 Composer\Repository\ComposerRepository->whatProvides() at phar:///home/travis/.phpenv/versions/7.1.5/bin/composer/src/Composer/DependencyResolver/Pool.php:204
 Composer\DependencyResolver\Pool->computeWhatProvides() at phar:///home/travis/.phpenv/versions/7.1.5/bin/composer/src/Composer/DependencyResolver/Pool.php:193
 Composer\DependencyResolver\Pool->whatProvides() at phar:///home/travis/.phpenv/versions/7.1.5/bin/composer/src/Composer/DependencyResolver/RuleSetGenerator.php:168
 Composer\DependencyResolver\RuleSetGenerator->whitelistFromPackage() at phar:///home/travis/.phpenv/versions/7.1.5/bin/composer/src/Composer/DependencyResolver/RuleSetGenerator.php:322
 Composer\DependencyResolver\RuleSetGenerator->getRulesFor() at phar:///home/travis/.phpenv/versions/7.1.5/bin/composer/src/Composer/DependencyResolver/Solver.php:214
 Composer\DependencyResolver\Solver->solve() at phar:///home/travis/.phpenv/versions/7.1.5/bin/composer/src/Composer/Installer.php:472
 Composer\Installer->doInstall() at phar:///home/travis/.phpenv/versions/7.1.5/bin/composer/src/Composer/Installer.php:223
 Composer\Installer->run() at phar:///home/travis/.phpenv/versions/7.1.5/bin/composer/src/Composer/Command/InstallCommand.php:119
 Composer\Command\InstallCommand->execute() at phar:///home/travis/.phpenv/versions/7.1.5/bin/composer/vendor/symfony/console/Command/Command.php:267
 Symfony\Component\Console\Command\Command->run() at phar:///home/travis/.phpenv/versions/7.1.5/bin/composer/vendor/symfony/console/Application.php:846
 Symfony\Component\Console\Application->doRunCommand() at phar:///home/travis/.phpenv/versions/7.1.5/bin/composer/vendor/symfony/console/Application.php:191
 Symfony\Component\Console\Application->doRun() at phar:///home/travis/.phpenv/versions/7.1.5/bin/composer/src/Composer/Console/Application.php:227
 Composer\Console\Application->doRun() at phar:///home/travis/.phpenv/versions/7.1.5/bin/composer/vendor/symfony/console/Application.php:122
 Symfony\Component\Console\Application->run() at phar:///home/travis/.phpenv/versions/7.1.5/bin/composer/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar:///home/travis/.phpenv/versions/7.1.5/bin/composer/bin/composer:54
 require() at /home/travis/.phpenv/versions/7.1.5/bin/composer:24
```

**Comment by joenmarz** [comment]
$ composer self-update --snapshot
Updating to version 4d8b9be5b6a0bda0a3d24c0a6ff89d7ccb26f715 (snapshot channel).
   Downloading (100%)
Use composer self-update --rollback to return to version 1.6.3

joenmarz@JR-NETWORK-SRV1 C:\Users\joenmarz
$ composer global require "fxp/composer-asset-plugin:^1.4.2" -vvv
Changed current directory to C:/Users/joenmarz/AppData/Roaming/Composer
Reading ./composer.json
Loading config file C:/Users/joenmarz/AppData/Roaming/Composer/config.json
Loading config file C:/Users/joenmarz/AppData/Roaming/Composer/auth.json
Loading config file ./composer.json
Loading config file C:\Users\joenmarz\AppData\Roaming\Composer/auth.json
Reading C:\Users\joenmarz\AppData\Roaming\Composer/auth.json
Checked CA file C:\Users\joenmarz\AppData\Local\Temp\ope1850.tmp: valid
Executing command (C:\Users\joenmarz\AppData\Roaming\Composer): git branch --no-color --no-abbrev -v
Executing command (C:\Users\joenmarz\AppData\Roaming\Composer): git describe --exact-match --tags
Executing command (C:\Users\joenmarz\AppData\Roaming\Composer): git log --pretty="%H" -n1 HEAD
Executing command (C:\Users\joenmarz\AppData\Roaming\Composer): hg branch
Executing command (C:\Users\joenmarz\AppData\Roaming\Composer): fossil branch list
Executing command (C:\Users\joenmarz\AppData\Roaming\Composer): fossil tag list
Executing command (C:\Users\joenmarz\AppData\Roaming\Composer): svn info --xml
Running 4d8b9be5b6a0bda0a3d24c0a6ff89d7ccb26f715 (2018-03-05 22:34:22) with PHP 7.2.3 on Windows NT / 6.1
Downloading https://packagist.org/packages.json
Downloading https://packagist.org/packages.json
Writing C:/Users/joenmarz/AppData/Local/Composer/repo/https---packagist.org/packages.json into cache
Downloading https://packagist.org/p/provider-2013%247b505cb90a7b4985feae767f3a53e934abf7f51e2aeb711c64b280cbf24fbe72.json
Downloading https://packagist.org/p/provider-2013%247b505cb90a7b4985feae767f3a53e934abf7f51e2aeb711c64b280cbf24fbe72.json
Downloading https://packagist.org/p/provider-2013%247b505cb90a7b4985feae767f3a53e934abf7f51e2aeb711c64b280cbf24fbe72.json


  [Composer\Downloader\TransportException]
  The "https://packagist.org/p/provider-2013%247b505cb90a7b4985feae767f3a53e934abf7f51e2aeb711c64b280cbf24fbe72.json" file could not be downloaded: SSL: Handshake time
  d out
  Failed to enable crypto
  failed to open stream: operation failed
  Undefined variable: http_response_header
