### ISSUE TITLE
Init git submodules?

### ISSUE THREAD

**Issue by ro0NL** [composer/composer#5223]
Hi,

We have a package with a registered submodule path (dont ask ;-)). When we install this via `create-project` as root project we encounter all sort of application errors due some scripts being ran.

This is because we are missing source files from the submodule as these are not initted at this point. This forces us to use te following workflow..

```
composer create-project --no-scripts vendor/package /path/to/install
cd /path/to/install
git submodule update --init
composer run-script post-root-package-install
composer run-script post-install-cmd
```

Basicly it would be awesome if `create-project` does this for us.. so we can just use
`composer create-project vendor/package /path/to/install`

Any thoughts?

**Comment by ro0NL** [comment]
Perhaps we can just add `--recursive` to the `git clone` command (https://github.com/composer/composer/blob/1.0/src/Composer/Downloader/GitDownloader.php#L48)

**Comment by Seldaek** [comment]
I don't think we want to add that to the GitDownloader as that would then apply to all installed packages, and I have no idea what the consequences would be but overall git submodules are such a pain that I'd rather not do that.

Why not add `git submodule update --init` to your `post-root-package-install` scripts?

**Comment by ro0NL** [comment]
You sir are a genius :) going to test it now.

Still believe composer should do it for us (indeed at root level only) to guarantee a full workingcopy (i.e. complete source code). We can assume any registered submodule SHOULD be part of the entire source code.. right?

**Comment by ro0NL** [comment]
My colleague just proposed to ask it interactively while running `create-project`.. which would be totally wicked awesome offcourse ;-)

Something like `Submodule detected for path /path. Would you like to update it? [y/N]`

**Comment by ro0NL** [comment]
Adding `git submodule update --init` to `post-root-package-install` works like a charm. So my problem is fixed for now.. what do you think about my feature request to ask it interactively for ANY package being installed...

**Comment by Seldaek** [comment]
TBH as it's.. IIRC the first time ever someone asked for submodule support, I don't think it's really worth the effort :) Glad that fixed it for you though.
