### ISSUE TITLE
Install Composer problem on Win 7

### ISSUE THREAD

**Issue by ColumbiaBlooms** [composer/composer#5225]
![composer](https://cloud.githubusercontent.com/assets/12977583/14678272/a7492fb2-06da-11e6-88a8-562c4bce1fe4.png)
Please see attached image. How do I solve this problem?

**Comment by stof** [comment]
Can you fix the Markdown markup of your issue description ? We are missing the relevant content currently as it is totally broken

**Comment by stof** [comment]
btw, by taking your screenshot URL to open it, I can tell you that the answer is inside the screenshot itself: you need to enable the openssl extension. and the error screen even tells you where the php.ini file is.

**Comment by ColumbiaBlooms** [comment]
I did my best to edit the question, but the image disappeared. This is a very difficult forum to use!

I followed the instructions. The extension is apparently enabled in php.ini. 

extension=php_openssl.dll

I'm using php 7 with MAMP. Is this the problem?

**Comment by alcohol** [comment]
What if you run php on the command line and pass the option `-m`; does it list openssl as one of the modules/extensions?

**Comment by ColumbiaBlooms** [comment]
Hmmm ...

This is weird. I found another php.ini at C:\MAMP\bin\php\php7.0.0. extension=php_openssl.dll was commented out in that one. I removed the ";", saved the file, and typed php -m in the Windows command prompt window, but openssl is not listed.

What's going on? It's as if the php.ini is being ignored.

**Comment by curry684** [comment]
Run:
```sh
php --ini
```
It will tell you exactly which ini files are loaded, in what order, from where.

**Comment by ColumbiaBlooms** [comment]
Thanks for the help. Obviously I'm a newbie and know little about php! Your kind help is greatly appreciated.

Here's what was returned.

`Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>cd C:\MAMP\bin\php\php7.0.0

C:\MAMP\bin\php\php7.0.0>php -m
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\php\php_openssl.dl
l' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'C:\php\php_openssl.dll' -
The specified module could not be found.
 in Unknown on line 0
[PHP Modules]
bcmath
calendar
com_dotnet
Core
ctype
date
dom
filter
hash
iconv
json
libxml
mcrypt
mysqlnd
odbc
pcre
PDO
pdo_mysql
Phar
Reflection
session
SimpleXML
soap
sockets
SPL
standard
tidy
tokenizer
wddx
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]


C:\MAMP\bin\php\php7.0.0>php --ini
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\php\php_openssl.dl
l' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'C:\php\php_openssl.dll' -
The specified module could not be found.
 in Unknown on line 0
Configuration File (php.ini) Path: C:\Windows
Loaded Configuration File:         C:\MAMP\bin\php\php7.0.0\php.ini
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)

C:\MAMP\bin\php\php7.0.0>`

There was no php.ini in c:\windows.

Note the warning about the dll. There is no php folder in C:. The dll is, however, located at C:\MAMP\bin\php\php7.0.0\ext. I updated extension=C:\MAMP\bin\php\php7.0.0\ext\php_openssl.dll by adding the path & the warning disappeared. 

Whew! Composer now installs.

**Comment by curry684** [comment]
Keep the extension lines all as they are:

    extension=php_openssl.dll

And instead look for the `extension_dir` settings in there and set it like this:

    extension_dir=C:\MAMP\bin\php\php7.0.0\ext\

It will make sure you don't run into this issue again if you load all extensions from that folder.

**Comment by marcomenzel** [comment]
Relative paths are possible as well: `extension_dir = "ext"`
