### ISSUE TITLE
Ambiguous class resolution from string "class can" located anywhere in comments

### ISSUE THREAD

**Issue by HasAusten** [composer/composer#5230]
Starting with composer version 1.0.0 beta 2
and continuing with version 1.0.2

I get this output:
```
...snip
Generating autoload files
Warning: Ambiguous class resolution, "can" was found in both "netAcuity/UDP/NetAcuityUDP.php" and "netAcuity/UDP/NetAcuityXML.php", the first will be used.
Warning: Ambiguous class resolution, "can" was found in both "netAcuity/UDP/NetAcuityUDP.php" and "netAcuity/UDP/RawResponse.php", the first will be used.
Warning: Ambiguous class resolution, "can" was found in both "netAcuity/UDP/NetAcuityUDP.php" and "netAcuity/UDP/NetAcuityASN.php", the first will be used.
Warning: Ambiguous class resolution, "can" was found in both "netAcuity/UDP/NetAcuityUDP.php" and "netAcuity/UDP/NetAcuityCBSA.php", the first will be used.
```

Sample of grep -R "class can" in the offending directory:
```
netAcuity/SharedMemory/NetAcuitySHM.php: * Description: This class can be used to interface with NetAcuity databases
netAcuity/UDP/NetAcuityUDP.php: * Description: This class can be used to interfaces with a NetAcuity server.
netAcuity/UDP/NetAcuityXML.php: * Description: This class can be used to interfaces to the NetAcuity server.
netAcuity/UDP/RawResponse.php: * Description: This class can be used to interfaces to the NetAcuity server.
netAcuity/UDP/example/NetAcuityASNExample.php: * Description: This class can be used to interfaces to the NetAcuity server.
```

This doesn't affect the running autoload classmap since "can" is not a class defined anywhere in my codebase, but it still floods our logs whenever we deploy.

**Comment by Seldaek** [comment]
Is the package public? Do you have a list to the source file? Or could you share at least a bit of it, enough to make it reproducible?

**Comment by HasAusten** [comment]
Yep, these are simulated files, since I can't share the originals without violating NDA. But tested here and it reproduces just the same.

Files are included in composr.json through
```json
"autoload": {
    "classmap": [
        "app/ext/modules",
```

which includes multiple subdirectories within, and including "repro" attached here: [repro.zip](https://github.com/composer/composer/files/230871/repro.zip)

Don't know if it matters, but composer is being invoked as follows:

composer update --no-dev

and composer.json is set to minimum-stability of "dev"

**Comment by Seldaek** [comment]
Ok so.. I can't reproduce it. Works fine for me but for some odd reason in CLI I can reproduce it with `php -r 'var_dump(php_strip_whitespace("four.php"));'` That prints the file without stripping the comments. I don't know why it doesn't act the same when composer actually runs (there I only get: `<? class FourClassThatDoesntExistAnywhereElse{}` as output, which is expected).

In any case, it seems php_strip_whitespace has issues with PHP short-open-tags, so if you have a chance to change your files to `<?php` it should solve it. I am not sure what we can do here as I can't even reproduce it.

**Comment by curry684** [comment]
It's very well possible that `short_open_tag`, off by default on every modern PHP install, was only enabled in `/etc/php/apache2/php.ini`...?

**Comment by Seldaek** [comment]
Ah that's why it works for me in composer and not in CLI actually:

I run composer via a `php -n ...` alias:
```
$ php -ni | grep short
short_open_tag => On => On
```

But my php.ini disables the short open tags:
```
$ php -i | grep short
short_open_tag => Off => Off
```

So.. @HasAusten either fix your php.ini or fix the files :)
