### ISSUE TITLE
Global composer with run-script does not use autoload

### ISSUE THREAD

**Issue by sourcerer-mike** [composer/composer#5233]
With the following composer.json:

```json
{
  "name": "my/own",
  "autoload": {
    "files": [
      "etc/composer/autoload.php"
    ]
  },
  "scripts": {
    "post-install-cmd": "Composer_Post_Install_Cmd::execute"
  },
  "config": {
    "bin-dir": "bin"
  },
  "require": {
    "composer/composer": "1.0.0-alpha11",
    "leafo/scssphp": "^0.6.3",
    "gettext/gettext": "~3",
    "phploc/phploc": "~2",
    "sourcerer-mike/wp-easy-translate": "dev-master",
    "symfony/finder": "~2",
    "symfony/filesystem": "~2",
    "wp-coding-standards/wpcs": "0.9.0",
    "wp-cli/wp-cli": "~0.23"
  },
  "require-dev": {
    "deployer/deployer": "~3",
    "phpunit/phpunit": "~4"
  }
}
```

When I run this command:

```
composer run-script -vvv post-install-cmd
```

I get this output:

```
Running 1.0.2 (2016-04-21 12:30:18) with PHP 5.6.11-1ubuntu3.2 on Linux / 4.2.0-35-generic
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Reading ./composer.json
Loading config file /home/mike/.composer/config.json
Loading config file /home/mike/.composer/auth.json
Loading config file ./composer.json
Checking CA file /etc/ssl/certs/ca-certificates.crt
Executing command (/home/mike/public_html/rmp/cb): git branch --no-color --no-abbrev -v
Reading /home/mike/.composer/composer.json
Loading config file /home/mike/.composer/config.json
Loading config file /home/mike/.composer/auth.json
Loading config file /home/mike/.composer/composer.json
Loading config file /home/mike/.composer/auth.json
Reading /home/mike/public_html/rmp/cb/vendor/composer/installed.json
Reading /home/mike/.composer/vendor/composer/installed.json
Class Composer_Post_Install_Cmd is not autoloadable, can not call post-install-cmd script
```

And I expected this to happen:

- Load the class
- Run the script

Additional information:

When I run the local installed composer (alpha-11) via `bin/composer run-script -vvv post-install-cmd` then it correctly loads the autoloader (see above in the composer.json).

```
// ...
Executing command (/home/mike/public_html/rmp/cb): git describe --exact-match --tags
Executing command (/home/mike/public_html/rmp/cb): git branch --no-color --no-abbrev -v
> post-install-cmd: Composer_Post_Install_Cmd::execute
Flushing cache ...
// ...
```

Edit: The autoloader `vendor/autoload.php` is not/never loaded by the global `composer` (1.0.2) but via `bin/composer` it is.

**Comment by stof** [comment]
> Edit: The autoloader vendor/autoload.php is not/never loaded by the global composer (1.0.2) but via bin/composer it is.

This is because your ``bin/composer`` means that composer is installed in the project itself, and so its autoloader is the project autoloader. this is why it loads it.


Regarding the normal usage of composer, it registers the autoloader for PSR-0, PSR-4 and classmap when running hooks. It does not load the files, as this could cause issues (as files cannot be loaded multiple times)

**Comment by sourcerer-mike** [comment]
Is this failure by design? I understand the risk that someone could write bad code and require files multiple times. But in that case I would say: Let them do it and fail.
I hope composer also uses the file section so that every file can be loaded. It is such inhomogenous behaviour if it one time does that and the other day it's different. So annoying.

Will this be fixed?

**Comment by alcohol** [comment]
It is known that `scripts` can only make use of `psr-0`, `psr-4` and `classmap`, since these are known to the `Classloader` instance that is loaded when `scripts` are run. Since `scripts` can run before any autoloading files have been generated, it doesn't use the normal autoloader which would support files autoloading. This is documented. This will likely not be "fixed" anytime soon.

**Comment by Seldaek** [comment]
As @alcohol said, it's a known limitation..
