### ISSUE TITLE
null in cache file for a tag that is missing a composer.json causes re checking on update

### ISSUE THREAD

**Issue by FinBoWa** [composer/composer#5234]
With the following composer.json:

```json
{
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/Focus-Flow/silverstripe-framework"
    }
  ],
  "name": "focusflow/silverstripe-installer",
  "description": "The SilverStripe Framework Installer",
  "require": {
    "php": ">=5.4.0",
    "composer/installers": "v1.0.13",
    "silverstripe/cms": "~3.2",
    "silverstripe/framework": "dev-ff-3-2 as 3.2.3"
  },
  "config": {
    "process-timeout": 600,
    "preferred-install": "dist"
  }
}
```

When I run this command:

```
composer update -vvv  ( after running composer install first of course) 
```

Part of the output is output:

```
[10.4MB/6.76s] Reading composer.json of silverstripe/framework (3.0.2-rc2)
[10.4MB/6.76s] Reading /Users/olli.tyynela/.composer/cache/repo/github.com/Focus-Flow/silverstripe-framework/db1bffb05406441781a70d0326eb3537ec0dd3b0 from cache
[10.4MB/6.76s] Downloading https://api.github.com/repos/Focus-Flow/silverstripe-framework/contents/composer.json?ref=db1bffb05406441781a70d0326eb3537ec0dd3b0
[10.4MB/7.52s] Downloading https://api.github.com/repos/Focus-Flow/silverstripe-framework/contents/composer.json?ref=db1bffb05406441781a70d0326eb3537ec0dd3b0
[10.4MB/8.26s] Writing /Users/olli.tyynela/.composer/cache/repo/github.com/Focus-Flow/silverstripe-framework/db1bffb05406441781a70d0326eb3537ec0dd3b0 into cache
[10.4MB/8.26s] Skipped tag 3.0.2-rc2, no composer file
```
And I expected this to happen:

No re-reading the tags composer file.. It doesn't exist. 

The cache file contains just null, but shouldn't that be treaded as "cached" as the file exists. Even if the tag doesn't contain a valid composer.json file?

Of course the alternative would be to trim out really old tags of our fork. 

/cc @jyrkij

**Comment by FinBoWa** [comment]
Version of composer is Composer version 1.0.2 2016-04-21 12:30:18. 

Also it seems to do 2 times the downloading. Thus slowing slighly more.

**Comment by alcohol** [comment]
Hmm.. it only seems to do the download attempt twice if it cannot find a `composer.json`.

This seems to be on purpose though: [GitHubDriver.php#L153](https://github.com/composer/composer/blob/49d7d65933c78e163354c2c580883926f1c8daee/src/Composer/Repository/Vcs/GitHubDriver.php#L153)

I'm not sure why we are writing a cache file though when we actually cannot find a `composer.json`. 

Again, this also seems on purpose though: [GitHubDriver.php#L191-L193](https://github.com/composer/composer/blob/49d7d65933c78e163354c2c580883926f1c8daee/src/Composer/Repository/Vcs/GitHubDriver.php#L191-L193)

I'm guessing an empty file though results in `$res` being *`falsy`* and thus not being added to the cache here: [GitHubDriver.php#L148-L150](https://github.com/composer/composer/blob/49d7d65933c78e163354c2c580883926f1c8daee/src/Composer/Repository/Vcs/GitHubDriver.php#L148-L150)

/cc @Seldaek thoughts?

**Comment by FinBoWa** [comment]
@alcohol if I remember correctly @jyrkij had some different cache store values for those, presumably from a older composer, and when he runs composer update / installs the cache is accepted. 

# I'm not sure why we are writing a cache file though when we actually cannot find a composer.json.

I think it should and it should accept it, the missing composer.json valid response as it doesnt't exists so the re checking can be skipped if its in cache.

**Comment by alcohol** [comment]
That is not entirely true though, as tags are not set in stone but can actually be updated/moved. So it's possible that a tag that did not contain a composer.json could suddenly contain one. However, I suppose a simple `cache-clear` run would resolve that situation. And in reality, tags should be treated as immutable (even when they are not).

**Comment by alcohol** [comment]
> @alcohol if I remember correctly @jyrkij had some different cache store values for those, presumably from a older composer, and when he runs composer update / installs the cache is accepted.

What do you mean by that? I don't quite understand, sorry.

**Comment by Seldaek** [comment]
We never cache (or if we do, it's a bug) when we can't find a composer.json, as that might well change in the future and we have no way of knowing. The solution for private packages is rather to use https://toranproxy.com so it can do the processing in the back and your updates can be fast without scanning every branch/tag. Cleaning up your old branches/tags that don't have composer.json can help of course, but I can see that this isn't always feasible.

**Comment by alcohol** [comment]
@Seldaek ok so if you look at the code I linked, we obviously have a bug then it seems :-).

**Comment by Seldaek** [comment]
Yeah I see.. https://github.com/composer/composer/commit/4c501365226d896183f04524966487ea8088fcc6 should fix :)

**Comment by FinBoWa** [comment]
> What do you mean by that? I don't quite understand, sorry.

@alcohol I meant that he has, if i remember correctly, false stored in the tags cache file or something else than null. Thus hes updates will skip the trying to download the composer.json bit .  

@Seldaek Ok. Thas fine. But even you closed this I just want to clarify my line of thought:

Wouldn't adding a composer.json to a tag after it has been created, and possibly cached, be the same as, for example, changing composer.json requirements, version constrains or similar, after the tag has been pushed to the wild?

Wouldn't the latter also be possibly cached unless you are quick enough to change it before anyone can do updates?

Also this is a case example of a "public" hotfix pull request that might not get merged to the upstream in time, but we need to get it on our projects quickly as possible. As we are using branch alias but its reading all the tags still. 

Anywyas that was my 5 cents.. need to look in to the proxy also.

**Comment by Seldaek** [comment]
@FinBoWa actually in case a tag is re-tagged it would get invalidated because the hash changes. I think the main reason we don't cache is actually not because the state could change but rather in case of failures from github we don't want to cache a state that is invalid. It used to fail a bit randomly with false-404s (hence why we added the retry). Not sure how bad it is these days.

**Comment by FinBoWa** [comment]
@Seldaek That makes sense. Thought I would like to hope that they have improved a lot but could you trust them not to cause the same issues why those fail safes were introduced in the first place. Probably not :) 

Anyways: that means I just need to trim either the tags a way or look in to the proxy.. 

 Cheers!
