### ISSUE TITLE
Composer replaces class names in plugins with `_composer_tmp0`

### ISSUE THREAD

**Issue by Ocramius** [composer/composer#5237]
First, note that this happens sporadically, and I didn't yet identify which state transition causes the composer [`PluginManager`](https://github.com/composer/composer/blob/6ce8477d04e4102944598d108bcc90d63cf442d4/src/Composer/Plugin/PluginManager.php) to do that.

Specifically, [my plugin](https://github.com/Ocramius/PackageVersions/blob/a108adf44c4663bfb72858ea2fcd174acddd317e/src/PackageVersions/Installer.php#L17-L30) looks like following:

```php
class MyPlugin
{
    const SOMETEMPLATE = <<<'PHP'
final class GeneratedThing
{
}
PHP;

    // ...
}
```

Composer seems to generate a temporary class to be [passed to `eval()` in some conditions](https://github.com/composer/composer/blob/6ce8477d04e4102944598d108bcc90d63cf442d4/src/Composer/Plugin/PluginManager.php#L181-L191).
I cannot reproduce the bug yet, but it seems seems related to optimized classmaps.
The replacement of the class names is done via a regular expression.
The regular expression doesn't recognize the difference between `class MyPlugin` (class definition) and `final class GeneratedThing` (within a string), and replaces both instances with respectively `MyPlugin_composer_tmp0` and `final class GeneratedThing_composer_tmp0`.

The [offending regex](https://github.com/composer/composer/blob/6ce8477d04e4102944598d108bcc90d63cf442d4/src/Composer/Plugin/PluginManager.php#L184) should probably be replaced with AST-aware code.

**Comment by Ocramius** [comment]
Meanwhile, worked around this bug via Ocramius/PackageVersions#16

**Comment by Ocramius** [comment]
I managed to reproduce this bug thanks to @BarthyB:

Given following `composer.json`:

```json
{
    "require": {
        "vich/uploader-bundle": "1.0.1",
        "ocramius/package-versions": "1.0.3"
    }
}
```

Run a `composer install` (output not relevant).

Then check `vendor/ocramius/package-versions/src/PackageVersions/Versions.php`. File should start with something like following:

```php
<?php

namespace PackageVersions;

/**
 * This class is generated by ocramius/package-versions, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class Versions
{
```

Run `composer require oneup/uploader-bundle` (output not relevant).

Check the `vendor/ocramius/package-versions/src/PackageVersions/Versions.php` file again:

```
<?php

namespace PackageVersions;

/**
 * This class is generated by ocramius/package-versions, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class Versions_composer_tmp0
{
```

**Comment by slbmeh** [comment]
Effort to leverage the internal tokenizer can be reused in #5239
