### ISSUE TITLE
Incorrect autoload generation in PHP 7 for anonymous class

### ISSUE THREAD

**Issue by kamilsk** [composer/composer#5239]
Failed build: https://travis-ci.org/kamilsk/Common/jobs/125265796

With the following composer.json:

```json
{
  "name": "kamilsk/common",
  "require": {
    "php": ">=7.0"
  },
  "autoload": {
    "psr-4": { "OctoLab\\Common\\": "src/" }
  },
  "autoload-dev": {
    "psr-4": { "OctoLab\\Common\\": "tests/" }
  }
}
```

When I run this command:

```
composer install -o && phpunit
```

I get this output:

```
Cannot declare class OctoLab\Common\Test\ClassAvailabilityTest, because the name is already in use
```

And I expected this to happen: all tests passed

---

In `vendor/composer/autoload_classmap.php` I found an incorrect generated definition `'OctoLab\\Common\\Test\\extends' => $baseDir . '/tests/Test/ClassAvailabilityTest.php',`

This is because in a test class I have something like this

```php
protected function getTest(): ClassAvailability
    {
        return new class extends ClassAvailability
        {
            protected function getClasses(): \Generator
            {
                foreach (require dirname(__DIR__, 2) . '/vendor/composer/autoload_classmap.php' as $class => $path) {
                    $signal = yield $class;
                    if (SIGSTOP === $signal) {
                        return;
                    }
                }
            }
        };
    }
```

I think that the parser has an incorrect reaction at `return new class extends ClassAvailability`.

**Comment by kamilsk** [comment]
https://travis-ci.org/kamilsk/Common/jobs/125271063 fixed by https://github.com/kamilsk/Common/commit/fbf4675ae6ccb904dbe39edbaaf6d4c78455a77d

**Comment by curry684** [comment]
I'm pretty sure these new PHP7 semantics kill the current regex based parsing there. Don't think we have much choice but to switch to real tokenizer for the class detectors.

**Comment by kamilsk** [comment]
@Seldaek, awesome! Thank you!
