### ISSUE TITLE
[feature] supporting "not only php" ... twitter/bootstrap for example

### ISSUE THREAD

**Issue by brikou** [composer/composer#524]
It is not an issue but working on php project involve sometimes more than php libraries but for example JS library or even bulk library. I think for example about http://twitter.github.com/bootstrap/ 

We could define a composer file for this github project which could be used with assetic (supporting less in this example), what do you think about supporting this kind of library?

cheer

**Comment by Seldaek** [comment]
Yeah I think we can leave that in the plugin for now, it can always be revisited later if it makes sense.
