### ISSUE TITLE
Show only first level dependencies when running composer outdated

### ISSUE THREAD

**Issue by briedis** [composer/composer#5240]
I've got a pretty fresh Laravel installation (6 dependencies, 5 dev dependencies). When I run outdated command, it lists about 70 packages. Scanning the list is hard too, because outdated ones are somewhere mixed between (looks like packages are alphabetically sorted) those which are up-to-date.

![Screenshot](https://ziedlejas.lv/screenshots/img.2016.04.24.bmvOZd.png)

I've got two suggestions, which would make this feature more useful, for me at least:
1. List actually outdated packages at top, somehow separately
2. By default show only my composer.json file dependency statuses, because I don't have any say for 90% of the listed dependencies.

**Comment by barryvdh** [comment]
FYI, if your shell supports colors, it is a lot clearer, as outdated versions are orange/red ;)
And dependant packages are equally important, you could create PR/issues. But some filtering could be helpful indeed (only root, only outdated etc)

**Comment by briedis** [comment]
Ah, the joy of windows command line :)

> you could create PR/issues

Eh, developers are too lazy to update their own project. I bet that maybe 1% would go and submit issues/PRs to other dependencies, so I think that by default we should see only root packages.

Maybe display root packages and below the list show a red text -
`There are X other outdated sub-packages. Run the command with --all to list them`

**Comment by barryvdh** [comment]
But if they have setup their decisions correctly, you can still update the dependant packages by just running composer update.

**Comment by Seldaek** [comment]
@briedis you can get colors on windows using either git bash or ansicon or conemu or a gazillion ways :) Just don't use plain cmd.exe as that is useless.

**Comment by briedis** [comment]
@Seldaek Tried running git bash, it shows colors, but still composer outdated was not in color:
https://ziedlejas.lv/screenshots/img.2016.04.24.RAPr96.png
(I'm using PhpStorms terminal, which used basic cmd.exe. I'll try plugging-in others you recommended, thanks!)

**Comment by Seldaek** [comment]
OK, try to call `export ANSICON=1` and then calling composer outdated, curious if that helps. On windows we need some sort of sign telling us that we can use colors, otherwise it looks like garbage if we trigger coloring when the terminal doesn't actually support it :)

**Comment by Seldaek** [comment]
And btw I'm working on a couple new flags to sort the OP out. Should be done soon

**Comment by Seldaek** [comment]
OK https://github.com/composer/composer/commit/aabe21d84d14418508fc46109f0484e98342e4dc adds --outdated/-o to remove up to date packages and --direct/-D to limit to your direct dependencies. `composer outdated -oD` is what you want I suppose.

**Comment by briedis** [comment]
Wow, that was fast! Amazing work, keep it up!
