### ISSUE TITLE
Respect minimum-stability for outdated

### ISSUE THREAD

**Issue by mbrodala** [composer/composer#5241]
With the following composer.json:

```json
{
  "name": "vendor/package",
  "require": {
    "php": "^5.6",
    "vendor/foo": "^1.2.3",
    "vendor/bar": "^4.5"
  }
}
```

When I run this command:

```
composer outdated
```

I get this output:

```
vendor/foo    1.2.3              dev-master deadbee Foo description
vendor/bar    4.5.6              dev-master abcdef0 Bar description
```

And I expected this to happen:

No output of dev/branch updates. Only stable releases should be taken into account here depending on `minimum-stability`.

**Comment by alcohol** [comment]
Can you also include your requirements definitions in your information?

**Comment by mbrodala** [comment]
@alcohol Nothing special really, initial message updated.

**Comment by mbrodala** [comment]
Strange thing is that I cannot reproduce this with the following workflow:

```
$ cd /path/to/tmp
$ composer require vendor/foo
$ composer outdated
```

In this case the `outdated` command does not list the master changes.

**Comment by Seldaek** [comment]
What are your minimum-stability and prefer-stable set to in composer.json?

**Comment by mbrodala** [comment]
Nothing set explicitly, thus Composer standard.

**Comment by Seldaek** [comment]
OK then I need a reproducible case because I don't see this here. What are those packages? Can you share the composer.json? At least which constraint they have and where they come from (packagist, VCS repo, ..?)

**Comment by mbrodala** [comment]
I'll get back to you when I have a minimal example to reproduce.

**Comment by mbrodala** [comment]
I was not able to reproduce this, thus closing this for now. I'll update this once I see it again and can reproduce it easily.
