### ISSUE TITLE
composer-plugin-api 1.0.0 -> no matching package found

### ISSUE THREAD

**Issue by shochdoerfer** [composer/composer#5252]
With the following composer.json (and the respective composer.lock file in place):

```json
{
  "require": {
    "sculpin/sculpin": "~2.0@dev",
    "composer/composer": "@dev",
    "dflydev/embedded-composer-console": "@dev",
    "dflydev/embedded-composer-core": "@dev",
    "phing/phing": "^2.13"
  }
}
```

When I run this command in my continuousphp build pipeline:

```
php5.6 -d memory_limit=-1 composer install -o --no-interaction --ansi --no-scripts --no-progress --no-dev
```

I get this output:

```
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug 
Loading composer repositories with package information 
Installing dependencies from lock file 
Your requirements could not be resolved to an installable set of packages. 
 
Problem 1 
- Installation request for sculpin/sculpin-theme-composer-plugin v1.0.0 -> satisfiable by sculpin/sculpin-theme-composer-plugin[v1.0.0]. 
- sculpin/sculpin-theme-composer-plugin v1.0.0 requires composer-plugin-api 1.0.0 -> no matching package found. 
Problem 2 
- sculpin/sculpin-theme-composer-plugin v1.0.0 requires composer-plugin-api 1.0.0 -> no matching package found. 
- sculpin/sculpin dev-master requires sculpin/sculpin-theme-composer-plugin 1.0.*@dev -> satisfiable by sculpin/sculpin-theme-composer-plugin[v1.0.0]. 
- Installation request for sculpin/sculpin dev-master -> satisfiable by sculpin/sculpin[dev-master]. 
 
Potential causes: 
- A typo in the package name 
- The package is not available in a stable-enough version according to your minimum-stability setting 
see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details. 
 
Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems. 

```

When running the same command locally with PHP 5.6 cli client the install command works fine. I even cleaned the ~/.composer/cache folder to make sure not to deal with any side effects. Any pointers?

**Comment by stof** [comment]
@shochdoerfer what is the version of composer used on your server where it fails ? Run ``composer --version`` to get it

**Comment by shochdoerfer** [comment]
Both locally and on the continuousphp infrastructure runs version 1.0.2.

**Comment by Seldaek** [comment]
Pretty sure you are running with a 1.1-dev version where it fails, because for me it fails on master and works on 1.0.2.

And in any case, the plugin should require ^1.0 not 1.0.0.

**Comment by ppaulis** [comment]
@Seldaek @stof Thanks for helping us out on this one!

I think I know what happened here. Continuousphp runs a daily self-update of composer, and I thought, because of this, we should logically be on 1.0.2. But it seems, that a self-update on 1.0-dev first updates to 1.1-dev, and only in a second self-update to the stable version.
So it seems that the base composer binary in our images simply was too old. We replaced it, and now we are on 1.0.2, as it should be.

Here's what I tried to reproduce:

```
ubuntu@ip-10-0-21-241:~$ /usr/local/bin/composer -V
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "/usr/local/bin/composer self-update" to get the latest version.
Composer version 1.0-dev (4c0e163977f8289288df7b37e0fd0469d3e8cbc6) 2016-02-20 19:28:03
ubuntu@ip-10-0-21-241:~$ sudo /usr/local/bin/composer self-update
Updating to version 6146f7aded4af85022b4d04e53143ee6bca6b456.
    Downloading: 100%         
Use composer self-update --rollback to return to version 4c0e163977f8289288df7b37e0fd0469d3e8cbc6
ubuntu@ip-10-0-21-241:~$ /usr/local/bin/composer -V
Composer version 1.1-dev (6146f7aded4af85022b4d04e53143ee6bca6b456) 2016-04-28 21:38:38
ubuntu@ip-10-0-21-241:~$ sudo /usr/local/bin/composer self-update
Updating to version 1.0.2 (stable channel).
    Downloading: 100%         
Use composer self-update --rollback to return to version 6146f7aded4af85022b4d04e53143ee6bca6b456```

Thanks!
Pascal

**Comment by stof** [comment]
@ppaulis a self-update done from a very old version of composer will always update in snapshot mode (as this was the only mode at that time). the issue is that the pre-installed version of composer is too old to know about update channels

**Comment by Seldaek** [comment]
@ppaulis np, but as I mentioned above, make sure the plugin require is fixed because otherwise it'll break once I tag 1.1.0 (which has a plugin-api 1.1.0) :) That's why we have snapshot builds, so you can see breakage in advance and fix things.

**Comment by shochdoerfer** [comment]
@Seldaek I know, I know. Waiting for Sculpin to release an update ;)
