### ISSUE TITLE
Only show "outdated" by default

### ISSUE THREAD

**Issue by mbrodala** [composer/composer#5253]
I think the new `outdated` command should only list outdated packages by default (that's what its name implies anyways.) Having to run a command like `composer outdated --outdated` feels awkward.

If only outdated packages where the default and one really wants to see the versions of all packages instead, he can be directed to `composer show --latest`.

What do you think?

**Comment by Seldaek** [comment]
I guess we could default outdated to --outdated, and add a --all to it to reverse that.

**Comment by mbrodala** [comment]
@Seldaek Funny how I dropped the `--all` part from my description only for you to come to the same conclusion. ;-)

**Comment by stof** [comment]
@Seldaek I don't even think we need the ``--all`` option, as other packages are not outdated.
We could simply mention ``composer show --latest`` in the help text of ``outdated`` for people wanting to show the latest version of all packages.

**Comment by Seldaek** [comment]
I don't think it hurts to add that flag to remove the --outdated. It's 
easier to explain than "call this other command". If you don't see how 
things are implemented it doesn't really make sense.

**Comment by wmather** [comment]
As a Windows user, out-of-the-box I can't see ANSI colours, so showing all the packages gives me no indication of what is outdated or not. Defaulting to `--outdated` solves this.

**Comment by Seldaek** [comment]
Fixed in https://github.com/composer/composer/commit/fd5f90989fe03bb6aecceb72000c2bfef8ecc34d - @wmather regardless of this fix, I would advise you to fix that color situation, as having colors is really much nicer in git and others as well :)
