### ISSUE TITLE
The new static loader prevents commits to WordPress SVN

### ISSUE THREAD

**Issue by daigo75** [composer/composer#5255]
WordPress repository has a pre-commit hook that parses the entire code base and reject a commit when they detect the static concatenation code introduce by the new static autoloader. The fact that such code may not even be loaded in PHP 5.5 and earlier is irrelevant, the parser considers the code invalid and any commit containing it is rejected.
For reference, see [Syntax error while updating SVN repository](https://wordpress.org/support/topic/syntax-error-while-updating-svn-repository).

This means that any plugin that should be published or updated in the WordPress repository will be rejected if it contains the static concatenation code. The only workaround found so far is to use an older version of Composer, but this is sub-optimal, as it doesn't allow to take advantage of the newer features.

It would be useful to have the possibility to exclude the *autoload_static.php* entirely, as such file cannot be committed to the SVN repository. Another solution would be to remove the pre-parsing of the committed code, but that won't be possible, as it's how the WordPress repository is configured.

**Comment by Seldaek** [comment]
As I wrote in the commit, I don't think this is really something we have to solve. First of all because it's an external tool flipping on our code, not our code doing anything bad per se. Secondly because we recommend against committing the vendor dir in the first place, so the use case is not even something we'd rather support. If you do this you are on your own IMO, and fixing it in the commit hook sounds easy enough so it doesn't really warrant a new option.

**Comment by stof** [comment]
> The only workaround found so far is to use an older version of Composer, but this is sub-optimal, as it doesn't allow to take advantage of the newer features

The workaround is to use the current stable version of composer instead of using the dev snapshot. It is not that bad.

**Comment by daigo75** [comment]
@Seldaek actually, committing the vendor folder is necessary, if you want to publish a plugin or a theme. If you have ever used WordPress, you will know that installing plugins is a "click and activate" operation. The software is supposed to work straight away, and it should come with all its dependencies packaged and ready for use. Assuming that anyone who downloads a software based on Composer has to run *composer install* or *composer update* is definitely wrong, as that's not going to happen. Most likely, Composer is not even going to be installed in the target system, and the software users would not even know what it is.

As for the commit hooks, they are not up to me to fix. They are set by the repository Admins, who are set to leave them as they are. No matter how easy it would be to address them, I don't see them going away at any time soon.

**Comment by daigo75** [comment]
@stof yes, that would work for the moment.

**Comment by stof** [comment]
> As for the commit hooks, they are not up to me to fix. They are set by the repository Admins, who are set to leave them as they are. No matter how easy it would be to address them, I don't see them going away at any time soon.

Well, the discussion should happen in the Wordpress issue tracker to try to change that

**Comment by daigo75** [comment]
@stof yes, that's where it started, and where I intend to continue it. Their system is already obsolete enough (no support for Git whatsoever), and their requirements often tend to be too strict (they recommend to support PHP 5.2, which is beyond obsolete).
