### ISSUE TITLE
Add a bind mount strategy to the path downloader.

### ISSUE THREAD

**Issue by sbuzonas** [composer/composer#5256]
Path repositories are very helpful when working on multiple projects in tandem and provide a faster feedback loop than commit -> push -> composer update.

The primary success of this shorter feedback loop comes from the symlink strategy. When working with docker containers and other virtualization scenarios that cannot or will not traverse symlinks on the host the advantage is lost.

Bind mounts, or possibly mounts in general, can be a sufficient alternative for these scenarios when possible.

**Comment by Seldaek** [comment]
Closing as no progress here and I don't really see the use case.
