### ISSUE TITLE
Deprecate version formats

### ISSUE THREAD

**Issue by Soullivaneuh** [composer/composer#5257]
New formats and standards came on composer like ` || ` for example.

I think we should deprecated the old and not-standard notations and make them strict on next major.

Some formats that should be deprecated:

* `||` (without spaces between versions)
* `|`
* `-` (without spaces between versions)

Maybe I made some mistakes about formats or missing some. Feel free to comment, I'll update this post.

What do you think?

**Comment by Seldaek** [comment]
We can not do this. Old composer.json files in old tags can't be fixed, so we can't just stop supporting version constraints.

**Comment by Soullivaneuh** [comment]
Oh, indeed! Didn't think about that, thanks.

**Comment by Soullivaneuh** [comment]
Another suggestion: We can't remove them, but we can write warning messages while parsing `composer.json` of root project or only on `composer validate` command.

Message as warning or recommendation to encourage people to change it.

This would not affect tagged release of dependencies because only root project file will be validated.

**Comment by Seldaek** [comment]
Yeah but what's the point though? This doesn't achieve much IMO it's just
more work for me reviewing a PR and more work for every user being annoyed
by warnings until they fix their requirements. Open source isn't just about
doing things for the sake of doing things. If there is no point to them
it's just noise and time wasted :)

**Comment by Soullivaneuh** [comment]
The point to them is to permit developer to take care of standards et have consistency on projects.

But I understand that could be going annoying for some people.

Why not only on `composer validate` so? We could also think about a CLI option deactivated by default on this command.

**Comment by Soullivaneuh** [comment]
> Why not only on composer validate so? We could also think about a CLI option deactivated by default on this command.

If someone is interested about that, I wrote a plugin that extends the `composer validate` command:

https://github.com/Soullivaneuh/composer-lint

Any feedback is appreciated! :+1:
