### ISSUE TITLE
Including files from a submodule in my package

### ISSUE THREAD

**Issue by robertkern** [composer/composer#5258]
I understand that git submodules are specifically not supported by composer. I am struggling to figure out a way to handle my situation:

A repo exists that contains a bunch of `yaml` files - it doesn't contain any actual code and doesn't have a `composer.json` etc. The purpose of this repo is to define a bunch of data and configs that can be used by any coding language.

My library has the previous repo as a submodule and loads the `yaml` files, then processes them to do what it needs to do (i can provide links to the actual repos if it helps).

When my library is installed via composer, the submodule repo obviously doesn't get included. I have tried including the following in my library `composer.json`, but the scripts don't run and I suspect the scripts feature isn't designed for this?

```json
{
    "scripts": {
        "post-package-install": [
            "git clone https://github.com/username/repo-name.git",
            "cd repo-name && git reset --hard abc123"
        ],
        "post-package-update": [
            "cd repo-name && git reset --hard abc123"
        ]
    }
}
```

Another option I thought might be usable is defining a custom repository package, but that would result in the contents of the submodule ending up in the `vendor` dir rather than within my package, and as it's just a bunch of `yaml` files, there's no autoloading support etc. Is there anything I can do to make that work?

The end result I would like is to have the contents of the submodule included somehow in my package when it's installed via composer. Is there any way to do this?

Thanks!

**Comment by Seldaek** [comment]
No this isn't really possible at the moment, except by declaring the package as a custom repository or declaring the scripts in the root package. Those two things are root-only so if you declare them in the package that you install as a dependency it won't get executed.

If you define a package repo though https://getcomposer.org/doc/05-repositories.md#package-2 you can just check from your other dep that `__DIR__.'/../../name/of-package-repo/'` exists and look for the yaml there. It's not great but might be an ok workaround if it's a private project.

**Comment by robertkern** [comment]
Thanks for clarifying that @Seldaek - your suggestion is probably the best way to go about it for now.

Thanks!
