### ISSUE TITLE
Composer scripts not longer running

### ISSUE THREAD

**Issue by ryanbowden** [composer/composer#5261]
I have the following in my composer file
`"scripts": {
    "post-install-cmd": [
        "cp -rf sourcefiles/. source/.",
        "rm -rf sourcefiles"
    ]
}`

When i run it, it does the work it correctly on version: 2016-02-24_11-44-07-45f6b37
But on the latest version, this no longer runs / works

I do not get any error messages when it runs it does not run the code i have also tried the following:
`"scripts": {
    "post-install-cmd": [
        "cp -rf sourcefiles/. source/.",
        "rm -rf sourcefiles"
    ]
}`

But this only works in version: 2016-02-24_11-44-07-45f6b37 or later. but none of the newer ones. 

Have i made a mistake or is their a bug?

**Comment by stof** [comment]
Running ``composer install`` without a lock file was previously running a ``composer update`` internally except for the composer script being run. This has been changed before reaching the 1.0 stable release to really run an update fully, i.e. running ``post-update-cmd`` in this case.

If you want your scripts to be run anytime, it should run on both post-install-cmd and post-update-cmd (you can use a custom script holding these commands and then referencing it on sections using ``@...`` if you want to avoid duplication)

**Comment by ryanbowden** [comment]
Thank you, you solved my issue.
