### ISSUE TITLE
Document CommandProvider capability

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#5262]
See https://github.com/composer/composer/tree/master/tests/Composer/Test/Plugin/Fixtures/plugin-v8/Installer for an example.

**Comment by nevvermind** [comment]
Should we add a new section in https://getcomposer.org/doc/articles/plugins.md#creating-a-plugin to document the Plugin Capability feature itself, then document each capability in that same page or each on its own page?

**Comment by bamarni** [comment]
I suggest to keep it on the same page as there is only one capability at the moment, and to provide a simple example for it.

@nevvermind : I can give it a shot if you're not already working on it.
