### ISSUE TITLE
 No version of Composer available for your PHP version

### ISSUE THREAD

**Issue by Nextt1** [composer/composer#5263]
When I run this command:

curl -sS https://getcomposer.org/installer | php

I get this output:

`PHP Warning:  file_get_contents(https://getcomposer.org/versions): failed to ope  n stream: Connection timed out in - on line 688
PHP Warning:  Invalid argument supplied for foreach() in - on line 471
PHP Fatal error:  Uncaught RuntimeException: There is no version of Composer available for your PHP version (7.0.5-4+donate.sury.org~trusty+1) in -:480
Stack trace:
#0 -(55): installComposer(false, '/usr/local/bin', 'composer', false, false, fal  se, 'stable')
#1 -(13): process(Array)
#2 {main}
  thrown in - on line 480And I expected this to happen:`

So how should I install composer on my system? I am using Ubuntu 14.04.

**Comment by stof** [comment]
Well, the error starts with ``PHP Warning: file_get_contents(https://getcomposer.org/versions): failed to ope n stream: Connection timed out in - on line 688``. So it looks like it cannot perform the network request.

@Seldaek looks like the installer is missing some error handling

**Comment by Seldaek** [comment]
Yeah we should probably fail earlier when one of the requests fails. It won't change the outcome though, but might make the output a bit clearer.

**Comment by Nextt1** [comment]
So is there any way I can install composer?

**Comment by Nextt1** [comment]
I am getting this output. 

All settings correct for using Composer
Downloading 1.0.3...
Download failed: file_get_contents(https://getcomposer.org/download/1.0.3/composer.phar): failed to open stream: Connection timed out
Downloading 1.0.3...
Download failed: file_get_contents(https://getcomposer.org/download/1.0.3/composer.phar): failed to open stream: Connection timed out
Downloading 1.0.3...
Download failed: file_get_contents(https://getcomposer.org/download/1.0.3/composer.phar.sig): failed to open stream: Connection timed out
The download failed repeatedly, aborting.


@Seldaek @stof  So is there any way I can install composer?

**Comment by johnstevenson** [comment]
This will be addressed in the sequence of installer updates that I am currently PR-ing.

**Comment by Seldaek** [comment]
OK closing then as it'll be fixed eventually but I feel we are likely to forget this and leave it open for nothing otherwise.
