### ISSUE TITLE
Composer cannot resolve 2.2.8-devphp7 version

### ISSUE THREAD

**Issue by malkusch** [composer/composer#5264]
With the following composer.json:

```json
{
    "require-dev": {
        "ext-redis": "^2.2.4",
    }
}
```

Composer (6146f7aded4af85022b4d04e53143ee6bca6b456) [thinks the installed extension doesn't match](https://travis-ci.org/bandwidth-throttle/token-bucket/jobs/126589714#L188):
> The requested PHP extension ext-redis ^2.2.4 has the wrong version (2.2.8-devphp7) installed. Install or enable PHP's redis extension.

I then even tried to explicitly require that `2.2.8-devphp7` version with

```json
{
    "require-dev": {
        "ext-redis": "2.2.8-devphp7",
    }
}
```
And now [composer cannot parse that version](https://travis-ci.org/bandwidth-throttle/token-bucket/jobs/126593686#L174):
> [UnexpectedValueException]
>  Could not parse version constraint 2.2.8-devphp7: Invalid version string "2.2.8-devphp7"

**Comment by stof** [comment]
Well, ``2.2.8-devphp7`` is not a supported version number. So just require ``*`` for now, until ext-redis exposes a supported version number.

**Comment by malkusch** [comment]
So you suggest I just file that bug at the redis extension, to fix their version number? What exactly is broken with their version number? I understand that this is even a valid semver version. Could please elaborate a little bit on this?

**Comment by kamilsk** [comment]
@malkusch where you found this version?

https://pecl.php.net/package/redis
https://github.com/phpredis/phpredis/releases

Could you provide `php --ri redis`?

Supported versions by composer are presented here https://getcomposer.org/doc/articles/versions.md

**Comment by alcohol** [comment]
@malkusch except for historical reasons, Composer doesn't allow semver specifically.

```
    /**
     * Regex to match pre-release data (sort of).
     *
     * Due to backwards compatibility:
     *   - Instead of enforcing hyphen; an underscore, dot or nothing at all are also accepted.
     *   - Only stabilities as recognized by Composer are allowed to precede a numerical identifier.
     *   - Numerical-only pre-release identifiers are not supported, see tests.
     *
     *                        |--------------|
     * [major].[minor].[patch] -[pre-release] +[build-metadata]
     *
     * @var string
     */
```

So `2.2.8-dev7` would be ok, but `2.2.8-devphp7` is not because `devphp` is not a supported stability.

**Comment by alcohol** [comment]
Can you give us the output of `composer show -m` ?

**Comment by malkusch** [comment]
>  but 2.2.8-devphp7 is not because devphp is not a supported stability.

So this `devphp` has a special meaning in Composer land. Ok, I can understand not supporting that in the composer.json file, but in my case (which is PHP-7 plus ext-redis on travis) I think it's very confusing that the installed version `2.2.8-devphp7` cannot be compared against my `^2.2.4` constraint.

How about not giving `devphp` a special meaning on the side of the installed extensions?

`composer show -p`
> [ext-redis           0](https://travis-ci.org/bandwidth-throttle/token-bucket/jobs/126665194#L219)

**Comment by alcohol** [comment]
We don't give it a special meaning. We simply cannot parse it. This means that the installed version ends up being unrecognized, and thus it defaults to `0`. As `0` does not match a constraint of `^2.2.4`, the requirement is considered unmet.

**Comment by malkusch** [comment]
> We simply cannot parse it

How about changing that? Would you accept a PR which would be able to compare `2.2.8-devphp7` against a `^2.2.4` constraint?

**Comment by alcohol** [comment]
Personally I'm ok with that, but when I first suggested to @Seldaek to support semver more according to their specification, he seemed a bit reluctant. So you'll have to convince him :-)

See [composer/semver](/composer/semver) repo for details.

**Comment by malkusch** [comment]
I guess you refer to composer/semver#15, right?

**Comment by alcohol** [comment]
To some extend, this was discussed there, yes.

**Comment by Seldaek** [comment]
One possibility to improve this (since it seems impossible to get pecl devs to clean up their act) would be to add a fallback for extension versions if they don't parse we could just keep the digits `^\d+(\.\d+)*` (and maybe the stability) and remove whatever follows so that it's parseable. It'd be best-effort and would result in 2.2.8 or 2.2.8-dev which is better than 0 I suppose.

**Comment by Seldaek** [comment]
Just pushed a fix that should make 2.2.8-devphp7 parse as 2.2.8

**Comment by malkusch** [comment]
Thank you.

**Comment by Hast** [comment]
Thank you!
