### ISSUE TITLE
Unable to require redis extension

### ISSUE THREAD

**Issue by Hast** [composer/composer#5265]
I'm trying to set phpredis extension as a requirement for my application. What I 've got in my composer.json:

`"ext-redis": ">=2.2.7"`

A've also tried these options: "^2.2.7", "2.2.7@dev" and even "2.2.8-devphp7".

But all the time I'm getting the error below:

>  Problem 1
>     - The requested PHP extension ext-redis >=2.2.7 has the wrong version (2.2.8-devphp7) installed. Install or enable PHP's redis extension.

Also see: http://stackoverflow.com/questions/36794463/composer-requrie-ext-redis

**Comment by malkusch** [comment]
You just duplicated me: #5264
