### ISSUE TITLE
Content-Length check fails due to redirect

### ISSUE THREAD

**Issue by nkovacs** [composer/composer#5268]
With the following composer.json:

```json
{
    "repositories": [
        {
            "type": "composer",
            "url": "https://languages.koodimonni.fi/packages.json"
        }
    ],
    "require": {
        "koodimonni-language/fi": "*",
        "koodimonni-language/fr_FR": "*"
    },
    "extra": {
        "dropin-paths": {
            "htdocs/wp-content/languages/": ["vendor:koodimonni-language"],
            "htdocs/wp-content/languages/plugins/": ["vendor:koodimonni-plugin-language"],
            "htdocs/wp-content/languages/themes/": ["vendor:koodimonni-theme-language"]
        }
    }
}
```

When I run this command:

```
composer update -vvv (please include -vvv!)
```

I get this output:

```
  [Composer\Downloader\TransportException]  
  Content-Length mismatch        
```

And I expected this to happen:

Successfully install the packages.

It looks like the Content-Length check compares the Content-Length of the first response (which returns a 301 and Content-Length 178) to the length of the response that is returned by the redirect target (https://wp-languages.github.io/packages.json, Content-Length 129), and it fails.

**Comment by Seldaek** [comment]
Thanks for the good analysis and report, I can confirm it fails, I'll try and fix shortly.

**Comment by Seldaek** [comment]
Fixed in snapshot build, I'll try to release a 1.0.3 soon.

**Comment by Seldaek** [comment]
Oh also.. you should use ` "url": "https://languages.koodimonni.fi/"`, the packages.json is not part of the repository url.

**Comment by nkovacs** [comment]
Thanks!
I accidentally copied the wrong url when I created a simplified testcase for the bug, we were using `https://languages.koodimonni.fi/` in the composer.json of the real project.
