### ISSUE TITLE
Is composer able to generate autoloading files which are compatible with required PHP version?

### ISSUE THREAD

**Issue by k00ni** [composer/composer#5269]
I am currently struggling with the following WordPress problem ([link](https://wordpress.org/support/topic/syntax-error-while-updating-svn-repository?replies=8#post-8345051)), which is not your concern, but describes the problem.

The topic is, that composer in the latest version generates autoloading files which require PHP 5.6+ to be interpreted, especially **vendor/composer/autoloading_static.php**. It uses concatenation to build file paths inside public static properties of a static class. Sure, it will only be loaded if the system runs with PHP 5.6, but there may other mechanisms like pre-commit hooks in Git which interfere.

This feature is not available in PHP 5.3, unfortunately. So it raises the question, if it makes sense or is even possible already, to tell composer to generate autoload files based on the required PHP version. For instance, i require PHP in version >5.3, so only compatible code to that version will be generated.

What are your opinions?

**Comment by Seldaek** [comment]
Please see https://github.com/composer/composer/issues/5255 :)
