### ISSUE TITLE
Cache directory should be analysed before install from cache

### ISSUE THREAD

**Issue by phroggyy** [composer/composer#5270]
Last night, my computer was running low on disk space. As a result, OS X started automatically clearing out cache files. Thing is, directories aren't automatically cleared, but only files. This led Composer to believe that I had, in that case, the Laravel framework in my cache, but in reality, it was a completely empty directory, which led the `classmap` to fail since it couldn't find the class it was supposed to. I propose that before installing a repo from cache, there should somehow be a pre-check against the `composer.json` of the package (or at the very least checking that there exists a `composer.json`) to ensure that we don't install an incomplete package from cache.

**Comment by alcohol** [comment]
I doubt that, since Composer doesn't use system `tmp` directories for cache. Instead it uses a directory in your home directory. Most likely something else went wrong, but since you have nothing for us to reproduce, we will never know what that was :-)
