### ISSUE TITLE
Composer 1.1.0-RC new optimised autoloader causing problems for users of php5.5 or below

### ISSUE THREAD

**Issue by paladox** [composer/composer#5273]
Hi updating to composer 1.1.0-RC is causing problems for users of php 5.5 or below.

Because you include a new optimised feature for autoloader it is causing problems in php 5.5 if you doint have php5.6

Please could this

•Optimized the autoloader initialization using static loading on PHP 5.6 and above, this reduces the load time for large classmaps to almost nothing

Being only used in php 5.6 and above, please include a check to make sure your using php 5.6 or else fallback to classmaps please.

Errors out here https://integration.wikimedia.org/ci/job/php55lint/10632/console

10:08:07 php5 -l vendor/composer/autoload_static.php 
10:08:07 PHP Parse error:  syntax error, unexpected '.', expecting ')' in vendor/composer/autoload_static.php on line 10
10:08:07 Errors parsing vendor/composer/autoload_static.php
10:08:07 xargs: php5: exited with status 255; aborting
10:08:07 Build step 'Execute shell' marked build as failure

https://gerrit.wikimedia.org/r/#/c/286298/1/vendor/composer/autoload_static.php

Please could this be fixed.

**Comment by paladox** [comment]
Maybe include backward compat support so it will generate both files and php 5.6 or higher will use the static one and php 5.5 or below will use class maps please.

**Comment by paladox** [comment]
It seems to do

PHP_VERSION_ID >= 50600

Which looks like php 5.0.6

**Comment by paladox** [comment]
Looking at https://github.com/composer/composer/commit/fd2f51cea8e5f1ef978cd8f90b87b69dc1778976

It uses either the optimised autoloader or the autoload files php file.

We should generate both and then add a check to detect your current php to load the optimised autoloader or the other one. That way we stay backword compat with other php please.

**Comment by xabbuh** [comment]
This is already ensured by https://github.com/composer/composer/commit/fd2f51cea8e5f1ef978cd8f90b87b69dc1778976#diff-33037407f7f293f37df2258567b56598R583, isn't it?

**Comment by paladox** [comment]
Oh, could the file somehow ignore linting for the static composer file please.

**Comment by xabbuh** [comment]
Looks like you need to configure the linter call to do so, but that's nothing Composer can do for you.

**Comment by alcohol** [comment]
This is not a Composer issue, sorry.
