### ISSUE TITLE
Do not show abandonned package on composer show by default

### ISSUE THREAD

**Issue by Soullivaneuh** [composer/composer#5274]
The idea is to only show not abandoned packages on `composer show --all` command. And add a `abandoned` option to force it.

Another idea would be to mark abandoned packages on the result list.

**Comment by alcohol** [comment]
I'm in favor of marking them, not so keen on the idea of hiding them.

**Comment by Seldaek** [comment]
Yeah I disagree. This should be shown by default as it is really a bad idea to keep using them.

**Comment by alcohol** [comment]
@seldaek wait what?

**Comment by Seldaek** [comment]
Yeah I totally misread this, that's what double negations and too many flags on one command do to people :p

Anyway, I'd rather not have even more flags, and I don't really see the point of marking them either, there isn't a whole lot of point to the --all flag to begin with :)

**Comment by Soullivaneuh** [comment]
@Seldaek In this case what about keep the default behavior and add a `--hide-abandoned` option?

**Comment by Seldaek** [comment]
What's the point though?

**Comment by Soullivaneuh** [comment]
Well, for my case I had to list all sonata-project packages to write a maintenance script.

So I did `composer show --all sonata-project/*` but after that, I had to manually check on website if the package is abandoned or not. It's quite painful.

I think it should be not hard to implement this option and this will change nothing to the default behavior. :+1:

**Comment by Seldaek** [comment]
Well the problem is in the full listing of all, we only have the provider names, no detailed information about each package, so we can't really implement this without adding stuff to packagist API etc.. not really worth it IMO.
