### ISSUE TITLE
Sub-repo dependencies

### ISSUE THREAD

**Issue by mnpenner** [composer/composer#5280]
Project A depends on Project B. Project B depends on Project C. Project C can only be found by looking at the "repositories" in Package B's composer.json. Running `composer install` and `composer update` work perfectly from inside Project B's directory -- it's able to find and install Project C without problems.

However, Project A cannot find Project C because it does not utilize Project B's "repositories". It isn't until you add Project B's repositories to Project A's composer.json that it works.

This seems bad. If Project B is working perfectly, then depending on Project B shouldn't create "no matching package found" errors in Project A.

I'd post an example, but this arises because of dependencies on private repositories which I can't share.

My proposed solution is that when Package A is trying to install Package B and can't find some of Package B's dependencies, then it should search Package B's "repositories" section of its composer.json. It doesn't make sense for Package A to have to know about all of its dependencies' dependencies.

If you need to see some bash, here it is:

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)           
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mycompany/polymig dev-default -> satisfiable by mycompany/polymig[dev-default].
    - mycompany/polymig dev-default requires mycompany/napi-php dev-default -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by stof** [comment]
See https://getcomposer.org/doc/faqs/why-can't-composer-load-repositories-recursively.md for the explanation about why it cannot be done
