### ISSUE TITLE
"official" composer-schema.json ?

### ISSUE THREAD

**Issue by mindplay-dk** [composer/composer#5282]
The [documentation](https://getcomposer.org/doc/04-schema.md#json-schema) currently points to this URL for the JSON-schema:

https://github.com/composer/composer/blob/master/res/composer-schema.json

The `1.1` branch is where development takes place, I think? So most likely, pointing to the `master` branch for the schema file is not a problem in terms of versioning?

The URL doesn't look very "offical" though, and I think that "best practice" is to put schema under the domain name of the schema vendor? e.g. `getcomposer.org/schema.json` or so?

It looks a bit "wrong" to have this lengthy Github URL in every `composer.json` file...

**Comment by Seldaek** [comment]
https://getcomposer.org/schema.json it is then.

**Comment by mindplay-dk** [comment]
Lovely! Thanks for the prompt response! :-)
