### ISSUE TITLE
Problem on semantic versioning within recursive dependencies

### ISSUE THREAD

**Issue by ZhaoVitapublic** [composer/composer#5283]
We got some problem with semantic versioning by loading recursive dependencies, when only one version is available.

We have a project 'main', which need a private library 'my-blabla', and 'my-blabla' references and require an 'base' library called 'base-blabla'.

Project 'main' will load library 'base' with following compose.json:

```
{
       "require": {
             "blabla/my-blabla": "~1.0.0"
        }
}
```

The composer.json of 'my-blabla' looks like following:

```
{
        "require";{
              "blabla/base-blabla": "~1.0.0"
        }
}
```

The problem occurs on the situation:
-         "my-blabla" has 2 version 1.0.0 and 1.0.1
-         "base-blabla" has 1 version 1.0.0

So far, when i run command: 

```
composer install. 
```

I got message like:

```
Your requirements could not be resolved to an installable set of packages.
    - blabla/my-blabla 1.0.0 requires blabla/base-blabla ~1.0.0 -> satisfiable by blabla/base-blabla[1.0.0]. 
    - blabla/my-blabla 1.0.1 requires blabla/base-blabla ~1.0.0 -> satisfiable by blabla/base-blabla[1.0.0].
    - Conclusion: don't install blabla/base-blabla 1.0.0
    - Installation request for blabla/my-blabla ~1.0.0 -> satisfiable by blabla/my-blabla[1.0.0, 1.0.1].
```

But if i have multiple version in 'base-blabla', like:
-         "my-blabla" has 2 version 1.0.0 and 1.0.1
-         "base-blabla" has 2 version 1.0.0 and 1.0.1

composer can install version 1.0.1 from both packages without any problem.

**Comment by stof** [comment]
Can you provide a reproducing test case ?

**Comment by ZhaoVitapublic** [comment]
I'm sorry, that the both package, named 'my-blabla' and 'base-blabla' are private project. 

But the problem is reproducable. And occurs only, when the recursive dependencies has only one version and will be load with semantic versioning.
I can give you the structure of both composer.json
Top level:
```
{
  "name": "my/my-project",
  "repositories": [
    {
      "type": "git",
      "url": "https://github.com/<my>/my-application-module"
    },
    {
      "type": "git",
      "url": "https://github.com/<my>/my-base-module"
    }
  ],
  "require": {
    "my/my-application-module": "~1.0.0"
  }
}
```
Dependency level:
```
{
  "name": "my/my-application-module",
  "repositories": [
    {
      "type": "git",
      "url": "https://github.com/<my>/my-base-module"
    }
  ],
  "require": {
    "my/my-base-module": "~1.0.0"
  }
}
```

Has problem by:
```
my-project   require "my-application-module": "~1.0.0"
      |--------- my-application-module   [1.0.0, 1.0.1]  require "my-base-module": "~1.0.0"       
                                  |------------------ my-base-module [1.0.0]
```
No problem by:
```
my-project   require "my-application-module": "~1.0.0"
      |--------- my-application-module   [1.0.0, 1.0.1]  require "my-base-module": "~1.0.0"       
                                  |------------------ my-base-module [1.0.0, 1.0.1]
```

**Comment by alcohol** [comment]
Repositories are not inherited and a root-only configuration option. Did you include those in your composer.json files to describe your use-case, or are those actually in there for real?

**Comment by alcohol** [comment]
If you could write a test case reproducing your scenario, we could actually look into this. See the `tests/Composer/Test/Fixtures/installer` directory for examples/inspiration.

**Comment by ZhaoVitapublic** [comment]
@alcohol 
Thanks for the hint. 
I write the following test with definition in packages, It's no problem to load the library as expected. 
```
--TEST--
Github issue #5283
--COMPOSER--
{
  "repositories": [
    {
      "type": "package",
        "package": [
            { "name": "a", "version": "1.0.0" },
            { "name": "b", "version": "1.0.0", "require": { "a": "~1.0.0" } },
            { "name": "b", "version": "1.0.1", "require": { "a": "~1.0.0" } }
        ]
    }
  ],
  "require": {
	"b": "~1.0.0"
  }
}
--RUN--
install
--EXPECT--
Installing a (1.0.0)
Installing b (1.0.1)
```

But my real problem is, that the recursive dependencies come via git repositories rather then package. As mentioned befor, the both git repositories 'my-application-module' and 'my-base-module' are defined in 'repositories' configuration in the main composer.json. The output message make me also a bit confused, because 'my-application-module' solve the dependencies of the same package_name+version of 'my-base-module', but the version can not be loaded. (The package 'my-base-module' is well defined and can be solved and loaded, but only if they have more than one version).

Did i miss something or missunderstand some thing?

**Comment by Seldaek** [comment]
Auto-closing as this hasn't been updated in over 6months and is marked as a support request. If there is a real bug to consider please let us know.
