### ISSUE TITLE
Failing to autoload files from directory prefixed with 'vendor_'

### ISSUE THREAD

**Issue by xhook** [composer/composer#5289]
I have a directory where I store 3rd party libraries that have no composer package available. I named this directory `vendor_static` and autoloaded files from there as follows:

```json
{
   	"minimum-stability": "stable",
	"require": {
		"php": ">=5.5.0",
	},
	"autoload": {
		"files": ["vendor_static/underscore.php"]
	}
}
```

Until recent update of composer all worked fine but now it generates invalid ComposerStaticInitXXX class with the following lines:
```php
    public static $files = array (
        'e3e5535f20f35978fa964f3f8b44fd67' => __DIR__ . '/..' . '_static/underscore.php',
    );
```

It trimmed off `vendor` prefix from directory and tries to load a file from a wrong place. If I rename directory to `static_vendor` everything works fine.

I'm running 
- Composer version 1.2-dev (d5ed45c3c7e5a08ee2efd1f3cbb25783ccee133b) 2016-05-05 12:37:01
- PHP 7.0.5

**Comment by Seldaek** [comment]
Strange, I get the correct path:

        'e3e5535f20f35978fa964f3f8b44fd67' => __DIR__ . '/../..' . '/vendor_static/underscore.php',

Are you on linux?

**Comment by Seldaek** [comment]
Yeah I can reproduce it on linux.

**Comment by ktomk** [comment]
I also had an issue installing within a sub-directory called build using `-d=build`  switch, it seems this commit fixed it, too. 

    broken: Composer version 1.2-dev (b8974a3e134dca8534f43b8afc6fa4ffd446b526) 2016-05-05 13:10:14
    good  : Composer version 1.2-dev (9ecaec4cca4118e29274e3303d0829b0819e5b9c) 2016-05-05 13:57:13

I have the build now storing the revisions so that building on travis will reveal it in the logs in the future. We're using composer snapshots for the build.

**Comment by xhook** [comment]
Confirm the bug fixed. Huge thanks!
