### ISSUE TITLE
Regression on Working Directory Switch

### ISSUE THREAD

**Issue by ktomk** [composer/composer#5290]
I'm using composer snapshots in a build script on Travis and I noticed that the working directory switch (`-d=build` in my case) stopped working. 

Testing the build script against a source version revealed that 92207da83ad1fac1b43e710cf6cd519d16b54f36 introduced the issue. Build works fine on the previous commit d07b4e0f3ecf16cd86584eb86792d0d7ac0d8e12.

The picture I get is that composer uses the vendor directory from the working directory (`.`) as well as the composer.lock but uses the composer.json from directory in the switch (`build`).

It's a bit weird but I think worth to report first of all.

The command I use in the build script is:

    ./composer.phar -d=build install --no-interaction

**Comment by Seldaek** [comment]
Hmm yeah -d needs to be processed before we load the plugins I guess.. I think that one can always be done first thing no matter the command, I'll work on a fix later.

**Comment by ktomk** [comment]
@Seldaek: Looks good! Builds are green again, temporary workaround has been removed. Future builds will show the version of composer snapshot used to easier tackle similar issues. Just FYI.
