### ISSUE TITLE
Composer config file versioning

### ISSUE THREAD

**Issue by sagikazarmark** [composer/composer#5296]
Everytime a new feature lands in composer, there is a waiting period until everyone updates composer to the new version (eg. carret, reusing scripts, etc). Probably the biggest problem with this is that people report "bugs" which after various amount of time ends up in "update composer".

By introducing config schema versioning, composer could tell if it is compatible with that version of the config or not and tell the user to update. Of course it is the maintainer responsibility to set the correct version in the config.

WDYT?

**Comment by alcohol** [comment]
I don't see any merit here. The config schema changes rarely. Also, the problem you described would not be solved by config versioning. In the end, users will have to update their Composer binary anyway.

**Comment by sagikazarmark** [comment]
> In the end, users will have to update their Composer binary anyway.

True, but the solution would be quite obvious, while right now we get strange errors which does not help solving the issue. Older versions of composer definitely cannot decide what the problem is, since they are old, don't support a feature. While manual versioning in the file would provide:

- proven compatibility with a given version
- helpful error message

**Comment by alcohol** [comment]
I think this would require far too much effort for virtually no gain. The amount of issues that arise from config changes are insignificant. Most issues are also very easy to solve.

We don't even offer documentation yet for each individual release channel (stable, preview, snapshot). That, in my opinion, is more important.

**Comment by sagikazarmark** [comment]
Ok, thanks for the response and the explanation.
