### ISSUE TITLE
Do not install me

### ISSUE THREAD

**Issue by Slamdunk** [composer/composer#5299]
Only few people on the Earth don't now yet the bless of Composer for our community.

What many people don't know are the consiquences of the very tiny word `"require"`.

The facts:

1. A lot of medium and small projects are not regularly maintained (understandable)
2. They group a lot of functionalities of the same topic
3. They need different dependancies for different functionalities, or different PHP versions
4. They write `"require"` like there is no tomorrow, instead of the `"suggest"` key
5. But you need only one of those functionalities

Our business app needs 10 packages, we ended up with 100 packages, and 80 of them are unused.

This drives me crazy: we have ~65 MB of useless code and they may only hurt.

Morover, the semvar is easily a nightmare to update:

1. You require A (~2), B
2. B requires C
3. C requires A (~1)

And you go nowhere until all the packages are updated, but you only need some part of B and not C.

What I wish from Santa this year is something that allows me to explicitly skip some packages.
Every time the DependencyResolver finds the package to skip in a composer.json of another package, it should behave like it doesn't exist.

How?

1. Maybe a `"skip"` key in the schema, and it's only read in the current composer.json, but not in the dependancy one (root-only)
2. Maybe a `--ask-what-to-install` option while producing a new composer.lock, and the composer.lock is signed as always out-of-sync
3. I don't know

For sure this will need a huge disclaimer in the doc and during usage for the developer that may lead to unexpected behaviours, but if you have written a decent testsuite, everything will be OK.
I tried to manually delete those previously mentioned ~65 MB from the ./vendor/, and my 95% code-coveraged SUT told me they where useless.

Before writing any PR, I would like to hear your thoughts, as I have no experience nor knowledge of any other dependancy manager.

**Comment by alcohol** [comment]
The implications this has is not worth the gain (which is virtually non-existant) it provides. 

Unused files
- do not consume memory.
- do not use cpu cycles,
- cost only a little bit of disk space (which is completely insignificant).

None of the above impacts your application performance in any significant way.

**Comment by Slamdunk** [comment]
Those downwards are insignificant. What bother me is the possibility that some external input might create an unexpected situation that uses the unused code and it's not covered by the testsuite.

A fatal error for a missing class is a light-year safer than an untested behaviour.

**Comment by alcohol** [comment]
Your scenario requires some very "creative" programming. I think some unused classes/files in your vendor directory would be the least of your worries in that case.

In any case, this is something that could be solved in your packaging process. Composer is a dependency manager, not a deployment tool. You're trying to solve the problem at the wrong end of your development pipeline.

**Comment by Slamdunk** [comment]
You understimate the power and complexity of external input: we run a business that interacts with more than 50 banks, each with a multitude of input data, changing month by month to follow national regulations in the structure, the format and the behaviour. Almost 80% of the times the changes are hidden, the consequences unforeseeable, and we spend the majority of the time adding testcases and tests.

> You're trying to solve the problem at the wrong end of your development pipeline.

If not during development, where do we have to remove and tests dependancies?

**Comment by alcohol** [comment]
You don't test dependencies, they should be tested by their author.
You can remove any redundant code/files during packaging, which should be one of the final steps in your continuous integration pipeline.

Roughly:

dev -> commit -> push -> test (ci job) -> package (ci job) -> deploy (ci job)

**Comment by Slamdunk** [comment]
> You don't test dependencies, they should be tested by their author.

I meant test the SUT againt dependancies.

>  You can remove any redundant code/files during packaging, which should be one of the final steps in your continuous integration pipeline.

This sounds totally wrong to me. Tests must be done against the exact version of the app that is in production, what is the point of testing something different? If in production a file must not be present, either in the development it must not be present.

**Comment by alcohol** [comment]
> I meant test the SUT againt (sic) dependancies.

What does that even mean?

> This sounds totally wrong to me.

That's ok, the world isn't coming to an end just yet. Just switch the order of the two jobs in that case. You are capable of thinking and making decisions for yourself I assume. I'm merely offering feedback, not telling you what to do.


Either way, what you are proposing has no place in Composer.

**Comment by Slamdunk** [comment]
It seems that my way of expressing may sounds like dull complaining. That was not my intention, if it was perceived like that I apologize.

Of course "testing dependancies" and "testing against dependancies" do not make any sense speaking in theory: I was referring that if something makes the testsuite results invariant, that thing may be removed, either a LOC or a dependancy, and in this context it was just an evidence that exist packages with a `"require"` key that are not a real requirement.

I would be glad to read something that spurs to create structural and/or behavioural differencies between development and production environment: I thank you in advance if you could provide me this last feedback.

Best regards, and again thank you for this amazing project

**Comment by alcohol** [comment]
Honestly, I just think you are looking for issues where there are none.

There is no way that a library that is never used might suddenly get used just cause of random user input. At least not in any program that is written in a common sensible manner (and this is something you could catch with proper testing also). You'd had to have automagic wiring stuff up the whazoo for things to explode that drastically. And at that point I'd just tell you to stop and think for a moment about what you are doing :p

Removing files just because you feel like they shouldn't be there is even more of a time-waster than premature optimizations. That's just my 2 cents. It's unlikely you will find much (if any) reading material on the subject.
