### ISSUE TITLE
usability: y,n,v,d,s what do those shortcuts mean?

### ISSUE THREAD

**Issue by staabm** [composer/composer#5302]
I just run a `composer update` on a old local project and got some error because of locally modified files.

I get dialogs like
```
-10 more files modified, choose "v" to view the full list
    Discard changes [y,n,v,d,s,?]?
```
would be great the explanations which get printed after I you type `?` would already be visible in the initial view.

**Comment by Seldaek** [comment]
IMO it'd be extra noisy for nothing, it's like printing the help every time you run a composer command just in case you forgot stuff? We have the ? option in there already which is fine I think.

**Comment by staabm** [comment]
then maybe we should make the "?" more prominent so one knows that "?" will give further information?

**Comment by Seldaek** [comment]
Isn't `?` quite an obvious sign for "help I'm confused?". I'm sorry if you had a confusing moment but I don't really believe we can prevent every single mishap. If we change it to something else someone else will find it confusing..

**Comment by hkdobrev** [comment]
Just to note this is very similar to what Git does with `git add --patch` and some other interactive commands for code hunks and probably is derived from Git. +1 for keeping it as it is.

**Comment by patrik7** [comment]
+1 all I want to do is have composer override anything I have, and it's not obvious to me which one of y,n,v,d,s does that.

Override changes? Override remote with mine, or mine with remote? I have no idea ..

**Comment by eduardomart** [comment]
I don't see an actual answer, yet this was closed. I have no idea where to find what the letters mean...

**Comment by xabbuh** [comment]
@eduardomart You can still type `?` to get an explanation of what these options mean (IIRC there are other command-line tools that behave the same).
