### ISSUE TITLE
Require IPv6 Support

### ISSUE THREAD

**Issue by Fleshgrinder** [composer/composer#5304]
PHP can be built with the `--disable-ipv6` option and there is no way to ensure that a package that requires IPv6 support forces an installer to actually having it enabled (or rather not disabled). The only way one could perform this validation would be at runtime:

```php
if (defined('AF_INET6') === false) {
    // Houston, we have a problem.
}
```

It would be nice to have the ability to specify this requirement in a libraries `composer.json` file and have composer validate it before the package is being installed. Maybe something along the lines:

```json
{
    "require": {
        "ext-network-ipv6": "*"
    }
}
```

Note that `ext-network` is always enabled in PHP, it is only possible to disable IPv6 support individually.

**Comment by alcohol** [comment]
Probably quite easy to implement by adding a few lines to the platform repository code.

**Comment by dzuelke** [comment]
Like I commented on the PR...

IMO this should be called php-ipv6 and not ext-network-ipv6, in line with php-64bit.

Future "core build" properties, such as debug or ZTS yes/no, could follow the same naming scheme.

**Comment by alcohol** [comment]
Is ipv6 support really part of the interpreter?

**Comment by Fleshgrinder** [comment]
Yes, it is, that is also why I initially created it as an extension to the `php` (`php-64bit` respectively). I only changed it because of your comment on the PR.

**Comment by dzuelke** [comment]
It is not an extension. Really should not be called `ext-$whatever`. I talked to @Seldaek via IM and seemed to agree. If someone wants to be quicker than me with a PR... :)

**Comment by Fleshgrinder** [comment]
Back to my original PR then. :smirk_cat:
