### ISSUE TITLE
Could some Composer commands be rewritten as plugins?

### ISSUE THREAD

**Issue by hkdobrev** [composer/composer#5306]
Since Composer 1.1.0 plugins can now register their own Composer commands. Is it possible some Composer commands to be rewritten as plugins which are distributed as part of Composer?

This have a few benefits:

- We would have nice, supported, official examples of how to write a plugin.
- The plugin API would grow and mature.
- A bit more modularity in Composer commands.
- An opportunity to rework some of the messy practices around some commands.

I'm sorry for asking this unprepared. I'm not familiar with Composer plugin API, but just wanted to start a discussion about that.

**Comment by slbmeh** [comment]
I was always a fan of vagrant doing just that.  When a library is extensible and ships it's own extensions as the core, it helps identify some of the issues in extension development that may have been only troublesome to third parties.

**Comment by alcohol** [comment]
That problem I see with this is that a lot of the commands contain custom code that is not yet represented anywhere else in the Composer "framework". Some commands even share pieces of code. So all of this would have to be tidied up too. This means the changes will be quite significant, and therefor difficult to review. Maybe a cleanup is in order first.

**Comment by Seldaek** [comment]
Yeah that sounds like quite some work and doesn't provide any direct benefits. Documentation about how to do such a plugin is now present, and I'm sure some examples will crop up in the wild if they haven't yet.
