### ISSUE TITLE
composer validate fails on tag 1.1 when using strict type declarations.

### ISSUE THREAD

**Issue by darianbr** [composer/composer#5307]
When I run this command using version 1.1 composer bin file (tag 1.0 works fine):

```
composer validate
```

I get this output:

```
PHP Fatal error:  strict_types declaration must be the very first statement in the script in /Users/username/projects/github/composer/composer/src/Composer/Plugin/PluginManager.php(193) : eval()'d code on line 3

Fatal error: strict_types declaration must be the very first statement in the script in /Users/username/projects/github/composer/composer/src/Composer/Plugin/PluginManager.php(193) : eval()'d code on line 3
```

The code that composer is attempting to eval is:

```
?><?php

declare (strict_types = 1); // @codeCoverageIgnore

namespace Vendor\Project;

class Foo
{
```

Due to line 193 in PluginManager.php executing `eval('?>'.$code);`.

On a side note, any reason to use `eval('?>'.$code);` instead of requiring the file?

**Comment by darianbr** [comment]
It is failing during my travis build. So as a temporary workaround I added 
```
before_install:
- composer self-update --rollback
```

to my travis.yml file which will rollback the composer version from 1.1 to 1.0 during the build.

**Comment by stof** [comment]
> On a side note, any reason to use eval('?>'.$code); instead of requiring the file?

If you look at the code, you will see that it can be modified to alter the class name name

**Comment by stof** [comment]
the workaround for now is to avoid putting the composer plugin class in strict mode

**Comment by Seldaek** [comment]
I am not sure what to do about this really. We could strip away the strict_type declaration I suppose. Any other idea?

**Comment by alcohol** [comment]
As I mentioned on Skype; stripping the opening tag and not having to use the closing tag makes the interpreter happy. I think it should be fairly easy and safe to accomplish that.

**Comment by staabm** [comment]
@TazeTSchnitzel @bwoebi any insights if php could allow 

```php
?><?php

declare (strict_types = 1);
```

without a warning like
```
PHP Fatal error:  strict_types declaration must be the very first statement in the script in /Users/username/projects/github/composer/composer/src/Composer/Plugin/PluginManager.php(193) : eval()'d code on line 3
```

**Comment by TazeTSchnitzel** [comment]
@staabm This is a guess, because I haven't looked into it, but I suspect `?><?php` gets compiled as if it was `echo "";`, thus the problem. PHP could add a hack where `?><?php` is ignored, I suppose…

**Comment by bwoebi** [comment]
@TazeTSchnitzel not quite. The T_CLOSE_TAG (see zendlex function) is returning a `;` (for supporting e.g. `<?=$foo?>`) which counts as empty statement. We may want to allow empty statements explicitly in `zend_declare_is_first_statement()`.

**Comment by Seldaek** [comment]
Closing as this doesn't seem to be a really big deal and nobody appears willing to fix it.
