### ISSUE TITLE
--no-dev flag not respected on install and update in version 1.1.0

### ISSUE THREAD

**Issue by pgarbarz** [composer/composer#5308]
With the following composer.json:

```json
{
    "require": {
        "php": ">=5.4.0",
        "oyejorge/less.php": "1.7.0.9",
        "php-di/php-di": "5.2.0",
        "zendframework/zend-http": "2.5.4"
    },
    "require-dev": {
        "pdepend/pdepend" : "2.2.4",
        "sebastian/phpcpd": "2.0.4",
        "squizlabs/php_codesniffer": "2.*",
        "theseer/phpdox": "0.8.*",
        "phploc/phploc": "2.*",
        "phpmd/phpmd": "2.4.*",
        "phpunit/phpunit": "4.8.21"
    },
}
```

When I run this command:

composer update --no-dev
composer install --no-dev

And I expected this to happen:

While install or update with `--no-dev` flag, dependencies from `require-dev` are trying to be resolved.

Same composer.json (without composer.lock and vendor dir) tested on version 1.0 works fine.

**Comment by alcaeus** [comment]
I can confirm this with the following minimal composer.json:
```
{
    "name":"test/fail",
    "type":"project",
    "license":"proprietary",
    "require":{
        "php": "^5.5"
    },
    "require-dev":{
        "ext-xdebug":">=2.0.5"
    }
}
```

With composer 1.1.0:
```
$ composer --version && composer install --no-dev
Composer version 1.1.0 2016-05-10 15:21:19
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-xdebug >=2.0.5 is missing from your system. Install or enable PHP's xdebug extension.
```

To compare, here's the same for composer 1.0.3:
```
$ composer --version && composer install --no-dev
Composer version 1.0.3 2016-04-29 16:30:15
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating autoload files
```

**Comment by alcaeus** [comment]
Looking at the changes in 1.1, I'd blame #5224 for this: https://github.com/composer/composer/pull/5224/files#diff-74425bc790838a69d0d16f06fc313edbL490

**Comment by alcohol** [comment]
Hmm, seems intentional after looking at the changes.

**Comment by alcaeus** [comment]
No, please don't remove the bug label. When installing without dev dependencies there's no point in requiring dev packages to be present. There's no point to differentiate between extensions, libraries and packages at this point.

**Comment by pgarbarz** [comment]
I also think that, this flag should be respected and it's a bug.
I use composer, on many vagrant machines, where `require-dev` libraries needs some php extensions, which of course are not needed on those vagrant machines. `--no-dev` flag was perfect for this. What is the sense of having it, if it always checking?

**Comment by stof** [comment]
@Seldaek I think an install from lock should not need to resolve them, as the goal of resolving them is to ensure the lock file is in the correct state

**Comment by pgarbarz** [comment]
And what if I want to build .lock while install task, but without dev libraries, because:

1. I don't need them on current project/machine
2. There are some dependencies on dev libraries which can't be resolved because of current machine configuration

**Comment by stof** [comment]
@pgarbarz the issue with that is that resolving deps with or without dev requirements would produce an inconsistent resolving of non-dev requirements (and committing a lock file generated without dev requirements would break the usage of ``composer install`` without the ``--no-dev`` option too).
This is why composer now takes them into account when resolving deps

**Comment by stof** [comment]
> I don't need them on current project

If the project does not need them, it should not define dev requirements

**Comment by alcaeus** [comment]
I agree with @stof here. IIRC, there were some issues in the early composer days when doing `composer update` without specifying dev dependencies (back then, you had to use the `--dev` switch). This was then changed to always resolve dev dependencies but only install them if you specified the `--dev` option, even when installing. This worked fine all the way up to 1.1.0. IMO, the process should be as follows:

`install` always respects the `--no-dev` option: if it is specified, don't check dev dependencies, don't install dev packages.
`update` always checks all dependencies to properly update the lock file (and have a lock file that includes all dependencies). Once the lock file update is complete, the `--no-dev` option should be respected, i.e. it doesn't install any dev packages if they weren't already installed.

**Comment by pgarbarz** [comment]
I'm totally agree with @alcaeus

**Comment by stof** [comment]
@alcaeus ``update`` works as you described here as of 1.1.0. In 1.0.0, doing a ``composer update --no-dev`` would totally ignore dev requirement, which is precisely what changed in 1.1

**Comment by alcaeus** [comment]
@stof Yes, that's what the PR intended to change and it's a good one. Unfortunately, install now also checks platform requirements specified via `require-dev` when `--no-dev` was specified, which effectively breaks `install --no-dev`

**Comment by Seldaek** [comment]
I'll take a look in a bit. Sounds like install from a lock file and --no-dev should skip the dev requirements for sure. Without lock file though it won't as that's basically an update.

**Comment by pgarbarz** [comment]
@stof I also agree with Your opinion about:

> > I don't need them on current project
> 
> If the project does not need them, it should not define dev requirements

this ofc fix problem, but before it works quite different.

**Comment by alcaeus** [comment]
> I'll take a look in a bit. Sounds like install from a lock file and --no-dev should skip the dev requirements for sure. Without lock file though it won't as that's basically an update.

Thanks for the reply. To clarify, this did happen when installing from lock file. I agree about it behaving different when no lock file is present.

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/commit/8f0324f51e4f94c9be18a19dbbc80c52e7b260c0 - you were right @alcaeus thanks for the pointer.

**Comment by alcaeus** [comment]
@Seldaek any chance we could get a hotfix in the next couple of days?

**Comment by Seldaek** [comment]
1.1.1 is out

**Comment by alcaeus** [comment]
Thank you!

**Comment by ruflin** [comment]
I somehow still seem to hit this issue with 1.1.2. This is my composer file:
```
{
    "name": "ruflin/elastica",
    "description": "Elasticsearch Client",
    "keywords": ["search","client"],
    "homepage": "http://elastica.io/",
    "type": "library",
    "license": "MIT",
    "authors": [
        {
            "name": "Nicolas Ruflin",
            "homepage": "http://ruflin.com/"
        }
    ],
    "require": {
        "php": ">=5.4.0",
        "psr/log": "~1.0"
    },
    "require-dev": {
        "aws/aws-sdk-php": "~3.0",
        "guzzlehttp/guzzle": "~6.0"
    },
    "suggest": {
        "aws/aws-sdk-php": "Allow using IAM authentication with Amazon ElasticSearch Service",
        "egeloen/http-adapter": "Allow using httpadapter transport",
        "guzzlehttp/guzzle": "Allow using guzzle 6 as the http transport (Requires php 5.5)",
        "monolog/monolog": "Logging request"
    },
    "autoload": {
        "psr-4": {
            "Elastica\\": "lib/Elastica/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Elastica\\Test\\": "test/lib/Elastica/Test/"
        }
    },
    "extra": {
        "branch-alias": {
            "dev-master": "3.1.x-dev"
        }
    }
}
```

If run `composer install --no-dev` it get the following error:

```
...
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - aws/aws-sdk-php 3.9.4 requires php >=5.5 -> your PHP version (5.4.45) does not satisfy that requirement.
...
```

It is correct, that the aws-sdk-php is not compatible with PHP 5.4, that is why we have it under require-dev. But it seems like it still checks for it and detects the incompatiblity? Is that expected? It worked with composer 1.0.*.

**Comment by alcohol** [comment]
It looks like you did not have a lock file. In that case, the new behaviour applies.

> Sounds like install from a lock file and --no-dev should skip the dev requirements for sure. Without lock file though it won't as that's basically an update.

**Comment by ruflin** [comment]
@alcohol That is correct, there is no lock file as Elastica does not check in a lock file. I assume there is no workaround here except for using the old docker version (or dropping support for PHP 5.4)?

**Comment by alcohol** [comment]
Correct.

**Comment by ruflin** [comment]
@alcohol Thanks a lot for the help. Will hack around it in this case (for the moment)
