### ISSUE TITLE
packages on Github private repo always require a token even when SSH key provided

### ISSUE THREAD

**Issue by gabriel-detassigny** [composer/composer#5312]
Hi guys,

I'm using a private git repository on github as a composer package in a project.
I'm using ssh keys to authenticate to it. 
However, even with a valid SSH key, composer always asks for a Github token.
(I'm using Docker, so I would need to re-enter that token each time as the global config wouldn't be stored).
It seems to work fine when I use the `--no-interaction` option, but that's a bit annoying to add that option for any composer command! And probably won't let us use any post-install-cmd if we need any in the future.

With the following composer.json:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:myprivate/repo.git",
            "options": {
                "ssh2": {
                    "username": "root",
                    "pubkey_file": "/root/.ssh/id_rsa.pub",
                    "privkey_file": "/root/.ssh/id_rsa"
                }
            }
        }
    ],
    "require": {
        "myprivate/repo": "dev-master"
    },
}
```

When I run this command:

```
composer install -vvv
```

I get this output:

```
Reading ./composer.json
Loading config file ./composer.json
Checking CA file /etc/ssl/certs/ca-certificates.crt
Executing command (/var/www/html): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /root/composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Loading composer repositories with package information
Downloading https://api.github.com/repos/myprivate/repo
Executing command (CWD): git config github.accesstoken
Your GitHub credentials are required to fetch private repository metadata (git@github.com:myprivate/repo.git)
Executing command (CWD): hostname
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+130f49b8be67+2016-05-11+1211
to retrieve a token. It will be stored in "/root/composer/auth.json" for future use by Composer.
Token (hidden):
```

I'm surprised that it doesn't try to fetch the repo using the SSH key, especially since it works using `--no-interaction`. Is there a way to force that, or maybe something else I'm missing?

Thanks for your help :)

**Comment by alcohol** [comment]
FYI: `--no-interaction` can be shortened to `-n`.

**Comment by alcohol** [comment]
Alternatively you could fire up your docker instance with the following ENV variable:

```
COMPOSER_AUTH={"github.com": "<your-token-here"}
```

**Comment by alcohol** [comment]
Composer asks for a token because it detects a private repo. There is no way for Composer to know if you have a valid SSH key or not. As you already mentioned, you can get around this using `-n` (or my previous ENV suggestion). Hence I see no reason to change the current behaviour.

**Comment by Seldaek** [comment]
You can also do this to prevent API usage which will remove the need for an API token, at least for the repo initialization:

```
        {
            "type": "vcs",
            "url": "git@github.com:myprivate/repo.git",
            "no-api": true
        }
```

**Comment by gabriel-detassigny** [comment]
Oh perfect! Thanks a lot, guys :smiley:

**Comment by WiRight** [comment]
Ok, I understand that it may be stupidly
But, if you run composer on your server, check that your key from server exists on GitHub
A have this issue and my problem solved by this case...)

P.S. sorry for my bad English

**Comment by likemusic** [comment]
> Alternatively you could fire up your docker instance with the following ENV variable:
> 
> ```
> COMPOSER_AUTH={"github.com": "<your-token-here>"}
> ```

Should be:
```
COMPOSER_AUTH={"github-oauth": {"github.com": "<your-token-here>"}}
```

**Comment by uphlewis** [comment]
Came here to add- that trying to change my repo url from https to ssh wasnt working for some reason- its cause i was using `composer install` but the https url was in the composer.lock already, so had to do `composer update` to get it to read the new url from composer.json instead.

**Comment by ranaprathap006** [comment]
Hi,
I'm trying to get install Codeigniter 4 in my system with the composer, but it showing error like below. Please help me to clear it.

C:\xampp\htdocs\newsportal>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 31 installs, 0 updates, 0 removals
  - Installing fzaninotto/faker (dev-master 5337ce5): Cloning 5337ce5261
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+DESKTOP-B7V11J0+2020-09-12+0801
to retrieve a token. It will be stored in "C:/Users/VR-Local/AppData/Roaming/Composer/auth.json" for future use by Composer.
Token (hidden):

**Comment by CiprianoPrince** [comment]
:)
