### ISSUE TITLE
Syntax error in autoload_static.php

### ISSUE THREAD

**Issue by ZachWatkins** [composer/composer#5316]
With the following composer.json:

```json
{
    "name": "agrilife/agriflex",
    "description": "Functionality for AgriLife AgriFlex theme",
    "license": "GPL2+",
    "authors": [
        {
            "name": "Zach Watkins",
            "email": "watkinza@gmail.com"
        }
    ],
    "minimum-stability": "stable",
    "require": {},
    "require-dev": {},
    "autoload": {
        "psr-4": {
            "AgriLife\\AgriFlex\\": "src"
        }
    }
}
```

When I run this command:

```
composer install
git push copy remote
```

I get this output:

```
remote: PHP Parse error: syntax error, unexpected '.', expecting ')' in - on line 19
```

And I expected this to happen:
No PHP errors

I am inexperienced with composer, and searching for a way to force composer.json to use a previous version of composer since this PHP error was not occurring last week.

**Comment by Seldaek** [comment]
The file is fine, it is made for PHP5.6+ and only included on those versions of PHP. If you have something linting all files, you will have to white-list that file I'm afraid.

**Comment by ZachWatkins** [comment]
The version of PHP running on our continuous integration service is not the same version of PHP running on our web host servers. The files are checked by our web host server.

Is there another solution? Because telling our web host not to lint files is not as easily done as providing a configuration file.

**Comment by Seldaek** [comment]
One option would be to delete the file before deploying it so it isn't
there to be linted. It won't be included if it's less than 5.6 so it
doesn't need to be there really.

**Comment by ZachWatkins** [comment]
How does composer check for the PHP version? Our CI service lets us set the PHP version using:
$ phpenv 5.4.45

Using this, we are still receiving the version of autoload for PHP 5.6+

**Comment by stof** [comment]
@ZachWatkins look at the ``autoload_real.php`` file. It decides at runtime whether it should include the ``autoload_static.php`` file or other generated files

**Comment by ZachWatkins** [comment]
By runtime, do you mean during the `$ composer install` operations? How do I define the PHP_VERSION_ID variable in bash in a way that autoload_real.php can access it and decide whether or not to add autoload_static.php to the package files?

**Comment by Seldaek** [comment]
@ZachWatkins this isn't a fool-proof solution, as soon as you get new autoload rules it might end up being unable to load some classes.

The best way IMO is for now to wipe the autoload_static.php file before deploy, and IF some day you get php upgraded to 5.6+ then stop wiping it so that it can load it and all will be fine.

**Comment by ZachWatkins** [comment]
Ok, then we'll do that and deal with related problems if they come up. Thanks for your help.
