### ISSUE TITLE
Composer v1.1.0 generated composer/autoload_static.php file syntactily invalid for PHP <5.6

### ISSUE THREAD

**Issue by bd808** [composer/composer#5324]
The [composer/autoload_static.php file](https://gerrit.wikimedia.org/r/#/c/288430/1/composer/autoload_static.php,unified) generated for the [REL1_25 release branch of mediawiki/vendor](https://github.com/wikimedia/mediawiki-vendor/tree/REL1_25) using Composer version 1.1.0 2016-05-10 15:21:19 fails a `php -l` lint check:

```
$ composer --version
Composer version 1.1.0 2016-05-10 15:21:19
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
$ php -v
PHP 5.5.31 (cli) (built: Jan 11 2016 23:27:33)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
$ php -l composer/autoload_static.php

Parse error: parse error, expecting `')'' in composer/autoload_static.php on line 23
Errors parsing composer/autoload_static.php
```

Using PHP 5.3 gives a slightly more useful lint failure message:
```
$ php -v
PHP 5.3.29 (cli) (built: Sep 15 2014 12:04:44)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans
$ php -l composer/autoload_static.php
PHP Parse error:  syntax error, unexpected '.', expecting ')' in composer/autoload_static.php on line 23
Errors parsing composer/autoload_static.php
```

The underlying problem is that PHP versions before 5.6 cannot use expressions when defining static properties:
> Like any other PHP static variable, static properties may only be initialized using a literal or constant before PHP 5.6; expressions are not allowed.
-- https://secure.php.net/manual/en/language.oop5.static.php#language.oop5.static.properties

**Comment by bd808** [comment]
I see that this use of this file is guarded in composer/autoload_real.php with a check for `PHP_VERSION_ID >= 50600`. The problem then is just one of the MediaWiki lint checks. Sorry for the noise.

**Comment by Chealer** [comment]
For Eclipse, this can be worked around using "Use as Library Folder" on the vendor/ directory.
