### ISSUE TITLE
composer  not work with debian

### ISSUE THREAD

**Issue by xoceunder** [composer/composer#5330]
does not work with debian and apache2

**Comment by staabm** [comment]
@xoceunder with this issue-report noone can help you. please describe the problem and provide more information. any error messages? how does your environment look like? which debian version...

**Comment by xoceunder** [comment]
@staabm  does not work  this http://91.134.176.53/ user: admin and pass: admin

**Comment by stof** [comment]
composer is a CLI too. So your bug report does not make sense

**Comment by xoceunder** [comment]
as I can make it work @stof
