### ISSUE TITLE
Is it possible to disable version string validation

### ISSUE THREAD

**Issue by MaksSlesarenko** [composer/composer#5331]
I've encountered problem updating dependencies:

> Your requirements could not be resolved to an installable set of packages.
>   Problem 1
> The requested PHP extension ext-phalcon >1.2 has the wrong version (2.1.0r) installed.

The reason of this is that I've extension that has version "2.1.0r" that composer fails to validate.

**Comment by kamilsk** [comment]
@MaksSlesarenko, please use `--ignore-platform-reqs`. Or you can create issue here https://github.com/phalcon/cphalcon/issues to support https://getcomposer.org/doc/articles/versions.md

**Comment by xabbuh** [comment]
see also https://github.com/composer/composer/issues/5264#issuecomment-216800184 for a suggestion from @Seldaek on how to improve the user experience here

**Comment by MaksSlesarenko** [comment]
I agree some packages version naming are not so formal. But the goal is to determine whether environment can evaluate  source code or not, otherwise it is not usefull to declare module dependencies in composer.json. 

I think that for this purpose there should be more complex solution than just setting module name and version. 
For example, I can not specify in composer that my app needs mongo extension because for php7 it is called "mongodb" and in other versions it is just "mongo".

**Comment by Seldaek** [comment]
Just pushed a fix that should make 2.1.0r parse as 2.1.0
