### ISSUE TITLE
--no-interaction option is treated as invalid for install command

### ISSUE THREAD

**Issue by FlyingDR** [composer/composer#5332]
`--no-interaction` option is treated as invalid argument when used together with `install` command despite of the fact that it is available into list of options:
```bash
$ composer --version
Composer version 1.1.0 2016-05-10 15:21:19
$ composer help install | grep "no-interaction"
  -n, --no-interaction           Do not ask any interactive question
$ composer install -vvv --no-interaction
Reading ./composer.json
Loading config file /var/www/.composer/config.json
Loading config file /var/www/.composer/auth.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/var/www/test): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /var/www/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /var/www/test/vendor/composer/installed.json
Loading plugin johnpbloch\Composer\WordPressCorePlugin
Loading plugin Flying\Composer\Plugin\WordpressComposerToolsPlugin
Loading plugin Composer\Installers\Plugin
Running 1.1.0 (2016-05-10 15:21:19) with PHP 5.6.20-1~dotdeb+7.1 on Linux / 2.6.32-406.el5.028stab119.2
Invalid argument -vvv --no-interaction. Use "composer require -vvv --no-interaction" instead to add packages to your composer.json.
```
Practical meaning of using this argument together with `install` command is Composer plugins that may rely on `IO::isInteractive()`.

**Comment by stof** [comment]
that looks really weird. It looks like the input was parsed as a single argument ``-vvv --no-interaction`` instead of parsing options. I never saw such behavior

**Comment by FlyingDR** [comment]
without `-vvv` option result is the same:
```bash
$ composer install -n
Invalid argument -n. Use "composer require -n" instead to add packages to your composer.json.
$ composer install --no-interaction
Invalid argument --no-interaction. Use "composer require --no-interaction" instead to add packages to your composer.json.
```
@stof Since from your comment it looks like problem may be somewhere else - can I help with any other tests?

**Comment by stof** [comment]
is ``composer`` the phar itself on your machine, or is it a wrapper script ?

**Comment by FlyingDR** [comment]
It looks like it is a wrapper:
```bash
$ whereis composer
composer: /usr/local/bin/composer.phar /usr/local/bin/composer
$ cat /usr/local/bin/composer
#!/bin/bash

/usr/bin/php /usr/local/bin/composer.phar -- $*

$
```

**Comment by stof** [comment]
the issue is the ``--`` there: this tells composer that anything following it is an argument, not an option. So your wrapper script does not allow you to pass options to composer.

**Comment by FlyingDR** [comment]
heh, you're right, stupid me... :( 

after fixing this composer starts to work properly. thanks for help!

**Comment by stof** [comment]
btw, you could simply rename composer.phar to be ``/usr/local/bin/composer`` itself. Making the phar executable will then work, as it starts with a shebang to execute it with php (assuming that ``which php`` gives you ``/usr/bin/php``, it will work fine)

**Comment by FlyingDR** [comment]
Thanks!
