### ISSUE TITLE
RFC: Do not use caret operator when requiring unstable package without version

### ISSUE THREAD

**Issue by localheinz** [composer/composer#5338]
With the following composer.json:

```json
{
    "name": "foo/bar",
    "description": "Foos all the bars",
    "type": "library",
    "license": "MIT",
    "require": {
        "php": "^5.5 || ^7.0"
    }
}
```

When I run this command:

```
$ composer require sentry/sentry
```

I get this output:

```
Using version ^0.17.0 for sentry/sentry
```

And I expected this to happen:

```
Using version 0.17.0 for sentry/sentry
```

💁 The problem is that with unstable packages, **anything may change at any time**, see [Semantic Versioning](http://semver.org/#spec-item-4):

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

So ideally, when requiring a package that is unstable (`0.x.y`), `composer` should not use (and implicitly suggest) the `^` operator, as running 

```
$ composer update
```

could potentially pull in breaking changes. 

Instead, `composer` should pin to the exact (highest unstable) version.

#### Version

```
$ composer --version
Composer version 1.1.0 2016-05-10 15:21:19
```

**Comment by xabbuh** [comment]
The caret operator behaves a bit differently when the major version is 0. Thus `^0.17.0` will only pull in `0.17.x` versions.

**Comment by localheinz** [comment]
@xabbuh 

Still,

> Anything may change at any time.

**Comment by Seldaek** [comment]
That's what semver says strictly (and why its generally bad to tag 0.x releases as they're a bit meaningless) but I think in practice most people try to avoid breaks in patch releases even in 0.x so IMO it's fine as is. It does t prevent you from being more restrictive if that's what you want, require just offers a suggestion.
