### ISSUE TITLE
EventDispatcherTest fails with Composer 1.1.0

### ISSUE THREAD

**Issue by pierres** [composer/composer#5340]
With Composer 1.1.0 the PHPUnit test `Composer\Test\EventDispatcher\EventDispatcherTest::testDispatcherCanConvertScriptEventToCommandEventForListener` fails with:

`Failed asserting that exception of type "PHPUnit_Framework_Error_Deprecated" is thrown.`

The issue was introduced with commit `e6c6d25b599da56ccc17def8c82fe88d3130210e`. I have tested on PHP version 5.5, 5.6 and 7.0.

It is also reproducible with the official PHP docker images. I wonder why the Travis tests do not fail though.

**Comment by Seldaek** [comment]
Yup I can reproduce it too but it only occurs when running the full test suite. Running that test alone doesn't fail which is why Travis works I think as it runs subsuites in parallel.

**Comment by Seldaek** [comment]
Ok I got a fix will push later.
