### ISSUE TITLE
composer self-update errors with invalid composer.json

### ISSUE THREAD

**Issue by staabm** [composer/composer#5348]
be in a directory with an empty `composer.json` and run `composer self-update`.

```
  [Seld\JsonLint\ParsingException]
  "./composer.json" does not contain valid JSON
  Parse error on line 1:
  ^
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['
```

why does the self-update command depend on a local composer.json file?

expected: `composer self-update` should run and update the composer binary no matter what a local composer.json looks like. Information from such a local composer.json is not relevant for the self-update, therefore shouldn't influence it?

env:
```
composer --version
Composer version 1.1.0 2016-05-10 15:21:19

php --version
PHP 5.4.45-3+deb.sury.org~precise+1 (cli) (built: Jan  7 2016 15:32:17)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend Debugger v6.0.0, Copyright (c) 1999-2013, by Zend Technologies
    with blackfire v1.10.5, https://blackfire.io, by Blackfireio Inc.
```

**Comment by staabm** [comment]
just realized that `composer --version` also prints the same error under such conditions.

**Comment by alcohol** [comment]
That's because this file is read during init/bootstrap state of Composer since it can contain configuration directives (e.g. cache-directory, etc, which are relevant for self-update).
