### ISSUE TITLE
Linux installation - mention apt-get

### ISSUE THREAD

**Issue by bamarni** [composer/composer#5351]
I just noticed composer could be installed through apt-get without any custom repo, it is apparently in the [official sources](http://packages.ubuntu.com/search?keywords=composer&searchon=names) since Ubuntu 15.10 and in Debian 9 (current testing). Would it make sense to mention this in the doc?

**Comment by stof** [comment]
This is installing an outdated version of Composer (15.10 and 16.04 are both installing an pre-1.0 alpha release), so I would not mention it in the official composer doc. I don't think this should be considered an officially supported installation channel

**Comment by bamarni** [comment]
It's a bit more recent (I'm getting beta2 in ubuntu 16.04) but indeed that's not a good option then.
