### ISSUE TITLE
Installation instructions which can be automated

### ISSUE THREAD

**Issue by bamarni** [composer/composer#5352]
I can understand why piping curl into php isn't the recommended installation method anymore, but is there an alternative way to automate composer installation now?

The [current instructions](https://getcomposer.org/download/) require to compare the installer against an hardcoded checksum.

**Comment by stof** [comment]
The signature is also available elsewhere. See http://composer.github.io/pubkeys.html

**Comment by bamarni** [comment]
Ah cool, thanks for the tip 👍
