### ISSUE TITLE
Q: post-package-install not working

### ISSUE THREAD

**Issue by ogrosko** [composer/composer#5353]
I have created composer [package](https://github.com/ogrosko/typo3-composer-maintenance) with some `post-package-install` script. But on installing package this script doesn't run
With the following composer.json:

```json
{
    "name"             : "ogrosko/typo3-composer-maintenance",
	"description"      : "Composer pre/post scripts for enabling/disabling maintenance mode for typo3",
	"keywords"         : ["maintenance", "typo3", "composer"],
	"type"             : "composer-scripts",
	"license"          : "GPL-3.0",
	"minimum-stability": "dev",
	"version"		   : "0.0.1",
	"authors"          : [
		{
			"name" : "Ondrej Grosko",
			"email": "ogrosko@gmail.com"
		}
	],
	"autoload": {
		"psr-4": {
			"OGrosko\\": "Classes/"
		}
	},
	"require": {
		
	},
    "scripts": {
        "post-package-install": [
        	"OGrosko\\Composer\\InstallerScripts::postPackageInstall"
        ],
        "post-package-update": [
        	"OGrosko\\Composer\\InstallerScripts::postPackageInstall"
        ]
    }
}
```

When I run this command:

```
composer require ogrosko/typo3-composer-maintenance
```

PAckage is installed but `post-package-install` and `post-package-update` scripts are not executed

Am I doing something wrong?

**Comment by stof** [comment]
scripts are a root-only feature, as explained in the doc. So this is totally expected

**Comment by ogrosko** [comment]
Ahaa so I have to always put to my root `composer.json` file?

**Comment by Seldaek** [comment]
Yup

**Comment by kjdion84** [comment]
Wow this sucks enormously.

**Comment by judgej** [comment]
Ooooh. I thought the statement meant it only works on packages installed in the root. It is actually even more specific than that.
