### ISSUE TITLE
Self update to a specific version/commit

### ISSUE THREAD

**Issue by Soullivaneuh** [composer/composer#5356]
It would be great to add a specific version option or commit sha on the `self-update`.

```bash
composer sefl-update --version=1.0.0
composer self-update --version=#1df5sfge8
```

This would permit to compare composer issues between versions with ease.

**Comment by Soullivaneuh** [comment]
Forget it, it's already possible. Need coffee.

**Comment by stof** [comment]
The getcomposer.org server does not keep the phar for each commit, so this cannot be implemented for the commit hash. and it is ``composer self-update 1.0.0`` for the version

**Comment by stof** [comment]
technically, it can be done for a specific commit in 1 case: when you already had this version installed in the past and you have not removed the backup created by ``self-update``
