### ISSUE TITLE
Updating a package that itself has an updated dependency is failing

### ISSUE THREAD

**Issue by chrisemerson** [composer/composer#5362]
Hi,

There appears to be an issue updating packages when that package updates one of the versions of its own dependency. I noticed the issue when trying to update the version of slim/slim, which in turn had updated its version of nikic/fast-route from 0.6 to 1.0. I don't know if the fact that it's updating from a pre-1.0 version has anything to do with it, but it's possible.

To recreate:

```
$ mkdir test
$ cd test
$ composer require slim/slim 3.3.0
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing container-interop/container-interop (1.1.0)
    Loading from cache

  - Installing nikic/fast-route (v0.6.0)
    Loading from cache

  - Installing psr/http-message (1.0)
    Loading from cache

  - Installing pimple/pimple (v3.0.2)
    Loading from cache

  - Installing slim/slim (3.3.0)
    Loading from cache

Writing lock file
Generating autoload files

$ composer require slim/slim ^3.4
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nikic/fast-route (locked at v0.6.0) -> satisfiable by nikic/fast-route[v0.6.0].
    - slim/slim 3.4.0 requires nikic/fast-route ^1.0 -> satisfiable by nikic/fast-route[v1.0.0].
    - slim/slim 3.4.1 requires nikic/fast-route ^1.0 -> satisfiable by nikic/fast-route[v1.0.0].
    - Conclusion: don't install nikic/fast-route v1.0.0
    - Installation request for slim/slim ^3.4 -> satisfiable by slim/slim[3.4.0, 3.4.1].


Installation failed, reverting ./composer.json to its original content.
```

As you can see, it's trying to install v1.0 of nikic/fast-route in order to update the slim/slim package, but it's conflicting with the version 0.6.0 which is installed & in the lock file, and fails. Since nikic/fast-route is only a dependency of the package I'm trying to update (slim/slim) and nothing else, I would expect composer to ignore this conflict and trust the new dependency list of the package I'm trying to update, updating nikic/fast-route to 1.0.

**Comment by alcohol** [comment]
Read: https://getcomposer.org/doc/03-cli.md#require

```
--update-with-dependencies: Also update dependencies of the newly required packages.
```

**Comment by chrisemerson** [comment]
Ah thanks. Must have missed that. Perhaps something to add to the error message in these cases? I would expect that if I requested an update to a package and it needed an updated dependency that nothing else relied on, it'd just update it though. Only if I or some other package relies on the old version should it error perhaps?

**Comment by alcohol** [comment]
I think we chose explicitly for this behaviour because when you do `composer require a/b`, in practical terms that means you add `a/b` to your list of requirements and then run `update a/b`. Since `update a/b` only mentions `a/b`, we do not update any dependencies it might have, unless you explicitly whitelist them (e.g. `update a/b a/c`) or if you pass the `--with-dependencies` flag to `update` (which is `--update-with-dependencies` when calling `require`).

**Comment by chrisemerson** [comment]
I see where you're coming from, but unless I (or another of my dependencies) also explicitly depends on that package, should I as a developer need to be concerned what upgrades my direct dependencies are doing? It took a fair while to get to the bottom of the issue as well, so a more descriptive error message (and suggestion to use --with-dependencies) might be a good change.

**Comment by alcohol** [comment]
> should I as a developer need to be concerned what upgrades my direct dependencies are doing

I guess that depends on the following: do you think it is wise to be in the dark about what you are installing on your system/environment?

**Comment by chrisemerson** [comment]
I don't think the 2 are mutually exclusive. It could be as simple as informing you that the upgrade would happen, or could prompt you to confirm you are happy that it is happening perhaps.

**Comment by alcohol** [comment]
That's not really an option, as installing it (or not) changes the dependency graph, which is already resolved before we install anything.

**Comment by dhensby** [comment]
I'm getting a similar issue when requiring a package globally.

```
- silverstripe/blowgun dev-master requires symfony/process 2.7.1 -> satisfiable by symfony/process[v2.7.1].
    - silverstripe/blowgun dev-master requires symfony/process 2.7.1 -> satisfiable by symfony/process[v2.7.1].
    - Conclusion: don't install symfony/process v2.7.1
```

Adding `--update-with-dependencies` makes no difference

**Comment by stof** [comment]
maybe you have another requirement forbidding to use symfony/process 2.7.1

Btw, silverstripe/blowgun should really allow a range instead of forcing to use an exact version (especially when it forces using a version of Symfony containing security issues, even if it is in another component)

**Comment by dhensby** [comment]
> maybe you have another requirement forbidding to use symfony/process 2.7.1

I'll take a look, the strange thing is that `composer update` works when just checking out the repo rather than requiring it globally

> Btw, silverstripe/blowgun should really allow a range instead of forcing to use an exact version (especially when it forces using a version of Symfony containing security issues, even if it is in another component)

Yep, I know, not for me to maintain, I'm afraid.

**Comment by Seldaek** [comment]
Auto-closing as this hasn't been updated in over 6months and is marked as a support request. If there is a real bug to consider please let us know.
