### ISSUE TITLE
Xampp Portable Installation Error

### ISSUE THREAD

**Issue by ButsAndCats** [composer/composer#5365]
I am using a portable version of xampp on windows. After locating the php.exe file during the installation I get the following message:

'```
The PHP exe file you specified did not run correctly:
F:\xampp\php\php.exe

The php.ini used by your command-line PHP is: F:\xampp\php\php.ini

A setting in your php.ini could be causing the problem: Either the 'extension_dir' value is incorrect or the dll does not exist.

Program Output:
Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_bz2.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_curl.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_mbstring.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_exif.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_gd2.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_gettext.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_mysql.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_mysqli.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_openssl.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_pdo_mysql.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_pdo_sqlite.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_soap.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_sockets.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_sqlite3.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_xmlrpc.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_xsl.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: Cannot open '\xampp\php\extras\browscap.ini' for reading in Unknown on line 0'
```

**Comment by kamilsk** [comment]
What does the Composer?

**Comment by ButsAndCats** [comment]
Composer-Setup.exe

**Comment by kamilsk** [comment]
Please provide output of `F:\xampp\php\php.exe -v` from `cmd`

**Comment by ButsAndCats** [comment]
```
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_bz2.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_bz2.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_curl.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_curl.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_mbstring.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_mbstring.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_exif.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_exif.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_gd2.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_gd2.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_gettext.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_gettext.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_mysql.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_mysql.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_mysqli.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_mysqli.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_openssl.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_openssl.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_pdo_mysql.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_pdo_mysql.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_pdo_sqlite.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_pdo_sqlite.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_soap.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_soap.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_sockets.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_sockets.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_sqlite3.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_sqlite3.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_xmlrpc.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_xmlrpc.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_xsl.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_xsl.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  Cannot open '\xampp\php\extras\browscap.ini' for reading in Unknown on line 0

Warning: Cannot open '\xampp\php\extras\browscap.ini' for reading in Unknown on line 0
PHP 5.6.15 (cli) (built: Oct 29 2015 12:40:36)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

**Comment by kamilsk** [comment]
@ButsAndCats, how I can see it is not a problem of Composer, but problem of your environment. Please use the XAMPP documentation to configure it correctly.

**Comment by ButsAndCats** [comment]
Thanks for your assistance, I expect it is due to it being a portable version.

**Comment by kamilsk** [comment]
after configuration your output should looks something like this:

```
$ F:\xampp\php\php.exe -v
PHP 5.6.15 (cli) (built: Oct 29 2015 12:40:36)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

without any warnings

**Comment by kamilsk** [comment]
> Thanks for your assistance

you are welcome

**Comment by kamilsk** [comment]
@ButsAndCats, can be closed?

**Comment by ButsAndCats** [comment]
Yep, it's working well on a static installation of xampp for anyone else experiencing this issue.

**Comment by kannangce** [comment]
What's the proper fix while using portable version?

**Comment by sizeg** [comment]
@kannangce just use windows paths instead
```php
# extension_dir = "\xampp-7.1\php\ext"
extension_dir = "./ext"
```

**Comment by byndstd** [comment]
`@kannangce just use in php.ini windows paths instead

; extension_dir = "\xampp-7.1\php\ext"
extension_dir = "./ext"`

I did try this but still not working on Portable version

**Comment by sizeg** [comment]
@byndstd try to specify full path. With some settings I can't get work relative path too, but they works perfect with a full path. For example:

`browscap = "d:\xampp-7.1\php\extras\browscap.ini"`

**Comment by xinzhan** [comment]
alternative to adding the absolute path to every module, look for the following in php.ini and add the drive instead:
extension_dir = "\xampp\php\ext"

**Comment by mmamoonkhan** [comment]
these warnings can not solved i tried to many solutions but still have an error and due to this i can not run my project
Warning: PHP Startup: Unable to load dynamic library 'pdo_sqlite' (tried: \xampp\php\ext\pdo_sqlite (The specified module could not be found.), \xampp\php\ext\php_pdo_sqlite.dll (The specified procedure could not be found.)) in Unknown on line 0
PHP Warning: PHP Startup: Unable to load dynamic library 'php_openssl.dll' (tried: \xampp\php\ext\php_openssl.dll (The specified procedure could not be found.), \xampp\php\ext\php_php_openssl.dll.dll (The specified module could not be found.)) in Unknown on line 
![error](https://user-images.githubusercontent.com/27205456/51606301-5ae10400-1f33-11e9-9be5-f2bd2379998a.PNG)

**Comment by sheikhuzairhussain** [comment]
In your `php.ini` file, change the line
`browscap = "\xampp\php\extras\browscap.ini"`
to `browscap = "C:\xampp\php\extras\browscap.ini"`
