### ISSUE TITLE
Composer reading dependencies from entire branch instead of from certain commit

### ISSUE THREAD

**Issue by capelinventures** [composer/composer#5369]
We're running a Symfony app with some older dependencies and thus some of the required versions are specified explicitly to certain versions of dev-master commit IDs:

With the following composer.json:

```json
{
        "sonata-project/admin-bundle": "~2.3",
        "sonata-project/doctrine-orm-admin-bundle": "~2.3",
        "sonata-project/doctrine-mongodb-admin-bundle": "~2.3",
        "sonata-project/easy-extends-bundle": "2.1.*",
        "sonata-project/datagrid-bundle": "~2.2",
        "sonata-project/user-bundle": "dev-master#0c56664",
}
```

When I run this command:

```
composer update -vvv (please include -vvv!)
```

I get this output:

```
Running 1.1.1 (2016-05-17 12:25:44) with PHP 5.5.30 on Linux / 4.1.7-hardened-r1
...
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sonata-project/user-bundle dev-master requires sonata-project/admin-bundle ^3.1 -> satisfiable by sonata-project/admin-bundle[3.1.0, 3.x-dev] but these conflict with your requirements or minimum-stability.
    - sonata-project/user-bundle dev-master requires sonata-project/admin-bundle ^3.1 -> satisfiable by sonata-project/admin-bundle[3.1.0, 3.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for sonata-project/user-bundle dev-master#0c56664 -> satisfiable by sonata-project/user-bundle[dev-master].
```

Previously it worked flawlessly. Now it doesn't.
If you browse files on sonata-project/user-bundle commit id #0c56664 and look at the composer.json file there ( https://github.com/sonata-project/SonataUserBundle/tree/0c566644c3b16e96979410b0c06aa6ea262b143b ), you'll notice that our requirements are met BUT if you look at the composer.json of the general (newest) master branch ( https://github.com/sonata-project/SonataUserBundle/tree/master ), you will notice that the requirements have changed.

My conclusion is that DESPIRE of me telling EXPLICITLY which commit to use, composer still loads the dependency requirements from the entire master branch, instead of this particular commit.

...or can it be solved some other way I'm not aware of?

**Comment by alcohol** [comment]
https://getcomposer.org/doc/articles/troubleshooting.md#i-have-locked-a-dependency-to-a-specific-commit-but-get-unexpected-results-
