### ISSUE TITLE
Allow different names in branches

### ISSUE THREAD

**Issue by Yehonal** [composer/composer#5372]
Suppose that I've a package on git that must change name ( or part of it)  at a specific version,  but i want to continue to support old version without create multiple repository.
 In git i can easily create a branch. But composer doesn't allow you to include that branch as dependency because has different name from the master branch. 

However you can "hack" this removing master branch, naming it in another way. 

Why you just don't remove this limit? 

I've created a more specific related comment some days ago here: https://github.com/composer/composer/issues/2588#issuecomment-219210375

**Comment by alcohol** [comment]
> Why you just don't remove this limit?

Sanity. :-)

A repository should contain a single library.

**Comment by Yehonal** [comment]
As i said,  there are cases where the library is the same but needs different names for version. Or you can read my related comment about the case of "strictly related orphan branch". 

Which sanity are you trying to protect? Git allows orphan branches for many kind of edge purpose that in some cases can be very helpful. 

You can say: "if someone include both old version and new version of the same library,  you can have class conflicts..."
But what limit you to create another repo to do the things I've said before? It's just more insane to create multiple repo for each lib version imho. 

You cannot avoid conflicts, it should be a language feature ( good namespacing for example) 

Not of the package manager.

**Comment by Yehonal** [comment]
However I'll continue to use hack explained before if it won't be fixed.

Often the best things are insane.

**Comment by alcohol** [comment]
Different names for versions makes no sense whatsoever from a versioning perspective.

**Comment by Yehonal** [comment]
Maybe in your little world. There are a lot of projects /packages splitted in various version that are developed in parallel, have different names ( even if just in suffix),  can be installed together and are nicely "namespaced"  to avoid conflicts if you care. 
They can share the same "root" but they are different branches.

**Comment by alcohol** [comment]
Ok.
