### ISSUE TITLE
Update dependency: justinrainbow/json-schema

### ISSUE THREAD

**Issue by alcohol** [composer/composer#5374]
https://github.com/justinrainbow/json-schema/compare/1.6.1...2.0.4

**Comment by Seldaek** [comment]
Right, I saw 1.6.1 bumped the php requirement but I didn't realize 2.0 undid that. Easy update.

**Comment by alcohol** [comment]
I wasn't sure if it would be a BC change since the major version got bumped. But I guess we only used it in the most basic sense, so no work required :-)
