### ISSUE TITLE
Signature mismatch (no such file or directory) - intermittent

### ISSUE THREAD

**Issue by kian** [composer/composer#5375]
The https://getcomposer.org/installer script has been failing with the following error:

```
Signature mismatch, could not verify the phar file integrity
```

The warnings indicate that signature validation fails because the file doesn't exist (because `copy()` failed on line 556) but the file **does** in fact exist, and it's md5 hash matches the latest version.

```
in bin/ on master
› ls -la
total 1604
drwxr-xr-x 3 Inanna staff     102 May 25 08:42 ./
drwxr-xr-x 3 Inanna staff     102 May 25 08:41 ../
-rwxr-xr-x 1 Inanna staff 1640247 May 25 08:42 composer*
```

```
05d30d20be1c94c9edc02756420a7d10  composer
```

**The strange part is that this error resolved itself after a few minutes, and installation now succeeds.**  Nothing was changed on our end however.

Questions:

 - Is this installation method still supported?
 - Could this have been an intermittent issue with https://getcomposer.org/installer?  
 - Is there some other information that would be useful to provide?

The complete error is shown below. 

```
php -r "readfile('https://getcomposer.org/installer');" | \
        php -- --install-dir='build/bin' --filename=composer
All settings correct for using Composer
Downloading 1.1.1...

PHP Warning:  copy(/Users/Inanna/placelocal/build/bin/composer): failed to open stream: No such file or directory in - on line 556
Warning: copy(/Users/Inanna/placelocal/build/bin/composer): failed to open stream: No such file or directory in - on line 556

PHP Warning:  file_get_contents(/Users/Inanna/placelocal/build/bin/composer): failed to open stream: No such file or directory in - on line 570
Warning: file_get_contents(/Users/Inanna/placelocal/build/bin/composer): failed to open stream: No such file or directory in - on line 570
Signature mismatch, could not verify the phar file integrity
```

**Comment by Seldaek** [comment]
The installation method should still work yes, but the error doesn't make much sense to me as it should fail earlier or at least print that the download failed if it couldn't write/download the file. Not quite sure what happened there, but if you can't reproduce it's gonna be hard to figure out I guess.

**Comment by dmeziere** [comment]
For the people landing here like I did for a close (same error message) but not identical problem, you can also check that the directory ~/.composer exists, and that current (may be different when sudoing as www-data for example) user has the write permissions to it, as Composer will place it's keys and cache here.

**Comment by vetripandi** [comment]
U have just use sudo then it will be successfully installed..first i've also face this error and now am understand..
