### ISSUE TITLE
Composer listens for flags after `--` when running exec.

### ISSUE THREAD

**Issue by Neppord** [composer/composer#5377]
When I run this command:

```
bin/composer.phar -vvv exec -- phpunit --version
```

I get this output:

```
Running 5c9c9102400dc4e38b8ea91074f22c7014050159 (2016-04-24 14:55:55) with PHP 5.6.17 on Linux / 3.2.0-4-amd64
Composer version 1.1-dev (5c9c9102400dc4e38b8ea91074f22c7014050159) 2016-04-24 14:55:55
```

And I expected same as:
```
bin/composer.phar -vvv exec -- 'phpunit --version'
```

**Comment by Neppord** [comment]
it still don't work after a self update.

```
Reading ./composer.json
Loading config file /home/.../.composer/config.json
Loading config file /home/.../.composer/auth.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Failed to initialize global composer: Composer could not find the config file: /home/.../.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading .../vendor/composer/installed.json
Running 1.1.1 (2016-05-17 12:25:44) with PHP 5.6.17 on Linux / 3.2.0-4-amd64
Composer version 1.1.1 2016-05-17 12:25:44
```

**Comment by stof** [comment]
I think this is because ``--version`` is implemented in a special way in Symfony Console, and does not handle ``--`` properly (we probably have the same issue for ``-v`` for the verbose mode btw).

Please open an issue on Symfony for that (it is not something Composer itself can fix, as it does not implement ``--version``)

**Comment by Seldaek** [comment]
Yeah that's a symfony bug I've been meaning to tackle for a while but then I guess I forgot :)

**Comment by Seldaek** [comment]
Ah I knew this rang a bell, I actually fixed this  a while back, but it only made it into Symfony 3.0 https://github.com/symfony/symfony/pull/11431 - so we'll get this fixed whenever we upgrade to sf3 (which.. is not gonna be too soon I'm afraid).
