### ISSUE TITLE
Ability to Quiet Suggestions?

### ISSUE THREAD

**Issue by donatj** [composer/composer#5379]
I have an automated testing process that runs composer install with `--prefer-dist --no-interaction --no-progress`. Even with these set I still end up with about 40 lines of:

```
aws/aws-sdk-php suggests installing aws/aws-php-sns-message-validator (To validate incoming SNS notifications)
aws/aws-sdk-php suggests installing doctrine/cache (To use the DoctrineCacheAdapter)
jakub-onderka/php-parallel-lint suggests installing jakub-onderka/php-console-highlighter (Highlight syntax in code snippet)
phing/phing suggests installing pdepend/pdepend (PHP version of JDepend)
...
```

They're just taking up space in my logs.  It would be nice to be able to silence suggestions with a flag.

**Comment by staabm** [comment]
You could use a custom `SuggestedPackagesReporter`

https://github.com/composer/composer/blob/master/src/Composer/Installer.php#L1623

**Comment by Seldaek** [comment]
`composer install | grep -v 'suggests installing` should fix it.

**Comment by donatj** [comment]
lol, that is the lamest solution I've ever heard.
