### ISSUE TITLE
how to get the path of global-required vendor directory.

### ISSUE THREAD

**Issue by yjqg6666** [composer/composer#5385]
I run some scripts which depend on some global-required libraries.  
On *nix machine, i could simply require_once $HOME/.composer/vendor/autoload.php, for windows X  it is $APPDATA/Composer/vendor/autoload.php. For other windows versions, the path may be different. 

Is there any way i could query the path of global vendor directory, which is compatible with windows x/8/7 and *nix.

**Comment by yjqg6666** [comment]
From the source code, i found https://github.com/composer/composer/blob/master/src/Composer/Config.php#L256
I googled and found nothing related to this.

**Comment by alcohol** [comment]
I would suggest `composer global config --absolute vendor-dir` but unfortunately that annoyingly puts out some stuff on stderr which you cannot easily avoid (`--quiet` makes the command output **nothing** at all).

**Comment by yjqg6666** [comment]
$ composer global config --absolute vendor-dir 2>/dev/null    solved my problem. Thanks @alcohol .

**Comment by alcohol** [comment]
I was thinking of suggesting that, but I didn't think `2>/dev/null` would work on windows.. o_O

**Comment by yjqg6666** [comment]
It's SO TRUE.

**Comment by yjqg6666** [comment]
is there any environment variable could disable the warning/error ?

**Comment by alcohol** [comment]
It's neither, it is verbose information. But there is no way to disable it.

**Comment by Seldaek** [comment]
On windows you can use `composer global config --absolute vendor-dir 2>NUL`
