### ISSUE TITLE
Broken code-generation

### ISSUE THREAD

**Issue by mindplay-dk** [composer/composer#5386]
I have two helper modules in different namespaces, but they have the same class-name.

This results in a fatal error after `codecept build`:

```
Fatal error: Cannot use Kodus\Database\Test\Support as Support because the name is already in use in C:\workspace\test\kodus-db\tests\_support\_generated\UnitTesterActions.php on line 11
```

Of course, yeah, I could just mangle the class-name in one of them as a work-around, but there goes the reason why we had namespaces in the first place :-(

**Comment by Seldaek** [comment]
I have literally no idea what this has to do with composer :)

**Comment by alcohol** [comment]
Yeah me neither..

You'll have to elaborate as to how or why this relates to Composer.

**Comment by mindplay-dk** [comment]
Cripes, SORRY, I meant to post this to codeception!
