### ISSUE TITLE
impossible to set `disable-tls` option

### ISSUE THREAD

**Issue by craue** [composer/composer#5388]
While calling `composer config -g disable-tls true`, it exits with an exception message telling me to set `disable-tls` to true. :boom: :laughing:

This happens with PHP 5.3.3 where the openssl extension is disabled. See [Travis output](https://travis-ci.org/craue/CraueFormFlowBundle/builds/134139553#L168). The exception is also raised when just calling `composer --version` (as seen above).

**Comment by stof** [comment]
Can you add the ``-v`` option to get the stack trace of the exception ?

**Comment by Nek-** [comment]
@craue just set PHP 5.3, I think it's an issue of PHP 5.3.3

**Comment by craue** [comment]
@stof, [done](https://travis-ci.org/craue/CraueFormFlowBundle/builds/134163383#L167).
@Nek-, I'd like to test against 5.3.3 explicitly and [it used to work](https://travis-ci.org/craue/CraueFormFlowBundle/jobs/124930332).

**Comment by alcohol** [comment]
This seems like a bug. I guess a quick work-around for now would be to manually modify `~/.composer/config.json`.

**Comment by craue** [comment]
Great, thank you @Seldaek.

**Comment by china-fengguan** [comment]
php 7.2, same happens.
