### ISSUE TITLE
Hoplessly lost and broken website

### ISSUE THREAD

**Issue by RonPare** [composer/composer#5391]
Somehow I was encouraged to do something this morning I don't know where I went wrong.
But I installed the composer manager in drupal and now my website is completely broke WSOD. My host can't help me, I don't know what to do.

www.modelersguild.com

I tried to disable via db no luck

With the following composer.json:

```json
{
    ...
}
```

When I run this command:

```
composer command -vvv (please include -vvv!)
```

I get this output:

```

```

And I expected this to happen:

**Comment by Seldaek** [comment]
This is really more to do with Drupal  and whatever this composer manager is doing than composer itself I'm afraid.. I think you'd have more luck asking for help in a more relevant place because I have no clue how this composer manager works or what it does :/
