### ISSUE TITLE
Requested package rejected due to constraints

### ISSUE THREAD

**Issue by kelunik** [composer/composer#5397]
With the following composer.json:

```json
{
    "require-dev": {
        "macfja/phar-builder": "dev-events+issue-17"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
}
```

When I run this command:

```
composer update
```

I get this output:

```
Problem 1
    - The requested package macfja/phar-builder dev-events+issue-17 exists as macfja/phar-builder[0.1, 0.2, 0.2.1, 0.2.2, 0.2.3, 0.2.4, dev-events+issue-17, dev-master] but those are rejected by your constraint.

```

And I expected this to happen:

Installation should have worked.

```
 $ composer why-not macfja/phar-builder dev-events+issue-17
There is no installed package depending on "macfja/phar-builder" in versions not matching dev-events+issue-17
```

I guess this could be related to the `+` in the branch name.

**Comment by alcohol** [comment]
Peculiar, not sure if this is solver related or version parsing (the latter can be found in [composer/semver](/composer/semver)). Will investigate in a moment.

**Comment by alcohol** [comment]
Ok, I think I understand what is going on. Since anything after the `+` is considered build metadata, it is stripped off.

So, your version requirement ends up being: `dev-events`.

However it seems that the branch names are not normalized in the same manner, or in other words, build metadata is not stripped. Hence they do not match.

/cc @Seldaek can you confirm this?

**Comment by alcohol** [comment]
So yeah it's a normalizing issue. Not sure what the best solution would be here. I'll let @Seldaek chime in :-)

**Comment by stof** [comment]
@alcohol I think ``dev-*`` versions should be left unchanged. They are not semver versions anyway, so there is no reason to support build metadata in them.

**Comment by alcohol** [comment]
That's what branch normalizing currently does. So we need to adjust version parsing to only strip build metadata if have determined the rest of the string to not be a dev-* type requirement.

So maybe just a change in ordering in here would be sufficient:

https://github.com/composer/semver/blob/master/src/VersionParser.php#L113-L125

**Comment by alcohol** [comment]
I pushed a fix for it, but that breaks an existing test.
I think we can drop that one though, since we are changing the behaviour on purpose.

```
1) Composer\Semver\VersionParserTest::testNormalizeSucceeds with data set "semver metadata" ('dev-master+foo.bar', '9999999-dev')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-9999999-dev
+dev-master+foo.bar
```

**Comment by stof** [comment]
yeah, I think this can be changed

**Comment by Seldaek** [comment]
Yup, seems like a good fix, it's a bit of an edge case anyway, most branches are alpha numerics and -/_, the rest is kinda madness IMO but eh :)

**Comment by kelunik** [comment]
Fix confirmed. :+1:
