### ISSUE TITLE
Can't compute source position

### ISSUE THREAD

**Issue by OskarD** [composer/composer#5400]
Suddenly during my own development, composer just stops working. I enter the command, and the CLI just freezes on the newline until I press CTRL + C and then Y to terminate the batch job.

I tried turning all my programs off, but nothing helped. Restarting my computer did. I could not find any suspicious or related processes running that i could stop.

I was listening to Xdebug 2.4.0 in the background, and suddenly noticed that it was writing out error messages whenever I tried to run the composer command. Here is what it says:
`Can't compute source position. The script 'composer.phar' isn't associated with any text file type.`

I am running Windows 10.

This has happened twice now.

**Comment by OskarD** [comment]
Turns out it stops during execution with Xdebug, and you have to instruct it manually to resume execution. I don't know why this happens. Does anyone know?

**Comment by Seldaek** [comment]
Check your xdebug settings? I guess you might have auto-debugging enabled or something.

**Comment by OskarD** [comment]
I am not very experienced with Xdebug, but it runs through my own programs unless I put break points in them. Why is this different?

**Comment by Seldaek** [comment]
It's just an idea.. I can't know for sure, but from a quick google search it seems this is related to phpstorm not having the mappings for composer. I suspect xdebug auto-connects to phpstorm for debugging and then is blocked until you restart phpstorm (which happens when you reboot). Again, check xdebug settings in php.ini, especially the xdebug.remote_* stuff like remote_autostart.

**Comment by OskarD** [comment]
It runs normally when I "stop listening to PHP Debug Connections" in PhpStorm.

These are the options I have enabled for xdebug:
```
xdebug.default_enable=1
xdebug.remote_enable=1
xdebug.remote_host=localhost
xdebug.remote_port=9000
xdebug.remote_autostart=1
xdebug.profiler_enable=1
xdebug.profiler_output_dir="C:\php\xdebug"
xdebug.idekey="PHPSTORM"
```

**Comment by Seldaek** [comment]
Then disable remote_autostart.. that should fix it. I'm not sure if that'll impact phpstorm debugging though. But it is anyway not related to composer so I'll close this. Sorry but I don't use phpstorm and can't really help much there.

**Comment by OskarD** [comment]
No worries, I understand :) Thanks for helping out!
