### ISSUE TITLE
InstallationManager::uninstall() does not update composer.lock

### ISSUE THREAD

**Issue by weierophinney** [composer/composer#5403]
(Deviating from the normal PR template due to the fact that this is an issue based on usage of the internal API.)

In zendframework/zend-skeleton-installer, we have a class, `Zend\SkeletonInstaller\Uninstaller` which is responsible for removing the plugin from the project installation after initial install. In that class, we have the following (summarized):

``` php
$installer = $composer->getInstallationManager();
$repository = $composer->getRepositoryManager()->getLocalRepository();
$package = $repository->findPackage('zendframework/zend-skeleton-installer', '*');

if (! $package) {
    return;
}

$installer->uninstall($repository, new UninstallOperation($package));
```

This works correctly, and Composer reports it has removed the plugin; moreover, a `composer info` shows that the plugin is not present, and the `vendor/` directory no longer contains the plugin. `vendor/composer/installed.json` does not contain an entry to it, either.

However, `composer.lock` _still contains an entry for it_. And any Composer install, update, or remove operation you invoke after this invokes the subscribers the plugin defines. In terms of the `OptionalPackagesInstaller`, because of how it works on first install, it has no work to do, and this is a no-op; however, for the `Uninstaller`, it invokes the code above, and, again, shows a successful uninstall operation, but with the `composer.lock` left with an entry for the plugin package.

Interestingly, this same plugin uses `Composer\Installer` to _install_ packages, and these are written correctly to it. I'm wondering if:
- First, if `InstallationManager::uninstall()` _should_ be updating the lock file,
- Second, if not, if I should be updating the lock file manually via the `Composer\Package\Locker::setLockData()`, and/or
- Third, if I should be using `Composer\Installer::run()` instead to perform the uninstall operation.

**Comment by weierophinney** [comment]
I've tried the second approach above, manually updating the lock file, using the following:

```php
$packages = [];
$devPackages = [];
$aliases = [];

foreach ($localRepository->getPackages() as $package) {
    if ($package->getName() === 'zendframework/zend-skeleton-installer') {
        continue;
    }

    if ($package instanceof AliasPackage) {
        $aliases[] = $package;
        continue;
    }

    if ($package->isDev()) {
        $devPackages[] = $package;
        continue;
    }

    $packages[] = $package;
}

$platformReqs = $locker->getPlatformRequirements(false);
$platformDevReqs = array_diff($locker->getPlatformRequirements(true), $platformReqs);

$locker->setLockData(
    $packages,
    $devPackages,
    $platformReqs,
    $platformDevReqs,
    $aliases,
    $locker->getMinimumStability(),
    $locker->getStabilityFlags(),
    $locker->getPreferStable(),
    $locker->getPreferLowest(),
    $locker->getPlatformOverrides()
);
```

This appears to work. It might be interesting to create an API to simplify this in the future, however.

**Comment by alcohol** [comment]
I am actually not sure if updating the lock file is the responsibility of the assorted installer classes. Hence I do not know if this is a bug or simple a lack of a feature (and in the latter case, where does it belong?).

**Comment by stof** [comment]
To me, the issue seems that you ask the installer manager to uninstall the package, but you don't remove it from the local repository, and so composer thinks it is still there when locking.

**Comment by weierophinney** [comment]
@stof okay - then how should I go about determining if a package was installed due to a require-dev rule?

**Comment by Seldaek** [comment]
@weierophinney You can't determine require/require-dev state  through the local repository. That's only available at the end of the Installer workflow in the lock file. Right now we don't pass this info along to the script events. It's technically available at the point where operations are being executed though..

As for the initial problem of updating the lock, the Installer class updates the lock after it's done but BEFORE post-update/install-cmd fires, so I am thinking maybe you trigger the uninstall too late and therefore the lock isn't updated until next time you run an update?

**Comment by Seldaek** [comment]
Auto-closing as this hasn't been updated in over 6months. If there is a real bug to consider please let us know.
