### ISSUE TITLE
The requested PHP extension mcrypt is missing

### ISSUE THREAD

**Issue by sasuke6** [composer/composer#5405]
When I run this command:

```
composer create-project laravel/laravel laravel5 5.0.22
```

no matter what the laravel version
I get this output:

```
Created project in laravel5
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laravel/framework v5.0.16 -> satisfiable by laravel/framework[v5.0.16].
    - laravel/framework v5.0.16 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

And I expected this to happen:
I can install the laravel by the composer,but I can use it successfully before.

At the same time I run lots of command:

```
brew install php56-mcrypt 
```
But the PHP extension is still missing.By the way,my system is Mac OS X 10.11.4,I want to use the native php

**Comment by stof** [comment]
well, if you are using the native php, ``brew install php56-mcrypt`` will not give you the mcrypt extension, as this will install it in the PHP managed by brew, not in the native php.

**Comment by sasuke6** [comment]
@stof Why do I have this problem?I can install the laravel by composer before,but I deleted it later.When I want to use it again,there is a question now.And I search on google and stackoverflow for many times,however it make no sense.

**Comment by alcohol** [comment]
@sasuke6 the native php doesn't come with a `/etc/php.ini`, only a `/etc/php.ini.default`. So it seems to me that you copied/created this file. You have to make sure mcrypt is enabled in your `php.ini`. Afterwards, check the output of `/usr/bin/php -m` and look in the list for mcrypt to verify that it is loaded.

**Comment by sasuke6** [comment]
@alcohol Yes,I copy the `/etc/php.ini.default`,and the `php.ini` does not have `mcrypt.so` file,I use the homebrew to install the mcrypt,but there is no such file in the php extension so that I can not launch.Obviously,mcrypt is not loaded in `/usr/bin/php -m` list.

**Comment by alcohol** [comment]
I recommend you use the brew installed php binary, not the default. If you insist on using the default, you will have to compile and install mcrypt yourself. Good luck with that :-)

**Comment by sasuke6** [comment]
@alcohol Thanks for your advice,I will try to use the homestead to run laravel.
