### ISSUE TITLE
Composer Update

### ISSUE THREAD

**Issue by nmallepally** [composer/composer#5406]
Hello,
I was doing upgrade to magento 2.1 version, and i have changed my composer.json file to 2.1 version and ran composer update .. list of errors it showed me. below. I have attached my composer.json file as well.
[composer.txt](https://github.com/composer/composer/files/297499/composer.txt)

C:\xampp\htdocs\baby>composer update
Loading composer repositories with package information
    Authentication required (repo.magento.com):
      Username: navyakrishnamallepally@ie.tricel.eu
      Password: This program is blocked by group policy. For more information, contact your system administrator.
Invalid credentials for 'https://repo.magento.com/packages.json', aborting.
https://repo.magento.com could not be fully loaded, package information was loaded from the local cache and may be out of date
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - The requested package magento/product-community-edition 2.1.0 exists as magento/product-community-edition[2.0.4, 0.42.0-beta7, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.5, 2.0.6, 2.0.7, 2.1.0-rc1] but these are rejected by your constraint.

**Comment by alcohol** [comment]
I see multiple issues here, none of which I can solve for you. You will have to do some more debugging yourself :-)
