### ISSUE TITLE
Fallback to source url from composer.json

### ISSUE THREAD

**Issue by Programie** [composer/composer#5410]
We just moved from one Git server to another which has different HTTPS and SSH URLs.

Now if I try to install a project which requires a few dependencies from our internal Satis instance (which already get's the packages from the new Git server), the installation failed because Composer still tries to clone the dependencies from the old Git server which does not provide the packages anymore.

I've already did some investigations and saw that the source URL of each dependency is saved in the composer.lock file. Of course I could simply update the composer.lock file so it contains the new URLs, but in my case I want to install a previous version of the project and I can't change the composer.lock of that one.

Is it possible to add a fallback to Composer so it would try to fetch the dependency from the new URL instead of the one defined in the composer.lock if that one failed?

**Comment by stof** [comment]
well, when doing a ``composer update``, Composer should be updating the URL of these packages (unless your composer is older than 1.0.0).
If you just run ``composer install`` (with a lock file), composer has no way to know the change, as it only reads the lock file and won't ever contact your satis repo.

**Comment by Programie** [comment]
But why don't try to fallback to the composer.json and use Satis if the source can't be downloaded using the URL from the composer.lock?

**Comment by stof** [comment]
Because using Satis would mean performing an update rather than performing an install. And ``composer install`` with a lock file is expected to install the locked dependencies, not to switch to an update instead (if you want it to update dependencies, you can call ``composer update`` explicitly instead of asking composer to create WTF moments for all other users)

**Comment by Programie** [comment]
I'm not asking for automatically updating the package to a different revision/version. Composer should just try to download the same revision from the new URL (maybe output a warning saying that it is now trying to download the package from the other URL).

If that would really change the expected behaviour of Composer: Why not just add an option like --no-lock to the install command?

I think I'm not the only one who might move repositories from one host to another and wants to avoid breaking older releases of applications just because the URL of a dependency is not available anymore. At least we could fall back to the URL provided by Satis (or some other Composer repository) and try to fetch the dependency package in the same version as defined in the composer.lock file.

**Comment by stof** [comment]
@Programie ignoring the composer.lock file in the install command would make it run exactly what the update command does

**Comment by stof** [comment]
and regarding fetching the same version from Satis or Packagist, this will also break in case you were using a dev version (as satis/packagist will not have the metadata anymore for this commit in case the branch was updated).

If you want to be able to move repositories without breaking existing releases, the best way is to ensure the old URL stay valid and redirects to the new location (this is what Github does for instance)

**Comment by Programie** [comment]
OK, then that would be the only solution.

Anyway, thanks for your help. 🙂
