### ISSUE TITLE
using composer with proxy authentication

### ISSUE THREAD

**Issue by stanislavivanovit** [composer/composer#5411]
With the following composer.json:

``` json
{
    ...
}
```

When I run this command:

**composer diagnose** 

I get this output:

Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: Warning: Accessing packagist.org over h                                                                                                                ttp which is an insecure protocol.
FAIL
[Composer\Downloader\TransportException] The "http://packagist.org/packages.json                                                                                                                " file could not be downloaded (HTTP/1.1 407 Proxy Authentication Required)
Checking https connectivity to packagist: FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.jso                                                                                                                n" file could not be downloaded: failed to open stream: Cannot connect to HTTPS                                                                                                                 server through proxy
Checking HTTP proxy: FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.jso                                                                                                                n" file could not be downloaded: failed to open stream: Cannot connect to HTTPS                                                                                                                 server through proxy
Checking HTTP proxy support for request_fulluri: FAIL
Unable to assess the situation, maybe packagist.org is down (The 'http://packagi                                                                                                                st.org/packages.json' URL could not be accessed: HTTP/1.1 400 Bad Request
)
Checking HTTPS proxy support for request_fulluri: FAIL
Unable to assess the situation, maybe github is down (The "https://api.github.co                                                                                                                m/repos/Seldaek/jsonlint/zipball/1.0.0" file could not be downloaded: failed to                                                                                                                 open stream: Cannot connect to HTTPS server through proxy)
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit"                                                                                                                 file could not be downloaded: failed to open stream: Cannot connect to HTTPS se                                                                                                                rver through proxy
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB                                                                                                                723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E32                                                                                                                8C AD90147D AFE50952
OK
Checking composer version:

  [Composer\Downloader\TransportException]
  The "https://getcomposer.org/versions" file could not be downloaded: failed
   to open stream: Cannot connect to HTTPS server through proxy

And I expected this to happen:

We use a proxy which requires authentication, and when we run composer behind that proxy it cannot connect to github.com, packagist.org/.

**When we test without authentication everything works, but we wish to use proxy authentication.
Is there a way we can set up composer to use proxy authentication.
and reach the desired outcome:** (bellow is the output of the command "composer diagnose" without proxy authentication)

$ composer diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: Warning: Accessing packagist.org over http which is an insecure protocol.
OK
Checking https connectivity to packagist: OK
Checking HTTP proxy: OK
Checking HTTP proxy support for request_fulluri: OK
Checking HTTPS proxy support for request_fulluri: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK

?

Thank you

**Comment by stof** [comment]
Well, you should configure the ``HTTP_PROXY`` env variable with the proper settings for your proxy

**Comment by stanislavivanovit** [comment]
Thank you for the quick reply,

I have configured global environmental variables in windows for http_proxy and https_proxy. Should they be set in composer specifically as well?
Please note that I am not a developer using this software, I’m a helpdesk agent helping a developer set this software on his workstation.
Can you give me an example where exactly http_proxy env should be set, what parameters it takes and in what format?

-Stani

**Comment by alcohol** [comment]
https://getcomposer.org/doc/03-cli.md#http-proxy-or-http-proxy

It takes a URL (which in turn can contain a username and password also).

**Comment by stanislavivanovit** [comment]
I have tried 
export http_proxy="http://username:password@your_proxy:your_port"
export https_proxy="https://username:password@your_proxy:your_port"
export http_proxy=http://username:password@your_proxy:your_port
export https_proxy=https://username:password@your_proxy:your_port

but the outcome is the same:

$ composer diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: Warning: Accessing packagist.org over http which is an insecure protocol.
OK
Checking https connectivity to packagist: FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Failed to enable crypto
failed to open stream: operation failed
Checking HTTP proxy: FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Failed to enable crypto
failed to open stream: operation failed
Checking HTTP proxy support for request_fulluri: OK
Checking HTTPS proxy support for request_fulluri: FAIL
Unable to assess the situation, maybe github is down (The "https://api.github.com/repos/Seldaek/jsonlint/zipball/1.0.0" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Failed to enable crypto
failed to open stream: operation failed)
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Failed to enable crypto
failed to open stream: operation failed
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version:

  [Composer\Downloader\TransportException]
  The "https://getcomposer.org/versions" file could not be downloaded: SSL op
  eration failed with code 1. OpenSSL Error messages:
  error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
  Failed to enable crypto
  failed to open stream: operation failed

**Comment by alcohol** [comment]
What kind of proxy is it?

**Comment by stanislavivanovit** [comment]
squid

**Comment by stanislavivanovit** [comment]
Can anybody help?

I have set global environmental variable for http and https_proxy with value our_proxy_ip:port (this proxy requires authentication)

this is the output when I run composer create-project --prefer-dist laravel/laravel blog
![envirometnal variable porxy with authentication](https://cloud.githubusercontent.com/assets/19794128/15961665/97717ed0-2f0e-11e6-8512-3e3130408a43.JPG)

I then tried with 
export http_proxy=http://username:password@your_proxy:your_port
export https_proxy=https://username:password@your_proxy:your_port

![export proxy without quotes](https://cloud.githubusercontent.com/assets/19794128/15961683/af8d1114-2f0e-11e6-97d9-bbe23aa0a157.JPG)

and then with 
export http_proxy="http://username:password@your_proxy:your_port"
export https_proxy="https://username:password@your_proxy:your_port"

![export proxy with quotes](https://cloud.githubusercontent.com/assets/19794128/15961694/c66f5de2-2f0e-11e6-92e8-5c736c89567c.JPG)

this is the output when I set env var http and http_proxy to a proxy with no authentication
![env var proxy with no auth](https://cloud.githubusercontent.com/assets/19794128/15961819/a8854dae-2f0f-11e6-9650-0a7f8de19038.JPG)

both proxies with and without authentication are squid proxies.

**Comment by alcohol** [comment]
I would guess that your proxy setup does not support https. You can force composer to default to http in that case, albeit it goes against all recommendations.

**Comment by faridmovsumov** [comment]
I have the same problem :(

**Comment by stanislavivanovit** [comment]
@faridmovsumov, not yet.

**Comment by mcarbonneaux** [comment]
notice that fopen http wrapper don't support proxy authentification with https...
it's patched in 5.4.1RC1 : 
https://github.com/php/php-src/commit/aa5055ba0fa9ea35b8b2144694602520d07d3b5d

**Comment by 7i4g0** [comment]
Hello there. Try this:
C:\xampp\htdocs\myproject\> SET HTTP_PROXY=http://username:password@proxy.yourdomain.com:8080 && php composer.phar create-project laravel/laravel --prefer-dist

I needed put the _composer.phar_ file into the same folder of the project.

**Comment by sasclar** [comment]
Hello,
Setting "HTTP_PROXY=http://username:password@proxy.yourdomain.com:port" on windows 7 at user level worked for me

**Comment by Seldaek** [comment]
Auto-closing this as it's marked as support request and has not received any update in a long time.

**Comment by mcarbonneaux** [comment]
in composer.php and in Composer/Util/StreamContextFactory.php

when read password they use urldecode before base64 encoding... 
```
            // handle proxy auth if present
            if (isset($proxy['user'])) {
                $auth = urldecode($proxy['user']);
                if (isset($proxy['pass'])) {
                    $auth .= ':' . urldecode($proxy['pass']);
                }
                $auth = base64_encode($auth);
```
the password with special char like `+` not work without encoding it in HTTP_PROXY variable not work...

**Comment by mcarbonneaux** [comment]
the php stream in ssl use by default STREAM_CRYPTO_METHOD_SSLv23_CLIENT in place of STREAM_CRYPTO_METHOD_TLS_CLIENT in : 
- ext/standard/http_fopen_wrapper.c
- ext/standard/ftp_fopen_wrapper.c 

this depend on version of openssl you use, but old one cannot abel to connect on ssl server that refuse sslv2 and v3...

on recent version of php you are abel to configure with the context the default protocol but on old one your are not abel to do it...

and the https://getcomposer.org/ as disabled sslv2 and v3...

in that way you are oblige to use --disable-tls for that...

why not use curl extension in place of php stream ? in that way you are abel to use correctly openssl protocol by configuration... and also the proxy option...

**Comment by mcarbonneaux** [comment]
Make to have the choice to use stream or curl, and eventually use curl or stream by default depending on version of php

**Comment by alcohol** [comment]
This is open source software. We don't have to do anything. But you're welcome to contribute.

**Comment by sealionking** [comment]
if you do not have to do anything，dont pub your shit，eat only yourself.

what a horrible open source sb

**Comment by sealionking** [comment]
what a shit and what a shit stupid
