### ISSUE TITLE
Don't execute scripts if nothing was installed or updated

### ISSUE THREAD

**Issue by RobertLangore** [composer/composer#5412]
When I run this command (inside a [Sylius](https://github.com/Sylius/Sylius) installation):
composer update

I get this output:
Loading composer repositories with package information
Updating dependencies (including require-dev)
**Nothing to install or update**

Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

 // Clearing the cache for the dev environment with debug
 // true

 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.

> Symfony\Cmf\Bundle\CreateBundle\Composer\ScriptHandler::downloadCreateAndCkeditor
Download or update create
Download or update ckeditor
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets

 Installing assets as hard copies.

 ---- ------------------------------ ----------------
       Bundle                         Method / Error
 ---- ------------------------------ ----------------
  OK   SyliusAttributeBundle          copy
  OK   SyliusShippingBundle           copy
  OK   SyliusReportBundle             copy
  OK   SyliusPromotionBundle          copy
  OK   SyliusAddressingBundle         copy
  OK   SyliusUserBundle               copy
  OK   SyliusMetadataBundle           copy
  OK   SyliusReviewBundle             copy
  OK   SyliusWebBundle                copy
  OK   SyliusResourceBundle           copy
  OK   CmfCreateBundle                copy
  OK   FrameworkBundle                copy
  OK   JMSTranslationBundle           copy
  OK   WhiteOctoberPagerfantaBundle   copy
 ---- ------------------------------ ----------------

 ! [NOTE] Some assets were installed via copy. If you make changes to these
 !        assets you have to run this command again.

 [OK] All assets were successfully installed.

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile

Since in this case there's nothing to install or update, it's not neccessary to execute the post-update scripts (which take some time and resources).

**Comment by alcohol** [comment]
There is no way for Composer to know if it should run those scripts or not. Just because nothing was installed or updated does not automatically mean the user does not want to run anything. If the user does not want to run anything, he can pass `--no-scripts`.

**Comment by RobertLangore** [comment]
Hi,

There is no way for Composer to know if it should run those scripts or not.
> But composer is giving the message "Nothing to install or update", so it does know.

Just because nothing was installed or updated does not automatically mean the user does not want to run anything. If the user does not want to run anything, he can pass --no-scripts.
> I didn't mean to archieve this (not run the scripts with --no-scripts). I meant: do not run the scripts if there are no installs or updates:
- run `composer update`
- composer checks if there where installs or updates:
  - if yes: execute post-install and post-update scripts
  - if no: don't do anything. If nothing was installed or updated, there is no need to regenerate the cache, re-install assets or perform other operations.

If the author of the package or the user wants to run those scripts anyway, there could be an option in the composer.json or via the `composer update`: always-run-scripts.

Or, other solution, add an option to `composer update` to not run the scripts **if** there are no installs or updates: --no-scripts-if-no-update.

I hope it's clear.


Another solution can be (usable now) using `composer update --dry-run` to see if there are updates, and if yes run `composer update`.

**Comment by kamilsk** [comment]
@alcohol, what you think if `Script\Event` will have some flag about this state? I saw that InstallerManager has private `notifiablePackages`

```php
            $installer = $this->getInstaller($initialType);
            $installer->update($repo, $initial, $target);
            $this->markForNotification($target);
```

> But composer is giving the message "Nothing to install or update", so it does know.

Yes, it know, but do not store this knowledge

`\Composer\Installer::doInstall`
```php
        // execute operations
        if (!$operations) {
            $this->io->writeError('Nothing to install or update');
        }

        $operations = $this->movePluginsToFront($operations);
        $operations = $this->moveUninstallsToFront($operations);
```

And I do not know how it is difficult to add support this. Maybe @Seldaek can help to answer this question.

@RobertLangore 

`post-install-cmd` and `post-update-cmd` are just a notification upon completion of the commands. They say nothing that some package was updated https://getcomposer.org/doc/articles/scripts.md#command-events.

Alternative use `linux way` as example:
alias = "composer install | check stdout | do something"
`check stdout` is simple grep for "Nothing to install or update" and return 1 - no updates, 0 - has updates

**Comment by roldan** [comment]
Hi @RobertLangore ,

I've resolved hooking in "post-dependencies-solving" event and in my script I do something like this:

`
use Composer\Installer\InstallerEvent;

class GenerateCommitFileHandler {

    /**
     * @param InstallerEvent $event
     */
    public static function postInstallCmd(InstallerEvent $event){
        $operations = $event->getOperations();
        foreach($operations as $operation){
            // do anything with each operation operation...
        }
    }
}
`
