### ISSUE TITLE
Local changes not detected

### ISSUE THREAD

**Issue by falvarez-bitban** [composer/composer#5413]
With the following composer.json:

```json
{
  "name": "mycompany/myproject",
  "description": "My project",
  "minimum-stability": "stable",
  "require": {
    "mycompany/myframework": "vx.y.z"
  },
  "repositories": [
    {
      "type": "vcs",
      "url": "git@mygitserver:myframework.git"
    }
  ]
}
```

When I run this command:

```
composer update
```

It runs as expected, an stores my company framework under vendor/mycompany/myframework.

Problem arises when I am developing and may change the framework locally. For example:

```
cd vendor/mycompany/myframework
git checkout x'.y'.z'
```

I have no way to know that things have changed. If I run this command from the project root:

```
composer status
````

I get this output:

```
No local changes
```

It seems to detect only file changes, but not when Git HEAD has moved.

**Comment by alcohol** [comment]
That's why you should use the `path` type locally.
