### ISSUE TITLE
Composer Issue on Windows 10

### ISSUE THREAD

**Issue by funkysunil** [composer/composer#5415]
I have following issue with composer installation
![composererr](https://cloud.githubusercontent.com/assets/10059479/15894520/ea6b60f4-2da3-11e6-8982-834247862e17.PNG)
 on my windows 10 32 bit machine

**Comment by kamilsk** [comment]
please close https://github.com/composer/composer/issues/5414, and I think best location for this issue type here https://github.com/composer/windows-setup

**Comment by alcohol** [comment]
Yes please report this issue @ https://github.com/composer/windows-setup
