### ISSUE TITLE
composer install attempts to run pre-update-cmd

### ISSUE THREAD

**Issue by jhoff** [composer/composer#5416]
After recently updating composer, when running `composer install` on a project with no composer.lock or vendor folder, composer is attempting to run the pre-update-cmd. Is this expected behavior?

-bash-4.1$ composer install
> php artisan clear-compiled
PHP Warning:  require(/var/local/www/production/pmo-portal/releases/release_484/bootstrap/../vendor/tsotools-laravel-packages/framework-utils/src/Helpers/Helpers.php): failed to open stream: No such file or directory in /var/local/www/production/pmo-portal/releases/release_484/bootstrap/autoload.php on line 16
PHP Fatal error:  require(): Failed opening required '/var/local/www/production/pmo-portal/releases/release_484/bootstrap/../vendor/tsotools-laravel-packages/framework-utils/src/Helpers/Helpers.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/local/www/production/pmo-portal/releases/release_484/bootstrap/autoload.php on line 16
Script php artisan clear-compiled handling the pre-update-cmd event returned with error code 255

-bash-4.1$ composer -V
> Composer version 1.2-dev (08ef916beded8c738be11acc4f463c450e277d64) 2016-06-06 10:22:06

**Comment by stof** [comment]
yes it is expected, because ``composer install`` without a lock file is actually exactly the same than ``composer update``. In pre-1.0 releases, the hook being run was inconsistent with the actual behavior of the command, and this was fixed before reaching stable.
