### ISSUE TITLE
First time git clone

### ISSUE THREAD

**Issue by davidsteinsland** [composer/composer#5419]
I'm running `composer` via docker and mounts `~/.ssh/id_rsa` into the container. This is allows me to install any private packages I may have in `composer.json`.

However, when composer tries to `git clone` against e.g. `github.com` the first time, this message appears:

```
The authenticity of host 'github.com (192.30.252.121)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? 
```

The result is that the command hangs, and eventually the build system kills the command because it "exceeded the timeout of 300 seconds."

I _can_ probably mount a `known_hosts` file into the container, but I wondered if there was some other work-around?

```
composer install --trust-ssh-hosts=github.com
```

**Comment by alcohol** [comment]
> I'm running composer via docker and mounts ~/.ssh/id_rsa into the container. This is allows me to install any private packages I may have in composer.json.

I would recommend using agent forwarding instead:
```
--volume $SSH_AUTH_SOCK:/run/ssh-agent.sock --env SSH_AUTH_SOCK=/run/ssh-agent.sock
```

---

Regarding that warning, you can disable it using:

```
# ~/.ssh/config
Host *
   StrictHostKeyChecking no
   UserKnownHostsFile=/dev/null
```

**Comment by allella** [comment]
To @alcohol 's point, you may want to look into using SSH agent forwarding so you're not putting your private key into a container.  I have no experience with Docker + SSH agent forwarding, but normally all you have to do is turn it on in your SSH config

```
# ~/.ssh/config
Host *
    ForwardAgent yes

```

**Comment by alcohol** [comment]
@allella that only forwards your agent when you connect to another machine using SSH. This will not work during a Docker build process. You need to mount your ssh agent socket inside the container instead, as I suggested :-)

**Comment by Seldaek** [comment]
Auto-closing as this hasn't been updated in over 6months and is marked as a support request. If there is a real bug to consider please let us know.
