### ISSUE TITLE
New feature: Upstream repo

### ISSUE THREAD

**Issue by PhilLello** [composer/composer#5426]
Hi all,

I'm looking at writing a patch (or a plugin) to ease keeping forks in sync with upstream code, and would like some feedback before going too fair into this. Basic architecture will be to add upstream data to a composer.json, then one or more new commands to bring things into sync.

**composer.json**
```
...
                "source": {
                    "type": "git",
                    "url": "https://github.com/dunlop-lello/moodle.git",
                    "upstream": {
                        "url": "https://github.com/moodle/moodle.git"
                    },
                    "reference": "master"
                }
... 
```
Upstream will optionally take a type and reference, although I currently have no intention of taking on the work to cope with anything other than git => git, and don't see much use for alternate references.

I think the logical approach is to download the repo into a separate work area so multiple branches can be synchronised, and to rebase branches against upstream rather than merging - I like to keep my customisations at the top of the commit log.

I have mixed feelings on how to handle tags here, as my initial use-case is to add missing composer metadata. Replacing upstream tags with ones that include a valid composer.json seems wrong from a git point of view, but is probably the best way to avoid confusion over versions.

**Comment by alcohol** [comment]
Can you explain the use-case behind this? Cause it sounds a lot like a [XY problem](http://xyproblem.info) to me.

**Comment by PhilLello** [comment]
Sure, it's fairly simple.

Repo A (e.g. https://github.com/moodle/moodle) is the official project (upstream), and I want to track everything that happens there.

Repo B (e.g. https://github.com/dunlop-lello/moodle) is my version (origin), and should include everything from Repo A with a few local patches.

Repo C is my checkout of repo B where I do my actual edits.

Repo A and B are operated by separated organisations, and pushes to repo A are not an option for developers working on repo B.

For a patch to be accepted by repo A, they need to cherry-pick changes from repo B. Although Repo B is a seperate repo, it's best to think of it as a long-lived set of feature branches kept up to date via git fetch/rebase. Resolving conflicts is always handled by the developers on repo B.

When I run composer status on a project on my machine (my changes in repo C and only ever pushed to repo B), I want to know two things:

- Do I have changes relative to repo B?
- Does repo A have any changes that haven't moved into repo B? e.g. can repo A cherry-pick my work from repo B?

When I run composer <to-be-named-plugin-command> locally (repo C), I want to:

- Pick up new/deleted branches from repo A ready to push to repo B.
- Rebase repo B branches against the upstream branch on repo A, and manually fix any conflicts.

There will likely be some organisation-specific changes in repo B that never make it into repo A. There will never be changes in repo A that are not wanted in repo B (or if there were, they'd be taken care of as reverts rather than skipping the upstream change).

**Comment by alcohol** [comment]
It sounds like you should look into Git tooling, not Composer. This goes far beyond the scope of what Composer tries to solve.
