### ISSUE TITLE
composer require and errors during post-update scripts

### ISSUE THREAD

**Issue by bamarni** [composer/composer#5429]
I had a composer unrelated issue in my application's post-update script and noticed that the dependencies were left in an inconsistent state.

For example :
```json
{
     "scripts": {
         "post-update-cmd": [
             "false"
         ]
     }
}
```

```
$ composer require symfony/yaml:^3.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing symfony/yaml (v3.1.0)
    Loading from cache

Writing lock file
Generating autoload files
> false
Script false handling the post-update-cmd event returned with error code 1

Installation failed, reverting ./composer.json to its original content.
```

After this error the dependency is still installed, the composer.lock is also updated but the composer.json misses the requirement. Should we change the behaviour for those cases?

**Comment by alcohol** [comment]
Composer does not do transactional/atomic operations. We also don't plan to support this.
