### ISSUE TITLE
GitHubDriver: Missing sanity checks on url

### ISSUE THREAD

**Issue by PhilLello** [composer/composer#5430]
As part of https://github.com/dunlop-lello/moodle-composed I have a plugin-provided repository that parses an upstream JSON feed and picks out repositories.

There's some dirty data in there, meaning I'm occasionally creating a VcsRepository against URLs such as https://github.com/jleyva/moodle-assignment_rtcollaboration/zipball/MOODLE_19_STABLE, and the driver ends up trying to parse the zip at https://api.github.com/repos/jleyva/moodle-assignment_rtcollaboration/zipball/MOODLE_19_STABLE as JSON.

I'll put some URL cleansing logic in my plugin, but I think this should be handled better... somehow.

As to what the better approach is, I'm not sure. I can think of:

  - Trim github urls down to owner/repo and ignore anything else
  - Tighten the pattern match for github urls and make VcsRepository::getDriver() return null

Both of these approaches assume github won't start doing more tiers, which would probably break a ton of code in the wild.

**Comment by stof** [comment]
the question is why you are adding a VCS repository pointing to a zipball ? this will never work (even if we tighten the pattern match, other drivers won't support it and so composer will still break).

In my opinion, you should fix things on your side, to avoid adding such vcs repository

**Comment by alcohol** [comment]
Sounds more like a user error to me (configuration, specifically). Composer cannot fix every little mistake people make.

**Comment by PhilLello** [comment]
I don't control the upstream feed. Cleansing it is my plugin's
responsibility, but better error detection for bad urls in the VcsDriver
would be sensible.
