### ISSUE TITLE
Possible bug in git version detection

### ISSUE THREAD

**Issue by Kaemmelot** [composer/composer#5431]
Hey,

I already wrote on [StackExchange](https://stackoverflow.com/questions/37773914/local-path-repository-doesnt-see-vcs-version-information), but as I now looked deeper into my problem I think it could be a bug or should at least have an improvement.

**What am I trying to do?**
I saw it's now possible to setup a local development without any plugins and with symlinking, so I wanted to try this.
I setup two projects: [Project1](https://github.com/Kaemmelot/test-php-project1) and [Project2](https://github.com/Kaemmelot/test-php-project2).
Project1 uses Project2. In Project2 is no version information within the `composer.json`, but in the git tags.
I now tried to get this example running, and created a `config.json` within the composer folder:
```
{
    "repositories": [
        {
            "type": "path",
            "url": "W:\\Temp\\php-project2"
        }
    ]
}
```

But when I now run `composer update -vvv` this happens:

> Reading ./composer.json
> Loading config file P:\Composer/config.json
> Loading config file P:\Composer/auth.json
> Loading config file ./composer.json
> Checked CA file C:\Users\Username\AppData\Local\Temp\composer-cacert-bcf331364fef73d53e4368ba519a6c3fcb21ea7836c3d8efad4ec32731e8152a.pem: valid
> Executing command (W:\Temp\php-project1): git branch --no-color --no-abbrev -v
> Failed to initialize global composer: Composer could not find the config file: P:\Composer/composer.json
> To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
> Running 1.1.2 (2016-05-31 19:48:11) with PHP 7.0.0 on Windows NT / 10.0
> You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
> Loading composer repositories with package information
> Executing command (W:\Temp\php-project2\): git branch --no-color --no-abbrev -v
> Executing command (W:\Temp\php-project2\): git log -n1 --pretty=%H
> Downloading https://packagist.org/packages.json
> Writing P:\Composer/cache/repo/https---packagist.org/packages.json into cache
> Updating dependencies (including require-dev)
> Reading P:\Composer/cache/repo/https---packagist.org/p-provider-2013.json from cache
> Reading P:\Composer/cache/repo/https---packagist.org/p-provider-2014.json from cache
> Reading P:\Composer/cache/repo/https---packagist.org/p-provider-2015.json from cache
> Reading P:\Composer/cache/repo/https---packagist.org/p-provider-2015-07.json from cache
> Reading P:\Composer/cache/repo/https---packagist.org/p-provider-2015-10.json from cache
> Reading P:\Composer/cache/repo/https---packagist.org/p-provider-2016-01.json from cache
> Downloading http://packagist.org/p/provider-2016-04%2409edaafe7521653bf15f34e662d0cb93750fc642e0fe9396c88de5d02828f21e.json
> Writing P:\Composer/cache/repo/https---packagist.org/p-provider-2016-04.json into cache
> Reading P:\Composer/cache/repo/https---packagist.org/p-provider-archived.json from cache
> Downloading http://packagist.org/p/provider-latest%249c081f98efff178b2bcde2bce95521cab23447016b1ff9c363ca3ea06b53b75e.json
> Writing P:\Composer/cache/repo/https---packagist.org/p-provider-latest.json into cache
> Resolving dependencies through SAT
> Dependency resolution completed in 0.001 seconds
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested package test/php-project2 could not be found in any version, there may be a typo in the package name.
> 
> Potential causes:
>  - A typo in the package name
>  - The package is not available in a stable-enough version according to your minimum-stability setting
>    see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
> 
> Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**What did I expect?**
The [documentation](https://getcomposer.org/doc/05-repositories.md#path) states this:

> If the package is a local VCS repository, the version may be inferred by the branch or tag that is currently checked out. Otherwise, the version should be explicitly defined in the package's composer.json file.

I therefore expected, that I can use version tags without the `composer.json` entry for versions.

After debugging composer I saw, that the VersionParser returns a `9999999-dev` for the master branch, which is then changed to `dev-master` as version. `dev-master` doesn't exist and the tags are ignored by the VersionGuesser.

Hope someone can help me with this.

**Comment by rquadling** [comment]
I found I had to add a require to my local composer.json, rather than use the command line.

https://github.com/composer/composer/issues/5427

I also had to make sure all dependencies for Phinx were installed.

**Comment by alcohol** [comment]
> `dev-master` doesn't exist and the tags are ignored by the VersionGuesser.

You don't have a `master` branch?

**Comment by Kaemmelot** [comment]
I have a master branch and this branch contains tags as version information. But this branch is the only branch I have and composer doesn't look at those tags I added and it doesn't use the master branch neither.
You can take a look on my example projects, I linked them above.
>  [Project1](https://github.com/Kaemmelot/test-php-project1) and [Project2](https://github.com/Kaemmelot/test-php-project2)

Maybe I got this wrong and I should use it different to get a symlink to project2, that's why I'm here ;)

@rquadling I don't see your point, sorry. Have a look at my [composer.json](https://github.com/Kaemmelot/test-php-project1/blob/master/composer.json) for my first project.

**Comment by alcohol** [comment]
Path does not look at tags. It simply looks at what you currently have checked out. If that is the master branch, then it is detected as `dev-master`, and you should use `dev-master` as your requirement. If you want to require a specific tag, then use the VCS repository type instead.

**Comment by Kaemmelot** [comment]
With your answer I get this idea now, thank you.

Can you give me an advice than how to achieve the situation that composer uses the version tags as it does now in my example projects but always uses symlinking in my local development only?
I tried to use this, because I have multiple projects with the same problem and I wanted to use some kind of config like `"url": "W:\\Temp\\php-*"` to automatically change this behaviour for all of them.
I would prefer a solution that doesn't change the behaviour for other users/devs, works for all projects the same and it would be nice if I don't have to change this in the projects  `composer.json`. Is this possible?

Thank you very much for your fast answers so far.

**Comment by alcohol** [comment]
It's not possible to combine tags with symlinks, as a symlink cannot guarantee it always points to the right tag.

What you are asking for is simply not possible.

**Comment by Kaemmelot** [comment]
I'm sorry, that was not what I meant.
I'm looking for something to let composer see, that project2 is currently on a valid version (based on tags), so composer symlinks to this folder or to ignore the required version within the project1s `composer.json` and use a symlink to project2 instead. But any of that without adding something like `"version": "0.3.0"` to the `comoser.json` of project2 and if possible not making changes in the `composer.json` of project1, that would break it for others. Some kind of config value to force using the local version of project2 when found.

I don't understand why composer creates a symlink when `composer.json` of project2 contains this `"version"` entry, but desn't use a symlink, when this version (as tag) is checked out without any further changes. Where is the difference? And why can't I use a symlink (maybe with a parameter "forced") in the last case?
I hope I described my problem better.

**Comment by alcohol** [comment]
I do not quite understand what you mean. Composer will recognize a tag if it is currently checked out. Works as expected:

```
rob@macbookpro /srv/git/iso3166 (master) $ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
rob@macbookpro /srv/git/iso3166 (master) $ git tag
1.0.0
1.0.1
1.0.2
1.0.3
1.0.4
2.0.0
2.1.0
2.1.1
2.1.2
2.1.3
2.2.0
3.0.0
4.0.0
4.1.0
rob@macbookpro /srv/git/iso3166 (master) $ git checkout 2.2.0
Note: checking out '2.2.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 781dc2b... Merge pull request #1 from edvinasme/update-lithuania-to-eur
rob@macbookpro /srv/git/iso3166 (781dc2b) $ cd /tmp
rob@macbookpro /tmp $ cat composer.json
{
    "repositories": [{
        "type": "path",
        "url": "/srv/git/iso3166"
    }],
    "require": {
        "alcohol/iso3166": "^2.0"
    }
}
rob@macbookpro /tmp $ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing alcohol/iso3166 (2.2.0.0)
    Symlinked from /srv/git/iso3166

Writing lock file
Generating autoload files
```

**Comment by Kaemmelot** [comment]
Thank you very much for you patience, I now see my fault from your example.

The tag is only used when HEAD is detached from it. When I checked out the latest tag on my master, my software (SourceTree) always checked out the master branch instead. Even though master and this tag point at the same commit, checking out a tag is different and composer only accepts it when the tag is checked out.
Stupid me, used git for quite a time and still didn't know this important difference.
