### ISSUE TITLE
Issue resolving cyclic dependencies in a library after cloning tagged version of a repo

### ISSUE THREAD

**Issue by gorkalaucirica** [composer/composer#5432]
This problem is mainly related to travis workflow, as it clones the repo as follows to test run tests over a specific tagged version of a repository:

```
git clone --depth=50 --branch=v1.0.0 https://github.com/BenGorUser/SymfonyRoutingBridgeBundle.git 
```

Our [SymfonyRoutingBridgeBundle](https://github.com/BenGorUser/SymfonyRoutingBridgeBundle) has a cyclic dependency with [BenGorUserBundle](https://github.com/BenGorUser/User) but it does not resolve it well as you can see in the following travis build:

https://travis-ci.org/BenGorUser/SymfonyRoutingBridgeBundle/builds/137440803

The issue is that the repository requires `bengor-user/user-bundle: ^1.0` but takes the cloned repo's version as `dev-1d2b4a80112c63750e814fea1ccb2281d399dacf` even if it is tagged as v1.0.0.

The build done over the same commit but on master branch passes all tests successfully as composer resolves the dependencies correctly:

https://travis-ci.org/BenGorUser/SymfonyRoutingBridgeBundle/jobs/137440680

**Comment by alcohol** [comment]
For some reason, your checkout of `v1.0.0` ends up in a detached head state. Composer is not able to recognize this as anything other than `dev-SHA`. Since BenGorUserBundle requires SymfonyRoutingBridgeBundle at `^1.0`, a conflict is reached. This is not a Composer issue, but rather an issue with your workflow.

**Comment by alcohol** [comment]
It's because you are checking out a tag, not a branch.

**Comment by alcohol** [comment]
Also, a cyclic dependency like this points to a completely broken design.

**Comment by stof** [comment]
use the ``COMPOSER_ROOT_VERSION`` env variable to specify the version of the root package instead of relying on the auto-detection, as it fails for you

**Comment by stof** [comment]
@gorkalaucirica in your case, it looks like the routing bridge bundle wants the user bundle only for its DependentBenGorUserBundle trait, which means it should probably be elsewhere than in the user bundle.

**Comment by gorkalaucirica** [comment]
Thanks @stof, that could fix the issue, but requires changing the `COMPOSER_ROOT_VERSION` every time we tag a new release, I guess.

After looking to our UserBundle we realized that we have some issues with our bridge/bundle architecture as @alcohol pointed out. 

The bundles causing errors will be removed from required in UserBundle and will be suggested as all of them are infrastructure implementations and replaceable with other adapters.

Thanks again!

**Comment by gorkalaucirica** [comment]
@stof In any case we need to require `bengor-user/user-bundle` as the adapter is made for that, it makes no sense in using it standalone.

It makes more sense to us to remove the dependency and suggest to install it in the basic configuration docs.

Thanks for your time!!

**Comment by alcohol** [comment]
Any particular reason you have setup travis to build your tag as a branch?

**Comment by stof** [comment]
@gorkalaucirica you could set the value of the env variable dynamically based on the build metadata (Travis gives you env variables to access them)

**Comment by gorkalaucirica** [comment]
@stof didn`t know that. I'll try

Thanks

**Comment by glensc** [comment]
btw, gitlab-ci does the same when building (checking out by hash) which results the same version detection failure for me:

```
$ git checkout NCMS-413
$ composer show -s
...
versions : * 1.17.x-dev
```

```
$ git show -s --oneline NCMS-413
4a3ff7c show composer version
$ git checkout 4a3ff7c
$ composer show -s
...
versions : * No version set (parsed as 1.0.0)

$ git describe --tags
1.17.0-11-g4a3ff7c

$ git describe
1.17.0-11-g4a3ff7c
```

`git describe` can still find the origin, perhaps improve composer detection?

**Comment by alcohol** [comment]
@glensc what is there to improve? We already determined there was no issue. Cyclic dependencies are bad. Use `COMPOSER_ROOT_VERSION` if you absolutely have to use cyclic dependencies.

**Comment by glensc** [comment]
@alcohol referenced commit that made branch detection to work on gitlab-ci again. perhaps you can do the same on composer side?

**Comment by alcohol** [comment]
I do not see what that has to do with cyclic dependencies.

**Comment by glensc** [comment]
https://github.com/composer/composer/issues/5432#issuecomment-255669875 try reading my previous post again. and note **how** `composer show -s` behaves differently based on how the code was checked out.

**Comment by alcohol** [comment]
I don't see how that is related to this issue. You can open a new one if you think there you have found another bug.

**Comment by glensc** [comment]
i came across the same underlying reason: after adding cyclic dependency to project, the dependencies no longer were solved.

- packageA requires packageB
- packageB requires-dev packageA

and the underlying problem is that when packageB is checked out in CI env (gitlab in my case, travis in this issue case) the version is not detected in packageB (defaults to 1.0.0), which can be solved by changing the way gitlab-ci checkouts the specific revision.

however, i think composer could also improve it's detection of "current branch version".

it can create separate issue if you do consider there's something to fix in composer side. there's little point creating issue which you will reject with "cyclic deps are bad"

**Comment by glensc** [comment]
closest tag can be found with:

```
$ git describe --tags --abbrev=0
1.17.0
```

**Comment by lauripiisang** [comment]
So, what I understand from @glensc is : 
Current scenario:
When git is in detached head state(and no exact tag match), composer doesn't make any educated guess as to what the closest version might be and comes up with the version 1.0.0.
Desired scenario:
When git is detached head state(and no exact tag match), composer runs `git describe --tags` to come up with the version `dev-1.17.0-11-g4a3ff7c`.

Correct ? 

Would this make sense to add to composer Version Guesser, @alcohol ?

**Comment by alcohol** [comment]
I think it would be best if we could first recreate the mentioned scenario with a test. Just a very basic git init / commit / tag / etc, and then the composer show expected output and actual output.

**Comment by lauripiisang** [comment]
@alcohol , here's a manual test. Don't have the time to put together an automated test case at this moment. 

Are there any more questions arising from this?

composer.json:
```
{
    "name": "lauripiisang/testproject",
    "require": {}
}
```
repo: 
```
mkdir testproject
cd testproject 
git init
touch 'README.md' 
git add README.md    
git commit -m 'initial add of README.md. first commit.'       
git tag -a -m 'initial version' 9.0 
touch DEPLOYMENT.md
git add DEPLOYMENT.md
git commit -m 'added DEPLOYMENT.md. second commit.'
echo '{
    "name": "lauripii/testproject",
    "require": {}
}' > composer.json
```

I end up with two commits:
```
git log --oneline

106dfc6 added DEPLOYMENT.md. second commit.
e9970a2 initial add of README.md
```

git checkout master  + composer show -s gives expected output of 

`Already on 'master'`
```
name     : lauripii/testproject
descrip. : 
keywords : 
versions : * dev-master
type     : library
source   : []  106dfc633aa21d543dac3a086d86e3f8f4a2d18e
dist     : []  106dfc633aa21d543dac3a086d86e3f8f4a2d18e
names    : lauripii/testproject
```

git checkout 9.0 + composer show -s gives (mainly) expected output of
```
Note: checking out '9.0'.
...
HEAD is now at e9970a2... initial add of README.md

name     : lauripii/testproject
descrip. : 
keywords : 
versions : * 9.0.0.0
type     : library
source   : []  
dist     : []  
names    : lauripii/testproject
```

Now, I move from detached tag to master, then to detached head of master's second commit:
```
git checkout master
# git output:  Previous HEAD position was e9970a2... initial add of README.md
# We are now at 106dfc6 - second commit.
# Now let's check out 106dfc6 and end up at a detached head:
git checkout 106dfc6
# Note: checking out '106dfc6'.
# You are in 'detached HEAD' state.
# HEAD is now at 106dfc6... added DEPLOYMENT.md. second commit.
```

Now, I'd expect composer to return at least a best guess of what the verison might be, as git does with `git describe --tags`:`9.0-1-g106dfc6`. Perhaps `dev-9.0-1-g106dfc6`?
Instead, I get 
```
name     : lauripii/testproject
descrip. : 
keywords : 
versions : * No version set (parsed as 1.0.0)
type     : library
source   : []  
dist     : []  
names    : lauripii/testproject
```

P.S. one thing I'm not touching on here is the lack of source/dist hashes in the last two examples, just ignore those for now. For my vision of what should be the final outcome for detached state, I propose:
```
name     : lauripii/testproject
descrip. : 
keywords : 
versions : * No version set (parsed as dev-9.0-1-g106dfc6)
type     : library
source   : []  
dist     : []  
names    : lauripii/testproject
```
