### ISSUE TITLE
Feature request: ability to store auth.json in the directory where you create a project

### ISSUE THREAD

**Issue by hostep** [composer/composer#5434]
Hi

I'm searching for a one line solution where you can run `composer create-project` with the ability to store the `auth.json` file in that same directory.

Right now, composer only asks you if you want to store the authentication data in your user configuration file, but I don't want that, since I work with a lot of different projects which all require separate authentications.

Things I tried (in both cases the current directory is completely empty before starting):
```
$ composer create-project --no-install --repository-url=https://repo.magento.com/ magento/project-community-edition .
    Authentication required (repo.magento.com):
      Username: xxyyzz
      Password:
Do you want to store credentials for repo.magento.com in /Users/me/.composer/auth.json ? [Yn] n
Installing magento/project-community-edition (2.0.7)
  - Installing magento/project-community-edition (2.0.7)
    Downloading: 100%

Created project in .

$ ls -l auth.json
ls: auth.json: No such file or directory
```
Ok. Makes sense.
Maybe composer can ask twice where you want to store the `auth.json` file, first time in project dir, if answer was 'n', then second time in the user config? (this will most likely break backwards compatibility)
Or maybe a switch can be added where you tell composer where to store the `auth.json` file?

Second attempt, with setting the `COMPOSER_HOME` variable:
```
$ COMPOSER_HOME=. composer create-project --no-install --repository-url=https://repo.magento.com/ magento/project-community-edition .
    Authentication required (repo.magento.com):
      Username: xxyyzz
      Password:
Do you want to store credentials for repo.magento.com in ./auth.json ? [Yn] Y
Installing magento/project-community-edition (2.0.7)


  [InvalidArgumentException]
  Project directory ./ is not empty.


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

$ ls -l auth.json
-rw-------  1 me  staff   189B Jun 14 20:39 auth.json
```

I really hoped this would work, but composer seems to create the `auth.json` file *before* creating the project, maybe it should defer that until *after* the project was created?

In both cases, I needed to manually create an `auth.json` file in that directory after the project was created. And composer already asked for the credentials. So in my opinion it should be possible for composer to store those in the project directory somehow.

What do you think?

Thanks!

**Comment by alcohol** [comment]
We specifically no longer support storing credentials inside the project dir because credentials should never be stored in VCS. We either store them in `$COMPOSER_HOME/auth.json`, or when you choose 'no', we simply don't store your credentials at all.

**Comment by hostep** [comment]
Ok thanks for the reply.

Guess we'll have to change our workflow then, because we actually do store the `auth.json` files in our VCS, but I understand the reasoning why you aren't encouraging this.

I'll close the issue.

**Comment by Seldaek** [comment]
Just to be clear, we do *support* auth.json files in the local project dir, we just don't write there by default, but you can write to that using `composer config --auth http-basic.repo.magento.com foo bar`, and then it'll be loaded just fine, but I would advise you put this in .gitignore to make sure everyone uses their own credentials then.

**Comment by hostep** [comment]
Just informational: we work on Magento 2 shops. If we use composer with Magento's repository, we have to authenticate per project we work on.

If we follow your recommendations, we need to work like this:

Client 1:
  - dev 1: auth-1
  - dev 2: auth-2
  - dev 3: auth-3
  - staging server: auth-4
  - production server: auth-5

Client 2:
  - dev 1: auth-6
  - dev 2: auth-7
  - staging server: auth-8
  - production server: auth-9

...

If we have 100 clients, this will become quite a burden to maintain. Also if a developer joins us, we'll have to generate an authentication pair for all our client projects.
I don't think we can maintain something like this.

I'd rather go for this:

Client 1:
  - dev 1 & dev 2 & dev 3 & staging & production server: shared-auth-1

Client 2:
  - dev 1 & dev 2 & staging & production server: shared-auth-2

This is the reason why I prefer the `auth.json` file per project directory and inside our VCS.

This is just informational, so you have a view of how we are currently using authentication with composer.

**Comment by Seldaek** [comment]
Yeah I see, if it makes sense to share credentials in your context by all means do it, it's technically possible but in general not a great idea as it makes revoking access to a given dev a bit harder, but you can also just cycle the shared credentials when someone leaves, it's not a huge deal.

**Comment by brandontamm** [comment]
What if we are scripting projects out from server build to composer project creation and require dependencies...How do you typically handle that if the command line requires a manual intervention to input credentials? I understand the idea behind not storing credentials, but in some CI/CD workflows like ours, it seems like our only option since we haven't found a way to get composer to use environmental variables with Bitbucket Pipelines..
