### ISSUE TITLE
no-check-certificate

### ISSUE THREAD

**Issue by bpgh** [composer/composer#5436]
Hi

I'm searching for a certificate function 'no-check-certificate' as in wget.

(The Problem is: Security Gateways opens ssl tunnel and Returns so your own certificate)

Composer Version 1.1.2 2016-05-31 19:48:11

Can you help?

Thanks!

**Comment by alcohol** [comment]
[xyproblem.info](http://xyproblem.info)

**Comment by Seldaek** [comment]
The only way to disable certificate verification, is to use the `disable-tls` config option, but it's really not a good idea as it opens you up to man in the middle attacks.

**Comment by alcohol** [comment]
For Composer (Packagist, etc) communication, the suggestion from @Seldaek should suffice. For Git (used by Composer to clone repo's etc), you can do any of the following:

```
// global config
git config http.sslVerify false

// single run
git -c http.sslVerify=false clone ...

// ENV based
export GIT_SSL_NO_VERIFY=true
git clone ...
```

**Comment by bpgh** [comment]
The suggestion from @Seldaek not working.
 Behind security Gateways (not Proxy! -> security Gateway it works as man in the middle) 
 it is necessary disable the certificate validation on the Exhibitor's name

**Comment by alcohol** [comment]
Can you give us the output of `composer config --global --list` ?

**Comment by alcohol** [comment]
The following commands should help you (but make your setup completely insecure):

```
composer config --global disable-tls true
composer config --global secure-http false
composer config --global repo.packagist composer http://packagist.org
```

**Comment by bpgh** [comment]
Thanks for the Workaround,

this tree options works!
(in environments with content scanners ist this unacceptable and only a Workaround)
