### ISSUE TITLE
Suggestion: Add support for web scripts commands

### ISSUE THREAD

**Issue by tampe125** [composer/composer#5440]
As far as I know, Composer is intended to be executed from CLI, however sometimes it would be useful to actually run a `composer install` within a web page.
For example, I'll report my current use case.
## The problem

I'm a Joomla extension developer, this means that I simply pack a big zip that will be installed on customer site (please keep in mind that the standard quality of shared hosts is pretty low). 
At the moment, if I have to use any Composer library, it means that I have to run all my commands locally, download all the libraries and then include them in the installation package. Since most of the libraries has other dependencies, the end result is a very big archive (maybe 10Mb) that the user has to install on his website.
Such large archives would lead to timeout issues when the customer tries to upload them, so I have to implement several workarounds to prevent that.

Everything would be easier if I could to simply include the `composer.json` and `composer.lock` in my extension and then run `composer install` on the remote site, within my PHP scripts.

Currently there are a couple of [solutions](http://stackoverflow.com/questions/17219436/run-composer-with-a-php-script-in-browser), but that are not really usable for two reasons:
1. **Timeout issues** Trying to download everything in one single page load is VERY risky, since our execution is limited to 30 seconds (maybe less)
2. **Resource usage** Again, doing everything in a single page load requires a lot of resources and sometimes under-the-par hosting would kill the request

I'm not asking Composer to completely re-invent itself, I think that only a small set of changes would be required.
## The solution (maybe)

Instead of doing everything in one shot, is it possible to perform the same action step by step?
In an ideal world, this what a wrapper of Composer would do when `composer install` is launched:
1. **Init step** Required dependencies are calculated
2. **Install step** The same address is polled again again, and each dependency is downloaded/installed one by one. 
3. **Finalization** Final work and clean up

Ideally Composer would store its state and job queue in a temporary file, if that is not possible (too many changes required), it could return the current state, which will be supplied at the next iteration.
Access to those steps could be performed by public methods exposed by Composer, so it will be developer responsibility to call them in the correct order and supply the valid input.

In this way, through several page loads (or AJAX call), we would be able to install the whole sets of dependencies, without the risk of hitting a timeout or using too many resources.
## Conclusion

I'm perfectly aware that this is a big request and the chances to be fulfilled are very low, however it would be a very big improvement for every extensions developer of any CMS (Joomla, Wordpress etc etc).
Nowadays if you want to interface yourself with any external service (AWS, Google) you have to use Composer. Adding web support would dramatically improve the adoption of Composer inside CMS.

**Comment by stof** [comment]
Currently, the [``Composer\Installer`` class](https://github.com/composer/composer/blob/1.1.2/src/Composer/Installer.php) contains all the logic for ``composer install`` and ``composer update``. Being able to build a UI running steps separately would probably require refactoring this class to extract the different steps in different classes.
This would then allow you to build a web interface which would use Composer as a library internally (you can already do that today, but you cannot split steps). But this is a big change in Composer, so I don't see it being done soon by the core team.

**Comment by alcohol** [comment]
Quick FYI; you could just delegate the commands to a queue, which then just runs them as background processes on the server. No issues with timeouts then.

As for your suggestions/questions, those are rather big changes. None of those "components" are currently available stand-alone. Ideally it would be nice if the solver could be decoupled from the other steps, but since it is so tightly integrated this is not something I foresee happening anytime soon.

**Comment by Seldaek** [comment]
That would indeed require huge undertakings in terms of code separation. While I'm sure they would be for the best in the end, it's still a lot of work, and due to the sensitivity of these code paths something I am fairly unlikely to merge if someone sends a +2000/-1500 LOC PR. It's just too hard to review, and I'd rather do it myself if it has to be done. I don't want to close this outright but indeed the chances of this happening are fairly low, and it would require a major release as well. I'll target it for 2.0 for now so we can reconsider it then.

**Comment by tampe125** [comment]
> Quick FYI; you could just delegate the commands to a queue, which then just runs them as background processes on the server. No issues with timeouts and resources then.

You are too much optimistic about the quality of those servers. Sometimes you don't even have the chance to create CRON jobs.
Last week I had a customer complaining about speed, at the end of the day we discovered that the hosting updated the kernel but they "forgot" to reboot the server :-/

>I don't want to close this outright but indeed the chances of this happening are fairly low, and it would require a major release as well. 

Yeah, I knew the chances were **very** low, however I just wanted to raise the attention on the problem. This is an issue that all developers creating mass distributed software are facing: we would love to use Composer, but console access is never granted. Therefore we have to ship the libraries inside the extension package, with the end result of a huge archive and duplicated libraries (because everyone and his dog is using the same libraries and there's no global  `vendor` folder)

I'll keep my finger crossed!

**Comment by alcohol** [comment]
> Therefore we have to ship the libraries inside the extension package, with the end result of a huge archive and duplicated libraries (because everyone and his dog is using the same libraries and there's no global vendor folder)

Disk space is really cheap now a days though, so this is not really a concern in my opinion. Global vendor also has risks and issues associated with it. It is definitely not the silver bullet some people seem to believe it could be.

**Comment by stof** [comment]
@alcohol duplicated libraries are an issue though if they are not at the same version of the library (because PHP cannot load multiple version of a class)

**Comment by alcohol** [comment]
@stof yes, I know. I'm merely commenting on their current workflow. If that's what they are doing, then it must be working. Maybe the extensions run stand-alone? *shrug*

**Comment by stof** [comment]
@alcohol or they were just lucky that the version being loaded was compatible with all extensions using it...

**Comment by tampe125** [comment]
@alcohol The problem is not the disk space. The problem is the installation package size and the max_upload_size directive. There are servers with a limit of 4Mb; plus customers with a terrible connections (so timeouts while uploading)
Ah, the joy of mass distributed software!

**Comment by thekabal** [comment]
+1, This would be very useful for my projects as well.

**Comment by Seldaek** [comment]
Closing this as 2.0 is coming and it has lots of refactorings which should help a little on this front.. Not sure if it's possible yet, but I imagine it'd be closer.
