### ISSUE TITLE
private repo with composer on bitbucket

### ISSUE THREAD

**Issue by craigcarnell** [composer/composer#5446]
I've added a private repo to my composer.json and that works just fine.

However I wish to distribute this code to other people and they won't have my SSH key to be able to access it.

In bitbucket you can add a deployment key, I've created one. I'm not sure if that is the best method.

How do I go about storing it with my repo? do I use auth.json?

**Comment by alcohol** [comment]
You should either grant them access to your repository, or make it public. I do not know what deployment keys do, nor does Composer know about these.

**Comment by Seldaek** [comment]
If the deployment key is present on a machine it should allow composer to clone the repo to read metadata out of it so it should make it work using the git driver for the VcsRepository, but it won't be able to use bitbucket zips etc. You also can't use private keys in auth.json, only oauth tokens. Private keys have to be placed in ~/.ssh/ and then you'll need to configure ssh to use the right private key for bitbucket.. 

All in all granting them read-only access on bitbucket might be easier than using deploy keys.
