### ISSUE TITLE
Composer fires ScriptEvents::POST_INSTALL_CMD even when the package has already been uninstalled

### ISSUE THREAD

**Issue by ptash** [composer/composer#5455]
With the following composer.json:

```json
"require-dev":
{
    "php-composter/php-composter": "^0.2",
}
```

When I run this command:

```
composer update
composer install --no-dev --verbose
```

I get this output:

```
- Removing php-composter/php-composter (v0.2.0)
Generating autoload files
PHP Fatal error:  Class 'PHPComposter\PHPComposter\HookConfig' not found in .../vendor/php-composter/php-composter/src/Plugin.php on line 89
```

I expected that the event post-install-cmd will not happen after removing package.

**Comment by alcohol** [comment]
Your expectations are wrong.

**Comment by ptash** [comment]
How in post-install-cmd check that package has already been uninstalled?
autoload cann't load PHPComposter\PHPComposter\HookConfig because file has been deleted...

**Comment by alcohol** [comment]
When removing a plugin, it is recommended to use the `--no-plugins` flag for install and/or update.

**Comment by alcohol** [comment]
@Seldaek unless you can think of a more elegant approach to deal with this situation?

**Comment by ptash** [comment]
`--no-plugins` works. 
What is there a more elegant approach?

**Comment by alcohol** [comment]
@ptash I personally cannot think of a more elegant approach than `--no-plugins`.

**Comment by ptash** [comment]
Perhaps a more elegant solution that does not call package method on event if the source code of this package is removed... or is it for something you need, and that makes sense?

There any way by Composer\Composer to find out that the package is removed?

I tried:
`$package = $composer->getRepositoryManager()->findPackage('php-composter/php-composter', '*');`
but it return the package not null...

**Comment by nvd-willer** [comment]
In my project build, I need to clear the code from the `dev` packages and run the composer plugins with the  command `install`. For this, I have to run 2 times `composer install` without and with `--no-plagins`. Which is not very convenient. I propose to correct this bug.

**Comment by alcohol** [comment]
And how do you propose to correct it?

**Comment by nvd-willer** [comment]
Do not run plug-ins for remote packages.

**Comment by nvd-willer** [comment]
It is better not to run the `dev` plugins if running `install` with `--no-dev`

**Comment by alcohol** [comment]
@seldaek is it as easy as suggested?

**Comment by nvd-willer** [comment]
It is more difficult than not to do. This is a bug and it needs to be fixed.

**Comment by Seldaek** [comment]
This issue is a duplicate of #4520 IMO.
