### ISSUE TITLE
search api not behaving as expected

### ISSUE THREAD

**Issue by gohanman** [composer/composer#5456]
With the following composer.json:

```json
{
    "name": "corepos/common",
    "description": "Common libraries for CORE-POS",
    "type": "library",
    "license": "GPLv2",
    "require": {},
    "autoload": {
        "psr-4": {
            "COREPOS\\common\\": "src/"
        }
    },
    "require-dev": {
        "phpunit/phpunit": "^5.4"
    }
}
```

When I run this command:

```
composer -vvv require
```

I get this output:

```
Reading ./composer.json
Loading config file ./composer.json
Checked CA file C:\Users\andy\AppData\Local\Temp\composer-cacert-bcf331364fef73d53e4368ba519a6c3fcb21ea7836c3d8efad4ec32731e8152a.pem: valid
Executing command (C:\Users\andy\Documents\Common): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: C:/Users/andy/AppData/Roaming/Composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading C:\Users\andy\Documents\Common/vendor/composer/installed.json
Running 1.1.2 (2016-05-31 19:48:11) with PHP 7.0.5 on Windows NT / 10.0
Search for a package: symfony
Downloading https://packagist.org/packages.json
Writing C:/Users/andy/AppData/Local/Composer/repo/https---packagist.org/packages.json into cache
Downloading https://packagist.org/search.json?q=symfony&type=%type%
Search for a package:
```

And I expected this to happen: show a list of symfony packages for install.

As near as I can tell the 6th line (To initialize...) is telling me I need to create the already-existing composer.json file that it read and loaded in the 1st and 2nd line.

I just installed composer via https://getcomposer.org/Composer-Setup.exe choosing all default options. Running `composer require vendor/package` works fine; it's just the interactive search that doesn't.

**Comment by alcohol** [comment]
The sixth line is irrelevant and you can ignore it. Most people do not have a **global** `composer.json`.

I think you could have elaborated a bit more on your scenario and expectations though. However, since I just tried to replicate your issue, I think I understand what you mean. After inputting a search query, I am simply prompted again to input a search query. It never returns any results. Is this the actual issue you are also experiencing?

It seems that for reasons unknown to me, it queries:
https://packagist.org/search.json?q=symfony&type=%type%

And because the `type` is not a legal value, it returns zero results.

We will have to see when and/or by what this was broken.

**Comment by stof** [comment]
@alcohol this is because the search URL of Packagist has been updated in https://github.com/composer/packagist/pull/692 to account for the new feature supported in nightly builds of composer, but this broke it for the stable builds which don't replace ``%type%``

**Comment by pierredup** [comment]
A fix is pending at composer/packagist#693

**Comment by cebe** [comment]
there is another issue with this change: https://github.com/composer/composer/commit/6a557e45b8295007db61e786736f04018fe5fe90#commitcomment-17966162

**Comment by stof** [comment]
@cebe the BC break for plugins is unrelated to the broken search (even if the same PR introduced it). Please report it separately

**Comment by Seldaek** [comment]
Fixed in https://github.com/composer/packagist/pull/693
