### ISSUE TITLE
Different package name per branch

### ISSUE THREAD

**Issue by tschechniker** [composer/composer#5462]
Hi,

is there a away i can define different package names per git branch? I tried it localy with my private satis repo but composer takes the name from the master branch. 

Best regards

Tobi

**Comment by staabm** [comment]
Whats your use-case? Why do you want that in the first place?

**Comment by alcohol** [comment]
This is not possible. Composer always takes the name on the master branch (unless you configured Github to present another branch as the default branch, then it takes it from that branch).

It also makes very little sense to have multiple packages in different branches. A package should have its own dedicated repository.
