### ISSUE TITLE
composer cannot install on ubuntu

### ISSUE THREAD

**Issue by lonhardt** [composer/composer#5465]
haloo, i need help

i want to install composer on my ubuntu server but when i run command:

 sudo curl -sS https://getcomposer.org/installer | sudo php,

i receive as answer:
 
curl: (6) Could not resolve host: getcomposer.org.

to ping getcomposer.org don´t work, but other sites work.

                                            thanks

**Comment by xabbuh** [comment]
This looks like an issue with your DNS server? Do you sit behind a proxy or something similar that intercepts DNS lookups?

**Comment by lonhardt** [comment]
I checked DNS and now works

thanks
