### ISSUE TITLE
win7    Parse error on line 1:   #!/bin/shdir=$(cd   ^

### ISSUE THREAD

**Issue by karnin** [composer/composer#5466]
My OS is win7.

When I run this command:

composer ,or composer update, or composer install 

I get this output:

 [Seld\JsonLint\ParsingException]
  "C:\ProgramData\ComposerSetup\bin\composer" does not contain valid JSON
  Parse error on line 1:
  #!/bin/shdir=$(cd
  ^
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['

**Comment by alcohol** [comment]
I have no idea why it would attempt to parse said file as json.

You will have to provide the full output of -vvv, not just this snippet. Otherwise we cannot help you.

**Comment by Seldaek** [comment]
Auto-closing as this hasn't been updated in over 6months and is marked as a support request. If there is a real bug to consider please let us know.

**Comment by tankchuen** [comment]
I face this problem also, this is what i run **composer -vvv** on Window 10 get

  [Seld\JsonLint\ParsingException]
  "C:\ProgramData\ComposerSetup\bin\composer" does not contain valid JSON
  Parse error on line 1:
  #!/bin/shdir=$(cd
  ^
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['


Exception trace:
 () at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Json/JsonFile.php:300
 Composer\Json\JsonFile::validateSyntax() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Json/JsonFile.php:156
 Composer\Json\JsonFile->validateSchema() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Factory.php:290
 Composer\Factory->createComposer() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Factory.php:576
 Composer\Factory::create() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:338
 Composer\Console\Application->getComposer() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:451
 Composer\Console\Application->getPluginCommands() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:149
 Composer\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin/composer:58
 require() at C:\ProgramData\ComposerSetup\bin\composer.phar:24


This is second time i face this problem, the first time i downgrade composer.phar from latest version to 1.60, then the problem solve. but this time i got change many composer.phar versions still remain the error.

**Comment by stof** [comment]
Why would it try to use `C:\ProgramData\ComposerSetup\bin\composer` as JSON ? Are you defining a `COMPOSER` env variable pointing to this file ?
