### ISSUE TITLE
Allow to disable cache via an argument

### ISSUE THREAD

**Issue by purificant** [composer/composer#5468]
As a user, I want to be able to disable composer cache when running `composer install`, so that unnecessary files are not saved to disk and do not have to be cleaned up manually afterwards.

This could look like

`php composer install --no-cache`

 
 

The use case is for building docker containers where cache files are not needed in order to keep the image lightweight. So that, when writing a dockerfile, instead of doing

`RUN composer install && composer clear-cache && rm -rf ~/.composer/cache`

I could

`RUN composer install --no-cache`

**Comment by alcohol** [comment]
I understand the rationale. Unfortunately, this will require significant changes to the codebase. Considering that a simple `rm -rf ~/.composer` will remove virtually all noteworthy traces after a composer install, it is very hard to justify those changes. I certainly do not expect anyone to actually invest time into this. But we can leave it here as a feature request regardless :-)

**Comment by Seldaek** [comment]
You can run `COMPOSER_CACHE_DIR=/dev/null composer install` which is about the same. IMO not really a feature warranting a global flag on all commands.

**Comment by purificant** [comment]
@Seldaek Thanks for the suggestion. This approach effectively disables the cache due to an error condition because cache location is not writable. I was hoping to achieve the same effect by disabling the cache explicitly without triggering the error log.

`Cannot create cache directory /dev/null/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /dev/null/files/, or directory is not writable. Proceeding without cache`

For my use case, the error log is not desirable as it may trigger build failure.

@alcohol If this is seen as a feature worth having, I am happy to contribute the code to make it happen.

**Comment by Seldaek** [comment]
I pushed a fix so that the warnings should not appear anymore for obviously disabled caches.

**Comment by nk2580** [comment]
FYI i now use JavaScript and Go because of this
