### ISSUE TITLE
Problem With Composer Update

### ISSUE THREAD

**Issue by ramiltk** [composer/composer#5470]
When update the composer shows this error.
Please help me.
![update composer issue](https://cloud.githubusercontent.com/assets/15965934/16348397/ee9f09c2-3a6f-11e6-8009-2b3687e8af51.jpg)

With the following composer.json:

```json
{
    ...
}
```

When I run this command:

```
composer command -vvv (please include -vvv!)
```

I get this output:

```

```

And I expected this to happen:

**Comment by MichaelGooden** [comment]
You don't fill out the required information for the issue yet you expect help?

Please spend 5 seconds reading the actual error message. It is blatantly clear what the issue is.

**Comment by curry684** [comment]
Reinstall git.

**Comment by ramiltk** [comment]
First time this is not my issue.
After re installation i got this issue.
My actual requirement is need to integrate the pretty photo with my application,for that purpose i will call for composer update.That time i got this issue.

**Comment by curry684** [comment]
Please read the error:

```sh
'git' is not recognized as an internal or external command, operable program or batch file.
```
That means `git` is no longer installed on your computer, or was broken in some way. [Reinstalling it](https://git-scm.com/download/win) will fix your issue.

**Comment by stof** [comment]
make sure that ``git`` is available in your PATH when installing it. the official git installer for windows has 3 options:

- exposing git in the PATH only for git bash
- exposing git in the PATH all the time
- exposing all unix utilities shipped in git bash in the windows PATH (not recommended as they might conflict with windows utilities with the same name).

If you choose the first option, composer will not be able to use git, as it is not in your PATH.
