### ISSUE TITLE
Incorrect assingments

### ISSUE THREAD

**Issue by Lcfvs** [composer/composer#5471]
Hi,

Please, sorry, I don't post any composer.json, because unrelated.

It's about a tiny error, in the autoload_static.php, the `getInitializer()`'s closure assigns some `ClassLoader` *privates* properties.

;)

**Comment by alcohol** [comment]
```
    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitab43d94ce7c5292ed54532e38317996c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitab43d94ce7c5292ed54532e38317996c::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitab43d94ce7c5292ed54532e38317996c::$prefixesPsr0;
            $loader->classMap = ComposerStaticInitab43d94ce7c5292ed54532e38317996c::$classMap;

        }, null, ClassLoader::class);
    }
```

Because the closure binds to the ClassLoader class, they're accessible.

**Comment by stof** [comment]
It is **not** an error. The closure is bound to the ClassLoader class, so it has access to these properties.

And using this trick is precisely what optimizes performances (it avoids having to copy the array from shared memory to the process)

**Comment by Lcfvs** [comment]
Ok, ok.

Sorry, then, guys.
