### ISSUE TITLE
Deploy content of pub folder using composer when installing a new Magento 2 module

### ISSUE THREAD

**Issue by michelgokan** [composer/composer#5472]
There are many modules that require to copy some files and folder inside the magento's "pub" folder. As our entire modules operations and infrastructure is based on composer, this manual (non-composer) copy/paste (merge) of pub folder is making a real pain for our automation process ( I know we can use rsync command but I really wanted to do all operations based on composer from our private Satis repo, just don't like to manually copy paste contents of our pub folder to magento's pub folder).

I already tried composer's map functionality but as we are using "[Composer Custom Directory Installer](https://github.com/mnsami/composer-custom-directory-installer)" plugin for composer to install some 3rd party modules in app folder (as they are not working when installed under vendor folder), so map functionality is not work as expected.

```
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.0.7",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
   "repositories": [
        {
            "type": "git",
            "url": "https://github.com/mnsami/composer-custom-directory-installer.git"
        },

        {
            "type": "git",
            "url": "https://michel_gokan@bitbucket.org/rmecommerce/oshopblog.git"
        },
          {
            "type": "git",
            "url": "https://michel_gokan@bitbucket.org/rmecommerce/oshopall.git"
        },
         {
            "type": "git",
            "url": "https://michel_gokan@bitbucket.org/rmecommerce/oshopbasewidget.git"
        }
        ,
         {
            "type": "git",
            "url": "https://michel_gokan@bitbucket.org/rmecommerce/oshoppagebuilder.git"
        },
        {
            "type": "git",
            "url": "https://michel_gokan@bitbucket.org/rmecommerce/oshopmegamenu.git"
        },  
        {
            "type": "git",
            "url": "https://michel_gokan@bitbucket.org/rmecommerce/oshopproductlist.git"
        },  
        {
            "type": "git",
            "url": "https://michel_gokan@bitbucket.org/rmecommerce/oshopsetup.git"
        },
        {
            "type": "git",
            "url": "https://michel_gokan@bitbucket.org/rmecommerce/oshopthemesettings.git"
        },      
        {
          "type": "git",
          "url": "https://michel_gokan@bitbucket.org/rmecommerce/landryandarcaritheme.git"
        },
        {
        "type": "git",
        "url": "https://michel_gokan@bitbucket.org/rmecommerce/base.git"
        },
        {
        "type": "git",
        "url": "https://michel_gokan@bitbucket.org/rmecommerce/oshoptheme.git"
        },
        {
        "type": "git",
        "url": "https://michel_gokan@bitbucket.org/rmecommerce/pub.git"
        },
        {
        "type": "git",
        "url": "https://michel_gokan@bitbucket.org/rmecommerce/landryandarcaripub.git"
        }



    ],
    "require": {
        "magento/product-community-edition": "2.0.7",
        "composer/composer": "@alpha",
        "mnsami/composer-custom-directory-installer": "*",
        "Ves/Blog":"*",
        "Ves/All":"*",
        "Ves/BaseWidget":"*",
        "Ves/PageBuilder":"*",
        "Ves/Megamenu":"*",
        "Ves/Productlist":"*",
        "Ves/Setup":"*",
        "Ves/Themesettings":"*",
        "magento/theme-frontend-oshop": "*",
        "magento/theme-frontend-base": "*",
        "magento/theme-frontend-Landryandarcari": "*",
        "RMI/pub":"*",
        "RMI/landry-arcari-pub":"*"

    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "2.3.*",
        "pdepend/pdepend": "2.2.2",
        "sjparkinson/static-review": "~4.1",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3 <=0.7.0"
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": "app/code/"
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
   "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "magento-force": "override",
        "installer-paths":{
      "./app/code/Ves/Blog/": ["Ves/Blog"],
      "./app/code/Ves/All/": ["Ves/All"],
      "./app/code/Ves/BaseWidget/": ["Ves/BaseWidget"],
      "./app/code/Ves/PageBuilder": ["Ves/PageBuilder"],
      "./app/code/Ves/Megamenu/": ["Ves/Megamenu"],
      "./app/code/Ves/Productlist/": ["Ves/Productlist"],
      "./app/code/Ves/Setup/": ["Ves/Setup"],
       "./app/code/Ves/Themesettings/": ["Ves/Themesettings"],


      "./app/design/frontend/Venustheme/oshop/": ["magento/theme-frontend-oshop"],
      "./app/design/frontend/RMI/Base/": ["magento/theme-frontend-base"],
      "./app/design/frontend/RMI/LandryAndArcari/": ["magento/theme-frontend-Landryandarcari"]

    }
    }
}
```

My goal is to install (merge) content of my module's pub folder with Magento 2's root pub folder when using composer require mynamespace/mymodulename command.

Any help would be appreciated.

**Comment by alcohol** [comment]
And you cannot use this custom installer for the same purpose?

**Comment by michelgokan** [comment]
@alcohol This is the link: https://github.com/mnsami/composer-custom-directory-installer
Actually, when I use that module, it tries to overwrite the pub folder (and so it removes the content of it and replace it with the new one) instead of merge the module's pub folder with the old one.
Is there anyway to fix it ?

**Comment by alcohol** [comment]
Looking at that, I do not think that actually does what you want it to do. It works on package level, as in, it will install the entire package into the given directory. It does not work if you just want to move a few individual files there from each package.

**Comment by stof** [comment]
I think you should use a similar solution than the one used by Symfony to copy assets of its bundles to the ``web`` directory: using a ``post-install-cmd`` and ``post-update-cmd`` hook to copy the necessary assets (in the case of Symfony, it invokes the Symfony CLI as there is a command doing this work)

**Comment by michelgokan** [comment]
@alcohol @stof Thanks for your reply. I actually need to achieve 2 goals:
1. Install a new package in app/code folder instead of default vendor folder. So this is why I used custom directory installer plugin.
2. Merge contents of a module's pub folder with the Magento's pub folder. This is something that the directory installer plugin can't accomplish it, because it replace the folder, not merging it.

From your reply, I think I need to write some custom scripts myself, right? If so, isn't there any other simple way to do it ? If not, it will be great if you can guide me a little bit as I don't have any idea how to do that and don't have any background about composer code structure.

**Comment by michelgokan** [comment]
@alcohol  @stof Any idea ?

**Comment by hostep** [comment]
Hi @michelgokan 

Since you are talking about a Magento 2 project, maybe you can take a look at the `extra/map` functionality of the [magento-composer-installer](https://github.com/magento/magento-composer-installer) module?

It looks like it depends on the `type` of composer module you are using as to where it will copy the files into, see the docs:
- https://github.com/magento/magento-composer-installer#magento-module
- https://github.com/magento/magento-composer-installer#magento-theme
- https://github.com/magento/magento-composer-installer#magento-language-package
- https://github.com/magento/magento-composer-installer#magento-library
- https://github.com/magento/magento-composer-installer#magento-component

I think in your case you either need `magento2-module` or `magento2-component` ?

Not sure if this is helpful for you ...

**Comment by Seldaek** [comment]
Auto-closing as this hasn't been updated in over 6months and is marked as a support request. If there is a real bug to consider please let us know.
