### ISSUE TITLE
Feature request: depending on external programs / commands

### ISSUE THREAD

**Issue by RonRademaker** [composer/composer#5477]
With the following composer.json:

```json
{
    "require": {
        "commands" : {
            "ls" : {},
            "curl" : {
                "versionArg": "--version",
                "findVersion": "^curl\\ ([^\\ ]*)\\ ",
                "require": "^7.0"
            }
         }
    }
}
```

When I run this command:

```
composer update -vvv
```

I get this output:

```

  [ErrorException]
  Illegal offset type in isset or empty

```

And I ~~expected~~ would like this to happen:

Composer checking if the ls command is available (in $PATH) and if the curl command is available and fulfills the version constraint ^7.0. 

I got inspired by this because of this issue https://github.com/php-ai/php-ml/issues/7.

**Comment by alcohol** [comment]
This goes beyond the scope of problems that Composer aims to solve. This is about requirements on an operating level, and thus should be handled by the package manager of said OS (such as yum, apt, pacman, etc). You can (and should) also use software such as Puppet, Ansible or similar solutions for this.

**Comment by curry684** [comment]
This is also trivial to implement with an after-install trigger, already present in Composer, where you can perform installation checks like this.

**Comment by RonRademaker** [comment]
> This goes beyond the scope of problems that Composer aims to solve. This is about requirements on an operating system level, and thus should be handled by the package manager of said OS (such as yum, apt, pacman, etc). You can (and should) use software such as Puppet, Ansible or similar solutions for this.

I would disagree for two reasons:

* Composer is meant to handle your dependencies, I perceive this as: after a composer install everything 'works' or composer gives me some kind of error why it won't 'work'. Why should such dependencies be limited to just PHP? (One could argue the php extension composer already supports are also OS requirements).
* Composer is meant to be used in development, I don't think tools like puppet or ansible are very suitable to manage your development environment (for production this is of course an entirely different story).

> This is also trivial to implement with an after-install trigger, already present in Composer, where you can perform installation checks like this.

Sounds like a good solution. Thanks.

**Comment by alcohol** [comment]
We can agree to disagree. :-)

**Comment by curry684** [comment]
> One could argue the php extension composer already supports are also OS requirements

One would be wrong  :wink:   Composer is a dependency manager, not a package manager. Composer's sole goal is to ensure the PHP end of a PHP project can run. Envisioning the OS as a pyramid of dependencies, Composer has no business outside the PHP subpyramid. So yes, it checks PHP's version and extensions, but nothing outside that. 

If we were to support this we would be adding firewall checkers, network configurations soon, Redis, Mongo and MariaDB installers next, and after that Gulp and NPM et al. Those are also kind of related to running PHP sites right?

**Comment by alcohol** [comment]
It is also a lot about finding a balance between what we want to support, and what we can actually support, considering the limited amount of time and contributors/maintainers/developers.
