### ISSUE TITLE
This package requires php 7 but your PHP version (7.0.8) does not satisfy that requirement.

### ISSUE THREAD

**Issue by tokidoki11** [composer/composer#5480]
With the following composer.json:

```json
{
     "require": {
    "php":"7",
    "ext-mysqli": "*",
    "ext-gd":"*",
    "ext-ldap": "*",
    "ext-openssl":"*",
    "php-opencloud/openstack": "^2.0"
  },
  "minimum-stability": "dev",
  "prefer-stable":true
}
```

When I run this command:

```
Composer install / composer update
```

I get this output:
This package requires php 7 but your PHP version (7.0.8) does not satisfy that requirement.

```

And I expected this to happen:
php-opencloud/openstack require php:~7.0
I supposedly be able to install right?

I force update on my development(laptop) environment.

I try to run this production on IBM Bluemix, force install is not a good idea I think

**Comment by staabm** [comment]
your composer.json is wrong for the php-requirement.

should be `"php": "^7.0",`

**Comment by alcohol** [comment]
Please read https://getcomposer.org/doc/articles/versions.md :-)

**Comment by tokidoki11** [comment]
Hi guys,
thanks for replying... matters resolved 👍 
thanks a lot

**Comment by pbrink231** [comment]
I have the same problem but I know is system configuration.  This works perfectly on windows machine but on Ubuntu I am having problems.  Any suggestions?

A couple commands to check my installs from the earlyer comment.
# php -v
PHP 7.1.7-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jul  7 2017 09:41:45) ( NTS )

# php -i | grep curl
/etc/php/7.1/cli/conf.d/20-curl.ini,
curl

# echo "<?php var_dump(extension_loaded('curl')); ?>" | php
bool(true)

---- This is the Laravel error being shown
(1/1) FatalThrowableError
Call to undefined function Ixudra\Curl\curl_init()
--
in Builder.php (line 370)

**Comment by pbrink231** [comment]
UPDATE with fix.

I installed
`apt-get install php-curl`

After installing
`apt-get install php7.0-curl`
It worked perfectly

**Comment by locsob** [comment]
I run with some issue on Windows. php -v out '5.6', but i use 7.0. The problem been in 'Path' variable, where global php install 'openserver/modules/php 5.6'. I changed it on 7.0 and it works.

**Comment by Lesnock** [comment]
@locsob 
Where is that variable?

**Comment by logicbate** [comment]
go to 
control panel/system security/ system
advanced system settings / environnement variables/  PATH / 
search php path and replace by new path c:\wamp64/bin/php/php7.1.9

**Comment by hayjay** [comment]
Whenever you come accross issues like this, try using ```composer install --ignore-platform-reqs``` source : [Useful Link](https://www.devopsschool.com/blog/composer-update-fails-with-composer-json-php-version-7-1-3/)
