### ISSUE TITLE
require vs require_once in generated autoload_real.php (Question)

### ISSUE THREAD

**Issue by mwjames** [composer/composer#5481]
Maybe there is a simple reason as to why the generated code in `autoload_real.php`

```
function composerRequire3741191bb7a7a054bcca8dd140f17d02($fileIdentifier, $file)
{
    if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
        require $file;

        $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;
    }
}
```
uses `require` instead of `require_once`. I just came across an issue where this caused a `Cannot redeclare class....`

Composer version 1.0.3 2016-04-29

**Comment by staabm** [comment]
duplicate of https://github.com/composer/composer/issues/867

**Comment by mwjames** [comment]
> duplicate of #867

Not really, #867 touches `vendor/autoload.php` as topic, I'm specifically interested in as to why the generated function relies on `require` instead of `require_once`.

**Comment by Seldaek** [comment]
We don't use require_once because require_once is slower and offers no guarantee that it'll work any better. https://github.com/composer/composer/pull/4186 also makes sure that we don't include the same file twice, but if you have multiple composer contexts included in the same process and they load the same file with different contents then they will be loaded twice and you might have issues.

In any case, we'd need more details as to how to reproduce this to maybe be able to help, but the require will not change to require_once.

**Comment by mwjames** [comment]
> but the require will not change to require_once.

OK

**Comment by Seldaek** [comment]
Also:

> we'd need more details as to how to reproduce this to maybe be able to help

Up to you tho.

**Comment by HalliHalloSchatz** [comment]
I have the problem, when I use composer.json from MediaWiki and enable the composer.local.json and add in composer.local.json "mediawiki/semantic-media-wiki": "*".

After "composer update --no-dev" wiki running fine.
After a second "composer update --no-dev" I get a " PHP Fatal error:  Cannot redeclare..." error. I found that is a problem with the autoload generation of composer.

Reproduce:
- I remove the "mediawiki/semantic-media-wiki": "*" in composer.local.json
- composer update --no-dev and after that wiki works fine.
- add in composer.local.json "mediawiki/semantic-media-wiki": "*"
- composer update --no-dev and after that wiki works fine.
- composer dump-autoload -o --no-dev RESULT: wiki get the PHP FAtal error.

in the vendor/composer/autoload_classmap.php, autoload_files.php, autoload_psr4.php and autoload_static.php have the Semantic-media-wiki files double.

I think it is a problem that there is no "require one switch" for the "autoload" section.
"extensions/SemanticMediaWiki/composer.json" and "composer.json" with included "composer.local.json" have both a "autoload" section.
