### ISSUE TITLE
composer dump-autoload --no-dev should exclude "require-dev"

### ISSUE THREAD

**Issue by avindra** [composer/composer#5483]
With the following composer.json:

```json
{
    "require-dev" : {
        "phpunit/phpunit" : "5.4.6"
    }
}
```

When I run this command:

```
composer dump-autoload --no-dev
```

`vendor/composer/autoload_static.php` contains:

```
...
         'PHPUnit_Exception' => __DIR__ . '/..' . '/phpunit/phpunit/src/Exception.php',
         'PHPUnit_Extensions_GroupTestSuite' => __DIR__ . '/..' . '/phpunit/phpunit/src/Extensions/Gro    upTestSuite.php',
        'PHPUnit_Extensions_PhptTestCase' => __DIR__ . '/..' . '/phpunit/phpunit/src/Extensions/PhptT    estCase.php',
        'PHPUnit_Extensions_PhptTestSuite' => __DIR__ . '/..' . '/phpunit/phpunit/src/Extensions/Phpt    TestSuite.php',
...
```

Etc (the list is absolutely massive),

It would be great to have these excluded, either with `no-dev` or a new flag called `no-require-dev`. My team follows the pattern where absolutely ZERO development dependencies run in our production code. Therefore, having them in the autoloader files is a waste of memory.

I thought this would be the default behavior for `no-dev`, but after reading the docs, it seems this is not intended:

```
      --no-dev                   Disables autoload-dev rules.
````

Therefore, this should be considered a feature request or an enhancement.

**Comment by Seldaek** [comment]
We dump everything that is installed, if you want to have a short classmap for production the recommended way is to run `composer install --no-dev -o` to make sure you don't have any dev dependency installed, and that will dump the optimized classmap as well.

**Comment by avindra** [comment]
@saldaek: thanks for the recommendation. The reason why I was looking for another way is that we deploy with our `vendor` folder containing all dependencies. Is there a workaround in this case (i.e., ignoring the installed dev dependencies)?

**Comment by Seldaek** [comment]
No there isn't. You can still run composer install --no-dev which will wipe the dev dependencies, if you have the composer.lock file present this should run very fast.

**Comment by avindra** [comment]
@Seldaek : Thanks, `composer install --no-dev --o` does it. Removes the dev deps we use in 1.34s, which is acceptable :+1:
