### ISSUE TITLE
Wrong handling of namespace changes

### ISSUE THREAD

**Issue by mihaiplasoianu** [composer/composer#5487]
I have a plugin with the following composer.json:
```
{
	"name": "acme/foo"
}
```
I have some tags **1.0**, **1.1** and **1.2**.

Later I change the composer.json to:
```
{
	"name": "acme/bar"
}
```
I create a new tag **2.0**.

From now on, composer only knows this plugin as **acme/bar**, even for the old 1.* tags. The following require:
```
"acme/foo": "1.*"
```
would produce this error:
```
  Problem 1
    - The requested package acme/foo could not be found in any version, there may be a typo in the package name.
```

This is imho a bug, as composer should use for every tag the namespace from the respective composer.json. What is the preferred method of dealing with namespace changes, while still supporting old versions?

**Comment by Seldaek** [comment]
See https://github.com/composer/composer/issues/5462 - this is not possible and would break support for renaming packages on packagist. Usually you are better off if all versions of the package have the same name.

If your package is on packagist, then you can keep the two names going.. If it's a private package then surely updating the requires to the new name shouldn't be too hard?
