### ISSUE TITLE
Very minor question about differences in autoload_static and autoload_classmap.

### ISSUE THREAD

**Issue by rquadling** [composer/composer#5488]
In my `vendor/composer/autoload_classmap.php` I have lines like ...

```php
    'ApiController' => $baseDir . '/controllers/ApiController.php',
    'Assert\\Assertion' => $vendorDir . '/beberlei/assert/lib/Assert/Assertion.php',
    'Assert\\AssertionChain' => $vendorDir . '/beberlei/assert/lib/Assert/AssertionChain.php',
```

where `$baseDir` is my application's base directory and `$vendorDir` is the `vendor` directory.

All ok there!

In my `vendor/composer/autoload_static.php` I have lines like ...

```php
        'AccountController' => __DIR__ . '/../..' . '/controllers/AccountController.php',
        'AffiliatesController' => __DIR__ . '/../..' . '/controllers/AffiliatesController.php',
        'ApiController' => __DIR__ . '/../..' . '/controllers/ApiController.php',
        'Assert\\Assertion' => __DIR__ . '/..' . '/beberlei/assert/lib/Assert/Assertion.php',
        'Assert\\AssertionChain' => __DIR__ . '/..' . '/beberlei/assert/lib/Assert/AssertionChain.php',
```

Here, we have various number of `'/..'`'s.

Is there any reason why one uses variables and the other uses dots?

Is there any real difference?

**Comment by Seldaek** [comment]
The __DIR__ stuff can be cached in opcache, the other version can't because of the variable, I guess it could be brought in line but there isn't a whole lot of gain to be had, if at all.
