### ISSUE TITLE
Show when Git is using cache during cloning

### ISSUE THREAD

**Issue by hkdobrev** [composer/composer#5489]
I wanted to try out the new Git caching. At first I thought it wasn't working and I was going to submit a bug. But then I've measured the Git clone speed and I realised it is working, but it doesn't say anything. This is a feature request to enhance the Git cloning and echo something similar to `Loading from cache` with tarballs. This way people would know VCS cache is used.

---

I've prepared the following `composer.json` to demonstrate what I've done:

```json
{
    "config": {
        "preferred-install": {
            "symfony/*": "source"
        }
    },
    "require": {
        "silex/silex": "^2.0"
    }
}
```

I ran these commands:

```
mkdir test && cd test
composer require silex/silex
rm -rf vendor
time composer install
rm -rf $HOME/.composer/cache/vcs/https---github.com-symfony-*
rm -rf vendor
time composer install
```

I saw around two-fold deduction in installation time. However I expected to see something like `Loading from cache`.

Here's the output I got:

```
  - Installing symfony/routing (v3.1.2)
    Cloning 22c7adc204057a0ff0b12eea2889782a5deb70a3

  - Installing symfony/polyfill-mbstring (v1.2.0)
    Cloning dff51f72b0706335131b00a7f49606168c582594

  - Installing symfony/http-foundation (v3.1.2)
    Cloning 6b5a3764c5b0ce1f0ec3b8be5bba969122a78cfc

  - Installing symfony/event-dispatcher (v3.1.2)
    Cloning 7f9839ede2070f53e7e2f0849b9bd14748c434c5

  - Installing psr/log (1.0.0)
    Loading from cache

  - Installing symfony/debug (v3.1.2)
    Cloning 06e2d52e307ef880ac739f44ee6c2418ca9e3283

  - Installing symfony/http-kernel (v3.1.2)
    Cloning 3a1ce1829128988826739bd9dd820f3238b92d65

  - Installing pimple/pimple (v3.0.2)
    Loading from cache

  - Installing silex/silex (v2.0.2)
    Loading from cache
```

You can clearly see the use of cache for the tarballs, but not for Git cloning.

---

For reference my benchmark was around the following:

```
# without cache
real 0m39.999s
user 0m2.947s
sys  0m1.740s

# with cache
real 0m21.744s
user 0m1.717s
sys  0m1.042s
```

**Comment by alcohol** [comment]
It will show this if you run it in `-vvv` for sure, since that outputs all the git commands we execute in the background. Perhaps it would be nice if we changed the wording for this particular step to "Cloning $ref from cache" (when applicable). But is it really that important of a distinction?

**Comment by hkdobrev** [comment]
@alcohol Thanks! Well, I'm not sure if that's so important and not sure if it's easy to implement or not. That's why I wanted to raise the question and see if others want the same thing.

**Comment by alcohol** [comment]
Yeah should be pretty easy. Just make the message a variable and alter it inside the conditional block when applicable, see code here: [GitDownloader.php#L50-L62](https://github.com/composer/composer/blob/334d0cce6b056e7555daf4c68c48cbe40ee4d51a/src/Composer/Downloader/GitDownloader.php#L50-L62)

**Comment by hkdobrev** [comment]
I'm happy to submit a PR, if others find this useful. I support the principle of least output, so I'm happy to leave this only in verbose mode if no one needs that, but we are outputting something anyway.

**Comment by umulmrum** [comment]
I'd be glad if it was obvious if the repo is cloned from the cache, so that it is consistent with the output for tarballs.
