### ISSUE TITLE
Unable to add config extra of non-string type

### ISSUE THREAD

**Issue by kweij** [composer/composer#5492]
With the following composer.json:

``` json
{
}
```

When I run this command:

```
composer config -vvv extra.param true
```

I get this composer.json:

``` json
{
    "extra": {
        "param": "true"
    }
}
```

And I expected this to happen:

``` json
{
    "extra": {
        "param": true
    }
}
```

Also adding other types beside booleans, such as integers is not possible using the `config` command. Can this feature be added?

**Comment by alcohol** [comment]
It could be. But since it is such an insignificant feature, it is unlikely anyone is willing to spend time on this. If you find it important and useful, you are welcome to contribute this yourself of course :-)

**Comment by alcohol** [comment]
Why not just store 0 and 1 then as string values? When being cast to boolean, you get the desired result.

```
rob@macbookpro ~ (master) $ php -r "var_dump((bool) '0');"
Command line code:1:
bool(false)
rob@macbookpro ~ (master) $ php -r "var_dump((bool) '1');"
Command line code:1:
bool(true)
```

**Comment by alcohol** [comment]
In general it should work, though. That is why I suggested it. Unless strict type matching is involved, which is rarely a good idea when dealing with configuration values, in my opinion.

**Comment by Seldaek** [comment]
Composer 2.0 adds a --json argument that allows fixing this https://getcomposer.org/doc/03-cli.md#modifying-extra-values
