### ISSUE TITLE
PHP Fatal error:  Allowed memory size of ... bytes exhausted

### ISSUE THREAD

**Issue by pacid** [composer/composer#5493]
With composer.json
```
{
  "name": "symfony/framework-standard-edition",
  "license": "MIT",
  "type": "project",
  "description": "The \"Symfony Standard Edition\" distribution",
  "autoload": {
    "psr-0": { "": "src/" }
  },
  "repositories": [
 (...)
  ],
  "require": {
    "php": ">=5.3.33",
    "symfony/symfony": "2.3.*",
    "doctrine/orm": "~2.2,>=2.2.3",
    "doctrine/doctrine-bundle": "1.2.*",
    "twig/extensions": "1.0.*",
    "symfony/assetic-bundle": "2.3.*",
    "symfony/swiftmailer-bundle": "2.3.*",
    "symfony/monolog-bundle": "2.3.*",
    "sensio/distribution-bundle": "2.3.*",
    "sensio/framework-extra-bundle": "2.3.*",
    "sensio/generator-bundle": "2.3.*",
    "incenteev/composer-parameter-handler": "~2.0",
    "friendsofsymfony/user-bundle": "dev-master",
    "fsd/homepage-bundle":"dev-login_refactor",
    "fds/silkadapter-bundle":"0.7.*",
    "fds/categorypage-bundle":"0.7.*",
    "fds/productpage-bundle":"dev-boilerplate",
    "fds/checkoutpage-bundle":"dev-boilerplate",
    "fds/contentpage-bundle":"dev-boilerplate",
    "fds/commonwidget-bundle":"0.1.*",
    "fds/blogpage-bundle":"0.4.*",
    "fds/loginpage-bundle":"dev-login_refactor",
    "fds/mappage-bundle":"0.2.*",
    "jms/i18n-routing-bundle": "dev-master",
    "jms/translation-bundle": "dev-master",
    "fds/ysi18nrouting-bundle":"0.2.*",
    "oodle/urlify": "dev-master"
  },
  "scripts": {
    "post-install-cmd": [
      "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
    ],
    "post-update-cmd": [
      "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
    ]
  },
  "config": {
    "bin-dir": "bin"
  },
  "minimum-stability": "stable",
  "extra": {
    "symfony-app-dir": "app",
    "symfony-web-dir": "web",
    "incenteev-parameters": {
      "file": "app/config/parameters.yml"
    },
    "branch-alias": {
      "dev-master": "2.3-dev"
    }
  }
}

```

**with composer update -vvv
and 8000 mb ram limit 
Composer version 1.1.3 2016-06-26 15:42:08  (tried also before, with 1.0.3, then did self-update)

PHP Version: PHP 5.6.2 (cli) (built: Oct 20 2014 16:21:27) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans

on a repo that I had never problems with memory, and even after a restart I am getting:**

(...)
Reading /Users/fds/.composer/cache/repo/https---packagist.org/provider-symfony$dom-crawler.json from cache
Reading /Users/fds/.composer/cache/repo/https---packagist.org/provider-symfony$locale.json from cache
Reading /Users/fds/.composer/cache/repo/https---packagist.org/provider-symfony$propel1-bridge.json from cache
Reading /Users/fds/.composer/cache/repo/https---packagist.org/provider-symfony$proxy-manager-bridge.json from cache
Reading /Users/fds/.composer/cache/repo/https---packagist.org/provider-symfony$serializer.json from cache
Reading /Users/fsd/.composer/cache/repo/https---packagist.org/provider-symfony$validator.json from cache
Reading /Users/fds/.composer/cache/repo/https---packagist.org/provider-symfony$web-profiler-bundle.json from cache
Reading /Users/fds/.composer/cache/repo/https---packagist.org/provider-symfony$security-http.json from cache
Reading /Users/fds/.composer/cache/repo/https---packagist.org/provider-symfony$expression-language.json from cache
Reading /Users/fds/.composer/cache/repo/https---packagist.org/provider-symfony$security-guard.json from cache
Reading /Users/fsd/.composer/cache/repo/https---packagist.org/provider-phpdocumentor$reflection-docblock.json from cache
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 134217728 bytes) in phar:///usr/local/Cellar/composer/1.0.0-alpha11/libexec/composer.phar/src/Composer/DependencyResolver/Solver.php on line 220

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 134217728 bytes) in phar:///usr/local/Cellar/composer/1.0.0-alpha11/libexec/composer.phar/src/Composer/DependencyResolver/Solver.php on line 220

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.

Anyone?

**Comment by staabm** [comment]
@pacid did you check the mentioned url https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors ?

**Comment by janmyszkier** [comment]
@pacid: Can you try disabling xdebug temporarily and see what's the result then?

**Comment by pacid** [comment]
@staabm, @janmyszkier  : yes, tried everything, xdebug disabled, memory to -1.

**Comment by pacid** [comment]
Tried something else:
I found that path disturbing:
```
phar:///usr/local/Cellar/composer/1.0.0-alpha11/libexec/composer.phar/src/Composer/DependencyResolver/Solver.php on line 220
```
I've asked myself - why would I have something like "1.0.0-alpha11" in path.
So, I've downloaded a composer.phar into my local project
```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === 'e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
```
and went with php composer.phar install  (tried update as well)
...and it works.

**Comment by janmyszkier** [comment]
@pacid  ah! so all that time you were using local composer package (which was alpha) ?

**Comment by alcohol** [comment]
Note that even though your machine has 8G ram, your PHP process was limited to 1G:

```
Fatal error: Allowed memory size of 1073741824 bytes exhausted
```

If Composer/PHP runs out of actual physical memory, the error would look more like:

```
PHP Fatal error: Out of memory
```

You said you tried changing the `memory_limit` to -1, but I do not see this reflected in the output. It could be your "packaged" Composer install was using a different php.ini for one reason or another.

I frequently recommend Mac users not to install Composer through Homebrew. The recipe is just a poor substitute for a manual install (which is really quite simple).

Anyway, it seems you managed to resolve the issue, so I am closing this thread :-)
