### ISSUE TITLE
Possibility to pass path of PHP

### ISSUE THREAD

**Issue by Mariyo** [composer/composer#5496]
Hi,

is it possible to pass different path to PHP than the global one? We have for some vhosts different PHP, but default (global one) is old 5.3. It would be nice to have this command:

```
composer install -path /path/to/project/php/different/than/global
```

Thank you

**Comment by alcohol** [comment]
You can use:

```
/path/to/bin/php composer.phar <command>
```

Note that you specifically need to run the composer phar/binary with the php binary. Using just "composer" will not work (even if it is in your path).

**Comment by Mariyo** [comment]
Cool, thx.
