### ISSUE TITLE
dev-master#abcd123 using dev-master autoload

### ISSUE THREAD

**Issue by tonyTacony** [composer/composer#5498]
Little summary, I am using a commit hash for the october/rain package (last working with my project). I am getting any error because of an autoload file in the composer.json of dev-master (but not in the has). The file exists on the dev-master, but not in the hash I am using.

I have not looked at composer's code yet, but it would seem like composer.lock is using the autoload of dev-master and not the one of the hash.

Maybe I am using this incorrectly?

With the following composer.json:

```json
{
    "require": {
        "php": ">=5.4",
        "laravel/framework": "5.0.*",
        "illuminate/html": "5.0.*",
        "october/rain": "dev-master#0011c5bf55a7100e3bc53f70c4c7531cbf75790c"
    }
}
```

When I run this command:

```
rm composer.lock
rm -Rf vendor/
composer clearcache
composer dumpautoload
composer install
```

I get this output:

```
(in browser)
"Warning: require(vendor/composer/../october/rain/src/Html/helpers.php): failed to open stream: No such file or directory in vendor/composer/autoload_real.php on line 70"

```

And I expected this to happen:

Use the autoload from the composer.json in the hash not dev-master

**Comment by alcohol** [comment]
https://getcomposer.org/doc/articles/troubleshooting.md#i-have-locked-a-dependency-to-a-specific-commit-but-get-unexpected-results-

**Comment by stof** [comment]
This is a documented behavior. ``dev-master#0011c5bf55a7100e3bc53f70c4c7531cbf75790c`` will still read the package metadata in dev-master (so it is not only getting the autoload from there but the dependencies too). the commit hash locking is an installer-level hack (btw, it works only for source installations or for github-hosted dist archives).
My advice is to avoid using this feature altogether (use tags instead, which is the proper way to deal with releases, or use the uptodate version of dev branches)

**Comment by tonyTacony** [comment]
Thank you for the quick reply, I was afraid of this. The project I am working with seems to not do tags/releases. I guess I will have to fork it, make a tag, and point it to my own repo. Thank you both for your help.

**Comment by stof** [comment]
if you fork it, you can also use a branch pointing to the wanted commit
