### ISSUE TITLE
Composer Status Support for Non-VCS Packages

### ISSUE THREAD

**Issue by tkn98** [composer/composer#5500]
From what I could quickly checked on the command-line, the `composer status` does not show any changes with non-vcs (git) repositories, is that correct?

If so what would be your feedback about the idea to have some check or flag to verify archived packages as well?

**Comment by stof** [comment]
how would you check whether a file has been edited for packages installed from an archive ?

**Comment by tkn98** [comment]
Comparing against the files in the archive. I can imagine that requires implementation per archive format.

**Comment by stof** [comment]
And this requires downloading the archive to compare (with the hope that this archive is still in the cache)

**Comment by tkn98** [comment]
Yes, something along those lines. So this must be a switch as it could result in quite some network cost.

**Comment by alcohol** [comment]
Seems like a huge waste of time to me :-)

Too much effort and complexity for something that holds very little value and will most likely almost never be used.

**Comment by Seldaek** [comment]
I agree that it's not really reasonable and not worth implementing. If you want change tracking make sure you use the preferred-install config to force source installs (this can be turned on for some packages/vendors only) :) https://getcomposer.org/doc/06-config.md#preferred-install

**Comment by tkn98** [comment]
Yes I know about source installs, in my scenario, that's not the context however. Anyway I can see this is plugin material. Thanks for all the feedback and tips again.

**Comment by inkatpms** [comment]
How to
