### ISSUE TITLE
HomeCommand should not use passthru to find the paths of executables

### ISSUE THREAD

**Issue by stof** [composer/composer#5501]
Currently, the ``home`` command uses passthru to call ``which``. But this causes the output of the command to be displayed in the output of Composer, which looks weird:

```bash 
$ composer home gedmo/doctrine-extensions
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
/usr/bin/xdg-open
/bin/open
```

The Process component should be used instead

**Comment by Seldaek** [comment]
Can you check that its fixed in latest snapshot and still works for you on nix? I only tested windows.

**Comment by stof** [comment]
@Seldaek does not work, because the Composer ProcessExecutor does not capture the output when passing a single argument, so the output of ``which`` is still displayed

**Comment by stof** [comment]
you would have to pass a second argument

**Comment by Seldaek** [comment]
OK self-update please :)

**Comment by stof** [comment]
works fine now
