### ISSUE TITLE
drush sql-cli hangs while calling mysql on proc_open

### ISSUE THREAD

**Issue by vibanu** [composer/composer#5502]
I am unable to go past the proc_open error when I give drush @local sql-cli; I'm not sure if this is a compser issue. I still have posted this bug here to see if anyone can provide some pointers to resolve this issue. 

BTW... drush @remote sql-cli works. It brings me to mysql > prompt. 

sql-cli to hangs at "proc_open(mysql --defaults-extra-file="C:\\Users\\name\\AppData\\Local\\\Temp\\dru9F1A.tmp"  --database=compscisbu --host=127.0.0.1 --port=3306) for local database.

I'm running drush through composer on windows 10
   composer global require drush/drush:7.*

I tried the fix to removing  ~/.composer/vendor/bin from my PATH and execute drush using ../vendor/drush/drush/drush from the site root as listed here https://github.com/drush-ops/drush/issues/1712; This did not fix the issue.

Any pointers on troubleshooting this will be helpful.

Thanks much!

**Comment by alcohol** [comment]
I'm sorry but this really is not a Composer issue.
