### ISSUE TITLE
Your logo is wrong

### ISSUE THREAD

**Issue by yourlogoiswrong** [composer/composer#5511]
Your logo is of a conductor, not a composer. While there indeed were conductors who were also composers, one does not automatically equal another.

**Comment by pborreli** [comment]
duplicate of #1713 and composer/getcomposer.org#36

**Comment by alcohol** [comment]
Thanks @pborreli

**Comment by Seldaek** [comment]
Wow, some courageous soul created a new fake account just for the purpose of trolling here. Impressive.

**Comment by yourlogoiswrong** [comment]
@Seldaek
Wow, some courageous soul posted in a closed issue thread just for the purpose of being butthurt. Impressive.
