### ISSUE TITLE
Composer command-line installation

### ISSUE THREAD

**Issue by PowerGamer1** [composer/composer#5512]
A script provided at https://getcomposer.org/download/ has a drawback:

> WARNING: Please do not redistribute the install code. It will change with every version of the installer. Instead, please link to this page or check how to install Composer programmatically.

Also, a solution here https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md is Linux only (does not support Windows).

Why not simply use `trim(file_get_contents('https://composer.github.io/installer.sig'))` instead of a hardcoded signature in the script at https://getcomposer.org/download/:
```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
```
P.S. `trim` is needed since https://composer.github.io/installer.sig returns the hash with an extra newline at the end.

**Comment by SvenRtbg** [comment]
I'd assume using an explicit hash value is less likely to be tampered with. It still is included in the install instructions coming from the same server, but it is seen by more people there.

**Comment by PowerGamer1** [comment]
@SvenRtbg 
> I'd assume using an explicit hash value is less likely to be tampered with.

Your logic does not hold for https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md where the hash value is not specified explicitly and is downloaded from the server.

**Comment by Seldaek** [comment]
@PowerGamer1 you are welcome to download the file as you wish on windows, the reason I use curl is that its ssl support is good by default. With php file_get_contents you only get decent ssl by default on php 5.6+ so I wouldn't recommend this to everyone.
