### ISSUE TITLE
Try to submit BitBucket private repos to pakagist.org getting error.

### ISSUE THREAD

**Issue by vipulpatel1994** [composer/composer#5513]
getting error is
We had problems parsing your composer.json file, the parser reports: The 'https://bitbucket.org/api/1.0/repositories/sandipneo/caketest/tags' URL could not be accessed: HTTP/1.1 403 FORBIDDEN

**Comment by stof** [comment]
This is logical, as Packagist does not have access to your private repo

**Comment by alcohol** [comment]
Private repositories cannot be used in combination with Packagist. Look into running [Satis](https://github.com/composer/satis) locally if you want to use private repositories.

**Comment by vipulpatel1994** [comment]
Thanks @alcohol and @stof  
Is it possible to set authentication in public repo, if is then how?

**Comment by alcohol** [comment]
Then it would not be public anymore. So, no.

**Comment by alcohol** [comment]
But you can have a look at the following documentation:

https://getcomposer.org/doc/05-repositories.md#using-private-repositories
https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md

**Comment by vipulpatel1994** [comment]
can you give me idea about this link
https://help.fortrabbit.com/private-composer-repos

**Comment by alcohol** [comment]
Looks ok, but I cannot say for sure.
