### ISSUE TITLE
Add clarity to 'composer update' in next MAJOR update by changing it to 'composer update-lock'

### ISSUE THREAD

**Issue by SilbinaryWolf** [composer/composer#5516]
When first getting used to Composer and trying to understand how it works, the language used in the commands isn't very intuitive.

If possible, I feel it would be best if we added an "update-lock" command and deprecate "update" moving forward as it immediately tells the user that the command is updating the .lock file. 

I only bring this up as I was working with a front-end developer who didn't understand that the "update" command was updating the lock file and I feel it's not that clear either.

**Comment by alcohol** [comment]
Sorry, but no, that is not an appropriate description of what update does, nor does it warrant changing one of the most often used commands at all.
