### ISSUE TITLE
Do not install a dependency which requires a custom installer when running "composer install --no-plugins"

### ISSUE THREAD

**Issue by christian-weiss** [composer/composer#5517]
If your project requires as dependency of type e.g. "mysoftware-myplugin" (a string defined in your custom installer plugin) it needs a custom installer to be installed. 

I expect that composer aborts with a warning, that there is a unsatisfied condition when running:
composer install --no-plugins 
or
composer install --no-custom-installers

At the moment (composer 1.1.3 2016-06-26 15:42:08) the dependency will be installed to vendor/ dir as if it were of type "library". I can not imaging a case where this makes sense. When implementing a custom installer to install a dependency with it there must be a good reason why someone goes that extra mile.

If you do not want to introduce this backward compatibility break, then at least issue a warning informing the user that package xyz was installed to vendor/ dir instead of using the custom installer.

**Comment by alcohol** [comment]
Installers offer additional features/functionality. Changing the installation target directory is just one of those, and it is completely optional. I do not see any good reason for completely not installing a package, simply because `--no-plugins` was passed.

There is no `--no-custom-installers`.

**Comment by christian-weiss** [comment]
Technically a custom installer is completly overriding build-in installer. 
Sementically i strongly disagree. If a plugin says "i am special. I am not of a build-in standard type." it means to me: "treat me special.". For me defining a non-build-in type is like defining a dependency to a custom installer. If the custom installer is not available, then dependency constraint failed and should lead to abort or at least a warning, when falling back to a build-in installer.

**Comment by christian-weiss** [comment]
Example:
To install a wordpress-plugin or a wordpress-theme to vendor/ dir do not make sense to me.

**Comment by christian-weiss** [comment]
about: --no-custom-installers
Please run:
composer install --blabla
and see this option listed. 

When running:
composer install --no-custom-installers
you get a warning:
You are using the depricated option "no-custom-installers". Use "no-plugins" instead.

I recommand to replace the info for: composer install --blabla from "--no-custom-installers" to "--no-plugins"

**Comment by stof** [comment]
But fordidding to install packages changing the `type` because of plugins being disabled is wrong to. It is very common to specify a special type to identify plugins for a given framework, while not having a custom installer for them.

**Comment by christian-weiss** [comment]
Do you mean software-plugins that uses https://github.com/composer/installers to be installed?

**Comment by Seldaek** [comment]
Many symfony bundles for example come with symfony-bundle as type, which allows for things like https://packagist.org/packages/list.json?type=symfony-bundle - yet there is no need for a custom installer for those, as they don't have any special installation requirements, the type is merely informational (for now anyway, this might change if symfony wanted to do special things when installing plugins).

So having even a warning when the LibraryInstaller ends up being used for non-library-typed packages sounds like a pain for a lot of people.

If the packages requiring a custom installer to be there for them to work require that custom installer, all works well AFAIK, so why not do that?
