### ISSUE TITLE
OpenSSL Errors on Installation Instructions

### ISSUE THREAD

**Issue by thelostspore** [composer/composer#5519]
Following the [installer instructions](https://getcomposer.org/download/), and running `php composer-setup.php` after Installer was verified, this was output: 

```
All settings correct for using Composer

Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in /Users/thelostspore/composer-setup.php on line 762

Warning: file_get_contents(): Failed to enable crypto in /Users/thelostspore/composer-setup.php on line 762

Warning: file_get_contents(https://getcomposer.org/versions): failed to open stream: operation failed in /Users/thelostspore/composer-setup.php on line 762

Warning: Invalid argument supplied for foreach() in /Users/thelostspore/composer-setup.php on line 508
None of the 0 stable version(s) of Composer matches your PHP version (5.5.34 / ID: 50534)
```

Could I be missing other requirements for installing composer?

**Comment by thelostspore** [comment]
Figured it out. Dug through the downloaded `composer-setup.php` source and discovered this line in `getSystemCaRootBundlePath` method body:

```php
 // If SSL_CERT_FILE env variable points to a valid certificate/bundle, use that.
 $envCertFile = getenv('SSL_CERT_FILE');
```

I downloaded a [cert bundle](https://curl.haxx.se/ca/cacert.pem) and set this directory for values in my php.ini (`/etc/php.ini`). 

```.ini
[openssl]
openssl.cafile=/etc/ssl/certs/cacert.pem
openssl.capath=/etc/ssl/certs/
```

I set the env var `SSL_CERT_FILE` to the path of the cert file and the openssl issues were resolved.

**Comment by srayhunter** [comment]
I ran into the same issue with Homebrew and PHP 7.0.8. 

I downloaded the cacert: 
```wget http://curl.haxx.se/ca/cacert.pem```

I then update the `openssl.cafile` in the `php.ini` file.

**Comment by thelostspore** [comment]
@srayhunter @alcohol 

Unfortunately setting the `SSL_CERT_FILE` env variable resulted in  `curl` certificate verification failures. I've seen [some discussion](https://github.com/Homebrew/legacy-homebrew/issues/32019) about unsetting the env variable to resolve these issues for `curl`, which resolved the issue for me too.

I've observed similar OpenSSL errors on several other developer's workstations as well. In a few cases, the devs were using `1.0-dev` and attempted `composer self-update --stable`. They received OpenSSL errors similar to the ones documented [in this issue](https://github.com/composer/composer/issues/4212). Note, none of these developers are using an HTTP proxy, which seemed to be the problem in that issue.

Output from one such developer's workstation: 

```
userX$ composer self-update --stable
                                                                               
  [Composer\Downloader\TransportException]                                     
  The "https://getcomposer.org/versions" file could not be downloaded: SSL op  
  eration failed with code 1. OpenSSL Error messages:                          
  error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify   
  failed                                                                       
  Failed to enable crypto                                                      
  failed to open stream: operation failed                                      
                                                                               

self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--] [<version>]
```

**Comment by thelostspore** [comment]
@alcohol, I may suggest `bug` label

**Comment by thelostspore** [comment]
This seems to be the same issue as https://github.com/composer/composer/issues/2798, which is locked & limited to contributors.

**Comment by alcohol** [comment]
The real issue is that 99 out of 100 times, this is simply the result of a broken and/or improperly configured environment on the user side. There is nothing Composer can do to remedy this. So I am very reluctant with assigning the "bug" label to openssl related issues.

**Comment by thelostspore** [comment]
In our office, 3/5 developers on our team have OpenSSL-related issues with Composer.

The failure messages do not provide any indication as to what the real issue is, and OpenSSL configuration is not listed as a system [requirement](https://getcomposer.org/doc/00-intro.md#system-requirements).

How exactly could OpenSSL be broken or misconfigured for Composer, specifically? I don't have OpenSSL related issues with any other OSS. I'm using the built-in system version that ships with ElCap (0.9.8zh), using default configuration.

Given that this has been an ongoing [issue](https://github.com/composer/composer/issues/2798), I have two ideas - could the composer installation script attempt to check if OpenSSL configuration is "correct"? Perhaps the script could point the user to a wiki with instructions as to how to remedy their workstation if there are problems.

Is there anything out there that would help a user debug/diagnose these problems for Composer?

**Comment by srayhunter** [comment]
@alcohol Here is how I can reproduce my issue.

Homebrew installed php7.0 which uses the homebrew version of openssl (openssl: stable 1.0.2h)
My version on el capitan is (0.9.8zh) like @thelostspore. 

When running this step `php composer-setup.php` it is failing because it using the openssl version from homebrew and not the osx version. This can be a little confusing with the capath not getting set properly. 

In my case, the capath that composer-setup.php was using was coming from the system and not the one from homebrew's version of php.

composer-setup.php found `/etc/ssl/certs`, which is the openssl (0.9.8zh) version. 

my php7.0 version are the following:
array(8) {
  ["default_cert_file"]=>
  string(31) "/usr/local/etc/openssl/cert.pem"
  ["default_cert_file_env"]=>
  string(13) "SSL_CERT_FILE"
  ["default_cert_dir"]=>
  string(28) "/usr/local/etc/openssl/certs"
  ["default_cert_dir_env"]=>
  string(12) "SSL_CERT_DIR"
  ["default_private_dir"]=>
  string(30) "/usr/local/etc/openssl/private"
  ["default_default_cert_area"]=>
  string(22) "/usr/local/etc/openssl"
  ["ini_cafile"]=>
  string(0) ""
  ["ini_capath"]=>
  string(0) ""
}

I wonder about the following method: self::getSystemCaRootBundlePath()

**Comment by srayhunter** [comment]
@alcohol 
In the `$caBundlePaths` under the `getSystemCaRootBundlePath()` there could be some other locations for homebrew as well for openssl and curl similar to macports. I am not sure if that is feasible or not.

I modified it this way:
```
  $caBundlePaths = array(
            '/etc/pki/tls/certs/ca-bundle.crt', // Fedora, RHEL, CentOS (ca-certificates package)
            '/etc/ssl/certs/ca-certificates.crt', // Debian, Ubuntu, Gentoo, Arch Linux (ca-certificates package)
            '/etc/ssl/ca-bundle.pem', // SUSE, openSUSE (ca-certificates package)
            '/usr/local/share/certs/ca-root-nss.crt', // FreeBSD (ca_root_nss_package)
            '/usr/ssl/certs/ca-bundle.crt', // Cygwin
            '/opt/local/share/curl/curl-ca-bundle.crt', // OS X macports, curl-ca-bundle package
            '/usr/local/share/curl/curl-ca-bundle.crt', // Default cURL CA bunde path (without --with-ca-bundle option)
            '/usr/share/ssl/certs/ca-bundle.crt', // Really old RedHat?
            '/etc/ssl/cert.pem', // OpenBSD
            '/usr/local/etc/ssl/cert.pem', // FreeBSD 10.x
            '/usr/local/etc/openssl/cert.pem' // OS X homebrew openssl 
        );
```

And that worked for me.

**Comment by thelostspore** [comment]
@srayhunter I do not think ElCap ships with an /etc/ssl directory.

**Comment by thelostspore** [comment]
For the time being, I have modified the installer in a hacky way.

This appears to be working on multiple developer workstations, with a few OpenSSL warnings about using a version older than `0.9.8zh`. `composer diagnose` fails only on those machines as well.

```bash
CERT_DIR="/tmp/certz"

command -v 'composer' > /dev/null

if [ $? == 0 ]; then
  echo "Composer already installed."
  exit 0
fi

if [ ! -d $CERT_DIR ]; then
  echo "Made folder for certs: ${CERT_DIR}"
  mkdir -p $CERT_DIR
fi

CERT_FILE="$CERT_DIR/cacert.pem"

# Download certificate bundle
echo "Downloading cert file..."
curl "https://curl.haxx.se/ca/cacert.pem" -so "$CERT_FILE"

# note: wget does not ship with OSX
echo "Downloading installer signature..."
EXPECTED_SIGNATURE=$(curl https://composer.github.io/installer.sig -s)

if [ $? -gt 0 ]; then
  echo "Could not fetch installer signature"
  exit 1
fi

php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")

echo "Comparing signatures..."
if [ "$EXPECTED_SIGNATURE" == "$ACTUAL_SIGNATURE" ]
then
  echo "Attempting installation of composer..."
  SSL_CERT_FILE="$CERT_FILE" bash -c "php composer-setup.php --quiet"

  if [ $? -gt 0 ]; then
    echo "Composer installation failed."
    exit 1
  fi

  echo "Moving phar into /usr/local/bin"
  mv "$(pwd)/composer.phar" /usr/local/bin/composer

  # drop the cert bundle in the .composer dir if composer installer didn't
  if [ -d "$HOME/.composer" ] && [ ! -f "$HOME/.composer/cacert.pem" ]; then
    mv $CERT_FILE "$HOME/.composer"
  fi

  command -v "composer" > /dev/null

  if [ $? == 0 ]; then
    echo "Composer successfully installed!"
    echo "Try running the composer command."
  else
    rm composer-setup.php
    exit 1
  fi

    rm composer-setup.php
    exit 0
  else
    echo "$Invalid Composer installer signature"
    rm composer-setup.php
    exit 1
  fi
fi
```

**Comment by srayhunter** [comment]
@thelostspore that might be a carry over from previous version of OSX or it might be some additional configuration that I have done in the past. 

It is a directory that `composer` picks up during the `getSystemCaRootBundlePath()` method call though - but this would explain the reason that perhaps developers have issues. It might be previous configurations or having homebrew installed and their php version is using a different version of openssl and the system caroot bundle path is not finding the right certs. 

I do like the idea of pulling the correct cert if needed during the installation process. But like @alcohol said, it falls more to configuration than anything. I would think that the `getSystemCaRootBundlePath()` might include testing other locations as well that might incorporate `Homebrew`.

**Comment by alcohol** [comment]
I have been using OSX + Homebrewed PHP/OpenSSL for several years now and never had any issues. So pretty sure it's a configuration issue on your end. There is virtually nothing Composer can do about that :/

**Comment by srayhunter** [comment]
@alcohol where is composer finding your ssl cacert.pem file at or is it downloading one for you?

I think the issue might be if a user setups up a cert for another environment, then composer finds it and tries to use it. For example, I have created /etc/ssl/certs to handle some certs for a java environment. I would not think that composer would search there since that is a linux setup and not osx. Composer finds the directory and uses that even though that directory location is for "Debian, Ubuntu, Gentoo, Arch Linux (ca-certificates package)" and not OSX.

Thoughts?

**Comment by alcohol** [comment]
If Composer cannot determine the CA file through regular means (for logic behind it, see [code](https://github.com/composer/ca-bundle/blob/5df9ed0ed0c9506ea6404a23450854e5df15cc12/src/CaBundle.php#L64)), it simply iterates a list of known directories (based on the defaults of several different OS) and uses the first one that exists. It is irrelevant whether or not that directory is a default on your actual OS, since Composer does not care what your OS is.

**Comment by alcohol** [comment]
So in short, if you want to use a specific cert/directory of certs, use the appropriate environment variables, or configure them in your [`php.ini`](http://php.net/manual/en/openssl.configuration.php).

**Comment by thelostspore** [comment]
Given that the Composer installer [validates](https://github.com/composer/getcomposer.org/blob/23046bcea5f75f97b74025124d0cf7f53c901a6f/web/installer#L1048) any found cert bundles and as a last resort uses [bundled root CAs](https://github.com/composer/getcomposer.org/blob/23046bcea5f75f97b74025124d0cf7f53c901a6f/web/installer#L1063), at a cursory glance, I'm perplexed as to how anyone could still be running into OpenSSL issues.

@alcohol, does the current composer installer use code from the [ca-bundle](https://github.com/composer/ca-bundle) repo? I'm seeing some of that code duplicated in the [installer script source](https://github.com/composer/getcomposer.org/blob/23046bcea5f75f97b74025124d0cf7f53c901a6f/web/installer), but not imported.

**Comment by srayhunter** [comment]
@thelostspore this is the issue that I ran into. It found a configuration that was not meant for it and used it and I ran into the issue with the failure to verify the cert. My initial concern was that it found the directory, but not the ca-cert under that directory. But it still used the directory and since there was no ca-cert to use, it failed. This is just an outlier issue though.

**Comment by alcohol** [comment]
@thelostspore it's duplicated because the installer has to be served as a single whole file, otherwise we cannot offer hash validated install instructions as documented on https://getcomposer.org/download/

**Comment by camdixon** [comment]
@thelostspore I am running into similar issue.  While you could be right about if composer make a change can you point to documentation on how to configure properly with this?  Also, the @thelostspore is correct in saying there is something you can do about it because the error message is not that helpful.

**Comment by alcohol** [comment]
@camdixon did you read all replies to this thread? Several solutions have already been mentioned.

**Comment by alcohol** [comment]
Also the error message is generated by PHP, not by Composer. There is nothing we can do about it.

**Comment by srayhunter** [comment]
@camdixon have much troubleshooting have you done? Like @alcohol mentioned, we have solutions, I was curious what might be the cause for your issue.

**Comment by camdixon** [comment]
@srayhunter going to try one of @thelostspore solutions tonight.  I was trying to change my composer.json config and I checked my auth.json which was correct.  Just not sure if my composer.json is correct considering @alcohol comments.

**Comment by alcohol** [comment]
The `composer.json` contents should have nothing to do with your openssl setup (unless you explicitly configure composer not to use https/ssl, which we **highly discourage**). Look at your php.ini setting as I suggested, or try setting the [environment variable](https://getcomposer.org/doc/03-cli.md#composer-cafile) and see if that resolves it.

**Comment by thelostspore** [comment]
Even though this issue is now closed, I've witnessed this error on other workstations and still think the messaging  should be modified. The suggestion is to remove the `All settings correct for using Composer` message - test `file_get_contents()` to see if warnings are emitted, and if so, let the user know their SSL settings are not configured correctly.

**Comment by wmelton** [comment]
This is closed but leaving for others incase they land here - 

If you're on a Mac, fix is simple: 

`sudo mkdir -p /usr/local/libressl/etc/ssl/certs
sudo curl -o /usr/local/libressl/etc/ssl/cert.pem https://curl.haxx.se/ca/cacert.pem`

**Comment by AleksSv** [comment]
I don't think I saw this mentioned, but a possible trigger of this error could be incorrect permissions for ssl directories.

For me it turned out I had the certs directory as 700 instead of 755 (remember this is certs not private).

Doing 
sudo chmod 755 certs
Fixed the problem for me

**Comment by glennmuk** [comment]
Yes - removing Kaspersky AV fixed this problem for me too.  On Windows 10.
