### ISSUE TITLE
isInstalled() of custom installer plugin is not called

### ISSUE THREAD

**Issue by christian-weiss** [composer/composer#5521]
When running 

```
composer remove myvendor/package-that-requires-a-custom-installer
```

it get this line:

```
Package "myvendor/package-that-requires-a-custom-installer" listed for update is not installed. Ignoring.
```

"myvendor/package-that-requires-a-custom-installer" is of type "mysoftware-module".

 When running:

   composer install

the package is installed to the custom directory. This leads me to the conclusion that my custom installer is recognized as responsible for that package type. Means the supports() method of my custom installer works. Adding an echo statement to the isInstalled() method do not show up in the output of composer, means this method was not called by composer. A bug?

**Comment by alcohol** [comment]
It would be very helpful if you can share the source of your custom installer. Without it, we can only guess.

**Comment by christian-weiss** [comment]
https://github.com/christian-weiss/composer-installer-sample
composer 1.1.3 2016-06-26 15:42:08

**Comment by donaldinou** [comment]
Your file containing the class "MyProjectInstallerPlugin" is named "VagrantProjectInstallerPlugin.php" it should be MyProjectInstallerPlugin.php or else autoload will not work.

Why don't you self-update composer?

**Comment by farhanwazir** [comment]
If you wanted to save your time then i recommend you [CPC Installer Plugin](https://github.com/farhanwazir/cpcinstaller). Hope this will help many developer's. 

[CPC Installer Plugin](https://github.com/farhanwazir/cpcinstaller) has many flexibility to manage your installer. I personally loved it when writing that ;)

**Comment by Seldaek** [comment]
Auto-closing this as it's marked as support request and has not received any update in a long time.
