### ISSUE TITLE
php extension requirement handling

### ISSUE THREAD

**Issue by staabm** [composer/composer#5525]
With the following command

```
composer global require "etsy/phan:dev-master"
```

on a plain ubuntu14 vm with php7 I got 

```
  Problem 1
    - Installation request for etsy/phan dev-master -> satisfiable by etsy/phan[                                                                                                     dev-master].
    - etsy/phan dev-master requires ext-ast * -> the requested PHP extension ast                                                                                                      is missing from your system.
```

after solving this problem by installing php-ast I now get

```
  Problem 1
    - Installation request for etsy/phan dev-master -> satisfiable by etsy/phan[dev-master].
    - etsy/phan dev-master requires ext-sqlite3 0.7-dev -> the requested PHP extension sqlite3 is missing from your system.
```

couldnt composer check all required extensions at once and give me information about all required extensions?
especially in a workflow where the person who installs the missing extensions is not the one who runs the CLI command this kind of single-cause error messages render the process time-comsuming.

```
composer --version
Composer version 1.1.3 2016-06-26 15:42:08

php --version
PHP 7.0.8-4+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-4+deb.sury.org~trusty+1, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by alcohol** [comment]
As far as I understand the solving process, this is not possible currently.

**Comment by alcohol** [comment]
But maybe @naderman can comment on this?

**Comment by naderman** [comment]
No it's not, at the time that one of these issues is detected it's unclear if the next one will actually become one. As long as it's the same package requiring several non existant packages though we could potentially figure this out at the time the error is reported.

**Comment by Seldaek** [comment]
Auto-closing as this hasn't been updated in over 6months and is marked as a question. If there is a real bug to consider please let us know.
