### ISSUE TITLE
composer checking require-dev dependencies when using --no-dev

### ISSUE THREAD

**Issue by marl-scot** [composer/composer#5526]
With the following composer.json:

{
  "name": "namespace/package_name",
  "description": "description_text",
  "minimum-stability": "dev",
  "license": "proprietary",
  "authors": [
    {
      "name": "name",
      "email": "email"
    }
  ],
  "autoload": {
    "psr-4": {
      "": "src/"
    }
  },
  "require": {
    "stecman/symfony-console-completion": "0.7.0",
    "symfony/console": "3.0.x-dev",
    "padraic/phar-updater": "1.0.*",
    "psr/log": "^1.0",
    "symfony/monolog-bundle": "*"
  },
  "require-dev": {
    "phpunit/phpunit": "5.4.*",
    "phing/phing": "2.9.*",
    "phploc/phploc": "3.0.*",
    "pdepend/pdepend": "2.2.*",
    "phpmd/phpmd": "2.4.*",
    "sebastian/phpcpd": "2.0.*",
    "doxphp/doxphp": "0.2.*"
  }
}

When I run this command:

 $ composer -vvv --no-dev install

I get this output:

Reading ./composer.json
Loading config file /home/matt/.composer/auth.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/home/matt/source/workspace.pin/sshwhite): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /home/matt/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 1.1.3 (2016-06-26 15:42:08) with PHP 5.5.9-1ubuntu4.17 on Linux / 3.19.0-32-generic
Loading composer repositories with package information
Downloading https://packagist.org/packages.json
Writing /home/matt/.cache/composer/repo/https---packagist.org/packages.json into cache
Updating dependencies
Reading /home/matt/.cache/composer/repo/https---packagist.org/p-provider-2013.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/p-provider-2014.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/p-provider-2015.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/p-provider-2015-10.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/p-provider-2016-01.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/p-provider-2016-04.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/p-provider-2016-07.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/p-provider-archived.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/p-provider-latest.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-stecman$symfony-console-completion.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-symfony$console.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-symfony$polyfill-mbstring.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-padraic$phar-updater.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-padraic$humbug-get-contents.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-symfony$finder.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-psr$log.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-symfony$monolog-bundle.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-symfony$monolog-bridge.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-monolog$monolog.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-symfony$http-kernel.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-symfony$event-dispatcher.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-symfony$http-foundation.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-symfony$dependency-injection.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-symfony$config.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-symfony$filesystem.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-symfony$debug.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-symfony$polyfill-php54.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-symfony$polyfill-php55.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-ircmaxell$password-compat.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-phpunit$phpunit.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-myclabs$deep-copy.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-phpspec$prophecy.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-phpunit$php-code-coverage.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-phpunit$php-file-iterator.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-phpunit$php-text-template.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-phpunit$php-timer.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-phpunit$phpunit-mock-objects.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-sebastian$comparator.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-sebastian$diff.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-sebastian$environment.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-sebastian$exporter.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-sebastian$global-state.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-sebastian$object-enumerator.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-sebastian$resource-operations.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-sebastian$version.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-symfony$yaml.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-phpdocumentor$reflection-docblock.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-doctrine$instantiator.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-sebastian$recursion-context.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-phpunit$php-token-stream.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-sebastian$code-unit-reverse-lookup.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-dflydev$markdown.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-phpdocumentor$reflection-common.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-phpdocumentor$type-resolver.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-webmozart$assert.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-phing$phing.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-phploc$phploc.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-sebastian$finder-facade.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-sebastian$git.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-theseer$fdomdocument.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-pdepend$pdepend.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-phpmd$phpmd.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-sebastian$phpcpd.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-doxphp$doxphp.json from cache
Reading /home/matt/.cache/composer/repo/https---packagist.org/provider-symfony$expression-language.json from cache
Resolving dependencies through SAT
Dependency resolution completed in 0.001 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpunit/phpunit 5.4.x-dev requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
    - phpunit/phpunit 5.4.6 requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
    - phpunit/phpunit 5.4.5 requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
    - phpunit/phpunit 5.4.4 requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
    - phpunit/phpunit 5.4.3 requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
    - phpunit/phpunit 5.4.2 requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
    - phpunit/phpunit 5.4.1 requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
    - phpunit/phpunit 5.4.0 requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
    - Installation request for phpunit/phpunit 5.4.* -> satisfiable by phpunit/phpunit[5.4.0, 5.4.1, 5.4.2, 5.4.3, 5.4.4, 5.4.5, 5.4.6, 5.4.x-dev].

And I expected this to happen:

If using the --no-dev flag, then nothing from the 'require-dev' section should be looked at.
If i try and remove the first entry from require-dev ("phpunit/phpunit": "5.4.*"), then try again, I just get errors about phploc/phpmd etc.

If i remove the require-dev section totally from composer.json, then the the install works fine.

I use the latest phpunit and php on my CI server, but on my production system i am running PHP 5.5.9

I don't understand why composer is trying to resolve dependencies from the require-dev section when i have asked it to ignore that set of entries?

thanks

matt

**Comment by alcohol** [comment]
See #5523
