### ISSUE TITLE
autoload_static ignores autoload_classmap ?

### ISSUE THREAD

**Issue by gossi** [composer/composer#5533]
I do use puli with composer. Puli puts its factory in autoload_classmap.php (it's hooked into autoload generation through a plugin). So far so good, it worked on my dev machine (php5.5). It wasn't loading on my prod server, which runs php7.

I was looking at the generated autoload code. So, as far as I can see, if it is php 5.6 or higher composer is using the static autoloader and as such `autoload_static.php`. I realized that autoload_static doesn't contain the entries from `autoload_classmap.php`.

Composer Version: 1.2

**Comment by alcohol** [comment]
If puli supplements the `autoload_classmap.php`, then it is up to Puli to also makes sure that the `autoload_static.php` gets updated.
