### ISSUE TITLE
Question: how to ignore non-existence of autoload/classmap folders?

### ISSUE THREAD

**Issue by Namek** [composer/composer#5536]
I have Laravel 4 webapp that includes 6 web stores (websites where you buy things through a browser) with big part of common code plus some files that are distinct for specific web stores.

For each store I setup distinct testing environment. Yesterday I saw this:

```
Generating autoload files

                                                                                                                       
  [RuntimeException]                                                                                                   
  Could not scan for classes inside "app_stores/webstore_1/controllers" which does not appear to be a file nor a folder  
```

With the following `composer.json` (web store names had to be obfuscated):

```json
"autoload": {
	"classmap": [
		"app/commands",
		"app/controllers",
		"app/database/migrations",
		"app/database/seeds",
		"app/viewcomposers",
		"app/common/src",
		"app/facades",
		"app/tests/TestCase.php",

		"app_stores/webstore_1/controllers",
		"app_stores/webstore_2/controllers",
		"app_stores/webstore_3/controllers",
		"app_stores/webstore_4/controllers",
		"app_stores/webstore_5/controllers",
		"app_stores/webstore_6/controllers"
	]
},
```

And now, for webstore_1 folders for webstores 2-6 are not existing. Is there a way to not throw this exception for those non-existing folders?

What's strange for me is that it appeared to me just today. But I updated composer on test machine yesterday, not sure about previous version but googling shows me that this exception was thrown few years before so I would assume it's not a new behaviour but maybe I'm wrong?

**Comment by Seldaek** [comment]
I don't think it is new no, and I am not sure why it worked before, but generally speaking we throw this because it is usually due to a misconfiguration and therefore the user should realize it very quickly. Warnings tend to be ignored..
