### ISSUE TITLE
hostname resolving error

### ISSUE THREAD

**Issue by alverdiyev91** [composer/composer#5539]
With the following composer.json:

```json
{
    ...
}
```

When I run this command:

```
installing composer-setup.exe on windows server 2008
```

I get this output:

```
The "http://getcomposer.org/versions" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: No such host is known. 
failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known.

```

And I expected this to happen:

**Comment by alcohol** [comment]
Either your DNS is not working properly, or you have a firewall/gateway/proxy blocking traffic. Please try again.

**Comment by musalo** [comment]
Hi.Unable to install Composer on my window 10
The "http://getcomposer.org/versions" file could not be downloaded: failed to open stream: No connection could be made because the target machine actively refused it.
