### ISSUE TITLE
Deploy a yii project to a ubuntu server from windows.

### ISSUE THREAD

**Issue by ely029** [composer/composer#5540]
Hello I have a question of regarding composer. I am new here in composer. Is there a way to deploy the project from the usb to the ubuntu server. the project is developing in the windows.

Is that possible? thanks

**Comment by stof** [comment]
Composer is not a deployment tool, so this is the wrong place to ask

**Comment by alcohol** [comment]
@stof is right. While unfortunately we cannot stop users from using Composer on production machines, it really is not a practice we can recommend or support. If you want to look into solutions for deployment, maybe give http://deployer.org a try?
