### ISSUE TITLE
in win10 cmd messy code

### ISSUE THREAD

**Issue by dingdayu** [composer/composer#5542]
in win10 x64:

![image](https://cloud.githubusercontent.com/assets/2040348/17085125/35f66cde-5203-11e6-9f6f-74fd7e502eb5.png)

**Comment by alcohol** [comment]
Can you check if this comment helps: [5323#issuecomment-220871883](https://github.com/composer/composer/issues/5323#issuecomment-220871883)

**Comment by dingdayu** [comment]
@alcohol I consulted a senior, he told me it was because ASCII Color .

**Comment by alcohol** [comment]
@dingdayu I know, you can explicitly turn off ansi coloring using the `--no-ansi` flag.

But the comment I linked contains a setting you can toggle on/off, for the windows command prompt (win10 only). That should also fix it, and you can have colored output then.

**Comment by ste93cry** [comment]
Same problem here after upgrading to Windows 10 Anniversary Update (build 10.0.14393). It worked fine before

**Comment by stof** [comment]
see the discussion in the Symfony issue referenced above. PHP will need to tell windows it wants this feature. Enabling it for all executables in the previous Windows 10 version was a mistake.

**Comment by cirdog** [comment]
If this hasn't been mentioned before, the global workaround for Windows is:

```
C:\ProgramData\ComposerSetup\bin\composer.bat
(edit its content)
php "%~dp0composer.phar" %* --no-ansi
```

Adding the "--no-ansi" flag at the launch script of composer eliminates the need to flag it for every command.
