### ISSUE TITLE
Autoload overwrite not working?

### ISSUE THREAD

**Issue by RobQuistNL** [composer/composer#5545]
With the following composer.json:

```json
{
    (...)
    "require": {
        "google/apiclient": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "NewGoogle\\": "vendor/google/apiclient/src/Google/"
        }
    },
    "require-dev": {
        "codeception/codeception": "^2.2",
        "flow/jsonpath": "^0.3.1"
    }
   (...)
}
```

I expect the code from the Google ApiClient (Which is namespaced like "Google_Client") to be available under "\NewGoogle\Client". Its not available under any name but the original one.

```
$test = new Google_Client();
var_dump($test::LIBVER);
``` 

Gives me 2.0.0

```
$test = new \NewGoogle\Google_Client();
$test = new \NewGoogle\Google\Client();
$test = new \NewGoogle\Client();
``` 

All gives me exceptions. I'm doing this because there is a bit of legacy code that is using a very old version of the Google_Client and I don't want to touch that.

Does anyone know why I can't use the new library this way? What am I doing wrong? I've tried psr-0 and psr-4 but its not working :/

**Comment by staabm** [comment]
the feature you are using does not work the way you use it ;-).

the key - in your case `"NewGoogle\\"` - needs to match the namespaces within the sources.
there is no mapping in this context.

**Comment by RobQuistNL** [comment]
Ah.. I thought i could "overwrite" the namespace (or prepend one) using this strategy. Well, seems like we'll just have to clean up the legacy code then, right?

**Comment by staabm** [comment]
I guess it depends on the amount of work (and size of your libs). you might also use some kind of BC layer using e.g. `class_alias`.

**Comment by RobQuistNL** [comment]
The old Google_Client library we were using was version  0.6.4, and since they are now on 2.0.x I assumed there were a lot of BC breaks. This turns out to be not that bad and I've updated the legacy code to support the new library. Works like a charm!

Thanks for the quick reply @staabm
