### ISSUE TITLE
--prefer-source sometimes fails (“Not a git repository”)

### ISSUE THREAD

**Issue by kinglozzer** [composer/composer#5546]
Firstly, this could potentially be an issue with Travis (or how it’s set up), so apologies if that is the case.

A bit of background: I’m using [silverstripe-travis-support](https://github.com/silverstripe-labs/silverstripe-travis-support), which generates a `composer.json` file for CI tests on Travis. I have two packages, the test classes in one package extend a `TestCase` class defined in the other (is this a bit of an anti-pattern?). I’m using `--prefer-source` as a dist version will ignore the `tests/` directory (as it is excluded from export in my `.gitattributes` file).

When Composer runs an install with the [generated `composer.json`](https://travis-ci.org/bigfork/silverstripe-oauth-login/jobs/145853708#L176), it fails to create a git clone of some of the packages. For example, installing silverstripe/framework fails (https://travis-ci.org/bigfork/silverstripe-oauth-login/jobs/145853708#L199-L204) despite the fact that the referenced commit [definitely exists](https://github.com/silverstripe/silverstripe-framework/commit/96b061ffffd472f917273b43790f5aaa2f9f89b4), and attempting the same install locally works.

This leads me to two questions:
1. Is anyone aware of anything that could cause the failure to install from source? The fact that the install from source works locally is what leads me to believe this could possibly be a Travis issue (feel free to close this issue if it’s misplaced).
2. Is it an anti-pattern to have, for example, unit tests in package B that extend a class defined in the unit tests of package A? I’m relying on `--prefer-source` working and making the `tests/` directory available, is that wrong (the wording “prefer” source suggests it might be)?

Any insights appreciated :)

**Comment by alcohol** [comment]
1. Will have to investigate.

2. Anti-pattern? No. Very unusual however, and I personally cannot see any good argument in favor of such a setup.

**Comment by alcohol** [comment]
It might be that this is also an issue related to the changes introduced by #5384 (just like #5541).

**Comment by kinglozzer** [comment]
Sorry it’s taken me a while to respond.

> Anti-pattern? No. Very unusual however, and I personally cannot see any good argument in favor of such a setup.

It was just to save duplicating code for test setup across packages. It’s a pretty tiny amount of code so I can just copy it anyway, but I wanted try to figure out why this wasn’t working how I expected :)

> It might be that this is also an issue related to the changes introduced by #5384 (just like #5541).

It looks like it could possibly be related to #5384, but I can’t see why Travis would be preserving those cache directories between builds - I’ve not set up any caching, and I’ve even tried explicitly setting `cache: false` in travis.yml to no avail.

**Comment by Seldaek** [comment]
Auto-closing as this hasn't been updated in over 6months and is marked as a support request. If there is a real bug to consider please let us know.
