### ISSUE TITLE
method to force usage of path repos - even if version restraint specified?

### ISSUE THREAD

**Issue by bkdotcom** [composer/composer#5548]
With the following composer.json:

```json
{
    "minimum-stability": "dev",
    "repositories": [
        {
            "type": "path",
            "url": "~/packages/*"
        }
    ],
    "require": {
        "foo/bar": "*"
    }
}
```

foo/bar's  composer.json:
```json
{
    "name": "foo/bar",
    "require": {
        "ding/dong": "^1.3"
    }
}
```

both foo/bar and ding/dong can be found in ~/packages
I believe because foo/bar is requiring a specific version of ding/dong, it's grabbing the package via packagist.     if I change foo/bar's composer.json to require "ding/dong": "\*"  *then* the path repo is used:
```a
Symlinked from path-omitted

    REASON: foo/bar dev-master requires ding/dong * -> satisfiable by ding/dong[list of versions that includes dev-master].
```

How can I force the usage of the path repo package without modifying the composer.json of sub-dependencies?

**Comment by stof** [comment]
This is because the version guessed by the path repository for your ``ding/dong`` local package does not match the ``^1.3`` constraint (it is probably guessed as being ``dev-master`` and you don't have a branch alias for dev-master)

**Comment by bkdotcom** [comment]
@stof  that's the missing piece I didn't know about thanks!

in my root project I a new require:
`"ding/dong": "dev-master as 1.3.x-dev"`

now my local path ding/dong repo is used!
