### ISSUE TITLE
 [LogicException] Composer repositories that have providers can not load... Eroor 

### ISSUE THREAD

**Issue by morwin10** [composer/composer#5550]
With the following composer.json in `C:\Users\morwin\AppData\Roaming\Composer\composer.json ` file :

```json

{
    "require": {
        "phpunit/phpunit": "5.0.*",
        "laravel/installer": "^1.3"
    },
    "repositories": [
    {
         "type": "composer",
         "url": "https://packagist.org"
    },
    { "packagist": false }
    ]
}


```

When I run this command :

```
composer create-project laravel/laravel Laravel-Angular2

```

I get this output:

```
  [LogicException]
  Composer repositories that have providers can not load the complete list of
   packages, use getProviderNames instead.


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]


```

And also if i try to enter this url from the browser
https://packagist.org/

I get:
You can not access this site
packagist.org closed the connection unexpectedly.

And with this VPN chrome extention I can have access

https://chrome.google.com/webstore/detail/gom-vpn-bypass-and-unbloc/ckiahbcmlmkpfiijecbpflfahoimklke

---

Why it's happen ?

**Comment by Seldaek** [comment]
Seems like network issues that we can not do much about
