### ISSUE TITLE
missing parameter for absolute path

### ISSUE THREAD

**Issue by kampfq** [composer/composer#5554]
sometimes i have to bind my projectfolder to an virtual drive in windows, dont ask why :D

when running composer from this virtual drive, means:
```
subst Y: C:\path\to\project
cd /D Y:\
composer update
```

the classmap will be created in this format:
```
'class' => 'path',
```

otherwise, when running composer in the real path, means:
```
cd C:\path\to\project
composer update
```

the classmap will be created in this format:
```
'class' => $baseDir . 'path'
```

only the second one runs fine otherwise no classes will be loaded

maybe i missed something but i didn't found a parameter to change this behavior

**Comment by alcohol** [comment]
@curry684: halp plz? Sorry buddy, but you're going to be my go-to reference for Windows issues until you tell me to stop bugging you :p

**Comment by kampfq** [comment]
the issue has something todo with the `isAbsolutePath()` in Autoloader.php on line 515, when removing the `if` it works

**Comment by alcohol** [comment]
Yea but it gets removed because $baseDir = / (which is an absolute path) in your situation, hence it makes no sense to put it in a variable I reckon.

**Comment by kampfq** [comment]
@curry684 yes, some kind of option to force the full path would be awesome. 
when this isn't possible, this ticket can be closed :)

**Comment by Seldaek** [comment]
Turns out there was a nasty bug in the normalizePath function :) Should be good now, but I'd be happy if you can confirm as I am not sure if I was able to fully reproduce the issue.
