### ISSUE TITLE
composer update nothing updates the dist keys in composer.lock if installed.json is out of date

### ISSUE THREAD

**Issue by PatrickRose** [composer/composer#5560]
We've just begun updating our composer workflow to include satis. The developer in charge of that has completed their work, and pushed their changes. I then checked it out, and tightened some dependencies and then ran `composer update nothing`

What I was expecting to happen was the `content-hash` to be updated `composer.lock` and nothing else, but the `dist` keys of all the packages was also updated. I've not really looked into this too much, but it looks like the contents of `installed.json` is used instead.

My colleagues's `installed.json` points to the correct place, but mine doesn't. If I run a `composer install` then composer (rightly) does nothing because all the dependencies I have installed match the requirements in the new version.

I don't really know what composer should do in this instance. I *think* that `composer update` should only be updating the dist of a package if it actually installed something, but a cursory read through of logic suggests that might be quite difficult to do performantly without a significant refactor.

**Comment by PatrickRose** [comment]
For now, we can work around this by telling everyone to delete their vendor directory and running `composer install` from scratch once this gets merged in.

**Comment by alcohol** [comment]
You should have run composer install (to get in sync) before tightening the constraints.

**Comment by PatrickRose** [comment]
I did.

```
$ git checkout live-branch
$ rm -rf vendor # Make sure that we're working from a fresh install
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing psr/log (1.0.0)
    Downloading: 100%
...
$ cat vendor/composer/installed.json
[
    {
        "name": "psr/log",
        "version": "1.0.0",
        "version_normalized": "1.0.0.0",
        "source": {
            "type": "git",
            "url": "https://github.com/php-fig/log.git",
            "reference": "fe0936ee26643249e916849d48e3a51d5f5e278b"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/php-fig/log/zipball/fe0936ee26643249e916849d48e3a51d5f5e278b",
            "reference": "fe0936ee26643249e916849d48e3a51d5f5e278b",
            "shasum": ""
        },
        "time": "2012-12-21 11:40:51",
        "type": "library",
        "installation-source": "dist",
        "autoload": {
            "psr-0": {
                "Psr\\Log\\": ""
            }
        },
        "notification-url": "https://packagist.org/downloads/",
        "license": [
            "MIT"
        ],
        "authors": [
            {
                "name": "PHP-FIG",
                "homepage": "http://www.php-fig.org/"
            }
        ],
        "description": "Common interface for logging libraries",
        "keywords": [
            "log",
            "psr",
            "psr-3"
        ]
    },
...
$ git checkout satis-branch
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Nothing to install or update
Generating autoload files
$ cat vendor/composer/installed.json
[
    {
        "name": "psr/log",
        "version": "1.0.0",
        "version_normalized": "1.0.0.0",
        "source": {
            "type": "git",
            "url": "https://github.com/php-fig/log.git",
            "reference": "fe0936ee26643249e916849d48e3a51d5f5e278b"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/php-fig/log/zipball/fe0936ee26643249e916849d48e3a51d5f5e278b",
            "reference": "fe0936ee26643249e916849d48e3a51d5f5e278b",
            "shasum": ""
        },
        "time": "2012-12-21 11:40:51",
        "type": "library",
        "installation-source": "dist",
        "autoload": {
            "psr-0": {
                "Psr\\Log\\": ""
            }
        },
        "notification-url": "https://packagist.org/downloads/",
        "license": [
            "MIT"
        ],
        "authors": [
            {
                "name": "PHP-FIG",
                "homepage": "http://www.php-fig.org/"
            }
        ],
        "description": "Common interface for logging libraries",
        "keywords": [
            "log",
            "psr",
            "psr-3"
        ]
    },
...
$ composer update nothing
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
$ git diff composer.lock
-                "type": "tar",
-                "url": "http://my-satis-url.com/dist/psr-log-fe0936ee26643249e916849d48e3a51d5f5e278b-zip-e71523.tar",
+                "type": "zip",
+                "url": "https://api.github.com/repos/php-fig/log/zipball/fe0936ee26643249e916849d48e3a51d5f5e278b",
                 "reference": "fe0936ee26643249e916849d48e3a51d5f5e278b",
-                "shasum": "499751f6d34037ff45397118ebd19b5e93778072"
+                "shasum": ""
```

Composer is doing the right thing when I run `composer install` and not doing anything - the versions still match up so the solver is correctly doing nothing, it's just the download locations that have changed.

**Comment by PatrickRose** [comment]
Possibly `installed.json` needs to be updated after every command, but this is only really a problem if your repositories have changed underneath your nose (which is what happened in our case)

**Comment by alcohol** [comment]
It looks to me like composer did the right thing.

**Comment by PatrickRose** [comment]
`composer update nothing` updated more than my `hash` or `content-hash` keys of the `composer.lock`. That doesn't sound right to me.

**Comment by PatrickRose** [comment]
Is there any additional thoughts on this? I'd offer to look into it but I'm not 100% on composer's internal so I'm wary of trying to do anything.

**Comment by alcohol** [comment]
I don't really see the problem here. If you commit a composer.json and lock file that are out of sync, you have to run `composer update --lock` to resync. As far as I know, all the behaviour here is quite simple and predictable. I'm not sure what scenario is confusing you or how you wound up in that state.

**Comment by PatrickRose** [comment]
The issue is that we've updated the place that we want composer to load the dependencies from. The reproduction scenario I have is:

```sh
mkdir composer-test
cd composer-test
git init
git commit --allow-empty -m "Tmp commit"
git checkout -b composer-using-packagist
# Create a quick and dirty composer.json - I'm using phpunit 4.3 since that's what's in my satis repo
echo '{"require": {"phpunit/phpunit": "4.3.*"}}' > composer.json
composer install
git add composer.*
git commit -m "Load phpunit from packagist"
git checkout master
# Remove the vendor directory - we'll reload things from satis
rm -rf vendor
git checkout -b composer-using-satis
# Use our satis repo
echo '{"repositories":[{"type":"composer","url":"satis-url-here"},{"packagist":false}],"require": {"phpunit/phpunit": "4.3.*"}}' > composer.json
composer install
git add composer.*
git commit -m "Load phpunit from satis"
git checkout composer-using-packagist
composer update --lock
# composer.lock gets updated
```

The `composer-using-packagist` branch has everything in sync, but `composer update --lock` is updating it because `vendor/composer/installed.json` is out of date.

**Comment by alcohol** [comment]
That is correct behaviour. After the last checkout (`git checkout composer-using-packagist`), you should have run `composer install` before running `composer update --lock`.

**Comment by PatrickRose** [comment]
Even if I run `composer install` before I run `composer update --lock` it updates the lock file. I have the right version of PHPUnit installed as far as composer is installed - I'm requesting the same version between the satis and packagist branches (4.3.8 in this instance).

The issue is that `vendor/composer/installed.json` is assumed to contain the correct place to download the packages from, which isn't the case when I switch between satis and packagist. If the versions didn't match up then this would be fixed by the composer install but part of the upgrade process for moving to satis was ensuring our dependency versions didn't change until someone had time to fully update them.

**Comment by alcohol** [comment]
> The issue is that `vendor/composer/installed.json` is assumed to contain the correct place to download the packages from, which isn't the case when I switch between satis and packagist.

But it is. Just because you are changing branches, that does not mean Composer understands your intentions. What might seem logical to you, in practice, simply is not. If you are installing the same version from both repositories, then Composer has no need to update the locally installed version once you've already completed a successful install. Composer only cares about fulfilling version constraints. We do not have source constraints.

There is not much that Composer can do in this scenario. Your are doing some funky things that we simply cannot account for. Be more conscious about your workflow and what you commit, that is all I can suggest.

**Comment by PatrickRose** [comment]
This boils down to the fact that I don't think it makes sense to update the `packages` key of `composer.lock` if I've run `composer update --lock`. I've explicitly told composer that I don't want it to update any packages so `packages` shouldn't change?

I could sort of understand updating the packages key if the version of a package I had installed in the vendor directory was incorrect, but in this instance that hasn't happened.
