### ISSUE TITLE
--ignore-platform-reqs does not handle "conflict" rules

### ISSUE THREAD

**Issue by ezzatron** [composer/composer#5562]
With the following composer.json:

``` json
{
    "conflict": {
        "php": "<99.0"
    }
}
```

When I run this command:

```
composer install --ignore-platform-reqs
```

I get this output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for __root__ No version set (parsed as 1.0.0) -> satisfiable by __root__[No version set (parsed as 1.0.0)].
    - php 7.0.6 conflicts with __root__[No version set (parsed as 1.0.0)].
    - Installation request for php 7.0.6 -> satisfiable by php[7.0.6].
```

And I expected this to happen:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

**Comment by alcohol** [comment]
A requirement does not equal a conflict.

**Comment by ezzatron** [comment]
Fair enough. Semantics aside, this is causing me real-world issues.

I have a dev dependency on [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer), who recently added a [conflict with HHVM <3.9](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/28675e57eb5db6822a8c9885cbeaf26dff4347cd/composer.json#L32), which [broke my Travis build](https://travis-ci.org/eloquent/phony/jobs/148187317#L349), even though I am using `--ignore-platform-reqs`.

The only solution I know of is to pin my dependency on PHP-CS-Fixer to a version before they added the conflict. I've done that as a work-around, but it essentially means I can never upgrade.

**Comment by alcohol** [comment]
I am not sure what we can do about this. @Seldaek would it make sense to also remove/filter any conflict rules that refer to platform requirements?

**Comment by Seldaek** [comment]
It probably makes sense to also remove conflicts yeah, if easily feasible (I haven't checked). cc @naderman for a sanity check here.

**Comment by giovannipds** [comment]
No news about this?
