### ISSUE TITLE
composer shows error message "… not having swap configured" while swap is configured (but too low)

### ISSUE THREAD

**Issue by alexislefebvre** [composer/composer#5565]
With a typical Symfony project (the packages are irrelevant here), When I run this command:

```
php ~/composer.phar update --no-progress --no-dev -vvv --profile
```

I get this output:

```
$ php ~/composer.phar update --no-progress --no-dev -vvv --profile
Reading ./composer.json
[…]
[884.6MB/35.87s]   - Removing symfony/symfony (v2.8.8)
[209.0MB/37.36s] The following exception is caused by a lack of memory and not having swap configured
[209.0MB/37.36s] Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details
```

The message `not having swap configured` is confusing, because my swap is configured, as shown by `free`.

# Proposal

I think that the message should not pretend that swap is not configured.

It could be less precise:

> The following exception is caused by a lack of memory or swap, or not having swap configured

**Comment by alcohol** [comment]
Fair enough.
