### ISSUE TITLE
The package is not available in a stable-enough version according to your minimum-stability setting

### ISSUE THREAD

**Issue by comeonhongxu** [composer/composer#5573]
```
composer install --prefer-dist
```

I get this output:

```
  Problem 1
    - Installation request for yiisoft/yii2-composer 2.0.x-dev -> satisfiable by yiisoft/yii2-composer[2.0.x-dev].
    - yiisoft/yii2-composer 2.0.x-dev requires composer-plugin-api 1.0.0 -> no matching package found.
  Problem 2
    - Installation request for yiisoft/yii2-composer dev-master -> satisfiable by yiisoft/yii2-composer[dev-master].
    - yiisoft/yii2-composer dev-master requires composer-plugin-api 1.0.0 -> no matching package found.
  Problem 3
    - yiisoft/yii2-composer dev-master requires composer-plugin-api 1.0.0 -> no matching package found.
    - yiisoft/yii2-composer 2.0.x-dev requires composer-plugin-api 1.0.0 -> no matching package found.
    - yiisoft/yii2 2.0.5 requires yiisoft/yii2-composer * -> satisfiable by yiisoft/yii2-composer[2.0.x-dev, dev-master].
    - Installation request for yiisoft/yii2 2.0.5 -> satisfiable by yiisoft/yii2[2.0.5].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by alcohol** [comment]
Please include your composer.json

**Comment by alcohol** [comment]
But it looks to me like you simply need to update your composer. Please run `composer self-update`.

**Comment by comeonhongxu** [comment]
@alcohol already executed compoer self-update
has composer.lock 
compoer.json
{
    "name": "www",
    "description": "Goumin New Application",
    "keywords": ["yii", "framework", "advanced", "application template"],
    "type": "project",
    "support": {
    },
    "minimum-stability": "dev",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "2.0.5",
        "yiisoft/yii2-bootstrap": "2.0.4",
        "yiisoft/yii2-swiftmailer": "2.0.4",
        "yiisoft/yii2-redis": "2.0.4",
        "yiisoft/yii2-sphinx": "2.0.4",
        "yiisoft/yii2-twig": "2.0.4",
        "yiisoft/yii2-jui":"2.0.4",
        "kartik-v/yii2-grid": "*",
        "mihaildev/yii2-ckeditor": "*",
        "yiisoft/yii2-mongodb":"2.0.4",
        "kartik-v/yii2-datecontrol": "dev-master",
        "phpoffice/phpexcel": "1.8.0",
        "kartik-v/yii2-widgets": "@dev",
        "kartik-v/yii2-mpdf": "*",
        "kartik-v/yii2-date-range": "*",
        "sammaye/yii2-solr":"*",
        "yiisoft/yii2-authclient": "^2.0"          
    },
    "require-dev": {
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-codeception": "*",
        "codeception/codeception": "2.0.8",
        "codeception/specify": "*",
        "symfony/yaml": "2.6.1"

    },
    "scripts": {
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject"
        ]
    },
    "config": {
        "process-timeout": 1800
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}

**Comment by alcohol** [comment]
Output of `composer --version` ?

**Comment by comeonhongxu** [comment]
@alcohol Composer version 1.2.0 2016-07-19 01:28:52

**Comment by alcohol** [comment]
Hmm I see they had a bug in their old version:

https://github.com/yiisoft/yii2-composer/commit/6b2a2b3bb83d4b3dd791f76e64c48973ce01bac6

It could be that this version with the bug is currently locked in your `composer.lock` file. Try deleting your `composer.lock` and installing from scratch.

**Comment by comeonhongxu** [comment]
@alcohol  I used to delete the composer.lock ,then installation is successful . I just don't know what's wrong with the composer.lock . now I get it.
Thank you very much!

**Comment by alcohol** [comment]
Problem solved? :-)

**Comment by comeonhongxu** [comment]
@alcohol 
yes 
delete composer.lock,then composer install 
or update composer.lock  "1.0.0" to "^1.0"   ,then install :-)))

**Comment by alcohol** [comment]
Ok, thanks :-)

**Comment by maheshjithvar** [comment]
Problem 1
    - yiisoft/yii2 2.0.3 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stabl
e -> no matching package found.
    - yiisoft/yii2 2.0.2 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stabl
e -> no matching package found.
    - yiisoft/yii2 2.0.1 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stabl
e -> no matching package found.
    - yiisoft/yii2 2.0.0 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stabl
e -> no matching package found.
    - yiisoft/yii2 2.0.11.1 requires bower-asset/jquery 2.2.*@stable | 2.1.*@sta
ble | 1.11.*@stable | 1.12.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.9 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable
 | 1.11.*@stable | 1.12.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.8 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable
 | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.7 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable
 | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.6 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stabl
e -> no matching package found.
    - yiisoft/yii2 2.0.5 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stabl
e -> no matching package found.
    - yiisoft/yii2 2.0.4 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stabl
e -> no matching package found.
    - yiisoft/yii2 2.0.12 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stabl
e | 1.11.*@stable | 1.12.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.11.2 requires bower-asset/jquery 2.2.*@stable | 2.1.*@sta
ble | 1.11.*@stable | 1.12.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.11.1 requires bower-asset/jquery 2.2.*@stable | 2.1.*@sta
ble | 1.11.*@stable | 1.12.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.11 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stabl
e | 1.11.*@stable | 1.12.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.10 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stabl
e | 1.11.*@stable | 1.12.*@stable -> no matching package found.
    - Installation request for yiisoft/yii2 * -> satisfiable by yiisoft/yii2[2.0
.0, 2.0.1, 2.0.10, 2.0.11, 2.0.11.1, 2.0.11.2, 2.0.12, 2.0.2, 2.0.3, 2.0.4, 2.0.
5, 2.0.6, 2.0.7, 2.0.8, 2.0.9].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more det
ails.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further commo
n problems.

**Comment by maheshjithvar** [comment]
can there is any solution with my errror

**Comment by aludayanan** [comment]
I encountered similar error as @maheshjithvar when trying to install Yii2 Advance Application using this command "composer create-project --prefer-dist yiisoft/yii2-app-advanced yii-application". After searching i managed to resolved and install using this command "composer create-project --prefer-dist --stability=dev  yiisoft/yii2-app-advanced yii-application".  hope this help

**Comment by BADBOYIII** [comment]
How did I fix this?

After installing Composer, run the following command to install the Composer Asset Plugin:

php composer.phar global require "fxp/composer-asset-plugin:^1.2.0"

Now choose one of the application templates to start installing Yii 2.0. An application template is a package that contains a skeleton Web application written in Yii.

**Comment by saurabhbarman** [comment]
When i Install Shopping Cart package in Git Bash This Error Show. How Can I solve This?

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - hwi/oauth-bundle 1.2.x-dev requires php-http/client-implementation ^1.0 -> no matching package found.
    - hwi/oauth-bundle 1.2.0 requires php-http/client-implementation ^1.0 -> no matching package found.
    - Installation request for hwi/oauth-bundle ^1.2 -> satisfiable by hwi/oauth-bundle[1.2.0, 1.2.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by saurabhbarman** [comment]
After Update composer. Now Show This Error?

$ composer require "darryldecode/cart:~4.0"
./composer.json has been updated
Running composer update darryldecode/cart
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - hwi/oauth-bundle[dev-master, 1.2.0] require php-http/client-implementation ^1.0 -> could not be found in any version, but the following packages provide it:
      - symfony/http-client Symfony HttpClient component
      - php-http/guzzle6-adapter Guzzle 6 HTTP Adapter
      - php-http/curl-client PSR-18 and HTTPlug Async client with cURL
      - kriswallsmith/buzz Lightweight HTTP client
      - php-http/mock-client Mock HTTP client
      - php-http/socket-client Socket client for PHP-HTTP
      - php-http/guzzle7-adapter Guzzle 7 HTTP Adapter
      - php-http/guzzle5-adapter Guzzle 5 HTTP Adapter
      - php-http/buzz-adapter Buzz HTTP Adapter
      - voku/httpful A Readable, Chainable, REST friendly, PHP HTTP Client
      - jorge-matricali/http-client A wrapper of libcurl that implements PSR-7 HTTP message interface.
      - php-http/cakephp-adapter Cake adapter for PHP-HTTP
      - code-tool/curl-client cURL client
      - eonx-com/apiformats Package for working with API requests and responses in different formats
      - windwalker/http Windwalker Http package
      - php-http/react-adapter React HTTP Adapter
      - swisnl/php-http-fixture-client Fixture client for PHP-HTTP
      - windwalker/framework A Modern PHP framework.
      - php-http/zend-adapter Zend Adapter for HTTPlug
      - juststeveking/http-slim A slim psr compliant http client to provide better interoperability
      ... and 23 more.
      Consider requiring one of these to satisfy the php-http/client-implementation requirement.
    - hwi/oauth-bundle 1.2.x-dev is an alias of hwi/oauth-bundle dev-master and thus requires it to be installed too.
    - Root composer.json requires hwi/oauth-bundle ^1.2 -> satisfiable by hwi/oauth-bundle[1.2.0, 1.2.x-dev (alias of dev-master)].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
