### ISSUE TITLE
Problem installing composer

### ISSUE THREAD

**Issue by gabrieletim** [composer/composer#5578]
sudo curl -sS http://getcomposer.org/installer | php
All settings correct for using Composer
PHP Warning:  file_put_contents(/home/gabriel/.composer/keys.dev.pub): failed to open stream: Permission denied in - on line 466
PHP Warning:  file_put_contents(/home/gabriel/.composer/keys.tags.pub): failed to open stream: Permission denied in - on line 483
Downloading 1.2.0...
PHP Warning:  openssl_verify(): supplied key param cannot be coerced into a public key in - on line 576
PHP Warning:  openssl_free_key() expects parameter 1 to be resource, boolean given in - on line 577
Signature mismatch, could not verify the phar file integrity

**Comment by alcohol** [comment]
You should not use sudo.
