### ISSUE TITLE
Composer create-project not respecting setfacl permissions

### ISSUE THREAD

**Issue by SplicePHP** [composer/composer#5579]
When I run this command:

```
composer create-project --prefer-dist cakephp/app project
```

I am running Linux Mint 18 Sarah 64bit as a development server.
I have created a virtual host inside my home directory /home/$USER/www.
I ran the following command to give groups and owners write access to files created in the www dir:

```
setfacl -d -m g::rwx "/home/$USER/www" 
```

(Note: you might need to reboot or restart terminal for settings to take effect)

Now all directories that are created inside this path should be 0775 and files should be 664.

Any files that are initialised with touch, mkdir or even created via git clone work correctly and permissions are set to 775 and 664 respectively.

When I run the composer command as stated above, composer seems to ignore these settings and creates files as 755 and 644.

I have already moved on by creating a chmod post install command to fix this issue for my installer but I thought you might want to know about the issue.

**Comment by alcohol** [comment]
Not really a Composer issue as far as I can tell.

**Comment by gisostallenberg** [comment]
I'm not sure if this is related, but after running `composer create-project` some files in bin/ are not executable, while after a `git clone` they are.
I found this running:
```bash
composer create-project sulu/sulu-minimal project -n
ls -l project/bin/
-rw-r--r-- 1 username groupname  164 Aug 24 13:30 adminconsole

git clone git@github.com:sulu/sulu-minimal.git project
composer install --working-dir=project/
ls -l project/bin/
-rwxr-xr-x 1 username groupname  164 Aug 24 13:32 adminconsole
```
In composer.json the dir is configured:
```json
    "config": {
        "bin-dir": "bin"
    }
```

**Comment by alcohol** [comment]
`create-project` is basically an alias for git clone + composer install, so at first glance I can't really say why the outcome would be any different.

**Comment by gisostallenberg** [comment]
The commands as mentioned above are the ones I executed, so I assume something in the internals of composer is doing something different.
Is this a separate issue? So would you like me to create a new one?

**Comment by alcohol** [comment]
They are definitely different issues, yes. Yours has nothing to do with `setfacl` afaik.

**Comment by gisostallenberg** [comment]
Created a new issue #5622

**Comment by Seldaek** [comment]
Auto-closing as this hasn't been updated in over 6months and is marked as a support request. If there is a real bug to consider please let us know.
