### ISSUE TITLE
RFC: New arguments --bc & --semver for outdated command

### ISSUE THREAD

**Issue by ravage84** [composer/composer#5581]
Today with Composer version 1.2.0 I tried the``outdated`` command with the ``--direct`` argument on one of my projects.

````
composer outdated --direct
````

It showed me, among others, that my ``adldap2/adldap2`` dependency ``v5.2.17`` is out of date as there is a version ``v6.1.1``  available.

This is nice to know but what I wanted to know and what I was expecting to get, was that it would show me that ``v5.2.17`` was the most current version according to my ``composer.json`` dependency definition of ``"adldap2/adldap2": "^5.2.8"``.

I chose that dependency version ``^5.2.8`` consciously and thus I currently don't care if there is a new major version available.

So when I executed the ``outdated`` command I expected that it would respect the setup of my ``composer.json``.

I guess this behavior can't be changed in the foreseeable future, so instead I propose two new arguments for the ``outdated`` command:

1. ``--bc``, showing only backward-**incompatible** versions
2. ``--semver``, showing only **semver-compatible** versions

This way, I could better filter the yellow and red colored versions, as mentioned in the docs:

> yellow: Dependency has a new version available that includes backwards compatibility breaks according to semver, so upgrade when you can but it may involve work.
red: Dependency has a new version that is semver-compatible and you should upgrade it.

https://getcomposer.org/doc/03-cli.md#outdated

As a bonus, people using Window's cmd (without colors) or people wanting to dump the output into a plain text file, would get an interpretable outcome.

Related:
https://github.com/composer/composer/issues/5240#issuecomment-213960385
https://github.com/composer/composer/issues/5253#issuecomment-215525842

**Comment by fvdb** [comment]
This might be of help: #5552

**Comment by stof** [comment]
``--bc`` would be a weird name for showing backward incompatible versions, as the abbreviation means "backward compatible" (or "backward compatibility")

**Comment by ravage84** [comment]
@stof True, may be ``--bic``. It was just one suggestion. I am open to any other better choice.

**Comment by Seldaek** [comment]
Closing as #5552 kinda does this IMO.
