### ISSUE TITLE
composer update and composer require fail on macOS

### ISSUE THREAD

**Issue by micheal** [composer/composer#5597]
When I run this command `composer update` or `composer require`, it fails with the following error message:

```
[ErrorException]
file_put_contents(/Users/<username>/Projects/Tools/<project>/vendor/bin/doctrine-dbal): failed to open stream: No such file or directory
```

But that file exists ... or not:

```
# [redacted] in ~/Projects/Tools/<project>/vendor/bin [12:01:41]
$ file doctrine-dbal
doctrine-dbal: broken symbolic link to /private/var/folders/sg/hgd7y7[brevity]00000gn/T/1469[brevity]7608e6/Symfony/vendor/doctrine/dbal/bin/doctrine-dbal
```

Actually, it does exist ... or maybe it doesn't:

```
# [redacted] in /private/var/folders/sg/hgd7y7[brevity]00000gn/T/1469[brevity]7608e6/Symfony/vendor/doctrine/dbal/bin [12:28:02]
$ file doctrine-dbal
doctrine-dbal: broken symbolic link to ../doctrine/dbal/bin/doctrine-dbal
```

Attempting to follow that symlink does indeed break.

Why is it symlinked like this? Things work for a little while, then suddenly break. Then I have to remove my `vendors/`, and do `composer update`. I use my Mac for development only, so it's not breaking anything, but it is really annoying.

**Comment by alcohol** [comment]
You redacted too much from the paths. In their current state, your issue makes no sense.

`/Users/[redacted]/vendor/bin/doctrine-dbal` could never match `~/Projects/Tools/[redacted]/vendor/bin` unless you redacted multiple subdirectories. But I cannot know if this the case or not. Hence your information is useless to me, so I cannot assist you until you remedy this.

**Comment by micheal** [comment]
Fixed.

**Comment by alcohol** [comment]
It looks quite weird to me. I am not really sure why it would even try to use your system tmp directories. AFAIK it does not need to do that at all for generating the bin symlinks. There is something very wrong with your environment. Can you try removing your vendor directory entirely and just running a clean install process?

**Comment by micheal** [comment]
Yeah, I'm at a loss to explain this. I've not done anything special to my environment as far as I'm aware. That is, I run IntelliJ IDEA, I have composer and PHP, and I've not implemented any special configurations. Here's another project that has the same problem. I delete `vendor/` and it works for a little bit. Then after a few times running `composer update`, it breaks again.

~~~
# [user] in ~/Projects/Websites/<project>/symfony/vendor/bin [18:34:40] 
$ ls -al
total 32
drwxr-xr-x   6 [user]  staff  204 Aug 16 18:16 .
drwxr-xr-x  26 [user]  staff  884 Aug 16 18:32 ..
lrwxr-xr-x   1 [user]  staff   28 Aug 16 18:16 doctrine -> ../doctrine/orm/bin/doctrine
lrwxr-xr-x   1 [user]  staff   34 Aug 16 18:16 doctrine-dbal -> ../doctrine/dbal/bin/doctrine-dbal
lrwxr-xr-x   1 [user]  staff   32 Aug 16 18:16 doctrine.php -> ../doctrine/orm/bin/doctrine.php
lrwxr-xr-x   1 [user]  staff   47 Aug 16 18:16 security-checker -> ../sensiolabs/security-checker/security-checker
~~~

It works for now. I'll try to keep a closer eye on just when it breaks. Maybe there's something that can't get moved properly during composer update? I don't know.

**Comment by alcohol** [comment]
All those symlinks look correct though. Although the path `<project-root>/symfony/vendor/bin` is not Composer default. How did you end up with that?

**Comment by micheal** [comment]
Yes, they are correct for now. They end up breaking later.

Symfony is actually installed in `symfony/`. I had non-Symfony files in `<project>`, and just haven't moved things in to the `<project>` folder.

**Comment by alcohol** [comment]
Alright. Then it's all good. Keep me in the loop if the situation changes again.

**Comment by Seldaek** [comment]
Auto-closing as this hasn't been updated in over 6months and is marked as a support request. If there is a real bug to consider please let us know.
