### ISSUE TITLE
Vendor folder should be called lib by default

### ISSUE THREAD

**Issue by jessegreathouse** [composer/composer#5599]
The folder "vendor/" is a thing that's unique to composer and doesn't follow any sort of pattern in the file system. Calling the folder "lib/" would be more semantically correct and also, on unix systems, would conform to the standard unix directory tree. For legacy reasons people could still change their lib folder to be called vendor, but I think that new projects, using composer, should have packages added to "lib/" by default.

**Comment by alcohol** [comment]
You are free to change the directory yourself; but we are not changing a convention we have followed for several years already.

https://getcomposer.org/doc/06-config.md#vendor-dir
https://getcomposer.org/doc/03-cli.md#composer-vendor-dir
