### ISSUE TITLE
Install command does nothing?

### ISSUE THREAD

**Issue by letharion** [composer/composer#560]
Probably a really silly question, but when I try to follow Fabian's "Create your own framework" (http://fabien.potencier.org/article/50/create-your-own-framework-on-top-of-the-symfony2-components-part-1) intro to symfony, I get stuck on the very first composer part. php composer.phar install just returns right away.

No output at all, and as far as I can tell, nothing happens. I have copy-pasted the sample composer.json file to the current dir. Is there some type of debug flag I can run with?

$ cat composer.json 
{
    "require": {
        "symfony/class-loader": "2.1.*"
    }
}
$ wget http://getcomposer.org/composer.phar
$ php composer.phar install
$ php composer.phar install --dry-run
$ ls -l
-rw-r--r-- 1 letharion letharion      67 10 apr 07.58 composer.json
-rw-r--r-- 1 letharion letharion 2358739 10 apr  2012 composer.phar

**Comment by physicalattraction** [comment]
How do you check your disabled functions?
