### ISSUE TITLE
"Checking platform settings: FAIL" in Windows

### ISSUE THREAD

**Issue by Chealer** [composer/composer#5601]
composer install would fail the first time I tried it. The Troubleshooting page would recommend using composer diagnose, which failed on my Windows 10 install:

> C:\Users\Philippe Cloutier\subversion\web>composer diagnose
> You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
> Checking platform settings: FAIL
> The xdebug extension is loaded, this can slow down Composer a little.
>  Disabling it when using Composer is recommended.
> 
> Checking git settings: OK
> Checking http connectivity to packagist: Warning: Accessing packagist.org over http which is an insecure protocol.
> OK
> Checking https connectivity to packagist: OK
> Checking github.com rate limit: OK
> Checking disk free space: OK
> Checking pubkeys:
> Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
> Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
> OK
> Checking composer version: OK
> 
> C:\Users\Philippe Cloutier\subversion\web>

It turned out that composer was in fact working. It was my composer.json which was incorrect.

This is a fresh install with no customization.
composer diagnose -vvv outputs:

> Failed to initialize global composer: Composer could not find the config file: C:/Users/Philippe Cloutier/AppData/Roaming/Composer/composer.json
> To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
> Running 1.2.0 (2016-07-19 01:28:52) with PHP 5.5.12 on Windows NT / 6.2
> You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
> Checked CA file C:\Users\Philippe Cloutier\AppData\Local\Temp\composer-cacert-bcf331364fef73d53e4368ba519a6c3fcb21ea7836c3d8efad4ec32731e8152a.pem: valid
> Checking platform settings: FAIL
> The xdebug extension is loaded, this can slow down Composer a little.
>  Disabling it when using Composer is recommended.
> 
> Checking git settings: Executing command (CWD): git config color.ui
> OK
> Checking http connectivity to packagist: Downloading http://packagist.org/packages.json
> Warning: Accessing packagist.org over http which is an insecure protocol.
> OK
> Checking https connectivity to packagist: Downloading https://packagist.org/packages.json
> OK
> Checking github.com rate limit: Downloading https://api.github.com/rate_limit
> OK
> Checking disk free space: OK
> Checking pubkeys:
> Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
> Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
> OK
> Checking composer version: Downloading https://getcomposer.org/versions
> OK

This was previously reported in ticket #4576.

**Comment by Chealer** [comment]
The other reporter also had Xdebug enabled.

I verified that after disabling Xdebug, the platform settings check succeeds.

**Comment by alcohol** [comment]
So.. no issue then.

**Comment by Chealer** [comment]
I have no issue anymore... after spending several minutes trying to debug the wrong bug.
Why did you close this ticket, alcohol?

**Comment by alcohol** [comment]
Because there is nothing left to do here?

**Comment by Chealer** [comment]
And what has been done?

**Comment by alcohol** [comment]
I cannot tell if you are being serious or just trolling. There is no issue here, just a simple misunderstanding. So what do you expect to "be done"?

**Comment by Chealer** [comment]
Unless something has been done solving this, please reopen.

I expect to be done whatever remains to be done so that composer diagnose; keeps succeeding when Xdebug is enabled (in general, the diagnosis should succeed, at least if composer is functional).

**Comment by alcohol** [comment]
It does succeed.

**Comment by Chealer** [comment]
It does not. The failure is shown in this ticket's title.

**Comment by alcohol** [comment]
But xdebug being enabled is supposed to lead to a warning (fail). So I repeat, what is the problem?

**Comment by Chealer** [comment]
A warning is not a failure. The problem is that composer diagnose; fails while Composer is functional. The explanation for that problem may be that composer diagnose; confuses warnings and failures.

**Comment by alcohol** [comment]
Functional, yes, but crippled. People run `diagnose` to determine various issues, e.g. connectivity, slowness, etc. Xdebug has **severe** performance impacts. So it rightfully fails. 

I think you might be confusing the behaviour of`validate` and `diagnose`. They serve different purposes.

**Comment by Chealer** [comment]
Nothing here disputes that PHP extensions have performance impacts. However, the presence of an extension with an impact on performance, no matter its importance, does not make diagnosis failures less wrong.

composer validate; is project-specific.

**Comment by alcohol** [comment]
Well we can agree to disagree. I'm unsubscribing.

**Comment by Seldaek** [comment]
Fixed in https://github.com/composer/composer/commit/b29d810d63f6c2a6a6be0bfd063ae8b722c2629d

**Comment by Chealer** [comment]
alcohol, announcing that you unsubscribe does not reopen the ticket. When you agree to disagree with a request, you leave the ticket alone or mention your disagreement; you do not close it without explanation.

**Comment by Chealer** [comment]
Many thanks Seldaek. By the looks of the diff, the commit seems to solve completely.
