### ISSUE TITLE
Composer run removes color from output

### ISSUE THREAD

**Issue by lukasoppermann** [composer/composer#5606]
Hey,

I did not find any issue or anything about this:

When I run something using composer script e.g.

```
    "scripts": {
        "humbug": "vendor/bin/humbug && vendor/bin/humbug stats --skip-killed=yes -vvv"
    },
```

it does not output in color, even though running the scripts directly from the cli does output color. With the example above it makes it really hard to spot where the mutation happened.

**Comment by alcohol** [comment]
That is because the output is not detected as being ANSI compatible (because it is a subprocess). You can force it by passing the proper argument to humbug.

**Comment by lukasoppermann** [comment]
@alcohol I take it you are talking about the `--ansi` flag? Sadly adding it does not show any effect.  What could I be doing wrong?

**Comment by alcohol** [comment]
That is peculiar. I can get it to add colors just fine. Not sure what you could be doing wrong. Can you show verbose output of composer (`-vvv`) when trying to run it with the `--ansi` flag?

**Comment by lukasoppermann** [comment]
My bad, I added it to `vendor/bin/humbug stats` but not to the `vendor/bin/humbug` before `&&`. 
So its all fixed and works fine, thanks.

**Comment by staabm** [comment]
here is a article which describes what needs to be done:

https://tomasvotruba.com/blog/2020/09/28/how-to-add-colors-to-continuious-integration-output/
