### ISSUE TITLE
Composer emits "No driver found to handle VCS repository" erroneously in at least two cases

### ISSUE THREAD

**Issue by cbj4074** [composer/composer#5610]
```
$ composer --version
Composer version 1.2.0 2016-07-19 01:28:52
```

# Case 1 #

I notice that if I lack access to repository that is defined in `"repositories": [...]` (though not referenced anywhere else in `composer.json`, which may be irrelevant), `composer install/update` yields:

```
[InvalidArgumentException]
No driver found to handle VCS repository repos.example.com:vendor/package
```

Increasing the verbosity with `-vvv` doesn't offer much more in the way of a useful message:

```
Importing branch master (dev-master)
Executing command (CWD): git ls-remote --heads 'repos.example.com:vendor/package'
Executing command (CWD): p4 -p repos.example.com:vendor/package info -s


  [InvalidArgumentException]
  No driver found to handle VCS repository repos.example.com:vendor/package
```

The real reason is revealed by executing the same command manually:

```
$ git ls-remote --heads 'repos.example.com:vendor/package'
FATAL: R any vendor/package my-ssh-user DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Is it possible to improve Composer's error-handling such that it echoes exactly the message `git ls-remote` returns? That would be a lot more helpful in this particular scenario than `No driver found to handle VCS repository`, which is not really relevant to the situation at hand. This isn't a driver issue. I simply lack access to the repository.

# Case 2 #

In this scenario, the remote host's SSH fingerprint has changed, so the value in `~/.ssh/known_hosts` no longer matches. But Composer doesn't tell us about this. Instead, it complains with our old friend:

```
[InvalidArgumentException]
No driver found to handle VCS repository repos.example.com:vendor/package
```

The *true* reason for the failure is, as in Case 1, revealed by executing the underlying commands manually:

```
git ls-remote --heads 'repos.example.com:vendor/package'
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@       WARNING: POSSIBLE DNS SPOOFING DETECTED!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
The ECDSA host key for repos.example.com has changed,
...
```

Again, it would be far more useful if Composer simply echoed the output from `git ls-remote`, rather than intervene with an inaccurate and unhelpful message.

Thanks for any consideration given to this issue!

**Comment by alcohol** [comment]
In these scenarios, Composer simply tries out every available driver until it finds one that can handle the repository. Since you have no access, all drivers fail. We cannot return the error at the first failure, because the whole idea is to iterate through all drivers until we find a working one.

In this case, the issue is simply a configuration error on the user side. These are things we cannot prevent. There is also no reason to improve the error reporting here as the situation described doesn't call for it.

**Comment by abdonor** [comment]
This can have a lot of different possibilities, but it also happen when your repository is linked with ssh private/public keys, and your private key is unprotected. The solution is to set it to 600, example below:

    sudo chmod 600 ~/.ssh/id_rsa
