### ISSUE TITLE
composer.json repositories have priority over config.json

### ISSUE THREAD

**Issue by AndreKR** [composer/composer#5614]
I am using `path` repositories in my `config.json` to junction local copies of packages into my vendor directories.

**config.json**
```
{
	"repositories": [
		{
			"type": "path",
			"url": "d:\\path\to\local\copy"
		},
		{
			"type": "composer",
			"url": "https://example.com/private_repository"
		}
	]
}
```

This works fine because the local copy takes precedence over the `composer` repository, I think because it comes first in my config.

However, when the application itself specifies the `composer` repository in its `composer.json`:
**composer.json**
```
	"repositories": [
		{
			"type": "composer",
			"url": "https://example.com/private_repository"
		}
	]
```
it no loner works because apparently the `composer.json` repositories have priority over the ones from `config.json`.

Shouldn't `config.json` *always* have priority?

**Comment by alcohol** [comment]
No, local (composer.json) has priority.

**Comment by AndreKR** [comment]
Is there any reasoning why it's implemented like this? Seems like a bug to me.

**Comment by Seldaek** [comment]
Because the system config can provide stuff but the local project config always wins over system config.. It works for most purposes, but obviously we can't please everybody in every possible situation.

**Comment by alcohol** [comment]
This is how generally configuration works (at least on Linux/OSX). Local takes precedence over User, User takes precedence over System.

**Comment by AndreKR** [comment]
That does make sense. Unfortunately Local (composer.json) is actually managed remotely (by the VCS) here, so maybe Composer should check for another `composer.local.json` or something that takes precedence? That's a lot of configs, though.

**Comment by alcohol** [comment]
I do not quite understand how it is managed remotely? You push the changes to the remote VCS yourself. So you are in control.

**Comment by AndreKR** [comment]
You're supposed to put composer.json in VCS, aren't you? So you can't just make local modification, they'll be reverted on the next checkout or might be accidentally committed.

**Comment by alcohol** [comment]
Well, yes, when you put it like that.
