### ISSUE TITLE
Make versioning scheme used by libraries explicit in composer.json

### ISSUE THREAD

**Issue by meadsteve** [composer/composer#5621]
Not all (sadly) libraries follow semver. Would it be sensible to add something like this to the composer.json:

```javascript
{
    "name": "example/lib",
    "description": "helps demonstrate things",
    "versioning": "semver"
   //...
}
```

This would unlock the ability to have composer warn when breaking updates are occurring.

**Comment by daylerees** [comment]
It's easy to identify semver here, but I wonder if it might be more difficult to identify (and agree on) a naming convention for the versioning principles of packages that don't implement semantic versioning?

**Comment by meadsteve** [comment]
@daylerees I agree with that. One way to sidestep that issue is to make it optional. Semver has a clear definition so they'd be the libraries with a value here. Others could be added as definitions are found.

**Comment by alcohol** [comment]
Does not really contribute anything meaningful, other than work and maintenance.

**Comment by meadsteve** [comment]
@alcohol I disagree. This enables warnings to be thrown in the future if someone makes a requirement like `^1.0` on a package that doesn't follow semver.

**Comment by alcohol** [comment]
That statement does not make much sense. You are saying that everyone that is currently already following semver, has to explicitly add this to their composer.json now, otherwise Composer will throw warnings to their users? Sounds like a god-awful idea. We cannot ask that of the community.

**Comment by alcohol** [comment]
Also, it's just purely cosmetics. There is still absolutely no guarantee that the project actually follows semver. As a user, you should always be conscious about what you require and install. There is no substitute for this, definitely not some simple attribute in a json schema.

**Comment by meadsteve** [comment]
@alcohol the same argument applies to the `license` field though. This was my inspiration.

**Comment by Seldaek** [comment]
I also don't really see huge value here, most popular projects already follow semver (to more or less strict levels) and the few that don't usually advertise it.

**Comment by meadsteve** [comment]
@alcohol @Seldaek fair enough 👍  Thanks for your responses. I was just nearly caught out by breaking changes in laravel 5.3 (I hadn't realised they didn't follow semver) and was trying to come up with ways to mitigate the risk.

I'll close this issue for now.

**Comment by Seldaek** [comment]
Yeah Laravel is one of the big "offenders" here.. I am not sure why Taylor insists on not following it, but you can try complaining over there, maybe eventually he will give in ;)
