### ISSUE TITLE
post-update-cmd event returned with error code 255

### ISSUE THREAD

**Issue by Powerin10** [composer/composer#5623]
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Script php artisan optimize handling the post-update-cmd event returned with error code 255

how can i fix it ?

**Comment by rohittheindiajobs** [comment]
I have same issue , would you please suggest how to fix it?

**Comment by oLDu67** [comment]
+1

**Comment by oLDu67** [comment]
https://laracasts.com/discuss/channels/general-discussion/cannot-run-php-artisan?page=1

**Comment by dontito94** [comment]
i had the same problem please any one to help us

**Comment by curry684** [comment]
Please stop polluting this closed issue. There is no Composer issue, it's just executing a command by your request that fails.

**Comment by dontito94** [comment]
Hey what are you talking about?

**Comment by spencershaw** [comment]
I have same problem. Please help

**Comment by curry684** [comment]
Again: this is Laravel specific functionality which is just being invoked *by* Composer *on behalf of* Laravel. Composer nor its developers cannot fix anything here or help you.

**Comment by mancini85** [comment]
[Symfony\Component\Debug\Exception\FatalThrowableError]                   
  Parse error: syntax error, unexpected '\' (T_SL), expecting end of file  
                                                                            

Script php artisan optimize handling the post-install-cmd event returned with error code 1

**Comment by shahzad-nawaz** [comment]
i am facing same issue ...

Mcrypt PHP extension required.
Script php artisan clear-compiled handling the post-update-cmd event returned with an error

                      
  [RuntimeException]  
  Error Output:

**Comment by nguyenttngan** [comment]
I had the same problem when I downgrade 4.3 from 5.5. Anybody get the solution yet? Thanks.

Mcrypt PHP extension required.
Script php artisan clear-compiled handling the post-update-cmd event returned with error code 1

**Comment by ComputerGuruInTraining** [comment]
The problem lies with dependencies, at least it did in my case. It took a few steps to fix it.
First, I experienced the problem on the server so I ran composer update and php artisan serve on localhost no problem, then remerged with server and a more explicit error msg was provided saying required php ^7.0 for doctrine/inflector package ^1.2.0.
So secondly, updated the php on server via server settings.
Then, a different error msg: 
[Symfony\Component\Debug\Exception\FatalThrowableError] Call to undefined method Illuminate\Foundation\Bootstrap\ConfigureLogging::configureHandler()
So thirdly, used the fix provided at:
https://github.com/laravel/framework/issues/6310
and changed current log code in config/app to 'log' => 'daily',
merge succeeded and all works fine :)

**Comment by YogeshSonar** [comment]
[Symfony\Component\Debug\Exception\FatalErrorException]  
 Class 'Illuminate\Foundation\Providers\View' not found   
Script PHP artisan optimize handling the post-update-cmd event returned with error code 255

what can I do?

**Comment by ComputerGuruInTraining** [comment]
If this occurred on web server, try composer update on localhost before merging with web server. I just experienced same problem again, and this fixed it.

**Comment by mansouryaacoubi** [comment]
@YogeshSonar got the same error. but it seems like no one has an answer to this.

**Comment by bolajipemipo** [comment]
Laravel Users:
[php artisan optimize has been removed in L5.6](https://laravel-news.com/laravel-5-6-removes-artisan-optimize)

**Comment by YogeshSonar** [comment]
Reinstall the composer then apply all steps repeat

**Comment by arm092** [comment]
If this happened after Laravel update from 6.x to 7.x, then this could be due to the update of Symfony. See the upgrade guide of this part: https://laravel.com/docs/7.x/upgrade#symfony-5-related-upgrades

**Comment by gehusandeep** [comment]
Script php artisan optimize handling the post-update-cmd event returned with error code 255

**Comment by IbtissamNoukta** [comment]
just remove from your composer.json the 'post-install-cmd' and 'post-update-cmd'.
All working fine for me now :)
