### ISSUE TITLE
Question: how to get unordered/untouched list of dependencies?

### ISSUE THREAD

**Issue by hiqsol** [composer/composer#5625]
Package::getRequires() and getDevRequires()  return list of dependencies ordered alphabetically.
Is there a way to get this list unchanged as it is listed in `composer.json`.

I know that this order is unimportant for composer but I need this information for my plugin.

If this is impossible what is the proper way to get the original `composer.json` contents?

I've tried to read the package's `composer.json` - it is not always: `$vendorDir/$packagePrettyName/composer.json` (eg. symfony/dom-crawler)
Is there a proper way to find the path?

**Comment by stof** [comment]
These methods are returning things in the order in which they were loaded. They are not applying any sorting.

The sorting is applied by Packagist when dumping the metadata to ensure that the order is stable between rendering (it cannot dump them in the original order, because it does not keep this info).

Why does your plugin needs this info (which does not exist as far as composer is concerned) ?

**Comment by alcohol** [comment]
> Package::getRequires() and getDevRequires() return list of dependencies ordered alphabetically.

Please link to the code where you presume said content is explicitly ordered. Lies never helped anyone, least of all when you lie to yourself :-)

**Comment by stof** [comment]
@alcohol I assume he just looked at what he received. But when getting package metadata for installed packages in a plugin, these metadata are loaded from Packagist, which means they are indeed sorted alphabetically.

**Comment by hiqsol** [comment]
@alcohol 
Here it is:
[Plugin.php:426](https://github.com/hiqdev/composer-config-plugin/blob/master/src/Plugin.php#L426)

The plugin is triggered onPostAutoloadDump.

I believe that Package::getRequires() itself doesn't touch the list of requirements but what I see - the order is changed.
My question is how to find out untouched list of dependencies.

@stof 
What I want to achieve in the plugin is to enable creating easy plugable extensions through assembling pieces of config spread across those extensions (packages).
So I merge configs (arrays) and the order is crucial.

**Comment by stof** [comment]
@hiqsol composer explicitly says that the order is irrelevant (and many people encourage using alphabetical order to have consistent standards, and ``composer require`` has an option for that as well).
And for your use case, it won't even solve the ordering for you, as installed packages are not all listed as root requirements. You will need to find a different way of controlling the loading order.

**Comment by hiqsol** [comment]
@stof  I'm iterating through dependencies too.
Actually now (with manual reading `composer.json` files) the plugin works as needed.

What I wanted to know is there a better way to get original `composer.json` files than fetch them manually ?

**Comment by stof** [comment]
As I said, Packagist does not store the original JSON, but the metadata contained in it. And when dumping these metadata again, the order of requirements is not preserved.
Composer will never read the original composer.json file (it does not even need to exist in the downloaded archive) as it reads the metadata from the repository.

**Comment by hiqsol** [comment]
Ok, thanks for quick answers!
