### ISSUE TITLE
Composer installer fail with PHP 7.0.8 (7.0.8-0ubuntu0.16.04.2 / ID: 70008)

### ISSUE THREAD

**Issue by felipebastosweb** [composer/composer#5627]
I wanted install silex framework (first fail), but trying reinstall composer found this
When I run this command:

```
php installer
sudo php installer
//composer installer downloaded directily because of same problem
```

I get this output:

```
All settings correct for using Composer
PHP Warning:  file_get_contents(https://getcomposer.org/versions): failed to open stream: Connection timed out in /home/felipe/installer on line 762
PHP Warning:  Invalid argument supplied for foreach() in /home/felipe/installer on line 508
None of the 0 stable version(s) of Composer matches your PHP version (7.0.8-0ubuntu0.16.04.2 / ID: 70008)
```
Days Before .. Composer was running, taken all components in packagist or cache.

**Comment by stof** [comment]
This is a network error:

```
PHP Warning:  file_get_contents(https://getcomposer.org/versions): failed to open stream: Connection timed out
```

**Comment by felipebastosweb** [comment]
only composer failure. All I try to access using the Composer timeout occurs. In the browser functions normally, access everything.

firewall is disabled

Only today started is fail, only with composer

Is possible incompatibility with PHP 7.0.8?

None of the 0 stable version(s) of Composer matches your PHP version (7.0.8-0ubuntu0.16.04.2 / ID: 70008)

curl https://getcomposer.org/versions Working!!!!

{
    "stable": [{"path": "/download/1.2.0/composer.phar", "version": "1.2.0", "min-php": 50300}],
    "preview": [{"path": "/download/1.2.0/composer.phar", "version": "1.2.0", "min-php": 50300}],
    "snapshot": [{"path": "/composer.phar", "version": "0aec42521b7210f66fefaf53a02ff9e4def0bdc0", "min-php": 50300}]
}

**Comment by felipebastosweb** [comment]
PHP 7.0.8 file_get_contents() is doing timeout connection.

I'll check.

thanks!
