### ISSUE TITLE
Laravel: error on "composer update" command

### ISSUE THREAD

**Issue by GiacomoK** [composer/composer#5629]
Hi,
I am not able to do a "composer update" command on Laravel 5, cause I get this error:

```
Updating guzzlehttp/promises (1.1.0 => 1.2.0)
Update failed (Failed to execute git diff --name-status composer/master...master --

error: bad index file sha1 signature
fatal: index file corrupt
)
```

I guess it does not depends on package, cause I already got the same error message on another package before this error.

Anyone knows why its happening?

Thanks

**Comment by davejamesmiller** [comment]
Sounds like the `vendor/guzzlehttp/promises/.git/index` file is corrupt. I would just delete and re-install all the packages:

```bash
rm -rf vendor
composer update
```

(If it's happening on multiple packages, corrupted files could be a symptom of another problem - I've had that happen on a hard drive that was failing, for example.)

**Comment by curry684** [comment]
@davejamesmiller `composer update` is overkill - `composer install` will also work fine from the lock and be 100 times faster.

**Comment by davejamesmiller** [comment]
@curry684 I only said `composer update` because that's the command that `GiacomoK` was attempting to run in the first place. Though it would be possible to do first an install then an update I suppose.

**Comment by GiacomoK** [comment]
Thanks both for your reply, I find out what was the problem.
Indeed the index file of some packages was corrupted, so I deleted the ".git" folder of all packages and "composer update" worked fine.

P.S. I tried (before this solution) to remove the "vendor" folder, but I got an error cause in the "vendor" folder there is "autoload.php" that needs to "composer update" command.
