### ISSUE TITLE
Composer init not accepting my name (similar to issue #3948)

### ISSUE THREAD

**Issue by emeraldinspirations** [composer/composer#5631]
Attempting to run composer.phar init produces the following error:

```
Author [Matthew "Juniper" Barlett <emeraldinspirations@gmail.com>, n to skip]: 
 Invalid author string.  Must be in the format: John Smith <john@example.com> 
Author [Matthew "Juniper" Barlett <emeraldinspirations@gmail.com>, n to skip]: Matthew (Juniper) Barlett <emeraldinspirations@gmail.com>
 Invalid author string.  Must be in the format: John Smith <john@example.com> 
Author [Matthew "Juniper" Barlett <emeraldinspirations@gmail.com>, n to skip]: 
```
[screenshot from 2016-08-28 04-13-03](https://cloud.githubusercontent.com/assets/20853049/18032768/3c16f514-6cd6-11e6-99ad-f63e79cab4a5.png)

**Comment by curry684** [comment]
The regexp is at https://github.com/composer/composer/blob/master/src/Composer/Command/InitCommand.php#L323 if you want an easy PR :wink:

**Comment by emeraldinspirations** [comment]
I am sorry, @curry684, I am new to gitHub.  What do you mean by PR?

**Comment by curry684** [comment]
https://www.thinkful.com/learn/github-pull-request-tutorial/ :smile:

**Comment by emeraldinspirations** [comment]
Status: Running into a circular dependency issue.
- To run the unit tests, composer is required
- Must fix the bug in order to install composer into the repo
- Can't verify the bug is fixed without the unit tests

Also, while I can simply adjust the filter, I have not yet finished tracing the code in order to verify that the quote character won't cause additional issues down the line.
