### ISSUE TITLE
Issue with separating binary arguments from composer arguments in exec.

### ISSUE THREAD

**Issue by SamMousa** [composer/composer#5632]
With the following composer.json:

```json
{
    "name": "sam/bug",
    "require": {
        "phpunit/phpunit": "^5.5"
    },
    "authors": [
        {
            "name": "Sam Mousa",
            "email": "sam@mousa.nl"
        }
    ]
}

```

When I run this command:

```
composer exec -vvv  -- phpunit -d

```

I get this output:

```
                                                         
  [RuntimeException]                                     
  Invalid working directory specified,  does not exist.  
                                                         

Exception trace:
 () at phar:///home/sam/bin/composer/src/Composer/Console/Application.php:256
 Composer\Console\Application->getNewWorkingDir() at phar:///home/sam/bin/composer/src/Composer/Console/Application.php:114
 Composer\Console\Application->doRun() at phar:///home/sam/bin/composer/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///home/sam/bin/composer/src/Composer/Console/Application.php:102
 Composer\Console\Application->run() at phar:///home/sam/bin/composer/bin/composer:43
 require() at /home/sam/bin/composer:24

```

And I expected this to happen:
````
PHPUnit 5.5.4 by Sebastian Bergmann and contributors.

option requires an argument -- d
````

According to `composer exec --help`, I should be able to separate binary args from composer args:
````
Usage:
  exec [options] [--] [<binary>] [<args>]...

Arguments:
  binary                         The binary to run, e.g. phpunit
  args                           Arguments to pass to the binary. Use -- to separate from composer arguments

Options:
  -l, --list                     
  -h, --help                     Display this help message
  -q, --quiet                    Do not output any message
  -V, --version                  Display this application version
      --ansi                     Force ANSI output
      --no-ansi                  Disable ANSI output
  -n, --no-interaction           Do not ask any interactive question
      --profile                  Display timing and memory usage information
      --no-plugins               Whether to disable plugins.
  -d, --working-dir=WORKING-DIR  If specified, use the given directory as working directory.
  -v|vv|vvv, --verbose           Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
 Execute a vendored binary/script
````

It seems that `--` is not properly interpreted. (One workaround is to use quotes: `composer exec -vvv -- "phpunit -d"`).

Either the implementation or the documentation is wrong.

**Comment by Seldaek** [comment]
This is a known issue and fixed in https://github.com/symfony/symfony/pull/11431 but sadly that is only in symfony3 so we will only get it once we bump dependencies to php5.5 :/

**Comment by gauthierm** [comment]
Is there an ETA for when this fix will be released? If it's going to be a while before the PHP dep is bumped then the CLI help should be updated to remove the "Use -- to separate from composer arguments" part.

**Comment by Seldaek** [comment]
The help text is still relevant, it just doesn't work 100% like with --help and such, but without `--` you will get more issues so no we are not removing it.

**Comment by gauthierm** [comment]
FWIW this issue prevents me from using composer to run phpunit commands.

**Comment by gauthierm** [comment]
This also makes it difficult to run phpcs:

```
composer exec -- phpcs -h
```

This returns help for composer and not phpcs. There's no way to use exec to get phpcs help.

**Comment by jcrben** [comment]
> (One workaround is to use quotes: composer exec -vvv -- "phpunit -d").

That workaround doesn't work for me, running composer 1.2.2 and phpunit 4.80 (old, I know...). When I updated to composer 1.4.2 composer exec broke and returned `Script phpunit handling the __exec_command event returned with error code 2` for `composer exec phpunit`.

Is there another issue that we can watch for a fix for this? Perhaps an issue tracking an upgrade to symfony3.

**Comment by yeldiRium** [comment]
Why is this issue closed?
In composer 1.7.1 it is still a problem and makes using executables like `phpcs` impossible without specifying the binary path explicitly.
