### ISSUE TITLE
composer.json is different from repo

### ISSUE THREAD

**Issue by BardiaAfshin** [composer/composer#5635]
In my repo, the composer.json is showing up as follows

```json
{
  "name": "bardia-module/product-attribute",
  "description": "N/A",
  "type": "magento2-module",
  "autoload": {
    "files": [
      "registration.php"
    ],
    "psr-4": {
      "BardiaModule\\ProductAttribute\\": ""
    }
  },
  "minimum-stability": "dev"
}
```

but when I do composer require bardiamodule/product-attribute

the project /vendor/bardiamodule directory , the psr-4 namespace definition is different, the string 'BardiaModule' is changed to 'Magento', I tried composer clear-cache thinking it was a caching issue

```json
{
  "name": "bardiamodule/product-attribute",
  "description": "N/A",
  "type": "magento2-module",
  "autoload": {
    "files": [
      "registration.php"
    ],
    "psr-4": {
      "Magento\\ProductAttribute\\": ""
    }
  },
  "minimum-stability": "dev"
}
```

**Comment by stof** [comment]
this is not the same package name either (see ``bardia-module`` vs ``bardiamodule``), so it looks like you installed a different package
