### ISSUE TITLE
Composer show - versions do not match packagist!

### ISSUE THREAD

**Issue by RyanThompson** [composer/composer#5643]
Using `composer show -a anomaly/addon-field_type`

I get: 

```
The requested package anomaly/addon-field_type v2.1.0 exists as anomaly/addon-field_type[dev-develop, dev-master, v1.0.0, v1.0.1, v1.0.2, v1.1.0, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.18, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9] but these are rejected by your constraint.
```

Yet packagist shows a 2.1.x branch and even a v2.1.0 tag!? 

https://packagist.org/packages/anomaly/addon-field_type

This is happening for all of my addons..

**Comment by xini** [comment]
same issue with my modules. new tag is not found.

**Comment by xini** [comment]
Just tested composer 1.1.3 and 1.2.0. same issue in both.

**Comment by no7mks** [comment]
same problem with my component, I have filed an issue which might be caused by similar problem:
https://github.com/composer/composer/issues/5644

**Comment by oscarotero** [comment]
Same problem here. I'm unable to update to [oscarotero/folk:^1.14](https://packagist.org/packages/oscarotero/folk) since yesterday.

**Comment by Hesto** [comment]
Same. So annoying.

**Comment by oscarotero** [comment]
Seems a problem with packagist. There's the issue: https://github.com/composer/packagist/issues/720

**Comment by courtney-miles** [comment]
I can confirm that this looks to be an issue with Packagist and not Composer.  The details for my package are up to date on the Packagist site, but the Packagist API is returning outdated information.

**Comment by dhm80** [comment]
Same here. Updates on website but not via API. Please fix ASAP. Composer is not usable at the moment.

**Comment by Seldaek** [comment]
See https://twitter.com/packagist/status/772034610632990720 for updates

**Comment by RyanThompson** [comment]
Thanks @seldaek !
