### ISSUE TITLE
Require different versions of branch

### ISSUE THREAD

**Issue by Henk8** [composer/composer#5650]
With the following composer.json:

```json
{
"require":{
	 "framework": "dev-master"
	},
	"require-dev":{
		 "framework": "dev-RC"
    },
}
```

When I run this command:
composer.phar update --no-dev

composer command -vvv (please include -vvv!)

I get this output:

 The requested package framework dev-master exists as Framework[dev-RC] but these are rejected by your constraint.

And I expected this to happen:
For several of our projects we have our own framework with two branches. The RC and the master branch. The RC is for developing and if it is passed the test it will be merged to the master branch. The master branch will be released online.

We maintain our own project and it has his own composer.json file.

For developing and our CI (Jenkins) we need the RC checkout of our repository. If it passes our test we merge the RC in the master and release the master branch online.

So what I would like is that when I run:
composer.phar update
That the RC branch is pulled from the repository.

When I run:
composer.phar update --no-dev
That the master branch is pulled from the repositry.

But this doesn't seem to work, is this possible?

**Comment by alcohol** [comment]
This is not supported. Composer takes both `require` and `require-dev` into consideration when resolving dependencies. You cannot have the same package in both sections. One will overwrite the other.
