### ISSUE TITLE
Option to disable generating autoload_static file and force pre1.1 behaviour.

### ISSUE THREAD

**Issue by khelle** [composer/composer#5651]
Hello,
I would like to request the option (CLI flag) to make composer disable generating autoload_static files and force pre1.1 autoloading behaviour. I know there were already requests for this, but each one were closed because of not providing good enough reason. Mine reason behind this is a fact that composer 1.1+ is unusable in multi-threaded PHP environment on version 7.0+, because threads by default nullifies static variables of not shared context.

**Comment by alcohol** [comment]
You can request all you want, but you will have much more success if you just submit a reasonable pull request. Also, AFAIK there have been no previous requests for this, so I am not sure where you saw all those "closed issues". Please feel free to correct me if I am wrong.

**Comment by Seldaek** [comment]
That sounds like a bug more than a reason to completely remove the feature. Can you provide details as to what you mean by multi-threaded php7? Is that with the pthreads extension or something else?

/cc @nicolas-grekas sounds like a fun new challenge presents itself ;)

**Comment by avant1** [comment]
Take a look at #5482, seems like the issue is similar, it even contains a workaround for it.

**Comment by Seldaek** [comment]
Ok indeed that seems like it's more an issue in pthreads than in Composer.
