### ISSUE TITLE
--no-dev does not ignore require-dev

### ISSUE THREAD

**Issue by bp1222** [composer/composer#5652]
I have provided two repositories that show this issue happening.

[Application](https://github.com/bp1222/application) is an example application that requires `~1.0.0` of the [Library](https://github.com/bp1222/library).  The library has 3 deployed tags, `1.0.0`, `1.0.1`, and `dev-master`.  The repository for library is located via Satis @ [packages.mudsite.com](https://packages.mudsite.com)

The Applications composer.json consists of:
```json
{
    "name": "bp1222/application",
    "description": "Example Application",
    "type": "project",
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.mudsite.com"
        }
    ],
    "require": {
        "php": ">=5.6.0",
        "bp1222/library": "~1.0.0"
    },
    "require-dev": {
        "bp1222/library": "dev-master as 1.0.0"
    }
}
```

The Libraries composer.json consists of:
```json
{
    "name": "bp1222/library",
    "description": "Example Library",
    "type": "library",
    "minimum-stability": "dev",
    "require": {
        "php": ">=5.6.0"
    }
}
```

**Running With "require-dev" containing the "dev-master as 1.0.0" line**
When I run this command from the Applications:
```
dwalker@linux:~/composertest/application › composer.phar update --no-dev
```

I get this output:
```
Loading composer repositories with package information
Updating dependencies
  - Installing bp1222/library (dev-master 436c7d0)
    Cloning 436c7d0e8db859627b337fb83ab1af0c7f6e8459 from cache

Writing lock file
Generating autoload files
```

And I expected this to happen:
I expect Library `1.0.1` to be installed, not `dev-master` at a commit past `1.0.1`

**Running With Applications "require-dev" empty**
When I run this command from the Applications:
```
dwalker@linux:~/composertest/application › composer.phar update --no-dev
```

I get this output:
```
Loading composer repositories with package information
Updating dependencies
  - Installing bp1222/library (1.0.1)
    Downloading: 100%         

Generating autoload files
```

And I expected this to happen:
I expect this to happen, this is the correct behavior.

**Comment by bp1222** [comment]
I can also confirm that the same behavior happens if:
```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/bp1222/library"
        }
    ],
```

Is used instead of Satis.

**Comment by alcohol** [comment]
See #5650

**Comment by bp1222** [comment]
@alcohol I see your comment in #5650 however that contradicts what is in the documentation.  So either the support for --no-dev should more literally be no "require-dev" considered, or the documentation about the composer.json schema should be changed:

> require-dev (root-only)#
> 
> Lists packages required for developing this package, or running tests, etc. The dev
> requirements of the root package are installed by default.  Both install or update
> support the --no-dev option that prevents dev dependencies from being installed.

It clearly reads that using --no-dev for install or update would render the dev dependencies from being used.  I can't find any documentation instructing us to prevent using a versioned package for require, and a dev-master version for dev.

**Comment by alcohol** [comment]
Not installed does not mean they are not taken into consideration for solving dependencies.

**Comment by bp1222** [comment]
But the end result, the documentation says --no-dev prevents from being installed.  Whereas the require-dev packages are in-fact installed.  If you use it for dependency resolution or not, isn't documented, what is is the opposite of the result.

**Comment by alcohol** [comment]
> Whereas the require-dev packages are in-fact installed.

No they are not.

**Comment by bp1222** [comment]
My steps laid out in the parent issue do showcase this.  The application has a require of library at `1.0.1`.  If you were to `composer update --no-dev`the installed library is not that of `1.0.1`, but dev-master a commit ahead of `1.0.1`.  So the use of --no-dev, when there is a `dev-master as` in require-dev does in stall the require-dev package over the require one.  That's the complaint in this issue.

**Comment by alcohol** [comment]
But as I told you, `require` and `require-dev` are merged. So the latter constraint always overwrites the former. Just because you are misusing the tools at your disposal and get undesirable results, that does not mean the tools are broken.

**Comment by bp1222** [comment]
I know you mentioned that in a comment to an issue. The documentation does not reflect that statement. What is a statement of fact, what is in RootPackage or whatever (been looking at code), and what is in documentation is different. 

I'm ok if what you're stating is the correct behavior, it needs to be documented as such though. 

That said, I'm learning the code and will eventually propose a PR to have the code behave as the documentation defines behavior.

**Comment by alcohol** [comment]
Ok, let me put it in simpler words.

The following is not supported, period:

```
    "require": {
        "php": ">=5.6.0",
        "bp1222/library": "~1.0.0"
    },
    "require-dev": {
        "bp1222/library": "dev-master as 1.0.0"
    }
```

**Comment by bp1222** [comment]
I understand that it is not. I wrote an issue that it should be. --no-dev
should mean, no require-dev. And it doesn't. That's the issue, that's my
example, that's the documentation. The fact it's not supported _is_ the
problem. It makes no sense that that example with --no-dev would install
anything _except_ the newest tag of 1.0.0 of the library that would
otherwise be installed with no require-dev directive.

**Comment by bp1222** [comment]
Or rather than back and fourth explain to me why it is that running
install/update with no-dev should install the master branch rather than the
version defined in require. I can't wrap my head around that as a concept.
Regardless to the technical limitation; it conceptually doesn't make sense
to me.

**Comment by alcohol** [comment]
This is completely unrelated to the `--no-dev` flag. We do not support listing the same package twice. I already mentioned this several times. Anyway, you are being incredibly stubborn and refuse to take in any of the information I am providing here, so I'm unsubscribing.

**Comment by Seldaek** [comment]
@bp1222 it's fine to request that feature be supported, but it's not a possibility we have. We have to compute all dependencies including dev ones otherwise it leads to weird edge cases, we did it the way you want before and it created issues so now it's all done in one go always, and thus it becomes impossible to override a required dependency in require-dev. That will surely not please everyone, but that's the state of the matter and it is not going to change.

**Comment by bp1222** [comment]
@Seldaek Thanks for explaining the reasoning behind it a bit more.  For my personal reference, and knowledge, is there any previous issues that you could point to that describe the weird edge cases?  I'm more intrigued to understand the current state as I can't conceptualize the odd-case.  If it wasn't listed anywhere, then I'll accept it as is and move on.

**Comment by Seldaek** [comment]
I don't remember exactly but one big issue is that the lock file is not created equal depending on whether you include dev requirements or not. That IMO is a big no no, because you should be able to take your dev lock file and push it to prod and install without dev packages and be sure you get the right stuff installed. Right now it is way more consistent as it always resolves the same way.

**Comment by bp1222** [comment]
Yes, that clarifies it up significantly for my thought process.  I think it's still a bit of a hiccup to me as where I'm at, we're both the application developers, and the library developers.  So in dev, I was wanting composer to install the libraries as clones of git so we can continue to develop within vendor/us/library.  But I do see us being the fringe case here, and the general usage would be to specify non-owned libraries  as your requirements, and dev being tools that aide in development, rather than development usages of your libraries.  @Seldaek thanks for taking the extra comments to clarify this for me.

**Comment by Seldaek** [comment]
You can install the lib as a clone even without requiring dev-master btw, see https://getcomposer.org/doc/06-config.md#preferred-install - then you can go in there and checkout master if you need to patch something.

**Comment by bp1222** [comment]
That does generally seem to work, although for no specific reason I'd prefer not to clone in prod and just download as dist.  However, it does seem preferred-install doesn't alter the lockfile, and the part in the composer.json instructs how to install the packages in the lock.  I assume that's intended.  I guess my overly ocd self would prefer to see a 'for dev' and a 'no-dev' option somewhere with preferred-install.  But I think excepting that, this is the behavior I was more looking for by duplicating packages in require&require-dev

**Comment by Seldaek** [comment]
You can do `install --no-dev --prefer-dist` in prod, IIRC that overrides 
all settings.
