### ISSUE TITLE
Some command does not work when a plugin add a custom repository

### ISSUE THREAD

**Issue by donaldinou** [composer/composer#5654]
I write a composer plugin and I need to create a custom repository (Don't ask me why the other could not do the job I want).

``` php
class Plugin {

    /* ... */

    public function activate(Composer $composer, IOInterface $io) {
            $this->composer = $composer;
            $this->io = $io;
            $this->composer->getRepositoryManager()->setRepositoryClass('custom', 'My\Custom\Repository\Class');
    }
}
```

"search" and some others commands work fine but not "show", "require" or "remove", "update" "install" commands.

With the following composer.json:

``` json
{
    ...
    "repositories": [
        {
            "type": "custom",
            "option": "..."
        }
    ]
    ...
}
```

When I run this command:

```
composer show xxx -vvv
```

I get this output:

```
Reading ./composer.json
Loading config file /home/xxx/.composer/auth.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Loading config file /home/xxx/.composer/auth.json
Failed to initialize global composer: Composer could not find the config file: /home/xxx/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running @package_version@ (@release_date@) with PHP 7.0.10-2+deb.sury.org~xenial+1 on Linux / 4.4.0-36-generic
Reading ./composer.json
Loading config file /home/xxx/.composer/auth.json
Loading config file ./composer.json
Reading ./composer.json
Loading config file /home/loyant/.composer/auth.json
Loading config file ./composer.json
Repository type is not registered: local
```

And I expected this to happen:

```
Reading ./composer.json
Loading config file /home/loyant/.composer/auth.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Failed to initialize global composer: Composer could not find the config file: /home/loyant/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /home/loyant/git/patisserie-ledaniel/drupal/vendor/composer/installed.json
Loading plugin My\Custom\Plugin
Running @package_version@ (@release_date@) with PHP 7.0.10-2+deb.sury.org~xenial+1 on Linux / 4.4.0-36-generic
name     : xxx
descrip. : xxx
versions : * vx.x.X
type     : x
...
```

I see that in show command it always get the composer instance with 

``` php
$this->getComposer(/*true*/);
```

And that the reason why the error is raise.

Is there a way to create a custom repository and directly set the class available for those commands? 

In order to work, I have to do this:

``` php
class Plugin {

    /* ... */

    public function activate(Composer $composer, IOInterface $io) {
            $this->composer = $composer;
            $this->io = $io;
            $this->composer->getRepositoryManager()->setRepositoryClass('custom', 'My\Custom\Repository\Class');
            $customRepository = $this->composer->getRepositoryManager()->createRepository('custom', array('option' => '....'));
            $this->composer->getRepositoryManager()->addRepository($customRepository);
    }
}
```

But this is not very "generic" in order to define "option" dynamically...

**Comment by alcohol** [comment]
So, I'm going to ask: why?

**Comment by donaldinou** [comment]
Si, I'm going to answer why not? 




Seriously, because I've got some libraries from a custom old framework. It Will be used like the pathRepository instead it has no composer.json the informations are stored un a projection.settings file. And I need to rework some methods from the repository.
I think create a custom repository is not very curious even if m'y needs are..

**Comment by alcohol** [comment]
Just use https://getcomposer.org/doc/05-repositories.md#package-2 :-)

**Comment by donaldinou** [comment]
Thanks but that not what I need... 
I will not define all those packages one by one (Or I misunderstood something)...

/-Path 1
|----/libraries
      |----/lib1 v1.0.1.1
      |----/ (a lot of other custom library)

/-Path 2
|----/libraries
      |----/lib1 v1.0.2.1
      |----/ (a lot of other custom library)

etc..

/-git
|----/lib1 v1.0.0 -> v1.0.3 (there is no v1.0.1.1 or v1.0.2.1)


And for example
```json
{
    "require": {
        "lib1": "<1.0.1 >=1.0.3"
    },
    "conflict": {
        "lib1": "1.0.2.1"
    }
}
```

So I'm expected to retrieve lib1 in a v1.0.1.1 or v1.0.2.x but I don't know where is the right version. And that for many others libs. 
I cannot do a "custom packagist" because I've got a lot of projects that I want progressively migrate from git or another. But it will be very long.
So I've really think about it and the best idea is to create a custom repository (what a big deal) with a composer plugin in order to manage my dependencies like I need.

Project1
```json
{
    "require": {
        "plugin": "*"
    },
    "repositories": [
    {
        "type": "custom",
        "option": "..."
    },
}
```

Project2
```json
{
    "require": {
        "plugin": "*"
    },
    "repositories": [
    {
        "type": "custom",
        "option": "anothers options..."
    },
}
```

etc...

**Comment by alcohol** [comment]
Ok, good luck.

**Comment by donaldinou** [comment]
Thank you... I already have something working, but my original question is not why I need to do that is why we cannot simply create a custom repository and define how it work in the composer.json like the other one?

(In order to set options to my custom repository I use the "extra" parameters from the json... And I'm sure this is not what we expect to do to set the $repoConfig)

**Comment by alcohol** [comment]
I'm not sure I understand your issues or your concerns. I am also not intimately familiar with the plugin system, since I never use it personally.

Looking at your code and the RepositoryManager code, I don't see why the following results in an error
```
$this->composer->getRepositoryManager()->setRepositoryClass('custom', 'My\Custom\Repository\Class');
```
while this does not
```
$this->composer->getRepositoryManager()->setRepositoryClass('custom', 'My\Custom\Repository\Class');
$customRepository = $this->composer->getRepositoryManager()->createRepository('custom', array('option' => '....'));
$this->composer->getRepositoryManager()->addRepository($customRepository);
```

The error you reported
```
Repository type is not registered: local
```
should only be triggered if you did not call `setRepositoryClass`, but you did, in both cases.

**Comment by donaldinou** [comment]
This is because parsing of the root composer.json is done before initializing Plugins (And that the way it should be I think).
But, the repositories are also loaded before the activation of a Plugin (from the factory behind $this->getComposer(true)).
So, if we define a custom repository in the json the class mapping is not set -> Error.

Now, if we create the custom repository in the plugin activate method it will work as expected but it is not "configurable".

workflow in json:
load json -> load repositories -> load plugin -> define custom class repository -> ...

workflow in plugin:
load json -> load repositories -> load plugin -> define custom class repository -> load custom repository -> ...

**Comment by Seldaek** [comment]
@donaldinou if you have the whole package metadata available why don't use you build a simple CLI script that crawls it and dumps a packages.json file so that you can use that as a "composer" typed repository? That sounds easier and more efficient than messing around with plugins and reloading the metadata at runtime every time.

**Comment by Seldaek** [comment]
Closing issue as it has been quiet for a long time and there is no clear next step we can take.
