### ISSUE TITLE
Unable to download & install laravel with composer

### ISSUE THREAD

**Issue by quoctrung2610** [composer/composer#5656]
With the following composer.json:

> {
>     "name": "laravel/laravel",
>     "description": "The Laravel Framework.",
>     "keywords": ["framework", "laravel"],
>     "license": "MIT",
>     "type": "project",
>     "require": {
>         "php": ">=5.6.4",
>         "laravel/framework": "5.3._"
>     },
>     "require-dev": {
>         "fzaninotto/faker": "~1.4",
>         "mockery/mockery": "0.9._",
>         "phpunit/phpunit": "~5.0",
>         "symfony/css-selector": "3.1._",
>         "symfony/dom-crawler": "3.1._"
>     },
>     "autoload": {
>         "classmap": [
>             "database"
>         ],
>         "psr-4": {
>             "App\": "app/"
>         }
>     },
>     "autoload-dev": {
>         "classmap": [
>             "tests/TestCase.php"
>         ]
>     },
>     "scripts": {
>         "post-root-package-install": [
>             "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
>         ],
>         "post-create-project-cmd": [
>             "php artisan key:generate"
>         ],
>         "post-install-cmd": [
>             "Illuminate\Foundation\ComposerScripts::postInstall",
>             "php artisan optimize"
>         ],
>         "post-update-cmd": [
>             "Illuminate\Foundation\ComposerScripts::postUpdate",
>             "php artisan optimize"
>         ]
>     },
>     "config": {
>         "preferred-install": "dist"
>     }
> }

When I run this command:

```
php composer.phar install
```

or:

```
composer global require "laravel/installer"
```

I get this output:

```
C:\wamp\www\st>php composer.phar install
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Updating dependencies (including require-dev)


  [Composer\Downloader\TransportException]
  The "http://packagist.org/p/laravel/framework%24d96abc693256d946d71122810d8151f9d954c7740b9889494f8d6f4136b10893.js
  on" file could not be downloaded: failed to open stream: HTTP request failed!


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...
```

I could not download laravel package.

**Comment by Seldaek** [comment]
Try to force https for all resources by running `composer config -g repo.packagist composer https://packagist.org` - that usually helps get around such network issues.

**Comment by dameety** [comment]
@Seldaek Thanks. You just help solved my composer/image intervention issue.

**Comment by ashish135** [comment]
Hello,

I'm getting this error...

The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: Connection timed out
https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date


  [Composer\Downloader\TransportException]
  The "https://packagist.org/p/intervention/image%243890bd39eb46bef5763ee74a0815873acd5a6a9eea8cdd3521a8a0a28317c7d0.json" file could not be downloaded: failed to open stream: Connection timed o
  ut

Using php composer.phar require intervention/image this command.

Help Me!

**Comment by victorhugorch** [comment]
Add this lines to your composer.json @ashish135 

```
"repositories": [
      {
        "type": "composer",
        "url": "https://packagist.org"
      },
      { "packagist": false }
    ]

```

**Comment by genyded** [comment]
Why is https not the default?

**Comment by donkovah** [comment]
@victorhugorch Your answer was brief, But helped a lot. Thanks

**Comment by fsevenm** [comment]
The solution from @Seldaek also work. Thanks

**Comment by flashadvocate** [comment]
Thanks @Seldaek

**Comment by Benjy1979** [comment]
Worked for me with mpdf install as well. Thanks,

**Comment by felipearaujodev** [comment]
@victorhugorch  solution worked

**Comment by mayur22-pune** [comment]
Hello Frirnds,
I am getting this error while installing laravel by composer by cmd

  [Composer\Downloader\TransportException]
  Content-Length mismatch, received 1490135 bytes out of the expected 2080224


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--r
epository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no
-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vc
s] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<dir
ectory>] [<version>]


So anyone can tell the solution

i used following command to install laravel

composer create-project laravel/laravel laravel "5.1.*"

Please Help me...

**Comment by rob006** [comment]
> Try to force https for all resources by running `composer config -g repo.packagist composer https://packagist.org` - that usually helps get around such network issues.

Shouldn't this be `https://repo.packagist.org` now instead of `https://packagist.org`? I've seen a lot of people refer to this comment as an official solution blessed by Composer's maintainer. It may be a good idea to update it after switching to `repo.packagist.org`.

**Comment by sjntruong** [comment]
> Add this lines to your composer.json @ashish135
> 
> ```
> "repositories": [
>       {
>         "type": "composer",
>         "url": "https://packagist.org"
>       },
>       { "packagist": false }
>     ]
> ```

thank you, it work with my case.

**Comment by fabiobagattoli** [comment]
Para mim não resolveu
