### ISSUE TITLE
Install packages locally works not as expected (at least not from the User's Working Model point of view)

### ISSUE THREAD

**Issue by sinkaszab** [composer/composer#5658]
Install packages:

I successfully installed composer on Mac OS X 10.11.6. I installed it into a project directory.
So, composer will basically downloaded to: Users/MyUser/
My composer.phar then goes to Users/MyUser/Projects/project.local/
And then when I want to install a package, composer looks for the json in:
Users/MyUser/ dir
instead its project folder.
Kinda not good.

**Comment by alcohol** [comment]
> I installed it into a project directory.

What does that mean?

> So, composer will basically downloaded to: Users/MyUser/

What? Why?

> My composer.phar then goes to Users/MyUser/Projects/project.local/

Your composer.phar travels?

> And then when I want to install a package, composer looks for the json in:

Install how? Be descriptive, tell us what command you run and where you run it.


Using issue template: ★★★☆☆
Issue description: ★☆☆☆☆
Overal experience: ★★☆☆☆

**Comment by sinkaszab** [comment]
Okay, sorry, my bad...

I open a terminal and it basically gives me this starting point as of the location in the file system:
`/Users/MyUser/`

`php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"` -> Works fine.
Puts composer-setup.php into: `/Users/MyUser/` directory.

`php -r "if (hash_file('SHA384', 'composer-setup.php') === 'e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" `-> Works fine.

`php composer-setup.php --install-dir=Projects/Project/`
I install the composer.phar into a local project directory. Which will then be located there form then on. (Full path then: `Users/User/Projects/Project/composer.phar`)

Then comes my problem when I would like to install a package.

`php Projects/Project/composer.phar install`
This doesn't work as I assumed. Because I would like my package to be installed here:
`Users/User/Projects/Project/vendor/package`
Instead the package will land here:
`Users/User/vendor/package`

So summarizing the problem:
I want composer to be local, but instead, packages will land on a global location.

**Comment by sinkaszab** [comment]
Sorry. I'm new...

**Comment by alcohol** [comment]
Ah, okay, that explanation is much more useful. Thank you.

So the problem is that your working directory is different. You need to either `cd` into it, or pass it as an extra argument (`-d`).

**Comment by sinkaszab** [comment]
Yes! Works just as expected. However would be nice if that would be handled automatically OR mentioned in the documentation.
