### ISSUE TITLE
Global config option to disable plugins and scripts

### ISSUE THREAD

**Issue by kelunik** [composer/composer#5659]
There's [documentation available to disable plugins and scripts](https://getcomposer.org/doc/faqs/how-to-install-untrusted-packages-safely.md) by passing the appropriate command line options: `--no-plugins --no-scripts`. Unfortunately, there's no (documented) way to make that the default via the global configuration.

Please add a configuration option to disable scripts and / or plugins globally.

**Comment by Seldaek** [comment]
Yeah I think an allowlist in composer.json sounds like the best option here. And I agree we probably should do this to avoid any bad surprises. Although a compromised package can still do a bunch of damage via files autoloading for example, as soon as the project code is executed. But I see your point that at composer runtime at least we should be safer by default.

**Comment by Seldaek** [comment]
WIP here https://github.com/composer/composer/pull/10314 if someone wants to have a look already.
