### ISSUE TITLE
GitLab authentication require to public repository

### ISSUE THREAD

**Issue by emulienfou** [composer/composer#5661]
Moving my package from **GitHub** to **GitLab** as a public repository, I come across some problems when trying to do a simple: `composer require dwoo/dwoo`.

With GitHub, no authentication was required because my project was _public_, now with GitLab I get the next message:

```
Could not fetch https://gitlab.com/api/v3/projects/dwooproject%2Fdwoo/repository/archive.zip?sha=00c2fa7adc36ad6aaa8114c1fe1279158183d1be, enter your gitlab.com credentials to access private repos
A token will be created and stored in "/home/david/.composer/auth.json", your password will never be stored
To revoke access to this token you can visit gitlab.com/profile/applications
```

> I'd like to precise that my project has the _public_ visibility too in GitLab.

---

Like describe in the official [GitLab documentation](https://docs.gitlab.com/ce/api/):

> All API requests require authentication via a token. There are three types of tokens available: private tokens, OAuth 2 tokens, and personal access tokens.
- It would be interesting to be able to get from public repository the archive without getting it from the GitLab API but from the public URL, such as: https://gitlab.com/dwooproject/dwoo/repository/archive.zip?ref=1.2.1

Thanks for your help!!!

**Comment by alcohol** [comment]
`/api/v3/` is a Github url, not Gitlab. Something is wrong in your config.

**Comment by emulienfou** [comment]
I'n not in this configuration, I receive this message when I just do a `composer require dwoo/dwoo` in a new folder for testing, outside any project. So no **composer.lock**. I remove all my config and cache from composer in my computer I test it and having the same problem.

**Comment by Spittal** [comment]
I'm having this issue where it will refuse to authenticate as I composer install:

My composer.json looks like this:
```javascript
    //...
    "require": {
        // ...
        "skyrkt/bentobox": "^0.0.15",
        // ...
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://gitlab.com/Skyrkt/Bentobox.git"
        }
    ],
    "config": {
      "gitlab-token": {
        "gitlab.com": "************** <-- my personal token"
      }
    }
```

But for some reason whenever I composer install I get this message:

```
Installing skyrkt/bentobox (0.0.15)
    Downloading: Connecting...    Failed to download skyrkt/bentobox from dist: Could not authenticate against gitlab.com
    Now trying to download from source
  - Installing skyrkt/bentobox (0.0.15)
    Cloning 894977ce09eba00e47de4dc2c03653cef00add28 from cache
```

This is really causing me a lot of grief, because this is a 100% public repository on Gitlab

**Comment by Bedotech** [comment]
I have the same problem as @Spittal i can't get Gitlab repo with token.

**Comment by Luceos** [comment]
Tried everything I could, but can't seem to get a private repository to work with any token. Also the url provided to create a token is invalid, it references a applications (that have a required callback) `gitlab.com/profile/applications`. The link should probably have been `gitlab.com/profile/personal_access_tokens`.

**Comment by stof** [comment]
See the discussion in https://github.com/composer/composer/issues/5988. Authenticating with a personal token on gitlab requires Composer 1.3, as it is part of the improvements done to the Gitlab integrations in 1.3).
and composer 1.3 is currently in RC (so available in the preview channel when updating)

**Comment by mlncn** [comment]
This should be fixed on Gitlab's side for public repositories, correct?

Asked them to fix it here: https://gitlab.com/gitlab-org/gitlab-ce/issues/29662
