### ISSUE TITLE
XzDownloaderTest fails on OS X because of different error message

### ISSUE THREAD

**Issue by martinsik** [composer/composer#5662]
When I clone `composer/composer`, install depenencies and run:

    $ ./vendor/bin/phpunit tests/Composer/Test/Downloader/XzDownloaderTest

It fails with:

```
$ ./vendor/bin/phpunit tests/Composer/Test/Downloader/XzDownloaderTest
PHPUnit 4.8.27 by Sebastian Bergmann and contributors.

F

Time: 233 ms, Memory: 6.00MB

There was 1 failure:

1) Composer\Test\Downloader\XzDownloaderTest::testErrorMessages
Failed asserting that 'Failed to execute tar -xJf '/private/var/folders/wn/t3gy9dzj07v3vlbd5pjxczy40000gn/T/composer-test-612657d28ad4495a7/XzDownloaderTest.php' -C '/private/var/folders/wn/t3gy9dzj07v3vlbd5pjxczy40000gn/T/composer-test-669757d28ad4406f5/composer/ee4099fc'

tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
' contains "File format not recognized".

/Users/martin/git/composer/tests/Composer/Test/Downloader/XzDownloaderTest.php:75

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

The test checks that the error message contains `File format not recognized` but it contains `tar: Unrecognized archive format ...` instead. This probably happens only on OS X since nobody reported anything similar yet.

OS X: 10.11.6
```
$ tar --version
bsdtar 2.8.3 - libarchive 2.8.3
```

**Comment by alcohol** [comment]
The problem lies in the fact that Mac OS X uses bsdtar, whereas most Linux systems use gnutar.

You can install gnutar on a Mac with Homebrew, using `brew install gnu-tar`, which will symlink gnutar into /usr/local/bin as gtar. You can also choose to install it without the `g` prefix. If you then put `/usr/local/bin` at the front of your PATH, any invocation of `tar` will use the gnu version instead of the bsd one.

**Comment by Seldaek** [comment]
Please confirm if it works for you now. I don't have a mac at hand.

**Comment by martinsik** [comment]
I can confirm it passes now. This is actually what I was going for rather that installing a separate `tar` because there'd be more people facing this issue due to the number of different implementations: http://unix.stackexchange.com/questions/101561/what-are-the-differences-between-bsdtar-and-gnu-tar
