### ISSUE TITLE
Can Composer skip the sample codes of libraries? 

### ISSUE THREAD

**Issue by shivanraptor** [composer/composer#5663]
I got a feature request.

Composer is a great tool to manage third-party library files. However, I think Composer should let the library owner to specify which directories are not required to be uploaded in PRD environment, such as sample codes. If Composer can add a new option in `composer.json` to specify whether downloading the sample codes or not, that will be great.

**Comment by JoeBengalen** [comment]
Checkout export-ignore in the .gitattributes

**Comment by Seldaek** [comment]
Yup, package authors can configure that using .gitattributes.
