### ISSUE TITLE
composer show gibberish characters in windows cmd

### ISSUE THREAD

**Issue by yikuo123** [composer/composer#5666]
when composer work with cmd(windows 10), the output is gibberish characters, but it work well with powershell
![qq 20160912163323](https://cloud.githubusercontent.com/assets/13978174/18429725/93ffd1b4-7907-11e6-9900-e90c6f63ada8.png)
![qq 20160912164035](https://cloud.githubusercontent.com/assets/13978174/18429764/c9acd4ba-7907-11e6-9145-d0da96300988.png)

**Comment by Seldaek** [comment]
This is a problem with Windows 10 really, and has been documented there #5323

**Comment by johnstevenson** [comment]
This has been fixed in symfony/console now, so a new Composer release pulling in the updated package will fix it for Win 10 anniversary update users.

**Comment by Seldaek** [comment]
@johnstevenson got a commit ref? In which release is it? Because Composer 1.2.1 includes sf 2.8.10..

**Comment by johnstevenson** [comment]
Ah, so this is now fixed in Composer 1.2.1.

(Symfony 2.8.10 resolved this). Sorry, I assumed 1.2.0 was the latest stable, because the screenshots from @yikuo123 showed this version.

**Comment by yikuo123** [comment]
Thanks to @Seldaek and @johnstevenson , it works perfectly now.
