### ISSUE TITLE
Using composer programatically to resolve a class with autoloading

### ISSUE THREAD

**Issue by felixfbecker** [composer/composer#5671]
I am currently working on a PHP language server that will use the open language server protocol and will be used by different IDEs (VS Code, Eclipse Che). It is completely implemented in PHP, using the great PHPParser package.

For completion, it should resolve a type (like a class) to a file path if the symbol does not exist in the current file the same way composer autoloading would resolve it. Basically honor psr-4, psr-1, classmap and also the `files` property in both the user's project but also its dependencies.

Instead of essentially implementing this algorithm I thought about using the composer package programmatically. Is there a way to do what I am after? I have a fully qualified class name and need to get the file path.

**Comment by Seldaek** [comment]
You could simply `$loader = include 'vendor/autoload.php';` and then get the path via ReflectionClass or using `$loader->findFile()`.

Alternatively, you could add composer/composer as a dependency and build an autoloader from scratch but I don't really see a benefit there.

**Comment by felixfbecker** [comment]
But that would also _register_ the autoloader, correct?

**Comment by felixfbecker** [comment]
It would also be nice to add stubs for built-in PHP classes/files to the autoloader.

**Comment by Seldaek** [comment]
The stubs thing sounds very much out of scope for Composer.

Regarding the autoloader, yeah it would be registered, but you can easily `->unregister()` it. The only potential side effect remains the inclusion of files contained in `autoload_files.php` - if that's unacceptable then you could configure the autoloader yourself, minus autoload_files (see autoload_real.php for how its done), but then you might end up with undiscoverable symbols.

**Comment by Seldaek** [comment]
Closing issue as it has been quiet for a long time and there is no clear next step we can take.
