### ISSUE TITLE
error coded zendguard 7

### ISSUE THREAD

**Issue by dpbuzz** [composer/composer#5672]
I am adding a api to a project coded with zendguard7 on debian8 + php5.6 + apache2.4
Api works ok uncoded
When coded with zendguard show error:

```
mod_fcgid: stderr: PHP Fatal error:  require(): Failed opening required '' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/clients/client61/web61/web/rh/api/vendor/composer/autoload_real.php on line 66
```

My `composer.json`:

``` json
{    "require": {
        "slim/slim": "^3.0",
        "tuupola/slim-jwt-auth": "^2.3",
        "firebase/php-jwt": "^4.0"
    }
}
```

My `autoload_real.php`:

``` php
<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit1d9ea7a8f631ff74c8abc24ae2e2277a
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInit1d9ea7a8f631ff74c8abc24ae2e2277a', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader();
        spl_autoload_unregister(array('ComposerAutoloaderInit1d9ea7a8f631ff74c8abc24ae2e2277a', 'loadClassLoader'));

        $useStaticLoader = PHP_VERSION_ID >= 50600 && !defined('HHVM_VERSION');
        if ($useStaticLoader) {
            require_once __DIR__ . '/autoload_static.php';

            call_user_func(\Composer\Autoload\ComposerStaticInit1d9ea7a8f631ff74c8abc24ae2e2277a::getInitializer($loader));
        } else {
            $map = require __DIR__ . '/autoload_namespaces.php';
            foreach ($map as $namespace => $path) {
                $loader->set($namespace, $path);
            }

            $map = require __DIR__ . '/autoload_psr4.php';
            foreach ($map as $namespace => $path) {
                $loader->setPsr4($namespace, $path);
            }

            $classMap = require __DIR__ . '/autoload_classmap.php';
            if ($classMap) {
                $loader->addClassMap($classMap);
            }
        }

        $loader->register(true);

        if ($useStaticLoader) {
            $includeFiles = Composer\Autoload\ComposerStaticInit1d9ea7a8f631ff74c8abc24ae2e2277a::$files;
        } else {
            $includeFiles = require __DIR__ . '/autoload_files.php';
        }
        foreach ($includeFiles as $fileIdentifier => $file) {
            composerRequire1d9ea7a8f631ff74c8abc24ae2e2277a($fileIdentifier, $file);
        }

        return $loader;
    }
}

function composerRequire1d9ea7a8f631ff74c8abc24ae2e2277a($fileIdentifier, $file)
{
    if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
        require $file;

        $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;
    }
}
```

**Comment by alcohol** [comment]
Sorry, but the information you provided does not really help us identify your issue.

**Comment by Seldaek** [comment]
Can you paste the content of `vendor/composer/autoload_files.php`? That seems like the culprit, but if so it is most likely a configuration issue.

**Comment by dpbuzz** [comment]
Hi thanks for your answer, let me know if what you need to help identify the problem. My autoload_files.php is:

<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '253c157292f75eb38082b5acb06f3f01' => $vendorDir . '/nikic/fast-route/src/functions.php',
);

**Comment by Seldaek** [comment]
Well that doesn't really help no.. `Failed opening required ''` it says, so it looks like it's trying to include an empty string, but that's clearly not an empty string.. I wonder if ZendGuard might have a bad impact on the optimized static loader. Any clue @nicolas-grekas?

**Comment by dpbuzz** [comment]
Ok I will also start an issue at Zend.

**Comment by nicolas-grekas** [comment]
No idea yet...

**Comment by dpbuzz** [comment]
Hi, I have this response at Zend:
"We know about a problem with autoloaders due to obfuscation mechanism, we're looking into this issue.
Please load the modules directly to skip autoloader code, let me know if it works.
I will try to get a minimal example - if you have something up your sleeve I will test it against the open issue.
You can also try to encode without security options for testing how it works without obfuscation, or try to add 'zend_runtime_obfuscate();' to the beginning of the PHP flow (before loading autoloader_real.php) in case it resolves the runtime names diff."

Is it posible to load the modules directly to skip autoloader code?

**Comment by hmic** [comment]
I'm interested too.
ZendGaurd is utter bullsh***, actually. No wonder they discontinued it *finally*...

But still, composer without autoloading? How would the Zend guys think of this as of today? *lol*

**Comment by hmic** [comment]
If anybody still interested, please test #5930 ! Works in my cases, might not work for you...
Keep in mind you need to *DISABLE* The obfucation on the "Classes" type in the security settings. All other obsfucations can be enabled without problems - YMMV.

If you add the additional checks to your already generated autoload_real.php please keep in mind that the file gets updated by composer automatically!

**Comment by dpbuzz** [comment]
Hi, how can update my composer with this changes to test it?

**Comment by dpbuzz** [comment]
In autoload_real.php I change: 
//$useStaticLoader = PHP_VERSION_ID >= 50600 && !defined('HHVM_VERSION');
$useStaticLoader = FALSE;

And the coded version begins to work!

**Comment by hmic** [comment]
This is basically what the fix does - don't ise the static loader if the autoload_real.hpp file itself is encoded. It's not perfect, but does the job as long as you encode the whole project, including all the composer installed libs.

**Comment by dpbuzz** [comment]
Yes I need to fix this now...
Will your fix be added to the main branch? How can I check when is added?

**Comment by hmic** [comment]
I don't know. I've just fixed the testcases. They have been very supportive, as it's a very small and easy fix, I think it might very well be included in the next release.
You could vote up 👍 my #5930 PR, to tell them there is more interest in it working - but since this issue has not been revisited in some time, i don't think many would use it.
Actually ZendGuard has been discontinued and there will be no follow up product for PHP7 onwards AFAIK, so it's of quite limited use anyways :-/

**Comment by dpbuzz** [comment]
thanks all for your help!

**Comment by msumme** [comment]
Thanks @hmic !  This was a lifesaver.

**Comment by xrobau** [comment]
Just as a FYI, this is actually more of an issue than it seems at face value.

The ZendGuard loader  **permanently breaks** the autoloader for that PHP run if you try to include a *licenced* file that is not licenced for the machine you are currently running it on.

For example, the ZendGuard documentation implies that you can see if your code is licenced for the machine you're running on by using zend_loader_file_licensed() (which only works on a licenced file) and then checking the results.

However, if you try to use that function and the machine is NOT licenced, the autoloader is destroyed. Only the magic __get and equivalent functions still work.

I'm leaving this note here in the hope that someone else who is having this issue won't need to spend the time I did discovering this.
