### ISSUE TITLE
Delete autoloader

### ISSUE THREAD

**Issue by ace411** [composer/composer#5677]
Hello there. I would like to find out how I can install my composer packages without the autoloader that comes with them.

**Comment by curry684** [comment]
You can't, barring manually deleting vendor/composer. Why would you ever want this though? The autoloaders are generated according to the package's rules, most are unusable without that.

**Comment by rosasurfer** [comment]
Indeed, you can. You might want to do so if you want to use your own or another class loader, e.g. the one that comes with Phalcon. Just pick Composer's auto loader from the SPL loader queue with ```spl_autoload_functions()``` (if you configured ```prepend=true``` it's the first one), get all the package information from it (there are getters) and pass that on to your preferred substitute. Lastly you unregister it with ```$loader->unregister()```.
Just know what you do.

**Comment by alcohol** [comment]
Your topic and opening post do not seem to match.

Your topic mentions deleting the autoloader (there is no need to delete anything, just stop using it).

Then you ask how you can install packages without the autoloader that comes with them. Packages do not come with an autoloader. Composer generates an autoloader.

**Comment by staabm** [comment]
@alcohol  the initial poster and the last comment are from 2 different accounts (persons?)

**Comment by curry684** [comment]
@rosasurfer of course you can delete, replace, or not use them as I also mentioned, but Composer does not have an option not to generate them. That was the actual question asked.

**Comment by alcohol** [comment]
> @alcohol the initial post and the last comment are from 2 different accounts (persons?)

This question seems rhetorical since you're stating the obvious, but yes, they are from different accounts.
