### ISSUE TITLE
[Windows] - The post-install-cmd event returned with error code 1

### ISSUE THREAD

**Issue by shivapoudel** [composer/composer#5680]
While using this `composer.json` and executiong command `composer install`

```
{
  "name": "flash-toolkit/flash-toolkit",
  "description": "ThemeGrill Core Toolkit Plugin for Flash Theme.",
  "homepage": "http://themegrill.com/plugins/flash-toolkit/",
  "type": "wordpress-plugin",
  "license": "GPL-3.0+",
  "require": {
    "composer/installers": "~1.0"
  },
  "require-dev": {
    "squizlabs/php_codesniffer": "*",
    "wp-coding-standards/wpcs": "*",
    "simplyadmire/composer-plugins" : "@dev"
  },
  "scripts": {
    "post-install-cmd": [
      "vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs"
    ],
    "post-update-cmd": [
      "vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs"
    ]
  }
}
```
Got this error on windows:
![capture](https://cloud.githubusercontent.com/assets/3774827/18575643/da884eb4-7bf9-11e6-828f-a1b0def61417.PNG)

**Comment by curry684** [comment]
From what I see the scripts are passed unprocessed to the system functions, hence causing this error because PHP on Windows may very well be agnostic to filesystem separators, the shell sure as hell isn't  :wink: 
```sh
C:\>vendor/bin/phpcs
'vendor' is not recognized as an internal or external command,
operable program or batch file.
```
We *could* fix this by preprocessing the field through the symfony/console [StringInput](https://github.com/symfony/console/blob/master/Input/StringInput.php) class, it's got the required logic for reliably separating command and arguments, not quite sure we should as it may cause worse new issues.

Workaround for now is using Bash for Windows on Windows 10 Anniversary edition or MingW, both use slashes instead of backslashes hehe.

**Comment by curry684** [comment]
Also btw your construct could never work anyway as Windows can't process shebangs, so `phpcs` can't be executed anyway. Explicitly using PHP will solve both issues as it will preprocess the path itself:
```json
"post-install-cmd": [
      "php vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs"
    ],
```

**Comment by shivapoudel** [comment]
> Explicitly using PHP will solve both issues as it will preprocess the path itself:

![capture](https://cloud.githubusercontent.com/assets/3774827/18579692/feca0868-7c16-11e6-95a6-aacacc0d8b5b.PNG)

@curry684 It displays above error if we use `php` :p

**Comment by curry684** [comment]
I was assuming `phpcs` to be a PHP file, but a bash script isn't going to execute on Windows one way or another  :)

Find a way to run it manually and then copy/paste that in the trigger commands. Composer is agnostic to platforms in this so we can't help you.

**Comment by alcohol** [comment]
@curry684 That looks like the unixy proxy code we install in some cases.

**Comment by alcohol** [comment]
Which I think we install because he is using http://www.mingw.org/ - which is basically asking for trouble, so there is not much more we can do here I think.

**Comment by Seldaek** [comment]
The way to call composer binaries is to just call the binaries directly, as we push bin-dir to the path, it works better if you do `"phpcs --config-set ..."` than `"vendor/bin/phpcs ..."`. Try it, AFAIK it works fine on windows too.

**Comment by Manuel-042** [comment]
when trying to install firebase php/jwt using composer I got this error - **Script sed -i s/name{0}/name[0]/ vendor/mikey179/vfsstream/src/main/php/org/bovigo/vfs/vfsStream.php handling the post-update-cmd event returned with error code 1 -** 
Please can someone help me navigate through this

**Comment by stof** [comment]
Please open a new issue following the template instead of commenting on an issue closed since 2016.
