### ISSUE TITLE
Run scripts only if the class is found

### ISSUE THREAD

**Issue by theofidry** [composer/composer#5684]
My `composer.json`:

```json
{
  "require": {
    "acme/lib1": "dev-master"
  },
  "require-dev": {
    "acme/lib2": "dev-master"
  },
  "scripts": {
    "post-install-cmd": [
      "Acme\\lib1\\Dummy::postInstallScript",
      "Acme\\lib2\\AnotherDummy::postInstallScript"
    ]
  }
}
```

Now if I do a `composer install --no-dev`, it will fail because it won't find `Acme\lib2\AnotherDummy` which is a dev dependency. If I do `composer install --no-dev --no-script`, `Acme\lib1\Dummy::postInstallScript()` won't be called.

Is there anyway to get around that natively in Composer or should I implement a thin wrapper to check the existence of the class to not run the script if it can't?

**Comment by alcohol** [comment]
Since order is important, simply place the non-dev scripts before the dev ones. That way it will fail at the right point in time.

**Comment by theofidry** [comment]
@alcohol that might be a little workaround, but you would still get a failure. Well I'll check this wrapper thing, should be fairly simple although I doubt it will be useful to many people, neither I think this should belong to the core (unless you think it's interesting to).

Unless you see something else to it, you can close the issue :)

**Comment by alcohol** [comment]
I'm not sure what a nice approach would be;
* could add a check for class existence and output a warning / skip,
* could add a "scripts-dev" section.

Multiple roads to go down. I'm not sure which has more merit, and if any are even worth the effort.

**Comment by theofidry** [comment]
Well not sure either ;)

Honestly unless there is more people asking for it and as I'm the first one posting an issue on it, I don't feel like this is needed in the core. I might be wrong and a lot of people are actually annoyed by that, dunno.

I was thinking of a wrapper doing 1., unlike 2. it doesn't require any change in the `composer.json`. And I it turns out I was wrong and it would be great to integrate it in Composer, this could be done extremely easily. There is no big difference DX wise AFAICT.

**Comment by Seldaek** [comment]
If anything, I think I'd rather have a hack-ish kind of `?ClassName::func` to make it optional or something, which would just skip failures in case the class is not found. But the best would definitely be to let users handle this and not change anything in Composer. Closing for now until you sort it out :)

**Comment by theofidry** [comment]
@Seldaek I though this could be done with an regular script but they [only takes an event](https://github.com/composer/composer/blob/master/src/Composer/EventDispatcher/EventDispatcher.php#L269) an nothing more so I don't see how I can solve it on my end (i.e. by not doing something in the code). So your `?ClassName::func` looks by me: should I do a PR for that?

**Comment by Seldaek** [comment]
What do you mean they only take an event? The event contains a lot of stuff.. What are you trying to do that you can't?

**Comment by theofidry** [comment]
I was thinking of something along the lines of:

```json
{
  "scripts": {
    "post-install-cmd": [
      "Fidry\\ScriptHandler::executeIfClassExists('Acme\\lib2\\AnotherDummy::postInstallScript')"
    ]
  }
}
```

with something like:

```php
namespace Fidry;

use Composer\Script\Event

class ScriptHandler
{
  public static function executeIfClassExists(string $callable, Event $event)
  {
    $className = substr($callable, 0, strpos($callable, '::'));
    $methodName = substr($callable, strpos($callable, '::') + 2);

    return $className::$methodName($event);
  }
}
```

'coz I naively though you could pass arguments like that in `scripts`.

**Comment by Seldaek** [comment]
I see.. do you wanna write a lexer for the args maybe? ;)

Anyway yeah maybe ?-hack prefix might be a thing, not really pretty but oh well..

**Comment by theofidry** [comment]
>do you wanna write a lexer for the args maybe? ;)

# NOPE.

>Anyway yeah maybe ?-hack prefix might be a thing, not really pretty but oh well..

`scripts-dev` might be more, erm, logical? But I personally find the `?className::method` more elegant.

**Comment by Seldaek** [comment]
Yeah, that said.. https://github.com/composer/composer/issues/4358 reminded me of  https://github.com/neronmoon/scriptsdev :p You could do that in your plugin too I suppose.

**Comment by theofidry** [comment]
or I could just use that plugin... I must really learn to use packagist API: https://packagist.org/search/?q=&type=composer-plugin.
