### ISSUE TITLE
OpenSSL Error

### ISSUE THREAD

**Issue by sger** [composer/composer#5685]
Hello, 

I'm on macOS Sierra with cmd 

`php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"`

getting 

`Warning: copy(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in Command line code on line 1

Warning: copy(): Failed to enable crypto in Command line code on line 1

Warning: copy(https://getcomposer.org/installer): failed to open stream: operation failed in Command line code on line 1`

any idea how to fix this?

**Comment by Seldaek** [comment]
You can use `http://` instead of https if that helps, it doesn't really matter as long as you verify the hash of the file is valid (which is the next line in the setup instructions).

Aside from that, it seems to be a php configuration error or you have an outdated version of the openssl extension/lib. Composer might be able to work around that though, once installed. If not then you'll have to resolve it.

**Comment by sger** [comment]
no worries @Seldaek I'm on Mac OS Sierra and something is wrong with the default php version.

**Comment by Hannover86** [comment]
I am having the same problem since I installed macos sierra

**Comment by sger** [comment]
@Hannover86 try with `curl -sS https://getcomposer.org/installer | php`

**Comment by Henriquedrdc** [comment]
After updating to MacOs sierra I had the same problem. Thanks @sger for solving my problem.

**Comment by sger** [comment]
@Seldaek @Henriquedrdc some OpenSSL output from `php -I`

`openssl

OpenSSL support => enabled
OpenSSL Library Version => LibreSSL 2.2.7
OpenSSL Header Version => LibreSSL 2.2.7
Openssl default config => /usr/local/libressl/etc/ssl/openssl.cnf

Directive => Local Value => Master Value
openssl.cafile => no value => no value
openssl.capath => no value => no value`

**Comment by darylknight** [comment]
Mac OS Sierra here too, same error

**Comment by yalegria** [comment]
Same error. Use of http instead of https also solve the problem. Using Sierra and PHP 5.6.24.

**Comment by sab24** [comment]
Same error here. This issue should not have been closed as the documentation on the download page has not been updated to include mentioning that an http alternative is also available in case the certificate verification fails.

**Comment by chishiuanlu** [comment]
Same error. +1 for re-open and get real fix. Thanks.

**Comment by KManiKumarReddy** [comment]
Same error. +1 for re-open and get real fix. Thanks.

**Comment by artwired** [comment]
Awesome!! Thanks sger, http worked for me too :))

**Comment by 1ce7ea** [comment]
For me, my linux was out of date, so php couldn't verify that the certificate was valid.

**Comment by konohanaruto** [comment]
It's right...

**Comment by justmyfreak** [comment]
I got this warning when was using PHP 5.6 on Mac Sierra. Installed PHP 7.1 via `brew` and it's fixed

**Comment by rslonik** [comment]
I only needed to open composer website https://getcomposer.org on the browser, and install went fine. Weird.

**Comment by s2925534** [comment]
run the reinstall of ca-certificates and OpenSSL and it will work

**Comment by bolaghi** [comment]
hi, use this :

php -r "copy('http://getcomposer.org/installer', 'composer-setup.php');"
php composer-setup.php --disable-tls

work for me .

Thanks to all the friends who helped me solve my problems .
