### ISSUE TITLE
Prevent authentication store

### ISSUE THREAD

**Issue by coder-pm** [composer/composer#5689]
Is there anyway to stop storing authentication credentials to disk? I got private repositories protected by basic authentication and they are always stored by vcs cache. Even when using "store-auths" to false, it is always saving login and password to vcs cache (not prompting for password anymore).

I dont want to share login and password and often modules are deployed to customer server.

**Comment by alcohol** [comment]
Can you be more specific? Where did you set this store-auths setting to false? And where are these authentication credentials stored?

**Comment by coder-pm** [comment]
I used: `composer config --global store-auths false`

Credentials to repository are cached by vcs cache here: `~/.composer/cache/vcs/repository.git/config` under url key: `https://username:password@example.com/repository.git`

Is there any way to prevent that? This is huge security problem.

**Comment by alcohol** [comment]
What version of Composer are you using?

**Comment by coder-pm** [comment]
`Composer version 1.2.1 2016-09-12 11:27:19`

**Comment by alcohol** [comment]
Any reason you cannot use SSH keys with your private repository?

**Comment by coder-pm** [comment]
First of all we are hosting repositories in project management application that does not support ssh keys. But main issue is connected with deployment process. Often we are deploying to customer server and we dont have our private user - so ssh keys wont help us (as customer will get this key as well).

**Comment by alcohol** [comment]
For the latter you would use deployment keys which provide read only access.

If you are using username + password, then we have to store them, otherwise the git clone will not be usable for future install/update commands.

**Comment by coder-pm** [comment]
Otherwise it should prompt for login/password. It clearly says:

`store-auths#

What to do after prompting for authentication, one of: true (always store), false (do not store) and "prompt" (ask every time), defaults to "prompt".`

It is not prompting only because of cache, I dont want it to cache my credentials. Either cache should be aware of store-auths or it should be possible to disable vcs cache.

**Comment by alcohol** [comment]
Do you always input username + password through the prompt? As in, your repository definitions in your composer.json do not contain any username and password in their repository url?

**Comment by coder-pm** [comment]
We never put passwords to comopser.json as they are commited to repository. And yes we input username + password during deployment to production server. They are plenty of management systems working like that, where single username + password pair gives access to repositories (and it is aware of user access to project)

**Comment by alcohol** [comment]
Look, I am merely trying to help you out here. You provide very little information for me to work with in your initial post. If you are going to react this defensive to each and every question I ask, then I'll just go back to performing the job that actually pays me a salary.

**Comment by coder-pm** [comment]
We just cant change our current architecture, and from security perspective this is not right to store username + password in plain text by cache mechanism. I am grateful for your attention but you're trying to change our way of deployment and we cannot do that. Thats why im came here and asked if there is any other way to prevent storing credentials by cache, because storing username and password by cache is serious issue. I guess most of people dont even know that when they input login and password.

**Comment by alcohol** [comment]
I'm not trying to change your deployment flow. I'm merely suggesting alternatives that you might not have considered yet (I don't know what you have or have not considered).

I think the username and password get stored because that is the only way we can pass them to the git clone command if I am not mistaken (as part of the clone source url). Since we use the `Process` class, and not `passthru()`, we cannot delegate the auth prompt from the git binary to the user.

Even if you disabled cache, the username and password would still end up in the git clone result in your vendor directory.

The only options I see, are to use SSH keys, or setup a [satis](/composer/satis) instance and install dist versions only.

**Comment by coder-pm** [comment]
We are already using satis and including tagged dependencies in composer.json. How it might change this flow? Isnt satis just keeping reference to repositories (after all composer is cloning from same repository, so it ask for username + password)?

**Comment by Seldaek** [comment]
I believe this would be addressed by https://github.com/composer/composer/pull/3608 which I shamefully still haven't managed to try out. It'd be nice if you could give it a shot see if it helps you, except it's conflicting with master right now.

**Comment by coder-pm** [comment]
I'll try it out and let you know!

**Comment by stof** [comment]
@coder-pm when using Satis, you can make it generate archives, so that composer can download the archive rather than cloning. Generating archives is disabled by default in Satis. you need to enable it in your Satis config file.

**Comment by coder-pm** [comment]
@stof so I can generate archives and include separate authentication layer just for satis repository?

**Comment by Seldaek** [comment]
Closing as there isn't a clear action item here, and it is kinda duplicate of #3608.
