### ISSUE TITLE
bin file is created without execute bit set

### ISSUE THREAD

**Issue by NadiyaS** [composer/composer#5691]
Hi,

when I create my project from composer, my bin file do not have an execute bit set.
I marked this file as bin in composer.json as described [here](https://getcomposer.org/doc/articles/vendor-binaries.md#how-is-it-defined-) and I expect that my file will have the execute bit, instead it has `-rw-r--r--`

My `composer.json`:
```json
{
    "name": "my-vendor/my-project",
    "bin": ["bin/my-project-bin"]
}
```
</details>

Also I tried another way and changed the vendor bin directory where my bin file is located:
```json
{
   "name": "my-vendor/my-project",
    "config": {
        "bin-dir": "bin"
    }
}
```
</details>

As a result I have all bin files from other packages with the execute bit except my bin file.

**Comment by alcohol** [comment]
The permissions are taken from the source repo/package as far as I know. If the bin file in your repository does not have the executable bit set, then it will not have it in the bin dir after install either. On the other hand though, I suppose we could try to enforce that, since it would be what most users expect. The package you are referring to, is it public? If not, could you create a public test repo that replicates and demonstrates this issue?

**Comment by stof** [comment]
@alcohol when using symlinks, chmoding the symlink will also change the permissions on the original file, leaving the repo in a modified state. So this is a bad idea

**Comment by Seldaek** [comment]
Yup we've had that in the past and it didn't help..

**Comment by alcohol** [comment]
I'm not sure this issue should already have been closed. We haven't yet deduced if the source is the problem, or if there is another issue at play here :p

**Comment by Seldaek** [comment]
Thing is in any case we can't make the file executable if it isn't, so it's most likely not in the git repo, or messed up git on windows settings, none of which we can do much about. Plus, we can always reopen.

**Comment by alcohol** [comment]
Fair enough. :)

**Comment by NadiyaS** [comment]
thank you for your response. 
But my expectation was that you try to change the permissions to files which were marked as bin. Especially it seems strange when you set bin-dir to directory with your bin files, and after creation the project all symlinks to other packages' bin files have full permissions except your bin file.
E.g.

- run `composer create-project composer/composer .`
- `ls -la bin` - you will see something like
```
-rw-r--r--   compile 
-rw-r--r--   composer
```
- change composer.json by adding
```json
"config": {
        "bin-dir": "bin"
    }
```
- run composer update
- `ls -la bin` you will see
```
-rw-r--r--  compile
-rw-r--r--  composer
lrwxrwxrwx  jsonlint -> ../vendor/seld/jsonlint/bin/jsonlint
lrwxrwxrwx  phpunit -> ../vendor/phpunit/phpunit/phpunit
lrwxrwxrwx  validate-json -> ../vendor/justinrainbow/json-schema/bin/validate-json

```
Also you wrote 

> The permissions are taken from the source repositry/package as far as I know

what does it mean? How can I store file permissions there? Any link will be appreciated.
Thanks.

**Comment by Seldaek** [comment]
If your package is in git, you can use `git update-index --chmod=+x bin/compile` for example, then a `git status` / `git diff` will show you the change of mode for that file

**Comment by alcohol** [comment]
Weird, if I run:

<details><summary>`composer create-project composer/composer` (click to expand)</summary>
```
 % composer create-project composer/composer                                                                                                                                                                    /tmp
Installing composer/composer (1.2.1)
  - Installing composer/composer (1.2.1)
    Downloading: 100%         

Created project in /tmp/composer
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing composer/ca-bundle (1.0.4)
    Loading from cache

  - Installing composer/semver (1.4.2)
    Loading from cache

  - Installing composer/spdx-licenses (1.1.4)
    Loading from cache

  - Installing justinrainbow/json-schema (2.0.5)
    Loading from cache

  - Installing psr/log (1.0.0)
    Loading from cache

  - Installing seld/cli-prompt (1.0.2)
    Loading from cache

  - Installing seld/jsonlint (1.4.0)
    Loading from cache

  - Installing seld/phar-utils (1.0.1)
    Loading from cache

  - Installing symfony/polyfill-mbstring (v1.2.0)
    Loading from cache

  - Installing symfony/console (v2.8.10)
    Loading from cache

  - Installing symfony/filesystem (v2.8.10)
    Loading from cache

  - Installing symfony/finder (v2.8.10)
    Loading from cache

  - Installing symfony/process (v2.8.10)
    Loading from cache

  - Installing phpdocumentor/reflection-docblock (2.0.4)
    Loading from cache

  - Installing phpunit/php-token-stream (1.4.8)
    Loading from cache

  - Installing symfony/yaml (v2.8.10)
    Loading from cache

  - Installing sebastian/version (1.0.6)
    Loading from cache

  - Installing sebastian/global-state (1.1.1)
    Loading from cache

  - Installing sebastian/recursion-context (1.0.2)
    Loading from cache

  - Installing sebastian/exporter (1.2.2)
    Loading from cache

  - Installing sebastian/environment (1.3.8)
    Loading from cache

  - Installing sebastian/diff (1.4.1)
    Loading from cache

  - Installing sebastian/comparator (1.2.0)
    Loading from cache

  - Installing phpunit/php-text-template (1.2.1)
    Loading from cache

  - Installing doctrine/instantiator (1.0.5)
    Loading from cache

  - Installing phpunit/phpunit-mock-objects (2.3.8)
    Loading from cache

  - Installing phpunit/php-timer (1.0.8)
    Loading from cache

  - Installing phpunit/php-file-iterator (1.4.1)
    Loading from cache

  - Installing phpunit/php-code-coverage (2.2.4)
    Loading from cache

  - Installing phpspec/prophecy (v1.6.1)
    Loading from cache

  - Installing phpunit/phpunit (4.8.27)
    Loading from cache

composer/composer suggests installing ext-zip (Enabling the zip extension allows you to unzip archives)
symfony/console suggests installing symfony/event-dispatcher ()
phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit-mock-objects suggests installing ext-soap (*)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Generating autoload files
```
</details>

I get the following permissions:

```
 % ll composer/bin
total 8.0K
-rwxr-xr-x 1 rob users  966 Sep 12 11:27 compile
-rwxr-xr-x 1 rob users 1.2K Sep 12 11:27 composer
```

Maybe you have some kind of acl permissions set on directories? Different umask?

**Comment by NadiyaS** [comment]
Thank you guys, 
I will solve the problem from my side.
