### ISSUE TITLE
Installation won't work on Windows 7 : error 14090086

### ISSUE THREAD

**Issue by KatharaDarko** [composer/composer#5694]
Hello,

I'm trying to install Composer on Windows 7 and I'm using Php version 5.4.24. I've got this error:
```
The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
```

My info about SSL:
```
OpenSSL support	enabled
OpenSSL Library Version	OpenSSL 0.9.8y 5 Feb 2013
OpenSSL Header Version	OpenSSL 0.9.8y 5 Feb 2013
```

I tried to link the cacert.pem in my php.ini but it didn't change anything. Any idea of what I'm missing ?

Thank you in advance and if I can help you with any further information, don't hesitate.

:confused: Update : I am now able to use composer in command line but I've still meet the same kind of error

```
 [Composer\Downloader\TransportException]
 The "https://packages.zendframework.com/packages.json" file could not be do
 wnloaded: SSL operation failed with code 1. OpenSSL Error messages:
 error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify
 failed
 Failed to enable crypto
 failed to open stream: operation failed

```

**Comment by alcohol** [comment]
Please update your openssl version.

**Comment by KatharaDarko** [comment]
Sorry to bother you but could you indicate me how to upload it ? I tried several ways but none of those worked. I've download and install the last version from slproweb, but I probably don't do it well. 

I know that it's not your job to answer to question like this, but I would really appreciate the help.

**Comment by alcohol** [comment]
I honestly do not know as I have never done development on Windows. I could tell you how to do it on Linux or OSX. Sorry.

**Comment by Seldaek** [comment]
@KatharaDarko the easiest would be to download/install a new version of php, and that would be better too as php5.4 is not maintained for years now.
