### ISSUE TITLE
 [Composer\Exception\NoSslException]

### ISSUE THREAD

**Issue by kakaruchi** [composer/composer#5699]
<details>
<summary> [Composer\Exception\NoSslException]  </summary>

> composer create-project --prefer-dist cakephp/app ameshop
> 
>                                                                                                                            
>   [Composer\Exception\NoSslException]                                                                                      
>   The openssl extension is required for SSL/TLS protection but is not available. If you can not enable the openssl extension, you can disable this error, at your own risk, by setting the 'disable-tls' option to true. 

I use composer globally with version is Composer version 1.2.1 2016-09-12 11:27:19
But when i try to create a project i received the above error. I try to enable open ssh in php.ini but the problem is not solve.

I use MAC OS SIERRA 10.12,PHP 7.0.10,Composer version 1.2.1 .
Please help me.

</details>

**Comment by alcohol** [comment]
Please provide the output of `php -m`.

**Comment by montel007** [comment]
hello i got same problem
