### ISSUE TITLE
Violation segment ( `core 'generated)

### ISSUE THREAD

**Issue by gburu98** [composer/composer#5703]
Error when trying to install laravel, what happens?

Composer: 1.2.1
SO: Ubuntu 16.04 (LTS), 32 bits
![composer](https://cloud.githubusercontent.com/assets/12548796/18769433/7d41857c-8103-11e6-934b-bd4e039ad826.png)

**Comment by alcohol** [comment]
Try running it with `-vvv`, and don't use screenshots but simply copy and paste the contents of your terminal.

**Comment by alcohol** [comment]
https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1626883
