### ISSUE TITLE
[feature request] Version numbers for code deprecation

### ISSUE THREAD

**Issue by nathan-fiscaletti** [composer/composer#5704]
I'd like to propose a feature for deprecating old code that may no longer run. 

For example, say a user is on v0.0.1, in v0.0.2 some code was deprecated so the package no longer works the same, the current version is v0.0.5. 

If a user is updating from anything before v0.0.2, they should be alerted to this change. If they are updating from anything after v0.0.2, there is no need to alert them of the change. 

Something like this in the composer.json file would suit these needs. 

```
"post-install-cmd": {
    "<v0.0.2": {
        "echo function foo is deprecated"
    }
]
```

This way, they would only be alerted if they are updating from a version of the code in which the deprecated code still worked.

**Comment by alcohol** [comment]
This is not the responsibility of a package/dependency manager. Look at how projects such as symfony handle deprecating methods/classes.

Alternatively, you can also have a look at http://symfony.com/blog/paving-the-way-for-symfony-3-with-the-deprecation-detector-tool
