### ISSUE TITLE
ca-certificates.crt segmentation fault

### ISSUE THREAD

**Issue by roonie12** [composer/composer#5705]
When I run any composer command. Debian 8.

PHP 5.6.24-0+deb8u1 (cli) (built: Jul 26 2016 08:17:07) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

I get the following output:
**Segmentation fault**

strace:
`
open("/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 6
fstat(6, {st_mode=S_IFREG|0644, st_size=277194, ...}) = 0
lseek(6, 0, SEEK_CUR)                   = 0
fstat(6, {st_mode=S_IFREG|0644, st_size=277194, ...}) = 0
mmap(NULL, 528384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f7606202000
read(6, "-----BEGIN CERTIFICATE-----\nMIIE"..., 8192) = 8192
read(6, "DVR0TAQH/BAUwAwEB/zBJBgNVHR8EQjB"..., 8192) = 8192
read(6, "Klf9AwpLQwDgYDVR0PAQH/BAQDAgEGMA"..., 8192) = 8192
read(6, "MAZOnTjC3U/dDxGkAV53ijSLdhwZAAIE"..., 8192) = 8192
read(6, "AxHm6VZM\nzfmpTMANmvPMZWnmJXbMWbf"..., 8192) = 8192
read(6, "4IBDwAwggEKAoIBAQDaDuaZ\njc6j40+K"..., 8192) = 8192
read(6, "MkjvN9wfcZnSX9EUi\n3fRc4L9t875lM+"..., 8192) = 8192
read(6, "JlcZaLDQP9nL9bFqyS2+r+eXyt66/3Fs"..., 8192) = 8192
read(6, "I9eNqPPYJayX5HA49LY6tJ07lyZDo6G8"..., 8192) = 8192
read(6, "OMCZEoalHmdkrQYu\nL6lwhceWD3yJZfW"..., 8192) = 8192
read(6, "0W+go/MpvRLHUKKwf4ip\nmXeascClOS5"..., 8192) = 8192
read(6, "ERTIFICATE-----\nMIIDAjCCAmsCEEzH"..., 8192) = 8192
read(6, "w0BAQUFAAOCAQEAERSWwauSCPc/L8my/"..., 8192) = 8192
read(6, "wDwYDVR0TAQH/\nBAUwAwEB/zARBglghk"..., 8192) = 8192
read(6, "RTIFICATE-----\nMIIFuzCCA6OgAwIBA"..., 8192) = 8192
read(6, "FvYDio+nEhEMy/0/ecGc/WLuo89U\nDNE"..., 8192) = 8192
read(6, "EHU1RdZX33inOhmlRaHylDFCfChQ+1iH"..., 8192) = 8192
read(6, "30mJ0jfJUaNSih8hp75mxpZuWW/Bd22Q"..., 8192) = 8192
read(6, "xMBEGCWCGSAGG+EIB\nAQQEAwIABzAfBg"..., 8192) = 8192
read(6, "bgmmkTPiab+ci2hC6X5L8GCcKqKpE+i4"..., 8192) = 8192
read(6, "5mTPj5dUyQ5xJwx0UCAwEAAaNjMGEwHQ"..., 8192) = 8192
read(6, "L9DbWu7PdIxztDhC2gV7+AJ1uP2lsdeu"..., 8192) = 8192
read(6, "aAehsmR0FyYgl9jDIpaq9iVpszLita/Z"..., 8192) = 8192
read(6, "AZCP4bsm+lU/hdezgfl6VzbHvvnpC2Mk"..., 8192) = 8192
read(6, "xDjrSzG+ntKEju/Ykn8sX/oymzsLS28y"..., 8192) = 8192
read(6, "2VydGlmaWNhdGlvbiBBdXRob3JpdHkgR"..., 8192) = 8192
read(6, "SBVRUtBRTEjMCEGA1UECwwaS2FtdSBTZ"..., 8192) = 8192
read(6, "uHfuY5H+QK4R4EA5sSVPvFVtlRkpdr7r"..., 8192) = 8192
read(6, "hucwNhkcV8sEVAbkSdjbCxlnRhLQ2pRd"..., 8192) = 8192
read(6, "QTLX2wRzKm6RAXwhTNS8rhsDdV14Ztk6"..., 8192) = 8192
read(6, "ixjIvirTthnVZil6Xc1bL3McJk6jfW+r"..., 8192) = 8192
read(6, "PhnEFtC+NiWYzKXZUmhH4J/qy\nP5Hgzg"..., 8192) = 8192
read(6, "jmmmVYjzlVYA211QC//G5Xc7UI2/YRYR"..., 8192) = 8192
read(6, "II5KAd+F//0m4rwkYHqOD8heGxI7Gsv\n"..., 8192) = 6858
read(6, "", 8192)                       = 0
read(6, "", 8192)                       = 0
close(6)                                = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
+++ killed by SIGSEGV +++
Segmentation fault
`

[ca-certificates.zip](https://github.com/composer/composer/files/488966/ca-certificates.zip)

**Comment by aboks** [comment]
I also got this problem on Debian 8, directly after OpenSSL was upgraded from `1.0.1t-1+deb8u3` to `1.0.1t-1+deb8u4`.

**Comment by alcohol** [comment]
That is more likely a PHP issue than a Composer issue. I don't see what we can do here for you.

**Comment by alcohol** [comment]
https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1626883
