### ISSUE TITLE
Crash on Ubuntu/16.04.2 i386 probably by network

### ISSUE THREAD

**Issue by Vovan-VE** [composer/composer#5706]
My `composer.json`:
(absent ever)

Output of `composer diagnose -vvv`:
<details>
<summary>CLICK TO EXPAND</summary>
```
Failed to initialize global composer: Composer could not find the config file: /home/<user>/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 1.2.1 (2016-09-12 11:27:19) with PHP 7.0.8-0ubuntu0.16.04.2 on Linux / 4.4.0-38-generic
Segmentation fault (core dumped)
```
</details>

When I run this command:
```
composer search <whatever>
```

I get the following output:
```
Segmentation fault (core dumped)
```

And I expected this to happen:
(no crash)

After that I installed xdebug to provide a trace: https://gist.github.com/Vovan-VE/b8166502c4408f866298dc65e4896f93

Looks like the problem born just now after Ubuntu upgrade. Some days ago everything was fine.

On **x64** everithing the same (Composer, PHP and Ubuntu) also **forks fine**.

**Comment by Vovan-VE** [comment]
Looks like I'm late. There also #5705.

**Comment by stof** [comment]
Segmentation fault are bugs at the C level, which means in PHP or one of its extension. So you should report it to PHP

**Comment by Vovan-VE** [comment]
Already reported: https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1626883

**Comment by alcohol** [comment]
Sorry, closing this as there is nothing we can do here.
