### ISSUE TITLE
Documentation incorrect and misleading for private repos.

### ISSUE THREAD

**Issue by kwhat** [composer/composer#5710]
"The only requirement is the installation of SSH keys for a git client."  from https://github.com/composer/composer/commit/656996335877cddf4c8cce52bfbec743b16c8e2a#diff-ffea9ab37002bc5aecff51b54d97c47aR208 is untrue and misleading.  **You MUST use an access token UNLESS you set `no-api` key to `true`!**

**Comment by alcohol** [comment]
Please provide proof. I will re-open when you do.
