### ISSUE TITLE
multi-lang project name support

### ISSUE THREAD

**Issue by yarcowang** [composer/composer#5711]
I'm ok for it does't support Chinese...as a non-English, my words are very limited. And i'm learning Spanish. I'm happy that i can name both `catalog` and `catálogo` (it is easy than to know another english word for the same meaning). And even php itself support multi-lang class name as in below:
```
php -a
Interactive shell

php > class catálogo {}
php > $o = new catálogo;
php > var_dump($o);
php shell code:1:
class catálogo#1 (0) {
}
```
Don't understand why composer itself does't support multi-lang project name.

### Details

When I run this command under the directory of `catálogo`:
```
catálogo$ composer init
```

I get the following output:
<details>
<summary>CLICK TO EXPAND</summary>
```
This command will guide you through creating your composer.json config.

Package name (<vendor>/<name>) [yarco/cat?logo]: 
 The package name yarco/cat?logo is invalid, it should be lowercase and have a vendor name, a forward slash, and a package name, matching: [a-z0-9_.-]+/[a-z0-9_.-]+ 
```
</details>

And I expected this to happen:
I could name the package in Spanish.

**Comment by alcohol** [comment]
Just write it as `catalogo` then.
