### ISSUE TITLE
Feature Request - bump version with `composer version`

### ISSUE THREAD

**Issue by fboutin-pmc** [composer/composer#5719]
Hi there,
It would be VERY appreciated if we could bump a component's version - like we do with any other package managers like node and bower - with something like `composer version MAJOR | MINOR | PATCH | X.Y.Z`.

The CLI would modify the `version` field in `composer.json` file, then `git commit` and `git tag` automatically.

Easy, quick, and less error prone.

Thank you!

Sources,
https://bower.io/docs/api/#version
https://docs.npmjs.com/cli/version

**Comment by fboutin-pmc** [comment]
I don't know why, but I definitely searched first before posting but I never saw this post,
https://github.com/composer/composer/issues/4939

The feature was scrapped for no good reason, if you ask me. Now I need to rely on a seperate 3rd party.
https://github.com/vutran/composer-version

**Comment by alcohol** [comment]
To re-iterate; the feature was scrapped because if you are using git tags (which 99% of our users are), then you should **not** specify any version in your composer.json. Emphasis for clarity on the **not** part.

**Comment by fboutin-pmc** [comment]
I don't agree. I just tagged a commit with a new version, I then modified my `require` statement in `composer.json` file and then I `composer install`.

```
Loading composer repositories with package information                                                                                                                                                         Updating dependencies (including require-dev)         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package MY_PACKAGE NEW_VERSION exists as MY_PACKAGE[all the composer.json versions found] but these are rejected by your constraint.
```

**Comment by alcohol** [comment]
That changes nothing.

**Comment by faboulaws** [comment]
Maybe there is something that I don't get. When using `npm`, publishing a package is using the version defined in the pakage.json file. Using git tags in my opinion is a side effect of git being popular.  What if the owner of a package is not using git? Maybe there is something different in the composer ecosystem that I am missing?

**Comment by Seldaek** [comment]
@faboulaws we support other VCSs, not only git. For other cases where code does not live in a versioned repo, like with composer's path repository or artifact repository, then specifying the version field can be useful, but this is very much the exception, not the rule.

**Comment by stof** [comment]
@faboulaws npm works by publishing releases (with all the code) to the registry. Composer integrates with various VCS systems directly. That's a major difference between both systems (and that's why you can install versions corresponding to branches in Composer, with metadata coming from packagist.org, while there is no equivalent in npm)
