### ISSUE TITLE
global installed composer, but no global cache dir?

### ISSUE THREAD

**Issue by christian-weiss** [composer/composer#5722]
When composer is installed globally then superuser permissions are required to run self-update.
(to update /usr/local/bin/composer)

To self-update composer as a non-root user (e.g. jenkins) you need to run it with e.g.
sudo composer self-update --no-progress

A side-effect of self-update is, it initializes the composer cache.
At the moment (composer 1.3-dev (012fb18...) it installes the cache to the home dir of the user (e.g. /home/jenkins/.composer). Combined with sudo this leads to create a file strukture under /home/jenkins.composer/ and by owned by root.

This leads to permission problems for sub-sequent composer runs (cache will not be used). E.g.
composer install

Composer should recorgnize that it is installed globally and it should not init the cache at all (or init it in user home (as by now), but with e.g. jenkins as owner). 

From my point of view "composer self-update" should not honor the project-specific composer.json / composer.lock when composer is installed globally. Even for locally installed composer i think it should not honor the project-specific composer.json / composer.lock.
Due to the fact that this "init" just create some dirs and some .htaccess files it is not a full fledged initialization the init should be skipped (we do not need it).

**Comment by alcohol** [comment]
While I understand the issue you describe, your proposed solution does not make a lot of sense. From a composer binary perspective, there is no global or local install. There is just the binary. It is run by a user (be it your user, or root). Composer even issues a warning when being run by root/through sudo. The consequences of running composer as root are for you to deal with, not us.

**Comment by christian-weiss** [comment]
Direct from the manual:
https://getcomposer.org/doc/00-intro.md#globally
> Note: If the above fails due to permissions, you may need to run it again with sudo.

As the manual recommends to use sudo for installation - implies a sudo is recommended for updates (self-update), too. 

Please at least update the wiki to:
a) not recommend to install it globally using sudo OR
b) put a note that "self-update" can not be performed by every user (not supported)

I recommend to drop the "cache dir init process" from "self-update". This would increase the user experience.

**Comment by alcohol** [comment]
That's globally speaking from a user/OS context, not Composer context.

**Comment by alcohol** [comment]
The cache dir is necessary because this is where we store previous version for `--rollback` support.

**Comment by christian-weiss** [comment]
When executing it with sudo, composer will be executed as user root. So why is composer using the homedir of jenkins (~${SUDO_USER} instead of homedir of root (~)? Sounds like composer is leaving user context. A bug?

**Comment by naderman** [comment]
Depending on your system configuration sudo does not replace the HOME environment variable. If you want the directory to be created in /root you need to run `sudo -h composer`. This is not an issue with composer.
