### ISSUE TITLE
How to edit hashbang safely?

### ISSUE THREAD

**Issue by nimasdj** [composer/composer#5729]
When I open /usr/local/bin/composer to change the hashbang to:

    #!/opt/php56/bin/php

to run it as php 5.6 as my default php is 5.4, I get invalid signature error and I get this because binary file is corrupted after edit/save? How to edit hashbang saftely to not corrupt the file?

**Comment by stof** [comment]
editing the phar will indeed make it invalid. The only way would be to edit the composer source and rebuild the phar from the updated source.

It is much simpler to run composer without relying on the shebang instead:

```bash
/opt/php56/bin/php /usr/local/bin/composer install
```

or if you don't want to hardcode the path to composer:


```bash
/opt/php56/bin/php `which composer` install
```

You can even use a bash alias doing it for you

**Comment by nimasdj** [comment]
Many thanks. @stof  How to use a bash alias?
