### ISSUE TITLE
optimizing autoloader

### ISSUE THREAD

**Issue by nimasdj** [composer/composer#5730]
After optimizing autoloader, isn't it better to delete autoload_psr4.php to speed up autoloader as this file seems to be just something duplicate?

**Comment by alcohol** [comment]
It can still be used as a fallback, if you do not set `classmap-authoritative`.

**Comment by nimasdj** [comment]
So for maximum performance better to optimize with classmap-authoritative then delete autoload_psr4.php? @alcohol

**Comment by alcohol** [comment]
I wouldn't delete anything. It has no impact just being there.

**Comment by nimasdj** [comment]
Ok. Thanks for advise. Just turn on classmap authoritative for maximum performance without deleting.... @alcohol

**Comment by alcohol** [comment]
You're welcome.
