### ISSUE TITLE
composer doesn't work behind proxy (php56u + centos 7)

### ISSUE THREAD

**Issue by armando-basile** [composer/composer#5732]
Hi all,
i trying to use composer version 1.2.0 2016-07-19 01:28:52 on my CentOS 7 with Php56u behind proxy but i receive always certificate verify error.
`# composer diag`

`FAIL
[Composer\Downloader\TransportException] Invalid credentials for 'http://packagist.org/packages.json', aborting.
Checking https connectivity to packagist: FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
failed to open stream: Cannot connect to HTTPS server through proxy
`
how could i fix it ?

thanks

**Comment by alcohol** [comment]
Did you have a look at https://getcomposer.org/doc/03-cli.md#http-proxy-or-http-proxy ?

**Comment by armando-basile** [comment]
Hi alcohol,
yes, i have environment vars configured, i tryed also to force with
`git config --global http.proxy ... `
`git config --global https.proxy ...`

without success

**Comment by alcohol** [comment]
If you configured them correctly, then it should work.

**Comment by armando-basile** [comment]
yes, i needed to download rootca.pem and updated 
curl.cainfo and openssl.cafile into php.ini
