### ISSUE TITLE
Possible improvements on Rule

### ISSUE THREAD

**Issue by Toflar** [composer/composer#5734]
Hey guys.

While doing some blackfire analysis I noticed that `unpack` gets quite a lot of calls. This is due to `Rule::getHash()` to increase the speed of comparisons. But I was wondering why we even need to use `md5()` and `unpack()` there because afaik the literals are always an array of ids that is sorted in `Rule::__construct()`. Is there any reason why we cannot go for this:

```diff
public function getHash()
{
-    $data = unpack('ihash', md5(implode(',', $this->literals), true));
-
-    return $data['hash'];
+    return implode(',', $this->literals);
}
```

?

Moreover, I noticed that the commit https://github.com/composer/composer/commit/c7e1f49e783f92960441b88fe23bc1e933797daa removed "hash caching" although in `RuleSet` the method `getHash()` is called multiple times (so maybe still worth caching?).

**Comment by alcohol** [comment]
I think @naderman is in the best position to answer this question.

**Comment by naderman** [comment]
@Toflar The reason I removed the property from the object was to save memory. The hashes get stored as keys in the ruleset anyway, it's more space efficient to use a short hash there than the full string. I don't believe getHash() is called more than once on any individual rule - but I may be wrong on that, so worth looking into that again. There can be hundreds of thousands of rule objects, which means that every bit of data we can save inside a rule ends up making significant improvements to the overall memory footprint. The small overhead of calling md5 and unpack is countered by a large saving of space. Feel free to benchmark this again, the pull request that changed this at the time contains my measurements: https://github.com/composer/composer/pull/4234

**Comment by Toflar** [comment]
First of all: Thanks for taking the time!

> but I may be wrong on that, so worth looking into that again.

1. https://github.com/composer/composer/blob/master/src/Composer/DependencyResolver/RuleSet.php#L71
2. https://github.com/composer/composer/blob/master/src/Composer/DependencyResolver/RuleSet.php#L140


> There can be hundreds of thousands of rule objects, which means that every bit of data we can save inside a rule ends up making significant improvements to the overall memory footprin

I know. My test case produces over 1 million conflict rules :-S 

>  Feel free to benchmark this again, the pull request that changed this at the time contains my measurements: #4234

I did. I cannot see a lot of difference in both, speed or memory. The only thing we can do is reduce the number of rules but I have no freaking idea about how to do that :D

**Comment by naderman** [comment]
> 1. https://github.com/composer/composer/blob/master/src/Composer/DependencyResolver/RuleSet.php#L71
> 2. https://github.com/composer/composer/blob/master/src/Composer/DependencyResolver/RuleSet.php#L140

Ok I think the only places `add()` is called are https://github.com/composer/composer/blob/master/src/Composer/DependencyResolver/RuleSetGenerator.php#L144 and https://github.com/composer/composer/blob/master/src/Composer/DependencyResolver/Solver.php#L359 the former uses `containsEquals()` before calling `add()`, so I think one can reduce this to a single function in `RuleSet` and only ever call `getHash()` once on the rule, that should cut down at least a few unnecessary calls. Would you like to make a PR for this?

> I did. I cannot see a lot of difference in both, speed or memory. The only thing we can do is reduce the number of rules but I have no freaking idea about how to do that :D
I've done that a few times, and there are some more ideas, but they require rather large refactorings, so maybe in Composer v2 ;-)

**Comment by Toflar** [comment]
> Would you like to make a PR for this?

Sure!
https://github.com/composer/composer/pull/5738
