### ISSUE TITLE
Use alternative rules storage to work around memory issues

### ISSUE THREAD

**Issue by Toflar** [composer/composer#5735]
This memory stuff just keeps me awake at night so I have to start the discussion again :-D
My current test case uses up 1.5 GB of memory. This is - as we all know - due to about 1.5 million rules that are being created and kept in memory.

I don't really care about composer using up that much memory on my local machine but sometimes I like to play around with things and 1.5 GB of RAM is just too much for geek stuff like the rasperry pi etc.
I would love if there was a way I could trade memory for execution time. Right now I cannot get it to work at all. If it took 20 seconds longer because it stored the rules somewhere else than in memory, I wouldn't really mind. At least I could get it to work :-)

So I was wondering if we could store the rules - that are held in the `RuleSet` as a regular array now - within a class (implementing `ArrayAccess`) instead which stores and retrieves the rules from sqlite via PDO. It would be way more inefficient, yes. But again, I'd rather spend 20 seconds more drinking coffee than not having composer work at all because of memory limits.

I'd be willing to give it a try but I wanted to know if you think it's even worth trying and get some feedback here. What do you think about the overall idea? Do you even think it might work? Alternative ideas? Do you think it's okay to serialize the `Rule` instances? Do you think it's feasible without breaking BC?

Of course it should end up as an optional feature (like `composer update --save-memory` or rather a config param in the `composer.json` because you're unlikely going to change the setting with every update as complexity is unlikely to drop and you don't just get more memory on the machine between updates :-)).

I know this is a crutch and we should work on reducing the overall number of rules but I don't know much about the algorithm and this proposal does not mean we cannot do this anymore. It's just maybe the one thing I, personally, could work on right now and try to contribute...

**Comment by staabm** [comment]
couldnt you configure a big enough swap file and the operation system should do what you are after?

**Comment by Toflar** [comment]
If one does have control about this stuff, yes. If you try to run it somewhere where your rights are restricted, you don't :)

**Comment by stof** [comment]
The RuleSet is also very sensitive to time. It is used by the SAT solver, meaning accesses can be done millions of time during the resolution of dependencies. Making a DB query each time would likely be slow as hell.
Thus, it will likely cause issues if we return 2 different Rule instances for subsequent access, meaning we would still have to keep a map in memory, defeating this point. I don't think it is possible to remove this memory map without breaking the solver.

My question is why you need to be able to run an update on a rasperry pi though. ``composer update`` is a development-time command. Anything else should be installing from a lock file (which consumes a reasonable amount of memory, unless you have millions of dependencies in your project)

**Comment by Toflar** [comment]
That rasperry pi thing was only an example. Don't focus on it. There are people executing a `composer update` on a regular webserver for example.

> My question is why you need to be able to run an update on a rasperry pi though. composer update is a development-time command. Anything else should be installing from a lock file (which consumes a reasonable amount of memory, unless you have millions of dependencies in your project)

Yes, I know it's only about `composer update`, I didn't mention anything else. I don't want to discuss the development-time stuff. That has been done a lot of times. I know it's not correct to e.g. execute a `composer update` on a web server. I never do that either. But go google for "composer memory" and you find enough people that are trying to do it and complaining about it. Whether their use case is supported or not, doesn't really matter (even if it should) because to me it seems like that memory stuff harms the image of composer and that's what matters to me. I don't need this workaround. I'm just trying to find ways to make sure composer gets the appreciation it deserves.
See where I'm coming from?

> Making a DB query each time would likely be slow as hell.

Jup. We'll have to find out how much slower it is :-)

> Thus, it will likely cause issues if we return 2 different Rule instances for subsequent access, meaning we would still have to keep a map in memory, defeating this point. I don't think it is possible to remove this memory map without breaking the solver.

I didn't get this. Can you elaborate a bit more maybe?

Also, if there was a way to exchange the `Solver` or `RuleSetGenerator` class(es) via a composer plugin, I could try it without affecting anybody else :-)

**Comment by stof** [comment]
@Toflar replacing the solver in a plugin will probably not happen. the solver is the heart of composer. Any replacement should be sure to implement exactly the same algorithm, otherwise it would break things.

> I didn't get this. Can you elaborate a bit more maybe?

Rules are mutable objects. So it makes it very hard to store them in a DB inside the RuleSet, as 2 successive access to the RuleSet MUST return the same instance of Rule (otherwise, you will have 2 independent mutable state, while we should have a single state)

**Comment by Toflar** [comment]
> @Toflar replacing the solver in a plugin will probably not happen. the solver is the heart of composer. Any replacement should be sure to implement exactly the same algorithm, otherwise it would break things.

I understand. I targeted the `Solver` because the `RuleSet` is created within the `Solver`. What about properly injecting the `RuleSet` into the `Solver` and make it possible to exchange the `RuleSet` via event before the `Solver` instance is created? I could do a PR for this.

> Rules are mutable objects. So it makes it very hard to store them in a DB inside the RuleSet, as 2 successive access to the RuleSet MUST return the same instance of Rule (otherwise, you will have 2 independent mutable state, while we should have a single state)

Yeah, we'd need to `serialize()` and `unserialize()` for every access. This will take like forever but I'd still like to give it a try :-)

**Comment by stof** [comment]
> Yeah, we'd need to serialize() and unserialize() for every access. This will take like forever but I'd still like to give it a try :-)

No, because unserialize for the new access will give you a **new** instance having the old serialized state, which will break things. It will not let you reuse the same instance. the only way to reuse the same instance is having a way to access it, i.e. keeping a reference to it. This means doing what is done today.

And btw, the RuleSet is not notified when a Rule is mutated, so it cannot serialize the new state.

**Comment by Toflar** [comment]
Obviously, yes. I just didn't see why this should be a problem until I searched for `spl_object_hash()` right now. Didn't notice this is being used until now. Hmmm :-(
You mean this stuff, right:

```php
$this->learnedWhy[spl_object_hash($newRule)] = $why;
```

**Comment by Toflar** [comment]
Can't we use 

```php
$this->learnedWhy[$newRule->getHash()] = $why;
```

instead?

**Comment by stof** [comment]
@Toflar this is not the only issue. Note how we are **mutating** rules inside the solver. If each access gives you a different instance, they will be independent and so a mutation will not takes effect properly.

Btw, ``Rule->getHash`` usage was reduced as much as possible, because of the impact on performance. Computing it on the fly as done today is costly (but currently, we use it only twice per rule, and we could refactor this) and storing it in a property (as done before) increases the memory footprint of rules (and you are trying to reduce it). this is why it is **no** used as key in this array (``spl_object_hash`` is fast because PHP does not have to compute anything, as the return value is related to the internal key of the object)

**Comment by Toflar** [comment]
Ah, now I understand. Cannot brain today. Sigh :-(
