### ISSUE TITLE
Composer not reading tagged composer.json on update?

### ISSUE THREAD

**Issue by NoScopie** [composer/composer#5736]
Hi there,

I had some issues with updating a bundle to a newer version.

Our project had installed bundle:

```json
    "appstrakt/php_mailerbundle": "1.0.*",
```

Now this bundle had some major improvements and since the 2.0.0 release the name in the composer.json changed from "appstrakt/php_mailerbundle" to "november_five/php_mailerbundle".

For an older project I had to do a hotfix on the 1.0.* branch. After fixing the bug I tagged it as version 1.0.6.

Now if I ran:

```json
    composer require appstrakt/php_mailerbundle:"1.0.6"
```

Composer told me that the package could not be found. I had to run:

```json
    composer require november_five/php_mailerbundle:"1.0.6"
```

So although the composer.json file on the 1.0.6 tag still has the old "appstrakt/php_mailerbundle" name I still need to use the newer "november_five/php_mailerbundle" name.

Does composer only read the latest composer.json by any chance?

**Comment by alcohol** [comment]
A repository can only contain 1 package. Packagist retrieves this information from the **main** branch, which on Github often defaults to master.

**Comment by NoScopie** [comment]
So once the name is updated you can't use the old one anymore? Not even for the older tags that still have that name?

**Comment by alcohol** [comment]
As far as I know, no. That is why name changes are not recommended.

See also [issuecomment-130599468](https://github.com/composer/packagist/issues/47#issuecomment-130599468).
