### ISSUE TITLE
macOS 10.12 no ansi

### ISSUE THREAD

**Issue by peshi** [composer/composer#5741]
After update to macOS 10.12 Sierra ansi colors are gone.
However if I run composer with --ansi they are working as expected.

**Comment by stof** [comment]
On Unix systems, you need to PHP ``posix`` extension to have color support autodetection. Make sure it is enabled in your PHP (use ``php -m`` and check whether it appears in the list). If it is not enabled, install this extension

**Comment by peshi** [comment]
Thanks, but it's available under php modules.

**Comment by peshi** [comment]
Closing, no ansi colors related to the following change in: https://github.com/Homebrew/homebrew-php/issues/3590

**Comment by alcohol** [comment]
This is not a Composer issue.
