### ISSUE TITLE
Regarding autload_dev

### ISSUE THREAD

**Issue by nikhil-dhiman** [composer/composer#5742]
As i know autoload_dev will only work for root package.
But i want that for child as well, since we have multiple repository and they are so much interlinked. We have to have parent repo manages all other repos. 

We have a tool that runs our test cases like yours whenever there is commit in git repo. But it fetches the parent repo and then run composer update and then runs test cases. In this case test case fails because autoload_dev fails for child repos.

I recently created a pull request while was marked closed because of test case fails. 
https://github.com/composer/composer/pull/5737 [Enable only for those which are mentioned in root package]

or we could have something like composer --enable-autoloaddev-for-child  update [Enable for all]

Please suggest a better way to do it.

**Comment by Seldaek** [comment]
If you want to build multiple projects like that, I would suggest you either define the autoload-dev in the root package (it can contain paths in `vendor/.../`) or that you run composer install in every project independently and then run the tests in each, this isn't so hard to script for a build process. We will not change this in Composer, dev stuff is only for the root package and this shouldn't change I think. It's a clear simple rule.

**Comment by nikhil-dhiman** [comment]
Yes @Seldaek  , no doubt in that. What you are saying i completely agree with that.
Only Root package has the privilege of dev stuff. My code is also aligning with that.

What i am saying is rather than specifying autoload-dev[child package] in root package. We should have other option in package to specify which child autoload-dev should work

ROOT PACKAGE COMPOSER.JSON[ABC is some child package]
```
"autoload-dev": {
      "psr-4": {
        "ABC\\test\\": "ABC/test/"
      }
    }

```
My Suggestion in ROOT PACKAGE
```
"enable-autoload-dev-for-child": [
        "ABC"
    ]

```
Where ABC is name of repository

This will prevent duplicacy of defining autoload-dev at root package/child package.

In my case both will work[When package is run under child or run himself as root].

**Comment by Seldaek** [comment]
I understand your proposal but I don't agree it's a good idea to bring this in sorry. It adds cruft for something that I don't think is necessary.

**Comment by nikhil-dhiman** [comment]
thanks @Seldaek  .. I understand .. 

Hoping it will come in nice_to_have tag some day. . :)
