### ISSUE TITLE
Local dependency not found

### ISSUE THREAD

**Issue by VasileGabriel** [composer/composer#5750]
Given 3 packages A, B and C, with A depending on B and B depending on C, and B and C beeing local git repositories.

Running "composer install" while in package B finds and brings package C as dependency, however running "composer install" in A results in package C not found. 

I'm not sure if this is a bug or it's supposed to work like that.
For anyone who wants to try I have a test case in the attached archive.
[composer-test.zip](https://github.com/composer/composer/files/508084/composer-test.zip)

**Comment by alcohol** [comment]
"[repositories](https://getcomposer.org/doc/04-schema.md#repositories)" is root only.

https://getcomposer.org/doc/faqs/why-can%27t-composer-load-repositories-recursively.md

**Comment by stof** [comment]
``repositories`` is a root-only key (reasons are explained in https://getcomposer.org/doc/faqs/why-can%27t-composer-load-repositories-recursively.md)
So if A does not know where C is, it won't be able to resolve it

**Comment by VasileGabriel** [comment]
Ok, this makes sense. Thanks!
