### ISSUE TITLE
Transition "composer/composer" Docker image on Docker Hub to Composer maintainers

### ISSUE THREAD

**Issue by eugene-dounar** [composer/composer#5751]
Hi folks!
Some time ago I was added to maintainers of composer/composer image on Docker Hub. Few days ago I got an email from Docker about transition of this image to Composer maintainers. 

As of my understanding image maintainers are ok with the transition. But as there are people using the image we need to work out some transition plan.

**Comment by alcohol** [comment]
We do not plan on moving the source repository, nor will the existing image be ejected from the composer organization. It is purely an administrative change (ownership of the organization).

**Comment by pmoust** [comment]
that's good to know.

The number of pulls on the images under the dockerhub org suggests that if a transition is to take place it needs to be smooth or else it will break CI/dev workflows for a lot of people.

(Speaking as someone that is^H^Hwas one of the Docker Hub maintainers, as well as someone that relies on those images to perform CI builds).

**Comment by alcohol** [comment]
The only changes I would like to implement asap is setting up some webhooks so that builds for the 'latest' tags are triggered whenever we merge changes into the master and/or 1.2 branch. Cause I noticed that the latest tags are lagging behind rather significantly.

**Comment by stof** [comment]
Well, it would make sense to move the source repository to the github organization, if we can update the docker hub to look for automated builds in the new repo. This should not require changing the image name in the hub (unless the docker community decided not to support updating the location of the source repo)

**Comment by alcohol** [comment]
I know Seldaek is a bit reluctant regarding moving the Github repository into the Composer organization. I'm neutral, though I personally think it could benefit from the move (increased visibility perhaps/hopefully could lead to more contributors?). It would require some planning though (though it's a fairly simple process).

**Comment by pmoust** [comment]
A webhook triggered per push event can be easily added and is much needed.
👍

**Comment by Seldaek** [comment]
Done here I believe?
