### ISSUE TITLE
Make composer remove case insensitive

### ISSUE THREAD

**Issue by kirkmadera** [composer/composer#5754]
My `composer.json`:
<details>
<summary>CLICK TO EXPAND</summary>
```json
{
    "minimum-stability": "dev",
    "prefer-stable": true,
    "repositories": [
        {
            "type": "composer",
            "url": "http://packages.firegento.com"
        }
    ],
    "require": {
        "magento-hackathon/magento-composer-installer": "^3.0.7",
        "aoepeople/Aoe_Scheduler": "^1.0",
    },
    "extra": {
        "magento-root-dir": "htdocs",
        "magento-deploystrategy": "symlink",
        "auto-append-gitignore": true,
        "magento-force": true
    }
}
```
</details>

Note, the package name should really be aoepeople/aoe_scheduler based on the [package's composer.json](https://github.com/AOEpeople/Aoe_Scheduler/blob/master/composer.json). But, this is how we inherited code from a previous build.

We have a script that forcefully removes all composer installed packages and then reinstalls them. This is needed when things go awry sometimes with the [magento-hackathon/magento-composer-installer](https://github.com/magento-hackathon/magento-composer-installer) or for some other reason.

Our script runs a `composer info`, then uses the output of that and creates a list of packages to pass to `composer remove $myPackages --no-interaction`. This works great, except that `composer remove` checks composer.json in a case sensitive way.

In the case above, `composer remove` misses aoepeople/aoe_scheduler because `composer info` reports it as aoepeople/aoe_scheduler, but it's written as aoepeople/Aoe_Scheduler in composer.json. Then, upon attempt to reinstall the module, it fails because symlinks are already in place. 
 
I know that the composer.json has an invalid package name in this case, but I would argue that an attempt should be made to treat package names case insensitively. (This may be a bigger existing discussion). At least for `composer remove`, I think it would be helpful to make the check for its existence in composer.json case insensitive.

**Comment by alcohol** [comment]
Package names are actually case insensitive as far as I know, so this seems like a very valid request to me. It is probably just not a common use-case, hence why nobody noticed it before or asked questions about it.
