### ISSUE TITLE
Integration with Bitbucket, Gitlab for create-project

### ISSUE THREAD

**Issue by henrypenny** [composer/composer#5756]
I'd really like to be able to set up some private boilerplate projects and have my team use them like this:

`composer create-project my-team/some-project new-project --repository https://gitlab.com/my-team/some-project.git`

I can't seem to get composer to work in this way on either bitbucket or gitlab. Since composer already supports requiring dependencies from private repos, surely it would be simple to allow using `create-project` in a similar manner.

I've looked everywhere for some guidance on how to do this. I can only assume it's currently not supported.

Is this supported or is it planned for the future?

Thanks.

**Comment by alcohol** [comment]
Private repositories require authentication in some form, you will have to provide that.

> I can't seem to get composer to work in this way

We cannot help you if you do not actually tell us what is going wrong (errors, output, etc, the issue template makes this quite clear). Reading minds is still something that only occurs in movies.

**Comment by henrypenny** [comment]
When I run this command:
```
composer create-project --repository-url https://gitlab.com/supplyltd/test-composer.git test-composer tc
```

I get the following output:
<details>
<summary>CLICK TO EXPAND</summary>
```
  [Seld\JsonLint\ParsingException]                                                            
  "https://gitlab.com/supplyltd/test-composer.git/packages.json" does not contain valid JSON  
  Parse error on line 1:                                                                      
  <!DOCTYPE html><htm                                                                         
  ^                                                                                           
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['                      
                                                                                              
```
</details>

And I expected this to happen:

I want to be able to create a new project from a repository within gitlab (or bitbucket). I know I'm linking to a repository not a list of repositories. But I've tried a bunch of other things and had no luck. 

Is there a known way to achieve this?

Note: I am authenticating via a public key.

**Comment by henrypenny** [comment]
My thinking is that either:

1) There's a way to get a list of packages from gitlab and/or bitbucket, but I haven't found it.
or
2) It would be a great feature to connect straight to a single repository. So:

`create-project --repository-url https://gitlab.com/supplyltd/test-composer.git test-composer tc`

... would be smart enough to look for a `packages.json` or determine that it was looking at a single repo.


`

**Comment by alcohol** [comment]
Just like I explained here, for private repos you need a private token. An ssh key is not going to work.

https://github.com/composer/composer/issues/5763#issuecomment-251902793

**Comment by Seldaek** [comment]
Closing issue as it has been quiet for a long time and there is no clear next step we can take.
