### ISSUE TITLE
documentation: vendor binaries to mention need for `chmod 777`

### ISSUE THREAD

**Issue by shadiakiki1986** [composer/composer#5757]
Summary:
It seems that `composer update` changes the execution bits on vendor binary files, but this is not mentioned in the [documentation](https://getcomposer.org/doc/articles/vendor-binaries.md).

Scenario:
* Package A defines a vendor binary file that doesn't have `chmod 777`
* Package B depends on A
* run `composer install` in package B
* make any update to package A
* run `composer update` in package B

Result
* prompt saying 
```
    The package has modified files:
    M bin/sicReport.php
    Discard changes [y,n,v,d,s,?]? 
```

Workaround
* add `chmod 777` to binary file in package A and commit
* run `composer update` in B
* the prompt is not triggered

**Comment by alcohol** [comment]
Composer does not change execution bits.

**Comment by cs278** [comment]
> Composer does not change execution bits.

https://github.com/composer/composer/blob/23d2e5600a91746fe4c2e19621431eeac21f174e/src/Composer/Installer/BinaryInstaller.php#L93

**Comment by alcohol** [comment]
Those are the "installed" binaries, not the source files. The "installed" binaries should not be committed in your vcs. The above message you displayed regarding "modified files" should never trigger for these.

**Comment by stof** [comment]
@alcohol when the installed binaries is a symlink, the chmod applies to the original file.

anyway, a file marked as a composer bin script should indeed be executable to avoid issues

**Comment by alcohol** [comment]
We should use `chmod -h` then. Not sure if that can be done using php's `chmod()` though :/

**Comment by stof** [comment]
``chmod -h`` ? Running ``man chmod`` does not show me such option, and it tells me this instead:

```
       chmod never changes the permissions of symbolic links; the chmod system
       call cannot change their permissions.  This is not a problem since  the
       permissions  of  symbolic links are never used.  However, for each sym‐
       bolic link listed on the command line, chmod changes the permissions of
       the pointed-to file.  In contrast, chmod ignores symbolic links encoun‐
       tered during recursive directory traversals.
```
