### ISSUE TITLE
Unable to add extra installer paths through command line.

### ISSUE THREAD

**Issue by tomasnagy** [composer/composer#5759]
We've been trying to add extra installer-paths to composer.json through command line.
This to automate our internal project creation workflow. 

When executing the following the value gets added as  a string.
`composer config extra.installer-paths.web/modules/custom/{\$name} type:drupal-module-custom`

It creates:

```
"extra": {
        "installer-paths": {
            ...
            "web/themes/contrib/{$name}": "type:drupal-theme",
}
```

But it should be:

```
"extra": {
        "installer-paths": {
            ...
            "web/themes/contrib/{$name}": ["type:drupal-theme"],
}
```

But for installer paths it has to be added as an array.
Documentation for this seems to be limited.

Is this currently not supported or is there another way to achieve the same result?

**Comment by alcohol** [comment]
Judging by the implementation, this is currently not supported.
https://github.com/composer/composer/blob/master/src/Composer/Command/ConfigCommand.php#L494-L501

Why does it have to be an array btw? Can't whatever method receives this simply cast it to an array if it receives a string?

**Comment by tomasnagy** [comment]
Thanks for the quick response!

What if you want to target multiple tags on the same key, you wouldn't be able to with the current implementation.

For example when thinking about installing package from multiple (external) repo's inside the same folder.

**Comment by Seldaek** [comment]
This is something we can't easily support via CLI unless we add an --array flag or somesuch but that'll maybe make the code quite messy for what value it brings.. Anyway we can keep the issue open for now I guess.

**Comment by sbuzonas** [comment]
There is an `--add` flag for git config, but they aren't dealing with json.

When adding an `--array` flag, it would be desirable to prevent usage on all non-array settings. In support of the comment by @alcohol, I think it should be up to the consumer of the data to handle it.  Accepting a single value as an array.  For the particular use case this issue was created for, I've been thinking about working on composer/installers#244

**Comment by cambri** [comment]
Experiencing the same issue as @tomasnagy has described. (composers/installers)

**Comment by sev-signal** [comment]
Any update on that one. I would like to do exactly the same, and it looks like 2 years after it's still not possible. Am I right to say that?

**Comment by landwire** [comment]
Same here. Would be great to do this via the composer cli.
Any updates on this?

**Comment by Seldaek** [comment]
Composer 2.0 adds a --json flag to config which should help here https://getcomposer.org/doc/03-cli.md#modifying-extra-values
