### ISSUE TITLE
"fork failed - Cannot allocate memory" with composer require but not with install or update

### ISSUE THREAD

**Issue by john-auld-sift** [composer/composer#5760]
My `composer.json`:
<details>
<summary>CLICK TO EXPAND</summary>
{
    "require": {
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "korotovsky/sso-idp-bundle": "^0.3.1"
    }
}
</details>

Output of `composer diagnose`:
<details>
<summary>CLICK TO EXPAND</summary>
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
</details>

When I run this command:

php -d memory_limit=-1 /usr/bin/composer require korotovsky/sso-idp-bundle

I get the following output:
<details>
<summary>CLICK TO EXPAND</summary>
PHP Warning:  proc_open(): fork failed - Cannot allocate memory in phar:///usr/bin/composer/vendor/symfony/console/Application.php on line 957
</details>

And I expected this to happen:

The command should complete successfully.

Note that the problem does not occur with the commands below.

php -d memory_limit=-1 /usr/bin/composer install
php -d memory_limit=-1 /usr/bin/composer update

The problem was seen on CentOS 7.2.1511 using rh-php56-2.0-6.el7.centos.x86_64 and on a separate virtual machine using php54-php-cli-5.4.45-5.el6.remi.x86_64 with a matching CentOS version and memory configuration (2GB physical memory and 512 MB swap space).

Increasing the swap space to 2GB allowed the command to run successfully in all cases.

Oddly, the "composer require" command also ran successfully with 512MB swap space during memory profiling with valgrind.

valgrind --tool=massif --pages-as-heap=yes --massif-out-file=massif.out php -d memory_limit=-1 /usr/bin/composer require korotovsky/sso-idp-bundle

**Comment by Seldaek** [comment]
https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors is all we have about memory, and unfortunately I doubt there is much more to say.
