### ISSUE TITLE
Private repositories with gitlab

### ISSUE THREAD

**Issue by marceldeglau** [composer/composer#5763]
Hey guys.

I need some help to setup private repositories with gitlab. 
My issue is, when I want to `install` the composer or `require`  I get this message:

     Could not fetch https://gitlab.com/api/v3/projects/*******************, enter your gitlab.com credentials to access private repos
     A token will be created and stored in "/root/.composer/auth.json", your password will never be stored
     To revoke access to this token you can visit gitlab.com/profile/applications

I don't want to set up the composer in this way, also this works not for me in the case of my gitlab account is protected with a two factor authentication.

I've looked to the documentation, but don't find a way to pull the repository via SSH2 or HTTPS.

Can you guys help me?

**Comment by alcohol** [comment]
To read the composer.json contained within the repository, we access the Gitlab API. To access the API for private repositories, you need to configure a "personal access token" (search for it [in the docs here](https://docs.gitlab.com/ce/api/)).

**Comment by marceldeglau** [comment]
@alcohol Thanks for your reply. I've already setup a "personal access token" (eg. I am using this for PhpStorm).

But how I need to save the token? The interactive mode is only asking for username and password. Can you give me an example?

Also I think my issue is a duplicate or simular as #5630 , #5661

Additional node: I think the best way to handle all this issue is, add an new configuration parameter to disable pull the repositories files via the API -- For example the composer will directly pull the data via SSH.

**Comment by alcohol** [comment]
https://getcomposer.org/doc/06-config.md#gitlab-token

> Additional node: I think the best way to handle all this issue is, add an new configuration parameter to disable pull the repositories files via the API -- For example the composer will directly pull the data via SSH.

It's not possible to pull a single file through ssh as far as I know. We use the API to access the `composer.json` file without cloning the entire repository. This is done to get the metadata needed for the dependency solver before it can determine what will be installed.
