### ISSUE TITLE
Ease namespacing of Composer scripts

### ISSUE THREAD

**Issue by raphaelstolt** [composer/composer#5764]
Future and namespaced Composer script definitions `composer.json`:
<details>
<summary>CLICK TO EXPAND</summary>
```json
{
  "_comment": "ommitted content",
  "scripts": {
     "namespace": {
       "test": "phpunit",
       "test-with-coverage": "phpunit --coverage-html coverage-reports",
       "configure-commit-template": "git config --add commit.template .gitmessage"
    }
  }
}
```
</details>

When I run this command:
```
composer
```

I would expect the following output:
<details>
<summary>CLICK TO EXPAND</summary>
```
namespace
 test                      Run the namespace:test script as defined in composer.json.
 test-with-coverage        Run the namespace:test-with-coverage script as defined in composer.json.
 configure-commit-template Run the namespace:configure-commit-template as defined in composer.json.
```
</details>

And I would expect the Composer scripts to be available and applicable as is:
```
composer namespace:test
```

**Comment by alcohol** [comment]
There is no added value here. The scripts handling is already more complicated than it has to be due to various exotic feature requests we received for it.

**Comment by stof** [comment]
you could probably achieve it already by using ``namespace:test`` as key in ``script``. No need to add extra features in the JSON schema (which would make it harder to handle, as value for a script can be an array already to provide several commands for this script)

**Comment by raphaelstolt** [comment]
The reason behind this PR was to reduce duplication and avoid multiple namespaces due to spelling mistakes.
