### ISSUE TITLE
Download from github private repo broken

### ISSUE THREAD

**Issue by SirLouen** [composer/composer#5767]
I've been using this version 1.2.1 but when trying to update I get: Error 404 (authentication issue):
https://developer.github.com/v3/#client-errors

But using an old 1.0-dev it works fine.

I've been using the vcs method for repository and it ask for token when going right, but with latest version 1.2.1 it shows directly the 404 error mentioned above

**Comment by alcohol** [comment]
Please use the issue template. We cannot help you when you do not provide any of the information we require. It's not rocket science.

**Comment by brusch** [comment]
My `composer.json`:
<details>
<summary>CLICK TO EXPAND</summary>
```json
{                                                                                   
    "repositories": [                                                               
        {                                                                           
            "type": "vcs",                                                          
            "url": "https://github.com/any-private/repo.git"     
        }                                                                           
    ],                                                                              
    "require": {                                                                    
        "any-private/repo": "dev-master"                         
    }                                                                               
}  
```
</details>

Output of `composer diagnose`:
<details>
<summary>CLICK TO EXPAND</summary>
```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.pimcore-partner/ActiveDirectoryAuth : unbound version constraints (dev-master) should be avoided
Checking platform settings: WARNING
The xdebug extension is loaded, this can slow down Composer a little.
 Disabling it when using Composer is recommended.

Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
```
</details>

When I run this command:
```
composer update
// or
composer install
```

I get the following output:
<details>
<summary>CLICK TO EXPAND</summary>
```
Loading composer repositories with package information


  [Composer\Downloader\TransportException]
  The "https://api.github.com/repos/any-private/repo" file could not be downloaded (HTTP/1.1 404 Not Found)


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
```
</details>

And I expected this to happen:
Composer should prompt with the link to the access token generator on github.com and should ask for the token. 

I think this is actually pretty critical :(

**Comment by Seldaek** [comment]
There is still not enough info there to reproduce it or figure out what is going on.. Try running update with `-vvv` and pasting the full output maybe. Don't delete stuff, change the private repo name if you must but otherwise it's better to leave the output alone.

**Comment by brusch** [comment]
Here we go: 

```
bernie@pimcore:/tmp/composer-test$ composer update -vvv
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/tmp/composer-test): git branch --no-color --no-abbrev -v
Executing command (/tmp/composer-test): git describe --exact-match --tags
Executing command (/tmp/composer-test): git log --pretty="%H" -n1 HEAD
Failed to initialize global composer: Composer could not find the config file: /home/bernie/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /tmp/composer-test/vendor/composer/installed.json
Running 1.2.1 (2016-09-12 11:27:19) with PHP 7.0.8-1~dotdeb+8.1 on Linux / 3.16.0-4-amd64
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Downloading https://api.github.com/repos/pimcore-partner/ActiveDirectoryAuth
Executing command (CWD): git config github.accesstoken
Downloading https://api.github.com/repos/pimcore-partner/ActiveDirectoryAuth


  [Composer\Downloader\TransportException]
  The "https://api.github.com/repos/pimcore-partner/ActiveDirectoryAuth" file could not be downloaded (HTTP/1.1 404 Not Found)


Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Util/RemoteFilesystem.php:368
 Composer\Util\RemoteFilesystem->get() at phar:///usr/local/bin/composer/src/Composer/Util/RemoteFilesystem.php:101
 Composer\Util\RemoteFilesystem->getContents() at phar:///usr/local/bin/composer/src/Composer/Repository/Vcs/VcsDriver.php:107
 Composer\Repository\Vcs\VcsDriver->getContents() at phar:///usr/local/bin/composer/src/Composer/Repository/Vcs/GitHubDriver.php:343
 Composer\Repository\Vcs\GitHubDriver->getContents() at phar:///usr/local/bin/composer/src/Composer/Repository/Vcs/GitHubDriver.php:435
 Composer\Repository\Vcs\GitHubDriver->fetchRootIdentifier() at phar:///usr/local/bin/composer/src/Composer/Repository/Vcs/GitHubDriver.php:65
 Composer\Repository\Vcs\GitHubDriver->initialize() at phar:///usr/local/bin/composer/src/Composer/Repository/VcsRepository.php:96
 Composer\Repository\VcsRepository->getDriver() at phar:///usr/local/bin/composer/src/Composer/Repository/VcsRepository.php:123
 Composer\Repository\VcsRepository->initialize() at phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:185
 Composer\Repository\ArrayRepository->getPackages() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:104
 Composer\DependencyResolver\Pool->addRepository() at phar:///usr/local/bin/composer/src/Composer/Installer.php:365
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:216
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:174
 Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:847
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:231
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:104
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:24

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

```

**Comment by alcohol** [comment]
I think using the "no-api" option might solve this (see https://getcomposer.org/doc/05-repositories.md).

If it does fix it though, we should probably take some time to document more extensively how to use private repositories. The number of related issues has been increasing more and more.

**Comment by brusch** [comment]
Unfortunately it doesn't. 
Now composer tries to clone the repo using ssh although the url is https://

```
{
    "repositories": [
        {
            "type": "vcs",
            "no-api": true,
            "url": "https://github.com/pimcore-partner/ActiveDirectoryAuth.git"
        }
    ],
    "require": {
        "pimcore-partner/ActiveDirectoryAuth": "dev-master"
    }
}
```

The strange thing is that it worked now for a long time and suddenly stopped working. 
Does it help if i provide you access to the private repo?

**Comment by Seldaek** [comment]
It might help to try and reproduce it yeah.. the URL is correct as per https://api.github.com/repos/composer/composer so if you get a 404 it must be an authentication issue. Not so sure what would have changed there that it would suddenly break though. Are you sure the token you have configured has access to that repo? It seems to be using the token that `git config github.accesstoken` returns according to the log.

**Comment by alcohol** [comment]
> It seems to be using the token that `git config github.accesstoken`

Good catch. That could be the culprit.

**Comment by brusch** [comment]
@Seldaek I've just sent you an invite to the private repo. 

Well the token is not configured, but Composer used to ask for the token and provided the link to generate the token with appropriate permissions, see: https://github.com/composer/composer/blob/14c77130e8f717ceb154720e1abefafe99124cb9/src/Composer/Util/GitHub.php#L89

**Comment by alcohol** [comment]
> Well the token is not configured

What do you mean by that exactly? Please use exact descriptions that leave no room for ambiguity.

Output of `git config github.accesstoken` is empty?
Output of `composer config github-oauth.github.com` is empty?

**Comment by brusch** [comment]
Both Git an Composer have no token set. 

> Output of git config github.accesstoken is empty?  

Yes 

> Output of composer config github-oauth.github.com is empty?  

Throws Exception: `github-oauth.github.com is not defined.`


But as I said, this wasn't necessary in the past

**Comment by alcohol** [comment]
Merely trying to determine all the facts. If we want to figure out what is going wrong, we need to know every detail.

**Comment by JackWH** [comment]
I was having a virtually identical problem to @brusch. My situation was almost identical to his in terms of version of composer, and outputs of `composer diagnose`, `composer update -vvv`, `git config github.accesstoken`, and `composer config github-oauth.github.com` (except obviously it references my own repository names etc.). The only other difference is that I am using SSH keys to access the private repository. My `composer.json` looks like this:

    "repositories": [{
        "type": "vcs",
        "url": "git@github.com:username/private-repository.git",
        "options": {
            "ssh2": {
                "username": "composer",
                "pubkey_file": "storage/.ssh/composer_id_rsa.pub",
                "privkey_file": "storage/.ssh/composer_id_rsa"
            }
        }
    }],
    "require": {
        "username/private-repository": "dev-master"
    }

This was working fine for months, then suddenly stopped working. Possibly since composer was updated (can't remember when), or maybe since I cleared composer's cache? I remember doing that recently.

Interestingly, unlike @brusch, I was able to fix this by using `"no-api": true`. I just thought I'd comment to let people know this has fixed it for me...

**Comment by Likeyn** [comment]
For posterity: just had the same issue (with SSH-based auth) and adding the `no-api` option did the trick indeed.

**Comment by ctrlaltdylan** [comment]
Used composer for this dozens of times, first time running into this error - adding the `"no-api": true" to the "repostiories" object worked for me too. Just a heads up!

**Comment by adrian-enspired** [comment]
>So if you can't access it.. making sure you have an GitHub API token configured:
> $ composer config github-oauth
> {"github.com":"...token here..."}

Just looking for clarification: does composer NOT prompt you to configure an access token when needed, as it did in the past?  It must now be done manually?

**Comment by Seldaek** [comment]
It should still prompt AFAIK. Easy to try for yourself though.

**Comment by adrian-enspired** [comment]
It does not, which is why I asked (people seemed to be trying to avoid giving a direct answer on that point).  It only gives me the [404 error described above](https://github.com/composer/composer/issues/5767#issuecomment-252202896) (this is after self-updating to most recent version (1.6.2)).

It does work after adding the token manually.

If the prompt-to-setup-token feature is gone, it should come back.  The current behavior is confusing and inconvenient.

**Comment by Seldaek** [comment]
@adrian-enspired OK wow this has been broken for a while I guess unless GitHub changed the way they respond to unauthenticated API  requests recently..

Anyway should be fixed now by 1933532ec5a436191e43c6fb43e34200c21536b2

**Comment by tsteuwer-accesso** [comment]
We just had a dev run into this and using `no-api: true` works but it makes no sense that our composer.json file hasn't changed in a year. Is it because they've changed the response composer is looking for?

**Comment by stof** [comment]
@tsteuwer-accesso are you using Composer 1.6.3 or an older version ?

**Comment by tsteuwer-accesso** [comment]
@stof we are using 1.6.3
