### ISSUE TITLE
Parse error with aws-sdk-php

### ISSUE THREAD

**Issue by 737simpilot** [composer/composer#5768]
I'm trying to upload an extension for phpBB that uploads attachments to Amazon S3. When I place the extension folder in my FTP my website goes blank. Looking at the error_log I see this:

[07-Oct-2016 00:02:25 America/Chicago] PHP Parse error:  syntax error, unexpected '$value' (T_VARIABLE) in /home/username/public_html/website/ext/AustinMaddox/s3/vendor/aws/aws-sdk-php/src/functions.php on line 36

While loading the website as the extension is being uploaded I see these two errors:

[phpBB Debug] PHP Warning: in file [ROOT]/ext/AustinMaddox/s3/vendor/autoload.php on line 5: require_once([ROOT]/ext/AustinMaddox/s3/vendor/composer/autoload_real.php): failed to open stream: No such file or directory

[phpBB Debug] PHP Warning: in file [ROOT]/ext/AustinMaddox/s3/vendor/composer/autoload_real.php on line 66: require([ROOT]/ext/AustinMaddox/s3/vendor/guzzlehttp/promises/src/functions_include.php): failed to open stream: No such file or directory

The extension is located here: https://www.phpbb.com/community/viewtopic.php?f=456&t=2385266

I use a shared account. So no VPS.  I ran composer in Windows 7 32bit and tried this extension in Xampp for testing and then wanted to test live. I installed composer into this extension with the Windows command prompt generating the necessary vendor files. Then I uploaded this extension to my website FTP when I got this error. 

PHP version 5.4.45.

Any info?

**Comment by alcohol** [comment]
Looks to me like you did not upload all the necessary files.

Also, your host is running php 5.4 but this extension requires 5.5, so it is never going to work.

**Comment by 737simpilot** [comment]
It says,

Requirements

PHP 5.3.2 or above (at least 5.3.4 recommended to avoid potential bugs)

**Comment by 737simpilot** [comment]
Just updated to PHP 5.6.19. Same errors persist. 

Would there be a difference if I installed composer in a Linux VM instead of Windows?

**Comment by alcohol** [comment]
I am talking about about the requirements of the aws extension for phpbb. Not about Composer. You need to upgrade the php version on your shared host, not your localhost.

**Comment by 737simpilot** [comment]
I just did update my PHP version on my host. That's what I meant.

**Comment by alcohol** [comment]
> `[07-Oct-2016 00:02:25 America/Chicago] PHP Parse error: syntax error, unexpected '$value' (T_VARIABLE) in /home/username/public_html/website/ext/AustinMaddox/s3/vendor/aws/aws-sdk-php/src/functions.php on line 36`

This error is a result of your PHP version being unsupported. That line/statement uses `yield`, which requires at least PHP >= `5.5`.

**Comment by 737simpilot** [comment]
It was inded the PHP version. I did update the PHP version and had errors loading the site as the file was being uploaded so I figured I still had a problem. But I just allowed the whole extension to install for the 7th time time and it finally worked.

**Comment by msisra99** [comment]
http://www.esra.ml
