### ISSUE TITLE
Set Environment Variable When `no-dev` option is passed

### ISSUE THREAD

**Issue by josephabrahams** [composer/composer#5769]
It would be very useful to be able to determine is the `no-dev` option has been set when running `post-install-cmd` scripts.

**Comment by alcohol** [comment]
You will have to be more specific.

**Comment by josephabrahams** [comment]
We use bash scripts defined in `post-install-cmd` to run administrative actions for setting up a site after a new deploy. Some scripts should/shouldn't run upon installation in a local development environment. Given that the --no-dev flag in passed for production installed, it would be nice if there an a way to test for this option from the Unix environment.

**Comment by axel-rutz** [comment]
SO has some hints on this: https://stackoverflow.com/questions/13087088/composer-run-scripts-only-in-dev-environment

**Comment by Seldaek** [comment]
There is now (as of 1.3.0) a COMPOSER_DEV_MODE env var which lets you react based on the --no-dev flag in scripts.
