### ISSUE TITLE
Conflict between package minimum PHP version and version used to create lock file

### ISSUE THREAD

**Issue by dshafik** [composer/composer#5772]
I have a package with a minimum PHP version of 5.5:

```json
{
    "name": "dshafik/composer-lock-bug",
    "description": "Create incompatible .lock files with newer PHP versions",
    "require": {
        "php": ">=5.5",
        "friendsofphp/php-cs-fixer": "^1.9"
    },
    "authors": [
        {
            "name": "Davey Shafik",
            "email": "me@daveyshafik.com"
        }
    ]
}
```

Then, depending on whether I add `config.platform.php = 5.5` to the JSON:

The `friendsofphp/php-cs-fixed` package has a dependency like: `symfony/event-dispatcher ^2.1 || ^3.0` which resolve differently with the `config.platform.php` version, and my local version (7.x) — installing 2.x on PHP 5.5 and 3.x on PHP 7.

This is because 2.8 has a dependency of `>=5.3.9` while 3.1 has a dependency of `>=5.5.9` and `5.5` is equal to `5.5.0`, not meeting the `5.5.9` requirement. *This is correct behavior*. 

The problem is that the `composer.lock` which I commit to my RCS **as per best practices** can have incompatible versions from `PHP >= 5.5.9` upgrade, vs a `<=5.5.9` upgrade. Now if I try to `composer install` and run on PHP `< 5.5.9` but > `5.5.0` which is **valid per composer.json** I will get incompatible code. This becomes much worse when the difference between versions is a minor or major version difference, rather than micro in this case.

On the other hand, if I'm running on the later versions, I want the latest compatible (but vetted and locked) versions of the code, particularly as the older code may be unmaintained, opening myself up to security and other issues.

The only way I can see to resolve this is to allow for multiple platforms in `composer.lock`.

For now, I will have to set the `config.platform.php` and deal with putting out older code.

**Comment by alcohol** [comment]
I'm not sure what you are actually submitting as an issue here? All of the above is common knowledge. Can you elaborate what exactly the issue is here, according to you?
