### ISSUE TITLE
composer error with php 5.5

### ISSUE THREAD

**Issue by nimasdj** [composer/composer#5774]
Composer gives error with php 5.5 because constant scalar is pupported on >5.6. Parse error in composer\autoload_static.php at line 10 - syntax error, unexpected '.', expecting ')'

and line 10 of that file is: 
```php
    '34901568a1e26d13dd475cb2c85e0284' => __DIR__ . '/..' . '/zendframework/zend-form/autoload/formElementManagerPolyfill.php',
```
in the file below. It works fine with 5.6,  	so if I use autoload.php on php 5.5, will I get the error? Or it uses its other files like *_files.php, *_classmap.php etc? Or what to do to have autoload.php compatible with 5.5? Please advise.

```php
    <?php

    // autoload_static.php @generated by Composer

    namespace Composer\Autoload;

    class ComposerStaticInitf5fb4a6513c4bb8e1183f32a6d8a31be
    {
    public static $files = array (
    '34901568a1e26d13dd475cb2c85e0284' => __DIR__ . '/..' . '/zendframework/zend-form/autoload/formElementManagerPolyfill.php',
    '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
    '3e2471375464aac821502deb0ac64275' => __DIR__ . '/..' . '/symfony/polyfill-php54/bootstrap.php',
    '6a47392539ca2329373e0d33e1dba053' => __DIR__ . '/..' . '/symfony/polyfill-intl-icu/bootstrap.php',
    '67153d798259e2422f77ee379077b565' => __DIR__ . '/..' . '/minfraud/http/src/HTTPBase.php',
    '038a1d49667b1c077e3f164315eba901' => __DIR__ . '/..' . '/minfraud/http/src/CreditCardFraudDetection.php',
    );
```

**Comment by alcohol** [comment]
You are not making any sense. Our test suite covers all of this and it works just fine on all versions of PHP that we support. Please provide an actual reproducible error.

**Comment by nimasdj** [comment]
I even tried to run composer with php 5.5 to generate files, but that file still looks the same as I copy/pasted above. Does this mean that composer was not running actually under 5.5 but 5.6? @alcohol

**Comment by alcohol** [comment]
Can you specific **when** exactly you are experiencing this error?

**Comment by nimasdj** [comment]
When I try to ionCube encode it with php 5.5, it gives that error but works fine with php 5.6 with ionCube encoder.
In CLI when generating autoloader I ran it as 5.5 but autoload_static.php still looks like above with constant scalar even when running generator under php 5.5 in CLI. why?

**Comment by alcohol** [comment]
Because we always generate that file. We simply do not include it when your PHP version does not support it.

IonCube isn't smart enough to recognize that this file is never used and tries to encrypt it I guess.

**Comment by nimasdj** [comment]
So if I understood correctly:
1) That file is always generated even if CLI is < 5.6
2) If product is running under a server < 5.6 that file not be included.
So we will be fine with 5.5 as that file will be included only if server is >= 5.6
Right? @alcohol

**Comment by alcohol** [comment]
Correct.

**Comment by nimasdj** [comment]
Thanks a lot.

**Comment by alcohol** [comment]
See https://github.com/composer/composer/blob/master/src/Composer/Autoload/AutoloadGenerator.php#L593-L598 for specifics.

**Comment by nimasdj** [comment]
Understood! 👍
