### ISSUE TITLE
Composer keep .git subdirectory package on vendor

### ISSUE THREAD

**Issue by jonathansayag** [composer/composer#5777]
Hi,

I'm using `repositories` in `composer.json` to get a package from a Git URL.

Everything is working except one thing : when Composer is cloning my package, it always keep the subdirectory `.git` of my package in the vendor directory, so why ?

Thanks

**Comment by alcohol** [comment]
Because you are installing from source. This is default behaviour. Anything installed from source, also dependencies that are pulled through Packagist, will always have their `.git` directory.
