### ISSUE TITLE
"https://getcomposer.org" Not responding & Composer Not installing !!!

### ISSUE THREAD

**Issue by amibappy** [composer/composer#5778]
hi i am Bappy, i am using :- 
os: windows 10 home,
browser: mozilla firefox 
xammp: leatest version (php 7)

while i'm trying to access "https://getcomposer.org/" its showing :- 
![capture2](https://cloud.githubusercontent.com/assets/13586412/19260707/ab94c386-8fad-11e6-944a-073f22450846.PNG)

Every other websites are working just fine except this one.

And while installing composer in windows installer its throwing this error :-
![capture](https://cloud.githubusercontent.com/assets/13586412/19260749/0d4c733a-8fae-11e6-97a3-90414dc346a4.PNG)

as a solution - i have changed the ipv4 - Ethernet/wi-fi MTU to 1458 & other numbers (previous 1500) & still the site not loading 😢 

i'm tired of this crazy problem !!!
if anyone can help.........Thanks in Advance 👍

**Comment by amibappy** [comment]
i have changed the ipv4 - Ethernet/wi-fi MTU to 1458 & other numbers (previous 1500) & still the site not loading 😢

**Comment by alcohol** [comment]
Are you behind a proxy or firewall? Cause the server is responding just fine for me.

**Comment by amibappy** [comment]
i am not using any proxy and my firewall looks clean & still having the problem 😢

**Comment by alcohol** [comment]
But you still get a timeout?

**Comment by alcohol** [comment]
Are you 100% certain that you are not behind a proxy or firewall? Are you at home, office, or some public wifi hotspot?

**Comment by amibappy** [comment]
i am in home, using my own personal laptop & using my internet in Ethernet provided by a local ISP. i have talked with my ISP about the problem but they have no strong response.  

without composer i will never see laravel again 😭

**Comment by alcohol** [comment]
Can you give us the output of `route print`?
And `tracert 87.98.253.108`?

**Comment by amibappy** [comment]
route print output :-
![route_print](https://cloud.githubusercontent.com/assets/13586412/19270391/a05dfa6c-8fe1-11e6-8bd2-ff099b8cf07a.PNG)
persistent routers : none


And tracert 87.98.253.108 output :
![trace](https://cloud.githubusercontent.com/assets/13586412/19270583/98b8e410-8fe2-11e6-9e4c-639020aafb3f.PNG)

**Comment by alcohol** [comment]
@Seldaek could this be an ipv6 issue? Or ISP routing issue?

**Comment by amibappy** [comment]
i have also tried "ipconfig/flushdns" & added the site (https://getcomposer.org) to trusted site list BUT it still timeout 😞

**Comment by amibappy** [comment]
OK Finally.........its my ISP problem.........the website is loading in another network connection. 
Thanks for been with me @alcohol 😀
