### ISSUE TITLE
Order of require in composer.json

### ISSUE THREAD

**Issue by frederikbosch** [composer/composer#5780]
Today I had a very strange composer behaviour. The order of the packages in `require` were relevant. The composer.json consisted of about 10 packages. When I changed the order of the first two, it was able to install. The other way around it was not because of `Conclusion don't install xyz`. Since the majority of my packages are linked to a Satis repo I cannot paste the complete json file here.

So this did not work:

```json
{
  "require": {
    "vendor/pkg1": "~1.0.0",
    "vendor/pkg2": "~1.0.0"
  }
}
```

while this did work:

```json
{
  "require": {
    "vendor/pkg2": "~1.0.0",
    "vendor/pkg1": "~1.0.0"
  }
}
```

However, when the packages were installed, the wrong versions were installed. Why is that so? Because if I enter `composer update` again right after installing, it installed the correct version of the packages. So there was an update available directly after the first install. With the packages installed the first time, there was no `composer.lock` and there was an empty vendor directory.

Hopefully this report is conclusive but I understand it might lack information because it would be hard to reproduce without access to the Satis repo.

Composer version 1.2.1 2016-09-12 11:27:19

**Comment by alcohol** [comment]
Unfortunately there is virtually nothing we can do without a reproducible scenario. Even the most basic of debugging approaches would require this. Everything else would be purely speculation.

**Comment by frederikbosch** [comment]
@alcohol I will reopen when I have more info.

**Comment by frederikbosch** [comment]
@alcohol I got a sense why this is failing. I'd like to reproduce in a test. Can you perhaps point me at a test that is testing the resolving of dependencies?

**Comment by alcohol** [comment]
Not exactly. But you can have a look at https://github.com/composer/composer/tree/master/tests/Composer/Test/Fixtures/installer

**Comment by frederikbosch** [comment]
@alcohol Thanks. Looks like what I need. I get a php-src feeling when looking at those .test files :)

**Comment by kenorb** [comment]
Related issue with repro steps: GH-7215.
