### ISSUE TITLE
verifying Certificate is failing

### ISSUE THREAD

**Issue by amad4biz** [composer/composer#5788]
I am behind a proxy, I installed composer but still receiving this error below can anyone please assist.
I am on windows 8.1 machine with xampp and composer installed.
Setting environment for using XAMPP for Windows.
myUserId c:\xampp
# composer diag

Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: WARNING
[Composer\Downloader\TransportException] The "https://packagist.org/packages.jso
n" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error
 messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify faile
d
failed to open stream: Cannot connect to HTTPS server through proxy
Checking HTTP proxy: FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.jso
n" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error
 messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify faile
d
failed to open stream: Cannot connect to HTTPS server through proxy
Checking HTTP proxy support for request_fulluri: OK
Checking HTTPS proxy support for request_fulluri: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: F3BB
Dev Public Key Fingerprint: 4AC45768C AD90147D AFE50952
OK
Checking composer version:

  [Composer\Downloader\TransportException]
  The "https://getcomposer.org/versions" file could not be downloaded: SSL op
  eration failed with code 1. OpenSSL Error messages:
  error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify
  failed
  failed to open stream: Cannot connect to HTTPS server through proxy

diagnose

**Comment by sstok** [comment]
Please try the tips in this issue: https://github.com/composer/composer/issues/2021

**Comment by amad4biz** [comment]
I tried that but it does not work, please anyone here to assist

**Comment by Seldaek** [comment]
Auto-closing this as it's marked as support request and has not received any update in a long time.
