### ISSUE TITLE
Extend package types

### ISSUE THREAD

**Issue by raphaelstolt** [composer/composer#5789]
It would be really helpful (in combination with some possible Packagist search filter) to extend the current package types. 

Missing types that I see for _my_ usecases and filter needs are `cli[-application]` and `composer-script`.

**Comment by alcohol** [comment]
You can use whatever type you want. But you'll have to write your own installer if you want to handle them in any special way (see [composer/installers](/composer/installers)).

**Comment by raphaelstolt** [comment]
The main purpose of this issue was to increase the possiblity to filter packages by type (i.e. on Packagist); which wouldn't work with `whatever` types.

**Comment by alcohol** [comment]
Then maybe you are confused, this is composer/composer, not [composer/packagist](/composer/packagist).

**Comment by raphaelstolt** [comment]
Nah I'm __not__ confused. To make this work (the filtering) on `composer/packagist` they have to be added to `composer/composer`.

**Comment by stof** [comment]
@raphaelstolt composer does not define a list of types. Packages can use whatever they want there.
but the primary usage of the type is to change the installation of the package, not to provide search filtering. Keywords are a better way to configure the search (and you can have several ones)

**Comment by alcohol** [comment]
@raphaelstolt You seem very confident in your statement. What makes you believe that in order to support this, changes need to be made in `composer/composer`?

**Comment by raphaelstolt** [comment]
Let's assume there is a `cli` package type and let's assume there's a Packagist filter for packages of the type `cli` or any other type. Where would the package type definition and documentation of these go?

Of course it would also be possible to implement a hypothetical Packagist filter based on `whatever-package-types` but having them definied and documented will prolly produce betty filter results.

**Comment by raphaelstolt** [comment]
I can nevertheless totally live with having this issue being closed.

**Comment by stof** [comment]
@raphaelstolt there is **no** definition for package types.

and Packagist already supports filtering by any package type you invent (it does not know any package type, not even the few ones defined in composer core btw. As far as packagist is concerned, the type can be any string): https://packagist.org/search/?type=mink-driver&q=selenium

**Comment by raphaelstolt** [comment]
@stof

> ... (it does not know any package type, not even the few ones defined in composer core btw. ...)

So there are package defintions in `composer/composer`. :smile:

**Comment by stof** [comment]
@raphaelstolt composer does not have a concept of definition for package types (btw, you are now talking about package definitions, which are totally different, and are what the whole composer.json is about).
What composer has are package installers, which know how to install packages. There are a few installers in core, which indeed define some supported types:

- the LibraryInstaller, handling packages with any type, which handles the default installation of a package (putting it in ``vendor/<package-name>``), used as fallback when no other installer supports the package
- the PluginInstaller, handling packages with type ``composer-plugin`` and ``composer-installer``, which additionally registers the plugin (it extends the LibraryInstaller)
- the Metapackage installer handling ``metapackage`` packages (i.e. packages not providing any source code)
- the PearInstaller, handling ``pear-library`` packages (the pear integration layer requires a special installation to account for special Pear features like moving files around)

As you can see, composer defines types only when we have a need for a special installation way. There is a common convention in the community to use ``project`` as type for projects which are consuming packages but are not meant to be installed themselves as a dependency elsewhere (for instance Packagist itself), but this is just a community convention. There is nothing in composer about it.

Note that https://github.com/composer/installers provides a bunch of installers for legacy project structures (i.e. frameworks requiring to install stuff in their own locations), and so defines a bunch of types for packages needing this special installation.

Btw, the case of ``mink-driver`` I used above in the example I gave is actually an abuse of type. As these packages don't require a special installation way, the default type should be used, and the search capabilities should be provided through keywords (as this is what they are about).
