### ISSUE TITLE
Composer install doesn't work

### ISSUE THREAD

**Issue by CutmastaD** [composer/composer#5790]
I tried this 
`curl -sS http://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer`

This is what I get

All settings correct for using Composer
PHP Warning:  file_get_contents(https://getcomposer.org/versions): failed to open stream: Connection timed out in - on line 762
PHP Warning:  Invalid argument supplied for foreach() in - on line 508
None of the 0 stable version(s) of Composer matches your PHP version (5.6.26-0+deb8u1 / ID: 50626)

I already checked the connection, to get that out the way by
`curl -sS https://getcomposer.org/versions`

and get

```
{
    "stable": [{"path": "/download/1.2.1/composer.phar", "version": "1.2.1", "min-php": 50300}],
    "preview": [{"path": "/download/1.2.1/composer.phar", "version": "1.2.1", "min-php": 50300}],
    "snapshot": [{"path": "/composer.phar", "version": "66efc9af8601234b8ab3a5fb91cfa7a2f30e9bbd", "min-php": 50300}]
}
```

I'm on Debian Jessie in a Virtualbox

**Comment by red-smeg** [comment]
I believe the installation of composer has changed significantly.  This from getcomposer.org

php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === 'e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

**Comment by CutmastaD** [comment]
Ok, I tried it.

`php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"`
gives me
PHP Warning:  copy(http://getcomposer.org/installer): failed to open stream: Connection timed out in Command line code on line 1

Then I downloaded the installer manually, renamed it composer-setup.php and tried the next step but it gave me the same exception
php composer-setup.php
All settings correct for using Composer
PHP Warning:  file_get_contents(https://getcomposer.org/versions): failed to open stream: Connection timed out in /home/vmolodew/composer-setup.php on line 762
PHP Warning:  Invalid argument supplied for foreach() in /home/vmolodew/composer-setup.php on line 508
None of the 0 stable version(s) of Composer matches your PHP version (5.6.26-0+deb8u1 / ID: 50626)

**Comment by red-smeg** [comment]
Can you successfully curl another file ??

**Comment by red-smeg** [comment]
Are you able to curl or copy any other URL's ??

**Comment by CutmastaD** [comment]
I already tried
`curl -sS https://getcomposer.org/versions`

and got

{
    "stable": [{"path": "/download/1.2.1/composer.phar", "version": "1.2.1", "min-php": 50300}],
    "preview": [{"path": "/download/1.2.1/composer.phar", "version": "1.2.1", "min-php": 50300}],
    "snapshot": [{"path": "/composer.phar", "version": "66efc9af8601234b8ab3a5fb91cfa7a2f30e9bbd", "min-php": 50300}]
}

or should I try a different URL?

**Comment by alcohol** [comment]
What about `php -r "copy('http://getcomposer.org/installer', 'composer-setup.php');"` (note: switched to http instead of https)?

**Comment by metinucar** [comment]
Switching from `https` to `http` ( as @alcohol suggested ) solved the problem for me.

**Comment by alcohol** [comment]
That is not good. :-/

**Comment by metinucar** [comment]
@alcohol Why?

**Comment by alcohol** [comment]
It should work over https. If it does not, then something is wrong:

* maybe your php + openssl configuration is incorrect,
* maybe your php + openssl installation is corrupt/version-mismatch/other-issue,
* bad proxy configuration or https not supported by proxy,
* bad firewall configuration or https not allowed by firewall.

**Comment by pixel-kitchen** [comment]
I am having the same issue as CutmastaD.

**Comment by sigysmund** [comment]
I have disabled IPv6 under debian, and then it was working fine. :)

**Comment by alcohol** [comment]
@pixel-kitchen you will need root access to write anything into the `/bin` directory. Use sudo or su.

**Comment by alcohol** [comment]
@sigysmund while that is one way to solve ipv6 related problems, you could also try a slightly less drastic approach: https://getcomposer.org/doc/articles/troubleshooting.md#operation-timed-out-ipv6-issues-

**Comment by Seldaek** [comment]
@sigysmund Please contact your ISP if disabling IPv6 helps resolve anything. They should fix their routing rules.

**Comment by Seldaek** [comment]
Closing issue as it has been quiet for a long time and there is no clear next step we can take.

**Comment by ask694** [comment]
still problem not solved.. :(

**Comment by delroh** [comment]
I am having this problem, using either `http` or `https` i get:

```
PHP Warning:  copy(https://getcomposer.org/installer): failed to open stream: Connection timed out in Command line code on line 1
PHP Stack trace:
PHP   1. {main}() Command line code:0
PHP   2. copy() Command line code:1
```

So I tested with:
`php -r "copy('https://httpbin.org/get', 'hello.txt');"`

And with another api mocking service that returns something and both work. I have no idea why it is failing with composer. Is there anything I could check to pin down the problem?

**Comment by developer-sp** [comment]
sucess in ubuntu 20.04
I download it by browser and naming it ```composer-setup.php``` 
After follow others steps of the site 
too use this for work in terminal 
``` sudo mv composer.phar /usr/local/bin/composer``` open new terminal and test ```composer --version```
