### ISSUE TITLE
Cache cloned repositories

### ISSUE THREAD

**Issue by borekb** [composer/composer#5792]
I don't have a deep knowledge of Composer so may not be describing this issue 100% correctly but it seems to me that most stable dependencies are cached as ZIP files in %appdata% while most dev-stability dependencies are cloned from GitHub over and over again, if I delete the `vendor` folder. Compare:

![image](https://cloud.githubusercontent.com/assets/101152/19417281/77e04d6c-93a9-11e6-994a-4e1704cc4d30.png)

![image](https://cloud.githubusercontent.com/assets/101152/19417304/ef420af8-93a9-11e6-8d9f-a13a489365cd.png)

I'm currently on a slower internet connection (and a metered one) and this makes things quite slow & consuming a lot of my data. I'm wondering why repositories are not cached similarly to ZIP files as doing a `git pull` is much more efficient than `git clone`.

**Comment by mhujer** [comment]
Are you running latest Composer? It was added in 1.2.0, see [Changelog](https://github.com/composer/composer/blob/master/CHANGELOG.md#120-rc---2016-07-04) (It first clones it first into appcache and then into project.)

![image](https://cloud.githubusercontent.com/assets/353372/19420140/aa8b9c6c-93e5-11e6-8aaa-509a9a5974b2.png)

**Comment by alcohol** [comment]
Dist installs are cached. Git clones are only cached if your Git version is recent enough and you are using the latest snapshot of Composer.

**Comment by borekb** [comment]
@mhujer Thanks! I was on 1.1.
