### ISSUE TITLE
Composer need swap enabled, but doesn't use it

### ISSUE THREAD

**Issue by fancsali** [composer/composer#5793]
I've tried to update the dependencies for my Symfony project:

```
composer update
```

And I got the following output:
```
PHP Warning:  proc_open(): fork failed - Cannot allocate memory in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php on line 957
```

However, if I enable swap, as per https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors, it suddenly starts to work. Even though, the swap is completely unused, `watch free -m` shows the output below:
```
                    total       used       free     shared    buffers     cached
Mem:          2445       1071       1373          1         16        928
...
Swap:         2047          0       2047
```

The *free memory* field drops quite low, but never actually goes below ~50 megs.

**Comment by bertalanimre** [comment]
Sooooo, no update how to tell Composer to use the freaking SWAP? I jsut ran into this error and I need a solution.
