### ISSUE TITLE
require - Add packages alphabetically

### ISSUE THREAD

**Issue by sourcerer-mike** [composer/composer#5795]
My `composer.json`:

```json
"require": {
    "composer/composer": "~1.0.0@dev",
    "wp-cli/wp-cli": "~0.23",
    "messed-up/ignore": ">9000"
  },
```

When I run this command:

```
composer require atoum/atoum
```

I get the following output:

```
"require": {
    "composer/composer": "~1.0.0@dev",
    "wp-cli/wp-cli": "~0.23",
    "messed-up/ignore": ">9000",
    "atoum/atoum": "~something"
  },
```

And I expected this to happen:

```
"require": {
    "atoum/atoum": "~something",
    "composer/composer": "~1.0.0@dev",
    "wp-cli/wp-cli": "~0.23",
    "messed-up/ignore": ">9000"
  },
```

So please ignore if there are mistakes already.
But add packages in alphabetical order, which is the most useful one in lists over nine packages - happens quiet often.
Tiny thing but way more readable and easier to maintain IMHO.

What do you think?

**Comment by xabbuh** [comment]
You can use the `--sort-packages` option.

**Comment by alcohol** [comment]
What @xabbuh said.

Both options (sorted or not sorted) are already present. We're not going to add a third (semi-almost-sorted).

**Comment by stof** [comment]
Btw, you can even force it in your project:

```json
{
    "config": {
        "sort-packages": true
    }
    "require": {}
}
```

This way, you don't need to pass the option anymore when calling the command

**Comment by sourcerer-mike** [comment]
Wow, I didn't see that. Thank you very much! :)
