### ISSUE TITLE
composer.phar installed Cache Access denied error

### ISSUE THREAD

**Issue by sarannrich** [composer/composer#5798]
When I run this command:

C:\wamp64\www>php composer.phar install

I get the following output:
C:\wamp64\www>
C:\wamp64\www>php composer.phar install
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>ERROR: Cache Access Denied</title>

<style type="text/css"></style>

</head><body id=ERR_CACHE_ACCESS_DENIED>

<div id="titles">
<h1>ERROR</h1>
<h2>Cache Access Denied.</h2>
</div>

<hr>

<div id="content">
<p>The following error was encountered while trying to retrieve the URL: <a href="https://getcomposer.org/*">https://getcomposer.org/*</a></p>

<blockquote id="error">
<p><b>Cache Access Denied.</b></p>
</blockquote>

<p>Sorry, you are not currently allowed to request https://getcomposer.org/* from this cache until you have authenticated yourself.</p>

<p>Please contact the <a href="mailto:root?subject=CacheErrorInfo%20-%20ERR_CACHE_ACCESS_DENIED&amp;body=CacheHost%3A%20proxy.manline.co.za%0D%0AErrPage%3A%20ERR_CACHE_ACCESS_DENIED%0D%0AErr%3A%20%5Bnone%5D%0D%0ATimeStamp%3A%20Mon,%2010%20Oct%202016%2011%3A18%3A59%20GMT%0D%0A%0D%0AClientIP%3A%20192.168.2.53%0D%0A%0D%0AHTTP%20Request%3A%0D%0ACONNECT%20%2F%20HTTP%2F1.1%0AHost%3A%20getcomposer.org%0D%0AProxy-Connection%3A%20Keep-Alive%0D%0AProxy-Authorization%3A%20NTLM%20TlRMTVNTUAADAAAAGAAYAEgAAAAYABgAYAAAAAAAAAB4AAAAFgAWAHgAAAAAAAAAjgAAAAAAAACOAAAAAYIIogUBKAoAAAAP11kiDrsCyFEAAAAAAAAAAAAAAAAAAAAATY5qXk5Siujs47+6zkiWdiwkVGLBM0qdcwByAGkAYwBoAGEAcgBkAHMAbwBuAA%3D%3D%0D%0A%0D%0A%0D%0A">cache administrator</a> if you have difficulties authenticating yourself.</p>

<br>
</div>

<hr>

<div id="footer">
<p>Generated Mon, 10 Oct 2016 11:18:59 GMT by proxy.manline.co.za (squid/3.1.23)</p>

</div>

</body></html>

C:\wamp64\www>

And I expected this to happen:

**Comment by stof** [comment]
this looks like a issue with your proxy at ``proxy.manline.co.za``, which seems to require authentication while you don't authenticate.
You should configure the HTTP_PROXY env variable to provide the proxy infos: https://getcomposer.org/doc/03-cli.md#http-proxy-or-http-proxy
