### ISSUE TITLE
Composer not connecting through SSH with Drupal 8 instance hosted by Google Cloud

### ISSUE THREAD

**Issue by Peter4498** [composer/composer#5801]
My `composer.json`:
{
    "require": {
        "christian-riesen/otp": "^2.2",
        "paragonie/random_compat": "^2.0",
        "giggsey/libphonenumber-for-php": "^7.7"
    },
    "repositories": {
        "drupal": {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    }
}

When I go to enable the module in Drupal 8 (TFA) which requires the christian-riesen/otp library....

I get the following output:

"Please install the 'christian-riesen/otp' library via composer. See the module README for instructions."

And I expected this to happen:

I expected the module to install since I already had the 'christian-riesen/otp' library. Why does it keep telling me I need to install it if it's already there?

**Comment by stof** [comment]
Displaying such warning is not part of composer, so this should probably be asked in the Drupal community instead.

**Comment by alcohol** [comment]
As @stof said, this is not a composer issue. Please ask the drupal community/maintainer of the drupal module you are attempting to enable.
