### ISSUE TITLE
Installation of "require" entries and autoload information of a local package

### ISSUE THREAD

**Issue by nimayneb** [composer/composer#5802]
I would like to install "require" entries of a local package in a project and extend the composer autoloader with the right path to the psr4 classes.

i don`t like the manner of adding psr-4 entries into the root "composer.json", because of double information in the project and it is the wrong location to do that.

Root "composer.json":
```json
{
   "name": "project",
   "require": {
      "local/package": "*"
   },
   "repositories": [
      {
         "type": "path",
         "url": "src/ext/*"
      }
   ]
}
```

Package "composer.json":
```json
{
   "name": "local/package",
   "require": {
      "external/package": "1.0.0"
   },
   "autoload": {
      "psr-4": {
         "Local\\Package\\": "Classes/"
      }
   }
}
```

After "composer install" it throws an error with "Symlink failed, fallback to use mirroring! Mirrored from src/ext". So, i miss the option for installing the requirements and adding my autoload information only. i just want to disallow the installation of the local package into the vendor dir.

is that even possible?

**Comment by stof** [comment]
the autoload info should work already if you have the right configuration in the package composer.json. You should not need anything special to have it working.

> After "composer install" it throws an error with "Symlink failed, fallback to use mirroring! Mirrored from src/ext".

it does not throw an error. It displays a warning saying that it could not create a symlink (if you are on windows, this requires having the right priviledges for your user account), and so it copied the code instead. There is such warning, because it means that changes to the source are not automatically applied to the installed package (requiring to update the installed package in case you make changes to the source).

**Comment by nimayneb** [comment]
Sorry, yes of course it is only a warning. I do not want the symlink or mirroring to the vendor path. That is the problem. i wondering about that there is no Option for my case.

**Comment by alcohol** [comment]
@nimayneb You are not making much sense. What do you want then?

**Comment by nimayneb** [comment]
My fault... Once again: The complete source of a composer project (root package) are already installed in my case. So i have a subset of local packages (like extension/module for this php project) within my sources. It is already a component of the project. The local packages have dependency definition (requires) and the autoload definition.

A local package no longer needs to be installed, composer has just fetch the dependencies (from the local package; except himself) and the autoload definitions.

The reason is, that i want to distribute the dependencies/autoload info into the right place.

Alternatively i have defined all information about autoload info into the composer.json (root). This is working. But then i also have to define all dependencies there and that is the sticking point. I cannot directly see which subset (local package) has these dependencies.

**Comment by alcohol** [comment]
Your workflow is simply not supported, because it is a weird edge-case.

You can look at https://github.com/beberlei/composer-monorepo-plugin

**Comment by nimayneb** [comment]
yes, no. Not really what i`m looking for. Nearly. This plugin supports the autoload question at least.

Thanks anyway.

**Comment by piotr-cz** [comment]
As described here: https://barryvanveen.nl/blog/44-package-development-run-a-package-from-a-local-directory

> After some searching, it turns out that this problem is specific for Windows users running a virtual machine. Windows does not allow local admins to create symlinks. Luckily this can be solved with a single change.
> 
> When you start your VM make sure you do this as an administrator.
