### ISSUE TITLE
Can't combine self and outdated options in show

### ISSUE THREAD

**Issue by curry684** [composer/composer#5808]
I expected `composer show -s --outdated` to show me outdated root packages, instead it gives:

```
PHP Fatal error:  Uncaught TypeError: Argument 4 passed to Composer\Command\ShowCommand::printMeta() must implement interface Composer\Package\PackageInterface, boolean given, called in phar:///opt/composer.phar/src/Composer/Command/ShowCommand.php on line 182 and defined in phar:///opt/composer.phar/src/Composer/Command/ShowCommand.php:461
Stack trace:
#0 phar:///opt/composer.phar/src/Composer/Command/ShowCommand.php(182): Composer\Command\ShowCommand->printMeta(Object(Composer\Package\RootPackage), Array, Object(Composer\Repository\ArrayRepository), false)
#1 phar:///opt/composer.phar/vendor/symfony/console/Command/Command.php(259): Composer\Command\ShowCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///opt/composer.phar/vendor/symfony/console/Application.php(849): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///opt/composer.ph in phar:///opt/composer.phar/src/Composer/Command/ShowCommand.php on line 461

Fatal error: Uncaught TypeError: Argument 4 passed to Composer\Command\ShowCommand::printMeta() must implement interface Composer\Package\PackageInterface, boolean given, called in phar:///opt/composer.phar/src/Composer/Command/ShowCommand.php on line 182 and defined in phar:///opt/composer.phar/src/Composer/Command/ShowCommand.php:461
Stack trace:
#0 phar:///opt/composer.phar/src/Composer/Command/ShowCommand.php(182): Composer\Command\ShowCommand->printMeta(Object(Composer\Package\RootPackage), Array, Object(Composer\Repository\ArrayRepository), false)
#1 phar:///opt/composer.phar/vendor/symfony/console/Command/Command.php(259): Composer\Command\ShowCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///opt/composer.phar/vendor/symfony/console/Application.php(849): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///opt/composer.ph in phar:///opt/composer.phar/src/Composer/Command/ShowCommand.php on line 461
```

**Comment by alcohol** [comment]
That is weird. I am unable to combine them (I only get the self info, not outdated), but I do not get an error however.

```
rob ~/Git/composer > composer show -s --outdated
name     : composer/composer
descrip. : Composer helps you declare, manage and install dependencies of PHP projects, ensuring you have the right stack everywhere.
keywords : package, dependency, autoload
versions : * 1.3.x-dev
latest   : 1.2.1
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : []  66efc9af8601234b8ab3a5fb91cfa7a2f30e9bbd
dist     : []  66efc9af8601234b8ab3a5fb91cfa7a2f30e9bbd
names    : composer/composer

support
irc : irc://irc.freenode.org/composer
issues : https://github.com/composer/composer/issues

autoload
psr-4
Composer\ => src/Composer

requires
php ^5.3.2 || ^7.0
justinrainbow/json-schema ^1.6 || ^2.0 || ^3.0 || ^4.0
composer/ca-bundle ^1.0
composer/semver ^1.0
composer/spdx-licenses ^1.0
seld/jsonlint ^1.4
symfony/console ^2.5 || ^3.0
symfony/finder ^2.2 || ^3.0
symfony/process ^2.1 || ^3.0
symfony/filesystem ^2.5 || ^3.0
seld/phar-utils ^1.0
seld/cli-prompt ^1.0
psr/log ^1.0

requires (dev)
phpunit/phpunit ^4.5 || ^5.0.5
phpunit/phpunit-mock-objects ^2.3 || ^3.0

suggests
ext-zip Enabling the zip extension allows you to unzip archives
ext-zlib Allow gzip compression of HTTP requests
ext-openssl Enabling the openssl extension allows you to access https URLs for repositories and packages
```

**Comment by alcohol** [comment]
Is there a chance that Windows handles these command line arguments differently?

**Comment by curry684** [comment]
I'm actually developing this project on Ubuntu hehe. It seems weird that it would depend on the package. I'm very short on time these days but should be able to debug it myself late next week or so.

**Comment by curry684** [comment]
I fixed the crash but it still seems silly and a bug on its own that I can't combine the 2 options - the scenario I was trying was to list the outdated *root* requirements that might be a candidate for breaking updates, for example referencing `^2.7` of a package that has a `3.0` out by now.

**Comment by curry684** [comment]
Funny part is I discovered today that the `-D` flag on `outdated` is what I was looking for. Not sure whether that warrants keeping this bug open, technically it's still broken that one flag silently nukes another.

**Comment by alcohol** [comment]
We could just issue a warning that the flags are mutually exclusive.

**Comment by curry684** [comment]
Wouldn't it be weird to have a flag that disables all other flags? Like doesn't that kind of beat the purpose of flags whatsoever and make it a prime candidate for a dedicated command?

**Comment by alcohol** [comment]
I do not think it is that weird at all. `--prefer-source` and `--prefer-dist` are mutually exclusive too. I am sure there are other examples that I cannot think of right now.

**Comment by curry684** [comment]
Good point, we'll just need to implement an error then.

**Comment by Seldaek** [comment]
IMO what you are asking (show me the root package AND show me outdated packages) doesn't make any sense. I understand it's not what you meant to ask, but still. So yeah if someone wants to add a warning fine by me, but closing anyway as it's not all that important I think.

**Comment by curry684** [comment]
@Seldaek it made enough for other people to implement the `composer show -oD` combination of flags, also available as `composer outdated -D`, it's already working today  :)   As for the functionality itself, it's the very first thing I want to do when picking up large maintenance on *any* older project: check which major releases of my dependencies have happened and whether I want to include them or not.

We left the bug itself open to track the erroneous behaviour that the `-s --self` flag nukes all other flags silently, which caused the confusion here.

**Comment by stof** [comment]
@curry684 ``-s`` means "show the root package". It is not the same than showing direct dependencies of the root package (which is done by ``-D``).
When displaying the root package itself, most other flags become meaningless as they are about filtering the list of packages, and filtering a list containing only the root package does not make much sense

**Comment by curry684** [comment]
I know, I found the correct flag later on, but while looking for this feature I ran into `--self` first which could have covered my expectation ("show own dependencies").

The only remaining issue is that in my opinion it's a bug, albeit non-severe, that a command can take a flag which is completely ignored because of another flag, and not show a warning or error to that effect, like:

```
$ composer show -s --outdated
-- Warning: ignoring --outdated flag in combination with --self
<rest of info>
```
In the larger scale of things it's a design mistake methinks that such a flag exists, this essentially makes it a command. Right now `composer show`, `composer outdated` and `composer info` (and possibly more) are nearly aliases, giving all of them flags that are at least 'weird' in their separate contexts.

**Comment by stof** [comment]
``info`` is an alias for ``show``, which is why it does the same (it is indeed exactly the same, as can be seen by using ``composer info --help``).

and ``--self`` is documented as ``Show the root package information``, not as ``show own dependencies``

**Comment by Seldaek** [comment]
And sending a warning PR would take less time than bickering about who can
read the docs best :p Jordi out.
