### ISSUE TITLE
Provide ability to update composer.json, without modifying vendor directory

### ISSUE THREAD

**Issue by senguttuvang** [composer/composer#5809]
I recently came across the composer pattern used for dockerized deployment where vendor directory is getting managed within the container, but the composer.json is managed within the local environment.

I'm looking for an option to run composer something like

`composer require Clockwork/Clockwork --skip-vendor `

so it would update the composer.json without actually modifying or even worrying about vendor directory. When I do, `docker-compose up`, vendor dir would automatically get updated within container.

**Comment by xabbuh** [comment]
Looks like you are looking for the `--no-update` option: `composer require --no-update Clockwork/Clockwork`

**Comment by senguttuvang** [comment]
Yes, I'm. I somehow overlooked the documentation. Thank you very much.
