### ISSUE TITLE
Order of ranges in constraint matters (different results for "same" constraint)

### ISSUE THREAD

**Issue by Wirone** [composer/composer#5811]
My problem raised with `phpseclib/phpseclib` which introduced invalid autoloading for 1.* branch and was fixed in 1.0.5 after my reported issue phpseclib/phpseclib#1048. Versions 1.0.3-1.0.4 are invalid from composer's point of view, so I needed to exclude them in my project.

Running Composer v1.2.1. My `composer.json`:

```json
"require": {
    "php": ">=5.5.0",
    "ext-curl": "*",
    "phpseclib/phpseclib": "~1.0,<=1.0.2||>1.0.4"
}
```

Output of `composer diagnose`:

```
require.phpseclib/phpseclib : unbound version constraints (~1.0,<=1.0.2||>1.0.4) should be avoided
```

Semver Checker result:
![image](https://cloud.githubusercontent.com/assets/600668/19644664/568194ac-99f1-11e6-9411-16240c95888e.png)

After `composer update phpseclib/phpseclib` 2.0.4 is installed and it's wrong.

When I change constraint (notice I change only order of ranges):

```
"require": {
    "php": ">=5.5.0",
    "ext-curl": "*",
    "phpseclib/phpseclib": "<=1.0.2||>1.0.4,~1.0"
}
```

I don't have warning in `composer diagnose`, Semver Checker result is:
![composer_phpseclib_inversed](https://cloud.githubusercontent.com/assets/600668/19644746/c44dac28-99f1-11e6-8b81-a1cccb44267d.png)

and version 1.0.5 is installed, which is correct.

Why those constraints are considered different? `,` is treated like logical AND so both constraints should return the same result?

**Comment by alcohol** [comment]
That is because order does matter in this case:

`~1.0,<=1.0.2||>1.0.4` means:

`( >=1.0.0.0 AND < 2.0.0.0 AND <= 1.0.2.0 ) OR ( >=1.0.4.0 )`

`<=1.0.2||>1.0.4,~1.0` means:

`( <=1.0.2.0 ) OR ( > 1.0.4.0 AND > 1.0.0.0 AND <2.0.0.0 )`

**Comment by Wirone** [comment]
But it should be `(>=1.0.0.0 AND <2.0.0.0) AND (<=1.0.2.0 OR >1.0.4.0)`. As far as I understand `,` is separator with [higher precedence](https://getcomposer.org/doc/articles/versions.md#range), so this is not important if it's like above or `(<=1.0.2.0 OR >1.0.4.0) AND (>=1.0.0.0 AND <2.0.0.0)`. Am I wrong?

**Comment by alcohol** [comment]
You are wrong.

**Comment by Wirone** [comment]
How is it possible then to achieve `(>=1.0.0.0 AND <2.0.0.0) AND (<=1.0.2.0 OR >1.0.4.0)` constraint?

**Comment by alcohol** [comment]
I would go with:

```
"require": {
  "foo/bar": "~1.0"
},
"conflicts": {
  "foo/bar": "~1.0.3.0 ~1.0.4.0"
}
```

**Comment by Wirone** [comment]
Ok, that did a trick:

```json
"require": {
    "phpseclib/phpseclib": "~1.0"
},
"conflict": {
    "phpseclib/phpseclib": "1.0.3 - 1.0.4"
},
```

If I require `phpseclib/phpseclib < 1.0.5` Composer installs 1.0.2 :+1: 

PS. `conflict`, not `conflicts` :-)

Thanks!

**Comment by alcohol** [comment]
> PS. `conflict`, not `conflicts` :-)

Correct, my mistake. Thanks.
