### ISSUE TITLE
[ASK] Could not find package global  at any version for your minimum stability

### ISSUE THREAD

**Issue by ad3n** [composer/composer#5815]
When i want to install global package, i always got that message. But i have not got if i use require (without global)

Example: 

- hirak/prestissimo
- alcaues/mongo-db-adapter

**Comment by alcohol** [comment]
Please include the command you are actually running, and the actual output. We cannot help you if you do not tell us what you are doing. Do not provide summaries. Simply copy and paste what you type/run in your terminal and what you get back as output (completely).

**Comment by ad3n** [comment]
Sorry i mistake :-(
