### ISSUE TITLE
Compress cache with tar.gz instead of zip

### ISSUE THREAD

**Issue by rogervila** [composer/composer#5817]
Hello,

The cache folder weight could be reduced by compressing vendors with `.tar.gz` instead of `.zip`
Is it possible to add it as a cross-platform feature?

**Comment by alcohol** [comment]
Since tar is not cross platform, no, not really. We default to this on linux/osx only. On windows, it will be zipped.

Also, please note, that a lot of the files inside the cache dir are zipfiles downloaded directly from github (dist releases). We do not re-archive those. We simply keep them as-is.
