### ISSUE TITLE
Custom repository with type="path" with deep search

### ISSUE THREAD

**Issue by greeny** [composer/composer#5818]
When I add custom repository like this:
```json
"repositories": [
	{
		"type": "path",
		"url": "/var/www/repositories"
	}
]
```

Composer only searches for `composer.json` in that path, but does not consider deeper `composer.json`s, for example `/var/www/repositories/database/composer.json`. Is there any chance of implementing this deep search? Or maybe add a property to repository JSON definition, that will enable deep search?

**Comment by alcohol** [comment]
It's a repositor**y** definition, not repositor**ies**. So, no.

**Comment by greeny** [comment]
I got your point, but this will be very helpful in many cases, when you are splitting big code into smaller services and you don't want to create repositories yet, since you are not sure how will the result code be organized. I think there should be a way to specify directory, where to look (does not have to be in `repositories`)

**Comment by alcohol** [comment]
If you want to have a monolithic repository with sub components, you might want to look at how Symfony does it, or alternatively, give https://github.com/beberlei/composer-monorepo-plugin a try.

**Comment by greeny** [comment]
Thanks for the tips :+1:
