### ISSUE TITLE
Question regarding security

### ISSUE THREAD

**Issue by vanderlee** [composer/composer#5822]
Composer packages, when included in a project, typically contain `readme` files, a `composer.json` and other files which may not be necessary to run the code.

For client-side projects, these files will usually be accessible to the public, and will contain information which can be used to identify the version of the package. This version information may be used to easily identify insecure versions of the package to potential hackers.

Is this a security concern? And if so; is there a way to handle Composer packages so these files that are automatically removed. For instance by allowing the package author to specify which files must __not__ be installed, instead of the default of installing the entire repository.

**Comment by alcohol** [comment]
> For client-side projects, these files will usually be accessible to the public, and will contain information which can be used to identify the version of the package. This version information may be used to easily identify insecure versions of the package to potential hackers.

Are you serious? You are worried that the readme might give away version details? You do realize Composer works entirely based on version constraints? And has a lock file that tracks exactly which version is installed? Knowing versions is key to managing dependencies.

For dist installs (specifically, packages hosted on github), people can exclude files using `.gitattributes` and the `ignore-export` attribute. See https://github.com/thephpleague/iso3166/blob/master/.gitattributes#L11 for example.

**Comment by Seldaek** [comment]
I think it's fair to say that it is a security concern, although mostly a security by obscurity kind of thing. That's also why I advised people in many of my composer talks at conferences to make sure composer.lock is not web-accessible, and ideally the vendor dir also should not be.

It's nothing we can do much about though, it really depends on your project directory layout. Most modern frameworks have a web/ dir or somesuch that is *under* the project root and therefore does not allow leaking info via the web server.

**Comment by curry684** [comment]
Exposing your `vendor` folder to the public is of course pretty much comparable to naming your includes `.php.inc` so the webserver returns your database password as `text/plain`.

*Everything* in a bundle should be protected from the outside world. In not a single project is it defendable to have your `src`, `app`, `tests` or `vendor` folders publicly accessible unchecked.
