### ISSUE TITLE
--prefer-dist doesn't respect commit refs

### ISSUE THREAD

**Issue by danepowell** [composer/composer#5823]
My `composer.json`:

``` json
{
  "minimum-stability": "dev",
  "require": {
    "drupal/simplesamlphp_auth": "8.3.x-dev#283994f",
    "drupal/acquia_lift": "8.3.x-dev#6640cab"
  },
  "repositories": [
    {
      "type": "composer",
      "url": "https://packagist.drupal-composer.org"
    }
  ]
}
```

When I run these commands:

```
composer update
rm -rf vendor
composer install --prefer-dist
```

I get the following output:

```
- Installing drupal/acquia_lift (dev-8.x-3.x 6640cab)
    Loading from cache
- Installing drupal/simplesamlphp_auth (dev-8.x-3.x 283994f)
    Cloning 283994f from cache
```

I would expect that both drupal/acquia_lift and drupal/simplesamlphp_auth are cloned from git, since they both specify a commit ref, and the packaged version for acquia_lift is much newer than the specified commit ref.

A couple notes:
- For simplesamlphp_auth, 283994f actually matches HEAD, and therefore the code in the packaged release. So it seems that the logic for --prefer-dist is actually exactly backwards: it's using the packaged version when it should be cloning from git and vice versa.
- The behavior is slightly different if a local copy of the package already exists. --prefer-dist is a bit "sticky" and will tend to use whatever is already in place, if you already have a source version of a package it will stick to the source version. That's why it's good to remove the vendor directory between tests, as in the testing steps above.

**Comment by alcohol** [comment]
Commit refs are a hack and their behaviour is unspecified. Bugs cannot be filed against them since we do not officially support this "feature".

**Comment by curry684** [comment]
@alcohol I agree with the statement but the [docs do not explicitly say the feature is unsupported](https://getcomposer.org/doc/04-schema.md#package-links), just not advised. I would recommend adding an explicit statement to this extent if policy is not to accept bugs on it.

**Comment by alcohol** [comment]
I will happily accept a docs PR for that.

**Comment by danepowell** [comment]
If commit refs are a hack, what's the proper solution to download a specific Git revision for a package? Is there one? This seems like pretty essential functionality.

**Comment by stof** [comment]
@danepowell stick with versions available properly: branch heads and tags. Packagist does not provide metadata for each commit, and so you cannot require an arbitrary in a clean way (as the solver needs the metadata)

**Comment by stof** [comment]
and if you really need a specific commit in a repo you don't own, you can end up using a ``package`` repository. But be careful about this: it is painful, as the composer.json file will be ignored entirely (you will have to copy it entirely into your repository) and updates to a different commit will be a pain. This should be a last resort (still better than the commit hash installer hack though, as it at least works fine even if it is painful)

**Comment by curry684** [comment]
Bluntly put: if you need a highly specific static version of a package that the maintainer never tagged, and doesn't correspond to a branch, you should likely just download the code at that revision and use that locally. Composer supplies path and package repositories that can fulfill this need fine and reliably. The commit ref functionality is indeed just a hack that conflicts with the most basic principles of dependency management.
