### ISSUE TITLE
Wrong autoload "files" section generated in composer.lock when using exact commit

### ISSUE THREAD

**Issue by trebi** [composer/composer#5835]
Consider a repository `composer-bug-main` (https://github.com/trebi/composer-bug-main) dependng on the exact commit of another repository `composer-bug-dependency`. The `composer.json` of `composer-bug-main` looks like:

```json
{
	"name": "trebi/composer-bug-main",
	"description": "Example demonstrating bug in composer.",
	"authors": [
		{
			"name": "Richard Trebichavský"
		}
	],
	"repositories": [
		{
			"type": "vcs",
			"url": "git@github.com:trebi/composer-bug-dependency.git"
		}
	],	
	"require": {
		"trebi/composer-bug-dependency": "dev-master#2ee39d0109dfad5d0c3641369f681ce7464b035d"
	}
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
The package "trebi/composer-bug-dependency" is pointing to a commit-ref, this is bad practice and can cause unforeseen issues.
require.trebi/composer-bug-dependency : unbound version constraints (dev-master#2ee39d0109dfad5d0c3641369f681ce7464b035d) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer install
```

the `composer.lock` file will be generated. However, the `"files"` section will contain ale files from newest commit: 
```
    "packages": [
        {
            ...
            "autoload": {
                "psr-4": {
                    "Trebi\\": "src/Trebi"
                },
                "files": [
                    "src/Trebi/Foo.php",
                    "src/Trebi/Bar.php"
                ]
            },
            ...
``` 
 But it should contain just `"src/Trebi/Foo.php"`, because it is the only file available in commit `2ee39d0109dfad5d0c3641369f681ce7464b035d` 

My guess is that composer uses a `composer.json` of the newest version of the branch, ignoring the exact commit fixation. 

This is unexpected and wrong - despite that using a `"dev-main#<commit>"` is a bad practice, sometimes it is unavoidable to work with a `dev-master` branch of the dependency (for various reasons - dependency does not have a release yet; there is a fix that you rely on not yet in release etc.)

I use fixation on the exact commit to prevent that my project will suddenly fail if the `master` branch will get updated. But this is exactly what happened here - `master` of the project was updated and my application got broken, because suddnely autoloader was searching for `"src/Trebi/Bar.php"` file which was obviously not there. This is the reason I think it's important to fix this issue, even through there is a warning `unbound version constraints (dev-master#...) should be avoided`

**Comment by alcohol** [comment]
https://getcomposer.org/doc/articles/troubleshooting.md#i-have-locked-a-dependency-to-a-specific-commit-but-get-unexpected-results-
