### ISSUE TITLE
Improve composer version guesser

### ISSUE THREAD

**Issue by lauripiisang** [composer/composer#5841]
From https://github.com/composer/composer/issues/5432#issuecomment-255705637

Current scenario:
When git is in detached head state(and no exact tag match), composer doesn't make any educated guess as to what the closest version might be and comes up with the version 1.0.0.
Desired scenario:
When git is detached head state(and no exact tag match), composer runs git describe --tags to come up with the version dev-1.17.0-11-g4a3ff7c.

@alcohol , here's a manual test. Don't have the time to put together an automated test case at this moment. 

Are there any more questions arising from this?

composer.json:
```
{
    "name": "lauripiisang/testproject",
    "require": {}
}
```
repo: 
```
mkdir testproject
cd testproject 
git init
touch 'README.md' 
git add README.md    
git commit -m 'initial add of README.md. first commit.'       
git tag -a -m 'initial version' 9.0 
touch DEPLOYMENT.md
git add DEPLOYMENT.md
git commit -m 'added DEPLOYMENT.md. second commit.'
echo '{
    "name": "lauripiisang/testproject",
    "require": {}
}' > composer.json
```

I end up with two commits:
```
git log --oneline

106dfc6 added DEPLOYMENT.md. second commit.
e9970a2 initial add of README.md
```

git checkout master  + composer show -s gives expected output of 

`Already on 'master'`
```
name     : lauripiisang/testproject
descrip. : 
keywords : 
versions : * dev-master
type     : library
source   : []  106dfc633aa21d543dac3a086d86e3f8f4a2d18e
dist     : []  106dfc633aa21d543dac3a086d86e3f8f4a2d18e
names    : lauripiisang/testproject
```

git checkout 9.0 + composer show -s gives (mainly) expected output of
```
Note: checking out '9.0'.
...
HEAD is now at e9970a2... initial add of README.md

name     : lauripiisang/testproject
descrip. : 
keywords : 
versions : * 9.0.0.0
type     : library
source   : []  
dist     : []  
names    : lauripiisang/testproject
```

Now, I move from detached tag to master, then to detached head of master's second commit:
```
git checkout master
# git output:  Previous HEAD position was e9970a2... initial add of README.md
# We are now at 106dfc6 - second commit.
# Now let's check out 106dfc6 and end up at a detached head:
git checkout 106dfc6
# Note: checking out '106dfc6'.
# You are in 'detached HEAD' state.
# HEAD is now at 106dfc6... added DEPLOYMENT.md. second commit.
```

Now, I'd expect composer to return at least a best guess of what the verison might be, as git does with `git describe --tags`:`9.0-1-g106dfc6`. Perhaps `dev-9.0-1-g106dfc6`?
Instead, I get 
```
name     : lauripiisang/testproject
descrip. : 
keywords : 
versions : * No version set (parsed as 1.0.0)
type     : library
source   : []  
dist     : []  
names    : lauripiisang/testproject
```

P.S. one thing I'm not touching on here is the lack of source/dist hashes in the last two examples, just ignore those for now -- this is also what I meant by (mainly) expected output. 

For my vision of what should be the final outcome for detached state, I propose:
```
name     : lauripiisang/testproject
descrip. : 
keywords : 
versions : * No version set (parsed as dev-9.0-1-g106dfc6)
type     : library
source   : []  
dist     : []  
names    : lauripiisang/testproject
```

**Comment by alcohol** [comment]
@Seldaek what are your thoughts on this?

**Comment by stof** [comment]
I don't see how this would be useful. ``dev-9.0-1-g106dfc6`` can only satisfy 2 kinds of version constraint for this package:

- a ``*@dev`` requirement (in which case ``1.0.0`` satisfies it as well, while not requirement to change the min stability to ``dev``)
- a requirement for ``dev-9.0-1-g106dfc6`` (which does not make any sense)

So I see no benefit here. The version of the root package itself is useful only for cyclic references implying the root package itself.

**Comment by alcohol** [comment]
Yeah, this spawned from issues arising from cyclic references as discussed in #5432 

I personally do not see much merit in adding changes here just to support cyclic references when COMPOSER_ROOT_VERSION already does the job well enough.

**Comment by Seldaek** [comment]
Yup I don't think this is really an major issue nor do I think we can do much to improve here. We guess when we can, and otherwise you can specify it yourself.

**Comment by glensc** [comment]
note: this also appears when you run composer commands during `git rebase`:
- https://github.com/Ocramius/PackageVersions/issues/84
