### ISSUE TITLE
[Docs] Maybe package stability should be explained a bit further

### ISSUE THREAD

**Issue by fabschurt** [composer/composer#5848]
Hi folks,

This is a documentation enhancement proposal.

One thing that I’ve had a hard time to wrap my head around with Composer is package stability. Only recently have I truly understood that `stable` versions are taken from normal version-like VCS tags, and that `dev` versions are taken from VCS branches AND suffixed version-like VCS tags (`-patch`, `-alpha` and so on).

Reading Composer’s documentation again, I think this distinction is not really explicit, yet it’s a very important part for people to understand in my opinion.

Would it be of any interest if I submitted a PR that would try to make this a bit clearer?

**Comment by stof** [comment]
Your explanation is actually wrong.

Composer has 5 stability levels for packages:

- ``stable`` for tags matching a version number
- ``RC`` for ``rc`` tags
- ``beta`` for ``beta`` tags
- ``alpha`` for ``alpha`` tags
- ``dev`` for VCS branches

These stability levels are ordered. And when specifying a constraint, what you give after the ``@`` is the **minimum** stability (overwriting the global ``minimum-stability`` configuration.
So ``@dev`` means "you can use any package being *at least* at dev stability".

This does not mean that ``1.2.0-alpha1`` will be a dev version (it is not, it is an alpha version). But it means that such version can fulfill a requirement when the min stability is ``dev``

**Comment by fabschurt** [comment]
Oh, right. That’s in fact well explained in the [Composer schema reference](https://getcomposer.org/doc/04-schema.md#minimum-stability). For whatever reason, I thought that `minimum-stability` only accepted either `dev` or `stable` as a value, leading me to believe that `dev` was «everything that is not stable». It worked in practise, but I didn’t know that we could specify intermediary stability tags.

Okay well, nevermind 😅 I’m closing this.

**Comment by stof** [comment]
The last paragraph of this doc displays the list of available options though. So I don't even think there is a need to update the doc
