### ISSUE TITLE
Ambiguous class resolution is different between default and optimized autoloader-creation

### ISSUE THREAD

**Issue by heiglandreas** [composer/composer#5849]
My `composer.json`:

```json
{
    "require": {
        "smarty/smarty": "v3.1.16",
        "buggedcom/phpvideotoolkit": "2.2.1",
        "zendframework/zendframework1": "^1.12",
        "php-amqplib/php-amqplib": "^2.2",
        "org_heigl/tokenizer": "dev-master",
        "org_heigl/filefinder": "^1.1",
        "ezyang/htmlpurifier": "dev-master",
        "phpunit/dbunit": "^1.4",
        "org_heigl/converter": "dev-master",
        "reprovinci/solr-php-client": "^1.0",
        "guzzle/guzzle": "^3.0",
        "wdv_mdv/file-preview": "^1.0",
        "org_heigl/color": "dev-master"
    },
    "prefer-stable" : true,
    "repositories": [
        {
            "type": "composer",
            "url": "[URL to private satis-instance]",
            "options" : {
                "ssl" : {
                    "cafile" : "share/certs/pubkey.pem"
                }
            }
        }
    ],
    "autoload": {
        "classmap" : [
            "lib/zf",
            "lib/symfony",
            "lib/fmandphp",
            "app/model",
            "app/modules",
            "app/forms",
            "lib/xmpphp",
            "lib/browserdetection",
            "lib/other",
            "app/modules/dl/lib",
            "app/modules/notification/lib"
        ]
    },
    "include-path": [
        "lib/zf",
        "lib/symfony",
        "lib/fmandphp",
        "lib/xmpphp",
        "app/model",
        "app/forms",
        "app/modules",
        "lib/browserdetection",
        "lib/other",
        "app/modules/dl/lib",
        "app/modules/notification/lib"
    ],
    "require-dev": {
        "phing/phing": "~2.10",
        "mockery/mockery": "0.9.*",
        "phpdocumentor/phpdocumentor": "~2.8",
        "sebastian/phpcpd": "~2.0",
        "phpmd/phpmd": "~2.2",
        "pdepend/pdepend": "~2.0",
        "phploc/phploc": "~2.1",
        "phpunit/phpunit": "~4.5|^5.0",
        "phpunit/dbunit": "~1.3"
    }
}
```

Output of `composer diagnose`:

```
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
phpunit/dbunit is required both in require and require-dev, this can lead to unexpected behavior
require.smarty/smarty : exact version constraints (v3.1.16) should be avoided if the package follows semantic versioning
require.buggedcom/phpvideotoolkit : exact version constraints (2.2.1) should be avoided if the package follows semantic versioning
require.org_heigl/tokenizer : unbound version constraints (dev-master) should be avoided
require.ezyang/htmlpurifier : unbound version constraints (dev-master) should be avoided
require.org_heigl/converter : unbound version constraints (dev-master) should be avoided
require.org_heigl/color : unbound version constraints (dev-master) should be avoided
Checking platform settings: WARNING
The xdebug extension is loaded, this can slow down Composer a little.
 Disabling it when using Composer is recommended.

Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: WARNING
You are not running the latest stable version, run `composer self-update` to update (1.2.1 => 1.2.2)```

When I run this command:

```
composer dumpautoload -o
```

I get the following output:

```
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Generating optimized autoload files
Warning: Ambiguous class resolution, "PHPVideoToolkit\VideoFormat_Wmv" was found in both "[docroot]/vendor/buggedcom/phpvideotoolkit/src/PHPVideoToolkit/VideoFormat/Wmv.php" and "[docroot]/vendor/buggedcom/phpvideotoolkit/src/PHPVideoToolkit/VideoFormat/Wmv3.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Locale" was found in both "[docroot]/vendor/zendframework/zendframework1/library/Zend/Locale.php" and "[docroot]/lib/zf/Zend/Locale.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Date" was found in both "[docroot]/vendor/zendframework/zendframework1/library/Zend/Date.php" and "[docroot]/lib/zf/Zend/Date.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Version" was found in both "[docroot]/vendor/zendframework/zendframework1/library/Zend/Version.php" and "[docroot]/lib/zf/Zend/Version.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Locale_Data_Translation" was found in both "[docroot]/vendor/zendframework/zendframework1/library/Zend/Locale/Data/Translation.php" and "[docroot]/lib/zf/Zend/Locale/Data/Translation.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Locale_Math_PhpMath" was found in both "[docroot]/vendor/zendframework/zendframework1/library/Zend/Locale/Math/PhpMath.php" and "[docroot]/lib/zf/Zend/Locale/Math/PhpMath.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Locale_Math_Exception" was found in both "[docroot]/vendor/zendframework/zendframework1/library/Zend/Locale/Math/Exception.php" and "[docroot]/lib/zf/Zend/Locale/Math/Exception.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Locale_Data" was found in both "[docroot]/vendor/zendframework/zendframework1/library/Zend/Locale/Data.php" and "[docroot]/lib/zf/Zend/Locale/Data.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Locale_Exception" was found in both "[docroot]/vendor/zendframework/zendframework1/library/Zend/Locale/Exception.php" and "[docroot]/lib/zf/Zend/Locale/Exception.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Locale_Format" was found in both "[docroot]/vendor/zendframework/zendframework1/library/Zend/Locale/Format.php" and "[docroot]/lib/zf/Zend/Locale/Format.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Locale_Math" was found in both "[docroot]/vendor/zendframework/zendframework1/library/Zend/Locale/Math.php" and "[docroot]/lib/zf/Zend/Locale/Math.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Date_Cities" was found in both "[docroot]/vendor/zendframework/zendframework1/library/Zend/Date/Cities.php" and "[docroot]/lib/zf/Zend/Date/Cities.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Date_DateObject" was found in both "[docroot]/vendor/zendframework/zendframework1/library/Zend/Date/DateObject.php" and "[docroot]/lib/zf/Zend/Date/DateObject.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Date_Exception" was found in both "[docroot]/vendor/zendframework/zendframework1/library/Zend/Date/Exception.php" and "[docroot]/lib/zf/Zend/Date/Exception.php", the first will be used.
```

but when I run

```
composer dumpautoload
```

I get the following output:

```
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Generating autoload files
```

I would expect both outputs to be the same.

I would at least expect the class-resolution to prefer the version in my project over the version from the vendor-folder. There surely are reasons why I choose to overwrite a class from a vendor within my own project.

**Comment by heiglandreas** [comment]
Classmap excerpt from ```composer dumpautoload```

```
    'Zend_Date' => $baseDir . '/lib/zf/Zend/Date.php',
    'Zend_Date_Cities' => $baseDir . '/lib/zf/Zend/Date/Cities.php',
    'Zend_Date_DateObject' => $baseDir . '/lib/zf/Zend/Date/DateObject.php',
    'Zend_Date_Exception' => $baseDir . '/lib/zf/Zend/Date/Exception.php',
```

Classmap excerpt from ```composer dumpautoload -a```

```
    'Zend_Date' => $vendorDir . '/zendframework/zendframework1/library/Zend/Date.php',
    'Zend_Date_Cities' => $vendorDir . '/zendframework/zendframework1/library/Zend/Date/Cities.php',
    'Zend_Date_DateObject' => $vendorDir . '/zendframework/zendframework1/library/Zend/Date/DateObject.php',
    'Zend_Date_Exception' => $vendorDir . '/zendframework/zendframework1/library/Zend/Date/Exception.php',
```

Due to the classloader first resolving via the classmap the result for autoloading ```Zend_Date``` with the ```composer dumpautoload```-data will load the class from the applications folder and not from the vendor folder. So an overwritten (Monkey-Patched) file will be used which should be the intended behaviour.

As the ```composer dumpautoload -a``` results in an autoloader with *only* a classmap - and that classmap not containing the class from the applications folder - the class from the vendor folder will be loaded which is not overwritten and might break the application-logic due to the missing patch.

Shouldn't both ways resolve to the same file (whether thats the application or the vendor one is a different thing) under such circumstances?

**Comment by alcohol** [comment]
Please clarify if you are differentiating between `-o` or `-a`. These options are not one and the same, but yet your first example uses `-o` and your second example speaks of `-a`.

**Comment by heiglandreas** [comment]
I'm talking about ```-o``` in both cases. But in the second example the outcome is identical for ```composer dumpautoload -o``` and ```composer dumpautoload -a```. It's both times 

```
    'Zend_Date' => $vendorDir . '/zendframework/zendframework1/library/Zend/Date.php',
    'Zend_Date_Cities' => $vendorDir . '/zendframework/zendframework1/library/Zend/Date/Cities.php',
    'Zend_Date_DateObject' => $vendorDir . '/zendframework/zendframework1/library/Zend/Date/DateObject.php',
    'Zend_Date_Exception' => $vendorDir . '/zendframework/zendframework1/library/Zend/Date/Exception.php',
```

And the message I get from ```composer dumpautoload -o``` and ```composer dumpautoload -a``` is also the same:

```
Generating optimized autoload files
Warning: Ambiguous class resolution, "PHPVideoToolkit\VideoFormat_Wmv" was found in both "/var/www/compass-testsystem.wdv.de/vendor/buggedcom/phpvideotoolkit/src/PHPVideoToolkit/VideoFormat/Wmv.php" and "/var/www/compass-testsystem.wdv.de/vendor/buggedcom/phpvideotoolkit/src/PHPVideoToolkit/VideoFormat/Wmv3.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Locale" was found in both "/var/www/compass-testsystem.wdv.de/vendor/zendframework/zendframework1/library/Zend/Locale.php" and "/var/www/compass-testsystem.wdv.de/lib/zf/Zend/Locale.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Date" was found in both "/var/www/compass-testsystem.wdv.de/vendor/zendframework/zendframework1/library/Zend/Date.php" and "/var/www/compass-testsystem.wdv.de/lib/zf/Zend/Date.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Version" was found in both "/var/www/compass-testsystem.wdv.de/vendor/zendframework/zendframework1/library/Zend/Version.php" and "/var/www/compass-testsystem.wdv.de/lib/zf/Zend/Version.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Locale_Data_Translation" was found in both "/var/www/compass-testsystem.wdv.de/vendor/zendframework/zendframework1/library/Zend/Locale/Data/Translation.php" and "/var/www/compass-testsystem.wdv.de/lib/zf/Zend/Locale/Data/Translation.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Locale_Math_PhpMath" was found in both "/var/www/compass-testsystem.wdv.de/vendor/zendframework/zendframework1/library/Zend/Locale/Math/PhpMath.php" and "/var/www/compass-testsystem.wdv.de/lib/zf/Zend/Locale/Math/PhpMath.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Locale_Math_Exception" was found in both "/var/www/compass-testsystem.wdv.de/vendor/zendframework/zendframework1/library/Zend/Locale/Math/Exception.php" and "/var/www/compass-testsystem.wdv.de/lib/zf/Zend/Locale/Math/Exception.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Locale_Data" was found in both "/var/www/compass-testsystem.wdv.de/vendor/zendframework/zendframework1/library/Zend/Locale/Data.php" and "/var/www/compass-testsystem.wdv.de/lib/zf/Zend/Locale/Data.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Locale_Exception" was found in both "/var/www/compass-testsystem.wdv.de/vendor/zendframework/zendframework1/library/Zend/Locale/Exception.php" and "/var/www/compass-testsystem.wdv.de/lib/zf/Zend/Locale/Exception.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Locale_Format" was found in both "/var/www/compass-testsystem.wdv.de/vendor/zendframework/zendframework1/library/Zend/Locale/Format.php" and "/var/www/compass-testsystem.wdv.de/lib/zf/Zend/Locale/Format.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Locale_Math" was found in both "/var/www/compass-testsystem.wdv.de/vendor/zendframework/zendframework1/library/Zend/Locale/Math.php" and "/var/www/compass-testsystem.wdv.de/lib/zf/Zend/Locale/Math.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Date_Cities" was found in both "/var/www/compass-testsystem.wdv.de/vendor/zendframework/zendframework1/library/Zend/Date/Cities.php" and "/var/www/compass-testsystem.wdv.de/lib/zf/Zend/Date/Cities.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Date_DateObject" was found in both "/var/www/compass-testsystem.wdv.de/vendor/zendframework/zendframework1/library/Zend/Date/DateObject.php" and "/var/www/compass-testsystem.wdv.de/lib/zf/Zend/Date/DateObject.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Date_Exception" was found in both "/var/www/compass-testsystem.wdv.de/vendor/zendframework/zendframework1/library/Zend/Date/Exception.php" and "/var/www/compass-testsystem.wdv.de/lib/zf/Zend/Date/Exception.php", the first will be used.
```

So even though those both options are not the same, they seem to have the same output in this specific case.

**Comment by alcohol** [comment]
Afaik, `-a` implies `-o` also because without it, it would not work, so that would make sense.

I am not sure what problem you are reporting though. The messages are quite clear and the behavior is as expected.

**Comment by alcohol** [comment]
Just to clarify, this not a feature nor "intended behavior" that one should rely upon. Ambiguous classes are bad, whether you optimize the classmap or not. They indicate a problem that you should address. Using these effects to implement a monkey patch is entirely at your own risk and you should take into account that we simply do not support this.

**Comment by heiglandreas** [comment]
The behaviour is not as expected because when I run ```composer dumpautoload``` a call to ```Zend_Date``` will be resolved to ```[docroot]/lib/zf/Zend/Date.php``` whereas after a call to ```composer dumpautoload -a```` or ```composer dumautoload -o``` it resolves to ```[docroot]/vendor/zendframework/zendframework1/library/Zend/Date.php```

Expected behaviour would be that in both cases the class would be resolved to the **same**  file.

Beneath that, when running ```composer dumpautoload``` there is **no information** about ambiguous class-resolution, so I'm not even aware that there is an issue! (Have a look at the resolution for PHPVideoToolkit\VideoFormat_Wmv in the first line which is caused by a library that I don't even have access to)

This is about consistency! Currently resolving of classes is dependent on how dumpautoload is called and I might not even be aware of monkey-patches as I might not even get informations about ambiguous resolutions.

**Comment by heiglandreas** [comment]
And *when* there is an ambiguous class, there *should* be a common way how to resolve that ambiguity.

**Comment by alcohol** [comment]
> Expected behaviour would be that in both cases the class would be resolved to the same file.

Having expectations regarding something that is explicitly not supported, is like expecting Santa Claus to be real. You can expect all you want, it is not going to the change the facts.

**Comment by heiglandreas** [comment]
So it is **intended behaviour** that resolution differs between ```composer dumpautoload``` and ```composer dumpautoload -o``` and ```composer dumpautoload -a```?

**Comment by alcohol** [comment]
No, the behavior is **undefined** and that will not change because this is simply not supported. You should not have duplicate ambiguous classes.

**Comment by heiglandreas** [comment]
This is a conjunctive. I know I *should* not have them. But life is life and - citing yourself - "you can expect all you want, it's not going to change the facts" There will be cases where there are abiguous classes.

By not defining an intended behaviour you make the current - undefined - behaviour the intended one. It's either intended or not. If it's not defined then the easiest thing is to define it.

**Comment by alcohol** [comment]
From a technical perspective, when you optimize during dumping the autoloading files, Composer will expand all classmap, psr0 and psr4 definitions. By expand, I mean that it will try to find all files and classes that match. When it encounters the same class in multiple files, it will warn you about this and use the first one found, ignoring any duplicates that follow it.

When you do not optimize the classmap (which is something you should do in almost all cases except during development perhaps), we simply do not know what classes exist and therefor we cannot warn you about this.

Run `-o`, find your problems, fix them.

**Comment by alcohol** [comment]
> By not defining an intended behaviour you make the current - undefined - behaviour the intended one. It's either intended or not. If it's not defined then the easiest thing is to define it.

I strongly disagree. By defining the behavior, we turn a explicitly not supported use-case into a supported use-case.

**Comment by Seldaek** [comment]
@alcohol is correct in the sense that indeed we can not warn about something we do not see, so the warning is "undefined behavior" perhaps and it won't warn you about clashes in non-optimized mode. 

That said, we do explicitly support package priorities in autoloading, and AFAIK we do load classes in the local project in priority over those in dependencies, specifically to allow such overrides if you use a similar or more specific PSR-4 namespace than the target package you want to override. So if we do that in PSR-4 mode, we should also do it in classmap-optimized mode, and make sure that we optimize the root package first so that clashing classes in dependencies get ignored and not the reverse. In that sense it sounds like a bug to me.

**Comment by alcohol** [comment]
@Seldaek why wouldn't it do that in optimized mode..? Afaik we gather and merge all the autoload definitions before optionally optimizing them? So how can the order be different?

**Comment by alcohol** [comment]
Actually, we `krsort()` only inside the optimize block. This is possibly how project local code could end up after vendor specific code?

**Comment by alcohol** [comment]
Oh, but @heiglandreas doesn't use psr0/psr4. So his classmap definitions get expanded after all psr0/psr4 definitions.

**Comment by alcohol** [comment]
Changing the order of processing here though would technically constitute a BC break. So while it might make some people happy, it could break builds all over the place for people who rely on the other side of the "expected behavior".

Hence my argument, that this should explicitly not be supported and people just need to accept that and fix their crap.

**Comment by Seldaek** [comment]
Yeah that's one problem I noticed that we probably don't handle this very well across different autoload types. I think we handle it well if you use the same autoload type than the stuff you want to override, but otherwise they might end up out of order. Ideally we'd process all the rules of every package in the right order, package by package not rule type by rule type.

Please stop calling stuff crap and unsupported, it's not helping anything. It is supported, it just has limitations, we either fix those limitations or we document them clearly and decide they can be lived with.

**Comment by heiglandreas** [comment]
Thanks @Seldaek for the clear words. I'm not complaining about my code not working, I try to point out an inconsistency. I never said it should work this or that way (I'd prefer one, but that's not the issue here), I'd just prefer it'd either work in a consistent way **or** be clearly documented that it isn't. There's not even a need for why it isn't.

**Comment by alcohol** [comment]
@Seldaek How is it supported? Just because it happens to work if everything would always be processed in the same order? I disagree. If this is a feature or functionality that people want, then it should be explicitly implemented as such. E.g. a monkey-patching autoloader that always picks a specific implementation of the class requested. Depending on the order in which you defined your autoloading definitions is really not a "feature". This is more like the #commit-ref hack if anything else. It happens to work, and some people might find a use-case for it, but that does not mean we have to support it, nor do we have to address any issues from misuse or abuse of it. That is simply my opinion. I do not expect you to agree, but that should go both ways.

**Comment by Seldaek** [comment]
I don't expect you to agree, I just expect you to be respectful. And yes this is supported because we explicitly built it to work this way over the years. This particular case wasn't thought through however so it doesn't work here but it should IMO, the question is whether fixing it makes a huge mess or not, if yes maybe we need to live with the limitation/inconsistency.

**Comment by Koc** [comment]
@Seldaek 

I have same warning and my project stops working

```
Warning: Ambiguous class resolution, "Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-migrations-bundle/Command/MigrationsMigrateDoctrineCommand.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-migrations-bundle/Doctrine/Bundle/MigrationsBundle/Command/MigrationsMigrateDoctrineCommand.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\MigrationsBundle\DependencyInjection\Configuration" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-migrations-bundle/Doctrine/Bundle/MigrationsBundle/DependencyInjection/Configuration.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-migrations-bundle/DependencyInjection/Configuration.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\MigrationsBundle\DependencyInjection\DoctrineMigrationsExtension" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-migrations-bundle/Doctrine/Bundle/MigrationsBundle/DependencyInjection/DoctrineMigrationsExtension.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-migrations-bundle/DependencyInjection/DoctrineMigrationsExtension.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-migrations-bundle/Doctrine/Bundle/MigrationsBundle/DoctrineMigrationsBundle.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-migrations-bundle/DoctrineMigrationsBundle.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\DoctrineCacheBundle\Command\CacheCommand" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Command/CacheCommand.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Doctrine/Bundle/DoctrineCacheBundle/Command/CacheCommand.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\DoctrineCacheBundle\Command\DeleteCommand" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Command/DeleteCommand.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Doctrine/Bundle/DoctrineCacheBundle/Command/DeleteCommand.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\DoctrineCacheBundle\Command\ContainsCommand" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Command/ContainsCommand.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Doctrine/Bundle/DoctrineCacheBundle/Command/ContainsCommand.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\DoctrineCacheBundle\Command\StatsCommand" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Command/StatsCommand.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Doctrine/Bundle/DoctrineCacheBundle/Command/StatsCommand.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\DoctrineCacheBundle\Command\FlushCommand" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Command/FlushCommand.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Doctrine/Bundle/DoctrineCacheBundle/Command/FlushCommand.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\DoctrineCacheBundle\DependencyInjection\Configuration" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Doctrine/Bundle/DoctrineCacheBundle/DependencyInjection/Configuration.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/DependencyInjection/Configuration.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\DoctrineCacheBundle\DependencyInjection\DoctrineCacheExtension" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Doctrine/Bundle/DoctrineCacheBundle/DependencyInjection/DoctrineCacheExtension.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/DependencyInjection/DoctrineCacheExtension.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\DoctrineCacheBundle\DependencyInjection\Definition\RiakDefinition" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Doctrine/Bundle/DoctrineCacheBundle/DependencyInjection/Definition/RiakDefinition.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/DependencyInjection/Definition/RiakDefinition.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\DoctrineCacheBundle\DependencyInjection\Definition\MemcachedDefinition" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Doctrine/Bundle/DoctrineCacheBundle/DependencyInjection/Definition/MemcachedDefinition.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/DependencyInjection/Definition/MemcachedDefinition.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\DoctrineCacheBundle\DependencyInjection\Definition\PhpFileDefinition" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Doctrine/Bundle/DoctrineCacheBundle/DependencyInjection/Definition/PhpFileDefinition.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/DependencyInjection/Definition/PhpFileDefinition.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\DoctrineCacheBundle\DependencyInjection\Definition\CouchbaseDefinition" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Doctrine/Bundle/DoctrineCacheBundle/DependencyInjection/Definition/CouchbaseDefinition.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/DependencyInjection/Definition/CouchbaseDefinition.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\DoctrineCacheBundle\DependencyInjection\Definition\FileSystemDefinition" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Doctrine/Bundle/DoctrineCacheBundle/DependencyInjection/Definition/FileSystemDefinition.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/DependencyInjection/Definition/FileSystemDefinition.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\DoctrineCacheBundle\DependencyInjection\Definition\RedisDefinition" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Doctrine/Bundle/DoctrineCacheBundle/DependencyInjection/Definition/RedisDefinition.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/DependencyInjection/Definition/RedisDefinition.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\DoctrineCacheBundle\DependencyInjection\Definition\MongodbDefinition" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Doctrine/Bundle/DoctrineCacheBundle/DependencyInjection/Definition/MongodbDefinition.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/DependencyInjection/Definition/MongodbDefinition.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\DoctrineCacheBundle\DependencyInjection\Definition\MemcacheDefinition" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Doctrine/Bundle/DoctrineCacheBundle/DependencyInjection/Definition/MemcacheDefinition.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/DependencyInjection/Definition/MemcacheDefinition.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\DoctrineCacheBundle\DependencyInjection\Definition\CacheDefinition" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Doctrine/Bundle/DoctrineCacheBundle/DependencyInjection/Definition/CacheDefinition.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/DependencyInjection/Definition/CacheDefinition.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\DoctrineCacheBundle\DependencyInjection\SymfonyBridgeAdapter" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Doctrine/Bundle/DoctrineCacheBundle/DependencyInjection/SymfonyBridgeAdapter.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/DependencyInjection/SymfonyBridgeAdapter.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\DoctrineCacheBundle\DependencyInjection\CacheProviderLoader" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Doctrine/Bundle/DoctrineCacheBundle/DependencyInjection/CacheProviderLoader.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/DependencyInjection/CacheProviderLoader.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Doctrine/Bundle/DoctrineCacheBundle/DoctrineCacheBundle.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/DoctrineCacheBundle.php", the first will be used.
Warning: Ambiguous class resolution, "Doctrine\Bundle\DoctrineCacheBundle\Acl\Model\AclCache" was found in both "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Doctrine/Bundle/DoctrineCacheBundle/Acl/Model/AclCache.php" and "/data/www/ololo.trololo/vendor/doctrine/doctrine-cache-bundle/Acl/Model/AclCache.php", the first will be used.
```

Looks like libraries duplitates in multiple folders and when autoloads generates - it takes wrong (old version of files). As workaround I've executed `rm -rf vendors` and run `composer install` again. Why old version of vendors are not removed properly?

**Comment by stof** [comment]
@Koc this looks like doing a mess when updating the package from the old version using target-dir to the newer version not using target-dir (i.e. not removing the old version before installing the new one). Can be solved with dropping your vendor folder and then running ``composer install``.

**Comment by Seldaek** [comment]
@heiglandreas I had a closer look here and this is very hard to fix cleanly tbh.. I don't think it's worth it. The current approach taken basically prefers psr-4/psr-0 rules to classmap ones when running optimizations, so the problem really is that you are using classmap autoloading while the package you are trying to override uses psr-0. In this case, your classmap wins in dev because classmap has higher prio in the autoloader, but in prod with optimized autoloader the psr-0 rules end up having priority in the classmap, and then it fails.

If you use the same type of autoloading as the package you are overriding though, this problem doesn't happen. So the best way to fix it for you is to change that classmap autoloading and instead use this:

```json
    "autoload": {
        "psr-0": {
            "Zend_": "lib/zf"
        }
    }
```

Then it'll load your file even in optimized mode.

**Comment by heiglandreas** [comment]
Thanks @Seldaek for digging into this. I think you are right about the effort outweighting the gain from "fixing" this. The clean solution looks like not relying on classmaps in the first place. 

For me that's fine. Thanks for your effort!!
