### ISSUE TITLE
Replace required packages from other library

### ISSUE THREAD

**Issue by noplanman** [composer/composer#5850]
What is the best way to override/replace a required dependency from another library?

My use case, without going into too much detail:
I'm using composer to import libraries that I need for a WordPress plugin. Since WordPress itself already implements a whole bunch of functionality, some required packages from the libraries I'm using aren't compatible, or rather, their functionality is already implemented in a way that would generate conflicts.
So basically, I need to replace those required libraries with a dummy, as no functionality will go lost.

At the moment I'm doing it like so:
```json
"repositories": [
    {
        "type": "git",
        "url": "https://github.com/noplanman/composer-wp-package-replacements.git"
    }
],
"require": {
    "php": "^5.5|^7.0",
    "noplanman/composer-wp-package-replacements": "@dev",
    "spomky-labs/otphp": "^8.2"
}
```

In the linked repository I then replace any packages that need dummy-ing out.

After some playing around, I found that it's also possible to use a dummy zip archive with an empty `composer.json` file in it, like so:

```json
"repositories": [
    {
        "type" : "package",
        "package" : {
            "name" : "_dummy/wp",
            "description": "Replace any required packages with a dummy.",
            "replace" : {
                "paragonie/random_compat" : "*"
            },
            "version" : "dev-master",
            "dist": {
                "type": "zip",
                "url": ".wp_composer_dummy.zip"
            }
        }
    }
],
"require": {
    "php": "^5.5|^7.0",
    "_dummy/wp": "@dev",
    "spomky-labs/otphp": "^8.2"
}
```

But this also seems like an unpretty hack.

Is there any *nice* way of doing this?

**Comment by alcohol** [comment]
Define "nice".

**Comment by noplanman** [comment]
Good question... I just feel like the way I've solved it is very hackish and not the way it should be done, but maybe it's the exact way.
So I'm rather asking if there is a better, more integrated way of doing it, or if overriding (or dummy-ing out) required packages is by definition a hack.

Does that make more sense?

**Comment by stof** [comment]
Well, using the ``replace`` feature for that is exactly the way to go (if you don't want to download a dummy zip, use a metapackage instead, by using ``type: metapackage``)

**Comment by stof** [comment]
but anyway, dummy-ing out required packages indeed looks like a hack by definition (doing it requires you to understand exactly why it is required, to be sure to provide the same feature exactly)

**Comment by noplanman** [comment]
> be sure to provide the same feature exactly

I'm totally aware of that, but thanks for pointing it out again to make sure.

How does the `metapackage` type work? I didn't find any example in the docs.
Could you maybe send a simple little example for me to understand?

**Comment by alcohol** [comment]
See https://github.com/dmstr/yii2-cms-metapackage

In this case it is a package that has a bunch of requirements (the metapackage is used simply to bundle them). In your case, you could make it a replace instead.

**Comment by noplanman** [comment]
Ok, well that was easy, just add `"type": "metapackage"` instead of the `"dist"` block 👍 

```json
"repositories": [
    {
        "type": "package",
        "package": {
            "type": "metapackage",
            "name": "_dummy/wp",
            "description": "Replace any required packages with a dummy.",
            "version": "dev-master",
            "replace": {
                "paragonie/random_compat": "*"
            }
        }
    }
],
"require": {
    "_dummy/wp": "@dev",
}
```

Thanks for the tip on the `metapackage` type 🎉
