### ISSUE TITLE
how to run composer script as interactive shell mode?

### ISSUE THREAD

**Issue by yozman** [composer/composer#5856]
hey guys,

I required `psy/psysh` with composer,
and define a script like
```json
"scripts": {
  "fly": "vendor/bin/psysh"
}
```

when I run `composer fly`
it runs and exit automatic
`composer exec psysh`
is also the same problem,
only `php vendor/bin/psysh` works.

how can I fix it?

By the way this is `psysh` author's answer,
https://github.com/bobthecow/psysh/issues/328#issuecomment-258663553
he said composer script is running under a non-interactive mode
could you please help me?

**Comment by alcohol** [comment]
We do not use `passthru`. So this is simply not possible.

**Comment by yozman** [comment]
@alcohol 
so could you please add that feature

**Comment by alcohol** [comment]
That is not really an option. We generally use the `symfony/process` component for all processes. They do not make use of `passthru`, so no.

**Comment by greg-1-anderson** [comment]
This could potentially be supported by using `$process->setTty(true);`.

See: https://github.com/symfony/symfony/issues/17010

I don't believe Composer scripts capture the script output; if this is the case, then tty mode could be made the default.

**Comment by greg-1-anderson** [comment]
Actually, on further reflection, it is likely that there scripts that depend on the current behavior. When not running with a tty, Symfony console applications will run in non-interactive mode. If a tty were added by default, then interactive mode would be used. This could cause problems in some scenarios - e.g. an application that prompts the user in a failure situation could be successfully exiting immediately with an error. Changing Composer to use a tty by default would require the user to change their command from `composer my-script` to `composer -n my-script`, or the script would start blocking on user input.

Overall, I think using `setTty` would be useful, but I thought it would be prudent to consider this edge case.

**Comment by alcohol** [comment]
@Seldaek perhaps something to consider for a future release (maybe even as far as 2.x)?

**Comment by Seldaek** [comment]
Worth exploring for 2.0 yeah.

**Comment by Artusamak** [comment]
I'm :+1: ing it would definitely be beneficial to support interactive scripts since we also have a --no-interaction flag that is supposed to be helpful to disable interactivity.

Thank you for your work.

**Comment by Artusamak** [comment]
Related to #5856 also.

**Comment by neelbhanushali** [comment]
Can use this
https://pantheon.io/blog/writing-composer-scripts

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/commit/f5726366286b9e2765dfe4947fa825701f306737 for 2.0
