### ISSUE TITLE
PHP Fatal Error : Out Of Memory Windows 10

### ISSUE THREAD

**Issue by omer-sds** [composer/composer#5859]
My `composer.json`:

```json
...{
    "name": "nenad/yii2-advanced-template",
    "description": "Improved Yii 2 Advanced Application Template By Nenad Zivkovic",
    "keywords": ["yii2", "framework", "advanced", "improved", "application template", "nenad"],
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "tutorial": "http://www.freetuts.org/tutorial/view?id=6",
        "source": "https://github.com/nenad-zivkovic/yii2-advanced-template"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "*",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "nenad/yii2-password-strength": "*",
        "mihaildev/yii2-ckeditor": "*",
        "mdmsoft/yii2-admin":"*"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*",
        "codeception/specify": "*",
        "codeception/verify": "*",
       
    },
    "config": {
        "vendor-dir": "_protected/vendor",
        "process-timeout": 1800
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "_protected/vendor/npm",
            "bower-asset-library": "_protected/vendor/bower"
        }
    }
}
...
```

Output of `composer diagnose`:

```
...Checking composer.json: WARNING
require.yiisoft/yii2 : unbound version constraints (*) should be avoided
require.yiisoft/yii2-bootstrap : unbound version constraints (*) should be avoided
require.yiisoft/yii2-swiftmailer : unbound version constraints (*) should be avoided
require.nenad/yii2-password-strength : unbound version constraints (*) should be avoided
require.mihaildev/yii2-ckeditor : unbound version constraints (*) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK...
```

When I run this command:

```
...php composer.phar update...
```

I get the following output:

```
...Loading composer repositories with package information
Updating dependencies (including require-dev)
PHP Fatal error:  Out of memory (allocated 1966080000) (tried to allocate 32 bytes) in phar://F:/xampp/htdocs/Nxb/nxbrankings/composer.phar/src/Composer/DependencyResolver/Rule.php on line 60

Fatal error: Out of memory (allocated 1966080000) (tried to allocate 32 bytes) in phar://F:/xampp/htdocs/Nxb/nxbrankings/composer.phar/src/Composer/DependencyResolver/Rule.php on line 60...
```

everything was working perfect then i ran update on composer 4 days ago and still the same, even used -1 as memory limit , by setting in the php.ini , i am using windows 10 64-bit with xampp, my php version details 

`PHP 5.6.21 (cli) (built: Apr 27 2016 20:13:54)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies`

**Comment by alcohol** [comment]
How much RAM do you have?

**Comment by omer-sds** [comment]
Antec Gigabyte core i7 16 GB Ram

**Comment by eved42** [comment]
Hello,

I had the same problem after updating composer to last version when I tried to install a bundle in Symfony 3.1.
Before update, I had no problem.

Command line : `$ composer require oneup/uploader-bundle "~1.4"`
Error : `PHP Fatal error: Allowed memory size of 1073741824 bytes exhausted <...>`

(I use my local CLI with PHP 5.6.16)

I solved my problem by running : 
```
$ cd path\of\my\project
$ php -d memory_limit=-1 C:\path\of\composer\ComposerSetup\bin\composer.phar require oneup/uploader-bundle "~1.4"
```

But it is not very convenient to do this every time I want to install a bundle...

**Comment by alcohol** [comment]
@eved42 then you should raise the memory limit in your php.ini

**Comment by omer-sds** [comment]
@alcohol  , now this was strange the thing that fixed it was the same that i mentioned in my last comment , the composer.lock file after getting updated fixed every thing , dont know what the connection is but this is strange , i would be closing this issue now or should i not ?

**Comment by eved42** [comment]
@alcohol I tried to raise the memory limit of the php.ini of Wamp Server 3.0.0 but when I restarted all services, the limit was still 128M (I wrote 1G), however when I returned in the php.ini, there is my change. I don't understand...

So, I prefer to do it with a command line. But I still say that there is a problem with composer and not with my install because in one year, I've never once had this memory problem...

**Comment by alcohol** [comment]
@eved42 Nope, not a Composer problem.

@omer-sds Not sure what actually solved it now? But glad to hear you got things working again.

**Comment by karatektus** [comment]
I just solved pretty much the same problem. XAMPP comes with 32 bit PHP (Which is the only sstable PHP version for windows.) 32Bit Processes cannot use more than 2GB of RAM (which corrosponds to @omer-sds logs)
The solution for me was to use the experimental php 5.6 version from here: [php.net](http://windows.php.net/download/)

That took me about 3 hours to figure out. fml :D hopefully someone in the same position reads this way sooner!
