### ISSUE TITLE
The source code and documentation is ambiguous

### ISSUE THREAD

**Issue by reatang** [composer/composer#5865]
https://github.com/composer/composer/blob/master/src/Composer/Package/AliasPackage.php#L59
https://github.com/composer/composer/blob/master/src/Composer/Package/AliasPackage.php#L176

used key is `replaces `

but documentation is `replace`

https://github.com/composer/composer/blob/master/doc/04-schema.md#replace

Is this a mistake?

**Comment by stof** [comment]
This is not a mistake. The ``$linkType`` variable in the code does not reference to the JSON field (as this code does not deal with the JSON) but with a way to build the getter method name easily (and getter methods are ``getProvides`` and so on, as it makes more sense when returning a list)

**Comment by reatang** [comment]
Thanks for your answer my question, I also have a similar problem.
When I was in using laravel framework。
it `replace` most of the internal package
Such as：
![image](https://cloud.githubusercontent.com/assets/8022923/20337853/8a647648-ac0e-11e6-86a7-504a8483d377.png)


I have some other package also uses these packages, but the package is downloaded again。
![image](https://cloud.githubusercontent.com/assets/8022923/20337847/7a095e94-ac0e-11e6-8dfe-b0e4dd1e04bd.png)

I am very confusing, and it also caused some mistakes.

example：
I am using laravel5.1, and package`spatie/laravel-fractal` support ~5.1.0|~5.2.0|~5.3.0, 
bug composer will automatically download 5.3 support components for `spatie/laravel-fractal`, cause laravel5.1 throw exception.

**Comment by slbmeh** [comment]
I'm not sure I'm following your example.  Can you provide a minimal `composer.json` that does what you describe?

**Comment by reatang** [comment]
1、laravel/laravel
{
    "name": "laravel/laravel",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "spatie/laravel-fractal": "~2.0`"
    },

}

2、laravel/framework
{
    "name": "laravel/framework",
    "replace": {
        "illuminate/auth": "self.version",
        "illuminate/bus": "self.version",
        "illuminate/broadcasting": "self.version",
        "illuminate/cache": "self.version",
        "illuminate/config": "self.version",
        "illuminate/console": "self.version",
        "illuminate/container": "self.version",
        "illuminate/contracts": "self.version",
        "illuminate/cookie": "self.version",
        "illuminate/database": "self.version",
        "illuminate/encryption": "self.version",
        "illuminate/events": "self.version",
        "illuminate/exception": "self.version",
        "illuminate/filesystem": "self.version",
        "illuminate/hashing": "self.version",
        "illuminate/http": "self.version",
        "illuminate/log": "self.version",
        "illuminate/mail": "self.version",
        "illuminate/pagination": "self.version",
        "illuminate/pipeline": "self.version",
        "illuminate/queue": "self.version",
        "illuminate/redis": "self.version",
        "illuminate/routing": "self.version",
        "illuminate/session": "self.version",
        "illuminate/support": "self.version",
        "illuminate/translation": "self.version",
        "illuminate/validation": "self.version",
        "illuminate/view": "self.version"
    }
}

3、spatie/laravel-fractal
{
    "name": "spatie/laravel-fractal",
    "description": "A Fractal service provider for Laravel",
    "require": {
        "php" : "^5.6|^7.0",
        "illuminate/support": "~5.1.0|~5.2.0|~5.3.0",
        "league/fractal": "^0.14.0"
    },
}

**Comment by slbmeh** [comment]
Can you provide a minimal `composer.json` that demonstrates the issue you are seeing?  You provided the `composer.json` for the packages you have mentioned.

**Comment by reatang** [comment]
I don't know what you mean, I already provided  a minimal `composer.json` in previous comment
![image](https://cloud.githubusercontent.com/assets/8022923/20656776/2a927ace-b56b-11e6-8425-dd2324598543.png)
