### ISSUE TITLE
Certificate verify failed in command line

### ISSUE THREAD

**Issue by christophemassin** [composer/composer#5866]
When trying to download composer from command line on a fresh computer : 

php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

Warning: copy(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in Command line code on line 1

Warning: copy(): Failed to enable crypto in Command line code on line 1

Warning: copy(https://getcomposer.org/installer): failed to open stream: operation failed in Command line code on line 1

**Comment by stof** [comment]
Looks like your PHP setup tries to perform the connection as SSLv3, which is not supported by getcomposer.org anymore. Make sure you have an uptodate version of OpenSSL

**Comment by christophemassin** [comment]
version 1.0.2 on mac osx ? 

Brew told me it's the latest.

**Comment by christophemassin** [comment]
ok solved thanks

**Comment by christophemassin** [comment]
$ openssl version
OpenSSL 1.0.2j  26 Sep 2016

**Comment by christophemassin** [comment]
what do you mean by CA file ?

**Comment by srigi** [comment]
@christophemassin install package `ca-certificates` by your system packager.

**Comment by hitchcockwill** [comment]
Can someone give a more detailed explanation of this?

**Comment by hitchcockwill** [comment]
@christophemassin I was able to skip these issues and get Composer installed with this tutorial:

https://www.abeautifulsite.net/installing-composer-on-os-x

**Comment by izemize** [comment]
Missing ca-certificates package from your machine. Install it.

**Comment by cpapidas** [comment]
just run `$ sudo apt-get install ca-certificates ` if you are using ubuntu.

**Comment by WashichawbachaW** [comment]
@cpapidas, how bout windows cmd?
