### ISSUE TITLE
Composer Times out  http connectivity : FAIL 

### ISSUE THREAD

**Issue by dlash02** [composer/composer#5868]
I cannot use composer on my system ... I keep getting: 
The "https://packagist.org/packages.json" file could not be downloaded: SSL: Handshake timed out
Failed to enable crypto
failed to open stream: operation failed
Checking HTTP proxy: FAIL               

I have checked my HTTP_PROXY and HTTPS_PROXY setting and they are correct. . . I am running a vanilla lamp download on a linux box. . . Any ideas?

**Comment by alcohol** [comment]
First idea: they are not correct.

**Comment by Seldaek** [comment]
Closing issue as it has been quiet for a long time and there is no clear next step we can take.
