### ISSUE TITLE
documentation updates

### ISSUE THREAD

**Issue by alcohol** [composer/composer#5869]
The docs could use some updates; e.g. : 

- [x] The [xdebug](https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer) section will be rather irrelevant once 1.3 gets released.
- [x] The [memory issues](https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors) section could benefit from details about cPanel fork bomb protection being a possible root-cause as well.

**Comment by Jean85** [comment]
I would like to tackle this! I need some basic info:

 * For the first point, you want to remove the xdebug section and the previous references too entirely?
 * for the cPanel protection, does suffice using your link and a small explanation?

**Comment by Jean85** [comment]
I've created a PR, trying what I think is the right approach. Review & suggestions welcome!

**Comment by staabm** [comment]
> The xdebug section will be rather irrelevant once 1.3 gets released.

may I ask how this issue was resolved with 1.3?

**Comment by alcohol** [comment]
@staabm see #5580 and #5698, kudos to @johnstevenson :-)

**Comment by staabm** [comment]
awesome, thx guys!
