### ISSUE TITLE
Windows remote repository

### ISSUE THREAD

**Issue by sectus** [composer/composer#5870]
My repo is located on windows machine (\\\\remote). And client on other windows machine want to fetch package from this repository. 

It seems that [isLocalPath](https://github.com/composer/composer/blob/master/src/Composer/Util/Filesystem.php#L478) treats //remote/repo/library as local, but it should not, because it remote.

---

Testing remote repository

```
$ git clone //remote/repo/library
$ cd library
$ composer validate
./composer.json is valid
```
---

My `composer.json`:

```json
{
"require": {"my/library":"dev-master"},
"repositories": [
    {
        "type": "git",
        "url": "//remote/repo/library"
    }]
}
```

Output of `composer diagnose`:

```
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Checking composer.json: WARNING
Defining autoload.psr-4 with an empty namespace prefix is a bad idea for performance
Checking platform settings: WARNING
The xdebug extension is loaded, this can slow down Composer a little.
 Disabling it when using Composer is recommended.

Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer update -vvv
```

I get the following output:

```
... 
Loading composer repositories with package information
Executing command (//remote/repo/library): git show-ref --tags
Executing command (//remote/repo/library): git branch --no-color --no-abbrev -v
Executing command (//remote/repo/library): git branch --no-color
Executing command (//remote/repo/library): git show "master":composer.json

No valid composer.json was found in any branch or tag of //remote/repo/library
, could not load a package from it.
```

And I expected this to happen:
Package is installed from remote repository.

**Comment by alcohol** [comment]
Did you read the actual error message?

**Comment by sectus** [comment]
@alcohol , yes. Message updated: added more output and checking of rempte repo.

**Comment by alcohol** [comment]
Ok, but did you **actually** read it?

**Comment by alcohol** [comment]
Let me put it like this, what happens if you run `git show "master":composer.json` yourself in the correct context?

**Comment by sectus** [comment]
```
$ git clone --mirror //remote/repo/library
$ cd library.git
$ git branch
  develop
* master
$ git log
... shows one commit
$ git show "master":composer.json
{
    "name": "my/library",
    "autoload": {"psr-4": {"Lib\\": "src/"}}
}
$ git show "develop":composer.json
... shows the same message as above
```

**Comment by alcohol** [comment]
Weird, you said you have a valid composer.json

> ```
$ composer validate
./composer.json is valid
```

But clearly:

```
rob /tmp > composer validate
./composer.json is valid for simple usage with composer but has
strict errors that make it unable to be published as a package:
See https://getcomposer.org/doc/04-schema.md for details on the schema
description : The property description is required
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
```

**Comment by alcohol** [comment]
Stop sharing fake data please. Give us facts.

**Comment by sectus** [comment]
It's difficult to remove unimportant data and leave important only.

Ok. Let's make a smiple test. By the way, I am using cygwing.

1) Create folders:
```
/cygdrive/c/test/library
/cygdrive/c/test/project
/cygdrive/c/tmp
```
2) Create library package at /cygdrive/c/test/library with composer.json
```
{
    "name": "my/library",
    "description": "",
    "type": "library",
    "require": {},
    "license": "proprietary"
}
```
2.1) Init repository and make a single commit into master.

3) Check repository
```
$ cd /cygdrive/c/tmp
$ git clone //127.0.0.1/c$/test/library/.git
$ cd library 
$ composer validate
./composer.json is valid
```
4) Create project at /cygdrive/c/test/project with composer.json
```
{
    "name": "my/project",
    "type": "project",
    "require": {"my/library":"dev-master"},
	"repositories": [
        {
            "type": "git",
            "url": "//127.0.0.1/c$/test/library/.git"
        }
    ]    
}
```
$ cd /cygdrive/c/test/project
```
  No valid composer.json was found in any branch or tag of //127.0.0.1/c$/tes
  t/library/.git, could not load a package from it.
```

---

After some research I found that composer uses symfony process, which uses `proc_open`, where 4th params is cwd. After simple test 
```
$cwd = '//remote/repo/library';
$process = proc_open('php', $descriptorspec, $pipes, $cwd);
```
I have error (translated from russian)
```
"\\remote\repo\library"

This path was used when running CMD.EXE as the current folder. CMD.EXE does not support UNC paths. By default, the Windows system folder.
```

**Comment by sectus** [comment]
After some research I have found this: [https://support.microsoft.com/en-us/kb/156276](https://support.microsoft.com/en-us/kb/156276)

After changing DisableUNCCheck value to 0x1 I've got new error:

```
$ cd /cygdrive/c/test/project
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing my/library (dev-master 1597d1b)
    Cloning 1597d1b438bb71b564d5f75e2d89944e8a36eb77


  [RuntimeException]
  Failed to execute git clone --no-checkout "\\127.0.0.1\C$\test\library" "C:
  \test\project\vendor\my\library" && cd /D "C:\test\project\vendor\my\librar
  y" && git remote add composer "\\127.0.0.1\C$\test\library" && git fetch co
  mposer
  fatal: repository '\127.0.0.1\C$\test\library' does not exist
```

Hint: changed slashes.

**Comment by alcohol** [comment]
I'm sorry, but I personally don't support Windows, and I know for a fact that cygwin generally is nothing but trouble. I wish you the best of luck on your endeavors. Perchance someone else can aid you.

**Comment by sectus** [comment]
@alcohol , thanks for your time. 

BTW, cmd and cygwin have equal behaviour in this case.

**Comment by alcohol** [comment]
@Seldaek any idea what might be going on with the weird path conversions here?

**Comment by Seldaek** [comment]
@sectus maybe the best way here would be to mount the network path as a local drive and then use that as path? Because indeed I don't think we support windows network paths very well.
