### ISSUE TITLE
website download page error/confusion

### ISSUE THREAD

**Issue by gwideman** [composer/composer#5871]
https://getcomposer.org/download/  says:

> Options must be appended to -- so that PHP ignores them, like -- --install-dir=bin, example:
> php composer-setup.php --install-dir=bin
> 

The narrative says to use two double-dashes, the example only shows one double-dash.  Which is correct? 
I suspect the narrative is trying to say that since the install-dir argument is intended for the composer-setup command, we want to avoid having the php interpreter consume it, Hence we must escape it with the additional double dash. Is that right? If so, the example must surely be wrong. (Along with subsequent examples.)

**Comment by stof** [comment]
I think this is a leftover from the time the installer was directly piped into PHP

**Comment by gwideman** [comment]
@stof  Which part is leftover from previously? Or more to the point, which part is currently correct?
