### ISSUE TITLE
Install rejected by constraints.

### ISSUE THREAD

**Issue by donaldinou** [composer/composer#5872]
Sorry for that one but I don't get it...

My `composer.json`:

```json
{
    "name": "my-vendor/my-generic-container",
    "description": "My Description",
    "repositories": [
        {
            "type": "vcs",
            "url":  "http://my-custom-gitlab.com/my-vendor/my-project.git"
        }
    ],
    "require": {
        "php": ">=5.5.9",
        "my-vendor/my-project": "3.x@dev"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "secure-http": false
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer install
```

I get the following output:

```

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package my-vendor/my-project 3.x@dev exists as my-vendor/my-project[dev-3.x-1.x] but these are rejected by your constraint.
```

Is that because my development branch contain a dash (3.x**-**1.x) ? What should I do then to get it work?

**Comment by stof** [comment]
this is because the name of your development branch does not match a branch naming recognized by Composer as a version number (and so it names the version ``dev-<branch_name>`` rather than ``<something>.x-dev`` like for recognized dev versions).
If you want to keep this branch name in your repository, you should use the branch-alias feature to alias the branch version (``dev-3.x-1.x`` in your case) to a valid composer version: https://getcomposer.org/doc/articles/aliases.md

**Comment by donaldinou** [comment]
@stof Thank you! That what I've notice. But I've tried aliases and it does not work too.

I've try like this:
```json
{
    "extra": {
        "branch-alias": {
            "dev-master": "dev-3.x-1.x"
        }
    }
}
```

Result is:
```
- The requested package my-vendor/my-project dev-master exists as my-vendor/my-project[dev-3.x-1.x] but these are rejected by your constraint.
```

Like this one:
I've try like this:
```json
{
    "extra": {
        "branch-alias": {
            "dev-master": "3.x-1.x-dev"
        }
    }
}
```

Result is:
```
- The requested package my-vendor/my-project dev-master exists as my-vendor/my-project[dev-3.x-1.x] but these are rejected by your constraint.
```

I also try inline alias 
I've try like this:
```json
{
    "my-vendor/my-project": "dev-master as dev-3.x-1.x"
}
```

Result is:
```
- The requested package my-vendor/my-project dev-master as dev-3.x-1.x exists as my-vendor/my-project[dev-3.x-1.x] but these are rejected by your constraint.
```

In composer I see that the pool return the version to "compare" with is 9999999-dev. Seems good (like any version). I think that the computeWhatProvides do not "correctly" consider my branch name.

Is my alias correct?

**Comment by stof** [comment]
you are attempting to create a branch alias for ``dev-master`` here, which is useless as this is not your version (in a given branch, composer simply ignores branch aliases defined for other branches, making the management of aliases much easier to handle).
What you need is a branch alias for ``dev-3.x-1.x``:

```json
{
    "extra": {
        "branch-alias": {
            "3.x-1.x-dev": "3.x-dev"
        }
    }
}
```

You should then adapt the alias version to match your needs (but according the requirement you wrote above, the one I gave seems to be what you expect)

**Comment by donaldinou** [comment]
Thanks a lot. I understand better. I'll try this and I'll closed issue if everything work.
