### ISSUE TITLE
gitlab Authentication no option to save credentials

### ISSUE THREAD

**Issue by putzflorian** [composer/composer#5875]
The option to save the credentials for gitlab integration is gone.
is there a way to activate this in the latest composer version?

**Comment by alcohol** [comment]
What do you mean, "gone" ? We have not removed any features.

**Comment by putzflorian** [comment]
when i grab files from gitlab i have to authentificate on my gitlab server.
if i type my credentials correctly i get a question to save the credentials this security question is gone now it never appears so i can't store the information and now i always have to type in the username and password

**Comment by alcohol** [comment]
Can you check the contents of `~/.composer/auth.json` (or `~/.config/composer/auth.json` if the former directory does not exist)?

**Comment by putzflorian** [comment]
thx for your info
