### ISSUE TITLE
Allow passing options to php

### ISSUE THREAD

**Issue by mirfilip** [composer/composer#5877]
The official docs mention what to do if you need to pass any opts to `php` binary: `php <opts here> composer.phar install`. This is not really portable, as path to `composer.phar` can vary and it's not wise to hardcode it. Also, it can be installed locally or globally. For one, I use the global installation for both development and staging/production machines.

Looking at the `composer` script, there seems to be no way of passing options to `php`. I'm after sth like: `composer install -- -dmemory_limit=1G`, particular php option is irrelevant. Neither you can `php -dmemory_limit=1G composer install`, for obvious reasons.

This caused me to wrap composer invocation in some script that:
1. `cat $(which composer) | tail -1 | awk '{ printf $(NF-1) }` - gets the path to composer.phar
2. `php -n -c my_custom_php_ini #{PATH_TO_COMPOSER_PHAR_FROM_1} #{args}` - invoke php with phar path.

I used to live with such a nasty workaround until the structure of `composer` changed recently and my extraction of `composer.phar` started failing. It was a straw that pushed me asking for fixing the problem properly.

1. Is there a better way of passing arbitrary opts to `php` binary?
2. Could you add a feature to either pass options to `php` or create some command like `composer path` that returns absolute path to the `.phar`?

**Comment by alcohol** [comment]
1. There are many ways.
2. No.

Example:

```
php -dX $(which composer[.phar]) <command>
```

**Comment by mirfilip** [comment]
@alcohol Damn, that was lame from me. Thx!
