### ISSUE TITLE
Does composer provide an official docker image?

### ISSUE THREAD

**Issue by tback** [composer/composer#5878]
Is the docker image [composer/composer][1] the 'official' docker image or is it created by someone not affiliated with the composer project?

Thanks for your time.

[1]: https://store.docker.com/community/images/composer/composer

**Comment by alcohol** [comment]
It was created by someone unaffiliated, but we do own the composer organization on the hub now. We still list their image currently because it has a significant amount of users already. We also have an open PR at docker-library/official-images#2290 to add an official Composer image on the hub.
