### ISSUE TITLE
composer updating

### ISSUE THREAD

**Issue by moralesf1** [composer/composer#5883]
![sin titulo](https://cloud.githubusercontent.com/assets/9494209/20465018/3aeb0f68-af2a-11e6-859c-7ba6d42127d4.jpg)

hi,i don't know whats is wrong running composer update?

composer.json file

![c js](https://cloud.githubusercontent.com/assets/9494209/20465044/c4e06088-af2a-11e6-9417-56bb0e76f185.jpg)

**Comment by staabm** [comment]
The errors happen inside in one of the laravel classes. Doesnt look like a composer problem

**Comment by alcohol** [comment]
Yes as @staabm mentions, the error happens when `php artisan optimize` runs. This is not a composer script, so we have no control or influence over this. Please consult the Laravel community for support.
