### ISSUE TITLE
raw MD on website

### ISSUE THREAD

**Issue by keradus** [composer/composer#5884]
Hi, sorry if this is wrong place, but I was unable to find better one and file used to generate the website is hosted in this package.

https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md

after:
> Once you've done this, you just run `php bin/satis build 

the HTML generated from MD is not properly generated, displaying **raw MD**.

The crash is on `php bin/satis build <configuration file> <build dir>`. The `<`/`>` should be escaped, but they are not, leading to produce that, invalid, html:
```html
php bin/satis build <configuration file></configuration></p>
<build dir>
```

**Comment by alcohol** [comment]
Definitely the right place. I'll see if I can fix that asap.

**Comment by keradus** [comment]
Great, thanks @alcohol
