### ISSUE TITLE
auth.json: http-basic per path, not domain

### ISSUE THREAD

**Issue by rask** [composer/composer#5890]
When using a custom repo such as Satis, and when splitting multiple package repositories over a single domain using subdirectories, Composer slaps http-basic auth configuration for the whole domain, not the individual subdirectories. This means that I cannot set auth.json for `pkgs.foobar.com/one`, `pkgs.foobar.com/two`, and `pkgs.foobar.com/three` at the same time, but only for the `pkgs.foobar.com` domain as a whole.

How to reproduce:

1.  Create three Satis repos inside a server document root under separate directories (e.g. `/one`, `/two`, and `/three`). This should result each directory containing a different `packages.json` file and the path to a single `packages.json` file looks like `https://pkgs.foobar.com/one/packages.json`.
2.  Create different basic auth credentials for each subdirectory using htpasswd for instance.
3.  Configure server to ask for different htpasswd creds inside each separate subdirectory.
4.  Add the following composer.json configuration:

        "repositories": [ { "type": "composer", "url": "https://pkgs.foobar.com/one" } ]
5.  Run `composer update`, enter credentials for the `/one` endpoint. Packages should install normally.
6.  Change the composer.json repo config to `/two` instead of `/one`.
7.  Attempt `composer update`.
8.  Composer either asks for credentials or complains that the credentials for `pkgs.foobar.com` are wrong.

In step 8 Composer is trying to access `pkgs.foobar.com/two/packages.json` with credentials set for `pkgs.foobar.com/one/packages.json`.

Changing the `auth.json` which can be generated during step 5 to use the path instead of domain does not work, `auth.json` is expected to contain a domain without a path.

Is there any way to use a multi-directory repository server with different basic auth credentials per sub-repo or are we required to use whole domains?

**Comment by alcohol** [comment]
Yo dawg, I heard you like subdomains, so I think you should add subdomains to your subdomain.

On a more serious note though, directories/path based credentials are not supported, only domain (which you can make more specific by adding more subdomains).

**Comment by rask** [comment]
Does that mean they are unsupported or impossible to implement? Most servers can use basic auth on a directory basis instead of being tied to domains. Does Composer use an implementation that cannot be enhanced to support directory-based basic auth?

**Comment by alcohol** [comment]
Correct. Our authentication credentials are always bound to domain. It works like that for all forms of authentication (oauth, tokens, headers, basic auth, etc). Making changes here would have to be done very carefully and will lots of additional tests, to make sure you do not break any of the existing forms of authentication.

**Comment by rask** [comment]
I see. I'll try and get subsubdomains working. More of a hassle with HTTPS and virtual server configs but I guess that is required after this revelation. Thanks. :)

**Comment by Seldaek** [comment]
Closing issue as it has been quiet for a long time and there is no clear next step we can take.
