### ISSUE TITLE
`composer show` does not display versions in travis logs

### ISSUE THREAD

**Issue by xtreamwayz** [composer/composer#5891]
My `composer.json`:

```json
...
```

Output of `composer diagnose`:

```
Composer version 1.2.2 2016-11-03 17:43:15
```

When I run this command:

```
composer show
```

I get the following output:

```
aura/di                                       
aura/router                                   
composer/composer                             
composer/semver
```
https://travis-ci.org/zendframework/zend-expressive-skeleton/jobs/177424153#L198

And I expected this to happen:

```
aura/di                                        3.0.0             
aura/router                                    2.3.0             
composer/composer                              1.0.0             
composer/semver                                1.0.0             
```
https://travis-ci.org/zendframework/zend-expressive-skeleton/jobs/156889589#L438

After checking logs of multiple repositories it seems to be broken since 1.2.2. Older versions are working.

**Comment by alcohol** [comment]
Cannot reproduce.

**Comment by alcohol** [comment]
It wont display the version if it cannot fit it in the terminal. No idea what terminal size travis-ci offers.

**Comment by xtreamwayz** [comment]
I've tried several versions in travis like this:

```
install:
  - composer self-update 1.2.0
  - composer show
  - composer self-update 1.2.1
  - composer show
  - composer self-update 1.2.2
  - composer show
```

And none did show the versions. So I guess the travis terminal is changed some time ago.

**Comment by alcohol** [comment]
Nothing we can do about that :-/

**Comment by alcohol** [comment]
Also I found travis-ci/travis-ci#5407 which seems to suggest it should default to 80 but for some reason it might have defaulted to 40 on some systems.

**Comment by xtreamwayz** [comment]
Thats exactly where I got the solution from. I'll close the issue when I
get back home.

Op di 22 nov. 2016 09:23 schreef Rob <notifications@github.com>:
