### ISSUE TITLE
Cannot use composer at all when composer.json/lock is broken

### ISSUE THREAD

**Issue by mirfilip** [composer/composer#5894]
My `composer.json`:
_any broken json_

When I run this command:

```
$ composer -V
$ composer --help
```

I get the following output:

```
  [Seld\JsonLint\ParsingException]
  "./composer.json" does not contain valid JSON
  Parse error on line 41:
  ...php": ">=5.5.9"    "ext-intl": "*",
  ---------------------^
  Expected one of: 'EOF', '}', ':', ',', ']'
```

And I expected this to happen:
To print version or help, composer.json is not needed. The same commands work when `$CWD` doesn't have a `composer.json/lock` file.

Related to #5893

**Comment by alcohol** [comment]
Composer parses any local composer.json (and also your global composer.json) upon execution automatically. It needs this for various other commands. Deviating from this specific flow just for a few exceptions is a lot of work with little to no extra value. Fix your composer.json.
