### ISSUE TITLE
None of the 0 stable version(s) of Composer matches your PHP version

### ISSUE THREAD

**Issue by YassYakh** [composer/composer#5895]
Hi i m using  CentOS release 6.8 (Final) and php version 5.6.27 , i m trying to dowload php composer but
When I run this command: `curl -sS https://getcomposer.org/installer | php`
 
I get the following output:

```
All settings correct for using Composer
PHP Warning:  file_get_contents(https://getcomposer.org/versions): failed to open stream: Connection timed out in - on line 770

Warning: file_get_contents(https://getcomposer.org/versions): failed to open stream: Connection timed out in - on line 770
PHP Warning:  Invalid argument supplied for foreach() in - on line 516

Warning: Invalid argument supplied for foreach() in - on line 516
None of the 0 stable version(s) of Composer matches your PHP version (5.6.27 / ID: 50627)  
```
i tried to upgrade and downgrade the PHP version but i get the same issue

**Comment by alcohol** [comment]
The error is in the fact that you are unable to access https://getcomposer.org/versions

**Comment by YassYakh** [comment]
how could i fix this problem ??

**Comment by alcohol** [comment]
Find out why you are unable to connect to https://getcomposer.org/versions using php. Could be misconfigured php, or extension. Or bad firewall/proxy. Or outdated openssl extension. Etc.  Could be a number of reasons. None of them are Composer issues though. We cannot fix this.

**Comment by stof** [comment]
@alcohol we should add a safeguard in the installer to fail early when it cannot download versions though, to provide a better error message.

**Comment by alcohol** [comment]
Well I thought we already did that by displaying these warnings. Previously those would not show and it would only return the "None of the 0....".

**Comment by YassYakh** [comment]
how could i find the main raison ??

**Comment by alcohol** [comment]
By using the power of deduction.

**Comment by stof** [comment]
Except that we should stop the execution if we cannot download things. Providing an invalid list of versions to foreach and then saying that ``0 versions matched`` because we looped over an empty array is confusing.

Having 0 compatible versions is not what happened. What happened is that we were unable to perform the matching.

**Comment by alcohol** [comment]
@stof sure, I agree the installer can use improvements. But it still won't help solve these cases.

**Comment by johnstevenson** [comment]
@stof Already PR-d here: https://github.com/composer/getcomposer.org/pull/103

**Comment by alcohol** [comment]
@johnstevenson nice one, lets make sure that gets some traction.

**Comment by johnstevenson** [comment]
@alcohol Ta, I've been running it in `ComposerSetup.exe` since April, so I guess it has had some battle-testing. The next stage will be to provide more informative error messages to the user.

**Comment by Seldaek** [comment]
Closing issue as it has been quiet for a long time and there is no clear step to take.
