### ISSUE TITLE
zlib_decode() data error

### ISSUE THREAD

**Issue by sfarkas1988** [composer/composer#5896]
Hi, i'm running a vagrant machine with:
Ubuntu 14.04.5 LTS
PHP 5.6
Vagrant provisioned with ansible.

My composer file is installed under /home/vagrant/bin/composer.

First i couldn't do composer update because of the error mentioned below.
Now i simply tried a clean php project with only one require statement and get the same error you see below.

I checked the troubleshooting page and nothing helps regarding this error, i don't use ipv6 as written on the page.

I hope anybody has an idea because my workaround doesn't work either (i removed the vendor folder and did composer install, but the newest dependencies are not installed because of composer.lock)

My `composer.json`:

```json

{
    "require": {
        "besimple/soap": "^0.2.6"
    }
}


```

Output of `composer diagnose`:

```
vagrant@ekomi-devenv:/var/www/test$ composer diagnose
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer install
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info


  [ErrorException]
  zlib_decode(): data error

```

And I expected this to happen:

A proper installation of my dependencies

Thank you in advance

**Comment by alcohol** [comment]
Please learn to use the search feature. It is common courtesy not to open duplicate issues.

#5814

**Comment by sfarkas1988** [comment]
Sorry, i searched through google since a few days, my mistake to not search properly in github.
