### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by alainib** [composer/composer#5898]
Hello, i get a 3 years old untouched project. I need to add gaufrette bundle in this project and tweak it.

the original `composer.json`:

        {
            "name": "symfony/framework-standard-edition",
            "description": "The \"Symfony Standard Edition\" distribution",
            "autoload": {
                "psr-0": { "": "src/" }
            },
            "require": {
                "php": ">=5.3.3",
                "symfony/icu": "1.1.x-dev",
                "symfony/symfony": "2.3.*",
                "doctrine/orm": ">=2.2.3,<2.4-dev",
                "doctrine/doctrine-bundle": "1.2.*",
                "twig/extensions": "1.0.*",
                "symfony/assetic-bundle": "2.3.*",
                "symfony/swiftmailer-bundle": "2.3.*",
                "symfony/monolog-bundle": "2.3.*",
                "sensio/distribution-bundle": "2.3.*",
                "sensio/framework-extra-bundle": "2.3.*",
                "sensio/generator-bundle": "2.3.*",
                "jms/security-extra-bundle": "1.5.*",
                "jms/di-extra-bundle": "1.4.*",
                "jms/serializer-bundle": "0.12.*",
                "incenteev/composer-parameter-handler": "~2.0",
                "friendsofsymfony/jsrouting-bundle": "1.1.*",
                "doctrine/mongodb-odm-bundle": "dev-master",
                "friendsofsymfony/user-bundle": "~2.0@dev",
                "white-october/pagerfanta-bundle": "dev-master",
                "friendsofsymfony/rest-bundle": "0.13.*",
                "guzzle/guzzle": "3.1.0",
                "stof/doctrine-extensions-bundle": "dev-master",
                "jms/translation-bundle": "dev-master",
                "willdurand/expose-translation-bundle": "0.3.*",
                "escapestudios/wsse-authentication-bundle": "2.3.x-dev",
                "nelmio/api-doc-bundle": "2.2.*",
                "jms/i18n-routing-bundle": "dev-master",
                "raulfraile/ladybug-bundle": "dev-master",
                "liip/imagine-bundle": "dev-master"
            },
            "scripts": {
                "post-install-cmd": [
                    "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
                    "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
                    "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
                    "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
                    "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
                ],
                "post-update-cmd": [
                    "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
                    "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
                    "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
                    "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
                    "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
                ]
            },
            "config": {
                "bin-dir": "bin"
            },
            "minimum-stability": "dev",
            "extra": {
                "symfony-app-dir": "app",
                "symfony-web-dir": "web",
                "incenteev-parameters": {
                    "file": "app/config/parameters.yml"
                },
                "branch-alias": {
                    "dev-master": "2.3-dev"
                }
            }
        }

this composer.json work if i don't change anything. i can make `composer install`
 
Output of `php composer.phar diagnose`:

 `    No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
    Defining autoload.psr-0 with an empty namespace prefix is a bad idea for performance
    require.symfony/icu : exact version constraints (1.1.x-dev) should be avoided if the package follows semantic versioning
    require.doctrine/mongodb-odm-bundle : unbound version constraints (dev-master) should be avoided
    require.white-october/pagerfanta-bundle : unbound version constraints (dev-master) should be avoided
    require.jms/translation-bundle : unbound version constraints (dev-master) should be avoided
    require.escapestudios/wsse-authentication-bundle : exact version constraints (2.3.x-dev) should be avoided if the package follows semantic versioning
    require.jms/i18n-routing-bundle : unbound version constraints (dev-master) should be avoided
    require.raulfraile/ladybug-bundle : unbound version constraints (dev-master) should be avoided
    Checking platform settings: OK
    Checking git settings: OK
    Checking http connectivity to packagist: OK
    Checking https connectivity to packagist: OK
    Checking github.com rate limit: OK
    Checking disk free space: OK
    Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
    Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
    Checking composer version: OK
`

I wanted to change all the dev-master to fixed version. So i get the composer.lock created 3 years ago and get the version of each bundle from `"extra": {
                "branch-alias": {
                    "dev-master": "XXX"
                }
            },`

So my new composer.json ( a changed the `A.B.x-dev` syntax with `A.B.*` each times )
    
    ...
    "require": {
        "php": ">=5.3.3",
        "symfony/icu": "1.1.x-dev",
        "symfony/symfony": "2.3.*",
        "doctrine/orm": ">=2.2.3,<2.4-dev",
        "doctrine/doctrine-bundle": "1.2.*",
        "twig/extensions": "1.0.*",
        "symfony/assetic-bundle": "2.3.*",
        "symfony/swiftmailer-bundle": "2.3.*",
        "symfony/monolog-bundle": "2.3.*",
        "sensio/distribution-bundle": "2.3.*",
        "sensio/framework-extra-bundle": "2.3.*",
        "sensio/generator-bundle": "2.3.*",
        "jms/security-extra-bundle": "1.5.*",
        "jms/di-extra-bundle": "1.4.*",
        "jms/serializer-bundle": "0.12.*",
        "incenteev/composer-parameter-handler": "~2.0",
        "friendsofsymfony/jsrouting-bundle": "1.1.*",
        "doctrine/mongodb-odm-bundle": "3.0.*",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "white-october/pagerfanta-bundle": "1.0.*",
        "friendsofsymfony/rest-bundle": "0.13.*",
        "guzzle/guzzle": "3.1.0",
        "stof/doctrine-extensions-bundle": "1.1.*",
        "jms/translation-bundle": "1.1.*",
        "willdurand/expose-translation-bundle": "0.3.*",
        "escapestudios/wsse-authentication-bundle": "2.3.x-dev",
        "nelmio/api-doc-bundle": "2.2.*",
        "jms/i18n-routing-bundle": "1.1.*",
        "raulfraile/ladybug-bundle": "dev-master",
        "liip/imagine-bundle": "1.0.*"
    }

 
So i try to `php composer.phar update` but i get erros depending on wich `dev-master` bundle i change
I get the following output: 

        php ../composer.phar update
	Loading composer repositories with package information
	Updating dependencies (including require-dev)
	Your requirements could not be resolved to an installable set of packages.

	  Problem 1
	    - The requested package willdurand/expose-translation-bundle could not be found in any version, there may be a typo in the package name.

	Potential causes:
	 - A typo in the package name
	 - The package is not available in a stable-enough version according to your minimum-stability setting
	   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

 I don't understand why composer found `willdurand/expose-translation-bundle` before and not now.
So i get the original composer.json, remove composer.lock ; remove /vendors/ make 
but i get the same error. is there other file to clean ?

**Comment by alcohol** [comment]
The package `willdurand/expose-translation-bundle` does not exist anymore.

**Comment by alainib** [comment]
but how composer download it the first time ?

**Comment by stof** [comment]
the package was renamed years ago

**Comment by stof** [comment]
@alainib the lock file still contains the old download URL, and Github redirects to the new repo name when renaming a repo

**Comment by alainib** [comment]
i delete the composer.lock file. 

my new composer.json 

     "require": {
        "php": ">=5.3.3",
        "symfony/icu": "1.1.x-dev",
        "symfony/symfony": "2.3.*",
        "doctrine/orm": ">=2.2.3,<2.4-dev",
        "doctrine/doctrine-bundle": "1.2.*",
        "twig/extensions": "1.0.*",
        "symfony/assetic-bundle": "2.3.*",
        "symfony/swiftmailer-bundle": "2.3.*",
        "symfony/monolog-bundle": "2.3.*",
        "sensio/distribution-bundle": "2.3.*",
        "sensio/framework-extra-bundle": "2.3.*",
        "sensio/generator-bundle": "2.3.*",
        "jms/security-extra-bundle": "1.5.*",
        "jms/di-extra-bundle": "1.4.*",
        "jms/serializer-bundle": "0.12.*",
        "incenteev/composer-parameter-handler": "~2.0",
        "friendsofsymfony/jsrouting-bundle": "1.1.*",
        "doctrine/mongodb-odm-bundle": "3.0.*",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "white-october/pagerfanta-bundle": "1.0.*",
        "friendsofsymfony/rest-bundle": "0.13.*",
        "guzzle/guzzle": "3.1.0",
        "stof/doctrine-extensions-bundle": "1.1.*",
        "jms/translation-bundle": "1.1.*",
        "willdurand/js-translation-bundle": "0.3.*",             // renamed
        "escapestudios/wsse-authentication-bundle": "2.2.2",
        "nelmio/api-doc-bundle": "2.2.*",
        "jms/i18n-routing-bundle": "1.1.*",
        "raulfraile/ladybug-bundle": "dev-master",
        "liip/imagine-bundle": "1.0.*"
    }

( the php is 5.5.9 version ) 
`composer update` give me this 

	> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

	                                                                                                                                                 
	  [Doctrine\ODM\MongoDB\Mapping\MappingException]                                                                                                
	  ReferenceMany's sort can not be used with addToSet and pushAll strategies, pushAll used in Plantnet\DataBundle\Document\Plantunit::taxonsrefs  
	                                                                                                                                                 

	Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception
	                                                                             
	  [RuntimeException]                                                         
	  An error occurred when executing the "'cache:clear --no-warmup'" command.  

which version of `doctrine/mongodb-odm-bundle` i should use ? dev-master don't work anymore with the new composer.json

**Comment by alcohol** [comment]
Why do you think we know what you should use? It is your software, and thus your responsibility. We build the tools to manage your dependencies, not the actual dependencies. Please seek help in the appropriate place.

**Comment by alainib** [comment]
you are right, sorry

**Comment by alainib** [comment]
yes you are right, i tryed many things since two days. i should use stackoverflow for this kind of error.

Last question specific to composer. 
**How to get real version of each bundle installed by composer ?**

i tried `php ../composer.phar show -i -t`  

	doctrine/mongodb-odm-bundle 3.0.x-dev Symfony2 Doctrine MongoDB Bundle
	├──doctrine/mongodb-odm ~1.0.0-beta5@dev
	│  ├──doctrine/annotations ~1.0
	│  │  ├──doctrine/lexer 1.*
	│  │  │  └──php >=5.3.2
	│  │  └──php >=5.3.2
	│  ├──doctrine/cache ~1.0
	│  │  └──php >=5.3.2
	│  ├──doctrine/collections ~1.1
	│  │  └──php >=5.3.2
	│  ├──doctrine/common 2.4.*
	             ....
	│  ├──doctrine/inflector ~1.0
	│  │  └──php >=5.3.2
	│  ├──doctrine/mongodb >=1.1.5,<2.0
	│  │  ├──doctrine/common >=2.1.0,<2.5-dev
	│  │  │  ├──doctrine/annotations 1.*
	             ....
	│  │  ├──ext-mongo >=1.2.12,<1.6-dev
	│  │  └──php >=5.3.2
	│  ├──php >=5.3.2
	│  └──symfony/console ~2.0
	├──php >=5.3.2
	├──symfony/doctrine-bridge ~2.1
	├──symfony/framework-bundle ~2.1
	└──symfony/options-resolver ~2.1
 
So i replace in `composer.json`  
    
     "doctrine/mongodb-odm-bundle": "dev-master" by
     "doctrine/mongodb-odm-bundle": "3.0.x-dev" 

but if i make `composer update` i get error that i don't have before ( like `[Doctrine\ODM\MongoDB\Mapping\MappingException]` ) so this bundle was not the same.

What i'm missing to get good bundle version ? thanks

**Comment by stof** [comment]
just ``composer show``

**Comment by alainib** [comment]
i tried to but i get dev-master 

	$ php ../composer.phar showdflydev/markdown                         dev-master dee1f7a
	doctrine/annotations                     dev-master 1ac675c
	doctrine/cache                           dev-master bb9b55b
	doctrine/collections                     dev-master b99c5c4
	doctrine/common                          2.4.x-dev b1a31ae 
	doctrine/dbal                            2.3.x-dev 87d5d92 
	doctrine/doctrine-bundle                 v1.2.0            
	doctrine/inflector                       dev-master dc02e4f
	doctrine/lexer                           dev-master f12a5f7
	doctrine/mongodb                         dev-master fd76cd0
	doctrine/mongodb-odm                     dev-master ba003db
	doctrine/mongodb-odm-bundle              dev-master ba17a28
	doctrine/orm                             2.3.x-dev 9817303 
	escapestudios/wsse-authentication-bundle dev-master 9ff8d7b
	friendsofsymfony/jsrouting-bundle        1.1.5             
	friendsofsymfony/rest                    0.8.0             
	friendsofsymfony/rest-bundle             0.13.1            
	friendsofsymfony/user-bundle             dev-master e4c000a
	gedmo/doctrine-extensions                dev-master 47ed3e4
	guzzle/guzzle                            v3.1.0            
	imagine/imagine                          v0.5.0            
	incenteev/composer-parameter-handler     dev-master f6b9861
	jdorn/sql-formatter                      dev-master ffd2441
	jms/aop-bundle                           dev-master 93f41ab
	jms/cg                                   dev-master 3d2881f
	jms/di-extra-bundle                      dev-master 4361495
	jms/i18n-routing-bundle                  dev-master 6f69173
	jms/metadata                             dev-master f44eefc
	jms/parser-lib                           dev-master d5961fa
	jms/security-extra-bundle                dev-master 2d84e41
	jms/serializer                           0.16.0            
	jms/serializer-bundle                    0.12.0            
	jms/translation-bundle                   dev-master 1c41baf
	kriswallsmith/assetic                    1.1.x-dev 1d671c5 
	liip/imagine-bundle                      dev-master 2be6f95
	monolog/monolog                          dev-master 97f79f7
	nelmio/api-doc-bundle                    2.2.4             
	nikic/php-parser                         v0.9.4            
	pagerfanta/pagerfanta                    dev-master c41473a
	phpcollection/phpcollection              dev-master 94a2c04
	phpoption/phpoption                      1.4.0             
	psr/log                                  dev-master a78d650
	ptachoire/cssembed                       v1.0.2            
	raulfraile/ladybug                       v1.0.8            
	raulfraile/ladybug-bundle                dev-master 342f0be
	raulfraile/ladybug-installer             v1.0.1            
	raulfraile/ladybug-plugin-extra          v1.0.1            
	raulfraile/ladybug-plugin-symfony2       v1.0.1            
	raulfraile/ladybug-theme-modern          v1.0.6            
	sensio/distribution-bundle               v2.3.4            
	sensio/framework-extra-bundle            2.3.x-dev f9e4c97 
	sensio/generator-bundle                  dev-master 201c75b
	stof/doctrine-extensions-bundle          dev-master f1c7993
	swiftmailer/swiftmailer                  dev-master 564abb1
	symfony/assetic-bundle                   2.3.x-dev 099e0bb 
	symfony/icu                              1.1.x-dev 0b82950 
	symfony/monolog-bundle                   2.3.x-dev f105e8c 
	symfony/swiftmailer-bundle               dev-master e98defd
	symfony/symfony                          2.3.x-dev 5cae63f 
	twig/extensions                          dev-master 5023031
	twig/twig                                dev-master af6910e
	white-october/pagerfanta-bundle          dev-master 35c8e21
	willdurand/expose-translation-bundle     dev-master 6df1246
	willdurand/negotiation                   1.0.x-dev 8f8c85f

**Comment by alcohol** [comment]
That is because you installed dev-master. You did not install a specific version.

**Comment by alainib** [comment]
yes but now i just want to take the already installed version and fix them in the composer.json. 

in `composer.json `

       doctrine/mongodb-odm-bundle": "dev-master

in `composer.lock`

       {
            "name": "doctrine/mongodb-odm-bundle",
            "version": "dev-master",
            "target-dir": "Doctrine/Bundle/MongoDBBundle",
            "source": {
                "type": "git",
                "url": "https://github.com/doctrine/DoctrineMongoDBBundle.git",
                "reference": "ba17a288ae0f2f2cb4ef1bac667710a5f3b7151e"
            },
            ....
            "extra": {
                "branch-alias": {
                    "dev-master": "3.0-dev"
                }
            }
            ...
        }

I can make `composer install` but  `composer update` get me error.

So i change `composer.json ` to

       doctrine/mongodb-odm-bundle": "3.0-dev"

now  `composer install`  stop working. i try erase lock file and composer cache.

**Comment by xabbuh** [comment]
@alainib The `MappingException` you were talking about before is triggered by a script that was executed after installing/updating your dependencies. This error is not related to Composer, but there may have been changes in DoctrineMongoDBBundle you need to account for.

**Comment by alcohol** [comment]
> yes but now i just want to take the already installed version and fix them in the composer.json

The problem is that since you were using `dev-master` in the past, it is virtually impossible to tell what "version" that was. It all depends on what point in time you last ran install and/or update, since `dev-master` is a constantly moving target.

**Comment by mantasputrius** [comment]
bybys kiausai
