### ISSUE TITLE
--ignore-platform-reqs to respect php version

### ISSUE THREAD

**Issue by glensc** [composer/composer#5900]
So, I run (in CI one step) `composer install --ignore-platform-reqs` because i don't want to spend time install extension dependencies, those are not needed at that time (this CI step is only for building `vendor/` dir).

but this results composer picking also versions out of range for php engine.

say i want to download dependencies for php 5.3:
- php -V -> 5.3
- composer install picks: symfony/process (v3.1.7)
- [v3.1.7/composer.json:L19](https://github.com/symfony/process/blob/v3.1.7/composer.json#L19) ->         `"php": ">=5.5.9"`

i've tried to put to composer.json:

```json
    "config": {
        "platform": {
            "php": "5.3.9"
        }
    },
```

but that did not help, `--ignore-platform-reqs` made to ignore it.

can some middle ground be found for this solution? an separate options to ignore extension dependencies and other option for php version?

**Comment by alcohol** [comment]
`--ignore-platform-reqs` does not ignore the `config` setting. It simply makes it completely irrelevant, because Composer will not check your php version requirements anymore, since they are platform requirements and you told Composer to ignore them.

Splitting the platform repository into multiple repositories (or however you'd want to go about implementing this) is not on our road map, but we might be open to a pull request depending on the implementation. /cc @Seldaek care to comment on whether or not you'd be ok with that?

**Comment by Seldaek** [comment]
I think in this case it's better that you define the extensions as being installed in the platform config.. That way you don't have to ignore anything, and you don't miss warnings in case you are missing an extension.

**Comment by glensc** [comment]
please do not assume i have only one project. i filed this RFE to have absolute solution for all projects.

**Comment by glensc** [comment]
@alcohol the config.platform.version hack was **second** solution i tried. the original problem was that running php 5.3 with --ignore-platform-reqs ignored php version as well, not just extension deps.

so this RFE was asking about to have two different commandline options, one for excluding ext-<name> dependencies, and other for ignoring php version dependency. well, ideally just need another option that would ignore only ext-<name>, and the current option behaviour can stay as it is.

**Comment by glensc** [comment]
@Seldaek also defining extensions in "platform.config" breaks normal usage, i.e usage for developers. it's equal just dropping ext-<xxx> in root composer.json, definately a "solution" to undefine dependencies.

**Comment by glensc** [comment]
@Seldaek and you you recommend to (ab)use that?

```
$ composer config platform.ext-mcrypt '*'
```

**Comment by Seldaek** [comment]
Yes.. it's not the best solution but I think it's the best compromise right now to avoid ignoring everything.

**Comment by glensc** [comment]
`'*'` was not valid version, so used `'0'` instead

```
$ composer config platform.ext-mcrypt '0'
```

**Comment by glensc** [comment]
Something was done in this commit: https://github.com/composer/composer/commit/c8efb50d399bd366f3635dbd2d84705bbf605cff for composer 2.0

can't yet find associated PR or doc

**Comment by Seldaek** [comment]
Yes with v2 you can then call `--ignore-platform-req=ext-foo --ignore-platform-req=ext-bar` for example to ignore two
