### ISSUE TITLE
composer outdated always exits with a 0 status code

### ISSUE THREAD

**Issue by Rudloff** [composer/composer#5901]
Hello,

It would be nice to have an option that treats outdated dependencies as an error and exits with a non-zero status code.
It would help check outdated dependencies with a CI tools.

**Comment by alcohol** [comment]
Feel free to contribute.

**Comment by Rudloff** [comment]
I can submit a patch but I have no idea what status code I should use.

**Comment by stof** [comment]
I would say 1. No need to go fancy

**Comment by alcohol** [comment]
Yeah we don't reserve specific numbers for specific errors. 0 means success, 1 means not a success. I know diagnose uses 2 for errors and 1 for warnings, but not sure if you need to make a distinction here. Also not sure if that was even a wise choice for diagnose.

**Comment by Rudloff** [comment]
Here is my pull request: https://github.com/composer/composer/pull/5907
Please feel free to comment it.
