### ISSUE TITLE
Composer doesn't get PHP Version correctly

### ISSUE THREAD

**Issue by LKDevelopment** [composer/composer#5905]
My `composer.json`:

```json
https://github.com/CachetHQ/Cachet/blob/v2.3.10/composer.json
```

Output of `composer diagnose`:

```
hecking composer.json: WARNING
require.laravel/framework : exact version constraints (5.2.39) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer require spatie/laravel-uptime-monitor
```

I get the following output:

```
  [InvalidArgumentException]
  Could not find package spatie/laravel-uptime-monitor at any version matching your PHP version 5.5.9.0
```

But when i run php -v i get:
```
PHP 7.0.13-1+deb.sury.org~xenial+1 (cli) ( NTS )
```

The System is an Ubuntu system with php7 setup.

**Comment by stof** [comment]
what do you get when you run ``/usr/bin/env php -v`` ?
One possible case is that you have a shell alias for ``php`` to make it target PHP 7, but that your PATH still targets PHP 5.5.
When running a tool using a shebang, shell aliases are not considered.

**Comment by LKDevelopment** [comment]
```
/usr/bin/env php -v
PHP 7.0.13-1+deb.sury.org~xenial+1 (cli) ( NTS )
```

The Server is fresh installed with https://forge.laravel.com

**Comment by stof** [comment]
Your composer.json configures that PHP must be considered as being 5.5.9:

```json
{
    "config": {
        "platform": {
            "php": "5.5.9"
        },
        "preferred-install": "dist"
    },
}
```

So the behavior of Composer is fine.

**Comment by LKDevelopment** [comment]
Oh sorry! Missed this in the config. Than that isn't a good practice from cachet. Thank you!

**Comment by stof** [comment]
Well, they configure it this way to ensure that their project does not drop support for PHP 5.5.9 in their locked dependencies (as it is their min supported version). If you start modifying the project, you can change this config too

**Comment by jbrooksuk** [comment]
Please note that from v2.4 we've already removed this config; https://github.com/CachetHQ/Cachet/blob/2.4/composer.json
