### ISSUE TITLE
Composer update fails

### ISSUE THREAD

**Issue by JQL** [composer/composer#5906]
Start Composer update and I get the following:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpunit/phpunit 5.6.2 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 5.6.2 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 5.6.2 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - Installation request for phpunit/phpunit (locked at 5.6.2) -> satisfiable by phpunit/phpunit[5.6.2].

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.0/cli/conf.d/10-opcache.ini
    - /etc/php/7.0/cli/conf.d/10-pdo.ini
    - /etc/php/7.0/cli/conf.d/20-calendar.ini
    - /etc/php/7.0/cli/conf.d/20-ctype.ini
    - /etc/php/7.0/cli/conf.d/20-curl.ini
    - /etc/php/7.0/cli/conf.d/20-dba.ini
    - /etc/php/7.0/cli/conf.d/20-exif.ini
    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.0/cli/conf.d/20-ftp.ini
    - /etc/php/7.0/cli/conf.d/20-gettext.ini
    - /etc/php/7.0/cli/conf.d/20-iconv.ini
    - /etc/php/7.0/cli/conf.d/20-intl.ini
    - /etc/php/7.0/cli/conf.d/20-json.ini
    - /etc/php/7.0/cli/conf.d/20-ldap.ini
    - /etc/php/7.0/cli/conf.d/20-mbstring.ini
    - /etc/php/7.0/cli/conf.d/20-mcrypt.ini
    - /etc/php/7.0/cli/conf.d/20-mysqli.ini
    - /etc/php/7.0/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.0/cli/conf.d/20-phar.ini
    - /etc/php/7.0/cli/conf.d/20-posix.ini
    - /etc/php/7.0/cli/conf.d/20-readline.ini
    - /etc/php/7.0/cli/conf.d/20-shmop.ini
    - /etc/php/7.0/cli/conf.d/20-sockets.ini
    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.0/cli/conf.d/20-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.

**Comment by alcohol** [comment]
Please learn to read.

**Comment by JQL** [comment]
Alcohol. Helpful NOT me thinks.

**Comment by stof** [comment]
Well, the error message tells you that ``ext-dom`` is missing from your PHP setup. So to make the install work, enable the extension

**Comment by alcohol** [comment]
@JQL The error clearly states what the problem is. If you do not want to invest any time/effort into simply understanding the message, why do you expect us to invest any effort/time at all?

**Comment by alcohol** [comment]
Composer dependency resolution will fail on the first hard error it encounters, and it will not proceed further at that point. So yes, it is possible that solving one might reveal another.

I do not see how this error was not self-explanatory enough, nor do I understand what Linux has to do with any of this.

Clearly, we both have a different approach to software development.

Your final solution does not really make sense to me either. If codeception does not run on php 7, then yes, downgrading php will solve that. No need to discover new paths or anything. If you are proposing to install a downgraded version next to php 7, and then use this older version simply to be able to update codeception (but still run on php 7 in the end), then you could just have used the `--ignore-platform-reqs` flag for install and/or update.
