### ISSUE TITLE
Error using version 5.3

### ISSUE THREAD

**Issue by vinnyfs89** [composer/composer#5908]
Using an application in version 5.3 of php the method "getInitializer" shows the following error "Class name constant is available in PHP 5.5 only". Even if you set the values below, the error persists:

```
"config": {
        "platform": {
            "php": "5.3.3"
        }
    },
```

It happened in this file : composer/src/Composer/Autoload

The error has started to appear since this review : https://github.com/composer/composer/commit/fd2f51cea8e5f1ef978cd8f90b87b69dc1778976

**Comment by alcohol** [comment]
That code is only used on PHP versions that support it. Hence it is not an issue.

**Comment by vinnyfs89** [comment]
Sorry, my bad. On autoload_real.php line 30 have a validation to do it...

```
$useStaticLoader = PHP_VERSION_ID >= 50600 && !defined('HHVM_VERSION');
```

Thanks, man.
