### ISSUE TITLE
Proxy not work

### ISSUE THREAD

**Issue by Crutchmaster** [composer/composer#5909]
`
$ composer -vvv selfupdate

Reading /home/user/.config/composer/composer.json
Loading config file /home/user/.config/composer/composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/home/user/.config/composer): git branch --no-color --no-abbrev -v
Executing command (/home/user/.config/composer): git describe --exact-match --tags
Executing command (/home/user/.config/composer): git log --pretty="%H" -n1 HEAD
Reading /home/user/.config/composer/vendor/composer/installed.json
Running f1eb78701358b74f21db9293035e87b1b98be2bc (2016-11-21 12:39:07) with PHP 5.6.24-0+deb8u1 on Linux / 3.2.0-4-686-pae
Downloading https://getcomposer.org/versions using proxy ssl://127.0.0.1:3128

  [Composer\Downloader\TransportException]                                                                                        
  The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:  
  error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol                                                             
  Failed to enable crypto                                                                                                         
  failed to open stream: operation failed 

$ export | grep proxy
declare -x http_proxy="http://127.0.0.1:3128"
declare -x https_proxy="https://127.0.0.1:3128"
$ uname -a
Linux test_server 3.2.0-4-686-pae #1 SMP Debian 3.2.82-1 i686 GNU/Linux
`

Just. Fix. Work. With. Proxy.

**Comment by staabm** [comment]
`The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:` sounds like you have issues with your ssl/tls system library or its php bindings

**Comment by alcohol** [comment]
> Just. Fix. Work. With. Proxy.

No. Cannot. Do. Thanks. Bye.

**Comment by Crutchmaster** [comment]
>sounds like you have issues with your ssl/tls system library or its php bindings

Oh yes. May be you know why sh comand https_proxy=$http_proxy fix it?

**Comment by alcohol** [comment]
You cannot run a https and http proxy on the same port.

**Comment by Crutchmaster** [comment]
>You cannot run a https and http proxy on the same port.
Yes, but http and https requests go through same proxy port. What means variable https_proxy? Proxy for https requests? Address of https proxy? Or both? If composer can't do ssl connect, why he don't use tcp to connect? Write one simply check it is something imposible?

**Comment by alcohol** [comment]
> What means variable https_proxy? Proxy for https requests? Address of https proxy? Or both?
Both.
