### ISSUE TITLE
How to make dependencies from internal package composer.json file available in project scope composer.json?

### ISSUE THREAD

**Issue by drupality** [composer/composer#5916]
Hi,

Kudos for this great tool.

The thing is that I have some custom modules that I want to reuse between projects.
To add custom dependency to project I run:

> composer require drupal/my_features_package

Inside my_features_package I have some mods + composer.json file.
In composer.json file I've added some contrib deps  (required by those mods of course), e.g:

```
   "require": {
        "drupal/ctools": "^3.0",
        "drupal/media_entity": "^1.5",
    }
```

This is working, I mean those mods are fetched, but in project composer.json file (site/composer.json) I have no info about this mods. Only about my custom package.

Is this possible to configure composer to adding these deps to site/composer.json automatically?

I want to control mods versions per project and have ability to override package composer.json dependencies in project composer.json. But keep ability to download contrib mods automatically upon composer require command.

I've tried: https://github.com/wikimedia/composer-merge-plugin but this seems to working only at runtime

**Comment by stof** [comment]
the composer.json is not there to store info about the resolved packages, as it is the input config of the resolution algorithm (which takes care of recursice requirements).

Locking exact versions is the job of the composer.lock, not of the composer.json

**Comment by drupality** [comment]
@stof thanks for the answer, so this is impossible? Versions is one thing, I want to at least have all dependencies listed in one place.

**Comment by PatrickBauer** [comment]
What is the benefit to see all your dependencies? The list would be incredibly long (as it would list *all* dependencies and not just drupal ones). I think a better way would be a tool which could list you all your dependencies, without writing them in your root composer file.

**Comment by alcohol** [comment]
No, this is not possible. Your project declares its dependencies in the composer.json. Those dependencies declare their own dependencies in their own respective composer.json's. If you want to have *all* dependencies in your root composer.json, you will need to add them yourself. To get an overview of all dependencies you have installed in a particular project, run `composer show`.

**Comment by drupality** [comment]
Thanks for the feedback. You are right, simple `composer show | grep drupal` will do the job. Sorr for bother.
