### ISSUE TITLE
Require lib-openssl fails when php is linked against LibreSSL

### ISSUE THREAD

**Issue by nocive** [composer/composer#5917]
It seems that composer is not able to detect lib openssl when using LibreSSL.

My `composer.json`:

```json
    "require": {
        "lib-openssl": "*"
    }
```

When running ```composer install``` this happens:
```
  Problem 1
    - namshi/jose 2.2.2 requires lib-openssl * -> the requested linked library openssl has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - namshi/jose 2.2.2 requires lib-openssl * -> the requested linked library openssl has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - Installation request for namshi/jose 2.2.2 -> satisfiable by namshi/jose[2.2.2].
```

More debug info
```
# php -v
PHP 7.0.13 (cli) (built: Nov 16 2016 17:49:30) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.13, Copyright (c) 1999-2016, by Zend Technologies
```
```
# composer show --platform
composer-plugin-api 1.1.0     The Composer Plugin API
ext-apcu            5.1.6     The apcu PHP extension
ext-bcmath          7.0.13    The bcmath PHP extension
ext-bz2             7.0.13    The bz2 PHP extension
ext-calendar        7.0.13    The calendar PHP extension
ext-ctype           7.0.13    The ctype PHP extension
ext-date            7.0.13    The date PHP extension
ext-dom             20031129  The dom PHP extension
ext-exif            0         The exif PHP extension (actual version: 1.4 $Id: 8bdc0c8f27c2c9dd1f7551f1f9fe3ab57a06a4b1 $)
ext-fileinfo        1.0.5     The fileinfo PHP extension
ext-filter          7.0.13    The filter PHP extension
ext-ftp             7.0.13    The ftp PHP extension
ext-hash            1.0       The hash PHP extension
ext-iconv           7.0.13    The iconv PHP extension
ext-intl            1.1.0     The intl PHP extension
ext-json            1.4.0     The json PHP extension
ext-libxml          7.0.13    The libxml PHP extension
ext-mbstring        7.0.13    The mbstring PHP extension
ext-mcrypt          7.0.13    The mcrypt PHP extension
ext-memcached       3.0.0b1   The memcached PHP extension
ext-openssl         7.0.13    The openssl PHP extension
ext-pcntl           7.0.13    The pcntl PHP extension
ext-pcre            7.0.13    The pcre PHP extension
ext-PDO             7.0.13    The PDO PHP extension
ext-pdo_pgsql       7.0.13    The pdo_pgsql PHP extension
ext-pgsql           7.0.13    The pgsql PHP extension
ext-Phar            2.0.2     The Phar PHP extension
ext-posix           7.0.13    The posix PHP extension
ext-redis           3.0.0-rc1 The redis PHP extension
ext-Reflection      7.0.13    The Reflection PHP extension
ext-session         7.0.13    The session PHP extension
ext-SimpleXML       7.0.13    The SimpleXML PHP extension
ext-soap            7.0.13    The soap PHP extension
ext-SPL             7.0.13    The SPL PHP extension
ext-ssh2            1.0       The ssh2 PHP extension
ext-tokenizer       7.0.13    The tokenizer PHP extension
ext-xml             7.0.13    The xml PHP extension
ext-xmlreader       7.0.13    The xmlreader PHP extension
ext-xmlrpc          7.0.13    The xmlrpc PHP extension
ext-xmlwriter       7.0.13    The xmlwriter PHP extension
ext-xsl             7.0.13    The xsl PHP extension
ext-Zend-OPcache    7.0.13    The Zend OPcache PHP extension
ext-zip             1.13.5    The zip PHP extension
ext-zlib            7.0.13    The zlib PHP extension
lib-ICU             57.1      The intl PHP library
lib-libxml          2.9.4     The libxml PHP library
lib-pcre            8.38      The pcre PHP library
lib-xsl             1.1.29    The xsl PHP library
php                 7.0.13    The PHP interpreter
php-64bit           7.0.13    The PHP interpreter, 64bit
php-ipv6            7.0.13    The PHP interpreter with IPv6 support
```
```
# php -i | grep -i openssl
openssl
OpenSSL support => enabled
OpenSSL Library Version => LibreSSL 2.4.4
OpenSSL Header Version => LibreSSL 2.4.4
Openssl default config => /etc/ssl/openssl.cnf
openssl.cafile => no value => no value
openssl.capath => no value => no value
OpenSSL support => enabled
```
```
# php -r "echo (new ReflectionExtension('openssl'))->getVersion();"
7.0.13
```
```
# php -r 'echo OPENSSL_VERSION_TEXT;'
LibreSSL 2.4.4
```

Functionality wise from PHP side everything seems to work fine regardless but composer refuses to install the project's dependencies due to this constraint.

It seems the culprit is here https://github.com/composer/composer/blob/master/src/Composer/Repository/PlatformRepository.php#L177
Not sure if this is intended behaviour or not since LibreSSL is still not completely rolled out in most major distributions but Alpine Linux recently switched to use LibreSSL completely and for sure more will follow.

Please advise, thank you.

**Comment by stof** [comment]
AFAIK, composer does not expose a package for the underlying Openssl library. Is there a need for it ?

Requiring an extension involves the ``ext-*`` package, not the ``lib-*`` package.

Btw, library packages are not fully reliable, because constants defined by extension are often reflecting the version used when compiling the extension rather than the version used at runtime, which may be different depending on how you install the extension (if you download a precompiled DDL for the extension from pecl.php.net and it does not ship its own version of the library to be used with it, it may end up being different for instance)

**Comment by alcohol** [comment]
@stof if I am not mistaken, we support both `lib-` and `ext-`, see https://github.com/composer/composer/blob/master/src/Composer/Repository/PlatformRepository.php#L26

Also, we expose openssl, see: https://github.com/composer/composer/blob/master/src/Composer/Repository/PlatformRepository.php#L176

Why it does not match is difficult to determine though without knowing the full context all the commands were run in.

**Comment by stof** [comment]
Well, the issue seems to be that ``LibreSSL 2.4.4`` won't match the regex (as it starts with ``LibreSSL``, not ``OpenSSL``), and so the full text ``LibreSSL 2.4.4`` will be used as version, which is invalid and so removes the ``lib-openssl`` package entirely.

**Comment by alcohol** [comment]
@stof then why does `composer show --platform` list it? It display it with the php version though, not the extension/lib version. I have the same version mismatch locally (even though my php 7.0.13 is compiled with openssl).

```
rob ~ > composer show --platform
composer-plugin-api 1.1.0    The Composer Plugin API
ext-bz2             7.0.13   The bz2 PHP extension
ext-ctype           7.0.13   The ctype PHP extension
ext-curl            7.0.13   The curl PHP extension
ext-date            7.0.13   The date PHP extension
ext-dom             20031129 The dom PHP extension
ext-fileinfo        1.0.5    The fileinfo PHP extension
ext-filter          7.0.13   The filter PHP extension
ext-hash            1.0      The hash PHP extension
ext-json            1.4.0    The json PHP extension
ext-libxml          7.0.13   The libxml PHP extension
ext-mbstring        7.0.13   The mbstring PHP extension
ext-mysqlnd         0        The mysqlnd PHP extension (actual version: mysqlnd 5.0.12-dev - 20150407 - $Id: 241ae00989d1995ffcbbf63d579943635faf9972 $)
ext-openssl         7.0.13   The openssl PHP extension
ext-pcntl           7.0.13   The pcntl PHP extension
ext-pcre            7.0.13   The pcre PHP extension
ext-PDO             7.0.13   The PDO PHP extension
ext-Phar            2.0.2    The Phar PHP extension
ext-posix           7.0.13   The posix PHP extension
ext-readline        7.0.13   The readline PHP extension
ext-Reflection      7.0.13   The Reflection PHP extension
ext-session         7.0.13   The session PHP extension
ext-SimpleXML       7.0.13   The SimpleXML PHP extension
ext-SPL             7.0.13   The SPL PHP extension
ext-tokenizer       7.0.13   The tokenizer PHP extension
ext-xml             7.0.13   The xml PHP extension
ext-xmlreader       7.0.13   The xmlreader PHP extension
ext-xmlwriter       7.0.13   The xmlwriter PHP extension
ext-zip             1.13.5   The zip PHP extension
ext-zlib            7.0.13   The zlib PHP extension
lib-curl            7.51.0   The curl PHP library
lib-libxml          2.9.4    The libxml PHP library
lib-openssl         1.0.2.10 OpenSSL 1.0.2j  26 Sep 2016
lib-pcre            8.39     The pcre PHP library
php                 7.0.13   The PHP interpreter
php-64bit           7.0.13   The PHP interpreter, 64bit
php-ipv6            7.0.13   The PHP interpreter, with IPv6 support
```

**Comment by alcohol** [comment]
Also, pretty sure it will add it even if the version cannot be parsed since that part is in a try-catch, see: https://github.com/composer/composer/blob/master/src/Composer/Repository/PlatformRepository.php#L217-L225

**Comment by alcohol** [comment]
So in short, @nocive is right, we should address the regex match for the `lib-` package. As a temp fix, he could require `ext-openssl` instead.

**Comment by nocive** [comment]
Thanks for the fast feedback guys.

The upstream package I'm relying on requires ```lib-openssl``` and this constraint works fine with php versions linked against OpenSSL, but not LibreSSL.
From the preliminary investigations I did, it did seem to me that the problem was in that regex match, that starts with OpenSSL has @stof pointed out.

It seems earlier versions of [namshi/jose](https://github.com/namshi/jose) do not have the ```require lib-openssl``` anymore and only requires the extension, which seems to make more sense imo.

However, my project is currently bound to an old version (https://github.com/namshi/jose/blob/2.2.2/composer.json#L23), so as a workaround I can fork it and drop the ```lib-openssl``` requirement from ```composer.json```, I just thought it would be worth bringing this up here since I can imagine this will potentially start affecting more people as LibreSSL goes mainstream.

**Comment by stof** [comment]
@alcohol ext-openssl has the version number of the extension itself, not of the openssl library (which is why we also have a lib-openssl package).
and for extension being built as part of PHP itself, their version is the same than the PHP version (as of PHP 7, it was a total mess in PHP 5.x with core extensions returning random crap for many of them)

**Comment by sbuzonas** [comment]
I don't know if adding LibreSSL to the OpenSSL regex is an ideal fix.  They are different libs and have different version schemes.

A package dependency on a lib expecting functionality is generally wrong because of @stof's remark above. But certain circumstances may be desirable to conflict with certain versions of the lib. 
In this particular case I can say `>1.0.1.6` to be a good netizen about heartbleed and it fortunately works out.  Ideally it would be nice if the PHP extension were to expose the distinction between `libcrypto`, `libssl`, and the new `libtls` provided by `LibreSSL`

**Comment by Seldaek** [comment]
I agree it'd be good to expose all with their own name, but then you can't really require any because they are system libs that users really don't have much control over, so if you require a specific one you are screwing over your users most likely.

**Comment by sbuzonas** [comment]
I agree, requiring a particular lib doesn't work out particularly well.  A conflict would be more appropriate in that case which would work as long as OpenSSL and LibreSSL never end up with overlapping versions.

**Comment by alcohol** [comment]
I also considered adding libressl as yet another `lib-` variant. In the end I believe it is easier for everyone if they all map to the same lib though, and leave it up to the enduser to decide which ssl library they actually want to use.
