### ISSUE TITLE
[Composer\Downloader\TransportException]

### ISSUE THREAD

**Issue by dzanwari** [composer/composer#5921]
The "https://packagist.org/packages.json" file could not be downloaded: php_network_getadd
  resses: getaddrinfo failed: Name or service not known
  failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not k
  nown

**Comment by rameshsrinivasan** [comment]
I got below error on composer update cmd.

composer diag
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: WARNING
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: SSL/TLS already set-up for this stream
failed to open stream: Cannot connect to HTTPS server through proxy
Checking HTTP proxy: FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: SSL/TLS already set-up for this stream
failed to open stream: Cannot connect to HTTPS server through proxy
Checking HTTP proxy support for request_fulluri: OK
Checking HTTPS proxy support for request_fulluri: WARNING
Unable to assess the situation, maybe github is down (The "https://api.github.com/repos/Seldaek/jsonlint/zipball/1.0.0" file could not be downloaded: SSL: An existing connection was forcibly closed by the remote host.

send of 88 bytes failed with errno=10054 An existing connection was forcibly closed by the remote host.

failed to open stream: Cannot connect to HTTPS server through proxy)
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: SSL: An existing connection was forcibly closed by the remote host.

send of 88 bytes failed with errno=10054 An existing connection was forcibly closed by the remote host.

failed to open stream: Cannot connect to HTTPS server through proxy
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version:

  [Composer\Downloader\TransportException]
  The "https://getcomposer.org/versions" file could not be downloaded: SSL: A
  n existing connection was forcibly closed by the remote host.
  send of 89 bytes failed with errno=10054 An existing connection was forcibl
  y closed by the remote host.
  failed to open stream: Cannot connect to HTTPS server through proxy


diagnose

**Comment by cristyan12** [comment]
I got the follow error when run command composer diagnose:
`composer diagnose`
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version:

  [Composer\Downloader\TransportException]
  The "https://getcomposer.org/versions" file could not be downloaded: SSL: Interruption of an existing connection by the remote host has been forced.
  send of 148 bytes failed with errno=10054 Interruption of an existing connection by the remote host has been forced.
  failed to open stream: HTTP request failed!


diagnose
