### ISSUE TITLE
Failed to load class with '\' at the beginning

### ISSUE THREAD

**Issue by xmav** [composer/composer#5923]
My `composer.json`:
```
{
    "name": "tst/tst",
    "description": "",
    "require": {
        "php": "^5.3.2 || ^7.0"
    },
    "autoload": {
        "psr-4": { "Namespaced\\": "Namespaced" }
    }
}
```

* Add file Namespaced\Bar.php
```
<?php

namespace Namespaced;

class Bar
{
}
```

* Add file test.php
```
<?php

$loader = require 'vendor/autoload.php';
var_dump($loader->findFile('Namespaced\\Bar'));
var_dump($loader->findFile('\\Namespaced\\Bar'));
```

* download latest composer (1.3)
curl -O https://getcomposer.org/composer.phar

* run ./composer.phar install
* run php -f test.php

Actual output:
/test_composer/test.php:4:
string(86) "/test_composer/vendor/composer/../../Namespaced/Bar.php"
/test_composer/test.php:5:
bool(false)

And I expected this to happen (get this with composer 1.2.2):
/test_composer/test.php:4:
string(86) "/test_composer/vendor/composer/../../Namespaced/Bar.php"
/test_composer/test.php:5:
string(86) "/test_composer/vendor/composer/../../Namespaced/Bar.php"

Looks like introduced in https://github.com/composer/composer/commit/2853e82400a113620e05504c52729c61b5a53f77#diff-02d8fd4e825f60819515851876a3e6e6

**Comment by stof** [comment]
PHP never passes the leading backslash when calling the autoloader, whch is why it is not supported.

**Comment by alcohol** [comment]
@stof actually, a very old deprecated version did, the following code was removed:

```
// work around for PHP 5.3.0 - 5.3.2 https://bugs.php.net/50731
if ('\\' == $class[0]) {
    $class = substr($class, 1);
}
```

@xmav update your php version.
