### ISSUE TITLE
composer update  not working

### ISSUE THREAD

**Issue by samsaifi** [composer/composer#5929]
![image](https://cloud.githubusercontent.com/assets/11800036/20828438/9a2f92ec-b89d-11e6-8dae-0daa306803ea.png)

**Comment by alcohol** [comment]
Can't really work with a screenshot. What do you expect from us?

**Comment by samsaifi** [comment]
@alcohol  i am trying to update my packages dependencies on local server with the help of these command " composer update "  but after pressing enter  they throwing error ->
[composer/downloader/transportexception] the http:/www.packagist.com/p/provider.....  1.1 bad 400 request

**Comment by Seldaek** [comment]
This seems to be due to a bad network, not much we can do..

**Comment by samsaifi** [comment]
thanks,  @Seldaek  i  solve my problem.
