### ISSUE TITLE
composer update error 255

### ISSUE THREAD

**Issue by moralesf1** [composer/composer#5939]
hi, after try "composer update" i get this errors 
![qweqweq](https://cloud.githubusercontent.com/assets/9494209/20867225/df7200c8-ba15-11e6-8c8f-7d38121faaea.jpg)
what does it mean?
this is composer.json
![qweqwe123](https://cloud.githubusercontent.com/assets/9494209/20867256/59e50ae4-ba16-11e6-8cb9-4511a7f22b8b.jpg)

**Comment by Seldaek** [comment]
That's an issue in the artisan script of laravel, we can't help with that here sorry. Please report it on their repo.
