### ISSUE TITLE
repositories: packagist.org=false is backwards-incompatible change

### ISSUE THREAD

**Issue by SvenRtbg** [composer/composer#5941]
My `composer.json`:

```json
{
    "name": "vendor/demo",
    "description": "Backwards-incompatible change",
    "require": {
        "composer/composer": "^1.0"
    },
    "repositories": {
        "packagist.org": false
    }
}
```

When I run this command (with Composer 1.2.2):

```
composer update
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing symfony/process (v2.8.14)
    Downloading: 100%

  - Installing symfony/finder (v2.8.14)
    Downloading: 100%

  - Installing symfony/filesystem (v2.8.14)
    Downloading: 100%

  - Installing psr/log (1.0.2)
    Downloading: 100%

  - Installing symfony/debug (v2.8.14)
    Downloading: 100%

  - Installing symfony/polyfill-mbstring (v1.3.0)
    Downloading: 100%

  - Installing symfony/console (v2.8.14)
    Downloading: 100%

  - Installing seld/phar-utils (1.0.1)
    Loading from cache

  - Installing seld/jsonlint (1.5.0)
    Downloading: 100%

  - Installing seld/cli-prompt (1.0.2)
    Loading from cache

  - Installing justinrainbow/json-schema (2.0.5)
    Loading from cache

  - Installing composer/spdx-licenses (1.1.5)
    Downloading: 100%

  - Installing composer/semver (1.4.2)
    Downloading: 100%

  - Installing composer/ca-bundle (1.0.6)
    Downloading: 100%

  - Installing composer/composer (1.2.3)
    Downloading: 100%

symfony/console suggests installing symfony/event-dispatcher ()
Writing lock file
Generating autoload files
```

And I expected this to happen:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package composer/composer could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

I have an upgrade problem now. I can continue to use the old `"packagist": false` way of disabling access to Packagist (everything relevant for our software is hosted locally), and Composer will continue to work. But as soon as any co-worker reads the documentation and gets the idea to update to the new schema, any instance of Composer that is older than 1.2.3 will start to IGNORE the forbidden Packagist access. So I'd not only have to (some day) update how to disable Packagist, but I primarily have to ensure everybody and every machine has the latest Composer installed.

I don't think such a change is warranted in a bugfix release, it rather looks like a backwards incompatible change, because the behaviour of older versions changes when encountering a newer `composer.json` scheme (the other way around, newer Composer versions encountering an older `composer.json`, works).

**Comment by stof** [comment]
this is not a BC breaking change, because the old ``packagist: false`` way still works.

If you use the new way, this is indeed not supported by older version of composer (and this will be true for *any* new features, as old versions cannot magically support them)

**Comment by SvenRtbg** [comment]
I know, but the documentation changes without a trace during a patch release, now stating that (without any connection to the Composer version to use) "packagist.org" is the way to do it.

And I do consider that a backwards-incompatible change because the new file format is now incompatible with the old software. And I do expect this to not happen during a patch release, and I'd hope not to encounter that during a minor release.

The `composer.json` file format has no version attached - it is intrinsically bound to the Composer software version. But the main use case of Composer is to read `composer.json` created by some OTHER Composer software version, and these two should either work (i.e. any version of the software should work with any version of the file), or complain about a version mismatch and suggest to update.

**Comment by SvenRtbg** [comment]
For comparison: The deprecation of `hash` vs. `content-hash` in `composer.lock` probably takes some releases, and it is on the roadmap for the 1.3 release to not create the `hash` entry anymore because it has been ignored for some time now (at least the 1.2 versions) if `content-hash` was present.

I consider this to be at the same level of incompatible changes of the file format - and it takes at least two minor releases to make that transition. Why rush the `packagist.org` change?

**Comment by alcohol** [comment]
We do not maintain multiple versions of the documentation because it is too much of a hassle. You are confusing documentation "BC" and actual code BC. Code wise, nothing will break for existing users. The documentation only applies to users running the latest version of Composer. If you do not run the latest version, then so be it. We can't please everyone.

**Comment by SvenRtbg** [comment]
Thank you for impolitely assuming that I confuse something. Existing users who do not run `composer selfupdate` daily, but who encounter newer versions of `composer.json` will see a different result. My perception was that Composer tried to roll out such changes gradually to allow as many users as possible to update and not be affected - at least waiting the 30, 60 or 90 days (or whatever the value) the current "outdated"-timer  waits to alert the user that he is using an outdated version.

The question remains why the deprecation of `hash` takes multiple minor releases (only affecting `composer.lock`, which I'd not consider a public API), but this has been rushed, affecting the publicly documented API?

**Comment by hkdobrev** [comment]
@SvenRtbg To answer your question partially - the `hash` removal from `composer.lock` was put for the next minor release not because it was considered public API, but to give it more time to be tested from users on the snapshot channel so any problems with it are fixed before released in a stable version.

**Comment by stof** [comment]
@alcohol however, I still argue that the online documentation should be the one of the maintenance branch (the 1.2 branch here) rather than of the dev branch, so that features don't appear in the online doc months before their availability. Most composer users will be on the stable channel.

**Comment by SvenRtbg** [comment]
@hkdobrev I consider the `composer.lock` to NOT be any kind API, as I said before.

The `packagist.org` change, however, doesn't even appear in the changelog, and the very least I'd say that the current situation has "issues" if the documented way of disabling Packagist is incompatible with all but the very latest stable patched release.

**Comment by alcohol** [comment]
>  Existing users who do not run composer selfupdate daily, but who encounter newer versions of composer.json will see a different result.

Repositories definitions only apply to root composer.json, so the odds of this actually occurring are rather slim, edge-case scenarios mostly. E.g. if you run `create-project` that is based off of a project that assumes you use the latest version of composer.

**Comment by alcohol** [comment]
@stof maybe, but we generally don't merge doc changes until they are in the latest release. E.g. the packagist.org change was in 1.3 afaik.

**Comment by SvenRtbg** [comment]
> Repositories definitions only apply to root composer.json so the odds of this actually occurring are rather slim, edge-case scenarios mostly.

You mean like developers in a corporate environment with local instances of Packagist/Satis and the requirement to NOT pull dependencies from Github directly for availability reasons.

**Comment by alcohol** [comment]
@SvenRtbg no that has nothing to do with it. Please read what I wrote, and make sure you understand what I mean by "root only".

**Comment by stof** [comment]
@alcohol but 1.3 is **not** released. This is my point.
And enforcing that the master branch does not contain documentation for unreleased features is bad, because it forces you to delay writing the doc while the current policy is to ask contributors to update the doc in the PR doing the change (only way to avoid forgetting to update it).
If you want to show only stable features in the doc, render it from the doc of the stable branch.

**Comment by alcohol** [comment]
@stof I am well aware of that, but this particular change we are discussing is part of `1.2.3`, which is released.

**Comment by Seldaek** [comment]
I think this is enough ink wasted. Take it privately if you really want to discuss this further.
