### ISSUE TITLE
Document autoloader optimization procedures

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#5947]
With https://github.com/composer/composer/pull/5559 we're adding yet another thing that may confuse people...

Here are the optimization levels we have:

- level0: regular autoloader
- level1: `--optimize-autoloader`
- level2: `--classmap-authoritative`
- level2: `--apcu-autoloader`

level1 should always be used in prod as it's risk free, but level2 autoloaders do carry some penalties and these trade-offs should be clearly documented in a new article about autoloading IMO.

**Comment by Seldaek** [comment]
Done at https://getcomposer.org/doc/articles/autoloader-optimization.md - happy to have someone review it for mistakes. /cc @nicolas-grekas

**Comment by nicolas-grekas** [comment]
LGTM, thanks for the doc!

**Comment by stof** [comment]
@Seldaek I would add a note sayign that you should not turn on any of these optimizations in your development environment:

- level 2 optimizations are destroying the DX entirely:
    - 2/A requires redumping the autoloader each time you add or remove a class
    - 2/B requires clearing APCu each time you add or remove a class (and clearing APCu is a pain as it needs to be done separately for each SAPI)
- level 1 optimization leads to weird errors when removing a class (which was there at the time of dumping the optimized autoloader), as the autoloader will assume it exists and will require the file, leading to a broken ``class_exists`` check. So this optimization does not have any trade-off in prod (unless you magically delete files between deployments), but it has trade-offs in dev.

**Comment by Seldaek** [comment]
Yup I hinted at the fact this is for production but might be good to emphasize it some more

**Comment by stof** [comment]
And this is something necessary. See https://github.com/symfony/symfony-standard/pull/1048 for a case where people wanted to optimize things, but adding the key in the composer.json rather than in the ``$COMPOSER_HOME/config.json`` of the prod server would impact dev environments too.

**Comment by stof** [comment]
Maybe we should hint a level 0 optimization too: using a more specific prefix in your autoload config, so that only your own classes are checked inside your package instead of checking your package for classes of another of your packages (there is some benefit for dev setups there).
This is mostly a recommendation for libraries btw. But this may be more suited as a note in the doc about ``autoload`` in the schema rather than on this page.
