### ISSUE TITLE
Latest composer seems to be giving non-stable version 1.3-dev

### ISSUE THREAD

**Issue by rooboy35** [composer/composer#5948]
My `composer.json`:

```
n/a
```

Output of `composer diagnose`:

```
n/a
```

When I run this command:

```
wget https://getcomposer.org/composer.phar;
php composer.phar
```

I get the following output:

```
Composer version 1.3-dev (e54c7478ee1207e60b0a345391a80b3511886429) 2016-12-07 00:02:55
```

And I expected this to happen:
```
Composer version 1.2.4 2016-12-06 22:00:51
```

Should we expect to see 1.2.4 at this point instead of the dev release? 
We have recently been seeing some "transport exception" issues on some servers doing new installs and wondering if that's since we started getting 1.3-dev.

thanks!

**Comment by alcohol** [comment]
`https://getcomposer.org/composer.phar` always points to the latest `--snapshot`, not `--stable` release.

**Comment by alcohol** [comment]
See https://getcomposer.org/download/ page for direct stable release download links.

**Comment by PascalBrouwers** [comment]
I can confirm this issue. Allot of servers now have the 1.3-dev version of composer instead of the stable one.

**Comment by xabbuh** [comment]
@PascalBrouwers This is expected. If you download the latest snapshot from that URL you can then run `composer self-update --stable` to get the latest stable version.

**Comment by PascalBrouwers** [comment]
@xabbuh I don't think you get it. At some point the latest stable composer was pointing to unstable 1.3-dev. Allot of servers auto update their software and so an unstable version was installed.

**Comment by xabbuh** [comment]
@PascalBrouwers If you download the snapshot from https://getcomposer.org/composer.phar you will run into these kind of problems again. That's why I mentioned the `--stable` option of the `self-update` command.
