### ISSUE TITLE
Wrong package dist URL in composer.lock for sub-dependency

### ISSUE THREAD

**Issue by rask** [composer/composer#5949]
Composer generates wrong repository dist URL for subsubdomains in composer.lock.

Assuming I have a following structure:

```
vendor/main-project
|
--> vendor/package-a:dev-master
     |
     --> vendor/package-b:^0.1
```

`main-project` is the one where `composer.lock` get messed up. `package-a` requires `package-b` which is located in a Satis repo at `https://subsub.sub.foobar.com`. The `composer.json` in `main-project` and `package-a` contains the following:

```json
"repositories": [
    {
        "type": "composer",
        "url": "https://subsub.sub.foobar.com"
    }
]
```

The `composer.lock` file for `package-a` generates properly, and the `^0.1` version of `package-b` gets a dist URL as such: `https://subsub.sub.foobar.com/dist/vendor-package-b-0.1.0-abcd1234.zip`.

But when I run `composer update` inside `main-project` the lockfile gets a bit mangled up. Instead of a proper dist URL the `package-b` gets the following: `https://sub.foobar.com/dist/vendor-package-b-0.1.0-abcd1234.zip`. Notice the missing `subsub` sub-domain.

After this our CI server reports 404s as the dist cannot be found, and the package is then loaded from Git source instead.

This is happening with the latest Composer (1.2.4) and PHP 7.0 on Ubuntu.

Let me know if more info is needed.

**Comment by rask** [comment]
I attempted to hack a fix by replacing the lockfile URL with the correct one, but the composer.lock file contains a checksum which is seemingly generated from the (incorrect) URL. This leads to a proper URL (no 404) but an invalid checksum.

Any idea how to replace the checksum properly with a Bash script?

**Comment by alcohol** [comment]
Just to clarify, you do not have a satis repository running @ https://sub.foobar.com ?

**Comment by alcohol** [comment]
Also please include the composer.json of all 3 packages.

**Comment by rask** [comment]
I have a satis repository running at https://subsub.sub.foobar.com, which is using basic authentication. sub.foobar.com doesn't contain anything.

Here are the composer.json files. I had to change them because of NDAs and so on.

- `main-project`: http://pastebin.com/pB8i7gFq
- `package-a`: http://pastebin.com/NzvPT98H
- `package-b`: http://pastebin.com/yNYw8nRm

`main-project` is a `type: project`. `package-a` is a VCS PHP package, `package-b` is a private package which sits at `subsub.sub.foobar.com` Satis.

**Comment by alcohol** [comment]
@Seldaek peculiar issue here, any idea what could cause this?

**Comment by rask** [comment]
The _only_ thing I can think of is that Composer is somehow looking up a server domain by IP when generating a repo URL? Did not have time to try this assumption yet though.

**Comment by alcohol** [comment]
Fairly confident that we do not do any lookups based on ip or domain.

**Comment by alcohol** [comment]
I _think_ the dist url simply gets generated by satis. Can you check the satis json files and see if they contain the correct url? Also make sure your are working with a clean cache directory (probably will not solve anything, but for debugging purposes it is **always** best to work with a clean slate).

**Comment by rask** [comment]
I've rebuilt the package repo a few times already, every time the package definitions display `subsub.sub.foobar.com`, as per the config used to build (repo URL and dist-prefix)

**Comment by Seldaek** [comment]
Auto-closing this as it's marked as support request and has not received any update in a long time.
