### ISSUE TITLE
SSL: Connection reset by peer - Failed to enable crypto

### ISSUE THREAD

**Issue by vs1785** [composer/composer#5953]
My `composer.json`:

{
}

Output of `composer diagnose`:

Do not run Composer as root/super user! See https://getcomposer.org/root for details
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: WARNING
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: SSL: Connection reset by peer
Failed to enable crypto
failed to open stream: operation failed
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK

When I run this command:
 composer global require "laravel/installer"

I get the following output:

Changed current directory to /root/.config/composer
Do not run Composer as root/super user! See https://getcomposer.org/root for details

  [Composer\Downloader\TransportException]
  The "https://packagist.org/packages.json" file could not be downloaded: SSL: Connection reset by peer
  Failed to enable crypto
  failed to open stream: operation failed

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

I have downloaded certificate from 

http://curl.haxx.se/ca/cacert.pem

Copied it to 

/etc/pki/tls/cert.pem

PHP INI is also modified accordingly

 php -r "print_r(openssl_get_cert_locations());"
Array
(
    [default_cert_file] => /etc/pki/tls/cert.pem
    [default_cert_file_env] => SSL_CERT_FILE
    [default_cert_dir] => /etc/pki/tls/certs
    [default_cert_dir_env] => SSL_CERT_DIR
    [default_private_dir] => /etc/pki/tls/private
    [default_default_cert_area] => /etc/pki/tls
    [ini_cafile] => /etc/pki/tls/cert.pem
    [ini_capath] =>
)

php -i | grep openssl
openssl
Openssl default config => /etc/pki/tls/openssl.cnf
openssl.cafile => /etc/pki/tls/cert.pem => /etc/pki/tls/cert.pem
openssl.capath => no value => no value

PHP version is 
rpm -qa | grep php
php70w-common-7.0.13-1.w7.x86_64
php70w-7.0.13-1.w7.x86_64
php70w-process-7.0.13-1.w7.x86_64
php-tcpdf-dejavu-sans-fonts-6.2.11-1.el7.noarch
php70w-cli-7.0.13-1.w7.x86_64
php70w-mysql-7.0.13-1.w7.x86_64
php70w-bcmath-7.0.13-1.w7.x86_64
php70w-tidy-7.0.13-1.w7.x86_64
php70w-mbstring-7.0.13-1.w7.x86_64
php-php-gettext-1.0.11-12.el7.noarch
php-tcpdf-6.2.11-1.el7.noarch
phpMyAdmin-4.4.15.8-2.el7.noarch
php70w-pdo-7.0.13-1.w7.x86_64
php70w-xml-7.0.13-1.w7.x86_64
php70w-gd-7.0.13-1.w7.x86_64

Openssl version is

rpm -qa | grep openssl
openssl-1.0.1e-51.el7_2.7.x86_64
openssl-devel-1.0.1e-51.el7_2.7.x86_64
openssl-libs-1.0.1e-51.el7_2.7.x86_64

I am lost at this moment. Please guide me to fix this ?

**Comment by alcohol** [comment]
I recommend you use the search function and look for other issues and possible solutions in there.

**Comment by vs1785** [comment]
Thank you for the reply.

I did searched in other issues and tried them but still not able to figure out the issue.

Is there any way i can get more information from output? I tried -vvv but still got same error i.e. Connection reset by peer. 

It would be a great help if anyone can point me in right direction

I am trying to install laravel and here is my output

[root@localhost ~]# composer global require "laravel/installer" -vvv
Changed current directory to /root/.config/composer
Reading ./composer.json
Loading config file /root/.config/composer/config.json
Loading config file /root/.config/composer/auth.json
Loading config file ./composer.json
Loading config file /root/.config/composer/auth.json
Reading /root/.config/composer/auth.json
Checked CA file /etc/pki/tls/cert.pem: valid
Executing command (/root/.config/composer): git branch --no-color --no-abbrev -v
Executing command (/root/.config/composer): git describe --exact-match --tags
Executing command (/root/.config/composer): git log --pretty="%H" -n1 HEAD
Running 1.2.4 (2016-12-06 22:00:51) with PHP 7.0.13 on Linux / 3.10.0-327.36.1.el7.x86_64
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Downloading https://packagist.org/packages.json
Downloading https://packagist.org/packages.json
Downloading https://packagist.org/packages.json


  [Composer\Downloader\TransportException]
  The "https://packagist.org/packages.json" file could not be downloaded: SSL: Connection reset by peer
  Failed to enable crypto
  failed to open stream: operation failed


Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Util/RemoteFilesystem.php:482
 Composer\Util\RemoteFilesystem->get() at phar:///usr/local/bin/composer/src/Composer/Util/RemoteFilesystem.php:101
 Composer\Util\RemoteFilesystem->getContents() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:665
 Composer\Repository\ComposerRepository->fetchFile() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:479
 Composer\Repository\ComposerRepository->loadRootServerFile() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:258
 Composer\Repository\ComposerRepository->hasProviders() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:99
 Composer\DependencyResolver\Pool->addRepository() at phar:///usr/local/bin/composer/src/Composer/Command/InitCommand.php:596
 Composer\Command\InitCommand->getPool() at phar:///usr/local/bin/composer/src/Composer/Command/InitCommand.php:632
 Composer\Command\InitCommand->findBestVersionForPackage() at phar:///usr/local/bin/composer/src/Composer/Command/InitCommand.php:365
 Composer\Command\InitCommand->determineRequirements() at phar:///usr/local/bin/composer/src/Composer/Command/RequireCommand.php:110
 Composer\Command\RequireCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:847
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:231
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:104
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Command/GlobalCommand.php:81
 Composer\Command\GlobalCommand->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:847
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:231
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:104
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:24

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

**Comment by vs1785** [comment]
It turned out to be an issue from my ISP

They have had issues with getting to packagist.org website. They fixed it and now it is working fine.

Thank you for your support.

**Comment by abenbrahim78** [comment]
Hello,

Same problem since yesterday (Composer 1.9.1).

Have you observed this problem ?
