### ISSUE TITLE
Feature Request: require-one

### ISSUE THREAD

**Issue by paragonie-scott** [composer/composer#5955]
Due to the existence of polyfill libraries in the PHP ecosystem, I'd like to propose a new require directive called `require-one`. At its highest level, it will be an array of objects. For each array member, at least one of the items must be installed. Order matters (as soon as a requirement is satisfied, it skips the rest).

```json
{
    "require-one": [
        {
            "php": "^7",
            "paragonie/random_compat": "^1|^2"
        },
        {
            "php": "^7.2",
            "ext-libsodium": "^1.0.6"
        }
    ]
}
```

In this example, if you're on PHP 7.2, no additional dependencies are required. If you're on PHP 7.0 through 7.1-latest, you need the libsodium extension from PECL. If you're on PHP 5.6, you need random_compat as well.

**Comment by kelunik** [comment]
Your example looks wrong. It combines 7.0 and random_compat instead of 5.6 and random_compat. Same for 7.2 and Sodium.

**Comment by paragonie-scott** [comment]
It's as intended. It should read as:

* You need one of the following:
  * PHP 7+
  * random_compat
* You need one of the following:
  * PHP 7.2+
  * PECL libsodium 1.0.6+

It's literally "at least one of the following is required" not "this is required if the other requirement in the list is met"

Think if-else, not relational.

**Comment by kelunik** [comment]
@paragonie-scott It reads more like

*You need either*

* PHP 7+
* random_compat

*or*

* PHP 7.2+
* PECL libsodium 1.0.6+

How about sets of packages where you either need those two, or that one?

```json
{
  "require-one": [
    [
      {"php": "^7"},
      {"paragonie/random_compat": "^1|^2"}
    ],
    [
      {"php": "^7.2"},
      {"ext-libsodium": "^1.0.6"}
    ]
  ]
}
```

**Comment by alcohol** [comment]
Considering how many people fully understand the solver, the likelihood that any new features (one-of, any-of, etc) will be implemented are slim to none.

**Comment by narfbg** [comment]
Being the second person replying, how do you know how many people do or don't understand it? I fully understood it right off the bat, though it might be because I've wanted a similar feature myself.

Perhaps the syntax can be improved to make the intent clearer. Here's how it could fit into the `require` scheme:

    {
        "require": [
            "oneOf": [
                {"php": "^7"},
                {"paragonie/random_compat": "^1|^2"}
            ]
        ]
    }

**Comment by hkdobrev** [comment]
@narfbg I think @alcohol was referring to how many people understand the logic and codebase for the solver inside of Composer source code, not how many people understand the syntax of the feature request.

**Comment by alcohol** [comment]
@narfbg exactly what @hkdobrev said. I understand the feature requested. I care very little about the implementation details at this point because as I said, it is unlikely anyone will actually implement it, since very few people know how the solver works.

**Comment by narfbg** [comment]
I see ... Sorry about that then, my bad.

**Comment by alcohol** [comment]
Don't get me wrong, I do not want to discourage this feature request. It has been asked many times before, not always in the same form but often with the same or similar intent (some sort of conditional requirements). It just isn't easy to implement this.

**Comment by stof** [comment]
thus, it could make dealing with the lock file much harder (as the chosen alternative will be locked too)

**Comment by hkdobrev** [comment]
If you use it for a project, better just define `config.platform` and resolve these conditions manually.  As @stof said it would create problems with `composer.lock`.

I can see this being very useful for repositories specifically made to be used with `composer create-project`. Then it would install (and lock) the dependencies needed based on your system.

However, for a library, I'd recommend just install the polyfills you need every time and try to be aggressive in requiring newer PHP versions and removing polyfills in new major versions.

**Comment by alcohol** [comment]
One solution I could see, while being less user-friendly, would be the following:

Assume core package `foo/bar` requires one of:
- `php: >= 7.1`
- `php: < 7.1`, `lib_compat: *`

Instead, make `foo/bar` require `foo/bar-x`, which is merely a metapackage.

Then create package `foo/bar-x-php` which is also a metapackage which only has `require: php: >= 7.1`, and have it [`provide: foo/bar-x`](https://getcomposer.org/doc/04-schema.md#provide).

Also create package `foo/bar-x-compat` which is also a metapackage which only has `require: php: < 7.1, lib_compat: *`, and also have it [`provide: foo/bar-x`](https://getcomposer.org/doc/04-schema.md#provide).

Let the user chose how to fulfill the requirement.

Very inconvenient and elaborate, but just thinking outside of the box here.

**Comment by stof** [comment]
@alcohol using such metapackage would be exactly what the solver would have to do internally to implement the feature anyway.

**Comment by Seldaek** [comment]
See https://github.com/composer/composer/issues/751 and https://github.com/composer/composer/issues/2940 for previous discussions on this topic.. And I still think it's not worth the trouble/complexity this would introduce. Having a few extraneous files installed for the few cases where polyfills are required and present isn't that dramatic.
