### ISSUE TITLE
Error in vendor>composer>autoload_static.php - Laravel 5.3.26

### ISSUE THREAD

**Issue by GNSubrahmanyam** [composer/composer#5956]
- Laravel Version: 5.3.26
- PHP Version: 5.6.28
- Database Driver & Version: MySQl
- Description: Error in vendor>composer>autoload_static.php - Laravel 5.3.26

```
public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit03e973073eea0174c457e95793a7c992::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit03e973073eea0174c457e95793a7c992::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit03e973073eea0174c457e95793a7c992::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit03e973073eea0174c457e95793a7c992::$classMap;

        }, null, ClassLoader::class);
    }
```
![15326254_1909838442586240_8481580461390228856_o](https://cloud.githubusercontent.com/assets/18217008/21039965/cf5388ba-be07-11e6-8f6b-21b112d61b40.jpg)

several times i ran composer dump-autoload command then also the error remains same.
How to fix this error. 

Thanks in Advance

**Comment by alcohol** [comment]
What error? It is ok that your IDE does not understand what is going on here.

**Comment by alcohol** [comment]
Those attributes are private, but because of the scope of the closure we can write to them. However, PHPStorm does not understand that.

**Comment by topcheese13** [comment]
Here is how you can exclude the faulty file from inspection.

https://stackoverflow.com/questions/11129857/how-to-exclude-files-folders-from-code-inspection-in-phpstorm/28077393#28077393
