### ISSUE TITLE
Pass current PHP_BINARY to composer scripts

### ISSUE THREAD

**Issue by ArminVieweg** [composer/composer#5957]
On some server configurations I need to use a different php binary than `php`. On german provider Mittwald for example you have to use `php_cli` on command line.

I want to trigger some binaries in scripts section in composer.json. Those binaries are served by some dependencies and are written in php. So they've got a shebang like `#!/usr/bin/env php` and are executable.

Here is an example of such a script call:
```
"scripts": {
        "post-autoload-dump": [
            "bin/example abc123"
        ]
    },
```
What composer does is executing this script (./bin/example) on shell. So even if I call 

```
php_cli composer.phar dump
```

Composer calls the script with `./bin/example`, which will use `php` instead of `php_cli` (because of missing prepending php binary and shebang which defined to use `php`).

So my idea (and feature request) is to add the possibility to prepend current PHP_BINARY in scripts section to script calls. The example above could look like this, then:

```
"scripts": {
        "post-autoload-dump": [
            "{$php-binary} bin/example abc123"
        ]
    },
```
And if composer passes `PHP_BINARY` to this variable I am able to use the same configuration on different environments. Because locally I've got `php` available on cli and I really don't want to update composer.json for each environment.

So I hope you like my idea of this additional php-binary variable. In that case I would try to provide a pull request :)

Thanks in advance
Armin

**Comment by ArminVieweg** [comment]
I've checked the source of composer a little bit and in `\Composer\EventDispatcher\EventDispatcher::doDispatch` I've found the `\Symfony\Component\Process\PhpExecutableFinder`. Great! 

Composer uses it already when using e.g. `@composer update` in scripts section. So this would be a perfect point to introduce `@phpbin` (or however you want to name it) which just get replaced with the result of `$phpExecutableFinder->find()`.

**Comment by ArminVieweg** [comment]
I've checked the source of composer a little bit and I am a little bit confused at this point. In `\Composer\EventDispatcher\EventDispatcher::doDispatch` you replace `@composer` with `\Symfony\Component\Process\PhpExecutableFinder::find()` which is not necessary the same binary, which called composer before. Why not using `PHP_BINARY`?

PhpExecutableFinder is always looking for `php` binary. I can overwrite this with using the environment variable `PHP_PATH`. Or I can set `HHVM_VERSION`, because this will return 

```
if (defined('HHVM_VERSION')) {
   return (getenv('PHP_BINARY') ?: PHP_BINARY).$args;
}
```
But all this just will fix problems with `@composer` in scripts section, if php binary is called differently. 
In case I call my php script as executable, `Composer\Util\ProcessExecutor` is involved.

But we could add another elseif there, which listens to `@php` and passes the `PHP_BINARY` directly, or using PhpExecutableFinder, which is configurable like described above.

**Comment by ArminVieweg** [comment]
I've found a solution to improve the execution of scripts, and put this to an own package: https://bitbucket.org/InstituteWeb/composer-scripts

```
"scripts": {
    "post-autoload-dump": [
        "\\InstituteWeb\\ComposerScripts\\ImprovedScriptExecution::apply",
        "@php -v"
    ]
}
```

So I am replacing `@php` with PHP_BINARY and on windows I am updating the directory separators. This takes effect for all commands after the callable script.

So this makes my request optional.

**Comment by Seldaek** [comment]
> Why not using PHP_BINARY?

Because it's only available on 5.5+ (IIRC). But the PhpExecutableFinder returns PHP_BINARY if it is defined.

Anyway I'll add `@php` support as it's easy enough and should help in such cases where you have non-standard PHP binaries.

**Comment by helhum** [comment]
> I'll add @php support as it's easy enough and should help in such cases where you have non-standard PHP binaries

Nice, thanks!

**Comment by ArminVieweg** [comment]
Thanks. Okay PHP support for older versions was not on my schedule. Thank you very much. 

Btw. when I've implemented it I had problems on windows because you can't call a batch file with php. Nor the shell script. For this case I fetch the path to php script from batch file. Maybe you have a better idea. Thanks, again.
