### ISSUE TITLE
Extra Values - a max depth of 3 levels

### ISSUE THREAD

**Issue by cambri** [composer/composer#5958]
From [Composer Docs](https://getcomposer.org/doc/03-cli.md#modifying-extra-values) Extra Values - a max depth of 3 levels 

I'm trying to use the wikimedia/merge-plugin from command line and can't use the include array as it nests to four levels { extras { merge-plugin { include { fourth level

Is there a reason to support only 3 depth levels?  Are there issues with supporting more depth levels? etc...

**Comment by Seldaek** [comment]
We only support 3 levels because it allows you to set domains like extra.foo.example.org => extra > foo > example.org. But that's only for the CLI command, if you edit the json by hand you can add as many levels as you wish really.

**Comment by sascha-egerer** [comment]
@Seldaek It would make more sense to escape the `.` if you need them in the string, doesn't it?
I've the same problem currently as i try to set a config for https://github.com/cweagans/composer-patches via CLI wich is not possible due to the 3 level limitation.
What do you think about changing that behavior?

**Comment by Seldaek** [comment]
Yeah maybe it would, but that'd also break BC..  Maybe we could add a new syntax for it, like `composer config 'extra > foo > bar > baz' value`, or just using spaces maybe? `composer config 'extra foo bar bar baz' value`. Both of these would require quoting though, but at least it makes it possible.

**Comment by sascha-egerer** [comment]
I think adding spaces would also be a breaking change as somebody does this already.
Maybe we can add some kind of configuration to keep the old behavior as default and add a warning that this behaivor will change in the next minor version?
That's a bit ugly but would be a way to make it not breaking yet.
And what about introducing "versions" for the composer.json format?

**Comment by Seldaek** [comment]
I don't think spaces in json keys are very widespread.. never seen it at least, but I might be wrong of course :) ` > ` surely is fairly safe.

**Comment by sascha-egerer** [comment]
Hm yeah it's save. But it's ugly too ;-)

What about passing a json object in?

```
composer config '{extra: { foo: { bar: { baz: 'value' }}}}'
```

**Comment by Seldaek** [comment]
That doens't seem less ugly really.. and not sure how to handle merging 
and stuff in this case, it opens up a lot of questions. This whole thing 
is probably not really needed to be honest. There are only a few cases 
where this is needed as we avoid deep nesting in composer itself at least.
