### ISSUE TITLE
Issue of "scripts" section...

### ISSUE THREAD

**Issue by adamasantares** [composer/composer#5960]
Hi, I don't understand why "post-package-install" doesn't work for my package.
Can anyone point what I did wrong?
I tryed different command in "scripts" section, but no one of them works :(

My `composer.json`:

```json
{
  "name": "adamasantares/migra-php",
  "description": "description",
  "keywords": ["php"],
  "type": "library",
  "minimum-stability": "dev",
  "prefer-stable" : true,
  "license": "MIT",
  "authors": [
    {
      "name": "Me",
    }
  ],
  "require": {
    "php": ">=7.0.0"
  },
  "scripts": {
    "post-package-install": [
      "bash chmod +x ./vendor/adamasantares/migra-php/migra",
      "bash ln -s ./vendor/adamasantares/migra-php/migra ./migra"
    ]
  }
}
```

Thank you.

**Comment by alcohol** [comment]
Can you be more specific than just "doesn't work"?

**Comment by adamasantares** [comment]
@alcohol Hi,

well, after I installed the package, I don't see that one of "scripts command" was executed.
I tryed different commands to check, like 

```
  "scripts": {
    "post-package-install": [
      "php -r \"file_put_contents('./test.txt', 'HEY!')\"",
      "php testfile.php"
    ]
  }
```

But when I looked at directory, I didn't seen "test.txt" or any other traces of scripts execution.

May be I missed something?

**Comment by alcohol** [comment]
Ok. Can you be more specific about which composer.json you added this to? Is it in the root composer.json of your project? Or is it in the composer.json of a dependency?

**Comment by Seldaek** [comment]
The right way to do this really is to publish the binary using "bin" https://getcomposer.org/doc/articles/vendor-binaries.md

**Comment by stof** [comment]
Are you sure it is a root composer.json ? ``vendor/adamasantares/migra-php/migra`` does not make sense if your ``adamasantares/migra-php`` is the root package.

**Comment by alcohol** [comment]
@adamasantares are you working directly on `adamasantares/migra-php`, or are you installed `adamasantares/migra-php` as a dependency of another project?

**Comment by adamasantares** [comment]
@alcohol 

Hi Rob, I think I understand my mistake, sorry for disturb.
