### ISSUE TITLE
composer validate project that will not be published

### ISSUE THREAD

**Issue by marcovtwout** [composer/composer#5961]
When I run this command:

```
composer validate --no-check-publish
```

I get the following output:

```
./composer.json is valid for simple usage with composer but has
strict errors that make it unable to be published as a package:
See https://getcomposer.org/doc/04-schema.md for details on the schema
name : The property name is required
description : The property description is required
```

And I expected this to happen:

```
./composer.json is valid
```

Or maybe we can even specifiy in composer.json that the project is not meant to be published, so `composer validate` would just work. For example, by denoting `publish: false`? I'm trying out SensioLabsInsight which simply runs 'composer validate' and lists the errors.

**Comment by alcohol** [comment]
Output is not what matters here, exit code is. What exit code is returned?

**Comment by marcovtwout** [comment]
composer validate returns 2.
composer validate -no-check-publish returns 0.

You are right, technically there is nothing wrong with the composer command and the --no-check-publish option is good.

I would like to make this a feature request for composer to automatically determine if --no-check-publish should be used, for example when `publish: false` is present in composer.json. That way I can just use `composer validate` on any project without having to specify externally if it is a publishable project or not.

**Comment by alcohol** [comment]
We are not going to add an attribute to the composer.json schema for something like this, sorry.

**Comment by marcovtwout** [comment]
Alright, understood :) Just an idea.
