### ISSUE TITLE
Composer creates directories with different permissions on different servers

### ISSUE THREAD

**Issue by PatrickRose** [composer/composer#5964]
We've just done a deployment which included a composer update, and hit a permissions issue:

 * Last week, developer A updated a dependency to a newer version - everything was successful
 * This week, developer B updated that dependency to an even newer version to apply a hotfix. On two of our production servers, it was successful but on the others there were incorrect permissions (group write wasn't set), so it failed to delete the old files.

After fixing the permissions and running the `composer install` again, we checked the permissions and on two of our servers the directory was created with 0775 permissions and on the others it was created with 755. The umask is the same for each server.

```
$ composer.phar --version
Composer version 1.2.1 2016-09-12 11:27:19
```

**Comment by alcohol** [comment]
Composer does not randomly pick different permissions. If they differ, it is not due to composer, but rather either the source, or environment.

**Comment by PatrickRose** [comment]
Our environment should be the same between the various servers (it's all handled by puppet), but the permissions are different for one package in particular:

```
me@server1 $ ls -l vendor/league
total 12
drwxrwsr-x 4 usera group 4096 Dec  6 18:19 flysystem
drwxrwsr-x 4 usera group 4096 Dec  6 18:19 flysystem-rackspace
drwxrwsr-x 3 userb  group 4096 Dec 13 18:52 flysystem-sftp
```

```
me@server2 $ ls -l vendor/league
total 12
drwxrwsr-x+ 4 usera group 4096 Dec  6 18:31 flysystem
drwxrwsr-x+ 4 usera group 4096 Dec  6 18:31 flysystem-rackspace
drwxr-sr-x+ 3 userb  group 4096 Dec 13 18:57 flysystem-sftp
```

I don't see why flysystem-sftp should be treated differently on two different servers when the other league packages we use are being created with `0775`

**Comment by alcohol** [comment]
And this is with a clean install from scratch? Not running update or install over an existing project?

**Comment by Seldaek** [comment]
Auto-closing this as it's marked as support request and has not received any update in a long time.
