### ISSUE TITLE
Suggestion: 'Optimise composer.json' command to prevent memory usage

### ISSUE THREAD

**Issue by stefandoorn** [composer/composer#5965]
I'm running lately into some memory usage problems, which can be temporary worked around by setting a higher memory limit. I read before that this is mainly due to large trees having to be build for all versions that potentially match your requirements specified in composer.json.

So let's say a project is at version 3.8.3, while in my composer.json (internal project, not a library) is specified something like ^3.1, and let's assume in the meanwhile 100 releases have been done, this results in a huge list. Practically seen, lots of projects could up their composer.json requirement after installing and testing the new version, reverting is hardly ever done. This applies less to library development.

I might be overlooking something, but it feels like this could prevent a lot of tree building and memory usage, as the requirements will be more strict. In the example above, ^3.8 might be a better requirement at this time and it will prevent all versions from 3.1 - 3.7 to be evaluated. 

Is this something interesting to add? I don't have any knowledge of the Composer codebase, but am willing to support in development. It would also be good ofcourse to start with an evaluation of the real gain, I haven't done that research yet.

**Comment by alcohol** [comment]
This is something I generally already do in any **application** I work on. The same does not apply to libraries. Those rather want to support a range as broad as possible. It's not a lot of work to do this manually (if you do it consistently), so I am not sure building an entire command for this is justified.

**Comment by stefandoorn** [comment]
I also overlooked the 'outdated' command I see now, which is also already a great help on this matter.

**Comment by Seldaek** [comment]
Closing as I don't think this is really practical
