### ISSUE TITLE
the version that composer get is bad

### ISSUE THREAD

**Issue by emimarz** [composer/composer#5966]
My `composer.json`:
```
{
    "config": {
        "platform": {
            "php": "5.3.3"
        }
    },
    "require": {
        "silex/silex": "1.2.*",
        "twig/twig": ">=1.8.0,<2.0-dev",
        "symfony/twig-bridge": "~2.3,<2.7",
        "twig/extensions": "1.2.*@dev",
        "monolog/monolog": "~1.4,>=1.4.1",
        "vrana/notorm": "dev-master",
        "mobiledetect/mobiledetectlib": "dev-master",
        "symfony/security": "2.6.*"
    }
}
```
Output of `composer diagnose`:
```
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.vrana/notorm : unbound version constraints (dev-master) should be avoided
require.mobiledetect/mobiledetectlib : unbound version constraints (dev-master) should be avoided
Checking platform settings: WARNING
Your PHP (5.3.3-7+squeeze19) is quite old, upgrading to PHP 5.3.4 or higher is recommended.
 Composer works with 5.3.2+ for most people, but there might be edge case issues.
The OpenSSL library (0.9.8o) used by PHP does not support TLSv1.2 or TLSv1.1.
If possible you should upgrade OpenSSL to version 1.0.1 or above.

Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```
When I run this command:

composer install --no-interaction --no-dev --prefer-dist -o

I get the following output:
```
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/debug v2.8.15 -> satisfiable by symfony/debug[v2.8.15].
    - symfony/debug v2.8.15 requires php >=5.3.9 -> your PHP version (5.3.3) does not satisfy that requirement.
  Problem 2
    - symfony/debug v2.8.15 requires php >=5.3.9 -> your PHP version (5.3.3) does not satisfy that requirement.
    - symfony/http-kernel v2.6.13 requires symfony/debug ~2.6,>=2.6.2 -> satisfiable by symfony/debug[v2.8.15].
    - Installation request for symfony/http-kernel v2.6.13 -> satisfiable by symfony/http-kernel[v2.6.13].
```
And I expected this to happen:

I have PHP 5.3.3 and I can't change it

the problem is this line
symfony/http-kernel v2.6.13 requires symfony/debug ~2.6,>=2.6.2 -> satisfiable by symfony/debug[v2.8.15]

symfony/http-kernel v2.6.13 needs symfony/debug ~2.6,>=2.6.2 and exists a symfony/debug[v2.6.15] that have a requirement of PHP 5.3.3 but instead that composer install or want installl 2.8.15 that require a newer PHP then I can't deploy my app

**Comment by alcohol** [comment]
You are running install, and you have a lock file. In this scenario, composer will not do dependency resolving, but instead it will directly proceed to installing the versions specified in the lock file. It appears that the lock file was generated on a system that is not running php `5.3.3` (also, it is out of sync, which is generally a bad sign).

Please run either update, or attempt to determine who generated this lock file and why it is not compatible with php `5.3.3`.

**Comment by emimarz** [comment]
Nobody create the file .lock 
Only composer, it is a fresh installation

**Comment by alcohol** [comment]
> Installing dependencies from lock file

There was a lock file already.

**Comment by emimarz** [comment]
yeah, but was composer who created that file

**Comment by alcohol** [comment]
Repeating yourself is not going to change anything about the situation. I explained what is wrong, and how you can resolve it. Go resolve it.

**Comment by hkdobrev** [comment]
I think reading the manual would help here - https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file

Composer is supposed to do that. Its purpose is to lock the dependencies versions and to update them only when you've explicitly wanted Composer to do so.

**Comment by alcohol** [comment]
Yes but it seems like the lock file they have was generated on a different system (environment). And now composer is trying to install dependencies that are not compatible with the system (environment) they are currently on.

**Comment by hkdobrev** [comment]
Probably the `platform` configuration was added without updating the lock file.

**Comment by emimarz** [comment]
I fix it removing composer.lock file. Thanks all for your help.
