### ISSUE TITLE
Suggesting to install xdebug even if installed it

### ISSUE THREAD

**Issue by issei-m** [composer/composer#5967]
It might be caused by XdebugHandler, a new feature introduced within 1.3. It's not critical but a bit of annoying.

---

My `composer.json`:

n/a (Actually, using [this repo's one](https://github.com/composer/composer/blob/b1156ed376adc39de57f4bb4ed2c345ae8cbeb7e/composer.json))

Output of `composer diagnose`:

```
$ composer diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: WARNING
Your git color.ui setting is set to always, this is known to create issues. Use "git config --global color.ui true" to set it correctly.
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
$ composer install
```

I get the following output:

```
...
"phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)"
...
```

And I expected this to happen:

Not appear.

**Comment by issei-m** [comment]
My `php -i` outputs:

```
$ php -v
PHP 7.0.12 (cli) (built: Nov  1 2016 10:21:11) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.12, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
```

For reference.

**Comment by stof** [comment]
@Seldaek when xdebug is disabled by the handler, we should still add xdebug to the platform repository. This could be achieved by passing the info in an env variable set by the XdebugHandler.

**Comment by johnstevenson** [comment]
@stof What info do you need to pass?

**Comment by Seldaek** [comment]
I think only the xdebug version is needed, then we can check for a given env var in PlatformRepository and add the ext-xdebug package.

**Comment by johnstevenson** [comment]
@Seldaek Is `COMPOSER_XDEBUG_VERSION` okay (to add to the growing list!)?

**Comment by Seldaek** [comment]
I guess it is :) And yes this is starting to get messy but hopefully 
it's all worth it.

**Comment by johnstevenson** [comment]
It is a hack, after all! Have we still got time to normalize the env variables to make it less messy?

`COMPOSER_XDEBUG_ALLOW`, `COMPOSER_XDEBUG_INIS`, `COMPOSER_XDEBUG_VERSION`

And is it worth it?

**Comment by stof** [comment]
``COMPOSER_XDEBUG_VERSION`` does not need to be documented though, as it would be set by the XDebugHandler to be read by PackageRepository in the retried process, making this env variable internal

**Comment by Seldaek** [comment]
I wouldn't rename the INI one as it isn't directly related to xdebug really, but to us restarting php.

Version one as stof says is internal so no matter.

The allow one is the only one widely exposed so rather not change it I guess, it's fine as is.

**Comment by johnstevenson** [comment]
Okay, thanks. I'll leave the others as is, and use `COMPOSER_XDEBUG_VERSION`
