### ISSUE TITLE
Note about custom commands needs to be improved

### ISSUE THREAD

**Issue by ravage84** [composer/composer#5970]
I opened a PR on https://github.com/cakephp/cakephp/pull/9862 and cited the [following note from the Composer Documentation](https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands):

> Note: Composer's bin-dir is pushed on top of the PATH so that binaries of dependencies are easily accessible as CLI commands when writing scripts.

As you can see, this [lead to some confusion](https://github.com/cakephp/cakephp/pull/9862#issuecomment-266414692).

I guess, this note should be reworded and should not mention the PATH (environment) variable or should explain what happens in more detail.

Since I could not find the actual resolution logic within Composer, I did not want to propose any wording.

**Comment by alcohol** [comment]
We take the PATH value, and push our own bin-dir on top of that value, before resolving the script binary to run. How could this be made more clear in your opinion?

See https://github.com/composer/composer/blob/98c5f825e0e9a60ae21c3c2bf8f005b93d01df50/src/Composer/EventDispatcher/EventDispatcher.php#L148-L161

**Comment by ravage84** [comment]
Bingo, call it what it is: It's an **Composer internal copy** of the system environment variable PATH, which gets used for resolution instead of the one from the system.

That way, people won't end up thinking the docs are talking about the system environment variable.

**Comment by alcohol** [comment]
But it is not an internal copy. It is literally the PATH for the scope of that script/command.

**Comment by alcohol** [comment]
But it is not an internal copy. It is literally the PATH for the scope of that script/command. It is the system environment variable.

**Comment by stof** [comment]
@ravage84 when a process launches a subprocess, it can pass it the environment it wants. It is not force to pass exactly the same environment variables than the one available in your shell (which is just another process launching subprocesses btw).

**Comment by ravage84** [comment]
All fine and nice, thanks for the clarification. But again, the problem at hand is that people out there do not understand what happens or better said misunderstand it.
Thus, this actually great feature is not understood and probably does not get used as much as it could.

This is not a support request as it is tagged, but it is an issue with the documentation.

Think of it like this:
How would one need to write that note about the PATH, so everybody understand it correctly?

**Comment by alcohol** [comment]
I would say the current documentation is quite accurate. I do not know what one might find confusing about it or what could be misunderstood here.

**Comment by ADmad** [comment]
> Note: the new value of PATH is only available within the run context of the composer process (which subsequently also exposes it to the script you run). It won't be permanently exported to your shell. For that you would have to add it to your bashrc/zshrc/etc.

The fact that you has to use the note in your comment makes it evident that the note in the docs can be misunderstood :smile: 

Perhaps the note could be updated as:  "Composer's bin-dir is pushed on top of the PATH **within the run context of the composer process** so that.."

**Comment by alcohol** [comment]
Sure, and then people will be like "what does ' the run context of the composer process' mean?" and the questions will just keep coming. The fact that this is the first time ever that this section was put into question signals to me that it either isn't very relevant, or it is clear enough for most. I don't see a need to change it.

But hey, if you can find a sensible alternative, go ahead and submit a PR.

**Comment by ADmad** [comment]
The best way to avoid questions would be to simply remove the note ;)

As for your suggestion regarding making a PR I'll let @ravage84 do whatever he thinks best.

**Comment by ravage84** [comment]
Never mind.

**Comment by Seldaek** [comment]
Hopefully fixed or at least improved in https://github.com/composer/composer/commit/da097aa6fcef2d937cf35d5764895fa195090bc5

**Comment by ADmad** [comment]
Thanks @Seldaek that's a lot more clearer.
