### ISSUE TITLE
Composer not generating autoload info for vcs library

### ISSUE THREAD

**Issue by StalkAlex** [composer/composer#5975]
So I've created library. Here's its composer.json
```json {
  "name": "StalkAllex/yii2-kaspersky-utilities",
  "license": "",
  "keywords": [],
  "type": "yii2-extension",
  "description": "Just wrapper for Kaspersky antivirus console commands",
  "authors": [
    {
      "name": "Alex Aboimov",
      "email": "akasstalkalex@gmail.com"
    }
  ],
  "autoload": {
    "psr-4": {
      "stalkalex\\utilities\\": "src"
    }
  },
  "require": {},
  "require-dev": {
    "phpunit/phpunit": "*",
    "squizlabs/php_codesniffer": "*",
    "codeclimate/php-test-reporter": "dev-master"
  }
}
```

After that I pushed it to GitHub and tried to add to my project like that
```json
  "repositories": [
    {
      "type":"package",
      "package": {
        "name": "stalkalex/yii2-kaspersky-utilities",
        "version":"master",
        "source": {
          "url": "https://github.com/StalkAlex/yii2-kaspersky-utilities.git",
          "type": "git",
          "reference":"master"
        }
      },
      "autoload": {
        "psr-4": {
          "stalkalex\\utilities\\": "src"
        }
      }
    }
  ]
```
And **it's not generating autoload** info for my library in my project, I've read all documentation, tried most of stackoverflow answeres related to the same problem. Just all for nothing Please help me!

 That's not working too
```json
"repositories": [
    {
      "type":"vcs",
      "url": "https://github.com/StalkAlex/yii2-kaspersky-utilities.git",
      "autoload": {
        "psr-4": {
          "stalkalex\\utilities\\": "src"
        }
      }
    }
  ]
```

**Comment by Seldaek** [comment]
In your second code block, the "autoload" config is outside of the package definition, put it inside and it will work :)

**Comment by StalkAlex** [comment]
No! Just copypasted your example, then used `composer dump-autoload` and nothing has been generated in autoload files.

**Comment by Seldaek** [comment]
No you need to first make sure the new package definition is actually installed, you can do that by `rm -rf vendor/stalkalex/ && composer update` then it will reinstall it and add the autoload config this time.
