### ISSUE TITLE
When hhvm and php requirements are set, treat it as a requirement for one or the other

### ISSUE THREAD

**Issue by michaelcullum** [composer/composer#5977]
When we have both requirements for `hhvm` and `php` versions set, we should treat this as we require either hhvm as that version or php as that version.

**Comment by Seldaek** [comment]
I don't agree, if you rely on either, then most likely you're not using hack, and you really only require php. It's up to hhvm to provide a good PHP_VERSION constant IMO to mark what they are compatible with.

**Comment by michaelcullum** [comment]
PHP versions aren't just used for features but a package might also rely on a specific bug in the engine to be fixed (which is why we sometimes see minimum php version != x.y.0), therefore one's minimum requirement for HHVM and PHP might be different. The question is are we depending on versions of the language specification (in which case we should only support requiring x.y versions and hhvm should be called hack in the composer file) or versions of the PHP/HHVM engines (which is the current behaviour realistically IMO).

**Comment by Seldaek** [comment]
I see what you mean but given the usage of HHVM these days I don't feel 
this level of hackery in Composer internals is warranted.

**Comment by robfrawley** [comment]
The issue is it *is* providing a useful value of `7.0.99-hhvm` and composer doesn't recognize that as meeting the requirement of `'php': `^7.0``.

**Comment by robfrawley** [comment]
As this issue was intended for a different that my comments, I've opened an issue detailing the problem I am running into instead of trying to carry on a conversation in a closed (and original-issue-not-applicable) ticket here. New ticket: composer/composer#5978
