### ISSUE TITLE
[Feature] Add SSL option to set verify_peer to false

### ISSUE THREAD

**Issue by onigoetz** [composer/composer#5981]
This is not related to a specific project but on to Composer in General.

In the company I work for, we have a Man in the middle proxy for all our internet access.
With the latest changes in Composer it's impossible for us to download anything with HTTPs, we get the following Error.

```
  - Installing psr/http-message (1.0.1) Downloading: Failed       
 Downloading: Failed       
 Downloading: Failed    Failed to download psr/http-message from dist: The "https://api.github.com/repos/php-fig/http-message/zipball/f6561bf28d520154e4b0ec72be95418abe6d9363" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
failed to open stream: Cannot connect to HTTPS server through proxy
    Now trying to download from source
```

I tracked down the problem to the fact that the http streams API doesn't allow self-signed certificates.

My certificates are installed correctly in `/etc/ssl/certs/ca-certificates.crt` and all other tools work fine (curl, wget ...) So the issue is not with my certificates.

Can we add a configuration `verify-peer: false` to composer's configuration ? 
Or change the behaviour of `disable-tls` to use `verify_peer: false` in the streams configuration instead of trying each url with HTTP (as the web is more and more encrypted, an option without HTTP may not be available.

I can create a pull request for any of both proposals. But I wanted to start a discussion first.

**Comment by staabm** [comment]
you should yourself do a favor and not use self-signed certs in your proxy.

in case you dont want to spent money at all you should at least get one from letsencrypt or similar.
your use case got stuck in the year 2000 ;-).

**Comment by onigoetz** [comment]
Well, the use case is a perfectly valid. Some companies like banks have to scan incoming and outgoing communications for security reasons.

Letsencrypt, doesn't issue certificates for proxy servers. No company does. For obvious security reasons.

Many issues already explain this problem on many different projects, not only Composer

This issue may look like a y2k issue, but it's not.

**Comment by staabm** [comment]
Did you check the curren composer schema[1].

It mentions several security/tls related config properties:

```

                "disable-tls": {
                    "type": "boolean",
                    "description": "Defaults to `false`. If set to true all HTTPS URLs will be tried with HTTP instead and no network level encryption is performed. Enabling this is a security risk and is NOT recommended. The better way is to enable the php_openssl extension in php.ini."
                },
                "secure-http": {
                    "type": "boolean",
                    "description": "Defaults to `true`. If set to true only HTTPS URLs are allowed to be downloaded via Composer. If you really absolutely need HTTP access to something then you can disable it, but using \"Let's Encrypt\" to get a free SSL certificate is generally a better alternative."
                },
                "cafile": {
                    "type": "string",
                    "description": "A way to set the path to the openssl CA file. In PHP 5.6+ you should rather set this via openssl.cafile in php.ini, although PHP 5.6+ should be able to detect your system CA file automatically."
                },
                "capath": {
                    "type": "string",
                    "description": "If cafile is not specified or if the certificate is not found there, the directory pointed to by capath is searched for a suitable certificate. capath must be a correctly hashed certificate directory."
                },
```

[1] https://getcomposer.org/schema.json

**Comment by onigoetz** [comment]
Yes, I know these properties.

- `disable-tls`: Pretty much useless as it only changes urls from `https://` to `http://`. Some URLs are https only, so that's not what I'm looking for.
- `secure-http`: Just ensures that resources are downloaded through secure protocols. I'm fine with this
- `cafile`/`capath`: I'm using PHP7. so I set this configuration in my `php.ini`. But it seems to not take them into consideration as the self-signed certificates I refered to are inside the `.crt` file 

I don't want to disable SSL, I want to disable the checks SSL makes, which is not the same and it isn't possible for the moment.

**Comment by alcohol** [comment]
There is no valid reason to make this possible. Complain to whoever runs your security department, because clearly they are just lazy.

**Comment by onigoetz** [comment]
@alcohol Okay, do you have a documentation or something I could point them to, so they can implement the thing properly ?

I don't see myself going to them and telling them "Someone on the internet says you're lazy, you have to change this"

I agree this MITM proxy is far less than ideal, but to my knowledge it's the only way to be able to scan the traffic with an HTTPs proxy (Which we need for legal reasons)

**Comment by alcohol** [comment]
Just have your ssl connections terminate at the proxy (making that your single point of entry). Then from there on, forward all requests as regular http to internal applications/servers. Use a valid ssl certificate on the proxy. Problem solved. Look into ssl-offloading, e.g. similar to this https://www.nginx.com/resources/wiki/start/topics/examples/SSL-Offloader/

**Comment by onigoetz** [comment]
Okay, It's as I thought.

We're not talking about the same thing. You are talking about a __reverse__ proxy. I'm talking about a real actual proxy.

In the case of a reverse proxy, like @staabm said, we can use a Letsencrypt certificate or any other certificate, which we already do.

In the case of a proxy, nobody will ever sell a certificate because that would mean that we could make a certificate for ANY website on the internet. So the solution is to create a master certificate, add it to your keystore. And in the proxy you do the SSL termination, then you re-issue the website with the new certificate to the end client.

This is why the certificate is self-signed.
Anyway, the base certificate is still checked as the proxy does the proper checking of the certificate. If the certificate is invalid, the proxy server blocks it.
So while the verification is disabled on the client side, the proxy server verified it already.

**Comment by onigoetz** [comment]
For more information on how it works, this question and answer are quite clear : http://security.stackexchange.com/questions/63304/how-can-my-employer-be-a-man-in-the-middle-when-i-connect-to-gmail

**Comment by alcohol** [comment]
I understand how that works. But I do not understand why you simply do not add this certificate to your chain then. If you are the client, you can simply include it (e.g. on your server). E.g. http://unix.stackexchange.com/questions/90450/adding-a-self-signed-certificate-to-the-trusted-list or https://confluence.atlassian.com/sourcetreekb/resolving-ssl-self-signed-certificate-errors-284368425.html

**Comment by onigoetz** [comment]
But that's the thing, they are in my certificates, but Composer refuses them because they are self-signed.
I will create a minimal test-case to reproduce this to show you.

**Comment by Seldaek** [comment]
Please stop arguing about the merits of corporate proxies.. This discussion is pointless.

Self-signed or not, if your certificate is in your ca-bundle it should work, and if not then I'd think there's a bug on our end or a misconfiguration on yours.

**Comment by onigoetz** [comment]
So, I was able to trace the exact source of the problem and it was on my side, sorry for the noise.

I'll document it here if someone has the same problem as I had : 

Using `openssl s_client` you can get the full certificate chain of the server:
```
openssl s_client -connect api.github.com:443 -proxy 127.0.0.1:3129
```

The certificate chain can look something like this.
```
---
Certificate chain
 0 s:/C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=*.github.com
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
 1 s:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA
---
```

In this case, I can see that the domain is actually signed by DigiCert, meaning it was __not__ signed with my company's custom certificate. And as macOS doesn't have a `/etc/ssl/certs/ca-certificates.crt` we created a custom one only with our internal certificates.

The fix : Add all base root certificates as well as the custom ones to `/etc/ssl/certs/ca-certificates.crt`

**Comment by Seldaek** [comment]
Great to hear :)

**Comment by meglio** [comment]
I added all certificates to `/etc/ssl/certs/ca-certificates.crt`. The issue persists.

While on Ubuntu, the following test runs fine:

```
openssl s_client -connect mydomain.com:443 -CApath /etc/ssl/certs
```

However, composer won't run.

**Comment by Seldaek** [comment]
@meglio check with `composer update -vvv` for a line starting with "Checked CA" which should let you know which CA file composer picked. If it's not the right one then maybe your php CA path (`openssl.cafile` in php.ini) or file is misconfigured? See also https://getcomposer.org/doc/06-config.md#cafile
