### ISSUE TITLE
ZIP uncompress errors when installing/updating dependencies

### ISSUE THREAD

**Issue by javiereguiluz** [composer/composer#5982]
My `composer.json`:

```json
    "require": {
        "php"                                      : ">=5.5.9",
        "algolia/algoliasearch-client-php"         : "^1.6",
        "beberlei/metrics"                         : "^2.0",

        "// ... and more packages here"
    }
```

Output of `composer diagnose`:

```
$ composer diagnose

Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
$ composer install
```

I get the following output:

```
- Installing beberlei/metrics (v2.3.0)
    Downloading: 100%
    Update failed ('<my-project>/vendor/beberlei/metrics/18ddcb3d31a1a6b6aaf65fef675bc3c9' is not a zip archive.
Failed to execute unzip '<my-project>/vendor/beberlei/metrics/18ddcb3d31a1a6b6aaf65fef675bc3c9' -d '<my-project>/vendor/composer/9c528af1' && chmod -R u+w '<my-project>/vendor/composer/9c528af1'

  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of <my-project>/vendor/beberlei/metrics/18ddcb3d31a1a6b6aaf65fef675bc3c9 or
        <my-project>/vendor/beberlei/metrics/18ddcb3d31a1a6b6aaf65fef675bc3c9.zip, and cannot find <my-project>/vendor/beberlei/metrics/18ddcb3d31a1a6b6aaf65fef675bc3c9.ZIP, period.)
    Would you like to try reinstalling the package instead [yes]?

  - Removing beberlei/metrics (v2.4.0)
  - Installing beberlei/metrics (v2.3.0)
    Downloading: 100%
    Invalid zip file, retrying...
  - Installing beberlei/metrics (v2.3.0)
    Downloading: 100%
    Invalid zip file, retrying...
  - Installing beberlei/metrics (v2.3.0)
    Downloading: 100%
    Failed to download beberlei/metrics from dist: '<my-project>/vendor/beberlei/metrics/18ddcb3d31a1a6b6aaf65fef675bc3c9' is not a zip archive.

    Now trying to download from source
    [...]

    (and the package is installed correctly)

```

At the end the packages are installed ... but after several retries and after downloading them from source, which is much slower. The error happens randomly for some packages, but not for all of them.

This never happened to me before. The only recent change that I made was installing PHP 7.1:

```
PHP 7.1.0 (cli) (built: Dec  2 2016 09:19:56) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.1.0, Copyright (c) 1999-2016, by Zend Technologies
    with blackfire v1.14.1~mac-x64-non_zts71, https://blackfire.io, by Blackfireio Inc.
```

**Comment by alcohol** [comment]
Do you run inside virtualbox?

**Comment by javiereguiluz** [comment]
@alcohol no. No virtualization or containerization.

**Comment by alcohol** [comment]
Proxy? Firewall? Virus scanner? What platform? More details?

**Comment by javiereguiluz** [comment]
No proxy or firewall or virus scanner. macOS. Composer worked great in the same computer for the last 4 years. I never had a single problem. The only recent change on this machine was the upgrade to PHP 7.1.0 (I use https://php-osx.liip.ch).

**Comment by Seldaek** [comment]
That's quite odd, looks like a network issue interrupting the download early or something along those lines? It's not a generic 7.1 issue though I've been running 7.1 for months without any issue. 

Can you disable blackfire see if you can still reproduce it? Just to exclude that.. Otherwise I am not sure what it can be tbh.

**Comment by javiereguiluz** [comment]
I've tried disabling Blackfire extension ... but the problem is that Composer is working again perfectly, so I cannot reproduce the error in any way.

In case it's useful, at least another developer reported the exact same error in Symfony's Slack and Twitter. See https://twitter.com/velmu/status/810505838611660800

But for now I'm closing this as "fixed". I'll reopen if I have more information. Thank you!

**Comment by staabm** [comment]
just guessing. maybe one of you guys is using cli-enabled opcache and the other doesn't?

**Comment by cerw** [comment]
Same issue.

**Comment by SteelHe** [comment]
hello. i met the same question. and it turned out to be the network issue.

**Comment by yoges89** [comment]
`composer clearcache` and `composer global update` solved my problem.

**Comment by mbrodala** [comment]
In my case the issue was caused by an (anonymous) Docker volume mount of `~/.composer/cache`. After removing the volume (thus keeping the in-container directory) the error ws gone.

**Comment by sirjeff** [comment]
> `composer clearcache` and `composer global update` solved my problem.

bash and cmd had the same issues. `composer clearcache` fixed it for me too.
(Windows 7 Pro. 64bit , PHP 7.2.10 , Composer 1.8.5)

**Comment by CowChris** [comment]
MacOS 10.14.5
Composer version 1.8.5 2019-04-09 17:46:47
PHP 7.2.19 (cli) (built: Jun 17 2019 09:03:55) ( NTS ) <-- installed via Brew

Same symptoms.

Not fixed by `composer clearcache` nor `composer global update` sadly. :(

Also tried updating to PHP 7.3 in case that helped, but no cigar.

Snippet of error:

```
[~/vendor/attractions-io/commerce-adapters/vendor/fzaninotto/faker/4c533b4eb75611405b4356205ac62790]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ~/vendor/attractions-io/commerce-adapters/vendor/fzaninotto/faker/4c533b4eb75611405b4356205ac62790 or
        ~/vendor/attractions-io/commerce-adapters/vendor/fzaninotto/faker/4c533b4eb75611405b4356205ac62790.zip, and cannot find ~/vendor/attractions-io/commerce-adapters/vendor/fzaninotto/faker/4c533b4eb75611405b4356205ac62790.ZIP, period.

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class
    REASON: Required by the root package: Install command rule (install fzaninotto/faker v1.8.0)
```

Any more ideas before I go ahead and re-install everything!

**Comment by sirjeff** [comment]
If it _is_ a composer cache issue and the 'clear-cache' isn't doing its thing, you could try deleting the files manually ...
https://stackoverflow.com/questions/22700728/composer-loading-from-cache

**Comment by smelike** [comment]
Same issue. Still broken

**Comment by pcktuts** [comment]
Same issue still not working with php 7.4

**Comment by dmpinder** [comment]
> I had the same issue.
> It seems that some downloaded zip files were broken.
> Run `composer clearcache` solved my problem.

This worked for me, thanks!

**Comment by leonelunderscore** [comment]
I got this issue too. I solved the problem by doing `composer clear-cache` and everything is ok now
