### ISSUE TITLE
Composer update fails when providing platform package

### ISSUE THREAD

**Issue by alcaeus** [composer/composer#5987]
This may be related to #5030.

Let's start out with the following `composer.json`:
```json
{
    "require": {
        "alcaeus/mongo-php-adapter": "1.0.6",
        "doctrine/mongodb": "^1.3"
    }
}
```

(Note: the exact version constraint for mongo-php-adapter is required for the next step to work)

Running `composer install` will fail due to the problem specified in #5030, thus we run `composer install --ignore-platform-reqs`:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing mongodb/mongodb (1.1.0)
    Loading from cache

  - Installing alcaeus/mongo-php-adapter (1.0.6)
    Loading from cache

  - Installing doctrine/lexer (v1.0.1)
    Loading from cache

  - Installing doctrine/inflector (v1.1.0)
    Loading from cache

  - Installing doctrine/collections (v1.3.0)
    Loading from cache

  - Installing doctrine/cache (v1.6.1)
    Loading from cache

  - Installing doctrine/annotations (v1.3.0)
    Loading from cache

  - Installing doctrine/common (v2.7.1)
    Loading from cache

  - Installing doctrine/mongodb (1.4.0)
    Loading from cache

doctrine/mongodb suggests installing jmikola/geojson (Support GeoJSON geometry objects in 2dsphere queries)
Writing lock file
Generating autoload files
```

Now we update the version constraint for mongo-php-adapter:
```json
{
    "require": {
        "alcaeus/mongo-php-adapter": "1.0.7",
        "doctrine/mongodb": "^1.3"
    }
}
```

Running `composer update` will yield an error:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - doctrine/mongodb 1.4.0 requires ext-mongo ^1.5 -> satisfiable by alcaeus/mongo-php-adapter[1.0.6].
    - doctrine/mongodb 1.3.0 requires ext-mongo ^1.5 -> satisfiable by alcaeus/mongo-php-adapter[1.0.6].
    - doctrine/mongodb 1.4.0 requires ext-mongo ^1.5 -> satisfiable by alcaeus/mongo-php-adapter[1.0.6].
    - Can only install one of: alcaeus/mongo-php-adapter[1.0.7, 1.0.6].
    - Installation request for alcaeus/mongo-php-adapter 1.0.7 -> satisfiable by alcaeus/mongo-php-adapter[1.0.7].
    - Installation request for doctrine/mongodb ^1.3 -> satisfiable by doctrine/mongodb[1.3.0, 1.4.0].

  To enable extensions, verify that they are enabled in those .ini files:
    - /usr/local/etc/php/7.1/php.ini
    - /usr/local/etc/php/7.1/conf.d/ext-imagick.ini
    - /usr/local/etc/php/7.1/conf.d/ext-intl.ini
    - /usr/local/etc/php/7.1/conf.d/ext-mongodb.ini
    - /usr/local/etc/php/7.1/conf.d/ext-v8js.ini
    - /usr/local/etc/php/7.1/conf.d/ext-xdebug.ini
    - /usr/local/etc/php/7.1/conf.d/memory.ini
    - /usr/local/etc/php/7.1/conf.d/timezone.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

Expected behavior: the update is made without problem since the original package dependency is still filled. The special use case is that mongo-php-adapter `provides` ext-mongo as a polyfill.

**Comment by alcohol** [comment]
This is known and not easily fixed, as you know from reading the issue you linked. Use a work-around for now.

**Comment by alcaeus** [comment]
I'm aware of the issue and the workarounds required. The problem is that the workaround (requiring with `--ignore-platform-reqs`, after which it works) no longer works. Unfortunately, this means that `composer update` is broken for everyone who has included the package. The only workaround now would be to run `composer update --ignore-platform-reqs`, which I don't think is a good idea. The only other option would be to run `composer update alcaeus/mongo-php-adapter --ignore-platform-reqs` followed by `composer update` to update the rest of the packages, would you agree?

One more thing, I've also tested this with earlier versions of composer (back to 1.1.3), which now all show the same error. Since it used to work until recently, that suggests that the issue is not with composer but rather with packagist.

**Comment by alcohol** [comment]
Did you actually read the whole thread? Another workaround is to add the provide on your root composer.json.

**Comment by Seldaek** [comment]
This should work in 2.0 so closing
