### ISSUE TITLE
ERROR:  Package is not installed: ext-xdebug-2.4.0.0  

### ISSUE THREAD

**Issue by javiern** [composer/composer#5995]
composer install throw exception

```
composer install
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 59 installs, 0 updates, 1 removal

                                                
  [InvalidArgumentException]                    
  Package is not installed: ext-xdebug-2.4.0.0  
                                                

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

```

php version

```
php --version
PHP 5.6.22 (cli) (built: Jun 18 2016 16:47:14) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

```

composer version

```
composer --version
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Composer version 1.3.0 2016-12-24 00:47:03

```

if i use the previous stable version 1.2.4 of composer the install command works just fine

**Comment by javiern** [comment]
to reproduce, you can just do this:

```
$ composer require phpunit/php-code-coverage
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Warning: Accessing phpackages.intraway.com over http which is an insecure protocol.
Using version ^4.0 for phpunit/php-code-coverage
./composer.json has been created
Loading composer repositories with package information
Warning: Accessing phpackages.intraway.com over http which is an insecure protocol.
Updating dependencies (including require-dev)
Package operations: 7 installs, 0 updates, 1 removal

Installation failed, deleting ./composer.json.

                                                
  [InvalidArgumentException]                    
  Package is not installed: ext-xdebug-2.4.0.0  
                                                

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

```

**Comment by ricardask** [comment]
Hello, 
I'm having same issue. Worked fine on 1.2.4. Most likely a new bug in 1.3

**Comment by xabbuh** [comment]
This is most likely related to the changes from #5580. Setting the `COMPOSER_ALLOW_XDEBUG` environment variable before running Composer, should prevent Composer from restarting itself with Xdebug disabled.

**Comment by johnstevenson** [comment]
@javiern @ricardask Are either of you guys setting the `COMPOSER_ALLOW_XDEBUG` environment variable beforehand? Because 1.3 restarts without xdebug if this is not present, yet the warning message shows that it is still running.

**Comment by ricardask** [comment]
@johnstevenson Hi, no I'm not setting the env. var.

**Comment by johnstevenson** [comment]
Thanks. And do you see the warning that indicates that xdebug is being used:

> You are running composer with xdebug enabled. This has a major impact on runtime performance.

**Comment by ricardask** [comment]
Yes it's present. (including Jenkins console log output for 1.3)
```
[exec] You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
[exec] Loading composer repositories with package information
[exec] Installing dependencies (including require-dev) from lock file
[exec] Package operations: 64 installs, 0 updates, 1 removal
[exec] 
[exec]                                                 
[exec]   [InvalidArgumentException]                    
[exec]   Package is not installed: ext-xdebug-2.5.0.0  
[exec]                                                 
[exec] 
[exec] install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
[exec] 

BUILD FAILED
```

**Comment by ricardask** [comment]
Adding stack trace:
```
  [InvalidArgumentException]
  Package is not installed: ext-xdebug-2.5.0.0


Exception trace:
 () at phar:///[PATH TO WORKSPACE]/workspace/composer.phar/src/Composer/Installer/LibraryInstaller.php:123
 Composer\Installer\LibraryInstaller->uninstall() at phar:///[PATH TO WORKSPACE]/workspace/composer.phar/src/Composer/Installer/InstallationManager.php:211
 Composer\Installer\InstallationManager->uninstall() at phar:///[PATH TO WORKSPACE]/workspace/composer.phar/src/Composer/Installer/InstallationManager.php:160
 Composer\Installer\InstallationManager->execute() at phar:///[PATH TO WORKSPACE]/workspace/composer.phar/src/Composer/Installer.php:584
 Composer\Installer->doInstall() at phar:///[PATH TO WORKSPACE]/workspace/composer.phar/src/Composer/Installer.php:223
 Composer\Installer->run() at phar:///[PATH TO WORKSPACE]/workspace/composer.phar/src/Composer/Command/InstallCommand.php:119
 Composer\Command\InstallCommand->execute() at phar:///[PATH TO WORKSPACE]/workspace/composer.phar/vendor/symfony/console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at phar:///[PATH TO WORKSPACE]/workspace/composer.phar/vendor/symfony/console/Application.php:849
 Symfony\Component\Console\Application->doRunCommand() at phar:///[PATH TO WORKSPACE]/workspace/composer.phar/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at phar:///[PATH TO WORKSPACE]/workspace/composer.phar/src/Composer/Console/Application.php:227
 Composer\Console\Application->doRun() at phar:///[PATH TO WORKSPACE]/workspace/composer.phar/vendor/symfony/console/Application.php:124
 Symfony\Component\Console\Application->run() at phar:///[PATH TO WORKSPACE]/workspace/composer.phar/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar:///[PATH TO WORKSPACE]/workspace/composer.phar/bin/composer:52
 require() at /[PATH TO WORKSPACE]/workspace/composer.phar:24
```

**Comment by johnstevenson** [comment]
@ricardask Thanks for that info. For some reason the xdebug handler failed to work and I cocked up by not checking for this (and clearing an internal environment variable). If you are able to test the fix I have [PR-ed](https://github.com/composer/composer/pull/5999), it would be much appreciated because I had to mock the failure on my setup. It would also be helpful to know your os and config so I can replicate and see why the handler failed.

@alcohol The presence of `COMPOSER_XDEBUG_VERSION` _and_ the xdebug extension loaded meant that xdebug was added twice as a platform package:  https://github.com/composer/composer/blob/master/src/Composer/Repository/PlatformRepository.php#L125 and this somehow caused the `LibraryInstaller->uninstall()` method to be run on xdebug. I have no idea if this is the expected behavior.

**Comment by alcohol** [comment]
That is quite unexpected I would say. @Seldaek any idea why it would call `uninstall` in that scenario?

**Comment by Seldaek** [comment]
Should be fixed in latest snapshot (`composer self-update --snapshot`) but it'd be good if you can answer @johnstevenson 's questions about your environment so we can make sure the xdebug disabling works everywhere.

**Comment by ricardask** [comment]
Hello @johnstevenson, @Seldaek . Sorry for a late reply. OS in question is  `RHEL 6.8`. I can confirm that latest snapshot works fine. Thank you all for a such a great tool and a quick bug fix.

**Comment by johnstevenson** [comment]
@ricardask Thanks. Could do with a bit more config details, if that is possible. Could you show me the output from `php --ini`?

I'll take a guess that you have an xdebug.ini in `/etc/php.d`

**Comment by javiern** [comment]
I can confirm that it is working fine in the snapshot version.

Thank you guys!

**Comment by johnstevenson** [comment]
@javiern Great. Could you show me the output from `php --ini` please. I want to find out why we failed to disable xdebug. Thanks.

**Comment by javiern** [comment]
Sure...

# php --ini
Configuration File (php.ini) Path: /opt/iway/php56/etc
Loaded Configuration File:         /opt/iway/php56/etc/php.ini
Scan for additional .ini files in: /opt/iway/php56/etc/conf.d
Additional .ini files parsed:      /opt/iway/php56/etc/conf.d/bcmath.ini,
/opt/iway/php56/etc/conf.d/bz2.ini,
/opt/iway/php56/etc/conf.d/calendar.ini,
/opt/iway/php56/etc/conf.d/curl.ini,
/opt/iway/php56/etc/conf.d/dba.ini,
/opt/iway/php56/etc/conf.d/exif.ini,
/opt/iway/php56/etc/conf.d/ftp.ini,
/opt/iway/php56/etc/conf.d/gd.ini,
/opt/iway/php56/etc/conf.d/gettext.ini,
/opt/iway/php56/etc/conf.d/gmp.ini,
/opt/iway/php56/etc/conf.d/iconv.ini,
/opt/iway/php56/etc/conf.d/intl.ini,
/opt/iway/php56/etc/conf.d/ldap.ini,
/opt/iway/php56/etc/conf.d/mbstring.ini,
/opt/iway/php56/etc/conf.d/mcrypt.ini,
/opt/iway/php56/etc/conf.d/memcached.ini,
/opt/iway/php56/etc/conf.d/mysql.ini,
/opt/iway/php56/etc/conf.d/mysqli.ini,
/opt/iway/php56/etc/conf.d/oci8.ini,
/opt/iway/php56/etc/conf.d/opcache.ini,
/opt/iway/php56/etc/conf.d/openssl.ini,
/opt/iway/php56/etc/conf.d/pcntl.ini,
/opt/iway/php56/etc/conf.d/pdo.ini,
/opt/iway/php56/etc/conf.d/readline.ini,
/opt/iway/php56/etc/conf.d/shmop.ini,
/opt/iway/php56/etc/conf.d/snmp.ini,
/opt/iway/php56/etc/conf.d/soap.ini,
/opt/iway/php56/etc/conf.d/sockets.ini,
/opt/iway/php56/etc/conf.d/sysvmsg.ini,
/opt/iway/php56/etc/conf.d/sysvsem.ini,
/opt/iway/php56/etc/conf.d/sysvshm.ini,
/opt/iway/php56/etc/conf.d/wddx.ini,
/opt/iway/php56/etc/conf.d/xdebug.ini,
/opt/iway/php56/etc/conf.d/xmlrpc.ini,
/opt/iway/php56/etc/conf.d/xsl.ini,
/opt/iway/php56/etc/conf.d/zip.ini,
/opt/iway/php56/etc/conf.d/zlib.ini

**Comment by johnstevenson** [comment]
@javiern Thanks, Currently the XdebugHandler will place the contents of all these files into a single ini, using the following rules:

- if a file path matches `...xdebug.ini` this file is not included. No other processing is done.
- if an `xdebug.ini` is not found, a regular expression is applied to the contents of each ini file to comment out any xdebug entry.

In your case, the first option is applied, which suggests that xdebug is enabled in one of the other ini files (and disabled in the xdebug.ini otherwise you would see an error: `Cannot load Xdebug - extension already loaded`).

Could you confirm if this is the case?

**Comment by johnstevenson** [comment]
That will teach me from trying to be a smart-arse! I'll ignore xdebug.ini from now on.

Thanks @javiern and @ricardask The conundrum is solved.

**Comment by x-yuri** [comment]
I'm experiencing the issue. Output from `php --ini`:

```
$ php --ini
Configuration File (php.ini) Path: /etc/php
Loaded Configuration File:         /etc/php/php.ini
Scan for additional .ini files in: /etc/php/conf.d
Additional .ini files parsed:      /etc/php/conf.d/xdebug.ini
```

```
$ composer --version
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Composer version 1.3.0 2016-12-24 00:47:03
```

OS is Arch Linux.

**Comment by chrisandchris** [comment]
In what release do you expect this issue to be released?

**Comment by Seldaek** [comment]
1.3.1 which I should release soon I guess as we've had a few important fixes already.

**Comment by bearow** [comment]
snapshot worked for me too

**Comment by Seldaek** [comment]
1.3.1 is out btw :)

**Comment by alcohol** [comment]
That is not a Composer error message. We cannot aid you with this.
