### ISSUE TITLE
Requesting available packages listing from source is not giving expected results

### ISSUE THREAD

**Issue by grey-dev-0** [composer/composer#6000]
I'm in a middle of a project that will enable developers to install, update and, remove composer packages from a web accessed panel instead of using the composer commands on terminal. This will help those who don't have shell access on their servers.

The problem is when I try `composer show -a` on terminal it shows all package names which is what I expect but, when I try to get it from my web panel source using the following:

```php
...
$this->initComposer();    // This creates a Composer\Console\Application instance with the proper settings.
$input = new ArrayInput(['command' => 'show', '-a']);
$this->composer->run($input, $this->consoleOutput);
...
```

I get the list of the **installed** packages only when I should get all of the available packages from packagist.org , and I successfully managed to run `composer require` and, `composer show -i` commands from my source with no problems so, it is not an internet connectivity problem.

Sorry for writing too much, but I'm trying to describe the issue as best as I can, moreover I updated composer from v1.2.4 to v1.3.0 both the dependency source in my project and, the composer.phar on my machine and the problem persists after the update.

**Comment by Seldaek** [comment]
I think you need `['command' => 'show', '-a' => true]`

**Comment by grey-dev-0** [comment]
Thanks @Seldaek , you are right, I wasn't aware that options which have no values should be set to `true`, I should set the `-i` to true in the `show -i` command as well.
