### ISSUE TITLE
Composer is losing memory_limit when starting process without xdebug

### ISSUE THREAD

**Issue by oleg-andreyev** [composer/composer#6004]
When I run this command:

```
php -dmemory_limit=3G composer.phar update symfony/symfony --prefer-stable --with-dependencies
// or
php -dmemory_limit=-1 composer.phar update symfony/symfony --prefer-stable --with-dependencies
```

I get the following output:

```
PHP Fatal error: Allowed memory size of XXXXXX bytes exhausted <...>
```

And I expected this to happen:
- composer update should pass

Reason:

Composer is starting new process without memory_limit and uses default one (1G):
```
'/usr/bin/php' '-c' '/tmp/kaoOdw' 'composer.phar' 'update' '--ansi' 'symfony/symfony' '--prefer-stable' '--with-dependencies' '-vvv'
```

**Comment by alcohol** [comment]
@johnstevenson I think this is an edge case we did not entirely take into account..

**Comment by johnstevenson** [comment]
@alcohol Not so much not taken into account, but more _didn't know what to do with_ I'm afraid!

We don't have direct access to user-supplied php params so it would be a case of second guessing what options might be used. There are various things you can do to compare a current ini setting to what is in an ini file but it is not going to be foolproof.

**Comment by johnstevenson** [comment]
@alcohol I need to change the tmp ini file creation, as per #5995, so I'll incorporate some ini-setting comparison logic as well.

**Comment by Seldaek** [comment]
I did a quick fix for the memory_limit for now. I don't know if we really need to support *all* ini settings or not.. I kinda doubt there are a lot in wide use, but memory_limit is kinda critical here.
