### ISSUE TITLE
Error instaling composer... yeah, another error

### ISSUE THREAD

**Issue by Matijt** [composer/composer#6006]
I`m kinda new here yet so first of all, hi to everyone.
Well, the main problem here is that I don`t know what the hell is happening, like most of the times where an error comes to demolish your coding day XD.

The main problem comes from the installer where I get the next message:

The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed

If I try to install it with cmd it happens the same if I keep the instructions of getcomposer.org/download

The only way I can more or less install composer is downloading manually the composer.phar file in the xampp/php folder and run: 
echo @php "%~dp0composer.phar" %*>composer.bat

however, this only let me use composer inside that folder, and I cannot use PHP functions outside xampp/php folder, so I cannot install any extra plugins for yii nor anything I want Dx...

Please help me to install composer correctly

@Seldaek  @naderman @padraic I saw you talking about something like this in another post XD

**Comment by alcohol** [comment]
SSL issues unfortunately are rarely a composer issue, and more often than not either an issue within your network (bad proxy/firewall), or on your host (bad openssl setup/installation combined with php).

**Comment by Matijt** [comment]
So, what do you recommend me to do?

**Comment by curry684** [comment]
In this case actually the certificate verification failed, so your host is missing a trusted certificates package. Ensure you install one, for example on Debian/Ubuntu the `ca-certificates` package.

**Comment by asminog** [comment]
try sudo

**Comment by WashichawbachaW** [comment]
@alcohol, how to fix firewall for that error? Should I disable it? Response will be greatly appreciated. :)

**Comment by Matijt** [comment]
I formated my computer and it worked. Without any kind of firewall so it
would be a good idea to disable it
