### ISSUE TITLE
Code explanation / better commenting

### ISSUE THREAD

**Issue by alexbowers** [composer/composer#6007]
In https://github.com/composer/composer/blob/master/src/Composer/XdebugHandler.php#L66

where does the $command variable come from?

**Comment by alexbowers** [comment]
Okay, I have found the answer; though to me it feels like it could be better written.

`prepareRestart` has a variable passed by reference, which is modified inside that method, and used on the `restart` method. This to me seems strange. Why not have the variable before both, or as the response from `prepareRestart`.

**Comment by alcohol** [comment]
Yeah I've received this question a few times already on IRC too, in regards to the xdebug handler. I was hoping I could find the time some day to rewrite some of it to no longer use pass-by-reference anymore. Unfortunately, I have not gotten around to that as of yet.

**Comment by alexbowers** [comment]
Made the changes @alcohol https://github.com/composer/composer/pull/6010

**Comment by johnstevenson** [comment]
That looks much cleaner now.
