### ISSUE TITLE
composer attempts to resolve "require-dev" dependencies with --no-dev

### ISSUE THREAD

**Issue by glensc** [composer/composer#6011]
My `composer.json`:

```json
{
        "require": {
        },
        "require-dev": {
                "facebook/php-sdk": "~3.2.3"
        }
}
```

```
$ composer clear-cache
$ rm -rf vendor composer.lock
$ composer update --no-dev
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package facebook/php-sdk ~3.2.3 exists as facebook/php-sdk[4.0.1, 4.0.10, 4.0.11, 4.0.12, 4.0.13, 4.0.14, 4.0.15, 4.0.16, 4.0.17, 4.0.18, 4.0.19, 4.0.2, 4.0.20, 4.0.21, 4.0.22, 4.0.23, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9, 5.0.0, 5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.1.4, 5.1.5, 5.1.x-dev, 5.2.0, 5.2.1, 5.2.x-dev, 5.3.0, 5.3.1, 5.3.x-dev, 5.4.0, 5.4.1, 5.4.2, 5.4.x-dev, dev-4.0-dev, dev-4.1-dev, dev-master, 6.x-dev, v4.0.0] but these are rejected by your constraint.

```
And I expected this to happen:

- composer update to succeed, "require-dev"  section must be ignored

**Comment by alcohol** [comment]
Old news, please use the search function.

**Comment by glensc** [comment]
i did not find anything, add reference to dupe

**Comment by Seldaek** [comment]
See #5650

**Comment by glensc** [comment]
thanks!

**Comment by glensc** [comment]
altho #5650 is a bit different: "You cannot have the same package in both sections." here is no such issue. composer is trying to resolve dependencies it should not, making the run longer (take more ram) and likely end up with unresolved dependencies, like #6011 fails because can't resolve version, #5650 fails because conflicting resolution happened.

aside, collecting explanation of reasoning behind that:

https://github.com/composer/composer/issues/5652#issuecomment-245541348
> We have to compute all dependencies including dev ones otherwise it leads to weird edge cases, we did it the way you want before and it created issues so now it's all done in one go always, and thus it becomes impossible to override a required dependency in require-dev. That will surely not please everyone, but that's the state of the matter and it is not going to change.


https://github.com/composer/composer/issues/5652#issuecomment-245622774
> I don't remember exactly but one big issue is that the lock file is not created equal depending on whether you include dev requirements or not. That IMO is a big no no, because you should be able to take your dev lock file and push it to prod and install without dev packages and be sure you get the right stuff installed. Right now it is way more consistent as it always resolves the same way.

i think some documentation should be updated somewhere to explain the dependency resolution process.

**Comment by dbezborodovrp** [comment]
Resolving requiredev dependencies with --no-dev can be a problem for some users.

For example, I have a project that needs to use tcz/phpunit-mockfunction in the development environment, which has a dependency on runkit. Runkit is something that one does not generally install on production servers for security reasons. It is only required for mocking in unit tests, so I don't want this dependency on runkit resolved on production servers.

**Comment by alcohol** [comment]
You don't have to resolve anything on production servers, because you would only run `install --no-dev` on production (or if you are smart, you would never run composer on production at all).

**Comment by dbezborodovrp** [comment]
> install from lock does not resolve dependencies
Right, that makes sense.

**Comment by Laurent3170** [comment]
@alcohol  why do you say
>  Or if you are smart, you would never run composer on production at all.

How do you update files otherwise ?
I am running in this problem, and running `composer update --no-dev` says it's looking for bundles (from dev part) so I've try to run `composer install --no-dev` but then it requires my `config_dev.yml (Symfony)` which is removed from my prod server, as it's dev.

**Comment by Laurent3170** [comment]
In my case (but don't know if it's what has to be done) my`composer.lock` is different on my dev computer and on my prod one as it is generated on each computer and not transferred from dev to prod one. That's what I setup when beginning to use composer.

**Comment by curry684** [comment]
Run `composer update` locally, test thoroughly, push to Git, enjoy your CI doing automated regression tests. **THEN** you deploy the result, including lock, to production and run `composer install`. Your production environment is now enjoying a quickly installed fully tested environment.

It cannot be understated: *running composer update in production means you are deploying untested code*. We should really put that snippet in `<h1>` in the docs somewhere.

**Comment by Laurent3170** [comment]
Thanks.
I did `composer update` on my dev computer, then pushed the `composer.lock` and run `composer install` on my prod server, it has installed all the dev part on my prod server and required my `config_dev.yml` which I put in place (don't know if it's really secure).

If I run `composer install --no-dev` it removes dev part BUT then it looks for them `An error occurred when executing the "'cache:clear --no-warmup'" command:`

**Comment by curry684** [comment]
If it's using the config_dev.yml you have misconfigured your webbrowser to use the debug packages. That's also likely causing it to load debug bundles which have not been installed.

A Symfony project should use `app.php` in production, not `app_dev.php`.

**Comment by alcohol** [comment]
I personally always delete `app.php` and `app_dev.php` and replace it with one streamlined `index.php` and use `.env` instead to determine the environment type. I do not understand why symfony is still advocating this double entrypoint setup when it causes so much confusion and ties environment setup to server configuration.

**Comment by Laurent3170** [comment]
Of course the web browser uses `app.php`. it's not related with that.
The comand `composer install` is requiring `config_dev.yml`, but you're right, maybe there's something wrong somewhere...
And the bundles are installed by composer as they figure in the `composer.lock` which is the one used on my dev computer, except if I use `install --no-dev` which seems to be the command to run, but then I have trouble with bundles being looked from dev part...

**Comment by alcohol** [comment]
> The comand composer install is requiring config_dev.yml

You realize that makes absolutely no sense at all right? `composer` has nothing to do with your symfony configuration setup.

**Comment by Laurent3170** [comment]
Yes you're right, in fact the command `composer install` also calls scripts, including "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache" which is the one requiring `config_dev.yml`, and I guess, that as I don't set `--no-dev` option it tries to clear cache including dev, which cannot be done as the file is not there...
But including `--no-dev` gives trouble with bundles being looked from dev part...

**Comment by alcohol** [comment]
You can run `composer` with the `--no-scripts` argument to not execute scripts. Though to my knowledge, the cache handler should work fine regardless of your environment though. It sounds to me like you somehow broke your deployment.

**Comment by curry684** [comment]
> Though to my knowledge, the cache handler should work fine regardless of your environment.

There are cache:clear events which may reference the container. If using a dev environment without the DebugBundle/WebProfilerBundle installed this will crash compilation.

This is way out of scope for composer by now btw.

**Comment by Laurent3170** [comment]
Thanks for your answers.
I'll investigate them. I'm just trying to "repair" something that was working before `composer update --no-dev`, that has been changed.
I can understand (and do understand) that a decision has been taken to change the behaviour, but this implies changes on what was done until that decision.
Nothing is broken in the deployment, maybe miss-configured as I cannot know each configuration for each product by the heart, moreover if they are changing.
But, thanks again for your time.

**Comment by Laurent3170** [comment]
So... the solution, as you said, not linked with composer is that we should `export SYMFONY_ENV=prod`before calling `composer install --no-dev` to ensure that environment is the prod one. Answer found from [Stackoverflow](http://stackoverflow.com/questions/28422933/deploy-symfony2-application-to-prod-environment-causes-post-install-cmd-exceptio/28428543#28428543) and [Symfony' documentation](http://symfony.com/doc/current/deployment.html#c-install-update-your-vendors).
Thanks for your help

**Comment by curry684** [comment]
This is actually the prime reason I never use install hooks. `bin/console --env=prod cache:clear` is more verbose and never breaks across environments.

**Comment by Laurent3170** [comment]
Install hooks are installed by default, so we need to remove them, or not (but they are simplier for newbies, as I was, and maybe still be). I was even clearing the cache twice, one with the command line and one by the hook ;-)
Having problems make us digging into code and then understand it to improve it :-)
