### ISSUE TITLE
Composer required Username and Password, which are this credetials?

### ISSUE THREAD

**Issue by bhattaxay** [composer/composer#6020]
My `composer.json`:

```
{
    "name": "yiisoft/addmoreyii",
    "description": "Yii 2 Advanced Project Template",
    "keywords": ["yii2", "framework", "advanced", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": ">=2.0.6",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "kartik-v/yii2-widgets": "*",
        "kartik-v/yii2-widget-datepicker":"@dev",
        "yiisoft/yii2-jui": "2.0.*@dev",
        "mdmsoft/yii2-admin": "~2.0",
        "2amigos/yii2-date-picker-widget": "~1.0",
        "wbraganca/yii2-dynamicform": "dev-master",
        "kartik-v/yii2-context-menu": "*"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*"
    },
    "config": {
        "process-timeout": 1800
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    },
    "scripts": {
        "post-install-cmd": "php init --env=Development --overwrite=n"
    }
}

```

When I run this command:

```
php composer.phar require kartik-v/yii2-grid "@dev"
```

I get the following output:

![composer-error](https://cloud.githubusercontent.com/assets/16645901/21585546/a324b2a2-d0e8-11e6-82bd-0499de38ea92.jpg)

And I expected this to happen:

> Which credential it requires here? I have given both github and packagist credentails one by one but it throws same error.

**Comment by Seldaek** [comment]
Can you run the command with -vvv to see exactly which file it is trying to download when you get that authentication required msg?

**Comment by bhattaxay** [comment]
> It show me like this:


![test](https://cloud.githubusercontent.com/assets/16645901/21588494/336676c4-d10d-11e6-8933-87f487ffa644.png)

**Comment by Seldaek** [comment]
What if you run `composer config --global repo.packagist composer https://packagist.org` and then try again? This should prevent it from using `http` protocol and force `https` which might fix it in case you have a bad proxy in the way.

**Comment by bhattaxay** [comment]
okk Thanks @Seldaek 
Thank you so much.
I have stuck here since long time.

**Comment by jilcimar** [comment]
> What if you run `composer config --global repo.packagist composer https://packagist.org` and then try again? This should prevent it from using `http` protocol and force `https` which might fix it in case you have a bad proxy in the way.

Thank you! I spent a lot of time trying to solve this problem.

**Comment by sdjdd** [comment]
It works. I used China mirror before, but now the download speed is...

**Comment by akazhuo** [comment]
> It works. I used China mirror before, but now the download speed is...

try this
composer config -g repo.packagist composer https://packagist.laravel-china.org

**Comment by sdjdd** [comment]
@akazhuo Much better, thanks!

**Comment by konohanaruto** [comment]
> What if you run `composer config --global repo.packagist composer https://packagist.org` and then try again? This should prevent it from using `http` protocol and force `https` which might fix it in case you have a bad proxy in the way.

works for me. Thanks.

**Comment by hellowahab** [comment]
> What if you run `

> composer config --global repo.packagist composer https://packagist.org

` and then try again? This should prevent it from using `http` protocol and force `https` which might fix it in case you have a bad proxy in the way.

Works perfectly fine after above configuration

**Comment by kobaita41** [comment]
Thank you!
