### ISSUE TITLE
Incomplete validation of repositories

### ISSUE THREAD

**Issue by glady** [composer/composer#6021]
My `composer.json`:

```json
{
  "name": "glady/xxx",
  "repositories": [
    {
      "type": "package",
      "package": {
        "name": "some/package",
        "version": "v1.2.3"
      }
    }
  ]
}
```

Output of `composer diagnose`:

```
[Composer\Json\JsonValidationException]
  "./composer.json" does not match the expected JSON schema:
   - repositories[0] : Must contain no more than 1 properties
   - repositories[0].package : Object value found, but a boolean is required
   - repositories[0].package : Does not have a value in the enumeration [false]
   - repositories[0].package : Object value found, but an array is required
   - repositories[0].package.description : The property description is required
   - repositories[0].package : Failed to match all schemas
   - repositories[0].package : Failed to match exactly one schema
   - repositories[0].url : The property url is required
   - repositories[0].type : Does not have a value in the enumeration ["composer"]
   - repositories[0].type : Does not have a value in the enumeration ["vcs","github","git","gitlab","git-bitbucket","hg","hg-bitbucket","fossil","perforce","svn"]
   - repositories[0].type : Does not have a value in the enumeration ["path"]
   - repositories[0].type : Does not have a value in the enumeration ["artifact"]
   - repositories[0].type : Does not have a value in the enumeration ["pear"]
   - repositories[0] : Failed to match exactly one schema
```

When I run this command:

```
composer --help
```

I get the following output:

```
[Composer\Json\JsonValidationException]
  "./composer.json" does not match the expected JSON schema:
   - repositories[0] : Must contain no more than 1 properties
   - repositories[0].package : Object value found, but a boolean is required
   - repositories[0].package : Does not have a value in the enumeration [false]
   - repositories[0].package : Object value found, but an array is required
   - repositories[0].package.description : The property description is required
   - repositories[0].package : Failed to match all schemas
   - repositories[0].package : Failed to match exactly one schema
   - repositories[0].url : The property url is required
   - repositories[0].type : Does not have a value in the enumeration ["composer"]
   - repositories[0].type : Does not have a value in the enumeration ["vcs","github","git","gitlab","git-bitbucket","hg","hg-bitbucket","fossil","perforce","svn"]
   - repositories[0].type : Does not have a value in the enumeration ["path"]
   - repositories[0].type : Does not have a value in the enumeration ["artifact"]
   - repositories[0].type : Does not have a value in the enumeration ["pear"]
   - repositories[0] : Failed to match exactly one schema
```

And I expected this to happen:

```
composer diagnose

Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
```

```
composer --help

Usage:
  help [options] [--] [<command_name>]

Arguments:
  command                        The command to execute
  command_name                   The command name [default: "help"]

Options:
      --xml                      To output help as XML
      --format=FORMAT            The output format (txt, xml, json, or md) [default: "txt"]
      --raw                      To output raw command help
  -h, --help                     Display this help message
  -q, --quiet                    Do not output any message
  -V, --version                  Display this application version
      --ansi                     Force ANSI output
      --no-ansi                  Disable ANSI output
  -n, --no-interaction           Do not ask any interactive question
      --profile                  Display timing and memory usage information
      --no-plugins               Whether to disable plugins.
  -d, --working-dir=WORKING-DIR  If specified, use the given directory as working directory.
  -v|vv|vvv, --verbose           Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  The help command displays help for a given command:

    php ..\composer\bin\composer help list

  You can also output the help in other formats by using the --format option:

    php ..\composer\bin\composer help --format=xml list

  To display the list of available commands, please use the list command.
```

Same behavior occurs on phar downloaded from getcomposer.org/composer.phar

**Comment by smxsm** [comment]
Wow, this just broke our CI pipelines and I was debugging for 1.5 hrs :( ! Is it fixed now in the download from getcomposer.org/composer.phar?

**Comment by staabm** [comment]
ping @stof

**Comment by Seldaek** [comment]
@smxsm use `composer self-update --stable` to make sure you get the last stable release. If you use snapshots in your CI pipeline you can only blame yourself when things break. Use snapshot releases on your dev machines (`self-update --snapshot`) if you want to get the latest builds from master branch and test things and make sure we don't break your CI when we tag a stable release :)

**Comment by smxsm** [comment]
Hi @Seldaek thanks for the hint, but I was using wget to just download the latest release from getcomposer.org, assuming that would give me the latest stable release... isn't that the case? If so, I'd commit a current stable release to our repo and use --stable as suggested.

**Comment by stof** [comment]
@smxsm https://getcomposer.org/composer.phar links to the snapshot build. See https://getcomposer.org/download/ for the list of links to releases.

**Comment by smxsm** [comment]
@stof Ah, thanks for the info, didn't realize that! So that's indeed dangerous for CI, I'll update our repo, thanks :)

**Comment by Seldaek** [comment]
You can download that snapshot and then do a self-update to --stable, or you can just keep a globally installed composer around and `self-update --stable` it before every build. That way you avoid downloading for nothing every time.

**Comment by alcohol** [comment]
Aside from the CI issues discussed, I still think there is an issue here to be addressed regarding the new composer.json schema validation, right?

**Comment by Seldaek** [comment]
Of course yes something is broken in the package repo validation. I merged @glady's fix which "fixes" the issue but it is still broken I think.. as doing this for example doesn't break anymore:

```
{
  "repositories": [
    {
      "type": "package",
      "package": {
        "name": "some/package",
        "version": "v1.2.3"
      },
      "autoload": {
      }
    }
  ]
}
```

I'll reopen this, I hope @stof or someone else has time to look into it.

**Comment by stof** [comment]
yeah, I think this is related to ``description`` being required in the global composer.json.
I will look into this as soon as possible.

**Comment by rajeevroy15** [comment]
Downloading snapshot by `wget http://getcomposer.org/composer.phar`and then do a `self-update` to `--stable` it throws same error. 
Possible to fix `https://getcomposer.org/composer.phar`? so it'd download latest stable version only.

**Comment by Seldaek** [comment]
@rajeevroy15 the way to download composer correctly is documented at https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md - if you just download the snapshot URL it's your issue to fix sorry.

**Comment by staabm** [comment]
@Seldaek maybe we could change the url to make it more obvious that a snapshop will be downloaded (or maybe make the user aware of that fact while installation is running)

**Comment by Seldaek** [comment]
@staabm changing the URL would cause potential BC issues, and there is no install process because people doing this are bypassing the installer and just downloading a phar.. So they're on their own.
