### ISSUE TITLE
run-script getting module warnings with xdebug present

### ISSUE THREAD

**Issue by merk** [composer/composer#6030]
I am currently on composer version b3bd409a30c67184321b9b70871b90b1989410a7.

I am running: `composer run-script makefile` in a makefile, which does not have alias expansion and is directly running /usr/local/bin/composer which includes xdebug instead of the aliased composer in my shell (which runs php with a different php.ini that does not include xdebug).

The output has recently started complaining about modules being already loaded:
```
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
Cannot load Zend OPcache - extension already loaded
PHP Warning:  Module 'crypto' already loaded in Unknown on line 0
PHP Warning:  Module 'gmp' already loaded in Unknown on line 0
PHP Warning:  Module 'imagick' already loaded in Unknown on line 0
PHP Warning:  Module 'intl' already loaded in Unknown on line 0
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
PHP Warning:  Module 'pdo_pgsql' already loaded in Unknown on line 0
PHP Warning:  Module 'ssh2' already loaded in Unknown on line 0

Warning: Module 'crypto' already loaded in Unknown on line 0

Warning: Module 'gmp' already loaded in Unknown on line 0

Warning: Module 'imagick' already loaded in Unknown on line 0

Warning: Module 'intl' already loaded in Unknown on line 0

Warning: Module 'mcrypt' already loaded in Unknown on line 0

Warning: Module 'pdo_pgsql' already loaded in Unknown on line 0

Warning: Module 'ssh2' already loaded in Unknown on line 0
```

Running composer in my shell without xdebug does not exhibit this error.

Default PHP configuration --ini:
```
Configuration File (php.ini) Path: /usr/local/etc/php/5.6
Loaded Configuration File:         /usr/local/etc/php/5.6/php.ini
Scan for additional .ini files in: /usr/local/etc/php/5.6/conf.d
Additional .ini files parsed:      /usr/local/etc/php/5.6/conf.d/ext-crypto.ini,
/usr/local/etc/php/5.6/conf.d/ext-gmp.ini,
/usr/local/etc/php/5.6/conf.d/ext-imagick.ini,
/usr/local/etc/php/5.6/conf.d/ext-intl.ini,
/usr/local/etc/php/5.6/conf.d/ext-mcrypt.ini,
/usr/local/etc/php/5.6/conf.d/ext-opcache.ini,
/usr/local/etc/php/5.6/conf.d/ext-pdo_pgsql.ini,
/usr/local/etc/php/5.6/conf.d/ext-ssh2.ini,
/usr/local/etc/php/5.6/conf.d/ext-xdebug.ini,
/usr/local/etc/php/5.6/conf.d/tim.ini
```

Composer specific --ini
```
Configuration File (php.ini) Path: /usr/local/etc/php/5.6
Loaded Configuration File:         /usr/local/etc/php/5.6/php-composer.ini
Scan for additional .ini files in: /usr/local/etc/php/5.6/conf.d
Additional .ini files parsed:      /usr/local/etc/php/5.6/conf.d/ext-crypto.ini,
/usr/local/etc/php/5.6/conf.d/ext-gmp.ini,
/usr/local/etc/php/5.6/conf.d/ext-imagick.ini,
/usr/local/etc/php/5.6/conf.d/ext-intl.ini,
/usr/local/etc/php/5.6/conf.d/ext-mcrypt.ini,
/usr/local/etc/php/5.6/conf.d/ext-opcache.ini,
/usr/local/etc/php/5.6/conf.d/ext-pdo_pgsql.ini,
/usr/local/etc/php/5.6/conf.d/ext-ssh2.ini,
/usr/local/etc/php/5.6/conf.d/ext-xdebug.ini,
/usr/local/etc/php/5.6/conf.d/tim.ini
```

Note: I load the xdebug extension in /usr/local/etc/php/5.6/php.ini as per previous composer documentation.

My ext-xdebug.ini
```
[xdebug]
xdebug.remote_enable = On
xdebug.remote_port = 9001
```

php.ini's extra line:

```
zend_extension="/usr/local/opt/php56-xdebug/xdebug.so"
```

**Comment by alcohol** [comment]
Composer explicitly tries to unload xdebug now at runtime and does this by generating a custom temporary php.ini and then forking to a new process, effectively "restarting" itself. If you need to run composer with xdebug for some weird reason, then I suggest you read the changelog to learn how to disable this behaviour.

**Comment by alcohol** [comment]
The sensio distribution issues unfortunately are something we cannot resolve for you. This is an issue on their end (and it is being worked on afaik).

**Comment by merk** [comment]
Its not quite so simple to disable xdebug in a makefile when aliases do not work and you cant rely on OS configuration of every developer. I like the auto-disable stuff, but there isnt an obvious point of failure beyond "i upgraded composer and now something is misbehaving."

These tickets are what you refer, I think:
sensiolabs/SensioDistributionBundle#299
sensiolabs/SensioDistributionBundle#304

**Comment by alcohol** [comment]
I'm confused. You don't have to disable xdebug in your makefile. Composer does this automatically. The warnings you see above are something we cannot prevent, but harmless.

**Comment by merk** [comment]
Yeah, the change is positive.

They are harmless, but error noise is a bad thing, ignoring it isn't an option - too much error output and it just keeps growing and getting ignored.

Nothing Composer can do from here it seems, except that the change in this project is exposing issues because it relaunches a customised PHP environment that causes issues in other projects. I'll wait for the above PRs to be merged before upgrading composer back to versions that do this.
