### ISSUE TITLE
Cannot enable openssl extension for Composer (after trying everything for hours!)

### ISSUE THREAD

**Issue by ashleyliu31** [composer/composer#6031]
When I try to use composer in command line, it keeps saying:

"[Composer\Exception\NoSslException] The openssl extension is required for SSL/TLS protection but is not available. If you can not enable the openssl extension, you can disable this error, at your own risk, by setting the 'disable-tls' option to true."
I did hours of research and tried basically everything I found, including:
- uncommenting extension=php_openssl.dllandextension_dir = "ext"inphp.ini` in all my wamp and stand-alone php folders. I even did that to the phpforApache files.
- making composer use both my stand-alone php AND wamp php (both ver 7.0)
- ticking ssl_module in wamp Apache modules and php_openssl in PHP extensions
- I checked. php_openssl.dll DOES exist in the /ext directory
- I checked and the extension in php.ini does lead to the right directory: extension_dir ="c:/wamp64/bin/php/php7.0.10/ext/"
- Copying libeay32.dll and ssleay32.dll from installdir/php/ to installdir/apache2/bin/
- reinstalling composer and wamp

What else can I possibly do?? I am pretty desperate now. I tried disabling tls but after that it banned me from connecting: " [Composer\Downloader\TransportException] Your configuration does not allow connections to http://packagist.org/packages.json. See https://getcomposer.org/do c/06-config.md#secure-http for details."

Help!

**Comment by alcohol** [comment]
Start with the basics.

Provide us the output of `php --ini`, `php -m` and `composer -m`.

**Comment by z1z2** [comment]
```
D:\>php --ini
Configuration File (php.ini) Path: C:\WINDOWS
Loaded Configuration File:         C:\Program Files\PHP\v7.0\php.ini
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)

D:\>php -m
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
filter
gd
gettext
hash
iconv
imap
json
libxml
mbstring
mcrypt
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
pdo_sqlsrv
Phar
Reflection
session
SimpleXML
soap
SPL
sqlsrv
standard
tidy
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
zip
zlib

[Zend Modules]


D:\>composer show -p
composer-plugin-api 1.1.0    The Composer Plugin API
ext-bcmath          7.0.9    The bcmath PHP extension
ext-calendar        7.0.9    The calendar PHP extension
ext-ctype           7.0.9    The ctype PHP extension
ext-date            7.0.9    The date PHP extension
ext-dom             20031129 The dom PHP extension
ext-filter          7.0.9    The filter PHP extension
ext-hash            1.0      The hash PHP extension
ext-iconv           7.0.9    The iconv PHP extension
ext-json            1.4.0    The json PHP extension
ext-libxml          7.0.9    The libxml PHP extension
ext-mcrypt          7.0.9    The mcrypt PHP extension
ext-mysqlnd         0        The mysqlnd PHP extension (actual version: mysqlnd 5.0.12-dev - 20150407 - $Id: 241ae00989d1995ffcbbf63d579943635faf9972 $)
ext-pcre            7.0.9    The pcre PHP extension
ext-PDO             7.0.9    The PDO PHP extension
ext-Phar            2.0.2    The Phar PHP extension
ext-Reflection      7.0.9    The Reflection PHP extension
ext-session         7.0.9    The session PHP extension
ext-SimpleXML       7.0.9    The SimpleXML PHP extension
ext-SPL             7.0.9    The SPL PHP extension
ext-tokenizer       7.0.9    The tokenizer PHP extension
ext-wddx            7.0.9    The wddx PHP extension
ext-xml             7.0.9    The xml PHP extension
ext-xmlreader       7.0.9    The xmlreader PHP extension
ext-xmlwriter       7.0.9    The xmlwriter PHP extension
ext-zip             1.13.3   The zip PHP extension
ext-zlib            7.0.9    The zlib PHP extension
lib-iconv           1.14     The iconv PHP library
lib-libxml          2.9.4    The libxml PHP library
lib-pcre            8.38     The pcre PHP library
php                 7.0.9    The PHP interpreter
php-64bit           7.0.9    The PHP interpreter, 64bit
php-ipv6            7.0.9    The PHP interpreter with IPv6 support
```

But if I ran "composer show -p" in my project folder, I got
```
[Composer\Exception\NoSslException]
```

And if I use PHP 5.6, everything is OK.

**Comment by alcohol** [comment]
You have no openssl, so yea it's not going to work.

**Comment by z1z2** [comment]
Thank you, @alcohol .
I made a stupid mistake. Since I used PHP 5.6 for a while, I wrote the composer.bat as
```
@php -c "C:\Program Files (x86)\PHP\v5.6\xdebug-disabled-php.ini" "%~dp0composer.phar" %*
```
Maybe the old version ini is not fully compatible with PHP 7.0, although openssl is enabled in it.

**Comment by alcohol** [comment]
Does it work now?

**Comment by z1z2** [comment]
Yes. Xdebug is automatically disabled by the new version of composer, so there's no need to provide another ini. Now the bat is 
```
@php "%~dp0composer.phar"
```
as recommended by the document.
Thank you.

**Comment by alcohol** [comment]
Great :-)

**Comment by amarirsafa** [comment]
i have the same problem heres my out put and im just a beginner i have no idea how this is working... i work on windows10 and i used to work with php5 now im using php7
C:\Users\Amarir>php --ini
Configuration File (php.ini) Path: C:\WINDOWS
Loaded Configuration File:         (none)
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)

C:\Users\Amarir>php -m
[PHP Modules]
bcmath
calendar
Core
ctype
date
dom
filter
hash
iconv
json
libxml
mysqlnd
pcre
PDO
Phar
readline
Reflection
session
SimpleXML
SPL
standard
tokenizer
wddx
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]


C:\Users\Amarir>composer show -p
composer-plugin-api 1.1.0    The Composer Plugin API
ext-bcmath          7.3.4    The bcmath PHP extension
ext-calendar        7.3.4    The calendar PHP extension
ext-ctype           7.3.4    The ctype PHP extension
ext-date            7.3.4    The date PHP extension
ext-dom             20031129 The dom PHP extension
ext-filter          7.3.4    The filter PHP extension
ext-hash            7.3.4    The hash PHP extension
ext-iconv           7.3.4    The iconv PHP extension
ext-json            1.7.0    The json PHP extension
ext-libxml          7.3.4    The libxml PHP extension
ext-mysqlnd         0        The mysqlnd PHP extension (actual version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7c...
ext-pcre            7.3.4    The pcre PHP extension
ext-PDO             7.3.4    The PDO PHP extension
ext-Phar            7.3.4    The Phar PHP extension
ext-readline        7.3.4    The readline PHP extension
ext-Reflection      7.3.4    The Reflection PHP extension
ext-session         7.3.4    The session PHP extension
ext-SimpleXML       7.3.4    The SimpleXML PHP extension
ext-SPL             7.3.4    The SPL PHP extension
ext-tokenizer       7.3.4    The tokenizer PHP extension
ext-wddx            7.3.4    The wddx PHP extension
ext-xml             7.3.4    The xml PHP extension
ext-xmlreader       7.3.4    The xmlreader PHP extension
ext-xmlwriter       7.3.4    The xmlwriter PHP extension
ext-zip             1.15.4   The zip PHP extension
ext-zlib            7.3.4    The zlib PHP extension
lib-iconv           1.15     The iconv PHP library
lib-libxml          2.9.9    The libxml PHP library
lib-pcre            10.32    The pcre PHP library
php                 7.3.4    The PHP interpreter
php-ipv6            7.3.4    The PHP interpreter, with IPv6 support
php-zts             7.3.4    The PHP interpreter, with Zend Thread Safety

**Comment by alcohol** [comment]
I am not sure how your problem is similar?

The original author did have `openssl` listed in his `php -m` output. You do not. So your php installation simply does not have it.

**Comment by amarirsafa** [comment]
ah alright thank you.

**Comment by khoja-kinan** [comment]
> I am not sure how your problem is similar?
> 
> The original author did have `openssl` listed in his `php -m` output. You do not. So your php installation simply does not have it.

how to add it ?
