### ISSUE TITLE
Question: is it possible to add extra options/flags (--foo) to commands?

### ISSUE THREAD

**Issue by kinglozzer** [composer/composer#6039]
Hi,

I’d like to build a plugin with opt-in behaviour from an option that may given to each (or every) command, for example:

```
$ composer update -o --foo=bar
``` 

Is it possible to achieve this? I can’t find any documentation for it, and I’ve glanced briefly at Composer’s source code and can’t spot anywhere that this would be exposed for plugin developers, so I have a feeling the answer is no. I just figured I’d ask the question just in case :)

Thanks!

**Comment by Seldaek** [comment]
I think you might be able to do it by parsing args after `--` yourself from `$_SERVER['argv']`, because if you pass like `composer update -o -- --foo=bar` composer will ignore what follows `--`. I don't think there's a better way..
