### ISSUE TITLE
Composer fails to install JMSSecurityExtraBundle because of a too long path length (ZipArchive Exception)

### ISSUE THREAD

**Issue by gnutix** [composer/composer#604]
When trying to install vendors with composer.phar in the following directory (path length is **77 chars**) : 

_D:\Dorian\Dropbox\XAMPP Lite Portable PHP 5.4\htdocs\github\Symfony2Testing\_

the installation of the package "jms/security-extra-bundle" (1.1.0) fails with the following exception :

_ZipArchive::extractTo(): Full extraction path exceed MAXPATHLEN (260)_

Changing the path (renamed XAMPP folder) to :

_D:\Dorian\Dropbox\XAMPP PHP 5.4\htdocs\github\Symfony2Testing\_

fixed the problem.
Here is the complete log : https://gist.github.com/aa7e6e4207a63bc19f94

**Comment by franz-josef-kaiser** [comment]
Same problem here

**Comment by grisha87** [comment]
Occurs also on Windows. I saw that the packages are downloaded to the target vendor directory (so for example zendframework/zendframework1/[hash].zip . Prefixed with the working directory path, this exceeds the limit.

**Comment by yellow1912** [comment]
I can confirm that I'm suffering from the same issue with phpdocumentor

**Comment by vixriihi** [comment]
Also having same issue with phpdocumentor

**Comment by RomanSyroeshko** [comment]
Same problem with phpdocumentor. Composer self-update didn't help.

**Comment by extdevelopment** [comment]
@RomanSyroeshko
In my case `--prefer-source` helped, (MAXPATHLEN (260) error)

`php composer.phar global require "phpdocumentor/phpdocumentor:2.*" --prefer-source`

**Comment by RomanSyroeshko** [comment]
The solution works for me too. Thanks, @extdevelopment!

**Comment by said-jomedia** [comment]
I had the same issue with installing `phpdocumentor` but `--prefer-source` worked also for me.

**Comment by kenylieou** [comment]
Same problem to me, is there any way to fix it without using --prefer-source

**Comment by glen-84** [comment]
This is no longer an issue with PHP 7.1. 🎉
