### ISSUE TITLE
openid connect support?

### ISSUE THREAD

**Issue by mente** [composer/composer#6042]
composer supports both github oauth and gitlab oauth. Is there any plan to support [OpenID Connect](http://openid.net/connect/)? If there's no plan - are there objections for contribution?

It's built on top of oauth so shouldn't be that hard (but I might be too lame). For example it would be great for organizations with [openresty](http://openresty.org/en/)

**Comment by Seldaek** [comment]
I am not entirely sure where this would sit in the stack (in RemoteFilesystem perhaps to authenticate http requests much like http-basic auth?) but given you are the first person to ask I doubt it will get done any time soon if you don't take care of it :)

**Comment by Seldaek** [comment]
Closing as I don't think we will ever do anything here.
