### ISSUE TITLE
PluginManager::addPlugin() should be public

### ISSUE THREAD

**Issue by felixfbecker** [composer/composer#6044]
I'm using Composer programmatically to install dependencies. I would like to add the [prestissimo plugin](https://github.com/hirak/prestissimo)  to make it faster. I thought it would be as easy as:

```php
$io = new IO;
$composerFactory = new Composer\Factory;
$composer = $composerFactory->createComposer($io, "$dir/composer.json", true, $dir);
// Add prestissimo plugin
$composer->getPluginManager()->addPlugin(new Prestissimo\Plugin);
$installer = Composer\Installer::create($io, $composer);
$installer->run();
```

but `addPlugin()` is private, and only called by `registerPackage` which takes a `PackageInterface`.

**Comment by alcohol** [comment]
Composer was not really designed to be used programmatically. While it is possible, you will run into barriers for certain use-cases.

"should be" is a matter of opinion :-)

**Comment by Jean85** [comment]
Maybe you can retrive the `PackageInterface` instantiation for the plugin?

**Comment by felixfbecker** [comment]
I don't know how I would get the `PackageInterface` of the plugin, I think that would be very complicated. I would have to work with `Repository` etc. At the end, all `registerPackage()` does is do some checks on the package and the call `addPlugin()`. I don't need all those checks, I have the `Plugin` instance at hand...

I know Composer isn't well suited or documented to be used programmatically, but it is implemented in PHP, and I definitely have the use case here. It would feel weird to use `exec()` from PHP to call Composer, and I would be limited to only the options the CLI provides.

The fix obviously is very simple. Is there anything that speaks against it? I would do a PR
