### ISSUE TITLE
composer doesn't install on ubuntu 14.04 hosted AWS EC2

### ISSUE THREAD

**Issue by steven-varga** [composer/composer#6049]
Output of `composer diagnose`:
All settings correct for using Composer
Downloading...
The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: Connection timed out

And I expected this to happen: type few lines, watch the screen blinking back calm grey color with occasional green checkmark. 
What I got: frustrating hours of reading, confusion.

**Comment by alcohol** [comment]
Ok.

**Comment by davidjeddy** [comment]
@steven-varga as a work around `wget https://getcomposer.org/composer.phar -O ./composer.phar` will pull the latest snapshot.

**Comment by steven-varga** [comment]
Thanks a lot! The problem was on my side: the TCP443 (SSL) outgoing traffic was blocked. Apologies for the noise; now Composer works as advertised, great stuff.
