### ISSUE TITLE
Local path package does not autoload classes

### ISSUE THREAD

**Issue by TomasVotruba** [composer/composer#6050]
I'm about to write post about local packages, but there is one thing that blocks me.

I use [path local package](https://getcomposer.org/doc/05-repositories.md#path).

I need to autoload-dev and require-dev dependencies so I could run tests on those local packages.
Without that, I have to put this into main `composer.json`, which kinda kills the decoupling to path package.

Is there a way to do that?

---

Output of `composer diagnose`:

```json
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

**Comment by TomasVotruba** [comment]
I've rechecked in simpler structure and it works fine.

Sorry for false report. Closing.

**Comment by alcohol** [comment]
No. Autoload-dev and require-dev are root only attributes, meaning that they only are read from your root composer.json, not your dependencies.

**Comment by TomasVotruba** [comment]
That's what I thought :(

How do you use your approach local packages tests then?

**Comment by TomasVotruba** [comment]
I moved the autoload to `autoload` in main package. Like this:

![image](https://cloud.githubusercontent.com/assets/924196/26179067/99add0f8-3b61-11e7-8f09-bd9957e775cf.png)


https://github.com/ApiGen/ApiGen/blob/f5aec83b98f5e1f19e21e83a388c54be7ae34fbc/composer.json#L38-L54
