### ISSUE TITLE
Unable to install composer

### ISSUE THREAD

**Issue by sushil8901** [composer/composer#6051]
Connection Error [ERR_CONNECTION]: Unable to connect to getcomposer.org

Request to https://getcomposer.org/installer failed with errors:
Failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by Seldaek** [comment]
This looks like a network error on your end..

**Comment by shubham994** [comment]
I am unable to open the website on any browser [https://getcomposer.org/installer](url)

**Comment by andreierdoss** [comment]
I have the same issue. The connection is timing out.

**Comment by Seldaek** [comment]
Auto-closing this as it's marked as support request and has not received any update in a long time.
