### ISSUE TITLE
Is it possible to fetch a PR directly from composer.json?

### ISSUE THREAD

**Issue by jozephbrasil** [composer/composer#6054]
Dear developers. Don't know if this is the right way to ask but I tried to find the answer on Google without success. As you know, some packages on github receive a lot of pull requests and my question is: how to include a pull request as required on composer.json?

For example:

```
  "repositories": [
    {
      "url": "https://github.com/mautic/api-library.git",
      "type": "git"
    }
  ],
  "require": {
    "php": ">=5.6.29",
    "mautic/api-library": "^2.4"
  },
```
but, how to specify the PR to be cloned? I always have to manually add:
fetch = +refs/pull/*/head:refs/remotes/origin/pr/*
to .git/config then run manually git fetch origin && git checkout pr/73

Is it possible to add this routine directly to composer.json file? I don't want to use a forked repository. I want to use the official repository but fetch a specific pull request.

**Comment by alcohol** [comment]
> I don't want to use a forked repository. I want to use the official repository but fetch a specific pull request.

The above is not possible.

**Comment by stof** [comment]
> I don't want to use a forked repository. I want to use the official repository but fetch a specific pull request.

If you fetch a specific PR, you would still end up using a forked repository (the one sending the PR). So why not doing it explicitly ?

**Comment by joachim-n** [comment]
https://github.com/cweagans/composer-patches might be of interest. It currently works with patches rather than PRs, but that's a starting point.

**Comment by Chi-teck** [comment]
GitHub provides some magic URLs to turn PR into patch.
See https://stackoverflow.com/a/6188624/272927
So that the above mentioned composer plugin can be used to apply PRs as well.

This does not work for Symfony Components though, because their repositories are read only, and PR's are submitted to special [main repository](https://github.com/symfony/symfony).
