### ISSUE TITLE
Private repo always cloned instead of dist (zip) automatic download in Bitbucket

### ISSUE THREAD

**Issue by teolaz** [composer/composer#6056]
Hi guys,
today i've lost 2 hours without any result. The problem is, i'm developing a Wordpress theme, it will be updatable and i need to download all my project dependencies as dist instead of cloning them.
I've some private repositories in bitbucket, and these are the only libraries still cloned instead of downloaded as package distribution and extracted. 

The strange thing is that what i read here https://getcomposer.org/doc/05-repositories.md#git-alternatives seems to not be respected, or i've some problem understanding this: 

> The VCS driver to be used is detected automatically based on the URL. However, should you need to specify one for whatever reason, you can use fossil, git, svn or hg as the repository type instead of vcs.
> 
> If you set the no-api key to true on a github repository it will clone the repository as it would with any other git repository instead of using the GitHub API. But unlike using the git driver directly, Composer will still attempt to use github's zip files.

As i understand, composer should use bitbucket's own wrapper and directly download a .zip.

I tried to force  

```json
"preferred-install": {
      "*": "dist"
}
```
without any result.

My `composer -V`:
`Composer version 1.3.1 2017-01-07 18:08:51`

My `composer.json`:

```json
{
    "config": {
        "preferred-install": {
            "*": "dist"
        }
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "git@bitbucket.org:websolution-treviso/websolution-wordpress-php-library.git"
        },
        {
            "type": "vcs",
            "url": "git@bitbucket.org:websolution-treviso/websolution-common-php-library.git"
        }
    ],
    "require" : {
        "gkralik/php-uglifyjs": "1.0.0",
        "leafo/lessphp": "v0.5.0",
        "tubalmartin/cssmin": "v2.4.8-p4",
        "electrolinux/phpquery": "0.9.6",
        "mobiledetect/mobiledetectlib": "^2.8",
        "websolution/common-php-library": "*",
        "websolution/wordpress-php-library": "*"
    },
    "autoload" : {
        "psr-4": {
            "WebSolution\\CompleteTheme\\" : "inc/classes/"
        }
    }
}
```

When I run this command:

```
composer install
```

I get the following output:

```
 Package operations: 9 installs, 0 updates, 0 removals
  - Installing gkralik/php-uglifyjs (1.0.0) Downloading: 100%
  - Installing leafo/lessphp (v0.5.0) Downloading: 100%
  - Installing tubalmartin/cssmin (v2.4.8-p4) Downloading: 100%
  - Installing electrolinux/phpquery (0.9.6) Downloading: 100%
  - Installing mobiledetect/mobiledetectlib (2.8.24) Downloading: 100%
  - Installing league/csv (8.1.2) Downloading: 100%
  - Installing hbattat/verifyemail (v1.0.7) Downloading: 100%
  - Installing websolution/common-php-library (0.0.7.4) Cloning 5fbe1d91ec
  - Installing websolution/wordpress-php-library (0.1.1.1) Cloning ed4aefc463

```

but then if i take a look on websolution dependencies, i still find the .git inside.
This deny bitbucket to version also the websolution dependencies, as they're already a git repository:

![image](https://cloud.githubusercontent.com/assets/19909323/21801819/94609eca-d723-11e6-8856-75b4325a655d.png)

and obviously when i share the theme archive (.zip) the websolution dependencies aren't found.

How can i solve this?

**Comment by stof** [comment]
If you use ``"type": "git"``, composer has no way to know about bitbucket archives, as you told composer that you don't want it to use dedicated drivers but to use the git driver explicitly. Use ``"type": "vcs"`` instead, to let composer detect the best VCS driver (which will be a bitbucket-specific driver in this case, knowing about the archive).

Also note that composer 1.3.0 has a bug related to bitbucket archives, so make sure you updated your composer to 1.3.1

**Comment by teolaz1990** [comment]
@stof composer is updated to 1.3.1, and i already tried with `"type": "vcs"` before writing to you...

**Comment by teolaz1990** [comment]
@stof could you try with a private bitbucket repo of you?

**Comment by alcohol** [comment]
How have you setup bitbucket authentication?

**Comment by teolaz1990** [comment]
@alcohol bitbucket was set up with ssh keypair method...

**Comment by alcohol** [comment]
SSH key does not provide API access. Without API access, you cannot download dist files.

**Comment by teolaz1990** [comment]
So, what i need to do?

**Comment by alcohol** [comment]
Configure bitbucket authentication.

**Comment by teolaz1990** [comment]
Could you please be more explicit?

**Comment by alcohol** [comment]
I think our manual is quite explicit. But in case you don't know how to find it, here you go:

https://getcomposer.org/doc/06-config.md#bitbucket-oauth

**Comment by teolaz1990** [comment]
Ehm... no way to read that "SSH key does not provide API access. Without API access, you cannot download dist files." on https://getcomposer.org/doc/05-repositories.md#git-alternatives ...
What you posted is only a small needle in a haystack :D better to write it in a "DRIVER" section on repositories specs, no? I think reading an explaination is simpler than reading the whole configuration variables wiki :D
Ok, i'm trying this, then i'll report the results and eventually close...

**Comment by alcohol** [comment]
> Ehm... no way to read that "SSH key does not provide API access. Without API access, you cannot download dist files."

This has nothing to do with Composer, and everything to do with Bitbucket. So why should we document that? It is in their documentation.

**Comment by teolaz1990** [comment]
> This has nothing to do with Composer
Wrong, as you left the driver documentation, and noone could know how it works, you at least write "please remind that..."
What you think?

**Comment by alcohol** [comment]
I do not understand what you are trying to say, sorry.

**Comment by teolaz1990** [comment]
Do i have to read the whole composer code to understand how you developed bitbucket drivers, how the application flux works and so on?
It's better to say in documentation, on section https://getcomposer.org/doc/05-repositories.md#git-alternatives that you developed this drivers to download source/dist directly from third parts and for any driver you should add what they need to work... no?

**Comment by alcohol** [comment]
Maybe. Most people do not really care what it downloads. And for public repositories dist is usually default in a lot of cases. You happen to want to use private repositories and you did not setup authentication properly. Yes, maybe this particular situation could use better documentation. Will you write it? :-)

**Comment by teolaz1990** [comment]
I could do it for Bitbucket, but i didn't tried and developed the other drivers, so you should take care of em...

**Comment by teolaz1990** [comment]
is this ok? if so, i'll pull request it...

Before 

> #### Subversion Options

Please note:
* **To let Composer choose which driver to use** the repository type needs to be defined as "vcs"
* **BitBucket driver** require the OAuth method to access to BitBucket REST APIs. If you
do not set up anything, by default Composer will clone the master branch source code (with .git directory, too).
If you want to know how to create a OAuth consumer using Bitbucket, please refer to [this link](https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html).
After created an OAuth consumer, you need to setup your composer.json config section with 
the requested credentials like this (more info [here](https://getcomposer.org/doc/06-config.md#bitbucket-oauth)):
```json
{
    "config": {
        "bitbucket.org": {
            "consumer-key": "myKey", 
            "consumer-secret": "mySecret"
        }
    }
}
```

**Comment by alcohol** [comment]
>  If you
do not set up anything, by default Composer will clone the master branch source code (with .git directory, too).

This is not really correct.

**Comment by teolaz1990** [comment]
Ok, as i didn't wrote composer, could you please correct what's wrong?

**Comment by teolaz1990** [comment]
After tried what you said, this is still not working...

Composer.json:

```json
{
    "config": {
        "bitbucket-oauth": {
            "bitbucket.org": {
                "consumer-key": "mykeyfrombitbucket",
                "consumer-secret": "mysecretfrombitbucket"
            }
        },
        "preferred-install": {
            "*": "dist"
        }
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "git@bitbucket.org:websolution-treviso/websolution-wordpress-php-library.git"
        },
        {
            "type": "vcs",
            "url": "git@bitbucket.org:websolution-treviso/websolution-common-php-library.git"
        }
    ],
    "require" : {
        "gkralik/php-uglifyjs": "1.0.0",
        "leafo/lessphp": "v0.5.0",
        "tubalmartin/cssmin": "v2.4.8-p4",
        "electrolinux/phpquery": "0.9.6",
        "mobiledetect/mobiledetectlib": "^2.8",
        "websolution/common-php-library": "*",
        "websolution/wordpress-php-library": "*"
    },
    "autoload" : {
        "psr-4": {
            "WebSolution\\CompleteTheme\\" : "inc/classes/"
        }
    }
}
```

My bitbucket setup:

![image](https://cloud.githubusercontent.com/assets/19909323/21807400/ca7d32b4-d73e-11e6-881c-bcdcbb11e622.png)

**Comment by teolaz1990** [comment]
I feel not alone so...
After reading this https://github.com/composer/composer/issues/5166#issuecomment-226110812 tried the suggested method without any result, changed also rows

```json
"repositories": [
        {
            "type": "vcs",
            "url": "git@bitbucket.org:websolution-treviso/websolution-wordpress-php-library.git"
        },
        {
            "type": "vcs",
            "url": "git@bitbucket.org:websolution-treviso/websolution-common-php-library.git"
        }
    ],
```

to

```json
"repositories": [
        {
            "type": "vcs",
            "url": "https://bitbucket.org/websolution-treviso/websolution-wordpress-php-library.git"
        },
        {
            "type": "vcs",
            "url": "https://bitbucket.org/websolution-treviso/websolution-common-php-library.git"
        }
    ],
```

and cleared cache but the result is still

```
  - Installing websolution/common-php-library (0.0.7.4) Cloning 5fbe1d91ec from cache
  - Installing websolution/wordpress-php-library (0.1.1.1) Cloning ed4aefc463 from cache
```

Is it possible this was a caching problem instead?

**Comment by teolaz1990** [comment]
@Seldaek any help?

**Comment by Seldaek** [comment]
I haven't done a lot of usage with Bitbucket and I haven't spent a lot of time with the bitbucket code, so no I can't really help right now. I'll look into this eventually but I don't have time today.

**Comment by teolaz1990** [comment]
I think i made it, clearing MANUALLY the .cache/composer folder (rm -rf) and launching a composer update then. 

Now `composer update -vvv` logs:

```
  - Installing websolution/common-php-library (0.0.7.4)Downloading https://bitbucket.org/websolution-treviso/websolution-common-php-library/get/5fbe1d91ec8e3c8f3377f00b7e869bd81569439e.zip
 Downloading: 100%Writing /var/www/.cache/composer/files/websolution/common-php-library/a3e2c19bcfcf3de8e9b233197851c77fe30a79ff.zip into cache from /var/www/sites/wpcompletetheme/wp-content/themes/websolution-complete-theme/vendor/websolution/common-php-library/72fd26d72b0d210901e9213aa1336323.zip
 Extracting archiveExecuting command (CWD): unzip -qq '/var/www/sites/wpcompletetheme/wp-content/themes/websolution-complete-theme/vendor/websolution/common-php-library/72fd26d72b0d210901e9213aa1336323.zip' -d '/var/www/sites/wpcompletetheme/wp-content/themes/websolution-complete-theme/vendor/composer/d4c2c9be' && chmod -R u+w '/var/www/sites/wpcompletetheme/wp-content/themes/websolution-complete-theme/vendor/composer/d4c2c9be'

    REASON: Required by the root package: Install command rule (install websolution/common-php-library 0.0.5|install websolution/common-php-library 0.0.4|install websolution/common-php-library 0.0.6.1|install websolution/common-php-library 0.0.1|install websolution/common-php-library 0.0.7.3|install websolution/common-php-library 0.0.3|install websolution/common-php-library 0.0.2|install websolution/common-php-library 0.0.6.2|install websolution/common-php-library 0.0.7.1|install websolution/common-php-library 0.0.7|install websolution/common-php-library 0.0.7.4|install websolution/common-php-library 0.0.6.3|install websolution/common-php-library 0.0.7.2|install websolution/common-php-library 0.0.5.1)

  - Installing websolution/wordpress-php-library (0.1.1.1)Downloading https://bitbucket.org/websolution-treviso/websolution-wordpress-php-library/get/ed4aefc46308891f1fcea9704eb60d22e904456b.zip
 Downloading: 100%Writing /var/www/.cache/composer/files/websolution/wordpress-php-library/a76570a503c3eb3305c80382caee7aba9fa2723b.zip into cache from /var/www/sites/wpcompletetheme/wp-content/themes/websolution-complete-theme/vendor/websolution/wordpress-php-library/7fe8b0aee602ead25aff30d91e4ff2dd.zip
 Extracting archiveExecuting command (CWD): unzip -qq '/var/www/sites/wpcompletetheme/wp-content/themes/websolution-complete-theme/vendor/websolution/wordpress-php-library/7fe8b0aee602ead25aff30d91e4ff2dd.zip' -d '/var/www/sites/wpcompletetheme/wp-content/themes/websolution-complete-theme/vendor/composer/530be424' && chmod -R u+w '/var/www/sites/wpcompletetheme/wp-content/themes/websolution-complete-theme/vendor/composer/530be424'

    REASON: Required by the root package: Install command rule (install websolution/wordpress-php-library 0.0.5|install websolution/wordpress-php-library 0.0.4|install websolution/wordpress-php-library 0.0.7|install websolution/wordpress-php-library 0.0.6|install websolution/wordpress-php-library 0.0.1|install websolution/wordpress-php-library 0.0.3|install websolution/wordpress-php-library 0.0.2|install websolution/wordpress-php-library 0.1|install websolution/wordpress-php-library 0.0.8|install websolution/wordpress-php-library 0.0.8.1|install websolution/wordpress-php-library 0.0.8.2|install websolution/wordpress-php-library 0.1.1.1|install websolution/wordpress-php-library 0.1.1)
```

**Comment by alcohol** [comment]
Manually clearing cache should not make a difference. In the previous log you can see that it _first_ cloned into the cache directory, and then from that clone in your cache directory, it cloned into your vendor directory.

If I am not mistaken, for the Bitbucket API to work, you have to fill in a callback url (even if it does nothing, e.g. google.com).

**Comment by teolaz1990** [comment]
I think i totally missed the `composer update` so...

**Comment by alcohol** [comment]
Oh, if you were using install then it would stick to what was in your `.lock` file yes. Update ignores the `.lock` file.

**Comment by Seldaek** [comment]
I think this can be closed now, let me know if I am mistaken.

**Comment by teolaz1990** [comment]
@Seldaek, @alcohol  i was waiting my pull request to be merged (or your fix) to enhance the documentation and add this particular before closing....

**Comment by Seldaek** [comment]
Ah.. If you're talking about https://github.com/teolaz1990/composer/pull/1 then you should rather open the pull request on this repository, because if it's on yours we don't notice it :)

**Comment by teolaz1990** [comment]
Ops, actually i posted the pr here https://github.com/composer/composer/issues/6056#issuecomment-271558088, i just forgot to see which pr i'm sending :S

**Comment by teolaz1990** [comment]
PR here : https://github.com/composer/composer/pull/6095

**Comment by purdel** [comment]
Still not working. I'm trying to get the zip file instead of the git clone for more than 2 hours now. Cleared the cache, created the key and secret, changed the urls ftom git@... to https, did everything to no avail.

Here's my composer.json:

```
{
  "config": {
    "bitbucket-oauth": {
      "bitbucket.org": {
        "consumer-key": "key",
        "consumer-secret": "secret"
      }
    },
    "preferred-install": {
      "*": "dist"
    }
  },
  "repositories": [
    {
      "type": "vcs",
      "url": "https://foo@bitbucket.org/foo/clustertools.git"
    }
  ],
  "require": {
    "piwik/ini": "^1.0",
    "vlucas/phpdotenv": "^2.4",
    "goodby/csv": "^1.3",
    "foo/cluster": "^1.0"
  }
}
```

**Comment by dynasource** [comment]
would be nice to have Composer matching the real commit key, instead of caching based on the url. 

Currently, when using Bitbuckets download function for the latest commit (https://bitbucket.org/user/repo/get/branche.zip), this will be cached and any future updates will not be respected, unless you clean the cache.

**Comment by Seldaek** [comment]
@dynasource that seems like a bug in bitbucketdriver that it creates urls for zips with branch names while it should include the commit hash in there, please report a new issue as this one is resolved actually.

**Comment by dynasource** [comment]
ahh, thanks for the pointer. I tried to get this working through old `package` configuration, but today the `vcs` is correctly supplying dist zips from BitBucket,  so BitBucket is working fine. Thx!

**Comment by trainoasis** [comment]
> would be nice to have Composer matching the real commit key, instead of caching based on the url.
> 
> Currently, when using Bitbuckets download function for the latest commit (https://bitbucket.org/user/repo/get/branche.zip), this will be cached and any future updates will not be respected, unless you clean the cache.

Did you manage to solve this somehow? For me it won't take the newly updated version (not a zip though) on bitbucket. Even have a tag with semantic versioning which is supposed to work, v3.8.3 etc.
