### ISSUE TITLE
[Gitlab driver] 404 on urlencode the repository name

### ISSUE THREAD

**Issue by fezfez** [composer/composer#6064]
My `composer.json`:

```json
{
    "description" : "File Parser",
    "type" : "library",
    "require" : {
       "psr/log" : "~1.0",
       "ulysse/file-iterator" : "~0.1",
       "symfony/validator": "^2.8",
       "symfony/config": "^2.8"
    },
    "require-dev" : {
        "phpunit/phpunit" : "~4.8"
    },
    "repositories": [
        { "type": "gitlab", "url": "https://gitlab.*******.fr/ulysse/file-iterator" }
    ],
    "prefer-stable" : true,
    "config": {
        "platform" : {
            "php": "5.4"
        },
        "gitlab-domains": ["https://gitlab.******.fr"]
    }
}

```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking HTTP proxy: OK
Checking HTTP proxy support for request_fulluri: OK
Checking HTTPS proxy support for request_fulluri: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: *****
Dev Public Key Fingerprint: ******
OK
Checking composer version: OK
```

When I run this command:

```
composer update
```

I get the following output:

```
composer update
Loading composer repositories with package information
Failed to download ulysse/file-iterator:The "https://gitlab.******.fr/api/v3/projects/ulysse%2Ffile%2Diterator" file could not be downloaded (HTTP/1.1 404 Not Found)
Your credentials are required to fetch private repository metadata (https://gitlab.*****.fr/ulysse/file-iterator)
A token will be created and stored in "C:/******/AppData/Roaming/Composer/auth.json", your password will never be stored
To revoke access to this token you can visit gitlab.******.fr/profile/applications
Username: ******
Password:
Token successfully created


  [Composer\Downloader\TransportException]
  The "https://gitlab.******.fr/api/v3/projects/ulysse%2Ffile%2Diterator" file could not be downloaded (HTTP/1.1 404 Not Found)


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
```

And I expected this to happen:
I simply expected to work :)

I believe that the encoding of the url in the repository name, especially for the "-" char is wrong. (https://github.com/composer/composer/blob/master/src/Composer/Repository/Vcs/GitLabDriver.php#L223)

A simple test on public gitlab repo.

https://gitlab.com/gitlab-org/gitlab-ee [200 OK]
https://gitlab.com/gitlab-org/gitlab%2Dee [302 Found]

On my private repo

https://gitlab.****.fr/ulysse/file-iterator [200 OK]
https://gitlab.*****.fr/ulysse/file%2Diterator[404 Not Found]

gitlab version 8.15.2
Composer version 1.3.1 2017-01-07 18:08:51

**Comment by alcohol** [comment]
This looks like a bug, but will need further investigation.

**Comment by alcohol** [comment]
I think the original encoding solution was because package names with `/` in them resulted in errors (since it is also a valid path separator in urls). Skipping the encoding for `-` should probably not be an issue since it holds no special meaning in urls.

**Comment by fezfez** [comment]
thanks @Seldaek

**Comment by amustill** [comment]
I'm currently experiencing the same issue with `version 1.3.2 2017-01-27 18:23:41`.

My `composer.json` with sensitive items redacted.

```javascript
{
    "name": "adam/private-gitlab-test",
    "require": {
        "group/project-name": "dev-master"
    },
    "repositories": [
        {
            "type": "gitlab",
            "url":  "https://git.domain.com/group/project-name"
        }
    ],
    "config": {
        "gitlab-domains": ["https://git.domain.com"]
    }
}
```

```bash
composer update
Failed to download group/project-name:The "https://git.domain.com/api/v3/projects/group%2Fproject-name" file could not be downloaded (HTTP/1.1 404 Not Found)
```

Hitting the URL `https://git.domain.com/api/v3/projects/group%2Fproject-name` directly in Chrome works.

**Comment by fezfez** [comment]
For me, it solve the issue.
Be careful on project visibility, for my case the value is "Public"

**Comment by amustill** [comment]
@fezfez I guess project visibility is the issue here although Composer is generating a valid API token for my user okay. It's a strange user experience.

**Comment by stoiev** [comment]
I've got same issue on 1.4.2 using a composer.json similar to yours.
The problem was resolved removing **https://** from **gitlab-domains** in config hash

    "config": {
        "platform" : {
            "php": "5.4"
        },
        "gitlab-domains": ["gitlab.******.fr"]
    }
