### ISSUE TITLE
Composer not checking if GitHub is available before deleting a dependency

### ISSUE THREAD

**Issue by eko3alpha** [composer/composer#6066]
GitHub was down while I was doing an update.  I noticed the following.

When I ran this command:

```
composer update
```

I got the following output:

```
Analyzed 839 rules to resolve dependencies
  - Removing symfony/var-dumper (v3.2.1)
  - Installing symfony/var-dumper (v3.2.2)
    Downloading: Connecting...    Downloading: 0%               Downloading: Failed
    Download failed, retrying...
    Downloading: Connecting...    Downloading: Failed       
    Download failed, retrying...
    Downloading: Connecting...    Downloading: Failed       

                                                                                                                                                                          
  [Composer\Downloader\TransportException]                                                                                                                                
  The "https://api.github.com/repos/symfony/var-dumper/zipball/b54b23f9a19b465e76fdaac0f6732410467c83b2" file could not be downloaded (HTTP/1.0 503 Service Unavailable)
```
I was surprised that Composer did not first check to see if the service was available before deleting the dependency from my project.  The result was a broken application.  I was able to restore using the cache.

```
composer install
```

And it was like nothing ever happened.

```
Installing dependencies (including require-dev) from lock file
  - Installing symfony/var-dumper (v3.2.1)
    Loading from cache
```

Would be nice to see composer first check to make sure all dependencies are available for download before deleting anything.

**Comment by stof** [comment]
there is no way to make the composer installation atomic when doing it in place anyway (many other things can go wrong than github being fully down).
So I don't think it is worth the complexity here

**Comment by Seldaek** [comment]
Yup I also don't think this can happen without a big rethink of composer internals, so will close this for now.
