### ISSUE TITLE
[Possible?] Explicitly shows CHANGELOG information (similar to suggestion) about the package after installation

### ISSUE THREAD

**Issue by gabbydgab** [composer/composer#6069]
**Rationale:**
Simple clean-up on the vendor folder.

I would like to ignore CHANGELOG.md file during export since most consumers ignores what's under  `vendor`.

It's also useful for `--dry-run` command to show what are the current development on a particular package.

### Option 1:
Similar to [suggestions](https://getcomposer.org/doc/04-schema.md#suggest), include the following in my `composer.json`:

```json
"changes": {
    "added": ["new features here"],
    "deprecated": ["notices here"],
    "removed": ["removed here"],
    "fixes": ["bc fixes or not here"]
}
```
**Caveat:** Tedious process for package maintainers.

### Option 2:
Or auto pull the latest CHANGELOG information from CHANGELOG.md file (with reversed chronological order by release).

**Caveat:** Can be compatible with most packages having CHANGELOG.md file but needs additional steps during parsing of the dependency.

Maybe additional feature will be halting the update if critical issues will be listed like backwards incompatible changes.

### Things to consider:
 - [ ] PSR for [CHANGELOG.md](https://github.com/thephpleague/skeleton/blob/master/CHANGELOG.md) (cc @php-fig, @michaelcullum)
 - [ ] Composer standards (about either options 1 or 2 or both)

I see some advantages here since it is explicit. I would love to hear your thoughts about this matter. Thanks in advance.

**Comment by michaelcullum** [comment]
If you're interested in starting a discussion about a PSR for changelog you're welcome to drop me a ping on twitter and we can have a chat. :)

**Comment by alcohol** [comment]
Such functionality could probably be implemented through the use of a plugin. I do not see any need for putting this in Composer core.

**Comment by Seldaek** [comment]
I don't really see this as being a Composer responsibility. As mentioned in https://github.com/composer/composer/issues/6079 it's something we want to improve for https://packagist.com though so we will see where we get with that and what can be integrated in https://packagist.org too.
