### ISSUE TITLE
[feature request] improve outdated no ansi output

### ISSUE THREAD

**Issue by greg0ire** [composer/composer#6070]
I'm working on [the issue template of several projects](https://github.com/sonata-project/dev-kit/pull/224). We used to ask for installed packages here, but I think it would be even better if we could quickly see which one are outdated.

Of course, people cannot preserve color when pasting `composer outdated --all` in the issue template, so I think it would be great if `outdated` detected the `--no-ansi` option and prefixed each like with something like ✔when up to date, ✘ otherwise. Or maybe even 3 symbols if we can find a meaningful way to express a warning (as opposed to an error)

I can work on a PR if you think this is a good idea.

**Comment by greg0ire** [comment]
Thanks a lot for implementing this @Seldaek !

**Comment by Seldaek** [comment]
np, I hope the signs are clear enough :)
