### ISSUE TITLE
[FEATURE REQUEST] Gets folders by namespace

### ISSUE THREAD

**Issue by jean-pasqualini** [composer/composer#6071]
I want this feature
Get the list of folders in which the autolaod look up from a namespace

Exemple
`$folders = $autoload->findFoldersByNamespace('Symfony\\Component\\HttpFoundation');`

Return 
`array('..../project/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation')`

**Comment by alcohol** [comment]
I don't really see a use-case for this, nor do I think the autoloader should be bloated by features considering it is a core component to many applications. But, who knows.. ¯\(°_o)/¯

**Comment by Seldaek** [comment]
Yup I don't see the point to have this in composer itself really, that's something you can do yourself if you like by using the getters on the classloader.
