### ISSUE TITLE
Help using Laravel

### ISSUE THREAD

**Issue by Crosa27** [composer/composer#6073]
I need help I'm using  Vagrant + composer and when I try  =composer create-project --prefer-dist laravel/laravel laravel  show me  this error: [Composer\Downloader\TransportException]
  Content-Length mismatch.,

**Comment by curry684** [comment]
This is not the helpdesk for Laravel issues. Please ask questions regarding specific products amd their usage on the relevant forums, not the issue tracker for one of the external tools.

**Comment by alcohol** [comment]
His error seems composer related though. But a lot of information is missing, nor did he actually include a detailed output log. So there is nothing we can do for him really.

**Comment by curry684** [comment]
Content-length mismatch is more likely related to an external repository misbehaving or local network problems.

**Comment by alcohol** [comment]
No, content-length mismatch usually happens when the client has a bad connection with packagist. As in, either a bad proxy or firewall, or possibly virus scanner.
