### ISSUE TITLE
auto detect license from LICENSE file

### ISSUE THREAD

**Issue by staabm** [composer/composer#6074]
github added support for detecting the license of a project based on a LICENSE file within the source repos and also added support for a api to detect those licenses [1].

there are a lot of php projects which forget to mention their license in the composer.json but have a LICENSE file.
As it is good practice to mention the license of a project inside of the composer.json and this information is also valueable, it would be great if composer (or packagist?) would also do a auto-detect of the used licsense, like github does.

this could help to make sure users of libraries have more legal information about the code they are using.
what do you think... is this feasible at all?

[1] https://github.com/blog/1964-open-source-license-usage-on-github-com

**Comment by staabm** [comment]
having more license information available would also make the job of validation licenses easier in tools which provide this kind of functionality.

**Comment by stof** [comment]
What we could do is adding this in the GithubDriver, using the github API.

Note however, that Github detects the license in the default branch. We cannot ask for a different license for each branch. So ``composer validate`` must still complain when the license is missing (otherwise, the wrong license would be reported by composer when the repo changes license over time)

**Comment by Seldaek** [comment]
The API is still in dev preview, so I would rather hold back for now. Once it becomes part of official API I think it would make sense to use that as fallback if the license is not specified yes.

**Comment by Seldaek** [comment]
I think I'd rather close this. We now complain harder on packagist.org for maintainers that do not specify it, so hopefully the situation has gotten better.
