### ISSUE TITLE
Propagate memory_limit to scripts

### ISSUE THREAD

**Issue by xavierleune** [composer/composer#6075]
Hello,

I've a standard symfony install, but it actually needs more memory than the default from my php.ini (128M) to execute cache:clear. 

When I run this command:

```
php -dmemory_limit=256M app/console cache:clear --env=qlf --no-debug
```

I get the following output:

```
 // Clearing the cache for the qlf environment with debug true                                                          

 [OK] Cache for the "qlf" environment (debug=true) was successfully cleared.    
```

But when I run this command:

```
php -dmemory_limit=256M /usr/local/bin/composer.phar install
```

I get the following output:

```
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

 // Clearing the cache for the qlf environment with debug true                                                          


Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 2097152 bytes) in /data/www_branche/vhosts/www.linternaute.com/vendor/twig/twig/lib/Twig/TokenParser/If.php on line 65

                                                                                             
  [Symfony\Component\Debug\Exception\OutOfMemoryException]                                   
  Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 2097152 bytes)  
                                                                                             

cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>

Segmentation fault
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

```

And I expected this to happen: cache:clear ended well.

As you can see in the output, symfony can allocate 134217728 bytes, which is 128M - the default from ini file, not the value given through command line (256M).

It seems that there is no other option than changing the value from the ini file right now. Am I right ? So a good thing could be to propagate to the executed scripts the memory_limit from the current script.

Thank you very much for any feedback !

**Comment by staabm** [comment]
do you use windows? `Segmentation fault` on windows caused by cli opcache was a issue discussed a few days ago...

**Comment by staabm** [comment]
with https://github.com/johnstevenson/composer/commit/2c39c43a9e9c0ebf8b0477adcfdafc26b94116d7 the memory_limit itself should be passed into composer

**Comment by xavierleune** [comment]
@staabm thank you for your feedback. Unfortunately, this is under debian.

**Comment by johnstevenson** [comment]
This was fixed (it only broke if you were running xdebug) in 1.3.1

**Comment by xavierleune** [comment]
thanx @Seldaek !
