### ISSUE TITLE
Composer bin command

### ISSUE THREAD

**Issue by dbpolito** [composer/composer#6077]
My goal is to have something like [yarn](https://yarnpkg.com/en/docs/cli/bin) does:

````bash
yarn global bin
````

So we could have prettier `$PATH` vars:

````bash
export PATH="/usr/local/bin:/usr/local/sbin:`yarn global bin`:`composer global bin`"
````

Currently we have command `composer config bin-dir`, which almost does what i would like, instead of printing the relative path, it would return the absolute path.

So in comparison of:

````bash
$ composer global config bin-dir
Changed current directory to /Users/mac/.composer
vendor/bin
````

We just return:

````bash
$ composer global bin
/Users/mac/.composer/vendor/bin
````

-----

I can open an PR for this, just wanted to know if this is something useful to others too.

**Comment by alcohol** [comment]
I use this in my `.bashrc`:

```
# Check if Composer is available, and if so, add global Composer bin directory.
if command -v composer >/dev/null 2>&1; then
  export COMPOSER_HOME="$XDG_CONFIG_HOME/composer"
  export COMPOSER_CACHE_DIR="$XDG_CACHE_HOME/composer"
  PATH="$(composer global config bin-dir --absolute 2>/dev/null):$PATH"
fi
```
