### ISSUE TITLE
[IDEA] require-groups for better autoloading

### ISSUE THREAD

**Issue by tommy-muehle** [composer/composer#6078]
I had an idea for specific autoloading in application contexts with only **one single** composer.json file in project and without splitting the application in different parts with own composer.json files.

The idea is to add "group" or "context" blocks in the require or require-dev sections.
Here an example:

```
"require": {
    "default": { 
      "symfony/symfony": "^3.0"
    },
    "app": {
      "app/thing": "1.0.0"
    },
    "api": {
      "api/thing": "1.0.0"
    }
  }
```

The "app" context includes the "default" and "app" part. And the "api" context "default" and "api".
If you add no special contexts everything is in default and the normal process are running.

To select a specific autoloader i imagine something like this: 
```
# autoload_api.php
require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloader::getLoader('api');
```

For example in the Symfony context are multiple kernel's possible. With this feature you can only load the API autoloader in the ApiKernel class. And so long in CLI- or normal AppKernel classes.

I hope that is clear enough to understand. What do you think about? It is possible? Or i'm out of touch?

*Note*
Please close the issue if there is any related issue open or existing. I searched for some keywords but personal found nothing in this topic.

**Comment by alcohol** [comment]
But.... why?

**Comment by stof** [comment]
I think what you want may be this plugin: https://github.com/beberlei/composer-monorepo-plugin

**Comment by stof** [comment]
anyway, I'm -1 for adding complexity to the require section to create contexts. It would become hard to understand IMO, for no real benefit (and then people will ask us to be able to have different package versions installed for each contexts, becoming an even bigger WTF)

**Comment by tommy-muehle** [comment]
@alcohol 
Just for performance.

@stof 
Thank you for the great hint with the composer plugin! 

And you're right. The complexity can be a problem. But to refute your complexity-example i would say that a package is further unique in the require or require-dev section and can therefore be only stay in one context. Shared packages (for all contexts) must stay in the "default" context.

**Comment by alcohol** [comment]
@tommy-muehle you are wrong, a package is not unique in the `require` or `require-dev` section. These are merged and together result in one list of requirements. Hence, having the same package in both will result in losing the constraint for one or the other.

**Comment by tommy-muehle** [comment]
@alcohol 
Thanks for clearing that up. Then PhpStorm with the composer plugin has always prevented me to add the same package twice. 

But to come to an end, i think my requirement isn't a general one. So the logic to do this might be better in a plugin, such as that the above.

**Comment by stof** [comment]
@tommy-muehle but dependencies may be required by packages from several contexts, so they may still end up in multipke contexts
