### ISSUE TITLE
[feature request] `support.changelog` in composer.json

### ISSUE THREAD

**Issue by brandonkelly** [composer/composer#6079]
The composer.json [`support` property](https://getcomposer.org/doc/04-schema.md#support) can already have the sub-properties

- `email`
- `issues`
- `forum`
- `wiki`
- `irc`
- `source`
- `docs`
- `rss`

It would be nice if Composer supported a `changelog` property as well, which could be set to the URL of a public changelog for the project, e.g. https://github.com/laravel/framework/blob/5.3/CHANGELOG-5.3.md .

**Comment by alcohol** [comment]
Personally not keen on this suggestion, but, we'll see.

**Comment by Seldaek** [comment]
I think that's the sort of stuff we should rather automate or standardize than force everyone to define it and keep it up to date. It's definitely something we hope to push forward with https://packagist.com in the coming months, so we will hopefully see progress on this front.
