### ISSUE TITLE
Composer hangs on "Resolving dependencies through SAT"

### ISSUE THREAD

**Issue by wesleylancel** [composer/composer#6089]
I have composer.json that require's one private package from a git repository. This private package requires several other packages, some stable ones, some dev-master ones.

When I run `composer install` (I don't have a `.lock` file yet) it will hang on `Resolving dependencies through SAT` forever (taking ~1.4GB RAM, confirmed on about 5 different systems).

However, when I run `composer install` in a clone of the private package it will resolve the dependencies in just a few seconds and install everything correctly.

Versions:
```
php -v
PHP 7.0.9 (cli) (built: Jul 21 2016 14:50:47) ( NTS )

composer --version
Composer version 1.3.1 2017-01-07 18:08:51
```

**Comment by alcohol** [comment]
Need a reproducible scenario.

**Comment by wesleylancel** [comment]
@alcohol I've set up a public repository that should reproduce the same issue using the following composer file: https://gist.github.com/wesleylancel/39024bf9eefab8c8be8bc1156fe5473b

If you clone the required repository manually and run `composer install` it'll work fine.

**Comment by alcohol** [comment]
From the example I draw the conclusion that you are trying to recursively use custom repository definitions.

https://getcomposer.org/doc/faqs/why-can%27t-composer-load-repositories-recursively.md

**Comment by wesleylancel** [comment]
@alcohol That does indeed seem to resolve the issue. Shouldn't that throw some sort of error though? Now it keeps running indefinitely...

**Comment by alcohol** [comment]
No because it does not see it.

**Comment by alcohol** [comment]
You can work around it by adding all the repository definitions to your root composer.json

**Comment by wesleylancel** [comment]
@alcohol Thanks, am aware, just didn't notice it here. It's just a little confusing no error is thrown, if any of your required packages does this, it won't be easy debugging where the issue is originating.

**Comment by alcohol** [comment]
Public packages should never require private packages. Private packages are outside of our scope.

**Comment by wesleylancel** [comment]
Yeah, but the issue isn't specifically related to it being private or not, just to custom repositories.
