### ISSUE TITLE
ShowCommand exits 0 even if given package is not installed

### ISSUE THREAD

**Issue by dzuelke** [composer/composer#6092]
Before afdae9c0e2094e8e6f0884167caa1022df7d99bf, `composer show something/notinstalled` would return 1 if the package was not installed.

Now the exit status is always 0, so code that calls the command can no longer determine if a package is installed or not.

**Comment by dzuelke** [comment]
This is caused by #6001, which should be rolled back. The "fix" is actually what's broken. It intentionally no longer returns 1, just because someone wrote a bash script that doesn't handle errors properly.

**Comment by alcohol** [comment]
I would agree that this should return `1` if the show command is called with a not installed package as argument.

**Comment by Seldaek** [comment]
Fixed by #6093
