### ISSUE TITLE
create project http auth is overridden by global auth.json

### ISSUE THREAD

**Issue by mikeymike** [composer/composer#6096]
We work on Magento and have to access their composer repository to pull packages down. This has basic http auth running for both it's community and enterprise packages. 

We keep our personal keys which have access to public repositories in ~/.composer/auth.json

When running the command below it fails trying to find the EE package. After removing the personal auth details from the global auth.json file it works fine. 

```
create-project -q --repository="https://xxxx:xxxx@repo.magento.com" magento/project-enterprise-edition magento2
```

Unfortunately running `-vvv` doesn't provide any more details on what's actually happening so I can  at this point only assume it doesn't check if the http auth details are in the url and always uses the auth.json details if they exist. 

Is this intentional, it would seem to me that details provided on cli would take precedence ?

Thanks 😄

**Comment by mikeymike** [comment]
Also to note each enterprise license has it's own key pair so the auth in the url was to override the public keys

**Comment by alcohol** [comment]
Not sure I understand your flow.

Might be worthwhile to note that `create-project a/b` is basically the same as:
1. git clone a/b source repo
2. switch to output directory of step 1
3. run composer install
4. (optional, default) remove .git directory

**Comment by mikeymike** [comment]
For standard Magento community projects the personal keys in `~/.composer/auth.json` would handle all http auth for us.

More often than not we need to create Magento enterprise projects but they require separate http auth details to access the enterprise packages which are unique for every client. 

I understand that create-project is a convenience command but it would be nice to still be able to use it and to be able to override the auth details stored globally.

**Comment by Seldaek** [comment]
That is odd because according to https://github.com/composer/composer/blob/9e592f5748511d64ad8c909cd242020c434b5537/src/Composer/Util/RemoteFilesystem.php#L211 the user/pass from the URL should become the one that is used for that hostname..

**Comment by Seldaek** [comment]
Closing as nobody cared to fix it in these many years, if it is still applicable do tell and I will reopen.
