### ISSUE TITLE
Composer is taking a long time to download provider

### ISSUE THREAD

**Issue by ross-chater** [composer/composer#6101]
Downloading http://packagist.org/p/provider-2016-07%24be4ebd626ddcbcf8434576189c56cedfb8237f4191903a345f6f6d3b3b2f896e.json

This hangs on here for ~5-10 mins

Even in a fresh directory, "composer init" then "composer require cakephp/cakephp"

All of my projects using packagist are taking a long time to update / install.

I can curl these json files in seconds just to note.  

Thanks

**Comment by staabm** [comment]
maybe your composer connection works thru a proxy and your curl doesnt?

**Comment by ross-chater** [comment]
I fully removed all cache / config and re-installed composer. Unless that sort of time to get providers is normal, and once in cache it works as expected?

**Comment by staabm** [comment]
Try checking with wireshark in between

**Comment by alcohol** [comment]
Looks like a networking issue. Check firewall, proxy or virus scanner activity. Not composer related.

**Comment by Seldaek** [comment]
Closing as we don't have enough info to reproduce..
