### ISSUE TITLE
Composer, git and recursive composer update

### ISSUE THREAD

**Issue by laurentdinclaux** [composer/composer#6102]
I manage my wordpress plugins in a private gitlab. I know about satis and toran but I need users access per repo. One customer may have access to a few repos but may not access some others. Other customers may have different repos permissions.

Git with composer is great. I give access to a few repos to a customer in gitlab (so he can report issues and follow development). I then generate a token for that user and configure his website/app with an auth.json. At the end he only has access to the repos he can access in gitlab, all good.

My issue is that some repos have sub-repos. So when I `composer update`, the sub-repos do not retrieve the composer packages they need, leading to a non-functional app.

I could I please fix that ?

**Comment by alcohol** [comment]
https://getcomposer.org/doc/faqs/why-can%27t-composer-load-repositories-recursively.md

**Comment by laurentdinclaux** [comment]
It the mean time I setup satis and it also doesn't handle recursive repos using repos of the composer type. Bummer, going to work on GitLab CI...

**Comment by alcohol** [comment]
It does not because you misunderstood how Satis fits into this picture. Not a single solution supports recursive repositories.

This does not work:
```
root composer (custom repo definition for a/a)
  `- private package a/a (custom repo definition for b/b)
    `- private package b/b
```

This also does not work:
```
root composer (satis repo definition)
  `- private package a/a (listed in satis, custom repo definition for b/b)
    `- private package b/b
```

This works:
```
root composer (satis repo definition)
  `- private package a/a (listed in satis)
    `- private package b/b (listed in satis)
```

Your satis instance needs to contain the custom repository definition for each private package you want to host/proxy.

**Comment by laurentdinclaux** [comment]
I have:

root composer (a/a satis repo definition)
  `- private package a/a (listed in satis)
    `- public package b/b (listed in packagist)

Shouldn't that work ?

**Comment by alcohol** [comment]
Yes. But Satis does not have to mirror the public package in that case. Can you define more clearly what does not work for you?

**Comment by stof** [comment]
Composer **never** create vendor subdirectories inside packages. there is a single vendor folder containing all necessary packages (class names and function names are global in PHP, so there is no way to isolate dependencies as done by npm)

**Comment by laurentdinclaux** [comment]
I have a root package that refers another package (hosted in satis).
In its composer.json, that package has a composer.json and a php file with an `include __DIR__ . '/vendor/autoload.php'`

If I `composer update` the root package, the child package get downloaded but no vendor/autoload.php, so the app throws an error.

**Comment by alcohol** [comment]
Ok, from the sound of this I am getting the feeling that you are quite new to using Composer. Please take the time to read through our documentation first, starting at https://getcomposer.org/doc/00-intro.md

**Comment by stof** [comment]
> That other package has a composer.json and a php file with an include __DIR__ . '/vendor/autoload.php'

well, this means that your other package is incompatible with the fact of being installed as a composer dependency of another package. This package should be fixed.

**Comment by laurentdinclaux** [comment]
This package should be able to be used standalone too. And yes I am new to composer.

So I guess I need a way to have it built using gitlab ci before so that satis retrieves it with the vendor package populated.

**Comment by alcohol** [comment]
Please the documentation. I am not here to repeat everything that is already explained in there.

**Comment by stof** [comment]
@laurentdinclaux no, you should write your require statement in a way supporting the package to be installed as a dependency (tons on packages are doing on Packagist, including composer itself, so it is definitely possible)

**Comment by laurentdinclaux** [comment]
That wouldn't work. The root package is basically a WordPress website and
sub packages are plugins and themes.

Le 26 janv. 2017 21:48, "Christophe Coevoet" <notifications@github.com> a
écrit :
