### ISSUE TITLE
PHP CLI has stopped working

### ISSUE THREAD

**Issue by bgillet** [composer/composer#6106]
My environment is :

- PHP 7.1.1 x64 NTS
- Windows Server 2012 x64
- IIS

No problem to install Composer following web site procedure but when I try the following command : `php composer`, PHP CLI crashes.

![image](https://cloud.githubusercontent.com/assets/3019854/22336466/ada3afe6-e3e2-11e6-9fcc-fb9707db0336.png)

![image](https://cloud.githubusercontent.com/assets/3019854/22336496/c78e2346-e3e2-11e6-8ea5-281444374566.png)

When looking for similar issues, I found this one on GitHub : #3971

It is closed and talks about a problem with opcache extension when enabled with CLI.

I have opcache extension enabled so I tried with the following option in my php.ini file : `opcache.enable_cli=0`

With opcache disabled for CLI, composer works and I don't have anymore crashes.

So issue #3971 is still existing.

**Comment by stof** [comment]
This should be reported to PHP. Segfaults are bugs in PHP itself, not in code written in PHP

**Comment by bgillet** [comment]
OK. I has already been done : https://bugs.php.net/bug.php?id=73983
