### ISSUE TITLE
dump-autoload generates absolute (system-dependent) PSR4 fallback paths on Windows (not on CentOS)

### ISSUE THREAD

**Issue by hngl** [composer/composer#6108]
When I `dump-autoload`, I get a different result on Windows than on CentOs. On Windows, some PSR4 fallback dirs are listed as _absolute paths_ in `autoload_static.php`, where they should be _relative paths_. (As they are generated on CentOS).

These absolute paths do not exist on the production server, making the classes in the actual fallback dir unloadable.

With this `composer.json` (in full at the bottom):
```json
"autoload": {
	"psr-4": {
		"": ["shared/", "library/"]
	}
```

On CentOS 7 I get:
```{php}
    public static $fallbackDirsPsr4 = array (
        0 => __DIR__ . '/../..' . '/shared',
        1 => __DIR__ . '/../..' . '/library',
    );
```

On Windows 10 I get:
```{php}
    public static $fallbackDirsPsr4 = array (
        0 => __DIR__ . '/../..' . '/shared',
        1 => 'Z:\\local_repo\\php\\library',
    );
```

Do you know a solution?

PS: I know PSR4 fallback are sub optimal performance wise. Yet this way we could already start using Composer with minimal change to our process and our legacy code.

--- the data ---

My `composer.json`:
```json
{
	"config": {
		"vendor-dir" : "library/"
	},
	"require": {
	  "smarty/smarty": "2.*",
	  "firebase/php-jwt" : "*"
	},
	"autoload": {
		"psr-4": {
			"FooTrait\\": "shared/database/FooTrait",
			"": ["shared/", "library/"]
		},
		"files": [
			"shared/Bar.php",
			"shared/Baz.php",
			"shared/Qux.php"
		]
	}
}
```

Output of `composer diagnose`:
```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Defining autoload.psr-4 with an empty namespace prefix is a bad idea for performance
require.firebase/php-jwt : unbound version constraints (*) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:
```
composer dump-autoload
```

I get the following output:
```{php}
    public static $fallbackDirsPsr4 = array (
        0 => __DIR__ . '/../..' . '/shared',
        1 => 'Z:\\local_repo\\php\\library',
    );
```

And I expected this to happen:
```{php}
    public static $fallbackDirsPsr4 = array (
        0 => __DIR__ . '/../..' . '/shared',
        1 => __DIR__ . '/../..' . '/library',
    );
```

**Comment by stof** [comment]
Is ``library`` a junction to code being elsewhere ?

**Comment by hngl** [comment]
@stof No, it is a simple folder inside the project file structure:

```
(root)
    - docs/
    - php/
        - shared
        - library
        - ...
    - composer.json

**Comment by alcohol** [comment]
If both shared and library are just plain directories, then it does not make sense for Composer to treat them differently. Can you please verify that library is no a junction (the windows equivalent of a symlink).

**Comment by alcohol** [comment]
Also why are you using psr4 fallback instead of classmap?

**Comment by hngl** [comment]
@alcohol Folders `shared` and `library` are not junctions.

Command:
```
dir /a /l
```
Response (redacted for brevity):
```
Directory of Z:\local_repo\php

27-01-2017  11:20    <DIR>          .
27-01-2017  11:20    <DIR>          ..
23-12-2016  10:17               626 .htaccess
10-01-2017  13:23    <DIR>          admin
27-01-2017  11:20    <DIR>          api
23-11-2016  10:25                79 bootstrap.php
09-01-2017  10:08               823 check.php
27-01-2017  11:20    <DIR>          cronjobs
10-01-2017  13:23             1.431 index.html
27-01-2017  11:20    <DIR>          library
18-12-2015  19:33    <DIR>          locale
10-01-2017  13:23             1.539 maintenance.php
02-12-2015  16:50                26 robots.txt
27-01-2017  13:48    <DIR>          shared
(...)
               8 File(s)         25.425 bytes
              10 Dir(s)   1.093.861.376 bytes free

```

**Comment by hngl** [comment]
@alcohol 

> Also why are you using psr4 fallback instead of classmap?

Because that would require us to add a build step in our process for every time a dev adds/renames a class in that folder. We will probably will do so in the future, but I want to start using Composer now. :-)

> PS: I know PSR4 fallback are sub optimal performance wise. Yet this way we could already start using Composer with minimal change to our process and our legacy code.

**Comment by alcohol** [comment]
> Because that would require us to add a build step in our process for every time a dev adds/renames a class in that folder. We will probably will do so in the future, but I want to start using Composer now. :-)

What? Why?

```
"classmap": [ "shared", "library" ]
```

**Comment by hngl** [comment]
I understand how the `classmap` mode works.

That does not change that the PSR4 fallback mode is inconsistent between CentOS and Windows.

**Comment by alcohol** [comment]
Yeah I have no way to reproduce this since I do not do any development on Windows. Maybe someone else can help you.

**Comment by curry684** [comment]
This is likely an unfortunate by-effect of `findShortestPathCode` being used in https://github.com/composer/composer/blob/1dcb2b5758f34e7e68b5a321deca72822774731a/src/Composer/Autoload/AutoloadGenerator.php#L760.

Is the issue reproducible if you rename `Z:\\local_repo` to `Z:\\local_repository` temporarily?

**Comment by hngl** [comment]
@curry684

Renaming `Z:\\local_repo` to `Z:\\local_repository` gets same undesirable effect.
```
    public static $fallbackDirsPsr4 = array (
        0 => __DIR__ . '/../..' . '/shared',
        1 => 'Z:\\local_repository\\php\\library',
    );
```
Second fallback written as absolute path.

**Comment by hngl** [comment]
I changed `composer.json`, and it seems the absolute path has something to do with the `library` folder, which is also the vendor dir.

`composer.json` version A:
```
    "autoload": {
        "psr-4": {
            "": ["./shared", "./library"]
        }
    }
```

gets `autoload_static.php` version A:
```
    public static $fallbackDirsPsr4 = array (
        0 => __DIR__ . '/../..' . '/shared',
        1 => 'Z:\\local_repository\\php\\library',
    );
```

`composer.json` version B (notice the order of 'shared' and 'library'):
```
    "autoload": {
        "psr-4": {
            "": ["./library", "./shared"]
        }
    }
```

gets `autoload_static.php` version A:
```
    public static $fallbackDirsPsr4 = array (
        0 => 'Z:\\local_repository\\php\\library',
        1 => __DIR__ . '/../..' . '/shared',
    );
```

**Comment by alcohol** [comment]
> `library` folder, which is also the vendor dir

Wait, what the fuck? How can library be your vendor directory?

**Comment by curry684** [comment]
Hmm didn't see that one coming but it would explain the shortest path detection breaking.

@alcohol it's regrettably a [documented feature](https://getcomposer.org/doc/06-config.md#vendor-dir). Probably because it has valid reasons for integrating with legacy systems. But it does allow Pandora's box of referential hell implicitly.

**Comment by alcohol** [comment]
Yeah I know it is possible. But I am just wondering who would actually do something like that? That just opening a can of worms that should stay shut closed. It is literally begging for problems.
