### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by yinm** [composer/composer#6111]
there are two install method.
* [the PHP command](https://getcomposer.org/download/)
* [Shell Script](https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md)

It is not easy to find Shell Script version.
Moving the section of Shell Script from [the current section](https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md) to [the PHP command section](https://getcomposer.org/download/) improves it.
If the suggestion is good, I will update documents with Pull requests.

**Comment by alcohol** [comment]
But that first page links directly to the second already.

Did you not see the giant box containing

> WARNING: Please do not redistribute the install code. It will change with every version of the installer. Instead, please link to this page or check [how to install Composer programmatically](https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md).

?

**Comment by yinm** [comment]
Thank you for the reply.

I saw the giant box, but it was after installation with the PHP command.
I think that it is easier to understand if it clearly stated that there are two methods like [the section of composer's installation](https://getcomposer.org/doc/00-intro.md#downloading-the-composer-executable).

> There are in short, two ways to install Composer. Locally as part of your project, or globally as a system wide executable.
Locally# ...
Globally# ...

**Comment by Seldaek** [comment]
I don't think we want to confuse people with one more choice to do, if 90% need the first option..
