### ISSUE TITLE
Failed to decode zlib stream

### ISSUE THREAD

**Issue by bishwaskalika** [composer/composer#6112]
Please help me sir i have this error while installing composer
![screenshot 445](https://cloud.githubusercontent.com/assets/23506220/22395679/4dbc1f28-e56d-11e6-9895-2dbc892adb1e.png)
 "Failed to decode zlib stream"

```
...replace me...
```

When I run this command:

```
...replace me...
```

I get the following output:

```
...replace me...
```

And I expected this to happen:

**Comment by rmgarcia1** [comment]
Itay

**Comment by alcohol** [comment]
This is most often a bad firewall or proxy configuration. We cannot solve this from Composer's end.
