### ISSUE TITLE
How to assign/set composer to use different PHP version ?

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [composer/composer#6113]
I am trying to use composer with PHP version 7.0.15, I am having multiple PHP versions on wamp, the composer is taking 5.5.12 as default, how I can change it to different versions as per my requirement now and in future ? You cna check my localhost is running PHP 7.0.15 but composer is using 5.5.12 while adding laravelcollective/html v5.4.1 to my project.

![issue](https://cloud.githubusercontent.com/assets/2470646/22396173/85539474-e578-11e6-9c35-ebbfedb254ea.JPG)

**Comment by staabm** [comment]
Either prepend your php binary with path `\path\to\your\php composer.phar ...`
Or change the %PATH% environment variable to fix it globally

**Comment by PrafullaKumarSahu** [comment]
@staabm  I should add E:\work\bin\php\php7.0.15 or I need to replace E:\work\bin\php\php5.5.12 with it ? which will be correct ?

**Comment by PrafullaKumarSahu** [comment]
extra information composer using perhaps php set on cli and i need to change that ?

PHP 5.4.45 (cli) (built: Sep  2 2015 23:48:00)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

**Comment by staabm** [comment]
Composer uses whatever is defined in your %PATH% env variable.

**Comment by PrafullaKumarSahu** [comment]
I have just uploaded the screenshot of my env setting can you confirm if I am doing something wrong ?

![env](https://cloud.githubusercontent.com/assets/2470646/22396508/3cda72e0-e581-11e6-9d52-2d744cfdb35c.JPG)

**Comment by staabm** [comment]
As you can see, the 2 row in your path points to 5.x. Windows is starting to work thru this list from the top to the bottom and will use the one find first

**Comment by PrafullaKumarSahu** [comment]
so it should use PHP7.0.15 now ?

**Comment by staabm** [comment]
Not with config depicted in your screenshot. You need to move php7 before php5 (to the top)

**Comment by PrafullaKumarSahu** [comment]
added it like this now getting Warning: PHP Startup: Unable to load dynamic library 'E:/work/bin/php/php7.0.15/ext/php_mysql.dll' - The specified module could not be found.
 in Unknown on line 0
PHP 7.0.15 (cli) (built: Jan 17 2017 13:58:38) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies


![env](https://cloud.githubusercontent.com/assets/2470646/22396566/a4de955a-e582-11e6-802e-7a536acee13c.JPG)

**Comment by PrafullaKumarSahu** [comment]
but in php.ini file I can see extension=php_mysql.dll so his does not has a semicolon before it, so it should be active ?

**Comment by staabm** [comment]
So its using the 'correct' php version now. Looks like your php.ini is configured to load a not existing extension.

**Comment by staabm** [comment]
> but in php.ini file I can see extension=php_mysql.dll so his does not has a semicolon before it, so it should be active ?

It is configured so php tries to load it.. maybe your dll is missing or corrupt. Try to comment this line

**Comment by PrafullaKumarSahu** [comment]
perfect, loved your explanation thank you so much.

**Comment by staabm** [comment]
You are welcome. Please close this issue if there is nothing more left todo

**Comment by PrafullaKumarSahu** [comment]
@staabm  already done . thank you .
