### ISSUE TITLE
Cannot install on Windows 2016 Server

### ISSUE THREAD

**Issue by thebe14** [composer/composer#6116]
Setup on Windows 2016 fails with the message:

The installation directory "C:\Users[myuser]\AppData\Local\Temp\is-ERG11.tmp" is not writable.

I tried running the installer both by double-clicking on it directly (although my user is a domain user that is part of the local Administrators group) or by right-clicking it and Run as Administrator. Both fail with the same error and the path is under my user's AppData folder, which makes me guess that there is some problem with unpacking the files. I surely hope that that is NOT the install location.

**Comment by johnstevenson** [comment]
@alcohol Also reported here: https://github.com/composer/windows-setup/issues/67

**Comment by alcohol** [comment]
I closed the wrong one, my bad :<
