### ISSUE TITLE
Question: Version suffixes

### ISSUE THREAD

**Issue by emodric** [composer/composer#6118]
I've tried searching existing issues, but could not find anything useful.

What would be the best way to handle version suffixes, for example `1.1.0` and `1.1.0-someclient`?

Use case is to have a private repo with a versioning scheme following semver, but also to have a feature branch which has the same versions tagged, but with an added suffix. This branch usually has a client specific fix, which sometimes cannot be overriden easily in a client project or is used across multiple client projects. Now the problem is not in the package itself, but in the packages which have the first package listed as a dependency.

Now, I know I can use `replace` and rename the package in Composer, which solves the technical side of the story, but sometimes it's not practical, because now we need to have a separate repo with separate issues, wiki, pull requests and so on. It complicates life both to us and clients.

A potential new feature to support version suffixes would be to allow installation of versions which have a specific suffix, similar to version stability, while making the suffixed versions be normalized to versions without suffix.

Any tips?

Thanks!

**Comment by alcohol** [comment]
This is a design/release problem really. Not a problem that Composer should solve.

**Comment by emodric** [comment]
@alcohol I'm aware of that. I was asking for a tip on how to handle it efficiently, since it's likely that other Composer users and maintainers must have ran into simmilar issues themselves.

But other than that, I think that issue is worthwhile exploring, since version suffixes are not that really uncommon and I'm sure users wouldn't mind if Composer supported them.

**Comment by alcohol** [comment]
We do not support anything beyond `-stable|beta|b|RC|alpha|a|patch|pl|p`, for legacy reasons, and we do not plan on supporting anything more. You can add metadata using the `+modified` as defined in semver but it is not taken into account when resolving dependencies afaik.

**Comment by alcohol** [comment]
And yes, I too have been in exactly the same situation as you are (one product, multiple "client specific versions"). But it really is not complicated to solve once you understand that Composer is **not** a deployment tool. We simply created release packages (.tar.gz archives) from our core version + branch specific fixes (for each client) and deployed those.

**Comment by emodric** [comment]
Alright, thanks for the tips!
