### ISSUE TITLE
Method of determining if .json and .lock are in sync.

### ISSUE THREAD

**Issue by wackyMole** [composer/composer#6120]
So, it's weird that it's taken this long to become an issue but...

I used to have a build step that would check that `composer.json` and `composer.lock` were in sync. This was to prevent someone from manually editing `composer.json` and then committing that change without doing the necessary work with Composer to update the lock file (`update` or `install` or whatever)

The build did this by hashing `composer.json` and the comparing that to the hash in `composer.lock`. However, `hash` was removed in 1.3.0(?) This is now causing the build to fail because `hash` is undefined.

I understand the reasoning behind removing `hash`. However, with that gone, what is the suggested method of checking that `composer.json` is in sync with `composer.lock`?

**Comment by alcohol** [comment]
We switched to another hash that merely checks the relevant attributes, rather than the whole file. It is called `content-hash`.

**Comment by alcohol** [comment]
But a simple way to check it would be:

```
rob ~/projects/php/composer/composer > composer validate
./composer.json is valid
The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update`.
rob ~/projects/php/composer/composer > echo $?
2
```

**Comment by curry684** [comment]
@alcohol that's not a full solution as it would also fail with the same error code if you are missing the mandatory properties `name` and `description`, which are actually only mandatory for libraries and thus rarely filled in for projects.

`composer install --dry-run` is more reliable I think, but it would make sense to add a flag somewhere to just do the hash checks, it's pretty useful for scripted validators and health checking code.

**Comment by alcohol** [comment]
@curry684 what is wrong with

```
rob ~/projects/php/composer/composer > composer validate --no-check-publish
./composer.json is valid
The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update`.
rob ~/projects/php/composer/composer > echo $?
2
```

?

**Comment by curry684** [comment]
That it has no verbosity at all as to what you're doing in your script, just what you're not doing  :P   Your script output might break if some day `composer validate` is also extended to check whether you have enough RAM to run the solver. A check that would surely fail in a microsized production environment. Which could still want to self-check on startup that it's deployment is sane.

`composer validate --only-lock` seems like a good idea for the case at hand to match the `--no-check-lock` option already there.

**Comment by stof** [comment]
@curry684 validate is not about checking if your system is able to run composer. We already have ``diagnose`` for that.
Repurposing the command for something else in the future would be a huge BC break

**Comment by curry684** [comment]
Ok bad example, point remains that it doesn't make sense to use an exclusion flag to select a single check.

**Comment by stof** [comment]
btw, validating the composer.json content makes sense for a CI system too. So I don't see the need to exclude the basic validity checks from your CI scripts.

**Comment by curry684** [comment]
I agree that just using `composer validate` would be the most brilliant solution, but it would require the project author to follow library conventions and add a name and description. Not really sure why that's a hard error in validate anyway right now - a warning would also suffice stating the composer.json is valid in itself but not fit for distribution platforms.

**Comment by stof** [comment]
@curry684 well, this is precisely why there is a ``--no-check-publish`` option, disabling **only** rules specific to published packages (it does not disable the whole composer.json validation).
And using this option makes totally sense if your package is not meant to be published (it is *exactly* what you need)

**Comment by curry684** [comment]
Why are you always right?  😆 

I'll shut up now, not my day hehe.
