### ISSUE TITLE
composer exec fails silently

### ISSUE THREAD

**Issue by Sarke** [composer/composer#6122]
My `composer.json` (not relevant):

```json
{
    "name": "user/comp",
    "authors": [
        {
            "name": "user",
            "email": "user@host.com"
        }
    ],
    "require": {}
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer exec notarealcommand
```

I get the following output:

```
(nothing)
```

And I expected this to happen: Get an error message.

When I run this command:

```
composer -v exec notarealcommand
```

I get the following output:

```
> __exec_command: notarealcommand
sh: 1: notarealcommand: not found
Script notarealcommand handling the __exec_command event returned with error code 127
```

The big problem with this is if I run `composer exec codecept run` and any of the tests fail then the output is blank.

**Comment by alcohol** [comment]
```
rob ~/projects/php/composer/composer > composer exec lol
rob ~/projects/php/composer/composer > echo $?
127
```

Pretty obvious that it failed, so what is the problem here?

**Comment by Sarke** [comment]
@alcohol, like I said, the big problem with this is when I run tests and any of them fail then I don't get any output.

**Comment by alcohol** [comment]
I don't even understand why you want to use `composer exec` for this. Why not just call the tests directly?

**Comment by Sarke** [comment]
@alcohol https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-testing.md

**Comment by alcohol** [comment]
Ugh.

Ok I don't know why they would advocate that approach. I recommend you figure out where the codecept binary gets installed (most likely either in `bin` or in `vendor/bin`), and then just call that directly, e.g:

```
bin/codecept build
bin/codecept run
```
or
```
vendor/bin/codecept build
vendor/bin/codecept run
```

Composer exec really should not be used imho.

**Comment by Sarke** [comment]
Ok, thank you.  Did this behavior recently change, or was it always silent on error?

And are you saying `composer exec` should **never** be used?  Is it being deprecated?

**Comment by alcohol** [comment]
I honestly have no idea. I never use it. I just do not advocate adding more complexity for the sake of absolutely nothing. There is absolutely no reason to use `composer exec` in this scenario. I can look into how this could be handled more gracefully, when I have the time.

**Comment by alcohol** [comment]
Weird I just ran it through xdebugger. It makes plenty of calls that should write output to stderr, but yet nothing is output. Have to further debug why this is failing.

**Comment by alcohol** [comment]
Ok I figured it out. It is because of these lines in the `exec` command:

```php
        if ($output->getVerbosity() === OutputInterface::VERBOSITY_NORMAL) {
            $output->setVerbosity(OutputInterface::VERBOSITY_QUIET);
        }
```

This basically means that `composer exec` always runs as if `--quiet` is passed, except when you pass in one or multiple verbosity flags (`-v|vv|vvv`).

In quiet mode, even errors are ignored it seems.

**Comment by Sarke** [comment]
Looks like this was introduced 11 months ago:

https://github.com/composer/composer/pull/4887 / 
https://github.com/composer/composer/commit/934be204a2a0811f01f5e84e6132c38bf8a5107b

**Comment by alcohol** [comment]
I think some people were annoyed by the output of
```
> command called
```

Can never make everyone happy it seems...

**Comment by Sarke** [comment]
Well there should be some middle ground.  Composer outputs could be hidden I guess, but hiding the output of the called script or command is a little overkill.

**Comment by curry684** [comment]
Ewww that bit of code is terrible - see nothing hear nothing approach. No matter the argument, quiet mode should never be enabled without explicit user intent.

I assume this predates the global cleanup of moving all diagnostic output to STDERR. If the command called is now correctly moved from STDOUT to STDERR this change should be reverted.

**Comment by alcohol** [comment]
A simple fix would be to make the errors write at level QUIET (since the Symfony component only hides them if message level > writer level). Should be a small fix.

**Comment by alcohol** [comment]
@curry684 no I believe it is related to some refactoring done by Fabien, where before it was simply using echo/print, and now it is using the IO instance to write to stderr. See #5852

**Comment by curry684** [comment]
In any case an unfortunate side effect methinks  ;)

**Comment by alcohol** [comment]
Yeah, but like I said, small thing to fix.

**Comment by ElisDN** [comment]
The `exec` command allowed to run binaries from local and global `vendor` directories both. In the quiet mode this command is useless.

**Comment by curry684** [comment]
@alcohol in that case I suggest a relabel from 'support' to 'bug+easy-pick'  😉
