### ISSUE TITLE
Bug in resolver: conflict message, when there is no conflict

### ISSUE THREAD

**Issue by christian-weiss** [composer/composer#6124]
Tested with:
 - composer 1.3.2 2017-0-27 18:23:41
 - composer 1.2.2

If you have myvendorname/mydependencyA releases:
 - 1.0.1
 - 1.0.2
 - 1.0.3

and if you have two version constrains in your projects composer.json as follows:
```
  "require": {
    "myvendorname/mydependencyA": "1.0.2"
  },
  "require-dev": {
    "myvendorname/mydependencyA": "1.0.*"
  },
```

composer should: 
evaluate the constraint "1.0.2" to be satisfiable by release "1.0.2" 
AND
evaluate the constraint "1.0.*" to be satisfiable by release "1.0.1", "1.0.2", "1.0.3"

The intersection of both is "1.0.2" and "1.0.2" should be used as "installable".

At the moment composer complains this as a conflict:
```
composer install --prefer-dist
Loading composer repositories with package information
Updating dependencies (including require-dev)

                                                                                                                                                       
  [Composer\DependencyResolver\SolverProblemsException]                                                                                                
    Problem 1                                                                                                                                          
      - The requested package myvendorname/mydependencyA 1.0.2 exists as myvendorname/mydependencyA[1.0.3] but these are rejected by your constraint.  
                                                                                                                                                       

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
```

While this can be considered to be an edge case and a "1.0.*" constraint in require-dev do not add a benifit at a global perspecitve. This bug maybe cause other "hard to discover" or "hard to reproduce" behaviors and should be fixed.

By the way: switching the "require" and "require-dev" constrains results in "1.0.2" installed, without a conflict message. Moving one constraint into a  mydependencyB package (which requires mydependencyA) are resolved and installed as expected, too.

**Comment by stof** [comment]
having the same package listed in require and in require-dev is an unsupported case. It creates weird things in the solver.

btw, ``composer validate`` **already** marks this as an issue (since years).

**Comment by christian-weiss** [comment]
Ok, i did not run "composer validate". Thanks. Issue can be closed
