### ISSUE TITLE
Brainstorming: Vendor files shared between projects? (to reduce memory usage)

### ISSUE THREAD

**Issue by donquixote** [composer/composer#6125]
On a server with many distinct PHP projects, memory usage could be reduced by having those projects use a shared vendor repository, sharing those vendor files that are identical.

To make this work, the shared repository would have to be able to provide multiple versions of the same library or file, because sometimes one project might require a different version of the same library than another project.

One idea to achieve this would be symlinks.. But I don't know if PHP actually saves memory by caching symlinked PHP files. Only profiling can tell.

If not using symlinks, the autoloader would have to point to those external file paths in the shared directory structure. Those paths could look like this: `path-to-shared-vendor-dir/acme/foolib/1.0.5/src/SomeClass.php`, so the version would be part of the path.

Somehow the shared repository would need to keep track of the different users, so it can determine which files can be deleted.

All of this is obviously not easy or trivial, so it is only worthwhile if more people are interested, and if it can be proven that there is a benefit.

## Alternative: PHP itself

Maybe this sharing should really be implemented in PHP itself? By caching opcodes by hash, not by file path, so identical files are cached in a shared instance.

Again, I know too little about how PHP works internally to determine if this is a good idea.

I imagine that the opcache of a file also depends on global symbols from other files. E.g. if the file defines a class with `extends`, and the extended class is defined in a different file.

## Motivation: Drupal multisite

Why am I asking this?

In Drupal 7 and Drupal 8 there is a feature called "multisite". It allows to start with a shared `index.php`, then have mostly shared PHP, but then have some PHP code that is only available for a specific site (e.g. domain).

For Drupal 9 there is a general desire to use Composer for module downloading. This makes the multisite feature more tricky.
https://www.drupal.org/node/2306013

One use case that has been reported is higher education websites.
One major reason (but not the only one) why people use this feature is to reduce the memory footprint that would occur if every single website would have their own instance of Drupal core and modules, and possibly other libraries.

Having a mechanism in Composer to reduce memory usage when having many websites/projects with shared code dependencies, would eliminate this specific reason for multisite. There might still be other reasons left, of course.

Even if this looks like a Drupal-specific use case, I could easily imagine similar needs can occur outside of Drupal.

**Comment by curry684** [comment]
This has been discussed at length before and is technically impossible because of the way autoloading and namespaces work. The simple and unavoidable fact is that you cannot share a codebase between multiple subprojects requiring different versions of the same class in the same namespace. No discussion possible, it's PHP itself blocking that, just like Java, C#, C++ and to my knowledge every other object oriented language out there.

**Comment by donquixote** [comment]
Do you remember where this was discussed?

What would happen if two projects attempt to do this?
Or for the sake of the example, just two different files? And using `__autoload()` for simplicity.

projects/a/index.php

```
function __autoload($class) {
  switch ($class) {
    case 'Acme\Foo\C':
      require_once 'shared/path/to/acme/foo/1.0.0/src/C.php';
      return;
    case 'Acme\Bar\C':
      require_once 'shared/path/to/acme/bar/1.0.0/src/C.php';
      return;
  }
}

new Acme\Foo\C;
new Acme\Bar\C;
```

projects/b/index.php

```
function __autoload($class) {
  switch ($class) {
    case 'Acme\Foo\C':
      // Same version as in a/index.php
      require_once 'shared/path/to/acme/foo/1.0.0/src/C.php';
      return;
    case 'Acme\Bar\C':
      // Different version than in a/index.php
      require_once 'shared/path/to/acme/bar/1.0.1/src/C.php';
      return;
  }
}

new Acme\Foo\C;
new Acme\Bar\C;
```

Obviously, a/index.php and b/index.php can never both be included at the same request / process.
But having separate requests to either one, I don't see where this would cause a problem.
In fact it is already happening in Drupal multisite, and possibly in some other projects with funky conditional autoload logic.

**Comment by donquixote** [comment]
So, in other words: Can you provide a reproducible example where this blows up?

**Comment by alcohol** [comment]
Please use the search functionality. @curry684 is right, this has been discussed at lengths several times in the past years. It is not feasible, not in the past, not now, and not in the future.

**Comment by donquixote** [comment]
Indeed some issues already exist where this or something similar is being discussed.
But you need to be lucky with your search terms. The issues are not nicely interlinked or enriched with keywords.

I like this one, #5046 "Shared packages [question]" (you need to search for "packages")

**Comment by donquixote** [comment]
@curry684 
Maybe we have a misunderstanding?

> This has been discussed at length before and is technically impossible because of the way autoloading and namespaces work. The simple and unavoidable fact is that you cannot share a codebase between multiple subprojects requiring different versions of the same class in the same namespace. No discussion possible, it's PHP itself blocking that, just like Java, C#, C++ and to my knowledge every other object oriented language out there. It can't be fixed because it's the problem namespaces were invented for in the first place.

After reading some of the other issues, I still do not buy this statement.

I can understand if Composer simply does not want to support this use case to avoid complication.
But that it would be technically impossible, I disagree.

The only limitation is that different versions of a class, function etc cannot coexist _within one request / process_. Otherwise, as pointed out in my previous comment, the basic functionality is already happening in real world projects, and can be demonstrated in simple experiments.

**Comment by alcohol** [comment]
@donquixote 

> On a server with many distinct PHP projects, memory usage could be reduced by having those projects use a shared vendor repository, sharing those vendor files that are identical.

This will hardly save you any memory at all.

However, something similar to your proposal could be achieved just as easily manually by adding all the libraries that your projects have in common to a global composer.json as path repositories that are checked out on your server. That way, all your projects will simply symlink to the same source files for those respective packages and versions.

Composer cannot support the feature you requested because an autoloader simply cannot know what version you need. An autoloader only receives the request to load a class, based on a string such as `Foo\Bar\Baz`. If one project requires this version at `1.0.0` and another project requires it at version `2.0.0`, then how do you expect us to make this distinction?

**Comment by curry684** [comment]
> The only limitation is that different versions of a class, function etc cannot coexist within one request / process

While technically correct this practically means the proposal is unfeasible. It means that caches, compiled data, storage drivers etc. may be serialized, read, unserialized, normalized, processed, you name it, differently between 2 different requests. With the most practical example in casu: the multisite definitions may not even be compatible between the participating sites.
