### ISSUE TITLE
Failed to clone http://github.com/fabpot/Twig.git, git was not found, check that it is installed and in your PATH env.

### ISSUE THREAD

**Issue by dcb** [composer/composer#613]
I'm getting the error in the subject on an Ubuntu 10.4 machine. git is working fine and it is in the path. I even updated to git 1.7.10 using the launchpad package, but the problem persisted. I also tried different packages in the composer.json file, still the error persisted. I am using php 5.4.0, compiled from sources.

POSSIBLE SOLUTION: If you have ansicon installed on windows try to remove it, see https://bugs.php.net/bug.php?id=63567 and comments for more details.

**Comment by JASONMUKAMA** [comment]
here is my test
string(4) "test"
array(1) {
  [0]=>
  string(4) "test"
}
int(0)
