### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by mahadebkesh** [composer/composer#6130]
<?php
namespace Firebase;
require_once __DIR__ . "/../src/firebaseLib.php";
use Exception;
class FirebaseTest extends \PHPUnit_Framework_TestCase
{
    protected $_firebase;
    protected $_todoMilk = array(
        'name' => 'Pick the milk',
        'priority' => 1
    );
    protected $_todoBeer = array(
        'name' => 'Pick the beer',
        'priority' => 2
    );
    protected $_todoLEGO = array(
        'name' => 'Pick the LEGO',
        'priority' => 3
    );
    // --- set up your own database here
    const DEFAULT_URL = 'https://mysite';
    const DEFAULT_TOKEN = 'My Key';
    const DEFAULT_TODO_PATH = '/sample/todo';
    const DELETE_PATH = '/sample';
    const DEFAULT_SET_RESPONSE = '{"name":"Pick the milk","priority":1}';
    const DEFAULT_UPDATE_RESPONSE = '{"name":"Pick the beer","priority":2}';
    const DEFAULT_PUSH_RESPONSE = '{"name":"Pick the LEGO","priority":3}';
    const DEFAULT_DELETE_RESPONSE = 'null';
    const DEFAULT_URI_ERROR = 'You must provide a baseURI variable.';
    public function setUp()
    {
        $this->_firebase = new FirebaseLib(self::DEFAULT_URL, self::DEFAULT_TOKEN);
    }
    public function testNoBaseURI()
    {
        $errorMessage = null;
        try {
            new FirebaseLib();
        } catch (Exception $e) {
            $errorMessage = $e->getMessage();
        }
        $this->assertEquals(self::DEFAULT_URI_ERROR, $errorMessage);
    }
    public function testSet()
    {
        $response = $this->_firebase->set(self::DEFAULT_TODO_PATH, $this->_todoMilk);
        $this->assertEquals(self::DEFAULT_SET_RESPONSE, $response);
    }
    public function testGetAfterSet()
    {
        $response = $this->_firebase->get(self::DEFAULT_TODO_PATH);
        $this->assertEquals(self::DEFAULT_SET_RESPONSE, $response);
    }
    public function testUpdate()
    {
        $response = $this->_firebase->update(self::DEFAULT_TODO_PATH, $this->_todoBeer);
        $this->assertEquals(self::DEFAULT_UPDATE_RESPONSE, $response);
    }
    public function testGetAfterUpdate()
    {
        $response = $this->_firebase->get(self::DEFAULT_TODO_PATH);
        $this->assertEquals(self::DEFAULT_UPDATE_RESPONSE, $response);
    }
    public function testPush()
    {
        $response = $this->_firebase->push(self::DEFAULT_TODO_PATH, $this->_todoLEGO);
        $this->assertRegExp('/{"name"\s?:\s?".*?}/', $response);
        return $this->_parsePushResponse($response);
    }
    /**
     * @depends testPush
     */
    public function testGetAfterPush($responseName)
    {
        $response = $this->_firebase->get(self::DEFAULT_TODO_PATH . '/' . $responseName);
        $this->assertEquals(self::DEFAULT_PUSH_RESPONSE, $response);
    }
    public function testDelete()
    {
        $response = $this->_firebase->delete(self::DELETE_PATH);
        $this->assertEquals(self::DEFAULT_DELETE_RESPONSE, $response);
    }
    public function testGetAfterDELETE()
    {
        $response = $this->_firebase->get(self::DEFAULT_TODO_PATH);
        $this->assertEquals(self::DEFAULT_DELETE_RESPONSE, $response);
    }
    /**
     * @param $response
     * @return mixed
     */
    private function _parsePushResponse($response)
    {
        $responseObj = json_decode($response);
        return $responseObj->name;
    }
}
?>

But it gives Error

Warning: require_once(/home/bosstesting/public_html/centralize_server/../src/firebaseLib.php): failed to open stream: No such file or directory in /home/bosstesting/public_html/centralize_server/test1.php on line 3

Fatal error: require_once(): Failed opening required '/home/bosstesting/public_html/centralize_server/../src/firebaseLib.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/bosstesting/public_html/centralize_server/test1.php on line 3

**Comment by curry684** [comment]
Please follow the provided template for reporting issues and check for the readability of your issue after posting.

**Comment by mahadebkesh** [comment]
pls give me solution as soon possible...

*Thanks and Regards.*

*Mahadeb  Kesh*

*Software  Developer*

*Mail Id* :- * mahadebkesh8@gmail.com <mahadebkesh8@gmail.com> /
mkesh101@gmail.com <mkesh101@gmail.com>*

*Mobile:-  9555679731 / 9953335783*

**Comment by mahadebkesh** [comment]
i don't have    firebaseLib.php code

**Comment by curry684** [comment]
We are not the firebase support desk and we cannot provide you help with your Composer issue if you do not provide usable and readable information. If you need a solution *as soon as possible* try helping us help you.

**Comment by keshmahadeb** [comment]
Hello sir,
I am new in firebase.
My projects is Fetch Data from firebase Realtime database  for my Employee tracking.
First i have create  a project in firebase.Then it gives me some Script Code like that

<script src="https://www.gstatic.com/firebasejs/3.6.8/firebase.js"></script>
<script>
  // Initialize Firebase

  var config = {
    apiKey: "Key",
    authDomain: "projectname",
    databaseURL: "Proect Url",
    storageBucket: "name",
    messagingSenderId: "id"
  };
  
  firebase.initializeApp(config);
  var database = firebase.database();
  console.log(database);
  
</script>

but i can not understand what to do now to fetch data from Firebase.

**Comment by stof** [comment]
@keshmahadeb this is the issue tracker of composer, not of firebase. Fetching info from firebase has **nothing** to do with Composer, so we cannot help you. contact the firebase support instead.
