### ISSUE TITLE
Composer does not respect vendor package composer.json 's repository setting

### ISSUE THREAD

**Issue by netroby** [composer/composer#6135]
We using composer to manage our php packages internals. 

we have a core framework , named ```btches-core```, it has several internal package dependencies. we add repositories config to ```btches-core``` ```composer.json```
like 
```
{
      "type": "vcs",
      "url": "git@g*******/modulea_develop.git"
    },
    {
      "type": "vcs",
      "url": "git@g*/dependency-injection.git"
    }
}
```

And we create new project, add btches-core as requirement. then run composer.phar update

```
{
  "name": "a********t",
  "description": "a************t site",
  "type": "project",
  "license": "MIT",
  "minimum-stability": "stable",
  "repositories": [
    {
      "type": "vcs",
      "url": "git@g*********/btches-core.git"
    }
  ],
  "require": {
    "btches-core/btches-core":"dev-master"
  }
}

```
the composer.phar can not find repository  , so can not find packages anywhere.

the error message looks like:
```
    - btches-core/btches-core dev-master requires modulea ^v2.2 -> no matching package found.

```

**Comment by alcohol** [comment]
https://getcomposer.org/doc/faqs/why-can%27t-composer-load-repositories-recursively.md
