### ISSUE TITLE
fopen(): failed to open stream: Invalid argument

### ISSUE THREAD

**Issue by wilmarcarinan** [composer/composer#6138]
Hello, I can't seem to run `composer update` or `composer install` in my command line. I've tried running `composer update --prefer-source` because someone with this error fixed this by running this command. However it's still not working for me. This was the error: **fopen(C;\Users\toshiba\AppData\Local\Temp;C:xampp\php.exe/composer-cacert-300c74d6960d46715ffed607c8e36acfa7cbcad49862bb1b67d3c43dea9bfb40.pem): failed to open stream: Invalid argument**
![image](https://cloud.githubusercontent.com/assets/14357042/22661082/fb38686e-ecde-11e6-8338-bb81886abf7f.png)

One more thing that I've seen is that when I run composer, there is also an error indicating that **PHP temp directory does not exist or is not writable to composer. Set sys_temp_dir in your php.ini**. 
![image](https://cloud.githubusercontent.com/assets/14357042/22661371/1a53f2da-ece0-11e6-95e7-78bd2d9d6297.png)

Thanks

**Comment by johnstevenson** [comment]
What value have you got in your php.ini for `sys_temp_dir` ?

**Comment by wilmarcarinan** [comment]
@johnstevenson `; sys_temp_dir = "/tmp"` It was comment out.

**Comment by johnstevenson** [comment]
I asked because I could replicate your issue if I defined `sys_temp_dir` with the value reported in the error message: _C;\Users\toshiba\AppData\Local\Temp;C:xampp\php.exe_ which looks path-like.

However the fact that it is commented out, somewhat disproves that theory, unless you are looking at the wrong php.ini?

**Comment by wilmarcarinan** [comment]
I'm sure that I'm looking at the correct php.ini. Isn't there only one php.ini in php directory?

**Comment by johnstevenson** [comment]
You can check which ini files are being used by running `php --ini`.

Trying a different approach, run `echo %TMP%` to see where your system tmp dir points to.
