### ISSUE TITLE
reproducable build documentation

### ISSUE THREAD

**Issue by igalic** [composer/composer#6141]
I cannot seem to find any documentation concerning builds of composer.
In trying to, naïvely, build it for [habitat.sh](https://github.com/habitat-sh/core-plans/) by replacing `#/usr/bin/env php` with habitat's path to `env` or `php`. which, of course, breaks the SHAxxx sum.

Is there a way to reproduce the build with a specific `env`/`php` path?

**Comment by alcohol** [comment]
If you need to run composer through a specific PHP version, simply run it is `/path/to/phpbinary /path/to/composer.phar <options>`.
