### ISSUE TITLE
[Question] Why "require" dependencies from "require-dev" load with --no-dev flag?

### ISSUE THREAD

**Issue by ericdowell** [composer/composer#6144]
My `composer.json`:

```json
{
    "name": "package/some-api",
    "description": "Fluent interface to some api",
    "require": {
        "php": ">=5.5.9",
        "guzzlehttp/guzzle": "~6.2",
        "illuminate/support": "~4.1|~5.1"
    },
    "require-dev": {
        "codeclimate/php-test-reporter": "dev-master",
        "mockery/mockery": "^0.9.4",
        "orchestra/testbench": "~3.0",
        "phpunit/phpunit": "~6.0"
    },
    "autoload": {
        "psr-4": {
            "SomeApi\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "SomeApi\\Tests\\": "tests/src/"
        }
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "branch-alias": {
            "dev-master": "1.0-dev"
        }
    },
    "minimum-stability": "stable"
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```bash
composer install --no-dev
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies
Package operations: 29 installs, 0 updates, 0 removals
  - Installing psr/log (1.0.2) Loading from cache
  - Installing symfony/debug (v3.2.3) Loading from cache
  - Installing symfony/polyfill-mbstring (v1.3.0) Loading from cache
  - Installing symfony/console (v3.2.3) Loading from cache
  - Installing symfony/event-dispatcher (v2.8.17) Loading from cache
  - Installing symfony/css-selector (v3.2.3) Loading from cache
  - Installing vlucas/phpdotenv (v2.4.0) Loading from cache
  - Installing tijsverkoyen/css-to-inline-styles (2.2.0) Loading from cache
  - Installing symfony/var-dumper (v3.2.3) Loading from cache
  - Installing symfony/routing (v3.2.3) Loading from cache
  - Installing symfony/process (v3.2.3) Loading from cache
  - Installing symfony/http-foundation (v3.2.3) Loading from cache
  - Installing symfony/http-kernel (v3.2.3) Loading from cache
  - Installing symfony/finder (v3.2.3) Loading from cache
  - Installing swiftmailer/swiftmailer (v5.4.5) Loading from cache
  - Installing paragonie/random_compat (v2.0.4) Loading from cache
  - Installing ramsey/uuid (3.5.2) Loading from cache
  - Installing symfony/translation (v3.2.3) Loading from cache
  - Installing nesbot/carbon (1.22.1) Loading from cache
  - Installing mtdowling/cron-expression (v1.2.0) Loading from cache
  - Installing monolog/monolog (1.22.0) Loading from cache
  - Installing league/flysystem (1.0.34) Loading from cache
  - Installing erusev/parsedown (1.6.1) Loading from cache
  - Installing doctrine/inflector (v1.1.0) Loading from cache
  - Installing laravel/framework (v5.4.10) Downloading: 100%         
  - Installing guzzlehttp/promises (v1.3.1) Loading from cache
  - Installing psr/http-message (1.0.1) Loading from cache
  - Installing guzzlehttp/psr7 (1.3.1) Loading from cache
  - Installing guzzlehttp/guzzle (6.2.2) Loading from cache
Writing lock file
Generating autoload files
```

And I expected this to happen:

```
Loading composer repositories with package information
Updating dependencies
Package operations: 8 installs, 0 updates, 0 removals
  - Installing guzzlehttp/promises (v1.3.1) Loading from cache
  - Installing psr/http-message (1.0.1) Loading from cache
  - Installing guzzlehttp/psr7 (1.3.1) Loading from cache
  - Installing guzzlehttp/guzzle (6.2.2) Loading from cache
  - Installing paragonie/random_compat (v2.0.4) Loading from cache
  - Installing illuminate/contracts (v5.4.9) Loading from cache
  - Installing doctrine/inflector (v1.1.0) Loading from cache
  - Installing illuminate/support (v5.4.9) Downloading: 100%         
Writing lock file
Generating autoload files
```

**Comment by ericdowell** [comment]
`composer --version` output:
```
Composer version 1.4-dev (07123715d6782185b25059871f272054057333c7) 2017-01-27 17:44:31
```

**Comment by stof** [comment]
can you post the output of ``composer show -t`` ?

**Comment by stof** [comment]
and also the output of ``composer why symfony/http-kernel`` please

**Comment by ericdowell** [comment]
`composer show -t` outputs
```
guzzlehttp/guzzle 6.2.2 Guzzle is a PHP HTTP client library
├──guzzlehttp/promises ^1.0
│  └──php >=5.5.0
├──guzzlehttp/psr7 ^1.3.1
│  ├──php >=5.4.0
│  └──psr/http-message ~1.0
│     └──php >=5.3.0
└──php >=5.5
```

`composer why symfony/http-kernel` outputs:
```
laravel/framework  v5.4.10  requires  symfony/http-kernel (~3.2)
```

I also did a rollback to `Composer version 1.3.2 2017-01-27 18:23:41` and got the same output for all these commands.

**Comment by ericdowell** [comment]
`laravel/framework` is a "require" dependency of [orchestra/testbench composer.json](https://github.com/orchestral/testbench/blob/e80767d56bb34036d2520bd69d67fc09433e069c/composer.json#L26)

**Comment by alcohol** [comment]
Huh weird, I can reproduce this.

```
rob /tmp > composer install --no-dev
Loading composer repositories with package information
Updating dependencies
Package operations: 29 installs, 0 updates, 0 removals
  - Installing psr/log (1.0.2) Loading from cache
  - Installing symfony/debug (v3.2.3) Downloading: 100%         
  - Installing symfony/polyfill-mbstring (v1.3.0) Loading from cache
  - Installing symfony/console (v3.2.3) Downloading: 100%         
  - Installing symfony/event-dispatcher (v3.2.3) Loading from cache
  - Installing guzzlehttp/promises (v1.3.1) Loading from cache
  - Installing psr/http-message (1.0.1) Loading from cache
  - Installing guzzlehttp/psr7 (1.3.1) Loading from cache
  - Installing guzzlehttp/guzzle (6.2.2) Loading from cache
  - Installing symfony/css-selector (v3.2.3) Downloading: 100%         
  - Installing tijsverkoyen/css-to-inline-styles (2.2.0) Downloading: 100%         
  - Installing vlucas/phpdotenv (v2.4.0) Loading from cache
  - Installing symfony/var-dumper (v3.2.3) Downloading: 100%         
  - Installing symfony/routing (v3.2.3) Downloading: 100%         
  - Installing symfony/process (v3.2.3) Downloading: 100%         
  - Installing symfony/http-foundation (v3.2.3) Downloading: 100%         
  - Installing symfony/http-kernel (v3.2.3) Downloading: 100%         
  - Installing symfony/finder (v3.2.3) Loading from cache
  - Installing swiftmailer/swiftmailer (v5.4.5) Loading from cache
  - Installing paragonie/random_compat (v2.0.4) Loading from cache
  - Installing ramsey/uuid (3.5.2) Downloading: 100%         
  - Installing symfony/translation (v3.2.3) Downloading: 100%         
  - Installing nesbot/carbon (1.22.1) Downloading: 100%         
  - Installing mtdowling/cron-expression (v1.2.0) Downloading: 100%         
  - Installing monolog/monolog (1.22.0) Loading from cache
  - Installing league/flysystem (1.0.34) Downloading: 100%         
  - Installing erusev/parsedown (1.6.1) Downloading: 100%         
  - Installing doctrine/inflector (v1.1.0) Loading from cache
  - Installing laravel/framework (v5.4.10) Downloading: 100%         
Writing lock file
Generating autoload files
rob /tmp > composer why league/flysystem
laravel/framework  v5.4.10  requires  league/flysystem (~1.0)
rob /tmp > composer why ramsey/uuid
laravel/framework  v5.4.10  requires  ramsey/uuid (~3.0)
rob /tmp > composer why nesbot/carbon
laravel/framework  v5.4.10  requires  nesbot/carbon (~1.20)
rob /tmp > composer why laravel/framework
There is no installed package depending on "laravel/framework"
```

Clean install without a lock file. Definitely peculiar. Lot of dependencies installed because of `laravel/framework`, but no reason for installing `laravel/framework`.

**Comment by curry684** [comment]
> and also the output of `composer why symfony/http-kernel` please

In debugging this `composer why -r` for recursive is more useful. Same output though, so definitely a bug.

As you can see `illuminate/support` is not installed, despite being on the `require` end of things. Because Composer resolves all `dev` dependencies as well in `--no-dev` mode, it recursively ends up with `laravel/framework` which [**replaces**](https://packagist.org/packages/laravel/framework) `illuminate/support`. So suddenly our dev dependency gets replaced in the solver by a **normal** dependency which does not get pruned before installing.

**Comment by Seldaek** [comment]
Yeah the issue is that we resolve ALL dependencies together, so really to get reliable information from the `why` command you need to install dev dependencies too, otherwise you might not get valid information.

As has been discussed in the past, this can't really be changed, we need to resolve all deps in one go, no matter if you decide to install dev ones or not.. I don't think this issue can be solved. And ultimately as laravel just replaces stuff, it's not really a problem, it just means you have a bit more code installed than you'd need in --no-dev mode, but everything should still be functional.

**Comment by curry684** [comment]
@Seldaek I don't really agree with closing this, as the behaviour is actually a bug with consequences. If TS ships his `composer.lock` to production and hits `composer install --no-dev` he will get a non-working application because of a missing package. It may not be a high priority bug, with a usable workaround, but it still warrants solving one day.

How complex would my suggested fix be? To my knowledge the solver has all the required knowledge at that point.

**Comment by Seldaek** [comment]
Why would it result in a broken application? The missing package is replaced by laravel as far as I can tell, so it's not broken, just more code than necessary?

**Comment by curry684** [comment]
```
$ composer why laravel/framework
There is no installed package depending on "laravel/framework"
```
As 'why' works from the lockfile my assumption would be that this means the package was installed from the to-be-installed list, but never made it to the lockfile because it has no parents after no-dev pruning.

Could be wrong though, my test case is on my home laptop so would need to check there.

**Comment by Seldaek** [comment]
`why` works from what is installed not from the lock file, and that doesn't answer why the package would be broken? :)

If you install without --no-dev you get this:

```
$ composer why laravel/framework
orchestra/testbench  v3.4.4  requires  laravel/framework (~5.4.0)
```

So in --no-dev, the package that caused laravel to be installed is not installed, but to compute what --no-dev installs we just remove the dev requirements, pin everything in require dev, and only allow it to uninstall what's not needed anymore, so if laravel sticks around in --no-dev it is because it is useful, as it replaces some stuff that is in `require`.

The only thing to fix eventually would be improving the `why` command so it traces back replacers better.. We already did quite a bit of that I thought for symfony use cases. It doesn't seem to work here I'm not sure why and I don't really have time to dig in at the moment, but I still am not convinced anything is broken otherwise.

**Comment by ericdowell** [comment]
My expected behavior of `--no-dev` is to not look at anything in `require-dev`. Why is this not the case?

**Comment by Seldaek** [comment]
https://github.com/composer/composer/issues/5652#issuecomment-245541348 includes some explanations, but the TL;DR is that it introduces inconsistencies for example in your case the packages resolved would be very different, and require + require-dev isn't a predictable set of packages vs require alone. 

We did it like you suggest before, and it didn't work. It means some edge cases like this one are a bit sub-optimal but then again a dev tool requiring an entire framework is a bit extreme too..

**Comment by curry684** [comment]
> why works from what is installed not from the lock file

I should really get back in this project when getting corrected on how why works, considering I wrote the damn thing myself haha 😆 

> and that doesn't answer why the package would be broken? :)

Not the package but the project would be broken if it only installed resolved prod deps, as illuminate/support isn't in there. If that isn't happening closing is fine with me - it's indeed an edge case and the test tool shouldn't depend on a whole framework indeed.
