### ISSUE TITLE
When 1.3.3 hotfix will be released?

### ISSUE THREAD

**Issue by garex** [composer/composer#6147]
Weird exception on package update is driving us crazy.

```
 [ErrorException]                 
  A non-numeric value encountered  
```

I see, that this fixed in master, but it's critical enough for hotfix.

update1: Current workaround is to use `composer self-update --snapshot`

**Comment by garex** [comment]
@alcohol why do you closed this issue? Nobody answered about release date still.

**Comment by alcohol** [comment]
It will be released when it is released.

**Comment by garex** [comment]
Amaizing answer ))

What prevents you or person, who responsible for releases to make a hotfix release?

**Comment by staabm** [comment]
@garex because you can use `composer self-update --snapshot` and people working on composer do it in their free time.

**Comment by garex** [comment]
@staabm We all know it. I just can't understand why do you think that broken main composer feature "update" is not critical for hotfix? It's not something rare-used, but main and basic feature, which everyone used everyday.

In russian internet we have this meme for it ))

![image](https://cloud.githubusercontent.com/assets/77981/22778828/da102c04-eeea-11e6-9545-f228b47c4f1d.png)

**Comment by staabm** [comment]
> We all know it. I just can't understand why do you think that broken main composer feature "update" is not critical for hotfix?

noone says that the fix itself is not critical or subject for a hotfix.

still you need to accept that people working on composer do it in their free time for no-money to provide a service for everyone.
