### ISSUE TITLE
outdated command requires packages to be installed

### ISSUE THREAD

**Issue by buffcode** [composer/composer#6148]
My `composer.json`:

```json
{
    "require": {
        "twig/twig": "1.*"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
$ rm -rf vendor
$ composer outdated
```

I get the following output:

```
<no output>
```

And I expected this to happen:
The `outdated` command requires all packages to be actually be installed. As the `composer.lock` (seemingly) contains all required information already, the command should work without installation as well.

Expected output without any packages installed should be identical to the current output with all packages installed:
```
twig/twig v1.31.0 v2.1.0 Twig, the flexible, fast, and secure template language for PHP
```

**Comment by alcohol** [comment]
You are misinformed. It uses the installed.json inside vendor/composer. Composer lock merely contains information on what **should** be installed, not what is actually installed.
