### ISSUE TITLE
[question] Library and private (local) vcs server

### ISSUE THREAD

**Issue by alexz707** [composer/composer#6149]
Hi! 
I have a question concerning libraries and private bitbucket server.
(I think the problem also occurs with other vcs...)

I have two libraries, let's call them `company/lib-a` and `company/lib-b`.
Both are on a non public local bitbucket server

urls:
- "https://user:pass@bitbucket.company.com/scm/company/lib-a.git"
- "https://user:pass@bitbucket.company.com/scm/company/lib-b.git"

The `lib-b` requires a specific version of `lib-a`.

My application`composer.json`:

```json
{
  "require": {
    "doctrine/common": "^2.6",
    "doctrine/orm": "^2.5.5",
    "company/lib-b": "1.0.0"
  },
  "repositories": [
    {
      "url": "https://user:pass@bitbucket.company.com/scm/company/lib-b.git",
      "type": "git"
    }
  ],
}
```
My lib-a`composer.json`:
```json
{
  "name":              "company/lib-a",
  "description":       "lib a stuff",
  "type":              "library",
  "minimum-stability": "stable",

  "require": {
    "php": ">=5.6",
    "doctrine/dbal": "2.5.10",
    "doctrine/orm": "^2.5.5",
  },
  "require-dev": {
    "phpunit/phpunit": "^5.7"
  },
  "autoload": {
    "psr-4": {
      "Company\\lib-a\\": "lib/Lib-a"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "Company\\lib-aTest\\": "tests/"
    }
  }
}
```
My lib-b`composer.json`:
```json
{
  "name":              "company/lib-b",
  "description":       "lib-b utilities",
  "type":              "library",
  "minimum-stability": "stable",
  "repositories": [
    {
      "url": "https://user:pass@bitbucket.company.com/scm/company/lib-a.git",
      "type": "git"
    }
  ],
  "require": {
    "php": ">=5.6",
    "company/lib-a": "0.1.1"
  },
  "require-dev": {
    "phpunit/phpunit": "^5.7"
  },
  "autoload": {
    "psr-4": {
      "Company\\lib-b\\": "lib/Lib-b"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "Company\\lib-bTest\\": "tests/"
    }
  }
}
```
When I run the composer update cmd I get the following:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for company/lib-b dev-master -> satisfiable by company/lib-b[dev-master].
    - company/lib-b dev-master requires company/lib-a 0.1.2 -> no matching package found.
```

So I assumed that when I run the composer update cmd in my application it should load the `lib-b` and check the requirements and load `lib-a` (which has its repos definded in the `lib-b` config). But this doesn't work.

It only works when I modify the `repositories` in my application `composer.json`:
```json
{
  "repositories": [
    {
      "url": "https://user:pass@bitbucket.company.com/scm/company/lib-a.git",
      "type": "git"
    },
    {
      "url": "https://user:pass@bitbucket.company.com/scm/company/lib-b.git",
      "type": "git"
    }
  ],
}
```
Is this intended or a bug? I expected not to write all repository locations into the application json because I have them in the libaries!?

Thanks for your suggestions/answers. ;)
alex

**Comment by alcohol** [comment]
This is intended.

https://getcomposer.org/doc/faqs/why-can%27t-composer-load-repositories-recursively.md

**Comment by alexz707** [comment]
Thanks for the fast clarification ! 👍
