### ISSUE TITLE
[Question] Can I specify custom json file for pulled packages ?

### ISSUE THREAD

**Issue by Kaukov** [composer/composer#6150]
Hey there!

I'm trying to use a custom composer.json file for a dev branch for a project containing multiple repositories that depend on each other. Each repository has a master and a dev branch. There is also a *master* package that pulls all of the repositories through composer.

The multiple repositories are set up like that because they can be pulled on their own and used in another project without requiring the *master* package.

My `composer.json`:

```json
"require": {
  "vendor/package1": "dev-branch",
  "vendor/package2": "dev-branch"
}
```

But many of the repositories pull the other ones through their own composer.json file. And, like in the *master* package, I have a custom composer.json in every other repository.

I can Issue `COMPOSER=composer.dev-branch.json php composer.phar update` on the *master* package, but it will only pull **package1** and **package2**'s *dev-branch* and the other packages will have their stable versions pulled.

Is there a way to specify the custom composer.json file in the pulled packages when updating the *master* package?

**Comment by alcohol** [comment]
Composer will read the composer.json of the version you require. You cannot specify a custom composer.json for your dependencies.

**Comment by Kaukov** [comment]
Okay, thanks!
