### ISSUE TITLE
Memory Leak with wired configuration

### ISSUE THREAD

**Issue by xrow** [composer/composer#6152]
Due to own failured I caused a memory leak, but maybe it should be there or could be resolved automaticly.

My `composer.json`:

When having this configiuration the memory leak doesn`t occur. My assumtion is the packagist gets loaded twice and maybe even produce a loop.
```json
        {
            "type": "composer",
	
            "url": "https://packagist.org"
        },
```
When having this configiuration the memory leak does occur.
```json
        {
            "type": "composer",
	
            "url": "https://packagist.org"
        },
        {
            "packagist": false
        },
```

When I run this command:

```
composer install
```

I get the following output:

```
PHP Fatal error:  Allowed memory size of 3196059648 bytes exhausted (tried to allocate 72 bytes) in /usr/share/php/Co
  mposer/DependencyResolver/RuleSetGenerator.php on line 126
```

And I expected this to happen:

a nice run...

**Comment by Seldaek** [comment]
If you define packagist twice, then yeah it'll use double the memory as it finds all the packages twice. So not so surprising, and not really a leak.. Not sure what we can do here.

**Comment by xrow** [comment]
You could ensure that it will not load them twice.
