### ISSUE TITLE
Self update prompt

### ISSUE THREAD

**Issue by pixiesky** [composer/composer#6153]
Currently composer will say after 60 days:

> Warning: This development build of composer is over 60 days old. It is recommended to update it by running "/home/vagrant/bin/composer self-update" to get the latest version.

It then immediately proceeds to run the command. I would like to be prompted with an option to update first before continuing.

**Comment by Seldaek** [comment]
That would probably break tons of CI and other automated environments that use snapshots (they shouldn't..) and don't use --no-interaction (they should) out there. You could argue that's a good thing as it would force people to look into their problems, but it's also causing pain for not much gain.

I'll leave open for now, if someone wants to look into it and finds a way to do it that doesn't introduce too much mess I guess why not..

**Comment by bbashy** [comment]
Settings file maybe?

**Comment by Maxim-Mazurok** [comment]
What about timeout? Like so:

1. Prompt `would you like to update [yes/No]:`
2. Give user about 5 seconds to make a choice
3. If no action taken - proceed to auto-update. Else - follow users choice.

This will give users an option, while not breaking "bad" CI's. Even more, "bad" CI users will probably notice that builds will take more time and hopefully will start to investigate into this and will finally start using `--no-interaction` option.

**Comment by Seldaek** [comment]
Yeah that's not a bad idea I guess.

**Comment by avant1** [comment]
Timeout sounds like a good idea.
However I don't think that it is fine to update Composer automatically if no input comes.
If something will be broken in new Composer release then large amount of CI's may be broken too.

This feature will be useful when you interact with composer manually, so I think it is better to do nothing if the question is not answered (developers usually are watching the output of command that they've just runned so they will have time to answer `Y`).

**Comment by Maxim-Mazurok** [comment]
@Seldaek ok then, I'll try to implement this.

@avant1 yep, I thought about it and personally I agree with you. But as I understand, now composer auto-updates if it's too outdated and many CI's may rely on that logic, so we shouldn't change it.

**Comment by Seldaek** [comment]
Composer does NOT auto-update ever right now, nope. And I agree it 
probably shouldn't. In non-interactive a warning is enough, and if 
interactive prompt and after 5 seconds discard and warn is probably 
fine, but I am not sure if we can do a 5seconds timeout prompt.. That'll 
probably be tricky.

**Comment by bamarni** [comment]
When composer is installed in /usr/local/bin for example it might fail to upgrade due to permissions issues. Maybe it could first check if the directory is writable before prompting the question? If it's not writable the execution could be stopped for a few seconds with the warning only, then continue, WDYT?

**Comment by Maxim-Mazurok** [comment]
@Seldaek oh, sorry, I'm still waking up :) Now it's clear, no auto-update by default. I think it's best practice and most applications handle it in the same way.
I have some ideas about implementation, will try them later.

**Comment by Seldaek** [comment]
TBH the more we discuss here the more I think this is insane and not worth the trouble/messy implementation. I think checking once a day max and warning users that a new version is available would be more than enough.

**Comment by bamarni** [comment]
How about just pausing for a few seconds? I think a lot of times the warning is just missed, with all the next output showing immediately.

**Comment by Seldaek** [comment]
Closing as it doesn't seem that important nor that easy to fix.
