### ISSUE TITLE
Unable to install composer on my windows 10 computer

### ISSUE THREAD

**Issue by musalo** [composer/composer#6154]
The "http://getcomposer.org/versions" file could not be downloaded: failed to open stream: No connection could be made because the target machine actively refused it.

**Comment by johnstevenson** [comment]
Are you installing using the Windows installer (Composer-Setup.exe) or from the command-line? It is a connectivity problem, may be a misconfigured proxy.

**Comment by musalo** [comment]
Thanks .I am installing using 
Windows installer (Composer-Setup.exe)

**Comment by johnstevenson** [comment]
Please provide the log file, as decribed here: https://github.com/composer/windows-setup#Troubleshooting

**Comment by musalo** [comment]
[Setup Log 2017-02-16 #005.txt](https://github.com/composer/composer/files/779760/Setup.Log.2017-02-16.005.txt)
[Setup Log 2017-02-16 #005.txt](https://github.com/composer/composer/files/779761/Setup.Log.2017-02-16.005.txt)

**Comment by musalo** [comment]
[Setup Log 2017-02-16 #006.txt](https://github.com/composer/composer/files/779794/Setup.Log.2017-02-16.006.txt)

**Comment by musalo** [comment]
use that last log file please
thanks

**Comment by johnstevenson** [comment]
From the log: `Found http_proxy in User environment`

Which means that you have an `http_proxy` variable set in your user environment, which must point to a non-working proxy (the log doesn't show the full details in case it contains a username/password).

You need to remove this from your user environment (or set it to a valid proxy if you need one)

**Comment by musalo** [comment]
.Thanks you alot.H
How can I remove http_proxy from user environment  Command prompt in windows??

**Comment by musalo** [comment]
.Thanks you alot.H
How can I remove http_proxy from user environment via Command  prompt in windows??

**Comment by johnstevenson** [comment]
You need to permanently remove the variable (cmd.exe will only remove it for the current session).

Control Panel | System | Advanced System Settings | Environment Variables

Or type _environment_ into the search box on the task bar.

**Comment by musalo** [comment]
Thank you very much.I have managed to install.
Once I run the composer command  it opens and closes instantly.what could be the problem??

**Comment by johnstevenson** [comment]
I presume you tried using it via Window's `Run`. However, Composer is a command line tool, so you need to run it from `cmd.exe` (or Git bash if you have Git installed).

**Comment by musalo** [comment]
thank you very much.Be blessed
