### ISSUE TITLE
Maintain order of libraries in composer.lock for version control systems

### ISSUE THREAD

**Issue by stopsopa** [composer/composer#6160]
Hi
I noticed that after "composer require" or "composer update" composer sometimes change order of libraries in composer.lock, which actually makes difficult to distinguish between what's changed and what's not in any diff tools in git. 
Maybe it's worth to add feature to keep order of records in newly generated composer.lock based on order of records in old composer.lock?
I think many people every day trying to understand what has changed in their projects after composer update/require that somebody from team did.
That's only suggestion.

...i love composer, great job :)

**Comment by stof** [comment]
that's weird. composer.lock stores packages in alphabetical order, precisely to make the order predictable and stable.
The only change which could happen is moving a package from a dev requirement to a normal requirement, as they are listed separately

**Comment by Taluu** [comment]
I also do not have this problem, whenever I am adding a new package (via `require`), or updating a single package, just the block with said package is "changed"...

**Comment by alcohol** [comment]
Please provide actual evidence, and preferably a reproducible scenario. To my knowledge, the scenario you are describing does not exist.

**Comment by Seldaek** [comment]
Auto-closing this as it's marked as support request and has not received any update in a long time.
