### ISSUE TITLE
remove hash

### ISSUE THREAD

**Issue by wanglilong2013** [composer/composer#6161]
my composer version is 1.3.2, while i run composer update ??/??,the hash is removed from composer.lock

**Comment by stof** [comment]
This is expected. Composer 1.3 does not generate this hash anymore.
Composer added ``content-hash`` years ago, which invalidates the lock file only when doing meaningful changes in the composer.json (so fixing a typo in the description, changing the license or fixing the autoloading config does not require rebuilding the lock file while it would not change its content as it does not impact the resolution process).
So the ``hash`` was finally removed, as it was unused.
Composer kept it in parallel for a while, to allow using composer 1.0.0-beta and stable releases on the same lock file for a while, but nobody should be using pre-1.0 unstable versions anymore now.
