### ISSUE TITLE
Update "justinrainbow/json-schema" to 5.0

### ISSUE THREAD

**Issue by cdekok** [composer/composer#6163]
Currently i have phpro/grumphp installed which depends on composer/composer
which causes me to not be able to install justinrainbow/json-schema" 5.0
can the dependency be upgraded to also support 5.0? I see it currently supports 3 and 4.

**Comment by stof** [comment]
json-schema 5.0 changed the public API of the library. So supporting it requires checking whether these changes impact us. I will try to look into this during the weekend if I can.
