### ISSUE TITLE
Version requirements of specific commits ignored?

### ISSUE THREAD

**Issue by andig** [composer/composer#6166]
My `composer.json`:

```json
{
    "name": "volkszaehler/volkszaehler",
    "type": "project",
    "description": "volkszaehler is a free smart meter implementation with focus on data privacy",
    "homepage": "http://www.volkszaehler.org/",
    "license": "GPL-3.0",
    "support": {
        "wiki": "http://wiki.volkszaehler.org/",
        "email": "volkszaehler@lists.volkszaehler.org"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "php": ">=5.6.0",
        "doctrine/orm": "^2.5",
        "doctrine/dbal": "^2.5",
        "andig/dbcopy": "dev-master",
        "symfony/console": "^2.6|^3.0",
        "symfony/http-kernel": "^2.6|^3.0",
        "symfony/http-foundation": "^2.6|^3.0",
        "symfony/routing": "^2.6|^3.0",
        "cboden/ratchet": "0.3.*",
        "react/socket": "0.4.*",
        "react/http": "dev-master#cd15204bd15d106d7832c680e4fb0ca0ce2f5e30"
    },
    "require-dev": {
        "phpunit/phpunit": "^4.4|^5.0",
        "react/http-client": "^0.3.2",
        "react/socket-client": "0.5.*",
        "ringcentral/psr7": "^1.2",
        "jenssegers/proxy": "^3.0-beta",
        "symfony/psr-http-message-bridge": "^1.0",
        "zendframework/zend-diactoros": "^1.3"
    },
    "autoload": {
        "psr-4": {
            "Volkszaehler\\": "lib/",
            "Tests\\": "test/"
        }
    },
    "suggest": {
        "jpgraph/jpgraph": "Server-side chart generation for volkszaehler"
    }
}
```

Has stopped working today after `reactphp/http` (https://github.com/reactphp/http/blob/master/composer.json) released v0.5 (which is after the sticky commit) which now requires `reactphp/socket@0.5`

Output of `composer diagnose`:

```
Checking composer.json: WARNING
The package "react/http" is pointing to a commit-ref, this is bad practice and can cause unforeseen issues.
require.andig/dbcopy : unbound version constraints (dev-master) should be avoided
require.react/http : unbound version constraints (dev-master#cd15204bd15d106d7832c680e4fb0ca0ce2f5e30) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer install
```

I get the following output:

```
➜  vz git:(master) ✗ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - react/http dev-master requires react/socket ^0.5 -> satisfiable by react/socket[v0.5.0] but these conflict with your requirements or minimum-stability.
    - react/http dev-master requires react/socket ^0.5 -> satisfiable by react/socket[v0.5.0] but these conflict with your requirements or minimum-stability.
    - Installation request for react/http dev-master#cd15204bd15d106d7832c680e4fb0ca0ce2f5e30 -> satisfiable by react/http[dev-master].
```

And I expected this to happen:

Clean install, `reactphp/socket` 0.4 installed as specified in the sticky commit at https://github.com/reactphp/http/blob/cd15204bd15d106d7832c680e4fb0ca0ce2f5e30/composer.json

It seems as if composer takes the `composer.json` version requirements from `dev-master`, not from `dev-master#commit`?

**Comment by stof** [comment]
This is explicitly documented. the commit locking is an *installer-level* hack. It does not impact the dependency resolution (composer cannot have metadata for arbitrary commits, it would make the amount of data stored and sent by Packagist totally insane)

**Comment by andig** [comment]
Darn- then I'm stuck for now and will probably resort to vcs alias until the upstream issues are resolved. Thank you for the quick answer.

**Comment by stof** [comment]
My advice is to completely avoid using this feature, all the time. It can only work temporarily.

It was added at a time where ``composer update`` did not support partial updates, as a way to partially emulate it.

**Comment by andig** [comment]
> My advice is to completely avoid using this feature, all the time. It can only work temporarily.

Good advise. Unfortunately we're fighting with a temporary upstream feature change that seemed to make this a feasible approach- at least for some time.

> the commit locking is an installer-level hack. It does not impact the dependency resolution

Testing some further I have the suspicion that the composer.json of the requested commit is not only ignored during dependency resolution but is also not used for installing the dependencies.

Is that the case?
