### ISSUE TITLE
Is it possible to declare dev repositories?

### ISSUE THREAD

**Issue by goetas** [composer/composer#6169]
We use a mono-repo, that gets split in multiple repos at each commit. Each folder of the root repo, is a new read-only repo, pushed to our git server.

Given the following composer.json
```json
{
    "require": {
        "company/my-package": "^2.2"
    },
    "repositories": [
        { "type": "path", "url": "../folder/my-package" }
    ]
}
```
During development this works nice, since a developer can modify the `company/my-package` code really easily and do cross package commits in the single repo we have.

But... this makes not possible to deploy the single mini repos since the folder `../folder/my-package` does not exist on the server prod... since on the prod server we would like to work only with the single mini repos.

Is there a way to define a "path" repo only when in development moe? Something as:

```json
{
    "require": {
        "company/my-package": "^2.2"
    },
    "repositories": [
        { "type": "path", "url": "../folder/my-package", "dev": true }
    ]
}
```
So this "path" repo  will be considered only in dev mode.... If the install is done in prod mode, it should use the "standard" packagist or other repos defined in the script.

This opens the possibility to do something as:

```js
{
    "require": {
        "company/my-package": "^2.2"
    },
    "repositories": [
        { "type": "path", "url": "../folder/my-package", "dev": true }, // used in dev
        { "type": "vcs", "url": "git://......", "dev": false } // used in prod
    ]
}
```

**Comment by alcohol** [comment]
No. Please use the search function.
