### ISSUE TITLE
Artifacts extracted paths

### ISSUE THREAD

**Issue by crowincage** [composer/composer#6173]
Hello :-)

I've read a lot about composer artifacts because for an 'offline' use this is the only possibility to use composer and other libraries in a current project. Unfortunately some things about artifacts are still not clear and I didn't find any solution an this.

To prepare the artifacts for the project I did a normal install of the packages on my local machine - excluding the artifact repository and packagist enabled. After install I've created zip files of each package with:

`cd vendor/package && zip -q -r /artifacts/target/vendor-package-v1.1.1.zip .`

As mentioned in the composer documentation the zip file needs a composer.json in it's root. A Package like for example symfony/console has a target-dir set in it's composer.json - so the above command changed to:

`cd vendor/package/composer/target-dir && zip -q -r /artifacts/target/vendor-package-v1.1.1.zip .`

to have a composer.json in it's root. So far the explanation on my steps.

A `composer.phar install` works fine now - but in the installed vendor packages the paths seems to be wrongly extracted. Not all but most of the packages are installed in a `vendor/package/package` path - for example symfony/polyfill-mbstring should be installed in 
`vendors/symfony/polyfill-mbstring` - but it's installed in 
`vendors/symfony/polyfill-mbstring/polyfill-mbstring` - the package name is double and composer doesn't seem to double this path in it's autoloader config as I'm getting the following error:

`PHP Warning:  require(/project/vendor/symfony/polyfill-mbstring/bootstrap.php): failed to open stream: No such file or directory in /project/vendor/composer/autoload_real.php on line 70`

My `composer.json`:

```json
{
  "name": "foo",
  "description": "bar",
  "config": {
    "bin-dir" : "bin",
    "vendor-dir": "project/vendor"
  },
  "minimum-stability": "dev",
  "prefer-stable": true,
  "repositories": [
    {
      "type": "artifact",
      "url": "artifacts/"
    },
    {
      "packagist.org": false
    }
  ],
  "require": {
    "symfony/filesystem": "2.6.13",
    "symfony/console": "2.6.13",
    "alcaeus/liquibase" : "3.0.2",
    "phing/phing": "2.15.2"
  },
  "require-dev": {
    "codeception/codeception": "^2.1",
    "site5/phantoman": "^1.1",
    "jakoch/phantomjs-installer": "^2.1"
  },
  "scripts": {
    ....
  }
}

```

I'm expecting - as composer - to find the package in the path vendors/symfony/polyfill-mbstring and not in vendors/symfony/polyfill-mbstring/polyfill-mbstring.
If I double click the artifact symfony-polyfill-mbstring-1.3.0.zip in finder (I'm on macOS) the archive is extracted into symfony-polyfill-mbstring-1.3.0/ path.

Now the master question - what went wrong? What is the best way to create and handle artifacts?

Thanks for any hints :-)

p.s. Just for info - same happens if I use the composer archive command to create the artifacts.

I just tried `composer archive symfony/polyfill-mbstring 1.3.0 --format=zip` and if run `composer install` afterwards the package ist also wrongly installed into
`vendors/symfony/polyfill-mbstring/polyfill-mbstring`
instead of
`vendors/symfony/polyfill-mbstring`

**Comment by Seldaek** [comment]
I don't quite see why this would happen sorry.. The archive created seems just fine to me, so I can't imagine why you'd have just that one package installed wrongly. Maybe try to run an install with `--no-plugins` to make sure that no plugin is messing up the install path.

**Comment by crowincage** [comment]
hej thanks for answering.
At the end it works as supposed. I'm not quite sure what this behaviour generated. Maybe do the archiving in osx console and composer install in VM. I'll try to regenerate this behaviour.

**Comment by Seldaek** [comment]
Auto-closing this as it's marked as support request and has not received any update in a long time.
