### ISSUE TITLE
Loosing the ability to debug in 1.3

### ISSUE THREAD

**Issue by theofidry** [composer/composer#6176]
I have a project where I have composer and a composer plugin installed as dev dependencies. I'm executing a composer command to debug the plugin. When using Composer 1.1.3, I could easily debug the plugin with xdebug by using breakpoints, it however no longer works as of Composer 1.3.2. Any idea?

**Comment by xabbuh** [comment]
Did you see that you can define the `COMPOSER_ALLOW_XDEBUG` environment var to disable the start of a new Composer process with Xdebug disabled?

**Comment by theofidry** [comment]
Ah right it's true that xdebug is disabled now. Sorry completely forgot about that!
