### ISSUE TITLE
Can't switch back from replacement project to original

### ISSUE THREAD

**Issue by fredemmott** [composer/composer#6182]
facebook/hack-codegen was previously archived. I put up a package with 'replaces': "facebook/hack-codegen' at fredemmott/hack-codegen.

facebook/hack-codegen is now alive again, the preferred thing to install, and I'm unable to make the fredemmott/hack-codegen public again.

Projects should be able to switch back to facebook/hack-codegen, but this is not supported.

Full repro here: https://gist.github.com/fredemmott/9ed22e965e29fc613b272e3ad2234272

My `composer.json`:

```json
{
    "require": {
        "fredemmott/hack-codegen": "^1.1"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
```

When I run this command:

```
composer require facebook/hack-codegen:2.1.0
```

I get the following output:

```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package fredemmott/hack-codegen is abandoned, you should avoid using it. Use facebook/hack-codegen instead.
Writing lock file
Generating autoload files
```

.... and no change to installed packages

And I expected this to happen:

facebook/hack-codegen 2.1.0 or above to be installed.

The only way this seems to be possible is to remove fredemmott/hack-codegen from composer.json, run composer update, then re-run the composer require command.

**Comment by alcohol** [comment]
This is because the replace does not work both ways and with the package still installed Composer does not really know how to resolve it.

You should first remove the currently installed package and then require the new (original) package.

**Comment by Seldaek** [comment]
Yup I'm afraid this will require a two step migration for users, you could have it as:

```
composer remove fredemmott/hack-codegen
composer require facebook/hack-codegen
```
