### ISSUE TITLE
Add --allow-root option

### ISSUE THREAD

**Issue by nicodmf** [composer/composer#6183]
As bower permit it, and because CI and docker containers are more suitable with a the root user, it seems to me better to have a allow root option.

Maybe a ticket exists, but my search give me many pages and the first and second doesn't mention any such option.

When I run this command:

```
...composer install
```

I get the following output:

```
...Do not run Composer as root/super user! See https://getcomposer.org/root for details
```

And I expected this to happen:

A normal process

**Comment by alcohol** [comment]
https://getcomposer.org/doc/03-cli.md#composer-allow-superuser

**Comment by henrypenny** [comment]
For example (on linux):
`$ export COMPOSER_ALLOW_SUPERUSER=1; composer show;`

**Comment by RScottLewis** [comment]
That worked. Thank you!

**Comment by mayankpandav** [comment]
sudo chown -R $USER $HOME/.composer

**Comment by JWPapi** [comment]
The last one is the right solution, there is a reason why there is a warning.

**Comment by emmanuelkafuihayibor** [comment]
Thanks so much

**Comment by judgej** [comment]
You can also do this in a bash shell:

   $ COMPOSER_ALLOW_SUPERUSER=1 composer show

There is no need to make the variable global in your shell or exported - it is only set for the `composer` process then thrown away. This can help to keep the environment clean.

**Comment by maherelgamil** [comment]
Run the following line directly from your server:

```bash
export COMPOSER_ALLOW_SUPERUSER=1;
```

or Add it to your bash script

**Comment by shawn-thesignchef** [comment]
You can also just:

```bash
yes | composer show
```
