### ISSUE TITLE
Composer stores Credentials in remote URL

### ISSUE THREAD

**Issue by leonex-cs1** [composer/composer#6186]
In our company we use Satis for private Git repositories. The repositories are secured by HTTPS.

Now, when I install a package with Composer, there's always added a remote with the URL `https://username:password@git.example.com/path/to/repo.git`, although I have already defined `store-auths` to `false`.

Is there no way to force Composer to use the interactive mode?

**Comment by alcohol** [comment]
Missing some useful information, such as your composer.json, and your Composer version.

**Comment by stof** [comment]
See https://github.com/composer/composer/pull/3608

**Comment by leonex-cs1** [comment]
You are right @stof #3608 targets the same problem that I have. Isn't this a huge security issue? Composer stores credentials on file system without telling the user about that (I was just asked for username/password) or is Git responsible for that?

**Comment by Seldaek** [comment]
Closing as duplicate of #3608
