### ISSUE TITLE
composer.lock encoding issue

### ISSUE THREAD

**Issue by Jelle-S** [composer/composer#6191]
I'm running composer (`Composer version 1.3.2 2017-01-27 18:23:41`) on Ubuntu 16.04 LTS.

My composer.lock contains some 'exotic' names with non-standard characters, but composer does something weird with them where it doesn't encode them properly or something. For example `Antoine Beaupré` is encoded as `Antoine BeauprÃ©`. Any ideas what the problem might be?

**Comment by staabm** [comment]
which php version? maybe related to php default charset http://php.net/manual/en/ini.core.php#ini.default-charset ?

**Comment by Jelle-S** [comment]
Yeah I checked that, but it seems to be fine to me?
```
; PHP's default character set is set to UTF-8.
; http://php.net/default-charset
default_charset = "UTF-8"
```
```bash
$ php -v
PHP 5.6.24 (cli) (built: Aug  1 2016 16:08:00) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
```

**Comment by stof** [comment]
Are you sure that your editor opens the file as UTF-8 ?

**Comment by Jelle-S** [comment]
Yeah, it shows up in all editors and with `git diff` as well.

**Comment by alcohol** [comment]
> but composer does something weird with them where it doesn't encode them properly or something. For example Antoine Beaupré is encoded as Antoine BeauprÃ©.

Where? When? What? Missing all the relevant and important information.

**Comment by Jelle-S** [comment]
- Where? See the title, in composer.lock
- When? Every time composer.lock is updated by composer (so on `composer require namespace/package`, `composer update`, ...)
- What? Any 'special' character like é, à, ç, ñ, ... is replaced by jibberish. For example Antoine Beaupré is encoded as Antoine BeauprÃ©.

Thought the title and description were pretty clear.

**Comment by agwidarsito** [comment]
You've definitely set the charset for the PHP config running in the
console? On ubuntu systems for example it's common to have two PHP configs:
one for CLI access and one for the web server.

**Comment by alcohol** [comment]
@Jelle-S not really, I still don't know in what terminal you were viewing this, or what editor, or what your locale was set to. Nor have you shared the actual composer.json file anywhere. So at the moment I have absolutely nothing reproducible to work with.

**Comment by agwidarsito** [comment]
I'm happy to try and reproduce it on my end of you can share the
composer.json file?

**Comment by Jelle-S** [comment]
Upgrading php to 5.6.30 solved it for me? Thx to everyone trying to help.
