### ISSUE TITLE
Dependency not updating after changing Satis location and/or branch alias

### ISSUE THREAD

**Issue by codedmonkey** [composer/composer#6194]
A private dependency in my projects is not updating after I changed the location of Satis and moved the dependency's alias between branches.

My project's `composer.json` contains the following reference to Satis:

```json

  "repositories": [
    { "type": "composer", "url": "https://satis.example.com" }
  ],

```

The dependency's branch alias was moved after I merged my changes from a `feature/symfony` branch to the `develop` branch (and deleted the old branch), which looks like this now:

```json

  "extra": {
    "branch-alias": {
      "dev-develop": "2.1.x-dev"
    }
  }

```

Unfortunately, when I run `composer update` from one of my projects, it doesn't recognize the fact that the alias moved at all, every time I get the response `Nothing to install or update` although it references an old version in `composer.lock`:

```json

        {
            "name": "codedmonkey/core",
            "version": "dev-feature/symfony",
            "source": {
                "type": "git",
                "url": "https://server.example.com/git/core",
                "reference": "136a3176b9954859b8a701367d9e7a3a5696326e"
            },
            "require": {
                ...
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-feature/symfony": "2.1.x-dev"
                }
            },
            "autoload": {
                ...
            },
            "time": "2017-02-13 15:43:28"
        },

```

Finally, I don't think Satis has anything to do with this problem, the generated metadata in Satis doesn't have a reference to the old branch anymore (since it was removed), this is what it looks like:

```json

        {
            "name": "codedmonkey/core",
            "version": "dev-feature/symfony",
            "source": {
                "type": "git",
                "url": "https://server.example.com/git/core",
                "reference": "136a3176b9954859b8a701367d9e7a3a5696326e"
            },
            "require": {
                ...
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-feature/symfony": "2.1.x-dev"
                }
            },
            "autoload": {
                ...
            },
            "time": "2017-02-13 15:43:28"
        },

```

Clearing composer's cache didn't help, nor did removing the project's `composer.lock`, I fixed the issue by deleting the `vendor` directory from the project.

**Comment by alcohol** [comment]
Please come back when you have a simple reproducible scenario. It looks like you just ran into a weird scenario where composer was unable to figure out what you wanted because you moved stuff around without actually changing versions. Removing `vendor` is often the best solution when you make such mistakes.

**Comment by codedmonkey** [comment]
Meh, don't feel like every coming back.
