### ISSUE TITLE
Composer invalidates cached sudo credentials

### ISSUE THREAD

**Issue by jmooring** [composer/composer#6195]
Composer invalidates cached sudo credentials, as if "sudo -k" were called. Example:
```
user@host~$ echo "I am a test file." > delete.me
user@host~$ chmod 600 delete.me
user@host~$ sudo chown root:root delete.me
[sudo] password for user:
user@host~$ cat delete.me
cat: delete.me: Permission denied
user@host~$ sudo cat delete.me
I am a test file.
user@host~$ composer -V
Composer version 1.3.2 2017-01-27 18:23:41
user@host~$ sudo cat delete.me
[sudo] password for user:
```
My cached sudo credentials were reset after running `composer -V`. Why is this a problem? We've got a script that does...
```
sudo command_1
command_2
command_3
composer foo
sudo command_4
command_5
```
The user is prompted for sudo credentials when launching the script, and expects the script to run to completion without further interaction. Instead, upon returning to his or her desk the user finds that the script is paused, waiting for them to enter their credentials again. And they might not notice the problem if passwd_timeout in /etc/sudoers is relatively short.

Output of `composer diagnose`:

`
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
`

**Comment by alcohol** [comment]
Because running composer as root user is bad.

If for some reason you feel like you have no other choice, https://getcomposer.org/doc/03-cli.md#composer-allow-superuser

**Comment by jmooring** [comment]
Well, actually, we're not running it as root. We're running the other commands as root. And it took way too long to track this down. Clobbering my sudo credentials without warning me just isn't nice.

And yes, I found the environment variable you referenced. So we're doing this instead:
```
sudo command_1
command_2
command_3
export COMPOSER_ALLOW_SUPERUSER=1
composer foo
export COMPOSER_ALLOW_SUPERUSER=0 
sudo command_4
command_5
```
Also, seems kinds of silly to clobber my sudo credentials when simply querying for the version.

**Comment by stof** [comment]
@jmooring but due to the cached credentials, any script called by composer would be allow to get sudo permissions without you noticing it (as it won't ask you for credentials again)

**Comment by alcohol** [comment]
@jmooring you can also run it as

```
sudo command_1
command_2
command_3
COMPOSER_ALLOW_SUPERUSER=1 composer foo
command_4
command_5
```

Whether or not you find it silly is not relevant to the issue. It is a security concern which we mitigate on purpose, since more often than not, users simply are not aware of what they are doing. There is an environment flag available for those that need it. Lets not waste more words on this pointless discussion.
