### ISSUE TITLE
Custom scripts slashes conflict in *nix and Windows 

### ISSUE THREAD

**Issue by TomasVotruba** [composer/composer#6197]
This only works in *nix:

```json
{
    "scripts": {
        "tests": "vendor/bin/phpunit src/Directory"
    }
}
```

And this only works in Windows:

```json
{
    "scripts": {
        "tests": "vendor\\bin\\phpunit src\\Directory"
    }
}
```

How to make it pass in both?

**Comment by alcohol** [comment]
@curry684 eh, is this true? I thought windows didn't really have a problem with those slashes.

**Comment by curry684** [comment]
PHP patches it all away internally invisibly (it normalizes `[/\]` to `DIRECTORY_SEPARATOR` on every platform) so it shouldn't pose any problems in PHP itself. Not really sure how the script handling works though, if it delegates to a local shell or a proxy script it could screw up badly and we would need to fix on our end.

**Comment by alcohol** [comment]
@TomasVotruba afaik, it should work just fine if you use `"phpunit src/Directory"` (don't need full path since Composer will figure it out for you).

**Comment by TomasVotruba** [comment]
@curry684 Is there a test for that passing on AppVeyor I could see?

@alcohol I will try it. Is this in docs to be found?

**Comment by curry684** [comment]
@TomasVotruba highly doubt it, I don't think there are meaningful compatibility tests on the scripts functionality.

**Comment by TomasVotruba** [comment]
@alcohol If I use

```
phpunit src/Directory
```

How to differ between global phpunit.phar and local composer phpunit package?

**Comment by curry684** [comment]
It *should* prefer the local one automatically and logically. If not by all means file a bug as it would be wrong.

If you want to bypass a local phpunit install just don't require it.

**Comment by TomasVotruba** [comment]
This *logic* could easily fail. If I run this on Travis with PHPUnit 5.x and my code requires PHPUnit 6.0+

I'd personally prefer using classic path instead of this magic.

```bash
vendor/bin/phpunit
```

**Comment by alcohol** [comment]
Pretty sure this should just work, but maybe @Seldaek can confirm?

**Comment by stof** [comment]
There is no magic. The vendor/bin directory is just prepended as the first entry in the PATH when executing scripts. So any locally required executable wins when the system resolves the executable, thanks to the meaning of the PATH in all OS.

Normalizing paths inside the executed command *would be* magic on the other hand, as it means that Composer would magically rewrite your command before executing it (which requires understanding which parts need to be rewritten btw, which requires understanding what the command does)

**Comment by TomasVotruba** [comment]
That's why I asked, where is this documented. To explain other people?

**Comment by alcohol** [comment]
https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands

**Comment by TomasVotruba** [comment]
@alcohol Thank you!

It's kinda hidden though. I'd suggest adding *nix note there, because"dependencies are easily accessible" is not really the reasons.

What do you think?

Just curious, could you link me to the code and line where is this managed?

**Comment by alcohol** [comment]
https://github.com/composer/composer/blob/eb5495b8e40811fc637e64bf0971a2e2349400ad/src/Composer/EventDispatcher/EventDispatcher.php#L148-L161

**Comment by robfrawley** [comment]
There is nothing `*nix` specific, so why would it mention that class of OS's in the documentation note? I think the wording is fairly concise while being expressive enough to deliver the intended message. Making "dependencies [...] easily accessible" is _exactly_ what is being done here, as well.

**Comment by TomasVotruba** [comment]
@robfrawley Why not? It fixed our issue with OS paths.

**Comment by TomasVotruba** [comment]
@alcohol Thank you!
