### ISSUE TITLE
private repositories  VS packages.org repositories ？

### ISSUE THREAD

**Issue by xuanskyer** [composer/composer#6201]
when the same package name both in private repositories and packages.org repositories. which will be used ?

ex:

I have package name：` one/piece` both in private repositories and packages.org repositories.（private repositories using satis deployed）

then,
My project `composer.json`:

```json
"repositories": [
        { "type": "composer", "url": "http://packages.myprivate.com/" }
],
"require": {
        "one/piece": "dev-master"
    }
```

afeter ` composer update ` , I found that `one/piece` came from   packages.org repositories.

why ?

I hope private package is More priority. how can I do ?

**Comment by stof** [comment]
The repository order in the config file defines the priority of repositories when resolving packages.
And the definition of packagist.org registered automatically by Composer is always placed at the end of the list

**Comment by stof** [comment]
and when you have repositories defined in your ``$COMPOSER_HOME/config.json`` file, they are placed after the project-level repositories (but before the default composer repositories)

**Comment by curry684** [comment]
If the Packagist version is being used your Satis either isn't working correctly, or the stability requirements are messing you up. Does it work if you [disable Packagist](https://getcomposer.org/doc/05-repositories.md#disabling-packagist-org)?

**Comment by xuanskyer** [comment]
@stof 
so, about priority , it means : project setting > $COMPOSER_HOME/config.json setting > the default composer repositories setting ?

**Comment by xuanskyer** [comment]
@curry684 
thanks! I got it. 
but it's not suitable for my projects. because some packages in my projects still using packagist.org
so ~
