### ISSUE TITLE
Problem resolving lowest versions

### ISSUE THREAD

**Issue by core23** [composer/composer#6207]
I got a strange problem, when calling running composer on clean project with the follwing `composer.json` file:

```json
{
  "require": {
    "friendsofphp/php-cs-fixer": "^2.0",
    "matthiasnoback/symfony-dependency-injection-test": "^1.1",
    "phpunit/phpunit": "^5.7",
    "sonata-project/admin-bundle": "^3.1"
  }
}

```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer update --prefer-lowest
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpunit/phpunit 5.7.0 requires sebastian/exporter ~2.0 -> satisfiable by sebastian/exporter[2.0.0].
    - phpunit/phpunit 5.7.1 requires sebastian/exporter ~2.0 -> satisfiable by sebastian/exporter[2.0.0].
    - phpunit/phpunit 5.7.10 requires sebastian/exporter ~2.0 -> satisfiable by sebastian/exporter[2.0.0].
    - phpunit/phpunit 5.7.11 requires sebastian/exporter ~2.0 -> satisfiable by sebastian/exporter[2.0.0].
    - phpunit/phpunit 5.7.12 requires sebastian/exporter ~2.0 -> satisfiable by sebastian/exporter[2.0.0].
    - phpunit/phpunit 5.7.13 requires sebastian/exporter ~2.0 -> satisfiable by sebastian/exporter[2.0.0].
    - phpunit/phpunit 5.7.14 requires sebastian/exporter ~2.0 -> satisfiable by sebastian/exporter[2.0.0].
    - phpunit/phpunit 5.7.2 requires sebastian/exporter ~2.0 -> satisfiable by sebastian/exporter[2.0.0].
    - phpunit/phpunit 5.7.3 requires sebastian/exporter ~2.0 -> satisfiable by sebastian/exporter[2.0.0].
    - phpunit/phpunit 5.7.4 requires sebastian/exporter ~2.0 -> satisfiable by sebastian/exporter[2.0.0].
    - phpunit/phpunit 5.7.5 requires sebastian/exporter ~2.0 -> satisfiable by sebastian/exporter[2.0.0].
    - phpunit/phpunit 5.7.6 requires sebastian/exporter ~2.0 -> satisfiable by sebastian/exporter[2.0.0].
    - phpunit/phpunit 5.7.7 requires sebastian/exporter ~2.0 -> satisfiable by sebastian/exporter[2.0.0].
    - phpunit/phpunit 5.7.8 requires sebastian/exporter ~2.0 -> satisfiable by sebastian/exporter[2.0.0].
    - phpunit/phpunit 5.7.9 requires sebastian/exporter ~2.0 -> satisfiable by sebastian/exporter[2.0.0].
    - Conclusion: don't install sebastian/exporter 2.0.0
    - Installation request for phpunit/phpunit ^5.7 -> satisfiable by phpunit/phpunit[5.7.0, 5.7.1, 5.7.10, 5.7.11, 5.7.12, 5.7.13, 5.7.14, 5.7.2, 5.7.3, 5.7.4, 5.7.5, 5.7.6, 5.7.7, 5.7.8, 5.7.9].

```

I don't get why the `sebastian/exporter` 2.0.0 dependency couldn't be loaded, because only two libs use this dependency (`matthiasnoback/symfony-dependency-injection-test` and `phpunit/phpunit`).

Curiously when I remove any dependency, composer will update my project.

**Comment by alcohol** [comment]
@naderman might be able to offer some insight into this.

I think if you have not ran a normal install yet, the solver might get stuck on the fact that `matthiasnoback/symfony-dependency-injection-test` has `^1.0` (full constraint is `^1.0|^2.0`) as the lowest boundary for `sebastian/exporter`, while `phpunit/phpunit` has `^2.0`.

If you first run install, and then run `update --prefer-lowest` you will see that it keeps `sebastian/exporter` at version `2.0.0`.

**Comment by core23** [comment]
Maybe this is related to https://github.com/composer/composer/issues/6188?

**Comment by core23** [comment]
> If you first run install, and then run update --prefer-lowest you will see that it keeps sebastian/exporter at version 2.0.0.

**Comment by core23** [comment]
@Seldaek You added the 2.0 milestone. So I can't expect a fix in the near future?

**Comment by Seldaek** [comment]
I mostly put it in that milestone because there's a set of solver-related issues we'll have to look at after 2.0 refactorings are done. I can't promise when that will be, but hopefully not too long.

**Comment by naderman** [comment]
Should be fixed with https://github.com/composer/composer/pull/7946 - please verify if you can.

**Comment by naderman** [comment]
You can use a current composer snapshot to test this `composer self-update --snapshot`.

I'll close this because I think it was fixed. Please comment/reopen if this is still a problem.
