### ISSUE TITLE
[ErrorException]   file_get_contents([...]spdx-licenses.json): failed to open stream: No such file

### ISSUE THREAD

**Issue by strarsis** [composer/composer#6209]
The composer.json for reproducing this issue/which is affected by this issue 
has to be valid JSON and contain a non-empty license field:

```json
{
    "name": "test/test",
    "license": "MIT",
    "description": "Test",
    "require": {}
}

````

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
```

When I run this command:

```
composer validate
```

I get the following output:

```
[ErrorException]
  file_get_contents(/usr/share/php/Composer/../../data/Composer/res/spdx-licenses.json): failed to open stream: No such file or directory


validate [--no-check-all] [--no-check-lock] [--no-check-publish] [-A|--with-dependencies] [--strict] [--] [<file>]
```

And I expected this to happen:
Valid result (either the composer.json is valid or valid with warnings or invalid including details).

**Comment by alcohol** [comment]
I don't know how you installed Composer, but judging from the error, it is something custom and not the recommended way (simple phar file). User error, not composer error.
