### ISSUE TITLE
Installer corrupt

### ISSUE THREAD

**Issue by VicTran** [composer/composer#6211]
I use mac os sierra then use mamp, php version: 7.1.1, which , which php:
/Applications/MAMP/bin/php/php7.1.1/bin/php
I try the command line installation of Composer like advised on https://getcomposer.org/download/

 sudo php -r "if (hash_file('SHA384', 'composer-setup.php') === '55d6ead61b29c7bdee5cccfb50076874187bd9f21f65d8991d46ec5cc90518f447387fb9f76ebae1fbbacf329e583e30') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

Installer corrupt

Please help me .

**Comment by Seldaek** [comment]
Auto-closing this as it's marked as support request and has not received any update in a long time.
