### ISSUE TITLE
Install: getaddrinfo failed: System error (2x try)

### ISSUE THREAD

**Issue by strarsis** [composer/composer#6212]
When installing composer according to [official installation instruction](https://getcomposer.org/download/),

`php composer-setup.php` fails with 
````
All settings correct for using Composer
Downloading...
The "https://getcomposer.org/download/1.3.2/composer.phar.sig" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: System error
failed to open stream: php_network_getaddresses: getaddrinfo failed: System error
Retrying...

Composer (version 1.3.2) successfully installed to: /home/build/composer.phar
Use it: php composer.phar
````
This happens each time I run the command above again, it has to try twice.

**Comment by stof** [comment]
``php_network_getaddresses: getaddrinfo failed: System error`` means that you had a DNS error on your system (``getaddrinfo`` is about resolving DNS)

**Comment by stof** [comment]
if it works the second time, I suspec that it has to do with a timing issue. Maybe the DNS lookup is too slow when it goes to a DNS server. The second try may be resolving the DNS from the system cache instead, which is faster.

**Comment by strarsis** [comment]
This is directly related to this previous issue https://github.com/composer/composer/issues/6210.
The reason why composer failed installing from GitHub repository despite composer.json and semver tag correctly in place is that the same error occurred (php_network_getaddresses: getaddrinfo failed: System error) in [src/Composer/Repository/Vcs/GitHubDriver.php, line 335](https://github.com/composer/composer/blob/master/src/Composer/Repository/Vcs/GitHubDriver.php#L335).
The code for this getaddrinfo error is 0 and not handled by the switch, just rethrown, further down in [src/Composer/Repository/VcsRepository.php, line 198](https://github.com/composer/composer/blob/master/src/Composer/Repository/VcsRepository.php#L198) the Exception is handled only so far that it is logged that in given branch no composer was file found (`Skipped branch master, no composer file was found`) - but not the causing issue (failed to resolve the hostname).

**Comment by strarsis** [comment]
It turns out that there was a very deep issue with the Ubuntu system and the system has to be reset back.
Resolving hostnames by DNS in PHP when being performed fast enough + with the stream context option that composer uses trigger this specific error.
For further debugging I replaced the hostname in URLs with their resolved IP addresses (and added Host field + peer_name) and the issue also went away, it is clearly the resolving using DNS.
