### ISSUE TITLE
Programmer are the worse to explain how to use it, the worse

### ISSUE THREAD

**Issue by onigetoc** [composer/composer#6214]
Programmer are the worse to explain how to use it, the worse.
It took years to Github to get decent help.

I do have a shared hosting and can't use composer, now 90% of Github scripts are useless to me.
I have a slow computer full of software, if i understand now i should install php on my slow computer. All attent in the past to install PHP or any server on my computer always crash after some days or week.

I tryed to use Composer-Setup.exe
in the help nothing talk about how to get or install the php.exe file it's looking for.

It's say, run command line. Where, how to open this command like in Windows, nothing

We do not work all in big compagny with lot of coworker to help us. 

Why nobody think about doing a sofware who to command line. like i said, Github took year to finally create a good software, in the begining i give up because command line never worked.

Some time, you will find a blogger who will explain better how to use this because the people who create these kind of program are advanced programer but they suck at explaining how it work.

I hate Node and Composer, it's slower to use this instead of all files from a Github project or just downloading the updated file, it take 30 secondes, but reinstalling or updating from Composer or Node take minutes. We have to search for all command line we forgot days ago because some use it only from time to time.

Like i said, no body at composer will take the time to do this kind of video.
"We do not have time for lesser stupid programer"
https://www.youtube.com/watch?v=ZocYVPP3nQY
and it's show interminable things to do just to get it work.
10 min video, how this make things faster?

Update:
Like i said, i found Wamp and i get this notice: can install because it miss VCRENTIME140.dll
it never work, i knew before one hour of losing my time.

**Comment by alcohol** [comment]
Using Composer is opt-in. You do not have to use it :-). Enjoy your day.

**Comment by Caroga** [comment]
Maybe fix your WAMP issue first, before running any other software. Your WAMP installation is blocking ANY PHP related program. 
http://stackoverflow.com/a/35131212/1472440

**Comment by onigetoc** [comment]
I did fix WAMP.
I'm writed myself a 100 lines of codes php parser (Returning json)
http://jsfiddle.net/onigetoc/d2ntn6x2/

**Comment by rquadling** [comment]
I'd sort of like to know how anyone would have the time to do all the research needed to keep a stack of libraries uptodate with bugs and features without using a package management tool.
