### ISSUE TITLE
How to self-update globally installed composer?

### ISSUE THREAD

**Issue by nimasdj** [composer/composer#6215]
Hello,

I installed my composer globally and it works fine but when I want to self-update it as root:
```$ composer self-update``` 
I get error
```The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly```
What should I do?

Thanks,

**Comment by alcohol** [comment]
Weird, normally root has `HOME` set. Your environment seems broken. What operating system are you running?

**Comment by mwgamble** [comment]
@nimasdj may have a particularly strict `sudo` configuration, or they may be running the update using an automated tool that results in it not being set.

**Comment by Seldaek** [comment]
Auto-closing this as it's marked as support request and has not received any update in a long time.
