### ISSUE TITLE
Cannot Run Command "composer" in CMD

### ISSUE THREAD

**Issue by adibarly** [composer/composer#6216]
Hy Guys,
I hve done install composer in Windows 10. but i cant run command 'composer' in CMD.

i try run command 'composer' in directory C:\ProgramData\ComposerSetup\bin . Its OK . running success.

but i try in cmd c:\User\Username . command not running.

this is screenshoot https://scontent-sin6-1.xx.fbcdn.net/v/t1.0-9/17021586_10208661762927422_8450395413326047949_n.jpg?oh=062029cfb931e757a5364df4800e95de&oe=59267DBE

someone help me . pls

**Comment by rquadling** [comment]
Add C:\ProgramData\ComposerSetup\bin to your path or set your COMPOSER_HOME environment variable.

http://stackoverflow.com/questions/25549177/change-composer-global-path-windows

GIYF
