### ISSUE TITLE
Using global package class in local package without being local dependency

### ISSUE THREAD

**Issue by rudiedirkx** [composer/composer#6217]
I've created a global package/plugin that extends `autoload.php` in any project on your computer. It adds a bin you can access anywhere. The bin knows where it is, and it requires Composer and Console so it can use those global classes in the local package.

`autoload.php` runs outside the global package/plugin context. It only knows the local package. The local package doesn't require the plugin, not even `--dev`. How can `autoload.php` in that package use the global package's classes? Does the Composer autoloader register some global Composer helpers to access global classes?

Specifically, I'm talking about [localoader](https://packagist.org/packages/rdx/composer-localoader-plugin):

* the global bin [`locaload`](https://github.com/rudiedirkx/composer-localoader-plugin/blob/master/locaload) uses Localoader and Console and Composer classes
* the local [`autoload.php`](https://github.com/rudiedirkx/composer-localoader-plugin/blob/master/autoload-dev.php) can't use anything global

It's a (global) dev package, so I don't care about the tiny autoloader overhead.

**Comment by Seldaek** [comment]
You should require the global autoload.php if you need classes from it.. There's really no other way.

**Comment by rudiedirkx** [comment]
How do I know where the global `autoload.php` lives? The local project doesn't know anything about global. The project's Composer autoloader has been inited, but nothing else. Do I just try a few common locations for `autoload.php` ?
