### ISSUE TITLE
pass the current known prefer-stable config value to findBestCandidate in the require and init command .

### ISSUE THREAD

**Issue by ryanaslett** [composer/composer#6219]
So, I manage packages.drupal.org, our way of bridging the drupal universe to the composer universe .  Also, I manage the drupalci infrastructure as well.

The story Im about to tell is such an unlikely edge case that If y'all wanna just 'close/wontfix' I wont be offended.

The issue Im running into is that I need to be able to have 'prefer-stable': false be respected when I do a composer require.

The reason I need this is a combination of a couple of things we're trying to do to bring drupal into the fold: Im mapping drupal's "one repository, many modules, with dependencies expressed on modules, not repos" data model to composer's "one repository, one package, dependencies are packages *and* repos" data model.

The other issue is that all of our testing and development is patch based, as we're not yet out of web 2.0 land.  

So, here's the problem:

When we test a "project" (which is a repository that contains multiple modules), we can usually `composer require drupal/projectname` and everything is fine. Except we *also* need to be able to detect changes to the composer.json itself so that people can test adding/removing new dependencies.  When we detect that a patch has modified the project's composer.json, we make a commit with the patch, make a new branch, and add that local git repo as a 'path' repository to the project, and then `composer require drupal/projectname` again to re-add the project with the new composer dependencies.

*sometimes*, when a project has a dependency on another module, that module *itself* has a dependency back to a 'submodule' of the project that we're testing.

So, an example is as follows:

Project A (`drupal/A`, contains 'module A, and module B',  has a require-dev on `drupal/C`.   Project C has a require on module B. Project/Module A on packages.drupal.org has all the real composer metadata.  Module B can also be found on packages.drupal.org, But `drupal/B` is just a metapackage that says "require project A:self.version"

Project A has a dev-2.x branch, as well as a 1.0.0-beta6 release. (and Project B therefore has the same versions)

When we patch Project A, and then `composer require drupal/A dev-temporary-branch AS dev-2.x` we then also parse that projects' require-dev, and require those to build the codebase to test.  In this case it says `composer require drupal/C`, which then has to bring in drupal/B. because drupal/C only requires drupal/B:*, when it tries to resolve which requirements it has, it finds 1.0.0-beta6 as the most stable, and cant install because we have the dev-2.x branch (which is what we're trying to test).

At this point you are probably wondering WTF did I just read. But in any case, I have a weird edge case where it'd be nice if findBestCandidate always got whatever setting was expressed in the config and didn't make assumptions about whether or not the end user ought to have stable or not.

Granted, Im not sure what assumption it makes when prefer-stable isn't set at all, so I would think this would only get passed if its explicitly set. (unless prefer-stable == true is the assumption throughout the codebase).

**Comment by curry684** [comment]
I think your use case makes sense, I'm not quite sure it's easy to fix due to complexities in the solver end of things.

**Comment by ryanaslett** [comment]
Would calls to `findbestCandidate` affect the solver in some way? It already takes in a 4th stability argument in other places, just not in InitCommand (https://github.com/composer/composer/blob/master/src/Composer/Command/InitCommand.php#L633).

Ideally the solver would behave the same if we said `composer require drupal/B:dev-2.x` or if we had `prefer-stable: false` and `composer require drupal/B:*`

**Comment by Seldaek** [comment]
@ryanaslett **if** I understood you correctly, then yeah I think it makes sense, and I think my fix is appropriate, but it'd be good if you can try it out and confirm. It's available in the latest snapshot (`composer self-update --snapshot`) and should now respect minimum-stability + prefer-stable. So by default it will pick stable versions still, but if you put a minimum-stability dev for example, it'll pick dev, unless you have prefer-stable true then it'll pick stable again.
