### ISSUE TITLE
Removing unused dirs from "vendor" directory

### ISSUE THREAD

**Issue by bkrukowski** [composer/composer#6223]
Let's imagine the following case: I'm owner of some composer repository. Repository has the following structure of directories:

* `src/`
* `tests/`

Directory `tests/` is useful only for this repository (root only). In my opinion would be great to have an option to remove automatically such directory from `vendor` when command `composer update` is being executed.

**Example:**

```json
{
    "name": "company/library",
    "excluded-dirs": ["tests"]
}
```

Current structure of directories in root repository:

```
src/
vendor/
    ...
    company/
        library/
            src/
            tests/
```

New structure:

```
src/
vendor/
    ...
    company/
        library/
            src/
```

**Benefits**

* IDE cannot suggest those classes
* I have 100% sure that nobody uses my classes written only for tests, so I can remove or change them without breaking backward compatibility.

**Comment by curry684** [comment]
> - IDE cannot suggest those classes
> - I have 100% sure that nobody uses my classes written only for tests, so I can remove or change them without breaking backward compatibility.

Your `autoload-dev` is only processed for the root package, so for all including packages the test classes are for all intents and purposes inaccessible, and won't autoload even if referenced.

**Comment by bkrukowski** [comment]
@curry684 Thank you for your response.

>Your `autoload-dev` is only processed for the root package

Yes, I know, but still IDE suggests useless classes. It is not a blocker, or big thing, but it could be useful. Maybe at least those directories could be removed when extra parameter is added to `composer update`, i.e. `composer update --remove-test-dirs`?

**Comment by alcohol** [comment]
`.gitattributes` + `export-ignore` works fine for tagged releases if you have `dist` installs.

**Comment by stof** [comment]
@alcohol even for dev versions, if you use dist installs for them too

**Comment by Seldaek** [comment]
Closing. See @alcohol's comment.
