### ISSUE TITLE
cakephp 3.4.2 requires lib-icu >=4.8

### ISSUE THREAD

**Issue by youneszd** [composer/composer#6226]
Hello i have this problem when i'm download cakePhp

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cakephp/cakephp 3.4.2 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - cakephp/cakephp 3.4.1 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - cakephp/cakephp 3.4.0 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - Installation request for cakephp/cakephp 3.4.* -> satisfiable by cakephp/cakephp[3.4.0, 3.4.1, 3.4.2].

**Comment by alcohol** [comment]
I suggest you take the time to read the information that is provided to you.

**Comment by youneszd** [comment]
i don't fin this lib-icu >=4.8  i'm search in google and i don't find any thing

**Comment by youneszd** [comment]
it's working in windows but is mac is still nut working for me
