### ISSUE TITLE
Dependency issue with replace?

### ISSUE THREAD

**Issue by Toflar** [composer/composer#6229]
My `composer.json`:

```json
{
    "require": {
        "symfony/symfony": "^3.2",
        "symfony/proxy-manager-bridge": "^3.2"
    }
}
```

I'm not really sure if this is a Composer issue or it's actually a Symfony one. The problem is that `symfony/proxy-manager-bridge` specifies the dependency on `ocramius/proxy-manager` (see https://github.com/symfony/proxy-manager-bridge/blob/master/composer.json#L21).
Now, my `composer.json` looks a bit awkward because if you already required `symfony/symfony` you wouldn't require `symfony/proxy-manager-bridge` again. But this is for illustration purposes. I actually noticed the behaviour when requiring something that **itself** requires `symfony/symfony`.

The problem is that `ocramius/proxy-manager` never gets installed unless I add it to my root requirements too. I'm not sure but I guess this is because `symfony/symfony` contains a

```json
"replace": {
        "symfony/proxy-manager-bridge": "self.version"
    },
```

So it actually replaces the `symfony/proxy-manager-bridge` but does not provide all of its dependencies. So I'd say this is due to Symfony but also at the same time I understand why Symfony uses the `replace` directive but cannot provide the `ocramius/proxy-manager` library.

It's just a very weird situation that if you require `example/project` that requires`symfony/symfony` you actually do get the `symfony/proxy-manager-bridge` but not its dependencies. And it's even more puzzling if you explicitly add `symfony/proxy-manager-bridge` again in your root `composer.json`, you still don't get the `ocramius/proxy-manager` :-D

Again, I think it's rather a Symfony issue but I have no clue how this could be resolved without having some special directives for Composer.

Also, if this is some sort of "known limitation" then maybe someone might find this issue when googling so it should be still worth writing it down here :-)

**Comment by alcohol** [comment]
Yeah replace has some odd behaviours, see #3754 also.

But your particular example seems to indicate an issue in the way Symfony uses replace for this particular library. Indeed, having `symfony/symfony` replace `symfony/proxy-manager-bridge` while not actually requiring the same dependencies seems like an issue or at least something that should be documented.

**Comment by alcohol** [comment]
You should report this on one of their repositories though in my opinion. This is not a Composer issue.
