### ISSUE TITLE
PEAR error: Undefined index: channel

### ISSUE THREAD

**Issue by m1ch3lp3r3z** [composer/composer#6231]
Hi, I'm getting an error when trying to update my libraries via composer, I have a pear repository included in my composer.json and I'm getting this warning:

```PEAR repository from http://pear.php.net could not be loaded. Undefined index: channel```

After that, the update continues but my pear.net packages are not found.

I have latest versions of both:
Composer version 1.3.2 2017-01-27 18:23:41
PEAR Version: 1.10.3
PHP 5.6.29 (cli) (built: Feb 13 2017 10:36:50)

Thanks

**Comment by m1ch3lp3r3z** [comment]
Nevermind, it worked now, I didn't change anything or did something I hadn't already, guessing something on PEAR XML, or maybe just me although I tested with several projects.

**Comment by avant1** [comment]
Take a look at #6193
It describes similar issue, and it was fixed in latest snapshot release.

**Comment by m1ch3lp3r3z** [comment]
Thanks @avant1, according to that thread it should be fixed, however I have the latest version of composer (1.3.2) and I'm still seeing the warning when I run the update.

**Comment by avant1** [comment]
Latest release version and snapshot release are not the same. 
Snapshot is current composer master build, and yesterday that fix presented in master branch, but not in latest release (1.3.2).

Now 1.3.3 has been released: https://github.com/composer/composer/releases/tag/1.3.3 so you can try it.

**Comment by m1ch3lp3r3z** [comment]
Sorry, good to know, the new version worked great!, thank you.
