### ISSUE TITLE
1.3.3 waits for input, ignoring --no-interaction flag

### ISSUE THREAD

**Issue by peterlozano** [composer/composer#6233]
My capistrano deployments have stoped working after the release of 1.3.3.

Composer install is waiting for input like this:

```
--> Updating parameters
- Installing twig/twig (v1.18.0):
````

it stops in every single dependency.

It ignores the --no-interaction flag

I have workaround it by setting capistrano to use composer 1.3.2.

**Comment by Seldaek** [comment]
Waiting for input? There is no waiting for input as far as I know? Or is capistrano treating `:` specially?

I just get stuff like this:

```
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing doctrine/inflector (v1.1.0): Loading from cache
```

So there is the `:` followed by whatever the installation is doing..

Can you provide any more details?

**Comment by statista** [comment]
We have the same issue. Which breaks our Jenkins deployments.

**Comment by peterlozano** [comment]
In my case, it doesn't print anything after the colon until I press enter. So basically, yes, it seems capistrano interprets the `:` as a 'waiting for input'.

A manual run of composer worked normally.

So not sure at this point if this is composer or capistrano's fault. But expect a few people to have their deployment systems broken in the next days.

1.3.3 Output:
```
- Installing twig/twig (v1.18.0): Loading from cache Extracting archive
````

1.3.2 Output:
```
  * - Installing twig/twig (v1.18.0)
  * Loading from cache
  * Extracting archive
```

**Comment by stof** [comment]
composer does not wait for input at this point. If Capistrano interprets a ``:`` as waiting for input, it is an issue to be reported to Capistrano. There are other valid use cases for `:` in the output than prompting.

**Comment by Seldaek** [comment]
I can't imagine we are the first to hit this though.. googling finds nothing. One aspect that might be triggering it is that we output `:` without newline following.. Until the rest is printed that is.

**Comment by peterlozano** [comment]
The fault seems to be of Capifony, a capistrano plugin to deploy symfony which is actually very old and abandone, but that many people (including me) are still using.

Code that waits for input is here: https://github.com/everzet/capifony/blob/55b5e5cb2e6860cb87b4370617c64ede822a59ee/lib/symfony2/symfony.rb#L209

I guess it is time for us to upgrade to Capistrano 3. So feel free to close this issue.

Unless this `:` with no new line may confuse other tools too.

Thanks for the response, btw.

**Comment by peterlozano** [comment]
For those using capifony who want to avoid this problem, add this to your app/config/deploy.rb

```
set :interactive_mode, false
```

**Comment by Seldaek** [comment]
OK thanks for the details. I'll add a note in the changelog.

**Comment by zelazowy** [comment]
Same problem here. 

Changing composer output format seems to be not that important comparing to capifony drawback. Maybe use `-` instead of `:`? Just something that won't break capifony deploys and give some time to upgrade to capistrano 3.

**Comment by Seldaek** [comment]
You can disable the interactive mode, no? Or keep using Composer 1.3.2 if you rather. I don't really want to go back and forth with the output format if there is an easy fix available.

**Comment by scuben** [comment]
This does not affect my deployments but a big plus for adding the solution directly into the first post!

**Comment by zelazowy** [comment]
I don't want to disable interactive mode because of parameters.
It seems that using specific version of Composer is the best option for now (well not the worst at least).

**Comment by hkdobrev** [comment]
I've just double checked our build and [Capistrano with Composer plugin](https://github.com/capistrano/composer) is not affected by this.

👍 for the quick resolution and handling this in the way it was handled for people who are or would be potentially affected.

**Comment by statista** [comment]
> set :interactive_mode, false
Works for us.

**Comment by peterlozano** [comment]
@Seldaek @stof I'd suggest to change the `:` for `...` which is how console commands usually deals with progress. I know of a human user that got confused today by the `:` thinking that composer was waiting for output.

**Comment by Seldaek** [comment]
But we usually print something very quickly after, so the window for confusion is pretty slim IMO? And ... takes more space, we're already running pretty long there for old-school terminal width, so I'd rather not.
