### ISSUE TITLE
I want to add arbitrary config entries (esp. repository) from the command line

### ISSUE THREAD

**Issue by axel-rutz** [composer/composer#6234]
What already works:

`php composer.phar config repositories.foo vcs https://github.com/xyz
`

It would be great to be able to add more complex repository entries (i.e. containing other keys) from the command line.

The use case is to overcome the limitation of having repository entries in subpackages, by providing a pre-packaged command.

**Comment by Seldaek** [comment]
Like what kind of more complex repo entry are you thinking about? Got a more detailed example of what you'd expect to do?

**Comment by axel-rutz** [comment]
Thanks for the quick reply! From the [drupal chosen module](http://cgit.drupalcode.org/chosen/tree/README.txt?h=8.x-2.x):

```
First, copy the following snippet into your project's composer.json file so
  the correct package is downloaded:

  "repositories": [
    {
      "type": "package",
      "package": {
        "name": "harvesthq/chosen",
        "version": "1.6.1",
        "type": "drupal-library",
        "dist": {
          "url": "https://github.com/harvesthq/chosen/releases/download/v1.6.1/chosen_v1.6.1.zip",
          "type": "zip"
        },
        "require": {
            "composer/installers": "^1.2.0"
        }
      }
    }
  ]

  Next, the following snippet must be added into your project's composer.json
  file so the javascript library is installed into the correct location:

  "extra": {
      "installer-paths": {
          "libraries/{$name}": ["type:drupal-library"]
      }
  }

  If there are already 'repositories' and/or 'extra' entries in the
  composer.json, merge these new entries with the already existing entries.

```

**Comment by stof** [comment]
Repositories of type `package` are a huge pain to handle (you have to specify everything manually, and take care of updates manually too). So I'm not sure writing a CLI syntax allowing to declare them is worth it (and it would be a huge pain given the number of configuration settings for a package).

I think the main issue here is that the drupal module tries to make you use composer to install a frontend package rather than a PHP library, and so this package is not available in the PHP package repositories (which is totally expected).

**Comment by axel-rutz** [comment]
I know it's not the perfect-world scenario, but there are lots of it, sigh...

Due to the simple structure of json even quite complex settings might be handled simply (though verbose) with something like this:
`
composer config repositories.type drupal-library ... repositories.dist.type zip
composer config "extra.installer-paths.libraries{\$name}" '["type:drupal-library"]'
`
 While typing, i realize that my intent is broader, modifying arbitrary config keys (will update title).

Of course this may be a _wontfix_ to keep composer simple and focused on the top 80% use cases.
Then it's up to some contrib solution to do the rest.

**Comment by Seldaek** [comment]
Yeah that's kinda borderline between useful and insane ;) I think I'd rather avoid adding this because it'll just promote such use cases which we would rather not promote really.

**Comment by PhilippeDirx** [comment]
To be honest, this can prove quite useful in scenario's like mine:
I have a private package (modular) based on Laravel.
By commands, I'd like to install modules for the package when deploying it in a new project.
This would require me adding repositories (package) to composer.json, which would be great if possible through command line.
Just my thoughts on the matter.

**Comment by axel-rutz** [comment]
So if someone knows or starts a command to alter json, dropping a link here is appreciated much!
