### ISSUE TITLE
Inconsistency in Commands when enabling apcu-autoloader

### ISSUE THREAD

**Issue by holtkamp** [composer/composer#6237]
The [documentation suggests](https://github.com/composer/composer/blob/a5ed32982d7f49c109c1a0d7775d240aef94589c/doc/articles/autoloader-optimization.md#optimization-level-2b-apcu-cache) to use ```apcu-autoloader``` to enable the APCu Autoloader using the config (and ```--apc``` when running command line... 😕 ).

However the DumpAutoloadCommand uses ```apcu``` for the InputOption AND configuration key:
https://github.com/composer/composer/blob/d8d0ee5870010253c98a7db4d27b07cd17bd6617/src/Composer/Command/DumpAutoloadCommand.php#L60

While other Commands use ```apcu-autoloader```, both for the InputOption AND configuration key:

- https://github.com/composer/composer/blob/1dcb2b5758f34e7e68b5a321deca72822774731a/src/Composer/Command/InstallCommand.php#L98
- https://github.com/composer/composer/blob/1dcb2b5758f34e7e68b5a321deca72822774731a/src/Composer/Command/UpdateCommand.php#L132

Might this be a mistake and should it have been used consistently as ```apcu-autoloader```?

@nicolas-grekas you submitted https://github.com/composer/composer/commit/6d4e60b9914e5514c49f4b19ee2b664c1d477605, was there a reason to use ```apcu``` only for the DumpAutoloadCommand?

**Comment by nicolas-grekas** [comment]
To me, that's consistent. See https://github.com/composer/composer/pull/5559 for some background about the decision.

**Comment by holtkamp** [comment]
MM, can't find anything about this difference in behaviour between the commands. 

My observation: using ```apcu-autoloader``` in the config section of ```composer.json``` will **not** be respected when running:

```composer dump-autoload```

The install and update commands **WILL** respect it. 

I think https://github.com/composer/composer/blob/d8d0ee5870010253c98a7db4d27b07cd17bd6617/src/Composer/Command/DumpAutoloadCommand.php#L60

should be (no change to documentation required):

```php
$apcu = $input->getOption('apcu') || $config->get('apcu-autoloader');
```

or even better / more consistent (change to documentation required):

```php
$apcu = $input->getOption('apcu-autoloader') || $config->get('apcu-autoloader');
```

**Comment by Seldaek** [comment]
The flag not having `-autoloader` in dump-autoload command is consistent with previous decisions. In the dump-autoload context, specifying -autoloader doesn't really bring a lot more info.

That said yeah the config key should be apcu-autoloader everywhere I agree :)

**Comment by holtkamp** [comment]
@Seldaek thanks for the swift confirmation 👍
