### ISSUE TITLE
composer.json failed validation after installing 1.4.0

### ISSUE THREAD

**Issue by symphoniezhao** [composer/composer#6242]
My `composer.json` has been working fine with composer 1.3.2 and earlier releases. Yesterday, after installing 1.4.0, it threw the following validation errors:

composerget:
     [exec] All settings correct for using Composer
     [exec] Downloading...
     [exec] 
     [exec] Composer (version 1.4.0) successfully installed to: ./composer.phar
     [exec] Use it: php composer.phar
     [exec] 
composer:
     [exec] 
     [exec]                                                                                                                                                                     
     [exec]   [Composer\Json\JsonValidationException]                                                                                                                           
     [exec]   "./composer.json" does not match the expected JSON schema:                                                                                                        
     [exec]    - repositories[0] : Must contain no more than 1 properties                                                                                                       
     [exec]    - repositories[0].url : String value found, but a boolean is required                                                                                            
     [exec]    - repositories[0].url : Does not have a value in the enumeration [false]                                                                                         
     [exec]    - repositories[0].package : The property package is required                                                                                                     
     [exec]    - repositories[0].type : Does not have a value in the enumeration ["package"]                                                                                    
     [exec]    - repositories[0].url : Invalid URL format                                                                                                                       
     [exec]    - repositories[0].type : Does not have a value in the enumeration ["vcs","github","git","gitlab","git-bitbucket","hg","hg-bitbucket","fossil","perforce","svn"]  
     [exec]    - repositories[0].type : Does not have a value in the enumeration ["path"]                                                                                       
     [exec]    - repositories[0].type : Does not have a value in the enumeration ["artifact"]                                                                                   
     [exec]    - repositories[0].type : Does not have a value in the enumeration ["pear"]                                                                                       
     [exec]    - repositories[0] : Failed to match exactly one schema                                                                                                           
     [exec]                                                                                                                                                                     
     [exec]

**Comment by Seldaek** [comment]
You need to share the "repositories" key of your composer.json for anyone to be able to help here, but it seems like probably you forgot a `https://` prefix in front of a URL and it is now validating that.

**Comment by Nek-** [comment]
And it's probably related to https://github.com/composer/composer/issues/6238

**Comment by symphoniezhao** [comment]
Thanks. These are very helpful. Our packagist url didn't have protocol prefix, which is only required since 1.4.0 I guess.
