### ISSUE TITLE
After update to 1.4 JsonValidationException block even help command

### ISSUE THREAD

**Issue by KrzysztofZalasa** [composer/composer#6243]
I have updated composer to version 1.4 and it even cannot display help etc. because of `Composer\Json\JsonValidationException`. Here is my full error message:

>  [Composer\Json\JsonValidationException]                                                                                                                           
>   "./composer.json" does not match the expected JSON schema:                                                                                                        
>    - repositories[0] : Must contain no more than 1 properties                                                                                                       
>    - repositories[0].url : String value found, but a boolean is required                                                                                            
>    - repositories[0].url : Does not have a value in the enumeration [false]                                                                                         
>    - repositories[0].package : The property package is required                                                                                                     
>    - repositories[0].type : Does not have a value in the enumeration ["package"]                                                                                    
>    - repositories[0].url : Invalid URL format                                                                                                                       
>    - repositories[0].type : Does not have a value in the enumeration ["vcs","github","git","gitlab","git-bitbucket","hg","hg-bitbucket","fossil","perforce","svn"]  
>    - repositories[0].type : Does not have a value in the enumeration ["path"]                                                                                       
>    - repositories[0].type : Does not have a value in the enumeration ["artifact"]                                                                                   
>    - repositories[0].type : Does not have a value in the enumeration ["pear"]                                                                                       
>    - repositories[0] : Failed to match exactly one schema  

It seams, that this is serious BC break in non major version update. My composer.json works fine on version 1.3, here is its content:
```
{
    "name": "xstream/my_name",
    "description": "My description",
    "require": {
        "guzzle/guzzle": "~3.8",
        "symfony/debug": "~2.6",
        "xstream/my-common": "^4.0"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.4"
    },
    "autoload": {
        "classmap": ["src/", "tests/"]
    },
    "repositories" : [
        {
            "type": "composer",
            "url": "http://satis.int.xstream.dk"
        }
    ],
    "config": {
        "secure-http": false
    }
}
```

In this situation I think it shall be fixed ASAP or it my hurt all peoples with internal satis.

**Comment by Seldaek** [comment]
I can't reproduce this here with that composer.json. Did you change the URL in the repository before pasting it here? Because it seems like that is what is invalid, but the one you pasted appears valid here.

**Comment by KrzysztofZalasa** [comment]
You're right, I have used composer.json from working setup. Once again file which works on 1.3 and  doesn't on 1.4

```
{
    "name": "xstream/my_name",
    "description": "My description",
    "require": {
        "guzzle/guzzle": "~3.8",
        "symfony/debug": "~2.6",
        "xstream/my-common": "^4.0"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.4"
    },
    "autoload": {
        "classmap": ["src/", "tests/"]
    },
    "repositories" : [
        {
            "type": "composer",
            "url": "satis.int.xstream.dk"
        }
    ],
    "config": {
        "secure-http": false
    }
}
```

**Comment by Seldaek** [comment]
Yeah, we now validate URLs and warn about invalid ones, and this one is missing an https:// or http:// scheme. 

I don't really understand how you managed to add the http:// before reporting the bug, but then did that without noticing that it fixed your "bug".. Anyway I hope it's all good now?

**Comment by KrzysztofZalasa** [comment]
In my company we have tens of projects where composer is used. Our common setup is that development version use always latest version of composer. All projects use internal satis for private libs.

After update to 1.4 composer.json files which works fine for 1.3 doesn't work. IMHO its BC break and it shall be fixed asap. I understand, that additional validation is introduced, but it means that it breaks BC without major release. So, you just break semver.

Please reopen this task. In described scenario, when http is omitted in configuration it shall display warning message until version 2.0 but for now it's not possible to even display help. It's serious issue.

**Comment by KrzysztofZalasa** [comment]
![composer](https://cloud.githubusercontent.com/assets/1415768/23788620/95ff9380-0577-11e7-8e3a-2bcb9d64a7f8.png)

**Comment by Seldaek** [comment]
1.4.1 is out which fixes this.

**Comment by KrzysztofZalasa** [comment]
Thanks a lot, works fine!

**Comment by erycoking** [comment]
@Seldaek kindly can you post a valid global composer.json file content because mine is giving me the same error and am a newbie to laravel. some help would really go along way.

**Comment by Seldaek** [comment]
`{}` is a valid json file.. I don't know what you are asking sorry. Maybe share your file's contents then we can help.
