### ISSUE TITLE
is it possible to do a non deferred autoload?

### ISSUE THREAD

**Issue by cyberhck** [composer/composer#6247]
I'm trying to get list of my controllers using `get_defined_classes`, but composer does a deferred autoload (I do understand it's because of __autoload thing) is there a way to load them instantly? I'm doing this for only development environment, which will automatically write to a file when on production.

Thanks in advanced.

**Comment by Seldaek** [comment]
If you run `composer dump-autoload --optimize`, all classes will be scanned into the `vendor/composer/autoload_classmap.php` file. You can require that file, and it will return the array with all classes known and the paths they are in. array_key() on that should get you what you want.
