### ISSUE TITLE
Exists there an option to install packages as minimal without examples or documentation ? 

### ISSUE THREAD

**Issue by yourchoice** [composer/composer#6252]
Exists there an option to install packages as minimal without example or documentation ?

My vendor folder have 16M. 

Many files are with examples or docs. 

Will be better if there can be a command to clean files that are not dist, or something on install to add just main files.

**Comment by alcohol** [comment]
No. Package maintainers can use `.gitattributes` to mark certain files as excluded from archive files generated by Github though (and use by Composer for dist installs). But honestly, 16mb is insignificant. And you can always setup a proper build process that cleans your deploy artifact if it is such a major concern for you.
