### ISSUE TITLE
Optional packages

### ISSUE THREAD

**Issue by goetas** [composer/composer#6255]
This is a feature request or a request for comments.

I'm writing some libraries that generally are used as dependencies in other projects.
Example `composer.json`:

```json
{
    "name": "goetas/cool",
    "require": {
        "php": "^7.0"
    },
    "suggest": {
        "doctrine/orm": "Required to use some cool doctrine feature with my lib."
    },
    "require-dev": {
        "doctrine/orm": "2.1.*"
   }
}
```

This file says that my library suggests doctrine/orm and looking at the "require-dev" section, probably is compatible only with doctrine/orm 2.1.x.

Now when somebody want to use my library can do something as:

```json
{
    "name": "project/project",
    "require": {
        "goetas/cool": "*",
        "doctrine/orm": "1.0.0"
    }
}
```

Composer will not complain and install dependencies as requested, but probably something will not work well since the doctrine version is wrong (v1.0.0 vs 2.1.x).

I do not want to put the optional dependency in the "require" section because is not mandatory, but in case the dependency is present, will be good to trigger at least some kind of alert to inform the user that the dependencies are not fully satisfied.

**Comment by jvasseur** [comment]
You could use a conflict rule to disallow installing your package with incompatible optional dependencies:
```json
{
    "suggest": {
        "doctrine/orm": "..."
    },
    "conflict": {
        "doctrine/orm": "<2.1.0,>=2.2.0"
    }
}
```

**Comment by goetas** [comment]
Sounds as a solution. Thanks
