### ISSUE TITLE
Why are stability flags on require root-only?

### ISSUE THREAD

**Issue by sminnee** [composer/composer#6258]
Suppose I have a library that currently depends on a development version of a dependency. In theory I could mark this using a stability flag:

```json
{
  "name": "sminnee/coollib",
  "require": {
    "symfony/config": "^3.3@dev"
  }
}
```

However, stability flags are only respected in the root repo, so this won't work:

```json
{
  "name": "sminnee/coollib",
  "require": {
    "sminnee/coollib": "*",
  }
}
```

Instead I'd have to add min-stability and/or prefer-stable.

```json
{
  "name": "sminnee/coollib",
  "require": {
    "sminnee/coollib": "*",
  },
  "min-stability": "dev",
  "prefer-stable": true,
}
```

This is an okay solution, but there are two reasons why it seems a bit suboptimal:

 * The min-stability and prefer-stable settings end up impacting the package resolution behaviour of all the other libraries I pull in. I'd prefer to be able to whitelist only those packages that need non-stable dependencies
 * The consumer application now needs to take responsibility for the management of sminnee/coollib dependencies. I'd prefer for the developer including sminnee/coollib not to have to worry about this.

What is the reason why stability flags are root-only, and is it something that could be changed?

Is there a better way of letting a libraries indicate the inclusion of a single specific non-stable dependency?

**Comment by tractorcow** [comment]
To add a bit of context to this, the main goal we have for this feature is to ensure that our CI runs certain other dependency modules vs their dev-* branches, but all other third party dependencies are installed as stable versions.

Note that using `dev-master` / `3.3.x-dev` etc as the dependency immediately makes installing non-dev versions impossible (negative implications outside of simply running CI), hence why we began looking into `^3.3@dev` as an alternative.

**Comment by alcohol** [comment]
This is not going to change. The responsibility lies with the root user, not dependencies. The root user has total control. Dependencies have least control.

**Comment by Seldaek** [comment]
And to explain a bit more, this is like this because various people have various stability requirements, and having the root in charge means everyone can tweak to their liking. If dependencies had the ability to override that it'd be anarchy :)

**Comment by sminnee** [comment]
OK thanks for the feedback!
