### ISSUE TITLE
Allow --timeout parameter for shorthand invocation of user scripts

### ISSUE THREAD

**Issue by Xerkus** [composer/composer#6259]
#4920 added --timeout parameter to run-script command:
```
composer run serve --timeout 0
```
However, shorthand form does not allow `--timeout`:
```
$ composer serve --timeout 0
[Symfony\Component\Console\Exception\RuntimeException]  
The "--timeout" option does not exist. 
```

**Comment by alcohol** [comment]
`run` is already shorthand form for `run-scripts`. Completely omitting that does not result in `run-scripts` being called anymore, but rather some sort of lookup process trying to find other commands that might match. Said lookup does not support the `timeout` flag.

Please use the proper shorthand form of `run-scripts` (anything that does not match another command, e.g. `ru`).
