### ISSUE TITLE
PRE_PACKAGE_UNINSTALL is never fired

### ISSUE THREAD

**Issue by SebCorbin** [composer/composer#6261]
__Problem__
Willing to contribute to https://github.com/cweagans/composer-patches and https://github.com/derhasi/composer-preserve-paths, I discovered that `PackageEvents::PRE_PACKAGE_UNINSTALL` is documented but never used

__Question__
So I'm wondering if it should be dispatched by composer itself on `$this->composer->getInstallationManager()->uninstall()` or by the module calling this?

**Comment by alcohol** [comment]
This is either a bug, or it was simply never implemented. Either way, a pull request is welcome :-).

**Comment by SebCorbin** [comment]
So my bad, this morning I dug up in the code and it seems implemented here https://github.com/composer/composer/blob/master/src/Composer/Installer.php#L572 bu the thing is, the number of arguments to reproduce this is too damn high :)

I tried a hotfix for the patch plugin here https://github.com/SebCorbin/composer-patches/commit/1cb9bacba51f8bba0c5f3f322c3bb61e4ceae974 and it is ugly
I don't want to break the API so I'm not gonna write a pull request, and now that I've found why I'm frustrated feel free to close this issue
