### ISSUE TITLE
Path repo (local git repo) not getting symlinked

### ISSUE THREAD

**Issue by introwit** [composer/composer#6265]
I have a fresh [Laravel](https://github.com/lubusIN/laravel-decomposer) app installed. I also have a local cloned copy of my [package](https://github.com/lubusIN/laravel-decomposer) I just learned about the path repository concept from Taylor Otwell in a talk. So I went ahead to apply the concept for my package development. The composer json file of my package mentioned above is as follows

```
{
    "name": "lubusin/laravel-decomposer",
    "description": "A Laravel package to decompose and list your installed packages and their dependencies",
    "license": "MIT",
    "authors": [
        {
            "name": "Harish Toshniwal",
            "email": "harish@lubus.in"
        }
    ],
    "autoload": {
        "psr-4": {
            "Lubusin\\Decomposer\\": "src/"
        }
    },
    "require": {
        "php": ">=5.6",
        "illuminate/database": "~5.3",
        "illuminate/support": "~5.3"
    },
    "require-dev": {
        "illuminate/routing": "~5.3",
        "illuminate/http": "~5.3"
    }
}
```
In the fresh laravel app's composer json i refer the local copy of my package by adding the following in it:

```
"repositories": [
        {
            "type": "path",
            "url": "./../laravel-decomposer",
            "options": {
                "symlink": true
            }
        }
    ],
```
After that I add the package to the require field of the app's composer json as follows:

```
"lubusin/laravel-decomposer": "*"
```

After I run `composer update` , it downloads the package in the vendor directory rather than creating a symlink for it.

@balbuf I saw one of your PR's on similar issue, can you help me please :)

**Comment by alcohol** [comment]
Can you give us the actual output composer produces, in verbose mode? We are missing important information right now. Also, it would help if you could tell us the absolute path of your laravel application and the absolute path of your package.

**Comment by introwit** [comment]
@alcohol here is the output

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing lubusin/laravel-decomposer (v1.0.1): Loading from cache
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
The compiled services file has been removed.
```

I am on ubuntu 16.04 & using PHP 7.1 , with LEMP stack. In my var/www/html directory I have those 2 repos: The Laravel app & the package

**Comment by curry684** [comment]
```
  - Installing lubusin/laravel-decomposer (v1.0.1): Loading from cache
```
The cache check is likely winning in being able to provide a matching version of the package, since you aren't specifying a minimum stability from what we can see. Try running `composer clearcache` and including the package explicitly as dev:
```
"lubusin/laravel-decomposer": "*@dev"
```

**Comment by introwit** [comment]
@curry684 that worked, Thank you so much :) Can you let me know what was wrong with that stability stuff, would be helpful for me to understand the mistake?

**Comment by curry684** [comment]
The default setting for `minimum-stability` is `stable`, refer to https://getcomposer.org/doc/04-schema.md#minimum-stability. The `@dev` postfix allows you to override that on a per-package basis during development (it's only respected in the root package). Path repositories are considered as `dev-master` by definition unless explicitly versioned in their own `composer.json`.

So the end result was that you were trying to include a dev package which was not a valid candidate due to stability, which usually gives a verbose error to that end, but not now as a lower priority repository (Packagist) was able to provide a package matching your requirements. Hence the solver never saw a problem and just resolved to the cached package.

**Comment by introwit** [comment]
@curry684 ah! That makes sense. Thank you so much for the info :)
