### ISSUE TITLE
zizaco/entrust": "5.2.x-dev problem

### ISSUE THREAD

**Issue by nadiaRasid** [composer/composer#6266]
composer update:

"zizaco/entrust": "5.2.x-dev" cannot install in my laravel 5.4 how to solve?

**Comment by alcohol** [comment]
Can you please include relevant output of the composer command you are running (in verbose mode). Saying that you have a problem without accurately describing the problem does not give us the ability to help you.

**Comment by Maxim-Mazurok** [comment]
@nadiaRasid here is my `composer.json` file contents:
```
{
    "require": {
        "laravel/laravel": "^5.4",
        "zizaco/entrust": "5.2.x-dev"
    }
}
```
and `composer update` it like a charm. Composer installed `laravel v5.4.16` and `entrust 5.2.x-dev 3623cc0` using `PHP 7.0.16`.

Which version of PHP you use? It seems like Zizaco/entrust dropped PHP v5.4 support and Laravel requires PHP version >= 5.6.4. You can check your PHP version by running `php -v` in terminal or by using `<?php phpinfo(); ?>` file.

**Comment by Seldaek** [comment]
Auto-closing this as it's marked as support request and has not received any update in a long time.
