### ISSUE TITLE
Issues with SSL connection to packagist behind corporate proxy

### ISSUE THREAD

**Issue by Lyca0n** [composer/composer#6269]
My `composer.json`:

    {
         "name": "mis",
         "description": "Call Center",
         "type": "Application",
        "keywords": [ "mysql", "pdo", "php" ],
        "homepage": "",
        "authors": [
            { "name": "jvillalv", "email": "julio.villalva@domain.com" }
        ],
        "config": {

        },    
        "require": {
            "php": ">=5.5.0",
            "phpmailer/phpmailer": "^5.2",
            "symfony/http-foundation": "^3.1",
            "dompdf/dompdf": "^0.7.0",
            "eventviva/php-image-resize": " 1.6.*",
           "ssilence/php-imap-client": "dev-master"
        
        },
        "autoload": {
            "psr-4": { "": "src/" }
        }
    }

Output of `composer diagnose`:

Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you
 may use "proprietary" as license.
Defining autoload.psr-4 with an empty namespace prefix is a bad idea for perform
ance
require.ssilence/php-imap-client : unbound version constraints (dev-master) shou
ld be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: WARNING
[Composer\Downloader\TransportException] The "https://packagist.org/packages.jso
n" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error
 messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify faile
d
failed to open stream: Cannot connect to HTTPS server through proxy
Checking HTTP proxy: FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.jso
n" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error
 messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify faile
d
failed to open stream: Cannot connect to HTTPS server through proxy
Checking HTTP proxy support for request_fulluri: OK
Checking HTTPS proxy support for request_fulluri: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB
723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E32
8C AD90147D AFE50952
OK
Checking composer version:

  [Composer\Downloader\TransportException]
  The "https://getcomposer.org/versions" file could not be downloaded: SSL op
  eration failed with code 1. OpenSSL Error messages:
  error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify
  failed
  failed to open stream: Cannot connect to HTTPS server through proxy

diagnose

When I run this command:

    composer require symfony/http-kernel

I get the following output:

The "https://packagist.org/packages.json" file could not be downloaded: SSL/TLS
already set-up for this stream
failed to open stream: Cannot connect to HTTPS server through proxy
https://packagist.org could not be fully loaded, package information was loaded
from the local cache and may be out of date
Using version ^3.2 for symfony/http-kernel
./composer.json has been updated
Loading composer repositories with package information
The "https://packagist.org/packages.json" file could not be downloaded: SSL/TLS
already set-up for this stream
failed to open stream: Cannot connect to HTTPS server through proxy
https://packagist.org could not be fully loaded, package information was loaded
from the local cache and may be out of date
Updating dependencies (including require-dev)

Installation failed, reverting ./composer.json to its original content.

  [Composer\Downloader\TransportException]
  The "http://packagist.org/p/phpmailer/phpmailer%24206bd23bf33105b8a3daf1866
  58d3f416295021af46748783a23476102e392ee.json" file could not be downloaded
  (HTTP/1.1 302 Found)

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update]
[--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform
-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-auto
loader] [-a|--classmap-authoritative] [--] [<packages>]...

And I expected this to happen:

install symfony/http-kernel

**Comment by curry684** [comment]
Given that the corporate proxy is obviously to blame, why are you not talking to the system administrators? We cannot fix your misbehaving proxy...

**Comment by m0rtal1990** [comment]
Code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify
failed.

There have been significant changes from PHP 5.5.0 to PHP 5.6.0 for OpenSSL.
Have you perhaps tried updating to PHP 5.6 or later? If not, check the Link below for OpenSSL migration reference. (From 5.5 to 5.6)

> While not recommended in general, it is possible to disable peer certificate verification for a request by setting the verify_peer context option to FALSE, and to disable peer name validation by setting the verify_peer_name context option to FALSE.

Just to be on the safe side check your certificates (are they self-signed?)

Links:
http://stackoverflow.com/questions/32211301/ssl-error-ssl3-get-server-certificatecertificate-verify-failed (Kind of sums up my response, taking into account the Certificates and perhaps PHP Issue.)

http://php.net/manual/en/migration56.openssl.php
(PHP 5.6 OpenSSL Migration)

**Comment by Seldaek** [comment]
Auto-closing this as it's marked as support request and has not received any update in a long time.
