### ISSUE TITLE
How composer finds which version to install

### ISSUE THREAD

**Issue by introwit** [composer/composer#6275]
I am developing a Laravel package. My package requires Illuminate/support as it's dependency. But requiring 5.3.* version of that makes my package only installable on Laravel 5.3 + , so to make it available for > = Laravel 5.1 , I need to use version 5.0.* of Illuminate/support as my package dependency. To solve this I looked how other packages are doing it. One of the famous package is doing this in it's composer.json : 

```
"illuminate/support": "~5.1.0|~5.2.0|~5.3.0|~5.4.0",
```

So when someone installs his package which version of Illuminate/support will composer pull in? And why? What is the order of priority composer will follow? 

Should I do the same or just do `illuminate/support: >=5.0` ? It might sound noob but sorry :( Any help/guidance would be very helpful!

**Comment by curry684** [comment]
That example is very wrong, and you should use `^5.0`. Semver then takes care that you accept all non breaking updates to that package. You should configure CI to also test with `composer update --prefer-lowest` to ensure your lower bounds remain compatible.

Consumers of your package will, if using default settings, get the most recent possible version of all their packages that are allowed by all installed packages. Therefore as a library developer it is best to limit as little as possible in your own constraints.

**Comment by introwit** [comment]
@curry684 Oh! Thanks :) Also, what does the minimum-stability key will do? Like if I add `minimum-stability: dev` in my package , how composer will figure out which release is stable and which is dev?

**Comment by alcohol** [comment]
@curry684 except laravel doesn't follow semver, so your suggestion is not right in this scenario.

In the original example given for `illuminate/support`, it seems they specifically targeted `>= 5.1, < 5.5` (which would be an easier way of writing this also). There is probably a reason they only want to support those versions at the moment.

**Comment by introwit** [comment]
@alcohol so which one out of these will be installed when I do this `"illuminate/support": "~5.1.0|~5.2.0|~5.3.0|~5.4.0",` in my package and the users do composer require my package? If they are on Laravel 5.1 will they get the 5.1.0 of illuminate/support and so on for the specific version? Just a Guess.

**Comment by alcohol** [comment]
That depends on the constraints imposed by other packages. I am not a dependency solver, nor do I know all the constraints involved, so I cannot tell you which version will get picked.

**Comment by introwit** [comment]
@alcohol this is my package's composer.json

```
{
    "name": "lubusin/laravel-decomposer",
    "description": "A Laravel package to decompose and list your installed packages and their dependencies",
    "license": "MIT",
    "authors": [
        {
            "name": "Harish Toshniwal",
            "email": "harish@lubus.in"
        }
    ],
    "autoload": {
        "psr-4": {
            "Lubusin\\Decomposer\\": "src/"
        }
    },
    "require": {
        "php": ">=5.6",
        "illuminate/support": "^5.0"
    },
    "require-dev": {
        "illuminate/routing": "^5.0",
        "illuminate/http": "^5.0"
    }
}
```

So if I replace the Illuminate/support & all requirements with the given example format of piped one, then? Sorry for being noob but I really don't understand.

**Comment by alcohol** [comment]
Like I already said before, it entirely depends on the constraints you impose, but also other packages. Right now, you are saying that your package will accept any version of `illuminate/support` that matches `>= 5.0, < 6.0` (which is what `^5.0` basically expands to). The example in your opening post would only allow `>= 5.1, < 5.5` as I already explained.

But assuming your package is installed as a dependency, and not as the root project, then you have to factor into account that other packages can have other constraints, imposing extra limits on which versions of `illuminate/support` are acceptable and which not. It is impossible therefor to tell you which version is installed, because as I said previously, I am not a dependency solver, nor do I know all the constraints that can affect this decision process. If you do not understand the concept of dependency solving, please go read some articles (or wikipedia).

**Comment by introwit** [comment]
@alcohol thank you so much Rob :)

**Comment by curry684** [comment]
> except laravel doesn't follow semver

Yikes, what century are they from...

**Comment by alcohol** [comment]
https://twitter.com/taylorotwell/status/698181502215938048

I don't think anything has changed since then. They still have not adopted it.
