### ISSUE TITLE
composer selfupdate command updates composer systemwide.

### ISSUE THREAD

**Issue by ShantanuKondhalkar** [composer/composer#6276]
First of all, I installed composer globally where version was 1.3.0.
Now I installed it for specific directory and then I fired command `composer selfupdate`.
In this case I was expecting that version for specified folder to be upgraded to 1.4.1, but it seems that system wide version of composer is now 1.4.1

**Comment by curry684** [comment]
It updates the executable you invoke, and has no interest in how many installs you have. 

It is also kind of assumed you only have a single install on your system, as there is no point whatsoever to keeping multiple or local installs.

**Comment by alcohol** [comment]
The binary will update itself. If you execute the global binary, the global binary is updated.

**Comment by ShantanuKondhalkar** [comment]
Thanks a lot :)
