### ISSUE TITLE
Change php version used by composer on windows

### ISSUE THREAD

**Issue by crashbdx** [composer/composer#6277]
Hi everyone, 

I don't understand why my composer is using a 5.4.45 php version when i don't see such version on my computer, i use wamp with php 5.6.25 , in my environmemt variable i have the this version on top of the list of path value.
Is there a want to change the version composer is using please ?

**Comment by alcohol** [comment]
> I don't understand why my composer is using a 5.4.45 php version 

Please explain what this means, where this information comes from, or what you are basing this on. Because it makes zero sense without any actual context.

**Comment by Seldaek** [comment]
@crashbdx the PATH value should contain the directory of the php.exe, not the full path including php.exe, just in case there is some confusion there.

Composer is not at fault in any case as this is OS/shell-level resolution.

If you're on windows you can type `where php` to see which php is used, or in bash on linux/OSX type `which php`.

**Comment by denisdulici** [comment]
@crashbdx the only way is to uninstall and install it again 😉 

@alcohol @Seldaek it would be nice if there were an option to change the following option without having to uninstall => install:

![2017-07-05_1025](https://user-images.githubusercontent.com/5254835/27853770-bfbd40c2-616c-11e7-80c6-e76305abb7fa.png)

**Comment by alcohol** [comment]
@denisdulici such requests should really be posted to [composer/windows-setup](https://github.com/composer/windows-setup). Then @johnstevenson can have a look at it and see how feasible it is :-)

**Comment by treetechsuman** [comment]
the only way is to uninstall and install it again 😉 work for me

**Comment by geeky3** [comment]
You can change php version of composer without uninstalling it, follow these steps : 
1) Search for system environment variables in cortana.
2) Click on the button "Environment variables".
3) Under "System variables" select path and click on edit, you will see one entry like this "C:\wamp\bin\php\php5.6.13".
4) Just change this to the folder name of the php located at your wamp/bin/php7.1.9, here bin7.1.9 is folder name.
5) Replace php5.6.13 with bin7.1.9, it will look like these "C:\wamp\bin\php\php7.1.9", just click ok on all the boxes.
6) You are done.
7) To verify, first close all the cmd windows, than open cmd and type "php -v", press enter and you should see php7.1.9.
8) If you don't see change in php version than just restart your pc and run php -v again in cmd , it will work.

**Comment by linslin** [comment]
IMO there is no need to switch the  environment variables just for running composer commands with a different PHP Version (which is not set in your env paths.). Just run your `composer.phar` with a absolut PHP execution file path and you will be fine:

**On window**: `C:\xampp\php\php.exe C:\ProgramData\ComposerSetup\bin\composer.phar install`
**On *ngix**: `/usr/bin/php /usr/local/bin/composer install`

**Comment by AndrasZiegenham** [comment]
DependencyResolver easily eats up over 1GB and 32bit php is limited to 2GB memory use and oddly enough I get fatal errors near 1.3GB, so I have to use a 64bit php just for composer.

So according to this (and this: https://github.com/composer/windows-setup/issues/72) topic the devs apparently don't care about this sort of problem and want you to change your whole system's environment to a different php... noice...

The only workaround seems to be the one mentioned by @linslin even though one can end up with monsters like this (using GitBash on windows): 

 /c/php/php-7.2.9-Win32-VC15-x64/php.exe -d memory_limit=-1 "c:\ProgramData\ComposerSetup\bin\composer.phar" update

Really, am I supposed to write this instead of "composer update"? Legit.

**Comment by RahulDey12** [comment]
![image](https://user-images.githubusercontent.com/26340814/75170512-3a940200-5750-11ea-96b6-b213642aaecb.png)
check out this i have composer installed and php command working on my pc but there is no php in path variable

**Comment by stof** [comment]
@RahulDey12 check both the user list and the system list. Both provide values for the PATH variable.

**Comment by jonathanlaf** [comment]
Same has @RahulDey12  I can't find it, even on user list and system list! Where the heck did Composer created that link 😲 ?

**Comment by hamidullorahmonberdiyev** [comment]
Hi. My project is has this error. "Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.9". You are running 8.0.22. in C:\OSPanel\domains\task-manager\vendor\composer\platform_check.php on line 24"

**Comment by FebryantoAdityaRizky020204** [comment]
if you want to change the PHP version used by Composer, you can add the PHP path to the environment variable. Make sure the path for the PHP version you want is at the top of the list above other PHP versions, so Composer will detect that version, as will your CMD.

![image](https://github.com/user-attachments/assets/c9e09d1e-4c59-4518-9a50-3e9122f31a72)
