### ISSUE TITLE
Documentation precision for composer.lock

### ISSUE THREAD

**Issue by theredcat** [composer/composer#6278]
Hi,

I'm using composer for a while and I'm using it without a lockfile. I know that the best practices in documentation is to use the lock to ensure same version will be used by your colleagues, CI, etc...

But in practice, I've not seen any difference between this method and using strict version number in the JSON:

- NOT use `"user/pkg": "^1.2.3"`
- NOT use `"user/pkg": "1.2.*"`
- but use `"user/pkg": "1.2.3"`

I think this should be in documentation as an alternative best-practice.

https://github.com/composer/composer/blame/master/doc/01-basic-usage.md#L133

This paragraph was added by @igorw, updated by @weaverryan and has minor modifications made by @kael-shipman and @alcohol

**Comment by curry684** [comment]
It's definitely not a best-practice as you are now saying *"hey I don't give a damn if a serious and fatal security issue is found in my library tomorrow, I'll just keep silently using the screwed up one"*.

The whole point of caret constraints is that it does give you minor and patch updates without affecting project integrity. The point of locking it down is [dev/prod parity](https://12factor.net/dev-prod-parity).

**Comment by theredcat** [comment]
> It's definitely not a best-practice as you are now saying "hey I don't give a damn if a serious and fatal security issue is found in my library tomorrow, I'll just keep silently using the screwed up one".

Indeed, but in the other hand, that mean that you can have a project going in production with security issues in a project where the devs never use "update" because they don't need any updates (E.g. : Symfony/Laravel project with lot of in-house code and few dependencies).

If you want to be up to date in production, you can use the caret constraints and have the latest version.
If you don't want to be up to date, you can then use the lock or a strict version number.

**Comment by alcohol** [comment]
It is not good practice, so it is not worth documenting.

**Comment by curry684** [comment]
> the devs never use "update" because they don't need any updates

That's still the hallmark of a flawed devops process. Needing updates is not a decision based on features alone.

At the beginning of each sprint or development cycle it should be mandatory to run either `composer update` or at least check `composer outdated`, and the lead developers should be subscribed to https://security.sensiolabs.org/database. Or make it an [automated part of your CI process](https://security.sensiolabs.org/check).
