### ISSUE TITLE
Issue a warning if a project is created without a .lock file

### ISSUE THREAD

**Issue by schmunk42** [composer/composer#6282]
This request or proposal has emerged from https://github.com/yiisoft/yii2-app-basic/issues/112

Many application template-projects do not put the `.lock` in their repos. Which leads to different behaviors outlined in https://github.com/yiisoft/yii2-app-basic/issues/112#issuecomment-288066205, eg. `create-project` does an `update` not an `install` without a `.lock` file.

IMHO a `validate` and/or `create-project` should issue a warning when not having a lock file (at least for projects, it's fine for libs not to have one). Similar to warnings like *unbound* or *overly strict* constraints.

I know this is a highly disputed topic, but I felt it was required to raise an issue here.

**Comment by curry684** [comment]
Fwiw I agree with https://github.com/yiisoft/yii2-app-basic/issues/112#issuecomment-286392078

In my opinion good practice is to run update at the start of a sprint or new development cycle. This is the point where you start developing new code and then hopefully go through thorough testing before releasing. As the scenario you're referring to is starting a new project, the most fundamental example of the beginning of a development cycle, I agree with @mikehaertl that this is the prime moment to update your dependencies. Who wants to start a new project with dependencies full of known bugs and security vulnerabilities?

**Comment by schmunk42** [comment]
> Who wants to start a new project with dependencies full of known bugs and security vulnerabilities?

That (*full of known bugs and security vulnerabilities*) is usually not the case, if the `lock` file is maintained like every other part of the app. The chance of getting an update which breaks things is also a problem. What I am saying (over and over) in the other thread is, that no-one is keeping you from doing that `update`.

But that is debatable (as I learned 🙄 ), what I am referring to is [this](https://getcomposer.org/doc/03-cli.md#create-project):

> You can use Composer to create new projects from an existing package. This is the equivalent of doing a git clone/svn checkout followed by a "composer install" of the vendors.

Which is simply not the case if the `composer.lock` file is missing. Maybe an additional thing, but then there should be `composer create-project --update`.

---

I feel that is also a reason why so many developers don't even know the difference between `update` and `install`, while researching about this topic I saw so many people commenting like: "I usually run update in production" 💥 Because they "learn" it from the beginning - or let's say think, that there's no difference anyway.

**Comment by schmunk42** [comment]
*From thread at yiisoft*

The point is, that having a lock file should not affect your workflow. 

Let's put it the other way around,  `create-project` does the update by default, but then it would be nice to have

```
composer install-project
```

**Comment by cebe** [comment]
> create-project does the update by default

composer create-project runs composer install, which will result in an update if no lock file is present, but will install if there is one. What is the purpose of `composer install-project`?

**Comment by schmunk42** [comment]
I was thinking loud about a way how to implement or improve this in BC-way.
Personally, I'd like

```
composer create-project --update
```

more. This would behave like a `create-project --no-install` followed by `composer update` - the way it currently works without having a .lock file.

`install-project` would check & enforce the existence of a lock-file, while `composer create-project` would then always update. As I write this - makes no sense ... Only the update switch would be cool.

**Comment by curry684** [comment]
But then what's the added value of the switch over simply typing:
```
composer create-project <src>
composer update
```
I don't really see the point of a switch that just replaces a single simple followup command.

**Comment by schmunk42** [comment]
It's a bit more, and I'd say it's much clearer and intuitive to have

```
composer create-project
```

```
composer create-project --update
```

vs.

```
composer create-project
```

```
composer create-project --no-install ...
cd DIR
composer update
```

The first one is also like `composer create-project --install`. While you can choose between `update` and `install` for an existing project, it's kinda hard to do that when creating a project.

Example about template installation, see https://github.com/yiisoft/yii2-app-basic/issues/112#issuecomment-288326029

**Comment by schmunk42** [comment]
As said in another issue, don't mean to annoy anyone, but I think, because of this issue https://github.com/composer/composer/issues/6282 or let's say the missing option; we (composer projects in general) have issues like https://github.com/yiisoft/yii2-app-basic/issues/112 - which has valid points.
But still, there are complex applications, which do not include a lock also https://github.com/humhub/humhub/issues/2416 - maybe due to the same reasons layed out above.
Finally, people have to add secrets to their repos https://github.com/Tails/docker-humhub/issues/1 - no hard feeling I did that also in the beginning, just because there was no other option in some cases.

So and `--update` option or warning would merely help the user to use `composer` correctly.

**Comment by Seldaek** [comment]
I don't think we want to warn on missing lock file. It's not our job to be opinionated on how people should do such things. That's a project policy thing IMO for create-project.

I read some of that yii thread and I tend to agree with what was said there.

**Comment by schmunk42** [comment]
> It's not our job to be opinionated on how people should do such things.

Yes, I agree.

My only issue is, that there's no choice in `create-project` and so we're forced to use the opinionated workflow used by other projects.

**Comment by schmunk42** [comment]
It does not leave me in peace :)

Just noticed that:

> Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

Which is pretty similar to what I've initially request, just sayin'...

**Comment by curry684** [comment]
That is just the result of a basic check whether you're running install on a lockfile older than its companion composer.json file, followed by a hash compare. That's a clear cut error situation leading to unexpected results if not fixed.

**Comment by schmunk42** [comment]
It's not an *error* situation, but a missing lock file also leads to unexpected results when running `install`.

So, if you've *changes* in `composer.json` and run `install` you still can use the command as intended, but you get a warning.

But if you *remove* the lock and run `install` composer **silently** falls back to update, that's the point where I'd expect a similar warning to above, like

> Notice: No `lock` file found, composer will `update` your project dependencies now...

---

Slightly OT: Why does composer need `.json` at all when building a release? Shouldn't a `.lock` file be sufficient for the installation?

**Comment by jvasseur** [comment]
@schmunk42 the `composer.lock` file only contains the information of the packages to install, it still needs the autoloading information for the root package and scripts to launch to do an install.

**Comment by schmunk42** [comment]
> it still needs the autoloading information for the root package and scripts to launch to do an install.

Ah 💡  right :) Thank you.
