### ISSUE TITLE
Composer URL cache doesn't invalidate dist URL on new package version

### ISSUE THREAD

**Issue by khromov** [composer/composer#6285]
We have noted that if the `dist` URL of a package does not change between versions, Composer will load the old version from cache, meaning you will get old version of dependencies. A better behaviour would be that Composer should re-download the URL if the version changes, because sometimes the `dist` URL might not have changed. Is this intended behaviour or is there an issue in our repository (WPackagist)

Related issue:
https://github.com/outlandishideas/wpackagist/pull/220

My `composer.json`:

```json
{
    "repositories":[
        {
            "type":"composer",
            "url":"https://wpackagist.org"
        }
    ],
    "require": {
        "wpackagist-plugin/wp-core-media-widgets": "dev-trunk"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.wpackagist-plugin/wp-core-media-widgets : unbound version constraints (dev-trunk) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

N/A

I get the following output:

N/A

And I expected this to happen:

N/A

**Comment by curry684** [comment]
Given the amount of issues being posted all the time in this project about misbehaving corporate proxies I would definitely never recycle URLs for different versions. Apart from that, it also disqualifies ever hosting your project on a CDN (CloudFront et al will happily cache a version for 30+ days).

Best practice is always to have a canonical URL per canonical version.

**Comment by khromov** [comment]
@curry684 I see your point. While my proposed fix would eliminate certain edge cases, it would add ambiguity around the caching. Then again, the current way is worse in my opinion (ie. you can't **update** to a new version without using `clear-cache` first.) 

I don't think you could revert to a previous version in this situation.

**Comment by alcohol** [comment]
Maybe we could use ETags if those are served.

**Comment by Seldaek** [comment]
Sorry but I don't really think it's worth invalidating all existing URLs from caches just to fix some edge case where people reuse URLs for different resources (which is kind of a bad idea anyway if you ask me).
