### ISSUE TITLE
mac按照步骤安装，不管用，想问下怎么在mac安装

### ISSUE THREAD

**Issue by files3** [composer/composer#6286]
My `composer.json`:

```json
...replace me...
```

Output of `composer diagnose`:

```
...replace me...
```

When I run this command:

```
...replace me...
```

I get the following output:

```
...replace me...
```

And I expected this to happen:

**Comment by rquadling** [comment]
I installed composer using homebrew. I nice package manager for MacOS.

**Comment by swumao** [comment]
@files3 Please use english here.

**Comment by files3** [comment]
@rquadling ok，我试下，
@swumao ，sorry，My English is so bad
