### ISSUE TITLE
[SUPPORT] - Folder name on GIT clone

### ISSUE THREAD

**Issue by 7php** [composer/composer#6289]
Hi @Seldaek and team,
this is not an issue, but more of help/support with the scenario below. Note that I'm only writing the important things, leaving the obvious parts.

The `bitbucket` of my custom plugin, named as `myplugin`:

```
git@gitlab.com:mycloud/projectname/myplugin.git
```

The `composer.json` file of my custom plugin, named as `myplugin`:

```json
{
    "name"       : "mycloud/projectname-myplugin"
}
```

The `composer.json` file of my main project, requiring the plugin `myplugin`:

```json
{
    "require": {       
          "mycloud/projectname-myplugin": "^2"
}
```

behaviour of `composer install`:

```
fetches projectname-myplugin and names the folder as `projectname-myplugin`
```

behaviour of `git clone git@gitlab.com:mycloud/projectname/myplugin.git`:

```
pulls the repo and names the folder as `myplugin`
```

So my question is:

1) How can I tell composer to name the folder as `myplugin` instead of `projectname-myplugin` without renaming in composer `"name"       : "mycloud/projectname-myplugin"` to `"name"       : "mycloud/myplugin"`

Is this possible?

**Comment by Seldaek** [comment]
It might be possible, depends what kind of plugin it is, and if it's installed via composer/installers or not.. i.e. give us more real data to work with and not `some-plugin` :)

**Comment by Seldaek** [comment]
Auto-closing this as it's marked as support request and has not received any update in a long time.
