### ISSUE TITLE
dealing with passphrase protected ssh-keys

### ISSUE THREAD

**Issue by stoneisonline** [composer/composer#6290]
hi!

a nice feature would be when composer could deal with passphrase protected ssh-keys.
So I could load from private repositories.

thank you
best regards

**Comment by alcohol** [comment]
It's called using an ssh agent.

**Comment by stoneisonline** [comment]
any suggestions for windows 10? and how to configure? pageant does not work

Am 23.03.2017 7:34 nachm. schrieb "Rob" <notifications@github.com>:

**Comment by johnstevenson** [comment]
If you install Git for Windows, it includes an ssh agent.

**Comment by stoneisonline** [comment]
thanks @johnstevenson 
git for windows and 
http://stackoverflow.com/a/37027079 was the right configuration and solution for me

**Comment by alcohol** [comment]
As far as I know, `pageant` should work just fine on Windows 10 too. Are you sure you configured it correctly?
