### ISSUE TITLE
Operation timed out for https://getcomposer.org/versions

### ISSUE THREAD

**Issue by jasonbio** [composer/composer#6291]
Getting the following when attempting a new install of composer:

```The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: Operation timed out```

**Comment by curry684** [comment]
@Seldaek given https://github.com/composer/composer/issues/6288 and https://github.com/composer/composer/issues/6280 I suspect the DNS for the new geobalancing may be not as stable as wanted. 3 reports in 2 days can't all be locally broken DNS.

**Comment by jasonbio** [comment]
I've also noticed that accessing https://getcomposer.org/versions in the browser works fine but https://getcomposer.org/versions/ results in a 404.

**Comment by curry684** [comment]
They are different URLs so that makes sense.

**Comment by alcohol** [comment]
`https://getcomposer.org/versions/` is not valid.

**Comment by jasonbio** [comment]
This is working for me, closing the issue.

**Comment by sebastianlofaro** [comment]
@jasonbio I am having your same issue. How did it get resolved for you?

**Comment by travidal** [comment]
Receiving the error message: The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: Operation timed out". Apparently still an issue.

**Comment by pvincent** [comment]
same issue right now.
seems to be related to ipv6.
no hint yet

**Comment by f2pnt8** [comment]
This worked for me:
`curl -sS https://getcomposer.org/installer | php -d detect_unicode=Off`

**Comment by pvincent** [comment]
sorry,
I've tried again, and yet it does not work.
pretty sure, it's about ipv6
cause :

- curl -4sS https://getcomposer.org/installer => works
- curl -6sS https://getcomposer.org/installer => failure

**Comment by f2pnt8** [comment]
Try this:
https://getcomposer.org/doc/articles/troubleshooting.md#operation-timed-out-ipv6-issues-

**Comment by pvincent** [comment]
thanks f2pnt8.
`sudo sh -c "echo 'precedence ::ffff:0:0/96 100' >> /etc/gai.conf"` does the job

**Comment by NgoThiLinh** [comment]
where I can put it to fix this issue??
sudo sh -c "echo 'precedence ::ffff:0:0/96 100' >> /etc/gai.conf"

**Comment by shingionline** [comment]
thanks f2pnt8.
sudo sh -c "echo 'precedence ::ffff:0:0/96 100' >> /etc/gai.conf" works for me too

**Comment by evolic** [comment]
```sudo sh -c "echo 'precedence ::ffff:0:0/96 100' >> /etc/gai.conf"``` still does the job!
