### ISSUE TITLE
Composer not working behind proxy

### ISSUE THREAD

**Issue by alexandruantochi** [composer/composer#6294]
My `composer.json`:

{
}

Output of `composer diagnose`:

Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: WARNING
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: SSL/TLS
 already set-up for this stream
failed to open stream: Cannot connect to HTTPS server through proxy
Checking HTTP proxy: FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: SSL/TLS
 already set-up for this stream
failed to open stream: Cannot connect to HTTPS server through proxy
Checking HTTP proxy support for request_fulluri: OK
Checking HTTPS proxy support for request_fulluri: WARNING
Unable to assess the situation, maybe github is down (The "https://api.github.com/repos/Seldaek/jsonlint/zipball/1.0.0"
file could not be downloaded: SSL/TLS already set-up for this stream
failed to open stream: Cannot connect to HTTPS server through proxy)
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: SSL/TLS a
lready set-up for this stream
failed to open stream: Cannot connect to HTTPS server through proxy
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version:

  [Composer\Downloader\TransportException]
  The "https://getcomposer.org/versions" file could not be downloaded: SSL/TLS already set-up for this stream
  failed to open stream: Cannot connect to HTTPS server through proxy

When I run this command:

`composer global require "laravel/install"

I get the following output:

composer hangs at first line: `Changed urrent directory to C:/Users/Alex/AppData/Romanig/Composer`

And I expected this to happen:

I have configured my `http(s)_proxy` environment variables to http(s)://username:password@proxy;  Before the config, I could not install composer at all.

Now when I try to install any php framework, Composer gets hanged at the first line:

Also checking http connnectivity to packagist takes around 2 minutes to complete with `composer diagnose`.

**Comment by Seldaek** [comment]
You can try to remove https_proxy, sometimes that helps..

**Comment by karschulze** [comment]
I've got a similar issue behind a proxy. I've got the composer installed, but the installation of Neos failed always with the message: SSL23_GET_SERVER_HELLO:unknown protocol. I already posted this problem in [https://discuss.neos.io/t/neos-installation-failed-behind-a-proxy/2363](url)
I also tried to remove https_proxy. I created the following script to verify my environment:

    #!/usr/bin/php
    <?php
    $url = "https://packagist.org/packages.json";

    function getUrlContent($url){
     $ch = curl_init();
     curl_setopt($ch, CURLOPT_URL, $url);
     curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; .NET CLR 1.1.4322)');
     curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
     curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);
     curl_setopt($ch, CURLOPT_TIMEOUT, 5);
     $data = curl_exec($ch);
     $httpcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
     curl_close($ch);
     return ($httpcode>=200 && $httpcode<300) ? $data : false;
    }

    print_r(getUrlContent($url));
    ?>

This script works very well and I see the output on the console. The log file of the proxy (squid) is fine:
`1498680723.028 366 192.168.1.120 TCP_TUNNEL/200 4626 CONNECT packagist.org:443 - HIER_DIRECT/87.98.253.214 -`
When I use the composer the proxy server logged a client error (400 Bad Request)
`1498681768.407 0 192.168.1.120 TAG_NONE/400 4462 NONE error:invalid-request - HIER_NONE/- text/html `
I believe the config of the proxy is ok. It seems that Composer is faulty and does not work behind a proxy. 
My environment:

     $ ./Software/composer.phar --version 
     Composer version 1.4.2 2017-05-17 08:17:52

    $ lsb_release -a  
    No LSB modules are available. 
    Distributor ID: Ubuntu 
    Description:    Ubuntu 16.04.2 LTS 
    Release:        16.04 
    Codename:       xenial

    $ php --version 
    PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS ) 
    Copyright (c) 1997-2017 The PHP Group 
    Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies 
       with Zend OPcache v7.0.18-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies 
       with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans

Any comments are appreciated.

**Comment by Seldaek** [comment]
Automatically closing as this has not received any updates in a while. Please re-open if it is still relevant.
