### ISSUE TITLE
Use PHPCPD (to avoid copy/paste)

### ISSUE THREAD

**Issue by RyDroid** [composer/composer#6295]
Hi.

```
$ phpcpd src/
phpcpd 2.0.4 by Sebastian Bergmann.

Found 2 exact clones with 45 duplicated lines in 4 files:

  -	/home/xlgg9854/workspace/composer/src/Composer/Downloader/HgDownloader.php:38-58
 	/home/xlgg9854/workspace/composer/src/Composer/Downloader/FossilDownloader.php:43-63
 
  -	/home/xlgg9854/workspace/composer/src/Composer/Command/UpdateCommand.php:122-147
 	/home/xlgg9854/workspace/composer/src/Composer/Command/InstallCommand.php:88-113
 
0.10% duplicated lines out of 44188 total lines of code.
```

This should be fixed and PHPCPD should be used in Travis CI.
https://github.com/sebastianbergmann/phpcpd
There is a Debian package, so it can easily be used with apt addons in Travis.
https://packages.debian.org/jessie/phpcpd

Regards.

**Comment by Seldaek** [comment]
If we manage to rack up a whole 2 violations in 6 years of development, I think it's safe to say we don't need to run phpcpd on a regular basis..
