### ISSUE TITLE
PHP Fatal error install composer on cent os 6.5

### ISSUE THREAD

**Issue by robertolaneccia** [composer/composer#6300]
I'm trying to install composer on my server centos 6.5 PHP Version 5.6.30

I tried it with this command

`curl -sS https://getcomposer.org/installer | php`
but I get this error

```
PHP Fatal error:  Directive 'safe_mode' is no longer available in PHP in Unknown on line 0
curl: (23) Failed writing body (0 != 16133)
```
how do I fix? thanks

**Comment by Seldaek** [comment]
Remove safe_mode from your php.ini I would think.. I don't think we can do much for you here.
