### ISSUE TITLE
--no-dev does not exist?

### ISSUE THREAD

**Issue by andig** [composer/composer#6303]
My `composer.json`:

```json
{
    "name": "volkszaehler/volkszaehler",
    "type": "project",
    "homepage": "http://www.volkszaehler.org/",
    "license": "GPL-3.0",
    "support": {
        "wiki": "http://wiki.volkszaehler.org/",
        "email": "volkszaehler@lists.volkszaehler.org"
    },
    "require": {
        "doctrine/orm": "2.4.*",
        "phpmailer/phpmailer": "~5.2",
        "twig/twig": "~1.0",
        "cboden/ratchet": "0.3.*",
        "react/socket": "0.4.*",
        "react/http": "0.4.*"
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.*"
    },
    "autoload": {
        "psr-0": {
            "Volkszaehler\\": "lib/",
            "Tests\\": "test/",
            "Wrapper\\": "test/"
        }
    }
}
```

Output of `composer diagnose`:

```
	> composer diagnose
	Checking composer.json: OK
	Checking platform settings: OK
	Checking git settings: OK
	Checking http connectivity to packagist: OK
	Checking https connectivity to packagist: OK
	Checking github.com oauth access: OK
	Checking disk free space: OK
	Checking pubkeys:
	Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
	Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
	OK
	Checking composer version: OK
```

When I run this command:

```
composer require slim/slim
```

I get the following output:

```
    Using version ^3.8 for slim/slim
    ./composer.json has been updated

    Installation failed, reverting ./composer.json to its original content.

      [RuntimeException]
      The lock file does not contain require-dev information, run install with the --no-dev option or run update to install those packages.
```

And I expected this to happen:

Slim package should be installed. Also, according to the error message I was expecting the `--no-dev` option to be available as hinted by the error message.

Problem is that I cannot find _any_ way to achieve this:

    > composer require --no-dev slim/slim

      [Symfony\Component\Console\Exception\RuntimeException]
      The "--no-dev" option does not exist.

Also according to the help output, the --update-no-dev option should be available for the `require` command:

    > composer install --update-no-dev slim/slim

      [Symfony\Component\Console\Exception\RuntimeException]
      The "--update-no-dev" option does not exist.

**Comment by curry684** [comment]
Just run `composer update`, or `rm -f composer.lock && composer require slim/slim` to do it in one go.

**Comment by andig** [comment]
> Just run

Sure- but that wouldn't make composer more consistent?

**Comment by curry684** [comment]
It already is, you just tried two things that are not even mentioned in the error message. It tells you to either:

> run install with the --no-dev option

Which is not a solution for your specific problem actually. It never told you to run `composer require --no-dev` though, as that flag makes no sense with `require`.

It also suggested:

> or run update to install those packages

Which is what I said - `composer update` will solve it. It never told you to make up a `--update-no-dev` flag, which would make no sense with `install` anyway.

**Comment by andig** [comment]
@curry684 you're of course right- thanks for bearing with me. My second attempt was running `install` instead of `require`. doh. 

I'd still maintain that the error message

    The lock file does not contain require-dev information, run install with the --no-dev option or run update to install those packages.

is misleading in response to a require command? The `update` part is right if I first edit the `composer.json`, but the first part?

**Comment by curry684** [comment]
The 'problem' is that the error message is thrown in a shared piece of code, therefore pretty generic, and hence suggests 2 courses of action which are usually right, but in this specific case the first one wouldn't have solved it (or rather - was not matching your intended result). 

Whilst yes, that means the error message could be improved, the situation can only occur when you are modifying your dependencies, something which by its very definition should never occur outside dev environments, while running a setup with disabled dev dependencies, which by its very definition should pretty much never occur within dev environments. That makes it a quite exotic issue and one that no one has ever run into before to my knowledge, plus the second suggested course of action is still correct - `composer update` will absolutely solve it properly.

So well, imho too edgy to apply a messy fix.

**Comment by andig** [comment]
> So well, imho too edgy to apply a messy fix.

Never mind. I have been using composer for a couple of years now as dev and was not able to work it out. Obviously deficit on my side :(
