### ISSUE TITLE
spdx-licenses.json - failed to open stream: No such file or directory 

### ISSUE THREAD

**Issue by mikepmtl** [composer/composer#6304]
I saw another ticket with the same issue that was recently closed.
I installed composer using apt on Ubuntu 16.04.

Composer version @package_branch_alias_version@ (1.0.0-beta2) 2016-03-27 16:00:34

When running composer diagnose I receive the following exception:

[ErrorException]                                                                                                                         
  file_get_contents(/usr/share/php/Composer/../../data/Composer/res/spdx-licenses.json): failed to open stream: No such file or directory

The issue is the file is located at:
/usr/share/php/Composer/../data/Composer/res/spdx-licenses.json  (No ../../)

Would you know how to reach the people that maintain the Ubuntu package?

Thanks.

**Comment by mikepmtl** [comment]
***For anyone with the issue the work around is to simply create a symbolic link in /usr/share.

cd /usr/share
ln -s php/data .

**Comment by stof** [comment]
the Ubuntu package is not an official installation method. So support is not provided by the composer team. And it looks like their packaging is broken.

See http://packages.ubuntu.com/yakkety/composer for details about the package maintainers.
And I strongly recommend you to use a supported installation method instead.

**Comment by Seldaek** [comment]
See https://bugs.launchpad.net/ubuntu/+source/composer/+bug/1595289
