### ISSUE TITLE
Files were not autoloaded due duplicated hash returned by the AutoloadGenerator::getFileIdentifier()

### ISSUE THREAD

**Issue by markbook2** [composer/composer#6307]
We have a main project and two sub-projects each one with own composer.json, the main project loads `vendor/autoload.php` of sub-projects, due a duplicated hash the autoloading does not work for the second project. Here are the steps to reproduce the problem:

Create a new file, main.php:
```php
mkdir /tmp/dup-hash && cd /tmp/dup-hash

cat <<'OUT' > main.php
<?php
require __DIR__ . '/test1/vendor/autoload.php';
require __DIR__ . '/test2/vendor/autoload.php';
OUT
```

Then create two sub-projects, each one with own composer.json and an autoload.php file with the same content:
```sh
mkdir test1 test2

cat <<'OUT' > test1/autoload.php
<?php
echo __FILE__ . "\n";
OUT

cat <<'OUT' > test1/composer.json
{
    "autoload": {
        "files": [
            "autoload.php"
        ]
    }
}
OUT

# Copy file from test1 to test2 for testing
cp test1/autoload.php test2/autoload.php
cp test1/composer.json test2/composer.json

tree
.
├── main.php
├── test1
│   ├── autoload.php
│   └── composer.json
└── test2
    ├── autoload.php
    └── composer.json
```

Init the sub-projects:
```sh
cd test1 && composer require -n
cd ../test2 && composer require -n
```

Run the main.php:
```sh
cd ..
php main.php
```

Expected result:
```
php main.php
/tmp/dup-hash/test1/autoload.php
/tmp/dup-hash/test2/autoload.php
```

Actual result:
```
/tmp/dup-hash/test1/autoload.php
```
The second file was not loaded, but the expected result is different. It happens due the duplicated md5 hash in the `$GLOBALS['__composer_autoload_files']`. The md5 hash is generated by the `Composer\Autoload\AutoloadGenerator::getFileIdentifier()` (checked for latest Composer from the `master` branch):
```sh
grep -RP "'\w{32}'"
test2/vendor/composer/autoload_static.php:        '5f78fdc9d9414feb747d08e60d2a61c3' => __DIR__ . '/../..' . '/autoload.php',
test2/vendor/composer/autoload_files.php:    '5f78fdc9d9414feb747d08e60d2a61c3' => $baseDir . '/autoload.php',
test1/vendor/composer/autoload_static.php:        '5f78fdc9d9414feb747d08e60d2a61c3' => __DIR__ . '/../..' . '/autoload.php',
test1/vendor/composer/autoload_files.php:    '5f78fdc9d9414feb747d08e60d2a61c3' => $baseDir . '/autoload.php',
```

**Comment by alcohol** [comment]
Uh that seems weird and unlikely, since the method signature requires both a package name and a path. How could they be identical in both cases?

```
    protected function getFileIdentifier(PackageInterface $package, $path)
    {
        return md5($package->getName() . ':' . $path);
    }
```

**Comment by alcohol** [comment]
Also I do not understand why you are loading the autoload files of composer of your subpackages. This scenario makes no sense to me. Sub packages should be part of your root composer setup. You only need one autoloading entrypoint. Why are you even running composer for your subproject? Please explain why you have this weird scenario in the first place, so we can try to understand where you are coming from.

**Comment by markbook2** [comment]
> Uh that seems weird and unlikely, since the method signature requires both a package name and a path. How could they be identical in both cases?

They can be identical because the `$path` contains not absolute but relative one, example: `autoload.php`.

> Also I do not understand why you are loading the autoload files of composer of your subpackages. This scenario makes no sense to me. Sub packages should be part of your root composer setup. You only need one autoloading entrypoint. Why are you even running composer for your subprojects? Please explain why you have this weird scenario in the first place, so we can try to understand where you are coming from.

It can happen in a complex setup, when the root package don't have enough information about its dependencies, i.e. sub-packages. Here are some examples:

Scenario 1: include a package based on conditions which are calculated *at run-time*. E.g.:
```php
require __DIR__ . '/vendor/autoload.php';
if (hasFooV1BeIncluded()) { // returns true if the "foo-v1/package" should be used, returns false otherwise.
    require __DIR__ . '/../foo-v1/package/vendor/autoload.php';
} else {
    require __DIR__ . '/../foo-v2/package/vendor/autoload.php';
}
```
We can't add the both "foo-v1/package" and the "foo-v2/package" to the composer.json of the main (root) package because:
1) The predicate hasFooV1BeIncluded() can be arbitrary complex (e.g. depend from the current time).
2) The sub-packages may define duplicated names (e.g. functions, classes etc).

Scenario 2: use 'include_path' in php.ini:
Suppose that there is a local package called `framework` (/home/foo/framework) and it has the following structure of files:
```sh
composer.json
vendor/
bootstrap.php
```
The /home/foo/framework/bootstrap.php looks like:
```php
<?php
require __DIR__ . '/vendor/autoload.php';
```
The php.ini contains:
```ini
include_path=/home/foo/framework
```
Then somewhere in other directory (say /home/foo/tmp), not belonging to framework we can include the framework and use own packages:
```php
require "bootstrap.php"; // Include framework's dependencies (/home/foo/framework/bootstrap.php)

require __DIR__ . '/vendor/autoload.php';  // includes /home/foo/tmp/vendor/autoload.php
```
Please note that the `framework` may be not published, it may be only private.

**Comment by alcohol** [comment]
None of this makes sense to me. Maybe someone else can help you.

**Comment by markbook2** [comment]
I think it is a bug, I don't think that the "Support" is the valid tag. It probably can be fixed using absolute paths.

**Comment by Seldaek** [comment]
If we pass the absolute path, then it breaks the use case the hash was added for. The reason it's there is that in case you run two composer autoloaders at the same time, we don't want to include the same file from the same package twice, even if it's installed in two different places, as it tends to cause duplicate function definition fatal errors.

The solution for you is to make sure test1/composer.json and test2/composer.json have a "name" key defined with different name and then I think they should resolve to different hashes.
