### ISSUE TITLE
Composer deleting my project files

### ISSUE THREAD

**Issue by GBeushausen** [composer/composer#6309]
I've come accross a very strange composer behaviour. Unfortunatly i cannot provide any files or proof.

I'm using composer inside a vagrant box running Ubuntu 16.04 using Puphpet under Windows.

I use a private repository using git. I manually changed those files in the vendor folder, until they worked as i wanted and then copied the changes to my original project, commited them to git and came back to my project running composer update.

Of course it complained that there where manual changes and i said i want to overwrite them. Unfortunatly i also had those files open in Atom and composer wasn't able to delete those files, because Windows was not allowing it due to the files still being open by another program.

So i closed all those applications and re-runned composer update again.

It then complained again that there are changes and if i would like to overwrite them. Unfortunatly i didn't looked carefully, because i thought it was related to my own repository. After saying yes, i saw, that the files composer mentioned where not related to the vendor directory, but to my /puphpet directory. Composer then deleted many of my vagrant related files.

This not being enough, it cluttered up my source code files in my project with nonsense. For example my class "CustomerController" was renamed to "CustomerVagrantController". 

What could this strange behaviour be?

**Comment by alcohol** [comment]
Does not sound like anything Composer would do. We do not rename classes or files, ever.
