### ISSUE TITLE
Extremely slow when writting packages.json into cache

### ISSUE THREAD

**Issue by rezariantono** [composer/composer#6310]
My `composer.json`:

```
{
    "require": {
        "hirak/prestissimo": "^0.3",
        "laravel/installer": "^1.3"
    }
}

```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK

```

When I run this command:

```
composer update or composer require jenssegers/mongodb --verbose -vvv --profile

```

I get the following output:

```
Writing /home/vagrant/.composer/cache/repo/https---packagist.org/packages.json into cache
```

Its been more than an hour and still there, cancelling and repeating did not help.

I'm running composer in Ubuntu 16.04 vagrant box.

Any idea why?

**Comment by staabm** [comment]
could you check with `strace` what the process is doing right nw?

**Comment by rezariantono** [comment]
Is this what you mean?

I run `strace -p 1869 -s 99`

Got this result:
`
strace: Process 1869 attached
select(8, [7], [], [], {0, 436175})     = 0 (Timeout)
rt_sigaction(SIGPIPE, NULL, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f5867ae9390}, 8) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f5867ae9390}, NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f5867ae9390}, NULL, 8) = 0
select(8, [7], [], [], {1, 0})          = 0 (Timeout)
rt_sigaction(SIGPIPE, NULL, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f5867ae9390}, 8) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f5867ae9390}, NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f5867ae9390}, NULL, 8) = 0
select(8, [7], [], [], {1, 0})          = 0 (Timeout)
rt_sigaction(SIGPIPE, NULL, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f5867ae9390}, 8) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f5867ae9390}, NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f5867ae9390}, NULL, 8) = 0
select(8, [7], [], [], {1, 0})          = 0 (Timeout)
rt_sigaction(SIGPIPE, NULL, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f5867ae9390}, 8) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f5867ae9390}, NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f5867ae9390}, NULL, 8) = 0
select(8, [7], [], [], {1, 0})          = 0 (Timeout)
rt_sigaction(SIGPIPE, NULL, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f5867ae9390}, 8) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f5867ae9390}, NULL, 8) = 0
poll([{fd=7, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f5867ae9390}, NULL, 8) = 0
select(8, [7], [], [], {1, 0}^Cstrace: Process 1869 detached
 <detached ...>
`

**Comment by alcohol** [comment]
Vagrant issue, not Composer.
