### ISSUE TITLE
Version of root package not detected

### ISSUE THREAD

**Issue by IchHabRecht** [composer/composer#6311]
My `composer.json`:

https://github.com/sebastianbergmann/phpunit/blob/master/composer.json

When I run this command:

```
composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable -vvv 
```

See https://ci.appveyor.com/project/helhum/phpunit/build/1.0.7/job/l2rbao080bvoo7a7#L43

I get the following output:

```
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - phpunit/phpunit-mock-objects 4.0.1 conflicts with phpunit/phpunit[**No version set (parsed as 1.0.0)**].
    - phpunit/phpunit-mock-objects 4.0.0 requires sebastian/exporter ^2.0 -> satisfiable by sebastian/exporter[2.0.0, 2.0.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for phpunit/phpunit No version set (parsed as 1.0.0) -> satisfiable by phpunit/phpunit[No version set (parsed as 1.0.0)].
    - Installation request for phpunit/phpunit-mock-objects ^4.0 -> satisfiable by phpunit/phpunit-mock-objects[4.0.0, 4.0.1].
```

And I expected this to happen:
Version of phpunit/phpunit should be 6.1.x-dev as defined in its branch alias

**Comment by curry684** [comment]
The behavior is on purpose for a bunch of good reasons. The root package is technically 'versionless', but set to `1.0.0` so it practically fulfills every requirement that could be thrown against it, and circular dependencies are explicitly guarded. Not sure we've ever seen a package that via a dependency conflicts with itself though  😆 

A conflict with the root package should just always be explicitly ignored, as it should indeed be 'versionless'.

**Comment by helhum** [comment]
@curry684 See discussion here: #5942 and the fix here e54c7478ee1207e60b0a345391a80b3511886429

To clarify the case:

We want to test PHPUnit dev-master on [Appveyor](https://ci.appveyor.com/project/helhum/phpunit/build/1.0.7/job/l2rbao080bvoo7a7#L40)

As you can see, the output of `git branch --no-color --no-abbrev -v` is
`* (HEAD detached at ef7c6aa68) ef7c6aa684e284970cae15e2f045d32678dc2036 Add Appveyor build file`

in contrast to

`* (HEAD detached at FETCH_HEAD) ef7c6aa684e284970cae15e2f045d32678dc2036 Add Appveyor`

Where composer correctly identifies the root package being on dev-master.

So I think the VersionGuesser can rightfully be improved here.

Meanwhile we set the version of the root package with `COMPOSER_ROOT_VERSION`, which solves our issue with the Appveyor build for now.

> A conflict with the root package should just always be explicitly ignored, as it should indeed be 'versionless'.

Yeah, well, it currently isn't. :-)

**Comment by curry684** [comment]
I see your case and problem, never argued it  :)

**Comment by alcohol** [comment]
This is why `COMPOSER_ROOT_VERSION` exists in the first place.

**Comment by IchHabRecht** [comment]
Sorry, but I have to disagree here. I don't think it is very helpful to enforce the definition of `COMPOSER_ROOT_VERSION`. I still think the parsing of composer is broken with current Git version. As you can see in the linked tickets, composer was always changed to be able to find the correct version on its own. Why should this behaviour changed by now and argue, the root package has to care about that itself?

I don't understand why you have closed this ticket as it would be solved by merging the pull request.

**Comment by alcohol** [comment]
Alright. The description of the problem and proposed solution did not really match in my opinion. Basically as I understand it now, you want to loosen the pattern matching to detect a `detached` state, after which we will try to do a version detection based on tags. Whether or not this is a good idea is debatable, considering a detached state could just be some random commit that does not refer to any tag. Then again, it won't make much of a difference either since in that case we can't really guess the version anyway.

**Comment by helhum** [comment]
> after which we will try to do a version detection based on tags

Nope. What we want to achieve is a detection based on a branch:

https://github.com/composer/composer/blob/master/src/Composer/Package/Version/VersionGuesser.php#L128-L133

All braches are fetched and composer iterates over the detected branches.
Then with a `git rev-list sha1..master` it is confirmed that the current sha1 is within the master branch, which enables branch version resolving (using extra/branch-alias)

**Comment by alcohol** [comment]
Right, that is an option too. Thanks for clarifying at least.
