### ISSUE TITLE
Consider hiding the progress bar with environment variables

### ISSUE THREAD

**Issue by jleeothon** [composer/composer#6313]
Just like there is `COMPOSER_NO_INTERACTION` ([link](https://getcomposer.org/doc/03-cli.md#composer-no-interaction)), which is particularly useful in scripting with `composer`, would it make sense to be able to hide the progress bar e.g. (`COMPOSER_NO_PROGRESS`)? This would be useful when we don't have a proper terminal that would print it nicely.

**Comment by curry684** [comment]
Actually I think `COMPOSER_NO_INTERACTION` should imply `--no-progress` automatically.

**Comment by alcohol** [comment]
Not sure if it does, the env conversion does not take place for all keys automatically:
https://github.com/composer/composer/blob/master/src/Composer/Config.php#L218-L219

**Comment by alcohol** [comment]
Ah but it is taken into account here:
https://github.com/composer/composer/blob/master/src/Composer/Console/Application.php#L177-L179

**Comment by jleeothon** [comment]
Hi @alcohol, the pieces of code you pointed at are relevant for `--no-interaction`, which—unless it is implicit within the same setting—is not the same as `--no-progress`. This ticket asks about the `--no-progress` setting.

It is worth to note that this is not an option to `composer` but rather an option to commands such as `install`, `require`, and others; i.e. you write `composer --no-interaction install `--no-progress etc etc`.

**Comment by curry684** [comment]
Just to clarify: my comment implied I think it *should* work like that, and it currently isn't. I just feel like 'no interaction' should mean no interaction at all. Keeping you up to date on progress is also interaction to me, it has no use unless a user is at the keyboard who could also answer questions.

**Comment by alcohol** [comment]
I guess you can submit a PR for this. Though I do not quite understand why people want to have env variables for things you can just control using a `--flag`.

**Comment by curry684** [comment]
Main usecase for this one is CI config files. I've seen `.travis.ci.yml` files that wasted more characters on `--no-progress --no-interaction` flags than actual config. I see the case there for readability.

**Comment by alcohol** [comment]
Fair enough.
