### ISSUE TITLE
Plugins vs Scripts. Autoload issue.

### ISSUE THREAD

**Issue by neomerx** [composer/composer#6315]
[Scripts](https://getcomposer.org/doc/articles/scripts.md#defining-scripts) defined in `composer.json` enjoy application code and external dependencies loaded on execution while [plugins](https://getcomposer.org/doc/articles/plugins.md) don't. Thus the following code works in scripts but not in plugins
```php
    $appClass = '\\App\\Application';
    $stuff = (new $appClass())->getSomeGreatStuff();
```
What is the proper way to make it work in plugins?

I tried  the following `PluginInterface::activate` (basically load `autoload.php` as we usually do)
```php
public function activate(Composer $composer, IOInterface $ioInterface)
{
    // use application auto loader otherwise no app classes will be visible for us
    $autoLoaderPath = $composer->getConfig()->get('vendor-dir') . DIRECTORY_SEPARATOR . 'autoload.php';
    if (file_exists($autoLoaderPath) === true) {
        require_once $autoLoaderPath;
    }
}
```
And the command works. BUT

When I run this command:

```
composer list -vvv
```

I get the following output:

```

Composer version 1.4.1 2017-03-10 09:29:45

        ...

[Symfony\Component\Debug\Exception\FatalThrowableError]
Call to undefined method Composer\Command\ScriptAliasCommand::isHidden()


Exception trace:
() at /..../vendor/symfony/console/Descriptor/ApplicationDescription.php:115
Symfony\Component\Console\Descriptor\ApplicationDescription->inspectApplication() at /..../vendor/symfony/console/Descriptor/ApplicationDescription.php:82
Symfony\Component\Console\Descriptor\ApplicationDescription->getCommands() at /..../vendor/symfony/console/Descriptor/TextDescriptor.php:194
Symfony\Component\Console\Descriptor\TextDescriptor->describeApplication() at /..../vendor/symfony/console/Descriptor/Descriptor.php:55
Symfony\Component\Console\Descriptor\Descriptor->describe() at /..../vendor/symfony/console/Helper/DescriptorHelper.php:72
Symfony\Component\Console\Helper\DescriptorHelper->describe() at phar:///usr/bin/composer/vendor/symfony/console/Command/ListCommand.php:81
Symfony\Component\Console\Command\ListCommand->execute() at phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php:267
Symfony\Component\Console\Command\Command->run() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:846
Symfony\Component\Console\Application->doRunCommand() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:191
Symfony\Component\Console\Application->doRun() at phar:///usr/bin/composer/src/Composer/Console/Application.php:227
Composer\Console\Application->doRun() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:122
Symfony\Component\Console\Application->run() at phar:///usr/bin/composer/src/Composer/Console/Application.php:100
Composer\Console\Application->run() at phar:///usr/bin/composer/bin/composer:54
require() at /usr/bin/composer:24
```

As you can see some of the classes are taken from `vendor` and some from `phar`.

So back to my question. What is the proper way to get application classes in plugins just like in scripts?

**Comment by alcohol** [comment]
Plugins are supposed to extend Composer logic. All of their login should be in the plugin. Making them depend on dependencies that are listed as requirements of a project makes no sense from a plugin perspective.

**Comment by stof** [comment]
Plugins are running at a time where the application code is not yet available (other dependencies are not yet installed). So calling your application would not work

**Comment by neomerx** [comment]
@stof Plugins are executed on every composer run and dependencies already available. An example of that `composer list` shows commands from plugin.

@alcohol Nope. It does make sense. I want a command that caches let's say routes from application. There is no other way to get route settings other than take it from the app.

You both were super helpful. /s

**Comment by alcohol** [comment]
> @alcohol Nope. It does make sense. I want a command that caches let's say routes from application. There is no other way to get route settings other than take it from the app.

Your use case already makes it very clear that you should not be using a Composer plugin. This is clearly a case where you should use a hook in your application instead. Composer has nothing to do with the cache-warmup process of your application.

**Comment by neomerx** [comment]
Do you mean [scripts](https://getcomposer.org/doc/articles/scripts.md)? I've been using both `scripts` and `plugins`. Scripts has a lack of support for arguments and not as good manageable as plugins if I want to add/remove new commands which would be distributes with updates.

To my mind they are both pretty much the same thing: they allow adding user defined commands to composer. And current differences are explained by the fact that scripts are much easier to develop => they used more widely => more stable/less buggy.

And BTW if you fix this issue you could have one implementation for both. I'm personally one step away of adding plugin commands as easy as scripts and only this issue prevent it.

**Comment by alcohol** [comment]
I am pretty confident you do not grasp the distinct difference between plugins and scripts. Also, your use-case is way out of line as far as I am concerned. This falls far outside of the realm of responsibilities one should try to solve with Composer.

**Comment by stof** [comment]
if you have application-level commands, they should be added to an application-level console, not to composer itself.
your issue comes from the fact that you load your project classes in the composer process and this ends up mixing the symfony/console version used by composer with the symfony/console version of your project (some classes being loaded from your project instead of the phar) and this creates incompatibility (totally expected in this case).

**Comment by neomerx** [comment]
@stof I pointed out that some classes are taken from `vendor` and some from `phar` in the original message.

@alcohol @stof Guys you autoload very nicely to scripts why not to be nice to plugins? I'm sure you coud make it :cool: as well :smile: 

For those who bump into this issue. You need to postpone loading your `vendor` from `init` phase to `execution`. In this case it won't make any visible troubles. Also command chaining would also work (you can mix such commands in `scripts`). The only limitation is you cannot easily load commands from application to composer for the reason above. A workaround, I believe should work, is loading something like simple array with scalars and add commands based on these data. The path to such file could be stored in `composer.json` -> `extra` and it will be available on init.

**Comment by stof** [comment]
@neomerx the difference is that scripts have much less impact on composer itself:

- when using a CLI command as the script, it runs as a separate process, so there is no conflict at all
- when using a PHP callable, the project autoloading is loaded only when running scripts, which is much later than the plugin initialization, so the symfony/console classes available in the phar are probably already loaded since a long time.
