### ISSUE TITLE
Feature: Add version constraints for optional dependencies

### ISSUE THREAD

**Issue by bradynpoulsen** [composer/composer#6321]
## Overview

It would be really nice to be able to specify the version constraints for optional dependencies. As an example, let's use `aws/aws-sdk-php`:

### 1. Library that has optional dependency version constraint needs

I am making a library `john-doe/my-library` where I am supporting the AWS SDK. So I add the following:

```json
{ "suggest": {
    "aws/aws-sdk-php": "^3.0"
} }
```

I add that suggestion because I do optionally provide that support; however, I am only able to support `^3.0`.

### 2. Application that violates dependency's optional sub-dependency version constraints

I have an application with the following dependencies:

```json
{ "requires": {
    "john-doe/my-library": "^1.0",
    "aws/aws-sdk-php": "^2.0"
} }
```

As you can see, the `^2.0` constraint for the AWS SDK is not supported by `john-doe/my-library` but there is no constraint preventing it (only a suggests message that is suppressed since `aws/aws-sdk-php` is already installed)

## Proposal

I suggest adding another level of dependencies called `optional` or `optionally-requires` that is structured the same as `requires`. 

An `optional` dependency will only be resolved during installation if it is accompanied by a `requires` for that dependency in another package.

In the scenario above, `john-doe/my-library` would have the following (which would prevent installing the incompatible `aws/aws-sdk-php ^2.0` versions):

```json
{ "optional": {
    "aws/aws-sdk-php": "^3.0"
} }
```

**Comment by avant1** [comment]
If I understand your case correctly you can use [conflict](https://getcomposer.org/doc/04-schema.md#conflict) section of your package for that:

```json
  "conflict": {
    "aws/aws-sdk-php": "<3.0"
  }
```
This will disallow installing `"aws/aws-sdk-php": "^2.0"` together with your package, and as a result will lead to conflict with (hopefully) clear reason.

And BTW writing version constraint in `suggest` section is not really useful. That value will be shown as a reason why you suggest to install that additional package and what functionality will it make available.

**Comment by alcohol** [comment]
It would be impossible to implement this without breaking BC. Also, this is not what `suggest` was made for.

**Comment by bradynpoulsen** [comment]
@avant1 good idea. I'll give that one a try!
@alcohol I really don't see how adding an `optional` configuration would break BC. The behavior of `suggest` would not have changed. Only new functionality through optional additional configuration

**Comment by alcohol** [comment]
There is no version constraint for suggests as you are suggesting:

```
{ "suggest": {
    "aws/aws-sdk-php": "^3.0"
} }
```

It's `"package/name": "description/reason for suggesting"`.

**Comment by bradynpoulsen** [comment]
@alcohol correct, my description was version `^3.0`. Not that it would actually serve as a constraint (which my example explains that it's suggestion is suppressed because the package is installed and nothing to do with the version in its description). The version constraint is what the `optional` proposal was for

**Comment by bradynpoulsen** [comment]
:)
> Example > 2. Application ...
> As you can see, the ^2.0 constraint for the AWS SDK is not supported by john-doe/my-library but **_there is no constraint preventing it (only a suggests message that is suppressed since aws/aws-sdk-php is already installed)_**
