### ISSUE TITLE
[docs] show on the documentation how to invoke a composer command from an event listener

### ISSUE THREAD

**Issue by Faryshta** [composer/composer#6322]
My `composer.json`:

```json
"scripts": {
    "check-stability": "Listener::check"
}
```
I would like to see on the doc something like this

```php
use Composer\Script\Event;

class Listener
{
     public static function check(Event $event)
     {
            if (/* something */) {
                 $event->getComposer()->run('update', ['no-dev' => true]);
            } else {
                 $event->getComposer()->run('update', ['prefer-dist' => true]);
            }
     }
}
```

so far haven't found anywhere how to call a composer command from a composer event listener.

**Comment by alcohol** [comment]
Calling composer commands from within event listeners is a tricky thing. I really would not want to advocate a bad practice. Hence why you do not see any of this in the documentation.

**Comment by Faryshta** [comment]
@alcohol why not? what if i have custom commands like `deploy` which might do diferent steps on development and production environments.

thats a very valid use case

**Comment by stof** [comment]
@Faryshta I'm not sure such a custom command belongs to Composer. It looks more like scripting deploying and having composer called as one step of it.
Composer is not meant to be a generic task runner.

**Comment by Faryshta** [comment]
@stof i intend for example to write a custom command to run all the neccesary steps to deploy an application on composer 

`composer deploy env=prod`

invokes `composer create-project --no-dev` for example the docs are here https://getcomposer.org/doc/articles/scripts.md

**Comment by alcohol** [comment]
Sounds like you need to learn how to use ansible or puppet.

**Comment by Faryshta** [comment]
i just need to invoke a composer command from a composer listener. I think thats something that should be on the docs since there are many valid use cases for them.

**Comment by alcohol** [comment]
> since there are many valid use cases for them

No.

**Comment by Faryshta** [comment]
Why not? The docs already explain how to invoke random bash and composer scripts but there is no way to do it intelligently or dynamically.
