### ISSUE TITLE
Custom script results in "sh: 1: Bad substitution"

### ISSUE THREAD

**Issue by nikolaposa** [composer/composer#6324]
I have this custom script defined in my `composer.json`:
```
"scripts": {
    "ci-cs": "git fetch; diff_files=`git diff --name-only --diff-filter=d origin/master | xargs`; php-cs-fixer fix --config=.php_cs -v --dry-run --using-cache=no --path-mode=intersection \"${diff_files[@]}\""
  }
```

But when I invoke it I get:
```
sh: 1: Bad substitution
Script git fetch; diff_files=$(git diff --name-only --diff-filter=d origin/master | xargs); printf '%s\n' "${diff_files[@]}"; php-cs-fixer fix --config=.php_cs -v --dry-run --using-cache=no --path-mode=intersection "${diff_files[@]}" handling the ci-cs1 event returned with error code 2
```

I suspect that it has something to do with escaping/parsing this bash command either by Composer or Symfony Process component, because it works when I run it raw from shell.

**Comment by alcohol** [comment]
Why not just write a command class instead? Something along the lines of https://gist.github.com/alcohol/df8e5800e7fa06e277defb51ad381e9b

Anyway, the scripts section was meant for simple short one-liners. Not sure how we could properly escape this use-case you are presenting.

**Comment by nikolaposa** [comment]
Solved it this way:
```
"ci-cs": "git fetch; php-cs-fixer fix --config=.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=d origin/master | xargs`"
```

`@` obviously cannot be used in script alias context. Feel free to close this issue.
