### ISSUE TITLE
Running “platform build” on platform.sh Drupal project throwing composer.phar not found error

### ISSUE THREAD

**Issue by shabananavas** [composer/composer#6327]
I'm trying to setup a platform.sh Drupal project on my local and I've got platform working and composer as well. However, when I run "platform build" I'm getting the following error claiming it can't find composer.phar.

I can run composer install/update just fine for any project. So I'm wondering why it is throwing an error here. I'm on a Windows 10 and am using cygwin.

```
-bash-4.4$ platform build
Building application myproject (runtime type: php:7.0)
Installing php dependencies with 'composer': drush/drush

C:\myproject\.platform\local\deps\php>php.exe composer.phar install --no-progress --prefer-dist --optimize-autoloader --no-interaction
Could not open input file: composer.phar


  [RuntimeException]
  The command failed with the exit code 1: composer install --no-progress --p
  refer-dist --optimize-autoloader --no-interaction
```

**Comment by alcohol** [comment]
This is not the right place to ask for help with drupal or platform.sh.
