### ISSUE TITLE
Composer complains about modified files outside vendor package that is being removed

### ISSUE THREAD

**Issue by nikolaposa** [composer/composer#6331]
I'm trying to run `composer remove` of a package, but the Composer complains that there are modified files in it even if there are not:
```
Updating dependencies (including require-dev)                                               
Package operations: 0 installs, 0 updates, 2 removals
  - Removing orchard-ondemand/arbor-sdk-php (1.0.4)
    The package has modified files:
    M composer.json
    Discard changes [y,n,v,d,?]? 
```

Modified `composer.json` is project's `composer.json` file that was modified during `composer remove` execution. 

I've also tried to modify some other random files in the project and Composer complains for them to when removing some package.

**Comment by Seldaek** [comment]
Did you remove the .git directory inside `vendor/orchard-ondemand/arbor-sdk-php`? That's the only thing I could imagine that would cause that, because then when it checks for git changes it would end up looking at your project's git repo.

**Comment by nikolaposa** [comment]
I haven't removed it. By the way, after I enter `y`, I get this error message: 

```
[RuntimeException]                                                                                                
  Could not delete /home/vagrant/arbor/di/vendor/orchard-ondemand/arbor-sdk-php/.git/hooks/applypatch-msg.sample:
```

**Comment by Seldaek** [comment]
This is very weird.. As if the cwd argument didn't work when composer starts the `git status` process inside `vendor/.../...`. Unfortunately it is quite hard to help you unless there is a clear way to reproduce. I see it happens in vagrant, wonder if maybe it's related to that. We've had many VM related issues over the years. Maybe make sure virtualbox and related are up to date?

**Comment by nikolaposa** [comment]
Yeah, it seems that this is some Vagrant-specific issue. I'll try to update virtualbox.

**Comment by nikolaposa** [comment]
So this was really weird. I deleted package directory manually, install it again (`composer install`), and after that `composer remove` worked.

**Comment by Seldaek** [comment]
Ok.. one more for the book of weird VM bugs then :)
