### ISSUE TITLE
Installing laravel via composer issue:The process has been signaled with signal "5".

### ISSUE THREAD

**Issue by mehdizahrane** [composer/composer#6333]
Hello everyone, i hope someone can help me.
Each time i try to install laravel via comoser it generates an exception 
This is the command that i type : composer global require "laravel/installer"
And this the exception : 

`[Symfony\Component\Process\Exception\RuntimeException]  
  The process has been signaled with signal "5". `

I saw this issue [composer/composer#2146](https://github.com/composer/composer/issues/2146)
but i couldn't understand, because as far as i understood we aren't facing the same issue.

PS: My OS is 'OS X EL CAPITAIN'

**Comment by curry684** [comment]
SIGTRAP is not a Composer issue, it's a lowlevel debugger in your OS intervening on something in the PHP executables itself. Disable any debugging tools you have and/or try upgrading PHP.

**Comment by kaisuketrax** [comment]
Having the same problem, I don't have any debugging tools enabled and I upgraded to the latest php version using composer. 

This is the first time I'm having this issue and I've used composer for over a year now.

This is the message error and using OSX El Capitan 10.11.3 :

`Changed current directory to /Users/nathalie/.composer

                                                          
  [Symfony\Component\Process\Exception\RuntimeException]  
  The process has been signaled with signal "5".          
                                                          

global <command-name> [<args>]...`

**Comment by mehdizahrane** [comment]
@kaisuketrax me too, I don't have any debugger enabled, I used to run this command in Ubuntu, and I didn't face any problems, I changed my php version and still the same issue, this is frustrating, if there's any alternative solutions, that would be great.

**Comment by kaisuketrax** [comment]
I erased my hard drive and installed a fresh version of OS X now it works without issues ... really annoying to go that far for this but now I'll pay more attention to what I'm doing with the terminal !

**Comment by mehdizahrane** [comment]
@kaisuketrax I think I will do the same thing, I couldn't find any solution.

**Comment by muyexi** [comment]
Try [this](https://laravel.com/docs/5.4#installing-laravel): `composer create-project --prefer-dist laravel/laravel blog`

**Comment by muyexi** [comment]
The dependency is broken. 

```
$ composer install -vvv
Reading /Users/muyexi/.composer/composer.json
Loading config file /Users/muyexi/.composer/composer.json
Checked CA file /private/etc/ssl/cert.pem: valid
Executing command (/Users/muyexi/.composer): git branch --no-color --no-abbrev -v
Executing command (/Users/muyexi/.composer): git describe --exact-match --tags
Executing command (/Users/muyexi/.composer): git log --pretty="%H" -n1 HEAD
Executing command (/Users/muyexi/.composer): hg branch
Executing command (/Users/muyexi/.composer): fossil branch list
Executing command (/Users/muyexi/.composer): fossil tag list
Executing command (/Users/muyexi/.composer): svn info --xml
Failed to initialize global composer: The process has been signaled with signal "6"
```

```
$ svn
dyld: Library not loaded: /usr/local/opt/sqlite/lib/libsqlite3.0.8.6.dylib
  Referenced from: /usr/local/bin/svn
  Reason: image not found
[1]    71050 abort      svn
```

So fix with `brew reinstall sqlite svn`

**Comment by vladyslavstartsev** [comment]
@muyexi thanks! `-vvv` and `brew reinstall svn` helped me

**Comment by pinguinoholdings** [comment]
Thank you.  I had to run `brew upgrade` and then `brew reinstall svn`
