### ISSUE TITLE
The "" directory does not exist.

### ISSUE THREAD

**Issue by knoxgon** [composer/composer#6343]
This issue is killing me. I'm trying to install composer but I end up, getting this error.
```
[InvalidArgumentException]        
  The "" directory does not exist.
```
My composer.json file, though, looks like the following and I don't have parameters that are empty. Nothing specific is being pointed at.

```json
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "laravel/socialite": "^3.0",
        "laravel/tinker": "~1.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    }
}
```

**Comment by doctorthompson** [comment]
Escape your backslashes (in psr-4 namespaces and Illuminate paths) and the nested double-quotes in the post-root-package-install script and it should work fine.

```json
{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
	"require": {
		"php": ">=5.6.4",
		"laravel/framework": "5.4.",
		"laravel/socialite": "^3.0",
		"laravel/tinker": "~1.0"
	},
	"require-dev": {
		"fzaninotto/faker": "~1.4",
		"mockery/mockery": "0.9.",
		"phpunit/phpunit": "~5.7"
	},
	"autoload": {
		"classmap": ["database"],
		"psr-4": {
			"App\\": "app/"
		}
	},
	"autoload-dev": {
		"psr-4": {
			"Tests\\": "tests/"
		}
	},
	"scripts": {
		"post-root-package-install": ["php -r \"file_exists('.env') || copy('.env.example', '.env');\""],
		"post-create-project-cmd": ["php artisan key:generate"],
		"post-install-cmd": ["Illuminate\\Foundation\\ComposerScripts::postInstall", "php artisan optimize"],
		"post-update-cmd": ["Illuminate\\Foundation\\ComposerScripts::postUpdate", "php artisan optimize"]
	},
	"config": {
		"preferred-install": "dist",
		"sort-packages": true
	}
}
```

**Comment by Seldaek** [comment]
Gonna assume @doctorthompson was right and close this for now, but if not and you still experience the issue then please give us the command you are running, and the full output of it, and make sure you run it with the `-vvv` flag so you get a backtrace as well.

**Comment by Top-Developer** [comment]
What do you mean exactly "Escape your backslashes (in psr-4 namespaces and Illuminate paths) and the nested double-quotes in the post-root-package-install script and it should work fine."?
I am sorry for my poor English.
Would you kindly explain in more detail?

**Comment by Seldaek** [comment]
It means `Foo\Bar` in json should be `Foo\\Bar` (escaped backslashes)

**Comment by bjornandersson** [comment]
I have the same problem even though the aforementioned lines were already escaped. Here's my output:

Reading ./composer.json
Loading config file ./composer.json
Checking CA file /etc/ssl/certs/ca-certificates.crt
Executing command (/mnt/c/dev/codeball/webserver/codeball): git branch --no-color --no-abbrev -v
Reading /home/bjoand/.composer/composer.json
Loading config file /home/bjoand/.composer/composer.json
Reading /mnt/c/dev/codeball/webserver/codeball/vendor/composer/installed.json
Reading /home/bjoand/.composer/vendor/composer/installed.json
Reading ./composer.lock
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Reading ./composer.lock
Resolving dependencies through SAT
Dependency resolution completed in 0.002 seconds
Analyzed 183 packages to resolve dependencies
Analyzed 515 rules to resolve dependencies
Nothing to install or update
Generating autoload files
> post-install-cmd: Illuminate\Foundation\ComposerScripts::postInstall
> post-install-cmd: php artisan optimize
Executing command (CWD): php artisan optimize


  [InvalidArgumentException]
  The "" directory does not exist.


Script php artisan optimize handling the post-install-cmd event returned with an error


  [RuntimeException]
  Error Output:


Exception trace:
 () at /usr/share/php/Composer/EventDispatcher/EventDispatcher.php:209
 Composer\EventDispatcher\EventDispatcher->doDispatch() at /usr/share/php/Composer/EventDispatcher/EventDispatcher.php:94
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at /usr/share/php/Composer/Installer.php:337
 Composer\Installer->run() at /usr/share/php/Composer/Command/InstallCommand.php:134
 Composer\Command\InstallCommand->execute() at /usr/share/php/Symfony/Component/Console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /usr/share/php/Symfony/Component/Console/Application.php:841
 Symfony\Component\Console\Application->doRunCommand() at /usr/share/php/Symfony/Component/Console/Application.php:189
 Symfony\Component\Console\Application->doRun() at /usr/share/php/Composer/Console/Application.php:166
 Composer\Console\Application->doRun() at /usr/share/php/Symfony/Component/Console/Application.php:120
 Symfony\Component\Console\Application->run() at /usr/share/php/Composer/Console/Application.php:99
 Composer\Console\Application->run() at /usr/bin/composer:44

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

**Comment by curry684** [comment]
```
Script php artisan optimize handling the post-install-cmd event returned with an error
```
This is not a Composer issue, it's the Laravel `artisan` command. We cannot help you here.

**Comment by sebastiaanluca** [comment]
Should anyone come across this issue, just had the same when writing tests for a Laravel package (so not the result of running `artisan`). Tests were working fine and suddenly threw the aforementioned error `The "" directory does not exist.`. Debugging led me to see it happening during framework boot. Turned out it was an autoloader issue and removing the `vendor` directory plus reinstalling packages "fixed" it.
