### ISSUE TITLE
failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date

### ISSUE THREAD

**Issue by cong520** [composer/composer#6347]
The "https://packagist.org/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Name or service not known
failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known
https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date

  [Composer\Downloader\TransportException]
  The "http://packagist.org/p/phpoffice/phpexcel%24fc331f1ad5b3634d5470ce0376
  000baee09a598a67e1b2bc80bf895b6f500a55.json" file could not be downloaded:
  php_network_getaddresses: getaddrinfo failed: Name or service not known
  failed to open stream: php_network_getaddresses: getaddrinfo failed: Name o
  r service not known

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

**Comment by ay4great** [comment]
this my exact challenge can someone help please

**Comment by stof** [comment]
`php_network_getaddresses: getaddrinfo failed: Name or service not known` means that DNS resolution failed. Check your network setup.
