### ISSUE TITLE
Parsing a composer.json file

### ISSUE THREAD

**Issue by m1guelpf** [composer/composer#6348]
I want to parse a composer.json file in php, and make a function to check if a version is inside the update range of composer. Is there a function I can reuse? A PHP package?

**Comment by stof** [comment]
if you just want to parse the file, use ``json_decode``. It is just a JSON file (with a specific structure).

Checking that a given version matches a constraint can be done using composer/semver, once you have the version and the constraint (as this is the goal of the package).
However, I'm not sure I understand what you mean when saying `check if a version is inside the update range of composer`

**Comment by m1guelpf** [comment]
I mean, I have a `$composer` variable, and I can do, for example, `$composer->requires->knplabs/github-api` is `^2.2`. Then, I have a list of versions (Maybe 1.1, 2.1.0, 2.1.3, etc.) and I want to check if they are inside the range. For example, `3.0` is not in the range, `1.0` is not in the range but `2.2.1` is.

**Comment by stof** [comment]
well, composer/semver is exactly about that.

```php
var_dump(\Composer\Semver\Server::satisfies('3.0', '^2.2')); // false
var_dump(\Composer\Semver\Server::satisfies('1.1', '^2.2')); // false
var_dump(\Composer\Semver\Server::satisfies('2.2.1', '^2.2')); // true
```

**Comment by stof** [comment]
you can also use the `satisfiedBy` method, which accepts an array of version as first argument and a constraint as second argument, and returns a filtered array of versions (keeping only versions satisfying the constraint)

**Comment by m1guelpf** [comment]
@stof And how can I know if the version specified is greater than the constraint?

**Comment by m1guelpf** [comment]
@stof Would this work?
``` php
protected function greater($version, $constraints)
    {
        $versionParser = new VersionParser();
        $provider = new Constraint('>', $versionParser->normalize($version));
        $constraints = $versionParser->parseConstraints($constraints);
        return $constraints->matches($provider);
    }
```

**Comment by stof** [comment]
What do you mean by `greater than the constraint` ? Versions cannot be greater or lesser than a constraint. Constraints and versions are not comparable together.

The only relation between a constraint and a version is that a version satisfies it or no.

**Comment by stof** [comment]
and this is exactly what I said: ``greater`` is undefined in this case, as both objects (Version and Constraint) are not comparable. (constraints are not even comparable together, except for equality, as there is no sorting defined for them, which would be quite hard)

**Comment by m1guelpf** [comment]
@stof But `^2.2` is a number range, rigth?

**Comment by stof** [comment]
it is a version constraint. Version constraints can be much more complex than version ranges. they can be a union of several ranges. In this case, how would you compare the version with the version range ?
And what happens when the version satisfies the constraint ? Is it lesser, equal or greater than the constraint ? Comparing unrelated concepts just does not make sense.
