### ISSUE TITLE
Gitlab subgroup

### ISSUE THREAD

**Issue by MatTheCat** [composer/composer#6349]
In my `composer.json`

```json
{
    "type": "gitlab",
    "url": "http://192.168.1.76/dnl/bundle/translation-bundle"
}
```

triggers an API call to http://192.168.1.76/dnl/api/v3/projects/bundle%2Ftranslation-bundle

It should be http://192.168.1.76/api/v3/projects/dnl%2Fbundle%2Ftranslation-bundle

**Comment by stof** [comment]
looks like the detection of the gitlab root failed in this case

**Comment by MatTheCat** [comment]
Subgroups came with GitLab 9 released March 22 so it's understandable.

It seems only [`GitLabDriver::initialize()`](https://github.com/composer/composer/blob/master/src/Composer/Repository/Vcs/GitLabDriver.php#L78) is at fault.

**Comment by MatTheCat** [comment]
Seems like `(?P<repo>[^/]+?)(?:\.git|/)?$` should be `(?P<repo>.+(?=\.git$|/$))` [here](https://github.com/composer/composer/blob/master/src/Composer/Repository/Vcs/GitLabDriver.php#L69).

**Comment by delamart** [comment]
I just hit this limitation reorganizing my projects in sub groups.
I'm going to have to move back until this is fixed.

**Comment by alcohol** [comment]
Can you link the documentation to how subgroups work please?

**Comment by delamart** [comment]
Here is the official doc: https://docs.gitlab.com/ce/user/group/subgroups/

**Comment by alcohol** [comment]
Thanks :-)

**Comment by Seldaek** [comment]
@delamart @MatTheCat I'd appreciate if you can double check the fix works using `composer self-update --snapshot`

**Comment by delamart** [comment]
```
$ composer --version
Composer version 1.5-dev (5efa503e4ecdedc52a964c86e2793c3bbc4a1303) 2017-05-17 06:22:16
```
**Confirmed it works** with both type:`gitlab`, url:`git@gitlab.com/a/b/repo.git` and  type:`gitlab`, url:`https://gitlab.com/a/b/repo.git` repositories. 

And rollback to version `1.4.1` fails as expected.

Thanks for the work, when can we expect this to be available composer stable ?

**Comment by alcohol** [comment]
It will be in the next tagged release(s).

**Comment by Seldaek** [comment]
It's in master so will be part of the 1.5.0 release whenever it happens.

**Comment by delamart** [comment]
Ok, hopefully soon.
