### ISSUE TITLE
version numbers missing from `show` command on Travis

### ISSUE THREAD

**Issue by craue** [composer/composer#6351]
`composer show` prints a list of installed dependencies including their version numbers (and description). But on Travis, I only get [the output](https://travis-ci.org/craue/CraueFormFlowBundle/jobs/221327458#L213) as if `composer show --name-only` would be called.

**Comment by Seldaek** [comment]
I'm assuming this is a terminal width detection issue.. if you could try again after a `composer self-update --snapshot` that'd be great, to see if it helps or not,

**Comment by craue** [comment]
@Seldaek, [it does](https://travis-ci.org/craue/CraueConfigBundle/jobs/221972010#L216). Thanks.
