### ISSUE TITLE
Path repositories not used when installing dependencies of a dependency

### ISSUE THREAD

**Issue by pylebecq** [composer/composer#6352]
Hi,

I'm currently developping an application that have a dependency on a private package stored in the same git repository, which also has a dependency stored in the same repository: app depends on package1, which depends on package2. Everything is stored in the same place.

My `composer.json` for the app:

```json
{
    "name": "test/app",
    "type": "project",
    "require": {
        "test/package1": "@dev"
    },
    "repositories": [
        { "type": "path", "url": "../packages/*" }
    ]
}
```

My `composer.json` for the package1:

```json
{
    "name": "test/package1",
    "type": "library",
    "require": {
        "test/package2": "@dev"
    },
    "repositories": [
        { "type": "path", "url": "../*" }
    ]
}
```

My `composer.json` for the package2:

```json
{
    "name": "test/package2",
    "type": "library",
    "require": {}
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.test/package1 : unbound version constraints (@dev) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command in my app directory:

```
composer install
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for test/package1 @dev -> satisfiable by test/package1[dev-master].
    - test/package1 dev-master requires test/package2 @dev -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

And I expected this to happen:

Packages should install successfully because my "path" repository with the glob contains both packages.

If I try to run `composer install` in package1 everything runs correctly because there is also a repository defined. I know it's not taken into account when running `composer install` from app because "repositories" is root-only but I keep it because I need it when I'm coding/running tests on package1 directly.

If I run the same setup with toran proxy instead of a path repository, it works fine: the toran proxy defined in app is used to resolve test/package2. Only when using a "path" repository it does not work.

I joined a zip file with the very basic setup I describe for you to try out if you want to :
[composer-path-repo.tar.gz](https://github.com/composer/composer/files/916613/composer-path-repo.tar.gz)
Extract it with `tar zxvf composer-path-repo.tar.gz` and then go into the app folder and run `composer install`.

Thanks

**Comment by Seldaek** [comment]
That's a pretty simple case of the https://getcomposer.org/doc/faqs/why-can%27t-composer-load-repositories-recursively.md :)

**Comment by pylebecq** [comment]
Sorry to insist but I don't understand how it answers the issue I have.

I don't want to load repositories recursively.

I just want my package2 to be resolved correctly, because my repository from my app matches this package. I don't mind the repository from package1 not being loaded because it points to the exact same path. Like I said, I only keep it there because I need when developping directly in this package.

If it's less confusing, here is an example with only one repository, and it does not work, and I think it should.

My filesystem tree:

```
.
├── app
│   └── composer.json
└── packages
    ├── package1
    │   └── composer.json
    └── package2
        └── composer.json

4 directories, 3 files
```

My composer.json for app:

```json
{
    "name": "test/app",
    "type": "project",
    "require": {
        "test/package1": "@dev"
    },
    "repositories": [
        { "type": "path", "url": "../packages/*" }
    ]
}
```

My `composer.json` for the package1:

```json
{
    "name": "test/package1",
    "type": "library",
    "require": {
        "test/package2": "@dev"
    }
}
```

My `composer.json` for the package2:

```json
{
    "name": "test/package2",
    "type": "library",
    "require": {}
}
```

Inside the app folder, if I run `composer install`, I still have the same error message.

**Comment by stof** [comment]
The issue in your case is the minimum-stability. By default, only stable packages are allowed by Composer, and only the root package can change this. Dependencies cannot force composer to select a dev version of a package if the root package does not allow it.
And I suspect that your package2 is detected as a dev version.

**Comment by pylebecq** [comment]
I see.

It means I need to set the minimum stability to dev, which I do not like because I'm afraid other developers will add many dependencies as dev even for properly versionned community packages.
Or maybe I can just set a fake stable version number in the composer.json of my packages that I will never update and set my requirements on this version number. I will try that.

Thanks for the help guys.

**Comment by Seldaek** [comment]
Ah yeah sorry I misunderstood at first. Another option is to combine
prefer-stable with minimum-stability to avoid everything going to dev.

**Comment by pylebecq** [comment]
All right, thanks for the help and for the hard work on composer.

**Comment by aburcheri** [comment]
I have a similar problem and can't resolve it: I have a git repository with my entities in a zf3 project with doctrine2. My composer.json looks like this:
`"repositories": [
        {
            "type": "git",
            "url": "git@github.com:blabla/BMEntities.git"
        },
        {
            "type": "path",
            "url": "../BMEntities"
        }
    ],`
After composer update : Nothing to install or update, but the folder does not exist in vendor.
