### ISSUE TITLE
Plugin registration from root package.

### ISSUE THREAD

**Issue by Dreimus** [composer/composer#6354]
Hello ! 

I'd like to register a plugin class into my root package so I can add custom installers and commands available before any vendor installation.
Is it possible to include my class somewhere before composer starts `install | update` command ?

Thanks !

**Comment by Dreimus** [comment]
Well, I have just found a way to do so : I've placed a folder in my root package, and I have registered it as a local private package : 

    
    "repositories": [
      {
        "type": "path",
        "url": "src/Composer/Plugin/"
      }
    ],
    "require": {
      "my/custom-plugin": "1.0.0"
    }

I'll do with this, if you have any suggestion to optimize, please notice me !

**Comment by Seldaek** [comment]
That seems like a decent solution.
