### ISSUE TITLE
Is version 0.0.x an special case for composer?

### ISSUE THREAD

**Issue by respinoza** [composer/composer#6358]
I am using composer 1.4.1

We have some packages tagged as 0.0.2, 0.0.3, etc.
I noticed that when you include them with the caret, for example, using ^0.0.2 it doesn't allow me to install version 0.0.3
I could also confirm this with the semver test site (see https://semver.mwl.be/#?package=payjp%2Fpayjp-php&version=%5E0.0&minimum-stability=stable)

I was expecting the 0.0.x behavior to be the same as for example 0.1.x, which means if I have a constraint like ^0.1.2, it means I can use version 0.1.2 and up but not 0.2.x

Is this a special case or am I hitting a bug here?

Thank you.

**Comment by stof** [comment]
`^` allows update as long as it does not change the first non-zero part of the version number.
So `^0.0.2` allows to go to `0.0.2.1` but not to `0.0.3`

**Comment by stof** [comment]
And this is not a bug. the code implementing it explicitly documents it as behaving this way (well, it says `no update for 0.0.X` because it does not use examples with 4 segments in the version): https://github.com/composer/semver/blob/1.4.2/src/VersionParser.php#L364

**Comment by respinoza** [comment]
Thank you, I understand now.
