### ISSUE TITLE
composer remove doesn't remove dependencies before install

### ISSUE THREAD

**Issue by jnvsor** [composer/composer#6359]
My `composer.json`:

```json
{
    "require-dev": {
        "friendsofphp/php-cs-fixer": "^2.0",
        "kint-php/kint": "^1.0"
    }
}
```

When I run this command on a not-yet-installed-package:

```
composer remove friendsofphp/php-cs-fixer
```

I get the following output:

```
Package "friendsofphp/php-cs-fixer" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - doctrine/annotations v1.4.0 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - doctrine/annotations v1.4.0 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - Installation request for doctrine/annotations (locked at v1.4.0) -> satisfiable by doctrine/annotations[v1.4.0].

Removal failed, reverting ./composer.json to its original content.
```

Essentially, `composer remove` doesn't remove dependencies when `composer install` has yet to be run. This can be demonstrated on any old repo but is most annoying when trying to remove something with dependencies that require a higher version of PHP than the system you're running on, since it's effectively impossible to install without throwing away the lockfile.

Example: https://travis-ci.org/jnvsor/kint/jobs/222157099

**Comment by alcohol** [comment]
Because there is nothing to remove, composer will run an `update` basically. This fails because your PHP version is not supported. You are using a command for a scenario for which it is not intended to be used. Not sure what you are expecting the outcome to be.

**Comment by jnvsor** [comment]
`composer remove` will do an install minus the targeted package ordinarily, and when it's already installed it will remove dependencies too
