### ISSUE TITLE
[PROPOSAL]: Support an "ignore" property in composer.json

### ISSUE THREAD

**Issue by LukeTowers** [composer/composer#6361]
# Introduction
I would like to open this issue as a conversation starter to discuss the possibility of adding the ability to ignore dependencies to Composer.

# Problem Description
First off, what I mean by "ignoring packages" is simply that. A dependency declares that it requires another dependency, but you don't want Composer to load that second dependency for one reason or another. 

In my case, I choose to tell Composer that I don't want that dependency because I already have it elsewhere in the project, it's just that Composer does not know that fact due to the structure of the project as a whole. 

To be specific, I use [OctoberCMS](https://github.com/octobercms/october). OctoberCMS is by itself a PHP CMS that uses Composer. However, it (like most CMSes) supports plugins; and these plugins also use Composer. Now, by default there isn't any problems, we utilize the [wikimedia-merge-plugin](https://github.com/wikimedia/composer-merge-plugin) to merge in every plugin's `composer.json` before running `composer update` from the project root. This works fine and dandy; all of the dependencies are properly loaded and all are stored in the project's main **vendor** directory.

However, not everybody that uses OctoberCMS uses Composer. Thus, if plugins are to be distributed to the entire ecosystem, they must undergo a build process in order to load their dependencies into their own folders so that they can be self contained and not dependent on the user of the OctoberCMS project they will be installed into to be using Composer. This then results in dependencies being loaded into the plugin's **vendor** directory instead of the project's **vendor** directory. 

Unfortunately, this build process fails to take into account all of the dependencies that have already been loaded into October's **vendor** directory (which comes with every OctoberCMS instance, irregardless of whether or not it uses Composer). This results in two negative results:
- Dependencies that have already been included in October's **vendor** directory will be included again within each plugin's **vendor** directory
- Incompatible versions of dependencies can be loaded simultaneously by both October and plugins. For example, October requires `"laravel/framework": "5.1.*"` which loads in dependencies like `"illuminate/support": "5.1.*"`. However, a plugin might attempt to load in something like `"illuminate/support": "5.1.*||5.2.*||5.3.*||5.4.*"`. Composer will then load in `"illuminate/support": "5.4.*"` which, as you might guess, is incompatible with what October requires.

# Potential Workaround
A potential workaround to this limitation could be [excluding dependencies](https://getcomposer.org/doc/04-schema.md#exclude-files-from-classmaps) already loaded by October in the plugin's classmap and then running a manual step during the build process to remove the dependencies that have been doubly loaded. 

While this could work, I thought it would be valuable to make this proposal for including the ability to ignore specific packages within October since I could get the insight of the experts of the community this way. This has been brought up a few times before; see #1426 (referring to platform requirements over regular packages), #5024, http://stackoverflow.com/questions/34637657/its-possible-ignore-child-dependency-in-composer-config, http://stackoverflow.com/questions/22012397/how-can-i-install-package-in-composer-without-dependency. 

# Proposed Solution
I'm envisioning a solution that follows the same syntax as `"require"`, except that instead of pulling the dependencies in `"ignore"` Composer would ignore them and their descendant dependency trees. 

In the case of our above plugins, we would then be able to proceed with our build process on the [plugin marketplace](http://octobercms.com/plugins) by having a parent `composer.json` that would define the dependencies that already get loaded by October as dependencies to `ignore`:
```json
{
    "ignore": {
        "laravel/laravel": "*",
        "illumination/support": "*",
        "illumination/contracts": "*",
        "illumination/filesystem": "*",
        // etc, etc.
    }
}
```

I would very much welcome feedback on this suggestion. Thank you for your time, I appreciate all the wonderful work that has gone into making Composer as powerful as it is today.

**Comment by stof** [comment]
you should use the `provide` directive in your build process, to tell composer that these packages are already provided.
However, make sure you use this only in your build process, not in the composer.json submitted to Packagist, as the package itself does not actually provide these packages (your build does as it knows about what the CMS provides).

**Comment by Seldaek** [comment]
Yup that's what provide is basically doing, so I don't think we need to add ignore. But indeed it should just be done as a "hack" during the build of the plugins.

**Comment by LukeTowers** [comment]
Perhaps this needs to be a separate issue then, because using `"provide"` did not work for me, composer still downloaded the packages that I said I already provided through the use of that property.

**Comment by stof** [comment]
Are you sure that the provide section is added properly before running  the install ? Try to validate the composer.json after adding it to catch mistakes.

Also, make sure you are running the command from a clean vendor folder. Adding a provide rule might not *remove* the package if it is already installed in your vendor folder.

**Comment by Seldaek** [comment]
Oh maybe you should rather try with `replace` than provide actually. That's been working well for me when I want to avoid installing some packages.

**Comment by LukeTowers** [comment]
Positive. This is what my `composer.json` file looks like before running `composer update`:
```json
{
    "name": "luketowers/oc-snappypdf-plugin",
    "type": "october-plugin",
    "description": "SnappyPDF integration for OctoberCMS",
    "homepage": "https://github.com/LukeTowers/oc-snappypdf-plugin",
    "keywords": ["october", "octobercms", "pdf", "barryvdh/laravel-snappy",  "wkhtmltopdf", "wkhtmltoimage"],
    "license": "MIT",
    "authors": [
        {
            "name": "Luke Towers",
            "email": "octobercms@luketowers.ca"
        }
    ],
    "require": {
	    "h4cc/wkhtmltopdf-i386": "0.12.*",
	    "h4cc/wkhtmltoimage-i386": "0.12.*",
	    
	    "h4cc/wkhtmltoimage-amd64": "0.12.*",
	    "h4cc/wkhtmltopdf-amd64": "0.12.*",
	    
	    "barryvdh/laravel-snappy": "0.*"
	},
	"provide": {
		"illuminate/support": "5.1.*"
	},
    "minimum-stability": "dev"
}
```
and this is the result I get from running `composer update`:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 13 installs, 0 updates, 0 removals
  - Installing h4cc/wkhtmltopdf-i386 (0.12.3): Loading from cache
  - Installing h4cc/wkhtmltoimage-i386 (0.12.3): Loading from cache
  - Installing h4cc/wkhtmltoimage-amd64 (0.12.3): Loading from cache
  - Installing h4cc/wkhtmltopdf-amd64 (0.12.3): Loading from cache
  - Installing symfony/finder (dev-master ce30991): Cloning ce309911aa from cache
  - Installing paragonie/random_compat (v2.0.10): Loading from cache
  - Installing illuminate/contracts (5.4.x-dev ab28257): Cloning ab2825726b from cache
  - Installing doctrine/inflector (dev-master 803a2ed): Cloning 803a2ed9fe from cache
  - Installing illuminate/support (5.4.x-dev b32e10f): Cloning b32e10fe8c from cache
  - Installing illuminate/filesystem (5.4.x-dev 7f656e3): Cloning 7f656e3421 from cache
  - Installing symfony/process (dev-master 34b680b): Cloning 34b680b099 from cache
  - Installing knplabs/knp-snappy (dev-master 4e55d12): Cloning 4e55d129d8 from cache
  - Installing barryvdh/laravel-snappy (dev-master dea7284): Cloning dea728426b from cache
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
illuminate/support suggests installing symfony/var-dumper (Required to use the dd function (~3.2).)
illuminate/filesystem suggests installing league/flysystem (Required to use the Flysystem local and FTP drivers (~1.0).)
illuminate/filesystem suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (~1.0).)
illuminate/filesystem suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).)
knplabs/knp-snappy suggests installing wemersonjanuario/wkhtmltopdf-windows (Provides wkhtmltopdf executable for Windows, use version `~0.12` as dependency)
Writing lock file
Generating autoload files
```
As you can see, I stated that I already provide `"illuminate/support": "5.1.*"` yet it still decided to install `illuminate/support (5.4.x-dev b32e10f)` anyways. The requirement from the sub dependency asks for `"illuminate/support": "5.0.x|5.1.x|5.2.x|5.3.x|5.4.x",`, so `"illuminate/support": "5.1.*"` should fulfill that.

**Comment by Seldaek** [comment]
It'd be best to replace `"illuminate/support": "5.*"` IMO, to make sure any version it tries to pick it'll find that being replaced. If you only replace or provide some versions, it might still prefer to install another version.

**Comment by xabbuh** [comment]
@LukeTowers Using `replace` instead of `provide` will give you the desired effect.

**Comment by LukeTowers** [comment]
@Seldaek problem is Laravel (illuminate) doesn't follow semver, it's second point versions (5.*) are breaking changes, so I don't want composer to assume that 5.1 fulfills 5.4.

@xabbuh Thank you so much for pointing me towards that! That worked fantastic!
