### ISSUE TITLE
Clear cache takes forever

### ISSUE THREAD

**Issue by barbazul** [composer/composer#6362]
I recently run into some issues with packagist.org cache not clearing a deleted repo (which was dutifully fixed by Jordi). However, while experimenting myself I found that composer clear-cache took about 30 minutes on each run, even if I ran it and immediately ran it again (on an emptied cache).

So, for the first time ever I started to look under the hood in Composer core.

First thing I did was locating the cache directory, it had the 3 corresponding directories (files, repo and vcs) and inside each of them was a huge folder tree (thousands of nested folders) and not a single file.

The hypothesis was pretty obvious: Clear cache is recursively iterating this massive tree of folders and deleting only the files within. The 30 minutes were spent on recursing directories and not so much in deleting content.

So I went to the code and found the inner workings of this **bug**.

`Composer\Command\ClearCacheCommand::execute()` runs `Composer\Cache::gc()` on each first-level cache folder which in turn calls iterates a `Symfony\Component\Finder\Finder` instance with a trivial date filter of "every file created before right now". So, essentially, every file in the tree -> Hypothesis confirmed!

So for a final validation, I manually deleted the content of the 3 folders (which took about 3 seconds) and ran composer clear-cache once more. It took 0 seconds this time.

I have yet to figure out how to build composer myself to start working on a fix and I honestly don't think I will find the time to do so in the near future, but if I had to guess, I'd say that `Composer\Cache::getFinder()` should drop the call to `Symfony\Component\Finder\Finder::files()` to avoid filtering out directories. Or alternatively, handle the complete wiping of cache as a special case and not just a "forced expiration of everything" and either use a different Finder instance or iterate and delete the folders right after iterating and deleting the files (potentially taking longer when the cache is really big).

Final consideration: some garbage collection mechanism  to delete emptied cache folders over time could be a better (although more complex) approach

**Comment by stof** [comment]
dropping the `files()` call would break the feature. The last modification date of a directory is not updated when you *update* a file in it. It is updated only when adding or removing files. So a directory might be detected as being older than the threshold, while it still has cached files in it.
We cannot implement `gc` this way.

**Comment by barbazul** [comment]
Yup. That makes sense.

So as mentioned before, you would need to not use gc(0, 0) and instead
create a method "clear" which would use a different finder instance.

**Comment by Seldaek** [comment]
The problem is the gc() is really made to work fine with the zip archive cleanup which probably leaves empty dirs behind but not many. Abusing it for the clear-cache command was a bad idea, as it goes into git clones and stuff leaving a lot of empty dirs behind. So yes for clear-cache having a Cache::clear() would be a lot better.

**Comment by barbazul** [comment]
Looking into the Filesystem helper used within the Cache library, it looks like removeDirectory() in the 3 cache directories might be the way to go

**Comment by Seldaek** [comment]
Yeah that sounds fine too.
