### ISSUE TITLE
Inconsistent output from composer update

### ISSUE THREAD

**Issue by danepowell** [composer/composer#6363]
Various fields in `composer.lock` can randomly change from one execution of `composer update` to the next. This is really annoying since it can make code reviews difficult and produce merge conflicts. The desired behavior is that repeatedly running composer update on the same composer.json file should produce exactly the same output (composer.lock).

Note that I'm not just talking about the content-hash here, but the actual contents of the file itself.

Most commonly, it's the "reference" field that switches back and forth between null and a correct version string such as "8.x-3.0-beta2" in the following snippet from composer.lock. I've also seen authors randomly disappear and reappear.

```json
{
    "packages": [
        {
            "name": "drupal/ctools",
            "version": "3.0.0-beta2",
            "source": {
                "type": "git",
                "url": "https://git.drupal.org/project/ctools",
                "reference": "8.x-3.0-beta2"
            },
            "dist": {
                "type": "zip",
                "url": "https://ftp.drupal.org/files/projects/ctools-8.x-3.0-beta2.zip",
                "reference": "8.x-3.0-beta2",
                "shasum": "6deece503cca328dde9b573a5d8a8fc74798d284"
            },
            "authors": [
                {
                    "name": "Kris Vanderwater (EclipseGc)",
                    "homepage": "https://www.drupal.org/u/eclipsegc",
                    "role": "Maintainer"
                },
```

To reproduce this, you can use a `composer.json` like the following, and repeatedly run composer update. Although you might have to mix it up, by changing dependencies, adding arguments such as `composer update drupal/core`, or just getting "lucky"--I've had a really hard time pinning down the conditions under which this occurs. Sometimes I can run `composer update` all day long and the bug never reoccurs.

```json
{
    "name": "test/test",
    "type": "project",
    "license": "proprietary",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "drupal/core": "^8.3.0",
        "drupal/ctools": "^3.0"
    },
    "repositories": {
        "drupal": {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    },
    "extra": {
        "installer-paths": {
            "docroot/core": [
                "type:drupal-core"
            ],
            "docroot/modules/contrib/{$name}": [
                "type:drupal-module"
            ],
            "docroot/modules/custom/{$name}": [
                "type:drupal-custom-module"
            ],
            "docroot/profiles/contrib/{$name}": [
                "type:drupal-profile"
            ],
            "docroot/profiles/custom/{$name}": [
                "type:drupal-custom-profile"
            ],
            "docroot/themes/contrib/{$name}": [
                "type:drupal-theme"
            ],
            "docroot/themes/custom/{$name}": [
                "type:drupal-custom-theme"
            ],
            "docroot/libraries/{$name}": [
                "type:drupal-library"
            ],
            "drush/contrib/{$name}": [
                "type:drupal-drush"
            ]
        }
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

**Comment by danepowell** [comment]
Actually I have detected a pattern here: running composer update from an Ubuntu environment tends to _add_ the reference tags (e.g. 8.x-3.0-beta2), while running from a Mac environment tends to _remove_ them (setting them to null).

This is the same Composer version on both environments (Composer version 1.4.1 2017-03-10 09:29:45)

**Comment by Seldaek** [comment]
The reference is normally just taken over from the repository  (in this case the drupal.org one). I'm not sure what would cause it to come and go like that.. And especially having a "tendency" to remove or add them sounds dodgy. Would be great if you can figure out a bit more specifically what causes it :)

**Comment by danepowell** [comment]
Today I noticed that my machines now behave identically (they both add the reference). But we still have other developers who's machines are not adding the reference field.

Could it have something to do with caching? Just a WAG: maybe if the Git version of a project is cached locally, affects the version detection even if you later download the packaged distribution?

**Comment by Seldaek** [comment]
OK that doesn't really help us reproduce it ;) Sorry but I really have no clue what could cause this.

**Comment by danepowell** [comment]
I know you think I'm crazy, but this must be a pretty widespread problem :) I'm surprised no one's reported it. Dozens of people in our department encounter it on a daily basis.

Perhaps it has something to do with the upstream package repository, since I've only ever seen this happen for Drupal packages. Can you tell me where I would look to verify the data coming from the repository? i.e. a raw JSON that I can check to verify if the reference value is set correctly?

The Drupal package repo is here: https://packages.drupal.org/8

**Comment by alcohol** [comment]
Can you please check if each user/client has the same Composer and Git version installed locally? See if there are any discrepancies there?

**Comment by danepowell** [comment]
Composer versions are the same (see comment above). Git versions are 2.11.0 and 2.11.1, that doesn't seem likely to be the difference. Plus, I think I mentioned that I can get differing results even on the same machine.

**Comment by darthsteven** [comment]
This is also logged on Drupal.org as an issue:
https://www.drupal.org/node/2893017

Not sure where the bug/issue issue is.

**Comment by anotherjames** [comment]
I've found the line of code causing this!!

1) The drupal.org composer repo does not return a 'reference' in the dist section for packages.
2) During an operation on the lock file (e.g. `composer update --lock`), https://github.com/composer/composer/blob/a3f2b7bb92a54f4e25b2d0998f00936ecac6f933/src/Composer/Installer.php#L1175 - the existing *source* reference is got (`$oldSourceRef`) and passed into the `updateInstallReferences()` method
3) That will set the *dist* reference from that. (https://github.com/composer/composer/blob/a3f2b7bb92a54f4e25b2d0998f00936ecac6f933/src/Composer/Installer.php#L1202)

So this could be solved by the composer repo ensuring to set the reference in the dist section, but the current docs say that's not required. See https://getcomposer.org/doc/05-repositories.md#packages  - the 'minimal package definition' does not include a reference value in the dist section. So either the documentation is wrong, so every composer repo endpoint that doesn't include a reference under dist needs to be fixed... or something could be done inside composer itself to avoid this problem. I suggest the latter.

In order to understand the best solution, I would like to know why the source reference gets written into the dist reference on updating the lock file without a whitelist? If there's a good reason, it should also be done when installing a package too. If not, then let's stop doing that please! I am happy to provide a PR either way, if we can get an answer to that.

**Comment by Seldaek** [comment]
@anotherjames thanks for the analysis. I pushed a tentative fix, would appreciate if you can confirm whether this fixes it after running `composer self-update --snapshot`. Note that it might require that you remove the vendor dir and run a `composer update` to clean up the installed data and make sure you generate a clean lock file again but I'm not 100% sure.

**Comment by anotherjames** [comment]
The composer repo endpoint was fixed to always set the reference now anyway (as of https://www.drupal.org/node/2893017#comment-12206325), so it's hard to test now! But it all looks to work correctly as far as I can see now. Thank you so much!
