### ISSUE TITLE
Composer can not find sys_temp_dir

### ISSUE THREAD

**Issue by Tumulalmamun** [composer/composer#6367]
:\xampp\htdocs>composer php PHP temp directory (C:\Users\Abdullah\AppData\Local\Temp;C:\xampp\php) does not exist or is not writable to Composer. Set sys_temp_dir in your php.ini [Symfony\Component\Console\Exception\CommandNotFoundException] Command "php" is not defined. to Copmposer can not find sys_temp_dir

**Comment by Seldaek** [comment]
It seems like the temp directory is wrong it should be only set to `C:\Users\Abdullah\AppData\Local\Temp` I think. Try setting it via sys_temp_dir in your php.ini. Sorry but we can't help much with that.. It's a PHP configuration issue.
