### ISSUE TITLE
Unable to download.Phar when installing composer.exe

### ISSUE THREAD

**Issue by lucyZhong** [composer/composer#6368]
The error is as follows:
The "https://getcomposer.org/versions" file could not be downloaded: 
The "https://getcomposer.org/download/1.4.1/composer.phar.sig" file could not be downloaded: SSL: Handshake timed out
Failed to enable crypto
failed to open stream: operation failed
Failed to decode zlib stream

In Chinese, installation, has over the wall

**Comment by Seldaek** [comment]
Seems like a network issue the timeout.. Not much we can help with I'm afraid.
