### ISSUE TITLE
Composer private gitlab repository does always clone master branch

### ISSUE THREAD

**Issue by florianlenz** [composer/composer#6369]
My `composer.json`:

```json
{
    "require": {
        "flole/project": "dev-version_one",
    },
    "repositories": [
        {
            "type": "git",
            "url":  "git@gitlab.com:my_username/my_repo.git"
        }
    ],
    "config": {
        "bin-dir": "bin",
        "gitlab-token" : {
            "gitlab.com": "my_token"
        }
    },
}

```

Output of `composer diagnose`:

```
(Nothing special install is successful. )
```

When I run this command:

```
composer install
```

And I expected this to happen:
I expect that the "version_one" branch of the repository is pulled into my project but composer does 
always install the master branch. I tested this by putting a simple txt file into my "version_one" branch. If i run the composer install command it is not in the vendor project root. So the master branch is used. As far as i understood i configured it correctly (i used this instructions https://getcomposer.org/doc/05-repositories.md#using-private-repositories).

**Comment by Dreimus** [comment]
Same issue for me with tag management with a GitLab Private repository
if I require a specific tag, master is always the one which is checked out.

**Comment by Dreimus** [comment]
Can you try to set in your composer.json config section : 

    "preferred-install": { 
        "flole/project":"source"
    },

It has checked out the right version if source is specified.
I think that the problem is coming from gitlab archive download from commit. Composer might not use the right commit revision number.

**Comment by Berdir** [comment]
Can confirm that the preferred-install workaround works, thanks!

This might be a bug in gitlab. Looking at the URL, I see this:

https://gitlab.example/api/v3/projects/my-project/repository/archive.zip?ref=correct-hash

When I download an archive in the UI, I get this URL:

https://gitlab.example/group/project/repository/archive.zip?ref=same-hash

The second URL works and downloads the right commit, the first URL clearly doesn't.

So this will possibly need to be reported against gitlab. They also deprecated v3 of their API, so that will need to be updated to v4 eventually. Maybe it is working there but I doubt it.

**Comment by Berdir** [comment]
Created https://gitlab.com/gitlab-org/gitlab-ce/issues/31530

**Comment by Berdir** [comment]
Got already feedback from them, looks like the parameter that needs to be used is sha, not ref.

https://gitlab.com/gitlab-org/gitlab-ce/blob/479d21d5850d9878ef292016ae7e643fdbb0b796/lib/api/v3/repositories.rb#L72

**Comment by Berdir** [comment]
Oh, looks like this was changed already.

be201924cd9f3f22c21399047d8740ba55025d83, which reverted a previous change that *broke* it, apparently.

Related issues mentioned in that commit: #6344, #6198

I guess this makes this a duplicate.

**Comment by Berdir** [comment]
As a workaround, you can downgrade to composer 1.3.2, that works for me.

**Comment by janpalacky** [comment]
Some progress with this issue? Using actual gitlab 9.1.3 and Composer 1.4.1. Composer is still checking out the master branch only. Or is some related opened issue on gitlab?

**Comment by sjadema** [comment]
Would it be possible for you guys to roll out a version `1.4.2` with this fix implemented?

**Comment by Seldaek** [comment]
1.4.2 is out, sorry for the delay.

**Comment by sjadema** [comment]
@Seldaek Thanks!

**Comment by Luitame** [comment]
@Seldaek today you saved my life  :)
