### ISSUE TITLE
Composer still includes .git directory with --prefer-dist when using github repository

### ISSUE THREAD

**Issue by albertski** [composer/composer#6370]
I added mypackage to the repositories key in composer.json:

        "repositories": {
            "packagist": {
                "type": "composer",
                "url": "https://packages.drupal.org/8"
            },
            "mypackage": {
                "type": "package",
                "package": {
                    "name": "company_name/mypackage",
                    "type": "drupal-module",
                    "version": "dev-master",
                    "source": {
                        "type": "git",
                        "url": "https://github.com/company_name/mypackage",
                        "reference": "master"
                    }
                }
            }
        },

I run `composer require company_name/mypackage-master --prefer-dist`

The package does get downloaded but it still adds the .git directory. I would like the package to download without the .git directory. How would I accomplish this?

**Comment by alcohol** [comment]
`--prefer-dist` often only works for versions, not moving targets such as `dev-master`. Although I do believe Github offers a tarball for branches as well. But since you are using the `git` type and not `vcs`, Composer cannot detect that the source is Github.

**Comment by albertski** [comment]
When I change the type from `git` to `vcs` I get the following InvalidArgumentException:

    Unknown downloader type: vcs. Available types: git, svn, fossil, hg, perforce, zip, rar, tar, gzip, xz, phar, file, path.

I created a release in github: 1.0.0 and updated version to 1.0.0 in composer and the same issue happens.

**Comment by alcohol** [comment]
Okay that's because you are using a package definition. Read the documenation on the different types that are available for more details.

```
"repositories": {
        "packagist": {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        },
        "mypackage": {
            "type": "vcs",
            "url": "https://github.com/company_name/mypackage"
        }
    },
```

**Comment by albertski** [comment]
I added a composer.json file to my package: https://github.com/xenomedia/xeno_hero/blob/master/composer.json

Updated repositories to:

    "repositories": {
        "packagist": {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        },
        "xenomedia/xeno_hero": {
            "type": "vcs",
            "url" : "https://github.com/xenomedia/xeno_hero"
        }
    },

But when running `composer require xenomedia/xeno_hero` I am getting the following error:

Could not find package xenomedia/xeno_hero at any version for your minimum-stability (dev). Check the package spelling or your minimum-stability

**Comment by stof** [comment]
Well, the package name in your composer.json is `drupal/xeno_hero`, not `xenomedia/xeno_hero`. So you need to use `composer require drupal/xeno_hero`

**Comment by albertski** [comment]
Thanks @stof.  I updated my composer file to be `xenomedia/xeno_hero` and now the issue doesn't happen.
