### ISSUE TITLE
Class 'crodas\InfluxPHP\Client' not found

### ISSUE THREAD

**Issue by contactmat85** [composer/composer#6374]
My `composer.json`:

{
    "require": {
        "phpmailer/phpmailer": "^5.2",
        "crodas/influx-php": "^0.9"
    }
}

Output of `composer diagnose`:

Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
[gestoos@s104-238-72-48 gestoos_analytics_tests]$

When I run this command:

$client = new \crodas\InfluxPHP\Client(
    "marty-96f1166d.influxcloud.net", // host
    8086,        // port
    "***",      // user
    "***"       // password
);

I get the following output:

Fatal error: Class 'crodas\InfluxPHP\Client' not found in /home/gestoos/public_html/gestoos_analytics_tests/analytics_test_influx.php on line 8

**Comment by alcohol** [comment]
Please read the documentation before opening an issue.
