### ISSUE TITLE
brozot/Laravel-FCM  problem 

### ISSUE THREAD

**Issue by virusismine** [composer/composer#6376]
C:\xampp\htdocs\warrantii_main>composer require brozot/laravel-fcm
Using version ^1.2 for brozot/laravel-fcm
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v4.2.22
    - Conclusion: don't install laravel/framework v4.2.22
    - brozot/laravel-fcm v1.2.0 requires illuminate/support >=5.0.0 -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.9].
    - brozot/laravel-fcm v1.2.1 requires illuminate/support >=5.0.0 -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.9].
    - brozot/laravel-fcm v1.2.2 requires illuminate/support 5.* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.9].
    - brozot/laravel-fcm v1.2.3 requires illuminate/support 5.* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.9].
    - brozot/laravel-fcm v1.2.4 requires illuminate/support 5.* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.9].
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.0.22|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.0.25|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.0.26|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.0.28|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.0.33|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.0.4|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.1|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.13|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.16|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.2|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.20|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.22|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.25|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.28|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.30|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.31|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.41|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.6|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.8|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.0|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.19|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.21|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.24|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.25|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.26|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.27|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.28|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.31|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.32|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.37|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.43|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.45|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.6|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.7|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.3.0|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.3.16|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.3.23|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.3.4|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.4.0|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.4.13|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.4.17|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.4.19|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.4.9|don't install laravel/framework v4.2.22
    - Installation request for laravel/framework (locked at v4.2.22, required as 4.2.*) -> satisfiable by laravel/framework[v4.2.22].
    - Installation request for brozot/laravel-fcm ^1.2 -> satisfiable by brozot/laravel-fcm[v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4].

Installation failed, reverting ./composer.json to its original content.

**Comment by virusismine** [comment]
how to install laravel-fcm packages .. please help..

**Comment by alcohol** [comment]
Upgrade laravel to `5.x`.

**Comment by virusismine** [comment]
thnx
