### ISSUE TITLE
Interact at create-project

### ISSUE THREAD

**Issue by gisostallenberg** [composer/composer#6380]
My `composer.json`: N/A

Output of `composer diagnose`: N/A

When I run this command:
```
composer create-project vendor/project target-directory
```

I get the a composer.json that is the same as the one in vendor/project. This is almost never what you want. It would be nice when composer asks some questions that are the same as in `composer init`, maybe giving the current setting as a default.

Would you be interested in a feature like that?

**Comment by alcohol** [comment]
I think you do not understand what `create-project` does.

It is simply a shortcut for:
- `git clone target-project`
- `cd target-project`
- `composer install`

**Comment by stof** [comment]
@alcohol to be exact, by default, it is a shortcut for this:

```bash
git clone target-project
cd target-project
rm -rf .git  # can be skipped with --keep-vcs
composer install
```
