### ISSUE TITLE
install project on another server

### ISSUE THREAD

**Issue by CashCode** [composer/composer#6382]
Hey!
I'm new to composer, I have project installed on local xampp server.
I want to put it on production server, but autoload doesnt work properly.
I tried to install it again on production server using command ```composer require author/package-php ```
it works, but it install a new version of package. I need the old one (which is installed on my local server).
How to put my local copy of project on production server?
I thought that I can just copy-paste it, but autoload doesnt work :(
composer.json on local: ```{
    "require": {
        "author/package-php": "^2.0"
    }
} ```
composer.json on server: ```{
    "require": {
        "author/package-php": "^1.5"
    }
} ```

**Comment by stof** [comment]
you should commit your composer.json and your composer.lock, and then run `composer install` on the prod server when deploying.

`composer require` and `composer update` are *development-time* commands

**Comment by sdee3** [comment]
I was just going to ask the exact same thing. After uploading the entire Composer/Slim project (whatever it is, I'm pretty new with PHP) and testing out one of my POST requests, I got a 403 error. Fortunately, GET requests work.

-all I did was use Filezilla to upload the project

Thanks, stof!

**Comment by CashCode** [comment]
@stof, thanks! Seems like it works and that was needed. There is older php version on server, than on local enviroment.
I'll try to update php version and do it again.
Please, don't close topic yet.

**Comment by xabbuh** [comment]
@CashCode Using the [`platform`](https://getcomposer.org/doc/06-config.md#platform) option you can let Composer now which PHP version you have on your live system so that your locally generated `composer.lock` file can be used on the server:

```json
{
    "config": {
        "platform": {
            "php": 5.6"
        }
    }
}
```
