### ISSUE TITLE
Rename vendor name for package

### ISSUE THREAD

**Issue by noplanman** [composer/composer#6385]
I've tried searching but haven't found a clean solution to this yet.

What I'm looking at, is to move a private project into an organisation, and thus updating the vendor name of the package.

Trying this on a test repository, the only way to get the updated name into packagist, seems to be deleting the project and then re-adding it.

I would have expected an "Update" to pick up the new name automatically.

What is the correct process to do this? Is there a way to force the update?

My `composer.json` before:
```json
    "name": "vendor/project",
```

My `composer.json` after:
```json
    "name": "new-vendor/project",
```

**Comment by Seldaek** [comment]
Please see https://github.com/composer/packagist/issues/47 for a how-to

**Comment by noplanman** [comment]
Ok, thanks!
Just noticed I was looking in the wrong repo, sorry.
