### ISSUE TITLE
Can Composer detect if PHP has Freetype support ?

### ISSUE THREAD

**Issue by dregad** [composer/composer#6390]
I have code that relies on [imagettfbbox()](http://php.net/manual/en/function.imagettfbbox.php). That function is part of *GD* extension, but also requires that PHP is compiled using `--with-freetype-dir=...` option.

I can set a `"require": { "ext-gd": "*" }`, but that only addresses part of the problem, so I was wondering if there is a way for Composer to check whether _Freetype_ is available, or if I have to rely on a run-time test in my code for that.

Thanks in advance

**Comment by alcohol** [comment]
You will need to use a run-time check/test.

**Comment by dregad** [comment]
Thanks for the prompt reply !
