### ISSUE TITLE
Using Github Installation token to install private repositories

### ISSUE THREAD

**Issue by bdelbasso** [composer/composer#6394]
Github has a new feature called [Integrations](https://developer.github.com/v3/integrations/), in early-access and moved to [pre-release](https://developer.github.com/changes/2017-04-25-Integrations-Pre-Release/) a few days ago,

It is possible to check-out repositories [using an Installation Token](https://developer.github.com/early-access/integrations/authentication/#http-based-git-access-by-an-installation) with username `x-access-token`:
```
git clone https://x-access-token:<token>@github.com/owner/repo.git
```

Assuming the following `composer.json`:
```
# example/some-private-repo is hosted on https://github.com/example/some-private-repo
{
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.example.com"
        }
    ],
    "require": {
        "example/some-private-repo": "^1.0"
    }
}
```

I did not find any way to use this token to install private repositories. 

- I tried using the token alone when prompted by composer. It is refused (invalid).
- I tried using [git credential storage](https://git-scm.com/book/gr/v2/Git-Tools-Credential-Storage). 

```
git config credential.helper 'cache --timeout=1800'
printf "protocol=https\nhost=github.com\nusername=x-access-token\npassword=TOKEN\n" | git credential-cache store

git clone https://github.com/example/some-private-repo 
# ==> success

composer install
# ==> fails (asks for an OAuth token)
```

Am I missing something?

If not, I see two options:

1. Update `github-oauth` option to support user/password tuples.

2. Add support for git credential storage.

I favor second option so that we don't reinvent the wheel.

**Comment by Xerkus** [comment]
try `http-basic`, it might work
```json
{
  "http-basic": {
    "gitlab.com": {
      "username": "x-access-token",
      "password": "<token>"
    }
  }
}
```

**Comment by bdelbasso** [comment]
@Xerkus Headshot! It works, thanks.

As a side question, does anyone know if supporting [git credential storage](https://git-scm.com/book/gr/v2/Git-Tools-Credential-Storage) was ever discussed? 

I'm wondering since in my use case, the credentials are already configured and I would even not need to tinker with the `auth.json`.

**Comment by alcohol** [comment]
@bdelbasso this was never discussed before, not has anyone attempted to do so, as of yet.
