### ISSUE TITLE
Docs suggestion: prefer CLI over composer.json editing

### ISSUE THREAD

**Issue by borekb** [composer/composer#6403]
While I understand that `composer.json` is at the core of Composer, I personally interact with most package managers from CLI, be it Composer, npm, Yarn or any other. This is also true for my colleagues and fellow developers. If this is a common approach, I think that the docs should be centered around this use case, for example, [Yarn's usage page](https://yarnpkg.com/en/docs/usage) seems shorter and easier to follow to me than Composer's [Basic usage](https://getcomposer.org/doc/01-basic-usage.md).

Before possibly starting a PR, I wanted to ask whether this is a shared view in the community or not. If so, I'd be happy to contribute to the docs.

**Comment by stof** [comment]
I think the main reason for that is that the basic usage page was first written at the time none of the commands used to manipulate the composer.json were written yet.
On the other hand, `yarn add` was part of the initial release

**Comment by borekb** [comment]
I also think that the `composer.json` info is valuable and should stay, the suggestion would just be to restructure the page to focus on user scenarios first.
