### ISSUE TITLE
Semver option in composer.json

### ISSUE THREAD

**Issue by bkrukowski** [composer/composer#6405]
Would be nice to have an option to mark that version numbers follows the semantic versioning or no.

```json
"semver": true
```
or

```json
"versioning": "semver"
```

### Documentation

Would be easier to get information that repository supports the semantic versioning. Everything would be placed in composer.json file.

### Warnings

Command `composer update` would display warning

```bash
Repository foo/bar supports semver. Please, use '^0.4' instead of '~0.4' for compatibility in future.
```

**Comment by alcohol** [comment]
Except there is no way we can actually enforce the validity of the value of this setting. So, a lot of work for something of little value honestly.
