### ISSUE TITLE
Plugin is not re-registered after being updated

### ISSUE THREAD

**Issue by bartfeenstra** [composer/composer#6408]
I have a plugin that subscribes to `PackageEvents::POST_PACKAGE_INSTALL` and `PackageEvents::POST_PACKAGE_UPDATE`. However, when the plugin package itself is updated, the old version's handlers are invoked rather than the new version's. This is because `\Composer\Plugin\PluginManager::registerPackage()` skips packages that have been registered during the same request already, which is the case for our plugin, probably because there is no way to undo `\Composer\Plugin\PluginManager::addPlugin()` (the event dispatcher does not support removing listeners).

Our goal: after updating our plugin, the old plugin's handlers MUST NOT be used, and the new plugin's handlers MUST be used.

Is this a bug, or are we taking the wrong approach to this?

**Comment by alcohol** [comment]
Just update the plugin using `composer update --no-plugins my/plugin`.

**Comment by bartfeenstra** [comment]
That is no solution as it prevents the new plugin's handlers from running during that same request. In our particular case this approach prevents our entire plugin from working (installing assets after it itself is installed).

**Comment by alcohol** [comment]
Thats because you should not run plugins while updating them.

**Comment by alcohol** [comment]
You can easily run your script after the proper update using `run-script` or simply running `install` (which will not update anything but should still trigger your scripts).

**Comment by bartfeenstra** [comment]
Thanks, will experiment with that :)

Is there a better solution for creating a dependency that can automatically perform tasks after its own installation/update?

**Comment by alcohol** [comment]
Due to the nature of the plugin system, this is virtually impossible afaik.

**Comment by stof** [comment]
what you could do is writing your business logic in a separate class in your plugin. Then, the event listener callable would call a method on this class, which will trigger the autoloader for this class *at the time the listener gets called*. This way, the *new* implementation of the business logic will be loaded (as long as you ensure you don't trigger a usage of this class earlier)

**Comment by bartfeenstra** [comment]
It took a while for me to get back to this problem, and I'm glad to be able to confirm your solution works fabulously, @stof. Thank you very much for chipping in here :)
