### ISSUE TITLE
URL to download the latest stable version

### ISSUE THREAD

**Issue by xxorax** [composer/composer#6409]
There is no easy way to download the latest stable version of composer except by using the installer.

The [link](https://getcomposer.org/composer.phar) provided on [the download page](https://getcomposer.org/download/) is the snapshot version, not the stable version. The lastest tag on github does not provide the phar file.

Installing composer on many servers is a boring task, running the heavy (undocumented?) installer, as root, is not acceptable for correct security, as well for network traffic.
The only way is actualy to look at the latest stable version number and get in from https://getcomposer.org/download/*/composer.phar  :
```bash
curl -L https://getcomposer.org/versions | awk '/stable/ { match($0, "\"path\": \"([^\"]+)\"", arr); print "https://getcomposer.org" arr[1] }'
```
But it looks unreliable in time.

Is there an URL somewhere ?
Somethink like https://getcomposer.org/download/stable/composer.phar ?

**Comment by alcohol** [comment]
@Seldaek could maybe setup an alias to the latest stable version (but it would have to be updated on every release).

Honestly though, if this is a difficult task for you to automate, maybe a career in IT is not in your future.

**Comment by Seldaek** [comment]
You can use https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md - and you don't really have to run it as root.. You might just have to move the composer.phar file as root at the end to place it in a dir that's in the PATH if you so desire.

**Comment by alcohol** [comment]
> the lastest tag on github does not provide the phar file.

I was adding the phar to each tag for a while, but have forgotten about this for several releases now. I could start adding those again, but this is a manual task and thus prone to being forgotten (as is evident already).

**Comment by Seldaek** [comment]
It also might break stuff if we release a new version that is not compatible with older PHP releases for example. The installer checks for this and will install the last compatible version, it's the better way to go.

**Comment by xxorax** [comment]
Well, there is finaly a package now : https://packages.debian.org/search?keywords=composer

**Comment by Koc** [comment]
@Seldaek please reopen.

For Docker image we should write short one-line commands. It is better execute
`RUN curl --insecure https://getcomposer.org/download/stable/composer.phar -o /usr/bin/composer && chmod +x /usr/bin/composer` instead of big running big script of programatically installation.

**Comment by alcohol** [comment]
@xxorax sure, but it is completely unsupported from our end :-)

@koc we already provide an official Docker image. There is no need to re-open this.

**Comment by fritzmg** [comment]
One could also do:
``` 
wget https://getcomposer.org/composer.phar && php composer.phar selfupdate --stable
``` 
Then you have the latest stable version. But I agree: a dedicated URL which always downloads the latest stable - whithout having to go through the installer - would be handy :).

**Comment by Seldaek** [comment]
https://getcomposer.org/composer-stable.phar is now available

**Comment by kimraz** [comment]
https://getcomposer.org/composer-stable.phar returns a HTTP-500 response
