### ISSUE TITLE
Allow passing --dev status to scripts

### ISSUE THREAD

**Issue by jalliot** [composer/composer#641]
Hi guys,

Would it be possible to pass (maybe in the extra array) whether the `--dev` flag was used to install/update dependencies or not?
Use case would be to run different commands in development or in "production".

**Comment by koenhendriks** [comment]
Still no updates?

I would like to see this as well. I'm using the php laravel ide generator in require-dev and in the scripts i would like to run `php artisan ide-helper:generate` but only on dev

**Comment by isaackearl** [comment]
@koenhendriks I have the exact same scenario.  +1 to this...

**Comment by neronmoon** [comment]
I just solve this by plugin. 
https://github.com/neronmoon/scriptsdev

**Comment by sergeyklay** [comment]
@neronmoon :+1:
