### ISSUE TITLE
Idea: Make ArchiveManager accessible from Composer class

### ISSUE THREAD

**Issue by brzuchal** [composer/composer#6411]
I have an idea to implement custom archiver, downloader and installer in form of plugin.
While implementing plugin I have access to `Composer` object and `IOInterface` through `activate(Composer $composer, IOInterface $io)` method. Almost all needed components are accessible like `DownloadManager`, `InstallationManager` and even `AutoloadGenerator` but there is no `ArchiveManager` which is used only in `composer archive` command.

Is it possible to move `ArchiveManager`object like other managers into `Composer` class?

**Comment by alcohol** [comment]
How do you feel about this @Seldaek ?
