### ISSUE TITLE
[RFC] Split releases and dev branches in separate provider files in composer repositories

### ISSUE THREAD

**Issue by stof** [composer/composer#6415]
Currently, the composer repositories using separate providers for each package (Packagist does it, and Satis has an option to do it too) are putting all the version of the package in the same file.
But this has a huge drawback: even though most Composer projects are using only stable versions of packages (due to the default minimum stability), the metadata file of the package gets updated for each commit in the repo (due to the dev version), which invalidates the local cache for this file.

I suggest reorganizing the provider files to have 2 files per packages: one with releases and one with dev branches (we could have separate files for the non-stable releases too, but I don't think this is worth it). This would have several advantages:

- the release file would change only when you create a new tag in your repository, which happens much less frequently than doing a commit. This would limit the cache busting effects.
- the dev branch file would be much smaller (most packages have a single dev version IMO, but I haven't checked this assumption based on the Packagist DB), so the file needing to be downloaded when the cache is busted for each commit would be much smaller
- as the pool knows which packages are allowed to use a dev version (the minimum stability and the stability flags are root-only settings), the repository could skip the download of the dev branch files when dev versions are rejected anyway.

Such change would require changes in 2 places:

- in composer to allow having multiple providers for the same file (it probably needs to use a new key in the file to allow having both the new split format and the old format in parallel in the repository to avoid breaking people using older composer versions, as we did in the past)
- in Packagist to implement the new dumping (keeping the existing one in parallel for some time for BC reasons)

what do you think about this idea ?

**Comment by stof** [comment]
Note that the third advantage (skipping the download based on stability) does not need to be implemented during this change. It is an extra optimization which becomes possible once the files are split.

**Comment by alcohol** [comment]
I think the biggest chunk is often the main provider files though. How would those be affected?

**Comment by Seldaek** [comment]
I think we can evaluate this once we work on 2.0 which will see changes to the repo format anyway. My first impression is not too keen on doing this because it adds complexity and I think we can reduce filesize in other ways, but maybe that changes after sleeping over it.

**Comment by stof** [comment]
@Seldaek the main goal of this is not to reduce file size, but to increase cache usage. Currently, Packagist invalidates the cache for package files each time a commit is pushed to a branch, even though most users only care about stable release (which happen every few weeks only)

**Comment by Seldaek** [comment]
See https://github.com/composer/composer/commit/ff82334124633d35f23343db17017e0d5abab1c2 and https://github.com/composer/packagist/commit/57d65b9ad563ee16577cf698328b749e093228b0
