### ISSUE TITLE
Time machine

### ISSUE THREAD

**Issue by ostrolucky** [composer/composer#6417]
### Proposal
Add a new flag to `composer install` which disallows installing versions released later than specified date. E.g. `composer install --max-package-release-date=2017-01-01`
### Use case:

You've got an old code containing composer.json, but no composer.lock. This code was supposed to demonstrate bug which was present at that time. However, it can no longer be replicated, because packages it relied to got meanwhile updated, so `composer install` downloads newer packages than the ones which were available at the time. These newer packages altered the original behaviour. Now, the only way to reproduce the original behaviour is to check the last time old behaviour was present, manually check which packages were released at that time and add upper bounds for these versions in constraints of composer.json. This is very time sensitive to do manually. 

This feature would help with investigation of old bug reports for PHP projects. Some users who reported bugs in past were kind enough to create a sandbox for a bug which they published to github, but after some time the reported behaviour has altered and it's difficult to figure out what change has caused this.

**Comment by alcohol** [comment]
> This is very time sensitive to do manually.

So automate it. This is what git-bisect was made for.

I see no reason to add yet another feature to composer, for a use-case scenario that almost never exists.

**Comment by Seldaek** [comment]
You could also try to run a `composer update --prefer-lowest` which will install oldest valid requirements.
