### ISSUE TITLE
"composer dump-autoload" ignores changes in dependent "autoload: {files: ...}" sections

### ISSUE THREAD

**Issue by rosasurfer** [composer/composer#6421]
How to reproduce:
---------------------
Setup root project:
```json
...
"require": {
    "name/dependency":   "dev-master"
},
...
```

Setup project "name/dependency" case 1:
```json
...
"autoload": {
    "classmap": ["app/"],
    "files": ["app/view/helper.php"]
},   
...
```

After ```composer install``` app/view/helper.php is correctly preloaded in the root project (see ```{root-project}/vendor/composer/autoload_files.php```). So far so good.

Now add a new class and another view helper file to the dependency. The class is not really required and only serves as a signal that Composer indeed detects and picks up the changes.

Setup project "name/dependency" case 2:
```json
...
"autoload": {
    "classmap": ["app/"],
    "files": ["app/view/helper.php", "app/view/helper2.php"]
},   
...
```
Run ```composer dump-autoload``` to reflect the changes. First in the dependent project, than in the root project.

Expected result:
------------------
The added class is available and the second view helper is preloaded together with the first one.

Actual result:
----------------
The added class is indeed available in the root project. However, the second view helper is not. See ```{root-project}/vendor/composer/autoload_files.php``` which still contains only one entry for preloaded files.

Is this expected behaviour? If so, how about updating preloaded file sections as well?

**Comment by stof** [comment]
Chaging the metadata of a dependency require running an update to get the new metadata in the lock file of your main project. If you don't run `composer update`, new metadata won't be read.

**Comment by rosasurfer** [comment]
Sorry, your statement is just wrong. As my test case shows it is expected and indeed intended behaviour that ```composer dump-autoload``` trashes and re-reads class loader meta-data of dependencies. If you was indeed right we would have another bug in Composer (added classes in dependencies become available without running ```composer update```).

**Comment by jvasseur** [comment]
The class list is not contained in the package `composer.json`, so you don't need to run `composer update` when it changes.

Composer totally ignores the data in the downloaded package (you could even remove it and it would still work). Composer create the autoloader based on the metadata that it gets from the composer repository (that is copied into `vendor/composer/installed.json`).

**Comment by rosasurfer** [comment]
No, it doesn't. If it was the new classes would not become available. Composer trashes and re-creates autoloader configuration by re-reading the dependencies, not only by inspecting ```vendor/composer/installed.json```. This can be seen by the fact that new classes become available. Either it's wrong that new classes automatically become available, or it's wrong that files section are skipped.

**Comment by Seldaek** [comment]
@rosasurfer what @stof said is correct. The vendor directory is not supposed to be edited ever. If you do then you void the warranty.

When you dump autoloader, the static classmap will rescan the classes in app/ so it will find new classes that you add, but if you add something else like src/ to the classmap of a dependency then it would not find those.

Similarly, the new files entries are not picked up as the composer.json in vendor/*/*/... are completely ignored.

The way to go is to update the packages that need updating, not to mess around in the vendor dir. The [path repo](https://getcomposer.org/doc/05-repositories.md#path) can help with that for local dev stuff.

**Comment by felds** [comment]
@Seldaek I'm going through this right now. It only works by removing and then re-adding the dependency. `composer update` does nothing, even when using the path repo.
