### ISSUE TITLE
Fails to resolve nested "private" repositories

### ISSUE THREAD

**Issue by chrisallenlane** [composer/composer#6425]
I am currently developing a large application composed of many small, private composer modules. I am making `composer.json` "aware" of my private modules like this in `composer.json`:

```javascript
// ...
    "repositories" : [
      {
        "type" : "vcs",
        "url"  : "git@github.com:MyVendor/MyRepo.git"
      }
    ],
// ...
    "require": {
        "MyVendor/MyRepo": "1.0.0",
    },
// ...
```

(Obviously, I'm truncating and redacting some information out of the above example.)

This works fine under "normal" circumstances, but seems to fail when I begin to "nest" my dependencies.

For example, assume we have the following modules and dependencies:

- `foo`: no dependencies
- `bar`: depends on `foo`
- `baz`: depends on `bar`.

When I run `composer install` while developing `foo`, I encounter no errors (obviously).
When I run `composer install` while developing `bar`, I encounter no errors.
When I run `composer install` while developing `baz`, I get the following error:

```sh
chris@fourside:~/src/baz$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for MyVendor/bar 1.0.0 -> satisfiable by MyVendor/bar[v1.0.0].
    - MyVendor/bar v1.0.0 requires MyVendor/foo 1.0.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

Through trial-and-error, I discovered that I can resolve this error by adding the following to the `composer.json` file in the `baz` module:

```javascript
//...
    "repositories" : [
      {
        "type" : "vcs",
        "url"  : "git@github.com:MyVendor/foo.git"
      }
    ],
//...
```
In other words, `baz` must be made aware of `foo`'s existence directly. Composer seems to be unable to properly resolve `bar`'s dependency on `foo` automatically when `foo` is hosted privately on Github.

In my opinion, this behavior is **extremely** counter-intuitive, as this seems to me to be a straightforward "dependency management" problem, which is Composer's _raison d'etre_.

It's possible that I've made some mistake in my diagnosis, as I've only been using Composer for about three months now. If there is a more appropriate way to accomplish what I'm trying to do, I'd appreciate some advice. Otherwise, I recommend that we give Composer the ability to resolve these dependencies automatically.

For reference:

```sh
chris@fourside:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.10
Release:        16.10
Codename:       yakkety

chris@fourside:~$ php --version
PHP 5.6.30-10+deb.sury.org~yakkety+2 (cli)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

chris@fourside:~$ composer --version
Composer version 1.1.3 2016-06-26 15:42:08
```

Thanks for your help, and for the work you've done.

**Comment by alcohol** [comment]
https://getcomposer.org/doc/faqs/why-can%27t-composer-load-repositories-recursively.md

**Comment by chrisallenlane** [comment]
Thanks.
