### ISSUE TITLE
Look “up” for composer.json if one doesn’t appear in the current folder

### ISSUE THREAD

**Issue by rachellawson** [composer/composer#6426]
When I run this command:

```
cd some/sub/folder
composer require xxx/yyy
```

And I expected the dependency to be added to the project’s composer dependencies.

But, I actually got a new, empty, composer.json file in the current folder.

It seems to me that we could have composer look to see if there is a composer.json file in the current folder and, if not, “look upwards” to see if one can be found. If it is, and the user confirms, it should add the dependency there.

Essentially, this should be the behaviour for all composer commands except `composer init`, I think

**Comment by bojanz** [comment]
Even if we don't want to look up, we should at least stop execution, cause the result will be unusable.

**Comment by alcohol** [comment]
This is the expected behaviour though. `composer require` will create a `composer.json` from scratch for you if there is not one currently in your working directory. Altering this behaviour would break backwards compatibility.

**Comment by bojanz** [comment]
But doesn't Composer operate under the assumption that each project has a root composer.json?
Below that level running composer require does nothing cause the downloaded files never reach the autoloader. And there's already composer init for initializing a new composer.json.
I'm not convinced there's any convenience gained by sacrificing this much UX.

**Comment by alcohol** [comment]
Composer does not, and has never, searched through a directory tree for the nearest `composer.json`. The current working directory is the only directory that matters. One can tell composer explicitly to use a given working directory through the `-d|--working-dir` flag.

**Comment by rachellawson** [comment]
Yes, I'm suggesting it could change that behaviour, to avoid errors by humans. 

The is no sense in a sub directory of a project to create a new composer.json file for any operation other than `composer init`, surely? It might seem like a convenience but, in practice, it just becomes an inconvenience. 

At the very least we could ask for a confirmation if the file does not exist at that location?

**Comment by bojanz** [comment]
@alcohol 
Yes, and it's fine not to search the directory tree.
What's not fine is accepting a "composer require" in a directory that produces no results to the user or the system.
I would either expect a hard error "hey, you're in the wrong directory" or at least a warning "looks like you're not in your project root, are you sure you want to continue".

**Comment by jvasseur** [comment]
@bojanz but it does produce a result, it creates an empty `composer.json` in the current directory and add the dependency to it.

**Comment by alcohol** [comment]
> The is no sense in a sub directory of a project (sp)

Except, to Composer, there is no such thing as a sub directory of a project since it does not look up in the tree, as I already told you. Each directory is simply a working directory, that either contains a `composer.json` or does not contain a `composer.json`.

**Comment by bojanz** [comment]
@jvasseur 
Yes, and after that it downloads the required project and creates a parallel vendor directory different from the one that's actually used.

@alcohol
Okay. Can we start by admitting that the current behavior is potentially very problematic from a UX perspective? As a maintainer of a large project I get about a complaint a day.
If we can agree that the current behavior is problematic, we can discuss BC and potential solutions, but there's no point in doing that if we're not on the same page.

**Comment by alcohol** [comment]
This is the first "complaint" that has been filed as an issue here since this project was created (to my knowledge). So I am not sure if "very problematic UX" is a suitable description. 

Whether or it is problematic is also very much a personal issue I believe. For me for example, the current behaviour is the correct behaviour. I use `make` a lot as well, and this also does not recurse the current directory tree to find the nearest `Makefile` to read. Nor do I know of or use any other tools that behave like this. So I have no expectations of Composer to do such a thing.

**Comment by stof** [comment]
@alcohol there is at least *one* tool doing such recursion: git

**Comment by rachellawson** [comment]
It is often the case with things like this that people won’t “complain” (I prefer “suggest improvement” - I wasn’t complaining) because they think they have done something “wrong”. Essentially they have, it’s just that the toll could be more “forgiving” of mistakes.

As far as other tools are concerned, I can only comment upon the ones I use and that’s not a lot:

- `make`: doesn’t look up the directory tree, just says that there is nothing to make. Importantly, though, it doesn’t add or change anything in the filesystem. So, doesn’t cause project “damage”  
- `vagrant`: looks back up the directory tree for a Vagrantfile and uses that. I do this every single day - it’s beautiful

**Comment by Seldaek** [comment]
IMO it could be done by looking up folders until at most the HOME dir, because if we reach that there might be some composer.json there that most probably isn't the "project". That said, it'd probably be best to do this by prompting the user with the suggestion, to make sure it's not accidentally doing something in the wrong folder.

**Comment by rachellawson** [comment]
/me is somewhat embarrassed she never thought of git!

**Comment by alcohol** [comment]
@stof yeah, and I have seen people make horrible mistakes thanks to that "feature" of `git`. While convenient, it also facilitates user-error. I guess Composer would be less susceptible to that since there is not much that could go "horribly" wrong. Unless you run Composer on production. But then again, you're kinda asking for it ;-)

Anyway, I am not opposed to changing this behaviour. Though I would not change it just for the `require` command. I would make it consistent for all commands. Just make sure that flags such as `-d|--working-dir` still work exactly as expected (for CI related jobs and such).

**Comment by Seldaek** [comment]
Yup it should be done globally in Application where we handle the -d flag, and only if the input is interactive.

**Comment by jvasseur** [comment]
I'm not sure what to think here. The current behavior is not intuitive but I relied on it a few times where I didn't care about creating a valid `composer.json` and just wanted to quickly add some dependencies to a new project.

**Comment by rachellawson** [comment]
Maybe something like...

```
prompt> composer require xxx/yyy
There is no composer.json file in the current working directory. 
I have found one at ../../composer.json - would you like me to use that as my working directory? [Y/n]
y
..........
```

**Comment by xabbuh** [comment]
For what it's worth: As @jvasseur said the current behaviour is quite useful for contexts where you don't care about your `composer.json` file being valid. For example, I use this a lot when trying to reproduce bug reports and I just need to quickly bootstrap a test environment.

**Comment by Seldaek** [comment]
We are not taking anything away here.. If you run a require command in 
some random directory without composer.json, and it can't find one 
above, it won't ask you and will create it in the current directory as 
is now the case.

If one is found above, then it prompts, and you still have the option to 
say no if you really want to create in the current dir.

**Comment by rachellawson** [comment]
Gah - fell foul of running composer in the wrong folder again today. It’s so easy to do and then weird things happen. At least having an “Are you really sure you want to create a new composer.json in this folder? Or do you want me to use the one in folder ../?” would be *really* helpful

**Comment by bojanz** [comment]
Thank you @Seldaek! Greatly appreciated.

**Comment by rachellawson** [comment]
Ha - @bojanz beat me to it - thank you @Seldaek!! It makes things less confusing for those new to modern tooling.
