### ISSUE TITLE
Composer is not trusting locally installed CAs on macOS

### ISSUE THREAD

**Issue by dserodio** [composer/composer#6427]
On macOS, to add custom CAs to openssl (installed via homebrew), one should copy the .pem file to `/usr/local/etc/openssl/certs` and run `/usr/local/opt/openssl/bin/c_rehash`, which creates a symlink to the certificate under `/usr/local/etc/openssl/certs` ([source](https://github.com/Homebrew/homebrew-core/blob/master/Formula/openssl.rb#L103-L108)).

At $WORK, we have an internal CA which is used to sign the SSL certificate used in our local composer repository (we use Artifactory). After installing our company's CA to the Mac's Keychain and also adding it to /usr/local/etc/openssl/certs and creating the appropriate symlink with c_rehash, every tool (openssl, curl, etc.) and language (PHP, Ruby, Python) recognize this CA, except for composer.

PHP itself does recognize said certificates:

```shell
$ php --version
PHP 5.6.30 (cli) (built: Mar 11 2017 09:56:18)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
$ php -r "file_get_contents('https://composer.intranet');"
$
```

However, composer does not recognize the certificates installed this way because it only reads the default bundle at `/usr/local/etc/openssl/cert.pem` (see the output from `composer install --prefer-dist -vvv` below).

----

My `composer.json`:

```json
{
    "repositories": [
        {"type": "composer", "url": "https://composer.intranet"},
        {"packagist": false}
    ]
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: WARNING
You are not running the latest stable version, run `composer self-update` to update (1.4.1 => 1.4.2)
```

When I run this command:

```
composer install --prefer-dist -vvv
```

I get the following output:

```
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /usr/local/etc/openssl/cert.pem: valid
Executing command (/private/tmp/composer-test): git branch --no-color --no-abbrev -v
Executing command (/private/tmp/composer-test): git describe --exact-match --tags
Executing command (/private/tmp/composer-test): git log --pretty="%H" -n1 HEAD
Executing command (/private/tmp/composer-test): hg branch
Executing command (/private/tmp/composer-test): fossil branch list
Executing command (/private/tmp/composer-test): fossil tag list
Executing command (/private/tmp/composer-test): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /Users/dserodio/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /private/tmp/composer-test/vendor/composer/installed.json
Running 1.4.1 (2017-03-10 09:29:45) with PHP 5.5.38 on Darwin / 15.6.0
Loading composer repositories with package information
Downloading https://composer.intranet/packages.json
Downloading https://composer.intranet/packages.json
Downloading https://composer.intranet/packages.json


  [Composer\Downloader\TransportException]
  The "https://composer.intranet/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
  error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
  Failed to enable crypto
  failed to open stream: operation failed


Exception trace:
 () at phar:///usr/local/Cellar/composer/1.4.1/libexec/composer.phar/src/Composer/Util/RemoteFilesystem.php:482
 Composer\Util\RemoteFilesystem->get() at phar:///usr/local/Cellar/composer/1.4.1/libexec/composer.phar/src/Composer/Util/RemoteFilesystem.php:101
 Composer\Util\RemoteFilesystem->getContents() at phar:///usr/local/Cellar/composer/1.4.1/libexec/composer.phar/src/Composer/Repository/ComposerRepository.php:661
 Composer\Repository\ComposerRepository->fetchFile() at phar:///usr/local/Cellar/composer/1.4.1/libexec/composer.phar/src/Composer/Repository/ComposerRepository.php:479
 Composer\Repository\ComposerRepository->loadRootServerFile() at phar:///usr/local/Cellar/composer/1.4.1/libexec/composer.phar/src/Composer/Repository/ComposerRepository.php:258
 Composer\Repository\ComposerRepository->hasProviders() at phar:///usr/local/Cellar/composer/1.4.1/libexec/composer.phar/src/Composer/DependencyResolver/Pool.php:99
 Composer\DependencyResolver\Pool->addRepository() at phar:///usr/local/Cellar/composer/1.4.1/libexec/composer.phar/src/Composer/Installer.php:376
 Composer\Installer->doInstall() at phar:///usr/local/Cellar/composer/1.4.1/libexec/composer.phar/src/Composer/Installer.php:223
 Composer\Installer->run() at phar:///usr/local/Cellar/composer/1.4.1/libexec/composer.phar/src/Composer/Command/InstallCommand.php:119
 Composer\Command\InstallCommand->execute() at phar:///usr/local/Cellar/composer/1.4.1/libexec/composer.phar/vendor/symfony/console/Command/Command.php:267
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/Cellar/composer/1.4.1/libexec/composer.phar/vendor/symfony/console/Application.php:846
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/Cellar/composer/1.4.1/libexec/composer.phar/vendor/symfony/console/Application.php:191
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/Cellar/composer/1.4.1/libexec/composer.phar/src/Composer/Console/Application.php:227
 Composer\Console\Application->doRun() at phar:///usr/local/Cellar/composer/1.4.1/libexec/composer.phar/vendor/symfony/console/Application.php:122
 Symfony\Component\Console\Application->run() at phar:///usr/local/Cellar/composer/1.4.1/libexec/composer.phar/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar:///usr/local/Cellar/composer/1.4.1/libexec/composer.phar/bin/composer:54
 require() at /usr/local/Cellar/composer/1.4.1/libexec/composer.phar:24

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
```

**Comment by alcohol** [comment]
Try specifying your custom `.pem` file in the following manner:

https://github.com/composer/composer/blob/14c77130e8f717ceb154720e1abefafe99124cb9/tests/Composer/Test/Config/Fixtures/config/config-with-exampletld-repository-and-options.json

**Comment by alcohol** [comment]
The options array corresponds to http://php.net/manual/en/context.ssl.php

**Comment by alcohol** [comment]
Composer determines which CA file to use through https://github.com/composer/ca-bundle/blob/master/src/CaBundle.php

**Comment by stof** [comment]
Well, configure your php.ini to also read another location, thanks to `openssl.cafile` or `openssl.capath`, and it should be taken into account

**Comment by brianlmoon** [comment]
I can add some more information to this issue. We have a private composer repo (satis) that uses our internal CA. After following the directions in `brew info openssl` for adding it to `/usr/local/etc/openssl/certs` and running a command to rehash the certs, `file_get_contents()` works fine.

```
 php -r "echo file_get_contents('https://composer.dealnews.net/packages.json');"
{
    "packages": [],
    "includes": {
        "include/all$8315899821511460e4a128d4ad33ebc0120436eb.json": {
            "sha1": "8315899821511460e4a128d4ad33ebc0120436eb"
        }
    }
}
```

However, `composer install` fails.

```
$ composer install
Loading composer repositories with package information

                                                                                                                                             
  [Composer\Downloader\TransportException]                                                                                                   
  The "https://composer.dealnews.net/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:  
  error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed                                                          
  Failed to enable crypto                                                                                                                    
  failed to open stream: operation failed                                                                          
```
After some debugging, I found that the issue is that CaBundle::getSystemCaRootBundlePath() returns _either_ a file _or_ a path. And this code in `RemoteFilesystem::getTlsDefaults` only sets _either_ a file _or_ a path.

```
        /**
         * Attempt to find a local cafile or throw an exception if none pre-set
         * The user may go download one if this occurs.
         */
        if (!isset($defaults['ssl']['cafile']) && !isset($defaults['ssl']['capath'])) {
            $result = CaBundle::getSystemCaRootBundlePath($caBundleLogger);

            if (is_dir($result)) {
                $defaults['ssl']['capath'] = $result;
            } else {
                $defaults['ssl']['cafile'] = $result;
            }
        }
```


I verified this with this script:

```
$opts = array(
    'ssl' => array(
        'cafile' => "/usr/local/etc/openssl/cert.pem",
    ),
);

$context = stream_context_create($opts);

echo file_get_contents("https://composer.dealnews.net/packages.json", false, $context);
```

That fails with the SSL error. Adding the path *and* the file, makes it work:

```
$opts = array(
    'ssl' => array(
        'cafile' => "/usr/local/etc/openssl/cert.pem",
        'capath' => "/usr/local/etc/openssl/certs"
    ),
);

$context = stream_context_create($opts);

echo file_get_contents("https://composer.dealnews.net/packages.json", false, $context);
```
I was able to get those locations from ``` php -r "var_dump(openssl_get_cert_locations());"
array(8) {
  ["default_cert_file"]=>
  string(31) "/usr/local/etc/openssl/cert.pem"
  ["default_cert_file_env"]=>
  string(13) "SSL_CERT_FILE"
  ["default_cert_dir"]=>
  string(28) "/usr/local/etc/openssl/certs"
  ["default_cert_dir_env"]=>
  string(12) "SSL_CERT_DIR"
  ["default_private_dir"]=>
  string(30) "/usr/local/etc/openssl/private"
  ["default_default_cert_area"]=>
  string(22) "/usr/local/etc/openssl"
  ["ini_cafile"]=>
  string(0) ""
  ["ini_capath"]=>
  string(0) ""
}
```
You need both. If you only set the path, then loading packagist.org fails.

It looks like if you don't set anything, it works fine. CaBundle is looking specifically for the homebrew openssl cert file. It picks that up and sets only the file. Hope this helps. I still don't have a work around. That is next I guess.

**Comment by alcohol** [comment]
> You need both. If you only set the path, then loading packagist.org fails.

Sorry but I cannot validate nor reproduce this statement.

I see in your example it is failing on a totally different domain though. So I'm going to assume for now that it is your host that is causing issue, and not https://packagist.org.

My repro attempt using file only:

```
rob@macbookpro.local /tmp > cat test.php
<?php

$opts = array(
    'ssl' => array(
        'cafile' => "/usr/local/etc/openssl/cert.pem",
    ),
);

$context = stream_context_create($opts);

echo file_get_contents("https://packagist.org/packages.json", false, $context);
```
```
rob@macbookpro.local /tmp > php test.php | json_pp
{
   "packages" : [],
   "providers-url" : "/p/%package%$%hash%.json",
   "provider-includes" : {
      "p/provider-archived$%hash%.json" : {
         "sha256" : "7a808bf19f27e2a2116fba474877ad621855e971aaf72f7523a2aa0535378b20"
      },
      "p/provider-2016$%hash%.json" : {
         "sha256" : "4b40992ea922d91126fa16579e3b43cf18d012260699757f8e70e22fbcf81466"
      },
      "p/provider-2017-01$%hash%.json" : {
         "sha256" : "f3c225f3d8eae22c38074a6a1ba38ea35a296bb4ae6ac1836312f63ca9a43f99"
      },
      "p/provider-latest$%hash%.json" : {
         "sha256" : "7ba3618410b41cd9ff638bc2b01b2578e1db0a9bba933975d5b72af49f58aa0b"
      },
      "p/provider-2017-04$%hash%.json" : {
         "sha256" : "f1eb3972573ede7b9b69b652abbbee038cfc74d44fcd10fc9a778854899c2992"
      },
      "p/provider-2017-07$%hash%.json" : {
         "sha256" : "8f771720bcd8373301d21722b4f86ee7700622ee599f416a8eb58461e43c80b9"
      },
      "p/provider-2014$%hash%.json" : {
         "sha256" : "32f91081a3c30452bdbfd4da7f20610e33289cd3f8ff30145d488e978acaa9d1"
      },
      "p/provider-2013$%hash%.json" : {
         "sha256" : "0ad7ef59ca768f30792ce0f683a0ba70af07c35f043705b4d23cca64deba7ee6"
      },
      "p/provider-2017-10$%hash%.json" : {
         "sha256" : "7d3c820fef18abe07e682472dbbc4155e6efa0b3b9995c03eb467743a4a4f858"
      },
      "p/provider-2015$%hash%.json" : {
         "sha256" : "77e3c0ff8dd2cf1889504715f1d252c54a45ecfdb2ba671f5b5a05288180b224"
      }
   },
   "notify-batch" : "/downloads/",
   "search" : "/search.json?q=%query%&type=%type%",
   "notify" : "/downloads/%package%"
}
```

My repro attempt using path only:

```
rob@macbookpro.local /tmp > cat test.php
<?php

$opts = array(
    'ssl' => array(
        'capatch' => "/usr/local/etc/openssl/certs",
    ),
);

$context = stream_context_create($opts);

echo file_get_contents("https://packagist.org/packages.json", false, $context);
```
```
rob@macbookpro.local /tmp > php test.php | json_pp
{
   "notify-batch" : "/downloads/",
   "notify" : "/downloads/%package%",
   "packages" : [],
   "search" : "/search.json?q=%query%&type=%type%",
   "providers-url" : "/p/%package%$%hash%.json",
   "provider-includes" : {
      "p/provider-2016$%hash%.json" : {
         "sha256" : "4b40992ea922d91126fa16579e3b43cf18d012260699757f8e70e22fbcf81466"
      },
      "p/provider-2017-10$%hash%.json" : {
         "sha256" : "7d3c820fef18abe07e682472dbbc4155e6efa0b3b9995c03eb467743a4a4f858"
      },
      "p/provider-2017-07$%hash%.json" : {
         "sha256" : "8f771720bcd8373301d21722b4f86ee7700622ee599f416a8eb58461e43c80b9"
      },
      "p/provider-2017-01$%hash%.json" : {
         "sha256" : "f3c225f3d8eae22c38074a6a1ba38ea35a296bb4ae6ac1836312f63ca9a43f99"
      },
      "p/provider-2015$%hash%.json" : {
         "sha256" : "77e3c0ff8dd2cf1889504715f1d252c54a45ecfdb2ba671f5b5a05288180b224"
      },
      "p/provider-2014$%hash%.json" : {
         "sha256" : "32f91081a3c30452bdbfd4da7f20610e33289cd3f8ff30145d488e978acaa9d1"
      },
      "p/provider-2017-04$%hash%.json" : {
         "sha256" : "f1eb3972573ede7b9b69b652abbbee038cfc74d44fcd10fc9a778854899c2992"
      },
      "p/provider-latest$%hash%.json" : {
         "sha256" : "7ba3618410b41cd9ff638bc2b01b2578e1db0a9bba933975d5b72af49f58aa0b"
      },
      "p/provider-2013$%hash%.json" : {
         "sha256" : "0ad7ef59ca768f30792ce0f683a0ba70af07c35f043705b4d23cca64deba7ee6"
      },
      "p/provider-archived$%hash%.json" : {
         "sha256" : "7a808bf19f27e2a2116fba474877ad621855e971aaf72f7523a2aa0535378b20"
      }
   }
}
```

**Comment by brianlmoon** [comment]
@alcohol I am sorry I did not include the example with only the path set. My custom cert is located in `/usr/local/etc/openssl/certs`. And our private repo is located at https://composer.dealnews.net/. So, this script:

```
<?php

$opts = array(
    'ssl' => array(
        'capath' => "/usr/local/etc/openssl/certs"
    ),
);

$context = stream_context_create($opts);

echo file_get_contents("https://composer.dealnews.net/packages.json", false, $context);

echo file_get_contents("https://packagist.org/packages.json", false, $context);
```

outputs:

```
$ php ~/tmp/test.php 
{
    "packages": [],
    "includes": {
        "include/all$8315899821511460e4a128d4ad33ebc0120436eb.json": {
            "sha1": "8315899821511460e4a128d4ad33ebc0120436eb"
        }
    }
}
PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /Users/brian/tmp/test.php on line 15

Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /Users/brian/tmp/test.php on line 15
PHP Warning:  file_get_contents(): Failed to enable crypto in /Users/brian/tmp/test.php on line 15

Warning: file_get_contents(): Failed to enable crypto in /Users/brian/tmp/test.php on line 15
PHP Warning:  file_get_contents(https://packagist.org/packages.json): failed to open stream: operation failed in /Users/brian/tmp/test.php on line 15

Warning: file_get_contents(https://packagist.org/packages.json): failed to open stream: operation failed in /Users/brian/tmp/test.php on line 15
```

**Comment by alcohol** [comment]
Well this makes even less sense. You get two different errors with the same context. I am sorry, but all signs indicate it is an issue on your side with your certificate. I simply cannot reproduce this on my end.

**Comment by brianlmoon** [comment]
@alcohol Maybe this script will help me be more clear.

```
<?php

function fetch_repos($opts) {
    $context = stream_context_create($opts);

    echo "Fetching Private Repository: ";
    $result = @file_get_contents("https://composer.dealnews.net/packages.json", false, $context);
    if($result !== false) {
        echo "OK\n";
    } else {
        echo "Failed\n";
    }

    echo "Fetching Packagist Repository: ";
    $result = @file_get_contents("https://packagist.org/packages.json", false, $context);
    if($result !== false) {
        echo "OK\n";
    } else {
        echo "Failed\n";
    }

}

echo "Using capath and cafile in context\n";
$opts = array(
    'ssl' => array(
        'cafile' => "/usr/local/etc/openssl/cert.pem",
        'capath' => "/usr/local/etc/openssl/certs"
    ),
);
fetch_repos($opts);
echo "\n";


echo "Using only capath in context\n";
$opts = array(
    'ssl' => array(
        'capath' => "/usr/local/etc/openssl/certs"
    ),
);
fetch_repos($opts);
echo "\n";


echo "Using only cafile in context\n";
$opts = array(
    'ssl' => array(
        'cafile' => "/usr/local/etc/openssl/cert.pem"
    ),
);
fetch_repos($opts);
echo "\n";
```
output:
```
$ php ~/tmp/test.php 
Using capath and cafile in context
Fetching Private Repository: OK
Fetching Packagist Repository: OK

Using only capath in context
Fetching Private Repository: OK
Fetching Packagist Repository: Failed

Using only cafile in context
Fetching Private Repository: Failed
Fetching Packagist Repository: OK
```

**Comment by brianlmoon** [comment]
The workaround I have found so far is to cat our private CA file into cert.pm. It's not ideal and not how PHP + OpenSSL is supposed to work. The docs for capath says:

If cafile is not specified **or** if the certificate is not found there, the directory pointed to by capath is searched for a suitable certificate. capath must be a correctly hashed certificate directory.

**Comment by alcohol** [comment]
It only proves my case even more. There is something wrong with your certs. I simply cannot reproduce this scenario.

**Comment by brianlmoon** [comment]
How does that prove there is something wrong with my certs? I do not follow. What I know is that if I provide no context, PHP works just fine with my certs. That means my certs are installed correctly as far as the openssl defaults are concerned. It's only when I provide only the cafile or capath and not both that things stop working.

**Comment by NBZ4live** [comment]
I agree with @brianlmoon the problem is that composer provides only file or directory and not both.
I'm now in the same situation and everything on my mac works nice with the certificates, everything that uses openssl. Except for composer.

Imho composer should have an option/setting to disable the ca-bundle and use the defaults of PHP and OpenSSL.

I'l try to explain it better.

If you specify both cafile and capath, than (like @brianlmoon already mentioned) first it will try to use the cafile and than fallback to the certs in capath.

In the current case composer provides only one of them and forces the usage of only one of them.

This leads to the case that if you provide a cafile it will work for everything which is signed by an official authority. If you provide capath with your custom authority certificate, than only this will be used and not the official CAs.
This will make your custom domain working (which is signed with a cert file from capath) but will fail on packagist.org because it is signed by an authority from cafile which was not provided to the context.

This is not the intended behaviour of OpenSSL and breaks composer if you want to use satis hosted on a domain signed by your companies CA and Packagist in parallel.

**Comment by Nijusan** [comment]
Any Update on this issue? @NBZ4live has perfectly described the problem. we are facing the exact same problem and the only current solution is to add the company certificate into the pem-file used by composer.
it works fine until a brew upgrade updating openssl. then u have to redo the copy...

**Comment by datort** [comment]
We have the same situation perfectly described by @NBZ4live. As a workaround we've added the PEM in question to the /usr/local/etc/openssl/cert.pem, which results in composer not able to connect to our internal systems after you run a brew upgrade on openssl.

**Comment by NBZ4live** [comment]
For everybody suffering:
At the moment we are working this around on dev machines by copying the pem to home directory and appending the custom CA. This requires maintenance only in case of a change of related official CA.

On build servers, we will automerge native pem with custom CAs to a temporarily file as a build step before running composer with SSL_CERT_FILE, which is a very, very bad behaviour, but currently the only solution which currently works without future maintenance on build server, avoiding unexpected outage.

**Comment by alcohol** [comment]
Descriptions of problems aren't going to solve the problem. I'm willing to take the time to review proposed solutions if someone is willing to invest the time to come up with one. Seeing as there are only a few edge-case scenarios where this is necessary, I simply cannot invest the time myself right now. We don't get paid for any of this.

**Comment by adjenks** [comment]
I am encountering the same problem. I can wget and curl my server but composer does not work.

Fails:
`wget https://myserver.com/satis/repo/packages.json`
Works fine:
`wget --ca-certificate mycert.pem https://myserver.com/satis/repo/packages.json`

Fails:
`curl https://myserver.com/satis/repo/packages.json`
Works fine:
`wget --cacert mycert.pem https://myserver.com/satis/repo/packages.json`

Fails:
```
{
	"name": "My Package",
	"repositories": [{
			"type": "composer",
			"url": "https://myserver.com/satis/repo/"
		}, {
			"type": "composer",
			"url": "https://packagist.org/"
		}
	]
}
```

ALSO fails:
```
{
	"name": "My Package",
	"repositories": [{
			"type": "composer",
			"url": "https://myserver.com/satis/repo/"
		}, {
			"type": "composer",
			"url": "https://packagist.org/"
		}
	],
	"cafile": "mycert.pem"
}
```

I also tried using capath in the root of composer.json and also tried inserting it in the options.ssl section.

The users above seem to be describing a similar problem to what I am experiencing. I even tried disabling antivirus and firewall, as described in #6870 .
Nothing seems to be working.
I'm on version 1.7.2

**Comment by adjenks** [comment]
When I tell it to use extra verbose output it says `Checked CA file /my/path/mycert.pem: valid`
But still fails.

**Comment by adjenks** [comment]
Solution proposed: Do whatever wget and curl do, because they work fine for me, only composer is not working. It seems like it's just not actually using the ca-cert that I'm providing to it.

**Comment by mariusbalcytis** [comment]
As a temporary workaround I've added certificates to the end of `/usr/local/etc/openssl/cert.pem` and provided it in the `php.ini` as `openssl.cafile`.

**Comment by karudonaldson** [comment]
**Mac OS X:**
Look for the location of your cafile by:
`php -r 'var_dump(openssl_get_cert_locations());'`
Then set composer to use this (with the example in my case):
`composer config --global cafile '<location of cafile>'`
Example:
`composer config --global cafile '/usr/local/etc/openssl/cert.pem'`

**Windows:**
https://support.microsoft.com/en-us/help/931125/how-to-get-a-root-certificate-update-for-windows

**Linux**
Debian:
apt-get install --only-upgrade ca-certificates

RedHat / CentOS:
yum update ca-certificates                        

Ref: https://typo3.org/article/certificate-issue-with-composer/

**Comment by fantomas662** [comment]
Still an issue in Composer 1.9.0.

Setting `openssl.cafile` and `openssl.capath` in *php.ini* instead of relying on defaults "fixes" this, but it shouldn't be required. PHP works fine with the defaults, but Composer breaks this with unnecessary stream options.

**Comment by MGHollander** [comment]
Wwth a small addition the [workaround](#issuecomme@karudonaldson) provided by @karudonaldson worked for me. I needed to append the company certificate to the `cert.pem` file.

**Comment by 234146326** [comment]
> `composer config --global cafile '/usr/local/etc/openssl/cert.pem'`

If this .pem file is accidentally deleted.How should it be regenerated?thank you for your reply.the Lord;

**Comment by adjenks** [comment]
@234146326 I think you should open a different ticket for that.

**Comment by 234146326** [comment]
> @234146326 I think you should open a different ticket for that.

https://github.com/composer/composer/issues/8992

**Comment by beryllium** [comment]
This issue came up for me today as well. Since Composer 2.0 is coming soon, it would be nice to get the issue resolved so that satis environments can work cleanly on macOS. How can I help move this forward?

**Comment by adjenks** [comment]
My error wasn't in MacOS, it was linux. The problem seems to be with using CA certs in general.
