### ISSUE TITLE
Loading a package from a forked repository

### ISSUE THREAD

**Issue by odai-alali** [composer/composer#6433]
I folowed [this](https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository) documentation and forked yii2 repository and created a branch with the name *dev-additor* and added the folowing lines to my composer.json 

```json
"repositories":[
      {
        "type":"vcs",
        "url":"https://github.com/odai-alali/yii2"
      }
    ],
    "require": {
        "yiisoft/yii2": "dev-additor"
    }
```

When I run this command:

```
composer install
```

I get the following output:

```
  Problem 1
    - The requested package yiisoft/yii2 dev-additor exists as yiisoft/yii2[2.0.0, 2.0.0-alpha, 2.0.0-beta, 2.0.0-rc, 2.0.1, 2.0.10, 2.
0.11, 2.0.11.1, 2.0.11.2, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, dev-master, 2.0.x-dev] but these are rejected by your
 constraint.
```
the composer version is 1.4.2
any help is appreciated.

**Comment by Seldaek** [comment]
That repo contains the yii2-dev package not the yii2 one.. https://github.com/odai-alali/yii2/blob/master/composer.json#L2 so it won't find it with the right branch.
