### ISSUE TITLE
Magento : Fatal error: Couldn't find implementation for method Zend\Stdlib\Parameters::getiterator in Unknown on line 0

### ISSUE THREAD

**Issue by ravichandrarv** [composer/composer#6439]
Magento : Fatal error: Couldn't find implementation for method Zend\Stdlib\Parameters::getiterator in Unknown on line 0

i got this error after enabling UPS on checkout.

**Comment by Seldaek** [comment]
I don't think this belongs on this repository.. seems like a magento issue, not composer related.
