### ISSUE TITLE
getcomposer.org page not working

### ISSUE THREAD

**Issue by lijoev** [composer/composer#6442]
composer.org page is down. i have been waiting for so long to get the composer installed in my system and for proper documentation. can anyone help me to troubleshoot it.

**Comment by scaytrase** [comment]
do you mean https://getcomposer.org/ ?

**Comment by lijoev** [comment]
yes it is

**Comment by Seldaek** [comment]
The site is up but we might have reachability issues in some places, follow https://github.com/composer/composer/issues/6342 for updates
