### ISSUE TITLE
Composer Slow / Timeout on  Updating dependencies

### ISSUE THREAD

**Issue by edgework** [composer/composer#6443]
My `composer.json`:

```json

{
    "require": {
        "predis/predis" : "^1.1.1",
        "sergeytsalkov/meekrodb": "^2.3",
        "monolog/monolog": "^1.22"
    }
}

```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
php composer.phar install --verbose
```

I get the following output:  **SOMETIMES**

```
Updating dependencies (including require-dev)

Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
```

And I expected this to happen:

It to work and quickly

Since May 22nd  composer installs have been REALLLLLYYYYY SLOOOWWWW and sometimes don't complete at all.  It usually hangs at  Updating dependencies (including require-dev)  and sometimes I get the above timeout error,  or other errors related to timeout.   This happens at work on an AT&T 300GB fiber connection,  at home on Comcast and in AWS.

Also --verbose  doesn't add anything to the output at all

**Comment by Seldaek** [comment]
Please subscribe to https://github.com/composer/composer/issues/6342

**Comment by edgework** [comment]
I don't see who that is related.  None of it applies to me!

**Comment by pmatias** [comment]
@edgework it does, `Failed to decode response: zlib_decode(): data error` means that there was a networking issue.

**Comment by pmatias** [comment]
#6342 is the main issue to refer for this.

**Comment by edgework** [comment]
http://packagist.org/p/provider-2017-01%24fe24b71e82be122e5862af906635199541751a7225ba325a6079be4df974125b.json  downloads immediately and is perfectly valid.  The processing of it is what is stalling.  @pmatias
