### ISSUE TITLE
Failed to decode response: zlib_decode(): data error

### ISSUE THREAD

**Issue by jhabdas** [composer/composer#6444]
Travis was failing most of the day for no apparent reason with the following:

```
Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
Installation failed, deleting ./composer.json.
                                            
  [Composer\Downloader\TransportException]  
  Content-Length mismatch  
```

The linked doc said to open an issue so I am. But I've already solved my own problem by using a debugging technique I call the _jiggle the keys_ approach. Which is to say sometimes you don't need to make sense of an error. You simply change the things which might be causing it until it fixes itself. Get it?

<img width="722" alt="screen shot 2017-05-23 at 11 53 31 pm" src="https://cloud.githubusercontent.com/assets/440298/26363297/2e29a314-4013-11e7-9c6f-319cf36b8988.png">

Here's a steady list of failures and the approach applied by removing and simply reverting the removal of `--prefer-dist` during Composer installation for those who need to solve similar issues and don't want to create a headache out of it: https://github.com/comfusion/hyperdrive/pull/45

**Comment by jhabdas** [comment]
Scratch that. I'll be squashing those commits. Just take my word for it. Because it started happening again. Sometimes a cache clearing refresh will do it for you depending on CI. Sometimes it helps to simply extend to a a new branch and push to origin with things start to go awry.

**Comment by jhabdas** [comment]
Also an exceptional time to go make a sandwich.

**Comment by xabbuh** [comment]
see https://github.com/composer/composer/issues/6342#issuecomment-303430990
