### ISSUE TITLE
Composer will not install anything anywhere?!

### ISSUE THREAD

**Issue by rick-rheo** [composer/composer#6445]
My `composer.json`:

```
ANY COMPOSER.JSON
```

Output of `composer diagnose`:

```
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK

```

When I run this command:

```
install
```

I get the following output:

```
.........   nothing or ssl errors 
```

And I expected this to happen:

I get dependencies.

**Comment by brunoneve** [comment]
my diagnose

Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: WARNING
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: SSL: Handshake timed out
Failed to enable crypto
failed to open stream: operation failed
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK

**Comment by griffithtp** [comment]
@rick-rheo add 
```
{
  "license": "proprietary",
  "name" : "vendorname/projectname",
  "description": "",
}
```
https://getcomposer.org/doc/04-schema.md#name

#### Mine fails on `Failed to decode response: zlib_decode(): data error`

**Comment by brunoneve** [comment]
I too, zlib_decode(): data error

**Comment by eesquibel** [comment]
I was getting the same error about 50min ago, though it seems to have cleared up within the last 5 or 10 minutes.

**Comment by Seldaek** [comment]
Fixed now

**Comment by falalal** [comment]
[
![image](https://user-images.githubusercontent.com/43725731/48127014-b2b98880-e2bd-11e8-9b72-ae8d0f2c3a54.png)
](url)

**Comment by falalal** [comment]
How to solve this problem?Help~

**Comment by falalal** [comment]
![image](https://user-images.githubusercontent.com/43725731/48127146-fc09d800-e2bd-11e8-9f65-aed677cdfdfa.png)
我想下载这个扩展，但是失败了。。

**Comment by stof** [comment]
this error says that DNS for `packagist.phpcomposer.com` cannot be resolved. This is either an issue with your network setup, or an issue with packagist.phpcomposer.com, which is not an official composer repository (and so is not maintained by the composer team).

**Comment by stof** [comment]
https://downforeveryoneorjustme.com/packagist.phpcomposer.com tells me that it seems to be an issue on their side though.

**Comment by SufyanNaseer1** [comment]
![sufyan](https://user-images.githubusercontent.com/70169305/91595656-571e2a80-e97d-11ea-8ce7-e8c9f7027352.PNG)
sir please solve the problem

**Comment by Seldaek** [comment]
@SufyanNaseer1 you need to run `composer install` not just `install`.
