### ISSUE TITLE
Composer is not finding Git tags

### ISSUE THREAD

**Issue by HillTravis** [composer/composer#6446]
My `composer.json`:

```json
{
	"name": "mycompany/myproject",
	"repositories": [
		{
			"type": "vcs",
			"url": "ssh://git@my-git-repo.com/mycompany/my-package.git"
		},
		{
			"type": "vcs",
			"url": "ssh://git@my-git-repo.com/mycompany/my-other-package.git"
		}
	],
	"require": {
		"php": ">=5.4.0",
		"mycompany/my-package": "1.0"
	}
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.mycompany/my-package : exact version constraints (1.0) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer install
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)           
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package mycompany/my-package could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

And I expected this to happen:
The package is installed correctly. I *DO* have a Git tag labeled v1.0 that has been pushed to the remote, but Composer does not seem to find it. It does find the commit SHA that has the tag, but doesn't find the tag itself. Here is the output of `composer show --all mycompany/my-package`:

```
name     : mycompany/my-package
descrip. : my-description
keywords : 
versions : dev-master
type     : library
source   : [git] ssh://git@my-git-repo.com/mycompany/my-package.git 63ceb5cda08a049d2a20e76c1a39b18fe44af374
dist     : []  
names    : mycompany/my-package

requires
php >=5.4.0
mycompany/my-other-package 1.7
monolog/monolog 1.22.1
```

If I omit the `--all` flag, I get the same error as indicated above. I've tried deleting my `~/.composer/cache` directory and I still get the same result.

**Comment by HillTravis** [comment]
As a test, I also tried cloning the git repo from the cached .git repo in `~/.composer/cache/vcs` and checking the tags, and `v1.0` is shown. So the cached version has the tag in it, but Composer still doesn't seem to find it.

**Comment by HillTravis** [comment]
My sincerest apologies. Some bonehead added a `version` entry in the package's composer.json file.

**Comment by RickKukiela** [comment]
I have this same exact problem except there is no version tag in my composer.json file. There is a tag but if I try to use it then composer does not find the package. If I use "dev-master" it works fine. The repo is a local path. I'm really lost at why this is not working. This is my first time trying to set this up :/

**Comment by tallcoder** [comment]
Having the same problem here. But, there's no "version" ... composer just doesn't see my new tag. I've deleted and created diff tags but none of them are being found by composer. I was really hoping this thread had some answers in it. :-\

**Comment by celorodovalho** [comment]
I have the same problem here!
Any ideas?

**Comment by HillTravis** [comment]
Sorry I can't help. I haven't used PHP since the original post.

**Comment by roman-w3lifer-grinyov** [comment]
In my case, Git was not installed  in the Docker container.
