### ISSUE TITLE
ErrorException Use of undefined constant CURLOPT_HTTPGET

### ISSUE THREAD

**Issue by ktomk** [composer/composer#6448]
Just a minor issue: When starting composer w/o curl extension installed composer greets with just an ErrorException with message "Use of undefined constant CURLOPT_HTTPGET - assumed 'CURLOPT_HTTPGET'".

It would be more comfortable for a user to see a message that a (the) required php extension is not available.

**Comment by stof** [comment]
Composer does not use curl at all. Look at the stack trace of the exception. I suspect it comes from a plugin

**Comment by ktomk** [comment]
Oh, good hint, have not run `-vvv`. Will report it to hirak/prestissimo.

**Comment by ktomk** [comment]
Ref: https://github.com/hirak/prestissimo/issues/145
