### ISSUE TITLE
update --no-dev fails because of a require-dev module

### ISSUE THREAD

**Issue by ennorehling** [composer/composer#6450]
My `composer.json`:

```json
{
    "require-dev": {
        "etsy/phan": "dev-master"
    },
    "require": {
        "phpseclib/phpseclib": "~2.0",
        "drush/drush": "8.*"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
php composer.phar update --no-dev
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - etsy/phan dev-master requires ext-ast ^0.1.4 -> the requested PHP extension ast is missing from your system.
    - etsy/phan dev-master requires ext-ast ^0.1.4 -> the requested PHP extension ast is missing from your system.
    - Installation request for etsy/phan dev-master -> satisfiable by etsy/phan[dev-master].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php.ini
   [...]
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

And I expected this to happen:

Since etsy/phan is a dev requirement (only listed in the require-dev section), and I specified --no-dev, I expect that the missing dependency (the ast.so extension is not loaded in php.ini for our non-developer machines) would not be an issue. Why is composer trying to install it, when I specifically told it not to?

**Comment by Seldaek** [comment]
Updating requires dev requires to be solvable, that's a known technical limitation, and isn't generally an issue as you should only run updates on dev machines.

You can use --ignore-platform-reqs to ignore any missing extension.

See also #5224, #5227, #5444, #5547, #5523, #6416 for previous duplicate issues.

**Comment by ennorehling** [comment]
Thanks. It appears I didn't understand the intended workflow of composer (this is my first project to use it), and most of all, the composer.lock file. I've figured it out.
