### ISSUE TITLE
Use GitLab v4 API (with anonymous access to public repos)

### ISSUE THREAD

**Issue by alecpl** [composer/composer#6453]
First of all v3 API will be removed in August (https://docs.gitlab.com/ce/api/v3_to_v4.html).

But I came here from https://gitlab.com/gitlab-org/gitlab-ce/issues/32226 and other closed tickets that asked for public repositories support without need to authenticate to GitLab. It looks it should be possible with v4.

**Comment by mlncn** [comment]
@alecpl Do you think  https://gitlab.com/gitlab-org/gitlab-ce/issues/32300 won't be necessary then?

**Comment by alecpl** [comment]
@mlncn I think so. This API should be used to get project metadata. Then as I understand, my usecase which is "make Gitlab repositories accessible for non-authenticated users" will be possible. The whole need for this comes from the fact that currently it's not possible to get package from Gitlab public repo without authentication using composer. See #4744 (which is related).

**Comment by alecpl** [comment]
I meant, I think it will be necessary. It is part of v4 API as I understand.

https://docs.gitlab.com/ce/api/projects.html#get-single-project

**Comment by Seldaek** [comment]
@alecpl I'd be happy if you can `composer self-update --snapshot` and then try with the latest version if everything still goes well for you. I did some basic testing but I don't have very interesting data on gitlab..

**Comment by alecpl** [comment]
@Seldaek It looks working for my needs. Thank you very much.
