### ISSUE TITLE
Fail Composer execute (quotes)

### ISSUE THREAD

**Issue by webadequate** [composer/composer#6454]
Hello!
I have some trouble with Composer. On windows 10 did Path environments _C:\OpenServer\modules\php\PHP-7.1-x64_ here PHP interpreter and **composer.phar** and **composer.bat**

When I run this command:

composer

I get the following output:

'""' is not recognized as an internal or external command,
operable program or batch file.

Any ideas how execute composer?

**Comment by alcohol** [comment]
@johnstevenson any idea what could be wrong here?

**Comment by johnstevenson** [comment]
@webadequate Have you tried using the Composer-Setup.exe installer?

If the path was set up incorrectly, then this error would be _'Composer' is not recognized as an internal or external command..._, so the composer.bat file must be doing something strange.

**Comment by webadequate** [comment]
@johnstevenson Yes, via installer.
I try direct executing _C:\OpenServer\modules\php\PHP-7.1-x64\composer.bat_ but the same 

> '""' is not recognized as an internal or external command,
> operable program or batch file.

**Comment by johnstevenson** [comment]
Thanks. Could you please run the installer again, then create an issue here: https://github.com/composer/windows-setup/issues/new

Please provide a log file (as per the new issue instructions), so we can see where everything is.

**Comment by johnstevenson** [comment]
@alcohol https://github.com/composer/windows-setup/issues/70
