### ISSUE TITLE
composer update not cleaning up after clone operation

### ISSUE THREAD

**Issue by mph2labs** [composer/composer#6456]
when running **composer update** and the zip unzip packages are missing on the system, you get the following error (this happens for every dependency not just the below):

`Failed to download symfony/polyfill-mbstring from dist: The zip extension and unzip command are both missing, skipping.`

then composer (I guess) clones the source and builds locally as I see a message like

`Installing symfony/polyfill-mbstring (v1.3.0): Cloning e79d363049 from cache`

What I believe is an issue, is that once the  clone operation is done and the package has been updated, there is no clean up operation resulting in massive use up of space. Which is an issue when using containers. In a recent docker container image I was working on, I saw it's size go up from 545mb to 1.8gb as a result of this.

Since composer can work without zip/unzip, I suggest a fix to cleanup when using clone.

**Comment by alcohol** [comment]
Either mount a `COMPOSER_HOME` directory form your host temporarily into your container (so you generate and persist the cache on your host system), or simply set the `COMPOSER_CACHE_DIR` env variable to `/dev/null` to skip building a cache completely.

No need to suggest fixes for non-existent problems :-)

**Comment by mph2labs** [comment]
thanks for taking the time to reply. I agree no need for a fix to non existent problem :-)  

I went with COMPOSER_CACHE_DIR=/dev/null /usr/local/bin/composer update in my DockerFile and I can confirm file size does not increase. 

happy days
