### ISSUE TITLE
composer dumpautoload --no-dev still includes dev dependencies

### ISSUE THREAD

**Issue by Firehed** [composer/composer#6457]
My `composer.json`:

```json
{
    "name": "firehed/certbot-cloudflare",
    "description": "Certbot hooks for Cloudflare DNS verification",
    "license": "MIT",
    "autoload": {
        "psr-4": {
            "Firehed\\Cloudflare\\": "src/"
        }
    },
    "require-dev": {
        "kherge/box": "^2.7"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer dumpautoload --no-dev
cat vendor/composer/autoload_files.php
```

I get the following output:

```
<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'decc78cc4436b1292c6c0d151b19445c' => $vendorDir . '/phpseclib/phpseclib/phpseclib/bootstrap.php',
    '742b7e606e92b28dd726e835467f413a' => $vendorDir . '/herrera-io/json/src/lib/json_version.php',
    '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => $vendorDir . '/symfony/polyfill-mbstring/bootstrap.php',
    'f0e9d233388e461ee3c460665eb265f0' => $vendorDir . '/herrera-io/phar-update/src/lib/constants.php',
);
```

And I expected this to happen:

No files should be included by the autoloader, since `--no-dev` was specified and there are no explicitly autoloaded files outside of those that exist from development dependencies. This applies to all of the required autoload files (namespaces, psr-4, etc), not just `autoload_files.php`.

Performing `composer install --no-dev` and subsequently re-dumping the autoloader (with or without the flag) produces the expected output in `vendor/composer/`

**Comment by alcohol** [comment]
I am confused. Nowhere in our documentation do we say that `dump-autoload` supports the `--no-dev` flag. What makes you think otherwise?

https://getcomposer.org/doc/03-cli.md#dump-autoload

**Comment by jvasseur** [comment]
The documentation of the `dump-autoload` command says
> --no-dev                   Disables autoload-dev rules.

This option is only used to control if you take into account the `autoload-dev` part of the root `composer.json`.

**Comment by alcohol** [comment]
I think you are confused. It will still skip the `autoload-dev` definitions of your root package when you pass `--no-dev`, but the definitions you see in your generated autoload files belong to your installed dependencies. Those are not `autoload-dev` definitions. Those are regular `autoload` definitions of your `require-dev` dependencies. `--no-dev` for the dump autoload command is not the same as `--no-dev` for the `install` command.

**Comment by Firehed** [comment]
I can certainly see that, but I also hope you see where I'm coming from when I interpret `--no-dev` to imply that the command should exclude *all* development dependencies - especially since this is the behavior everywhere else that the option is supported (to the best of my knowledge, at least); quite counter to the "principle of least surprise".

If you disagree I can understand that, though I would really appreciate an explanation of why you feel that the current behavior is correct.

In either outcome I am happy to lend a hand where possible, either by updating the built-in documentation of the command or by filtering what makes it into the autoload dumper.

**Comment by alcohol** [comment]
I neither agree nor disagree. As I have been using Composer for a very long time, I have simply come to accept things as they are. To me, it make sense, because it has worked like this since it was implemented.

I can imagine that for new users, some of the options or features we offer, may not seem as straight forward or obvious, or sometimes may even appear a little counter-intuitive.

I think the documentation (or rather, lack of) plays a big part here too. In a lot of cases, it is rather brief and probably makes too many assumptions about how users perceive things.

I personally feel that the `--no-dev` flag, as part of the `dump-autoload` command, in its current state works as intended. The command simply generates the autoload files based on all currently installed packages (this could be documented more explicitly perhaps). The `--no-dev` flag is merely meant to ommit the `autoload-dev` definition from your root composer.json. This is something that you would use when generating a optimized production ready set of autoload files, e.g.:

```
composer install --no-dev && composer dump-autoload --no-dev --optimize

// which can be shortened to
composer install --no-dev --optimize-autoloader

// or even more securely (but don't use this during development)
composer install --no-dev --classmap-authoritative
```

**Comment by jvasseur** [comment]
The problem with changing the current behavior is that the `dump-autoload` command created the autoloader based on the installed packages (that could be out of date with the composer.lock) and to do so it use the `installed.json` file that doesn't contains the information if a packages is a dev or a normal requirement.

**Comment by theofidry** [comment]
@jvasseur one way or another, the problem is still there, you cannot use `--no-dev` as soon as you have a file in your `require-dev` as this would break the application.
