### ISSUE TITLE
Update command does not add "dist" section to lock file

### ISSUE THREAD

**Issue by ZZromanZZ** [composer/composer#6462]
My `composer.json`:
```json
...
"repositories": [
    {
         "type": "composer",
         "url": "https://example.com/"
    }
],
...
```
I generated my own packages.json file without dist versions on my repository, but recently I switched to Satis, which can provide zipped "dist" versions of my packages.

When I run "composer update" (no matter if --prefer-dist is specified or not), "dist" sections in composer.lock are added only for packages that are actually updated.

Expected behaviour:
Composer update command will add "dist" section for all packages in composer.lock, no matter if package is actually updated or not . This allows speed-up installing packages which has not been updated yet.

**Comment by alcohol** [comment]
Unfortunately your expectation cannot be met because this is simply not how composer works.

**Comment by mmenozzi** [comment]
@ZZromanZZ you can met your expectations by removing the `vendor` folder and then run `composer update`.
