### ISSUE TITLE
Fatal error: Class 'PD0' not found in /var/www/html/c_login/resource/Database.php on line 8

### ISSUE THREAD

**Issue by andercodder** [composer/composer#6463]
/*my home page */
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Homepage</title>
</head>
<body>
<h2>User Authentication System </h2><hr>

<?php

 include_once 'resource/Database.php';

 ?>

</body>
</html>
// my database code
<?php

error_reporting(E_ALL);
ini_set('display_errors', 1);

$db = new PD0('mysql:localhost;dbname=register', 'andre', 'mysql.d3b1an1000!');

echo "conneted to register database";
?>
``

**Comment by alcohol** [comment]
Install the PDO extension for PHP. This is not a composer issue.

**Comment by renanbr** [comment]
Furthermore, it seems rather a typo `PDO` != `PD0`

**Comment by andercodder** [comment]
sorry for disturbing...very thank you i could solve it was really PD0 instead of PDO @renanbr
