### ISSUE TITLE
errors with installing laravel

### ISSUE THREAD

**Issue by shimamsh** [composer/composer#6470]
while calling  composer config -g disable-tls true in command and then calling composer create-project --prefer-dist laravel/laravel blog i faced with this error : your configuration does not allow connection to htttruees.json. versus while calling composer config -g disable-tls false and then calling composer create-project --prefer-dist laravel/laravel blog i faced with this error : the openssl extension is required for SSL/TLS protection but is not available .if you can not enable openssl extension.you can disable this error by setting disable-tls to true!!!
now what should i do?

**Comment by Seldaek** [comment]
Sorry but we are not a php helpdesk.. As the error says you have to enable the php openssl extension in your php.ini, you can surely figure out how to do that in the documentation (or google) of whatever method you use to run php.
