### ISSUE TITLE
Inconsistent fallback for missing "version" property in packages for »path« & »artifact« repositories

### ISSUE THREAD

**Issue by pixelbrackets** [composer/composer#6472]
Hi :) I played around with the repository types »path« and »artifact« and noticed an inconsistent behaviour for version fallbacks.

I created a folder with two packages. Both do not have a »version« property in the `composer.json`.
* https://github.com/pixelbrackets/composer-test-multiple-packages/tree/master/packages/

I also compressed these packages and saved them as ZIP-files in another container.
* https://github.com/pixelbrackets/composer-test-multiple-packages/tree/master/packages-as-zip-files/

When I require the packages using the »path« repository type, then the driver falls back to »dev-master« if the »version«-property is missing in the packages.
* https://github.com/pixelbrackets/composer-test-multiple-packages/blob/master/composer-repo-with-relative-path/composer.json

When I require the packages using the »artifact« repository type, then the driver requires a »version«-property in the packages. It is not possible to omnit this property, as in »path« (In the example I did add a version just before adding them to the ZIP-file, and required these exact versions in the dummy project then, so it will work → when I omnit the version it will fail).
* https://github.com/pixelbrackets/composer-test-multiple-packages/blob/master/composer-repo-with-zip-packages/composer.json

Reason:

The »path« repository sets »dev-master« as fallback, if no version was found.
* https://github.com/composer/composer/blob/master/src/Composer/Repository/PathRepository.php#L145-L148

The »artifact« repository used to have the same fallback, but it was removed some days later without any explaination.
* Fallback added https://github.com/composer/composer/commit/b5e1457470df6b4ff373d10236663fd27599d6fc
* Fallback removed https://github.com/composer/composer/commit/07920c48a692114f3a4eb8784ad696b063ddb9d0

Imho both should either require a version property, or use a fallback. The later is my expected behaviour.

**Comment by alcohol** [comment]
The reason behind the "removal" was discussed here (it was never actually added, the add + removal commits exist in the same branch/PR, which was not squashed):

https://github.com/composer/composer/pull/1728#discussion-diff-3634511

**Comment by alcohol** [comment]
Not sure how @Seldaek feels about changing the default.

**Comment by Seldaek** [comment]
The thing is the path repo typically points to a git repo or something where we can infer a version, so the fallback is rarely used there. In artifact repo, without version information you basically have invalid packages and IMO it's good to force the archives to be constructed correctly.

I don't really see the benefit of removing the fallback in path repo as it just introduces a potential pain point. I definitely don't think we should add one to the artifact repo though.

And by the way vcs repo also allows you to work without version specified for example, but package requires that you provide one.. It's not really inconsistent it's just that every repository has different usage patterns.
