### ISSUE TITLE
why all packages are installed when I just need laravel ??

### ISSUE THREAD

**Issue by akehsanz** [composer/composer#6473]
**My `composer.json`:**
{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
	"require": {
		"laravel/framework": "4.2.*"
	},
	"autoload": {
		"classmap": [
			"app/commands",
			"app/controllers",
			"app/models",
			"app/database/migrations",
			"app/database/seeds",
			"app/tests/TestCase.php"
		]
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	},
	"minimum-stability": "stable"
**Output of `composer diagnose`:**
... just a newbie here, not run yet
```

When I run this command:
$ [\xampp\htdocs\]composer install -d "myWebfolder"

I get the following output:
all packages of composer installed:
symfony....

And I expected this to happen:
why is this so ??
[:angry:]how can I just install one laravel package & forget the rest ??
real simple solution shud be there..rite??

**Comment by alcohol** [comment]
It's called `"dependencies"`. Please google for search terms such as "php", "composer" and "dependencies". Unfortunately this area goes way beyond the scope of just composer support. You are more in need of a general introduction to present day php programming it seems. Google has plenty of resources on the subject  :-)
