### ISSUE TITLE
[Command line] adding repository to numeric array

### ISSUE THREAD

**Issue by kubawerlos** [composer/composer#6474]
Hi,

whenever I have custom repositories defined in numeric array:
```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/foo/bar1"
        },
        {
            "type": "vcs",
            "url": "https://github.com/foo/bar2"
        }
    ]
}
```

and I run

```bash
    composer config repositories.bar3 vcs https://github.com/foo/bar3
```

it changes repositories array from numeric to associate.

It would be nice to have a possibility to run such a command it will append new repository at the end of it's array.

**Comment by Seldaek** [comment]
The problem is if we do this you can't then remove it using repo.bar3 --unset. IMO this isn't so easy to do this reliably given all possible cases. If you decide to modify repos via CLI then you should accept that the output may not look like what you want.
