### ISSUE TITLE
Include Composer Dependencies

### ISSUE THREAD

**Issue by marktopper** [composer/composer#6479]
Is it possible to make something like this:

`composer.json`
```
{
    "include": [
      "vendor/test/composer.json"
    ]
}
```

`vendor/test/composer.json`
```
{
    "require": {
      "test/test": "~1.2.3"
    }
}
```

Then the original composer file will act like the parts from the additional composer file was a part of the original file.
Is this possible?

**Comment by stof** [comment]
This is not possible in the core. But there is a plugin to merge multiple composer.json files together: https://packagist.org/packages/wikimedia/composer-merge-plugin

**Comment by marktopper** [comment]
Thanks
