### ISSUE TITLE
Mechanism to disable the creation of .htaccess files

### ISSUE THREAD

**Issue by WilHall** [composer/composer#6480]
This is #5816.

Currently, composer uses the following block of code in `Composer\Factory` to ensure that the home, cache, and data directories have a `.htaccess` file present:
```
// Protect directory against web access. Since HOME could be
// the www-data's user home and be web-accessible it is a
// potential security risk
$dirs = array($config->get('home'), $config->get('cache-dir'), $config->get('data-dir'));
foreach ($dirs as $dir) {
    if (!file_exists($dir . '/.htaccess')) {
        if (!is_dir($dir)) {
            Silencer::call('mkdir', $dir, 0777, true);
        }
        Silencer::call('file_put_contents', $dir . '/.htaccess', 'Deny from all');
    }
}
```

In the majority of cases, this is not mitigating any security risk. Not all installations are under an Apache document root, and not all systems even run an Apache-based web server. Additionally, it doesn't feel like a package manager's responsibility to ensure that web server configuration files exist.

This ticket is a feature request to add a composer config which would make it possible to disable this feature.

For example, if I know that I do not run Apache on my system, I might like to set `COMPOSER_HTACCESS_PROTECT` to `false` so that these files are not created.

As mentioned on #5816, this _may be_ protecting some people, and I think it's good to air on the safe side for a default. Perhaps this setting should stay on by default, which wouldn't affect people who may be relying on it (knowingly or unknowingly) for security. But for users who do not need it, this would make it possible to disable.

**Comment by alcohol** [comment]
Making it configurable could be a nice compromise vs. totally removing it (which I am still in favor of). Feel free to submit a pull request.

**Comment by staabm** [comment]
Side-note: Apache since 2.4 does not read .htaccess files per default anymore.
