### ISSUE TITLE
Partial dump of autoload

### ISSUE THREAD

**Issue by marktopper** [composer/composer#6481]
I have a script that creates classes for me runtime and then it dumps autoload, since we use classmaps.

Would it be possible to only dump parts of the autoload, so let's say every autoload for the folder `/test`?

This would make the whole progress go a lot faster.

**Comment by alcohol** [comment]
Not sure I understand the reason or motivation behind this request. Can you elaborate? Also, have you considered using `composer/composer` as a `require-dev` dependency in your project and using the dumper manually to dump whichever directory you want to dump?

**Comment by marktopper** [comment]
That was what I was looking for doing! 👍
