### ISSUE TITLE
Reload dependency composer.json file?

### ISSUE THREAD

**Issue by marktopper** [composer/composer#6482]
Is it possible to reload dependency composer.json file in order to add the missing dependencies and add any new autoload rules to the system without having to do a full `composer update`?

**Comment by alcohol** [comment]
How can the `composer.json` of one of your dependencies suddenly change?

**Comment by marktopper** [comment]
I use a a repository with the path type. Then I make changes to that repositorys dependencies, and would like a way to update the dependencies only for that composer file.

**Comment by alcohol** [comment]
What about `composer update your/package`?

**Comment by marktopper** [comment]
I have already tried that @alcohol, however without luck.

Here is what I have tried:
`composer.json`
```
{
    "repositories": [
    	{
    		"type": "path",
    		"url": "hooks"
    	}
    ],
    "require": {
    	"hooks": "*"
    }
}
```

`hooks/composer.json`
```
{
    "name": "hooks",
    "version": "1.0.0"
}
```

Then I ran `composer install`, after that I added this to `hooks/composer.json`:
```
    "require": {
        "laravel/tinker": "*"
    }
```
And ran `composer update`.
But it *DID NOT* get the required dependency.

**Comment by alcohol** [comment]
Your first mistake is defining a version number in your `hooks/composer.json`.

**Comment by marktopper** [comment]
Thanks. Works.

**Comment by stof** [comment]
yeah, if you set a release version in your package, you have to bump it each time you make changes
