### ISSUE TITLE
Make it possible to have a repository with repositories?

### ISSUE THREAD

**Issue by marktopper** [composer/composer#6484]
Can we have it possible to have a repository with repositories?

It seems that it now only support the `repositories` composer JSON object for the root composer file, right?

**Comment by alcohol** [comment]
Can you elaborate on the use-case / motivation behind this feature request? Because the phrasing of the question is unclear to me.

**Comment by Seldaek** [comment]
I am really sorry but all that comes to mind is this..

![image](https://user-images.githubusercontent.com/183678/27261841-7c1a2b4c-544b-11e7-8973-0758664fb2d5.png)

We need more details otherwise this is not going to go anywhere :)
