### ISSUE TITLE
How to install/test local plugin

### ISSUE THREAD

**Issue by marktopper** [composer/composer#6485]
I have followed this guide: https://getcomposer.org/doc/articles/plugins.md#creating-a-plugin

However I cannot get it to actually run the plugin.

**Comment by alcohol** [comment]
Please, share your code / example repository on Github through either a new repository or a Gist, so that we have a reproducible scenario to work with.

**Comment by marktopper** [comment]
This is what I have tried so far: https://github.com/larapack/composer-hook-plugin/blob/master/src/HookPlugin.php

**Comment by Seldaek** [comment]
The best way to test it I think would be using the [path repository](https://getcomposer.org/doc/05-repositories.md#path) to require the plugin in a test project, and just `rm -rf vendor && composer update` every time you want to install/run it again.

**Comment by llaville** [comment]
@Seldaek Related to your comment https://github.com/composer/composer/issues/6485#issuecomment-309284499, article about plugins should be updated, especially https://github.com/composer/composer/blob/main/doc/articles/plugins.md#running-plugins-manually
