### ISSUE TITLE
Composer update not passing --ignore-platform-reqs (possibly other relevant options?) to install

### ISSUE THREAD

**Issue by mattacular** [composer/composer#6487]
When I run this command:

```
composer update --ignore-platform-reqs
```

I get the following output:

```
error	15-Jun-2017 20:50:59	Generating autoload files
build	15-Jun-2017 20:51:01	Gathering patches for root package.
error	15-Jun-2017 20:51:01	Loading composer repositories with package information
error	15-Jun-2017 20:51:01	Installing dependencies (including require-dev) from lock file
error	15-Jun-2017 20:51:01	Your requirements could not be resolved to an installable set of packages.
error	15-Jun-2017 20:51:01	
error	15-Jun-2017 20:51:01	  Problem 1
error	15-Jun-2017 20:51:01	    - zendframework/zend-stdlib 3.1.0 requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
error	15-Jun-2017 20:51:01	    - zendframework/zend-stdlib 3.1.0 requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
error	15-Jun-2017 20:51:01	    - Installation request for zendframework/zend-stdlib 3.1.0 -> satisfiable by zendframework/zend-stdlib[3.1.0].
```

And I expected this to happen:

I assume at this point updating of the lock-file is complete and "composer update" continues by simply running the install command for you. I expect it would pass any shared options it has with "update" on to "install". Since I am relying on being able to ignore platform reqs on my build server where nothing is getting executed in PHP, this fails the command.

I found a work-around suggestion in another unrelated issue that seems to be working for me but I hope you'll consider a formal fix for this problem even though it is an edge case:

```
composer update nothing --ignore-platform-reqs [..other options]
composer install --ignore-platform-reqs [..copy other options]
```

Thank you!

**Comment by alcohol** [comment]
Based on this output:

```
error	15-Jun-2017 20:50:59	Generating autoload files
build	15-Jun-2017 20:51:01	Gathering patches for root package.
error	15-Jun-2017 20:51:01	Loading composer repositories with package information
```

it seems evident to me that you are running Composer with some kind of plugin(s).

Please try running composer without any side-effects (`--no-scripts --no-plugins`) and see if the problem still persists.

**Comment by mattacular** [comment]
That was the problem, thanks. Will follow-up with the plugin maintainers once I pinpoint it.

**Comment by vishal-jpeg** [comment]
> --no-scripts --no-plugins

what is the command for it
