### ISSUE TITLE
Cannot enable packagist from the commandline

### ISSUE THREAD

**Issue by mrgrain** [composer/composer#6488]
The behaviour for disabling packagist via the commandline is very inconsitent.
Sometimes `"packagist": false` is added, other times  `"packagist.org": false` is added.

Anyway, once a `"packagist.org": false` is in the `composer.json` there is no way of re-enabling packagist via the commandline.

My `composer.json`:

```json
{
    "name": "test/test",
    "repositories": [
        {"packagist": false}
    ]
}
```
When I run this command:

```
composer config repo.packagist false
```

I get the following `composer.json`:

```
{
    "name": "test/test",
    "repositories": {
        "packagist.org": false,
        "packagist": false
    }
}
```

When I run this command:

```
composer config --unset repo.packagist
```

I get the following `composer.json`:

```
{
    "name": "test/test",
    "repositories": {
        "packagist.org": false
    }
}
```

And I expected this to happen:
`packagist.org` entry should be removed

Output of `composer -V`:

```
Composer version 1.4.2 2017-05-17 08:17:52
```

## Inconsistent behaviour of `composer config repo.packagist false` 
Running
```
composer config repo.packagist false
```
with two different but semantically equivalent `composer.json` files yields a different result:

Case1: Before
```
{
    "name": "test/test",
    "repositories": {
        "packagist": false
    }
}
```
After:
```
{
    "name": "test/test",
    "repositories": {
        "packagist": false
    }
}
```

Case2: Before
```
{
    "name": "test/test",
    "repositories": [
        {
            "packagist": false
        }
    ]
}
```
After:
```
{
    "name": "test/test",
    "repositories": {
        "packagist.org": false,
        "packagist": false
    }
}
```

**Comment by alcohol** [comment]
`packagist.org` is the new approach, `packagist` is still supported for legacy reasons. Newer versions of composer will automatically treat `packagist` as `packagist.org` when reading the configuration. It is however not trivial to make the `ConfigCommand` completely aware of this, hence why it simply inserts what you give it.

```
rob /tmp > echo '{}' > composer.json
rob /tmp > composer config repo.packagist.org false
rob /tmp > cat composer.json
{
    "repositories": {
        "packagist.org": false
    }
}
```
```
rob /tmp > composer config --unset repo.packagist.org
rob /tmp > cat composer.json 
{
    "repositories": {
    }
}
```

> note: Composer will not automatically remove an empty repositories key.

**Comment by mrgrain** [comment]
Hi @alcohol Thanks for your prompt feedback, I wasn't clear enough on my issue. It is (at least with my composer 1.4.2 NOT possible to set or unset the `repo.packagist.org` config since it contains an additional dot between `packagist` and `org`
```
$ echo '{}' > composer.json
$ composer config repo.packagist.org false
$ cat composer.json
{
    "repositories": {
        "packagist": {
            "org": false
        }
    }
}
$ composer validate                                                                          
  [Composer\Json\JsonValidationException]                                       
  "./composer.json" does not match the expected JSON schema:                    
   - repositories.packagist : Object value found, but a boolean is required     
   - repositories.packagist : Does not have a value in the enumeration [false]  
   - repositories.packagist.type : The property type is required                
   - repositories.packagist.package : The property package is required          
   - repositories.packagist.url : The property url is required                  
   - repositories.packagist : Failed to match exactly one schema                
```
So that's already really bad, but hey okay I can see why this is a user error, however it is NOT what you thin should happen.

More important is bug number 2:
## Cannot undo a setting one can set via the cli with the cli
Given a file with the correct `packagist.org` settings (as one can get, see first post)
```
$ cat composer.json
{
    "repositories": {
        "packagist.org": false
    }
}
$ composer config --unset repo.packagist.org
$ cat composer.json
{
    "repositories": {
        "packagist.org": false
    }
}
```
No change! Which makes sense since the nested object doesn't exists.

**Please review your classification of this issue. I think it's a bug.**

**Comment by alcohol** [comment]
Sorry, I forgot I am using `1.5-dev`. We recently introduced a change to the config command which allows it to handle full (sub)domains for repository configuration by no longer cutting it off at the first `.`.

**Comment by mrgrain** [comment]
Sweet, that's good enough for me. Might be worth mentioning in the docs though. :)
