### ISSUE TITLE
Package with branch-alias fails to update to symlink if previously installed from remote

### ISSUE THREAD

**Issue by emileber** [composer/composer#6491]
_Disclaimer: I removed everything unnecessary for my test from the `composer.json` files in the following example to keep it minimal and focused._

# Our initial configuration

This is in a vagrant VM running Ubuntu 16.04.2 LTS (homestead 5.1.0) on Macbook Pro (macOS Sierra 10.12.5) with both Php 5.6 and 7.1.

I tested this with Composer version 1.4.1 2017-03-10 09:29:45 and version 1.4.2 2017-05-17 08:17:52 after updating.

We have a **private SDK package** shared between multiple projects that has the following `composer.json`:

```json
{
    "name": "company/sdk",
    "description": "redacted",
    "license": "proprietary",
    "keywords": ["redacted"],
    "authors": [
        {
            "name": "redacted",
            "email": "support@company.com"
        }
    ],
    "type": "project",
    "extra": {
        "branch-alias": {
            "dev-master": "3.1.*-dev"
        }
    }
}
```

A project that uses the SDK as a dependency has the following `composer.json`:

```json
{
    "name": "company/frontend",
    "description": "product (front-end)",
    "keywords": ["product", "frontend"],
    "type": "project",
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:company/sdk.git"
        }
    ],
    "require": {
        "company/sdk": "3.1.*"
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    }
}
```

It installs correctly version 3.1.0 of the SDK.

# Development needs symlink

But as we're developing new features which implies changing the SDK in addition to the frontend, we'd like to use the `symlink` feature of composer to use our local version of the SDK.

So I checked out the `feature/sdk-changes` branch in the SDK project. Then in the frontend project, I changed the `composer.json` file to the following:

```json
{
    "name": "company/frontend",
    "description": "product (front-end)",
    "keywords": ["product", "frontend"],
    "type": "project",
    "repositories": [
        {
            "type": "path",
            "url": "/home/vagrant/repos/sdk",
            "options": {
                "symlink": true
            }
        }
    ],
    "require": {
        "company/sdk": "dev-feature/sdk-changes"
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    }
}
```

# The problem

Then, I run

```bash
$ composer update company/sdk

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package company/sdk dev-feature/sdk-changes as 3.1.0 exists as company/sdk[3.1.0, dev-develop] but these are rejected by your constraint.
```

And it fails to install the local version with a symlink. **Even if I delete the `composer.lock` and the `vendor/` directory**, it still gives the same error.

## The expected behavior

I would expect it to remove version 3.1.0 and symlink to my local version. I'm expecting the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Removing company/sdk (3.1.0)
  - Installing company/sdk (dev-feature/sdk-changes): Symlinking from /home/vagrant/repos/sdk
Writing lock file
Generating autoload files
```

## What I found about `branch-alias`

After searching why it was now failing since it worked well in the past, I saw that someone had added a `branch-alias` in the SDK project. So I tried removing the attribute from the `composer.json`:

```json
{
    "name": "company/sdk",
    "description": "redacted",
    "license": "proprietary",
    "keywords": ["redacted"],
    "authors": [
        {
            "name": "redacted",
            "email": "support@company.com"
        }
    ],
    "type": "project",
    "extra": {}
}
```

Then running `composer update company/sdk` works as expected, removing the previously installed SDK and installing the local version using a symlink, then it correctly updates the lock file.

Once the lock file up to date, I can put back the `branch-alias` attribute in the SDK's `composer.json` and it can be reinstalled correctly.

---

Maybe I'm misunderstanding how the `branch-alias` works and that it is the expected behavior and using a symlink like that isn't meant to work. But it looks like the constraints check fails on the local version when the `branch-alias` attribute is present.

**Comment by Seldaek** [comment]
If you use the path repo, it only is aware of the currently checked out branch/tag in that path, so You can't require the `dev-feature/sdk-change` version unless you go in `/home/vagrant/repos/sdk` and do `git checkout feature/sdk-change`.

**Comment by emileber** [comment]
@saldaek thanks for your response, but I already know that, and it's already mentioned above:

> So I checked out the `feature/sdk-changes` branch in the SDK project.

I meant locally, in the same directory the path repository is configured.

And it works as soon as I remove the `branch-alias` from that same project, while checked out on the `dev-feature/sdk-changes`.

**Comment by emileber** [comment]
Another thing, all my colleagues are experiencing the same issue.

**Comment by Seldaek** [comment]
OK sorry I misread your post. The thing is usually when the branch-alias is defined and you are on a feature branch (i.e. **not** master or develop), composer resolves the version back to the nearest non-feature branch, be it master or 1.x or 2.4 or whatever branch that feature branch was created from. The reason is if you have circular dependencies in that project, and something relies on that package as 1.* for example then if the version is dev-feature-blah it won't match 1.* and that's a problem. So this is usually a good thing, and it really just means in your case that you should keep the require to sdk `3.1.*@dev` and if you check out `dev-feature/foo` it should resolve that one to `dev-develop` which is aliased as `3.1.*-dev` so that should match the requirement.

**Comment by emileber** [comment]
Oh thanks, we were so close and you definitely opened our eyes on how it works.

> The requested package `company/sdk 3.1.*@dev` exists as `company/sdk[dev-develop]` but these are rejected by your constraint.

The _"exists as `company/sdk[dev-develop]`"_ part seems to refer to our local version. By adding `"dev-develop": "3.1.*-dev"` to the SDK branch aliases, it now installs correctly by symlinking.

Thank you again for your time.
