### ISSUE TITLE
"Illegal instruction: 4"

### ISSUE THREAD

**Issue by hirasso** [composer/composer#6494]
I am trying to install a package on my machine using composer, but I get an error:
```
composer require giggsey/libphonenumber-for-php
Illegal instruction: 4
```
running only `composer` throws the same error... Google didn't help so I am posting this here.
Any ideas? I am happy to provide you with more information if needed.

**Comment by alcohol** [comment]
What happens if you run:

```
composer install --no-scripts --no-plugins require giggsey/libphonenumber-for-php
```

**Comment by stof** [comment]
I think this is related to using a PHP binary compiled on a newer version of Mac OS X, and incompatible with your version: https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10

**Comment by hirasso** [comment]
@alcohol I get the same error running your command...
@stof This thread claims that this would fix it, if I understand it right:
```
composer install require giggsey/libphonenumber-for-php -mmacosx-version-min=10.5 
```
...but I keep getting the error. Do I have to update composer?

**Comment by robfrawley** [comment]
> this is related to using a PHP binary compiled on a newer version of Mac OS X, and incompatible with your version

If @stof's assertion is correct, this means your *PHP* installation needs to be reinstalled, not *composer*.

**Comment by hirasso** [comment]
@robfrawley Thanks for your help, reinstalling PHP fixed my problem.
