### ISSUE TITLE
Xdebug is not disabled, cannot be disabled

### ISSUE THREAD

**Issue by jhabdas** [composer/composer#6498]
**My `composer.json`:**

```json
{}
```

**Output of `composer diagnose`:**

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

**When I run this command:**

```
COMPOSER_ALLOW_XDEBUG=0 && curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install
```

**I get the following output:**

```
Installing Terminus...
<warning>You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug</warning>
```

**And I expected this to happen:**

```
Installing Terminus...
```

**Other observations:**

- [Xdebug impact on Composer](https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer) suggests Composer disables Xdebug by default. However, that has not been my experience, which is why you see `COMPOSER_ALLOW_XDEBUG` set to `0` above in attempt to explicitly disable Composer's use of Xdebug.
- Documentation does not clearly state how to restart Composer.
- Composer CHANGELOG shows many xdebug related changes, but does not link to commits and therefore is difficult to use.

**Suggestions:**

- Provide documentation on how to restart composer and link to troubleshooting docs.
- Give users the ability to explicitly disable Xdebug, rather than relying on defaults as it appears there is either a regression here or an environment-related corner-case.
- Consider using [Conventional Changelog](https://github.com/conventional-changelog/conventional-changelog) to facilitate debugging and minimize issues.

**Environment:**

- OS version Darwin 16.6.0
- Composer version 1.4.2 2017-05-17 08:17:52

**Comment by alcohol** [comment]
Please submit an issue on the terminus installer repository. This is not a composer issue.

**Comment by jhabdas** [comment]
It's not their issue.

**Comment by alcohol** [comment]
```
COMPOSER_ALLOW_XDEBUG=0 \
  && curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar \
  && php installer.phar install
```

Your own provided evidence begs to differ.

**Comment by jhabdas** [comment]
With all due respect, I think you're missing the point here. I will open some additional issues with minimal reproducible test cases now, of which there will be three.

**Comment by alcohol** [comment]
Please do. If there is a legitimate issue with Composer itself, it will be addressed accordingly. This simply isn't such :-)

**Comment by jhabdas** [comment]
That doesn't mean you should've closed it without inquiry first. That's just bad form.

**Comment by alcohol** [comment]
You are entitled to your opinion. :-)

**Comment by jhabdas** [comment]
Whatever.

**Comment by alcohol** [comment]
You are submitting an issue generated by the binary/installer of another project. You expect us to devote time (which is scarce) to determine why said other project is making composer misbehave (in your opinion), without asking them first? That's just bad form :-)

**Comment by jhabdas** [comment]
If you want to get pedantic, no. I'm asking for a proper triage process, and for you to review and address my other feedback. Which you clearly did not. That's bad form. And that's not my opinion. It just is. :-)

**Comment by alcohol** [comment]
> Xdebug impact on Composer suggests Composer disables Xdebug by default. However, that has not been my experience, which is why you see COMPOSER_ALLOW_XDEBUG set to 0 above in attempt to explicitly disable Composer's use of Xdebug.

Your experience has not been my experience. Cannot reproduce. Provide reproducible scenario.

> Documentation does not clearly state how to restart Composer.

Because there is no such thing as "restarting" composer. Elaborate on what you are actually asking for here.

> Composer CHANGELOG shows many xdebug related changes, but does not link to commits and therefore is difficult to use.

All you need to know is in the documentation.

**Comment by Seldaek** [comment]
First of all, COMPOSER_ALLOW_XDEBUG is only [documented as being enable-able](https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer). Setting it to 0 has no effect, as it just says that it's not allowed, so we try to restart without it, but that's the default anyway.

`COMPOSER_DISABLE_XDEBUG_WARN=1` as documented there too is the way to suppress the warning if you want to ignore the warning. The reason why it can't do the restart without xdebug I have no idea but I suspect it is indeed due to something that installer is doing.

**Comment by Seldaek** [comment]
A quick look at the terminus-installer source shows that it is executing Composer's Application class directly via PHP code, and not via the composer.phar file: https://github.com/pantheon-systems/terminus-installer/blob/7d0cba3350513620dfd7f95d4ebb63092a8df14b/src/Command/UpdateCommand.php#L52

As we do the restart in [bin/composer](https://github.com/composer/composer/blob/master/bin/composer#L19) only, this code is bypassed entirely, so yes the bug if you will is in the terminus-installer, they should do the restart themselves or make sure to `putenv('COMPOSER_DISABLE_XDEBUG_WARN=1');` before running Composer.

**Comment by jhabdas** [comment]
@Seldaek Thank you. That's all I needed to know.
