### ISSUE TITLE
Updates blocked by not passing --with-dependencies` flag are unclear

### ISSUE THREAD

**Issue by Firehed** [composer/composer#6502]
My `composer.json`:

```json
{
  "repositories": [
    {
      "type": "composer",
      "url": "my-private-repo"
    }
  ],
  "require": {
    "quartzy/shipping-sdk": "^0.2"
  },
  "license": "proprietary"
}

```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer update quartzy/shipping-sdk
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
```

And I expected this to happen:

Either:
a) the behavior that would trigger with `--with-dependencies` occurs (implicitly making it the default when a package is specified); i.e.
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Updating quartzy/shipping (0.2.2 => 0.3.0): Loading from cache
  - Updating quartzy/shipping-sdk (0.2.1 => 0.2.2): Loading from cache
Writing lock file
Generating autoload files
```
or b) There is some indication in the command's output that updating is being blocked due to a dependency update, and I should re-run the command with the `--with-dependencies` flag (preferably with an output similar to `--with-dependencies --dry-run`) in order to get the latest version that matches my requirements.

**Comment by alcohol** [comment]
@Seldaek how do you feel about this?

**Comment by stof** [comment]
there is `composer why-not quartzy/shipping-sdk 0.2.2` which already explains you what prevents installing it

**Comment by Firehed** [comment]
@alcohol many tools have great built-in help, Composer among them. But in this case, the output of the tool indicates nothing to do rather than a refusal to do something it could, which when you know for a fact that there is something to do leads you to believe there's some sort of upstream problem (did I not actually push the tags? Is my version constraint wrong? Is the repo behind? Did a cache get screwed up?). IMO this is a messaging problem, not a documentation one. 

@stof that doesnt address the discoverability issue. This has happened to me a number of times over the years, because "nothing to install or update" implies a new version is unavailable, rather than being blocked due to a conflict. In fact, I've almost filed basically this same issue at least twice before finally getting lucky and rediscovering the flag that solves the problem.

I'm more than happy to implement either change I've suggested (more likely the latter, by the sounds of it), but I'd like feedback from the maintainers first on direction, and don't want to waste time if you're not interested.

**Comment by Seldaek** [comment]
The combination of `composer outdated` to discover new releases + `composer why-not` to understand when something won't update is the best we can do I'm afraid.. What you are asking would require that we do essentially two updates internally, check if there are any differences and suggest that maybe if you updated with dependencies more would update. That might help in some cases, and you might think the performance cost is worth it, but there are also many cases where you know there are dependencies that can be updated but you don't want to do it yet, and having that cost on every update plus a warning nagging you every time I don't think it'd be worth it really..
