### ISSUE TITLE
run-script scans entire classmap directory prior to running script

### ISSUE THREAD

**Issue by sagara-** [composer/composer#6503]
My `composer.json`:

```json
{
    "name": "test/rscript",
    "authors": [],
    "license": "MIT",
    "require": {},
    "autoload": {
        "classmap": ["src/"],
        "exclude-from-classmap": ["src/media"]
    },
    "scripts": {
        "sc": "bin/s.php"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK

```

When I run this command:

```
composer run-script sc
```

When the above command is run and a classmap autoloader is being used, composer scans the entire directory tree under the classmap dirs before running the script. I first noticed this attempting to use run-script on a legacy project I was looking to integrate composer into. The project itself has a large amount of asset files under some subdirs of the source directory, and run-script could take 20+s to run.

A cursory glance by running run-script under strace shows that prior to executing the script, it scans the entire src/ directory (including anything in the exclude-from-classmap list). If {"psr-4": {"": "src/"}} is used for the autoloader block, then this behavior doesn't occur. This behavior is also not present if running the script via the php command directly, nor do other composer commands trigger this behavior.

I've put up a small test [project](https://github.com/sagara-/composer-runscript-issue) that demonstrates this behavior. If one runs run-script-strace.sh in the directory after running composer install, checking the rs-strace.log file shows the directory scan prior to running the script at bin/s.php (searching for media-file shows up before the execve to s.php).

I've read through [the](https://getcomposer.org/doc/04-schema.md#classmap) [docs](https://getcomposer.org/doc/articles/scripts.md) and checked opened issues, but can't find anything that hints at this behavior. I've confirmed this behavior both under Arch Linux using a downloaded composer and Ubuntu Xenial using the package from apt, so I don't believe it's platform specific but I haven't tested on windows or osx to be certain.

The behavior itself is odd, and as it stands scripts are completely unusable for that specific project due to this issue, so this seems like it might be a bug or at least something that should be documented.

**Comment by alcohol** [comment]
Afaik we mimick the behavior of running the autoloader generation before `scripts` get executed, because scripts might reference classes that are mentioned in the autoload definitions.

**Comment by sagara-** [comment]
Hmm, in that case, shouldn't it ignore paths listed under exclude-from-classmap at least? Unless I've written up that part wrong it should ignore src/media but it clearly scans it anyways.

I guess the point of mimicking the autoloader is to support PHP class callbacks, since those must be loadable via the autoloader? I guess composer doesn't load the on-disk autoloader at any point, which is why this behavior exists?

Although the docs state that for pre-update-cmd and pre-install-cmd scripts should not rely on dependencies being available, I've assumed anything else would just use the dumped autoloader. I guess this is only really a problem for anyone using the classmap autoloader option, which is generally uncommon outside of older projects.

I can work around this by just providing my own launcher script with subcommands instead of going via composer's scripts if this is expected behavior. Although I feel it's probably undesirable behavior, I understand that if this is being relied on, changing it could break backwards compat, so it might not be possible, especially since it only has a negative impact on those using the classmap autoloader functionality. But it would be nice if this behavior was noted somewhere in the documentation if this is the case, for example by mentioning it under the classmap section.

**Comment by alcohol** [comment]
> shouldn't it ignore paths listed under exclude-from-classmap at least?

I'm not sure, I would have to dive deeper into the code to figure that out.

> I guess the point of mimicking the autoloader is to support PHP class callbacks, since those must be loadable via the autoloader?

Correct.

> Although the docs state that for pre-update-cmd and pre-install-cmd scripts should not rely on dependencies being available

Correct, but you can depend on classes in your root project code base to be available.

---

I'm not sure what to suggest here to be honest. I've never run into performance issues myself in this scenario. Then again, I rarely have a need for the scripts section so I don't use it all that much at all.

**Comment by sagara-** [comment]
Ya, my case is just a bit odd due to how this project was set up. I guess the only real issue here is that the script loader isn't respecting the exclude-from-classmap; if it's expected to mimic the classloader it should obey that directive as well.

I guess maybe just a small note regarding the behavior in the documentation somewhere might of benefit incase someone else has such a project set up. This is just an issue with using the classmap autoloader though, since modern projects don't have such a setup they aren't affected. Although if exclude-from-classmap is respected then it shouldn't be that much of an issue, since in my case issue comes from composer scanning the entire (massive) assets subdirectory it should be ignoring.

In my case I'll just use a launcher script to invoke the vendor scripts instead to bypass this if I end up using the classmap autoloader for the existing code, so I can work around it just fine. I had originally thought of going through composer since one of the dependencies I'm composer-izing has a large number of exposed scripts.

**Comment by alcohol** [comment]
I think (but could be wrong here) that the exclude-from-classmap is only relevant during generation of the autoload files. Since this classloader for run-scripts is generated on the fly it does not use any autoload generated files, hence the exclude-from-classmap does not apply.

**Comment by alcohol** [comment]
I think (but could be wrong here) that the exclude-from-classmap is only relevant during generation of the autoload files. Since this classloader for run-scripts is generated on the fly it does not use any autoload generated files, hence the exclude-from-classmap does not apply.

@Seldaek or am I way off-base here?

**Comment by Seldaek** [comment]
Definitely was a bug there, exclude-from-classmap was added way later and not added everywhere it seems.

**Comment by sagara-** [comment]
Awesome, thanks for fixing it.
