### ISSUE TITLE
Can Composer be made to use a specific path to OpenSSL, if you have two versions of it?

### ISSUE THREAD

**Issue by lynna-freeform** [composer/composer#6505]
My `composer.json`:

```
(I'm sorry, I don't know how to find this - if someone can tell me how to access it I will add it here.)
```

Output of `composer diagnose`:

```
Checking platform settings: WARNING
The OpenSSL library (0.9.8zc) used by PHP does not support TLSv1.2 or TLSv1.1.
If possible you should upgrade OpenSSL to version 1.0.1 or above.

Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

I recently installed Composer, and got the same error included in the diagose output above, about the OpenSSL version. I am on Mac OS X 10.10.5 (Yosemite), and from what I've been able to determine, Apple has not updated the version of OpenSSL they include (the pre-Heartbleed version, thankfully) for some while because they are moving away from OpenSSL and toward some other alternative I'm not clear on. But since Composer seems to require OpenSSL, I tried to update it, using Homebrew since that seemed like the most widely recommended method. 

However, Homebrew gave me the following message during the OpenSSL update:

"Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib"

So my question is: is there a way I can tell Composer to use the full path, so that it gets the updated OpenSSL rather than the older version? I would have thought the older version would be replaced by the newer one, but apparently that's not the case...

**Comment by stof** [comment]
Composer is not the one using openssl. PHP is (Composer uses PHP though). So this is the wrong place to ask. You should ask for support to the maintainer of the PHP package you are using.

**Comment by lynna-freeform** [comment]
OK, sorry.
