### ISSUE TITLE
Interactive dependency installation does not indicate progress

### ISSUE THREAD

**Issue by jhabdas** [composer/composer#6507]
When I run this command:

```
composer init
```

I get the following output:

```
Would you like to define your dependencies (require) interactively [yes]? yes
Search for a package: installers

Found 15 packages matching installers

   [0] composer/installers
   [1] laravel/installer
   [2] contao-components/installer
   [3] silverstripe/installer
   [4] notadd/installers
   [5] quorum/installer
   [6] openpsa/installer
   [7] orchestra/installer
   [8] thelia/installer
   [9] dreamfactory/installer
  [10] xpressengine/installer
  [11] pyrocms/installer
  [12] konafets/installers
  [13] antvel/installer
  [14] speedwork/installer

Enter package # to add, or the complete package name if it is not listed: 0
Enter the version constraint to require (or leave blank to use the latest version):
```

And I expected this to happen:

Progress indication. Instead it hangs, eventually finishing, but takes several minutes for a single dependency and multiple <kbd>return</kbd> statements exit the interactive before more than a single dependency may be added.

Attaching screenshots showing output and resource utilization (leading me to believe it's hanging on the network):

<img width="344" alt="screen shot 2017-06-27 at 4 34 45 pm" src="https://user-images.githubusercontent.com/440298/27578722-7e2d34fc-5b57-11e7-99ea-80002205d79f.png">

<img width="304" alt="screen shot 2017-06-27 at 4 37 18 pm" src="https://user-images.githubusercontent.com/440298/27578723-7e2da356-5b57-11e7-9f0f-2b005bf5c701.png">

Same deal for `require`. Would be great to have even a throbber spinning to show something's happening in a tty. I use the terminal app for macOS but see the same behavior under linux.

**Comment by jhabdas** [comment]
Same deal with require. No progress indication. Not even a throbber.

<img width="762" alt="screen shot 2017-06-27 at 4 56 40 pm" src="https://user-images.githubusercontent.com/440298/27579311-a7741112-5b59-11e7-8d59-2dfbe7cbd76c.png">

**Comment by alcohol** [comment]
I'm sorry but I cannot reproduce your scenario. It looks to be a networking issue on your end. There is not much we can do to improve your situation. I suggest speaking to whoever is in charge of operating/maintaining your network connection :-)

**Comment by jhabdas** [comment]
I'll assume it's just me then. No worries. I've learned to be patient.

**Comment by jhabdas** [comment]
I no longer believe this was hanging on the network. I believe it's hanging on a long-running subprocess.

**Comment by alcohol** [comment]
Can you identify what sub-process it hangs on?

**Comment by jhabdas** [comment]
I'll be looking into it. Might need a profiler.

**Comment by jhabdas** [comment]
Suppose htop might do. Will see. Thx hoss
