### ISSUE TITLE
HTTP Request Failure: http://getcomposer.org/composer.phar "Fail to Open Stream"

### ISSUE THREAD

**Issue by KidA78** [composer/composer#6515]
We've been seeing Composer stream errors happen around the same time every day.  Around 5pm PST, we get the following errors below. Is there something that is happening during this time that causes the stream to fail?

```
Console/cake composer.c self-update;
```

I get the following output:

```
00:13:56 Warning Error: file_get_contents(http://getcomposer.org/composer.phar): failed to open stream: HTTP request failed!  in [/path/to/ComposerShell.php, line 82]
00:13:56 
```

**Comment by alcohol** [comment]
@Seldaek anything in the error logs on the host of getcomposer.org ?

But on a side note, the scripts you are running don't seem to be provided/supported by us. So if you want to do more debugging on your end, we really cannot help you as we have no idea what you're doing.

**Comment by KidA78** [comment]
@alcohol thanks. What the script is doing, is just a wrapper around 
```
php composer.phar self-update
```
But the latest `composer.phar` fails to download.  And the last few failures we've had all happen around the same time on those different days.  A retry a few hours later, and the `phar` file downloads without issue.  Let's see if @Seldaek has noticed any issues in the logs?

**Comment by Seldaek** [comment]
If self-update is working fine for everyone else, I'd guess your script is doing something funky or the environment/network has issues. Check if `composer self-update` or `composer diagnose` report anything funky, if not then I'd guess it's in your script. I don't see anything in logs but without an exact UTC time to look for it's kinda hard anyway as we have lots of traffic and logs are pretty noisy.

**Comment by KidA78** [comment]
Thanks @Seldaek, if it happens again I'll provide a timestamp, and I'll run diagnose to see if `composer` reports anything.

**Comment by KidA78** [comment]
@Seldaek @alcohol  the issue has happened again.  I have a timestamp for you:

At Sat July 22, 2017 00:05:46 UTC, when downloading http://getcomposer.org/composer.phar
This error happens around this exact same time.  Is this server restarting, or is some process happening on this box around this time?

**Comment by Seldaek** [comment]
Sorry but I don't see anything special in logs at that time there is nothing at all in the nginx error log and nothing odd in access log either.

**Comment by KidA78** [comment]
@Seldaek @alcohol 
Just getting back to this.  As we speak, the issue is still happening.  Starting at 0:00:00 UTC and continuing for about 30 minutes, random HTTP failures when downloading the `composer.phar` file:

```
@local:/path/to/my/app $ composer self-update

                                                                                                
  [Composer\Downloader\TransportException]                                                      
  The "https://getcomposer.org/versions" file could not be downloaded: Failed to enable crypto  
  failed to open stream: operation failed                                                       
                                                                                                

self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--set-channel-only] [--] [<version>]
```

**Comment by Seldaek** [comment]
I just deployed some changes to our infrastructure which should help with this. Let me know if that is not the case.

**Comment by KidA78** [comment]
@Seldaek thanks for following up.  Will let you know if the issue persists.

**Comment by go2amp** [comment]
Having same issue.  Haven't had any problems on other dev machines during the 8-5pm EST working hours, but tonight at 7:17PM EST, getting this error.  Not getting a page when simply browsing to https://getcomposer.org either.

**Comment by qcho** [comment]
Had the same error. The issue was the local DNS service was resolving `getcomposer.org` into an ipv6 address instead of ipv4.
The solution was to un-comment the following line in `/etc/gai.conf`:
```sh
#
#    For sites which prefer IPv4 connections change the last line to
#
precedence ::ffff:0:0/96  100
```
hope helps someone :)
