### ISSUE TITLE
Type:vcs not working on windows 10

### ISSUE THREAD

**Issue by jmckay56** [composer/composer#6516]
My `composer.json`:

```
 "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:xxx/xxx-lib-cache"
        },
        ],
```

Output of `composer diagnose`:

```
 PS E:\rlsDocker\lbe> composer diagnose
Checking composer.json: WARNING
License "private" is not a valid SPDX license identifier, see https://spdx.org/licenses/ if you use an open license.
If the software is closed-source, you may use "proprietary" as license.
require.zfr/hydrator : unbound version constraints (dev-master) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK

```

When I run this command:

```
composer update
```

I get the following output:

```
  [Composer\Downloader\TransportException]
  The "https://api.github.com/repos/xxx/xxx-lib-cache" file could not be downloaded (HTTP/1.1 404 Not Found)

```

And I expected this to happen:
Libraries to load. If I change the "type":"vcs" to "type":"git"  the TransportException error goes away, and the libraries get loaded

**Comment by alcohol** [comment]
The only distinction I can draw here is that type git would result in composer doing a git clone of the remote repository into local cache directory, and then a checkout of that into the vendor directory.

Using type vcs it should detect that the source is a github repo and thus it tries to use the github api instead which is theoretically more efficient.

Is this a private repo in your use-case?

**Comment by jmckay56** [comment]
yes it is a private repo

**Comment by alcohol** [comment]
I am not sure if using the API works for private repositories since it would require token authentication at the very least (cannot use ssh key for API). You can try disabling the use of the API when using type vcs.

```
"no-api": true
```

**Comment by jmckay56** [comment]
I probably should have mentioned problem does not exist on my window 7 desktop or Mac OS.  It could be unique to me.  I was wondering if it other windows 10 users had similar experience.

**Comment by jmckay56** [comment]
"no-api": true

worked great for me, but changign it from type from vcs to git also worked

**Comment by jmckay56** [comment]
Since no other windows 10 users are having this problem, and I have a work around.  I will close this issue.

**Comment by jmckay56** [comment]
Since no other windows 10 users are having this problem, and I have a work around.  I will close this issue.

**Comment by jmckay56** [comment]
https://github.com/composer/composer/issues/2366.  For some reason Windows 10 enterprise did not create an oauth key.  following instructions at the above link worked
