### ISSUE TITLE
using HTTP basic auth with toran does not work

### ISSUE THREAD

**Issue by mikk150** [composer/composer#6518]
My `composer.json`:

```json
{
    "repositories": [
        {
            "type": "composer",
            "url": "https://username:maximumsecurepassword@toran.myawesomesite.org/repo/private/"
        }
    ]
}
```

Output of `composer diagnose`:

Checking composer.json: WARNING
......
couple of warnings that I do not have version constraints 
......
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK

When I run this command:

```
composer install --prefer-dist
```

I get the following output:

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
    Finished: success: 0, skipped: 0, failure: 170, total: 170
Package operations: 185 installs, 0 updates, 0 removals
  - Installing yiisoft/yii2-composer (2.0.5):                            
    Authentication required (toran.myawesomesite.org):
      Username: 

```

And I expected this to happen:
install everything with username and password from composer.json file as is documented in [http-basic-authentication.md](https://github.com/composer/composer/blob/master/doc/articles/http-basic-authentication.md)

**Comment by Seldaek** [comment]
You should rather use the auth.json method described later in that doc page you linked. It's more secure than committing credentials. Also you seem to have some plugin or something outputting that `    Finished: success: 0, skipped: 0, failure: 170, total: 170` so that might not be compatible.

And finally, you should rather use [Private Packagist](https://packagist.com) than Toran as the latter is EOL and unmaintained.
