### ISSUE TITLE
Need to be able to disable ipv6 when composer creates remote stream context

### ISSUE THREAD

**Issue by montsamu** [composer/composer#6519]
I am a non-admin user on a system which is slightly misconfigured, in that wget works to download http://packagist.org/packages.json but curl times out, as does composer install/create-project/etc. Unfortunately, as a non-admin user, the ipv6 workarounds are not available to me. (I can't fix the IPV6 setup, and I can't sudo or make temporary changes.) However, curl -4 (forcing ipv4) works, leading me to believe that the socket context used in composer's RemoteFilesytem and StreamContextFactory needs also to be able to force ipv4, which I confirmed by patching composer locally. Unfortunately there is not a "global" way to do this in PHP config or runtime settings (well, there is, via stream_context_set_default, but composer does not read the default before creating its own options...), so it requires patching composer source to work. Ideally, a general config setting for "default context factory" would be ideal, so I could set:

(array('socket' => array('bindto' => '0:0'))

Or defined as a JSON syntax or whatever, as part of the default stream context. Alternately, it is possible that composer might be able to pick up a context I set (e.g. with an auto prepend script calling stream_context_set_default) via stream_context_get_default, but that I haven't tested, only that setting this additional context does in fact allow composer to reach packagist and download packages.json, and frankly adding a composer config for this seems much better than using a prepend script.

**Comment by montsamu** [comment]
Here's where I changed things to get it to work locally:

`    public static function getContext($url, array $defaultOptions = array(), array $defaultParams = array())
    {
        $options = array('http' => array(
            // specify defaults again to try and work better with curlwrappers enabled
            'follow_location' => 1,
            'max_redirects' => 20,
        ));`

By adding my 'socket' => array('bindto' => '0:0') to these options. Obviously this is not desirable all the time! But I am not familiar with consuming the composer config at the composer code level, and StreamContextFactory does not currently reference Config. RemoteFilesystem does, so an alternate location for a fix would be to have RemoteFilesystem read a new Config parameter here, possibly in getOptionsForUrl.

**Comment by alcohol** [comment]
@Seldaek any thoughts on this? Can we provide more easier out of the box solutions to work around ipv6 issues?

**Comment by Seldaek** [comment]
@montsamu The last proposal you made of adding a `disable-ipv6` config option sounds like the better approach to me. Might be best to have a 3-modal switch though `ip-stack: auto/4/6` so it can be forced either way (for forcing v6 there is a `socket => ipv6_v6only` flag as of php7, or maybe we can set `bindto => [0]:0`).

**Comment by DavidAnderson684** [comment]
Similar-ish problem here. IPv6 is working (I can visit other sites). I can visit packagist.org over IPv4... but no IPv6.

```
# telnet packagist.org 443
Trying 2607:5300:60:7113::3...
(times out)

# telnet ipv6.google.com 443
Trying 2a00:1450:4011:804::1000...
Connected to ipv6.google.com.
Escape character is '^]'.
```

**Comment by cpjeanpaul** [comment]
Linux: sudo sh -c "echo 'precedence ::ffff:0:0/96 100' >> /etc/gai.conf"
Worked for me! 
Ref: https://getcomposer.org/doc/articles/troubleshooting.md#operation-timed-out-ipv6-issues-

**Comment by AndrewSithole** [comment]
> Linux: sudo sh -c "echo 'precedence ::ffff:0:0/96 100' >> /etc/gai.conf"
> Worked for me!
> Ref: https://getcomposer.org/doc/articles/troubleshooting.md#operation-timed-out-ipv6-issues-

Worked For me too

**Comment by Seldaek** [comment]
It seems IPv6 issues are less and less frequent as it gets more and more use, so I think we can get by without adding this.

**Comment by jby** [comment]
I have ipv6 completely disabled in my Linux (RHEL-7) server, but I still get the ipv6 timeout when trying...

`https://repo.packagist.org could not be fully loaded (curl error 7 while downloading https://repo.packagist.org/packages.json: Failed to connect to 2001:41d0:304:200::b7ae: Network is unreachable)`

So, an option to disable even trying the use of ipv6 would be nice.
I've tried the suggested lowering of precedence, but to no avail...
