### ISSUE TITLE
How to install without root user?

### ISSUE THREAD

**Issue by BoBBer446** [composer/composer#6521]
Hey, i got a small question:
I run as root user the composer installation.

```
root@xxxx:~# composer --version
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer version 1.4.2 2017-05-17 08:17:52
```

I dont know what that mean. Is it better to run installation with other uiser?

Is it possible to switch user for Composer?

I try to install composer non-interactive / better: I install composer as root user like this:
```
installcomposer() {
cd ~/sources
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" >>"$main_log" 2>>"$err_log"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" >>"$main_log" 2>>"$err_log" || error_exit "Cannot verify Composer Hash! Aborting"
php composer-setup.php >>"$main_log" 2>>"$err_log"
php -r "unlink('composer-setup.php');"
mv composer.phar /usr/local/bin/composer
}
```

Is it better to switch user before install?

**Comment by mikk150** [comment]
You can install composer as root(tho not really best idea, but works)

You shall not EXECUTE! composer as root, because any moron can now run `rm -rf /` on your server/machine

**Comment by Rubemlrm** [comment]
Its better run as "normal" user , instead root , since this can open a huge security breach . Sometimes what i do is install composer to a ~/bin directory and create a alias in shell pointing to the local path of composer. In this way whatever i do is safe for the main system.
