### ISSUE TITLE
Provide sha384sum compatible checksum for composer-setup.php file

### ISSUE THREAD

**Issue by emanuelb** [composer/composer#6526]
I saw the 'How do I install Composer programmatically?'
https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md

and decided to use similar code to accomplish the same thing, see below: which rely on `sha384sum -c` for checksum verification, it will be handy if a compatible checksum will be provided at:
https://composer.github.io/composer-setup.php.sha384sum

currently code used:
> curl --output composer-setup.php.sha384sum https://composer.github.io/installer.sig 
curl --output composer-setup.php --location https://getcomposer.org/installer 
cat composer-setup.php.sha384sum | tr -d '[:space:]' > composer-setup.php.sha384sumN
echo " composer-setup.php" >> composer-setup.php.sha384sumN
sha384sum -c composer-setup.php.sha384sumN

after adding the file at: https://composer.github.io/composer-setup.php.sha384sum (which has the content of https://composer.github.io/installer.sig followed by space and file-name (which is composer-setup.php))
the following will work:

> curl --output composer-setup.php.sha384sum https://composer.github.io/composer-setup.php.sha384sum
curl --output composer-setup.php --location https://getcomposer.org/installer 
sha384sum -c composer-setup.php.sha384sum

**Comment by alcohol** [comment]
Is there a particular reason the current signature provided is not good enough?

**Comment by emanuelb** [comment]
yes, it's not standard digest file (which is created by sha*sum commands from coreutils, such as `sha384sum composer-setup.php`) which enable easier verification via `sha384sum -c checksumfile` command.

**Comment by alcohol** [comment]
I see. That could be correct. We merely provide the signature. Perhaps we could also offer a valid `.digest` file @Seldaek ?

**Comment by Seldaek** [comment]
Added a new file (see https://composer.github.io/pubkeys.html) https://composer.github.io/installer.sha384sum

Hope that solves it for you. Feel free to send a PR to add curl-based instructions to the programmatic install page.
