### ISSUE TITLE
"env: ‘php’: No such file or directory" when running composer update

### ISSUE THREAD

**Issue by emanuelb** [composer/composer#6527]
I develop docker container based on alpine, which install php7 & php7-fpm using apk.
the composer is installed using: (see Issue https://github.com/composer/composer/issues/6526 'Provide sha384sum compatible checksum for composer-setup.php file') as there is no composer package from alpine.

> && curl --output composer-setup.sha384sum https://composer.github.io/installer.sig \
&& curl --output composer-setup.php --location https://getcomposer.org/installer \
&& cat composer-setup.sha384sum | tr -d '[:space:]' > composer-setup.sha384sumN \
&& echo " composer-setup.php" >> composer-setup.sha384sumN \
&& sha384sum -c composer-setup.sha384sumN && rm composer-setup.sha384sum composer-setup.sha384sumN \
&& php7 composer-setup.php --quiet --install-dir=/usr/bin/ --filename=composer && rm composer-setup.php;

running:
composer update in /www directory (which contain the PHP project) will result in:
> env: ‘php’: No such file or directory

calling PHP is possible in the container by using php7:
>php7 -r "echo 1;"

but not via php
> php -r "echo 1;"

fix:
use better detection of which command to use in order to run PHP?

**Comment by emanuelb** [comment]
it's fixed easily by running (before using composer):
> ln -s /usr/bin/php7 /usr/bin/php

still it's probably better to detect where the PHP binary located during setup and use it, thus not need to make the symlink...

**Comment by alcohol** [comment]
If `php` is only installed explicitly as `php7`, then env will not know where to find `php`. I have never encountered this scenario before though. It would appear you are using a custom tailored `php` installation, and not a generic one provided by whichever operating system you are running.

**Comment by emanuelb** [comment]
here test-case how to reproduce it (alpine on docker)

run:

mkdir composertest && nano Dockerfile

> FROM alpine:3.5
RUN apk add --no-cache coreutils curl php7 php7-fpm php7-phar php7-mbstring php7-openssl php7-json php7-zlib
RUN set -x \
    && curl --output composer-setup.sha384sum https://composer.github.io/installer.sig \
    && curl --output composer-setup.php --location https://getcomposer.org/installer \
    && cat composer-setup.sha384sum | tr -d '[:space:]' > composer-setup.sha384sumN \
    && echo " composer-setup.php" >> composer-setup.sha384sumN \
    && sha384sum -c composer-setup.sha384sumN && rm composer-setup.sha384sum composer-setup.sha384sumN \
    && php7 composer-setup.php --quiet --install-dir=/usr/bin/ --filename=composer && rm composer-setup.php \
    && composer;

then run:

> cd composertest &&  docker build -t composertest .

result:

> env: ‘php’: No such file or directory
The command '....;' returned a non-zero code: 127

**Comment by alcohol** [comment]
What if you just install `php`? Does that not also provide the latest version? Also, why not extend `FROM php:7-alpine`?

**Comment by emanuelb** [comment]
it doesn't work with php as dependency (which point to old version of php `5.6.30-r0`)
https://pkgs.alpinelinux.org/packages?name=php
while the app require at least php 7.
regarding `FROM php:7-alpine` usage, it won't let me install gd extension via `php7-gd` or `php-gd`, it's possible to mention `php5-gd` which will install but fail when php code call GD functions...

**Comment by alcohol** [comment]
None of this sounds like a composer issue unfortunately. It is more a provisioning/environment issue. We cannot resolve this on our end.

**Comment by emanuelb** [comment]
There is a open issue about it (regarding php5 package missing symlink to php)
https://bugs.alpinelinux.org/issues/7473
so it's probably need to be fixed by alpine via providing symlinks..
