### ISSUE TITLE
Any way to disable/override execution of composer update unless flags are given?

### ISSUE THREAD

**Issue by BrianGilbert** [composer/composer#6530]
When I run this command:

```
composer update
```

I'd like to be able to configure the following output:

```
echo "You should not run composer update in this project without any flags, did you mean composer update --lock?"
```

And I would expect this to happen:
Project update is not executed, the only way a user can update a package would be to use 

```
composer update /repo/package
```

**Comment by alcohol** [comment]
It is unlikely that this will ever be implemented.

**Comment by alcohol** [comment]
The message you mention does not belong to composer btw. We never output such a message. Must be part of your project, or one of the plugins you are using.
