### ISSUE TITLE
Protect production environment from getting updated 

### ISSUE THREAD

**Issue by robsch** [composer/composer#6533]
I'm not that familiar with composer. So close this issue if it doesn't make sense or if this is already possible.

It just happend recently to me that I called `composer update` on my production system. AFAIK one shouldn't do this. Usually, in production mode only `composer install` should be called. So, to avoid such mistakes it would be nice if composer could prevent that action by default (therefore it needs to know that it is in an production environment, probably by a setting stored in composer.json) and allow it with some kind of _force_ flag. An alternative would be to warn the user and let him confirm that he really wants to update, though it is an production environment.

In automated scenarios that is not so useful. But when deploying manually it would be of some help, I think.

**Comment by Seldaek** [comment]
IMO this isn't a common enough problem to warrant a new feature. Generally deployment should be scripted/automated, so that you never run these commands manually and mistakes don't happen.
