### ISSUE TITLE
I create a private package from svn, how to ignore .svn when composer install or update

### ISSUE THREAD

**Issue by liubusian** [composer/composer#6535]
I create a private package from svn

Now, I can get the repo

but Its structure like:
.svn
src/
composer.json
.....

I want remove ".svn" , how to do ?

I try add .gitignore file, no effect....

help me 

Thanks

**Comment by Rubemlrm** [comment]
.gitIgnore only works with git repositories. Besides that .svn is the svn folder that stores all information relative to the project in case, acts like .git act on a git repository. How do you want to use the package ?

**Comment by lovelock** [comment]
In my case, even packages are in git, there still is a .git directory in vendor/mypackage, THIS WILL ONLY HAPPEN IN Windows. I can't figure out if it's a bug of composer

**Comment by liubusian** [comment]
@Rubemlrm
The repository will give to my customer.
I don't hope that they can see the .svn folder

**Comment by Seldaek** [comment]
Sorry but not sure how to help here.. Private packages in svn are installed via svn so the .svn directory remains behind so when you update it gets updated quicker instead of having to pull the whole svn repo again..

**Comment by andrii-pukhalevych** [comment]
You can add "/composer-svn-export-plugin": "*@dev" to composer.json 'require' section to use svn export instead of svn checkout
