### ISSUE TITLE
How to enable composer on shared IIS windows server

### ISSUE THREAD

**Issue by wilsonld** [composer/composer#6536]
I am trying to install the latest version of Richfilemanager which uses the composer package manager on a website which runs on a shared windows IIS server (Godaddy).  I installed composer on my PC and the Richfilemanager works on the local IIS but when I upload it to the remote shared server, it won't initialize.

Previously, I had problems running .json files on the shared IIS server as it wasn't set up to recognize them.  I don't have the ability to change the IIS settings,  but I modified the Web.config file to include the following coding:

```
<system.webServer>
    <staticContent>
         <mimeMap fileExtension=".json" mimeType="application/json" />
    </staticContent>
</system.webServer>
```

Since I couldn't modify the server setup, this coding in the Web.config file did the trick.

I am clueless as to how to enable the remote IIS server to handle the composer package manager.  Does anyone have information as to how to do it?

**Comment by Seldaek** [comment]
Sorry but I have no idea how IIS comes into play here in the context of running composer.. Composer should be executed from the CLI and will access json files locally. There is no web server involved.

**Comment by Seldaek** [comment]
Automatically closing as this has not received any updates in a while. Please re-open if it is still relevant.
