### ISSUE TITLE
Unknown SSL protocol error in connection to getcomposer.org:443

### ISSUE THREAD

**Issue by airways** [composer/composer#6538]
Previously working Docker build script that relies on composer failing randomly. This is happening right now, while posting this ticket, and has happened periodically over the past week with no relevant changes on our side.

My `composer.json`:

```json
{
  "require": {
     "ext-mbstring": "*",
     "ext-gd": "*",
     "ext-mcrypt": "*"
  }
}
```

Output of `composer diagnose`:

_Not possible to run._

When I run this command:

```
curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer && cd /var/www/ && composer install --no-plugins --no-scripts

```

I get the following output:

```
curl: (35) Unknown SSL protocol error in connection to getcomposer.org:443
```

And I expected this to happen:

Installer script should download composer.phar to the current directly.

This usually works, but we periodically run into a problem where this build step fails. This happens both locally and on AWS via Dockerfile running under Convox.

We have attempted to use composer.phar download directly from the site locally, but in this case the SSL errors prevent packages from being loaded by composer.

It looks like a server configuration error in getcomposer.org, possibly related to the server's system time since the error seems to resolve itself after an indeterminate period of time. Just a guess though.

**Comment by airways** [comment]
This just cleared up, again without any changes on our part:

```
curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer && cd /var/www/ && composer install --no-plugins --no-scripts

```

Current output from above build step:
```
All settings correct for using Composer
Downloading...

Composer (version 1.4.2) successfully installed to: /var/www/html/composer.phar
Use it: php composer.phar
```

**Comment by Bukashk0zzz** [comment]
Have same problem time to time on our CI server.

**Comment by ragboyjr** [comment]
Similar issue here. It's off and on.

```
curl -sS https://getcomposer.org/installer | php
curl: (35) gnutls_handshake() failed: Error in the push function.
```

**Comment by curry684** [comment]
Afaics this was a 2 minute booboo. If we expect Composer and Packagist to have an 100.000% uptime like Google instead of the 99.9% it's currently doing fine we should consider sending the authors a Google sized budget perhaps. The only way to never have errors like this is to have a redundant distributed CDN with dedicated SSL terminating redundant loadbalancers, and there's simply no budget for that on this free service. [You can help though and fix your own problems in one go](https://packagist.com/).

**Comment by lox** [comment]
Seeing this randomly over the past few days as well. 

@curry684 that was a particularly hostile response, I don't think anyone is saying they expect 100% uptime.

**Comment by curry684** [comment]
In IT in general and issue tracker comments in particular the single most unconstructive type of feedback is "Hey I'm also experiencing issue X", as it indicates you're expected some kind of SLA despite not paying for one. There's nothing hostile at all about simply pointing out at that it's not realistic to expect this kind of uptime from a free service serving terabytes of traffic per month.

I also had 2 CI jobs fail. I hit retry and they succeeded. It happens.

**Comment by lox** [comment]
I can understand that view point, but often you need a few data points to indicate something is a pervasive issue. If it's a transient issue them sure, retry and write it off to internet gremlins. If there is some underlying issue that needs addressing then the issue reports help.

**Comment by lsh-0** [comment]
+1, I'm also experiencing this issue.

(heh)

I wrote it off to Internet Gremlins when I experienced it twice last week but I just experienced it twice this morning. @curry684 , if getcomposer.org isn't good enough, for whatever reason, you might consider relying on github or google to serve your content.

**Comment by perk11** [comment]
Also experiencing this

**Comment by curry684** [comment]
@lsh-0 all package downloads are already served by Github, the terabytes of traffic on packagist.org are only metadata used for package resolution. So far no sponsor has been found for that, and a proper solution with AWS/Azure/GCE is therefore out of budget.

**Comment by zenoyu** [comment]
Also run into this issue today

**Comment by mohitbagde** [comment]
Just ran into this today as well. Based off of comments, seems like it's very rare and intermittent and the best solution is to simply re-try the `composer update/install`.

I re-tried 2-3 times after a few minutes, and it worked. 👍

**Comment by parisk** [comment]
I ran into this today, when installing Composer in a Docker container, running via "Docker In Docker" on Azure.

The workaround for me was the one described at https://github.com/moby/moby/issues/13475#issuecomment-108707488.

I changed "Docker in Docker"'s MTU to 1400.

Hope it helps.

**Comment by scandel** [comment]
Also experiencing this issue. In our CI it happens every day at the same time,  at 00:00 GMT. Waiting a few minutes and retrying doesn't solve anything, but waiting half an hour usually does.

**Comment by scandel** [comment]
While writing my previous comment, I was thinking that mabye the time where the problem occured (always around 00:00 GMT in my case)  was important. I shifted our CI jobs at 01:00 GMT, and it seems to have solved the problem. But I don't know why ???

**Comment by scandel** [comment]
While writing my previous comment, I was thinking that mabye the time where the problem occured (always around 00:00 GMT in my case)  was important. I shifted our CI jobs at 01:00 GMT, and it seems to have solved the problem. But I don't know why ???
