### ISSUE TITLE
Support for platform presets

### ISSUE THREAD

**Issue by hailwood** [composer/composer#6544]
With the uptake in docker running composer now has three different methods of running composer.

1. Run docker inside the container
2. `composer update --ignore-platform-reqs`
3. a `platform` entry in the composer.json to fake the environment

The first option is a bit of a hassle since you have to sort up linking your composer cache etc.
The second option is a bit of a nuke but one I believe most docker users are now using
The third option is likely the most reliable, unfortunately it requires adding a platform entry to each projects composer.json

Given that we use 3 different docker containers for different environments; But these cover > 200 projects I am proposing that we allow adding user defined named platform presets to your global composer.json.

These would like as below

```json
{
   "config": {
      "platform_presets": {
         "php7": {"php": "7.1", "ext-something": "4.0"},
         "php5": {"php": "5.6", "ext-something": "4.0"},
         "laravel": {"php": "7.1", "ext-laravel-specific": "4.0"}
      }
   }
}
```

Then when invoking composer you would use `composer --platform php7 update`

This gives a tidy middle ground between the nuclear option, and having to define the platform on every composer.json

Additionally savvy users can create aliases for these platforms so it becomes as simple as
`comp7 install` to keep things quick.

I would be keen to give a pull request for this a go if the idea gets approved.

**Comment by Seldaek** [comment]
Have you considered using https://github.com/wikimedia/composer-merge-plugin instead? I think it's better as it offers a generic way to import stuff.. You could have 3 presets as 3 different files defined globally for example.

I am not too keen on adding this functionality to composer itself as it seems fairly specific to your use case and generally speaking actually installing the right extensions is the preferred way IMO.
