### ISSUE TITLE
Update failed when unzipping (in Windows)

### ISSUE THREAD

**Issue by j-d** [composer/composer#6546]
There is a package, `google/apiclient-services` that is causing problems. 

The reason is that there are two folders here: https://github.com/google/google-api-php-client-services/tree/master/src/Google/Service that are called `BigQueryDataTransfer` and `BIGQUERYDATATRANSFER` that in Windows clash. 

Because of that, `composer update` crashes and gives the following message
```
  - Updating google/apiclient-services (v0.11 => v0.14): Downloading (100%)    Update failed (Failed to execute unzip -qq '/var/www/ccr/vendor/google/apiclient-services/e205a6443d455ac896f2245d48c65207' -d '/var/www/ccr/vendor/composer/a00378c6' && chmod -R u+w '/var/www/ccr/vendor/composer/a00378c6'

replace /var/www/ccr/vendor/composer/a00378c6/google-google-api-php-client-services-b8c3ee8/src/Google/Service/BigQueryDataTransfer.php? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
)
    Would you like to try reinstalling the package instead [yes]?
  - Removing google/apiclient-services (v0.11)
  - Installing google/apiclient-services (v0.14): Downloading (100%)    Failed to download google/apiclient-services from dist: Failed to execute unzip -qq '/var/www/ccr/vendor/google/apiclient-services/e205a6443d455ac896f2245d48c65207' -d '/var/www/ccr/vendor/composer/ebc82f66' && chmod -R u+w '/var/www/ccr/vendor/composer/ebc82f66'

replace /var/www/ccr/vendor/composer/ebc82f66/google-google-api-php-client-services-b8c3ee8/src/Google/Service/BigQueryDataTransfer.php? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
```

Because it is waiting for an answer to that prompt. 

I understand that Google's naming convention is far from ideal on this case, but I don't think it should crash. 

My `composer.json`:

```json
{
    "name": "root/tmp",
    "require": {
        "google/apiclient-services": "dev-master"
    },
    "authors": [
        {
            "name": "John Smith",
            "email": "john@example.com"
        }
    ]
}
```

When I run this command:

```
composer update
```

**Comment by alcohol** [comment]
This is a known issue that has no work-around or solution. These kind of mistakes (assuming all hosts will have case-sensitive filesystems) are just poor developer judgement. Unfortunately from our end we cannot fix this as we cannot just go ahead and rename things. You'll have to patch the library yourself (fork, send a PR, or whatever else you can come up with).

**Comment by j-d** [comment]
Thanks @alcohol
