### ISSUE TITLE
updating symlinked dependency doesn't work without removing vendor folder and specify subdependency

### ISSUE THREAD

**Issue by sod** [composer/composer#6547]
Testcase: https://github.com/sod/composer-update-symlinked-issue
Environment: macOS 10.12.5 / composer 1.4.2

### Precondition
I have `mylib` and `myapp`, both in one repository. `myapp` requires `mylib`. It's configured via `repositories => type: "path"` to be symlinked.

### What I want to do
Update a dependency in `mylib`. Then update `mylib` in `myapp`

### How I expected it to work
```sh
cd mylib;
composer require jms/metadata 1.6
cd ../myapp;
composer update mylib
# jms/metadata is still on old version in myapp 1.3
```

### How it actually works
```sh
cd mylib;
composer require jms/metadata 1.6
cd ../myapp;
rm -r vendor; composer update mylib jms/metadata # remove vendor and update both
# jms/metadata was updated to 1.6
```

Also, if you just
`composer update mylib jms/metadata` (not removing vendor), or:
`rm -r vendor; composer update mylib` (not updating jms/metadata)
it also doesn't work.

**Comment by sod** [comment]
Just found out, this also works

```sh
composer update mylib '*'
```

I guess I go with that?

**Comment by alcohol** [comment]
Is your path repository of the type `git`? And did you actually make a new commit after you required this new dependency?

**Comment by Seldaek** [comment]
If you do `update mylib *` you're basically updating everything. What you need to do is `composer update mylib --with-dependencies`, or `composer update mylib jms/metadata` if you know exactly which packages you want to update.
