### ISSUE TITLE
Command line argument handling is unintuitive and fails subtly

### ISSUE THREAD

**Issue by apapsch** [composer/composer#6550]
This bug is independent of any composer.json.

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer -d /tmp install
```

I get the following output:

```

                                                               
  [RuntimeException]                                           
  Invalid working directory specified, --ansi does not exist.  
                                                               


```

And I expected this output:

```
Composer could not find a composer.json file in /tmp
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
```

It isn't clear that composer doesn't do "standard" argument handling, like GNU software established. E.g. I would expect the following to be parsed alright:

* -d/tmp
* -d /tmp
* --working-dir /tmp
* --working-dir=/tmp

but actually only this works:

* -d=/tmp
* --working-dir=/tmp

Even if composer doesn't want to adopt standard argument handling, it shouldn't fail with this cryptic message.

**Comment by alcohol** [comment]
Composer doesn't do much of the argument handling, `symfony/console` does most of the heavy lifting. Please file a bug with their component if you feel that it does not behave as it should. If you believe that this is a bug specific to composer only, then please provide some insight into why/how.
