### ISSUE TITLE
Support request: SemVer policy on public API

### ISSUE THREAD

**Issue by greg-1-anderson** [composer/composer#6551]
The [Composer\Autoload\ClassLoader::getPrefixesPsr4() method is public](https://getcomposer.org/apidoc/master/Composer/Autoload/ClassLoader.html#method_getPrefixesPsr4), but has no API documentation (beyond its basic unadorned entry in the API docs).

- Is this method considered to be part of the Composer 1.x stable API? That is, can we count on it remaining public, not being removed, and the structure of the data it returns remaining the same?
- Are all public methods of public classes considered to be covered by the SemVer contract to maintain compatibility for all releases in the 1.x version line?
- Can we count on autoload.php always returning a `Composer\Autoload\ClassLoader` object?

Considering using this in a simple lightweight plugin mechanism: https://github.com/consolidation/Robo/pull/604

**Comment by alcohol** [comment]
We generally follow semver quite closely. Anything that is public now won't be made protected or private without a major release increase. API documentation is minimal because generally we mostly support composer as a binary tool, not as a library.

**Comment by greg-1-anderson** [comment]
Great! Thank you for the clarification.
