### ISSUE TITLE
Switch to Symfony 5

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#6552]
Just a list of things that would be good to have once we can switch to Symfony 3 (or 5..), as a reminder only.

- https://github.com/symfony/symfony/pull/21474
- ..?
- See https://symfony.com/blog/new-in-symfony-5-3-negatable-command-options

**Comment by Webysther** [comment]
Symfony 4 require PHP 7.1, it sounds huge drop of PHP support.

**Comment by staabm** [comment]
I would guess that you can still use composer 1.x for old php versions and composer 2.x for more modern ones.

**Comment by stof** [comment]
Another thing that will come: native color support on windows 10 for PHP 7.2+, as soon as symfony/console supports them (which is on my TODO-list for 3.4)

**Comment by derrabus** [comment]
Are there any plans on when to do a Composer 2 and what target environment it would have? I would volunteer to help with the migration, if help is needed. The migration could also be a source of tasks for the SymfonyCon hackday, maybe.

**Comment by stof** [comment]
@derrabus Composer is already compatible with Symfony 3 when using it as a library. What is impacted by this task is the phar, which requires being compatible with PHP 5.3 currently, and so cannot use Symfony 3 (which requires 5.5.9+)

**Comment by teohhanhui** [comment]
I think Composer 2.0 could safely drop support for PHP < 5.6, at the very least. Since even WordPress has been nagging users to upgrade to at least PHP 5.6 for a while now: https://wordpress.org/news/2019/04/minimum-php-version-update/

**Comment by BafS** [comment]
As composer 2.3 targets PHP 7.2+ Symfony 5 components could be used right ? Is the title outdated or is there a reason for Symfony 3 ?

**Comment by stof** [comment]
@BafS the title was not updated since 2017.

**Comment by BafS** [comment]
I realized that @stof :) but as I saw some activity here I was wondering if it is intentional or if Symfony 5 could be a possibility

**Comment by stof** [comment]
@BafS the newest discussion happened in https://github.com/composer/composer/issues/9303#issuecomment-720714140

**Comment by BafS** [comment]
Ah great, thanks !
