### ISSUE TITLE
Composer exclude from class map won't work on absolute path with symlink

### ISSUE THREAD

**Issue by JacobCohenIsrael** [composer/composer#6553]
I have the following autoload:

```
  "autoload" : {
    "classmap": ["src/", "../library/project/src", "tests/mocks"],
    "exclude-from-classmap": ["../psl-library/project/src/Couchbase.php"]
  }
```
The result is as I expected - inside autoload_classmap.php I get this:

`'Couchbase' => $baseDir . '/tests/mocks/Couchbase.php'`
I have made a symlink from to the `../library/project/src` to `/var/www/html/include/library`

Then my autoload looked like as follows:

```
  "autoload" : {
    "classmap": ["src/", "/var/www/html/include/library", "tests/mocks"],
    "exclude-from-classmap": ["/var/www/html/include/library/Couchbase.php"]
  }
```
After running dumpautoload I get an unexpected result:

`'Couchbase' => '/var/www/html/include/library/Couchbase.php'`
Any idea what might be the problem when working with absolute path or with symlinks?

**Comment by alcohol** [comment]
#6553

**Comment by alcohol** [comment]
#4604
