### ISSUE TITLE
Error trying to install the Composer 

### ISSUE THREAD

**Issue by Akinyemi1** [composer/composer#6559]
I tried installing but I got stuck with this error .....

C:\Users\DELLS>composer -V
Composer version 1.4.2 2017-05-17 08:17:52

C:\Users\DELLS>C:\xampp\htdocs\amp-library-master\
'C:\xampp\htdocs\amp-library-master\' is not recognized as an internal or external command,
operable program or batch file.

**Comment by curry684** [comment]
Considering that Composer is correctly reporting its version and build date I'd say your installation went just fine. The second command has nothing to do with Composer.
