### ISSUE TITLE
TLS support in composer, with php 7.2, without openssl.so ?

### ISSUE THREAD

**Issue by pgnd** [composer/composer#6562]
I'm building PHP 7.2-dev on linux64.

OpenSSL 1.1 is installed locally.

The openssl extension is not Openssl 1.1 compatible; reports/patches for it get no attention.

For general php crypto, not so much a problem anymore, as libsodium's a fine crypto alternative -- and now in PHP 7.2+ core.

So my PHP 7.2 gets built -openssl, +sodium.

Unfortunately, 'composer' now complains for lack of openssl

```
composer --version
	Composer version 1.4.2 2017-05-17 08:17:52

composer self-update
  [Composer\Exception\NoSslException]
  The openssl extension is required for SSL/TLS protection but is not available. If you can not enable the openssl extension, you can disable this error, at your own risk, by setting the 'disable-tls' option to true.
```

Yes, there's the "disable-tls" option -- but obviously not ideal.

AFACIT, sodium still does not implement TLS protocol ... so, catch-22.

*IS* there an option for composer/TLS when Openssl 1.1.0 is installed, other than a self-patched openssl php ext?

NOTE:  this is relevant ...
https://github.com/composer/composer/issues/5917

**Comment by Seldaek** [comment]
Is libsodium a replacement for libopenssl for https streams? If not then we'll still need to require ext-openssl, if it can replace it fully we have to see about adjusting some code I guess.

**Comment by stof** [comment]
Well, as libsodium does not implement TLS, openssl is still required for PHP to support it. In any case, Composer cannot make the change. The TLS implementation for PHP streams is done in PHP, not in Composer.

**Comment by Seldaek** [comment]
Of course we don't want to implement TLS ourselves. I missed the line about sodium not implementing TLS.. So I don't really get what this issue is about. 

We are not going to use a system-wide openssl to implement TLS on top of php streams oureslves either, that's just a waste of energy when ext-openssl does it well enough.
