### ISSUE TITLE
Cannot download require-dev in repositories package(path)

### ISSUE THREAD

**Issue by panlatent** [composer/composer#6563]
My `composer.json`:

```json
"repositories": [
        {
            "type": "path",
            "url": "extensions/*"
        }
    ]
```

When I run this command:

```
composer install
composer update
```

Composer only download/parser `extensions` directory some packages `require` And ignored the `-dev`。 Is it a feature or a bug? What's the point?

**Comment by alcohol** [comment]
Incomplete information provided.

**Comment by Seldaek** [comment]
No idea what you mean by `ignored the -dev`. Please provide more info and what you expected / what happened if you want help.
