### ISSUE TITLE
Cake php

### ISSUE THREAD

**Issue by AREN7** [composer/composer#6564]
Someone can help me to resolve this probleme please...
My computer have the minimum requirements to install cake php
- HTTP Server
- PHP version 7.1
- mbstring PHP extension enbled 
- intl PHP extension enbled
- OS : windows 8.1
I already used composer with laravel project and work fine.
Bur after updating it, if I create project with cake php, it still load and show the message bellow.

"## composer create-project --prefer-dist cakephp/app cake01
**Content-Length mismatch
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date

  [InvalidArgumentException]
  Could not find package cakephp/app with stability stable.**
"

I really need it to finish my project. 
Thank you.

**Comment by curry684** [comment]
It was either a transitional problem or a local isssue since I have no problems running that command.

**Comment by AREN7** [comment]
Thank you
