### ISSUE TITLE
dependency problem

### ISSUE THREAD

**Issue by vdvb** [composer/composer#6573]
hello,
I don't know if this is the right place but i don't get any answer from the "plugin" author.
It's also related to composer so i try it here also.
I installed a yii2 plugin with composer  ->  kartik-v/yii2-date-range
This plugin depends on dangrossman/bootstrap-daterangepicker plugin

the kartik-v/yii2-date-range is missing the isCustomDate option, not available in Version: 2.1.19 but it is in the latest Version: 2.1.25(from dangrossman)
I hope it's a bit understandable :-). 

How can i resolve this
Thx.
B

**Comment by Seldaek** [comment]
Sorry but this has nothing to do with Composer it seems.. We are not responsible for every PHP package out there :)
