### ISSUE TITLE
Composer.Err  [InvalidArgumentException]       Project directory basic/ is not empty.

### ISSUE THREAD

**Issue by NadyaCrasina** [composer/composer#6577]
Ubuntu 16.04. Install yii2 framework local in /home/red/composer. 
1. ~/composer $ composer create-project --prefer-dist yiisoft/yii2-app-basic basic
Err: [Composer\Repository\InvalidRepositoryException]                                                                                      
  No valid bower.json was found in any branch or tag of https://github.com/twitter/typeahead.js.git, could not load a package from it. 
2.composer create-project --prefer-dist --stability=dev yiisoft/yii2-app-basic basic
Err:[InvalidArgumentException]              
  Project directory basic/ is not empty. 

What's wrong?

**Comment by alcohol** [comment]
`bower.json` is not a Composer issue.
