### ISSUE TITLE
Fire a new event, InstallerEvents::FAILED_DEPENDENCIES_SOLVING

### ISSUE THREAD

**Issue by dave1010** [composer/composer#6583]
`Composer\Installer:doInstall()` fires an `InstallerEvents::PRE_DEPENDENCIES_SOLVING` and an `InstallerEvents::POST_DEPENDENCIES_SOLVING` but if it fails then it returns an error code without any more events being fired.

Can a new InstallerEvent be dispatched if resolving dependencies failed, so plugins can hook into it?

Alternatively,  `InstallCommand` could dispatch a CommandEvent after calling `$install->run()`?

It could be that there's a much better way for plugins to hook into failed commands. If that's the case then please point me in the right direction. Thanks.

**Comment by Seldaek** [comment]
Do you mind sharing more about the use case that you're trying to solve?

**Comment by dave1010** [comment]
Sorry for the slow reply. The original idea was to provide semi-interactive help to resolve dependency issues (eg platform requirements, SSH keys) for some projects as a standalone plugin. The idea hasn't really gone anywhere, so I don't think this specific use case is valid.

I was going to have a go at a pull request for this but realistically I'm not going to get time for a while. Feel free to close as won't fix unless you think there's value in this for others.

**Comment by Seldaek** [comment]
Barring a real use case I rather not add code that won't be able to removed due to BC concerns, so yes let's close for now :)
