### ISSUE TITLE
Compose Doesn't Recognize Current Feature Branch

### ISSUE THREAD

**Issue by bbatsche** [composer/composer#6585]
If my project is on a branch configured as a `feature-branch`, compose will report the current version as this branch's *parent*, rather than the branch itself. For example, here is my project git tree:

```
+- master
 \
  +- develop 
   \
    +- fizz <== currently checked out branch
```

My `composer.json`:

```json
{
    "name": "foo/acl",
    "minimum-stability": "stable",
    "require": {
        "php": "^5.6 || ^7.0",
        "foo/core": "self.version"
    },
    "repositories": [{
        "type" : "git",
        "url": "ssh://git@git.bar.io/foo/core.git"
    }],
    "feature-branches": [
        "master",
        "develop",
        "fizz"
    ]
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer show -s
```

I get the following output:

```
name     : foo/acl
descrip. :
keywords :
versions : * dev-develop
source   : []  abcdef0123456789
dist     : []  abcdef0123456789
names    : foo/acl

requires
php ^5.6 || ^7.0
foo/core self.version
```

And I expected this to happen:

Version should be `dev-fizz` as that's the currently checked out branch, and is set to be a standard feature branch.

This seems related to the logic in [Composer\Package\Version\VersionGuesser::guessFeatureVersion()](https://github.com/composer/composer/blob/965f1f42d1239e495bb93ff101120a509476636e/src/Composer/Package/Version/VersionGuesser.php#L197). If I had a better sense of what the intended logic in that `foreach ()` loop was, I'd been happy to create a pull request for this.

**Comment by alcohol** [comment]
Cannot reproduce:

```
rob@macbookpro.local /tmp/test > git checkout -b develop
Switched to a new branch 'develop'

rob@macbookpro.local /tmp/test > git add composer.json

rob@macbookpro.local /tmp/test > git commit
[develop (root-commit) eabfeff] test
 1 file changed, 3 insertions(+)
 create mode 100644 composer.json

rob@macbookpro.local /tmp/test > composer show -s
name     : foo/bar
descrip. :
keywords :
versions : * dev-develop
type     : library
source   : []  eabfefff32e9cf8f68b48d515a8e6168055523ba
dist     : []  eabfefff32e9cf8f68b48d515a8e6168055523ba
names    : foo/bar

rob@macbookpro.local /tmp/test > git checkout -b test
Switched to a new branch 'test'

rob@macbookpro.local /tmp/test > touch foo

rob@macbookpro.local /tmp/test > git add foo

rob@macbookpro.local /tmp/test > git commit
[test 78c05c4] added foo
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 foo

rob@macbookpro.local /tmp/test > composer show -s
name     : foo/bar
descrip. :
keywords :
versions : * dev-test
type     : library
source   : []  78c05c4820643ef91307f70a65d7f30ec063a22f
dist     : []  78c05c4820643ef91307f70a65d7f30ec063a22f
names    : foo/bar
```

**Comment by Seldaek** [comment]
@bbatsche that's not a bug it's a feature because it lets you work with cyclic dependencies even when you are on feature branches. What is the problem with this feature? Is there any other issue than you realised that it's not showing you the branch you expected?

**Comment by bbatsche** [comment]
The problem is that if I try to run `install` or `update`, I get the incorrect version of `foo/core`. So the situation is as follows:

1. I'm working in `foo/acl`
1. I have the branch `fizz` checked out
1. `foo/acl` depends on `foo/core` which also has a branch `fizz`
1. `foo/core` has the same dependency on `foo/acl` (yes circular dependencies are the devil, I'm sorry)
1. `fizz` is in the list of `feature-branches` in both

Expected:
1. Running `install` or `update` should attempt to install `foo/core[dev-fizz]`
1. `foo/core`'s dependency on `foo/acl` should already be satisfied by the checked out repository

Actual:
1. Running `install` or `update` tries to install `foo/core[dev-develop]`
1. `foo/core` requires `foo/acl[dev-develop]`
1. Since that branch is different than what's currently checked out, the dependency isn't satisfied
1. Install/update fails

**Comment by bbatsche** [comment]
Digging into the code looks like changes for `feature-branches` has been removed; I'm going to pull the latest update and do some more testing. Sorry if I brought up an out-of-date issue 😅

**Comment by Seldaek** [comment]
@bbatsche I pushed the removal of feature-branches 10min ago, bad race condition there. But you can use `"non-feature-branches": ["fizz"]` and that should work (in latest snapshot.. 1.5 tag coming up in a second)

**Comment by bbatsche** [comment]
@Seldaek Just saw your commit and read the comments. That makes **so much** more sense; I was really getting turned around with those key names in `composer.json`. I'm going to go ahead and close this and see if things work better now with `non-feature-branches`. If I'm still running into things, will just open a new issue. Thanks!
