### ISSUE TITLE
WAMP Composer Drupal Opensocial can't install

### ISSUE THREAD

**Issue by wisamx** [composer/composer#6586]
Hello!

I am so tired of trying to install dependence for Drupal 8 Opensocial using Composer.
I have been searching and trying things for 2 days.
Windows 10 x64
WAMP Server 3.0.6 64bit
Apache 2.4.23 - PHP 5.6.25 - MySQL 5.7.14
PHP 5.6.25 for CLI (Command-Line Interface)

```
E:\wamp64\www\social-8.x-1.2>composer config repositories.drupal composer https://packages.drupal.org/8

E:\wamp64\www\social-8.x-1.2>composer require "drupal/address ~1.0"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev) **//notice: at this point there's an internet traffic for about 30sec (512kbps adsl internet)**

Installation failed, reverting ./composer.json to its original content.


  [Composer\Downloader\TransportException]
  The 'http://packagist.org/p/drupal/core-proxy-builder%24a745f947f24079d630ae9fc1bf4e24d8f800ef768fd161756f509d24848
  a4dc0.json' URL could not be accessed: HTTP/1.1 400 Bad URI


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...
```

Composer Diagnose

```
E:\wamp64\www\social-8.x-1.2>composer diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

**Comment by alcohol** [comment]
You cut off a lot of output. Also, it seems to attempt to use a http url. Did you disable https on purpose? Cause by default everything should be https..

**Comment by Seldaek** [comment]
@alcohol no it isn't, we downgrade to http for performance reason after fetching the first file, since the rest can be verified using the sha256 hash chain.

@wisamx Do you have any proxy by any chance? Because that `URL could not be accessed: HTTP/1.1 400 Bad URI` is pretty odd.. The URL is very much valid.

**Comment by alcohol** [comment]
@Seldaek I know, that is why I said that he cut off a lot of output. Because it **could** be because of a downgrade, but without the full output we cannot know for sure.

**Comment by Seldaek** [comment]
It's not just the downgrade with message, that switches back to http/1.0 and other stuff, but by default it also downgrades silently to http after the first https request. But anyway I agree there isn't enough info to make sense of anything.

**Comment by wisamx** [comment]
thanks for your responses.
I tried composer in an empty folder to install libraries it works.
the problems was when I was trying to install Drupal 8 Open Social.
Then for somehow installing composer wasn't enough that i needed to install git manually.
I could install open social.

**Comment by alcohol** [comment]
So..... does that mean your issue is solved? 👍
