### ISSUE TITLE
Optimize json cache with diff-encoding

### ISSUE THREAD

**Issue by donquixote** [composer/composer#6589]
When running `composer install -vvv` or `composer update -vvv` on a project with many dependencies, a lot of time is spent on operations like this:
> Reading /home/USERNAME/.composer/cache/repo/https---packagist.org/provider-symfony$workflow.json from cache 

Looking into these json files reveals that they contain the entire composer.json for each version of the package. Obviously this means a lot of redundancy.

One way to make this faster would be to have the first version of a package explicit, and then for each subsequent version only store the diff.

Of course it would be useful to let packagist already serve the optimized json files.
But to make it less disruptive, it could instead be implemented locally as a cache layer on top of the file download cache.

How exactly the diff encoding would work? There are different formats imaginable.
E.g. as elementary operations "add", "set", "unset":
```json
{
  "packages": {
    "symfony\/workflow": {
      "base": {
        "name": "symfony\/workflow",
        "description": "Symfony Workflow Component",
        [..]
      },
      "versions": {
        "3.2.x-dev": [
          ["add", ["keywords"], "new-keyword"],
          ["set", ["autoload", "psr-4", "\\Acme\\Foo"], "src/Foo"],
          ["unset", ["autoload", "psr-4", "\\Acme\\Legacy"], "src/Foo"],
          [..]
        ],
        [..]
      }
    }
  }
}
```
I imagine running these operations in PHP will be faster than the time we currently lose on file read and json_decode().

Of course the idea of not treating every version separately could be spun further, which would allow to also optimize the "Resolving dependencies through SAT" step. But let's do one step at a time.

**Comment by alcohol** [comment]
There are some plans in the works already to optimize the way composer and packagist handle metadata etc. What you are proposing is not really feasible though, as the effort far exceeds the gains.

**Comment by donquixote** [comment]
> as the effort far exceeds the gains.

I would imagine the typical composer install or update to become twice as fast or faster with an improvement like this. Or more precisely, I think that the reading of the files could actually be sped up by a factor of 10x or something, but there is still some other part of the operation that would not get faster, so.. this is why I say 2x.
Of course I would have to back this up, but I really think there is a significant gain possible here.

The technical changes would be:
- class Composer\Cache would remain as it is today.
- In ComposerRepository, whenever it says `json_decode($this->cache->read($cacheKey))`, it would instead read `$this->dataCache->read($cacheKey)`.
- This "data cache" would be a layer on top of the current file cache. It can store the compressed arrays as json or as serialized PHP values, it does not matter.
- Other components can use the new data cache, or continue using the file cache.

There may be some tricky details, but the general idea does not look so difficult.

**Comment by Seldaek** [comment]
@donquixote don't forget that files are gzipped at the moment, so a lot of this redundant info gets crunched down on the wire at least. Anyway we will consider such tricks for the 2.0 exchange format for sure, when the time comes.

**Comment by donquixote** [comment]
Actually it can be much smarter than this.
Currently we are downloading and caching the composer.json of every version of a project (all combined into one file).
But really, for the dependency resolution, we only need a small subset of the composer.json file. E.g. all the autoload information is irrelevant for dependency resolution.
Then, as in my previous argument, the dependencies do not change with every version. Instead, we usually have a range of versions with the same dependencies.

The dependency resolver could, in a first step, find a pool of version ranges. Then, in a second step, it could decide on concrete version numbers.

@Seldaek Is there any discussion about the 2.0 exchange format?
