### ISSUE TITLE
Not able to add package

### ISSUE THREAD

**Issue by vivdub** [composer/composer#6591]
Hi,

This is my first package that I created and submitted to packagist.
Once submitted I am not able to add it.
https://packagist.org/packages/vivdub/distmatrix

My `composer.json`:

{
    "name": "vivdub/distmatrix",
    "description": "The package is intented to use google distance matrix api to find the time required to travel between destinations.",
    "type": "library",
    "authors": [
        {
            "name": "vivdub",
            "email": "vivdub@yandex.com"
        }
    ],
    "require": {}
}

Output of `composer diagnose`:

Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: WARNING
You are not running the latest stable version, run `composer self-update` to update (1.2.3 => 1.4.3)

When I run this command:
composer require vivdub/distmatrix

I get the following output:
[InvalidArgumentException]                                                   
  Could not find package vivdub/distmatrix at any version for your minimum-st  
  ability (stable). Check the package spelling or your minimum-stability

**Comment by alcohol** [comment]
Did you run 
```
composer require vivdub/distmatrix
```
or
```
composer require vivdub/distmatrix:dev-master
```

Because the first will not work until you have a stable release. But you can install `dev-master` if you explicitly specify it.

I just did:
```
rob@thuis.robbast.nl /tmp/test > docker run -v $(pwd):/app composer require vivdub/distmatrix:dev-master
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing vivdub/distmatrix (dev-master 0df999b): Cloning 0df999bd23 from cache
Writing lock file
Generating autoload files

rob@thuis.robbast.nl /tmp/test > cat vendor/vivdub/distmatrix/README.md 
<p># DistMatrix This is a laravel package using Google Distance Matrix Api, to find the time required to travel between destinations. <br /><br /> <strong>Using the package</strong></p>
<ul>
<li>Use&nbsp;name space:&nbsp;<br /><em>use Vivdub\DistMatrix\GMap;<br /><br /></em></li>
<li>Create Object:<br />$gmap = new GMap(env("DIST_MATRIX_API_KEY", ""));<br /><br /></li>
<li>Provide coordinates:<br />$gmap-&gt;timeWithCoordinates(array($source_lat,$source_lon), array(array(dest_lat1, dest_lon1), array(dest_lat2, dest_lon2)));<br /><br /></li>
<li>Get the duration text.<br />$gmap-&gt;getDurationText(0,0);<br />//== First argument is source, since the method created is always using one source coordinate set, so this will always be 0 (for now), other parameter is destination index, in order you provided.</li>
</ul>
<p>&nbsp;</p>
<p>&nbsp;</p>
```

**Comment by vivdub** [comment]
Thanks

**Comment by vivdub** [comment]
I am getting following error

**composer require vivdub/distmatrix:dev-master**

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize

                                                           
  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'Vivdub\DistMatrix\DistMatrixProvider' not found   
                                                           

Script php artisan optimize handling the post-update-cmd event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

**Comment by vivdub** [comment]
Got it working.
There was small issue.
