### ISSUE TITLE
ignore-platform-reqs installs dev-master instead of correct version

### ISSUE THREAD

**Issue by michabbb** [composer/composer#6593]
My `composer.json`:

```json
{
  "name": "xxxxxxxxx/xxxx",
  "description": "test",
  "config": {
    "secure-http": false,
    "platform": {
      "php": "5.6.30"
    }
  },
  "minimum-stability": "dev",
  "require": {
    "php"        : ">=5.6",
    "ext-json"   : "*",
    "ext-soap"   : "*",
    "ext-curl"   : "*",
    "ext-mysqli" : "*",
    "laravie/parser": "~1.0"
  }
}
```

PHP Version: 7

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: WARNING
You are not running the latest stable version, run `composer self-update` to update (1.4.2 => 1.4.3)
```

When I run this command:

```
composer --ignore-platform-reqs update
```

I get the following output:

```
Installing illuminate/support (dev-master fcaaaeb)
```

And I expected this to happen:

```
Installing illuminate/support (5.4.x-dev 8090663)
```

[the composer.json of laravie/parser](https://github.com/laravie/parser/blob/master/composer.json)
says:

` "illuminate/support": "^5.1"`

i understand that `ignore-platform-reqs` ignores php version and php extensions, but i don´t understand why ignoring platform requiremtens automatically means, to install different t´versions of packages.

without `ignore-platform-reqs` i get the correct package installed: 

`illuminate/support (5.4.x-dev 8090663)`

with `ignore-platform-reqs` i get installed:

`illuminate/support (dev-master fcaaaeb)`

and in that case the key `ignore-platform-reqs` doesn´t help me at all, because i never can trust that on my dev env i get the same packages installed like on my production env.

**Comment by Seldaek** [comment]
You define the platform to be php 5.6:

```
    "platform": {
      "php": "5.6.30"
    }
```

And `illuminate/support 5.5/dev-master` requires php 7, so when you ignore platform requirements it gets installed, but when you don't it can not be installed so it uses  `illuminate/support 5.4` instead.

The question is why you are using --ignore-platofrm-reqs at all? If you define your platform like that, including extensions you have installed in production, then you should not need to use that flag.

**Comment by michabbb** [comment]
@Seldaek this might look strange, but it's very easy explained:

- my dev env is a docker container based on php 5.6.30
- [i use composer as a container, too](https://github.com/composer/docker)

so my code runs with php 5.6.30 but the composer container is created with php 7.0

so in that case i am forced to use `ignore-platform-reqs` - to ignore the fact that i dont want to check the php version and don´t want to check if php-ext exists.

but i don´t understand the sense, that when the php version gets ignored, that composer ignores my wish for a specific version.  laravie/parser says "i want illuminate/support 5.1 so why do i get dev-master ?
i do myself terrible hard to understand this, sorry.....

**Comment by Seldaek** [comment]
You seem to misunderstand the platform config.. When you define it, it fakes your environment so that no matter which PHP you are running with, composer assumes it is always 5.6.30, so you do not need to use --ignore-platform-reqs.

**Comment by michabbb** [comment]
@Seldaek my problem still is: when I don't use ignore-platform-reqs I get errors that php extensions are missing, which is totally correct. Because the docker composer container is build as simple as possible., so that I can use it for all my projects/containers. 

And again: even this would work without ignore-platform-reqs, I don't understand why I get dev-master instead of 5.x because the composer.json of laravie wants this very explicitly.

**Comment by stof** [comment]
@micaherne the `platform` config also allows you to specify available extensions.

And `"^5.1"` as constraint allows to install 5.5.x-dev. And illuminate/support dev-master has a branch alias to say that it is 5.5.x-dev. So installing it to fulfill the laravie/parser requirement is perfectly fine.

**Comment by stof** [comment]
btw, running composer as a different container than your PHP runtime looks like a weird setup to me, as it kills any platform check.

**Comment by michabbb** [comment]
@stof first of all: it wasn´t my idea to implement the parameter `ignore-platform-reqs` - and next to this: it makes sense, either [this project](https://github.com/composer/docker) wouldn´t exist.

but you bring something new into this whole thing, called "alias" and i never used that before (no need to)...  so if i understand your info about the alias correct, does it work like this:

`^5.1 means >=5.1.0,<6.0.0`

so because there exists an alias called `5.5-dev` which leads to `dev-master` i get `dev-master` because....
and this is the magic question for me:

- because i used `ignore-platform-reqs` and composer searches for something that is compatible with php7  (because thats the php version inside the composer docker container) and ignores my `platform` infos in my composer.json ?
- because i didn´t use `prefer-stable` (i already tested this)

so how should my composer.json look like, that it works with php7 correctly (ignores missing php-ext) and takes care of my dev env with php 5,6.30 where all the php-ext are installed???

`ignore-platform-reqs` seems to ignore the `platform` part inside the composer.jon.

to all: thanks for your help and patience, seems like a hard composer lession to learn for me......

**Comment by Seldaek** [comment]
In short. Use this:

```
{
  "config": {
    "platform": {
      "php": "5.6.30",
      "ext-mbstring": "5.6.30"
    }
  }
}
```

Add other extensions if they are missing, this should represent all that is in your production/dev env, so that the composer container can install fine, and then stop using `--ignore-platform-reqs`.

**Comment by michabbb** [comment]
@Seldaek ok will test it, many thanks ! but can you tell me if [my analysis](https://github.com/composer/composer/issues/6593#issuecomment-321037477) is correct why i get `dev-master` , because i really want to understand this ;)

**Comment by michabbb** [comment]
@Seldaek i also have a concept problem with "platform". the composer.json is inside my git repo.
on my production i don´t want to fake anything, but for my dev env i need to - so how is that working ? do i need two different composer.json versions ? one for dev one for prod ?

**Comment by Seldaek** [comment]
> because i used ignore-platform-reqs and composer searches for something that is compatible with php7 (because thats the php version inside the composer docker container) and ignores my platform infos in my composer.json ?

No, it ignores all platform requirements, and platform config. It doesn't look for something compatible with php7, it just doesn't care about php versions anymore, so you get the highest available version.

> because i didn´t use prefer-stable (i already tested this)

In this case yes using prefer-stable would fix it, but if there was a stable release e.g. 5.5.0 which required php7, even with prefer-stable it would install it if you ignore platform requirements.

**Comment by Seldaek** [comment]
The platform config should match what php/extension/.. versions you have running in production, otherwise you risk installing things in development that then will fail when deployed to production.

**Comment by michabbb** [comment]
@Seldaek many thanks for your patience, i guess i can now fit all pieces of this puzzle together, holy crap ! ;-)

**Comment by michabbb** [comment]
@Seldaek okay, the composer docker container with php7 is working as expacted when i use:

```
"platform": {
      "php": "5.6.24",
      "ext-soap"   : "5.6.24",
      "ext-mysqli" : "5.6.24"
    }
```
so using `ignore-platform-reqs` is indeed a very bad solution when dealing with different types of php versions.... ;/

**Comment by Seldaek** [comment]
It's just the nuclear option.. It helps sometimes to get stuff installed no matter what, but it's not really recommended for daily use.

**Comment by humaneguy** [comment]
Currently facing this issue in Composer 2. I had to use this config:

```php
"config": {
  "platform": {
        "php": "7.3",
        "ext-mbstring": "7.3.30",
        "ext-soap": "7.3.30"
   }
}
```
