### ISSUE TITLE
Fatal error after composer upgrade

### ISSUE THREAD

**Issue by edhgoose** [composer/composer#6594]
Apologies for brevity, but it looks like the latest release has caused a problem @Seldaek 

```
PHP Fatal error:  Uncaught Error: Class 'Composer\Factory' not found in phar:///usr/local/bin/composer/bin/composer:16
Stack trace:
#0 /usr/local/bin/composer(24): require()
#1 {main}
  thrown in phar:///usr/local/bin/composer/bin/composer on line 16
```

**Comment by Seldaek** [comment]
Yup sorry I pushed out a corrupt phar accidentally. Fixed it very quickly but unfortunately it was completely borked, so you can't rollback to an older release using the phar.. Please re-install using instructions at https://getcomposer.org/download/

**Comment by PapsOu** [comment]
@Seldaek 

This issue is appearing again with composer `1.6.0` and `1.6.1`. `1.6.0-RC` seams to work correctly.

```
./composer.phar -v    
PHP Fatal error:  Uncaught Error: Class 'Composer\Factory' not found in phar:///home/PapsOu/Softwares/composer/composer.phar/bin/composer:16
Stack trace:
#0 /home/PapsOu/Softwares/composer/composer.phar(24): require()
#1 {main}
  thrown in phar:///home/PapsOu/Softwares/composer/composer.phar/bin/composer on line 16
```

**Comment by xabbuh** [comment]
@PapsOu see #6977
