### ISSUE TITLE
can composer replace existing package with custom one?

### ISSUE THREAD

**Issue by videni** [composer/composer#6596]
Let's assume there is a project that requires:  
```
"vendor/package1": "^1.0",
"vendor/package2": "^1.0"
```
the `vendor/package1`  requires
```
"vendor/another-package1": "^1.0"
```
I fork the  "vendor/another-package1" ,  create a branch  `bugfix`,  now there are two repoes for the package ,  I need the `example/package1` to use my `bugfix` branch without change its constraint , how can I do this?

**Comment by kenorb** [comment]
Yes, you can use [`replace`](https://getcomposer.org/doc/04-schema.md#replace) with `self.version`. See: [How to override a requirement globally for `composer.json`?](https://stackoverflow.com/q/43536516/55075)

**Comment by stof** [comment]
if you fork the package temporarily, you should not rename the package itself (and you should not register your fork on Packagist)

What you should do is use inline aliases: https://getcomposer.org/doc/articles/aliases.md#require-inline-alias
