### ISSUE TITLE
ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by Shkarbatov** [composer/composer#6597]
Hello, I need help :)

I use ubuntu 16.04, trying to update composer and receive an error:
                                                                                                                                  
```
$ php composer.phar self-update

[Composer\Downloader\TransportException]                                                                                        
The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:  
error:1408F10B:SSL routines:ssl3_get_record:wrong version number                                                                
failed to open stream: Cannot connect to HTTPS server through proxy                                                             

```
**This is what I have in php:**
```
$ php -i | grep -i openssl
SSL Version => OpenSSL/1.0.2g
openssl
OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.1.0f  25 May 2017
OpenSSL Header Version => OpenSSL 1.1.0f  25 May 2017
Openssl default config => /usr/lib/ssl/openssl.cnf
openssl.cafile => no value => no value
openssl.capath => no value => no value
Native OpenSSL support => enabled
```

Whats wrong?

**Comment by Shkarbatov** [comment]
This is my problem:
export http_proxy="http://login:pass@proxy:8080"

**Comment by carbonellcarlos** [comment]
I have the same problem on Ubuntu 18.04 and http_proxy didn't solve the problem. It worked fine on debian stretch and windows 10 though, but not in Ubuntu 18.04. What's wrong?

**Comment by semae** [comment]
> I have the same problem on Ubuntu 18.04 and http_proxy didn't solve the problem. It worked fine on debian stretch and windows 10 though, but not in Ubuntu 18.04. What's wrong?

Same problem here, but I'm using it inside a docker ubuntu image

**Comment by saktib** [comment]
Ubuntu 18.04 Fix: pass --disable-tls for composer-setup.php
#
# Install composer
#
RUN wget -O ./composer-setup.php  https://getcomposer.org/installer
RUN php ./composer-setup.php **--disable-tls** --install-dir=bin --filename=composer

**Comment by stof** [comment]
`--disable-tls` is not a fix. It is a workaround for non-working TLS, but that's downgrading to insecure connection.

@Shkarbatov something looks weird in your `php -i` output: you have 2 different openssl version in there (`1.0.2g` and `1.1.0f`). This might be related to the error saying `wrong version number`.
