### ISSUE TITLE
Why this message

### ISSUE THREAD

**Issue by m-alam** [composer/composer#6600]
- Installing nesbot/carbon (1.22.1): Loading from cache
  - Installing mtdowling/cron-expression (v1.2.0): Loading from cache
  - Installing monolog/monolog (1.23.0): Loading from cache
  - Installing league/flysystem (1.0.41): Loading from cache
  - Installing erusev/parsedown (1.6.3): Loading from cache
  - Installing laravel/framework (v5.4.32): Downloading (100%)

  [ErrorException]
  copy(C:/Users/mahabub/AppData/Local/Composer/files/laravel/framework/a930c8846cb61d1c653c469994844b70666604b7.zip):
   failed to open stream: Invalid argument

**Comment by curry684** [comment]
If you run `php -i` (lots of output), do the entries for "Registered PHP Streams" include `compress.zlib` and/or `zip`?

Does `php -m` list `zip` and/or `zlib` under "PHP Modules"?

**Comment by Seldaek** [comment]
Automatically closing as this has not received any updates in a while. Please re-open if it is still relevant.
