### ISSUE TITLE
Installing Composer via git clone - what to do after cloning?

### ISSUE THREAD

**Issue by Glthubnoob** [composer/composer#6607]
Hi everyone,
I tried to install Composer with

> git clone https://github.com/composer/composer.git < 
I was able to clone the directory into my home: ~/composer
But what do I have to do next, as there is no README concerning installation steps file or any install.sh 

Can you help me what I have to do next? Thx.
Jonathan

**Comment by curry684** [comment]
If you're asking this question you are using the wrong install method. Follow https://getcomposer.org/download/ instead.

**Comment by OnkelTem** [comment]
@Glthubnoob Might help: https://github.com/composer/composer/issues/6603#issuecomment-322146998

**Comment by curry684** [comment]
No, that answer is definitely not relevant. Please ignore it and use the installer as advised.
