### ISSUE TITLE
content-hash seems not updating

### ISSUE THREAD

**Issue by webmake** [composer/composer#6609]
My current Composer version 1.5.1.
Everytime I run `composer update x/package`, not updating hash or even `composer update`, so running `composer validate` it gives
```
./composer.json is valid
The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update`.
```
So only `composer update --lock` fixed the problem

I'm not sure which change broken this feature, because with previous (maybe 1.4) I hadn't such troubles

**Comment by alcohol** [comment]
Can you provide a reproducible scenario please. Because your explanation is lacking in sufficient details for us to provide any meaningful assistance.

**Comment by webmake** [comment]
I guess that is occuring when I change json file, You can reproduce with laravel/framework and some modules. Here is the output

$ cat composer.lock | grep content-hash
7:    "content-hash": "ad6ce57ea500c53ae0e672c51605aec7",

$ composer validate
./composer.json is valid

$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 7 updates, 0 removals
  - Updating doctrine/inflector (v1.2.0 => v1.1.0): Loading from cache
  - Updating laravel/framework (v5.4.30 => v5.4.32): Loading from cache
  - Updating bugsnag/bugsnag (v3.5.1 => v3.6.0): Loading from cache
  - Updating bugsnag/bugsnag-laravel (v2.6.0 => v2.7.0): Loading from cache
  - Updating nwidart/laravel-modules (1.26.0 => 1.27.1): Loading from cache
  - Updating watson/bootstrap-form (1.1.8 => 1.1.10): Loading from cache
  - Updating yajra/laravel-datatables-oracle (v7.9.3 => v7.9.9): Loading from cache
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
...

$ cat composer.lock | grep content-hash
7:    "content-hash": "ad6ce57ea500c53ae0e672c51605aec7",

as you can see even writin message was in output, but content-hash is still unchanged.
More over, I lift in composer.json from ^2.6 `"bugsnag/bugsnag-laravel": "^2.7"` version, so here comes interesting part:
$ composer validate
./composer.json is valid
The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update`.

I guess hash should be created from lock, not json, am I wrong?

**Comment by alcohol** [comment]
`content-hash` is based on content of `composer.json`.

**Comment by webmake** [comment]
But version actually didn't changed as you can see (2.7), I didn't understood why `hash` was completely replaced by `content-hash` it is other purpose, because 3rd parties updates are not visible in composer.json. So they should work in tandem to speed up any process

**Comment by alcohol** [comment]
`hash` was deprecated. I still do not understand your problem, and I am not able to reproduce it.

**Comment by webmake** [comment]
Let's say you have in composer.json "bugsnag/bugsnag-laravel": "^2.6" and in lock it is as 2.6version. So after composer update this version in lock it upgrades up to 2.7, so it is safe to update in json also 2.7, but it now gives after `composer validate` in big red letters
`The lock file is not up to date with the latest changes in composer.json, it is recommended that you run composer update.`

**Comment by alcohol** [comment]
That is because you updated the composer.json after running `composer update`. The `content-hash`  value is calculated based on the actual content of `requirements` and a few other attributes. If you change your requirements without also updating your lock file again, composer will complain that your composer.json and lock file are out of sync, because they are.

**Comment by webmake** [comment]
Requirements also consists from lock (snapshot of working bunch of other dependencies). Main idea was, that installed version (2.7) is the same as 2.6 lifted upto 2.7 manually, and shouldn't require re-run `composer update --lock`. Lock file is the fact how environment should be setup, and run only `composer install`. Otherwise lock is not neccesary in such approach if doesn't care 2.7actual version.

**Comment by alcohol** [comment]
Ok, you are entitled to your own opinion, but that just is not how things work.
Anyway, original question was answered.
