### ISSUE TITLE
No composer uninstall option available.  Please add one.

### ISSUE THREAD

**Issue by amolochitis** [composer/composer#6611]
If I want to uninstall composer, there is not an uninstall procedure available.  Please add one.

**Comment by derrabus** [comment]
Composer is a single executable file. Simply delete it.

**Comment by amolochitis** [comment]
Removing composer.phar is the uninstall process?

**Comment by derrabus** [comment]
Yes.

**Comment by curry684** [comment]
You likely also want to `rm -rf $HOME/.composer` with all the caches and indexes, but yes, that's the complete uninstall procedure in itself.

I expect however that you're talking about the Windows installer based version, which to my knowledge has a fine uninstaller available via "Add/remove Programs" in the control panel?

**Comment by alcohol** [comment]
Yes it would help if you specified what your operating system is. The uninstall procedure for each varies.

**Comment by amolochitis** [comment]
Centos 6 and 7

**Comment by Jean85** [comment]
Then removing the phar is enough. Deleting the cache in your home folder is for full purge.
