### ISSUE TITLE
Composer ext and lib list

### ISSUE THREAD

**Issue by decadence** [composer/composer#6616]
Hello.
Where can I find full list of Composer require ext- and lib- options?
I don't quite understand how to detect if php extension is ext or lib.

**Comment by staabm** [comment]
Lib is everything you find e.g on packagist (php based libraries/frameworks); ext is something which gets loaded via the php extension mechanics (usually implemented in C)

**Comment by decadence** [comment]
Wrong. From doc:
lib-<name> allows constraints to be made on versions of libraries used by PHP. The following are available: curl, iconv, icu, libxml, openssl, pcre, uuid, xsl

So lib is something that belongs to PHP and not to packagist.

**Comment by decadence** [comment]
Ok, lib has own list in doc. But in PHP doc they are extensions.

**Comment by staabm** [comment]
Ahh mixed lib with packages up...

**Comment by decadence** [comment]
I think curl, iconv, icu, libxml, openssl, pcre, uuid, xsl are lib-, other extensions are ext-.
Exact names can be retrieved by run `composer show --platform`.
