### ISSUE TITLE
Different behaviour of `composer create-project` (1.4 -> 1.5)

### ISSUE THREAD

**Issue by mwjames** [composer/composer#6617]
## Issue
The following command `composer create-project ...` no longer creates expected results after Travis uses "Updating to version 1.5.1 (stable channel)."

Updating to version 1.4.3 (stable channel) produced [0]:

```
cd /home/travis/build/SemanticMediaWiki/SemanticMediaWiki/../mw/extensions
composer create-project mediawiki/semantic-media-wiki SemanticMediaWiki dev-master -s dev --prefer-dist --no-dev
Installing mediawiki/semantic-media-wiki (dev-master ec5abd96805466e99c4e42205e2d83c9124587e1)
  - Installing mediawiki/semantic-media-wiki (dev-master master): Downloading (100%)
...
```

Updating to version 1.5.1 (stable channel) now produces [1]:

```
cd /home/travis/build/SemanticMediaWiki/SemanticMediaWiki/../mw/extensions
composer create-project mediawiki/semantic-media-wiki SemanticMediaWiki dev-master -s dev --prefer-dist --no-dev

No composer.json in current directory, do you want to use the one at /home/travis/build/SemanticMediaWiki/mw? [Y,n]? 
```

No changes to the Travis setup, directory, or composer.json were applied.

[0] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/261701383
[1] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/265581327

**Comment by hswong3i** [comment]
My build https://travis-ci.org/drustack/drustack-standard/jobs/266495624 also failed due to waiting for a Y confirmation...

**Comment by alcohol** [comment]
You did not specify `--no-interaction`.

**Comment by Seldaek** [comment]
You indeed should use --no-interaction when writing scripts, but also create-project really should not look for a composer.json in a parent dir, that was an oversight.
