### ISSUE TITLE
composer update: truncated output

### ISSUE THREAD

**Issue by simonschaufi** [composer/composer#6619]
My `composer.json`:

```json
{
"require": "symfony/process"
}
```

Output of `composer diagnose`:

```
```

When I run this command:

```
composer update
```

I get the following output:

```
Loading composer repositorUpdating dependencies (including require-dev)
```

And I expected this to happen:
either:
```
Loading composer repository
Updating dependencies (including require-dev)
```
or
(Loading composer repository is not visible any more)
```
Updating dependencies (including require-dev)
```

System Environment: Ubuntu but in Git Bash It's the same.
Composer Version: 1.5.1 2017-08-09 16:07:22

**Comment by alcohol** [comment]
Cannot reproduce. Need more information.

**Comment by simonschaufi** [comment]
This is the output on git bash on another composer project:
```
$ composer update
Loading composer repositories with package information
```
after some seconds, it will be:
```
$ composer update
Loading composer repositorReading composer.json of xxx/xxx (v1.0.0)
```
As you can see, the first part "Loading composer repositor" is never replaced.

**Comment by simonschaufi** [comment]
I think it has to do with the window size. If I make the putty window bigger, there is no overlapping.
Anyway, the text should start on the new line and not somewhere on the right.

**Comment by Seldaek** [comment]
Sounds like perhaps duplicate of #6520 although that one is only phpstorm.. This one also only happens with custom vcs repositories though, which use the ConsoleIO overwrite method to output text over the previous line.. Maybe that fails when the lines wrap or something?

**Comment by simonschaufi** [comment]
Ah yes, I'm also using own repository section. I didn't mention that in the beginning. I just see that it's not a problem of composer. It will probably come from a composer installer plugin. I will dig deeper but close the issue for now as I don't see the problem directly in composer.
