### ISSUE TITLE
--install-suggests doesn't exists

### ISSUE THREAD

**Issue by ShurikAg** [composer/composer#662]
Hi we used to use composer with the option --install-suggests.

At some point the option stopped been available:

if I run:

 ./composer.phar update --install-suggests

I get an error message:

[RuntimeException]
  The "--install-suggests" option does
   not exist.

update [--prefer-source] [--dry-run] [--dev]

is this option still available?

**Comment by FractalizeR** [comment]
It would be good to be able to install / remove suggested packages without modifying composer.json
