### ISSUE TITLE
Composer picks wrong version of dependency

### ISSUE THREAD

**Issue by silid** [composer/composer#6628]
When I run this command:

```
composer create-project melonsmasher/chocolatier
```

I get the following output:

```
Installing melonsmasher/chocolatier (v0.1.7)
  - Installing melonsmasher/chocolatier (v0.1.7): Downloading (100%)
Created project in /var/www/website/html/chocolatier
> php -r "copy('.env.example', '.env');"
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/instantiator 1.1.0 -> satisfiable by doctrine/instantiator[1.1.0].
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
  Problem 2
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
    - phpunit/phpunit-mock-objects 3.4.4 requires doctrine/instantiator ^1.0.2 -> satisfiable by doctrine/instantiator[1.1.0].
    - Installation request for phpunit/phpunit-mock-objects 3.4.4 -> satisfiable by phpunit/phpunit-mock-objects[3.4.4].
```

And I expected this to happen:
Composer should install doctrine/instantiator 1.0.5 which meets the dependencies and is compatible with PHP 7.0

**Comment by alcaeus** [comment]
I thought something was odd, so I tried this:
```
$ php -v
PHP 7.0.22 (cli) (built: Aug  7 2017 14:07:27) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

alcaeus at vulcan in ~/Code/alcaeus/testbed/composer/require-stuff on master [*]
$ composer require phpunit/phpunit-mock-objects 3.4.4
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 5 installs, 0 updates, 0 removals
  - Installing sebastian/recursion-context (2.0.0): Loading from cache
  - Installing sebastian/exporter (2.0.0): Loading from cache
  - Installing doctrine/instantiator (1.0.5): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (3.4.4): Loading from cache
Writing lock file
Generating autoload files
```

As you can see, requiring the package that apparently caused the error (phpunit-mock-objects) works fine. So, what's the reason? The project you're using in `create-project` contains a `composer.lock` which was created on PHP 7.1 and thus contains a requirement to `doctrine/instantiator` 1.1.0: https://github.com/MelonSmasher/Chocolatier/blob/10f8cf71872a217930d90d4bd6ce9f9e942090aa/composer.lock#L2315..L2316. So, after calling `create-project`, composer will try to install the dependencies marked in the `composer.lock` file and fail due to the PHP requirement.

**Comment by silid** [comment]
Thanks for your help. Does create-project have a flag that forces an update before installing dependencies, or otherwise compensates for the upstream project - or is the best fix to keep lock files out of public repos?

**Comment by alcaeus** [comment]
FWIW, I tried removing `composer.lock` and reinstalling dependencies to get a fresh set, which didn't work. There's definitely something fancy with the project.

Regardless of whether `composer.lock` should be in a public repo or not (there are valid arguments for and against), if it is there it should always be generated on the lowest requirement, so in this case on PHP 7, not 7.1.

**Comment by silid** [comment]
Thanks.
