### ISSUE TITLE
composer.lock is missing "support" property

### ISSUE THREAD

**Issue by X-Coder** [composer/composer#6633]
Hi,

I wondered why the composer.lock file seems to include all [properties ](https://getcomposer.org/doc/04-schema.md#properties)of the composer.json schema except the [support](https://getcomposer.org/doc/04-schema.md#support) property. At least in version Composer version <=1.5.1.

I need this support property because I want to parse the lockfile and list all installed packages in some GUI in my project. I could use all vendor/*/composer.json files for this, but this feels wrong and I think just this missing property in the lockfile is a bug.

Some example [composer.json](https://github.com/ckeditor/ckeditor-releases/blob/master/composer.json) which has no support property in lockfile.

**Comment by stof** [comment]
Well, the composer.lock file will contain the support info when Composer has it.

But Packagist is dropping this info from metadata sent to Composer: https://github.com/composer/packagist/issues/787. So this is an issue on Packagist side.

If you use a VCS repository to get the metadata of a package, the lock file will have the support info

**Comment by X-Coder** [comment]
Thanks, I wish Packagist would here be more consistent, as it makes no sense exclude this property, but include everything else.

**Comment by stof** [comment]
well, many other properties are necessary for Composer to work. Support is just here to be displayed.

But I agree it would be fine to have this. I was the one reporting the issue to Packagist.

I suggest you to close this issue in favor of the Packagist one though (there is nothing to fix in composer itself)
