### ISSUE TITLE
Composer config --unset homepage breaks composer.json syntax

### ISSUE THREAD

**Issue by pmatias** [composer/composer#6636]
On a regular `composer.json` file, run:

`composer config homepage https://www.myurl.com/`

The `homepage` variable will be added at the **bottom** of the `composer.json` file:
```
          [...]
           }
        }
    },
    "homepage": "https://www.myurl.com/"
}
```
Whereas any other variable I set (`description`, `license`, etc) will be set at the **top** of the file.

Now, if I try to unset the `homepage` variable:
`composer config --unset homepage`

The resulting `composer.json` file will be:
```
           [...]
          }
        }
    },
    }
```

As you can see, it removed the line, but not the extra comma and curly braces.

Now, if I try to set any other variable:
`composer config description 'A Description' `

it will result in:
```
[Seld\JsonLint\ParsingException]
  "./composer.json" does not contain valid JSON
  Parse error on line 102:
  ...       }    },    }
  --------------------^
  Expected: 'STRING' - It appears you have an extra trailing comma
```

I've been browsing around opened/closed issues and found nothing related, so I apologise in advance if there's another issue already opened/solved about this and didn't see it, and greatly appreciate it if you can point me to that issue number.

I'm using composer `1.5.1`, by the way.

**Comment by jkribeiro** [comment]
I noticed the same issue on my end.

**Comment by Deamon** [comment]
Hey, 
i manage to reproduce the bug of the last coma and propose a small fix.

But I couldn't reproduce the fact that `description` or `license` go to the beginning of the file. 
Every time I tried to add them they go to the end of the file.

**Comment by jkribeiro** [comment]
I'm using Composer `1.5.6`, this issue is not happening anymore, I think we can close this issue.

**Comment by pmatias** [comment]
I can confirm the same thing, using `1.5.6`
