### ISSUE TITLE
Rejected by your constraint

### ISSUE THREAD

**Issue by NesooseN** [composer/composer#6638]
My `composer.json`:

```json
{
    "name": "magento/updater",
    "description": "Magento Updater",
    "type": "project",
    "version": "10.0.4",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "require": {
        "php": "~5.5.0|~5.6.0|~7.0.0",
        "composer/composer": "1.0.0-beta1",
        "magento/composer": "~1.0.0",
        "symfony/console": "~2.3 <2.7",
        "monolog/monolog": "1.16.0",
        "psr/log": "~1.0",
        "minimum-stability": "dev"
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0"
    },
    "autoload": {
        "psr-4": {
            "Magento\\": "app/code/Magento/"
        }
    }
}
```

Output of `composer diagnose`:

```

Checking composer.json: FAIL
The version field is present, it is recommended to leave it out if the package is published on Packagist.
Defining autoload.psr-0 with an empty namespace prefix is a bad idea for performance
require.magento/product-community-edition : exact version constraints (2.0.17) should be avoided if the package follows semantic versioning
require.composer/composer : unbound version constraints (@alpha) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: Warning: Accessing packagist.org over http which is an insecure protocol.
OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: FAIL
You are not running the latest stable version, run `composer self-update` to update (1.1.1 => 1.5.1)

```

When I run this command:

```
composer update
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/product-community-edition 2.0.18 exists as magento/product-community-edition[2.1.6, 0.42.0-beta7, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.1.0-rc1, 2.1.0-rc2, 2.1.0-rc3, 2.1.0, 2.0.8, 2.0.9, 2.1.1, 2.0.10, 2.1.2, 2.1.3, 2.0.11, 2.1.4, 2.0.12, 2.1.5, 2.0.13, 2.1.7, 2.0.14, 2.0.15, 2.1.8, 2.2.0-rc20, 2.2.0-rc21, 2.2.0-rc22] but these are rejected by your constraint.

```

And I expected this to happen: to start update from 2.1.16 to 2.1.8

What is problem ?

**Comment by Deamon** [comment]
isn't this related to #6639?

**Comment by NesooseN** [comment]
More details:

composer depends magento/product-community-edition
magento/project-community-edition  2.1.6  requires  magento/product-community-edition (2.0.18)

`composer show magento/product-community-edition
name     : magento/product-community-edition
descrip. : eCommerce Platform for Growth (Community Edition)
keywords :
versions : * 2.1.6
type     : metapackage
license  : Open Software License 3.0 (OSL-3.0) (OSI approved) https://spdx.org/licenses/OSL-3.0.html#licenseText
license  : Academic Free License v3.0 (AFL-3.0) (OSI approved) https://spdx.org/licenses/AFL-3.0.html#licenseText
source   : []
dist     : [zip] https://repo.magento.com/archives/magento/product-community-edition/magento-product-community-edition-2.1.6.0.zip
names    : magento/product-community-edition

requires
braintree/braintree_php 3.7.0
colinmollenhour/cache-backend-file 1.4
colinmollenhour/cache-backend-redis 1.9
colinmollenhour/credis 1.6
colinmollenhour/php-redis-session-abstract 1.2
composer/composer <=1.0.0-beta1
ext-ctype *
ext-curl *
ext-dom *
ext-gd *
ext-hash *
ext-iconv *
ext-intl *
ext-mbstring *
ext-mcrypt *
ext-openssl *
ext-simplexml *
ext-spl *
ext-xsl *
ext-zip *
lib-libxml *
magento/composer ~1.0.0
magento/framework 100.1.6
magento/language-de_de 100.1.1
magento/language-en_us 100.1.1
magento/language-es_es 100.1.1
magento/language-fr_fr 100.1.1
magento/language-nl_nl 100.1.1
magento/language-pt_br 100.1.1
magento/language-zh_hans_cn 100.1.1
magento/magento-composer-installer *
magento/magento2-base 2.1.6
magento/module-admin-notification 100.1.2
magento/module-advanced-pricing-import-export 100.1.2
magento/module-authorization 100.1.2
magento/module-authorizenet 100.1.4
magento/module-backend 100.1.3
magento/module-backup 100.1.2
magento/module-braintree 100.1.5
magento/module-bundle 100.1.2
magento/module-bundle-import-export 100.1.3
magento/module-cache-invalidate 100.1.3
magento/module-captcha 100.1.3
magento/module-catalog 101.0.6
magento/module-catalog-import-export 100.1.4
magento/module-catalog-inventory 100.1.5
magento/module-catalog-rule 100.1.4
magento/module-catalog-rule-configurable 100.1.3
magento/module-catalog-search 100.1.5
magento/module-catalog-url-rewrite 100.1.3
magento/module-catalog-widget 100.1.2
magento/module-checkout 100.1.5
magento/module-checkout-agreements 100.1.2
magento/module-cms 101.0.4
magento/module-cms-url-rewrite 100.1.2
magento/module-config 100.1.4
magento/module-configurable-import-export 100.1.2
magento/module-configurable-product 100.1.6
magento/module-contact 100.1.3
magento/module-cookie 100.1.2
magento/module-cron 100.1.3
magento/module-currency-symbol 100.1.2
magento/module-customer 100.1.5
magento/module-customer-import-export 100.1.2
magento/module-deploy 100.1.5
magento/module-developer 100.1.3
magento/module-dhl 100.1.3
magento/module-directory 100.1.3
magento/module-downloadable 100.1.2
magento/module-downloadable-import-export 100.1.2
magento/module-eav 100.1.5
magento/module-email 100.1.3
magento/module-encryption-key 100.1.2
magento/module-fedex 100.1.3
magento/module-gift-message 100.1.3
magento/module-google-adwords 100.1.2
magento/module-google-analytics 100.1.2
magento/module-google-optimizer 100.1.2
magento/module-grouped-import-export 100.1.2
magento/module-grouped-product 100.1.3
magento/module-import-export 100.1.4
magento/module-indexer 100.1.3
magento/module-integration 100.1.3
magento/module-layered-navigation 100.1.2
magento/module-marketplace 100.1.2
magento/module-media-storage 100.1.2
magento/module-msrp 100.1.3
magento/module-multishipping 100.1.2
magento/module-new-relic-reporting 100.1.3
magento/module-newsletter 100.1.2
magento/module-offline-payments 100.1.2
magento/module-offline-shipping 100.1.3
magento/module-page-cache 100.1.3
magento/module-payment 100.1.5
magento/module-paypal 100.1.4
magento/module-persistent 100.1.3
magento/module-product-alert 100.1.3
magento/module-product-video 100.1.4
magento/module-quote 100.1.4
magento/module-reports 100.1.3
magento/module-require-js 100.1.3
magento/module-review 100.1.2
magento/module-rss 100.1.2
magento/module-rule 100.1.3
magento/module-sales 100.1.5
magento/module-sales-inventory 100.1.1
magento/module-sales-rule 100.1.3
magento/module-sales-sequence 100.1.3
magento/module-sample-data 100.1.3
magento/module-search 100.1.2
magento/module-security 100.1.3
magento/module-send-friend 100.1.2
magento/module-shipping 100.1.3
magento/module-sitemap 100.1.3
magento/module-store 100.1.5
magento/module-swagger 100.1.2
magento/module-swatches 100.1.5
magento/module-swatches-layered-navigation 100.1.2
magento/module-tax 100.1.2
magento/module-tax-import-export 100.1.2
magento/module-theme 100.1.4
magento/module-translation 100.1.3
magento/module-ui 100.1.4
magento/module-ups 100.1.3
magento/module-url-rewrite 100.1.2
magento/module-user 100.1.3
magento/module-usps 100.1.3
magento/module-variable 100.1.2
magento/module-vault 100.2.1
magento/module-version 100.1.2
magento/module-webapi 100.1.2
magento/module-webapi-security 100.1.2
magento/module-weee 100.1.2
magento/module-widget 100.1.2
magento/module-wishlist 100.1.4
magento/theme-adminhtml-backend 100.1.2
magento/theme-frontend-blank 100.1.4
magento/theme-frontend-luma 100.1.5
magento/zendframework1 ~1.12.16
monolog/monolog 1.16.0
oyejorge/less.php ~1.7.0
pelago/emogrifier 0.1.1
php ~5.6.5|7.0.2|7.0.4|~7.0.6
phpseclib/phpseclib 2.0.*
sjparkinson/static-review ~4.1
symfony/console ~2.3 <2.7
symfony/event-dispatcher ~2.1
symfony/process ~2.1
tedivm/jshrink ~1.0.1
tubalmartin/cssmin 2.4.8-p4
zendframework/zend-code ~2.4.6
zendframework/zend-config ~2.4.6
zendframework/zend-console ~2.4.6
zendframework/zend-crypt ~2.4.6
zendframework/zend-di ~2.4.6
zendframework/zend-eventmanager ~2.4.6
zendframework/zend-form ~2.4.6
zendframework/zend-http ~2.4.6
zendframework/zend-i18n ~2.4.6
zendframework/zend-json ~2.4.6
zendframework/zend-log ~2.4.6
zendframework/zend-modulemanager ~2.4.6
zendframework/zend-mvc ~2.4.6
zendframework/zend-serializer ~2.4.6
zendframework/zend-server ~2.4.6
zendframework/zend-servicemanager ~2.4.6
zendframework/zend-soap ~2.4.6
zendframework/zend-stdlib ~2.4.6
zendframework/zend-text ~2.4.6
zendframework/zend-uri ~2.4.6
zendframework/zend-validator ~2.4.6
zendframework/zend-view ~2.4.6
`

**Comment by Seldaek** [comment]
Automatically closing as this has not received any updates in a while. Please re-open if it is still relevant.

**Comment by miracode2033** [comment]
HERE'S MY PROBLEM
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/project-community-edition 2.2.6-dev exists as magento/project-community-edition[0.1.0-alpha100, 0.1.0-alpha101, 0.1.0-alpha102, 0.1.0-alpha103, 0.1.0-alpha104, 0.1.0-alpha105, 0.1.0-alpha106, 0.1.0-alpha107, 0.1.0-alpha108, 0.1.0-alpha89, 0.1.0-alpha90, 0.1.0-alpha91, 0.1.0-alpha92, 0.1.0-alpha93, 0.1.0-alpha94, 0.1.0-alpha95, 0.1.0-alpha96, 0.1.0-alpha97, 0.1.0-alpha98, 0.1.0-alpha99, 0.42.0-beta1, 0.42.0-beta10, 0.42.0-beta11, 0.42.0-beta2, 0.42.0-beta3, 0.42.0-beta4, 0.42.0-beta5, 0.42.0-beta6, 0.42.0-beta7, 0.42.0-beta8, 0.42.0-beta9, 0.74.0-beta1, 0.74.0-beta10, 0.74.0-beta11, 0.74.0-beta12, 0.74.0-beta13, 0.74.0-beta14, 0.74.0-beta15, 0.74.0-beta16, 0.74.0-beta2, 0.74.0-beta3, 0.74.0-beta4, 0.74.0-beta5, 0.74.0-beta6, 0.74.0-beta7, 0.74.0-beta8, 0.74.0-beta9, 1.0.0-beta, 2.0.0, 2.0.0-rc, 2.0.0-rc2, 2.0.1, 2.0.2, dev-master] but these are rejected by your constraint.
