### ISSUE TITLE
Composer 1.5 no longer reads branches from gitlab

### ISSUE THREAD

**Issue by Berdir** [composer/composer#6639]
I haven't fully tracked this down yet, but I have a custom gitlab server and I'm trying to add a package there baesd on a branch.

With composer 1.4, this works. With composer 1.5, it only finds tags.

It *could* be related to the fact that I have old branches that have no composer.json, with -vv, it reports exactly one branch with a warning about it not having a composer.json and then moves on to the next package.

```
Reading composer.json of package/provider (zol/local-access)
Skipped branch zol/local-access, no composer file
```

My `composer.json`:

```json
  "provider/package": "dev-develop",
```

Output of `composer diagnose`:

```
All OK except some warnings about packages with dev-master branch.
```

When I run this command:

```
composer update
```

I get the following output:

```
  Problem 1
    - The requested package provider/package dev-develop exists as provider/package[1.8.19, ...] but these are rejected by your constraint.

```

And I expected this to happen (and it happens with composer 1.4):

```
  - Updating provider/package (.... => dev-develop 3b3bdbb):  Checking out 3b3bdbb6c7

```

**Comment by Berdir** [comment]
I can confirm that deleting all old branches without a composer.json file seems to have fixed this, it works again *and* seems to be much faster now at doing it in 1.5.

**Comment by alcohol** [comment]
So, is this a bug or not..?

**Comment by Berdir** [comment]
IMHO it is a bug/regression, yes. It clearly worked in 1.4 and is broken in 1.5.

It's something you can work around *if* you figure out what the problem is and are in a position to being able to delete those old branches, but possibly that's not something you want to do.

**Comment by Seldaek** [comment]
With the merge of #6643 and other bugfixes in 1.5.1 can you please make sure whether this is still a problem with the latest snapshot (`composer self-update --snapshot`)?

And if so, please provide more infos on how to reproduce.

**Comment by Berdir** [comment]
Tried to reproduce this with a public package on gitlab.com but couldn't. Closing for now, thanks for the feedback.
