### ISSUE TITLE
Shared library

### ISSUE THREAD

**Issue by kingcrunch** [composer/composer#664]
I little idea on how to avoid, that every little PHP application/tool fetches their own vendor libraries into their own local folders, even if every application/tool uses the same depencies in the same version :) Its slightly inspired by Rubys RVM [1] (site is currently down, 

Instead of unpacking every vendor package in `vendor/` of the main package composer could unpack it for example in `~/.composer/packs`, like

```
~/.composer/packs/symfony/swiftmailer-bundle/2.1.0
```

And now I'm playing with links:

```
myProject/vendor => ~/.composer/projects/myName/myProject/1.0
~/.composer/projects/myName/myProject/1.0/symfony/switftmailer-bundle => ~/.composer/packs/symfony/swiftmailer-bundle/2.1.0
```

My prefered VCS is git, thus I'll try to explain some additions on top of this. Others should work similar
- Instead of installing a package directly into `packs/vendor/name/version` composer could install it in `refs/vendor/name/version/SHA` and `packs/vendor/name/version` links here. Once I want to update a pacakge it gets installed into `refs/vendor/name/version/otherSHA` and the links will be set here.
- Same for the application itself: `~/.composer/projects/myName/myProject/1.0` could link to `~/.composer/snapshots/myName/myProject/1.0/YYYYMMDDHHMMSS`. On update the packages will be installed into `myProject/1.0/YYYYMMDDHHMMSS` with the new date and time and at the very end it will reset the link to the new location

(The names like `packs`, or such are just symbolic of course)

The main beneft I had in mind. If two applications both required (for example) `myPackage-1.7` they would be linked to the same library. 
- Saves memory (ok, not expensive nowadays ;))
- Once I update a package everyone linking to it (in _this version_!) will interact with the updated one.
- If an application wants to update a package lets say from 1.7 to 1.8 and 1.8 already exists, it only needs to set the link there

Some nice side effects (which I hadn't in mind, when this idea comes up ;))
- The `vendor/`-folder will never be in an "incomplete"/broken state, because only if and only when everything is stable again, the link will be set to the new location
- Its easy to rollback a whole installation as long as the old installation exists (if one thought about implementing "rollback" ^^)
- Removing a package is like ignoring them ;)
- The `vendor/` within the application itself should look like before.

A `cleanup` could iterate over every `refs/` and `packs/` entry and look, if there is a link from `snapshots/` or `projects/`. If not, it could delete it.

This idea may be incomplete and may contain errors :) I hope it's at least intelligible

[1] https://rvm.io/

**Comment by sup-ham** [comment]
You can check this plugin https://github.com/sup-ham/php-share
