### ISSUE TITLE
Getting a windows exe to run from a linux machine

### ISSUE THREAD

**Issue by totomtornado** [composer/composer#6640]
Can someone point me to a general example of how to run an executable....
I seem to be connected fine to the other machine and can print the contents of folders and move around... BUT running the program I wish to run is not working.

I have looked everywhere.

I am running the php script on a raspberry pi with ubuntu mate.  I am trying to get the script to run an executable on a machine that is running windows 7.

Cheers if you can point me in the right direction.

**Comment by totomtornado** [comment]
Part of the puzzle seems to be openssh....

if I use putty and ssh into the windows machine, I can get to whereever I want.  However, if I use the seclib I can only go to a certain directory level... no deeper... Security feature?

So I moved my batch file to a place I can get to... A user folder within the OpenSSH directory.  Great.  But still from seclib I can not run the batch file.

Again, through putty I can run the batch file with no issues by just typing the name of the batch file and hitting enter but with seclib it says "/bin/sh: line 2: convert_to_mp4.bat: command not found"

Here is my code thus far:

`<?php
include '../../../../../home/travis/vendor/autoload.php';
    $ssh = new \phpseclib\Net\SSH2('192.168.127.73');

    if (!$ssh->login('pi', 'password123')) {
        exit('Login Failed');
   }

$deployment_script = "set -e" . PHP_EOL
	  . "cd Handbrake_Folder/IN/" . PHP_EOL
        . "convert_to_mp4.bat";

$ssh->exec(
    $deployment_script, function ($str) {
        echo $str;
        flush();
        ob_flush();
});
?>`

I know my include statement is a bit strange.  Part of this is not having a clear understanding of composer(the method I installed it).  Still... I do seem to be able to connect this way regardless.  I feel I could make the include better but the biggest issue is how to call the batch file... the proper command that is.

Any suggestions would be awesome.

**Comment by totomtornado** [comment]
Further testing with putty reveals I can run the script after logging in by going to the batch file folder and then entering the command:

`start convert_to_mp4.bat `

for some reason the space at the end needs to be there....
Again, seclib doesn't seem to recognize start as a command so not sure how to mimic this behavior.

so frustrating... is seclib able to start a batch file....????????
if not then I will need to think of a different approach.

**Comment by Deamon** [comment]
Hi,
can you point me how is composer related to your problem ?

**Comment by totomtornado** [comment]
I do not think composer is related but I am using my include statement in a strange way compared to all examples I have seen.  Still I seem to be able to access the library.

**Comment by totomtornado** [comment]
This library just did not seem to have the instructions I needed.  I am sure someone can get it to work but I could not...

I installed php's native ssh and it works great....
http://php.net/manual/en/book.ssh2.php

**Comment by alcohol** [comment]
I am sorry. But this really is not an issue related to Composer. We cannot provide support on this.
