### ISSUE TITLE
manage dev-tools in phar like phpunit, phpDocumentor

### ISSUE THREAD

**Issue by altair2010** [composer/composer#6641]
Is it possible to add a new feature to use composer to manage dev-tool ?

require-dev manage dev library, but some dev tool like phpunit or phpdocumentor must be keep in phar archive and not added into ClassLoader because their dependencies can be incompatible with projet one.

So in my mind...
> Packagiste can register phar file (not store it)
>
> Adding in composer.json something like
> "dev-tools": [ "phpunit", "phpDocumentor" ]
> 
> And after user composer to install library, dev library, and dev tool, i can use tool in scripts

**Comment by Seldaek** [comment]
Lots of discussion about this at #5390 but it's unlikely to happen really.
