### ISSUE TITLE
Alias `composer upgrade` with `composer update` (see apt-get, yarn, brew, etc)

### ISSUE THREAD

**Issue by inoas** [composer/composer#6649]
### Suggestion

Composer should more closely mimick `apt-get`, `brew`, `yarn` (and yum to some degree) etc. instead of `npm` in future.

All these package managers only upgrade libraries, executable etc, when you run upgrade. Update just updates the recipe database.

The difference in nomenclature is important. Running `composer install` vs `composer update` may feel to both do a "good thing" for newbies, but the difference is huge.

**Upgrading** sounds a lot more "dangerous" and "possibly destructive" which is IMHO the way to go, even if semver is respected by all participating/linked libraries/projects.

Upgrading is to newbies like "buying Windows 10" versus updating is "running Windows Update".

Updating sounds always good, upgrading makes you consider "do I really want to?", "what would the impact be. That's better IMHO, don't you think?

### What Happens

When I run this command:

```
composer upgrade
```

I get the following output:

```
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "upgrade" is not defined.   
```

### What should happen

And I expected this to happen:

Execute the code that `composer update` executes.

### BC change to composer 

* At some point `composer update` should be deprecated.
* At some point a warning should be shown that `update` will be removed in favour of `upgrade`.
* At some point running it should point you at "did you mean upgrade?"
* In very far future it should then be removed?

**Comment by alcohol** [comment]
My feedback:

`upgrade` can easily be added as an alias to `update`.
I see no immediate reason to deprecate `update`.
There is also `self-update` -- should this then be aliased as `self-upgrade`?

**Comment by inoas** [comment]
Strictly speaking self-update should be self-upgrade, yes. But there I do not see any need for deprecation, we can simply have both.

Then: This is no question - more an RFC/Feature Request.
Not deprecating means people will in all future of composer be able to run `composer update` and when doing so it should after deprecation say `You probably meant composer install, unless you wanted to install new packages not suggested by the vendors composer.lock file`  or similar.

**Comment by Seldaek** [comment]
I can perhaps see adding an alias to make it easier for people that use upgrade mechanically, but to be honest the distinction between update and upgrade seems very slim to me in terms of language. 

It has a different meaning in the apt-get context sure, but even yarn for example has no update per se, it only has upgrade. Composer only has update. Both of these do what the equivalent of apt-get update + upgrade do, except in one command.

I don't see the value in making everyone change by deprecating update. Perhaps to you upgrade has a stronger meaning, but it doesn't seem like a huge hurdle day-to-day given nobody complained about this until now.

**Comment by inoas** [comment]
If we alias it now, we can make (or not make) the decision to deprecate `update` later on.
If we ever deprecated `updated` we can later use it to update a repository/version store as `apt-get` and other package/dependency managers do?

And you don't see the wording difference? I know projects that use `*4.1.0` instead of `^4.1.0` because people accidentally run `composer update` cause they don't know any better - and the maintainers don't want to see things possibly breaking in minor version upgrades. Now while I don't support that decision, please consider aliasing upgrade so we can some time in far future have the option to deprecate `update`?

**Comment by inoas** [comment]
<3
