### ISSUE TITLE
Escaping of composer arguments

### ISSUE THREAD

**Issue by mplx** [composer/composer#6655]
A build pipeline in a project of mine occasionally fails running a `composer config` command. The problem is caused by a generated token I'm setting as password which might start with a dash sometimes so composer will take it as an option but not argument.

`composer config -g http-basic.<host> <user> <password>`

`composer config -g http-basic.some.host.com anyuser -PASSWORD`
...results in ` The "-P" option does not exist.`

I tried to escape the password argument but failed.

`composer config -g http-basic.some.host.com anyuser "-PASSWORD"`
...results in ` The "-P" option does not exist.`

`composer config -g http-basic.some.host.com anyuser '-PASSWORD'`
...results in ` The "-P" option does not exist.`

While it seems the escaping generally works...

`composer config -g http-basic.some.host.com "anyuser -PASSWORD"`
...results in ` Expected two arguments (username, password), got 1`

...everything starting with `-` is always threaded as option.

`composer config -g http-basic.some.host.com "-anyuser" "-PASSWORD"` 
...results in `The "-y" option does not exist.`

(Composer version 1.5.1 2017-08-09 16:07:22)

**Comment by alcohol** [comment]
This might be related to how the symfony component treats arguments. The following works just fine:

```
composer config -g -- http-basic.some.host.com anyuser -PASSWORD
```

**Comment by mplx** [comment]
Thanks!
