### ISSUE TITLE
Ubuntu 17.04 don't access getcomposer.org and packagist.org

### ISSUE THREAD

**Issue by viniciuseduardo** [composer/composer#6656]
Hello,

After upgrading my Ubuntu OS from 16.04 to 17.04, I can not access getcomposer.org or packagist.org.

When you try to install the composer it returns the following error:

> PHP Warning:  file_get_contents(https://getcomposer.org/versions): failed to open stream: Operation timed out in

I did some connectivity tests and running ping as ipv4 nothing returns, however using ipv6 works normally.
Test IPV4:
`$ ping -4 -c 3 getcomposer.org`
> PING getcomposer.org (87.98.253.108) 56(84) bytes of data.
--- getcomposer.org ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2037ms

`$ ping -6 -c 3 getcomposer.org`
> PING getcomposer.org(2001:41d0: a:7b19::2 (2001:41d0: a:7b19::2)) 56 data bytes
64 bytes from 2001:41d0: a:7b19::2 (2001:41d0: a:7b19::2): icmp_seq=1 ttl=53 time=233 ms
64 bytes from 2001:41d0: a:7b19::2 (2001:41d0: a:7b19::2): icmp_seq=2 ttl=53 time=233 ms
64 bytes from 2001:41d0: a:7b19::2 (2001:41d0: a:7b19::2): icmp_seq=3 ttl=53 time=234 ms

--- getcomposer.org ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2001ms
rtt min/avg/max/mdev = 233.830/234.163/234.682/0.542 ms

Is there any extra configuration for this OS version?

Thanks

**Comment by robfrawley** [comment]
Nope; I've been using that version of Ubuntu on my main development system since its release and have never encountered the errors you mentioned.

**Comment by viniciuseduardo** [comment]
@robfrawley 
I can not access via Browser and Terminal (curl, wget, etc).

Before the upgrade, it was working normally.

**Comment by robfrawley** [comment]
This is likely a network or configuration issue on your end (possibly a routing issue with your home network, or maybe the OS upgrade caused it due to extra PPAs, non-standard etc configuration, or any number of things), but there is nothing Ubuntu `17.04`-specific that needs to be configured for `packagist.org` or `getcomposer.com` to work, assuming a fully-functional system.

**Comment by alcohol** [comment]
Networking issue on user side.

**Comment by viniciuseduardo** [comment]
Hello,

I was able to fix the problem by reinstalling the drivers for the network card.

Thank you all for your help
