### ISSUE TITLE
Support using apcu autoloader on HHVM

### ISSUE THREAD

**Issue by legoktm** [composer/composer#6658]
The apcu autoloader currently looks for the existence of the function `apcu_fetch`. However, HHVM still only has the old APC function names (<https://github.com/facebook/hhvm/issues/6784>):
```
$ hhvm -a
hphpd> =function_exists('apcu_fetch');
=function_exists('apcu_fetch');
false
hphpd> =function_exists('apc_fetch');
=function_exists('apc_fetch');
true
```
Can this be changed to also check for the legacy `apc_fetch` to support HHVM?

**Comment by derrabus** [comment]
Does it work if you add `symfony/polyfill-apcu` to your project's dependencies?

**Comment by legoktm** [comment]
No, I don't think that will work. in `autoload_real.php`, there's a call to `$loader->setApcuPrefix()` which does a check to see whether the `apcu_fetch` function exists. After that, only then are the autoload_files enabled, which sets up the polyfill.

**Comment by alcohol** [comment]
`apc` and `apcu` are different implementations. It is not just about 'old' names.

**Comment by legoktm** [comment]
Right, but in this case it it shouldn't matter as the two APCu functions being called should have the same functionality regardless of whether they are APC or APCu.

**Comment by derrabus** [comment]
Well you could manually include the polyfill's bootstrap script before requiring `vendor/autoload.php`. Still, it remains a dirty workaround.

```php
require __DIR__.'/vendor/symfony/polyfill-apcu/bootstrap.php';
require __DIR__.'/vendor/autoload.php';
```

Anyway, I don't think that Composer should implement support for the legacy APC methods. This is an issue, HHVM should fix, imho.

**Comment by alcohol** [comment]
I agree with @derrabus, this really is a HHVM issue, not a Composer issue.

You could alias the functions locally as a work around for now.

**Comment by legoktm** [comment]
I agree that ideally this should be fixed in HHVM, but I don't think that should prevent composer from also implementing a work around. Composer already works around other odd uses, so I'd have thought stock HHVM would be something that could also be accommodated. Even if HHVM were to implement it today, it could still be around a year before it makes its way into actual usage due to LTS release cycles, similar to any PHP bugfix.

I can easily alias the functions in MediaWiki itself, but I thought this would be something that other HHVM users could benefit from and wanted to share with others.

And just to be clear, this isn't just for HHVM - this also affects PHP 5.3 and 5.4 users, which composer also still supports (though if you're really cared about performance I doubt you'd still be using those versions).

**Comment by Seldaek** [comment]
5.3/5.4 as you say are no concern because I won't take anyone seriously about performance that is still running these. HHVM is different, but given the amount of HHVM usage we see I rather not add some hacks in the autoloader that will add a useless function_exists call for every file autoloaded for 99% of users.

I would suggest fixing HHVM so that it provides apcu_* functions, and adding function aliases in your bootstrap script as a stopgap solution, which as you say is very easy and will be also more efficient than calling function_exists every time.
