### ISSUE TITLE
Allow a given package and its dependencies (including siblings) to be updated.

### ISSUE THREAD

**Issue by grasmash** [composer/composer#6661]
This feature request is intended to address a very common difficulty with updating composer packages. It is inspired by a large number of support requests.

###  Summary

It is not possible to update a single package and its dependencies if one of those dependencies is also defined in the root composer.json file.

### Scenario

My composer.json file defines the following:

```json
{
    "require": {
        "acme/package1": "^1.0.0",
        "acme/package2": "^1.0.0",
        "unrelated/package1": "^1.0.0"
     }
}
```

Currently installed versions are:

* acme/package1: 1.0.0
* acme/package2: 1.0.0

I would like to update acme/package1 to 1.0.1,  which happens to rely on acme/package2 1.0.1.

I'd like to perform this update using a single command that updates only acme/package1 and its dependencies. Unfortunately, this is not possible with `composer update acme/package1` or `composer update acme/package1 --with-dependencies`. The definition of `"acme/package2": "^1.0.0"` in my composer.json prevents the update from executing, despite the fact that its version constraint is compatible with both new versions of the new packages.

The upshot here is that one needs to either manually traverse the dependency tree and figure out which packages should be manually updated, or else execute a wholesale `composer update`,  which can have unintended consequences by updating more packages than are necessary.

###  Suggested solutions

1. Modify the `--with-dependencies` option such that it is able to update packages that are defined in the root composer.json file.
1. Introduce a new option such as `--with-dependencies-and-siblings` (or something shorter) that would provide this capability.

**Comment by grasmash** [comment]
It looks like this issue has been discussed previously:

* github.com/composer/composer/issues/4795, https://github.com/composer/composer/blob/14c77130e8f717ceb154720e1abefafe99124cb9/tests/Composer/Test/Fixtures/installer/github-issues-4795.test#L5
* https://github.com/composer/composer/pull/4817#issuecomment-175019534

I believe that the issue is not resolved, given the following [rationale](https://github.com/composer/composer/pull/4817#issuecomment-175019534):
> The idea is that you want versions listed in your composer.json to be in specific versions unless you explicitly update them. --with-dependencies should only update packages which are not explicitly listed as dependencies themselves.  

However, this comment overlooks the fact that you might have a minimum version defined in your composer.json  rather than an exact version. In this case, if the version constraint is compatible with of the newly available package version, it should be white listed.

**Comment by Jean85** [comment]
Well, whitelisting shouldn't just allow a package to be updated? I expect that the constraint would still be enforced, what's the rationale behind not whitelisting `package2`?

From #4795:
> So, figured out why it doesn't update the root package. Seems like a deliberate choice (considering the implementation). Whether or not it is desirable is another question though.

IMHO it's not desiderable, since the user is explicitly using a flag to propagate the update downwards. If the root requirement is not correctly constrained and we get a botched update, it's the user who's at fault.

**Comment by grasmash** [comment]
Agreed. I believe that the --with-dependencies flag should update dependencies listed in the root composer.json.

Using the flag implies that the user expects all dependencies to be updated. The current behavior is confusing and unexpected.

**Comment by Seldaek** [comment]
The rationale behind the current behavior is that the dependencies you explicitly list are your direct dependencies that your code relies on, and as such you probably want to manage them with more care than transient dependencies which can simply update using --with-dependencies.

We could perhaps add a --with-all-dependencies that ignores this fact and includes the whole dependency tree of whitelisted deps. That combined with more detailed documentation about the flag(s) would hopefully help reduce the confusion.

**Comment by grasmash** [comment]
> We could perhaps add a --with-all-dependencies

That would be a solution that adequately addresses the issue.

**Comment by grasmash** [comment]
> you probably want to manage them with more care than transient dependencies which can simply update using --with-dependencies.

Yes, however, modifying the behavior such that the `--with-dependencies` flag would update root packages would not preclude one from carefully managing said dependencies.  All version constraints would still be respected. So, the package maintainer would still be able to fully manage all direct dependencies with care.

Executing `composer update --with-dependencies` would therefore not cause any unexpected behavior as the packages would be updated completely in line with the version constraints in the root package.

**Comment by Seldaek** [comment]
Yeah the problem is that in some contexts you end up with a lot of packages depending on the same stuff and if you update one with dependencies you end up updating half your application's dependencies which you don't necessarily want. Anyway having both options probably makes most sense.

**Comment by grasmash** [comment]
Should there be a new `no-update-with-all-dependencies` for `remove` and  `update-with-all-dependencies` for `require` ?

**Comment by Seldaek** [comment]
For require I guess yes, for remove no it's not necessary as removing dependencies that are also required by the root package does not make sense anyway.

**Comment by grasmash** [comment]
@Seldaek #6674 is ready for review.

**Comment by grasmash** [comment]
@Seldaek Is there anything that I can do to move this issue forward?

**Comment by Seldaek** [comment]
@grasmash nope.. just have some patience :) I moved to a new apartment yesterday, and have a ton of other stuff going on as well as holidays coming up. I'll get to it when I have some time.

**Comment by rulatir** [comment]
People. Just. Want. To. Be. Able. To. Update. A. Package. In O(1) time. Without the long and tedious and iterative process where you attempt the update, eye-grep the problem list for dependencies that also need to be bumped, add them to the require command, and try again until you succeed.

This should be possible and easy, and should not require starting from scratch (i.e. deleting `composer.lock` and `vendor/`).

**Comment by Seldaek** [comment]
There is `--update-with-all-dependencies` (or `-W`) that should do that.

**Comment by stof** [comment]
@rulatir `--with-dependencies` is implemented since years. and `--update-with-all-dependencies` as well as this issue is closed since 2017

**Comment by rulatir** [comment]
> @rulatir `--with-dependencies` is implemented since years. and `--update-with-all-dependencies` as well as this issue is closed since 2017

Doesn't work though:

```
$ composer require --update-with-all-dependencies auth0/php-jwt:3.4.x-dev
PHP Deprecated:  Directive 'allow_url_include' is deprecated in Unknown on line 0
./composer.json has been updated
Running composer update auth0/php-jwt --with-all-dependencies
Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - auth0/auth0-php is locked to version 7.9.2 and an update of this package was not requested.
    - auth0/auth0-php 7.9.2 requires auth0/php-jwt 3.3.4 -> found auth0/php-jwt[3.3.4] but it conflicts with your root composer.json require (3.4.x-dev).


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

If `--update-with-all-dependencies` does NOT have the semantics of "do EVERYTHING it takes, relax ALL locked version requirements that must be relaxed, in order for this command to SUCCEED", then it doesn't implement this feature request, full stop.

**Comment by Seldaek** [comment]
The thing is there is no easy way to do what you want unless by unlocking all packages, and doing a full update, which you can do with `composer require auth0/php-jwt:3.4.x-dev --no-update && composer update`. That may update things you don't want it to update though.

If you disagree you are welcome to work on a plugin adding a `composer require-magically foo/bar` command.

**Comment by Seldaek** [comment]
> One undesirable side effect of this manual procedure (apart from it being manual) is that those packages end up as direct dependencies of my project (because adding them as such is the ONLY way to unlock them selectively), so I must remove them from composer.json and re-run composer install afterwards (they will remain installed as dependencies).

That is not true, you can't abuse the require command to do partial updates without adding packages, true, but you can do a composer require with --no-update, then use `composer update new/pkg other/blocking-dep` and it will not add other/blocking-dep to your composer.json.

As for require-recursively, I see very well what you mean, but it's not something that plays well at all with our model of the dependency resolution, so it'd have to be built around the whole solver as a solve/parse-error/solve-again/parse-error/.. loop which is indeed probably doable, but not something I feel is such a necessity. I hardly ever have problems like that, and you seem to be the only one ranting here, hence why I suggested you write a plugin if it is such a big everyday problem for you.

**Comment by rulatir** [comment]
> That is not true, you can't abuse the require command to do partial updates without adding packages, true, but you can do a composer require with --no-update, then use `composer update new/pkg other/blocking-dep` and it will not add other/blocking-dep to your composer.json.

The thing is, other/blocking-dep can BE a direct dependency in my `composer.json`, together with a blocking constraint. In this case I would HAVE to require it, update won't do, will it?

**Comment by rulatir** [comment]
It's not an "everyday problem", but once you hit it, it's hours upon hours upon hours upon hours upon hours of nuclear disarmament negotations with composer.

**Comment by rulatir** [comment]
Is there a way to get those problem reports in a machine processable format? Parsing natural language would be last resort.

**Comment by Seldaek** [comment]
> The thing is, other/blocking-dep CAN be a direct dependency in my composer.json, together with a blocking constraint. In this case I would HAVE to require it, update won't do, will it? 

If your constraint prevents it from updating to a compatible version you'll have to change that, sure, but that's an even rarer occasion I'd imagine. Overall keeping regularly updated by looking at `composer outdated` is probably the best so you don't end up with tons of conflicting dependencies..

> Is there a way to get those problem reports in a machine processable format? Parsing natural language would be last resort.

Not really, other than calling the solver directly (see how it's done in Composer\Installer), then you have the SolverProblemsException::getProblems to get the raw data. Parsing the string output might be easier though tbh, at least to prototype something, there's gonna be way less of a learning curve that way.

**Comment by rulatir** [comment]
> If your constraint prevents it from updating to a compatible version you'll have to change that

That's the problem right here. I want to be able to concisely express the following meta-intention: "my intention is to **upgrade this package**, and all other intentions directly or indirectly conflicting with this one should be automatically conservatively adjusted".
