### ISSUE TITLE
Install does not trigger credential request for GitLab private repositories

### ISSUE THREAD

**Issue by Jean85** [composer/composer#6669]
The scenario is: **I'm installing a new dev environment for my project on a new machine**.

My (reduced and redacted) `composer.json`:

```json
{
    "name": "my-project/core",
    "repositories": [
        {
            "type": "gitlab",
            "url": "https://gitlab.mydomain.com/my-project/client.git"
        }
    ],
    "require": {
        "my-project/client": "0.2",
    },
    "config": {
        "gitlab-domains": [
            "gitlab.mydomain.com"
        ]
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
require.roave/security-advisories : unbound version constraints (dev-master) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command (on a new setup, just after cloning my project):

```
composer install
```

I get the following output:

```
Package operations: 1 install, 0 updates, 0 removals
- Installing my-project/client (0.2.0): Downloading (failed)    Failed to download my-project/client from dist: The "https://gitlab.mydomain.com/api/v4/projects/my-project%2Fclient/repository/archive.zip?sha=890e40e40c418eeb5ace0073b6f72dc8b772051e" file could not be downloaded (HTTP/1.1 404 Not Found)
Now trying to download from source
- Installing my-project/client (0.2.0): Cloning 890e40e40c

[RuntimeException]
Failed to execute git clone --no-checkout 'git@gitlab.mydomain.com:my-project/client.git' '/var/www/my-project/core/vendor/my-project/client' && cd '/var/www/my-project/core/vendor/my-project/client' && git remote add composer 'git@gitlab.mydomain.com:my-project/client.git' && git fetch composer                                                                                        
Cloning into '/var/www/my-project/core/vendor/my-project/client'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.                                                                                                                                                           
```

And I expected this to happen:
I expect to be asked for my GitLab credentials, to populate `auth.json` with a fresh OAuth token, as it happens if I launch a `composer update`. Since I'm just installing a new dev environment, I don't want to alter my `composer.lock` file.

[EDIT] I've edited the output, it seems that GitLab responds 404 instead of 401; I don't know if that is intentional to not leak information about private repositories or not.

**Comment by Seldaek** [comment]
If you run a composer update I guess it would prompt you, but on install it tries to download the zip directly and if that fails with a 404  it won't trigger our code asking for gitlab credentials..

f71baa5e0 attempts to fix that by making it prompt on gitlab 404s. Please try to `self-update --snapshot` and check whether it helps?

**Comment by Jean85** [comment]
Tested, it's working, thanks @Seldaek for the fast fix!

**Comment by Seldaek** [comment]
Great, will try and get a release out soon then

**Comment by Steveb-p** [comment]
I know I'm a necromancer, but I just wanted to thank @Seldaek for resolving this particular issue :) :beer: 

I only had to my own domain to `gitlab-domains` in config, but otherwise it worked great :)
