### ISSUE TITLE
Long download for composer.json file when using alternative vcs.

### ISSUE THREAD

**Issue by rquadling** [composer/composer#6680]
Hi.

I've made a patch to a dependency and whilst I'm waiting for it to be merged, I'm using my repo.

The package in question has a LOT of releases/tags.

When I have added my vcs to composer.json, and then ran `composer update` (so that my project will now get my patched version - using a tag of 3.36.4.1 - 3.36.4 is the last official release), there is a very long wait whilst composer downloads all the composer.json files for all the versions.

Is it feasible/possible to not bother downloading versions/tags of composer.json that fail to match the requirements?

For example ...

```
 "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/rquadling/aws-sdk-php"
    }
  ],
...
  "require-dev": {
    "aws/aws-sdk-php": "^3.36",
    ...
  },
```

Considering I'm asking for a version of 3.36 or greater, it would seem pointless to download any composer.json file for a version less than that.

**Comment by rquadling** [comment]
It does seem that this is a one time issue, but all our devs will be affected and our build times will be extended by several minutes, so blocking the retrieval of unusable (from what I can tell) data would seem useful.

**Comment by alcohol** [comment]
This is how the vcs repository works. The only "fix" you can apply is removing all tags you don't care about from your fork.

**Comment by rquadling** [comment]
OK. Fair enough.
