### ISSUE TITLE
[HELP] detect wich package adds contraints on a specific dependency version

### ISSUE THREAD

**Issue by quazardous** [composer/composer#6686]
Say I have a project with many required packages and so lots of (hidden) dependencies (more packages).

One one the (hidden) dependency is in an outdated version.

How can I quickly list the required packages which trigger this specific constraint ?

I tried with `composer show -t` but it was not helpful.

**Comment by xabbuh** [comment]
You can use `composer depends`/`composer prohibits` to find out why package depends on a particular version of another package or which one is prohibiting the installation of a particular package/version.

**Comment by quazardous** [comment]
thx
