### ISSUE TITLE
Package "name" listed for update is not installed. Ignoring.

### ISSUE THREAD

**Issue by ctf0** [composer/composer#6687]
atm we have 
> composer update --with-dependencies

which sadly does nothing, because composer already have a constraint that if the package is not listed in root "composer.json" , then dont update which is kinda dump because now the `--with-dependencies`is simply useless.

i 've also tried
> composer update package-name
> composer update vendor/*

but without luck, so is there **ANY** way to force update the packages & override the dame `Package "name" listed for update is not installed. Ignoring.` error ?

**Comment by alcohol** [comment]
You are not making much sense. It seems like you have tried solutions that do not work, but we cannot help you with this because you did not share the actual problem with us. Therefor we are unable to determine why your chosen solutions do not work for your scenario.

**Comment by ctf0** [comment]
i dont know how expressive you want me to describe this issue but to make things as clear as possible.

atm composer wont update a dependency unless its required in the project main `composer.json`
which for example

1- if we have a package that depends on another ex.
```json
"require": {
        "php" : "~7.0",
       "abc/some-package": "^1.0"
    },
```
and on installing this package we downloaded the version `1.0.0` of `abc/some-package`

2- after a while when running `composer outdated` we found out that `abc/some-package` is now at version `1.1.0` 

3- composer wont fetch that new version, and instead will display the error 
`Package "abc/some-package" listed for update is not installed. Ignoring`

and the reason we are getting this error is because composer dont update package dependencies.

**Comment by alcohol** [comment]
Cannot reproduce.

**Comment by ctf0** [comment]
lets try from another angle, how to suppress the `Package "name" listed for update is not installed. Ignoring` error and bypass that restriction ?

**Comment by stof** [comment]
Composer do update transitive deps when you do a full update (just `composer update`)

**Comment by ctf0** [comment]
here is a package to test with

`composer require ctf0/media-manager:1.2.2`
in this package am requiring `ziggy` as dependency at version `^0.3` and the latest is `0.4.1`

install it and test `composer update`

**Comment by stof** [comment]
Well, this is because your constraint forbids using `0.4.1`.
The semver operator (`^`) allows composer to update the package until the next BC-breaking release. It respects the semver semantic of pre-1.0 release: when the left number is `0`, an update of the next number is considered a BC-breaking update (rules is recursive in case you make versions like `0.0.1`).

**Comment by stof** [comment]
btw, you can use the `composer prohibits ziggy 0.4.1` command to ask composer to explain you why ziggy 0.4.1 cannot be used in your project when asking for updates.

**Comment by ctf0** [comment]
f*ck, really ?!!

okay thanx, but doesnt composer have a `--force-update` option to update packages even its going to break compatibility ?

**Comment by alcohol** [comment]
It does not have a `--force-update`.

**Comment by ctf0** [comment]
okay thanx for all ur help.

**Comment by stof** [comment]
@ctf0 Composer resolves dependencies respecting the constraints given by packages. If `ctf0/media-manager` tells composer that it cannot work with `ziggy` 0.4, why would composer expose an option to force using 0.4 of this package ?
What you need to do is update the version constraint in `ctf0/media-manager` (to make it accept 0.4 versions, telling composer they are fine together) and make a new release. Then composer will happily use ziggy 0.4 when updating ctf0/media-manager to a version accepting it.
