### ISSUE TITLE
Question: is config.platform inherited?

### ISSUE THREAD

**Issue by jeabakker** [composer/composer#6688]
Sorry if this question has already been asked/answered.

Imagine the following setup

Package composer.json
```json
{
    "name": "my/package",
    "require": {
        "some/other_package": "~1.0"
    },
    "config": {
    	"platform": {
	    	"php": "5.6",
	    }
    }
}
```
This will ensure that dependency is installed as if i'm using PHP 5.6

Project composer.json
```json
{
    "type": "project",
    "name": "my/project",
    "require": {
        "my/package": "~1.0"
	}
}
```

If i run `composer update` on the **project** will it pretend to be PHP 5.6 or will it use my actual PHP version of the machine from which i run the command (eg. PHP 7)

**Comment by alcohol** [comment]
It is not inherited.

**Comment by jeabakker** [comment]
thanks for the answer, i need to learn to read more ;)
