### ISSUE TITLE
composer fails to execute on windows with php 7.2 RC2

### ISSUE THREAD

**Issue by tmak7** [composer/composer#6693]
Hi

composer executed fine on windows + php 7.2 Beta 3.

When attempting to execute it on windows + php 7.2 RC2, whichever command I execute, getting the following error:
````
C:\tmp\inst>php composer.phar

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "list" is not defined.
  Did you mean this?
````
Note: the issue does NOT occur on Linux with the same php version.
Anyone has a contrary experience ?

**Comment by johnstevenson** [comment]
Works fine for me:
php 7.2.0 RC2 (VC15 x86 Non Thread Safe)
Composer version 1.5.2

**Comment by alcohol** [comment]
List is one of the default commands that the symfony/console library provides. Not sure how it could be missing from your composer.phar. Did you build it yourself?

**Comment by tmak7** [comment]
Nope, I've downloaded v1.5.2 from https://getcomposer.org/download. 
Once it failed, also followed the Command-line installation, but reached the exact same results.
I'm using also the NTS version with a nightly release of Zend Server.

**Comment by johnstevenson** [comment]
What happens if you download a standalone PHP and use that (rather than using the PHP from the Zend Server installation)?

**Comment by tmak7** [comment]
Indeed seems to work fine on standalone PHP - so closing for now, thanks !
