### ISSUE TITLE
`run` as an alias to `run-script`?

### ISSUE THREAD

**Issue by borekb** [composer/composer#6697]
The [Scripts documentation](https://github.com/composer/composer/blob/edece864e7e4c668dcad6601df70777882d22116/doc/articles/scripts.md) strictly uses `composer run-script xyz` while it seems that `composer run xyz` works equally well and maybe could be mentioned in the docs as it is shorter to write.

I was thinking about submitting a docs PR but now that I'm looking at [`RunScriptCommand`](https://github.com/composer/composer/blob/e12e0335a4d467878093fc76e3dea592ff3e1ce3/src/Composer/Command/RunScriptCommand.php) I'm not sure: it registers only `run-script` and there is no mention of plain `run` there. Could someone guide me? Do you guys and galls use `run-script` or just `run` in practice?

**Comment by stof** [comment]
This is due to the way symfony/console works. Any command name can be shortened as much as you want, as long as it stays unambiguous (i.e. only one command name starts like that`

**Comment by stof** [comment]
Note that if you define a script named `run`, a command will be registered for it and so `composer run` won't be expanded to `run-script` anymore.
so if you are doing some scripting, always use the actual command name.

**Comment by borekb** [comment]
Aha! That explains it nicely, so I guess it's not advisable to just use `run` (generally). I thought it's some kind of alias like `npm run` and `npm run-script`.

**Comment by stof** [comment]
yeah, if you know that your own project does not have anything overriding the `run` shortcut (no script with a name starting with `run` and no composer plugin providing a command starting with `run`), you might shorten the name when calling it. But for any scripting purpose, use the full name.
And if you are not sure about the first condition, use the full name. If the offending script/command is named exactly `run`, running `composer run` would call this one (if its name only starts with `run`, composer would fail saying the shortcut is mabiguous)
