### ISSUE TITLE
OAUTH Credentials being Removed from composer.json config section...

### ISSUE THREAD

**Issue by brandontamm** [composer/composer#6698]
My `composer.json`:

```json
see below
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
```

When I run this command:

```
composer update --ignore-platform-reqs
```

I experience the following strange behavior:

The oauth credentials are removed from my composer.json config section for some odd reason:
BEFORE running command:
```
    "config": {
        "use-include-path": true,
        "github-protocols": ["https", "http"],
        "github-oauth": {"github.com": "keys-removed"},
        "bitbucket-oauth": {"bitbucket.org": {"consumer-key": "keys-removed", "consumer-secret": "keys-removed"}}
    },

```

AFTER running command:
```
    "config": {
        "use-include-path": true,
        "github-protocols": ["https", "http"],
        "github-oauth": {
            "github.com": "keys-removed"
        },
        "bitbucket-oauth": {

        }
    },

```

And I expected this to happen:
OAuth should not be removed from composer.json. I wouldn't expect composer.json to be changed at all, ever. But It is literally remove all of my bitbucket-auth section containing my keys and the entire syntax...Any ideas?

**Comment by brandontamm** [comment]
Please note, during the time that the credentials are removed from the file, there is an auth.json file creating in ~./composer and the credentials are added there like so:
`{
    "bitbucket-oauth": {
        "bitbucket.org": {
            "consumer-key": "keys-removed",
            "consumer-secret": "keys-removed",
            "access-token": "keys-removed",
            "access-token-expiration": 1506118998
        }
    }
}
`

**Comment by alcohol** [comment]
Correct, credentials belong in auth.json, not in composer.json.

**Comment by brandontamm** [comment]
Assuming I can close this. Moving credentials from composer.json "config" section to auth.json is recommended method per @alcohol
