### ISSUE TITLE
Composer requesting packagist authentication

### ISSUE THREAD

**Issue by Furqanaa** [composer/composer#6699]
I'm new to laravel & composer, I used composer to download laravel package, the composer is requesting an authentication for packagist.org:
`Installing laravel/laravel (v5.5.0)

Installing laravel/laravel (v5.5.0): Loading from cache
Created project in TestLaravel
@php -r "file_exists('.env') || copy('.env.example', '.env');"
Loading composer repositories with package information
Updating dependencies (including require-dev)
Authentication required (packagist.org):
  Username:
  Password:
[Composer\Downloader\TransportException]
The "http://packagist.org/p/fideloper/proxy%245475fc0d4379d08a55b6e256813b0
223f779b1106292a3895064434bad3eb6a9.json" file could not be downloaded: fai
led to open stream: A connection attempt failed because the connected party
did not properly respond after a period of time, or established connection
failed because connected host has failed to respond.

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--r
epository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no
-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vc
s] [--no-install] [--ignore-platform-reqs] [--] [] [] []
`
I notice that I don't have a composer.json file in Users\MyUser\AppData\Roaming\Composer

I tried to add my packagist.org account to auth.json:
"http-basic": {"packagist.org": { "username": "my_account", "password": "my_password" }}
the composer did not requested authentication any more but i still have the following exception:
`Installing laravel/laravel (v5.5.0)

Installing laravel/laravel (v5.5.0): Loading from cache
Created project in TestLaravel
@php -r "file_exists('.env') || copy('.env.example', '.env');"
Loading composer repositories with package information
Updating dependencies (including require-dev)
[Composer\Downloader\TransportException]
Invalid credentials for 'http://packagist.org/p/fideloper/proxy%245475fc0d4
379d08a55b6e256813b0223f779b1106292a3895064434bad3eb6a9.json', aborting.

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--r
epository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no
-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vc
s] [--no-install] [--ignore-platform-reqs] [--] [] [] []
`
Please any idea on how to solve this ?

**Comment by alcohol** [comment]
It looks to me like you are behind a proxy perhaps. Because packagist.org will *never* ask you for a username and password.
