### ISSUE TITLE
Wrong sha384 checksum

### ISSUE THREAD

**Issue by NormanHoehne** [composer/composer#6701]
The sha384 checksum you provide on https://composer.github.io/pubkeys.html differs from the one I calculate on latest Composer-Setup.exe:

3d1ca61917afeff4337fc9ff20aa97193aeae143958796d4f1e2a17d2ed56cad1f11fb37c881ef2896ac08df18349804

How does that come? Wrong File? Key not updated?

**Comment by jvasseur** [comment]
The hash shown on https://composer.github.io/pubkeys.html is the hash of the bash installer (https://getcomposer.org/installer).

I don't think the hash of the windows installer is published somewhere.

**Comment by alcohol** [comment]
> I don't think the hash of the windows installer is published somewhere.

Indeed it is not. 

@johnstevenson you think you could offer a SHA for the windows installer? Maybe just as a file as part of the 'release' on Github?

**Comment by johnstevenson** [comment]
Yes, I could do something along those lines. The exe is already code-signed.

**Comment by johnstevenson** [comment]
On second thoughts, I don't think I'll bother. As I said, the code is already SHA256 code-signed.

**Comment by alcohol** [comment]
Fine with me :-) 👍
