### ISSUE TITLE
Use sodium_crypto_generichash for version 2

### ISSUE THREAD

**Issue by webysther** [composer/composer#6702]
Maybe is time to consider [BLAKE2](https://en.wikipedia.org/wiki/BLAKE_%28hash_function%29#BLAKE2) provided by sodium wich is more fast than MD5 and more secure than used SHA256, is provided by [polyfill](https://github.com/mollie/polyfill-libsodium) for PHP7.2 parity and [polyfill](https://github.com/paragonie/sodium_compat) of implementation too.

# crypto_generichash()

For PHP developers: This is sort of like `hash()`, except it can also be `hash_hmac()` if you pass a key, and it only allows BLAKE2b (so you don't have to select the algorithm).

You want to use `crypto_generichash()` anywhere you'd normally use `hash()`, `md5()`, or `sha1()` (unless "normally" implies something that would cause a cryptographer would look at you funny). `crypto_generichash()` is attractive because it is all of the following:

- Collision-resistant
- Preimage-resistant
- Immune to length-extension attacks
- More secure than SHA256
- Faster than MD5

Reference: https://dev.to/paragonie/libsodium-quick-reference#crypto-generichash

**Comment by alcohol** [comment]
Not really a short term priority I would think. We have more important things to focus on. But could definitely be on the 2.0 roadmap.

**Comment by Seldaek** [comment]
I just had another look at this, and I did not really identify any place we are using md5/sha256 right now where we could switch without breaking BC. There's only one instance which is just a debug thing and thus fairly inconsequential.

So closing, but keeping in mind that this would be a good hashing function to use going forward so we don't introduce more legacy.
