### ISSUE TITLE
How to replace the 3rd party dependency

### ISSUE THREAD

**Issue by kenorb** [composer/composer#6705]
My `composer.json`:

```json
{
  "require-dev": {
    "guzzlehttp/guzzle": "5.3.x-dev as 5.0.0",
    "aeris/guzzle-http-mock": ">=1.1.5"
  }
}
```

I'm trying to replace requirement for `guzzlehttp/guzzle` (required by `aeris/guzzle-http-mock`)  and use `5.3.x-dev` version instead of `5.0.0`.

Also I've tried to use `replace` section, e.g.

```
  "replace": {
    "guzzlehttp/guzzle": "5.3.x-dev"
  }
```

However I've got still the following error:

```
  Problem 1
    - aeris/guzzle-http-mock 1.1.5 requires guzzlehttp/guzzle ~5.0.0 -> no matching package found.
    - aeris/guzzle-http-mock 1.1.5 requires guzzlehttp/guzzle ~5.0.0 -> no matching package found.
    - Installation request for aeris/guzzle-http-mock 1.1.5 -> satisfiable by aeris/guzzle-http-mock[1.1.5].
```

Is it possible to achieve the above? To replace the version provided by `composer.json` hosted on _packagist_?

**Comment by stof** [comment]
What do you mean by replacing the requirement ?

**Comment by stof** [comment]
btw, if the library says it supports only `5.0.*` of guzzle, forcing it to install alongisde 5.3 may create weird issues.

**Comment by kenorb** [comment]
@stof I'd like to install `aeris/guzzle-http-mock`, however the package has hardcoded:

    "guzzlehttp/guzzle": "~5.0.0"

where I'd like to lower the expectation and install `^5.0` or `5.3`.

**Comment by stof** [comment]
Well, you should first try to get this change in the library itself. And then, a better solution to solve your issue is to use a forked version of the mock library (adding support for newer Guzzle versions) until the change is merged upstream instead of aliasing guzzle (which may affect other packages, and create weird issues due to lying on the actual version of Guzzle)

See https://getcomposer.org/doc/articles/aliases.md#require-inline-alias for the way to use a fork temporarily.

**Comment by kenorb** [comment]
The package is [not maintained anymore](https://github.com/aerisweather/GuzzleHttpMock/issues/4#issuecomment-325762961) and there is another fork at [`systemhaus/GuzzleHttpMock`](https://github.com/systemhaus/GuzzleHttpMock), but it's supporting Guzzle 6, which my code can't, so what you're saying, I should create another fork and publish on _packagist_.  I thought you can use `replace` or `as` to replace these dependencies, but it sounds like you cannot.

**Comment by Seldaek** [comment]
The inline alias you used should have worked so not sure what was going on there, but anyway closing as hopefully it's resovled by now. And no publishing forks on packagist is not the way, you should define the repository in your composer.json and not pollute packagist :)

**Comment by hayden-t** [comment]
I found that just putting the alias require in my composer.json didnt have effect, i had to use require command instead to add it, and then i could require my old package
php composer.phar require "guzzlehttp/guzzle:7.4.5 as 6.3"
php composer.phar require mitchdav/st-george-ipg "1.0.0"

**Comment by tiller1010** [comment]
I had a similar issue. The inline alias **did** work for me.
