### ISSUE TITLE
Composer Doesn't Work

### ISSUE THREAD

**Issue by GhaleonZ** [composer/composer#6715]
My `composer.json`:
{
    "require": {
         "mediawiki/semantic-extra-special-properties": "~1.5",
         "mediawiki/semantic-breadcrumb-links": "~1.4"
    }
}

Output of `composer diagnose`:
WTH is composer diagnose?

When I run this command:

composer update -vvv

I get the following output:

A bunch of garbage, telling me the global JSON is nowhere to be found. And then Composer spends 5 hours trolling through packagist with a bunch of unnamed JSON downloads, that are less than 20mb total in size. And then writing into the AppData/Local directory's repo folder a variety of JSON files that are already in my vendor folder of the XAMPP installation I'm using.

And I expected this to happen:

What I'm told will happen is that it's supposed to download and install those two extensions for my Mediawiki installation. But it never happens. I've seen the way it's supposed to look, and my log looks NOTHING like that at all.

In short, Composer was installed via the Windows Setup exe, directed to the PHP.exe file inside my XAMPP installation. And that is the only thing that has worked in this entire process.

Using Composer Require from the command line does edit the composer.json file inside htdocs/zephyr (where my MW installation is).

But after that, it does NOTHING like everyone says it does. It doesn't install anything. But instead appears to troll GIT and download stuff that is already in my vendor folders.

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Ghaleon>cd c:\xampp\htdocs\zephyr

c:\xampp\htdocs\zephyr>composer require mediawiki/semantic-extra-special-propert
ies "~1.5" -vvv
Reading ./composer.json
Loading config file ./composer.json
Checked CA file C:\Users\Ghaleon\AppData\Local\Temp\composer-cacert-e78c8ab7b443
2bd466e64bb942d988f6c0ac91cd785017e465bdc96d42fe9dd0.pem: valid
Executing command (C:\xampp\htdocs\zephyr): git branch --no-color --no-abbrev -v

Executing command (C:\xampp\htdocs\zephyr): git describe --exact-match --tags
Executing command (C:\xampp\htdocs\zephyr): git log --pretty="%H" -n1 HEAD
Executing command (C:\xampp\htdocs\zephyr): hg branch
Executing command (C:\xampp\htdocs\zephyr): fossil branch list
Executing command (C:\xampp\htdocs\zephyr): fossil tag list
Executing command (C:\xampp\htdocs\zephyr): svn info --xml
Failed to initialize global composer: Composer could not find the config file: C
:/Users/Ghaleon/AppData/Roaming/Composer/composer.json
To initialize a project, please create a composer.json file as described in the
https://getcomposer.org/ "Getting Started" section
Reading C:\xampp\htdocs\zephyr/vendor/composer/installed.json
Loading plugin Wikimedia\Composer\MergePlugin
Running 1.5.2 (2017-09-11 16:59:25) with PHP 7.1.7 on Windows NT / 6.1
./composer.json has been updated
Reading ./composer.json
Loading config file ./composer.json
Executing command (C:\xampp\htdocs\zephyr): git branch --no-color --no-abbrev -v

Executing command (C:\xampp\htdocs\zephyr): git describe --exact-match --tags
Executing command (C:\xampp\htdocs\zephyr): git log --pretty="%H" -n1 HEAD
Executing command (C:\xampp\htdocs\zephyr): hg branch
Executing command (C:\xampp\htdocs\zephyr): fossil branch list
Executing command (C:\xampp\htdocs\zephyr): fossil tag list
Executing command (C:\xampp\htdocs\zephyr): svn info --xml
Failed to initialize global composer: Composer could not find the config file: C
:/Users/Ghaleon/AppData/Roaming/Composer/composer.json
To initialize a project, please create a composer.json file as described in the
https://getcomposer.org/ "Getting Started" section
Reading C:\xampp\htdocs\zephyr/vendor/composer/installed.json
Loading plugin Wikimedia\Composer\MergePlugin_composer_tmp0
Loading composer repositories with package information
Downloading https://packagist.org/packages.json
Writing C:/Users/Ghaleon/AppData/Local/Composer/repo/https---packagist.org/packa
ges.json into cache
Updating dependencies (including require-dev)
Reading C:/Users/Ghaleon/AppData/Local/Composer/repo/https---packagist.org/p-pro
vider-2013.json from cache
Reading C:/Users/Ghaleon/AppData/Local/Composer/repo/https---packagist.org/p-pro
vider-2014.json from cache
Reading C:/Users/Ghaleon/AppData/Local/Composer/repo/https---packagist.org/p-pro
vider-2015.json from cache
Reading C:/Users/Ghaleon/AppData/Local/Composer/repo/https---packagist.org/p-pro
vider-2016.json from cache
Reading C:/Users/Ghaleon/AppData/Local/Composer/repo/https---packagist.org/p-pro
vider-2016-10.json from cache
Downloading http://packagist.org/p/provider-2017-01%24d88eddadd51717e910cd1bad29
89204217e7add9448808859860c1520b3d294d.json

I'm extremely frustrated. I don't know what half of the geek speak means. All I want is the ability to use two extensions on my MediaWiki extension. Semantic Breadcrumb Links and Semantic Extra Special Properties.

And nobody on the Internet seems to be able to tell me how I can get these two installed, without a week spent learning CommandLine stuff and Composer commands.

**Comment by Simperfit** [comment]
If you already have both require you just need to do a composer install wi
^à

**Comment by frvge** [comment]
Looks like you don't have a composer.json file in the root folder of your project.

Make a backup of the current composer.json file, just in case, and then remove the one that you have to start with a clean slate.
Make a new composer.json in `C:\xampp\htdocs\zephyr`, like so: `composer init`. This will ask you some questions. I think you can just use the defaults. This will tell composer that your folder is the root of a new project.

Afterwards, you can add the new requirements via the command you already pasted: `composer require mediawiki/semantic-extra-special-properties "~1.5" -vvv` .

Then run `composer install`. This can take a bit of time, but shouldn't take more than a few minutes.

I hope this helps.

**Comment by GhaleonZ** [comment]
Composer.json is in the Zephyr folder. It has the require SESP and SBL in 
it.
 
I tried running Composer Install. It ran for hours. Telling me I didn't 
have a  Global composer.json in the Roaming folder. Then proceeded to 
download a TON of JSON files and stuff them into 
AppData/Local/Composer/repo
 
And they all are stuff I had in a vendor folder. But yeah, it ran for 
at least 4 or 5 hours and never once came up about packages/installing or 
anything else.
 
Yesterday I downloaded ComposerCat, the GUI for Composer. When directed to 
Zephyr it brings up the SESP/SBL in the top right corner, saying Pending 
Installation. the Require-Dev part below that is empty.
 
But CC will not run right on my PC now because I'm back on dialup. I'm 
going to try it again at the local library to see if it will function right on 
my laptop. But that won't be until Thursday.10/2/2017 9:26 AM Frank van 
Gemeren (notifications@github.com) 

  Looks like you don't have a composer.json file in the root folder of your 
  project.
  Make a backup of the current composer.json file, just in case, and then 
  remove the one that you have to start with a clean slate.Make a new 
  composer.json in C:\xampp\htdocs\zephyr, like so: composer 
  init. This will ask you some questions. I think you can just use the 
  defaults. This will tell composer that your folder is the root of a new 
  project.
  Afterwards, you can add the new requirements via the command you already 
  pasted: composer require mediawiki/semantic-extra-special-properties 
  "~1.5" -vvv .
  Then run composer install. This can take a bit of time, but 
  shouldn't take more than a few minutes.
  I hope this helps.
  —You 
  are receiving this because you authored the thread.Reply to this email 
  directly, view 
  it on GitHub, or mute 
  the thread.
  
  
  
  
  {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/composer/composer","title":"composer/composer","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/composer/composer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@frvge in #6715: Looks like you don't have a composer.json file in the root folder of your project.\r\n\r\nMake a backup of the current composer.json file, just in case, and then remove the one that you have to start with a clean slate.\r\nMake a new composer.json in `C:\\xampp\\htdocs\\zephyr`, like so: `composer init`. This will ask you some questions. I think you can just use the defaults. This will tell composer that your folder is the root of a new project.\r\n\r\nAfterwards, you can add the new requirements via the command you already pasted: `composer require mediawiki/semantic-extra-special-properties \"~1.5\" -vvv` .\r\n\r\nThen run `composer install`. This can take a bit of time, but shouldn't take more than a few minutes.\r\n\r\nI hope this helps."}],"action":{"name":"View Issue","url":"https://github.com/composer/composer/issues/6715#issuecomment-333533528"}}}

**Comment by Seldaek** [comment]
Automatically closing as this has not received any updates in a while. Please re-open if it is still relevant.
