### ISSUE TITLE
Composer requiring a minimum version of composer

### ISSUE THREAD

**Issue by rjgwiz** [composer/composer#6718]
Is it possible for a `composer.json` file to enforce a minimum version of composer itself?

I've searched through the issue queue and across Google and could not find anything on this.

The use case is: developers collaborating on a project who are using older versions of composer can lead to differences and inconsistencies in `composer.lock` (timestamp format, other "metadata"). Requiring a composer version or minimum version would alleviate that. e.g.:

```
"require": {
        "composer": "^1.5.2"
}
```

**Comment by Tobion** [comment]
I've experienced such differences as well. But I don't think it's worth to add in composer itself. You can solve this very easily yourself by writing a composer listener that then simply checks the composer version https://github.com/composer/composer/blob/1.5.2/src/Composer/Composer.php#L32 and prints a warning or whatever.

**Comment by rjgwiz** [comment]
Good idea, `Composer::VERSION` will work. 

By composer listener are you talking about a [script](https://getcomposer.org/doc/articles/scripts.md)?

**Comment by Tobion** [comment]
yes

**Comment by stof** [comment]
This is not possible currently (and adding this feature would not prevent people from using any of the existing versions which don't have this check).
I agree with @Tobion that a composer script displaying a warning is probably enough in most cases.

**Comment by rjgwiz** [comment]
Thanks, closing. I plan to build this out and share an example.
