### ISSUE TITLE
Autoloader optimizer is skipping helpers/ directory in yiisoft/yii2 package

### ISSUE THREAD

**Issue by brandonkelly** [composer/composer#6721]
My `composer.json`:

```json
{
  "provide": {
    "bower-asset/bootstrap": "3.3.* | 3.2.* | 3.1.*",
    "bower-asset/jquery": "2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable",
    "bower-asset/jquery.inputmask": "~3.2.2 | ~3.3.5",
    "bower-asset/punycode": "1.3.*",
    "bower-asset/yii2-pjax": "~2.0.1"
  },
  "require": {
    "yiisoft/yii2": "^2.0"
  }
}
```

_(The `provide` bit will prevent you from needing to install [fxp/composer-asset-plugin](https://packagist.org/packages/fxp/composer-asset-plugin); loading front-end assets are not relevant to this issue.)_

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run these commands:

```
> composer install
> composer dump-autoload -o
```

Everything works, _except_ for some reason the classes in `vendor/yiisoft/yii2/helpers/` are not included in the classmap in `vendor/composer/autoload_classmap.php`.

Normal (non-optimized) autoloading works fine; `Composer\Autoload\ClassLoader::findFile()` has no trouble locating the `yii\helpers\*` classes at runtime (as long as the classmap isn’t authoritative, of course).

Environment info:

- OS: Ubuntu 16.04.2 LTS
- Composer version: 1.5.2
- PHP version: 7.1.3

**Comment by stof** [comment]
I just tried this, and the helpers classes are part of the generated classmap.

**Comment by khalwat** [comment]
Works fine here, even after a clean `composer install` and manually running `composer dump-autoload -o`

- OS: Ubuntu 16.04.2 LTS
- Composer version: 1.5.0 2017-08-08 11:08:04
- PHP version: PHP 7.1.10-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Sep 29 2017 17:04:25) ( NTS )

**Comment by brandonkelly** [comment]
Well this is bizarre. I just tried running the AutoloadGenerator from source so I could step through it with Xdebug, and it worked correctly for the `yii\helpers` classes. And of course now `composer dump-autoload -o` is working correctly as well. No idea why it was skipping that `helpers/` folder earlier, but I guess it was a fluke.
