### ISSUE TITLE
Autoloader files are not generated correctly when composer.json is not in the root directory

### ISSUE THREAD

**Issue by Gitward** [composer/composer#6723]
My `composer.json`:

```json
{
  "name": "acme/website",
  "require": {
  },
  "require-dev": {
  },
  "config": {
    "vendor-dir": "Project/lib/"
  },
  "autoload": {
    "psr-4": {"ACME\\": "src/"}
  }
}
```

* `Project/` is the directory I upload to the server
* `Project/src/` contains my own class files that should be loaded using the autoloader of composer
* `Project/lib/` contains dependecies installed using composer
* `composer.json` is NOT in the folder `Project/`, but in the root directory of my git repository

Running `php composer.phar dump-autoload` creates `Project/lib/composer/autoload_static.php` with the content:

```php
<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite08b862a173387243eafaeea90b76eb4
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'ACME\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ACME\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite08b862a173387243eafaeea90b76eb4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite08b862a173387243eafaeea90b76eb4::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
```

The line ` 0 => __DIR__ . '/../../..' . '/src',` should be ` 0 => __DIR__ . '/../..' . '/src',` to get the autoloader load the correct classes.

It seems to me that Composer can't handle that my `composer.json` is not in the root directory of the output files. **How can I instruct Composer to use `Project/` as the root directory, when building the autoloader files?**

**Comment by stof** [comment]
Well, paths in the `autoload` section is relative to the composer.json location. So the generated path is totally fine according to your config (but your config is not fine according to your expectation on the project layout)

**Comment by Gitward** [comment]
@stof: What is the reason behind generating th paths relative to the `composer.json` instead of generating them relative to the autoload-file/vendor-folder? I my opinion **the paths should be relative to the vendor-folder**. Otherwise you have to put the composer.json to the root-directory - and this is a restriction which is not necessary.

**Comment by sboekhoff** [comment]
You could try:

```json
{
  "name": "acme/website",
  "require": {
  },
  "require-dev": {
  },
  "config": {
    "vendor-dir": "lib/"
  },
  "autoload": {
    "psr-4": {"ACME\\": "src/"}
  },
  "scripts": {
    "pre-update-cmd": "if [ -d 'Project/lib' ]; then mv Project/lib lib; fi",
    "pre-install-cmd": "if [ -d 'Project/lib' ]; then mv Project/lib lib; fi",
    "pre-autoload-dump": "if [ -d 'Project/lib' ]; then mv Project/lib lib; fi",
    "post-update-cmd": "if [ -d 'lib' ]; then mv lib Project/lib; fi",
    "post-install-cmd": "if [ -d 'lib' ]; then mv lib Project/lib; fi",
    "post-autoload-dump": "if [ -d 'lib' ]; then mv lib Project/lib; fi"
  }
}
```

Or arrange yourself with the requirements of Composer and move the `Composer.json` to the root of your sources.

**Comment by Seldaek** [comment]
The point @stof was making is the autoload config is wrong..

```
{
  [...]
  "autoload": {
    "psr-4": {"ACME\\": "src/"}
  }
}
```

Should be:


```
{
  [...]
  "autoload": {
    "psr-4": {"ACME\\": "Project/src/"}
  }
}
```
