### ISSUE TITLE
Downloading Composer to folder on Windows computer.

### ISSUE THREAD

**Issue by WebDevGuy2143** [composer/composer#6724]
Hello, I am having trouble installing composer to a specified folder using xampp on my windows computer. I've tried following the instructions, but I must not be doing it right. Can I get a step by step instructional on how to do this? I don't use command prompt very often.

**Comment by concept-core** [comment]
@WebDevGuy2143 not sure which example you followed but it should be pretty simple.
Please look at the installer section : https://getcomposer.org/doc/00-intro.md#using-the-installer

**Comment by Seldaek** [comment]
Automatically closing as this has not received any updates in a while. Please re-open if it is still relevant.
