### ISSUE TITLE
Cannot install composer on windows 7 / Wamp 3

### ISSUE THREAD

**Issue by phil123456** [composer/composer#6725]
Hello,

I am new to composer and I have troubles installing it on windows

**ERROR** :

```
The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
failed to open stream: Cannot connect to HTTPS server through proxy
```

**I TRIED** :

I downloaded http://curl.haxx.se/ca/cacert.pem
I changed my php.ini file but I still the same error

```
[curl]
curl.cainfo ="D:/WORK/wamp64/cacert.pem"
[openssl]
openssl.cafile="D:/WORK/wamp64/cacert.pem"
openssl.capath="D:/WORK/wamp64/"
```
but it does not seem to work, 

I have set an env variable SSL_CERT_FILE to point to the cert file, it doesnt solve the issue

the below values dont make any sens on windows and the ca file and folder dont appear to be setup even after restarting wamp

```
d:\>php.exe -r "print_r(openssl_get_cert_locations());"
Array
(
    [default_cert_file] => c:/usr/local/ssl/cert.pem
    [default_cert_file_env] => SSL_CERT_FILE
    [default_cert_dir] => c:/usr/local/ssl/certs
    [default_cert_dir_env] => SSL_CERT_DIR
    [default_private_dir] => c:/usr/local/ssl/private
    [default_default_cert_area] => c:/usr/local/ssl
    [ini_cafile] =>
    [ini_capath] =>
)
```

what can I do more to make this work ?

thanks

**Comment by Seldaek** [comment]
Seems like the issue is you're stuck to SSLv3 which is super old. Maybe try to update to a newer PHP version?

**Comment by phil123456** [comment]
I use wamp 3 php 7

**Comment by Seldaek** [comment]
Then maybe it comes with an outdated openssl dll
