### ISSUE TITLE
Installed.json is no longer consulted for comparing references on install?

### ISSUE THREAD

**Issue by dorxy** [composer/composer#6726]
Within our company we have various packages that are used throughout several projects. As these packages are also in development most of our developers use a symlink within the /vendor/our-company-name directory of a project. This way we can verify new functionality within the packages for more than one project, and use this symlinked folder as VCS root when contributing.

The 'problem' we have is that when project X uses version 1.3 of package Y and project Z uses version 1.4, only updating dependencies within the projects updates the HEAD of the packages. We used to edit the installed.json file reference for those packages to ensure they are checked out at the correct reference but this no longer seems to work. Manually checking out these dependencies per project can be tedious.

Our script checks installed.json's packages and when an installed package of a repository is a git repository itself, checks their current HEAD versus the installed.jsons version and updates the installed.json file when they are not equal. Unfortunately `composer install` does nothing when these changes are made.

I'm pretty sure this is not regular usage within composer and I'm not sure if this is anything that should be supported. I am however curious if contributors of composer or other developers have an idea on how to solve this process. If anyone suggests a solution that should/might be implemented within composer I could contribute and/or test.

**Comment by Seldaek** [comment]
Have you tried updating the composer.lock file? Because that's what will be applied when you run `composer install`.

**Comment by Seldaek** [comment]
Also maybe check the [path repository](https://getcomposer.org/doc/05-repositories.md#path) instead of managing symlinks yourself. That might result in less need for hand-managing this.

**Comment by dorxy** [comment]
Most of the times we don’t want to update the composer.lock file, for example when hotfixing. The path repository seems interesting, but that would only work locally, as deploying would have to check out the repositories from our own satis instance instead of local directories. In the meantime I’ve written a small script which does what I want, maybe I can add it here for more context on what I’m trying to achieve?

**Comment by stof** [comment]
`composer install` will install the reference which is locked. So if you don't update it when you want to install a different commit, things won't work.

installed.json is never a source of truth for what should be installed at the end of `composer install`

**Comment by dorxy** [comment]
It doesn't install the reference which is locked necessarily, it should, in my opinion, but in our case it ignores the actual commit that is checked out. 

Say I have `app/x` with a `composer.lock` containing `package/y` at commit `abc`.
`composer install` will install the required package at `abc`, but if I then manually (or through another `composer install` of `app/k` which uses the same symlinked directory for `package/y`) change the commit on which `package/y` is checked out, `composer install` will **not** checkout `package/y` on commit `abc` for `app/x` again, it will do nothing with `package/y`. This is my issue, I hope that is clear.

This might be something that is not possible to 'fix', or not even seen as an issue. If so, I'll have to solve my problem otherwise.

**Comment by Seldaek** [comment]
I see, indeed that is the case, we compare what's in the lock file with what's in installed.json. If you mess with the vendor dir directly you void the warranty :) That's not something we can fix comprehensively as you might not even have git data in the vendor dir so it's just recommended against and if you want to do it then you have to take care of keeping things sane yourself.
