### ISSUE TITLE
Install cannot succeed with Convenant Eyes installed

### ISSUE THREAD

**Issue by genyded** [composer/composer#6732]
I spent days isolating this and it seems that if http://www.covenanteyes.com/ is installed, the composer install will fail with. Covenant eyes is an internet monitoring software that uses a proxy and that proxy in intentionally not exposed so that it cannot be disabled or bypassed. That means there is no way to provide proxy info to Composer. You can manually install and get the phar working, but then any package installs fail for the same reason (unless you bypass TLS which defeats the whole point and is a huge security risk).

Covenant Eyes is required where I work, so if there is no way to resolve comparability with Composer, we cannot use composer, which means we cannot use Yii (at least not with composer which sucks), which means we have to seek an alternate architectural solution for our app - which again sucks.

**Comment by Seldaek** [comment]
Wow.. quite the tag line on that product :|

Anyway, nothing we can do I believe if a proxy messes up traffic.. Your best bet is to disable tls verification I guess, or convince your boss that the risk of employees watching porn is maybe not as bad as the sure fact of blocking the entire development team from getting their job done.
