### ISSUE TITLE
When restarting to disable debugging, display a notice

### ISSUE THREAD

**Issue by deviantintegral** [composer/composer#6733]
I understand why `COMPOSER_ALLOW_XDEBUG` exists - it's a nice performance fix for locals. However, it's totally confusing when you actually want to debug composer itself. It's not a common pattern with other PHP apps, and it's easy to miss unless you debug composer from it's entrypoint.

Could we throw a notice when we restart the process without debugging? Or, is there a way to detect not just that xdebug is loaded, but has an active connection, and skip the restart?

**Comment by Seldaek** [comment]
If there is a way to detect that xdebug is currently active (as in active debugging or profiling session), then yes we could skip the restart. I don't think we want to throw a notice or any output though. Most people that'd need to debug this are aware of the fact, and I wouldn't want to nag every other user on every composer run.

**Comment by deviantintegral** [comment]
I'm not seeing any function at the [function list](https://xdebug.org/docs/all_functions) that returns any status info about an active debug connection.

What if the notice was a one-time warning that only showed the first time composer needs to restart?

**Comment by Seldaek** [comment]
I don't see much value in that really, as it requires us to keep track of that state and if you saw a warning 5 months ago and you're now trying to debug it you probably wouldn't remember so it's added complexity with little added value. I don't think this is such a frequent problem as not a lot of people dive in with a debugger.
