### ISSUE TITLE
Composer to download content from src folder only

### ISSUE THREAD

**Issue by vbezruchkin** [composer/composer#6737]
Greetings,

I wonder if you have plans to implement a flag to download the source files only. For example I would like to distribute the project with some composer packages directly in the package file.  I am not sure if it's a good idea to keep all the other stuff like unit tests, docs, etc. alongside with the package. So technically I only want packages to be downloaded with src/ folder.

Can I achieve this now? 

Thanks

**Comment by pxgamer** [comment]
This is where you'd use a `.gitattributes` file in your repo with [`export-ignore`](https://git-scm.com/docs/git-archive#git-archive-export-ignore).

Then when it does the dist exports, it will ignore the specified directories/files. I doubt Composer would implement this as different developers have different directories for tests, etc. So it should be down to the developer.

Example: https://github.com/laravel/framework/blob/master/.gitattributes
More info: https://www.kernel.org/pub/software/scm/git/docs/gitattributes.html

**Comment by vbezruchkin** [comment]
Hi,

Thanks for the explanation though I don't think it really helps in my case. I do think it has nothing to do with git, as the task is more related to composer itself and it's classic files/folders structure. Most developers put source code in src/ folder and when we run composer update, it would be nice to get files from this folder without any updates of docs, etc. 

Thanks again

**Comment by pxgamer** [comment]
A lot of projects still put source files in a `lib` directory.

I know the majority now use the `src` directory, but Composer should be able to cover all possibilities.

Considering that Composer by default uses a dist release, personally I think it's better for Composer to be flexible and have the developer control what gets included in a dist.

Also, sometimes you want to include tests, and non source files. I guess if it had an option such as `--src-only` where the developer could specify source files/directories in their JSON, that may help.

I guess you could make a PR and see what the core devs think. :+1:

**Comment by vbezruchkin** [comment]
Yes, exactly! Thanks for the consideration!

It would be perfect if devs could control what files they need to fetch while running composer commands. In this case software companies, that produce a stand-alone software package that relies on some composer libraries, would be able to get source files only and don't bloat their installation package with examples, docs, unit tests (in case they are not used). Sometimes software developers are rather limited in terms of hosting access, customers skills, etc. so it's much easier to deliver the full-featured solution with all necessary libraries included.

Thanks again!
