### ISSUE TITLE
Run update without downloading packages.

### ISSUE THREAD

**Issue by thom8** [composer/composer#6747]
Wondering if there's a way I can run `composer update` to update the lock file but not download packages. The idea being that you'd need to do a separate `install` to actually retrieve the updates

There's `composer update --dry-run` but this doesn't update the lock file also `composer update --lock` but this doesn't actually update packages.

For background as to why, I'm working on an openfaas endpoint which would be a composer API but doesn't need to download packages. - https://github.com/thom8/faas-composer

The primary reason for the service is that running composer updates in locations with very poor network latency can take a very long time, but also you can run composer commands via curl without PHP or composer installed.

**Comment by naderman** [comment]
This is currently only doable by using custom PHP code that interacts with the installer object.

**Comment by thom8** [comment]
Thanks @naderman, was hoping to get away which building directly from the offical composer container, to allow for easy updates -- https://github.com/thom8/faas-composer/blob/master/Dockerfile#L1

but will take a look how I could cleanly extend the container with some custom PHP.

**Comment by thom8** [comment]
Just a thought, as a workaround this could be done as a custom global plugin which overrides and bypasses the download.

**Comment by thom8** [comment]
Moving this issue over to https://github.com/thom8/faas-composer/issues/4
