### ISSUE TITLE
Issue of SSL

### ISSUE THREAD

**Issue by vikash12345** [composer/composer#6749]
Output of `composer diagnose`:
...PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
 error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in /app/vendor/openaustralia/scraperwiki/simple_html_dom.php on line 75
 PHP Warning:  file_get_contents(): Failed to enable crypto in /app/vendor/openaustralia/scraperwiki/simple_html_dom.php on line 75
 PHP Warning:  file_get_contents(https://putusan.mahkamahagung.go.id/putusan/af8dda3bd542f23d4139e3df6c209a95): failed to open stream: operation failed in /app/vendor/openaustralia/scraperwiki/simple_html_dom.php on line 75
 PHP Fatal error:  Call to a member function find() on boolean in /app/scraper.php on line 21...
```

This is my scraper link 
https://github.com/vikash12345/Indonesia_Litigation/blob/master/scraper.php

its working fine on my local machine but not working in morph.io

**Comment by alcohol** [comment]
Not a composer issue.
