### ISSUE TITLE
single pipe in version constraint, undocumented or buggy?

### ISSUE THREAD

**Issue by joachim-n** [composer/composer#6755]
My `composer.json`:

```json
        "drush/drush": "~8.0|^9.0.0-beta7",

```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer validate
```

I get the following output:

```
./composer.json is valid
```

And I expected this to happen:

The use of the | (single pipe) symbol is not documented at https://getcomposer.org/doc/articles/versions.md#caret-version-range-. Therefore, either the documentation has an error, or 'composer validate' does.

**Comment by stof** [comment]
Well, a single pipe is the older OR operator, just like AND can be done either by a comma or just by putting spaces.
The doc at https://getcomposer.org/doc/articles/versions.md#version-range has been simplified a while ago to show only the recommended alternative for the OR operator (the one being described in the semver spec).

**Comment by joachim-n** [comment]
> The doc at https://getcomposer.org/doc/articles/versions.md#version-range has been simplified a while ago to show only the recommended alternative for the OR operator (the one being described in the semver spec).

That's a mistake. Docs should still mention deprecated features, while stating that they are deprecated. Otherwise, users who encounter deprecated features in use won't be able to understand them.

**Comment by alcohol** [comment]
@joachim-n opinions vary.

We prefer not to pollute the documentation with details that are no longer relevant.

**Comment by joachim-n** [comment]
It's relevant in that users may encounter it in libraries that still use it in their composer.json files, and then need to understand what it means!

**Comment by alcohol** [comment]
We cannot wait for everyone to update their files/libraries. Some of those never will. So no, it is not relevant. Not anymore. Also, the amount of times people actually run into this is insignificant.

**Comment by fritzmg** [comment]
Does Composer 2.x still support single pipe ORs, or will the packages that still use the single piples have to be updated in order to work with Composer 2.x?

**Comment by Seldaek** [comment]
We can not ever remove this or it'd break existing versions, we can only tell you || is preferred now :)

**Comment by fritzmg** [comment]
Well, following semantic versioning, 2.x can have breaking changes, that's why I am asking ;)

**Comment by Seldaek** [comment]
Of course but we are not interested in breaking the whole ecosystem that'd be slightly counter productive.

**Comment by nicholsonjf** [comment]
I just encountered a single pipe and looked to the versions doc for an explanation but it appears this was left out intentionally. What is the downside to putting a note in the doc explaining this? It seems more harmful to the community to pretend that single pipe was never and is not currently valid.

**Comment by Seldaek** [comment]
Yeah a short footnote next to `||` would be fine IMO, if you like to send a PR :)

**Comment by nicholsonjf** [comment]
@Seldaek I will, thank you :)
