### ISSUE TITLE
Simulate php version via command line?

### ISSUE THREAD

**Issue by andig** [composer/composer#6757]
My problem is upgrading of a single dependency to a newer version while maintaining php 5.6 compatibility. I do not have php5 on my dev machine. 

It would be nice if config.platform could be set via command line to ensure composer keeps and checks 5.6 compatibility during the upgrade or require operation.

**Comment by stof** [comment]
you can set the platform config in your system-level config file before running the command (and remove it after if you don't need it anymore).

Composer does not have a way to set it for the current command only.

**Comment by andig** [comment]
Great! I wasn‘t even aware of the global config file.
