### ISSUE TITLE
Composer could not find the config file

### ISSUE THREAD

**Issue by 68696c6c** [composer/composer#6759]
My `composer.json`:

```
{
  "name": "laravel/laravel",
  "description": "The Laravel Framework.",
  "keywords": [
    "framework",
    "laravel"
  ],
  "license": "MIT",
  "type": "project",
  "require": {
    "php": ">=7.0.0",
    "fideloper/proxy": "~3.3",
    "laravel/framework": "5.5.*",
    "laravel/tinker": "~1.0"
  },
  "require-dev": {
    "filp/whoops": "~2.0",
    "fzaninotto/faker": "~1.4",
    "mockery/mockery": "0.9.*",
    "phpunit/phpunit": "~6.0"
  },
  "autoload": {
    "classmap": [
      "database/seeds",
      "database/factories"
    ],
    "psr-4": {
      "App\\": "app/"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "Tests\\": "tests/"
    }
  },
  "extra": {
    "laravel": {
      "dont-discover": [
      ]
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ],
    "post-create-project-cmd": [
      "@php artisan key:generate"
    ],
    "post-autoload-dump": [
      "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
      "@php artisan package:discover"
    ]
  },
  "config": {
    "preferred-install": "dist",
    "sort-packages": true,
    "optimize-autoloader": true
  }
}
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer install
```

I get the following output:

```
Composer could not find the config file: /Users/aaronhill/.composer/vendor/bin
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
```

And I expected this to happen:
Expected composer to install the dependancies since the project's composer.json file is present.

I'm using Composer version 1.5.2 on MacOS 10.12.6.  I've uninstalled and reinstalled Composer a couple of times trying to get this to work.  My ~/.composer directory appears to be missing the vendor directory mentioned in the error message, but I'm at a loss for why.

This is happening in a brand new Laravel project.  I've tried creating a new project from scratch by downloading the Laravel zip and have the same problem every time.  The `composer create-project` command just throws an error similar to the one above.

**Comment by valh1996** [comment]
same problem on windows...

**Comment by 68696c6c** [comment]
FWIW, I have two other Macs running the MacOS 10.12.x, all using php 7.1.  Neither of them have this issue.  One of them is using composer 1.4.2, so on my Mac that is having this problem, I switch to composer 1.4.2 and still had this issue.

**Comment by akupaka** [comment]
Is there a ~/.composer directory? I've installed Composer v.1.5.2 today and it has put its configuration files to ~/.config/composer/ not to ~/.composer like it was earlier on other machine. And the vendor directory is ~/.config/composer/vendor/ respectively.

**Comment by curry684** [comment]
> Composer could not find the config file: /Users/aaronhill/.composer/vendor/bin

That's supposed to be a directory, not a config file. It definitely seems to be some sort of configuration issue.

**Comment by Seldaek** [comment]
Automatically closing as this has not received any updates in a while. Please re-open if it is still relevant.

**Comment by dfmabbas** [comment]
+1

**Comment by RikardoVerdo** [comment]
I have the same problem on windows and linux mint when I try to create laravel project by composer create-project

**Comment by rashed-877** [comment]
Same problem I am facing now. Please help. I have re-installed composer, deleted environment variable but still I faced this.

**Comment by tecladopl** [comment]
for it was wrong executable path

**Comment by elepsis5** [comment]
> Please reopen as i have the same challenge, i am trying to install phpmailer using composer, and i get this same error.
> 
> `$ composer install Composer could not find the config file: C:\Users\chun_kingz\AppData\Roaming\Composer\vendor\bin To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section `

Try to **clear the registry**. The easiest way to use utillity like Reg Organizer and make search in registry string "C:\Users\chun_kingz\AppData\Roaming\Composer\vendor\bin" and delete it.
