### ISSUE TITLE
Hanging during provider downloads

### ISSUE THREAD

**Issue by kelunik** [composer/composer#6762]
Sometimes `composer update -vvv` just hangs while downloading files like

```
Downloading http://packagist.org/p/provider-2017-10%2496dfb6e4d2305925ee42dce611951d4c4f395cd397aa2b92f1095bec2c3e7459.json
```

I abort it then and restart it, then it runs maybe fine, maybe it hangs again. Usually it runs fine after several retries, because more and more of these provider updates are cached then, so the number of downloads where it could hang decreases with each run.

I'm usually using PHP 7.2 RCs. I haven't noticed such hangs with my system installation, which is PHP 7.0, but have only payed attention to that very recently.

```
Composer version 1.6-dev (edece864e7e4c668dcad6601df70777882d22116) 2017-09-19 08:42:10
```

If anyone is also experiencing such hangs, which PHP version do you use?

**Comment by nurasto** [comment]
I am having the same problem. I am using Composer 1.5.2 with PHP 7.1.11 debsury

`[77.3MB/1.70s] Downloading http://packagist.org/p/provider-2017-07%24e29efb2e00d2200045158ef7c4e9a2c71706b1404f1acb1e1db0c109806487a0.json[94.2MB/160.19s] Writing /home/dev/.cache/composer/repo/https---packagist.org/p-provider-2017-07.json into cache
[95.1MB/160.24s] Downloading http://packagist.org/p/provider-2017-10%2466b0a67751e626c2d6878e0326fe53392e64ec0b06bbc8b589f816a6f5ffb7f2.json
[103.9MB/229.32s] Writing /home/dev/.cache/composer/repo/https---packagist.org/p-provider-2017-10.json into cache
[101.5MB/229.36s] Reading /home/dev/.cache/composer/repo/https---packagist.org/p-provider-archived.json from cache`

**Comment by mrksdiehl** [comment]
I am having this issue as well. Opening this file in the browser will load it in a matter of seconds. In composer require, install or update will take forever or just won't finish at all.

    Downloading https://packagist.org/p/provider-
    2016%24cd1b64e249ed0fa1ca3397cdbbe7e15d6ecac3e1c12883d41c77bdb83704f0a4.json

**Comment by kelunik** [comment]
@mrksdiehl Ctrl+C and repeat always solved the issue for me. But currently I'm no longer having this issue.

**Comment by rmott-littler** [comment]
the solution for me came from https://debril.org/how-to-fix-composers-slowness.html:
`$ composer config --global repo.packagist composer https://packagist.org`
but why?  what is happening that it nearly chokes and dies on http but https goes fine?  something with packagist.org's 307 redirect?

**Comment by allmanaj** [comment]
> the solution for me came from https://debril.org/how-to-fix-composers-slowness.html:
> `$ composer config --global repo.packagist composer https://packagist.org`
> but why? what is happening that it nearly chokes and dies on http but https goes fine? something with packagist.org's 307 redirect?

This solved my issue thanks!

**Comment by 247webs** [comment]
> the solution for me came from https://debril.org/how-to-fix-composers-slowness.html:
> `$ composer config --global repo.packagist composer https://packagist.org`
> but why? what is happening that it nearly chokes and dies on http but https goes fine? something with packagist.org's 307 redirect?

Works for me. Thanks!

**Comment by Seldaek** [comment]
Should be fixed by composer 2 as it uses https always, no more need to redefine the packagist repo.
