### ISSUE TITLE
Composer tries to install dependencies of dependencies that do not match the PHP minimum version of my package

### ISSUE THREAD

**Issue by jclaveau** [composer/composer#6767]
My `composer.json`:

```json
{
    "name": "jclaveau/php-social-video",
    "description": "Library to ease handling of videos from social networks.",
    "license": "MIT",
    "keywords": ["youtube", "dailymotion", "vimeo", "facebook", "twitch"],
    "authors": [
        {
            "name": "Jean Claveau",
            "role": "Developer"
        },
        {
            "name": "lingtalfi",
            "role": "Developer"
        }
    ],
    "autoload": {
        "psr-4" : {
            "JClaveau\\SocialVideo\\" : "src"
        }
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/jclaveau/php-visibility-violator"
        }
    ],
    "require-dev": {
        "phpunit/phpunit": "4.8.*",
        "jclaveau/php-visibility-violator": "dev-master",
        "evert/phpdoc-md": "~0.2.0",
        "phpdocumentor/phpdocumentor": "~2.8.0"
    },
    "require": {
        "php": ">=5.5.0"
    }
}
```

Output of `composer diagnose`:
This is the output of my local composer diagnose run with PHP 5.6 and I've not been able to run it in Travis-CI due to "Missing pubkey for tags verification" and then
"Public keys can not be fetched in non-interactive mode, please run Composer interactively" which is not feasible in Travis environment.

```
jean@jean-Lenovo-G580:~/dev/mediabong/apps/php-social-video$ composer diagnose
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Checking composer.json: OK
Checking platform settings: FAIL
The xdebug extension is loaded, this can slow down Composer a little.
 Disabling it when using Composer is recommended.

Checking git settings: OK
Checking http connectivity to packagist: Warning: Accessing packagist.org over http which is an insecure protocol.
OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
```

When I run this command with PHP 5.5:

```
composer install --no-interaction
```

I get the following output:
https://travis-ci.org/jclaveau/php-social-video/builds/293178633
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1

    - Installation request for doctrine/annotations v1.4.0 -> satisfiable by doctrine/annotations[v1.4.0].

    - doctrine/annotations v1.4.0 requires php ^5.6 || ^7.0 -> your PHP version (5.5.38) does not satisfy that requirement.

  Problem 2

    - Installation request for zendframework/zend-eventmanager 3.2.0 -> satisfiable by zendframework/zend-eventmanager[3.2.0].

    - zendframework/zend-eventmanager 3.2.0 requires php ^5.6 || ^7.0 -> your PHP version (5.5.38) does not satisfy that requirement.

  Problem 3

    - Installation request for zendframework/zend-i18n 2.7.4 -> satisfiable by zendframework/zend-i18n[2.7.4].

    - zendframework/zend-i18n 2.7.4 requires php ^7.0 || ^5.6 -> your PHP version (5.5.38) does not satisfy that requirement.

  Problem 4

    - Installation request for zendframework/zend-serializer 2.8.0 -> satisfiable by zendframework/zend-serializer[2.8.0].

    - zendframework/zend-serializer 2.8.0 requires php ^5.6 || ^7.0 -> your PHP version (5.5.38) does not satisfy that requirement.

  Problem 5

    - doctrine/annotations v1.4.0 requires php ^5.6 || ^7.0 -> your PHP version (5.5.38) does not satisfy that requirement.

    - jms/serializer 0.16.0 requires doctrine/annotations 1.* -> satisfiable by doctrine/annotations[v1.4.0].

    - Installation request for jms/serializer 0.16.0 -> satisfiable by jms/serializer[0.16.0].
```

And I expected this to happen:
exit with 0

I dug into issues reported by other people, found the solution of platform for php extensions compatibility issues and other threads but only one looks like corresponding to my problem:
https://stackoverflow.com/questions/32055527/composer-dependency-for-specified-php-version

Where it's said that we cannot choose dependencies depending on php versions and that the best option would be to make a dedicated branch for PHP 5.5 even if my code is fully compatible with this version.

This means basically: make my package much more complex for a composer issue.

Why a composer issue? Because composer tries to install dependencies of dependencies that do not match the PHP version requirement written in my... composer.json (which looks all but normal to me). 

Thus I found a workaround for this: adding the dependencies of dependencies that I need directly in my composer.json: 

```json
        "doctrine/annotations": "1.2.7",
        "zendframework/zend-eventmanager": "3.0.1",
        "zendframework/zend-i18n": "2.7.3",
        "zendframework/zend-serializer": "2.7.2"
```
instead of the automatically chosen versions: 
```json
        "doctrine/annotations": "1.4.0",
        "zendframework/zend-eventmanager": "3.2.0",
        "zendframework/zend-i18n": "2.7.4",
        "zendframework/zend-serializer": "2.8.0"
```

I wonder if there is a good reason for this behavior but I can't find one by myself so please, tell me if I missed something somewhere or how to proceed to fix it.

Thanks in advance,
Jean Claveau

**Comment by stof** [comment]
`composer install` will try to install whatever version was specified in the lock file. It is not allowed to use another version.
So what you need to do is make sure that you run `composer update` (which generates the lock file) on the PHP version that your project is targeting. If you cannot use the right PHP version, you can use the composer config to force a version different that the PHP runtime (but be careful about that if you end up running your code in a version different that the forced one, as things may be incompatible then, as they would be selected to be compatible with the version you are forcing): https://getcomposer.org/doc/06-config.md#platform

**Comment by jclaveau** [comment]
Thank you @stof for your quick answer.

Does this means that I MUST make a branch by PHP version to specify a different platform on each and have a different composer.lock for every PHP version I wan't my lib to be available for (which looks kind of insane btw)?

**Comment by jclaveau** [comment]
@stof I configured my composer.json platform option and ran composer update but the build still don't pass on PHP 5.5
https://travis-ci.org/jclaveau/php-social-video/jobs/293246005

```json
{
    "name": "jclaveau/php-social-video",
    "description": "Library to ease handling of videos from social networks.",
    "license": "MIT",
    "keywords": ["youtube", "dailymotion", "vimeo", "facebook", "twitch"],
    "authors": [
        {
            "name": "Jean Claveau",
            "role": "Developer"
        },
        {
            "name": "lingtalfi",
            "role": "Developer"
        }
    ],
    "autoload": {
        "psr-4" : {
            "JClaveau\\SocialVideo\\" : "src"
        }
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/jclaveau/php-visibility-violator"
        }
    ],
    "require-dev": {
        "phpunit/phpunit": "4.8.*",
        "jclaveau/php-visibility-violator": "dev-master",
        "evert/phpdoc-md": "~0.2.0",
        "phpdocumentor/phpdocumentor": "~2.8.0"
    },
    "require": {
        "php": ">=5.5.0"
    },
    "platform": {
        "php": "5.5"
    }
}
```

Is there something I missed?

**Comment by Jean85** [comment]
You're still using `composer install` instead of `composer update`.
An other solution could be removing the `platform` along with removing the committed `composer.lock` file. In this way, `composer install` will behave like a `composer update` (since lock is missing) and it will determine the needed packages depending on the current PHP version, not the `platform` forced one.

This is the right way to do CI on Travis with multiple PHP versions.

**Comment by jclaveau** [comment]
Heeeeeeeeee, that's it! I had been told, a while ago, that committing the composer.lock was a best practice to follow. I now understand why it's not (at least not always).

Thank you very much @Jean85, I wonder if an explicit error message would be useful to people in the same case but meanwhile, I got it.

Thanks again!

**Comment by jclaveau** [comment]
Glad to you: [![Dependency Status](https://www.versioneye.com/user/projects/59f33e0515f0d7003ff197c3/badge.svg?style=flat-square)](https://www.versioneye.com/user/projects/59f33e0515f0d7003ff197c3)

:)

**Comment by Jean85** [comment]
@jclaveau I have the .lock committed in a few of my project, but in CI I use `composer update` to ignore it in every build job, except the one in which I want it.

If it's simpler to you, no commited .lock it's the easier path to follow.

**Comment by jclaveau** [comment]
@Jean85 Interesting. Why is it still interesting to commit the .lock?

**Comment by stof** [comment]
@jclaveau committing the lock file is important for projects (rather than libraries), to be sure that the local development, the CI and the prod are running the same dependencies. But these are also cases where you generally don't need to bother about lots of different PHP versions (as you have one in prod, and should be using the same one in CI and locally).

For libraries, I generally don't commit it.
