### ISSUE TITLE
FEATURE: specify order of operations for "files" and "require" (load files before autoload)

### ISSUE THREAD

**Issue by fireproofsocks** [composer/composer#6768]
This is something that keeps coming up and I believe there is no clean solution for it other than a change at the composer level.  Imagine the following `composer.json`:

```json
{
  "files": ["helpers.php"],
  "require": {
    "laravel/framework": "5.4.*"
  }
}
```

where our custom `helpers.php` file defines alternatives to the Laravel helper functions (e.g. `redirect()`).  This is a common convention for helper functions where they are all nicely wrapped with a `function_exists` block with the expectation that they can be overridden, e.g.

```
if (! function_exists('redirect')) {
    function redirect() { /* ... */ }
}
```

This works fine for most day-to-day application operations because our application bootstraps using a line like this:

```
require_once __DIR__.'/helpers.php';
require __DIR__.'/vendor/autoload.php';
```

In other words, we are explicitly forcing our helper functions to be loaded first (before the Laravel helper functions that get loaded by classes in the "require" autoloading section). 

The problem really comes up when we try to use other PHP scripts like `phpunit`.  They don't know or care about our custom overrides, so (as expected), they simply include the composer `vendor/autoload.php` file.  However, the `autoload.php` file does NOT load up any of the files specified by the composer.json's `"files"` array until after it has loaded its classes.

**Expected result:**

I would expect that files listed in the `"files"` array would be loaded BEFORE any of the classes defined in the `"require"` section.  

**Actual result:**

Files listed in the `"files"` array are not loaded until AFTER the classes in the `"require"` section.

**Suggestion:**
Either the "files" array should be loaded first, or a new parameter should allow users to specify the order of operations in the includes so that these types of functional overrides can work without resorting to ugly hacks that usually involve editing files inside the `vendor/` directory or inside system-level binaries.

**Comment by alcohol** [comment]
I am not sure I understand the problem?

The "files" are loaded explicitly when a user requires or includes the `autoload.php` file. Classes are not loaded at this point. The autoloader that can resolve them is setup, nothing more.

Can you make a small reproducible example to demonstrate your exact problem?

**Comment by fireproofsocks** [comment]
Ah, you're right -- this was more subtle than I thought.  My specific problem has to do with a vendor's code (Laravel's specifically).  Nevermind!

**Comment by nanaya** [comment]
@fireproofsocks how did you fix it?

@alcohol laravel package also have some `"files"` defined in its composer file and those files are loaded first which includes some function definitions. That results in those functions getting defined first and thus can't be overridden anymore.

Composer loads/requires the files in these order:
1. laravel helper 1 (defines some functions)
2. laravel helper 2 (defines some more functions)
3. files defined in main `composer.json` (overriding some of laravel helpers) &larr; this doesn't work

What's needed is:
1. files defined in main `composer.json`
2. laravel helper 1 (defines some functions, excluding previously defined)
3. laravel helper 2 (defines some more functions, excluding previously defined)

**Comment by alcohol** [comment]
You're replying to a topic that is about something else. What you are looking for is a way to specify ordering for (or assign ordering to) all "files" autoload definitions. Please create a new issue.

**Comment by nanaya** [comment]
I believe that's what he originally asked about, though. Or at least a way to load `files` defined in main file before the ones in `require` specified in same `composer.json`.

**Comment by alcohol** [comment]
Not exactly.

**Comment by fireproofsocks** [comment]
I stumbled back into this again, but this time I dug in a bit more.  Again, the issue is that Laravel in particular defines a `helpers.php` file with some functions that we'd like to override -- they are wrapped in 'function_exists()` statements for this purpose.  So our `composer.json` file requires `laravel/framework` and we have a `"files": ["helpers.php"]` to include our custom helpers that overwrite some of the functions that exist in Laravel's `helpers.php`.  The filename "helpers" isn't important: we only need to define our own instances of the functions BEFORE Laravel's helpers get loaded.

However, no matter where we put the `files` declaration in our `composer.json`, the vendor packages seem to ALWAYS be loaded first.  Inside `vendor/composer/autoload_files.php` we see something like the following:

```
'f0906e6318348a765ffb6eb24e0d0938' => $vendorDir . '/laravel/framework/src/Illuminate/Foundation/helpers.php',
    '0d9bc4b9d4e9aeb9a29cccb6912fb09f' => $baseDir . '/helpers.php',
```

It's clear that the laravel/framework `helpers.php` is being loaded before our local `helpers.php`, so the end effect is that we can't overload the functions.

To clarify, @nanaya, that was exactly what I was talking about, and no, I did not find a solution, just some bad workarounds.

@alcohol here's how to reproduce the problem:

## helpers.php
```
<?php

function redirect($url = '/', $code = 302)
{
    header('Location: '.urldecode($url), true, $code);
    exit;
}
```
## composer.json
```
{
    "autoload": {
        "files": ["helpers.php"]
    },
    "require": {
        "laravel/framework": "^5.6"
    }
}
```

## app.php

```
<?php
require_once 'vendor/autoload.php';

print "Do something here...";
```

To reproduce, just run `php app.php`.  You'll get a fatal error:

```
Fatal error: Cannot redeclare redirect() (previously declared in vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:680) in helpers.php on line 7
```

I expected instead to just be able to run my simple program and have my `helpers.php` (and its files) loaded before the ones defined by the vendor package.

**Comment by dciancu** [comment]
The only solution for now is to require your `helpers.php` file before the Composer `autoload.php` file.
At least this is how I solved it for now.

**Comment by Ma-ve** [comment]
Up. We have a polyfill for getallheaders() ourselves, and we just included `aws/aws-sdk-php` which has a dependency on https://github.com/ralouphie/getallheaders, and that method apparently parses Content-Type different from our method, which breaks our flow.

**Comment by kareem2** [comment]
I had the same problem when using PHPUnit also, even if specifying the bootstrap file for PHPUnit, PHPUnit always load the `vendoer/autoload.php` file first and this makes the same issue you have had. 

As a workaround, I forked the PHPUnit package and updated the `src/vendor/my-forked-package/phpunit/phpunit` file by including my custom load file before loading the `vendoer/autoload.php`

```
if (\file_exists(__DIR__ . '/../../../phpunitCustomLoadFile.php')) {
    require_once __DIR__ . '/../../../phpunitCustomLoadFile.php';
}
```

The `src/vendor/my-forked-package/phpunit/phpunit` file will be like;

```
#!/usr/bin/env php
<?php declare(strict_types=1);
/*
 * This file is part of PHPUnit.
 *
 * (c) Sebastian Bergmann <sebastian@phpunit.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

if (version_compare('7.2.0', PHP_VERSION, '>')) {
    fwrite(
        STDERR,
        sprintf(
            'This version of PHPUnit is supported on PHP 7.2, PHP 7.3, and PHP 7.4.' . PHP_EOL .
            'You are using PHP %s (%s).' . PHP_EOL,
            PHP_VERSION,
            PHP_BINARY
        )
    );

    die(1);
}

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('PHPUNIT_COMPOSER_INSTALL', $file);

        break;
    }
}

unset($file);

if (!defined('PHPUNIT_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

$options = getopt('', array('prepend:'));

if (isset($options['prepend'])) {
    require $options['prepend'];
}

unset($options);

if (\file_exists(__DIR__ . '/../../../phpunitCustomLoadFile.php')) {
    require_once __DIR__ . '/../../../phpunitCustomLoadFile.php';
}

require PHPUNIT_COMPOSER_INSTALL;

PHPUnit\TextUI\Command::main();
```

As you see, the code will check if there is a file named `phpunitCustomLoadFile.php` that exists in the same directory that contains the `vendor` folder and loads it.

A possible improvemnt is to add this to the phpunit.xml file as a parameter.

**Comment by Seldaek** [comment]
IMO it'd be cleaner to do something like this:

create a `bin/phpunit` file with:

```
#!/usr/bin/env php
<?php

// add custom stuff
include __DIR__.'/../phpunitCustomLoadFile.php';

// run phpunit
include __DIR__.'/../vendor/phpunit/phpunit/phpunit';
```

Then you don't have to fork phpunit at all, you just have to call it via your wrapper script.

Similarly the case above by @fireproofsocks - you only need to include your `helpers.php` file *before* you include `vendor/autoload.php` to be able to overload the laravel functions IMO. There is nothing saying that `vendor/autoload.php` has to be the first included file.

**Comment by nanaya** [comment]
phpunit command has argument exactly for this purpose (`--prepend=path/to/preload.php`).

**Comment by kareem2** [comment]
@Seldaek 
You are right, it is cleaner, but when I tried it I got an error 
```
PHP Fatal error: strict_types declaration must be the very first statement in the script ....
```

Your suggestion guides me to copy the `vendor/phpunit/phpunit/phpunit` and inject my code and it works fine, Thanks

@nanaya 
I already tried that option, but it does not work for me, but now after reading your comment, I tried it more and it works, I found that I need to use it with the bootstrap option also, so, my command will look like:
`vendor/bin/phpunit  --prepend=phpunitCustomLoadFile.php --bootstrap=protected/tests/bootstrap.php protected/tests/`

`phpunitCustomLoadFile.php` will load the required php files, and the `bootstrap.php` will do another initialization after loading the `autolad.php` file, I belive that this can be also improved my moving the code of bootstrap into the `setUp` function.

@Seldaek and @nanaya 
Thank you very much.

**Comment by torian257x** [comment]
what's the state of this? I'm surprised and a bit shocked to see there is no way to specify load priority in composer.

**Comment by bancer** [comment]
@quasilyte it is not clear how https://github.com/VKCOM/kphp/pull/39 fixes this issue.

**Comment by bancer** [comment]
@quasilyte sorry, yes, you are right.

**Comment by Seldaek** [comment]
@joelmellon there's nothing saying everything has to be loaded by Composer? Why not include your own project helpers inside a bootstrap.php, which includes helpers and then includes vendor/autoload.php? That bootstrap can be used for PHPUnit and for your app's bootstrapping instead of vendor/autoloda.php, ensuring your helpers go first.

**Comment by joelmellon** [comment]
I agree. This is a feature request and it's closed. I've merely added my input, and offered my solution to help others. Go away.
