### ISSUE TITLE
No matching package found error

### ISSUE THREAD

**Issue by avg0043** [composer/composer#6769]
I have two Symfony projects: project-a (root project) and project-b.

My composer.json file from project-a contains:

```
{
  "name": "myprojects/project-a",
  "require": {
    "myprojects/project-b": "dev-master",
  },
  "repositories": [
        {
            "type": "vcs",
            "url":  "git@bitbucket.org:MYPROJECTS/project-b.git"
        }
    ]
}
```

And my composer.json from project-b:

```
{
  "name": "myprojects/project-b",
  "require": {
    "guzzlehttp/guzzle": "^6.3"
  }
}
```
I need to update project-b but when I execute the command `composer update myprojects/project-b` from project-a, I get this composer error:

```
[Composer\DependencyResolver\SolverProblemsException]

Problem 1

Installation request for myprojects/project-b dev-master -> satisfiable by myprojects/project-b[dev-master].
myprojects/project-b dev-master requires guzzlehttp/guzzle ^6.3 -> no matching package found.
Potential causes:

A typo in the package name
The package is not available in a stable-enough version according to your minimum-stability setting
```
I have tried solve this adding `"minimum-stability": "dev"` property to both composer.json files, but it doesn't works.. How can I solve this?

Thanks.

**Comment by avg0043** [comment]
composer clear cache and self-update solves my problem. I'm not using "minimum-stability": "dev" and all worked perfectly.

**Comment by neoacevedo** [comment]
I apologize to re-open it, but in my case, the error happens with a package:
A private package (hosted on bitbucket) requires another package type component, and it is also private (hosted on bitbucket). The error happens just in this dependency.

**Comment by nignatov** [comment]
I'm also experience the same problem like @neoacevedo
