### ISSUE TITLE
[feature request] reading working dir from composer.json

### ISSUE THREAD

**Issue by unhawkable** [composer/composer#6774]
Suppose we have a project in /var/home/project. but composer.json and composer.lock are in /var/home/project/lib/. Running "composer install" in /var/home/project would return "Composer could not find a composer.json file" error.
Would it be possible to implement a workaround so that a working dir could be specified in composer.json file? so that if we added a simple composer.json file in /var/home/project:

`{
  "config": {
    "working-dir": "lib/"
  }
}`

all composer commands would run as if the --working-dir=lib/ option was passed.

**Comment by marcing** [comment]
+1

**Comment by gaia-ovos** [comment]
+1

**Comment by TheFox** [comment]
+1

**Comment by Seldaek** [comment]
What about just specifying `vendor-dir` to be `lib/vendor`? That sounds like it'd achieve the same. Changing the working dir from the config isn't really easy as we read the composer.json from the working dir.. It sounds like a bunch of added complexity for very little value.

**Comment by unhawkable** [comment]
Thanks @Seldaek for your input. I have been expecting that it would not make sense for most. But we are dinosaurs still using svn and while checkouting the whole project on dev we checkout only a subdir on prod (and yeah we are using composer to install dependencies on prod while it is considered a bad practice). So now we are having composer.bat and composer.sh aliases in the root folder which first cd to the subfolder and call composer from there. Works, but still on *nix one have to call ./composer.sh instead of just "composer" in this case. (just wanted to avoid typing composer --working-dir=lib/ every time)
So until we move to git and CI and change our folder structure we are stuck with that I guess.
This is our case. I only thought that it could be also useful in some other cases other users may have. I did not have time to look into composer's code to hack a PR yet but maybe someday.

**Comment by Seldaek** [comment]
@unhawkable I don't get what you are saying though, because if you're checking out a subdir on prod, and your composer.json would be on the top level, then it wouldn't be checked out on prod so it wouldn't work either? Maybe I misunderstand..

**Comment by unhawkable** [comment]
Yes. So i put composer.json in the subfolder being checked out. (to have only one file which would work both on prod and dev). I don't have composer.json on the top level.

**Comment by Seldaek** [comment]
Ok so if you don't have a composer.json I don't know where you would even place that "working-dir" config option you suggested? :) Anyway yes I think the best is to just do cd or write a script for now and hopefully some day it fixes itself by migrating to git.
