### ISSUE TITLE
Ignoring .git directory when satisfying "composer require ..."

### ISSUE THREAD

**Issue by achinayoungwaubonsee** [composer/composer#6775]
We are using composer to manage our Drupal 8.3.7 installation. One of the modules we wish to add is drupal/menu_position. The composer.lock entry for this module is:
```
        {
            "name": "drupal/menu_position",
            "version": "dev-1.x",
            "source": {
                "type": "git",
                "url": "https://git.drupal.org/project/menu_position",
                "reference": "d134276b4bbd08b3c9678943d0225fbef7dd05b5"
            },
            "require": {
                "drupal/core": "~8.0"
            },
            ....
```
When composer downloads this module, it looks like it clones the https://git.drupal.org/project/menu_position repo to web/modules/contrib/menu_position. Unfortunately, we plan to check in all of our Drupal modules to our git repository and, unless we add web/modules/contrib/menu_position as a submodule/subtree of our git repo, we cannot track the drtupal/menu_position module. Is there a way for composer to manage drupal/menu_position but no include the .git directory when it downloads the module? No releases of this module have been made yet.

**Comment by alcohol** [comment]
If you are not using a dist release, then you will always get a source clone. No, you cannot avoid the `.git` directory in the latter scenario.

**Comment by achinayoungwaubonsee** [comment]
Ok, thank you.
