### ISSUE TITLE
memory limit

### ISSUE THREAD

**Issue by ecentinela** [composer/composer#6776]
composer seems not using the php -d flag for memory_limit.

In my installation of PHP / Symfony, I decreased the memory to 16M. Then, I launch composer with:

`php -d memory_limit=128M /usr/bin/composer install`

The output is giving me:

```
[RuntimeException]
  An error occurred when executing the "'cache:clear'" command:
  Fatal error: Allowed memory size of 16777216 bytes exhausted (tried to allocate 65536 bytes) in Unknown on line 0
```

- No composer plugins, no xdebug enabled.
- Composer 1.5.2

**Comment by alcohol** [comment]
Not a composer issue.

The cache:clear command looks to be a script or plugin running. It is not an action of composer itself (thus it is another process).
