### ISSUE TITLE
Feature request: Namespace interal functions and constants

### ISSUE THREAD

**Issue by Michal-sk** [composer/composer#6777]
Since we want composer to be as fast as possible, maybe we could namespace the internal functions and constants?

Couldn't find any other issue mentioning it. If interested i could make a pull request. There are multiple tools to achieve this:

- https://github.com/nilportugues/php-backslasher
- https://github.com/Roave/FunctionFQNReplacer 
- https://github.com/kelunik/fqn-check
- https://github.com/FriendsOfPHP/PHP-CS-Fixer (native_function_invocation )

**Comment by alcohol** [comment]
@Seldaek do you think this will have any significant impact? I suppose it couldn't make things worse, so we might as well?

**Comment by Michal-sk** [comment]
Thing to keep in mind is that the look of the code might get 'messier'.

**Comment by Michal-sk** [comment]
Is there a general way how you guys benchmark the composer package? I am running https://github.com/FriendsOfPHP/PHP-CS-Fixer/  at this moment and would like to do a benchmark afterwards. I have Blackfire so if there is any script i could run i could get some benchmarks online.

**Comment by alcohol** [comment]
There currently is not a predefined way to benchmark Composer.

We generally do not run php-cs-fixer against our entire codebase because that would invalidate/put a lot of existing pull-requests into a conflict state.

**Comment by Michal-sk** [comment]
i have ran it only with the specific rule which applies the '\'. How do you run benchmarks on the codebase? If there is a simple script i can run for the benchmark i could run that trouhg blackfire and publish the result.

**Comment by alcohol** [comment]
Like I said, I do not know of any way we run benchmarks ( I have never ran one myself ).

**Comment by Michal-sk** [comment]
Ok got it. If anyone has some suggestions is would love to hear them.

**Comment by Seldaek** [comment]
I don't think this makes enough of an impact to be measurable in the Composer context tbh.. And it makes the code way uglier than it needs to be, so I'd rather not.

**Comment by keradus** [comment]
at PHP CS Fixer, we got 5% boost on PHP 7.
what about not following it in codebase, but apply it just before running tests on CI and building phar file ?

**Comment by staabm** [comment]
When constants like PHP_VERSION etc. Opcache can eliminate dead code at compiletime which can have significant gains

**Comment by alcohol** [comment]
@Seldaek thoughts on above latest comments?

**Comment by Seldaek** [comment]
I still doubt we would see a significant gain. 5% is not that much, but PHPCSFixer does a lot more than Composer does in terms of computation. The solver loop we have is where most of the CPU stuff happens and that doesn't have a ton of code in the end. Maybe it'd be worth it there, I don't know. If someone measures it and proves it's worth it we can discuss again, but applying this to the whole code base still sounds pointless. And applying stuff at build time that modifies the code from a third party repo also doesn't sound very exciting to me tbh.

**Comment by Seldaek** [comment]
@staabm as for autoloading, if you use optimized autoloader (as you should if you care about perf), autoloading boils down to one isset() call. As isset is a language construct it seems you can't even prefix it with a \, so I'm not sure what we can improve there.

**Comment by keradus** [comment]
IMO, fair enough.


> And applying stuff at build time that modifies the code from a third party repo also doesn't sound very exciting to me tbh.

just a note - I bet you would enjoy doing anything in typescript, which requires transpiling via 3rd party tool to actually be able to execute it :D

**Comment by Michal-sk** [comment]
Just fyi, this did make it into Doctrine. In Doctrine instead of / a use is now used. Same result.

- https://github.com/doctrine/doctrine2/issues/6807#issuecomment-355865483
- https://github.com/doctrine/coding-standard/pull/15

**Comment by staabm** [comment]
@Michal-sk I guess we can convince Jordi only with a benchmark showing a actual substantial perf increase... would you be willing to provide a PR and do some benchmarks?

**Comment by Michal-sk** [comment]
@staabm i sure would. But i have asked multiple times how to benchmark composer, no one knew or could give me any advise. So if you have an idea on how to benchmark it i am more than happy to do it.
