### ISSUE TITLE
under windows composer did not see my bat-scripts

### ISSUE THREAD

**Issue by SailorMax** [composer/composer#6778]
My directory:

```
bin/                            // bin/ with my scripts
bin/php-cs-check
bin/php-cs-check.bat
vendor/bin/                     // bin/ of vendor libs
vendor/...
composer.json
```

My `composer.json`:

```json
{
    "scripts": {
        "check-syntax": ["bin/php-cs-check"]
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer check-syntax
```

I get the following output:

```
> bin/php-cs-check
'bin' is not recognized as an internal or external command,
operable program or batch file.
Script bin/php-cs-check handling the check-syntax event returned with error code 1
```

And I expected this to happen:
Executed script "bin/check-syntax.bat"

Under linux it work as expected. problem under Windows.

Composer version 1.5.2 2017-09-11 16:59:25

**Comment by stof** [comment]
folder separator is `\` on Windows, not `/`, this is what causing you issue here (as the command it looks for is `bin`, not `bin\check-syntax`)

**Comment by SailorMax** [comment]
I need it work on both OS.
Plus "bin\\php-cs-check" did not work also.

**Comment by avant1** [comment]
Try this one (double quotes around path to binary):
```
    "scripts": { 
        "check-syntax": [
            "\"bin/foo\""
        ] 
    }
```

It should work on both Windows and Linux. 
Double quotes are required to make this work on Windows with incorrect directory separator.

**Comment by SailorMax** [comment]
`Script "bin/foo" handling the check-code event returned with error code 255`

**Comment by SailorMax** [comment]
@avant1
Looks like it work! Thank you!

**Comment by Seldaek** [comment]
The best way to do this normally is to make sure the binaries are in the "bin-dir" you configure, and then just use "binary-name" like "php-cs-check" as the bin-dir gets added to the PATH.

**Comment by Tomicapo** [comment]
I'm trying this on Windows and it doesn't work. Any ideas?

```js
	"scripts": {
		"post-install-cmd": [
		"\"bin/cake migrations migrate\"",
```

Throws this error: 
> "bin/cake migrations migrate"
'"bin/cake migrations migrate"' is not recognized as an internal or external command, operable program or batch file.

**Comment by SailorMax** [comment]
@Tomicapo Based on error message try to remove arguments. Try just "bin/cake". Composer uses all string as command _name_.

**Comment by Tomicapo** [comment]
Yes! That worked. Thanks!
