### ISSUE TITLE
Install composer programmatically only downloads the composer phar

### ISSUE THREAD

**Issue by chrissound** [composer/composer#6782]
https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md

The script only downloads the phar file - it doesn't actually make it globally accessible - perhaps this should be titled with "Download composer ..." instead?

**Comment by alcohol** [comment]
I think that is because that page is mostly just an addendum to the main documentation pages about installing Composer. Usually users would not navigate there directly.

**Comment by Seldaek** [comment]
Yeah the thing is "installing" composer isn't really more than downloading the file. Making it globally accessible is left as an exercise for the reader :)
