### ISSUE TITLE
Move files fails after package extraction

### ISSUE THREAD

**Issue by TheFox** [composer/composer#6784]
It seems that sometimes Composer moves the wrong files/directory when I run `composer install`.

I'm using
- PHP 7.0.25 CLI,
- under Debian 9.2
- in a Docker container. So it runs under root.
- Composer version 1.5.2 2017-09-11 16:59:25

It doesn't matter if I use `unzip` or the zip PHP extention.

After I run `composer install` it fails, because I want to install Symfony 3.3.9. It fails because the Symfony source is under the wrong path: `vendor/symfony/symfony/symfony-symfony-a9d2f68`

The content of `vendor/symfony/symfony/symfony-symfony-a9d2f68/` should be unter `vendor/symfony/symfony/`, without `symfony-symfony-a9d2f68/`.

This behavior appears only when `vendor/` does not exist at all. When only `vendor/symfony/symfony/` does not exist and I run `composer install` it will be extracted to `vendor/symfony/symfony/` instead to `vendor/symfony/symfony/symfony-symfony-a9d2f68/`.

I debugged the newest version of Composer using `COMPOSER_ALLOW_XDEBUG=1 php ./composer/bin/composer install -vv`. I guess this is because in some cases [this condition](https://github.com/composer/composer/blob/bfed974ae969635e622c4844e5e69526d8459baf/src/Composer/Downloader/ArchiveDownloader.php#L55) fails.

---

**Edit**: This issue is because of Mac OS X. When you have the Finder open in `vendor/` (or sub-folder), it creates a `.DS_Store` file inside of `vendor/composer/b1712560/symfony-symfony-a9d2f68/` and this let the above mentioned if-condition `if (1 === count($contentDir) && is_dir(reset($contentDir))) {` fail.

**Comment by alcohol** [comment]
I am not sure your suggested fix really solves the root problem..

**Comment by TheFox** [comment]
Why not? What's the root problem?

**Comment by alcohol** [comment]
The check, whether or not the directory is empty.

**Comment by Seldaek** [comment]
The check is needed to handle github archives which wrap the whole repo into a single directory. The fix seems kinda reasonable I guess although I wish we didn't need to do that. I find it surprising that this never happened or at least never been reported before.. The question is whether it's really needed to be fixed.

**Comment by TheFox** [comment]
That's because you usually don't have the `vendor/` directory open in Finder. But I would actually like to fix this in Symfony Finder, to build a list of files from Operating Systems which you usually don't care about. I don't know if the Symfony community likes to have such a feature.

Is this the only way to distinguish GitHub archives from the rest?

**Comment by Seldaek** [comment]
Well I'm not sure if it's only github doing this, but generally speaking if an archive contains a single folder it's most likely the whole project folder was archived together so we wanna extract that out.
