### ISSUE TITLE
Can't run composer self-update, about and others 

### ISSUE THREAD

**Issue by jmevalentin** [composer/composer#6786]
Composer version is 1.6-dev
I run composer self-update and get this:

> PHP Warning:  PHP Startup: Unable to load dynamic library '/Users/me/.phpbrew/php/php-7.1.10/lib/php/extensions/debug-zts-20160303/php_openssl.dll' - dlopen(/Users/me/.phpbrew/php/php-7.1.10/lib/php/extensions/debug-zts-20160303/php_openssl.dll, 9): image not found in Unknown on line 0
>
> Warning: PHP Startup: Unable to load dynamic library '/Users/me/.phpbrew/php/php-7.1.10/lib/php/extensions/debug-zts-20160303/php_openssl.dll' - dlopen(/Users/me/.phpbrew/php/php-7.1.10/lib/php/extensions/debug-zts-20160303/php_openssl.dll, 9): image not found in Unknown on line 0
>                                                                                                         
 > [Composer\Exception\NoSslException]                                                                      
 > The openssl extension is required for SSL/TLS protection but is not available. If you can not enable the openssl extension, you can disable this error, at your own risk, by setting the 'disable-tls' option to true.    

I may have messed things up by installing php-7.1.10  and php-5.6.24  with phpbrew. I installed apache via homebrew and enabled ssl_module in httpd.conf and then extension=php_openssl.dll in php.ini, then made sure the path was correct so running `openssl version -a` from the cli returns the following:
`
OpenSSL 1.0.2m  2 Nov 2017
built on: reproducible build, date unspecified
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: clang -I. -I.. -I../include  -fPIC -fno-common -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -arch x86_64 -O3 -DL_ENDIAN -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/local/etc/openssl"
`
Is there anything else I need to check?

**Comment by TheFox** [comment]
I would first search for the extension file using `find /Users/me/.phpbrew/php/php-7.1.10 -type f -iname '*openssl*'` to see if this file really exists. Maybe the path is wrong.

Why are even `.dll` files used under macOS? Is this a phpbrew thing?

**Comment by jmevalentin** [comment]
You know, that's a great question that didn't even occur to me. I just did a find for any dll files in the /Users/ and /usr/ directories and no hits. Now I', really at a loss. Any suggestions?

**Comment by TheFox** [comment]
I would not search for dll files, but rather for `'*openssl*'`.

**Comment by jmevalentin** [comment]
Did a `locate openssl` but too many hits, then just did a `which openssl`, found it at `/usr/local/opt/openssl/bin/openssl`. Then ran `/usr/local/opt/openssl/bin/openssl version -a` and get the same version info as in my original post.

**Comment by TheFox** [comment]
And what does `find /Users/me/.phpbrew/php/php-7.1.10 -type f -iname '*openssl*'` say?

**Comment by jmevalentin** [comment]
Nothing found in that directory. I'm not sure if it's necessarily phpbrew or a php or apache pointer to the wrong location.

**Comment by alcohol** [comment]
I don't want to be harsh, but as this really is not a Composer issue, I'm closing the issue.

**Comment by jmevalentin** [comment]
No problem, thanks @TheFox for trying to help me resolve it. I just disabled the php.ini line for now.

Cheers!
