### ISSUE TITLE
Using environment-level variable as package version.

### ISSUE THREAD

**Issue by cvsouth** [composer/composer#6792]
I think it would be useful if the version of a package could be specified via an environment variable or similar. For example: ```"my/package" => "$SOMEVAR or dev-develop"```

In this example composer would look for the environment variable SOMEVAR to use as the version and if not found, fall back to dev-develop.

Use case: https://stackoverflow.com/questions/47174597/specifiy-composer-json-file-in-laravel-env.

**Comment by stof** [comment]
Supporting env variables in the composer.json is incompatible with the lock file: the lock file would be generated for a specific value of the env variable (the one used during the `composer update` call generating it) and then the lock file would have to also encode this info, to be able to report any mismatch when using it later.

The use case described in SO looks like a use case which can only be achieved by not using a lock file (i.e. running `composer update` during the deployment process, and then running a set of dependencies in prod that you never tried locally before), which is very far from the Composer recommendations

**Comment by cvsouth** [comment]
I see what you are saying.

Could the lock file not leave the variables in to be resolved during `composer update` though? Because this scenario would only apply to people actually using environment variables as versions and in this case the user should be aware of this behavior and any possible consequence considered? i.e. Only use it for packages which you can personally verify have been tested in situ; which is as per the use case?

**Comment by cvsouth** [comment]
Alternatively could the developer not still do a test run using their production dependencies in their development environment prior to deployment by passing some option to composer (or changing the environmental variable temporarily), thus generating a composer.lock which can then be deployed as normal?

**Comment by stof** [comment]
> Could the lock file not leave the variables in to be resolved during `composer update` though?

@cvsouth the composer.lock is the **output** of the `composer update` dependency solving. So I don't understand your suggestion.

> Because this scenario would only apply to people actually using environment variables as versions and in this case the user should be aware of this behavior and any possible consequence considered?

That's a wrong assumption. People using this feature will *not* magically know that using it breaks one of the biggest feature of Composer: reproduceable installs thanks to the lock file.

> Only use it for packages which you can personally verify have been tested in situ; which is as per the use case?

Different versions of packages can have different requirements, so changing the version of *your* package being used can also change the installed version of totally unrelated packages.
And even if the other version of the package works fine on its own, it does not mean that it will work fine for the way your project uses it (it may be hitting a weird edge case bug).

I actually don't understand why people would want to run a different codebase on production than elsewhere. It goes the opposite way of all modern development practices of having a dev env as close as possible to the prod (sharing the codebase was the first thing devs agreed on)

**Comment by cvsouth** [comment]
Sorry what I intended to mean when I put:

> Could the lock file not leave the variables in to be resolved during composer update though?

Was that during `composer update`, the variables could be left in the composer.lock file for composer to deal with in production. But I worded it all wrong. And you're right. I am not thinking about it properly.

But does my consequent comment not hold true?

> Alternatively could the developer not still do a test run using their production dependencies in their development environment prior to deployment by passing some option to composer (or changing the environmental variable temporarily), thus generating a composer.lock which can then be deployed as normal?

Maybe the whole environment variable thing would not be necessary actually, but rather the use case could be solved by having composer specific variables in the composer.json file which can be then passed to the `composer update` command?

So for example maybe the composer.json would look like `"my/package" => "$SOMEVAR or dev-develop"` and then to get ready for deployment you could run `composer update --var="SOMEVAR:dev-master", generating a lock file which can be tested and deployed?

**Comment by stof** [comment]
@cvsouth using a CLI flag of an environment variable has exactly the same issue: the lock file now depends on what value you passed for the variable, and running a `composer install` with a different set of variable would not work file.

**Comment by alcohol** [comment]
Your linked use-case is talking about using a different composer.json for different scenarios, by specifying which file to use in the `$COMPOSER` environment variable.

This issue is asking for something entirely different. Also, no, variables are not supported.

**Comment by cvsouth** [comment]
The use case is for using dev-develop across a set of packages when the main project is on the develop branch and dev-master versions for that same set of packages when the main project is on the master branch. Please tell me what the proper solution to this is?

**Comment by alcohol** [comment]
Two composer.json files, and `$COMPOSER` env variable.

**Comment by cvsouth** [comment]
And when packages required directly by the main project's composer.json require further packages through their own composer.json, which should also follow suit being dev-develop when the main project is on the develop branch and dev-master when the main project is on the master branch?

**Comment by Seldaek** [comment]
@cvsouth perhaps you can require `"self.version"` which will always resolve to the current version of your package, so if you're on master it'll require dev-master, on develop it'll require dev-develop, etc.
