### ISSUE TITLE
"vendor" folder missing after running "Composer Install"

### ISSUE THREAD

**Issue by carlotscvdata** [composer/composer#6794]
Hello I am trying to run an existing Laravel application that I pulled from Github and when I try to open it on the browser I get the following error: 

**Warning: require(/home/vagrant/.../public/vendor/autoload.php): failed to open stream: No such file or directory in /home/vagrant/..../public/autoload.php on line 2**

I am running the application using Vagrant Homestead, and I already tried Composer Install and Composer Update from the root directory. I navigated to the vendor folder and noticed that it was not created. How can I fix it?

When I run this command: 

```
...Composer Install
```

I get the following output:

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package herrera-io/json is abandoned, you should avoid using it. Use kherge/json instead.
Package kherge/version is abandoned, you should avoid using it. No replacement was suggested.
Package herrera-io/phar-update is abandoned, you should avoid using it. No replacement was suggested.
Package mjolnic/bootstrap-colorpicker is abandoned, you should avoid using it. Use itsjavi/bootstrap-colorpicker instead.
Generating autoload files
> php artisan clear-compiled
> php artisan optimize
Generating optimized class loader

**Comment by xabbuh** [comment]
Can you show your `composer.json` file?

**Comment by carlotscvdata** [comment]
"require": {
        "laravel/framework": "4.2.*",
        "way/generators": "2.6.*",
        "abodeo/laravel-stripe": "dev-master",
        "barryvdh/laravel-ide-helper": "1.11.*",
        "doctrine/dbal": "v2.4.0",
        "maatwebsite/excel": "dev-custom-file-extensions",
        "gregwar/captcha": "1.0.*",
        "authorizenet/authorizenet": "~1.8.0",
        "codeception/codeception": "2.0.*",
        "scvdata/session": "dev-master",
        "mjolnic/bootstrap-colorpicker": "dev-master",
        "anlutro/l4-smart-errors": "dev-master",
        "fzaninotto/faker": "dev-master#31e2dd76ce734b0f7175de7ab6de3efddc240644",
        "barryvdh/laravel-debugbar": "~1.8"
    },
    "require-dev": {
        "501st-alpha1/codeception-data-selector": "dev-master",
        "codeception/specify": "*",
        "codeception/aspect-mock": "0.5.*",
        "phpdocumentor/phpdocumentor": "2.*"
    },
    "repositories": [
        {
            "type": "git",
            "url": "ssh://git@github.com/scvdata/scvdata-laravel-session.git"
        },
        {
            "type": "git",
            "url": "https://github.com/501st-alpha1/codeception-data-selector.git"
        },
        {
            "type": "git",
            "url": "https://github.com/501st-alpha1/Laravel-Excel.git"
        }
    ],
    "autoload": {
        "classmap": [
            "app/commands",
            "app/controllers",
            "app/models",
            "app/extensions",
            "app/interfaces",
            "app/services",
            "app/database/migrations",
            "app/database/seeds",
            "app/helpers.php",
            "app/tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "php artisan clear-compiled",
            "php artisan ide-helper:generate",
            "php artisan optimize"
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "stable"
}


**This is the output when I run composer install:** 

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package herrera-io/json is abandoned, you should avoid using it. Use kherge/json instead.
Package kherge/version is abandoned, you should avoid using it. No replacement was suggested.
Package herrera-io/phar-update is abandoned, you should avoid using it. No replacement was suggested.
Package mjolnic/bootstrap-colorpicker is abandoned, you should avoid using it. Use itsjavi/bootstrap-colorpicker instead.
Generating autoload files
> php artisan clear-compiled
> php artisan optimize
Generating optimized class loader

**Maybe an outdated package is causing the problem?**

**Comment by mirsahib** [comment]
Look like the issue is closed but currenly i am facing the same problem.

my composer.json

`{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.2.5",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.0",
        "laravel/tinker": "^2.0"
    },
    "require-dev": {
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.1",
        "phpunit/phpunit": "^8.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}`

I am using ubuntu 20.04 and xamp with php7.4.let me know if need to create a seperate issue
