### ISSUE TITLE
Composer Update on a Typo Should Not Barrel Blindly Ahead

### ISSUE THREAD

**Issue by donatj** [composer/composer#6799]
When running something like the following command and accidently typo-ing the package name

```
composer update myvendor/typoedname
```

Composer does the following:

```
Package "myvendor/typoedname" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)
[…]
```

This is really a **very bad** default behaviour. Obviously the user was trying to update a **single** package. Not all of them. Fail. Updating _them all_ is obviously not what they wanted.

We take the time to vet our updates to individual packages very closely. Security concerns and the like. I have to imagine a lot of larger users / companies do as well.

Running `composer update` without specifying a package is **almost never** what we want.

As it stands right now if I typo a package name running update I need to check my lock file out of git and re-composer-install. I do this a couple times a week because I'm not the most accurate typist.

This is a major source of frustration.

**Comment by curry684** [comment]
Are you sure it's actually doing the global update or does it just seem that way from output?

Expected is that in this case all mentioned and valid packages would update, so 0. If in this case it falls back to global update I agree it's a bug.
