### ISSUE TITLE
Use separate XDebugHandler package

### ISSUE THREAD

**Issue by felixfbecker** [composer/composer#6802]
I've been using the `XDebugHandler` in my project to restart it without XDebug if it's enabled because it has an enormous performance impact.

https://github.com/felixfbecker/php-language-server/blob/1804ac8d978a318a4a6b88dc02b4362854b6a65b/bin/php-language-server.php#L34-L35

But it would be nice if I could use it without bringing in the whole `composer/composer` package and all its transitive dependencies. What do you think about moving it to a separate package? Like the semver library, I think it can be very valuable to other projects.

**Comment by weirdan** [comment]
Other projects (like `vimeo/psalm`) may benefit from separate package as well.
/cc @muglug

**Comment by johnstevenson** [comment]
It's not my decision to make, but I'd be willing to extract it to a standalone package. It is a bit of a hack though. The main problems are passing any ini overrides (`-d ini_key=value`) to the new process, and the new process wanting to do anything via `php_ini_loaded_file` or `php_ini_scanned_files`.

The first _could_ be solved using [this unmerged PR](https://github.com/composer/composer/pull/6036) and Composer extending the class to override it with the current functionality.

The second is internally solved by using a combination of an env variable `COMPOSER_ORIGINAL_INIS` and a helper function (which I guess could be included as a static method in the new package, though there is no guarantee that the new process will be aware that it needs to use it!).

I'd imagine that this and the other variables (`COMPOSER_ALLOW_XDEBUG  COMPOSER_XDEBUG_VERSION`) would need to be renamed as well.

**Comment by AJenbo** [comment]
This might also benifit:
Phan (already includes [a hard copy](https://github.com/phan/phan/blob/c6775f9d308f69241af7c83df25d1540b3aca5db/src/Phan/Library/Composer/XdebugHandler.php))
Phpstan ([#605](https://github.com/phpstan/phpstan/pull/605) [#254](https://github.com/phpstan/phpstan/issues/254))
Php-cs-fixer
PHP_CodeSniffer
PHPMD

I would be happy to create patches/pull request for some of them.

**Comment by alcohol** [comment]
@johnstevenson I would definitely be 👍  on extracting this. Let me know if you need any help at all.

**Comment by johnstevenson** [comment]
@alcohol Cool. I think it would work best as a Composer package (like semver and spdx-licenses) then we could keep the existing environment variables. Perhaps `composer/xdebug-handler`

What is the best way forward? I can put a test repo up under my Github account, then it could be transferred over if it is considered suitable (as happened with the Composer-Setup installer) or whatever...

**Comment by AJenbo** [comment]
I'd be happy to help too :)

**Comment by alcohol** [comment]
@johnstevenson I'll ping @Seldaek for a repo. No need to create one under your account first. Would be nice to start with a fresh list of issues/feature requests and pull requests there from the start.

**Comment by Seldaek** [comment]
@johnstevenson @alcohol  I created the repo and granted you access - please go ahead extracting it, but if possible don't do any of the above changes in the master branch but rather send PRs for those so we can discuss point by point and see what makes sense. i.e. ini overrides are way overkill IMO so we can perhaps add them as an option perhaps, but I wouldn't want Composer to suddenly inherit weird behavior added to make this more general purpose :)

**Comment by alcohol** [comment]
Yeah. It would be nice to make things like environment variable names configurable.

**Comment by johnstevenson** [comment]
@Seldaek Aha, Mr Boggiano I presume.

Separate issue but did you get the emails about a new Composer-Setup release: https://github.com/composer/windows-setup/releases/tag/v4.8.0

**Comment by Seldaek** [comment]
@johnstevenson I did, just been too busy to deal with any of it what with SymfonyCon and then trying to get some work done, but will update that some time latest next week :)

**Comment by johnstevenson** [comment]
@Seldaek That's fine, just wanted to make sure you knew about it.

**Comment by Seldaek** [comment]
Keeping this open for now until we removed the code in this repo, but it's available on composer/xdebug-handler already.

**Comment by felixfbecker** [comment]
Also doesn't have a release yet (or a readme)

**Comment by johnstevenson** [comment]
Yup, it is still being worked on. Best to wait for a release.

**Comment by muglug** [comment]
I think this can be closed!

**Comment by felixfbecker** [comment]
Yup

**Comment by felixfbecker** [comment]
Well, actually what's left here is removing the XDebugHandler and depending on the external package so fixes and improvements don't get fragmented

**Comment by johnstevenson** [comment]
PR here: https://github.com/composer/composer/pull/7174

**Comment by Seldaek** [comment]
https://github.com/composer/composer/pull/7174 has been merged, thanks everyone!
