### ISSUE TITLE
Plugin dependency class not found on Composer 1.5.0 and later

### ISSUE THREAD

**Issue by aleksip** [composer/composer#6803]
I'm writing a Composer plugin that has a dependency on a package which is also a dependency of the root package using the plugin.

With Composer 1.5.0 and later the plugin fails because a class in this dependency is not found. Using Composer 1.4.3 the plugin works fine.

Composer 1.5.0 release notes mention a change in package install order to ensure that plugins are always installed as soon as possible. Maybe this caused the changed behaviour?

Root project `composer.json`: https://github.com/pattern-lab/edition-php-twig-development/blob/feature/decoupled-core/composer.json

Plugin `composer.json`: https://github.com/aleksip/patternlab-composer-plugin/blob/master/composer.json

**Comment by Seldaek** [comment]
Interesting.. Installer::movePluginsToFront should normally do this correctly and move the dependencies of the plugins ahead as well as the plugins themselves. Looking at the code I can't really figure out why this would happen.

**Comment by aleksip** [comment]
The root package uses an inline alias for the required package. It looks like this has something to do with the problem. If I remove the inline alias, or add an inline alias for the plugin, everything seems to work.

**Comment by aleksip** [comment]
Adding an inline alias for the plugin doesn't seem to fix the problem after all. Only removing the inline alias for the required package seems to work. The packages do seem to be installed in the same correct order in all cases.

**Comment by aleksip** [comment]
I tried removing the version constraint from the plugin's `composer.json`, and now the class is found with or without an inline alias for the required package in the root project's `composer.json`.
