### ISSUE TITLE
How to resolve circular dependency over 2 external packages

### ISSUE THREAD

**Issue by TomasVotruba** [composer/composer#6805]
I'm trying to update `phpdocumentor/reflection-docblock` to newer `phpunit/phpunit` dependency, that [started to use the package](https://github.com/phpspec/prophecy-phpunit#this-package-is-not-maintained-anymore-prophecy-is-supported-in-phpunit-directly-as-of-phpunit-45-making-this-package-useless) I update.

There is new circular dependency:

- (**this**) `phpdocumentor/reflection-docblock` package requires `phpunit/phpunit`
- `phpunit/phpunit` requires `phpspec/prophecy` (since `phpunit/phpunit` 4.5)
- `phpspec/prophecy` requires this `phpdocumentor/reflection-docblock` (**this**) package

In abstraction:

- A needs B
- B needs C (new one!)
- C needs A

### Before - works

```json
{
    "require-dev": {
        "phpunit/phpunit": "4.4"
    }
}
```

### After - broken

```json
{
    "require-dev": {
        "phpunit/phpunit": "4.5"
    }
}
```

When I run:

```bash
composer update
```

**Composer conflict output**:

    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - Installation request for phpdocumentor/reflection-docblock dev-phpunit -> satisfiable by phpdocumentor/reflection-docblock[dev-phpunit].
        - phpspec/prophecy v1.3.1 requires phpdocumentor/reflection-docblock ~2.0 -> satisfiable by phpdocumentor/reflection-docblock[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5].
        - phpunit/phpunit 4.5.0 requires phpspec/prophecy ~1.3.1 -> satisfiable by phpspec/prophecy[v1.3.1].
        - Can only install one of: phpdocumentor/reflection-docblock[2.0.0, dev-phpunit].
        - Can only install one of: phpdocumentor/reflection-docblock[2.0.1, dev-phpunit].
        - Can only install one of: phpdocumentor/reflection-docblock[2.0.2, dev-phpunit].
        - Can only install one of: phpdocumentor/reflection-docblock[2.0.3, dev-phpunit].
        - Can only install one of: phpdocumentor/reflection-docblock[2.0.4, dev-phpunit].
        - Can only install one of: phpdocumentor/reflection-docblock[2.0.5, dev-phpunit].
        - Installation request for phpunit/phpunit 4.5 -> satisfiable by phpunit/phpunit[4.5.0].

---

I've tried:

- `minimum-stability: dev`
- aliases `"phpunit/phpunit": "4.5 as 4.4"`

Any ideas how to approach this?

Ref: [SO question, with no attention](https://stackoverflow.com/questions/47236948/how-to-resolve-composer-package-circular-dependency-of-external-package)

**Comment by alcohol** [comment]
Cannot reproduce:

```
rob@macbookpro.local /tmp/test > cat composer.json
{
    "require-dev": {
        "phpunit/phpunit": "4.4"
    }
}
```
```
rob@macbookpro.local /tmp/test > composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 16 installs, 0 updates, 0 removals
  - Installing symfony/yaml (v2.8.30): Loading from cache
  - Installing sebastian/version (1.0.6): Loading from cache
  - Installing sebastian/global-state (1.1.1): Loading from cache
  - Installing sebastian/recursion-context (1.0.5): Loading from cache
  - Installing sebastian/exporter (1.2.2): Loading from cache
  - Installing sebastian/environment (1.3.8): Loading from cache
  - Installing sebastian/diff (1.4.3): Loading from cache
  - Installing sebastian/comparator (1.2.4): Loading from cache
  - Installing doctrine/instantiator (1.0.5): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (2.3.8): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.3.4): Loading from cache
  - Installing phpunit/php-token-stream (1.4.11): Loading from cache
  - Installing phpunit/php-code-coverage (2.2.4): Loading from cache
  - Installing phpunit/phpunit (4.4.0): Downloading (100%)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Writing lock file
Generating autoload files
```
```
rob@macbookpro.local /tmp/test > cat composer.json
{
    "require-dev": {
        "phpunit/phpunit": "4.5"
    }
}
```
```
rob@macbookpro.local /tmp/test > composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 1 update, 0 removals
  - Installing phpdocumentor/reflection-docblock (2.0.5): Loading from cache
  - Installing phpspec/prophecy (v1.3.1): Loading from cache
  - Updating phpunit/phpunit (4.4.0 => 4.5.0): Loading from cache
phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
Writing lock file
Generating autoload files
```

**Comment by carusogabriel** [comment]
I’ve experienced this a lot. Two possible scenarios: `composer.lock` committed to master and `branch-alias` not defined in `extra` section.

**Comment by TomasVotruba** [comment]
@carusogabriel Yes, that would the right direction. 
I've paid for a helpful answer on stackoverflow: https://stackoverflow.com/a/47271258/1348344

Resolved successfully

**Comment by stof** [comment]
Note that `4.5` in your requirement means you only allow a single version of PHPUnit: 4.5.0. Not allowing version ranges makes it very hard to avoid conflicts (and PHPUnit 4.5.0 is outdated since approximately 5 years)

**Comment by TomasVotruba** [comment]
That's not related at all. Point was in circular dependency, no matter to package or version.
