### ISSUE TITLE
SMTP connect failed()

### ISSUE THREAD

**Issue by Jonazg** [composer/composer#6807]
I am working locally on xampp and using Gmail SMTP plugin to get my contact form 7 to work. When i try sending a test email it fails, and i get this error message:
Connection failed. Error #2: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed [C:\xampp1\htdocs\WP\wp-content\plugins\gmail-smtp\PHPMailer\class.smtp.php line 369]
SMTP Error: Could not connect to SMTP host.
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

I changed the mail function settings in php.ini and sendmail configuration accordingly. Can you help me with what the problem might be here?

**Comment by xabbuh** [comment]
I don't think that this is related to Composer.

**Comment by Jonazg** [comment]
yeah sorry i accidentally posted under this category
@xabbuh

**Comment by xabbuh** [comment]
@Jonazg Can you close the issue then please?
