### ISSUE TITLE
Add --patch-level-updates parameter to require

### ISSUE THREAD

**Issue by schmunk42** [composer/composer#6816]
When I run this command:

```
composer require <--patch-level-updates> yiisoft/yii2-swiftmailer
```

I get the following output (in composer.json):

```
"yiisoft/yii2-swiftmailer": "^2.1.0"
```

And I expected this to happen (**only with an additional param**):

```
"yiisoft/yii2-swiftmailer": "~2.1.0"
```

The package above should be included with only patch-level updates. While the default behavior of composer is fine, it would be nice to have a parameter, which would pick the "right" constraint in such a case, would be a documentation thing for the package. There might be other reasons why a developer only wants to do patch level updates by default.

Related: https://github.com/yiisoft/yii2-swiftmailer/issues/55#issuecomment-344851814

**Comment by alcohol** [comment]
I don't see a strong reason to add this functionality.

If you do not provide a constraint, composer will pick a sensible default. If you are more picky about your constraints, simply provide the constraint.

```
composer require yiisoft/yii2-swiftmailer:~2.1.0
```

**Comment by schmunk42** [comment]
Yeah, this actually relates to some projects not following the three-digit semver policy to 100% - rather using a four-digit policy, where the first two digits indicate a major version.

I like the feature of composer very much, that it automatically creates a constraint based on the current version for you. Taking this further, it would be an idea, if the maintainer could specify the default upgrade level in it's `composer.json`.

But I also want to say, that this issue is no big thing to me, I just wanted to voice it. Close issue at will.

**Comment by Seldaek** [comment]
Also not a fan of adding complication there for something that I doubt a lot of people would use. Rather go complain to those projects that it'd be nicer to users if they followed semver like most other projects instead of breaking assumptions :/
