### ISSUE TITLE
Installing a bundle which lets the scripts fail dependency is reverted afterward

### ISSUE THREAD

**Issue by wachterjohannes** [composer/composer#6821]
As we discussed in the #SymfonyConHackday2017 the cache:clear fails for `composer require symfony/security-bundle` for example. 

If you do that the `composer.json` file will be reverted after the failing script (unless the dependency is installed in the vendor folder) and the dependency is gone. This is quite confusing because actually, I think with Symfony flex there will be things like that.

**Comment by ElectricMaxxx** [comment]
@wachterjohannes i questioned that issue several weeks ago: https://gist.github.com/ElectricMaxxx/15dca79636d725e972a7e9471208cfd4
My proposal was to have clean bundles, that mean bundle should install without an issue. I added a simple [script](https://github.com/symfony-cmf/testing/blob/master/bin/scripts/check_install.sh) for that to our travis matrix at CMF.

**Comment by weaverryan** [comment]
Related/duplicate - see symfony/flex#142
