### ISSUE TITLE
Trigger an error on composer install without a lock file

### ISSUE THREAD

**Issue by naderman** [composer/composer#6822]
To reduce confusion around the purposes and behaviors of the composer install and update commands, the install command should error if no lock file is present. Users will have to get started with composer update.

This is clearly a BC break so will require 2.0, but it's easy to fix for users by running update if a lock file should be generated or committing a lock file if install was actually supposed to use a particular set of dependencies.

Introductory docs should be reviewed as well to make sure we don't induce people into doing this wrong.

**Comment by stof** [comment]
Reviewing doc should probably even be done sooner than 2.0, to push them in the right direction already

**Comment by Seldaek** [comment]
Works for me but IMO we should print a warning and if interactive ask user if they `... want to run update instead now? [Yn]`. No point in making the user type it out themselves..

**Comment by 7ochem** [comment]
Should there also be an issue to add a warning already in Composer 1.x about this, to inform of a future BC break. I can imagine there can be automated processes running `composer install --no-interaction` without a lock file that will break.

**Comment by itsjavi** [comment]
other package managers use `install` as the initial verb, why cause more confusion?
also when you have a new project, `update` makes no sense in that context

**Comment by naderman** [comment]
On the 2.0 branch install now updates a clear warning message that without a lock file present what it's doing is actually an update to generate a lock file.

I agree that breaking existing automation that relies on install doing an update is an unnecessary bc break.
