### ISSUE TITLE
Create seperate package for XdebugHandler

### ISSUE THREAD

**Issue by AJenbo** [composer/composer#6823]
A few other CLI tools would benefit from using the XdebugHandler found in Composer:

https://github.com/composer/composer/blob/26a50b37624b20d73c861b7714c3d34cbba8e4e1/src/Composer/XdebugHandler.php
https://github.com/composer/composer/blob/26a50b37624b20d73c861b7714c3d34cbba8e4e1/src/Composer/Util/IniHelper.php

To better facilitate this it would be beneficial if it could be moved to it's own package.

Tools that might benifit:
Phan (already includes [a hard copy](https://github.com/phan/phan/blob/c6775f9d308f69241af7c83df25d1540b3aca5db/src/Phan/Library/Composer/XdebugHandler.php))
Phpstan ([#605](https://github.com/phpstan/phpstan/pull/605) [#254](https://github.com/phpstan/phpstan/issues/254))
Php-cs-fixer
PHP_CodeSniffer
PHPMD

I would be happy extracting the handelers and associated test in to a seporate package and help maintain them, as well as create patches/pull request for the before mentioned tools. All I would need help with is for a repository to be setup for the XdebugHandler that I can make pull request against.
Somthing like composer/xdebug-handler ?

Anything I'm overlooking?

**Comment by johnstevenson** [comment]
Please see https://github.com/composer/composer/issues/6802

As the original author, I would prefer to do this initial work, because I understand its hackish limitations - (mainly from fixing all the mistakes I made!).

**Comment by AJenbo** [comment]
Duplicate of #6802 
Thank you for the response, and sorry I missed the existing issue for this.
