### ISSUE TITLE
Composer edited and added a new line to my Laravel index.php

### ISSUE THREAD

**Issue by Nezzle** [composer/composer#6825]
Composer edited and added a new line to my index.php file in laravel project. 
	"""" include 'vendor/composer/autoload_script.php'; """"

Because of  that line my whole project stopped working. it added a js script file 
<script src='/vendor/composer/installed.js'></script> to every response.
it caused so much problems especially with json responses.

how can i avoid this problem in future

**Comment by AmitM13** [comment]
reopen this question i have also same issue

**Comment by alcohol** [comment]
I will not reopen this issue because this is not something that composer does.

**Comment by AmitM13** [comment]
okay

**Comment by AmitM13** [comment]
it solve i have solve this issue and it autoload_script.php issue its a malware.

**Comment by Nezzle** [comment]
how did you solved the issue can you help me?

**Comment by shoguniphicus** [comment]
Yes, please enlightened the rest of us, it's happening to 1 of my laravel installation but not the other.

**Comment by Nezzle** [comment]
it happened to my every laravel projects which was uploaded in root directory. But not affected to which that are uploaded to subfolders

**Comment by AmitM13** [comment]
there is malware files in vendor/composer folder you need to delete those
files.
