### ISSUE TITLE
Update with --lock sometimes updates dependencies

### ISSUE THREAD

**Issue by mihaiplasoianu** [composer/composer#6827]
In some projects, we have dependencies like this:
```
"foo/bar": "dev-branch as 1.2.3"
```
If I run `composer update --lock`, these dependencies get updated to the newest commit on the specific branch. I don't think this should happen.

**Comment by alcohol** [comment]
Can you provide a reproducible scenario.

**Comment by mihaiplasoianu** [comment]
@alcohol I cannot reproduce it with newly created demo repositories. I'll try and figure out what causes this in our plugins and reopen the issue.
