### ISSUE TITLE
Add JSON5 support

### ISSUE THREAD

**Issue by Bilge** [composer/composer#6830]
It seems to me comments are sorely needed due to [regular](https://github.com/composer/composer/issues/5364) [requests](https://github.com/composer/composer/issues/1988) and there exist standards for introducing them such as [JSON5](http://json5.org/) which have [PHP support](https://github.com/colinodell/json5#json5-for-php---json-for-humans).

JSON5 ("JSON for humans") doesn't just open up the specification to support comments but also unquoted object identifiers, single-quoted strings and trailing commas in array and object literals. In other words, most of the features JavaScript developers have long taken for granted and which offer greater flexibility and easier development when defining Composer dependencies.

We should recognize that the Composer file is intended to be authored by humans so anything that eases development should be regarded as a win. Despite similar threads on this topic, they have all been closed without resolution. Can we not have a discussion about the feasibility of introducing support for this emerging standard to make Composer files more maintainable?

**Comment by cebe** [comment]
> Can we not have a discussion about the feasibility of introducing support for this emerging standard to make Composer files more maintainable?

As far as I see this discussion happened in the tickets you linked, please take the time to read them. I am also in favor of having comments, but unless you propose an easy way to add it without breaking a lot of things that is not going to happen.

**Comment by Seldaek** [comment]
This would indeed break a bunch of third party infrastructure, as well as stuff like JsonManipulator in Composer itself which I doubt would be possible to achieve given the leniency of the JSON5 format. 

IMO the _comments "trick" works well enough for the odd cases where I need comments:

```
{
    "require": {
        "foo/bar": "2.0.3"
    },
    "_comments": {
        "foo/bar": "pinned until XXX is resolved"
    }
}
```

**Comment by Bilge** [comment]
@Seldaek Third party things *can* be broken if you target the next major version, i.e. 2.0; that's what semantic versioning is for. Third parties would be foolish to upgrade until they have updated their technology to be compatible. Nothing will improve as long as you keep pretending that that `_comments` is sufficient and that virtual third party constraints control your development decisions.

**Comment by stof** [comment]
@Bilge third-party broken because of that cares about composer config files, not about composer itself. They are not the one upgrading to JSON5. The community would be the one upgrading (and suddenly, they carefully crafted composer.json support would break because people use JSON5).

And supporting a new format has a huge impact, because support for composer.json files **cannot** be dropped (ever), as this would make all the existing ecosystem incompatible (making it essentially a new competing package manager to support for libraries).
Look for closed issues asking for YAML support for the details about what this implies for the composer tooling

**Comment by keithy** [comment]
All that is needed is "support". Composer uses composer.lock as the master, and reports if composer.json has changed. So, use composer.json as the master for tooling, and report if composer.json5 produces a different result. Then the USER can use the json5 file for comments etc, and composer continues to use composer.json Later someone can produce tooling for backporting changes from json to json5. I think I will just write bash script to implement.

**Comment by keithy** [comment]
https://github.com/keithy/composer-beethoven
