### ISSUE TITLE
Composer won't update

### ISSUE THREAD

**Issue by SmiffyKMc** [composer/composer#6831]
We have composer as our dependency injection framework which will pull in a library we created, foobar, which works fine. The library foobar has 14 version v1.1.1 -> v1.1.14. All the way up to .12 composer updated the app fine. But now we are getting this error...

    Update failed (Source directory /home/username/dev/git/appname/vendor/foorbar/library has unpushed changes on the current branch: 
    Branch v1.1.14 could not be found on the origin remote and appears to be unpushed)
Things to know:

- Vendor is ignored in .gitignore.
- Tried doing composer.phar clearcache.
- Would be ideal to not have to delete the library every time.

Has anyone had this issue and how did you manage to solve it?

Thanks

**Comment by tomzx** [comment]
@SmiffyKMc Please share your `composer.json` file.

**Comment by stof** [comment]
`branch v1.1.14` ? that looks weird. Aren't you using git tags ?

**Comment by SmiffyKMc** [comment]
Guys, thanks a million for the reply! It was something I couldn't understand at all.

Sure the composer.json file is below now:

{
	"name" : "App",
	"description" : "Foo Bar",
	"require" : {
		"php" : ">=5.3.3",
		"zendframework/zendframework" : "2.2.*",
		"foobarzf2lib/library" : "v1.1.*"
	},
	"minimum-stability" : "stable",
	"repositories" : [{
			"type" : "package",
			"package" : {
				"name" : "foobarzf2lib/library",
				"version" : "v1.1.14",
				"source" : {
					"url" : "https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/foobarzf2lib",
					"type" : "git",
					"reference" : "test"
				},
				"autoload" : {
					"psr-4" : {
						"FooBar\\" : "FooBar/"
					}
				}
			}
		}
	]
}

**Comment by tomzx** [comment]
Please use the proper formatting (using triple backticks `).

**Comment by Insasse** [comment]
Removing the package and reinstall helped me to fix this.
