### ISSUE TITLE
Composer including .git directory when using private git repository

### ISSUE THREAD

**Issue by g0dlight** [composer/composer#6832]
My `composer.json`:

```json
    "require": {
        "mycheck/common": "*",
    },
    "repositories": [
        {
            "type": "git",
            "url":  "git@bitbucket.org:erez_spatz/mycheck-common.git"
        }
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
require.mycheck/common : unbound version constraints (*) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer update mycheck/* -v
```

I get the following output:

```
Dependency resolution completed in 0.085 seconds
Analyzed 10334 packages to resolve dependencies
Analyzed 164748 rules to resolve dependencies
Dependency resolution completed in 0.000 seconds
Package operations: 1 install, 0 updates, 0 removals
Installs: mycheck/common:v0.8.13
  - Installing mycheck/common (v0.8.13): Cloning 990970cf3dbd52c543de2e5ee4f257bd5161fb7e from cache
Writing lock file
Generating autoload files
> post-update-cmd: Illuminate\Foundation\ComposerScripts::postUpdate
> post-update-cmd: php artisan optimize
Generating optimized class loader
The compiled services file has been removed.
```

The problem is that composer including .git directory when cloning this repository.
This is causing git of the root project to use git submodule:

when I am running this:
```
git add .
```

I get this out put
```
        modified:   composer.lock
        modified:   vendor/composer/installed.json
        new file:   vendor/mycheck/common
```

I need git to include all vendor files and not use git submodule.

**Comment by SmiffyKMc** [comment]
Hmm I'm wondering if your issue and [mine](https://github.com/composer/composer/issues/6831) are related somehow? Seems to be adding some git with composer?!

**Comment by alcohol** [comment]
`vendor/` should be a part of your `.gitignore`.

https://getcomposer.org/doc/01-basic-usage.md

**Comment by g0dlight** [comment]
@alcohol thanks for your reply, but I know the best practice for composer but for various reasons we decided to include vendor in our project, is there explanation way the .git folder download with our dependency? it's not present in any other dependencies. can we do something about it?

**Comment by Seldaek** [comment]
@g0dlight you can use https://getcomposer.org/doc/06-config.md#preferred-install to configure that. By default dev packages are installed from source (git clone), so if you set this to dist it should install them all with dist (zip file)

**Comment by g0dlight** [comment]
@Seldaek thanks for your reply, I actually have this in my root project config.
```
"config": {
  "preferred-install": "dist",
  "sort-packages": true
}
```

But it doesn't help my package stay as it is.

Any other advice?

**Comment by Seldaek** [comment]
You have to reinstall the dependencies fully after adding preferred-install, just remove the whole vendor dir and run a `composer install`, then they should be installed as dist/zip.. For private bitbucket repos you need [oauth configured](https://getcomposer.org/doc/06-config.md#bitbucket-oauth) to properly support zip files though, otherwise only git clones will happen. Alternatively you can also use [Private Packagist](https://packagist.com) which will create the archives for you and make the oauth process much simpler as bitbucket oauth config is kind of a pain.

**Comment by Dwza** [comment]
had the same problem and deleting folder wasnt the solution. my solution was composer clearcache after deleting vendor, what actually makes sense since the output clearly says "cloning from cache" what is NOT the vendor folder!

**Comment by hayden-t** [comment]
Thank you ! "preferred-install": "dist", and delete vendor then update
