### ISSUE TITLE
Composer fails to find custom repo package if package name/namespace has been changed

### ISSUE THREAD

**Issue by yareckon** [composer/composer#6837]
Outer Project composer.json
```
{
    "name": "test/test-composer",
    "description": "It's a test",
    "type": "project",
    "repositories": [
      {
          "name": "new/new-dist-frontend",
          "type": "git",
          "url": "git@example.com:new/new-dist-frontend.git"
      }
    ],
    "require": {
      "new/new-dist-frontend": "dev-develop"
    }
}
```

Dependency Composer.json is currently
```
{
	"name":"new/new-dist-frontend",
	"type":"frontend-prototype"
}
```
But used to be:  (package namespace changed)
```
{
	"name":"old/new-dist-frontend",
	"type":"frontend-prototype"
}
```

If you've previously used composer to install the outer project, then change the package name or namespace in the dependency's composer.json, then subsequent attempts to install / update the outer project package will fail with an unhelpful error message:

```
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev) 
Your requirements could not be resolved to an installable set of packages.

 Problem 1
 - The requested package new/new-dist-frontend could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
 see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

```

Using composer update -vvv one can see composer using the local cache to determine the package name (likely unless the repo url has changed?).  Despite using the old package name from cache, the error message incorrectly indicates the new package name is the one not being found.

A composer clear-cache fixes this problem.

**Comment by yareckon** [comment]
This is on 1.5.x.

**Comment by Seldaek** [comment]
Are you sure you updated the name in the default branch of git@example.com:new/new-dist-frontend.git ? Composer only reads the name from the default branch and then applies this name to all branches/tags, otherwise it makes renaming impossible for past tags. So in case develop is not your default branch, make sure you update master too and try again.
