### ISSUE TITLE
PackageInterface::getPrettyVersion() returns same value as getVersion() when in version-branch

### ISSUE THREAD

**Issue by Jean85** [composer/composer#6845]
This was originally reported in https://github.com/Jean85/pretty-package-versions/issues/4.

Basically, in https://github.com/Ocramius/PackageVersions/pull/51 (let's ping @Ocramius) we started using `PackageInterface::getPrettyVersion()` to get the pretty version of the root package, without normalization, as for the dependecies (that we get from the lock).
This doesn't seem to work when the root package is in a version-branch, like `3.0`, because `getPrettyVersion()` and `getVersion()` are returning the same value; but `getPrettyVersion()` should return the non-normalized version instead!

The issue can be reproduced like this:
```bash
git init
cat > composer.json <<EOF
{
    "name": "test/test",
    "require": {
        "ocramius/package-versions": "dev-master#ad8a245decad4897cc6b432743913dad0d69753c as 1.1.3"
    }
}
EOF

cat > main.php  <<EOF
<?php

require __DIR__ . '/vendor/autoload.php';
echo \PackageVersions\Versions::getVersion('test/test'), PHP_EOL;
EOF

git checkout -b 3.0
git add .
git commit -mTest
composer install
php main.php

# 3.0.9999999.9999999-dev@412b22b
# instead of
# 3.0-dev@412b22b
```

**Comment by Ocramius** [comment]
@Jean85 can you please report an issue also on https://github.com/Ocramius/PackageVersions? This is a release blocker on my side.

**Comment by Jean85** [comment]
I've track down the issue to this piece of code: https://github.com/composer/composer/blob/bfed974ae969635e622c4844e5e69526d8459baf/src/Composer/Package/Loader/RootPackageLoader.php#L70-L101

It loads the root package using `$versionData['version']`; but the `VersionGuesser` uses `version` and `pretty_version` as array keys, and instead the `RootPackageLoader` parent constructor does this:

https://github.com/composer/composer/blob/bfed974ae969635e622c4844e5e69526d8459baf/src/Composer/Package/Loader/ArrayLoader.php#L56

IMHO it should at least use the `pretty_version` piece and fall back if it's not there.

**Comment by Jean85** [comment]
I'm sorry @Seldaek but yuor fix doesn't seem to work.. I've opened #6866 to try and fix it.
