### ISSUE TITLE
Using `autoload`/`psr-4` doesn't generate the classmap/namespaces

### ISSUE THREAD

**Issue by kenorb** [composer/composer#6846]
Here is my `composer.json` which I'm testing on the empty folder:

```json
{
  "require-dev": {
    "queueit/KnownUser.V3.PHP": "dev-master"
  },
  "repositories": [
    {
      "type": "package",
      "package": {
        "name": "queueit/KnownUser.V3.PHP",
        "version": "dev-master",
        "source": {
          "type": "git",
          "url": "https://github.com/queueit/KnownUser.V3.PHP.git",
          "reference": "master"
        }
      }
    }
  ]
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

Output of `composer --version`:

```
Composer version 1.5.2 2017-09-11 16:59:25
```
----

When I run this command:

```
composer install
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing queueit/knownuser.v3.php (dev-master master): Cloning master from cache
Writing lock file
Generating autoload files
```

----

And I expected that autoload files are generated correctly as per the following definition in the project's [`composer.json` file](https://github.com/queueit/KnownUser.V3.PHP/blob/5d7b4e2abeec762dfd22a75b18e16a59ecf83282/composer.json):

```
    "autoload": {
        "psr-4": {
            "QueueIT\\": ""
        }
    }
```

Instead no namespaces/classmap is generated. I'm checking this with the following command:

    grep -R QueueIT vendor/composer/

What I've tried:

- Running `composer dumpautoload -o` in the top folder didn't work either.

----

To my surprise, this somehow worked when generated `autoload` in the project's folder:

```
$ cd vendor/queueit/KnownUser.V3.PHP/
$ composer dumpautoload -o -vvv
...
$ grep -R QueueIT vendor/composer/
vendor/composer//autoload_classmap.php:    'QueueIT\\KnownUserV3\\SDK\\ActionTypes' => $baseDir . '/Models.php',
...
vendor/composer//autoload_psr4.php:    'QueueIT\\' => array($baseDir . '/'),
vendor/composer//autoload_static.php:            'QueueIT\\' => 8,
...
```

But it doesn't not work when running in the top folder. I'm missing anything, or it's a bug?

**Comment by stof** [comment]
your repository of type `package` does not put any autoloading configuration in the package metadata.
The `package` type for repositories will **never** read the composer.json file in your package. Its goal is precisely to be able to get a package from a project *not* supporting composer.
If you have a composer.json in your package, use the `vcs` type instead (otherwise, you would have to copy the project metadata entirely in your `package` repository, and this is harder to maintain).

**Comment by kenorb** [comment]
Thank you, the following `composer.json` worked fine:

```
{
  "require": {
    "queueit/knownuserv3": "dev-master"
  },
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/queueit/KnownUser.V3.PHP"
    }
  ]
}
```
