### ISSUE TITLE
UnexpectedValueException: continue truncated downloads

### ISSUE THREAD

**Issue by traumschule** [composer/composer#6850]
This is a feature request to enable composer to continue/retry interrupted downloads.

It would be great to automatically continue downloads that failed with `UnexpectedValueException`. Currently composer bluntly raises an error instead of retrying with an offset of the already downloaded part (equivalent to `wget -c`).

Note that this would be especially useful for people with "slow" internet (~300 kbit/s) and "big" downloads of more than 40 MB. In our case `composer install` is called through provisioning a vagrant box with ansible and repeatedly fails at this specific tasks.

# composer.json
```
{
  "repositories": [
    {
      "type": "package",
      "package": {
        "name": "wiki",
        "version": "1.29.2",
        "type": "project",
        "dist": {
          "url": "https://releases.wikimedia.org/mediawiki/1.29/mediawiki-1.29.2.tar.gz",
          "type": "tar"
        }
      }
    }
  ],
  "require": {
    "wiki": "*"
  }
}
```

# composer diagnose
```
$ composer diagnose
Checking composer.json:
  [ErrorException] file_get_contents(/usr/share/php/Composer/../../data/Composer/res/spdx-licenses.json): failed to open stream: No such file or directory  

diagnose

$ composer --version
Composer version @package_branch_alias_version@ (1.0.0-beta2) 2016-03-27 16:00:34
```

# composer install
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
>   - Installing wiki (1.29.2)
>     Downloading: 100%
> 
>                                                                                                                    
>   [UnexpectedValueException]                                                                                       
>   phar error: "/var/www/test/vendor/wiki/41ce3a3312e82e1171878cd737e1c3ef.gz" is a corrupted tar file (truncated)  
>                                                                                                                    
> 
> install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

# Steps to reproduce
```
apt-get install trickle
cat <<EOF > composer.json
{
  "repositories": [
    {
      "type": "package",
      "package": {
        "name": "wiki",
        "version": "1.29.2",
        "type": "project",
        "dist": {
          "url": "https://releases.wikimedia.org/mediawiki/1.29/mediawiki-1.29.2.tar.gz",
          "type": "tar"
        }
      }
    }
  ],
  "require": {
    "wiki": "*"
  }
}
EOF
trickle -d 50 composer install
```

**Comment by Seldaek** [comment]
I agree this sounds good but in practice I am not sure how easy it is to achieve given our current download infrastructure via http streams.. Maybe more a thing for 2.0 or later. 

Alternatively what you could do is to make sure you download the files beforehand and include them with the VM, then use an [artifact repo](https://getcomposer.org/doc/05-repositories.md#artifact) to install from instead of downloading during composer install.

**Comment by Seldaek** [comment]
Closing as I don't really see how we can reasonably do this.
