### ISSUE TITLE
"composer create-project -s dev symfony/skeleton" fails

### ISSUE THREAD

**Issue by nicolas-grekas** [composer/composer#6852]
Running `composer create-project -s dev symfony/skeleton` fails with this error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/framework-bundle ^4.1 -> satisfiable by symfony/framework-bundle[4.1.x-dev].
    - symfony/framework-bundle dev-master conflicts with symfony/lts[4.x-dev].
    - don't install symfony/framework-bundle 4.1.x-dev|install symfony/framework-bundle dev-master
    - Installation request for symfony/lts ^4@dev -> satisfiable by symfony/lts[4.x-dev].

```

BUT, both `symfony/framework-bundle` and `symfony/lts` have branch-alias correctly set, so that I don't get the failure. Looks like a bug in composer to me.

**Comment by stof** [comment]
hmm, looks like the symfony/lts conflict rule does not play well with the Symfony dev-master branch alias (because `4.1.x-dev` is lower than `5`, but `dev-master` gets normalized as `9999999-dev`, which match the `>= 5` conflict rule).
Solving this would be hard.

**Comment by nicolas-grekas** [comment]
This completely breaks playing with anything @dev in Symfony 4.
Would be great to find a fix or a workaround...

**Comment by Seldaek** [comment]
Maybe @naderman has an idea.. Not too sure I haven't looked into the situation in detail.

**Comment by naderman** [comment]
Aliases are always treated as both versions being present, so dev-master being alias'd to 4.1.x-dev means that the package is both versions simultaneously. So a conflict with either version will result in it not being installed. I think this could be changed in the RuleSetGenerator quite easily, however I'm not sure it's intended. If I have a conflict with dev-master, do I want it to be installed anyway just because it has an alias defined on it?

**Comment by nicolas-grekas** [comment]
> If I have a conflict with dev-master, do I want it to be installed anyway just because it has an alias defined on it?

in fact, there is no conflict with dev-master. There is only a conflict with `>=5` (which dev-master is not, as stated in with the alias)

**Comment by Seldaek** [comment]
Yeah I guess your conflict should be `>=5,<99`.. maybe we could automatically append `&& <9999999-dev` to conflict rules simply stating `>=X` or `>X`? Not sure if there would be unintended consequences to that.. I mean technically dev-master if not aliased should be included so this is not really correct either to do it automatically. It's indeed only to be excluded if aliased. dev-master aliases are kinda special too as they not only assign a number to a named branch but these end up with two numbers for the one version.

**Comment by naderman** [comment]
I'm not sure my idea for implementing this is even feasible. My thought was to skip any package in the conflict generation which is the alias of a package which is not a conflict candidate, or which has an alias that is not a conflict candidate. However we have no easy way of retrieving all aliases of package to even test this I think (it's only accessible via getAliasOf() from AliasPackage to original package).

https://github.com/composer/composer/blob/master/src/Composer/DependencyResolver/RuleSetGenerator.php#L209-215

**Comment by naderman** [comment]
@Seldaek I think the problem is that the 4.x-dev version will not be compatible with dev-master as soon as the branch alias on dev-master changes, so just appending <99999 to the constraint would actually result in broken behaviour later.
