### ISSUE TITLE
[ErrorException] file_get_contents(./composer.json): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by vkathirvel** [composer/composer#6854]
My `composer.json`:

Happens with any composer.json.

Output of `composer diagnose`:

[ErrorException]
  file_get_contents(./composer.json): failed to open stream: No such file or directory

When I run this command:

composer update / install / -v 
any...

I get the following output:

[ErrorException]
  file_get_contents(./composer.json): failed to open stream: No such file or directory

Exception trace:
 () at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Json/JsonFile.php:152
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 file_get_contents() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Json/JsonFile.php:152
 Composer\Json\JsonFile->validateSchema() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Factory.php:290
 Composer\Factory->createComposer() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Factory.php:576
 Composer\Factory::create() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:332
 Composer\Console\Application->getComposer() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:444
 Composer\Console\Application->getPluginCommands() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:149
 Composer\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:127
 Symfony\Component\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin/composer:54
 require() at C:\ProgramData\ComposerSetup\bin\composer.phar:24

And I expected this to happen:

Update or install

I am on Windows 10 Pro, if that helps

**Comment by vkathirvel** [comment]
- I uninstalled and reinstalled composer
- I downgraded to a few different versions
- ran CMD / BASH as admin

still no luck

**Comment by alcohol** [comment]
Is there such a file in your local working directory?

**Comment by vkathirvel** [comment]
Yes, the composer.json file is present. If I remove the composer.json file, composer -v does not trigger errors. Once I bring the composer.json file, the error appears. I thought the problem was with one specific composer.json file, but it happens for any composer.json file. Quite strange actually.

**Comment by vkathirvel** [comment]
Ignore this please. The folder was sync'd by OneDrive. I guess OneDrive was holding some kind of control over these files. I moved the folder to a non OneDrive zone it worked!

**Comment by FikriJulaihi** [comment]
> Ignore this please. The folder was sync'd by OneDrive. I guess OneDrive was holding some kind of control over these files. I moved the folder to a non OneDrive zone it worked!

Hi, there may I know what had u done to solve the problem? I think mine also is about OneDrive that is making this problem occur. I had the same error as u did.  file_put_contents(./composer.json): failed to open stream: No such file or directory

**Comment by vkathirvel** [comment]
> > Ignore this please. The folder was sync'd by OneDrive. I guess OneDrive was holding some kind of control over these files. I moved the folder to a non OneDrive zone it worked!
> 
> Hi, there may I know what had u done to solve the problem? I think mine also is about OneDrive that is making this problem occur. I had the same error as u did. file_put_contents(./composer.json): failed to open stream: No such file or directory

Don't remember now. Sorry. Maybe, try moving the entire folder outside of OneDrive and then run it.

**Comment by FikriJulaihi** [comment]
> Don't remember now. Sorry. Maybe, try moving the entire folder outside of OneDrive and then run it.

No problem so far it works when it's not in the OneDrive folder. Just looking for a solution on how to solve this even it is in the OneDrive folder.

**Comment by alcohol** [comment]
Due to the syncing mechanisms involved with tools like OneDrive and Dropbox, this simply cannot be solved on our end.

**Comment by ionl** [comment]
I had this same error with phpStorm
> file_get_contents(./composer.json): failed to open stream: No such file or directory
I resolved (wtf) with creation of new project but in the same windows (not a new, not attached)!
It was pertaining with container helper, but I don't know more :(

**Comment by gillespieza** [comment]
This happens to me too, but my folder is not in DropBox or OneDrive.

**Comment by mlncn** [comment]
`rm -rf vendor` and `composer update` solved for me, no file synching or other weirdness to have caused it in the first place though.
