### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by ravindralande** [composer/composer#6855]
> curl -vvv https://getcomposer.org/version                             
*   Trying 87.98.253.108...                                             
* Connected to getcomposer.org (87.98.253.108) port 443 (#0)            
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@ST
* successfully set certificate verify locations:                        

  CApath: none                                                          
* TLSv1.2 (OUT), TLS Unknown, Certificate Status (22):                  
* TLSv1.2 (OUT), TLS handshake, Client hello (1):                       
* TLSv1.2 (IN), TLS handshake, Server hello (2):                        
* TLSv1.2 (IN), TLS handshake, Certificate (11):                        
* TLSv1.2 (OUT), TLS alert, Server hello (2):                           
* SSL certificate problem: unable to get local issuer certificate       
* Closing connection 0                                                  
* TLSv1.2 (OUT), TLS alert, Client hello (1):                           
curl: (60) SSL certificate problem: unable to get local issuer certifica
More details here: https://curl.haxx.se/docs/sslcerts.html              
                                                                        
curl performs SSL certificate verification by default, using a "bundle" 
 of Certificate Authority (CA) public keys (CA certs). If the default   
 bundle file isn't adequate, you can specify an alternate file          
 using the --cacert option.                                             
If this HTTPS server uses a certificate signed by a CA represented in   
 the bundle, the certificate verification probably failed due to a      
 problem with the certificate (it might be expired, or the name might   
 not match the domain name in the URL).                                 
If you'd like to turn off curl's verification of the certificate, use   
 the -k (or --insecure) option.

**Comment by ThomasBerends** [comment]
This is not a problem with Composer.

You can find the answer for your problem here:
https://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-unable-to-get-local-issuer-certificate

**Comment by alcohol** [comment]
This is a client side issue, not server side.
