### ISSUE TITLE
Running with superfluous verbose flags

### ISSUE THREAD

**Issue by andersevenrud** [composer/composer#6857]
If you run composer with *more than three* `-v` verbose flags it will actually run without any verbosity.

Example: `composer install -vvvv`.

This caused quite some confusion, because I expected it to give out the maximum verbosity. I did not realize that I've typed in the wrong amount because there was no warnings from the argument parsing.

**Comment by Seldaek** [comment]
That's an issue in symfony console actually, because those arguments are parsed using some weird way before the rest of the args are parsed.. I am not sure if it's easily fixable, but anyway not really something we can do in Composer I think, and it's not like it happens that often either.
