### ISSUE TITLE
Composer detected version incorrectly

### ISSUE THREAD

**Issue by peter279k** [composer/composer#6859]
- Composer version: 1.5.3
- Composer command: ```composer require satooshi/php-coveralls dev-master```
- Composer error output:
```
[InvalidArgumentException]                                                   
  Could not find package satooshi/php-coveralls in a version matching dev-master
```
As title, the version seems to be incorrect during finding the current version.
But using the Composer version ```1.5.2``` is successful.
I think it's the bug.

**Comment by OndraM** [comment]
Just hit the same issue:

```sh
$ composer --version
Composer version 1.5.2 2017-09-11 16:59:25
$ mkdir test && cd test
$ composer require lmc/steward:dev-master
... Installing lmc/steward (dev-master 3b2f7ee): Cloning 3b2f7ee693 from cache
...
Writing lock file
Generating autoload files
```


```sh
$ composer --version
Composer version 1.5.3 2017-11-30 18:29:43
$ mkdir test-2 && cd test-2
$ composer require lmc/steward:dev-master

                                                                       
  [InvalidArgumentException]                                           
  Could not find package lmc/steward in a version matching dev-master  
                                                                       

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

```

**Comment by Seldaek** [comment]
1.5.4 is out correcting this.

**Comment by thewilkybarkid** [comment]
#6860 still fails for me...

**Comment by peter279k** [comment]
It seems to be failed for me, too....

**Comment by mente** [comment]
Still not working here :-/

**Comment by jakzal** [comment]
What I'm [getting now](https://travis-ci.org/jakzal/phpqa/jobs/309964899#L1294) is: 

>  Package rskuipers/php-assumptions at version dev-master has a PHP requirement incompatible with your PHP version (7.2.0.0) 

But [`rskuipers/php-assumptions`](https://packagist.org/packages/rskuipers/php-assumptions) package doesn't have a PHP version requirement.

**Comment by s7eph4n** [comment]
Not working here, either:
```
$ composer --version
Composer version 1.5.4 2017-12-01 11:02:17

$ composer require 'mediawiki/semantic-media-wiki=~3.0@dev' --update-with-dependencies

  [InvalidArgumentException]                                                   
  Package mediawiki/semantic-media-wiki at version ~3.0@dev has a PHP require  
  ment incompatible with your PHP version (5.6.31.0)                           
```
PHP requirement is `"php": ">=5.5.0"`.

See https://travis-ci.org/SemanticMediaWiki/SemanticResultFormats/jobs/309733763

**Comment by Seldaek** [comment]
Sorry folks, I thought I got to the bottom of it but I guess not. I'll have another look.

**Comment by Seldaek** [comment]
Can you please try after `composer self-update --snapshot` to make sure it's fine for everyone before I tag another one this time? :)

**Comment by OndraM** [comment]
Great, works for me now, thanks for the quick fix!

**Comment by xabbuh** [comment]
👍 fixes it for me

**Comment by Seldaek** [comment]
Alright I'll get another release out then.

**Comment by peter279k** [comment]
It looks good for me when using the version ```1.5.5```.
Thanks for @Seldaek

**Comment by jakzal** [comment]
Ok, this works:

```
composer global req --no-suggest --prefer-dist --update-no-dev -n bmitch/churn-php
composer global req --no-suggest --prefer-dist --update-no-dev -n akeneo/php-coupling-detector
composer global req --no-suggest --prefer-dist --update-no-dev -n rskuipers/php-assumptions:dev-master
```

But this still doesn't (on php 7.2):

```
composer global req --no-suggest --prefer-dist --update-no-dev -n bmitch/churn-php akeneo/php-coupling-detector rskuipers/php-assumptions:dev-master
```

**Comment by peter279k** [comment]
To @jakzal, I also try your command and get the same error output here.
And here is the error output:
```
Using version ^0.4.1 for bmitch/churn-php
Using version ^0.2.0 for akeneo/php-coupling-detector

                                                                               
  [InvalidArgumentException]                                                   
  Package rskuipers/php-assumptions at version dev-master has a PHP requireme  
  nt incompatible with your PHP version (7.2.0.0)                              
                         
```
And I found that the [rskuipers/php-assumptions](https://github.com/rskuipers/php-assumptions/blob/master/composer.json)   ```composer.json``` doesn't present the specific PHP version in require settings.

Perhaps this is the problem and let the Composer detect version incorrectly.
I think we can try to add the specific PHP version in that ```composer.json``` then try to execute command again.

Thanks.

**Comment by peter279k** [comment]
BTW, it worked fine when using Composer version 1.5.2 in PHP 7.2
It seems that the Composer has the bug problem.

**Comment by Seldaek** [comment]
Please don't modify that package at all, as it will break the reproducibility of the bug here. I'll have a look when I get a chance.

**Comment by tomasnorre** [comment]
I have seen a fun behavior here. 

When have reposity 
`
{
            "type": "composer",
            "url": "https://composer.domain.tld"
        }
`
It doesn't work,

but with (satis):
`
{
            "type": "git",
            "url": "git@domain.tld:repository"
        }
`
Then it works, I don't know if it has a relation to satis in combination with composer and satis.

**Comment by Seldaek** [comment]
Ok I think (or hope) we're finally through with all issues here :)

**Comment by jakzal** [comment]
Seems to work now. Thanks @Seldaek :beer:

**Comment by rxu** [comment]
Still fails with 1.5.6 here https://travis-ci.org/phpbb-extensions/ad-management/jobs/320703184
>[InvalidArgumentException]                                                   
  Package phpbb/epv at version dev-master has a PHP requirement incompatible   
  with your PHP version (5.4)

**Comment by Seldaek** [comment]
@rxu Thanks, this is fixed by https://github.com/composer/composer/commit/8a50345df791c3dddd5ec73792f45fc8bc84af42 - not yet in a release but will be included in 1.6.0

**Comment by rxu** [comment]
@Seldaek Thanks. Looking forward for release to check the fix.

**Comment by mehdichaouch** [comment]
Me too ;)
