### ISSUE TITLE
1.5.3 failing to require dev-master package

### ISSUE THREAD

**Issue by thewilkybarkid** [composer/composer#6860]
When I run this command:

```
composer require elife/proofreader-php:dev-master
```

I get the following output:

```
 [InvalidArgumentException]
  Could not find a matching version of package elife/proofreader-php. Check the package spelling, your version constraint and that the package is available in a stability
  which matches your minimum-stability (stable).
```

And I expected this to happen:

`elife/proofreader-php` is installed.

(We actually use it globally (https://github.com/elifesciences/builder-base-formula/blob/master/elife/proofreader-php.sls#L3), but can recreate locally.)

Rolling back to 1.5.2 sees the command work.

**Comment by xabbuh** [comment]
see #6859

**Comment by Seldaek** [comment]
Closing as duplicate
