### ISSUE TITLE
PHP 7.2 - mcrypt

### ISSUE THREAD

**Issue by jiriferkl** [composer/composer#6862]
Hi,
I have just installed php 7.2, where mcrypt is fully removed. But now I can't use composer without installing old and deprecated library. When this will be fixed? 

Thanks

**Comment by marinpurgar** [comment]
What exactly doesn't work. This is from docker container running php:7.2.0-cli-stretch

```
www-data@8693ed4f9f8b:~$ uname -a
Linux 8693ed4f9f8b 4.10.0-38-generic #42-Ubuntu SMP Tue Oct 10 13:24:27 UTC 2017 x86_64 GNU/Linux
www-data@8693ed4f9f8b:~$ php -v
PHP 7.2.0 (cli) (built: Dec  1 2017 01:02:32) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
www-data@8693ed4f9f8b:~$ php composer.phar -V
Composer version 1.5.5 2017-12-01 14:42:57
```

**Comment by alcohol** [comment]
Need a reproducible scenario.

**Comment by jiriferkl** [comment]
Sorry I thought this is enough. 

I use docker container running php:apache. For our purpose I had to enable several php extensions.

`
RUN docker-php-ext-install mcrypt && \
    docker-php-ext-install bcmath
    etc....
` 

But after downloading the latest image with php 7.2 `docker-php-ext-install mcrypt` isn' t working anymore because it has been removed. So now when I run `composer install` it throws `The requested php extension is missing`.

**Comment by alcohol** [comment]
Ok, so, this might seem confusing to you, but that probably means you have a dependency installed (or are trying to install) that requires mcrypt. Because Composer itself does not have a hard dependency on mcrypt.

You can try running:
```
composer why ext-mcrypt
```

**Comment by jiriferkl** [comment]
Oh. Silly me. I've checked this before, but I must have overlooked it so I blamed the composer. Thanks guys.
