### ISSUE TITLE
Local file based git repository 

### ISSUE THREAD

**Issue by DocOlson** [composer/composer#6867]
Hello,

I am quite new to composer and I am trying to set up my magento workflow with it.
I have a local folder which contains my local git (bare) repositories. 

A little cumbersome is the fact that I have to add each repository individually so they can be required.

This works fine:
```json
{
  "repositories": [
    {
      "type": "vcs",
      "url": "/git/magento/om/base"
    },
    {
      "type": "vcs",
      "url": "/git/magento/om/slider"
    },
    {
      "type": "composer",
      "url": "https://packages.firegento.com"
    }
  ],
  "require": {    
    "om/base": "dev-master",
    "om/slider": "dev-master"
  }
}
```

What I would like to have:
```json
{
  "repositories": [
    {
      "type": "vcs",
      "url": "/git/magento/om/*"
    },
    {
      "type": "composer",
      "url": "https://packages.firegento.com"
    }
  ],
  "require": {    
    "om/base": "dev-master",
    "om/slider": "dev-master"
  }
}
```

So I could add more of my modules in the require section without having to add each repository individually.

It somehow does work for the composer repository which lists multiple modules/repositories as well.

Is this somehow possible?

Thank you

**Comment by Seldaek** [comment]
You can do this with the [path](https://getcomposer.org/doc/05-repositories.md#path) repository as it supports `*`. vcs repos only support one package at a time though.

**Comment by DocOlson** [comment]
I tried but it doesn't work.
``
{
  "repositories": [
    {
      "type": "path",
      "url": "/git/magento/free/*"
    }
  ],
  "require": {    
    "jreinke/require-login": "dev-master"
  }
}
``

/git/magento/free/ is a normal folder containing multiple repositories in subfolders.
/git/magento/free/jreinke/require-login is a bare git repository.

The repo contains a composer.json:

`{
    "name": "jreinke/require-login",
    "description": "Require login to access catalog",
    "type": "magento-module",
    "authors": [
        {
            "name": "Johann Reinké"
        }
    ],
    "minimum-stability": "stable",
    "require": {}
}
`

I keep getting "The requested package require-login could not be found in any version".

**Comment by Seldaek** [comment]
If it's in /git/magento/free/jreinke/require-login I think you should use `/git/magento/free/*/*` as `url`

**Comment by DocOlson** [comment]
I tried. Did not work.
Could it be that path only allows relative paths? At least that is what I see all over the internet when looking for examples.

**Comment by Seldaek** [comment]
It finds directories using `glob($this->url, GLOB_MARK | GLOB_ONLYDIR)` so it should support whatever glob supports, and absolute paths too..
