### ISSUE TITLE
[Solver] New proposed approach for --prefer-lowest

### ISSUE THREAD

**Issue by Jean85** [composer/composer#6868]
This is an idea that I'm rambling about since this morning...

I've seen that there are many pending issues with the 2.0 milestone about the solver and related to `--prefer-lowest`, i.e. #6476 #6207 #5355.

Since this option is mainly used to test in CI with the lowest package combination possible, this creates some strange issues. IMHO the main cause stems from the fact that the `require-dev` constraints are taken into consideration too, but they shouldn't in that scenario.

IMHO a good way to fix this issue should be using an alternative solver that:
 - acts like the current one, but only considering the `require` section
 - then goes on to the development requirements, without trying to require the lowest.

This approach could be better, since:
 * the pool of possible versions would be a lot smaller (hence faster resolution)
 * a more desirable behavior would happen, non-dev lowest would have priority
 * if a dev package is preventing a non-dev lowest, we would have an easy and clear error
 * the obvious (and more correct) path would be relaxing the dev requirements

What do you think?

**Comment by curry684** [comment]
Unfortunately, this is not going to work. Have a looksie at this bundle of mine: https://packagist.org/packages/omines/datatables-bundle

We have some optional integrations, for example with Doctrine ORM. As ORM integration is just one of the available integration options, we do not require everyone to install  `doctrine/doctrine-bundle`. So it's in the suggests section where it belongs. It's also in `require-dev` of course as we do want to test the integration. Following your proposal, we'd only ever test with v1.8.1 of that bundle, while we declare compatibility with 1.6.7. Obviously not an intended outcome. Same goes for Twig bundle in this package, and for many other dev dependencies in the future.

If I'm asking for lowest possible requirements, [I want to get the lowest supported version](https://travis-ci.org/omines/datatables-bundle/jobs/310884131#L600).

**Comment by Jean85** [comment]
I think you misunderstood my proposal. I'm not advocating installing multiple versions of dev packages, but just postponing their constraint resolution after resolving the non-dev constraints. This will lead to a "divide et impera" approach of the proposed Solver, with smaller constraints group, that will be easier to solve.

In this way:
 * the non-dev packages will surely have the lowest version possible, without interference from the dev packages
 * the dev packages will have the highest version possible, apart from possible conflicts from the aforementioned ones.

For your specific use case, I think you wouldn't maintain the same, current approach, but instead you would do a specific step in your CI for each optional package.

Let's take Doctrine ORM as the example, so I'll try to explain myself better. You said that your package declares a compatibility of `^1.6.7`; right now, if an other dev package conflict with Doctrine 1.6.7, you could get in trouble without knowing it, because `--prefer-lowest` will install something newer without warning you.

With my proposed approach, you would `composer require doctrine/doctrine-bundle 1.6.7 --no-update` as a pre-step in your CI, requiring **exactly** the lowest preferred version as a **non-dev** requirement, just for the `--prefer-lowest` job, and you would obtain exactly all the lowest non-dev packages, without the dev constraints.

PS: my suggestion doesn't have to be a `--prefer-lowest` replacement, I'm just advocating changing that approach into mine when testing a lib lowest compat situation.

**Comment by stof** [comment]
> I think you misunderstood my proposal. I'm not advocating installing multiple versions of dev packages, but just postponing their constraint resolution after resolving the non-dev constraints.

This does not work, as it might become impossible to satisfy the dev requirements if you resolve them separately.

**Comment by Jean85** [comment]
Well, I hadn't disregarded that scenario; instead, I think it's an issue that my approach wants to resolve: I think that if `--prefer-lowest` is required, a dev constraint that prevents the installation of the real lowest version is an issue for the maintainers of the lib, since you wouldn't be testing what you're requesting.

With this kind of approach, the fact that a dev package is preventing a real lowest installation would be evident, since the Solver would clearly say that the dev package's constraint are preventing him to go forward, and relaxing the lower bounds of the culprit dev package would be the right way to go.

Obviously this would have to be an opt-in behavior, not the default one.

**Comment by nicolas-grekas** [comment]
I think the discussion in #6856 is going in a right direction that'd fx the underlying problem this tries to solve.

**Comment by Jean85** [comment]
Woha, it's basically the same proposal :smile: 
Closing this in favor of that one, I'll reply there.
