### ISSUE TITLE
OpenSSL Failed to enable crypto

### ISSUE THREAD

**Issue by ybelenko** [composer/composer#6870]
Please, help. I cannot install my dependencies.
WampServer Version 3.0.6 64bit
Apache 2.4.23 - PHP 5.6.25 - MySQL 5.7.14
PHP 5.6.25 for CLI (Command-Line Interface)

```
[PHP Modules]
...bash
mysql
mysqli
mysqlnd
odbc
openssl
pcre
PDO
...
[Zend Modules]
```

Output of `composer diagnose`:

```bash
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0
84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D A
FE50952
OK
Checking composer version: OK
```

When I run this command:

```bash
$ composer require vlucas/phpdotenv
```

I get the following output:

```bash
Package operations: 1 install, 0 updates, 0 removals
  - Installing vlucas/phpdotenv (v2.4.0): Downloading (connecting...)
Downloading (connecting...)
Downloading (connecting...)
Failed to download vlucas/phpdotenv from dist: 
The "https://codeload.github.com/vlucas/phpdotenv/legacy.zip/3cc116adbe4b11be5ec557bf1d24dc5e3a21d18c" file could not be downloaded: SSL operation failed with code 
1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
```

**Comment by tomzx** [comment]
See #3346.

This has to do with the certificate file used by your installation of PHP not containing the required certificate to verify github.com. Get an up-to-date list of certificates (from http://curl.haxx.se/ca/cacert.pem for instance), update your PHP configuration to use this certificate and your issue should be resolved.

**Comment by ybelenko** [comment]
It seems that problem solved itself. I didn't change anything, except restarting WAMP. And certificate path looks the same.
```bash
$  php -r "print_r(openssl_get_cert_locations());"
Array
(
    [default_cert_file] => /usr/local/ssl/cert.pem
    [default_cert_file_env] => SSL_CERT_FILE
    [default_cert_dir] => /usr/local/ssl/certs
    [default_cert_dir_env] => SSL_CERT_DIR
    [default_private_dir] => /usr/local/ssl/private
    [default_default_cert_area] => /usr/local/ssl
    [ini_cafile] => C:\wamp64\bin\php\php5.6.25\extras\ssl-cert\cacert.pem
    [ini_capath] =>
)
I didn't found where I can change `default_cert_file` path, but it's obviously WAMP or even `php_openssl` extension problem, not yours.
It would be very helpfull to see absolute path to cert file when *error:14090086:SSL* occures. Right now you don't know which one cert file is broken and WAMP server contains a lot of cert files and configs.

**Comment by ybelenko** [comment]
And the problem comes back with another package.
```bash
$ composer require egulias/email-validator
```
Output:
```bash
You are running Composer with SSL/TLS protection disabled.
Using version ^2.1 for egulias/email-validator
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing doctrine/lexer (v1.0.1): Downloading (connecting...)
Downloading (connecting...)
Downloading (connecting...)    
Failed to download doctrine/lexer from dist: The "https://codeload.github.com/doctrine/lexer/legacy.zip/83893c552fd2045dd78aef794c31e694c37c0b8c" file could not be downloaded: SSL operation failed with code 
1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
```
I've tried already:
- Both php5.6.25 and php7.0.10
- Download certificate from http://curl.haxx.se/ca/cacert.pem
- Different certificates and configs from `openssl_get_cert_locations()`
- WAMP restarting many many times
- PC reboot

**Comment by ybelenko** [comment]
Any workaround maybe?
I cannot install from dist because of SSL problem. Meanwhile I can install from source most of packages which is slow, annoying but I can live with that. But now I'm facing package which I cannot install neither from dist nor from source.
```bash
$ composer require squizlabs/php_codesniffer --dev
```
And output is:
```bash
You are running Composer with SSL/TLS protection disabled.
Using version ^3.2 for squizlabs/php_codesniffer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing squizlabs/php_codesniffer (3.2.2): Downloading (connecting...)
Downloading (connecting...)
Downloading (connecting...)    Failed to download squizlabs/php_codesniffer from dist: The "https://codeload.github.com/squizlabs/PHP_CodeSniffer/legacy.zip/d7c00c3000ac0ce79c96fcbfef86b49a71158cd1" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
    Now trying to download from source
  - Installing squizlabs/php_codesniffer (3.2.2): Cloning d7c00c3000 from cache

  [Symfony\Component\Process\Exception\ProcessTimedOutException]
  The process "git clone --no-checkout "https://github.com/squizlabs/PHP_Code
  Sniffer.git" "C:\wamp64\www\PHPLeads\vendor\squizlabs\php_codesniffer" --di
  ssociate --reference "C:/Users/Yuriy/AppData/Local/Composer/vcs/https---git
  hub.com-squizlabs-PHP-CodeSniffer.git/" && cd /D "C:\wamp64\www\PHPLeads\ve
  ndor\squizlabs\php_codesniffer" && git remote add composer "https://github.
  com/squizlabs/PHP_CodeSniffer.git" && git fetch composer" exceeded the time
  out of 300 seconds.

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...
```

I did try to download package manually and unzip it to `vendor/squizlabs/php_codesniffer`, but every `composer install` script erases this folder and tries to download it again without success.

Please, help me to unzip package manually, because it seems to me that issue with SSL will never be solved.

**Comment by ybelenko** [comment]
It's embarassing, but it's not completely my fault.

Finally, I've spotted weird DNS settings of my internet connection.
As it turns out it was Mail.ru Trojan or something.
This malicous script changes preferred and alternate DNS servers.
When you're trying to download any zip, exe or file without extension it swaps this file with zipped malicious exe file.

Dr. Web and Malwarebytes didn't help, however.
After adjustment to correct DNS servers everything works perfect.

**Comment by mzf** [comment]
Same issue :(


  [Composer\Downloader\TransportException]
  The "https://api.github.com/repos/ghunti/HighchartsPHP/zipball/548b321478510ec1559432a9baabbfba1a1e559a" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
  error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
  Failed to enable crypto
  failed to open stream: operation failed

**Comment by mzf** [comment]
Fixed by disable Kaspersky Antivirus

**Comment by SlimSavernake** [comment]
thank you mzf!!!!!

**Comment by roslov** [comment]
@mzf, thanks disabling KIS helped!

**Comment by evinkuraga** [comment]
@mzf ... 3 hours wasted doing all sorts of different things. I wish I found your post first! Thanks!

**Comment by olivia-outshine** [comment]
Ask you friends
Php : 7.2
Centos: 7.4
Composer: 1.6.5
Whether the certificate has been replaced, or it will prompt the verification to fail
```
[Composer\Downloader\TransportException]                                                                                               
  The "https://composer.czxb.com/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:  
  error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed                                                      
  Failed to enable crypto                                                                                                                
  failed to open stream: operation failed
```

**Comment by marcovtwout** [comment]
@mzf More specifically, this issue is caused by Kaspersky AntiVirus scanning encrypted connections. This component can be disabled through `Settings > Additional > Network > Do not scan encrypted connections`.

**Comment by saravananvelu** [comment]
@mzf Thank you.

**Comment by chopoti** [comment]
Thank you, it was Kaspersky issue, Lost two days..kah

**Comment by usman84** [comment]
Here it is, I'm facing the same issue while requiring  **composer require drush/drush:8.x**

`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20160303/geos.so' - /usr/lib/php/20160303/geos.so: cannot open shared object file: No such file or directory in Unknown on line 0`

`[Composer\Downloader\TransportException]
  The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
  error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
  Failed to enable crypto
  failed to open stream: operation failed`

Still wasting a lot of time on it. Any help?

**Comment by hojaonline** [comment]
@roslov Thanks! I was struggling with this for many hours. Disabling Kaspersky do the job.

Cheers!

**Comment by kdomenick** [comment]
Same error message(s) as the original issue from @ybelenko.  Running a Red Hat 7 box behind a firewall with PHP 7.1.8 and Composer 1.7.2.  Tried all the certificate adjustments, permissions, etc.  In my case it was resolved by a firewall adjustment, adding the exception to our firewall and URL filtering blade.

**Comment by brianbui171** [comment]
F**k Kas. wast me a lot of times.

**Comment by jgmuchiri** [comment]
In my case, it was the CA Cert file that was the culprit

Open terminal and run `php -r "var_dump(openssl_get_cert_locations());"`
 
Note the location of `default_cert_file`. It might say `\usr\local\ssl\cert.pem`
Verify that that file exists. If not, download the cacert.pem file from https://curl.haxx.se/ca/cacert.pem and place it in somewhere preferably in `/usr/local/ssl`

You now have a file is `usr/local/ssl/cacert.pem`

Open your php.ini and add the location of the file `openssl.cafile=cacert.pem`

Run `composer config --global cafile "/usr/local/ssl/cacert.pem"`

**Comment by quincy-soeliman** [comment]
@jgmuchiri Thanks! This fixed it for me.

**Comment by karudonaldson** [comment]
> In my case, it was the CA Cert file that was the culprit
> 
> Open terminal and run `php -r "var_dump(openssl_get_cert_locations());"`
> 
> Note the location of `default_cert_file`. It might say `\usr\local\ssl\cert.pem`
> Verify that that file exists. If not, download the cacert.pem file from https://curl.haxx.se/ca/cacert.pem and place it in somewhere preferably in `/usr/local/ssl`
> 
> You now have a file is `usr/local/ssl/cacert.pem`
> 
> Open your php.ini and add the location of the file `openssl.cafile=cacert.pem`
> 
> Run `composer config --global cafile "/usr/local/ssl/cacert.pem"`

Thanks @jgmuchiri for pointing in the right direction.

If it's of any use to others, I use valet+ 1.0.26, composer 1.8.4 OSX Movajes 10.14.3, php7.3 and simply specifying the cert composer looks for with: 
`composer config --global cafile "/usr/local/etc/openssl/cert.pem"`

Fixed it for me.

**Comment by sazzadh88** [comment]
Thanks

> > In my case, it was the CA Cert file that was the culprit
> > Open terminal and run `php -r "var_dump(openssl_get_cert_locations());"`
> > Note the location of `default_cert_file`. It might say `\usr\local\ssl\cert.pem`
> > Verify that that file exists. If not, download the cacert.pem file from https://curl.haxx.se/ca/cacert.pem and place it in somewhere preferably in `/usr/local/ssl`
> > You now have a file is `usr/local/ssl/cacert.pem`
> > Open your php.ini and add the location of the file `openssl.cafile=cacert.pem`
> > Run `composer config --global cafile "/usr/local/ssl/cacert.pem"`
> 
> Thanks @jgmuchiri for pointing in the right direction.
> 
> If it's of any use to others, I use valet+ 1.0.26, composer 1.8.4 OSX Movajes 10.14.3, php7.3 and simply specifying the cert composer looks for with:
> `composer config --global cafile "/usr/local/etc/openssl/cert.pem"`
> 
> Fixed it for me.

This worked for me.

**Comment by maximebourdel** [comment]
Same problem for me, with this config :

   - local windows with avast 
   - VM with ubuntu trying to send mail
Avast on my local was Stopping my VM from sending mails after I tried to switching date from GMT to UTC with : error:14090086:SSL

At the second I desactivated Avast on local, it worked ! 
Lost 4 hours on this problem, thank you avast...

**Comment by shohagsb** [comment]
I just used a trick. that is I just removed the 's' from the https://. Use "http://" instead "https://"
this worked for me. Let me know if this works for you too. Thanks

**USE THIS CODE:**
php -r "copy('http://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

**Comment by jrbecart** [comment]
I solved this by disconnecting my VPN (from work)

**Comment by myrage18** [comment]
> It's embarassing, but it's not completely my fault.
> 
> Finally, I've spotted weird DNS settings of my internet connection. As it turns out it was Mail.ru Trojan or something. This malicous script changes preferred and alternate DNS servers. When you're trying to download any zip, exe or file without extension it swaps this file with zipped malicious exe file.
> 
> Dr. Web and Malwarebytes didn't help, however. After adjustment to correct DNS servers everything works perfect.

There is nothing embarassing... Your solution is fixing my problem. I used PLDT on a different condo and everything was fine, and since I moved out to a different condo and transferred my PLDT connection here... I started to have problems, not being able to access my own server and using Cloudflare DNS or Google DNS on my router now allow me to access all my stuff normally. My local server can now connect using SSL on my developing server without issues... Wasted time looking at the code while the problem was from the ISP.

Thank you

**Comment by its-leofisher** [comment]
> In my case, it was the CA Cert file that was the culprit
> 
> Open terminal and run `php -r "var_dump(openssl_get_cert_locations());"`
> 
> Note the location of `default_cert_file`. It might say `\usr\local\ssl\cert.pem` Verify that that file exists. If not, download the cacert.pem file from https://curl.haxx.se/ca/cacert.pem and place it in somewhere preferably in `/usr/local/ssl`
> 
> You now have a file is `usr/local/ssl/cacert.pem`
> 
> Open your php.ini and add the location of the file `openssl.cafile=cacert.pem`
> 
> Run `composer config --global cafile "/usr/local/ssl/cacert.pem"`

Worked for me on windows 11 via wsl with ubuntu distro

```
["default_cert_file"]=>
  string(21) "/usr/lib/ssl/cert.pem"
```
