### ISSUE TITLE
Issue with symfony 4.x: incompatibility with outputformatter constructor

### ISSUE THREAD

**Issue by daften** [composer/composer#6871]
In Factory.php:241 a new OutputFormatter is created like this:
```
$formatter = new OutputFormatter(null, $styles);
```

However, the constructor has changed in Symfony 4 to use a boolean as first argument:
```
public function __construct(bool $decorated = false, array $styles = array())
```

See
https://github.com/composer/composer/blame/master/src/Composer/Factory.php
and
https://github.com/symfony/symfony/blame/master/src/Symfony/Component/Console/Formatter/OutputFormatter.php

**Comment by curry684** [comment]
This is weird, I would expect this to be covered by unit tests. Observation is most certainly correct that this can't work.

**Comment by curry684** [comment]
Oh I see, your project is including `dev-master`. You should include either tags or the 1.5 branch if you expect any kind of stability.

The `master` branch contains the upcoming Composer upgrade and is not fit for realworld usage yet.

**Comment by daften** [comment]
I'll try that! thanks :)

I also think that not all potential latest versions are tested, if you use composer as a library, since there is a composer.lock file in this project.

**Comment by daften** [comment]
Hi @curry684 
I don't remember why i chose dev-master. I guess because we use git-flow and I assumed master was safe, not incorporating different requirements like for composer. I've now pinned my composer.json to ^1 so it stays on major version 1, it should be fine now.

Thanks for the help and sorry for the dumb mistake on my part.

**Comment by Seldaek** [comment]
Well, master targets 1.6 at the moment, so sooner or later this will be released as a stable version and you'll have the issue again, so maybe we should fix this if there is an actual problem? I guess we should just pass false as that's what it was cast to before, and anyway this value doesn't matter as it's being overwritten by https://github.com/symfony/symfony/blob/3ce9c29ae44692555d15983c7537187f5566e9ce/src/Symfony/Component/Console/Output/Output.php#L44 - I'll commit some fix.

**Comment by daften** [comment]
Was figuring this was going to show up in unit tests at some point, so it would be fixed then. Thanks for the anticipated fix!
