### ISSUE TITLE
Drupal 8 basic install any need to edit composer.json file?

### ISSUE THREAD

**Issue by PebbleSun** [composer/composer#6874]
Hi

I am doing a vanilla install of Drupal 8 using the drupal-project script at github. I have downloaded Drupal and intend to install it manually through the browser.

I was wondering with this basic installation is there any need to make any changes to the composer.json file?

Thanks for your help.

**Comment by tomzx** [comment]
You're more likely to find the appropriate support @ https://www.drupal.org/support than here. This is for bugs/features requests related to composer, not for support for other software (such as Drupal).
