### ISSUE TITLE
Move "scripts-description" to toplevel

### ISSUE THREAD

**Issue by mbrodala** [composer/composer#6881]
With #6672 a new config option `scripts-description` was added to provide description for custom commands.

Since this was implemented as `extra` config option every change here requires a update of the `composer.lock` file. This is not really useful since changes to script descriptions don't affect package states or similar at all.

Thus I propose to move `scripts-description` toplevel which also allows to put them next to `scripts`.

**Comment by Seldaek** [comment]
Yeah I agree having this in extra is kinda weird as it's not an third-party feature really but a built-in Composer one. Would you like to work on a patch? It'll require updating the json schema as well as a couple of classes. /cc @alcohol @thom8 any counter-opinion?

**Comment by thom8** [comment]
Agreed, top level would be preferable, I hadn't considered this case thanks @mbrodala

**Comment by alcohol** [comment]
No counter opinion.
