### ISSUE TITLE
Is it possible to get bash colors from redirected scripts?

### ISSUE THREAD

**Issue by igorsantos07** [composer/composer#6884]
I saw some search results pointing to different solutions depending on the target script, but is there any way to completely redirect the original script output into my terminal, or should there be?

-------------------------------

My `composer.json`:

```json
...
    "scripts": {
        "run": "php -S localhost:8080 -t public"
    },
...
```

Output of `composer diagnose`: Everything is ok - including colored output.

When I run this command:

```
composer run
```

I get the following output:
![selection_018](https://user-images.githubusercontent.com/532299/33791377-0bbe234e-dc72-11e7-8216-d0282274c336.png)

And I expected this to happen:
_(note some output is also gone, like URL and folder details)_
![selection_020](https://user-images.githubusercontent.com/532299/33791390-457d355c-dc72-11e7-95b9-356019f03bea.png)

**Comment by Seldaek** [comment]
This is an issue of tty and color support detection, etc. It's way more complex than just forwarding all output, which we do. I don't really think it's worth the amount of work either. You can easily run things without composer if needed.

**Comment by igorsantos07** [comment]
Got it :)

I thought it could indeed he more complex, but only found patches or edge
cases, so I filled an  issue so at least the overall thing is documented
for future searches :)

Thanks!
