### ISSUE TITLE
multiple versions of packages

### ISSUE THREAD

**Issue by zomorod** [composer/composer#6890]
How to use multiple versions of packages or the ability to place those packages in site specific directories.
I do not know but I think this is a kind of bug. 

Thank you

**Comment by curry684** [comment]
Multiple versions are not possible due to how autoloading works in PHP.  Composer works in site specific directories by definition.

**Comment by zomorod** [comment]
What is a solution for it ?

**Comment by curry684** [comment]
I don't know. The question you asked has no solution, but you didn't share your actual problem. 

So explain what you want to achieve and we may be able to think with you. Right now this issue screams XY at me.
