### ISSUE TITLE
Composer php_network_getaddresses: getaddrinfo failed?

### ISSUE THREAD

**Issue by MB34** [composer/composer#6891]
(Windows7, PHP 5.6.31)
Attempting to run a diagnose in the laravel-master directory, I get these results
I do have HTTP_PROXY env variable set

    Checking composer.json: OK
    
    Checking platform settings: OK
    
    Checking git settings: OK
    
    Checking http connectivity to packagist: WARNING
    [Composer\Downloader\TransportException] The "http://packagist.org/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: No such host is known. 
    failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known. 
    
    Checking https connectivity to packagist: WARNING
    [Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: No such host is known. 
    failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known. 
    
    Checking HTTP proxy: FAIL
    [Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: No such host is known. 
    failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known. 
    
    Checking HTTP proxy support for request_fulluri: WARNING
    Unable to assess the situation, maybe packagist.org is down (The "http://packagist.org/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: No such host is known. 
    failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known. )
    
    Checking HTTPS proxy support for request_fulluri: WARNING
    Unable to assess the situation, maybe github is down (The "https://api.github.com/repos/Seldaek/jsonlint/zipball/1.0.0" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: No such host is known. 
    failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known. )
    
    Checking github.com rate limit: FAIL
    [Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: No such host is known. 
    failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known. 
    
    Checking disk free space: OK
    
    Checking pubkeys: FAIL
    
    Missing pubkey for tags verification
    
    Missing pubkey for dev verification
    
    Run composer self-update --update-keys to set them up
    
    Checking composer version: 
    [Composer\Downloader\TransportException]
    The "https://getcomposer.org/versions" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: No such host is known. failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known.

I can ping packagist.org just fine:

    C:\wamp\www\laravel-master>ping packagist.org
    Pinging packagist.org [87.98.253.214] with 32 bytes of data:    
    Reply from 87.98.253.214: bytes=32 time=147ms TTL=45    
    Reply from 87.98.253.214: bytes=32 time=147ms TTL=45

**Comment by alcohol** [comment]
Then it would appear your proxy configuration is incorrect.

**Comment by shiny** [comment]
got the same problem in docker on ubuntu

**Comment by zqunor** [comment]
So am I.  Waiting for solutions....

**Comment by alcohol** [comment]
My initial reply was incorrect.

"getaddrinfo failed" indicates a resolving error, meaning your host/machine/container is unable to resolve packagist.org
