### ISSUE TITLE
Require command should add dependency with letter case from it's name in composer.json

### ISSUE THREAD

**Issue by kubawerlos** [composer/composer#6892]
Having empty `composer.json` whether I run `composer require squizlabs/PHP_CodeSniffer` or composer `composer require squizlabs/PhP_CoDeSNiFFeR` I should end up with:
```json
{
    "require": {
        "squizlabs/php_codesniffer": "^3.1"
    }
}
```
as `squizlabs/php_codesniffer` is the [name of the package](https://github.com/squizlabs/PHP_CodeSniffer/blob/3.1.1/composer.json#L2).

**Comment by Seldaek** [comment]
Fixed by #6912
