### ISSUE TITLE
Composer fetches invalid versions with minimum-stability: dev

### ISSUE THREAD

**Issue by helhum** [composer/composer#6897]
My `composer.json`:

```json
{
    "minimum-stability" : "dev",
     "require": {
        "typo3/cms": "^8.7"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer install
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 25 installs, 0 updates, 0 removals
  - Installing typo3/cms-composer-installers (1.4.5): Loading from cache
  - Installing typo3/class-alias-loader (dev-master d067bad): Cloning d067bad74a from cache
  - Installing symfony/yaml (dev-master 5748d4f): Cloning 5748d4fb71 from cache
  - Installing symfony/finder (dev-master db49fa8): Cloning db49fa8f34 from cache
…
```

And I expected this to happen:

[typo3/cms 8.7](https://packagist.org/packages/typo3/cms#v8.7.9) defines a dependency to [symfony/yaml](https://packagist.org/packages/symfony/yaml) `"symfony/yaml": "^2.7 || ^3.0"`

symfony/yaml dev-master has a branch alias 4.1.x-dev and a branch 3.4 identified as 3.4.x-dev

I would expect composer to not install dev-master of symfony/yaml (aka 4.1.x) because typo3/cms requests this package to be a lower version than 4.0.0

So I would expect symfony/yaml 3.4.x-dev to be installed instead.

Same for symfony/finder

The (to me) interesting thing is, that if I have the following root composer.json

```
{
    "minimum-stability" : "dev",
     "require": {
        "symfony/yaml": "^2.7 || ^3.0"
    }
}
```

on `composer install` i get:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing symfony/yaml (3.4.x-dev afe0cd3): Cloning afe0cd3848 from cache
…
```

So if the package is referenced in root composer.json everything works as expected.

**Comment by sascha-egerer** [comment]
Try `composer config prefer-stable true` and then run `composer install` again. Is that what you would expect?

**Comment by helhum** [comment]
> Try composer config prefer-stable true and then run composer install again. Is that what you would expect?

nope, not my point. My point is, that composer resolves dependencies with wrong/ conflicting constraints, when minimum-stability is set to dev. Of course I can change the config or add prefer-stable, but composer should still resolve correct versions with the setting mentioned.

**Comment by sascha-egerer** [comment]
Well just checked the dependencies of typo3/cms 8.7 and it has 
`symfony/yaml: ^2.7 || ^3.0 || ^4.0` 
and not `symfony/yaml: ^2.7 || ^3.0`

But i get your point and i always prevent that behavior you describe with the prefer-stable config.

**Comment by helhum** [comment]
ah, sorry, my bad. I looked at the 8.7.8 dependencies. OK, so nothing wrong here
