### ISSUE TITLE
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

### ISSUE THREAD

**Issue by ghost** [composer/composer#6898]
Hi,

because of the new restrictions of Google for SSL certificates I created own signed multi domain certificates. My local web developments, I do about XAMPP and phpstorm.

After I created these certificates for one multi domain project, I realized that I got issues with the composer. I got issues with the composer itself and with the composer, when I wanted to make updates for frameworks like Laravel. 

Because I didn't really know what I had to do, I wanted to make a reinstall of the composer. 

Now I always get this error message and I don't know how I can fix it.
```
The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
```

The steps, what I already did are to set everything back in xampp, what I changed for SSL.

I also downloaded the follow thing [http://curl.haxx.se/ca/cacert.pem](http://curl.haxx.se/ca/cacert.pem) and implemented it to XAMPP by curl.cainfo and openssl.cafile.

**Comment by alcohol** [comment]
Composer does not use curl. So setting that will not solve anything. It does look at openssl.cafile and openssl.capath though. But you can also provide custom configuration in your composer.json and such. So I would suggest to double check all your configurations/files.

**Comment by ForzaSFerrari** [comment]
What composer.json do you mean, if the composer is uninstalled?

**Comment by proimage** [comment]
Try this solution: https://stackoverflow.com/a/16134586/999556
