### ISSUE TITLE
[Feature Request] store completely vendor to cache for composer.lock

### ISSUE THREAD

**Issue by fico7489** [composer/composer#6909]
Suppose we have two branches (branch_a and branch_b), each branch have different composer.lock. If we have to switch between two branches (two compser.lock) very often it takes to much time calling composer install. It would be nice to have some flag e.g. --full-cache to store completely vendor folder

currently : 
```
git checkout branch_a
composer install
git checkout branch_b
composer install
git checkout branch_a
composer install
```

last "git checkout branch_a" takes e.g. 1,2 minute

with  --full-cache flag : 
```
git checkout branch_a
composer install --full-cache
git checkout branch_b
composer install --full-cache
git checkout branch_a
composer install
```

last "git checkout branch_a" now takes e.g. few second...

**Comment by tomzx** [comment]
Are you pulling git repositories as part of your dependencies or is everything distributed packages (zip files)?

**Comment by fico7489** [comment]
I have a branch for laravel 5.5. and laravel 5.4. and I need often to switch between those branches and after each switch, I have to hit composer install or composer update and this takes 1-2 minutes...I suppose many people have staging and production with a different composer.lock and this feature could help a loot.

**Comment by Seldaek** [comment]
I don't really feel like there is such a big use case for this.. The times where you have such big differences in dependencies between two branches are pretty rare, and you could also work around it in a different way. For example how about having two checkouts of your project? One on each branch, if you work on them both regularly it might be easier?
