### ISSUE TITLE
[suggestion] use `__DIR__` instead of `dirname(__FILE__)`

### ISSUE THREAD

**Issue by zerkms** [composer/composer#6910]
Given `composer` requires php >= v5.3.2 to run, how about replacing

```php
$vendorDir = dirname(dirname(__FILE__));
```
with
```php
$vendorDir = dirname(__DIR__);
```
everywhere?

**Comment by tomzx** [comment]
Other than in the generated fixtures, did you find it elsewhere?

**Comment by zerkms** [comment]
Oh, I'm sorry. The instances I'm referring to are in the autoloader.

**Comment by Seldaek** [comment]
Composer requires 5.3 but the autoloader can work on 5.2, which is why we don't use __DIR__
