### ISSUE TITLE
dev-master is not resolved in branch-alias in Subversion repository

### ISSUE THREAD

**Issue by AnrDaemon** [composer/composer#6922]
With `composer.json` like this in a Subversion repo:

```json
{
    …
    "extra": {
        "branch-alias": {
            "dev-master": "1.x-dev"
        }
    },
    …
}
```

installation fails with:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package vendor/project ^1.7@dev exists as vendor/project[dev-trunk] but these are rejected by your constraint.
```

There's a workaround for this, though - just add dev-trunk the same way:

```json
{
    …
    "extra": {
        "branch-alias": {
            "dev-trunk": "1.x-dev",
            "dev-master": "1.x-dev"
        }
    },
    …
}
```

But I don't think it's a desirable behavior.

**Comment by AnrDaemon** [comment]
I understand, why this works the way it works, but this worth a note in the documentation.
IMO.

**Comment by Seldaek** [comment]
Not sure I understand the problem.. You can alias any named branch, if it's called trunk then you have to alias dev-trunk.

**Comment by AnrDaemon** [comment]
Ok, sorry. My bad.
This is not a problem per se. Just a configuration caveat.
The issue is that in Subversion repository "master" branch is /trunk, and in certain cases it is transparently aliased (i.e. for purposes of `require …:dev-master`), but not when you explicitly declare branch-alias.
