### ISSUE TITLE
missing newline before "Writing $path"

### ISSUE THREAD

**Issue by staabm** [composer/composer#6924]
trigger a `composer global remove friendsofphp/php-cs-fixer -vvv` (after you had it installed at first) and you get a lot of output...what stands out is, that it seems it would benefit from a additional newline in the marked place:

![grafik](https://user-images.githubusercontent.com/120441/34202158-36d58640-e577-11e7-81f3-47348070e0d3.png)

Output of `composer diagnose`:

```
$ php -v
PHP 7.1.2 (cli) (built: Feb 14 2017 21:24:45) ( NTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

$ composer --version
Composer version 1.5.6 2017-12-18 12:09:18

$ composer diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

tested on windows10x64 in a bash (mingw64) which was automatically installed when installing Github for Desktop[1]

[1]: https://desktop.github.com/

**Comment by Seldaek** [comment]
Closing as v2 output is very different, there are probably such things to fix as well but frankly the -vvv output isn't optimized to be pretty..
