### ISSUE TITLE
check-platform-reqs does not work fine

### ISSUE THREAD

**Issue by stof** [composer/composer#6925]
My `composer.json`:

```json
{
    "require": {
        "php": "7.1.*",
        "ext-amqp": "*",
        "ext-apcu": "*",
        "ext-ftp": "*",
        "ext-intl": "*",
        "ext-mbstring": "*",
        "ext-openssl": "*",
        "ext-pcntl": "*"
    }
}
```

Plus a lot of other non-platform requirements of course

When I run this command:

```
php7.2 $(which composer) check-platform-reqs
```

I get the following output:

```
php            7.2.0       success
```

And I expected this to happen:

Telling me that my PHP version is wrong (as PHP 7.2.0 does not match the `7.1.*` constraint)

**Comment by hollodotme** [comment]
Same here. I tested the following constraints:

| Constraint | Output |
|------------|--------|
| `"php": ">=7.1"` | `php 7.2.0 success` (correct) |
| `"php": "7.1.12"` | `php 7.2.0 failed` (correct) |
| `"php": "7.1.*"` | `php 7.2.0 success` (not correct) |
| `"php": "^7.1.0"` | `php 7.2.0 success` (not correct) |
| `"php": "~7.1.0"` | `php 7.2.0 success` (not correct) |

**Comment by stof** [comment]
> "php": "^7.1.0" 	php 7.2.0 success (not correct)

that case is actually correct. `^7.1.0` means `>=7.1.0, <8`

**Comment by hollodotme** [comment]
@stof You're right.  I fixed the comment.

**Comment by stof** [comment]
anyway, this is now fixed in the snapshot channel.
