### ISSUE TITLE
Memory_limit as an optional value

### ISSUE THREAD

**Issue by PurpleBabar** [composer/composer#6931]
Hi Guys :D

Thanks a lot for composer, the tool is amazing, But i have a lots of issue where the memory limit value is exceeded, and i think a lot of people have. I have composer installed globally and it's kinda annoying to have to call it by path to change the memory limit, would you be open to a pull request to just accept an options in composer command for the memory_limit value ? something as -m 3G for exeample ?

Thanks a lot for your answer, 
Happy to help if i can :)

**Comment by Seldaek** [comment]
Right now we force the memory_limit to be at least 1.5G. Maybe that's not enough and we should just force it to -1 always.. Anyone has a reason not to?

**Comment by PurpleBabar** [comment]
The -1 could be an option, but the option in the composer command seems a litlle less wild and extreme  imo :p

**Comment by PurpleBabar** [comment]
So great ! :D 

Thank you so much, it's gonna save to a lot of us a great amount of time ;)
