### ISSUE TITLE
Include the current progress when installing or updating packages

### ISSUE THREAD

**Issue by dannyhajj** [composer/composer#6932]
Sometimes, when using composer, there would be lots of packages that need to be updated or installed. Especially when we use a framework. For example, when I'm trying to install Magento 2, Composer needs to install a total of 249 packages. It would be nice if Composer can help us figure out the current progress.

When we are installing or updating packages with Composer, we get an output similar to the following 
```
Package operations: 249 installs, 0 updates, 0 removals
  - Installing magento/magento-composer-installer (0.1.12): Loading from cache
  - Installing magento/zendframework1 (1.13.1): Loading from cache
  - Installing zendframework/zend-stdlib (2.7.7): Loading from cache
....
```

However, during installation, it would be nice to know the current progress. Can the `Installing ...` messages be prepended with the progress of packages installed? It would be similar to Debian's apt approach when apt is downloading packages.

Here are some examples of how it may work (I think the second example is the best):

```
Package operations: 249 installs, 15 updates, 3 removals
  - [Install: 1] Installing magento/magento-composer-installer (0.1.12): Loading from cache
  - [Install: 2] Installing magento/zendframework1 (1.13.1): Loading from cache
  - [Install: 3] Installing zendframework/zend-stdlib (2.7.7): Loading from cache
....
  - [Update: 1] Updating zendframework/zend-stdlib (2.7.7): Loading from cache
  - [Update: 2] Updating zendframework/zend-stdlib (2.7.7): Loading from cache
....
  - [Removal: 1] Removing zendframework/zend-stdlib
  - [Removal: 2] Removing zendframework/zend-stdlib
  - [Removal: 3] Removing zendframework/zend-stdlib
```
or the following:
```
Package operations: 249 installs, 15 updates, 3 removals
  - [Install: 1/249] Installing magento/magento-composer-installer (0.1.12): Loading from cache
  - [Install: 2/249] Installing magento/zendframework1 (1.13.1): Loading from cache
  - [Install: 3/249] Installing zendframework/zend-stdlib (2.7.7): Loading from cache
....
  - [Update: 1/15] Updating zendframework/zend-stdlib (2.7.7): Loading from cache
  - [Update: 2/15] Updating zendframework/zend-stdlib (2.7.7): Loading from cache
....
  - [Removal: 1/3] Removing zendframework/zend-stdlib
  - [Removal: 2/3] Removing zendframework/zend-stdlib
  - [Removal: 3/3] Removing zendframework/zend-stdlib
```

A third alternative would be to sum everything up (but this may be a bit confusing)

```
Package operations: 249 installs, 15 updates, 3 removals
  - [1/267] Installing magento/magento-composer-installer (0.1.12): Loading from cache
  - [2/267] Installing magento/zendframework1 (1.13.1): Loading from cache
  - [3/267] Installing zendframework/zend-stdlib (2.7.7): Loading from cache
....
  - [250/267] Updating zendframework/zend-stdlib (2.7.7): Loading from cache
  - [251/267] Updating zendframework/zend-stdlib (2.7.7): Loading from cache
....
  - [265/267] Removing zendframework/zend-stdlib
  - [266/267] Removing zendframework/zend-stdlib
  - [267/267] Removing zendframework/zend-stdlib
```

**Comment by Seldaek** [comment]
Something that might be considered in 2.0 IMO once we do bigger refactorings to the install process.

**Comment by Seldaek** [comment]
Considering this again, I think we rather not do it and keep the output simpler. Seeing progress might help you a little mentally in long installs but our goal is to make the installs faster, and after all there is nothing much more you can do than wait for it to finish.

**Comment by simplenotezy** [comment]
What about a --progress flag? I am dealing with a `composer global update` that has currently run for ages without any updates. Would be helpful to see if it's stuck somewhere.
