### ISSUE TITLE
git tag not picked up correctly

### ISSUE THREAD

**Issue by minac** [composer/composer#6933]
**Problem**: Composer seems to create the correct branch after the name of the relevant tag, but not actually change its contents.

**Steps**:
I have a dependency on my composer file from a bitbucket repo:

```json
(...)
  "repositories": [
    {
      "type" : "composer",
      "url"  : "https://wpackagist.org"
    },
    {
      "type" : "git",
      "url"  : "git@bitbucket.org:randomprovider/myprovider-ce.git"
    } 
 ],
  "require": {
    "hirak/prestissimo": "~0.3.7",
    "wpackagist-plugin/akismet": "~4.0.1",
    "wpackagist-plugin/amp": "~0.5.1",
(...)
    "myprovider/myprovider-ce": "0.0.14"
  }
  "extra" : {
    "installer-paths" : {
      "wp-content/plugins/{$name}/" : ["type:wordpress-plugin"],
      "wp-content/themes/{$name}/" : ["type:wordpress-theme"]
    }

(...)
```

The repository has version tags like v0.0.14 and v0.0.15.
When I do composer install for the latest version (0.0.15) and then want to switch back to 0.0.14, it seems to be picking up the latest code in master and calling it branch with the correct tag (in this case 0.0.14) like so:

```
Installs: myprovider/myprovider-ce:v0.0.14
  - Installing myprovider/myprovider-ce (v0.0.14): Executing command (CWD): git --version

    Cloning to cache at '/home/ubuntu/.cache/composer/vcs/git-bitbucket.org-randomprovider-myprovider-ce.git/'
Executing command (/home/ubuntu/.cache/composer/vcs/git-bitbucket.org-randomprovider-myprovider-ce.git/): git rev-parse --git-dir
Executing command (/home/ubuntu/.cache/composer/vcs/git-bitbucket.org-randomprovider-myprovider-ce.git/): git remote -v
Executing command (/home/ubuntu/.cache/composer/vcs/git-bitbucket.org-randomprovider-myprovider-ce.git/): git remote set-url origin 'git@bitbucket.org:randomprovider/myprovider-ce.git' && git remote update --prune origin
Cloning master from cache
Executing command (CWD): git clone --no-checkout 'git@bitbucket.org:randomprovider/myprovider-ce.git' 'wp-content/plugins/myprovider-ce/' --dissociate --reference '/home/ubuntu/.cache/composer/vcs/git-bitbucket.org-randomprovider-myprovider-ce.git/' && cd 'wp-content/plugins/myprovider-ce/' && git remote add composer 'git@bitbucket.org:randomprovider/myprovider-ce.git' && git fetch composer
Executing command (wp-content/plugins/myprovider-ce/): git branch -r
Executing command (wp-content/plugins/myprovider-ce/): git checkout -B 'v0.0.14' 'composer/master' -- && git reset --hard 'composer/master' --
    REASON: Required by the root package: Install command rule (install myprovider/myprovider-ce v0.0.14)
```

Looking at the filesystem, the correct "branch" seems to be selected:
```bash
ubuntu@ip-10-0-0-1:/var/www/mywebsite.com/wp-content/plugins/myprovider-ce$ git branch
  master
* v0.0.14
  v0.0.15
```

But then when looking at the content of the main file (which has the version in tandem with the tag version), we see that it never left 0.0.15:

```bash
ubuntu@ip-10-0-0-1:/var/www/mywebsite.com/wp-content/plugins/myprovider-ce$ head myprovider-ce.php <?php
/*
Plugin Name: My Provider C. E.
Plugin URI:
Description:
Version: 0.0.15
Author: Random provider
Author URI: https://randomprovid.er/
Text Domain: myprovider-ce
License: GPL-2.0+
```

Looking up at the git commands I don't see anything that pulls the correct tag like `git checkout tags/<tag_name> -b <branch_name>`.

All I want to do is to select the preferred tag in _composer.json_ and then run `composer update` and it fetching the right tag from the git repo.

Am I doing something wrong here? Or is this a bug?

Thanks.

**Comment by Seldaek** [comment]
It seems like part of the problem is you're using branches instead of tags, but it should nonetheless not be creating a branch from master like it seems to be doing at:

```
Executing command (wp-content/plugins/myprovider-ce/): git branch -r
Executing command (wp-content/plugins/myprovider-ce/): git checkout -B 'v0.0.14' 'composer/master' -- && git reset --hard 'composer/master' --
```

The weird thing here is composer/master which in the code is `'composer/'.$reference` so it seems like the reference for the branch somehow is `master` unless I misunderstand something.

In any case it would be very helpful to have a public repository with which to reproduce this, because as such it's just guess work.

**Comment by minac** [comment]
Hi Jordi,

Thank you for the reply.

Now, I don’t understand. I am using tags which are inside the master branch
of the git repo. So what I expect to see if composer cloning the master
branch, and checking out a specific tag which is what is specified in
composer.json. No just creating a local branch with the name of the tag and
not checking the correct code out.

I’m afraid that the repos I’m working with are all private so I don’t have
a public example for you.

—
Miguel
IT Infrastructure Engineer <https://www.linkedin.com/in/migueldavid/> -
migueldavid.eu

On 22 December 2017 at 15:25:18, Jordi Boggiano (notifications@github.com)
wrote:

It seems like part of the problem is you're using branches instead of tags,
but it should nonetheless not be creating a branch from master like it
seems to be doing at:

Executing command (wp-content/plugins/myprovider-ce/): git branch -r
Executing command (wp-content/plugins/myprovider-ce/): git checkout -B
'v0.0.14' 'composer/master' -- && git reset --hard 'composer/master'
--

The weird thing here is composer/master which in the code is
'composer/'.$reference so it seems like the reference for the branch
somehow is master unless I misunderstand something.

In any case it would be very helpful to have a public repository with which
to reproduce this, because as such it's just guess work.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/composer/composer/issues/6933#issuecomment-353618788>,
or mute the thread

**Comment by Seldaek** [comment]
Yeah the question is can you make a dummy public repo that lets us reproduce it? Otherwise I doubt this is fixable given the information provided.

**Comment by minac** [comment]
I can't replicate it with fresh public repos...
Here are the repos:
https://gitlab.com/migueldavid/masterproject.git
https://migueldavid@bitbucket.org/migueldavid/childproject.git

Out of laziness I created a docker container from the composer image:
Dockerfile
```
FROM composer
RUN apk add git
RUN git clone https://gitlab.com/migueldavid/masterproject.git
RUN git clone https://bitbucket.org/migueldavid/childproject.git
CMD bash```

And then executed it and did `composer install -vvv` and everything works as it should. There is a checkout of the tag and a reset hard following it..

```
Executing command (/tmp/cache/vcs/https---bitbucket.org-migueldavid-childproject.git/): git rev-parse --git-dir
Executing command (/tmp/cache/vcs/https---bitbucket.org-migueldavid-childproject.git/): git remote -v
Executing command (/tmp/cache/vcs/https---bitbucket.org-migueldavid-childproject.git/): git remote set-url origin 'https://bitbucket.org/migueldavid/childproject.git' && git remote update --prune origin
Cloning fac0a735941c1d9348028927e6bc9b3bcb59c5ef from cache
Executing command (CWD): git clone --no-checkout 'https://bitbucket.org/migueldavid/childproject.git' '/app/masterproject/vendor/migueldavid/childproject' --dissociate --reference '/tmp/cache/vcs/https---bitbucket.org-migueldavid-childproject.git/' && cd '/app/masterproject/vendor/migueldavid/childproject' && git remote add composer 'https://bitbucket.org/migueldavid/childproject.git' && git fetch composer
Executing command (/app/masterproject/vendor/migueldavid/childproject): git branch -r
Executing command (/app/masterproject/vendor/migueldavid/childproject): git checkout 'v1.1' --
Executing command (/app/masterproject/vendor/migueldavid/childproject): git reset --hard 'fac0a735941c1d9348028927e6bc9b3bcb59c5ef' --
    REASON: Required by the root package: Install command rule (install migueldavid/childproject v1.1)
```

So I don't get why I keep getting the same issue with the setup I showed before... :(

**Comment by minac** [comment]
They have a `"reference": "master"` under `source`, that may be it.

**Comment by minac** [comment]
Nope, that was not it. I simply can't seem to replicate it with a different (open) repository. Giving up on this one for now.
