### ISSUE TITLE
[Feature request] replaced-by key

### ISSUE THREAD

**Issue by greg0ire** [composer/composer#6934]
Some packages, like `symfony/polyfill-mbstring` do things only if an extension like `ext-mbstring` is missing. I think a configuration key that would act as the inverse of `replaces` could be useful in that kind of case.

**Comment by javiereguiluz** [comment]
How would this work for packages like `symfony/polyfill-php56` where the install rule is: *"ignore this package if PHP version is PHP 5.6 or higher"*.

**Comment by greg0ire** [comment]
@javiereguiluz you're right, it should probably not be that simple. I think it could look like this:

```
    "name": "symfony/polyfill-php56",
    "replaced-by": {
        "php": ">=7.0"
    }
```

or


```
    "name": "symfony/polyfill-mbstring",
    "replaced-by": {
        "ext-mbstring": "*"
    }
```

**Comment by Seldaek** [comment]
Closing as I don't think this is likely to happen. It's too complex for what it brings IMO, installing a bit of code that's not needed isn't the worst problem.
