### ISSUE TITLE
Redundant prefixLengthsPsr4 lookup in ClassLoader::findFileWithExtension()

### ISSUE THREAD

**Issue by drscre** [composer/composer#6937]
I am looking at the following piece of code from [ClassLoader::findFileWithExtension](
https://github.com/composer/composer/blob/master/src/Composer/Autoload/ClassLoader.php#L375):

```php
if (isset($this->prefixLengthsPsr4[$first])) {
    $subPath = $class;
    while (false !== $lastPos = strrpos($subPath, '\\')) {
        $subPath = substr($subPath, 0, $lastPos);
        $search = $subPath.'\\';
        if (isset($this->prefixDirsPsr4[$search])) {
            $length = $this->prefixLengthsPsr4[$first][$search]; // === $lastPos + 1 === strlen($search) ?
            foreach ($this->prefixDirsPsr4[$search] as $dir) {
                if (file_exists($file = $dir . DIRECTORY_SEPARATOR . substr($logicalPathPsr4, $length))) {
                    return $file;
                }
            }
        }
    }
}
```
And it seems to me that `$length = $this->prefixLengthsPsr4[$first][$search];` is the same as the length of `$search` which in turn is equal to `$lastPos + 1`.

As far as i understand, `$length` is the length  of namespace prefix we want to substitute for directory.
So, probably to avoid `strlen($search)` function call (is it that slow?), the length of namespace prefix is looked up in pre-computed prefix length map `$this->prefixLengthsPsr4`:

`$length = $this->prefixLengthsPsr4[$first][$search];`

But it turns out even this lookup is redundant, because we already know the prefix length after calling `strrpos`:

`$length = $lastPos + 1;`

P.S.
`substr($logicalPathPsr4, $length)` can also be taken out of `foreach ($this->prefixDirsPsr4[$search] as $dir)` loop

**Comment by Seldaek** [comment]
Good catch, this allows to simplify the code a little.
