### ISSUE TITLE
auto update

### ISSUE THREAD

**Issue by robertnicjoo** [composer/composer#6938]
hi,
this is not an issue is mostly curiosity question,
I'm working on laravel project which supports composer by default to install packages and i was wondering if there is any possible way to get list of all available updates on composer including laravel itself and by clicking on some button being able to update production mode app?

something like wordpress update system, you get notification about new update and you click on update button then booom everything is new without need of any terminal or code typing.

is that possible?

**Comment by mhujer** [comment]
You can run `composer outdated` to check for the latest package versions.

I think that Wordpress is testing the updates compatibility, so they won't break the website.
But if you updated all the packages in `composer.json`, it would probably break the application.

**Comment by Seldaek** [comment]
There is no UI for composer
