### ISSUE TITLE
Composer Not Working due to MongoDB

### ISSUE THREAD

**Issue by AyushSurana97** [composer/composer#6943]
I have a Windows 10 x64 PC and am trying to install Composer so as to use it with MongoDB
The Error that I am getting is this : - 

**The PHP exe file you specified did not run correctly:
C:\xampp\php\php.exe

The php.ini used by your command-line PHP is: C:\xampp\php\php.ini

A setting in your php.ini could be causing the problem: Either the 'extension_dir' value is incorrect or the dll does not exist.

Program Output:
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_mongodb.dll' - The specified module could not be found.
 in Unknown on line 0**

I have downloaded and added my mongodb.dll file from https://pecl.php.net/package/mongodb 
and added the proper extension in the php.ini file. I don't know what the problem is.

Any help will be highly appreciated ...

**Comment by johnstevenson** [comment]
If your extension_dir value is `"ext"` and your extension entry is `extension=php_mongodb.dll`, then you have probably downloaded a version that is not compatible with your PHP (version, thread-safety or bitness).
