### ISSUE TITLE
[docs] Libraries - Lock file

### ISSUE THREAD

**Issue by mhujer** [composer/composer#6950]
The [Libraries - Lock file documentation](https://getcomposer.org/doc/02-libraries.md#lock-file) states:

> For your library you may commit the `composer.lock` file if you want to. This can help your team to always test against the same dependency versions. However, this lock file will not have any effect on other projects that depend on it. It only has an effect on the main project.

I may be missing something, but the advise does not seem right. Imagine this scenario:

- You are creating a library which depends on some public packages.
- You specify quite loose constraints in `composer.json`
- You generate and commit `composer.lock`
- Locked versions are used by CI server as well as other colleagues (and everything works smoothly)
- After some time, you use the library in a project and other versions of dependencies are installed, which were never tested with the library (and they may break)

I think that the user would be better off if the `composer.lock` was not versioned at all, right?

**Comment by Seldaek** [comment]
You can't really test your library against all versions of all dependencies so typically people do a build with an update and a build with an update --prefer-lowest, and that's kinda good enough. If you want to have the lock file in or not is a philosophical question really that I don't want to take position on in the docs.
