### ISSUE TITLE
suggestions of the root-package are not printed to the screen

### ISSUE THREAD

**Issue by daniela-waranie** [composer/composer#6953]
My `composer.json`:

```json
{
    "name": "bug/example",
    "description": "This composer.json shows that the suggest-block defined at root-package is not printed to the screen.",
    "type": "project",
    "license": "proprietary",
    "require": {
        "mfacenet/hello-world": "*"
    },
    "suggest": {
        "ext-pdo_mysql": "Needed for database connectivity to mysql servers.",
        "ext-pdo_pgsql": "Needed for database connectivity to postgreSQL servers.",
        "monolog/monolog": "Allows more advanced logging of the application flow"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
require.mfacenet/hello-world : unbound version constraints (*) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK

```

When I run this command:

```
php composer.phar install
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing mfacenet/hello-world (v1.0.4): Downloading (100%)         
mfacenet/hello-world suggests installing zendframework/zendframework (Most awesome framework ever)
Writing lock file
Generating autoload files

```

And I expected this to happen:
I expect to get all suggestions defined in each package incl. root-package. Expected output:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing mfacenet/hello-world (v1.0.4): Downloading (100%)         
bug/example suggests installing ext-pdo_mysql (Needed for database connectivity to mysql servers.)
bug/example suggests installing ext-pdo_pgsql (Needed for database connectivity to postgreSQL servers.)
bug/example suggests installing monolog/monolog (Allows more advanced logging of the application flow)
mfacenet/hello-world suggests installing zendframework/zendframework (Most awesome framework ever)
Writing lock file
Generating autoload files
```

Ubuntu 17.10
Composer version 1.5.6 2017-12-18 12:09:18
PHP 7.0.22-0ubuntu0.17.04.1 (cli) (built: Aug  8 2017 22:03:30) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans
    with Zend OPcache v7.0.22-0ubuntu0.17.04.1, Copyright (c) 1999-2017, by Zend Technologies

Also tested on most-up-to-date raspbian image:
Linux raspberrypi 4.9.59+ #1047 Sun Oct 29 11:47:10 GMT 2017 armv6l GNU/Linux
Composer version 1.5.6 2017-12-18 12:09:18
PHP 7.0.19-1 (cli) (built: May 11 2017 14:04:47) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.19-1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by Seldaek** [comment]
I am not sure why root package suggestions should be included, considering you are in charge of the root package and as such they are your own suggestions..

**Comment by curry684** [comment]
I see the use case - it looks like TS is distributing a project that can be configured by the end user with different database backends, and if the customer wants advanced logging they should install monolog.

I personally think something like that should be in the product manual next to the instruction on how to actually configure the DSN and the log target, as right now the suggestions are just hollow calls to install something.... and then what.

**Comment by alcohol** [comment]
I guess the only logical scenario might be during a `create-project` run. But considering how that works, I do not really see this being feasible (can hardly differentiate it from a regular `install`). I have never considered the "suggestions" part very useful anyway. Documentation should handle that IMHO.

**Comment by daniela-waranie** [comment]
I really like composer (and any other dependency manager / package manager), because:
- it is (or should be) the single point of truth
- it can be part of an automated process

I don't want to spread my dependency definitions accross multiple places (wikis, readmes and dependency tool config files, etc.). Not for hard dependencies, not for optional dependencies / suggestions.

As far a i know composer it is not situation-aware! Means i do not try to guess if you are a developer, contributor, an administrator, a normal user, a CI server (build time, packaging time, testing time, deployment time, etc.), at developer machine, at staging environment or at production environment, on a singel user project or on a project with thousands of forks and contributors. And that is a good design decision from my point of view.

When you think about dependencies/suggestions you may have a specific workflow, project style or something else in mind, but i think a tool does it very well, when not forcing a special style. 

Maybe we do not need suggestions at all in composer. But when there is a suggestion-feature in composer it should do it consistent. I do not see a point, to ignore root-level suggestions at all. If a single (core) developer want to make aware all its thousands of contributors/users of a new suggestion - the single point of truth should be composer. The main audience for suggestions are developers and administrators (i guess) - both should carefully read logs / outputs, but tend to not read manuals - and if they feel familar with a software they often stop reading documentation after the first install (on updates, subsequent installs). Printing root-level suggestions would be consistent behavior and help to manage large contributor/user bases.

Each project can enforce a project level policy to handle suggestions a different way, but from my point of view composer should not force a specific way of working with suggestions.

If you realy want to have suggestions written to other places you can optional could grab composers output (suggestion lines) in build and release process and push it to the readme file for that release, as you maybe do already. Generated redundancy is better than manually redundancy or spreading information around to different places.

**Comment by alcohol** [comment]
> tend to not read manuals

Really? Cause that is the first thing I read of pretty much anything I use (or consider using).

IMHO, people who do not read manuals deserve to get burned (as in, you reap what you sow, face the consequences, etc).

> composer should not force a specific way of working with suggestions

Composer does not force anything. It is a tool.

--

If you want consistency, I will gladly accept a PR that removes the "suggestions" functionality in its entirety. Though I doubt I could get @Seldaek to agree on that :d

**Comment by curry684** [comment]
I don't read manuals for kitchen appliances or USB chargers.

In manuals on how to install complex software I read every word three times.

**Comment by daniela-waranie** [comment]
@alcohol i agree, when not making this feature consistent i would vote for removing it entirely.
