### ISSUE TITLE
Limit connection time during download process

### ISSUE THREAD

**Issue by webmake** [composer/composer#6957]
My `composer.json`:

```json
{
....
    "config": {
        "secure-http": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true,
        "platform": {
            "php": "7.1"
        },
	"process-timeout" : 10
    }
}
```
So I used `process-timeout` and expected to minimize waiting time due too long downloading package.json file, but finally I always get an error after 60s, error `file_get_contents(https://satis***.com/packages.json): failed to open stream: Connection timed out`  

I think https://github.com/composer/composer/blob/master/src/Composer/Util/RemoteFilesystem.php#L300 should be passed an option, how long to try to connect, because now it not clear while waiting, what is the reason of failure. 

It's not a problem, but a proposal.

In my case by adding this code solved waiting time
```
    public static function getContext($url, array $defaultOptions = array(), array $defaultParams = array())
    {
        $options = array('http' => array(
            // specify defaults again to try and work better with curlwrappers enabled
            'follow_location' => 1,
            'max_redirects' => 20,
            'timeout' => 2,
        ));
```

**Comment by Seldaek** [comment]
You can try to define it inside the repository:

```
{
  "repositories": [{
    "type": "composer",
    "url": "https://satis.example.org",
    "options": {
      "http": {
        "timeout": 2
      }
    }
  }]
}
```

**Comment by webmake** [comment]
Sadly, but seems it has no effect
