### ISSUE TITLE
[RFC] Optional requirements 

### ISSUE THREAD

**Issue by sebastianblum** [composer/composer#6965]
Hello!

I want to discuss if we can add support for optional dependencies to composer.

Problem explained by the LiipImagineBundle:
The LiipImagineBundle:2.0 had an dependency to PHP-CS-FIXER
```json
{
  "require-dev": {
    "friendsofphp/php-cs-fixer": "^1.0|^2.0"
  }
}
```
and PHP-CS-Fixer doesn't support PHP 7.3 see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.9/composer.json
```json
{
  "require": {
        "php": "^5.6 || >=7.0 <7.3"
  }
}
```
See discussion https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3323 - PHP-CS-FIXER will not support PHP 7.3 at the moment. So the nightly php travis builds fail because composer could not resolve the dependencies. LiipImagineBundle now removed PHP-CS-FIXER dependency
 at the moment.

How can we solve the problem in composer?

One solution will be to add support for optional requirements which can be installed or skipped.
What do you think about this?

Related Issues (I found)
- #6321 use case for conflict

Possible syntax
```json
{
  "optional": {
    "friendsofphp/php-cs-fixer": "^1.0|^2.0"
  }, 
  "optional-dev": {
    "friendsofphp/php-cs-fixer": "^1.0|^2.0"
  }
}
```
or question mark before
```json
{
  "require-dev": {
    "?friendsofphp/php-cs-fixer": "^1.0|^2.0"
  }
}
```
or dash for skipped
```json
{
  "require-dev": {
    "friendsofphp/php-cs-fixer": "^1.0|^2.0|-"
  }
}
```

Thank you very much

**Comment by Seldaek** [comment]
Probably not going to support this ever so closing..
