### ISSUE TITLE
[Docs] Explicitly mention not to use `apt-get install composer`

### ISSUE THREAD

**Issue by wouterj** [composer/composer#6967]
Since `symfony/thanks` is now required by Laravel and Symfony, there are quite some people looking for help because they get "symfony/thanks depends on composer-plugin-api ^1.1, you are using 1.0".

In all these cases (i.e. https://github.com/symfony/symfony-docs/issues/8938), it is because they are using Composer 1.0.0 beta2 installed through `apt-get`.

Can the Composer community do something to avoid people using `apt-get` and installing this very old version of Composer? Can we show some alert, just like it used to do in beta phrase? Can we maybe explicitly tell in the docs *not* to use `apt-get`? Or, maybe simpler, can we make `apt-get` install a more recent version?

*EDIT: Just released I probably created this issue in a very wrong repository. Sorry! If you want, I can reopen it in another repository.*

**Comment by Seldaek** [comment]
I am not sure what to do about this.. People installing via apt-get probably do so because they prefer that method, some prefer it in quite a religious fashion even. I doubt docs are gonna help much there. As for updating the version that apt-get installs, that's definitely not our jurisdiction here.

**Comment by nicolas-grekas** [comment]
Can be closed once https://github.com/symfony/flex/pull/303 is merged.

**Comment by nicolas-grekas** [comment]
oups, I thought I was on some Symfony repo :)

**Comment by nicolas-grekas** [comment]
Still, can be closed, see https://github.com/symfony/thanks/pull/37
