### ISSUE TITLE
zlib_decode() data error

### ISSUE THREAD

**Issue by alcanardanangelo** [composer/composer#6970]
I can use Composer before. But now I cannot do composer update. I can't even install composer. The error shows. I didn't change any configuration on my computer.

````The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: HTTP request failed!
The "https://getcomposer.org/download/1.5.6/composer.phar.sig" file could not be downloaded: failed to open stream: HTTP request failed!
Failed to decode zlib stream

Please help. Thanks!

**Comment by mrkalmdn** [comment]
Getting the same error. Any update on this?

**Comment by ace411** [comment]
I'm experiencing a similar issue.

**Comment by ace411** [comment]
![composer-issues](https://user-images.githubusercontent.com/11040337/35700356-d18df110-07a3-11e8-9eb5-202d69b7f312.JPG)

**Comment by alcanardanangelo** [comment]
Hi, this is a network problem. There is a policy set up our company firewall. I just ask our network administrator to turn off the firewall policy whenever I want to install a library. :)

**Comment by mrkalmdn** [comment]
Same issue. Same solution. Lol.
