### ISSUE TITLE
Unify versions in composer show

### ISSUE THREAD

**Issue by kubawerlos** [composer/composer#6971]
Currently running `composer show` will display some versions prefixed with `v` and some without (depending of the convention adopted by author):

```bash
squizlabs/php_codesniffer             3.2.2              PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a defined set of coding standards.
symfony/config                        v3.4.2             Symfony Config Component
```

List would look much better if we get rid of the `v` prefix, wouldn't it?

**Comment by localheinz** [comment]
@kubawerlos 

What do you think about also normalizing elsewhere, for example, when updating packages?

**Comment by alcohol** [comment]
I think being precise is more valid in this case. Versions match tags and/or branches. Leaving off the `v` can be confusing.

**Comment by Seldaek** [comment]
Yeah I tend to agree, I don't think it's good to mess with user data like that.
