### ISSUE TITLE
composer does not fully check versions when changing repository URL

### ISSUE THREAD

**Issue by schmunk42** [composer/composer#6972]
My `composer.json`:

```json
{
    "name": "tobias/issue-composer-repo-url-downgrade",
    "require": {
        "dektrium/yii2-rbac": "^0.3.0"
    },
    "repositories": {
        "rbac": {
            "type": "vcs",
            "url": "https://github.com/dmstr-forks/yii2-rbac.git"
        }
    }
}
```

(You need https://github.com/fxpio/composer-asset-plugin or https://asset-packagist.org/ to reproduce - but the plugin or additional repo is not the cause for this issue)

Output of `composer diagnose`:

```
> composer diagnose
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: WARNING
You are not running the latest stable version, run `composer self-update` to update (1.5.2 => 1.5.6)
```

When I run this command:

```
composer update -vv
<remove repositories section>
composer update -vv
```

I get the following output:

```
[...]
Analyzed 405 packages to resolve dependencies
Analyzed 3081 rules to resolve dependencies
Nothing to install or update
Writing lock file
Generating autoload files
```

And I expected this to happen:

```
[...]
Dependency resolution completed in 0.006 seconds
Analyzed 404 packages to resolve dependencies
Analyzed 3078 rules to resolve dependencies
Package operations: 1 install, 0 updates, 0 removals
Installs: dektrium/yii2-rbac:0.3.0
  - Installing dektrium/yii2-rbac (0.3.0): Loading from cache
 Extracting archive    REASON: Required by the root package: Install command rule (install dektrium/yii2-rbac 0.3.0)

Writing lock file
Generating autoload files
```

We're using a fork of `dektrium/yii2-rbac` which has a tag `0.3.999`, if we remove the custom fork-repo, composer should check only the versions in the original URL and downgrade to `0.3.0` in this case, but it sees the installed version - which should not be available at all now - as valid and stays on `0.3.999`.

Related to https://github.com/composer/composer/issues/3876#issue-64525212

It works, when I remove `vendor/dektrium/yii2-rbac` - there should be some additional checks to https://github.com/composer/composer/pull/3985 if a URL has been changed. Actually composer should treat the package as not available and force a full check of it's versions.
 
[addon]

Clearing the cache has no effect.

**Comment by artemmolotov** [comment]
Any news?

**Comment by Seldaek** [comment]
Closing as super old and I think maybe it works better with 2.x now, but who knows :)
