### ISSUE TITLE
Autoload issues in 1.6.1

### ISSUE THREAD

**Issue by PascalBrouwers** [composer/composer#6977]
My `composer.json`:

```json
{
  "name": "ho-nl/opposuits",
  "description": "Opposuits website",
  "authors": [
    {
      "name": "H&O",
      "email": "info@h-o.nl"
    }
  ],
  "minimum-stability": "dev",
  "require": {
    "ho-nl/ruleprice": "dev-master",
    "magento-hackathon/perfect_watermarks": "dev-fix-missing-interpolation",
    "loewenstark/url_indexer": "dev-master",
    "reach-digital/php-connector-lib": "dev-master",
    "reach-digital/magento1-netsuite": "dev-master",
    "reach-digital/magento1-phpconnectorlib": "dev-master",
    "ho-nl-fork/netsuite-php": "dev-master",
    "guzzlehttp/oauth-subscriber": "~0.3"
  },
  "repositories": {
    "0": {
      "type": "vcs",
      "url": "git@github.com:ho-nl/magento1-Ho_RulePrice.git"
    },
    "1": {
      "type": "vcs",
      "url": "git@github.com:ho-nl-fork/magento1-FireGento_PerfectWatermarks.git"
    },
    "2": {
      "type": "vcs",
      "url": "git@github.com:ho-nl-fork/Loewenstark_UrlIndexer.git"
    },
    "3": {
      "type": "composer",
      "url": "https://packages.firegento.com"
    },
    "reach-digital/php-connector-lib": {
      "type": "vcs",
      "url": "git@github.com:ho-nl/php-connector-lib.git"
    },
    "reach-digital/magento1-netsuite": {
      "type": "vcs",
      "url": "git@github.com:ho-nl/magento1-NetSuite.git"
    },
    "reach-digital/magento1-phpconnectorlib": {
      "type": "vcs",
      "url": "git@github.com:ho-nl/magento1-PhpConnectorLib.git"
    },
    "ho-nl-fork/netsuite-php": {
      "type": "vcs",
      "url": "git@github.com:ho-nl-fork/netsuite-php.git"
    },
    "chrisboulton/php-resque-scheduler": {
      "type": "vcs",
      "url": "git@github.com:chrisboulton/php-resque-scheduler.git"
    },
    "ho-nl-fork/php-resque-retry": {
      "type": "vcs",
      "url": "git@github.com:ho-nl-fork/php-resque-retry.git"
    }
  },
  "extra": {
    "magento-root-dir":"./",
    "auto-append-gitignore": true
  }
}
```

When I run this command:

```
composer install
n98-magerun.phar sys:url:list (trigger an autoload)
```

I get the following output:

```
Uncaught Error: Class 'ReachDigital\PhpConnectorLib\Resque\ExponentialRetryPlugin' not found in ... vendor/reach-digital/php-connector-lib/register.php
```

Works fine when installing with composer 1.5.6. Breaks when installing with composer 1.6.1

**Comment by Seldaek** [comment]
Could you try if it still fails with 1.6.1 if you delete the vendor dir before running install? Just trying to see if it's an issue when upgrading the vendor dir from 1.5.6 to 1.6.1 or if it's always a problem with 1.6.1.

**Comment by Seldaek** [comment]
Also can you share the autoload configuration for reach-digital/php-connector-lib?

**Comment by PascalBrouwers** [comment]
Sure, the json is
```
{
    "name": "reach-digital/php-connector-lib",
    "description": "Library to create a connector with any eCommerce PHP Platform (M1/M2/etc.)",
    "type": "library",
    "license": "COMMERCIAL",
    "authors": [
        {
            "name": "Paul Hachmang",
            "email": "paul@h-o.nl"
        }
    ],
    "minimum-stability": "stable",
    "autoload": {
        "files" : [ "register.php" ],
        "psr-4": { "ReachDigital\\PhpConnectorLib\\": "./" }
    },
    "require": {
        "chrisboulton/php-resque": "dev-master",
        "chrisboulton/php-resque-scheduler": "dev-master",
        "ho-nl-fork/php-resque-retry": "dev-master"
    },
    "repositories": {
        "chrisboulton/php-resque-scheduler": {
            "type": "vcs",
            "url": "git@github.com:chrisboulton/php-resque-scheduler.git"
        },
        "ho-nl-fork/php-resque-retry": {
            "type": "vcs",
            "url": "git@github.com:ho-nl-fork/php-resque-retry.git"
        }
    }
}
```

I removed the vendor folder before doing an install. I tested this with 1.5.6 and 1.6.1. As well as redoing the install with 1.6.1 or 1.5.6.

The only difference is the version of the composer.phar I use.

**Comment by Seldaek** [comment]
Ok and next to that composer.json is a `Resque/ExponentialRetryPlugin.php` file with that class in it right? Why is that not working on 1.6 is odd but thanks I'll try to reproduce here.

**Comment by PascalBrouwers** [comment]
That is correct. It should have been loaded from the register.php:
```
$retry = new \ReachDigital\PhpConnectorLib\Resque\ExponentialRetryPlugin();
```

**Comment by PascalBrouwers** [comment]
Good luck! Let me know if I should test something when you have a fix.

**Comment by iconico** [comment]
I also had the exact same error going from 1.5.6 to 1.6.1.
This caused some huge issues this morning, please can you retest as this is clearly not an isolated incident!

**Comment by laurin1** [comment]
I have tested all version from 1.56 to 1.6.1, including 1.6.0-RC and the failure occurs in 1.6.0 for 2 packages (referenced above).

**Comment by Seldaek** [comment]
Ok could someone with the problem please check if it works again after a `composer self-update --snapshot && composer dump-autoload` ? Because I can't reproduce here.

**Comment by webflo** [comment]
Its working fine for me.

**Comment by Seldaek** [comment]
@webflo is that meaning the latest snapshot fixes it, or you did not experience the bug at all? @laurin1 @iconico @PascalBrouwers anyone to check if it is better? Then I can release a 1.6.2..

**Comment by webflo** [comment]
@Seldaek The snapshot works fine, i could reproduce the error with composer 1.6.1 before. 👍

**Comment by bobvandevijver** [comment]
So, I have a similar issue with composer since version 1.6.0 (tested on 1.6.1, 1.6.0 and 1.5.6, only 1.5.6 works). For me, it is even more isolated, as I only get the autoload issue in the phpunit docker container. Running phpunit without docker does not impose any issues. My stacktrace:

```
PHP Fatal error:  Uncaught Error: Class 'Symfony\Bridge\PhpUnit\DeprecationErrorHandler' not found in /builds/snt/wesp-ldap-admin/vendor/symfony/phpunit-bridge/bootstrap.php:39
Stack trace:
#0 /builds/snt/wesp-ldap-admin/vendor/composer/autoload_real.php(66): require()
#1 /builds/snt/wesp-ldap-admin/vendor/composer/autoload_real.php(56): composerRequire4804725fa48ab2d89d297929141c3bbd('92c8763cd6170fc...', false)
#2 /builds/snt/wesp-ldap-admin/vendor/autoload.php(7): ComposerAutoloaderInit4804725fa48ab2d89d297929141c3bbd::getLoader()
#3 /tmp/vendor/phpunit/phpunit/src/Util/Fileloader.php(64): include_once('/builds/snt/wes...')
#4 /tmp/vendor/phpunit/phpunit/src/Util/Fileloader.php(48): PHPUnit\Util\Fileloader::load('/builds/snt/wes...')
#5 /tmp/vendor/phpunit/phpunit/src/TextUI/Command.php(991): PHPUnit\Util\Fileloader::checkAndLoad('/builds/snt/wes...')
#6 /tmp/vendor/phpunit/phpunit/src/TextUI/Command.php(788): PHPUnit\TextUI\Command->handleBootstrap('/builds/snt/wes...')
#7 /tmp/vendor/phpunit/phpunit/src/TextUI/Command.php in /builds/snt/wesp-ldap-admin/vendor/symfony/phpunit-bridge/bootstrap.php on line 39
```

**Comment by martinschumann** [comment]
Ran into same error with Contao Composer Client and Composer >= 1.6.0
<pre>
Fatal error: Uncaught exception Error with message Class 'Composer\Factory' not found thrown in system\modules\!composer\src\ClientBackend.php on line 294
</pre>

Updating to latest snapshot and dump-autoload solved it for me.

**Comment by Seldaek** [comment]
Ok great thanks folks. I'll try and get this release in a bit.

**Comment by thepedroferrari** [comment]
Also in 1.6+ whenever I am launching sage/trellis I get:

`non-zero return code
PHP Fatal error:  Uncaught Error: Class 'Dotenv\Dotenv' not found in
/srv/www/conversionista.no/current/config/application.php:17
Stack trace:
#0 phar:///usr/bin/wp/php/WP_CLI/Runner.php(1070) : eval()'d code(7):
require_once()
#1 phar:///usr/bin/wp/php/WP_CLI/Runner.php(1070): eval()
#2 phar:///usr/bin/wp/php/WP_CLI/Runner.php(1032):
WP_CLI\Runner->load_wordpress()
#3 phar:///usr/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php(23):
WP_CLI\Runner->start()
#4 phar:///usr/bin/wp/php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->p
rocess(Object(WP_CLI\Bootstrap\BootstrapState))
#5 phar:///usr/bin/wp/php/wp-cli.php(23): WP_CLI\bootstrap()
#6 phar:///usr/bin/wp/php/boot-phar.php(8): include('phar:///usr/bin...')
#7 /usr/bin/wp(4): include('phar:///usr/bin...')
#8 {main}
  thrown in /srv/www/conversionista.no/current/config/application.php on line
17
failed: [default] (item=conversionista.no) => {"changed": true, "cmd": ["wp", "core", "install", "--allow-root", "--url=http://conversionista.dev", "--title=conversionista.no", "--admin_user=The One", "--admin_password=admin", "--admin_email=webmaster@conversionista.se"], "delta": "0:00:00.088409", "end": "2018-01-05 12:11:11.338428", "item": "conversionista.no", "rc": 255, "start": "2018-01-05 12:11:11.250019", "stderr_lines": ["PHP Fatal error:  Uncaught Error: Class 'Dotenv\\Dotenv' not found in /srv/www/conversionista.no/current/config/application.php:17", "Stack trace:", "#0 phar:///usr/bin/wp/php/WP_CLI/Runner.php(1070) : eval()'d code(7): require_once()", "#1 phar:///usr/bin/wp/php/WP_CLI/Runner.php(1070): eval()", "#2 phar:///usr/bin/wp/php/WP_CLI/Runner.php(1032): WP_CLI\\Runner->load_wordpress()", "#3 phar:///usr/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\\Runner->start()", "#4 phar:///usr/bin/wp/php/bootstrap.php(75): WP_CLI\\Bootstrap\\LaunchRunner->process(Object(WP_CLI\\Bootstrap\\BootstrapState))", "#5 phar:///usr/bin/wp/php/wp-cli.php(23): WP_CLI\\bootstrap()", "#6 phar:///usr/bin/wp/php/boot-phar.php(8): include('phar:///usr/bin...')", "#7 /usr/bin/wp(4): include('phar:///usr/bin...')", "#8 {main}", "  thrown in /srv/www/conversionista.no/current/config/application.php on line 17"], "stdout": "", "stdout_lines": []}

RUNNING HANDLER [common : reload nginx] ****************************************
changed: [default]

RUNNING HANDLER [common : perform nginx reload] ********************************
changed: [default]
        to retry, use: --limit @/home/vagrant/trellis/dev.retry

PLAY RECAP *********************************************************************
default                    : ok=96   changed=7    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.`


The same works fine on composer 1.5.6, but not >=1.6.0

**Comment by Seldaek** [comment]
Alright 1.6.2 is out, please do tell if you still have issues with it /cc @nicolas-grekas

**Comment by pfrenssen** [comment]
1.6.2 fixes it for me.
