### ISSUE TITLE
[RuntimeException] Could not scan for classes inside "src/" which does not appear to be a file nor a folder

### ISSUE THREAD

**Issue by NomanJaved** [composer/composer#6980]
I am have installed Xampp on Windows 10.

I am facing the issue that the composer install not work properly in Laravel 5.5. How can I fix this issue. the error is mentioned in the title. If you guys require further detail I can provide it.

**Comment by curry684** [comment]
> If you guys require further detail I can provide it.

The default issue template was designed to give us enough detail before we have to ask for it. Right now you are just sharing an extremely generic error message which could be completely correct in a million situations.

Is there an `src` folder? Where is it? What is your composer.json? Which exact command are you running? In which directory?

**Comment by NomanJaved** [comment]
I am using Laravel 5.5 and I first try this command and get failed
`composer require --dev phpunit/phpunit ^6`
then I delete the Vendor folder and try again to install the 
`composer install`
but again I get the same error.  I don't know about the src folder. Where should it be by the way?

**Comment by curry684** [comment]
Again, please share the composer.json contents.

**Comment by NomanJaved** [comment]
`{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=7.0.0",
        "fideloper/proxy": "~3.3",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0"
    },
    "require-dev": {
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "~1.0",
        "phpunit/phpunit": "~6.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}
`

**Comment by curry684** [comment]
Why is that a copy of https://github.com/laravel/laravel/blob/master/composer.json? Are you developing on the core of Laravel?

**Comment by NomanJaved** [comment]
I just install the laravel project and start working on it. I am new bie on Laravel so I don't have much experience. What should I do now?

**Comment by curry684** [comment]
Use Homestead until you have tons more experience: https://laravel.com/docs/5.5/homestead

**Comment by itshaydendev** [comment]
@curry684 it's a copy of that because laravel/laravel is a template for laravel apps. the core is at laravel/framework.

I'm also running into this, what's a fix?

**Comment by itshaydendev** [comment]
(although I did just notice this thread is near on three years old by now so I'm sorry if it wasn't at the time and I just corrected you on it)
