### ISSUE TITLE
`composer validate` recommends invalid SPDX license

### ISSUE THREAD

**Issue by ntwb** [composer/composer#6981]
My `composer.json`:

```json
{
  "name": "wordpress/gutenberg",
  "type": "wordpress-plugin",
  "license": "GPL-2.0+",
  "description": "Prototyping since 1440. Development hub for the editor focus in core.",
  "homepage": "https://wordpress.github.io/gutenberg/",
  "keywords": [
    "gutenberg", "wordpress", "editor", "wp", "react", "javascript"
  ],
  "support": {
    "issues": "https://github.com/WordPress/gutenberg/issues"
  },
  "require-dev": {
    "dealerdirect/phpcodesniffer-composer-installer": "^0.4.3",
    "squizlabs/php_codesniffer": "^3.1",
    "wimg/php-compatibility": "^8",
    "wp-coding-standards/wpcs": "^0.14.0"
  },
  "require": {
    "composer/installers": "~1.0"
  }
}
```

Output of `composer diagnose`:

```
composer diagnose
Checking composer.json: WARNING
License "GPL-2.0+" is a deprecated SPDX license identifier, use "GPL-2.0+-only" or "GPL-2.0+-or-later" instead
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.6.2
PHP version: 7.1.13
PHP binary path: /usr/local/Cellar/php71/7.1.13_24/bin/php

```

When I run this command:

```
composer validate
```

I get the following output:

```
License "GPL-2.0+" is a deprecated SPDX license identifier, use "GPL-2.0+-only" or "GPL-2.0+-or-later" instead
```

And I expected this to happen:

I expected a valid SPDX License option to be returned.

What actually happens:

Two invalid SPDX License options are returned: `GPL-2.0+-only` and `GPL-2.0+-or-later`, both of these are invalid licenses, they should be `GPL-2.0-only` and `GPL-2.0-or-later`

After updating the license in `composer.json` to `GPL-2.0+-only` the following is reported back from `composer validate`: `License "GPL-2.0+-only" is not a valid SPDX license identifier, see https://spdx.org/licenses/ if you use an open license.`

----
Cause:

The issue is due to the `+` symbol being included in the `$license` string here:
https://github.com/composer/composer/blob/master/src/Composer/Package/Loader/ValidatingArrayLoader.php#L128

Resolution:

As none of the valid SPDX Licenses contain a `+` symbol dropping the `+` symbol before updating the `$license` string seems to be the solution from my quick glance

**Comment by Seldaek** [comment]
Oh yeah I forgot to account for the `+`, sorry about that, will get it fixed.

**Comment by ntwb** [comment]
Thanks :)
