### ISSUE TITLE
Cant install Instagram-API to Composer !!!

### ISSUE THREAD

**Issue by Xandr2410** [composer/composer#6986]
I get good instalated my composer on the Ubuntu 16, but when i start install Instagram API i got many troubles. One of them:
**user@ubuntu44:~$ composer show -p ext-xsl**

  [InvalidArgumentException]
  Package ext-xsl not found

show [--all] [-i|--installed] [-p|--platform] [-a|--available] [-s|--self] [-N|--name-only] [-P|--path] [-t|--tree] [-l|--latest] [-o|--outdated] [-m|--minor-only] [-D|--direct] [--strict] [-f|--format FORMAT] [--] [<package>] [<version>]

**user@ubuntu44:~$ composer install php5.6-xsl**
Invalid argument php5.6-xsl. Use "composer require php5.6-xsl" instead to add packages to your composer.json.
**user@ubuntu44:~$ composer require php5.6-xsl**

  [InvalidArgumentException]
  Could not find a matching version of package php5.6-xsl. Check the package spelling, your versi
  on constraint and that the package is available in a stability which matches your minimum-stabi
  lity (stable).

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

How can i fix this problem, help please!?

**Comment by xabbuh** [comment]
PHP extensions are not installed using Composer. How you have to do that highly depends on how you set up PHP. For example, if you did that using the package manager (I guess so because you seem to use Ubuntu), you can use that to install the extensions too like this:

```
apt-get install php-xml
```

For Ubuntu, there is also https://packages.ubuntu.com/ which you can use to search for packages (or use the CLI tools it ships).

**Comment by Xandr2410** [comment]
YEEEES My friend, from Moscow with love to You. Very very thanks!!!!!!!

**Comment by xabbuh** [comment]
Cheers. :) Can you close the issue then?

**Comment by Xandr2410** [comment]
Yes), how can i do it???
