### ISSUE TITLE
File included twice leads to fatal error

### ISSUE THREAD

**Issue by alekitto** [composer/composer#6987]
File may be included twice if present in `autoload.files` and is located under a `psr`-prefixed dir, and can lead to a fatal error.
I'm running composer 1.6.2 on PHP 7.2.0.

My `composer.json`:

```json
{
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        },
        "files": ["src/test.php"]
    }
}
```

The `src/test.php` file contains:

```php
<?php
function test() { }
```

When I run this script:

```php
<?php
require 'vendor/autoload.php';
class_exists('App\test');
```

I get the following output:

```
PHP Fatal error:  Cannot redeclare test() (previously declared in /Users/alekitto/projects/composer-bug/src/test.php:3) in src/test.php on line 3
PHP Stack trace:
PHP   1. {main}() test.php:0
PHP   2. class_exists() test.php:3
PHP   3. spl_autoload_call() test.php:3
PHP   4. Composer\Autoload\ClassLoader->loadClass() test.php:3
PHP   5. Composer\Autoload\includeFile() vendor/composer/ClassLoader.php:322
```

This does not happen if autoloader has been generated with authoritative classmap flag enabled.
I know that example code is probably missing a `function_exists` call, but there are some packages that have a similar issue (ex: `myclabs/deep-copy`).

**Comment by alekitto** [comment]
Actually it is a problem when using Symfony's PSR4 service loader as it recursively iterates over all the files present in a folder and its subfolders and checks if class exists and is instantiable.

**Comment by Seldaek** [comment]
It still sounds like a bad idea to me to mix PSR-4 files together with files-autoload based ones, but anyway maybe you should report that in the symfony repo rather. We are not going to use include_once as it slows things down.

**Comment by stof** [comment]
the Symfony loader has a way to exclude files from the loading though, so you can tell it not to load your file defining a function rather than a class.

**Comment by alekitto** [comment]
I used the symfony loader as an example, but this will break any possible psr-compliant class discovery service. I understand that `include_once` will slow things down, but what about raising a warning at the end of the update command about a possible name conflict?
If mix files and psr4 namespaces is a bad idea (and I agree with that), a warning would allow to report the problem to package maintainers quickly (again, as an example `myclabs/deep-copy` and `nelmio/alice` packages do have this problem)

**Comment by antonmedv** [comment]
@stof how to use it? Can you add some links to docs?

**Comment by ostretsov** [comment]
@antonmedv 
In your services.yml exclude directory:
```yaml
App\:
        resource: '../src/*'
        exclude: '../src/{functions,other/paths}'
```
