### ISSUE TITLE
can't install composer on centos 7

### ISSUE THREAD

**Issue by rivetweb** [composer/composer#6990]
https://getcomposer.org/download/
not work 

> Some settings on your machine make Composer unable to work properly.
> Make sure that you fix the issues listed below and run this script again:
> 
> The phar extension is missing.
> Install it or recompile php without --disable-phar
> 

> php -v
> PHP 7.0.27 (cli) (built: Jan  2 2018 12:38:03) ( NTS )
> Copyright (c) 1997-2017 The PHP Group
> Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
>     with Zend OPcache v7.0.27, Copyright (c) 1999-2017, by Zend Technologies
>

**Comment by xabbuh** [comment]
Searching for the error message reveals questions like https://stackoverflow.com/questions/35505264/installing-composer-on-centos which should provide some helpful insights.

**Comment by rivetweb** [comment]
https://stackoverflow.com/questions/35505264/installing-composer-on-centos/41050005#41050005
yes
this make it work.

anyway why you don't make one single php file, which don't need any phar or whatever extension ?

**Comment by Seldaek** [comment]
Because phar is quite useful and works for 99% of people..
