### ISSUE TITLE
Cant install instagram API to composer, help me please!!!

### ISSUE THREAD

**Issue by Xandr2410** [composer/composer#6991]
Hi all, i have next troubles when i try install instagram API to composer! 
P.S. I have ubuntu 16, v php - 7.1.12-3+ubuntu16.04.1+deb.sury.org+1 (cli)

**user@ubuntu44:~$ composer require mgp25/instagram-php**

Using version ^3.1 for mgp25/instagram-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mgp25/instagram-php ^3.1 -> satisfiable by mgp25/instagram-php[3.1].
    - mgp25/instagram-php 3.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.1/cli/php.ini
    - /etc/php/7.1/cli/conf.d/10-opcache.ini
    - /etc/php/7.1/cli/conf.d/10-pdo.ini
    - /etc/php/7.1/cli/conf.d/15-xml.ini
    - /etc/php/7.1/cli/conf.d/20-calendar.ini
    - /etc/php/7.1/cli/conf.d/20-ctype.ini
    - /etc/php/7.1/cli/conf.d/20-dom.ini
    - /etc/php/7.1/cli/conf.d/20-exif.ini
    - /etc/php/7.1/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.1/cli/conf.d/20-ftp.ini
    - /etc/php/7.1/cli/conf.d/20-gettext.ini
    - /etc/php/7.1/cli/conf.d/20-iconv.ini
    - /etc/php/7.1/cli/conf.d/20-json.ini
    - /etc/php/7.1/cli/conf.d/20-mbstring.ini
    - /etc/php/7.1/cli/conf.d/20-phar.ini
    - /etc/php/7.1/cli/conf.d/20-posix.ini
    - /etc/php/7.1/cli/conf.d/20-readline.ini
    - /etc/php/7.1/cli/conf.d/20-shmop.ini
    - /etc/php/7.1/cli/conf.d/20-simplexml.ini
    - /etc/php/7.1/cli/conf.d/20-sockets.ini
    - /etc/php/7.1/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.1/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.1/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.1/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.1/cli/conf.d/20-wddx.ini
    - /etc/php/7.1/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.1/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.1/cli/conf.d/20-xsl.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.

**Comment by xabbuh** [comment]
```
- mgp25/instagram-php 3.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
```

You need to install the cURL extension (similar to what you did to resolve #6986).

**Comment by Xandr2410** [comment]
I installed **apt-get install php-curl** and **apt-get install php-gd** 

And i got next:

user@ubuntu44:~$ composer require mgp25/instagram-php
Using version ^3.1 for mgp25/instagram-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 20 installs, 0 updates, 0 removals
  - Installing binsoul/net-mqtt (0.2.1): Downloading (100%)
  - Installing react/promise (v2.5.1): Downloading (100%)
  - Installing react/event-loop (v0.4.3): Downloading (100%)
  - Installing react/promise-timer (v1.2.1): Downloading (100%)
  - Installing evenement/evenement (v3.0.1): Downloading (100%)
  - Installing react/stream (v0.7.6): Downloading (100%)
  - Installing react/socket (v0.8.8): Downloading (100%)
  - Installing react/dns (v0.4.11): Downloading (100%)
  - Installing react/cache (v0.4.2): Downloading (100%)
  - Installing valga/fbns-react (0.1.8): Downloading (100%)
  - Installing psr/http-message (1.0.1): Downloading (100%)
  - Installing ringcentral/psr7 (1.2.1): Downloading (100%)
  - Installing clue/http-proxy-react (v1.2.0): Downloading (100%)
  - Installing clue/socks-react (v0.8.7): Downloading (100%)
  - Installing binsoul/net-mqtt-client-react (0.3.2): Downloading (100%)
  - Installing guzzlehttp/promises (v1.3.1): Downloading (100%)
  - Installing guzzlehttp/psr7 (1.4.2): Downloading (100%)
  - Installing guzzlehttp/guzzle (6.3.0): Downloading (100%)
  - Installing netresearch/jsonmapper (v1.4.0): Downloading (100%)
  - Installing mgp25/instagram-php (3.1): Downloading (100%)
react/event-loop suggests installing ext-libevent (>=0.1.0)
react/event-loop suggests installing ext-event (~1.0)
react/event-loop suggests installing ext-libev (*)
valga/fbns-react suggests installing ext-event (For more efficient event loop implementation.)
valga/fbns-react suggests installing ext-gmp (To be able to run this code on x86 PHP builds.)
mgp25/instagram-php suggests installing ext-event (Installing PHP's native Event extension enables faster Realtime class event handling.)
Writing lock file
Generating autoload files
user@ubuntu44:~$

This means that "composer require mgp25/instagram-php" was good installed???

**Comment by xabbuh** [comment]
Yes, this looks good.

**Comment by cyberman110** [comment]
Installing mgp25/instagram-php (v7.0.1): Downloading (failed)    Failed to download mgp25/instagram-php from dist: The "https://api.github.com/repos/mgp25/Instagram-API/zipball/53421f90b9ef7743f1c6221c4963f2b9f7a592e8" file could not be downloaded (HTTP/1.1 451 Unavailable for Legal Reasons)
    Now trying to download from source
  - Installing mgp25/instagram-php (v7.0.1): Cloning 53421f90b9


  [RuntimeException]
  Failed to clone https://github.com/mgp25/Instagram-API.git, git was not found, check that it is installed and in yo
  ur PATH env.

  'git' is not recognized as an internal or external command,
  operable program or batch file.


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

InstagramLive-PHP is now up-to-date!

**Comment by cyberman110** [comment]
please help me

Installing mgp25/instagram-php (v7.0.1): Downloading (failed) Failed to download mgp25/instagram-php from dist: The "https://api.github.com/repos/mgp25/Instagram-API/zipball/53421f90b9ef7743f1c6221c4963f2b9f7a592e8" file could not be downloaded (HTTP/1.1 451 Unavailable for Legal Reasons)
Now trying to download from source

    Installing mgp25/instagram-php (v7.0.1): Cloning 53421f90b9

[RuntimeException]
Failed to clone https://github.com/mgp25/Instagram-API.git, git was not found, check that it is installed and in yo
ur PATH env.

'git' is not recognized as an internal or external command,
operable program or batch file.

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] []...

InstagramLive-PHP is now up-to-date!

**Comment by cyberman110** [comment]
Loading Updater...
PHP Warning:  require_once(F:\program\IP TV\Instagram Live\jadid\2\InstagramLive-PHP-master-master\InstagramLive-PHP-master-master/utils.php): failed to open stream: No such file or directory in F:\program\IP TV\Instagram Live\jadid\2\InstagramLive-PHP-master-master\InstagramLive-PHP-master-master\goLive.php on line 186
PHP Fatal error:  require_once(): Failed opening required 'F:\program\IP TV\Instagram Live\jadid\2\InstagramLive-PHP-master-master\InstagramLive-PHP-master-master/utils.php' (include_path='.;C:\php\pear') in F:\program\IP TV\Instagram Live\jadid\2\InstagramLive-PHP-master-master\InstagramLive-PHP-master-master\goLive.php on line 186
Fetching Latest Stable Release Data
PHP Warning:  file_get_contents(https://raw.githubusercontent.com/JRoy/InstagramLive-PHP/update/stable.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in F:\program\IP TV\Instagram Live\jadid\2\InstagramLive-PHP-master-master\InstagramLive-PHP-master-master\update.php on line 74
PHP Notice:  Trying to access array offset on value of type null in F:\program\IP TV\Instagram Live\jadid\2\InstagramLive-PHP-master-master\InstagramLive-PHP-master-master\update.php on line 75
PHP Notice:  Trying to access array offset on value of type null in F:\program\IP TV\Instagram Live\jadid\2\InstagramLive-PHP-master-master\InstagramLive-PHP-master-master\update.php on line 75
Fetched Version:  (Version Code )
Validating directories...
PHP Notice:  Trying to access array offset on value of type null in F:\program\IP TV\Instagram Live\jadid\2\InstagramLive-PHP-master-master\InstagramLive-PHP-master-master\update.php on line 78
PHP Warning:  Invalid argument supplied for foreach() in F:\program\IP TV\Instagram Live\jadid\2\InstagramLive-PHP-master-master\InstagramLive-PHP-master-master\update.php on line 78
Comparing Files...
PHP Notice:  Trying to access array offset on value of type null in F:\program\IP TV\Instagram Live\jadid\2\InstagramLive-PHP-master-master\InstagramLive-PHP-master-master\update.php on line 88
PHP Warning:  Invalid argument supplied for foreach() in F:\program\IP TV\Instagram Live\jadid\2\InstagramLive-PHP-master-master\InstagramLive-PHP-master-master\update.php on line 88
Checking for config updates...
PHP Notice:  Trying to access array offset on value of type null in F:\program\IP TV\Instagram Live\jadid\2\InstagramLive-PHP-master-master\InstagramLive-PHP-master-master\update.php on line 105
PHP Notice:  Trying to access array offset on value of type null in F:\program\IP TV\Instagram Live\jadid\2\InstagramLive-PHP-master-master\InstagramLive-PHP-master-master\update.php on line 105
InstagramLive-PHP is now up-to-date!

**Comment by Lazza** [comment]
@cyberman110 this has nothing to do with Composer. As you can clearly see from the data, the repository has been taken down from GitHub:

```
{
  "message": "Repository access blocked",
  "block": {
    "reason": "dmca",
    "created_at": "2020-01-29T17:29:55Z",
    "html_url": "https://github.com/github/dmca/blob/master/2020/01/2020-01-22-facebook.md"
  }
}
```
