### ISSUE TITLE
"tar" type repository does not allow extraction of empty folder in tar.gz file

### ISSUE THREAD

**Issue by verbruggenalex** [composer/composer#6992]
Because the tar.gz file contains an un-named folder "." the tar type extractor is not able to extract the contents of the folder. If the folder is named there is no problem.

<details><summary>File: composer.json</summary>

```json
    "require": {
        "ec-europa/platform_dev": "~2.4.0"
    },
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "ec-europa/platform_dev",
                "version": "2.4.63",
                "type": "drupal-core",
                "dist": {
                    "url": "https://github.com/ec-europa/platform-dev/releases/download/2.4.63/platform-dev-2.4.63.tar.gz",
                    "type": "tar"
                }
            }
        }
    ]
}
```

</details>

<details><p><summary>Run: composer install</summary>

```
  [PharException]
  Extraction from phar "/home/verbral/platform-composer/build/28911af645fcdc4a61e64f6ef3e444ab.gz" failed: Cannot extract ".", internal error
```
</details></p>

I know this is an edge case. But would it be possible to allow for un-named folders to be extracted? I'm not really in the mood to re-upload 500 packages to our repository.

Possible solution provided on PHP documentation page:
http://php.net/manual/en/phardata.extractto.php

**Comment by stof** [comment]
why is there a folder named `.` in the tar ?

**Comment by verbruggenalex** [comment]
Legacy, techical debt, fucked up? Honestly I have no clue. Our releases are packaged by Jenkins.
I'm just wondering if you would mind providing support for this "edge" case. I'm willing to write a patch to solve the situation for this. But do you think such a thing could be accepted? Or we just say, don't be stupid, fix the packages themselves?

**Comment by alcohol** [comment]
Having a directory named `.` kind of breaks the whole symbolic meaning of `.` and `..`. I cannot even begin to understand how you wound up with such a directory in the first place.

**Comment by verbruggenalex** [comment]
You are right. I will ask my colleagues to repackage 😂

**Comment by Seldaek** [comment]
Yup I don't really see anything to be fixed here.
