### ISSUE TITLE
Potential security issue with Composer

### ISSUE THREAD

**Issue by Justproof** [composer/composer#6997]
Is it normal to have around 100 sha256 keys listed within the following .composer/cache/... files when searching for "bitcoin'?  I've installed everything from a minimal install of Ubuntu and after using Composer to install Laravel, these "sha256" keys begin to show up on my machine. 

Bitcoin is a blackbox to me and I'm a noob to composer, and I'd appreciate the help if anyone is seeing this, or this is supposed to be there.

When I run this command:

```
`find . -type f -exec grep -l 'bitcoin' {} \;`
```

I get the following output:

```
-------Files Containing bitcoin sha256-------
.composer/cache/repo/https---packagist.org/p-provider-2013.json
./.composer/cache/repo/https---packagist.org/p-provider-2014.json
./.composer/cache/repo/https---packagist.org/p-provider-2015.json
./.composer/cache/repo/https---packagist.org/p-provider-2016.json
./.composer/cache/repo/https---packagist.org/p-provider-2017-04.json
./.composer/cache/repo/https---packagist.org/p-provider-2017-07.json
./.composer/cache/repo/https---packagist.org/p-provider-2017-10.json
./.composer/cache/repo/https---packagist.org/p-provider-2017.json
./.composer/cache/repo/https---packagist.org/p-provider-latest.json
```
**One Example:(Key and User name removed)**
{"sha256":"KEY HERE"},"USERNAME\/bitcoin-transaction-event-loop":

**Comment by dzuelke** [comment]
Those are just published packages and their hashes.

**Comment by Justproof** [comment]
Thank you for clearing this up.
