### ISSUE TITLE
"remove" output and exit status do not tell about failures/non-removages

### ISSUE THREAD

**Issue by cweiske** [composer/composer#6998]
My `composer.json`:

```json
{
    "require": {
        "laravel/framework": "^5.5"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.6.2
PHP version: 7.1.12-3+ubuntu16.04.1+deb.sury.org+1
PHP binary path: /usr/bin/php7.1
```

When I run this command:

```
composer remove swiftmailer/swiftmailer; echo $?
```

I get the following output:

```
swiftmailer/swiftmailer is not required in your composer.json and has not been removed
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

And I expected this to happen:

1. A message telling me that swiftmailer was not removed (maybe with a reason: 'hard requirement by laravel/framework")
2. Exit code of non-0, because 0 means success.

I want to *remove* a package, and composer did not do that - and failed to tell me that. The package I wanted to remove is still installed.

I do know that "composer remove" currently only removes the entry from `composer.json` and then runs "update", but thats implementation detail. The user's intent when using "remove" is that a package shall be removed, and composer doesn't behave in a way the user would expect.

**Comment by alcohol** [comment]
Or the user expectations are wrong.

`remove` is for root-only requirements. You have no such root-only requirement. You cannot remove this package without removing the root package that depends on it.

**Comment by cweiske** [comment]
I don't think that a proper exit status is a wrong user expectation.

**Comment by alcohol** [comment]
Not being able to remove a package that is not there is not a failure though. It is a success in essence (the package that you wanted to remove is not there).

I guess that not being able to assert if a package is installed hinders whatever you are trying to achieve, probably. But since you are only proposing a solution and not presenting us with your actual problem or challenge, I can only guess.

**Comment by cweiske** [comment]
Standard unix tools give you an error in that case:

```
$ rm thisfiledoesnotexist; echo $?
rm: cannot remove 'thisfiledoesnotexist': No such file or directory
1
```

Also, if you actually try to remove a root package and have a typo, you're still getting a success status currently.

**Comment by alcohol** [comment]
> Also, if you actually try to remove a root package and have a typo, you're still getting a success status currently.

But then the question becomes, did the command fail, or did user input fail?

Anyway, if you really want an exit code, that's fine by me. Please submit a PR :-)
