### ISSUE TITLE
Wrong return value from Composer/IO/ConsoleIO::select() method

### ISSUE THREAD

**Issue by victorynox** [composer/composer#7000]
My `composer.json`:

```json
"require": {
        "rollun-com/rollun-installer "^4.0",
}
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.6.2
PHP version: 7.1.12-2+0~20171207160618.12+stretch~1.gbp5c91f3
PHP binary path: /usr/bin/php7.1
```

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: WARNING
You are not running the latest stable version, run `composer self-update` to update (1.5.2 => 1.6.2)
```

When I run this method:

[Composer\IO\ConsoleIO::select()](https://github.com/composer/composer/blob/master/src/Composer/IO/ConsoleIO.php#L283) 
```
$data = $console->select(
"Select value",
[
            "Choice value 0",
            "Choice value 1",
            "Choice value 2",
],
"0,2",
false,
'Value "%s" is invalid',
true
);
```

I get the following output in data:
Array with **values** of the `"$choices"` array
```
[
 "Choice value0",
 "Choice value2"
]
```

And I expected this to happen:
Array with **keys** of the `"$choices"` array
```
[
0,
2
]
```

Wen I'm using composer version 1.5.2 and earlier, method [Composer\IO\ConsoleIO::select()](https://github.com/composer/composer/blob/master/src/Composer/IO/ConsoleIO.php#L283)
return the array with **keys** of the `"$choices"` array ([as in the documentation ](https://getcomposer.org/apidoc/1.6.1/Composer/IO/ConsoleIO.html#method_select)), but in composer 1.6.2 i'm getting the array with **values** of the `"$choices"` array.

**Comment by alcohol** [comment]
The `select` method simply uses http://symfony.com/doc/current/components/console/helpers/questionhelper.html

I am not sure why it might have returned the keys in the past. It should always return the value.

That API documentation seems generated based on the `IOInterface` definition, which is probably wrong: https://github.com/composer/composer/blob/master/src/Composer/IO/IOInterface.php

@Seldaek input?

**Comment by Seldaek** [comment]
Yeah it sounds like just a documentation error but if it indeed changed between 1.5.2 and 1.6.2 then we should double check what happened in symfony, maybe something changed.

**Comment by alcohol** [comment]
We only upgraded `symfony/console` from `2.8.26` to `2.8.32`.

But we did change the way we call it (to some extend).

https://github.com/composer/composer/blob/c639623fa2178b404ed4bab80f0d1263853fa4ae/src/Composer/IO/ConsoleIO.php#L279-L289

vs.

https://github.com/composer/composer/blob/db191abd24b0be110c98ba2271ca992e1c70962f/src/Composer/IO/ConsoleIO.php#L280-L293

**Comment by alcohol** [comment]
Ah, it's because we were using the deprecated dialog helper.

https://symfony.com/doc/2.8/components/console/helpers/dialoghelper.html

And when I updated a lot of the console stuff, I implemented the question helper instead (which behaves slightly different).
