### ISSUE TITLE
The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: HTTP request failed!

### ISSUE THREAD

**Issue by chrisEspira** [composer/composer#7001]
HI,
Somebody can help me solve this problem
i cannot install composer
 when i try to install composer 
I get this error
The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: HTTP request failed!

i need help please..........thx

**Comment by tomzx** [comment]
Looks like a duplicate of #6515.
