### ISSUE TITLE
Option to always remove VCS on `create-project`?

### ISSUE THREAD

**Issue by apfelbox** [composer/composer#7002]
Hi 👋 ,

I am currently in the process of researching a possible fix for https://github.com/symfony/flex/issues/285.

The desired behaviour is for the symfony skeleton installation to just always remove the VCS directory and don't ask in the CLI for it.

Currently this is implemented that Symfony Flex just completely disables interactivity in IO, so that the call to `->askConfirmation()` [here](https://github.com/composer/composer/blob/994bac0c153348c09d42cd77225c465c1b81e8e9/src/Composer/Command/CreateProjectCommand.php#L201) just [returns the default value](https://github.com/symfony/console/blob/bf56f79b8604e4dd32c236048606c507e9dbbcd3/Helper/QuestionHelper.php#L55) (`true`).

Unfortunately that also kills all subsequent interactive calls.

As I read the code:
https://github.com/composer/composer/blob/master/src/Composer/Command/CreateProjectCommand.php#L176-L202

there currently is no way to just disable interactivity for the one call to `askConfirmation()`.
It's always either all scripts + the "delete VCS dir" one, or nothing.

So I would like to ask whether it would be possible to:

* dispatch another event between `Installer` and `->askConfirmation()` so that Flex can hook specifically in to disable interactivity in this event and re-enable again in the event `POST_CREATE_PROJECT_CMD ` (something like `POST_ROOT_PACKAGE_DEPENDENCIES_INSTALL`).
* provide a way to just always remove the VCS directory in a plugin (env var, some global setting or a callback somewhere).

What do you think?

**Comment by Seldaek** [comment]
You can now pass `--remove-vcs` to it.

**Comment by apfelbox** [comment]
Is it possible to set this flag programmatically as we want to set it in [flex](https://github.com/symfony/flex), which is a composer plugin?

**Comment by Seldaek** [comment]
I don't know how flex calls the create-project command, but it's just an argument to it so I would assume yes. I probably won't release 1.6.3 for another few days tho so if you need another fix please let me know soon :)

**Comment by apfelbox** [comment]
As far as I read the code, flex doesn't actually do anything here, as it just lets composer do it's job (aka invoke the composer command).

Until now the plugin only disabled interactivity when it was loaded (which is before any command is run) and could re-enable it after the command has run.

Possibly the easiest way would be to just use an env variable as a default for the parameter, that flex could set when the plugin is loaded.
(or is there another way?)

**Comment by Seldaek** [comment]
Ah I see, then yes the param won't be enough, unless flex injects it in $_SERVER['argv'] or something before it's read, not sure if that's feasible. Anyway would rather have a way to let parameters be modified than add an env var just for that one param though, as then we'll need another one for every parameter.. Reopening this for now.

**Comment by Seldaek** [comment]
Alright added a new event for this that lets you do something like:

```
$composer->getEventDispatcher()->addListener('pre-command-run', function ($e) {
    if ($e->getCommand() == 'create-project') {
        $e->getInput()->setOption('remove-vcs', true);
    }
});
```

/cc @nicolas-grekas might come in handy as I see you're doing a lot of that already but I think it's maybe happening too early to work fine as the command's input definition is not merged yet when we activate plugins.

**Comment by apfelbox** [comment]
Hello again @Seldaek ,

sorry to be bothering you again.
The solution you implemented does work with *preinstalled* plugins, but flex isn't preinstalled:

```
c create-project symfony/skeleton # <- installs flex + other dependencies
# flex does its magic
```

Here you can see it a bit more clearly:

![2018-01-25 at 12 21](https://user-images.githubusercontent.com/1032411/35385950-6f25d2ba-01ca-11e8-80b3-88e8a4b536c9.png)

1. the new event is triggered
2. the skeleton is installed, and flex is a dependency of the skeleton
3. flex was installed (as first dependency of the skeleton) and the code is executed

But the event is already thrown before flex was even installed. To solve the issue at hand we would need a way to modify the currently running `create-project` command.

(the newly created `pre-command-run` event can be kept, as is might come in handy in other use cases)

**Comment by Seldaek** [comment]
Ah crap, yes you're absolutely right, I didn't consider that flex gets
installed after the command starts.

Not sure yet how to best address that but it'll have to be 1.7 so we have
some time to think It through. I don't see an elegant way to do this though
right now.

**Comment by apfelbox** [comment]
All right. Could you re-open this issue then, please – that it doesn't get lost? 😉

**Comment by Seldaek** [comment]
Fixed in https://github.com/symfony/flex/pull/377 - just needs a 1.7.0 release
