### ISSUE TITLE
could this apporoach will be more useful to optimize with apcu 

### ISSUE THREAD

**Issue by ncomer** [composer/composer#7003]
since  i run the command  "dump-autoload -o --apcu" to improve the boot speed of laravel,
i got a big autoload_static file which have 4k lines code.
Then i found   this code block within auloload_real.php:

```
if ($useStaticLoader) {
      require_once __DIR__ . '/autoload_static.php';  
 call_user_func(\Composer\Autoload\ComposerStaticInitb6642ee553ca64f76f58aeb2231d582d::getInitializer($loader));
}
```
, when run a xhprof, load::composer/autoload_static.php rank No 1(about 11,702 µs in my case).

What i think is: since apcu can be used for cache,and an obj type can directly  be stored in,
then i can modify above code like this:

1. autoload_static.php@getInitializer
add `$loader->f = ComposerStaticInitb6642ee553ca64f76f58aeb2231d582d::$files;`
2. auloload_real.php 
```
$loaderApc = apcu_fetch('cloader', $hit);
            if (!$hit){
                require_once __DIR__ . '/autoload_static.php';
                call_user_func(\Composer\Autoload\ComposerStaticInitb6642ee553ca64f76f58aeb2231d582d::getInitializer($loader));
                apcu_store('cloader', clone $loader);
            }else{
                $loader = $loaderApc;
            }
another place:
if ($useStaticLoader) {
            $includeFiles = $loader->f;
        }
```

I do not have a overall composer source code's reading, but this seems  work,
Will this ok and be achieved further or am i wrong with something..  1st post,sorry for possiable mis

**Comment by ncomer** [comment]
enn,maybe opcache can solve include/require big file

**Comment by Seldaek** [comment]
As per https://getcomposer.org/doc/articles/autoloader-optimization.md you should not add `-o` if you use `--apcu` IMO.

**Comment by ncomer** [comment]
May be that's a Compromise,thanks anyway
