### ISSUE TITLE
scripts-descriptions are not displayed in run-script --list

### ISSUE THREAD

**Issue by mhujer** [composer/composer#7009]
My `composer.json`:

```json
...
  "scripts": {
    "test": "phpunit",
    "phpcs": "phpcs --standard=PSR2 src"
  },
  "scripts-descriptions": {
    "phpcs": "Checks that the application code conforms to coding standard",
    "test": "Launches the preconfigured PHPUnit"
  }
....
```

Output of `composer diagnose`:

```
Composer version: 1.6.2
PHP version: 7.1.12
```

When I run this command:

```
composer run-script --list
```

I get the following output:

```
scripts:
  test
  phpcs
```

And I expected this to happen:

Scripts description should be displayed the same way they are displayed when running `composer` without parameters.

**Comment by mhujer** [comment]
I had a look on how it can be fixed.

1. The easy and dirty way would be to copy most of this
https://github.com/composer/composer/blob/994bac0c153348c09d42cd77225c465c1b81e8e9/src/Composer/Console/Application.php#L222-L243 
into `RunScriptCommand::listScripts()`.

2. Better way would be to create some class to wrap scripts-descriptions fetching

3. Or maybe add a new property to `RootPackageInterface`?

What do you think? I'd be happy to prepare a PR.

**Comment by alcohol** [comment]
In my opinion, the console command classes should be as "dumb" as possible. So I would probably lean towards option 3. @Seldaek how do you feel about that?

**Comment by Seldaek** [comment]
Found a 4th way.. and by the time I was done checking if it could be done it was kinda implemented so I just did it.

**Comment by mhujer** [comment]
Cool 👍
