### ISSUE TITLE
while installing package through composer it require too much time to install and update too, i am using in laravel project 

### ISSUE THREAD

**Issue by rabin999** [composer/composer#7012]
My `composer.json`:

```json
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=7.0.0",
        "fideloper/proxy": "~3.3",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0"
    },
    "require-dev": {
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "~1.0",
        "phpunit/phpunit": "~6.0",
        "predis/predis": "^1.1"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}

```

When I run command require or update on package, at least it took 15-18 min for small changes :(

**Comment by narwy** [comment]
It could be down to your connection to the server speed. If you have a lot of packages to download that could also be a factor.

**Comment by rabin999** [comment]
I was downloading https://packagist.org/packages/predis/predis package, n  for literally each package installation took 15 to 18 min.

**Comment by tomzx** [comment]
Can you provide the output of `php composer.phar install --profile -vvv`?

To install your `composer.json` on my computer, it takes approximately 1 minute. If it takes you a lot longer, network issues or slow disks might be the cause.

**Comment by rabin999** [comment]
$ php composer.phar install --profile -vvv
Reading C:/Users/DevRabin/AppData/Roaming/Composer/composer.json
Loading config file C:/Users/DevRabin/AppData/Roaming/Composer/composer.json
Checked CA file C:\Users\DevRabin\AppData\Local\Temp\composer-cacert-e62a07e61e5
870effa81b430e1900778943c228bd7da1259dd6a955ee2262b47.pem: valid
Executing command (C:/Users/DevRabin/AppData/Roaming/Composer): git branch --no-
color --no-abbrev -v
Executing command (C:/Users/DevRabin/AppData/Roaming/Composer): git describe --e
xact-match --tags
Executing command (C:/Users/DevRabin/AppData/Roaming/Composer): git log --pretty
="%H" -n1 HEAD
Executing command (C:/Users/DevRabin/AppData/Roaming/Composer): hg branch
Executing command (C:/Users/DevRabin/AppData/Roaming/Composer): fossil branch li
st
Executing command (C:/Users/DevRabin/AppData/Roaming/Composer): fossil tag list
Executing command (C:/Users/DevRabin/AppData/Roaming/Composer): svn info --xml
Reading C:/Users/DevRabin/AppData/Roaming/Composer/composer.json
Loading config file C:/Users/DevRabin/AppData/Roaming/Composer/composer.json
Reading C:/Users/DevRabin/AppData/Roaming/Composer/vendor/composer/installed.jso
n
Reading C:/Users/DevRabin/AppData/Roaming/Composer/vendor/composer/installed.jso
n
Running 1.4.1 (2017-03-10 09:29:45) with PHP 7.0.19 on Windows NT / 10.0
[7.5MB/0.00s] Composer could not find a composer.json file in C:\ProgramData\Com
poserSetup\bin
To initialize a project, please create a composer.json file as described in the
https://getcomposer.org/ "Getting Started" section

**Comment by melato** [comment]
I used to get such long times (15 minutes) on a Linux LXD container and ZFS storage.
See https://discuss.linuxcontainers.org/t/php-composer-is-excessively-slow-in-zfs-container/3670/2

**Comment by narwy** [comment]
> I used to get such long times (15 minutes) on a Linux LXD container and ZFS storage.
> See https://discuss.linuxcontainers.org/t/php-composer-is-excessively-slow-in-zfs-container/3670/2

How many packages are you trying to download?

**Comment by melato** [comment]
I don't know exactly how many packages, but after applying the workaround the time went down about 5X to 2.5 minutes.  Also, doing "composer require" on a single additional package (that had a single library dependency) took ~ 23 minutes once.
The workaround is to disable transparent hugepage support on the host.  I don't know what transparent hugepage support is.  It seems to have something to do with the way php memory maps files.  The issue that I referenced has instructions about how to reproduce.  In that issue I also provide another reference that shows extremely slow php mmap performance:  https://stackoverflow.com/questions/45013646/php-fpm7-1-mmap-munmap-very-slow-performance-on-virtualized-systems-hugepage
