### ISSUE TITLE
Composer TestCase

### ISSUE THREAD

**Issue by nadar** [composer/composer#7017]
We have built a composer based open source CMS and Admin UI (https://luya.io), therefore we have made a composer plugin to track the packages from our "type". In order to test (phpunit) the composer plugin, we could not found any useful documentation, so where looking how you did => https://github.com/composer/composer/blob/master/tests/Composer/TestCase.php. 

So we have used the TestCase class to test our own plugin, sadly due to this comment `https://github.com/composer/composer/commit/b656973a86c9f4793f45bd5fa68410878bb5acc3#comments` the test files are no longer shipped into the vendor folder.

Composer is the future, so more plugins will follow, we need tools to test those plugins.

So my question is:

1. Why not adding the test files for other developers to? (re add the `tests` folder)
2. Or provide a basic TestCase for developers which makes it easy to test the plugin, like a composer testsuite?

**Comment by Seldaek** [comment]
What are you using exactly from the TestCase class that you feel is so useful? The getPackage is about the only thing I can imagine and that's like 3 lines of code so I am not so sure how helpful it is.

**Comment by nadar** [comment]
Well okay, i am going to close this issue.

In my case it was hard to find out how to test plugins, i still believe some better guidance or a basic test case everyone can quick setup and start running very basics tests would be a good feature, regarding the time even more composer plugins will be developed.

Thanks anyhow fo the good work!
