### ISSUE TITLE
--no-dev installs package replaced by dev requirement, not original requirement

### ISSUE THREAD

**Issue by rickselby** [composer/composer#7018]
My `composer.json`:

_This is a simplified version of the issue I'm seeing. In the real case, my `require-dev` contains `"graham-campbell/testbench": "^4.0"`; its dependencies eventually require `laravel/framework`, which causes the issue. Both setups give the same results._

```json
{
    "require": {
        "illuminate/contracts": "~5.5.0"
    },
    "require-dev": {
        "laravel/framework": "~5.5.0"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.6.2
PHP version: 7.0.22-0ubuntu0.16.04.1
PHP binary path: /usr/bin/php7.0
```

When I run this command:

```
composer install --no-dev
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies
Package operations: 30 installs, 0 updates, 0 removals
...<snip>...
  - Installing laravel/framework (v5.5.31): Downloading (100%)         
Writing lock file
Generating autoload files
```

And I expected this to happen:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
...<snip>...
  - Installing illuminate/contracts (v5.5.28): Downloading (100%)         
Writing lock file
Generating autoload files
```

`laravel/framework`'s composer.json contains the following:
```
"replace": {
   ...
   "illuminate/contracts": "self.version",
   ...
}
```

I've read through the numerous issues relating to updating requiring require-dev to be solvable (#5224 etc), and that require-dev is parsed even when --no-dev is specified, so I'm not sure if anything can be done here, but thought it best to raise this case.

**Comment by Seldaek** [comment]
As far as I understand laravel/framework replaces illuminate/contracts so when we resolve dependencies (including dev ones) laravel/framework is selected and illuminate/contracts is not present at all. When you install without dev dependencies, the only packages available for installation are those that are in the lock file, so that means laravel/framework is the only one to be picked. Indeed not something we can fix.
