### ISSUE TITLE
Composer file could not be downloaded (404 not found)

### ISSUE THREAD

**Issue by bepossitive** [composer/composer#7021]
I tyring to install Laravel

Output of `composer diagnose`:

d:\web>composer diag
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking HTTP proxy: OK
Checking HTTP proxy support for request_fulluri: OK
Checking HTTPS proxy support for request_fulluri: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  ****
723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  ****
8C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.6.2
PHP version: 7.2.1
PHP binary path: D:\php-7.2.1-nts-Win32-VC15-x86\php.exe

When I run this command:

composer global require "laravel/installer"

I get the following output:

 [Composer\Downloader\TransportException]
 The "https://packagist.org/p/symfony/console%2433f24f3dbe55cff57fe06a5fa93b
 a0bbe3ae3b259e2c5b7d051da0238769fa0f.json" file could not be downloaded (HT
 TP/1.1 404 Not Found)

**Comment by MirazMac** [comment]
I'm having the same problem. It hangs for a long time, then displays this error. I tried uninstalling and re-installing Composer, but the result is same.

**Comment by karim10** [comment]
Same problem for me

**Comment by MirazMac** [comment]
No solution yet? Still facing the same problem :(

**Comment by siduke000** [comment]
Same problem for me

**Comment by johnabelardom** [comment]
Can you try 

composer clear-cache

then

composer -vvv

after that try running the install command for laravel, it worked for me though

**Comment by q10242** [comment]
having the same problem.

**Comment by iamsampath7** [comment]
Also my problem

**Comment by MirazMac** [comment]
This issue was never fixed.

**Comment by alcohol** [comment]
For proxy issues, try:
https://gist.github.com/naderman/377e40c1c76e0fe8b905c1a333c4112a

Details:
https://twitter.com/naderman/status/1029839134070853637

**Comment by ravigohil999** [comment]
Anybody found the solution?

**Comment by MirazMac** [comment]
I didn't find any solution. But I found when the problem occurs. It seems the problem only occurs when I'm using my broadband connection IP. If I use mobile data via hotspot everything seems to work fine. But for some reason won't work on my broadbrand IP.

**Comment by ravigohil999** [comment]
That is weird. I will check that too


Sent from Yahoo Mail for iPhone


On Tuesday, January 29, 2019, 12:57 PM, Miraz Mac <notifications@github.com> wrote:


I didn't find any solution. But I found when the problem occurs. It seems the problem only occurs when I'm using my broadband connection IP. If I use mobile data via hotspot everything seems to work fine. But for some reason won't work on my broadbrand IP.

**Comment by RunyonYe** [comment]
First I try the command "composer clear-cache". It still not working.
Then I try the command "composer dump-autoload". 
It works for me.

**Comment by ViperMY** [comment]
> Can you try
> 
> composer clear-cache
> 
> then
> 
> composer -vvv
> 
> after that try running the install command for laravel, it worked for me though

It works for me.

**Comment by linus-zhou** [comment]
> Can you try
> 
> composer clear-cache
> 
> then
> 
> composer -vvv
> 
> after that try running the install command for laravel, it worked for me though

it works for me too

**Comment by OZZlE** [comment]
we had a ton of vcs repos pointing to different private github repos, I simply removed most of them added a packagist url to those, tried install again, then it asked me for github ssh access token, I entered it, it failed installing some modules, I reverted composer.json back to the original, removed everything in vendor folder and ran install again and then everything worked fine :P

**Comment by felipeescorel** [comment]
> Can you try
> 
> composer clear-cache
> 
> then
> 
> composer -vvv
> 
> after that try running the install command for laravel, it worked for me though

This worked for me aswell

**Comment by Marks-1** [comment]
composer clear-cache rectifies the error

**Comment by OZZlE** [comment]
It didn't for me, no reason to keep spamming the same answer as siduke000 @Marks-1 @felipeescorel it's already written here, write something useful if you write something

**Comment by Sciecha** [comment]
Probably sometimes you have to add repositories to composer, it solved my problem.

**Comment by faniabdo99** [comment]
the composer clear-cache Solution Worked For Me , Thanks to @johnabelardom

**Comment by UmarSaeed456** [comment]
> Can you try
> 
> composer clear-cache
> 
> then
> 
> composer -vvv
> 
> after that try running the install command for laravel, it worked for me though

This work for me also

**Comment by SV-ZeroOne** [comment]
Hello, I recently encountered the same following error when trying to composer require seostats/seostats package.
Was first getting this error
[Composer\Downloader\TransportException] The "https://packagist.org/p/provider-2019-04%244380046a2dfa549bfcf196bfc2c1a5cca9d58c63fb9b8e836367bfe2c01f062b.json" file could not be downloaded (HTTP/1.1 404 Not Found)

Then tried a composer cache-clear
Now getting this error
[Composer\Downloader\TransportException] Content-Length mismatch, received 551423 bytes out of the expected 2019004

Can anybody explain why this is happening?

Here is my composer diagnose results
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Checking composer version: OK
Composer version: 1.8.6
PHP version: 7.2.20
PHP binary path: /opt/cpanel/ea-php72/root/usr/bin/php
[root@dev-steve-cpanel elitehost_domain_info]#

**Comment by SV-ZeroOne** [comment]
Hello, I recently encountered the same following error when trying to composer require seostats/seostats package.
Was first getting this error
[Composer\Downloader\TransportException] The "https://packagist.org/p/provider-2019-04%244380046a2dfa549bfcf196bfc2c1a5cca9d58c63fb9b8e836367bfe2c01f062b.json" file could not be downloaded (HTTP/1.1 404 Not Found)

Then tried a composer cache-clear
Now getting this error
[Composer\Downloader\TransportException] Content-Length mismatch, received 551423 bytes out of the expected 2019004

Can anybody explain why this is happening?

Here is my composer diagnose results
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Checking composer version: OK
Composer version: 1.8.6
PHP version: 7.2.20
PHP binary path: /opt/cpanel/ea-php72/root/usr/bin/php
[root@dev-steve-cpanel elitehost_domain_info]#

**Comment by SV-ZeroOne** [comment]
> Hello, I recently encountered the same following error when trying to composer require seostats/seostats package.
> Was first getting this error
> `[Composer\Downloader\TransportException] The "https://packagist.org/p/provider-2019-04%244380046a2dfa549bfcf196bfc2c1a5cca9d58c63fb9b8e836367bfe2c01f062b.json" file could not be downloaded (HTTP/1.1 404 Not Found)`
> 
> Then tried a composer clear-cache
> Now getting this error
> `[Composer\Downloader\TransportException] Content-Length mismatch, received 551423 bytes out of the expected 2019004`
> 
> Can anybody explain why this is happening?
> 
> Here is my composer diagnose results
> Checking platform settings: OK
> Checking git settings: OK
> Checking http connectivity to packagist: OK
> Checking https connectivity to packagist: OK
> Checking github.com rate limit: OK
> Checking disk free space: OK
> Checking pubkeys:
> Checking composer version: OK
> Composer version: 1.8.6
> PHP version: 7.2.20
> PHP binary path: /opt/cpanel/ea-php72/root/usr/bin/php

Changed my composer default repos to this and it solved the content-length mismatch errors and I was able to successfully install my package.
composer config -g repo.packagist composer https://packagist.org
composer config -g github-protocols https ssh

**Comment by anovix** [comment]
@SV-ZeroOne This might be the problem: https://twitter.com/packagist/status/1156148973738110978

**Comment by Indexo-Git** [comment]
> Can you try
> 
> composer clear-cache
> 
> then
> 
> composer -vvv
> 
> after that try running the install command for laravel, it worked for me though

Work for me also

**Comment by NamaSeydou1** [comment]
composer clear-cache

composer -vvv

**Comment by viraljetani** [comment]
if "composer clear-cache" doesnt work, try using "composer self-update" before your composer update command and it should fix any composer related issues itself and should fix your problem.

**Comment by kaluzki** [comment]
`composer clear-cache` didn't work for me

it seems that there are some network issues from time to time on the main server `https://packagist.org` 

i tried one of the [mirrors](https://packagist.org/mirrors) as a temporary workaround:

`composer config -g repo.packagist composer https?://packagist.jp`

it was pretty slow, but worked finally

**Comment by BorisGautier** [comment]
composer config -g -- disable-tls false

**Comment by LMDeb** [comment]
> `composer clear-cache` no funcionó para mí
> 
> parece que hay algunos problemas de red de vez en cuando en el servidor principal `https://packagist.org`
> 
> probé uno de los [espejos](https://packagist.org/mirrors) como una solución temporal:
> 
> `composer config -g repo.packagist composer https?://packagist.jp`
> 
> fue bastante lento, pero finalmente funcionó


It worked for me. I installed laravel / ui, I had the same error. Thank you

**Comment by ixperiencenl** [comment]
This is very strange behaviour.
I run Ubuntu 18 in a VM and try to update my Laravel packages.
It gives me this error.

When I try to open the JSON url, it gives the neat 404 error from the Packagist.

When I try to open the JSON url on the Windows host, it show the json data just fine.

I think it is worth investigating this further. Is maybe packagist blocking certain requests?

**Comment by mohsinalipro** [comment]
> 
> 
> `composer clear-cache` didn't work for me
> 
> it seems that there are some network issues from time to time on the main server `https://packagist.org`
> 
> i tried one of the [mirrors](https://packagist.org/mirrors) as a temporary workaround:
> 
> `composer config -g repo.packagist composer https?://packagist.jp`
> 
> it was pretty slow, but worked finally

Worked (I am using cPanel Terminal)

**Comment by hameedhub** [comment]
> `composer clear-cache` didn't work for me
> 
> it seems that there are some network issues from time to time on the main server `https://packagist.org`
> 
> i tried one of the [mirrors](https://packagist.org/mirrors) as a temporary workaround:
> 
> `composer config -g repo.packagist composer https?://packagist.jp`
> 
> it was pretty slow, but worked finally

This worked for me! Thanks so much

**Comment by p2made** [comment]
I've been having an occurence of this issue. None of the suggestions in this thread have worked, but I've found that the issue only occurs when I attempt to load `"npm-asset/pdfmake": "~0.1"`. When I use `"bower-asset/pdfmake": "~0.1"` (as I previously had been, I'm migrating some of my dependancies to using npm) there's no error. I've opened an issue [here](https://github.com/bpampuch/pdfmake/issues/1839).

**Comment by MohammadTaher99** [comment]
> `composer clear-cache` didn't work for me
> 
> it seems that there are some network issues from time to time on the main server `https://packagist.org`
> 
> i tried one of the [mirrors](https://packagist.org/mirrors) as a temporary workaround:
> 
> `composer config -g repo.packagist composer https?://packagist.jp`
> 
> it was pretty slow, but worked finally

This worked for me.Thanks:)

**Comment by peter279k** [comment]
It seems that this problem is about failing to download required JSON from Packagist mirror site.

And I've suffered this issue from main and my Packagist mirror before.

It usually gets failed when the specific mirror site is upgrading mirror data.

And it doesn't have the current way to resolve this issue at this moment.

Some possible ways I try are as follows:

- Running failed command again. That is, when using the `composer install` command is failed, running this command again.
- Using the `composer clear-cache` to remove possible cached files and run the failed command again.

**Comment by RoseRiyadh** [comment]
> Can you try
> 
> composer clear-cache
> 
> then
> 
> composer -vvv
> 
> after that try running the install command for laravel, it worked for me though

This helped me, Thank you <3.

**Comment by oussamabouchikhi** [comment]
> `composer clear-cache` didn't work for me
> 
> it seems that there are some network issues from time to time on the main server `https://packagist.org`
> 
> i tried one of the [mirrors](https://packagist.org/mirrors) as a temporary workaround:
> 
> `composer config -g repo.packagist composer https?://packagist.jp`
> 
> it was pretty slow, but worked finally

I tried all previous sollution and nothing happened but finally this worked for me

**Comment by andreas-hub** [comment]
I got this issue when I forgot to use SUDO. So `sudo composer update` worked for me.

**Comment by ixperiencenl** [comment]
Beste mailer, in augustus ben ik minder goed bereikbaar in verband met de vakantieperiode. Spoedeisende zaken kunnen telefonisch worden gemeld op het bij u bekende telefoonnummer. Let op; hiervoor kunnen extra kosten in rekening worden gebracht. Vanaf maandag 30 augustus ben ik weer volledig bereikbaar.

Bedankt voor uw begrip.

Dear reader, in the month of august I my attainability is limited due to holiday times. Emergency cases can be reported on the known phone number you have. Attention; additional fees may be charged. From monday the 30th of august I am fully operational again.

Thank you for your understanding.

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by savan13** [comment]
> Can you try
> 
> composer clear-cache
> 
> then
> 
> composer -vvv
> 
> after that try running the install command for laravel, it worked for me though

Same issue

**Comment by paugnu** [comment]
There are many reasons for this error. One additional thing to check is that, if you're using private repos with user/pass, you might not have the correct permissions.

Check:
- auth.json file, check credentials
- if necessary, set up new credentials and try again

**Comment by victorboilevin** [comment]
> There are many reasons for this error. One additional thing to check is that, if you're using private repos with user/pass, you might not have the correct permissions.
> 
> Check:
> 
> * auth.json file, check credentials
> * if necessary, set up new credentials and try again

Credentials problem for me!

**Comment by martinberlin** [comment]
Yes that happened for me too!
To know the current version and update details:

composer diagnose

If you spot there:
Checking github.com oauth access: The oauth token for github.com seems invalid, run "composer config --global --unset github-oauth.github.com" to remove it

Just remove it. And try install again. In my case I was getting 404 errors because an outdated key was there (Although it expected other error with that instead of 404)

**Comment by selcuktemizsoy** [comment]
> Yes that happened for me too! To know the current version and update details:
> 
> composer diagnose
> 
> If you spot there: Checking github.com oauth access: The oauth token for github.com seems invalid, run "composer config --global --unset github-oauth.github.com" to remove it
> 
> Just remove it. And try install again. In my case I was getting 404 errors because an outdated key was there (Although it expected other error with that instead of 404)

This one helped me for some situation. I think token is expired and it couldn't connect to git repo due to this reason. But after removing it, it asked me for new token and I generated new one and it fixed the problem. Thank you.

**Comment by Hillaryudechukwu** [comment]
nano ~/.composer/auth.json
change ==>
 "github-oauth": {
    "github.com": "ghp_[YOUR-PERSONAL-TOKEN]"
  }
to ==>
delete the github.com entry under "github-oauth": {}
That's it.

**Comment by b3wii** [comment]
This helped :)
rm -Rf ~/.composer/cache/files/*

**Comment by ixperiencenl** [comment]
Beste relatie, van 6 t/m 26 mei zijn wij beperkter bereikbaar i.v.m. vakantie. Als zelfstandig ondernemer kan ook ik niet altijd aan staan. Collega's zullen werkzaamheden waar nodig waarnemen en overnemen, alleen indien uw verzoek spoed behoeft kunt u deze bereiken op support[@]ixperience.nl 

Alleen bij gevallen waarbij ernstige spoed vereist is kunt u mij bellen op het bij u bekende nummer. Let op: ik ben ook daar niet altijd bereikbaar i.v.m. mobiel bereik.

**Comment by b3wii** [comment]
This worked for me:
`php composer.phar config --global --editor --auth`
