### ISSUE TITLE
InvalidRepositoryException "Some branches contained ... License "GPL-2.0+" is a deprecated SPDX license identifier"

### ISSUE THREAD

**Issue by mwjames** [composer/composer#7026]
```json
{
	"name": "mediawiki/semantic-media-wiki",
	"type": "mediawiki-extension",
	"description": "MediaWiki extension that lets you store and query structured data within wiki pages",
	"keywords": [
		"SMW",
		"Semantic MediaWiki",
		"Wiki",
		"MediaWiki"
	],
	"homepage": "https://www.semantic-mediawiki.org/wiki/",
	"license": "GPL-2.0-or-later",

```
https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/composer.json

## Issue

Composer spouts [0] with the following output:

```The mediawiki/semantic-media-wiki package of which you are a maintainer has
failed to update due to invalid data contained in your composer.json.
Please address this as soon as possible since the package stopped updating.

It is recommended that you use `composer validate` to check for errors when you
change your composer.json.

Below is the full update log which should highlight errors as
"Skipped branch ...":

...

[Composer\Repository\InvalidRepositoryException]: Some branches contained invalid data and were discarded, it is advised to review the log and fix any issues present in branches

Reading composer.json of mediawiki/semantic-media-wiki (2.5.x)
Importing branch 2.5.x (2.5.x-dev)
Skipped branch 2.5.x, Invalid package information:
License "GPL-2.0+" is a deprecated SPDX license identifier, use "GPL-2.0-or-later" instead
```

## Expected

I don't really care about "License "GPL-2.0+" is a deprecated SPDX license identifier, use "GPL-2.0-or-later" instead" and Composer should not throw a `InvalidRepositoryException` on some license identifier causing a spam with each PR that gets merged.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2957

**Comment by Seldaek** [comment]
I see you already fixed it in the master branch so I trust this is now resolved.

**Comment by mwjames** [comment]
> I see you already fixed it in the master branch so I trust this is now
> resolved.

No, It is not since each branch reports the same issue and it is
unfeasible to correct those branches.

Furthermore, the master branch on packagist.org has not been updated
due to the exception and holds an outdated sha1 reference from
2018-01-15 07:06 UTC.

As I said in the beginning, you should just not throw an exception on
a `License` issue that has no functional bearing on a package.

If you need to log those issues that's fine but don't throw an exception!

**Comment by Seldaek** [comment]
I fixed it yesterday so we only warn/throw on issues in new/updated branches. I don't see an issue on packagist.org anymore for mediawiki/semantic-media-wiki - if there's an other package involved please let me know which.

**Comment by mwjames** [comment]
>  I don't see an issue on packagist.org anymore for mediawiki/semantic-media-wiki - if there's an other package involved please let me know which.

A community member posted to our 2.5.x backport branch with the result that I received another "Some branches contained invalid..." message [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2957#issuecomment-362827501

**Comment by mwjames** [comment]
... and now I receive the same message for the master branch, I really thought the issue was fixed.

```
Reading composer.json of mediawiki/semantic-media-wiki (ftext-update)
Importing branch ftext-update (dev-ftext-update)
```

**Comment by mwjames** [comment]
The constant `InvalidRepositoryException` spam forced me to manually change the `composer.json` in a backport branch to switch from `GPL-2.0+` to `GPL-2.0-or-later` but this is surely impractical for any future use case.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/1d745f436385b28c667c5cf346eff46bd6337005

**Comment by mundschenk-at** [comment]
I've just seen the same issue pop-up with [mundschenk-at/php-typography](https://packagist.org/packages/mundschenk-at/php-typography) :(

**Comment by Seldaek** [comment]
All I said was it will not warn about old branches being outdated anymore. It still warns for new branches so that people update their projects to the latest SPDX identifiers.

**Comment by mundschenk-at** [comment]
On packagist.org an exception is thrown, even for old branches.

**Comment by mwjames** [comment]
> All I said was it will not warn about old branches being outdated anymore.
> It still warns for new branches so that people update their projects to the
> latest SPDX identifiers.

Maybe I was unclear about the issue, informing about a possible
incompatibility is fine throwing an exception (and hereby not updating
the package) on a non-functional attribute is NOT.

If we were talking about a damaged JSON, or some other issues in the
JSON then this would an appropriate action (due to functional
impairment) but a deprecated licence is definitely not one of those
cases.

**Comment by Seldaek** [comment]
Yes I got it.. I was hoping to move people forward to the latest standard but it seems that whining endlessly here is easier than updating composer.json files so I give up. I'll remove the validation and we can all happily use deprecated stuff for the ages to come.

**Comment by kghbln** [comment]
An interesting concept: Defying reality by trying to fix the user and then insulting them as the result. One of Composer's finest hours I guess.

**Comment by mwjames** [comment]
> Yes I got it.. I was hoping to move people forward to the latest standard

I appreciated your intentions but it causes more work (and hereby
needless pain) with less than an ideal outcome. Educating users is
fine, forcing them to do something should only be considered when
functional impairment is imperative.

> composer.json files so I give up. I'll remove the validation and we can all
> happily use deprecated stuff for the ages to come.

This should close #7073 as well.

**Comment by Seldaek** [comment]
@kghbln Fixing the user? What are you even talking about? I am just trying to keep the ecosystem together behind the SPDX standard. If we all use the latest identifiers it means people can do analysis on the license identifiers and get valid results. If people have outdated stuff in there we don't know what it means. For example GPL-2.0 is not clear, as some meant GPL-2.0+ and some meant really only GPL-2.0. I assume that's why the SPDX folks decided to clarify it in their latest release with the -only / -or-later suffixes.

And yes it is frustrating to only get a ton of resistance to this, and to see people spend a lot of time arguing instead of taking a little time fixing their composer.json. You probably ended up on this issue because of SMW links, but I have the pleasure to see all of the other issues too, and the tweets, and the emails. From my perspective it indeed looks like one of the Composer users' finest hours. I guess maintainers and users can't always understand each other. 

Anyway fix is deployed, have a great day.

**Comment by kghbln** [comment]
> I guess maintainers and users can't always understand each other.

Indeed. So I am a user after all? Whatever. Have a great day, too.

**Comment by dg** [comment]
It is a big mistake of SPDX. 

Identifier `GPL-2.0` is really clear. It means GPL 2.0 exactly, no GPL 3 or 4. (In fact `-or-later` seems to me like a sign of a bianko check and I would never do it and I don't understand that someone is doing it, but it is the matter of others). There is another clear identifier `GPL-2.0+`.

What I do not understand is that orgranization SPDX will decide to unnecessarily change the identifiers of one of the most used licenses. That they do a huge BC break that affects the open source world. Why?

Even SPDX is not prepared for this foolishness, their FAQ is now inconsistent with their list https://spdx.org/frequently-asked-questions-faq-0 (look for GPL). 

I think that if someone makes a mistake, it's better to say it, than force millions of open source developers to "fix" their composer.json files, files that were perfectly fine yesterday. We are not sheeps.

**Comment by mundschenk-at** [comment]
Fascinating. The [license list on spdx.org](https://spdx.org/licenses/) reflects version 3.0 of the specification, supposedly released on December 28 last year. The [latest specification for public perusal](https://spdx.org/specifications) is 2.1, though. The [GitHub repository indicates that neither versions 2.2 nor 3.0 have yet been released](https://github.com/spdx/spdx-spec/milestones).

So discussions whether it's actually appropriate to prevent package updates on "non-functional attribute" aside, basing anything on that 3.0 license list seems premature to me. **This is not a released specification.**
