### ISSUE TITLE
unable to install by composer

### ISSUE THREAD

**Issue by flik** [composer/composer#7028]
My `composer.json`:

```
composer require guzzlehttp/guzzle:~6.0
```

Output of `composer diagnose`:

```
Jan2018@adminxA MINGW32 /d/xampp/htdocs/zf-tutorial
$ composer require guzzlehttp/guzzle:~6.0
Content-Length mismatch, received 1847255 bytes out of the expected 1913396
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
```

When I run this command:
I want to install guzzle according to instructions on http://docs.guzzlephp.org/en/stable/overview.html#installation but getting nothing.

```
composer require guzzlehttp/guzzle:~6.0
```

I get the following output:

```

Jan2018@adminxA MINGW32 /d/xampp/htdocs/zf-tutorial
$ composer require guzzlehttp/guzzle:~6.0
Content-Length mismatch, received 1847255 bytes out of the expected 1913396
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
```

And I expected this to happen:
Guzzul should install.

**Comment by tomzx** [comment]
I see you're running on Windows but using something else than `cmd.exe`. Would you mind trying to run the same command using `cmd.exe` to verify if the error can be reproduced? Furthermore, how did you install PHP? Can you run `php -v` and share the results?

**Comment by flik** [comment]
```
$ php -v
PHP 7.0.13 (cli) (built: Nov  8 2016 13:45:28) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

**Comment by ace411** [comment]
I am experiencing a similar problem. Below are screenshots of my ```composer update```, ```composer diagnose```, and ```php --version``` screens as of 02/02/2018.
![composer-update-02-02-2018](https://user-images.githubusercontent.com/11040337/35715937-9b027ba0-07e6-11e8-89e9-224d5d0034af.JPG)
![composer-diagnose-02-02-2018](https://user-images.githubusercontent.com/11040337/35715936-9ab26ef8-07e6-11e8-9000-422d3b8ea746.JPG)
![php-version](https://user-images.githubusercontent.com/11040337/35715938-9b4f894a-07e6-11e8-8f61-a3dfdf1e8131.JPG)
