### ISSUE TITLE
Overriding a single File from available packages

### ISSUE THREAD

**Issue by techsemicolon** [composer/composer#7029]
Hello All,

I have been into situations where packages available were working best, I wanted to extend some of the existing class methods or add some new ones. I could do something which had my custom class which extends a base class of package file I want to modify. 

However this does not suffice all the time. For example in Laravel's builder, if we want to add a new method, we can have custombuilder(having new methods) which extends builder. But this builder is getting used in lot of places internally in the package. So it would be lot of change which is not standard to implement.

Also have seen reviews like this  : http://shyammakwana.me/php/laravel-override-vendor-classes.html
 But I think it would be good if it's handled internally so that we don't need to do composer dump autoload everytime that package is updated?

I would like to propose a configuration in composer where we can override just a particular class in a package. 

`"autoload": {
        "override-files" : {
            "Illuminate/Database/Eloquent/Builder.php" : "Custom/Database/Builder.php"
        }
    }`

So when application will need to get Eloquent Builder it will look under custom/Database/Builder.php instead of the Illuminate/Database/Eloquent/Builder.php file in package. 

This will give us huge advantages where any package, you can get 90% of the functionalities available and add the 10% on the top of it by overriding some of the function/add some new ones. 

I am relatively new to raising a suggestion on github, I am not sure if this is the right place to suggest this. But I would like to see if this makes sense to anyone else.  I would love to raise  PR for the same if this approach seems good to other experienced contributors for this package.

Thanks, Mihir.

**Comment by techsemicolon** [comment]
Thanks for your response @kenorb, the situation is for overriding just one of few handful of classes in the package.  Replace might be overkill. Patching is also a workaround, but composer is used so extensively, having something in the composer package to support overrides would be a much straightforward solution. (I can maybe refer it with similar to the way Magento overrides code files from its config.xml to add functionalities on top of available core packages).

**Comment by kenorb** [comment]
@techsemicolon You can also replace the files by adding relevant commands in [`post-install-cmd` event](https://getcomposer.org/doc/articles/scripts.md#command-events).

E.g.

```
  "scripts": {
    "post-autoload-dump": ["cp /path/to/bar vendor/foo/bar", "cp /path/to/foo vendor/bar/foo"]
  },
```

**Comment by techsemicolon** [comment]
@kenorb this looks promising, I will give it a go. Thanks 😃

**Comment by Seldaek** [comment]
You can already do this by specifying a psr-4 autoloading rule in your package that is more specific than the original class's autoloading rule, e.g. to override `Illuminate\Database\Eloquent\Builder` you can do:

```
"autoload": {
    "psr-4": {
        "Illuminate\\Database\\Eloquent\\": "src/CustomEloquent"
    }
}
```

And in `src/CustomEloquent/Builder.php` place your custom `Illuminate\Database\Eloquent\Builder` class.

**Comment by devnix** [comment]
Hi @Seldaek! This solution gives me the following warning: 
```
Warning: Ambiguous class resolution, "Symfony\Component\HttpFoundation\Request" was found 2x: in
"/var/www/html/src/Override/Symfony/HttpFoundation/Request.php" and
"/var/www/html/vendor/symfony/http-foundation/Request.php", the first will be used.
```

Do you have any recommendations for overriding in Composer 2?

**Comment by Seldaek** [comment]
@devnix this is simply a warning to indicate something is maybe wrong, but in this case you can see it is picking your override one so it is actually working as it should. You can suppress it if you really care by excluding the original file:

```json
    "autoload": {
        "exclude-from-classmap": ["vendor/symfony/http-foundation/Request.php"]
    }
```

**Comment by d-damien** [comment]
It works but the problem is that you need to copy the whole class. It'd be great if we could rewrite only the parts we need − basically extending − but I can't seem to make it work. With DI you can specify a new class that you extend, but it'd be nice for composer to have something to work around packages that don't have DI.
