### ISSUE TITLE
[UX] improve the dependency resolution conflict/error, make it more readable at a glance

### ISSUE THREAD

**Issue by dkarlovi** [composer/composer#7033]
This was [started on Twitter](https://twitter.com/WyriHaximus/status/954412954136477698) by @WyriHaximus, adding here so it's not lost there.

[My suggestion](https://twitter.com/dkarlovi/status/955755318058868736) is:
> start with a known composer.json, try to install something which produces a conflict and then make the error message as clear as possible

[Also](https://twitter.com/dkarlovi/status/955755682858459137):
> We can even obey the verbosity flag here:
> `-v` Cannot install `X`
> `-vv` Cannot install `X`, blocked by `Y`
> `-vvv` Cannot install `X`, blocked by `Y`, might be satisfied by `Z1`, `Z2`, but isn't
> Or something similar.

So will fill in this issue with a basic `composer.json` which illustrates the issue.

**Comment by Seldaek** [comment]
2.0 improves this greatly so closing
