### ISSUE TITLE
Where is composer.phar

### ISSUE THREAD

**Issue by PebbleSun** [composer/composer#7037]
Hi

I have a server and when I got it Composer was installed by default. It is installed here:

/opt/cpanel/composer/bin/composer

when I list what is in the composer directory (the last one) there is nothing. It is not a directory. Can someone explain where on earth my composer.phar is as I think I need to move it to access Composer globally. 

I have used composer but I think I need to move the Composer.phar file to use it everywhere.

Many thanks for any help

Pebble

**Comment by stof** [comment]
this is because it is not a directory. It *is* the composer.phar executable (without the `.phar` extension to make the executable nicer)

**Comment by PebbleSun** [comment]
Thanks for your reply.
To execute Composer commands globally I believe I have to move this file (composer.phar) to /usr/local/bin/composer

In which directory do I have to be to execute mv composer.phar /usr/local/bin/composer to move this file or doesn't it matter in which directory this is executed?
I also don't know what to do if the file is called composer and not composer.phar. Will it still be moved without the file extension? I used the find command to try and find composer.phar and I got no result?

Many thanks for any help.

**Comment by curry684** [comment]
Please follow the relevant install guides at https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx

**Comment by Abilandou** [comment]
Everything was working well after  following steps from https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx;  
I am working on a Laravel project and when i tried to install an image package by running
sudo composer.phar require intervention/image or sudo php composer.phar require intervention/image

i get Could not open input file: composer.phar.

Please help.

**Comment by mrkhoa99** [comment]
@Abilandou You can try with the option COMPOSER_MEMORY_LIMIT=-1.

For example: `COMPOSER_MEMORY_LIMIT=-1 composer require mobiledetect/mobiledetectlib`

**Comment by sharkfin009** [comment]
@mrkhoa99 Thanks this worked! Please explain ? thanks!
