### ISSUE TITLE
SPDX license matching is incorrectly case-sensitive

### ISSUE THREAD

**Issue by DaveRandom** [composer/composer#7039]
My `composer.json`:

```json
{
  "name": "vendor/package",
  "license": "mit"
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
License "mit" is not a valid SPDX license identifier, see https://spdx.org/licenses/ if you use an open license.
/** stuff */
```

According to section 4 of the [SPDX license matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines):

> All upper case and lower case letters should be treated as lower case letters

This issue is also causing packagist to fail updating from webhooks and manually, for example when I press "Update" [here](https://packagist.org/packages/daverandom/lifx-lan-protocol) I get an error message stating:

> Skipped branch master, Invalid package information: 
> License "mit" is not a valid SPDX license identifier, see https://spdx.org/licenses/ if you use an open license.
> If the software is closed-source, you may use "proprietary" as license.

**Comment by phadej** [comment]
Note: https://github.com/spdx/spdx-spec/issues/63 The issue is still open.
