### ISSUE TITLE
composer update slowness: Windows 10 and packagist.org IPV6 DNS resolution

### ISSUE THREAD

**Issue by lxxps** [composer/composer#7043]
Nothing related with any composer file...

On Windows 10 NT, you may encounter slowness with a simple `composer update` command.

So, redo this command with options `composer update -vvv --profile`. If you see huge time differences on `Downloading https://packagist.org/*` operations (especially the `https://packagist.org/packages.json` one), your machine may have issue to resolve `packagist.org` IPV6 address.

To diagnose that, just decrease the `default_socket_timeout` setting in `php.ini`. If you see that some `Downloading https://packagist.org/*` operations fit this limit, your machine cannot resolve `packagist.org` IPV6 address.

A solution? Ofc :)

Determine the IPV4 address of `packagist.org` with `ping packagist.org -4` or `tracert -j packagist.org`, copy the IPV4 result, and, in your global composer `config.json` file, add theses lines:

```json
{
    "repositories": {
        "packagist": {
            "type": "composer",
            "url": "https://87.98.253.214",
            "options": {
                "ssl": {
                    "verify_peer": false,
                    "verify_peer_name": false,
                    "allow_ssl_downgrade": true
                }
            }
        }
    }
}
```

^^

**Comment by stof** [comment]
or configure your computer to prefer using IPv4 over IPv6 if your IPv6 networking is slow (which generally comes from crappy IPv6 support from your ISP).

Note that disabling peer verification in the ssl config means that the connection is not secure anymore (anyone can do a MitM attack, as any SSL certificate would be accepted), so I would not recommend this solution.

**Comment by lxxps** [comment]
Yes, i've seen this solution. Do you mean that even if I know the IPV4 address of `packagist.org`, I should not trust it?

Whatever, it also works with `verify_peer` set to `true` and `allow_ssl_downgrade` set to `false` (default values, if I remember well):

```json
{
    "repositories": {
        "packagist": {
            "type": "composer",
            "url": "https://87.98.253.214",
            "options": {
                "ssl": {
                    "verify_peer_name": false
                }
            }
        }
    }
}
```

So, does `verify_peer_name` may cause security issue, even if I know the IPV4 address of `packagist.org`?

Thanks for your feedback

**Comment by stof** [comment]
I mean that setting `verify_peer` or `verify_peer_name` to false defeats the purpose of using HTTPS in the first place.

**Comment by lxxps** [comment]
You're right, it seems that I can solve the issue and keep PEER name verification :)

```json
{
    "repositories": {
        "packagist": {
            "type": "composer",
            "url": "https://87.98.253.214",
            "options": {
                "ssl": {
                    "peer_name": "packagist.org"
                }
            }
        }
    }
}
```

See http://php.net/context.ssl

**Comment by Seldaek** [comment]
That kind of hackery is just not a great idea as if we change IPs for any reason you'll end up having issues, but I guess it's an ok workaround. Anyway not much we can do here I'm afraid so closing.
