### ISSUE TITLE
Running self-update can lead to "Array to string conversion" ErrorException

### ISSUE THREAD

**Issue by stronk7** [composer/composer#7045]
Using PHP 7.0.26 under MacOS X High Sierra (but I think it's PHP/OS version agnostic) , have detected some situations where the self-update command ends with `"Array to string conversion" ErrorException`. Tracing it down (using -vvv), I've ended @ line:

https://github.com/composer/composer/blob/f31e2552be7fb8f165af001b912c2bcfc2459245/src/Composer/Command/SelfUpdateCommand.php#L115

There,  both `$composeUser` and `$homeOwner`are used to compose the message. And they are arrays - see [posix_getpwuid()](http://php.net/manual/en/function.posix-getpwuid.php) - hence the error when users don't match.

Ciao :-)

**Comment by curry684** [comment]
Yep, seen same issue when trying to switch channels recently, didn't debug it because I thought I was triggering a really obscure case in my development build. Should be fixed if it also affects "real" users.

**Comment by stronk7** [comment]
Yay, thanks!
