### ISSUE TITLE
No symlink with local path repositories and stable version specified

### ISSUE THREAD

**Issue by Arcesilas** [composer/composer#7047]
My `composer.json`:

```json
    "require": {
        "arcesilas/dot-array": "^1.0"
    },
    "repositories": [
        {
            "type": "path",
            "url": "/path/to/dot-array",
            "options": {
                "symlink": true
            }
        }
    ]
```

Output of `composer diagnose`:

```shell
$ composer diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
```

When I run this command:

```shell
composer update
```

I get the following output:

```shell
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing arcesilas/dot-array (v1.0.0): Downloading (100%)         
Writing lock file
Generating autoload files
```

And I expected a symbolic link to be created instead of downloading the package:
```shell
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing arcesilas/dot-array (dev-master): Symlinking from ../dot-array
Writing lock file
Generating autoload files
```

If I specify a dev version (`dev-master` for instance), the package is actually symlinked.

When running `composer update -vvv` it seems that Composer only looks for branches:
```shell
Executing command (/home/olivier/dev/arcesilas/dot-array/): git branch --no-color --no-abbrev -v
Executing command (/home/olivier/dev/arcesilas/dot-array/): git log -n1 --pretty=%H
```

Obviously, Composer is not aware of the tags (ie versions) available in the local path repository...

Since I don't want to change my `composer.json`, I use [Studio]https://github.com/franzliedke/studio to load path repositories. This package works as expected: it loads the local path repository before running the actual update. Since Composer does not create a symlink when (I consider) it should, then no symlink is created.

Is there a reason to create symlinks only when requiring dev version like `dev-master`? If not, is there a way to solve this?

**Comment by Seldaek** [comment]
As per https://getcomposer.org/doc/05-repositories.md#path "If the package is a local VCS repository, the version may be inferred by the branch or tag that is currently checked out"

Only that version is made available to composer, so in your case most likely `dev-master` if `/home/olivier/dev/arcesilas/dot-array` has master checked out. As you ask for `^1.0` which does not include dev releases it picks the latest stable 1.x release from packagist.org instead of your local one. When you require explicitly dev-master, of if you'd require `^1.0@dev` assuming you have a 1.x-dev branch-alias set up for your master branch, then it should symlink.

**Comment by Arcesilas** [comment]
Thanks for your answer! It makes process clearer to me!

**Comment by bkdotcom** [comment]
I realize this issue has been closed, but I'd really like a "force-symlink" option available in the root project..    as is, I need to make sure my root composer.json and all composer.json's in the dependency chain refer to "dev-master" for local projects...     if there's a local repository @ "dev-master", and I've got "force-symlink",, it should satisfy any version tag!

**Comment by Arcesilas** [comment]
It would be very nice, indeed, especially if the option can be used by plugins (like [studio](https://github.com/franzliedke/studio)). I really like the idea to not have to change anything in `composer.json` to work on package development and to publish it.

**Comment by bkdotcom** [comment]
... perhaps rather than a all-or-nothing boolean, `force-symlink` could be a list of packages that should always be symlinked.

```
{
    "force-symlink": [
        'foo/package',
        'somedescendant/dependency'
    ]
}
```

**Comment by curry684** [comment]
Given the scenario you are hinting at you'll likely want to consider using prefer-dist options instead to check out repositories directly to your vendor folder.

**Comment by Arcesilas** [comment]
?
Could you be more specific? I don't understand what you mean...

**Comment by CrazyICT** [comment]
It would be very nice that we get a 'force-symlink' option (if found local path)

**Comment by ChrisEdwards** [comment]
I cannot agree more. I have fought this symlink issue for over a year now. This should be dirt simple, yet it is frustrating and unintuitive. I should not have to jump through hoops just to develop a local package. I just want to tell composer where to symlink to get this package and be done with it already.

**Comment by amrography** [comment]
In my case, the order of repos does matter. It was reading from remote instead of local

Before
```
"repositories": [
    {
      "type": "composer",
      "url": "https://x.repo.repman.io"
    },
    {
      "type": "path",
      "url": "../pkg/**/*"
    },
],
```

After:
```
"repositories": [
    {
      "type": "path",
      "url": "../pkg/**/*"
    },
    {
      "type": "composer",
      "url": "https://x.repo.repman.io"
    }
],
```

**Comment by Seldaek** [comment]
@amrography https://getcomposer.org/doc/articles/repository-priorities.md explains this in detail.

**Comment by bilogic** [comment]
> As per https://getcomposer.org/doc/05-repositories.md#path "If the package is a local VCS repository, the version may be inferred by the branch or tag that is currently checked out"

This is part of my `composer.json` and have a question on this:

```
    "require": {
        "my/repo1": "^1"
    }
    "repositories": [
        {
            "type": "path",
            "url": "/git/*/*",
            "options": {
                "symlink": true
            }
        }
    ]
```

My `/path/repo` is a Git repo tagged with `1.0.0` and `2.0.0`, currently pointing to `2.0.0`
Is there a way to make it mirror `1.0.0` of only `my/repo1` while symlink for the rest?

I looked at `config.json`, but wasn't sure which was it. Thank you.

**Comment by bilogic** [comment]
Found it. This allows me to mirror (thus lock) only `my/repo1` to `1.0.0` while symlinking the rest of my `path` repositories
```
"repositories": {
    "0": {
        "type": "vcs",
        "url": "/git/my/repo1"
    },
    "1": {
        "type": "path",
        "url": "/git/*/*",
        "options": {
            "symlink": true
        }
    }
}
```

**Comment by amrography** [comment]
> @amrography https://getcomposer.org/doc/articles/repository-priorities.md explains this in detail.

I had multiple mirrors for my package. Add the local mirror in first order solved my problem

**Comment by amrography** [comment]
> Found it. This allows me to mirror (thus lock) only `my/repo1` to `1.0.0` while symlinking the rest of my `path` repositories
> 
> ```
> "repositories": {
>     "0": {
>         "type": "vcs",
>         "url": "/git/my/repo1"
>     },
>     "1": {
>         "type": "path",
>         "url": "/git/*/*",
>         "options": {
>             "symlink": true
>         }
>     }
> }
> ```

Make 2 composer files will solve your issue in ease

https://stackoverflow.com/a/56263538/4414952

and I created an alias in .zsh

`alias cv=“COMPOSER=composer-testing.json composer ”`

**Comment by bilogic** [comment]
@amrography 

My purpose is not for testing, rather, packages need to be symlinked by default for changes to spread across projects all at once. However, there are legacy apps that need to be locked to certain versions. That is where `type: vcs` steps in.
