### ISSUE TITLE
composer not working and strange error

### ISSUE THREAD

**Issue by flik** [composer/composer#7048]
My `composer.json`:
I am getting this detail from : https://packagist.org/packages/xorm/xorm
```json
composer require xorm/xorm
```

Output of `composer diagnose`:

```
$ composer require xorm/xorm
Using version dev-master for xorm/xorm
./composer.json has been updated
Root package 'xorm/xorm' cannot require itself in its composer.json
Did you accidentally name your root package after an external package?

```

When I run this command:

```
...replace me...
```

I get the following output:

```
...replace me...
```

And I expected this to happen: I want to install xorm like other repositories. Can you tell me what is wrong here.

**Comment by Seldaek** [comment]
Please share your composer.json if you want help, but the error is pretty clear, it seems like you have `"name": "xorm/xorm"` in your composer.json, which causes the issue. Make sure you remove that.
