### ISSUE TITLE
Indent is off in "Pulling in changes" section

### ISSUE THREAD

**Issue by staabm** [composer/composer#7053]
when updating my dependencies (which are referenced via svn), I get the following ouput:

![grafik](https://user-images.githubusercontent.com/120441/35509151-5c3dc5a0-04f3-11e8-9f2a-2e79f5bfc584.png)

notice the "wrong" indent in the bottom left corner of the screen
(the ugly black bars in the screen just hide our internal commit messages)

```
$ composer --version
Composer version 1.7-dev (f31e2552be7fb8f165af001b912c2bcfc2459245) 2018-01-24 15:19:39

$ php --version
PHP 7.0.27-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jan  5 2018 14:12:46) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.27-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
    with blackfire v1.18.0~linux-x64-non_zts70, https://blackfire.io, by SensioLabs
```

**Comment by Seldaek** [comment]
I believe that's just wrong because you run in --verbose, which prints the output of the svn checkout which wouldn't otherwise happen if you didn't have --verboes then it would look correct.

If that assumption is correct then I'd say it works as expected, we can't tailor the output to every verbosity level it's too complex really.

**Comment by stof** [comment]
It is still weird to have extra indentation added to only *part* of the svn output.

**Comment by Seldaek** [comment]
It's two completely different pieces though.. Not sure it might be due to the discard prompt too. Anyway if you find an easy fix go for it but otherwise I'd say no big deal as non-verbose output is the default and that's what we target as main UX.
