### ISSUE TITLE
Wasted space with .git folder in defined repositories

### ISSUE THREAD

**Issue by Sarke** [composer/composer#7058]
With regular public packages the git folder is not included, but when you define a repository (e.g. private or github fork) the git folder remains.  I think this discrepancy needs to be fixed. 

I suggest either:

1. Always removing the `.git/` folder.

or 

2. Adding an option to remove the `.git/` folder, and/or setting the cloning depth.

I don't see why the git folder would be needed in `vendor/`.  One open source project I forked has a 262 mb git folder, which can grow the vendor folder by quite a bit.  

This would also fix related #6832.

**Comment by Jean85** [comment]
If the repository is on GitHub you could specify it in the repo type, and the API should kick in...

**Comment by Sarke** [comment]
Actually, this is true for packagist repos too when defining a @dev branch.

**Comment by Seldaek** [comment]
You can configure this via https://getcomposer.org/doc/06-config.md#preferred-install - for dev packages source is used by default and that means you get the .git folder.

**Comment by Radon8472** [comment]
I understand that the git folder is downloaded during the install.
But why issnt it enough when the .git folder goes to the `cache-repo-dir` ?

This .git folder in the vendor or target directory is yust space-wasting for `library` but it is a real problem for custom installer types like [ProcessWire-Module][pw-installer].
In that case you have the `.git` folder in your install directory for the module, and that is a real problem.

And I think it is no good solution to yust `.gitignore` all this folders.
For some custom installer types it could break the main-system when there are subfolders from git what dont belong to the installed composer-package.

[pw-installer]: https://github.com/harikt/pwmoduleinstaller
