### ISSUE TITLE
RFE: git stash should not require git config author

### ISSUE THREAD

**Issue by glensc** [composer/composer#7059]
When using composer in environment when git is not configured, the stash command used by update/install is failing because git is failing to create stash commit without configured author.

such environment is for example using composer install via docker.

I believe there's way to override this, by configuring suitable author name/email in vendor/package/.git.

```
The package has modified files:
    M src/file1.php
    M src/dir/file2.php
    Discard changes [y,n,v,d,s,?]? s
    Update failed (Could not stash changes

:
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@b0c7dd324b07.(none)')
Cannot save the current index state
)
    Would you like to try reinstalling the package instead [yes]? n


```

**Comment by Jean85** [comment]
Maybe you can avoid this issue altogether by not installing dependencies with Git, using the `--prefer-dist` flag when installing.

**Comment by Seldaek** [comment]
Seems like we might be able to set (and unset after!) GIT_AUTHOR_EMAIL / GIT_AUTHOR_NAME if they are missing to force git stash to work even without configured author. Needs to be experimented.

**Comment by glensc** [comment]
@Jean85 your suggestion does not always apply. the dependencies may be installed via git. not everything is in github :)

**Comment by Seldaek** [comment]
Closing as this doesn't really seem to be worth fixing. Too edge-casey and nobody cared in two years..
