### ISSUE TITLE
Can't validate composer.json with valid license

### ISSUE THREAD

**Issue by taq** [composer/composer#7062]
My `composer.json`:

```json
    "license": "GPL-2.0-or-later",
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
License "GPL-2.0-or-later" is not a valid SPDX license identifier, see https://spdx.org/licenses/ if you use an open license.
If the software is closed-source, you may use "proprietary" as license.
The version field is present, it is recommended to leave it out if the package is published on Packagist.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
```

When I run this command:

```
$ composer validate
```

I get the following output:

```
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
License "GPL-2.0-or-later" is not a valid SPDX license identifier, see https://spdx.org/licenses/ if you use an open license.
If the software is closed-source, you may use "proprietary" as license.
The version field is present, it is recommended to leave it out if the package is published on Packagist.
```

And I expected this to happen:

A valid file. I got some emails from Packagist telling me that the license there was invalid, and asked me to select a new one from SPDX. I changed to "GPL-2.0-or-later", as specified there, but no luck, as seen above.

**Comment by Seldaek** [comment]
Are you sure you are using the latest composer locally? If you have an old version it might not have the new SPDX identifiers. Run `composer self-update` to be sure.

**Comment by taq** [comment]
Hey, thanks for your answer, @Seldaek , I confirmed yesterday that I have the most recent *Ubuntu* composer version, but not the more recent on the repository. But I was wondering, even if I have the most recent version, I just noticed an error because I got another email from Packagist telling me that there was still an error on the package, but then I noticed:

```
Reading composer.json of taq/torm (v1.3.1)
Importing tag v1.3.1 (1.3.1.0)
Reading composer.json of taq/torm (v1.2.8)
Skipped tag v1.2.8, tag (1.2.8.0) does not match version (1.2.7.0) in composer.json
```
So seems that Packagist is updated, but it's complaining an old version has a now invalid license, ouch! The more recent version (1.3.1) seems ok. If it builds the latest version, to me it's ok.

Also, running `composer self-update` on the Ubuntu package gives me this:

```
$ composer self-update
                                                               
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "self-update" is not defined.
```

I have the version 1.5.1 installed, seems it don't have the `self-update` option.

```
$ composer -h | grep update
```
I tried to find a recent PPA but seems that there is not one. Maybe a good idea to remove the package and install it as [instructed here](https://getcomposer.org/download/)?

**Comment by Seldaek** [comment]
It does not complain that 1.2.8 has an old license, it complains that `tag (1.2.8.0) does not match version (1.2.7.0) in composer.json` i.e. you had a "version" field hardcoded in composer.json and that didn't match your tag, so the tag is considered invalid. Best is to remove the version field altogether.

As for running an outdated Composer.. sadly we can't control what Ubuntu does, so yes if you want to run latest the best is to uninstall the package and install using our instructions.

**Comment by Seldaek** [comment]
Note that you still have a few branches that have outdated license fields and probably would be fixed by rebasing them against master: `issue11`, `issue12` and `postgresql`.

**Comment by taq** [comment]
Yeah, as I said, on the most recent version, it don't complains, but dude, need to rebase all the other versions and tags, or remove the tags, losing the repository history? Packagist seems a little radical about that ... but also seems that it built with a recent version and ignored the other ones, so it's ok. Not the latest one (yet) but ok. :-)

**Comment by Seldaek** [comment]
Again, it won't complain about tags. It only complains about tags if they have an invalid version field in there, but that has been the case for years so nothing new.

For the license it only complains in newly updated branches that have been created/updated since we published the license change.

**Comment by taq** [comment]
Ok, "tags with invalid versions", I got it. But I just got those messages on the last week, the package is there for a long time ...
Anyway, seems that everything is good now, thanks for your attention! :+1:

**Comment by mcrase2020** [comment]
https://composer.json.jolicode.com/ is the resource, makes it easier to read .....
simply added a top line of license : "proprietary" to meet the standard the composer author failed to address
all objections closed using composer diagnose, composer self-update from command prompt
