### ISSUE TITLE
Composer PHP Version parsing

### ISSUE THREAD

**Issue by PatrickRose** [composer/composer#7067]
My `composer.json`:

```json
{
    "config": {
        "platform": {
            "php": "7.1"
        }
    },
    "name": "patrickrose/tmp",
    "require": {
        "symfony/debug": "4.0.3"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.symfony/debug : exact version constraints (4.0.3) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: WARNING
You are not running the latest stable version, run `composer self-update` to update (1.6.2 => 1.6.3)
Composer version: 1.6.2
PHP version: 7.1.11-1+0~20171027135825.10+jessie~1.gbp2e638d
PHP binary path: /usr/bin/php7.1
```

When I run this command:

```
composer install
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/debug 4.0.3 -> satisfiable by symfony/debug[v4.0.3].
    - symfony/debug v4.0.3 requires php ^7.1.3 -> your PHP version (7.1.11-1+0~20171027135825.10+jessie~1.gbp2e638d) overridden by "config.platform.php" version (7.1) does not satisfy that requirement.
```

It looks like Composer thinks I don't have PHP 7.1.3 because of my configuration. If I change the `composer.json` to instead be 

```json
{
    "config": {
        "platform": {
            "php": "7.1"
        }
    },
    "name": "patrickrose/tmp",
    "require": {
        "php": ">=7.1.3"
    }
}
```

I get 

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php >=7.1.3 but your PHP version (7.1) does not satisfy that requirement.
```

**Comment by curry684** [comment]
I don't understand the issue?

**Comment by stof** [comment]
Well, `7.1` does not match the `>= 7.1.3, <8` requirement. Composer is totally right. `7.1` is normalized to `7.1.0.0` (composer works with 4 segments internally), which is lower than `7.1.3.0` (the normalized version of `7.1.3`)

**Comment by PatrickRose** [comment]
This behaviour surprised me. I assumed that saying I had `7.1` would allow Composer to assume I had any of the patch versions of 7.1 - after investigating I saw that Composer had normalised it to `7.1.0.0` but it's not clear that Composer has normalised it _in the error message_.

If the message displayed `This package requires php >=7.1.3 but your PHP version (7.1 - normalised to 7.1.0) does not satisfy that requirement.` then it probably would have been clearer?

**Comment by stof** [comment]
`Any 7.1 patch version` is not a version. It is a version range. Composer needs a PHP version for its resolution.

Imagine that we have one package asking `PHP < 7.1.5` and the other one asking `PHP >= 7.1.8`. What would happen if you consider your PHP version to be `any 7.1 patch version` ? would it be possible to install these 2 packages together ? It will never be possible to build a prod environment satisfying both packages.

**Comment by PatrickRose** [comment]
> It will never be possible to build a prod environment satisfying both packages.

No - but Composer has acted obtusely in this case. [The docs suggest just providing a minor version](https://getcomposer.org/doc/06-config.md#platform), so that's what we did. How Composer internalises that under the hood is up to Composer - but if I get told that my PHP version doesn't match with a message that give a PHP version that _does_ match it leads to confusion.

Can the message be updated to be clearer about what Composer has done?

 * Saying what my `PHP_VERSION` isn't helpful - Composer isn't using it
 * Saying what my config value is isn't helpful - Composer has normalised it to something else

**Comment by curry684** [comment]
I agree the docs example should use 3 digits,  but the errors themselves are highly verbose already.
