### ISSUE TITLE
Require doesn't seem to resolve replacements correctly

### ISSUE THREAD

**Issue by IchHabRecht** [composer/composer#7068]
My `composer.json`:

```json
{
    "require": {
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.6.3
PHP version: 5.5.0
PHP binary path: C:\Unix\PHP-5.5.0-x64\php.exe
```

When I run this command:

```
composer require nimut/typo3-complete="7.6.x-dev" typo3/cms-core="*"
```

I get the following output:

```
[InvalidArgumentException]
  Package typo3/cms-core at version * has a PHP requirement incompatible with your PHP version (5.5.0)
```

And I expected this to happen:
Require nimut/typo3-complete="7.6.x-dev" should require the current dev-TYPO3_7-6 branch from typo3/cms that replaces typo3/cms-core and is compatible to PHP 5.5. Instead only the available packages from typo3/cms-core seem to be fetch. Those are not compatible to PHP 5.5.

Interesting: am able to run `composer install` with a composer.json

```
{
    "require": {
        "typo3/cms-core": "*",
        "nimut/typo3-complete": "7.6.x-dev"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

**Comment by IchHabRecht** [comment]
Some more information about my use case:

In my composer.json I have the constraint: "typo3/cms-core": "^7.6". As I like to execute tests against the current developbranch, I need to change the constraint to "typo3/cms-core": "*" (or "typo3/cms-core": "@dev") which I'm trying to archive with `composer require --no-update "typo3/cms-core": "*"` to be able to run `composer install` afterwards. Unfortunately even with `--no-update` composer seems to check for a valid version and fails.

**Comment by Seldaek** [comment]
I doubt this can be done very easily tbh.. Such a complex setup with replacers and influenced by the PHP version gets very messy to handle. I agree it'd be nice to have it working but I won't be spending time on this as I don't see how to get it done quick enough.

**Comment by Seldaek** [comment]
We improved things in this regard as much as we could IMO in 2.0, if still not enough it'll probably be a wont-fix situation, so closing here.
