### ISSUE TITLE
Licenses GPL-2.0 and GPL-3.0 and broken open source world

### ISSUE THREAD

**Issue by dg** [composer/composer#7073]
Please, continue to support licenses `GPL-2.0` and `GPL-3.0`.

You have changed license name from `GPL-2.0` to `GPL-2.0-only`. This is a totally unnecessary change that has no meaning at all (should we expect change from `BSD-3-Clause` to `BSD-3-Only-Clause`?). It has completely broke all my open source projects. New versions are not promoted on Packagist. I receive long and hard to understand emails that there is something wrong with my project (from Packagist).

This BC break adds work for open source developers. Unnecessary work.

Please fix it.

**Comment by mundschenk-at** [comment]
This really is very bad. Contrary to #7026, the issue is not fixed :(
