### ISSUE TITLE
Composer syntax using require

### ISSUE THREAD

**Issue by PebbleSun** [composer/composer#7074]
Hi 
I had a curious issue involving syntax and I was wondering if anyone has encountered the same issue.
I have two identical websites one staging and one live. On the staging site I used the composer require as follows which worked fine:
$ composer require "drupal/<module name>:^1.0"
When I used exactly the same command on the other site it wouldn't work. I got it to work correctly by adding one space after the colon:
$ composer require "drupal/<module name>: ^1.0"
Does anyone know why it works without the space on one site and with the space on another. The sites are identical and on the same server. I wasn't making these commands as super user.
I know in the composer.json file there is a space after the colon on all require entries. Should there be a space after the colon when making these commands? In all the examples I have seen there is no space after the colon?

Thanks for any help

**Comment by PebbleSun** [comment]
Sorry the above commands were: 
$ composer require "drupal/module_name:^1.0"
and
$ composer require "drupal/module_name: ^1.0"
the words module_name were removed when I published the issue.
Thanks again

**Comment by tomzx** [comment]
There shouldn't be any difference between "this/package:^1.0" and "this/package: ^1.0".

You'll have to be more specific when you say "it wouldn't work". What did `composer` output when that happened?
