### ISSUE TITLE
composer-Keyword starts wrong version

### ISSUE THREAD

**Issue by Musikopi** [composer/composer#7078]
I installed and deleted composer a few times. In my www-directory there is one composer.phar-file. OK,
`php composer.phar` starts the current version:

> Composer version 1.6.3 2018-01-31 16:28:17 …

while the solo-keyword `composer` starts an older version:

> Warning: This development build of composer is over 60 days old. It is recommended to update it by running "/usr/bin/composer self-update" to get the latest version.
> Composer version 1.3-dev (324c31f4a7e6869590dedfd6ea95dcd9180eb33f) 2016-12-20 16:27:36 …

How can I change the keyword `composer` to use the newer installation, too? Btw I don't even know where files for the older composer version are because I think I deleted everything besides composer.phar in the www-directory.

**Comment by stof** [comment]
well, the old file seems to be `/usr/bin/composer` according to the message you get. It even tells you which command to run to be able to update it.
