### ISSUE TITLE
[FEATURE REQUEST] `composer download-install` option to allow `composer install` from cache

### ISSUE THREAD

**Issue by eusonlito** [composer/composer#7080]
I want to force to composer to download all packages before to install it and to speedup the dependencies installation on projects.

On production environment, I don't want to wait to packages download, it must be installed from cache.

Something like:

```
$> composer download-install && composer install # The packages will be installed always from cache
```

There are any composer option to do it?

Thanks!

**Comment by alcohol** [comment]
No such feature or option exists currently.

**Comment by eusonlito** [comment]
I know, it's a feature request.

**Comment by alcohol** [comment]
Yeah, that is probably not going to happen.

**Comment by eusonlito** [comment]
I know, but in some cases is not so easy. Thanks anyway.

**Comment by rquadling** [comment]
I use hirak/prestissimo to do the parallel download. You can then persist the composer cache as an immutable artefact somewhere. You may find that your pipeline tool already is capable of providing a previously constructed cache. We use BitBucket. Their pipelines can cache composer and node_modules between runs, significantly reducing the amount of time to do an install.

**Comment by Seldaek** [comment]
2.0 does the download of all packages first and then installs them so going to close this even though it's not available as a separate step I don't think we really want to add that.
