### ISSUE TITLE
How to automate local tests against multiple dependency versions?

### ISSUE THREAD

**Issue by lezhnev74** [composer/composer#7081]
I have an app which must work with a specific package in various versions. I'd like to automatically run local tests against different versions of the package.

**How is it done?**

I can only think of a manual way:
- change composer.json
- run `composer update`
- run tests
- repeat with another version

**Comment by stof** [comment]
Well, I suggest you to write a script automating the different steps you gave here. There is nothing forcing to do such steps manually.

**Comment by bizmate** [comment]
> I have an app which must work with a specific package in various versions
So you have this app code pushed to different branches? Then in each branch have the right dependency for the package and automated the tests.

About automation as suggested just instead of

> change composer.json
> run composer update

simply
`composer require vendor/package:$(MY_PACKAGE_VERSION)`

**Comment by lezhnev74** [comment]
Yes, looks like this is a way to do it. 
Since dependencies are cached that should not take too much time to pull another version.
