### ISSUE TITLE
Override composer config from the command line

### ISSUE THREAD

**Issue by h-bragg** [composer/composer#7082]
I am attempting to test multiple php versions locally for a library.

To be able to test php versions from `5.6` to `7.2` with `phpunit` (which no single version can cover all php versions). We need to do a composer install with the same php version. 

We are using the `composer` image from docker which uses a single php version, so to get the correct versions installed, we specify the php version in the platform configuration.

```json
{
    "config": {
        "platform": {
            "php": "7.2"
        }
    }
}
```

But this needs to be modified for each different version. I am currently replacing the version before doing an install in the file, which is a bit horrible.

What would work is being able to specify configuration options on the command line that will override the `composer.json` file. Something like:

```shell
~$ composer update --config "platform.php=7.2"
```

**Comment by alcohol** [comment]
I don't see overrides like such ever being supported.

You can just run:

```
composer config platform.php 7.0.26 && composer update
```

**Comment by amirmasoud** [comment]
A more versitle solution I could come up with is something like this:

```bash
COMPOSER_PLATFORM_PHP=$(composer config platform.php)
composer config platform.php x.y.z
composer install
composer config platform.php $COMPOSER_PLATFORM_PHP
```

or for `preferred-install`:

```bash
composer config preferred-install."my-org/*" "source"
composer install
composer config preferred-install."my-org/*" "dist"
```
