### ISSUE TITLE
Proc_open (NUL): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by arfurs** [composer/composer#7083]
I successfully installed composer through the installation steps of the official tutorial and have configured the environment variables. When I execute composer install and composer init or other instructions, PHP throws the following exceptions:

[ErrorException]
Proc_open (NUL): failed to open stream: No such file or directory

My operating system is windows10
The version of PHP is 7.1.3

The following are the following:

C:\xampp>composer -version
Composer version 1.6.3 2018-01-31 16:28:17

C:\xampp\htdocs>composer install
  [ErrorException]
  proc_open(NUL): failed to open stream: No such file or directory

My Composer.json :
{
    "require": {
        "monolog/monolog": "1.0.*"
    }
}

Request solution!

(I'm sorry, my English is not good, I translate this passage through the translation software.)

**Comment by Donng** [comment]
I have the same problem, how did u solve this?

**Comment by Cloudmersive** [comment]
Same problem

**Comment by jayimillena** [comment]
This doesn't work using Windows  10 OS, located on OneDrive.

Upon typing the command composer -version, on bash on a specific Laravel project, this returns, an exception trace:

() at phar://C:/composer/composer.phar/vendor/symfony/process/Process.php:285
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 proc_open() at phar://C:/composer/composer.phar/vendor/symfony/process/Process.php:285
 Symfony\Component\Process\Process->start() at phar://C:/composer/composer.phar/vendor/symfony/process/Process.php:196
 Symfony\Component\Process\Process->run() at phar://C:/composer/composer.phar/src/Composer/Util/ProcessExecutor.php:125
 Composer\Util\ProcessExecutor->doExecute() at phar://C:/composer/composer.phar/src/Composer/Util/ProcessExecutor.php:65
 Composer\Util\ProcessExecutor->execute() at phar://C:/composer/composer.phar/src/Composer/Package/Version/VersionGuesser.php:122
 Composer\Package\Version\VersionGuesser->guessGitVersion() at phar://C:/composer/composer.phar/src/Composer/Package/Version/VersionGuesser.php:71
 Composer\Package\Version\VersionGuesser->guessVersion() at phar://C:/composer/composer.phar/src/Composer/Package/Loader/RootPackageLoader.php:83
 Composer\Package\Loader\RootPackageLoader->load() at phar://C:/composer/composer.phar/src/Composer/Factory.php:368
 Composer\Factory->createComposer() at phar://C:/composer/composer.phar/src/Composer/Factory.php:595
 Composer\Factory::create() at phar://C:/composer/composer.phar/src/Composer/Console/Application.php:408
 Composer\Console\Application->getComposer() at phar://C:/composer/composer.phar/src/Composer/Console/Application.php:526
 Composer\Console\Application->getPluginCommands() at phar://C:/composer/composer.phar/src/Composer/Console/Application.php:187
 Composer\Console\Application->doRun() at phar://C:/composer/composer.phar/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar://C:/composer/composer.phar/src/Composer/Console/Application.php:122
 Composer\Console\Application->run() at phar://C:/composer/composer.phar/bin/composer:63
 require() at C:\composer\composer.phar:24
 
 Thank you anyway.
