### ISSUE TITLE
Wording: Downgrading instead of Updating

### ISSUE THREAD

**Issue by flowl** [composer/composer#7085]
This is not a bug or a major deal, it's more a "wish" concerning the following wording:

When downgrading, composer says `Updating`:

    - Updating phing/phing (2.16.0 => 2.14.0): Downloading (100%)

It should be 

    - Downgrading phing/phing (2.16.0 => 2.14.0): Downloading (100%)

When the new version is smaller than the version before.

**Comment by Seldaek** [comment]
Fixed in #7119
