### ISSUE TITLE
controversial advice to run `update` in warning while hash does mismatch

### ISSUE THREAD

**Issue by and800** [composer/composer#7091]
When content-hash is screwed:
+ `install` produces "Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them."
+ `validate` produces "The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update`."

In my opinion simply updating the project and regenerating lock file is not the best idea in most of cases.

Firstly, when the hash does not match the content, then either `.json` or `.lock` file is corrupt. It may be for example some unintended change to `.json` or bad vcs merge of `.lock` or maybe something else. So it is quite a good idea to investigate the cause before just rewriting lock file.

At second, in my current project it's difficult to `update` our every package because a few of them may break. It's risky and requires wide test coverage which we don't have

**Comment by alcohol** [comment]
It should be more specific, e.g.:

```
composer update --lock
// or
composer update lock
```

**Comment by Seldaek** [comment]
I don't think it should advice a update --lock, as that won't update any packages. If you changed a meaningful part of the composer.json and forgot to update that's a problem IMO. That's what we report. How to deal with it we can not know. If you are scared of running a `composer update` then don't do it, Composer isn't running it for you, it's just a warning.
