### ISSUE TITLE
Breaking changes in ClassLoader

### ISSUE THREAD

**Issue by soltmar** [composer/composer#7092]
Hi,

I've done self update on composer today.

When I've done `composer dump-autoload` some parts of my app are not working'

I've found that when I revert changes manually in `vendor/composer/ClassLoader.php` to state from before this commit [https://github.com/composer/composer/commit/e6d648f46569be1442ccd05f7555fc77b74e684f#diff-02d8fd4e825f60819515851876a3e6e6](https://github.com/composer/composer/commit/e6d648f46569be1442ccd05f7555fc77b74e684f#diff-02d8fd4e825f60819515851876a3e6e6) everything comes back to normal.

Please let me know if you need any more info.

**Comment by soltmar** [comment]
It looks lik this function changed class loading order (something related to that) so method from one class has been called earlier than the other one when booting app, which caused unexpected results.

I've sorted it.

**Comment by stof** [comment]
you mean, in case you have multiple definitions of the same class ?

**Comment by soltmar** [comment]
No. 
I'm using Laravel and it seems that it did register its packages with different order when using older composer.
Two packages were registering event which could be registered only once so previously different event callback has been fired and everything was working. After composer upgrade this order has changed so behaviour was different.
