### ISSUE TITLE
Composer Isshue of file_put_contents(): Filename cannot be empty

### ISSUE THREAD

**Issue by arpitmca1992** [composer/composer#7093]
[My `composer.json`:
{
}

When I run this command:

composer self-update or Any composer global require "laravel/installer"
I get the following output:

C:\Users\Devil>composer self-update

  [ErrorException]
  file_put_contents(): Filename cannot be empty

self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--set-channel-only] [--] [<version>]

And I expected to install laravel

**Comment by 376221269** [comment]
Have you got the solution

**Comment by arpitmca1992** [comment]
yes

**Comment by alcohol** [comment]
More information required to create a reproducible scenario.

**Comment by arpitmca1992** [comment]
Got solution
