### ISSUE TITLE
Working directory option -d not recognized

### ISSUE THREAD

**Issue by MrKappa** [composer/composer#7102]
Composer version 1.6.3 2018-01-31 16:28:17

When I run this command:

```
composer install -d=/var/www/html/
```

I get the following output:

```
Usage:
  install [options] [--] [<packages>]...

Arguments:
  packages                       Should not be provided, use composer require instead to add a given package to composer.json.

Options:
      --prefer-source
      ...etc etc....
      -d, --working-dir=WORKING-DIR  If specified, use the given directory as working directory.
      ...etc etc....
```

And I expected that composer will install dependencies as usual. After some test I figured out that the **-d** option isn't recognized anymore. If I use the alternative **--working-dir** it works as expected.

**Comment by shuryoka** [comment]
It should work if you write it like this:
`composer install -d /var/www/html`
The equals sign between -d and the path is unnecessary.

**Comment by tabascoterrier** [comment]
I just ran into this myself after my deploy scripts were no longer triggering Composer.  The -d=/foo/bar syntax previously worked, but now does not.  Omitting the equals sign does work.

**Comment by thueske** [comment]
Can confirm this issue.

-d=/foo/bar previously worked

**Comment by Seldaek** [comment]
Might be due to an update of symfony/console. I am not sure, but as we don't really control the argument parsing code I'll close this. Please use `-d foo` as workaround.
