### ISSUE TITLE
proc_open(NUL) failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by unknowableee** [composer/composer#7112]
Output of `composer diagnose`:

Checking platform settings: OK
Checking git settings:

  [ErrorException]
  proc_open(NUL): failed to open stream: No such file or directory

diagnose

This ErrorException also happens with every single command and thus renders Compose unusable currently

**Comment by Seldaek** [comment]
See https://github.com/composer/composer/issues/7186#issuecomment-373134916

**Comment by jayimillena** [comment]
Thank you in advance Seldaek, I'll try the linked you've shared:  https://github.com/composer/composer/issues/7186#issuecomment-373134916
