### ISSUE TITLE
SVN credentials error

### ISSUE THREAD

**Issue by vmeron** [composer/composer#7114]
When running a composer install or update using external svn repos with basic authentication, the system user running the command is sent rather than the one prompted for svn creds.

No auth.json is being used since I am on server used by other devs, so creds are needed on every command run.

The issue is non-existent on composer 1.6.2, only on 1.6.3

**Comment by idybil** [comment]
Same problem for me, it's working with 1.6.2 but not with 1.6.3

**Comment by ctrlaltca** [comment]
Just updated to composer 1.6.3, same problem.

**Comment by ctrlaltca** [comment]
Bisect results points to 9bc83d698e48dff2cd5559134c9c0877ca6977a4:
```
9bc83d698e48dff2cd5559134c9c0877ca6977a4 is the first bad commit
commit 9bc83d698e48dff2cd5559134c9c0877ca6977a4
Author: Markus Staab <markus.staab@redaxo.de>
Date:   Fri Jan 12 10:42:46 2018 +0100

    Pass auth credentials to svn log while retrieving commit logs

:040000 040000 ccf867b11feb1b3d2688858408133047997d60e9 57c8fde03069e7bb62bf40f583148c371247825f M	src
```
