### ISSUE TITLE
Separate config-dev

### ISSUE THREAD

**Issue by tomzx** [composer/composer#7118]
Hello,

I wonder if it would be a reasonable feature to have the ability to specify a different set of `config` property in a `dev` setting.

The use case I have in mind is as follow:
* `config` is used to specify the limitation of the target platform, or the lowest common denominator we want to use to generate the composer.lock file. This way, composer dependencies are computed against a specific PHP version instead of the current's developer PHP version.
* `config-dev` is used to specify a more flexible environment, aka the developer's environment, where it would be nice to use the latest tools/librairies whenever possible. Furthermore, this allows them to use more recent versions of PHP, on which some of those tools/libraries may rely.

**Comment by Seldaek** [comment]
I don't think this is a workable idea because that means the lock file would be created for the dev's environment and then wouldn't work for prod. Also developing on the same php version as you use in prod is kinda a good idea anyway.
