### ISSUE TITLE
Can't Install on Windows 10 Wampserver64 3.1.0

### ISSUE THREAD

**Issue by solarsnowfall** [composer/composer#7121]
Windows 10
Wampserver64 3.1.0

Attempting to run Composer-Setup.exe, after selecting path for php gives the following error dialog:

PHP Settings Error

The PHP exe file you specified did not run correctly:
C:\wamp\bin\php\php7.1.9\php.exe

Program Output:
Failed loading c:/wamp/bin/php/php7.1.9/zend_ext/php_xdebug-2.5.5-7.0-vc14-x86_64.dll

The matching thread safe dll file is in the directory. Any help?

Thanks!

**Comment by johnstevenson** [comment]
Read the Xdebug download instructions to get the correct version.

**Comment by solarsnowfall** [comment]
Thank you, however, after following the directions (https://xdebug.org/wizard.php) the error persists.

Instructions:

Download php_xdebug-2.6.0-7.1-vc14-x86_64.dll
Move the downloaded file to c:\wamp\bin\php\php7.1.9\ext
Edit C:\wamp\bin\apache\apache2.4.27\bin\php.ini and add the line
zend_extension = c:\wamp\bin\php\php7.1.9\ext\php_xdebug-2.6.0-7.1-vc14-x86_64.dll
Restart the webserver

Error:

The PHP exe file you specified did not run correctly:
C:\wamp\bin\php\php7.1.9\php.exe

Program Output:
Failed loading c:/wamp/bin/php/php7.1.9/zend_ext/php_xdebug-2.5.5-7.0-vc14-x86_64.dll

Please note the error indicates a different version of the file than I'm instructed to download from Xdebug.

Thanks.

**Comment by johnstevenson** [comment]
Sorry, but this is not a really our issue. Composer-Setup should have told you your CLI php.ini location (if not run ...php.exe --ini). Open it and remove the reference to xdebug, then:

1.  run Composer-Setup. If you have any further issues please report them here: https://github.com/composer/windows-setup/issues/new

2. Find out how to install xdebug on your particular setup (Composer disables it anyway)

**Comment by solarsnowfall** [comment]
Okay. Thank you for the redirection.
