### ISSUE TITLE
Exception handling for suggestions

### ISSUE THREAD

**Issue by antonioribeiro** [composer/composer#7123]
Would it be possible to set and exception handler to, when a class is missing from a suggested package, just tell the user (developer) to install the suggestion instead of throwing a exception? 

I have got some of those, and I know it may take a while until the developer realizes it's just something they forgot to install, because the suggestion appeared only when you first installed the package, it's kind of easy to forget if you needed that feature some time after.

Of course the package's `composer.json` would have to change a little, to provide the missing classes:

``` json
"suggest": {
    "doctrine/dbal": "Required to rename columns and drop SQLite columns (~2.6).",
    "pda/pheanstalk": {
        "dependencies": [
            "Pheanstalk\\Connection",
            "Pheanstalk\\Pheanstalk"
        ],
        "message": "Required to use the beanstalk queue driver (~3.0).",
    },
},
```

And, when the missing class is a suggestion, could say:

```
The class Pheanstalk\Connection was not found. 
You should probably install pda/pheanstalk, as suggested by laravel/framework.
```

**Comment by Seldaek** [comment]
I think it's best you do that in your code really, you can class_exists() and throw a meaningful exception. Otherwise this would bloat the autoloader with tons of mostly useless data from all dependencies.
