### ISSUE TITLE
Manual repository entry doesn't honor `github-protocols`

### ISSUE THREAD

**Issue by donatj** [composer/composer#7130]
Our CI's firewall rules only allow cloning over https, not SSH - for a complicated set of reasons. 

Setting github-protocols to https works for packages from packagist but *not* ones listed in the repositories ection.

I have put it in my config section of my composer.json - I have also done `composer config --global github-protocols https`

You can see the URL listed in the `repositories` url entry is `https://` yet it clones it via git, and git@ is added to my composer.lock - every package from packagist to the contrary is successfully cloned and logged to composer.lock as `https://`

The awful workaround we have at the moment is adding the following junk to our CI startup before running composer install - this of course only works on projects where we commit the `composer.lock` - but for our libraries we'd strongly prefer not to have to.

```
      - sed -i 's/com:redacted/com\\/redacted/' composer.lock
      - sed -i 's/git@/https:\\/\\//' composer.lock
```

My `composer.json`:

```json
{
	"name"       : "redacted/redacted",
	"license"    : "proprietary",
	"require": {
		"php"                         : ">=7.1",
		"psr/container"               : "~1.0",
		"psr/log"                     : "~1.0"
	},
	"require-dev": {
		"redacted/project" : "3.*"
	},
	"repositories": [
		{
			"type" : "vcs",
			"url"  : "https://github.com/redacted/project.git"
		}
	],
	"config": {
		"github-protocols": ["https"]
	}
}
```

When I run this command:

```
composer install
```

I get the following output:

```
Loading composer repositories with package information
Failed to clone the git@github.com:redacted/project.git repository, try running in interactive mode so that you can enter your GitHub credentials

                                                                                                                                                 
  [RuntimeException]                                                                                                                             
  Failed to execute git clone --mirror 'git@github.com:redacted/project.git' '/root/.composer/cache/vcs/git-github.com-redacted-project.git/'
```

And I expected this to happen:

Clone over https as instructed

**Comment by nanojover** [comment]
Is there any recent update on this?
We have the same problem and  `install --prefer-dist` it doesn't work.

**Comment by alcohol** [comment]
> but if you have time to dig into the code and see why it fails for you that'd be great

No feedback received, so no update.

**Comment by githoober** [comment]
The issue is still present. What kind of feedback was expected here?

**Comment by alcohol** [comment]
Debugging information that details why the code was not working as expected. Issues related to edge-case scenarios simply cannot be solved by us without additional research and effort put in by the reporting side.

**Comment by MatteoOreficeGS** [comment]
please could point me at the point in the code where the switch between https and ssh is done?

**Comment by sonnykt** [comment]
The error `Failed to clone the git@github.com:redacted/project.git repository, try running in interactive mode so that you can enter your GitHub credentials` is actually from `GitHubDriver::attemptCloneFallback()` https://github.com/composer/composer/blob/main/src/Composer/Repository/Vcs/GitHubDriver.php#L577. It seems that Composer failed to clone the repo via HTTPS and it fallback to SSH.

We also get this issue intermittently with a public Github repo.
