### ISSUE TITLE
Command not executable

### ISSUE THREAD

**Issue by huguijie** [composer/composer#7144]
![d2d63801-fdf8-49a6-b9da-3d400c12351b](https://user-images.githubusercontent.com/22492042/36824738-d7b0dafc-1d3e-11e8-981e-35c7a8198fef.png)
No command can be executed successfully, always stuck.I don't know why？
system is macOS，version is 10.13.3
PHP version is php7.1

**Comment by Seldaek** [comment]
Sorry but we do not support brew...
