### ISSUE TITLE
Composer can not calculate current git status for package

### ISSUE THREAD

**Issue by bm13kk** [composer/composer#7146]
We developing framework with many packages. So we develop in vendor folder.

And we got a lot of composer errors - becaues, composer can not correctly calculate current status of package git commit.

I go to `spryker/spryker` and `git checkout 0435916`. After that I try update - check result below.

For some reason, composer told me, that he have changes - but this is impossible:
```
➤ git status 
HEAD detached at 0435916f72
nothing to commit, working tree clean
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
require.spryker/spryker : unbound version constraints (dev-master) should be avoided
require.spryker/spryker-shop : unbound version constraints (dev-master) should be avoided
require.spryker-eco/loggly : unbound version constraints (dev-master) should be avoided
require.spryker/rabbit-mq : unbound version constraints (dev-master) should be avoided
require.spryker/install : unbound version constraints (dev-master) should be avoided
require.spryker/event-behavior : unbound version constraints (dev-master) should be avoided
require.spryker/synchronization-behavior : unbound version constraints (dev-master) should be avoided
require.propel/propel : exact version constraints (2.0.0-alpha8) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.6.3
PHP version: 7.1.13-1+0~20180105151623.14+stretch~1.gbp1086fa
PHP binary path: /usr/bin/php7.1
```

When I run this command:

```
composer update "spryker/spryker-shop" "spryker/spryker"
```

I get the following output:

```
- Updating spryker/spryker (dev-feature/CORE-2417_re_order 0435916 => dev-master 0871f05):     Update failed (Source directory /data/shop/development/current/vendor/spryker/spryker has unpushed changes on the current branch: 
M       Bundles/Messenger/composer.json
A       Bundles/Messenger/src/Spryker/Client/Messenger/FlashBag/FlashBag.php
A       Bundles/Messenger/src/Spryker/Client/Messenger/FlashBag/FlashBagInterface.php
M       Bundles/Messenger/src/Spryker/Client/Messenger/MessengerClient.php
M       Bundles/Messenger/src/Spryker/Client/Messenger/MessengerClientInterface.php
M       Bundles/Messenger/src/Spryker/Client/Messenger/MessengerDependencyProvider.php
M       Bundles/Messenger/src/Spryker/Client/Messenger/MessengerFactory.php
A       Bundles/Messenger/src/Spryker/Client/Messenger/ZedRequest/Messages.php
A       Bundles/Messenger/src/Spryker/Client/Messenger/ZedRequest/MessagesInterface.php
M       Bundles/ProductBundle/tests/SprykerTest/Zed/ProductBundle/Business/Availability/PreCheck/ProductBundleCartAvailabilityCheckTest.php
M       Bundles/Shipment/src/Spryker/Zed/Shipment/Business/Model/ShipmentOrderHydrate.php)
```

And I expected this to happen:
Update working.

**Comment by stof** [comment]
well, if you manually checkout a different commit, it might indeed be detected as unpushed changes (note that Composer does not complain about *uncommitted changes*, which is what `git status` would display, but about *unpushed* ones here)

**Comment by bm13kk** [comment]
1) this problem is schredinger. Some times composer work, even with changed branch. Sometimes, not.
2) everething is pushed
3) `composer clearcashe` did not change stuation
4) i tried to run composer in all cases
`git checkout master` - branch from json
`git checkout 0435916` - commit, that composer think i am rifght now
`git checkout 0871f05` - commit, that composer think i should get (commit from lock file)

Why composer in all cases think, that package at `0435916`?
Why this not changed with clear cashe?
I understand, that composer should actually check git status, not remember it.

**Comment by bm13kk** [comment]
One of workarounds, that i found - move folder, update, move folder back.
```
mv vendor/spryker/spryker tmp
composer update ...
rm -rf vendor/spryker/spryker
mv tmp vendor/spryker/spryker
```

But even on empty space composer found problems!
I got 
```
composer update "spryker/spryker-shop" "spryker/spryker"
Loading composer repositories with package information    Updating dependencies (including require-dev)         Package operations: 2 installs, 29 updates, 0 removals                                                     
  - Updating spryker/spryker (dev-bugfix/CORE-2425_add_not_valid_products_from_wishlist_to_cart f69cf41 => dev-feature/CORE-2417_re_order cf654ef):     Update failed (The .git directory is missing from /data/shop/development/current/vendor/spryker/spryker, see https://getcomposer.org/commit-deps for more information)
    Would you like to try reinstalling the package instead [yes]? y
```
when `vendor/spryker/spryker` was moved

**Comment by stof** [comment]
well, it looks like your package was initially installed from source, and then the `.git` folder was removed from it, which breaks stuff for composer (as it cannot just checkout a different commit in the git repository), which is why Composer asks you whether you want to reinstall the package.

**Comment by bm13kk** [comment]
>and then the .git folder was removed from it
it's never happend.
I do not delete `.git` folder.

More over, after this fix (moving folders) - composer stops complaing and start working.
Even in situations, when vendor folder already in new state. Composer just update lock file, and nothing more.

**Comment by alcohol** [comment]
You should not work in your vendor directory, you should use path repos for that use-case instead.

**Comment by vol4onok** [comment]
git fetch composer

**Comment by vol4onok** [comment]
`git fetch composer`
