### ISSUE TITLE
Question / Feature Request : Need option to remove certain files from

### ISSUE THREAD

**Issue by varunsridharan** [composer/composer#7149]
Just started to use Composer. and found that i can't exclude certain files

lets say i am working on a large application and i use a lot of libs from github
And all those has files like below

![image](https://user-images.githubusercontent.com/1884287/36878919-3aabe7fc-1de7-11e8-8a00-77b1238ce510.png)

In that i dont need most files except composer.json & LICENSE

Is there a way to exclude files / folders ?

My Composer JONS File
```json
{
    "require": {
        "johnbillion/extended-cpts": "*",
        "panvagenas/wp-admin-notices": "^2.0"
    },
    "config": {
        "vendor-dir": "packages"
    }
}

```

**Comment by Seldaek** [comment]
As a package consumer you can not exclude those files no, only package authors can decide which files they exclude from their package.
