### ISSUE TITLE
Pass variables to scripts in composer.json

### ISSUE THREAD

**Issue by sebastianpisula** [composer/composer#7155]
My `composer.json`:

```{
"scripts": {
    "pre-update-cmd": [
      "wp core install",
    ]
  }
```

I want run command `composer install --url=http://example.com` and run script with value od param: `wp core install --url=http://example.com`

Any idea?

**Comment by alcohol** [comment]
This is not supported.

**Comment by alcohol** [comment]
What you can do manually though, I think, is:

```
composer run-script pre-update-cmd -- --url=http://example.com
composer install --no-scripts
```

**Comment by Seldaek** [comment]
Yeah no as part of the install command this is not possible. If you need arguments you can put data into the "extra" key of composer.json and read it from a php script handler which then can call your wp process with the correct arguments.
