### ISSUE TITLE
[Feature] Remove all packages with same vendor

### ISSUE THREAD

**Issue by higoka** [composer/composer#7159]
I dont know if this is already implemented but it would be handy to remove all packages with same vendor with one command instead of typing all package names manually, specially if you have a lot.

For example i have 3 packages all under the same vendor "foo":
- foo/foo
- foo/bar
- foo/baz

If i want to remove them all, i could do it like this: **composer remove foo/***
This would then remove the 3 packages listed above.

**Comment by Seldaek** [comment]
Sounds good yes, we already support that for `composer update foo/*` so that'd make sense I think.
