### ISSUE TITLE
PHP 7.2.3 compatible?

### ISSUE THREAD

**Issue by sinnis-dev-trey** [composer/composer#7163]
Hey,

just got this error:

```
  Problem 1
    - This package requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 but your PHP version (7.2.3) does not satisfy that requirement.
  Problem 2
    - The requested PHP extension ext-mcrypt * is missing from your system. Install or enable PHP's mcrypt extension.
  Problem 3
    - The requested PHP extension ext-intl * is missing from your system. Install or enable PHP's intl extension.
  Problem 4
    - The requested PHP extension ext-zip * is missing from your system. Install or enable PHP's zip extension.
  Problem 5
    - The requested PHP extension ext-soap * is missing from your system. Install or enable PHP's soap extension.
  Problem 6
    - Installation request for colinmollenhour/php-redis-session-abstract v1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
    - colinmollenhour/php-redis-session-abstract v1.3.4 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0 -> your PHP version (7.2.3) does not satisfy that requirement.
  Problem 7
    - Installation request for magento/composer 1.2.0 -> satisfiable by magento/composer[1.2.0].
    - magento/composer 1.2.0 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0 -> your PHP version (7.2.3) does not satisfy that requirement.
  Problem 8
    - Installation request for friendsofphp/php-cs-fixer v2.1.3 -> satisfiable by friendsofphp/php-cs-fixer[v2.1.3].
    - friendsofphp/php-cs-fixer v2.1.3 requires php ^5.3.6 || >=7.0 <7.2 -> your PHP version (7.2.3) does not satisfy that requirement.
```

the ones from problem 2 - problem 5 can be fixed by installing/enabling modules so ignore that, but the others seem to not like my PHP version being on 7.2.3 - something that's already known about or new bug/version-support request? :)

Thanks.

**Comment by stof** [comment]
this should be reported to friendsofphp/php-cs-fixer, colinmollenhour/php-redis-session-abstract and magento/composer which are the packages saying that they are not compatible with PHP 7.2

and the problem 1 is because the root package also says it is incompatible with PHP 7.2, but I cannot help you there as I don't have your composer.json to see which package it is.

But anyway, this is nothing that can be fixed on composer's side (composer made exactly what it should: failing because the packages are saying they don't support PHP 7.2 while you run on 7.2)

**Comment by julienfalque** [comment]
Regarding PHP CS Fixer, you will need to upgrade at least to version 2.2 which supports PHP 7.2. Version 2.1.x isn't maintained anymore.

**Comment by sinnis-dev-trey** [comment]
@stof hey thank you! Will post the issue there :)

and the composer.json is generated - using default Magento 2 Framework (would the specific version help). 

@julienfalque thank you, will get onto that :)

**Comment by stof** [comment]
well, report it to the Magento 2 team then.

**Comment by sinnis-dev-trey** [comment]
@stof yeah thinking about it - I should have reported it there and not here, sorta jumped the gun on it haha will close

Thanks for help :)
