### ISSUE TITLE
I can't clear cache

### ISSUE THREAD

**Issue by Neneone** [composer/composer#7180]
When I run
`composer clearcache`
it says "Cache cleared", but if I use `composer update` it clones all of my packages from the cache... How can I clear the cache?

**Comment by staabm** [comment]
Maybe you need sudo in case you messed up filepermissions

**Comment by curry684** [comment]
What is the output of `ls -al ~/.composer/cache`?

If it is messed up, you should rebuild instead of continuing to use elevation:
```
sudo rm -rf ~/.composer/cache
composer update
```

**Comment by Sarke** [comment]
Are you using https://github.com/hirak/prestissimo by any chance?

It will pre-download them into the cache when you run composer, so it will always say "from cache".

**Comment by alcohol** [comment]
It would also help if you included more output from a verbose command invocation (add `-vv` at the very least).

**Comment by adrian-enspired** [comment]
Any answer here? I seem to be running into a similar issue:
```bash
$ rm -rf vendor/
$ composer clearcache
Clearing cache (cache-vcs-dir): /---/.cache/composer/vcs
Clearing cache (cache-repo-dir): /---/.cache/composer/repo
Clearing cache (cache-files-dir): /---/.cache/composer/files
Clearing cache (cache-dir): /---/.cache/composer
All caches cleared.
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 43 installs, 0 updates, 0 removals
  - Installing guzzlehttp/promises (v1.3.1): Downloading (100%)         
  - Installing psr/http-message (1.0.1): Downloading (100%)         
  - Installing guzzlehttp/psr7 (1.4.2): Downloading (100%)         
  - Installing php-enspired/exceptable (v1.2.1): Downloading (100%)         
  - Installing guzzlehttp/guzzle (6.3.3): Downloading (100%)         
  - Installing nexcess/nexcess-php-sdk (dev-master 8c9186c): Cloning 8c9186c6c9 from cache
-------------------------------------------------------------^
```
Also note this is not the correct (current) commit hash.
