### ISSUE TITLE
composer update --unsatisfied

### ISSUE THREAD

**Issue by axel-rutz** [composer/composer#7182]
How to reproduce:
* Install a current drupal-composer/drupal-template project on a php-7.1 host
* Realize that you need compatibility with a php-7.0 host
* On the 7.0 machine, any composer command will give us something like `doctrine/common v2.8.1 requires php ~7.1 -> your PHP version (7.0.25) does not satisfy that requirement.`
* OK, so to downgrade that, doing `composer update doctrine/common`
* Then we have the same problem for doctrine/cache
* After some iterations we happily solved the problem via `composer update doctrine/common doctrine/annotations doctrine/cache doctrine/collections symfony/cache`

OK, so
* Is there some easier way to do this that i missed in my mere mortal understanding?
* If not, can we get one? Something like `composer update --unsatisfied`?

(Even if - of course - that strategy is not guaaranteed to work out, this is valuable if it does.)

**Comment by alcohol** [comment]
Why not just run `composer update` ?

**Comment by axel-rutz** [comment]
Good question, simple answer:
As `composer update`  updates each and every package. Often this is increases the risk to break the site, or even is known to (as in our case).

**Comment by alcohol** [comment]
Then you probably don't run update often enough.

**Comment by axel-rutz** [comment]
I do not see what your last statement might mean.
???

**Comment by alcohol** [comment]
> Often this is increases the risk to break the site, or even is known to (as in our case).

If you update frequently, you run less behind and there are less changes that you have to take into account that might break your application. Also, if you know that certain library updates might break your application, you can add an upper constraint until you have the time to make the necessary adjustments to accommodate for the update, e.g.: `"foo/bar": "^1.3 <1.5"`.

**Comment by Seldaek** [comment]
The best way would be to define a platform config https://getcomposer.org/doc/06-config.md#platform indicating you are using php 7.0, then you can run a `composer update --dry-run` to see what would be downgraded and only update those packages if you don't want to do the full update.
