### ISSUE TITLE
Composer updates but returns old version

### ISSUE THREAD

**Issue by Boojs** [composer/composer#7189]
Hi there, relatively new to composer so I may be missing something completely in front of my eyes. I am trying to update composer with self-update and it works fine, but the returned version seems to stay the same. Not sure whats going on?

Output of `composer diagnose`:

```
$ composer diagnose
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: Warning: Accessing packagist.org over http which is an insecure protocol.
OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking composer version: FAIL
You are not running the latest stable version, run `composer self-update` to update (1.1.2 => 1.6.3)
```

When I run this command:

`$ composer -v`

I get the following output: 

`Composer version 1.1.2 2016-05-31 19:48:11`

When I run this command to update:

```
composer selfupdate
Updating to version 1.6.3 (stable channel).
    Downloading: 100%
Use composer self-update --rollback to return to version 1.1.2

```
And check again for version

```
composer -v
Composer version 1.1.2 2016-05-31 19:48:11
```

And I expected this to happen:

```
composer -v
Composer version 1.6.3 2016-05-31 19:48:11
```

**Comment by hectorprats** [comment]
check where is your composer file and replace it with one that you download from getcomposer.org

**Comment by Boojs** [comment]
hey @hectorprats 

I used ansible to download and install composer, I download the `composer.phar` and overwrite it into my path. I've tried both methods and they seem to still be conflicting.

**Comment by alcohol** [comment]
We do not support ansible as an installation method. Since we do not know what it does, we cannot really assist in resolving this issue.

It could be it creates a shell alias, shortcut, or wrapper even. Unfortunately, you will have to debug this for yourself :-)
