### ISSUE TITLE
Composer 2 problems.

### ISSUE THREAD

**Issue by SIbava** [composer/composer#7190]
Problem 1
    - This package requires php >=7.0.0 but your PHP version (5.6.31) does not satisfy that requirement.
  Problem 2
    - Installation request for hxphp/framework dev-master -> satisfiable by hxphp/framework[dev-master].
    - hxphp/framework dev-master requires php >=7.0.0 -> your PHP version (5.6.31) does not satisfy that requirement.

Please help

**Comment by hectorprats** [comment]
Please, check the composer docs. This is not an issue of composer.

Your package need PHP 7.0, upload your local PHP version

**Comment by iGavrilo** [comment]
Actually Im really not sure if you cant read or what is your problem. Notice is clearly or you need some tutorial in notice ?

**Comment by SIbava** [comment]
hi!

help me please!
i have this error

*Fatal error*: Uncaught Exception: Erro fatal: A view
<'C:\wamp64\www\sistema\app\views\error404\index.phtml'> não foi
encontrada. Por favor, crie a view e tente novamente. in
C:\wamp64\www\sistema\vendor\hxphp\framework\src\HXPHP\System\View\Core.php:303
Stack trace: #0
C:\wamp64\www\sistema\vendor\hxphp\framework\src\HXPHP\System\App.php(120):
HXPHP\System\View\Core->flush() #1 C:\wamp64\www\sistema\index.php(40):
HXPHP\System\App->run() #2 {main} thrown in
*C:\wamp64\www\sistema\vendor\hxphp\framework\src\HXPHP\System\View\Core.php*
 on line *303*

2018-03-16 3:28 GMT-07:00 Rob <notifications@github.com>:
