### ISSUE TITLE
Working on local dependant repositories

### ISSUE THREAD

**Issue by Sarke** [composer/composer#7192]
This is a follow-up to #6790.

The problem is that I am working locally on both the main package and it's dependant packages.  I'll have the main package running, and will need to make a change to one of the dependencies (which are also developed locally).

As I see it, there are several ways to work around this problem, but none ideal:

---

**1. "Normal"**

Make a change in the dependency, git commit, git push, composer update.

pros: keeps a valid composer.lock, works when deploying.

cons: Very tedious. Too many small commits.

**2. Override local global repo config**

https://github.com/composer/composer/issues/6790#issuecomment-342739823

Make a change in the dependency, which is symlinked to vendor/package.

pros: quick local development.

cons: composer.lock only valid on local machine, not good when deploying.

**3. Symlink**

https://www.adampatterson.ca/2017/using-private-composer-packages-with-laravel/

Make a change in the dependency, which is symlinked to vendor/package.  Almost the same as number 2, but Composer doesn't know it's a symlink.

pros: quick local development, valid composer.lock.

cons: Risk of overwriting local repo by Composer action.

**4. Separate composer.json for local development**

https://stackoverflow.com/a/48987303/1448147

pros: quick local development.

cons: composer.lock only valid on local machine, not good when deploying.

---

These solutions all assume that composer.lock is part of the commit and version control, which seems to be the accepted way of doing it.

I have been using solution 2 as recommended by @alcohol but it is now causing issues when deploying.  A work-around could be to delete the composer.lock file on deployment, and do a new `composer install` in the deploy script, but this seems to counter the above.

Number 3 seems almost ideal, except I am worried that Composer has access to the local repository and can delete it thinking it's just a copy inside the vendor folder.

Any thoughts on this?  I feel like I can't be the only one with this problem, but I'm having a hard time finding a good solution.

**Comment by alcohol** [comment]
## Suggestion 1:

You could keep two `composer.json` files locally. Once which uses the custom path repositories, and one which does not. During development, call `composer` with:

```
COMPOSER=composer.local.json composer <command+args>
```

Then when you are ready to head to production, tag your dependencies, and use your regular `composer.json` to update to the latest versions, creating a clean lock file and pushing all of that.

## Suggestion 2:

If you have a CI/CD intermediate step, have that performs a `composer update` rather than install. If your CI/CD does not have the custom path repositories, it should generate a clean `composer.lock` file for your build artifact.

Downside here being of course, that you cannot guarantee you will end up with the same versions as in development.

---

I could probably think of a few more alternatives, but to be honest, there is no one perfect silver bullet for your use-case.

**Comment by Sarke** [comment]
Your suggestion 1 is my option 4.  Doesn't really work well with CI/CD.

Your suggestion 2 is not in my list, but it doesn't go against the idea of keeping the composer.lock file?

> but to be honest, there is no one perfect silver bullet for your use-case.

This is what I don't get.  This scenario can't be that uncommon, can it?  What do other people do?

**Comment by alcohol** [comment]
It actually is quite uncommon. Almost all of our users fall into the following two categories:

- User develops a project, that might have some third party dependencies that they need to manage.
- User develops a library, that might have some third party dependencies that they need to manage.

You are working on several packages at the same time though, that also depend on each other (either unidirectional, or bidirectional, doesn't really matter). This is honestly a 1% scenario. And while we support it to some extend in several ways, not a single one way is the preferred/recommended/best way. It really depends on what you prefer, are more comfortable with, or simply can manage to "make it work".

**Comment by joelwurtz** [comment]
Personally, after many years working on separate repositories, i ended merging everything under one repository and use subtree spliting, this is by far the best solution actually for those scenarios.

And you can use this wonderful free service proposed by Tobias Nyholm https://www.subtreesplit.com/

**Comment by alcohol** [comment]
Basically what symfony does too, I think.

**Comment by Seldaek** [comment]
You could do step 2 but in your CI before deployment/packaging you could run `composer update your/package your/other-package` so you only update those back to a good version and get a working lock file again, but without updating third party dependencies to their latest version which might result in bad surprises as you deploy.

I don't think we can offer a better solution right now at least so closing.
