### ISSUE TITLE
isabled in the server configuration by allow_url_fopen=0

### ISSUE THREAD

**Issue by EngHaithamGhanem** [composer/composer#7195]
![error](https://user-images.githubusercontent.com/32108387/37558473-d09b9970-2a25-11e8-9bd0-adf5636bfa68.PNG)

**Comment by EngHaithamGhanem** [comment]
Where @alcohol

**Comment by alcohol** [comment]
`php.ini`

**Comment by EngHaithamGhanem** [comment]
thank you @alcohol  iam update in php.ini but not active in program !

**Comment by curry684** [comment]
When running PHP as FPM, restart the FPM daemon. If running as an Apache module, restart Apache. Reloading the process ensures configuration is reloaded.

**Comment by EngHaithamGhanem** [comment]
Thanks for the help @curry684 , I will do this
