### ISSUE TITLE
composer access denied - cannot intall github

### ISSUE THREAD

**Issue by dorian90** [composer/composer#7204]
My `composer.json`:

```json
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.0.2",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "require": {
        "magento/product-community-edition": "2.0.2",
        "composer/composer": "@alpha",
        "quickpay/magento2": "^1.1",
        "mageplaza/magento-2-danish-language-pack": "dev-master"
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.2.2",
        "sjparkinson/static-review": "~4.1",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3 <=0.7.0"
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": "app/code/"
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "alpha",
    "prefer-stable": true,
    "extra": {
        "magento-force": "override"
    }
}

```

Output of `composer diagnose`:

```
...replace me...
```

When I run this command:
[xntrkzla@server12 ~]$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
Package sjparkinson/static-review is abandoned, you should avoid using it. Use phpro/grumphp instead.
Generating autoload files

                                                                                   
  [ErrorException]                                                                 
  file_put_contents(/home/xntrkzla/app/etc/vendor_path.php): failed to open strea  
  m: No such file or directory                                                     
                                                                                   

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

[xntrkzla@server12 ~]$ "autoload": {
-bash: autoload:: command not found
[xntrkzla@server12 ~]$      "psr-4": {
-bash: psr-4:: command not found
[xntrkzla@server12 ~]$      "Magento\\Framework\\": "htdocs/lib/internal/Magento/Framework/",
-bash: Magento\Framework\:: command not found
[xntrkzla@server12 ~]$      "Magento\\Setup\\": "htdocs/setup/src/Magento/Setup/"
-bash: Magento\Setup\:: command not found
[xntrkzla@server12 ~]$     }
-bash: syntax error near unexpected token `}'
[xntrkzla@server12 ~]$ composer self-update
Updating to version 1.6.3 (stable channel).
   Downloading (100%)         

                                                                                   
  [ErrorException]                                                                 
  rename(/opt/cpanel/composer/bin/composer): failed to open stream: Permission de  
  nied                                                                             
                                                                                   

self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--set-channel-only] [--] [<version>]
```
...replace me...
```

And I expected this to happen:
to install

**Comment by alcohol** [comment]
All of the above issues are quite easily identified and fixed (permission issues). Unless you're on a shared host. In that case, good luck. None of these however, are actual Composer issues.
