### ISSUE TITLE
The --no-check-* flags actually do check, just convert errors to warnings

### ISSUE THREAD

**Issue by tomasfejfar** [composer/composer#7207]
**When I run this command:**

```
composer validate --no-check-publish --no-check-all --strict; echo $?
```
On a repository, that has empty description and name

**I get the following output:**

```
./composer.json is valid for simple usage with composer but has
strict errors that make it unable to be published as a package:
See https://getcomposer.org/doc/04-schema.md for details on the schema
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
name : The property name is required
description : The property description is required
1
```

**And I expected this to happen:**
Return 0, because "publish" is not checked, "all" is not checked and lockfile is fine. 
The suppressed checks should not run at all.

**Comment by alcohol** [comment]
Maybe the documentation should be adjusted.

`--check-all` trumps all other options. So it will check everything.

Since you are checking everything, `--no-check-publish` simply means that any issues found related to publishing downgrade from errors into warnings.

And since you specified `--strict`, it will output `1` because there were warnings.

**Comment by alcohol** [comment]
Misread the first time. But, still the following applies (and actually is documented):

`--no-check-publish` merely means it does not emit an error, but a warning instead. And since you specified `--strict`, warnings result in a failure too.

**Comment by tomasfejfar** [comment]
I know it's documented and expected. I argue that is wrong. 

How can one set it up so that it does

**Comment by tomasfejfar** [comment]
How can one set it up so, that it does fail on any error or warning, except anything publish-related?

That is currently impossible due to the behaviour of the flag imho.

**Comment by alcohol** [comment]
Correct, and this specific behaviour is simply not supported. If you could clarify why you need this specific combination, and cannot for example achieve the same result without using `--strict`, perhaps we can better understand what you are trying to accomplish.

**Comment by alcohol** [comment]
You could just check if the exit code equals 2 in that case. It will be 1 if there are warnings, but it will be 2 if there are errors.

**Comment by alcohol** [comment]
I realize the above is not actually documented, so I cannot fault you for not knowing this. But I do believe this would serve your use-case?
