### ISSUE TITLE
composer show options --tree and --path do not work together

### ISSUE THREAD

**Issue by kenorb** [composer/composer#7209]
When I run this command:

```
composer global show -t -P
```

I get the following output:

```
$ composer global show -t -P
drupal/coder 8.2.12 Coder is a library to review Drupal code.
├──ext-mbstring *
├──php >=5.4.0
├──squizlabs/php_codesniffer >=2.8.1 <3.0
│  ├──ext-simplexml *
│  ├──ext-tokenizer *
│  ├──ext-xmlwriter *
│  └──php >=5.1.2
└──symfony/yaml >=2.0.0
   └──php ^5.5.9|>=7.0.8
...
```

And I expected this to happen: the extra paths are shown similar when running as `composer global show -P`.

I expect that the path is shown at the end or in the bracket, like:

`├──squizlabs/php_codesniffer >=2.8.1 <3.0 (~/.composer/vendor/squizlabs/php_codesniffer)
`
If these arguments aren't compatible together, maybe there should be some warning.

Composer version 1.6.3 2018-01-31 16:28:17

**Comment by dmanners** [comment]
I would be happy to take this on. I have found the place to do this for the package items but not their requires.

The packages are of type `Composer\Package\CompletePackage` which allows you to find the path in the same way as the `--path` flag does it.

The requires are of type `Composer\Package\Link` which only has some basic package information.

If we want the requires to have path information shown then we would have to update the link type to include type and target directory. I would be happy to do this but want to check before I start adding extra items to object, if we should do this and if this approach is actually the best way.

Other option would be to add a warning or documentation to these flags.

**Comment by Seldaek** [comment]
I think a warning would be acceptable tbh.. I don't see a ton of value to littering the tree view with path information. If you want the path of something you can get that already, if you want to see the tree you can too.
