### ISSUE TITLE
Dependency conclusion, but works when changing the order

### ISSUE THREAD

**Issue by kenorb** [composer/composer#7215]
The following bug report relates to the following post:

- [Why composer says “Conclusion: don't install” when (seemingly) no obstacles are present?](https://stackoverflow.com/q/45009772/55075)

The `composer.json` with **non-working** order:

```json
{
    "minimum-stability": "dev",
    "require": {
        "jasny/bootstrap": ">=3.1.3",
        "2amigos/yii2-file-input-widget": "*"
    }
}
```

The `composer.json` with **working** order:

```json
{
    "minimum-stability": "dev",
    "require": {
        "2amigos/yii2-file-input-widget": "*",
        "jasny/bootstrap": ">=3.1.3"
    }
}
```

The above files are exactly the same, but the order is different. One works, one doesn't.

When I run `composer install` (on empty folder) with the wrong order, I get the following output:

```
$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - 2amigos/yii2-file-input-widget 0.1.2 requires jasny/bootstrap v3.1.0 -> satisfiable by jasny/bootstrap[v3.1.0] but these conflict with your requirements or minimum-stability.
    - 2amigos/yii2-file-input-widget 0.1.1 requires jasny/bootstrap v3.1.0 -> satisfiable by jasny/bootstrap[v3.1.0] but these conflict with your requirements or minimum-stability.
    - 2amigos/yii2-file-input-widget 0.1.0 requires jasny/bootstrap v3.1.0 -> satisfiable by jasny/bootstrap[v3.1.0] but these conflict with your requirements or minimum-stability.
    - 2amigos/yii2-file-input-widget 1.0.0 requires jasny/bootstrap ~3.1.0 -> satisfiable by jasny/bootstrap[v3.1.3].
    - 2amigos/yii2-file-input-widget 1.0.1 requires jasny/bootstrap ~3.1.0 -> satisfiable by jasny/bootstrap[v3.1.3].
    - 2amigos/yii2-file-input-widget 1.0.2 requires jasny/bootstrap ~3.1.0 -> satisfiable by jasny/bootstrap[v3.1.3].
    - 2amigos/yii2-file-input-widget dev-master requires jasny/bootstrap ~3.1.0 -> satisfiable by jasny/bootstrap[v3.1.3].
    - 2amigos/yii2-file-input-widget 1.0.x-dev requires jasny/bootstrap ~3.1.0 -> satisfiable by jasny/bootstrap[v3.1.3].
    - Conclusion: don't install jasny/bootstrap v3.1.3
    - Installation request for 2amigos/yii2-file-input-widget * -> satisfiable by 2amigos/yii2-file-input-widget[0.1.0, 0.1.1, 0.1.2, 1.0.0, 1.0.1, 1.0.2, dev-master, 1.0.x-dev].
```

It works when I change the order in `require` section (on empty folder).

And I expected this to happen: It should work the same way despite the different order.

Composer version 1.6.3 2018-01-31 16:28:17 on macOS High Sierra

Related issues: GH-5780

**Comment by frederikbosch** [comment]
I also still have the related issue #5780. Another thing I recognized is different behaviour in install and update, which is also logical because they are different things. However, if install fails, and I remove one of the or reorder dependencies as such that install succeeds, then directly after installing running update with all dependencies in same order, does succeed. That does seems strange to me.

**Comment by mwgamble** [comment]
Have you tried using the `why` and `why-not` commands?

**Comment by alcohol** [comment]
Huh, interesting issue. I can reproduce this consistently. I might take a look at this today if I have the time.

**Comment by alcohol** [comment]
@mwgamble those commands do not work if you cannot actually install anything at all from scratch.

**Comment by alcohol** [comment]
It definitely seems related to the minimum stability of dev in this case. @frederikbosch was this also the case in your scenario? Since you had a lot of private packages, you never shared a reproducible scenario so I am missing a lot of information in your related issue.

**Comment by frederikbosch** [comment]
@alcohol nope, all stable packages

**Comment by alcohol** [comment]
Oh ☹️

**Comment by YetiCGN** [comment]
Same problem appeared a few days ago with Symfony 3.4 and Sulu 1.6. Sulu 1.6.22 came out and declared a conflict with Symfony 3.4.16 and 3.4.17.

If you have the order

        "sulu/sulu": "~1.6.0",
        "symfony/symfony": "^3.4",

everything works fine as sulu/sulu 1.6.22 and symfony/symfony 3.4.15 are chosen. But change the order to

        "symfony/symfony": "^3.4",
        "sulu/sulu": "~1.6.0",

and you get 

    - Updating symfony/symfony (v3.4.14 => v3.4.17): Loading from cache
    - Downgrading sulu/sulu (1.6.22 => 1.6.21): Loading from cache

**Comment by frederikbosch** [comment]
Not possible for me to verify this at the moment since I don't have a repo with the problem now, but thanks a lot for your work!

**Comment by naderman** [comment]
I'll assume this is fixed then, please open a new issue if you run into something like this again.
