### ISSUE TITLE
Make composer ignore changes in a particular vendor subdir

### ISSUE THREAD

**Issue by uuf6429** [composer/composer#7216]
## Use Case

I'm working on a composer package for interacting with some SOAP API.

Since it's SOAP, one can generate PHP classes out of the API WSDL. By default, I'll be distributing version X of this API (as such classes), in a particular sub-directory of the package.

I'd like to provide a way for the package user to use a different version of the API, possibly even located somewhere else entirely (ie, WSDL sources is on a different host).

## Solved Problems
- to keep everything clean and working, the generated classes should always have the same namespace and end up in the same directory
- ideally, these classes should be generated very early, so that things like composer autoload dumping can be used

## Solutions
- implement a *Composer Plugin* that checks _"extra"_ for custom WSDL URLs and triggers code generation

## Unsolved Problems
- ~if the _"extra"_ element is **removed** and `composer update` is run, I need to find a way to roll back generated changes. The particular difficulty here is that the default WSDL URLs are not publicly accessible. _Maybe this can be solved by somehow telling Composer that this package needs to be redownloaded/updated?_~ I'll simply distribute the WSDL as I'm already doing and then just generate classes out of it.
- Composer will eventually complain that some files have changed in the sub-dir (because they were generated). _Maybe I can solve this by my installer/plugin changing Composer behaviour?_

**Comment by mwgamble** [comment]
Why not make it so the generated files are situated outside of the vendor directory by making the path where the generated files should be stored configurable?

**Comment by alcohol** [comment]
I agree with @mwgamble. Look at how Symfony manages all its compiled classes and such in the cache directory. A similar approach should be used. This is not a Composer topic/issue.

**Comment by uuf6429** [comment]
I'm not against this idea, but:
1. Symfony is a framework and can impose requirements such as a cache dir outside of composer
2. To be clear, are we talking about Symfony's container compiler/cache mechanism?
3. I need to provide a sensible default, so people won't need to mess around with this unless they really want to
4. Adding to point 3, the premise of a cache is that the application can function without it and since the package is only aware of Composer, it does make it a bit of a Composer topic
5. With this approach it means I should be modifying the autoloader to somehow know the correct class path

**Comment by alcohol** [comment]
And with regards to `5`, if the user always instantiates your generator/loader with the proper configuration, then you can easily detect/track whether or not you already generated the code (or if it needs to be regenerated perhaps?). And from that point you can append it to the autoloading mechanism just as easily.

**Comment by uuf6429** [comment]
Hi, I've almost got this working.

> And from that point you can append it to the autoloading mechanism just as easily.

I couldn't figure that part out. The composer plugin has access to `$composer->getAutoloadGenerator()`, however that object doesn't seem to have functionality for adding to or modifying the generated autoloader. I can overwrite it with my own (perhaps wrapped) autoload manager, but it seems too hacky.

**Comment by curry684** [comment]
I think you're missing a vital piece of knowledge: [PHP's autoloading mechanisms will happily accept as many autoloaders as your code needs](http://php.net/manual/en/function.spl-autoload-register.php). For example [Doctrine Annotations](http://docs.doctrine-project.org/projects/doctrine-common/en/latest/reference/annotations.html#registering-annotations) can also use their own autoloader, happily co-existing with Composer's.

Also, if you really want to integrate, you can actually just extend on Composer's autoloader:
```php
$autoloader = require(__DIR__ . '/vendor/autoload.php');
MyWSDLParser::configure('/tmp/generatedClasses', $autoloader);
```
I would however definitely recommend bringing your own:
```php
require(__DIR__ . '/vendor/autoload.php');

// Set base path for WSDL-generated files and register its autoloader
MyWSDLParser::register('/tmp/generatedClass');
```

**Comment by uuf6429** [comment]
I'm aware of the fact that you can extend autoloading, however that solution seems to be suitable for the end user - something I would like to avoid.

Imagine if everyone went with this approach, you'd have a growing list of require's in your bootstrap script for all the generated code, even if this information is actually already known.

The original idea was that a composer plugin would be used to generate the classes and then add a new entry to the autoloader to be generated (or appended to the file).

Here's a few solutions I can see:
1. Tell the user to: require the composer package, configure it and add an additional `require()` in their bootstrap file
  - con: too much work for the user, does not sound like the composer way of adding packages
  - pro: very easy to do, pushes all responsibility to the user
2. The composer plugin appends some code to `autoload.php` (taking care not to append multiple times)
  - con: messing with composer-generated files might produce unintended and unpredictable side-effects
  - pro: completely automated, high-performance
3. A [file](https://getcomposer.org/doc/04-schema.md#files) autoload entry in my composer package that figures out the generated classes path and loads the autoloader from there
  - con: slows down application startup since it needs to parse composer.json to figure out location of generated files, will break down if `composer.json` is missing
  - pro: completely automated
4. Add a `require_once()` to all library classes that use generated classes (similar to 3, but user is not allowed to use generated classes directly)
  - con: very small performance hit the first time such a class is loaded, will break down if `composer.json` is missing
  - pro: completely automated, slightly better performance than 3.
5. Figure out a way to dynamically add an entry to the autoload generator (my original approach above)
  - con: none
  - pro: completely automated, transparent and high-performance

**Comment by uuf6429** [comment]
I went with 5 using the following composer plugin code:
```php
        $gen = new SoapGen($wsdlSources, $wsdlClassPath, $logger);
        $gen->generate();

        $autoloadFile = $wsdlClassPath . '/autoload.php';
        if (!file_exists($autoloadFile)) {
            throw new \RuntimeException("WSDL autoloader does not exist in $autoloadFile");
        }

        $autoload = $composer->getPackage()->getAutoload();
        $autoload['files'][] = $autoloadFile;
        $composer->getPackage()->setAutoload($autoload);
```
