### ISSUE TITLE
Relocate warnings in "outdated" or add option to hide them

### ISSUE THREAD

**Issue by mbrodala** [composer/composer#7218]
My `composer.json`:

```json
{
    "require": {
        "react/socket-client": "^0.7.0"
    }
}
```

When I run this command:

```
composer outdated
```

I get the following output:

```
evenement/evenement v2.1.0  v3.0.1  Événement is a very simple event dispatching library for PHP
react/socket-client v0.7.0  v0.7.0  Async, streaming plaintext TCP/IP and secure TLS based connections for ReactPHP
Package react/socket-client is abandoned, you should avoid using it. Use react/socket instead.
react/stream        v0.6.0  v0.7.7  Event-driven readable and writable streams for non-blocking I/O in ReactPHP
```

And I expected this to happen:

```
evenement/evenement v2.1.0  v3.0.1  Événement is a very simple event dispatching library for PHP
react/socket-client v0.7.0  v0.7.0  Async, streaming plaintext TCP/IP and secure TLS based connections for ReactPHP (Package is abandoned, you should avoid using it. Use react/socket instead.)
react/stream        v0.6.0  v0.7.7  Event-driven readable and writable streams for non-blocking I/O in ReactPHP
```

The _Package ... is abandoned ..._ warning currently is outputted right after the package in question but unfortunately on a separate line. This makes it harder to process the output of the `outdated` command. I am aware that JSON output is supported but processing JSON is not possible in every environment, e.g. native shell.

Thus I'd like to request to move this warning after the package description. Alternatively an option/environment variable to hide this message would help.

**Comment by Seldaek** [comment]
`composer outdated 2>/dev/null` is now working fine to eliminate those. They should not have been output on stdout sorry about that.

**Comment by mbrodala** [comment]
Thanks, that should be enough. :-)
