### ISSUE TITLE
SSL Failed to enable crypto

### ISSUE THREAD

**Issue by matthewattanasio** [composer/composer#7221]
Everytime I use `composer install` now I am getting the following error for all packages. Does this have something to do with https://blog.github.com/2018-02-23-weak-cryptographic-standards-removed/ ?

```
SSL operation failed with code 1. OpenSSL Error messages:
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Failed to enable crypto
failed to open stream: operation failed
```

I am Using 
OSX El Capitan
Composer 1.6.3

**Comment by stof** [comment]
it may totally be related to this removal, yes. Check your openssl version, and try to upgrade it in case it is a version not supporting TLS 1.2. There is nothing Composer can do there, as it is not implementing the TLS encryption itself (this is done at the PHP layer using the Openssl extension)

**Comment by matthewattanasio** [comment]
Thanks Stof

**Comment by Bazooki** [comment]
No solution on how to fix it!?
