### ISSUE TITLE
Error installing composer

### ISSUE THREAD

**Issue by chaaza** [composer/composer#7222]
This is the output when I try to isntall composer:

![capture](https://user-images.githubusercontent.com/36837603/38016723-796ec106-32a2-11e8-8949-3cc4211127c5.PNG)

The "https://getcomposer.org/versions" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.
failed to open stream: php_network_getaddresses: getaddrinfo failed: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.

**Comment by masiorama** [comment]
Same problem here.

` [Composer\Downloader\TransportException]
  The "https://packagist.org/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo faile
  d: Name or service not known
  failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known`

**Comment by chaaza** [comment]
Oh I forgot to close this. I solved this issue. Its actually because of my internet connection. My internet is not connected at the time I want to install it.
