### ISSUE TITLE
[Feature request] Allow abandoning of package versions

### ISSUE THREAD

**Issue by aidantwoods** [composer/composer#7223]
Composer already has support for `"abandoned": true` (see: https://github.com/composer/composer/issues/4610), however this may confuse users into thinking the entire package has been abandoned if committed to a single version (see: https://github.com/composer/composer/issues/4610#issuecomment-376789273).

It was suggested in #4610 that users should run `composer outdate`, however:

IMO it would be nice to have composer support abandonment via a version constraint too (and perhaps have adjusted wording) :) The abandon feature exists so package authors can be responsible and give users a heads up when development ceases, I think we should be able to do the same thing for versions that have the same fate.

I don't think that `composer outdated` does this job because:
1. It requires users to proactively check (abandon gives them notice)
2. Existence of new major versions doesn't mean the one you're using isn't supported. While it might be a good idea to update if a new major version exists, it additionally becomes dangerous not to if the one you're using is no longer supported

**Comment by Seldaek** [comment]
Closing as I don't think we will ever do anything here. IMO this is something which can be communicated via other means, and doesn't apply to enough projects (most hardly have enough resources to maintain their main branch, let alone maintain older major releases) to really be worth the trouble.
