### ISSUE TITLE
Installing composer : do you firewall on the IP 54.x.x.x range ?

### ISSUE THREAD

**Issue by tostaky** [composer/composer#7226]
Hello,
i installed composer several times on diverse host, but today i have an unusual error.
failed to open stream: No route to host in Command line code on line 1 (tried both resolved name and IP).

The installer works on my hosts, except for one, whose IP is on the same range (54.x.x.x) as the getcomposer.org server. Do you firewall on this range by any chance?
Tnx
JP

**Comment by curry684** [comment]
That error indicates a routing issue on your end, not a firewall at the other end. Check the output of the route command without parameters. 

You would get this error if you misconfigured your gateway subnet.
