### ISSUE TITLE
prohibits does not detect conflicts in replaced packages

### ISSUE THREAD

**Issue by deviantintegral** [composer/composer#7230]
When a package replaces another package, and there is a conflict caused by the replaced package, `composer prohibits` shows that no conflicts exist.

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 1.6.3
PHP version: 7.2.3
PHP binary path: /usr/local/Cellar/php/7.2.3_2/bin/php
```

```
$ git clone --depth 1 --branch 8.5.x https://git.drupal.org/project/drupal.git
$ composer install
$ composer require --no-update doctrine/annotations:^1.3
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package doctrine/annotations 1.2.* is satisfiable by doctrine/annotations[v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.5, v1.2.6, v1.2.7] but these conflict with your requirements or minimum-stability.

$ composer -t why-not doctrine/annotations ^1.3
There is no installed package depending on "doctrine/annotations" in versions not matching ^1.3

$ composer -t why doctrine/annotations ^1.3
doctrine/annotations v1.2.7 Docblock Annotations Parser
├──doctrine/common v2.6.2 (requires doctrine/annotations 1.*)
│  └──drupal/drupal 8.5.x-dev (requires doctrine/common ^2.5)
│     └──drupal/drupal 8.5.x-dev (replaces drupal/core ^8.5)
└──drupal/drupal 8.5.x-dev (requires doctrine/annotations ^1.3)
```

Drupal's [`core/composer.json` requires `"doctrine/annotations": "^1.2"`](https://cgit.drupalcode.org/drupal/tree/core/composer.json?h=8.5.x#n36) and replaces `"drupal/core-annotation": "self.version",`. However, the [`drupal/core-annotation` requirement is `1.2.*`](https://cgit.drupalcode.org/drupal/tree/core/lib/Drupal/Component/Annotation/composer.json?h=8.5.x#n10), which is what triggers the composer update error.

What I'm not sure is:

1. Is this expected behaviour when replacing a package, and their version constraints do not match? If so, then I think this is a bug to be fixed in Drupal.
1. Should composer highlight the package replacement in it's commands? It's rather confusing that a composer.json is used from a package that never shows up in `composer show` or the depends / prohibits commands.

**Comment by Seldaek** [comment]
Might be fixed by https://github.com/composer/composer/issues/7234#issuecomment-691164177 - otherwise it's just too complex IMO
