### ISSUE TITLE
The network titles are not changing while importing and exporting

### ISSUE THREAD

**Issue by susmitasomanchi** [composer/composer#7232]
In the Starter plan 
Create a network.
Go to Write Code->Select Develop Code->View Website->Import a different network ,the network name is not changing ,it is remaining the same.Even while exporting it is saving old network name .

![1inital page](https://user-images.githubusercontent.com/9839118/38216709-aeabde9e-3699-11e8-9368-61e6b430d147.png)
![2import vehicle manufactre network](https://user-images.githubusercontent.com/9839118/38216710-aebc8bd6-3699-11e8-973a-d888b2ad67f8.png)
![3import successful](https://user-images.githubusercontent.com/9839118/38216712-aed2e278-3699-11e8-8895-b242c6774baf.png)
![4export](https://user-images.githubusercontent.com/9839118/38216713-aee8f89c-3699-11e8-89f4-1aa65fa71fee.png)

**Comment by xabbuh** [comment]
@susmitasomanchi I think you accidentally chose the wrong repository to report your issue. :)

**Comment by susmitasomanchi** [comment]
Changed to repo 
https://github.ibm.com/Blockchain-WW-Labs/IBM-Composer/issues/81
