### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by yusren** [composer/composer#7236]
Every time I run composer install or composer update, the composer always download same file again and again but with different file name. I've an idea : composer creates hash files for downloaded .json files. When the update or install process (composer install or composer update) is executed, the hash on my computer will be compared to the hash file on the packagist server. If the hash has the same value, then the composer will use my .json file, if different composer will download the new file. It can speed up time. Thanks with Love.

**Comment by stof** [comment]
The hash in the packagist URL is already a hash of the content of the file. So if the file is not changed on the server side, the file name does not change either.
