### ISSUE TITLE
Question: Force composer to fail

### ISSUE THREAD

**Issue by designermonkey** [composer/composer#7237]
This is a question not an issue, sorry if I shouldn't post it here.

I want to make composer fail during tests of an app that uses it and has to report the failure.

Is there a simple known method to make a `composer install` or `composer update` fail with exit codes other that `0`?

**Comment by staabm** [comment]
what are you trying to achieve?

**Comment by stof** [comment]
make it run `update` on an impossible set of requirements:

```json
{
    "require": {
        "monolog/monolog": "1.0.0, != 1.0.0"
    }
}
```

**Comment by designermonkey** [comment]
@staabm I logged a [bug for deployer](https://github.com/deployphp/deployer/issues/1569) the other day that shows up when composer fails. Deployer still completes it's run as successful. I wanted to write tests for this bug that I could use to fix it, but didn't know how to force composer to fail.

@stof That's a great idea. I guess that would only cause a exit code of 2. I wonder if there is a way to cause an exit code of 1?

I will start here though, thanks for the input.

**Comment by staabm** [comment]
couldn't you define `bin/composer` as `exit 1` instead?

**Comment by Seldaek** [comment]
I am not really aware of another way to get a 1. Perhaps defining an inline package with an invalid URL would do the trick? https://getcomposer.org/doc/05-repositories.md#package-2

**Comment by designermonkey** [comment]
Thanks for everyone's feedback.
