### ISSUE TITLE
[semver] semver.mwl.be doesn't interpret the caret (^) operator same way as composer

### ISSUE THREAD

**Issue by phansys** [composer/composer#7238]
Current documentation about [Caret Version Range](https://github.com/composer/composer/blob/master/doc/articles/versions.md#caret-version-range-) states that `^1.2.3` is equivalent to `>=1.2.3 <2.0.0`, but semver.mwl.be interprets `^1.2.3` as `>=1.2.3 <1.3.0`, and `^1.2` as `>=1.2.0 <1.3.0`.

See these examples:
* https://semver.mwl.be/#?package=madewithlove%2Felasticsearcher&version=%5E0.1.1&minimum-stability=stable
**Expected**:
![image](https://user-images.githubusercontent.com/1231441/38330352-bcde6052-3826-11e8-9ee7-e4b17372d926.png)
**Current**:
![image](https://user-images.githubusercontent.com/1231441/38330067-feccfe98-3825-11e8-989b-75f2bdb2ddf3.png)

* https://semver.mwl.be/#?package=madewithlove%2Felasticsearcher&version=%5E0.1&minimum-stability=stable
**Expected**:
![image](https://user-images.githubusercontent.com/1231441/38330260-763cf712-3826-11e8-969b-8673de001d1f.png)
**Current**:
![image](https://user-images.githubusercontent.com/1231441/38330124-26878944-3826-11e8-9d21-f22740a98c66.png)

**Comment by stof** [comment]
semver.mwl.be is not maintained by the composer team. Report this to their maintainers.

**Comment by stof** [comment]
your bug report is wrong. You are reporting about `^1.2.3`, but your tests are using `^0.1.1`.

The tool is perfectly right in this case. A 0.x major version behaves in a special way in semver, as it means that any increment of the next number can be a BC breaking release too (and so `^` rejects them).

See https://semver.mwl.be/#?package=symfony%2Fsymfony&version=%5E3.2.1&minimum-stability=stable for the proof.

**Comment by stof** [comment]
@alcohol this issue should be closed, as there is no issue at all

**Comment by stof** [comment]
and here is a quote from the composer doc (the last sentence in the paragraph you referenced in the original issue):

> For pre-1.0 versions it also acts with safety in mind and treats `^0.3` as `>=0.3.0 <0.4.0`.

**Comment by phansys** [comment]
Sorry for the misunderstanding, I didn't noticed the special behavior for pre-1.0 versions. Thank you.
