### ISSUE TITLE
The `--no-suggest` option is missing in composer 1.6.3

### ISSUE THREAD

**Issue by koktaildotcom** [composer/composer#7239]
When I run this command:

```
composer install --no-suggest
```

I get the following output:

```
  [RuntimeException]                         
  The "--no-suggest" option does not exist.
```

And I expected this to happen:
An install without suggestions

relates to: https://github.com/composer/composer/issues/2066

**Comment by xabbuh** [comment]
Are you sure you are using Composer 1.6.3? I cannot confirm your issue with that version. What is the output of `composer --version`?

**Comment by koktaildotcom** [comment]
You are right. The version is the local installed version and is `1.0.0-beta2`.

**Comment by koktaildotcom** [comment]
@xabbuh should the option "--no-suggest" avaiable in version `1.0.0-beta2`?

**Comment by xabbuh** [comment]
@koktaildotcom I don't think so. This option was introduced in #5392 which was first part of the 1.2 release.
