### ISSUE TITLE
Hang on Resolving dependencies through SAT for over 22h

### ISSUE THREAD

**Issue by kenorb** [composer/composer#7240]
My `composer.json`:

```json
{
  "require": {
    "behat/behat":                     "^2@stable",
    "dealerdirect/phpcodesniffer-composer-installer": "^0.4.4",
    "drupal/coder":                    "^8@stable",
    "drush/drush":                     "^8@stable",
    "jakub-onderka/php-parallel-lint": "^1@stable",
    "pdepend/pdepend":                 "^2@stable",
    "pheromone/phpcs-security-audit":  "^1@stable",
    "phploc/phploc":                   "^4@stable",
    "phpmd/phpmd":                     "^2@stable",
    "phpunit/phpcov":                  "^4@stable",
    "phpunit/phpunit":                 "^6@stable",
    "phpunit/phpunit-selenium":        "^1@stable",
    "sebastian/phpcpd":                "^3@stable",
    "squizlabs/php_codesniffer":       "^2@stable"
  },
  "minimum-stability": "dev"
}
```

Output of `composer diagnose`:

```
OK
Checking composer version: OK
Composer version: 1.6.3
PHP version: 7.1.14
PHP binary path: /usr/local/Cellar/php71/7.1.14_25/bin/php
```

When I run this command:

```
time composer -vvv install 
```

I get the following output:

```
Loading config file ./composer.json
...
Resolving dependencies through SAT
...
load: 2.95  cmd: php 6462 running 35420.91u 158.86s
^C
real:1377m58.550s user:0m0.022s sys:0m0.016s
```

The command was run for over 22 hours and was stuck on 'Resolving dependencies through SAT' step. The PHP process used 99% of CPU and if I didn't cancel it, it could go forever I think.

Related: GH-7224 with the similar `composer.json`, but the above file it seems it is stuck in some loop forever. I've reproduced the issue on few different machines.

**Comment by kenorb** [comment]
I've tried to narrow down the required versions, but it didn't help:

```
{
  "require": {
    "behat/behat":                     "^2.5@stable",
    "dealerdirect/phpcodesniffer-composer-installer": "^0.4",
    "drupal/coder":                    "^8.2@stable",
    "drush/drush":                     "^8.1@stable",
    "jakub-onderka/php-parallel-lint": "^1.0@stable",
    "pdepend/pdepend":                 "^2.5@stable",
    "pheromone/phpcs-security-audit":  "^1.0@stable",
    "phploc/phploc":                   "^4.0@stable",
    "phpmd/phpmd":                     "^2.6@stable",
    "phpunit/phpcov":                  "^4.0@stable",
    "phpunit/phpunit":                 "^6.5@stable",
    "phpunit/phpunit-selenium":        "^4.1@stable",
    "sebastian/phpcpd":                "^3.0@stable",
    "squizlabs/php_codesniffer":       "^2.9@stable"
  },
  "minimum-stability": "dev"
}
```

**Comment by kenorb** [comment]
In one configuration which took like over half an hour to run, the dependency error was long for over 600 lines. One weird line was like:

>      [exec]     - Removal request for vipsoft/code-coverage-extension == 2.5.9999999.9999999-dev

The latest version of this package is `2.5.0.5` (`composer show -a vipsoft/code-coverage-extension`), so does it mean the Composer had to traverse through 9999999*9999999 versions for some reason?

Attaching the error logs: 
[Composer_error1.txt.gz](https://github.com/composer/composer/files/1890501/Composer_error1.txt.gz)
, [Composer_error2.txt.gz](https://github.com/composer/composer/files/1890504/Composer_error2.txt.gz), but these are generated only in certain scenarios, in most cases the dependencies takes few hours to compute.

**Comment by picasso250** [comment]
```
Resolving dependencies through SAT
Dependency resolution completed in 305.450 seconds
```
Is there better ways to resolve dependency?

Even, I think we can introduce a **faster resolving mode**, that it only expand `~2.0` to 2.0.0.
That is, it only guess the most possible version or fail directly to ensure the speed.

**Comment by stof** [comment]
`2.5.9999999.9999999-dev` is the normalized version of `2.5.x-dev`, i.e. the 2.5.x branch of the repo

**Comment by codeistalk** [comment]
Any updates

**Comment by staabm** [comment]
still reproducible with the latest composer version?

**Comment by cocochepeau** [comment]
Still experiencing it (upgrade from lumen "5.5.*" to "5.6.*").

**Comment by codeistalk** [comment]
Yes

**Comment by arku31** [comment]
I also experienced this. I have fixed my issues by updating some dependency versions. This is definitely a bug, this kind of conditions should lead to the error message and not hanging out but anyway it's kind of easy to "fix".

**Comment by kenorb** [comment]
The workaround is to avoid using wildcards or too vague versions, so:
- instead of `5.6.*`, use `^5.6.1` (or the latest known version),
- instead of `^2` use `^2.0.0`.

This avoids Composer guessing release numbers from 0 to 9999999, and traversing all permutations to match the final dependencies, most often causing Composer to fail due to out of memory.

**Comment by Seldaek** [comment]
Closing here, feel free to track https://github.com/composer/composer/issues/9294
