### ISSUE TITLE
Revision is ignored in dependent package

### ISSUE THREAD

**Issue by zored** [composer/composer#7241]
## Steps to reproduce:
- Create `./a/composer.json`:
    ```json
    {
        "name": "a",
        "require": {
            "danog/madelineproto": "dev-master#a18cfa28efa4"
        },
        "minimum-stability": "dev",
        "prefer-stable": true
    }
    ```
- Update: `cd ./a/ && composer update`.
- Check version: `composer show | grep danog/madelineproto`. Got `a18cfa28efa4` **as expected**.
- Create `./b/composer.json` that depends on `./a/composer.json`:
    ```json
    {
        "name": "b",
        "repositories": [
            {
                "type": "path",
                "url": "../a"
            }
        ],
        "require": {
            "a": "*"
        },
        "minimum-stability": "dev",
        "prefer-stable": true
    }
    ```
- Update: `cd ./b/ && composer update`.
- Check version: `composer show | grep danog/madelineproto`. **Got unexpected latest**.

Found here: danog/MadelineProto#366

**Comment by stof** [comment]
the commit locking is working only at the root  (and even at the root, it still has severe limitations, making it working only partially). It is ignored when used in a dependency.

**Comment by stof** [comment]
The way to have stable references for a packages is to make releases of the package.

**Comment by zored** [comment]
@stof thank you for response! 😃  
I could not find this info in docs. This limitation enforces authors to use stable versions of their packages, doesn't it?
