### ISSUE TITLE
SVN Private repo throws wrong credentials exception 

### ISSUE THREAD

**Issue by pmoubed** [composer/composer#7242]
My `composer.json`:

> "repositories": [
>         {
>             "type": "vcs",
>             "url": "http://private.repo.exampl.com/svn/repos/package_name",
>             "branches-path": "branches",
>             "tags-path": "tags",
>             "trunk-path": "trunk"
>         }
>     ],

Output of `composer install --verbose`:

> 
> The Subversion server (http://private.repo.example.com/svn/repos/package_name) requested credentials:
> Username: _input username by user_
> Password: _input password by user_
> Should Subversion cache these credentials? (yes/no)
> _input no by user_
> 
>   [RuntimeException]
>   Package could not be downloaded, wrong credentials provided (
>   svn: OPTIONS of 'http://private.repo.example.com/svn/repos/package_name/tags/1.0.3': authorization failed: Could not authenticate to server: rejected Basic challenge (http://private.repo.example.com/svn/repos/package_name)
>   )
> 
> 
> Exception trace:
>  () at phar:///var/www/html/dashboard/composer.phar/src/Composer/Downloader/SvnDownloader.php:104
>  Composer\Downloader\SvnDownloader->execute() at phar:///var/www/html/dashboard/composer.phar/src/Composer/Downloader/SvnDownloader.php:45
>  Composer\Downloader\SvnDownloader->doDownload() at phar:///var/www/html/dashboard/composer.phar/src/Composer/Downloader/VcsDownloader.php:90
>  Composer\Downloader\VcsDownloader->download() at phar:///var/www/html/dashboard/composer.phar/src/Composer/Downloader/DownloadManager.php:213
>  Composer\Downloader\DownloadManager->download() at phar:///var/www/html/dashboard/composer.phar/src/Composer/Installer/LibraryInstaller.php:186
>  Composer\Installer\LibraryInstaller->installCode() at phar:///var/www/html/dashboard/composer.phar/src/Composer/Installer/LibraryInstaller.php:90
>  Composer\Installer\LibraryInstaller->install() at phar:///var/www/html/dashboard/composer.phar/src/Composer/Installer/InstallationManager.php:173
>  Composer\Installer\InstallationManager->install() at phar:///var/www/html/dashboard/composer.phar/src/Composer/Installer/InstallationManager.php:160
>  Composer\Installer\InstallationManager->execute() at phar:///var/www/html/dashboard/composer.phar/src/Composer/Installer.php:588
>  Composer\Installer->doInstall() at phar:///var/www/html/dashboard/composer.phar/src/Composer/Installer.php:227
>  Composer\Installer->run() at phar:///var/www/html/dashboard/composer.phar/src/Composer/Command/InstallCommand.php:119
>  Composer\Command\InstallCommand->execute() at phar:///var/www/html/dashboard/composer.phar/vendor/symfony/console/Command/Command.php:242
>  Symfony\Component\Console\Command\Command->run() at phar:///var/www/html/dashboard/composer.phar/vendor/symfony/console/Application.php:842
>  Symfony\Component\Console\Application->doRunCommand() at phar:///var/www/html/dashboard/composer.phar/vendor/symfony/console/Application.php:193
>  Symfony\Component\Console\Application->doRun() at phar:///var/www/html/dashboard/composer.phar/src/Composer/Console/Application.php:251
>  Composer\Console\Application->doRun() at phar:///var/www/html/dashboard/composer.phar/vendor/symfony/console/Application.php:117
>  Symfony\Component\Console\Application->run() at phar:///var/www/html/dashboard/composer.phar/src/Composer/Console/Application.php:100
>  Composer\Console\Application->run() at phar:///var/www/html/dashboard/composer.phar/bin/composer:58
>  require() at /var/www/html/dashboard/composer.phar:24

And I expected this to happen:
If I add **http-basic** under my **config** with same username and password works fine but in interactive mode when user inputs username/password for private repository like shown above it doesn't work. 

It is working fine in v1.6.2, after upgrade to 1.6.3 this feature stopped working.

**Comment by pmoubed** [comment]
I think this line is causing the issue: https://github.com/composer/composer/blob/c2fbbe3b86788eb507a0f4f45f9fdc623ca579c4/src/Composer/Util/Svn.php#L107

**Comment by Seldaek** [comment]
I think it was fixed by some merges yesterday, please try again after `composer self-update --snapshot` or wait for 1.6.4 to be out later.

**Comment by Seldaek** [comment]
Ah, should have been fixed in https://github.com/composer/composer/commit/c9aa9c0d2fb2280f6ebda68b175f920a155e69b9
