### ISSUE TITLE
composer.json for project in bitbucket private repository

### ISSUE THREAD

**Issue by neoacevedo** [composer/composer#7249]
Hi
How should be the composer.json for a private project hosted in bitbucket?

I mean, not a package installed into vendor directory but else a full project (like Laravel or Yii2).

**Comment by oleg-andreyev** [comment]
You need to define package via [repositores](https://getcomposer.org/doc/05-repositories.md)

Example:
```
{
    "repositories": [
        { "type": "vcs", "url": "<bitbucket clone url>" }
    ],
    ...
}
```

**Comment by neoacevedo** [comment]
Oops! I forgot to close this issue time ago. Thank you @oleg-andreyev I already had found it in another issues :)
