### ISSUE TITLE
Possibility to catch if package not found

### ISSUE THREAD

**Issue by vladitot** [composer/composer#7250]
Hello.
I have a task.
We have packages, stored in our private repository.
Also we have same packages, stored at "server" in zip archives.
Access rights is checking by ssh key-pair, stored on the machine.
Repositories stored at Gitlab.
"Server" is apache with php, but I think it's no matter.
On "composer install" I need to load package from repository if I have access rights on this machine, or load from zip archive from server if I haven't access rights. Is it possible to do this? I need advice.

**Comment by Seldaek** [comment]
I don't know about your setup so it's kinda hard to say, but one easy option is to use Private Packagist https://packagist.com to deal with private repos. It supports GitLab sync and will make sure people can download zips easily with every user having their own token.
