### ISSUE TITLE
PathDownloader: successful installed package fails on package update

### ISSUE THREAD

**Issue by mricherzhagen** [composer/composer#7255]
I encountered a weird state, where sometimes an exception is thrown, but sometimes not, when installing a dependency from a path-repository in a subdirectory.

The full "testcase"-repository can be found [here](https://github.com/mricherzhagen/composer_subpackage_example)

My 2 versions of the `composer.json`-File:
```json
{
    "name": "mricherzagen/composer_subpackage_example",
    "repositories": [
    ],
    "require": {
        "php": ">5.0"
    }
}
```

```json
{
    "name": "mricherzagen/composer_subpackage_example",
    "repositories": [
        {
            "type": "path",
            "url": "./subpackage"
        }
    ],
    "require": {
        "mricherzagen/composer_subpackage_example_subpackage": "*@dev",
        "php": ">5.5"
    }
}
```

When i have these 2 `composer.json` files on 2 branches i get an exception when executing `composer install` after switching between the branches.
I did add the "php"-requirement to force the creation of a `composer.lock`-file. I could not reproduce the error when i did not change the php-requirement-version between the 2 files as well.

I run these commands:
```bash
rm -rf vendor/ #if exists
git checkout master
composer install # Runs without error
git checkout add_subpackage
composer install # Runs without error, installs subpackage
git checkout master
composer install # Runs without error - does "something"?
git checkout add_subpackage
composer install # Error
```

I get the following output:

```
  [RuntimeException]
  Package mricherzagen/composer_subpackage_example_subpackage cannot install to "[...]/composer_subpackage_example/subpackage" inside its source at  "[...]/composer_subpackage_example/subpackage"
```

And I expected this to happen:

Either:
* the exception being thrown on the first `composer install`  on the `add_subpackage`-branch

or (even better)
* the exception not being thrown at all.

**Comment by mricherzhagen** [comment]
So the [`LibraryManager->installCode()`](https://github.com/composer/composer/blob/14c77130e8f717ceb154720e1abefafe99124cb9/src/Composer/Installer/LibraryInstaller.php#L183-L187) seems to work, but it fails on [`LibraryManager->updateCode()`](https://github.com/composer/composer/blob/14c77130e8f717ceb154720e1abefafe99124cb9/src/Composer/Installer/LibraryInstaller.php#L189-L208), which calls `PathDownloader->update()`, which is [`inherited from FileDownloader`](https://github.com/composer/composer/blob/14c77130e8f717ceb154720e1abefafe99124cb9/src/Composer/Downloader/FileDownloader.php#L198-L202).

For some reasons the `$target->getDistUrl()` and `$this->getInstallPath($target)` in the `LibraryManger->update()`-Method are identical. which triggers the exception.

So i can install a package, but not update it, which from my understanding should not happen.

**Comment by Frederick888** [comment]
Same issue here. Does anyone have the idea of the last working version? It can't normally generate a lock file currently due to this bug.
