### ISSUE TITLE
It is possible to specify a configuration file (composer.json) for install/update etc. command ?

### ISSUE THREAD

**Issue by huangzhhui** [composer/composer#7266]
It is possible to specify a configuration file (composer.json) for install/update etc. command ? for example, I have a dev configuration file like composer.dev.json, it's only use for some situation like component development, only use for some guys in the team, If `composer install -c composer.dev.json` command or some command like this is available it would be prefect.

**Comment by tomzx** [comment]
See https://getcomposer.org/doc/03-cli.md#composer.
