### ISSUE TITLE
Could not parse version constraint &&: Invalid version string "&&"

### ISSUE THREAD

**Issue by hassansheikh** [composer/composer#7270]
My `composer.json`:

```json
{
    "name": "yiisoft/yii2-app-advanced",
    "description": "Yii 2 Advanced Application Template",
    "keywords": ["yii2", "framework", "advanced", "application template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "dev",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": ">=2.0.06",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "yiisoft/yii2-jui": "*",
		"yiisoft/yii2-imagine": "~2.0.0",
		"php-ffmpeg/php-ffmpeg": "~0.5",
        "yiisoft/yii2-redis": "^2.0",
        "kartik-v/yii2-widget-datetimepicker": "*",
        "kartik-v/yii2-widget-datepicker": "*",
        "aws/aws-sdk-php": "^3.27.1"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-faker": "*",
        "yiisoft/yii2-gii": "*"
    },
    "config": {
        "process-timeout": 1800
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}

```

Output of `composer diagnose`:

```
[UnexpectedValueException]
Could not parse version constraint &&: Invalid version string "&&"
```

When I run this command:

```
composer update
```

I get the following output:

```
[UnexpectedValueException]
Could not parse version constraint &&: Invalid version string "&&"
```

And I expected this to happen:
I want to update my yii2 version.  can you please help me to fix my issue

**Comment by tomzx** [comment]
Can you run `composer update -vvv`?

It looks like one of the packages you depend on may have an invalid constraint string.

**Comment by hassansheikh** [comment]
Issue fixed by using complete version name instead of "*" in composer.json file

**Comment by pptyasar** [comment]
@hassansheikh  is this fixed

**Comment by pptyasar** [comment]
May I know how ..
This is my composer.json

`{
    "name": "yiisoft/yii2-app-basic",
    "description": "Yii 2 Basic Project Template",
    "keywords": ["yii2", "framework", "basic", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "dev",
    "require": {




        
        "php": ">=5.4.0",
        "yiisoft/yii2": "~2.0.14",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0",
        "dmstr/yii2-adminlte-asset": "2.*",
        "vlucas/phpdotenv": "1.1.*@dev",
        "codeception/specify": "*",
        "codeception/verify": "*",
        "yiisoft/yii2-imagine": "^2.0",
        "kartik-v/yii2-widget-select2": "@dev",
        "yiisoft/yii2-jui": "^2.0",
        "kartik-v/yii2-widget-typeahead": "*",
        "kartik-v/yii2-widget-growl": "*",
        "keygenqt/yii2-autocomplete-ajax": "*",
        "wbraganca/yii2-dynamicform": "*",
        "codeonyii/yii2-at-least-validator": "^1.1",
        "yiisoft/yii2-authclient": "^2.1",
        "linslin/yii2-curl": "*",
        "kartik-v/yii2-widget-colorinput": "*",
        "2amigos/yii2-google-maps-library": "*",
        "machour/yii2-notifications": "^1.0@dev",
        "richardfan1126/yii2-sortable-gridview": "*",
        "imanilchaudhari/yii2-currency-converter": "dev-master",
        "2amigos/yii2-taggable-behavior": "~1.0",
        "kartik-v/yii2-export": "*",
        "kartik-v/yii2-grid": "@dev",
        "2amigos/qrcode-library": "^1.1",
        "kartik-v/yii2-widget-datetimepicker": "*",
        "alexandernst/yii2-device-detect": " 0.0.12",
        "yii2tech/csv-grid": "^1.0",
        "mistic100/randomcolor": "dev-master",
        "arturoliveira/yii2-excelview": "*",
        "phpoffice/phpspreadsheet": "dev-master",
        "kartik-v/yii2-mpdf": "^1.0@dev",
        "sivarajd/letter-avatar": "dev-master",
        "yiisoft/yii2-codeception": "^2.0@dev",
        "brussens/yii2-maintenance-mode": "*",
        "yiisoft/yii2-queue": "^2.0@dev",
        "kartik-v/yii2-editable": "*",
        "ramsey/uuid": "^3.0@dev",
        "codeception/codeception": "2.4.x-dev"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.0.0",
        "yiisoft/yii2-gii": "~2.0.0",
        "yiisoft/yii2-faker": "~2.0.0",

        "codeception/base": "^2.2.3",
        "codeception/verify": "~0.3.1",
        "codeception/specify": "~0.4.3"
    },
    "config": {
        "process-timeout": 1800,
        "fxp-asset":{
            "installer-paths": {
                "npm-asset-library": "vendor/npm",
                "bower-asset-library": "vendor/bower"
            }
        }
    },
    "scripts": {
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject",
            "yii\\composer\\Installer::postInstall"
        ]
    },
    "extra": {
        "yii\\composer\\Installer::postCreateProject": {
            "setPermission": [
                {
                    "runtime": "0777",
                    "web/assets": "0777",
                    "yii": "0755"
                }
            ],
            "generateCookieValidationKey": [
                "config/web.php"
            ]
        },
        "yii\\composer\\Installer::postInstall": {
            "generateCookieValidationKey": [
                "config/web.php"
            ]
        },
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ]
}
`

**Comment by pptyasar** [comment]
{
    "name": "yiisoft/yii2-app-basic",
    "description": "Yii 2 Basic Project Template",
    "keywords": ["yii2", "framework", "basic", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "dev",
    "require": {




        
        "php": ">=5.4.0",
        "yiisoft/yii2": "~2.0.14",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0",
        "dmstr/yii2-adminlte-asset": "2.*",
        "vlucas/phpdotenv": "1.1.*@dev",
        "codeception/specify": "*",
        "codeception/verify": "*",
        "yiisoft/yii2-imagine": "^2.0",
        "kartik-v/yii2-widget-select2": "@dev",
        "yiisoft/yii2-jui": "^2.0",
        "kartik-v/yii2-widget-typeahead": "*",
        "kartik-v/yii2-widget-growl": "*",
        "keygenqt/yii2-autocomplete-ajax": "*",
        "wbraganca/yii2-dynamicform": "*",
        "codeonyii/yii2-at-least-validator": "^1.1",
        "yiisoft/yii2-authclient": "^2.1",
        "linslin/yii2-curl": "*",
        "kartik-v/yii2-widget-colorinput": "*",
        "2amigos/yii2-google-maps-library": "*",
        "machour/yii2-notifications": "^1.0@dev",
        "richardfan1126/yii2-sortable-gridview": "*",
        "imanilchaudhari/yii2-currency-converter": "dev-master",
        "2amigos/yii2-taggable-behavior": "~1.0",
        "kartik-v/yii2-export": "*",
        "kartik-v/yii2-grid": "@dev",
        "2amigos/qrcode-library": "^1.1",
        "kartik-v/yii2-widget-datetimepicker": "*",
        "alexandernst/yii2-device-detect": " 0.0.12",
        "yii2tech/csv-grid": "^1.0",
        "mistic100/randomcolor": "dev-master",
        "arturoliveira/yii2-excelview": "*",
        "phpoffice/phpspreadsheet": "dev-master",
        "kartik-v/yii2-mpdf": "^1.0@dev",
        "sivarajd/letter-avatar": "dev-master",
        "yiisoft/yii2-codeception": "^2.0@dev",
        "brussens/yii2-maintenance-mode": "*",
        "yiisoft/yii2-queue": "^2.0@dev",
        "kartik-v/yii2-editable": "*",
        "ramsey/uuid": "^3.0@dev",
        "codeception/codeception": "2.4.x-dev"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.0.0",
        "yiisoft/yii2-gii": "~2.0.0",
        "yiisoft/yii2-faker": "~2.0.0",

        "codeception/base": "^2.2.3",
        "codeception/verify": "~0.3.1",
        "codeception/specify": "~0.4.3"
    },
    "config": {
        "process-timeout": 1800,
        "fxp-asset":{
            "installer-paths": {
                "npm-asset-library": "vendor/npm",
                "bower-asset-library": "vendor/bower"
            }
        }
    },
    "scripts": {
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject",
            "yii\\composer\\Installer::postInstall"
        ]
    },
    "extra": {
        "yii\\composer\\Installer::postCreateProject": {
            "setPermission": [
                {
                    "runtime": "0777",
                    "web/assets": "0777",
                    "yii": "0755"
                }
            ],
            "generateCookieValidationKey": [
                "config/web.php"
            ]
        },
        "yii\\composer\\Installer::postInstall": {
            "generateCookieValidationKey": [
                "config/web.php"
            ]
        },
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ]
}

**Comment by hassansheikh** [comment]
"require": {
"php": ">=5.4.0",
"yiisoft/yii2": ">=2.0.5",
"yiisoft/yii2-bootstrap": "~2.0.0",
"yiisoft/yii2-swiftmailer": "~2.0.0 || ~2.1.0",
"vlucas/phpdotenv": ">=2.2",
"conquer/oauth2": "@dev",
"linslin/yii2-curl": "@dev",
"kartik-v/yii2-icons": "@dev",
"ramsey/uuid": "^3.0@dev",
"thamtech/yii2-uuid": "@dev",
"yiisoft/yii2-queue": "^2.0@dev"
},
"require-dev": {
"yiisoft/yii2-codeception": "~2.0.0",
"yiisoft/yii2-debug": "~2.0.0",
"yiisoft/yii2-gii": "~2.0.0",
"yiisoft/yii2-faker": "~2.0.0"
},

Try this one, hope it would work
