### ISSUE TITLE
[Feature] A package runner (npx like)

### ISSUE THREAD

**Issue by BafS** [composer/composer#7272]
Hi,

npm "recently" [added the new npx binary](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b) to run packages directly from node_modules. Would it be possible to have  something similar with composer without the need of run-script, like composerx ?

Example: To run a testsuite with PHPUnit we need to add an entry in "script" and do something like `composer run-script phpunit -- --testsuite xxx` or directly via `./vendor/bin/phpunit  --testsuite x`. With composerx it would just be `composerx phpunit --testsuite x`.

Thanks in advance

**Comment by Seldaek** [comment]
You can do `composer exec phpunit` too, although that is quiet by default, so `composer exec -v phpunit -- --filter foo` for example. With an `alias c=composer` or `cx=composer exec -v` for you can shorten that quite a bit. As we don't have an installer per se it's kinda hard for us to provide this as a utility.

**Comment by jansenfelipe** [comment]
@Seldaek In your example, I need to have phpunit already installed in my project for the `composer exec phpunit` command to work.

I found the idea of running a PHP script interesting without having to install it interesting.
