### ISSUE TITLE
Version 1.6.4 breaks `-d={my-folder}`

### ISSUE THREAD

**Issue by omichelsen** [composer/composer#7276]
When I run this command:

```
composer -d=api install
```

I get the following output:

```
[RuntimeException]
Invalid working directory specified, =api does not exist.
```

And I expected this to happen:

It should use the folder "api" as the working folder.

This works fine in v1.6.3 but breaks in v1.6.4. I can make it work by using `composer --working-dir=api install`, but this breaking change is not mentioned in the v1.6.4 release notes. According to the documentation the shorthand `-d` is still valid. 

I have also tried `composer -d api install` (no `=`) but that fails as well with the following error:

```
[Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "api" is not defined.
```

**Comment by jvasseur** [comment]
This changes comes from an update in the symfony console component. You need to use `-dapi` (without `=`) or `composer install -d api` (putting the option after the command)

**Comment by stof** [comment]
the syntax with the `=` sign works when using long options.

**Comment by omichelsen** [comment]
Nevertheless, this is not documented and it is a breaking change in a patch version.

**Comment by stof** [comment]
@omichelsen any bugfix is a BC break if you were relying on it though
