### ISSUE TITLE
Replace "self" in circular dependency

### ISSUE THREAD

**Issue by iluuu1994** [composer/composer#7279]
First of all, thanks for Composer! ❤️ I take it for granted everyday.

We develop our own web framework and build websites with it. Obviously the websites depend on the framework but unfortunately the framework also depends on the website. The website contains various classes like entities that are directly referenced in the framework. Yeah, I know this is stupid but unfortunately we can't change that for now.

This was irrelevant until now because the framework never had to be used without a website. This changes now as we'd like to setup static analysis with [PHPStan](https://github.com/phpstan/phpstan) for the framework. When PHPStan looks at the framework those entity classes must exist.

What I'd like to do is add the website-skeleton, which we usually fork when creating a new website, to the `require-dev`.

`composer.json` of the framework:

```json
{
    "name": "company/framework",
    "type": "library",
    "require-dev": {
        "company/website-skeleton": "^4.3"
    }
}
```

`composer.json` of the website-skeleton:

```json
{
    "name": "company/website-skeleton",
    "require": {
        "company/framework": "^4.3"
    }
}
```

This works absolutely fine. The problem is that as soon as we branch the framework the whole build fails because the website-skeleton requires a stable `^4.3` release. I'd like to overwrite the version of the framework for this instance. I tried using `replace` and branch-aliases but I was unsuccessful to get this working.

Any help would be greatly appreciated! I've been at this for hours.

Thanks again for Composer!

**Comment by alcohol** [comment]
Did you try using https://getcomposer.org/doc/03-cli.md#composer-root-version ?

**Comment by iluuu1994** [comment]
Oh, I missed that one. I'll try that!
