### ISSUE TITLE
Composer 1.6.4 regression from 1.5.6 and documented behavoir

### ISSUE THREAD

**Issue by epreston** [composer/composer#7281]
My `composer.json`:

```json
    "require": {
        "test/test-package": "*@dev"
    },
    "repositories": [
        {
            "type": "path",
            "url": "./path-to-test-package",
            "options": {
                "symlink": true
            }
        }
    ]
```

Output of `composer diagnose`:

```
require.test/test-package : unbound version constraints (*@dev) should be avoided
```

When I run this command:

```
composer update
```

I get the following output the first time:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing test/test-package (dev-master): Symlinking from ./path-to-test-package
Writing lock file
Generating optimized autoload files
```

And I expected this to happen:

Running the composer update command again, a second time, the autoloader fails to load any classes or files from the directory `./test` through the newly created `vendor\test\test-package` symlink.

DOWNGRADING to 1.5.6 fixes this issue.

This behaviour is documented to work here: 
https://getcomposer.org/doc/05-repositories.md#path

**Comment by alcohol** [comment]
Need a reproducible scenario (test-repo, etc). 
Please re-open once you can provide this.
