### ISSUE TITLE
Bug Devil Not install ubuntu debian

### ISSUE THREAD

**Issue by gilcierweb** [composer/composer#7290]
php -i | grep Configure
PHP 7.1.6-2 (cli) (built: Jun 14 2017 05:31:31) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
 ✘ gilcierweb  ~  php --re Phar | grep version
 ✘ gilcierweb  ~  php -i | grep Configure
 ✘ gilcierweb  ~  sudo pecl install phar
sudo: pecl: comando não encontrado
 ✘ gilcierweb  ~  sudo service nginx restart
 gilcierweb  ~  php -i | grep Configure   
 ✘ gilcierweb  ~  composer update

Fatal error: Uncaught Error: Call to undefined function Composer\Json\json_decode() in /usr/share/php/Composer/Json/JsonFile.php:153
Stack trace:
#0 /usr/share/php/Composer/Factory.php(272): Composer\Json\JsonFile->validateSchema(1)
#1 /usr/share/php/Composer/Factory.php(418): Composer\Factory->createComposer(Object(Composer\IO\ConsoleIO), '/home/gilcierwe...', false, '/home/gilcierwe...', true)
#2 /usr/share/php/Composer/Factory.php(398): Composer\Factory->createGlobalComposer(Object(Composer\IO\ConsoleIO), Object(Composer\Config), false, true)
#3 /usr/share/php/Composer/Console/Application.php(432): Composer\Factory::createGlobal(Object(Composer\IO\ConsoleIO), false)
#4 /usr/share/php/Composer/Console/Application.php(135): Composer\Console\Application->getPluginCommands()
#5 /usr/share/php/Symfony/Component/Console/Application.php(123): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /usr/share/php/Composer/Console/Applicat in /usr/share/php/Composer/Json/JsonFile.php on line 153

**Comment by itscaro** [comment]
install php-json?

**Comment by gilcierweb** [comment]
Already installed all extensions !!
