### ISSUE TITLE
composer archive with no root level files gets installed wrong

### ISSUE THREAD

**Issue by glensc** [composer/composer#7292]
if i have project which i `archive.exclude` files that only `src` subdir remains, it gets installed to `vendor` without `src` subdir, which results broken classloader paths.

```
    "archive": {
        "exclude": ["/.*", "/tests", "/vendor", "/*.spec", "/*.xml", "/*.md", "/*.lock", "*.patch", "*.tar"]
    },
```

i'll provide reproducer soon, but as i know that the created .zip/.tar.gz is okay, but the install part "gets it wrong".

**Comment by alcohol** [comment]
This is due to how we treat archives and how Github dist archives are structured.

**Comment by stof** [comment]
anyway, you should generally keep the LICENSE file at the root anyway.

**Comment by glensc** [comment]
not everybody develops opensource. no license!

however, my input is satis provided archives, not github zip.

yes. as a workaround, need to keep some file at top level.

based on symtoms, i deduct that the behavior is not constant, there seems to be some variations how many top levels are stropped. imho that should be fixed count and driver specific (github only?).

just guessing, because haven't looked at actual implementation (source code)

**Comment by stof** [comment]
to avoid the issue, you only need to ensure that the archive contains at least 2 top-level items (one of them being your `src` folder).
An option could be to keep a readme or the composer.json at the root (keeping the LICENSE will solve it too for open-source projects)
