### ISSUE TITLE
Path repo symlink to symlink shortest path optimization undesired

### ISSUE THREAD

**Issue by cvdwel** [composer/composer#7294]
My `composer.json`:

```json
{
  "repositories": [
      {
          "type": "path",
          "url": "../../packages/my-package"
      }
  ],
  "require": {
      "my/package": "*@dev"
  }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.my/package : unbound version constraints (*@dev) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.6.4
PHP version: 7.1.14
PHP binary path: /usr/bin/php
```

When I run this command:

```
composer update
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing my/package (dev-master): Symlinking from ../../packages/my-package
Writing lock file
Generating autoload files
```

And I expected this to happen:

A symlink created in vendor/my/package pointing to ../../../../packages/my-package, but the symlink points to ../../../../my-package. So it's optimized to using the shortest path: https://github.com/composer/composer/blob/a8df30c09be550bffc37ba540fb7c7f0383c3944/src/Composer/Downloader/PathDownloader.php#L104

Which is great if you run composer install on your production environment, but not if you want to distribute the application to a different server with a different filesystem layout. So this behaviour should at least be optional if you ask me. Maybe add some flag like "optimize_symlink" to the path repo options?

I don't run composer install on my production machines, but just once in a CI/CD environment. After composer install is completed, the application including the vendor directory will be rsynced to production.

Used directory structure:

- apps
\_ my-app
  \_ composer.json
- packages
\_ my-package => symlink to ../real-package (but could be located anywhere on the filesystem, so this symlink might point to a different location in a different environment)
- real-package
\_ composer.json

**Comment by alcohol** [comment]
Unsupported workflow.
