### ISSUE TITLE
Require minimum version of Composer

### ISSUE THREAD

**Issue by grasmash** [composer/composer#7297]
Is it possible for a package to declare a dependency on a minimum version of Composer?

E.g., declare that my package requires Composer `^1.6.0`. 

I believe that adding `composer/composer` to require will not achieve this, as it will simply download Composer to vendor. It would not prevent a global composer version 1.5.0 from executing against my project.

**Comment by alcohol** [comment]
What you are asking is not possible, nor can I imagine why you would want that.

May I ask in what scenario you perceive this to be useful or necessary?

**Comment by Jean85** [comment]
I.e. when the root package requires a GitLab private package, hence requiring Composer 1.6.5+ (2 previous versions contained GitLab-related bugs)

**Comment by alcohol** [comment]
It simply is not possible to specify this. While we could turn this into an RFC, the likelihood of it being implemented is very low. It would be a root-only attribute. And you could just as easily document the recommended version in your project README.

**Comment by Seldaek** [comment]
The only approximation of this we have is the virtual package composer-plugin-api which is in 1.1.0 at the moment. I am not sure what the point would be of doing this for the rest of composer. @Jean85's use case IMO is kinda solvable by having people upgrading their composer version more often. I don't like having a version check as our snapshot builds don't have a version per se.
