### ISSUE TITLE
Combination of packages causing very slow dependency resolution

### ISSUE THREAD

**Issue by anlutro** [composer/composer#7300]
Given this situation, with a completely fresh setup:

```
$ rm -rf /tmp/composertest; mkdir -p /tmp/composertest; cd /tmp/composertest
$ composer require illuminate/{database,validation}:4.2.* anlutro/l4-testing:0.2.* -vvvv
```

On my laptop, this shows me:

```
Resolving dependencies through SAT
Dependency resolution completed in 29.327 seconds
```

If I remove one of the illuminate packages, or try to manually require the packages that `anlutro/l4-testing` requires, the resolution takes less than a second.

I *think* the issue stems from `l4-testing`'s require-dev being taken into account when resolving dependencies, because I see references to `illuminate/framework` being added to the reasons in the output despite this package not being installed, but this is pure speculation from my part.

Newer versions of the illuminate packages (I've tried with `5.1.*`, `5.5.*` and `5.6.*`) also resolve fast.

30 seconds is acceptable on my laptop, but this is causing 10 minute install times on travis-ci.com using older PHP versions (5.6 or lower).

```
$ composer diagnose
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.6.4
PHP version: 7.2.5
PHP binary path: /usr/local/bin/php
```

**Comment by jvasseur** [comment]
`laravel/framework` is considered during the resolution because it's a dependency of `anlutro/l4-testing` version `0.2.0` - `0.2.6` not because it's a dev requirement.

Requiring dependencies of dependencies speed up the resolution because it adds "absolute" rules to the resolution that can directly eliminate package version where dependencies of dependencies are not sure because we don't know which version of the first dependency will be installed.

Another way to speed up resolution is to use constraints that allow less version because the solver will have less package version to check for a solution.

**Comment by anlutro** [comment]
Ah I didn't even realize that! Changing my command to `l4-testing:~0.2.7` does indeed make it way faster. I'll do this to speed up my travis-ci build, at least.

**Comment by anlutro** [comment]
Urgh, turns out that only helped in my isolated example, in the repository I'm trying to run tests (https://github.com/anlutro/laravel-repository) the resolution slowed down to 45 seconds on my laptop :/

**Comment by jvasseur** [comment]
One thing you could do is remove the `"minimum-stability": "dev"` and instead add a `@dev` flag for the packages where you want to allow dev versions. Not allowing dev version for all dependencies reduce the number of package to test and thus decrease the time needed for solving dependencies.

**Comment by alcohol** [comment]
This is not a Composer issue, but more a matter of configuring more strict version constraints.
