### ISSUE TITLE
Provide default config via Composer API

### ISSUE THREAD

**Issue by grasmash** [composer/composer#7301]
I manage a Composer plugin, and I would like my plugin to provide default configuration for the `extra` array and the `autoload-dev` array. The configuration in question is not owned by my plugin.

Is it possible to do this with the Composer Plugin API? If so, can you please point me in the right direction in term of what classes to use and what events to listen to?

**Comment by Seldaek** [comment]
On plugin activation I think you could grab the Composer instance and from it `->getPackage()` gives you the root package which you can then modify to contain what you want in extra/autoload-dev.

**Comment by grasmash** [comment]
Thank you for the suggestion. It works, but with one issue. It seems that the plugin is not activated until the subsequent `composer` call, after the plugin is installed. E.g. `composer install my/plugin` does not activate the plugin, but the next `composer install something/else` does. Is there any way to hook into the initial `composer install` process?

**Comment by stof** [comment]
Well, when installing the plugin, it gets registered only after its installation is done. So it might be too late for some things.
