### ISSUE TITLE
Fatal error:  Out of memory

### ISSUE THREAD

**Issue by abhisheks4** [composer/composer#7302]
Fatal error: Out of memory (allocated 1475608576) (tried to allocate 268435456 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php on line 220
PHP Fatal error:  Out of memory (allocated 1475608576) (tried to allocate 268435456 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php on line 220
/c/ProgramData/ComposerSetup/bin/composer: line 10:  8388 Segmentation fault      php "${dir}/composer.phar" "$@"

My `composer.json`:

{
    "name": "symfony/framework-standard-edition",
    "license": "MIT",
    "type": "project",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-4": { "": "src/" },
        "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
    },
    "require": {
        "php": ">=5.6",
        "beberlei/DoctrineExtensions": "^1.0",
        "doctrine/doctrine-bundle": "~1.4",
        "doctrine/doctrine-fixtures-bundle": "dev-master",
        "doctrine/orm": "^2.4.8",
        "egeloen/ckeditor-bundle": "^4.0",
        "facebook/graph-sdk": "^5.6",
        "friendsofsymfony/jsrouting-bundle": "2.0.*@dev",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "google/apiclient": "^2.0",
        "google/recaptcha": "~1.1",
        "gos/web-socket-bundle": "^1.8",
        "incenteev/composer-parameter-handler": "~2.0",
        "javiereguiluz/easyadmin-bundle": "^1.16",
        "knplabs/knp-components": "~1.2",
        "knplabs/knp-paginator-bundle": "dev-master",
        "league/oauth2-client": "2.1",
        "mgp25/instagram-php": "^1.5",
        "sensio/distribution-bundle": "~4.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "stof/doctrine-extensions-bundle": "@dev",
        "symfony/assetic-bundle": "^2.8",
        "symfony/monolog-bundle": "^3.0.2",
        "symfony/swiftmailer-bundle": "~2.3,>=2.3.10",
        "symfony/symfony": "2.8.*",
        "twig/twig": "^1.0||^2.0",
        "vich/uploader-bundle": "^0.14.0",
        "wemakecustom/stripe-bundle": "dev-master"
    },
    "require-dev": {
        "sensio/generator-bundle": "~3.0",
        "symfony/phpunit-bridge": "~2.7"
    },
    "scripts": {
        "symfony-scripts": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-install-cmd": [
            "@symfony-scripts"
        ],
        "post-update-cmd": [
            "@symfony-scripts"
        ]
    },
    "config": {
        "bin-dir": "bin",
        "platform": {
            "php": "5.6"
        },
        "sort-packages": true
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": {
            "dev-master": "2.8-dev"
        }
    }
}

Output of `composer diagnose`:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)

Fatal error: Out of memory (allocated 1412169728) (tried to allocate 268435456 bytes) in phar://C:/ProgramData/Comp          oserSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php on line 220
PHP Fatal error:  Out of memory (allocated 1412169728) (tried to allocate 268435456 bytes) in phar://C:/ProgramData          /ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php on line 220
/c/ProgramData/ComposerSetup/bin/composer: line 10: 11796 Segmentation fault      php "${dir}/composer.phar" "$@"
```

When I run this command:

```
composer update
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Fatal error: Out of memory (allocated 1412169728) (tried to allocate 268435456 bytes) in phar://C:/ProgramData/Comp          oserSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php on line 220
PHP Fatal error:  Out of memory (allocated 1412169728) (tried to allocate 268435456 bytes) in phar://C:/ProgramData          /ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php on line 220
/c/ProgramData/ComposerSetup/bin/composer: line 10: 11796 Segmentation fault      php "${dir}/composer.phar" "$@"
```

And I expected this to happen:

It should update vendors

**Comment by abhisheks4** [comment]
@alcohol , hey could please let me know if there is another thread which has bee resolved and closesd

**Comment by alcohol** [comment]
That is not what your initial post shows.

**Comment by abhisheks4** [comment]
@alcohol  any suggestion this scenario
