### ISSUE TITLE
 Magento 2 Upgrade Error :: Class Not Found -> Composer\Semver\VersionParser 

### ISSUE THREAD

**Issue by Jeeva-Rathinam** [composer/composer#7305]
I am try to upgrade 2.0.0 to 2.1.7.

Installation Guide : https://www.mgt-commerce.com/tutorial/how-to-upgrade-magento2-with-composer

As regard installation guide 6th step getting stuck.

Fatal error: Class 'Composer\Semver\VersionParser' not found in C:\wamp\www\gta\ vendor\composer\composer\src\Composer\Package\Version\VersionParser.php on line 17

My VersionParser.php file : https://justpaste.it/5x351

How can i solve this error.

**Comment by Seldaek** [comment]
Seems like you did not install composer correctly? Please follow instructions at https://getcomposer.org/download/ and check if `composer diagnose` works before trying anything with regard to Magento. We won't provide support for magento specific issues here.
