### ISSUE TITLE
.git folder inside package

### ISSUE THREAD

**Issue by assghard** [composer/composer#7308]
Hello.
I just created my first composer package. 
There is .git folder inside after install (composer require assghard/aes-file-encription).
How I can remove it from package?

Best regards,
assghard

**Comment by stof** [comment]
For dev versions of packages, Composer installs them from source by default. This is where the `.git` folder comes from.
The solution if you don't want it is to ask Composer to install from dist (note that this does not guarantee that there won't be a source install, as some packages may provide only source, but any package hosted on Github, Gitlab or Bitbucket will have a dist at least as these platforms are generating it):

```shell
# Remove the existing source installation so that composer reinstalls the package
$ rm -rf vendor/assghard/aes-file-encription
# Run the composer installation, which will reinstall the missing package
$ composer install --prefer-dist
```

If you want to *always* install from dist, setting it through the config might be easier than using the `--prefer-dist` option each time you run `install`, `update` or `require`: https://getcomposer.org/doc/06-config.md#preferred-install

**Comment by assghard** [comment]
Thanks a lot
