### ISSUE TITLE
Could not find package ext-xyz. Did you mean this? ext-xyz

### ISSUE THREAD

**Issue by uuf6429** [composer/composer#7310]
My `composer.json`:

```json
{
    "name": "my/test",
    "description": "a test",
    "require": {
    }
}
```

Output of `composer diagnose`:

```
...
Checking composer version: OK
Composer version: 1.6.5
PHP version: 5.6.31
PHP binary path: C:\php\php.exe
```

When I run this command:

```
composer require ext-ssh2:*
```

I get the following output:

```
  [InvalidArgumentException]
  Could not find package ext-ssh2.

  Did you mean this?
      ext-ssh2
```

Funny message. 😄 

----

If I add `"ext-ssh2": "*"` to `composer.json` manually and run `composer update` I get this:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-ssh2 * is missing from your system. Install or enable PHP's ssh2 extension.
```
**This is was expected, I don't have that extension on my system.**

However, I expected a similar message to be shown when I run `composer require ...` instead of the strange one mentioned above.

**Comment by Seldaek** [comment]
Could be a quoting issue due to your use of the `*`. Have you tried `composer require 'ext-ssh:*'` ?

**Comment by cvele** [comment]
@Seldaek I doubt it, since it started happening in my projects few hours ago. In my case packages I tried are Symfony related. Could this be symfony/flex issue?

**Comment by uuf6429** [comment]
@Seldaek yes, I tried that too - same result.

**Comment by alcohol** [comment]
For extensions we use https://github.com/composer/composer/blob/master/src/Composer/Repository/PlatformRepository.php -- but it might be that this is not properly setup/initialized in the `require` command?

**Comment by Slayer911** [comment]
Also such error can be for reason that your repository does not support your version of the composer, for example you have 1 version, and the repository supports only the 2. 
New vendors published on "packagist.org" accept only second composer version.
![image](https://user-images.githubusercontent.com/9704032/124598739-9c4c9c00-de6d-11eb-9a32-83a5cb8f3572.png)

**Comment by stof** [comment]
@Slayer911 See https://blog.packagist.com/deprecating-composer-1-support/ for the actual rule

**Comment by Slayer911** [comment]
@stof  I read this article, thanks. I wrote my post for people who looking resolving of the same error in google.
