### ISSUE TITLE
Tell me what directory I'm in when I get File "./composer.json" cannot be found in the current directory

### ISSUE THREAD

**Issue by joshuaadickerson** [composer/composer#7311]
I am running composer through Docker with a bunch of shell scripts attached. I'd like to know which directory composer is in.

The error:
File "./composer.json" cannot be found in the current directory

Is not very helpful. I would like it to show me what directory it is looking in. So, change it to:
File "./composer.json" cannot be found in $PWD

**Comment by tomzx** [comment]
Can you please run your `php composer.phar` command with `-vvv` so it's easier to identify the source of your problem?
