### ISSUE TITLE
Open_basedir restriction error while using composer

### ISSUE THREAD

**Issue by rumanpasha** [composer/composer#7315]
I'm getting  the following error on my development server while installing a json schema validation library:

tempnam(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): 

how can i configure composer to use another folder instead of /temp folder?

**Comment by alcohol** [comment]
You can't, since `tempnam()` is a native PHP function. Which indicates to me that your PHP configuration is simply broken. Having PHP default to `/tmp` for temporary files while not allowing `/tmp` in your open basedir settings does not make much sense to me.
