### ISSUE TITLE
Invalid installer signature while installing composer programatically

### ISSUE THREAD

**Issue by ohchiko** [composer/composer#7317]
I get
```
ERROR: Invalid installer signature
```

When I'm building gitlab registry on my server using my `Dockerfile`. Below is my `Dockerfile`:
```
FROM debian:stretch

RUN apt-get update && \
    apt-get install -y \
    apt-transport-https \
    lsb-release \
    ca-certificates \
    curl \
    git \
    zip \
    unzip \
    sudo \
    wget

ADD https://packages.sury.org/php/apt.gpg /etc/apt/trusted.gpg.d/php.gpg
RUN sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
RUN chmod 664 /etc/apt/trusted.gpg.d/php.gpg

RUN apt-get update && \
    apt-get install -y \
    php7.2-fpm \
    php7.2-cli \
    php7.2-mysql \
    php7.2-mbstring \
    php7.2-json \
    php7.2-sqlite3 \
    php7.2-xml

RUN php -i
COPY ./composer-dl.sh /composer-dl.sh
RUN chmod +x /composer-dl.sh && \
    /composer-dl.sh

RUN php -v && \
    git --version && \
    composer --version
```

As mentioned above code, I run `composer-dl.sh` which contains:
```
#!/bin/sh

EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_SIGNATURE="$(php -r "echo hash_file('SHA384', 'composer-setup.php');")"

if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
then
    >&2 echo 'ERROR: Invalid installer signature'
    rm composer-setup.php
    exit 1
fi

php composer-setup.php --quiet
RESULT=$?
rm composer-setup.php
exit $RESULT
```

I get the following output:

```
Step 10/11 : RUN chmod +x /composer-dl.sh &&     /composer-dl.sh
 ---> Running in fcd178496898
ERROR: Invalid installer signature
The command '/bin/sh -c chmod +x /composer-dl.sh &&     /composer-dl.sh' returned a non-zero code: 1
```

I've `echo` the `$EXPECTED_SIGNATURE` and `$ACTUAL_SIGNATURE` which they're different.

I prefer to [install programatically](https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md) because the reason what [that page](https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md) says.

**Comment by alcohol** [comment]
Maybe that documentation should be updated.

When using Composer in Docker, it is recommended to just use our container (or copy the binary FROM our container):

- https://hub.docker.com/_/composer/

Specifically:

> Note: Docker introduced multi-stage builds in 17.05:
>
> Create your own image, and copy Composer from the official image into it:
>
>```
>COPY --from=composer:1.5 /usr/bin/composer /usr/bin/composer
>```

**Comment by alcohol** [comment]
As to why you are not getting the correct signature(s), I am not sure.

**Comment by ohchiko** [comment]
Thanks! I'm using docker's composer for now. But I still wondering how that could be possible.

**Comment by gurubobnz** [comment]
I had this issue and was using this shell script https://dev.to/czarpino/installing-composer-programmatically-1bh6 to assist with installing it in a docker container.

The problem was ultimately because the `ca-certificates` package was not installed and so `curl` was unable to fetch the signature and was silently using an empty string instead.

You can verify this is the problem by using `curl -sv https://composer.github.io/installer.sig` and see if you get the message "error setting certificate verify locations", e.g.:

```
$ curl -sv https://composer.github.io/installer.sig
*   Trying 185.199.108.153:443...
* TCP_NODELAY set
* Connected to composer.github.io (185.199.108.153) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* Closing connection 0
```
