### ISSUE TITLE
implement audit command

### ISSUE THREAD

**Issue by alexander-akait** [composer/composer#7323]
My `composer.json`:

```json
{
    "name": "vendor/name",
    "description": "Description",
    "type": "project",
    "license": "MIT",
    "require": {
        "other-vendor/vulnerable-package": "~1.5",
    }
}
```

Output of `composer diagnose`:

not require, but push this

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.6.5
PHP version: 7.2.3-1ubuntu1
PHP binary path: /usr/bin/php7.2

```

When I run this command:

```
composer audit
```

I get the following output:

Nothing

And I expected this to happen:

List of vulnerable packages in `require`, `require-dev`

It would be very great to receive information about vulnerable packages using `composer` command (npm implement same command in `npm@6`). Looks like https://github.com/FriendsOfPHP/security-advisories now is best database with known vulnerable packages.

Some good feature which will be great implement with `composer audit`:
- `composer` should do audit when i install or update package(s).
- `composer audit` should exit with non zero code when find vulnerable package(s).
- `composer` should have ability to ignore some `vulnerable packages`, maybe field in `composer.json` or other file where you can point which vulnerable packages should be ignored (i.e. if `composer audit` not found vulnerable packages or found which ignored, `composer` should have zero exit code).

I know about https://github.com/sensiolabs/security-checker. But I believe that security of your package when you use `composer` is part of package manager. This would avoid many projects using vulnerable packages, as well as warn them when installing/upgrading packages.

Thanks!

**Comment by Jean85** [comment]
There is already the https://github.com/Roave/SecurityAdvisories package, which conflicts with all vulnerable packages. I think it's a better approach, since it will actively refuse to update.

**Comment by alcohol** [comment]
While the idea might sound great to you, I don't think we, the developers, are looking forward to yet more stuff to maintain that is outside of the scope of what Composer aims to provide. We're a very small team, with very little spare time. As @Jean85 already mentioned, there are community provided solutions that work just fine.

**Comment by stof** [comment]
> I can maintain this feature in future

this is the part that fails generally, unless you start reviewing PRs on the repo.

**Comment by alcohol** [comment]
Yeah, honestly, I feel like this is best left as a community solution. It can be implemented in various ways, each having their own pros and cons. I think the solution by Roave/SecurityAdvisories is quite elegant. But one could also write a plugin that does something similar.

**Comment by evilebottnawi** [comment]
@alcohol problem with using `security-check`: I was trying to talk about the innovations that are required by many users (`proxy`, `offline` and etc), and at all or received a rejection or just did not receive a response.
problem with using https://github.com/Roave/SecurityAdvisories: no api to ignore some deps and no information about security issue like this (https://github.com/FriendsOfPHP/security-advisories/blob/master/cakephp/cakephp/2015-11-05.yaml)

**Comment by Jean85** [comment]
@evilebottnawi the Roave package is directly generated from the issue repository that you linked, so it's the same source.

IMHO we could add a suggestion to the Roave package in the Composer docs, if we're worried about new users.

**Comment by evilebottnawi** [comment]
@sbuzonas good work, thanks! It is working solution? I can implement READ and other stuff, can you send invite?

**Comment by evilebottnawi** [comment]
@sbuzonas looks composer have build-in proxy support, maybe we can use this?

**Comment by sbuzonas** [comment]
@evilebottnawi done in fancyguy/composer-security-check-plugin#7

Let's move the discussion to that repo

**Comment by prisis** [comment]
Hey :) I have created a audit command for composer
It runs on every composer install and update and it has a a audit command 

Check it out https://github.com/narrowspark/automatic-security-audit

**Comment by evilebottnawi** [comment]
@prisis good work, but  PHP >=7.2.0 is not good right now, maybe we should lower this

**Comment by prisis** [comment]
@evilebottnawi sorry but i will not lower the php version

**Comment by evilebottnawi** [comment]
@prisis how developers can use you projects if they use `7.1` (what is LTS)?

**Comment by prisis** [comment]
@evilebottnawi if you take a look on http://php.net/supported-versions.php the active support for php 7.1 will end in 28 days.

My package is just a option and i will stick with php 7.2

**Comment by evilebottnawi** [comment]
@prisis need distinguishing "Active Support Until" and "Security Support Until", if everyone will use only the latest versions and remove LTS support (include "Security Support Until") software stability will fall. Most of the time you will only spend on endless updates and resolving compatibility issues. That is why language developers make support for several years. The question is not in support PHP 5.4, 5.5 or even 5.6.

**Comment by prisis** [comment]
I will check how much work it is to change the php version to 7.1

**Comment by prisis** [comment]
So the package can now be used with php 7.1

**Comment by naderman** [comment]
Closing this in favor of https://github.com/composer/composer/issues/10329, if you have anything you'd like to add to that issue, please comment there.
