### ISSUE TITLE
Loading dependencies from secondary repo with changed global system `COMPOSER` variable.

### ISSUE THREAD

**Issue by tomFlidr** [composer/composer#7330]
I'm running command (with [global variable change](https://getcomposer.org/doc/03-cli.md#composer)):

```sh
set COMPOSER=composer.dev.json
composer update
```
...in my **application** directory, where is this **`composer.dev.json`** file:
```json
{
	"repositories": [{
		"packagist.org": false
	},{
		"type": "vcs",
		"url": "../../../packages/mvccore/ext-view-helper-assets"
	}],
	"require": {
		"php": ">=5.4.0",
		"mvccore/ext-view-helper-assets": "dev-master"
	},
	"minimum-stability": "dev"
}
```
There is another **`composer.dev.json`** in directory **`../../../packages/mvccore/ext-view-helper-assets`** looking like this:
```json
{
	"name": "mvccore/ext-view-helper-assets",
	"type": "library",
	"repositories": [{
		"packagist.org": false
	},{
		"type": "vcs",
		"url": "../../../packages/mvccore/ext-view-helper"
	}],
	"require": {
		"php": ">=5.4.0",
		"mvccore/ext-view-helper": "dev-master"
	},
	"minimum-stability": "dev"
}
```
And there is also another **`composer.json`** in directory **`../../../packages/mvccore/ext-view-helper-assets`** looking like this:
```json
{
	"name": "mvccore/ext-view-helper-assets",
	"type": "library",
	"require": {
		"php": ">=5.4.0",
		"mvccore/ext-view-helper": "^4.3.1"
	},
	"minimum-stability": "stable"
}
```
I get the following output:
```
Loading composer repositories with package information 
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages. 

	Problem 1
	- Installation request for mvccore/ext-view-helper-assets dev-master -> satisfiable by mvccore/ext-view-helper-assets [dev-master].
	- mvccore/ext-view-helper-assets dev-master requires mvccore/mvccore ^4.3.1 -> satisfiable by mvccore/mvccore[v4.3.1] but these conflict with your requirements or minimum-stability.
```

I expect to happen, that if I change `composer.json` to `composer.dev.json` by shell command `set COMPOSER=composer.dev.json`, that I change every occurance where is used `composer.json` string to load or process or save `composer.json` file inside composer. Not just only for the first `composer.json` file loading process, when is loaded `composer.dev.json` in my application. 
I expect, that dependencies for repository `mvccore/ext-view-helper-assets` will be loaded also from file `composer.dev.json` file, because I changed the **`global`** variable in my system. 
Is that expectable for my only or for everybody?

**Comment by alcohol** [comment]
Your expectations cannot be met. The `COMPOSER` variable only applies to the root project. For other dependencies we always use the default `composer.json` since that is the convention.

**Comment by tomFlidr** [comment]
Okay, I will try to explain, why I need a different value for `COMPOSER` global variable first
maybe later will be much clear why I'm doing this.

I'm developing a set of libraries. Some libraries from the set have to be sometimes connected together to work properly and sometimes, it could work separately. In the same way like Zend framework or any other:
 - `zendframework/zend-code` requires `zendframework/zend-stdlib`
 - `zendframework/zend-stdlib` requires `zendframework/zend-coding-standard`
 - `zendframework/zend-coding-standard` requires nothing else from `zendframework/*`
 - ...

But new version of my libraries set is very very different with libraries set dependencies between each other and I need a way how to develop and test everything comfortably and fast. But there are very very many libraries in the set. So everytime I need to fix something or change something in one library, I need to commit, push, wait for bussy packagist.org, update composer in all tests, demos and applications, where the changed libraary is used and where I develop the libraries set.
So much better solution for me is to use composer with `path` repositories option, something like this:

`composer.json` in my application:

```
	"repositories": [{
		"packagist.org": false
	},{
		"type": "path",
		"url": "../../../packages/mvccore/mvccore"
	},{
		"type": "path",
		"url": "../../../packages/mvccore/ext-view-helper-assets"
	}],
	"require": {
		"php": ">=5.4.0",
		"mvccore/mvccore": "dev-master",
		"mvccore/ext-view-helper-assets": "dev-master"
	},
```

`composer.json` in `"mvccore/ext-view-helper-assets"` extension:
```
	"repositories": [{
		"packagist.org": false
	},{
		"type": "path",
		"url": "../../../packages/mvccore/mvccore"
	},{
		"type": "path",
		"url": "../../../packages/mvccore/ext-view-helper"
	}],
	"require": {
		"php": ">=5.4.0",
		"mvccore/mvccore": "dev-master",
		"mvccore/ext-view-helper": "dev-master"
	},
```

`composer.json` in `"mvccore/ext-view-helper"` extension:
```
	"repositories": [{
		"packagist.org": false
	},{
		"type": "path",
		"url": "../../../packages/mvccore/mvccore"
	}],
	"require": {
		"php": ">=5.4.0",
		"mvccore/mvccore": "dev-master"
	},
```


But I don't want to put this into `composer.json`, so I made everywhere `composer.dev.json`.
When I need to do any change, I can just change something in libraries set and all tests, demos and 
applications has created symlinks by the composer, so the change is everywhere imediatelly.
If I neet to add any file, I need only to commit it into library repository from my framework set and run:
```
set COMPOSER=composer.dev.json
composer update
```
And I need to load dependencies for sub-libraries in set (in second and third dependencies) also by `composer.dev.json`
to keep this working. That's why I thing the global variables are. 

So Should be better to look for `composer.dev.json` from `COMPOSER` global variable first, 
if `COMPOSER` global variable has some special value and if the file`composer.dev.json` 
doesn't exists, then to load standard `composer.json` file?

**Comment by alcohol** [comment]
We simply do not support such complex scenarios and workflows.

You can look into defining path repositories in your global composer.json on your development machine.

You can consider defining all your dependencies **and sub-dependencies** and their custom repository definitions in your main project root `composer.dev.json` and then the problem could also be alleviated perhaps.

But changing the behavior of the `COMPOSER` environment variable is not likely to happen.

**Comment by tomFlidr** [comment]
Okay, thank you for your answer, I'll try to define path repos in my global composer..dev.json placed in the first level in the demo application, it could work. Thank you for your patience and I wish everything good.
Good bye.

**Comment by stof** [comment]
Thus, repositories are root-only, so they get ignored in the composer.json of your dependencies anyway.
