### ISSUE TITLE
Upgrade Symfony 2. to 3 using path

### ISSUE THREAD

**Issue by nirvo** [composer/composer#7346]
Hi,
I am looking how to upgrade the framework Symfony 2.8 to 3.4 using local deposit (directory) because my development environment doesn't have access to internet.

I've followed https://getcomposer.org/doc/05-repositories.md#path

I download Symfony 3.4 and deposit it in the same directory as Symfony 2.8
```
\Frameworks
    \Symfony-2.8
    \Symfony-3.4
```
My `composer.json` (Symfony 2.8):
```
"repositories": [
		{ "packagist": false },
		{
			"type": "path",
			"url" : "../symfony3-4/",
			"options": {
                                         "symlink": false
                        }
		}
	],
	"require": {
		"symfony/symfony": "3.4.*"
         },
```
When I run this command:
`Composer update`

I get this error :
```
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - The requested package symfony/symfony 3.4.* exists as symfony/symfony[v2.8.32] but these are rejected by your constraint.
```

**Comment by nirvo** [comment]
Hello,
Any suggestion ?

**Comment by sbuzonas** [comment]
Your path doesn't match your directory.

Your directory list shows `\Frameworks\Symfony-3.4`. Your path repository points to `../symfony3-4/`

Try using `../Symfony-3.4/`
