### ISSUE TITLE
Autoload optimizer violates PSR-4 and changes autoloading algorithm

### ISSUE THREAD

**Issue by and800** [composer/composer#7352]
When composer optimizes loading of files under PSR-4 root, it does not check correspondence between directory paths and namespaces. So if developer makes a mistake and puts php file in wrong directory, the application behaves differently when optimized and when not optimized.

I am not completely sure if we have to implement this. At first, this issue may be classified as "undefined behavior" and it isn't Composer's fault. Also it would be a breaking change for projects relying on this bug.  
But It's very productive when my tools help me to find errors on early stage, not hide them.

Composer version: 1.6.5

My directory layout:
```
src
|---BadDirectory
|   |---Example.php
composer.json
test.php
```

composer.json:
```json
{
    "autoload": {
        "psr-4": {
            "and800\\Example\\": "src/"
        }
    }
}

```

Example.php:
```
<?php
namespace and800\Example;
class Example {}
```

test.php
```
<?php
include __DIR__ . '/vendor/autoload.php';
new and800\Example\Example();
echo "autoload succeed";
```

When I run this command:

```
$ composer install && php test.php
$ composer install -o && php test.php
```

I get the following output:

```
PHP Fatal error:  Uncaught Error: Class 'and800\Example\Example' not found in /tmp/ctest/test.php:3
autoload succeed
```

And I expected this to happen:
```
PHP Fatal error:  Uncaught Error: Class 'and800\Example\Example' not found in /tmp/ctest/test.php:3
PHP Fatal error:  Uncaught Error: Class 'and800\Example\Example' not found in /tmp/ctest/test.php:3
```

**Comment by ameenross** [comment]
> but classmap autoloading instead

You're using classmap for autoloading, not classmap instructions for generating a class map. You're instructing Composer to use PSR-4 for a certain tree, not to search said tree for any and every class that can be found.

Also, the algorithm is naive. Let's say I have this:

```json
{
  "autoload": {
    "psr-4": {
      "App\\": "app/"
    }
}
```
Then I have 2 classes with FQCN `App\SomeClass` in different directories. Obviously, only 1 of the 2 can appear in the classmap, and it does. However, the other class (which one is not clear) is ignored and can thus not be used. Composer doesn't complain.

**Comment by alcohol** [comment]
Sure, I understand that. But should you not have already identified those issues yourself through basic tests and/or during development? I am usually in favor of building in features and safeguards that make development workflows more convenient or easier. But making it completely idiot proof is a bit outside of that scope in my humble opinion. Cause then it becomes almost impossible to draw the line considering how 'creative' people can be when it comes to making mistakes.

**Comment by ameenross** [comment]
> Then you clearly have not actually attempted to run your scenario.

You can be sure that I have. I should have been more clear: the CLI shows a warning, but it happily continues generating the classmap and eventually completes successfully.

**Comment by and800** [comment]
> But should you not have already identified those issues yourself through basic tests and/or during development?

The developer who made a mistake compiles `autoload.php` with `-o` flag. The build system, which ships the code to production, doesn't use `-o` flag. That path hasn't been covered by tests and noone noticed it during code review.

That scenario is roughly similar to that which made me to open that issue. It shows some serious flaws in our working process, but I cannot call that completely idiotic

**Comment by stof** [comment]
> The build system, which ships the code to production, doesn't use `-o` flag.

I would consider it a bug of the build system to be honest :smile: Production is precisely the place where you should be using optimized mode.

**Comment by and800** [comment]
> I would consider it a bug of the build system

Of course it is. But even ops tend to make mistakes :)  
So that how we can get broken build, without any single warning and error during build time

**Comment by ameenross** [comment]
In my case I ran into this because a project has optimization enabled in the `composer.json`. A colleague made classed with non-matching namespace and directory. This behaviour of composer was unknown to us, so we basically relied on Composer to know whether the FQCN was correct: if the autoloader finds it, it's correct.

That turns out to be false now.

**Comment by alcohol** [comment]
I suppose a `--strict` flag or something could be added if the there really is such a need. But the current default implementation cannot be changed as that would be a BC. Feel free to submit a PR.

**Comment by Seldaek** [comment]
I'd rather not have an additional flag for this. If we implement it I feel like it should be the default (and only) behavior. It definitely should be mentioned in the release notes as it's a possible issue for people relying on the bug, but optimized autoloader really shouldn't be used in development IMO and strictly speaking it'd be a bug fix so I wouldn't say it's a BC break.

**Comment by alcohol** [comment]
What exactly should be implemented then though? Ignore any classes that do not actually match the specified autoload format under which we expected to find them?

Perhaps the `diagnose` command could also be expanded to hint at such mistakes and urge to correct them.

**Comment by Seldaek** [comment]
Yes I'd say while parsing psr-0/4 records as classmap, ignore any class that is not in its valid psr-0/4 path. Possibly with a warning to highlight the issue. I think it really comes down to how easy it is to implement. If it adds too much cruft or slows down optimized dumping too much I'd say it's not worth it as it doesn't seem to be a very common issue.

**Comment by zorji** [comment]
I also have a related issue. Both my project and the library depended on have the class with the exact same name. When I was using non-optimised version, it loads the class from my project which is what I want. However, when I use autoload optimise, it uses the library version. The library uses PSR-0 and my project uses PSR-4. It wasn't an issue when my project and the library both uses PSR-0.

Project `composer.json`:

```json
{
  "autoload": {
    "psr-4": {
      "SomeName\\Util\\": "Util/"
    }
}
```

Library `composer.json`:

```json
{
  "autoload": {
    "psr-0": {
      "SomeName\\Util\\": "src/"
    }
}
```

**Comment by Seldaek** [comment]
If you want to override a library's rules the best is to define a more specific namespace like `SomeName\Util\Foo` if you can. But I thought PSR-4 should win over PSR-0 anyway. Maybe that's not the case in the optimized autoloader case.

**Comment by zorji** [comment]
@Seldaek I checked `autoload dump`, it only generates class map for PSR-0 but not PSR-4. So this made PSR-0 takes higher priority.

**Comment by and800** [comment]
>  it only generates class map for PSR-0 but not PSR-4
no, it also generates for PSR-4 too, just the variables have confusing names there :)

**Comment by and800** [comment]
> ignore any class that is not in its valid psr-0/4 path. Possibly with a warning to highlight the issue.

@Seldaek I think there must be no warning, othervise it will be triggered for every file that has more than one class inside, which is generally not bad :thinking:

**Comment by stof** [comment]
@and800 we could skip the warning if the matching PSR class is found in the file (and register only that class in the classmap), but still display violations for other cases.
