### ISSUE TITLE
Composer installation error on Windows 10

### ISSUE THREAD

**Issue by MOLAKANM71** [composer/composer#7353]
The Composer installer script did not run correctly [exit code 1]:

PHP Warning:  realpath(): open_basedir restriction in effect. File(C:\Users\User\AppData\Local\Temp\is-N6RLR.tmp) is not within the allowed path(s): (c:/winnmp) in C:\Users\User\AppData\Local\Temp\is-N6RLR.tmp\installer.php on line 626
PHP Warning:  is_writeable(): open_basedir restriction in effect. File(C:\Users\User\AppData\Local\Temp\is-N6RLR.tmp) is not within the allowed path(s): (c:/winnmp) in C:\Users\User\AppData\Local\Temp\is-N6RLR.tmp\installer.php on line 628

I don't know what to do have google noting and I can't find "N6RLR.tmp\installer.php" on my system
Pls, Help.
Thanks

**Comment by johnstevenson** [comment]
You need to comment out the `open_basedir` ini setting: https://php.net/manual/en/ini.core.php#ini.open-basedir

**Comment by johnstevenson** [comment]
Have you done what I suggested?

**Comment by MOLAKANM71** [comment]
don't understand it

**Comment by johnstevenson** [comment]
Google for `php.ini` (the configuration file) and `open_basedir` (the setting that needs changing). Sorry, but you really need to grasp the basics yourself.

**Comment by MOLAKANM71** [comment]
@johnstevenson is still giving me the same error. "The Composer installer script did not run correctly [exit code 1]:

PHP Warning:  realpath(): open_basedir restriction in effect. File(C:\Users\User\AppData\Local\Temp\is-DHM6T.tmp) is not within the allowed path(s): (/var/www/htdocs/:/var/www/tmp/) in C:\Users\User\AppData\Local\Temp\is-DHM6T.tmp\installer.php on line 626
PHP Warning:  is_writeable(): open_basedir restriction in effect. File(C:\Users\User\AppData\Local\Temp\is-DHM6T.tmp) is not within the allowed path(s): (/var/www/htdocs/:/var/www/tmp/) in C:\Users\User\AppData\Local\Temp\is-DHM6T.tmp\installer.php on line 628" I think i need to work on installation.php script.

**Comment by alcohol** [comment]
@MOLAKANM71 please read http://php.net/manual/en/ini.core.php#ini.open-basedir

**Comment by mlocati** [comment]
@MOLAKANM71 You need to edit the PHP configuration.
This configuration is stored in a file named `php.ini`
To determine the full path of the `php.ini` file, open a command prompt and type the following command:
```bat
php --ini
```
Then edit that file with a text editor (for example with [Notepad++](https://notepad-plus-plus.org/)), and remove the line that starts with `open_basedir`.

@didox12345 Composer is a PHP script, so the architecture of your operating system is totally irrelevant.

**Comment by zoglun** [comment]
Hi there,

@MOLAKANM71 I got exact same error as you, when installing composer with WinNMP. I do comment out open_basedir in php.ini but still receiving error message. 
It eventually turns out that restart the windows system solve the error in "C:\Users\User\AppData\Local\Temp\is-xxxxx.tmp\installer.php" .

Hope this solution can help others!

**Comment by n0099** [comment]
#680
