### ISSUE TITLE
Dependency resolution on local packagist

### ISSUE THREAD

**Issue by bseddon** [composer/composer#7354]
The documentation states in several places that nested respository dependencies will not be resolved.  However this is not the case for libraries hosted on packagist.com.  When a library hosted on packagist.com specifies required dependent libraries composer will resolve any implied dependencies.  

For example  when [pear/log](https://packagist.org/packages/pear/log) is installed to an app using a composer.json like;

```
{
   "requires" :  { "pear/log": ">1.13" }
}
```

composer will install the log library **and also** the required pear/pear_exception library.  That is, it resolves the dependency and installs it.  I would like to benefit from required dependency resolution.

The [documentation](https://getcomposer.org/doc/05-repositories.md#composer) says of the 'composer' repository type: "This is also the repository type that packagist uses. To reference a composer repository, supply the path before the packages.json file. In the case of packagist, that file is located at /packages.json..."

So I have created a packages.json file for our internal libraries hoping that, then, composer will identify and install implied dependencies.  Using the packages.json I am able to install the libraries if all the libraries are specified in an application composer.json like this:

```
{
    "repositories": [
        {
            "type": "composer",
            "url": "file:///<directory path to folder containing packages.json>"
        }],
    "require": {
		"lyquidity/xml" : "dev-master",
		"lyquidity/utilities" : "dev-master",
		"lyquidity/XPath2" : "dev-master",
		"lyquidity/XBRL" : "dev-master"
	}
}
```

This indicates that the structure of my packages.json is correct and composer can use it. However, what I'd like to do is be able to use a composer.json like this:

```
{
    "repositories": [
        {
            "type": "composer",
            "url": "file:///<directory path to folder containing packages.json>"
        }],
    "require": {
		"lyquidity/XBRL" : "dev-master"
	}
}
```

The composer.json of the XBRL library and its definition in packages.json both specify the other three libraries (xml, utilities and XPath2) as required dependencies so my hope is that by using the same sort of package definition used by packagist.org I will be able to benefit from dependency resolution but it does not work for me.  Instead I see this message:

```
  Problem 1
    - Installation request for lyquidity/xbrl dev-master -> satisfiable by lyquidity/XBRL[dev-master].
    - lyquidity/XBRL dev-master requires lyquidity/utilities dev-master -> no matching package found.
```
Am I barking up the wrong tree or is there something else I should be doing to have composer install dependencies automatically.  

Interestingly, although the pear/log library is not explicitly defined in the app composer.json above, composer does resolve this as a dependency *it is required by all our libraries) and installs it from packagist.org.  

For completeness, here is my packages.json:

```
{
    "packages": {
        "lyquidity/utilities": {
            "dev-master": { 
				"name": "lyquidity/utilities",
				"version" : "dev-master",
				"description": "Utility classes to provide a tuple dictionary and to convert a simple XML class to an array",
				"dist": {
                    "url": "file:///<path to packages folder>/utilities.zip",
                    "type": "zip"
                },
				"type": "library",
				"homepage": "https://github.com/lyquidity/utilities",
				"license": "GPL version 3.0",
				"authors": [
					{
						"name": "Bill Seddon",
						"homepage": "https://github.com/orgs/lyquidity/people/bseddon"
					}
				],
				"repositories": [
					{
						"type": "composer",
						"url": "file:///<path to packages.json folder>/"
					}
				],
				"require": {
					"php": "^7.0",
					"pear/log": ">1.13",
					"lyquidity/xml" : "dev-master"
				},
				"autoload": {
					"files": [ 
						"./tuple-dictionary.php",
						"./SimpleXMLElementToArray.php"
					]
				}
			}
        },
        "lyquidity/xml": {
            "dev-master": {
				"name": "lyquidity/xml",
				"version" : "dev-master",
				"description": "Reads XML Schema documents (.xsd) files and extracts type information for PHP",
				"dist": {
                    "url": "file:///<path to packages folder>/xml.zip",
                    "type": "zip"
                },
				"keywords": ["lyquidity", "xml", "schema"],
				"type": "library",
				"homepage": "https://github.com/lyquidity/xml",
				"license": "GPL version 3.0",
				"authors": [
					{
						"name": "Bill Seddon",
						"homepage": "https://github.com/orgs/lyquidity/people/bseddon"
					}
				],
				"require": {
					"php": "^7.0",
					"pear/log": ">1.13"
				},
				"autoload": {
					"files": [ "./bootstrap.php" ]
				}
			}
        },
        "lyquidity/XPath2": {
            "dev-master": { 
				"name": "lyquidity/XPath2",
				"version" : "dev-master",
				"description": "Reads XML Schema documents (.xsd) files and extracts type information for PHP",
				"dist": {
                    "url": "file:///<path to packages folder>/XPath2.zip",
                    "type": "zip"
                },
				"keywords": ["lyquidity", "xml", "xpath 2.0"],
				"type": "library",
				"homepage": "https://github.com/lyquidity/XPath2",
				"license": "GPL version 3.0",
				"authors": [
					{
						"name": "Bill Seddon",
						"homepage": "https://github.com/orgs/lyquidity/people/bseddon"
					}
				],
				"require": {
					"php": "^7.0",
					"pear/log": ">1.13",
					"lyquidity/xml" : "dev-master"
				},
				"autoload": {
					"psr-4": { "lyquidity\\XPath2\\" : "./" }
				}
			}
        },
        "lyquidity/XBRL": {
            "dev-master": { 
				"name": "lyquidity/XBRL",
				"version" : "dev-master",
				"description": "Classes that implement the XBRL 2.1, XDT, Formulas, Generics and XFI specifications",
				"dist": {
                    "url": "file:///<path to packages folder>/source.zip",
                    "type": "zip"
                },
				"keywords": ["lyquidity", "XBRL", "Dimensions", "Formulas"],
				"type": "library",
				"homepage": "https://github.com/lyquidity/XBRL",
				"license": "GPL version 3.0",
				"authors": [
					{
						"name": "Bill Seddon",
						"homepage": "https://github.com/orgs/lyquidity/people/bseddon"
					}
				],
				"require": {
					"php": ">=7.0",
					"pear/log": ">1.13",
					"lyquidity/utilities" : "dev-master",
					"lyquidity/xml" : "dev-master",
					"lyquidity/XPath2" : "dev-master"
				},
				"autoload": { "files": ["./XBRL.php"] }
			}
        }
    }
}
```

**Comment by Seldaek** [comment]
Just to make things clear, *dependencies* are always resolved recursively. Only the "repositories" key of dependencies is not loaded recursively.

As for your problem, it seems to stem from the fact you're using dev-master releases, and not allowing a minimum-stability value of `dev`, so it can't find those releases. The root package defines the allowed stability for all packages. By hoisting the dev-master requires to the root composer.json you're effectively whitelisting these packages to be allowed in dev stability as well. That's why it "fixes" it.
