### ISSUE TITLE
still can't create project using composer

### ISSUE THREAD

**Issue by alvaro-lima** [composer/composer#7355]
composer -vvv create-project --prefer-dist cakephp/app vis

Installing cakephp/app (3.6.1)
  - Installing cakephp/app (3.6.1): Reading /home/alvaro/.cache/composer/files/cakephp/app/c8d3da2f103e036c77db16a61d6cad3870d986d1.zip from cache
Loading from cache
 Extracting archiveExecuting command (CWD): unzip -qq  'vis//564001695dbbca790ce66f06798719ce' -d '/opt/lampp/htdocs/vendor/composer/e9d6dc2e'
Created project in vis

  [InvalidArgumentException]
  Composer could not find a composer.json file in /opt/lampp/htdocs/vis
  To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

Exception trace:
 () at phar:///opt/lampp/bin/composer/src/Composer/Factory.php:287
 Composer\Factory->createComposer() at phar:///opt/lampp/bin/composer/src/Composer/Factory.php:576
 Composer\Factory::create() at phar:///opt/lampp/bin/composer/src/Composer/Command/CreateProjectCommand.php:164
 Composer\Command\CreateProjectCommand->installProject() at phar:///opt/lampp/bin/composer/src/Composer/Command/CreateProjectCommand.php:145
 Composer\Command\CreateProjectCommand->execute() at phar:///opt/lampp/bin/composer/vendor/symfony/console/Command/Command.php:242
 Symfony\Component\Console\Command\Command->run() at phar:///opt/lampp/bin/composer/vendor/symfony/console/Application.php:843
 Symfony\Component\Console\Application->doRunCommand() at phar:///opt/lampp/bin/composer/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at phar:///opt/lampp/bin/composer/src/Composer/Console/Application.php:251
 Composer\Console\Application->doRun() at phar:///opt/lampp/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///opt/lampp/bin/composer/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar:///opt/lampp/bin/composer/bin/composer:59
 require() at /opt/lampp/bin/composer:24

**Comment by alvaro-lima** [comment]
this is getting frustrating..

**Comment by Seldaek** [comment]
We'll need more details if you want any assistance here. The error you get makes no sense to me, as the composer.json exists in the project you're installing. It's probably due to something going wrong in your environment.
