### ISSUE TITLE
Document Composer's own versioning policy

### ISSUE THREAD

**Issue by sampablokuper** [composer/composer#7356]
Thanks for maintaining Composer :+1:

Does Composer _itself_ follow Semantic Versioning (aka SemVer)? If not, what guarantees, if any, of backwards compatibility does Composer make?

These matters do not appear to have been documented. (If I am mistaken, please correct me by linking to the relevant part of the documentation.)

If they have not been documented, then they should be added to the documentation.

**Comment by alcohol** [comment]
We try to follow Semver to the best of our ability. Not sure since when, but it has been the case for quite a long time already. This is not explicitly mentioned or documented anywhere to my knowledge.

**Comment by Seldaek** [comment]
If you have a suggestion as to where to document that please do send a PR :) Yes we try to follow semver to the best of our abilities. IMO it's kinda the obvious expectation for a package manager, but it doesn't hurt to specify.

**Comment by sampablokuper** [comment]
@Seldaek wrote:
> Yes we try to follow semver to the best of our abilities.

I meant to ask above: which version of SemVer?

> IMO it's kinda the obvious expectation for a package manager, but it doesn't hurt to specify.

Exactly.

> If you have a suggestion as to where to document that please do send a PR :) 

[Done](https://github.com/composer/composer/pull/7382). I've assumed SemVer 2.0.0, but either I or a Composer maintainer can amend the pull request if Composer is using a different version of SemVer version.
