### ISSUE TITLE
Composer archive should not read ignore files (gitignore, hgignore, ...)

### ISSUE THREAD

**Issue by naderman** [composer/composer#7358]
Composer archive currently reads ignore files and excludes these files/directories from generated zip files. This behaviour is not correct since ignored directories should only be ignored for commiting changes. They may very well exist in the repository anyway and should be included in the resulting zip file, too.

To skip files or directories when generating the zip file other mechanisms ought to be used. For git one should use git attributes to exclude directories from export. Composer should only take these settings into account. We could see what alternatives there are for other VCS systems or whether there should be a way to define such an exclusion list in composer.json.

**Comment by stof** [comment]
> For git one should use git attributes to exclude directories from export.

gitattributes allows you to ignore *extra* files from the archive. they don't allow you to bring files in the archive if they were not part of the repo.

**Comment by naderman** [comment]
@stof That's not what I was saying? Not sure what your point is?

**Comment by sbuzonas** [comment]
IIRC you can negate a rule in `export-ignore` of `.gitattributes` as well as in the `composer.json`.

**Comment by naderman** [comment]
Again not sure what that adds to the issue here. We're trying to get the same results as the zip files generated on github for example, or by a git archive, neither of them take gitignore into account, so neither should we.

**Comment by sbuzonas** [comment]
> or whether there should be a way to define such an exclusion list in composer.json.

My remark was that there is a way to define it in composer.json. And there are current workarounds to achieve the desired behavior.

The edit stating that it makes more sense was in agreement with disregarding .gitignore.

**Comment by unglud** [comment]
Why you have files in repo AND in .gitignore? Sounds strange for me. Could you please give an example or use case? Thank you.

**Comment by sbuzonas** [comment]
@unglud not in the repo and gitignore, but inclusion of files in the working tree that are ignored in the repo such as generated files
