### ISSUE TITLE
repositories with type path are ignored for dependencies

### ISSUE THREAD

**Issue by vertexvaar** [composer/composer#7359]
Foreword: The packages used in this example are not available on packagist on purpose. They reside in a local folder called "repo". Please have a look in the provided ZIP.

My `composer.json`:

```json
{
    "name": "vertexvaar/local_dependency",
    "description": "Project which demonstrates a bug with two local repos",
    "type": "project",
    "repositories": [
        {
            "type": "path",
            "url": "repo/*"
        }
    ]
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.vertexvaar/dependency : unbound version constraints (dev-master) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Composer version: 1.6.3
PHP version: 7.2.5-0ubuntu0.18.04.1
PHP binary path: /usr/bin/php7.2
```

When I run this command:

```
composer require vertexvaar/main_package=dev-master
```

I get the following output:

```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for vertexvaar/main_package dev-master -> satisfiable by vertexvaar/main_package[9999999-dev].
    - vertexvaar/main_package 9999999-dev requires vertexvaar/dependency ^1.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

And I expected this to happen:
I expect vertexvaar/main_package to be installed just like vertexvaar/dependency which was already successfully symlinked to the vendor folder.

Both packages can be installed on their own (if i remove `vertexvaar/dependency` from the `require` section of `vertexvaar/main_package`)

It seems that composer does not respect `repositories` with type "path" when searching for dependencies. I can also reproduce this with packages available on packagist but wanted to provide the smallest possible setup.

[example.zip](https://github.com/composer/composer/files/2018189/example.zip)

**Comment by alcohol** [comment]
Your problem is that your packages require a tagged version, and your path repos don't offer those.

**Comment by vertexvaar** [comment]
Should i be able to override the required versions in the root composer.json?
I would expect composer to install both packages in the required version if i had defined them there.

Putting both packages with the dev-master version requirement into the root composer.json doesn't work either.

**Comment by alcohol** [comment]
That's because while your root package might require both as dev-master, individually  your main package will still require dependency to match `^1.0`.

**Comment by alcohol** [comment]
@stof he isn't using repository definitions in his path repos though.

**Comment by vertexvaar** [comment]
I added a branch-alias to the dependency and it worked. However i couldn't figure out why it does not work with my real issue where the branch-alias are set and everything is kinda the same. I will continue digging into this and keep you informed
