### ISSUE TITLE
Composer doesn't autoload classes on Ubuntu 18.04

### ISSUE THREAD

**Issue by Obitox** [composer/composer#7362]
Composer doesn't autoload any of my classes, I am using Xampp to run my project and I am on Ubuntu 18.04, when I run my index.php using xampp I get the following output:
`Fatal error: Uncaught Error: Class 'App\Core\DatabaseConfiguration' not found in /opt/lampp/htdocs/pivt/index.php:9 Stack trace: #0 {main} thrown in /opt/lampp/htdocs/pivt/index.php on line 9`
I have tried countless things, from reinstalling my composer on all ways I could find on official site and Stackoverflow, checked my project structure countless times along with my teacher who doesn't have any clue either, giving all privileges to composer although it's not advised, giving all privileges to files and folders in my project and I just can't seem to find any solution to my problem. My friend who is using Windows 10 and has done exactly the same configuration for composer as I did doesn't get this error. Is there something I can try to make composer work because I really need composer for my project?

My `composer.json`:
{
    "name": "pivt/pivt",
    "description": "Chinese restaurant",
    "type": "project",
    "require": {
        "twig/twig": "^2.4"
    },
    "psr-4": { "App\\": "" }	
}

Output of `composer diagnose`:
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.6.5
PHP version: 7.2.4
PHP binary path: /opt/lampp/bin/php-7.2.4

My index.php:
```
<?php
    require_once 'vendor/autoload.php';

    use App\Core\DatabaseConfiguration;
    use App\Core\DatabaseConnection;

    $dbConfig = new DatabaseConfiguration(
        'localhost', 
        'root',
        '',
        'fastfood_db');
    $dbCon = new DatabaseConnection($dbConfig);

    $url = strval(filter_input(INPUT_GET, 'url'));
    $httpMethod = filter_input(INPUT_SERVER, 'REQUEST_METHOD');

    $router = new \App\Core\Router();
    $routes = require_once 'routes.php';
    ```
    foreach ($routes as $route) {
        $router->add($route);
    }

    $route = $router->find($httpMethod, $url);
    $argumenti = $route->getArguments($url);

    $controllerName     = $route->getControllerName();
    $controllerFullName = '\\App\\Controllers\\' . $controllerName .  'Controller';
    $methodName         = $route->getMethodName();
    

    $worker = new $controllerFullName($dbCon);
	call_user_func_array([$worker, $methodName], $argumenti);

    $data = $worker->getData();

    $loader = new Twig_Loader_Filesystem("./views");
    $twig = new Twig_Environment($loader, [
        "cache"       => "./twig-cache",
        "auto_reload" => true
    ]);

    $data['BASE'] = Configuration::BASE;

    echo $twig->render($controllerName.'/'.$methodName.'.html', $data);
```

**Comment by dvikan** [comment]
try `"psr-4": { "App\": "" }` then dump autoloader.

**Comment by Obitox** [comment]
Thank you for your answer, but it still doesn't work, I have modified my composer.json and did dump-autoload inside my project folder but still i get the same error, this is my composer.json now:
```
{
    "name": "pivt/pivt",
    "description": "Chinese restaurant",
    "type": "project",
    "require": {
        "twig/twig": "^2.4"
    },
    "autoload": {
        "psr-4": {
            "App\\": ""
        }
    }	
}
```
And still I get this error:
`Fatal error: Uncaught Error: Class 'App\Core\DatabaseConfiguration' not found in /opt/lampp/htdocs/pivt/index.php:7 Stack trace: #0 {main} thrown in /opt/lampp/htdocs/pivt/index.php on line 7`

**Comment by xabbuh** [comment]
Where exactly is the `DatabaseConfiguration.php` file located?

**Comment by Obitox** [comment]
![selection_001](https://user-images.githubusercontent.com/26469778/40355830-bb27a870-5db7-11e8-87d1-1e6d1e578ebd.jpg)
Here is the full hierarchy of my project.

**Comment by stof** [comment]
you have an issue, `core` on filesystem vs `Core` in namespace of the class you try to use. If your filesystem is case-sensitive, Composer will look for a `Core` folder, and will not find it.

**Comment by Obitox** [comment]
![selection_003](https://user-images.githubusercontent.com/26469778/40356714-37e90a32-5dba-11e8-8c4c-4e0eb29a827a.jpg)
Still the same :(
`Fatal error: Uncaught Error: Class 'App\Core\DatabaseConfiguration' not found in /opt/lampp/htdocs/pivt/index.php:7 Stack trace: #0 {main} thrown in /opt/lampp/htdocs/pivt/index.php on line 7`

**Comment by stof** [comment]
Can you also show your `DatabaseConfiguration.php` file ?

**Comment by Obitox** [comment]
![selection_004](https://user-images.githubusercontent.com/26469778/40357227-c7b269fa-5dbb-11e8-8648-f55df2b2cfa6.jpg)

**Comment by stof** [comment]
hmm, I don't have any idea here. The class declaration is fine, the composer autoloading config should be fine.

**Comment by Obitox** [comment]
Important thing that I must add is that I have the same configuration on my Windows 7 desktop PC and everything is working as it should, error with psr-4 in my composer.json was generated cause I was desperately trying to make it work somehow and I have made a mistake, my friend that is working on this project with me also has Windows, he has the same setup also and he doesn't get this error.

**Comment by alcohol** [comment]
Can you run `composer dump` (without `-o`) and see if it still fails then?

**Comment by Obitox** [comment]
YES! Finally, `composer dump` did it, works as a charm!
Thank you @dvikan @xabbuh @stof @alcohol for helping me ^_^

**Comment by stof** [comment]
Well, if you dump an optimized autoloader, you indeed have to re-dump it regularly when making changes (which is why it is not optimized by default, as it only makes sense in prod).
and if you change your autoloading config in the composer.json, you also have to dump the autoloader again (to use the new config).

**Comment by Obitox** [comment]
Makes sense now, I apologize, this was purely my mistake not understanding OS I am working on and not digging deep enough into composer documentation, I thank you kind gentleman for helping me out even with my lack of knowledge ^_^
