### ISSUE TITLE
How to - Refresh namespaces after a given action

### ISSUE THREAD

**Issue by RoySegall** [composer/composer#7363]
Hello,
Awesome project and I think this one of the best package manager out there.

I'm facing something very strange and I need some inorder to do what I want to do.

I'm managing in my database list of folders(like a Drupal module) and when I enable that folder to be active I need composer to register the new namespace.  so I created a custom autoloader file like this:
```php
<?php
/**
 * Registering the custom namespaces.
 */
/** @var \Composer\Autoload\ClassLoader $composer */
$composer = include getcwd() . '/vendor/autoload.php';
try {
  $capsule_manager = \Nuntius\Nuntius::getCapsuleManager();
  // Get the enabled capsules.
  $enabled = $capsule_manager->capsuleList('enabled');
  // Get all the capsules.
  $capsules = $capsule_manager->getCapsules();
  foreach ($enabled as $enable) {
    $capsule = $capsules[$enable];
    $path = $capsules[$enable];
    $names = explode('_', $capsule['machine_name']);
    $namespace = 'Nuntius\\' . implode('', array_map(function($item) {
        return ucfirst($item);
      }, $names));
    $composer->addPsr4($namespace . '\\', $capsule_manager->getRoot() . '/' . $path['path'] . '/src/');
  }
}
catch (Exception $e) {
}
return $composer;
```

The problem is in PHPUNIT. In PHPUNIT i'm starting the test without any folder enabled and enabling it later on. The thing is that I need to refresh the autoloader namepsaces during the test and I don't know how. The test looks like this:
```php
  /**
   * For now, disable.
   *
   * todo: release blocker.
   */
  public function testAutoloaderRegister() {
    $this->assertFalse(class_exists('\Nuntius\System\PluginDispatcher'));
    $this->capsuleService->enableCapsule('system');
    $foo = new \Nuntius\System\PluginDispatcher();
  }
```

Any ideas? Thnaks in adanved.

**Comment by alcohol** [comment]
That looks more like a system test than a unit test. Not sure how to deal with that, but this is not really the right place to be asking for help on this subject. Try stackoverflow instead :-)

**Comment by RoySegall** [comment]
Actually, I solved this one. You can see it here - https://github.com/RoySegall/nuntius-bot/pull/112/files

I used a custom spl autoload.

**Comment by Seldaek** [comment]
Yup sounds to me like generally speaking registering a second autoloader is safer than modifying the composer one :)
