### ISSUE TITLE
I have problem when install every package

### ISSUE THREAD

**Issue by ilbeygi** [composer/composer#7367]
i have this problem when install every package :
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: fai led to open stream: Connection refused

please help me !!!

OS : ubuntu 16.04

[stackoverflow](https://stackoverflow.com/questions/50449226/composer-error-when-install-package?noredirect=1#comment87939716_50449226) link

**Comment by alcohol** [comment]
Looks like a proxy or firewall issue. Please check your network/host machine.
