### ISSUE TITLE
ubuntu 16.04 : composer first install behind a corporate proxy

### ISSUE THREAD

**Issue by QuentinBibas** [composer/composer#7368]
i cannot seem to make this to work.
````
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
````

Ubuntu's composer package does not have the self-update mechanism, and the server i'm trying to deploy requires a newer composer package than the one available.
Only problem is :
I am behind a corporate proxy, and have no idea how to tell php to pass it.

i've tried things like this :
https://stackoverflow.com/questions/3892635/how-to-have-php-to-use-proxy-setting-to-connect-to-internet?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
adding php -r, trying to make a .php file with this and the above and running it...

is there any other way to get composer that doesn't involve php -r ?

**Comment by stof** [comment]
well, you can use `curl` to perform the download instead of `php -r "copy(....)`:

```bash
curl -o composer-setup.php https://getcomposer.org/installer
```

**Comment by QuentinBibas** [comment]
oh.

well, i worked around the problem, i just used
curl -sS https://getcomposer.org/installer | php
and ran with composer.phar directly into the working dir

**Comment by Seldaek** [comment]
That's a decent workaround, but at that point you can also move composer.phar to wherever `which composer` is to replace the system-wide one.
