### ISSUE TITLE
ezsystem[...] requires composer-plugin-api 1.0.0 -> no matching package found.

### ISSUE THREAD

**Issue by jejey** [composer/composer#7372]
Same issue but closed https://github.com/composer/composer/issues/2324
I tried : self-update -> up to date.
Note that I installed it with the command lines provided by the official installation guide

Thank you in advance, if you have any suggestion or question don't hesitate.
(diagnosis & composer.json at the end of the file)

**When I run this command:**
 php -d memory_limit=-1 composer.phar update symfony/icu --no-dev 
(Also tried with --no-plugins options, same output but the beginning ) 

**I get the following output:**
The "ezsystems/ezpublish-legacy-installer" plugin was skipped because it requires a Plugin API version ("1.0.0") that does not match your Composer installation ("1.1.0"). You may need to run composer update with the "--no-plugins" option.
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - ezsystems/ezpublish-legacy-installer v2.0.0 requires composer-plugin-api 1.0.0 -> no matching package found.
    - ezsystems/ezpublish-legacy-installer v2.0.0 requires composer-plugin-api 1.0.0 -> no matching package found.
    - ezsystems/ezpublish-legacy-installer v2.0.0 requires composer-plugin-api 1.0.0 -> no matching package found.
    - Installation request for ezsystems/ezpublish-legacy-installer (locked at v2.0.0) -> satisfiable by ezsystems/ezpublish-legacy-installer[v2.0.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

**And I expected this to happen:**
to update symfony icu, then to install phpunit

My `composer.json`:
{
    "name": "ezsystems/ezpublish-community",
    "description": "eZ Publish 5 community distribution",
    "homepage": "http://share.ez.no",
    "license": "GPL-2.0",
    "authors": [
        {
            "name": "eZ Publish dev-team & eZ Community",
            "homepage": "https://github.com/ezsystems/ezpublish-community/contributors"
        }
    ],
    "autoload": {
        "psr-0": { "": "src/" }
    },
    "require": {
        "php": ">=5.3.3",
        "symfony/icu": "1.0.*@dev",
        "symfony/symfony": "2.3.*",
        "twig/extensions": "1.0.*",
        "symfony/assetic-bundle": "2.3.*",
        "symfony/swiftmailer-bundle": "2.3.*",
        "symfony/monolog-bundle": "2.3.*",
        "sensio/distribution-bundle": "2.3.*",
        "sensio/generator-bundle": "2.3.*",
        "incenteev/composer-parameter-handler": "~2.0",
        "tedivm/stash-bundle": "0.3.*",
        "ezsystems/ezpublish-kernel": "2014.03.2",
        "ezsystems/ezpublish-legacy": "2014.03.1",
        "ezsystems/demobundle": "2014.03.1",
        "ezsystems/comments-bundle": "2014.03.1",
        "egulias/listeners-debug-command-bundle": "~1.9",
        "white-october/pagerfanta-bundle": "1.0.*",
        "nelmio/cors-bundle": "~1.3",
        "zetacomponents/archive": "@dev",
        "zetacomponents/authentication": "@dev",
        "zetacomponents/authentication-database-tiein": "@dev",
        "zetacomponents/cache": "@dev",
        "zetacomponents/configuration": "@dev",
        "zetacomponents/console-tools": "@dev",
        "zetacomponents/database": "@dev",
        "zetacomponents/debug": "@dev",
        "zetacomponents/event-log": "@dev",
        "zetacomponents/feed": "@dev",
        "zetacomponents/image-conversion": "@dev",
        "zetacomponents/mail": "@dev",
        "zetacomponents/mvc-tools": "@dev",
        "zetacomponents/mvc-authentication-tiein": "@dev",
        "zetacomponents/persistent-object": "@dev",
        "zetacomponents/php-generator": "@dev",
        "zetacomponents/signal-slot": "@dev",
        "zetacomponents/system-information": "@dev",
        "hautelook/templated-uri-bundle": "~1.0",
        "doctrine/doctrine-bundle": "1.2.*",
        "phpoffice/phpexcel": "^1.8",
        "phpunit/phpunit": "5.7.*"
    },
    "conflict": {
        "symfony/symfony": "2.3.9"
    },
    "require-dev": {
        "behat/behat": "2.5.*",
        "behat/symfony2-extension": "*",
        "behat/sahi-client": "dev-master as 1.1.1",
        "behat/mink-extension": "*",
        "behat/mink-goutte-driver": "*",
        "behat/mink-selenium-driver": "*",
        "behat/mink-sahi-driver": "*",
        "behat/mink-selenium2-driver": "*",
        "phpunit/phpunit": "3.7.*"
    },
    "scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "eZ\\Bundle\\EzPublishLegacyBundle\\Composer\\ScriptHandler::installAssets",
            "eZ\\Bundle\\EzPublishCoreBundle\\Composer\\ScriptHandler::dumpAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "eZ\\Bundle\\EzPublishLegacyBundle\\Composer\\ScriptHandler::installLegacyBundlesExtensions"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "eZ\\Bundle\\EzPublishLegacyBundle\\Composer\\ScriptHandler::installAssets",
            "eZ\\Bundle\\EzPublishCoreBundle\\Composer\\ScriptHandler::dumpAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "eZ\\Bundle\\EzPublishLegacyBundle\\Composer\\ScriptHandler::installLegacyBundlesExtensions"
        ]
    },
    "config": {
        "process-timeout": 3000,
        "bin-dir": "bin"
    },
    "extra": {
        "symfony-app-dir": "ezpublish",
        "symfony-web-dir": "web",
        "ezpublish-legacy-dir": "ezpublish_legacy",
        "_symfony-assets-install_comment_": "One of 'symlink', 'relative' (symlinks) or 'hard'",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "ezpublish/config/parameters.yml"
        },
        "branch-alias": {
            "dev-master": "5.3.x-dev"
        }
    }
}

Output of `composer diagnose`:
 command not found

**Output of `php composer.phar diagnose`:**
root@5f4d6763cddc:/var/www/crc/sources# php composer.phar diagnose
The "ezsystems/ezpublish-legacy-installer" plugin was skipped because it requires a Plugin API version ("1.0.0") that does not match your Composer installation ("1.1.0"). You may need to run composer update with the "--no-plugins" option.
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Checking composer.json: WARNING
License "GPL-2.0" is a deprecated SPDX license identifier, use "GPL-2.0-only" or "GPL-2.0-or-later" instead
phpunit/phpunit is required both in require and require-dev, this can lead to unexpected behavior
Defining autoload.psr-0 with an empty namespace prefix is a bad idea for performance
require.ezsystems/ezpublish-kernel : exact version constraints (2014.03.2) should be avoided if the package follows semantic versioning
require.ezsystems/ezpublish-legacy : exact version constraints (2014.03.1) should be avoided if the package follows semantic versioning
require.ezsystems/demobundle : exact version constraints (2014.03.1) should be avoided if the package follows semantic versioning
require.ezsystems/comments-bundle : exact version constraints (2014.03.1) should be avoided if the package follows semantic versioning
require.zetacomponents/archive : unbound version constraints (@dev) should be avoided
require.zetacomponents/authentication : unbound version constraints (@dev) should be avoided
require.zetacomponents/authentication-database-tiein : unbound version constraints (@dev) should be avoided
require.zetacomponents/cache : unbound version constraints (@dev) should be avoided
require.zetacomponents/configuration : unbound version constraints (@dev) should be avoided
require.zetacomponents/console-tools : unbound version constraints (@dev) should be avoided
require.zetacomponents/database : unbound version constraints (@dev) should be avoided
require.zetacomponents/debug : unbound version constraints (@dev) should be avoided
require.zetacomponents/event-log : unbound version constraints (@dev) should be avoided
require.zetacomponents/feed : unbound version constraints (@dev) should be avoided
require.zetacomponents/image-conversion : unbound version constraints (@dev) should be avoided
require.zetacomponents/mail : unbound version constraints (@dev) should be avoided
require.zetacomponents/mvc-tools : unbound version constraints (@dev) should be avoided
require.zetacomponents/mvc-authentication-tiein : unbound version constraints (@dev) should be avoided
require.zetacomponents/persistent-object : unbound version constraints (@dev) should be avoided
require.zetacomponents/php-generator : unbound version constraints (@dev) should be avoided
require.zetacomponents/signal-slot : unbound version constraints (@dev) should be avoided
require.zetacomponents/system-information : unbound version constraints (@dev) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.6.5
PHP version: 5.6.33
PHP binary path: /usr/local/bin/php

**Comment by xabbuh** [comment]
It looks like you need to update your version of the `ezsystems/ezpublish-legacy-installer` package. The requirement there was changed some time ago in ezsystems/ezpublish-legacy-installer@127643119288c6a47b8ef8bf7018c8a01cfdc788.

**Comment by xabbuh** [comment]
Ah, seems you are not requiring this package yourself. So you need to find out which package requires it in this old version and then update this too or work around it by disabling plugins during the package updates.

**Comment by jejey** [comment]
Thanks for your answer @xabbuh , I think you have the solution but I found a quicker way actually : I installed phpUnit with command lines without composer ( https://phpunit.de/manual/5.7/en/installation.html ) 
Sorry to have made you lost your time, I didn't think of it before posting my issue.. My bad !
