### ISSUE TITLE
Composer plugins throw error exceptions regardless of cli/php.ini 

### ISSUE THREAD

**Issue by matrix-amiel** [composer/composer#7374]
Hi!

I'm developing new plugin for composer and I found very strange behavior of the php. even in the my php.ini there is - `error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_USER_DEPRECATED & ~E_NOTICE` composer throw ErrorException even for strict and notice and failed.

I'm using a external library and I can't fix them..
Somebody know where I reconfigure the error_reporting for the composer? there is another php.ini for composer?

Thanks
Amiel

**Comment by Seldaek** [comment]
We do throw on any error because that's the best way to avoid any errors from creeping up un-noticed. You can not disable this behavior. Make sure your plugin is error and notice-free.
