### ISSUE TITLE
Installed composer but not able see version

### ISSUE THREAD

**Issue by Sreekanth1234** [composer/composer#7378]
My `composer.json`:

```json
...replace me...
```

Output of `composer diagnose`:

```
...replace me...
```

When I run this command:

Yesterday i had installed composer on IBM cloud by this commands 
**npm install -g composer-cli
npm install -g composer-rest-server
npm install -g generator-hyperledger-composer
npm install -g yo**
Today i'm not able to see version of composer 

```

I get the following output:
linux1@hyperledger:~/fabric-dev-servers> composer version
If 'composer' is not a typo you can use command-not-found to lookup the package that contains it, like this: cnf composer
linux1@hyperledger:~/fabric-dev-servers> composer cli version
If 'composer' is not a typo you can use command-not-found to lookup the package that contains it, like this: cnf composer
```
```

And I expected this to happen:
what is reason and what i have to ?

**Comment by prisis** [comment]
You installed this package https://www.npmjs.com/package/composer-cli not composer for php but a npm package for administering business networks

**Comment by Sreekanth1234** [comment]
Ok. But when installed **npm installed -g composer-cli** i am able to see.. Now also i installed see below image
![Uploading Screen Shot 2018-05-31 at 10.35.29 AM.png…]()

Now also i'm not able to see version ?
