### ISSUE TITLE
How to install/use the cloned repo of composer for development?

### ISSUE THREAD

**Issue by rumanpasha** [composer/composer#7380]
I have cloned the repo in my development server, please tell me how to install and use the repo

**Comment by stof** [comment]
use composer (the phar) to run `composer install` in your local clone, to get all the dependencies (yes, composer itself uses composer to manage dependencies).

and then, you can run composer using your dev clone by using `.../bin/composer` to run composer (`...` being replace by the location where you cloned the repo).
