### ISSUE TITLE
New feature - Slack and/or Discord support links

### ISSUE THREAD

**Issue by Truemedia** [composer/composer#7384]
So I see the support section of the composer schema has an option for an irc channel, but this is quite old school now and so many organisations use slack or discord as a more modern alternative.

If you try putting a URL for either of those in the IRC field it causes a composer error, so ideally would be nice to have new field to put these URL's in.

I use satis and been able to directly search for a package and click the support links it fetches back from composer is extremely useful for me.

**Comment by Seldaek** [comment]
We could add a "chat" node I guess, calling it slack sounds a bit restrictive, and I'd rather not add gitter and co as well. For discord I'd put it in the `forum` URL.

**Comment by Truemedia** [comment]
Yeh something agnostic would be ideal, and forum does make sense if linking to a discord server for a dedicated community rather than a dedicated channel.

**Comment by ryanaslett** [comment]
discourse (https://www.discourse.org/) should go to the forums. Discord (https://discordapp.com/) is a slack clone, of which theres also rocketchat, matrix, and many others, so having a "chat" heading is a good idea.

**Comment by Seldaek** [comment]
Ah thanks for the clarification @ryanaslett, I indeed got those mixed up.

**Comment by Seldaek** [comment]
Oh this was fixed by https://github.com/composer/composer/pull/7714 ages ago.
