### ISSUE TITLE
Can not implement interface with the same name ending

### ISSUE THREAD

**Issue by spawnia** [composer/composer#7392]
I have the following two files:

src/DigiaOnlineSchemaBuilder.php

````php
<?php

namespace Nuwave\Lighthouse;

class DigiaOnlineSchemaBuilder implements Builder
//...
````

src/Builder.php

````php
<?php

namespace Nuwave\Lighthouse;

interface Builder
//...
````

When I run this command:

```
vendor/bin/phpunit
```

I get the following output:

```
PHP Fatal error:  Interface 'Nuwave\Lighthouse\Builder' not found in /var/www/src/DigiaOnlineSchemaBuilder.php on line 58

In DigiaOnlineSchemaBuilder.php line 58:

  Interface 'Nuwave\Lighthouse\Builder' not found
```

And I expected this to happen:

Tests should execute normally as the interface is found.

I tried changing the name of the interface, when i name it something like `IBuilder`, it works. The error occurs when the name of the interface is contained in the name of the class that implements it.

When i move the Interface do a different folder and namespace, e.g. src/Interfaces/Builder.php and `namespace Nuwave\Lighthouse\Interfaces`, it is found with no problem.

My `composer.json`:

```json
    "autoload": {
        "psr-4": {
            "Nuwave\\Lighthouse\\": "src/"
        }
    },
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
require.digiaonline/graphql : unbound version constraints (@dev) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.6.5
PHP version: 7.1.17
PHP binary path: /usr/bin/php7
```

**Comment by stof** [comment]
does it happen with an optimized autoloader (and at which optimization level) or a non-optimized one ?

**Comment by spawnia** [comment]
I managed to find the root cause of this. Composer had nothing to do with it, sorry!

The issue was that the test setup defined an alias `Builder::class => DigiaOnlineSchemaBuilder::class`

It was our (misguided) attempt of binding a concrete implementation to that interface. We have it figured out now in a way that will not break our code.
