### ISSUE TITLE
issue while create project using composer

### ISSUE THREAD

**Issue by sandipmavani** [composer/composer#7393]
Output of `composer diagnose`:

```
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Failed to enable crypto
failed to open stream: operation failed
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.6.5
PHP version: 5.6.10
PHP binary path: /Applications/MAMP/bin/php/php5.6.10/bin/php
```
openssl verion

```
OpenSSL 1.0.2o  27 Mar 2018
```

When I run this command:

```
composer create-project --prefer-dist laravel/laravel blog "5.4.*"
```

I get the following output:

```
Failed to download laravel/laravel from dist: The "https://api.github.com/repos/laravel/laravel/zipball/098b8a48830c0e4e6ba6540979bf2459c8a6a49e" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Failed to enable crypto
failed to open stream: operation failed
```

And I expected this to happen:

**Comment by sbuzonas** [comment]
What is the output of `composer show --platform`?

**Comment by zeldystern** [comment]
I have the same issue.

Here are my outputs 

composer show --platform
composer-plugin-api  1.1.0    The Composer Plugin API
ext-bcmath           7.2.12   The bcmath PHP extension
ext-bz2              7.2.12   The bz2 PHP extension
ext-calendar         7.2.12   The calendar PHP extension
ext-ctype            7.2.12   The ctype PHP extension
ext-curl             7.2.12   The curl PHP extension
ext-date             7.2.12   The date PHP extension
ext-dba              7.2.12   The dba PHP extension
ext-dom              20031129 The dom PHP extension
ext-exif             7.2.12   The exif PHP extension
ext-fileinfo         1.0.5    The fileinfo PHP extension
ext-filter           7.2.12   The filter PHP extension
ext-ftp              7.2.12   The ftp PHP extension
ext-gd               7.2.12   The gd PHP extension
ext-gettext          7.2.12   The gettext PHP extension
ext-gmp              7.2.12   The gmp PHP extension
ext-hash             1.0      The hash PHP extension
ext-iconv            7.2.12   The iconv PHP extension
ext-intl             1.1.0    The intl PHP extension
ext-json             1.6.0    The json PHP extension
ext-ldap             7.2.12   The ldap PHP extension
ext-libxml           7.2.12   The libxml PHP extension
ext-mbstring         7.2.12   The mbstring PHP extension
ext-mysqli           7.2.12   The mysqli PHP extension
ext-mysqlnd          0        The mysqlnd PHP extension (actual version: mysqlnd 5.0.12-dev - 2015040...
ext-odbc             7.2.12   The odbc PHP extension
ext-openssl          7.2.12   The openssl PHP extension
ext-pcntl            7.2.12   The pcntl PHP extension
ext-pcre             7.2.12   The pcre PHP extension
ext-PDO              7.2.12   The PDO PHP extension
ext-pdo_dblib        7.2.12   The pdo_dblib PHP extension
ext-pdo_mysql        7.2.12   The pdo_mysql PHP extension
ext-PDO_ODBC         7.2.12   The PDO_ODBC PHP extension
ext-pdo_pgsql        7.2.12   The pdo_pgsql PHP extension
ext-pdo_sqlite       7.2.12   The pdo_sqlite PHP extension
ext-pgsql            7.2.12   The pgsql PHP extension
ext-Phar             2.0.2    The Phar PHP extension
ext-phpdbg_webhelper 0.5.0    The phpdbg_webhelper PHP extension
ext-posix            7.2.12   The posix PHP extension
ext-pspell           7.2.12   The pspell PHP extension
ext-readline         7.2.12   The readline PHP extension
ext-Reflection       7.2.12   The Reflection PHP extension
ext-session          7.2.12   The session PHP extension
ext-shmop            7.2.12   The shmop PHP extension
ext-SimpleXML        7.2.12   The SimpleXML PHP extension
ext-soap             7.2.12   The soap PHP extension
ext-sockets          7.2.12   The sockets PHP extension
ext-sodium           7.2.12   The sodium PHP extension
ext-SPL              7.2.12   The SPL PHP extension
ext-sqlite3          7.2.12   The sqlite3 PHP extension
ext-sysvmsg          7.2.12   The sysvmsg PHP extension
ext-sysvsem          7.2.12   The sysvsem PHP extension
ext-sysvshm          7.2.12   The sysvshm PHP extension
ext-tidy             7.2.12   The tidy PHP extension
ext-tokenizer        7.2.12   The tokenizer PHP extension
ext-wddx             7.2.12   The wddx PHP extension
ext-xdebug           2.6.1    The xdebug PHP extension
ext-xml              7.2.12   The xml PHP extension
ext-xmlreader        7.2.12   The xmlreader PHP extension
ext-xmlrpc           7.2.12   The xmlrpc PHP extension
ext-xmlwriter        7.2.12   The xmlwriter PHP extension
ext-xsl              7.2.12   The xsl PHP extension
ext-Zend-OPcache     7.2.12   The Zend OPcache PHP extension
ext-zip              1.15.4   The zip PHP extension
ext-zlib             7.2.12   The zlib PHP extension
lib-curl             7.62.0   The curl PHP library
lib-iconv            1.11     The iconv PHP library
lib-ICU              62.1     The intl PHP library
lib-libxml           2.9.4    The libxml PHP library
lib-openssl          1.0.2.16 OpenSSL 1.0.2p  14 Aug 2018
lib-pcre             8.41     The pcre PHP library
lib-xsl              1.1.29   The xsl PHP library
php                  7.2.12   The PHP interpreter
php-64bit            7.2.12   The PHP interpreter, 64bit
php-ipv6             7.2.12   The PHP interpreter, with IPv6 support

openssl ciphers -v TLSv1.2
ECDHE-ECDSA-CHACHA20-POLY1305 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=ChaCha20-Poly1305 Mac=AEAD
ECDHE-RSA-CHACHA20-POLY1305 TLSv1.2 Kx=ECDH     Au=RSA  Enc=ChaCha20-Poly1305 Mac=AEAD
DHE-RSA-CHACHA20-POLY1305 TLSv1.2 Kx=DH       Au=RSA  Enc=ChaCha20-Poly1305 Mac=AEAD
ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AESGCM(256) Mac=AEAD
ECDHE-ECDSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AESGCM(256) Mac=AEAD
ECDHE-RSA-AES256-SHA384 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AES(256)  Mac=SHA384
ECDHE-ECDSA-AES256-SHA384 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AES(256)  Mac=SHA384
DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD
DHE-RSA-AES256-SHA256   TLSv1.2 Kx=DH       Au=RSA  Enc=AES(256)  Mac=SHA256
DHE-RSA-CAMELLIA256-SHA256 TLSv1.2 Kx=DH       Au=RSA  Enc=Camellia(256) Mac=SHA256
ADH-AES256-GCM-SHA384   TLSv1.2 Kx=DH       Au=None Enc=AESGCM(256) Mac=AEAD
ADH-AES256-SHA256       TLSv1.2 Kx=DH       Au=None Enc=AES(256)  Mac=SHA256
ADH-CAMELLIA256-SHA256  TLSv1.2 Kx=DH       Au=None Enc=Camellia(256) Mac=SHA256
AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
AES256-SHA256           TLSv1.2 Kx=RSA      Au=RSA  Enc=AES(256)  Mac=SHA256
CAMELLIA256-SHA256      TLSv1.2 Kx=RSA      Au=RSA  Enc=Camellia(256) Mac=SHA256
ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AESGCM(128) Mac=AEAD
ECDHE-ECDSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AESGCM(128) Mac=AEAD
ECDHE-RSA-AES128-SHA256 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AES(128)  Mac=SHA256
ECDHE-ECDSA-AES128-SHA256 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AES(128)  Mac=SHA256
DHE-RSA-AES128-GCM-SHA256 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(128) Mac=AEAD
DHE-RSA-AES128-SHA256   TLSv1.2 Kx=DH       Au=RSA  Enc=AES(128)  Mac=SHA256
DHE-RSA-CAMELLIA128-SHA256 TLSv1.2 Kx=DH       Au=RSA  Enc=Camellia(128) Mac=SHA256
ADH-AES128-GCM-SHA256   TLSv1.2 Kx=DH       Au=None Enc=AESGCM(128) Mac=AEAD
ADH-AES128-SHA256       TLSv1.2 Kx=DH       Au=None Enc=AES(128)  Mac=SHA256
ADH-CAMELLIA128-SHA256  TLSv1.2 Kx=DH       Au=None Enc=Camellia(128) Mac=SHA256
AES128-GCM-SHA256       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(128) Mac=AEAD
AES128-SHA256           TLSv1.2 Kx=RSA      Au=RSA  Enc=AES(128)  Mac=SHA256
CAMELLIA128-SHA256      TLSv1.2 Kx=RSA      Au=RSA  Enc=Camellia(128) Mac=SHA256
NULL-SHA256             TLSv1.2 Kx=RSA      Au=RSA  Enc=None      Mac=SHA256

I am on Mac 10.14 (Mojave).
