### ISSUE TITLE
Question: download decencies for different PHP version

### ISSUE THREAD

**Issue by aik099** [composer/composer#7396]
I have a situation, when I run Composer on PHP 7.1, but I need all dependency resolution code think, that I'm running it on PHP 5.6 so that downloaded dependencies work for PHP 5.6. Is there a way to do that?

If I run Composer on PHP 5.6, then I'll got enormously large "vendor" folder, because on my development machine I'm using OpenSSL 0.9.x and because of it SSL negotiation for dist package download composer makes never completes and it's doing `git clone` a lot.

As alternative maybe there is a way to do `git export` instead of `git clone`?

Thanks.

**Comment by jvasseur** [comment]
You can override the platform (php version and extensions) in your `composer.json` : https://getcomposer.org/doc/06-config.md#platform, this force composer to do dependency resolution with the given platform instead of the one from the running php executable.

**Comment by stof** [comment]
note that the platform config has a shortcoming regarding extensions: it can mark additional extension as supported by the platform. But it cannot remove extensions supported by your runtime (the settings from the config are merged with the settings coming from the runtime, so they can override versions and add more info but they cannot remove them)

**Comment by aik099** [comment]
@jvasseur , will the `platform` work in project's `composer.json` or I only set global platform?

Adding this to project's `composer.json` had no effect on `composer install` command:

```json
"config": {
	"platform": {
		"php": "5.4"
	}
}
```

**Comment by aik099** [comment]
Ah, that was my `composer.lock` file, that hadn't that `platform` setting. Now I've removed `composer.lock` and all worked like a charm. Big thanks.
