### ISSUE TITLE
Global vendors issue when I alternate PHP versions

### ISSUE THREAD

**Issue by hectorprats** [composer/composer#7410]
Hi, in my work we hace a lot of preojects, and we work with vendors like cs-fixer, phpstan, etc... and we have issues aternating PHP version.

How can we work with it?

if this is not possible, maybe I can create an improvement for global to record the PHP version number in the dependency folder.

**Comment by alexislefebvre** [comment]
> we have issues aternating PHP version

Please explain your issues.

> I can create an improvement for global to record the PHP version number in the dependency folder

I'm not sure that I understood your problem but you can force the PHP version used by Composer by defining the `platform`: https://getcomposer.org/doc/06-config.md#platform https://stackoverflow.com/a/37438345/2257664

**Comment by hectorprats** [comment]
Ok, thanks.

The problems we have is that a global installation of php7 libraries is done and when you run composer with php 5. * it returns an error because it has a vendor with php7 in an execution with php5.

That is why it is important that composer installations version, such as vendor / php5.6 or vendor / php7.1

In this way the use of alternate will always be compatible.

**Comment by alexislefebvre** [comment]
So, you can remove global installations of libraries and `require` the libraries in each project. So you will avoid conflicts because projets will be independent.

Or you can use Docker container in order to run different PHP versions on the same session.

**Comment by hectorprats** [comment]
It's true, and it's a good solution. But I can also stop using composer and do a coupler with the libraries that I need everywhere. I understand that the good thing about composer is that he is in charge of integrating things correctly, and in this case he does not do it.
If the vendors were versioned by php version, those who use a single PHP would not see a difference, but those who alternate would not have to be erasing and downloading packages.

**Comment by alexislefebvre** [comment]
Thanks for the explanation.

> I can create an improvement for global to record the PHP version number in the dependency folder

This may be possible with the [`COMPOSER_HOME`](https://getcomposer.org/doc/03-cli.md#composer-home) variable to use several global configurations, by setting the value before calling PHP and Composer:

```bash
COMPOSER_HOME=~/.composer/7.0 php7.0 composer install
COMPOSER_HOME=~/.composer/7.1 php7.1 composer install
```

**Comment by alcohol** [comment]
What @alexislefebvre proposed is a somewhat elegant solution to an inelegant problem. 

In practice, while I recognize the benefits of having global installs for tools such as phpunit, php-cs-fixer, etc; I will always recommend adding them to your require-dev on a project level instead.
