### ISSUE TITLE
A link that explain color in terminal output from composer

### ISSUE THREAD

**Issue by user67x** [composer/composer#7411]
Hello,

I user composer in my Drupal 8 installation.

I search a link that explain the color in terminal output for Composer command line.

I search too to know the diffencence between the ^ and the ~ in composer.json

(I have googled yet)

Thanks for your help

**Comment by stof** [comment]
https://getcomposer.org/doc/articles/versions.md#next-significant-release-operators for the operators

**Comment by alcohol** [comment]
And colors can be controlled using `--ansi|--no-ansi`; https://getcomposer.org/doc/03-cli.md#global-options
