### ISSUE TITLE
composer require fideloper/proxy

### ISSUE THREAD

**Issue by alladodakey** [composer/composer#7413]
Am having this error : 
[Composer\Downloader\TransportException]
  The'http://packagist.org/p/fideloper/proxy%249271e19129358853986ed3ca9315ced11a42439a57f49537033c3b436a6f
  f543.json' URL could not be accessed: HTTP/1.1 400 Bad URI
what should i do?

**Comment by alexislefebvre** [comment]
Please try again, the URL https://packagist.org/p/fideloper/proxy%249271e19129358853986ed3ca9315ced11a42439a57f49537033c3b436a6ff543.json is working now.

**Comment by yaser-alazem** [comment]
Actually it's still not working !!
