### ISSUE TITLE
On php7.2 composer is failing for Ubuntu  

### ISSUE THREAD

**Issue by Ranjansingh41** [composer/composer#7418]
```

  Problem 1
    - fabpot/php-cs-fixer v1.13.3 requires php ^5.3.6 || >=7.0 <7.2 -> your PHP version (7.2.4) does not satisfy that requirement.
    - fabpot/php-cs-fixer v1.13.3 requires php ^5.3.6 || >=7.0 <7.2 -> your PHP version (7.2.4) does not satisfy that requirement.
    - Installation request for fabpot/php-cs-fixer v1.13.3 -> satisfiable by fabpot/php-cs-fixer[v1.13.3].

The command '/bin/sh -c /u16phpall/install.sh' returned a non-zero code: 2
```

When i try to install php7.2 on Ubuntu composer are throwing this above error.

**Comment by stof** [comment]
Well, the error message tells you that `fabpot/php-cs-fixer v1.13.3` does not support PHP 7.2. that's not a composer bug at all. That's composer doing exactly its job.

If you want to run on PHP 7.2, you will need to use a newer version of that library.

**Comment by xabbuh** [comment]
You may want to use friendsofphp/php-cs-fixer instead.
