### ISSUE TITLE
Strange behaviour with option "archive"

### ISSUE THREAD

**Issue by o5** [composer/composer#7420]
I'm using an own composer registry ([Satis with simple GUI](https://github.com/terramar-labs/packages)). I would like to include only one directory (`/src/*`) from package which is downloaded as archive. I discovered option [archive](https://getcomposer.org/doc/04-schema.md#archive) which is exactly what I looked for. 

But there is a problem because if I install this package over composer, content of `/src` directory is copied into root of package.

My vendor after `composer install` looks like:

```
$ ls vendor/company/package
Foo.php
Bar.php
```

instead of 

```
$ ls vendor/company/package
src/
```

Package's `composer.json`:

```json
   "archive": {
        "exclude": [".*", "*", "!/src"]
    },
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 1.6.5
PHP version: 7.2.6
PHP binary path: /usr/local/bin/php
```

```
Satis 1.0.0-dev (a816b99abba521baf13b5c5595a1a07e150b8a0e)
Packages 3.2.1-DEV (9e01b1b84829be224a5d2065cb5eaa862ba67ea8)
```

When I manually download TAR archive, there is not a problem (only `src/` dir is in root). It's probably something wrong in extracting phase, [here](https://github.com/composer/composer/blob/d21032ace524d98dbb73ce50d887a00de2891219/src/Composer/Downloader/TarDownloader.php#L29)?

When I don't use first exclude `.*` (excluding all of dot files) it works (with dot files).

**Comment by stof** [comment]
that's because composer has a special handling for archives having a single folder as their root content, to account for tools wrapping the whole source in a folder in the archive (github is one such tool IIRC).
A solution would be to ensure that you keep another file at the root (the composer.json file might be used for that, or the LICENSE file if it is at the root, but any file would do it)

**Comment by o5** [comment]
Thanks for quick reply!

Well, I don't understand *this special handling for archives*. I think this is a big WTF but sure, I can use a workaround which you served me as a solution.

Closing...
