### ISSUE TITLE
Minor release with `.0` hotfix or without?

### ISSUE THREAD

**Issue by flowl** [composer/composer#7430]
I have a question regarding semver.
When we publish a new (minor)release (not a hotfix), is the version `1.1` or is it `1.1.0` ?
Technically it doesn't matter if there is a `.0` hotfix string appended but I am curious if there is a convention over this?

Thanks and regards

**Comment by alcohol** [comment]
www.semver.org begs to differ: https://semver.org/#spec-item-2

Always use MAJOR.MINOR.PATCH

**Comment by stof** [comment]
note that composer itself does not care, as it will normalize the version
