### ISSUE TITLE
IP Ban?

### ISSUE THREAD

**Issue by Aecron** [composer/composer#7433]
Hello guys!

Sorry to bother you here guys, but i do feel like my server's IP has apparently been banned from reaching getcomposer.org & packagist.org ;
I think last time i've been using composer ~~was maybe 6 months ago, so I can't really tell since how long the situation is going,~~ (**actually no more than a month ago, I did some packages updates**) but today when i wanted to install a new package to try it out (GraphQL-php by Webonyx), all install attempts would end up in timeouts. Tried to update my composer, but that fails too. After some time of forums scratching, came upon someone suggesting to force https protocol, but then again no success. Cleared cache multiple times, then went for a fully clean reinstall, but then php (or wget, or anything) can't reach getcomposer.org.
When looking around to see if it was possible, i came across a ticket here 3 or 4 years ago, where the project's guys said that they never ban IPs, so i went into some more testing, and yeah, turned out i can't even ping getcomposer.org or packagist.org (100% of packets dropped) while i can virtually access anything else from my server.

Sooooo... what should i do :D

**Comment by alcohol** [comment]
Sounds more like a routing issue. We really do not ban anyone.

Have you tried using tools such as `tracepath` or `traceroute`?

**Comment by Aecron** [comment]
Hello!

Thanks for your reply. As i went to check on this today, the issue is now apparently the issue is no more. I still couldn't even ping both domains until late yesterday night, but now i succeed to reinstall composer & install some packages.
I would agree on the routing issue, but maybe from my server's hosting side.

Case closed :D
