### ISSUE TITLE
composer.lock specification

### ISSUE THREAD

**Issue by scy** [composer/composer#7435]
(Not using the issue template since my project and my Composer versions are irrelevant here.)

When changing a dependency in my `composer.json` from a tagged version constraint (e.g. `>=0.2`) to a branch name (e.g. `whatever`), I've noticed that the corresponding change in `composer.lock` added a `"my-package-name": 20` value to the `stability-flags` array.

I'm assuming by [this line](https://github.com/composer/composer/blob/122e422682d961233cc5db8b2102cd98b049d4f9/src/Composer/Package/BasePackage.php#L37) in the Composer source that the number 20 means "dev", but I couldn't find any documentation about these numbers or even the `stability-flags` array in the lockfile. Instead, while there's [detailed documentation about `composer.json`](https://getcomposer.org/doc/04-schema.md), apparently there's no page documenting `composer.lock` at all.

Am I just failing to find it? Because I certainly think that such a document should exist.

**Comment by alcohol** [comment]
Such a document does not exist because the lock file is generated and maintained by Composer programatically. We do not offer a public contract on the specification unlike the composer.json file.
