### ISSUE TITLE
Allow to specify location of phar files

### ISSUE THREAD

**Issue by Isinlor** [composer/composer#7446]
I would like to suggest adding a way for a package / project to specify a location of a phar file in their composer.json file.

I'm currently investigating a way to separate external tools that code of my project does not depend on, from actual code dependencies. (It allows to avoid conflicts and namespace pollution in general).

Promising way to do this is Tooly: https://github.com/tommy-muehle/tooly-composer-script

It allows to install `.phar` files from remote locations. However, it requires manual maintenance of versions, since Tooly can not keep track of `.phar` file versions. 

Therefore, as mentioned, I would like to propose to add / document a `phar` entry that would allow to locate `.phar` files automatically.

On package maintainer side the maintenance of `phar` entry could likely be automated as well with help of tools like `phar-composer`: https://github.com/clue/phar-composer

Related issue: https://github.com/composer/composer/issues/5390

**Comment by staabm** [comment]
Did you try using `composer global install` for this tools?

**Comment by Isinlor** [comment]
Yes, however there is a lot of conflicts due to releases of tools like nikic/PHP-Parser 2 / 3 / 4 or symfony/console etc.

Also I want to avoid global dependencies to make sure that my build / CI are reproducible independent of local configuration.

**Comment by alcohol** [comment]
I do not understand the use-case.

It sounds like you do not want to use `require-dev` for some reason, but instead want to use a bunch of phar files. One way to approach that would be to use something as simple and basic as http://php.net/manual/en/ini.core.php#ini.include-path

**Comment by Seldaek** [comment]
Please use https://github.com/bamarni/composer-bin-plugin if you want globally isolated deps, it seems to handle things well. Otherwise using require-dev in every project is definitely the best way to avoid clashes between various global utilities. I don't think this is something we want to look into further in Composer at the moment.

**Comment by Isinlor** [comment]
Indeed, `composer-bin-plugin` addresses all my issues 👍
