### ISSUE TITLE
[Optimization idea] Register conflict rules only based on required packages

### ISSUE THREAD

**Issue by stof** [composer/composer#7452]
Currently, conflict rules are registered in the solver for all packages matching the constraint (for `replaces` and `conflicts` in the metadata), even when the conflicting package is never required.
In https://blackfire.io/profiles/04234c24-b8c4-43b0-b23a-0a836b8c766e/graph?settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=focused&settings%5BtabPane%5D=nodes&selected=Composer%5CDependencyResolver%5CRuleSet%3A%3Aadd&callname=Composer%5CDependencyResolver%5CRuleSet%3A%3Aadd (shared in #7449), the `RuleSet::add` method is called 194446 and `Rules2Literal::getHash` is called 193248 times. `Rules2Literal` is used only to represent these conflict rules (preventing 2 packages to be installed at the same time) and `getHash` is called only once when adding them in the set. So this tells us that 99.4% of rules are conflict rules in this case. Reducing the number of these rules might then be a good news for the solver.

These rules can never make composer select a package to install. They are only about rejecting them. And it is common for packages to conflict with packages you won't need in the end (if they were hard dependencies, they would be registered using `require` for the supported versions, not `conflicts` for the unsupported ones). Thus, a conflict constraint will only grow its number of rules over time (as more releases are made) and you cannot really narrow it down (it would not have been a conflict in the first place otherwise).
Thus, this also requires loading metadata for these never used packages (because the metadata are used by the conflict rules)

My idea would be to generate the RuleSet in 2 passes:

- build rules allowing to bring in packages (`require` ones, and the root dev requirements), while registering the list of packages considered in additive way by this process
- process the conflicts/replaces rules of all involved packages, but matching them on the pool of packages created in the first phase instead of matching them on the repository pool.

This way, any conflict constraint would only add rules for packages which can be selected by a positive rule (much less than currently), and we would not load metadata at all for packages never required (as the pool used by the second pass would not be loading more package metadata).

What do you think about this idea ?

**Comment by stof** [comment]
On a side note, this might even allow fixing https://github.com/composer/composer/issues/3754, which was introduced when the repository pool started to be optimized based on root requirements (which is fine for rules adding more packages as we know that we will have to do an AND between both set of rules, but breaks for rules rejecting packages as they might miss some rejections due to treating the replaces rule the same for its `provide` and `conflict` part while it conflict with *all* other versions of this package), as the second-pass pool would not have this root-package optimization applied in it (it would have a different one)

**Comment by stof** [comment]
#7454 has done part of it (that fixed a bug without performance regression, but hasn't helped much with performance).

https://github.com/composer/composer/pull/7454#issuecomment-403773876 might give a hint to continue, but requires @naderman's explanation about what that thing is exactly.

Otherwise, remaining optimizations would only be about loading less versions of each packages in the solver...

**Comment by staabm** [comment]
IMO we need async IO, all other e.g. solver related things are already well optimized.
Asyncio would speedup things considerably

**Comment by Seldaek** [comment]
@staabm I'm working on that front, more usable progress in the next couple days hopefully :)

**Comment by mbaynton** [comment]
@naderman and I both have implementations that tackle this
#8053 
https://github.com/naderman/composer/tree/multi-conflict-rule

**Comment by naderman** [comment]
This is solved with a combination of the following merged 2.0 PRs now:

- https://github.com/composer/composer/pull/7625 implementation of pool builder restricts metadata loading to packages directly required
- https://github.com/composer/composer/pull/7936 reduces unnecessary poolbuilder input
- https://github.com/composer/composer/pull/8424 reduces conflict rules for the same package to a single Rule object which greatly reduces memory

**Comment by naderman** [comment]
@stof Anything else you think is missing? otherwise I think this can be closed.
