### ISSUE TITLE
What does "composer update mirrors" actually do?

### ISSUE THREAD

**Issue by ezzatron** [composer/composer#7459]
We have a private Packagist installation at my workplace. We also use GitHub Enterprise and Travis CI Enterprise.

Occasionally we run into weird issues in our CI builds with Composer installs failing despite having access to the required auth tokens. The fix for these issues is generally to run `composer update mirrors`, but it's a bit of a "magic" fix that none of us really understand, and the results seem to vary depending on the environment in which it is run.

It seems the only mentions of `composer update mirrors` on the entire internet are a brief mention on https://packagist.com/docs and a [random GitHub issue written in Chinese](https://github.com/dueros/dumi_doc/issues/5). AFAIK it's not mentioned anywhere on https://getcomposer.org/ or the output from `composer update --help`.

Can you shed any light on this command, what factors influence how it changes the lock file, and why it's implemented as a "magic" undocumented argument to the `composer update` command? Cheers.

**Comment by alcohol** [comment]
`mirrors`, just like `nothing` and `lock` is basically telling Composer to update the composer.lock file without actually updating any packages.

I cannot recall if that is basically the same as running `composer update --lock`.

@Seldaek did I miss anything?

**Comment by Seldaek** [comment]
That is correct. Triggering this update means Composer also tries to update repository URLs and whatnot in the installed packages and hence the lock file.

**Comment by vlaidmeR** [comment]
7459

في أربعاء، 11 يوليو، 2018 في 4:55 م، كتب Jordi Boggiano <
notifications@github.com>:

**Comment by vlaidmeR** [comment]
https://github.com/composer/composer/issues/7459


في أربعاء، 11 يوليو، 2018 في 7:00 م، كتب Hadi 3mer <hadi3mer@gmail.com>:

**Comment by ezzatron** [comment]
Thanks for the info. Just to clarify - are you saying that `composer update mirrors` does *exactly* the same thing as `composer update --lock`? Or does `mirrors` *also* update repository URLs in addition to the behaviour of `--lock`?

**Comment by Seldaek** [comment]
It does the same

**Comment by ezzatron** [comment]
Thanks!
