### ISSUE TITLE
Problem with "replace" on circullar dependency

### ISSUE THREAD

**Issue by paranoiq** [composer/composer#7460]
hi,
this issue is similar to https://github.com/composer/composer/issues/858, but little different

i have a development tools package:
```
{
    "name": "dogma/dogma-dev",
    ...
    "require": {
        "php-64bit": "^7.1.0",
        "consistence/coding-standard": "2.4.0",
        ...
        "spell-checker/spell-checker": "~0.3"
    },
    ...
}
```

i would like to use this package when developing one of the dev tools - spell-checker:
```
{
    "name": "spell-checker/spell-checker",
    ...
    "require": {
        ...
    },
    "require-dev": {
        "dogma/dogma-dev": "~0.1"
    },
    "replace": {
        "spell-checker/spell-checker": "~0.3"
    },
    ...
}
```

i thought the "replace" rule should turn off the child dependency, but it does not seem to work in this case when the spell-checker/spell-checker dependency is forced as we are inside that actual project

composer returns:
```
Problem 1
    - Installation request for spell-checker/spell-checker dev-master -> satisfiable by spell-checker/spell-checker[dev-master].
    - dogma/dogma-dev v0.1 requires spell-checker/spell-checker ~0.3 -> satisfiable by spell-checker/spell-checker[v0.3, v0.3.1, v0.3.2, v0.3.3, v0.3.4, v0.3.5, v0.3.6].
    - don't install spell-checker/spell-checker v0.3|remove spell-checker/spell-checker dev-master
    ...
    - don't install spell-checker/spell-checker v0.3.6|remove spell-checker/spell-checker dev-master
    - Installation request for dogma/dogma-dev ~0.1 -> satisfiable by dogma/dogma-dev[v0.1].
```

is it a bug or am i using it wrong?

**Comment by alcohol** [comment]
Did you actually try to use the solution proposed in the issue that you linked?

```
cd /path/to/spell-checker-repository
COMPOSER_ROOT_VERSION=0.3 composer install
```

**Comment by paranoiq** [comment]
yes i tried and it did not work, so i did not realize that it could work in this case.

i tried that again now with cleaning the vendor directory completely and the installation finished without problems

regarding the "replace" - i am still not sure about this. do you consider it a bug?

**Comment by alcohol** [comment]
I do not think replace is meant to be used like this. Replace is meant for situations where one package replaces another. You are trying to replace a package with itself, with the intent of fulfilling a specific version constraint. And you only want to do this because of your development workflow which is unconventional and uses a circular reference. The `replace` should not even be committed in your real composer.json. So none of this really makes sense. `COMPOSER_ROOT_VERSION` is the only "reasonable" solution here.
