### ISSUE TITLE
composer update erases package using path repository

### ISSUE THREAD

**Issue by joachim-n** [composer/composer#7462]
I ran 'composer update foo/foo' when foo/foo was configured as a path resository, and Composer had it symlinked in.

Result: composer deleted the symlink and downloaded the package.

**Comment by alcohol** [comment]
Please provide a reproducible scenario/case.

**Comment by joachim-n** [comment]
1. Find an app you can install with composer, which has at least one dependency. Call the app app/app and the dependency dep/dep.
2. Get a git clone of dep/dep, say in ~/dep
3. Set up a folder for the app, say in ~/app, and in the composer.json, configure a 'repository' section that specifies the git clone of dep/dep as a path.
4. Do 'composer install' in ~/app. This should use a symlink to install dep/dep, rather than download it. This is as expected.
5. Now do 'composer update dep/dep'. This overwrites the symlink and does a checkout, without warning. This is not as expected.

**Comment by alcohol** [comment]
Unable to reproduce:

```
rob@galaga ~ $ mkdir -p /tmp/test
mkdir: created directory '/tmp/test'

rob@galaga ~ $ cd /tmp/test

rob@galaga /tmp/test $ git clone git@github.com:alcohol/iso4217
Cloning into 'iso4217'...
remote: Counting objects: 385, done.
remote: Total 385 (delta 0), reused 0 (delta 0), pack-reused 385
Receiving objects: 100% (385/385), 105.32 KiB | 238.00 KiB/s, done.
Resolving deltas: 100% (210/210), done.

rob@galaga /tmp/test $ cat << JSON > composer.json
{
  "repositories": [
    {"type": "path", "url": "./iso4217" }
  ],
  "require": { "alcohol/iso4217": "dev-master" }
}
JSON

rob@galaga /tmp/test $ composer install -v
Loading composer repositories with package information
Updating dependencies (including require-dev)
Dependency resolution completed in 0.000 seconds
Analyzed 57 packages to resolve dependencies
Analyzed 47 rules to resolve dependencies
Package operations: 1 install, 0 updates, 0 removals
Installs: alcohol/iso4217:dev-master
  - Installing alcohol/iso4217 (dev-master): Symlinking from ./iso4217
Writing lock file
Generating autoload files

rob@galaga /tmp/test $ composer update alcohol/iso4217 -v
Loading composer repositories with package information
Updating dependencies (including require-dev)
Dependency resolution completed in 0.000 seconds
Analyzed 61 packages to resolve dependencies
Analyzed 69 rules to resolve dependencies
Package operations: 0 installs, 0 updates, 0 removals
Generating autoload files
```

**Comment by alcohol** [comment]
What probably happened is that you did not use `dev-master`, or Composer was able to determine a specific version for your path repository source, and it deemed a newer version was available remotely, so it discarded your path repository.

**Comment by joachim-n** [comment]
That sounds like it, but I think Composer should ask for confirmation before erasing something! Particularly given how slowly Composer runs -- mistakes like this take a long time to undo.

**Comment by alcohol** [comment]
Creating a symlink takes almost no time.. anyway, this is not an issue, simply incorrect configuration.

**Comment by joachim-n** [comment]
> Creating a symlink takes almost no time.. 

Perhaps, but Composer repeats all its calculations on version dependencies every time, so the whole operation of 'composer remote' and then redoing 'composer install' took me about 5 minutes.

> anyway, this is not an issue, simply incorrect configuration.

Incorrect configuration should not lose data.

I am really unhappy about how Composer has very little respect for my time or my data as a user.

**Comment by alcohol** [comment]
You did not lose data. The source still exist. A symlink is not data.

If you are unhappy, can I suggest you take a moment to step outside, enjoy some fresh air and talk to a human being? Try not to forget you are communicating with other people here, not robots.

**Comment by joachim-n** [comment]
The setup of my app was broken, and it took time to restore it. That makes it a destructive operation, and Composer should ask for confirmation.
