### ISSUE TITLE
Authentication with auth.json ignored with Mercurial

### ISSUE THREAD

**Issue by Elendev** [composer/composer#7463]
My `composer.json`:

```json
{
    "repositories": [
        {
            "type": "hg",
            "url": "https://my.private.repository.com/my-package"
        }
    ],
}
```
My `auth.json`:

```json
{
    "http-basic": {
      "my.private.repository.com": {
        "username": "myusername",
        "password": "secret"
      }
    }
}
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking HTTP proxy: OK
Checking HTTP proxy support for request_fulluri: OK
Checking HTTPS proxy support for request_fulluri: OK
Checking github.com rate limit: OK
Checking disk free space: OK
```

When I run this command:

```
composer update
```

I get the following output:

```
[RuntimeException]                                                                                                    
  Failed to clone https://my.private.repository.com/my-package, could not read packages from it  
                                                                                                                        
  abort: http authorization required for https://my.private.repository.com/my-package      
```

And I expected this to happen:

I expect Composer to be able to use a Mercurial repository behind a http-basic authentication mechanism with the `auth.json` file.

If I use this:
```json
{
    "repositories": [
        {
            "type": "hg",
            "url": "https://myusername:secret@my.private.repository.com/my-package"
        }
    ],
}
```
I'm able to use my private package, but as soon as I'm using an `auth.json` file, the credentials are not used.
The `hg` command executed is the following: `hg clone --noupdate 'https://my.private.repository.com/my-package' '/root/.composer/cache/vcs/https---my-private-repository-com-my-package/'`.

**Comment by alcohol** [comment]
It would help if you could provide us with a reproducible scenario/case. I do not have any hosted http-basic auth protected HG repositories, nor do I have the time to create one. So there is nothing I can do to debug this presently.

**Comment by Elendev** [comment]
@alcohol You are right, as soon as I have time, I will try to create a publicly available password-protected mercurial repository to be able to easily reproduce the issue.
In the meantime, I'll try to solve it through a PR since I have this configuration available in my environment.

**Comment by alcohol** [comment]
:+1:

**Comment by Seldaek** [comment]
Closed by https://github.com/composer/composer/pull/7475
