### ISSUE TITLE
Platform Constraint oddness? Or am I just misunderstanding?

### ISSUE THREAD

**Issue by mbadolato** [composer/composer#7465]
My `composer.json`:

```json
{
    "name": "my/library",
    "require": {
        "php": ">=5.6",
        "tightenco/collect": "^5.3"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "platform": {
            "php": ">=5.6"
        },
        "sort-packages": true
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.6.5
PHP version: 7.2.7
PHP binary path: /usr/local/Cellar/php/7.2.7/bin/php
```

When I run this command:

```
composer install
```

I get the following output:

```
composer install
    1/1:	http://packagist.org/p/provider-latest$2deb34ff00e397d6d03e7661e27f321162a2280481890b4e05561abd8d313cad.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Loading composer repositories with package information
Updating dependencies (including require-dev)
    1/1:	https://codeload.github.com/tightenco/collect/legacy.zip/07547aa6191f6d05b459ecea7c62526e18f33851
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Package operations: 1 install, 0 updates, 0 removals
  - Installing tightenco/collect (v5.3.20): Loading from cache
Writing lock file
Generating autoload files
```

And I expected this to happen:

The above is correct. I expect to see `tightenco/collect` install a `5.3` version as that's the last compatible version with the PHP 5.6 constraint. The latest version of the library is a `5.6.N` version, which requires PHP 7 or higher.

Now... when I try to use my library in an application that does not have any platform constraint in the `config` section of its composer.json file, and I run

```
composer require my/library
```
composer ignores `my/library`'s platform constraint requirement and installs a version of `tightenco/collect` in the `5.6.N` release cycle.

I would think that even if the parent application had no constraints, the library's json file would still honor the constraints defined and install something targeted for PHP 5.6 (the collect lib's `5.3.N` releases).  Is this not the case? Am I misunderstanding how the contraints should work? The app is not previously using the collect package so has no constraints of it's own or anything like that.

I know I can get around it by having `my/library` define the requirement as `~5.3.0` instead, but I was under the impression that `^5.3` would work given the platform constraint and that it installs an appropriate version when doing a `composer install` in the library itself, it just doesn't bubble up that constraint up to the application using the application, and I thought it would.

Any info/explanation greatly appreciated so that I have a better understanding!

thanks

**Comment by alcohol** [comment]
As a library you can only specify platform constraints through `require`. The platform config value is not a constraint (so your value of `>=5.5` makes no sense), it simply provides a way to fake the php version of your environment.

Also note that https://getcomposer.org/doc/04-schema.md#config is root-only. Which means that it only applies to the root composer.json, and it is ignored for any dependencies.

**Comment by mbadolato** [comment]
> Also note that https://getcomposer.org/doc/04-schema.md#config is root-only. Which means that it only applies to the root composer.json, and it is ignored for any dependencies.

That's what had needed to know, thank you!
