### ISSUE TITLE
vendor / package lookup mechanism

### ISSUE THREAD

**Issue by AntoninSlejska** [composer/composer#7466]
When the vendor name and package name is known, then it is possible at Packagist to get the project's data (e.g. versions): https://packagist.org/packages/symfony/symfony.json

By other hosts it is necessary to find the hash. E.g.
 - not working URL: https://packages.drupal.org/8/drupal/commerce.json
 - working URL: https://packages.drupal.org/8/drupal/commerce%24f8b852956418601bb4d985203d4138a18e2bfc0ae1b67b249a667228190fd26f.json

How can I get the working URL (or the hash), when I know only the vendor (drupal) and the package (commerce)?

There is also a related question at StackExchange: https://drupal.stackexchange.com/q/259157/72107

**Comment by alcohol** [comment]
The packagist repository can be found at https://github.com/composer/packagist

We do not maintain any other repositories. This means we also do not provide any support for other repositories.
