### ISSUE TITLE
Gone packages in cache

### ISSUE THREAD

**Issue by aude** [composer/composer#7473]
I'm working in the Magento 2 ecosystem, where composer can be used.

It happens that a package that was available from the Internet at some point, ceases to be available from the Internet later. It will continue to live in the composer cache, but that gives a "false impression" that the package is available. When deploying to another server later, the deployment is not successful because the package is not available.

Example:

1. Install package via composer. (package is added to cache)
2. Remove package from repo.
3. `rm -r vendor/ && composer install` (success, because of cache)
4. Deploy to stage server. (fails, because package is not available in repo)

Is there some way to fail earlier here? For example, is there a way to let composer remove cache entries that are not available from the Internet anymore?

This is a quite generic question, though I'd appreciate any nudge in the right direction :)

**Comment by stof** [comment]
Well, the goal of the cache is precisely to avoid downloading it from the Internet (because that's slow due to network being involved). So trying to download it to see whether it is still available does not make much sense IMO.

**Comment by alcohol** [comment]
You can just clear the cache manually if you want. Since we cache so much, adding checks to see if the remote source still exists would cause a significant performance impact that serves virtually no purpose.

**Comment by aude** [comment]
Your make good points, thanks for the feedback.

I could still imagine a command to check every item in the cache and remove items that are not available from the Internet anymore. For example `composer validate-cache`. It would be slow, but maybe useful to some.

Just food for thought at this point, I'll not pursue this idea further now.

**Comment by curry684** [comment]
> It happens that a package that was available from the Internet at some point, ceases to be available from the Internet later. 

This is also just bad practice from the repository maintainer. Packagist itself only allows package deletion up to a very low number of downloads (ref https://github.com/composer/packagist/issues/115) because, exactly like you experienced, it breaks dependent projects and there's nothing Composer can do about it.

[Read this anecdote for a good explanation on why yanking packages is a bad idea](https://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/).

**Comment by alcohol** [comment]
> Packagist itself only allows package deletion up to a very low number of downloads

Unfortunately we can only prevent deletion of the reference in packagist. There is nothing that we can do to prevent maintainers from removing their source (e.g. a repository on Github).
