### ISSUE TITLE
Need help analyzing intermittent connection failures

### ISSUE THREAD

**Issue by kwisatz** [composer/composer#7482]
I realize this is not a bug with the composer binary, but I'm trying to figure out if a certain behavior I'm seeing is due to issues with the network connection at our datacenter or with the network connection at the datacenter hosting getcomposer.org.

That being said, I'm seeing this kind of behavior and I've been seeing it for the past few days:

```bash
### 02:07-02:13
Jul 22 02:07:11 host-a2 puppet-agent[25890]: (/Stage[main]/Php::Composer::Auto_update/Exec[update composer]/returns)   The "https://getcomposer.org/versions" file could not be downloaded: SSL: Connection reset by peer
Jul 22 02:09:54 server2 puppet-agent[9377]: (/Stage[main]/Php::Composer::Auto_update/Exec[update composer]/returns)   The "https://getcomposer.org/versions" file could not be downloaded: SSL: Connection reset by peer
Jul 22 02:12:37 host-a1 puppet-agent[123190]: (/Stage[main]/Php::Composer::Auto_update/Exec[update composer]/returns)   The "https://getcomposer.org/versions" file could not be downloaded: SSL: Connection reset by peer

Jul 22 04:07:00 host-a2 puppet-agent[42777]: (/Stage[main]/Php::Composer::Auto_update/Exec[update composer]/returns) executed successfully
Jul 22 04:12:51 host-a1 puppet-agent[9023]: (/Stage[main]/Php::Composer::Auto_update/Exec[update composer]/returns) executed successfully

### 04:23-04:36
Jul 22 04:23:12 host1 puppet-agent[12253]: (/Stage[main]/Php::Composer::Auto_update/Exec[update composer]/returns)   The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: HTTP request failed

Jul 22 04:37:01 host-a2 puppet-agent[46916]: (/Stage[main]/Php::Composer::Auto_update/Exec[update composer]/returns) executed successfully
Jul 22 04:42:44 host-a1 puppet-agent[13124]: (/Stage[main]/Php::Composer::Auto_update/Exec[update composer]/returns) executed successfully


Jul 22 06:12:38 host-a1 puppet-agent[25395]: (/Stage[main]/Php::Composer::Auto_update/Exec[update composer]/returns) executed successfully
Jul 22 06:37:01 host-a2 puppet-agent[63686]: (/Stage[main]/Php::Composer::Auto_update/Exec[update composer]/returns) executed successfully
Jul 22 06:42:41 host-a1 puppet-agent[29755]: (/Stage[main]/Php::Composer::Auto_update/Exec[update composer]/returns) executed successfully

### 06:47-07:02
Jul 22 06:47:17 server3 puppet-agent[31608]: (/Stage[main]/Php::Composer::Auto_update/Exec[update composer]/returns)   The "https://getcomposer.org/versions" file could not be downloaded: SSL: Connection reset by peer
Jul 22 06:51:09 plaza2 puppet-agent[15480]: (/Stage[main]/Php::Composer::Auto_update/Exec[update composer]/returns)   The "https://getcomposer.org/versions" file could not be downloaded: SSL: Connection reset by peer
Jul 22 06:52:45 host1 puppet-agent[825]: (/Stage[main]/Php::Composer::Auto_update/Exec[update composer]/returns)   The "https://getcomposer.org/versions" file could not be downloaded: SSL: Connection reset by peer
Jul 22 06:55:21 host2 puppet-agent[28140]: (/Stage[main]/Php::Composer::Auto_update/Exec[update composer]/returns)   The "https://getcomposer.org/versions" file could not be downloaded: SSL: Connection reset by peer
Jul 22 07:01:41 server1 puppet-agent[10408]: (/Stage[main]/Php::Composer::Auto_update/Exec[update composer]/returns)   The "https://getcomposer.org/versions" file could not be downloaded: SSL: Connection reset by peer

Jul 22 07:07:06 host-a2 puppet-agent[2922]: (/Stage[main]/Php::Composer::Auto_update/Exec[update composer]/returns) executed successfully
Jul 22 07:09:54 server2 puppet-agent[30486]: (/Stage[main]/Php::Composer::Auto_update/Exec[update composer]/returns) executed successfully
Jul 22 07:12:39 host-a1 puppet-agent[33849]: (/Stage[main]/Php::Composer::Auto_update/Exec[update composer]/returns) executed successfully
```

As you can see, there are periods when all connections to getcomposer.org fail.

Yes, we're in a puppet context here, but if you look at https://github.com/voxpupuli/puppet-php/blob/v4.0.0/manifests/composer/auto_update.pp, there's no magic here.

Now my concrete question is: Are there any network outages/issues known on your side during those time-slots or not? Have others seen similar behavior during the same time-slots, or are we alone in this? In other words, before I blame this e.g. on our datacenter operator, I'd like to make sure it's not on getcomposer.org's side.

**Comment by alcohol** [comment]
I doubt @Seldaek could find much in the server logs.

**Comment by Seldaek** [comment]
Ok around 2/2:15 CEST there might be a problem on our end which we can't really fix easily though, the issue I see is that this time equals midnight UTC, and it seems a gazillion people have scripts to check for `composer self-update` at midnight, which triggers so many connections to our servers that it trips up the anti-DDoS protections at the host level leading to some connections possibly being dropped.

Regarding the other times you showed, I don't see anything odd on our end. The amount of traffic is not particularly dropping at 04:47-04:55 UTC for example.

**Comment by Seldaek** [comment]
I attempted some tweaks on our end, at least for the midnight issue, we'll see if that helps tonight.

**Comment by alcohol** [comment]
> and it seems a gazillion people have scripts to check for `composer self-update` at midnight

I did not even know that was a thing people do.. :sweat_smile:

**Comment by kwisatz** [comment]
Thanks for your help. We'll see if there's any difference tonight. I was
considering DDoS protection, but for the 4am or 6am issues, I highly
doubt that it's our update attempts alone ;)

**Comment by curry684** [comment]
> I did not even know that was a thing people do.. 

Likely some package-managed Composer versions also install stuff in `/etc/cron.d`.

**Comment by Seldaek** [comment]
@kwisatz did it help on your end? On mine I am not quite sure..

**Comment by kwisatz** [comment]
No, unfortunately, no change on our side. We saw the same issue again
between approx. 02:00 and 02:15 tonight and the night before.

I'm actually doing these updates far too often from our side, so making
sure they don't run that often might ensure that they don't run during
that timespan either, but that'd be just getting rid of the symptoms,
not the cause.

**Comment by Seldaek** [comment]
Think this got better these days so closing

**Comment by kwisatz** [comment]
👍 haven't seen this in quite a while
