### ISSUE TITLE
Can we somehow have a conf.d directory?

### ISSUE THREAD

**Issue by maniac0s** [composer/composer#7490]
I have the following issue that I want to have composer pulling from my own git server using my-domain/package-name as an install/update location.

Normally I'd be using 

    composer create-project drupal-composer/drupal-project:8.x-dev some-dir --stability dev --no-interaction

to create a new Drupal project. But to host my own drupa-project git repository to add own default modules, I mirrored the drupal-project and modified it's composer.json

The way I operated it is to run

    git clone -b 8.x git@gitolite:drupal-project project-name
    cd project-name
    composer create-project

This however gives me a clone of the drupal-project git repository and I have to remove the .git and init a new repo in order to have project-name an own git-repository, also I don't want to risk accidentally pushing project-related stuff into the generic drupal-project repository.

So I want to be able to run 

    composer create-project my/drupal-project:8.x-dev some-dir --stability dev --no-interactio

As I understood it, composer will try to look on github for https://github.com/my/drupal-project.git to pull from there. I had no better idea to add my-git.domain.com to Config.php to enable composer look on my own git-server. (Am I understanding this correctly at all?) However since Config.php is to be maintained by this repository here, I'd like to keep it that way and instead add custom variables in a file that I can add to .gitignore, so it won't cause a merge conflict when updating composer repository via git.

**Comment by YetiCGN** [comment]
You should add your own repository according to the docs: https://getcomposer.org/doc/05-repositories.md
