### ISSUE TITLE
Composer does not return error code when script not exists

### ISSUE THREAD

**Issue by iro88** [composer/composer#7491]
Like in: https://github.com/composer/composer/issues/1943
I expect that Composer will return error code when script not exists.

https://github.com/composer/composer/blob/158e1c95da02cc0b932de74f9a09a1c7b6cf654f/src/Composer/EventDispatcher/EventDispatcher.php#L190

**Comment by iro88** [comment]
I my case I had a typo in "build" script, so my CI process pass and delivery empty project without dependencies. Now I must write additional "ugly" check after build, before deploy.

**Comment by alcohol** [comment]
Or don't make typo's..


In general there are two paths we can take:

- path of early failure, most restrictive
- path of least resistance, try to proceed as gracefully as possible in most scenarios

a long time ago the choice was made for the second approach.

While I personally prefer the first also, mixing them is not a good idea. The first is also not very user friendly, while the second can sometimes lead to somewhat unexpected results.
