### ISSUE TITLE
Run composer validate from different commands

### ISSUE THREAD

**Issue by staabm** [composer/composer#7492]
As discussed in https://github.com/composer/composer/issues/5940#issuecomment-407660843 I would like to propose to internally call „composer validate“ from different commands, which can help/should help to find errors caused by invalid composer.json more easily.

I guess it would help in the following commands:
- at the end of composer diagnose
- when composer update/install runs into a error

What do you guys think?

**Comment by Seldaek** [comment]
- diagnose already does at least a partial schema check in checkComposerSchema
- Factory::createComposer also does a LAX_SCHEMA validation of the schema when loading the composer.json, which applies to all commands. But this only outputs errors, not warnings as that'd be very invasive.

If you wanna do more why not as long as it doesn't nag people needlessly.. I don't think this problem occurs that often tbh but obviously it's hard to tell.

**Comment by staabm** [comment]
> Factory::createComposer also does a LAX_SCHEMA validation of the schema when loading the composer.json, which applies to all commands

is this LAX validation done, because of performance problems or do not all operations require a strict schema?

**Comment by Seldaek** [comment]
Lax just means this:

```
            $schemaData->additionalProperties = true;
            $schemaData->required = array();
```

So we don't check for typo in top level property names, and we don't force name to be present. It's not that big a difference.

**Comment by stof** [comment]
note that `composer validate` performs more validation than only the schema validation.

**Comment by staabm** [comment]
Thanks 🙏
