### ISSUE TITLE
Composer 1.7-RC1 - wrong display of warning

### ISSUE THREAD

**Issue by OskarStark** [composer/composer#7494]
The warning about the `unzip` extension should be yellow, instead of exposing `<warn>` and `</warn>` tags 

![screenshot 2018-07-26 12 43 48](https://user-images.githubusercontent.com/995707/43258005-a22aebbe-90d1-11e8-946d-e1e49981fd4d.png)

**Comment by stof** [comment]
that's because the tag to put things in yellow is `<warning>`, not `<warn>`. Do you want to submit a PR to contribute a fix ?

**Comment by OskarStark** [comment]
> Do you want to submit a PR to contribute a fix ?

I would, but @Seldaek was to fast 😄
