### ISSUE TITLE
Composer 1.7-RC does not show "Loading from cache" or "Downloading (100%)"

### ISSUE THREAD

**Issue by OskarStark** [composer/composer#7498]
**Composer 1.6.5:**
![screenshot 2018-07-27 07 19 20](https://user-images.githubusercontent.com/995707/43302871-64c81bec-916d-11e8-8c94-2d341dd15472.png)

**Composer 1.7-RC1:**
![screenshot 2018-07-27 07 17 52](https://user-images.githubusercontent.com/995707/43302862-5a36ddb2-916d-11e8-9efc-569529fee830.png)

And btw. why is there "5 updates" but only 4 packages where updated? This belongs to both versions.

Thank you

**Comment by stof** [comment]
are you running it with `--no-progress` ?

**Comment by OskarStark** [comment]
no

**Comment by Seldaek** [comment]
Why 5 updates I don't know, one would have to debug that further on your use case. The missing string though we definitely should fix, not sure what's up there.
