### ISSUE TITLE
How to disable the cache

### ISSUE THREAD

**Issue by tobias74** [composer/composer#7500]
Due to restrictions of our project I cannot publish our composer.json here.

I will try to explain my situation in words:

I am developing an application and dependent libraries using composer. When installing dependencies with composer I use the option 

> --prefer-source

In the main project's composer.json I require those depencies with _**"@dev"**_

I would expect that composer pulled the latest commits from github when I run a composer install, but they are always installed "from cache". Only after I issue a new release in github I will get the new commits when running composer install.

Cache-Invalidation has been discussed here before, and a "--no-cache"-option has been dismissed as far as I know. Is there any way to get around the cache permanantly?

I tried running the clearcache-command. It tells me that all caches have been cleared. But a following install-command will still find everything in the cache and clone it from there.

Even setting 

> "cache-files-ttl": 0 

won't disable the cache.

**Comment by staabm** [comment]
Do you use „install“ or „update“ to update your dependencies?

**Comment by tobias74** [comment]
I use "update". As far as I understand, "update" ignores the package.lock while "install" repects it

**Comment by tobias74** [comment]
I have a workflow now: 

1. delete the vendor-folder
2. push a commit with a simple change (the README.md)
3. draft a new release with a new version-number
4. update the dependency to that exact version-number in composer.json
5. composer update

So that is the workflow now, seems legit.

**Comment by staabm** [comment]
We use a very similar scenario and it works for us without the need to delete the cache.

**Comment by alcohol** [comment]
Don't let the output mislead you.

Even when we install from source, we still clone into the source into the cache directory first, and then we create a dissociated clone of the clone in the cache (so it can be reused in multiple projects). This saves networking transfer.

**Comment by alcohol** [comment]
Anyway, if for some weird reason you really want to disable caching completely, just run composer as `COMPOSER_CACHE_DIR=/dev/null composer <command>`.

See https://getcomposer.org/doc/03-cli.md#composer-cache-dir

**Comment by dendihandian** [comment]
Anyone know how to prevent the `composer install` invoking github.com? The openshift setup from my client restricted to access github.com

**Comment by stof** [comment]
@dendihandian use Private packagist or a Satis repo hosting archives for all the dependencies you use, so that you don't need to download them from github.com (Satis would still need access to github of course when building the archives)
