### ISSUE TITLE
  The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by threeFatCat** [composer/composer#7503]
My `composer.json`:

```json
{
    "name": "ricadiz/composer",
    "require": {}
}

```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: WARNING
[Composer\Downloader\TransportException] The "http://packagist.org/packages.json" file could not be downloaded: failed to open stream: No connection could be made because the target machine actively refused it.

Checking https connectivity to packagist: WARNING
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: No connection could be made because the target machine actively refused it.

Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.6.5
PHP version: 7.2.7
PHP binary path: D:\xampp7\php\php.exe

```

When I run this command:

```
composer create-project --prefer-dist laravel/laravel testapp
```

I get the following output:

```
  [Composer\Downloader\TransportException]                                      
  The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: No connection could
  be made because the target machine actively refused it.         
```

Basically I was trying to setup composer in a corporate environment to enable to work with Laravel projects. I freshly installed latest XAMPP. But I have already spent days looking for solution on how to make composer work. I have already tried the following:

* Disable IPv6 wireless connection (Since I'm currently using laptop)
* Set/Remove environment variables (tried http_proxy alone, http_proxy, https_proxy, HTTP_PROXY, HTTP_PROXY, all four of them) but still would fail somehow
* Did restart every set of env variables
* Removed all the environment proxy variable and manually doing ```export HTTP_PROXY=....``` and ```export HTTPS_PROXY=...``` 
* Yes, I use credentials in my proxy ```username:password@host:port```

**Additional notes:**
* I used the windows installer to install composer, and I noticed that the installer doesn't accept leading ```http://``` or ```https://``` in the proxy field during installation. Which I also spent days troubleshooting how to install composer. I'm not using VM for now.
* I installed latest `cURL` and tried the following command:
``` curl https://packagist.org/package.json -vv```
And somehow got the json from the respose:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1456  100  1456    0     0   3586      0 --:--:-- --:--:-- --:--:--  3586{"packages":[],"notify":"https://packagist.org/downloads/%package%","notify-batch":"https://packagist.org/downloads/","providers-url":"/p/%package%$%hash%.json","search":"https://packagist.org/search.json?q=%query%&type=%type%","provider-includes":{"p/provider-2013$%hash%.json":{"sha256":"99bae025d4d2e751a27fe35e136f601de188eda7077be4d5f63a549ea97907db"},"p/provider-2014$%hash%.json":{"sha256":"9406108133abe969d70795f837a3a9f72b416d25ca63944d1fc43355fde3cacf"},"p/provider-2015$%hash%.json":{"sha256":"9e6c81496931a07012024abf1cf1c114e8b86188f643d9a6f5481dbda26d02cd"},"p/provider-2016$%hash%.json":{"sha256":"7a798e4cb4e4191c3932f06c5d6cf099b1397df3d8eee73f61f73ca8f6dbe917"},"p/provider-2017$%hash%.json":{"sha256":"31a86e95e9ba4cae26868d352250c93c2c20f8ff6f454cf7086ba066c1877e3c"},"p/provider-2017-10$%hash%.json":{"sha256":"b2da560198469600563d4428b4c7c769601802154d16b224cb559404567cad72"},"p/provider-2018-01$%hash%.json":{"sha256":"b1959d2e442d85a41d6c5fda0dca0946a342f2da07df60eae618a2ed19421a0d"},"p/provider-2018-04$%hash%.json":{"sha256":"4b39c9ca91e2bba7265b8b1f85bdb8dc522a5c8df00b322adfb43ac3c1d5c4a2"},"p/provider-2018-07$%hash%.json":{"sha256":"93936039e8fd151b21c68a396a7a1217e2d725803a2b54b0e1cad961c76aabfc"},"p/provider-archived$%hash%.json":{"sha256":"939a942590ec7e93239cd4beb63399da3206d5337563e0ac345a5b58f458b46e"},"p/provider-latest$%hash%.json":{"sha256":"793c519d05e378606154e744a199e151f88adb32f526294cd15c78895af3a3a8"}}}
```
* We're using a domain user account so basically my proxy authentication looks like this:
```domain/username:password```
* I can access the url using a web browser
* I got certificate errors for ```https://getcomposer.org``` also along the way but I already managed to fix it  by importing the necessary intermediate ca. 
* I tried to check run this command ``` openssl s_client -connect packagist.org:443``` and got this response:
```
connect: No error
connect:errno=0
```

I would like to be much in detail but I don't want this post to get long. Thanks.

**Comment by alcohol** [comment]
I would recommend you talk to your network administrator.

**Comment by johnstevenson** [comment]
> the installer doesn't accept leading http:// or https:// in the proxy field during installation. 

Yes it does. It accepts whatever value you choose to enter and creates a temporary `http_proxy` environment variable with that value, for the installer php script to use.

**Comment by threeFatCat** [comment]
@alcohol not sure yet what to tell the network admin since I can just access through ```cURL``` and web browser. I think I'll just try to figure out first which part composer can't access ```https://packagist.org```. 

I also wonder why during ```composer diagnose``` it was able to access ```https://api.github.com/..``` for checking rate limit but it can't for ```https://packagist.org``` and can access ```https://getcomposer.org/versions``` for ```Checking composer version```

**Comment by alcohol** [comment]
For proxy issues, try:
https://gist.github.com/naderman/377e40c1c76e0fe8b905c1a333c4112a

Details:
https://twitter.com/naderman/status/1029839134070853637

**Comment by threeFatCat** [comment]
I was able to resolved my issue now. But now, I'm using vm using Homestead hoping it will fix if I will use Linux, but not all, I don't think this contribute to the fix, anyway as mentioned in my first post I was getting error for the url `**http**://packagist.org/packages.json` and `**https**://packagist.org/packages.json` saying `No connection could be made because the target machine actively refused it.` during `composer diagnose` but getting `**OK**` at the rest, and I was able to take note that error will occur, if I have not setup properly the proxy or I have not specified any proxy at all.

Now if I specified the correct proxy, the error for both `**http**://packagist.org/packages.json` and `**https**://packagist.org/packages.json` disappear, but then I got error in `Checking HTTPS proxy support for request_fulluri` saying like `unable to verify ssl certificate` for urls `https://api.github.com` and `https://getcomposer.org` but as you noticed, I mentioned I got `**OK**` when there are no proxy specified. So that is where the confusion I had I was thinking both were related and it may be because of proxy or certificate but no it's not.

So what I did after all the digging, I finally was able to think **_what if_** I only apply the proxy in the url `**http**://packagist.org/packages.json` and `**https**://packagist.org/packages.json`? So I set in the environment variable:

`export no_proxy=.github.com,.getcomposer.org`

After that, this is now my result:

```
Checking platform settings: OK
Checking git settings: Executing command (CWD): git config color.ui
OK
Checking http connectivity to packagist: Downloading http://repo.packagist.org/packages.json using proxy tcp://172.20.172.1:9090
OK
Checking https connectivity to packagist: Downloading https://repo.packagist.org/packages.json using proxy tcp://172.20.172.1:9090
OK
Checking HTTP proxy: Downloading https://repo.packagist.org/packages.json using proxy tcp://172.20.172.1:9090
Downloading https://repo.packagist.org/p/provider-2013$5245d01edf52919d9cd07317a0358d87f7cbb0570a154fd2ae2c3f66723c1664.json using proxy tcp://172.20.172.1:9090
OK
Checking HTTP proxy support for request_fulluri: Downloading http://repo.packagist.org/packages.json using proxy tcp://172.20.172.1:9090
OK
Checking HTTPS proxy support for request_fulluri: Downloading https://api.github.com/repos/Seldaek/jsonlint/zipball/1.0.0

Following redirect (2) https://codeload.github.com/Seldaek/jsonlint/legacy.zip/1.0.0
Downloading https://codeload.github.com/Seldaek/jsonlint/legacy.zip/1.0.0
OK
Checking github.com oauth access: Downloading https://api.github.com/
OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: Downloading https://getcomposer.org/versions
OK
Composer version: 1.7.2
PHP version: 7.2.9
PHP binary path: /usr/bin/php7.2
```

**Comment by tounsils** [comment]
I had the same problem,
I figured out that I have an other php 5.5 installed along with xampp php version 7.2. So i launched the command (composer create-project symfony/skeleton MyProject) under php 7.2 folder and it was really awesome :)

**Comment by NwosuCC** [comment]
This link has a composer config solution that worked for me:
https://laravel.io/forum/solved-issues-with-nesbotcarbon

**Comment by lucashtc** [comment]
Solution by  @threeFatCat 

> SOLUTION:
export no_proxy=.github.com,.getcomposer.org


resolved
thank @threeFatCat.

**Comment by tewshi** [comment]
based on the link shared by @NwosuCC I sorted it out while trying to install laravel/horizon on Ubuntu using
` composer config -g repo.packagist composer https://repo.packagist.org`

**Comment by RMSHT** [comment]
> based on the link shared by @NwosuCC I sorted it out while trying to install laravel/horizon on Ubuntu using
> ` composer config -g repo.packagist composer https://repo.packagist.org`

Thanks

**Comment by 7bamboo** [comment]
For me all the above solutions didn't work. 
However, this did work - 
networksetup -setv6off Wi-Fi
composer create-project --prefer-dist laravel/laravel app123 //or  lumen new app123
networksetup -setv6automatic Wi-Fi

Read more about it https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode

**Comment by kaitaylor** [comment]
> based on the link shared by @NwosuCC I sorted it out while trying to install laravel/horizon on Ubuntu using
> ` composer config -g repo.packagist composer https://repo.packagist.org`

OMG thank you @tewshi so much. I have tried so many solutions before this including updating PHP and mySQL, adding a flag to allow non secure http, manually updating composer packages.. and a whole lot more. But this little command worked like magic! Thank you again!

**Comment by miskerbirhanu** [comment]
@tewshi thank you so much..

**Comment by moslem-deris** [comment]
I just restarted my OS and the error was gone!

**Comment by tewshi** [comment]
You’re welcome @miskerbirhanu

**Comment by hvrlee** [comment]
![Capture](https://user-images.githubusercontent.com/23356925/73633148-e8077e80-4698-11ea-8833-927b6d5c77da.PNG)


how do fix??? help please

**Comment by saber13812002** [comment]
it looks like iran wifi internet i change to IR-MCI my mobile phone and it is installed as well

**Comment by peter279k** [comment]
Recently I got this issue at some moments.

After retrying the composer command, it will be successful to execute without error message.

I think this error message is about my Internet network connection is unreachable temporarily.

**Comment by aortegae** [comment]
I have got this one,
Anybody knows how to solve?

<img width="978" alt="Captura de Pantalla 2020-06-09 a la(s) 16 32 30" src="https://user-images.githubusercontent.com/58084141/84203289-d3842a00-aa6e-11ea-8444-babf01695d28.png">

**Comment by peter279k** [comment]
> 
> 
> I have got this one,
> Anybody knows how to solve?
> 
> <img alt="Captura de Pantalla 2020-06-09 a la(s) 16 32 30" width="978" src="https://user-images.githubusercontent.com/58084141/84203289-d3842a00-aa6e-11ea-8444-babf01695d28.png">

I sometimes suffer this issue and I also run related `composer` command again.

And it will be successful without any error.

**Comment by AbhayPai** [comment]
![image](https://user-images.githubusercontent.com/14177170/85275571-17d1ea00-b4b3-11ea-8196-8d77881d7962.png)
![image](https://user-images.githubusercontent.com/14177170/85275897-93339b80-b4b3-11ea-96d0-fc52c3996cc0.png)
Facing this issue; i switched my internet but it didn't work

**Comment by jaiwalker** [comment]
the above one is temperory look at https://github.com/composer/composer/issues/9003

**Comment by aortegae** [comment]
Is not temporary, in my case it was because I have got IPv6 turned on in my network config, so I turned off while composer is running.

**Comment by MohammadShakilCSE** [comment]
what is the problem??

  [Composer\Downloader\TransportException]
  Unable to use a proxy: malformed http_proxy url


require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...

**Comment by peter279k** [comment]
It seems that the Composer try to download some files behind HTTP proxy.

Could you use the `composer install -vvvv` to present more details?

**Comment by MohammadShakilCSE** [comment]
> 
> 
> It seems that the Composer try to download some files behind HTTP proxy.
> 
> Could you use the `composer install -vvv` to present more details?
it shows what is the problem ?/
Composer could not find a composer.json file in C:\Users\xxxxxxxxx
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
