### ISSUE TITLE
Output of composer run-script is messed up

### ISSUE THREAD

**Issue by emodric** [composer/composer#7505]
Truth to be told, I'm not really sure if this is an issue with PHPStan or Composer, but it only happens when I run the Composer script.

Basically, when using scripts, the output is sometimes messed up (cca 1 out of 5 times), as shown in the screenshot below. I realize "sometimes" is not reproducable, but I'm not really sure how to debug it properly.

My `composer.json`:

```json
{
    "scripts": {
        "phpstan": "@php vendor/bin/phpstan analyse --level=7 --ansi lib bundle"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.6.5
PHP version: 7.2.8-1+ubuntu18.04.1+deb.sury.org+1
PHP binary path: /usr/bin/php7.2
```

When I run this command:

```
composer run-script phpstan
```

I get the following output:

![screenshot from 2018-08-01 10-01-32](https://user-images.githubusercontent.com/362286/43509111-fb1eca34-9571-11e8-9230-dff8e39a07fb.png)

And I expected this to happen:

I expect the output to always be correct.

**Comment by alcohol** [comment]
Generally, if you really care about the output visually, then you should run the script(s) directly, and not through `composer run-script`. Handling process output remains a "best effort" mostly. They are a convenience feature, nothing more.
