### ISSUE TITLE
Unable to remove unused package

### ISSUE THREAD

**Issue by torkiljohnsen** [composer/composer#7508]
Composer made me aware that a package was outdated, and needed upgrading.

    1 package is not up to date:
     - google/cloud (v0.49.0) latest is v0.69.0

This package was unknown to me, but I am working with several other developers, so I checked:

    $ composer why google/cloud
    There is no installed package depending on "google/cloud"

Long story short; since the package was not in use, I figured I would remove it, but  I soon discovered that this was not that easy. For instance with remove:

    $ composer remove google/cloud
    google/cloud is not required in your composer.json and has not been removed

I even tried `composer require google/cloud:^0.49`, and then did `composer remove google/cloud` afterwards, 
…but it is neither removed from the `vendor` folder nor the `composer.lock` file.

A bit later though, I may have stumbled onto the explanation by accident, when I found that I had required `google/cloud-storage` but could not see it in the vendor folder:

    $ composer why google/cloud-storage
    google/cloud                          v0.49.0  replaces  google/cloud-storage (1.3.0)       
    superbalist/flysystem-google-storage  7.0.0    requires  google/cloud-storage (>=1.0 <1.4)

So composer can't see why `google/cloud` is required, since `google/cloud-storage` is the one that is really required, but it is replaced by `google/cloud`. Or so it might seem.

Is this expected behavior?

IMO this would be better:

    $ composer why google/cloud
    google/cloud replaces google/cloud-storage, which is required by superbalist/flysystem-google-storage

**Comment by Seldaek** [comment]
Related/similar issue to https://github.com/composer/composer/issues/8059

**Comment by Seldaek** [comment]
Closing as I cannot repro anymore and #8059 is resolved so I am hoping this one is too.
