### ISSUE TITLE
Composer show does not consider version constraints in composer.json

### ISSUE THREAD

**Issue by JacobSanford** [composer/composer#7509]
My `composer.json`:

```json
...
    "require": {
        "composer/installers": "^1.2.0",
        "cweagans/composer-patches": "~1.6.1",
        "drupal-composer/drupal-scaffold": "~2.2.0",
        "drupal/bootstrap": "3.12",
        "drupal/chosen": "2.6",
        "drupal/config_update": "1.5",
        "drupal/console": "~1.0",
        "drupal/core": "8.5.6",
        "drupal/csv_serialization": "1.4",
        "drupal/editor_file": "1.2",
        "drupal/features": "3.7",
        "drupal/field_group": "3.0-beta1",
        "drupal/google_analytics": "2.3",
        "drupal/honeypot": "1.27",
        "drupal/migrate_plus": "4.0-beta3",
        "drupal/migrate_source_csv": "2.2",
        "drupal/migrate_tools": "4.0-rc1",
        "drupal/pathauto": "1.2",
        "drupal/search_api": "1.9",
        "drupal/search_api_solr": "1.2",
        "drupal/simple_entity_merge": "1.0",
        "drupal/simple_gmap": "1.4",
        "drupal/taxonomy_access_fix": "2.6",
        "drupal/taxonomy_manager": "1.0-alpha1",
        "drupal/token": "1.3",
        "drupal/tvi": "1.0-beta2",
        "drupal/twig_field_value": "1.1",
        "drupal/views_autocomplete_filters": "1.2",
        "drupal/views_slideshow": "4.6",
        "drush/drush": "^8.1.15",
        "harvesthq/chosen": "~1.8",
        "malsup/jquery.cycle": "1.0",
        "solarium/solarium": "~3.8",
        "teqneers/php-stream-wrapper-for-git": "1.0.1",
        "webflo/drupal-finder": "^0.3.0",
        "webmozart/path-util": "^2.3"
    },
...
```

Output of `composer diagnose`:

```
/app/html # composer diagnose
Checking composer.json: WARNING
require.drupal/bootstrap : exact version constraints (3.12) should be avoided if the package follows semantic versioning
require.drupal/chosen : exact version constraints (2.6) should be avoided if the package follows semantic versioning
require.drupal/config_update : exact version constraints (1.5) should be avoided if the package follows semantic versioning
require.drupal/core : exact version constraints (8.5.6) should be avoided if the package follows semantic versioning
require.drupal/csv_serialization : exact version constraints (1.4) should be avoided if the package follows semantic versioning
require.drupal/editor_file : exact version constraints (1.2) should be avoided if the package follows semantic versioning
require.drupal/features : exact version constraints (3.7) should be avoided if the package follows semantic versioning
require.drupal/field_group : exact version constraints (3.0-beta1) should be avoided if the package follows semantic versioning
require.drupal/google_analytics : exact version constraints (2.3) should be avoided if the package follows semantic versioning
require.drupal/honeypot : exact version constraints (1.27) should be avoided if the package follows semantic versioning
require.drupal/migrate_plus : exact version constraints (4.0-beta3) should be avoided if the package follows semantic versioning
require.drupal/migrate_source_csv : exact version constraints (2.2) should be avoided if the package follows semantic versioning
require.drupal/migrate_tools : exact version constraints (4.0-rc1) should be avoided if the package follows semantic versioning
require.drupal/pathauto : exact version constraints (1.2) should be avoided if the package follows semantic versioning
require.drupal/search_api : exact version constraints (1.9) should be avoided if the package follows semantic versioning
require.drupal/search_api_solr : exact version constraints (1.2) should be avoided if the package follows semantic versioning
require.drupal/simple_entity_merge : exact version constraints (1.0) should be avoided if the package follows semantic versioning
require.drupal/simple_gmap : exact version constraints (1.4) should be avoided if the package follows semantic versioning
require.drupal/taxonomy_access_fix : exact version constraints (2.6) should be avoided if the package follows semantic versioning
require.drupal/taxonomy_manager : exact version constraints (1.0-alpha1) should be avoided if the package follows semantic versioning
require.drupal/token : exact version constraints (1.3) should be avoided if the package follows semantic versioning
require.drupal/tvi : exact version constraints (1.0-beta2) should be avoided if the package follows semantic versioning
require.drupal/twig_field_value : exact version constraints (1.1) should be avoided if the package follows semantic versioning
require.drupal/views_autocomplete_filters : exact version constraints (1.2) should be avoided if the package follows semantic versioning
require.drupal/views_slideshow : exact version constraints (4.6) should be avoided if the package follows semantic versioning
require.malsup/jquery.cycle : exact version constraints (1.0) should be avoided if the package follows semantic versioning
require.teqneers/php-stream-wrapper-for-git : exact version constraints (1.0.1) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.6.5
PHP version: 7.2.8
PHP binary path: /usr/bin/php7
```

When I run this command:

```
/app/html # composer show -l --direct --outdated
```

I get the following output:

```
drupal-composer/drupal-scaffold     2.2.0  2.5.3  Composer Plugin for updati...     
drupal/console                      1.0.0  1.8.0  The Drupal CLI. A tool to ...
drupal/search_api_solr              1.2.0  2.0.0  Offers an implementation o...
drush/drush                         8.1.17 9.3.0  Drush is a command line sh...
harvesthq/chosen                    1.8.3  v1.8.7
solarium/solarium                   3.8.1  4.0.0  PHP Solr client
teqneers/php-stream-wrapper-for-git v1.0.1 v2.0.0 Git Stream Wrapper for PHP
webflo/drupal-finder                0.3.0  1.1.0  Helper class to locate a D...
```

And I expected this to happen:

```
drupal-composer/drupal-scaffold     2.2.0  2.5.3  Composer Plugin for updati...     
drupal/console                      1.0.0  1.8.0  The Drupal CLI. A tool to ...
drupal/search_api_solr              1.2.0  2.0.0  Offers an implementation o...
harvesthq/chosen                    1.8.3  v1.8.7
teqneers/php-stream-wrapper-for-git v1.0.1 v2.0.0 Git Stream Wrapper for PHP
```
Specifics:
* IMHO updates that would not be installed with ```composer update``` (due to honoring constraints)  should not be listed. (drush, solarium, drupal-finder). 
* Updates with exact versions and no constraints show all updates.

**Comment by jvasseur** [comment]
Showing packages that can be updated, even if the new version don't match your constraints is exactly what `--outdated` is for.  If you want to get the updates available that match your constraints you can use `composer update --dry-run`.

**Comment by JacobSanford** [comment]
Hi @jvasseur, thanks for the reply. I sincerely appreciate it.

To explain our use case : we're generating reports of updates that are needed in live applications.

My pain point with your suggestion :  ```composer update --dry-run``` does not accept the ```--direct``` switch. This means the tools we have written to report available updates need to do two runs : one to store package names that respect constraints with ```composer update --dry-run```, and then another run with ```composer show``` and we then filter the packages that showed up in the previous update command. Otherwise dependencies show up in the report.

Certainly this is an edge case, but it can't be novel.

Thanks!

**Comment by jvasseur** [comment]
The equivalent of the `--direct` option for update is `--root-reqs` so `composer update --root-reqs --dry-run` should do what you want.

**Comment by alcohol** [comment]
The problem here is that there is a wide range of opinions on what the output could or should be, and we simply cannot cater to them all at the same time easily. I understand that some companies have very strict policies when it comes to updating dependencies. You're asking us to respect version constraints when listing available updates, but at the same time also ignore them (a fixed version is also a constraint). This is simply too complicated of a scenario to offer from our end. I am afraid you will have to find some work-around yourself.


My 2 cents though:

> we're generating reports of updates that are needed in live applications

If you have a solid deployment pipeline with sufficient test coverage, you should just update everything all the time. In my experience, frequent small updates are much easier to handle than less frequent mass updates.

**Comment by JacobSanford** [comment]
@alcohol -> I completely understand. The more I thought about it (as I wrote the replies above), I began to realize that we're trying to do something quite specific - as you mentioned. Listing updates for pinned dependencies (--outdated) while respecting constraints otherwise. Perhaps the time SHOULD be spent expanding our test coverage into something where we're more confident with unpinning those Drupal module dependencies and just running with it. We've been bitten before by that, so it is difficult to swallow.

I appreciate the time and thoughts. Thanks!

**Comment by PilarLF** [comment]
Hi! I'm having this error:
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - drupal/core is locked to version 10.3.6 and an update of this package was not requested.
    - drupal/core 10.3.6 requires composer-runtime-api ^2.1 -> found composer-runtime-api[2.0.0] but it does not match the constraint.
  Problem 2
    - drupal/core 10.3.6 requires composer-runtime-api ^2.1 -> found composer-runtime-api[2.0.0] but it does not match the constraint.
    - drupal/core-recommended 10.3.6 requires drupal/core 10.3.6 -> satisfiable by drupal/core[10.3.6].
    - drupal/core-recommended is locked to version 10.3.6 and an update of this package was not requested.

but actually my composer version is 2.8, 
so why is using v2.0.9 to run?

**Comment by stof** [comment]
@PilarLF please open a dedicated issue providing full details instead of commenting on a random issue closed more than 6 years ago.

**Comment by PilarLF** [comment]
yep :) thanks for dedicating your time to write this 
have a great day
