### ISSUE TITLE
Support for alternative requirements

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#751]
Example:

```json
{
    "require": {
        "symfony/yaml": "2.*",
        "redis": [
            { "ext-phpredis": "*" },
            { "predis/predis": "0.7.*" }
        ]
    }
}
```

The package would then have a require on `redis-some-hash-of-the-array: 1.0.0` or the like. All packages matching the alternative requirements would have a provide added with `redis-some-hash-of-the-array: 1.0.0`. That should solve it pretty easily.

**Comment by shehi** [comment]
Question: Has this discussion stalled? :)

**Comment by slbmeh** [comment]
@shehi appears that way, I've been using the provide method for nearly a year now and it seems to be sufficient for the minimal amount of use cases I've encountered.

**Comment by andrerom** [comment]
Any update on this?

Looking for way to specify either `ext-gd`, `ext-imagick ` or `ext-gmagick` is installed *(yes, so only need this for system requirements)*

**Comment by slbmeh** [comment]
@andrerom AFAIK you can solve that by taking your variably dependent logic and segregating it into a small package that provides a virtual package which your larger project depends on.

````json
{
  "name": "my/gd-impl",
  "require": {
    "ext-gd": "*"
  },
  "provide": {
    "my/image-processor": "1.0.0"
  }
}


{
  "name": "my/imagick-impl",
  "require": {
    "ext-imagick": "*"
  },
  "provide": {
    "my/image-processor": "1.0.0"
  }
}


{
  "name": "my/gmagick-impl",
  "require": {
    "ext-gmagick": "*"
  },
  "provide": {
    "my/image-processor": "1.0.0"
  }
}


{
  "name": "my/awesome-project",
  "require": {
    "my/image-processor": "^1.0.0"
  }
}
````

**Comment by andrerom** [comment]
would work, but then I basically need to setup 3 repos with packagist, just for one file in each of them then. Unless I manage to convince imagine maintainers to do this where it makes sense, in their setup, where the actual drivers for these backends exists.

**Comment by slbmeh** [comment]
@andrerom I usually approach it by abstracting the driver that works with different extensions into a separate lib... then i don't need to care which one they picked and just expect my interface to be implemented...

**Comment by andrerom** [comment]
Sure, but I'm not the maintainer of those libs, so that would be completely up to them if they would appreciate splitting out their code.

**Comment by slbmeh** [comment]
@andrerom that isn't what I meant... I break out the piece of my code that works with the extension or dependency.  Example being I have an API client that can work with guzzle 3 or guzzle 5... i took the variable code and created an interface... then i wrote two micro libs responsible for handling the pieces directly with guzzle and injected them into my project with an autoload file config.

IMO a cleaner approach.  Rather than having all of the code for imagick, gmagick, and gd in your project when it may only be using one at a time you put that with the composer.json file that depends on the extension you are interacting with.

**Comment by Seldaek** [comment]
As written in #2940 I think this is unlikely to happen so I'm closing this now. There are ways to do this as stated above, and the rest of the most complicated checks can be left to runtime checks IMO, if we try to build all this into composer it might end up just adding more complexity for little apparent benefit.
