### ISSUE TITLE
JSON formatter breaks UTF-8

### ISSUE THREAD

**Issue by kamazee** [composer/composer#7510]
In poor environments (PHP < 5.4), a custom function is used to format JSON: 
https://github.com/composer/composer/blob/f24fcea35b4e8438caa96baccec7ff932c4ac0c3/src/Composer/Json/JsonFile.php#L198-L226
https://github.com/composer/composer/blob/f24fcea35b4e8438caa96baccec7ff932c4ac0c3/src/Composer/Json/JsonFormatter.php#L37

When UTF-8 code exceeds certain size, it can't be represented with 1 escape sequence (`\uXXXX`). So, if a 4-byte character occurs, it's escaped, and then attempt to unescape it actually breaks UTF-8 and, consequently, JSON. [Here is an example](https://travis-ci.org/JakubOnderka/PHP-Parallel-Lint/jobs/409347867#L199): on PHP 5.3.3 composer reads `composer.json`s; one of them is [nette/tester's json](https://github.com/nette/tester/blob/285563e242bdabade7d8aa9d69ac457db7d4cac5/composer.json); it contains fancy green and red unicode apples.

```
php > echo strlen("🍏");
4
php > var_dump(json_encode("🍏"));
string(14) ""\ud83c\udf4f""
```

Formatter treats `'"\ud83c\udf4f"'` as 2 characters, which is wrong. As a result, installed.json is written but can never be read again: JSON parser chokes on broken UTF-8 (which is shown in build log).

I created a test case that depicts the issue (will push when issue is created; should appear below).

I thought about fixing it but decided to reach out first. The issue is there for a very long time (`git blame` says it's more than 4 years), so it's certainly not a hot high-priority thing; also fixing it properly is far from being trivial: we basically would need to port unescaping unicode characters to PHP. This is a maintenance burden that imposes nearly 0 profit; so the question is: wouldn't it be more pragmatic to ditch support for unescaping unicode for PHP < 5.4 at all? Well, there could be compromises (maybe we could be off with a workaround that preserves backward compatibility and decodes *some* characters, e.g. escape sequence for which starts with 0: it would cover a ton of real-life use cases (descriptions in most, if not all, of European and even [CJK](https://en.wikipedia.org/wiki/CJK_Unified_Ideographs) languages), leave fancy green apples escaped, and avoid adding too much complexity for nothing.

What do you think?

**Comment by Seldaek** [comment]
Removing unescaped unicode on php 5.3 sounds reasonable at this point. Definitely don't want to add lots of code to fix something that's hardly a problem and only on 5.3. Would be great if you can send a PR doing that.

**Comment by kamazee** [comment]
@Seldaek I meant just leaving some characters escaped rather than removing them (should be better because it neither changes nor breaks original info, just makes it harder to read with a human eye).

I'll try to address this and update the PR with a failing test case.
