### ISSUE TITLE
Composer sends `ansi` parameter to invoked script causing it to fail

### ISSUE THREAD

**Issue by Bilge** [composer/composer#7517]
Since Composer 1.7.0, running a script invokes the script with a forced `--ansi` parameter, which may case the invoked command to fail because it does not recognize this parameter.

```json
  "scripts": {
    "test": "phpunit -c test"
}
```

>composer test -- --coverage-clover=build/logs/clover.xml

>\> phpunit -c test '--coverage-clover=build/logs/clover.xml' '--ansi'
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
unrecognized option --ansi
Script phpunit -c test handling the test event returned with error code 1

See also the [Travis build output](https://travis-ci.org/Porter-connectors/FileConnector/jobs/411812130).

**Comment by Seldaek** [comment]
This is fixed by https://github.com/composer/xdebug-handler/pull/69 - I didn't realize this was a limitation of the xdebug-handler lib until now, sorry about that.

**Comment by Seldaek** [comment]
@johnstevenson thanks! I'll get a new composer release out soon then.

**Comment by Seldaek** [comment]
1.7.2 is out
