### ISSUE TITLE
Error Color Windows PowerShell 

### ISSUE THREAD

**Issue by franckentien** [composer/composer#7523]
Hello,

I got an minor error with Windows PowerShell and composer.
I use composer for an Symfony 3.4.x project ran on wamp 
My composer.phar was: `Composer version 1.7.0 2018-08-03 15:39:07`

When I run this command: 

```
php .\composer.phar update
```

The result color change and was good but at the end of the script it stay yellow:

I run the command with default color to white and at the end of the commande the default color was yellow.
Normaly it's must set the color to white of default color at the end of the script.

The first command: 

![The first command](https://user-images.githubusercontent.com/6872773/43701359-373e351c-9956-11e8-94a9-045008e10868.png)

The difference when it's run just after: 

![It's Yellowp](https://user-images.githubusercontent.com/6872773/43701405-6011a49c-9956-11e8-828c-109f13922c7f.png)

Thanks

**Comment by alcohol** [comment]
The output seems to originate from the post handler of the `symfony/asset` package. I would suggest opening an issue on their repo.
