### ISSUE TITLE
Allow multiple package versions to be installed in parallel

### ISSUE THREAD

**Issue by dohpaz42** [composer/composer#7526]
[I have read the previous stance on the idea of allowing composer to manage multiple versions of a given package.](https://github.com/composer/composer/issues/2167) However, I would like to re-open the discussion as there are valid use cases for wanting multiple versions installed in parallel. 

I would counter that this is completely possible based on the following arguments:

1. It's not composer's responsibility to ensure that a developer doesn't try to do something they aren't supposed to do; mind you, it would be fair of composer to issue a stern warning, but ultimately allow a developer to shoot themselves in the foot if that's what they so choose to do.
1. PHP's namespace aliasing and/or composer's autoloader might be a way to work around loading two classes from different versions of a package -- in other words, manipulate the namespace in the autoloader so that if I install versions `2.0` and `3.0` of `package/xyz` (with a namespace of `Package\Xyz`) I could reference them in code as either `Package\Xyz\2.0\MyClass or `Package\Xyz\3.0\MyClass`. And if I wanted to import both of them, I could alias the second one to a non-conflicting class name (see point 1 above).
1. There are use-cases where packages are installed to be run as commands (e.g., phpunit, pdepend, phpcs, phpdoc, phpstan, et al) and would not be included/required directly into a PHP project's code base

One use case I've run into is that I want to install `ramsey/jenkins-php`, which inheritantly depends on `nikic/php-parser: ^1.0`, as well as `phpstan/phpstan-symfony` which inheritantly depends on `nikic/php-parser: ^4.0`. Both are commands to be run from a shell, so there would be no actual conflict with each other. The only thing stopping them from both being installed side by side is that composer does not support multiple versions of the same library.

I understand that this is probably going to be a decisive feature request. I also understand I've probably not thought out every single possible hurdle to making this happen. But I feel like this is an important request to discuss with you and the composer community.

Thank you!

**Comment by alcohol** [comment]
For some of your use-cases there are already existing work-arounds. In other cases, we simply do not support it. This discussion will lead nowhere.
