### ISSUE TITLE
Allow multiple package versions to be installed in parallel Pt 2

### ISSUE THREAD

**Issue by dohpaz42** [composer/composer#7527]
Re: https://github.com/composer/composer/issues/7526#issuecomment-410733739

Please do not lock this conversation without actually having a conversation. 

You say there are work arounds, yet you do not list them. You suggest this topic will lead nowhere, yet you refuse to actually find out.

**Comment by dohpaz42** [comment]
@alcohol if you do not wish to have this conversation, please do not reply to said conversation. Please leave it open for others to discuss.

**Comment by Seldaek** [comment]
Look into https://github.com/bamarni/composer-bin-plugin if you really want to install tools globally. We recommend installing tools in every project's require-dev. And we will not spend our time dealing with version conflicts as you requested.

**Comment by dohpaz42** [comment]
@Seldaek The composer-bin-plugin looks about what I was looking for, so thank you for the pointer!

**Comment by localheinz** [comment]
@dohpaz42 

You might also be interested in taking a look at https://github.com/phar-io/phive.

**Comment by dohpaz42** [comment]
@localheinz Someone else mentioned it to me, and I did look at it. Right now, though, it's not quite there yet, but I definitely see the potential!
