### ISSUE TITLE
Regression in composer plugins support 1.7.0

### ISSUE THREAD

**Issue by neomerx** [composer/composer#7529]
My `composer.json` has a dependency to custom composer [provider](https://getcomposer.org/doc/articles/plugins.md) which includes custom `CommandProvider` and a command extending `BaseCommand`.

When I run any composer command (without `--no-plugins`) it loads and runs the provider (exactly as expected). However, the provider has a dependency on another package and it's defined in provider's composer.json ("require" section).

On 1.6.5 and earlier composer loaded those dependencies from provider's composer.json but since 1.7.0 it seems stopped to do that which looks like a bug. If I downgrade to 1.6.5 it works just fine but on 1.7.0 it gives `PHP Fatal error:  Uncaught Error: Class '<interface class from external lib>' not found in <a class from plugin>`.

Output of `composer diagnose  --no-plugins`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 1.7.0
PHP version: 7.2.8
PHP binary path: /usr/bin/php
```

**Comment by Seldaek** [comment]
https://github.com/composer/composer/releases/tag/1.7.1 is out now
