### ISSUE TITLE
docs: installer-paths

### ISSUE THREAD

**Issue by aleclarson** [composer/composer#7532]
Please add the following to the documentation [here](https://getcomposer.org/doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md#how-do-i-install-a-package-to-a-custom-path-for-my-framework-):
- talk about `type:` usage, give an example
- `installer-paths` is order-dependent. If you want to move a package by name, it should come before the installer path of a `type:` that matches that same package

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/pull/8746
