### ISSUE TITLE
Path repository type not picking up changes to composer.json

### ISSUE THREAD

**Issue by carnage** [composer/composer#7543]
I have a couple of local packages, which I am developing in parallel to the main app and so have added them, for the time being, to composer.json in the main app as path repositories. Composer correctly found and symlinked these packages. 

I edited the autoload section in one of the packages and ran `composer dump` the changes weren't picked up, so I ran `composer update` output "nothing to install or update" It was only after *committing* the changes into git that `composer update` saw them and updated the autoloader.

This is probably an edge case use case, so it might be a better idea to just add a note to the docs that this is how it works to save others spending time chasing down the problem in the future.

**Comment by kdambekalns** [comment]
I had mixed results… sometimes a commit seems to help, at other times the only way to get composer to see the changes is to remove the existing symlink to the package with the changed dependencies.

**Comment by trompx** [comment]
I am havingthe same problem.
When I add a required package to the local package composer.json (which is symlinked in the main project composer.json), doing `composer update` in the main project doesn't install the new package.
For this to work, I need to **remove the symlink** first.
I tried to automate this with a `pre-update-cmd` script but most of the time I need to run twice `composer update` for it to work.

**Comment by Seldaek** [comment]
I'd say this has been fixed in recent versions as path repos are always implicitly updated now.
