### ISSUE TITLE
Composer fail to update dependencies which are using `dev-master`.

### ISSUE THREAD

**Issue by shulard** [composer/composer#7546]
My `composer.json`:

```json
{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.2.0",
        "ext-iconv": "*",
        "enqueue/messenger-adapter": "^0.1.0",
        "enqueue/redis": "^0.8.23",
        "league/flysystem": "^1.0",
        "league/fractal": "^0.17.0",
        "nelmio/alice": "^3.4",
        "php-http/httplug-pack": "^1.1",
        "predis/predis": "^1",
        "sensio/framework-extra-bundle": "^5.2@dev",
        "symfony/asset": "^4.1",
        "symfony/console": "^4.1",
        "symfony/debug-pack": "^1.0",
        "symfony/dotenv": "^4.1",
        "symfony/expression-language": "^4.1",
        "symfony/flex": "^1.0",
        "symfony/form": "^4.1",
        "symfony/framework-bundle": "^4.1",
        "symfony/messenger": "^4.1",
        "symfony/orm-pack": "^1.0",
        "symfony/security-bundle": "^4.1",
        "symfony/serializer-pack": "^1.0",
        "symfony/translation": "^4.1",
        "symfony/twig-bundle": "^4.1",
        "symfony/validator": "^4.1",
        "symfony/web-link": "^4.1",
        "symfony/webpack-encore-pack": "^1.0",
        "symfony/yaml": "^4.1"
    },
    "require-dev": {
        "phpspec/phpspec": "^5",
        "roave/security-advisories": "dev-master",
        "squizlabs/php_codesniffer": "^3.2",
        "symfony/browser-kit": "^4.1",
        "symfony/phpunit-bridge": "^4.1",
        "symfony/process": "^4.1",
        "symfony/property-access": "^4.1",
        "symfony/web-server-bundle": "^4.1"
    },
    "config": {
        "bin-dir": "bin",
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ],
        "test": "SYMFONY_PHPUNIT_VERSION=6.5 simple-phpunit",
        "cs": "phpcs --standard=phpcs.xml",
        "cbf": "phpcbf --standard=phpcs.xml",
        "cs-fixer": "php-cs-fixer fix --allow-risky=yes --rules=no_unused_imports,ordered_imports,declare_strict_types,no_superfluous_phpdoc_tags,no_useless_else,no_useless_return"
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "id": "01CCBFAZ1N3SKRQNG36YSWYV4G",
            "allow-contrib": false
        }
    }
}

```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.7.1
PHP version: 7.2.8
PHP binary path: /usr/local/bin/php
```

When I run this command:

```
$ composer outdated

phpdocumentor/type-resolver 0.4.0      0.6.3
roave/security-advisories   dev-master dev-master f834fd0 Prevents installation of composer packages with known se...

$ composer update 

Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
```

And I expected this to happen:

So there is actually one update to be made during the `composer updated`. But if I run `composer outdated`, the dependencies were not updated...

I tried to clear all cache, and also to run composer from a container to have a totally clean workspace outside of my computer.

It seems that the package definition is valid on packagist too and in my cache folder... I'm a bit lost here, if you have some clue I'll be glad to hear them 😄.

**Comment by shulard** [comment]
Actually, the second call of `composer outdated` give me the exact same result. So no dependencies were updated.

I also checked in the `composer.lock` generated file and it seems that `source` and `dist` entries were removed for `roave/security-advisories` after running `composer update` :

```diff
++++ w/composer.lock
@@ -7328,17 +7328,6 @@
         {
             "name": "roave/security-advisories",
             "version": "dev-master",
-            "source": {
-                "type": "git",
-                "url": "https://github.com/Roave/SecurityAdvisories.git",
-                "reference": "f834fd02a512672f298ed7c59e44e46621b6423d"
-            },
-            "dist": {
-                "type": "zip",
-                "url": "https://api.github.com/repos/Roave/SecurityAdvisories/zipball/f834fd02a512672f298ed7c59e44e46621b6423d",
-                "reference": "f834fd02a512672f298ed7c59e44e46621b6423d",
-                "shasum": ""
-            },
             "conflict": {
                 "3f/pygmentize": "<1.2",
                 "adodb/adodb-php": "<5.20.12",
```

My trouble is more about the `roave/security-advisories` which is a direct dependency. The second one will be update by the corresponding package.

**Comment by alcohol** [comment]
That is to be expected since https://github.com/composer/composer/pull/7501

**Comment by shulard** [comment]
Hello,

I get a bit deeper after reading the comments in the #7501 issue.

So, this issue only come when you are using metapackage. Since the `source` / `dist` are not stored anymore the outdated algorithm doesn't works.

In the `ShowCommand`, at line 375 the comparison is made between `$package` and `$latestPackage`. Those two variable are `CompletePackage` instances.

* `$package` is loaded from the `vendor/composer/installed.json` file
* `$latestPackage` is loaded from the Packagist JSON definition for the package

If I call the `getFullPrettyVersion` method used for that comparison, the two variables gave me two different results event when the latest version is installed : 

* `$latestPackage`: `dev-master 0abc14e`
* `$package`: `dev-master`

`getFullPrettyVersion` combine the requested version (here `dev-master`) and the current source id (aka commit id).

Since the `source` and `dist` are not stored locally but are stored on Packagist (see: https://packagist.org/packages/roave/security-advisories.json) that comparison always return false and my local package is always marked as outdated.

If think the solution is to update the `getFullPrettyVersion` method to handle the `metapackage` case.

I've created a PR to fix that case : #7575

**Comment by sbuzonas** [comment]
If you don't use a source reference, then you'll get stale results. `dev-master` will match no matter how many revisions forward it is.

**Comment by stof** [comment]
@alcohol then it means https://github.com/composer/composer/pull/7501 should be reverted, as it might cause issues when running against a Satis repository (no source reference on any side, so things would match even though one is the *old* dev-master)

**Comment by alcohol** [comment]
Yeah I think you are right. @Seldaek any input?

**Comment by Seldaek** [comment]
I'd go for revert of #7501 as well, otherwise there is no way we can fix this properly. We need to have the reference information even though there is no installed files per se. I will go ahead and do that.
