### ISSUE TITLE
Installation won't work

### ISSUE THREAD

**Issue by jm1994** [composer/composer#7547]
Hey,
the installation won't work on my work station. I get the following error

> The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.

The german part says: Connection failed, because the other computer denied the connection. (or did not allow)
When I try the same manually via terminal, I get the same error.

**Comment by alcohol** [comment]
Try using a different LAN/WLAN connection. Looks like you are firewalled or behind a proxy.

**Comment by jm1994** [comment]
Yes, it was a firewall problem. Solved by out IT Service.
