### ISSUE TITLE
Removing composer.lock and vendor folder for resolving issues. Good or bad?

### ISSUE THREAD

**Issue by zomorod** [composer/composer#7554]
My `composer.json`:

```json
It is very long, I can added if it is necessary. 
```

Output of `composer diagnose`:

```
$ composer diagnose
Checking composer.json: WARNING
License "GPL-2.0+" is a deprecated SPDX license identifier, use "GPL-2.0-or-later" instead
require.drupal/calendar_datetime : exact version constraints (1.x-dev) should be avoided if the package follows semantic versioning
require.drupal/calendar : exact version constraints (1.x-dev) should be avoided if the package follows semantic versioning
require.drupal/cas_attributes : exact version constraints (1.x-dev) should be avoided if the package follows semantic versioning
require.drupal/menu_block : exact version constraints (1.x-dev) should be avoided if the package follows semantic versioning
require.drupal/menu_position : exact version constraints (1.x-dev) should be avoided if the package follows semantic versioning
require.drupal/token_conditions : exact version constraints (1.x-dev) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: ..... 
Dev Public Key Fingerprint: .....
OK
Checking composer version: OK
Composer version: 1.7.1
PHP version: 5.6.35
```

When I run this command:

```
$ composer require drupal/core:8.5.6 --no-update
./composer.json has been updated
$ composer update drupal/core --with-dependencies
```

I get the following output:

```
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for drupal/core 8.5.6 -> satisfiable by drupal/core[8.5.6].
    - Conclusion: remove symfony/dependency-injection v3.4.8
    - Conclusion: don't install symfony/dependency-injection v3.4.8
    - drupal/core 8.5.6 requires symfony/http-kernel ~3.4.14 -> satisfiable by symfony/http-kernel[3.4.x-dev, v3.4.14].
    - symfony/http-kernel 3.4.x-dev conflicts with symfony/dependency-injection[v3.4.8].
    - symfony/http-kernel v3.4.14 conflicts with symfony/dependency-injection[v3.4.8].
    - Installation request for symfony/dependency-injection (locked at v3.4.8, required as ~3.4.0) -> satisfiable by symfony/dependency-injection[v3.4.8].
```

I have ran the following to find out why I have the error.

```
$ composer why-not drupal/core:8.5.6
drupal/core  8.5.6                       requires          symfony/http-foundation (~3.4.14)
usp/usp.org  dev-acqUpd-719076-20180814  does not require  symfony/http-foundation (but v3.4.8 is installed)
drupal/core  8.5.6                       requires          symfony/http-kernel (~3.4.14)
usp/usp.org  dev-acqUpd-719076-20180814  does not require  symfony/http-kernel (but v3.4.8 is installed)
```

```
$ composer why symfony/dependency-injection
drupal/console-core  1.8.0  requires  symfony/dependency-injection (~2.8|~3.0)
drupal/core          8.5.3  requires  symfony/dependency-injection (~3.4.0)
```

I appreciate if you can help me to resolve the issue.
In the meantime, I have removed composer.lock and vendor folder and then run the following:

```$ composer update drupal/core --with-dependencies```

Problem solved!

I have some concerns here. What is the consequences of removing composer.lock and vendor folder?
Is this a right way to solve the problem?

I have several examples that I can pass the error by removing the composer.lock and vendor folder(I can add them here, if you like). What is good a practice?

Also, I am thinking about the best solution for many problems with composer because I am working with many composer sites and eventually in the future I would like to automate the process for may sites. 

Thank you for your help in advance,

**Comment by stof** [comment]
please provide a reproducing case.
As removing the composer.lock solves the issue, we will need both the composer.json and the composer.lock for that (the ones before running your commands of course, not the final ones)

**Comment by stof** [comment]
also, please provide the full output of the failing command, in verbose mode.

**Comment by alcohol** [comment]
It looks to me like you need to spend some more time on your dependency management.

Having several Symfony components installed in different versions (especially in the 3.x range) is cause for concern.

You should probably remove your entire "require" set and start from scratch, only adding the root dependencies you explicitly need. Let your root dependencies determine the remaining transitive dependencies. Also pay more attention to the diagnose output; using dev packages really should be avoided as much as possible.

**Comment by asd-collab** [comment]
> Is this a right way to solve the problem?

it depends. if it works for your  development setup when you are in a hurry, its ok. But as above comment mentions there could be underlying problems, that you will need to solve.

you could also see if just removing the composer.lock works. 

probably it could be caused by using composer to install all dependencies in one project without planing ahead.

---

asd-collab
