### ISSUE TITLE
Error not caught properly

### ISSUE THREAD

**Issue by teo1978** [composer/composer#7556]
I **know** I've done something wrong, but I expect a sensible error message telling me what's wrong, so hear me out.

On my debian server, **as root**, I installed composer globally as indicated here:
https://getcomposer.org/doc/00-intro.md#globally

`composer` was installed correctly and worked as expected, but then when I tried it out requiring some package (which got installed succesfully), I got this message:
```
Do not run Composer as root/super user! See https://getcomposer.org/root for details
```

So, since I am a good boy, I `su`-ed to the user `www-data`, and then I tried:
```
composer global require laravel/installer
```
(which is the same that had worked perfectly when run as root)

**Expected:**
a sensible error message _from composer_ telling _me_ whatever _I_ am doing wrong

**Observed**
An error message _from the OS_ telling _composer_ what _composer_ is doing wrong.
Namely, this was the error message:
```
                                                
  [ErrorException]                              
  chdir(): No such file or directory (errno 2)  
                                                

global <command-name> [<args>]...
```

I'm pretty sure there's something wrong in installing `composer` as root and then trying to use it as another user - that doesn't seem wrong per se, but I'm probably missing some necessary step. Anyway, the error message I'm getting makes no sense whatsoever from the perspective of the user and gives me no clue of what I am supposed to fix.

**Comment by teo1978** [comment]
It seems that the problem was that the directory `.config/composer` in user `www-data`'s home didn't exist.

Which confirm that I had done something wrong, but also confirms that there's a bug here.
Composer should give an error message saying the directory does not exist (and most importantly **_what_** directory doesn't exist), rather than blindly trying to `chdir()` into it.

Also, showing the **command usage at the end** like that makes no sense:
1. when you show the expected usage of a command you should prepend it with something like "Usage:" (otherwise it's just a string that I don't know why is there, I have no clue that you are telling me how I am supposed to use the command)
2. usually you do that when there's something wrong with the way the command is being used, not every time any kind of error happens.

**Comment by Seldaek** [comment]
Please try again after a `composer self-update --snapshot` to see if that helped. At least it should improve the reporting a little. The usage thing you mentioned I agree it's not always relevant but it's done by symfony/console and not really something we control AFAIK.
