### ISSUE TITLE
Failed opening required '/app/vendor/composer/../opis/closure/functions.php'

### ISSUE THREAD

**Issue by HGWells07** [composer/composer#7558]
My `composer.json`:

```json
{
    "require": {
        "botman/botman": "^2.3",
        "botman/driver-facebook": "^1.8",
        "doctrine/cache": "^1.7"
    }
}
```

Output of `composer diagnose`:

```
OK
Checking composer version: OK
Composer version: 1.7.2
PHP version: 7.2.8
PHP binary path: C:\xampp\php\php.exe
```

I'm coding a webapp that its deployed to heroku, recently I updated all my Composer dependencies and composer itself. Since I update I've been getting the next output from heroku logs. Notice that this error only happens when deploying, when this has happened to me it has been becouse of some route badly specified, but I have not changed anything from the composer configuration.

I get the following output:

```
PHP Fatal error:  require(): Failed opening required '/app/vendor/composer/../opis/closure/functions.php' (include_path='.:/app/.heroku/php/lib/php') in /app/vendor/composer/autoload_real.php on line 66
```

**Comment by alcohol** [comment]
Looks to me like you did not share your complete `composer.json` with us. You also did not share a verbose and complete command input and output.
