### ISSUE TITLE
[tool/feature] update to latest available version

### ISSUE THREAD

**Issue by strarsis** [composer/composer#7560]
Is it possible to let composer bump all versions in `composer.json` to their latest versions?
After bumping to latest version, tests are run to check if the packages are still compatible.
Having a feature/tool for automatically bumping all versions in `composer.json` (not in the lockfile) would be helpful.

**Comment by alcohol** [comment]
I have personally been looking into this lately a bit myself, but haven't really invested the time yet to actually submit a PR.

**Comment by strarsis** [comment]
@alcohol: This feature would be very helpful!

**Comment by strarsis** [comment]
@alcohol: Is this still planned to be implemented in near future?
It is very useful to bulk-update WordPress plugins managed by composer for example.

**Comment by alcohol** [comment]
No explicit plans, on my personal to-do, but really low on time to be honest. :-(

**Comment by Seldaek** [comment]
Duplicate of https://github.com/composer/composer/issues/7273
