### ISSUE TITLE
Calling composer scripts recursively with params show error

### ISSUE THREAD

**Issue by Faryshta** [composer/composer#7562]
My `composer.json`:

```json
"scripts": {
        "run-tests": "@php vendor/bin/codecept run --steps",
        "run-coverage": "@run-tests -- --coverage --coverage-xml"
    }
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.7.2
PHP version: 7.1.17
PHP binary path: /usr/bin/php7.1
```

When I run this command:

```
...replace me...
```

I get the following output:

```
You made a reference to a non-existent script @run-tests -- --coverage --coverage-xml
```

And I expected this to happen:

Run the tests and generate coverage report.

This is because it takes the entire 'run-tests -- --coverage --coverage-xml' as the name of the script and not just 'run-tests'.

Currently I can fix it by changing the composer.json to

```json
"scripts": {
        "run-tests": "@php vendor/bin/codecept run --steps",
        "run-coverage": "@composer run-tests -- --coverage --coverage-xml"
    }
```

**Comment by alcohol** [comment]
I am not sure if we want to hack in more stuff to support this. The `scripts` section has already been patched a lot to support all these various odd use-cases. What is the harm in just defining the full command to run in both scripts? Sure, it duplicates a few words, but it is not like you are adding/removing/updating your scripts section every single day. So honestly, no worth investing any time on in my humble opinion.

**Comment by Faryshta** [comment]
>What is the harm in just defining the full command to run in both scripts? 

Code duplication, when you want to change one and the other change too without changing it twice.

Can you guide me on where to patch it to make a PR? As in I dont know any doc to where beging searching on the actual code.

**Comment by alcohol** [comment]
> Sure, it duplicates a few words, but it is not like you are adding/removing/updating your scripts section every single day.

Anyway, I think it should be somewhere in

https://github.com/composer/composer/blob/158e1c95da02cc0b932de74f9a09a1c7b6cf654f/src/Composer/EventDispatcher/EventDispatcher.php#L169-L254

**Comment by Faryshta** [comment]
I think the problem is at line 177

    $scriptName = substr($callable, 1); 

A line like `@update --prefer-dist` would  seek an script names `update --prefer-dist`. So I think it should be something like

    $script = explode(' ', substr($callable, 1));
    $scriptName = $script[0];
    unset($script[0]); // now $script contains all the params

What I dont know is how to pass the params to the new execution.

**Comment by PandelisZ** [comment]
I've spent some time in the debugger looking at how this works. I like this functionality I use it allot with NPM which is implemented here: https://github.com/npm/cli/blob/59e5056a2129cb2951f4ff3b657ada20657f01a7/lib/run-script.js#L177

I'm going to take a stab at implementing this now that I understand how the event dispatcher is behaving.

**Comment by GusAntoniassi** [comment]
If you're coming here because you're facing this error message, try updating your composer version. 

I was using `1.6.0` and was having this issue, then I upgraded to `1.8.0` and now it works fine.
