### ISSUE TITLE
[ Feature-Request ] Composer Network-Timeout

### ISSUE THREAD

**Issue by mike-reinders** [composer/composer#7568]
Hey,

sometimes, when I am running composer in my virtual machines, I forget to give it external network access before running composer.

If there is no external network access, composer runs for years and isnt timeouting when no connection can be established.
It would be nice if you add a timeout option for composer. Maybe by default it could be 10 seconds.

Have a nice day!

**Comment by alcohol** [comment]
AFAIK, Composer will respect most default timeout settings. Are you sure your php.ini configuration is configured correctly?

**Comment by MikesCodeProjects** [comment]
`php -d default_socket_timeout=10 /usr/local/bin/composer update`
Is that what you meant to tell me? O.o

**Comment by staabm** [comment]
There ars some bugs in php that connections dont timeout in certain conditions. 

You nerd to provide more information, how to reproduce your problem and maybe also search the php bugtrackee depending on your php version

**Comment by MikesCodeProjects** [comment]
I am running composer in a docker container with `php:7.2.6-fpm-stretch` as the base image.

**My dependencies are installed via:**

```
RUN apt-get update \
        && apt-get install --no-install-recommends --no-install-suggests --yes git libzip-dev zip unzip libpng-dev libxml2-dev

RUN docker-php-ext-install \
        pdo \
        pdo_mysql \
	    mbstring \
	    gd \
	    bcmath \
        xml \
	&& docker-php-ext-enable \
	    pdo \
	    pdo_mysql \
	    mbstring \
	    gd \
	    bcmath \
	    xml \
	&& pecl install \
	    apcu-5.1.12 \
	    zip-1.15.3 \
	&& docker-php-ext-enable \
	    apcu \
	    zip

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
	&& php composer-setup.php \
	&& php -r "unlink('composer-setup.php');" \
	&& mv composer.phar /usr/local/bin/composer
```

My php.ini's:
```
root@9d632f8f28c0:/www# php --ini
Configuration File (php.ini) Path: /usr/local/etc/php
Loaded Configuration File:         (none)
Scan for additional .ini files in: /usr/local/etc/php/conf.d
Additional .ini files parsed:      /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini,
/usr/local/etc/php/conf.d/docker-php-ext-bcmath.ini,
/usr/local/etc/php/conf.d/docker-php-ext-gd.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini,
/usr/local/etc/php/conf.d/docker-php-ext-sodium.ini,
/usr/local/etc/php/conf.d/docker-php-ext-zip.ini
```

My PHP-INFO:
https://gist.github.com/MikesCodeProjects/d85a10e95a10da232816422a0fc8fc6b

Composer Version:
```
root@9d632f8f28c0:/www/services# composer --version
Composer version 1.7.2 2018-08-16 16:57:12
```

Thanks for your quick replies!

**Comment by staabm** [comment]
Maybe you should run a ping before or something similar?

**Comment by MikesCodeProjects** [comment]
A docker container has no ping command by default :P
But I could install it :D
Is there no way to implement such a timeout feature? *w*

**Comment by alcohol** [comment]
Yes, but again, most timeouts should be handled by PHP already. If it does not, you must have run into a very odd scenario / bug. There is very little we can do about this.

**Comment by staabm** [comment]
Maybe you could strace which command does not timeout?

**Comment by MikeR-GH** [comment]
After cloning the specific git repository from gitlab requires a `composer install` after starting the docker machine.

And my php-fpm-service is only available for other containers within the virtual network.
That means I always have to connect the php-fpm-container with the external network. And when I forget about that, `composer install` will hang for years :(

**Comment by staabm** [comment]
strace is a cli tool which shows syscalls of a running process.
Maybe we can see that was which connection doesnt work?
Or maybe you already know which IO operation does not return/timeout?

**Comment by MikeR-GH** [comment]
Are you sure, you want to see the strace?? O.O
It's over 20k Lines long lol

https://gist.github.com/MikeR-GH/d143a39cb94aa981e2b810d253fedc6f

**Comment by ktomk** [comment]
@mike-reinders The gists are gone.

For a test I would run composer install with non-interactive and -vvv to see where it hangs.

To obtain the command-line PHP configuration, `php -i | grep socket` should reveal the default PHP configuration composer inherits from:

~~~
$ php -i | grep 'socket'         
/etc/php/7.2/cli/conf.d/20-sockets.ini,
sockets
default_socket_timeout => 60 => 60
~~~

I can not say if there is an offline mode available for composer.

However having the vendor folder in the docker build context already would spare to install composer in the container only to create the vendor folder.
