### ISSUE TITLE
composer cannot install dependency under children dependency if parent dependency contains the same dependency

### ISSUE THREAD

**Issue by claytonxia** [composer/composer#7572]
let's assump that A depend B and B depend C , if A also depend C, then C will not be installed under B vendor directory if you execute composer update B in the A directory. currently i can only require autoload.php from A in B as well as autoload.php from B to make C available in B. is there a better solution except execute composer install in B ? thanks

**Comment by stof** [comment]
that's totally expected. Composer creates a single vendor directory, not multiple ones.

Classes are global in PHP anyway. There is nothing like ` make C available in B`. If a class is autoloadable, it is available anywhere.
