### ISSUE TITLE
packages.json from bitbucket repo file

### ISSUE THREAD

**Issue by lightcoresystems** [composer/composer#7576]
Hello,

I'm not sure if its possible to do what i'm doing. I want to create my own private composer repository.

I have created a packages.json file, which works perfectly on any public domain (example: https://test.com/packages.json), so my syntax is OK. I do not want to pay for any domain just to put there one file, or buy server to get this file via ssh, so I thought I can use bitbucket. 

I created bitbucket repo (with a lot of tools and scripts useful in my project), where is packages.json file. Path to this file is: https://bitbucket.org/company/tools/raw/master/packages.json
This returns raw file.

And this solution is not working :( I made my bitbucket repo public and it still do not work properly :( 

composer -vvv update returns smth like this:

`Following redirect (2) https://bitbucket.org/account/signin/?next=/company/tools/raw/master/packages.json
Downloading https://bitbucket.org/account/signin/?next=/company/tools/raw/master/packages.json
Retrying download: Maximum (20) redirects followed
`

Its a redirect loop.

Can anyone help me ? :) Or tell my why it is not possible to do this ?

Regards

**Comment by alcohol** [comment]
If I go to that URL I also get a 404. So this is not an issue on our end. The file is simply not there :-)

**Comment by lightcoresystems** [comment]
That was an example URL. For an example I created public repository with packages.json (correct syntax I think, beacouse its working when its on any domain).

**Comment by alcohol** [comment]
Why would you give us an example URL..? :man_facepalming: 

Anyway, that real URL works for me:

```
rob@galaga /tmp/test $ cat composer.json
{
    "repositories": [
        { "type": "composer", "url": "https://bitbucket.org/lightcoresystems/faq/raw/master/packages.json" },
        { "packagist.org": false }
    ]
}

rob@galaga /tmp/test $ composer show --all
platform:
  composer-plugin-api 1.1.0    The Composer Plugin API
  ext-ctype           7.2.8    The ctype PHP extension
  ext-curl            7.2.8    The curl PHP extension
  ext-date            7.2.8    The date PHP extension
  ext-dom             20031129 The dom PHP extension
  ext-fileinfo        1.0.5    The fileinfo PHP extension
  ext-filter          7.2.8    The filter PHP extension
  ext-ftp             7.2.8    The ftp PHP extension
  ext-hash            1.0      The hash PHP extension
  ext-iconv           7.2.8    The iconv PHP extension
  ext-json            1.6.0    The json PHP extension
  ext-libxml          7.2.8    The libxml PHP extension
  ext-mbstring        7.2.8    The mbstring PHP extension
  ext-mysqlnd         0        The mysqlnd PHP extension (actual version: mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $)
  ext-openssl         7.2.8    The openssl PHP extension
  ext-pcre            7.2.8    The pcre PHP extension
  ext-PDO             7.2.8    The PDO PHP extension
  ext-pdo_sqlite      7.2.8    The pdo_sqlite PHP extension
  ext-Phar            2.0.2    The Phar PHP extension
  ext-posix           7.2.8    The posix PHP extension
  ext-readline        7.2.8    The readline PHP extension
  ext-Reflection      7.2.8    The Reflection PHP extension
  ext-session         7.2.8    The session PHP extension
  ext-SimpleXML       7.2.8    The SimpleXML PHP extension
  ext-sodium          7.2.8    The sodium PHP extension
  ext-SPL             7.2.8    The SPL PHP extension
  ext-sqlite3         7.2.8    The sqlite3 PHP extension
  ext-tokenizer       7.2.8    The tokenizer PHP extension
  ext-xml             7.2.8    The xml PHP extension
  ext-xmlreader       7.2.8    The xmlreader PHP extension
  ext-xmlwriter       7.2.8    The xmlwriter PHP extension
  ext-zip             1.15.3   The zip PHP extension
  ext-zlib            7.2.8    The zlib PHP extension
  lib-curl            7.61.0   The curl PHP library
  lib-libxml          2.9.7    The libxml PHP library
  lib-openssl         2.6.5    LibreSSL 2.6.5
  lib-pcre            8.41     The pcre PHP library
  php                 7.2.8    The PHP interpreter
  php-64bit           7.2.8    The PHP interpreter, 64bit
  php-ipv6            7.2.8    The PHP interpreter, with IPv6 support

available:
  lightcore/faq

```

**Comment by lightcoresystems** [comment]
hmm... That works when "lightcore/faq" is public. When its private it dont work for me. I have correct auth.json configured for bitbucket.

Maybe I dont understand any assumptions of composer repositories, but why cant I set local path to a packages.json file?

Regards

**Comment by sbuzonas** [comment]
> Or maybe there is any possibility to set local path to packages.json instead of https/ftp/ssh ??

You should be able to use a file uri. `file:///path/to/packages.json`

**Comment by lightcoresystems** [comment]
@sbuzonas this works great, but I can use only abolute paths via "file://". I want to use relative paths :(

**Comment by sbuzonas** [comment]
Did you try `file://./relative/path/to/packages.json`? I'm not sure where a relative path would originate from in the stream

**Comment by lightcoresystems** [comment]
@sbuzonas I tried that. It do not worked, because it dont have a originate.. It should be possible to use classic paths like "relative/path/to/package.json" or "/absolute/path/to/package.json".. But it Will add automatically "http://" at the begining..

IS there Any known solution? Or only solution is fork and do it by myself? :)

**Comment by sbuzonas** [comment]
What do you mean by `it dont have an originate`? If you add the `file://` scheme it will not assume `http://` scheme.

**Comment by sbuzonas** [comment]
Oh, to clarify my statement:

> I'm not sure where a relative path would originate from in the stream

Using `file://` can be any path on the filesystem. Beginning a path with `/` makes it absolute, omitting it should be relative, and beginning with `.` is explicitly stating current directory where `..` would be parent directory. The question is, where the context of the current working directory comes from. I would imagine it would be the actual cwd, but I haven't had a chance to test it.

**Comment by lightcoresystems** [comment]
It dont work, I tried.. file:// is not relative to the position of the composer.json, because its a protocol working on absolute paths. You can paste file:///absolute/path/to/file to the browser and you can see that it works.

https://en.wikipedia.org/wiki/File_URI_scheme

**Comment by sbuzonas** [comment]
Wikipedia is a terrible source for technical specification (non-authoritative).  [RFC-3986](https://tools.ietf.org/html/rfc3986#section-1.2.3) discusses `scheme:.` and `scheme:..` as the relative counterparts to the absolute `scheme://`

That being said, I did some digging into different permutations of the stream context with `file:` uris. It seems that PHP streams do not handle `file:.` or `file:..` because of Windows compatibility for drive letters. The way to support relative paths is to omit the scheme and use the default stream handler. The problem is that `ComposerRepository` assumes that it should be `http://` uri if not provided. [ref](https://github.com/composer/composer/blob/master/src/Composer/Repository/ComposerRepository.php#L70)

IMO, relative paths are messy. If you move your directory it breaks. If a collaborator has a different preferred file hierarchy it breaks. Etc.

If you need to write support for this, you shouldn't need to maintain a fork. It should be pretty straightforward to create a plugin that subscribes to the `PreFileDownloadEvent` to replace the `RemoteFilesystem` when fetching your root repo data. Or you can have a plugin register a stream wrapper. Both of these will be brittle with the no plugins option, but much easier to keep your composer up to date.

**Comment by lightcoresystems** [comment]
Ok, great ! Thanks for full answer. I will try creating plugin ! I think I can close this issue
