### ISSUE TITLE
[Feature Request] Allow new versions to specify deprecated requirements that should not be removed when updating

### ISSUE THREAD

**Issue by pdohogne** [composer/composer#7582]
We have a new version of our package being released that no longer has a requirement on a specific dependency, but that dependency does not break the new version and provides some additional functionality that existing users may be using so we do not want it removed when our users run `composer update`.  Currently our solution is to include documentation of how to add that dependency as a requirement outside of our package so it won't be removed, but we don't want it to break if users run an update for other reasons than our package and thus might be unaware of the change.  We'd also very much prefer to not need to add additional steps to the update process that are outside of the normal workflow just to make sure we don't break other things.

**Suggestion:**
Add a "deprecated" section to the `composer.json` schema to specify former requirements that will not be removed when executing `composer update` if they already exist.

**Example:**
Previous version's `composer.json`:
```JSON
{
     "name": "company/package",
     "version": "2.1.3",
     "require": {
          "merchant/main-module": "^2.3",
          "merchant/format-utils": "^1.2"
     }
}
```

New version's `composer.json`:
```JSON
{
     "name": "company/package",
     "version": "2.2.0",
     "require": {
          "merchant/main-module": "^2.3"
     },
     "deprecated": {
          "merchant/format-utils": {
               "version": "^1.2",
               "since": "2.2.0"
          }
     }
}
```

**Comment by alcohol** [comment]
Sounds like you should just release a new major version of your package. We are not going to adjust Composer because you came up with a new and unique way to develop and release software.
