### ISSUE TITLE
Custom Arguments for Events

### ISSUE THREAD

**Issue by ucola** [composer/composer#7585]
Hi all

We use the event "pre-package-install" with a own Class to do some stuff before install a package.
No we want to pass there some custom arguments, to handle more stuff.

i.e. composer update drupal/core --no-backup

We want no to read out the argument --no-backup in our event. How can we register or create some custom arguments for an event?

**Comment by Nek-** [comment]
I think this demand is really ok. You should consider to open a new PR about. 👍

**Comment by ucola** [comment]
thank you for your answer, can you tel me where we can do a product request? Or is this issue enought?

**Comment by Nek-** [comment]
This issue is enough but you should consider this project is maintained by people that give free time for that. It's mainly based on contributions. Best way to see it inside the code base is to do it by yourself.

That's why I suggested to you to make a new PR with the feature.

**Comment by alcohol** [comment]
https://getcomposer.org/doc/articles/scripts.md#running-scripts-manually

I am not sure if the same functionality can be using during `composer install`; try it and see I guess :-)

**Comment by ucola** [comment]
We test it... -- dosen't works

**Comment by alcohol** [comment]
I'm not sure how we could achieve this. Maybe @Seldaek has some thoughts on this.

**Comment by Seldaek** [comment]
You may be able to add an argument to the command by listening to the pre_command_run event, not sure though you have to try it.

**Comment by ucola** [comment]
ok, so we need to create a own plugin for this? did you have an example for us how we can use pre_command_run event? thank you for help!

**Comment by Seldaek** [comment]
Yes, have a look at https://getcomposer.org/doc/articles/plugins.md - no guarantee this will work though as I said, it's definitely pushing the boundaries of plugins.
