### ISSUE TITLE
Composer giving following error

### ISSUE THREAD

**Issue by vknrvk** [composer/composer#7587]
This is the first time I am installing composer. I am trying to install Yii and use for development.

I installed composer and tried to diagnose installation. Got following error.

e:\xampp\htdocs\leadership>composer diagnose
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.7.2
PHP version: 7.2.8
PHP binary path: E:\xampp\php\php.exe

Let me know what could cause this and how to rectify this. 

Thanks in advance,
Vijay Nair

**Comment by alcohol** [comment]
Please search the existing Github issues. There are several issues related to SSL/OpenSSL misconfiguration and bad installations.
