### ISSUE TITLE
Composer and Git Enterprise repos

### ISSUE THREAD

**Issue by jpegram2** [composer/composer#7591]
So this may be a redundant question but I haven't found a direct answer. First, I know I can add an individual repository to composer.json, what I want to do is add a specific instance of Git Enterprise and be able to access all the subsequent repositories.  I've tried: 
`{"type": "git", "url": "https://git.mydomain.com"}`
and I have api key which works fine. Like I said if I use:
`{"type": "git", "url": "https://git.mydomain.com/org/console-stuff.git"}`
it works fine but if I have multiple dependencies then I have to add each ones individual repo, which seems a bit odd. 

Is this something can be done now? Currently I'm getting a redirection error from 2FA. Maybe I don't understand how Git is supposed to work but it sure seems like this should work. 

Any thoughts?

**Comment by alcohol** [comment]
> I haven't found a direct answer

> Maybe I don't understand how Git is supposed to work but it sure seems like this should work.

This is not how it works, should work, or could ever work.

You have to add each repository individually.

**Comment by jpegram2** [comment]
Thanks @alcohol
