### ISSUE TITLE
... is not a junction and thus cannot be removed as one

### ISSUE THREAD

**Issue by DmitryKuh** [composer/composer#7592]
I'm trying to install the SilverStripe CMS.

When I'm using the composer commands (any) I have the following error:
----------------------------------------------
 C:\SilverStripe>composer require silverstripe/mssql "*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 49 installs, 0 updates, 0 removals
  - Installing silverstripe/framework (4.2.1): Loading from cache
    Skipped installation of bin sake for package silverstripe/framework: name conflicts with an existing file
Exposing web directories for silverstripe-vendormodule silverstripe/framework with method auto:
  - client/images
  - client/styles
  - src/Dev/Install/client

  [Symfony\Component\Filesystem\Exception\IOException]
  C:\SilverStripe\public\resources\vendor\silverstripe\framework\client\images is not a junction and thus cannot be removed as one

-------------------------------------------
This is happening for any command.

Do you have any solution?

**Comment by curry684** [comment]
The output you're showing indicates that some plugin is installed that is doing custom actions, and even running into problems while doing it. Also it seems to be modifying its own installation in the vendor folder, which is really bad practice (and leading to this problem). I'd first take this up with the author of the plugin doing this.

**Comment by DmitryKuh** [comment]
Maybe it is a bad example. I have another one:

Using version ^5.2 for silverstripe/userforms
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals

Installing silverstripe/segment-field (2.2.1): Loading from cache
Exposing web directories for silverstripe-vendormodule silverstripe/segment-field with method auto:
client/dist
[Symfony\Component\Filesystem\Exception\IOException]
C:\ss\public\resources\vendor\silverstripe\segment-field\client\dist **is not a junction and thus cannot be removed as one**
-------------------------------------------------------
It is sounds like trying to delete a symbolic link "dist" created during the installation process using rmdir command.

I had the same error when tried to delete it manually without -Force parameter.

**Comment by alcohol** [comment]
Please use `-vvv` so we can see where the Exception originates from.

**Comment by curry684** [comment]
Yep, it works on `rmdir` internally since we (more specifically: I) discovered during implementation that wrapper CLI commands was far more reliable than attempting to predict the on Windows frequently dodgy FS wrappers for exotic functionality like symlinks and junctions.

Anyway, we indeed need more specifics on what is triggering the issue, so we'll need something we can copy/paste from an empty directory to reproduce it, or a full walkthrough including `-vvv` flags.
