### ISSUE TITLE
[Composer\Downloader\TransportException]                                                                                                              The "http://repo.packagist.org/p/provider-2018-07%245714a0dc840abb2a5da64345abc53df9354b01309b55a8fd83f112e2929fa949.json" file could not be down  loaded (HTTP/1.1 404 Not Found)  

### ISSUE THREAD

**Issue by JosephRidge** [composer/composer#7599]
[Composer\Downloader\TransportException]                                                                                                           
  The "http://repo.packagist.org/p/provider-2018-07%245714a0dc840abb2a5da64345abc53df9354b01309b55a8fd83f112e2929fa949.json" file could not be down  
  loaded (HTTP/1.1 404 Not Found)  

tried updating my composerinorder to install laravel but this is rhe error that it brought kindly assist

**Comment by alcohol** [comment]
Usually a temporary error.
