### ISSUE TITLE
Composer not working... 

### ISSUE THREAD

**Issue by Thorene** [composer/composer#7608]
Hi,

I'm trying to install the api from Woo Commerce.
They tell everywhere that I have to do it with composer.
So  I followed the instructions and everytime I run the following script : 
```
<?php
	require __DIR__ . '\vendor\autoload.php';
	use Automattic\WooCommerce\Client;
	 
	use Automattic\WooCommerce\HttpClient\HttpClientException;
	if ( is_readable( $autoloader ) ) {
		require_once $autoloader;
	}


	$woocommerce = new Client(
		'http://studiofrancine.be/wordpress-4.9.5-fr_BE/wordpress/',
		'A',
		'B',
		[
			'wp_api'  => true,
			'version' => 'wc/v2',
		]
	);
?>
```

( ! ) Fatal error: require(): Failed opening required 'C:\wamp\www\Wcommercealac\vendor\autoload.php' (include_path='.;C:\php\pear') in C:\wamp\www\Wcommercealac\index.php on line 2
Warning: require(C:\wamp\www\Wcommercealac\vendor\autoload.php): failed to open stream: No such file or directory in C:\wamp\www\Wcommercealac\index.php on line 

I get thoses errors. I tried to change the include path in the php.ini and it really doesn't wanna change. It doesn't change anything... I'm in Wamp, using PHP 7.2.4. To change the ini file, I go to C:\wamp\bin\apache\apache2.4.33\bin 

I can make the code work with includes but then the function use bugs... I'm not used to thoses functions and composer. Can someone help me? I really have no clue how to fix that... 
I thought composer was simple, but it looks it more difficult...

**Comment by alcohol** [comment]
Did you actually run `composer install`?
Is there a new directory called `vendor` inside your project root?

**Comment by Thorene** [comment]
Yes there is. I followed instructions :

**Comment by curry684** [comment]
> I get thoses errors. I tried to change the include path in the php.ini and it really doesn't wanna change. It doesn't change anything... I'm in Wamp, using PHP 7.2.4. To change the ini file, I go to C:\wamp\bin\apache\apache2.4.33\bin

By all means - never touch the ini file again until you really know what you're doing. By modifying the include paths in there you may have broken your Wamp installation beyond repair by now.

> ( ! ) Notice: Undefined variable: autoloader in C:\wamp\www\Wcommercealac\index.php on line 6

This error is logical given the code snippet you provided, it's just broken like that itself. This has nothing to do with Composer, that code can never work properly (it's trying to see if a variable never used elsewhere is a readable file in the filesystem).

**Comment by Thorene** [comment]
Hello guys, thanks all for your answers.

I didn't know this Composer and finally fixed my problem by installing in the directory concerned. I thought that when you use Composer, all libraries where put at same place and I couldn't find how to tell my script to reach this place. 

Thanks all for your reactivity and your support.
