### ISSUE TITLE
Add support to use local repository if exists, else use git version

### ISSUE THREAD

**Issue by jordyvandomselaar** [composer/composer#7609]
My `composer.json`:

At work we have this example `composer.json`:

```json
{
  "require": {
    "deinternetjongens/lighthouse-utils": "dev-develop"
  },
  "repositories": [
    {
      "type": "path",
      "url": "../Lighthouse-Utils"
    }
  ]
```

Now, if I have the repository locally it shows

> Installing deinternetjongens/lighthouse-utils (dev-develop): Symlinking from ../Lighthouse-Utils

But, if it cannot find the package locally I get

 >  /Users/jordyvandomselaar/workspace/hockeyweerelt-middleware/vendor/deinternetjongens/lighthouse-utils does not exist and could not be created.  

It would be great if it were possible to use the local version if it exists, else clone it from git.

**Comment by jordyvandomselaar** [comment]
Our usecase is as follows:

We have a project running on a test server. It uses a package that we're still actively developing alongside the project.

Right now we just edit the files in the vendor folder and commit/push from there. But it'd be nicer if the two projects could be cloned alongside eachother for development, else use the latest version that's on our github.

**Comment by alcohol** [comment]
Yeah and I already explained how you can easily achieve that without implementing additional features in Composer.

> You should probably just add your local repository definition on your development machine to your global composer config, not your project composer.json

**Comment by jordyvandomselaar** [comment]
For now it'll do. Since we're working in teams it's suboptimal, however. Would be easier if composer.json could handle this so we'd configure it once, and run it everywhere.

**Comment by alcohol** [comment]
I fail to see the relevance of "teams" to this issue. You're asking for a specific solution to help you deal with your work flow, but none of us here are familiar with or understand your work flow.

Considering millions of users have no problem using Composer without the functionality you requested, you can understand our reluctance to implement additional features for a specific individual.

**Comment by piotrbrzezina** [comment]
Hi I got the similar use case like you. My way to achieve that is, simply add `path repostiory` and also add  your `git repository` eg
```{
  "require": {
    "deinternetjongens/lighthouse-utils": "dev-develop"
  },
  "repositories": [
    {
      "type": "path",
      "url": "../Lighthouse-Utils"
    },
    {
      "type": "vcs",
      "url": "https://gitlab.com/Lighthouse-Utils.git"
    }
  ]
```

You should be aware that order has matter in repository array. So first you should add the path repository and after that add git repository

**Comment by sbuzonas** [comment]
> Right now we just edit the files in the vendor folder and commit/push from there. But it'd be nicer if the two projects could be cloned alongside eachother for development, else use the latest version that's on our github.

Path repositories in your global config with symlinks enabled works incredibly well for this scenario.

**Comment by jordyvandomselaar** [comment]
> I fail to see the relevance of "teams" to this issue. You're asking for a specific solution to help you deal with your work flow, but none of us here are familiar with or understand your work flow.
> 
> Considering millions of users have no problem using Composer without the functionality you requested, you can understand our reluctance to implement additional features for a specific individual.

Excuse me for my late reply,

>  Considering millions of users have no problem using Composer without the functionality you requested, you can understand our reluctance to implement additional features for a specific individual.

Yes, I do. We'll have a look at how we can accomplish our goal in a different way. Thanks for the replies!

I'll close this issue for now.
