### ISSUE TITLE
Very slow download packages on latest composer version vs 1.6.4 (with Artifactory repository)

### ISSUE THREAD

**Issue by sadok-f** [composer/composer#7626]
Hello !

Not sure is it an Artifactory issue or Composer, but recently our build process start taking too much time because composer taking up to 30 min to install dependencies.
We're using docker images for composer and we have the issue with following versions : 1.7.2,  1.7.1 , 1.7.0
But in the older version 1.6.4 , it works fine , installing dependencies such as the composer.json below takes `1m 42.66s`

We are using Artifactory (5x) as private registry for docker, composer, npm,....

When increasing the verbosity, it shows that it stucks in downloading some packages (randomly) 
such as 
`Downloading http://artifactory.xxxx.xxx/artifactory/api/composer/php-remote/vcs-dists/zip/symfony/test-pack/958d23627214f5268d211c25031650d0dd6bdf60
(45%)`

if I copy paste the link in a browser, it got downloaded immidiatly.

Here My `composer.json`:

```json
{
  "name": "test",
  "description": "",
  "type": "project",
  "license": "proprietary",
  "require": {
    "php": "^7.2.6",
    "ext-iconv": "*",
    "sensio/framework-extra-bundle": "^5.2",
    "symfony/console": "^4.0",
    "symfony/dotenv": "^4.0",
    "symfony/flex": "^1.0",
    "symfony/framework-bundle": "^4.0",
    "symfony/lts": "^4@dev",
    "symfony/yaml": "^4.0",
    "symfony/monolog-bundle": "^3.3",
    "glopgar/monolog-timer-processor": "^0.1.1",
    "bramus/monolog-colored-line-formatter": "~2.0"
  },
  "minimum-stability": "dev",
  "prefer-stable": true,
  "require-dev": {
    "guzzlehttp/guzzle": "^6.3",
    "squizlabs/php_codesniffer": "^3.3",
    "symfony/browser-kit": "^4.0",
    "friendsofphp/php-cs-fixer": "^2.12",
    "symfony/test-pack": "^1.0"
  },
  "config": {
    "preferred-install": {
      "*": "dist"
    },
    "sort-packages": true,
    "secure-http": false
  },
  "replace": {
    "symfony/polyfill-iconv": "*",
    "symfony/polyfill-php71": "*",
    "symfony/polyfill-php70": "*",
    "symfony/polyfill-php56": "*"
  },
  "repositories": [
    {
      "type": "composer",
      "url": "http://artifactory.xxxx.xxx/artifactory/api/composer/php-remote"
    },
    {
      "type": "composer",
      "url": "http://artifactory.xxxx.xxx/artifactory/api/composer/php-local"
    },
    {
      "packagist": false
    }
  ],
  "conflict": {
    "symfony/symfony": "*"
  },
  "extra": {
    "symfony": {
      "id": "01CAMT3F0PZG98NNXYJNV18JN5",
      "allow-contrib": true
    }
  },
  "scripts": {
    "auto-scripts": {
      "cache:clear": "symfony-cmd",
      "assets:install %PUBLIC_DIR%": "symfony-cmd"
    }
  }
}

```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 1.7.2
PHP version: 7.2.9
PHP binary path: /usr/local/bin/ph
```

When I run this command:

```
time composer install --ignore-platform-reqs --dev -vvv
```

I get the following output:

```
Downloading http://artifactory.xxxx.xxx/artifactory/api/composer/php-remote/vcs-dists/zip/symfony/test-pack/958d23627214f5268d211c25031650d0dd6bdf60
 (45%)
```

And I expected this to happen:
Dependencies installed faster and autoload files generated.

We're having this issue on our staging system (AWS) and in devs local machine (windows, mac, vagrant vm).

Thank you in advance.

**Comment by adjenks** [comment]
I'm experiencing a similar problem, but without running artifactory. Each download takes extremely long when running install.

**Comment by simonberger** [comment]
This issue is pretty old. But I was not able to download a ~20MB binary package (artifactory as well) in a lot of tries.
It always failed on a timeout after downloading XX%.
After disabling use of curl (in HttpDownloader) it worked pretty fast.

**Comment by adjenks** [comment]
@simonberger How did you disable it exactly?

**Comment by simonberger** [comment]
I am sorry. Curl is in use just since alpha releases of version 2.
The cause in version 1 must have another reason.
