### ISSUE TITLE
Composer v1.7.2 says "the requested PHP extension XXXXX is missing from your system" not matter it does exist. 

### ISSUE THREAD

**Issue by devtdeng** [composer/composer#7628]
Composer v1.7.2 says many extensions are missing although they exist on the system. 

```
# php --version
PHP 5.6.37 (cli) (built: Jul 31 2018 17:13:40)

# composer --version
Composer version 1.7.2 2018-08-16 16:57:12

# php -m |  grep mbstring
mbstring

# php -a
Interactive mode enabled
php > var_dump(extension_loaded('mbstring'));
php shell code:1:
bool(true)

# composer show -p ext-mbstring
Do not run Composer as root/super user! See https://getcomposer.org/root for details

  [InvalidArgumentException]
  Package ext-mbstring not found
```

The problem only happens with composer v1.7.2 releases, once download composer to v1.7.1  or older releases, the problem can't be reproduced on the same test box.

**Comment by stof** [comment]
having an InvalidArgumentException here looks wrong though.

Please run the command in verbose mode to see the stacktrace of the exception.
