### ISSUE TITLE
Composer 1.7.2 fatal error "Can't inherit abstract function Composer\Repository\RepositoryInterface::removePackage()"

### ISSUE THREAD

**Issue by JulianaApolo** [composer/composer#7634]
Composer doesn't run. 

```
php -v
```
PHP 5.3.3 (cli) (built: Mar 22 2017 12:27:09) 

When I run this command:

```
php composer.phar install --ansi
```

I get the following output:

```
PHP Fatal error:  Can't inherit abstract function Composer\Repository\RepositoryInterface::removePackage() (previously declared abstract in Composer\Repository\WritableRepositoryInterface) in phar:///net/nas-unity-01/dev_desenvolvedores/29/integrador_clientes/composer.phar/src/Composer/Repository/WritableRepositoryInterface.php on line 23

```

**Comment by alcohol** [comment]
Sounds like you have a plugin that is not compatible with our interface. The interface was modified recently to include a method that is required but was missing from the interface.

**Comment by Seldaek** [comment]
Please try again after a `composer self-update`.

**Comment by Seldaek** [comment]
But also please consider updating your PHP version. 5.3.3 is very very outdated at this point and hasn't been maintained for bugs and security fixes for ages.

**Comment by JulianaApolo** [comment]
@Seldaek thank u. I saw the commit revert. Composer is working now.
I can't update my php version this moment. My internal framework is not compatible.
