### ISSUE TITLE
Issue with Installer

### ISSUE THREAD

**Issue by TH3DoCtOr11th** [composer/composer#7635]
Sorry, I could not make use of the preset questions. Actually, I have an issue with the Windows Installer, and I hoped I could find some answers here. Searching on Google brought me to nothing. My problem is, when I select the php.exe to check, it locks on "Checking command-line PHP". It does not move from there, and it does not show any sign of completion, error, anything. Has someone experienced the same issue? Thanks in advance

**Comment by johnstevenson** [comment]
Hi, could you please report this issue here: https://github.com/composer/windows-setup/issues/new and include the log file as described in the new issue preamble. Thanks.
