### ISSUE TITLE
Running 'update --lock' is doing things other than updating the lock file hash

### ISSUE THREAD

**Issue by LeeSaferite** [composer/composer#7638]
Output of `composer diagnose`:

```
Checking composer.json: WARNING
Defining autoload.psr-0 with an empty namespace prefix is a bad idea for performance
require.magento/magento-cloud-metapackage : exact version constraints (2.2.5) should be avoided if the package follows semantic versioning
require.colinmollenhour/cache-backend-file : exact version constraints (1.4.2 as 1.4) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.7.2
PHP version: 7.1.18
PHP binary path: /usr/local/bin/php
```

When I run this command:

```
composer update --lock
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating fastly/magento2 (1.2.60 => 1.2.63): As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Installing 'unzip' may remediate them.
Downloading (100%)
Writing lock file
Generating autoload files
```

And I expected this to happen:
I expected composer to _just_ update the lock file hash and *not* update/install packages.

The `fastly/magento2` package was updated in the master branch that I was merging back to a feature dev branch. After resolving a conflict in `composer.lock` manually I wanted to update the hash in the lock file to prevent composer from giving out warnings. I ran `composer update --lock` expecting it to do what it is described as doing and just update the hash. Running it on my host machine resulted in an error related to me having PHP 7.2 and some of the packages in the lock file not allowing 7.2 so I re-ran the command inside the docker container for the project. The second run resulted in this bug report and is described above. It seems to me that the `--lock` argument is *not* simply doing a hash update as claimed and it seems like either the documentation is wrong or the code is wrong. Of course, I could be doing something wrong as well.

**Comment by Seldaek** [comment]
The --lock means it will only update the lock hash but it also runs the equivalent of a `composer install` at the same time, so if your vendor directory is out of date with the lock file it will apply changes to bring it in line with the lock file. If you run `composer install` then `composer update --lock` nothing should happen in the lock step.

**Comment by LeeSaferite** [comment]
Why does the help message for this read like it _only_ changes the lock file hash?
Is there a way to update the lock file hash _without_ doing anything else?

**Comment by stof** [comment]
Well, it only changes that as part of the updating step. But it still performs the installing step if the vendor folder is not uptodate.
