### ISSUE TITLE
Feature Request: Accept GitHub Token from Environment Variable

### ISSUE THREAD

**Issue by alexmbird** [composer/composer#7640]
I'm trying to run `compose install` within a Docker build for a project that imports some things from private GitHub repositories and I've run into a snag.

Git needs access to retrieve these repos.  Hacks exist to export my private SSH key into the Docker build container but they're seen as a bad idea and in any case, will be brittle if used in an automated build.

A slightly better option would be to pass compose a GitHub API token.  I'd set it with `composer config -g github-oauth.github.com <oauthtoken>` and this would result in a `~/.composer/auth.json` file containing the string.

Trouble is, in Docker builds it is important not to write credentials to the filesystem.  Even if later deleted they persist in a layer and anybody with access to the image will be able to retrieve them.

Therefore, please can composer accept a GitHub token via an environment variable like `GITHUB_OAUTH_TOKEN`?  This can be set using Docker's `--build-arg` option.  It will be used during builds but won't be written to the filesystem, so cannot be leaked when publishing the resultant Docker image.

**Comment by alexmbird** [comment]
A closer look reveals things set with `--build-arg` actually persist in the image's metadata.  Therefore it's not suitable for setting secrets.   Closing this, but feel free to reopen if you think a GitHub token env var will be useful to others.

**Comment by alcohol** [comment]
You do realize this is already possible, right?

https://getcomposer.org/doc/03-cli.md#composer-auth

**Comment by alexmbird** [comment]
Nope, even with half an hour of googling I did not!   Thanks for the pointer.
