### ISSUE TITLE
[solver] Optimization idea: detect common dependency layouts

### ISSUE THREAD

**Issue by stof** [composer/composer#7643]
When finding multiple versions of a package which can fulfill a constraint, it is quite common for them to have the same set of dependencies (we can have multiple such groups among the versions found), as most packages don't update their requirements on each patch release.

Create a group of versions in the solver might allow limiting the number of rules in the solver. Instead of having require rules for each version to their dependencies, we would have requires rule from the group to the dependencies (so 1 set instead of N set), a require rule from the group to the packages in it, and incoming require rules would point to the group.

I haven't investigated the idea to be sure that it is a correct one (I think it is safe change in the algorithm, but @naderman knows it much better than me).

**Comment by stof** [comment]
Things which need to be checked:

- `conflict` rules (I think keeping them at the package level is fine, so no change for them)
- impact on `replace`/`provide` (the providing part of `replace`, as it is `provide`+`conflict`). Not sure this actually impacts the solver, as it would impact the list used as input

**Comment by naderman** [comment]
Already discussed something like this with Jordi. Our idea was to potentially optimize the composer repo protocol to send a list of versions instead of full metadata for each version, and to then represent the metadata similarly inside the composer object structure, where you'd not have a package object per version, but rather per name which can return the different version's data but doesn't take up as much space. Not entirely sure on the ideal implementation yet.

**Comment by stof** [comment]
well, requirements may still be different per version. We cannot force to move them at the package level

**Comment by Seldaek** [comment]
No this isn't moving at the package level, it'd just mean packagist ships the metadata in a format where equivalent versions's metadata are grouped together. I did some tests and it seems to save quite a bit of memory (~15% IIRC, but that will vary per package) as we reuse the same strings from the json in multiple version instances, but I didn't experiment about doing this deeper in the solver.

**Comment by stof** [comment]
Well, if the server returns requirement in an optimized format, this may make it simpler to build the optimized solving grouping (as the metadata would already be grouped). But I think these are actually independent optimizations (optimizing different things)

**Comment by Seldaek** [comment]
Yes exactly.. it's unrelated but the server one will most likely happen as it seems like an easy win and then we can see about optimizing the rest later.

**Comment by naderman** [comment]
I'm moving this back over to 2.0 milestone. I think for a first 2.0 version, we already have a fair few optimizations in place and this looks rather complex, but like something we can tackle independently after all the improvements we already made without any BC breaks.

**Comment by stof** [comment]
Closing this in favor of the PoolOptimizer implemented in #9261. Once the pool is optimized like that, the probably to find groups of versions of a package with exactly the same dependencies will be very low, as they will most likely have been filtered by the pool optimization in most cases already. Introducing more complexity in the solver is then not worth it.
