### ISSUE TITLE
PHP version used for scripts is not the same as version calling Composer

### ISSUE THREAD

**Issue by jrfnl** [composer/composer#7645]
#### My `composer.json`:
```json
{
	"require"    : {
		"php"                      : ">=5.4",
		"squizlabs/php_codesniffer": "^3.3.0"
	},
	"require-dev": {
		"phpunit/phpunit": "^4.0 || ^5.0 || ^6.0 || ^7.0"
	},
	"scripts"    : {
		"install-standards"    : "\"vendor/bin/phpcs\" --config-set installed_paths ../../..",
		"run-tests"            : "\"vendor/bin/phpunit\" --filter StndName ./vendor/squizlabs/php_codesniffer/tests/AllTests.php",
		"check-cs"             : "\"vendor/bin/phpcs\"",
		"post-install-cmd"     : "@install-standards",
		"post-update-cmd"      : "@install-standards"
	}
}
```

#### Output of `composer diagnose`:
```
Composer version 1.7.2 2018-08-16 16:57:12

Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: XXX
2
Dev Public Key Fingerprint: XXX

OK
Checking composer version: OK
Composer version: 1.7.2
PHP version: 7.1.20
PHP binary path: C:\wamp\bin\php\php7.1.20\php.exe
```

#### When I run this command:
```
composer run-tests
```

#### I get the following output:
```
> "vendor/bin/phpunit" --filter StndName ./vendor/squizlabs/php_codesniffer/tests/AllTests.php
This version of PHPUnit is supported on PHP 5.6, PHP 7.0, and PHP 7.1.
You are using PHP 5.4.20 (C:\wamp\bin\php\php5.4.20\php.exe).
Script "vendor/bin/phpunit" --filter StndName ./vendor/squizlabs/php_codesniffer/tests/AllTests.php handling the run-tests event returned with error code 1
```

#### And I expected this to happen:
The script to be run with PHP 7.1.20 - the version of PHP used to call Composer -, not with the system default PHP-CLI version (5.4.20 - don't ask, there is a reason for that).

---
The above is an abbreviated version of the issue to illustrate it.

What it comes down to is that I have a number of different PHP versions installed on my (Windows7) system and regularly need to switch between versions for different use-cases.
The system default for PHP-CLI is PHP 5.4.20.

To call composer, I use a `composer.bat` file which is in the windows `PATH` environment variable which looks like this:
```
@echo off
:set PHPBIN=C:\wamp\bin\php\php5.3.29\php.exe
:set PHPBIN=C:\wamp\bin\php\php5.4.45\php.exe
:set PHPBIN=C:\wamp\bin\php\php5.5.38\php.exe
:set PHPBIN=C:\wamp\bin\php\php5.6.37\php.exe
:set PHPBIN=C:\wamp\bin\php\php7.0.31\php.exe
set PHPBIN=C:\wamp\bin\php\php7.1.20\php.exe
:set PHPBIN=C:\wamp\bin\php\php7.2.8\php.exe

"%PHPBIN%" "C:\phars\composer.1.7.2.phar" -- --version
ECHO(
"%PHPBIN%" "C:\phars\composer.1.7.2.phar" %*
```

Depending on the use-case, I uncomment the PHP version I want to run Composer with.

The problem I'm running into is, that this works perfectly for resolving the dependencies, but goes wrong when any scripts are being called (like in the above example).

Composer appears to disregard the PHP version used to call it in that case and falls back to the system default PHP-CLI version.
Depending on what's being `require`d, this causes issues with running scripts as the dependencies will have taken the custom version of PHP into account - PHP 7.1.20 in the above example - when they were installed, but the scripts are in fact run by Composer via PHP 5.4.20

**Comment by jvasseur** [comment]
The php resolution is done by your OS so it's normal that it fallbacks to the system default. The solution is to prefix your scripts with `@php ` which will be replaced that the PHP binary allowing the command to be called with the right PHP version.

**Comment by jrfnl** [comment]
@jvasseur Thanks for your response. I've just been playing around with that, but I'm obviously doing something wrong as that just prints the script to the screen.

The script command I've been testing with which worked on Windows, but with the wrong PHP version:
```json
	"scripts"    : {
		"phpcs-i" : "\"vendor/bin/phpcs\" -i",
	}
```

I've tried both of the below, but neither work for me.

```json
	"scripts"    : {
		"phpcs-i" : "@php \"vendor/bin/phpcs\" -i",
	}
```
```json
	"scripts"    : {
		"phpcs-i" : "@php vendor/bin/phpcs -i"
	}
```

The output I get is:
```
> @php vendor/bin/phpcs -i

dir=$(cd "${0%[/\\]*}" > /dev/null; cd "../squizlabs/php_codesniffer/bin" && pwd)

if [ -d /proc/cygdrive ] && [[ $(which php) == $(readlink -n /proc/cygdrive)/* ]]; then
   # We are in Cgywin using Windows php, so the path must be translated
   dir=$(cygpath -m "$dir");
fi

"${dir}/phpcs" "$@"
```

I'm most definitely no command-line guru, so any help is appreciated :heart:

**Comment by jrfnl** [comment]
@jvasseur You're a star! That works like a treat :heart:
