### ISSUE TITLE
composer 在root账户下不可使用 

### ISSUE THREAD

**Issue by zhou5210** [composer/composer#7646]
[root@iz2zefnmihs8r2l9hi3fnez thinkphp-swoole]# composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files

虽然可以切换用户实现,但是 不开心,因为实在是不方便,并且root不应该拥有所有权嘛,可以出提示,为什么直接干掉了,这是我想问的,就算切换用户 不还得获取相应的权限嘛,到最后在某些位置 普通用户≈root用户的权限

**Comment by taxusorg** [comment]
“获取相应的权限”是什么权限？打算把站点放在哪？

**Comment by zhou5210** [comment]
@taxusorg   在结尾加上  --no-plugins --no-scripts  可以执行 但是不是我想要 的

**Comment by taxusorg** [comment]
Nothing to install or update
没有需要安装或者更新的
这个和权限有关吗？
贴出conposer.json来看看

**Comment by sdjdd** [comment]
**Do not run Composer as root/super user!** 只是一个警告，防止使用超级用户运行恶意代码。
