### ISSUE TITLE
run command in background in composer script 

### ISSUE THREAD

**Issue by amin3mej** [composer/composer#7650]
My `composer.json`:

```json
"scripts" : {
     "test": [
            "nohup ./yii serve --port=8086 &",
            "./yii migrate/fresh --interactive=0",
            " ./vendor/bin/codecept run api",
        ],
}
```
When i run `composer test` I except the command run step by step.
and when run it, This stack in the first command and don't run other commands.
How i can send the first command to background and run next commands?

Thank's for helping.

**Comment by alcohol** [comment]
AFAIK, not supported. But I could be wrong.

**Comment by Seldaek** [comment]
Indeed not supported and probably won't be so closing.
