### ISSUE TITLE
Use composer -v to show you are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug According to the https://getcomposer.org/xdebug injury method, still won't Help

### ISSUE THREAD

**Issue by Heartbeatc** [composer/composer#7651]
![image](https://user-images.githubusercontent.com/39974543/45620005-e8a47280-baad-11e8-8ae5-351b18701679.png)

**Comment by stof** [comment]
The version of Composer you use is quite old (March 2016). Some of the features related to Xdebug and documented in https://getcomposer.org/xdebug (restarting automatically for instance) have been implemented more recently than that.
