### ISSUE TITLE
Composer No driver found

### ISSUE THREAD

**Issue by AlexanderChoudhury** [composer/composer#7655]
![no driver found](https://user-images.githubusercontent.com/28726954/45748168-2500db80-bc32-11e8-8f0f-438267335ad6.png)
I got this problem with my composer did anyone know what cause this problem?? Thank you

**Comment by alcohol** [comment]
It looks like you specified a local VCS repository in your `composer.json`. But it also looks like that path does not actually represent a VCS repository (or an unsupported VCS type).

**Comment by AlexanderChoudhury** [comment]
and how to fix that? can you help me? because im really new with composer and building a web thank you @alcohol

**Comment by alcohol** [comment]
I cannot help you because I have no idea what you are doing.
