### ISSUE TITLE
Too low strictness in `outdated` command

### ISSUE THREAD

**Issue by Wirone** [composer/composer#7656]
Is it possible to make `composer outdated` command ignore some updates that cannot be done safely? I have:
```
$ composer outdated --direct --minor-only --strict
kartik-v/yii2-detail-view v1.7.6 v1.7.7 Various enhancements to the Yii 2 Detail View with multi model...
kartik-v/yii2-dialog      v1.0.1 v1.0.4 An asset bundle for bootstrap3-dialog for Yii 2.0 framework.
kartik-v/yii2-grid        v3.1.8 v3.2.1 Yii 2 GridView on steroids. Various enhancements and utilities...
kartik-v/yii2-krajee-base v1.8.9 v1.9.4 Base library and foundation components for all Yii2 Krajee ext...
```
and the point is I can't update at least first 2 packages (last one is a dependency, but I've added it with strict constraint `~1.8.0` to prevent using non-compatible `1.9` branch) because some part of the UI stop working and I don't have time now to fix it. I thought `--minor-only` would do the trick, but even if I define `"kartik-v/yii2-dialog": "1.0.1"` (exact version) it complains about possible update.

Any idea how it could be done?

Composer 1.6.3 / 1.7.2

**Comment by stof** [comment]
`composer outdated` is not meant to show you which package would be updated by a `composer update` without changing your existing constraints, but which one are outdated.

A package having a 1.9.0 release while you want to stay on 1.8.x is still an outdated package, even if you decided to keep it outdated.

`--minor-only` means it won't ask you to upgrade major versions. But 1.8.x to 1.9.0 is **not** a major version change. It is a minor version change.

**Comment by stof** [comment]
Well, I don't understand what you are trying to achieve here.

And yes, I know that in practice, not all packages are following semver (and even when they do follow it, regressions happen, and any bugfix might be considered a BC break in your project if you were actually relying on the buggy behavior).

`composer outdated` is precisely meant to *not* resolve dependencies by taking requirements into account (as that would make it an equivalent of `update --dry-run`, but to show you were you have outdated packages that may need to be updated, potentially by changing requirements. Then, it is up to you to decide whether you want to update them or to keep them outdated for some reason.

**Comment by Wirone** [comment]
We check for outdated packages in CI job and I don't want failures (even if it's only warning) on packages that we know we won't update.

I don't want to resolve dependencies but only validate constraints per package, so if I have constraint that does not have newer version qualifying to it (like `~1.8.0` and there isn't any newer version in 1.8.x), Composer won't complain if I configure it do do so.

And for now I can't do this, so we have warnings in all pipelines.

**Comment by stof** [comment]
@Wirone checking outdated packages taking constraints into account requires running the solver. And that is what `composer update` is about (the `--dry-run` option means it won't actually perform the update but only report what the update would do).

If you want your CI to take constraints into account, you should not be using `composer outdated` as your CI command.

**Comment by Wirone** [comment]
Ok, I don't know internals of `outdated` command, so I won't argue with your point.

However, adding optional flag for ignoring some packages won't change command's logic, it would only filter the output, so there wouldn't be exit code `1` if there are ignored outdated packages but there aren't any non-ignored outdated packages.

Is it something that can be done?

**Comment by stof** [comment]
@Wirone but filtering output based on what ? If it has to filters based on constraints used to require it, that changes things a lot, as constraints can come from many packages.
And that cannot be applied as a post-processing step, as having 1.8.0 installed, with both 1.8.1 and 1.9.0 available should still mark it as outdated by your rules when requiring `1.8.x` (as it could be upgraded to 1.8.1), but the post-processing would say that `1.9.0` needs to be filtered out.

**Comment by Wirone** [comment]
@stof no, I thought about simple filtering by package name(s). So taking current behavior and result, just before printing report it could filter out packages explicitely marked as ignored (because it's already known that they shouldn't be updated).

**Comment by xabbuh** [comment]
This sounds like it would then just be another way to trigger `composer update --dry-run` as @stof said, wouldn't it?

**Comment by Wirone** [comment]
@xabbuh not really because:
- we use `composer outdated -D --strict` and rely on exit code (failing job) and I suppose `composer update --dry-run` doesn't return `1` after printing the output if there was something "updated"
- `composer update` won't "update" anything if you have constraint `^1.0.0` and there is `v1.1.0` available, while `composer outdated` will warn about new version

What I want to achieve, assuming output from issue description, is ignoring 4 listed packages and fail the job only if there is any other package to update.

**Comment by stof** [comment]
`composer outdated` is **not** meant to tell you whether there are packages to update based on your existing constraints. Its goal does not include the `based on your existing constraints` (taking constraints into account is what `composer update` does, as it requires using the solver to deal with constraints).

IMO, this package filtering does not make sense in `composer outdated` (and adding such feature means that Composer maintainers have to maintain it in the future, and that the command becomes more complex for everyone)

**Comment by stof** [comment]
side note: `^1.0.0` is matched by 1.1.0, the solver would allow it too.

**Comment by Wirone** [comment]
@stof yeah, I actually was thinking about `~1.0.0` (so only `1.0.x` are accepted), I always mix it :)

**Comment by curry684** [comment]
> Even worse, updating kartik-v/yii2-dialog from 1.0.1 to 1.0.3(!) makes our UI's confirmation modal works differently (ugly dialog with much vertical empty spaces, which doesn't fit screen's height).

Composer relies on package maintainers either using Semver correctly, or end users knowing that their package maintainers don't and adapting their constraints accordingly. I don't see any merit in adding/changing Composer functionality to cater for bad package release protocols.

**Comment by Wirone** [comment]
@curry684 the problem is `composer outdated` informs about possible update even if my constraint is set to exact version. And from discussion above you can see that won't change, because constraints are not taken into account here.

So the only way of achieving what we need (no failures in pipeline) is to ignore packages after checking available versions, but before printing the output.

Of course, we can remove `--strict` flag, add some `grep`s and return `0`/`1` code based on `wc -l`, but I really thought it could be done directly in the command.

**Comment by curry684** [comment]
> the problem is composer outdated informs about possible update even if my constraint is set to exact version

It's meant to. The question is whether it shows it yellow or red.

> So the only way of achieving what we need (no failures in pipeline)

Imho that's a pretty fubar idea anyway. I cannot think of ANY good reason where missing either a major, minor or patch update to a dependency should cause CI or CD to fail, as the only thing it implies is that development and/or QA have not had time yet to apply and test it thoroughly, or are consciously not taking the update. In both cases it's neither a software failure (thus CI shouldn't fail) nor a stability failure (thus CD shouldn't fail), and it will permanently block maintenance of older versions than edge since they will and should be locked to older dependencies.

**Comment by Wirone** [comment]
@curry684 

> It's meant to.

I know. It was discussed already - topic closed.

> I cannot think of ANY good reason where missing either a major, minor or patch update to a dependency should cause CI or CD to fail (...)

We use `allow_failure` flag and dedicated job in test stage, so there is only a warning. Still, the point is I don't want warnings if there aren't any upgradable packages that I'm interested in (=ignore those I won't update).

And to be clear: ignoring must be explicit and per-project, so you would do:

```
composer outdated -D --strict --ignore=kartik-v/yii2-detail-view --ignore=kartik-v/yii2-dialog --ignore=kartik-v/yii2-grid --ignore=kartik-v/yii2-krajee-base
```
or something like that. Any other package, not listed in `--ignore`, when newer version is available, should trigger `1` exit code.

**Comment by Wirone** [comment]
I've changed commit's author because I previously commited on company's credentials.
