### ISSUE TITLE
Add option to disable all chmod operations in composer so it can be run in a guest VM shared folder without sudo

### ISSUE THREAD

**Issue by therobyouknow** [composer/composer#7662]
Composer is failing to run commands such as require, when run inside a guest-VM where the composer.json is inside a directory that is shared from the host machine (NFS share).

Specifically, the require command is attempting to set permissions as a step within its execution steps.

My `composer.json`:

```json
...replace me...
```

N/A

Output of `composer diagnose`:

```
...replace me...
```

N/A

When I run this command:

```
...replace me...
```
N/A

I get the following output:

chmod operation not permitted

```
...replace me...
```

And I expected this to happen:

For composer not to fail when setting permissions.

Really, on a development (non-production setup) it doesn't need to set them, if the files and folders have sufficient permissions.

I don't understand why composer had to change permissions on  a development environment, for the following reasons:
a) if they are already sufficient, e.g. 777 for directories, 666 for files - so why change them?
b) on a developer's local environment, requiring permissions is not necessary for security measures

**Comment by therobyouknow** [comment]
I think composer also tries to set timestamps (to assist it's dependency engine at a guess as to what needs to be downloaded etc), and these also fail, I think for similar reasons as for permissions failing. It might be hard to justify disabling time stamp changes  as well as permissions as this might interfere with the workings of composer.

Thoughts?

**Comment by alcohol** [comment]
> Thoughts?

Use Docker.

I have not used VirtualBox in a very long time myself. But back when I did, I never had issues with Composer and file/directory permissions etc. It sounds to me like you perhaps have a poor understanding of how permissions work or how to handle them in your environment. What you are asking for is a lot of work to support a specific workflow of a very few select individuals. This will most likely not happen.
