### ISSUE TITLE
Composer installs for package in tagged release but not master

### ISSUE THREAD

**Issue by RikSomers** [composer/composer#7666]
Hi!

At a company I work at, we got this weird bug where composer install would say the lnstallation failed due to `Your requirements could not be resolved to an installable set of packages.`

The weird thing is that the `composer.json` file will install correctly when we use a tagged release (e.g. 1.10.0), but will not install on the master branch (where our CI will run). 

So, when our CI tries to do a composer install or composer update without there being a `vendor/` folder and without there being a `composer.lock` file, it just fails with the message that is discribed below.

If we tell composer to install the specific version 5.4.25 of `company/package-two`, or we add `company/another-package` with version 1.6.1 to the `composer.json` it also correctly installs without any further issues.

For our company packages we use a private repository as can be seen in the `repositories` key. For the rest, the normal packagist is being used. 

Due to secrecy, I renamed our own packages in the following composer file `composer.json`:

```json
{
    "name": "company/TestPackage",
    "license": "proprietary",
    "require": {
        "php": "^7.1.3",
        "illuminate/support": "5.6.*",
        "league/csv": "^9.0",
        "company/package-one": "^1.11",
        "company/package-two": "^5.4.24",
        "company/package-three": "^1.6",
        "company/package-four": "^2.6",
        "moontoast/math": "^1.1",
        "ramsey/uuid": "^3.5"
    },
    "require-dev": {
        "company/testcase-one": "~2.3",
        "company/testcase-two": "~2.3",
        "company/testcase-three": "~3.6"
    },
   "repositories": [
        { "type": "composer", "url": "http://company.com/repo/private/" }
    ],
    "autoload": {
        "psr-4": {
            "company\\TestPackage\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "company\\Tests\\TestPackage\\": "tests/"
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true,
    "config": {
        "secure-http": false,
        "sort-packages": true
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.7.2
PHP version: 7.1.11
PHP binary path: C:\xampp\php\php.exe
```

When I run this command:

```
composer install -vvv
```

I get the following output:

```
[...]
Resolving dependencies through SAT
Looking at all rules.
Something's changed, looking at all rules again (pass #4)
Dependency resolution completed in 0.328 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install company/another-package 1.6.1
    - company/package-two 5.4.24 requires company/another-package ^1.6 -> satisfiable by company/another-package[1.6.0, 1.6.1].
    - company/package-two 5.4.25 requires company/another-package ^1.6 -> satisfiable by company/another-package[1.6.0, 1.6.1].
    - Conclusion: don't install company/another-package 1.6.0|install company/another-package 1.6.1
    - Installation request for company/package-two ^5.4 -> satisfiable by company/package-two[5.4.24, 5.4.25].
```

And I expected this to happen:
I expect everything to work correctly, as it does on the tagged release. But it does not.

**Comment by stof** [comment]
without knowing the requirements of `company/another-package` and `company/package-two` in each of their version, there is nothing we can do to help you, as there is not enough info to reproduce it.

**Comment by alcohol** [comment]
Need a reproducible scenario.

**Comment by RikSomers** [comment]
If I could reproduce the scenrario I would have, but I have not been able to reproduce it with other packages.

That being said, for whatever reason, it resolved itself over te weekends. So it might have been some kind of caching issue on our part.
