### ISSUE TITLE
Self-upgrading Composer complains about missing SHA384 in OpenSSL (while it's avaliable in both ext/openssl and ext/hash)

### ISSUE THREAD

**Issue by Majkl578** [composer/composer#7669]
```
$ composer self -v 
Updating to version 1.7.2 (stable channel).
   Downloading (100%)         

                                                                                               
  [RuntimeException]                                                                           
  SHA384 is not supported by your openssl extension, could not verify the phar file integrity  
                                                                                               

Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Command/SelfUpdateCommand.php:218
 Composer\Command\SelfUpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:242
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:843
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:251
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:59
 require() at /usr/local/bin/composer:24

self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--set-channel-only] [--] [<version>]
```

Algorithms available in my ext/openssl include both SHA384 and SHA3-384:
```
$ php -r 'var_dump(openssl_get_md_methods());' | grep -i 384
  string(8) "sha3-384"
  string(6) "sha384"
```

Algorithms available in my ext/hash also include both SHA384 and SHA3-384:
```
$ php -r 'var_dump(hash_algos());' | grep 384
  string(6) "sha384"
  string(8) "sha3-384"
```

PHP 7.2.9 compiled against OpenSSL 1.1.1.

**Comment by enumag** [comment]
The code in `SelfUpdateCommand` looks like this:

```
            if (!in_array('SHA384', openssl_get_md_methods())) {
                throw new \RuntimeException('SHA384 is not supported by your openssl extension, could not verify the phar file integrity');
            }
```

So maybe it's just a case sensitivity issue?

In the example from [PHP documentation](http://php.net/manual/en/function.openssl-get-md-methods.php) the result has both `"sha384"` and `"SHA384"`. Not sure why one of them would be missing.

**Comment by alcohol** [comment]
Yeah sorry, this is a scenario self-update simply cannot fix. You'll have to manually update composer.

**Comment by Majkl578** [comment]
That sounds like an impossible upgrade path. I will never be able to upgrade to 1.7 without the patch, but the patch is not avaliable in 1.6.x. :roll_eyes:

**Comment by Majkl578** [comment]
> You'll have to manually update composer.

Ok, fair, but maybe this should be communicated better, not by throwing an exception saying SHA384 is not available.

**Comment by alcohol** [comment]
We can't do much about that. The openssl package changed something in 1.1.1 which we never anticipated for. If you had not upgraded your openssl package, you would still be able to update composer right now. We cannot throw a more descriptive exception because this is a situation we had never foreseen.

**Comment by staabm** [comment]
Is this something which can/should be reported to openssl as a possible bc break?

**Comment by alcohol** [comment]
I don't think this could be considered a BC break.

**Comment by rvanlaak** [comment]
Just came here after upgrading PHP to 7.3, to which the error is not related. The issue heading was clear enough to find out a reinstallation was the way to go :+1"

**Comment by Marthy-M** [comment]
Possible workaround is to run self-update with an older PHP version (with an older OpenSSL package).

Worked for me on Ubuntu:
`$ update-alternatives --set php /usr/bin/php5
$ composer self-update
$ update-alternatives --set php /usr/bin/php7.3`

**Comment by alexweissman** [comment]
You might still see this error even after upgrading if you still have the `composer` command linked to an older version of Composer.

**Comment by maniac0s** [comment]
So how do I solve this now?
