### ISSUE TITLE
Skip only local scripts (still run plugins)

### ISSUE THREAD

**Issue by jrjohnson** [composer/composer#7670]
### What?

Is it be possible to skip only the scripts in my `composer.json` without also skipping anything in my vendors?

### Why?
In the default `composer.json` for a new symfony app scripts are defined to clear the cache. For developers and anyone installing out application locally this is perfect. It ensures that the cache is clear before doing anything else.

```json
{
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
}

```

However when we install the same app into a container we don't want the cache to be cleared (clearing the cache requires access to a redis machine that would never be available in a container build step). 

So we run `composer install --no-scripts`.  The problem is that this prevents scripts from plugins like 
`ocramius/package-versions` and `symfony/flex` from running as well.

Thanks,

**Comment by alcohol** [comment]
This is currently not possible.

I find it quite odd that your cache clear requires access to a redis machine. Maybe make it an optional one? I thought `--no-optional-warmers` applies to both cache:clear and cache:warmup.

**Comment by jrjohnson** [comment]
Thanks.  I haven't dug too far into the redis issue. In general we don't want any of these scripts to run on docker since they will be handled differently there, the cache clear was just a good example.

We will need to reorganize our scripts and our docs to be sure that on-prem installers of our app who aren't using docker get all the steps right.  This isn't too big of a deal, I just wanted to be sure I wasn't missing something easy.

Not sure if I should close this, or leave it open as a feature request. Happy to do whatever is best for the project.

**Comment by Seldaek** [comment]
Rather close this, we have this as a convenience feature but the goal isn't to become a fully fledged build tool :)
