### ISSUE TITLE
Change .composer directory

### ISSUE THREAD

**Issue by Nitwel** [composer/composer#7671]
My issue is that composer uses the "home" directory for the ".composer" folder and its not changeable.
Is there a way to not use the "home" directory wich I did not found or is it just not possible to have the folder somewhere else?

The reason why I have to use another directory is simply that I dont have write permission for this folder.

**Comment by alcohol** [comment]
That is not exactly true.

See https://getcomposer.org/doc/03-cli.md#composer-home for more information.
