### ISSUE TITLE
transport-options not removed on composer update which switches package repo source

### ISSUE THREAD

**Issue by naderman** [composer/composer#7672]
If you currently use a package from a custom repository which has "transport-options" defined, then run composer update mirrors which replaces the same packages with packages from another repository, somehow the "transport-options" of the old packages remain. This can lead to 400 Bad Request errors on requests to the new mirror repository because of incorrect transport options.

**Comment by AaronHolbrook** [comment]
FYI, to work through this:

* delete the existing composer.lock file
* delete the vendor directory (important or composer won't regenerate correctly)
* run `composer update mirrors`

Thanks for all the help @naderman !!
