### ISSUE TITLE
Update fails entirely when a single repository connection fails.

### ISSUE THREAD

**Issue by adjenks** [composer/composer#7676]
My `composer.json`, the google example should obviously fail since it is not a composer repo:

```json
{
	"name": "Sample",
	"description": "Sample composer file",
	"license": "proprietary",
	"repositories": [{
			"type": "composer",
			"url": "https://google.ca/"
		}, {
			"type": "composer",
			"url": "https://packagist.org/"
		}
	],
	"require": {
		"phptal/phptal": "^1.3",
		"justinrainbow/json-schema": "^5.2"
	},
	"autoload": {
		"psr-4": {
			"": "src/"
		}
	},
	"require-dev": {
		"phpmd/phpmd": "^2.6"
	}
}

```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.7.2
PHP version: 7.1.22
PHP binary path: /usr/bin/php

```

When I run this command:

```
php ./bin/composer.phar -v --prefer-dist update
```

I get the following output:

```
Loading composer repositories with package information


  [Composer\Downloader\TransportException]
  The "https://google.ca/packages.json" file could not be downloaded (HTTP/1.1 404 Not Found)


Exception trace: ***Exception details redacted***
```

And I expected this to happen:

I expect it to just fallback to the next repo available and see if the packages are available there. What if I have a local packagist mirror as well as packagist.org, as well as some other repos. I would like redundancy and fallback abilities. I am allowed to define redundant repos, but there is no fallback. It should report an error, but continue to load info from the next repo if one fails.

**Comment by alcohol** [comment]
> I would like redundancy and fallback abilities.

So submit a feature request.

> I am allowed to define redundant repos, but there is no fallback.

Nowhere in our documentation does it state that repository definitions are meant to be redundant or used as fallback.

> It should report an error, but continue to load info from the next repo if one fails.

According to what? Because as far as I know, it is behaving exactly as it was implemented.


TL/DR; submit a feature request, not a complaint.

**Comment by adjenks** [comment]
I'm sorry, my mistake. Only once I began writing it did I realize that it wasn't intended to do that. It sort of changed from a bug report to a feature request as I was going along. I will resubmit a ticket for a feature request.
