### ISSUE TITLE
Invalid JSON/XML in output due to PHP deprecation warnings

### ISSUE THREAD

**Issue by AGSPhoenix** [composer/composer#7679]
Output of `composer diagnose`:

```
Comments starting with '#' are deprecated in /etc/hhvm//php.ini on line 10
Comments starting with '#' are deprecated in /etc/hhvm//php.ini on line 17
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
WARNING
Github has a rate limit on their API. You currently have 0 out of 60 requests left.
See https://developer.github.com/v3/#rate-limiting and also
    https://getcomposer.org/doc/articles/troubleshooting.md#api-rate-limit-and-oauth-tokens
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 1.7.2
PHP version: 7.1.99
PHP binary path: /usr/bin/hhvm
```

When I run this command:

```
/usr/bin/php /usr/local/bin/composer help install --format=json
```

I get the following output:

```
Comments starting with '#' are deprecated in /etc/hhvm//php.ini on line 10
Comments starting with '#' are deprecated in /etc/hhvm//php.ini on line 17
{"name":"install","usage":   [snip]   "default":null}}}}
```
(the warnings appear both on stderr and stdout)

I'm using ansible's Composer module, and the deprecation warnings break the module's interactions with Composer. The obvious workaround is to update the comments to use semicolons (and I'll be doing so), but I'd like to see a proper fix if possible. Presumably these messages are coming from PHP as it parses the config file; is there anything Composer can do to suppress them?

This issue is fairly similar to #5147 (and I'm mentioning it for the benefit of other composer users that find that issue).

**Comment by alcohol** [comment]
There is nothing Composer can do about it. You should fix your HHVM configuration.
