### ISSUE TITLE
"autoload_read.php" some autoload problem

### ISSUE THREAD

**Issue by Zhucola** [composer/composer#7684]
spl_autoload_register(array('ComposerAutoloaderInit71cac9d4c8c41e355d5b531006266236', 'loadClassLoader'), true, true);
self::$loader = $loader = new \Composer\Autoload\ClassLoader();
spl_autoload_unregister(array('ComposerAutoloaderInit71cac9d4c8c41e355d5b531006266236', 'loadClassLoader'));

why not replace "require __DIR__ . '/ClassLoader.php';"

thanks

**Comment by alcohol** [comment]
- I do not see any actual problem reported.
- I see a suggestion to replace something. But no motivation describing why.
- Unclear what you actually want from us.

**Comment by alcohol** [comment]
I think @Seldaek can explain this better than me.

**Comment by stof** [comment]
You could have multiple locations having the `Composer\Autoload\ClassLoader` class definition. For instance, many projects are embedding it in their phar, and a  tool installed with `composer global` creates a global autoloader setup too.
And it is common for these tools to load the project-level autoloader in the same process than their own code. For such case, we need to avoid loading the ClassLoader definition a second time as it would break. And `require_once` does not help, as both definitions are in separate files.

Relying on PHP's autoloading system to load the class definition when necessary was found to be the most reliable and simplest solution (Composer had some another implementation previously, but which was less reliable for some weird cases).

**Comment by stof** [comment]
See https://github.com/composer/composer/pull/1313 for the PR implementing that.

**Comment by mpvdk** [comment]
@stof 
I know this i an old topic, but I am trying to get a thorough understanding of composer and I can't seem to get a grasp on this particular implementation, nor can I find any more information about it besides from this Github issue. 

More specifically, I can't imagine a situation why the \Composer\Autoload\ClassLoader would be defined twice in a single PHP process. And why would a phar executable need an autoloader anyway? Isn't the point of a phar that the entire application -including all class definitions - is contained in a single file?

I know that this may be more a stackoverflow-kind-of question, but I'm hoping you might be willing to shed some light on the issue for me. Perhaps in the form of a concrete example of how a situation like that may occur. It would be greatly appreciated.

**Comment by stof** [comment]
@mpvdk the phar is a single file on the filesystem. But it is not a single *PHP* file. It is just that the PHP process knows how to access the different files inside that archive (a phar file is more similar to a zip or tar file than to a php file)

**Comment by mpvdk** [comment]
@stof  
Following your reply I have extracted and inspected a few phar archives, and this has actually cleared things up for me. I have also re-read the https://github.com/composer/composer/issues/1248, and now your original answer from October 1st 2018 makes a lot more sense. 

Thank you!
