### ISSUE TITLE
How to execute command script only once without a lock file

### ISSUE THREAD

**Issue by jpegram2** [composer/composer#7685]
So I get the logic behind post-install-cmd and post-update-cmd but how do you execute a script **ONLY ONCE** when a lock file **DOES NOT** exist? For instance, I have a repository that is maintained as a skeleton, so when it is cloned the user is told to run composer install. (As noted already in past conversations, telling them to run composer update seems counter intuitive). 

In this case, when they clone the repository a .git directory is created. I would like to not rely on the user understanding "now delete the .git" directory before committing to their project repository. I thought I could do this with a cmd script but the only way I can get it to work is by putting it in the post-update-cmd directive and doing that causes the script to execute on every update which would subsequently delete the correct .git directory.

Any thoughts on how to handle this?

**Comment by alcohol** [comment]
Composer scripts were not intended to be used for such a task. This is something the project should simply document.

But;
- you could make your script master and detect if the `.git` directory is still there or not.
- you could store some state in some file and attempt to read from said file.
- you could store state in the composer.json `extra` section (but you might annoy a lot of users by doing this).
