### ISSUE TITLE
Some help with random connection issue

### ISSUE THREAD

**Issue by joveice** [composer/composer#7686]
When I run this command:

```
composer require adldap2/adldap2-laravel
```

I get the following output:

```
Authentication required (repo.packagist.org)
```

And I expected this to happen:
*installed*

I'm behind a proxy and this worked fine, but out of the blue this now happens, I updated to latest and it still does. The proxy server logs shows that it tries to connect to http://repo.packagist.org and not https. Why does it try http now? I have only https opened.

**Comment by alcohol** [comment]
Composer can fallback to http if https does not work.

But it looks to me like your proxy setup is broken. There is not much Composer can do about this. It is up to you or your network administrator to make sure your proxy behaves correctly and that you supply the appropriate values in the correct environment variables.

**Comment by joveice** [comment]
I believe the proxy has not changed (not 100% sure) but I can reach repo on https and not http, so I don't see why it falls to http when https already works?

**Comment by joveice** [comment]
I still don't know what was the issue, a tcpdump says it never tried https and went right for http. Ended up with opening for http as I need to keep working.

**Comment by alcohol** [comment]
It is possible to configure Composer in such a way that it will always use http. But it should not do this by default.
