### ISSUE TITLE
Respect other gitignore files when archiving

### ISSUE THREAD

**Issue by gszy** [composer/composer#7694]
Currently `composer archive` ignores files that match patterns in `.gitignore` and `.gitattributes` (at least [GitExcludeFilter.php:33–47][1] suggests that). I think it should also respect other gitignore files, like `$GIT_DIR/info/exclude` or `$XDG_CONFIG_HOME/git/ignore`.

Such change would help for example when IDEs configuration files are ignored in developer’s personal gitignore file instead of project’s common `.gitignore`. Currently I have `.gitignore` clean of any `.atom`s, `.vscode`s etc., but I’d have to add them to [`archive.exclude`][2] in `composer.json`.

Unfortunately, this issue is probably against the ideas described in #7358.

**Update**: there can also be `.gitignore`s in subdirectories.

[1]: https://github.com/composer/composer/blob/1.7.2/src/Composer/Package/Archiver/GitExcludeFilter.php#L33-L47
[2]: https://getcomposer.org/doc/04-schema.md#archive

**Comment by sbuzonas** [comment]
I think in the spirit of #7358, `gitattributes` should be the standard for archiving.

It does make sense to me to consider `core.attributesFile`, `$GIT_DIR/info/attributes`, and all `.gitattributes` files within the repo.

**Comment by Seldaek** [comment]
As you pointed out, this goes against https://github.com/composer/composer/issues/7358 and we've decided to go for that approach rather than following gitignore as this does create issues in practice when files are added to git despite being ignored (which you can do with `git add -f [file]`). I'll thus close this.
