### ISSUE TITLE
composer require knplabs/knp-paginator-bundle error

### ISSUE THREAD

**Issue by ockang** [composer/composer#7697]
The "http://repo.packagist.org/p/provider-2016%246c3a32420753d469fb69db279a1553a30ba246cde5206a3fc23da02a01514b34.json" file could not be downloaded: failed to open stream: Operation timed out
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info

  [Composer\Downloader\TransportException]
  The "http://repo.packagist.org/p/provider-2016%246c3a32420753d469fb69db279a1553a30ba246cde5206a3fc23da02a01514b34.json" file could not be downloaded: php_network_getaddresses: getaddrinf
  o failed: nodename nor servname provided, or not known
  failed to open stream: php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known

**Comment by alcohol** [comment]
Cannot reproduce. Check with your network administrator.
