### ISSUE TITLE
help pls composer

### ISSUE THREAD

**Issue by onurbabax** [composer/composer#7701]
composer require mgp25/instagram-php
Using version ^2.0 for mgp25/instagram-php
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mgp25/instagram-php ^2.0 -> satisfiable by mgp25/instagram-php[v2.0].
    - mgp25/instagram-php v2.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.

  To enable extensions, verify that they are enabled in those .ini files:

**Comment by stof** [comment]
Well, I think the output already tells you what's wrong: 

> the requested PHP extension curl is missing from your system.
