### ISSUE TITLE
 [Composer\Downloader\TransportException]                                                                                                                         Invalid credentials for 'https://packagist.phpcomposer.com/p/spatie/once%24ce7b81bcbb4de6a18c1e92fa39645769db03f8d5a08e0a96b343a70369a83aa5.json', aborting. 

### ISSUE THREAD

**Issue by lilianjin** [composer/composer#7704]
[Composer\Downloader\TransportException]                                                                                                                      
  Invalid credentials for 'https://packagist.phpcomposer.com/p/spatie/once%24ce7b81bcbb4de6a18c1e92fa39645769db03f8d5a08e0a96b343a70369a83aa5.json', aborting. 
```bash
composer diag  
```
Key fideloper/proxy is a duplicate in ./composer.json at line 16
Checking composer.json: WARNING
require.laravel/nova : unbound version constraints (*) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.7.2
PHP version: 7.2.10
PHP binary path: /usr/local/Cellar/php/7.2.10/bin/php
```
composer update
Key fideloper/proxy is a duplicate in ./composer.json at line 16
Loading composer repositories with package information
Updating dependencies (including require-dev)
                                             
    Authentication required (packagist.phpcomposer.com):
      Username:
```
I really can't understand why there is such a problem. I tried to completely clean and reinstall composre, which is obviously invalid.

**Comment by alcohol** [comment]
Your composer.json seems to contain a duplicate entry. Also, I have no idea what packagist.phpcomposer.com is. But it seems you need credentials to connect to it. It is not operated by us.
