### ISSUE TITLE
Feature version guessing depends on git branch order

### ISSUE THREAD

**Issue by dtakken** [composer/composer#7710]
If my project is on a branch configured in non-feature-branches and I have a dependency constrained at version `self.version`, composer will report the current version to be a parent of the current branch rather than the branch itself. For example, here is my project git tree:

```
+- master
 \
  +- 2.0.0-dev
   \
    +- feature <== currently checked out branch

```
My `composer.json`:
```
{
  "name": "foo/bar",
  "description": "test",
  "minimum-stability": "dev",
  "prefer-stable": true,
  "non-feature-branches": ["feature"],
  "require":
  {
    "some/dependency": "self.version",
  }
}
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.7.2
PHP version: 7.2.10
PHP binary path: /usr/bin/php7.2

```

When I run this command:

```
composer show -s
```

I get the following output:

```
name     : foo/bar
descrip. : test
keywords : 
versions : * dev-2.0.0-dev
type     : library
source   : []  4ab29502aa482515ab9992078be40081fa867ac8
dist     : []  4ab29502aa482515ab9992078be40081fa867ac8
names    : foo/bar

requires
some/dependency self.version

```

And I expected this output:

```
name     : foo/bar
descrip. : test
keywords : 
versions : * dev-feature
type     : library
source   : []  4ab29502aa482515ab9992078be40081fa867ac8
dist     : []  4ab29502aa482515ab9992078be40081fa867ac8
names    : foo/bar

requires
some/dependency self.version

```

After looking at the the version guessing code, specifically this loop:

https://github.com/composer/composer/blob/041028920f7ba5be4a3fab3ba344ce4fc1d09ae2/src/Composer/Package/Version/VersionGuesser.php#L223-L244

I realized that the outcome of the guessing depends on the order of the branches returned by the `git branch --no-color --no-abbrev -v` command, which is used earlier in the code to get the list of branches. Only if the currently checked out branch happens to be the first in the list produced by git, it breaks out of the loop right away on L226 and the branch is accepted as the currently guessed package version. So far so good.

However, when git is configured to order branches by name (which is the default I believe), the `2.0.0-dev` branch will be processed before `feature`, overwriting `$version` to become `dev-2.0.0-dev`. It will still break out of the loop on L226 when processing the `feature` branch, but the resulting version will be `dev-2.0.0-dev` now.

My guess is that this is not correct and that `$version` should be set to the candidate branch just before the break on L226. Does that make sense?

**Comment by alcohol** [comment]
This kind of voodoo is probably better "fixed" by simply using https://getcomposer.org/doc/03-cli.md#composer-root-version
