### ISSUE TITLE
* 2d9abbbb28fd917589eaf.json" file could not be downloaded (HTTP/ 1.1 503 Service Unavailable).

### ISSUE THREAD

**Issue by seanbw1609** [composer/composer#7712]
My `composer.json`:

```
{
}
```

```json

Output of `composer diagnose`:
```

> Checking composer.json: WARNING
> No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
> Checking platform settings: OK
> Checking git settings: OK
> Checking http connectivity to packagist: OK
> Checking https connectivity to packagist: OK
> Checking github.com rate limit: OK
> Checking disk free space: OK
> Checking pubkeys:
> Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
> Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
> OK
> Checking composer version: OK
> Composer version: 1.7.2
> PHP version: 7.0.32
> PHP binary path:  `/usr/bin/php7.0>`

When I run this command:  < php composer.phar global require cpriego/valet-linux>
which is just a procedure in this guide:  [``https://hackernoon.com/experimenting-with-windows-subsystem-for-linux-and-web-development-85180b90382f`](Experimenting with Windows Subsystem for Linux and Web Development)
At step 10 , we are supposed to download valet and then export the path to .bashrc but I cannot get past step 10 and this is frustrating.
Instead of getting valet downloaded, I get this error:
I get the following output:
<

> " [Composer\Downloader\TransportException]   The "http://repo.packagist.org/p/provider-2014%245f5764e22cd27614d019395ae20acf6e1b9b70bb77f29ad5b092d8301a5ed8ba.json" file could not be downloaded (HTTP/  1.1 503 Service Unavailable)
> require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]..."

And I expected this to happen: download the https://cpriego.github.io/valet-linux/ package but it does not. The issue was examined in #issue 4388 but this particular issue "file could not be downloaded (HTTP/   1.1 503 Service Unavailable)" was only brought at the end of the issue and was never examined in detail:

I have tried all the resolutions offered in that issue starting with:

locate cacert.pem and created the cacert.pem file as advised in hat issue.

I tried this solution:
php -i | grep -i ssl but this is what I get:

> <Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, tls, tlsv1.0, tlsv1.1, tlsv1.2
> SSL => Yes
> SSL Version => OpenSSL/1.0.2g
> core SSL => supported
> extended SSL => supported
> openssl
> OpenSSL support => enabled
> OpenSSL Library Version => OpenSSL 1.0.2g  1 Mar 2016
> OpenSSL Header Version => OpenSSL 1.0.2g  1 Mar 2016
> Openssl default config => /usr/lib/ssl/openssl.cnf
> openssl.cafile => no value => no value
> openssl.capath => no value => no value
> Native OpenSSL support => enabled>
I don't seem to have any issue with my ssl.

Trying to self update gave me this:

 php composer.phar self-update -vvv

> Reading ./composer.json
> Loading config file ./composer.json
> Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
> Executing command (/home/seanb): git branch --no-color --no-abbrev -v
> Executing command (/home/seanb): git describe --exact-match --tags
> Executing command (/home/seanb): git log --pretty="%H" -n1 HEAD
> Executing command (/home/seanb): hg branch
> Executing command (/home/seanb): fossil branch list
> Executing command (/home/seanb): fossil tag list
> Executing command (/home/seanb): svn info --xml
> Reading /home/seanb/.config/composer/composer.json
> Loading config file /home/seanb/.config/composer/composer.json
> Running 1.7.2 (2018-08-16 16:57:12) with PHP 7.0.32-0ubuntu0.16.04.1 on Linux / 4.4.0-17692-Microsoft
> Downloading https://getcomposer.org/versions
> You are already using composer version 1.7.2 (stable channel).

the self update command gave me this:

>  php /usr/local/bin/composer global self-update
> Changed current directory to /home/seanb/.config/composer
> You are already using composer version 1.7.2 (stable channel).

The only obstacle to downloading this package is this http 1.1.503 issue and I can't get any solution from googling it with reference to composer so I am sorry but I have to open an issue here.
I will be grateful for any assistance.

Just to add one thing I  noticed . The problem file seems to be just two different files:

-  The "http://repo.packagist.org/p/provider-2013%24d27cd1aa6c7201cfe13c2133f98499487407365cdab2d9abbbb28fd917589eaf.json" file could not be downloaded (HTTP/  1.1 503 Service Unavailable)
-  Content-Length mismatch, received 15440 bytes out of the expected 331888
- The "http://repo.packagist.org/p/provider-2013%24d27cd1aa6c7201cfe13c2133f98499487407365cdab2d9abbbb28fd917589eaf.json" file could not be downloaded (HTTP/  1.1 503 Service Unavailable)
-  i cleared the cache then it changes
-  The "http://repo.packagist.org/p/provider-2014%245f5764e22cd27614d019395ae20acf6e1b9b70bb77f29ad5b092d8301a5ed8ba.json" file could not be downloaded (HTTP/  1.1 503 Service Unavailable)
- After trying the cacert solution, alias composer=user/local/bin/composer, self-update,composer init, composer diagnose error changes to:
- The "http://repo.packagist.org/p/provider-2014%245f5764e22cd27614d019395ae20acf6e1b9b70bb77f29ad5b092d8301a5ed8ba.json" file could not be downloaded (HTTP/  1.1 503 Service Unavailable)
- Tried this solution:  wget http://curl.haxx.se/ca/cacert.pem --no-check-certificate error is now:
-   The "http://repo.packagist.org/p/provider-2014%245f5764e22cd27614d019395ae20acf6e1b9b70bb77f29ad5b092d8301a5ed8ba.json" file could not be downloaded (HTTP/  1.1 503 Service Unavailable)
- I tried this command:
-  composer global require --prefer-stable cpriego/valet-linux and got this error:
-  The "http://repo.packagist.org/p/provider-2014%245f5764e22cd27614d019395ae20acf6e1b9b70bb77f29ad5b092d8301a5ed8ba.json" file could not be downloaded (HTTP/  1.1 503 Service Unavailable)

**Comment by alcohol** [comment]
It looks like the main site or one of the mirrors was having some issues. This is usually of temporary nature. Have you retried it later? Does it still fail with a 503?

**Comment by saber13812002** [comment]
it looks like iran wifi internet problem i change to IR-MCI my mobile phone and it is installed as well
