### ISSUE TITLE
Allow combining self.version with fallback version constraint

### ISSUE THREAD

**Issue by dtakken** [composer/composer#7713]
The situation is like this: I have a Composer package that has a dependency belonging to the same project. Sometimes I need to do some refactoring and make changes to both the package and the dependency. To do this, I might create a branch named `feature` in both the package and the dependency. While developing and testing, I need to have the same branch checked out for both. 

When I push the `feature` branches to my CI machine, it will check out the package and run `composer install` on it, which in turn checks out the dependency. In order to make the automated tests that run on the CI machine pass, the `composer install` must install the `feature` branch for both the package and the dependency.

This could be achieved by having Composer infer the version from the branch and use `self.version` as the version constraint for the dependency. However, using `self.version` implies that the dependency will _always_ have the same branch checked out as the parent package. This is not always desirable. For example, I might be working on a feature branch in the parent package while the dependency remains unchanged and needs to have a regular version tag checked out. So, I think I would like the version constraint of the package to read (example):

`self.version|2.1.0`

which would be interpreted by Composer as: "Install the version of the parent package or fall back to installing `2.1.0` in case that version is not available".

Does this make any sense? Any other options to make this scenario work?

Thanks a lot!

**Comment by alcohol** [comment]
I can see why this would be blocking for an automated process. But I am not sure that anything can be done about that. Your branch contains a change that you actually do not want. You added this change to "simplify" your development workflow. Unfortunately, you thereby complicated your build pipeline. There will always be tradeoffs to whatever solution you come up with. No workflow is perfect. I am not sure I can offer you any useful tips or advice on how to work around this.
