### ISSUE TITLE
Composer uninstall and Contextual menu

### ISSUE THREAD

**Issue by damiencot** [composer/composer#7718]
Hello,

I come to you regarding 2 problems that I met with composing. I wish to clarify that the 2nd problem can prevent me from solving the 1st problem.

1st: I wanted to uninstall Composer because I have not used it for several years. I proceed in this way, I went to Programs and Features and I uninstalled simply. But I noticed that the options in the right mouse click (context menu) were still present. I searched on the Composer GitHubt page, and I noticed some comment explaining that it had to be installed a second time while unchecking the shell option. I tried this method but it did not work, the context menu was still there. My question is, do you know a method to remove the option from the context menu?

2nd: By doing all these manipulations, I wanted to uninstall one before to try another method but I received this message "Windows can not find 'C:\Program Files (x86)\ComposerSetup\unins000.exe.' Check that you have entered the correct name and then try again" and I do not know how to restore this file or uninstall it completely. A solution ?

Thank you in advance if you read my post.

**Comment by johnstevenson** [comment]
If you uninstalled from the Control Panel successfully, then the context menu items should have been removed and likewise the Control Panel entry. Are they still there after a restart?

**Comment by alcohol** [comment]
@johnstevenson he did mention he installed it several years ago (not sure if exaggerating or true). So could it be the installer didn't quite work like that back then?

**Comment by johnstevenson** [comment]
@alcohol Yes, it is an old version that includes the Context Menus, which were dropped because their installation and removal required system provided APIs which were unreliable.

The uninstaller is version-specific though. It unloads the Context Menu DLL (if the system is playing nicely) and removes this and the composer stuff. Sometimes the system keeps the DLL loaded in File Explorer windows, even if it has been removed, so a restart is required.

This version (3.0) was available from December 2013 until it was replaced in March 2016.

**Comment by alcohol** [comment]
Thanks for the clarification :-) I think we can close this issue @damiencot ?

**Comment by damiencot** [comment]
I managed to fix my problem number 2, but is it normal that the ComposerSetup folder is always present even after a uninstall ?

As against the contextual menu, it is always present.

**Comment by johnstevenson** [comment]
> I managed to fix my problem number 2,

How you did this would be informative (likewise the Windows version )

> is it normal that the ComposerSetup folder is always present even after a uninstall ?

No. The uninstall process will remove it unless it is unable to (because it is "locked" in another program).
