### ISSUE TITLE
SSL Expire files.phpcomposer.com

### ISSUE THREAD

**Issue by bsormagec** [composer/composer#7724]
Hi, @Seldaek, after I installed 3 times all php modules retry i found a problem on your certificate can you please fix files.phpcomposer.com ssl problem ? 

For example "https://files.phpcomposer.com/files/Seldaek/monolog/fd8c787753b3a2ad11bc60c063cff1358a32a3b4.zip"

Thanks 👯‍♂️

**Comment by alcohol** [comment]
We do not own nor operate nor maintain files.phpcomposer.com

**Comment by bsormagec** [comment]
oke
