### ISSUE TITLE
Upgrading to a stable release is considered a "downgrade"?

### ISSUE THREAD

**Issue by mindplay-dk** [composer/composer#7728]
I've noticed recently, anytime I upgrade from an unstable release-branch (e.g. `3.0.0`) to a stable tag, the message in the console says it's *down*grading the package:

```
  - Downgrading kodus/session (3.0.0.x-dev a4077d2 => 3.0.0):  Checking out a4077d26e3
```

This thew me off and was quite confusing - I thought maybe I had tagged the wrong commit (an older commit) or something.

Why is going from an unstable pre-release to a tagged stable release considered a downgrade?

**Comment by stof** [comment]
I think it only compares the versions to decide between upgrade or downgrade in the message. And `3.0.0.x-dev` is considered a higher version than `3.0.0`

**Comment by alcohol** [comment]
> `3.0.0.x-dev` is considered a higher version than `3.0.0`

**Comment by mindplay-dk** [comment]
According to [clause #9 of the semver spec](https://semver.org/#spec-item-9):

> Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version.

I guess what has me confused is the `MAJOR.MINOR.PATCH.XXX` format, which I don't think is valid semver in the first place? The format is `MAJOR.MINOR.PATCH`, I don't see anything about a fourth version number in the spec?

This, combined with the fact that the `-` suffix semantically means "minus" in semver and is supposed to have a lower precedence, it's rather confusing to me.

Nobody else thinks that's strange? Maybe it's just me :-)

**Comment by alcohol** [comment]
Branches are not tags. `3.0.0.x-dev` is not a "tag" before `3.0.0`, it indicates it is ahead of `3.0.0`. This is not a semver thing, this is how Composer deals with branches.

**Comment by stof** [comment]
Semver only deals with releases, so branches are something that are out of its scope.

**Comment by sbuzonas** [comment]
The `.x-dev` suffix is essentially an alias to `.9999999@dev`
