### ISSUE TITLE
Cloning from cache takes longer

### ISSUE THREAD

**Issue by webmake** [composer/composer#7729]
Hello,

this is more question, than problem, but I have noticed, that having multiple `dev-master` dependencies, they increase `composer install` command time up to 3mins, while in theory counting only `Loading from cache` lines - it would be in total ~20s, and noticed that even small amount but it counts, +2s up to +15s from `dev-master`, ex.:
```
18:16:10 [0m[91m  - Installing phpdocumentor/type-resolver (0.4.0): [0m[91mLoading from cache[0m[91m
18:16:10 [0m[91m  - Installing phpdocumentor/reflection-docblock (4.3.0): [0m[91mLoading from cache
18:16:23 [0m[91m  - Installing internal/package (dev-master 0556e3e): [0m[91mCloning 0556e3ecbc from cache
18:16:23 [0m[91m  - Installing symfony/expression-language (v4.1.4): [0m[91mLoading from cache
```
`Loading from cache` it is done even at same second multiple rows. (ex. 13s per 1s)

Isn't possible after `fetchRefOrSyncMirror` command to do just copy recursive from cache [instead of](https://github.com/composer/composer/blob/master/src/Composer/Downloader/GitDownloader.php#L61)

here is other dependency, but still 1.5s it counts:
```
[15.3MB/0.59s] Executing command (CWD): git clone --no-checkout '/home/vagrant/.cache/composer/vcs/git-bitbucket.org-internal-package2.git/' '/project/vendor/internal/package2' --dissociate --reference '/home/vagrant/.cache/composer/vcs/git-bitbucket.org-internal-package2.git/' && cd '/project/vendor/internal/package2' && git remote set-url origin 'git@bitbucket.org:internal/package2.git' && git remote add composer 'git@bitbucket.org:internal/package2.git'
[15.3MB/2.09s] Executing command (/project/vendor/internal/package2): git branch -r
```

Is there any method to speed up, that I do not know apart tags?

**Comment by stof** [comment]
Well, by default, for dev versions, Composer install them from source (which allows you to have the git repo for them). There is a `--prefer-dist` option to use archives even for dev version (this can also be configured in the config)

**Comment by webmake** [comment]
It still executes it, same output, and time similar.

**Comment by webmake** [comment]
I will try to configure satis, I see `"skip-dev": true`, so will change to false, and I'll let you know

**Comment by webmake** [comment]
Yes, it was great speed up using `--prefer-dist`, but had to clean cache and composer.lock, that it would apear `"dist"` part with urls . Thanks
