### ISSUE TITLE
Composer 1.7.2 does not work in Ubuntu 18.04 and PHP 7.1

### ISSUE THREAD

**Issue by saidbakr** [composer/composer#7730]
I have installed composer using the downloaded installer script but when trying run `$ composer` I get the following dependency error from PHP:

```
php: error while loading shared libraries: libicui18n.so.55: cannot open shared object file: No such file or directory
```
My PHP version is: -`php -v`
```
PHP 7.1.23-2+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Oct 15 2018 11:37:26) ( NTS ) Copyright (c) 1997-2018 The PHP Group Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies with Zend OPcache v7.1.23-2+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```
However, `php composer.phar` works fine.

**Comment by staabm** [comment]
This error is not related to composer but your php binary and its extensions

**Comment by saidbakr** [comment]
@staabm but the installer should check these things before installation!

**Comment by staabm** [comment]
This error will occur whenever you run a php command on cli.
Its a low level setup problem on your end

**Comment by saidbakr** [comment]
@staabm  Is there any suggestion about the PHP, I installed it using:
```
sudo apt-get install php7.1 libapache2-mod-php7.1 php7.1-mcrypt php7.1-cli php7.1-xml php7.1-zip php7.1-mysql php7.1-gd php7.1-imagick php7.1-recode php7.1-tidy php7.1-xmlrpc
```
From ppa:ondrej/php repo

**Comment by stof** [comment]
note that the installer cannot check this either, as the installer is also written in PHP and so you would also get this error when running the installer.

**Comment by stof** [comment]
@saidbakr if `php composer.phar` works but `composer` does not, make sure that `/usr/bin/env php` resolves to the same runtime than `php`.

The composer shebang uses `/usr/bin/env php` which resolves the executable based on the PATH. `php` might be overriden by a shell alias you have.
If that's indeed the issue, make sure that the PHP executable in your PATH is the working one.

**Comment by saidbakr** [comment]
@stof I think this is true. Now I need to know how could I make `/usr/bin/env php` uses the correct php?
My $PATH output is :

bash: ~/.composer/vendor/bin:/home/said/bin:/home/said/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin: No such file or directory

**Comment by stof** [comment]
well, the first step is to identify what is each of the runtime you have.

run `which php` to see what `php` is in your shell. And then, try `sh -c "which php"` to see the result when running it in separate environment (when I tried it, the second command bypasses the alias I created for testing). this would allow you to identify where they come from.

**Comment by saidbakr** [comment]
Both `sh -c "which php"` and `which php` identically return the same output: `/usr/local/bin/php`

**Comment by saidbakr** [comment]
These are three commands outputs:
```
said@said:~$ whereis /usr/local/bin/php
php: /usr/bin/php7.1 /usr/bin/php /usr/lib/php /etc/php /usr/local/bin/php /usr/local/lib/php /usr/include/php /usr/local/php /usr/share/php7.1-json /usr/share/php7.1-common /usr/share/php7.2-common /usr/share/php7.1-recode /usr/share/php7.1-zip /usr/share/php7.2-bz2 /usr/share/php7.2-mbstring /usr/share/php7.1-readline /usr/share/php7.1-tidy /usr/share/php7.1-mcrypt /usr/share/php /usr/share/php7.1-mysql /usr/share/php7.1-gd /usr/share/php7.1-xml /usr/share/php7.1-opcache /usr/share/php7.2-curl /usr/share/php7.1-xmlrpc /usr/share/php7.1-mbstring /usr/share/man/man1/php.1.gz
said@said:~$ /usr/local/bin/php -v
/usr/local/bin/php: error while loading shared libraries: libmysqlclient.so.20: cannot open shared object file: No such file or directory
said@said:~$ /usr/bin/php -v
PHP 7.1.23-2+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Oct 15 2018 11:37:26) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.23-2+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
said@said:~$ 
```

**Comment by janmyszkier** [comment]
@stof I just checked this in ubuntu 18.04 and libicu55 package is not available for this release at all. Then, you should stop requiring it for composer (at least in 18.04+).

My guess is the OP should use the `apt-get install composer` and use older composer version made for this specific distro?
@saidbakr can you run
```
apt-get update && apt-get upgrade;
apt-get remove composer;
apt-get install composer;
apt-get install -f --fix-missing;
composer --version;
```
?
mine here is 
```
Composer version 1.7.2 2018-08-16 16:57:12
```
and works fine (installed with ubuntu repos as far as I remember).

**Comment by xabbuh** [comment]
Error messages like "error while loading shared libraries" are not caused by Composer, but are due to a misconfigured PHP installation (i.e. PHP was configured to load a specific shared library that is not installed). This already happens before Composer is executed at all.

**Comment by saidbakr** [comment]
@xabbuh I agree with you, but the installer should be able to check all of these stuff.

**Comment by saidbakr** [comment]
@janmyszkier I had done what you had regarded, I got composer version 1.6.3, but it does not have `self-update` command!

**Comment by oerdnj** [comment]
The system in question mixes PHP installed from source in /usr/local and PHP 7.1 installed from PPA. Just make your system clean of previous installations and you’ll be fine.
And always try to reproduce bug in clean system before you spend other people’s time to debug the issue for you.

**Comment by oerdnj** [comment]
If you have PHP in /usr/local/bin then your statement is simply not true.

Using some Docker recipe perhaps?
