### ISSUE TITLE
Composer behind a corporate proxy with windows authentication

### ISSUE THREAD

**Issue by gcrispyn** [composer/composer#7731]
Hello dear composer community,

I have a big problem. I try to use composer in my company wich have a corporate proxy with authentication with windows.

I can't specify the username and the password on the uri described on the HTTP(S)_PROXY variable (I try but the proxy disconnect me). 

I want to use a PAC file instead of but I don't know how to use this with the composer configuration.

Is there a way to auto-detect proxy configuration (like PHPstorm) using an uri through PAC file?

Thank you in advance

**Comment by gcrispyn** [comment]
Problem solved :

It was a password problem. Don't forget to rawurlencode your password !!

**Comment by gcrispyn** [comment]
Problem still exists. Rawurlencode is not enough. I have a password with special characters like 'ç' and 'é'. Because of this, the password is not encoded well and the connection is broken.

Any suggestion?

**Comment by Seldaek** [comment]
rawurlencode might need you to make sure you use the correct encoding too, as the proxy expects it?
