### ISSUE TITLE
Feature request: add option to set custom command for linking

### ISSUE THREAD

**Issue by cprn** [composer/composer#7733]
My `composer.json`:

```json
{
    "name": "foo/myProject",
    "type": "project",
    "description": "example of local vendor linking",
    "repositories": [
        {
            "type": "path",
            "url": "../*"
        }
    ],
    "require": {
        "foo/myLocalBundle": "^1"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking HTTP proxy: OK
Checking HTTP proxy support for request_fulluri: OK
Checking HTTPS proxy support for request_fulluri: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Composer version: 1.6.3
PHP version: 7.2.11-2+ubuntu18.04.1+deb.sury.org+1
PHP binary path: /usr/bin/php7.2
```

When I run this command:

```
composer install
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing foo/mylocalbundle (1.0): Symlinking from ../myLocalBundle
Writing lock file
Generating autoload files
```

And I expected this to happen:
This is a long shot - I understand perfectly well I can just use `repositories.options.symlink=false` in json or `COMPOSER_MIRROR_PATH_REPOS=1` in environment as a workaround and there will be no hard feelings for just closing this without response. Above said... It would be nice to have more control over the way dependencies are linked, e.g. to have them mounted (`mount --bind original new`) instead of linked (`ln -s original new`) as a way to work around the issue of 3rd party tools not being able to traverse symlinks but still be able to avoid redundancy in local repository.

**Comment by alcohol** [comment]
PRs are welcome.

**Comment by sbuzonas** [comment]
See also #5256

**Comment by cprn** [comment]
Ah, thank you, I failed to find it indeed. Good to know I'm not the only one.

I'm currently trying to solve the issue with https://github.com/felixfbecker/php-language-server/issues/586 but if I fail there I'll try to prepare a PR here, therefore please, don't close this ticket yet.

**Comment by Seldaek** [comment]
Closing as I don't think we will ever do anything here.
