### ISSUE TITLE
RFC/Feature request: handling HHVM without PHP support in HHVM

### ISSUE THREAD

**Issue by fredemmott** [composer/composer#7734]
HHVM is [planning to drop support for PHP](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html); this will mean that it will eventually stop being possible to execute Composer using HHVM.

This leaves a few options:
1. encourage the Hack community to use a different package manager (currently Yarn and Esy are at the top of the list). This might also involve extending another package manager to support Packagist as a migration strategy.
2. use PHP to execute Composer; modify composer to detect what version of HHVM is installed on the system (e.g. `hhvm --version`), even if it's not being used to execute Composer
3. use PHP to execute Composer; modify composer to ignore 'hhvm' platform dependencies
4. use PHP to execute Composer; ask the Hack community to remove 'hhvm' platform dependencies from their composer.json files

What's best out of 2-4 depend on (a) are there any aspirations for using composer/packagist for multiple languages? i.e. would this be a one-off hack for HHVM, or possibly a basis for more flexibility in the future? (b) how much tech debt in composer would be required (with 4 presumably being 'none'), and what's acceptable to you?

**Comment by er1z** [comment]
I'd like to see POSIX-perception: „do one job and do it well”.

**Comment by alcohol** [comment]
Composer only supports Hack because it was virtually a drop in replacement for PHP at the beginning. If Hack moves away from supporting PHP, then so be it. But that does not really affect us. Our focus is, and has always been, the PHP community :-)

**Comment by fredemmott** [comment]
I don't disagree - but just to be clear, not doing anything special in composer means (1) long-term, and (4) temporarily - and (4) does potentially have a slight negative effect on the PHP community

**Comment by fredemmott** [comment]
If the goal is to focus purely on PHP, my ideal would be (1) and (2), with the goal of removing (2) from composer in 6-18 months and reverting to being a pure PHP package manager.

**Comment by Seldaek** [comment]
2) sounds reasonable to me if it can be done without too much madness and burden on our end. 

1) is kind of up to you. I guess either with yarn or composer you won't be running the package manager using hhvm anyway.. As for "abusing" packagist.org to list packages that aren't PHP at all, it does not sound ideal to me, but I suppose this is the case already so probably fine.

**Comment by Seldaek** [comment]
Also note that there is a (5) which is to use https://getcomposer.org/doc/06-config.md#platform to configure which hhvm version you have in your composer.json, that should already work as a (2) variant without any changes to composer.

**Comment by fredemmott** [comment]
(1) The advantage of Yarn or Esy over Composer isn't the language/ecosystem they're centered around - it's that supporting multiple languages is a goal for them (OCaml and C++ being current works in progress, with live stuff in the npm repo). I'm guessing it would be better for both Composer and Hack for Hack to be a plugin in a multi-language system than a special case in a PHP system :)

**Comment by fredemmott** [comment]
An alternative, more flexible solution:

we create a file `/etc/composer/platform.d/hhvm` containing the version number (with similar paths such as `/usr/local/etc/` on macOS homebrew systems). Composer would treat any filename in those directories as a package name, with the contents being the version. No handling of HHVM.

**Comment by fredemmott** [comment]
Tracking issues needed for us to stop use composer in https://github.com/yarnpkg/yarn/issues/7001
