### ISSUE TITLE
RFC/Feature Request: Yarn like workspaces with composer

### ISSUE THREAD

**Issue by codeliner** [composer/composer#7742]
Yarn has a neat feature called "workspaces", see yarn docs: https://yarnpkg.com/lang/en/docs/workspaces/

I thought about something similar for PHP backends using composer. And with a workaround it already works with one exception. I'll get to that in a minute. First let me describe the expected behavior.

Let's say we want to develop a modular application. You can think of ZF2 modules or Sf bundles.
Instead of modules separated by technical concern we want to apply DDD and want to have a module for each bounded context. So we have a module **A** and a module **B** representing our bounded contexts A and B. 

Due to the fact that A and B are part of the same application you put every dependency, autoloading definitions etc. in a single `composer.json`.

**It would be nice if each module can define its own dependencies and autoloading definition in a module specific composer.json.**

*Why is it useful?*
A bounded context should be treated as an independent unit. It has a clear boundary and a module specific composer.json would underline this concept. Moreover, you'd have fine-grained control of module specific dependencies because you always know which of your modules requires a specific third-party package. This is especially useful if you want to turn modules into separate microservices later. Split a single module from the rest of the system is easier due to strong boundaries, separated namespaces and a good overview of module dependencies.

*How can this set up be achieved with current composer features?*

Let's assume this simple structure:
```
MyApp
|_ ModuleA
   |_ src                   <-- Namespace: MyApp\ModuleA
   |_ tests                <-- Namespace: MyApp\ModuleATest
   |_ composer.json    <-- module A composer.json, defines autolaoding and module dependencies
|_ ModuleB
   |_ src                   <-- Namespace: MyApp\ModuleB
   |_ tests                <-- Namespace: MyApp\ModuleBTest
   |_ composer.json    <-- module B composer.json, defines autolaoding and module dependencies
|_ composer.json       <-- Root composer.json, requires ModuleA and ModuleB as local packages
|_ vendor
    |_ ModuleA            <-- Symlink to ModuleA due to local package requirement
    |_ ModuleB            <-- Symlink to ModuleB due to local package requirement
    |_ ModuleADep      <-- A dependency defined in A composer.json
    |_ ModuleBDep      <-- B dependency defined in B composer.json
    |_ ABDep               <-- Dependency defined in both module composer.json files
    |_ autoload.php      <-- Can autoload module namespaces 
```

As I said this works already with a root composer.json like this:

```json
{
   "repositories": [
        {
            "type": "path",
            "url": "ModuleA"
        },
         {
            "type": "path",
            "url": "ModuleB"
        }
    ],
     "require": {
        "myapp/module-a": "*",
        "myapp/module-b": "*"
    }
}
```

Anyway, two things bother me:

1) Symlinking modules into vendor dir is not neccessary because the modules are part of the application
2) Module specific **autoload-dev** configuration is ignored because the local packages are treated like third-party packages. Hence, module tests don't work because the autoloader simply cannot find test classes. That said, at least all test namespaces need to be defined in the root composer.json and that makes the concept flawed ...

Yarn workspaces solve this problem by introducing an explicit module concept into dependency management. Modules (or workspaces) define their own package dependencies in a workspace specific package.json and in the root package.json those workspaces are configured explicitly. Then you can run `yarn install` on the app root and it merges all package.json files - creating an application wide dependency tree, resolve the best version for each package and detect conflicts.

*How can composer solve the issue?*

I'd say we need a workspace concept similar to one developed for yarn. This would solve the two issues listed above caused by the current workaround. A simple "workspace" key in the root composer.json would be sufficient. It could be as simple as the current local package configuration shown above.
Composer would read the workspace composer.json files, merge dependencies and add the autoload mapping (also autoload-dev) to the autoloader.

What do you think?

Combined with a middleware dispatcher like Zend Expressive this is a really powerful concept. You can use a modular monolithic approach in early stages of a project but at any given point in time you have the option to cut out one or more modules and deploy them separately. I've described this technique in more details [here](https://proophsoftware.github.io/fee-office/intro/module_system.html#1-3)

**Comment by alcohol** [comment]
There are already some plugins available that facilitate similar behavior, the most popular being https://github.com/wikimedia/composer-merge-plugin

I do not think we want to support this from Composer's perspective. It tailors to a specific workflow that is not really used by the general target audience. It would require quite some work to implement properly and then also needs to be maintained in future releases. Add to that the fact that there are other ways to achieve a similar work-flow, I feel the cons outweigh the pros significantly.

**Comment by naderman** [comment]
I think you've already outlined that path repositories solve this particular problem quite well.

A module that is independent should be able to run the tests by itself, so the typical test setup in a scenario like this is to run composer install and tests in each module independently. It seems like the entirety of your concept boils down to wanting to run tests across all modules instead of individually, and that really seems like a tiny very avoidable problem? I'm guess I'm still missing the point of all of this?

**Comment by codeliner** [comment]
> A module that is independent should be able to run the tests by itself, so the typical test setup in a scenario like this is to run composer install and tests in each module independently.

If the module is comparable to a library I'd agree. Business logic put into different modules is bit different.
The application layer is the same for all modules and can inject global dependencies into modules. Let's say all modules should use an application wide logger. They work against PS-3 logger interface and the application injects monolog into each module.
Therefor, I need the application autoloader in place during tests and not a module specific autoloader.
I really want to merge autoloading definitions and dependencies of each module into the application. Just like yarn does with workspaces.

And again the current solution is a workaround:

> Symlinking modules into vendor dir is not neccessary because the modules are part of the application

A workspace is not a local library. It's part of the application and should not be treated like a vendor package. That's the point I try to make here.

**Comment by codeliner** [comment]
composer-merge-plugin looks good. I'll use it and close this issue. I still think that a workspace concept could be nice core feature, though. 

Anyway, thx for your time and the hint.
