### ISSUE TITLE
Local path repository conflicts with Packagist repository

### ISSUE THREAD

**Issue by BitOne** [composer/composer#7746]
My main `composer.json` in my directory:

```json
{
    "name": "akeneo/pim-enterprise-dev",
    "require": {
        "akeneo/pim-community-dev": "3.0.x-dev@dev"
    },
    "require-dev": {
        "phpunit/phpunit": "6.5.3"
    },
    "minimum-stability": "stable",
    "repositories": {
       "pim-community-dev": {
           "type": "path",
           "url": "../ce/"
       }
   }
}
```

And the secondary `composer.json` file in the `../ce/` directory:
```json
{
    "name": "akeneo/pim-community-dev",
    "require": {
        "doctrine/orm": "2.5.6"
    },
    "minimum-stability": "stable",
    "extra": {
        "branch-alias": {
            "dev-master": "3.0.x-dev"
        }
   }
}
```  

Note: there are no other files or folders in the directories where the `composer.json` files are located.

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.akeneo/pim-community-dev : exact version constraints (3.0.x-dev@dev) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.7.2
PHP version: 7.2.11
PHP binary path: /usr/bin/php7.2
```

When I run this command:

```
composer install
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - akeneo/pim-community-dev 3.0.x-dev requires doctrine/orm 2.5.6 -> satisfiable by doctrine/orm[v2.5.6].
    - akeneo/pim-community-dev 3.0.x-dev requires doctrine/orm 2.5.6 -> satisfiable by doctrine/orm[v2.5.6].
    - Conclusion: don't install doctrine/orm v2.5.6
    - Installation request for akeneo/pim-community-dev 3.0.x-dev@dev -> satisfiable by akeneo/pim-community-dev[3.0.x-dev].
```

And I expected this to happen: installation without error and using `../ce/` as the `akeneo/pim-community-dev` package.

Some interesting behaviors:
 - if I remove the `repositories` section in the main `composer.json` file, the installation works well
 - if I remove `phpunit/phpunit` from the `require-dev` of the main composer.json file, the installation works well
 - if I remove `doctrine/orm` from the `require` of the secondary composer.json file, the installation works well.

Thanks a lot for looking at this issue!

If you need me to do more tests, I will be happy to do them.

**Comment by alcohol** [comment]
Can you run

```
composer why-not doctrine/orm 2.5.6
```

**Comment by alcohol** [comment]
Also I would change the requirement constraint for `akeneo/pim-community-dev` to `dev-master` if I were you. That is the recommended constraint for path repositories.

**Comment by BitOne** [comment]
Hey @alcohol ,

Thanks for answering!

Unfortunately, the composer diagnostic commands will not work as they need to have the vendor already installed. So here is the output:
```
$ composer why-not doctrine/orm 2.5.6

                                                         
  [InvalidArgumentException]                             
  Could not find package "doctrine/orm" in your project  
                                                         

prohibits [-r|--recursive] [-t|--tree] [--] <package> [<constraint>
```

As per your suggestion, I've changed as well the `pim-community-dev` requirement to `dev-master`, but I got the same error:
```
$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - akeneo/pim-community-dev dev-master requires doctrine/orm 2.5.6 -> satisfiable by doctrine/orm[v2.5.6].
    - akeneo/pim-community-dev dev-master requires doctrine/orm 2.5.6 -> satisfiable by doctrine/orm[v2.5.6].
    - Conclusion: don't install doctrine/orm v2.5.6
    - Installation request for akeneo/pim-community-dev dev-master@dev -> satisfiable by akeneo/pim-community-dev[dev-master].
```

**Comment by alcohol** [comment]
I don't really know how to help you any further with this since I do not have a reproducible scenario. Can you share/create a public reproducible scenario?

**Comment by BitOne** [comment]
Hi @alcohol,

It wasn't clear in the original issue, but there's everything to reproduce the problem ;)

Here are the steps:
 - create two subdirectories inside a directory: `ee` and `ce`
 - copy the first (main) `composer.json` file from the issue above inside the `ee` directory
 - copy the second (secondary) `composer.json` in the `ce` directory
 - go to the `ee` directory
 - from it, launch `composer install`

=> This should reproduce the problem.

Thanks again for taking the time!

**Comment by alcohol** [comment]
So I tried a simple scenario, and could not reproduce it:

```
rob@galaga /tmp/composer $ cat foo/composer.json 
{
    "name": "foo/foo",
    "require": {
        "foo/bar": "dev-master"
    },
    "require-dev": {
        "phpunit/phpunit": "6.5.3"
    },
    "minimum-stability": "stable",
    "repositories": [
       { "type": "path", "url": "../bar/" }
   ]
}
rob@galaga /tmp/composer $ cat bar/composer.json 
{
    "name": "foo/bar",
    "require": {
        "doctrine/orm": "2.5.6"
    },
    "minimum-stability": "stable"
}
rob@galaga /tmp/composer $ composer install --no-suggest -d foo
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 41 installs, 0 updates, 0 removals
  - Installing psr/log (1.0.2): Loading from cache
  - <snipped>
  - Installing phpunit/phpunit (6.5.3): Loading from cache
Writing lock file
Generating autoload files
```

**Comment by alcohol** [comment]
Yeah I see what is wrong. You have to set your constraint to `"*"` to make sure the local repository will be given priority over the existing packagist version.

**Comment by BitOne** [comment]
Hey @alcohol ,

I tried again today, with the original files, and now everything works properly. I cannot reproduce the installation fail anymore. I don't know if something has changed on packagist side, or on one of the dependencies I was using.

Thanks again for the time spent on this subject. If the problem arises again, I will follow your advice and use the `"*"` constraint for the local repository.

**Comment by alcohol** [comment]
Weird.. glad to hear things worked out in the end though.
