### ISSUE TITLE
Unexpected behaviour for VCS repository

### ISSUE THREAD

**Issue by alcohol** [composer/composer#7747]
When defining a custom VCS repository, the package name is determined by the root identifier (often the `master` branch). When scanning tags of said repository, we do not verify if the `composer.json` of each tag contains the same package name.

I know this scenario is unlikely to occur; but I actually had someone in my team run into this (by mistake).

Short (simplified) description:
- Master branch was name `foo/bar`.
- They were working on a branch `2.x`, where they changed the name to `foo/baz` (not sure why, irrelevant).
- They were tagging `2.x.x` releases from the `2.x` branch for a while which Composer gladly picked up as new versions for `foo/bar`, but once they merged the `2.x` branch into `master`, everything broke.

This of course was a mistake on the user's end, but it seems like we could guard against this by rejecting tags with `composer.json` schemas that do not contain the same package name as the root identifier.

**Comment by Seldaek** [comment]
What do you mean by "everything broke"? AFAIK packagist and I believe composer too will ignore the name entirely except for in the default branch.

**Comment by sbuzonas** [comment]
The behavior was slightly modified in #7756 

My thought in this [comment](https://github.com/composer/composer/pull/7756#discussion_r229167742) was that weird things would happen if the package name changed.

**Comment by Seldaek** [comment]
Hmm in a composer vcs repo maybe.. on packagist though the name *must* be present when submitting and then we just keep that forever.

**Comment by Seldaek** [comment]
Don't think this is fixable actually, as the name must be able to be different in tags otherwise you can never rename a package without re-tagging everything.
