### ISSUE TITLE
The composer update <repository-name> support

### ISSUE THREAD

**Issue by mcspronko** [composer/composer#7749]
I searched for possible pull requests or known issues in this repository to find if someone has raised the question about single repository update support.

The idea is to provide a repository name when running the "composer update" command and update only the given repository. As a result, the composer.lock file will only have a single update rather than all dependencies.

I am happy to discuss it.

**Comment by stof** [comment]
composer does not update repositories, it updates packages. And partial updates are already supported since years

**Comment by mcspronko** [comment]
@stof I mean packages :).

I tried to use composer update vendor/package with "-vv" option and composer still goes and reads through absolutely all packages/repositories to get composer.json file. Worth optimizing?

**Comment by stof** [comment]
yes, it is an optimization opportunity known since a long time, but nobody implemented it yet: https://github.com/composer/composer/issues/3672 (this is scheduled to be part of the big refactoring of the solver for 2.x though)

**Comment by stof** [comment]
note that reading repositories cannot be avoided (as that's necessary to know which packages are inside each). But when dealing with a composer repository (for instance packagist), Composer does not read the whole repository, so this optimization would allow reading less from it.

**Comment by mcspronko** [comment]
Thanks, @stof for the detailed answer and the link to the ticket. This is probably all I wanted to know about partial updates. It will be great to have the improvement implemented as partial still takes a good portion of the time.
