### ISSUE TITLE
"configured cafile ... was not valid or could not be read"

### ISSUE THREAD

**Issue by LPloganvoss** [composer/composer#7757]
"The Composer installer script was not successful [exit code 1].

Script Output:
The configured cafile (//FS01-AZ.az.local/profiles$/MY_NAME/AppData/Roaming/Composer\cacert.pem) was not valid or could not be read."

I'm thinking it may because my work computer is on an active directory and there isn't much I can do about that, but is there any way I can point the installer to the cafile I created with open SSL? I also tried installing programmatically through the command line, and there doesn't seem to be anywhere to point to where my generated cafile is located.

**Comment by johnstevenson** [comment]
Curious, because Composer provides its own cacert.pem and writes it to `APPDATA\Composer`. Could you please supply an install log as per https://github.com/composer/windows-setup/issues/new

**Comment by LPloganvoss** [comment]
[Setup Log 2018-10-30 #003.txt](https://github.com/composer/composer/files/2530001/Setup.Log.2018-10-30.003.txt)

**Comment by johnstevenson** [comment]
Thanks for that. It looks like a bug in the Composer installer script that changes the `\\` prefix of your UNC share path.

Could you please try with this Composer-Setup version: 
[Composer-Setup.4.9.1.exe.zip](https://github.com/composer/composer/files/2530545/Composer-Setup.4.9.1.exe.zip)

**Comment by LPloganvoss** [comment]
Hmm, it looks like the same error is occuring.

**Comment by LPloganvoss** [comment]
[Setup Log 2018-10-30 #008.txt](https://github.com/composer/composer/files/2531023/Setup.Log.2018-10-30.008.txt)

**Comment by johnstevenson** [comment]
Well at least it is not changing the UNC path now! What is odd is that the installer succeeds in writing the cacert.pem to `AppData\Roaming\Composer` (otherwise you would have seen an ealier error) but is unable to read it, apparently.

You could manually download the php install script and run it with `--cafile=...` , but that won't help later when Composer tries to use `AppData\Roaming\Composer`

**Comment by LPloganvoss** [comment]
It's weird, do you think it has anything to do with the line where it says "Registering: Add to User path"? That's the first instance of the active directory being included in anything. Everything else has just been using my local directories and C drive

**Comment by johnstevenson** [comment]
That is your local file system, not the UNC share.

**Comment by staabm** [comment]
Should composer ship with https://github.com/paragonie/certainty so it doesnt depend on a properly configured and up2date cabundle?

**Comment by LPloganvoss** [comment]
Oh okay, my bad. I ran it again with powershell in the UNC path \\FS01-LP.lp.local\profiles$\logan.voss\AppData

php -r "var_dump(is_re
adable('\\FS01-LP.lp.local\profiles$\logan.voss\AppData\Roaming'));"

and returned false this time

**Comment by johnstevenson** [comment]
Please try that with a specific file on that path, as `is_readable` is for a file (and may return true for a directory).

**Comment by LPloganvoss** [comment]
Okay, tried
```
php -r "var_
dump(is_readable('\\FS01-LP.lp.local\profiles$\logan.voss\AppData\Roaming\Greenshot\Greenshot.ini'));"
```
and returned false

**Comment by LPloganvoss** [comment]
Okay I created a text file and tried
php -r "var_dump(is_readable('
\\FS01-LP.lp.local\profiles$\logan.voss\AppData\Roaming\filename.txt'));"
and returned false

**Comment by johnstevenson** [comment]
```
php -r "var_dump(is_readable('\\\\FS01-LP.lp.local\\profiles$\\logan.voss\\AppData\\Roaming\\filename.txt'));"
```

**Comment by johnstevenson** [comment]
I think this might be a specific Active Directory issue, because if I set my %APPDATA% environment variable to a local UNC share (for example `\\COMPUTER\Users\John\folder`) and install composer manually from the command line, then it installs correctly - with the cacert.pem written to a Composer directory that is created in the UNC share path.

**Comment by LPloganvoss** [comment]
Ran your command, false again.
I agree I definitely think this is an active directory thing, I tried changing my environment variable as well to either a different UNC path and a local path and nothing is working.

**Comment by bzqadmin** [comment]
just uninstall composer   and delete all composer folders in AppData/local    and  AppData/roaming ,then reinstall composer,done.
