### ISSUE TITLE
Dispatch "post-package-update" event after updating composer.lock write

### ISSUE THREAD

**Issue by mbrodala** [composer/composer#7765]
At the moment the `post-package-update` event is dispatched **before** updating the `composer.lock` file:

https://github.com/composer/composer/blob/ff59bbd/src/Composer/Installer.php#L613-L620

I would like to suggest to dispatch the event **after** updating the `composer.lock` file instead. This allows event listeners to assume a clean and complete package state.

Background: I would like to rewrite an existing Shell helper script which automatically performs all pending package updates one by one and does a Git commit after each single update. This allows for easy bisect and better revert if necessary. The users then only need to perform a `composer up` and rest assured that there's a Git commit for every single update performed. However, if the `composer.lock` was not written at the time my `post-package-update` listener is called, I cannot commit the package update.

**Comment by alcohol** [comment]
I am pretty sure that we only update the composer.lock once after we installed all updates, so I am not sure how changing the timing would help you as your commits will all contain the same composer.lock file. Or did I misunderstand the purpose/goal?

**Comment by alcohol** [comment]
Hmm, seems I was wrong :thinking:.

**Comment by sbuzonas** [comment]
I think it makes sense, but moving it would cause things to break that may have tweaked the lock before it was written.

**Comment by sbuzonas** [comment]
There isn't a way to get it from the event, but I normally get it in the plugin activation from the repository manager.

**Comment by mbrodala** [comment]
Sounds like this could work, I'll have a look.

**Comment by mbrodala** [comment]
Just FYI: I recently noticed that it is actually impossible to implement what I had in mind. Handlers for the `post-package-update` event can update the local repo at most but not update the lock file. This is done by the `Installer` once all package updates have been performed and is basically impossible to replicate.
