### ISSUE TITLE
SSL client certificate support

### ISSUE THREAD

**Issue by sandermarechal** [composer/composer#777]
I would like to a private repository with restricted access. I don't want to use HTTP Basic auth because I would need to add the username/password to all my `composer.json` files. I am thinking about putting an SSL certificate on the server that serves my private repository, but at the moment you cannot supply an SSL client certificate to Composer. Something like this would be fantastic:

```
{
    "repositories": [
        {
            "type": "composer",
            "url": "http://example.org",
            "ssl-cert": "/path/to/client.cert"
        }
    ],
    "require": {
       "example/package": "*"
    }
}
```

I'd be happy to write a PR for this, if there is interest in such a feature.

**Comment by Seldaek** [comment]
AFAIK this is possible via the repository options key, see the second example at https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md#security
