### ISSUE TITLE
Allow public projects on GitLab/GitHub to be cloned with SSH, rather than only HTTPS, URLs

### ISSUE THREAD

**Issue by mlncn** [composer/composer#7771]
Thank you to @Seldaek, @ianlet, @alcohol, @alecpl, and everyone whose worked to make composer work as well as it now does for a multi-repository public open source free software project on GitLab.

The workflow we're trying to achieve for our project is that when contributing developers `composer install` with our "[developer template](https://gitlab.com/drutopia/drutopia_dev_template) they will get clones of all projects ready to immediately branch and contribute to.  (Note that GitLab's merge request, rather than fork and pull request, functionality makes this feasible.)  All we need to do is give people *access* to use the SSH clone URL, but we don't need to give them any commands that change per repository (and so would have to be tailored to the repository)— just `git branch my-fix-or-feature` and they're already set to contribute!

Having read that `type: vcs` might be doing magic that we can avoid with `type: git` i have tried that but we're still getting the same results.

It seems that, as @aadmathijssen noted, it the fix in https://github.com/composer/composer/pull/5591 may have been a bit overzealous and taken away this option.  Or i just may not have found the trick to communicating to composer to stick with the SSH URL.

My `composer.json`:

```json
{
    "name": "drutopia/drutopia_dev_template",
    "description": "Template for developing composer-based Drutopia projects.",
    "type": "project",
    "license": "GPL-2.0-or-later",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "composer/installers": "^1.0",
        "drupal-composer/drupal-scaffold": "^2.0.0",
        "cweagans/composer-patches": "^1.0",
        "drutopia/drutopia": "dev-8.x-1.x",
        "drupal/drutopia_action": "dev-8.x-1.x as 1.x-dev",
        "drupal/core": "^8.6.2",
        "drush/drush": "^9.0"
    },
    "repositories": {
        "drupal": {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        },
        "drupal/drutopia": {
            "type": "git",
            "url": "git@gitlab.com:drutopia/drutopia.git"
        },
        "drupal/drutopia_action": {
            "type": "git",
            "url": "git@gitlab.com:drutopia/drutopia_action.git"
        }
    },
    "extra": {
        "installer-paths": {
            "web/core": [
                "drupal/core"
            ],
            "web/modules/contrib/{$name}": [
                "type:drupal-module"
            ],
            "web/profiles/contrib/{$name}": [
                "type:drupal-profile"
            ],
            "web/themes/contrib/{$name}": [
                "type:drupal-theme"
            ],
            "drush/contrib/{$name}": [
                "type:drupal-drush"
            ]
        },
        "enable-patching": true
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.7.3
PHP version: 7.2.10
PHP binary path: /usr/bin/php7.2
```

When I run this command:

```
composer update --prefer-source
```

I get all the right output *except* in the drutopia_action project (in `web/modules/contrib/drutopia_action/.git/config) instead of using the SSH URL i provided (`git@gitlab.com:drutopia/drutopia_action.git`) it has been switched to an HTTPS URL (`https://gitlab.com/drutopia/drutopia_action.git`) for both the 'origin' and 'composer' remotes.

**Comment by Seldaek** [comment]
Have you tried deleting the vendor dir and composer.lock after you changed the type from `vcs` to `git`? Because if not it probably still cloned the old one from the lock file with the https URL it had in there?

If you set it to git I don't see how it could possibly switch to a https URL.

Regardless of that.. Would you mind explaining *why* it matters so much what URL you end up with? Is it then impossible to `git push` to the https URL?

I think the main reason we did this change was that gitlab didn't let you git clone an SSH URL without having ssh access configured for gitlab, but I might be wrong there. Anyway I suppose we could add an option to the GitLabDriver to make it possible to force it to use the SSH URLs. I'd still like to understand the use case first though.

**Comment by mlncn** [comment]
Ack, good grief i had a "composer nuke" script that wasn't deleting the composer.lock file when i thought it was.  Eep.

Completely contrary to what i wrote above, `type: git` when overriding the repository in our base `composer.json` here **does** work, beautifully.  (And it works whether or not `--prefer-source` is used.)

Thank you, and yes— the use case is precisely that people can then `git push`.  So the only developer documentation we need is to tell people to git branch, and maybe join on an organization level at GitLab to have access to all the repositories, and we *don't* have to explain how to find the SSH (git@gitlab etc.) URL for each project.

Thanks again, apologies for all the noise!
