### ISSUE TITLE
Bitbucket - OAuth Authentication failed on update

### ISSUE THREAD

**Issue by runner78** [composer/composer#7774]
I using private repository in my composer project using OAuth. 
Using the update command:

```
Update failed (Failed to execute git remote set-url composer 'https://x-token-auth:***@bitbucket.org/<repository-path>' && git rev-parse --quiet --verify '019819fe6b6d33ce98f02c7bdad9a74891b3e343^{commit}' || (git fetch composer && git fetch --tags composer)

remote: Invalid username or password
fatal: Authentication failed for 'https://x-token-auth:***@bitbucket.org/<repository-path>/'
)
    Would you like to try reinstalling the package instead [yes]? yes
  - Removing <package> (dev-develop)
  - Installing <package> (dev-develop 019819f): Cloning 019819fe6b from cache
    019819fe6b6d33ce98f02c7bdad9a74891b3e343 is gone (history was rewritten?)
    Failed to download <package> from source: Failed to execute git checkout '019819fe6b6d33ce98f02c7bdad9a74891b3e343' -- && git reset --hard '019819fe6b6d33ce98f02c7bdad9a74891b3e343' --

fatal: reference is not a tree: 019819fe6b6d33ce98f02c7bdad9a74891b3e343

    Now trying to download from dist
  - Installing <package> (dev-develop 019819f): Downloading (connecting...)
                                                
  [Composer\Downloader\TransportException]      
  Could not authenticate against bitbucket.org  
```

But if i delete the cache in the .composer folder, it works for this package, but fail again for the next private repository.

My Workflow now:
- composer update: fail for first package
- delete cache
- composer update: first success, second fail
- delete cache
- composer update: second success, third fail
- delete cache
- ...

Composer versions: 1.7.2 and 1.7.3
PHP: 7.1 and 7.2

Edit:
The second attempt succeeds only if i try to reinstall after failing.

**Comment by jerturowetz** [comment]
I'm also having issues with BitbucketOauth on latest version of composer & latest satis on both Win10 and Ubuntu 16.04.4. Getting a _Invalid OAuth consumer provided_ for thrice checked and updated active consumer secrets/keys. Did you have any sucess debugging your issue @runner78 ?

**Comment by jerturowetz** [comment]
@runner78 my issue was with Bitbucket, not composer in the end, they updated some elements of OAuth (i think preparing for 2019 changes) and it broke the everything (error messages were pretty unclear).

Try adjusting your Bitbucket OAuth settings to match mine:

- Make sure you have filled out the _**Callback URL**_ field (can be anything)
- Make sure _**This is a private consumer**_ is checked
- Under _Permissions >> Repositories_ make sure _**read**_ is checked
- ALSO, under _Permissions >> Projects_ make sure _**read**_ is checked

I have opened a ticket to find out why this occurred out of the blue and will try to follow up here even after issue is closed. I hope this resolves your issue as well.

**Comment by runner78** [comment]
The only thing I did not have was the Permissions >> Projects.
Strange: with one Project it works after the settings change, but with an other Project the same problem, both are on the same Server with the same PHP and both are TYPO3 Projects in composer-mode. The difference is only the TYPO3 version.

A cache delete is not always needed, sometime it works with simple retrys.

**Comment by jerturowetz** [comment]
Just guessing, but I suspect that also has to do with Bitbucket's new rules. What's your error message on these other projects is it still rejecting the key or something else ?

**Comment by jerturowetz** [comment]
**UPDATE from Bitbucket support**

> Our developer did some research on this. It turns out that `client_credentials` flow was used, which would make sense for this scenario. The questionable part is that this should have never worked without _This is a private consumer_ being checked. Without it, this would invalidate the `client_credentials` flow as it would indicate that the key/secret would be public if used in a desktop (SourceTree, for instance) or mobile web app. If someone were to look into SourceTree's binaries (without the private consumer check) they could extract your key/secret.

So basically, it really shouldn't have worked before and some internal Bitbucket update likely "fixed" what must have been us accessing the repos in an insecure way :P

I'm gonna bet the rest of the bitbucket related issues have something to do with these API updates and are likely not composer issues.

**Comment by rubenrua** [comment]
> Just guessing, but I suspect that also has to do with Bitbucket's new rules. @rubenrua what's your error message on these other projects is it still rejecting the key or something else ?

Sorry. I don't have any relation with this issue.

ping @runner78

**Comment by Deltachaos** [comment]
I have the same problem and i have made sure that the settings in bitbucket are like @jerturowetz described it.

It works with composer version 1.6.5 but not starting with version 1.7.3.

**Comment by runner78** [comment]
The errors occurs only on updating, if i install an package it's work successful.

**Comment by design1online** [comment]
This took me forever to figure out! Gah, I hope this saves someone else a whole lot of trouble. First you need to create a personal access token in github here: https://github.com/settings/tokens and make sure you check the repo checkbox at the top to give it all the repo permissions.

<img width="1025" alt="Screen Shot 2019-05-15 at 10 06 40 PM" src="https://user-images.githubusercontent.com/5115671/57821261-e1795580-775d-11e9-9422-09bca1339a49.png">

Then you need to tell composer to use your token configuration before the installation step. Basically your pipeline code ends up looking something like this:

```
# install and configure composer
 - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
- composer config github-oauth.github.com {GITHUB_TOKEN}
- composer install --no-interaction --no-progress --prefer-dist```

**Comment by runner78** [comment]
> This took me forever to figure out! Gah, I hope this saves someone else a whole lot of trouble. First you need to create a personal access token in github here: https://github.com/settings/tokens and make sure you check the repo checkbox at the top to give it all the repo permissions.
> 
> Then you need to tell composer to use your token configuration before the installation step. Basically your pipeline code ends up looking something like this:
> 
> ```
> # install and configure composer
>  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
> - composer config github-oauth.github.com {GITHUB_TOKEN}
> - composer install --no-interaction --no-progress --prefer-dist```
> ```

This Issue is about bitbucket, not github.
The problem still exists with 1.9.
