### ISSUE TITLE
Improve Error Reporting

### ISSUE THREAD

**Issue by naderman** [composer/composer#7779]
- [x] https://github.com/composer/composer/issues/8525
- [x] https://github.com/composer/composer/issues/7254
- [x] load full list of versions for packages in error messages, so users are not confused by errors about "no versions found" or versions they expected not showing up
- [x] Make sure packages in lock file conflicting with the root requirements (because lock is outdated) report errors properly, see test removed in https://github.com/composer/composer/pull/8531/commits/6f44350c0108c4310fe5e85cfac70fce46a33aa0
- [x] Try fixing test updated in  https://github.com/composer/composer/pull/8533/commits/ebe910c3a55b2767549350de114f3c63f243d5c3 - or at least make use of unacceptable fixed packages from the Pool to describe why something is missing
- [x] https://github.com/composer/composer/issues/6513
- [x] https://github.com/composer/composer/issues/2811
- [x] Any message of the type "- don't install symfony/symfony v3.4.17|don't install symfony/asset v4.1.6" should instead say "- install at most one of these: symfony/symfony v3.4.17, symfony/asset v4.1.6"
- [x] mention if a package would exist in a lower prio repo but it was shadowed by a higher prio one See https://github.com/composer/composer/pull/8528/files#diff-360e82e2b4be04c97674f5c1019b0970R2

Labeled "Good first issue" because some of the individual tasks may be suitable, take a look at the SolverProblemsException.

**Comment by barryvdh** [comment]
Linked from #7254:
I ran into this issue also. After searching it does indeed seem that I have a conflict in my requirements and the `replace` entry in a library. The only thing which is a bit confusing is that it doesn't state WHY it cannot resolve those packages:

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - don't install twbs/bootstrap v3.3.0|don't install magento/magento2-base 2.2.6
    - don't install twbs/bootstrap v3.3.1|don't install magento/magento2-base 2.2.6
    - don't install twbs/bootstrap v3.3.2|don't install magento/magento2-base 2.2.6
    - don't install twbs/bootstrap v3.3.4|don't install magento/magento2-base 2.2.6
    - don't install twbs/bootstrap v3.3.5|don't install magento/magento2-base 2.2.6
    - don't install twbs/bootstrap v3.3.6|don't install magento/magento2-base 2.2.6
    - don't install twbs/bootstrap v3.3.7|don't install magento/magento2-base 2.2.6
    - magento/product-community-edition 2.2.6 requires magento/magento2-base 2.2.6 -> satisfiable by magento/magento2-base[2.2.6].
    - Installation request for magento/product-community-edition 2.2.6 -> satisfiable by magento/product-community-edition[2.2.6].
    - Installation request for twbs/bootstrap ^3.3 -> satisfiable by twbs/bootstrap[v3.3.0, v3.3.1, v3.3.2, v3.3.4, v3.3.5, v3.3.6, v3.3.7].
```

Not sure how hard it would be, but stating that `magento/magento2-base 2.2.6` replaces ` twbs/bootstrap 3.1.0` would be helpful in this case.

**Comment by sakshamsaxena** [comment]
@naderman Hi! New to Composer here. I'd like to start off with the last checkbox : `Any message of the type "- don't install symfony/symfony v3.4.17|don't install symfony/asset v4.1.6" should instead say "- install at most one of these: symfony/symfony v3.4.17, symfony/asset v4.1.6"`
I'm keen on implementing this. Could you please give a test case to generate this error ? That'd be extremely helpful! Thanks :)

**Comment by naderman** [comment]
@sakshamsaxena Hey! Thnks for your interest, take a look at the getPrettyString function on the Rule object: https://github.com/composer/composer/blob/master/src/Composer/DependencyResolver/Rule.php#L129 It's used in the Problem to output this text: https://github.com/composer/composer/blob/master/src/Composer/DependencyResolver/Problem.php

**Comment by naderman** [comment]
@sakshamsaxena sorry missed your second request, but don't have a test case for this currently, so you'd have to create one yourself.

**Comment by barryvdh** [comment]
#7254 still contains a valid test case I think?

**Comment by xuanquynh** [comment]
The news sounds good to me. I always find difficult to solve dependencies with the current conflict error messages.

**Comment by sakshamsaxena** [comment]
Thanks, @naderman ! Yeah eventually I'd arrived at `getPrettyString` too. Was tinkering with it already, but don't have anything concrete at the moment. I will create a PR soon in coming weekend :)

**Comment by naderman** [comment]
@barryvdh not an actual executable test case, and kind of a different problem

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/pull/8558
