### ISSUE TITLE
Segmentation fault with satis repo and php7.1

### ISSUE THREAD

**Issue by forsdahl** [composer/composer#7781]
My `composer.json`:

```json
{
	...
	"repositories": [
		{
	        "type": "composer",
	        "url": "ssh2.sftp://satisserver/path/to/packages",
	        "options": {
	            "ssh2": {
	                "username": "username",
	                "pubkey_file": "/home/username/.ssh/id_rsa.pub",
	                "privkey_file": "/home/username/.ssh/id_rsa"
	            }
	    	}
        }
    ],
	"require": {
		...
	}
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.7.3
PHP version: 7.1.24
PHP binary path: /usr/bin/php7.1
```

When I run this command:

```
composer -vvv update
```

I get the following output:

```
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/var/www/project): git branch --no-color --no-abbrev -v
Reading /home/username/.composer/composer.json
Loading config file /home/username/.composer/composer.json
Reading /var/www/project/vendor/composer/installed.json
Reading /home/username/.composer/vendor/composer/installed.json
Loading plugin Composer\Installers\Plugin
Running 1.7.3 (2018-11-01 10:05:06) with PHP 7.1.24-1+0~20181112093455.10+stretch~1.gbp09a4fd on Linux / 4.4.0-17134-Microsoft
Loading composer repositories with package information
Reading ssh2.sftp://satisserver/path/to/packages
Segmentation fault (core dumped)
```

And I expected this to happen:
Packages will be updated without a segmentation fault.
I am using a private satis repository over sftp with the latest php 7.1 packages from deb.sury.org in Debian Stretch (real path to repository is replaced in provided composer.json and output). Running composer update with php 5.6 works as expected though, but is not a long-term solution.
Might be related to `file_get_contents` being used with a ssh2.sftp-stream.

**Comment by alcohol** [comment]
Will need a reproducible scenario to solve this.

**Comment by forsdahl** [comment]
@alcohol the closest reproducible scenario I can give you is to use Debian Stretch with the latest php 7.1 package from deb.sury.org, and a composer.json with a valid satis composer repository configuration. Unfortunately I cannot provide a composer.json for you, since our own satis repository is behind a firewall, but any valid ssh2 composer repository config will probably create the same segmentation fault with this php 7.1 version.
As I mentioned, it is probably related to `file_get_contents` being used with a ssh2.sftp context (in `src/Composer/Util/RemoteFilesystem.php`, `getRemoteContents`). Using `curl` or even `fopen` for fetching the remote content would probably be more robust and would likely resolve the problem (`file_get_contents` just doesn't seem very reliable in php with anything other than a normal context and response headers).

**Comment by alcohol** [comment]
I am sorry, but unless you are able to provide a fully reproducible scenario somewhere in a repository, there is nothing we can do for you. We simply do not have the time to both debug problems AND attempt to find a reproducible scenario first, especially complex ones such as these.

**Comment by ericek111** [comment]
This is still a thing. It's a [known bug][wrappers doc] and it has been reported ([PHP #69981][php 69981] and [PHP #64169][php 64169]) several years ago. Using PHPSecLib, as described in #4352, might just be our silver bullet.

I'm just leaving this here for reference while I'm looking into it.

[wrappers doc]: https://www.php.net/manual/en/wrappers.ssh2.php#121849
[php 69981]: https://bugs.php.net/bug.php?id=69981
[php 64169]: https://bugs.php.net/bug.php?id=64169

**Comment by skript-cc** [comment]
My two cents: ssh2.sftp:// urls still don't work due to a bug with stream wrappers in the ssh2 pecl extension, see [#79757](https://bugs.php.net/bug.php?id=79757).*

I encountered this bug after installing ssh2-1.2 on php 7.3.24+ubuntu18.04.1+deb.sury.org+1, using composer 2.0.8.

The configuration example given in the article [Handling private packages](https://getcomposer.org/doc/articles/handling-private-packages.md#security) doesn't work due to this bug. As long as this bug isn't fixed, it would be nice to at least add a warning to the documentation. It could safe other people the trouble of installing the ssh2 extension, only to find out it leads to a segfault error which they can't prevent from happening.

* I don't think the bugs @ericek111 links to are related to the issue described by @forsdahl. Composer doesn't open sftp streams by calling ssh2_* functions, but uses the ssh2.sftp:// stream wrapper with some extra context.
