### ISSUE TITLE
Peer certificate CN=`packagist.org' did not match expected CN=`repo.packagist.org'

### ISSUE THREAD

**Issue by GameScripting** [composer/composer#7789]
Our CI-System just broke as we can't install composer packages anymore in our docker image building process:

    curl -sS https://getcomposer.org/installer | php -- --install-dir=/bin --filename=composer
    cd /var/www
    composer require sabre/dav # <-- this line fails
    cd /

It did not happen until an few minutes ago. We always do a fresh composer install as part of our CI-process.

---

1. Are there any ongoing problems with the offical package-mirror at https://repo.packagist.org/? I also get a cert warning when I use my browser to visit the site:
![grafik](https://user-images.githubusercontent.com/1827070/48549205-6e3a7800-e8cf-11e8-8651-8a57527262c8.png)
2. Is there any workarround without disabling TLS cert verification entirely?

**Comment by Zae** [comment]
Was just about to open an issue for this is well, thought I might have broken something myself, but guess not :D I've been having the same problem.

**Comment by Zae** [comment]
And fixed :D, that was fast <3

**Comment by GameScripting** [comment]
Nice. I'll close the issue.
