### ISSUE TITLE
Split requirements and preferred version in require?

### ISSUE THREAD

**Issue by rmccue** [composer/composer#7791]
We'd like to have a metarepo at version `2.0.0` which *requires* `foo/a ~2.0` (e.g. 2.0.9, 2.1.0, 2.2.4, etc), but which *prefers* `foo/a ~2.0.0` (e.g. 2.0.0, 2.0.9, but not 2.1.0). We want to allow the root package (or other package requiring the metarepo) to specify a newer minor version, but otherwise to use `X.0.Y` as a requirement.

(For context: we want to coordinate major versions across packages, and allow people to opt-in to newer releases of specific components before the next major version is released.)

Is it possible to split the requirement from the preferred version? Is this something we could do in a plugin at least? (If so, is there any similar prior art?)

**Comment by Seldaek** [comment]
IMO the way to do this is to use RC/beta/alpha releases. Then you can require ^2.0 in your package, and when 2.1.0-alpha or 2.1.0-RC or whatever comes about, by default composer will stick to 2.0.x, but if the user requires `"foo/a": "^2.1@RC"` or even simply `"foo/a": "@RC"` for example that would allow them to opt-in to pre-releases. Once 2.1.0 stable hits, everyone would upgrade, but if you follow semver things shouldn't break. I don't really see Composer offering further options on that front, but IMO it's not really necessary if you do versioning correctly.
