### ISSUE TITLE
add a --dry-run option to the 'remove' command 

### ISSUE THREAD

**Issue by joachim-n** [composer/composer#7793]
The install and update commands have a --dry-run option, but the remove command does not.

**Comment by Seldaek** [comment]
`require` also doesn't AFAIK. What should it do exactly, skip everything, or just skip doing the update? Because there is a --no-update for that.

**Comment by joachim-n** [comment]
The point of a dry-run option is to show the user what *would* happen, but not to actually make any changes.

So --no-update doesn't satisfy this, as AFAIK it only removes the given package from the composer.json file, but doesn't show me any of the other effects that the remove command would have, such as removing dependencies or updating totally unrelated packages (see #7476).

**Comment by Dzhuneyt** [comment]
@Seldaek could you please review if https://github.com/composer/composer/pull/7896 is an okay solution to this problem?

**Comment by Seldaek** [comment]
See https://github.com/composer/composer/pull/7896#issuecomment-458060388 - scheduling for 2.0 as it might become possible then, but right now I don't think it's worth the added complexity to do this correctly.

**Comment by luenemam** [comment]
possible workaround:

    composer remove --no-update vendor/package
    composer update --with-dependencies --dry-run vendor/package

**Comment by Seldaek** [comment]
Fixed in https://github.com/composer/composer/commit/d14d411fa47b721e672f0d2644cf34db38ff24aa for 2.0
