### ISSUE TITLE
Composer no longer allows updating manifest with "no yet existing" version (as of 1.5.3)

### ISSUE THREAD

**Issue by kdambekalns** [composer/composer#7800]
We have a script for creating new branches in our project. Since that needs to update the version of required packages from `dev-master` to e.g. `2.1.x-dev` when creating the `2.1` branch, we used to do this in that script:

```
composer require --no-update foo/bar:2.1.x-dev
```

Note that at that very point the `2.1` branch does not (yet) exist, but is coming into existence during the very run of said script.

That works fine up to and including Composer 1.5.2. As of 1.5.3 it no longer works and results in `Could not find package foo/bar in a version matching 2.1.x-dev`. The reason is the use of `findBestVersionForPackage()` in [1.5.2...1.5.3](https://github.com/composer/composer/compare/1.5.2...1.5.3#diff-95c967f849028fd2898e6edf84afd7c0)

We would love to keep using Composer for those updates, instead of messing with the manifest file in some home-grown code. Any advice?

**Comment by alcohol** [comment]
Create the branch first?

**Comment by kdambekalns** [comment]
Well, we have a mono-repo and rather long-running split jobs, so that would really take some time. Plus, right now it's quite "atomic", which I like. Everything is done on the CI machine and then pushed at the end.

**Comment by alcohol** [comment]
I am confused. No matter how large your repo is, creating a new branch takes less than a second.

**Comment by kdambekalns** [comment]
Yes, but splitting individual packages (into seperate repositories) takes a while, and the complaint is about one of those "single packages"… it _might_ be that pushing the branch in the mino-repo works, since it "is" also the single packages. Need to try that.

**Comment by Seldaek** [comment]
Regardless.. IMO if you provide a version constraint it probably should just trust it and not look it up. I *think* it's a regression but would have to look at in more depth when I have time.

**Comment by alcohol** [comment]
I think we need a better picture of what you are trying to achieve, cause right now it is not very clear, at least not to me.

You are basically asking why it is no longer possible to require a version that does not exist, and this question seems somewhat rhetorical to me.

@Seldaek you implemented this behaviour in https://github.com/composer/composer/commit/b4df2c95173f08d887ad0c4066afbb3ca17a33f7#diff-95c967f849028fd2898e6edf84afd7c0

**Comment by Seldaek** [comment]
That's in case there is no version provided when you require AFAIK. 
Anyway don't have time to dig in now so will see some other time.

**Comment by kdambekalns** [comment]
> You are basically asking why it is no longer possible to require a version that does not exist, and this question seems somewhat rhetorical to me.

Exactly, I want to update the manifest with a new version constraint. I _know_ that version will exist as soon as I am done.

I understand the benefit of checking for an existing version, generally. In my case, however, the previous behavior was jus nice. :) I could imagine only checking if no constraint was explicitly given (as @Seldaek said above) or skip the check when `--no-update` is given or maybe add a new flag to skip the check.

(And pushing does not help me, just tried that. See https://jenkins.neos.io/job/flow-create-branch/12/console for details)

**Comment by Seldaek** [comment]
Ok sorry I my rush last week I missed that you reported this for 1.**5**.3. I thought this was about 1.7.3 - But this "regression" is a year old at this point.. Anyway I shall fix it so it's not checking versions when --no-update is provided, that way you can get your errors later when running the update, if appropriate.

**Comment by kdambekalns** [comment]
Yes, a year old, but still… **Thanks** for fixing this! ❤️
