### ISSUE TITLE
SHA384 is not supported by your openssl extension,

### ISSUE THREAD

**Issue by Firesphere** [composer/composer#7802]
When I run this command:

```
composer self-update
```

I get the following output:

```
SHA384 is not supported by your openssl extension,
```

And I expected this to happen:
Composer to update itself

**Comment by Seldaek** [comment]
This has been fixed already, reinstall composer from https://getcomposer.org to overwrite your current one as it's too old and won't support updating on your system.. We can't fix old builds unfortunately.

**Comment by marthad-musa** [comment]
Hi, I have a different kind of problem. Lately I got a new laptop and I tried to install composer but the same message keep appearing and interrupt the setup causing it to cancel the process.
This is the message that appear :
"SHA384 is not supported by your openssl extension composer"
Please help me, guys

**Comment by marthad-musa** [comment]
Hi, I have a different kind of problem. Lately I got a new laptop and I tried to install composer but the same message keep appearing and interrupt the setup causing it to cancel the process.
This is the message that appear :
"SHA384 is not supported by your openssl extension composer"
Please help me, guys

**Comment by yht** [comment]
Reinstall your composer.

> php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
> php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
> php composer-setup.php
php -r "unlink('composer-setup.php');"

**Comment by leymannx** [comment]
@yht – And maybe `mv composer.phar /usr/local/bin/composer` at the end.

**Comment by Stalinko** [comment]
Also faced an issue:
`Unable to write keys.dev.pub to: /home/apps/.composer`

Solved by:
`sudo chown apps:apps -R /home/apps/.composer/`

(change `apps` to your username)

**Comment by mehov** [comment]
````
wget -O /var/www/composer-install https://getcomposer.org/installer
php /var/www/composer-install
````
