### ISSUE TITLE
Add creation timestamp to composer.lock files

### ISSUE THREAD

**Issue by Synchro** [composer/composer#7805]
Minor feature request: the composer.lock file does not contain a timestamp of when it was generated. Obviously the file creation time does provide that information, but that's easily affected by external operations, for example some file copy operations will update the file system created/modified timestamps, so it would be better to have a record of this inside the file.

In short, please add a timestamp (preferably human-readable) inside the composer.lock file.

**Comment by alcohol** [comment]
Mind clarifying why you would need this? That would also help us determine whether it should be part of the hash that we use to verify the lock file, etc.

**Comment by Synchro** [comment]
Sure - I'm currently doing a code audit on someone else's code, and I wanted to know when packages were last updated, and was a bit surprised that I couldn't find out. Best I could do was to search through the package list and see when the most recent update was, which is a bit painful. It probably should be included in the verification hash so as to make it tamper-proof.

**Comment by Seldaek** [comment]
`git log composer.lock` should be enough really. I don't really think adding a timestamp in there would be generally helpful as it might change even if no dependencies change resulting in git diffs for no reason. I get that it might help you in this one case, but it sounds like a bad thing overall.

**Comment by gmponos** [comment]
A partial work around would be to create your own script and add it on composer-install/update commands.

**Comment by alcohol** [comment]
What @gmponos said, something as simple as this for example:

```
{
    "scripts": {
        "post-update-cmd": "@composer config extra.updated-at `date +%FT%T`"
    },
    "extra": {
        "updated-at": "2018-11-27T13:17:09"
    }
}
```

**Comment by Synchro** [comment]
That's a nice trick, but it's not something I can impose on a client or upstream project.

I think @Seldaek's suggestion of using the git log will do for my purposes - thanks Jordi!

As far as causing git noise, composer could avoid that by declining to update the timestamp if there have been no changes - that's also another circumstance where a no-op update alters the file timestamp.
