### ISSUE TITLE
composer 1.7.3 doesn't disable xdebug on archlinux

### ISSUE THREAD

**Issue by Potomac** [composer/composer#7807]
I use archlinux, apache 2.4.37-1,  php 7.2.12-1, composer 1.7.3-1, xdebug php extension (2.6.1-1)

I have installed xdebug php extension, composer is supposed to automatically disable xdebug when installed, but it's not the case with my configuration,

to trigger the bug :  
- install archlinux 
- install apache, php 7.2.12-1, composer 1.7.3-1 (the official archlinux packages)
- enable all php extensions needed by composer
- install xdebug php extension (an archlinux package is provided) and enable it

and finally install "laravel" with composer :  
composer require "laravel/installer"

you will notice that composer claims that zip php extension is not installed, but this extension is really installed in /etc/php.ini, and you will notice also that xdebug is not disabled by composer,

the compose.json : 
{
    "require": {
        "laravel/installer": "^2.0"
    }
}

the output of the command "composer require "laravel/installer" : 

Warning: file_get_contents(/etc/php/conf.d/xdebug.ini): failed to open stream: Operation not permitted in phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/XdebugHandler.php on line 330

Call Stack:
    0.0001     400208   1. {main}() /usr/bin/composer:0
    0.0067     640824   2. require('phar:///usr/bin/composer/bin/composer') /usr/bin/composer:24
    0.0104     883040   3. Composer\XdebugHandler\XdebugHandler->check() phar:///usr/bin/composer/bin/composer:17
    0.0104     883416   4. Composer\XdebugHandler\XdebugHandler->prepareRestart() phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/XdebugHandler.php:133
    0.0105     884008   5. Composer\XdebugHandler\XdebugHandler->writeTmpIni() phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/XdebugHandler.php:295
    0.0115     884232   6. file_get_contents() phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/XdebugHandler.php:330

Using version ^2.0 for laravel/installer
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/installer v2.0.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - laravel/installer v2.0.0 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - Installation request for laravel/installer ^2.0 -> satisfiable by laravel/installer[v2.0.0, v2.0.1].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/php.ini
    - /etc/php/conf.d/apcu.ini
    - /etc/php/conf.d/imagick.ini
    - /etc/php/conf.d/xdebug.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, deleting ./composer.json.

Output of `composer diagnose`:
PHP Warning:  file_get_contents(/etc/php/conf.d/apcu.ini): failed to open stream: Operation not permitted in phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/XdebugHandler.php on line 330
PHP Stack trace:
PHP   1. {main}() /usr/bin/composer:0
PHP   2. require() /usr/bin/composer:24
PHP   3. Composer\XdebugHandler\XdebugHandler->check() phar:///usr/bin/composer/bin/composer:17
PHP   4. Composer\XdebugHandler\XdebugHandler->prepareRestart() phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/XdebugHandler.php:133
PHP   5. Composer\XdebugHandler\XdebugHandler->writeTmpIni() phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/XdebugHandler.php:295
PHP   6. file_get_contents() phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/XdebugHandler.php:330

Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.7.3
PHP version: 7.2.12
PHP binary path: /usr/bin/php

the workaround I use : if I uninstall xdebug extension then composer works without problem

**Comment by alcohol** [comment]
First of all, we do not support packages not provided by us (as much as I am an Archlinux fan, the Archlinux package for Composer is not maintainted by us). There is virtually zero need to package composer since it can be installed system/vendor agnostic incredibly easily.

Second, can you please provide us with the output of the following commands:

```
which php
php --ini
composer diagnose
composer show --platform
```

**Comment by alcohol** [comment]
I think the problem is pretty straightforward though;

> Warning: file_get_contents(/etc/php/conf.d/xdebug.ini): failed to open stream: Operation not permitted in phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/XdebugHandler.php on line 330

You seem to have messed up the permissions on this file. Normally it should be at least readable by the world. Composer is currently unable to identify if xdebug is present and therefor will not disable it.

**Comment by Potomac54** [comment]
Hello Alcohol : 

> I think the problem is pretty straightforward though;
> 
> > Warning: file_get_contents(/etc/php/conf.d/xdebug.ini): failed to open stream: Operation not permitted in phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/XdebugHandler.php on line 330
> 
> You seem to have messed up the permissions on this file. Normally it should be at least readable by > the world. Composer is currently unable to identify if xdebug is present and therefor will not disable it.

I have checked yesterday  the file /etc/php/conf.d/xdebug.ini, it is readable by all the world, the xdebug package is provided by archlinux, by default /etc/php/conf.d/xdebug.ini file is readable for all the world
https://www.archlinux.org/packages/community/x86_64/xdebug/

the permission rights (chmod) for /etc/php/conf.d/xdebug.ini file is "644" according to the PKGBUILD file used by the archlinux maintener of the xdebug package
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/xdebug

maybe the problem is elsewhere, a missing configuration in php.ini related to phar, but I am almost sure that I have well configured php.ini for composer, 

as you said your are an archlinux fan (and also user ?) you can test with your archlinux installation, by installing archlinux composer package and the xdebug package, then you should see if composer can really work when xdebug is activated, 

I am at work so I don't have my personnal PC with me, but  I can post the outpout of  composer diagnose (present in the first message) :

PHP Warning: file_get_contents(/etc/php/conf.d/apcu.ini): failed to open stream: Operation not permitted in phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/XdebugHandler.php on line 330
PHP Stack trace:
PHP 1. {main}() /usr/bin/composer:0
PHP 2. require() /usr/bin/composer:24
PHP 3. Composer\XdebugHandler\XdebugHandler->check() phar:///usr/bin/composer/bin/composer:17
PHP 4. Composer\XdebugHandler\XdebugHandler->prepareRestart() phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/XdebugHandler.php:133
PHP 5. Composer\XdebugHandler\XdebugHandler->writeTmpIni() phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/XdebugHandler.php:295
PHP 6. file_get_contents() phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/XdebugHandler.php:330

Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0 87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B 0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.7.3
PHP version: 7.2.12
PHP binary path: /usr/bin/php

I will post the output of other command you have asked at the end of the day,

thanks for your support, I hope we will find the solution

**Comment by johnstevenson** [comment]
Interesting that xdebug-handler cannot read the ini files (which php is using and which php has provided the locations of):

> PHP Warning: file_get_contents(/etc/php/conf.d/apcu.ini): failed to open stream:

> Warning: file_get_contents(/etc/php/conf.d/xdebug.ini): failed to open stream: 

If you enable debug output (for xdebug-handler) it may give us a clue:

```
export XDEBUG_HANDLER_DEBUG=1
composer ...
```

**Comment by alcohol** [comment]
```
rob@galaga ~ $ sudo pacman -Syyu xdebug composer
:: Synchronizing package databases...
 antergos                                                     167.6 KiB   864K/s 00:00 [--------------------------------------------------] 100%
 core                                                         132.8 KiB   846K/s 00:00 [--------------------------------------------------] 100%
 extra                                                       1680.4 KiB  1605K/s 00:01 [--------------------------------------------------] 100%
 community                                                      4.7 MiB  3.13M/s 00:02 [--------------------------------------------------] 100%
 multilib                                                     178.3 KiB   990K/s 00:00 [--------------------------------------------------] 100%
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Package (3)       New Version  Net Change  Download Size

extra/php         7.2.12-1      19.68 MiB       3.38 MiB
extra/composer    1.7.3-1        1.79 MiB       0.37 MiB
community/xdebug  2.6.1-1        0.32 MiB       0.10 MiB

Total Download Size:    3.84 MiB
Total Installed Size:  21.78 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 php-7.2.12-1-x86_64                                            3.4 MiB  2.86M/s 00:01 [--------------------------------------------------]  87%
 composer-1.7.3-1-any                                           3.7 MiB  2.69M/s 00:01 [--------------------------------------------------]  97%
 xdebug-2.6.1-1-x86_64                                          3.8 MiB  2.52M/s 00:02 [--------------------------------------------------] 100%
(3/3) checking keys in keyring                                                         [--------------------------------------------------] 100%
(3/3) checking package integrity                                                       [--------------------------------------------------] 100%
(3/3) loading package files                                                            [--------------------------------------------------] 100%
(3/3) checking for file conflicts                                                      [--------------------------------------------------] 100%
(3/3) checking available disk space                                                    [--------------------------------------------------] 100%
:: Processing package changes...
(1/3) installing php                                                                   [--------------------------------------------------] 100%
(2/3) installing xdebug                                                                [--------------------------------------------------] 100%
(3/3) installing composer                                                              [--------------------------------------------------] 100%
:: Running post-transaction hooks...
(1/3) Cleaning cache
==> no candidate packages found for pruning
(2/3) Purging uninstalled packages from cache
==> no candidate packages found for pruning
(3/3) Arming ConditionNeedsUpdate...
```

After enabling xdebug in `/etc/php/conf.d/xdebug.ini`:
```
rob@galaga /tmp/composer $ XDEBUG_HANDLER_DEBUG=1 /usr/bin/php $(which composer) show --platform
xdebug-handler[5180] Checking COMPOSER_ALLOW_XDEBUG
xdebug-handler[5180] The xdebug extension is loaded (2.6.1)
xdebug-handler[5180] Process restarting (COMPOSER_ALLOW_XDEBUG=internal|2.6.1|1|*|*)
xdebug-handler[5180] Running '/usr/bin/php' '-n' '-c' '/tmp/VxQ9fL' '/usr/bin/composer' 'show' '--platform' '--ansi'
xdebug-handler[5181] Checking COMPOSER_ALLOW_XDEBUG
xdebug-handler[5181] Restarted (26 ms). The xdebug extension is not loaded
composer-plugin-api 1.1.0    The Composer Plugin API
ext-ctype           7.2.12   The ctype PHP extension
ext-curl            7.2.12   The curl PHP extension
ext-date            7.2.12   The date PHP extension
ext-dom             20031129 The dom PHP extension
ext-fileinfo        1.0.5    The fileinfo PHP extension
ext-filter          7.2.12   The filter PHP extension
ext-hash            1.0      The hash PHP extension
ext-json            1.6.0    The json PHP extension
ext-libxml          7.2.12   The libxml PHP extension
ext-mbstring        7.2.12   The mbstring PHP extension
ext-mysqlnd         0        The mysqlnd PHP extension (actual version: mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98a...
ext-openssl         7.2.12   The openssl PHP extension
ext-pcntl           7.2.12   The pcntl PHP extension
ext-pcre            7.2.12   The pcre PHP extension
ext-PDO             7.2.12   The PDO PHP extension
ext-Phar            2.0.2    The Phar PHP extension
ext-posix           7.2.12   The posix PHP extension
ext-readline        7.2.12   The readline PHP extension
ext-Reflection      7.2.12   The Reflection PHP extension
ext-session         7.2.12   The session PHP extension
ext-SimpleXML       7.2.12   The SimpleXML PHP extension
ext-SPL             7.2.12   The SPL PHP extension
ext-tokenizer       7.2.12   The tokenizer PHP extension
ext-xdebug          2.6.1    The xdebug PHP extension
ext-xml             7.2.12   The xml PHP extension
ext-xmlreader       7.2.12   The xmlreader PHP extension
ext-xmlwriter       7.2.12   The xmlwriter PHP extension
ext-zip             1.15.4   The zip PHP extension
ext-zlib            7.2.12   The zlib PHP extension
lib-curl            7.62.0   The curl PHP library
lib-libxml          2.9.8    The libxml PHP library
lib-openssl         1.1.1    OpenSSL 1.1.1  11 Sep 2018
lib-pcre            8.42     The pcre PHP library
php                 7.2.12   The PHP interpreter
php-64bit           7.2.12   The PHP interpreter, 64bit
php-ipv6            7.2.12   The PHP interpreter, with IPv6 support
xdebug-handler[5180] Restarted process exited 0
```

**Comment by Potomac** [comment]
I found the explanation : the problem was the setting "open_basedir" in /etc/php.ini, the directory "/etc/php" was not present in the list of the allowed directories, if I add "/etc/php" for this setting then all is ok,

PHP Warning:  file_get_contents(): **open_basedir restriction in effect**. File(/etc/php/php.ini) is not within the allowed path(s)

the correct setting in /etc/php.ini if you use open_basedir : 

 open_basedir = /srv/http/:/home/:/tmp/:/usr/share/pear/:/usr/share/webapps/:/etc/webapps/:/usr/bin:/usr/bin/composer:/etc/php

the output of composer diagnose : 

$ composer diagnose  
xdebug-handler[2031] Checking COMPOSER_ALLOW_XDEBUG
xdebug-handler[2031] The xdebug extension is loaded (2.6.1)
xdebug-handler[2031] Process restarting (COMPOSER_ALLOW_XDEBUG=internal|2.6.1|1|*|*)
xdebug-handler[2031] Running '/usr/bin/php' '-n' '-c' '/tmp/9GuJJp' '/bin/composer' 'diagnose' '--ansi'
xdebug-handler[2032] Checking COMPOSER_ALLOW_XDEBUG
xdebug-handler[2032] Restarted (45 ms). The xdebug extension is not loaded
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.7.3
PHP version: 7.2.12
PHP binary path: /usr/bin/php
xdebug-handler[2031] Restarted process exited 0

**Comment by johnstevenson** [comment]
@Potomac 

> it would be interesting to add in composer source code an improvement for the xdebug detection presence

I didn't bother with checking for `open_basedir` restrictions in xdebug-handler because you would normally see it mentioned in the error message. How come it wasn't visible in your initial post?

**Comment by Potomac** [comment]
probably too much warning messages in the log, the most important message goes unnoticed ?
in the initial post I haven't pasted all the log (because it was too long)

**Comment by johnstevenson** [comment]
Ha, ha. I know what you mean.

I think that your original problem was that xdebug-handler restarted the process with an essentially empty temporary ini file (because it couldn't read the ini files reported by php from `php_ini_loaded_file` and `php_ini_scanned_files`). Consequently none of your ini settings, including those that enable extensions, were available.

Which is not good and xdebug-handler should probably not restart in this case. Could you check that this is happening please on your old set up (with the problem open_basedir restrictions in place):

```
export XDEBUG_HANDLER_DEBUG=2
composer --version
```
This directive saves the temp ini file, and tells you were it is.

**Comment by Potomac** [comment]
I did the test : the temp ini file is almost empty (4 empty lines and one line "opcache.enable_cli=0")

file:///tmp/bMTCYD

**Comment by johnstevenson** [comment]
Thanks, that's very helpful. I'll update https://github.com/composer/xdebug-handler to not restart
