### ISSUE TITLE
Using require-dev, but exclude require-dev section of packages' dependencies

### ISSUE THREAD

**Issue by riconeitzel** [composer/composer#7808]
Today in project I wanted to install a debug package on my local machine. So I used `require --dev`. That forces composer to install all packages from the dependency's require-dev section.

There should be a way to avoid installing the packages' dev dependencies, if you just want to *use* the package, not *develop* for it.

In Detail:

I was installing `firegento/debug` with `require --dev` to make it available to my local dev env.
It requires `magento-composer-installer` which has a reference to another package that references `symfony/debug`.

I only need `firegento/debug` locally but don't need `symfony/debug` locally as it is not even used for it, but rather a few levels down in some `require-dev` sections, which are only needed, if you want to develop with and for that component.

I was looking for that feature request/support request but couldn't find anything suitable to that. I'm very sorry in advance if that's a duplicate!

Rico

**Comment by xabbuh** [comment]
The `require-dev` section is only taken into account from the project's `composer.json` file. `symfony/debug` is probably installed for another reason. Can you show the output of `composer require --dev firegento/debug -vvv`?

**Comment by xabbuh** [comment]
You can also use `composer why symfony/debug` to find out which package actually requires the Symfony Debug component.

**Comment by riconeitzel** [comment]
Hi @xabbuh, 

"the devil is in the details" (der Teufel steckt im Detail) … thanks to your tipps, I finally figured out that it's most probably a "bug" in `symfony/console`'s `composer.json`.

Have a great weekend and thank you for your fast and kind help :-)

Rico
