### ISSUE TITLE
Document opportunities to donate to Composer project

### ISSUE THREAD

**Issue by legoktm** [composer/composer#7810]
I'm forwarding a request from IRC (`#composer-dev`) since I'm also interested in the answer (as someone who works at an org who is also potentially interested in contributing back). Apologies in advance if there's a better forum for this type of question, I couldn't really think of one.

`<preinheimer> Is there a way to give Composer (or its developers) money? We're starting up a new thing at work where the company gives money to open source projects we use as chosen by our devs, and we use composer a fair bit so...`

I looked on the main web page and didn't see any obvious donate links. So what's the best way for users of composer to financially donate back to the project?

**Comment by alcohol** [comment]
I do not believe Composer is registered as a non-profit, but @Seldaek or @naderman probably know more about that than me. One way you can definitely contribute towards Composer, is by making use of the commercial Packagist offering (https://packagist.com).

**Comment by naderman** [comment]
Indeed, we do not accept donations. If you'd like to support the project financially, please purchase licenses for Private Packagist.
