### ISSUE TITLE
create-project command modifies the composer.json file from the repo

### ISSUE THREAD

**Issue by emodric** [composer/composer#7816]
Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.0
PHP version: 7.2.12
PHP binary path: /usr/bin/php7.2
```

When I run this command:

```
composer create-project ezsystems/ezplatform
```

`composer.json` file in the project is modified in the following ways

1) author names are removed from `authors` section, making the `composer.json` file invalid
2) `name` and `description` are removed from the file
3) License is changed to `proprietary`

And I expected this to happen:

`composer.json` file is left untouched.

**Comment by Seldaek** [comment]
I can't reproduce this with `--no-plugins --no-scripts`, so it seems to be caused by one of these https://github.com/ezsystems/ezplatform/blob/v2.3.2.2/composer.json#L90-L93 or a plugin.. In any case not something we can fix AFAICT.

**Comment by emodric** [comment]
Hn. Might actually be `symfony/flex` issue, since I have it installed as a global dependency. Sorry for the noise.
