### ISSUE TITLE
Updating a single package doesn't work

### ISSUE THREAD

**Issue by kostiklv** [composer/composer#782]
Running `composer.phar update vendor/package` actually updates all the packages, not just the selected one.

**Comment by gstoert** [comment]
Is there any progress on this issue? It still doesn't seem to work, neither with composer.lock in place nor without it.

**Comment by stof** [comment]
@gstoert if you have an issue, open a new issue instead of commenting on an issue closed 3 years ago. Your issue is likely to be a different one

**Comment by luis02lopez** [comment]
+1 still hace the same problem. It update every package. This issue is in current topic.

**Comment by Jafo232** [comment]
I can confirm this issue is still happening.

**Comment by smalec79** [comment]
And still doesn't do it right

**Comment by smalec79** [comment]
with
Composer version 1.6.5 2018-05-04 11:44:59

**Comment by stof** [comment]
my comment from November 2015 still holds true. If you have an issue, please open a new ticket, with details about what you expect and what happens instead, instead of telling us that you face the same bug than here, whole this one was fixed in 2012 (and so your issue is probably a different one)

**Comment by naneri** [comment]
Still have this issue
