### ISSUE TITLE
Allow installations in non-empty folders

### ISSUE THREAD

**Issue by jakedohm** [composer/composer#7822]
Hi all! First of all, Composer is awesome, thanks so much for all of the hard work on it!

Here's the problem I'm running into: I work with Craft CMS, which uses `composer create-project` to initialize a new project (but this issue isn't Craft specific). My workflow is: Create a new Github repo, clone it into `~/Sites`, `cd` to the newly cloned repo's folder, run `composer create-project craftcms/craft .`. The problem with this is that you can't use `composer create-project` in a non-empty folder, and when a folder is cloned from GitHub it always has a `.git` folder (and often a README).

I've reviewed issue #2044 (and #2278) so I understand the technical problem with not being able to `git clone` into a non-empty folder, but I believe there are viable solutions to this problem, and it seems like a far too common use-case to ignore.

I think [this solution](https://github.com/composer/composer/issues/2044#issuecomment-90767947) (in #2044) is a good one, but I'll differ to y'all on implementation as I don't know the ins-and-outs of Composer 😄.

I'd really love to see this implemented, as it would make the Composer experience easier not just for me, but for a fair amount of users.

If you're interested in discussing implementation, I'm glad to chip in and/or beta test :smile:

**Comment by er1z** [comment]
Workaround: run composer as usual and force git to clone into `target_` — after composer is done, rename `target` to `target_`. Works for me. :)

**Comment by alcohol** [comment]
The proposed solution in #2044 is a lot of work to implement for a feature that is barely in demand and that can actually be worked around quite easily by a user themselves. Expecting the maintainers to implement this is not reasonable. You are free to submit a PR though.

**Comment by Seldaek** [comment]
Yeah I tend to agree that this isn't needed at all.. It's really not hard to move a directory or do a git init after you do create-project (or you could do a git clone if you get git to fix this problem on their end..).

If someone makes a reasonable PR which doesn't add too much complexity why not, but I am not going to do this myself.

**Comment by Seldaek** [comment]
Closing as I don't think we will ever do anything here.
