### ISSUE TITLE
JSON Schema for composer.lock file

### ISSUE THREAD

**Issue by Majkl578** [composer/composer#7823]
Hi,

there appears to be no JSON schema for composer.lock structure.
This is a bit problematic for tools building on top of the lockfile, be it for reading, manipulation, maintaining bi-directional compatibility or different use cases.

Would it be possible to add one?

Thanks.

**Comment by alcohol** [comment]
I think this is not entirely unreasonable to ask/do. @Seldaek would you be ok with this? I could probably write one up pretty easily based on the one we have for `composer.json` with the extra attributes unique to the lock file.

**Comment by Seldaek** [comment]
Yeah it sounds reasonable for sure.

**Comment by Seldaek** [comment]
See https://github.com/composer/composer/pull/12123 if anyone interested in this wants to help review.
