### ISSUE TITLE
PHP compatibility for older releases

### ISSUE THREAD

**Issue by milo** [composer/composer#7826]
Hi,

we hit a problem with PHP compatibility for older releases. PHP throws Fatal error when an `object` is used as a class name since PHP 7.2. We used such name in times of PHP 5.6 and we have many library releases, namely 2.2.0 - 2.2.9 with PHP restriction to `>=5.3.1` and 2.3.0 - 2.3.13 with PHP restriction to `>=5.6`. These branches are no longer maintained but many projects still depend on them.

Now, people are switching to PHP 7.2, the Composer installs library in version 2.2.9 or 2.3.13 without error, but an application fails after. We cannot fix that by PHP restriction to `<7.2` and releasing 2.2.10 and 2.3.14, because the Composer will still install older ones.

I cannot imagine how complex the problem is, but would be nice somehow inform the Composer, that such old library releases are not compatible with PHP 7.2 anymore.

**Comment by staabm** [comment]
I guess one need to un-publish the available releases and publish a new minor for 2.2.x and 2.3.x

**Comment by milo** [comment]
@staabm IMHO, that would break many installations with `composer.lock` file versioned.

**Comment by JanTvrdik** [comment]
@milo Maybe not, with `composer.lock` no lookup to packagist.org is done.

**Comment by milo** [comment]
@JanTvrdik I didn't know that. But still, seems to me wrong to "remove" all old releases.

**Comment by alcohol** [comment]
@Seldaek I forgot if there was a recommended approach to this kind of situation. If there is, maybe we should document it? I'm guessing there isn't much that can be done though, aside from creating a new patch release on top of the older tags with a fixed `composer.json`?

**Comment by Seldaek** [comment]
Yeah the only way is to move forward with this kind of problem. People requiring older (broken) versions will experience issues, nothing you can do about it. Even if you delete the old tags, they could still install older versions from lock files so issues might occur anyway.
