### ISSUE TITLE
"*" don't work in repository name for conflict config

### ISSUE THREAD

**Issue by steevanb** [composer/composer#7827]
Not sure it is an issue, or normal behavior.

With this `composer.json` (i removed some useless configs for the example):
```json
{
    "require": {
        "php": "^7.1.3",
        "symfony/console": "4.0.*",
        "symfony/flex": "^1.0",
        "symfony/framework-bundle": "4.0.*",
        "symfony/yaml": "4.0.*",
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "conflict": {
        "symfony/symfony": "*",
        "symfony/*": ">=4.1.0"
    },
}
```
When i run `composer update`, some `symfony/` dependencies who are not in my composer.json, like `symfony/routing`, will be downloaded as `4.2.1` (latest version) instead of `4.0.*` (as configured in `conflict`).

If i add `"symfony/routing": ">=4.1.0"` in `conflict`, it's ok, `symfony/routing` will be downloaded in 4.0.15 version.

Maybe `*` in repository name is not taken into account ?
In this case, what can i do to restrict all repositories under `symfony` as `<4.1.0` ?

**Comment by alcohol** [comment]
`*` wildcard is not supported.

> In this case, what can i do to restrict all repositories under symfony as <4.1.0 ?

Add conflict rules for them all.

**Comment by apfelbox** [comment]
But is this not a feature that might provide some value?

**Comment by steevanb** [comment]
See https://github.com/symfony/symfony/issues/29581, this is an example on why it might be a good feature :)

**Comment by stof** [comment]
@steevanb this wildcard won't help you emulate the Flex feature without flex, because `symfony/*` would match more packages than the `symfony/symfony` subtree splits (and these other packages have different version numbers)

**Comment by steevanb** [comment]
You are everywhere @stof ;)
I know, but if i have to add just 2 or 3 repositories in conflict, to allow other versions for repositories who are not directly linked to the framework (a component), it's better than add "all" this repositories.
And maybe forgot one, or don't know a new one has been added, and updated to a version i don't want.

For example, don't allow to get 4.2.* when you want 4.1.* for components, but allow another repository who is not a component and who not follow same versions (see `conflict` section) :
```json
{
    "require": {
        "php": "^7.1.3",
        "symfony/console": "4.0.*",
        "symfony/flex": "^1.0",
        "symfony/framework-bundle": "4.0.*",
        "symfony/yaml": "4.0.*",
    },
    "conflict": {
        "symfony/symfony": "*",
        "symfony/*": ">=4.1.0",
        "symfony/not-component": ">=5.0.0"
    },
}
```

**Comment by xabbuh** [comment]
But that still would mean that you forbid any other bundle/package from the `symfony` to be installed in a version greater than or equal to 4.1.0 (and this may happen, for example, for MonologBundle or the polyfill packages).

**Comment by steevanb** [comment]
No, see my example: if you add symfony/*, and it works, you could add symfony/monolog-bundle too, and it override symfony/*.

**Comment by curry684** [comment]
This is a very bad idea imho as it makes your `composer.json` root package act on elements out of your control. Symfony could release `symfony/awesome-new-package` tomorrow with version 684 and people would be stumped on why they can't use it.

Now Symfony is unlikely to do something that stupid or unexpected, but you're proposing a generic feature. People would start using this for `someidiot/*`, or `*/*polyfill` or I don't know what. Drama waiting to happen.

The only sort of valid scenario for the use case is Symfony. Symfony has an awesome plugin called Flex to fix exactly these Symfony-specific use cases. Let's keep Symfony specific behavior there.

**Comment by steevanb** [comment]
Well, i don't agree, but ok :)

**Comment by curry684** [comment]
I'm just saying, out of experience from watching Composer issues the past 2~3 years, that if you hand out shotguns there will always be people aiming them at their own feet. And you add documentation and warnings saying they shouldn't be pointed at body parts, and they say ok, and the next day they do it again. And someone else will also do it. And another guy. 

It's a universal truth sadly. [And it's drama to solve once it's there](https://github.com/nodejs/node/issues/5258).
