### ISSUE TITLE
Can not disable ssl via config command when openssl ext not enabled

### ISSUE THREAD

**Issue by glensc** [composer/composer#7828]
having openssl extension missing, I should be able to use `composer config` to disable tls, but the command requires tls 🐙 

```
[@d65fd610a474 /app]# composer config -g -- disable-tls true


  [Composer\Exception\NoSslException]
  The openssl extension is required for SSL/TLS protection but is not available. If you can not enable the openssl extension, you can disable this error, at your own risk, by setting the 'disabl
  e-tls' option to true.


config [-g|--global] [-e|--editor] [-a|--auth] [--unset] [-l|--list] [-f|--file FILE] [--absolute] [--] [<setting-key>] [<setting-value>]...

[@d65fd610a474 /app]# composer --version
Composer version 1.7.3 2018-11-01 10:05:06

```

**Comment by alcohol** [comment]
You can disable it, just not programmatically.

Unfortunately a lot of validations and assertions made are not entirely context aware and could probably be disabled or skipped in certain flows. This requires a significant amount of work though which yields very little gain and isn't really worth development time.

Feel free to submit a PR though.

**Comment by glensc** [comment]
thanks. made title more distinct.
