### ISSUE TITLE
Command to force a composer cache gc

### ISSUE THREAD

**Issue by stof** [composer/composer#7834]
The `Composer\Cache` has 2 cleanup modes:

- `clear` which empties it
- `gc` which removes only files older than some TTL (by default, 6 months).

`clear` is exposed to the user through a command.
`gc` is only run randomly by the FileDownloader on instantiation, and this is only for the `files` cache. Other caches (`vcs` and `repo`) are never garbage collected (btw, gc would not work as is for the vcs, as it deals with individual files, while the vcs cache would have to deal with directories).

Would it make sense to expose a command forcing a gc of the cache ? And also running gc on the repo cache ?

**Comment by Seldaek** [comment]
I think we could have a --gc on clearcache command.. It's already kind of a useless command so I'd rather not add a second one for cache stuff.

As for doing GC on vcs/repo, indeed it's kinda more complex.. and I am not sure it's worth fixing. The whole cache dir on my laptop is ~600MB, which is kinda irrelevant.

**Comment by stof** [comment]
Well, on my own machine, I have 1.2GB for the cache with `vcs` and `repo` being the biggest contributors, so the automatic GC of the `files` cache might be enough to keep it under control already. The command to force a GC might indeed not be necessary.

```
$ du -h -d 1 ~/.cache/composer/
620M	/home/stof/.cache/composer/vcs
408M	/home/stof/.cache/composer/repo
110M	/home/stof/.cache/composer/files
1.2G	/home/stof/.cache/composer/
```

AFAICT, the GC on `repo` could actually be simple. It is caching each cache key as a single file. So as long as reading the cached metadata properly marks the file as used, the existing GC algorithm would work (and we could probably use a lower TTL as I doubt composer will ever be able to use a 6 months old metadata file it never used in-between and not have it being outdated compared to the server).

There is only the `vcs` cache needing a more complex GC algorithm.
