### ISSUE TITLE
Use fully qualified function calls

### ISSUE THREAD

**Issue by gmponos** [composer/composer#7839]
There are a lot of issues risen on composer about performance... how would you feel about a PR that would use Fully Qualified Function Calls

https://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/

**Comment by staabm** [comment]
This type of issues was already discussed . Please search the issues for duplicates

**Comment by gmponos** [comment]
https://github.com/composer/composer/issues/6777

ok found it.
