### ISSUE TITLE
composer install fails after successful composer update

### ISSUE THREAD

**Issue by skobkin** [composer/composer#7843]
Sorry for not providing `composer.json`. Project I'm working on is not open-source and also there are some private vendor libraries which are not publicly accessible.

Output of `composer diagnose`:

```
> $ composer diagnose
Checking composer.json: WARNING
Defining autoload.psr-0 with an empty namespace prefix is a bad idea for performance
require.iphp/filestore-bundle : unbound version constraints (dev-master) should be avoided
require.xxx/xxx/xxx : unbound version constraints (dev-master) should be avoided
require.xxx/dksoapclient : unbound version constraints (dev-master) should be avoided
require.xxx/xxx/xxx : unbound version constraints (dev-master) should be avoided
require.xxx/xxx/xxx : unbound version constraints (dev-master) should be avoided
require.xxx/xxx/xxx : unbound version constraints (dev-master) should be avoided
require.xxx/xxx/xxx : unbound version constraints (dev-master) should be avoided
require.xxx/xxx/xxx : unbound version constraints (dev-master) should be avoided
require.xxx/xxx/xxx : unbound version constraints (dev-master) should be avoided
require.xxx/xxx/xxx : unbound version constraints (dev-master) should be avoided
require.xxx/xxx/xxx : unbound version constraints (dev-master) should be avoided
require.xxx/xxx/xxx : unbound version constraints (dev-master) should be avoided
require.xxx/xxx : unbound version constraints (dev-master) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.0
PHP version: 7.1.25
PHP binary path: /usr/lib64/php7.1/bin/php
```

When I run this command:

```
composer update "sonata-project/*"
composer install
```

I get the following output:

```
> $ composer update "sonata-project/*"
Loading composer repositories with package information                                                                                                         Updating dependencies (including require-dev)         Package operations: 0 installs, 11 updates, 0 removals
  - Updating sonata-project/exporter (1.7.1 => 1.10.0): Downloading (100%)
  - Updating sonata-project/datagrid-bundle (2.2 => 2.2.1): Downloading (100%)
  - Updating sonata-project/doctrine-extensions (1.0.2 => 1.1.3): Downloading (100%)
  - Updating sonata-project/cache (1.0.7 => 1.1.1): Downloading (100%)
  - Updating sonata-project/block-bundle (3.3.0 => 3.4.0): Downloading (100%)
  - Updating sonata-project/admin-bundle (3.18.2 => 3.23.0): Downloading (100%)
  - Updating sonata-project/doctrine-orm-admin-bundle (3.1.4 => 3.1.7): Downloading (100%)
  - Updating sonata-project/google-authenticator (1.0.2 => 2.2.0): Downloading (100%)
  - Updating sonata-project/easy-extends-bundle (2.1.10 => 2.2.0): Downloading (100%)
  - Updating sonata-project/user-bundle (3.2.1 => 3.3.0): Downloading (100%)
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.
Package symfony/assetic-bundle is abandoned, you should avoid using it. Use symfony/webpack-encore-pack instead.
Writing lock file
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
Clearing the cache for the dev environment with debug true
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets
< ... >
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget
> Ivory\CKEditorBundle\Composer\CKEditorScriptHandler::install
----------------------
| CKEditor Installer |
----------------------
 // Dropping CKEditor from "/home/skobkin/src/uts/dictionaryadminproject/vendor/egeloen/ckeditor-bundle/Resources/public"
 520/520 [============================] 100%
 // Downloading CKEditor ZIP archive from "https://github.com/ckeditor/ckeditor-releases/archive/full/latest.zip"
 1713963/1713963 [============================] 100%
 // Extracting CKEditor ZIP archive to "/home/skobkin/src/uts/dictionaryadminproject/vendor/egeloen/ckeditor-bundle/Resources/public"
 521/521 [============================] 100%
 // Dropping CKEditor ZIP archive "/tmp/ckeditor-full-latest-6spoCZ.zip"                                   
 [OK] - CKEditor has been successfully installed...

> $ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sonata-project/doctrine-mongodb-admin-bundle 3.x-dev requires sonata-project/admin-bundle ^3.31 -> no matching package found.
    - sonata-project/doctrine-mongodb-admin-bundle 3.x-dev requires sonata-project/admin-bundle ^3.31 -> no matching package found.
    - Installation request for sonata-project/doctrine-mongodb-admin-bundle 3.x-dev -> satisfiable by sonata-project/doctrine-mongodb-admin-bundle[3.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

And I expected this to happen:

I expected that if `composer update` finished successfully then `composer install` must not cause any problems. But looks like in my situation `composer update` for `sonata-project/*` components causes unsolved dependencies in the `composer.lock`.

What I've already tried:

- `composer clear-cache` and removing `./vendor` before reproducing the problem again
- using Composer's snapshot build and stable (1.8) build.

**Comment by Seldaek** [comment]
This seems very strange but also really hard to figure out anything if we can't reproduce it.. Can you try to build a simpler repro case without your private packages?

**Comment by skobkin** [comment]
@Seldaek Thanks for feedback.

I'll try in spare time. But not sure if I can isolate the problem. Other day I've successfully updated a dozen of other dependencies but when I'm trying to update this bunch of sonata-project packages it happens again.

Maybe I'll try to update them by one and see if this error occurs. And then possibly I could repeat it in the separate repository...

**Comment by pwolanin** [comment]
I'm not sure if thsi is the same problem, but seeing something similar with the 1.8.0 release vs. 1.6.5.  I can get composer update or install to work with 1.6.5, but running it with 1.8.0 fails.

It seems to be referencing the project itself as a conflicting dependency for Drupal core:

```
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - remove raft/chemical-source-database dev-CHEM-170-csd-begin-sprint-composer-updat|remove drupal/core 8.6.5
    - don't install drupal/core 8.6.5|remove raft/chemical-source-database dev-CHEM-170-csd-begin-sprint-composer-updat
    - Installation request for raft/chemical-source-database dev-CHEM-170-csd-begin-sprint-composer-updat -> satisfiable by raft/chemical-source-database[dev-CHEM-170-csd-begin-sprint-composer-updat].
    - Installation request for drupal/core 8.6.5 -> satisfiable by drupal/core[8.6.5].
```

I can post the composer.json file but it references some private code so it's can't be built by you as-is.  Let me see if I can strip those out and still reproduce the bug.

**Comment by stof** [comment]
could it be that `raft/chemical-source-database` has a conflict rule with `drupal/core` or that it has a replace rule for `drupal/core` ?

**Comment by pwolanin** [comment]
@stof  as above - it's fine with composer 1.6.5.  The original source for the project is 
https://github.com/drupal-composer/drupal-project/blob/8.x/composer.json

That comes with a rule:

```
    "conflict": {
        "drupal/drupal": "*"
    },
```

But that's to avoid an outdated mirror of Drupal.

I think I have a file I can post with STR

**Comment by pwolanin** [comment]
See attached composer.json with added TXT extension
[composer.json.txt](https://github.com/composer/composer/files/2759909/composer.json.txt)

STR:
* `mkdir testme && cd testme`
* `composer create-project --stability=dev drupal-composer/drupal-project .`
* `cp ~/Downloads/composer.json.txt  composer.json
`
* `rm composer.lock`
* `composer install`

composer 1.6.5: success
composer 1.7.3: failure
composer 1.8.0: failure

Failure message looks like:
```
  Problem 1
    - don't install drupal/core 8.6.5|remove buggy/test-database No version set (parsed as 1.0.0)
    - remove buggy/test-database No version set (parsed as 1.0.0)|remove drupal/core 8.6.5
    - Installation request for buggy/test-database No version set (parsed as 1.0.0) -> satisfiable by buggy/test-database[No version set (parsed as 1.0.0)].
    - Installation request for drupal/core 8.6.5 -> satisfiable by drupal/core[8.6.5].

```

The bug may be related to the use of the merge plugin which we are using to fetch dev dependencies for Drupal core, since a composer.lock file is created and then the error occurs.

**Comment by skobkin** [comment]
@Seldaek I've just prepared test-case for this issue. I've removed our vendor packages and other packages whose removal didn't prevent reproducibility of this problem (not all packages though but made composer.json MORE compact and clear).

You can see it here: https://github.com/skobkin/composer-issue-7843-test-case

I've just reproduced this on two of my machines using PHP 7.1 and 7.3 (both using composer 1.8.0 as in the first post).

Let me know if I can help more to clarify this problem.

**Comment by Seldaek** [comment]
@skobkin the problem is you require symfony 2.7 https://github.com/skobkin/composer-issue-7843-test-case/blob/master/composer.json#L30 which replaces symfony/validator 2.7, but  sonata-project/core-bundle requires symfony/validator `^2.8 || ^3.2 || ^4.0`. Those two are not compatible. There might be more issues, but regardless you should make sure to update to symfony 2.8 or ideally 3.*/4.* as 2.* is now EOL.

**Comment by Seldaek** [comment]
And.. it worked in older Composer versions because of a bug which allowed installing replaced packages together with their replacers in different versions. So most likely you ended up with symfony/symfony 2.7 installed and then symfony/validator 2.8 or whatever installed as well, and then what happens is all bets are off in terms of code consistency.. You might load classes from one or the other which aren't compatible etc.

**Comment by skobkin** [comment]
Yeah. I think that's exactly what happened to our project.

Thanks!
