### ISSUE TITLE
Create custom warnings for packages to not update

### ISSUE THREAD

**Issue by golddragon007** [composer/composer#7845]
Able to set custom warning massages to packages to i.e. warn the user to not update that package until xy issue solved.
I.e. you have a package (1.4), which has a dependency (1.2). Now, you can't use this, because the dependency has a bug, so you fix the dependency to a previous version (1.1), but the newest version of your package also doesn't work with this old dependency, so you set it an older version (1.3).
Now another guy want to update the package, if "everything works fine" he will find out it has a bug the dependency so he will restore the previous state, or if that kind of bug is a bit more special, maybe he won't, and a third people from your team it will starts investigating for a thing which can't be fixed, because another function relays on the newer package, making a big mess.
To prevent this and similar cases, it would nice if we can put some warning massages to don't upgrade specific packages until something happened.

**Comment by xabbuh** [comment]
IMO you can use conflict rules to prevent the installation of particular versions of a dependency. Committing such a conflict with a meaningful message will also allow other team members to understand the reason.

**Comment by golddragon007** [comment]
Yeah, you can solve it like that, however it's not for that and as far as I saw some developers, not really looking for the reasons, they just run into the wall... And I feel, if I put into the commit message, it will be the same like the readme file, nobody will read it. And another problem, sometimes they just run some commands, and they don't read the messages... Actually it should be an error not a warning, to break/kill the upgrade proccess.

**Comment by Seldaek** [comment]
What I do when requiring things to a specific version (which is always a big red flag when I want to upgrade a package IMO, if it's pinned to a version I look for the reason why..) is add a note like `"require_notes": {"pinned/package": "pinned until issue X is fixed"}` in the composer.json, so it kinda belongs together and is easy to find.

I don't really think we want to provide much more than that so closing.
