### ISSUE TITLE
Composer fails to run on CentOS 7 with SCL enabled

### ISSUE THREAD

**Issue by noloader** [composer/composer#7852]
I'm trying to install Mediawiki 1.30 on CentOS 7 with SCL enabled. SCL provides an updated Apache, PHP, MySQL etc. Mediawiki release tarballs do not have all the files they need to run so we need to install components like composer. Red Hat ships antique versions of the programs so users have to enable SCL to get into a good state. The situation pretty much sucks. I'd rather be dragged across hot rocks and broken glass than deal with this shit.

--

My `composer.json`:

I have no idea what this file is or where it is located. `find /usr/share -name composer.json` returns about 50 of them. Which one do you want?

--

Output of `composer diagnose`:

```
# composer diagnose
PHP Fatal error:  Class 'Phar' not found in /usr/share/php/Composer/Factory.php  on line 514
Fatal error: Class 'Phar' not found in /usr/share/php/Composer/Factory.php on line 514
```

--

When I run this command:

```
# composer update
```

I get the following output:

```
PHP Fatal error:  Class 'Phar' not found in /usr/share/php/Composer/Factory.php  on line 514
Fatal error: Class 'Phar' not found in /usr/share/php/Composer/Factory.php on line 514
```
--

And I expected this to happen:

I expect thing to work. Composer needs to find what it needs or stop depending on stuff it cannot find.

All of this stuff is in Red Hat's SCL directories and they are on-path. Please make this stuff work so I can go back to C/C++ development.

```
# echo $PATH
/opt/rh/python27/root/usr/bin:/opt/rh/rh-php71/root/usr/bin:/opt/rh/rh-php71/roo
t/usr/sbin:/opt/rh/httpd24/root/usr/bin:/opt/rh/httpd24/root/usr/sbin:/usr/local
/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin

# command -v php
/opt/rh/rh-php71/root/usr/bin/php

# find /opt/rh -name phar.so
/opt/rh/rh-php71/root/usr/lib64/php/modules/phar.so
```

-----

In case you're interested, here's what we've had to upgrade because of Mediawiki's overzealous requirements:

```
# ls /opt/rh
httpd24  python27  rh-php71
```

And here are the steps used to perform the SCL upgrade: [How to update Apache to 2.4.29 using SCL?](https://unix.stackexchange.com/q/412122/56041) It makes a good test machine if you are brave enough to try to set one up.

MySQL is next once I figure out the procedure. We can't upgrade to Mediawiki 1.31 until we find a process for MySQL. (I've been working on it since June and I still have not found one).

**Comment by melato** [comment]
I was able to make composer run on a brand new centos7 system which I installed as an LXD container.  I am not a centos user, but I followed the instructions that you referenced (and added yum-utils.noarch).  This is approximately what I did on an Ubuntu 18.04 system with LXD installed:

```
lxc launch images:centos/7 c7
lxc exec c7 bash

yum update
yum install centos-release-scl
yum install yum-utils.noarch
yum-config-manager --enable rhel-server-rhscl-7-rpms
yum -y install rh-php71 rh-php71-php rh-php71-ssl rh-php71-php-mysqlnd

```

create /etc/profile.d/enable-scl-php71.sh with this content:
```
#!/usr/bin/env bash
source scl_source enable rh-php71

```
chmod +x /etc/profile.d/enable-scl-php71.sh

logout and login again

```
php -v
# PHP 7.1.8 (cli) (built: Aug  9 2017 13:20:06) ( NTS )

```
yum install wget

install composer.  I used the following script:

```
#!/bin/sh

EXPECTED_SIGNATURE=$(wget https://composer.github.io/installer.sig -O - -q)
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")

if [ "$EXPECTED_SIGNATURE" = "$ACTUAL_SIGNATURE" ]
then
    php composer-setup.php --quiet
    RESULT=$?
    rm composer-setup.php
    exit $RESULT
else
    >&2 echo 'ERROR: Invalid installer signature'
    rm composer-setup.php
    exit 1
fi

```

mv composer.phar /usr/local/bin/composer

composer -V

```
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer version 1.8.0 2018-12-03 10:31:16

```
composer diagnose
...
