### ISSUE TITLE
can't upgrade a package to the next minor version

### ISSUE THREAD

**Issue by joachim-n** [composer/composer#7854]
I have a project where I can't update the drush/drush package to the next minor version. 

To reproduce this, I created a slimed-down case, by setting up a clean project the following commands:

```
composer init
composer require drush/drush ~9.4.0
```

I used the ~ constraint to simulate the situation that 9.4.0 is the most recent version.

To update the drush/drush package, I now do:

```
composer require drush/drush ^9.5.0
```

This should update drush to the next version, right?

However, this is the output:

```
    1/2:	http://repo.packagist.org/p/provider-latest$0845e071dde0137f218b28f7d7be0bcccc1b479004869bb058db7195f0d622bf.json
    2/2:	http://repo.packagist.org/p/provider-2018-07$c5a9e6b75e480ad0e5f76679cde44cadfc24515aaf1ea15d10e0652fa038fa4a.json
    Finished: success: 2, skipped: 0, failure: 0, total: 2
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install drush/drush 9.5.2
    - Conclusion: don't install drush/drush 9.5.1
    - Conclusion: remove symfony/var-dumper v4.2.1
    - Installation request for drush/drush ^9.5.0 -> satisfiable by drush/drush[9.5.0, 9.5.1, 9.5.2].
    - Conclusion: don't install symfony/var-dumper v4.2.1
    - drush/drush 9.5.0 requires symfony/var-dumper ^3.4 -> satisfiable by symfony/var-dumper[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - Can only install one of: symfony/var-dumper[v3.4.0, v4.2.1].
    - Can only install one of: symfony/var-dumper[v3.4.1, v4.2.1].
    - Can only install one of: symfony/var-dumper[v3.4.10, v4.2.1].
    - Can only install one of: symfony/var-dumper[v3.4.11, v4.2.1].
    - Can only install one of: symfony/var-dumper[v3.4.12, v4.2.1].
    - Can only install one of: symfony/var-dumper[v3.4.13, v4.2.1].
    - Can only install one of: symfony/var-dumper[v3.4.14, v4.2.1].
    - Can only install one of: symfony/var-dumper[v3.4.15, v4.2.1].
    - Can only install one of: symfony/var-dumper[v3.4.16, v4.2.1].
    - Can only install one of: symfony/var-dumper[v3.4.17, v4.2.1].
    - Can only install one of: symfony/var-dumper[v3.4.18, v4.2.1].
    - Can only install one of: symfony/var-dumper[v3.4.19, v4.2.1].
    - Can only install one of: symfony/var-dumper[v3.4.2, v4.2.1].
    - Can only install one of: symfony/var-dumper[v3.4.20, v4.2.1].
    - Can only install one of: symfony/var-dumper[v3.4.3, v4.2.1].
    - Can only install one of: symfony/var-dumper[v3.4.4, v4.2.1].
    - Can only install one of: symfony/var-dumper[v3.4.5, v4.2.1].
    - Can only install one of: symfony/var-dumper[v3.4.6, v4.2.1].
    - Can only install one of: symfony/var-dumper[v3.4.7, v4.2.1].
    - Can only install one of: symfony/var-dumper[v3.4.8, v4.2.1].
    - Can only install one of: symfony/var-dumper[v3.4.9, v4.2.1].
    - Installation request for symfony/var-dumper (locked at v4.2.1) -> satisfiable by symfony/var-dumper[v4.2.1].
```

I don't understand what is going wrong here. drush/drush is the ONLY package that has been explicitly installed. So surely, updating it should work? There is nothing else to set constraints on it.

The output is really hard to make sense of:

- Why does it *begin* with 'conclusions'?
- Why does 'Installation request for drush/drush ^9.5.0 -> satisfiable by drush/drush' then lead to 'Conclusion: don't install symfony/var-dumper'? What's the connection between these two statements?
- Why does it say 'Installation request for symfony/var-dumper (locked at v4.2.1)'? Who's locked it at that version? Certainly not me! I've not requested that package explicitly, it's merely a dependency of drush/drush!

Output of `composer diagnose`:

```
composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.0
PHP version: 7.2.8
PHP binary path: /Applications/MAMP/bin/php/php7.2.8/bin/php
```

**Comment by chriskapp** [comment]
Hi, I have also the same problem. I have a package which is at version "v2.1.4" but through a normal `composer install` on travisci it always installs version "v2.1.3" https://travis-ci.org/apioo/fusio-impl/jobs/472068828

as a workaround I run now `composer update [my_package]` which then fetches the latest version. But I still wonder why it does not install the latest version on `composer install`.

Through `composer why [my_package]` I have the following version constraints:

```
[package_a] v3.0.3  requires  [my_package] (^2.1)
[package_b] v4.1.3  requires  [my_package] (^2.0)
```

**Comment by xabbuh** [comment]
@joachim-n For some reason, Drush was compatible with the VarDumper component version 4 in 9.4.0, but requires 3.4 in 9.5.0. Thus, to be able to update Drush the VarDumper component needs to be downgraded. You can do so by adding the `--update-with-dependencies` option:

```
$ composer require drush/drush ^9.5.0 --update-with-dependencies
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 1 removal
  - Removing symfony/polyfill-php72 (v1.10.0)
  - Downgrading symfony/var-dumper (v4.2.1 => v3.4.20): Downloading (100%)         
  - Updating drush/drush (9.4.0 => 9.5.2): Downloading (100%)         
Writing lock file
Generating autoload files
```

**Comment by joachim-n** [comment]
I've just hit the same problem with updating acquia/blt from 9.1.3 to 9.1.7.

The problem is that 9.1.3 has:

```
        "typhonius/acquia-php-sdk-v2": "dev-master",
```

whereas 9.1.7 has:

```
        "typhonius/acquia-php-sdk-v2": "^1.0.3",
```

There's no output from Composer that explains the problem, which is very confusing.

Running why-not with a specific version number hints at the problem, but you need to know that downgrading a required package is actually something that's problematic to make sense of it:

```
composer why-not acquia/blt 9.1.7
acquia/blt                   9.1.7                                    requires          typhonius/acquia-php-sdk-v2 (^1.0.3)
my/project  dev-mybranch  does not require  typhonius/acquia-php-sdk-v2 (but dev-master is installed)
```

In light of the UX issue here, could this issue be changed back to a bug please?

**Comment by joachim-n** [comment]
Though actually, I've tried doing `composer require drush/drush ^9.5.0 --update-with-dependencies` as suggested above, and the problem with that is that is is updating lots of completely unrelated packages.

**Comment by joachim-n** [comment]
The way I got this to work in the acquia/blt case was with:

```
composer update acquia/blt typhonius/acquia-php-sdk-v2
```

-- explicitly asking composer to update the problematic dependency as well. But having to specify dependencies like this sort of goes against the point of a package manager!

**Comment by Seldaek** [comment]
@joachim-n you could've done with `composer update acquia/blt --with-dependencies` probably.

**Comment by Seldaek** [comment]
Ah sorry I see you tried that, but yes in that case it updates all the dependencies of the package, so it can have a broader effect than you'd like. So specifying the exact packages to update is the way to go.
