### ISSUE TITLE
composer failed to require server

### ISSUE THREAD

**Issue by yossepbb** [composer/composer#7859]
My `composer.json`:

{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "sensio/framework-extra-bundle": "^5.1",
        "symfony/asset": "4.2.*",
        "symfony/console": "4.2.*",
        "symfony/dotenv": "4.2.*",
        "symfony/expression-language": "4.2.*",
        "symfony/flex": "^1.1",
        "symfony/form": "4.2.*",
        "symfony/framework-bundle": "4.2.*",
        "symfony/monolog-bundle": "^3.1",
        "symfony/orm-pack": "*",
        "symfony/process": "4.2.*",
        "symfony/security-bundle": "4.2.*",
        "symfony/serializer-pack": "*",
        "symfony/swiftmailer-bundle": "^3.1",
        "symfony/translation": "4.2.*",
        "symfony/twig-bundle": "4.2.*",
        "symfony/validator": "4.2.*",
        "symfony/web-link": "4.2.*",
        "symfony/yaml": "4.2.*"
    },
    "require-dev": {
        "symfony/debug-pack": "*",
        "symfony/maker-bundle": "^1.0",
        "symfony/profiler-pack": "*",
        "symfony/test-pack": "*",
        "symfony/web-server-bundle": "4.2.*"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "paragonie/random_compat": "2.*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "4.2.*"
        }
    }
}

**Comment by yossepbb** [comment]
When i run composer require server --dev it fails and says that it couldn't find package server.
I checked out the composer.json file and apparently nothing's  wrong .

I am using Symfony 1.1.3 on windows 7

Can you help me please

**Comment by xabbuh** [comment]
Can you show the full output?

**Comment by yossepbb** [comment]
yes of course
![composer](https://user-images.githubusercontent.com/33312886/50489758-d077b400-0a09-11e9-9db6-79a8c087f4d2.PNG)

**Comment by xabbuh** [comment]
`server` is an alias for another package which is resolved by Symfony Flex. Could it be that you ran the command without having your dependencies installed? If so, does it help if you run `composer install` before?

**Comment by yossepbb** [comment]
I did it and i still have the same result

**Comment by yossepbb** [comment]
I want to develop with php maybe i should require php censor package?

**Comment by yossepbb** [comment]
It Finally works. I restart my laptop.
Thanks Guy!!!! :+1:
