### ISSUE TITLE
Support Proxy-Authenticate: Negotiate

### ISSUE THREAD

**Issue by Drabuna** [composer/composer#7872]
Composer version 1.7.3

I'm behind corporate proxy server - which is squid/3.5.12.
Authentication method: Negotiate

With curl I can do something like `curl --proxy-negotiate --U : http://whatever`, and it will work fine.
When trying to do `composer diag`, I get:

```console
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: WARNING
[Composer\Downloader\TransportException] The "http://repo.packagist.org/packages.json" file could not be downloaded (HTTP/1.1 407 Proxy Authentication Required)
```

The reason for that is most likely in StreamContextFactory.php, when doing:
`$options['http']['header'] = array("Proxy-Authorization: Basic {$auth}");`

It would be nice to have a way of configuring what type of Proxy-Authorization to use, so I can specify 'Proxy-Authorization: Negotiate'.

**Comment by alcohol** [comment]
Feel free to submit a PR.

**Comment by Seldaek** [comment]
I have no idea if PHP streams support this, so for 1.x it might be impossible to implement. If the PHP curl extension supports it, it might be feasible for 2.0, but to be honest I have no idea how this Negotiate stuff works so indeed I'd tend to say feel free to submit a PR..

**Comment by Seldaek** [comment]
Closing as I don't think we will ever do anything here.
