### ISSUE TITLE
Add a warning on update & install if the require section contains invalid package names

### ISSUE THREAD

**Issue by naderman** [composer/composer#7874]
We already do stricter validation of package names on packagist.org and composer validate/init, but there's a bit of a mix in what is supported or not. To make this clearer Composer 2.0 should error if there are invalid package names in the name of the package or the require/require-dev/provide/replace/conflict/suggest sections. To prepare for this change we should add a warning to Composer 1.x ASAP.

On composer commands (require, install, update, ...) display a warning if any packages mentioned in composer.json do not strictly match the format for package names (containing exactly one slash, unless platform package, ascii alphanumeric characters only - all lower case?)

**Comment by craue** [comment]
I'm getting a warning about requiring `ext-pdo_mysql` now. Is this intended?

**Comment by Seldaek** [comment]
@craue shit no this isn't, I forgot underscores.. Feel free to ignore I'll get a patch out.

**Comment by kukulich** [comment]
Perfect, I just find the same issue :)

**Comment by Seldaek** [comment]
OK 1.8.2 is out

**Comment by craue** [comment]
👍 that was quick

**Comment by mkopinsky** [comment]
What is the expected (approximate) release schedule for 2.0? Just trying to figure out how long I have before I need to fix my package names so things don't break.

(I imagine lots of people are going to be asking that question when they see the new warning, so it may make sense to put it somewhere obvious - I really couldn't find a good place to ask other than this issue.)

**Comment by Seldaek** [comment]
@mkopinsky in the next few months hopefully, but to be honest it depends on how fast things progress. In any case do fix your packages whenever you can, those deprecated package names were not allowed on packagist.org anyway so any public package won't have an issue. Private packages/ecosystems are much more controlled so I expect you can migrate at your own pace and if needed even force people to stick to Composer v1 until you migrated fully.

**Comment by staabm** [comment]
do we need to only change the `require`-section of the consuming packages or also the `name` of the packages itself?

**Comment by naderman** [comment]
@staabm Both should be changed.

**Comment by staabm** [comment]
thx @naderman. atm our implementation indirectly depends on the package name, because we use filesystem paths, which no longer work when lowercasing the package-name.

is there a composer property which allows me to configure the folder namen under which composer will checkout the package into the vendor/ dir?

atm. it is vendor/$package-name but since my code depends on the case-sensitive name of $package-name lowercasing the name will break this filesystem paths assumption.. :(

**Comment by naderman** [comment]
Not quite sure how to put on words the level of facepalming here ;-)

Anyway, if you want to customize the installation path of a dependency, you can use a custom installer Composer plugin: https://getcomposer.org/doc/articles/custom-installers.md

**Comment by staabm** [comment]
> Not quite sure how to put in words the level of facepalming here ;-)

its not that bad ;-).

as an example: in case one uses something like `require 'vendor/myPackageIsUppercase/config.php'` inside the root-package you cannot just rename the package to uppercase anymore.
