### ISSUE TITLE
Enforce valid package names in name/require/require-dev/provide/replace/conflict/suggest

### ISSUE THREAD

**Issue by naderman** [composer/composer#7875]
After the warning introduced via https://github.com/composer/composer/issues/7874 - we should error on all composer commands (update, install, require, ...) if any package name in composer.json is invalid (name/require/require-dev/provide/replace/conflict/suggest) - we should probably not error on upper case letters as they are too widely spread but keep the warning for this case.

**Comment by Seldaek** [comment]
Should consider #7975 before moving ahead here.
