### ISSUE TITLE
Show warning if highest version can't be installed

### ISSUE THREAD

**Issue by tikoflano** [composer/composer#7876]
First of all Thanks to all Composer contributors, what an amazing tool it is.

Now, it would be great if on `composer update` could show a warning when you can't use the latest version defined in your constraints because of other constraint. For example:

```
"require": {
   "php": ">=5.5.9",
   "doctrine/orm": "^2.5"
},
```

At the time, the latest "doctrine/orm" version satisfied by the constraint is v2.6.3, but composer won't install it because it needs "php" 7.1 or higher. Instead it installs "doctrine/orm" v2.5.14. 

As `"v2.5.14" !=="v2.6.3"` it could throw a warning letting me know the situationso I could say "Oh, I'm missing some new functionalities because of my PHP version, maybe I should update my system to work with php 7.1".

I came across this problem when trying to use some functions from "doctrine/orm" that were implemented in v2.6.0 and I couldn't understand why I didn't have that version if my restrictions in my composer.json file did allowed it. I had to manually read the restrictions of that package to finally understant the problem. Composer could have helped me from the start.

**Comment by alcohol** [comment]
See https://getcomposer.org/doc/03-cli.md#outdated and https://getcomposer.org/doc/03-cli.md#prohibits-why-not-
