### ISSUE TITLE
Can not downgrade particular "symfony/symfony" package when using composer 1.8 (composer 1.6 is fine)

### ISSUE THREAD

**Issue by lzakrzewski** [composer/composer#7881]
My composer.json (everything works fine with composer 1.6)
```json
// ...
        "symfony/symfony": "4.1.*",
        "symfony/yaml": "3.4.*",
// ...
```

when I try to `composer install` using composer to 1.8 then I see an error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/symfony v4.1.1 -> satisfiable by symfony/symfony[v4.1.1].
    - don't install symfony/yaml v3.4.12|don't install symfony/symfony v4.1.1
    - Installation request for symfony/yaml v3.4.12 -> satisfiable by symfony/yaml[v3.4.12].
```

In order to make it working fine with composer 1.8 I just need to upgrade symfony/yaml to 4.1 so my composer.json will look like this:

```json
// ...
        "symfony/symfony": "4.1.*",
// ...
```

I saw a few similar issues so I decided to post my example of fixing this. 
BTW, is this an expected behavior of composer 1.8? 
I guess downgrading packages of symfony/symfony framework is not a good idea right? 
(I had to do it in the past due to some infrastructure limitations that are already fixed now)

**Comment by alcohol** [comment]
We fixed some issues that previously allowed users to (erroneously) install `symfony/symfony` side-by-side with `symfony/<component>` in conflicting versions. You should either use `symfony/symfony` only or specify all `symfony/<component>` packages that you need and do not rquire `symfony/symfony` at all.
