### ISSUE TITLE
Composer takes unnecessarily long time to check for PHP version

### ISSUE THREAD

**Issue by YetiCGN** [composer/composer#7885]
My `composer.json`:

```json
[...]
    "require": {
        "php": "~7.1",
[...]
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
[... irrelevant ...]
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.0
PHP version: 7.0.32
PHP binary path: /usr/bin/php7.0
```

When I run this command:

```
composer update --profile
```

I get the following output:

```
[6.1MB/0.00s] Loading composer repositories with package information
[6.4MB/0.22s] Updating dependencies (including require-dev)
[2064.7MB/49.18s] Your requirements could not be resolved to an installable set of packages.
[2064.7MB/49.18s]
  Problem 1
    - This package requires php ~7.1 but your PHP version (7.0.32) does not satisfy that requirement.

[402.8MB/50.28s] Memory usage: 402.82MB (peak: 2064.73MB), time: 50.28s
```

Why does Composer need to calculate for 50 seconds with 2 GB of RAM to find out that my PHP version is too low? On another run it was 70 seconds. Why isn't that one of the first checks before any dependency version constraints get evaluated? If my application `composer.json` defines platform constraints the solver should fail fast and not build the dependency graph first. Or is it a feature to output all encountered problems? Then I would suggest to add a switch like `--fail-fast` so users can control whether to wait for a minute for a simple PHP version check or get all problems at once.

**Comment by xabbuh** [comment]
The reason probably is that it does not necessarily have to be the root requirements that don't match your platform, but it could as well be any of the required packages that leads to this failure.

**Comment by YetiCGN** [comment]
@xabbuh Well, in that case I'd be totally fine with the following order:
1. Check root platform requirements, fail if they're not met.
1. Check dependency platform requirements, fail if they're not met.
1. Check dependency version constraints.

**Comment by alcohol** [comment]
@YetiCGN I think you will just have to learn to be fine with the way things work currently. Platform packages are treated the same as other dependencies and we only resolve the dependency tree once.

**Comment by YetiCGN** [comment]
Okay. The more I think about it, the more I realize that it's probably a micro-optimization for a rare edge case with possible side effects for other users.

**Comment by apfelbox** [comment]
@YetiCGN please note that 

> 2. Check dependency platform requirements, fail if they're not met.

can not work, as the platform requirements of the dependencies might change between different versions of the package. So you really need to check all of the requirements (platform + dependencies) all at once.

So you could only extract checking the root platform requirements, which will bring a highly faster error check in case of a mismatch, but doesn't change much in the grand scheme of things, I guess. 😉

**Comment by YetiCGN** [comment]
@apfelbox What do you mean by

> the platform requirements of the dependencies might change between different versions of the package

? I am assuming an application context here, not a library's `composer.json`. In that case you would just take all the packages and iterate them to see whether the PHP version checks out and whether all required extensions are installed. Done, right?

**Comment by apfelbox** [comment]
@YetiCGN 

Yeah, but the version number and the required extension may depend on the version.

Take for example `doctrine/orm`: version 2.5.x requires PHP 5.4+, 2.6.x requires PHP 7.1+.
So if you have the constraint `"doctrine/orm": "^2.5"` you can't easily check whether your system running PHP 5.6 fulfils the requirements, as it depends on which version of doctrine will be installed.

So if one of the other packages conflicts with `doctrine/orm 2.5.x` your 5.6.x might not match the requirements.

All the requirements of the package (like PHP version, required extension and even possibly the extension versions) depend on the concrete package versions that could potentially be installed. And the concrete package versions itself might depend on the platform requirements (like on PHP 7.1 you can only install `doctrine/orm 2.6+`), so both these dependencies on packages and on the platform are interweaved with each other.

**Comment by YetiCGN** [comment]
I see now. Thanks for the clarification! I'm convinced now, this was not a good idea. 😉
