### ISSUE TITLE
JSON Output Support for the Actions install and update

### ISSUE THREAD

**Issue by strausmann** [composer/composer#7887]
For the "composer install" and "composer update" actions, I miss the Format option to see the output of the actions, e.g. Also available in JSON format.

**Comment by alcohol** [comment]
That is probably because they were never implemented, due to the complexity of the output that they generate.

**Comment by Seldaek** [comment]
This will probably become more feasible in v2, but it's not exactly high priority either IMO.

**Comment by Seldaek** [comment]
Closing, this is just too much work for what it's worth IMO, especially given there is seemingly not much interest. One can diff composer.lock before/after for programmatically handling changes like we do for https://packagist.com/features/update-review for example.
