### ISSUE TITLE
Composer never finish when called inside scripts

### ISSUE THREAD

**Issue by marcospassos** [composer/composer#7888]
When I run the command below, the script stops at `composer install` and never finishes. I tried starting two installations at the same time and it also not worked. Is there any limitation about running composer in parallel?

`composer.json`
```json
{
    "scripts": {
        "test": [
            "@composer install",
            "./run-tests.sh"
        ]
    }
}
```

`run-tests.sh`
```bash
cd "packages/foo"
composer install
phpunit
```

**Comment by Dzhuneyt** [comment]
You should try running the command with the `-vvv` argument to see extra verbose logs. There might be a permission issue or some other issue that prevents the composer command from proceeding normally.

Also, you mentioned "in parallel", but I don't see in the above example two instances of the command running in parallel?
