### ISSUE TITLE
Wrong CWD with PHP ZTS during create-project

### ISSUE THREAD

**Issue by Sweetchuck** [composer/composer#7890]
My `composer.json`:
The whole project is in a private Git repository, and uses a package which also hosted in a private repository. (not the private repository the problem)
```json
{
  "name": "my/template-01",
  "repositories": {
    "foo/bar": {
      "type": "git",
      "url": "git@example.com:foo/bar.git"
    }
  },
  "require": {
    "foo/bar": "dev-something"
  }
}
```

Output of `composer diagnose`:

```
PHP version: 7.2.12 with ZTS !
```

When I run this command:

```
cd /a/b
composer create-project my/template-01 /a/b/instance-01
```

I get the following output:

```
  - Installing foo/bar (dev-something abcdefg): Cloning abcdefg from cache
                                                                                                                                                  
  [RuntimeException]                                                                                                                              
  Failed to execute git checkout 'abcdefg_LONG_HASH' -- && git reset --hard 'abcdefg_LONG_HASH' --  
                                                                                                                                                  
  fatal: not a git repository (or any parent up to mount point /)                                                                              
  Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set). 
```

And I expected this to happen:
Gather all the dependencies without any problem :-)

I have PHP 7.2.12 with NTS and ZTS as well.
This problem only occurs when I use the one with ZTS.

The `composer create-project` differs from the `composer install` command, because in the terminal the `$PWD` is different than the new project directory will be. Most likely the new project directory not even exists at the moment when you run the `composer create-project` command.

In the `\Composer\Downloader\GitDownloader::updateToCommit()` the `$path` contains a path which is relative from the PHP `getcwd()`, but the PHP `getcwd()` is different from the current directory used in the `$this->process->execute()`.

When I add the following lines:
```php
var_dump('getcwd() = ' . getcwd());
var_dump("\$path = '$path'");
var_dump('`pwd` = ' . trim(`pwd`));

$this->process->execute('pwd', $output);
var_dump('$this->process->execute("pwd") = ' . trim($output));

$this->process->execute('ls -la', $output, $path);
var_dump('$this->process->execute("ls -la") = ' . trim($output));
```
The output is:
```
"getcwd() = /a/b/instance-01"
"$path = 'vendor/foo/bar'"
"`pwd` = /a/b/instance-01"
"$this->process->execute("pwd") = /a/b/instance-01"
"$this->process->execute("ls -la") = total 0
drwxr-xr-x  4 me users  80 Jan 13 18:18 .
drwx------  8 me users 180 Jan 12 17:03 ..
drwxr-xr-x 10 me users 440 Jan 13 18:18 instance-01
```

The outputs from `$this->process->execute("pwd")` and `$this->process->execute("ls -la")` are contradictory.
If the current directory is `/a/b/instance-01` then an `instance-01` child directory should not be there.

With the following modification both the PHP NTS ans ZTS work.
(I will create Pull request soon)
```PHP
$command = sprintf($template, ProcessExecutor::escape($gitRef));
if ($path) {
    $command = sprintf('cd %s && %s', ProcessExecutor::escape($path), $command);
}

if (0 === $this->process->execute($command, $output)) {
    return;
}
```

Others are also having problem which might be related to this.

acquia/lightning-project#17

**Comment by Sweetchuck** [comment]
The workaround is to step into the destination directory before you run the `composer create-project` command, and you have to provide the second (directory) argument as well.
In this case the _current directory_ will be the same in every context.

```bash
rm -rf my-project-01
mkdir my-project-01
cd my-project-01
composer create-project "vendor01/project01" .
```
Note the `.` (dot) at the end.

**Comment by alcohol** [comment]
Your issue report and pull request look a bit disjointed. Also your problem seems to indicate there might be a bug in the Symfony Process class (specifically the `execute()` method and its third argument). Rather than working around this potential bug, I suggest you attempt to solve it on the right end.

**Comment by alcohol** [comment]
The issue you referenced however hints a bug in the `CreateProjectCommand` class and how the `chdir` might not properly propagate to later install steps.

This really needs a simplified reproducible scenario though to fix properly.

**Comment by Sweetchuck** [comment]
I don't get your point

**Comment by Sweetchuck** [comment]
https://github.com/symfony/process/blob/master/Process.php#L153

**Comment by Sweetchuck** [comment]
No.
They dealing with ZTS and current directory only if the `$cwd` is not provided from outside.
`if (null === $this->cwd && (\defined('ZEND_THREAD_SAFE') || '\\' === \DIRECTORY_SEPARATOR)) {`

**Comment by Seldaek** [comment]
Right, but we do give a path, so according to the comment in there, this shouldn't be a problem..

**Comment by Sweetchuck** [comment]
> but we do give a path
Yes, you give a path, which is a relative path, but it is not relative from the current directory.

**Comment by Seldaek** [comment]
Ok.. could you try if removing the `Platform::isWindows()` check from GitDownloader::normalizePath fixes it for you? Because this is turning the path into an absolute path on Windows.

**Comment by alcohol** [comment]
> Yes, you give a path, which is a relative path, but it is not relative from the current directory.

What do you mean?

When you create project with destination `/a/b/instance-01`, then `vendor/foo/bar` would be the correct relative path for installing a dependency because `create-project` will `chdir` into `/a/b/instance-01` after installing the root package.

**Comment by Sweetchuck** [comment]
```
cd /a/b
composer create-project my/template-01 /a/b/instance-01
```
The initial PHP process started from the `/a/b` directory.
The current directory of `proc_open()` stays there (/a/b) even if you ran a `chdir('/a/b/instance-01')` earlier.

**Comment by alcohol** [comment]
But as I now understand it, that only happens on ZTS?

**Comment by Seldaek** [comment]
@Sweetchuck I can't reproduce what you say about us using relative paths.. I only see absolute paths being passed in. Please run the create-project command again with `-vvv` and share the full output here (or at least the `Executing command` lines that precede the exception).
