### ISSUE TITLE
Connection timed out with Docker

### ISSUE THREAD

**Issue by yi01184** [composer/composer#7893]
I'm total newbie to composer(and docker) and trying to install it via Docker on a company server. 
I'm using the offical guide from https://hub.docker.com/r/composer/composer/.
Sadly it always fails at step 3 

My `composer.json`:
{
    "require": {
        "monolog/monolog": "1.0.*"
    }
}

Output of `composer diagnose`:

Current working directory: '/srv/docker/devops_sandbox/composer'
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/app): git branch --no-color --no-abbrev -v
Executing command (/app): git describe --exact-match --tags
Executing command (/app): git log --pretty="%H" -n1 HEAD
Failed to initialize global composer: Composer could not find the config file: /composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 1.2.0 (2016-07-19 01:28:52) with PHP 7.0.7 on Linux / 4.4.131-94.29-default
Checking composer.json: Reading ./composer.json
FAIL
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: Executing command (CWD): git config color.ui
OK
Checking http connectivity to packagist: Downloading http://packagist.org/packages.json
Warning: Accessing packagist.org over http which is an insecure protocol.
 FAIL
[Composer\Downloader\TransportException] The "http://packagist.org/packages.json" file could not be downloaded: failed to open stream: Connection timed out
Checking https connectivity to packagist: Downloading https://packagist.org/packages.json
Downloading https://api.github.com/rate_limit
FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: Connection timed out
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: failed to open stream: Connection timed out
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint:***
Dev Public Key Fingerprint: ***
OK
Checking composer version: Downloading https://getcomposer.org/versions

  [Composer\Downloader\TransportException]
  The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: Connection timed out

As far as I understand this means that my proxy settings are wrong, but where do I need to set them?
Other docker applications use the variables set in"env |grep proxy". Why doesn't composer use them?

A similar issuse may be #4142, but as far as I know is that we don't work with ipv6.

Hope you can help me 

Cheers

**Comment by alcohol** [comment]
Can't help you if you do not provide us with more useful information. For example, what container are you running? Are you using our [official container](https://hub.docker.com/_/composer)? Are you building your own, and if so, where can we see your `Dockerfile`?
