### ISSUE TITLE
Meta: Extend Composer and Packagist to add a "security release" release flag, "security release -only" update flag

### ISSUE THREAD

**Issue by damienmckenna** [composer/composer#7894]
I'd like to propose that Composer and the Packagist platform be extended to support security-only updates.

Use case: as a project owner I would like to only update the codebase when there are security updates available.

This would involve updates to both systems and I'm sure there's a lot of pieces to the puzzle, so I'm calling this a "meta" issue as the pieces are worked out.

I see there being three main parts that would need to be extended:

1. composer.json would need a way of indicating that a specific release was a security update.
1. Composer would need an argument on `update` to only do security updates.
1. Packagist would need a way of indicating that a specific update was a security update.

Thoughts?

**Comment by CashWilliams** [comment]
https://github.com/composer/packagist/issues/335

**Comment by alcohol** [comment]
Extremely unlikely to ever happen.

**Comment by damienmckenna** [comment]
I updated the request to indicate a specific use case:

> Use case: as a project owner I would like to only update the codebase when there are security updates available.

*Many* software projects are in what could be considered "maintenance-only" mode in that the owners only wish to deal with security problems and not other run-of-the-mill updates. There isn't any current way of handling this in the Composer/Packagist ecosystem and there should be.

**Comment by alcohol** [comment]
It's called patch releases., As in `major`.`minor`.`patch`.

**Comment by damienmckenna** [comment]
The semver system on its own does not in any way account for additional meta data, e.g. "is a security release", there's no way of telling that updating one dependency will fix a critical XSS bug in your project and needs to be applied immediately.

**Comment by alcohol** [comment]
I misread your comment as in being from the perspective of a software project that wants to release a security update. But I understand now that you mean it from the perspective of a software project that only wants to install security updates of their dependencies.

That brings me back to my original statement;

> Extremely unlikely to ever happen.

**Comment by xabbuh** [comment]
@damienmckenna You may want to take a look at https://github.com/FriendsOfPHP/security-advisories and https://github.com/Roave/SecurityAdvisories.

**Comment by prisis** [comment]
@damienmckenna or on this one https://github.com/narrowspark/automatic-security-audit

**Comment by damienmckenna** [comment]
But why can't Composer/Packagist handle those directly, why not have it built in?

**Comment by Seldaek** [comment]
Another thing to consider is.. if you only do security updates.. what happens when the version you're using stops being maintained? Should security updates include new major versions? I don't think it's possible to reach a point where you can simply ignore the ecosystem, update blindly and magically get everything to work well and securely.

You need to have some involvement with the projects you are using.
