### ISSUE TITLE
Allow disabling cache via command line

### ISSUE THREAD

**Issue by wyqydsyq** [composer/composer#7895]
Re-open of https://github.com/composer/composer/issues/1896

There is a very valid use case for wanting to completely disable the cache - Docker.

Best practices for building slim Docker images are to disable or clear caches for all package managers. There is absolutely zero benefit from having cached packages in a Docker image, it just consumes space.

We can of course delete the cache files after in a seperate command - however it seems pretty standard for modern package managers to now offer this as a CLI option, see: [PIP](https://pip.pypa.io/en/stable/reference/pip_install/#caching), [APK](https://github.com/gliderlabs/docker-alpine/blob/master/docs/usage.md#disabling-cache), [Yarn is also looking at implementing it](https://github.com/yarnpkg/rfcs/pull/53).

**Comment by alcohol** [comment]
I do not understand how Docker is "a very valid" use-case. I use Docker extensively and the Composer cache is not an issue, especially since multi-stage builds were introduced. Your production container should only contain your build artifact anyway, there shouldn't be anything related to Composer inside of it if you are doing it right.

**Comment by Dzhuneyt** [comment]
Already solved in pull request https://github.com/composer/composer/pull/7880

Feel free to review the code and mark it as approved if you think it makes sense. That would bring it closer to release.

**Comment by Dzhuneyt** [comment]
I agree, but following the discussion in https://github.com/composer/composer/issues/6650 and more specifically - your comment (https://github.com/composer/composer/issues/6650#issuecomment-326901913), I was under the impression that such a feature will be useful.

@Fleshgrinder correctly pointed out in his comment 

> Users need to find that out on their own, instead of simply getting the answer from composer --help.

I believe that having this feature as "built-in" AND crossplatform out of the box, is much better than resorting to undocumented tricks with setting environment variables in the command line.

**Comment by alcohol** [comment]
Indeed, they are documented and they are also cross platform.. anyway, a flag that does exactly the same does not hurt I guess. It's only a few lines of code. And if it makes some people happy for some reason, that's a win I guess :man_shrugging:

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/pull/7880
