### ISSUE TITLE
How can I force Composer to use a given path repository or find out why it won't?

### ISSUE THREAD

**Issue by TravisCarden** [composer/composer#7899]
**Summary:** I need to ensure that a path repository is used for a given package. When it isn't, I need to know why so I can fix it.

**Details:** As in #7847, I'm working on a testing framework for my company's packages that relies on path repositories. And while it works well most of the time, sometimes I still have problems getting Composer to use a path repository. When these cases arise, troubleshooting is very difficult. I have identified a number of preconditions I can test for*, but apparently, I'm still missing some.

**Request:** I need to force Composer to use my path repositories. If there's a way to do that, great! If not, I need to know the necessary preconditions for selecting a repository so I can ensure them. A way to ask Composer why it didn't use a given repository would be ideal, though I recognize that may be a somewhat obscure need. How would you recommend I solve my problem?

\* For reference, below are the preconditions I've identified so far:

1. The project `composer.json` must contain the path repository specification.
1. The project must require `vendor/package:@dev`.
1. The package must exist at the specified location and be readable.
1. The package must contain a valid `composer.json` with a `name` value matching the project requirement.
1. The package must (be made to) satisfy any version constraints with one of the following methods. (I haven't found a good way to automatically test for this one yet.)
    * A [branch alias](https://getcomposer.org/doc/articles/aliases.md#branch-alias)
    * A corresponding VCS branch checked out
1. The project requirement must have no conflicting version constraints. (Easily testable using `composer why-not`.)

**Comment by alcohol** [comment]
2. is wrong, generally it's better to use `*` as a constraint.

**Comment by TravisCarden** [comment]
Thank you, @alcohol, but if I switch from `@dev` to `*`, the path repositories it _is_ finding for me stop working.

Any thoughts on the overall question: how to force Composer to select a given repository?

**Comment by TravisCarden** [comment]
I've come up with a reasonably effective solution for my needs, which I'll share in case it helps anyone else. I can't hardcode a branch name (like `dev-master`) because my framework has to support both arbitrary topic branches and pull requests, neither of which lend to prediction. So after playing with wildcards without success, I decided to point Composer at the repository in question and ask it what _it_ thinks it is. My code looks something like the following (simplified for illustration):

```php
class ExampleClass {

  /**
   * This gets injected into my constructor.
   *
   * @var \Composer\Package\Version\VersionGuesser
   */
  private $versionGuesser;

  private function getRepoPackageString(): string {
    $guess = $this->versionGuesser
      ->guessVersion($this->getRepoComposerJsonDataAsArray(), $this->getRepoPath());
    $version = (empty($guess['version'])) ? '@dev' : $guess['version'];
    return "{$this->getRepoPackageName()}:{$version}";
  }

}
```

Paired with appropriate [branch aliases](https://getcomposer.org/doc/articles/aliases.md#branch-alias), this works pretty well so far.

**Comment by stof** [comment]
`@dev` as constraint is effectively a `*@dev` constraint. So that satisfies the recommendation of @alcohol. But for a path repositories, the `@dev` part is generally necessary, as the default minimum-stability of composer rejects dev packages, and path repositories are considered dev versions IIRC.
