### ISSUE TITLE
Composer doesn't seem detect changes in between repository types for a package with the exact same name and version

### ISSUE THREAD

**Issue by hostep** [composer/composer#7908]
Sorry for not following the issue template, because I can't create an easily reproducible case at the moment (because of private packages).

I was able to reproduce this with composer versions 1.4.2 & 1.8.0

So this issue is a weird one, which probably not a lot of people will run into, but here we go.

We have a project with a git repository with multiple branches.

In one branch, our `composer.json` file has a certain repository with type `artifact` and on another branch we have a repository with type `composer`. On both branches the exact same package is being installed, same name and same version but it comes from a different source (`artifact` vs `composer` repo). The `composer.lock` file also contains the correct info for this specific package on both branches (`url` and `shasum` differ as expected)

To reproduce:
Suppose we are first on the branch with the `artifact` repository type and we start from scratch (the `vendor` directory is empty). If we run `composer install` it will do everything as expected, and the `vendor/composer/installed.json` contains the `url` pointing to the `artifact` path for that package.
Now, when we switch to the second branch with the `composer` repository type and we run `composer install`, it will not update the `vendor/composer/installed.json` file with the correct `url` of the package and still use the path to the artifact. Probably because the version hasn't changed for that package in between the two branches. So here lies the bug I assume: composer doesn't seem to detect the change in repository types when a package has the same name and version and doesn't write it to the `installed.json` file.

We have some other packages in this project (also using `artifact` on one branch and `composer` on the other), where the version *is* different in between the 2 branches, and there it works as expected, the `installed.json` file gets updated with the correct info.

Now, you could argue: "there is no problem, if the version is the same, why should we re-install the package?"
Well the problem comes when we then do a `composer update {some-other-package}` or `composer update --lock` on the branch where the `installed.json` file isn't correct, then for some reason, the `composer.lock` file suddenly also contains the incorrect `url` to the package. And then the real problems start for us when people aren't paying close attention to the diff of the `composer.lock` file before committing.
I guess composer uses the info from the `installed.json` file to put it in the `composer.lock` file, which would explain this, could that be?

We can circumvent the problem, by removing the `vendor/composer/installed.json` file after switching branches and before running `composer install`, but that's a bit annoying an we can easily forget to do this.

Hope this description is clear enough so you can try to reproduce the problem? If you need more info, please let me know!

**Comment by hostep** [comment]
To make this a bit more concrete (this is a reverse case of what I explained above, but that doesn't really matter):

- our `composer.json` contains a repo with type `artifact` and has a dependency on a package `vendor/example` which only lives in that `artifact` repo
- the entry for the package `vendor/example` in our `composer.lock` file has an `url` which points to the `artifact` zip file.
- the entry for the package `vendor/example` in our `vendor/composer/installed.json` files has an `url` which points to the a `https` url from the `composer` repo from our other branch (because I just switched branches and the `installed.json` file isn't in our VCS)

When I execute `composer install`, I would expect that the entry for `vendor/example` in the `installed.json` file gets updated, and the `url` from the `composer.lock` file is written to it, but that doesn't happen.

Hope that this makes things a bit more clear here :)

**Comment by hostep** [comment]
Because - as explained in my opening post - the `url` is incorrect in the `installed.json` file, and when that is the case and you run `composer update` it will take that incorrect `url` from the `installed.json` file and put it in your `composer.lock` file.

**Comment by Seldaek** [comment]
As far as I can tell this is fixed in 2.0 branch so I'm going to close this.

**Comment by hostep** [comment]
Excellent, thanks!
