### ISSUE TITLE
symfony/var-dumper doesn't work inside plugin code

### ISSUE THREAD

**Issue by joachim-n** [composer/composer#7911]
I have symfony/var-dumper included in my project and also a composer plugin. Within plugin code, calling dump() causes a crash, as symfony/var-dumper does not appear to have been autoloaded.

So far I've tested:

- activate()
- getSubscribedEvents()
- an subscribed callback that's set in getSubscribedEvents()

**Comment by joachim-n** [comment]
Doing the following in activate() is a workaround:

```
    include './vendor/symfony/var-dumper/Resources/functions/dump.php';
```

Given that var-dumper's composer.json has psr-4 autoloading too, I suspect what's happening is that files autoloading isn't loaded at this point, though psr-4 is.


```
    "autoload": {
        "files": [ "Resources/functions/dump.php" ],
        "psr-4": { "Symfony\\Component\\VarDumper\\": "" },
        "exclude-from-classmap": [
            "/Tests/"
        ]
    },
```

**Comment by stof** [comment]
Well, plugins are running before the full autoloader is generated and loaded. Files autoloading is indeed not working there (because `files` is not actually about autoloading, but about eager-loading, loading the file at the beginning, and this would add lots of complexity when registering plugin one by one after they get installed)

**Comment by alcohol** [comment]
Yeah what @stof said. Plugins use an on-the-fly generated autoloader which does not include anything from any `files` directives.

**Comment by alcohol** [comment]
Your work around is the correct approach to this. Simply check if the function is defined or not, and include the source file if it is not yet defined.

**Comment by joachim-n** [comment]
> loading the file at the beginning, and this would add lots of complexity when registering plugin one by one after they get installed)

Do you mean when plugins are first installed, or simply when they're loaded each time Composer runs?

> Plugins use an on-the-fly generated autoloader which does not include anything from any files directives.

Is there a reason they can't do this?

> Plugins use an on-the-fly generated autoloader which does not include anything from any files directives.

Is this documented?

**Comment by alcohol** [comment]
> Do you mean when plugins are first installed, or simply when they're loaded each time Composer runs?

Each time Composer runs.

> Is there a reason they can't do this?

Composer itself does not use the generated autoloader files, it uses the source for them. And the source does not automatically load `files` directives.

> Is this documented?

Not very explicitly perhaps. It is part of the documentation for scripts:

https://getcomposer.org/doc/articles/scripts.md#defining-scripts (see 'for any given event')

**Comment by joachim-n** [comment]
My workaround has stopped working :(

I get:

```
  [Error]
  Class "Symfony\Component\VarDumper\VarDumper" not found
```

This also happens if I access the class directly, bypassing the dump() function:

```
    VarDumper::dump($installed_tag);
```

What is happening with the autoloader?

**Comment by joachim-n** [comment]
I can fix it if I do:

```
    $autoload = require_once './vendor/autoload.php';
```

in the script.

**Comment by alcohol** [comment]
Hard to tell why without a reproducible example. If you cannot provide this, we cannot help you.

**Comment by joachim-n** [comment]
Steps to reproduce:

1. Create a project with this composer.json:

```
{
    "name": "joachim/test-composer-7911",
    "type": "project",
    "authors": [
        {
            "name": "Joachim Noreiko",
            "email": "joachim@107701.no-reply.drupal.org"
        }
    ],
    "require": {
        "joachim-n/drupal-project-contrib-development": "dev-main",
        "symfony/var-dumper": "^7.0"
    },
    "config": {
        "allow-plugins": {
            "joachim-n/drupal-project-contrib-development": true
        }
    }
}
```

2. Install the packages
3. Open the file vendor/joachim-n/drupal-project-contrib-development/Command/SwitchPackageToGitClone.php and uncomment line 15, `require_once 'vendor/symfony/var-dumper/Resources/functions/dump.php';`
4. Add a `dump()` at the top of the execute() method.
5. Do `composer dc:clone foo` on the command line

Result:

In dump.php line 29:

  [Error]
  Class "Symfony\Component\VarDumper\VarDumper" not found

**Comment by Seldaek** [comment]
The problem is that joachim-n/drupal-project-contrib-development does not require symfony/var-dumper so composer does not make that package autoloadable at runtime when enabling the plugin. So yes if you need the other dependencies in the project you should require the project autoloader.

**Comment by Seldaek** [comment]
Also note that if you do `require_once './vendor/autoload.php';` you won't need the require of dump.php

**Comment by Seldaek** [comment]
Composer only ever makes the project's classes autoloadable (when needed for script handlers) and dependencies as needed for plugins to run. Anything else in not made autoloadable during composer runtime as it doesn't need to be.
