### ISSUE TITLE
change in installer path isn't picked up for a package

### ISSUE THREAD

**Issue by joachim-n** [composer/composer#7915]
I changed the installer path for a package. I was hoping that 'composer update --lock' would take care of moving it.

I'm not sure how to accomplish this, short of removing it and reinstalling it, which will affect other packages.

**Comment by Jean85** [comment]
You can ask to update a single package by appending it to your `composer update` command

**Comment by joachim-n** [comment]
Thanks!

But won't that then also try to increase the version? I don't see an option to the `update` command that will refresh the package while keeping the version the same.

**Comment by joachim-n** [comment]
> You can ask to update a single package by appending it to your composer update command

That's not moving the package to its new specified location.

**Comment by Seldaek** [comment]
The problem is when you remap the path, it doesn't know where to find the old one anymore.. This is due to the fact this stuff is not standard composer but tacked on by a plugin (composer/installers I assume). Changing paths isn't well supported really, and you should avoid doing that if possible.
