### ISSUE TITLE
PSR-4 autoloading only works with dumping optimized autoloader

### ISSUE THREAD

**Issue by dmaicher** [composer/composer#7917]
I have an interesting issue:

I refactored parts of a project that I'm working on and moved some classes into new namespaces (under my `CA` namespace).

I have this PSR-4 autoload config:

```json
    "autoload": {
        "psr-4": {
            "CA\\": "src/CA/"
        }
    }
```

Since the refactoring the autoloading does not work properly without dumping an optimized autoloader.

PhpStan also reports some autoloading issues in that case:

```
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------- 
         Class CA\Core\Bundle\Model\Portal\PortalListInterface was not found while trying to analyse it - autoloading is probably not configured properly.  
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------- 
```

**If I run `composer install -o` everything works just fine.**

I realize its probably hard to diagnose that issue without being able to debug it further... but maybe someone has an idea whats going on? :blush:

**Comment by alcohol** [comment]
Can you give us the exact path to that file? And the header of that file (just the namespace and interface definition line is enough).

**Comment by dmaicher** [comment]
Wow I just noticed the space in the filename:

`src/CA/Core/Bundle/Model/Portal/PortalListInterface .php`

No idea how that got there :man_facepalming: :see_no_evil: 

Renamed it and works fine now. Sorry for wasting your time!
