### ISSUE TITLE
Is the "pear" repository type affected by the recent PEAR security incident?

### ISSUE THREAD

**Issue by saeidw** [composer/composer#7918]
There was a [security incident with the pear.php.net site](https://arstechnica.com/information-technology/2019/01/pear-php-site-breach-lets-hackers-slip-malware-into-official-download/).

I use the "pear" repository type in composer.json like so:

 ```json
  "repositories": [
    {
      "type": "pear",
      "url": "https://pear.php.net"
    }
  ],
...
  "require": {
    ...
    "pear-pear.php.net/DB": "^1.9",
    "pear-pear.php.net/Log": "^1.13",
    "pear-pear.php.net/Mail": "^1.3",
    "pear-pear.php.net/Mail_Mime": "^1.10",
    "pear-pear.php.net/MDB2": "2.5.0b5",
    "pear-pear.php.net/MDB2_Driver_pgsql": "^1.4",
    "pear-pear.php.net/Net_SMTP": "^1.7",
    "pear-pear.php.net/PEAR": "^1.10",
     ...
  },
```

Does Composer use the compromised `go-pear.phar` internally in some way when fetching "pear" packages? My shallow understanding is that I have nothing to worry about but I just wanted to ask to be sure.

In the short term I will be removing the pear dependency from my composer.json. I just wonder if it is necessary to conduct a security audit of my `vendor/` deployment due to this incident?

**Comment by stof** [comment]
On a side note, most of the PEAR packages you depend on here are available on Packagist directly: https://packagist.org/packages/pear/

The `pear` repository type is quite slow (as a pear repository is optimized for pear's needs, not for composer's ones). So if you can remove the need for this repository (I'm not sure `MDB2` is on Packagist, but all others you listed are there), it might still be good for you, by making `composer update` faster (as you would not need to register and load the pear repository).

**Comment by stof** [comment]
However, the usage of this repository in composer will still be affected by the fact that they brought the whole server down (as composer cannot access the packages anymore).

And you may be affected if the hackers also managed to corrupt the archives for packages in addition to `go-pear.phar`. There is no evidence for it yet AFAIK, but the PEAR team has not finished the review yet. Comparing the packages in your `vendor` folder to their codebase on github might still make sense if you want to check that part (most official pear packages have their source in https://github.com/pear/).

**Comment by saeidw** [comment]
Thanks! I will run a comparison on my `vendor/` just to be safe, and possibly switch over to the Packagist packages instead!
