### ISSUE TITLE
[FR] Allow vendor search / wildcard in why command

### ISSUE THREAD

**Issue by kiler129** [composer/composer#7919]
### Current status
When I run `composer why symfony/*` command I get the following output:

```
  [InvalidArgumentException]                          
  Could not find package "symfony/*" in your project  
```

### Proposed functionality
I expected list of all packages by the vendor to appear. This is especially useful in case of security problems discovered in one of the vendor packages. Composer supports such wildcards with `update` command - it will be good to support it with `why` command too.

### Current workaround
For now the `composer show | awk '{print $1}' | xargs -L1 composer why` command can be used. The output is slightly misformatted but readable.

**Comment by stof** [comment]
this would first require adding support for multiple package in the output of `why`. Currently, the command is only meant to provide explanations about a single package. I fear that this might be hard (the output is not always a single line)

**Comment by Seldaek** [comment]
Yup this sounds like not worth adding really as it's kinda easy to call yourself..
