### ISSUE TITLE
Composer is executing twice when uopz and xdebug are enabled

### ISSUE THREAD

**Issue by SunMar** [composer/composer#7921]
Hi,

When both the [User Operations for Zend](https://pecl.php.net/package/uopz) and [XDebug](https://xdebug.org/) extensions are installed, composer executes twice.

Steps to reproduce, start a new docker container with `docker run --rm -it php:7.2-cli bash` and inside run:
```
   pecl install uopz xdebug \
&& curl -sS https://getcomposer.org/installer | php -- --install-dir=/ --filename=composer \
&& export COMPOSER_ALLOW_SUPERUSER=1 \
&& export XDEBUG_HANDLER_DEBUG=1 \
&& echo -en "\nw/o either: " && php composer --version \
&& echo -en "\nonly uopz: " && php -dextension=uopz.so composer --version \
&& echo -en "\nonly xdebug: " && php -dzend_extension=xdebug.so composer --version \
&& echo -en "\nboth: " && php -dextension=uopz.so -dzend_extension=xdebug.so composer --version
```

This will give the output:
```
w/o either: xdebug-handler[7483] Checking COMPOSER_ALLOW_XDEBUG
xdebug-handler[7483] The xdebug extension is not loaded
Composer version 1.8.0 2018-12-03 10:31:16

only uopz: xdebug-handler[7484] Checking COMPOSER_ALLOW_XDEBUG
xdebug-handler[7484] The xdebug extension is not loaded
Composer version 1.8.0 2018-12-03 10:31:16

only xdebug: xdebug-handler[7485] Checking COMPOSER_ALLOW_XDEBUG
xdebug-handler[7485] The xdebug extension is loaded (2.6.1)
xdebug-handler[7485] Process restarting (COMPOSER_ALLOW_XDEBUG=internal|2.6.1|1|*|*)
xdebug-handler[7485] Running '/usr/local/bin/php' '-n' '-c' '/tmp/Sr4H9Q' 'composer' '--version' '--ansi'
xdebug-handler[7487] Checking COMPOSER_ALLOW_XDEBUG
xdebug-handler[7487] Restarted (18 ms). The xdebug extension is not loaded
Composer version 1.8.0 2018-12-03 10:31:16
xdebug-handler[7485] Restarted process exited 0

both: xdebug-handler[7488] Checking COMPOSER_ALLOW_XDEBUG
xdebug-handler[7488] The xdebug extension is loaded (2.6.1)
xdebug-handler[7488] Process restarting (COMPOSER_ALLOW_XDEBUG=internal|2.6.1|1|*|*)
xdebug-handler[7488] Running '/usr/local/bin/php' '-n' '-c' '/tmp/sTXiiX' 'composer' '--version' '--ansi'
xdebug-handler[7490] Checking COMPOSER_ALLOW_XDEBUG
xdebug-handler[7490] Restarted (19 ms). The xdebug extension is not loaded
Composer version 1.8.0 2018-12-03 10:31:16
xdebug-handler[7488] Restarted process exited 0
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Composer version 1.8.0 2018-12-03 10:31:16
```

As you can see in the last scenario it run twice, both in the restarted process without xdebug and in the main process with xdebug (and uopz). This isn't limited to just `--version`, it also applies when doing other commands like `update`.

**Comment by johnstevenson** [comment]
If you set `XDEBUG_HANDLER_DEBUG=1` then xdebug-handler outputs debug info and the pids of the initial and restarted processes. Doing this may help to illustrate the execution flow.

**Comment by SunMar** [comment]
Updated the original description with the `XDEBUG_HANDLER_DEBUG=1` information added to it. It seems to confirm as expected that that composer for some reason is executing its logic in both the parent and the child processes.

**Comment by johnstevenson** [comment]
I don't think that Composer is doing this, rather that it is a side effect of restarting a process when uopz is enabled. But I haven't played with it yet. Perhaps you could show us the new output when `XDEBUG_HANDLER_DEBUG` is set.

**Comment by johnstevenson** [comment]
`xdebug-handler[7488] Restarted process exited 0`

This line is reported by the initial php process, after which xdebug-handler calls exit. So it must be something to do with uopz.

See https://github.com/composer/xdebug-handler/blob/dc523135366eb68f22268d069ea7749486458562/src/XdebugHandler.php#L268

**Comment by johnstevenson** [comment]
Additionally, neither uopz or xdebug are loaded in the restarted process in this example, since xdebug-handler has no knowledge of the command-line arguments used to invoke php. 

Both extensions do things with opcodes , so there is no guarantee that their actions are compatible. Unfortunately I don't think that there is anything that xdebug-handler can do, even if it knows that uopz is enabled, because the duplicate call occurs after `exit` has been called.

**Comment by SunMar** [comment]
@johnstevenson Thanks for the help, I was able to reproduce it with a standalone script and found the reason for the behavior:

http://php.net/manual/en/function.uopz-allow-exit.php

The uopz extension by default disables `exit()`. If you only load uopz and not XDebug, then composer won't try to restart, so it never needs to do an `exit()`, and if you don't load uopz, then `exit()` isn't disabled. So it appears to be expected behavior from the extension. If in my test script I do a call to `uopz_allow_exit(true);` the behavior disappears. The uopz extension isn't one that should be loaded anyways when running composer, I was only just experimenting with it and initially just enabled it globally while trying it out, not bothering with only loading it conditionally when running test suites when it's actually required. It's a bit confusing though that it won't send anything to the log either to indicate an opcode was ignored as it'll change code behavior, but that is something to do with the extension, not composer.

Thanks again for the help :).

**Comment by johnstevenson** [comment]
Fixed in https://github.com/composer/xdebug-handler/releases/tag/1.3.2

@SunMar Thanks for the report and your help.
