### ISSUE TITLE
Error "Package is not installed: ext-mbstring-7.3.1.0" but it's installed

### ISSUE THREAD

**Issue by ebuildy** [composer/composer#7924]
The exception is thrown only if "ext-mbstring" is in the composer.json, under "provide" field, maybe this is the normal behavior?

My `composer.json`:

```json
{
    "require": {
        "alcaeus/mongo-php-adapter":"^1.1",
        "twig/twig": "1.21.1",
        "symfony/......":         "2.8.1",
        "cache/memcached-adapter": "^1.0"
    },
    "autoload": {
        "psr-0": { "": "src/" }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "provide" : {
        "ext-mongo": "*",
        "ext-mbstring": "*",
        "ext-dom": "*"
    }
}

```

Output of `composer diagnose`:

```
Composer version: 1.8.0
PHP version: 7.3.1
PHP binary path: /usr/local/Cellar/php/7.3.1/bin/php
```

When I run this command:

```
composer install --ignore-platform-reqs
```

I get the following output:

```
"Package is not installed: ext-mbstring-7.3.1.0"
```

And I expected this to happen:

Because I run with ``ignore-platform-reqs`` flag, ext-* should be taken in account. Also, ext-mbstring is installed (check with ``php -m | grep mbstring``).

**Comment by alcohol** [comment]
Can you give us the full verbose output of the composer command you are running?

**Comment by alcohol** [comment]
@Seldaek eh this is weird to me, would we ever propose to remove extensions?

**Comment by Seldaek** [comment]
Yeah try using https://getcomposer.org/doc/06-config.md#platform instead of provide..

**Comment by ebuildy** [comment]
Yes it's working if I remove provide entries.

Thanks,
