### ISSUE TITLE
Don't forcefully empty download's destination directory

### ISSUE THREAD

**Issue by drzraf** [composer/composer#7929]
While developing a composer plugin that needs to download and extract tarball, I needed a _Downloader_
Ideally I would like to reuse the traditional chain of `File > Archive > Zip` downloaders.

But a base method of the base class of archive downloaders, `FileDownloader::doDownload` has a problematic behavior : destructive operations on the filesystem:
- emptyDirectory (destination path)
- removeDirectory (cleanup)

My goal is **complementing** a package with an external tarball downloaded and `ZipDownloader` would make a perfect fit... if it wasn't forcefully cleaning the destination directory.
To allow that without duplicating code from all 3 classes, a switch should be implemented to inhibit destination directory cleanups in `doDownload`.

(@drupol)

**Comment by drupol** [comment]
That make sense. It would be a great addition.

**Comment by Seldaek** [comment]
The 2.0 improves this a little already by separating download from install/update, but it is still doing the delete.. which arguably might not need to happen, at least shouldn't happen in the download step. I'll take a look, but this won't be fixed in 1.x

**Comment by Seldaek** [comment]
download() now does not touch the target path anymore, install() from ZipDownloader will still clean up before unarchiving, but you could also extend the class and call download+extract yourself without using install directly.
