### ISSUE TITLE
The requested package could not be found in any version

### ISSUE THREAD

**Issue by Vhaptar** [composer/composer#7939]
Hi,

Could you please help me to fix this ? 
I tried lot of things i found from other issues but nothing worked for me.

My `composer.json`:

```json
{
    "require": {
        "jdchmiel/mongogento": "master"
    },
    "repositories": {
        "mongogento": {
            "type": "vcs",
            "url": "https://github.com/jdchmiel/mongogento/"
        }
    }
}
```

When I run this command:

```
First command : 
composer config repositories.mongogento vcs https://github.com/jdchmiel/mongogento/

Then:
composer require jdchmiel/mongogento:master
```

I get the following output:

```
Problem 1
    - The requested package jdchmiel/mongogento could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

```

Thanks in advance.

Best regards.

**Comment by alcohol** [comment]
Your `type` is wrong.

> `"type": "magento-module",`

Since you declared that it is not a package, you cannot install it.

**Comment by alcohol** [comment]
See https://getcomposer.org/doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md for more details.

**Comment by Vhaptar** [comment]
Thanks for your share.

I followed you advices but still have an error.

So now the json file look like this:
```json
{
    "repositories": {
        "mongogento": {
            "type": "magento-module",
            "url": "https://github.com/jdchmiel/mongogento/",
            "require":{
                "composer/installers": "~1.0"
            }
        }
    }
}
```

But it throw a new error: 

> [Composer\Json\JsonValidationException]
>   "./composer.json" does not match the expected JSON schema:
>    - repositories.mongogento : Object value found, but a boolean is required
>    - repositories.mongogento : Does not have a value in the enumeration [false]
>    - repositories.mongogento.package : The property package is required
>    - repositories.mongogento.type : Does not have a value in the enumeration ["package"]
>    - repositories.mongogento.type : Does not have a value in the enumeration ["composer"]
>    - repositories.mongogento.type : Does not have a value in the enumeration ["vcs","github","git","gitlab","git-bitbucket","hg",
>   "hg-bitbucket","fossil","perforce","svn"]
>    - repositories.mongogento.type : Does not have a value in the enumeration ["path"]
>    - repositories.mongogento.type : Does not have a value in the enumeration ["artifact"]
>    - repositories.mongogento.type : Does not have a value in the enumeration ["pear"]
>    - repositori

> es.mongogento: Failed to match exactly one schema

Thanks in advance for your help.

Best regards.

**Comment by stof** [comment]
`master` is not an existing version for a VCS repo. The version for the `master` branch of the repo will be `dev-master`. That's the issue you have originally.

**Comment by stof** [comment]
@alcohol the `type` in the first snippet is not a package type, but a repository type. `vcs` is the right type there (the package type is found in the composer.json file inside the github repo)

**Comment by alcohol** [comment]
I was referring to the type in the composer.json of his "package", not of his repository definition.

**Comment by alcohol** [comment]
https://github.com/jdchmiel/mongogento/blob/fdee38f4df3839c6cd321fb039fdc89f56fd2646/composer.json#L3

**Comment by Vhaptar** [comment]
Thanks @stof, you got it. 

Now i think it's working properly, i will be able to fix next issues.

> Problem 1
>     - mongodb/mongodb 1.4.2 requires ext-mongodb ^1.5.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.4.1 requires ext-mongodb ^1.5.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.4.0 requires ext-mongodb ^1.5.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.3.2 requires ext-mongodb ^1.4.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.3.1 requires ext-mongodb ^1.4.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.3.0 requires ext-mongodb ^1.4.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.2.0 requires ext-mongodb ^1.3.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.1.2 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.1.1 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.1.0 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.0.5 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.0.4 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.0.3 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.0.2 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.0.1 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
>     - mongodb/mongodb 1.0.0 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
>     - jdchmiel/mongogento dev-master requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 1.4.1, 1.4.2].
>     - Installation request for jdchmiel/mongogento dev-master -> satisfiable by jdchmiel/mongogento[dev-master].
