### ISSUE TITLE
Switching to a dev-branch triggers "update failed"

### ISSUE THREAD

**Issue by mindplay-dk** [composer/composer#7940]
Whenever I switch from a stable release/tag to a dev-branch, I get a very confusing error message.

So I'll make a change like this to `composer.json`:

![image](https://user-images.githubusercontent.com/103348/52041161-dfd2ab80-2539-11e9-945e-8c094c5a54f9.png)

And then run `composer update`:

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 3 updates, 0 removals
  - Updating kodus/score (0.18.10 => dev-asset-delivery 37249de):     Update failed (Source directory /mnt/c/workspace/kodus-media-admin/vendor/kodus/score has unpushed changes on the current branch:
M       UPGRADING.md
M       docs/controllers.md
M       src/Http/Middleware/NotFoundMiddleware.php
A       src/Result/NotFoundResult.php
A       templates/NotFoundPage.text.php
M       tests/integration/RoutingCest.php)
...
```

What's really confusing here, is there are in fact no changes.

If I go to the vendor-folder and do this:

    $ cd vendor/kodus/score
    $ git diff

There is no diff.

I've gotten used to these "false positives" and simply ignore them - but the risk here, is someday I'm going to accidentally delete something that was *actually* a real change.

I'm not sure what's causing this, but if I had to guess... maybe the check for modifications needs to happen against the currently installed tag/branch rather than against the one you're switching to?

Probably this requires an additonal, separate `git` command before switching?

**Comment by mindplay-dk** [comment]
In addition, answering `yes` to "Would you like to try reinstalling the package instead?" usually fails with a `RuntimeException` with the message:

> Source directory /mnt/c/workspace/kodus-media-admin/vendor/kodus/score has unpushed changes on the current branch

Even if it actually had unpushed changes (which it doesn't) you were just made aware of that and prompted to confirm that you want to replace the package.

**Comment by Seldaek** [comment]
Please run the update with -vvv to see what git commands are being executed that result in the warning. Then you can run that yourself to see what the issue stems from.. Unpushed changes !== uncommitted changes, so git diff wouldn't show that.

**Comment by Jimbolino** [comment]
We have the same issue when we switch a dependency in our composer.json from dev-master to dev-develop.
Whenever we commit the `composer.lock` and run a `composer install` on the build server it fails with the same error.

I've run the command with -vvv and there is not much strange:
```
git show-ref --head -d
git diff --name-status composer/master...master --
git fetch composer && git fetch origin
git diff --name-status composer/master...master --
```
When i run a `git status` in the vendor folder it shows us this:
```
$ git status
On branch master
Your branch is ahead of 'origin/master' by 3 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
```
So it has actually merged the origin/develop into the local master ?

**Comment by krixon** [comment]
I have the same problem when switching between `dev-*` branches. I've got the following in my `composer.json`:

```
"config": {
    "preferred-install": {
        "*": "dist"
     }
},
```

So my understanding is that Composer should not be using the git repo itself? However this doesn't appear to be the case. It also doesn't matter if I use `--prefer-dist` from the CLI.

**Comment by stof** [comment]
well, `prefer-dist` is not `force-dist`. If the package does not expose a dist archive, source install will still be used as that's the only available one.

**Comment by krixon** [comment]
Thanks @stof, I guess my understanding of what `dist` means is flawed. I thought it meant that composer would essentially `git archive` rather than pulling from the repo itself to manage changes during install.
