### ISSUE TITLE
Upgrading to silverstripe 4.3 shows “exceeded the timeout of 60 seconds”

### ISSUE THREAD

**Issue by utmsandeep** [composer/composer#7943]
When I run this command it shows an error:

C:\wamp64\www>php upgrade-code.phar recompose --write

Upgrading PHP constraint
========================

 Done.

Rebuilding dependencies
=======================

 ! [NOTE] Trying to re-require all packages

 * Requiring php:">=5.6" ......... ✔
 * Requiring silverstripe/recipe-core:"4.3.0" ....................................................................................... ✔
 * Requiring silverstripe/recipe-cms:"*" .................................................................................................................................... ✔
 * Requiring silverstripe/reports:"*" ............................................................................................................................................... ✔
 * Requiring silverstripe/siteconfig:"*" ............................................................................................................................. ✔
 * Requiring silverstripe-themes/simple:"*" .............................................................................................................................. ✔

In Process.php line 1236:

  The process "composer update --working-dir="C:\Users\PKGUPT~1\AppData\Local\Temp\ss-upgrader-5c53e7ac309a8" --prefe
  r-stable --ignore-platform-reqs --no-plugins" exceeded the timeout of 60 seconds.

recompose [-d|--root-dir ROOT-DIR] [-w|--write] [-S|--strict] [-R|--recipe-core-constraint [RECIPE-CORE-CONSTRAINT]] [--cwp-constraint [CWP-CONSTRAINT]] [-P|--composer-path [COMPOSER-PATH]] [-Q|--quick]

**Comment by stof** [comment]
Well, that's an issue with this upgrade-code.phar tool. Running composer with a timeout of 60 seconds is a bad idea. A `composer update` can often take more than 60 seconds to complete.

This exception is not coming from composer.

**Comment by utmsandeep** [comment]
So have you any suggestion to this in another way ?? please suggest.

**Comment by stof** [comment]
Well, the maintainers of `upgrade-code.phar` should allow a longer timeout when running composer. But you should contact that project (which is not related to composer)

**Comment by wojciechmruk** [comment]
So there's no suggestions and I don't know what to do with that :/
