### ISSUE TITLE
load is breaking my page can not use composer 

### ISSUE THREAD

**Issue by Matteveli** [composer/composer#7944]
My `composer.json`:

```
{
    "require": {
        "vlucas/phpdotenv": "^3.3"
    }
}
```

Output of `composer diagnose`:
```

> composer diagnose
> Checking composer.json: WARNING
> No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
> Checking platform settings: OK
> Checking git settings: OK
> Checking http connectivity to packagist: OK
> Checking https connectivity to packagist: OK
> Checking github.com rate limit: OK
> Checking disk free space: OK
> Checking pubkeys:
> Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
> Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
> OK
> Checking composer version: OK
> Composer version: 1.8.3
> PHP version: 7.1.23
> PHP binary path: /usr/bin/php
```

but i do not know if this is the issue if where to put "proprietary" or the license

When I run this command:

```
`require 'vendor/autoload.php';

$dotenv = Dotenv\Dotenv::create(__DIR__);

$dotenv->load(); 
```

I get the following output:

the $dotenv-> load() or when i try to load any other libary through composer instantly breaks my webpage i dont know why this is not just with the lucas it is with any libary i try to load with composer. as soon as i get to the load or NEW the page breaks  

PLEASE HELP

let me know if any more info is needed

**Comment by alcohol** [comment]
Insufficient information/. "the page breaks" is not useful information. It does not tell us what is wrong. It does not tell us what kind of error you are experiencing.

It sounds more like you have an issue with PHP itself though, and not specifically Composer. Are you new to PHP? If so, I recommend you start with a tutorial to get a good understanding of the basic concepts.

**Comment by Matteveli** [comment]
sorry i have solved it now  you were right it was not composer it was that i was putting a semi colon after each file it the .env .... school boy error.. Thank you for your reply
