### ISSUE TITLE
ArrayDumper or schema do not comply for dist information of package

### ISSUE THREAD

**Issue by Toflar** [composer/composer#7955]
The schema for an `inline-package` contains the following information for a `dist` package: 

```json
"dist": {
  "type": "object",
  "required": ["type", "url"],
  "properties": {
    "type": {
      "type": "string"
    },
    "url": {
      "type": "string"
    },
    "reference": {
      "type": "string"
    },
    "shasum": {
      "type": "string"
    },
    "mirrors": {
      "type": "array"
    }
  }
}
```

See: https://github.com/composer/composer/blob/master/res/composer-schema.json#L822

So for example `reference` must be a string. However, this can be `null`.
So not sure what's correct here. Either the schema has to be fixed or the `ArrayDumper` should omit `null` values [here](https://github.com/composer/composer/blob/master/src/Composer/Package/Dumper/ArrayDumper.php#L57) just the same as it's done with `mirrors`?

**Comment by Toflar** [comment]
Nope, the JSON schema validation fails if you pass `"reference": null,`. I suppose the `ArrayDumper` should omit it then.

**Comment by alcohol** [comment]
Oh like that. Yes, null values should be omitted from the output of array dumper.

**Comment by alcohol** [comment]
Are you sure it returns null though, and not just an empty string?

**Comment by alcohol** [comment]
An inline package should ideally declare a reference type of some sort btw; see https://getcomposer.org/doc/05-repositories.md#package-2

**Comment by Toflar** [comment]
I've noticed it for artifact packages. They do not contain a reference: https://github.com/composer/composer/blob/master/src/Composer/Repository/ArtifactRepository.php#L153
