### ISSUE TITLE
Cannot install from public repo

### ISSUE THREAD

**Issue by prumand** [composer/composer#7956]
I try to add a package from a public git-repo (internal accessible without password) to our composer.json. On composer update it always prompts me for a password. Isn't it possible to have public repos included like this?

```
# output composer update -vvv
Loading composer repositories with package information
Executing command (CWD): git clone --mirror 'https://bitbucket.private/scm/test/test.git' '/root/.composer/cache/vcs/https---bitbucket.private-scm-test-test.git/'
    Authentication required (bitbucket.private):
      Username:
```

```json
// entries in composer.json (package not yet as dependency)
"repositories": {
        "repo-name": {
            "type": "vcs",
            "url": "https://bitbucket.private/scm/test/test.git"
        }
}
```

cc: @HigHendHd

**Comment by alcohol** [comment]
Composer does not ask for authentication unless necessary. So whatever you told it to communicate with, is clearly not public for Composer.

**Comment by prumand** [comment]
ah, that could be one reason. We have a private CA. So it fails to the clone, and tries to use a password? I try whether installing the certs changes the behavior.

**Comment by prumand** [comment]
Ok, that is the problem. I trusted the CA and now `composer update` works.

Is there a way to trust the certs anyway? I tried some options like below, but different combinations didn't work. I would like to avoid trusting our CA on build (we use docker).
```json
"options": {
                "ssl": {
                    "verify_peer": false
                }
            }
```

**Comment by prumand** [comment]
PS: from my point of view, I would wish for a different error
PPS: thx btw

**Comment by alcohol** [comment]
How did you use this options block? It is really hard to be helpful when you give is only snippets of information. I cannot tell if you put this somewhere randomly in your `composer.json` or if you put it in the right place.

**Comment by prumand** [comment]
sry provided more context.

**Comment by alcohol** [comment]
I am also not sure what a CA certificate has to do with authentication btw. SSL != authentication.

**Comment by prumand** [comment]
Short update on my understanding:
* ca = Certificate authority, issuing the SSL certificate. All issued certs can be trusted via the ca's cert
* you are right. I though it would do something like: `git -c http.sslVerify=false clone https://...`

I guess this ticket can be closed. Public repos yes, untrusted ssl no.

What do you think, shall I open an issue concerning the misleading error handling? Git doesn't return a specific error code (128) for certs-errors, but the output is rather specific:

````
fatal: unable to access 'https://bitbucket.private/scm/test/test.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
````

**Comment by alcohol** [comment]
I honestly do not know. Try asking @Seldaek :-)

**Comment by Seldaek** [comment]
`untrusted ssl no` is indeed a good summary :) I think improving our error reporting here might help indeed if you want to send a pull request, but we don't want to support this further otherwise. In this day and age of letsencrypt self-signed certs are kinda to be avoided or if you do it then configure the CA bundle correctly on all machines.
