### ISSUE TITLE
Install composer on Jenkins: Composer could not find the config file: C:\ProgramData\ComposerSetup\bin

### ISSUE THREAD

**Issue by forgetaboutme** [composer/composer#7957]
I have an Ant build script that is trying to execute Composer install but I get this error when executed through Jenkins:
```Bash
     [exec] Composer could not find the config file: C:\ProgramData\ComposerSetup\bin
     [exec] To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
     [exec] Result: 1
     [echo] composer update complete
```

Here is the target from Ant:

```Ant
<target name="self-update"
        if="composer.self-update"
        unless="composer.installed"
        description="Self-update Composer">
    <echo message="Self-updating composer" level="debug"/>
    <exec executable="${composer.phar}">
        <arg value="self-update" />
        <arg value="--quiet" />
        <arg value="--no-interaction" />
    </exec>
    <echo message="composer self-update complete" level="debug"/>
</target>
```

However, this works fine when running the Ant build locally.

Some people say to delete the environment variables that the composer installer sets; however it does not seem to change anything.

**Comment by alcohol** [comment]
@johnstevenson any idea what would be the bare minimum in regards to path or other env variables when it comes to automatic installation on windows?

**Comment by alcohol** [comment]
Question, your task output shows "composer update complete" but your task is about self updating and contains the message "composer self-update complete". Are you sure the output belongs to the task that you shared with us?

**Comment by johnstevenson** [comment]
@alcohol Internally Composer-Setup.exe runs the script from `https://getcomposer.org/installer` and modifies the environment thus: 
> Environment Variables

The installer will modify your system path for Admin installs, or your user path for User installs:

    the path to PHP will be added/replaced
    the path to the composer files directory will be added/replaced

In addition the installer will add the following to the user environment:

    the C:\Users\<user>\AppData\Roaming\Composer\vendor\bin directory to your path
    an http_proxy value, if specified in the installer

https://github.com/composer/windows-setup#environment-variables

**Comment by alcohol** [comment]
Thanks for that info :-)

**Comment by forgetaboutme** [comment]
@alcohol sorry for that, here is the complete output:

```Ant
composer.composer:
[available] Unable to find ${phptools.project.dir}\composer.lock
Condition false; setting composer.command to install
Setting project property: composer.command -> install
     [echo] Beginning composer install
     [exec] Current OS is Windows 10
     [exec] Executing 'php' with arguments:
     [exec] 'E:\Program Files (x86)\Jenkins\workspace\OPECC Test/composer.phar'
     [exec] 'install'
     [exec] '--verbose'
     [exec] '--no-interaction'
     [exec] '--optimize-autoloader'
     [exec] '--prefer-dist'
     [exec] 
     [exec] The ' characters around the executable and arguments are
     [exec] not part of the command.
Execute:Java13CommandLauncher: Executing 'php' with arguments:
'E:\Program Files (x86)\Jenkins\workspace\OPECC Test/composer.phar'
'install'
'--verbose'
'--no-interaction'
'--optimize-autoloader'
'--prefer-dist'

The ' characters around the executable and arguments are
not part of the command.
     [exec] Composer could not find the config file: C:\ProgramData\ComposerSetup\bin
     [exec] To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
     [exec] Result: 1
     [echo] composer install complete
```

**Comment by alcohol** [comment]
Can you also share what environment variables are set in that context? I do not know if Windows has a command similar to [`env`](https://linux.die.net/man/1/env).

**Comment by forgetaboutme** [comment]
Currently for Jenkins:
```
E:\Program Files (x86)\Jenkins\jre\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\cygwin64\bin\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\Program Files\Microsoft VS Code\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Druide\Antidote 9\Application\Bin64\;C:\Program Files (x86)\Druide\Antidote 9\Application\Bin32\;C:\Program Files\Git\cmd;C:\xampp\php;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;.
--
```
I know the windows installer sets an environment variable to be able to run Composer globally - I tried running my build with and without this variable set - nothing changes, I still get this error.
I figured that composer might be trying to look for a config file inside the `C:\ProgramData\ComposerSetup\bin` folder; however, I am trying to run it locally inside the project.

**Comment by alcohol** [comment]
```
rob@thinkpad ~ $ cd $(mktemp -d)
rob@thinkpad /tmp/tmp.X5Iv68uZyC $ composer install
Composer could not find a composer.json file in /tmp/tmp.X5Iv68uZyC
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
```

This looks similar (but not identical) to your output.


Relevant code:

https://github.com/composer/composer/blob/79af9d45afb6bcaac8b73ae6a8ae24414ddf8b4b/src/Composer/Factory.php#L266-L288

It would appear that for some reason your Composer executable is under the impression that it should be reading configuration from `C:\ProgramData\ComposerSetup\bin` rather than `composer.json`. Are you sure there are no environment variables set that are overriding the default behaviour of Composer?

**Comment by johnstevenson** [comment]
@forgetaboutme How and where do you install composer. I guess you must be using Composer-Setup.exe

**Comment by forgetaboutme** [comment]
@johnstevenson Yes, I am using the Composer-Setup.exe to install composer on my local machine. However, I am trying to execute composer through an ant script on Jenkins. This Jenkins' instance is installed on my local machine as well.

**Comment by forgetaboutme** [comment]
@johnstevenson Will double check, hopefully the folder was still there and this works after deleting it! Thank you for your help by the way, I truly appreciate - I've been banging my head on the table for a few weeks now.

**Comment by johnstevenson** [comment]
I wouldn't guarantee that will work. It's hard to understand the problem without knowing where everything is installed to.

Is `E:` a partition or a drive mapped to a local folder on `C:`. From which location is the build called from? What exactly are you trying to achieve (I'm guessing that you are trying to create a folder that contains a PHP application with all dependencies included that can be distributed).

**Comment by forgetaboutme** [comment]
`E:` is a partition. I can try re-installing Jenkins on my `C:` drive. The build is called from `E:\Program Files (x86)\Jenkins\workspace\...` . I am at work right now but will try see what can be done tonight.

**Comment by johnstevenson** [comment]
Okay thanks. There is no need to worry about the partition - I can happily run `composer install` from a different drive with composer itself installed on `C:` (via Composer-Setup.exe). 

You could try:

- reinstall composer with Composer-Setup.exe
- alter your Ant target executable to `<exec executable="composer">` 
- remove the `<arg value="${composer.phar}"/>` argument.

**Comment by alcohol** [comment]
No, what I meant was that it looks like there is an environment variable named `COMPOSER` that is set to `C:\ProgramData\ComposerSetup\bin`. Because that is the flow your code is executing. Hence why I asked numerous times if you can check your environment variables in the context of that task, cause it definitely looks like the `COMPOSER` environment variable is set.

**Comment by johnstevenson** [comment]
@alcohol Ah, good point. I always seem to forget about the `COMPOSER` environment variable!

**Comment by forgetaboutme** [comment]
@alcohol you were 100% right, it seems like the following property is being loaded when executed through Ant:
```Ant
Setting project property: env.Composer -> C:\ProgramData\ComposerSetup\bin
```
I am not sure from where it loads this variable - when I go in CMD and `ECHO %Composer%`, nothing comes out... neither when I try `ECHO %COMPOSER%`.

**Comment by forgetaboutme** [comment]
So I could manage a workaround by setting the composer `env` variable to `""` this:

```XML
    <target name="composer"
            depends="init, self-install, self-update"
            if="composer.run">
        <condition property="composer.command" value="update" else="install">
            <available file="${composer.lock}"/>
        </condition>
        <echo message="Beginning composer ${composer.command}" level="debug"/>
        <exec executable="php">
            <env key="composer" value=""/>
            <arg value="${composer.phar}"/>
            <arg value="${composer.command}"/>
            <arg value="--verbose"/>
            <arg value="--no-interaction"/>
            <arg value="--optimize-autoloader"/>
            <arg value="--prefer-dist"/>
        </exec>
        <echo message="composer ${composer.command} complete" level="debug"/>
    </target>
```

**Comment by alcohol** [comment]
It's better to just set it to `composer.json` then.
