### ISSUE TITLE
Operation timed out with composer update

### ISSUE THREAD

**Issue by rcouturieracquia** [composer/composer#7958]
Hi Everyone,

Since this afternoon I'm not able to run the `composer update` command in my Drupal repository.

Environnement info:

- Mac OS 10.14
- Composer version 1.8.3 2019-01-30 08:31:33
- Drupal 8.6.8
- PHP CLI 7.1.9

Below is the output of `composer update` command being executed in Drupal root directory :

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 79 installs, 30 updates, 0 removals
  - Updating symfony/class-loader (v3.4.15 => v3.4.22): Downloading (failed)       
The "https://api.github.com/repos/symfony/class-loader/zipball/4459eef5298dedfb69f771186a580062b8516497" file could not be downloaded: failed to open stream: Operation timed out
```
This error seems to happen with every packages.

I tried to re-install composer, but it doesn't seem to change anything.

If anyone could help it would be great!

Thanks
Romain

**Comment by alcohol** [comment]
Not sure what we can do about this. It looks like a networking issue, which is always a local issue. So you'll have to check your firewall or proxy setup, or reach out to your local network admin.

**Comment by rcouturieracquia** [comment]
Hi alcohol, thank you for your quick reply. I'm currently working from my house and private network. No proxy / no VPN.

The weird thing is I don't recall changing any configuration on my router recently. Is there any port or connectivity requirements that need to be done for composer to work ?

When I did a `composer self-update` everything worked well. It's just happening when I want to update packages on a project.

**Comment by rcouturieracquia** [comment]
Well guess what.. It's back and working now.. 

I've no idea what just happened, but no "Connection Timed Out" anymore. My guess is (and maybe I'm wrong), it was probably a network issue at the hosting provider level. Because I haven't changed any settings on my router.

**Comment by alcohol** [comment]
Glad to hear it is working again.
