### ISSUE TITLE
Update the documentation to quote wildcard

### ISSUE THREAD

**Issue by gagarine** [composer/composer#7960]
The composer [documentation](https://getcomposer.org/doc/03-cli.md#update-u) introduce the use a wildcard like that:

`php composer.phar update vendor/*`

But this is not safe. For example, when I'm using that for drupal on [fish](http://fishshell.com/) I get this error:

```
composer outdated drupal/*
fish: No matches for wildcard “drupal/*”. See `help expand`.
```

I think the save things to do is always quote the argument like.

`php composer.phar update "vendor/*"`

The documentation should be updated no?

**Comment by alcohol** [comment]
Yeah, a PR to update the documentation is welcome.
