### ISSUE TITLE
Introduce the ability for a script to require that dependencies have been installed

### ISSUE THREAD

**Issue by johnbillion** [composer/composer#7964]
I'm utilising the `scripts` property to define a script that calls a binary within `vendor/bin` (`phpcs` in the example composer.json below).

The problem is that this script requires that the Composer dependencies have first been installed with `composer install`. If the user has not run `composer install` then they'll get a shell error stating `phpcs: command not found`.

In this situation I would prefer one of two things:

1. To provide a friendlier error message to the user (eg. `Please run "composer install" to install this script's dependencies`).
2. To automatically run `composer install` if the dependencies have yet to be installed.

I attempted to solve `2` by adding a `setup` script which gets called by `test` and installs the dependencies if necessary, but it raises a couple of problems of its own:

1. You cannot use `@composer` within a shell script, so I needed to use `composer install` which doesn't necessarily resolve to the correct composer.phar.
2. The addition of the call to `@setup` within the `test` script means that it's no longer possible to pass arguments to PHPCS (eg. `composer test --standard=foo`) without those arguments _also_ being passed to `setup` and therefore causing a fatal error.

It would be great if there was a way for a script to declare that it requires that dependencies have first been installed before it can run, and for a user-friendly error message to be displayed if not.

Thoughts?

---

My `composer.json`:

```json
{
    "name": "foo/bar",
    "scripts": {
        "setup": [
            "if [ ! -d 'vendor' ]; then composer install; fi"
        ],
        "test": [
            "@setup",
            "phpcs ."
        ]
    },
    "require-dev": {
        "squizlabs/php_codesniffer": "^3"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.3
PHP version: 7.2 - Package overridden via config.platform (same as actual)
PHP binary path: /Users/john/.phpbrew/php/7.2/bin/php
```

**Comment by alcohol** [comment]
Seems like a lot of trouble for virtually no value.

**Comment by Seldaek** [comment]
I agree that this is.. somewhat far fetched. Installing dependencies is kind of a reasonable prerequisite to using a project. Recommending people install/clone your software with `composer create-project` might be a way to help there, as that will install dependencies automatically.
