### ISSUE TITLE
composer validate should require scripts-descriptions properties for all scripts, if it's present

### ISSUE THREAD

**Issue by johnbillion** [composer/composer#7965]
Given a composer.json file that contains a `scripts-descriptions` property, when running `composer validate --strict` I would expect an error to be triggered if `scripts-descriptions` does not contain an entry for all of the scripts in the `scripts` property. If I choose document one script then I want to ensure that they're all documented.

Note that I would not expect to have to provide a description for any of Composer's built-in scripts if they're present in `scripts`, for example `post-install-cmd` etc.

My `composer.json`:

```json
{
    "name": "foo/bar",
    "scripts": {
        "foo": "foo",
        "bar": "bar"
    },
    "scripts-descriptions": {
        "foo": "Runs Foo"
    }
}
```

When I run this command:

```
composer validate --strict
```

I get the following output:

```
./composer.json is valid
```

And I expected this to happen:

```
Description for script "bar" not found in "scripts-descriptions"
```

**Comment by johnbillion** [comment]
Actually I'm not so sure about documenting Composer's built-in scripts if they're present in `scripts`, maybe descriptions for those should be required too.

**Comment by johnbillion** [comment]
Ah it looks like descriptions for built-in scripts get ignored anyway when calling `composer run-script --list`.

**Comment by Seldaek** [comment]
I don't really agree that validate should nag you to this level of detail. If you have a `test` script for example, it's kinda self explanatory.. forcing a description is like failing a build if a method has no docblock. That sounds way too strict to me.
