### ISSUE TITLE
composer 2.0 roadmap

### ISSUE THREAD

**Issue by mitelg** [composer/composer#7966]
Hello there!

I tested the dev state of composer 2.0 and I'm really impressed by the outstanding performance (tried "require" most of the time though). Is there any information or roadmap or something like that, when we will benefit from this in production?

Best regards :wave:

**Comment by Seldaek** [comment]
Sorry but no date yet.. it's kinda "when it's done". Feel free to follow https://github.com/composer/composer/milestone/23

**Comment by glensc** [comment]
is there any blog or doc what is the 2.0 goals? min php version, what is it different from, say 1.8?

**Comment by Seldaek** [comment]
No change in min php version.. it's mostly internal refactorings and packagist.org protocol changes that won't directly affect users. The main big change for users is faster parallel downloads and more predictable update/install process.
