### ISSUE TITLE
JSON in Getting Started 

### ISSUE THREAD

**Issue by SheepDomination** [composer/composer#7968]
I'm looking within the *Getting Started* on how to create a JSON file, but nothing exists within the guide ?

**Comment by hirak** [comment]
All you have to do is `composer init` command.
https://getcomposer.org/doc/03-cli.md#init
Full composer.json options are here.
https://getcomposer.org/doc/04-schema.md

**Comment by SheepDomination** [comment]
I want to get the package name, but `show` isn't giving me any results; as the package name `composer.phar` is invalid ?
