### ISSUE TITLE
composer cli config command does not support arrays

### ISSUE THREAD

**Issue by alphp** [composer/composer#7981]
Composer version: 1.8.4
PHP version: 7.3.2

My `composer.json`:

```json
{
    "name": "me/project",
    "type": "project",
    "config": {
        "vendor-dir": "vendors"
    }
}
```

When I run this command:

```
composer config extra.installer-types ["cakephp-plugin"]
composer config extra.installer-paths.app/Plugin/{$name} ["type: cakephp-plugin"]
```

Output `composer.json`:

```json
{
    "name": "me/project",
    "type": "project",
    "config": {
        "vendor-dir": "vendors"
    },
    "extra": {
        "installer-types": "[cakephp-plugin]",
        "installer-paths": {
            "app/Plugin/{$name}": "[type:cakephp-plugin]"
        }
    }
}
```

Expected `composer.json`:

```json
{
    "name": "me/project",
    "type": "project",
    "config": {
        "vendor-dir": "vendors"
    },
    "extra": {
        "installer-types": ["cakephp-plugin"],
        "installer-paths": {
            "app/Plugin/{$name}": ["type:cakephp-plugin"]
        }
    }
}
```

**Comment by Seldaek** [comment]
`omposer config extra.installer-types.0 "cakephp-plugin"` works for the first one, but the second is too deep and is not supported. Complex operations have to be done manually in the json.. the config command is a convenience thing but meant to be a full blown json editor.

**Comment by XedinUnknown** [comment]
I too would like very much to see this work, and incidentally for the same config keys. The reason is that `composer config` is useful in configuring different kinds of environment, e.g. staging VS dev. In this case, I am developing a WP plugin, and I need to install `wordpress-plugin` packages _alongside mine_ (i.e. `../{$name}/`) in a dev environment, but into the `vendor` folder in a staging environment.

Is there a particular problem with supporting this? Perhaps, it could be marked as a "nice to have" feature, and re-considered in the future?

**Comment by Seldaek** [comment]
Most tools editing json use some sort of XPath-style json query language to address deep keys as the structure can get very complex. I don't really want to add support for this.. and also it'd be hard to add it in a BC way at this point anyway. So we support up to two level deep as a convenience and if that's not enough you're on your own. There probably are other CLI tools you could use to modify the json in a programmatic way if you really need it in a CI setting or similar.

**Comment by XedinUnknown** [comment]
Good point re. other JSON-editing CLI tools, thanks!

**Comment by alphp** [comment]
My method:

```bash
php -a
```

```php
$composer = json_decode(file_get_contents('composer.json'), true);
$composer['extra']['installer-types'] = ['cakephp-plugin'];
$composer['extra']['installer-paths']['app/Plugin/{$name}'] = ['type:cakephp-plugin'];
file_put_contents('composer.json', json_encode($composer, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
exit
```

**Comment by alphp** [comment]
With PR #8017 this code work as expected:
composer config extra.installer-types.0 "cakephp-plugin"
composer config extra.installer-paths.app/Plugin/{$name}.0 "type: cakephp-plugin"
