### ISSUE TITLE
Cannot update single package because of not related package

### ISSUE THREAD

**Issue by BLaDZer** [composer/composer#7983]
My `composer.json`:

```json
{
    "require": {
        "twig/twig": "~1.00",
        "robmorgan/phinx": "^0.9.2",
        "odan/phinx-migrations-generator": "^2.6",
        "tecnickcom/tc-lib-barcode": "^1.15"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.4
PHP version: 5.6.40
PHP binary path: /usr/bin/php5.6
```

When I run this command:

```
composer update twig/twig
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Dependency resolution completed in 0.001 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - odan/phinx-migrations-generator 2.6.1 requires php ^7.0 -> your PHP version (5.6.40-1+ubuntu18.04.1+deb.sury.org+1) overridden by "config.platform.php" version (5.6) does not satisfy that requirement.
    - odan/phinx-migrations-generator 2.6.1 requires php ^7.0 -> your PHP version (5.6.40-1+ubuntu18.04.1+deb.sury.org+1) overridden by "config.platform.php" version (5.6) does not satisfy that requirement.
    - odan/phinx-migrations-generator 2.6.1 requires php ^7.0 -> your PHP version (5.6.40-1+ubuntu18.04.1+deb.sury.org+1) overridden by "config.platform.php" version (5.6) does not satisfy that requirement.
    - Installation request for odan/phinx-migrations-generator (locked at 2.6.1, required as ^2.6) -> satisfiable by odan/phinx-migrations-generator[2.6.1].
```

And I expected this to happen:
Package ``twig/twig`` should be easily updated cuz it doesn't need to update any shared dependencies or install any dependency that require php > 5.6.
Tried update from version ``1.35.3`` to ``1.37.1``

**Comment by BLaDZer** [comment]
```
composer why-not twig/twig

__root__  dev-develop  requires  twig/twig (~1.0)
```
what does this mean?

Also tried with different options
```
--lock
--no-suggest
--prefer-dist
--prefer-lowest
--prefer-stable
--with-dependencies
```
but nothing of it worked for me.

Only working using ```--ignore-platform-reqs```` but it's wrong cuz after update composer update twig/twig requirements from php >=5.3.3 to >=5.4.0 and install symfony/polyfill-ctype that require php >=5.3.3 and thats all.

**Comment by xabbuh** [comment]
How did you actually manage to install the dependencies in the first place given that `odan/phinx-migrations-generator` requires PHP 7, but your system uses 5.6.40?

**Comment by BLaDZer** [comment]
@xabbuh I've updated it with same ``--ignore-platform-reqs`` cuz it actually doesn't req PHP 7 for this version

**Comment by xabbuh** [comment]
Okay, well then you need to do the same now as all installed packages are also part of the dependency graph that is being resolved.

**Comment by BLaDZer** [comment]
@xabbuh so do you think it's normal behavior: not letting update one package because of another package that wasn't going to be updated also non of any of it's dependencies?

I mean ``dependency satisfaction strategy`` and actually ``install/update strategy`` is working in different ways. I'm sorry but it's seems to be unclear to me.

> Just note that doing so is quite risky

I completely agree with you. That's why I don't want to use ``--ignore-platform-reqs`` when it's not necessary like in this case.

**Comment by xabbuh** [comment]
Afaik (but other know the solver way better than me) the solver just needs to take the whole dependency graph into account. It doesn't have any knowledge about whether a package is already installed or not.

**Comment by Seldaek** [comment]
Right, even if something is installed, it just means it's pinned to that version in a partial update, but it's still part of the dependency resolution. If you opt-in to use a package with the wrong php requirement, you'll have to keep using --ignore-platform-reqs.
