### ISSUE TITLE
Add Util class to read composer.json from ZIP file

### ISSUE THREAD

**Issue by aschempp** [composer/composer#7984]
It would be great if we could extract the private methods from `ArtifactRepository` to read the `composer.json` from ZIP files.

https://github.com/composer/composer/blob/master/src/Composer/Repository/ArtifactRepository.php#L83-L166

I currently have to duplicate these lines in two projects where I already require `composer/composer`. Would you be ok with extracting these two? I'm open to create a pull request for it.

**Comment by Seldaek** [comment]
I guess you could move them to a Composer\Util\Zip, at least locateFile. The other one kinda seems very specific to ArtifactRepo, but I guess this bit https://github.com/composer/composer/blob/master/src/Composer/Repository/ArtifactRepository.php#L128-L150 could be extracted to a somewhat generic thing to read any file?

**Comment by aschempp** [comment]
closed in favor of #7994
