### ISSUE TITLE
Incorrect resolution of repository during outdated

### ISSUE THREAD

**Issue by fgm** [composer/composer#7985]
My `composer.json`:

```json
...
  "repositories": [
    {
      "type": "package",
      "package": {
        "name": "elijaa/phpmemcacheadmin",
        "version": "dev-master",
        "source": {
          "reference": "master",
          "type": "git",
          "url": "https://github.com/elijaa/phpmemcachedadmin.git"
        }
      }
    },
  ],
  "require": {
    "elijaa/phpmemcacheadmin": "dev-master",
  }
...
```

Output of `composer diagnose`:
(filtered irrelavant portions)
```
Checking composer.json: WARNING
require.elijaa/phpmemcacheadmin : unbound version constraints (dev-master) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Composer version: 1.8.4
PHP version: 7.0.25 - Package overridden via config.platform (actual: 7.2.15)
PHP binary path: /usr/local/Cellar/php@7.2/7.2.15/bin/php
```

When I run this command:
(filtered irrelevant portions)
```
composer outdated
```

I get the following output:

```
elijaa/phpmemcacheadmin     dev-master master dev-master ea7c773 (in red)
```

And I expected this to happen:
```
elijaa/phpmemcacheadmin     dev-master master dev-master (in black)
```

When diagnosing what is happening, the problem is that elijaa/phpmemcacheadmin in Packagist is (incorrectly IMHO) pointing to a fork of the actual project ( https://github.com/alphayax/phpmemcachedadmin ) instead of the original ( https://github.com/elijaa/phpmemcachedadmin ) which is why the `repositories` entry is needed in the first place, and the commit referenced in outdated is the master HEAD from the fork provided by Packagist instead of the master HEAD from the one pointed to by the project `repositories` entry/

Now, when requiring/upgrading, the specified repository is correctly used, this problem only happens with the "oudated" command. Even a show gives the proper results:
```
composer show -a elijaa/phpmemcacheadmin
name     : elijaa/phpmemcacheadmin
descrip. :
keywords :
versions : dev-master
type     : library
source   : [git] https://github.com/elijaa/phpmemcachedadmin.git master
dist     : []
names    : elijaa/phpmemcacheadmin
```

**Comment by Seldaek** [comment]
I updated the repo to point to the correct one. @elijaa if you have a packagist.org account let me know and I will transfer the https://packagist.org/packages/elijaa/phpmemcacheadmin package to you.

@fgm does this help?

**Comment by fgm** [comment]
Hi @Seldaek . Yes it fixes the problem for this specific case, thank you. However, I can't help but think this is just hiding an actual bug in repo selection during outdated, don't you think ?

**Comment by Seldaek** [comment]
I am not sure - but given we are changing a ton of how that works in v2, I think I'd rather close this for now and if it ever crops up again on v2 we can have a closer look.
