### ISSUE TITLE
Composer not installing on PHP 5.5

### ISSUE THREAD

**Issue by LarsFronius** [composer/composer#7986]
When I run this command:

```
wget https://getcomposer.org/installer -O - -q | php -- --filename=composer
```
^This is running under our legacy-legacy PHP 5.5 based environment.

I get the following output:

```
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'checkPlatform() expects parameter 1 by reference, but the call was not annotated with '&'' in /tmp/php-wrap-TxJf4S:52
```

And I expected this to happen: Composer installs.

I didn't see that PHP 5.5 was announced as not working with composer (I totally agree it could be as PHP 5.5 is EOL).

**Comment by Seldaek** [comment]
Are you sure about your PHP version? https://3v4l.org/RpB1V seems to work fine with reference args.

/tmp/php-wrap-TxJf4S:52 also seems to indicate your "php" isn't quite just a plain php.

**Comment by LarsFronius** [comment]
I'm just trying to reproduce this locally. I'll get back to you once I have something :)

**Comment by naderman** [comment]
Because @LarsFronius didn't document this here for others :P

The cause of the problem was that he was running HHVM 4.0, which throws this error when attempting to run the installer.
