### ISSUE TITLE
[Feature] Add support for requirement grouping

### ISSUE THREAD

**Issue by drmovi** [composer/composer#7989]
It will be helpful if composer support requirement grouping. we all know that `require` option is for application dependencies and `require-dev` is for development dependency.

**Problem:**
in modern development Continuous integration and continuous delivery requires different developmental dependencies for example in CI unit testing may be all we need since CI process should be very fast, there is no need to install tools for acceptance testing or end to end testing as it will never be used in this process.

**Suggested Feature:**
require-(group) where  group is the grouping tag used to be called during build time e.g.
`composer install --require-ci --require-acceptance`

I think this can save time and bandwidth and improve our CI/CD performance.

Thanks

**Comment by Seldaek** [comment]
This has been proposed before and rejected as not worth it. It introduces too much complexity, and doesn't gain you a whole lot. Put CI dependencies in require-dev.
