### ISSUE TITLE
Improve debug output for http calls by adding http auth user

### ISSUE THREAD

**Issue by glaubinix** [composer/composer#7992]
Hey,

to make it easier to debug failing `composer install/update` with `-vvv` it would be helpful to display the http auth user for every http call that is being used to make the call.

As it is only the user and not the password part of the http basic auth this should not be a security issue in case anyone would post the full `composer install -vvv` output in a public place.

**Comment by mathiasdonoso** [comment]
Hello @glaubinix , is this related to #8316 ?

**Comment by glaubinix** [comment]
Yes, thank you!
