### ISSUE TITLE
post-install-cmd not working on vendor dependency

### ISSUE THREAD

**Issue by manuakasam** [composer/composer#7993]
I'm trying to build a helper library for my colleagues. Currently I'm only working locally and try to get it to work, so no server is involved. 

This is the json of the library im creating

```json
{
    "name": "kk-commons/development-helpers-php",
    "description": "TBD",
    "authors": [
        {
            "name": "Manuel Stosic",
            "email": "sam@krankikom.de"
        }
    ],
    "autoload": {
        "psr-4": {
            "Krankikom\\DevelopmentHelpersPHP\\": "src/"
        }
    },
    "require-dev": {
        "composer/composer": "^1.8"
    },
    "scripts": {
        "post-install-cmd": [
            "Krankikom\\DevelopmentHelpersPHP\\Installer::postInstallCmd"
        ],
        "post-update-cmd": [
            "Krankikom\\DevelopmentHelpersPHP\\Installer::postUpdateCmd"
        ],
        "post-package-install": [
            "Krankikom\\DevelopmentHelpersPHP\\Installer::postPackageInstall"
        ]
    }
}
```

This is the json of the project where I'm trying to include this helper library and have those commands executed:

```
{
    "name": "manuakasam/open-space-tooling",
    "authors": [
        {
            "name": "Sam",
            "email": "manuakasam@googlemail.com"
        }
    ],
    "require": {
    },
    "require-dev": {
        "kk-commons/development-helpers-php": "dev-master"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "/Users/manuakasam/projects/krankikom/development-helpers-php"
        }
    ]
}
```

When i run ```composer run-script post-install-cmd``` on the helper library root then the scripts gets executed.

However, when i run `composer require kk-commons/development-helpers-php --dev` on the main lib, the package is being installed but no commands are being executed.

I'm likely missing something completely obvious but even checking out other packages that do similar stuff I can't see where my issue lies. Any help will be greatly appreciated and will result in many developers writing cleaner code, soon (tm) :D

**Comment by Seldaek** [comment]
I guess it doesn't say on the scripts page, but https://getcomposer.org/doc/04-schema.md#scripts indicates that scripts is only available on the root package. So you'd have to define the scripts in manuakasam/open-space-tooling, but they can point to a class inside the dependency/helper.

Leaving this open because the scripts page should make this clearer in the docs.

**Comment by manuakasam** [comment]
Well granted the scripts page does say that its only happening in the root package. So basically my idea can only work if either people would add the `scripts` section to the main project or alternatively use `composer create-project` with the helper package as the base point. Both only fairly mediocre options, therefore things I have in mind will stay mostly manual tasks then.

Thank you for the explanation!

**Comment by Seldaek** [comment]
Right, alternatively you could write a plugin package I suppose.

**Comment by 7334499340** [comment]
Send me money place

**Comment by mitch292** [comment]
> Leaving this open because the scripts page should make this clearer in the docs.

Looks like this has been solved! - https://getcomposer.org/doc/articles/scripts.md

**Comment by manuakasam** [comment]
Yeap, that sounds understandable and therefore this can most definitely be closed now. Thanks for pointing out @mitch292
