### ISSUE TITLE
Add a logfile with detailed infos for each update

### ISSUE THREAD

**Issue by lunetics** [composer/composer#800]
It would be reall helpful if composer would have a logfile, which automatically does e.g. for git a 'git log' for each rep.

So if something breaks cause of a 3rd party bundle, you can look into the logfile and have an overview of what changed in which bundle.

**Comment by jakoch** [comment]
(Sidenote: There is a new plugin called [composer-changelogs](https://github.com/pyrech/composer-changelogs) which goes into the direction of this feature request. It provides a summary of the updates with links. The output is ready to be pasted into the commit message when updating the composer.lock file.)

**Comment by lunetics** [comment]
thanks for the info jakoch, just saw it. i will close the ticket then
