### ISSUE TITLE
Composer auth.json conflicts with TortoiseSVN auth.json

### ISSUE THREAD

**Issue by ofbeaton** [composer/composer#8003]
Can we get a way to rename the `auth.json` to a different name, perhaps in our `config` section of `composer.json`?

We are having the issue where we use SVN with many devs using TortoiseSVN.

They both will pickup creds in `auth.json` but the credentials stored for composer are just a read-only user to pull from a private repo.

While in TortoiseSVN devs want to use their actual user.

The workaround is for devs to use their actual user in the auth.json for composer too... but that would expose their user/pass to more people inside the team and make some automation more difficult.

So just a feature request if it's not too much to ask.

Thanks

**Comment by alcohol** [comment]
Why not use `~/.ocnfig/composer/auth.json` (`~/.composer/auth.json` on older systems) for credentials?

**Comment by ofbeaton** [comment]
Because that isn't a per-project file, and I shouldn't overwrite/manage it with puppet as the user may have other projects with other credentials in there.

Hence requesting a way to rename the `auth.json` in the project dir to a composer-only specific name.

**Comment by Seldaek** [comment]
What you can do is put auth stuff in composer.json, or use COMPOSER_AUTH env var.. Allowing renaming the file because of some clash with TortoiseSVN I don't see us doing sorry.

Does TortoiseSVN not offer a way to read credentials from somewhere else perhaps? Does it actually read composer's json format or do they accidentally happen to be exactly the same?

**Comment by ofbeaton** [comment]
Thanks for taking the time for giving the support workaround ideas. The ENV var sounds like it might work.

And yes, sadly the filenames and format are identical, it took us forever to figure out. 

Closing.

**Comment by ofbeaton** [comment]
Hm, apologies, after more googling and troubleshooting our problem is likely not with TortoiseSVN but with composer persisting the creds into the SVN cache, which TortoiseSVN then uses. #3163 tipped me off. 

The fix then would be to add `no-auth-cache` to my composer.json, which would work perfectly.

Really sorry for the extra support headache here.

In my case I kept reading the documentation for the `auth.json` file https://getcomposer.org/doc/articles/http-basic-authentication.md

whereas I should have been reading the docs private svn repos here https://getcomposer.org/doc/05-repositories.md#subversion-options

Perhaps the former could briefly link to the other if that could make sense?
