### ISSUE TITLE
Validate strict should have a none zero exit code when deprecations are thrown

### ISSUE THREAD

**Issue by alexander-schranz** [composer/composer#8004]
My `composer.json`:

```json
{
    "require": {
          "beberlei/DoctrineExtensions": "^1.0"
     }
}
```

Output of `composer diagnose`:

```
Deprecation warning: require.beberlei/DoctrineExtensions is invalid, it should not contain uppercase characters. Please use beberlei/doctrineextensions instead. Make sure you fix this as Composer 2.0 will error.
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.4
PHP version: 7.1.25
PHP binary path: /usr/local/Cellar/php@7.1/7.1.25/bin/php
```

When I run this command:

```bash
composer validate --strict
```

I get the following output:

```bash
echo $? # returns 0 
```

And I expected this to happen:

In strict validation I would think that the exit code of --strict should not be 0 when a deprecation is thrown.

**Comment by alcohol** [comment]
These deprecations are fairly new and I am guessing the validate command was not taken into account when introducing them. Good first issue for someone who wants to contribute to Composer though :-)

**Comment by alexander-schranz** [comment]
@alcohol would it be basically adding a `set_error_handler` to the [ValidateCommand](https://github.com/composer/composer/blob/f1297b11bc7f62e83472f0132661d9f610bbe0c4/src/Composer/Command/ValidateCommand.php)?

And would you do it only for --strict?

**Comment by alcohol** [comment]
Yeah, just make sure the original error handler(s) still get called too.

@Seldaek got any input or suggestions here?

**Comment by Seldaek** [comment]
These are not triggered as errors, and they are handled a bit special because of the way we need to notify people, so it's gonna be hard to do it this way IMO.

See ValidatingArrayLoader::hasPackageNamingError which is right now called in the RootPackageLoader.

The best would probably to add a check for this as well in the ConfigValidator class returning it as a warning for now (which will be turned to an error by --strict).

**Comment by alcohol** [comment]
Good thing I checked with you :sweat_smile:

**Comment by PReimers** [comment]
I would like to take a look at it.

Is somebody working on it or can I give it a try?

**Comment by Seldaek** [comment]
I'd say go for it unless @alexander-schranz has started smth..

**Comment by alexander-schranz** [comment]
@PReimers go for it 👍
