### ISSUE TITLE
Composer cannot upgrade itself from 1.7 to 1.8

### ISSUE THREAD

**Issue by caugner** [composer/composer#8015]
My `composer.json`:

```json
{
    "license": "MIT",
    "require": {
        "composer/composer": "1.7.*"
    }
}
```

Output of `composer diagnose`:

```
vendor/bin/composer diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Composer version: 1.7.3
PHP version: 7.2.15
PHP binary path: /nix/store/c6az7nhf794hkwyhjw56dnnz3fhb4pnx-php-7.2.15/bin/ph
```

When I run this command:

```
vendor/bin/composer require 'composer/composer:1.8.*'
```

I get the following output:

```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating composer/composer (1.7.3 => 1.8.4): 
Fatal error: Uncaught Error: Class 'Composer\Util\Url' not found in /tmp/composer/vendor/composer/composer/src/Composer/Downloader/FileDownloader.php:270
Stack trace:
#0 /tmp/composer/vendor/composer/composer/src/Composer/Downloader/FileDownloader.php(127): Composer\Downloader\FileDownloader->processUrl(Object(Composer\Package\CompletePackage), 'https://api.git...')
#1 /tmp/composer/vendor/composer/composer/src/Composer/Downloader/FileDownloader.php(97): Composer\Downloader\FileDownloader->doDownload(Object(Composer\Package\CompletePackage), '/tmp/composer/v...', 'https://api.git...')
#2 /tmp/composer/vendor/composer/composer/src/Composer/Downloader/ArchiveDownloader.php(38): Composer\Downloader\FileDownloader->download(Object(Composer\Package\CompletePackage), '/tmp/composer/v...', false)
#3 /tmp/composer/vendor/composer/composer/src/Composer/Downloader/ZipDownloader.php(77): Composer\Downloader\ArchiveDownloader->download(Object(Composer\Package\CompletePackage), '/tmp/composer/v...', false)
#4 /tmp/composer/vendor/comp in /tmp/composer/vendor/composer/composer/src/Composer/Downloader/FileDownloader.php on line 270
```

(And `vendor/bin/composer` no longer exists.)

And I expected this to happen:

Composer should have been updated to `1.8.4`.

**Comment by alcohol** [comment]
You need to use a compiled version to update the source. What you are doing does not make sense.

**Comment by alcohol** [comment]
I recommend you read our documentation to get a better understanding of how Composer works.

https://getcomposer.org/doc/00-intro.md

**Comment by caugner** [comment]
> You need to use a compiled version to update Composer as a dependency.

@alcohol Can you point out where this limitation is documented?

(The `composer.json` above is merely a minimal example to replicate the issue.)

**Comment by alcohol** [comment]
Not really documented as it seems quite logical and self explanatory to me. But maybe explaining what is happening will make it more apparent to you as well.

When you're using `vendor/bin/composer`, you are using the code that exists inside `vendor/composer/composer` to run Composer. But at the same time in your scenario, you are telling it to update your dependency, which means we remove `vendor/composer/composer` and try to replace it with the newer version. So basically, we are removing all the files that you are using to run Composer. Get it?

**Comment by caugner** [comment]
> What you are doing does not make sense.

All I'm trying to do is manage the dependency manager as a dependency in the context of continuous deployment. Using a compiled version of a dependency contradicts that intention.

> it seems quite logical and self explanatory to me

It should surprise you then that `yarn` can indeed manage itself as a dependency without problems:

```console
cd /tmp
mkdir yarn
cd yarn
npm install --only=dev yarn@1.0.1
node_modules/.bin/yarn add --dev yarn@1.1.0
node_modules/.bin/yarn --version
node_modules/.bin/yarn add --dev yarn@1.2.1
node_modules/.bin/yarn --version
node_modules/.bin/yarn add --dev yarn@1.3.2
node_modules/.bin/yarn --version
node_modules/.bin/yarn add --dev yarn@1.4.0
node_modules/.bin/yarn --version
node_modules/.bin/yarn add --dev yarn@1.5.1
node_modules/.bin/yarn --version
node_modules/.bin/yarn add --dev yarn@1.6.0
node_modules/.bin/yarn --version
node_modules/.bin/yarn add --dev yarn@1.7.0
node_modules/.bin/yarn --version
node_modules/.bin/yarn add --dev yarn@1.8.0
node_modules/.bin/yarn --version
node_modules/.bin/yarn add --dev yarn@1.9.4
node_modules/.bin/yarn --version
node_modules/.bin/yarn add --dev yarn@1.10.1
node_modules/.bin/yarn --version
node_modules/.bin/yarn add --dev yarn@1.11.1
node_modules/.bin/yarn --version
node_modules/.bin/yarn add --dev yarn@1.12.3
node_modules/.bin/yarn --version
node_modules/.bin/yarn add --dev yarn@1.13.0
node_modules/.bin/yarn --version
node_modules/.bin/yarn add --dev yarn@1.14.0
node_modules/.bin/yarn --version
```

> But at the same time in your scenario, you are telling it to update your dependency, which means we remove vendor/composer/composer and try to replace it with the newer version. So basically, we are removing all the files that you are using to run Composer. Get it?

What you seem to say is that software cannot update itself, because updating itself includes removing the files necessary for the update itself. However, not only yarn, but also e.g. Nextcloud and WordPress manage to update themselves (and don't end in an inconsistent/broken state).

In any case, composer shouldn't brick itself when trying to update itself.

Maybe @Seldaek has a different perspective on this?

**Comment by alcohol** [comment]
> It should surprise you then that yarn can indeed manage itself as a dependency without problems:

No that does not surprise me at all. Look at any Linux package manager, they can update themselves too.

Anyway, you're entitled to your own opinion of course. But comparing Yarn with Composer is like comparing apples with pears. Sure they're both dependency management tools. But they have very different fundamentals and are written in a completely different language.

**Comment by alcohol** [comment]
> All I'm trying to do is manage the dependency manager as a dependency in the context of continuous deployment. Using a compiled version of a dependency contradicts that intention.

Are you implying that you merely require Composer as a dependency for the sake of having `vendor/bin/composer` rather than having Composer available as a standalone binary tool in your build pipeline, and not actually use Composer as a dependency?

**Comment by Seldaek** [comment]
@Seldaek does not have a different perspective on this no.. The supported deployment mode is a phar archive with all dependencies included in it. `composer self-update` then updates the phar file in one go and without bricking itself.

To support updating like you want to do we'd have to make sure all classes are loaded before we upgrade the codebase on disk, to avoid the autoloader looking for stuff that has been removed or doesn't exist yet during the update process. It's possibly not that hard to achieve, but I also don't really see the point in spending my time fixing this.

**Comment by caugner** [comment]
> Are you implying that you merely require Composer as a dependency for the sake of having vendor/bin/composer rather than having Composer available as a standalone binary tool in your build pipeline, and not actually use Composer as a dependency?

Yes and no, I'm managing Composer as a dependency for the same reasons I manage other dependencies as a dependency: to lock its version to a version that I know works (read: to have more or less reproducible installs/updates). But yes, I'm not using Composer as a dependency in the sense that I'm using any Composer classes in my classes.

> To support updating like you want to do we'd have to make sure all classes are loaded before we upgrade the codebase on disk, to avoid the autoloader looking for stuff that has been removed or doesn't exist yet during the update process. It's possibly not that hard to achieve, but I also don't really see the point in spending my time fixing this.

Thanks for taking the time to outline how it would need to be implemented.

As a compromise, would it be an option to publish a package `composer/composer-phar` that only includes the `composer.phar` (and sets itself up as a binary at `vendor/bin/composer`)?

**Comment by alcohol** [comment]
> Yes and no, I'm managing Composer as a dependency for the same reasons I manage other dependencies as a dependency: to lock its version to a version that I know works (read: to have more or less reproducible installs/updates). But yes, I'm not using Composer as a dependency in the sense that I'm using any Composer classes in my classes.

Why not just commit the `composer.phar` into your codebase then if this is so important to you? While I can understand and appreciate your reasoning behind wanting to lock Composer to a specific version, it does not make much sense in this context.

You should approach it more like you would your PHP runtime version. Simply make sure it is available on the host / platform where you need it, in the version that you expect it to be.

One way to do this (which is perhaps not explicitly documented), would be to pass the version to the installer: https://github.com/composer/getcomposer.org/blob/master/web/installer#L44

See also https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md for more about the installer.
