### ISSUE TITLE
[Question] Install package manually from plugin

### ISSUE THREAD

**Issue by emulienfou** [composer/composer#8020]
Hello there,
I would like to install a package from code in a Composer plugin.

## 1st attempt
I tried to use the code from `RequireCommand.php` to try to install a package, like:
```php
$install = Installer::create($io, $composer);
$install
    ->setUpdateWhitelist(array_keys($requirements))
    ->setDevMode(true)
    ->setUpdate(true)
    ->setRunScripts(false);
$install->run();
```

> However, it return the next message: `Package "VENDOR/NAME" listed for update is not installed. Ignoring.`

## 2nd attempt
I tried to write some code like:
```php
$package = $composer->getRepositoryManager()->findPackage('vendor/name', 'dev-master');
if (null !== $package) {
    $operation = new InstallOperation($package);
    $installationManager->install(new InstalledFilesystemRepository(new JsonFile('php://memory')),
        $operation);
    $this->installationManager->notifyInstalls($io);
}
```
> However, in that case, I manually need to update `composer.json` and `composer.lock` files.
> But the package is not present in `installed.json` nor registered in autoloader files.

**If anyone would help, it would be greatly appreciated**

**Comment by alcohol** [comment]
I'm sorry but we do not officially support using Composer as a library. If you want to venture down this path I suggest you familiarize yourself intimately with the codebase first.
