### ISSUE TITLE
Composer is not creating symlink for local repo

### ISSUE THREAD

**Issue by timothymarois** [composer/composer#8021]
I have had this issue with other projects. For some reason can not figure out why it is not working. This is very fustrating and it needs to be addressed.

We need an option for **local path failed**, if we add a repository path and it fails, it needs to output this. I have clearly stated I wanted to use a local repo, I would like it to tell me why it did not load in the local composer.json and instead went straight to the source. This is a problem when debugging. 

1) using "dev-master"
2) cd path does exist
3) cleared out vendors and cache to get a fresh install
4) I've tried swiching `preferred-install` from dist to source and vise-versa

**Nothing works**, it still prefers to download or load from cache. This used to work, I moved directories around recently, but everything is still there. I updated the composer file to reflect those changes, and now it does not work. This is an issue. And **looking more like a bug** unless there is a specific setting that I need to use, but from the docs, I am doing exactly what it asks.

My `composer.json`:

```json
{
    "repositories":
    [
       {
           "type": "path",
           "url": "/Development/PROJECTS/tm-package-name"
       }
   ],

    "require": {
        "user/package-name": "dev-master"
    },
    
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    
    "minimum-stability": "dev",
    "prefer-stable": true
}

```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.4
PHP version: 7.1.22
PHP binary path: /Applications/MAMP/bin/php/php7.1.22/bin/php
```

When I run this command:

```
composer install
```

I get the following output:

```
Loading from cache
```

And I expected this to happen:

```
created symlink
```

Using MacOS

**Comment by alcohol** [comment]
Please provide a reproducible scenario in a gist/repository somewhere.

**Comment by CameronHall** [comment]
@timothymarois I had this same problem. I managed to fix it by deleting the the vendor directory, clearing the composer cache and running `composer update`.
```
rm -rf vendor
composer clearcache
composer update -vvv
```
