### ISSUE TITLE
composer require respect parent constraints

### ISSUE THREAD

**Issue by Lemmork** [composer/composer#8024]
Hi, when I require a package with composer, it always installs the latest version, not respecting the constraints of the parent composer.json.

I will explain it with a simple example.
I have a package called vendor/childpackage with multiple versions.
Version 1.0.0 has these requirements in the composer.json:
```
"require": {
    "vendor/require": "~3",
  },
```
Version 2.0.0 has these requirements in the composer.json:
```
"require": {
    "vendor/require": "~4",
  },
```

Now I have an existing composer.json, which also has this requirement:
```
"require": {
    "vendor/require": "~3",
  },
```
Now I call
`composer require vendor/childpackage`
in the folder with the composer.json.
What I expect is, that composer sees, that the "parent" composer.json requires "vendor/require" in version 3 and pulls version 1.0.0 of vendor/childpackage. But it always pulls version 2.0.0, which is the latest.
Does this only work with platform constraints?

**Comment by alcohol** [comment]
Please offer a reproducible scenario in a public repository. What you are describing is not the correct behavior and could be a potential bug. However, we do not have a magic "fix bugs" button. Without a reproducible scenario, we cannot determine what is wrong, and thus we cannot right the wrong.

**Comment by Lemmork** [comment]
A "fix bugs" button could be a nice github feature. ;-)

You can reproduce it with this composer.json:
```
{
  "name": "test/parent",
  "require": {
    "neos/neos": "~3"
  }
}
```
Place this file in a directory and type:
`composer require neos/nodetypes`

Composer will now add neos/nodetypes ^4.2 to composer.json and the update will fail, because this version requires neos/neos ^4.2.
My expectation was, that composer will resolve this constraints and add neos/nodetypes ~3 to the composer.json.

**Comment by Seldaek** [comment]
That's not something we support as it's way more complex that it sounds.. You are responsible for your version constraints.

**Comment by alcohol** [comment]
Oh, yeah. When you use `require` and provide an explicit version constraint that we cannot match, `require` will just fail. Instead, you should call `require` without a version constraint to get the behaviour that you are looking for. Composer will automatically determine the best possible version.

**Comment by Lemmork** [comment]
When I require vendor/mypackage:* composer resolves the constraints in my case. This was the reason, why I thought it might work with "composer require".

**Comment by alcohol** [comment]
@Seldaek oh, just PHP version? I guess that makes more sense yeah.

@Lemmork but `require vendor/package:*` is definitely not the same as `require vendor/package:^x.y.z`. In the first case you tell Composer you will accept any version and it will run the solving process to determine what we can install. In the latter case you tell Composer you want that package in a version matching at least x.y.z or higher (check how [constraints](https://getcomposer.org/doc/articles/versions.md) work), and if that is not possible because it conflicts with other constraints of currently installed packages then Composer simply cannot satisfy your constraint.

**Comment by Lemmork** [comment]
@alcohol yes I know it is not the same. I thought `require vendor/package` without any version will force composer to search for the version which fits best with all other constraints. I think this would be helpful if you have a lot of packages, because composer can help you in this case to find the right version. Therefore composer can resolve the constraints with `require vendor/package:*` I use it at the moment, then search for the version composer has installed and enter it in the composer.json.
