### ISSUE TITLE
Feature request: Check outdated without installed packages / installed.json

### ISSUE THREAD

**Issue by t3easy** [composer/composer#8025]
ATM I run this to check if a package in my project is outdated:
```
composer install --no-ansi --no-interaction --no-dev --no-progress --no-scripts
composer outdated -D -m --strict
```
As I run that script on every push and periodically on every project it would be usefull to check outdated packages against the composer.lock directly without the need to install the packages first to generate installed.json.

Add a command / parameter to outdated that does the same but for the composer.lock would save a lot of time.

I've seen #6148 was closed because it describes the behaviour as a bug. For me its a feature.

**Comment by Seldaek** [comment]
It might be doable after 2.0, but I'd rather not do such changes to the 1.x to avoid conflicts with ongoing 2.0 changes.

**Comment by fadaile** [comment]
hi all thank you

**Comment by Seldaek** [comment]
You can use --locked already in 2.0.0 with the show command, fixed this now to also be available via the outdated command.
