### ISSUE TITLE
Composer Hook for FinishedAllUpdatesAndInstalls

### ISSUE THREAD

**Issue by darophi** [composer/composer#8026]
I am trying to recompile bootstrap .scss files and move them to the /public/css folder of my project IF the twbs/bootstrap package has been updated or been installed. Currently I am trying to get it working on the **post-package-update** & **post-package-install** hooks, but here the issue is that they are triggered on every single update and install (as expected). That means, if I investigate the operations on the event object, that I will see the update for twbs/bootstrap, but before it actually is being update.

I wonder if there is any support or incoming support for a hook, let's call it "post-all-updated" or "post-all-installed", such that the event that would get sent into that hook would have an array or the like, that resembles which packages have been affected. Thereby avoiding the necessity to check on every single update/install, but just wait until both/either of these operations have finished.

**Comment by alcohol** [comment]
What is wrong with `post-update-cmd` or `post-install-cmd` or `post-dump-autoload`?

https://getcomposer.org/doc/articles/scripts.md#command-events

**Comment by darophi** [comment]
Yes that is actually what I need. How did I oversee this...😄
