### ISSUE TITLE
There is impossible to overwrite loaded files

### ISSUE THREAD

**Issue by salarmehr** [composer/composer#8028]
the issue is that Laravel in particular defines a helpers.php file with some functions that we'd like to override -- they are wrapped in function_exists() statements for this purpose. So our composer.json file requires laravel/framework and we have a "files": ["helpers.php"] to include our custom helpers that overwrite some of the functions that exist in Laravel's helpers.php. The filename "helpers" isn't important: we only need to define our own instances of the functions BEFORE Laravel's helpers get loaded.

However, no matter where we put the files declaration in our composer.json, the vendor packages seem to ALWAYS be loaded first. Inside vendor/composer/autoload_files.php we see something like the following:
```

'f0906e6318348a765ffb6eb24e0d0938' => $vendorDir . '/laravel/framework/src/Illuminate/Foundation/helpers.php',
    '0d9bc4b9d4e9aeb9a29cccb6912fb09f' => $baseDir . '/helpers.php',
```
It's clear that the laravel/framework helpers.php is being loaded before our local helpers.php, so the end effect is that we can't overload the functions.

To clarify, @nanaya, that was exactly what I was talking about, and no, I did not find a solution, just some bad workarounds.

@alcohol here's how to reproduce the problem:

```
helpers.php
<?php

function redirect($url = '/', $code = 302)
{
    header('Location: '.urldecode($url), true, $code);
    exit;
}
composer.json
{
    "autoload": {
        "files": ["helpers.php"]
    },
    "require": {
        "laravel/framework": "^5.6"
    }
}
app.php
<?php
require_once 'vendor/autoload.php';

```
print "Do something here...";
To reproduce, just run php app.php. You'll get a fatal error:

Fatal error: Cannot redeclare redirect() (previously declared in vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:680) in helpers.php on line 7
I expected instead to just be able to run my simple program and have my helpers.php (and its functions) loaded before the ones defined by the vendor package.

**Comment by alcohol** [comment]
#7535
