### ISSUE TITLE
Undefined variable '$hit'

### ISSUE THREAD

**Issue by FLasH3r** [composer/composer#8031]
I've looked at the source to learn a bit more about Composer internals, using Vscode it immediately highlighted an undefined variable in ClassLoader - not sure if it's a valid "bug", but giving the fact that `$hit` will never be true, lines 346-348 are dead code.  

https://github.com/composer/composer/blob/2528654c53b88b490c3b78e111d068bcbe7fef61/src/Composer/Autoload/ClassLoader.php#L345

<img width="772" alt="Screen Shot 2019-03-11 at 9 13 39" src="https://user-images.githubusercontent.com/1413249/54106245-2f7c8080-43de-11e9-99f5-00142995bae3.png">

**Comment by FLasH3r** [comment]
never mind, looked @ http://php.net/apcu_fetch

**Comment by Seldaek** [comment]
The fix is to ignore this nonsense from intelephense, because apcu_fetch creates that variable by reference when it is called.
