### ISSUE TITLE
Relative Path File Collection

### ISSUE THREAD

**Issue by Caffe1neAdd1ct** [composer/composer#8035]
I'm working on an interesting issue when using the `COMPOSER_VENDOR_DIR` environment variable, however the patching library `netresearch/composer-patches-plugin` expects patch files to be listed from the project root relatively, for example:

```
"extra": {
        "patches": {
            "other/dep": {
                "v6.5.4": [
                    {
                        "title": "[BUGFIX] fixes a bug in other/dep/thing.php",
                        "url": "vendor/me/patches/src/other/dep/thing.patch"
                    }
                ]
            }
        }
    }
``` 

I've noted the patching library uses `src/Composer/Util/RemoteFilesystem.php getContents()`:

```
	public function getContents($url) {
		if (array_key_exists($url, $this->cache)) {
			return $this->cache[$url];
		}
		return $this->cache[$url] = $this->remoteFileSystem->getContents($this->getOriginUrl($url), $url, false);
	}
```

$this->remoteFileSystem being the RemoteFilesystem instance.

As not everyone will be changing the vendor path, I can't specify different paths in the patch library composer.json e.g:

```
"extra": {
        "patches": {
            "other/dep": {
                "v6.5.4": [
                    {
                        "title": "[BUGFIX] fixes a bug in other/dep/thing.php",
                        "url": "other-vendor-folder/me/patches/src/other/dep/thing.patch"
                    }
                ]
            }
        }
    }
``` 

I've got two options:

1) Request a change to `src/Composer/Util/RemoteFilesystem.php` to translate any paths starting with `vendor/` to `COMPOSER_VENDOR_DIR . '/'` which might not be wanted and or might break things (though worth asking the question)

2) Request a change to `netresearch/composer-patches-plugin` in their getContents method to make this translation.

So my question is would it be possible for composer to automatically translate requests for files starting 'vendor/' to use the COMPOSER_VENDOR_DIR environment variable when requesting local filesystem file content?

Any other solutions or recommendations more than welcome :+1:

**Comment by alcohol** [comment]
This seems like logic that does not belong in the `getContents()` method. So I would say that the answer to your question is a definite "no".

**Comment by Caffe1neAdd1ct** [comment]
@alcohol Cheers for the review!

I did see a lot of mapping for hosts and other logic in there and wondered if it would be a useful addition, looking at it from a composer point of view, it deals with the paths fine and shouldn't need any mappings in the download/getContents method.

So the correct solution would be the library/plugin correctly resolving the vendor path, e.g: https://github.com/netresearch/composer-patches-plugin/pull/30/files

Just wanted to make sure the change was applied to the best possible place :+1:

**Comment by alcohol** [comment]
I think it would be safer indeed if the plugin respected the environment variables that Composer supports.
