### ISSUE TITLE
composer why-not/prohibits insists that a package must be installed

### ISSUE THREAD

**Issue by ssaki** [composer/composer#8036]
I'm trying to `composer require` a package and it fails due to dependency conflict.
I then try to execute `composer why-not vendor/package:version` and I'm getting the following message:
"Could not find package *vendor*/*package* in your project."

This seems wrong as if I had the package then I succeeded installing it and therefore I don't have to check why it failed installing.

Composer is v1.8.4

**Comment by alcohol** [comment]
You have to add the package as a requirement in your `composer.json`. Because your invocation of `require` failed, your `composer.json` was reset to its previous state and thus it contains no such requirement. Manually add the requirement and then run `why-not` (or `prohibits`).

**Comment by ssaki** [comment]
The `why-not` command has a mandatory argument for the package of interest. Nothing in command's description suggests that what you stated is required. I'd suggest if that's the case that the command description be updated with note/disclaimer about that. 

IMO this needs fixing as it's hardly user friendly or even rational (as one passes the package via the mandatory argument anyway), but I have no time to fix it myself right now, so I won't complain too much on closing the issue :)

**Comment by sam452** [comment]
Hmm, found this issue. 
`composer -V` => 1.8.4
my composer.json snippet:
`require: `
...
`"drupal/entity_usage": "^2.0",`
`"drupal/paragraphs": "^1.8"`
Save composer.json
`composer prohibits drupal/entity_usage` or any other variation of the package name.
Could not find package "drupal/entity_usage" in your project.
Glad it works for you, haven't figured out why it's not working for me.

**Comment by alcohol** [comment]
I could have been mistaken. 
I have not used why-not/ptohibits in a long time. 

On closer inspection, it would seem that it only works for letting you know why it cannot update an existing package to a specific version (e.g. when you run update but nothing gets updated even though a newer version exists).

When you run require and it fails, the command should already tell you why it fails. You will not get a more clear answer from why-not/prohibits.

**Comment by Leksat** [comment]
Maybe the command description should be changed from "Displays detailed information about why a package cannot be _installed_" to "Displays detailed information about why a package cannot be _updated_"?

Or maybe the command should be removed? Because `composer require` does the same job anyway.
