### ISSUE TITLE
composer diagnose should also check for missing/modified files in packages

### ISSUE THREAD

**Issue by connorshea** [composer/composer#8040]
I recently had a problem with a package acting incorrectly that took almost an hour to solve because `composer diagnose` didn't warn me about a package having been modified. (In hindsight, obviously one of the first things I should have done was delete the `vendor/` directory and reinstall, but I didn't because I'm a dummy.)

If you modify or delete a file in a package and then run `composer diagnose`, it won't point out any problem with your current setup. So I ended up going on a wild goose chase trying to figure out the problem.

I know `composer status` exists and does this (well, I know _now_), but `diagnose` seems to me like it should also check for things like that. At the least, it'd be nice if –  at the end of `composer diagnose` – it told the user about the existence of `composer status` as a possible way to detect problems.

Thanks for composer, it's worked quite well so far other than that :)

**Comment by alcohol** [comment]
`diagnose` is meant to verify your Composer configuration and setup. It it not meant to verify your `vendor` contents.
