### ISSUE TITLE
Composer script timeouts not behaving as expected

### ISSUE THREAD

**Issue by Antnee** [composer/composer#8041]
_I want to stress from the title, **AS EXPECTED**. This whole issue may be because my expectations are incorrect._

----

We use Composer's scripts quite extensively. We even use it to automate our dev Docker environments, so commands like `composer serve` will run a Docker Compose command behind the scenes. Basically, everything goes through Composer. So we can flush caches, build the front-end etc, all through Composer scripts.

We like this solution because it's one place to go to. It's easy for devs to learn, and let's be honest, pretty much everyone working with PHP understands Composer, right? Because everything runs inside Docker, our dev environments essentially have three dependencies: PHP, Composer and Docker. This works better cross-OS than using shell scripts, for example.

Anyway, this has gone really well, except for a couple of problems:

We have a `composer webpack` command, which spins up a Node container and runs a `webpack --watch` command which will spot any changes to our SCSS, for example, and automatically build it, rather than us needing to manually compile after every save. This will eventually timeout, as expected. We have two options that we can see: Increase the process timeout to something enormous (feels wrong), or we pass in the `--timeout=0` argument to disable the timeout for this script. And here's the problem:

1. We can't make it part of the Composer Script config, it has to be part of the command that the dev enters, which means that the convenience is reduced. The command currently looks like this:

    ```json
    "scripts": {
      "node": "docker-compose run --rm -w /app node",
      "webpack": "@node webpack --watch"
    }
    ```
    (the `node` entry is there for convenience since we reuse it for a few commands).
  
    I wanted the command to be more like this:

    ```json
    "scripts": {
      "node": "docker-compose run --rm -w /app node",
      "webpack": "@node webpack --watch --timeout=0"
    }
    ```
    This does not work as the timeout argument is passed to the container, not Composer. Can we do this, somehow?

2. The other problem is that for us to pass in the `--timeout=0` argument, we can't use the shorthand `composer webpack`. We have to use `composer run webpack`. OK, it's only four extra characters, but it's reducing convenience again. Developers either need to get out of the habit of just running `composer test`, or `composer serve` and to start typing `composer run test`, or they need to remember that the Webpack script is an exception to the rule, and they'll need to not only add the timeout, but also the additional `run` parameter.

I had a quick look, and in all honesty, it wasn't something that was immediately obvious on how to fix (for either problem).

Can you advise is this actually a fault? Can either be fixed? And if so, can anyone point me in the right direction so that I can give it a go and submit a PR?

**Comment by alcohol** [comment]
Did you try `@node webpack -- --watch --timeout=0`?

**Comment by Antnee** [comment]
No. That doesn't look right to me. How would that help? I can try it later when I'm home, but I can't see how it'd help

**Comment by alcohol** [comment]
The `--` separator tells it the rest to be followed are not arguments for the `composer run` invocation itself.

But I am honestly quite confused by your story. I have no idea where the `--timout` argument should end up and where it ends up right now.

**Comment by Antnee** [comment]
The `--timeout=0` argument is for Composer, not Webpack. But apparently it doesn't work with the shorthand `composer webpack` command. We have to do something approximating `composer run-script webpack --timeout=0`, otherwise Composer's timeout shuts the script down, which we don't want. This command should keep running until it's terminated

**Comment by alcohol** [comment]
Ok, so you should just call `composer run-script --timeout 0 -- webpack`.

I understand you consider this a problem, because you find it inconvenient. However, that is something you will have to learn to live with. Composer was never meant to be used as a full featured build and development tool. It is a dependency manager first and foremost. A lot of the extra features we offer are exactly that, extras. I see very little logic behind trying to support every conceivable workflow out there, because it would make maintaining Composer an absolute nightmare.

If you want to be lazy, use a `Makefile`.

**Comment by Antnee** [comment]
That doesn't make any sense. You've made it even more characters than what already works. And I appreciate that this is not exactly what it's for, but Composer has the facility to allow custom commands already, as I understand it to make DX better, but it could do with a minor change. And it is _minor_.

I asked why it's not possible to just do `composer webpack --timeout=0` instead of `composer run webpack --timeout=0`. This second command does what we need already, but why do we need to add the `run` argument when `composer webpack` works, albeit without being able to override the timeout?

**Comment by alcohol** [comment]
Because the `timeout` argument is for the `run` command specifically. And what you are doing is abusing the "smart" command resolver, which basically means that when you pass Composer a command that does not exist, it first checks if a script with such a name exists. If it does, it uses some magic to invoke it. But this flow does not invoke the `run-script` command, and thus the `timeout` argument is not available.

**Comment by alcohol** [comment]
> You've made it even more characters than what already works. 

I merely gave you the fully qualified official version. You can shorten it where possible.

**Comment by alcohol** [comment]
If you really want to fix this, you're welcome to submit a PR. But convenience features are not maintained or developed by us because it is a waste of what little time we have.

I suggest you look at https://github.com/composer/composer/blob/522ea033a3c6e72d72954f7cd019a3b75e28f391/src/Composer/Console/Application.php#L238-L259

and https://github.com/composer/composer/blob/522ea033a3c6e72d72954f7cd019a3b75e28f391/src/Composer/Command/ScriptAliasCommand.php

**Comment by Antnee** [comment]
To be fair, I didn't ask anyone to fix it. I asked if I've misunderstood something and where to look to see if I can fix it so I can submit a PR. I'll take a look and see what I can come up with

**Comment by Seldaek** [comment]
IMO there is no easy way to address this. What you want in short is a per-script process timeout value, right? That sounds like a very use case specific thing to me to add a new config item for it..

**Comment by alcohol** [comment]
I think it can be fixed by adding the `timeout` flag as an argument for the `ScriptAliasCommand` (copy and paste the implementation from `RunScriptCommand` basically).

**Comment by Seldaek** [comment]
Yeah that might fix one of the UX quirks of it.

**Comment by alcohol** [comment]
You will still have to pass `--timeout 0` from the CLI though, I don't think you can use this within the script definition itself in your `composer.json`.

**Comment by Antnee** [comment]
It would be nice to have a per-script timeout, yes @Seldaek. That would hit the nail on the head. But yeah, it is very use-case specific and I appreciate not exactly a good fit for Composer. Being able to use the `timeout` argument with the shorthand would be better, though. So
```
$ composer webpack --timeout=0
```
That's _better_

**Comment by Seldaek** [comment]
Right, feel free to PR that, it sounds like a reasonable addition.

**Comment by Antnee** [comment]
I will see if I can work it out some time soon when I have a moment free. At least we've established that I'd not misunderstood something and that the feature isn't supposed to already be there. Thanks all

**Comment by Seldaek** [comment]
@Antnee see #8088

**Comment by Antnee** [comment]
Oh, that's much nicer than anything I'd have come up with!
