### ISSUE TITLE
composer update <package> updates extraneous packages

### ISSUE THREAD

**Issue by cxj** [composer/composer#8044]
My `composer.json`:
```json
{
    "name": "foo/someproject",
    "type": "project",
    "license": "proprietary",
    "require": {
        "foo/templates-web2": "~1",
        "foo/web-responders": "~1.1",
        "components/jquery": "^3.1",
        "radar/adr": "~1.0",
        "relay/middleware": "~1.0",
        "zendframework/zend-diactoros": "~1.0",
        "php": ">=7.1.0"
    },
    "autoload": {
        "psr-4": {
            "Foo\\Web\\": "src/"
        }
    }
}
```

Output of `composer diagnose`:
```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6      8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369       153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.4
PHP version: 7.2.11
PHP binary path: /usr/local/Cellar/php/7.2.11/bin/php
```

When I run this command:
```
$ composer update foo/web-responders
```

I get the following output:
```
$ composer update foo/web-responders
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Updating foo/templates-web2 (1.2.31 => 1.2.32): Loading from cache
  - Updating foo/web-responders (1.1.3 => 1.1.4): Downloading (100%)
Writing lock file
```

And I expected this to happen:

I expect the output to look like the following.  That is, I expect **only** the package I requested to be updated, not some random other package that has a newer minor version.

```
$ composer update foo/web-responders
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Updating foo/web-responders (1.1.3 => 1.1.4): Downloading (100%)
Writing lock file
```

Is this a bug, or documentation error?   The documentation clearly says the *only* the specified package(s) will be updated.

**Comment by xuanquynh** [comment]
I think it's not a bug. I guess the `foo/web-responders` package depends on the `foo/templates-web2` package. So, updating a package will be done after updating it's dependencies.

One more thing, a newer minor version doesn't break your application, isn't it? It just give more functionality and you may use or not.

**Comment by alcohol** [comment]
@xuanquynh actually, even if it was a dependency, the `--with-dependencies` flag should have been added in this case to allow it to update.

@cxj are you sure your local vendor directory was not out of sync with the latest json/lock changes? It could be that pulled in a lock file change but forgot to run composer install, and during this update invocation it not only updated your package but also installed a package that was already updated in the lock file.

**Comment by xuanquynh** [comment]
I missed the situation in which the vendor directory might be outdated of `composer.lock` file. I will check the available options more carefully.

Thank you so much!

**Comment by Seldaek** [comment]
Make sure you run `composer install` to sync up your vendor dir before running a partial update, if that still updates more than expected then you can report it, but I doubt that'd be the case. If you don't sync up then it might do other updates to bring your vendor dir in sync with the lock file, but it won't technically update those packages from lock file.. which you should be able to confirm in the changes you see in the lock file with git diff.

**Comment by cxj** [comment]
Although I can't imagine how my project could have gotten into the state where my vendor directory was somehow behind a revision from the lock file for that extra, unexpected package, I see that this is a path for this behavior that is correct operation of `composer`.  I will attempt to pay careful attention to this detail in the future.

**Comment by cxj** [comment]
Thank you.
