### ISSUE TITLE
Can not install composer if php 7.3

### ISSUE THREAD

**Issue by dalph** [composer/composer#8046]
When I run this command:

```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

```

I get the following output:

```
Parse error: syntax error, unexpected end of file, expecting ')' in Command line code on line 1
```

And I expected this to happen:

**Comment by alcohol** [comment]
Unable to reproduce.

**Comment by xuanquynh** [comment]
I can't reproduce this. I ran this command in a docker container with php-cli v7.3.3 and everything worked normally. I got the `composer-setup.php` file.

**Comment by alcohol** [comment]
Please provide the output of

```
which php
type php
php --ini
php -m
php --version
```

**Comment by Seldaek** [comment]
This is most likely a quoting issue, which shell/OS/terminal app are you on?

**Comment by dalph** [comment]
(php 7.3)c3030@h2:~/1.na4u.ru$ which php
/usr/bin/php
(php 7.3)c3030@h2:~/1.na4u.ru$ type php
php is hashed (/usr/bin/php)
(php 7.3)c3030@h2:~/1.na4u.ru$ php --version
PHP 7.3.0 (cli) (built: Dec 13 2018 05:00:00) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.0, Copyright (c) 1999-2018, by Zend Technologies
(php 7.3)c3030@h2:~/1.na4u.ru$ php --ini
Configuration File (php.ini) Path: /etc
Loaded Configuration File:         /home/c3030/1.na4u.ru/etc/php.ini
Scan for additional .ini files in: /etc/hosting2/php-defaults/php7.3
Additional .ini files parsed:      /etc/hosting2/php-defaults/php7.3/extensions.ini,
/etc/hosting2/php-defaults/php7.3/zend_extensions.ini

(php 7.3)c3030@h2:~/1.na4u.ru$ php -m
[PHP Modules]
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
exif
fileinfo
filter
ftp
gd
geoip
gettext
gmp
hash
iconv
imagick
imap
intl
json
ldap
libxml
mbstring
memcache
memcached
mongodb
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
pspell
redis
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by alcohol** [comment]
What is this `(php 7.3)` prefix? Are you using some kind of runtime / version tool to manage php versions?

**Comment by Falseee** [comment]
Have the same issue, fresh installed ubuntu and composer.
```
[false@false-desktop:~]$ which php
/usr/bin/php
[false@false-desktop:~]$ type php
php is hashed (/usr/bin/php)
[false@false-desktop:~]$ php --version
PHP 7.3.3-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Mar  7 2019 20:31:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.3, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.3-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
[false@false-desktop:~]$ php --ini
Configuration File (php.ini) Path: /etc/php/7.3/cli
Loaded Configuration File:         /etc/php/7.3/cli/php.ini
Scan for additional .ini files in: /etc/php/7.3/cli/conf.d
Additional .ini files parsed:      /etc/php/7.3/cli/conf.d/10-opcache.ini,
/etc/php/7.3/cli/conf.d/10-pdo.ini,
/etc/php/7.3/cli/conf.d/20-calendar.ini,
/etc/php/7.3/cli/conf.d/20-ctype.ini,
/etc/php/7.3/cli/conf.d/20-exif.ini,
/etc/php/7.3/cli/conf.d/20-fileinfo.ini,
/etc/php/7.3/cli/conf.d/20-ftp.ini,
/etc/php/7.3/cli/conf.d/20-gettext.ini,
/etc/php/7.3/cli/conf.d/20-iconv.ini,
/etc/php/7.3/cli/conf.d/20-json.ini,
/etc/php/7.3/cli/conf.d/20-phar.ini,
/etc/php/7.3/cli/conf.d/20-posix.ini,
/etc/php/7.3/cli/conf.d/20-readline.ini,
/etc/php/7.3/cli/conf.d/20-shmop.ini,
/etc/php/7.3/cli/conf.d/20-sockets.ini,
/etc/php/7.3/cli/conf.d/20-sysvmsg.ini,
/etc/php/7.3/cli/conf.d/20-sysvsem.ini,
/etc/php/7.3/cli/conf.d/20-sysvshm.ini,
/etc/php/7.3/cli/conf.d/20-tokenizer.ini

[false@false-desktop:~]$ php -m
```

**Comment by subotkevic** [comment]
Same issue. Any news?

**Comment by jerrybendy** [comment]
Unable to reproduce in PHP 7.3. But this issue repeats in PHP 7.1 and composer 1.8.6.

```
Warning: Unexpected character in input:  ' in phar:///app/web/composer.phar/bin/composer on line 62

Parse error: syntax error, unexpected ')' in phar:///app/web/composer.phar/src/bootstrap.php on line 25
```

**Comment by khru** [comment]
I have the same Issue on a docker container.
