### ISSUE TITLE
Package scripts are not executed when updating application packages

### ISSUE THREAD

**Issue by antonioribeiro** [composer/composer#8049]
Are Composer scripts supposed to execute automatically for all packages installed on an app?

I believe they are but I'm not sure why [this one](https://github.com/Ocramius/PackageVersions/blob/master/composer.json):

```json
"scripts": {
    "post-update-cmd":  "PackageVersions\\Installer::dumpVersionsClass",
    "post-install-cmd": "PackageVersions\\Installer::dumpVersionsClass"
}
```

works fine, as I see them executing when I update or install packages in the application root, but [my own](https://github.com/antonioribeiro/google2fa/blob/v4.0.2/composer.json) doesn't:

```json
"scripts": {
    "post-update-cmd": [
        "@php -r 'echo \"\\e[41m===== WARNING ===== Please upgrade to pragmarx/google2fa:^5.0 and check the README  \";'"
    ],
    "post-install-cmd": [
        "@php -r 'echo \"\\e[41m===== WARNING ===== Please upgrade to pragmarx/google2fa:^5.0 and check the README  \";'"
    ]
},
```

It doesn't work when I `composer update` in the application root dir, but if I enter the package folder it works fine.

Output of `composer diagnose`:

```
$ composer diagnose
Checking composer.json: WARNING
require.paragonie/random_compat : unbound version constraints (>=1.0) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.4
PHP version: 7.3.2
PHP binary path: /usr/local/Cellar/php/7.3.2/bin/php
```

**Comment by barryvdh** [comment]
See https://getcomposer.org/doc/articles/scripts.md

> Note: Only scripts defined in the root package's composer.json are executed. If a dependency of the root package specifies its own scripts, Composer does not execute those additional scripts.

**Comment by stof** [comment]
The `post-update-cmd` command of the `ocramius/package-versions` is **not** executed when installing it in your project.
But the `ocramius/package-versions` is a composer plugin. So it is able to hook into the update process.

**Comment by antonioribeiro** [comment]
@barryvdh, I read that in the docs, but got confused by package-versions, but @stof just cleared that for me. Thank you both.
