### ISSUE TITLE
The "discard-changes" option does not work

### ISSUE THREAD

**Issue by gergelypap** [composer/composer#8054]
Composer JSON schema mentions an option called [discard-changes](https://github.com/composer/composer/blob/master/res/composer-schema.json#L232), which can override the default behaviour for dirty updates in vendor packages. It defaults to false, however it still asks the user about discarding changes when it is set to `true` or `"stash"`.

Reproduction steps:
1. Set discard-changes to true: `composer config discard-changes true`
2. Modify some vendor package code.
3. Run `composer update vendor/package` on the package you modified.

Example output:

```
Gathering patches for dependencies. This might take a minute.
  - Updating drupal/password_policy dev-3.x (4adce53 => 176dd7e):     The package has modified files:
    M password_policy.install
    M password_policy.module
    M password_policy.permissions.yml
    M src/EventSubscriber/PasswordPolicyEventSubscriber.php
    Discard changes [y,n,v,d,s,?]?
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.4
PHP version: 7.2.16
PHP binary path: /usr/bin/php7.2
```

Also the documentation mentions nothing about this option: https://getcomposer.org/doc/04-schema.md

**Comment by alcohol** [comment]
I think it will ask as long as you run in interactive mode. In non-interactive mode, the config setting determines the behaviour.

**Comment by alcohol** [comment]
See https://github.com/composer/composer/blob/66a77ed21031d99b8f74c527932fef0b7aace1d9/src/Composer/Downloader/GitDownloader.php#L245-L259

**Comment by gergelypap** [comment]
Oh, I see. Thanks for the info!

**Comment by alcohol** [comment]
I'm not sure what needs to be updated exactly, but PRs are welcome if you think this could be presented better / more detailed.
