### ISSUE TITLE
PHP Fatal error:  strict_types declaration must be the very first statement in the script in /usr/share/php/Composer/Plugin/PluginManager.php(178) : eval()'d code on line 3

### ISSUE THREAD

**Issue by maxyc** [composer/composer#8057]
maxyc@maxyc-System-Product-Name /var/www/yiinextrun $ php -v
PHP 7.2.16-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Mar  7 2019 20:23:06) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.16-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.0, Copyright (c) 2002-2019, by Derick Rethans

maxyc@maxyc-System-Product-Name /var/www/yiinextrun $ composer require "mito/yii2-sentry"
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Using version ^1.0 for mito/yii2-sentry
./composer.json has been updated
PHP Fatal error:  strict_types declaration must be the very first statement in the script in /usr/share/php/Composer/Plugin/PluginManager.php(178) : eval()'d code on line 3
PHP Stack trace:
PHP   1. {main}() /usr/bin/composer:0
PHP   2. Composer\Console\Application->run($input = *uninitialized*, $output = *uninitialized*) /usr/bin/composer:44
PHP   3. Composer\Console\Application->run($input = *uninitialized*, $output = *uninitialized*) /usr/share/php/Composer/Console/Application.php:99
PHP   4. Composer\Console\Application->doRun($input = *uninitialized*, $output = *uninitialized*) /usr/share/php/Symfony/Component/Console/Application.php:120
PHP   5. Composer\Console\Application->doRun($input = *uninitialized*, $output = *uninitialized*) /usr/share/php/Composer/Console/Application.php:166
PHP   6. Composer\Console\Application->doRunCommand($command = *uninitialized*, $input = *uninitialized*, $output = *uninitialized*) /usr/share/php/Symfony/Component/Console/Application.php:189
PHP   7. Composer\Command\RequireCommand->run($input = *uninitialized*, $output = *uninitialized*) /usr/share/php/Symfony/Component/Console/Application.php:841
PHP   8. Composer\Command\RequireCommand->execute($input = *uninitialized*, $output = *uninitialized*) /usr/share/php/Symfony/Component/Console/Command/Command.php:256
PHP   9. Composer\Command\RequireCommand->getComposer($required = *uninitialized*, $disablePlugins = *uninitialized*) /usr/share/php/Composer/Command/RequireCommand.php:147
PHP  10. Composer\Console\Application->getComposer($required = *uninitialized*, $disablePlugins = *uninitialized*) /usr/share/php/Composer/Command/BaseCommand.php:53
PHP  11. Composer\Factory::create($io = *uninitialized*, $config = *uninitialized*, $disablePlugins = *uninitialized*) /usr/share/php/Composer/Console/Application.php:244
PHP  12. Composer\Factory->createComposer($io = *uninitialized*, $localConfig = *uninitialized*, $disablePlugins = *uninitialized*, $cwd = *uninitialized*, $fullLoad = *uninitialized*) /usr/share/php/Composer/Factory.php:532
PHP  13. Composer\Plugin\PluginManager->loadInstalledPlugins() /usr/share/php/Composer/Factory.php:354
PHP  14. Composer\Plugin\PluginManager->loadRepository($repo = *uninitialized*) /usr/share/php/Composer/Plugin/PluginManager.php:76
PHP  15. Composer\Plugin\PluginManager->registerPackage($package = *uninitialized*, $failOnMissingClasses = *uninitialized*) /usr/share/php/Composer/Plugin/PluginManager.php:240

Fatal error: strict_types declaration must be the very first statement in the script in /usr/share/php/Composer/Plugin/PluginManager.php(178) : eval()'d code on line 3

Call Stack:
    0.0033     395888   1. {main}() /usr/bin/composer:0
    0.0791    2834384   2. Composer\Console\Application->run(???, ???) /usr/bin/composer:44
    0.0814    3146504   3. Composer\Console\Application->run(???, ???) /usr/share/php/Composer/Console/Application.php:99
    0.0822    3227032   4. Composer\Console\Application->doRun(???, ???) /usr/share/php/Symfony/Component/Console/Application.php:120
    0.0833    3316528   5. Composer\Console\Application->doRun(???, ???) /usr/share/php/Composer/Console/Application.php:166
    0.0833    3316528   6. Composer\Console\Application->doRunCommand(???, ???, ???) /usr/share/php/Symfony/Component/Console/Application.php:189
    0.0834    3316528   7. Composer\Command\RequireCommand->run(???, ???) /usr/share/php/Symfony/Component/Console/Application.php:841
    0.0837    3319752   8. Composer\Command\RequireCommand->execute(???, ???) /usr/share/php/Symfony/Component/Console/Command/Command.php:256
    4.1365  154411880   9. Composer\Command\RequireCommand->getComposer(???, ???) /usr/share/php/Composer/Command/RequireCommand.php:147
    4.1365  154411880  10. Composer\Console\Application->getComposer(???, ???) /usr/share/php/Composer/Command/BaseCommand.php:53
    4.1365  154411880  11. Composer\Factory::create(???, ???, ???) /usr/share/php/Composer/Console/Application.php:244
    4.1365  154411920  12. Composer\Factory->createComposer(???, ???, ???, ???, ???) /usr/share/php/Composer/Factory.php:532
    4.1652  154457616  13. Composer\Plugin\PluginManager->loadInstalledPlugins() /usr/share/php/Composer/Factory.php:354
    4.1652  154457616  14. Composer\Plugin\PluginManager->loadRepository(???) /usr/share/php/Composer/Plugin/PluginManager.php:76
    4.2026  155265048  15. Composer\Plugin\PluginManager->registerPackage(???, ???) /usr/share/php/Composer/Plugin/PluginManager.php:240

Variables in local scope (#15): biiig text...

**Comment by xabbuh** [comment]
Which version of Composer do you use?

**Comment by alcohol** [comment]
Looks like he is trying to use a plugin that is written with a strict_types declaration. That's not going to work.

**Comment by alcohol** [comment]
Run `composer require --no-plugin vendor/package` and it will work.
