### ISSUE TITLE
Option for `check-platform-reqs` to check dependencies' requirements too

### ISSUE THREAD

**Issue by paragonie-scott** [composer/composer#8058]
(Discarding the template for a moment...)

If you'd like to see the problem for yourself, do this:

1. Install Debian Stretch onto a brand new virtual machine.
2. Install `php7.2-cli php7.2-common` from the Sury packages, and nothing else.
3. Try to install Magento 2.3.0 community edition via Composer.

You'll run into what I like to call "the aptitude-composer feedback loop from hell".

I'd like to use `composer check-platform-reqs` to, in one go, obtain a list of PHP extensions that are found in dependencies' `composer.json` files rather than the main project's. As of right now, `check-platform-reqs` doesn't resolve dependencies unless you've already successfully run `composer install` before.

(Alternatively, having a `composer install` failure give you a discrete and complete list of missing extensions in one go would save a lot of headache.)

**Proposal:** Add a `--recursive` flag to the `check-platform-reqs` command that enumerates missing PHP extensions required by any dependency.

That will turn the feedback look of hell into:

1. `composer check-platform-reqs --recursive`
2. Take note of all extensions needed
3. `apt-get install ...`
4. `composer install`

**Comment by Seldaek** [comment]
check-platform-reqs already runs recursively if it has a composer.lock to work with and you use `--no-dev`. In that case it goes through the lock file and checks everything. I'd say that's the optimal operation mode when deploying something, as you should really deploy from a lock file you built up on a dev machine.

If `--no-dev` is not passed in tho, it uses the local repository (meaning packages which are installed). That is kinda useless behavior if you haven't installed anything yet, which is the typical use case for this command really. It probably should try to use the lock file if present in all cases. And warn if no lock file is present that results will probably be sub-par.

Like explained on twitter by Nils, recursively showing things without lock file is just not a practical option, and running an update command in that case is probably the better approach.

**Comment by Seldaek** [comment]
If you are missing a lock file, you can run an `update --ignore-platform-reqs` to create one and then use `check-platform-reqs --no-dev` to see what's missing from the system I guess.

**Comment by paragonie-scott** [comment]
Oh, yeah, that would solve the problem elegantly.

**Comment by Seldaek** [comment]
Gonna keep this open because the default behavior (without --no-dev) still should be improved.
