### ISSUE TITLE
composer depends doesn't factor in 'provide' packages

### ISSUE THREAD

**Issue by madmatt** [composer/composer#8059]
**My `composer.json`:**

```json
{
  "require": {
    "omnipay/common": "^3"
  }
}
```

**Output of `composer diagnose`:**

```bash
$ composer diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.4
PHP version: 7.1.24 - Package overridden via config.platform (actual: 7.2.1)
PHP binary path: /usr/local/Cellar/php/7.2.1_12/bin/php

```

**When I run this command:**

```bash
composer why php-http/buzz-adapter
```

**I get the following output:**

```bash
$ composer why php-http/buzz-adapter
There is no installed package depending on "php-http/buzz-adapter"
```

**And I expected this to happen (aka further clarification):**

`omnipay/common` has the following in its composer.json:
```json
"require": {
  "php-http/client-implementation": "^1"
}
```

`php-http/buzz-adapter` has the following in its composer.json:
```json
"provide": {
  "php-http/client-implementation": "1.0"
}
```

I presume this is why the package is being installed, as it's the only link between two modules in my lock file. The `provide` schema is [not documented significantly|https://getcomposer.org/doc/04-schema.md#provide], so I can only guess that is how it works.

**Could `composer depends`/`composer why` be updated to support this use-case?**

For example, if I run `composer why php-http/client-implementation`, then I get output that I expect:
```bash
$ composer why php-http/client-implementation
omnipay/common  v3.0.2  requires  php-http/client-implementation (^1)
```

But to figure that link out requires manual poking in the composer.lock file.

Thanks for your time, and thanks for such a great project!

**Comment by Seldaek** [comment]
It's weird though because a provide shouldn't be enough reason for a package to be selected in the first place. So at some point most likely something required the buzz-adapter explicitly, and then that require was dropped but the package probably remained as the php-http/client-implementation is required and it provides it.

If you explicitly remove it from the vendor dir, and then run a `composer update --dry-run`, I suspect you'll get an error about client-implementation being required.

Anyway we should for sure improve `depends` to support this if it's feasible as it'd be a good improvement regardless.

**Comment by madmatt** [comment]
Hey @Seldaek, thanks for checking this one out. I have since realised that was in fact the case, a previous git commit did require `php-http/buzz-adapter`, but that was then removed and as you say the package ended up lingering despite not being explicitly required anywhere.

**Comment by stof** [comment]
@Seldaek I suggest to close that one, as Composer 2 won't take previously installed packages into account to satisfy a requirement

**Comment by Seldaek** [comment]
Right shouldn't be an issue anymore.
