### ISSUE TITLE
composer checking PHP version of the bash not of the server

### ISSUE THREAD

**Issue by Uhradone** [composer/composer#8061]
My `composer.json`:

```
{
    "name": "zazuberlin/start2019",
    "type": "project",
    "description": "This is the general TYPO3 page setup from 2019. It includes zazusitepackage.",
    "authors": [
        {
            "name": "Thomas Hezel",
            "role": "Developer",
            "email": "film@inter.net"
        }
    ],
    "license": "GPL-2.0-or-later",
    **"config": {
		"platform": {
			"php": "7.2"
		}
	},**
    "repositories": [
        {
            "type": "vcs",
            "url": "https://thomas-hezel@bitbucket.org/thomas-hezel/zazupackage.git"
        },
        {
            "type": "composer",
            "url": "https://composer.typo3.org/"
        }
    ],
    "require": {
        "helhum/typo3-console": "^5.5.5",
        "typo3/minimal": "^9.5",
        "typo3/cms-adminpanel": "^9.5",
        "typo3/cms-belog": "^9.5",
        "typo3/cms-beuser": "^9.5",
        "typo3/cms-felogin": "^9.5",
        "typo3/cms-filemetadata": "^9.5",
        "typo3/cms-fluid-styled-content": "^9.5.5",
        "typo3/cms-form": "^9.5",
        "typo3/cms-impexp": "^9.5",
        "typo3/cms-info": "^9.5",
        "typo3/cms-linkvalidator": "^9.5",
        "typo3/cms-lowlevel": "^9.5",
        "typo3/cms-opendocs": "^9.5",
        "typo3/cms-redirects": "^9.5",
        "typo3/cms-reports": "^9.5",
        "typo3/cms-rte-ckeditor": "^9.5",
        "typo3/cms-scheduler": "^9.5",
        "typo3/cms-seo": "^9.5",
        "typo3/cms-setup": "^9.5",
        "typo3/cms-sys-note": "^9.5",
        "typo3/cms-tstemplate": "^9.5",
		"typo3/cms-t3editor": "^9.5",
        "typo3/cms-recycler": "^9.5",
        "zazuberlin/zazupackage": "@dev-master"
    },
    "scripts":{
		"typo3-cms-scripts": [
			"typo3cms install:fixfolderstructure",
			"typo3cms install:generatepackagestates"
		],
		"post-autoload-dump": [
			"@typo3-cms-scripts"
		]
	}
}
```

And I expected this to happen:

Composer is validating the PHP version according to the PHP version of the bash and not of the version e.g. Apache2 is running on. Most ISPs run older version for their bash instances compared to the server version. This makes it impossible to use composer mode e.g. for TYPO3 installation.

Is there a workaround or an adjustment to tell composer to check PHP versions of the server and not the bash?

**Comment by xabbuh** [comment]
Composer can only use the PHP version that you are executing it with. So if you run it on the command-line, it doesn't know anything about the PHP version that is in the web context. If you install dependencies using a different PHP version than the one that serves your application, you *can* tell Composer about that version explicitly using the [platform](https://getcomposer.org/doc/06-config.md#platform) config. But you still need to make sure that the PHP version used to install dependencies is compatible with any scripts that are executed afters (or run `install` with the `--no-scripts` option).

**Comment by Uhradone** [comment]
Thank you for the fast reply!
The "platform config." is exactly what the TYPO3 core team uses as standard. This has the consequence that using the standard procedure installation will fail due to bash-php-versions. But I didn't check whether skipping the platform command will result in an installation. But I also understand that it is hard for composer to check the target system for php-versions instead checking the cli-version.

**Comment by alcohol** [comment]
Bash? I think you mean the version specified in `config.platform.php`. This overrides the actual php version detected on the host. In other words, behaving exactly as expected.

**Comment by Seldaek** [comment]
Just for reference, link to the docs of platform config https://getcomposer.org/doc/06-config.md#platform
