### ISSUE TITLE
composer.lock file should be sanity checked before making file changes

### ISSUE THREAD

**Issue by joachim-n** [composer/composer#8062]
I did 'composer require foo/bar'

```
[SNIP]
./composer.json has been updated

  [Seld\JsonLint\ParsingException]
  "./composer.lock" does not contain valid JSON
```

I was left with the update only partially complete and files in an unstable state.

This happened because there had been a merge conflict in my composer.lock file, and my git GUI app hadn't actually discarded the unwanted changes.

It would be a good idea to parse composer.lock for a sanity check before making any changes to files.

**Comment by alcohol** [comment]
Doesn't `composer validate` warn you about this? I don't think we should be writing sanity checks for everything. It's ok to just let things fail sometimes.

**Comment by joachim-n** [comment]
My point is that there is already a sanity check later on, in that it crashes if the JSON is malformed. I am saying that attempting to load and parse the lock file's JSON should happen before any changes are made to the files.

**Comment by alcohol** [comment]
I understood what you said. I just disagree that we need to sanity check everything. Sometimes failure is an acceptable path.

**Comment by Seldaek** [comment]
Checking all things beforehand is not so practical, but I agree that an exception being thrown shouldn't leave the composer.json in a modified state, so fixed that part.
