### ISSUE TITLE
Are nested composer projects ok?

### ISSUE THREAD

**Issue by beppe9000** [composer/composer#8064]
If I have this folder structure, will I have conflicts if the same library is required by both projects?
the lib.php is included_once by the index.php and both include their own autoloader from their respective vendor folder.

/root/composer.json
/root/index.php
/root/vendor
/root/component_subfolder/composer.json
/root/component_subfolder/vendor
/root/component_subfolder/lib.php

How are different versions of the same library handled?

**Comment by alcohol** [comment]
Not sure what you are asking. We don't support multiple libraries in a repository for starters.

**Comment by alcohol** [comment]
If both index and lib use the Composer autoloader from their own vendor directories, then you will run into very unpredictable results because at runtime you will have two autoloaders active. Whether or not this will cause issues depends. Only one way to find out. Good luck with that :-)

**Comment by beppe9000** [comment]
But how does one avoid the problem when working on a modular project with composer?
For example if two wordpress plugins have their dependencies managed by composer and they get both loaded it's not very practical to mod the plugins to use the same vendor folder.
Do I have to turn lib.php into a packagist package and include in the index composer.json? But then it would defy the concept of plug-ins at production-level.
Could you please point me to some examples of these workarounds if you know about them?
Ps. Are there plans for detecting such a situation within the composer autoloader?

**Comment by alcohol** [comment]
I'm not sure I understand why plugins have their own dependencies managed by Composer / vendor directory. Plugins should be a dependency of your root project, and Composer will automatically handle the dependency trees of your root project combined with your plugins.

**Comment by beppe9000** [comment]
But what about third party plugins that are installable after deployement? For example in my plugin system I loop all the subfolders of a '/plugins' folder and read a plugin.json file that tells what file from that folder is to be 'require`d. The entire point is about not having to modify the project afterwards by allowing users to make plugins. Now wheter the main project dependencies are managed by composer or not, how should I manage the possibilities of plugin authors deciding to use composer?

**Comment by alcohol** [comment]
I'm sorry, but the concept of projects/plugins not using Composer is alien to me at this point. It's 2019. So I can't really comment on such a situation. PHP as a language simply does not work well with multiple autoloaders that might be used to load the same classes/namespaces (but different versions). Such conflict scenarios require very careful thought put into the whole process of autoloading, and prioritizing one autoloader over another, etc.

**Comment by staabm** [comment]
I guess this article describes what you want

https://medium.com/sroze/managing-monolithic-repositories-with-composers-path-repository-c28af031746d

**Comment by beppe9000** [comment]
Thanks, that has the same problem of having to run `composer update` on production.
Actually, this seems to be _exactly_ what I had in mind... https://github.com/coenjacobs/mozart
