### ISSUE TITLE
Race condition in how Composer plugins are activated leads to classmap errors

### ISSUE THREAD

**Issue by danepowell** [composer/composer#8065]
My `composer.json`:

```json
{
    "name": "example/demo",
    "description": "Composer installers error demo",
    "type": "project",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "license": "GPL-2.0-only",
    "require": {
        "acquia/blt": "dev-issue-3148-demo",
        "composer/installers": "^1.2.0"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.4
PHP version: 7.2.15
PHP binary path: /usr/bin/php7.2
```

When I run this command:

```
composer install && composer --version
```

I get the following output:

```
Could not scan for classes inside "vendor/drupal/core/lib/Drupal.php" which does not appear to be a file nor a folder
```

And I expected this to happen:
No errors

Downstream issues with additional context:
- https://github.com/composer/installers/issues/427
- https://github.com/acquia/blt/issues/3148
- https://github.com/wikimedia/composer-merge-plugin/issues/139

What I think is going on here is a race condition in the way that Composer plugins are activated.

Both BLT and Composer Installers provide plugins. In the [minimum failing example](https://github.com/acquia/blt/tree/issue-3148-demo), BLT's plugin is completely empty. Composer Installers obviously is changing the directory where Drupal files are installed.

When you run the initial composer install, everything works fine because Composer activates the Installers plugin prior to BLT, due to the order of dependency resolution. But when you subsequently run `composer --version`, it's throwing errors because plugins are activated _alphabetically_. This means that Composer activates the BLT plugin before the Installers plugin. The BLT plugin itself doesn't do anything, but Composer mucks about with the autoloader / classmap as part of PluginManager::registerPackage(), and because this happens before the Installers plugin loads you get errors.

I don't know the exact best way to solve this, but I think it requires action on the part of Composer, because I can't think of any way to force one plugin to run before another (other than renaming it to be something like `zacquia/blt`, which actually does solve this problem, but obviously isn't viable.)

It seems to me that either there could be some sort of weight system or consideration of the dependency tree in activating plugins in order to make sure plugins like Installers run first, or Composer could simply fail more gracefully during the plugin activation process since it's highly likely that classes will be missing during out-of-order activation.

**Comment by Seldaek** [comment]
It sounds like a pretty terrible idea to build a plugin that depends on another plugin IMO. The plugin does not need to be a drupal-specific module I assume, so it could be simply a plugin landing in vendor/.. and then everything would be fine?

That said, it's probably fixable by loading the plugins according to their dependencies..

**Comment by danepowell** [comment]
> It sounds like a pretty terrible idea to build a plugin that depends on another plugin IMO

To be clear, this doesn't arise from one plugin depending on another. It arises from any project depending on two or more plugins, when one of those plugins messes with the class map as [Composer Installers](https://github.com/composer/installers) does. This is demonstrated in my minimum failing example above: note that neither BLT or Composer Installers depend directly on each other, they are merely included by the same top-level composer.json.

This means that any project that uses Composer Installers and any other plugin starting with letters "a" or "b" (i.e. acquia/blt) will experience this bug.

**Comment by briantully** [comment]
@Seldaek 	any update on whether https://github.com/composer/composer/pull/8085 can be approved/merged to resolve this frustrating bug? Much appreciated! 😃
