### ISSUE TITLE
composer-plugin-api bump in 2.0 branch bifurcates ecosystem

### ISSUE THREAD

**Issue by mbaynton** [composer/composer#8066]
Composer 2.0 is incompatible with all currently available packages that require a plugin. That's by design of course, but the unresolvable conflict spreads pretty quickly across dependency chains and so prevents the installation of any bigger project out there that anywhere has a dependency on a plugin.

Where this is particularly alarming to me is that what's going to happen is, the day Composer 2.0 drops, package and plugin maintainers will quickly scurry around and update to be Composer 2.x compatible, which is maybe a minor pain but not so bad. The bad part is now there'll be the set of things on packagist that you need Composer 1.x for, and the set that you need 2.0 for. _*shivers*_. 

**Why this sucks**

- I'm sure Composer has been pretty widely baked into CI/CD pipelines, imagine the hell now when you want to test against latest (use 2.0 for that one!) and lowest (use 1.x), etc. 
- If you as an app developer haven't moved to Composer 2.0, you won't get any updates to your packages after the maintainer did the `composer-plugin-api: ^2.0` bump; whether you're even aware of the newer version is questionable.

**Suggested mitigation**
Treat the plugin API more like a versioned web application API, where the earlier version just kinda hangs out for things that still need it, and concurrently introduce new versions that peacefully coexist with the old one.

This wouldn't necessarily mean that you'd have to continue supporting plugin api 1.x interfaces in perpetuity, but it would mean that you'd support them in 2.0.0 and for a year or two afterwards so that when the bifurcation happens, it at least is only for versions of packages that are year(s) out of date.

And you'd make the rule introduced in https://github.com/composer/composer/issues/4085 more permissive so that `composer-plugin-api` 1.x or 2.x were allowed. You could possibly also do some things like create a `Plugin2` context class that plugins requiring plugin api 2.x were passed.

**Comment by alcohol** [comment]
> Composer 2.0 is incompatible with all currently available packages that require a plugin.

Not sure what that statement is based on. But then again I stay as far away from plugins as I can. @Seldaek can probably best answer this question.

**Comment by mbaynton** [comment]
It's based on the solver-generated refusal to proceed on the 2.0 branch when trying to install Sylius or Drupal
```
Your requirements could not be resolved to an installable set of packages.
...
    - ocramius/package-versions 1.1.2 requires composer-plugin-api ^1.0 -> no matching package found.
```

Wondering if project leadership sees this as a severe limitation or not.

**Comment by alcohol** [comment]
But what makes you think plugins cannot support ^1.0 and ^2.0 ? You say you will end up needing Composer 1.x and Composer 2.x in the future, but I am not quite sure what this is based on.

**Comment by mbaynton** [comment]
Ah, is that possible? If the plan is for plugin authors to create updates to the plugins that are not new major versions of the plugins (so work with all existing versions of projects that require them), and that are able to support composer-plugin-api ^1.0|^2.0, then that would make things a lot better.

I guess I assumed if there was an api version bump it was because they were incompatible, but maybe the plugins can be written to figure it out?

**Comment by alcohol** [comment]
Yes, it's very possible that older versions of the plugin do not support ^2.0, but that newer versions can support both 1.x and 2.x

**Comment by Seldaek** [comment]
Indeed most plugins will be able to simply update their requirements to composer-plugin-api `^1.0 || ^2.0` and will work fine. Some more involved plugins will need heavier updates though, and might need to have new versions to support v2, but to support the v1 API for those is just impossible as we are refactoring internals so much.
