### ISSUE TITLE
Composer not removing dist from composer.lock

### ISSUE THREAD

**Issue by captainskippah** [composer/composer#8072]
Initially, while developing locally, I was using the package from my local directly like:

```json
{
  "repositories": [
    {
      "type": "path",
      "url": "../packageB"
    }
  ]
}
```

After pushing everything to private repo, I have changed the `type` to `vcs` and the `url` accordingly.

Now, the problem is, the `dist` part of `packageB` in `composer.lock` does not get removed but the `source` is updated. `composer.lock` looks like:

```json
{
  "packages": [
    {
      "name": "vendor/packageB",
      "source": {
        "type": "git",
        "url": "{git url}"
       },
      "dist": {
        "type": "path",
        "url": "../packageB"
      }
    }
  ]
}
```

Tried `composer require`, `composer update --lock`, and  `composer update vendor/packageB` without success.

Is this expected?

I managed to solve it by doing `composer remove vendor/packageB` and then `composer require vendor/packageB` again but I thought composer should have handled that one.

**Comment by alcohol** [comment]
Composer does not handle this scenario due to complexity involved. The symlink has to be removed first (through removing the package like you did, or just removing the whole vendor directory) and a clean install has to be made.
