### ISSUE TITLE
Bitbucket: clearcache before update

### ISSUE THREAD

**Issue by rentalhost** [composer/composer#8074]
I have setup a private Bitbucket for my composer. It works fine for some hours, but then it will starts to fail to update the private package with the message "update failed". So for fix it, I need run `composer clearcache` then again `composer update`, but it will give a "update failed" again, but with an option to I resintall the private package. If I say "yes", the package will be reinstalled and it will works for more some hours without problem.

**My `composer.json`:**

```json
{
    "name": "xxx/yyy",
    "license": "proprietary",
    "type": "project",
    
    "require": {
        "some-private/bitbucket-repository": "^1"
    }
}
```

**Output of `composer diagnose`:**

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: ***
Dev Public Key Fingerprint: ***
OK
Checking composer version: OK
Composer version: 1.8.4
PHP version: 7.2.16
PHP binary path: /opt/cpanel/ea-php72/root/usr/bin/php
```

**When I run this command:**

```
ea-php72 /usr/local/bin/composer update some-private/bitbucket-repository
-- OR JUST --
ea-php72 /usr/local/bin/composer update
```

**I get the following output:**

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating some-private/bitbucket-repository dev-master (4f201f5 => 046d100):  Checking out 046d100587
    Update failed (Failed to execute git remote set-url composer 'https://x-token-auth:***@bitbucket.org/some-private/bitbucket-repository.git' && git rev-parse --quiet --verify '046d100587495c81f4e6bcf9e0cd4f1e7dc2eb14^{commit}' || (git fetch composer && git fetch --tags composer)

remote: Invalid username or password
fatal: Authentication failed for 'https://x-token-auth:***@bitbucket.org/some-private/bitbucket-repository.git/'
)
    Would you like to try reinstalling the package instead [yes]? yes
  - Removing some-private/bitbucket-repository (dev-master)
  - Installing some-private/bitbucket-repository (dev-master 046d100): Cloning 046d100587 from cache
Writing lock file
```

**And I expected this to happen:**

I do expect that it works without additional interaction or `clearcache` before.

**Comment by alcohol** [comment]
Unfortunately I am not very familiar with the token flow of Bitbucket (nor their API). The driver we use for Bitbucket is mostly maintained by community contributions. Could it be that Bitbucket tokens have a lifetime, and that it needs to be refreshed every so often?

**Comment by alcohol** [comment]
It will use the `GitDriver` in fallback mode:

https://github.com/composer/composer/blob/master/src/Composer/Repository/Vcs/GitBitbucketDriver.php#L72-L82

Pinging Nils and Jordi won't do much good. None of us have invested a lot of time into the `Bitbucket`drivers. You would do better trying to find the original contributors.

**Comment by rentalhost** [comment]
Oh, ok... I will try to fix it and send a PR on weekend. It not seems to be very hard (I hope haha). Thanks!

**Comment by alcohol** [comment]
https://community.developer.atlassian.com/t/oauth2-token-lifetime-expiration-clarification/22136 could be interesting to take into account.

**Comment by petk** [comment]
It seems that for private repositories on Bitbucket, this example below works ok:

```json
...
"repositories": [
{
  "type": "vcs",
  "url": "https://bitbucket.org/user/repository"
}
],
...
```
(and using an OAuth token generated via the Bitbucket user settings page). The `url` could be also `git@bitbucket.org:user/repository` if there is read  access on the repository. 

When using the `"type": "git"` like this:

```json
...
"repositories": [
{
  "type": "git",
  "url": "https://bitbucket.org/user/repository"
}
],
...
```
this warning occurs:

```text
Failed to update https://bitbucket.org/user/repository, package information from this repository may be outdated
```

**Comment by Seldaek** [comment]
Closing as nobody cared to fix it in these many years, if it is still applicable do tell and I will reopen. It may have been fixed by some recent fixes to the bitbucket handling tho.
