### ISSUE TITLE
Cannot install Composer v1.8.4 on Windows 10.0.17134 Build 17134

### ISSUE THREAD

**Issue by XXvevo** [composer/composer#8077]
Hello,

if I try to open [Composer-Setup.exe](https://getcomposer.org/Composer-Setup.exe) v1.8.4 on my Windows 10.0.17134 Build 17134 machine, I receive the following error as shown in the attached image.

What can I do to fix this issue?

![Screenshot_1](https://user-images.githubusercontent.com/7198574/55339885-d5824e80-54a3-11e9-81c5-23f5b3d97b0c.png)

**Comment by alcohol** [comment]
I am unable to move this issue, so closing it instead and asking you to open it again at the right repository: https://github.com/composer/windows-setup
