### ISSUE TITLE
composer.lock file changes BitBucket to GitHub for the dist/zip entry

### ISSUE THREAD

**Issue by groovenectar** [composer/composer#8078]
My `composer.json`:

```json
    "require": {
        "username/packagename": "dev-branch"
    },
    "repositories": {
        "uniquename": {
            "type": "vcs",
            "url": "git@bitbucket.org:FORKEDusername/packagename.git"
        }
    }
```

Output of `composer diagnose`:

```
➜  htdocs git:(master) ✗ composer diagnose   
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.4
PHP version: 7.2.15
PHP binary path: /usr/bin/php7.2
```

When I run this command:

```shell
rm composer.lock
composer update
```

I get the following output in `composer.lock`:

```json
        {
            "name": "username/packagename",
            "version": "dev-branch",
            "source": {
                "type": "git",
                "url": "git@bitbucket.org:usernameFORKED/packagename.git",
                "reference": "[COMMITHASH]"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/username/packagename/zipball/[COMMITHASH]",
                "reference": "[COMMITHASH]",
                "shasum": ""
            },
        }
```

And I expected this to happen:

```json
        {
            "name": "username/packagename",
            "version": "dev-branch",
            "source": {
                "type": "git",
                "url": "git@bitbucket.org:usernameFORKED/packagename.git",
                "reference": "[COMMITHASH]"
            },
            "dist": {
                "type": "zip",
                "url": "https://bitbucket.org/usernameFORKED/packagename/get/[BITBUCKETHASH].zip",
                "reference": "[COMMITHASH]",
                "shasum": ""
            },
        }
```

Here was the flow:

1) Forked a GitHub package and made changes

2) Cloned into BitBucket

3) Included BitBucket repository in `composer.json`

GitHub seems to have a rate limit issue that could be a bug. It makes unattended deploys impossible if they involve Composer pulling from there, if you do it more than *once* in an hour. It requires you to login to GitHub and make a new token, which is not feasible as a headless process. The best solution seems to use any other repository host besides GitHub.

Now, the original `username/packagename` does have an official Composer repository, so perhaps it is getting mixed up because of that?

**Comment by alcohol** [comment]
> GitHub seems to have a rate limit issue that could be a bug. It makes unattended deploys impossible if they involve Composer pulling from there, if you do it more than once in an hour. It requires you to login to GitHub and make a new token, which is not feasible as a headless process. The best solution seems to use any other repository host besides GitHub.

Suggest you look at https://github.com/composer/composer/issues/8068#issuecomment-478906019

**Comment by alcohol** [comment]
A token should increase your rate limit significantly. I cannot imagine you ever hit the cap.

**Comment by groovenectar** [comment]
> A token should increase your rate limit significantly. I cannot imagine you ever hit the cap.

Perhaps that will be the solution.

However, it doesn't really address what could cause Bitbucket to be rewritten as GitHub in the `composer.lock` for the zip archive, when the source repo is Bitbucket and the `composer.json` doesn't mention GitHub for the package...

**Comment by alcohol** [comment]
> Even without the token, it's absurd to hit the limit headlessly after about one request, enough to the point where I'd just rather not mess with GitHub as the source.

It is absurd. It is also something you alone seem to be experiencing, while hundreds of thousands of other developers are not. So before blaming Github for your frustration, I would suggest you look into what is really going wrong in your environment first perhaps. Because most likely it is a configuration error on your end.

**Comment by groovenectar** [comment]
> > Even without the token, it's absurd to hit the limit headlessly after about one request, enough to the point where I'd just rather not mess with GitHub as the source.
> 
> It is absurd. It is also something you alone seem to be experiencing, while hundreds of thousands of other developers are not. So before blaming Github for your frustration, I would suggest you look into what is really going wrong in your environment first perhaps. Because most likely it is a configuration error on your end.

Other people are experiencing this issue.

https://github.com/composer/composer/issues/3542

https://github.com/composer/composer/issues/6621

I'm not blaming GitHub for the posted issue of switching the archive URL, that's why I'm posting/asking this in `composer/composer`.

**Comment by alcohol** [comment]
Both Github and Bitbucket are a VCS provider. VCS in `composer.json` simply means "try to figure out the underlying implementation", which could be github, gitlab, bitbucket, hg, p4, or just plain git, among others.

Using forks is generally a discouraged practice, as it will only cause headaches in the long run. That being said, you should be able to install a custom branch from your fork without trouble. Without any real reproducible scenario however (fake date and configuration examples are useless), we simply cannot determine what is actually going wrong.

Also note that when you use repositories, you should not only  `rm composer.lock` if you want to run a "from scratch" scenario. You should also `composer clear-cache`. Because repositories are cached locally in the global cache directory and then mirrored into your vendor directory.

**Comment by groovenectar** [comment]
Thanks for the insight -- I did use a custom default branch, but did not try running `clear-cache`. Perhaps that would have been key. The route I ended up having to take was to integrate the package into the application, but I'll want to revisit. Will close this for now since it would be a process to spin up a test case again.
