### ISSUE TITLE
composer --no-cache option does not exist

### ISSUE THREAD

**Issue by Ovsyanka** [composer/composer#8079]
Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 1.8.4
PHP version: 7.3.3
PHP binary path: /usr/bin/php
```

When I run this command:

```
composer global require "fxp/composer-asset-plugin:~1.3" --prefer-dist --no-scripts --no-cache
```

I get the following output:

```
 [Symfony\Component\Console\Exception\RuntimeException]  
  The "--no-cache" option does not exist.
```

And I expected this to happen:

The package be installed as usual without using cache, as written in the [documentation](https://getcomposer.org/doc/03-cli.md#global-options).

**Comment by alcohol** [comment]
It seems this has no effect for some reason: https://github.com/composer/composer/blob/522ea033a3c6e72d72954f7cd019a3b75e28f391/src/Composer/Console/Application.php#L121-L124

**Comment by alcohol** [comment]
I found the issue. These changes are only in master currently, not in the latest release. You'll have to upgrade to the latest snapshot if you want to use them.

**Comment by Ovsyanka** [comment]
What do you mean by latest release? I got 1.8.4 and it is a latest release, isn't it? I am not sure how to check the particular commit of file, but the date in `version` output equal to the date of [1.8.4](https://github.com/composer/composer/releases/tag/1.8.4) release:
```sh
$ composer --version
Composer version 1.8.4 2019-02-11 10:52:10
```

**Comment by alcohol** [comment]
> These changes are only in master currently, not in the latest release.

Note that I said *not* in the latest release :-)

> You'll have to upgrade to the latest snapshot if you want to use them.

```
composer self-update --snapshot
```

**Comment by Ovsyanka** [comment]
I misunderstood you. Thought that you talking about some error that exists in the master only.
I updated the composer as you said and it is working indeed. Thanks!

As I understood, the official documentation represents master instead of latest release? In my opinion it could lead to issues like this issue and it looks better to have either the "latest release" docs or multiple versions of documentation for several releases and master. What do you think&

**Comment by alcohol** [comment]
> As I understood, the official documentation represents master instead of latest release? In my opinion it could lead to issues like this issue and it looks better to have either the "latest release" docs or multiple versions of documentation for several releases and master. What do you think&

Documentation is based on `master` branch yes. Unfortunately this has always been the case. Changing this has incredibly low priority for us.

**Comment by conradfr** [comment]
FWIW I still get "The "--no-cache" option does not exist." on the latest snapshot.
