### ISSUE TITLE
Composer.json permissions

### ISSUE THREAD

**Issue by tzak902** [composer/composer#8086]
Hi, I have a quick question please and need someone with deep knowledge about composer to respond.

I have Prestashop installed and I have 2 files composer.json and composer.lock

I can access the 2 files from the URL domain.com/composer.json 
and it will show me all content my current permission for this file is 640.

Here is my question:

Is it safe if anyone browse to that file via a web URL link ?
Is there is vulnerable way to access other stuff via the file being exposed in the internet for anyone?

I need clarifications please.

**Comment by alcohol** [comment]
Sounds to me like your webroot is not correctly configured. Usually `composer.json` is in the root of your project, and your project will contain a directory named `web` or `public` which will contain the entry point for your webserver.

Being able to read these files however is not a big deal. It does make it slightly easier for potential threats to determine which versions you are using of certain packages and whether or not known CVE's exist for those or not.

**Comment by tzak902** [comment]
Hello @alcohol Thanks for your input, the composer.json file exists inside the public_html folder that contains my website files.
So this is a mistake? I've just checked and I don't have a "web" or "public" folder

**Comment by alcohol** [comment]
Usually your php files would be outside of your public_html directory, in a directory called src (source). Next to that there would be a directory called vendor (produced by composer). Your php files should never be in your public_html directory (with the exception of your index.php / entrypoint). But now we are venturing into basic webserver setup and configuration, and this is rather outside of the scope of our project. And while I do have plenty of experience on this subject, this is not really the place to discuss it.

**Comment by nuxwin** [comment]
@alcohol 

Having a `public_html` directory as document root is just a convention. Not all projects are using such a convention where sensible file live outside of the document root. There are projects where sensible files are protected using a `.htaccess` files (Apache2) or a `deny all` directive (Nginx). Of course, having sensible files outside the document root is a good practice but that still just a practice.

**Comment by alcohol** [comment]
I do not see any reason to share or document discouraged practices. They only add noise to the conversation.

**Comment by nuxwin** [comment]
> I do not see any reason to share or document discouraged practices.

Don't get annoyed. But there is no real standart about that. That's only practices which are good or bad, whatever. You cannot answer someone by just saying: You need do like this and not like that. That's not your role. That's only your own vision.

**Comment by alcohol** [comment]
Pretty sure I can answer in any way I see fit.
