### ISSUE TITLE
Composer still cloning from cache after clearing

### ISSUE THREAD

**Issue by ExploHash** [composer/composer#8087]
I ran:
```
composer clear-cache
rm -rf vendor
rm -rf ~/.cache/composer
```
But I still get `Cloning 3e01bdad3e from cache` by a `composer install`

composer.json:
```
{
  "name": "{companyname}/{custom-repo-name}-skeleton",
  "authors": [
    {
      "name": "{name}",
      "email": "{email}"
    }
  ],
  "minimum-stability": "dev",
  "require": {
    "{companyname}/{custom-repo-name}": "dev-master",
    "{companyname}/{custom-repo-name}-yii2-bridge": ">=1.0.5",
    "{companyname}/{custom-repo-name}-events": "dev-master",
    "{companyname}/{custom-repo-name}-gii": "dev-master",
    "{companyname}/{custom-repo-name}-filesystem": ">=1.0.0",
    "yiisoft/yii2": "~2.0.7",
    "yiisoft/yii2-jui": "^2.0",
    "{companyname}/{custom-repo-name}-yii2-activefield": "dev-master",
    "andres-montanez/magallanes": "^1.0",
    "{companyname}/{custom-repo-name}-tasks": "*",
    "trntv/yii2-command-bus": "^2.1",
    "yiisoft/yii": "^1.1.19",
    "php": "7.1.*",
    "yidas/yii2-bower-asset": "dev-master",
    "josegonzalez/dotenv": "@stable"
  },
  "require-dev": {
    "yiisoft/yii2-codeception": "^2.0",
    "codeception/codeception": "2.2",
    "codeception/specify": "^0.4.3"
  },
  "repositories": [
    {
      "type": "vcs",
      "url": "git@github.com:{companyname}/{custom-repo-name}.git"
    },
    {
      "type": "vcs",
      "url": "git@github.com:{companyname}/{custom-repo-name}-yii2-bridge.git"
    },
    {
      "type": "vcs",
      "url": "git@github.com:{companyname}/{custom-repo-name}-yii2-activefield.git"
    },
    {
      "type": "vcs",
      "url": "git@github.com:{companyname}/{custom-repo-name}-tasks.git"
    },
    {
      "type": "vcs",
      "url": "git@github.com:{companyname}/{custom-repo-name}-events.git"
    },
    {
      "type": "vcs",
      "url": "git@github.com:{companyname}/{custom-repo-name}-gii.git"
    },
    {
      "type": "vcs",
      "url": "git@github.com:{companyname}/{custom-repo-name}-filesystem.git"
    }
  ],
  "autoload": {
    "exclude-from-classmap": [
      "vendor/yiisoft/yii/framework/yii.php"
    ]
  },
}
```

Output `composer install`:
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 82 installs, 0 updates, 0 removals
  - Installing yiisoft/yii2-composer (dev-master f4cb50d): 
Cloning f4cb50d40e from cache
  - Installing ezyang/htmlpurifier (v4.10.0): Downloading (100%)         
  - Installing cebe/markdown (dev-master 530bc7d): Cloning 530bc7dcbd from cache
  - Installing bower-asset/jquery (3.2.1): Downloading (100%)         
  - Installing bower-asset/yii2-pjax (dev-master c39f239): Cloning c39f239388 from cache
  - Installing bower-asset/punycode (v1.3.2): Downloading (100%)         
  - Installing bower-asset/inputmask (3.3.11): Downloading (100%)         
  - Installing yiisoft/yii2 (dev-master bfcccc4): Cloning bfcccc46cd from cache
  - Installing trntv/yii2-command-bus (2.1.3): Downloading (100%)         
  - Installing {companyname}/{custom-repo-name}-events (dev-master eand4a6): Cloning eabd4a653b from cache
  - Installing symfony/process (dev-master 81bb068): Cloning 81bb068ddd from cache
  - Installing psr/log (dev-master 3490ba5): Cloning 3490ba5925 from cache
  - Installing spatie/image-optimizer (1.1.2): Downloading (100%)         
  - Installing yiisoft/yii (1.1.20): Downloading (100%)         
  - Installing swiftmailer/swiftmailer (v5.2.1): Downloading (100%)         
............
```

**Comment by alcohol** [comment]
And would this involve a custom repository package by any chance?

**Comment by alcohol** [comment]
Also, significant log output is missing from this post to provide a more quick and clear answer. The issue template exists for a reason. Please respect it.

**Comment by ExploHash** [comment]
This contains both custom repositories and packages. I added the composer.json and output of composer install to the post.

**Comment by alcohol** [comment]
All of those are to be expected. None of the packages in question are `dist` installs, since you are not using versions but branches. Source installs are always cloned into the cache locally first, and then installed from cache. That is why you are seeing "from cache" even after a `clear-cache`.

**Comment by ExploHash** [comment]
Thanks a lot for clarifying. I can't really find this in de composer docs. Maybe worth mentioning?

**Comment by alcohol** [comment]
Depending on how verbose and whether or not you are running in interactive mode, this process is actually more or less visible already. Not really worth documenting IMHO. If we document every little peculiar detail, people would probably be put off even more from reading our documentation.

**Comment by ExploHash** [comment]
Fair enough :P. I can't really say I looked at the docs for more than 5 seconds before I encountered the problem. Maybe another aproach: some installs show `downloading....`. Wouldn't it be helpfull if it would say `cloning...` instead of an empty line? Just a suggestion.

**Comment by alcohol** [comment]
The `downloading` is because they are using `dist` installs (versioned, so we can fetch a tarball/gzip directly from github and just extract that).

**Comment by ExploHash** [comment]
Ah, I understand but what I meant was if a `source` install happens, it shows an empty line while it's cloning and after that it shows `Cloning 530bc7dcbd from cache` right? Why not show `cloning from {url}` instead of an empty line and afterwards `Cloning {bla} from cache`.

I can understand that it's to much work for a simple clarification but that would make it more clear (for me atleast).

**Comment by alcohol** [comment]
It should say it is cloning to cache initially:

https://github.com/composer/composer/blob/66a77ed21031d99b8f74c527932fef0b7aace1d9/src/Composer/Downloader/GitDownloader.php#L57

**Comment by ExploHash** [comment]
Weird. Even though I have version 1.8.4 this doesn't happen.

**Comment by Seldaek** [comment]
That only gets output in debug verbosity, i.e. `-vvv`. That's why we ask to report issues with full verbose output..

**Comment by alcohol** [comment]
Yeah, like I said

> Depending on how verbose and whether or not you are running in interactive mode, this process is actually more or less visible already.
