### ISSUE TITLE
Alias conflicts to conflict rather than silently discarding it from composer.json

### ISSUE THREAD

**Issue by glensc** [composer/composer#8094]
The correct key for "conflicts" is "conflict":
- https://getcomposer.org/doc/04-schema.md#conflict

however, when using wrong key name "conflicts", no warning or error is not emitted, making such error not being noticed.

oddly, packagist.org shows the conflicts under "conflicts" key, making it even more confusing.

Proposed outcomes:
- make "conflicts" alias to "conflict", treat them equally
- apply validation when running "composer update" or "composer install" commands and note the user

example:
- using "conflicts" key: https://packagist.org/packages/glen/slack-unfurl-jira#v0.4.1

![image](https://user-images.githubusercontent.com/199095/55917524-48a06900-5bf8-11e9-949e-bfd891e3e8c9.png)

using proper "conflict" key: https://packagist.org/packages/glen/slack-unfurl-jira#v0.4.2

![image](https://user-images.githubusercontent.com/199095/55917538-5229d100-5bf8-11e9-965a-6e25c6a2949b.png)

**Comment by glensc** [comment]
note: `composer validate` notices this error, but it's unlikely to be ran as end user as "conflict" keys are typically modified manually.

```
➔ composer validate
./composer.json is valid

➔ git checkout HEAD~1
➔ composer update --lock
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

➔ composer validate
./composer.json is valid for simple usage with composer but has
strict errors that make it unable to be published as a package:
See https://getcomposer.org/doc/04-schema.md for details on the schema
The property conflicts is not defined and the definition does not allow additional properties
➔
```

**Comment by Seldaek** [comment]
I think we could error/warn if we see any of the conflict/require/require-dev/.. keys in its pluralized form, but aliasing silently sounds like it'd cause more issues down the line. And I disagree packagist should be changed here, it is a list of conflicts, while the composer.json arguably should also be a list of conflicts/requires, but that's set in stone so not really worth discussing.

**Comment by stof** [comment]
it is weird though that validate says `./composer.json is valid for simple usage with composer but has
strict errors that make it unable to be published as a package`. I would say that extra properties should always be considered a warning for normal usage.

**Comment by Seldaek** [comment]
I'd rather not as adding extra keys to use as comments for example or other stuff used for plugins (although it should ideally be within `extra`) can be valid use case.

**Comment by stof** [comment]
well, we have `_comment` in the schema for comments. And other things indeed belong to `extra`

**Comment by Seldaek** [comment]
I think I'd rather close this, if someone wants to send a PR to warn on conflicts/requires/.. why not, but I won't spend time on this as I don't think it is a frequent enough problem. Not worth investing time debating..
