### ISSUE TITLE
update user

### ISSUE THREAD

**Issue by Theolodewijk** [composer/composer#8098]
after some searching on the web but ask here!

it is possible to perform an update from linux crond.

normally i go to the folder of my projects and do i do composer update but can i also do this from a linus crond?

**Comment by alcohol** [comment]
If you want, yes.

**Comment by Theolodewijk** [comment]
okay, do you have an example?

**Comment by alcohol** [comment]
Just run composer as you would run any normal cronjob. Specify the interval, the user, and make sure you run it against the right working directory.

**Comment by Theolodewijk** [comment]
normal I do cd /home/roor directory of project and run composer update

suld it be * * * * * cd /home/path composer update 

??

**Comment by alcohol** [comment]
No, that would not work correctly.

The `cd /path` command cannot be combined with `composer update` like that. 

I would suggest using
```
composer --working-dir /path update
```

Note that this requires that your `$PATH` contains the directory in which `composer` can be found.

Currently you specified it to run every minute. If you do not want to run the update command every minute, look here for cron syntax: https://crontab.guru/
