### ISSUE TITLE
Unable to run composer

### ISSUE THREAD

**Issue by mdongsheng** [composer/composer#8103]
Unable to run composer:
PHP Warning:  Unexpected character in input:  ' in phar:///usr/local/bin/composer/bin/composer on line 62

Composer version: 1.8.5

PHP env:
PHP 7.2.16 (cli) (built: Mar 10 2019 21:22:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by alcohol** [comment]
Missing sufficient information.

**Comment by mdongsheng** [comment]
PHP Version: 7.2.16
OS: CentOS 7.6
Composer Version: 1.8.5

When executing coposer -v, the following error is reported:

PHP Warning: Unexpected character in input: ' in phar:///usr/local/bin/composer/bin/composer on line 62

**Comment by alcohol** [comment]
How did you install Composer?
What does `type composer` and `which composer` return?

**Comment by mdongsheng** [comment]
Installation step:
php -r "copy('https://install.phpcomposer.com/installer', 'composer-setup.php');”
sudo php composer-setup.php --install-dir=/usr/local/bin/
php -r "unlink('composer-setup.php');”
which composer:
/usr/local/bin/composer

Flollow error is returned when I run the composer command:
PHP Warning: Unexpected character in input: ' in phar:///usr/local/bin/composer/bin/composer on line 62

**Comment by alcohol** [comment]
That does not make much sense.

The installer will deliver a `composer.phar` in your current directory. You are executing a binary called `composer`. These are two very different files.

It is rather difficult to help you if you do not know what you are doing to begin with.

**Comment by xywf221** [comment]
> Installation step:
> php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
> php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
> php composer-setup.php
> php -r "unlink('composer-setup.php');"
> which composer:
> /usr/local/bin/composer
> 
> Flollow error is returned when I run the composer command:
> PHP Warning: Unexpected character in input: ' in phar:///usr/local/bin/composer/bin/composer on line 62

Hi, I feel like you should send out how you use the composer command line and use the -V option

**Comment by mdongsheng** [comment]
Sorry, I missed a step, I executed sudo mv composer.phar /usr/local/bin/composer

**Comment by mdongsheng** [comment]
> > Installation step:
> > php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
> > php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
> > php composer-setup.php
> > php -r "unlink('composer-setup.php');"
> > which composer:
> > /usr/local/bin/composer
> > Flollow error is returned when I run the composer command:
> > PHP Warning: Unexpected character in input: ' in phar:///usr/local/bin/composer/bin/composer on line 62
> 
> Hi, I feel like you should send out how you use the composer command line and use the -v option

Executing composer -v will also get this error.

**Comment by alcohol** [comment]
And what was the output of `type composer`?
What about `which php`? And `type php`?

**Comment by alcohol** [comment]
Also, what if you just do this for a moment:

```
cd $(mktemp -d)
wget https://getcomposer.org/download/1.8.5/composer.phar
php composer.phar --version
```

**Comment by mdongsheng** [comment]
> Also, what if you just do this for a moment:
> 
> ```
> cd $(mktemp -d)
> wget https://getcomposer.org/download/1.8.5/composer.phar
> php composer.phar --version
> ```

PHP Warning:  Unexpected character in input:  ' in phar:///tmp/tmp.oWLx3XentV/composer.phar/bin/composer on line 62

I was wondering if it would be my PHP environment problem, but other applications on my website are running normally.

**Comment by mdongsheng** [comment]
> And what was the output of `type composer`?
> What about `which php`? And `type php`?
> And the output of `php --ini` and `php -i`?

which php
/usr/bin/php

php --ini
Configuration File (php.ini) Path: /etc
Loaded Configuration File:         /etc/php.ini
Scan for additional .ini files in: /etc/php.d
Additional .ini files parsed:      /etc/php.d/bcmath.ini,
...

short_open_tag = On

**Comment by stof** [comment]
Please give the full output of `php -i`, not just one line of it.

**Comment by mdongsheng** [comment]
I think I found the problem, it is my fault, one of my .so has gone wrong, solved, thanks all of you.
