### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by Mitij0** [composer/composer#8105]
Hello everyone,

I'm very new to this github and composer thing, so I'm trying to figure out all I need but it's not really going well. I've had a brief explanation of someone who isn't really familiair with this stuff either, so I hope I can find my answer here.

I want to use this github project:
https://github.com/Surfoo/geocaching-php-sdk
And figured out how to clone it already (yeah, you'd think it'd be easy once you know how...)
Anyway, now I need to use the composer, but that's where it goes wrong:

Output of `composer diagnose`:
![image](https://user-images.githubusercontent.com/33699013/56470331-34a10680-6445-11e9-9bbe-2ab24609af8d.png)

I really have no clue what this all means. I've searched for this error on google, stackoverflow, ... but it seems to be so specific for each case, I'm not getting any wiser out of it.

Now, which extra information might you need from me? Or is there maybe anyone here who can help me already with this information?

Thank you in advance!

**Comment by xabbuh** [comment]
Can you please show the contents of your `composer.json` file?

**Comment by sovainfo** [comment]
Looks like the clone you made interferes with using it in your project. The message you get is that you have contradicting requirements. It wants to get 3.3.0 for you but there is something already requiring dev-develop. Composer can only use one version in a project at the time. Not sure, but suspect you are running this from the clone. You should run it from the project you want to start. No need for cloning, composer will make it available for you.
