### ISSUE TITLE
COMPOSER_AUTH environment variable is malformed, should be a valid JSON object

### ISSUE THREAD

**Issue by mozgbrasil** [composer/composer#8106]
https://github.com/magento/magento2/issues/22460

**Comment by alcohol** [comment]
The error explains itself. Not really sure what you want us to tell you. Perhaps the contents of the environment variable is escaped too many times (or not enough)?

**Comment by mozgbrasil** [comment]
Hello good Morning

Perhaps the occurrence is related to the EBS,

Thank you for interacting and sorry for anything.
