### ISSUE TITLE
Composer hangs on simplest command

### ISSUE THREAD

**Issue by joeyhub** [composer/composer#8109]
There's nothing in there except some ext requires and a single small PHP package. The ext is already installed, all it has to do is update composer.json but instead it hangs.

```
# composer require ext-abc
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^1.7 for ext-abc
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
^C^C
^C^C
^C
^C
^C

^C
^C^C

^C
^C
^C^C
^C^C
^C^C^C
^C
^C
^C
^C^C
^C
^C
^C
^C
^C^C^C^C
^C^C
^C^C^C^C^C^C^C
^C^C
^C

^C^C

```

**Comment by alcohol** [comment]
Cannot reproduce.

**Comment by joeyhub** [comment]
It's probably because you've put update in there. Can you take that out? Loads of commands are stealthily also running update which isn't actually what the user is asking composer to do, it just seems to be something you want the user to do.

Update should only run when people ask for it to run, especially if it's really slow. In this case even if update were to only consider affected packages, you wouldn't expect a function like this to effect anything.

Are you having to rescan everything to look for if packages have some kind of conflicts (IE, anti-dependencies)? Shouldn't that be locally cached and fast to look up? The ext really shouldn't be present in any of the packages.

The only non-ext I have is a php package which only requires php and another extension, it's not a complex dependency graph.

It's mind bogging how composer comes to a halt (most likely IO) for such a trivial task. `--no-update` really should be a default as the update function is so unreliable and slow, to run it takes special provisions.

**Comment by alcohol** [comment]
> It's probably because you've put update in there. Can you take that out?

No, the whole purpose of `require` is to provide a convenience method for modifying the `composer.json` and updating the dependency tree.

**Comment by alcohol** [comment]
> Update should only run when people ask for it to run

`require` runs update, and since you ran `require`, you asked for the update. You can optionally provide `--no-update`.
