### ISSUE TITLE
Error while installing Composer

### ISSUE THREAD

**Issue by shrutiupari** [composer/composer#8110]
My `composer.json`:

{
}

Output of `composer diagnose`:

```
...replace me...
```

When I run this command:

Composer-Setup (Set Up file)

I get the following output:

The Composer installer script was not successful [exit code 1].

Script Output:
The "https://getcomposer.org/versions" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: No such host is known. 
failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known.

And I expected this to happen:

**Comment by alcohol** [comment]
Check if you can reach https://getcomposer.org in your browser. Looks like your network either has a firewall or a proxy that is interfering with your connections/traffic.

**Comment by shrutiupari** [comment]
@alcohol I can access it but unable to install

**Comment by alcohol** [comment]
There is nothing we can do about that. Check with whoever is responsible for your network why you cannot connect to our host.
