### ISSUE TITLE
I would like to run scripts that depend on packages when I follow the project composer install.

### ISSUE THREAD

**Issue by whiteCcinn** [composer/composer#8117]
My `composer.json`:

```json
{
      "require": {
         "issue-php": "^0.2.*"
      }
 }
```

Output of `composer diagnose`:

```
...replace me...
```

When I run this command:

```
composer install
```

I get the following output:

```
run scripts that depend on packages
```

And I expected this to happen:

I would like to run scripts that depend on packages when I follow the project composer install. Could you support this function?

**Comment by prisis** [comment]
I have composer plugin that is doing that stuff that you requesting, https://github.com/narrowspark/automatic

**Comment by whiteCcinn** [comment]
@prisis 
I need at least compatible with php5.6, and your project is more complex, the examples are not enough, it is a little difficult to digest. But thanks anyway.

**Comment by alcohol** [comment]
Feature request is unclear to me. Can you describe an exact scenario?

Most likely the answer will be no however. Special behavior should be implemented using plugins generally.

**Comment by whiteCcinn** [comment]
@alcohol 

Yes, I've implemented it with a plugin, thanks.
