### ISSUE TITLE
Composer does not respect set "config.platform.php" when resolving dependencies

### ISSUE THREAD

**Issue by ArminVieweg** [composer/composer#8120]
Hi,
 
in my composer.json I've required `"doctrine/doctrine-migrations-bundle": "^2.0",`.

My local dev machine on PHP 7.3 but the production environment is 7.1, so I've also set 

```
"config": {
        "platform": {
            "php": "7.1.3"
        }
}
```
Now, when I try to `composer install` I get the following error:

>  - ocramius/proxy-manager 2.3.1 requires php ^7.4.0 -> your PHP version (7.3.4) overridden by "config.platform.php" version (7.1.3) does not satisfy that requirement.

True. But why does it require version 2.3.1? The last suitable version of proxy-manager for PHP 7.1 was 2.1.1?

**The dependency graph here is:**

1. `"doctrine/doctrine-migrations-bundle": "^2.0"` required in root composer.json
2. This bundle requires `"doctrine/migrations":"^2.0"`, which results in 2.0.2
3. doctrine/migrations 2.0.2 requires `"ocramius/proxy-manager": "^2.0.2"` which **should** result in 2.1.1 but it doesn't. It ignores the set platform in config of composer.json

When I ``--ignore-platform-reqs`` it installs the latest version which breaks, because no PHP 7.4 given.

When I add `ocramius/proxy-manager:"2.1.1"` in my root composer.json, it uses the correct version. But I'm curious why composer does not resolve it correctly by itself?

**Comment by alcohol** [comment]
Does composer complain about composer.json and composer.lock being out of sync?

**Comment by ArminVieweg** [comment]
No. This was the first two calls I did and their responses:

```
C:\Dev\symfony>set COMPOSER=dev-composer.json && composer install --dry-run
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ocramius/proxy-manager 2.3.1 -> satisfiable by ocramius/proxy-manager[2.3.1].
    - ocramius/proxy-manager 2.3.1 requires php ^7.4.0 -> your PHP version (7.3.4) overridden by "config.platform.php" version (7.1.3) does not satisfy that requirement.
  Problem 2
    - ocramius/proxy-manager 2.3.1 requires php ^7.4.0 -> your PHP version (7.3.4) overridden by "config.platform.php" version (7.1.3) does not satisfy that requirement.
    - doctrine/migrations v2.0.2 requires ocramius/proxy-manager ^2.0.2 -> satisfiable by ocramius/proxy-manager[2.3.1].
    - Installation request for doctrine/migrations v2.0.2 -> satisfiable by doctrine/migrations[v2.0.2].
```

```
C:\Dev\symfony>set COMPOSER=dev-composer.json && composer install --dry-run --ignore-platform-reqs
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 0 installs, 3 updates, 0 removals
  - Updating ocramius/proxy-manager (2.1.1) to ocramius/proxy-manager (2.3.1)
  - Updating doctrine/migrations (v2.0.1) to doctrine/migrations (v2.0.2)
  - Updating bafza/traeger-bundle (dev-develop 6778230) to bafza/traeger-bundle (dev-develop 4e3d900)
```

**Comment by ArminVieweg** [comment]
@alcohol But I think you are right. When I remove the lock file it has no problems and uses the correct versions.

**Comment by alcohol** [comment]
It could be someone committed a .json and .lock file that contained the version which was not actually supported. If you run install at that point on another environment, it will simply fail.

**Comment by ArminVieweg** [comment]
Okay thanks. It works now and resolving dependencies works as expected, when lock file does not contain corrupted version numbers.
