### ISSUE TITLE
multiple projects on one installation with shared git libraries

### ISSUE THREAD

**Issue by 4DallasC** [composer/composer#8125]
I'm having an issue when I have multiple websites on the one system that share the same git library. I've installed both websites from git with 'composer install'. I progressed one website and when I went back to update the other website, it gave me the following error:

Output of `composer diagnose`:
- Installing <library>/<project name> (dev-master 94ed1bc): Cloning 94ed1bcf00 from cache
    94ed1bcf00e28a137f8f3d7b954cb0288808cd08 is gone (history was rewritten?)
    Failed to download <library>/<project name> from source: Failed to execute git checkout '94ed1bcf00e28a137f8f3d7b954cb0288808cd08' -- && git reset --hard '94ed1bcf00e28a137f8f3d7b954cb0288808cd08' --

fatal: reference is not a tree: 94ed1bcf00e28a137f8f3d7b954cb0288808cd08

    Now trying to download from dist
  - Installing <library>/<project name> (dev-master 94ed1bc): Downloading (connecting...)

  [Composer\Downloader\TransportException]
  Could not authenticate against bitbucket.org

The only way I could get this to update was to copy the vendor directory and composer.lock file from the website that was working. I'm guessing that the .composer/cache has the expected results from one of the websites and it has overridden the git position of the other.  If that is correct, then the error is incorrect,

**Comment by alcohol** [comment]
When installing custom repositories or from source, we usually cache a local clone. I am not quite sure how you ran into this error though as the scenario that you describe is incomplete or not detailed enough. In theory, it should work just fine. So clearly there is something going on that is relevant for us to help determine the issue, but you are simply not sharing sufficient information.

**Comment by 4DallasC** [comment]
Hello Rob,

The only way I've been able to update the projects is to delete the .composer/cache directory. It keeps giving me this error:-

Loading composer repositories with package information                             Updating dependencies (including require-dev)         Package operations: 0 installs, 1 update, 0 removals
  - Updating repository/project dev-master (94ed1bc => a77e593):  Checking out a77e59350b
    Update failed (Failed to execute git remote set-url composer 'https://x-token-auth:***@bitbucket.org/repository/project.git' && git rev-parse --quiet --verify 'a77e59350bf5e7244e05f43ed97cfef4e4617438^{commit}' || (git fetch composer && git fetch --tags composer)

remote: Invalid username or password
fatal: Authentication failed for 'https://x-token-auth:***@bitbucket.org/repository/project.git/'
)
    Would you like to try reinstalling the package instead [yes]? yes
  - Removing repository/project (dev-master)
  - Installing repository/project (dev-master a77e593): Cloning a77e59350b from cache
    a77e59350bf5e7244e05f43ed97cfef4e4617438 is gone (history was rewritten?)
    Failed to download repository/project from source: Failed to execute git checkout 'a77e59350bf5e7244e05f43ed97cfef4e4617438' -- && git reset --hard 'a77e59350bf5e7244e05f43ed97cfef4e4617438' --

fatal: reference is not a tree: a77e59350bf5e7244e05f43ed97cfef4e4617438

    Now trying to download from dist
  - Installing repository/project (dev-master a77e593): Downloading (connecting...)

  [Composer\Downloader\TransportException]
  Could not authenticate against bitbucket.org


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

**Comment by alcohol** [comment]
I can't really reproduce this because I do not have any private repositories on bitbucket. I do know bitbucket oauth authentication is pretty finicky and there are some known issues currently. Refreshing the token currently seems to fail often (or always).
