### ISSUE TITLE
HHVM: Keyword __HALT_COMPILER must be written in lowercase

### ISSUE THREAD

**Issue by tgr** [composer/composer#8127]
Running composer on Travis with PHP set to "hhvm" with an otherwise stock config results in [this error](https://travis-ci.org/wikimedia/mediawiki-oauthclient-php/jobs/528588784):
```
$ composer self-update
Fatal error: Uncaught Error: Keyword __HALT_COMPILER must be written in lowercase in /home/travis/.phpenv/versions/hhvm-stable/bin/composer:27
```
HHVM version is 4.3.0; not sure about Composer version as `composer --version` dies with the same error, but in non-HHVM builds it is 1.8.5, so I'd assume it's the same.

**Comment by alcohol** [comment]
We no longer support HHVM.
