### ISSUE TITLE
Disable timeout (documentation?) problem

### ISSUE THREAD

**Issue by yannickroger** [composer/composer#8128]
The documentation [says](https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands) we can disable the timeout. It seems there is a problem with it.

My `composer.json`:

```json
{
    "license": "proprietary",
    "scripts": {
        "test": [
            "Composer\\Config::disableProcessTimeout",
            "echo hi"
        ]
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 1.8.5
PHP version: 7.3.4
PHP binary path: /usr/local/Cellar/php/7.3.4_1/bin/php
```

When I run this command:

```
composer test
```

I get the following output:

```
Method Composer\Config::disableProcessTimeout is not callable, can not call test script
> echo hi
hi

```

And I expected this to happen: Not to have `Method Composer\Config::disableProcessTimeout is not callable, can not call test script` warning message and have the timeout working (even if that example doesn't show it not working).

**Comment by alcohol** [comment]
This functionality only exists in the latest snapshot currently.

https://github.com/composer/composer/commit/8ac401bbd859d9b3f3268fe335e2862051d89574

**Comment by yannickroger** [comment]
That's what I was hinting in the title as being the bug. The documentation is not in sync with the last release, it can be quite misleading.

**Comment by alcohol** [comment]
Because the documentation comes from the master branch, not the latest release.

**Comment by yannickroger** [comment]
Shouldn't it come from the latest release, since that's what people are using?

**Comment by alcohol** [comment]
Too complicated, so no.

**Comment by zinthose** [comment]
30 minutes wasted trying to debug a documented feature that is not yet implemented into the current version.
#sigh

It would be nice if each feature had a tag showing the first version implementation so we can see when each feature is added to know if our current version supports it.  Could have saved me some time.

**Comment by chez14** [comment]
This actually can be documented by adding a simple line:

```html
<p><b>WARN:</b> This feature are currently in experimental and not available under stable release.</p>
```

So there's nobody fall in the same home like me and @zinthose.

**Comment by scottconnerly** [comment]
https://github.com/composer/composer/pull/8088 was when this feature was added

It appears as though it is slated for the 1.9 release: https://github.com/composer/composer/milestone/22
Presently: 71% complete  6 open  15 closed

I look forward to its arrival.
