### ISSUE TITLE
PSR-0 Autoloading issue - duplicated namespace separator

### ISSUE THREAD

**Issue by webimpress** [composer/composer#8129]
My `composer.json`:

```json
{
    "name": "webimpress/composer-autoload-issue",
    "require": {},
    "autoload": {
        "psr-0": {
            "": "src/"
        }
    }
}
```

I've prepared repository to demonstrate that issue: https://github.com/webimpress/composer-autoload-issue

So basically the file is included when autoloader is called with class name where namespace separator are duplicated, for example: `MyNamespace\\MyClass` instead of `MyNamespace\MyClass`.
However autoloading chain is not broken at this point.

For more details please see example in related repository.

The problem is not present with PSR-4 autoloading.

**EDIT:** There is Travis build: https://travis-ci.com/webimpress/composer-autoload-issue/builds/110903433

**Comment by alcohol** [comment]
https://getcomposer.org/doc/04-schema.md#autoload

> Please note namespace declarations should end in `\\` to make sure the autoloader responds exactly.

**Comment by alcohol** [comment]
If you change line in your test.php from

```
var_dump(class_exists('Webimpress\\\\ComposerAutoloadIssue\\\\Example'));
```
to
```
var_dump(class_exists('Webimpress\\ComposerAutoloadIssue\\Example'));
```

you will see that it returns true immediately.

**Comment by webimpress** [comment]
@alcohol 
> If you change line 5 in your test.php  ...

I know that, the problem is that file is loaded and I think it shouldn't be loaded in that case. When using PSR-4 for the same example it will be fine, because I will have defined namespace in `composer.json`.

I've used the simplest example to show the issue and if you think it's invalid that's fine. For me it's very edge case so maybe it's not worth fixing.

**Comment by alcohol** [comment]
> I know that, the problem is that file is loaded and I think it shouldn't be loaded in that case.

Okay, I completely missed this point from your whole issue and pull-request description. Communication remains a complicated thing on the internet :sweat_smile:

Anyway, I don't quite see the harm in this. You're describing a very unique scenario, in which most things still work as they should, but with one (possibly) unintended side-effect.

**Comment by webimpress** [comment]
No worries. My script is passing 'some strings' to `class_exists` and I got confused that file was loaded but the result was still false. And then, the same script try to load the class form the file again but using single namespace separators and file cannot be included again, because class is already defined.

I will find another solution in my script, thought that maybe resolving it on composer autoloader level is gonna be better.

Thanks for your response.

**Comment by alcohol** [comment]
Sounds to me like your script does too much escaping (`\\`). Rather than making us having to handle invalid input, it would be better to just pass in correct input.

**Comment by webimpress** [comment]
My script is not doing any escaping, but, because you said that I think now I should do unescaping.

I am doing script to detect when we can use `::class` notation instead of string. So PHP tokenizer is tokenizing the code and I am checking all strings with `\` in the name. In the configuration I have something like:

```php
return [
    'MyNamespace\\MyClass' => [
        'configuration' => [
            // ...
        ],
    ],
];
```

and string `MyNamespace\\MyClass` passed to `class_exists` gives that weird result. I will give a try with stripping slashes to check if it works as expected.

Just note: `MyNamespace\\MyClass` and `MyNamespace\MyClass` will be exactly the same in above example. In PHP `\` can be backslashed: https://3v4l.org/HX5Z5
