### ISSUE TITLE
Is it necessary to clobber cached sudo credentials when running 'composer --version'?

### ISSUE THREAD

**Issue by mwgamble** [composer/composer#8132]
I appreciate all of the reasons why composer silently clobbers cached sudo credentials, and fully agree with them. However, I don't think it's necessary to do this for operations that will never execute code that doesn't come from composer itself. Specifically, we run `composer --version` on a regular basis to check whether or not it's up to date. This operation will never run non-core code, and so it seems like overkill to clobber sudo credentials when doing so.

**Comment by mwgamble** [comment]
To be clear, at no stage are we running composer itself as root.

**Comment by alcohol** [comment]
> To be clear, at no stage are we running composer itself as root.

So then what is the issue? If you do not run it as root, there are no sudo credentials to clobber. So the thing you do not want to happen, is not happening.

:thinking:

**Comment by alcohol** [comment]
But yes, it is necessary. When running composer, regardless of flag or command given, we always do some initializing steps that in some scenarios can result in files or directories being created (and in the case of sudo, with the wrong ownership/permissions).

**Comment by mwgamble** [comment]
> So then what is the issue? If you do not run it as root, there are no sudo credentials to clobber. So the thing you do not want to happen, is not happening.

The point is that there are sudo credentials to clobber. There are some cases in some of our systems where `sudo --validate` is run, then `composer --version` is run (without sudo), then some other command is run with `sudo`. Clearly there is no security concern within composer when it comes to just outputting version information, so I'm not sure why there is a need to clobber cached sudo credentials in that case.

**Comment by alcohol** [comment]
> so I'm not sure why there is a need to clobber cached sudo credentials in that case

See my second comment.

Anyway, you can just use https://getcomposer.org/doc/03-cli.md#composer-allow-superuser if it bothers you so much.
