### ISSUE TITLE
Misconfigured config.platform.php shows HHVM version doesn't match

### ISSUE THREAD

**Issue by kelunik** [composer/composer#8138]
My `composer.json`:

```json
{
    "name": "kelunik/composer-hhvm-version-bug",
    "require": {
        "php": ">=7.1"
    },
    "config": {
        "platform": {
            "php": "7.0"
        }
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 8288d2c456287d4ec2d746db1d285d6bd82d52ec
PHP version: 7.0 - Package overridden via config.platform (actual: 7.3.3)
PHP binary path: /home/kelunik/.phpenv/versions/7.3.3/bin/php
```

When I run this command:

```
composer install
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php >=7.1 but your HHVM version does not satisfy that requirement.
```

And I expected this to happen:

The error message should say that the configured PHP version in `composer.json` doesn't match the package requirement, instead of showing a confusing message about HHVM version mismatch.

**Comment by alcohol** [comment]
This is because the `HHVM_VERSION` environment variable is set for some reason in your environment. And because of the various scenarios we have to cover, you can sometimes end up with this confusing message.

**Comment by uuf6429** [comment]
I was just about to report this issue. I hate to contradict the comment above, but it is not true.

If you look at [the code here](https://github.com/composer/composer/blob/d2ab4f66fd79e9f3fe906a8c8b2c8c183819b27a/src/Composer/DependencyResolver/Problem.php#L111), you'll see that it doesn't depend on the constant.

Naive guess: maybe it should have been an `&&` instead of an `||`?

**Comment by alcohol** [comment]
You are correct. That sounds about right. Though I think the `||` is not wrong, but it probably needs an additional check, e.g.:

```
(count($available) && $packageName === 'hhvm')
```

**Comment by Seldaek** [comment]
Sounds sensible, will commit that change.
