### ISSUE TITLE
ext-* should allow unbound constraints

### ISSUE THREAD

**Issue by dereuromark** [composer/composer#8140]
```
 "require": {
    "ext-openssl": "*",
```
This is what usually is used for ext-*

`composer validate` on a library composer.json:

![image(1)](https://user-images.githubusercontent.com/39854/57699604-65491a00-7658-11e9-8d3d-2aa21627a603.png)

The composer validate command should not error on unbound constraints (`*`) for `ext-*`
Here we often/usually do not have constraints, we only want to assert those are installed at all.

As such, this error forces us to use hacks or alternatives.

Would be nice if this got fixed up as silencing for this specific case.

**Comment by alcohol** [comment]
Controversial opinion. Maybe make it an option by use of a flag.

**Comment by dereuromark** [comment]
It could be just a warning in this case. That would probably be a good compromise.

**Comment by stof** [comment]
I think this request is valid, especially given that core PHP extensions don't always report a meaningful version.

**Comment by Seldaek** [comment]
I agree this probably should be a warning or maybe not show anything at all, it's definitely an unintended consequence of the feature as far as I am concerned as most PHP extensions have no version info.

**Comment by stof** [comment]
@dereuromark are you sure you are actually running the `composer validate` command ? The `ValidatingArrayLoader` excludes platform package names (so `php`, `ext-*`  and `lib-*`) from the unbound constraint check.

**Comment by stof** [comment]
Or maybe you are using a totally outdated version of composer, before this condition was added in https://github.com/composer/composer/commit/e7b82cdd886f305cd5b86fbf52d80e2d9020c9fb (but that goes back to 2014)

**Comment by dereuromark** [comment]
You are right, this was a side effect of some outdated tooling. I will close this as not reproducible. All seems fine here. Thank you!
