### ISSUE TITLE
Change interpretation of php platform version without hotfix version

### ISSUE THREAD

**Issue by alexander-schranz** [composer/composer#8144]
My `composer.json`:

```json
{
    "name": "l91/test",
    "require": {
        "php": "^7.1.3"
    },
    "config": {
        "platform": {
            "php": "7.1"
        }
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.5
PHP version: 7.1 - Package overridden via config.platform (actual: 7.1.28)
PHP binary path: /usr/local/Cellar/php@7.1/7.1.28_1/bin/php
```

When I run this command:

```
composer install
```

I get the following output:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php ^7.1.3 but your HHVM version does not satisfy that requirement.
```

This error is mostly not a the problem the problem is that you mostly are in the allowed range of your project and get a older version of some dependencies who requires example 7.1.3 version of php.

And I expected this to happen: install the dependencies.

**Solution A:**

Interpret a php version like `7.1` as `7.1.99999`

**Solution B:**

Don't allow php version with `7.1` and force `7.1.0` to be more specific.

**Comment by alcohol** [comment]
`7.1` is interpreted as `7.1.0` already, that is why it fails. But due to how the error resolution logic works and the fact that clearly `HHVM_VERSION` is set for some reason in your environment you get an odd error message about HHVM.

**Comment by alexander-schranz** [comment]
> 7.1 is interpreted as 7.1.0 already

That what I think is missleading as my experience was that most devs did think 7.1 is enough to set to get newest dependencies for php 7.1 version but its not so I thats why I created the issue as I think its not a good idea to interpret 7.1 as 7.1.0 in this case.

**Comment by alcohol** [comment]
What do you mean? `7.1.3` is obviously larger than `7.1` (as common sense dictates that `7.1` equals `7.1.0`). This is how semantic versioning works.

**Comment by alexander-schranz** [comment]
@alcohol as said I don't think its a good idea to interpret this value this way as I'm not possible todo something like 7.1.* or other semantic version constraints. I would interpet the version number the same way in this case like e.g. [docker images](https://hub.docker.com/_/php) does it 7.1 is the newest 7.1 php version and not to oldest.

**Comment by alcohol** [comment]
I am sorry, but your personal opinion is not really a strong motivation to change behaviour that has worked in such a way since it was implemented, and is generally expected to work this way by the majority of users.

Comparing this to how docker images are tagged and aliased is like comparing apples and pears. They are simply not one and the same. The platform config section allows a user to mock a specific version. It is not an alias or anything like that.

**Comment by alcohol** [comment]
> docker images does it 7.1 is the newest 7.1 php version and not to oldest.

We simply do not know what the latest version is. We are not configuring a constraint here. We are specifying an exact version. So if a user provides `7.1`, the best we can make of that is `7.1.0`. That is the most accurate representation. If a user wants a higher patch version, it is a very simple and trivial step for the user to include that in their composer.json.
