### ISSUE TITLE
Another Solution For Windows 10 Composer Access From WSL

### ISSUE THREAD

**Issue by joshuadabejero** [composer/composer#8145]
# Another Solution For Windows 10 Composer Access From WSL
I have found a solution how to make WSL access the composer which is installed in Windows 10.

1. Windows 10 Path which was automatically added in WSL should be disable using Registry Key.
Go to `regedit` using `Win + R` or just by searching in Start Menu.
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\{GUID}\Flags
Change the Flags' value from 7 to 5.

2. Open your WSL and create a .bash_aliases and .bash_paths.
   * In .bash_aliases add `alias composer='php.exe C:\\ProgramData\\ComposerSetup\\bin\\composer.phar'` that's my location of composer you can change it where your Composer's Bin located.

   * In .bash_paths add `export PATH="$PATH:/mnt/c/Programs/xampp/php"` `/mnt/c/Programs/xampp/php` which is my php located in.

3. Add .bash_paths to your .bashrc by adding this,
```
if [ -f ~/.bash_paths ]; then
    . ~/.bash_paths
fi
```

Now restart your WSL using `exit` command.

If you run into errors and can't access ls, cat, vim, and nano, do not be alarmed just use this command `export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`.

I hope it helps!

**Comment by johnstevenson** [comment]
Since you have installed Composer using the Windows installer, you could change the `composer` shim script (located in C:\ProgramData\ComposerSetup\bin) to: 

```sh
#!/bin/sh

php=php
dir=$(cd "${0%[/\\]*}" > /dev/null; pwd)

if [ -d /proc/cygdrive ]; then
    case $(which php) in
        $(readlink -n /proc/cygdrive)/*)
            # We are in Cygwin using Windows php, so the path must be translated
            dir=$(cygpath -m "$dir");
            ;;
    esac
elif [ -x /bin/wslpath ]; then
    # We are in WSL using Windows php, so the path must be translated
    dir=$(wslpath -m "$dir");
    php=php.exe
fi

$php "${dir}/composer.phar" "$@"
```

**Comment by joshuadabejero** [comment]
Will the update of `composer` revert the shim script back to it's default?

**Comment by johnstevenson** [comment]
No, the shim scripts are only created/replaced when Composer-Setup.exe is run. Updating Composer itself, using `self-update`, essentially downloads a new `composer.phar`.

I may well include this in future versions of Composer-Setup, since WSL has settled down, although I might wait to see what WSL2 brings, which uses an actual Linux kernel.

**Comment by joshuadabejero** [comment]
Sad to say I am not much on Hyper V so probably I will stick to WSL1 for the meantime. As long as my devs are working they way I want it use to be. I'll stay here at WSL1. Though I am currently working on a project like WSL CPanel which has a GUI and support for WSL1. If composer shim script is fixed even using `self-update` I guess thats great but those who wants to personalize their dev-environment the instruction above is the best for them as it will have manual option of adding of `windows paths` to wsl.

**Comment by johnstevenson** [comment]
> If composer shim script is fixed even using self-update I guess

As I explained, this doesn't happen. `self-update` replaces the current composer.phar with a newer version, it doesn't alter the shim script - which is installed by Composer-Setup.exe

> I guess thats great but those who wants to personalize their dev-environment the instruction above is the best for them ...

Any advice that suggests changing registry settings is, IMHO, very brittle because it is all too easy to forget what has been changed (and where). Also, you seem to be using WSL as a Unixy shell for Windows (rather than running PHP in your chosen distro) when can get the same benefits using Git bash.

**Comment by joshuadabejero** [comment]
I'm afraid if I run on WSL chosen distro it is much slower. I use those programs which can't be run on windows directly like, ruby gems / rvm, nodejs, npm, jekyll. But if it's available on windows I prioritize using windows as I have an AWS / VPS as my staging to show it to my clients.

**Comment by joshuadabejero** [comment]
@johnstevenson I tried to use your solution but I received the same error.

**Comment by joshuadabejero** [comment]
I have new solution which is easy. In .bash_aliases just add an alias for composer like this, `alias composer='cmd.exe /c composer'` which removes the complicated portion of directory.
