### ISSUE TITLE
Package\Script is not autoloadable, can not call post-package-install script

### ISSUE THREAD

**Issue by stasgar** [composer/composer#8147]
Related issues:
https://github.com/composer/composer/issues/1430, https://github.com/composer/composer/issues/3739

My `composer.json` (package):

```json
{
    "name": "my/package",
    "description": "Kodeks standard git-hooks...",
    "authors": [
        {
            "name": "...",
            "email": "..."
        }
    ],
    "require": {
        "php" : "^7.1.3"
    },
    "require-dev": {
        "composer/composer": "^1.8"
    },
    "autoload": {
        "psr-4": {
            "MyPackage\\Scripts\\": "src/"
        }
    }
}

```

My `composer.json` (project's root file):

```json
"require": {
        "php": "^7.1.3",
        "my/package": "@dev",
        ...
    },
    "require-dev": {
        ...
    },
    "autoload": {
        "files": [
          "app/Support/Helpers/helpers.php"
        ],
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
      "post-package-install": "MyPackage\\Scripts\\MyScript::run",
    },
```

And `MyScript`:
```php
<?php

namespace MyPackage\Scripts;

use Composer\Installer\PackageEvent;

/**
 * Class MyScript
 */
class MyScript
{
    /**
     * @param PackageEvent $event
     */
    public static function run(PackageEvent $event)
    {
        echo "Script is running!";
    }
```

Output of `composer diagnose`:

```
Composer version 1.8.5 2019-04-09

...Everything's OK...
Composer version: 1.8.5
PHP version: 7.2.17
PHP binary path: /usr/bin/php7.2
```

When I run this command:

```
composer update my/package
```

I get the following output:

```
...
Class MyPackage\Scripts\MyScript is not autoloadable, can not call post-package-install script
...
```

And I expected my script to run.

**Comment by stof** [comment]
The issue here is that you try to run a script on `post-package-install` relying on a class from an external package. If this package is not the first installed package, the code won't be available yet when running this script for the first package.

Using third-party code in `post-package-install` is unreliable because you cannot know yet which packages are already installed at the time this runs (as this event is not delayed until all packages are installed).

**Comment by stasgar** [comment]
Yeah, makes sense... Ok, but when i use `post-install-cmd` - i see the same error.

**Comment by alcohol** [comment]
> Yeah, makes sense... Ok, but when i use `post-install-cmd` - i see the same error.

Can you please provide us the verbose output of a full run for this?

**Comment by stasgar** [comment]
@alcohol yeah, here you go, there is nothing special here:

`composer install`:
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: barryvdh/laravel-cors
* * *
Package manifest generated successfully.
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Class MyPackage\Scripts\MyScript is not autoloadable, can not call post-install-cmd script
```

**Comment by alcohol** [comment]
And this works inside the same repo?

```php
<?php

require 'vendor/autoload.php';

var_dump(class_exists('MyPackage\Scripts\MyScript'));
```

**Comment by stasgar** [comment]
@alcohol i get false here. The reason is symlink package connection =\

Anyway, i copy-pasted my package explicitly and the error is still here (class_exists is true at this point).

**Comment by alcohol** [comment]
Need a reproducible scenario in a Github repository somewhere. Cause as far as I can tell right now, this looks to be a user error / configuration mistake. Nothing we can do here from our side.

**Comment by stasgar** [comment]
@alcohol ok, thanks. I'll take a deeper look at this one later.
