### ISSUE TITLE
$vendorDir is undefined in AutoloadGenerator

### ISSUE THREAD

**Issue by szepeviktor** [composer/composer#8150]
Could it be that `$vendorDir` and `$baseDir` are not defined in [Composer/Autoload/AutoloadGenerator.php:774](https://github.com/composer/composer/blob/master/src/Composer/Autoload/AutoloadGenerator.php#L774-L775) `getStaticFile()` ?

**Comment by szepeviktor** [comment]
Maybe they come from `require $targetDir . '/autoload_*.php'` ?

**Comment by alcohol** [comment]
No, that should never be the case.

It would help if you include a real error message that you are experiencing, with verbose output from whichever Composer command you were executing.

**Comment by szepeviktor** [comment]
> a real error message

Actually I've configured PHPStan - a static analyzer - and ran in on Composer.

**Comment by alcohol** [comment]
You can ignore that. It does not understand the difference between actual code and template code output to a file.

**Comment by alcohol** [comment]
> Maybe they come from `require $targetDir . '/autoload_*.php'` ?

This is correct.
