### ISSUE TITLE
create-project does not respect classmap-authoritative config setting

### ISSUE THREAD

**Issue by szepeviktor** [composer/composer#8155]
I've tried it with my package: composer create-project [szepeviktor/wordpress-autoloaded](https://github.com/szepeviktor/wordpress-autoloaded/blob/master/composer.json#L58)

and noticed that autoload_classmap.php contains no classes.

Could you help?

**Comment by xabbuh** [comment]
I cannot reproduce the issue with your application as the `bin/remove-class-loading.sh` produces an error:

```
$ composer create-project szepeviktor/wordpress-autoloaded composer-8155
Installing szepeviktor/wordpress-autoloaded (5.2.1)
  - Installing szepeviktor/wordpress-autoloaded (5.2.1): Downloading (100%)         
Created project in composer-8155
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing composer/installers (v1.6.0): Downloading (100%)         
  - Installing wordpress/wordpress (5.2.1): Downloading (100%)         
Writing lock file
Generating autoload files
> bin/remove-class-loading.sh
 ...
sed: -i may not be used with stdin
Script bin/remove-class-loading.sh handling the post-update-cmd event returned with error code 1
```

**Comment by szepeviktor** [comment]
Thank you!

bin/remove-class-loading.sh produces an error because of missing class maps.

It is fixed in dev-master: https://github.com/szepeviktor/wordpress-autoloaded/blob/master/bin/remove-class-loading.sh#L56-L60

**Comment by szepeviktor** [comment]
Thank you @Seldaek
