### ISSUE TITLE
Composer should warn (or even error?) if you try to require a package with the same name as the root package

### ISSUE THREAD

**Issue by naderman** [composer/composer#8156]
It doesn't make a lot of sense to require a package with the same name as the root package (so the name listed in composer.json), since it will automatically be met if the version constraint matches, or otherwise always fail.

Is there any use case for this at all? Unless anyone can think of one, i think this should error when running composer update (so also on composer require). Not sure in how far that's a problem because of existing composer.json files? Alternatively we could make it warn, and only error in composer require if someone is trying to add such a requirement.

**Comment by Seldaek** [comment]
Probably an error could be added to ConfigValidator and as guard on the `require` command. I don't think we need to fail on update/install, just not worth checking for IMO.

**Comment by LeoVie** [comment]
Hey, I'd like to implement this.

**Comment by LeoVie** [comment]
This seems to be implemented since #8247 or am I wrong?

**Comment by stof** [comment]
for the `require` command, yes. But the ConfigValidator still needs it

**Comment by LeoVie** [comment]
When I run `validate` I get the same output as when I run `require`.
![grafik](https://user-images.githubusercontent.com/7249788/97587650-ea1a2600-19fb-11eb-92f5-f54641cea06d.png)

for this `composer.json`:
```json
{
    "name": "some/package",
	"require": {
	    "some/package": "1.0"
	}
}
```

Do I get the intention of the issue wrong?

**Comment by stof** [comment]
Getting a RuntimeException for `composer validate` looks weird

**Comment by LeoVie** [comment]
Here is a Dockerfile which reproduces the behavior:
```dockerfile
FROM composer/composer
RUN echo "{\"name\": \"some/package\", \"require\": { \"some/package\": \"dev-master\" }}" > /app/composer.json
RUN composer validate
```

If you build this, you get the RuntimeException.

**Comment by stof** [comment]
@LeoVie can you run it with `-v` to get the stack trace ?
I think that the RuntimeException might be implemented in the wrong place to let `validate` run properly.

**Comment by LeoVie** [comment]
Of course, this gives the following trace:
```
 () at phar:///usr/bin/composer/src/Composer/Package/Loader/RootPackageLoader.php:144
 Composer\Package\Loader\RootPackageLoader->load() at phar:///usr/bin/composer/src/Composer/Factory.php:351
 Composer\Factory->createComposer() at phar:///usr/bin/composer/src/Composer/Factory.php:576
 Composer\Factory::create() at phar:///usr/bin/composer/src/Composer/Console/Application.php:368
 Composer\Console\Application->getComposer() at phar:///usr/bin/composer/src/Composer/Console/Application.php:486
 Composer\Console\Application->getPluginCommands() at phar:///usr/bin/composer/src/Composer/Console/Application.php:178
 Composer\Console\Application->doRun() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/bin/composer/src/Composer/Console/Application.php:113
 Composer\Console\Application->run() at phar:///usr/bin/composer/bin/composer:61
 require() at /usr/bin/composer:24
```

**Comment by stof** [comment]
OK, so this was indeed added a long time ago in https://github.com/composer/composer/pull/4838

**Comment by Seldaek** [comment]
Oh sorry for wasting your time @LeoVie, I didn't realize this was done already :)
