### ISSUE TITLE
Script cache:clear returned with error code -1073741819

### ISSUE THREAD

**Issue by ivanovnickolay** [composer/composer#8157]
This project in PHP 7.1.7 does not have such problems. When you switch to the new version (copying the project folder, not repository cloning), it immediately shows errors when running tests.

My `composer.json`:
`{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "beberlei/doctrineextensions": "v1.1.2",
        "box/spout": "2.8.x-dev",
        "mikey179/vfsstream": "2.0.x-dev",
        "phpoffice/phpspreadsheet": "1.3.1",
        "sensio/framework-extra-bundle": "^5.1",
        "symfony/annotations-pack": "v1.0.0",
        "symfony/apache-pack": "v1.0.1",
        "symfony/asset": "4.1.x-dev",
        "symfony/browser-kit": "4.1.x-dev",
        "symfony/console": "^4.1",
        "symfony/flex": "^1.0",
        "symfony/form": "4.1.x-dev",
        "symfony/framework-bundle": "^4.1",
        "symfony/lts": "^4@dev",
        "symfony/maker-bundle": "1.0.0",
        "symfony/orm-pack": "^1.0",
        "symfony/profiler-pack": "v1.0.3",
        "symfony/twig-bundle": "4.0.x-dev",
        "symfony/validator": "4.1.x-dev",
        "symfony/yaml": "^4.1"
    },
    "require-dev": {
        "symfony/dotenv": "^4.1",
        "symfony/webpack-encore-bundle": "v1.1.0"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false
        }
    }
}
`

Output of `composer diagnose`:
`Checking composer.json: WARNING
require.beberlei/doctrineextensions : exact version constraints (v1.1.2) should be avoided if the package follows semantic versioning
require.box/spout : exact version constraints (2.8.x-dev) should be avoided if the package follows semantic versioning
require.mikey179/vfsstream : exact version constraints (2.0.x-dev) should be avoided if the package follows semantic versioning
require.phpoffice/phpspreadsheet : exact version constraints (1.3.1) should be avoided if the package follows semantic versioning
require.symfony/annotations-pack : exact version constraints (v1.0.0) should be avoided if the package follows semantic versioning
require.symfony/apache-pack : exact version constraints (v1.0.1) should be avoided if the package follows semantic versioning
require.symfony/asset : exact version constraints (4.1.x-dev) should be avoided if the package follows semantic versioning
require.symfony/browser-kit : exact version constraints (4.1.x-dev) should be avoided if the package follows semantic versioning
require.symfony/form : exact version constraints (4.1.x-dev) should be avoided if the package follows semantic versioning
require.symfony/maker-bundle : exact version constraints (1.0.0) should be avoided if the package follows semantic versioning
require.symfony/profiler-pack : exact version constraints (v1.0.3) should be avoided if the package follows semantic versioning
require.symfony/twig-bundle : exact version constraints (4.0.x-dev) should be avoided if the package follows semantic versioning
require.symfony/validator : exact version constraints (4.1.x-dev) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (dd40d74bf6041ddcefa1ebe46fb9117d031b1ccd => 1.8.5)
Composer version: dd40d74bf6041ddcefa1ebe46fb9117d031b1ccd
PHP version: 7.3.4
PHP binary path: C:\Web\php\php.exe
`

When I run this command:
`composer.phar update --no-interaction --ansi
 Loading composer repositories with package information
 Updating dependencies (including require-dev)
 Nothing to install or update
 Generating autoload files
 ocramius/package-versions:  Generating version class...
 ocramius/package-versions: ...done generating version class
 Executing script cache:clear [KO]
  [KO]
 Script cache:clear returned with error code -1073741819
 !!
 Script @auto-scripts was called via post-update-cmd
 Failed to update packages for  ./composer.json.`
```
Error codes are the same!

`php.exe phpunit --configuration \phpunit.xml.dist Test.php --teamcity Process finished with exit code -1073741819 (0xC0000005)`
`bin\console --version Process finished with exit code -1,073,741,819 at 01:00:27`
```

I get the following output:

```
...replace me...
```

And I expected this to happen:

**Comment by alcohol** [comment]
This is not a Composer error.
