### ISSUE TITLE
PHP Fatal error: setDistUrl() not found

### ISSUE THREAD

**Issue by PhilippGrashoff** [composer/composer#8159]
Hi there,

Until today everything worked fine. I just pulled the master of a repository required in composer.json. Today, I needed to define a commit ID to pull from this repository. After I changed to this, I do get the following PHP error when running `php composer.phar update`:

```
Fatal error: Uncaught Error: Call to undefined method Composer\Package\AliasPackage::setDistUrl() in phar:///path/to/my/composerphar/composer.phar/src/Composer/Installer.php:1223
Stack trace:
#0 phar:///path/to/my/composerphar/composer.phar/src/Composer/Installer.php(563): Composer\Installer->updateInstallReferences(Object(Composer\Package\AliasPackage), '09a3858')
#1 phar:///path/to/my/composerphar/composer.phar/src/Composer/Installer.php(229): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Repository\CompositeRepository), Object(Composer\Repository\PlatformRepository), Array)
#2 phar:///path/to/my/composerphar/composer.phar/src/Composer/Command/UpdateCommand.php(163): Composer\Installer->run()
#3 phar:///path/to/my/composerphar/composer.phar/vendor/symfony/console/Command/Command.php(245): Composer\Command\UpdateCommand->execute(Object(Symfony\Compon in phar:///path/to/my/composerphar/composer.phar/src/Composer/Installer.php on line 1223
```

The commit number `09a3858` comes from a public repository, I define it like this in composer.json:
```
"somevendor/somerepo": "dev-master#09a3858 as master",
```

The composer.phar is the newest 1.8.5.

Strangely, I only get this error sometimes. The repo that causes this is not on packagist or so, but added to composer.json like 
```
  "repositories": [
    {
      "type": "vcs",
      "url":  "git@github.com:somevendor/somerepo.git"
    }
  ],
```

Best regards
Philipp

**Comment by alcohol** [comment]
It seems this method is not inherited. You are using an alias combined with the unsupported commit notation.

Regardless, we do not officially support this functionality, so I am closing this issue.

https://getcomposer.org/doc/articles/troubleshooting.md#i-have-locked-a-dependency-to-a-specific-commit-but-get-unexpected-results-

**Comment by PhilippGrashoff** [comment]
HI there, thanks for the reply.
Could you point me what is a supported commit notation? the complete commit ID, not just the first 7 chars?

Thanks
Philipp

**Comment by alcohol** [comment]
We do not support any commit notation.
