### ISSUE TITLE
composer autoloader does not load all PSR-4 namespaces when using -o & --no-dev

### ISSUE THREAD

**Issue by fritzmg** [composer/composer#8163]
I just came across an odd issue. If your root `composer.json` contains a dev dependency, which is actually otherwise a regular dependency of one of your root dependencies, then the autoloader does not load all PSR-4 namespaces for some reason when using `--optimize-autoloader` __and__ `--no-dev`.

For example: https://pastebin.com/pBPx11ep

When you run
```
composer update --optimize-autoloader --no-dev
```
on this `composer.json`, the autoloader will not load all namespaces, resulting in an error at the end of the operation.
```
Fatal error: Uncaught Error: Class 'DependencyInjection\Container\ContaoManager\Plugin' not found
```
Omitting either `--optimize-autoloader` or `--no-dev` causes the autoloader to correctly autoload all namespaces again.

~~The "fix" for me is easy, since it does not make sense to require that package as a dev dependency (it was just an experiment for something else entirely) - however I find it still odd, that the autoloader seemingly randomly skips autoload of some namespaces - which do not even have anything to do with the dev dependency.~~

```
$ composer diagnose
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Defining autoload.psr-4 with an empty namespace prefix is a bad idea for performance
require.inspiredminds/contao-backend-forms : unbound version constraints (dev-master) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 1.8.5
PHP version: 7.2.99 - Package overridden via config.platform (actual: 7.1.29)
PHP binary path: C:\ProgramData\scoop\apps\php71\current\php.exe
```

**Comment by fritzmg** [comment]
Sorry - looks like my analysis was wrong. Removing `"symfony/framework-bundle": "^4.2"` as a dev dependency did not actually fix it :(

**Comment by fritzmg** [comment]
I did some further testing. Using the above `composer.json` alone will not reproduce the problem. Thus I compared the existing installation with the fresh one, to figure out what's different. I then noticed, that in the fresh installation, the package
```
menatwork/contao-multicolumnwizard
``` 
was installed, while in the existing installation where the problem occurs, the package
```
menatwork/contao-multicolumnwizard-bundle
```
was installed, which replaces `menatwork/contao-multicolumnwizard`. Curiously, when I executed
``` 
$ composer why menatwork/contao-multicolumnwizard-bundle
```
composer told me:
```
There is no installed package depending on "menatwork/contao-multicolumnwizard-bundle"
```
But how could this be?  Then I remembered, that I did a downgrade of a package, which would have affected which of these two packages would be installed.

So, when you do a fresh installation with the above `composer.json`, only `menatwork/contao-multicolumnwizard`. But when you update `inspiredminds/contao-isotope-pdf-templates` to `~2.1.0` from `~2.0.0`, `menatwork/contao-multicolumnwizard-bundle` will replace `menatwork/contao-multicolumnwizard`, since `inspiredminds/contao-isotope-pdf-templates:2.1.x` required `menatwork/contao-multicolumnwizard-bundle`.

When you downgrade back to `~2.0.0` though, `menatwork/contao-multicolumnwizard-bundle` stays - and that's when the error happens.

So to reproduce the error, you must run the following on the above `composer.json`:
```
composer update
composer require inspiredminds/contao-isotope-pdf-templates:~2.1.0 --no-update
composer update
composer require inspiredminds/contao-isotope-pdf-templates:~2.0.0 --no-update
composer update -o --no-dev
```

**Comment by alcohol** [comment]
Considering the edge-case scenario, it is unlikely this will be picked up though. There is bigger work in progress that might eventually make this bug obsolete anyway.

**Comment by fritzmg** [comment]
Agreed. I mainly wanted to document it for posterity - in case anyone runs into this as well.

**Comment by Seldaek** [comment]
This most likely will get fixed by 2.0 as the resolution is more resilient to such cases where something disappears in a subsequent update and it leaves the project in a different state than if you did an clean update from scratch. Not really worth investing time until 2.0 is further and we can actually check.

**Comment by jeffsrepoaccount** [comment]
Also wanting to document this for posterity, I ran into a very similar issue to this using composer version 1.9.1. Running `composer install --no-dev -o` would cause some PSR4 package classes not to be present in `vendor/composer/autoload_psr4.php`. Downgrading to 1.6.3 fixed the issue.

**Comment by Seldaek** [comment]
Looks like this is fixed by https://github.com/composer/composer/pull/8621
