### ISSUE TITLE
VersionGuesser fails in GitLab-CI

### ISSUE THREAD

**Issue by maglnet** [composer/composer#8164]
Hi there,

we're currently experiencing problems within our Gitlab-CI build environment.  
Since Gitlab-CI-Runner version 1.9.x only fetches a single commit, composer is not able to guess the correct package version anymore.  
The problem in our case is that circular dependencies (I know that's not good) are now not installable anymore because composer does not correctly guess the branch name / branch alias.

I have an example project setup here:
https://gitlab.com/maglnet/test-composer-version
and the corresponding build job is here:
https://gitlab.com/maglnet/test-composer-version/-/jobs/222968864

So now i would like to create a MR to get this working again, and would like to get some input of you, which solution would be preferred:

1. GitLab specific: check if we're in a Gitlab-CI-Environment (possible through env vars) and then use the GitLab API to list branches and get the correct branch name for the given commit hash. This would result in something like `guessGitLabCiVersion()` within the `VersionGuesser`
2. Git specific: if we find us in detached head mode, it might be possible to get all informations by fetching everything within `guessGitVersion()` within `VersionGuesser`.

best regards,
Matthias

----
My `composer.json`:

```json
{
    "name": "mglaub/test-composer-version",
    "type": "library",
    "authors": [
        {
            "name": "Matthias Glaub",
            "email": "matthias.glaub@milchundzucker.de"
        }
    ],
    "require": {}
}

```

When I run this command:

```
composer show -s
```

I get the following output:

```
name     : mglaub/test-composer-version
descrip. : 
keywords : 
versions : * dev-6170b3a26b866e00088bb806757293e81e55d0e5
type     : library
source   : []  6170b3a26b866e00088bb806757293e81e55d0e5
dist     : []  6170b3a26b866e00088bb806757293e81e55d0e5
path     : 
names    : mglaub/test-composer-version
```

And I expected this to happen:
``` 
versions : * dev-master
```

**Comment by alcohol** [comment]
This is what https://getcomposer.org/doc/03-cli.md#composer-root-version is for.
Also, don't use circular dependencies.
