### ISSUE TITLE
Upgrade laravel 

### ISSUE THREAD

**Issue by NomiJutt123** [composer/composer#8167]
how can i upgrade php version in composer beacuse i am using wamp and in wamp it show php verion is 7.3.5 butt in composer it have 5.6 i am use laravel not when i try to update laravel verion it say your php version is 5.6 butt this require 7.1

**Comment by alcohol** [comment]
Update the config platform section in your `composer.json`.

**Comment by NomiJutt123** [comment]
This error occur
c:\wamp64\www\first_try>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php >=7.3.5 but your HHVM version does not satisfy that requirement.
  Problem 2
    - laravel/framework v5.8.9 requires php ^7.1.3 -> your PHP version (5.6.40) overridden by "config.platform.php" version (5.6.1) does not satisfy that requirement.
    - laravel/framework v5.8.8 requires php ^7.1.3 -> your PHP version (5.6.40) overridden by "config.platform.php" version (5.6.1) does not satisfy that requirement.
    - laravel/framework v5.8.7 requires php ^7.1.3 -> your PHP version (5.6.40) overridden by "config.platform.php" version (5.6.1) does not satisfy that requirement.
    - laravel/framework v5.8.6 requires php ^7.1.3 -> your PHP version (5.6.40) overridden by "config.platform.php" version (5.6.1) does not satisfy that requirement.
    - laravel/framework v5.8.5 requires php ^7.1.3 -> your PHP version (5.6.40) overridden by "config.platform.php" version (5.6.1) does not satisfy that requirement.
    - laravel/framework v5.8.4 requires php ^7.1.3 -> your PHP version (5.6.40) overridden by "config.platform.php" version (5.6.1) does not satisfy that requirement.
    - laravel/framework v5.8.3 requires php ^7.1.3 -> your PHP version (5.6.40) overridden by "config.platform.php" version (5.6.1) does not satisfy that requirement.
    - laravel/framework v5.8.2 requires php ^7.1.3 -> your PHP version (5.6.40) overridden by "config.platform.php" version (5.6.1) does not satisfy that requirement.
    - laravel/framework v5.8.19 requires php ^7.1.3 -> your PHP version (5.6.40) overridden by "config.platform.php" version (5.6.1) does not satisfy that requirement.
    - laravel/framework v5.8.18 requires php ^7.1.3 -> your PHP version (5.6.40) overridden by "config.platform.php" version (5.6.1) does not satisfy that requirement.
    - laravel/framework v5.8.17 requires php ^7.1.3 -> your PHP version (5.6.40) overridden by "config.platform.php" version (5.6.1) does not satisfy that requirement.
    - laravel/framework v5.8.16 requires php ^7.1.3 -> your PHP version (5.6.40) overridden by "config.platform.php" version (5.6.1) does not satisfy that requirement.
    - laravel/framework v5.8.15 requires php ^7.1.3 -> your PHP version (5.6.40) overridden by "config.platform.php" version (5.6.1) does not satisfy that requirement.
    - laravel/framework v5.8.14 requires php ^7.1.3 -> your PHP version (5.6.40) overridden by "config.platform.php" version (5.6.1) does not satisfy that requirement.
    - laravel/framework v5.8.13 requires php ^7.1.3 -> your PHP version (5.6.40) overridden by "config.platform.php" version (5.6.1) does not satisfy that requirement.
    - laravel/framework v5.8.12 requires php ^7.1.3 -> your PHP version (5.6.40) overridden by "config.platform.php" version (5.6.1) does not satisfy that requirement.
    - laravel/framework v5.8.11 requires php ^7.1.3 -> your PHP version (5.6.40) overridden by "config.platform.php" version (5.6.1) does not satisfy that requirement.
    - laravel/framework v5.8.10 requires php ^7.1.3 -> your PHP version (5.6.40) overridden by "config.platform.php" version (5.6.1) does not satisfy that requirement.
    - laravel/framework v5.8.1 requires php ^7.1.3 -> your PHP version (5.6.40) overridden by "config.platform.php" version (5.6.1) does not satisfy that requirement.
    - laravel/framework v5.8.0 requires php ^7.1.3 -> your PHP version (5.6.40) overridden by "config.platform.php" version (5.6.1) does not satisfy that requirement.
    - Installation request for laravel/framework 5.8.* -> satisfiable by laravel/framework[v5.8.0, v5.8.1, v5.8.10, v5.8.11, v5.8.12, v5.8.13, v5.8.14, v5.8.15, v5.8.16, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.3, v5.8.4, v5.8.5, v5.8.6, v5.8.7, v5.8.8, v5.8.9].

**Comment by NomiJutt123** [comment]
Thanks 

> Update the config platform section in your `composer.json`.

Thanks Sir For Slove my issue
