### ISSUE TITLE
Display platform requirement without check

### ISSUE THREAD

**Issue by macintoshplus** [composer/composer#8171]
How to display the platform requirement without checks ?
I want the resolved minimum PHP version requirement and the maximum PHP version (with all extensions needed).

For example, a command like `composer platform-reqs` with output:
```
php min 5.6.0 max 7.3.999999
ext-ldap *
ext-curl *
ext-mbstring *
...
```

This command extract information from the project's composer.json and all dependency platform requirements.

This can help to list the PHP version and extension requirement for reporting this information and manage the project portfolios.

**Comment by Seldaek** [comment]
It's not as simple as min/max.. There might be 20 packages requiring php in different version ranges. The check command checks whether all constraints are fulfilled, but in your case I am not sure what we would list. Figuring the smallest constraint of all might be tricky I am not sure.

**Comment by alcohol** [comment]
I think basically what he wants is a command that goes through all platform specific dependencies, recursively, and determines what the lowest boundary is and what the highest boundary is. Technically I think this can be done. But it is a lot of work for something not very important.

**Comment by Seldaek** [comment]
Closing as I don't think it's gonna happen.
