### ISSUE TITLE
Package phpoffice/phpspreadsheet at version  has a PHP requirement incompatible with your PHP version (5.5.9) 

### ISSUE THREAD

**Issue by Kat35601** [composer/composer#8172]
when running this command "php composer.phar require phpoffice/phpspreadsheet" I get this error

[InvalidArgumentException]                                                                                     
  Package phpoffice/phpspreadsheet at version  has a PHP requirement incompatible with your PHP version (5.5.9)

**Comment by xabbuh** [comment]
It seems that this package requires at least PHP 5.6 (you can see them all at https://packagist.org/packages/phpoffice/phpspreadsheet) while the Composer process runs with PHP 5.5.9.
