### ISSUE TITLE
Allow scripts/plugins to prevent a package from being uninstalled

### ISSUE THREAD

**Issue by andrewbelcher** [composer/composer#8177]
## Summary
Is there a way for a plugin (or script) to prevent the a package being uninstalled (as in removed from disk) when it is no longer required? I took a look around `pre-package-uninstall`, but I couldn't see a way for the subscribers to prevent the uninstall.

## Scenario
This is a little bit of an edge case, so I thought it would be more appropriate as a script or plugin. I'm managing a Drupal project with composer. Composer manages the code including the modules, but they are enabled independently within Drupal. Modules should be uninstalled rather than just removed (for example they may clean up things in the database etc). This means that you have to keep the code in place until the module is uninstalled and _then_ you can remove it.

This essentially means that any deployment that removes a package has to be a two step process, which the deployment process a bit more complicated and tricky. This is especially the case when the removed dependency is actually not a root level dependency, as you may have never explicitly depended on it. The direct dependency may have changed how it did something and no longer required the other package, but Drupal still has it installed. A `pre-package-uninstall` script that uninstalls the module before removing it may not work in this case, as the direct dependency may need to run data migration into a new structure before the old is removed.

The best I can work out at the moment is a script that adds additional root requirements for any enabled modules, but this gets a little complicated as you need this to only run on production (as removing in a dev environment before deployed to production will lead back to the initial problem).

However, if I can create a script/plugin that will prevent uninstall, I can make sure that in any environment, the code for enabled modules remains present (and will be cleared up the next install after the module is uninstalled in Drupal).

**Comment by alcohol** [comment]
Unlikely this will be supported. I cannot see a good reason for giving plugins control over what a user wants to install or uninstall.

**Comment by andrewbelcher** [comment]
Isn't any system where a package requires some kind of 'uninstall' going to have a similar issue? At the moment it has the be handled via manually staged releases, where as this could automate that.

**Comment by alcohol** [comment]
It should be part of the enabling/disabling step imho. Has little to nothing to do with managing dependencies inside the `vendor` directory.

**Comment by Seldaek** [comment]
This might be possible by hooking into the pre-dependencies-solving event, and modifying the $request object to force those packages to be still present, but that's pretty much like adding root requirements as you mentioned above.

There is no way to change what gets applied once the dependency resolution has occurred I am afraid.. But what you *could* do although it could get messy IMO is to register a new custom installer (https://getcomposer.org/doc/articles/custom-installers.md) that would conditionally ignore uninstall() operations given to it..  

In theory the custom installer route is the way to go I'd say as it lets you handle uninstall cleanly. Doing it in stages gets more complex though as it won't play in the composer workflow very well and will require you to conditionally do uninstall or prepare for uninstall or what do I know..

**Comment by andrewbelcher** [comment]
@Seldaek My understanding is handling at the point of dependencies is part of update rather than install? We wouldn't look to run update on a production environment, so I think that might not work.

@alcohol So the complication with that is the two are often blurred. As an example, if module A brings functionality in house where it previously depended on module B, you need to have the updated code of A available (and possibly run some migrations) before disabling the module B. Which means your workflow has to be:

1. Add B as a root requirement (it wasn't previously as it was part of A's requirements)
2. Update A
3. Tag release 2
4. Deploy production (checkout 2, composer install, run updates)
5. Remove B as a root requirement
6. Tag release 3
7. Deploy (checkout 3, composer install)

You also have to ensure every environment you deploy 2 to every environment (e.g. to go from 1 to 4, you'd actually have to go 1 to 2, 2 to 4). It's also very hard to script or automate as it's hard to make a script aware of which tags are required intermediaries.

If I can prevent the removal as part of a plugin (which can check whether it's currently installed on the given environment), your steps could be:

1. Update A [B removed from composer.lock but code not removed]
2. Tag release 2
3. Deploy production (checkout 2, composer install [B not removed], run updates, composer install [B now removed])

There's no special or additional tags, no adding temporary root requirements etc and would be very easy to automate (a second composer install on a release without a removed module will simply do nothing).

**Comment by alcohol** [comment]
IMHO this goes way beyond the scope of a dependency/package manager. You're talking about a whole lifecycle/flow in your application with regards to updates and downgrades, etc.

**Comment by andrewbelcher** [comment]
Thanks for the thoughts and suggestions. A quick look at custom installers suggests that may do the job!

**Comment by freality** [comment]
From what I see in `Composer\EventDispatcher\EventDispatcher::doDispatch`, if an event script was to throw, the operation halts. So, to prevent uninstall, a `pre_package_uninstall` script could do its check and throw an error if package does not meet remove requirements.

**Comment by Seldaek** [comment]
@andrewbelcher the dependency resolution I mentioned happens in installs as well as update, to figure out what to do from the vendor dir to the desired state. What changes is in updates the desired state is "whatever is new" while in install it's "what the lock file says".

**Comment by andrewbelcher** [comment]
Thanks all for the pointers. I've got a plugin that handles my case perfectly. Still need a separate deploy to get the plugin installed, but all future deploys are correctly handled. https://packagist.org/packages/freelygive/drupal-composer-preserve if anyone is interested. Pretty barebones atm, but if it starts getting wider use it can be improved and get some test coverage!
