### ISSUE TITLE
Files not being processed in AutoloadGenerator::createLoader()

### ISSUE THREAD

**Issue by gsomoza** [composer/composer#8192]
The "files" key for the `array $autoloads` argument is being ignored here: https://github.com/composer/composer/blob/cd15bbd64bf303937b9a2abc7df85366ab1bb821/src/Composer/Autoload/AutoloadGenerator.php#L426

I arrived to that line when trying to debug why my Composer plugin, which depends on certain files being auto-loaded properly, wasn't working due to those files not being auto-loaded.

**Environment**
Tested with PHP 7.2.13 on OSx 10.14.5 – but I'd expect this to be reproducable in other environments.

**Steps to Reproduce**

1. Create a Composer plugin and require ringcentral/psr7 (a package that auto-loads a file with several functions)
2. In your plugin, call function `RingCentral\Psr7\str` with a dummy message.
3. Run your plugin in another context (e.g. another Composer project or the global composer).

**Expected Result**
The function is called correctly and outputs a string representation of the message.

**Actual Result**
An exception: `Fatal error: Uncaught Error: Call to undefined function RingCentral\Psr7\str()`

**Notes**
1. The issue can be avoided with code on the plugin's `activate` function, but that's a workaround.
2. This only seems to happen to me in the context of using a Composer plugin. Am I missing something?
3. I put a breakpoint on the files to confirm they're indeed never autoloaded.

If this issue is confirmed and there's a recommended solution then I'd be happy to spend some time to submit a PR.

**Comment by gsomoza** [comment]
FYI here's how I solved it for now in my plugin: https://github.com/gsomoza/composer-plugin-file-loader

**Comment by alcohol** [comment]
This is actually expected behaviour. We do not support the 'files' autoload section for plugins or scripts in the dynamic autoloader used at runtime.

**Comment by alcohol** [comment]
> Callbacks can only autoload classes from psr-0, psr-4 and classmap definitions. If a defined callback relies on functions defined outside of a class, the callback itself is responsible for loading the file containing these functions.

Same applies for plugins.

**Comment by gsomoza** [comment]
Thanks for the quick response. I'd be interested in knowing the reason behind that: I understand why you wouldn't want to autoload files from the "user" project (i.e. where the plugin is operating against, which seems to be the case addressed by the "scripts" documentation), but why not autoload files declared in the dependencies of the plugin itself?

**Comment by gsomoza** [comment]
If this would require too much explanation then it's OK, I don't want to bother too much as I know you guys are swamped..

**Comment by alcohol** [comment]
I don't remember the specific reason. It has been like this ever since it was implemented.

**Comment by gsomoza** [comment]
Could that mean there's an opportunity to improve something here? It seems to me that, at least in theory, all dependencies from plugins should be auto-loaded properly. I'm willing to work on a PR for that if the core team finds it interesting.

**Comment by alcohol** [comment]
No, I am pretty sure it was intentional. @Seldaek do you remember the specific reason?

**Comment by Seldaek** [comment]
The main problem is files autoloading typically loads functions into the global namespace, and plugins can be autoloaded multiple times, leading to clashes and fatal errors if we load files autoloading multiple times. The plugin class should be standalone as much as possible to avoid dependencies breaking the plugin in update cases..

**Comment by gsomoza** [comment]
Hmm yes I see the potential issue.. makes sense. Thanks for clarifying!
