### ISSUE TITLE
Add the ability to automatically remove any temporary dependency's directories.

### ISSUE THREAD

**Issue by HRADigital** [composer/composer#8199]
How much of a possibility would be, to remove any temporary development directories from dependencies, when using `composer install --no-dev`?

This command, installs all (_production_) dependencies, **except** development dependencies.
This is used on **Production Environments**.
In these Environments, it doesn't make much sense to keep testing directories and/or other testing assets.

One possible solution, could be to add a parameter on `composer.json`, that will inform `composer` what to remove when `composer install --no-dev` is invoked.

The command would still perform in **the same exact way**, but would also perform **one extra action** for each one of the provided values.

`composer.json` could have the following parameter:

```json
...
"dev-assets": [
    "./tests/",
    "./**/*.md",
    "./dir..."
],
...
```

_**Note:** the parameter's name, is obviously opened for discussion._

The expected result, would be to have a `/vendor` directory stripped/cleaned from any testing code.

If this parameter is not present in `composer.json`, then the extra action would be completely skipped.

**Comment by alcohol** [comment]
If you use `dist` type installs, this already happens for many dependencies that make use of `.gitattributes`, see for example https://github.com/thephpleague/iso3166/blob/master/.gitattributes

It is unlikely this will ever be implemented as a feature in Composer. If you really believe that stripping your `vendor/` directory will yield you any benefit at all (which it really does not), you can always make it a part of your deployment pipeline.

**Comment by Seldaek** [comment]
You can use https://github.com/barryvdh/composer-cleanup-plugin if that's something you really care for.
