### ISSUE TITLE
Make sure the package is available locally before removing an old version

### ISSUE THREAD

**Issue by rentalhost** [composer/composer#8201]
When I run `composer update`, sometimes it fails during package install (after it being already removed). Because of that, it will cause 500 Error on production app, because it depends of this package installed. So I need clear the cache, then run `composer update` again to it be installed again.

**This is the execution flow** (I have put some spaces to make it better to read):

```
/* MAKE SURE THAT COMPOSER IS UPDATED. */

root@server [~]# composer self-update
Updating to version 1.8.6 (stable channel).
   Downloading (100%)
Use composer self-update --rollback to return to version 1.8.5

/* STARTS HERE. */

root@server [~]# cd /home/APP_PATH/public_html/
root@server [/home/APP_PATH/public_html]# ea-php72 /usr/local/bin/composer update vendor/package

Loading composer repositories with package information
Updating dependencies (including require-dev)

Package operations: 0 installs, 1 update, 0 removals

  - Updating vendor/package dev-master (8381fcc => 21838ac):  Checking out 21838ac658

    Update failed (Failed to execute git remote set-url composer 'https://x-token-auth:***@bitbucket.org/vendor/package.git' && git rev-parse --quiet --verify '21838ac658a5e3d2ef1865ce5dfb9c0d62f7ab01^{commit}' || (git fetch composer && git fetch --tags composer)
      remote: Invalid username or password
      fatal: Authentication failed for 'https://x-token-auth:***@bitbucket.org/vendor/package.git/'
    )

    Would you like to try reinstalling the package instead [yes]? yes

  - Removing vendor/package (dev-master)
  - Installing vendor/package (dev-master 21838ac): Cloning 21838ac658

    Failed to download vendor/package from source: Failed to execute git clone --no-checkout 'https://x-token-auth:***@bitbucket.org/vendor/package.git' '/home/APP_PATH/public_html/vendor/vendor/package' && cd '/home/APP_PATH/public_html/vendor/vendor/package' && git remote add composer 'https://x-token-auth:***@bitbucket.org/vendor/package.git' && git fetch composer

    Now trying to download from dist
  - Installing vendor/package (dev-master 21838ac): Downloading (connecting...)

  [Composer\Downloader\TransportException]
  Could not authenticate against bitbucket.org
```

**Possible solutions:**

1. Make sure that package is fully downloaded to local before remove it;
2. Install package in a temporary folder first, then rename old version to a temporary name, rename the new package to final name, and then remove old version (this will reduce a lot of app unavailability);

**Comment by alcohol** [comment]
You should not run Composer on production environments. Use deployment artifacts instead.

**Comment by alcohol** [comment]
On a side note, this kind of behaviour is already on the roadmap if I am not mistaken, for 2.x or 3.x.

**Comment by rentalhost** [comment]
What kind of deployment artifact I should use as replacement to composer in production? I could not find it. I appreciate if you can help me. Thanks!

**Comment by stof** [comment]
First, you should never run `composer update` in production or during the deployment process, as this would update dependencies (and so deploying untested code). The deployment process should rely on `composer install` to use the lock file.

And to avoid downtime, your deployment process should prepare the whole source code (new version of your app code, and new version of vendors) before making the code live. Even if composer would update each package in an atomic way, this would not prevent downtime, as you would still be running a mix of old and new code (some packages updated and others not yet). Tools like capistrano solve this by installing the full project (both your code and the vendors) in a separate folder, and then swapping the document root to point to the new code. Some other deployments tools use the same strategy. Other tools build an image first (Docker, but also IAAS like Heroku, Platform.sh or Symfony Cloud for instance) which is then deployed.

**Comment by Seldaek** [comment]
This will be fixed in Composer v2 as we download before installing there, but what @alcohol and @stof said is also very true..
