### ISSUE TITLE
Junctioning Vendor from Composer into a LocalVendor Symlink, Stopped Working on Package change?

### ISSUE THREAD

**Issue by bbruman** [composer/composer#8204]
What's the right syntax in my `composer.json` file to override the default vendor packages with one on my local system?

I have it working for one -- well I had it working for both -- until one of the package names changed on [packagist](https://packagist.org/packages/mithereal/bonanza).

Here's my minified `composer.json` file I've been trying to mess with to get it working.

    {
        "name": "vendorname/packagename",
        "minimum-stability": "dev",
        "prefer-stable": true,
        "require": {
            "vantoozz/proxy-scraper": "1.8.0.01",
            "mithereal/bonanza":  "dev-master"
        },
        "repositories": [
        {
            "type": "path",
            "url": "src/vendorlocal/vantoozz/proxy-scraper",
            "options": {
                "symlink": true
            }
        },
        {
            "type": "path",
            "url": "src/vendorlocal/mithereal/bonanza",
            "options": {
                "symlink": true
            }
        }
    ]
    
    }

the `"vantoozz/proxy-scraper": "1.8.0.01",` repository works fine for a local vendor package, and always created a `symlink` in the `vendor` folder which points to my `localvendor` "fork"...

This one, `"mithereal/bonanza":  "dev-master"`, I cannot seem to get to symlink to my local folder and instead it just acts as a normal vendor package.

Here's what happens with a `composer update`

    > $ composer update Loading composer repositories with package
    > information Updating dependencies (including require-dev) Package
    > operations: 2 installs, 0 updates, 0 removals
    >   - Installing vantoozz/proxy-scraper (1.8.0.01): Junctioning from src/vendorlocal/vantoozz/proxy-scraper
    >   - Installing mithereal/bonanza (dev-master 500aebe): Cloning 500aebe617 from cache Writing lock file Generating autoload files

I've tried clearing cache, dumping autoload, changing the folder names...

As noted in the title, this was working fine but recently the vendor package for `bonanza` changed from `"ecomlogic/bonanza-sdk":  "1.1.0.0"` to `"mithereal/bonanza":  "dev-master"` on packagist.

My old composer.json file worked fine to localize this vendor package into my vendorlocal package.. that looked like this:

    "require": {
            "ecomlogic/bonanza-sdk":  "1.1.0.0"
    . . . . 
    "repositories": [
        {
            "type": "path",
            "url": "src/vendorlocal/php-bonanza",
            "options": {
                "symlink": true
            }
        }
    ]

And this worked fine.. but for some reason with the new name change composer is having difficulties connecting our knowing the new name is in reference to my `vendorlocal` folder?

What's the missing link in my composer.json file for composer to know to symlink this package to a local folder instead of ignoring my `repositories` `"src/vendorlocal/mithereal/bonanza"` entry and installing it as a normal package?

**Comment by alcohol** [comment]
You need to make sure the right package name is used in the composer.json in your copy inside vendorlocal. It is difficult to really help you debug this because we cannot access your local files.

**Comment by bbruman** [comment]
> You need to make sure the right package name is used in the composer.json in your copy inside vendorlocal. It is difficult to really help you debug this because we cannot access your local files.

Just performed some tests, even with copying over the actual vendor package into my vendorlocal directory (and deleting the one from the vendor folder, and clearing cache, and updating composer again), it still  

`- Installing mithereal/bonanza (dev-master 500aebe): Cloning 500aebe617 from cache`

Clones from cache...

My composer information was already present in my original post.. as for my file structure, it is fairly typical I think and is correct as far as I can tell?  I'll of course minimize the files I have per the issue at hand :)

Starting at my Root Local File Directory...

> /
> src/vendorlocal/mithereal/bonanza/src/Bonanza/controllers
> vendor/mithereal/bonanza/src/Bonanza
> composer.json

I did add another folder for my modifications to the package (folder named `controllers`), but that shouldn't matter, should it? 

`require": { mithereal/bonanza":  "dev-master" }` 

along with 

```
  "repositories": [
    {
        "type": "path",
        "url": "src/vendorlocal/vantoozz/proxy-scraper",
        "options": {
            "symlink": true
        }
    }
```

Seems like it should be a sufficient match.  Is it in composer.json that it looks for this detection to symlink or is there something else not right?

**Comment by alcohol** [comment]
If you want to install `mithereal/bonanza` from a local repository, you need to make sure you have that local repository added as a path repository in your project `composer.json` (I see both `src/vendorlocal/mithereal/bonanza` and `src/vendorlocal/vantoozz/proxy-scraper` so I am a bit confused by that part).

You also need to make sure, that in the local copy, the composer.json in your master branch references this same package name inside of it.
