### ISSUE TITLE
Different Package Version for Development & Production in Composer

### ISSUE THREAD

**Issue by varunsridharan** [composer/composer#8206]
i am working on multiple composer packages and a application which dose requries all the packages that i develop.

I would like to know how i can have a package with multiple version

    stable version for production
    development / master version for local development

i tried following config but it din't work

```json
{
  "minimum-stability" : "dev",
  "require"           : {
    "varunsridharan/vsp-framework" : "^1.0",
    "wponion/wponion"              : "^1.0"
  },
  "require-dev"       : {
    "varunsridharan/vsp-framework" : "dev-master",
    "wponion/wponion"              : "dev-development"
  }
}
```

When i run composer install or composer install --no-dev i get the below output

```
Loading composer repositories with package information
Updating dependencies


  [Composer\DependencyResolver\SolverProblemsException]
  Problem 1
      - The requested package varunsridharan/vsp-framework ^1.0 exists as varunsridharan/vsp-framework[dev-master] but these are rejected by your constraint.
    Problem 2
      - The requested package wponion/wponion ^1.0 exists as wponion/wponion[dev-development] but these are rejected by your constraint.


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-author
itative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
```

**Comment by alcohol** [comment]
You cannot.

**Comment by varunsridharan** [comment]
@alcohol is there anyother way ? because i work on a lot of project which requires different version for production and different for development

**Comment by alcohol** [comment]
This is a workflow we do not support because it is bad practice.

**Comment by alcohol** [comment]
But you could have two different `composer.json` files and tell Composer which one to use through the [`COMPOSER`](https://getcomposer.org/doc/03-cli.md#composer) environment variable.

**Comment by varunsridharan** [comment]
@ alcohol i tried env variable but its not working.

**Comment by alcohol** [comment]
You will have to be more specific than "its not working". Please remember that I am not sitting next to you, and that I am not an all knowing entity. Provide as much information as you possibly can.

**Comment by varunsridharan** [comment]
@alcohol hey chill out man. i forgot to provide the information.
Here what i get when i run the cmd

`COMPOSER=composer-dev.json composer install`

![image](https://user-images.githubusercontent.com/1884287/60434470-ce92e580-9c24-11e9-8315-0b3a59393741.png)

```
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "=composer-dev.json" is not defined.       
```

**Comment by alcohol** [comment]
I don't know how Windows behaves with regards to environment variables and the `composer` executable bat file.

**Comment by alcohol** [comment]
@johnstevenson any idea?

**Comment by stof** [comment]
Windows does not support passing per-command env variables by prepending them. You have to set the env variable before running the command.

This is not something specific to the composer executable. This is how the Windows terminal works.

**Comment by johnstevenson** [comment]
@stof You beat me to it. cmd.exe treats `COMPOSER=composer-dev.json composer install` as:

- COMPOSER - the program to run
- `=composer-dev.json composer install` - the command-line.

So you need to do:
```
set COMPOSER=composer-dev.json
composer install
```
The environment variable is now set for the current terminal session.

**Comment by varunsridharan** [comment]
@ johnstevenson  this worked. and it seems i need to run `set COMPOSER=composer-dev.json` with file name changed for every time  need to install with a another file right ?

**Comment by alcohol** [comment]
Yes, that is what you need to do on Windows.
