### ISSUE TITLE
Run composer install from inline shell on remote machine azure devops

### ISSUE THREAD

**Issue by x1c0** [composer/composer#8209]
My `composer.json`:

```json
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "elasticsearch/elasticsearch": "^7.0",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0"
    },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^7.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Composer version: 1.8.4
PHP version: 7.2.19
PHP binary path: /usr/bin/php7.2
```

When I run this command:

```
sudo -u www-data composer diagnose
```

I get the following output:
![image](https://user-images.githubusercontent.com/2421483/60577188-2f363580-9d7f-11e9-8c02-0f93cac558e3.png)
And I expected this to happen:
No errors :)

Probably this is not a composer issue, the error output is not clear where is the problem is coming from.. If I ssh the machine and execute exactly the same command it works but on azure devops inline script I get this false errors, because composer does manage to install dependencies as far as I see, and the site does work.

I tried to run with composer install --verbose to see if I would have more detailed info but the output was the same..

Any ideas? Thanks in advance!

**Comment by stof** [comment]
Can you please fix the markup for your output ? I'm quite sure that you don't see the markdown for an image as output. You probably intended to render the image rather than rendering a codeblock containing this markup (you need to remove the indentation of the line to fix it).

**Comment by alcohol** [comment]
It looks more like 'azure devops' interprets output on `stderr` as if the application actually errors. But we output all debug/verbose information on `stderr`. Only the exit code of the Composer process should be used as an indication of whether or not it error'ed.

**Comment by stof** [comment]
Are you enabling `failOnStderr` in the config of your inline script ? That could be the issue.

Composer properly use stderr to report progress (as intended). Detecting failures must not be done by looking at whether something was output to stderr. The exit code is the way.

**Comment by stof** [comment]
@alcohol according to the Azure doc, it does not do it by default. But they provide an option for that.

**Comment by x1c0** [comment]
I have this option, but then if I unselect it, this means that for real errors I will miss the "breaking release" feature..
![image](https://user-images.githubusercontent.com/2421483/60578420-74f3fd80-9d81-11e9-9b11-273adb2f97ad.png)

**Comment by alcohol** [comment]
If you rely on this, then honestly, your release process is broken.

**Comment by alcohol** [comment]
You can mute Composer output completely if you absolutely need to "Fail on STDERR" because your other tools do not properly use exit codes. But I would rather suggest you use proper tooling. Exit codes are much more reliable than watching for output on stderr.

**Comment by x1c0** [comment]
Sorry I probably don't understand this, but stderr should not be used only for errors? what is the common practice?  Also I don't think I really understand what "Fail on STDERR" means..

**Comment by x1c0** [comment]
this is the current output unchecking that option:
![image](https://user-images.githubusercontent.com/2421483/60578845-33b01d80-9d82-11e9-978d-66a62c6a2ede.png)

**Comment by alcohol** [comment]
> but stderr should not be used only for errors?

Correct. `stderr` should be used for everything that is informational, verbose, errors, warnings, etc. `stdout` should be used for data that could be process or handled / piped into other programs.

> Also I don't think I really understand what "Fail on STDERR" means..

This means it will consider any output on `stderr` as a complete failure. This is very bad practice and generally you should always rely on exit codes of processes, not on output.

**Comment by alcohol** [comment]
https://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout provides some good information and rationale behind this choice.

**Comment by x1c0** [comment]
ah got it @alcohol thanks for explaining! that's what you mean by using proper tooling 😬 but i guess I have no other choice then using azure devops then :( 

Anyhow, thank you all for the super fast & awesome support!!

**Comment by alcohol** [comment]
> but i guess I have no other choice then using azure devops then :(

There is nothing wrong with using azure devops. Just don't use the "Fail on STDERR" feature. You should not need it. If Composer fails, you can rely on the exit code. Most of your other tooling probably also does this correctly.
