### ISSUE TITLE
Unable to disable packagist with `composer init`

### ISSUE THREAD

**Issue by Doqnach** [composer/composer#8210]
My `composer.json`:

```json
n/a
```

Output of `composer diagnose`:

```
[8.8MiB/0.00s] Checking composer.json: [9.3MiB/0.02s] WARNING
[9.3MiB/0.02s] No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
[9.3MiB/0.02s] Checking platform settings: [9.3MiB/0.02s] OK
[9.3MiB/0.02s] Checking git settings: [9.3MiB/0.03s] OK
[9.3MiB/0.03s] Checking http connectivity to packagist: [9.3MiB/0.08s] OK
[9.3MiB/0.08s] Checking https connectivity to packagist: [9.3MiB/0.21s] OK
[9.3MiB/0.21s] Checking github.com oauth access: [9.3MiB/0.67s] OK
[9.3MiB/0.67s] Checking disk free space: [9.3MiB/0.67s] OK
[9.3MiB/0.67s] Checking pubkeys: [9.3MiB/0.67s] 
[9.3MiB/0.67s] Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
[9.3MiB/0.67s] Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
[9.3MiB/0.67s] OK
[9.3MiB/0.67s] Checking composer version: [9.3MiB/0.73s] OK
[9.3MiB/0.73s] Composer version: 1.8.6
[9.4MiB/0.74s] PHP version: 7.3.4
[9.4MiB/0.74s] PHP binary path: /usr/local/bin/php
[9.4MiB/0.74s] Memory usage: 9.37MiB (peak: 9.44MiB), time: 0.74s
```

When I run this command:

```
composer init --name=foo --description=bar --stability=dev --type=library --license=proprietary --repository="{\"packagist\":false}" --repository="{\"type\":\"composer\",\"url\":\"https://my.private.repo/\"}"
```

I get the following output:

```                                                               
[UnexpectedValueException]                                     
Repository "0" ({"packagist":false}) must have a type defined  
```

And I expected this to happen:

A valid `composer.json` like:

```json
{
    "name": "foo",
    "description": "bar",
    "type": "library",
    "license": "proprietary",
    "require": {},
    "repositories": [
        {
            "packagist":false
        },
        {
            "type": "composer",
            "url": "https://my.private.repo/"
        }
    ],
    "minimum-stability": "dev"
}
```

Based on https://getcomposer.org/doc/03-cli.md#init and https://getcomposer.org/doc/04-schema.md#repositories I expect to be able to disable packagist during `composer init`, see https://getcomposer.org/schema.json#/properties/repositories/additionalProperties/oneOf[1].

**Comment by alcohol** [comment]
I don't think we support disabling packagist through the repository argument of the init command. Why do you need to disable packagist anyway? You simply need to provide the additional repository if that is where your project can be found.

**Comment by Doqnach** [comment]
We want to disable it since we run a Private Packagist (Enterprise) and want to get everything from there, including public packages. When disabling packagist we also notice a greatly lower memory footprint when requiring packages.

Since the docs say any value that is valid for the `repositories` key should be accepted, I would also expect the `{"packagist":false}` to be valid.

**Comment by alcohol** [comment]
There is special behaviour involved for `{"packagist":false}` which isn't taken into account by how the init command handles the repositories flag. Perhaps the documentation should reflect this. But in short, no you cannot use the flag to disable packagist as a repository.

**Comment by Doqnach** [comment]
And any chance of `composer init` and `composer create-project` taking into account that special behaviour for `{"packagist":false}`? Because in both cases I would love to not touch packagist at all. Either through `--repository` or some other argument (`--no-packagist`?).

**Comment by Doqnach** [comment]
This issue would warrent a "feature" label instead of "support"

**Comment by stof** [comment]
@Doqnach both commands would respect a setting coming from the global composer config.

**Comment by Doqnach** [comment]
But I don't want to disable packagist for my entire host system, only for this one (monorepo) project.
So when I do a `composer create-project` within the monorepo to create a new module, I want that command only to ignore packagist.

When working on a completely different project I am happy to use packagist.

**Comment by Seldaek** [comment]
@Doqnach fixed it for init, for create-project I think it should work if you define your private repo as the repo URL to use (e.g. `--repository=https://..`) as it only looks for the package in the given repo then, no need to disable the default packagist.org one

**Comment by Doqnach** [comment]
I will check for `create-project` and get back to you on this. Would you want it as a new issue if it doesn't work like you described (which I do not believe it does but have to verify)?

**Comment by Seldaek** [comment]
Sure rather create a new one but you can reference this one, please use `composer self-update --snapshot` to try with the latest dev build from master branch.
