### ISSUE TITLE
No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by GiacomoLaw** [composer/composer#8212]
Trying to install Composer on Windows using the .exe. I have tried disabling ipv6, using a proxy, disabling the firewall, but no luck

I use XAMPP.

```
The Composer installer script was not successful [exit code 1].

A proxy or firewall may be causing this error.

Script Output:
The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: No connection could be made because the target machine actively refused it.
```

How can I get composer installed?

Thanks

**Comment by alcohol** [comment]
Network issues are almost always (99.99%) on the user side. There is nothing we can do, except to tell you to investigate what is mis-configured in your network. Check firewalls, vpn software, proxies, etc. If you are in an office, ask your local admin for help.

**Comment by GiacomoLaw** [comment]
Done all that - tried using a proxy, tried using only ipv4/6, disabling firewalls, switching VPN services completely off, and yet no success.

**Comment by alcohol** [comment]
Okay. And what do you want us to do?

**Comment by GiacomoLaw** [comment]
Just wondering if anyone has a solution :)

**Comment by alcohol** [comment]
These kind of networking issues need to be resolved on your end. There simply is nothing we can do for you.

**Comment by GiacomoLaw** [comment]
Okay, thanks.

**Comment by farshidahmadianpin** [comment]
> Trying to install Composer on Windows using the .exe. I have tried disabling ipv6, using a proxy, disabling the firewall, but no luck
> 
> I use XAMPP.
> 
> ```
> The Composer installer script was not successful [exit code 1].
> 
> A proxy or firewall may be causing this error.
> 
> Script Output:
> The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: No connection could be made because the target machine actively refused it.
> ```
> 
> How can I get composer installed?
> 
> Thanks

hi can you guide me to solve this problem?
i have same error
