### ISSUE TITLE
Support polyfills for extensions

### ISSUE THREAD

**Issue by filips123** [composer/composer#8213]
It's currently not possible to install PHP extensions with Composer. This means that it is harder for users to use package that requires PHP extension and some (shared) hosts even don't support installing custom extensions.

However, some extensions also have some kind of pure PHP "polyfill" for them, but maybe with limited functionality or worst performance. Even if they have some limitations, it's better for users than nothing.

---

But it's currently hard to use that polyfills in packages. There are a few options for package maintainers what to do.

First is to include both extensions and polyfills in `require` section of `package.json`. Problem with it is that users will have to ignore platform requirements before installing (if they don't have an extension) and extension and polyfill may cause conflict.

Second is to only use the extension in `require` and polyfill in `suggest`. Users will again have to ignore platform requirements but polyfill will be "suggested" also for users with extension.

The third is to use polyfill in `require` and extension in `suggest`. This may also cause conflict if both extension and polyfill are installed.

---

Solution for this is to provide some kind of "conditional dependencies". This may be "include this dependency if the extension is not installed", "include this dependency if PHP version is lower/higher than" and "include this dependency if PHP function/class/constant is not defined".

I currently haven't think in what way would package maintainer provide that information, but it would be good if it would be supported.

There are also similar problems with supporting older PHP versions. There are also [polyfills for that](https://github.com/symfony/polyfill) so it should also be possible to use my suggestion for them.

**Comment by alcohol** [comment]
If a polyfill package exists, users should just require that instead of the extension it polyfills. If the extension that it polyfills is present, it simply won't be used.

Conditional requirements are far too complex to implement. We simply do not have the time and resources.
