### ISSUE TITLE
Composer integration with Snap to install platform reqs

### ISSUE THREAD

**Issue by luizkim** [composer/composer#8217]
Not a bug, but the idea for a new feature.

When installing some project with some platform requirements, the composer only warns that the package is not installed or is not in the correct version.

The idea is to use Snap to perform the installation. (https://snapcraft.io/)

This would make the project simpler to install with a tuion than is necessary to function properly.

**Comment by alcohol** [comment]
Similar ideas and implementations have been suggested in the past. We simply do not have the numbers and time to extend the scope of Composer by this much.
