### ISSUE TITLE
[Windows 10]Issuing a composer command in the terminal givesme a CLI has stopped working error

### ISSUE THREAD

**Issue by abrhambas01** [composer/composer#8219]
Why is it that every time I issue a 

$ composer

command in the terminal

[Window Title]
CLI

[Main Instruction]
CLI has stopped working

[Content]
Hang on while Windows reports the problem to Microsoft...

[Cancel]

And also this : 

![image](https://user-images.githubusercontent.com/12043306/61019963-9e8ad580-a3ce-11e9-8d91-d06899135c4f.png)

**Comment by alcohol** [comment]
Your guess is as good as ours. There is not much we can deduce from a screenshot of this dialog and no further information whatsoever.

**Comment by abrhambas01** [comment]
I don't know but maybe the restart works, all my commands are now ok. Node -v and composer commands give me a head 3 hours ago, but now it's back :D :D
