### ISSUE TITLE
Authentication required

### ISSUE THREAD

**Issue by arturslogins** [composer/composer#8220]
Hello 
When I installed the package this morning, I was prompted to log in.
Is there any information why this happened? 

Prefetching 20 packages =>
  - Downloading (5%)    Authentication required (dl.laravel-china.org):
      Username:

**Comment by alcohol** [comment]
`dl.laravel-china.org` is not maintained by us.

**Comment by arturslogins** [comment]
> `dl.laravel-china.org` is not maintained by us.

It's really interesting 
Do you have any idea why composer added "mirror" array to .lock file?
`
"mirrors": [
                    {
                        "url": "https://dl.laravel-china.org/%package%/%reference%.%type%",
                        "preferred": true
                    }
                ]
`

**Comment by alcohol** [comment]
That is not something Composer would do. You are probably using a plugin or script that does this.

**Comment by arturslogins** [comment]
> That is not something Composer would do. You are probably using a plugin or script that does this.

Hmm, 
Never used any script or plugin. 
From git history  I see that it has appeared after package update.
I'm using only "composer update" command

**Comment by alcohol** [comment]
> Never used any script or plugin.

I cannot take your word for this since you did not share the complete contents of your `composer.json` with us. Honestly, with the tiny amount of information you provided us, I am not sure what you expect us to help you with at all.

**Comment by arturslogins** [comment]
> > Never used any script or plugin.
> 
> I cannot take your word for this since you did not share the complete contents of your `composer.json` with us. Honestly, with the tiny amount of information you provided us, I am not sure what you expect us to help you with at all.

Any way, I found solutions.  Maybe someone has the same problem as me
There is two options: 
1. Delete lock file and run "composer install"
2. Manually go through composer lock file and remove "mirrors" object
