### ISSUE TITLE
Composer require on a bitbucket repo w/ oauth causes warning

### ISSUE THREAD

**Issue by rtek** [composer/composer#8224]
My `composer.json`:

```json
{
    "name": "rtek/composer",
  
    "require": {
    },
    "repositories": [{
        "type": "vcs",
        "url": "https://bitbucket.org/my/repo.git"
    }]
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.6
PHP version: 7.2.18
PHP binary path: C:\server\p7218\php.exe

```

When I run this command:

```
$ composer require my/repo
Using version ^0.1 for my/repo
./composer.json has been updated
Warning: You should avoid overwriting already defined auth settings for bitbucket.org.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files


$ composer require my/repo--no-update
Using version ^0.1 for my/repo
./composer.json has been updated
```

And I expected this to happen:

There should not be a warning when using oauth for bitbucket in the first case.

## Cause
* BaseIO loads the bitbucket oauth credentials from auth.json
* The require command uses the key/secret pair and swaps it for an x-auth-token/access token pair
* BaseIO instance is not reset 
* The following update command uses an initialized BaseIO
* auth.json is reloaded on top of the access token, causing the reror

## Fix
* There is a mismatch between how the oauth is stored and how its loaded if the token is not expired. If the token is not expired it should be used instead of key/secret.

I can do a PR for this, but can I have a recommendation on how to write a test case? Should i just test against `NullIO`?

**Comment by Seldaek** [comment]
Pushed a fix which I think should do the trick, but would be good if you can check after a `composer self-update --snapshot` as I don't have a repro case here. In case you still want to send a PR with a test for this, NullIO should be fine for tests, or BufferIO might be easier to check the output.
