### ISSUE TITLE
dump-autoload command wants to download https://flex.symfony.com/versions.json

### ISSUE THREAD

**Issue by RevisionTen** [composer/composer#8227]
I want to run `dump-autoload` on a production system with no outgoing internet access. When I run the command I get this message:

> The "https://flex.symfony.com/versions.json" file could not be downloaded: failed to open stream: Connection timed out
https://flex.symfony.com/versions.json could not be fully loaded, package information was loaded from the local cache and may be out of date

How can I prevent this?

**Comment by alcohol** [comment]
Include `--no-scripts`

**Comment by alcohol** [comment]
But you should not run Composer on a production system. You should create a production ready build artifact in your pipeline and release/deploy that instead.
