### ISSUE TITLE
Fix no permissions - use relative path if possible

### ISSUE THREAD

**Issue by mvorisek** [composer/composer#8237]
Consider the following file structure:
```
root@debian:/root/composertest# ls -lah
drwxr-xr-x  2 composer composer .
drwx------ 11 root     root      ..
```

and any composer operation started like:
```
sudo -u composer composer init --name test
```

the composer currently outputs:
```
  [ErrorException]
  file_put_contents(./composer.json): failed to open stream: Permission denied
```

it seems the PHP try to use a full path, consider the following example to better understand the permission issue:
```
root@debian:/root/composertest# sudo -u composer mkdir /root/composertest//test
mkdir: cannot create directory ‘/root/composertest//test’: Permission denied
```
vs
```
root@debian:/root/composertest# sudo -u composer mkdir test
(directory is created successfully, no error)
```

**Comment by Seldaek** [comment]
That seems to be a PHP limitation, file_put_contents even with a relative path fails to create the file. Also seems like kind of an edge case that's not really worth investing much time in fixing IMO.

**Comment by mvorisek** [comment]
@Seldaek reported as PHP bug: https://bugs.php.net/bug.php?id=78350
