### ISSUE TITLE
Composer checks out master branch instead of required dev-trunk 

### ISSUE THREAD

**Issue by ayeo** [composer/composer#8246]
When I try to use the library from a private repository using "trunk" branch Composer gets always the master branch. Indeed it checks out trunk branch as expected but at the end switches to the master. I guess [that line](https://github.com/composer/composer/blob/e022c073706769d0486de96de0f98719cd9950b5/src/Composer/Repository/VcsRepository.php#L252) is responsible for that behavior. I wonder what is the purpose of such condition? I dont really understand the warning message. I have solved my issue just by changing branch name but I am just curious :)

**Comment by Seldaek** [comment]
Right, trunk is assumed to only exist on subversion, and is therefore parsed the same as master.. Please don't use it on git :) Sorry it's just a restriction you have to live with.
