### ISSUE TITLE
Document v2 metadata format

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#8248]
Also we need to release the minification code as standalone lib to allow re-use by other implementors.

**Comment by Seldaek** [comment]
Docs added to https://github.com/composer/composer/blob/master/UPGRADE-2.0.md#for-composer-repository-implementors - still need to release mirroring code tho.

**Comment by Seldaek** [comment]
Mirroring code is at https://github.com/composer/mirror

**Comment by stof** [comment]
@Seldaek what about the minification code ?
