### ISSUE TITLE
Escaped slashes also confuse composer remove command

### ISSUE THREAD

**Issue by rgpublic** [composer/composer#8249]
In the changelog for 1.8.6 I found:

https://github.com/composer/composer/blob/master/CHANGELOG.md

"Fixed handling of backslash-escapes handling in composer.json when using the require command".

I couldnt find the corresponding issue for this and I might be wrong, but I think this also needs to be fixed for the remove command. If in composer.json the slash in a package string in the required section is escaped with a preceding backslash (e.g. written by PHP's json_encode if you don't use the JSON_UNESCAPED_SLASHES option) then the remove doesn't work.

**Comment by Seldaek** [comment]
The issue was https://github.com/composer/composer/issues/8131 which is unrelated to escaping slashes actually, but I'll have a look at the issue you describe.

**Comment by rgpublic** [comment]
@Seldaek That was *fast*. I think this was the shortest time I ever encountered between a bug report of mine and its solution in any open source project. Thanks a lot!
