### ISSUE TITLE
Allow path repositories to be relocated to their source location

### ISSUE THREAD

**Issue by greg-1-anderson** [composer/composer#8254]
**Problem / Motivation**

Drupal uses Composer to manage its dependencies, and employs composer/installers to ensure that internal dependencies are placed in their historic locations, because it is still a work-in-progress to allow modules, themes, drupal core and etc. to run from the `vendor` directory.

Furthermore, some Drupal sites use a community project, [drupal-composer/drupal-project](https://github.com/drupal-composer/drupal-project) to produce a Composer-friendly project, whereas other Drupal sites use a project layout that is more similar to the historic (Drupal 7 and earlier) project layout that is not Composer-friendly.

There is an initiative to make Drupal use of Composer a little more standard. Both layouts will be supported, and will be Composer-friendly. In order to achieve this, the project drupal/core (a subtree split from the monorepo drupal/drupal) is going to be installed as a path repository instead of being merged in via the wikimedia Composer Merge Plugin.

Using a path repository can result in problems if the source of the path repository is located in the same location that the repository should be installed to. See below for workarounds.

My `composer.json`:

```json
{
    "name": "drupal/drupal",
    "description": "Drupal is an open source content management platform powering millions of websites and applications.",
    "type": "project",
    "license": "GPL-2.0-or-later",
    "repositories": [
        {
            "type": "path",
            "url": "core",
            "options": {
                "symlink": true
            }
        }
    ],
    "require": {
        "composer/installers": "^1.0.24",
        "drupal/core": "self.version"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "preferred-install": "dist",
        "autoloader-suffix": "Drupal8"
    },
    "extra": {
        "installer-paths": {
            "core": ["type:drupal-core"]
        }
    }
}
```

Output of `composer diagnose`:

```
$ composer diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.6
PHP version: 7.3.5
PHP binary path: /usr/local/Cellar/php/7.3.5/bin/php
```

When I run this command:

```
composer install
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 108 installs, 0 updates, 0 removals
  - Installing composer/installers (v1.6.0): Loading from cache

... [more output]

  [RuntimeException]                                                                                                                                                                    
  Package drupal/core cannot install to ".../drupal-8.8.x/core" inside its source at ".../drupal-8.8.x/core"  
                                                                                                                                                                                        
install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

```

Note that if the value of the `symlink` option is set to `false`, then the output changes to:

```
$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 49 installs, 0 updates, 0 removals
  - Installing drupal/core (8.8.x-dev): Mirroring from core
```

... and Composer hangs attempting to copy `core` over `core`.

And I expected this to happen:

Composer should note that the source and destination path are the same, and make the symlink / mirror operation a no-op. Ideally, Composer would do the right thing regardless of the setting of the `symlink` option, but it would be acceptable if this or some new option had to be set to work in this configuration.

**Notes:**

This is different than #6085 in that the symlink is not inside the source, but is in the exact same location as the source.

In this configuration (with a `path` repository defined), the `remove` option should be a no-op. It is possible that, if the `path` repository definition is removed from the `composer.json` file, and the user then runs `composer remove drupal/core` or something like `composer update` that indirectly causes `drupal/core` to be removed while `vendor/installed.json` still points at the `core` directory, then Composer will delete the `core` directory (the source). Ideally, `vendor/installed.json` would also note that installed location is the source location so that this does not happen.

Using drupal/core as a path repository will only happen when doing development using the drupal/drupal monorepo. Most users will use the subtree split of drupal/core.

Once it is possible to [put modules in the vendor directory](https://www.drupal.org/project/drupal/issues/2701253), it will no longer be necessary to relocate drupal-core to its source location. It will probably take years to get there, though. Also, this feature (relocating a path repo to its source) might also be useful for other monorepo projects working toward better Composer integration.

**Workaround:**

Presently, the composer/installers data in the composer.json file is set up to relocate drupal-core to vendor/drupal/core. Note that this is the default location; however, composer/installers contains a rule to relocate drupal-core to core, so we cannot simply leave the drupal-core rule out.

The workaround behaves just fine, but folks do not like the `vendor/drupal/core` entry in the root composer.json file, and folks do not like the symlink that is created in the vendor/drupal directory.

**References:**

- [drupal/drupal#2912387](https://www.drupal.org/project/drupal/issues/2912387): Stop using wikimedia/composer-merge-plugin
- [drupal/drupal#2701253](https://www.drupal.org/project/drupal/issues/2701253): [META] Make it possible to put modules into the vendor directory
- [drupal/drupal#2002304](https://www.drupal.org/project/drupal/issues/2002304): [META] Improve Drupal's use of Composer

**Comment by Seldaek** [comment]
So first point is there seem to be a bug when symlinking is disabled, we should look into that. It should definitely error as well instead of getting stuck..

Second point, I wonder why you are trying to use a path repo at all here. I don't really understand what composer/installers is doing, you run composer install inside the `drupal/drupal` repo, and it contains the `core/` dir, but you also require `drupal/core`, so it gets installed in `vendor/drupal/core`, but the installer symlinks it to `core/`?

Ultimately the way I understand it you want a way to load a package that is already included in the source, much like `replace: drupal/core` would let you do, but using `replace` would require you to copy all the require/replace/.. from drupal/core to drupal/drupal, which I guess is a bit of a maintenance pain. 

So yes maybe we could make the path repo do a noop when a noop is requested instead of crashing, that sounds probably reasonable..

**Comment by Seldaek** [comment]
Re first point, I could not reproduce this, and from looking at the source as well, I can't see how symlink true or false would change anything as the `Package %s cannot install to "%s" inside its source at "%s"` error is thrown very early on..

I however did the change to noop when installing in exactly the same dir as the source is in.

**Comment by greg-1-anderson** [comment]
Great, thanks for fixing that!

To explain a bit more, the situation with drupal/drupal is a little odd. This all dates back to Drupal 8.0.0, when the core maintainers decided that they wanted to use Symfony + Composer, but did not want the end-user experience from the non-Composer days to change. As a result, folks download a pre-populated `vendor` directory with every Drupal tarball download.

Glossing over the implementation details, we are now in a position where we want end-users to start using "template projects" that look like an ordinary Composer project, i.e. no "path" repository, and the "core" directory installed from the drupal/core project, with composer/installers relocating it to the location at the document root where the existing code requires it. The path repository only comes into play for folks who clone the git repository and develop on the monorepo.

This situation is temporary; over time we will fix the legacy code to allow project development to happen without the path repository relocating back on top of itself. In the meantime, though, this fix / workaround in Composer will be very helpful.

**Comment by Seldaek** [comment]
Ok I see :) I'll try and release 1.9 soon with this included

**Comment by Seldaek** [comment]
It's out

**Comment by greg-1-anderson** [comment]
Thanks!
