### ISSUE TITLE
[debugged] HTTPS proxying fails under certain circumstances

### ISSUE THREAD

**Issue by matjon** [composer/composer#8255]
Hello,
When I set
```
export http_proxy=localhost:8080
export https_proxy=localhost:8080
```
`composer diagnose` runs correctly, but when I use default system-configured values of
```
export http_proxy=http://localhost:8080
export https_proxy=https://localhost:8080
```
`composer diagnose` fails with
```
Checking https connectivity to packagist: 
StreamContextFactory: setting $options['http']['proxy'] to ssl://localhost:8080
[Composer\Downloader\TransportException] The "https://repo.packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Failed to enable crypto
failed to open stream: operation failed
```
(I have added a debugging echo in StreamContextFactory.php ).
This error code is a well-known result of talking raw HTTPS to a proxy (which normally expects CONNECT commands). This probably means that OpenSSL did not use proxy to connect to the site (there is a forced redirection from port 443 to the proxy).

Setting
```
export HTTP_PROXY_REQUEST_FULLURI=false
export HTTPS_PROXY_REQUEST_FULLURI=false
```
does not have any effect.

I have debugged the issue somewhat. When I set proxy env variables with http/https prefixes, 
`$options['http']['proxy']` inside src/Composer/Util/StreamContextFactory.php is set to `ssl://localhost:8080`. When the env variables do not have these prefixes, this variable is set to `localhost:8080` and connection works correctly.

Relevant code is in https://github.com/composer/composer/blob/60f198c17d99728b0c1adb5b17e581fe274e34e8/src/Composer/Util/StreamContextFactory.php#L78-L84

My `composer.json`:
https://github.com/composer/composer/blob/master/composer.json
(I have tested this bug with official composer repository)

**I use OpenSSL 1.0.2g-1ubuntu4.15 (quite old) on Ubuntu 16.04.** This happens both on Ubuntu-provided PHP 7.0.33 and manually compiled 7.3.7, both on Composer git master and 
Composer 1.8.6.

Output of `./composer diagnose` (with a debugging `echo` added):
```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: 
StreamContextFactory: setting $options['http']['proxy'] to tcp://localhost:8080
OK
Checking https connectivity to packagist: 
StreamContextFactory: setting $options['http']['proxy'] to ssl://localhost:8080
[Composer\Downloader\TransportException] The "https://repo.packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Failed to enable crypto
failed to open stream: operation failed

StreamContextFactory: setting $options['http']['proxy'] to tcp://localhost:8080
Checking HTTP proxy: 
StreamContextFactory: setting $options['http']['proxy'] to ssl://localhost:8080
FAIL
[Composer\Downloader\TransportException] The "https://repo.packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Failed to enable crypto
failed to open stream: operation failed
Checking HTTP proxy support for request_fulluri: 
StreamContextFactory: setting $options['http']['proxy'] to tcp://localhost:8080
OK
Checking HTTPS proxy support for request_fulluri: 
StreamContextFactory: setting $options['http']['proxy'] to ssl://localhost:8080

StreamContextFactory: setting $options['http']['proxy'] to ssl://localhost:8080
Unable to assess the situation, maybe github is down (The "https://api.github.com/repos/Seldaek/jsonlint/zipball/1.0.0" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Failed to enable crypto
failed to open stream: operation failed)
Checking github.com rate limit: 
StreamContextFactory: setting $options['http']['proxy'] to ssl://localhost:8080
FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Failed to enable crypto
failed to open stream: operation failed
Checking disk free space: OK
Composer version: @package_version@
PHP version: 7.3.7
PHP binary path: /home/mateusz/Vista/bin/bin/php

```

**Comment by matjon** [comment]
This patch fixes the issue, but I do not know why:
```
diff --git a/src/Composer/Util/StreamContextFactory.php b/src/Composer/Util/StreamContextFactory.php
index da3e578..757d526 100644
--- a/src/Composer/Util/StreamContextFactory.php
+++ b/src/Composer/Util/StreamContextFactory.php
@@ -75,7 +75,7 @@ public static function getContext($url, array $defaultOptions = array(), array $
             }
 
             // http(s):// is not supported in proxy
-            $proxyURL = str_replace(array('http://', 'https://'), array('tcp://', 'ssl://'), $proxyURL);
+            $proxyURL = str_replace(array('http://', 'https://'), array('tcp://', 'tcp://'), $proxyURL);
 
             if (0 === strpos($proxyURL, 'ssl:') && !extension_loaded('openssl')) {
                 throw new \RuntimeException('You must enable the openssl extension to use a proxy over https');
```

**Comment by matjon** [comment]
This seems sensible, because:
https://www.php.net/manual/en/transports.inet.php
>    Note: If no transport is specified, tcp:// will be assumed.

**Comment by Seldaek** [comment]
Can you try on composer's 2.0 branch? I also don't see why your patch would fix anything.. it sounds to me like by doing that you are then not talking ssl to the proxy at all, and instead end up having unencrypted traffic to the proxy..

Could it be your proxy does not support https?

**Comment by matjon** [comment]
The traffic between the proxy and the client is in some sense unencrypted. The client should send a HTTP CONNECT request over plaintext, which would contain the hostname it wants to connect to. The proxy server would grant the request, open a TCP connection to this hostname and then tunnel all traffic between the client and the remote host. This mechanism is very simple. The proxy does not do any encryption processing and does not see the data (unless it is a MITM proxy, which is another story).

This is the ordinary, traditional way HTTP proxies work when it comes to HTTPS tunnelling. Therefore, every client has to be explicitly configured to use this proxy so that it would send the CONNECT request. Simple redirection (e.g. via iptables) does not work.

Therefore, `$options['http']['proxy']` should be set to `tcp://localhost:8080` so that this CONNECT request is sent over plaintext.
When

    $options['http']['proxy'] = "tls://localhost:8080"

PHP tries to negotiate a TLS connection to the proxy, which fails because the proxy does not expect this.

Please take look at this excerpt from PHP source code:

https://github.com/php/php-src/blob/41c4816157bc0201b30877591fb595686d665748/ext/standard/http_fopen_wrapper.c#L232-L246

**Comment by matjon** [comment]
I'll send a formal pull request in a while.

**Comment by matjon** [comment]
On the 2.0 branch: when I use 
```
export http_proxy=http://localhost:8080
export https_proxy=https://localhost:8080
```
composer fails with same error, when I set these env variables without http/https prefixes, I get:

```
mateusz@mateusz-ubuntu:~/open_source/composer/composer/bin$ ./composer diagnose
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking HTTP proxy: PHP Fatal error:  Uncaught Error: Call to undefined method Composer\Util\Http\Response::parseJson() in /home/mateusz/open_source/composer/composer/src/Composer/Command/DiagnoseCommand.php:257
Stack trace:
#0 /home/mateusz/open_source/composer/composer/src/Composer/Command/DiagnoseCommand.php(107): Composer\Command\DiagnoseCommand->checkHttpProxy()
#1 /home/mateusz/open_source/composer/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\DiagnoseCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
[...]
```
which seems to be another bug.

**Comment by Seldaek** [comment]
I'll look into the 2.0 branch bug (the branch is definitely not stable yet so not too unexpected), but regarding the other one I am not sure if that makes sense. It fixes for you but there are definitely lots of people that have been using proxies successfully until now, including with https URLs, so the question is why does it only break for you, and will your patch break it for others?

**Comment by matjon** [comment]
I have tested with squid (version 3.5.12) and get the same behaviour.
Installing squid or tinyproxy from repositories should be quick and easy in case You would like to try yourself. In case of squid, set

    http_proxy='http:\\localhost:3128'
    https_proxy='https:\\localhost:3128'

It is possible that PHP upgrade somehow caused this. I will test with PHP 5.

**Comment by matjon** [comment]
With PHP 5 same behaviour (I have compiled PHP 5.6.40 manually and I was testing Composer 1.8.6).

**Comment by johnstevenson** [comment]
> [Composer\Downloader\TransportException] The "https://repo.packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

This error means that the proxy server you are connecting to, `https://localhost:8080`, does not support connections over TLS.

If it did, then the following would happen after the initial connection:

* PHP would negotiate a TLS connection with the proxy server, failing if the certificates do not check out.    
* PHP would send a CONNECT request to the proxy. The proxy would then:
    * establish a connection to the origin-server
    * set up pipes so that PHP can communicate directly with the origin-server
* Ideally, PHP would now:
    * negotiate a TLS connection with the origin-server, failing if the certificates do not check out
    * send a GET request to the origin-server
    * receive content from the origin-server

but it doesn't actually support this and fails with: 
```
SSL/TLS already set-up for this stream
Failed to open stream: Cannot connect to HTTPS server through proxy
```

**Comment by Seldaek** [comment]
Closing this as I think Composer 2 will handle things much better and with clearer error messages.
