### ISSUE TITLE
when exec "composer require" vendor/composer/installed.json empty

### ISSUE THREAD

**Issue by juvin-git** [composer/composer#8256]
PHP:7.3.7
composer:1.8.4
os  : centos 7 run php docker php image

        i can use composer install laravel 5.5 ,but when i composer update or require command ,it wil be make vendor/composer/installed.json empty an throw a error say installed.json invalid . 
        This problem has been bothering me for several days, and I really hope to get help.

**Comment by Seldaek** [comment]
you'll need to provide more details here.. What exact command are you creating, from which state (empty folder? or existing one?) Please try to build a small reproduction case that we can try to run.
