### ISSUE TITLE
version 1.9.0.'s validate now returns failure exit code for deprecations

### ISSUE THREAD

**Issue by sfgeorge** [composer/composer#8260]
My `composer.json`:

```json
{
    "name":"cloudvox/crbn",
    "description":"The Real CARBON",
    "authors":[
        {
            "name":"Ifbyphone",
            "email":"example@example.com"
        }
    ],
    "license": "proprietary",
    "repositories": [
        {
            "type": "git",
            "url": "git@github.com:cloudvox/Ifbyphone.git"
        },
        {
            "type": "git",
            "url": "git@github.com:cloudvox/Rediska.git"
        },
        {
            "type": "git",
            "url": "git@github.com:cloudvox/php-oauth-client.git"
        },
        {
            "type": "git",
            "url": "git@github.com:cloudvox/php-domain-parser.git"
        },
        {
            "type": "git",
            "url": "git@github.com:cloudvox/phpbrake.git"
        },
        {
            "type": "git",
            "url": "git@github.com:cloudvox/QuickForm.git"
        },
        {
            "type": "git",
            "url": "git@github.com:cloudvox/zf1-future.git"
        }
    ],
    "config": {
        "platform": {
            "php": "5.6"
        }
    },
    "require": {
        "php": ">=5.3.3",
        "rediska/rediska": "@dev",
        "predis/predis": "1.1",
        "cloudvox/Ifbyphone":"0.6.*",
        "aws/aws-sdk-php": "2.8.7",
        "google/apiclient": "1.1.2",
        "asimlqt/php-google-spreadsheet-client": "2.3.4",
        "jeremykendall/php-domain-parser" : "3.0.1",
        "pusher/pusher-php-server": "2.2.1",
        "giggsey/libphonenumber-for-php": "7.2.1",
        "airbrake/phpbrake": "@dev",
        "firebase/php-jwt": "^5.0",
        "microsoft/bingads" : "v0.11.12.7",
        "stevenmaguire/oauth2-salesforce": "^2.0",
        "phpoffice/phpspreadsheet": "1.5.2",
        "smarty/smarty": "2.6.31",
        "cloudvox/quickform": "@dev",
        "shardj/zf1-future": "dev-develop",
        "pear/pear": "^1.10",
        "html2text/html2text": "^4.2",
        "pear/mail": "^1.4",
        "pear/mail_mime": "^1.10",
        "react/child-process": "^0.6.1",
        "react/event-loop": "^1.1"
    },
    "require-dev": {
        "fzaninotto/faker": "^1.5",
        "nelmio/alice": "^1.7",
        "phpunit/phpunit": "^5.7",
        "phpunit/dbunit": "^1.4",
        "mockery/mockery": "^1.2",
        "johnkary/phpunit-speedtrap": "*"
    },
    "autoload": {
        "psr-0": { "Cron\\": ["./library"], "Utility\\": ["./library"] }
    },
    "autoload-dev": {
        "psr-0": { "Cron\\": ["./library","./tests/library", "./tests"], "Utility\\": ["./library","./tests/library"], "TestHelpers\\": ["./tests/helpers"], "Portal\\": ["./tests"] }
    }
}
```

Output of `composer diagnose`:

```
Deprecation warning: require.cloudvox/Ifbyphone is invalid, it should not contain uppercase characters. Please use cloudvox/ifbyphone instead. Make sure you fix this as Composer 2.0 will error.
Checking composer.json: WARNING
require.rediska/rediska : unbound version constraints (@dev) should be avoided
require.predis/predis : exact version constraints (1.1) should be avoided if the package follows semantic versioning
Deprecation warning: require.cloudvox/Ifbyphone is invalid, it should not contain uppercase characters. Please use cloudvox/ifbyphone instead. Make sure you fix this as Composer 2.0 will error.
require.aws/aws-sdk-php : exact version constraints (2.8.7) should be avoided if the package follows semantic versioning
require.google/apiclient : exact version constraints (1.1.2) should be avoided if the package follows semantic versioning
require.asimlqt/php-google-spreadsheet-client : exact version constraints (2.3.4) should be avoided if the package follows semantic versioning
require.jeremykendall/php-domain-parser : exact version constraints (3.0.1) should be avoided if the package follows semantic versioning
require.pusher/pusher-php-server : exact version constraints (2.2.1) should be avoided if the package follows semantic versioning
require.giggsey/libphonenumber-for-php : exact version constraints (7.2.1) should be avoided if the package follows semantic versioning
require.airbrake/phpbrake : unbound version constraints (@dev) should be avoided
require.phpoffice/phpspreadsheet : exact version constraints (1.5.2) should be avoided if the package follows semantic versioning
require.smarty/smarty : exact version constraints (2.6.31) should be avoided if the package follows semantic versioning
require.cloudvox/quickform : unbound version constraints (@dev) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.9.0
PHP version: 5.6 - Package overridden via config.platform (actual: 7.2.20)
PHP binary path: /usr/local/Cellar/php@7.2/7.2.20/bin/php
```

When I run this command:

```
./composer.phar self-update 1.9.0
./composer.phar validate --no-check-publish --no-check-all --strict
echo EXIT CODE $?
```

I get the following output:

> Deprecation warning: require.cloudvox/Ifbyphone is invalid, it should not contain uppercase characters. Please use cloudvox/ifbyphone instead. Make sure you fix this as Composer 2.0 will error.
> Deprecation warning: require.cloudvox/Ifbyphone is invalid, it should not contain uppercase characters. Please use cloudvox/ifbyphone instead. Make sure you fix this as Composer 2.0 will error.
> ./composer.json is valid, but with a few warnings
> See https://getcomposer.org/doc/04-schema.md for details on the schema
> Deprecation warning: require.cloudvox/Ifbyphone is invalid, it should not contain uppercase characters. Please use cloudvox/ifbyphone instead. Make sure you fix this as Composer 2.0 will error.
> ### EXIT CODE 1

And I expected this to happen:

> Deprecation warning: require.cloudvox/Ifbyphone is invalid, it should not contain uppercase characters. Please use cloudvox/ifbyphone instead. Make sure you fix this as Composer 2.0 will error.
> Deprecation warning: require.cloudvox/Ifbyphone is invalid, it should not contain uppercase characters. Please use cloudvox/ifbyphone instead. Make sure you fix this as Composer 2.0 will error.
> ./composer.json is valid, but with a few warnings
> See https://getcomposer.org/doc/04-schema.md for details on the schema
> Deprecation warning: require.cloudvox/Ifbyphone is invalid, it should not contain uppercase characters. Please use cloudvox/ifbyphone instead. Make sure you fix this as Composer 2.0 will error.
> ### EXIT CODE 0

**Comment by Seldaek** [comment]
Yes this change was on purpose see https://github.com/composer/composer/pull/8013 - you are using --strict which is great IMO but then it also means you have to follow the warnings strictly. It's a simple update of the require line to lowercase the package name.

**Comment by sfgeorge** [comment]
I agree that there should be a way to discern validation errors from deprecation notices - but there are backwards-compatible ways to do that (like adding a new --fail-on-notices flag that causes deprecation notices to return one non-zero exit code, and errors to return another).

To "deprecate" something is to put on notice that it is not yet broken, but will be soon.

And to follow Semantic Versioning is to say that features won't be broken until the next major release.

This change breaks our existing CI builds without advancing the major version of composer, which violates SemVer.

We can disable our composer validate step entirely for now, until we've renamed the package.  But by all the deprecation notices informed us thus far... that shouldn't have been necessary until 2.0.

**Comment by Seldaek** [comment]
Another way to look at it is that thanks to this you got a hard warning now
in a way that's easy to skip, before you get a hard fail in v2.. but yes I
can see it's slightly disturbing your process, sorry about that. 100% bc is
hard with complex software and many users.

**Comment by sfgeorge** [comment]
> 100% bc is hard with complex software and many users.

That's a very fair point.  This stuff ain't easy at this level.  Thank you.
