### ISSUE TITLE
Pass the path with scripts.

### ISSUE THREAD

**Issue by YuK1Game** [composer/composer#8261]
I want to create a package that zips a project with a command.

However, I do not know how to refer to the root of the project from the package added by composer require.

Can you do it either way?

Pass project root path from composer.json script of project.

Get project root path from within package.

```composer.json
{
    "scripts": {
        "deploy": [
            "vendor/bin/zip <!-- Here's your own absolute path variable -->"
        ]
    }
}
```

Relative path from within the project is impossible.

Local packages do not exist under vendor.

thanks.

**Comment by Seldaek** [comment]
The current working directory should be the path of the root composer.json, which is what you want I think?
