### ISSUE TITLE
Could not find package * at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

### ISSUE THREAD

**Issue by ask664** [composer/composer#8264]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ask664/dd-trace-for-tracing 1.7.0 -> satisfiable by ask664/dd-trace-for-tracing[1.7.0].
    - ask664/dd-trace-for-tracing 1.7.0 requires mvc-php/framework dev-master -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by xabbuh** [comment]
Same as #8258?

**Comment by ask664** [comment]
nope 
this is on public packagist link is here - https://packagist.org/packages/ask664/dd-trace-for-tracing

**Comment by xabbuh** [comment]
But the `mvc-php/framework` package isn't listed on packagist.org.

**Comment by ask664** [comment]
i didn't get your point

**Comment by xabbuh** [comment]
The package `mvc-php/framework` is not found and I also do not see it on packagist.org. So my assumption is that this is somehow related to your private Packagist.

**Comment by ask664** [comment]
I already share the link.
please check this link - https://packagist.org/packages/ask664/dd-trace-for-tracing

**Comment by xabbuh** [comment]
That link points to the package `ask664/dd-trace-for-tracing`. But I am talking about `mvc-php/framework` which is a dependency of the former.

**Comment by alcohol** [comment]
```
- ask664/dd-trace-for-tracing 1.7.0 requires mvc-php/framework dev-master -> no matching package found.
```
