### ISSUE TITLE
Show which package includes a problematic package

### ISSUE THREAD

**Issue by burzum** [composer/composer#8267]
So I'm getting this error message which is fine so far.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for prooph/event-store-http-client dev-master -> satisfiable by prooph/event-store-http-client[dev-master].
    - Conclusion: remove php-http/httplug v1.1.0
    - Conclusion: don't install php-http/httplug v1.1.0
```

My only issue is that we have lot's of dependencies and httplug is not one of ours but a child dependency of one of the packages we use... It would be awesome if this error message would indent a list similar to `composer show --tree` of the packages, basically the path in the tree, that leads to the package causing the issue.

**Comment by Seldaek** [comment]
You can use `composer why php-http/httplug`
