### ISSUE TITLE
solver does not handle virtual package requirements as expected

### ISSUE THREAD

**Issue by alcohol** [composer/composer#8269]
Given:
- a root project from scratch,
- package `foo/a` depends on virtual package `virtual/package`,
- package `foo/b` provides `virtual/package`.

An installation request for only `foo/a` will fail because no explicit implementation for `virtual/package` is provided.

An installation request for `foo/a` and `foo/b` will succeed.

However, subsequently removing the requirement on `foo/b` currently yields no changes in the vendor directory because the solver uses `installed.json` as one the available repository sources. While there is no longer a direct requirement for `foo/b` anymore, indirectly it is still required due to the virtual package requirement of `foo/a`, and because it is installed, the solver is satisfied.

Ideally it should be treated as uninstalled or missing and would trigger an error similar to the very first scenario.

Related: https://github.com/composer/composer/issues/8263#issuecomment-519459829

**Comment by Seldaek** [comment]
Fixed already by current 2.0 behavior
