### ISSUE TITLE
Weird solving behavior on `minimum-stability`.

### ISSUE THREAD

**Issue by chez14** [composer/composer#8270]
My `composer.json`:

```json
{
    "name": "chez14/kissanime-notifier",
    "description": "Kissanime notifier",
    "type": "project",
    "license": "LGPL-3.0-or-later",
    "authors": [
        {
            "name": "Chris",
            "homepage": "https://christianto.net",
            "email": "chris@christianto.net",
            "role": "Developer"
        }
    ],
    "minimum-stability": "beta",
    "require": {
        "bcosca/fatfree-core": "^3.6",
        "spatie/array-to-xml": "^2.8",
        "ikkez/f3-cortex": "^1.5",
        "chez14/f3-ilgar": "v1.0.0.1",
        "kyranrana/cloudflare-bypass": "^2.0",
        "guzzlehttp/guzzle": "^6.3",
        "xfra35/f3-cron": "^1.2"
    },
    "config": {
        "vendor-dir": "vendor"
    },
    "scripts": {
        "start":"./start_php_dev_server.sh"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
require.chez14/f3-ilgar : exact version constraints (v1.0.0.1) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.9.0
PHP version: 7.3.7
PHP binary path: /usr/bin/php7.3
```

When I run this command:

```
composer require monolog/monolog
```

I get the following output:

```
Using version ^2.0@beta for monolog/monolog
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - chez14/f3-ilgar v1.0.0.1 requires monolog/monolog ^1.23 -> satisfiable by monolog/monolog[1.23.0, 1.24.0, 1.x-dev] but these conflict with your requirements or minimum-stability.
    - chez14/f3-ilgar v1.0.0.1 requires monolog/monolog ^1.23 -> satisfiable by monolog/monolog[1.23.0, 1.24.0, 1.x-dev] but these conflict with your requirements or minimum-stability.
    - chez14/f3-ilgar v1.0.0.1 requires monolog/monolog ^1.23 -> satisfiable by monolog/monolog[1.23.0, 1.24.0, 1.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for chez14/f3-ilgar v1.0.0.1 -> satisfiable by chez14/f3-ilgar[v1.0.0.1].


Installation failed, reverting ./composer.json to its original content.
```

And I expected this to happen:
It will install Monolog v1.23 or Monolog v1.24 because:
- `f3-ilgar` need **at least** `stable` `minimum-stability`, so this project's `minimum-stability` can be ignored (because `beta` is lower than `stable`).
- `f3-ilgar` **at least** asked for stable v1.23, so we can require v1.23 or above (`^1.23`).

Thank you.

**Comment by alcohol** [comment]
> * `f3-ilgar` need **at least** `stable` `minimum-stability`, so this project's `minimum-stability` can be ignored (because `beta` is lower than `stable`).

Incorrect, Composer does not care about what minimum stability a dependency declares because it only reads this property from the root composer.json as specified in the [documentation](https://getcomposer.org/doc/04-schema.md#minimum-stability).

As to why the `require` command decided on using `^2.0@beta` as a constraint (it does this using some magic since you did not specify a constraint yourself), I am not entirely sure. It should be able to tell with the current set of requirements that `chez14/f3-ilgar` requires `^1.23`. @Seldaek any idea here?

**Comment by Seldaek** [comment]
The problem is your minimum-stability is beta, so when you require monolog without version it decides to use the latest beta available for 2.0, as this fits your minimum-stability, but it conflicts with your requirement's requirements, so it then fails to resolve. You need to explicitly do it e.g. `composer require monolog/monolog:^1.20` will fix it.

**Comment by chez14** [comment]
Oh so i have to do it manually? Shouldn't that be resolved automatically by Composer? I'm genuinely confused @.@ Sorry for the troubles, also thanks for the support.

**Comment by Seldaek** [comment]
If you explicitly require `monolog/monolog:*` for example then it should figure out the right version yes, but when using require without constraint it tries to guess what the best constraint would be and that's mostly taking the highest version available, not really looking at your entire deps

**Comment by alcohol** [comment]
@Seldaek are you sure the pool the version selector gets doesn't take into account the current requirements? I remember we talked about this once before and I thought you said something contrary to what you are saying now. I could be mistaken though.

https://github.com/composer/composer/blob/bfba228b5a232bcb9e4bb7941f0a0aaa37bab117/src/Composer/Command/InitCommand.php#L709-L717

**Comment by Seldaek** [comment]
Afaik it only takes into account the php version in use, not other deps

**Comment by alcohol** [comment]
Yes you are entirely correct, I found the older comment and that is what you said then too :-)

**Comment by chez14** [comment]
Noted very well. I'll use `minimum-stability` only for my `project` project type. Thank you so much for the explanation. Have a good day.
