### ISSUE TITLE
Composer installs new dependencies when running remove

### ISSUE THREAD

**Issue by idontusenumbers** [composer/composer#8273]
Composer seems to install packages when executing `composer remove`

Composer version 1.9.0 2019-08-02 20:55:32

Steps to reproduce:
1. Add `packageB` to composer `require`
2. Execute `composer remove packageA`

Expected results:
`packageA` is removed and `packageB` remains not-installed

Actual results:
`packageA` is removed and `packageB` is installed

**Comment by alcohol** [comment]
Your expectations are wrong.

`composer remove` is the equivalent of updating the `require` section in your composer.json and then running `composer update`. Hence it takes into account the package you added as well in your scenario.

**Comment by idontusenumbers** [comment]
That's not at all my expectations based on the names of the commands.

It's also not at all what the composer documentation says what it prints it out.

```
remove               Removes a package from the require or require-dev.
update               Upgrades your dependencies to the latest version according to composer.json, and updates the composer.lock file.
```

**Comment by alcohol** [comment]
Understandable when you're new to using Composer. But that is how dependency solving works. There is no simple "remove this package". You remove a requirement and you resolve the new set of dependencies entirely, since removing a requirement (which has requirements by itself) can have a large impact.

**Comment by idontusenumbers** [comment]
Maybe you misunderstand. My complaint isn't that composer is behaving in a way that was not the way it was intended. My complaint is that composer is behaving in a way that contrary to what the user should expect given the terminology used and contrary to how the documentation says it will behave.

I can understand how frustrating it would be for composer to change the way it behaves after numerous users get used to this bad behavior.

At the very very very least the documentation should be fixed.

Fixing the actual behavior wouldn't be the first time a project did a mea culpa and changed the behavior to better match expectations.

**Comment by alcohol** [comment]
The behaviour cannot be changed as your interpretation of it is simply not how dependency solving works. I think the documentation is good enough. You're welcome to submit a pull request if you feel it could be better.

**Comment by idontusenumbers** [comment]
It feels like you closed the issue because the program works as you know it to work, but that too has nothing to do with the issue.

The behavior is not linked to my interpretation nor is my interpretation linked to the behavior.

Both my interpretation and your interpretation of how dependency solving works is irrelevant to this discussion. The bug is that the command itself and documentation about the command both differ from the implementation.

**Comment by alcohol** [comment]
> The bug is that the command itself and documentation about the command both differ from the implementation.

Again, that depends on how one interprets the command and documentation.

You're free to submit a pull request and we will take it into consideration. But considering it has been like this for several years and you are the first user to raise this issue, I think it is safe to say that up until now, the description and documentation has been adequate to say the least.

**Comment by idontusenumbers** [comment]
> remove               Removes a package from the require or require-dev.
What part of the word remove, that description, or the dictionary definition of remove are you interpreting to mean 'finds not-yet-installed packages, connects to internet server, downloads packages, and installs packages'?

**Comment by alcohol** [comment]
```
composer remove --help
Usage:
  remove [options] [--] <packages> (<packages>)...

Arguments:
  packages                           Packages that should be removed.

Options:
      --dev                          Removes a package from the require-dev section.
      --no-progress                  Do not output download progress.
      --no-update                    Disables the automatic update of the dependencies.
      --no-scripts                   Skips the execution of all scripts defined in composer.json file.
      --update-no-dev                Run the dependency update with the --no-dev option.
      --update-with-dependencies     Allows inherited dependencies to be updated with explicit dependencies. (Deprecrated, is now default behavior)
      --no-update-with-dependencies  Does not allow inherited dependencies to be updated with explicit dependencies.
      --ignore-platform-reqs         Ignore platform requirements (php & ext- packages).
  -o, --optimize-autoloader          Optimize autoloader during autoloader dump
  -a, --classmap-authoritative       Autoload classes from the classmap only. Implicitly enables `--optimize-autoloader`.
      --apcu-autoloader              Use APCu to cache found/not-found classes.
  -h, --help                         Display this help message
  -q, --quiet                        Do not output any message
  -V, --version                      Display this application version
      --ansi                         Force ANSI output
      --no-ansi                      Disable ANSI output
  -n, --no-interaction               Do not ask any interactive question
      --profile                      Display timing and memory usage information
      --no-plugins                   Whether to disable plugins.
  -d, --working-dir=WORKING-DIR      If specified, use the given directory as working directory.
  -v|vv|vvv, --verbose               Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  The remove command removes a package from the current
  list of installed packages
  
  php composer.phar remove
  
  Read more at https://getcomposer.org/doc/03-cli.md#remove
```

The command updates your composer.json and then runs the update process to resolve the new set of dependencies. If you do not want that, pass the `--no-updates` flag as described in the documentation that you so painstakingly want to cling to word for word.
