### ISSUE TITLE
Composer 1.9.0 treats hosts with port numbers differently from 1.8.6 for authentication

### ISSUE THREAD

**Issue by lpd-au** [composer/composer#8274]
Consider the following `auth.json` file:

```json
{
    "http-basic": {
        "artifacts.myhost.local": {
            "username": "Lpd",
            "password": "password"
        }
    }
}
```

Using Composer **1.8.6**, this authenticates for all URLs on that domain such as:

1. `https://artifacts.myhost.local/api/composer/inno-composer`
2. `https://artifacts.myhost.local:443/api/composer/inno-composer/vcs-dists/zip/guzzle/guzzle/407b0cb880ace85c9b63c5f9551db498cb2d50ba`

However, using Composer **1.9.0**, URLs with ports are treated as separate hosts. This means the second URL above would not authenticate, and instead requires an auth file like so:

```json
{
    "http-basic": {
        "artifacts.myhost.local": {
            "username": "Lpd",
            "password": "password"
        },
        "artifacts.myhost.local:443": {
            "username": "Lpd",
            "password": "password"
        }
    }
}
```

This is a breaking change for `--no-interaction` commands (eg `./composer.phar install --prefer-dist --no-interaction`) and not documented in the changelog.

**Comment by Seldaek** [comment]
Sorry didn't realize this would affect such artifact repos, will add to the changelog but that's all I can do I am afraid, the previous behavior was completely broken in some conditions so we fixed that and while I tried to keep BC as much as possible I guess the artifact repos pointing to custom port URLs suffered...

**Comment by lpd-au** [comment]
Could you please also add some logging to the `-vvvv` output about what exact host is being searched for in `auth.json`, and whether it could be found? This drove us crazy with no hints about what was going on :)

**Comment by Seldaek** [comment]
Ah I guess it did not prompt because you had --no-interaction?

**Comment by Seldaek** [comment]
From what I see in the code in that case it should error with `                    $message = "The '" . $this->fileUrl . "' URL required authentication.\nYou must be using the interactive console to authenticate";
` is that what you saw?

**Comment by lpd-au** [comment]
Exactly! It would have helped us debug this alot faster if we saw more like:
```
Loading config file /var/lib/jenkins/.composer/auth.json
Loaded credentials for hosts [artifacts.myhost.local]
...
Credentials for host artifacts.myhost.local:443 not found, prompting.
The 'https://artifacts.myhost.local:443/api/composer/inno-composer/vcs-dists/zip/myclabs/DeepCopy/007c053ae6f31bba39dfa19a7726f56e9763bbea' URL required authentication.
You must be using the interactive console to authenticate
```
Instead of just:
```
Loading config file /var/lib/jenkins/.composer/auth.json
The 'https://artifacts.myhost.local:443/api/composer/inno-composer/vcs-dists/zip/myclabs/DeepCopy/007c053ae6f31bba39dfa19a7726f56e9763bbea' URL required authentication.
You must be using the interactive console to authenticate
```
