### ISSUE TITLE
Composer could not delete package files from machine

### ISSUE THREAD

**Issue by PatrickPiroth** [composer/composer#8278]
I am creating a new TYPO3 project from scretch with docker toolbox and ddev. I try to execute ddev composer create project typo3/cms. Composer starts to download the latest T3-version. The first package installation fails and composer tries to removing the package with following error:

```json
[RuntimeException]
Could not delete /var/www/html/.tmp_ddev_composer_create_uKKXAI/vendor/typo3/class-alias-loader/tests/Unit:
```

Same Issue if i try to setup with a vagrant box. 

The permissions should be okay, if i ssh into the machines, i can delete the files/folder with default user.

**Comment by alcohol** [comment]
Missing a verbose stack trace.
