### ISSUE TITLE
interactive dependencies definition

### ISSUE THREAD

**Issue by hubroot** [composer/composer#8280]
Search for a package: testrepo
Found 15 packages matching test repo
[0] test/repo
...

Enter package # to add, or the complete package name if it is not listed: 0

Search for a package: testrepo
Found 15 packages matching test repo
[0] test/repo
...

i think the scenario shouldn't show the same results as test/repo has been chosen before.

**Comment by alcohol** [comment]
So you want to filter out current requirements?

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/pull/8372
