### ISSUE TITLE
allow_url_fopen issue

### ISSUE THREAD

**Issue by qcybb** [composer/composer#8282]
I do not want to enable "allow_url_fopen" globally in my php.ini file as it's a security risk.

Instead, I added it to my vhost so it's only enable for one domain :

> <Directory "/usr/www/example.com/httpdocs/">
>     php_admin_value allow_url_fopen On
> <\/Directory>

As you can see in phpInfo, "allow_url_fopen" is enabled (https://i.imgur.com/UtUIhJG.png)

However, composer still complains that "allow_url_fopen" is still not enabled and only works when I add it to my php.ini file.

Is there any way around this?

**Comment by alcohol** [comment]
You can add it to the cli specific php.ini which is not used by apache, on most distros that is `php-cli.ini`.
