### ISSUE TITLE
Any chance of a 'purge' command for non-required packages?

### ISSUE THREAD

**Issue by exteon** [composer/composer#8283]
We would really need a `remove`-like kind of function that removes any packages that are no longer required in composer.json; something like passing `composer show` through `composer why`, filtering empty entries and passing forward to `composer remove`. This would have the effect of removing useless data and files in `vendor`, `composer.lock` and any other locations piled up by plugins.

The reason is that we are removing entries form `composer.json` without going through the `composer` CLI (see below why), and in my understanding it's supposed to work, editing the json file externally and then managing state through the CLI command.

We can't use the `composer update` command because that will update all versions and we don't want to do that, we only want to remove the dead dependencies from the source tree and lock file and this happens when everything is already tested with the current versions in place.

**Background:** 
Our `composer.json` files are managed using an external versioning/composition tool that doesn't run through the `composer` CLI, but generates the json files so it does not have a backlog of `composer remove` commands that could be replicated to update state. We also can't do a diff on the `json` files' `require` section because we are also using the `wikimedia/composer-merge-plugin` to syndicate the composition of a number of `composer.json` files, so the only way we get some access to the merged list of requirements is via the output of `composer show`.

**Current workarounds until a better way:**
For anyone having the same problem, at this point we are implementing parsing the `composer show` output, to feed it through `composer why`, select entries and feed through `composer remove`. The challenges of this implementation are that there is no lexically-structured output for `composer show` - i.e. no `--format=json` or its likes, also impossibility to turn off warning messages (`-q` turns off output completely, even for data query commands - quite peculiar). It is also excruciantingly slow.

**Relevance**
Adding these to establish relevance:
https://stackoverflow.com/questions/27944795/composer-remove-a-package-clean-up-dependencies-dont-update-other-packages/37715903#37715903
https://stackoverflow.com/questions/57559821/how-to-purge-composer-project-of-unused-packages?noredirect=1#comment101588204_57559821

At least 40-something people seem interested.

**Comment by milescook** [comment]
Something I've been wanting a while is the option to get rid of the vendor directory completely and start fresh. Bad installs due to connectivity or force exiting composer leaves a degraded vendor directory. Having some directory issues which I'll look at tomorrow but branch is here:
https://github.com/milescook/composer/tree/_8283

**Comment by exteon** [comment]
@milescook well, it's not just a question of the `vendor` directory, since various packages can slice and dice files and manipulate state, so they need to be rolled back in a consistent manner. My problem is more of just determining unneeded packages and rolling them back quietly without affecting anything else. This makes sense since it seems `update <packagename>` seems to do just that, if the package is not required anymore it just sacks it. So knowing which package is dead, it's easy. The missing park is actually finding those packages which are not required anymore.

**Comment by alcohol** [comment]
> Something I've been wanting a while is the option to get rid of the vendor directory completely and start fresh. 

@milescook not sure I understand. Wouldn't `rm -rf vendor/ composer.lock` achieve exactly this?

@exteon sounds to me like basically you just need to `rm -rf vendor/` and then install from the lock file. Or are you implying that the lock file contains dependencies that are not actually required by any of your composer.json files or the merged result of them?

**Comment by exteon** [comment]
@alcohol 
1) `composer` does support plugins since forever and a day, which can splice files around, manage state, even handle DB data. See for instance symfony bundles. Packages need to be removed in a semantic way to preserve project state, not just deleted at random.
2) If they were ever installed (and they were), they are present in the lock file. Also, removing everything to reinstall everything can even take minutes (see my point about plugins above).
3) A simple feature like listing packages that `show` but have no `why` (and maybe cleaning them up as a courtesy, similar to `update <unused-package>`) seems much more convenient here than finding external workarounds that can mean trashing a perfectly consistent project state.

**Comment by milescook** [comment]
@exteon ahh a slightly different use case to me then. Makes sense.

@alcohol yes you could and script that, but I'd personally prefer to delegate this task to composer. Seems more future proof to me.

**Comment by Seldaek** [comment]
Tagging for 2.0 as it should be easier to do then.

**Comment by exteon** [comment]
Well, a `--unused` mode would be also useful for listing. So yes, it would make sense intuitively that a same switch would feed the same list to `update`, `remove`. Separate commands (like `outdated` would be just aliases for convenience.

Note: documentation for `remove` and `update` in context of remove with respect to `--update-with-dependencies` is very skimpy for my taste. For example, if I remove package `X` which was locking dependency `Y` at version 1.0.0, by removing `X` with `--update-with-dependencies` will `Y` get updated to the most recent resolvable version? Seems not ATM, but it's impossible to tell from the documentation what the intent is on this matter (seems like everything on package removal has a bit of an "undefined" semantical structure).

**Comment by alcohol** [comment]
> but the semantic meaning would be absolutely clear

From a verb perspective maybe. But not from a dependency resolving perspective.

**Comment by exteon** [comment]
Well, in my mind and correct me if I'm wrong, removing edges/nodes from the dependency graph does  not require any subsequent resolving, pruning a consistent dependency graph always results in a consistent dependency graph (albeit possibly disconnected).

**Comment by alcohol** [comment]
No I am saying that if you run `remove X`, merely removing `X` as an installed package makes no sense from a dependency resolving perspective, as the removal itself can have a huge impact on how the new graph would look. If anything, I feel like `remove` is a somewhat poor choice of a name for a command that does much more than simply remove. It does not merely update the composer.json and drop a requirement. It runs the whole solving process again too.

**Comment by exteon** [comment]
But that doesn't need to happen. Removing a rule does not make the graph inconsistent, it's not the same as `require` or `update some-package`. It is perfectly correct that after an update the graph might look different because of the opened version space, but wouldn't it make more sense that is left to my choice?

Also (and I haven't looke into it yet), I'm pretty sure the plugins have (or will need at some point have) different semantics for package install, (up|down)grade and uninstall, because when external state data is involved, uninstall/install (==reset) is quite not the same as "upgrade", which preserves (and maybe change) data. That is also a probable why `update` should not do removal (risk of warningless data loss).

So any way you look at it, `remove` is bound by nature to have different semantics than `update`...

**Comment by alcohol** [comment]
I stay far away from the whole plugin component of Composer, and prefer not to comment on that.

> And it turns out I'm right:

I have no idea what you are claiming to be right about. You've lost me.

Maybe I should be more verbose about what I am trying to explain:

I'm merely saying that `remove` is a shortcut. It modifies your composer.json for you, altering your list of requirements/constraints. Basically a quick way for people who do not want to modify their composer.json manually. After this, it runs `update` with or without some constraints (depending on what flags you passed to `remove`). So as I said before, the verb "remove" here is not entirely accurate. Since there is no "removing a package". There is only the removal of a requirement/constraint, which means a new graph is resolved.

**Comment by stof** [comment]
@naderman with Composer 2.x not taking into account installed packages, wouldn't a `composer update --lock` already remove packages which are not required anywhere anymore ?

**Comment by naderman** [comment]
@stof A composer update --lock specifically requests the installation of all packages in the lock file at their current version and then uses the solver, so it will never remove any packages. You can do a partial update for the packages to be removed and that will remove them.
