### ISSUE TITLE
-q, --quiet also turn off expected output in query commands

### ISSUE THREAD

**Issue by exteon** [composer/composer#8284]
Running with `-q` literally turns output off even for commands that only exist to produce an output, such as `show`. The way it usually works with other tools it that is suppresses any processing meta-messages (such as warnings, process state or completion messages), but if a function is supposed to produce a certain output (i.e. data queries) it does produce it, as it's the main purpose of the function.

**Comment by alcohol** [comment]
I think currently `--quiet` is used mostly when you don't care about the output but only the exit code of the process. In your scenario I am not even sure why you would use quiet. Adjusting the behaviour as per your suggestion would require quite a lot of work (determine when and where we should or should not mute output), which none of us really have time for, considering of how little importance this really is.

**Comment by exteon** [comment]
Well, most tools feature it to suppress warnings and other meta-information to use in a programmatic context. I mean, you do support `--no-ansi`... `-q` as it is, is already readily available such as `2>&1 1>/dev/null`  or just not looking at the screen...

**Comment by alcohol** [comment]
Yeah, I understand. But it is simply a lot of work right now to fine tune the output when taking flags such as `--quiet` into account. Work that is simply not really worth the investment of time considering the gains.

**Comment by exteon** [comment]
Well, one instance that I find particularly bugging is that there is no way to shut the "Do not run composer as root" message. I have a couple of dev boxes where for the convenience of testing I always run as root. I ended up just deleting the warning code from composer so I can use its output programatically.

**Comment by alcohol** [comment]
Unrelated, but you can just set `COMPOSER_ALLOW_SUPERUSER` to avoid that warning (which goes to stderr so you can also filter that out using redirection).

**Comment by exteon** [comment]
Thanks!

**Comment by Seldaek** [comment]
--quiet will still output critical failures AFAIK, which >/dev/null wouldn't do. What you want to achieve is doable with `2>/dev/null` IMO, as relevant output of commands like `show` should be going to stdout and not stderr.
