### ISSUE TITLE
composer install Downloading shows 400%

### ISSUE THREAD

**Issue by mesiarm** [composer/composer#8285]
When i run composer install, it starts downloading packages and it shows current value of progress  percentage, but value wont stop at 100%, but continues up to 400%.

**Comment by alcohol** [comment]
Need a reproducible scenario.

**Comment by mesiarm** [comment]
1. run composer clear-cache
1. run composer install with existing composer.json file, which contains some new packages (or remove vendor folder or remove composer.lock file)
2. command outputs: 
Prefetching xx packages 
  - Downloading (xx%) - 
5. in some cases Downloading percentage reach 400%

**Comment by alcohol** [comment]
I cannot reproduce it without a composer.json.

**Comment by alcohol** [comment]
Make sure you also first run install with `--no-plugins --no-scripts` to see if that solves it.
