### ISSUE TITLE
replace environment variable into composer.json

### ISSUE THREAD

**Issue by martingg88** [composer/composer#8297]
I do have following repo setting at composer.json. How to do make repo url to be variable instead of hard code the repo url and replaced by environment variable when run the composer require/update. Thanks.

```
 "repositories": [
        {
            "type": "path",
            "url": "../../Framework",
            "options": {
                "symlink": true
            }
        }
    ],
```

**Comment by Seldaek** [comment]
This is not possible.. Relative paths is as good as it gets, and tbh I don't think env var support is going to happen there.

**Comment by stof** [comment]
Supporting env variables would be a pain regarding the lock file btw.

**Comment by martingg88** [comment]
This Framework wouldn't be relative to the project root directory when switch to production environment. Any idea how to make this path declaration to be more dynamic and flexible?

Thank

**Comment by Seldaek** [comment]
You could have a separate composer.json file for production with a different path I guess but that's kind of a maintenance nightmare as well.

**Comment by martingg88** [comment]
Yes. It'd be another nightmare as well.
