### ISSUE TITLE
Bad checksum on windows installer

### ISSUE THREAD

**Issue by desperatedan85** [composer/composer#8299]
I've downloaded the windows installer Composer-Setup.exe v1.9.0

When checking the SHA-384 checksum, I get:
EA39C1DDDA72C722EA540C4E13EFABD17BF03660641FE7A1D231220FA5B05DBE6FD...

And I expected this to happen: Checksum should have been
a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1

Can I verify my checksum is ok?

**Comment by Seldaek** [comment]
Sorry the checksums are only published for the php installer, not for the exe.

ea39c1ddda72c722ea540c4e13efabd17bf03660641fe7a1d231220fa5b05dbe6fd702ccbff4e4a13b9c273efad3d569 is correct though for the exe.
