### ISSUE TITLE
Composer 1.9.0 does not include port numbers in authentication prompts

### ISSUE THREAD

**Issue by lpd-au** [composer/composer#8300]
This issue relates to https://github.com/composer/composer/issues/8274. In that issue, I reported that identical hostnames with different/missing port numbers were now treated as different hosts for authentication purposes, which was then added to the changelog as a known breaking change. I also discussed that a lack of `-vvvv` logging (https://github.com/composer/composer/issues/8274#issuecomment-520888982) made this issue harder to diagnose on our CI server. The following bug made that issue harder to catch earlier in our development environments:

### Port numbers are not included in authentication prompts ###

Consider a `composer.json` that fetches two URLs:

1. `https://artifacts.myhost.local/api/composer/inno-composer`
2. `https://artifacts.myhost.local:443/api/composer/inno-composer/vcs-dists/zip/guzzle/guzzle/407b0cb880ace85c9b63c5f9551db498cb2d50ba`

Below is the expected output using Composer 1.9.0:

```
$ composer.phar update
Loading composer repositories with package information
    Authentication required (artifacts.myhost.local):
      Username: Lpd
      Password:
Do you want to store credentials for artifacts.myhost.local in /home/lpd/.composer/auth.json ? [Yn] n
Updating dependencies (including require-dev)
    Authentication required (artifacts.myhost.local:443):
      Username: Lpd
      Password:
Nothing to install or update
Generating autoload files
```

Below is the actual output using Composer 1.9.0:

```
$ composer.phar update
Loading composer repositories with package information
    Authentication required (artifacts.myhost.local):
      Username: Lpd
      Password:
Do you want to store credentials for artifacts.myhost.local in /home/lpd/.composer/auth.json ? [Yn] n
Updating dependencies (including require-dev)
    Authentication required (artifacts.myhost.local):
      Username: Lpd
      Password:
Nothing to install or update
Generating autoload files
```

Please take notice of the second "Authentication required" line.

**Comment by Seldaek** [comment]
If you can try again with the latest snapshot build that'd be nice, but I believe it fixes the issue.

**Comment by lpd-au** [comment]
Thanks, this is what I see now:

```
$ composer.phar update
Loading composer repositories with package information
    Authentication required (artifacts.myhost.local):
      Username: Lpd
      Password:
Do you want to store credentials for artifacts.myhost.local in /home/lpd/.composer/auth.json ? [Yn] n
Updating dependencies (including require-dev)
    Authentication required (artifacts.myhost.local:443):
      Username: Lpd
      Password:
Do you want to store credentials for artifacts.myhost.local:443 in /home/lpd/.composer/auth.json ? [Yn] n
Nothing to install or update
Generating autoload files
```
