### ISSUE TITLE
Composer v1.9.0 Windows - Disable xdebug

### ISSUE THREAD

**Issue by TCB13** [composer/composer#8302]
Hello,
I installed composer in a Windows machine using the provided installer and it doesn't seem to disable xdebug properly. Whenever I run composer I always get xdebug in phpstorm asking a project to attach to.

To install xdebug I simply downloaded the extension and added this to my `php.ini`:
````
[XDebug]
zend_extension="php_xdebug-2.8.0beta2-7.3-vc15-x86_64.dll"
xdebug.remote_host = 127.0.0.1
xdebug.remote_port=9000
xdebug.remote_enable=true
xdebug.profiler_append = 0
xdebug.profiler_enable = 0
xdebug.profiler_enable_trigger = 0
xdebug.remote_enable = on
xdebug.remote_handler = dbgp
xdebug.remote_autostart = On
xdebug.auto_trace = Off
xdebug.show_exception_trace = Off
````
PHP info:
````
> php --version                                                                                                        
PHP 7.3.9 (cli) (built: Aug 28 2019 09:28:48) ( ZTS MSVC15 (Visual C++ 2017) x64 )                                     Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.8.0beta2, Copyright (c) 2002-2019, by Derick Rethans
````
Is this a bug? Composer should disable xdebug, shouldn't it?

Thank you.

**Comment by johnstevenson** [comment]
If you set the following environment variable before you run a Composer command, you will see if xdebug is present or not: `XDEBUG_HANDLER_DEBUG=1`

For example, using cmd.exe:

```
set XDEBUG_HANDLER_DEBUG=1
composer --version
```

**Comment by TCB13** [comment]
@johnstevenson let me show you what happens with composer and xdebug. When I run composer, phpstorm shows the debugger and composer hangs for ever until I click on the green "resume program" button:

![image](https://user-images.githubusercontent.com/6315832/64075212-550f8600-ccad-11e9-8224-cd47581b3478.png)

As you can see the debugger is attached to composer.phar and well nothing happens until I click resume. I believe that after that printscreen is more than obvious that composer is not disabling xdebug.

Now about your suggestion what's the expected output?

![image](https://user-images.githubusercontent.com/6315832/64075234-9869f480-ccad-11e9-9190-b38c933f688b.png)

Thank you.

**Comment by johnstevenson** [comment]
> Now about your suggestion, it clearly says that xdebug is enabled as well

It also says that it is not loaded in the restarted process, which is the correct behaviour.

**Comment by TCB13** [comment]
> not loaded in the restarted process

Yeah, check my edit. Sorry.

**Comment by johnstevenson** [comment]
Set up phpstorm so that it does not immediately start debugging? Sorry, I don't use it, but Composer is behaving as intended by disabling xdebug by default.

**Comment by TCB13** [comment]
Your command actually lead me to a fix, because I was finally able to understand what was going on. Here is the issue, composer does this:

1. Composer strats up
2. Check if there is xdebug enabled
3. If xdebug is enabled, restarts with process without xdebug.

Problem: phpstorm stops the execution of any php script if it is ouside the project directory by default. What happens is that phpstorm stops the execution of composer before it check if xdebug is enabled causing the issue I showed before.

With this in mind I found this fix:

![image](https://user-images.githubusercontent.com/6315832/64075432-2a72fc80-ccb0-11e9-98fd-aa4927a71edc.png)

This way phpstorm will ignore composer and the execution proceeds to step 3.

Thank you for the help!

**Comment by johnstevenson** [comment]
> Your command actually lead me to a fix, I'm finally able to understand what is going on.

Yeah, it's very useful to see exactly what is happening (especially if the restarted process then calls another php process). More info here: https://github.com/composer/xdebug-handler#troubleshooting

Thank you for taking the time to explain how to resolve it - this will be very useful for other folks in the same situation.
