### ISSUE TITLE
Add flag to require latest but fixed version: `composer require acme/foo --fixed`

### ISSUE THREAD

**Issue by unkind** [composer/composer#8303]
Usually, I prefer to keep fixed/specific versions of dependencies in my projects (applications):

```json
{
    "require": {
        "acme/foo": "1.0.42"
    }
}
```
There is always chance that some minor update of dependency may break compatibility even if it must not. I explicitly change version whenever I need to update specific dependency.

Every time I want to add a new dependency, I run `composer require acme/foo` and after that I edit `composer.json` to remove `^` from the version:
```diff
-        "acme/foo": "^1.0.42"
+        "acme/foo": "1.0.42"
```

I think it makes sense to consider adding option that would force composer to save `composer.json` with specific version, e.g. `composer require acme/foo --fixed`.

Some similar opinions/issues:
https://blog.martinhujer.cz/17-tips-for-using-composer-efficiently/#tip-%233%3A-use-specific-dependencies%27-versions-for-applications
https://stackoverflow.com/questions/41200946/update-composer-dependencies-to-latest-despite-static-version-numbers

What do you think?

**Comment by alcohol** [comment]
I think opinion on fixed versions vary a lot. But if you put that aside, the suggested addition is minor and trivial. Feel free to submit a PR.
