### ISSUE TITLE
`composer install` should not reinstall all installed packges

### ISSUE THREAD

**Issue by TangMonk** [composer/composer#8311]
I require a package in local development machine and the rsync to server, then run `composer install` on server, All packages will reinstall, it is unnecessary

It should only install newly added packages, just like [npm](https://www.npmjs.com) or [bundler](https://bundler.io)

**Comment by stof** [comment]
well, that's what composer does already. Make sure that you don't delete the `vendor/composer/installed.json` file though (as that's where Composer remembers what is already installed).

**Comment by stof** [comment]
also, if the server installed versions were not in sync with the composer.lock, a `composer install` will reinstall the affected packages to match what the lock file is asking for. But that's totally expected (and this is also what npm or yarn are doing, no idea about bundler).

**Comment by Seldaek** [comment]
Also not sure why you'd run a composer install on the server at all if you deployed all the files you need..
