### ISSUE TITLE
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

### ISSUE THREAD

**Issue by gumpon** [composer/composer#8312]
My `composer.json`:

```json
...replace me...
```

Output of `composer diagnose`:

```
...replace me...
```

When I run this command:
composer diagnose
```
...replace me...
```

I get the following output:
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 
Dev Public Key Fingerprint: 
OK
Checking composer version: OK
Composer version: 1.9.0
PHP version: 7.3.8
PHP binary path: C:\xampp\php\php.exe

```
...replace me...
```

And I expected this to happen:

Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed

**Comment by Seldaek** [comment]
It looks like you're having issues connecting to api.github.com - not sure why the certificate verification failed. If you run `composer diagnose -vvv` and paste the full output perhaps it'll point to a problem, but otherwise sounds like a network issue.

**Comment by gumpon** [comment]
Loading config file C:/Users/gumpon/AppData/Roaming/Composer/config.json
Loading config file C:/Users/gumpon/AppData/Roaming/Composer/auth.json
Reading C:/Users/gumpon/AppData/Roaming/Composer/composer.json
Loading config file C:/Users/gumpon/AppData/Roaming/Composer/config.json
Loading config file C:/Users/gumpon/AppData/Roaming/Composer/auth.json
Loading config file C:/Users/gumpon/AppData/Roaming/Composer/composer.json
Loading config file C:\Users\gumpon\AppData\Roaming\Composer/auth.json
Reading C:\Users\gumpon\AppData\Roaming\Composer/auth.json
Checked CA file C:\xampp\apache\bin\cacert.pem: valid
Executing command (C:/Users/gumpon/AppData/Roaming/Composer): git branch --no-color --no-abbrev -v
Executing command (C:/Users/gumpon/AppData/Roaming/Composer): git describe --exact-match --tags
Executing command (C:/Users/gumpon/AppData/Roaming/Composer): git log --pretty="%H" -n1 HEAD
Executing command (C:/Users/gumpon/AppData/Roaming/Composer): hg branch
Executing command (C:/Users/gumpon/AppData/Roaming/Composer): fossil branch list
Executing command (C:/Users/gumpon/AppData/Roaming/Composer): fossil tag list
Executing command (C:/Users/gumpon/AppData/Roaming/Composer): svn info --xml
Reading C:/Users/gumpon/AppData/Roaming/Composer/composer.json
Loading config file C:/Users/gumpon/AppData/Roaming/Composer/config.json
Loading config file C:/Users/gumpon/AppData/Roaming/Composer/auth.json
Loading config file C:/Users/gumpon/AppData/Roaming/Composer/composer.json
Loading config file C:\Users\gumpon\AppData\Roaming\Composer/auth.json
Reading C:\Users\gumpon\AppData\Roaming\Composer/auth.json
Reading C:/Users/gumpon/AppData/Roaming/Composer/vendor/composer/installed.json
Reading C:/Users/gumpon/AppData/Roaming/Composer/vendor/composer/installed.json
Running 1.9.0 (2019-08-02 20:55:32) with PHP 7.3.8 on Windows NT / 6.3
Loading config file C:/Users/gumpon/AppData/Roaming/Composer/config.json
Loading config file C:/Users/gumpon/AppData/Roaming/Composer/auth.json
Reading C:/Users/gumpon/AppData/Roaming/Composer/composer.json
Loading config file C:/Users/gumpon/AppData/Roaming/Composer/config.json
Loading config file C:/Users/gumpon/AppData/Roaming/Composer/auth.json
Loading config file C:/Users/gumpon/AppData/Roaming/Composer/composer.json
Loading config file C:\Users\gumpon\AppData\Roaming\Composer/auth.json
Reading C:\Users\gumpon\AppData\Roaming\Composer/auth.json
Executing command (C:/Users/gumpon/AppData/Roaming/Composer): git branch --no-color --no-abbrev -v
Executing command (C:/Users/gumpon/AppData/Roaming/Composer): git describe --exact-match --tags
Executing command (C:/Users/gumpon/AppData/Roaming/Composer): git log --pretty="%H" -n1 HEAD
Executing command (C:/Users/gumpon/AppData/Roaming/Composer): hg branch
Executing command (C:/Users/gumpon/AppData/Roaming/Composer): fossil branch list
Executing command (C:/Users/gumpon/AppData/Roaming/Composer): fossil tag list
Executing command (C:/Users/gumpon/AppData/Roaming/Composer): svn info --xml
Reading C:/Users/gumpon/AppData/Roaming/Composer/composer.json
Loading config file C:/Users/gumpon/AppData/Roaming/Composer/config.json
Loading config file C:/Users/gumpon/AppData/Roaming/Composer/auth.json
Loading config file C:/Users/gumpon/AppData/Roaming/Composer/composer.json
Loading config file C:\Users\gumpon\AppData\Roaming\Composer/auth.json
Reading C:\Users\gumpon\AppData\Roaming\Composer/auth.json
Reading C:/Users/gumpon/AppData/Roaming/Composer/vendor/composer/installed.json
Reading C:/Users/gumpon/AppData/Roaming/Composer/vendor/composer/installed.json
Checking platform settings: OK
Checking git settings: Executing command (CWD): git config color.ui
OK
Checking http connectivity to packagist: Downloading http://repo.packagist.org/packages.json
OK
Checking https connectivity to packagist: Downloading https://repo.packagist.org/packages.json
OK
Checking github.com oauth access: Downloading https://api.github.com/
FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: Dev Public Key Fingerprint:
OK
Checking composer version: Downloading https://getcomposer.org/versions
OK
Composer version: 1.9.0
PHP version: 7.3.8
PHP binary path: C:\xampp\php\php.exe

**Comment by Seldaek** [comment]
Ok so what I can think is perhaps C:\xampp\apache\bin\cacert.pem is outdated? Try replacing it with a fresh copy from https://curl.haxx.se/ca/cacert.pem

**Comment by vikas-nichi** [comment]
check my answer here it may help https://stackoverflow.com/a/60709451/5068530

**Comment by EduardoRoblesCh** [comment]
@vikas-agent 🎈🎈✨ You save my life. I just have to **TURN OFF the ANTIVIRUS**
