### ISSUE TITLE
[UnexpectedValueException]

### ISSUE THREAD

**Issue by maxval94** [composer/composer#8314]
[UnexpectedValueException]
  Your github oauth token for github.com contains invalid characters: "__TOKEN__"

_Originally posted by @Ianluyon in https://github.com/composer/composer/issues/3609#issuecomment-372935430_

The same issue!!

When execute
`composer config -g github-oauth.github.com *TOKEN*`

**Comment by smelike** [comment]
What is the matter? I have this issue.

**Comment by devantoine** [comment]
I got the same issue.

The only "invalid" char that I can think of in my token is an underscore.

**Comment by Seldaek** [comment]
@devantoine if you're seeing this, make sure you update to latest Composer version which was just released and includes a fix (https://github.com/composer/composer/pull/9757)

**Comment by devantoine** [comment]
@Seldaek yes, sorry about that I was coming back here to say I missed the latest version.
Thanks for your quick reply!
