### ISSUE TITLE
[Feature request] Allow to exclude package in Composer outdated

### ISSUE THREAD

**Issue by VincentLanglet** [composer/composer#8317]
I use 
```
composer outdated --direct --strict
```
on my CI to check every package is up to date.

But at the moment, I use a library that I don't want to update since the maintainer introduced a bug. It would be nice if I could do something like
```
composer outdated --direct --strict --exclude my-package
```
Or 
```
composer outdated --direct --strict --exclude some/file/with/the/list/of/package
```

**Comment by mathiasdonoso** [comment]
Is this different from the `--ignore` option?

**Comment by VincentLanglet** [comment]
@mathiasdonoso I don't see this option in the documentation https://getcomposer.org/doc/03-cli.md#outdated
