### ISSUE TITLE
Why allow_ssl_downgrade not part of repository options?

### ISSUE THREAD

**Issue by antonkomarev** [composer/composer#8321]
This is not a bug report. Wouldn't it be better for consistency to have `"allow_ssl_downgrade": true` configuration inside of the `options` object and not in the root of repository object?

There is `options.ssl` key already exists, I thought it will be better to have all the connection settings in one place.

Instead of:
```json
{
    "type": "composer",
    "url": "https?://packages.example.com",
    "allow_ssl_downgrade": true,
    "options": {
        "ssl": {
            "verify_peer": "true"
        }
    }
}
```

We will have:
```json
{
    "type": "composer",
    "url": "https?://packages.example.com",
    "options": {
        "ssl": {
            "allow_downgrade": true,
            "verify_peer": "true"
        }
    }
}
```

**Comment by stof** [comment]
That's because `options.ssl` is passed directly to [`stream_context_create`](https://www.php.net/stream-context-create). `allow_downgrade` is an option managed by Composer itself, not by the HTTP client layer.

**Comment by alcohol** [comment]
Like @stof said, different context :-)

**Comment by antonkomarev** [comment]
Just a note: `allow_ssl_downgrade` flag isn't documented.

**Comment by alcohol** [comment]
You are correct, it is only mentioned in https://github.com/composer/composer/blob/master/res/composer-schema.json
