### ISSUE TITLE
Windows junction was overwritten with git branch in path repository

### ISSUE THREAD

**Issue by oburk** [composer/composer#8322]
My `composer.json`:

```json
{
	"name": "muz/reced_backend",
	"description": "The backend.",
	"require": {
		"muz/beesite-backend-core": "*",
		"oomphinc/composer-installers-extender": "^1.1",
		"muz/beesite-module-event": "2.x-dev",
		"muz/beesite-community-backend": "^1.0",
		"muz/beesite-widget-extendedcandidate": "dev-master",
		"muz/beesite-backend-base": "dev-master",
		"muz/ffw": "dev-master"
	},
	"config": {
		"platform": {
			"php": "5.6",
			"ext-calendar": "0",
			"ext-imap": "0",
			"ext-ldap": "0"
		},
	},
	"minimum-stability": "dev",
	"prefer-stable": true,
	"autoload": {
		"classmap": [
			"wms/lib/",
			"webs/"
		]
	},
	"repositories": [
		{
			"type": "path",
			"url": "../../beesite_trunk/"
		},
		{
			"type": "composer",
			"url": "https://composer.milchundzucker.de/"
		},
		{
			"type": "composer",
			"url": "https://asset-packagist.org"
		}
	],
	"require-dev": {
		"phing/phing": "2.*"
	}
}

```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.9.0
PHP version: 5.6 - Package overridden via config.platform (actual: 7.3.4)
PHP binary path: C:\xampp\php\php.exe
```

When I run this command:
```
composer update
```

I get the following output:
First run
```
  - Removing muz/beesite-backend-core (7.1.22)
  - Installing muz/beesite-backend-core (dev-master): Junctioning from ../../beesite_trunk
```
Second run
```
  - Can only install one of: doctrine/doctrine-orm-module[1.1.5, 0.9.2].
    - muz/beesite-module-event dev-master requires doctrine/doctrine-orm-module ^0.9.2 || ^0.11 || ^1.1.8 || ^2.1.5 -> satisfiable by doctrine/doctrine-orm-module[0.11.0, 0.9.2, 1.1.8, 2.1.5].
    - Conclusion: don't install doctrine/doctrine-orm-module 0.11.0
```
Third run
```
 - Removing muz/beesite-backend-core (dev-master), source is still present in C:\Sandbox\beesite_hr_trunk\backend\vendor/muz/beesite-backend-core
  - Installing muz/beesite-backend-core (7.1.22): Downloading (100%)
```

And I expected this to happen:
First run of `composer update` successfully generated junction to my local git repository. I changed the php plattform requirements from `7.0` to `5.6` and run `composer update` again. Now I got some dependency problems (Second run). I solved them in our event module and run `composer update` again.

After running `composer update` last time  my local git repository was replaced by tagged stable version from git repository. All my local changes and branches are lost.

**Comment by crashkonijn** [comment]
Is anything being done with this? I've lost loads of work due to this as well.

**Comment by Seldaek** [comment]
It'd be good to have an easy to reproduce case, with public repos if possible.

**Comment by muzjsr** [comment]
I've lost Work due to that Issue also!
Everything worked fine for weeks. Than one day some Messages pops up during `composer update`. I answered with `yes`.
After that my local commits (and changes) were gone, cause of the replacement of the local git repo with the repo form server.

I had several interactions like the following with some 3rd-Party-Packages during update process.
`  - Updating twig/twig (v2.12.2 => v2.12.3):  Checking out 97b6311585
    Update failed (Failed to execute git checkout "97b6311585cae66a26833b14b33785f5797f7d39" -- && git reset --hard "97b6311585cae66a26833b14b33785f5797f7d39" --

error: The following untracked working tree files would be overwritten by checkout:
        extra/intl-extra/tests/IntlExtensionTest.php
Please move or remove them before you switch branches.
Aborting
)
    Would you like to try reinstalling the package instead [yes]? yes
  - Removing twig/twig (v2.12.2)
  - Installing twig/twig (v2.12.3): Cloning 97b6311585 from cache
`

Then at the End i got those information's:
`
  - Removing my_namespace/local_repo_1 (dev-master), source is still present in C:\PATH\TO\PROJECT\vendor/my_namespace/local_repo_1
  - Installing my_namespace/local_repo_1 (dev-master 68cd64f): Cloning 68cd64f9c2 from cache
  - Removing my_namespace/local_repo_2 (dev-master), source is still present in C:\PATH\TO\PROJECT\vendor/my_namespace/local_repo_2
  - Installing my_namespace/local_repo_2 (dev-master): Source already present
`

Interesting is that i loose all local History for local_repo_1 while local_repo_2 was untouched.

**Comment by JasonStephensTAMU** [comment]
I've encountered this issue as well, it appears the junction is not removed when the source changes from path to cache (or remote). This results in the junctioned folder being overwritten with the package files.

The actual case I've encountered was with a combination of private repos and local directories, however I have tried to simulate the issue using `symfony/skeleton` and `symfony/process`, with some success.

This is on Windows 10, using Composer 1.10.13 and Git Bash.

Assuming a starting directory of `C:\symfony`:

1. Install `symfony/skeleton` and require `symfony/process`
```
$ composer create-project symfony/skeleton skeleton
$ cd skeleton/
$ composer require symfony/process
...
Package operations: 1 install, 0 updates, 0 removals
  - Installing symfony/process (v5.1.7): Loading from cache
...
```

2. Clone the process repo as a sibling to the skeleton parent directory and checkout a new branch named outside of the current branch/tag names
```
$ cd ../
$ git clone https://github.com/symfony/process.git
$ cd process/
$ git checkout -b 5.1.79
```

3. Edit the version in the local process repo file `C:\symfony\process\composer.json` to match the branch name with x-dev appended
```
...
    "version": "5.1.79.x-dev"
}
```

4. Add the local path as a repository to the skeleton in `C:\symfony\skeleton\composer.json`
```
...
    "repositories": [
        {
            "type": "path",
            "url": "../process",
            "options": {
                "symlink": true
            }
        }
    ]
}
```

5. Return to the skeleton directory and require the local process version
```
$ cd ../skeleton/
$ composer require symfony/process 5.1.79.x-dev
...
Package operations: 0 installs, 1 update, 0 removals
  - Removing symfony/process (v5.1.7)
  - Installing symfony/process (5.1.79.x-dev): Junctioning from ../process
...
```

6. Now switch back to requiring the previous version
```
$ composer require symfony/process 5.1.7
...
Package operations: 0 installs, 1 update, 0 removals
  - Removing symfony/process (5.1.79.x-dev), source is still present in C:\symfony\skeleton\vendor/symfony/process
  - Installing symfony/process (v5.1.7): Loading from cache
...
```

7. Return to the process folder and verify the directory has been overwritten by the vendor package
```
$ cd ../process/
$ git status
fatal: not a git repository (or any of the parent directories): .git
```

Perhaps I'm using composer incorrectly, or there may be a permission issue on my end, if it proves difficult to reproduce.

My thought is that composer should not overwrite a junctioned folder in any scenario, fail with an error and/or possibly provide an option flag to force the overwrite.
