### ISSUE TITLE
[2.0][RFC] Stop normalizing dev-master as 9999999-dev

### ISSUE THREAD

**Issue by stof** [composer/composer#8323]
composer/semver normalizes `dev-master`, `dev-trunk` and `dev-default` to `9999999-dev`. This leads to hard-to-understand issues when dealing with conflict rules and branch aliases.:

- `stof/doctrine-extensions-bundle` has a branch-alias from `dev-master` to `1.3x-dev`
- `sonata-project/translation-bundle` has a conflict rule on `stof/doctrine-extensions-bundle` with the range `< 1.1 || >= 2.0`
- a project depends on `stof/doctrine-extensions-bundle: ^1.3@dev` and `sonata-project/translation-bundle`

This project cannot install dependencies:

```
  [Composer\DependencyResolver\SolverProblemsException]                                                                                
  Problem 1                                                                                                                            
      - Installation request for sonata-project/translation-bundle ^2.3 -> satisfiable by sonata-project/translation-bundle[2.x-dev].  
      - remove stof/doctrine-extensions-bundle 1.3.x-dev|keep stof/doctrine-extensions-bundle dev-master                               
      - stof/doctrine-extensions-bundle dev-master conflicts with sonata-project/translation-bundle[2.x-dev].                          
      - Installation request for stof/doctrine-extensions-bundle ^1.3 -> satisfiable by stof/doctrine-extensions-bundle[1.3.x-dev].   
```

This is because the `9999999-dev` version matches the conflict rule.

Disabling the normalization to a comparable version would impact projects depending on a `*@dev` constraint when there is no branch alias, as dev-master would then become like any other unversioned branches: it would need to either be required explicitly or to have a branch alias.
A lower-impact solution could be to disable that normalization only when the branch is aliased to an explicit version. but that could be harder to explain.

**Comment by Seldaek** [comment]
Another fix would be to say that the conflict here doesn't match because the alias can go through the conflict fine.. I am not sure if that's possible, but something worth investigating because changing the normalization is IMO a pretty big potential for problems.

**Comment by stof** [comment]
well, that would make conflicts harder to manage IMO (especially when the conflict matches the main Package and not the AliasPackage). But that's indeed something worth investigating. But I think that would be almost equivalent to the idea of disabling the normalization of `dev-master` when it has a branch alias (the only difference would be that a master branch with an alias of `1.3.x-dev` would not match a `>=2.5` requirement anymore, but I think that might actually make things more expected).

**Comment by stof** [comment]
An idea that I just got for that: stop *normalizing* the default branch (`master` or `trunk`) to `9999999-dev`, so that their normalized version stays `dev-master` (not comparable by semver and so not matching `conflict: > 5`). And instead, consider that this default branch has a branch alias of `9999999-dev` if there is no explicit branch alias.

**Comment by stof** [comment]
the effect of that change would be similar to my previous comment, but it is probably the simplest way to implement it.

**Comment by Seldaek** [comment]
Yup that's a good idea I think. Would need to try and see if anything goes wrong but in theory sounds good :)

**Comment by Seldaek** [comment]
Done in https://github.com/composer/composer/commit/a7a975ec1c0e3f30a04ea9ad75b696382559bc19 - it's working I believe to fix the conflict issue at least. It adds a few other little quirks but mostly internal stuff that I worked around.. I hope I didn't overlook anything.
