### ISSUE TITLE
Composer can not find composer.json file

### ISSUE THREAD

**Issue by Jeff-Yan** [composer/composer#8325]
My `composer.json`:

```json
C:\Users\jeffr\desktop\dce\dceu

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "doctrine/dbal": "^2.9",
        "fideloper/proxy": "^4.0",
        "google/recaptcha": "~1.1",
        "intervention/image": "^2.5",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "uxweb/sweet-alert": "^2.0"
    },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^7.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

```

Output of `composer diagnose`:

```
$ composer diagnose
Checking platform settings: OK
Checking git settings:

  [ErrorException]
  proc_open(NUL): failed to open stream: No such file or directory


diagnose

```

When I run this command:

```
composer install
or composer update
```

I get the following output:

```
$ composer install
Composer could not find a composer.json file in C:\Users\jeffr\desktop\dce\dceu
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

$ composer update
Composer could not find a composer.json file in C:\Users\jeffr\desktop\dce\dceu
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
```

And I expected this to happen:
it should install or update my packages

**Comment by otrigg** [comment]
I experienced the same issue just a few hours ago, after a Windows 10 update.
Could not be able to use composer anymore.
I reverted to the previous working version and the issue disappeared.

**Comment by marcoskipper** [comment]
> 
> 
> I experienced the same issue just a few hours ago, after a Windows 10 update.
> Could not be able to use composer anymore.
> I reverted to the previous working version and the issue disappeared.

How you reverted to the previus working version? i have the same issue, is beacuse this windows 10 update?

**Comment by otrigg** [comment]
> > I experienced the same issue just a few hours ago, after a Windows 10 update.
> > Could not be able to use composer anymore.
> > I reverted to the previous working version and the issue disappeared.
> 
> How you reverted to the previus working version? i have the same issue, is beacuse this windows 10 update?

I'm pretty sure it was Windows' today update in my case.
To revert, just: Windows Settings -> Update & Security -> Recovery -> Go back to previous version of Windows 10

**Comment by marcoskipper** [comment]
> 
> 
> > > I experienced the same issue just a few hours ago, after a Windows 10 update.
> > > Could not be able to use composer anymore.
> > > I reverted to the previous working version and the issue disappeared.
> > 
> > 
> > How you reverted to the previus working version? i have the same issue, is beacuse this windows 10 update?
> 
> I'm pretty sure it was Windows' today update in my case.
> To revert, just: Windows Settings -> Update & Security -> Recovery -> Go back to previous version of Windows 10

Nice! i was fighting whit this error like 3 hours, thx a lot!

**Comment by Gitog** [comment]
Ho do you resolve the same error hen using linux, i even changed path to compose location and still getting
'Composer could not find a composer.json file in /usr/local/bin
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
'

**Comment by HeardTangent** [comment]
Got the same problem, and have reverted windows 10 to updates from 2019 August but still isn't working. Anyone have a solution?

**Comment by boay24** [comment]
same here.
![Capture](https://user-images.githubusercontent.com/61148495/75012432-8cb8f700-54b4-11ea-8647-01854a9ae753.PNG)

# composer update
  Composer could not find a composer.json file in /mnt/c/container/24template/6748-MY/app/local
  To initialize a project, please create a composer.json file as described in the 
  https://getcomposer.org/ "Getting Started" section

OS Build 1964.1005

**Comment by Esthove** [comment]
Is there any fix for this issue without having to revert Windows update ?

**Comment by pabloprieto** [comment]
Got the same issue after updating Windows and found out it was because the project folder was in a OneDrive shared folder. Moving the project folder out of OneDrive solved the issue.

**Comment by Esthove** [comment]
Thanks @pabloprieto, moving the project folder out of OneDrive helped. Got composer working.

**Comment by ionl** [comment]
It's OneDrive! Thank you Microsoft :D

**Comment by ahajjaj** [comment]
To install composer and add to your global path:

curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer

**Comment by shahryarahmad** [comment]
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "doctrine/dbal": "^2.9",
        "fideloper/proxy": "^4.0",
        "google/recaptcha": "~1.1",
        "intervention/image": "^2.5",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "uxweb/sweet-alert": "^2.0"
    },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^7.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
copy the above and paste into a notepad file and save as composer.json and put it in the directory where the error is being shown eg. 
Composer could not find a composer.json file in C:\Users\Shahryar Ahmad
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

just goto C:\Users\Shahryar Ahmad and paste the json file their goto cmd and type composer update and you are good to go

![image](https://user-images.githubusercontent.com/46865356/90146482-86884100-dd9a-11ea-8d56-ad4a74df5148.png)

**Comment by twalibu** [comment]
I got the same error when i install composer any one come with solution please ..

**Comment by nolasco7a** [comment]
I have exactly the same error but yet I don't found a solution, some suggest?

**Comment by Jim97M** [comment]
If you are using ubuntu most likely your installable composer.json for package tracing and management is located in "/home/user/.config/composer". If you navigate to this folder and run composer update then Dang! you are good to go.

**Comment by eymeen** [comment]
I've faced the same problem, just check the version of PHP you're using if it is appropriate for the project you're working on, for me it was **7.4.26**
