### ISSUE TITLE
Offline require/update

### ISSUE THREAD

**Issue by szepeviktor** [composer/composer#8327]
My `composer.json`:

```json
(empty)
```

When I run this command:

```
composer require --dev phpstan/phpstan-shim szepeviktor/phpstan-wordpress
```

I get the following output:

```
Using version ^0.11.15 for phpstan/phpstan-shim
Using version ^0.2.0 for szepeviktor/phpstan-wordpress
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing phpstan/phpstan-shim (0.11.15): Loading from cache
  - Installing giacocorsiglia/wordpress-stubs (v5.1.1): Loading from cache
  - Installing szepeviktor/phpstan-wordpress (0.2.0): Loading from cache
Writing lock file
Generating autoload files
```

And I expected this to happen:

When I inspect a new WordPress plugin I use the above command but I **always** have to wait for Composer to check the latest packages.
Would it be possible to implement `--cached-only` to skip connecting to repo(s) and use the local cache only?
Thank you.

**Comment by Seldaek** [comment]
Yup on v2 you should be able to run with `COMPOSER_DISABLE_NETWORK=1` set in the env.
