### ISSUE TITLE
composer archive --format=zip does not preserve permission umask on files

### ISSUE THREAD

**Issue by jimmy-ho** [composer/composer#8330]
It is noticed when using **composer/satis** that during the archive process to create **dist** of repository tags/branches that permission umask on files that may have an executable flag set is not maintained.

composer/satis simply uses the composer archive functionality where the issue lies.

I have traced this down to the ZipArchiver not using the **setExternalAttributesName** applied on the resultant file in the zip archive.

I have a patch forthcoming to address this issue for review.

Unless someone can explain if this was intentional.

This is related to https://github.com/composer/satis/issues/314

**Comment by stof** [comment]
I don't think this was intentional. Most probably the developer implementing the ZipArchiver was not aware of the `setExternalAttributesName` API (or maybe it was implemented before this API was added in PHP 5.6)

**Comment by jimmy-ho** [comment]
Cool thanks @stof for your feedback, I'll update once I have a PR up for quick review.

**Comment by stof** [comment]
@jimmy-ho make sure to keep the ZipArchiver working on PHP < 5.6 (as the min version of PHP supported by Composer is 5.3), by skipping the `setExternalAttributesName` usage there (it is better to generate the archive as today on old PHP runtimes than to fail to generate it).

**Comment by jimmy-ho** [comment]
Thanks for the callout @stof, will do.

**Comment by jimmy-ho** [comment]
PR for this at: https://github.com/composer/composer/pull/8331

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/pull/8331
