### ISSUE TITLE
create-project fails when requiring dev versions, even with --stability=dev flag

### ISSUE THREAD

**Issue by aaronbauman** [composer/composer#8333]
My `composer.json`: https://github.com/aaronbauman/example-drops-8-composer/blob/create_fail/composer.json

Output of `composer diagnose`:
```
Checking composer.json: WARNING
require.drupal/bootstrap : exact version constraints (3.x-dev) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.9.0
PHP version: 7.0.8 - Package overridden via config.platform (actual: 7.1.8)
PHP binary path: /usr/local/Cellar/php@7.1/7.1.8_20/bin/php
```

When I run this command:
```
composer create-project pantheon-systems/example-drops-8-composer:dev-create_fail footest -n --stability=dev -vvv --repository='{"type": "vcs","url": "https://github.com/aaronbauman/example-drops-8-composer.git"}'
```

I get the following output (error only, full output on pastebin: https://pastebin.com/j6z3iMzQ ):
```                                                                                                                                                  
  [RuntimeException]                                                                                                                              
  Failed to execute git checkout 'abd91b3eb6d49587fd929057f65be3e4144f2b22' -- && git reset --hard 'abd91b3eb6d49587fd929057f65be3e4144f2b22' --  
                                                                                                                                                  
  fatal: Not a git repository (or any of the parent directories): .git                                                                            
```

And I expected this to result in a successful create project.

Additional information:
  - Tried various other version syntax to require drupal/bootstrap, none work. including ^3.x-and ^dev-3.x
  - Removing the drupal/bootstrap:3.x-dev requirement allows successful create-project
  - Switching to a tagged release (e.g. ^3.0) allows successful create-project
  - `composer install` works perfectly fine with the same composer.json
  - `--no-plugins` flag allows create-project command to complete successfully

I realize this may be an issue with one of the plugins, or interactions between plugins (or maybe not). But I have no idea on how to track this down, and I've been unable to find a guide about how to set up composer for debugging.

Can anyone help?

**Comment by alcohol** [comment]
Can you run the same command with `--no-plugins` and let me know if that succeeds or not?

**Comment by alcohol** [comment]
Ah I missed the last line in additional information.

But in short, determine which plugin is causing the failure and submit an issue with the plugin maintainer/repository instead.

**Comment by aaronbauman** [comment]
I have removed all requirements other than drupal/bootstrap:3.x-dev, and still getting the error as above. Presumably this means the problematic plugin is a 2nd-level dependency.

Any suggestions about how to track it down among the 132 inherited dependencies?

**Comment by alcohol** [comment]
The plugin that is causing issues is not a dependency of your project. It is most likely one of the globally installed plugins on your host machine.

**Comment by aaronbauman** [comment]
Thank you thank you, i removed some unused packages and updated my globals and the problem is resolved!
