### ISSUE TITLE
Require as with invalid version string breaks whole composer

### ISSUE THREAD

**Issue by Dropa** [composer/composer#8338]
So if you happen to insert invalid version string when requiring package, it will still write it into `composer.json` and nothing works after that. So for example; `composer require phpunit/phpunit:"8.3.3 as ^8.3"`

My `composer.json`:

```json
{
    "require": {
        "phpunit/phpunit": "8.3.3 as ^8.3"
    }
}
```

Output of `composer diagnose`:

```
$ composer diagnose
                                                                               
  [UnexpectedValueException]                                                   
  Invalid version string "^8.3" in "8.3.3 as ^8.3", the alias must be an exac  
  t version                                                                    
                
```

When I run this command:

```
$ composer require phpunit/phpunit:"8.3.3 as 8.3.0"
```

I get the following output:

```                                                                               
  [UnexpectedValueException]                                                   
  Invalid version string "^8.3" in "8.3.3 as ^8.3", the alias must be an exac  
  t version          
```

And I expected this to happen:
```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downgrading phpunit/phpunit (8.3.0 => 8.3.3): Downloading (100%)         
Writing lock file
Generating autoload files
```

**Comment by Seldaek** [comment]
That is correct, and indeed not ideal, but it's also really hard as we load the composer.json first and that fails as the alias is invalid.. If you choose to add an invalid alias by editing the file by hand, I guess you are stuck on your own to fix the file by editing it manually as well.

**Comment by Dropa** [comment]
The invalid alias is not put in file by hand. The require does that even with invalid alias. So the fix would be to check require validity before editing file, right?

**Comment by Seldaek** [comment]
Ah yeah sorry I missed that, if composer require lets you enter invalid aliases that's definitely smth which should be fixed.

**Comment by stof** [comment]
Well, in your report, you say that your composer.json contains the invalid alias already. Is it indeed the case when you run `composer require` ?

**Comment by Dropa** [comment]
I may have been a bit unclear. I did write require before that part in the issue. You may reproduce the problem without any composer.json existing by going in empty folder and running `composer require phpunit/phpunit:"8.3.3 as ^8.0"`. 

Also note that I made the expected result with a little modified situation where module wouldnhave been installed already.

**Comment by adrianosferreira** [comment]
@Seldaek I've done my first contribution here in https://github.com/composer/semver/pull/76. Please let me know how it goes :)

**Comment by Seldaek** [comment]
composer require does not work at all for me with aliases:

```
$ composer require phpunit/phpunit:"8.3.3 as 8.3.0"

  [InvalidArgumentException]
  Could not find package as.

  Did you mean one of these?
      ext-hash
      ramsey/uuid
      doctrine/cache
      webmozart/assert
      phar-io/manifest

```

That said, if the update fails we now revert the composer.json so I think this issue is fixed now. Please try with 2.0 and confirm though.
