### ISSUE TITLE
Class autoloaded with mistaken namespace crashes program

### ISSUE THREAD

**Issue by CJDennis** [composer/composer#8340]
If a file `Foo/Bar/Qux.php` is included but the fully qualified class name is `\Foo\Baz\Qux` (`Baz` instead of `Bar`), PHP will die on the second attempt to autoload the class.

`Composer\Autoload\ClassLoader::loadClass()` assumes that if it finds a class, the namespace must therefore match what it's expecting. It also assumes that a missing class is a fatal error, which is not always the case. It calls `includeFile($file)` which `include`s the file, when it should only `include_once`, since it's expecting a class.

From what I can tell it would be safe to change `include` to `include_once`, but I can't be 100% sure. Maybe change `includeFile($file)` to `includeFileOnce($file)`, or add `includeFileOnce($file)`.

**Comment by alcohol** [comment]
Have never heard of nor seen such an issue before myself. Need a actual reproducible scenario to determine what could cause this. If you can create a repository somewhere with demo files / Docker containers with the right PHP version, we can look into this. But otherwise, nothing we can do.

**Comment by stof** [comment]
Well, the drawback of `include_once` vs `include` is related to performance: `include_once` needs to perform more IO checks.
As the benefit would be only for cases where you make a typo in your namespace (or folder) compared to the PSR-4 convention, I'm not sure it is worth the cost.

Btw, if you want to be warned about such error during development, the `symfony/debug` component implements a DebugClassLoader which wraps the composer autoloader and adds checks for such mismatch (as well as reports a bunch of deprecated usages), with the benefit that it can be used in a dev environment without affecting the performance of a prod environment (unlike changing the way the composer ClassLoader includes files).

**Comment by Seldaek** [comment]
Yeah this is unfortunately something we can not fix due to performance reasons.
