### ISSUE TITLE
The requested PHP extension ext-zip ^7.2 has the wrong version (1.15.4) installed.

### ISSUE THREAD

**Issue by dev-mansonthomas** [composer/composer#8342]
My `composer.json`:

```json
{
    "name": "rcq/redcrossquest",
    "description": "",
    "keywords": ["microframework","rest","router", "psr7"],
    "homepage": "http://github.com/slimphp/Slim-Skeleton",
    "license": "MIT",
    "authors": [
        {
            "name": "Thomas Manson",
            "email": "email@domain.com",
            "homepage": "http://www.domain.com/"
        }
    ],
    "require": {
        "php": "7.2.*",
        "slim/slim": "^3.11",
        "slim/php-view": "^2.2",
        "robmorgan/phinx": "^0.10.6",
        "fzaninotto/faker": "^1.8",
        "nesbot/carbon": "^1.36.2",
        "lcobucci/jwt": "^3.3.1",
        "phpmailer/phpmailer": "^6.0",
        "ramsey/uuid": "^3.8",
        "sendgrid/sendgrid": "^7",
        "google/apiclient": "^2.2",
        "google/cloud-pubsub": "^1.7",
        "google/cloud-storage": "^1.10",
        "google/recaptcha": "^1.2",
        "ext-zip" : "^7.2",
        "ext-bz2" : "^7.2",
        "ext-PDO" : "^7.2",
        "ext-json": "^1.6",
        "symfony/validator": "^4.2",
        "egulias/email-validator": "^2.1",
        "google/cloud": "^0.93.0"
    },
    "autoload": {
      "psr-4": {"RedCrossQuest\\": "src/"}
    },

    "config": {
      "optimize-autoloader": true
    }
}

```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.9.0
PHP version: 7.2.22
PHP binary path: /usr/local/Cellar/php@7.2/7.2.22_1/bin/php

```

When I run this command:

```
composer update
```

I get the following output:

```
[12:52]user@laptop:~/path$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-zip ^7.2 has the wrong version (1.15.4) installed. Install or enable PHP's zip extension.

```

And I expected this to happen:

perform composer update normally.
This also prevent me to install new package with the same error.

I've just reinstalled httpd/apache with Brew on my mac : 

brew install httpd
brew install php@7.2

and perform the basics to enable php into httpd.

If I display phpinfo(), I get 

```
Zip | enabled

Zip version | 1.15.4
Libzip headers version | 1.5.2
Libzip library version | 1.5.2
```

So the versionb 1.15.4 seems a legitimate version.

i've tried to installed the PECL zip extension (which is in the version 1.15.5), but I couldn't find a way to override the version integrated with php.

it's really a major issue for me, as it blocks me in my development (which of course requires zip to work)

**Comment by xabbuh** [comment]
What about not requiring a certain version of the extension instead (i.e. use something like `'ext-zip': '*'` instead)?

**Comment by dev-mansonthomas** [comment]
Thanks, it's a good work-around !

Although I feel it should work with the 7.2 explicitly set.

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating optimized autoload files
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
[13:45] thomasmanson@Thomass-MBP:~/Dropbox/eclipse-workspace/crf2/RedCrossQuest/server$ 
```

**Comment by xabbuh** [comment]
I do not understand. Why should 7.2 work if the version of the extension is 1.15?

**Comment by stof** [comment]
@dev-mansonthomas I don't understand why you complain about this. `1.15.4` is indeed a legitimate version. but your own composer.json requires `^7.2`, and `1.15.4` does not match that constraint (and there is no reason it should, unless you work in a world where `7 === 1`).

**Comment by apfelbox** [comment]
The versions of the PHP extensions are completely separate from the PHP version itself  – maybe that is the confusion here.

As the versions of PHP extensions are normally pretty unreliable most people just use `"*"` as was already mentioned.

**Comment by dev-mansonthomas** [comment]
Thanks @apfelbox 

It's incorrect to state that PHP 7.2 must come with version 1.15.5, as you could see, brew compiles it with version 1.15.4 and it's totally legitimate. And 1.15.5 works as well, as shown, using PECL.

I guess that somewhere the link version 7.2 of PHP must come with 1.15.5 should be change to 1.15.x (or something similar)

**Comment by xabbuh** [comment]
What link are you talking about? As far as I can see the only link is that you assume a certain version of the extension based on the version of the PHP version that you use.
