### ISSUE TITLE
[InvalidArgumentException]There is no packagist.org.url repository defined

### ISSUE THREAD

**Issue by liesauer** [composer/composer#8343]
composer version:
`1.8.6 2019-06-11 15:03:05`

When I run this command:

```
composer config repositories.packagist.org.url
```

I get the following output:

```
  [InvalidArgumentException]
  There is no packagist.url repository defined
```

And I expected this to happen:
print my mirror url

how ever i run the following commands are all work fine:
```
composer config repositories
{"packagist.org":{"type":"composer","url":"https:\/\/mirrors.aliyun.com\/composer\/"}}

composer config repositories.packagist.org
{"type":"composer","url":"https:\/\/mirrors.aliyun.com\/composer\/"}
```

it seems like is the json syntax parser issue.

**Comment by alcohol** [comment]
The `config` command does not support this currently.

**Comment by Seldaek** [comment]
See #8353 for why this isn't possible and probably won't be as well as workarounds.
