### ISSUE TITLE
[sh: 1: : Permission denied] php exec('composer install  2>&1', $output); echo sh: 1: : Permission denied

### ISSUE THREAD

**Issue by jackwiy** [composer/composer#8344]
Dear,

I can't use php exec composer as www-data user in web service.
it show "sh: 1: : Permission denied", no more information to show.
I hope what is specific reasons or more debug information output？

#ll /usr/local/bin/composer
-rwxrwxr-x 1 www-data www-data 1932034 Sep 26 02:32 /usr/local/bin/composer*

#cat /etc/passwd | grep www-data
www-data: x:1000:33:www-data:/var/www

#ll /var/www/.composer/
total 1888
drwxr-xr-x  4 www-data www-data    4096 Sep 26 02:32 ./
drwxr-xr-x  1 root     root        4096 Sep 26 03:12 ../
-rw-r--r--  1 root     root     1849094 Sep 26 02:32 2018-05-04_11-44-59-1.6.5-old.phar
-rwx--x--x  1 www-data www-data     236 Sep 24 06:20 auth.json*
drwxr-xr-x  5 www-data www-data    4096 Sep 24 06:18 cache/
-rwxr-xr-x  1 www-data www-data      96 Jun 30  2018 composer.json*
-rwxr-xr-x  1 www-data www-data   36284 Jun 30  2018 composer.lock*
-rwx--x--x  1 www-data www-data     173 Sep 24 06:58 config.json*
-rwxr-xr-x  1 www-data www-data      13 Jun 30  2018 .htaccess*
-rwxr-xr-x  1 www-data www-data     799 Jun 30  2018 keys.dev.pub*
-rwxr-xr-x  1 www-data www-data     799 Jun 30  2018 keys.tags.pub*
drwxr-xr-x 12 www-data www-data    4096 Jun 30  2018 vendor/

#ll  /var/www/html/app | grep composer
-rwxrwxrwx  1 www-data www-data   2196 Sep 26 03:27 composer.json*
-rwxrwxrwx  1 www-data www-data 211403 Sep 24 07:08 composer.lock*

cat deploy.sh
#!/bin/bash

#debug
date
set -x

#who
whoami

#pwd
cd /var/www/html/app
pwd

#composer
composer install

cat deploy.php
$bash = 'bash /var/www/html/app/deploy.sh 2>&1';
exec($bash,$output,$status);
echo implode("\n",$output);

php web browser echo content:

Thu Sep 26 03:51:42 UTC 2019
+ whoami
www-data
+ cd /var/www/html/app
+ pwd
/var/www/html/app
+ composer install
sh: 1: : Permission denied

Ref:
https://github.com/jeromejaglale/laravel-github-webhook
https://jeromejaglale.com/doc/php/laravel_github_webhook

First, create the shell script. At the root of your Laravel application, add deploy.sh
I want use www-data,no root,Because to be on the safe side。 
Do not run Composer as root/super user! See https://getcomposer.org/root for details

Thanks

**Comment by alcohol** [comment]
Could you show us the output of

```
head /usr/local/bin/composer
```

**Comment by alcohol** [comment]
This is confusing as ****. So.. you have a php script that calls a bash script that calls composer. Why on earth are you complicating it so much? Just run composer directly as the www-data user.

**Comment by alcohol** [comment]
Regardless, this is an environment/deployment issue, and not a Composer issue.

**Comment by jackwiy** [comment]
@alcohol 
Thank you for your reply.
