### ISSUE TITLE
Running `composer install` invalidates sudo cache?

### ISSUE THREAD

**Issue by jesseleite** [composer/composer#8345]
If I cache my sudo credentials for the duration of an install script using `sudo --validate` at the beginning of my script, when my script gets to `composer global install`, it's like the sudo cache is invalidated, and all future commands requiring a password ask for one again.  Is there a reason for this, or might this be a bug?

**Comment by Seldaek** [comment]
We do this to avoid privilege escalation in potential nefarious plugins or anything. You can use `export COMPOSER_ALLOW_SUPERUSER=1` before to allow root user usage and sudo cache to persist.
