### ISSUE TITLE
composer install without creating lock file

### ISSUE THREAD

**Issue by webdevium** [composer/composer#8357]
### Useful feature

When I run this command:

```
composer install --no-lock
```

I expected this to happen:
no **composer.lock** file created in current folder

**Comment by Seldaek** [comment]
What's the use case?

**Comment by Seldaek** [comment]
Also this looks like a duplicate of #8354 but if you have a use case for a flag vs a config option please do tell, otherwise this can be closed I guess.

**Comment by webdevium** [comment]
Yeap. My use case is mostly identical with #8354. Parameter in composer.json is useful too. Thanks!
