### ISSUE TITLE
Composer - Patch support issues

### ISSUE THREAD

**Issue by ihor-sviziev** [composer/composer#8368]
My `composer.json`:

```json
{
    "name": "vendor/module",
    "description": "description",
    "homepage": "https://example.com",
    "require": {
        "php": "^7.1.3",
        "magento/product-community-edition": "~2.3.2",
        "magento/module-catalog-import-export": "101.0.2|101.0.2-p*",
        "psr/log": "^1.0"
    },
    "type": "magento2-module",
    "license": "proprietary",
    "autoload": {
        "files": [
            "registration.php"
        ],
        "psr-4": {
            "Vendor\\Module\\": ""
        }
    }
}
```

Output of `composer diagnose` (in another directory):

```

Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.9.0
PHP version: 7.1.32
PHP binary path: /usr/bin/php7.1

```

When I run this command:

```
composer diagnose -v
```

I get the following output:

```
                                                                                      
  [UnexpectedValueException]                                                          
  Could not parse version constraint 101.0.2-p*: Invalid version string "101.0.2-p*"  
                                                                                      

Exception trace:
 () at phar:///usr/bin/composer/vendor/composer/semver/src/VersionParser.php:477
 Composer\Semver\VersionParser->parseConstraint() at phar:///usr/bin/composer/vendor/composer/semver/src/VersionParser.php:249
 Composer\Semver\VersionParser->parseConstraints() at phar:///usr/bin/composer/src/Composer/Package/Version/VersionParser.php:29
 Composer\Package\Version\VersionParser->parseConstraints() at phar:///usr/bin/composer/src/Composer/Package/Loader/ArrayLoader.php:238
 Composer\Package\Loader\ArrayLoader->parseLinks() at phar:///usr/bin/composer/src/Composer/Package/Loader/ArrayLoader.php:121
 Composer\Package\Loader\ArrayLoader->load() at phar:///usr/bin/composer/src/Composer/Package/Loader/RootPackageLoader.php:115
 Composer\Package\Loader\RootPackageLoader->load() at phar:///usr/bin/composer/src/Composer/Factory.php:351
 Composer\Factory->createComposer() at phar:///usr/bin/composer/src/Composer/Factory.php:576
 Composer\Factory::create() at phar:///usr/bin/composer/src/Composer/Console/Application.php:354
 Composer\Console\Application->getComposer() at phar:///usr/bin/composer/src/Composer/Console/Application.php:471
 Composer\Console\Application->getPluginCommands() at phar:///usr/bin/composer/src/Composer/Console/Application.php:165
 Composer\Console\Application->doRun() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/bin/composer/src/Composer/Console/Application.php:106
 Composer\Console\Application->run() at phar:///usr/bin/composer/bin/composer:61
 require() at /usr/bin/composer:24
```

And I expected this to happen:
It will show diagnose data.

**Additional info:**

This issue appear even i'll try to execute just `composer`, `composer -v` or `composer -V`.

According to https://github.com/composer/semver/blob/0f299a13ad1188a276c9c12b321475d22cf1ac34/src/VersionParser.php#L39 - version `101.0.2-p2` - valid version, so we should able to depends on it.

Also I think composer should be able to write his version, diagnose with even broken composer.json file in the folder.

**Comment by ihor-sviziev** [comment]
Hi @alcohol,

>Composer cannot operate with a broken composer.json file because this file is read before most actions are taken. So you have to fix the contents before you can execute whichever command you want to execute. 

As for me - it doesn't have a sense. `composer.json` - config file for the project, not global config for whole composer and it should NOT affect global composer command.

As an example Google Chrome - this is browser, it works with websites. If you went to the website with broken html - it should be broken **only for this tab**, but you should be able to use core functionality - open new tabs, see Chrome's settings, version, etc.

Am I wrong?

**Comment by stof** [comment]
@ihor-sviziev the composer.json is the config of the project. The HTML is not the config of Chrome. If you want to compare it with Chrome, you would need to compare it to the Chrome settings (corrupting the file containing the Chrome setting may make Chrome crash too).

**Comment by ihor-sviziev** [comment]
@stof 
composer.json inside is NOT config for the whole composer, so it's not the same as chrome settings file.

**Comment by stof** [comment]
we need to run the composer.json to initialize the CLI, because plugins can hook into the CLI (registering new commands for instance). Without plugins, we could skip that for many commands.

**Comment by ihor-sviziev** [comment]
@stof
ah, ok, make sense.

But doesn't it mean that if we wasn't able to get list of plugins from composer.json file - we need to behave in the same way as without this file? I think this would be expected result
