### ISSUE TITLE
Strange behavior with PHP 7.1 and magento/composer package.

### ISSUE THREAD

**Issue by hostep** [composer/composer#8370]
## Steps to reproduce

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.9.0
PHP version: 7.1.32
PHP binary path: /opt/local/bin/php71
```

When I run this command (after acquiring credentials at https://marketplace.magento.com):

```
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition:2.2.10 ./71
```

I get the following output:

```
Installing magento/project-community-edition (2.2.10)
  - Installing magento/project-community-edition (2.2.10): Loading from cache
Created project in ./71
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 313 installs, 0 updates, 0 removals
  - Installing magento/magento-composer-installer (0.1.13): Loading from cache

...

  - Installing magento/composer (1.2.0): Loading from cache

...

Writing lock file
Generating autoload files
```

And I expected this to happen:

Version 1.2.2 of `magento/composer` should get installed.

## Further discussion

There is nothing in the `composer.lock` file preventing `magento/composer` version 1.2.2 to be installed:
- `magento/magento2-base`'s require says: `"magento/composer": "~1.2.0",`
- `magento/product-community-edition`'s require says: `"magento/composer": "~1.2.0",`

Running `composer update` results in no updates.
But running `composer require magento/composer:1.2.2` runs without problems and installs version 1.2.2.

Doing the same song and dance using PHP 7.2.23 instead of PHP 7.1.32 immediately gives me version 1.2.2 with the `composer create-project` command.

Difference between versions 1.2.0 and 1.2.2 for completeness sake: https://github.com/magento/composer/compare/1.2.0...1.2.2

And further, after comparing the generated `composer.lock` file from the PHP 7.1 and 7.2 install, I do seem to notice that the source of the package is different. Version 1.2.0 comes from repo.magento.com, while 1.2.2 comes from packagist.org, but that shouldn't cause this behavior I guess ...

<img width="1746" alt="Screenshot 2019-10-10 at 22 09 52" src="https://user-images.githubusercontent.com/85479/66602711-fc37e500-ebaa-11e9-88b0-5ab919256540.png">

Not really sure what is going on here, can't really explain, but feels like a bug, no?

**Comment by alcohol** [comment]
Did you try running

```
composer why magento/composer 1.2.0
composer why-not magento/composer 1.2.2
```

**Comment by alcohol** [comment]
Can't reproduce it myself cause I have no credentials :-(

**Comment by hostep** [comment]
Thanks for trying to look into this @alcohol 

Here's the output of those two commands when running with PHP 7.1:
```bash
$ composer why magento/composer 1.2.0
magento/magento2-base              2.2.10  requires  magento/composer (~1.2.0)
magento/product-community-edition  2.2.10  requires  magento/composer (~1.2.0)

$ composer why-not magento/composer 1.2.2
There is no installed package depending on "magento/composer" in versions not matching 1.2.2
```

So that doesn't really make it more clear unfortunately.

**Comment by stof** [comment]
it looks like the 1.2.0 release comes from repo.magento.com while the 1.2.2 release comes from packagist, according to your composer.lock diff.

Versions coming from a custom repository that you configure are preferred over versions from Packagist (to allow overriding). So here, I think that repo.magento.com is outdated and does not know about the 1.2.2 release yet.

**Comment by alcohol** [comment]
@stof if he has both the magento repository and packagist configured, I thought the magento repository only has precedence for versions that equal or exceed the versions available in packagist. But if packagist has `1.2.2` and the magento repo does not, I do believe the packagist repo should take priority?

**Comment by alcohol** [comment]
@hostep what does this return?

```
composer show magento/composer
```

**Comment by hostep** [comment]
> But if packagist has 1.2.2 and the magento repo does not, I do believe the packagist repo should take priority?

Yeah, that's what I would expect indeed.
But if it is by design, than I could raise the issue with Magento and ask them to publish v1.2.2 on repo.magento.com

Output of `composer show magento/composer`:
```
name     : magento/composer
descrip. : Magento composer library helps to instantiate Composer application and run composer commands.
keywords :
versions : * 1.2.0
type     : library
license  : Open Software License 3.0 (OSL-3.0) (OSI approved) https://spdx.org/licenses/OSL-3.0.html#licenseText
license  : Academic Free License v3.0 (AFL-3.0) (OSI approved) https://spdx.org/licenses/AFL-3.0.html#licenseText
source   : []
dist     : [zip] https://repo.magento.com/archives/magento/composer/magento-composer-1.2.0.0.zip
path     : /Users/me/Downloads/Magento-CE-2.2.10-2019-09-26-09-36-10/vendor/magento/composer
names    : magento/composer

autoload
psr-4
Magento\Composer\ => src

requires
composer/composer 1.4.1
php ~5.5.0|~5.6.0|~7.0.0|~7.1.0
symfony/console ~2.3, !=2.7.0

requires (dev)
phpunit/phpunit 4.1.0
```

**Comment by stof** [comment]
@alcohol no, that was change a long time ago. Repository priority wins over version order now. This avoids having someone publishing a `1.99` release on Packagist for a name matching your internal package and then having your project suddenly switching to the public (potentially malicious) package instead of your internal one. Lower priority repos will be used only if the higher priority repo does not have any acceptable version.

**Comment by hostep** [comment]
Ok, thanks for the info @stof 

I'll ask Magento to publish version 1.2.2 on repo.magento.com then 👍

**Comment by hostep** [comment]
Information has been passed on to Magento and they are investigating as well.

Let me close this ticket, thanks for the feedback!
