### ISSUE TITLE
new install of composer and first require fails using php7.3:  "continue" targeting switch is equivalent to "break"

### ISSUE THREAD

**Issue by Fever905** [composer/composer#8379]
Just downloaded composer for the first time, and trying to install the php-firebase admin panel using:

`composer require kreait/firebase-php ^4.35`

Resulting output:
`Using version ^4.35 for kreait/firebase-php
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)

Installation failed, deleting ./composer.json.

 [ErrorException]
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

require [--dev] [--prefer-source] [--prefer-dist] [--no-plugins] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...`

**Comment by alcohol** [comment]
Please run the command in very verbose mode and then re-submit the command execution + output.

**Comment by Seldaek** [comment]
This has been fixed already, you're using an outdated Composer version. Install latest from https://getcomposer.org
