### ISSUE TITLE
Question: How to semver patch a patch? e.g. use a specific tag

### ISSUE THREAD

**Issue by josephdpurcell** [composer/composer#8381]
## Problem / Motivation

This issues is to help everyone understand what to do when you need to "patch a patch," i.e. insert a tag between two PATCH versions.

Imagine you have a project that has the following versions as tags in the repository:

* `1.0.59` - Includes Features A and B
* `1.0.60` - Includes Features A, B, C, D, E, and F

The `1.0.59` version is deployed to production. The `1.0.60` version is not schedule to go to production for another 5 days and you need a hotfix deployed today. You can't release `1.0.60` because there are features that haven't been QA'd yet, some of them may have bugs. We need to move more quickly.

**How do I tag a release in such a way that composer will accept it and it complies with [semver](https://semver.org/)?**

## Options to Consider

It sounds like there are a few paths that could be taken in theory, let's make the assumption they all require *telling* anyone using the `1.0.59` version to use a specific other version, i.e. no one can just do a composer update to pull in the hotfix in the scenario outlined above.

### Option 1: Claim it's a release management issue.

You could argue that the issue is with the release management process or correct use of version numbers. If `1.0.59` and `1.0.60` are releases of features, why  didn't the *MINOR* version increase? Why are you not tagging a release candidate or pre-release version instead of an actual patch since QA hasn't been completed? This is a long term solution, it doesn't solve the immediate problem of needing to patch a patch.

### Option 2: Semver to support 4 digit versions.

Semver supports only 3 digits, `X.y.z`. Revise the spec to support 4 digit versions. Composer already supports this. So, this is currently a viable option as long as you have nothing preventing you from creating a 4 digit version and you're OK with violating semver. For example, use `1.0.59.1` as the hotfix version.

### Option 3: Use composer patches.

Release a patch file to the `1.0.59` version. Have everyone using the `1.0.59` version  to add this patch to their composer.json file using [composer patches](https://github.com/cweagans/composer-patches).

### Option 4: Composer to support specifying a specific tag.

Composer supports pinning to a specific commit hash *on a branch*. Revise composer to support pinning to a specific tag name. Perhaps this could be achieved by supporting semver build metadata, e.g. `1.0.59+hotfix`.

### Option 5: Create a permanent branch to represent the hotfix.

Create a branch off `1.0.59` like so:

```
git checkout -b  hotfix/foo 1.0.59
```

Have everyone using the `1.0.59` version to use the `hotfix/foo` branch. Never delete the branch.

## Proposed Resolution

TODO: insert recommendation  here.

## Related Information

* [Support letters in version strings #4330](https://github.com/composer/composer/issues/4330) - Makes the point `Build metadata SHOULD be ignored when determining version precedence.` from semver docs, and that build metadata shouldn't be *silently* ignored.
* [Refactoring #13](https://github.com/composer/semver/pull/13#discussion-diff-36172250) - Point that build metadata should be ignored
* [Validate schema name, type and version #8262 ](https://github.com/composer/composer/pull/8262) - Discussion about how 4 digit version numbers are allowed
* [SemverTest.php#L100](https://github.com/composer/semver/blob/master/tests/SemverTest.php#L100) - Shows there are tests for build meta, but no tests for 4 digit version numbers
* [VersionParserTest.php#L56](https://github.com/composer/semver/blob/master/tests/VersionParserTest.php#L56) - Shows normalized versions are parsed to 4 digit versions
* [Allow arbitrary tag names #8071](https://github.com/composer/composer/issues/8071#issuecomment-480192641) - Talks about composer supporting arbitrary patch names, but how determining priority would be unpredictable
* [Possible to reference branch#tag in github? #6206](https://github.com/composer/composer/issues/6206) - You cannot reference a specific tag; and the fact you can reference a specific commit hash is a legacy hack, see [this issue](https://getcomposer.org/doc/articles/troubleshooting.md#i-have-locked-a-dependency-to-a-specific-commit-but-get-unexpected-results-)
* [Handling hotfix versions #241](https://github.com/semver/semver/issues/241) - Discussion about using version suffixes to handle the "patch to a patch" case
* [Supporting multiple versions and backporting fixes that introduce features or break things #532](https://github.com/semver/semver/issues/532) - A conversation about the difficulties of managing multiple versions you need to patch while complying with semver.
* [Discussion: pre-release versioning and PEP440 cross-compatibility #483](https://github.com/semver/semver/issues/483) - A discussion comparing semver with PEP440 which brings up some interesting challenges with versioning to consider

**Comment by phansys** [comment]
How introducing features C, D, E, and F in a *PATCH* version is intended to be compatible with the semantic versioning spec?

**Comment by josephdpurcell** [comment]
I am interested in what the PHP/composer/semver community thinks about which option is most reasonable.

@phansys your comment sounds like a vote for "Option 1: Claim it's a release management issue." For the sake of argument though, what if these are all fixes instead of features? i.e. `1.0.59` is a PATCH and `1.0.60` is a PATCH, but there is a need for a patch to `1.0.59` that needs released *before* `1.0.60`? Option 1 may still be valid, but doesn't offer a short term solution. Say we're in this situation, how would you solve it?

**Comment by josephdpurcell** [comment]
Edited description to clarify Option 1 is long term with no short term solution. Added 2 more reference materials.

**Comment by Seldaek** [comment]
Strictly per semver you would have to release 1.0.60 and then your upcoming 1.0.60 would be pushed to 1.0.61.

With Composer though you may use 1.0.60.1 which is supported, or 1.0.59-patch1 which is also supported. Using build metadata (`1.0.59+patch1`) IMO is not a good idea as this should resolve to the same version as 1.0.59 and thus users won't necessarily update to it.

**Comment by josephdpurcell** [comment]
Thanks for the input, @Seldaek!

I apparently did not properly test using a pre-release. This does work! I'm updating the description to show this as Option 6: Use a pre-release tag. This violates Semver since anything `X.y.z-*` precedes `X.y.z`, but it does work.

I'll also clarify the assumption that it is not possible to re-tag; that certainly would be a fine option if its available.

**Comment by Seldaek** [comment]
It is possible to retag but it is generally speaking poor practice as people having updated before the retag can't easily be sure they are on the right tag, and it can cause other issues with git.

**Comment by josephdpurcell** [comment]
I've added `Option 7: Reference the commit of a build tag. [requires disclaimer]`.

Also, I updated the "Proposed Resolution" section with some opinions.

What I've concluded is: Which option is the best choice is contextual. If I had to pick one, I would go with `Option 2: Use a 4 digit version`. While it violates Semver it has the least risk, least effort, and least confusion.
