### ISSUE TITLE
Probably dead code in src/Composer/DependencyResolver/Decisions.php

### ISSUE THREAD

**Issue by Drupal-Infrastructure** [composer/composer#8383]
I was running the debugger trying to sort out why a packagist.org package is being favored over a path repository, and I accidentally made a dumb assignment on a breakpoint inspection, which triggered this code:

https://github.com/composer/composer/blob/fdcae616b0bdf57b1460491badb4501906a83044/src/Composer/DependencyResolver/Decisions.php#L185-L191

Now, Im going to assume that whole code block is unnecessary, because 

1. `literalToString` is an undefined function. 
2. Its been there for 7 years.  
3. Nobody has reported it or noticed it.

**Comment by ryanaslett** [comment]
Oops. Meant to open this as myself.

**Comment by alcohol** [comment]
@naderman is this a remnant of some debug stuff you use from time to time?

**Comment by naderman** [comment]
@alcohol indeed this is just a piece of debug code which triggers if one makes changes in the wrong place, I guess much like what @ryanaslett did as well ;-) If this actually happened to a user there'd be a bug in the solver, so it makes sense this doesn't usually happen. So I guess the function was never updated, but I'd prefer to keep this section there to catch any potential bugs in this code. The function is simply called "literalToPrettyString" today. It takes an installedmap as an additional argument, but if this isn't available in Decisions you can just pass an empty array and the function will work fine.
