### ISSUE TITLE
Using composer with bitbucket-server

### ISSUE THREAD

**Issue by DemigodCode** [composer/composer#8388]
Is there any way to use bitbucket-server (NOT cloud) using the bitbucket-driver?
I don't want to define each repository in bitbucket as private repository in the composer.json for each package.

Best would be to define the bitbucket-server and each repo is registered automatically.

**Comment by Seldaek** [comment]
Not really no, this is something [Private Packagist](https://packagist.com) helps with as it will sync all your bitbucket server packages into a private repo Composer can then use directly.
