### ISSUE TITLE
Why repositories-dev is not a thing? Is there any alternative?

### ISSUE THREAD

**Issue by TonnyORG** [composer/composer#8391]
There is a real need for `repositories-dev` property or any sort of alternative to it. I've already read #6169 and #2619 but so far I think I have a solid case here (unless you can tell me a workaround for this).

 My `composer.json`:

```json
{
...
    "require": {
        "amazing/package": "*",
        ...
    },
    "repositories": [
        { "type": "path", "url": "../amazing-package" },
    ],
...
}
```

### The use-case

I've a 3 repositories project:
1- Migrations
2- AppA
3- AppB

Both, AppA and AppB share the Migrations project; so no matter what, AppA and AppB can work even together or as standalone projects.

During the development stage, I find easier to use the `path` type as I can have a structure like this:
```
- /
  - app-a/
  - app-b/
  - migrations/
```

That way, I can work on both projects and test all the changes I made to migrations on both projects at the same time (so I can actually what production would look like once I push these changes.

Here is the thing, once I push these changes to production, AppA and AppB are in different places (they don't share the same servers), so I've to go to my composer and change `path` to `vcs` and the url as well. This is kinda annoying because all the commits made during the development process have a record of the composer.json and composer.lock files pointing to `path`; this also represents another "space in my head" to remember myself to actually change the type and url before pushing AppA and AppB to production.

Anyway, so what I am thinking is in this, so when I do run `composer install` for dev then composer reads my "amazing/package" from my local path, but if I append `--no-dev` then it will uses the production instead.
```json
{
...
    "require": {
        "amazing/package": "*",
        ...
    },
    "repositories-dev": [
        { "type": "path", "url": "../amazing-package" }
    ],
    "repositories": [
        { "type": "vcs", "url": "git@somewhere.com/repo.git" }
    ],
...
}
```

I am pretty open to any sort of alternative you guys have in mind to make this happen without the proposed idea. Thank you very much, and I hope to hear from you soon.

I am sorry for my bad English, if something is not clear enough please lmk.

**Comment by alcohol** [comment]
One way to solve this would be using a path repository definition in your global composer configuration on your development environment / machine, and using a vcs repository definition in your global composer configuration on your production environment (note the use of global).

**Comment by Seldaek** [comment]
Then you need to run composer update with --no-dev or not to switch between envs, IMO this doesn't make a ton of sense. The best solution is to use https://packagist.org/packages/franzl/studio IMO
