### ISSUE TITLE
Composer does not see a new release, when the packagist sees it fine

### ISSUE THREAD

**Issue by Eugene-Melbourne** [composer/composer#8392]
I created a new release

    https://packagist.org/packages/eugene-melbourne/laravel-csv-generator#1.9

but comopser refuses to see it.

    $ composer require --ignore-platform-reqs eugene-melbourne/laravel-csv-generator 1.9

>    [InvalidArgumentException]
      Could not find package eugene-melbourne/laravel-csv-generator in a version matching 1.9 

Git has it, packagist sees it.

   $ composer self-update
>    You are already using composer version 1.9.0 (stable channel).

 Ubuntu 18.04.2, php  v7.2.17-1+ubuntu18.04.1+deb.sury.org+3

I tried 

    composer clearcache

it does not help

     composer show -a eugene-melbourne/laravel-csv-generator
> versions : dev-master, 1.4, 1.3, 1.2, 1.1, 1.0

**Comment by Seldaek** [comment]
This has been resolved, we had an issue with the metadata mirroring over the weekend sorry about that.

**Comment by Eugene-Melbourne** [comment]
Thank  you very much

**Comment by Eugene-Melbourne** [comment]
The same problems is back. Mr @Seldaek please help.

**Comment by Eugene-Melbourne** [comment]
Either you fixed it, or it takes 3 minutes to propagate the change.

**Comment by Seldaek** [comment]
Yes changes can take up to a couple minutes to propagate but that's expected.
