### ISSUE TITLE
When does Composer fall back to install a package from packagist.org?

### ISSUE THREAD

**Issue by kiamlaluno** [composer/composer#8396]
I am trying to understand why Composer installs a package from packagist.org when the composer.json file I use lists a very specific repository. I created a new directory, where I put a composer.json file containing the following lines.

```json
{
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    ]
}
```
I run `composer require drupal/root`, which should install a Drupal theme from https://www.drupal.org/project/root (exposed from https://packages.drupal.org/8 as drupal/root), but it instead installs the drupal/root package found on packagist.org (https://packagist.org/packages/drupal/root). When I add a version constraint (for example `composer require drupal/root:~1.0`, the expected package is installed.

When I run `composer show -a drupal/root` from that directory, I get the following output.

```
name     : drupal/root
descrip. : Drupal admin theme for Seeds distribution
keywords : 
versions : dev-master, 8.1.0, 8.0.2, 8.0.1, 8.0.0, 1.x-dev, 1.3.0, 1.2.0, 1.1.0, 1.0.0, 1.0.0-alpha2, dev-1.x
type     : drupal-theme
license  : GNU General Public License v2.0 or later (GPL-2.0+) (OSI approved) https://spdx.org/licenses/GPL-2.0+.html#licenseText
source   : [git] https://git.drupalcode.org/project/root.git bb80d49dd272987bd518942487f1387bfffc611d
dist     : []  
names    : drupal/root

support
source : https://git.drupalcode.org/project/root

requires
drupal/core ~8.0
```
I take the correct package is found on https://packages.drupal.org/8, and it takes the precedence when listed, but for some reasons, it's not the installed package.

If this the expected behavior? If it's expected, when does Composer look back to packagist.org to install a package, even when instructed to use a specific repository?

**Comment by kiamlaluno** [comment]
Thank you for your reply! I guess the only way to force Composer to use the repository set in the composer.json file is requiring a specific version. Did I get it right?

**Comment by Seldaek** [comment]
Composer 2 deals with this better, following https://getcomposer.org/doc/articles/repository-priorities.md
