### ISSUE TITLE
Private repositories - unable to clone, only download from dist

### ISSUE THREAD

**Issue by 6562680** [composer/composer#8402]
My `composer.json`:

```json
{
  "name": "gzhegow/localhost",
  "type": "project",
  "description": "Test",
  "minimum-stability": "dev",
  "prefer-stable": true,
  "license": "MIT",
  "repositories": [
    {
      "type": "gitlab",
      "url": "git@gitlab.com:6562680/support.git"
    }
  ],
  "require": {
    "gzhegow/support": "dev-master"
  },
  "require-dev": {
  },
  "autoload": {
    "psr-4": {
      "App\\": "app/"
    }
  }
}

```

When I run this command:

```
D:\OSPanel\domains\insta.loc>composer diagnose
```

I get the following output:

```
D:\OSPanel\domains\insta.loc>composer diagnose
Checking composer.json: WARNING
require.gzhegow/support : unbound version constraints (dev-master) should be avoided
semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 1.9.0
PHP version: 7.3.9
PHP binary path: D:\OSPanel\modules\php\PHP_7.3-x64\php.exe

```

And I expected this to happen:
OS: Win10
```
Installing gzhegow/support (dev-master 7bf9f3f): Cloning 7bf9f3fbf3

Failed to download gzhegow/support from source: Failed to execute git clone --no-checkout "git@gitlab.com:6562680/
support.git" "D:\OSPanel\domains\insta.loc\vendor\gzhegow\support" && cd /D "D:\OSPanel\domains\insta.loc\vendor\gzheg
ow\support" && git remote add composer "git@gitlab.com:6562680/support.git" && git fetch composer

Now trying to download from dist
Installing gzhegow/support (dev-master 7bf9f3f): Downloading (100%)
```

**I launched command directly and get error "directory's not empty"**

_Seems like git is unable to put the files of new clone (dev-master always clone instead of pull by some reason) in directory where still disposed ".git" folder or something_

**Comment by 6562680** [comment]
What? Is it support?
Where is the support?

Seems like a hardcoded bug in composer.phar

**Comment by KminekMatej** [comment]
We've been dealing with the same thing. I found the bug. Here is the problematic line:

https://github.com/composer/composer/blob/557fb873ee10c413bbd86d8c820c063c2b871a43/src/Composer/Util/Git.php#L168

This parses gitlab url into _$match_ variable, but **cuts off the .git extension**. Ouput url then looks like:
> https://oauth2:***@gitlab.com/boostspace/api/category

See? Should be 

> https://oauth2:***@gitlab.com/boostspace/api/category.git

After getting this url, gitlab responds with 404 (logically). Possible solution is to update the regex to:
`{^(git)@' . self::getGitLabDomainsRegex($this->config) . ':(.+?)$}i`

However, I noticed that you are cutting the .git extension also from bitbucket urls, so I believe there is some reason why to cut it - maybe just Gitlab cant swallot the url without the extension?

**Comment by KminekMatej** [comment]
After deeper investigation, I found out that the bug was pretty simple - .git extension is always being cut using preg_match, but in bitbucket section it gets appended into final $authUrl string, but in gitlab section is just popped out (common typo I guess). Its now imho correctly solved and pull-request is waiting.

**Comment by Seldaek** [comment]
As a workaround I believe using `https://gitlab.com/6562680/support.git` as URL should work.

**Comment by KminekMatej** [comment]
I believe urls starting with `https://` gets automatically converted into `git://` adresses in the first place, so this workaround wont actually work.
