### ISSUE TITLE
1.10-dev is being distributed from link instead of 1.9.1

### ISSUE THREAD

**Issue by mbarnesBHR** [composer/composer#8405]
https://getcomposer.org/composer.phar
link is set to download Composer version 1.10-dev (1.10-dev+4e4c38795a0814db2b9222871a63714f674fd1d9) 2019-11-01 16:29:20

The download link shows that it should be Composer version 1.9.1 2019-11-01 17:20:17. Is this on purpose that we are installing the dev version of composer?

**Comment by alcohol** [comment]
That link is for the **latest snapshot** version of Composer, which is indeed `1.10-dev`. If you want the latest stable release, simply use the link for 1.9.1 on https://getcomposer.org/download/.
