### ISSUE TITLE
composer.json type property became case sensitive in 1.9.1?

### ISSUE THREAD

**Issue by chris-kruining** [composer/composer#8411]
$ composer install
                                                              
  [Composer\Json\JsonValidationException]                     
  "./composer.json" does not match the expected JSON schema:  
   - type : Does not match the regex pattern ^[a-z0-9-]+$     
                                                              
The command "composer install" failed and exited with 1 during .

with the following json

```json
{
    "name": "chris-kruining/utilities",
    "type": "Utilities",
    "description": "Utilities for PHP 7.1^",
    "keywords": ["Utilities","PHP"],
    "homepage": "https://github.com/chris-kruining/utilities",
    "license": "GPL-3.0-or-later",
    "authors": [
        {
            "name": "Chris Kruining",
            "email": "chris@kruining.eu",
            "homepage": "https://github.com/chris-kruining",
            "role": "Developer"
        }
    ],
    "require": {
        "php": ">=7.1.0",
        "psr/container": "1.0.0",
        "nesbot/carbon": "2.25.3",
        "composer/composer": "1.9.1"
    },
    "require-dev": {
        "phpunit/phpunit": "8.4.0",
        "phpspec/phpspec": "6.0.0",
        "php-coveralls/php-coveralls": "2.1.0"
    },
    "provide": {
        "psr/container-implementation": "1.0"
    },
    "config": {
      "bin-dir": "bin"
    },
    "autoload": {
        "psr-4": {
            "CPB\\Utilities\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "spec\\": "spec/"
        }
    }
}
```

I've had this config with a capital 'U' for as long as I can remember. Is this an issue or is it deliberate?

**Comment by alcohol** [comment]
Commits show this was indeed changed. Before there was no validation at all. Your type is not one of the four supported types officially (though extensions/plugins can add support for additional types here). See documentation at https://getcomposer.org/doc/04-schema.md#type

**Comment by alcohol** [comment]
@Seldaek any specific reason you can think of that this was made case-sensitive?

**Comment by stof** [comment]
I don't think that the change was about making this case-sensitive, but about making this following a strict pattern rather than being free-form. Even if we were allowing capital letters in the schema, the change would still render some other values invalid (accents, emojis, etc...)

**Comment by chris-kruining** [comment]
> I don't think that the change was about making this case-sensitive, but about making this following a strict pattern rather than being free-form. Even if we were allowing capital letters in the schema, the change would still render some other values invalid (accents, emojis, etc...)

Ergo, it is deliberate and I should fix my json conf?

**Comment by Seldaek** [comment]
Please update to lowercase, and generally speaking I'd say refrain from defining random types like Utilities which have no meaning. The type is meant for installers to know how the package should be installed, and all the known types are lowercased strings following `^[a-z0-9-]+$`. There is really no reason to define the type property otherwise. See https://getcomposer.org/doc/04-schema.md#type

**Comment by chris-kruining** [comment]
Ok, will do. Thanks!

**Comment by EnoahNetzach** [comment]
Shouldn't this be a breaking change?

As per __1.9.0__ there is a warning:
```
Deprecation warning: Your package name .Cleafy Web Dashboard is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.
```

Suddenly all the builds are breaking for no discernible reason..

**Comment by EnoahNetzach** [comment]
Shouldn't this be a breaking change?

As per 1.9.0 there is a warning:
```
Deprecation warning: Your package name[...] is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.
```

Suddenly all the builds are breaking for no discernible reason..

**Comment by alcohol** [comment]
The name field validation was introduced quite a while ago. This issue is regarding the type field validation. Please do not mix up the two of them in the same issue.

**Comment by Seldaek** [comment]
Also the name validation is just a warning so I doubt it's breaking your builds.. You should fix it though before it does.
