### ISSUE TITLE
Show license besides version when running composer info

### ISSUE THREAD

**Issue by dingo-d** [composer/composer#8416]
This is more of a feature request than an issue. Would it be possible to show license information when one runs `composer info`?

Like

```bash
composer info

guzzlehttp/guzzle      6.4.1    MIT       Guzzle is a PHP HTTP client library
guzzlehttp/promises    v1.3.1   MIT       Guzzle promises library
...
```

**Comment by Seldaek** [comment]
There is the `composer license` command already for exactly this purpose. I'd rather keep the output short on `composer show`.

**Comment by dingo-d** [comment]
Wasn't aware of that command, thanks! This will help me out a lot 🙂
