### ISSUE TITLE
Invalid Repository Exception—No Valid Bower.json

### ISSUE THREAD

**Issue by charlieartist** [composer/composer#8427]
I had recently updated to Composer v.1.9.1, and most operations after the update ran without issue.

A few days ago, though, I was getting responses such as this, even when using `composer update [some project]` on unrelated projects:

`  [Composer\Repository\InvalidRepositoryException]                             
  No valid bower.json was found in any branch or tag of [URL to project repository], could not load a package from it.  `

In addition, I would also get PHP memory limit errors when running Composer commands, which I hadn't experienced before.

Naturally, I did a `git reset` and `composer clearcache`,  but the same issue would present itself again. I checked the flagged repo, where a valid bower.json existed, and had worked fine—where some projects had run without issue for over a year. 

To validate if this was specific to one linked project or to other reasons, I ran `composer update [some project]` on other builds, where the Invalid Repository Exception would be flagged for another project, which may have worked fine in another build.

To deal with this, I ran `composer self-update --rollback`, which rolled back to v.1.8.6. After running `composer clearcache`, the updates on all projects ran without issue.

OS: macOS 10.15.1 (Catalina)

**Comment by alcohol** [comment]
Composer does not need any `bower.json`. Most likely you have a plugin installed that depends on this. Not a Composer issue though.

**Comment by charlieartist** [comment]
The issue cropped up with v.1.9.1. It appeared to be searching through the bower.json files of every project in the vendor directory. v.1.8.6 doesn't do this. 

If this were due to a plugin, would it not have also presented the same error in v.1.9.1?

**Comment by alcohol** [comment]
I don't understand what vagrant plugins have to do with globally installed composer plugins.

**Comment by alcohol** [comment]
If you run `composer update --no-plugins` you will see that things work as expected without plugins.
