### ISSUE TITLE
[feature-request] showing potential upgrades that are being left out by outdated dependencies

### ISSUE THREAD

**Issue by CytoDev** [composer/composer#8428]
Hey Team,

I have been running into this issue lately wherein I am updating my dependencies and I know that I should be able to upgrade a certain package to version `x.y.z` but composer seems to silently (-vvv shows why) ignore this upgrade.

The steps to re-create this issue are quite simple:
 - create a package that requires another package at version `^1.0.0`

 - create a second package that requires the first package
 - require the first package into the second with the same constraint (`^1.0.0`)
 - _package is updated to 1.2.3_
 - update the first package by changing the composer requirements to a stricter `1.0.*`
 - _package is denied the 1.1.x and is locked at 1.0.x_
 - call `composer update` on the second package

This issue _could_ be easily resolved by deleting the lock file, or editing it to remove the strict constraint, but ideally this would be a no-go.

My suggestion:
The output on why this or that package could not be upgraded is already present in the very verbose option, but this should (ideally) also trigger a warning on the regular execution.

I'd love to hear some feedback on this idea!

**Comment by alcohol** [comment]
I think `composer why-not package 1.2.3` already does this.
