### ISSUE TITLE
Multiple composer files in a project, but not merged

### ISSUE THREAD

**Issue by Loguercio** [composer/composer#8429]
What we're trying to accomplish is to have multiple composer files in our multisite Drupal project.

What we would like is that there would be a main composer file that would install drupal core and all the most common modules, and then each site would have its own composer file that would install just the contrib modules that that particular site needs. 

The problem is that the individual site's composer files try to reinstall everything again as drupal core is a requirement for every contrib module.

Is there a way to tell composer what's already installed on the system, so that it can just install what's missing?

Thanks

**Comment by alcohol** [comment]
As far as I can tell (your description is a little bit vague as to what you actually want), your use-case is not supported.

**Comment by Seldaek** [comment]
You might be able to abuse `"provide": {"drupal/core": "..."}` in the sites composer files, but that'll be manual work to maintain the version you provide, and might result in a mess. I wouldn't really advise for it, rather install every site independently and have duplicate stuff installed IMO.
