### ISSUE TITLE
Modify the third-party library of composer to customize git without changing its name

### ISSUE THREAD

**Issue by 957651480** [composer/composer#8430]
Modify the third-party library of composer how to implement composer without changing its name. Do you support package alias or package mapping instead of building a private library of composer.
{
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/yangtaihua/streams-platform.git"
        },
    ],
    "require": {
        "anomaly/streams-platform": "^1.7",
    },
}

I hope "anomaly / streams platform" can't read the above version library at all, because one is "anomaly" and the other is "yangtaihua", because "anomaly" on GitHub has been registered for a long time

**Comment by stof** [comment]
repo URLs are totally independent from the package name. The package name comes from what you have in the composer.json file inside the repo (in the master branch)
