### ISSUE TITLE
Replacing dependency with custom one, how to update it's dependencies?

### ISSUE THREAD

**Issue by ghost** [composer/composer#8434]
We are building a custom module that replaces a core module (this is in Magento 2)

The core module defines a dependency on a 3rd party SDK and locks it to the x.y.z version number.

We need to be able to update this SDK to a new major release.

Our custom module composer.json file uses the "replace" section to remove the core module and put ours in its place, and in the current setup, we are also removing the 3rd party SDK by using "replace" as well.

The issue is, even if we use an alias to add the SDK via the "require" section eg

```
"require": {
    "third_party/sdk": "2.0.0 as 1.0.0"
}
```

Because the SDK is in the lock file, it will not be updated.

I tried using the `--update-with-dependencies` flag but that didn't help.

Can I possibly use "replace" with an alias?

**Comment by alcohol** [comment]
Needs a clearer description of the issue (missing `composer.json` - or multiple even, unclear).

**Comment by paul-gene** [comment]
@alcohol apologies, it's tricky to explain.

Basically, Framework X required Package A which requires Package B set to version 1.0.0

We are replacing Package A, but need to use Package B v2.0.0

We cannot set an alias in our Package A, as the Package B version is set in the lock file.

Our current method involves using `replace: "package_b":"*"` and including Package B inside our Package A, using composers autoloading to handle the loading of Package B.

What's interesting, is though this method works, using an alias to "fool" the dependencies doesn't.
