### ISSUE TITLE
Can't find the autoload command

### ISSUE THREAD

**Issue by CJDennis** [composer/composer#8443]
I can't find the Composer command to add `"autoload": { "psr-4": {"Namespace\\ProjectToAdd\\": "src/Namespace/ProjectToAdd/"} }` and `"autoload-dev": { "psr-4": {"Namespace\\ProjectToAdd\\": "src/Namespace/ProjectToAdd/"} }` to `composer.json`. I always have to edit `composer.json` directly which I know you're not supposed to do.

i.e. to add a requirement you don't edit `composer.json`, you say `composer require namespace/project-to-add` with an optional `--dev` flag.

I've tried `composer autoload Namespace\ProjectToAdd src/Namespace/ProjectToAdd`, but obviously it just gives an error saying `Command "autoload" is not defined.`

Once the sections have been added manually, `composer dump-autoload` does work as it should, I'm just missing the bit in the middle to get those sections there in the first place.

I've also tried `composer list` but I can't see the command.

What's the command to add these sections?

**Comment by alcohol** [comment]
> I always have to edit composer.json directly which I know you're not supposed to do.

Says who?

> to add a requirement you don't edit composer.json, you say composer require

Editing the file manually is just as much a valid option as using the `require` command.

> What's the command to add these sections?

There is no such command. You have to manually write/edit them in your composer.json file.
