### ISSUE TITLE
When run script, do not echo/output the script name

### ISSUE THREAD

**Issue by matmartigan17** [composer/composer#8447]
My `composer.json`:

```json
...  "scripts": {
    "pre-autoload-dump": "Ox\\Core\\Composer\\CComposerScript::preAutoloadDump"
}
```

Output of `composer diagnose`:

```
...> Ox\Core\Composer\CComposerScript::postAutoloadDump
```
How to do not display the script name ?

**Comment by alcohol** [comment]
As far as I know, you cannot, unless you use the `--quiet` flag.

**Comment by matmartigan17** [comment]
thank you, but with the flag --quiet you escape all ouptut y jsute want ignore command line name outpu like this :


> Ox\Core\Composer\CComposerScript::preAutoloadDump [remove]
openxtrem/mediboard: Lorem...
> Ox\Core\Composer\CComposerScript::postAutoloadDump [remove]
openxtrem/mediboard: Lorem...
openxtrem/mediboard: Lorem...

**Comment by alcohol** [comment]
That is not possible.
