### ISSUE TITLE
Feature request: composer require --repository

### ISSUE THREAD

**Issue by alexander-schranz** [composer/composer#8448]
It would be create to add forks  and other libraries as requirement with the same syntax as you can create projects over create-project with --repository.

```
composer require custom/bundle:^1.0 --repository='{"type": "git", "url": "git@gitlab.com:custom/budnle.git"}'
```

And I expected this to happen:

```
    "repositories": [
        {
            "type": "git",
            "url": "git@gitlab.com:custom/bundle.git"
        }
    ],
    "require": {
           "custom/bundle": "^1.0"
    }
```

**Comment by alcohol** [comment]
Seems like added complexity though for an edge-case scenario that you can already achieve as wel by calling the `composer config` command first and then running your `composer require` command.

**Comment by alexander-schranz** [comment]
@alcohol didn't know that the config command can add repositories. Thx for the fast response 👍
