### ISSUE TITLE
Generate a runtime platform version check in the autoloader

### ISSUE THREAD

**Issue by naderman** [composer/composer#8451]
Users often execute composer install with a different version of PHP than the version they execute the resulting code with. This can of course lead to problems and it would help if the generated autoloader verified a compatible PHP version is actually used. This is based on the idea implemented in flex: https://github.com/symfony/flex/pull/576

Using either https://github.com/composer/semver/issues/71 or https://github.com/composer/semver/issues/72 a check for PHP should be compiled into the autoload file which verifies that the PHP version used is compatible with all packages present in the composer.lock file which was used to install/generate the autoloader.

We could expand this to other platform packages like extensions, but we need to consider the runtime performance overhead of such a check which means we should probably add an option to dump-autoload to skip this check if we do more than a simple if for the PHP version.

**Comment by nicolas-grekas** [comment]
About the runtime overhead:  if we're careful enough to generate code that opcache is able to resolve at compile, it might be a free check.

**Comment by cebe** [comment]
@Seldaek why did you close this? is it solved or did you decide to not add it?

**Comment by Seldaek** [comment]
Ah I figured the PR was linking to this sorry.. It was done in https://github.com/composer/composer/pull/8546
