### ISSUE TITLE
composer config -g --absolute -- bin-dir shows wrong path

### ISSUE THREAD

**Issue by cjunge-work** [composer/composer#8452]
I am running Xubuntu 19.10.

Output of `composer diagnose`:

```
$ composer global diagnose
Changed current directory to /home/cameron/.config/composer
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.9.1
PHP version: 7.3.11
PHP binary path: /usr/bin/php7.3
```

When I run this command:

```
$ composer config -g --absolute -- bin-dir
```

I get the following output:

```
/home/cameron/vendor/bin
```

And I expected this to happen:
```/home/cameron/.config/composer/vendor/bin```

If I run
```
$ composer global config --absolute -- bin-dir
```

I get the expected output.

The help for `composer config` says:
```
 -g, --global                   Apply command to the global config file
```

**Comment by alcohol** [comment]
Can you provide the contents of `/home/cameron/.config/composer/composer.json` ?

**Comment by Seldaek** [comment]
Note that the global config accessible through `config -g` (this config applies to all composer runs, it's the user level config) is not the same as running `composer global config` (this config is the local config of the `composer global` "project". That's most likely the reason for your problem. To be fair this is slightly confusing and could be better documented I assume, if you want to PR something that would have helped you that'd be welcome.
