### ISSUE TITLE
Question: Deprecation notice psr-4 autoloading

### ISSUE THREAD

**Issue by icanhazstring** [composer/composer#8465]
Hi there.

After updating composer to `1.10-dev` we receive a lot of deprecation notices that our classes does not comply the psr-4 autoloading standard.

And this is just a question on how to solve a huge load of these notices and still keep the optimized classmap alive. So couple of problems on how to solve them:

1. `Deprecation Notice: Class framework\api\api_interface located in ./includes/framework/api/api.interface.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v1.11+. in phar:///usr/local/bin/c
omposer/src/Composer/Autoload/ClassMapGenerator.php:185`

2. `Deprecation Notice: Class ZZV\ExternalApi\SSOEndpoint\Test\Functional\Handler\Bootstrap\HandlerFeatureContextTest located in ./module/ExternalApi/SSOEndpoint/tests/Functional/Handler/bootstrap/HandlerFeatureContextTest.php does not
comply with psr-4 autoloading standard. It will not autoload anymore in Composer v1.11+. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185`

3. `Deprecation Notice: Class Prefix\BusinessDomain\Lead\Document\Pipeline\ListDocumentsPayload located in ./module/BusinessDomain/Lead/src/DocumentImport/Pipeline/ListDocumentsPayload.php does not comply with psr-4 autoloading standard. I
t will not autoload anymore in Composer v1.11+. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185`

---
Now to my conclusion, just to see if they are correct and how to solve them:

1. I'd recon that this is because the class name is `api_interfance` and the file is `api.interface.php` where it should be `api_interface.php`?

2. Is there a problem between `SSOEndpoint\Test` and the path `SSOEndpoint/tests`? Should the path be `SSOEndpoint/test`? Or what is the solution here? 

3. Also most the same. Here the path seems to be the problem, but the namespace (configuration in composer.json) points directly into this src directory `Prefix\BusinessDomain\Lead` points to `module/BusinessDomain/Lead/src`.

Now how to solve those issues an where is the specific violation on the psr-4 standard?
Also how can I provide an optimized classmap for legacy code files like in point 1. ?

**Comment by alcohol** [comment]
Burn it all :fire: 

But eh, you're not obligated to update your composer binary. If having proper filenames and/or classnames is too much of a hassle in your legacy project, I recommend you hard-commit an older version of the composer binary in your repository to ensure you don't run into issues in the future.

1) correct
2) case-sensitivity could be one issue, another is that test and tests are not equal (one is plural, one is not)
3) psr4 allows you alias namespaces to specific directories, so i don't see an immediate issue with that. you just have to make sure the files inside `module/BusinessDomain/Lead/src` all contain classes in the namespace `Prefix\BusinessDomain\Lead`.

**Comment by icanhazstring** [comment]
Thanks for quick response.

1. Is there a documented way to also add "non psr-4 standard" files into the classmap (coz next composer version won't do)? I didn't find any way to do that. So for example für 1. we have a custom autoloader which does the loading.

2. Ok, will try and see if that makes a difference. In any other way, there is probably no need to optimize autoloading for test cases. So `exclude-from-classmap` here is probably the best solution.

3. Ok now saw the problem. There is a difference in namespace and folder, Namespace points do `Document` path points on `DocumentImport`

   So these problem happen quite often, which seems to be problem with paths and namings, so thats that "solved" ;)

**Comment by alcohol** [comment]
Instead of using psr-4 or psr-0 autoload definitions, you can use https://getcomposer.org/doc/04-schema.md#classmap definition I think? Not really sure since you never included your composer.json so I am not aware of what you are currently using.

**Comment by icanhazstring** [comment]
```
...
  "autoload": {
    "files": [
      "includes/framework/functions.inc.php",
      "includes/funcs.inc.php",
      "includes/framework/dataobject.class.php"
    ],
    "classmap": [
      "includes/libraries",
      "modules/api"
    ],
    "psr-0": {
      "deploy": "deploy",
      "behat": "behat",
      "bin": "bin"
    },
    "psr-4": {
      "vv\\": "includes/vv",
      "framework\\": "includes/framework",
      "modules\\": "modules",
      "Prefix\\BusinessDomain\\Lead\\": "module/BusinessDomain/Lead/src",
      ...
    }
  },
...
```

Currently looks like this. So there is probably just all.
So what you suggest is: move legacy classes from `psr-4` to classmap and leave em there correct?

**Comment by stof** [comment]
if you cannot make your code structure valid against PSR-4, using `classmap` is indeed what you should do.
Note that your autoloading works in older composer versions only if dumping an optimized autoloader (due to the fact that the optimized classmap was not enforcing the PSR-4 rules for class registered as being autoloaded by PSR-4). so thinks are working currently either because you always optimize the autoloader (and then, you should switch to `classmap` for these legacy classes) or because you don't actually relying on autoloading these classes (which might be the case for phpunit tests), in which case a solution could also be to remove the autoloading config entirely.

**Comment by icanhazstring** [comment]
Alright. Sounds good and answers my questions. Thanks for clarification :)
