### ISSUE TITLE
Choco install composer failing

### ISSUE THREAD

**Issue by dking3876** [composer/composer#8470]
As of dec 5, install was working but had been updated and using php 7.4. as of dec 6. the install now installs 7.2.15 and fails right after attempt o install  'chocolatey-core.extension (� 1.3.3)'

Failure notice is  Unable to resolve dependency 'chocolatey-core.extension (� 1.3.3)'

**Comment by johnstevenson** [comment]
@dking3876 Can you report this here please: https://github.com/composer/windows-setup/issues
