### ISSUE TITLE
Wrong deprecation warning

### ISSUE THREAD

**Issue by i--storm** [composer/composer#8472]
My `composer.json`:

"repositories": [
        {
            "url": "https://github.com/i--storm/AvalancheImagineBundle.git",
            "type": "git"
        }
]
...
"require": {
    "i--storm/avalanche-imagine-bundle": "~2.2.4"
}

When I run this command:

composer.phar update

I get the following output:

Deprecation warning: require.i--storm/avalanche-imagine-bundle is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a
-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.

And I expected this to happen:

"i--storm" is valid github repository vendor name, but it does not match regexp and I get warning and error in future versions

**Comment by Seldaek** [comment]
The problem is this is invalid according to our package naming guidelines: https://github.com/i--storm/AvalancheImagineBundle/blob/develop/composer.json#L2 - the repo name can contain -- yes but that's something else than the package's name.
