### ISSUE TITLE
--no-dev should ignore require-dev (or add new option)

### ISSUE THREAD

**Issue by ScreamingDev** [composer/composer#8474]
My `composer.json`:

```json
{
  "require-dev": {
    "php-mime-mail-parser/php-mime-mail-parser": "*"
  }
}
```

When I run this command:

```
composer install --no-dev
```

I get the following output:

```
  Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.  
```

And I expected this to happen:

Ignore "require-dev".

--- 

Our workflow: 

1. "require-dev" is for developers and developing things.
2. "require" is meant for the production system
3. composer.lock will never ever go in the repo

Why the last? Because packages change on a daily basis. We have 6 Merge-Requests in 1 Project per day. Having composer.lock in the repo would mean:

1. 6 times commit the lock file, push and create a merge request
2. Quality assurance / Review comes around and approves the FIRST merge request.
3. Merge-Request is merged
4. The 5 other Merge-Request run in merge-conflicts
5. Five developer get informed and at least one needs to fix this.
6. Starting all over with step 2

So for 6 MR per day we have 11 to 21 hands on just because of the composer.lock . As we got rid of it was like:

1. 6 new merge requests incoming
2. Quality assurance / Review comes around and approves ALL merge request.
3. Merge-Request are merged , we have a new release.

Please make "composer install --no-dev" ignore the "require-dev" part of show up some alternative flow near to the above for covering the problem. Otherwise the above mentioned example JSON could not be deployed (because the production server does not have "ext-mailparse").

**Comment by alcohol** [comment]
Please search our issue list, this behaviour is not changing for reasons already mentioned.

**Comment by ScreamingDev** [comment]
Just looked into 200 issues + almost 30 before opening this. None of them mentioned it.

**Comment by alcohol** [comment]
Dev requirements are always taken into consideration when **resolving** dependencies. The `--no-dev` flag merely does not install them.

**Comment by grappler** [comment]
Related Issue: https://github.com/composer/composer/issues/6575

**Comment by ScreamingDev** [comment]
Please explain this to me.
It doesn't take much to come up with several cases where this will harm the customers / production systems.
Here is one (just one out of the bunch): Imagine installing roave-security which nags about a dev-requirement. This won't be installed on production but still the prod is not deployable now.

I see no sense at all to take require-dev into account when running --no-dev.

**Comment by grappler** [comment]
A specific use case I am struggling with:

I would like to run PHPUnit tests in PHP 5.6 🙈. The coding standards library (dev-dependency) requires PHP 7.1 to run but it is will not be used in Production so the my package is still PHP 5.6 compatable.

A workaround that I am using is to uninstall the coding standards library before running composer install in GitHub actions.

**Comment by olleharstedt** [comment]
Similar issue here, wanting to use modern tools to analyze the code even if production server is old.

Any workarounds?

```json
{
    "require": {
        "php": "7.0.33",
        "neam/php-sie": "3.3.3.1"
    },
    "require-dev": {
        "php": ">=7.4",
        "phpstan/phpstan": "^1.10"
    }
}
```

**Comment by stof** [comment]
`composer install` is meant to install from lock. So `composer install --no-dev` **cannot** ignore require-dev to resolve dependencies, because it has to use the already resolved dependencies as well.
And `composer update` always resolves dev dependencies because the composer.lock has to take them into account (to be usable with a `composer install` command that does not use the `--no-dev` flag).

One workaround is to use https://packagist.org/packages/bamarni/composer-bin-plugin to install your tooling that is not compatible with your main requirement, allowing to resolve dependencies of the project in a way supporting your target PHP versions while having some tooling supporting only more modern versions. This is what I use in the 1.x branch of [scssphp](https://github.com/scssphp/scssphp/tree/1.x) for that exact reason.

**Comment by olleharstedt** [comment]
Thanks for the feedback! I'm just using two separate composer.json files for now. Thankfully this issue is only in one of our older branches.
