### ISSUE TITLE
OpenShift Assembly / Composer / file could not be downloaded SSL Connection reset by peer

### ISSUE THREAD

**Issue by abenbrahim78** [composer/composer#8480]
I encounter this problem with composer 1.9.1, during assembly S2I under openshift.

Using docker-registry.default.svc:5000/openshift/composer-s2i@sha256:aace56f51cc136ad7430896bfd18d12aac052acc29c16c1b8451498fba8315a4 as the s2i builder image
---> Installing application source...
Found 'composer.json', installing dependencies using composer.phar...
Downloading https://getcomposer.org/installer , attempt 1/6
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100  267k  100  267k    0     0   751k      0 --:--:-- --:--:-- --:--:--  754k
All settings correct for using Composer
Downloading...
The "https://getcomposer.org/versions " file could not be downloaded: SSL: Connection reset by peer
Failed to enable crypto
failed to open stream: operation failed
Retrying...

**composer diagnose**
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: ....
Dev Public Key Fingerprint: ....
OK
Checking composer version: OK
Composer version: 1.9.1
PHP version: 7.0.27
PHP binary path: /opt/rh/rh-php70/root/usr/bin/php

Thank you for your support.

**Comment by stof** [comment]
Which image build are you talking about ?

**Comment by abenbrahim78** [comment]
From a Docker image to an S2I image (source to image).

**Comment by alcohol** [comment]
Looks like your builder does not have a proper openssl/certificates setup.

**Comment by abenbrahim78** [comment]
Hello,

My problem was corrected in 

https://github.com/composer/getcomposer.org/commit/0659b45afd64e9fcda2fcc620762e23de326acbd

Thank you !
