### ISSUE TITLE
composer-setup.exe identified as known malware via Carbon Black

### ISSUE THREAD

**Issue by rmaly** [composer/composer#8482]
Associates in network are flagged when working with composer-setup.exe SHA 6a0b75feaf3823a1054274a362bdd92b9687b265c0f0ff782741853c7995cdd8 as Known Malware via the networks Carbon Black protections.

**Comment by johnstevenson** [comment]
Obviously we haven't included any malware in this. It does use the latest version of Inno Setup (6.03), so perhaps this explains the false positive.

Source code: https://github.com/composer/windows-setup

**Comment by johnstevenson** [comment]
https://www.virustotal.com/gui/file/6a0b75feaf3823a1054274a362bdd92b9687b265c0f0ff782741853c7995cdd8/detection

Nothing is detected on VirusTotal now (having initially shown 5 false-positives, which is much more than the usual none or one).
