### ISSUE TITLE
JsonValidationException when using `dev-master` as the version of a package.

### ISSUE THREAD

**Issue by rtheunissen** [composer/composer#8483]
We are using `"version": "dev-master"` to ensure that `path` repositories always install as `dev-master`. Recently, after upgrading to 1.9.1, we're seeing this error:

```
[Composer\Json\JsonValidationException]
"./composer.json" does not match the expected JSON schema:
 - version : Does not match the regex pattern ^v?\d+(((\.\d+)?\.\d+)?\.\d+)?
```

**Comment by alcohol** [comment]
That's because your "solution" to a "problem" is not the right one. It just appears to work for reasons unrelated. Path repositories could benefit from better documentation perhaps. You should not hardcode any version in your composer.json honestly, but if you do hardcode one, it should be an actual version.

**Comment by rtheunissen** [comment]
> That's because your "solution" to a "problem" is not the right one.

The "problem" is valid, so what would be the correct solution?

> You should not hardcode any version in your composer.json honestly, but if you do hardcode one, it should be an actual version.

So the definition of an "actual version" is different for "version" and the version constraints you can set per package? Because `dev-master` is considered a valid version there. 

---

This worked as expected in 1.9.0 and breaks in 1.9.1 - we are not hacking the API in any way, and we believe our understanding of a "version" is valid. We see no reason why the regex that defines a valid version at the root level should be restricted to numeric versioning, because other version constraints do not apply that same rule.

---
Coming back to the problem at hand: we have an application that contains multiple packages within it, and each of these package has its own composer.json file to be able to define the dependencies, scripts, etc at the package level. It's all one big repository though.

The container's composer.json defines a single path repository to `packages/*`, which works very well without the need to publish each of those packages or go to VCS (it's all the same repository). The documentation even states that:

> This can be especially useful when dealing with monolithic repositories

Great, that's perfect. However, we all work on feature branches, for example `feature-1`. This results in versions like `dev-feature-1` in the lock file because of the branch we're currently on. When someone else then tries to install without that branch available, it breaks. Our goal is to always install these packages as `dev-master` so that it doesn't matter what branch you're on (because the packages are part of the same revision anyway). 

Our solution to this was to set an explicit `dev-master` version in each package and install them as `dev-master` in the container. This worked perfectly until someone updated to 1.9.1.

We are open to a better solution to this problem - this issue has not yet been resolved.

**Comment by rtheunissen** [comment]
> If the package is a local VCS repository, the version may be inferred by the branch or tag that is currently checked out. **Otherwise, the version should be explicitly defined in the package's composer.json** file. If the version cannot be resolved by these means, it is assumed to be **dev-master**.

The documentation implies that what we're trying to do is perfectly valid. Otherwise we'd have to `1.0.0` everything arbitrarily which implies that our packages are versioned individually, which they are not. 

Our opinion is that the regex is too restrictive and contradicts the documentation.

**Comment by Seldaek** [comment]
I have fixed this already in https://github.com/composer/composer/commit/b6673612e0d27424a2e35d500776e89a10e4f806 - make sure you use `composer self-update --snapshot` until it's in a tagged release.

**Comment by kolumnin** [comment]
My output screen either vanish or quickly relocate, before I release anything. My eyes are strained. I could follow the procedures instructed at my local folder but can't perform with the touch screen and remote unknown mouse.

**Comment by kolumnin** [comment]
I can only delete the composer folder and recover if needed later from the zip file saved.
I can't converse at programer level and sorry for the inconveniences.

**Comment by pdelre** [comment]
Glad to see this getting resolved. We came to the same solution as @rtheunissen for a monorepo. I had originally done a write-up with detailing some data and a reproduction script. If anyone here is interested for current or future discussions, here is the gist: https://gist.github.com/pdelre/e3425208e525af9711e5f74e53f64ae5

**Comment by jhicks-ddm** [comment]
I get the same error even after updating composer using the latest snapshot. Here is my composer version: ```Composer version 1.10-dev (1.10-dev+6034c2af01e264652a060e57f1e0288b4038a31a) 2019-12-22 11:46:13```

**Comment by Seldaek** [comment]
@jhicks-ddm The regex pattern shown seems outdated so I wonder if you're really running it using the right composer.phar?
