### ISSUE TITLE
Composer hangs during installation

### ISSUE THREAD

**Issue by IchHabRecht** [composer/composer#8486]
My `composer.json`:

```json
{
    "require": {
        "typo3/cms": "7.x-dev"
    },
    "require-dev": {
        "nimut/phpunit-merger": "0.3.2"
    }
}

```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.typo3/cms : exact version constraints (7.x-dev) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 082422f334f1bf2d593ea395fe4d8c056b24fc8e
PHP version: 7.2.14
PHP binary path: C:\Unix\PHP-7.2.14-x64\php.exe
```

When I run this command:

```
composer install -vvv
```

I get the following output (Composer hangs at this point):

```
Something's changed, looking at all rules again (pass #100)
```

And I expected this to happen:
After some investigation I found out there are some incompatible version constraints: TYPO3 requires symfony packages with version "^2.7" but phpunit-merger only allows versions "^3.0 || ^4.0". I would expect an error message here but Composer hangs and doesn't return anything.

**Comment by Seldaek** [comment]
Seems like this might well be one of those solver edge cases where finding a solution is just awfully long.. It's a property of the algo that this can happen, it doesn't often, but if it does not much we can do. Usually playing around with requirements and narrowing things down a bit if possible helps.

**Comment by sleitz** [comment]
I also ran into this problem for some projects. I found the related (or rather, similar) issue #7665, which does not seems to have received a lot of attention in terms of fixes. I still hope this can be fixed in Composer, because one does not really have any influence on the packages and versions on offer via Packagist. All the dependencies used to work a while back.

**Comment by Seldaek** [comment]
Please track https://github.com/composer/composer/issues/9294 instead
