### ISSUE TITLE
composer scripts run on a different shell

### ISSUE THREAD

**Issue by staabm** [composer/composer#8489]
using the composer.json:

```json
{
    "scripts": {
		"phpstan-init": [
			"COMPOSER=phpstan-composer.json composer install --prefer-dist"
		]
    }
}
```

I have the problem that running the command 1:1 on the shell does work, but invoking it via composer scripts does not:

(using git bash on windows):
```
mstaab@COMPLEX-67 MINGW64 /c/dvl/Zend/DefaultWorkspace13/php-clxmobilenet-portable (clxmstaab-patch-1)
$ COMPOSER=phpstan-composer.json composer install --prefer-dist
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
complex/package-versions: Generating version class...
complex/package-versions: ...done generating version class
```

doing the same thing with the same command via composer scripts (on the same shell):
```
mstaab@COMPLEX-67 MINGW64 /c/dvl/Zend/DefaultWorkspace13/php-clxmobilenet-portable (clxmstaab-patch-1)
$ composer phpstan-init
> COMPOSER=phpstan-composer.json composer install --prefer-dist


  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "=phpstan-composer.json" is not defined.


Script COMPOSER=phpstan-composer.json composer install --prefer-dist handling the phpstan-init event returned with error code 1

```

the error I get here looks the same as when I run the command on cmd.exe.

**Comment by johnstevenson** [comment]
Well scripts are run on the native OS shell (through `proc_open`) so cmd.exe for Windows, which cannot handle setting an env and calling a command as a one-liner like you can do on linux and linuxy (Git Bash, Msys, Cygwin on Windows).

Perhaps setting the env outside of the `scripts` entry would be a more robust and cross-platform solution?

**Comment by staabm** [comment]
@johnstevenson thx for the feedback. Based on that I came up with the following idea: https://github.com/composer/composer/issues/8488#issuecomment-568156592
