### ISSUE TITLE
Help please kind people something is wrong and I have no idea what

### ISSUE THREAD

**Issue by Fildav0le** [composer/composer#8500]
So yeah I tried to install stuff that can give me the power to stream from my pc to instagram (I know...) and I have ran into a problem. (Disclaimer: I have no idea how to code or whatsever so yeah that's that). This is the error :
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mgp25/instagram-php v7.0.1 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - mgp25/instagram-php v7.0.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - Installation request for mgp25/instagram-php ^7.0 -> satisfiable by mgp25/instagram-php[v7.0.0, v7.0.1].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\Users\Standard\Desktop\php-7.2.26-Win32-VC15-x64\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, deleting ./composer.json.

Thanks for your help

**Comment by johnstevenson** [comment]
You need to enable the gd extension. Open the php.ini file, as referenced, search for the line `;extension=gd2` and remove the semi-colon (which acts as a comment character) to enable it:

`extension=gd2`
