### ISSUE TITLE
composer.lock seems unnecessarily verbose

### ISSUE THREAD

**Issue by donquixote** [composer/composer#8501]
One purpose of composer.lock, as far as I understand, is to be checked into a (git) repository to lock the versions of installed packages. For this it would be sufficient if it contained the following info for each package:
- Package machine name
- Package version
- Install source (e.g. packagist, vcs, symlink to local path..)
- Information about applied patches.
- Perhaps some kind of checksum.
- Destination path where it was installed (if installer-paths was used), so that it can be removed later if applicable.

Currently the composer.lock contains a lot of other info per installed package. I think it contains a complete copy of the composer.json for that package. This causes a lot of noise in git when updating packages. And, I suppose, merge conflicts.

A solution could be to split the file:
- A slim json file with only the necessary information to be tracked with vcs / git. This would be used by composer install.
- A larger file which contains all the other info, for the user's convenience. This would be the composer.lock we know today. This file could be ignored with .gitignore. It would be irrelevant for composer install, unless the smaller file is missing.

For backwards compatibility, there could be:
- A setting in composer.json to opt into this new behavior.
- Perhaps composer.lock can be the bigger file, and we would give a new name to the smaller file.

**Comment by mpdude** [comment]
Treat `composer.lock` like an opaque, binary file. In particular, don't try to merge it.

**Comment by donquixote** [comment]
So, do you not track it in git? If I track it, I will have to merge it at some point.
I could "regenerate" it using composer update to resolve the conflict, but this would give me unexpected versions of the dependencies that were in none of the parent commits.

**Comment by localheinz** [comment]
@donquixote 

Maybe this helps?

https://blog.doh.ms/2016/11/28/solving-conflicts-in-composer-lock/

**Comment by donquixote** [comment]
Hmm this works in the simple case where you know exactly what you are doing.
But there are limitations.

If you merge two branches which none of them you authored, then you won't know what to do.
Well perhaps you do if the instructions are documented in the commit messages. But even then there are limitations.

If some upstream packages have new versions, the update will give you package versions that you did not previously test.
If your automated tests are good then I guess it is ok.. I happen to work on a legacy project where test coverage is non-existent and it would be really hard to add a sufficient coverage now.

To avoid the unexpected updates (in an application project, not a published package) one could freeze the version in the composer.json directly, instead of the composer.lock. This would be sad because it would mean the composer.lock is not a reliable enough tool for freezing the version.

On the other hand, I realize that simply "merging" the file could lead to incompatible versions..

-----

All this said, I think my points above still apply: Most of the stuff in composer.lock is redundant and should not be in a file tracked in git. Even if you use the method suggested in the link instead of merging, there is still no reason to have all this stuff in the file.

Perhaps we could agree on this observation and then decide to leave it be, because it is not big enough a problem?

**Comment by Seldaek** [comment]
The benefit of the current approach is that we have the full package info in the lock file, so running an install from the lock file is essentially an offline operation which is very fast. Aside from that, most conflicts happen due to the `content-hash` or the actual package versions IMO, the rest of the package metadata which you suggest removing rarely changes.. So all in all I don't think this needs changing.
