### ISSUE TITLE
Memory overflow when removing a vendor that is no longer available

### ISSUE THREAD

**Issue by DavidGarciaCat** [composer/composer#8505]
Hi there,

As I was pointing out on this other Issue https://github.com/friends-of-phpspec/phpspec-code-coverage/issues/19 I've found that my Composer has thrown a memory overflow because I installed a vendor through the `composer require` command but then the author decided to remove the repo from GitHub although he kept it in Packagist (flagging it as abandoned).

When Composer tried to retrieve the vendor to analyse the dependencies, due to the repo doesn't exist anymore, the bin threw the memory overflow error.

I can see this case as a problem related to the repository because when it was deleted made the Composer binary unable to retrieve the data. However, as pointed out by the author, the error comes from Composer.

Hope this can be fixed in a new release soon.

Cheers,

**Comment by Seldaek** [comment]
We are working on memory improvements in v2 already so closing this.
