### ISSUE TITLE
Composer eats too many memory during composer require

### ISSUE THREAD

**Issue by ihor-sviziev** [composer/composer#8507]
My `composer.json`: (get it [after installing magento 2](https://devdocs.magento.com/guides/v2.3/install-gde/composer.html))

```json
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "require": {
        "magento/product-community-edition": "2.3.2-p2"
    },
    "require-dev": {
        "allure-framework/allure-phpunit": "~1.2.0",
        "friendsofphp/php-cs-fixer": "~2.13.0",
        "lusitanian/oauth": "~0.8.10",
        "magento/magento-coding-standard": "~1.0.0",
        "magento/magento2-functional-testing-framework": "~2.3.14",
        "pdepend/pdepend": "2.5.2",
        "phpmd/phpmd": "@stable",
        "phpunit/phpunit": "~6.5.0",
        "sebastian/phpcpd": "~3.0.0",
        "squizlabs/php_codesniffer": "3.3.1"
    },
    "conflict": {
        "gene/bluefoot": "*"
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/",
            "Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/"
        },
        "psr-0": {
            "": [
                "app/code/",
                "generated/code/"
            ]
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "version": "2.3.2-p2",
    "minimum-stability": "stable",
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "extra": {
        "magento-force": "override"
    }
}

```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
The version field is present, it is recommended to leave it out if the package is published on Packagist.
Defining autoload.psr-0 with an empty namespace prefix is a bad idea for performance
require.magento/product-community-edition : exact version constraints (2.3.2-p2) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.9.1
PHP version: 7.2.26
PHP binary path: /usr/bin/php7.2

```

When I run this command:

```
composer require --profile -vvv "magento/product-community-edition":"2.3.2-p2"
```

I get the following output:
![image](https://user-images.githubusercontent.com/1873745/71722779-d41af380-2e32-11ea-8b6e-a29e2cdfe4d0.png)

`Memory usage: 644.91MiB (peak: 1479.29MiB), time: 51.19s`

And I expected this to happen:
Right now 
Composer eat 619 MB of RAM, then grew to ~1.5 GB, then went down to 643 MB back.

It's really **too much** - eating 1.5 GB of memory just for installing some package.

If I'm adding all my extensions via composer - I'm getting following error:
Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52

I do know that I could allow more memory, and it will fix this issue for some time, but this is really hack, composer should utilize memory in more optimal way.

**Comment by tworthington** [comment]
This has been going on for years now; the composer devs simply don't know how to use memory efficiently. Or don't want to. Either way, composer is basically a broken package that only works if it's handed ideal conditions that many people on shared hosting or even just older hardware can not provide and which are completely ludicrous for managing a dependency graph (1½GB is more space than the Encyclopedia Britannica requires). The whole package needs to be thrown away and re-written from scratch as far as I can see. Preferably by a different team.

If you're lucky enough to be able to increase the memory limits in php.ini then try that - although you might find even then that composer's gargantuan memory requirements will might outstrip your physical limits.

Composer: all the elegance of manually editing your /etc/ dir combined with the convenience of having to hack JSON files.

**Comment by xabbuh** [comment]
@tworthington Congratulations, it's only the 4th day of the year and you are already leading the race for the least constructive comment of the year by a wide margin.

I am pretty sure the Composer team which did a great job to move the whole PHP ecosystem into a new era will value your feedback and will carefully review your contribution in making the whole SAT implementation faster and less memory consuming.

I wish you happy new year!

**Comment by Seldaek** [comment]
See 2.0 branch, we're on it.

**Comment by klidifia** [comment]
It's a shame, my site works fine with 1GB ram and every time I want to use composer I have to up it to 4.

**Comment by xabbuh** [comment]
@klidifia Instead of ranting here you can try out the 2.0 dev version of Composer and write a proper (!) issue if you don't see any improvements there.

By the way, there is no need to run Composer on the same server that is used to serve your website. Run it locally on your development machines and commit the `composer.lock` file. Executing `composer install` with a lock file being present is actually a quite cheap operation.

**Comment by klidifia** [comment]
Thanks for your constructive suggestions.

For anyone else struggling: I've ended up setting some swap memory.
