### ISSUE TITLE
Character output

### ISSUE THREAD

**Issue by AkioSarkiz** [composer/composer#8509]
I have this index.php
```php
<?php declare(strict_types=1);
ob_start();
require __DIR__ . '/vendor/autoload.php';
var_dump(ob_get_contents());
exit();
```
This code should not output anything, but I get: 
```php
E:\GitHub.Repositories\some_project\index.php:4:string '﻿' (length=3)
```

It bothers me. Because I can’t set up the session and cookies. Why is composer doing this?

**Comment by xabbuh** [comment]
This has nothing to do with Composer. `var_dump()` does the output (see also https://3v4l.org/bIFRB).

**Comment by AkioSarkiz** [comment]
> 
> 
> This has nothing to do with Composer. `var_dump()` does the output (see also https://3v4l.org/bIFRB).

Not. I say that the composer should not output anything, but only should connect files and monitor for updates. Why it displays characters during connection is not clear. I used var_dump to count the characters that the composer displays when connected and there are 3 of them. This behavior is not normal
```
E:\GitHub.Repositories\some_project\index.php:4:string '﻿' (length=3)
```

**Comment by stof** [comment]
One idea is that one of the file being loaded by `autoload-files` in your project has a BOM char before the PHP opening tag (which is then part of the output).
Composer does not put BOM chars in the autoload files it generates.
