### ISSUE TITLE
Allow $schema in composer.json (and composer.lock)

### ISSUE THREAD

**Issue by glen-84** [composer/composer#8512]
**Edit:** Correction, it is _not_ supported by PhpStorm.

---

I thought that this was [VS Code-specific](https://code.visualstudio.com/docs/languages/json#_mapping-in-the-json), but it seems to work in PhpStorm as well.

![image](https://user-images.githubusercontent.com/261509/71811229-d2dd0700-307c-11ea-85c2-cab83a8c2098.png)

![image](https://user-images.githubusercontent.com/261509/71811246-da041500-307c-11ea-8dbb-86dd7e46eebd.png)

**Comment by localheinz** [comment]
Sounds good!

Was just thinking about this the other day as well!

**Comment by mfn** [comment]
Nice!

You can already choose at the bottom, but of course it's auto-included, that would be even better:
![image](https://user-images.githubusercontent.com/87493/71814008-804f1b00-307b-11ea-9476-6d12e6b80dcd.png)

**Comment by paul-gene** [comment]
In PHPStorm 2019.2, it shows a warning that `$schema` isn't allowed.

**Comment by glen-84** [comment]
@paul-gene That's expected, and what this issue is about. See #8513, which will fix this.

**Comment by paul-gene** [comment]
@glen-84 but in your screenshot, it's not being underlined as erroneous?

**Comment by glen-84** [comment]
@paul-gene It's highlighted as a warning in my screenshot.

**Comment by stof** [comment]
I'm quite sure this is VS Code specific (as they document themselves, with a gotcha that it might make validation fail). And https://github.com/json-schema-org/json-schema-spec/issues/828 makes it clear that this is *not* what is expected by the JSON-Schema spec.

AFAIK, PHPStorm does not read this `$schema`. But it probably already has the mapping for composer.json built-in (either it is built-in, or it is part of the composer.json plugin).

**Comment by localheinz** [comment]
@glen-84 @mfn 

If you are interested in support for specifying the underlying JSON schema in a JSON file, please chime in at https://github.com/json-schema-org/json-schema-spec/issues/828.

**Comment by stof** [comment]
btw, if you install https://marketplace.visualstudio.com/items?itemName=ikappas.composer VS Code will know automatically that composer.json files are using the composer json schema (this extension registers this mapping in the config)

**Comment by Relequestual** [comment]
> If you are interested in support for specifying the underlying JSON schema in a JSON file, please chime in at json-schema-org/json-schema-spec#828.

We don't really want people `+1`ing issues. We are aware of the issue. We don't have the bandwidth to address it, nor the bandwidth to even prioritise issues for the next release right now. Thanks.

**Comment by glen-84** [comment]
I apologize, I didn't realize that PhpStorm was automatically loading the schema based on the file name. I must have tested it incorrectly.

OP updated. Closing.
