### ISSUE TITLE
Should composer install check the currently checked out versions for dependencies, changing them if needed?

### ISSUE THREAD

**Issue by aldenw** [composer/composer#8514]
To preface, I have an application with dependencies in repositories that we also maintain.

The workflow I was hoping would exist was that I could install a dependency using --prefer-source,  getting the repository in my vendor folder, create a new feature branch for the dependency, then commit and push the needed work on the feature branch.  When done with my work on the feature branch in the dependency, I would expect to be able to run composer install again, causing composer to checkout the branch/revision specified in the composer.lock file (which has not been modified in the meantime). 

I was hoping composer would confirm the currently checked out source of my dependency matches the lock file's version, but it seems to not do that.  Instead it leaves the dependency with the feature branch checked out.

Is there perhaps a feature that I'm missing here, or some other recommended workflow?  The workarounds are to either delete the vendor/mydependency folder that I'm working on, then running composer install works as I would expect, re-installing the version from lock file, but the major downside to that is that I can't maintain a local .git folder with my local branches in my vendor folder, or I can of course manually check out the branch.

**Comment by Seldaek** [comment]
This is indeed not possible right now, if you modify the vendor directory you are on your own. `composer status` will list the changed dependencies though, if you want to check for anything that's out of order, but `install` does not run this stuff as it's quite slow, and it instead relies on vendor/composer/installed.json to tell it what is currently installed.
