### ISSUE TITLE
Composer v1.9.1 won't install with PHP v7.4.1

### ISSUE THREAD

**Issue by skeeith** [composer/composer#8519]
Recently formatted my laptop and tried to install Composer v1.9.1 using PHP v7.4.1 TS.

**Comment by gaurangkumar** [comment]
Screenshot: https://imgur.com/a/P8Fenqg

Composer 1.9.1 installed on PHP 7.4.1 and working perfectly.

Please describe your problem in detail and show us step to produce that problem again.

You can share screenshot by https://imgur.com/.

**Comment by gaurangkumar** [comment]
I have downloaded php-7.4.1-Win32-vc15-x64.zip as your step 1 and done all steps but no problem occurred.
You should close this issue or share error displaying screenshot by https://imgur.com/.
