### ISSUE TITLE
Unable to use classmaps when using multiple autoloaders

### ISSUE THREAD

**Issue by jenkoian** [composer/composer#8522]
When working with some ecosystems (e.g. WordPress) often you'll find modules or plugins ship a 'built' version which bundles all the vendors and uses `vendor/autoload.php` for autoloading. 

When you have multiple modules/plugins that do this you find each classmap registered to the class loader overwrites the last one. For example:

Plugin A: 
Set `$classmap` to a

Plugin B:
Uses same `ClassLoader` sets `$classmap` to b

Attempt to load `new A\Foo` from plugin A it checks the classmap but is that from B so resorts to finding from filesystem which is slower etc.

So nothing breaks, but you miss out on the higher performance of using a class map. 

I hope I've explained that well enough, but please let me know if you would like further clarification or anything. 👍

**Comment by stof** [comment]
shouldn't each autoload.php file be using a *different* instance of ClassLoader ? And so not overriding things from others ?

Either the issue is not reported properly, or you are doing weird things with your autoloaders.

**Comment by stof** [comment]
Note that when you have multiple autoloaders registered, each autoloader is called in turn, until one of them finds the class. But they are unaware of each other.

So if the first autoloader register does not enable the level 2 optimizations of the composer class loader, it will indeed check the file system before giving up (and so before the second autoloader is called).

**Comment by jenkoian** [comment]
Thanks for the reply @stof 

I've created a basic repo here: https://github.com/jenkoian/composer-issue-8522 that should outline the issue (output below), I think though it confirms your comment...

> So if the first autoloader register does not enable the level 2 optimizations of the composer class loader, it will indeed check the file system before giving up (and so before the second autoloader is called).

```
Classmap for A at registration time:/Users/ianjenkins/Code/composer-issue-8522/plugins/a/vendor/composer/autoload_real.php:49:
array(1) {
  'A\Foo' =>
  string(86) "/Users/ianjenkins/Code/composer-issue-8522/plugins/a/vendor/composer/../../src/Foo.php"
}

Classmap for B at registration time:/Users/ianjenkins/Code/composer-issue-8522/plugins/b/vendor/composer/autoload_real.php:49:
array(1) {
  'B\Bar' =>
  string(86) "/Users/ianjenkins/Code/composer-issue-8522/plugins/b/vendor/composer/../../src/Bar.php"
}

Call class from A
Classmap for A at call time:/Users/ianjenkins/Code/composer-issue-8522/plugins/a/vendor/composer/ClassLoader.php:322:
array(1) {
  'B\Bar' =>
  string(86) "/Users/ianjenkins/Code/composer-issue-8522/plugins/b/vendor/composer/../../src/Bar.php"
}

Classmap for A at call time:/Users/ianjenkins/Code/composer-issue-8522/plugins/a/vendor/composer/ClassLoader.php:322:
array(1) {
  'A\Foo' =>
  string(86) "/Users/ianjenkins/Code/composer-issue-8522/plugins/a/vendor/composer/../../src/Foo.php"
}

Call class from B
Classmap for A at call time:/Users/ianjenkins/Code/composer-issue-8522/plugins/a/vendor/composer/ClassLoader.php:322:
array(1) {
  'B\Bar' =>
  string(86) "/Users/ianjenkins/Code/composer-issue-8522/plugins/b/vendor/composer/../../src/Bar.php"
}
```

So yeah I think I was seeing that initial class map being incorrect and thinking this was an issue where as it seems if you follow it through it will load a class loader with the correct class map eventually. Thanks for your help and for clarifying the (non) issue. 👍
