### ISSUE TITLE
Documentation of website is build from branch master

### ISSUE THREAD

**Issue by windaishi** [composer/composer#8530]
The documentation on the website (https://getcomposer.org/doc) seems to be built from the .md files of the master branch. This is very confusing. You should use the current tag to build the documentation.

I noticed it because the documentation mentions that there is a config option called `lock` (https://getcomposer.org/doc/06-config.md#lock), but this feature does not work in the current version (1.9.2) of Composer. The feature currently only works on the master.

**Comment by Seldaek** [comment]
It is a bit confusing, but it also means we ship doc fixes ASAP, which is nice.. It's a trade-off..
