### ISSUE TITLE
feat: add --no-bin option

### ISSUE THREAD

**Issue by zanona** [composer/composer#8539]
It would be nice if we could set a `--no-bin` flag to the composer install command so it would not install executables under `vendor/bin`. This is particularly useful when only consuming packages from source.

Currently, I am running `composer install --no-dev -d dist && rm -rf dist/vendor/bin` to prevent sending those files over to the deployment server.

**Comment by Seldaek** [comment]
I don't really see this as valuable enough to add a new flag.. This adds clutter and the commands already have tons of arguments. Having a few extra files/symlinks on your deployment server doesn't seem like that big a deal. 

Alternatively you could perhaps set bin-dir in the config to /dev/null, maybe it fixes it for you.
