### ISSUE TITLE
Set COMPOSER_AUTH with ssh key for git clone

### ISSUE THREAD

**Issue by alexander-schranz** [composer/composer#8541]
My `composer.json`:

```json
{
    "name": "my/project",
    "license": "proprietary",
    "description": "My Project",
    "repositories": [
        {
            "type": "vcs",
            "url": "git@mygit.com:some/private-package.git"
        }
    ],
    "requires": {
          "some/private-package": "^1.0"
    }
}
```

<details>

<summary>
Output of `composer diagnose`:
</summary>

```bash
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.9.2
PHP version: 7.3.12
PHP binary path: /usr/local/Cellar/php@7.3/7.3.12/bin/php

[ 1s296 | Jan 21 09:16am ]
```

</details>

<details>

<summary>
When I run this command:
</summary>

```
composer install
```

</details>

<details>

<summary>
I get the following output:
</summary>

```
No access to the repository (needs ssh key)
```

</details>

And I expected this to happen:

I'm searching for a way to set an ENVIRONMENT variable with ssh private public key value to be used for the git clone so I thought about that maybe `COMPOSER_AUTH` environment variable could support this the following way:

```js
{
     "ssh-key-pair": {
           "mygit.com": { // not sure if this is needed
                 "private-key": "<private-key>",
                 "public-key": "<public-key>"
           }
     }
}
```

Maybe I did misunderstood the docs but I think currently there is no way to set a SSH key in composer_auth variable or?

**Comment by Toflar** [comment]
Try using the git environment variable `GIT_SSH_COMMAND`.

**Comment by alexander-schranz** [comment]
@Toflar Thank you for response. I did try that but could not found in the `ssh` command a way to read the key out of a ENVIRONMENT variable it seems `ssh -i identy_file` is the only way to set the ssh key file but I'm searching for a solution to set only ENV vars or is there a direct way to specify in the `ssh` command the ssh key?

**Comment by Toflar** [comment]
Just write it in a temp file before :)

**Comment by alexander-schranz** [comment]
@Toflar thats what I'm doing currently but I need todo that everywhere first write it into that file and thats why I'm searching for a way todo this with only ENV variables.

**Comment by Seldaek** [comment]
I don't think there is a way to do this right now, and I am not even sure there would be a way for composer to facilitate this. Especially as it seems to be kind of an edge case use case, I'm fairly reluctant to add cruft on our end.
