### ISSUE TITLE
Introduce "safe mode" to isolate security concern

### ISSUE THREAD

**Issue by fulldecent** [composer/composer#8543]
# Background

All Composer functionality is categorized in three buckets:

1. Read-only actions
   - **about**                Shows the short information about Composer.
   - **browse**               Opens the package's repository URL or homepage in your browser.
   - **check-platform-reqs**  Check that platform requirements are satisfied.
   - **depends**              Shows which packages cause the given package to be installed.
   - **diagnose**             Diagnoses the system to identify common errors.
   - **dump-autoload**        Dumps the autoloader.
   - **help**                 Displays help for a command
   - **home**                 Opens the package's repository URL or homepage in your browser.
   - **info**                 Shows information about packages.
   - **licenses**             Shows information about licenses of dependencies.
   - **list**                 Lists commands
   - **outdated**             Shows a list of installed packages that have updates available, including their latest version.
   - **prohibits**            Shows which packages prevent the given package from being installed.
   - **search**               Searches for packages.
   - **show**                 Shows information about packages.
   - **status**               Shows a list of locally modified packages, for packages installed from source.
   - **suggests**             Shows package suggestions.
   - **validate**             Validates a composer.json and composer.lock.
   - **why**                  Shows which packages cause the given package to be installed.
   - **why-not**              Shows which packages prevent the given package from being installed.

2. Mutating actions that do not execute third-party code
   - **archive**              Creates an archive of this composer package.
   - **clear-cache**          Clears composer's internal package cache.
   - **config**               Sets config options.
   - **create-project**       Creates new project from a package into given directory.
   - **init**                 Creates a basic composer.json file in current directory.
   - **remove**               Removes a package from the require or require-dev.
   - **self-update**          Updates composer.phar to the latest version.

3. Actions that execute third-party code
   - :bomb: **exec**                 Executes a vendored binary/script.
   - :bomb: **global**               Allows running commands in the global composer dir ($COMPOSER_HOME).
   - :warning: **install**              Installs the project dependencies from the composer.lock file if present, or falls back on the composer.json.
   - :warning: **require**              Adds required packages to your composer.json and installs them.
   - :bomb: **run**                  Runs the scripts defined in composer.json.
   - :warning: **update**               Upgrades your dependencies to the latest version according to composer.json, and updates the composer.lock file.

:warning: The actions **install**, **require** and **update** can [run arbitrary code from your shell](https://getcomposer.org/doc/articles/custom-installers.md) if they are modules or depend on modules.
:bomb: The actions **exec**, **global** and **run** can always run arbitrary code from your shell.

:bomb: Furthermore, [Composer plugins](https://getcomposer.org/doc/articles/plugins.md#plugin-capabilities) can also run arbitrary third-party code as your user account.

# Discussion

Maintainers are well-aware of the risk profile here of running third-party code in your shell and have added this warning:

> Do not run Composer as root/super user! See https://getcomposer.org/root for details

This issue is to add a layer of protection for *all* users on your system, not just the *root/super user*.

# Specification

1. Add a global command line option `--unsafe`
2. Any invocation of **exec**, **global** and **run** will fail with error if `--unsafe` is not specified
    > ERROR: The exec action requires the --unsafe option because it will run third-party code
    > ERROR: The global action requires the --unsafe option because it will run third-party code
    > ERROR: The run action requires the --unsafe option because it may run third-party code
3. Invocations of **install**, **require** and **update** will fail with error if `--unsafe` is not specified and a custom install is encountered
    > ERROR: You most specify the --unsafe option to install these packages which will run third-party code during installation: $$PACKAGE_NAME$$
4. Invocations will fail if plugins are installed unless one of `--unsafe` or `--no-plugins` is specified.
4. Change the warning:
    > Do not run Composer as root/super user! See https://getcomposer.org/root for details

    to:

    > Be safe when running Composer as root/super user! See https://getcomposer.org/root for details.

**Comment by stof** [comment]
Composer plugins are still able to hook into other commands, including read-only ones. As soon as you have plugins installed, they might all be unsafe commands by this definition.

**Comment by fulldecent** [comment]
@stof much thanks for that. I have updated to account for that.

**Comment by Seldaek** [comment]
I think this would generally speaking be nice to have, but I guess I'd prefer a whitelist system of sorts, as in asking the user if plugins are safe before enabling them the first time. Because for example [ocramius/package-versions](https://packagist.org/packages/ocramius/package-versions/dependents?order_by=downloads) is installed in tons of projects as it is depended upon by doctrine. If you then have to --unsafe all the time it'd become a pain and actually defeat the purpose as it might shadow the addition of another plugin that you are not aware of.

**Comment by fulldecent** [comment]
I think using --unsafe all the time is a pain and that this pain is a good thing.

If package-versions is such a great feature, then people should bring it upstream.

The main purpose of Composer is "Dependency Manager for PHP" not a script runner. So things involving dependency management are in-scope for the project and running third party code on machines should be hidden behind --unsafe.

**Comment by stof** [comment]
And the whole point of composer allowing plugins is to avoid having the composer core team (3 developers) maintaining all features that can as well be implemented externally.
Also, many communities have built their own composer plugin to integrate some features specific to their ecosystem (Symfony has the Flex plugin, Laminas has `laminas-component-installer`, there's several plugins related to Drupal, etc...).
Being able to whitelist some plugins (after reviewing them, if you really care) would allow to keep using the plugin of your framework while still being warned about other things (always using `unsafe` in all of these communities would make this flag useless).

**Comment by fulldecent** [comment]
That seems fair enough. I would expect end users will be whitelisting by editing ~/.composer.rc or similar, rather than ./composer.json. Because the latter could, of course, be third-party content.

**Comment by mfn** [comment]
Drive-by question: would this cover packages which, when being installed, would e.g. modify git hooks?

----

I recently had the pleasure to work on a library which require-dev such an add-on. I knew it's also "a practice" in the JS world, but I was pretty shocked that it modified by local git hooks without asking me (the package in question did emit an information, though).
Fun fact: due to it being an old dependency in this particular case, it actually _broke_ my ability to simply git commit locally. I guess I don't need to describe how furious I was when I found this all out 😄 

Thanks to the issue I learned that using `composer install --no-plugins` would have prevented this 👍 I guess I want to have this globally set to never run plugins…

And it also seems this will still run the various scripts steps (`post-*`, …) on the root project (which makes sense because this is an explicit "dependency" of the project),

----

Isn't `unsafe` equivalent to `--no-plugins` then?

Thank you

**Comment by fulldecent** [comment]
Great question. And yes, modifying a git will become impossible without running the proposed `--unsafe` switch.

`--no-plugins` is part of the issue, but `--unsafe` additionally protects against other things.

**Comment by Seldaek** [comment]
We now have allow-plugins, and docs at https://getcomposer.org/doc/faqs/how-to-install-untrusted-packages-safely.md on how to run safely. I am closing this as I don't see us adding more right now.

**Comment by fulldecent** [comment]
@Seldaek Thank you for the ping.

---

> You can disable plugins and scripts during package installation or updates with the following syntax so only Composer's code, and no third party code, will execute:

I think this note could be more clear. Does this means that a package installation which is expecting a script/plugin will result in a failed/inconsistent installation? Or will such an installation abort with error?

---

> Depending on the operating system we have seen cases where it is possible to trigger execution of files in the repository using specially crafted composer.json.

This seems like a bug and should be reported.

---

Otherwise this issue "Introduce safe mode" is fully resolved by those new additions, thank you.

Still I hope composer can be safe by default rather than "So in general if you do want to install untrusted dependencies you should sandbox them completely in a container or equivalent."

But the appetite is not there for that yet.
