### ISSUE TITLE
Links to symlink's target rather than path repository if symlink 

### ISSUE THREAD

**Issue by nsrosenqvist** [composer/composer#8548]
My `composer.json`:

```json
{
    "name": "[REDACTED]",
    "type": "project",
    "license": "MIT",
    "require": {
        "php": ">=7.0.0",
        "composer/installers": "~1.6",
        "[REDACTED]": "dev-master as 4.0",
        "[REDACTED]": "dev-master",
        "[REDACTED]": "dev-master"
    },
    "repositories": [
        {
            "type": "path",
            "url": "deployer/*/current",
            "options": {
                "symlink": true
            }
        }
    ]
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
require.[REDACTED] : unbound version constraints (dev-master as 4.0) should be avoided
require.[REDACTED] : unbound version constraints (dev-master) should be avoided
require.[REDACTED] : unbound version constraints (dev-master) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.9.2
PHP version: 7.2.24
PHP binary path: /usr/bin/php7.2
```

Description: 

For a personal project I deploy the most recent versions of a couple of private libraries using [Deployer](https://github.com/deployphp/deployer) rather than having to publish changes to the git repo before I have tested them in multiple environments. The way it works is that it keeps a few of the most recent versions that was deployed and links the active version by creating a symlink called `current` pointing to a specific release (`releases/12`), allowing for easy rollbacks. So the defined path repo is itself a symlink.

```
- deployer
-- project 1
--- current -> releases/12
--- releases
---- 12
---- 11
---- 10
-- project 2
--- ...
-- project 3
--- ...
```

When I then run `composer install` composer resolves the realpath of the link and the symlink in the vendor directory becomes `releases/12` rather than `current`, preventing me from deploying new updates or rolling back changes. So to resolve this I'm temporarily adding another step to the deployment step that relinks the folder in vendor to the `current` symlink.

What I expect to happen is that the symlink in vendor is pointing to what was actually defined in composer.json, not the resolved path.

**Comment by Seldaek** [comment]
You can try to experiment fixing this, I don't know if it's doable or not.. but seems like an edge case enough that I most likely won't spend time on it any time soon. Got lots more urgent stuff to work on at the moment.

**Comment by sup-ham** [comment]
look like using  same strategy with [this](/sup-ham/php-share)
