### ISSUE TITLE
Improvement of `composer show`

### ISSUE THREAD

**Issue by ycolin** [composer/composer#8549]
When I run this command:

```
composer show
```

I get the following output:

```
algolia/algoliasearch-client-php                 1.28.0             Algolia Search API Client for PHP
...
```

And I would like to get this output instead:

```
algolia/algoliasearch-client-php                 1.x.x -> 1.28.0             Algolia Search API Client for PHP
...
```

**Comment by stof** [comment]
why would you like to see `1.x.x -> 1.28.0` when you have the 1.28.0 release installed ?

**Comment by ycolin** [comment]
It's just an example. I just want: lastVersion -> newVersion just for information.

**Comment by Seldaek** [comment]
What does `lastVersion` even mean?

Sounds to me like maybe you want to run `composer outdated` which shows you current version and latest version for packages with updates available.

**Comment by ycolin** [comment]
No it's not that.
I want to see:  lastInstalledVersion -> currentlyInstalledVersion

**Comment by Seldaek** [comment]
Okay.. that is not going to happen though as it would require us to keep track of changes done in every update. Sorry :)
