### ISSUE TITLE
ERROR: "it was not specified a valid package" ???

### ISSUE THREAD

**Issue by 1helices** [composer/composer#8550]
My `composer.json`:
{
  "require":
  {
    "phpclasses/oauth-api": ">=1.0.105"
  },
  "repositories":
  [
    {
      "type": "composer",
      "url": "https:\/\/www.phpclasses.org\/"
    },
    {
      "packagist": false
    }
  ]
}

Output of `composer diagnose`:

Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.phpclasses/oauth-api : unbound version constraints (>=1.0.105) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking HTTP proxy: OK
Checking HTTP proxy support for request_fulluri: OK
Checking HTTPS proxy support for request_fulluri: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Composer version: 1.9.1
PHP version: 5.6.40
PHP binary path: /usr/bin/php

When I run this command:

/bin/composer install -vvv

I get the following output:

Reading ./composer.json
Loading config file ./composer.json
Loading config file /opt/oauth_2/auth.json
Reading /opt/oauth_2/auth.json
Checked CA file /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem: valid
Executing command (/opt/oauth_2): git branch --no-color --no-abbrev -v
Executing command (/opt/oauth_2): git describe --exact-match --tags
Executing command (/opt/oauth_2): git log --pretty="%H" -n1 HEAD
Executing command (/opt/oauth_2): hg branch
Executing command (/opt/oauth_2): fossil branch list
Executing command (/opt/oauth_2): fossil tag list
Executing command (/opt/oauth_2): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /home/transfer_user/.config/composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 1.9.1 (2019-11-01 17:20:17) with PHP 5.6.40 on Linux / 3.10.0-957.1.3.el7.x86_64
Loading composer repositories with package information
Downloading https://www.phpclasses.org/packages.json using proxy tcp://squid-awsisland.provell.com:3128
Writing /home/transfer_user/.cache/composer/repo/https---www.phpclasses.org/packages.json into cache
Updating dependencies (including require-dev)
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.000 seconds
Analyzed 4895 packages to resolve dependencies
Analyzed 67 rules to resolve dependencies
Package operations: 3 installs, 0 updates, 0 removals
Installs: phpclasses/sasl:1.0.0, phpclasses/httpclient:1.0.5, phpclasses/oauth-api:1.0.105
  - Installing phpclasses/sasl (1.0.0): Downloading https://www.phpclasses.org/install/package/sasl.zip using proxy tcp://squid-awsisland.provell.com:3128
Downloading (failed)
Failed: [Composer\Downloader\TransportException] 404: The "https://www.phpclasses.org/install/package/sasl.zip" file could not be downloaded (HTTP/1.0 404 it was not specified a valid package)

  [Composer\Downloader\TransportException]
  The "https://www.phpclasses.org/install/package/sasl.zip" file could not be downloaded (HTTP/1.0 404 it was not spe
  cified a valid package)

Exception trace:
 () at /usr/share/php/Composer/Util/RemoteFilesystem.php:440
 Composer\Util\RemoteFilesystem->get() at /usr/share/php/Composer/Util/RemoteFilesystem.php:89
 Composer\Util\RemoteFilesystem->copy() at /usr/share/php/Composer/Downloader/FileDownloader.php:153
 Composer\Downloader\FileDownloader->doDownload() at /usr/share/php/Composer/Downloader/FileDownloader.php:97
 Composer\Downloader\FileDownloader->download() at /usr/share/php/Composer/Downloader/ArchiveDownloader.php:38
 Composer\Downloader\ArchiveDownloader->download() at /usr/share/php/Composer/Downloader/ZipDownloader.php:77
 Composer\Downloader\ZipDownloader->download() at /usr/share/php/Composer/Downloader/DownloadManager.php:216
 Composer\Downloader\DownloadManager->download() at /usr/share/php/Composer/Installer/LibraryInstaller.php:197
 Composer\Installer\LibraryInstaller->installCode() at /usr/share/php/Composer/Installer/LibraryInstaller.php:101
 Composer\Installer\LibraryInstaller->install() at /usr/share/php/Composer/Installer/InstallationManager.php:173
 Composer\Installer\InstallationManager->install() at /usr/share/php/Composer/Installer/InstallationManager.php:160
 Composer\Installer\InstallationManager->execute() at /usr/share/php/Composer/Installer.php:597
 Composer\Installer->doInstall() at /usr/share/php/Composer/Installer.php:229
 Composer\Installer->run() at /usr/share/php/Composer/Command/InstallCommand.php:122
 Composer\Command\InstallCommand->execute() at /usr/share/php/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /usr/share/php/Symfony/Component/Console/Application.php:849
 Symfony\Component\Console\Application->doRunCommand() at /usr/share/php/Symfony/Component/Console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /usr/share/php/Composer/Console/Application.php:267
 Composer\Console\Application->doRun() at /usr/share/php/Symfony/Component/Console/Application.php:124
 Symfony\Component\Console\Application->run() at /usr/share/php/Composer/Console/Application.php:106
 Composer\Console\Application->run() at /usr/bin/composer:62

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

And I expected this to happen:

Successfully install: phpclasses/oauth-api

[transfer_user@russell /opt/oauth2] $ cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)

[transfer_user@russell /opt/oauth2] $ /usr/bin/php -v
PHP 5.6.40 (cli) (built: Oct 22 2019 09:33:23)

[transfer_user@russell /opt/oauth_2] $ /bin/composer -V
Composer version 1.9.1 2019-11-01 17:20:17

We have been using AWS PHP API successfully, installed via Composer, for a year. We have successfully installed other Packagist packages via Composer.

The subject error occurs only for a non-Packagist package, oauth-api, from here: https://www.phpclasses.org/package/7700-PHP-Authorize-and-access-APIs-using-OAuth.html

NOTE: This package requires username/password, which we also supply via auth.json file.

How can we correct the subject error?

Please, advise. Thank you.

**Comment by Seldaek** [comment]
I have no idea how the phpclasses.org repository works, but it seems to be a problem you should report there. If it's indeed an auth issue it might be due to your proxy?

**Comment by 1helices** [comment]
Yes, of course, I did report this there first.

The first reason for my post here is, what does this Composer error mean?

I, too, suspect our proxy. But, this proxy works for everything else, including Composer with Packagist.

Without knowing what Composer is complaining about, it is more difficult to troubleshoot and resolve this problem.

Please, advise. Thank you.

~ Mike

**Comment by Seldaek** [comment]
As you can see at https://github.com/composer/composer/blob/88cff792cc6f2fa4df736e9abb612b955b783087/src/Composer/Util/RemoteFilesystem.php#L441 - the error message comes from the response headers of the request, i.e. the server is returning `HTTP/1.0 404 it was not specified a valid package` as a response, and I also have no idea what the heck this means as it's not my repository. Hence why I think you should see with phpclasses.org first. Or alternatively I would suggest not using phpclasses.org at all as it has a history of publishing poor quality code, and instead try something like https://packagist.org/packages/league/oauth2-client ?
