### ISSUE TITLE
Composer updates local state just to show help

### ISSUE THREAD

**Issue by datashaman** [composer/composer#8552]
When `composer command --help` is invoked, _composer_ seems to update its package cache or state before the help is shown.

I live in Africa - it takes a long time for _composer_ to update its state. It's quite annoying when all you want to see is the options for a command.

Please consider looking at the provided options before syncing state to see if help can be shown immediately.

**Comment by Seldaek** [comment]
Please run composer `composer show -s --help --profile -vvv` and post the full output so we can maybe see where it's spending so much time.
