### ISSUE TITLE
Package resolution order unclear with multiple repositories

### ISSUE THREAD

**Issue by Cheezykins** [composer/composer#8559]
I'm having a little trouble working out what composer will do in this situation, sorry if it is documented somewhere but I've read the docs and it has left me a little confused.

I have multiple repositories, one of which contains local packages and one is essentially a proxy for packagist.

The composer.json repositories section looks like:

```json
  "repositories": [
    {
      "type": "composer",
      "url": "https://artifactory/artifactory/api/composer/local"
    },
    {
      "type": "composer",
      "url": "https://artifactory/artifactory/api/composer/remote"
    },
    {
      "packagist.org": false
    }
  ]
```

and the requires has:
```json
"mynamespace/mypackage": "^1.12"
```

I have a local package that mirrors a remote one, but the remote one may be several versions ahead.

What isn't clear is, which package would be chosen when the remote package is ahead?

For instance:

The local repository contains mynamespace/mypackage versions 1.12.0, 1.12.1 and 1.13.0
The packagist proxy contains mynamespace/mypackage versions 1.12.0, 1.12.1, 1.13.0 and 1.13.1

Based upon https://getcomposer.org/doc/04-schema.md#repositories it says

> **Note:** Order is significant here. When looking for a package, Composer will look from the first to the last repository, and pick the first match. By default Packagist is added last which means that custom repositories can override packages from it.

But, https://getcomposer.org/doc/05-repositories.md#package says:

> In fact, internally Composer sees every version as a separate package.

Does this mean that the local repository's mynamespace/mypackage 1.13.0 (for example) replaces the packagist proxy's mynamespace/mypackage 1.13.0, but because the highest stable one is the packagist proxy's mynamespace/mypackage 1.13.1 that is the one that will be installed. Because each version is considered its own package.

Or as mynamespace/mypackage is found in the local repository first, does the fact that it has a lower highest version that matches the constraint than the second repository become irrelevant and it will still be selected.

**Comment by Seldaek** [comment]
> Does this mean that the local repository's mynamespace/mypackage 1.13.0 (for example) replaces the packagist proxy's mynamespace/mypackage 1.13.0, but because the highest stable one is the packagist proxy's mynamespace/mypackage 1.13.1 that is the one that will be installed. Because each version is considered its own package.

Yes in composer v1 this is true, and it is indeed problematic and somewhat unexpected. Composer's 2.0 branch fixes that already, we're hoping to release soonish but no clear timeline yet sorry.
