### ISSUE TITLE
Multiple composer.json handling!!

### ISSUE THREAD

**Issue by inandi** [composer/composer#8568]
let's say my project directory structure like this:

```
root
|---vendor/
|---composer.json
|---API_DIRECTORY
	|---index.php
	|---LIBRARY
		|---AWS/
			|---vendor/
			|---composer.json
		|---GOOGLE/
			|---vendor/
			|---composer.json
		|---FACEBOOK/
			|---vendor/
			|---composer.json
	|---vendor/
	|---composer.json
```
as you can see I have multiple packages with different composer.json files. each and every time I need to run composer install separately. how can I do it only once, using one composer JSON file?

**Comment by alcohol** [comment]
I don't really see a good use-case for such an odd setup/configuration. But using some simple bash scripting you could create a solution I guess. We will never natively support this use-case however.
