### ISSUE TITLE
please add installer sha-256 or -512 checksum

### ISSUE THREAD

**Issue by davakos** [composer/composer#8571]
Would it be feasible to also provide either a sha-256 or sha-512 checksum for your installer? i.e.:
`https://composer.github.io/installer.sha384sum` (existing)
`https://composer.github.io/installer.sha512sum` (new)

You currently provide a sha-384, but I have a use-case where I need to install on Alpine Linux, which, as far as I can find, only provides facilities for validating sha-256 or 512. I also don't see an option for apk installing a sha384sum or shasum package, as it appears that would be part of the busybox base image.

Thank you and best regards,

**Comment by alcohol** [comment]
The `sha384sum` binary is part of the `coreutils` package (which is a must-have in any Alpine container imho).

**Comment by davakos** [comment]
@alcohol thank you for this information. I haven't needed coreutils for any of my container's functionality, but could use it in a multi-stage build. Thanks again for the guidance, will give that a try.

**Comment by davakos** [comment]
That worked. Please let me know if you'd like to keep this open for future use or would like to close since a viable workaround is available. Thanks again.

**Comment by Seldaek** [comment]
We already have enough places I need to update the signature of whenever the installer changes, so rathre not add more :)
