### ISSUE TITLE
Composer is using a deprecated authentication method with Github's GraphQL API

### ISSUE THREAD

**Issue by apfelbox** [composer/composer#8573]
Hi,

after running different commands in composer, I get an email from Github telling me about composer using a deprecated authentication method when accessing the GraphQL API:

![2020-02-04 at 11 38](https://user-images.githubusercontent.com/1032411/73739273-33c43180-4746-11ea-8968-e27537b28957.png)

**Comment by apfelbox** [comment]
Just found this ticket: https://github.com/composer/composer/issues/8454

Apparently the `1.10` hasn't been released yet. Is there already an ETA?

**Comment by dereuromark** [comment]
Yeah, the whole world/internet now gets these :)
I am sure they will fix it asap.

**Comment by Seldaek** [comment]
1.9.3 is out now
