### ISSUE TITLE
GitHub oauth token deprecation warning

### ISSUE THREAD

**Issue by jeabakker** [composer/composer#8574]
After running `composer install` I got a message from GitHub about the oauth token deprecation

> Hi @jeabakker,

> On February 4th, 2020 at 10:56 (UTC) your personal access token (*****) using Composer/1.9.2 (Linux; 3.10.0-957.21.3.el7.x86_64; PHP 7.4.2) was used as part of a query parameter to access an endpoint through the GitHub API:
> 
> https://api.github.com/repositories/***/zipball/****
> 
> 
> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.
> 
> Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
> Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
> 
> Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.
> 
> Thanks,
> The GitHub Team

I'm sorry if this was already reported (or even fixed)

**Comment by alexmuller** [comment]
👍 I think this is the same issue as #8454.

**Comment by jeabakker** [comment]
indeed, so closing this one

**Comment by Seldaek** [comment]
Fixed in 1.9.3. Run `composer self-update`
