### ISSUE TITLE
opcache_reset() after composer update?

### ISSUE THREAD

**Issue by rentalhost** [composer/composer#8578]
Could `opcache_reset()` be called after `composer update`? Or maybe there are another way to do that?

I mean, once composer will update PHP scripts for a lot packages, maybe is viable force a opcache reset to recompile this files and avoid some errors during files are keept at cache system.

**Comment by mfn** [comment]
Did you take a look at https://getcomposer.org/doc/articles/scripts.md , specifically the `post-update-cmd`?

**Comment by rentalhost** [comment]
I don't know if it could works, because opcache could be disabled for cli. So the `opcache_reset()` should run once when script is called from web server. I could create a workaround (which is what I'm going to do), but I think that it should be provided by composer.

**Comment by mfn** [comment]
But it has the same limitations: you run composer via CLI and opcache_reset has to happen in the process doing that caching aka php-fpm or whatever.

Unrelated to your original question, my experience is that it's not advised to call opcache_reset() in production. If you've a lot of cached code (i.e. frameworks) and many requests, a reset can severely impact the performance (spike) when it suddenly needs to start from a 0 cache.

**Comment by Seldaek** [comment]
There is no chance of composer providing this. This is a deployment concern and not a dependency management one.

That said, you could have a post-install-cmd script calling `cachetool opcache:clear`, if you make sure to install [cachetool](https://github.com/gordalina/cachetool) on your servers, or you could require it in your composer.json too I suppose.
