### ISSUE TITLE
Support custom username for GitLab's project deploy token

### ISSUE THREAD

**Issue by stanislav-zaprudskiy** [composer/composer#8582]
Currently, when composer authenticates against GitLab using [gitlab-token](https://getcomposer.org/doc/06-config.md#gitlab-token) it uses the hard-coded [`private-token`](https://github.com/composer/composer/blob/0fe200d6d950b0774688713be3153bb410eb70b8/src/Composer/Util/GitLab.php#L74) username. Which is OK for personal user tokens - which use that username, and which have no way to change it. But this doesn't go along with project deploy tokens - https://docs.gitlab.com/ee/user/project/deploy_tokens/. 

Even though GitLab [allows](https://docs.gitlab.com/ee/user/project/deploy_tokens/#deploy-token-custom-username) you to specify `private-token` as a username for your project deploy token, there are a couple of issues with that:

- it's not a default value for project deploy tokens
- `private-token` username is not mentioned anywhere in composer's docs, but only in the code
- as GitLab supports using different names, so should do composer

**Comment by stanislav-zaprudskiy** [comment]
This may potentially allow to resolve #7439, where a username is specified as part of a repository HTTP URL.

**Comment by alcohol** [comment]
Unfortunately the Gitlab implementation depends heavily on user-contributed changes, improvements etc. So it could take a while before this sees the light of day.

**Comment by simivar** [comment]
@alcohol wouldn't that feature boil down to adding a new option `gitlab-username` that takes `private-token` as default? If so I think I can try to find some time to open PR (I think that's what you meant by "depends heavily on user-contributed changes"?).

**Comment by alcohol** [comment]
> wouldn't that feature boil down to adding a new option gitlab-username that takes private-token as default?

I'm not sure to be honest, I haven't worked much at all on the gitlab implementation.

> If so I think I can try to find some time to open PR (I think that's what you meant by "depends heavily on user-contributed changes"?).

Absolutely :+1:

**Comment by KminekMatej** [comment]
@alcohol @simivar  I just did it:
https://github.com/composer/composer/pull/8858

**Comment by Seldaek** [comment]
Fixed in 2.0 by https://github.com/composer/composer/pull/8867
