### ISSUE TITLE
running a command thru composer scripts is waaaay slower then natively invoked

### ISSUE THREAD

**Issue by staabm** [composer/composer#8587]
My `composer.json`:

```json
{
  ...
    "scripts": {
        "phpstan": [
            "phpstan analyse -c phpstan.neon.dist"
        ]
    }
}

```

Output of `composer diagnose`:

```
$ composer diagnose
A script named bin would override a Composer command and has been skipped
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.complex/rocket : unbound version constraints (dev-CLX6_2019R03|dev-CLX6_2019R04|dev-trunk) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.9.3
PHP version: 7.0 - Package overridden via config.platform (actual: 7.2.9)
PHP binary path: C:\php-7.2\php.exe

```

When I run this command:

```
composer phpstan
```

I get a phpstan scan taking minutes and finally running into a **300 secs** timeout.

when I run `phpstan analyse -c phpstan.neon.dist` directly, I get the results in **3-4 seconds**.

**Comment by alcohol** [comment]
Can't reproduce this :man_shrugging:

**Comment by Seldaek** [comment]
Also not seeing this here.. Wonder what would cause it except some timeout thingy because of a script waiting for input.. BTW could be improved in 2.0 branch as that allows scripts to run in TTY mode.. Maybe worth trying it out to see if you can repro there?

**Comment by staabm** [comment]
hmm I can reproduce this issue only when phpstan needs to scan "enough" files. it happens in a project on file 319 of 501 or at 296 of 477. it does not happen on the same project when scanning less files

**Comment by alcohol** [comment]
I would suggest you try to use something like blackfire to get more insight into the call-graph. Without more information/details, it would just be wild guessing :-(

**Comment by staabm** [comment]
I somehow have the feeling that the antivirus is getting into my way. will investigate further

**Comment by staabm** [comment]
> BTW could be improved in 2.0 branch as that allows scripts to run in TTY mode..

how can I update my local composer to 2.0-dev? (and rollback afterwards?)

**Comment by Seldaek** [comment]
There are no builds available yet so you'd have to clone the repo, checkout 2.0, run composer install (from a phar), and then call bin/composer to run 2.0-dev

**Comment by staabm** [comment]
hmm when using `Composer\Config::disableProcessTimeout` it works and finally finshes (after 5min50 secs).

without a composer script it takes 3-4 secs

**Comment by alcohol** [comment]
If you want to quickly build a container with Composer 2.0-dev:

```
docker build --tag composer:2 -<<EOF
FROM composer:1
RUN set eux ; \
  git clone https://github.com/composer/composer /composer ; \
  cd /composer ; \
  git checkout 2.0 ; \
  composer install ; \
  ln -sf /composer/bin/composer /usr/bin/composer ; \
  composer --version
EOF
```

Then you can alias it as `composer2` in your shell by adding the following function to your `.bashrc` for example:

```
# .bashrc
composer2 () {
  tty=
  tty -s && tty=--tty
  docker run \
    $tty \
    --interactive \
    --rm \
    --cap-drop ALL \
    --env COMPOSER_HOME \
    --env COMPOSER_CACHE_DIR \
    --user $(id -u):$(id -g) \
    --volume $COMPOSER_HOME:$COMPOSER_HOME:delegated \
    --volume $COMPOSER_CACHE_DIR:$COMPOSER_CACHE_DIR:delegated \
    --volume /etc/passwd:/etc/passwd:ro \
    --volume /etc/group:/etc/group:ro \
    --volume "$(pwd)":/workdir \
    --workdir /workdir \
    composer:2 "$@"
}
```

**Comment by staabm** [comment]
on composer 2.x I see similar execution times.. I guess the antivirus is at fault.

**Comment by staabm** [comment]
I guess its something on my workstation and composer cannot solve it on its end

**Comment by sanmai** [comment]
If you have this in your `composer.json`, then it will rescan the whole hierarchy upon running `composer phpstan` even though you did `composer dump-autoload` just prior.

```json
{
    "autoload": {
        "classmap": [
            "src/"
        ]
    }
}
```

**Comment by Seldaek** [comment]
@sanmai thanks for the random comment on a 5yo closed issue! These are often useless zombie issues but in this one instance it actually made me realize we can improve things quite a bit, see https://github.com/composer/composer/pull/12456 😃

**Comment by sanmai** [comment]
Absolutely! My apologies for not making it a full-fledged bug report right away.
