### ISSUE TITLE
[GitHub API] Deprecation notice even after update to 1.9.3

### ISSUE THREAD

**Issue by trentza** [composer/composer#8589]
Hi we are still seeing these mails.

Our configuration is inline with all recommendations in the docs.

> On February 7th, 2020 at 08:18 (UTC) your personal access token (docker-build) using **Composer/1.9.3** (Linux; 4.19.76+; PHP 7.xxx) was used as part of a query parameter to access an endpoint through the GitHub API:
> 
> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.

**Comment by omansour** [comment]
see https://github.com/composer/composer/issues/8586 ?
