### ISSUE TITLE
Invalid lockfile after modifying composer.json with plugin

### ISSUE THREAD

**Issue by danepowell** [composer/composer#8606]
I maintain a Composer plugin that, in part, is responsible for cleaning up people's composer.json file. For example, one thing I want to set is `{ "config": {"platform": {"php": "7.3"} } }`.

I've seen https://github.com/composer/composer/issues/8259 and followed a similar technique. The problem is it results in an invalid lockfile that's missing `{ "platform-overrides": { "php": "7.3"} }` (which I guess corresponds to the platform config in composer.json).

I'm implementing the post-update-cmd event in order to make these updates, as you can see here (please overlook how ugly this code is, it's a WIP :smile: ): https://github.com/acquia/blt/pull/4010/files

Would it help to use some other event? How can I ensure the lock file is up to date at the end of this process?

**Comment by stof** [comment]
Altering the parts of the composer.json which impact the dependency resolution is complex, because you would have to re-run the update (maybe selected dependencies are not acceptable anymore).

And for the config, you will probably need to modify the composer config, not the root package (as the config was already loaded). That may be issue in your case.

**Comment by danepowell** [comment]
Thanks! I confirmed that by modifying the composer config instead of root package config I can get this to work. You can see the changes in the PR linked above.

My only concern is about which event hook to use. Through experimentation, I ended up using POST_PACKAGE_INSTALL / POST_PACKAGE_UPDATE but I'm not sure if that's ideal. The problem is that some hooks (PRE_UPDATE_CMD) seem to fire before my plugin is loaded while others (POST_UPDATE_CMD) run too late to modify config.

**Comment by Seldaek** [comment]
Yeah that's a typical chicken & egg case.. there is not going to be a perfect solution if you can't guarantee that your plugin is preinstalled globally for users who need it. You can also listen to both events in the plugin so the first time it runs it can at least do a half-assed job and then next composer update it will trigger at the right time?

**Comment by danepowell** [comment]
The problem is that I want to modify composer.json during a `composer create-project` call, to dynamically set some values such as the PHP constraint based on the user's environment. It's a bad UX for them to get some predefined PHP constraint that doesn't match their environment, and it would also be bad to force them to manually run composer update immediately after creating a new project just to update the lock file.

Using post_package_update works for modifying composer.json and injecting the config into the update process so that it gets written to composer.lock... the only problem _now_ is that the lock file hash is not up to date. Looking at Factory.php, it appears that plugins are registered immediately before composer.json is hashed and the Locker class is initialized. There's no hook in between those two where I could, say, modify composer.json with a plugin such that it gets picked up in the lock file hash.

To resolve this, I think we'd either need a post-plugin-activate hook (which could be pretty useful), or we need a way to force the hash to be recalculated. Does such a method exist?

**Comment by stof** [comment]
well, the thing is, we don't want to let plugins modify the composer.json between the time the solver runs and the time the hash is generated. The whole point of that hash is to check whether the composer.lock contains dependencies which correspond to the output of the solver for that composer.json. In your case, running an update with the changes applied would install different dependencies. so the lock file is indeed outdated.

**Comment by danepowell** [comment]
I guess this is a feature request then: as an end user, when I run `composer create-project`, I'd like some way to bake the minimum supported PHP version into my composer.json file, so that other people who clone my new project with newer PHP versions don't break my dependencies. Seems like a CLI parameter would be best if a plugin can't do it. Let me know if you want me to close this and open a new issue.

**Comment by Seldaek** [comment]
Why not just shipping the project with `{ "config": {"platform": {"php": "7.3"} } }` or whatever lowest php version you support, and let people on higher php versions bump that themselves if they care?

**Comment by Seldaek** [comment]
Closing as I don't see us adding this feature, seems a bit too edge-casey to me. Composer 2 flow is [quite a bit different](https://github.com/composer/composer/blob/59acf9d4aafd1fd4e1d869b66c9cafc0fbf1ce8d/UPGRADE-2.0.md#detailed-differences-in-event-flow-during-dependency-resolution-composer-updates-and-installs) so I don't know what you can do in a plugin, best bet IMO would be to run a `composer update --lock` internally in the plugin after updating the composer.json, which should be possible in v2 as the lock file does not get updated anymore during package install.
