### ISSUE TITLE
Using create-project command with absolute path does not work in 1.10-RC

### ISSUE THREAD

**Issue by ol0lll** [composer/composer#8609]
When I run this command:

```
composer create-project thunder/thunder-project:3.x /home/runner/build/test-dir --stability dev --no-interaction --no-install
```

I get the following output:
```
Creating a "thunder/thunder-project:3.x" project at "/home/runner/work/theme-thunder-admin/theme-thunder-admin//home/runner/build/test-dir"
```

And I expected this to happen:

Project should be created in ' /home/runner/build/test-dir'.
In https://github.com/composer/composer/commit/43e0321ee74aa5efb9b720f8576145c351d7f3e3 the directory variable is prepend with getcwd() even when path argument is set which renders using absolute paths impossible.

**Comment by Seldaek** [comment]
Ah good catch, should be an easy fix if you want to have a look at sending a PR? :)

**Comment by ol0lll** [comment]
I've added a PR.
