### ISSUE TITLE
Display of composer outdated output mangled on Windows 7 / unreadable

### ISSUE THREAD

**Issue by jrfnl** [composer/composer#8610]
This has been happening for a while and I just tried to test when it started by rolling back, but haven't come to a conclusion other than that something changed (for the better) in 1.8.5, but that things are still wonky.

It seems to be related to which PHP version is used to run Composer. The more recent versions display things properly, older versions don't.

These are just some random PHP versions I used to test with - I have not tested to the extend to determine the exact PHP versions in which things changed.

PHP | Wonky | Good
--- | --- | ---
7.1 | 7.1.25 | 7.1.30
7.2 | 7.2.17 | 7.2.25
7.3 | 7.3.4 | 7.3.12
7.4 | - | 7.4.0+

_**If you deem this a PHP issue and not a Composer issue, please feel free to close the issue.
In that case, it can serve as an answer for other people who run into it to** "upgrade to the latest PHP version to fix"._

I've also seen wonky display like the below when running other commands, but this is the easiest one to consistently reproduce.

The screenshots are from the [PHPCSUtils](https://github.com/PHPCSStandards/PHPCSUtils/) project, but this behaviour is independent of which project I'm running the command(s) on.

Feel free to use PHPCSUtils as a test case to reproduce the issue though:
```
composer create-project phpcsstandards/phpcsutils
```

### When I run this command:

```
composer outdated
```

### I get the following output:

ConEmu (190310 preview):
![image](https://user-images.githubusercontent.com/663378/74545057-8244ad80-4f48-11ea-8a0f-8b77e74ea7f8.png)

Cmd:
![image](https://user-images.githubusercontent.com/663378/74545152-a6a08a00-4f48-11ea-8b1c-c45e9f89cf3b.png)

### And I expected this to happen:

The "abandoned" messages to be displayed neatly underneath the relevant package (like is done on recent PHP versions), not placed wherever in the middle of lines or under unrelated packages.

![image](https://user-images.githubusercontent.com/663378/74546497-e9fbf800-4f4a-11ea-8b38-9f0871b982b4.png)

I'm reporting this here as I see this happening both in ConEmu as well as on the plain Windows command line (though less bad in the latter).

Please let me know if you need more information or would like me to test something (if I can).

**Comment by Seldaek** [comment]
Also not sure where the fault lies, but I believe 6cf54170ccae08c0dc67f8cc6ff04036be4a17dc fixed it.

**Comment by jrfnl** [comment]
Thanks so much @Seldaek ! :heart:
