### ISSUE TITLE
Using a version constraint like ^0.0.1 does not install 0.0.2

### ISSUE THREAD

**Issue by alexander-schranz** [composer/composer#8613]
My `composer.json`:

```json
{
    "require": {
        "jackalope/jackalope-fs": "^0.0.1"
    }
}
```

(Issue 

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.9.3
PHP version: 7.3.12
PHP binary path: /usr/local/Cellar/php@7.3/7.3.12/bin/php
```

When I run this command:

```
composer update
```

I get the following output:

```
  - Installing jackalope/jackalope-fs (0.0.1): Downloading (100%)
```

(on 0.0.1 without "minimum-stability": "dev" it will error but the issue isn't)

And I expected this to happen:

```
  - Installing jackalope/jackalope-fs (0.0.2): Downloading (100%)
```

There are currently 2 versions of the package `0.0.1` and `0.0.2` if I use `^0.0.2` or `0.0.*` in the composer.json it does install the expected version but using `^0.0.1` does install `0.0.1`.

**Comment by Seldaek** [comment]
The docs for composer/semver's parser of `^` operator indicate the "problem":

        // Allows changes that do not modify the left-most non-zero digit in the [major, minor, patch] tuple.
        // In other words, this allows patch and minor updates for versions 1.0.0 and above, patch updates for
        // versions 0.X >=0.1.0, and no updates for versions 0.0.X

Which is in line with what [node does](https://github.com/npm/node-semver#caret-ranges-123-025-004).

The issue is they should be using 0.1.x versions really, unless 0.0.1 => 0.0.2 has breaking changes.

**Comment by alexander-schranz** [comment]
@Seldaek oh I understand. Sorry for wasting your time 🙈
