### ISSUE TITLE
no-suggest and no-progress via composer.json config

### ISSUE THREAD

**Issue by clxmstaab** [composer/composer#8615]
I would like to configure via composer.json the value of no-suggest and no-progress.

almost everywhere I am using this 2 command switches. I would love to configure them e.g. via composer.json

example
```
{
    "name" : "example/mypackage",
    "license": "proprietary",
    "config" : {
        "no-suggest" : true,
        "no-progress" : true,
        "optimize-autoloader" : true,
        "platform" : {
            "php" : "7.0"
        }
    }
}
```

is this something you would consider to add if I provide a PR for it?

**Comment by clxmstaab** [comment]
example github action workflow, which would benefit from having these settings in the composer.json:

![image](https://user-images.githubusercontent.com/47448731/74656983-975f4d80-518f-11ea-99c0-613206267355.png)

**Comment by Seldaek** [comment]
2.0 branch has no --no-suggest flag anymore as output has been trimmed down to one line and it shows up in much less cases, and currently has no progress display (flag is still there for now but maybe should go too), not sure if we'll reintroduce that or not..

**Comment by alcohol** [comment]
Also, you could put those flags in a `$flags` variable if you feel like you are repeating them over and over.

**Comment by clxmstaab** [comment]
I see. thx for your opinions on this one.
