### ISSUE TITLE
COMPOSER_CACHE_DIR documentation specifies wrong directory for *nix XDG systems

### ISSUE THREAD

**Issue by fho** [composer/composer#8625]
The documentation states that the default cache dir on an XDG compatible *nix system is `$XDG_CONFIG_HOME/composer/cache` but composer uses `XDG_CACHE_HOME/composer` as default.

https://getcomposer.org/doc/03-cli.md#composer-cache-dir quote: 

> By default it points to $COMPOSER_HOME/cache on *nix and macOS, and C:\Users\<user>\AppData\Local\Composer (or %LOCALAPPDATA%/Composer) on Windows.

- On an XDG compatible *nix system the default `$COMPOSER_HOME` is `$XDG_CONFIG_HOME/composer`
  - Therefore `$COMPOSER_CACHE_DIR` -> `$COMPOSER_HOME/cache `-> `$XDG_CONFIG_HOME/composer/cache`
- composer uses `$XDG_CACHE_HOME/cache`  instead as cache: https://github.com/composer/composer/blob/master/src/Composer/Factory.php#L116

---------

**Comment by alcohol** [comment]
I think this part of the documentation was forgotten when the XDG specification was implemented. Maybe it is best to not mention the default at all, since it depends on circumstances (which only makes the documentation more confusing IMHO).

**Comment by imme-emosol** [comment]
Yes, it currently seems ~confusing~ contradictory.
https://getcomposer.org/doc/03-cli.md#composer-cache-dir
vs.
https://getcomposer.org/doc/06-config.md#cache-dir

**Comment by naderman** [comment]
Fixed via https://github.com/composer/composer/pull/10333
