### ISSUE TITLE
Ideas and suggestions. Modular development.

### ISSUE THREAD

**Issue by ALexeyP0708** [composer/composer#8626]
Ideas and suggestions. Modular development.
 
 The principle of modular development.
There is a central autoloader; by its logic (for example, by a route) it determines which module to load. That is, it determines which autoloader (module autoloader) will be next.

At the moment, each module has its own "vendor" folder, in which the dependencies of the version that the module needs are installed.
Thus, the more modules, the more vendor folders
.
In the future (in more modern versions), I would like to see such an implementation.

A single folder "vendor" where the dependencies are distributed by version, `[vendor / MyProduction / 2.0.0 / .....], [vendor / MyProduction / MyApp / 3.0.0 / .....]` 

Each autoloader is configured for each module.

The installation command, for example, is such a `composer  install --module  --vendor-modules  '/project/modules/vendor'`. Composer picks up the usual composer.json, checks if the necessary versions are installed,
 and install the missing versions. Installation of the dependency version is the maximum allowed for the module. After composer will form an atloader for the module according to the dependency versions.

I understand that a conflict problem is possible. The purpose of the module is to work autonomously within its borders. Everything else is on the conscience of the developer.
In cases of a common API between the modules, the developer can write for himself a separate component in which he will compare the composer.json file of the main module and composer.json of the dependent module before installing the dependent module.

**Comment by Seldaek** [comment]
I think in most cases this is adding complexity for little benefit, unless I misunderstand you. In any case I think it's something which is unlikely to happen in Composer so closing.
