### ISSUE TITLE
DX: Add better exception rendering when working on composer plugins

### ISSUE THREAD

**Issue by staabm** [composer/composer#8644]
when working on a composer plugin you sometimes run into php errors/warnings.
this warnings get converted into ErrorExceptions (in `Composer/Util/ErrorHandler`)) and finally get rendered on the console.

the console message does not contain information of the file/line though.
you just see the actual error message.

example:
![image](https://user-images.githubusercontent.com/120441/75165273-6c8e6f80-5722-11ea-853c-972bef326a19.png)

even if you debug with `-vvv` you don't get a stacktrace which contains the actual line/file which emitted the origin error/warning.

would be great DX if the message in the console would have a " in file $file on line $line" suffix :-).

I was not able to spot the code which renders the exception into the console, therefore was not able to provide a patch myself.

```
C:\dvl\Zend\DefaultWorkspace13\xxx>composer diagnose
A script named bin would override a Composer command and has been skipped
Checking composer.json: WARNING
require.complex/autoload-plugin : unbound version constraints (dev-master) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.9.3
PHP version: 7.0 - Package overridden via config.platform (actual: 7.2.9)
PHP binary path: C:\php-7.2\php.exe
```

**Comment by staabm** [comment]
I was able to fix my actual problem, but want to leave a bite more details here, as I think the DX still can be improved:

the error message with `-vvv`

```
Writing lock file
Generating optimized autoload files

Installation failed, reverting ./composer.json to its original content.


  [ErrorException]
  Array to string conversion


Exception trace:
 () at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/process/Process.php:263
 Composer\Util\ErrorHandler::handle() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/process/Process.php:263
 Symfony\Component\Process\Process->start() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/process/Process.php:196
 Symfony\Component\Process\Process->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Plugin/PluginManager.php(196) : eval()'d code:82
 complex\rocket\autoload\AutoloadPlugin_composer_tmp2::buildAutoloadClassmap() at n/a:n/a
 call_user_func() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:176
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:96
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Autoload/AutoloadGenerator.php:112
 Composer\Autoload\AutoloadGenerator->dump() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer.php:304
 Composer\Installer->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/RequireCommand.php:228
 Composer\Command\RequireCommand->doUpdate() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/RequireCommand.php:185
 Composer\Command\RequireCommand->execute() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:267
 Composer\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:106
 Composer\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin/composer:61
 require() at C:\ProgramData\ComposerSetup\bin\composer.phar:24
```

the error only happend when I used `composer update` on my project using my plugin.
the error didn't happen when testing the plugin project itself locally because of different versions of `symfony/process` in use.

I didn't realize that my error was that I started a symfony process using ` $process = new Process(['composer', 'dump-autoload']);` instead of ` $process = new Process('composer dump-autoload');`.
The line of code is a error in symfony/process 2.8.x but not on newer versions.

my plugin declares `"symfony/process": "^2.8 || ^3.0 || ^4.0 || ^5.0"` (like composer itself). running my local tests used a newer `symfony/process` version then composer.phar itself which bundles a rather old symfony/process 2.8.x.

therefore I wasnt able to reproduce the issue as I didn't realize that the error depends on the "old" dependencies within composer.phar.

**Comment by Seldaek** [comment]
The code rendering exceptions is in the symfony/console's Application class IIRC. But that should show the full trace as soon as you use `-v`, as in your second post.

Not sure what we can do here, maybe in v3 when we can upgrade dependencies we get better exception treatment out of the box..
