### ISSUE TITLE
Add the ability to use wildcards in bin configuration

### ISSUE THREAD

**Issue by jackbentley** [composer/composer#8646]
It would be useful to be able to add all of the files within a directory. This could be achieved with wildcards - as shown below.

This would be particularly useful for libraries such as https://github.com/cytopia/awesome-ci which can be installed via composer and provide loads of bin files that could be added to.

The only current alternative is to list each individual file.

Interestingly, for PEAR this already kind of happens https://github.com/composer/composer/blob/f154d5c09d69a6338d6a955bf51cc264d0448b3d/src/Composer/Installer/PearBinaryInstaller.php

---

My `composer.json`:

```json
{
	"require": {
		"acme/library": "*"
	}
}
```

`composer.json` in `acme/library`:
```json
{
	"bin": [
		"bin/*"
	]
}
```

When I run this command:

```
composer install
```

I get the following output:

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
    Skipped installation of bin bin/* for package acme/library: file not found in package
```

And I expected this to happen:

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
```

**Comment by Seldaek** [comment]
Sounds reasonable if the implementation isn't crazy.

**Comment by Seldaek** [comment]
I tried implementing this but not having the full list makes uninstall much more brittle in some cases so I think I'd rather not do this after all.
