### ISSUE TITLE
Official bash completion script please

### ISSUE THREAD

**Issue by socialcyberdog** [composer/composer#8647]
I found some low quality and / or disfunctional bash completion scripts for composer / symfony "somewhere on the internet" - this is of course not something anyone wants to spend a lot of time debugging with, so it would be a great thing if there existed an official, well maintained bash completion script from the composer team inside this repo that could be simply used. Thanks!

**Comment by alcohol** [comment]
https://sjorek.github.io/composer-bash-completion/ looks decent to me.

I do not think we will offer one officially, since there is not enough value in having it vs. maintaining it.
