### ISSUE TITLE
run composer commands from within a plugin

### ISSUE THREAD

**Issue by staabm** [composer/composer#8648]
I am in the process of building a custom plugin. in this plugin I am listening for `ScriptEvents::PRE_AUTOLOAD_DUMP` and want to execute another composer command.

I need to copy a lot of code arround (from composer itself) to be able to do it.

my current code looks like:

```php
class AutoloadPlugin implements PluginInterface, EventSubscriberInterface
{
    public function activate(Composer $composer, IOInterface $io)
    {
        // Nothing to do here, as all features are provided through event listeners
    }

    /**
     * {@inheritdoc}
     */
    public static function getSubscribedEvents(): array
    {
        return [ScriptEvents::PRE_AUTOLOAD_DUMP => 'buildAutoloadClassmap'];
    }

    public static function buildAutoloadClassmap(Event $event)
    {
        /*
        $extra = json_decode('{
            "rocket-autoload": {
                "admin": {
                    "classmap": [
                        "lib/admin/123"
                    ]
                },
                "shop": {
                    "classmap": [
                        "lib/shop/123"
                    ]
                }
            }
        }', true);
        */
        /**
         * @var array<string, array<string, array<string, string>>>
         */
        $extra = $event->getComposer()->getPackage()->getExtra();
        $pluginExtra = $extra['rocket-autoload'] ?? [];

        if (getenv('ROCKET_AUTOLOAD')) {
            if (getenv('COMPOSER_VENDOR_DIR')) {
                // We need the root package so we can add our classmaps to its loader.
                $package = $event
                    ->getComposer()
                    ->getPackage();

                $autoload = $package->getAutoload();

                if (empty($autoload['classmap'])) {
                    $autoload['classmap'] = [];
                }

// do my autoloading maginc

                $package->setAutoload($autoload);
            }
        } else {
            $io = $event->getIO();
// copied from Composer EventDispatcher
            $cmd = self::getPhpExecCommand() .' '. ProcessExecutor::escape(getenv('COMPOSER_BINARY')) . ' dump-autoload';
            putenv("ROCKET_AUTOLOAD=1");

            // dump a new autoloader for-each app
            foreach ($pluginExtra as $appName => $additionalClassMap) {
                putenv("COMPOSER_VENDOR_DIR=vendor-$appName");

                $process = new ProcessExecutor($io);
                $process->execute($cmd);
            }
        }
    }

// copied from Composer EventDispatcher
    static protected function getPhpExecCommand()
    {
        $finder = new PhpExecutableFinder();
        $phpPath = $finder->find(false);
        if (!$phpPath) {
            throw new \RuntimeException('Failed to locate PHP binary to execute '.$phpPath);
        }
        $phpArgs = $finder->findArguments();
        $phpArgs = $phpArgs ? ' ' . implode(' ', $phpArgs) : '';
        $allowUrlFOpenFlag = ' -d allow_url_fopen=' . ProcessExecutor::escape(ini_get('allow_url_fopen'));
        $disableFunctionsFlag = ' -d disable_functions=' . ProcessExecutor::escape(ini_get('disable_functions'));
        $memoryLimitFlag = ' -d memory_limit=' . ProcessExecutor::escape(ini_get('memory_limit'));

        return ProcessExecutor::escape($phpPath) . $phpArgs . $allowUrlFOpenFlag . $disableFunctionsFlag . $memoryLimitFlag;
    }
}
```

as you can see I had to copy `EventDispatcher::getPhpExecCommand()` and also need to pass some ENV vars into the `ProcessExecutor` via global state.

did I miss something and is there an easier way to run a composer command from within a plugin?

**Comment by alcohol** [comment]
I think it would help if you illustrated the actual use-case, cause right now you present us with a solution to an unknown problem, and all I can say is "why on earth do you want to do this?".

**Comment by staabm** [comment]
you are right, sorry for that:

I need several autoloaders because I am in a classical monorepo setup which contains several applications. the whole monorepo contains just a single composer.json.

I want composer to build a separate autoloader per application. this is something I will implent via a composer plugin (paths per app will be configured via composer.json extra attribute).
therefore I need to define a different class-loader name to make sure composer will not override all the files over and over again.

**Comment by alcohol** [comment]
Why do you want an autoload per application?

**Comment by staabm** [comment]
the applications use equal named classes and therefore I cannot build a single autoloader for all of them

**Comment by staabm** [comment]
To be more precise. I want a single classloader per app but with a different classmap each

**Comment by staabm** [comment]
To be more precise. I want a single classloader per app but with a different classmap each

**Comment by alcohol** [comment]
That's just a semantic difference honestly, and I still don't quite understand why? If that is really what you want, why not have a composer.json per application as well?

**Comment by staabm** [comment]
> That's just a semantic difference honestly

I dont think so. its a major difference whether you have a single autoloader at runtime which knows all classes/classmaps or you have several autoloaders which need to play well together and do that fast.


> and I still don't quite understand why? If that is really what you want, why not have a composer.json per application as well

we have ~15 mono repos which each contain ~4-10 apps (legacy). each mono-repo has a single composer.json. all apps within a single mono-repo share the same context and therfore share the same dependencies and composer.json.

having several composer.json inside a mono-repo would.. (to mention a few)
- be a lot of work to migrate to
- duplicate a lot of stuff
- need composer.json files outside the source versioning root, which is a major problem for a lot of tools
- require major changes in the ci/cd pipeline and duplicate a lot of ci/cd config

**Comment by alcohol** [comment]
Okay, so in that case, why do you want

> I want a single classloader per app but with a different classmap each

Sounds to me like just having one composer.json for all those applications in your mono-repo already works. Why the need to split up the autoloading part specifically?

**Comment by staabm** [comment]
> I need several autoloaders because I am in a classical monorepo setup which contains several applications. the whole monorepo contains just a single composer.json.

**Comment by staabm** [comment]
my apps contain equal named classes (in the global php namespace) and therefore collide with each other (class-naming wise)

**Comment by alcohol** [comment]
Okay, I see. Yeah, I can't really think of an elegant solution for that. Maybe a plugin is indeed the best candidate for such a specific use-case. I don't think the plugin API was ever really meant for such internal rewiring, so I'm not sure if you can avoid the messy part.

**Comment by staabm** [comment]
my plugin is already implemented and it kind of works.

my actual request with this issue was more about, if there is a "official" way to call a composer command from within a plugin.

as the conversation goes it seems there is no such way and I need to use the kind of workarounds I already do.

therefore closing.

thanks for your time and ideas.

**Comment by Seldaek** [comment]
I think this should do and is a little easier/cleaner (inspired from ExecCommand)..

```
        $dispatcher = $composer->getEventDispatcher();
        $dispatcher->addListener('__your_plugin_command', '@composer dump-autoload');
        $dispatcher->dispatchScript('__your_plugin_command', true);
```
