### ISSUE TITLE
Add PluginEvents::POST_FILE_DOWNLOAD event

### ISSUE THREAD

**Issue by heddn** [composer/composer#8654]
We're working on trying to build an update mechanism for Drupal that supports composer. One of the features we have currently with the MVP (without composer) is/was to do some security hash checking that what we downloaded matches what we expected. In looking to extend that into the composer world, it would be nice to have a POST download event. So we can do what we want and validate what we downloaded is what we expected.

**Comment by heddn** [comment]
Questions came up in Drupal slack about this approach. I'm going to pose them and answer them so we have the thoughts captured in a persistent location.


> @greg-1-anderson
> I'm not sure if this new event is going to be substantially different than the existing post-package-update event

Response:
I don't see these as the same thing at all. I believe that post package-{update|install} has already moved the files into the final destination. Post file download only fires in FileDownloader, meaning for tagged/packaged archives. Which is exactly what we want. We don't want to trigger it for source or git cloned things. Because git already has security built-in for those.

And prior to moving into the final destination, I want to have a chance to review and throw an exception if there's a MiM attack. Where I triggered the event, it hasn't moved them from temp yet.

**Comment by bruno-ds** [comment]
My question is probably stupid, but still, I don't see why:
If you use a "**trusted**" + "**https**" endpoint, there is no room for a man in the middle attack, no?

**Comment by heddn** [comment]
@bruno-ds for Drupal, we've opted to not assume that every hosting site, etc has a fully functional SSL setup. Yes, much of that is in the past, but to _assume_ that SSL is always available isn't true. Additionally, the "et cetera" part of the various attacks would also include things like verifying that the packages themselves haven't been modified on the remote server by someone who obtains FTP access and starts hacking away at the zip files. For Drupal, there's a 90 key rotation ceremony and regeneration of all the zip archives. We don't want to have any opportunity for anything odd happening when we deliver these artifacts.
