### ISSUE TITLE
When cloning fails error status code 0 is returned by composer

### ISSUE THREAD

**Issue by chrisdejager** [composer/composer#8665]
I use composer install in a gitlab ci pipeline. We use a private repository from which a package is installed. At some moment the docker image did not contain the required host key in known_hosts. Subsequently in the next jobs the composer install failed with an RuntimeException complaining that the git clone command failed because of host key verification error.
BUT composer does not return an error status code, thus the ci job continued running, resulting in weird later errors. Returned status code is zero/0. Verified by hand.

I would expect composer to always return an error status code other then 0 on any runtimeexception and/or for every failed package install. This would help debugging in automated build systems.

To replicate:
- Use a private repository
- Do not have the key for the host in known_hosts
- Do not have the composer dependency package installed in vendor
- Run composer install without tty OR answer NO on the question "Are you sure you want to continue?"
- composer fails with RuntimeException and status code 0

Composer version 1.9.3
PHP version 7.1.33

Thanks for your GREAT tool composer!!!

**Comment by chrisdejager** [comment]
aj! not a bug, it works as expected!

I made a wrapper script around composer to disable xdebug, but forgot to add "set -e" to the script (which makes the script fail when a subcommand fails). 

When directly executing composer it returns status code 1 as expected.

Sorry!

**Comment by johnstevenson** [comment]
@chrisdejager Composer automatically disables xdebug, so no need for  wrapper script: https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer
