### ISSUE TITLE
Question: How to cancel update operation from a “pre-package-update” listener

### ISSUE THREAD

**Issue by miguelrs** [composer/composer#8670]
_Posted [this on StackOverflow](https://stackoverflow.com/questions/60402968/how-to-cancel-the-composer-update-operation-from-a-pre-package-update-listener), but didn't get much visibility, so cross-posting here - hope it's alright..._

Working on a small Composer plugin, which has a listener for the `pre-package-update` event.

    public function prePackageUpdate(PackageEvent $event): void
    {
        /** @var UpdateOperation $operation */
        $operation = $event->getOperation();
        
        if ($something) {
            // I would like the stop the update for this package...
        }
    }

Based on some logic, I would like the package to _not_ be updated, but I cannot find any way to do that... Is there one?

Ideally I'd like the command (either install or update) to continue with the other packages, but if that's not possible, it's ok if the whole process is cancelled and reverted.

**Comment by alcohol** [comment]
> but if that's not possible, it's ok if the whole process is cancelled and reverted.

Throwing an exception would probably do that.

I think `pre-package-update` is too late to stop an update operation though. At this point the dependency solver process has already finished and the outcome has been determined. @Seldaek probably knows way more about this than me though.

**Comment by miguelrs** [comment]
Thanks a lot for your reply @alcohol.

I feel a bit dumb now, because I didn't think of simply throwing an exception...  
I gave it a try and it actually does cancel the process and revert the `composer.json` file to its original content 👍   

Not the ideal situation, but thinking about it again, it does make sense it's too late at that point because, potentially, if you cancel the update for a particular package, some other package(s) might need to be installed in a version different than the one in the original outcome...

Wondering if I could use a different event not specific to a single package (e.g. `pre/post-dependecies-solving`) and do the check for _all_ the packages. Although I think I'd have similar issues 🤔  

Anyway, will give it a try - thanks!

**Comment by Seldaek** [comment]
It'd be best to do the check in post-dependencies-solving (or pre-operations-exec for upcoming v2), and throw then to avoid having any operations executed already as that will leave the vendor dir in a somewhat inconsistent state.

That said, without knowing your use case, I gotta say this overall sounds like a pretty bad idea..

**Comment by miguelrs** [comment]
@Seldaek thanks a lot. 

Yeah I'll take a look at what I can do in `post-dependencies-solving`, and will look at that upcoming `pre-operations-exec` I didn't know about 👍 

>That said, without knowing your use case, I gotta say this overall sounds like a pretty bad idea..

😅 as a quick summary, one of the ideas is being able to define a "dependency upgrade stopper" for a package, as a human-friendly way to say that a dependency cannot be upgraded, and the (business-related) reason why...  
In older projects, you may look at `composer.json` and see e.g. 
```
"require": {
    "some/package": "1.x"
}
```
but actually today the latest version of `some/package` is `2.5`, and the rest of your dependencies are OK with the new version...  
However, did we set `1.x` for a reason, or was it just because it was the latest version at the time?  
With something like this (or the absence of it!), it'd be clearer:
```
"extra": {
    "my-stoppers-plugin": {
        "some/package": {
            "1.x": "Stuck on v1 until we fix that thing (see ABC-1234)."
        }
    }
}
```
So I wanted to cancel an update for `some/package` if the version was higher than the one defined as a "stopper"...  

Not sure whether this would be useful to anyone and/or there's something that does this already, but it's a bit of a toy project anyway 😄

**Comment by Seldaek** [comment]
I see.. IMO it's best to add comments about it in the composer.json, using stuff like:

```
    "_comment": [
        "some/package locked at 1.x until XXXX is merged"
    ]
```

But I guess your plugin works too, I was kinda worried it was a more complex use case.. As you always prevent the update and really the user should do a rollback of changes, it's not too bad.

**Comment by miguelrs** [comment]
Yeah I thought about using just comments, but wanted to try something more "integrated"/"structured" - e.g. cancelling updates beyond the stopper as I said, or asking you to define a stopper if detects you're installing a non-latest version, and a few more features I have in mind... 

Anyway, thanks both for the help, and keep going with the good work 👍
