### ISSUE TITLE
302 Redirect on SSL When Downloading Zip Archive Causes Issues

### ISSUE THREAD

**Issue by samspinoy** [composer/composer#8673]
Exactly same issue as this one: https://github.com/composer/composer/issues/4782

**Comment by alcohol** [comment]
Can you be more specific? Or are you using the exact same version of Composer with the exact same set of dependencies and the exact same package is failing?

**Comment by samspinoy** [comment]
I'm using v 1.9.3. Otherwise the error message is the same, as is the workaround.

**Comment by stof** [comment]
The issue you linked was for PHP 5.5 and older. As of PHP 5.6, the TLS stack of PHP handles peer verification properly by default and so the workarounds which were discussed in #4782 are all disabled.
And in the meantime, some code evolved in Composer as well (and the discussion itself was quite long btw).
So please describe the actual issue you have today.

**Comment by samspinoy** [comment]
Using composer 1.9.3. This is the version installed on our hosting partner's (platform.sh) servers. Locally I am using 1.9.1 and that works.

PHP 7.2

Composer.json entry:
`{
            "type": "package",
            "package": {
                "name": "library/stickytableheaders",
                "version": "0.1.19",
                "type": "drupal-library",
                "dist": {
                  "url": "https://github.com/jmosbech/StickyTableHeaders/archive/v0.1.19.zip",
                  "type": "zip"
                }
            }
        },`

Error given:
`[Composer\Downloader\TransportException]                                                                                        
The "https://github.com/jmosbech/StickyTableHeaders/archive/v0.1.19.zip" file could not be downloaded (HTTP/1.1 404 Not Found)`

Can be fixed by manually replacing the .zip url by https://codeload.github.com/jmosbech/StickyTableHeaders/zip/v0.1.19

Hope that provides you with enough details?

**Comment by alcohol** [comment]
Wait, so you have a package entry with a hardcoded url and that url returns a 404 and that doesn't raise any question marks on your end..?

**Comment by samspinoy** [comment]
Not sure I understand your question? Are you saying I should not include the url "https://github.com/jmosbech/StickyTableHeaders/archive/v0.1.19.zip" in the json file? 

There is nothing wrong with that url, if you try it, it will download the file. It's just that it is a 302 redirect (to https://codeload.github.com/jmosbech/StickyTableHeaders/zip/v0.1.19). It appears composer has some problems handling this redirect.

**Comment by alcohol** [comment]
I do get the redirect. Which begs the question, how did you end up getting a 404?

**Comment by samspinoy** [comment]
Well that is the question I am asking as well. I just added the library to my composer.json file, ran composer update which added the same .zip url to my composer.lock file. 

EDIT: I can see I left out an important part of the error description here: locally this works, hence no 404 locally. But when pushed to platform.sh servers, the direct .zip url gives a 404.

**Comment by samspinoy** [comment]
Actually I was just informed by platform.sh support that this is a Github bug. So closing this one.
