### ISSUE TITLE
Monstrous resource consumption

### ISSUE THREAD

**Issue by ergcode** [composer/composer#8675]
My `composer.json`:

```json
any
```

Output of `composer diagnose`:

```
any
```

When I run this command:

```
any
```

I get the following output:

```
Monstrous resource consumption due to dependencies. Where it is not needed.
```

And I expected this to happen:
Delete the repository and prevent developers from using this monster.

**Comment by floverdevel** [comment]
Is this some kind of troll?
I think his issue does not follow the contributing guidelines.

**Comment by ergcode** [comment]
> Is this some kind of troll?
> I think his issue does not follow the [contributing guidelines](https://github.com/composer/composer/blob/master/.github/CONTRIBUTING.md).

No, I'm not a troll. Developers use this low-tech solution in many projects. And they absolutely don't care about performance.
If the php script worked for hours or days, then there are no complaints. But php is made to be born and die. And when using composer, the resource consumption is simply unbelievable (it requires downloading tens or even hundreds of dependencies).

Any project in which composer is present is just a server killer.

**Comment by xabbuh** [comment]
Composer is a tool that helps you to install a compatible set of all the third-party libraries that you need. It is not meant to be executed when your applications serve the response for a request (except for the autoloader).

**Comment by floverdevel** [comment]
@ergcode can you tell us how are you using composer in your project?  It sounds like you are running `composer install` on every request, which you shouldn't do.

**Comment by alcohol** [comment]
Thank you for contributing.
