### ISSUE TITLE
"build" version and prefer-lowest flag

### ISSUE THREAD

**Issue by michalbundyra** [composer/composer#8677]
We have issued patched version for some libraries in Laminas (diactoros, laminas-view, and couple more) - fixed version for tag `1.1.0` is `1.1.0p1` (it's called "build" version in semver).

My `composer.json`:

```json
{
    "name": "michalbundyra/composer-test",
    "type": "library",
    "require": {
        "laminas/laminas-view": "^2.1.6p1"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.9.3
PHP version: 7.3.11
PHP binary path: /usr/bin/php
```

When I run this command:

```
composer update --prefer-lowest
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 5 installs, 0 updates, 0 removals
  - Installing laminas/laminas-zendframework-bridge (1.0.0): Loading from cache
  - Installing laminas/laminas-stdlib (2.2.0): Loading from cache
  - Installing laminas/laminas-loader (2.2.0): Loading from cache
  - Installing laminas/laminas-eventmanager (2.2.0): Loading from cache
  - Installing laminas/laminas-view (2.2.0): Loading from cache
Writing lock file
Generating autoload files
```

And I expected this to happen:

`laminas/laminas-view` [2.1.6p1](https://github.com/laminas/laminas-view/tree/2.1.6p1) should be installed instead of `2.2.0`.

This behaves different way for different versions. For example if I use version `^2.5.0p1` in composer.json and run update with `--prefer-lowest` it works fine.

**Comment by sbuzonas** [comment]
build metadata is denoted by a `+` after the semantic version

as an aside, build metadata `MUST` be ignored when determining precedence according to the [spec][1]

[1]: https://semver.org/#spec-item-10

**Comment by weierophinney** [comment]
@sbuzonas But what about the "patch-level" releases? Composer has supported those for some time, and what's being reported here is that `--prefer-lowest` is actually installing a _later_ version than the patch-level release.

**Comment by Seldaek** [comment]
The problem is if you look at the requires, `laminas/laminas-stdlib: 2.1.6p1` for example does not exist, and so on. If you use self.version you better make sure all relevant packages get tagged equally.

**Comment by michalbundyra** [comment]
@Seldaek Oh! Thanks for pointing it out! It is the problem on our side then.

@weierophinney see: https://github.com/laminas/laminas-view/blob/2.1.6p1/composer.json#L29-L31
