### ISSUE TITLE
How to install composer on Windows to another drive?

### ISSUE THREAD

**Issue by samuelnovotny** [composer/composer#8680]
Hi,
I'm trying to install the composer on Windows 10 to drive D.
I use the installer and do the following:

Destination location
`D:\bin\composer\composer-1.10.0`

PHP path
`D:\bin\php\php-7.4.3`

After the computer restarts, the composer does not work.

https://i.imgur.com/2yWJ7Gd.png

Can you help me?
Of course, the system is installed on drive C, but I need Apache, PHP and Composer on drive D.

**Comment by johnstevenson** [comment]
> After the computer restarts, the composer does not work.

You very rarely need to restart your computer after installing Composer. It looks like you are missing the composer directory from your PATH.

Did you use Composer-Setup.exe, because all this stuff is done for you?

If so, can you provide the log file, as detailed here: https://github.com/composer/windows-setup/issues/new

If not, can you explain how you installed it.

**Comment by samuelnovotny** [comment]
I did restart computer after installing Composer. I also checked PATH, both paths are there. I also used Composer-Setup.exe.

A little while ago, I removed everything and tried to install the Composer again. The result is the same.
Here's my log, it doesn't seem to be anything wrong.
[Setup Log 2020-03-11 #001.txt](https://github.com/composer/composer/files/4318031/Setup.Log.2020-03-11.001.txt)

I have Apache and PHP installed on my computer without XAMPP.

**Comment by johnstevenson** [comment]
Thanks. The log looks fine, but I cannot reproduce this using the same locations as yours.

What is the output from the following?  (note cmd, not powershell)?
```
where php
where composer
```

**Comment by samuelnovotny** [comment]
Here is the output.
![screenshot-4](https://user-images.githubusercontent.com/47574974/76428716-53d2ba80-63ae-11ea-81aa-3be8b8e11aca.png)

**Comment by johnstevenson** [comment]
You need to remove `composer.bat` from your system directory.

Before you do, could you show me its contents so I can try and work out where it came from.

**Comment by samuelnovotny** [comment]
It is blank. I didn't create it. But it helped me. Thank you for your help.

**Comment by johnstevenson** [comment]
Okay, well Composer-Setup.exe would not have created it because it would have had some content (and the installation would have failed because the byte-count wouldn't match). A mystery then.
