### ISSUE TITLE
c:\wamp\www\hotels>composer create -project --prefer -dist laravel hotel "5.8.*"     [RuntimeException]   Invalid working directory specified, ist does not exist.

### ISSUE THREAD

**Issue by johnbaruah** [composer/composer#8698]
c:\wamp\www\hotels>composer create -project --prefer -dist laravel hotel "5.8.*"

  [RuntimeException]
  Invalid working directory specified, ist does not exist.

**Comment by johnstevenson** [comment]
You need to ensure that your commands are formatted properly and do not contain extra whitespace. For example `create-project`, `--prefer-dist` etc.

Unquoted whitespace acts as a delimiter on the command line. So `--prefer -dist` is read as:
- `--prefer`
-  `-d` flag, followed by the directory name

**Comment by johnbaruah** [comment]
Thanks
