### ISSUE TITLE
autoload psr-4 structure question

### ISSUE THREAD

**Issue by davidjr82** [composer/composer#8701]
Just a question. From composer v1.10 I get a warning of autoloading issues in composer v2.0:

https://github.com/composer/composer/blob/3405781f1576512dbd2c9607e3f2ac57826e9711/src/Composer/Autoload/ClassMapGenerator.php#L200

Does this means that the folder structure must be the same than the subnamespaces structure in composer v2? Wasn't the namespaces a way to make independent the logical structure and the physical  structure?

Thanks for your time reading my question!

**Comment by Seldaek** [comment]
I am sorry but I don't quite understand the question.. it would be easier if you shared the warning you see, as well as your autoload configuration. Also please make sure you check with composer 1.10.1 as it fixed a few invalid warnings.

**Comment by davidjr82** [comment]
Hi,

I refactor my code moving folders to get a new structure. But I don't want to change all the namespacing, because it is working and I want it to be as it was. When I move the folders without changing the namespace, I get this kind of warnings (from composer v 1.10, I didn't get them with v 1.9):

`Deprecation Notice: Class App\Providers\EventServiceProvider located in ./app/Interface/Http/Providers/EventServiceProvider.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201`

As you can see, I moved the class that first was in the folder `Providers\EventServiceProvider` from my root `app` source folder to the new folder `Interface/Http/Providers/EventServiceProvider.php`, but I didn't change the namespace.

Is ir required to change all the namespaces when I rearrange the folder structure? If so, why? Shouldn't be the namespace a way to make independent the physical structure from the logical structure?

Thanks!

**Comment by Seldaek** [comment]
It's ok do to as you do, but then you should use a `classmap` type autoloader, and not psr-4, as psr-4 dictates that the path should match the namespace.

**Comment by Seldaek** [comment]
See the spec at https://www.php-fig.org/psr/psr-4/

**Comment by davidjr82** [comment]
So in my app, I had this:

`    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "files": [
            "app/Infrastructure/Support/helpers.php"
        ],
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },`

what should I set in the autoload? Just remove the psr-4 section, and add `app/` to my classmap? Like this?:

`    "autoload": {
        "files": [
            "app/Infrastructure/Support/helpers.php"
        ],
        "classmap": [
            "app/",
            "database/seeds",
            "database/factories"
        ]
    },`

Apart from that, would be any performance penalty for not using psr-4? 

Thanks a lot for the time you are using answering me.

**Comment by davidjr82** [comment]
Ok, so it is working as @Seldaek said. Just wondering if it would have any performance penalty.

Closing and thanks!

**Comment by Seldaek** [comment]
No performance penalty if you use https://getcomposer.org/doc/articles/autoloader-optimization.md#optimization-level-2-a-authoritative-class-maps - the only penalty of not using psr-4 is that if you add a new class with classmap you will need to run `composer dump-autoload` otherwise the new class will not be autoloadable.

**Comment by davidjr82** [comment]
Perfect, thanks a lot!
