### ISSUE TITLE
How to get version constraint string from a package

### ISSUE THREAD

**Issue by sup-ham** [composer/composer#8706]
>  `~1.2` is equivalent to `>=1.2 <2.0.0` 

I developing a composer plugin,  I want get these string `~1.2` from a package that  currenlty  at  instal or update operation
may be following pseudo code understandable for my question. Thanks
```php
    protected function installCode($package)
    {
        $package->getPrettyVersion(); // 1.9.0 the actual version
        $package->getVersionConstraints(); // [ 1.9.0, ~1.2,  ^1.2 ]  as it can be defined by root-project or other package
    }
```

**Comment by stof** [comment]
well, look at `$package->getRequires()` to find the requirements of a package.

The version constraints of requirements don't belong to a package, but to the other packages requiring it. Making a getter on the Package object depend on all other packages does not make sense.
