### ISSUE TITLE
Basic Auth Against GitHub Fails

### ISSUE THREAD

**Issue by derekrprice** [composer/composer#8708]
I am using the instructions on [Increasing the unauthenticated rate limit for OAuth applications](https://developer.github.com/v3/#increasing-the-unauthenticated-rate-limit-for-oauth-applications) from github to set up a CI/CD pipeline with a higher rate limit.

When I run this command:

```
composer -vvv install
```

I get the following output:

```
  - Installing mongodb/mongodb (1.5.2): Using HTTP basic authentication with username "xxxxxxxxxxxxx"
Downloading https://api.github.com/repos/mongodb/mongo-php-library/zipball/9480f994de9f70e2ae5a946b21e6fc04bf5a6c3c
Downloading (connecting...)
Following redirect (2) https://codeload.github.com/mongodb/mongo-php-library/legacy.zip/9480f994de9f70e2ae5a946b21e6fc04bf5a6c3c
Downloading https://codeload.github.com/mongodb/mongo-php-library/legacy.zip/9480f994de9f70e2ae5a946b21e6fc04bf5a6c3c
Downloading (0%)
Failed: [Composer\Downloader\TransportException] 404: The "https://codeload.github.com/mongodb/mongo-php-library/legacy.zip/9480f994de9f70e2ae5a946b21e6fc04bf5a6c3c" file could not be downloaded (HTTP/1.1 404 Not Found)
    Failed to download mongodb/mongodb from dist: The "https://codeload.github.com/mongodb/mongo-php-library/legacy.zip/9480f994de9f70e2ae5a946b21e6fc04bf5a6c3c" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
```

And I expected this to happen:
Normal installation using the specified user and password.

It appears that the authentication provided should be used for api.github.com but not for codeload.github.com.  Running the same two downloads via curl works fine if I do not pass authentication for the codeload URL and fails via curl when I do.  Unfortunately, when I update my auth.json to specify "api.github.com" as the host using HTTP auth, composer completely ignores the configuration and falls back on the unauthenticated API.

**Comment by Seldaek** [comment]
Have you tried using https://getcomposer.org/doc/06-config.md#github-oauth rather than basic auth? I don't think we support the basic auth option very well.

**Comment by derekrprice** [comment]
That was the workaround that I put in place, but this workaround forces me to put my personal authentication token into a CI/CD pipeline application shared by many people.  The right solution here is defining the pipeline as an Application which belongs to my Github Organization and using its client id and secret.

**Comment by Seldaek** [comment]
Yes, indeed using secrets is the way to go. Or alternatively you can use --prefer-source which will do clones instead of downloading zips, it's a bit slower but goes around the API.
