### ISSUE TITLE
Unable to install package located in subdirectory on GitHub

### ISSUE THREAD

**Issue by thomaseadie** [composer/composer#8711]
Currently when a custom repo is specified in composer.json it will only look in the root directory for the project's composer.json file. It would be nice to be able to specify a subdirectory path to where the project is stored.

I came across this missing functionality while trying to install this package: https://github.com/launchdarkly/api-client-php/tree/master/LaunchDarklyApi

There is a packagePath parameter that can be specified in the composer.json file to install from a subdirectory, but it currently applies only to SVN repos.

I took a crack at creating a solution, which can be found here: https://github.com/thomaseadie/composer/commit/a413118fe92907791c8473b0e6702ea12fd02fac

I tested this on the above mentioned GitHub project and it worked, and I added the same functionality for the GitLab and BitBucket driver code while trying to not break the SVN driver, but I haven't tested any of them and don't really know what I'm doing.

**Comment by Seldaek** [comment]
This is not really something we want to support at the moment at least. It was added to svn because of legacy reasons mostly but hasn't really been a necessity in the git days and it does complicate things vs having a consistent and unified repository structure.
