### ISSUE TITLE
Composer does not fallback to vcs repository if local path VCS does not exist

### ISSUE THREAD

**Issue by javiercaride** [composer/composer#8712]
Hi,

Today I upgraded composer from 1.9.3 to 1.10.1 version. I have a project that has two different repositories for a self-library:

- A local repository using path-type repository (to be used in our development laptops to point the library to a local version)
- A vcs repository (to be used in the production builds)

```json
"repositories": [
    {
      "type": "path",
      "url": "../../libraries/smart-places-core",
      "options": {
        "symlink": true
      }
    },
    {
      "type": "vcs",
      "url": "git@bitbucket.org:XXXXXX/smart-places-core.git"
    }
  ]
```

With 1.9.3 version, when I run ```composer install``` in a machine that does not have a local copy of the library, composer is able to fallback to vcs repository and composer ends ok

```
composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Package operations: 113 installs, 0 updates, 0 removals
  - Installing raulfraile/ladybug-installer (v1.0.1): Loading from cache
  - Installing symfony/translation (v2.5.2): Loading from cache
...
  - Installing mobailapps/smart-places-core (dev-dev e1a1ea7): Cloning e1a1ea7f96 from cache
...
Writing lock file
Generating autoload files
```

But if I upgrade composer to 1.10.1 and using the same composer.json I get the following output:

```
composer install
Loading composer repositories with package information

                                                                                                 
  [RuntimeException]                                                                             
  The `url` supplied for the path (../../libraries/smart-places-core) repository does not exist
```

Is this the expected behaviour of the 1.10 release or is it a bug? I read all the release notes and I didn't found anything regarding backward compatibility changes about the use of path-based repositories

Thanks in advance

**Comment by Seldaek** [comment]
The warning was added on purpose to help people figure out when they have a broken config. Your use case is not really something we want to encourage as it is generating broken lock files.. What you can do as a workaround though is define the path as `../../libraries/*` or I guess `../../libraries/smart-places-core*` works too. The wildcard will suppress the warning in case it can not find anything.
