### ISSUE TITLE
Archive exclusion doesn't exclude related dependencies

### ISSUE THREAD

**Issue by bperel** [composer/composer#8716]
I would like only a subdirectory of project A to be included in my Composer package. However, when I require this package in project B, all the package dependencies are added, including those that are not in the exported subdirectory.

```json
{
    ...
    "archive": {
        "exclude": ["/*", "/.*", "!/src/Client"]
    },

    "require": {
        "psr/http-message": "^1.0",
        ...
    }
    ...
}
```

In this example, `psr/http-message` is a dependency that is required in project A, but since none of the source files in `src/Client` require it, I don't want B to have this dependency in its vendor directory.
Since A is a project will a lot of dependencies but `src/Client` is a small subset of project A, the vendor directory of B contains a lot of dependencies that it doesn't need.

Is there a configuration that I missed that allows custom dependencies to be bundled with the package?

**Comment by Seldaek** [comment]
Nope this isn't possible, this is about dependencies not archives..

As a hack, you could put `"provide": {"psr/http-message":"*"}` in B's composer.json, which will make composer think it's installed already and will fulfill A's dependency on it. This technique should absolutely not be used on public packages which are published on packagist.org though as it can make a mess for people depending on your package then.

**Comment by bperel** [comment]
Thank you for your answer :-)
