### ISSUE TITLE
new require-plugin stage and before resolve dependency installs dependencies require-plugin and after than install others

### ISSUE THREAD

**Issue by sonersivri** [composer/composer#8720]
New feature request.
if there is away of install plugins before install require and require-dev some one run plugins and run before install and after and execute scripts. 

pre-dependencies-solving stage cannot be executed if source is in the composer.json dependent library

**Comment by Seldaek** [comment]
This is not something we are looking to support in the future sorry. It adds too much complexity and not enough benefits.
