### ISSUE TITLE
Wrong deprection notices for PSR-4 autoloading in 1.10.x

### ISSUE THREAD

**Issue by aimeos** [composer/composer#8722]
My `composer.json`:

```json
	"autoload": {
		"psr-4": {
			"Aimeos\\MW\\": "lib/mwlib/src/MW/",
			"Aimeos\\MShop\\": "lib/mshoplib/src/MShop/",
			"Aimeos\\MAdmin\\": "lib/mshoplib/src/MAdmin/",
			"Aimeos\\Controller\\Common\\": "controller/common/src/Controller/Common/",
			"Aimeos\\Controller\\Jobs\\": "controller/common/src/Controller/Jobs/",
			"Aimeos\\": "."
		},
		"classmap": [
			"lib/mwlib/src",
			"lib/mshoplib/src",
			"lib/mshoplib/setup",
			"controller/common/src",
			"controller/jobs/src",
			"Bootstrap.php"
		]
	},
	"autoload-dev": {
		"psr-4": {
			"Aimeos\\MW\\": "lib/mwlib/tests/MW/",
			"Aimeos\\MShop\\": "lib/mshoplib/tests/MShop/",
			"Aimeos\\MAdmin\\": "lib/mshoplib/tests/MAdmin/",
			"Aimeos\\Controller\\Common\\": "controller/common/tests/Controller/Common/",
			"Aimeos\\Controller\\Jobs\\": "controller/common/tests/Controller/Jobs/"
		},
		"classmap": [
			"lib/mwlib/tests",
			"lib/mshoplib/tests",
			"controller/common/tests",
			"controller/jobs/tests"
		]
	}
```

Output of `composer diagnose`:

```
Checking composer.json:
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.1
PHP version: 7.3.16
PHP binary path: /usr/bin/php7.3
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

When I run this command:

```
composer dump-autoload
```

I get the following output:

```
...
Deprecation Notice: Class Aimeos\MAdmin\Job\Item\StandardTest located in ./vendor/aimeos/aimeos-core/lib/mshoplib/tests/MAdmin/Job/Item/StandardTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///home/nose/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```

And I expected this to happen:
This happens for all test classes. It happens because the relative paths from the classmap section aren't used when checking the files:
https://github.com/composer/composer/blob/master/src/Composer/Autoload/ClassMapGenerator.php#L159-L207

For example:
- $basePath: /.../vendor/aimeos/aimeos-core
- $filePath: /.../vendor/aimeos/aimeos-core/lib/mshoplib/tests/MAdmin/Job/Item/StandardTest.php

Result in https://github.com/composer/composer/blob/master/src/Composer/Autoload/ClassMapGenerator.php#L190:
- $subPath: MAdmin/Job/Item/StandardTest
- $realSubPath: lib/mshoplib/tests/MAdmin/Job/Item/StandardTest

As $subPath and $realSubPath doesn't match, the deprecation notice is shown. It does also happen if the `autoload-dev` section is removed. The test directories are added even if they aren't mentioned in the `classmap` section. Is this a bug or is our configuration wrong?

**Comment by Seldaek** [comment]
I think the issue is rather coming from your psr-4 entry `"Aimeos\\": "."`, because that makes it scan the entire repository, and any class that did not match yet  according to psr-4 rules will then error. I don't know why you declared this, but if it's for Bootstrap.php I guess you don't need the rule at all as it's included in classmap. If you can try it without that'd be great.

**Comment by Seldaek** [comment]
Note that you need to run `composer dump-autoload -o` to see the warnings.

**Comment by aimeos** [comment]
Works perfectly without `"Aimeos\\": "."`. Thanks a lot!
