### ISSUE TITLE
Funding doesn't properly handle missing "url"

### ISSUE THREAD

**Issue by apfelbox** [composer/composer#8731]
My `composer.json`:

```json
{
    "require": {
        "sentry/sentry-symfony": "^3.4"
    }
}

```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.1
PHP version: 7.4.2
PHP binary path: /usr/local/Cellar/php/7.4.2/bin/php
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

When I run this command:

```
composer fund
```

I get the following output:

![2020-04-02 at 16 00](https://user-images.githubusercontent.com/1032411/78258141-18359700-74fb-11ea-8936-b3290dc1dfa7.png)

And I expected this to happen:
... not throw an error?

---

Background is, that the funding info has a lot of these entries (see `vendor/composer/installed.json`):

![2020-04-02 at 16 00](https://user-images.githubusercontent.com/1032411/78258201-2a173a00-74fb-11ea-9d00-76000e4cd64b.png)

They apparently have no `"url"` key, that's why this fails: 
https://github.com/composer/composer/blob/beb64914a37205f6748552d764d9531d99c7f41e/src/Composer/Command/FundCommand.php#L94

**Comment by stof** [comment]
It looks like there is an issue with Github. Sentry fixed their URL in https://github.com/getsentry/.github/blob/master/FUNDING.yml but when I force an update of the package on packagist, it still see the old value.

**Comment by apfelbox** [comment]
Some validation there wouldn't hurt though, as this is data from external sources and you can't be sure about its formatting.

**Comment by stof** [comment]
Well, packagist rejects the update now. But the validation was added after the invalid data was entered.

**Comment by stof** [comment]
and there is a bug preventing packagist/composer from getting the new metadata.
