### ISSUE TITLE
Github funding info is not properly refreshed when coming from the global repo

### ISSUE THREAD

**Issue by stof** [composer/composer#8732]
The GithubDriver loads the funding info on its own, as the REST API does not expose it (the GraphQL API does). As such, it has to implement the loading of `funding.yml` on its own.
But the way this is done breaks when caching is involved (this can be seen current with the `sentry/sentry-symfony` package on Packagist which keeps saying that the funding config is invalid while the https://github.com/getsentry/.github repo was fixed 8 days ago.

This happens because the github funding info is merged into the metadata before writing to the cache. But the cache key is the commit id, and the funding info loaded from github does not depend on this commit id (and so it can be changed without changing the commit).

**Comment by stof** [comment]
Refs #8731

**Comment by weierophinney** [comment]
I can note this as well. We recently added a FUNDING.yml to our organization `.github` repos, but we're not seeing Composer recognize it unless we add it directly to the individual packages, even after pushing a new release. I actually assumed Composer didn't support it at the organization level until I searched for issues here.

**Comment by Seldaek** [comment]
What @stof describes is correct and it means it requires a commit in the package repo (in default branch) to see the .github repo info update. We'll see if that can be fixed...

That doesn't seem to explain your problem though @weierophinney if you tagged a release I assume you had new commits in default branch too, or not?

**Comment by Seldaek** [comment]
Nah seems like sentry/sentry still shows stale data despite having new commits on master, so I guess there is a worse problem here than I assumed.

**Comment by stof** [comment]
Tagging a release might not involve a new commit. You could tag the existing commit.

**Comment by Seldaek** [comment]
Sentry actually got fixed now as they just pushed a commit on default branch. I don't really see how we can fix this aside from throwing out caching entirely.. Any suggestions? Otherwise I'll close as a limitation we just have to live with.

**Comment by stof** [comment]
@Seldaek the info loaded from default branches could be cached separately, and merged with the info coming from the commit after reading the cache (instead of merging it with the commit info before writing the cache)

**Comment by weierophinney** [comment]
> That doesn't seem to explain your problem though @weierophinney if you tagged a release I assume you had new commits in default branch too, or not?

There _were_ new commits made before tagging, and those happened _after_ we'd added the FUNDING.yml at the organization level.

What is your recommendation at this point? We have some scripts we've used in the past for mass-updating our repos, so that _is_ an option. We'd hoped to have that information centralized, however, so we can update it in one place. If that's not an option, we just need to know so we can plan accordingly.

Thanks again!

**Comment by Seldaek** [comment]
Definitely keep this in the org-level .github repo. I'll take a look tomorrow at handling this better. Not sure we can split the caches though as the versions which are already existing on packagist are completely skipped to save CPU cycles. But if you add a commit in a package repo it should definitely update it, I need to make sure that works.

**Comment by Seldaek** [comment]
Looking at this again, it just doesn't seem worth the waste of an extra one or two requests on every package update just to make sure we update faster, as the funding info is typically something that does not change very often. So I'll have to leave it as is, and it means it'll sometimes be out of date until the repo's default branch updates.
