### ISSUE TITLE
Optimized autoloader fails on virtual packages (in a special case)

### ISSUE THREAD

**Issue by umulmrum** [composer/composer#8735]
My `composer.json`:

```json
{
    "name": "app/app",
    "type": "project",
    "require": {
        "php-http/httplug-bundle": "^1.18",
        "php-http/guzzle6-adapter": "^2.0"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.1
PHP version: 7.4.4
PHP binary path: /usr/local/bin/php
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

When I run this command:

```
composer remove php-http/guzzle6-adapter

---

composer install --no-dev --optimize-autoloader
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
16 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

---

Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
16 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

guzzle6-adapter is not removed from file system but IS removed from composer.json. For me the main problem is that the generated classmap does NOT contain classes from guzzle6-adapter then. Deleting the vendor dir completely and reinstalling makes no difference.

And I expected this to happen:

One of these:
- Error message on removal attempt for guzzle6-adapter, as it is still required by httplug-bundle (although it's only indirectly required as httplug-bundle requires the virtual package php-http/client-implementation which guzzle6-adapter provides).
- Uninstall both packages.
- Classes are part of the classmap (note that the classmap is correct if `--no-dev` is NOT used).

This issue can be avoided by simply not removing guzzle6-adapter. Still this is a pitfall that cost me some time now, so might be worth fixing for others, too. Thanks for supporting!

**Comment by Seldaek** [comment]
Composer 2 will fix this. Instead of letting you shoot yourself in the foot there with the remove command, it returns:

![image](https://user-images.githubusercontent.com/183678/78679707-dd60a400-78ea-11ea-90fa-0ebf4533d71e.png)
