### ISSUE TITLE
Case sensitive folders

### ISSUE THREAD

**Issue by ellllllen** [composer/composer#8739]
We are having issues with packages that are uppercase i.e. `"name": "Company/package"`. When we perform a `composer update` the composer.lock gets created with the name of `company\package`. This causes issues where we need to refer to files within the vendor/**C**ompany/package as it puts the package in vendor/**c**ompany/package

We are migrating are packages to lowercase but this will take a while and this is causing us issues in the meantime.

We would appreciate any help or suggestions.

Thanks in advance :)

**Comment by ellllllen** [comment]
We have managed to get around it by changing the text in the vensor/composer/autoload_psr4.php and installed.json to uppercase and running `composer update` again.

**Comment by Seldaek** [comment]
This sounds like an autoload config issue which you should be able to solve with the right config. There is not really another solution to this sorry. Packages should ideally be self-contained units, defining their own autoload rules, then it doesn't matter which directory name they are installed in.
