### ISSUE TITLE
Package naming in 2.0 and the asset ecosystem

### ISSUE THREAD

**Issue by cebe** [composer/composer#8749]
Hi, I wanted to make you aware of an impact of the package naming restriction in 2.0, which is going to affect users of https://asset-packagist.org/ and [composer-asset-plugin](https://github.com/fxpio/composer-asset-plugin/issues/333). This is not about whether one should use these (I know your opinion on this @Seldaek :smiley:) but the fact that upgrading to Composer 2.0 becomes really hard (currently impossible) for people on this ecosystem.

### The issue

Composer 2.0 will restrict the use of `-` (dashes). When converting npm package names which include a vendor name (`vendor/package`) we can not keep the `/` because having multiple `/` in a package name has obvious issues (as discussed in #7975). Currently the `/` is converted to `--` (see [docs](https://github.com/fxpio/composer-asset-plugin/blob/fe3943dfddbb599d77002734a7077dc5d98cfe4f/Resources/doc/index.md#work-with-the-npm-scopes)). Double dashes however are not valid anymore in Composer 2.0.

### How to solve this issue?

There are two ways to solve this:

1. The easiest solution: allow multiple dashes in package names.
2. Come up with a different replacement when converting package names in `composer-asset-plugin`. 
  Given that we find a replacement that matches the naming restrictions and does not cause other problems (which is already quite hard), this also means a lot of upgrade work as people need to rename all their package requirements.
  We also we need a breaking change in the repository of asset-packagist as well as a new major version of composer-asset-plugin, which is incompatible with the current version, meaning a composer.json file will work either with version 1 or 2 but never with both. The fact that the plugin needs to be installed globally will make it very hard to work on two projects with different state. 

Allowing multiple dashes in package names is not a huge problem for composer and does not introduce any overhead as far as I see. Compared to the amount of work needed to make the composer-asset-plugin/asset-packagist ecosystem compatible with Composer 2.0.

Thank you!

Btw, docs should be adjusted:

https://github.com/composer/composer/blob/master/doc/04-schema.md#name

(I can help with that once this issue is solved)

**Comment by cebe** [comment]
should the regex be added to the json schema?

https://github.com/composer/composer/blob/40a35abb9423e16f8bafcb1ed1b7e027881b0422/res/composer-schema.json#L8-L11

**Comment by Seldaek** [comment]
Yup that'd probably make sense for 2.0, it might make it a hard fail by default as well and allow us to remove the rest of the validation code, not sure. But anyway should be a separate PR afterwards I guess.

**Comment by Seldaek** [comment]
Keeping open as the schema change should probably still happen in master, and we should also check whether it errors correctly when a require or name is defined with an invalid package name.

**Comment by cebe** [comment]
While checking the docs about naming, I also found the following thing: 

https://github.com/composer/composer/blob/be1ddcf29356cea48c87ff8a8d670311f3d78a38/doc/05-repositories.md#pear

PEAR repositories also do not work in 2.0:

Running composer in a directory with the composer.json from the docs example, gives the following:

```
$ ../bin/composer install

                                                                                                                                                                     
  [RuntimeException]                                                                                                                                                 
  require.pear-pear2.php.net/PEAR2_Text_Markdown is invalid, it should not contain uppercase characters. Please use pear-pear2.php.net/pear2_text_markdown instead.  
                                                                                                                                                                     

$ ../bin/composer --version

                                                                                                                                                                     
  [RuntimeException]                                                                                                                                                 
  require.pear-pear2.php.net/PEAR2_Text_Markdown is invalid, it should not contain uppercase characters. Please use pear-pear2.php.net/pear2_text_markdown instead.  
                                                                                                                                                                     

```

**Comment by cebe** [comment]
Thank you, @Seldaek!

**Comment by francoispluchino** [comment]
@Seldaek Thank you!
