### ISSUE TITLE
Update/downgrade to specific version without updating composer.json

### ISSUE THREAD

**Issue by caugner** [composer/composer#8756]
My `composer.json`:

```json
{
    "name": "dev/example",
    "require": {
        "google/cloud-translate": "^1.7.0"
    }
}
```

(Note: Let the dependency be locked at `1.7.0` or `1.7.2`, depending on the use-case below.)

Output of `composer diagnose`:

<details>
<pre>
$ composer diagnose
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (1.9.3 => 1.10.1)
Composer version: 1.9.3
PHP version: 7.3.16
PHP binary path: C:\php\php.exe
</pre>
</details>

When I run this command:

```
composer update google/cloud-translate:1.7.1
```

I get the following output:

```
Package "google/cloud-translate:1.7.1" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

And I expected this to happen:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 updates, 0 removals
  - Updating google/cloud-translate (v1.7.0 => v1.7.1): Downloading (100%)
Writing lock file
```

## Explanation

This requirement has already been requested in #3387, which has been closed referencing `composer require vendor/package:version` as the suggested solution.

IMO the `require` command is not necessarily an alternative, because it updates the `composer.json` as a side-effect, which may not always be desired and especially reduces the version space for conflic resolution and further updates (when forgetting to extending the version constraint again later).

A workaround would be to `composer require vendor/package:version`, revert the changes made by composer to `composer.json` and then run `composer update --lock`.

### Use case 1: Update to specific version

Say the latest version of `google/cloud-translate` is `v1.7.2` and I'm at `v1.7.0`. Instead of going directly to `v1.7.2`, I would like to go via `v1.7.1` (and commit that state to make it easier to `git bisect` later), but without changing the `composer.json`, because `v1.7.0` was working fine.

### Use case 2: Downgrade to specific version

Say I ran `composer update` and `google/cloud-translate` was updated from `v1.7.0` directly to `v1.7.2`, but now I discover a regression, i.e. an issue with `v1.7.2` that was not present with `v1.7.0`. I would like to go via `v1.7.1` in order to find the latest version not having this issue.

**Comment by Seldaek** [comment]
Right now, composer 2.0 will completely prevent doing this, as the trick with the lock file that you suggest does not work anymore. So it's probably a good time to add an official way to achieve this.

We are thinking it'd be best to have a flag on the update command to add a temporary additional constraint on any package. Something like `composer update --with foo/bar:1.7.1`. That would do a full update, but if you only want to update foo/bar you can use the shorthand  `composer update foo/bar:1.7.1`.

Any feedback on naming or others welcome.

**Comment by caugner** [comment]
IMO the naming you suggest is perfect. 👌

**Comment by Seldaek** [comment]
Implementation is at https://github.com/composer/composer/pull/8860 if you want to give it a shot or at least have a look. It works well and seems like a nice addition 👍

**Comment by froemken** [comment]
For me this ticket is not solved. Question was how to downgrade a sub-package without updating composer.json. I just have tried the --with option

`php ../tools/bin/composer.phar update "typo3/cms-*" --with doctrine/dbal:~2.11.2 --with-all-dependencies`

and

`php ../tools/bin/composer.phar update doctrine/dbal:~2.11.2`

but both results in 

`Only root package requirements can receive temporary constraints and doctrine/dbal is not one`

Have a look into TYPO3 CMS version 10.4.9: https://packagist.org/packages/typo3/cms-core#v10.4.9
`doctrine/dbal`: Everything above 2.10 is allowed. In composer.lock version 2.12.1 was installed.

Now I try to update to TYPO3 version 10.4.17: https://packagist.org/packages/typo3/cms-core#v10.4.17
`doctrine/dbal` 2.12 is NOT allowed by typo3/cms and because of another package doctrine 2.13 and higher is NOT allowed.

So, the only possibility is to downgrade doctrine/dbal to version 2.11. But I don't want to do that in my composer.json. It's the job of typo3/cms and/or composer to install the correct versions and I don't want to check all the version constraints within the next updates.

Question is still valid: How do I downgrade a sub-package without modifying the composer.json?

**Comment by caugner** [comment]
@froemken My issue was about a root requirement, but your use case makes sense to me (and I have been in the same situation about a week ago in the context of https://github.com/psalm/psalm-plugin-laravel/pull/147), so it would be great if you could open a new issue to request `--with` support for indirect dependencies.

**Comment by froemken** [comment]
It seems to be a very specific problem at customers server. Don't get it. Locally, composer downgrades related packages automatically to match version dependencies. As I have overwritten customers composer.lock with my solution I can't check again for any other issues anymore. So, without a "broken" composer.lock it does not make sense to create a new ticket. But of cause I will, if I stumble over such a problem in future.

**Comment by louisitvn** [comment]
> For now I have solved it that way:
> 
> php ../tools/bin/composer.phar require doctrine/dbal:~2.11.2 php ../tools/bin/composer.phar update "typo3/cms-*" --with-all-dependencies php ../tools/bin/composer.phar remove doctrine/dbal
> 
> Results in:
> 
> Removal failed, doctrine/dbal is still present, it may be required by another package. See `composer why doctrine/dbal`.
> 
> composer.json is clean again and doctrine is still installed. fine.

This is the PERFECT workaround for this EXACT matter. It just works exactly the way you need it to be: update a particular package (upgrade or downgrade, usually a downgrade) in the composer.lock file without modifying the composer.json.
