### ISSUE TITLE
Composer update on AppVeyor fails with 2.0 snapshot

### ISSUE THREAD

**Issue by kubawerlos** [composer/composer#8757]
When I run this command:

```
php C:\tools\composer.phar update --optimize-autoloader --no-interaction --no-progress --prefer-stable --no-ansi
```

I get the following output:

```
The "hirak/prestissimo" plugin was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Loading composer repositories with package information
Updating dependencies
https://repo.packagist.org could not be fully loaded (SSL certificate problem: unable to get local issuer certificate), package information was loaded from the local cache and may be out of date
                                                                   
  [Composer\Downloader\TransportException]                         
  SSL certificate problem: unable to get local issuer certificate  
                                                                   
update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
Command exited with code 1
```

And I expected this to happen: normal update

When I use https://getcomposer.org/composer-stable.phar all is fine.
Here is the run on snapshot with `-vvv --profile`: https://ci.appveyor.com/project/keradus/php-cs-fixer/builds/32072541/job/3qx5rsy53tpb8vta
Here is the run on stable with `-vvv --profile`: https://ci.appveyor.com/project/keradus/php-cs-fixer/builds/32072674/job/7c8onqyoa49v3xjj?fullLog=true

All reproduced here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4906

I cannot reproduce it on my PC - all works fine.

Should I also run `composer diagnose` on AppVeyor?

**Comment by stof** [comment]
hmm, it looks like the new downloader based on curl has issues for the TLS certificate on Appveyor.

@Seldaek is the new downloader using `composer/ca-bundle` or does it rely on PHP's default CA config ?

**Comment by Seldaek** [comment]
@kubawerlos I could not reproduce the issue but I did find the most likely cause and fixed that so please confirm that it's fixed for you with latest snapshot.

**Comment by Seldaek** [comment]
@stof it was using it as it used to for RemoteFilesystem but the options were then not passed down where they needed to, so curl capath was never configured

**Comment by kubawerlos** [comment]
@Seldaek thanks, confirming, all works now with snapshot here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4907
