### ISSUE TITLE
Arrays are not allowed in class constants 

### ISSUE THREAD

**Issue by Drewzar** [composer/composer#8759]
Composer version 1.10.3 2020-04-09 16:26:35

My `composer.json`:

```json
{
    "require": {
        "guzzlehttp/guzzle": "^6.0",
        "smarty/smarty": "3.1.12",
        "musicglue/sidekiq-job-pusher": "dev-master",
        "symfony/yaml": ">=2.0,<3.0",
        "league/flysystem": "1.0.4",
        "league/flysystem-aws-s3-v3": "1.0.9",
        "league/flysystem-memory": "^1.0",
        "league/glide": "dev-master",
        "aws/aws-sdk-php": "^3.4",
        "codeguy/upload": "dev-master",
        "cloudinary/cloudinary_php": "dev-master",
        "drewm/mailchimp-api": "^2.2",
        "firebase/php-jwt": "^4.0",
        "paypal/rest-api-sdk-php": "*"
    },
    "require-dev": {
        "phpunit/phpunit": "^4.8"
    },
    "minimum-stability": "dev",
    "config": {
        "bin-dir": "bin/"
    },
    "autoload": {
        "psr-0": {
            "Liftopia": "lib/"
        }
    }
}
```

Output of `composer diagnose`:

```
Cannot create cache directory /home/me/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/me/.composer/cache/files/, or directory is not writable. Proceeding without cache
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.smarty/smarty : exact version constraints (3.1.12) should be avoided if the package follows semantic versioning
require.musicglue/sidekiq-job-pusher : unbound version constraints (dev-master) should be avoided
require.league/flysystem : exact version constraints (1.0.4) should be avoided if the package follows semantic versioning
require.league/flysystem-aws-s3-v3 : exact version constraints (1.0.9) should be avoided if the package follows semantic versioning
require.league/glide : unbound version constraints (dev-master) should be avoided
require.codeguy/upload : unbound version constraints (dev-master) should be avoided
require.cloudinary/cloudinary_php : unbound version constraints (dev-master) should be avoided
require.paypal/rest-api-sdk-php : unbound version constraints (*) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: PHP Fatal error:  Arrays are not allowed in class constants in phar:///usr/bin/composer/src/Composer/SelfUpdate/Versions.php on line 24

Fatal error: Arrays are not allowed in class constants in phar:///usr/bin/composer/src/Composer/SelfUpdate/Versions.php on line 24
```

When I run this command:

```
self-update
```

I get the following output:

```
PHP Fatal error:  Arrays are not allowed in class constants in phar:///usr/bin/composer/src/Composer/SelfUpdate/Versions.php on line 24

Fatal error: Arrays are not allowed in class constants in phar:///usr/bin/composer/src/Composer/SelfUpdate/Versions.php on line 24
```

And I expected this to happen:
It updates 😄

**Comment by Drewzar** [comment]
Same issue with `Composer version 1.10.4 2020-04-09 17:05:50`

**Comment by plessbd** [comment]
I believe this is an issue with the version of PHP
I am seeing this on a project that still relies on PHP 5.4

**Comment by Drewzar** [comment]
We are currently running on this version:

```
PHP 5.5.9-1ubuntu4.26 (cli) (built: Sep 17 2018 13:46:30)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

**Comment by jessejessee** [comment]
We are having the same issue and are running `PHP 5.4.39`

**Comment by Tobion** [comment]
https://www.php.net/manual/en/language.constants.syntax.php
> From PHP 5.6 onwards, it is possible to define a constant as a scalar expression, and it is also possible to define an array constant.

https://github.com/composer/composer/commit/ccc8829ed963c8add98a60d88ad3ae6d8e7f11de

**Comment by Seldaek** [comment]
Fixed by 1.10.5 but you will have to install that from scratch from https://getcomposer.org/download/ as self-update is broken for you.

Also.. please upgrade your PHP versions, really using these age old versions there is no excuse anymore..

**Comment by Seldaek** [comment]
As a reminder https://www.php.net/supported-versions.php

**Comment by plessbd** [comment]
Most of us do not need to be reminded we are running on very old software.

Unfortunately (for some of us), these versions are still supported by Red Hat until the EOL of the respective release of the software.  Since that is what some institutions still use that is what we use.  Trying to get people to change is not always the easiest, and upgrading is slow.

https://access.redhat.com/security/updates/backporting

**Comment by Tobion** [comment]
@Seldaek do you not plan to increase the php requirement for composer v2?

**Comment by plessbd** [comment]
composer requirements are also set at `"php": "^5.3.2 || ^7.0",`

https://github.com/composer/composer/blob/40a35abb9423e16f8bafcb1ed1b7e027881b0422/composer.json#L25

**Comment by Seldaek** [comment]
I do realize it's mostly not by choice that people are stuck on old versions, which is why yes v2 will still support down to 5.3.2, so we can allow everyone to migrate to v2. Still had to rant about it tho sorry :)

**Comment by stof** [comment]
@Seldaek the drawback of that is that the composer phar has to ship with unmaintained versions of symfony components (and for instance, it still won't have support for `--`)

**Comment by Seldaek** [comment]
@stof yes, we'll have to see once 2.0 is further how to best proceed there. One option is to ship a second phar for more modern PHP with different dependencies, but that can cause a bit of a mess for issue reports. Other option is to start working on 3.0 immediately after 2.0 is out and drop old PHP versions then. Or last option would be dropping older php versions in 2.1 or something. The main thing is that I wanted to make sure all users could upgrade to 2.0, including new repository format. But I don't want to keep maintaining for 5.3 forever. It's time to turn the page somehow.. Anyway I'll add a new issue to keep track of this.
