### ISSUE TITLE
Composer 2.0 issues with installing COPs

### ISSUE THREAD

**Issue by sicksix** [composer/composer#8768]
I am unable to install COPs because of the new composer 2.0.  Any ideas?
https://github.com/seblucas/cops

pi@BOOK:/var/www/html/ebooks $ php composer.phar global require "fxp/composer-asset-plugin:~1.1"
Changed current directory to /home/pi/.config/composer
./composer.json has been created
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - fxp/composer-asset-plugin v1.1.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.
    - fxp/composer-asset-plugin v1.1.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.
    - fxp/composer-asset-plugin v1.1.2 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.
    - fxp/composer-asset-plugin v1.1.3 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.
    - fxp/composer-asset-plugin v1.1.4 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.
    - fxp/composer-asset-plugin v1.2.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.
    - fxp/composer-asset-plugin v1.2.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.
    - fxp/composer-asset-plugin v1.2.2 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.
    - fxp/composer-asset-plugin v1.3.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.
    - fxp/composer-asset-plugin v1.3.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.
    - fxp/composer-asset-plugin v1.4.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.
    - fxp/composer-asset-plugin v1.4.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.
    - fxp/composer-asset-plugin v1.4.2 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.
    - fxp/composer-asset-plugin v1.4.3 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.
    - fxp/composer-asset-plugin v1.4.4 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.
    - fxp/composer-asset-plugin v1.4.5 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.
    - fxp/composer-asset-plugin v1.4.6 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.
    - Root composer.json requires fxp/composer-asset-plugin ~1.1 -> satisfiable by fxp/composer-asset-plugin[v1.4.6, v1.4.5, v1.4.4, v1.4.3, v1.4.2, v1.4.1, v1.4.0, v1.3.1, v1.3.0, v1.2.2, v1.2.1, v1.2.0, v1.1.4, v1.1.3, v1.1.2, v1.1.1, v1.1.0].

You are using a snapshot build of Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report an issue to them to ask them to support Composer 2. To work around this you can run Composer with --ignore-platform-reqs, but this will also ignore your PHP version and may result in bigger problems down the line.

Installation failed, deleting ./composer.json.

**Comment by stof** [comment]
Well, that plugin is not yet compatible with Composer 2. That's something you should report to the plugin, not to composer (btw, the end of the output is precisely telling you about that)

**Comment by Seldaek** [comment]
Alternatively, `composer self-update --stable` will get you back to composer 1.x
