### ISSUE TITLE
 The requested package exists but these are rejected by your constraint.

### ISSUE THREAD

**Issue by smohadjer** [composer/composer#8769]
I'm trying to install a library I have on github using composer and even though I have a release on github tagged as 3.1.0, composer throws an error like this:
```
The requested package smohadjer/filterlist 3.1.0 exists as 
smohadjer/filterlist[dev-master] but these are rejected by your constraint.
```

I can install it when in require I use "dev-master" instead of "3.1.0", but I want to know why I can't use my released version. Thanks.

My `composer.json`:
```json
    "require": {
        "smohadjer/filterlist": "3.1.0"
    },
```

When I run this command:
```
composer update
```

**Comment by villfa** [comment]
You should probably set `"minimum-stability": "dev"` in your `composer.json` file.

See documentation for more details: https://getcomposer.org/doc/04-schema.md#minimum-stability

**Comment by smohadjer** [comment]
Thanks, but is there a way to specify the package I'm loading as stable so I don't need to change minimum-stability? The package I'm loading has a released version on github, so I'm not sure why composer considers it not stable in the first place. I also noticed that if I rename the release tag of package on github from 3.1.0 to v3.1.0 composer stops complaining, so this kind of feels like a bug in composer.

**Comment by Seldaek** [comment]
The problem is your tag 3.1.0 had no composer.json so composer ignored it https://github.com/smohadjer/filterList/blob/3.1.0/composer.json - while v3.1.0 does so it loads fine https://github.com/smohadjer/filterList/blob/v3.1.0/composer.json

Also please note the version field is best left out of the composer.json - see https://getcomposer.org/doc/04-schema.md#version

**Comment by smohadjer** [comment]
Thanks a lot @Seldaek

**Comment by andreshg112** [comment]
I created tags and releases, and published the repo to Packagist. Nothing worked! I had to add the repository to the "repositories" keys in composer.json:

    ```
"repositories": {
        "andreshg112/aws-sns": {
            "type": "vcs",
            "url": "https://github.com/andreshg112/aws-sns.git"
        }
    }
```

**Comment by Seldaek** [comment]
@andreshg112 could it be you are still using Composer 1.x? If so you really should upgrade.. See https://blog.packagist.com/deprecating-composer-1-support/

**Comment by andreshg112** [comment]
@Seldaek, yes! That's an old project I was requested to upgrade the Laravel version. Thanks for mentioning that!
