### ISSUE TITLE
Exclusive composer respository support

### ISSUE THREAD

**Issue by Ayesh** [composer/composer#8776]
Composer v2's repository configuration is awesome it will be quite useful! Thank you for all of your time and efforts on them.

I would like to propose a new `exclusive` setting for repositories. 

```json
{
    "repositories":[
        {
            "type":"composer",
            "url":"https://packages.drupal.org/8",
            "exclusive": ["drupal/*"]
        }
    ],
}
```

With `only`, if a package is not found in the given repository, composer still looks up that package in lower priority repos. I think an `exclusive` setting can help force Composer prevent looking for that package in any other repository. 

For example, the Drupal repo with `exclusive=drupal/*` will prevent composer from looking up `drupal/token` in `packagist.org` or any other repo. This can work as a neat vendor-exclusive security feature. If you have Drupal repo added with exclusivity, it is guaranteed that none of the lower priority will be able to take over any package that match those configured, even if the Drupal repo doesn't host a given package. 

If you think this can be useful feature, I'd be happy to send a PR as well. Thank you 🙏.

**Comment by Seldaek** [comment]
Implementation wise I think this would be fairly easy to do in FilterRepository by returning the requested names matching exclusive rules in namesFound, regardless if they were found or not.

As for do we want this, I am not sure it brings a lot of value, but it also is fairly harmless to add so I'd tend to say why not. @naderman any opinion on this?

**Comment by Ayesh** [comment]
Thanks @Seldaek. You are right it probably wouldn't bring a lot of value at a security point-of-view because the repos need to be trusted anyway.

I suppose the predictability is a good use case. This is an extreme one with a lot of imagination: If a team uses `example-org` namespace and a private repo to host them, someone can claim that same namespace in `packagist.org`, and deliver malicious packages if a package was pulled from private repo. `wpackagist-theme` namespace is currently not claimed in `packagist.org`, and someone could deliver malicious packages when a theme is pulled from the WordPress repo, which happens a few times a year.

**Comment by naderman** [comment]
I think this is actually going to result in some levels of confusion. e.g. what does exclusive mean if there is a higher priority repository which offers something by that name? Either we say that's okay, then "exclusive" is confusing, or we say that's not okay, then we make it impossible to fork packages in such a repository and e.g. add them as a vcs repo above temporarily. I'm not sure the confusion this may cause is worth adding this extra option, but I am open for maybe some better/alternative proposal, although I don't know what that would look like?

**Comment by Seldaek** [comment]
The naming is indeed confusing when seen like that. What it does is disallow lower-prio repos from using the names defined, but indeed it has no effect on higher-prio ones. I don't know if a name change would fix this, I really have no idea what an appropriate name would be. Otherwise I'd say we just proceed without this for now and see if there is any more demand/interest then maybe it can be worth adding later. It's not really blocking a 2.0.

**Comment by Ayesh** [comment]
Thank you for your inputs, and I absolutely support marking this as low prio to get 2.0 moving 👍.

**Comment by Seldaek** [comment]
I think this is better fixed now by the addition of `available-package-patterns` to the repository's packages.json, so the repo itself can declare what vendors it's serving, by e.g. returning `"available-package-patterns":["drupal/*"]`.
