### ISSUE TITLE
PEAR Repositories do not work in 2.0

### ISSUE THREAD

**Issue by cebe** [composer/composer#8778]
While checking the docs about naming, I also found the following thing: 

https://github.com/composer/composer/blob/be1ddcf29356cea48c87ff8a8d670311f3d78a38/doc/05-repositories.md#pear

PEAR repositories also do not work in 2.0:

Running composer in a directory with the composer.json from the docs example, gives the following:

```
$ ../bin/composer install

                                                                                                                                                                     
  [RuntimeException]                                                                                                                                                 
  require.pear-pear2.php.net/PEAR2_Text_Markdown is invalid, it should not contain uppercase characters. Please use pear-pear2.php.net/pear2_text_markdown instead.  
                                                                                                                                                                     

$ ../bin/composer --version

                                                                                                                                                                     
  [RuntimeException]                                                                                                                                                 
  require.pear-pear2.php.net/PEAR2_Text_Markdown is invalid, it should not contain uppercase characters. Please use pear-pear2.php.net/pear2_text_markdown instead.  
                                                                                                                                                                     

```

Renaming the package to lowercase:

```
$ ../bin/composer install
The "wikimedia/composer-merge-plugin" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "fxp/composer-asset-plugin" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
Loading composer repositories with package information
Updating dependencies
Initializing PEAR repository https://pear2.php.net
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires pear-pear2.php.net/pear2_text_markdown, it could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Root composer.json requires pear-pear2/pear2_http_request, it could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
You are using a snapshot build of Composer 2, which may be the cause of the problem. Run `composer self-update --stable` and then try again. In case it solves the problem, please report an issue mentioning Composer 2.
```

Maybe the strict naming restriction should be limited to native composer ecosystem and not be applied to fetch packages from external sources?

**Comment by cebe** [comment]
Well, seems it also does not work in 1.10.5...

```
$ composer install
Deprecation warning: require.pear-pear2.php.net/PEAR2_Text_Markdown is invalid, it should not contain uppercase characters. Please use pear-pear2.php.net/pear2_text_markdown instead. Make sure you fix this as Composer 2.0 will error.
Deprecation warning: require.pear-pear2/PEAR2_HTTP_Request is invalid, it should not contain uppercase characters. Please use pear-pear2/pear2_http_request instead. Make sure you fix this as Composer 2.0 will error.
Loading composer repositories with package information
Initializing PEAR repository https://pear2.php.net
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package pear-pear2.php.net/pear2_text_markdown could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package pear-pear2/pear2_http_request could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by Seldaek** [comment]
TBH I wonder if anyone still uses this.. Maybe should be soft-deleted in v2 until/unless someone complains. I'll have a look at that. Just ignore for now.

**Comment by naderman** [comment]
:+1: on deleting pear support in v2

**Comment by glensc** [comment]
here's some thoughts in case someone wonders here and misses pear integration.

1. most of the active projects in pear do have also composer.json, if not, you can fork, add the composer.json and use "type: vcs" to the forked repository: https://getcomposer.org/doc/05-repositories.md#vcs
2. you should be still able to define the pear package via "type: package": https://getcomposer.org/doc/05-repositories.md#package-2
3. you could setup older version of satis, publish the result, and then use packages via "type: composer". such example project: https://github.com/eventum/composer

**Comment by bytestream** [comment]
> TBH I wonder if anyone still uses this.. Maybe should be soft-deleted in v2 until/unless someone complains. I'll have a look at that. Just ignore for now.

@Seldaek https://dev.horde.org/imap_client/install.php would be one example of a large, well known, PHP lib distributing via pear repository. Usage may be increasing given php-imap extension is dead, lacking oauth support and looming deadlines from Google+Microsoft forcing a switchover to OAuth only authentication which php-imap does not support.

**Comment by naderman** [comment]
@bytestream As per their site which you linked to, it can be installed via Composer too.

**Comment by bytestream** [comment]
@naderman I'm using that and it results in:

```
  RuntimeException]                                      
  The PEAR repository has been removed from Composer 2.0  
```

**Comment by naderman** [comment]
@bytestream Sorry didn't realize you must have gotten this via email before I deleted again, I missed that they only give Composer instructions for the now removed PEAR support. So indeed it doesn't look like one can currently install their packages without using one of the three solutions @glensc suggested.

**Comment by bytestream** [comment]
Given the somewhat whimsical appearance of @Seldaek statement I quoted above, hope you will reconsider removing pear. 

Nonetheless I'll check with Horde, but there's PRs dating back to 2019 so I'm not very confident :)
_ref https://wiki.horde.org/Project/NoMorePear_

**Comment by glensc** [comment]
@bytestream you can still use composer 1.x for pear repositories. and perhaps go with the third option I suggested to build satis repository, because even in 1.x the type:pear made composer very slow to operate, so better setup satis proxy if pear support is not going down in near future.

**Comment by Seldaek** [comment]
Yeah I don't think we're going to bring back pear support because of one project. PEAR isn't shipping with PHP anymore, it's really about time people move on.

**Comment by bytestream** [comment]
> so better setup satis proxy if pear support is not going down in near future.

@glensc thanks for the suggestion. I've tried this route and now Composer 2 complains:
```
is invalid, it should not contain uppercase characters.
```

Any suggestion for that?

**Comment by glensc** [comment]
@bytestream I don't know what you actually did. make a reproducible bug report. publish it as gist perhaps.

you do not need to use uppercase names for pear packages, `pear-pear.php.net/text_diff` should do fine. some of the popular pear packages also exist on composer like pear/db, pear/mail, pear/xml_rpc...

**Comment by bytestream** [comment]
@glensc thanks for the quick reply. You can see Satis here: https://github.com/supportpal/satis/tree/main

I require it via `composer require pear-pear.horde.org/horde_imap_client`

I suspect the problem is versioned package names are capitalised
https://raw.githubusercontent.com/supportpal/satis/gh-pages/include/all%2431c31e95b7f3146b4aa3ee43b249d420ba925db0.json contains:
```
"pear-pear.horde.org/horde_imap_client": {
    "1.0.0": {
        "name": "pear-pear.horde.org/Horde_Imap_Client",
```

**Comment by glensc** [comment]
@bytestream maybe create a patch to composer 1.x to lowercase package names (in all occurrences) in pear support, and satis option to use it?

or just post-process your json files with sed:

```sh
sed -i -e 's/Horde_Imap_Client/horde_imap_client/g' *.json
```

**Comment by ChristophWurst** [comment]
> @Seldaek https://dev.horde.org/imap_client/install.php would be one example of a large, well known, PHP lib distributing via pear repository.

cc @mrubinsk @yunosh

**Comment by yunosh** [comment]
FWIW next major versions of all Horde libraries and applications will be composer-only too.

**Comment by ChristophWurst** [comment]
Thanks a lot. I'm happy to assist develop & test if you need any help :)

**Comment by bytestream** [comment]
Yeah @yunosh happy to help. Is there a place we can coordinate?

**Comment by yunosh** [comment]
https://lists.horde.org/mailman/listinfo/dev is the place where things are being discussed mostly, with references to the relevant repos and PRs.

**Comment by Herz3h** [comment]
We currently use horde_imap_client and it prevents us from upgrading to composer 2. So for now we stick to  v1, but upon uploading a package to packagist, it says: 


`This package is not installable via Composer 1.x...`
 Is there a workaround ? we can't use v2 since we need pear repository.

**Comment by stof** [comment]
you need to download it with composer 2 first, to make it appear in the composer 1 metadata of packagist.org
