### ISSUE TITLE
Any way to enforce a given composer version to be used within the project?

### ISSUE THREAD

**Issue by kbuczynski-nashpl** [composer/composer#8781]
Hi
I was wondering is there a way to enforce a composer version to be used within the project ?

I tried going threw documentation and online media but i was not able to find a answer

**Comment by stof** [comment]
Well, that's something to be asked to the tooling managing the installation of composer for your project. Once you run `composer install`, it runs with the version being installed as `composer` on your system.

**Comment by stof** [comment]
If your goal is to forbid using Composer 2 in your project if someone installed it, a solution might be to add a conflict rule with `plugin-api-version >=2`

**Comment by kbuczynski-nashpl** [comment]
Thanks it was a big help.
