### ISSUE TITLE
Possible to abort on failed dist download?

### ISSUE THREAD

**Issue by okdana** [composer/composer#8791]
Hi there. Hope this isn't a dumb question:

I have Satis set up to mirror select packages from Packagist, and everything works fine, but i find the following behaviour — where Composer works around failed dist downloads — undesirable in this scenario:

```
  - Installing symfony/polyfill-iconv (v1.14.0): Downloading (100%)    Failed to download symfony/polyfill-iconv from dist: The checksum verification of the file failed (downloaded from https://mysatis.example.org/dist/symfony/polyfill-iconv/symfony-polyfill-iconv-926832ce51059bb58211b7b2080a88e0c3b5328e-zip-f50d46.zip)
    Now trying to download from source
  - Installing symfony/polyfill-iconv (v1.14.0): Cloning 926832ce51 from cache
```

Failure to download the dist package indicates to me that i need to fix either my `composer.{json,lock}` or my Satis configuration. The fact that Composer automatically works around it means that my automated builds don't notify me of the problem.

Is there any way i can tell Composer to abort, or at least return >0, when it fails to download a dist package?

I tried `--prefer-dist`, as well as setting `preferred-install` in `composer.json`, but neither made a difference.

---

I think this is just a usage question, but in case you need additional information:

* I'm using Composer 1.10.5

* I don't have any issue with the failed downloads themselves. They seem to occur when (a) another package depends on a version of the package that i haven't explicitly mirrored and/or (b) a check-sum mismatch occurs because my `composer.lock` was generated before i mirrored the package. So it's just something i need to fix on my end, nothing wrong with Composer or Satis there

* Here's a reduced illustration of my `composer.json` set-up:

  ```
  {
    "repositories": [
      { "type": "composer", "url": "https://mysatis.example.org" },
      { "packagist.org": false }
    ],
    "require": { "some/broken-package": "^1.0" }
  }
  ```

**Comment by Seldaek** [comment]
This is not possible to disable, and it's generally a good thing for reliability IMO, but yes in your case I can see how you'd rather get a failed build perhaps..

That said probably not something we're gonna add given the fringe use case.
