### ISSUE TITLE
https://getcomposer.org/composer.phar provide 2.0-dev

### ISSUE THREAD

**Issue by yalh76** [composer/composer#8796]
hello, 

Why https://getcomposer.org/composer.phar provide the 2.0-dev instead of 1.10.5 ?

```
const VERSION = '12be472c6b2d5b36a380253ab01b7d199c4cb453';
const BRANCH_ALIAS_VERSION = '2.0-dev';
const RELEASE_DATE = '2020-04-15 14:57:15';
const SOURCE_VERSION = '';
```

**Comment by stof** [comment]
That's because this URL is for the dev snapshot of Composer, not for the latest stable release. See the various links on https://getcomposer.org/download/

**Comment by yalh76** [comment]
My bad.... I will report the issue to the application that use the dev snapshot instead of the stable release.

Sorry for the noise and thanks for the work :)
