### ISSUE TITLE
Deprecation Notice, PSR-4 and invalid namespace

### ISSUE THREAD

**Issue by michalbundyra** [composer/composer#8801]
Since Composer 1.10 we are getting deprecation notice when file has invalid namespace in the directory which is listed in PSR-4 autoloading rules.

We got it reported here:
https://github.com/php-mock/php-mock/issues/33

The problem is as follows:

- composer.json:
```json
"autoload": {
  "psr-4": {
    "phpmock\\": ["classes/", "tests/"]
  }
}
```

and in we had file: [`tests/MockNamespaceTest.php`](https://github.com/php-mock/php-mock/blob/8ca7205ad5e73fbbffa9bde9f6bc90daf5e49702/tests/MockNamespaceTest.php#L4) with namespace: `phpmock\test`.

Because of that we got notice: 
```
Deprecation Notice: Class phpmock\test\MockNamespaceTest located in ./vendor/php-mock/php-mock/tests/MockNamespaceTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```

(only when running "optimized" autoloader - `composer dump-autoload -o`).

I can totally understand that is an issue, and I totally agree with this approach, but I do not understand why any deprecation notice is not reported for completely invalid namespace?
 
We have there also file [`tests/ExampleTest.php`](https://github.com/php-mock/php-mock/blob/master/tests/ExampleTest.php#L3) with `namespace foo;` and no any issue is reported about that file.

I would expect also some deprecation notice to be reported about that file, as it was about the first one. Also I am not sure about this deprecation notice. I think the file was not autoloaded also using composer v1, so not even sure why in the notice message we have that it will be not working on Composer v2?

Thanks !

**Comment by Seldaek** [comment]
Seems to me like you could fix the warnings by fixing your config, e.g.:

```json
"autoload": {
  "psr-4": {
    "phpmock\\": ["classes/"]
  }
},
"autoload-dev": {
  "psr-4": {
    "phpmock\\test\\": ["tests/"]
  }
}
```

**Comment by Seldaek** [comment]
Ah I see you have a mess in there with different namespaces in the same dir.. In that case you should just use classmap autoloading IMO for the tests/ dir.

**Comment by michalbundyra** [comment]
@Seldaek 

> Seems to me like you could fix the warnings ...

I do know that. The question I was asking is why it is reporting notice for:
`namespace phpmock\test` but it is not reporting anything for `namespace foo`?

Also why it is reporting notice that is not gonna work on Composer v2 as I believe it does not work on v1 either.

**Comment by Seldaek** [comment]
On v1 it works when using optimized autoloader because that switches it to classmap autoloading which autoloads everything.

I am not sure why it skips namespace foo, have to check this on v1 and v2.. Reopening for now.

**Comment by michalbundyra** [comment]
So you want to say that on v1 rule:
```json
"psr-4": {
  "phpmock": "tests/"
}
```

will load correctly file `tests/Whatever.php` with `namespace phpmock\foobar`? 😱

**Comment by Seldaek** [comment]
Only if you do optimized autoloader, yes. That was a mistake because we didn't think people were that messy.. Frequent mistake to make ;) That's why we deprecated and removed in 2.0 because indeed it should not be the case.

**Comment by michalbundyra** [comment]
Ok, I see... and just checked, so on v1 this invalid namespace (`phpmock\test` was loaded, as you said). This is classmap generate when run dump-autoload with `-o`:

```php
 'phpmock\\test\\MockNamespaceTest' => $vendorDir . '/php-mock/php-mock/tests/MockNamespaceTest.php',
```

but there is no any entry for the file with `foo` namespace, so it was not loaded. I guess that's why deprecated is not reported for the other file.

**Comment by Seldaek** [comment]
Ok I think it did filter by the base namespace yes so it needs to match the prefix in the composer.json at least, but did not check the validity according to PSR-4 rules.

I guess we can close this then?

**Comment by michalbundyra** [comment]
Thanks, @Seldaek!
