### ISSUE TITLE
Installing from dist doesn't recognize basic auth credentials in CI environment

### ISSUE THREAD

**Issue by hhoechtl** [composer/composer#8829]
My `composer.json`:

```json
{
    "name": "hhoechtl/test",
    "type": "project",
    "license": "MIT",
    "require": {
        "php": "~7.3",
        "hhoechtl/news": "1.*"
    },
    "config": {
        "optimize-autoloader": true,
        "platform": {
            "php": "7.3"
        }
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://someuser:somepassword@somehost.de/"
        }
    ],
    "minimum-stability": "stable",
    "prefer-stable": true
}
```

In the `composer.lock`:

```
{
            "name": "hhoechtl/news",
            "version": "1.0.2",
            "source": {
                "type": "git",
                "url": "git@somegit.hhoechtl/news.git",
                "reference": "ced36aac1acf2ca6700b4b81454161ffbda7fdea"
            },
            "dist": {
                "type": "tar",
                "url": "https://somehost.de/dist/hhoechtl/news/hhoechtl-news-ced36aac1acf2ca6700b4b81454161ffbda7fdea-zip-2942a3.tar",
                "reference": "ced36aac1acf2ca6700b4b81454161ffbda7fdea",
                "shasum": "defb8f6a7d05af692d3a24767d6432aaf834dc4a"
            },
```

When I run this command:

```
composer install -n
```

**On my local machine** or an isolated docker container (for testing), **it works**. I assume composer can read the basic authentication information from the repository url and use that to authenticate and download the dist archive (which is protected by the same password).

But, if I run this in Gitlab CI with the exactly same docker container and composer version `Composer version 1.10.1 2020-03-13 20:34:27`, I get this:

```
- Installing hhoechtl/news (1.0.2): Downloading (connecting...)    Failed to download hhoechtl/news from dist: The 'https://somehost.de/dist/hhoechtl/news/hhoechtl-news-ced36aac1acf2ca6700b4b81454161ffbda7fdea-zip-2942a3.tar' URL required authentication.
 You must be using the interactive console to authenticate
     Now trying to download from source
```

Of course it can't download from source, because it's a private protected repository, but it should download from dist as it works if I run that exakt same execution in the container.

The only difference is, that on Gitlab CI there's no interactive shell, but why whould it try to authenticate anyway as it has the credentials and that works if you test it manually in a container.

**Comment by hhoechtl** [comment]
Switching to:

```
    "config": {
        "http-basic": {
            "somehost.de": {
                "username": "someuser",
                "password": "somepassword"
            }
        }
    },
```

worked though

**Comment by Seldaek** [comment]
IMO the correct way to provide auth is via auth.json, as per https://getcomposer.org/doc/06-config.md#http-basic - hardcoding credentials in config files is not a proper solution, and while it may work in some circumstances it's not really a use case we want improve.
