### ISSUE TITLE
Force download sources with --prefer-source

### ISSUE THREAD

**Issue by antonioribeiro** [composer/composer#8830]
If I do

```
composer require pragmarx/countries
```

Then

```
composer require pragmarx/countries --prefer-source
```

It will only download the source if, before, I do:

```
rm -rf vendor/pragmarx/countries
```

Not sure if there's a way to force it already, but it would be nice if we didn't have to remove the dir, since it's pretty clear what the user wants are the sources.

And why not run `--prefer-sources` in the first run? Because it will download sources for all dependencies, and usually I don't want that.

**Comment by Seldaek** [comment]
IMO the best option you have right now is then to configure `composer config preferred-install.pragmax/countries source` before doing the require.

We could do a `reinstall` command or something, which would do `rm + install` for you in one go for the given package names, but I find this of very little value given how easy it is to do yourself.

**Comment by antonioribeiro** [comment]
Maybe a way of setting --strict mode and downlod sources only for the packages required by the command?

My concern is that it takes some time to calculate dependencies and finally download all packages, and this process is basically done twice.

**Comment by GromNaN** [comment]
I may have missed something. Why don't you run directly the second command?

**Comment by antonioribeiro** [comment]
Because it will download sources for the package I’m requiring and also for all 25 other package dependencies I don’t need sources to.

**Comment by Seldaek** [comment]
@antonioribeiro then set preferred-install for the package first..

But what you say is anyway not correct, after require the lock file is updated, and then if you rm -rf one package and run `install`, there is no dependency resolution happening so it won't take any time at all. It just reads from lock file at that point.
