### ISSUE TITLE
Composer 2.0-dev

### ISSUE THREAD

**Issue by pgrosvenor** [composer/composer#8831]
I seem to have Composer 2.0 ... but I can't see that it's been released yet?

![composer-2 0](https://user-images.githubusercontent.com/6230463/80193726-a3490f00-8619-11ea-887e-4e5aa840b315.png)

`2.0-dev+df0cada93f1c1f14e2503f1d943824cf27535acb`

I reinstalled an old VM yesterday afternoon and updated everything as normal. Then when I wanted to pull in packages for my legacy project I got a bunch of PSR-4 errors:

> Class does not comply with psr-4 autoloading standard. Skipping.

I understand that this is a breaking (but necessary) change in v2 ... but I didn't expect to just "get" v2 without any warning? According to the downloads page (https://getcomposer.org/download/), the latest version is v1.10.5

**Comment by curzio-della-santa** [comment]
As mentioned in a different issue, we also had problems, because the  https://getcomposer.org/composer.phar currently returns the 2.x dev branch and not the latest stable 1.10.5  as it should.

**Comment by stof** [comment]
And that's not a bug at all, because this URL is for the latest snapshot. If you want the stable release, use https://getcomposer.org/composer-stable.phar, as documented on the download page.

**Comment by stof** [comment]
note that even before the snapshot became 2.0-dev, this snapshot URL was still not giving you an unstable version of composer (since the very early days of composer)

**Comment by curzio-della-santa** [comment]
@stof Thanks, I'll make sure to use the https://getcomposer.org/composer-stable.phar for autoloading optimization in the future.

**Comment by Seldaek** [comment]
Not an issue as @stof explained..
