### ISSUE TITLE
2.0 - composer.lock contains package which should be replaced

### ISSUE THREAD

**Issue by boesing** [composer/composer#8838]
Hey there,

I cannot provide my companies `composer.json`, e.g. (as there are private packages which are not available publicly which might lead to this strange behavior)...
Thats why I am asking for some help so I can create a project to reproduce this behavior.

However, I have a project, where two packages (where one should replace the other) are available in different versions.

zendframework/zend-hydrator in `dev-release-2.4` and laminas/laminas-hydrator in `3.0.2`.

This only happens, if I remove the lock file and the vendor directory before executing `composer install`.

If I run `composer install` with composer 1.0, it works as expected.

I am open for a screenshare to show that this is really happening and after this, we can probably find a way to reproduce that (as you guys know where to set break points for debugging, e.g.).

**Comment by Seldaek** [comment]
If you could try to build a repro case without your private packages that'd be much easier than a screenshare call. I assume/hope all it needs are the involved ZF/laminas packages and an exact sequence of commands to run.

**Comment by stof** [comment]
> This only happens, if I remove the lock file and the vendor directory before executing `composer install`.

Removing the lock files means that your `composer install` is actually running a `composer update`.

**Comment by boesing** [comment]
> If you could try to build a repro case without your private packages that'd be much easier than a screenshare call. I assume/hope all it needs are the involved ZF/laminas packages and an exact sequence of commands to run.

I was trying, but the fact, that there are hundreds of packages involved with dependencies in dependencies which might lead to this is quite hard.

I need some time to create a dependency graph like this on github so it is getting properly checked out. Wondering if it matters if the package is being downloaded or linked from repositories so I can create a single repository with multiple `composer.json` files in sub-directories.

Any suggestion?

**Comment by Seldaek** [comment]
You can do this:

https://github.com/composer/composer/blob/master/tests/Composer/Test/Fixtures/installer/install-dev.test#L5-L13

Add `"type": "metapackage"` to make them installable without the need to provide source or dist. That's the easiest way to list a bunch of packages if it's only about the require inter-dependencies.

**Comment by Seldaek** [comment]
@boesing I suspect this might be related to https://github.com/composer/composer/issues/8902 - can you try again with the latest 2.0 snapshot see if it's fixed?

**Comment by boesing** [comment]
Oh nice, I've spent hours to reproduce it with metapackage but there was more involved than that...

Can confirm that it works with `5e5f9f8142051b39f4dd61cf5ec95ec68408cca9`.

**Comment by Seldaek** [comment]
Great!
