### ISSUE TITLE
[RFC] composer uprade package diff direct link

### ISSUE THREAD

**Issue by noniagriconomie** [composer/composer#8839]
Hello

I would like to know if with composer, there is an option to have something like that when upgrading dependencies

**before**

```
Package operations: 0 installs, 3 updates, 0 removals
 - Updating foo/bar (1.1.1 => 1.2.0)
```

**after**

```diff
Package operations: 0 installs, 1 updates, 0 removals
 - Updating foo/bar (1.1.1 => 1.2.0)
++   - https://github.com/foo/bar/compare/1.1.1...1.2.0
```

Having an output with a link to the source repo with the diff ?
Either by default, or with an --option for example

---

**The idea behind it is to go check/review the code diff faster**

**And if not, do you think it is doable? I could give it a try it :)**

Many thanks :)

**Comment by MacFJA** [comment]
Hi,

There is a Composer plugin that can do it: [pyrech/composer-changelogs](https://packagist.org/packages/pyrech/composer-changelogs)

**Comment by Seldaek** [comment]
Closing as the plugin is IMO good enough for this, and it's not something we want to spend time on atm.
