### ISSUE TITLE
Runtime platform check does not honor --ignore-platform-reqs

### ISSUE THREAD

**Issue by kelunik** [composer/composer#8861]
My `composer.json`:

```json
{
    "name": "amphp/byte-stream",
    "homepage": "http://amphp.org/byte-stream",
    "description": "A stream abstraction to make working with non-blocking I/O simple.",
    "support": {
        "issues": "https://github.com/amphp/byte-stream/issues",
        "irc": "irc://irc.freenode.org/amphp"
    },
    "keywords": [
        "stream",
        "async",
        "non-blocking",
        "amp",
        "amphp",
        "io"
    ],
    "license": "MIT",
    "authors": [
        {
            "name": "Aaron Piotrowski",
            "email": "aaron@trowski.com"
        },
        {
            "name": "Niklas Keller",
            "email": "me@kelunik.com"
        }
    ],
    "require": {
        "amphp/amp": "^2"
    },
    "require-dev": {
        "amphp/phpunit-util": "^1",
        "phpunit/phpunit": "^6 || ^7 || ^8",
        "friendsofphp/php-cs-fixer": "^2.3",
        "amphp/php-cs-fixer-config": "dev-master",
        "psalm/phar": "^3.11@dev",
        "jetbrains/phpstorm-stubs": "^2019.3"
    },
    "autoload": {
        "psr-4": {
            "Amp\\ByteStream\\": "lib"
        },
        "files": [
            "lib/functions.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Amp\\ByteStream\\Test\\": "test"
        }
    },
    "extra": {
        "branch-alias": {
            "dev-master": "1.x-dev"
        }
    }
}
```

Output of `composer diagnose`:

```
Deprecation Notice: Required parameter $path follows optional parameter $schema in phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/UndefinedConstraint.php:62
Deprecation Notice: Required parameter $path follows optional parameter $schema in phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/UndefinedConstraint.php:108
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0-dev+1d077ede704216206b41b477f6113926a7ea2b9e
PHP version: 8.0.0-dev
PHP binary path: /home/kelunik/.phpenv/versions/attributes/bin/php
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

When I run this command:

```
./vendor/bin/psalm.phar
```

I get the following output:

```   
Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 7.2.5" and "< 8.0.0". You are running 8.0.0-dev.
```

And I expected this to happen:

I'm able to run the script, because I have specified `--ignore-platform-reqs` during installation.

Additionally, I expect some way to ignore that check to be documented in the error message.

**Comment by Seldaek** [comment]
I think now that https://github.com/composer/composer/blob/master/doc/07-runtime.md#platform-check has been written, we could add a short-link to it in the error message, like https://getcomposer.org/platform-check

Aside from that, the whole point of the feature is to make sure things are running the expected runtime, no matter what php version was used to run composer, nor what flags/platform config were used to override things at install time. So IMO it behaves as expected here, although I do see that it is annoying for php 8 or generally speaking unreleased PHP versions. I'm not sure if we should warrant an exception there or not. /cc @naderman @nicolas-grekas

**Comment by kelunik** [comment]
It's good to know there's an option to disable the check, but I guess it makes sense to allow temporarily suppress the runtime check, e.g. with an environment variable like `COMPOSER_CHECK_PLATFORM=0`, maybe also with a separate one for the PHP version like `COMPOSER_CHECK_PHP_VERSION=0` to opt-out only for the PHP version check, but keep all other platform checks in place.

**Comment by nicolas-grekas** [comment]
On my side, I think the core of the issue is the `< 8.0.0` constraint. I would call this rule "planned obsolescence". It doesn't provide any safety - but it blocks testing/running with the newest versions of PHP. I'm not sure Composer should provide anything more to help with this way of restricting contraints.

**Comment by nicolas-grekas** [comment]
I'm withdrawing my previous comment, not really helpful sorry :)

I'm not sure I understand the issue. Does `--ignore-platform-reqs` remove the runtime check? We discussed this recently but I missed the PR.

Adding runtime checks would mean slowing down the hot path. The max we can do it check against `$_SERVER['COMPOSER_CHECK_PLATFORM']`, not `getenv()` of course. But I'm missing some pieces to tell if this is a good idea in the first place. Please tell me how I can help.

**Comment by kelunik** [comment]
No, `--ignore-platform-reqs` does not remove the check.

I guess it's fine to check the additional environment variables only for the CLI, PHPDBG and embed SAPIs, where this isn't an as hot code path.

**Comment by Seldaek** [comment]
--ignore-platform-reqs now removes the runtime check, and there is also a way to narrow down what gets excluded like `--ignore-platform-reqs=php` will only ignore php requirements

**Comment by kelunik** [comment]
Thanks!
