### ISSUE TITLE
Composer 2 pre-stable tagged release

### ISSUE THREAD

**Issue by greg-1-anderson** [composer/composer#8872]
Drupal is currently running a subset of all Core tests against the snapshot build of Composer 2. This will help detect any problems with any submitted patches that might break compatibility with the Composer 2 API. (Yep, the current HEAD of Drupal 9.0.x / 9.1.x are now working with Composer 2. Yay.)

This is great, except that testing against the dev snapshot makes the Drupal tests fragile, in that any bad commit to Composer master will break Drupal tests. We would therefore prefer to test with a specific Composer 2 build, so that our tests do not have two variables (Composer 2 version and the patch under test). We tried this at [#3133423](https://www.drupal.org/project/drupal/issues/3133423), but the Composer self-update command does not work with arbitrary sha's.

Would it be convenient to create a pre-stable tag (e.g. 2.0.0-alpha1, or whatever), to make Composer 2 testing easier? If not, we could always run our test by cloning from GitHub, but having a tag would also make it clearer which version of Composer 2 was being used in the test.

**Comment by Seldaek** [comment]
2.0.0-alpha1 is out now, it is an alpha so things may still change, but we'll try to stay BC from now on unless needed.
