### ISSUE TITLE
Composer doen't download anything by a Cisco Proxy - SSL: Success Failed to enable crypto

### ISSUE THREAD

**Issue by Ahivala** [composer/composer#8876]
Hi everyone,

  I'm new with composer and I'm finding almost all of my troubles because of a Cisco proxy.

  I've already rules in the proxy to allow my Ubuntu server to download everything (I can download from everywhere with "wget" command) but composer has an "SSL: Success   Failed to enable crypto"

  Further below you'll find more information according the information you required.

  Thanks and I hope someone could help me.

Regards.

**My `composer.json`:**

()

**Output of `composer diagnose`:**

Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: [Composer\Downloader\TransportException] The "https://repo.packagist.org/packages.json" file could not be downloaded: SSL: Success
Failed to enable crypto
failed to open stream: operation failed
Checking HTTP proxy: FAIL
[Composer\Downloader\TransportException] The "https://repo.packagist.org/packages.json" file could not be downloaded: SSL: Success
Failed to enable crypto
failed to open stream: operation failed
Checking HTTP proxy support for request_fulluri: OK
Checking HTTPS proxy support for request_fulluri: Unable to assess the situation, maybe github is down (The "https://api.github.com/repos/Seldaek/jsonlint/zipball/1.0.0" file could not be downloaded: SSL: Success
Failed to enable crypto
failed to open stream: operation failed)
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: SSL: Success
Failed to enable crypto
failed to open stream: operation failed
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version:

  [Composer\Downloader\TransportException]
  The "https://getcomposer.org/versions" file could not be downloaded: SSL: Success
  Failed to enable crypto
  failed to open stream: operation failed

diagnose

**When I run this command:**

 php composer.phar install

**I get the following output:**
Loading composer repositories with package information

  [Composer\Downloader\TransportException]
  The "https://repo.packagist.org/packages.json" file could not be downloaded: SSL: Success
  Failed to enable crypto
  failed to open stream: operation failed

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

**And I expected this to happen:**

I expected to download something from internet. I am using a Cisco Proxy.

**Comment by stof** [comment]
see https://getcomposer.org/doc/03-cli.md#http-proxy-or-http-proxy

You might want to set the env variable `HTTPS_PROXY_REQUEST_FULLURI=false`

**Comment by Ahivala** [comment]
Thanks "stof", I've tried but I have the same results. Below I put you my env config for those related with HTTP and the 'php composer.phar diagnose':


**user@myserver:~$ env | grep HTTP**
HTTP_PROXY=http://myproxy01:8080
HTTP_PROXY_REQUEST_FULLURI=0
HTTPS_PROXY=https://myproxy01:8080
HTTPS_PROXY_REQUEST_FULLURI=0

**user@myserver:~$ php composer.phar diagnose**
Checking composer.json: _WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license._
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: _[Composer\Downloader\TransportException] The "https://repo.packagist.org/packages.json" file could not be downloaded: SSL: Success
Failed to enable crypto
failed to open stream: operation failed_
Checking HTTP proxy: FAIL
[Composer\Downloader\TransportException] The "https://repo.packagist.org/packages.json" file could not be downloaded: SSL: Success
Failed to enable crypto
failed to open stream: operation failed
Checking HTTP proxy support for request_fulluri: OK
Checking HTTPS proxy support for request_fulluri: Unable to assess the situation, maybe github is down (The "https://api.github.com/repos/Seldaek/jsonlint/zipball/1.0.0" file could not be downloaded: SSL: Success
Failed to enable crypto
failed to open stream: operation failed)
Checking github.com rate limit: _FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: SSL: Success
Failed to enable crypto
failed to open stream: operation failed_
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version:

  _[Composer\Downloader\TransportException]
  The "https://getcomposer.org/versions" file could not be downloaded: SSL: Success
  Failed to enable crypto
  failed to open stream: operation failed_


diagnose

**Comment by Ahivala** [comment]
Finally that worked by my proxy configuring env variable **HTTPS_PROXY=http://myproxy01:8080**

Thanks for your help @stof , your indications also helped to guide me to the correct  answer.
