### ISSUE TITLE
[Symfony\Component\Console\Exception\RuntimeException] The "--v" option does not exist.

### ISSUE THREAD

**Issue by burakalac4** [composer/composer#8877]
Hello 
I have encountered such an error, can you help?
Error Code
`
  [Symfony\Component\Console\Exception\RuntimeException]
  The "--v" option does not exist.
`
Screenshoot 
https://prnt.sc/sbzi2y

Thanks you, i am wait.

**Comment by xabbuh** [comment]
You need to use just one dash (i.e. `-v` instead of `--v`).

**Comment by stof** [comment]
it is either `-v` or `--verbose`

**Comment by darkwe** [comment]
> it is either `-v` or `--verbose`
> You need to use just one dash (i.e. `-v` instead of `--v`).

I am getting such an error, how can I solve it?

https://prnt.sc/sc3dlz

**Comment by xabbuh** [comment]
As the error message says, the Composer command is `require` not `reqiure` (notice the order of `i` and `u`).
