### ISSUE TITLE
Windows manual installation instructions do not produce composer.bat

### ISSUE THREAD

**Issue by PixievoltNo1** [composer/composer#8883]
I'm trying to install Composer on Windows manually, as Composer-Setup.exe didn't work (I'll file a separate issue for that shortly). The instructions at https://getcomposer.org/download/ worked and gave me composer.phar, but the instructions at https://getcomposer.org/doc/00-intro.md#manual-installation produce no new file. I'm using PowerShell on Windows 10.

My `composer.json`: N/A

Output of `composer diagnose`: N/A

When I run this command:

```
echo @php "%~dp0composer.phar" %*>composer.bat
```

I get the following output:

```
%~dp0composer.phar
%*>composer.bat
```

And I expected this to happen:

I'd get a composer.bat file.

**Comment by Seldaek** [comment]
You can create the composer.bat yourself with `@php "%~dp0composer.phar" %*` as contents. That's all the echo line is doing.. 

That said I am not sure why it's not working for you, so leaving this open until someone can investigate more and possibly update the docs.

**Comment by johnstevenson** [comment]
@PixievoltNo1 Those instructions only work for cmd.exe. For Powershell it is:

```
Set-Content composer.bat '@php "%~dp0composer.phar" %*'
```
