### ISSUE TITLE
Different package sources for dev and live ?

### ISSUE THREAD

**Issue by UtechtDustin** [composer/composer#8887]
I have a package which is used in some modules of my project.
If want to update this package and if i use
``` 
"dependencies": {
    "packagename": "dev-master"
  }
```
I always have to commit, push the package and pull on the module.
Which takes a lot of time.

My idea was to have 2 repositorie sources, one for dev and one for prod.
On Dev i want do use a local repository with the symlink option,  like this:
```
"repositories": [
    {
        "type": "path",
        "url": "../path-to-package",
        "options": {
            "symlink": true
        }
    }
]
```
While the production deployment i want that the package will be fetched from the git repository instead of a local path.

Is this possible ?

**Comment by apfelbox** [comment]
You can use the composer plugin [`studio`](https://github.com/franzliedke/studio) for that, it sounds like that's exactly what you are looking for.

Install the plugin locally, add the `studio.json` locally (gitignore it) and then you should have exactly this setup.

**Comment by UtechtDustin** [comment]
@apfelbox Thank you, i will check that plugin :)
