### ISSUE TITLE
Print abanonded warning for old PHP versions

### ISSUE THREAD

**Issue by GrahamCampbell** [composer/composer#8891]
Just like composer warns of abandoned packages, maybe it should warn about abandoned "php" versions too. This would encourage upgrading. ;)

**Comment by staabm** [comment]
We do similar checks in a open source cms.. maybe this can used for inspiration 

https://github.com/redaxo/redaxo/blob/ade2e34f995983fd50ba6ed0a314ef3b0e86824b/redaxo/src/core/lib/setup/setup.php#L179-L187

**Comment by GrahamCampbell** [comment]
Well, given that composer warns about packages that aren't maintained any more, it already plays the upgrade police, as you say. I think warning about PHP versions is totally reasonable, given that we already warn about dead packages. Maybe even if composer delays until 12 months after until security support ends before printing warnings, that would be a good middle ground?

Also, I was wondering if packagist could automatically mark packages as abandoned if they have no updates after 2 years. Perhaps with a way for the author to extend the countdown to say, that their package is maintained, but just didn't need updating. There are a lot of packages out there that are abandoned, but haven't been marked as such. Similarly, packages could be auto-abandoned if they are linked to a repo marked as read-only on github.

**Comment by Seldaek** [comment]
We already mark packages abandoned when they get archived on github. Abandoning automatically otherwise might be worth doing later, but right now I'm focusing on Composer 2.0.

Same with warning about PHP versions.. I am still not so convinced it's worth the trouble. I doubt most people still using old versions do it because they accidentally didn't realize there were a gazillion new PHP releases. That's not the same as warning for abandoned packages, for which unless you go check on packagist you otherwise wouldn't know.

**Comment by staabm** [comment]
> Well, given that composer warns about packages that aren't maintained any more, it already plays the upgrade police, as you say.

I dont agree. The person in charge of updating php is not necessary the same as the one using composer.

I agree with Jordi that composer is not the right tool to promote the php upgrade policy

**Comment by GrahamCampbell** [comment]
> The person in charge of updating php is not necessary the same as the one using composer.

That certainly used to be the case, but these days, increasingly this is not the case, with infrastructure as code, and docker, and the likes.

**Comment by Seldaek** [comment]
I think we'll have to agree to disagree here..
