### ISSUE TITLE
file_exists() is up to 100x slower then is_dir() or is_file()

### ISSUE THREAD

**Issue by staabm** [composer/composer#8892]
Inspired by https://bugs.php.net/bug.php?id=78285

benchmark:
```php
<?php
$t0 = hrtime(true);
for ($i = 0; $i < 1000; $i++) {
    is_file(__FILE__);
}
$t1 = hrtime(true);
for ($i = 0; $i < 1000; $i++) {
    file_exists(__FILE__);
}
$t2 = hrtime(true);
printf("is_file      took %f ms\n", ($t1 - $t0)/10e6);
printf("file_exists took %f ms\n", ($t2 - $t1)/10e6);
```

measured on my laptop
```sh
$ php perf.php
is_file      took 0.058450 ms
file_exists took 5.852210 ms

$ php perf.php
is_file      took 0.047010 ms
file_exists took 6.005810 ms

$ php -v
PHP 7.3.0 (cli) (built: Dec  6 2018 02:17:00) ( ZTS MSVC15 (Visual C++ 2017) x86
 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with blackfire v1.24.1~win-x32-zts73, https://blackfire.io, by Blackfire
```

Did a quick search thru the codebase and found looots of file_exists() calls. We should investigate which are on perf critical path and fix them

Similar to https://github.com/symfony/symfony/issues/36493

**Comment by Ayesh** [comment]
[tests](https://github.com/Ayesh/composer/runs/671851292?check_suite_focus=true) appear to pass with `file_exists()` replaced with `is_file()`, but to due to symlink resolution in `file_exists()`, this would be a breaking change on the extreme case the files are symlinked, which is often the case for `path` repositories. I don't think we have test coverage for the `ClassLoader`, which is probably why the tests passed.

**Comment by Seldaek** [comment]
Adding clearstatcache to each for loop makes it take the same time.. so are you sure there is a difference if you are not calling to check if the same file exist a million times? If it's just a win thanks to the stat cache then there will be no win in real use cases where different paths are checked..

If you can update the benchmark to create 1000 files, clearstatcache, then check is_file/file_exists on the 1000 files, maybe it gives us a more relevant insight?

**Comment by Seldaek** [comment]
In other words, unless you have very convincing evidence, and a PR which doesn't look like it's gonna break stuff, I am inclined to just ignore this as not worth the trouble. Happy to be proven wrong though if it can make a relevant performance impact, ideally backed by a real world benchmark.

**Comment by staabm** [comment]
I was not yet able to create a workload where `file_exists()` is detect as one of the top X bottlenecks

**Comment by markbernard** [comment]
No appreciable difference on 10000 files.

Run on 12 year old hardware running ubuntu 18.
is_file      took 0.001291 ms
file_exists took 0.001180 ms

`<?php
class Test {
  public function run() {
    $names = array();
    $handles = array();
    for ($i=0;$i<10000;$i++) {
      array_push($names, tempnam(sys_get_temp_dir(), "AAA"));
      array_push($handles, fopen($names[$i], "rw"));
      fwrite($handles[$i], "writing to tempfile\n");
    }

    $t0 = microtime(true);
    for ($i = 0; $i < 10000; $i++) {   
        is_file($names[$i]);
    }
    $t1 = microtime(true);
    for ($i = 0; $i < 10000; $i++) {
        file_exists($names[$i]);
    }
    $t2 = microtime(true);
    printf("is_file      took %f ms\n", ($t1 - $t0));
    printf("file_exists took %f ms\n", ($t2 - $t1));

    for ($i=0;$i<10000;$i++) {
      fclose($handles[$i]);
      unlink($names[$i]);
    }
  }
}

$t = new Test();
$t->run();
?>`

**Comment by Seldaek** [comment]
Ok closing this then, feel free to reopen/comment if there's a proven benefit.
