### ISSUE TITLE
failed to create symbolic link 'public/storage/public': File exists

### ISSUE THREAD

**Issue by saidhappy010** [composer/composer#8894]
I am installing composer composer install using .gitlab-ci.yml.
installation was successfully done with this message:
`Package manifest generated successfully.`
but I got these errors:

> Package manifest generated successfully.
Method Composer\Config::disableProcessTimeout is not callable, can not call post-install-cmd script
ln -sr storage/app/public public/storage
ln: failed to create symbolic link 'public/storage/public': File exists
Script ln -sr storage/app/public public/storage handling the post-install-cmd event returned with error code 1
Running after_script
Uploading artifacts for failed job
ERROR: Job failed: exit status 1

please how can I fix it

**Comment by stof** [comment]
This is an error coming from a custom scriptyou have (running `ln -sr storage/app/public public/storage`). So the issue is in your project (which defines this script), not in Composer

**Comment by saidhappy010** [comment]
thank you for your reply
  yes this script exists in the composer.json file
         "post-install-cmd": [
             "ln -sr storage / app / public public / storage",
],
what should i do please.
thank you

**Comment by stof** [comment]
Well, then solve the fact that your script fails. That is that script failing, not composer itself. Composer won't be able to solve this for your.
