### ISSUE TITLE
Composer v2 faster for some but not for other projects

### ISSUE THREAD

**Issue by leofeyer** [composer/composer#8895]
I have noticed that Composer v2 is faster for some but not for other projects compared to Composer v1. Here is what I did:

```
composer create-project --profile contao/contao
composer create-project --profile contao/manager-plugin
```

And here are the results:

| Package | v1 memory | v1 time | v2 memory | v2 time |
| --- | --- | --- | --- | --- |
| contao | 413.48MiB (781.75MiB) | 27.05s | 23.87MiB (109.05MiB) | 19.26s |
| manager-plugin | 436.55MiB (1401.03MiB) | 32.33s | 52.28MiB (874.13MiB) | 33.93s |

While installing contao/contao was significantly faster, installing contao/manager-plugin has not improved at all regarding time. (Memory usage improvements are amazing in both cases.)

I have repeated the tests with Composer v2 vs. Composer v1 + Symfony Flex:

| Package | v1 memory | v1 time | v2 memory | v2 time |
| --- | --- | --- | --- | --- |
| contao | 278.01MiB (880.77MiB) | 19.22s | 26.1MiB (109.62MiB) | 18.62s |
| manager-plugin | 312.47MiB (715.92MiB) | 19.11s | 52.79MiB (874.69MiB) | 32.64s |

The improvements of the Symfony Flex plugin seem to affect both packages. Maybe #8295 or #8850 can bring these improvements to Composer v2 as well? @ausi @Toflar /cc

I have no idea if this is helpful in any way, but I wanted to share it in case it is. 🙈

**Comment by stof** [comment]
`contao/contao` has lots of root requirements (all other contao packages) while `contao/manager-plugin` has only a few. So I suspect that #8295 might indeed help here.

Also, have you run this with an empty cache each time or with a warm cache ?

**Comment by leofeyer** [comment]
All packages were in the cache. Nothing needed to be downloaded.

**Comment by stof** [comment]
OK, then the only impact of Flex will be the filtering of Symfony packages. This means that the difference between your 2 cases is indeed something that #8295 will solve.

**Comment by Seldaek** [comment]
Thanks for sharing, closing tho as it is indeed tracked already by https://github.com/composer/composer/pull/8850
