### ISSUE TITLE
Autoloader should not be generated if no packages installed

### ISSUE THREAD

**Issue by leewillis77** [composer/composer#8897]
My `composer.json`:

```json
{
    "require-dev": {
        "squizlabs/php_codesniffer": "^3.5",
    }
}
```

Output of `composer diagnose`:

```
Composer version: 1.10.6
PHP version: 7.3.17
```

When I run this command:

```
composer install --no-dev
```

Composer still generates autoload files under vendor. E.g.

```
$ ls -1 vendor
autoload.php
bin/
composer/
```

Since composer is not installing any packages, I don't want that autoload code generated (and would like it removed if it exists from a previous run).

_Note_: I'm aware of the `--no-autoloader` flag to composer, however that doesn't work for me in this situation since I use a standardised build script across many projects, and the build script can't assume whether autoloading is or isn't required - only composer has that knowledge when it is running.

For many of the projects it will be (so composer should install dependencies and generate an autoloader), but for others composer is only used for dev dependencies which aren't required when building for a release and composer should not need to generate autoload code.

**Comment by Ayesh** [comment]
You can dump the autoloader without `require-dev` entries with `composer dump-autoload --no-dev`. This will still create the `vendor/autoload.php` file, but it will not add any require-dev classes there. The require-dev files are not removed. 

I personally don't think it will be wise to prevent composer from building `vendor/autoload.php` file. By now, it's pretty much muscle memory to require this file in a framework entrypoint, and the sudden lack of this file can raise more issues than the few kilobytes an empty autoloader takes.

**Comment by Seldaek** [comment]
99.99% of projects using composer will end up having a need for the autoloader, so I don't really see a need to special case this. If you don't need the autoloader in prod then don't require the autoloader and that's it. It ends up wasting a couple files on disk, not a huge deal.
