### ISSUE TITLE
Path repository is not working

### ISSUE THREAD

**Issue by themsaid** [composer/composer#8899]
My `composer.json`:

```json
{
    "repositories": [
        {
            "type": "path",
            "url": "../src/laravel"
        }
    ],
    "require": {
        "laravel/framework": "*"
    }
}
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.6
PHP version: 7.4.2
PHP binary path: /usr/local/Cellar/php/7.4.2/bin/php
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

When I run this command:

```
composer update
```

I get the following output:

```
Installing laravel/framework (v7.11.0): Downloading (100%)  
```

And I expected this to happen:

I expect /vendor/laravel/framework to be a symlink to the local path specified in composer.json

**Comment by taylorotwell** [comment]
I was able to recreate path repositories not working on my machine as well.

**Comment by leewillis77** [comment]
Assuming that ../src/laravel is a local copy of laravel/framework, and assuming that you haven't checked out a specific tag then this is expected behaviour. 

> If the package is a local VCS repository, the version may be inferred by the branch or tag that is currently checked out. Otherwise, the version should be explicitly defined in the package's composer.json file. If the version cannot be resolved by these means, it is assumed to be dev-master.

[From https://getcomposer.org/doc/05-repositories.md#path]

Adding a "version" declaration to `../src/laravel/composer.json` will resolve this, or tell composer to require the version that you have on your filesystem.

**Comment by leewillis77** [comment]
If you have the 7.x branch checked out then you want this (works for me here)
```
{
    "repositories": [
        {
            "type": "path",
            "url": "../src/laravel"
        }
    ],
    "require": {
        "laravel/framework": "7.x.x-dev"
    }
}
```

That produces the desired outcome I think:
`  - Installing laravel/framework (7.x-dev): Symlinking from ../src/laravel`

**Comment by themsaid** [comment]
@leewillis77 Seems like `7.x-dev` and `dev-master` works!

Something must have changed recently because we used to symlink and require `*@dev`.

I'm going to close the issue since it's the expected behaviour.

Thanks :)
