### ISSUE TITLE
Provide a direct import function to avoid composer.json configurations

### ISSUE THREAD

**Issue by otobio** [composer/composer#8905]
# Goal
Simplify the process of library consumption

# Example
Can we import libraries like we do on the web

<script src="https://...."></script>
import_from_composer("https://..")

Basically, with the goal of avoiding a zillion command to use a library.

- composer require package
- require(../autoload.php)
- use ns/ns/class;

all simplifies as

- import_from_composer(package)

# Why
Why not. It is simpler, it is what PHP itself does.

# Other motivations
We do this on the web, the deno project might do this too. Dynamic language features should just be easier. Let composer be first

**Comment by stof** [comment]
Contrary to modern JS wheremodules are relying on local names with explicit imports and exports, PHP does not have such a concept. All functions and classes are in the same global scope. So resolving dependencies to a single version of each package is a necessary step. Also, dependencies between JS modules are resolved statically (which is the requirement for something like Deno to be viable, as it does not need to wait until runtime to know what gets imported).
What you are asking cannot be done by composer (btw, the equivalent of composer in JS is npm, and that is precisely the tool that the Deno project dropped). What you are asking for is a different language than PHP (one with a module system).

This issue should be closed.

**Comment by otobio** [comment]
@stof What I am asking for is a way to use composer packages without the need for composer.json or composer cli. Still, i get your point that composer was designed to be a PHP version of npm. I will close this.
