### ISSUE TITLE
composer is not compatible with latest macOS

### ISSUE THREAD

**Issue by Janardanank** [composer/composer#8911]
Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries. 
Trying to force-link OpenSSL returns- "Linking keg-only OpenSSL means you may end up linking against the insecure, deprecated system version while using the headers from the Homebrew version. 
Will composer be upgraded to work with LibreSSL? 
Is there any workaround?

**Comment by Seldaek** [comment]
I don't know exactly what the support looks like. As far as I can see from a quick googling session it seems php should build fine with libressl in place of openssl. It doesn't seem to make any difference for userland PHP code which is loaded.. So I am not sure what you mean by incompatible. What is breaking and how etc?

**Comment by Janardanank** [comment]
On MacOs Catalina version 10.15.4, I get this
composer 1.10.6 is already installed, it's just not linked
You can use `brew link composer` to link this version.
...... ~% brew link composer
Linking /usr/local/Cellar/composer/1.10.6... 1 symlinks created
...... ~ % composer --version
dyld: Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
zsh: abort      composer --version

**Comment by Seldaek** [comment]
Please report this to the brew composer package wherever that is, we do not support brew installs here as we can't fix it.

**Comment by Janardanank** [comment]
Direct install also do not work:
~ % php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

dyld: Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
zsh: abort      php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
dyld: Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
zsh: abort      php -r 
dyld: Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
zsh: abort      php composer-setup.php
dyld: Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
zsh: abort      php -r "unlink('composer-setup.php');"

**Comment by Seldaek** [comment]
Well yes as that is still using your PHP from homebrew with the broken openssl.

**Comment by Janardanank** [comment]
/usr/local/bin/php was invoking /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
instead of /usr/local/opt/openssl/lib/libcrypto.1.1.dylib

 Solved by changing path to php. 
Thanks.
Consider closed
