### ISSUE TITLE
Install only required files

### ISSUE THREAD

**Issue by steevanb** [composer/composer#8915]
Hi,

When i add a dependency (in this example : https://github.com/phpstan/phpstan-deprecation-rules), Composer will download and install all files from this repository:
 * src
 * rules.neon
 * tests
 * .editorconfig
 * etc

But i just need `src` and `rules.neon`, all other files / directories are not needed but installed.

Maybe we can add an option / configuration to install only required files?
Example of how we can achieve that, in `phpstan/phpstan-deprecation-rules` `composer.json` :
```json
{
    "sources": [
        "src/",
        "rules.neon"
    ]
}
```

It can be an awesome feature to reduce `vendor` directory size, because a lot of files are not required.

**Comment by Seldaek** [comment]
.gitattributes can be used by package authors to create zips without tests and whatever is not needed https://medium.com/@pavlakis/sharing-with-composer-and-gitattributes-4423f5c4967f - on the consuming side maintaining lists of stuff to delete is IMO a gigantic waste of time, but if you really care there is https://github.com/barryvdh/composer-cleanup-plugin doing this I believe.

**Comment by steevanb** [comment]
Why do you thinks it's a waste of time?

To me it's easy to do, and it's really usefull to reduce vendor directory size.
