### ISSUE TITLE
Composer issue with XQuartz?

### ISSUE THREAD

**Issue by begrafx** [composer/composer#8919]
Is composer known to have any issues with the Xquartz environment? I'd had Composer installed and it was working fine; The only change I can think of to my environment was installing Inkscape, which required the Xquartz environment. Now when I attempt to use Composer at all, I get: 

`$ composer

                                                                               
  [RuntimeException]                                                           
  Could not read /Users/brianeller-mini/.composer/config.json                  
                                                                               
  file_get_contents(/Users/brianeller-mini/.composer/config.json): failed to   
  open stream: Permission denied                                               
                                                                               

`

I have even attempted to reinstall Composer using the instructions at https://getcomposer.org/download/ but no change. 

OS: MacOS Mojave

Results: 

`$ which composer
/usr/local/bin/composer
Brians-Mac-mini:bin brianeller-mini$ type composer
composer is hashed (/usr/local/bin/composer)
Brians-Mac-mini:bin brianeller-mini$ env
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/4v/l6w1x1t94p9gx0pjw417mp8w0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.DGWEzHfyHJ/Render
TERM_PROGRAM_VERSION=421.2
TERM_SESSION_ID=CA2A5E99-E37A-4A7F-9335-227E18662315
USER=brianeller-mini
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.WkZbpOLKdz/Listeners
PATH=/opt/local/bin:/opt/local/sbin:/Users/brianeller-mini/.composer/vendor/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
PWD=/usr/local/bin
LANG=en_US.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/brianeller-mini
LOGNAME=brianeller-mini
DISPLAY=/private/tmp/com.apple.launchd.MATWVIFTzx/org.macosforge.xquartz:0
_=/usr/bin/env
OLDPWD=/Users/brianeller-mini`

Any suggestions are appreciated.

**Comment by stof** [comment]
Well, check the permissions on the `.composer` folder. Maybe something changed the permissions.

**Comment by begrafx** [comment]
I have. The folder was set with "System" having Read/Write access, Staff and Everyone having Read only. I went in and added myself specifically, granting Read/Write permissions, and still get the same result.

**Comment by begrafx** [comment]
The only thing I can think of that has been done that could have changed anything, caused an issue like this, is installing XQuartz. I am thinking I will uninstall XQuartz, uninstall Inkscape, and completely uninstall and reinstall Composer. Presumably, that should put everything back, set as it should be. Yes? But on that note, what is the best way to completely uninstall Composer? I know I can just go in and delete the .composer folder and composer.phar, but will that be enough? Will that allow a reinstall to set everything correctly?

**Comment by Naheem** [comment]
Offtopic but I dont think the latest inkscape requires xquartz?

**Comment by Seldaek** [comment]
There is no Composer installation nor uninstall really. It's just a single self-contained phar file. You could wipe `~/.composer` to clean local state up, but that's about it.

Sorry but I am not aware of anything related to xquartz. Then again I am also not familiar with it at all so not sure how it could impact Composer. Seems to be that things fail at a fairly low level though, if a file_get_contents fail that's not really something which Composer can fix.
