### ISSUE TITLE
Method ReflectionParameter::getClass() is deprecated

### ISSUE THREAD

**Issue by matbech** [composer/composer#8924]
With the latest version of PHP 8.0, getClass has been deprecated:
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in phar://C:/composer.phar/src/Composer/Repository/RepositoryManager.php:130

ReflectionParameter::getType() and ReflectionType::getName() should be used instead.

See PHP commit:
https://github.com/php/php-src/commit/28af364d2ae2261addc21f8830f175baa8fa72cf

**Comment by matbech** [comment]
Closed because it does not apply to the version 2.x of composer

**Comment by Saboor-Hamedi** [comment]
I just download php 8, I got this error, what exactly is this ?
ErrorException: Method ReflectionParameter::getClass() is deprecated in C:\Users\Saboor\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\phpdocumentor\reflection-docblock\src\DocBlock\StandardTagFactory.php:241 Stack trace: #0 C:\Users\Saboor\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\phpdocumentor\reflection-docblock\src\DocBlock\StandardTagFactory.php(241): {closure}(8192, 'Method Reflecti...', 'C:\\Users\\Saboor...', 241) #1 C:\Users\Saboor\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\phpdocumentor\reflection-docblock\src\DocBlock\StandardTagFactory.php(198): phpDocumentor\Reflection\DocBlock\StandardTagFactory->getArgumentsForParametersFromWiring(Array, Array) #2 C:\Users\Saboor\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\phpdocumentor\reflection-docblock\src\DocBlock\StandardTagFactory.php(122): phpDocumentor\Reflection\DocBlock\StandardTagFactory->createTag('ClientCapabilit...', 'param', Object(phpDocumentor\R...

**Comment by mfn** [comment]
@Saboor-Hamedi one of your dependencies is an outdated version of phpDocumentor/ReflectionDocBlock not supporting PHP8, [it's fixed since 5.2.0](https://github.com/phpDocumentor/ReflectionDocBlock/commit/65a85616f432c3511991b787b7e5ec10ae2eb79c#diff-0a54b372c4e4b90d958830938d282b2fe77063cbf4a3f259b2ecf19b14f862f5) and you seem to have an older version

**Comment by alxndr-w** [comment]
And how to solve it if it stops you from updating?
![image](https://user-images.githubusercontent.com/3855487/119314977-9f9d1700-bc75-11eb-851f-12a93e24ca2c.png)
