### ISSUE TITLE
Not POSIX compliant: short option -d expects parameter without whitespace

### ISSUE THREAD

**Issue by c0deright** [composer/composer#8927]
composer 1.10.6 (2020-05-06 10:28:10) usage says:

`-d, --working-dir=WORKING-DIR  If specified, use the given directory as working directory.`

I would expect the following invocations to yield the same results:

```
composer -d /foo/bar/myproject install
composer --working-dir=/foo/bar/myproject install
```

but only the long option is working.

However, the short option *is* working when omitting the space between option and value:

`composer -d/foo/bar/myproject install`

That's a really odd design decision and stands against POSIX recommendations:

From [25.1.1 Program Argument Syntax Conventions](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html):

> An option and its argument may or may not appear as separate tokens. (In other words, the whitespace separating them is optional.) Thus, `-o foo` and `-ofoo` are equivalent.

Please allow whitespaces between options and tokens.

**Comment by stof** [comment]
IIRC, things work as expected if you put the name of the composer command (`install` in that case) before the options. The issue being that symfony/console needs to know which command is being run before being able to parse the options (to know whether `-d` expects a value or is a simple flag), as each command can have different options.

**Comment by c0deright** [comment]
My bad, didn't notice help said:

```
Usage:
  command [options] [arguments]
```

`composer install -d /foo/bar/myproject` is working as expected. Thanks for pointing this out.
