### ISSUE TITLE
list "packagist is disabled" as a possible source, when requirements cannot be resolved

### ISSUE THREAD

**Issue by staabm** [composer/composer#8933]
when running updates you sometimes run into the problem that packages cannot be resolved.

![grafik](https://user-images.githubusercontent.com/120441/83257969-b9686300-a1b5-11ea-9d21-6787b1f973f2.png)

today the cause of this problem was, that packagist was disabled for my current project

using

```
  "repositories" : [
    {"packagist.org": false}
  ]
```

what do you think about adding a "its a public package and packagist.org is disabled in composer.json"-reason in case packagist.org is disabled?

**Comment by Seldaek** [comment]
Given there are various conditions where disabling packagist.org is legitimate, and also seeing as people generally speaking already don't read error messages and making them longer doesn't tend to help, we decided we'd rather not add this. Hopefully it's happening rarely enough that it's not such a big problem.
