### ISSUE TITLE
composer and sudo in sequence

### ISSUE THREAD

**Issue by mk-mxp** [composer/composer#8934]
I am a great fan of composer and do not use composer as root. I'm doing root things with sudo as often as necessary and stumbled upon this problem.

When running sudo the state is saved for a while before I need to re-authorize sudo with my password. This is expected behaviour. But when when I run composer, I always must re-authorize afterwards, no matter how much time has passed. This can be proven by this:

```
$ sudo echo "test"; sudo echo "test2"; composer --version; sudo echo "test3"
[sudo] Password for mk: 
test
test2
Composer version 1.10.5 2020-04-10 11:44:22
[sudo] Passwort for mk: 
test3
```

It also happens with 1.10.6. I do not have older composer versions around to prove when this started. I'm using BASH in a variety of Ubuntu systems, from 16.04 to 20.04, with PHP from 7.0 to 7.4, and have this problem on all of them.

**Comment by stof** [comment]
That's actually a feature, to prevent scripts and composer plugins from being able to benefit from an active sudo session. See https://github.com/composer/composer/blob/e8aae7a86bd952ae670f66e88ecac7ebd0e01dbe/src/Composer/Console/Application.php#L240-L244 and https://github.com/composer/composer/issues/5119

**Comment by mk-mxp** [comment]
OK, another feature intended to raise security but actually reducing it. Because the only way to workaround this is: run all of the script invoking composer as root. Which you shouldn't.

**Comment by Seldaek** [comment]
You can disable this by setting COMPOSER_ALLOW_SUPERUSER=1 if you want. No need to run composer with sudo.

**Comment by mk-mxp** [comment]
@Seldaek You missed the point. It's not about composer, it's about composer killing (possibly) unattended script runs like:

```
sudo apt-get install $packages       <- the very first command where the user is still here, this takes about 45-60 minutes
composer install
sudo chown -r www-data. web/public   <- this command will not be run, but wait for the user
```

And the only way to work around that annoying stop in the script is to run **all** as root.

**Comment by Seldaek** [comment]
No.. as I said if you set the env var composer will not kill the root session. It does open you up to scripts/plugins running sudo commands though, as @stof said above.

**Comment by mk-mxp** [comment]
It's a bug then?

```
COMPOSER_ALLOW_SUPERUSER=1; sudo echo "test"; sudo echo "test2"; composer --version; sudo echo "test3"
[sudo] Password for mk: 
test
test2
Composer version 1.10.5 2020-04-10 11:44:22
[sudo] Passwort for mk: 
test3
```

**Comment by Seldaek** [comment]
you need `export COMPOSER_ALLOW_SUPERUSER=1`, or to set it only for the composer process `COMPOSER_ALLOW_SUPERUSER=1 composer --version`

**Comment by mk-mxp** [comment]
Thank you! Exporting that variable is not necessary in a script...fine. Thank you, again!
