### ISSUE TITLE
Generate runtime platform check even when platform config is defined in composer.json

### ISSUE THREAD

**Issue by naderman** [composer/composer#8935]
The purpose of the runtime platform check is to verify that the set of dependencies installed on another platform with composer update works on the current platform used to execute the code. This may happen if you use PHP 7.4 on local development to run composer update, receive a dependency which requires PHP 7.4 and then copy the resulting vendor directory to a production system running PHP 7.3. Instead of running into errors down the line, the platform check will immediately fatal error because the PHP version 7.3 is not supported by the dependencies you installed.

If you set the platform configuration PHP version to 7.4 and run composer update on PHP 7.3 you may still get a dependency installed which only works on PHP 7.4, which is intentional now, because you defined the platform config to allow this. When you then copy the dependencies over to another system you expect to be running on 7.4, but is in fact still only running 7.3, the runtime platform check should error as well, as platform you are running on is both lower than the configured PHP version and lower than one of the dependencies in your project.

I don't think the runtime platform check should error if the PHP version is lower than the platform config if there is no actual requirement for a higher PHP version in any dependency. So the check should probably simply work as usual, since the platform config is taken into account when resolving deps.

**Comment by artem-prozorov** [comment]
@naderman do you have any type of specification for this?

**Comment by nicolas-grekas** [comment]
Isn't this solved by making the check account only for deps and never the actual runtime nor config.platform.php? Isn't it how it already works btw?

About setting config.platform.php to 7.4 while running on 7.3, this might still create troubles with plugins, eg doing so while using any doctrine dep will explode thanks to ocramius/package-versions.

I wouldn't be shocked if Composer 2 were to refuse to run if config.platform.php were set to a higher major.minor than the current runtime (but this should ignore the patch number: we use 7.4.99 as a trick to solve deps on php8 and that's fine).

**Comment by naderman** [comment]
@artem-prozorov not sure what exactly you are looking for?

**Comment by naderman** [comment]
@nicolas-grekas The point of my last paragraph was that it doesn't make sense for the platform config to be considered in the runtime check if all the installed deps are compatible with the older currently running PHP version.

**Comment by artem-prozorov** [comment]
> @artem-prozorov not sure what exactly you are looking for?

In other words, am I free to contribute and post a PR for this feature? If so, are there any preferences / considerations about how to accomplish this technically or are you opened for suggestions?

**Comment by naderman** [comment]
So just reviewed the code, and it does exactly what I describe here already.

The confusion stemmed from Jordi stating in https://twitter.com/seldaek/status/1267515231502323713 "I think platform config is actually completely ignored right now wrt platform check." - which I understood to mean the platform check does not generated at all if a platform config is used. However that is not what he meant, he meant that the platform config isn't used as input for the check, which is exactly what I described here too. So closing this, as there is nothing to be done anyway :-)
