### ISSUE TITLE
HHVM 3

### ISSUE THREAD

**Issue by GrahamCampbell** [composer/composer#8939]
Composer 1.10 works fine on HHVM 3 (I am testing software needs to support HHVM https://github.com/vlucas/phpdotenv/commits/2.6), however 2.0-dev crashes with:

```
  [ErrorException]                                             

  curl_multi_setopt():Invalid curl multi configuration option  
```

Perapse there should be a way to tell composer not to use curl, even if it is available?

**Comment by stof** [comment]
Can you run it in verbose mode to get the stack trace ? It makes things easier to investigate.

**Comment by stof** [comment]
this would allow knowing which of the `curl_multi_setopt` calls is failing.

**Comment by GrahamCampbell** [comment]
I am testing with HHVM 3.18.8 and 3.30.12. Both give the following trace:

![image](https://user-images.githubusercontent.com/2829600/83527933-60177100-a4e0-11ea-9cee-4f6b8e96c14d.png)

**Comment by GrahamCampbell** [comment]
I guess it's here: https://github.com/composer/composer/blob/master/src/Composer/Util/Http/CurlDownloader.php#L79. Maybe we can simply check HHVM_VERSION is not defined too?

**Comment by Seldaek** [comment]
Weird they'd define the const but not support it but anyway.. Easy fix so let's do it.

**Comment by GrahamCampbell** [comment]
I'm not sure what php version id they have too. Maybe it is mimicking 7.999.999, in which case a 2nd fix will be in order for the code on line 79. I'll test it again shortly and see what happens...

**Comment by GrahamCampbell** [comment]
Seems to work now. 🚀

**Comment by stof** [comment]
In https://github.com/facebook/hhvm/commit/d40071053775a027dd96aee1d5290ee2e7ac2fa2, they imported a bunch of PHP curl constants, with subsequent commits meant to implement them. I suspect that the subsequent commits were incomplete...

**Comment by GrahamCampbell** [comment]
Ok, I spoke too soon. HHVM 3.18.x is working, but 3.30.x is not, for a different reason:

![image](https://user-images.githubusercontent.com/2829600/83530903-4415ce80-a4e4-11ea-9ce9-a5eb26c9ad82.png)

**Comment by Seldaek** [comment]
Ah that's a typo, will fix.

**Comment by stof** [comment]
Could it be related to the fact that the `loop` is lowercase in the typehint ? Maybe HHVM 3.30 does not properly treats class name case insensitively.

**Comment by GrahamCampbell** [comment]
Yes and yes. :)

**Comment by Seldaek** [comment]
You can try again

**Comment by GrahamCampbell** [comment]
Yep, that did the trick. 🎉
