### ISSUE TITLE
Composer failing to find new version tags in VCS package

### ISSUE THREAD

**Issue by AmericanUmlaut** [composer/composer#8947]
My `composer.json`:

```json
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "type": "project",
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/[company-project]/[company-repo].git"
        }
    ],
    "require": {
        "php": "^7.2",
        "fideloper/proxy": "^4.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^5.8.0",
        "laravel/tinker": "^1.0",
        "[company-project]/[company-repo]": "1.*"
    },
    "require-dev": {
        "barryvdh/laravel-ide-helper": "^2.4",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "HESGUI\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true,
        "discard-changes": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.7
PHP version: 7.4.5
PHP binary path: /usr/local/Cellar/php/7.4.5_2/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020

```

When I run this command:

```
git tag #within the package's directory after a fresh clone to ensure it's up to date

composer show [company-project/company-package] --all
```

I get the following output:

```
# git tag
v1.1.0
v1.1.1
v1.1.10
v1.1.11
v1.1.12
v1.1.2
v1.1.3
v1.1.4
v1.1.5
v1.1.6
v1.1.7
v1.1.8
v1.1.9
v1.2.0
v1.2.1

# composer show [company-project/company-package] --all
name     : [company-project]/[company-package]
descrip. : 
keywords : 
versions : dev-master, * 1.1.8, 1.1.7, 1.1.6, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1, dev-release
type     : library
homepage : 
source   : [git] [company-package-git-url] 41d67c6f95b550e2fe36c6c54f09e9bf023a05fe
dist     : []  
path     : [...]/vendor/[company-project]/[company-package]
names    : [company-project]/[company-package]

autoload
psr-4
HESCommon\ => src

```

And I expected this to happen:

I expect the versions list in the response to include 1.1.5 and all of the versions that are greater than 1.1.8. Instead, 1.1.8 is the most recent version recognized, and 1.1.5 is also omitted. I am able to resolve this issue by manually entering version 1.2.1 and the corresponding hash into my composer.lock, then deleting the package from vendors/ and running `composer install`.

I have tried running `composer clear-cache`, adding additional new versions, deleting and re-cloning the repository, and trying the whole thing on a different system, but have had the same result each time. I have also run `git tag` from within the package directory in vendors/ and confirmed that all of the tags are listed.

I am happy to provide a reviewer with read-only access to the package repository if it's not possible to diagnose the issue from the information given here.

**Comment by AmericanUmlaut** [comment]
Further information:

I was able to get the correct version of the package to install by adding a new version tag ("v1.2.2") to a commit in which I also added the "version" property to the package's composer.json, which according to my understanding of the documentation should not be necessary.

**Comment by Seldaek** [comment]
If you run `composer show -a foo/bar -v` (add `-v`) it should show you in detail as it loads the repository what is going on and why it skips a given version. Typically it's because people specify the version field and forget to update it, if it doesn't match the tag name then the tag is ignored. So yeah definitely you should rather not specify that in composer.json. I can't help you more than this though if the repo isn't public.

**Comment by AmericanUmlaut** [comment]
@Seldaek Thank you very much for taking the time to respond to this.

The additional verbosity (for anyone coming across this ticket in the future: the verbosity flag actually needs to be `-vv` or `-vvv` to see the explanation of why a version is skipped) did the trick. The problem was the "version" tag in composer.json not matching the tag.

This is resolved for us. Again, thank you so much for taking the time to respond.
