### ISSUE TITLE
Misleading error message for tags with -dev suffix

### ISSUE THREAD

**Issue by glaubinix** [composer/composer#8951]
Using VCS repositories with Composer that have tags with a `-dev` suffix will result in a misleading message during composer update.

Steps to reproduce:
* create a tag with a `-dev` suffix e.g. `2.0.x-dev`
* run a composer update with verbose output which will show a message that the tag couldn't not be imported because the version in the composer.json doesn't match the tag e.g. `Skipped tag v.2.0.x-dev, tag (dev-v.2.0.x) does not match version (v.2.0.x) in composer.json`

I would expect a message that explains that tags with a `-dev` suffix are not supported

**Comment by Seldaek** [comment]
This comes from https://github.com/composer/composer/blob/627afe78ca89df139d20fcb4374c32a7424146b6/src/Composer/Repository/VcsRepository.php#L228-L238 for the record. Possibly should be clarified yes :)
