### ISSUE TITLE
Inline Alias not working in 2.0.0-alpha1

### ISSUE THREAD

**Issue by swiffer** [composer/composer#8954]
My `composer.json`:

```json
...
        "cakephp/authentication": "^2.0",
        "cakephp/authorization": "^2.0",
        "cakephp/cakephp": "dev-4.next as 4.1.0-RC2",
...
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.0-alpha1
PHP version: 7.4.4 - Package overridden via config.platform, actual: 7.4.7-dev
PHP binary path: c:\program files\php\php.exe
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

When I run this command:

```
composer update
```

I get the following output:

```
  Problem 1
    - Root composer.json requires cakephp/authentication ^2.0 -> satisfiable by cakephp/authentication[2.3.0].
    - cakephp/authentication 2.3.0 requires cakephp/core ^4.0 -> could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Root composer.json requires cakephp/authorization ^2.0 -> satisfiable by cakephp/authorization[2.0.3].
    - cakephp/authorization 2.0.3 requires cakephp/cakephp ^4.0 -> found cakephp/cakephp[dev-4.next] but it does not match the constraint.
...
```

And I expected this to happen:
In Composer 1.10.7 running `composer update` works fine and installs dev-4.next branch without issues.

**Comment by swiffer** [comment]
I've set up a demo project to showcase the problem:

https://github.com/swiffer/demo_project

running `composer update` fails in 2.0.0-alpha1 and succeeded in 1.10.7.

**Comment by GrahamCampbell** [comment]
Does it work if you pin a specific commit from the dev branch using the hash symbol?

**Comment by swiffer** [comment]
no, same problem

**Comment by GrahamCampbell** [comment]
I've not been able to replicate this in the master version, actually.

**Comment by swiffer** [comment]
Still not working here :( have you tried running composer update from my demo project ?

**Comment by GrahamCampbell** [comment]
The following works:

```json
{
    "require": {
        "php": ">=7.2",
        "cakephp/authentication": "^2.3",
        "cakephp/cakephp": "dev-4.next as 4.1.0-RC2",
        "cakephp/migrations": "^3.0",
        "cakephp/plugin-installer": "^1.2",
        "mobiledetect/mobiledetectlib": "^2.8"
    },
    "prefer-stable": true
}
```

**Comment by GrahamCampbell** [comment]
Why is this hack even needed? Cake should implement branch aliases properly, so you can just ask composer for `^4.1@dev`.

**Comment by swiffer** [comment]
> 
> 
> The following works:
> 
> ```json
> {
>     "require": {
>         "php": ">=7.2",
>         "cakephp/authentication": "^2.3",
>         "cakephp/cakephp": "dev-4.next as 4.1.0-RC2",
>         "cakephp/migrations": "^3.0",
>         "cakephp/plugin-installer": "^1.2",
>         "mobiledetect/mobiledetectlib": "^2.8"
>     },
>     "prefer-stable": true
> }
> ```

Have you tried using the demo_project I've linked. For me it still isn't. I've uploaded a screencast to demo the issue in --preview and --snapshot.

- https://youtu.be/odDmZDfGEv8 - Initial clone & install
- https://youtu.be/odDmZDfGEv8?t=188 - `composer update` - 1.10.7
- https://youtu.be/odDmZDfGEv8?t=202 - `composer update` - 2.0.0-alpha1
- https://youtu.be/odDmZDfGEv8?t=235 - `composer update` - snapshot
- https://youtu.be/odDmZDfGEv8?t=253 - `composer update` - 1.10.7

**Comment by jaydiablo** [comment]
I ran into this as well testing Composer 2.0.  I just tested a `dev-master` build to see if there was anything in the recent commits that fixed it (based on @GrahamCampbell's comments that he wasn't seeing it in `master`) but I get the same error.

**Comment by emodric** [comment]
Yep, ran into the same issue just now. 

From `require` section:

```
"ezsystems/ezpublish-legacy-installer": "dev-composer2 as 2.0.5"
```

`repositories` section:

```
"repositories": [
    { "type": "vcs", "url": "git@github.com:emodric/ezpublish-legacy-installer.git" }
],
```

Result of `composer update`:

```
Loading composer repositories with package information
Updating dependencies
Unable to find a compatible set of packages based on your non-dev requirements alone.
Your requirements can be resolved successfully when require-dev packages are present.
You may need to move packages from require-dev or some of their dependencies to require.

  Problem 1
    - ezsystems/legacy-bridge v2.1.5 requires ezsystems/ezpublish-legacy-installer ^2.0.4 -> found ezsystems/ezpublish-legacy-installer[dev-composer2] but it does not match the constraint.
```

**Comment by Seldaek** [comment]
The minimum repro case was something like:

```
{
    "require": {
        "cakephp/authentication": "2.3.0",
        "cakephp/cakephp": "dev-4.next as 4.1.0-RC2"
    },
    "require-dev": {
        "cakephp/bake": "2.1.1"
    }
}
```

Anyway there is a fix in https://github.com/composer/composer/pull/8982 - thanks for reporting!

**Comment by jaydiablo** [comment]
This works now (built a phar from github clone), and wow, impressive stats from Composer 2!

Composer 1 for this particular app: `Memory usage: 1114.79MiB (peak: 3529.46MiB), time: 277.78s`

Composer 2 for the same app: `Memory usage: 80.84MiB (peak: 824.72MiB), time: 155.29s`

(cache and vendor dir cleared before each run)

Thanks!
