### ISSUE TITLE
Composer Installation Error Unable to continue with Installation

### ISSUE THREAD

**Issue by adicoderanger** [composer/composer#8967]
After downloading the Composer-Setup.exe file and 

**When I ran the Composer-Setup.exe file**

**I was get the following output:**

![image](https://user-images.githubusercontent.com/43764560/84301823-6af68500-ab22-11ea-9b07-af683549b5ca.png)

**And I expected this to happen:**
I expect composer to be Installed on my PC

**Comment by johnstevenson** [comment]
Either update the certificate file from https://curl.haxx.se/docs/caextract.html or comment out the openssl.cafile ini setting.
