### ISSUE TITLE
Remove redundant code

### ISSUE THREAD

**Issue by chippyash** [composer/composer#8968]
As there doesn't appear to be a discussion place for Composer (happy to be proven wrong) I am posting here.

Composer, like many other code dependency systems does a fantastic job of managing dependencies. It does its job.

Problem: There is no way to remove redundant code for a Production package.

Use case: include the AWS PHP SDK. Use the S3 component. You don't need anything else other than S3 and some supporting interfaces, abstractions etc. But you get to upload the whole megabytes of library. Ditto Symfony, Zend, Laravel etc.

Use case: [bref](https://github.com/brefphp/bref) is aiming at allowing PHP devs to deploy to AWS Lambda. It works really well. Major problem is the upload size.

I don't think this is directly a Composer problem, but I do think it is something that PHP devs need to worry about.  So, opening it up here as in [Bref](https://github.com/brefphp/bref/issues/669) for comments and suggestions.

**Comment by villfa** [comment]
@chippyash here a Composer plugin that may help you: https://github.com/dg/composer-cleaner

**Comment by Seldaek** [comment]
Yeah composer-cleaner helps to reduce the amount of useless cruft. It won't completely help for huge packages like the AWS SDK though, for Symfony you should rely on individual components to avoid installing it all, but for the AWS SDK that option doesn't exist.. Maybe using https://async-aws.com/ instead would result in smaller package size.

Anyway closing this as there isn't anything we can do really, but feel free to discuss further if anyone has more to say :)
