### ISSUE TITLE
An error occurred while executing composer require

### ISSUE THREAD

**Issue by gaizhixin** [composer/composer#8969]
When I install swagger-php.
Composer error: proc_open (): fork failed-Invalid argument
It runs on WSL
My PHP version is 7.4.6
Composer version is 1.10.7

**Comment by Seldaek** [comment]
Please provide full output with `-vvv`..

**Comment by gaizhixin** [comment]
@Seldaek I've solved it. I'm using WSL. I think my SWAP memory setting is too small.
