### ISSUE TITLE
Alpha version shipped as default

### ISSUE THREAD

**Issue by Mezzle** [composer/composer#8970]
When downloading 

https://getcomposer.org/composer.phar

I get composer version

```
Composer version 2.0-dev (2.0-dev+9d5051faac0b94c99133936e1872a8d115dfbd44) 2020-06-05 14:02:02
```

This breaks a lot of install things that may require the old Composer API.

This was noticed when the PHP module in forge grabbed this version and a build of a magento install failed due to the wrong API version

**Comment by stof** [comment]
This is totally expected, as that's the URL for the latest snapshot built (updated at each commit of the master branch). The latest stable release is available at https://getcomposer.org/composer-stable.phar as documented on https://getcomposer.org/download/
