### ISSUE TITLE
Merged PR #8659 missing from current codebase

### ISSUE THREAD

**Issue by johnstevenson** [composer/composer#8972]
Unless I am going mad, https://github.com/composer/composer/pull/8659 was merged into the 1.9 branch on Feb 28 2020, but does not seem to be in the current codebase (master or 1.10).

**Comment by Seldaek** [comment]
It does indeed seem like this got lost, I guess I merged this just before moving master into 1.10 and wiping out 1.9, and didn't realize this never got merged up.. Anyway it's back now https://github.com/composer/composer/commit/54debe821

**Comment by johnstevenson** [comment]
Thanks.
