### ISSUE TITLE
[enhancement] Highlight major version upgrade in `update` command output

### ISSUE THREAD

**Issue by alterphp** [composer/composer#8976]
Hi,

This is a suggestion. When running `update` command, I'd love to see major version upgrades highlighted, as they require more attention.

**Comment by Seldaek** [comment]
Do you have any suggestion how you'd highlight these?

**Comment by alterphp** [comment]
inversed text/background in the std output or any `warning` icon at the line beginning

**Comment by alterphp** [comment]
or a `MAJOR` tag at the line beginning

Anything that breaks the flow of updated packages

**Comment by Seldaek** [comment]
Tried it a little, and really I can't find a way to highlight it which is meaningful and not too intrusive. Either it's clearly stated MAJOR like you suggested, but then that's also ugly as hell, or you just use a smaller warning icon or something but then it looks like there's an error.

The bottom line is I am not so convinced this needs highlighting at all, usually the only major updates you should care about are those of your own dependencies, and you should be consciously bumping those requirements yourself so you are probably aware of those. So all in all doesn't seem worth the trouble.
