### ISSUE TITLE
how to uninstall composer from mac?

### ISSUE THREAD

**Issue by forgottenouthere** [composer/composer#8977]
installed globally on desktop. should I just delete files from desktop or is there anything else? 

Thank You

![Screen Shot 2020-06-15 at 16 29 37](https://user-images.githubusercontent.com/66563936/84663143-6ddbe600-af25-11ea-8229-fc9fbfdc30e6.png)

**Comment by GromNaN** [comment]
Depending on how you [installed](https://getcomposer.org/doc/00-intro.md#globally) composer, you may have to remove `/usr/local/bin/composer`.

**Comment by forgottenouthere** [comment]
hi @GromNaN 

thanks for reaching out. 

I tried doing that, but I'm not sure if it went through. 

it also didn't remove the files on the desktop, not sure if I have to remove these myself. 

could you instruct me as to how to uninstall this, or check if it's uninstalled already?

* I installed it by following the instructions in this video:

https://laracasts.com/series/laravel-6-from-scratch/episodes/2?autoplay=true

**Comment by forgottenouthere** [comment]
help, anybody?

**Comment by gabrielpires** [comment]
@forgottenouthere Hi, you have a few options to check/remove your installation.

The screenshot isn't the composer, it is the packages you installed for the project. 

Composer is a package manager, can be installed globally, the packages you install with it should live along with your project. So you can remove those files in the screenshot.

Could you clarify a bit more about what you want to remove besides those files?

**Comment by forgottenouthere** [comment]
hi Gabriel

thanks for replying :)

I have since reinstalled the system on my mac, but I don't know if it's related. anyway, the computer works fine at the moment, so I wouldn't want to mess around with it too much. I did remove these folders since I wrote this by simply throwing them to the trash. other than that, I don't know if/where there's anything else which should be removed.

**Comment by stof** [comment]
@forgottenouthere as said by @gabrielpires, the files in your screenshot are **not** the composer installation. they are a projet *using* composer. So removing them is not about uninstalling composer.

**Comment by forgottenouthere** [comment]
I know, that's the reason I opened this thread. I was expecting a professional to tell me something in the lines of: 

"here's how to uninstall composer"... 

any luck guess?

* I'm using a mac running the latest catalina version. 

I think there was a search I ran in terminal regarding composer folder or something, but nothing was found. this was a while ago.

**Comment by stof** [comment]
Well, the answer about removing Composer itself was given in https://github.com/composer/composer/issues/8977#issuecomment-644171861
Composer is a single file (as it is distributed as a Phar). So uninstalling it is just about removing that file (you might want to clear the composer cache first so that the cache is also deleted).
The files you showed in your screenshot are indeed not removed, but that's unrelated as they are *not* part of the composer installation (expecting them to be removed would be equivalent to thinking that uninstalling Microsoft Word from a computer should delete all `.docx` files on that computer too)

**Comment by forgottenouthere** [comment]
@stof 
could you do a step by stem explanation of how to go about it on a mac?

if I remember correctly, I installed it following the instructions in the composer website. it was part of my trying to install Laravel, which was an epic fail...

**Comment by xabbuh** [comment]
If you type `type composer`, you should see the path where Composer is stored. Then you can delete that file.

**Comment by forgottenouthere** [comment]
@xabbuh thanks, I assume you meant typing that in terminal. 

result: not found...

so maybe it's uninstalled after all.

**Comment by prashanthkp4** [comment]
Check this out!

https://youtu.be/5x7DjQHjVmY
