### ISSUE TITLE
[Composer 2] Option to hide lock file operations

### ISSUE THREAD

**Issue by emodric** [composer/composer#8979]
It would be nice to have an option (maybe even activated by default, unless `--lock` is provided) to hide the `Lock file operations` section from Composer 2 output as it contains completely redundant information which is already contained in `Installing dependencies from lock file` section:

When I run this command:

```
composer update
```

I get the following output:

```
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading jean85/pretty-package-versions (1.3.0 => 1.4.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Upgrading jean85/pretty-package-versions (1.3.0 => 1.4.0): Extracting archive
```

And I expected this to happen:

Not to show redundant information, as the output can grow quite significantly in case of many dependencies.

**Comment by Seldaek** [comment]
If anything, we should hide the details of the "Installing dependencies from lock file" step while running updates, as the lock file changes are actually the most critical bit here, the rest is just saying what it does to get your vendor dir in sync with the lock file, which ultimately isn't that relevant. But yes generally speaking I agree it is getting a bit verbose, we need to get a bit more experience with it and find the right balance.

**Comment by emodric** [comment]
One area where `Installing dependencies from lock file` is more useful is additional details, e.g. notice that the package is symlinked when using path repo:

```
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 2 updates, 1 removal
  - Removing composer/package-versions-deprecated (1.8.1)
  - Upgrading jean85/pretty-package-versions (1.3.0 => 1.4.0)
  - Upgrading netgen/layouts-standard (dev-master a5fcae4 => dev-master c37e924)
  - Locking ocramius/package-versions (1.8.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 2 updates, 1 removal
  - Removing composer/package-versions-deprecated (1.8.1)
  - Installing ocramius/package-versions (1.8.0): Extracting archive
  - Upgrading jean85/pretty-package-versions (1.3.0 => 1.4.0): Extracting archive
  - Upgrading netgen/layouts-standard (dev-master a5fcae4 => dev-master c37e924): Symlinking from ../layouts-standard
Generating autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
102 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Symfony recipes are disabled: "symfony/flex" not found in the root composer.json

What about running composer global require symfony/thanks && composer thanks now?
This will spread some 💖  by sending a ★  to the GitHub repositories of your fellow package maintainers.
```

**Comment by stof** [comment]
`Installing dependencies from lock file` might contain more operations, if your existing vendor dir was not in sync with the previous lock file.

**Comment by naderman** [comment]
I think we absolutely need to display both of these steps separately. I think this will have an extremely positive effect on user's understanding of the distinction between composer update and install as well as the general difference between the lock file and the vendor directory.

Maybe there is a way to make the output a bit shorter, but I think hiding either of those steps or merging them together is going to do our users a disservice. One of the main difficulties for novice users with Composer is understanding what the purpose of the lock file is and how it works, the separated output in 2 steps will help them a lot.

**Comment by Seldaek** [comment]
Closing as now after a while using Composer 2 IMO in practice this is a good thing.

**Comment by emodric** [comment]
For what it's worth, I still think that the first section is pretty much superfluous and leads to less readable and manageable output in terminal, especially with lots of dependencies, since there's lots of information repeated. But, obviously, I'm the only one bothered by this :)

**Comment by Seldaek** [comment]
I usually look only at the first section because those are the actual changes which happened to the dependencies, what is applied to the vendor dir is not really important as it may include older dependency updates if my vendor dir was not in sync with the lock file before the update.

**Comment by emodric** [comment]
My usecase is that I usually look at the second section precisely becuase it shows the updates to actual code and not the lock file. I am usually more interested that a package went from 1.2.3 to 1.2.5 in vendor, so I can corelate that with the changelog, rather than the fact that the lock file was updated from 1.2.4 to 1.2.5.

**Comment by stof** [comment]
@emodric but if the lock file only goes from 1.2.4 to 1.2.5, it means someone else in your team already performed the upgrade from 1.2.3 to 1.2.4 (and that you haven't run `composer install` after that to sync your local clone)

**Comment by emodric** [comment]
I am aware of that. And as I said, for me, more relevant information is that my local install went from 1.2.3 to 1.2.5. Because, in the end, I am interested in exactly that: the exact version change of the running package in my install, so I can trace the exact changes in the running code. The fact that someone ran the update some time before and that I forgot to run `composer install` some time before is completely irrelevant.

I suppose we all have different usecases, which only goes to show that, obviously, both sections in Composer output are relevant :)

**Comment by stof** [comment]
So you are more interested in the changelog impacted your local setup than in the changelog impacting the deployed code (assuming that your deployment pipeline makes sure to always deploy the locked dependency) ?

**Comment by emodric** [comment]
@stof Precisely! For deployment, I only care about the target version of the lib in `vendor/`, it doesn't really matter what was the version before. Our deployment process always makes sure that the lock file is used properly, and besides, unless an error happens, I don't event bother to check the Composer output when deploying.

As for the local setup, yes, I care about the *real* changelog, so I can be aware of potential impact to behaviour. The fact that my lock file was updated from a version I wasn't even running, is, IMO, pretty much worthless.

**Comment by stof** [comment]
@emodric but if *you* are not running the current locked version, the prod is probably already running it (based on the update done by your coworker)

**Comment by emodric** [comment]
Well, not necessarily. Not all changes in lock file are immediately deployed to production. Why would they be?

**Comment by stof** [comment]
@emodric even if you skip a deployment because you do 2 upgrades in a row, the first upgrade from 1.2.3 to 1.2.4 (which changed the lock file) has already been checked when doing it (or at least it should, as it could have been deployed to prod without doing another upgrade before the deployment).

**Comment by emodric** [comment]
> or at least it should

This is the keyword here :) It should be checked, but not always is, nor I can assume it is checked. I personally feel I'd do a half-arsed job if I didn't make sure that the bump in all my local dependencies doesn't cause issues, even if some of them are already checked/deployed.

This situation is usually more evident when there are more dependencies that are updated, and only one of them is out of sync. Knowing what exact package is out of sync with the lock file is not really easy. You'd have to go up and down in the output and compare versions for each of the packages. It is waaay easier just look at the second section and review changes there, even if some of them were already reviewed by others.

**Comment by stof** [comment]
@emodric but saying that the first section is superfluous because you don't use it because you don't trust your coworkers to check upgrades they make to the lock file is a bad justification IMO. Other workflows might be caring more about what actually changes in the lock file (i.e. the first section)

**Comment by emodric** [comment]
The issue is not my miss-trust in my co-workers, I trust them. I don't trust myself, however. The previous update might as well be done by me before on another copy of the project.

Besides, that why this issue is about adding a flag to hide the section, not remove it completely.
