### ISSUE TITLE
UnexpectedValueException: Expected empty path to extract package

### ISSUE THREAD

**Issue by emodric** [composer/composer#8988]
[This commit](https://github.com/composer/composer/commit/73251691a0be65440c722461cb38f8574cea0c25) causes an issue with installing eZ Publish Legacy extensions. The workflow is as follows:

eZ Publish Legacy (`ezsystems/ezpublish-legacy`) is installed to `ezpublish_legacy/` folder.
eZ Publish Legacy itself, provides some extensions out of the box, located in `ezpublish_legacy/extension/` (https://github.com/ezsystems/ezpublish-legacy/tree/2019.03/extension)

Every other extension is its own Composer package, also installed to `ezpublish_legacy/extension`.

After the project is installed for the first time, and after removing `vendor` and `composer.lock` and reinstalling, the issue below is encountered.

**The problem**: When I remove `vendor` and `composer.lock`, I cannot remove `ezpublish_legacy` folder, since it contains the `ezpublish_legacy/var` folder containing binary files uploaded through CMS admin. I also cannot remove `ezpublish_legacy/extension` folder, since 3 of those extensions are provided by the `ezsystems/ezpublish-legacy` package, meaning they won't be reinstalled if I remove them.

In Composer 1 this workflow worked fine, since the package folders were emptied before installing, but Composer 2 throws an exception if the package folder already exists, which it does since I cannot easily remove contents of `ezpublish_legacy/extension` folder.

My `composer.json`:

```json
{
    "require": {
        "ezsystems/ezpublish-legacy": ">=2019.03.4",
        "ezsystems/ezpublish-legacy-installer": "dev-master as 2.0.4"
    },
    "extra": {
        "ezpublish-legacy-dir": "ezpublish_legacy"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
Defining autoload.psr-0 with an empty namespace prefix is a bad idea for performance
require.ezsystems/ezpublish-legacy : unbound version constraints (>=2019.03.4) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0-dev+09fc263d373a4c44c62c71ef56f209d1daf22d92
PHP version: 7.4.6
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

When I run this command:

```
composer install
rm -rf vendor composer.lock
composer install
```

I get the following output:

```
  [UnexpectedValueException]                                                                                                      
  Expected empty path to extract ezsystems/ezwt-ls-extension-5.3.10.0 into but directory exists: ezpublish_legacy/extension/ezwt
```

And I expected this to happen:

For install to pass successfully.

**Comment by Seldaek** [comment]
Ok that should be fixed now, but you still gotta handle the returned promises or you'll get failures. To be able to reproduce that you need to be have `unzip` available on your system btw, and run on OSX/Linux/WSL.

**Comment by emodric** [comment]
Thanks @Seldaek !

Handling promises in the installer is handled with https://github.com/ezsystems/ezpublish-legacy-installer/pull/20, and with that, I don't expect any issues any more :+1:
