### ISSUE TITLE
> `composer config --global cafile '/usr/local/etc/openssl/cert.pem'`

### ISSUE THREAD

**Issue by 234146326** [composer/composer#8992]
> `composer config --global cafile '/usr/local/etc/openssl/cert.pem'`

If this .pem file is accidentally deleted.How should it be regenerated?thank you for your reply.the Lord;

![image](https://user-images.githubusercontent.com/17285770/85050574-e3b3ac00-b1c8-11ea-99f5-7d76f4bf45ec.png)

_Originally posted by @234146326 in https://github.com/composer/composer/issues/6427#issuecomment-646177590_

**Comment by Seldaek** [comment]
You can do `composer config --global --unset cafile` which will make composer use best guess to figure out which CA file to use.. But according to your screenshot it anyway seems to be using /private/etc/ssl/cert.pem and finding it valid, so I'm not sure what the problem is.
