### ISSUE TITLE
Issue with PHP8 in CurlDownloader (composer2)

### ISSUE THREAD

**Issue by jderusse** [composer/composer#8994]
Runing composer req on PHP8 image triggers an exception in CurlDownloader (when casting the resource to int)

```cli
composer init --no-interaction
composer req symfony/phpunit-bridge -vvv
```

```
    [ErrorException]                                          
    Object of class CurlHandle could not be converted to int  
                                                              
  
  Exception trace:
   () at phar:///usr/local/bin/composer/src/Composer/Util/Http/CurlDownloader.php:188
   Composer\Util\ErrorHandler::handle() at phar:///usr/local/bin/composer/src/Composer/Util/Http/CurlDownloader.php:188
   Composer\Util\Http\CurlDownloader->initDownload() at phar:///usr/local/bin/composer/src/Composer/Util/Http/CurlDownloader.php:105
   Composer\Util\Http\CurlDownloader->download() at phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php:260
   Composer\Util\HttpDownloader->startJob() at phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php:223
   Composer\Util\HttpDownloader->addJob() at phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php:84
```

full reproduce-case with docker image
```cli
docker pull devilbox/php-fpm-8.0
docker run --rm -ti devilbox/php-fpm-8.0 bash
apt-get update; apt-get install -y git zip

php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php composer-setup.php
php composer.phar selfupdate --snapshot

php composer.phar init --no-interaction
php composer.phar req symfony/phpunit-bridge -vvv
```

note: got the exact same error with https://github.com/hirak/prestissimo

**Comment by jderusse** [comment]
Looks like related to https://github.com/php/php-src/pull/5402

**Comment by nicolas-grekas** [comment]
@nikic could we allow `CurlHandler` to return their object-id when they're cast to int? It's very common to use curl handles this way.

**Comment by nikic** [comment]
@nicolas-grekas I'd be okay with that, `(int)` cast was also the main issue for guzzle compatibility (https://gist.github.com/nikic/107010824a818d638998494925711b4f).

@kocsismate What do you think about this? Do we want to add an overloaded int cast?

**Comment by kocsismate** [comment]
@nikic Although I'm not fond of the idea, I believe we must do it anyway, to avoid a way too large BC impact. So +1 from my side.

**Comment by Seldaek** [comment]
Ok so closing this here, the issue will fix itself when new PHP builds with the fix get shipped.
