### ISSUE TITLE
Composer 2 --no-interaction bug

### ISSUE THREAD

**Issue by GrahamCampbell** [composer/composer#9001]
Composer gets stuck on asking for authenticity:

```
composer update --no-interaction -vvv
Reading ./composer.json
Loading config file /root/.composer/config.json
Loading config file /root/.composer/auth.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/data): git branch --no-color --no-abbrev -v
Executing command (/data): git remote show origin
The authenticity of host 'gitlab.com (172.65.251.78)' can't be established.
ECDSA key fingerprint is SHA256:HbW3g8zUjNSksFbqTiUWPWg2Bq1x8xdGUrliXFzSnUw.
Are you sure you want to continue connecting (yes/no)? 
```

I think 6349764 is probably the change that broke things? Still kinda odd this happens, because `execute(...)` doesn't use a TTY, so git shouldn't be able to wait like that...

**Comment by GrahamCampbell** [comment]
NB This wasn't happening 7 days ago, so the change happened some time in the last 7 days.

**Comment by GrahamCampbell** [comment]
In verbose mode:

```
Reading ./composer.json
Loading config file /root/.composer/config.json
Loading config file /root/.composer/auth.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/data): git branch --no-color --no-abbrev -v
Executing command (/data): git remote show origin
The authenticity of host 'gitlab.com (172.65.251.78)' can't be established.
ECDSA key fingerprint is SHA256:HbW3g8zUjNSksFbqTiUWPWg2Bq1x8xdGUrliXFzSnUw.
Are you sure you want to continue connecting (yes/no)? 
```

**Comment by GrahamCampbell** [comment]
Ok, I think https://github.com/composer/composer/commit/6349764c2db1bdaad3099547512c4acbafe3a2e0 is probably the change that broke things?

**Comment by Seldaek** [comment]
I guess this is on a build machine or something? I find it surprising that you'd get an error for the origin remote, as you most likely cloned from it, it should be in known hosts already. We surely need to fix this regardless though.

**Comment by GrahamCampbell** [comment]
It will happen if someone uses the composer 2 docker image, for example.

**Comment by Seldaek** [comment]
Huh really? Would it not use your ~/.ssh dir from the machine even if the composer process is in the container?

**Comment by GrahamCampbell** [comment]
Not unless I explicitly mounted it. In any case, the error would have still been triggered, actually. ;)
