### ISSUE TITLE
"composer update" not working

### ISSUE THREAD

**Issue by prungprung** [composer/composer#9003]
![1592813919846](https://user-images.githubusercontent.com/33546861/85265506-8f484f00-b49c-11ea-95a8-b2a00669cd7f.jpg)
I use this command "composer update",and i got this error

**Comment by nattawut2** [comment]
i same problem.

**Comment by ek0519** [comment]
Good Game......

**Comment by ek0519** [comment]
get off work......

**Comment by whchi** [comment]
Same here, looks like it's https://packagist.org/ have some problem.

**Comment by Seldaek** [comment]
We're having bandwidth issues on our Asia mirror, I will try and resolve this ASAP. In the meantime, you can try using Composer 2 via `composer self-update --snapshot`, which is more network efficient and hopefully will get through.

**Comment by nattawut2** [comment]
@Seldaek Thank you is work for me.

**Comment by prungprung** [comment]
@Seldaek Thanks you for your answer and advice

**Comment by pavarnos** [comment]
working now but slow from New Zealand (was seeing only partial downloads of http://repo.packagist.org/p/provider-* files). Thank you @Seldaek

**Comment by cw-hrtech** [comment]
I same problem.

I try server in **Viet Nam, Singapore** (Error), but I try server **N. Virginia** working now 

![image](https://user-images.githubusercontent.com/47654519/85278479-3635e680-b4af-11ea-9788-9a7eb0a8e686.png)

**Comment by jaiwalker** [comment]
same issue

**Comment by HarishSTOnline** [comment]
I was trying to find the issue for the past hour! Thought it was my internet issue.

**Comment by Seldaek** [comment]
Ok we have now more bandwidth available. I hope things will stabilize in a few minutes once the bulk of people waiting get through.

BTW I would still recommend trying composer 2 if you can.

**Comment by dipakmdhrm** [comment]
@Seldaek Won't updating to composer 2 cause compatibility issues?
How about using other mirrors listed at: https://packagist.org/mirrors?

**Comment by Seldaek** [comment]
See https://github.com/composer/composer/blob/master/CHANGELOG.md#200-alpha1-2020-06-03 for v2 changelog and upgrade guide.  There are a few but not many incompabilities. Mostly it's plugins that might hold you back.

**Comment by Seldaek** [comment]
As for other mirrors, they are not official ones and we can't guarantee anything security wise, but otherwise they're an ok option I think, if they help in your region.

**Comment by parmonov98** [comment]
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Content-Length mismatch, received 1463351 bytes out of the expected 2492320
http://repo.packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
```

**Comment by Seldaek** [comment]
@parmonov98 This kind of me too comment is rather useless spam. Please report a new issue if you can reproduce this conclusively, including the details we ask for in new issues. But most likely this is a network issue that will resolve itself I guess.

**Comment by zerkms** [comment]
@Seldaek this sort of errors can only happen because of the http server problems.

**Comment by Seldaek** [comment]
@zerkms I agree it usually does, but looking at our bandwidth usage lately we are really not peaking, and the release of Composer 2 seems to have helped clear up some usage even so I don't see what we can do about it. It's another situation as in the original issue here whereas back in June the bandwidth we had available in Asia was definitely not enough.
