### ISSUE TITLE
Easier determining installed versions of packages

### ISSUE THREAD

**Issue by pretzlaw** [composer/composer#9004]
My `composer.json`:

```json
{
  "name": "foo/bar",
  "require": {
    "pimple/pimple": "^3.0"
  },
  "require-dev": {
    "phpstan/phpstan": "*",
    "symfony/yaml": "~3|~4"
  }
}
```

After running `composer update` all packages get installed and/or package versions might change.

## Situation

> As a package-developer
> I want to offer compatibility to other package-versions
> so that more people can use my package.

What I NOT want: My `foo/bar:1.0` is compatible to `x/y:~3`
and my `foo/bar:2.0` is compatible to `x/y:~4` (but incompatible `x/y:~3`).

What I want: My `foo/bar:1.0` should be compatible to `x/y:~3` as well as `x/y:~4` . 

### Common example

Most of the time from one major-version to another the interface of third-party-classes changes. So for me I need to have a "proxy" to this new interface. Lets say:

* In Symfon3 it says `\Symfony\Component\Yaml\Yaml::parse($input, $flags = 0)`
* In Symfony4 it says `\Symfony\Component\Yaml\Yaml::parse(string $input, int $flags = 0)`

We take this slight difference as an example. Please keep in mind that this can get a bit more complex for other scenarios. Anyhow we define compatibility like this:

```php
<?php // src/Foo/Bar/Yaml.php

namespace Foo\Bar;

use Foo\Bar\Compat\Symfony3\Yaml as Symfony3Yaml;
use Foo\Bar\Compat\Symfony4\Yaml as Symfony4Yaml;

switch (true) {
    case PHP_VERSION_ID < 701000:
        class_alias(Symfony3Yaml::class, Yaml::class);
        break;
    default:
        class_alias(Symfony4Yaml::class, Yaml::class);
}
```

So when I do

```
$yaml = new \Foo\Bar\Yaml();
```

then I actually get ...

* `Foo\Bar\Compat\Symfony3\Yaml` when running PHP <= 7.0
* `Foo\Bar\Compat\Symfony4\Yaml` when running PHP >= 7.1

as redirected by `class_alias`.
This solves and allows compatibility to other packages / changed interfaces.

*Please note: I know that PHP 7.0 and/or the package is outdated. This is just an example!*

## Problem / Possible solution

The above code relies on the PHP-Version (see `PHP_VERSION_ID < 701000` ). But when Symfony3 is installed on PHP >= 7.1 then the wrong "compat proxy" (here: `Foo\Bar\Compat\Symfony4\Yaml` ) would be used for Symfony3. This leads to lots of warnings in the error-log and worse.

One solution would be to lookup the correct version in the `composer.lock` file. But this is no solution for production because finding the composer.lock, parsing and finding "symfony/yaml" costs too much.

A simpler solution would be to have some global representation of the currently installed versions. For example via constants or in a generated class (after install/update/...) like this:

```php
<?php

class ComposerVersions {
  public static $packages = [
     // ...
    "symfony/yaml" => "v3.7.14",
     // ...
  ];  
}
```

With such thing as part of the "autoloader.php" the compat switch / proxy would behave correctly with a simple lookup:

```php
<?php // src/Foo/Bar/Yaml.php

namespace Foo\Bar;

use Foo\Bar\Compat\Symfony3\Yaml as Symfony3Yaml;
use Foo\Bar\Compat\Symfony4\Yaml as Symfony4Yaml;

switch (true) {
    case version_compare('4.0.0', ComposerVersions::$package['symfony/yaml'], '<'):
        class_alias(Symfony3Yaml::class, Yaml::class);
        break;
    default:
        class_alias(Symfony4Yaml::class, Yaml::class);
}
```

**Sum up: Please allow a simple low-cost access to the currently installed versions**

**Comment by apfelbox** [comment]
This should be covered by https://github.com/composer/composer/pull/8803

**Comment by Seldaek** [comment]
See https://github.com/composer/composer/blob/master/doc/07-runtime.md#knowing-whether-package-x-is-installed-in-version-y for docs on how to use this in composer 2.
