### ISSUE TITLE
Private Github repository update method uses deprecated API

### ISSUE THREAD

**Issue by davidsneighbour** [composer/composer#9005]
My `composer.json` (stripped):

```json
{
  "config": {
    "notify-on-install": false,
    "optimize-autoloader": true,
    "classmap-authoritative": true,
    "sort-packages": true
  },
  "require": {
    ... and so on ...
    "davidsneighbour/booka-gateways": "^1.0"
    ... and so on ...
  },
  "repositories": [
    {
      "type": "vcs",
      "url": "git@github.com:davidsneighbour/booka-gateways.git"
    }
  ]
}
```

Composer version:
```
Composer version 1.10.5 2020-04-10 11:44:22
```

I have a setup with several private repositories. The one in the sample is set to private.

When I run `composer install` on a new system composer asks for an authentication token from Github. I went and created one and the installation went through.

Some hours later this email arrived from Github:

>Hi @davidsneighbour,
>
>On June 21st, 2020 at 15:12 (UTC) your personal access token (###) using Composer/1.9.0 (Linux; 4.14.93-grsec-dedi+; PHP 7.4.3) was used as part of a query parameter to access an endpoint through the GitHub API:
>
>https://api.github.com/
>
>Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation.
>
>Depending on your API usage, we'll be sending you this email reminder on a monthly basis for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
>
>Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.
>
>Thanks,
>The GitHub Team

What would be the proper way to run this scenario or is this a bug that needs fixing/updating?

**Comment by stof** [comment]
Well, you say you use Composer 1.10.5.
But the email from github talks about Composer 1.9.0 (which is indeed before the composer bugfix for that deprecation, which came out in 1.9.3). So make sure that the system on which you have the issue actually uses the latest composer version.

**Comment by davidsneighbour** [comment]
Oh, ok. Thank you :) I updated on the system and it's working now.
