### ISSUE TITLE
Unable to download composer installer

### ISSUE THREAD

**Issue by tcahall** [composer/composer#9006]
I am attempting to install Composer as part of a Snipe-IT install.  I am getting a timeout on the download of the installer.  I have pulled out the https call and put it into curl with the same result.  Command  curl https://getcomposer.org/installer/composer-setup.php
I am getting a page not found.

Output of `composer diagnose`:
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="robots" content="noindex,nofollow" />
        <style>                body { background-color: #fff; color: #222; font: 16px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; margin: 0; }
                .container { margin: 30px; max-width: 600px; }
                h1 { color: #dc3545; font-size: 24px; }</style>
    </head>
    <body>
                        <div class="container">
                    <h1>Sorry, the page you are looking for could not be found.</h1>
                </div>
    </body>

Below is the extract from the snipe-it installer:

```
install_composer () {
  # https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
  EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
  run_as_app_user php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  ACTUAL_SIGNATURE="$(run_as_app_user php -r "echo hash_file('SHA384', 'composer-setup.php');")"

  if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
  then
      >&2 echo 'ERROR: Invalid composer installer signature'
      run_as_app_user rm composer-setup.php
      exit 1
  fi

  run_as_app_user php composer-setup.php
  run_as_app_user rm composer-setup.php

  mv "$(eval echo ~$APP_USER)"/composer.phar /usr/local/bin/composer
}
```

**Comment by Seldaek** [comment]
`https://getcomposer.org/installer/composer-setup.php` is not a valid URL, I don't know where you pulled this from.. `https://getcomposer.org/installer` is the installer URL, and it is saved as composer-setup.php in the script.
