### ISSUE TITLE
composer remote using git-credentials (non-https) - should use https instead

### ISSUE THREAD

**Issue by staabm** [composer/composer#9013]
after checking out a project and running `composer update` via packagist.com my dependent source packages have 2 remotes.
A `origin` remote using regular git (non-https) and a https based remote named `composer`:

```
$ git remote -v
composer        https://github.com/my-org/php-rocket.git (fetch)
composer        https://github.com/my-org/php-rocket.git (push)
origin  git@github.com:my-org/php-rocket.git (fetch)
origin  git@github.com:my-org/php-rocket.git (push)
```

such a repo "origin" cannot be used with the offical [github desktop](https://desktop.github.com/) tool, as my authentication only works on https.

I guess this happens here:
https://github.com/composer/composer/blob/a5e608fb73f8eeff8f3acc6fb938c15e5310efcb/src/Composer/Downloader/GitDownloader.php#L91-L93

is there anything I can do, so I can have one of...
- the new "composer" remote would be the default?
- the package beeing checked out would use a https urls for the origin remote?

ATM my workaround is one of
- directly push/fetch from the "composer" remote, which I have to mention in every command since its not the default
- changing the default-remotes url to HTTPS manually after each checkout triggered by `composer update`

my env

```
$ php -v
PHP 7.4.5 (cli) (built: Apr 14 2020 16:17:19) ( NTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

$ composer -V
Composer version 1.10.7 2020-06-03 10:03:56
```

**Comment by stof** [comment]
See https://getcomposer.org/doc/06-config.md#github-protocols

**Comment by staabm** [comment]
thx for the hint. I will try working with `composer config --global github-protocols https`.

I somehow remember chatting with Nils or Jordi on the packagist.com support chat about this topic, and IIRC we came to the conclusion that this setting will not work alone, because of a combination with packagist.com

I can't remember the details though.

**Comment by Seldaek** [comment]
Seems to me like the easiest would be to configure public key auth so that you can use git@github.com URLs. We can't really fix this for you without breaking it for others I'm afraid.
