### ISSUE TITLE
seft-update creat an SSSL issue

### ISSUE THREAD

**Issue by golsmea** [composer/composer#9015]
Hi hope you can help me.
I'm using php 7.4.0 
on a windows 10
thx for helping

When I run this command: 
php composer.phar seff-update 

I get the following output:
 [Composer\Downloader\TransportException]
  The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Erro
  r messages:
  error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
  Failed to enable crypto
  failed to open stream: operation failed

**Comment by Seldaek** [comment]
Looks like you have an invalid CA bundle, but who knows as you did not post the full output of the command with `-vvv` as we request..
