### ISSUE TITLE
Ability to check if package exists composer cache

### ISSUE THREAD

**Issue by drpayyne** [composer/composer#9017]
Hello, I was just wondering if there was a way to check if a package:version is present in composer's cache. There isn't really a major use case for this, apart from debugging, which is when I needed this feature.

**Comment by Seldaek** [comment]
No way to do this no.. Debugging what exactly? Generally speaking the cache state should be irrelevant.

**Comment by drpayyne** [comment]
Thanks, @Seldaek. I personally came across this when I was trying to sync my composer cache into a docker container and running composer install or update inside it. Sometimes, when I expect a package to be fetched from cache, it starts to download it all over again inside the container. So I was curious if there was a way to actually check if a package:version exists in my local composer cache and in docker too. Not really a major use case, as I mentioned. But just curiosity during development.

**Comment by Seldaek** [comment]
I see, the best is to run an install without vendor dir then it will download everything it needs and you should have a fully primed cache at that point. There's no way to look deeper into the cache than that.
