### ISSUE TITLE
Composer does not generate .htaccess on install

### ISSUE THREAD

**Issue by stefanseeger** [composer/composer#9019]
**My `composer.json`:**

```json
{
    "name": "api",
    "type": "project",
    "description": "",
    "require": {
        "firebase/php-jwt": "^5.2"
    },
    "authors": [
        {
            "name": "Stefan Seeger",
            "email": "email@mail.de"
        }
    ],
    "config": {
        "htaccess-protect": true
    }
}

```

**Output of `composer diagnose`:**

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.8
PHP version: 7.4.7
PHP binary path: C:\Program Files\php\php.exe
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**When I run this command:**

```
composer install
```

**I get the following output:**

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
```

**And I expected this to happen:**
Normally, per default the `.htaccess` should be generated. But even if i enfoce it with `"htaccess-protect": true` it is not generated.
Could some one please explain what is going wrong

Thank you and best regards,
Stefan

**Comment by alcohol** [comment]
How did you check if the file exists or does not exist?

I am asking because I see that you are on Windows, and that platform hides dotfiles by default in applications such as "Explorer".

**Comment by Seldaek** [comment]
The htaccess-protect stuff is about the composer home dir, I don't know where you checked, but it creates it in home, cache-dir and data-dir, which paths you can see via:

composer config cache-dir
composer config data-dir
composer config home

**Comment by stefanseeger** [comment]
Hello,
thank you for your answers. Maybe I understood it wrong then.
I expected to have a ``.htaccess`` inside my project folder which is preventing access to `composer.json`, `composer.lock` and the `vendor` folder for security reasons. Is there anything like this?

Best regards,
Stefan

**Comment by Seldaek** [comment]
Nope there is nothing like that. You can easily create that htaccess
yourself though.
