### ISSUE TITLE
Make --2 download 2.0.0alpha2

### ISSUE THREAD

**Issue by GrahamCampbell** [composer/composer#9022]
Currently the self-update command `--1` downloads `1.10.8` but `--2` downloads `2.0.x-dev`. I'd expect it to download `2.0.0alpha2`. This is related to https://github.com/shivammathur/setup-php/issues/238.

**Comment by Seldaek** [comment]
Hmm, fix didn't seem to quite do the trick

**Comment by Seldaek** [comment]
Ok fixed now

**Comment by GrahamCampbell** [comment]
👍
