### ISSUE TITLE
Composer runs out of memory

### ISSUE THREAD

**Issue by rootpric** [composer/composer#9028]
It happened after a kernel update in WHM on a Centos linux server with Cpanel everything shows that I have 2 Gig of memory. I tried everything in the closed out of memory issue "Composer runs out of memory on latest version #8981
 Closed	ElvenSpellmaker opened this issue 15 days ago · 19 comments" but it did not help. I do not understand why this issue is closed when there is no solution to it yet? So I opened this one.

My `composer.json`:

```json
...replace me...
```

Output of `composer diagnose`:

```
...replace me...
```

When I run this command:

```
composer update
```

I get the following output:

```
Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///opt/cpanel/composer/bin/composer/src/Composer/DependencyResolver/RuleSetGenerator.php on line 129

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.[oiya@ip-2-18-16-9 test]$ composer show -p php-64bit
name     : php-64bit
descrip. : The PHP interpreter, 64bit
keywords :
versions : * 7.4.7
type     : library
source   : []
dist     : []
path     :
names    : php-64bit
```

And I expected this to happen:

Drupal updated successfully

**Comment by Seldaek** [comment]
The issue is closed because we can not do anything about it. We fixed tons of memory usage issues in v2 which you can try with `composer self-update --preview` (see changelog https://github.com/composer/composer/releases/tag/2.0.0-alpha2)

v1 can not be fixed. If you have more dependencies than your memory can handle, not much we can do there.
