### ISSUE TITLE
Packagist DNS Not Resolving

### ISSUE THREAD

**Issue by GrahamCampbell** [composer/composer#9031]
Seeing this all over various GitHub Actions runs across lots of different projects over the last 2 hours:

```
failed to open stream: php_network_getaddresses: getaddrinfo failed: Name does not resolve 
```

**Comment by Seldaek** [comment]
I take it it fixed itself? I'm not sure what to say or do about this, we use Route 53 for DNS which should be fairly reliable.. Maybe a GH Actions glitch, or maybe AWS, or maybe something else in between.. but seems fine now at least for me.
