### ISSUE TITLE
Issue While Composer Install related to Network

### ISSUE THREAD

**Issue by msmubbo99** [composer/composer#9032]
Getting This error while Composer Install : 
![image](https://user-images.githubusercontent.com/62053620/86276539-adc3ee00-bbf2-11ea-82f5-2b31c02389bf.png)

And this also : 
![image](https://user-images.githubusercontent.com/62053620/86276690-f54a7a00-bbf2-11ea-8c90-23bb2c532a8e.png)

**Comment by Seldaek** [comment]
I think there was a glitch in our infra yesterday, should be fixed now, if not let me know what IP repo.packagist.org resolves to for you (you can run `ping repo.packagist.org` for example to see the IP).

Also you can try using v2 pre-releases which are more network efficient: https://github.com/composer/composer/releases/tag/2.0.0-alpha2

**Comment by msmubbo99** [comment]
Yes it is resolved

**Comment by s709t** [comment]
not solved yet, i'm facing the same issue with the host
