### ISSUE TITLE
Seeing inconsistent behavior with minor-only flag

### ISSUE THREAD

**Issue by shaysmith** [composer/composer#9033]
When I run this command:

```
composer info --latest
```

The latest versions column includes version information that reflects major version updates:

```
drupal/core                     8.6.15      9.0.1
```

If I include the minor-only flag:

```
composer info --latest --minor-only
```

The version information correctly displays version information in the same minor version:

```
drupal/core                     8.6.15      8.9.1
```

However, if I specify a dependency:

```
composer info drupal/core --latest
```

I get the following version information (output truncated to the version line):

```
versions : * 8.6.15
latest   : 9.0.1
```

If I add the minor-only flag:

```
composer info drupal/core --latest
```

The latest version does not accurately display the minor version as expected:

```
versions : * 8.6.15
latest   : 9.0.1
```

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/pull/9050
