### ISSUE TITLE
Improvement suggestion for fork with false composer name

### ISSUE THREAD

**Issue by alexander-schranz** [composer/composer#9036]
My `composer.json`:

```json
{
    "name": "my/test",
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/alexander-schranz/my-fork-repo"
        }
    ],
    "require": {
        "alexander-schranz/renamed": "dev-my-branch"
    }
}
```

Fork Repository [master](https://github.com/alexander-schranz/master/blob/my-branch/composer.json):

```json
{
    "name": "alexander-schranz/old-name"
}
```

Fork Repository [my-branch](https://github.com/alexander-schranz/my-fork-repo/blob/my-branch/composer.json)

```json
{
    "name": "alexander-schranz/renamed"
}
```

Output of `composer diagnose`:

```bash
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.8
PHP version: 7.4.7
PHP binary path: /usr/local/Cellar/php/7.4.7/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

When I run this command:

```bash
composer update
```

I get the following output:

```bash
alexanderschranz/test not found as dev-my-branch found [1.x, ...]
```

And I expected this to happen:

> alexanderschranz/test not found as dev-my-branch found [1.x, ...]
> 
> There was also an unused fork:
> Unused repository "https://github.com/alexander-schranz/my-fork-repo" with packages name "alexanderschranz/old-name". Check the package name in the composer.json of the default branch.

It took my some time to find out why my fork is not used until I did found that the master branch of the fork did still point to an old composer package name. It would be great to have a error output maybe that a repository was added which is not required by a package, as I think it would be not easy to get the package name from the required branch and install correctly.

**Comment by Seldaek** [comment]
Definitely sounds like a good improvement in your use case, but also sounds fairly complex to achieve for such an edge case situation.

**Comment by Seldaek** [comment]
I guess doing the update with `-v` would have helped as it shows packages that are loaded from the VCS repo which I guess would have hinted you at the problem.

Anyway closing as I don't see a reasonable way to do this.
