### ISSUE TITLE
[RFC] Built in warnings or banning for packages with known vulnerabilities

### ISSUE THREAD

**Issue by GrahamCampbell** [composer/composer#9043]
https://github.com/Roave/SecurityAdvisories exists, but possibly this is something that could be a core feature of composer? Is it possible for packagist to fetch security advisories from github too? I'm not sure if they're in a consumable format to identify version ranges, always.

**Comment by GrahamCampbell** [comment]
Can't composer just consume the APIs you added to packagist.org?

**Comment by stof** [comment]
we could imagine a `composer audit` command using the packagist.org API (suggested command name is based on `npm audit`)

**Comment by stof** [comment]
btw, this command could be first built as a plugin to experiment with it.

**Comment by Seldaek** [comment]
Duplicate of https://github.com/composer/composer/issues/7323
