### ISSUE TITLE
Packagist suck processing package

### ISSUE THREAD

**Issue by GrahamCampbell** [composer/composer#9044]
https://packagist.org/packages/graham-campbell/phpspec-skip-example-extension. Could this be because the repo has no master branch? The "default" branch is named 5.0. NB I'm publishing this fork because the original package authors have abandoned their repo for over a year and aren't responding.

<img width="895" alt="image" src="https://user-images.githubusercontent.com/2829600/87200144-daaf8980-c2f3-11ea-86d3-7d2866271698.png">

**Comment by GrahamCampbell** [comment]
This seems to be an issue affecting all new packages, actually. All these are in a stuck state:

<img width="397" alt="image" src="https://user-images.githubusercontent.com/2829600/87204854-dd16e100-c2fd-11ea-9b93-3f35fb0d4a85.png">

**Comment by Seldaek** [comment]
This started with an extra high load of updates, and then went on to workers being down during the night which did not help.. Things are catching up slowly now. Should hopefully be back on track soon.

**Comment by GrahamCampbell** [comment]
🍻
