### ISSUE TITLE
Unexpected change of composer home directory on WSL2

### ISSUE THREAD

**Issue by marveloo** [composer/composer#9045]
Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.8
PHP version: 7.4.3
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

This is the Composer home directory in Ubuntu 20.04 LTS Bash (running on WSL2):

```
$ ~/.local/bin/composer global config home
Changed current directory to /home/marveloo/.config/composer
/home/marveloo/.config/composer
```

However once I run the composer from the Command Prompt or Windows PowerShell the Composer home directory unexpectedly changes:

```
PS> wsl.exe ~/.local/bin/composer global config home
Changed current directory to /home/marveloo/.composer
/home/marveloo/.composer
```

The change is permanent, i.e. when I get back to Bash the change is still present there unless I delete `/home/marveloo/.composer` which causes composer home directory to get back to its initial state.

**Comment by johnstevenson** [comment]
It is not really surprising that this won't work. To explain:

Composer uses environment variables to determine the composer home directory location: `COMPOSER_HOME` on all platforms, `APPDATA` on Windows, or `HOME` or from `XDG_???` on Unixy.

The problem with running something in wsl from a Windows native shell is that the environment is not the same as that in the `<distro>` bash shell. Run `env` from bash and `wsl.exe env` from cmd.exe to see the difference.

What causes this particular scenario is that the `XDG_???` variable is missing from the Windows environment, so Composer assumes that your distro does not use the XDG Base Directory Specifications (which it does, if invoked from the `<distro>` bash shell).

You can trick this command to work by setting certain environment variables in Windows, but there is no guarantee that all of composer will work.

**Comment by marveloo** [comment]
I kind of expected that it was to do with `XGD_` variables. However, as I already mentioned, this `COMPOSER_HOME` change seems to be permanent, i.e. when I get back to Bash, my `COMPOSER_HOME` directory does not get back to its previous location, which makes me think, that Composer relies on `XDG_` variables only if `~/.composer` direcory is not present. So I am thinking maybe composer could also additionally check for existence of `~/.config/composer` if `~/.composer` is not present before moving on to `XDG_` check. Could it be a solution?

**Comment by johnstevenson** [comment]
It doesn't go back to the xdg location because it already exists at the normal (non-xdg) location.

If you need to run stuff across OS boundaries, then `WSLENV` is your friend.

**Comment by marveloo** [comment]
> It doesn't go back to the xdg location because it already exists at the normal (non-xdg) location.

This is true, but if it doesn't exist then composer checks `XDG_` variables for location. Whereas my suggestion for composer is to do one additional check for presence of Composer XDG directory in its default location (which is `~/.config/composer`) if all other checks fail.

From XDG Base Directory Specification:

> If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

This is it!

> If you need to run stuff across OS boundaries, then `WSLENV` is your friend.

I just hope for something more stable and longterm which seems to be only possible on the Composer's side. In the meantime the best fix on my part it seems is to do nothing because the `COMPOSER_HOME` changes only once ... hopefully :smile:

**Comment by johnstevenson** [comment]
> I just hope for something more stable and longterm which seems to be only possible on the Composer's side.

As already mentioned, the stable and long term solution is to correctly set up your OS using `WSLENV` to set the environment variables you need when running wsl from a Windows native shell, as per the wsl documentation: https://docs.microsoft.com/en-us/windows/wsl/interop

Otherwise you are asking that some sensible logic (that has been working for over 4 years and which itself took several years to materialize https://github.com/composer/composer/pull/1407) be changed because of your (inadvertent) misconfiguration.

**Comment by marveloo** [comment]
I was not suggesting any breaking backward incompatible changes. Let me explain in more detail:

First, this is the algorithm used by Composer now:

- if COMPOSER_HOME is set, use it
- elseif it's Windows and APPDATA is set, use `%APPDATA%/Composer`
- elseif it's Windows, throw error
- elseif `~/.composer` exists, use it
- elseif XDG_CONFIG_HOME is set, use `$XDG_CONFIG_HOME/composer`
- elseif any of XDG_* variables is set, use `~/.config/composer`
- else use `~/.composer`

And this is the full algorithm proposed in my previous comment:

- if COMPOSER_HOME is set, use it
- elseif it's Windows and APPDATA is set, use `%APPDATA%/Composer`
- elseif it's Windows, throw error
- elseif `~/.composer` exists, use it
- elseif XDG_CONFIG_HOME is set, use `$XDG_CONFIG_HOME/composer`
- elseif (any of XDG_* variables is set) or (`~/.config/composer` exists), use `~/.config/composer`   :point_left:
- else use `~/.composer`

Full compatibility with existing Composer installations on users' machines.

<hr>

On the other hand, the specification says this:

> If `$XDG_CONFIG_DIRS` is either not set or empty, a value equal to `/etc/xdg` should be used.

So I thought perhaps this could be the big clue in XDG detection:

- if COMPOSER_HOME is set, use it
- elseif it's Windows and APPDATA is set, use `%APPDATA%/Composer`
- elseif it's Windows, throw error
- elseif `~/.composer` exists, use it
- elseif XDG_CONFIG_HOME is set, use `$XDG_CONFIG_HOME/composer`
- elseif (any of XDG_* variables is set) or (`/etc/xdg` exists), use `~/.config/composer`   :point_left:
- else use `~/.composer`

Full compatibility with existing installations as well.

**Comment by Seldaek** [comment]
Thanks for the good overview, I believe https://github.com/composer/composer/commit/10590dc519fe9b12c8333452c75904155214ca3e addresses it correctly, it's targetted for 2.0  as it's a minor BC break, but hopefully should not affect many people.
