### ISSUE TITLE
Implement http auth digest

### ISSUE THREAD

**Issue by thomas-kl1** [composer/composer#9052]
Today the http auth digest authentication is not supported and the http basic is applied by default.

I'm ready to help and implement this case. However I want to be sure digest auth is not available because of some reasons or if there is a workaround/open to discussion.

**Comment by Seldaek** [comment]
Mostly not there because nobody has needed it I believe.

**Comment by Seldaek** [comment]
master branch / 2.0-dev uses curl by default if available, but it still has to work with file_get_contents too so if it's not possible to make it work with both I'd maybe rather not have it given it seems to be a fringe feature anyway.

**Comment by Seldaek** [comment]
What's your use case/requirement here?

**Comment by thomas-kl1** [comment]
I was playing with satis for private repositories and I was trying to achieve HTTP Auth Digest in order to manage auth by multiple domains/realm in pure apache.
Also it seems Digest is a bit more secure than Basic auth

**Comment by Seldaek** [comment]
Closing as I don't think we will ever do anything here.
