### ISSUE TITLE
Self-update to preview not working

### ISSUE THREAD

**Issue by alexander-schranz** [composer/composer#9060]
Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.9
PHP version: 7.4.5 - Package overridden via config.platform (actual: 7.4.8)
PHP binary path: /usr/local/Cellar/php/7.4.8/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

When I run this command:

```
composer self-update --preview
```

I get the following output:

```
.You are already using composer version 1.10.9 (preview channel).
```

And I expected this to happen:

Installation of composer 2 / latest dev commit.

This seems also be the case when using 1.10.8 so it seems have nothing todo with the release. It just seems like 1.10.9 is now accidentally the new preview channel which should just be the stable channel.

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/getcomposer.org/commit/ed106feacef086c1fe511f535ad3988d383493d9

**Comment by stof** [comment]
@Seldaek I think the same issue might happen in the future again, including for the `stable` channel, because the script considers the "last" version by date, not by semver rules of higher version number.
