### ISSUE TITLE
cant install composer

### ISSUE THREAD

**Issue by riznisa** [composer/composer#9075]
The "https://getcomposer.org/download/1.10.9/composer.phar" file could not be downloaded: SSL: An existing connection was forcibly closed by the remote host.

failed to open stream: HTTP request failed! 
The "https://getcomposer.org/download/1.10.9/composer.phar" file could not be downloaded: SSL: An existing connection was forcibly closed by the remote host.

failed to open stream: HTTP request failed! 
Some settings on your machine may cause stability issues with Composer.
If you encounter issues, try to change the following:

The Windows OneDrive folder is not supported on PHP versions below 7.2.23 and 7.3.10.
Upgrade your PHP (7.3.2) to use this location with Composer.

**Comment by johnstevenson** [comment]
If you used https://getcomposer.org/Composer-Setup.exe then please create a new issue with a log file here:
https://github.com/composer/windows-setup/issues/new (and supply a log file)

If not, please try it and file an issue it if fails.
