### ISSUE TITLE
Feature: Require an exact version, including pre-releases

### ISSUE THREAD

**Issue by kusabi** [composer/composer#9081]
Hi

Apologies if this ticket is the wrong format as I could only find guidelines on adding bugs.

I recently had a small amount of trouble. I needed to require a specific version down to the patch `3.8.1`.
The library in questions is in active development and utilising pre-release tags `3.8.1-rc6`.

The original composer had `"some/library": "~3.8.1", but as soon as a `3.8.2` was tagged it pulled that in.

The project was propriety work so I cannot post code, but in essence, this library contained migration data and was tagged to the project release number. So with 5+ releases being worked on in advance, it's not uncommon for this library to be worked on multiple versions ahead, and when working on release `3.8.1` you need `3.8.1` from the library, despite there being `3.8.2` and `3.8.3`.

I changed the composer file to require `3.8.1` but that did not pick up any pre-release tags, and since there is no `3.8.1` yet, the update failed to find anything.

After I did some digging, I found I could get away with either `>=3.8.1-dev <=3.8.1` or `3.8.1.*@dev`.

So my question is; is there any chance of getting a nicer way of achieving this? I am happy to attempt the PR if it something to be considered, but I wouldn't want to change any default behaviours so the only thing I can think of is to add a new character like ^ or ~.

Any thoughts?

I can live with my current solution if it's deemed pointless, as I understand it is a tiny nitpick of a request, but to me it makes sense to have a way to require a specific version, or any pre-release of that version.

Also, perhaps I have just over complicated something, when there already exists a better solution? If so I would be much obliged to here about it :)

**Comment by stof** [comment]
`3.8.1.*` is already doing exactly that (the `@dev` impacts the stability requirement if that constraint appears in the root package, but it has no effect on the bounds of this constraint.

**Comment by dereuromark** [comment]
The `.*` isnt necessary, though, is it? Even just `3.8.1` does this.

**Comment by kusabi** [comment]
> `3.8.1.*` is already doing exactly that (the `@dev` impacts the stability requirement if that constraint appears in the root package, but it has no effect on the bounds of this constraint.

Thank you, I will test this out later but if this works it's exactly what I am looking for.

**Comment by kusabi** [comment]
> The `.*` isnt necessary, though, is it? Even just `3.8.1` does this.

Not that I can see, it looks only for the exact tag and ignores all pre-releases.

@dereuromark example above looks like a perfect workaround though, using a fourth wildcard to signify any pre-release of this version is is required. I will test this out later today but if it works it's exactly what I was looking for.

**Comment by kusabi** [comment]
Hi, this method has worked perfectly. I have confirmed that the pattern `3.8.0.*` will match `3.8.0-rc10` and `3.8.0`.

Thank you for the quick response. I will close this issue.

**Comment by dereuromark** [comment]
Maybe a useful note to the docs?

**Comment by stof** [comment]
`3.8.1` is a exact-match constraint, not a range constraint. It is definitely *not* equivalent to `3.8.1.*` (`3.8.1.x` is a support alternate notation though)
