### ISSUE TITLE
»composer update« of packages will update the package without checking for package conflicts

### ISSUE THREAD

**Issue by pixelbrackets** [composer/composer#9082]
I installed the TYPO3 project »typo3/cms-base-distribution« using composer and added the package »roave/security-advisories«.

The base distribution has »typo3/cms-core« as dependency. 15 days ago the latest version was 10.4.5.

Today a new version 10.4.6 for »typo3/cms-core« was released. Also a new version of »roave/security-advisories« was released, having a conflict with »typo3/cms-core« version 10.4.5 (see https://github.com/Roave/SecurityAdvisories/blob/master/composer.json#L216).

When I run this command:
`composer update --dry-run roave/security-advisories`
I expect Composer to throw a warning, that a conflict with the currently installed version of TYPO3 exists.

Instead the package is updated just fine. When I open the `vendor/composer/installed.json` file, this conflict is listed in »roave/security-advisories«.

I made an example repository to reproduce this issue:
https://github.com/pixelbrackets/SecurityAdvisoriesTest/

The issue was first reported in https://github.com/Roave/SecurityAdvisories/issues/66 → in there @Ocramius and I were able to confirm that this behavior exists in Composer 1, but not in Composer 2.

My `composer.json`: https://github.com/pixelbrackets/SecurityAdvisoriesTest/blob/master/composer.json

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.9
PHP version: 7.2 - Package overridden via config.platform (actual: 7.2.32)
PHP binary path: /usr/bin/php7.2
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Comment by Ocramius** [comment]
To be clear: `composer/composer:^2` is correct, while `composer/composer:^1` misbehaves here.

**Comment by stof** [comment]
Composer 1.x takes the existing installed packages into account as input of the solver. This is a known issue of Composer 1, which is one of the things solved in Composer 2.
I'm quite sure that if you run composer a second time (with the updated metadata for the installed version of `roave/security-advisories`) will report the issue.

**Comment by Seldaek** [comment]
Yes, this is known issue and a won't-fix for composer 1. Composer 2 solves it already as you saw.
