### ISSUE TITLE
trigger script events of a plugin

### ISSUE THREAD

**Issue by staabm** [composer/composer#9083]
I am using https://github.com/cweagans/composer-patches 1.x which hooks into the `composer install` process and modifies packages/applies patches to packages at `composer install/update` time.

see the plugin events it is listening for:
https://github.com/cweagans/composer-patches/blob/2e6f72a2ad8d59cd7e2b729f218bf42adb14f590/src/Patches.php#L71-L82

I would love to use this plugin, but since we are working with a `--no-scripts` flag in the build/deployment pipeline the plugins mechanics are not triggered.
I cannot just drop the `--no-scripts` trigger because other plugins which we also use would then beeing triggered which doesn't work for us either.

is there some way, I could trigger just this plugin after my regular `composer install ... --no-scripts` finished?
or maybe there is some easy way I could adjust the plugin and invoke it e.g. via `composer run-script ...`?

I am all ears for ideas on how I could tackle this problem.
thank you very much for any input.

**Comment by stof** [comment]
Well, if you run with `--no-scripts`, that disables all plugins. And that's by design.

Allowing to use the plugin features through a different way is a feature that must be requested to the plugin (they must implement such invocation mode)

**Comment by staabm** [comment]
> Well, if you run with `--no-scripts`, that disables all plugins. And that's by design.

yeah I am aware of that. I actually use this feature and like/need it.

> Allowing to use the plugin features through a different way is a feature that must be requested to the plugin (they must implement such invocation mode)

so do you say there is some kind of composer api which allows me to e.g. register a custom event/script which I could utilize to invokes the 3 phases of the plugin, by e.g. `composer run-script` or similar?

**Comment by stof** [comment]
plugins are already allowed to register custom commands

**Comment by clxmstaab** [comment]
> plugins are already allowed to register custom commands

thx for the hin. I guess I found the related docs: https://getcomposer.org/doc/articles/plugins.md#command-provider

**Comment by clxmstaab** [comment]
oh my, it seems the plugin in question does some crazy magic and requires a lot of in-detail context, so its pretty hard to trigger it outside the regular flow, see e.g. https://github.com/cweagans/composer-patches/blob/2e6f72a2ad8d59cd7e2b729f218bf42adb14f590/src/Patches.php#L176

it requires a lot of code and copying of composers internals to mimic composer in a way that the plugins expectations will be met.

maybe someone has an idea on how I could achieve the same goal without fiddling with so much composer internals?

**Comment by Seldaek** [comment]
I don't see a reasonable way to do this easily. Patches typically have to be applied only once, so you'd have to keep track of which packages got installed/updated, so you can replay that by calling the plugin and telling it to apply patches to packages X and Y. I mean it might be possible to keep the state somewhere, but it just sounds like a lot of work and something that'd be better done/coordinated with the plugin authors, rather than done from the outside.

I do wonder why you disallow plugins/scripts in general during build though. That sounds like a case of overcomplicating things which leads to more unique weird issues..

**Comment by staabm** [comment]
> I do wonder why you disallow plugins/scripts in general during build though. That sounds like a case of overcomplicating things which leads to more unique weird issues.. 

I disallow scripts, because I dont want the post-install-cmd of the composer.json beeing triggered

**Comment by Seldaek** [comment]
Then if it's only about suppressing your own scripts maybe run `composer config scripts.post-install-cmd --unset` before `composer install` in your CI?

**Comment by staabm** [comment]
Thats reads great. Will try tomorrow and report back :-).

Thx!

**Comment by staabm** [comment]
this seem to work for me. thank you so much for the suggestion.
