### ISSUE TITLE
Composer's autoload.php doesn't load any library

### ISSUE THREAD

**Issue by nspeedzy** [composer/composer#9086]
## Description:
I am using composer to install the `mongodb/mongodb` library. The install was successful but when I include the library using the line:
```php
require 'vendor/autoload.php';
```
It doesn't work. Composer's `autoload.php` doesn't load the composer goodies into my `index.php` file. Is there any way to fix this? If there is any additional info I need to give, please inform me

## Environment info
Composer version: `1.10.6`
OS: `Windows 10 x64`
PHP version: `7.4.8`

**Comment by stof** [comment]
what doe you mean by `it doesn't work` ? what happens exactly ?

**Comment by nspeedzy** [comment]
@stof Well, composer doesn't load the classes and namespaces and stuff

**Comment by nspeedzy** [comment]
Oh and by the way, here is my `composer.json`:
```json
{
    "name": "nspeedzy/project_php",
    "description": "",
    "authors": [{
        "name": "nspeedzy",
        "email": "ninjasurya71@gmail.com"
    }],
    "require": {
        "mongodb/mongodb": "^1.6"
    }
}

```

**Comment by Seldaek** [comment]
Do you actually get an issue when you execute index.php, or is it only an issue in VSCode?

**Comment by nspeedzy** [comment]
@Seldaek It's not an issue with vscode. I have a feeling it is an issue with the `autoload.php` y know. This is the same case with all the other libraries too

**Comment by stof** [comment]
@nspeedzy but do you actually get an error when **running** the code ? Your screenshot proves that VS Code cannot find the class, but VS Code does not rely on the PHP autoloading AFAIK.

**Comment by nspeedzy** [comment]
@stof Hm, lemme see and tell u in a few minutes

**Comment by nspeedzy** [comment]
Hello guys! So, Actually, it is working now. I think i didn't use the require statement properly! Thanks for the help anyways! I will close this issue now.
