### ISSUE TITLE
Custom repositories ignored in GitHub Actions?

### ISSUE THREAD

**Issue by ondrejmirtes** [composer/composer#9087]
I'd like to use my own fork for nette/utils. Locally it installs the branch from my repository just fine but in GitHub Actions it fails, it looks like it doesn't look at the `repositories` section at all: https://github.com/phpstan/phpstan-src/runs/924807549?check_suite_focus=true

```
 Problem 1
    - Root composer.json requires nette/utils dev-php-8 as 3.1.99, found nette/utils[v2.2.1, ..., v2.4.4, v3.0.0, ..., v3.1.2] but it does not match the constraint.
  Problem 2
    - Root composer.json requires nette/di dev-master#4e1e2d1747d61b5da5d84ba77a28b726b6d7744c -> satisfiable by nette/di[dev-master].
    - nette/di dev-master requires nette/utils ^3.1 -> found nette/utils[v3.1.0, v3.1.1, v3.1.2] but it conflicts with your root composer.json require (dev-php-8 as 3.1.99).
  Problem 3
    - nette/finder[v2.5.2, ..., v2.5.x-dev] require nette/utils ^2.4 || ^3.0 -> found nette/utils[v2.4.0, ..., v2.4.4, v3.0.0, ..., v3.1.2] but it conflicts with your root composer.json require (dev-php-8 as 3.1.99).
    - nette/finder[v2.5.0, ..., v2.5.1] require nette/utils ^2.4 || ~3.0.0 -> found nette/utils[v2.4.0, ..., v2.4.4, v3.0.0, v3.0.1, v3.0.2, v3.0.3] but it conflicts with your root composer.json require (dev-php-8 as 3.1.99).
    - Root composer.json requires nette/finder ^2.5 -> satisfiable by nette/finder[v2.5.0, v2.5.1, v2.5.2, v2.5.x-dev].
```

My `composer.json` (the full one): https://github.com/phpstan/phpstan-src/blob/012ea824cd96693d3fe804e308a5c2328f723af1/composer.json

```json
{
    "require": {
        "nette/utils": "dev-php-8 as 3.1.99"
    },
    "repositories": [
        {
                "type": "vcs",
                "url": "git@github.com:ondrejmirtes/utils.git"
        }
    ]
}
```

I also tried `https://github.com/ondrejmirtes/utils.git` instead of `git@github...` without any change.

It doesn't matter if I'm using Composer v1 stable or Composer v2 snapshot.

My theory is that it has to do something with shallow cloning in GitHub Actions but I don't see a reason why it'd affect this logic.

**Comment by ondrejmirtes** [comment]
What's funny that randomly some job succeeds, but it's very rare: https://github.com/phpstan/phpstan-src/runs/924808143?check_suite_focus=true

**Comment by ondrejmirtes** [comment]
It always works in Travis CI.

Two theories I have:

1) There's some kind of aggresive timeout in GitHub Actions and if the clone fails, Composer silently uses the authoritative repo from Packagist. That would explain the randomness.
2) GitHub Actions apply the same shallow depth for `git clone` as they do for `actions/checkout`.

Neither of those theories have any support in git-config manual... https://git-scm.com/docs/git-config

**Comment by stof** [comment]
@ondrejmirtes could you update your workflow to run composer in debug verbosity (`-vvv`) ? this would display some details about the loading of repository metadata.

**Comment by ondrejmirtes** [comment]
So I ran it with `-vvv` both locally and in GitHub Actions:

Locally:

```
Reading composer.json of nette/utils (php-8)
Downloading https://api.github.com/repos/ondrejmirtes/utils/contents/composer.json?ref=e55a8dab6c7802e46c667a8d841e7aa0c4b001af
[200] https://api.github.com/repos/ondrejmirtes/utils/contents/composer.json?ref=e55a8dab6c7802e46c667a8d841e7aa0c4b001af
Downloading https://api.github.com/repos/ondrejmirtes/utils/commits/e55a8dab6c7802e46c667a8d841e7aa0c4b001af
[200] https://api.github.com/repos/ondrejmirtes/utils/commits/e55a8dab6c7802e46c667a8d841e7aa0c4b001af
Writing /Users/ondrej/.composer/cache/repo/github.com/ondrejmirtes/utils/e55a8dab6c7802e46c667a8d841e7aa0c4b001af into cache
Importing branch php-8 (dev-php-8)
```

GitHub Actions:

```
2020-07-30T11:01:43.6081401Z Reading composer.json of nette/utils (php-8)
2020-07-30T11:01:43.6081963Z Downloading https://api.github.com/repos/ondrejmirtes/utils/contents/composer.json?ref=e55a8dab6c7802e46c667a8d841e7aa0c4b001af
2020-07-30T11:01:43.6188126Z [403] https://api.github.com/repos/ondrejmirtes/utils/contents/composer.json?ref=e55a8dab6c7802e46c667a8d841e7aa0c4b001af
2020-07-30T11:01:43.6188318Z Executing command (CWD): git config github.accesstoken
2020-07-30T11:01:43.6224521Z Skipped branch php-8, no composer file was found (401 HTTP status code)
```

So I obviously need to set a GitHub token in Composer. Looks like it works!

Maybe we should consider that in scenarios like this, custom repositories shouldn't be skipped silently because it leads to unexpected results...

**Comment by Seldaek** [comment]
You can add a step like this:

```
      - name: "Setup Composer auth"
        run: "composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}"
```

The question is whether we really need this.. it'd be good if we could auto-configure this somehow, but I don't think the secret is available in the env by default?

**Comment by Seldaek** [comment]
I guess the best we could do is detect github actions and recommend setting this up if we get an auth failure.

The other question is indeed why this failed silently, I'd think it should error loudly but maybe not due to `--no-interaction`. I'll look into that.

**Comment by ondrejmirtes** [comment]
This is what I did: https://github.com/phpstan/phpstan-src/commit/58013fe9e4822855266beb9f6173d59304167bf5

I didn't find a more DRY way to do this. If Composer read some environment variable it would be easier.

**Comment by Seldaek** [comment]
there is COMPOSER_AUTH env var which takes a json like `{"github-oauth":{"github.com":"tokenxxxxxxxxx"}}`, that should help :)

**Comment by stof** [comment]
@ondrejmirtes this may deserve a feature request on the `shivammathur/setup-php` action, as it might be able to configure a token then (note sure whether this would work out of the box or would require passing the token to the action explicitly though)

**Comment by ondrejmirtes** [comment]
@Seldaek Thank you!

Even with the token the job sometimes fails, not sure if it's possible I'm going over the rate limit with my job matrix...

**Comment by Seldaek** [comment]
The 5000/h limit is pretty high but anything is possible :P

You could use an inline package declaration instead for this very special case IMO, it'd resolve much faster and without using the github API.  https://getcomposer.org/doc/05-repositories.md#package-2

**Comment by shivammathur** [comment]
@ondrejmirtes @stof Setting the GitHub API token for composer is supported on `setup-php`.
https://github.com/shivammathur/setup-php#composer-github-oauth
