### ISSUE TITLE
--no-interaction (-n): Do not ask any interactive question.

### ISSUE THREAD

**Issue by My6UoT9** [composer/composer#9089]
I understand that this flag, should take the default option?
Using composer `Composer version 2.0.0-alpha2 2020-06-24 21:36:18`

Setting the flag -n `composer update -n` I expect it to take the default option yes, and do whatever would have been done in interactive mode. But that does not happen.
Unfortunately in docu I could not find how the bevahior should be, if it just negates always, or takes default option.

**Comment by Seldaek** [comment]
Which question/prompt are you talking about?

**Comment by My6UoT9** [comment]
This prompt:
```
  - Upgrading organisation/org-module (dev-master 3ef4b23 => dev-master de8bc38): Checking out de8bc38460 from cache
    Update failed (Failed to execute git rev-parse --quiet --verify "de8bc38460a1d32ff3716d12768bf621562e24f5^{commit}" || (git remote set-url
 composer "C:/Users/user/AppData/Local/Composer/vcs/gogs-example.com-ORGEXT-org-module.git/" && git fetch composer && git fetch --tags com
poser); git remote set-url composer "gogs@example.com:ORGEXT/org-module.git"

)
    Would you like to try reinstalling the package instead [yes]?
```

Running with `-n`, this ain't a subsequent run, but I still had this in console from a previous try:
```
 - Upgrading organisation/org-module (dev-master 3d54a0a => dev-master b586471): Checking out b5864711e4 from cache
    Update of organisation/org-module failed
    0 [>---------------------------]
                                                                                                                                  
  [RuntimeException]                                                                                                              
  Failed to execute git rev-parse --quiet --verify "572e8499d362af0915cbf17b803bfb18289db376^{commit}" || (git remote set-url co  
  mposer "C:/Users/user/AppData/Local/Composer/vcs/gogs-example.com-ORGEXT-org-core-core.git/" && git fetch composer && git fetch  
   --tags composer); git remote set-url composer "gogs@example.com:ORGEXT/org-core-core.git"                                          
                                                                                                                                  
```
This is a private repo behind it, using Gitea and Satis. I have modified the names for privacy.

**Comment by Seldaek** [comment]
Ok yes in this case if updating fails we fail hard, because there might be various reasons the update failed. Some reason might be that you have uncommitted/unpushed changes in the directory, and so reinstalling by default would wipe that data, which isn't good.

**Comment by My6UoT9** [comment]
Ah so this only because I am using dev-master and maybe have modified files. 
So when using versions this would not happen.

Hm would it be possible to add a flag for that? Maybe my workflow is not good, but it is how I do it. I got several sub repos in my vendor folder with dev-master, and I can either update em through git, or actually composer update does it too, but I have to press Enter for each default option.

**Comment by Seldaek** [comment]
Might be fixable but it's weird to me how it fails here..

Could you try to run the command which fails inside the given vendor package's dir to see perhaps where/why/how it fails? I'm not sure why the error output is empty in what you copied..

**Comment by My6UoT9** [comment]
Hm this is special indeed, I tried to copy paste the the cmd:
`git rev-parse --quiet --verify "305612527b0f7c2948d0e1b639c0780f61b2ab97^{commit}" || (git remote set-url composer "C:/Users/user/AppData/Local/Composer/vcs/gogs-example.com-ORGEXT-org-core-core.git/" && git fetch composer && git fetch --tags composer); git remote set-url composer "gogs@example.com:FIREEXT/org-core-core.git"`

Running that in windows cmd, it fails with, I can try changing my lang to english if it matters, but only if required:
> "git" kann syntaktisch an dieser Stelle nicht verarbeitet werden.
```
C:\laragon\www\project\vendor\organisation\org-core-core>git rev-parse --quiet --verify "305612527b0f7c2948d0e1b639c0780f61b2ab97^{commit}" || (git remote set-url composer "C:/Users/user/AppData/L
ocal/Composer/vcs/gogs-example.com-ORGEXT-org-core-core.git/" && git fetch composer && git fetch --tags composer); git remote set-url composer "gogs@example.com:ORGEXT/fire-core-core.git
"git" kann syntaktisch an dieser Stelle nicht verarbeitet werden.

```

So this is weird, so I tried to run the cmd till the semicolon, and that worked:
```
C:\laragon\www\fire\vendor\firegroup\fire-core-core>git rev-parse --quiet --verify "305612527b0f7c2948d0e1b639c0780f61b2ab97^{commit}" || (git remote set-url composer "C:/Users/user/AppData/L
ocal/Composer/vcs/gogs-example.com-ORGEXT-org-core-core.git/" && git fetch composer && git fetch --tags composer);
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 23 (delta 18), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (23/23), 2.17 KiB | 11.00 KiB/s, done.
```
... more output from git which is not relevant, it does not fail - thats relevant.

**Comment by Seldaek** [comment]
Ah very good thanks that helped. I believe the latest snapshot fixes it but couldn't really confirm directly. Could you try after a `composer self-update --snapshot` see if it allows your updates to go through now?

**Comment by My6UoT9** [comment]
Unfortunately that did not fix it,
```
 [RuntimeException]                                                                                                                              
  Failed to execute git rev-parse --quiet --verify "305612527b0f7c2948d0e1b639c0780f61b2ab97^{commit}" || (git remote set-url composer "C:/Users/user/AppData/Local/Composer/vcs/gogs-example.com-ORGEXT-org-core-core.git/" && git fetch composer && git fetch --tags composer); git remote set-url composer "gogs@example.com:ORGEXT/org-core-core.git"  
```

**Comment by My6UoT9** [comment]
Hm now I am not sure if I got the latest version.
`Composer version 2.0-dev (2.0-dev+d8fa7464334404643237971bdf921120f784916e) 2020-07-21 15:17:12`
Seems not, I will wait 10mins and try again.

**Comment by Seldaek** [comment]
Sorry you probably ran self-update before the build was done. If you run self-update again it should ship you 41318576a359705c32ce5560a3188b5c54d62fb1 now which is latest commit.

**Comment by My6UoT9** [comment]
Hm it works now, but I am not sure if I did hit the problem for that package which failed before, now it says "from cache"
>  - Upgrading organisation/org-core-core (dev-master aebeae7 => dev-master ae292fe): Checking out ae292fe069 from cache

Maybe you can tell if that is correct - I had expected from git or something related to git?

**Comment by Seldaek** [comment]
Yeah that is probably correct, you can run it with -vvv though which will show you exactly the commands being executed. Anyway if you experience the issue again let me know.
