### ISSUE TITLE
make vendor library centralized for multiple projects

### ISSUE THREAD

**Issue by vrkansagara** [composer/composer#9090]
I would like to see composer use common library while instillation of same library and it's same version for different projects.

example :1 Laravel project using `xyz:1.0.0` library
example :2 Magento  project using `xyz:1.0.0` library

In both project has common library and it's version so lets download it once per user and make it symbolink link using global composer directory so other project can get benefits of same library and no need to download again and again same package from server.

Benefits : -
(1) Hosting provider can save much space per user
(2) Single user can save much space and network delay
(3) https://packagist.org/  download increase capacity approx 20% global

Ping : @Seldaek

**Comment by stof** [comment]
the third benefit is void. packagist.org does not host the code archives at all.

**Comment by Seldaek** [comment]
The disk space saving is the only real benefit, as archives are already stored in local cache and thus not redownloaded, network savings would be minimal. And given the average size of packages and cost of disk space these days, IMO this is not worth optimizing/making more complex with symlinks.
