### ISSUE TITLE
Composer 2: Output of composer show displays incorrect metadata

### ISSUE THREAD

**Issue by ryanaslett** [composer/composer#9094]
`composer show -a vendor/packagename <version>` should give the metadata associated with that version, and did under composer 1.10.9

```
➜  composer --version
Composer version 1.10.9 2020-07-16 12:57:00
➜  composer show -a symfony/yaml v5.0.11
name     : symfony/yaml
descrip. : Symfony Yaml Component
keywords :
versions : v5.0.11
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://symfony.com
source   : [git] https://github.com/symfony/yaml.git 29b60e88ff11a45b708115004fdeacab1ee3dd5d
dist     : [zip] https://api.github.com/repos/symfony/yaml/zipball/29b60e88ff11a45b708115004fdeacab1ee3dd5d 29b60e88ff11a45b708115004fdeacab1ee3dd5d
names    : symfony/yaml

autoload
psr-4
Symfony\Component\Yaml\ => .
exclude-from-classmap

requires
php >=7.2.5
symfony/polyfill-ctype ~1.8

requires (dev)
symfony/console ^4.4|^5.0

suggests
symfony/console For validating YAML files using the lint command

conflicts
symfony/console <4.4
```

However the data that is displayed when using composer 2 shows the metadata for the most recent version of symfony/yaml (those hashes correspond to v5.1.3, instead of v5.0.11) 

```
➜  composer --version
Composer version 2.0.0-alpha2 2020-06-24 21:36:18
➜  composer show -a symfony/yaml v5.0.11
name     : symfony/yaml
descrip. : Symfony Yaml Component
keywords :
versions : v5.0.11
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://symfony.com
source   : [git] https://github.com/symfony/yaml.git ea342353a3ef4f453809acc4ebc55382231d4d23
dist     : [zip] https://api.github.com/repos/symfony/yaml/zipball/ea342353a3ef4f453809acc4ebc55382231d4d23 ea342353a3ef4f453809acc4ebc55382231d4d23
names    : symfony/yaml

support
source : https://github.com/symfony/yaml/tree/5.1

autoload
psr-4
Symfony\Component\Yaml\ => .
exclude-from-classmap

requires
php >=7.2.5
symfony/deprecation-contracts ^2.1
symfony/polyfill-ctype ~1.8

requires (dev)
symfony/console ^4.4|^5.0

suggests
symfony/console For validating YAML files using the lint command

conflicts
symfony/console <4.4
```

**Comment by liz642** [comment]
> `composer show -a vendor/packagename <version>` should give the metadata associated with that version, and did under composer 1.10.9
> 
> ```
> ➜  composer --version
> Composer version 1.10.9 2020-07-16 12:57:00
> ➜  composer show -a symfony/yaml v5.0.11
> name     : symfony/yaml
> descrip. : Symfony Yaml Component
> keywords :
> versions : v5.0.11
> type     : library
> license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
> homepage : https://symfony.com
> source   : [git] https://github.com/symfony/yaml.git 29b60e88ff11a45b708115004fdeacab1ee3dd5d
> dist     : [zip] https://api.github.com/repos/symfony/yaml/zipball/29b60e88ff11a45b708115004fdeacab1ee3dd5d 29b60e88ff11a45b708115004fdeacab1ee3dd5d
> names    : symfony/yaml
> 
> autoload
> psr-4
> Symfony\Component\Yaml\ => .
> exclude-from-classmap
> 
> requires
> php >=7.2.5
> symfony/polyfill-ctype ~1.8
> 
> requires (dev)
> symfony/console ^4.4|^5.0
> 
> suggests
> symfony/console For validating YAML files using the lint command
> 
> conflicts
> symfony/console <4.4
> ```
> 
> However the data that is displayed when using composer 2 shows the metadata for the most recent version of symfony/yaml (those hashes correspond to v5.1.3, instead of v5.0.11)
> 
> ```
> ➜  composer --version
> Composer version 2.0.0-alpha2 2020-06-24 21:36:18
> ➜  composer show -a symfony/yaml v5.0.11
> name     : leo
> descrip. : Symfony Yaml Component
> keywords :
> versions : v5.0.11
> type     : library
> license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
> homepage : https://symfony.com
> source   : [git] https://github.com/symfony/yaml.git ea342353a3ef4f453809acc4ebc55382231d4d23
> dist     : [zip] https://api.github.com/repos/symfony/yaml/zipball/ea342353a3ef4f453809acc4ebc55382231d4d23 ea342353a3ef4f453809acc4ebc55382231d4d23
> names    : symfony/yaml
> 
> support
> source : https://github.com/symfony/yaml/tree/5.1
> 
> autoload
> psr-4
> Symfony\Component\Yaml\ => .
> exclude-from-classmap
> 
> requires
> php >=7.2.5
> symfony/deprecation-contracts ^2.1
> symfony/polyfill-ctype ~1.8
> 
> requires (dev)
> symfony/console ^4.4|^5.0
> 
> suggests
> symfony/console For validating YAML files using the lint command
> 
> conflicts
> symfony/console <4.4
> ```

**Comment by ryanaslett** [comment]
Great, thanks!
