### ISSUE TITLE
composer global require installs to .config/.composer but composer global update looks in .composer?

### ISSUE THREAD

**Issue by ryanmortier** [composer/composer#9096]
Output of `composer diagnose`:

```
Changed current directory to /home/ryan/.composer
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 1.10.9
PHP version: 7.4.3
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

When I run this command:

```
composer global update
```

I get the following output:

```
Changed current directory to /home/ryan/.composer
Composer could not find a composer.json file in /home/ryan/.composer
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
```

And I expected this to happen:

After I installed `composer` I did a `composer global require laravel/installer` which created a `composer.json` file in the directory `/home/ryan/.config/.composer`. However, when I type `composer global update` it's looking in `/home/ryan/.composer`?

Ubuntu 20.04 if it matters.

**Comment by Seldaek** [comment]
Composer 1.x will use ~/.composer if it is present, then use ~/.config/composer otherwise. Composer 2 will change this to prefer the ~/.config one if both are present. Make sure you delete ~/.composer and it should use ~/.config/composer consistently for now. If not please try and debug  what is going on in Composer\Factory::getHomeDir

**Comment by stof** [comment]
@Seldaek should `composer diagnose` be updated in 1.x to detect the case where both directories exist, to show a warning ?

**Comment by Seldaek** [comment]
If someone wants to PR it why not I suppose..
