### ISSUE TITLE
Allow installing from lock

### ISSUE THREAD

**Issue by MatTheCat** [composer/composer#9102]
I was wondering why `composer install` took ages on the CI. I thought in presence of a *composer.lock* file its behavior would be similar to `npm ci` where it just install packages in the exact version.

But on https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies I read

> Running install when a composer.lock file is present resolves and installs all dependencies that you listed in composer.json […]

So I guess that explains it but I cannot find if it is possible to skip dependencies’ resolve when *composer.lock* is present. If not, would it be possible to make it?

**Comment by Seldaek** [comment]
As per the piece of truncated text that follows, "but Composer uses the exact versions listed in composer.lock". So composer install if the lock file is present should be very fast, at least the solving step. The install can still take a while if you have a ton of packages to download/extract.

**Comment by MatTheCat** [comment]
Why does it need to resolve dependencies if every needed package is listed in the lock file with its exact version?

**Comment by Seldaek** [comment]
It still needs to figure out what needs installing/updating/removing between the vendor directory and the state of the lock file, which is done using the solver, but using no network and so few packages that it is typically resolving within milliseconds.

**Comment by MatTheCat** [comment]
Maybe my issue is that the CI starts from an empty vendor folder?

I believe `npm ci` empties the dependencies folder so it does not have to worry about which dependencies were installed.
