### ISSUE TITLE
[Question] Can I use the composer.lock file generated by Composer 2.0 with Composer 1.10?

### ISSUE THREAD

**Issue by anyt** [composer/composer#9108]
Hi guys,

Are there are any breaking changes regarding `composer.lock` file format, or can we safely use the lock file generated by composer 2.0 to install or update dependencies using composer 1.10 and vise-versa? 

I don't see anything related in the changelog or other issues, so I guess it should be fully compatible. 

Thank you for your time!

**Comment by Seldaek** [comment]
It is indeed compatible, as long as it does not rely on  a plugin which requires composer 2 exclusively.
