### ISSUE TITLE
Detect Github Action runs and format errors/warnings in Github Actions format

### ISSUE THREAD

**Issue by staabm** [composer/composer#9109]
When composer is invoked from within a Github Action It should output error messages in the Github Action native error format.

See https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message

This would make error messages appear in the Pull Request itself and people would not need to dig into the Github Actions logs to find out what happend/what the error is

The Github Action run can be detected by presence of a Env var, see https://github.com/OndraM/ci-detector/blob/main/src/Ci/GitHubActions.php

**Comment by Seldaek** [comment]
Should be doable by hooking into Application::doRun, at the end of it we handle exceptions, could output them as errors and then proceed to rethrow to get the usual output as well.

**Comment by staabm** [comment]
I thought about subclassing ConsoleIO and emitting github formatted markup based on the message-formatting tags used in the error messages

**Comment by Seldaek** [comment]
That sounds way overkill IMO, and possibly wrong too, as we sometimes emit warnings and possibly error level stuff which should not really trigger errors on github. Uncaught exceptions tho are definitely a problem we can report. Might just need a special case for solving errors I can't remember if those are output somehow or just thrown.
