### ISSUE TITLE
Composer 2: update --lock not working with aliased package versions correctly

### ISSUE THREAD

**Issue by robert-heinig** [composer/composer#9110]
When executing "update --lock" composer seems to use the dependency data of the aliased (=older) version, not the dependency data of the currently installed package. There are no errors when executing "install" or "update" without "--lock".
This problem does not occur with composer 1.

I do not post my complete package.json because there are private packages. The relevant definitions are:
```
"doctrine/dbal": "2.8.1 as 2.5.4",
"doctrine/common": "^2.10",
```

One of the errors when executing "update --lock":
```
 Problem 1
    - Root composer.json requires doctrine/dbal == 2.5.4.0 -> satisfiable by doctrine/dbal[v2.5.4].
    - doctrine/dbal v2.5.4 requires doctrine/common >=2.4,<2.7-dev -> found doctrine/common[v2.4.0, ..., v2.6.2] but it conflicts with your root composer.json require (^2.10).
```

I expect that the dependency data of doctrine/dbal:2.8.1 will be used:
https://github.com/doctrine/dbal/blob/2.8/composer.json
There is no dependency to doctrine/common in 2.8, but in 2.5:
https://github.com/doctrine/dbal/blob/2.5/composer.json
```
"doctrine/common": ">=2.4,<2.8-dev"
```
This error also occurs for other packages when I version-alias doctrine/common to a valid version, so I don't think it's relevant that there is no dependency to doctrine/common in 2.8.

Output of `composer diagnose`:
```
...
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.0-alpha3
PHP version: 7.2 - Package overridden via config.platform, actual: 7.3.12
PHP binary path: /usr/local/bin/php
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Comment by Seldaek** [comment]
I can't reproduce from a clean install. What versions of doctrine/dbal do you have in `composer show doctrine/dbal` and what version do you have in your existing composer.lock?

**Comment by robert-heinig** [comment]
`composer show doctrine/dbal` shows:
```
versions : * v2.8.1
```
In composer it's the same version:
```
"version": "v2.8.1",
```

**Comment by robert-heinig** [comment]
There is also a "Problem 5" with another doctrine/dbal constraint by another package.
When I use a clean directory and a new composer.json there is an error when trying to install this package.
```
composer require doctrine/common:"^2.10"
composer require doctrine/dbal:"2.8.1 as 2.5.4"
composer require typo3/cms-core:^8 --ignore-platform-reqs

Problem 1
    - typo3/cms-core[v8.7.7, ..., v8.7.32] require doctrine/dbal ~2.5.4 -> found doctrine/dbal[v2.5.4, ..., v2.5.13] but it conflicts with your root composer.json require (2.8.1 as 2.5.4).
    - Root composer.json requires typo3/cms-core ^8 -> satisfiable by typo3/cms-core[v8.7.7, ..., v8.7.32].

Use the option --with-all-dependencies to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```
"--with-all-dependencies" is necessary to install typo3/cms-core:^8.
After installing the package this way, the problem within my origininal post is reproducable with `composer update --lock`.

When 
`doctrine/dbal:"2.8.1 as 2.5.4"`
is defined, shouldn't that prevent the error when trying to install `typo3/cms-core:^8` ?

**Comment by Seldaek** [comment]
Alright I think I found the cause, would be glad if you can verify it fixes it for you though using the latest snapshot: `composer self-update --snapshot`.

**Comment by robert-heinig** [comment]
The initial error does no longer occur, but a fatal error occurs:
```
Fatal error: Uncaught Error: Call to undefined method Composer\Semver\Constraint\Constraint::getPrettyConstraint() in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Request.php:64
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Installer.php(396): Composer\DependencyResolver\Request->requireName('cweagans/compos...', Object(Composer\Semver\Constraint\Constraint))
#1 phar:///usr/local/bin/composer/src/Composer/Installer.php(250): Composer\Installer->doUpdate(Object(Composer\Repository\InstalledFilesystemRepository), true)
#2 phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php(228): Composer\Installer->run()
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\UpdateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Compon in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Request.php on line 64
```
I think the correct method here is `getPrettyString`?
https://github.com/composer/semver/blob/master/src/Constraint/ConstraintInterface.php

Don't know of this exception will be catched or if this is another problem - maybe with the `cweagans/composer-patches` package.

**Comment by Seldaek** [comment]
@robert-heinig please try again with latest snapshot.. Fixed the exception now, so it will get thrown and not caught, it will still fail, but at least maybe it hints at what the problem is.

**Comment by Seldaek** [comment]
Also, if you can reproduce still, it'd be good to get more details as to the steps that you took, as the steps above should not break anymore IIRC.

**Comment by robert-heinig** [comment]
Seems to work now - thank you!

The remaining issue seems to be with cweagans/composer-patches and not composer itself.
