### ISSUE TITLE
[RFC] composer knowledge of EOL/EOM packages

### ISSUE THREAD

**Issue by noniagriconomie** [composer/composer#9113]
Hello

**RFC**

Following https://github.com/symfony/symfony/pull/37754#rfc and its description (bottom part).

I would like to know if there is in the Composer land a way to know the EOL of packages, and then display/notice/warn the dev when such dependencies are inside `composer.json`, and maybe also display it on the http://packagist.org/packages page description

We already know the  [`Security Advisories`](https://github.com/FriendsOfPHP/security-advisories), could an `End Of Life Advisories` be usefull and then evaluated?

friendly ping @stof as you answer in a way on the other PR (cf https://github.com/symfony/symfony/pull/37754#issuecomment-669857399)

Thank you for your time

**Comment by stof** [comment]
Well, the question is how this info about EOL would be managed in the ecosystem, and how they would be defined (most projects don't have a specific EOL per version, but rather per minor or major version depending on whether they support multiple minor versions in parallel). Also, the EOL date might not be defined yet at the time of the release (which excludes putting this in the composer.json of the version).

**Comment by noniagriconomie** [comment]
@stof thanks again for taking time on this, in fact that is is underlying purpose of this issue :)

if we make a parallel with the other logic of security advisor issue, I imagine that we can totaly do something like that;

when a package maintainer(s), who have or not a release/deprecate/endoflife process tied to its package, or even a date known at the start of the release, can advise in such database the tag of its package when it reaches EOL

and then a tool, could be inside composer itself or a plugin installable aside (and packagist.org), could read such info and take action on it (display/warn/etc) the developper regarding its composer deps and versions.

----

the main goal of this discussion is in reality to have a better process of discoverability/upgradability of project dependencies regarding life of package developped and maintained by the community in general :)
it could also be a way for package maintainer to warn "publicly" that such version is EOL, so no issue/PR must be opened on
 etc

**Comment by Seldaek** [comment]
I think it might be a feature we add to packagist.org at some point to allow you to mark versions EOL, or define a policy somehow so it can be automated, but I don't know how beneficial this would be tbh.. Most projects are too small to have any kind of official maintenance schedule, they maintain the last minor and that's it. The big projects already communicate quite clearly and if you're using something like symfony you probably are aware of their maintenance schedule, or you should research this really.

**Comment by noniagriconomie** [comment]
@Seldaek of course big projects have this in their release process, and comunicate on this a lot

> but I don't know how beneficial this would be tbh

The aim is to have this info on a daily basis, when dealing with composer logic as an entry point, and for all kind/size of project :)
For example, now we actually have output like
 - `Package foo/bar is abandoned, you should avoid using it.`
We can imagine in a new outpout
 - `Package foo/bar:1.2.3 is EOL. Considere upgrading to 2.0`
 - `Package foo/bar:1.2.3 will EOL at yyyy-mm-dd (in x days). Considere upgrading to 2.0`

The benefit is here I think. Giving knowledge to devs on their dependencies and the step to upgrade.
Once it is centralised and made available for package maintainer, it could be very usefull like the "abandon" or "security advisor" parts imho.

Anyway, thanks for your time on this :)

**Comment by Seldaek** [comment]
Thinking about this again, I just don't see it happening at such granularity. It seems like more trouble than it's worth so closing.
