### ISSUE TITLE
Feature request: Record composer version in lock file

### ISSUE THREAD

**Issue by rarkins** [composer/composer#9114]
Before v2 becomes GA, I request that Composer embeds the last-run version in its lock file. This concept of explicitly specifying the version that was last used to update the lock file is becoming common in package managers and also helps with things like debugging (examples: Bundler, Go Modules, Poetry).

I am one of the maintainers of [Renovate Bot](https://github.com/renovatebot/renovate) and we need a way of determining which Composer version to run for each repo without requiring every repo to specify it in config and keep it updated, so that is my main motivation.

**Comment by stof** [comment]
As Composer 1.10+ registers the `plugin-api-version` in the lock file now, this can be determined already (you cannot know the exact version of Composer being used, which might generate unnecessary diffs if the patch version is not the same for everyone, but you can get the major version from it)

**Comment by rarkins** [comment]
Thanks for clarifying. Happy to consider this closed for our bot purposes but first my thoughts based on observing a lot of package managers recently:

> As Composer 1.10+ registers the `plugin-api-version` in the lock file now

This approach is a little too obscure/indirect in my opinion. I think recording the version used should be a first class concept in the lock file and more user-friendly than needing to know what `plugin-api-version` means. Of course, it's sufficient for our use case because we're a bot, but it's not human-friendly.

> you cannot know the exact version of Composer being used

I think that's a mistake. Every tool can have regression failures. If/when Composer makes one (e.g. that causes flapping of lock file entries between versions), knowing the exact version that last updated it would be best.

> might generate unnecessary diffs if the patch version is not the same for everyone

Again, I think package managers are converging on approaches to have all members of a team running the same version of tools. You'll certainly never achieve it if Composer intentionally doesn't record the exact version.

However this was also why I used the terminology of "last used to **update**" instead of "last run". I agree that you definitely wouldn't want the lock file updated with a one line diff just because someone ran a newer or older version to install. If Composer was smart enough to only update the version if *some other update to the lock file was required*, then I wouldn't consider this to be undesirable flapping/diffs.

**Comment by Seldaek** [comment]
IMO the benefits you list aren't really worth the added noise in diffs and potential for merge conflicts when people run updates in different branches with different composer versions. People can either require `composer-runtime-api` in their composer.json to enforce a given composer version, or indeed by default you can now read the presence of plugin-api-version in the lock file, if it's missing it's a 1.x.

As for bugs and regressions, the best way to help as an integrator which relies on us not messing up, is to run sufficient CI with pre-release/snapshot versions of Composer, to ensure regressions if any are caught early and before they hit anyone's prod.
