### ISSUE TITLE
Package version updated on Packagist cannot be downloaded by Composer

### ISSUE THREAD

**Issue by antonioribeiro** [composer/composer#9121]
Not sure if there's something I can do on my end fo clear this cache, but:

My `composer.json`:

```json
"require": {
   ... 
    "area17/laravel-auto-head-tags": "^1.1.4"
  },
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.10
PHP version: 7.4.7
PHP binary path: /usr/local/Cellar/php/7.4.7/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

When I run this command:

```
composer update
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package area17/laravel-auto-head-tags ^1.1.4 exists as area17/laravel-auto-head-tags[dev-master, 2.0.x-dev, v1.0.0, v1.0.1, v1.1.0, v1.1.1, v1.1.2, v1.1.3] but these are rejected by your constraint.
```

And I expected this to happen:

Package to be updated, because the [package on packagist.com](https://packagist.org/packages/area17/laravel-auto-head-tags) is showing as with v1.1.4.

**Comment by stof** [comment]
@Seldaek is there an extra delay in the metadata dumping on Packagist currently ?

**Comment by stof** [comment]
OK, I just saw this: https://twitter.com/packagist/status/1293823325903486976

**Comment by antonioribeiro** [comment]
Thanks, @stof!
Closing it.

**Comment by antonioribeiro** [comment]
For those in a hurry like me, you can still grab the commit hash and update it manually on `composer.lock`:

![image](https://user-images.githubusercontent.com/3182864/90117094-b877b400-dd56-11ea-9fbf-f06c62ccc0e9.png)

**Comment by Seldaek** [comment]
Sorry for the trouble, almost done

**Comment by antonioribeiro** [comment]
No worries, @Seldaek , take your time, this workaround was enough to unblock me.
And thank you for your amazing work.

**Comment by Seldaek** [comment]
All back to normal, after metadata updates came back we had to deal with some related downtime but anyway all sorted now.
