### ISSUE TITLE
Composer update does not respect version range configured in composer.json

### ISSUE THREAD

**Issue by windaishi** [composer/composer#9123]
### My `composer.json`:

```json
{
    "name": "pickware/public-demo-shop",
    "type": "project",
    "description": "Project used for Pickware public demo shop.",
    "license": "proprietary",
    "require": {
       ...
        "shopware/administration": "~6.2",
        "shopware/core": "~6.2",
        "shopware/storefront": "~6.2",
        ...
    },
    "require-dev": {
        ...
    },
    "config": {
        "optimize-autoloader": true
    },
    "autoload": {
        "psr-4": {
            "Pickware\\PublicDemoShop\\": "src/"
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}
```

### Output of `composer diagnose`:

```
Checking composer.json: WARNING
require.composer/package-versions-deprecated : exact version constraints (1.8.0) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.10
PHP version: 7.4.8
PHP binary path: /usr/local/Cellar/php/7.4.8/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

### When I run this command:

```
composer update
```

### I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 3 updates, 3 removals
  - Removing phpseclib/phpseclib (2.0.28)
  - Removing google/apiclient-services (v0.142)
  - Removing google/apiclient (v2.4.0)
  - Installing psr/event-dispatcher (1.0.0): Loading from cache
  - Updating shopware/core (v6.2.3 => 6.3.0.1): Loading from cache
  - Updating shopware/administration (v6.2.3 => 6.3.0.1): Loading from cache
  - Updating shopware/storefront (v6.2.3 => 6.3.0.1): Loading from cache
Writing lock file
```

### And I expected this to happen:

Composer is installing version 6.3.0.1 of the packages `shopware/*` even though this version does not match the version range configured in the composer.json.

I expect composer to update to a version matching `~6.2`, e.g. `6.2.1`.

If I change the composer.json to have `~6.2.0` instead of `~6.2` everything works as expected.

**Comment by xabbuh** [comment]
`~6.2` is equal to `>=6.2.0,<7.0`. So the result is totally expected. If you want to stick on 6.2.*, you will need to use one of `~6.2.0`,`6.2.*`, or `~6.2,<6.3.0`.

**Comment by windaishi** [comment]
Semver Cheat Sheet tells s.th. different: https://devhints.io/semver
Also an online checker: https://jubianchi.github.io/semver-check/#/~6.2/6.3.0.1

**Comment by Seldaek** [comment]
That cheatsheet is for npm, welcome to Composer :D You may want to read our docs https://getcomposer.org/doc/articles/versions.md#next-significant-release-operators

**Comment by windaishi** [comment]
It's very sad that this issue was closed with such a comment.
I think it is still an issue of composer that the `~` works differently there than in many other package managers, like npm and yarn. 
The problem as a developer: You have to know this! If you don't, you'll get serious issues.

I opened that issue in the Composer and not in NPM  because (in my opinion) Composer handles it unintuitive. You have to know that `^5.1.3` is the same as `^5.1` but `~5.2.0` and `~5.2` are different.

The world would be nicer if both tools work the same you you do not have to remember the "special" rules of every tool.

With composer 2.0 you have the chance to solve an issue for developers by adjusting the behavior of the ~ in composer, to work like "expected", like npm handles it.

**Besides that, since the docs don't state that:**
What does `~6.3.1.0` compare to?

**Comment by stof** [comment]
changing the meaning of constraint operators in composer 2 is a no-go: it would break support for all existing releases of packages, which is far too big as impact.

The composer `~` operator works exactly like the `~>` operator of Bundler (which was the original inspiration of Composer constraints, not npm).

> I think it is still an issue of composer that the `~` works differently there than in many other package managers, like npm and yarn.

Which "many" package managers ? npm and yarn are 2 CLI clients for the *same* ecosystem of packages (they both use the npm registry), so they count as only 1 here.
Bundler does not have any equivalent of the npm `~` operator for instance.

> What does `~6.3.1.0` compare to?

`>=6.3.1.0, <6.3.2`. The `~` operator allows to increment only the last segment of the specified version (excluding the first segment, so `~3` is not different from `~3.0`, otherwise that would not have any upper bound)

**Comment by windaishi** [comment]
@stof Thank you for your answer.

> The composer ~ operator works exactly like the ~> operator of Bundler (which was the original inspiration of Composer constraints, not npm).

This is a nice info to know, thanks. That explains many things.

> Which "many" package managers ? npm and yarn are 2 CLI clients for the same ecosystem of packages (they both use the npm registry), so they count as only 1 here.

Well, I think it is still a problem that in composer and NPM `~` works differently. PHP and JS (NPM) are often used together in the same project, so confusing the things is pretty easy. I did some deeper googling and found that actually the `~`-operator has different meanings in pretty much every package-manager, whereas ^ seems to be mostly working the same. For PHP and JS this leads to a special kind of problem as they are often used together in the same project.

> changing the meaning of constraint operators in composer 2 is a no-go: it would break support for all existing releases of packages, which is far too big as impact.

Yeah, I see the problem here. 

As I can see there is no actual standard for version ranges with semver and maybe that the root of all evil.

After all I still have a suggestion to maybe reduce the problem:
* Add a hint in the documentation that the `~` operator works differently in NPM and composer.

Hopefully there will be a new standard for semver version ranges to get rid of such nasty problems in the future.

**Comment by stof** [comment]
> Yeah, I see the problem here. But still i would be happy to see forward to a world where the semver-ranging in NPM and composer ARE the same and not feel or look the same.

That would require one of the ecosystems to start over from scratch, banning all releases created using the old meaning of the operator (not gonna happen in any of them IMO) or to settle on a *new* common operator and strongly discourage using the old `~` (but without ever being able to remove it, otherwise we're back at the previous alternative, except it would not silently change old releases).

>  * Add a hint in the documentation that the `~` operator works differently in NPM and composer.

I would say that this is totally possible. The source of the doc lives in the `doc` folder of the repo.

**Comment by Seldaek** [comment]
We added `^` exactly to add compatibility with npm, it works exactly the same then. We also added support for `||` for compatibility with npm. But `~` we can not fix anymore as @stof explained. It works the same as npm when you specify 3 digits, which IMO makes sense if you are looking to stay stuck within one minor version. If you only use 2 digits then they work differently.

**Comment by windaishi** [comment]
> We added `^` exactly to add compatibility with npm, it works exactly the same then. We also added support for `||` for compatibility with npm. But `~` we can not fix anymore as @stof explained. It works the same as npm when you specify 3 digits, which IMO makes sense if you are looking to stay stuck within one minor version. If you only use 2 digits then they work differently.

So you are actually aiming to be fully (as possible) compatible with npm?

How about a non-breaking solution then, like stating in composer.json which "version range" method is used, with values like  "npm-compatible", "full-npm". If not stated, the fallback is the current "composer" method.

**Comment by Seldaek** [comment]
No we don't aim to be fully compatible, we aim to be compatible where possible/sensible because indeed many php devs are going to use both.

We use `^` by default when you use composer require, which is a strong nudge in that direction.. I hardly see `~` used at this point I have to say. I think it's just an unfortunate accident you fell into, maybe it's not worth over-correcting because of it.
