### ISSUE TITLE
Have autoload.php put "version" from composer.json into $_ENV var

### ISSUE THREAD

**Issue by pnoeric** [composer/composer#9126]
Forgive me if this has already been done. I regularly push out releases of my web site and update the version number at the top of my composer.json file. (To be clear: this is indicating the version of the entire site release; this has nothing to do with versions of individual packages.)

```
{
    "name": "my-github-name/my-project-name",
    "version": "1.7.0",
    "license": "see license in LICENSE.md",
    "homepage": "https://example.com",
    "type": "project",
    "require": {
        "php": "^7.4",
        "monolog/monolog": "^1.25",
        "firebase/php-jwt": "v5.0.0",
        "theiconic/php-ga-measurement-protocol": "^2.7",
        ....etc....
    }
}
```

And then I'd like to be able to indicate this version number somewhere in my code on the site.

One way to do this is to have webpack (or whatever other build tool) parse that version number and put it somewhere. But my project doesn't have a big build process and I don't use webpack.

So I was thinking: hmm, my project includes composer's vendor/autoload file on every page, which is already parsing out that version number. Why can't composer just dump it into a PHP $_ENV variable for me, so I can access it readily?

i.e., with the example above, it would be like `$_ENV['COMPOSER_VERSION'] = "1.7.0"`

Then in my code I can access that $_ENV variable anywhere, any time, to show the version number.

Again: I'm just thinking, if Composer is already doing so much processing with the composer.json file, this seems like an extremely trivial addition to the library to add some useful functionality.

**Comment by michaljusiega** [comment]
Maybe try to use InstalledVersion class from Composer 2 to get your project version?

**Comment by pnoeric** [comment]
It appears that the `InstalledVersions` helper class only returns results for the packages I've installed. My idea is actually about the "global" composer version number (at the top of the file), not the version of any of the packages.

This is the version number I want:

![image](https://user-images.githubusercontent.com/447652/90334857-db150180-dfd0-11ea-849f-8610249d8aa9.png)

...and like I said, if autoload.php is already playing with the composer.json file and parsing things, it seems like it would be super trivial to copy that version number into an $_ENV variable.

In fact, if someone can give me an idea of where to start, I'd be happy to try to do it and submit a PR...

**Comment by michaljusiega** [comment]
So use `InstalledVersions::getPrettyVersion('my-github-name/my-project-name');` or `InstalledVersions::getPrettyVersion('root');` ?

**Comment by pnoeric** [comment]
Hmm that might work, so I have two thoughts:

1. If that package goes out to github to retrieve the info, that won’t work since my project is private.

2. Installing a whole package seems a little bit like overkill if it’s something that could just be added to the existing composer auto load in a few lines. :-)

Do you know the composer code base? If you can tell me where something like this might go, I’d love to explore it’s feasibility.

**Comment by michaljusiega** [comment]
> 
> Do you know the composer code base? If you can tell me where something like this might go, I’d love to explore it’s feasibility.

Sorry, I don't know Composer enough to help you.

**Comment by stof** [comment]
When using composer 2, this can be solved with `InstalledVersions::getRootPackage()['pretty_version'];`, as the version of the root package is available through this API.
Composer 1 does not have a similar runtime API.

**Comment by pnoeric** [comment]
Thank you! I see now how it works in Composer 2. Instead of messing with the current code I'll just use C2. ;-) Appreciate it!!
