### ISSUE TITLE
Allow `symlink: true` to actually force symlinks

### ISSUE THREAD

**Issue by hdodov** [composer/composer#9147]
I have a folder structure that looks like this:

```
/projects
  /lib-a
  /lib-b
  /mysite
```

The project `mysite` uses `lib-b`, which uses `lib-a`. My `composer.json` for `mysite` looked like this:

```json
{
	"minimum-stability": "dev",
	"repositories": [
		{
			"type": "path",
			"url": "../lib-a",
			"options": {
				"symlink": true
			}
		},
		{
			"type": "path",
			"url": "../lib-b",
			"options": {
				"symlink": true
			}
		}
	],
	"require": {
		"me/lib-b": "dev-dev"
	}
}
```

The problem I was experiencing was that `lib-b` was always cloned as a Git repository, instead of getting symlinked. At the actual location of `lib-b`, I have the `dev` branch checked out. I created a new `test-branch` and executed `composer require me/lib-b:dev-test-branch` and _then_ it created a symlink. This makes no sense! Why do I need to checkout an empty branch just to force symlinking...

To verify it's reproducible before writing this issue, I executed `composer require me/lib-b:dev-dev` and instead of removing the link and cloning the repo (as expected), Composer cloned the repo _before_ removing the link and it actually overwrote my `lib-b` repository... I had some unstaged changes and they were lost. That's pretty shitty.

So there are two problems:

1. Composer only appears to creates symlinks when the currently checked out branch is not present on the remote
2. Composer manipulates repositories before checking to see if it accesses said repositories via symlink

**Comment by Seldaek** [comment]
Could you perhaps build a reproduce case with open source minimalistic repos (no need for much in there aside from a composer.json)? That'd be easier to then try it out and see what is exactly going on and what can be improved.

Especially if you find a good repro case for the overwriting of code, that would definitely be good to fix.

**Comment by Seldaek** [comment]
Closing as no feedback and no clear actionable step here.
