### ISSUE TITLE
Composer runs out of memory

### ISSUE THREAD

**Issue by rootpric** [composer/composer#9149]
My `composer.json`:

Where can I find my composer json?
```

Output of `composer diagnose`:

```
How do I run diagnose?
```

When I run this command:

```
composer update
```

I get the following output:

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///opt/cpanel/composer/bin/composer/src/Composer/DependencyResolver/RuleSetGenerator.php on line 129

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.
```

And I expected this to happen:
updated successfully

**Comment by Seldaek** [comment]
Known issue, Composer 2 helps with that, you can try the prerelease already, see https://github.com/composer/composer/releases/tag/2.0.0-alpha3

**Comment by rootpric** [comment]
I have tried that it seems composer broke after the update and reverting back to earlier version does not fix it. Sent from Mail for Windows 10 From: Jordi BoggianoSent: Tuesday, August 25, 2020 2:52 AMTo: composer/composerCc: Joseph Sherrill; AuthorSubject: Re: [composer/composer] Composer runs out of memory (#9149) Known issue, Composer 2 helps with that, you can try the prerelease already, see https://github.com/composer/composer/releases/tag/2.0.0-alpha3—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
