### ISSUE TITLE
FR: Use cache read-only (for being bind-mountable into container)

### ISSUE THREAD

**Issue by arnegroskurth** [composer/composer#9150]
I do have a use-case where a read-only usage of the composer cache would be helpful: I'm running composer inside a docker-container and would like to re-use the composer-cache of the docker host using a bind-mount. However, as the user inside the container does in general not have the same UID/GID, the mounted cache gets "corrupted" as files added to the cache will now be owned by a different user.

This might also get fixed by docker (https://github.com/moby/moby/issues/22258) (hopefully) via a transparent UID/GID translation for bind-mounts but using the cache just read-only would also do the trick for this and comparable scenarios.

Just to preemp:
- I'm not able to / do not want to change the user running the service inside the container - that's another concern.
- Due to the potential size of the cache, it is not practical to copy the entire cache into the container - so using a bind-mount is a must.
- Updating the file ownerships after composer has run is shaky as cumbersome error-handling is required in case the composer-run fails

**Comment by Seldaek** [comment]
Note you can use the env var `COMPOSER_CACHE_READ_ONLY=1` as well as the config. I hope it works for you. You can try with the latest 2.0 snapshot (`composer self-update --snapshot`)
