### ISSUE TITLE
Composer breaks after update

### ISSUE THREAD

**Issue by rootpric** [composer/composer#9151]
My `composer.json`:

```json
{
    "name": "goalgorilla/social_template",
    "description": "Social project template for composer based Open Social projects.",
    "type": "project",
    "license": "GPL-2.0+",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "composer/installers": "^1.0",
        "drupal-composer/drupal-scaffold": "^2.6.1",
        "cweagans/composer-patches": "^1.0",
        "goalgorilla/open_social": "~8.0",
        "php": "^7.2",
        "monolog/monolog": "^1.17",
        "drupal/entity": "^1.0",
        "drupal/flag": "^4.0",
        "drupal/like_and_dislike": "^1.0",
        "league/oauth2-client": "^2.4",
        "drupal/social_auth_facebook": "^2.0",
        "drush/drush": "^10.3",
        "drupal/ief_table_view_mode": "^2.1",
        "drupal/time_formatter": "^1.0",
        "drupal/nodejs": "^1.3"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        },
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ],
    "scripts": {
      "post-install-cmd": [
        "DrupalComposer\\DrupalScaffold\\Plugin::scaffold"
      ],
      "post-update-cmd": [
        "DrupalComposer\\DrupalScaffold\\Plugin::scaffold"
      ]
    },
    "extra": {
        "installer-types": [
            "bower-asset",
            "npm-asset"
        ],
        "installer-paths": {
            "html/core": [
                "drupal/core"
            ],
            "html/modules/contrib/{$name}": [
                "type:drupal-module"
            ],
            "html/profiles/contrib/social": [
                "goalgorilla/open_social"
            ],
            "html/profiles/contrib/{$name}": [
                "type:drupal-profile"
            ],
            "html/themes/contrib/{$name}": [
                "type:drupal-theme"
            ],
            "html/libraries/{$name}": [
                "type:drupal-library",
                "type:bower-asset",
                "type:npm-asset"
            ],
            "drush/contrib/{$name}": [
                "type:drupal-drush"
            ]
        },
        "enable-patching": true
    }
}
```

Output of `composer diagnose`:

```
]$ composer diagnose
Checking composer.json: WARNING
License "GPL-2.0+" is a deprecated SPDX license identifier, use "GPL-2.0-or-later" instead
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.10
PHP version: 7.4.9
PHP binary path: /opt/cpanel/ea-php74/root/usr/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

When I run this command:

```
composer update
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///opt/cpanel/composer/bin/composer/src/Composer/DependencyResolver/RuleSetGenerator.php on line 129

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.[oiwb57pb88ya@ip-132-148-167-96 test]$

```

And I expected this to happen:
Successfully updated. 
I have tried to roll back to an earler version but still having issues

**Comment by rootpric** [comment]
how do I remove composer globally? I have removed every instance of composer from all users and projects along with the Lock and Json files. Yet I type composer it runs and replaces the files that I have previously deleted, CentOS7  Cpanel and WHM platform.
.

**Comment by xabbuh** [comment]
How did you install it globally?

**Comment by rootpric** [comment]
I never did but after I delete all instances of composer from all users on the server. and come back and type "composer" it runs and re-installs .composer file on its own?  So it must be installed globally? unless you have a different explanation on how it re installs its self?

**Comment by rootpric** [comment]
And this thread can be combined with this issue its the same problem   
Composer always runs into "Allowed memory size of 1610612736 bytes exhausted" - on server as well as local! #9166

https://github.com/composer/composer/issues/9166

**Comment by rootpric** [comment]
This is how you install composer globally but how do you remove it globally?

Globally#
You can place the Composer PHAR anywhere you wish. If you put it in a directory that is part of your PATH, you can access it globally. On Unix systems you can even make it executable and invoke it without directly using the php interpreter.

After running the installer following the Download page instructions you can run this to move composer.phar to a directory that is in your path:

mv composer.phar /usr/local/bin/composer
If you like to install it only for your user and avoid requiring root permissions, you can use ~/.local/bin instead which is available by default on some Linux distributions.

Note: If the above fails due to permissions, you may need to run it again with sudo.

Note: On some versions of macOS the /usr directory does not exist by default. If you receive the error "/usr/local/bin/composer: No such file or directory" then you must create the directory manually before proceeding: mkdir -p /usr/local/bin.

Note: For information on changing your PATH, please read the Wikipedia article and/or use your search engine of choice.

Now run composer in order to run Composer instead of php composer.phar.

**Comment by rootpric** [comment]
Ran the command "composer install" and "composer install --no dev" after deleting "composer.lock" and got this same  result for both commands..


Loading composer repositories with package information
Updating dependencies (including require-dev)

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///opt/cpanel/composer/bin/composer/src/Composer/DependencyResolver/Solver.php on line 223

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.


and nothing on suggested web page helped.

**Comment by xabbuh** [comment]
If you followed those instructions you will have to remove the `/use/local/bin/composer` file to remove it globally. But I fail to see how that will help with your memory limit issue. Do you really have to set the minimum stability option to `dev`? Removing that will probably decrease the memory being used.

**Comment by rootpric** [comment]
It all started with the last composer update. This occurs on 2 different projects on Drupal a total of 4 different websites both online and local. We have tried most rollback and dev, alpha and beta fallback options. It seems the server update for composer broke the composer system and rolling back has no effects. Goddady comes with composer installed globally by default.

And this person  Composer always runs into "Allowed memory size of 1610612736 bytes exhausted" - on server as well as local! #9166 Has the same issue so it is not just me.

**Comment by rootpric** [comment]
Please merge these issues


Composer always runs into "Allowed memory size of 1610612736 bytes exhausted" - on server as well as local!
#9166
FrazeColder opened this issue 23 hours ago · 1 comment

Composer breaks after update #9151
 Open
rootpric opened this issue 6 days ago · 8 comment

**Comment by rootpric** [comment]
Please correct me if I am wrong? If I am successful at the removal of all composer installed instances? I should get the response of "composer command not found" when I try to run composer? That is what I am aiming for. A complete removal of composer from the entire two systems both online and local.

**Comment by xabbuh** [comment]
> A complete removal of composer from the entire two systems both online and local.

I still fail to see how that would solve the memory limit issue. Anyway, if Composer is installed by Godaddy, you should rather ask their support to remove Composer if that's really what you want to do.

**Comment by rootpric** [comment]
We are running a VPS server GoDaddy refuses to maintain it other than to make sure it has power to it.
I am thinking if I can remove all instances that all set values will set back to default. And I want to do away with global install which I think is over riding all other composer values mem properties and so on. I want to get rid of global and have composer setup on a per project basis. And why are you not addressing Composer always runs into "Allowed memory size of 1610612736 bytes exhausted" - on server as well as local! #9166???

I have repeatedly asked for a merge with that guy?

**Comment by xabbuh** [comment]
> And why are you not addressing Composer always runs into "Allowed memory size of 1610612736 bytes exhausted" - on server as well as local! #9166???
> 
> I have repeatedly asked for a merge with that guy?

Because as you can see I do not have any permissions here to do so.

**Comment by xabbuh** [comment]
By the way, as said in https://github.com/composer/composer/issues/9151#issuecomment-683593359:

> Do you really have to set the minimum stability option to `dev`? Removing that will probably decrease the memory being used.

Can you provide some feedback on this?

**Comment by rootpric** [comment]
In response to above question. We are trying all possibilities leaving nothing untried.

**Comment by rootpric** [comment]
Now lets stop bickering? And address this issue with professionalism please?

**Comment by rootpric** [comment]
Please give me options to try???

**Comment by rootpric** [comment]
@xabbuh How can we merge those two issues?

**Comment by rootpric** [comment]
Ok I have removed every instance of composer from the server and will try to install composer on a per project basis

**Comment by rootpric** [comment]
Problem solved. You have to remove composer competently from server and local. Test your success by calling composer and you should get "composer command not found". Then install composer on a per project basis fallowing the steps from this page https://getcomposer.org/download/

**Comment by rootpric** [comment]
Nope not working All four Drupal installations are now non accessible now I have larger problems then I started out with
