### ISSUE TITLE
Support for unsetting export-ignore attribute in .gitattributes

### ISSUE THREAD

**Issue by greg0ire** [composer/composer#9153]
The following allows to express "exclude everything but `src` and `LICENSE` and is understood as such by `git archive` and Github:

```
/* export-ignore
/src -export-ignore
/src/** -export-ignore
/LICENSE -export-ignore
```

It does not seem to be handled when using `satis build` though. `statis build` seems to relate on this piece of code from Composer for that purpose:

https://github.com/composer/composer/blob/2a13bb2649151932407aae1a37a356179b1f5199/src/Composer/Package/Archiver/GitExcludeFilter.php#L69-L79

As you can see, lines ending with `-export-ignore` (note the first dash) will not be taken into account, which means this probably will result in an empty archive.

**Comment by morozov** [comment]
I'm a total stranger to the Composer internals but as fairly pointed out in https://github.com/doctrine/dbal/pull/4227#issuecomment-680227779, the logic of handling `.gitattributes` is implemented in `git archive`.

What's the reason to reimplement this in Composer?

**Comment by Ayesh** [comment]
> What's the reason to reimplement this in Composer?

Composer has a `composer archive` command that is similar to `git archive`. In a standard GitHub zipball downloads, `composer archive` is not used, but I think it's good if `composer archive` behaves similar to `git archive`.
