### ISSUE TITLE
Be able to handle multiple autoloaded vendors into project, maybe with class prefix ?

### ISSUE THREAD

**Issue by matks** [composer/composer#9180]
Hi !

I work on the [PrestaShop](https://github.com/prestashop/prestashop) e-commerce CMS.

The community of PrestaShop module developers is using more and more Composer and that is a great thing 😄 .
However most of current shop environments cannot allow to run `composer install` in production, so the standard way to workaround this is for modules to build ZIP archives with bundled-in vendors.

In PrestaShop, all modules are installed within the `modules/` folder and loaded on-demand, either being booted specifically or as event listeners.

**So the following situation happens more and more:**

The Shop mycommerce.com has installed 3 modules: A, B and C. All of them have been installed as a ZIP archive with bundled-in vendors:

```
modules/
    moduleA/
        somefile.php
        somefile.css
        composer.jon
        vendor/
            autoload.php
            superdev/
                awesomepackage
    moduleB/
        somefilecool.php
        aaa.js
        composer.jon
        vendor/
            autoload.php
            superdev/
                anotherpackage
    moduleC/
        bbb.php
        composer.jon
        vendor/
            autoload.php
            greatdev/
                package
```

So far, so good. Everything works like a charm.

The issue comes when moduleA and moduleB decide to use _the same dependency_ with different versions. For example moduleA uses Guzzle v6 and moduleB uses Guzzle v7.

```
modules/
    moduleA/
        somefile.php
        somefile.css
        composer.jon
        vendor/
            autoload.php
            guzzlehttp/
                guzzle
    moduleB/
        somefilecool.php
        aaa.js
        composer.jon
        vendor/
            autoload.php
            guzzlehttp/
                guzzle
    moduleC/
        bbb.php
        composer.jon
        vendor/
            autoload.php
            guzzlehttp/
                guzzle
```

Right now, this is not supported. So what happens is _the first module which is loaded_ will load its version of Guzzle. And when another module, in the same request, uses Guzzle too, the autoload keeps the "1st version autoloaded".

So if moduleA uses Guzzle v6 and moduleB uses Guzzle v7 ; if module A is loaded first then module B, then moduleB will be run with Guzzle v6 code, not Guzzle v7.

## One possible solution: prefix

I dont know if Composer can and/or should fix this solution. This is an open question 😄 .

One idea I have would be to allow Composer to prefix a vendor namespace to allow specific targeting.

So if moduleA was prefixing guzzle with 'ModuleA' and moduleB was prefixing guzzle with ModuleB', Composer would be fine because there would be no conflicts. There would class `ModuleA\GuzzleHttp\Client` and class `ModuleA\GuzzleHttp\Client`.

Ideally this would be transparent, meaning "classes loaded by a composer.json with prefix feature enabled do not need to use the dedicated prefix".

### Other issues

In order to be sure I am not submitting a duplicate, I looked at other issues and found other ones that are somehow related but not identical:
- https://github.com/composer/composer/issues/7527
- https://github.com/composer/composer/issues/7526
- https://github.com/composer/composer/issues/8568
- https://github.com/composer/composer/issues/8429

**Comment by Seldaek** [comment]
This is not something we are going to support. The solution here is for PrestaShop dependencies, including modules, to be all resolved in one go by Composer. That would be much cleaner and would not result in duplicated dependencies like you're seeing.

**Comment by matks** [comment]
> This is not something we are going to support. The solution here is for PrestaShop dependencies, including modules, to be all resolved in one go by Composer. That would be much cleaner and would not result in duplicated dependencies like you're seeing.

Thank you for your answer ! I was expecting this 😅 but I asked anyway

I am willing to explore this feature on my side, on my  fork. If was able to build a "Namespace Prefix" feature stable enough, and passing Composer Continuous Integration, would you consider merging the PR (and thus accepting to maintain it in the future) or is that a final "won't support" decision ?

**Comment by Seldaek** [comment]
That's a fairly final no. I just don't want to waste energy supporting this. https://github.com/humbug/php-scoper is kinda doing it, and might be part of a best practices/how-to solution for module authors I suppose, but I don't think this belongs in composer itself.

**Comment by matks** [comment]
> That's a fairly final no. I just don't want to waste energy supporting this. https://github.com/humbug/php-scoper is kinda doing it, and might be part of a best practices/how-to solution for module authors I suppose, but I don't think this belongs in composer itself.

Thank you for the link ! This does look like a nice work-around we can provide to people needing to solve a "same dependency, multiple versions" issue until we reach the point where we use a single Composer for the whole project (we are working on it, but it'll take probably at least 2 major releases before reaching this point).

Thank you for the answer, and thank you for the amazing work you do on Composer 😊 have a nice day !

**Comment by lhall-amphibee** [comment]
Sorry for reviving this thread, but I am a PrestaShop module developer and I'm facing this exact problem.

I wanted to know if you found a way around this issue ?

**Comment by matks** [comment]
@lhall-amphibee Multiple module developers I know are using https://github.com/humbug/php-scoper and this is doing great for them

**Comment by lhall-amphibee** [comment]
Thanks for the proposition, I will look into it !
