### ISSUE TITLE
Enhancing security insights for Composer

### ISSUE THREAD

**Issue by bmvermeer** [composer/composer#9182]
Hey folks,
Brian from [Snyk](https://snyk.io) (open source security) here 👋

Me and my team have been spending some time recently working with the community to increase the security awareness for developers as they use dependencies. A good couple of examples of that which we've done already with community folks are [a small badge on jsDelivr](https://www.jsdelivr.com/package/npm/lodash?version=4.17.0), and CDNjs [like this](https://cdnjs.dev/libraries/lodash.js/4.10.0).
 
I'd be keen on exploring some ideas like integrating a quick badge on package pages like packagist, or even further collaboration. The Composer vulnerabilities database (and other ecosystems) is already open https://snyk.io/vuln?type=composer and we could make APIs available to tie all of this up.
 
![image](https://user-images.githubusercontent.com/316371/89864178-2afc5e80-dbb4-11ea-9e24-961218144164.png)

or [like this on yarnpkg](https://yarnpkg.com/package/markdown):
 
![image](https://user-images.githubusercontent.com/316371/89864434-9f370200-dbb4-11ea-941a-3a69d4eae8ae.png)
 
Both me and @lirantal would be happy to work with you on something similar or jump on a call to discuss other ideas.

**Comment by Ayesh** [comment]
Tagging some related issues and projects. I maintain a WordPress security advisory composer confict-list myself, and was interested in creating a plugin too, but I came across much better approaches:
 - https://github.com/DavidePastore/composer-audit
 - #7323
 - https://github.com/narrowspark/automatic-security-audit
 - https://github.com/sensiolabs/security-checker
 - https://github.com/fancyguy/composer-security-check-plugin

**Comment by lirantal** [comment]
Hey Ayesh. Great resources list! Happy to meet you 🤗 

Brian's initial post is just one idea but in a bigger picture Snyk is doing a lot of community outreach and involvement and there's a bigger story here. A partial list of a more long-term collaboration is:
1. Proposing to embed security insights in package pages on https://packagist.org/ (perhaps though this isn't the proper repository for that?)
2. Proposing a deeper relationship of the Snyk security research team with the PHP community to help triage, collaborate with maintainers of composer packages and even contribute fixes. We've had tremendous success doing this collaboration on other ecosystems like npm, as well as performing our own security research to further uncover security issues and then work with maintainers on responsible disclosures for them.

I'm not sure who would be the folks to include in a broader collaboration like above which spans between the composer CLI, the packagist website and the PHP Security team. Would appreciate if you know the relevant people to bring to the conversion.

**Comment by stof** [comment]
Packagist already contains some info about security advisories. See for instance https://packagist.org/packages/symfony/symfony:

- the right bar shows `Security: 51` which is the number of security advisories for that package (clicking on it shows the list)
- the list of versions on the bottom right shows a red warning for vulnerable versions.

Right now, these advisories are sourced from https://github.com/FriendsOfPHP/security-advisories. But more sources can be added.

**Comment by lirantal** [comment]
Oh weird I haven't noticed that! is this new or has been there all along? 🙃
It's great to see!

- I wonder if it can be more visible somehow?
- Maybe can show the number of vulns each version tag has? with distribution of h/m/l (severity levels)

How would you go about adding more sources such as what we can help with from the Snyk side?
Can you do a quick scan of the blog here https://snyk.io/blog/instant-security-information-with-the-snyk-security-badge/ ? it's about putting a badge with a score which I think is more visible for users.

**Comment by Ayesh** [comment]
I was pleasantly surprised to see packagist showing how many vulnerabilities the package has. It also shows vulnerable tags as such. It's a recent addition, as far as I remember. 

It looks like the data directly comes from the FriendsOfPHP security advisories project. This list does not provide any indication for severity of the vulnerabilities, but it's good at gate keeping all vulnerable versions regardless of the severity.

**Comment by stof** [comment]
@lirantal see https://github.com/composer/packagist/tree/master/src/Packagist/WebBundle/SecurityAdvisory for the implementation

**Comment by naderman** [comment]
As was discussed here, the necessary API already exists on packagist.org which Composer uses anyway. So closing this in favor of https://github.com/composer/composer/issues/10329
