### ISSUE TITLE
Snapshot build of 1.x

### ISSUE THREAD

**Issue by stof** [composer/composer#9189]
Currently, there is no way to install a snapshot version of Composer 1.x to benefit early for bug fixes merged in 1.x, as the snashot channel contains Composer 2.
As both major versions are active in parallel, it might make sense to provide a nightly build of composer 1.x as well.

**Comment by Seldaek** [comment]
That is true, but I am not going to waste time on this. The goal is to get 2.0 out asap. I just tagged 1.10.11 though which contains all the php8 fixes.
