### ISSUE TITLE
Diagnose tells me to self-upgrade, even after I've just done that

### ISSUE THREAD

**Issue by derickr** [composer/composer#9199]
Output of `composer diagnose`:

```
Checking composer version: You are not running the latest snapshot version, run `composer self-update` to update (1.10.13 => 0408207e350d3be0a7b2c8a9795841f6f235826e)
Composer version: 1.10.13
PHP version: 7.0.33-dev
```

When I run this command:

```
php ~/composer.phar self-update
php ~/composer diagnose

```

I get the following output:

```
Upgrading to version 1.10.13 (stable channel).

….

Checking composer version: You are not running the latest snapshot version, run `composer self-update` to update (1.10.13 => 0408207e350d3be0a7b2c8a9795841f6f235826e)
Composer version: 1.10.13
PHP version: 7.0.33-dev
```

And I expected this to happen:

No warning, or an upgraded composer.

**Comment by Seldaek** [comment]
That is odd because the self-update uses stable channel, but diagnose uses snapshot channel. What do you have in `~/.composer/update-channel` or `~/.config/composer/update-channel`?

**Comment by derickr** [comment]
```
derick@gargleblaster:/tmp/amqplib$ cat ~/.composer/update-channel
snapshot
```

```                                                                   
derick@gargleblaster:/tmp/amqplib$ cat ~/.config/composer/update-channel 
stable
```

**Comment by Seldaek** [comment]
Ah you got both I see. You probably should delete ~/.composer in that case.. tho I don't quite understand why it picks one over the other in different situations. I guess I'll try to repro locally later. But I'd imagine wiping ~/.composer would solve it for you at least.

**Comment by derickr** [comment]
I can confirm that it does.

**Comment by Seldaek** [comment]
Can't repro but anyway Composer 2 changes the logic there so hopefully whatever caused this is fixed there already.
