### ISSUE TITLE
While install / update codeigniter 4 getting :: Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos

### ISSUE THREAD

**Issue by ranaprathap006** [composer/composer#9205]
C:\xampp\htdocs\newsportal>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 31 installs, 0 updates, 0 removals
  - Installing fzaninotto/faker (dev-master 5337ce5): Cloning 5337ce5261
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+DESKTOP-B7V11J0+2020-09-12+0801
to retrieve a token. It will be stored in "C:/Users/VR-Local/AppData/Roaming/Composer/auth.json" for future use by Composer.
Token (hidden):

**Comment by suwidadi** [comment]
i experiencing similar to this. when installing using PHP 7.4 and composer 2.0.2.

**Comment by Seldaek** [comment]
We need more info on how to reproduce this if you'd like us to help.

**Comment by suwidadi** [comment]
> We need more info on how to reproduce this if you'd like us to help.

I just using composer command below

`composer create-project codeigniter4/appstarter` 

I found out that the git is needed. after git installation, the composer installation works.

**Comment by Seldaek** [comment]
I can't repro this if git is missing.. I think it might only happen if you run out of API requests for github or something along those lines. Anyway not sure what we could even do about it. It asks you to configure a github token which isn't the worst problem is it?

**Comment by suwidadi** [comment]
yes, actually it a little bit weird asking for a GitHub auth token which we should provide the URL of repos we don't own and in particular is fzaninotto faker repos.

**Comment by henzeb** [comment]
Had similar issues with a private repo of ours. In our case we had git installed and all, I could clone the repo manually in the same shell (kubuntu), but composer insisted on asking a token. I finally made it work: If at first you don't succeed, try, try again: 
When it asks a token, press enter, when it asks if you want to try again, just press enter, this may solve your issue.

**Comment by cwegener** [comment]
> I found out that the git is needed. after git installation, the composer installation works.

Thank you. You win the Internet for the day!

**Comment by Rau7** [comment]
Maybe it's about dependencies' characteristics. If a dependency pulled from GitHub, yes you'll need git. For dependencies not stored on GitHub (like google/apiclient), it seems you won't need it. Actually it worked for me just like that.

**Comment by MrLeche** [comment]
I installed git GUI based. Dose10X64, no dice...

**Comment by ramphy** [comment]
You need install first "GIT"

apt-get install git

and then composer again.

**Comment by MrLeche** [comment]
I'm using Doze. WIN10X64 on XAMPP. Anyways I got it all figured out. Thank
you so much!

**Comment by MrLeche** [comment]
'Ppreciate it bruh!

**Comment by mikiyasET** [comment]
you can follow the link https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+Unk...... it might be different on your case check the command line you will find it and then it will ask for your GitHub account and then you can generate a token and when you enter the token in the command line it will work

**Comment by clementkasun** [comment]
create personal access token on git and paste it when appear to enter

**Comment by jimmymchau** [comment]
Just press **ENTER** button twice (two times in a lump sum)  when it asked you for a git token

**Comment by Jalalnx** [comment]
> Just press **ENTER** button twice (two times in a lump sum) when it asked you for a git token

thanks
