### ISSUE TITLE
platform requirements do not have a pretty constraint (composer 2.0-RC1)

### ISSUE THREAD

**Issue by mitelg** [composer/composer#9210]
Is there a reason why [here (PlatformRepository)](https://github.com/composer/composer/blob/master/src/Composer/Repository/PlatformRepository.php#L589) no pretty constraint is passed to the platform requirements?

We read them out and got an error with composer 2
Works fine with composer 1.x

**Comment by Seldaek** [comment]
Probably no good reason no. Could be fixed. Feel free to send a PR fixing it for the couple cases in this class.

**Comment by mitelg** [comment]
okay cool 👍 I will do that
