### ISSUE TITLE
Can we have an alias for --with-dependencies

### ISSUE THREAD

**Issue by vaibhavjain-in** [composer/composer#9213]
My `composer.json`:

```json
Not Required
```

Output of `composer diagnose`:

```
Not Required
```

When I run this command:

```
composer update Repo/Package --with-dependencies
```

I get the following output:

```
I tend to mistype the word dependencies
```

And I expected this to happen:
I expect to have an alias like `-wd` which is much smaller and there are less chances of mistake.

I know its not just me, whose first language is not English. Many other devs including my team members / friends are facing this issue.

**Comment by Seldaek** [comment]
I think we could add -w for --with-dependencies and -W for --with-all-dependencies.
