### ISSUE TITLE
Segfaults on armhf with composer.json with authors and mail

### ISSUE THREAD

**Issue by jaymoulin** [composer/composer#9216]
My `composer.json`:

```json
{
    "authors": [
        {
            "name": "My Name",
	    "email": "test@example.com"
        }
    ]
}

```

Output of `composer diagnose`:

```
Segmentation fault (core dumped)
```

When I run this command:

```
composer --version
```

I get the following output:

```
Segmentation fault (core dumped)
```

And I expected this to happen:

Composer version 1.10.13 2020-09-09 11:46:34

Useful information:

Using docker image arm32v6/php:7.4-alpine without anything added
Output of `uname -m` : `armv7l`
Segfault only occurs on this architecture when email is set on authors index 0.
Composer installed with 
```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '795f976fe0ebd8b75f26a6dd68f78fd3453ce79f32ecb33e7fd087d39bfeb978342fb73ac986cd4f54edd0dc902601dc') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
```
And 
```
wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --quiet
```

Both methods gave the same results

**Comment by stof** [comment]
segmentation fault indicates that PHP itself (or one of its extensions) is crashing. so I doubt the composer team can solve this

**Comment by jaymoulin** [comment]
If `email` is absent in `authors` section, it works. If composer.json is absent, it works, PHP works and the application mounted on this particular docker version without anything compiled with, it works. Hope it helps

**Comment by Seldaek** [comment]
No it doesn't help. I don't have access to an arm machine, and as @stof said segfaults are not our jurisdiction.. Please report this at bugs.php.net, it's great that it seems like you got a minimalistic repro case so they can probably act on that.
