### ISSUE TITLE
Feature Request: Improve compression for faster network

### ISSUE THREAD

**Issue by bingalls** [composer/composer#9217]
It would be nice for composer to allow tighter compression, for better performance.
Perhaps content-type style negotiation?
In particular, xz offers the tightest compression in free/open software standards.
While decompression speeds rival zip, parallel xz should rival parallel unzip.
7z is on par with tar.xz, but may require custom tweaking- e.g. must be told how many cpus are available. Parallel pxz, which needs no tuning, may decompress faster than tuned 7z
xz is not so good at repairing corrupted archives. However, SHA hashes & re-downloads should mitigate such uncommon occurrences.

**Comment by naderman** [comment]
Hey, Composer actually already supports xz https://github.com/composer/composer/blob/master/src/Composer/Downloader/XzDownloader.php - however we do not generate or host any of the archive files for open source PHP packages on packagist.org. Files are provided by the source hosting provider the package uses, which in over 95% of cases is GitHub. So if anything you'd have to talk to GitHub support about adding this as a feature to their archive generation.
