### ISSUE TITLE
Removing a dependency does not remove its child dependencies (composer 2.0-RC1)

### ISSUE THREAD

**Issue by rgeraads** [composer/composer#9218]
When I run composer require phpunit/phpunit it installs phpunit and all its requirements, but when I do composer remove phpunit/phpunit  it only removes the main dependency, leaving its children in composer.lock. is this intended?

**Comment by stof** [comment]
Is this happening with Composer 2 ? If yes, that's a known issue tracked at https://github.com/composer/composer/issues/8870

**Comment by rgeraads** [comment]
Indeed. Thanks! I will close this one then.
