### ISSUE TITLE
Observation: platform-check (composer 2)

### ISSUE THREAD

**Issue by MircoBabin** [composer/composer#9222]
I observed the https://github.com/composer/composer/blob/2.0.0-alpha1/UPGRADE-2.0.md stating a new platform-check is added https://github.com/composer/composer/blob/2.0.0-alpha1/doc/07-runtime.md#platform-check.

The implementation of platform-check is a black/white solution. Either all requirements are fullfilled or you will get a white page in production. There is no chance of Laravel (or any other framework) logging the error.

So what's better from a production perspective ? Having a production site that works for 0% (black) or having a site where some parts don't work because of requirements not being fulfilled (grey) ? And if the production site is grey, the not working parts can be fixed while the working parts can be used. And while the production site is grey at least Laravel is logging errors that can be inspected.

I rather have a grey production site than a black production site. So for now I am going to update alle my composer.json to:

```
    "config": {
        "platform-check": false
    },

```

**Comment by Seldaek** [comment]
The point is more.. in your grey state, some of it might work, but you won't know if it all works until later.. At least with the hard failure now you realize the problem very quickly and can fix it immediately. Ideally you should realize this on a staging env and not production, that's for sure. Anyway feel free to disable it if you rather risk partial issues, it's definitely up to you if you use this or not.

**Comment by Seldaek** [comment]
Also note that you could set `composer config -g platform-check false` globally (with -g) on the production machine so you avoid issues there but still make sure staging/dev envs would get a hard failure if not setup correctly.

**Comment by MircoBabin** [comment]
> The point is more.. in your grey state, some of it might work, but you won't know if it all works until later.. At least with the hard failure now you realize the problem very quickly and can fix it immediately. Ideally you should realize this on a staging env and not production, that's for sure. Anyway feel free to disable it if you rather risk partial issues, it's definitely up to you if you use this or not.

In theory everything could go wrong when platform requirements are not met. In practice this is not the case. When deploying to 50 websites simultaneously I want my grey state. Because of the timeline.

You are right that having a mechanism in place to test for platform requirements could be helpful. But it should not be a black/white solution. Perhaps a grey solution can also be added, where platform requirements will be checked but no hard fail. Output about what platform requirements are not met is then returned to the caller who can log it (assuming logging works, but in theory everything can work if you are optimistic or nothing works if you are pessimistic).

There is a staging environment, but this is not equal to the production environment. The staging environment could meet the platform requirements while the production environment does not.


> Also note that you could set `composer config -g platform-check false` globally (with -g) on the production machine so you avoid issues there but still make sure staging/dev envs would get a hard failure if not setup correctly.

SSH is not possible, the Internet Service Provider does not support this. Deployment takes place via FTP.

**Comment by Seldaek** [comment]
Ideally you would run `composer check-platform-reqs` before putting the code in production, that's the "Perhaps a grey solution can also be added, where platform requirements will be checked but no hard fail".

**Comment by MircoBabin** [comment]
In utopia world it would be possible to run ```composer check-platform-reqs``` everywhere on every server and platform. But as I have written before, on the production site I can not execute ```composer``` commands. 

So if something breaks, it will be after the production deployment via FTP. And here starts the "timeline". At this point there is only a way forward, there is no revert step or go back to the previous version step. So while figuring things out with the ISP helpdesk (that takes time, maybe the ISP has to take additional steps to provide the correct platform requirements), I want as much functionality working as possible for the end users. So my grey scenario. Off course not all will work, but this can be incrementally improved in the next hour(s).

I understand that in utopia world one would always have an option to revert to the previous version in such cases. Unfortunatly I'm not living in utopia world, I have to deal with ISP requirements beyond my power.

I can disable the platform requirements check in the composer.json, so I have a solution. I'm sharing my observation because many projects don't live in utopia world.  And the on by default platform requirement check could yield an unexpected experience for may.

If ```composer``` does not want to support the grey scenario and wants to live in utopia world, that's ok. But at least inform via blogs, documentation, discussions, etc. what the consequences can be of the platform requirements check.

**Comment by stof** [comment]
Composer already supports disabling that platform check, either at the project level or globally on the system (if you don't run the `composer install` command in your prod server but on another system, *that* system is the one where the global config could be useful).
This platform-check features comes from the fact that a common mistake is to use incompatible dependencies (when composer is not run on the production server so `composer install` is not itself reporting the issue) and then get errors which don't clearly explain the problem and often get reported to the package using a new PHP syntax, while this package has no issue. This creates a lot of issue triaging work for many open-source project, and this `platform-check` feature solves that. Also, depending on the architecture of the project, disabling might still not allow things to work (so the grey scenario would not actually be grey) and for such case, it only increases the time until the actual issue is known.

This feature is not built for an utopia world. In an utopia world, local, staging and production environments are identical and so there is no issue regarding not respecting platform requirements.

**Comment by MircoBabin** [comment]
> Composer already supports disabling that platform check, either at the project level or globally on the system (if you don't run the `composer install` command in your prod server but on another system, _that_ system is the one where the global config could be useful).

Thanks for the explanation. Because it is a project descision involving multiple programmers/systems not to perform the platform requirements check, the way to go for me is to use the composer.json flag.

> This platform-check features comes from the fact that a common mistake is to use incompatible dependencies (when composer is not run on the production server so `composer install` is not itself reporting the issue) and then get errors which don't clearly explain the problem and often get reported to the package using a new PHP syntax, while this package has no issue. This creates a lot of issue triaging work for many open-source project, and this `platform-check` feature solves that. 

Again thanks for the explanation, it is now clearer what problem the platform requirements check tries to solve. But as I observed there is a downside to this solution.

I have hesitations about the solution. If open source projects get a lot of issues because of platform requirements failing, how is this solution going to solve that?
* The developer, working on a local environment, very early gets a black site when platform requirements are failing. But a new platform requirement might not be noticed, because the developer already activated too much extensions. Or a platform requirement was already needed for a ```--dev``` package. When the developer environment gets black, that's not really an issue because it only affects one person and not production.
* The production site, after FTP deployment, goes black because platform requirements are failing. The developer didn't notice a new plaform requirement and the production site has as less as possible extensions activated because of security. Here the production site goes down, affecting many persons. And that's where my grey scenario gets in to play.



>Also, depending on the architecture of the project, disabling might still not allow things to work (so the grey scenario would not actually be grey) and for such case, it only increases the time until the actual issue is known.

That depends, it could be the grey scenario equals the black scenario, but could also be a grey scenario. The answer depends on each individual situation. In the grey scenario, at least there is a chance some parts are working, and the remaining parts can incrementally be made working. In the black scenario for sure none part is working. And in the black scenario logging will not work, because the autoloading of logging will fail. And composer does not have a logging facility. No logging really is a problem.

> This feature is not built for an utopia world. In an utopia world, local, staging and production environments are identical and so there is no issue regarding not respecting platform requirements.

I agree with this conclusion, as you have explained the problem to be solved is the number of issues in open-source projects. Which apparently is a real life problem.
