### ISSUE TITLE
New Windows User Doc Issue:  After Global Install "Getting Started" does not explain where to install composer.json

### ISSUE THREAD

**Issue by VBruceHunt** [composer/composer#9225]
My `composer.json`:

Is simple but does not exist yet because, as a newbie, I don't know where to install it. This is likely a documentation issue. I've just globally installed composer for windows 10 and am following the "Getting Started" and moved to the "Basic Usage Page."  The "composer.json" file is clearly described but where to put it is not.  For clarity and newbie peace of mind, it would be good to explicitly state where to put the 'composer.json' file and to explain why it goes where it goes.  When installing something new to a project, one tends to be hyper about understanding exactly what is going on.  It would assist us new users greatly to have that clarity.

Output of `composer diagnose`:

```
...replace me...
```

When I run this command:

```
...replace me...
```

I get the following output:

```
...replace me...
```

And I expected this to happen:

**Comment by sumpygump** [comment]
I believe you are referring to this page:
https://github.com/composer/composer/blob/master/doc/01-basic-usage.md

Do you have a suggestion on how the documentation could be updated to clarify where to put the file and why?

**Comment by Seldaek** [comment]
Fixed or at least hopefully improved by https://github.com/composer/composer/commit/e3c6b213e770ceb078f8958c177e1119f89a984d
