### ISSUE TITLE
v2.0.0-RC1  OperationInterface::getReason() is always null in the 'post-package-install' event

### ISSUE THREAD

**Issue by kpicaza** [composer/composer#9230]
In the 1.x version, the 'post-package-install' event's operation reason, is filled with a GenericRule object instance, since the versión 2.x the OperationInterface::getReason is always null. Is this an expected behavior?

Thanks for your great work;-D

**Comment by simonberger** [comment]
This has been removed in commit http://github.com/composer/composer/commit/25de5218c39957dc644eb9f03c265a0bb7060534
Not obvious to me if this happened intentionally or not. Currently the reason seems nowhere in use and should be removed.

/cc @naderman

**Comment by naderman** [comment]
Install now really means synchronization with the lock file, so during package install there is no information available on rules from a composer update which had an effect on the selection of the package. This previously was rather unreliable information as it would have depended on whether you ran composer update yourself or if somebody else generated the lock file for you for example.

**Comment by Seldaek** [comment]
Removed getReason completely as it was not used anymore in v2, please make sure your plugin stops relying on it when used with Composer 2.
