### ISSUE TITLE
Feature request: Improve VCS/git repository speed with concurrent / asynchronous calls

### ISSUE THREAD

**Issue by medigeek** [composer/composer#9233]
Hi,

We use a lot of vcs/git repositories and it would be a nice addition to have a `--async` flag that would make importing vcs/git branches in parallel/concurrent/asynchronously, using guzzle http or guzzle command or otherwise?

We have tried with the prestissimo plugin but doesn't match our expectations when contacting the vcs/git repositories (i.e. when importing git branches and tags).

**Comment by Seldaek** [comment]
That's IMO not worth the code complexity increase given the use case. VCS repos aren't meant to be used by the dozen in your composer.json, there are other better solutions like Private Packagist which make it much more efficient as the metadata is kept in sync in the background. See https://getcomposer.org/doc/05-repositories.md#hosting-your-own

**Comment by medigeek** [comment]
Thank you for the reply. Unfortunately, solutions like satis increases the overall project complexity on a user-level, as we need it to be dynamic, to get the latest version to test and push between repos the latest version found in git repositories.
Perhaps satis with cron could help. But do keep in mind my suggestion. I'll see if I can fork something up, something simple. :)

**Comment by Seldaek** [comment]
@medigeek I'm pretty sure [Private Packagist](https://packagist.com) simplifies the user level complexity as it automatically syncs all your git repos, you don't really have to think about it much there, you add the composer repo once in your json and that's it.

**Comment by medigeek** [comment]
Oh, thank you for the link! Will definitely take a look at it.
