### ISSUE TITLE
"Overwriting requires seems like a bug" error for composer update --lock

### ISSUE THREAD

**Issue by glaubinix** [composer/composer#9240]
My `composer.json`:

```json
{
    "require": {
	    "composer/composer": "^2.0@dev"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0-dev+5df1797d20c6ab1eb606dc0f0d76a16ba57ddb7f
PHP version: 7.4.10
PHP binary path: /usr/local/Cellar/php/7.4.10/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

When I run this command:

```
composer update --lock or composer update nothing
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies


  [LogicException]
  Overwriting requires seems like a bug (composer/composer == dev-master => == dev-master, check w
  hy it is happening, might be a root alias
```

And I expected this to happen:
This works fine in Composer 2.0-alpha3

**Comment by Majkl578** [comment]
Same issue with dependency locked to a specific commit (`dev-master#abcd`). Stacktrace:
Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Request.php:64
 Composer\DependencyResolver\Request->requireName() at phar:///usr/local/bin/composer/src/Composer/Installer.php:396
 Composer\Installer->doUpdate() at phar:///usr/local/bin/composer/src/Composer/Installer.php:250
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:228
 Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:309
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:121
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:61
 require() at /usr/local/bin/composer:24

**Comment by Seldaek** [comment]
@Majkl578 I can't reproduce this. Please make sure you can with latest snapshot (`composer self-update --snapshot`) and if you can give me more repro details.

**Comment by Majkl578** [comment]
@Seldaek Yep, it seems to work fine in master, I encountered the issue with 2.0.0-RC1. Looking forward to RC2. 😎

**Comment by bretto36** [comment]
For anyone else who encounters this. Check to see if the package that is erroring is in the .lock file more than once. 

I had an issue where a git merge had a conflict and it duplicated the package in the lock file. Removing the duplicate fixed the issue
