### ISSUE TITLE
1.10.13: complex `composer exec` argument parsing fails on Windows

### ISSUE THREAD

**Issue by lkraav** [composer/composer#9244]
My `composer.json`:

This problem is independent of a specific `composer.json`

Output of `composer diagnose`:

```
$ composer diagnose
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.hull/hull : unbound version constraints (dev-master) should be avoided
require.league/plates : unbound version constraints (dev-master) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Composer version: 1.10.13
PHP version: 7.4.9
PHP binary path: /usr/lib64/php7.4/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

When I run this command:

```
composer exec -v phpcbf -- src/Plugin.php; if [ $? -eq 1 ]; then exit 0; fi
```

I get the following output:

On Linux, all great success.

On Windows, `;` and beyond get treated as arguments to `phpcbf`.

```
× composer exec -v phpcbf -- src\Plugin.php; if [ $? -eq 1 ]; then exit 0; fi:
> __exec_command: phpcbf "src\Plugin.php;" "if" "[" "$?" "-eq" "1" "];" "then" "exit" "0;" "fi"
Script phpcbf handling the __exec_command event returned with error code 3
ERROR: The file "src\Plugin.php;" does not exist.
Run "phpcbf --help" for usage information
husky > pre-commit hook failed (add --no-verify to bypass)'
```

And I expected this to happen:

Great argument parsing success, like on Linux.

I can't tell for sure, but this might be an upstream https://github.com/symfony/console/tree/master/Input issue.. or?

**Comment by johnstevenson** [comment]
What terminal are you using on Windows? `src/Plugin.php; if [ $? -eq 1 ]; then exit 0; fi` is a bash command.

**Comment by lkraav** [comment]
@saas786 could provide some details on your environment?

**Comment by saas786** [comment]
Basically I use github desktop app, and it uses "Git bash" with it.

![git-shell](https://user-images.githubusercontent.com/1642796/94411231-c3b16280-0191-11eb-8dbb-55cfb9665cf4.jpg)

**Comment by stof** [comment]
The shell used by Github Desktop has no relation to the shell used by PHP for its subprocess (which is `cmd` on Windows)
