### ISSUE TITLE
Previously (potentially) invalid version strings now valid

### ISSUE THREAD

**Issue by ryanaslett** [composer/composer#9246]
With the changes surrouding https://github.com/composer/semver/issues/106 and https://github.com/composer/composer/issues/9191 and other related issues, Im wondering if something changed that is now *allowing* previously invalid versions to be parsed and acceptable.

We recently had a user that was unable to install a package because it had the following requirement string:

`"drupal/lingotek": "^2.21 || ^3.*"`

That user was using composer 1.10.8, and got the following response:

```
  [RuntimeException]                                                                            
  Could not load package drupal/lingotek_comment_profile in https://packages.drupal.org/8: [Un  
  expectedValueException] Could not parse version constraint ^3.*: Invalid version string "^3.  
  *"       
```

However, our packaging system validates that string as valid, and also, composer 1.10.13 does not have any problem with that string:

So, either composer is letting some invalid versions slide through now, Or that version was actually fine in the first place, and composer now accepts it. 

Im basically filing this issue just in case its the former, hoping its the latter.

**Comment by dkulyk** [comment]
You should use one of `^3.0`, `3.*` and not combination of both.

**Comment by stof** [comment]
see https://getcomposer.org/doc/faqs/why-are-version-constraints-combining-comparisons-and-wildcards-a-bad-idea.md

**Comment by ryanaslett** [comment]
I think you are misreading my report.  We're aware that wildcards are a bad idea. And that combining those is an error.

The issue is that *old versions* of projects used those wildcards, and prior to the recent changes, those weird versions *used to fail validation*, and our packages.drupal.org repository would reject them. Now that we've upgraded the validator on p.d.o to use the most recent version, versions like `^3.*` are now passing validiation, being delivered in the metadata, which breaks older composer clients. 

So, *should they still fail validation* ? Presumably the linked issues were to make validation more strict and keep garbage out of the metadata, so I dont think we want to also loosen validation at the same time.

**Comment by ryanaslett** [comment]
And the docs that you linked to mention

> For this reason, Composer throws an error and says that this is invalid.

Composer no longer throws an error and says that this is invalid.. so I think this is definitely a new bug.

**Comment by ryanaslett** [comment]
I have verified that this is a bug recently introduced in composer/semver, and opened a PR there https://github.com/composer/semver/pull/117
