### ISSUE TITLE
Help Request

### ISSUE THREAD

**Issue by begrafx** [composer/composer#9249]
Not a "Bug report" but just a help request.

I inadvertently managed to overwrite my COMPOSER.JSON file, when I was attempting to create one in another folder. The COMPOSER.LOCK file from the original .JSON file is still intact. Is there some way of regenerating the .JSON file from the information in the .LOCK file?

**Comment by begrafx** [comment]
Perhaps a better question would be, Is there some way of regenerating the .JSON file from the .LOCK file, or otherwise recovering the .JSON?

**Comment by ryanaslett** [comment]
The lock file contains the exact versions that composer resolved based on your likely much more open constraints in your original composer.json, so you could regenerate a composer.json from your lock file, but it wouldnt resemble your original constraints in any way. 

git/versioncontrol is the tool you should be using to recover changes to your composer.json.  If you do not have any of these files in versioncontrol, then theres not a straightforward way to recover them.

**Comment by begrafx** [comment]
I don't have git/versioncontrol, and I'm guessing that it is something that would have needed to have been in place PRIOR to this mishap... ?

The project is fairly simple and early on, so I can probably just "harvest" the files/versions from the lock file. I just wanted to throw this out there to ask, before I started in on something, if there was an easier recovery method.

**Comment by ryanaslett** [comment]
Yes, it would have been helpful prior. So you should set it up now before doing anything else.

**Comment by begrafx** [comment]
As I think about it, git/versioncontrol wouldn't have helped here anyhow. If it's part of the GIT system, it would only keep track as you work and make commits. This was still a fairly early-on project, that wasn't ready to make commit, but far enough along I didn't want to have to try to recreate the JSON file if I didn't have to. I guess perhaps that should become part of the process... just like saving your work... commit regularly, commit often. :)
