### ISSUE TITLE
this file does not have an app associated with it for performing this action . Please install an app or , if one is already installed, create an association in the Defalt Apps Settings page

### ISSUE THREAD

**Issue by NegraMed** [composer/composer#9254]
i get this error message " this file does not have an app associated with it for performing this action . Please install an app or , if one is already installed, create an association in the Defalt Apps Settings page" 

When I run this command:

```
composer -v 
```
in the cmd after installing the composer and adding the path

**Comment by stof** [comment]
which OS is this ? And how did you install it ?

**Comment by NegraMed** [comment]
On windows and i followed this website to install it https://getcomposer.org/download/

**Comment by stof** [comment]
have you used the windows installer or the command-line instructions ?
