### ISSUE TITLE
The "-D" flag for "composer outdated" should be the default

### ISSUE THREAD

**Issue by MidnightDesign** [composer/composer#9255]
I think `composer outdated` should only list direct dependencies by default. It's what's actionable for the developer and I actually don't see a point in seeing outdated dependencies of my dependencies ever. (But there should be an option for querying that as well obviously.)

Also, it would bring Composer in line with Yarn and NPM.

What do you think?

**Comment by stof** [comment]
@MidnightDesign it depends what you use the command for. Most of the time, outdated patch releases are actionable, as a `composer update` will allow upgrading.

**Comment by MidnightDesign** [comment]
Your're right, haven't thought of that. I just blindly do `composer update` and trust that my dependencies adhere to semantic versioning and/or my CI catches any errors.

Still, I think the "are there any dependencies in my composer.json that I need to upgrade" use case is way more frequently used and should be the default.

**Comment by Seldaek** [comment]
That's an opinion/workflow thing.. We surely can't fit everyone's workflow with the defaults, that's why we have optional flags after all :)
