### ISSUE TITLE
vendor package repos

### ISSUE THREAD

**Issue by dgoosens** [composer/composer#9266]
Hi

Not sure this is the appropriate place to ask questions, but haven't found any Discord or Slack channel to discuss this matter...

So I'm going to start a new Symfony based projet....  
Following the DDD principles, I want the business layer of my app to be completely decoupled from the framework (nope, no microservices).  
Therefore, we will create a dedicated vendor package for each module.

Thus, what I would need is the ability to edit & commit both the app within the framework and all my vendor packages (not the other vendors' packages).  
I read about the `--prefer-source` argument that can be used to download the source of a package instead of its build.... But that does not seem the best way to proceed as it would download the sources of ALL the packages.

Would seem "logical" to me if there were a section in the `composer.json` file where I could indicate a list of packages that in `dev` mode would require the sources to be fetched (ie. repo should be cloned).  
Or are there any other ways to achieve this easily... I can't find any real best practices about this online...  
(I've seen people using symlinks to achieve this, that would work I guess, but does not seem very intuitive).

Any thoughts/suggestions ?

**Comment by Seldaek** [comment]
See https://getcomposer.org/doc/06-config.md#preferred-install

**Comment by dgoosens** [comment]
great !  
should have searched better it seems  

thanks a lot
