### ISSUE TITLE
imply `--ansi` when composer is running within a Github Action

### ISSUE THREAD

**Issue by staabm** [composer/composer#9269]
wouldn't it make sense to imply `--ansi` when composer runs within a Github Action?

atm we need to add a lot of --ansi params in our workflows etc. see e.g. https://github.com/redaxo/redaxo/pull/3939/files

PR welcome?

**Comment by mfn** [comment]
Some projects (e.g. phpstan) use https://github.com/OndraM/ci-detector to automatically figure out sane defaults for some of the runtime settings.

**Comment by Seldaek** [comment]
Why though? That looks like a symfony/console bug or a github action env bug? This stuff should just work from our perspective..

**Comment by stof** [comment]
the guessing in `symfony/console` relies on `stream_isatty`: https://github.com/symfony/symfony/blob/v5.1.7/src/Symfony/Component/Console/Output/StreamOutput.php#L94

Maybe github actions does not run commands using a tty.

**Comment by Seldaek** [comment]
Yeah IMO this should be fixed in actions or symfony/console, not really our problem..
