### ISSUE TITLE
[ErrorException]   "Undefined index: extra" Composer can't install / upgrade packages

### ISSUE THREAD

**Issue by gino2014** [composer/composer#9271]
My `composer.json`:
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "require": {
        "avstudnitz/scopehint2": "^1.1",
        "dhl/shipping-m2": "1.0.0",
        "firegento/magesetup2": "^0.2.0",
        "fooman/emailattachments-m2": "^3.0",
        "magefan/module-login-as-customer": "2.2.5",
        "magefan/module-translation": "^2.0",
        "magefan/module-wysiwyg-advanced": "^2.0",
        "magehost/performance-dashboard": "^1.15",
        "magento/product-community-edition": "2.3.5-p2",
        "magento/quality-patches": "^1.0",
        "magento2translations/language_el_gr": "dev-master",
        "magepal/magento2-customeraccountlinksmanager": "^1.1",
        "magepal/magento2-customshippingrate": "^1.6",
        "mageplaza/module-currency-formatter": "^1.0",
        "magepow/multitranslate": "^1.0",
        "magepow/recentorder": "^1.0",
        "olegkoval/magento2-regenerate-url-rewrites": "^1.5",
        "redchamps/module-clean-admin-menu": "^1.0",
        "swissup/ajaxlayerednavigation": "^1.3",
        "swissup/argento-m2": "1.20",
        "swissup/cache-warmer": "^1.0",
        "swissup/easyflags": "^1.3",
        "swissup/email": "^0.3.11",
        "swissup/email-templates": "^1.0",
        "swissup/firecheckout": "^1.22",
        "swissup/helpdesk": "^1.1",
        "swissup/maintenance": "^2.1",
        "swissup/module-marketplace": "^1.5",
        "swissup/pdf-invoice": "^1.2",
        "zf1/zend-reflection": "^1.12"
    },
	"replace": {
    "swissup/theme-frontend-argento-essence": "*",
    "swissup/theme-frontend-argento-flat": "*",
    "swissup/theme-frontend-argento-pure2": "*",
    "swissup/theme-frontend-argento-mall": "*",
    "swissup/theme-frontend-argento-stripes": "*"
},
    "require-dev": {
        "allure-framework/allure-phpunit": "~1.2.0",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.5.0",
        "fooman/composer-magento2-optimizations": "dev-master",
        "friendsofphp/php-cs-fixer": "~2.15.8",
        "lusitanian/oauth": "~0.8.10",
        "magento/magento-coding-standard": "*",
        "magento/magento2-functional-testing-framework": "~2.6.4",
        "pdepend/pdepend": "2.5.2",
        "phpcompatibility/php-compatibility": "^9.3",
        "phpmd/phpmd": "@stable",
        "phpstan/phpstan": "^0.12.2",
        "phpunit/phpunit": "~6.5.0",
        "sebastian/phpcpd": "~3.0.0",
        "squizlabs/php_codesniffer": "~3.4.0",
		"drewm/mailchimp-api": "^2.2",
		"knowband/constantcontact": "1.0.0",
		"mobiledetect/mobiledetectlib": "^2.8",
		"geoip2/geoip2": "^2.9.0"
    },
    "conflict": {
        "gene/bluefoot": "*"
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/",
            "Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/"
        },
        "psr-0": {
            "": [
                "app/code/",
                "generated/code/"
            ]
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/",
            "Magento\\PhpStan\\": "dev/tests/static/framework/Magento/PhpStan/"
        }
    },
    "version": "2.3.5-p1",
    "minimum-stability": "stable",
    "repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "swissuplabs": {
            "type": "composer",
            "url": "https://ci.swissuplabs.com/api/packages.json"
        },
        "swissupartifacts": {
            "type": "artifact",
            "url": "/home/XXXXXXX/dev.XXXXXXX.com/vendor/swissup/artifacts"
        }
    },
    "extra": {
        "magento-force": "override"
    }
}

```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
The version field is present, it is recommended to leave it out if the package is published on Packagist.
Defining autoload.psr-0 with an empty namespace prefix is a bad idea for performance
require.dhl/shipping-m2 : exact version constraints (1.0.0) should be avoided if the package follows semantic versioning
require.magefan/module-login-as-customer : exact version constraints (2.2.5) should be avoided if the package follows semantic versioning
require.magento/product-community-edition : exact version constraints (2.3.5-p2) should be avoided if the package follows semantic versioning
require.magento2translations/language_el_gr : unbound version constraints (dev-master) should be avoided
require.swissup/argento-m2 : exact version constraints (1.20) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.13
PHP version: 7.3.20
PHP binary path: /opt/alt/php73/usr/bin/php
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017

And I expected this to happen:

Upgrade packages

**Comment by stof** [comment]
Please run the command in verbose mode (with `-v`) so that composer outputs the stack trace of the exception. Then, from that stack trace, figure out which composer plugin triggers this error and make sure you use the latest version of that plugin (to upgrade it, use `composer update my/plugin --no-plugins` to avoid getting the error).

Several plugins in the ecosystem have been discovered to assume that Symfony packages always define a `branch-alias` for `dev-master` (even though Composer does not require anything like that). And they broke when Symfony removed that branch-alias (due to starting to move away from using `master`).

There is a discussion on the Symfony commit which already lists at least 3 such plugins (old versions of `symfony/flex` even though that was already fixed *prior* to being impacted by the removal, `zaporylie/composer-drupal-optimizations` (fixed in 1.1.2) and `rubenrua/symfony-clean-tags-composer-plugin` (fixed in dev-master but not released yet))

**Comment by gino2014** [comment]
Hello stof,

thanks for your help. Could find the issue und solved. Issue was caused by composer-magento2-optimizations. But now everything is working fine again.
Thanks again.
