### ISSUE TITLE
Iterating over empty variable

### ISSUE THREAD

**Issue by ondrejmirtes** [composer/composer#9277]
Just a heads-up: The latest dev version of PHPStan (soon to be released as 0.12.49) found a bug in InitCommand.php:

```
 ------ ------------------------------------------------------ 
  Line   src/Composer/Command/InitCommand.php                  
 ------ ------------------------------------------------------ 
  460    Empty array passed to foreach.                        
  463    Call to function unset() contains undefined variable  
         $requiredPackage.                                     
 ------ ------------------------------------------------------ 
```

The code in question: https://github.com/composer/composer/blob/df22988003ed00fe39988bd3335f0c56e2b407ae/src/Composer/Command/InitCommand.php#L460-L463

The truthy `$requires` is eliminated a few lines above in `if ($requires)` that ends with `return $result`.

The foreach on line 460 can probably just be deleted, or maybe it's meant to mean something else and needs to be modified :)

**Comment by Seldaek** [comment]
Thanks, good catch for sure, I'll look into it.
