### ISSUE TITLE
Composer 2 stable release date?

### ISSUE THREAD

**Issue by greg-1-anderson** [composer/composer#9281]
Composer 2.0.0-RC1 has been working very well in the field. I was wondering if the maintainers have considered when the stable release might be tagged? An estimated availability date would be very helpful for planning purposes.

**Comment by Seldaek** [comment]
It got a bit of a delay due to a 2 week vacation, but I definitely want to get an RC2 out this week. Looking at stats it seems I can't convince enough people to try it out as long as they don't get it installed by default.. so yeah barring any bad issue report I think it'd be about time to just call it stable late october and see how that goes :)

**Comment by Seldaek** [comment]
https://github.com/composer/composer/releases/tag/2.0.0-RC2 is out - that's a first step :)

**Comment by greg-1-anderson** [comment]
I don't want to add any pressure or feelings of obligation or anything like that, but if we're now down to the point where you're just deciding the right time for the stable release, having it in ~ 1 week would make a big difference vs having it in 2 weeks or more vis-a-vis the upcoming Drupal 9.1.0 stable release. Where we are at right now is that Drupal 8 and Drupal 9 work with Composer 2 for end-users, but Drupal is still using Composer 1.x and composer/semver 1.x for internal uses, e.g. the test suite. With a stable release of Composer 2, then we could test with Composer 2 libraries in the unit tests and upgrade to composer/semver 3.x. The later will unblock a small number of modules (e.g. Violinist and similar Composer-centric modules) from using Composer 2.

Don't sweat it, though; we might still be able to squeeze C2 in late even with an end-of-October stable release, and if we do not, the inconvenience is not great, and can be resolved in another six months with 9.2.

**Comment by Seldaek** [comment]
My current plan is to release on October 27th. I have to be able to focus the few days after the release on bugfixing etc as I'm sure tons of people are not testing it yet but will somehow manage to auto-update to it accidentally the instant it's released stable and then freak out with x or y not working.. If you can't work with the current RC until then I'm afraid that's that :)

**Comment by greg-1-anderson** [comment]
It's good to know what the schedule is. We can't change our date, but there are things we can do to adjust.

**Comment by Seldaek** [comment]
Looks like we might pull off October 24th to get a smoother weekend ramp up and avoid dropping this on a weekday. Not sure if it helps you @greg-1-anderson.

**Comment by andypost** [comment]
FYI at November 2 beta of Drupal scheduled, so there's a chance to get it in before beta https://www.drupal.org/about/core/policies/core-release-cycles/drupal-core-release-cycle-major-minor-and-patch-releases#current-development-cycle

Btw composer is a dev-dependency of core but it blocks update to semver 2+ which is required dependency

**Comment by Seldaek** [comment]
2.0.0 is out! 🥳

**Comment by andypost** [comment]
Thank you! Great write-up https://blog.packagist.com/composer-2-0-is-now-available/

**Comment by gitressa** [comment]
Thank you @Seldaek! The improvements in performance are pretty impressive:

Command | Composer 1 | Composer 2 | Faster
--- | --- | --- | ---
create-project drupal/recommended-project | 10.782s | 2.118s | ~5x
require drush/drush | 21.190s | 8.030s | ~2.5x
require drupal/admin_toolbar | 15.681s| 2.862s | ~5.5x

**Comment by snetcher** [comment]
Thank You!!!
