### ISSUE TITLE
Store installed version in a package directory

### ISSUE THREAD

**Issue by Chi-teck** [composer/composer#9282]
### Problem/Motivation

This is a fairly common task to determine programatically what version of a particular package was installed. Currently the most used approach is manually setting [PHP constants](https://github.com/twigphp/Twig/blob/v3.0.5/src/Environment.php#L41-L46). Unforunetly, that requires some tedious work when publishing releases and [pollution git history](https://github.com/twigphp/Twig/commits/v3.0.5/src/Environment.php). Also that may cause [bugs](https://github.com/twigphp/Twig/pull/2945).

### Proposed resolution
Store installed version somewhare in package directory

Posible solutions:
1. Create some text or json file. For example drupal.org packaging script appends the following information to module info file.
```
# Information added by Drupal.org packaging script on 2019-10-29
version: '8.x-2.0'
project: 'admin_toolbar'
datestamp: 1572370993
```

2. Automatically replace placeholders inside package code.
```php
const VERSION='[PACKAGE_VERSION]';
```
This approach is used in [box](https://github.com/box-project/box/blob/master/doc/configuration.md#git-tag-placeholder-git-tag) library.

3. Generate a simle PHP class within package root directory under `Composer` name space. Something like this.
```php
<?php

namespace Composer\twig\twig;

final class Version {
    const VERSION = '3.0.5';
    const VERSION_ID = 30005;
    const MAJOR_VERSION = 3;
    const MINOR_VERSION = 0;
    const RELEASE_VERSION = 5;
    const EXTRA_VERSION = '';
}
```

**Comment by Seldaek** [comment]
We are not going to add constant replacement, but Composer 2 comes with new a new class to help solve this: https://getcomposer.org/doc/07-runtime.md#knowing-a-package-s-own-installed-version
