### ISSUE TITLE
Should there be version specific documentation?

### ISSUE THREAD

**Issue by JakoD** [composer/composer#9287]
I recently stumbled over the problem, that there are already flags and config options in the live documentation that only relate to the upcoming version 2, which I thought I could already use in my existing composer version 1 setup.
Today while scanning through the changelog for the alpha releases, I got reminded of this and also saw this issue #9237, so there is definitely confusion about what flags are available and it's not just me.

The question came to my mind if the documentation should:
- be a complete set of pages per version. \
 (so for example https://getcomposer.org/doc/latest/03-cli.md and https://getcomposer.org/doc/2.0.0-rc1/03-cli.md instead of just https://getcomposer.org/doc/03-cli.md) \
Depending on the current setup this could be a larger change. Also adding documentation fixes for old versions might be tricky with this approach.

- state the version which added support on a per flag / per config basis. \
This would be rather easy to implement as it is only textual changes, but might add visual clutter very fast.

- stay as is. \
Post 2.0.0 release may ease the situation a bit since new projects will hopefully use the new version. But old project likely won't upgrade immediately while still requiring and updating packages, so they would have to use a documentation page which doesn't reflect the composer version they are using.

**Comment by Seldaek** [comment]
It is a bit worse than usual right now with 2.0 taking so long to come out, but that's soon resolved, and otherwise IMO it's just not really worth the trouble of implementing this for the few cases where it actually leads to confusion. I know not everyone agrees with me but unless someone is willing to do the work that's that :)
