### ISSUE TITLE
GitDriver requires a usable cache directory

### ISSUE THREAD

**Issue by roukmoute** [composer/composer#9288]
Since composer 1.10.10 on Windows with option `no-cache`, I've got this error:

```sh
composer create-project --repository=https://git.private.repo private/skeleton --profile --no-cache
```

```sh
  [RuntimeException]
  GitDriver requires a usable cache directory, and it looks like you set it to be disabled
```

How can I resolve this?

**Comment by Seldaek** [comment]
Yeah.. it requires a cache dir to clone into so the data can be read from. The only alternative I see is to point the repository to a local clone of the repo but for a create-project I suspect this is not what you want.

Anyway I am not sure how you expect this to be resolved. As far as I can tell it's been like that for over two years.. https://github.com/composer/composer/commit/02ceb74151eb027cf74c17059dfb80a1af1a088d#diff-2f30cd17b349980f47ee8a67d55275661817b5a07f38395d7946140cf7660341

**Comment by roukmoute** [comment]
Ok thanks!

So it works only on linux and Windows and Mac are problematic, is it ok for you with this?

**Comment by stof** [comment]
@roukmoute I don't understand your comment. A usable cache directory is required on all OS when you use a git repository rather than a repository allowing to fetch metadata from an API (a composer repository, or a github/gitlab/bitbucket vcs repository).

**Comment by roukmoute** [comment]
Because on Linux i have not this problem, it works.

**Comment by tomatov-net** [comment]
Have same problem with `composer install --no-cache`

**Comment by Seldaek** [comment]
@tomatov-net please show a stack trace, and the full output of the command you're running. If you're installing from a lock file this should not happen, but I suspect you either have no lock file (which means running an update) or something else is going on.

**Comment by roukmoute** [comment]
Does not work anymore on linux with composer 2
