### ISSUE TITLE
Make it possible to override preferred install for create-project command

### ISSUE THREAD

**Issue by alexander-schranz** [composer/composer#9289]
My `composer.json`:

```json
None
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.15
PHP version: 7.4.11
PHP binary path: /usr/local/Cellar/php/7.4.11/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

My `~/composer/config.json`:

```json
{
    "config": {
        "preferred-install": {
            "sulu/*": "source",
            "l91/*": "source",
            "handcraftedinthealps/*": "source",
            "massive/*": "source"
        }
    }
}
```

When I run this command:

```bash
composer create-project sulu/skeleton
```

I get the following output:

*In this case it will create the project using `source` mode and will not remove the file which are defined in [.gitattributes](https://github.com/sulu/skeleton/blob/2.1.2/.gitattributes)*

And I expected this to happen:

*I would like an option that does use `--prefer-dist` for `create-project` e.g.:*

```json
{
    "config": {
        "preferred-install": {
            "sulu/*": "source",
            "l91/*": "source",
            "handcraftedinthealps/*": "source",
            "massive/*": "source"
        },
        "preferred-create-project": {
            "*": "dist"
        }
    }
}
```

**Comment by Seldaek** [comment]
As far as I can tell from the code it should respect the default set globally if you set * to dist in preferred-install.. Should there be a special one for just create-project.. I don't really see why?

**Comment by alexander-schranz** [comment]
> Should there be a special one for just create-project.. I don't really see why?

I'm using "source" so that my `vendor/` of my packages contains the git repository, so I can easier create bugfixes there without the need to clone that specific version into another directory.

But when I'm using `create-project` I want that the `.gitattributes` file is taken into account as I'm creating a new client project. I see a lot sulu projects also in our partner agency, which still contains the files like travis/appveyor/.github which are not used still exist there because they used similar composer settings. So it would be great to have a global setting for create-project. 

Another solution for me would be that `composer` would handle the `.gitattributes` file and remove the one which are set as [export-ignore](https://github.com/sulu/skeleton/blob/37655b2a45d16071fd4eb81bc852619e2d00b5db/.gitattributes#L1-L6) when creating a new project. Currently I think this is handled by github as github does not add this file to the zip download?

**Comment by Seldaek** [comment]
Ok, but so if it's to be used by other people IMO the best would be to recommend they use the --prefer-dist flag when calling create-project, rather than configuring stuff globally.. Because that's unlikely they'll have it set up globally? Also it should by default pick dist for stable releases, the issue is you have it set to source so you change the default.

It just seems a bit like a niche use case to add a new config setting here..

**Comment by alexander-schranz** [comment]
@Seldaek I understand you. For me it was just unexpected that `create-project` behaves different when this was configured. I personally would have expected that it only did effect install/update command. Its okay for me personally using `--prefer-dist` but its just not easy to make awareness for it for other developers which do not have so much experience.

**Comment by Seldaek** [comment]
Yeah I see your point it's maybe a bit unexpected, but on the other hand it's been like that forever so I'm not sure if it'd be wise to change that now. I doubt most people configure their global preferred-install though, so for most devs it probably just works?

**Comment by alexander-schranz** [comment]
I think most devs don't need preferred-installed as most just create projects and don't have public repositories they maintain and so don't get into this kind of things.

Is okay for me if you don't want to change the behaviour, I think I will workaround with a create-project hook which will remove the files based on the .gitattributes file. Feel free to close the issue.

**Comment by Seldaek** [comment]
Ok sounds good to me. Or you could do a bash alias like `createproj='composer create-project --prefer-dist'`? :D

**Comment by alexander-schranz** [comment]
@Seldaek good idea need to spread a bash alias to create sulu projects 👍
