### ISSUE TITLE
create-project yields different result between v1 & v2

### ISSUE THREAD

**Issue by nicolas-grekas** [composer/composer#9292]
`composer create-project symfony/skeleton test-cc 5.2.x-dev`

this installs the beta of symfony components with composer v2, and installs them in their 5.x state with composer v1.
Both behaviors can be argued as correct. Which one is desired? I'm reporting in case this is unexpected.

**Comment by Seldaek** [comment]
`composer update --no-plugins` in test-cc installs the 5.x-dev then, so I am suspecting this is a flex compat issue with v2.. Most likely it's filtering too much still, or something along those lines. Do you really need this version filtering? Is it really that valuable for v2 still?

**Comment by nicolas-grekas** [comment]
> I am suspecting this is a flex compat issue with v2

Oh, some filtering in flex which happens differently on v1, thanks for having a look, it's on me now.

> Do you really need this version filtering? Is it really that valuable for v2 still?

Yes, it's critical to control the version of transitive symfony packages.

**Comment by Seldaek** [comment]
I am guessing that the issue is you filter on `5.2.*` and 5.x-dev resolves to `5.9999999.9999999.9999999-dev` which is not in `5.2.*`. I am not sure why that'd work in composer 1 though.
