### ISSUE TITLE
"repositories" property in schema should be `anyOf` and not `oneOf`

### ISSUE THREAD

**Issue by gmazzap** [composer/composer#9295]
I'm using Private Packagist and my `composer.json` looks like this:

```json
{
    "name": "example/example",
    "description": "An example",
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.packagist.com/my-company/"
        },
        {
            "packagist.org": false
        }
    ]
}
```

That is what is suggested by Private Packagist.

However, my IDE says that is wrong:

![schema](https://user-images.githubusercontent.com/2208282/96172975-74a45500-0f27-11eb-8cf3-b2f14d654072.jpg)

I found out that Composer schema uses [**`oneOf`**](https://json-schema.org/understanding-json-schema/reference/combining.html#oneof) for [`repositories` property](https://github.com/composer/composer/blob/master/res/composer-schema.json#L386-L394) but I think it should be [**`anyOf`**](https://json-schema.org/understanding-json-schema/reference/combining.html#anyof) because the boolean variant and the object variant are not mutually esclusive.

Glad to send a PR if wanted.

**Comment by naderman** [comment]
For the record there is also https://youtrack.jetbrains.com/issue/WI-55746 regarding the PHPStorm error thrown, but I guess the error may actually be correct based on what you are saying.

**Comment by gmazzap** [comment]
Yes, I think that PHPStorm is correct in saying that's an error because using `oneOf` the schema is saying _the items of the array must be **either** an object of type "repository" or an object with a single property that is false, not both".
