### ISSUE TITLE
[Question] Does Composer automatically self-update to v2 once stable?

### ISSUE THREAD

**Issue by futape** [composer/composer#9298]
I recently got the following output to my console when running composer:

> Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is about to be released and the older 1.x releases will self-update directly to it once it is released. To avoid surprises update now to the latest 1.x version which will prompt you before self-updating to 2.x.

Does this mean, that once Composer 2.0 is released as stable and I configured stable as my release channel, composer will update itself automatically from 1.x to 2.0 (with or without prompt) after release when running any composer command or do I have to run `composer self-update` manually?

I assume, in either case, I can prevent the major upgrade by running `composer self-update --1 --set-channel-only`, right?

**Comment by stof** [comment]
you will still need to run `self-update` for any update of composer to happen. But `composer self-update` without any flag will bring you to v2.

**Comment by stof** [comment]
to be exact, composer 1.10.10+ knows how to avoid to jump to 2.x silently. This warning is shown only to older composer versions.

**Comment by Seldaek** [comment]
It will not update itself automatically, it only updates itself when `composer self-update` is called. 

Once v2 stable is out though, versions before 1.10.10 will self-update to 2.0 directly, while 1.10.10+ will only update to 1.x and if 2.0 is available it will show a warning.

**Comment by futape** [comment]
Alright, thank you for the quick feedback.
