### ISSUE TITLE
Composer 2.0.0-RC2 falsely thinks HHVM is loaded

### ISSUE THREAD

**Issue by GrahamCampbell** [composer/composer#9301]
My `composer.json`:

```json
{
    "name": "friendsofphp/php-cs-fixer",
    "type": "application",
    "description": "A tool to automatically fix PHP code style",
    "license": "MIT",
    "authors": [
        {
            "name": "Fabien Potencier",
            "email": "fabien@symfony.com"
        },
        {
            "name": "Dariusz Rumiński",
            "email": "dariusz.ruminski@gmail.com"
        }
    ],
    "require": {
        "php": "^5.6 || ^7.0",
        "ext-json": "*",
        "ext-tokenizer": "*",
        "composer/semver": "^1.4 || ^2.0 || ^3.0",
        "composer/xdebug-handler": "^1.2",
        "doctrine/annotations": "^1.2",
        "php-cs-fixer/diff": "^1.3",
        "symfony/console": "^3.4.43 || ^4.1.6 || ^5.0",
        "symfony/event-dispatcher": "^3.0 || ^4.0 || ^5.0",
        "symfony/filesystem": "^3.0 || ^4.0 || ^5.0",
        "symfony/finder": "^3.0 || ^4.0 || ^5.0",
        "symfony/options-resolver": "^3.0 || ^4.0 || ^5.0",
        "symfony/polyfill-php70": "^1.0",
        "symfony/polyfill-php72": "^1.4",
        "symfony/process": "^3.0 || ^4.0 || ^5.0",
        "symfony/stopwatch": "^3.0 || ^4.0 || ^5.0"
    },
    "require-dev": {
        "johnkary/phpunit-speedtrap": "^1.1 || ^2.0 || ^3.0",
        "justinrainbow/json-schema": "^5.0",
        "keradus/cli-executor": "^1.2",
        "mikey179/vfsstream": "^1.6",
        "php-coveralls/php-coveralls": "^2.1",
        "php-cs-fixer/accessible-object": "^1.0",
        "php-cs-fixer/phpunit-constraint-isidenticalstring": "^1.1",
        "php-cs-fixer/phpunit-constraint-xmlmatchesxsd": "^1.2",
        "phpunit/phpunit": "^5.7.27 || ^6.5.14 || ^7.1",
        "phpunitgoodpractices/traits": "^1.8",
        "symfony/phpunit-bridge": "^5.1",
        "symfony/yaml": "^3.0 || ^4.0 || ^5.0"
    },
    "suggest": {
        "ext-dom": "For handling output formats in XML",
        "ext-mbstring": "For handling non-UTF8 characters.",
        "php-cs-fixer/phpunit-constraint-isidenticalstring": "For IsIdenticalString constraint.",
        "php-cs-fixer/phpunit-constraint-xmlmatchesxsd": "For XmlMatchesXsd constraint.",
        "symfony/polyfill-mbstring": "When enabling `ext-mbstring` is not possible."
    },
    "config": {
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "PhpCsFixer\\": "src/"
        },
        "classmap": [
            "tests/Test/AbstractFixerTestCase.php",
            "tests/Test/AbstractIntegrationCaseFactory.php",
            "tests/Test/AbstractIntegrationTestCase.php",
            "tests/Test/Assert/AssertTokensTrait.php",
            "tests/Test/IntegrationCase.php",
            "tests/Test/IntegrationCaseFactory.php",
            "tests/Test/IntegrationCaseFactoryInterface.php",
            "tests/Test/InternalIntegrationCaseFactory.php",
            "tests/Test/IsIdenticalConstraint.php",
            "tests/TestCase.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "PhpCsFixer\\Tests\\": "tests/"
        }
    },
    "bin": [
        "php-cs-fixer"
    ]
}

```

When I run this command (PHP 7.4, Ubuntu 20.04 GH actions):

```
composer update
```

I get the following output:

```
  Problem 1
    - hhvm is present at version 4.78.0 and cannot be modified by Composer
    - hhvm 4.78.0 conflicts with phpunitgoodpractices/traits v1.8.0.
    - Root composer.json requires phpunitgoodpractices/traits ^1.8 -> satisfiable by phpunitgoodpractices/traits[v1.8.0].
```

And I expected this to happen:

To resolve deps.

Interestingly, this doesn't happen on Windows or MacOS. Just Linux: https://github.com/GrahamCampbell/PHP-CS-Fixer/actions/runs/313798090.

**Comment by GrahamCampbell** [comment]
I'll need to do some more debugging later to provide you with a more minimal example...

**Comment by Seldaek** [comment]
Unfortunately due to latest HHVM not being able to execute composer anymore, we currently have a [hack in place](https://github.com/composer/composer/blob/master/src/Composer/Platform/HhvmDetector.php#L48-L52) that adds the hhvm platform package as soon as the hhvm executable is present on the machine.

So one suggestion workaround for CI is to maybe `sudo rm $(which hhvm)`.. 

Also as far as I know this should be an issue with Composer 1.10 too.

@fredemmott any clue what the status is here? https://github.com/composer/composer/pull/7913 mentioned this was a temporary solution, but it's been almost two years :) I don't know if HHVM users still rely on/need this or not?

**Comment by fredemmott** [comment]
We're still depending on it; we were planning to move to either Yarn or Etsy, but their plans have changed and we don't fit so easily in now.

I'm looking for another alternative approach  - either a less annoying change to composer, or a different package manager that isn't "make yet another package manager just for hack"; I'd appreciate any suggestions here.

**Comment by GrahamCampbell** [comment]
Why isn't Composer a good option for hack projects?

**Comment by GrahamCampbell** [comment]
A composer plugin could be implemented (I think), to generate hack autoload files, instead of `.php`.

**Comment by fredemmott** [comment]
Autoloading is a solved problem; the big one is that HHVM is no longer a PHP runtime, and composer isn’t designed to support multiple languages - for example, it doesn’t make sense to have a single project with both hack and PHP dependencies.

**Comment by GrahamCampbell** [comment]
Composer could be exclusively used to load hack dependencies though? The "php" requirement should just never be listed in packages, and composer should be instructed to ignore the current platform via `--ignore-platform-reqs`. The only piece that's missing is telling composer what version of HHVM you want, I suppose, so it can do proper platform resolution instead of ignoring hhvm version constraints.

**Comment by Seldaek** [comment]
@GrahamCampbell hhvm constraints work too. There is no problem with HHVM using Composer.

The only issue is with packages conflicting with hhvm, if you do have hhvm installed on the machine. People in the PHP ecosystem should simply not conflict against HHVM anymore as it makes no sense, because HHVM can not execute their code anymore.

phpunitgoodpractices/traits now has a release fixing this, so I guess this issue can be closed.

@fredemmott Sorry but I don't have a better suggestion for you. I don't really mind the workaround we have in place now.

**Comment by GrahamCampbell** [comment]
It looks like the conflict information is actually incorrect? That package does not directly conflict with HHVM?

```
  Problem 1
    - hhvm is present at version 4.79.0 and cannot be modified by Composer
    - hhvm 4.79.0 conflicts with php-cs-fixer/accessible-object v1.0.0.
    - Root composer.json requires php-cs-fixer/accessible-object ^1.0 -> satisfiable by php-cs-fixer/accessible-object[v1.0.0].
```

**Comment by fredemmott** [comment]
If everyone's OK with this being a semi-long-term strategy, perhaps adding an optional `"language": "php"`, `"language": "hack"` field to composer.json might be nice? No real understanding of the value would be necessary for this to be useful - just a requirement that it has the same value (or is omitted) for all projects in the current dependency tree?

**Comment by Seldaek** [comment]
I think we could use a require on hhvm as a marker for hack projects? And use that to enable the hhvm binary/version detection and perhaps also remove all other packages from the platform repo if that's the case, that'd automatically prevent anything requiring php from being installed. Does that sound workable on your end?
