### ISSUE TITLE
Composer 2 doesn't fetch package when it is "provided" by some dependency

### ISSUE THREAD

**Issue by andrew-demb** [composer/composer#9308]
My `composer.json`:

```json
{
    "name": "gh/issue",
    "require": {
        "php-http/socket-client": "^2"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.0-RC2
PHP version: 7.4.11
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
cURL version: 7.64.0 libz 1.2.11 ssl OpenSSL/1.1.1g
zip extension: not loaded
```

When I run this command:

```
composer update
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies
Lock file operations: 10 installs, 0 updates, 0 removals
  - Locking nyholm/psr7 (1.3.1)
  - Locking php-http/httplug (2.2.0)
  - Locking php-http/message-factory (v1.0.2)
  - Locking php-http/promise (1.1.0)
  - Locking php-http/socket-client (2.0.1)
  - Locking psr/http-factory (1.0.1)
  - Locking psr/http-message (1.0.1)
  - Locking symfony/deprecation-contracts (v2.2.0)
  - Locking symfony/options-resolver (v5.1.7)
  - Locking symfony/polyfill-php80 (v1.18.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 10 installs, 0 updates, 0 removals
  - Installing psr/http-message (1.0.1): Extracting archive
  - Installing php-http/message-factory (v1.0.2): Extracting archive
  - Installing php-http/promise (1.1.0): Extracting archive
  - Installing symfony/polyfill-php80 (v1.18.1): Extracting archive
  - Installing symfony/deprecation-contracts (v2.2.0): Extracting archive
  - Installing symfony/options-resolver (v5.1.7): Extracting archive
  - Installing php-http/socket-client (2.0.1): Extracting archive
  - Installing php-http/httplug (2.2.0): Extracting archive
  - Installing psr/http-factory (1.0.1): Extracting archive
  - Installing nyholm/psr7 (1.3.1): Extracting archive
Generating autoload files
4 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

And I expected this to happen: 
package `psr/http-client` installed and this code shows `bool(true)`
```php
<?php

require __DIR__ . '/vendor/autoload.php';

var_dump(interface_exists(\Psr\Http\Client\ClientInterface::class));
```

If I run `composer update` with composer 1.10.5 it successfully installs `psr/http-client`.

Possible source of issue:
`php-http/socket-client` provide package `psr/http-client`
https://github.com/php-http/socket-client/blob/3db137a526c467b52d8d743f5c2f7fdcc00362ef/composer.json#L26

**Comment by stof** [comment]
well, if a package provides another one, it means that installing it provides the code of the other one. If `php-http/socket-client` lies about what it provides, composer cannot be blamed for respecting that lie.

**Comment by stof** [comment]
however, the fact that Composer 2 does not do the same than Composer 1 is indeed weird.

**Comment by andrew-demb** [comment]
Should we fix more packages that follow the same error?
https://packagist.org/providers/psr/http-client

**Comment by stof** [comment]
@andrew-demb yeah. Any package which does not contain the code of the `Psr\Http\Client\ClientInterface` would be buggy if it says it provides the package (and packages which do contain the interface should rather be refactored to depend on the official package instead)

**Comment by stof** [comment]
@Seldaek @naderman IIRC, in Composer 1, a `provide` rule will only satisfy a package requirement if no package with the exact name is available to satisfy it. Is this behavior gone in 2.x ? I'm quite sure that this rule is the reason why these packages were working in Composer 1.

**Comment by naderman** [comment]
The package php-http/socket-client requires psr/http-client and also provides it. This is quite pointless, as the requirement is automatically met by the package itself providing the very thing it requires.

Composer1 due to some weird quirks did in some cases like this install the actual package by that name anyway (yes @stof providers were ignored if an actual package by the name existed, mostly because providers were all loaded through a single file in the Composer repo). As of Composer2 we no longer have this special behavior of ignoring provide definitions for packages which actually exist. If something claims to provide another package, Composer trusts it to actually do so.

The fix in this case will be to remove the false provide statement from php-http/socket-client, the package will then work fine in Composer1 and Composer2.

So for Composer2 this isn't a bug and for Composer1 it's somewhat defined misbehavior, that we're not going to change anymore either, so closing this ticket.

**Comment by stof** [comment]
> As of Composer2 we no longer have this special behavior of ignoring provide definitions for packages which actually exist. If something claims to provide another package, Composer trusts it to actually do so.

but this means that any package can cause to remove a package that you explicitly require by listing it in `provide` (here, we do have an explicit requirement on a `psr/htttp-client` package that exists). IIRC, the rule of preferring an exact match of the name over a provider package was added as a security measure too.

**Comment by naderman** [comment]
That was definitely not a security measure, and yes, that is what it means.

**Comment by naderman** [comment]
And it's not like any package can do it. only packages you explicitly require somewhere even get loaded. So you have to explicitly require a package which contains the provide.
