### ISSUE TITLE
Composer2 and proxies

### ISSUE THREAD

**Issue by johnstevenson** [composer/composer#9314]
I've been testing proxy support in Composer2 and discovered a few issues. I'll PR something to address these, with suggested solutions outlined below. Comments, criticisms and ideas very welcome.

# 1. curl
Composer2 does not specifically set proxy options for curl, but relies on curl picking up proxy environment variables. Curl uses a `[scheme]_proxy` system to determine if a request should be proxied which leads to inconsistencies when the user has only one variable set, for example:

 * http_proxy: curl will not use a proxy for https requests (Composer streams will)
 * CGI_HTTP_PROXY: curl does not recognize this so will not use a proxy for any requests (Composer streams will)

There are also differences between `no_proxy` IP address handling: curl string-matches the values, while Composer does binary comparison, which allows handling CIDR ranges (similar to golang).

Additionally, in the case of a secure-proxy (see below) curl requires specific certificate options to be set.

### _Solution_
1. Determine if a proxy should be used from the environment (as currently) then set `CURLOPT_PROXY` to either:
    * the proxy url - curl will use this
    * an empty string - curl won't use a proxy or read the environment

2. For secure-proxies, set `CURLOPT_PROXY_CAINFO` or `CURLOPT_PROXY_CAPATH `

Note that curl does not understand `HTTP(S)_PROXY_REQUEST_FULLURI` environment variables, but they are irrelevant as curl uses the full uri where appropriate.

# 2. Secure proxy support
A secure HTTP proxy is one that only accepts encrypted TLS connections, compared to a basic HTTP proxy which accepts unencrypted connections. Both types allow a client to make http and https requests to an origin-server.

The table shows current PHP built-in proxy handling capabilities:

|             | basic-proxy >http | basic-proxy >https | secure-proxy >http | secure-proxy >https |
|-------------|-------------------|--------------------|--------------------|---------------------|
| php streams | Yes               | Yes                | Yes                | No                  | 
| php curl    | Yes               | Yes                | *PHP 7.3 ?          | *PHP 7.3 ?          |

* curl needs the `CURL_VERSION_HTTPS_PROXY` feature (added in curl 7.52.0, Dec 2016). This constant was added in PHP 7.3 which allows checking for this feature.

Although rare, secure-proxies do exist. For _secure-proxy >https_, PHP will error with : `SSL/TLS already set-up for this stream` (see issue #6294) because it only uses a single connection - and this is already TLS enabled from connecting to the proxy. 

### _Solution_
A few ideas if there is no curl _secure-proxy >https_ support:
* If the server allows http, downgrade the request to _secure-proxy >http_ and use PHP streams. Note that this will fail if the origin-server responds with a redirect to an https resource.
* Otherwise let it fail and make `diagnose` report this stuff.

Note that writing a php client to do _secure-proxy >https_ is complex and defeats the objective of using curl.

# 3. request_fulluri
The PHP manual for [HTTP context options request_fulluri](https://www.php.net/manual/en/context.http.php) states: 
> When set to TRUE, the entire URI will be used when constructing the request. (i.e. `GET http://www.example.com/path/to/file.html HTTP/1.0`). While this is a non-standard request format, some proxy servers require it. 

However the HTTP 1.0 spec (1996) mandates that the [entire URL](https://tools.ietf.org/html/rfc1945#section-5.1.2) must be used for proxies: 
>The absoluteURI form is only allowed when the request is being made to a proxy.

So rather than being 'a non-standard request format' it is actually the required format for **http** requests to a proxy. Note that https requests through a proxy are handled differently, as described below.

## http requests
Composer sets request_fulluri to true and allows the user to disable it with `HTTP_PROXY_REQUEST_FULLURI`. This is good because by default a  HTTP/1.0+ compliant request is sent to the proxy, which carries out the request on the client's behalf and returns the response.

It would need a very screwed up/old proxy not to accept such a request. Interestingly `HTTP_PROXY_REQUEST_FULLURI` was added to solve a problem with https requests, as described below, rather than http requests to useless proxies.

Additionaly, curl does not recognize this value and always uses the full uri.

## https requests
The request_fulluri value has no relevance to the proxy's involvement in the transaction, which is to set up a tcp tunnel to the origin-server in response to a `CONNECT` request from the client.

The client (PHP) then continues with the request as if it had set up the connection itself. If request_fulluri is true, PHP will send a non-compliant HTTP/1.0+ request to the origin-server (which SHOULD, but doesn't have to, accept it). The proxy's involvement at this stage is to pipe byte streams (in this instance encrypted) back and forth between the client and the origin-server.

This PR https://github.com/composer/composer/pull/1825 is a result of such non-compliant requests being refused (to https://api.github.com) and adds `HTTP_PROXY_REQUEST_FULLURI`  for disabling request_fulluri on http and https requests.

Composer1 sets request_fulluri to true and allows the user to disable it with `HTTPS_PROXY_REQUEST_FULLURI`, while Composer2 sets it to true only if  `HTTPS_PROXY_REQUEST_FULLURI` is truthy.

If a user really needs to set this, then it would mean that either an origin-server doesn't recognize compliant HTTP requests (which would make it essentially useless), or that a MITM proxy is involved, decrypting the payload and getting stuff wrong. 

### _Solution_
* Deprecate and ignore `HTTP_PROXY_REQUEST_FULLURI` and keep on setting request_fulluri to true for http requests. curl doesn't recognize it or offer a similar option, which it probably would if there were proxies out there that required a non-compliant request.
* Deprecate and ignore `HTTPS_PROXY_REQUEST_FULLURI`. It really has nothing to do with proxies and curl doesn't recognize it or offer a similar option (because it doesn't make any sense).
* Alternatively, keep one or both and jump through a few hoops to switch from curl to streams if appropriate or fail if not.

@Seldaek Could particularly do with your thoughts on this bit. I've scoured all the proxy related issues and the only thing in common seems, to me at least, that there is really nothing in common. I think that PHP's misleading description and non-compliant implementation (by not automatically using the full uri in non-CONNECT requests) has lead to this confusion.

**Comment by Seldaek** [comment]
First thanks for the diligent work on this. You seem to have a way better grasp of this than I do, so I mostly trust your conclusion here.. 

1. your solution sounds good. See `CurlDownloader::$options` for a way to map StreamContextFactory return value to curl options. CGI_HTTP_PROXY I don't really know why it's there nor if we should care, but I guess should be handled by the proposed solution. 

2. In the few (about 2% atm) requests from composer 2 we have, there are definitely some curl <7.52 in there, tho not the majority.. But IMO almost no origins allow HTTP at this point, or if they do it really should not be used anyway.. especially if the URL to download is HTTPS, we shouldn't downgrade silently. So I think I'd rather let this fail hard with a proper error (mentioning curl version, minimum version needed, and the fact that secure proxies + HTTPS are not supported without that..).

3. yes HTTP*_PROXY_REQUEST_FULLURI are probably not needed anymore now that we figured out the correct defaults.. which indeed should be the defaults in PHP.

Sorry for the rush but do you think you can PR this today or tomorrow latest? It'd be great to get it in 2.0.0 to avoid changing this again after.

**Comment by johnstevenson** [comment]
> so I mostly trust your conclusion here..

I had this stuff nearly ready about 2 weeks ago, but to be absolutely certain I knocked up my own php proxy so I could see exactly how it all works, particularly the _secure-proxy > https stuff_. I tested it with multiple clients -curl cli, php, ruby, .net etc, even php running in a debugger.

I hope that makes you feel better! 

> So I think I'd rather let this fail hard with a proper error 

But where though? Is this a `Composer\Exception\NoSslException` type show-stopper, as per Factory::createHttpDownloader()? In which case I could get HttpDownloader to throw a `TransportException` on construction.

PR on its way later (as in today), but one question about StreamContextFactory::initOptions() where I'm pretty certain that the following lines are no longer needed:

https://github.com/composer/composer/blob/492bece6e28310901ea678cfe6f119d67d60b425/src/Composer/Util/StreamContextFactory.php#L133...#L139

They were added in Dec 2014 (https://github.com/composer/composer/commit/8dad8466136e58a595bd74f866f201a219d44936) and are only effective if there **is** a proxy, which seems wrong. Subsequently
getOptionsFor Url sets the SNI_server_name (added in Jan 2016 from https://github.com/composer/composer/pull/4759)

It makes subsequent stuff cleaner to remove this bit first, so if you agree, do you want a separate PR or should I include it in the main upcoming PR?

(The php proxy demo is here, should anyone care: https://github.com/johnstevenson/proxy-demo)

**Comment by stof** [comment]
> It makes subsequent stuff cleaner to remove this bit first, so if you agree, do you want a separate PR or should I include it in the main upcoming PR?

have you tested that these things keep working file on old PHP versions (5.5 and older) as they are the target of this code ?

**Comment by Seldaek** [comment]
@johnstevenson IMO yes if a secure proxy is configured, and curl is too old I'd throw, but perhaps only at the point where we receive an URL which would have the proxy applied, just in case the noproxy rules end up excluding everything which is needed, who knows. So I'd probably do the check for proxy presence in the CurlDownloader if the curl version is too old.

As for the SNI support, you can see the background in https://github.com/composer/composer/issues/3204 it apparently was needed to fix a possibly borked secure proxy. If you can keep it please do, but if not I guess we can take the chance of breaking things for these very much outdated PHP versions as it would only touch proxy users.

**Comment by johnstevenson** [comment]
@stof @Seldaek Guys, I guess I haven't explained this very well:

These options have now already been set. StreamContextFactory::getTlsDefaults() sets general ssl values:

https://github.com/composer/composer/blob/492bece6e28310901ea678cfe6f119d67d60b425/src/Composer/Util/StreamContextFactory.php#L238-L246

Then RemoteFileSystem::getOptionsForUrl() sets specific stuff for the url, including `SNI_server_name` for older PHP versions:

https://github.com/composer/composer/blob/492bece6e28310901ea678cfe6f119d67d60b425/src/Composer/Util/RemoteFilesystem.php#L628-L664

To clarify: this wasn't the case at the time the proxy modifications were added.

I guess the borked proxy issue was a case of SNI not being specifically enabled at that time as well the the `400 Bad Request` response, which was solved by: "To get it working I had to set the env var: HTTPS_PROXY_REQUEST_FULLURI to false."

**Comment by johnstevenson** [comment]
> if a secure proxy is configured, and curl is too old I'd throw, but perhaps only at the point where we receive an URL 

@Seldaek I'll make it work in a similar way to streams:

https://github.com/composer/composer/blob/492bece6e28310901ea678cfe6f119d67d60b425/src/Composer/Util/StreamContextFactory.php#L111-L113

**Comment by Seldaek** [comment]
Ah yeah ok that clarifies things, then indeed looks like SNI can be removed from the proxy config bit.
