### ISSUE TITLE
[composer update] Supporting switching between packages repositories without upgrading versions

### ISSUE THREAD

**Issue by isqo** [composer/composer#9315]
I found that when a project has to fetch dependencies from different repositories separately (repositories in composer.json change depending on the environment), changing the dist url of packages in the composer.lock without impacting the version of packages is not something possible.
I think that it would be great if "composer update" had a flag like "--only-dist", allowing the switch between repositories depending on the environment without modifying the whole composer.lock .

**Comment by Seldaek** [comment]
You can do `composer update mirrors` I think that should do what you're after.

**Comment by isqo** [comment]
@Seldaek i think that `composer update mirrors` update versions in composer.lock, it is is exactly the same as  `composer update --lock`

**Comment by Seldaek** [comment]
Yes it's the same.. But it should not update to new versions? Can you try it with composer 2? `composer self-update --snapshot` gets you the latest build.

**Comment by isqo** [comment]
@Seldaek thanks for the suggestion, it resolved my problem.
I think that the doc of the option "--lock" lacks a little bit of clarity, it would be good if we change it to something more precise like:
* **--lock:** Updates the lock file hash to suppress warning about the lock file being out of date and also updates the packages' mirrors if they change, keeping the same versions installed.
