### ISSUE TITLE
composer clear-cache method but keeping the current version of required packages.

### ISSUE THREAD

**Issue by VincentLanglet** [composer/composer#9319]
I recently had storage issues on my server and discovered that composer cache is taking a lot of place.
I ran `composer clear-cache`, but then, obviously, `composer install` took more time the first time.
Is there a way to keep the current version of downloaded package when running `clear-cache`.

WDYT about adding an option ?

**Comment by Seldaek** [comment]
That's not really possible as we do not store the version, only the reference for cached zip files, so we don't actually know which is the latest. And anyway the first install is a bit slower, not the end of the world I'd think. Especially now with Composer 2 downloading in parallel it should be faster anyway.
