### ISSUE TITLE
Windows, vendor binaries and the proxy script

### ISSUE THREAD

**Issue by fritzmg** [composer/composer#9325]
Currently Composer handles installation of binaries in a special way when run in a Windows environment:

* A `.bat` file is generated automatically to reference the binary
* _A Unix-style proxy file with the same name as the binary is generated automatically (useful for Cygwin or Git Bash)_

https://getcomposer.org/doc/articles/vendor-binaries.md#what-about-windows-and-bat-files-

I am wondering why Composer creates the proxy file at all, instead of creating a relative symlink to the actual bin file, just like on Linux. There does not seem to be any benefit to having the proxy file. Instead it prevents you from using a specific PHP CLI:

* When using the Windows CMD, executing `vendor\bin\the-bin-file` will automatically use the `vendor\bin\the-bin-file.bat` file.
* When using the Git Bash etc., executing `vendor/bin/the-bin-file` will execute said proxy shell script.
* **However**, when using _either_ the Windows CMD _or_ Git Bash etc. executing `php vendor/bin/the-bin-file` or `php vendor\bin\the-bin-file` respectively will not work in either case, because PHP of course cannot interpret a shell script and just outputs its content.

If instead I manually create the relative symlink on Windows to the PHP binary (example with the Contao Managed Edition binary):

<img src="https://user-images.githubusercontent.com/4970961/96996210-635ed800-1527-11eb-897e-35a4b037cc7f.png" width="665">

everything works as expected, both in the Windows CMD:

<img src="https://user-images.githubusercontent.com/4970961/96996241-6b1e7c80-1527-11eb-9018-813092d28b2b.png" width="514">

as well as in the Git Bash for example:

<img src="https://user-images.githubusercontent.com/4970961/96996320-91441c80-1527-11eb-8997-8a149cc44122.png" width="568">

So - what is the purpose of the proxy shell script? The reason I am wondering about this at all: for Contao we want to switch from using a Composer script handler to directly using a command: https://github.com/contao/contao/pull/2183

However, this currently does not work on Windows, because of the proxy shell script.

**Comment by Seldaek** [comment]
I think the issue is initially we could not create symlinks on windows due to old restrictions that were in place. This got better with more modern versions of windows and PHP, so I think now it might be an option to do this yes.

That said, in the interest of understanding your issue in more details and perhaps helping out find a workaround for current composer versions, what's the problem with running vendor/bin/the-bin-file directly? Why do you want/need to prefix it with php?

**Comment by fritzmg** [comment]
> Why do you want/need to prefix it with php?

It always needs to be prefixed with the correct PHP CLI, otherwise a wrong CLI might be used. e.g. if you execute

```
/path/to/php7.4 composer.phar install
```

then that PHP CLI should be used for all the commands as well. Otherwise a totally different CLI might be used, which might be wrong PHP version.

**Comment by Seldaek** [comment]
Ok I see, then you may want to put `@php contao-console ....` in the composer.json, that will execute it with the current PHP process. I am not 100% sure if it'll run the shell script or the original one from vendor tho, possibly you'll have the same issue, but you can give it a shot :)

**Comment by stof** [comment]
note that even on Linux systems, there is no guarantee that the `vendor/bin/*` files will be symlinks. If the creation of the symlink fails (not sure what can make it fail), a proxy script will also be used.

**Comment by fritzmg** [comment]
> I think the issue is initially we could not create symlinks on windows due to old restrictions that were in place.

Some thoughts on that:

* In order for PHP (or anything) to be able to create a symlink in Windows, the user under which the process is executed must either be an Administrator - or the user needs to have the `SE_CREATE_SYMBOLIC_LINK_NAME` permission enabled. This is not the case by default. Thus I think the proxy script still needs to be created as a fallback, if the creation of the symlink fails. For our purposes this is not a problem, since running Contao requires the environment to be able to create symlinks.

* There is a myth in the PHP community that you cannot create relative symlinks on Windows - however this is not the case. The myth origins from a bug within the Windows version of PHP where relative symlinks cannot be created as expected. This stems from the fact that the Win32API function for creating a symlink refers to the CWD for relative symlinks, rather than the directory of the target. See also https://github.com/php/php-src/pull/1243. Unfortunately this was never fixed within PHP itself, as there is little interest for Windows.

**Comment by fritzmg** [comment]
> Ok I see, then you may want to put `@php contao-console ....` in the composer.json, that will execute it with the current PHP binary. I am not 100% sure if it'll run the shell script or the original one from vendor tho, possibly you'll have the same issue, but you can give it a shot :)

Yeah, that does not work on Windows at all unfortunately ;)

```
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
82 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
contao/manager-plugin: Generating plugin class...
contao/manager-plugin: ...done generating plugin class
Symfony recipes are disabled: "symfony/flex" not found in the root composer.json

> @php contao-console contao:initialize-application --ansi
Could not open input file: contao-console
Script @php contao-console contao:initialize-application --ansi handling the post-install-cmd event returned with error code 1
```

**Comment by Seldaek** [comment]
See https://github.com/composer/composer/pull/9713 please, would be happy to get more people sanity-checking this ;)
