### ISSUE TITLE
Inconsistent value of COMPOSER_DEV_MODE in 'post-install-cmd' after update

### ISSUE THREAD

**Issue by thg2k** [composer/composer#9332]
My `composer.json`:

```json
(...)
        "post-install-cmd": [
            "echo \"ccdbg1=$COMPOSER_DEV_MODE\""
        ],
        "post-update-cmd": [
            "echo \"ccdbg2=$COMPOSER_DEV_MODE\""
        ]
(...)
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (1.10.15 => 2.0.0)
Composer version: 1.10.15
PHP version: 7.2.18
PHP binary path: /usr/bin/php
OpenSSL version: OpenSSL 1.1.0i  14 Aug 2018
```

When I run this command:

```
composer update
```

I get the following output:

```
ccdbg2=1
ccdbg1=0
```

And I expected this to happen:

```
ccdbg2=1
ccdbg1=1
```

**Comment by thg2k** [comment]
Sorry, this was a bogus report:

I just realized that `composer update` does **not** run `post-install-cmd`, I did myself the triggering of `post-install-cmd` inside my `post-update-cmd` because I thought it was logical, and I was not passing the correct flags.

**Comment by Seldaek** [comment]
If you need the same in post-install and post-update, you maybe rather want to use a reference than triggering post-install-cmd from post-update-cmd... https://getcomposer.org/doc/articles/scripts.md#referencing-scripts
