### ISSUE TITLE
Prioritizing local Composer plugins

### ISSUE THREAD

**Issue by mcaskill** [composer/composer#9333]
Hi Composer,

> ℹ️ As per @Seldaek's recommendation, this continues the discussion started in ffraenz/private-composer-installer#25.

With the introduction of Composer 2.0, a number of specialty Composer plugins are having trouble supporting the new architecture.

These Composer plugins offer a way to install private packages that do not support Composer and, more specifically, do not use standard authentication methods. Instead, they rely on URIs with sensitive credentials.

<details><summary>Example 1.0</summary>

```json
{
  "type": "package",
  "package": {
    "name": "package-name/package-name",
    "version": "1.0.0",
    "dist": {
      "type": "zip",
      "url": "https://example.com/package-name.zip?key={%PACKAGE_KEY}&version={%VERSION}"
    },
    "require": {
      "ffraenz/private-composer-installer": "^4.0"
    }
  }
}
```
</details>

Most Composer plugins catering to these private packages outsource the sensitive parts of these URIs into environment variables or a `.env` file typically ignored by version control.

For some packages, the actual URI to the archive is hidden behind APIs (like [Easy Digital Downloads](https://docs.easydigitaldownloads.com/article/384-software-licensing-api)). The download URI is often limited to the latest version of the package _and_ often expirable.

During a download operation, the plugin replaces the placeholders in the URI with the sensitive values or fetches the URI from the intermediate API. The lock file will often store a variant of this URI that contains only the replaced version number in order to maintain a consistent cache key.

<details><summary>Example 2.0</summary>

```json
"dist": {
  "type": "zip",
  "url": "https://example.com/package-name.zip?key={%PACKAGE_KEY}&version=1.0.0"
}
```
</details>

In Composer v1, this has worked rather well because of its nonconcurrent architecture where plugins would be installed first to be available to mutate the private packages' processed URIs.

With Composer v2, the operations are executed in batches, plugins first then the rest. But the downloads are executed all at once before the installs are executed. Composer will obviously fail when it hits this special placeholder-filled URI since the Composer plugin is often not available yet.

---

Currently, the possible solutions available are:

1. Install the Composer plugin globally but this isn't the most practical solution for a group of users on a project, they need to be aware of what global plugin to install (a crude example, I know).
2. Build a private Composer repository but not everyone can build and maintain one and this essentially kills these plugins.

@Seldaek has proposed to tweak the Composer install process to allow plugins to mark themselves as having to be installed ahead of time.

Being able to prioritize the availability of local Composer plugins might also be beneficial beyond URI replacements, obviously.

Thanks

---

Concerned plugins:

- [ffraenz/private-composer-installer](https://github.com/ffraenz/private-composer-installer)
- [junaidbhura/composer-wp-pro-plugins](https://github.com/junaidbhura/composer-wp-pro-plugins)
- [philippbaschke/acf-pro-installer](https://github.com/PhilippBaschke/acf-pro-installer)
- [pivvenit/acf-pro-installer](https://github.com/pivvenit/acf-pro-installer)

Parties involved: @ffraenz, @justinrainbow @Qrious

**Comment by naderman** [comment]
As per @Seldaek 's suggestion I'd say it'd be reasonable to add a new flag to composer.json's extra key to mark a plugin which modifies downloads, e.g. "extra.plugin-load-before-downloads" or "extra.plugin-modifies-downloads". These plugins would then need to get loaded before the rest of the downloads takes place at all.

**Comment by Seldaek** [comment]
Opened https://github.com/composer/composer/pull/9339 with a possible fix, I'd appreciate if you can add the `"extra": {"plugin-modifies-downloads": true}` to your composer.json and try it out using the branch.

**Comment by Qrious** [comment]
I can confirm that my integration tests now succeed with the `"extra": {"plugin-modifies-downloads": true}` added to our composer.json and the usage of the composer version provided in your branch. 🎉

**Comment by Seldaek** [comment]
Great, then let's hope this allows you all to become compatible with Composer 2 soon :)
