### ISSUE TITLE
Undefined index: name errors using Composer 2.01 for updating Laravel 6

### ISSUE THREAD

**Issue by arkid** [composer/composer#9340]
My `composer.json`:

```json
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "area17/twill": "^2.1",
        "fideloper/proxy": "^4.0",
        "kalnoy/nestedset": "^5.0",
        "laravel/framework": "6.0.*",
        "laravel/helpers": "^1.2",
        "laravel/tinker": "^1.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "3.*",
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^7.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
```

Output of `composer diagnose`:

> Checking composer.json: OK
> Checking platform settings: OK
> Checking git settings: OK
> Checking http connectivity to packagist: OK
> Checking https connectivity to packagist: OK
> Checking github.com rate limit: OK
> Checking disk free space: OK
> Checking pubkeys:
> Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
> Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
> OK
> Checking composer version: OK
> Composer version: 2.0.1
> PHP version: 7.3.7
> PHP binary path: C:\Program Files\php\7.3.7\php.exe
> OpenSSL version: OpenSSL 1.1.1c  28 May 2019
> cURL version: 7.64.0 libz 1.2.11 ssl OpenSSL/1.1.1c
> zip extension: OK

When I run this command:

> composer update

I get the following output:

> In PackageManifest.php line 122:
> 
>   Undefined index: name
> 
> Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
>

**Comment by simonberger** [comment]
Searching for this issue shows several reports of laravel users in the last months. All seemed to just downgrade to composer stable (at that time) release again.
If you can edit your `PackageManifest.php` output the current package array instead of letting it fail and/or check the `? 
`vendor/composer./installed.json` file for packages without a name property (for whatever reason). Apart from this the error happens in artisan and you should file a bug there.

**Comment by Seldaek** [comment]
Yup, please report on the https://github.com/laravel/framework repo, artisan crashes are not something we can fix.

**Comment by Seldaek** [comment]
Ok looks like this was actually fixed in https://github.com/laravel/framework/commit/65a555105f7812e87888245c8123cad027bf88df already - so make sure you update laravel to at least 6.18.7+ or 7.6.0+ or 8.0+.

Running `composer update laravel/framework` should hopefully fix this, and not cause you other problems. If you can not update laravel then you're better off downgrading to Composer 1 using `composer self-update --1`.

If you are using **illuminate/foundation** instead of laravel/framework, then make sure you `composer update illuminate/foundation` instead.

**Comment by travismorrison** [comment]
Not for nothing, but I see this issue at `laravel/framework 6.19.1`. the cited patch to laravel/framework is there. 
We're rolling back to composer 1, and I'm not here to litigate whether this is a laravel or a composer issue. Just want to question the assertion that `6.18.7+` does the trick, in case others are digging into this.

**Comment by arkid** [comment]
Thanks for the feedback everyone!   I will be updating to the latest Laravel 6 now before updating to Composer 2.

**Comment by ngocnd0242** [comment]
Return composer to version 2.x using the command
```composer self-update --rollback```

**Comment by omysurya** [comment]
refers to this https://laravel-news.com/laravel-5-6-removes-artisan-optimize

**Comment by uniquechukwuma** [comment]
This happened when i tried to run **composer install**

But i just did **composer update** and it fixed itself. 

So if any of the suggestions didn't solve your problem try this one

**Comment by ngocnd0242** [comment]
@uniquechukwuma Can you try composer version 1 and 2? What did you use compose version?
