### ISSUE TITLE
Composer breaking for php 7.3.11

### ISSUE THREAD

**Issue by iamakanksha** [composer/composer#9344]
When I run this command:
  - `composer self-update`
  - `composer install -n`

I get the following output:
`> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap() must be an instance of Composer\Script\CommandEvent, instance of Composer\Script\Event given, called in phar:///home/travis/.phpenv/versions/7.0.4/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php on line 323 and defined in /home/travis/build/practo/consult-api/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Composer/ScriptHandler.php:67
Stack trace:
#0 phar:///home/travis/.phpenv/versions/7.0.4/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(323): Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap(Object(Composer\Script\Event))
#1 phar:///home/travis/.phpenv/versions/7.0.4/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(219): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('Sensio\\Bundle\\D...', 'buildBootstrap', Object(Composer\Script\Event))
#2 phar:///home/travis/.phpenv/versions/7.0.4/bin/compose in /home/travis/build/practo/consult-api/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Composer/ScriptHandler.php on line 67
Fatal error: Uncaught TypeError: Argument 1 passed to Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap() must be an instance of Composer\Script\CommandEvent, instance of Composer\Script\Event given, called in phar:///home/travis/.phpenv/versions/7.0.4/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php on line 323 and defined in /home/travis/build/practo/consult-api/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Composer/ScriptHandler.php:67
Stack trace:
#0 phar:///home/travis/.phpenv/versions/7.0.4/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(323): Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap(Object(Composer\Script\Event))
#1 phar:///home/travis/.phpenv/versions/7.0.4/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(219): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('Sensio\\Bundle\\D...', 'buildBootstrap', Object(Composer\Script\Event))
#2 phar:///home/travis/.phpenv/versions/7.0.4/bin/compose in /home/travis/build/practo/consult-api/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Composer/ScriptHandler.php on line 67`

**Comment by Toflar** [comment]
The error is coming from `Sensio\Bundle\DistributionBundle\Composer\ScriptHandler`. Looks like https://github.com/sensiolabs/SensioDistributionBundle which has been abandoned years ago and thus won't get any compatibility updates anymore. I guess you should update your application to use Symfony Flex as stated in the README of the project.

**Comment by Seldaek** [comment]
This is most likely because you're using a way outdated sensio/distribution-bundle as it was fixed in https://github.com/sensiolabs/SensioDistributionBundle/commit/4fd740b02261672cc4e41a78791af35935424b7f over 4 years ago. Make sure you run composer update sensio/distribution-bundle and then it should work.

**Comment by iamakanksha** [comment]
@Toflar @Seldaek due to the symfony version of the project (2.8), I can not update sensio/distribution-bundle beyond a certain version, I was not facing the issue until I used composer 2.x

**Comment by stof** [comment]
@iamakanksha if you use unmaintained versions of both Symfony and `sensio/distribution-bundle`, I guess you will also need to stay on outdated composer.
But looking at sensio/distribution-bundle, the versions fixing support for the "new" version of composer events are 3.0.36, 4.0.6 and 5.0.6. And they all support Symfony 2.8. So I don't see why you couldn't update the bundle.

**Comment by Seldaek** [comment]
@iamakanksha as far as I can see, 3.0.36 supports symfony 2.8 still, and has the fix https://packagist.org/packages/sensio/distribution-bundle#v3.0.36 

Anyway closing here as there isn't much we can do.

**Comment by stof** [comment]
even 5.0.25 supports Symfony 2.8

**Comment by iamakanksha** [comment]
Thank you updating the package version resolved my issue
