### ISSUE TITLE
Trigger plugin only when global events occur.

### ISSUE THREAD

**Issue by evonicgu** [composer/composer#9346]
I'm developing a composer plugin, that must watch for globally installed packages and read extra info from them. My goal is to determine if the PackageEvent passed to method is global, because I don't want my plugin to work with local events.

**Comment by Seldaek** [comment]
I think you might be able to detect if composer is running in global context by checking `realpath($composer->getConfig()->get('home')) === getcwd()`

**Comment by evonicgu** [comment]
Thanks
