### ISSUE TITLE
The compose config bin-dir --absolute --global command doesn't work as expected

### ISSUE THREAD

**Issue by glensc** [composer/composer#9354]
Background: need to put composer global bin to $PATH in a portable way.

Apparently it can vary on different things:
- $COMPOSER_HOME env being set
- user having legacy path ($HOME/.composer present)
- composer is new enough that xdg path is used

portable way is to ask composer itself what the bin dir is and update PATH
 
----

When I run this command:

```
$ cd /tmp
$ composer config bin-dir --absolute --global
/private/tmp/vendor/bin
$
```

I get the following output:

```
/private/tmp/vendor/bin
```

And I expected this to happen:
```
/Users/glen/.composer/vendor/bin
```

or 

```
/Users/glen/.config/composer/vendor/bin
```

**Comment by glensc** [comment]
composer global can be used to get proper value, but to prints noise to output so it's not usable (in a stable way) from scripts.


```
$ composer global config bin-dir --absolute --global
Changed current directory to /Users/glen/.composer
/Users/glen/.composer/vendor/bin
$
```

EDIT: looks like it is scriptable as the other diagnostic is printed to stderr, not stdout:


```
$ c=$(composer global config bin-dir --absolute --global)
Changed current directory to /Users/glen/.composer
$ echo $c
/Users/glen/.composer/vendor/bin
$
```

**Comment by Seldaek** [comment]
If you want the bin dir of the `composer global` vendors, then use `composer global config bin-dir --absolute`. If you pass the --global flag to the config command, this does something else, it just reads the value from the global config file (which is unrelated to the composer global installed stuff.. I know it's confusing, I'm sorry :)
