### ISSUE TITLE
Backwards compatibility issues

### ISSUE THREAD

**Issue by jhaagmans** [composer/composer#9356]
We have an older (~2y) CakePHP project running in a docker environment. When building that docker environment, we install all composer dependencies like this:

```Dockerfile
RUN COMPOSER_ALLOW_SUPERUSER=1 wget https://raw.githubusercontent.com/composer/getcomposer.org/d3e09029468023aa4e9dcd165e9b6f43df0a9999/web/installer -O - -q | php -- --quiet && \
    php composer.phar install --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader --apcu-autoloader && \
    php composer.phar clearcache && \
    rm composer.phar
```

This will install composer 1.8.0 and should run a production-safe installation of all composer dependencies.

However, since this weekend (presumably since Composer 2.0 came out), this started to throw errors like:

```shell
    Failed to extract cakephp/localized: (1) unzip -qq  '/var/www/equalture.com/vendor/composer/tmp-48c19aa917647d1e3e95e9494052f665' -d '/var/www/equalture.com/vendor/composer/aff7929a'

unzip: can't open /var/www/equalture.com/vendor/composer/tmp-48c19aa917647d1e3e95e9494052f665[.zip]

    This most likely is due to a custom installer plugin not handling the returned Promise from the downloader
    See https://github.com/composer/installers/commit/5006d0c28730ade233a8f42ec31ac68fb1c5c9bb for an example fix
    Failed to extract cakephp/migrations: (1) unzip -qq  '/var/www/equalture.com/vendor/composer/tmp-35742f1c25536ff29b3b8b267d6cbebf' -d '/var/www/equalture.com/vendor/composer/2170b332'

unzip: can't open /var/www/equalture.com/vendor/composer/tmp-35742f1c25536ff29b3b8b267d6cbebf[.zip]

    This most likely is due to a custom installer plugin not handling the returned Promise from the downloader
    See https://github.com/composer/installers/commit/5006d0c28730ade233a8f42ec31ac68fb1c5c9bb for an example fix
```

We have not changed anything in the `composer.lock` for weeks. Upgrading to composer 2 didn't help.

What I found to be the root cause was `cakephp/plugin-installer` and everything seems to have resolved itself after upgrading that to `1.3.0` (still needs a full test round). What worries me, though, is the fact that even though we have fixed package and composer versions, our build pipeline suddenly broke due to a change outside of our environment.

I concede that we could be more up-to-date but even with `cakephp/plugin-installer` 1.2.x (which was the latest version until 3 days ago), this would have broke. That _really_ worries me. [Did you just break userspace?](https://lkml.org/lkml/2012/12/23/75) 😬

**Comment by stof** [comment]
the installer installs the latest stable version by default. And this is composer 2.
The error you get is from Composer 2.

If you want to keep installing Composer 1, you should pass the `--1` option to the installer (and making sure that your use an uptodate installer script, as https://github.com/composer/getcomposer.org/commit/d3e09029468023aa4e9dcd165e9b6f43df0a9999 is actually too old to support that option)

**Comment by jhaagmans** [comment]
Ah, so passing a commit hash for the installer does not in fact lock the version of composer? That actually makes sense...

**Comment by stof** [comment]
no. It only locks the version of the installer
