### ISSUE TITLE
Http secure fail if changed get signature error

### ISSUE THREAD

**Issue by SLAY3RYTB** [composer/composer#9359]
Hello,

Im need help for use composer to install Irony for RoundCube.

Im needed use Composer 1.10.16 because Irony use Pear repository.

The probleme are :

1. If im use command : php composer.phar install / on cmd im get the first error probleme there say need http security for download XLM_UTIL_1.2.1 look on attached file for lookup error getted

2. If im going on composer.phar file and im edit the ligne 10211 : 'secure-http' => true, and change this to false : 'secure-http' => false, im saving file and execute command : php composer.phar install / im get an error php say broken signature look on attached file for lookup error getted

Please help me, im very need that for my work.

PS : im sorry for my english, im an a french people

Sincerely,
SLAY3R

![http secure error](https://user-images.githubusercontent.com/56283720/97320319-f53f4b80-186d-11eb-87f9-72de29425fdd.PNG)

![signature brocken](https://user-images.githubusercontent.com/56283720/97320322-f5d7e200-186d-11eb-8be0-e96f0cbc4ff3.PNG)

**Comment by Seldaek** [comment]
1. If you want to use pear's xml util, you should rather use https://packagist.org/packages/pear/xml_util IMO - but anyway it seems like Irony is pretty old and not necessarily maintained.. If that's the repo you're using https://github.com/detrout/irony/blob/master/composer.json then I'd suggest you update the pear repository URL to be `https://`, that should fix things. If not you can also run `composer config secure-http false` to allow insecure http requests
2. Do not edit phar files, that breaks them indeed. You can change the config using the composer config command, or by editing the composer.json manually.
