### ISSUE TITLE
Composer 2 is slow even for --version and about

### ISSUE THREAD

**Issue by GaryJones** [composer/composer#9363]
My (global) `composer.json`:

```json
{
    "require": {

    },
    "require-dev": {

    }
}

```

(previously had a few Composer plugins in there, but since removed from `composer.json`, deleted `composer.lock` and run `composer update`.)

Output of `composer g diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.2
PHP version: 7.4.8
PHP binary path: /usr/local/Cellar/php/7.4.8/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
cURL version: 7.71.1 libz 1.2.11 ssl OpenSSL/1.1.1g
zip extension: OK
```

When I run this command:

```
time composer g about -vvv -profile
```

I get the following output:

```
[3.9MiB/0.68s] Changed current directory to /Users/gary/.composer
Reading ./composer.json
Loading config file /Users/gary/.composer/auth.json
Loading config file ./composer.json
Loading config file /Users/gary/.composer/auth.json
Reading /Users/gary/.composer/auth.json
Checked CA file /usr/local/etc/openssl@1.1/cert.pem: valid
Executing command (/Users/gary/.composer): git branch -a --no-color --no-abbrev -v
Executing command (/Users/gary/.composer): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (/Users/gary/.composer): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (/Users/gary/.composer): hg branch
Executing command (/Users/gary/.composer): fossil branch list
Executing command (/Users/gary/.composer): fossil tag list
Executing command (/Users/gary/.composer): svn info --xml
Reading /Users/gary/.composer/vendor/composer/installed.json
Running 2.0.2 (2020-10-25 23:03:59) with PHP 7.4.8 on Darwin / 19.6.0
[7.6MiB/0.07s] Composer - Dependency Manager for PHP
Composer is a dependency manager tracking local dependencies of your projects and libraries.
See https://getcomposer.org/ for more information.
[7.6MiB/0.07s] Memory usage: 7.56MiB (peak: 7.64MiB), time: 0.07s
composer g about -vvv  0.16s user 0.13s system 1% cpu 27.700 total
```

And I expected this to happen:

Quicker than 27 seconds to give me the About blurb. Same slowness happens for `composer --version` as well. Tried in ZSH (Oh My Zsh, with all plugins disabled), and native Mac Terminal with similar results.

I ran the [install script](https://getcomposer.org/download/), then moved `composer.phar` to `/usr/local/bin` and renamed to `composer`. For fun, I also ran the install script again, and `php composer.phar --version` also takes ~21 seconds to complete.

I also explicitly disabled Xdebug, and updated to PHP 7.4.11, but there was no change in behaviour.

It's possible that the `time: 0.07s` suggests that Composer 2 is running quickly, but the data isn't coming to the terminal at any speed. Composer 1.10.16 was done in 0.5s:

```
time php composer.phar about -vvv --profile
Loading config file /Users/gary/.composer/auth.json
Reading /Users/gary/.composer/composer.json
Loading config file /Users/gary/.composer/auth.json
Loading config file /Users/gary/.composer/composer.json
Loading config file /Users/gary/.composer/auth.json
Reading /Users/gary/.composer/auth.json
Checked CA file /usr/local/etc/openssl@1.1/cert.pem: valid
Executing command (/Users/gary/.composer): git branch -a --no-color --no-abbrev -v
Executing command (/Users/gary/.composer): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (/Users/gary/.composer): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (/Users/gary/.composer): hg branch
Executing command (/Users/gary/.composer): fossil branch list
Executing command (/Users/gary/.composer): fossil tag list
Executing command (/Users/gary/.composer): svn info --xml
Reading /Users/gary/.composer/vendor/composer/installed.json
Running 1.10.16 (2020-10-24 09:55:59) with PHP 7.4.11 on Darwin / 19.6.0
[6.8MiB/0.00s] Loading config file /Users/gary/.composer/auth.json
[7.1MiB/0.00s] Reading /Users/gary/.composer/composer.json
[7.1MiB/0.00s] Loading config file /Users/gary/.composer/auth.json
[7.1MiB/0.00s] Loading config file /Users/gary/.composer/composer.json
[7.1MiB/0.00s] Loading config file /Users/gary/.composer/auth.json
[7.1MiB/0.00s] Reading /Users/gary/.composer/auth.json
[7.1MiB/0.00s] Executing command (/Users/gary/.composer): git branch -a --no-color --no-abbrev -v
[7.1MiB/0.02s] Executing command (/Users/gary/.composer): git describe --exact-match --tags
[7.1MiB/0.05s] Executing command (/Users/gary/.composer): git log --pretty="%H" -n1 HEAD --no-show-signature
[7.1MiB/0.07s] Executing command (/Users/gary/.composer): hg branch
[7.1MiB/0.09s] Executing command (/Users/gary/.composer): fossil branch list
[7.1MiB/0.11s] Executing command (/Users/gary/.composer): fossil tag list
[7.1MiB/0.12s] Executing command (/Users/gary/.composer): svn info --xml
[7.1MiB/0.16s] Reading /Users/gary/.composer/vendor/composer/installed.json
[7.1MiB/0.16s] Composer - Dependency Manager for PHP
Composer is a dependency manager tracking local dependencies of your projects and libraries.
See https://getcomposer.org/ for more information.
[7.1MiB/0.16s] Memory usage: 7.1MiB (peak: 7.15MiB), time: 0.16s
php composer.phar about -vvv --profile  0.11s user 0.12s system 45% cpu 0.523 total
```

Composer 2.0.0-alpha1 was also slow. No change after `composer clearcache` either.

Any suggestions?

**Comment by stof** [comment]
is it the same if you remove the global composer.json entirely ?

**Comment by GaryJones** [comment]
Seems a bit quick (11-12 seconds).

I ran `rm ~/.composer/composer.json`, then `time composer g about -vvv --profile` and also `time composer about -vvv --profile`

**Comment by Seldaek** [comment]
Any chance you can strace the process to hopefully see where it's spending time in more details? Or run it through a profiler? Running `time composer about -vvv --profile` completes in 0.3s real time here, so I'm not sure how to help :) 

The output looks all fairly normal too.

**Comment by naderman** [comment]
The fact that the time reported at the end of the composer script as well as user/sys time are low, only real is that long, suggests this is something in your system that's slowing the phar execution down after it's done.

**Comment by Seldaek** [comment]
Something to maybe look at is whether you have an antivirus configured, maybe try disabling it see if it helps? Stabbing in the dark here really, no idea but it seems to be in your environment somehow.

**Comment by GaryJones** [comment]
> Something to maybe look at is whether you have an antivirus configured, maybe try disabling it see if it helps?

Jordi wins the prize :-)

I only recently installed an AV ([Avira](https://www.avira.com/)) on this machine - as soon as I turned off real-time protection, then Composer 2.0 responded instantly:

```
time composer --version --profile
[6.1MiB/0.00s] Memory usage: 6.13MiB (peak: 6.21MiB), time: 0s
Composer version 2.0.2 2020-10-25 23:03:59
composer --version --profile  0.11s user 0.08s system 92% cpu 0.198 total
```

Thank you!

I wonder why it affects the Composer 2.0 phar, but not the 1.10.16 phar?

**Comment by Seldaek** [comment]
Alright then closing here, we can't do much about it. I don't know if the antivirus sees some phars as more risky for some reason, or if the 1.10.16 has been scanned enough times that the file has been marked safe in their DB?

**Comment by GaryJones** [comment]
I did reach out to Avira, and while the response was along the lines of "we can't do anything", then I've just noticed that having the real-time protection running, no longer makes Composer 2 (2.0.2 and 2.0.8) run slowly, so it looks like their database got updated. ✅
