### ISSUE TITLE
Suggestion: Display package's "homepage" instead of "description" in `composer show` list

### ISSUE THREAD

**Issue by ThomasLandauer** [composer/composer#9367]
I'm suggesting to replace the last column of the output table of `composer show` and `composer outdated`: Show the packages website (i.e. `homepage`) instead of its `description`

Reasons:
* When I'm looking at that list, most of the time I need more information about the package. So I usually copy the package name into my web browser to search for it. An url which is clickable right away would be quicker.
* The `description` of most packages is non-saying, If I really don't know what this package is, its description certainly won't tell me. To find out, I'd have to, well, visit its website :-)
* While not fully solving https://github.com/composer/composer/issues/8104, it would at least be a step in this direction.

Which URL to display?
If given, use [`homepage`](https://getcomposer.org/doc/04-schema.md#homepage) from `composer.json`. If not, use the package's packagist.org URL.

**Comment by Seldaek** [comment]
I think this will have to wait until we can upgrade dependencies in 2.2, then we can make use of https://symfony.com/blog/new-in-symfony-4-3-console-hyperlinks which would be a more elegant way to fix this IMO, making the name clickable or adding short `[home] [repo]` links before the description for example.

**Comment by ThomasLandauer** [comment]
Well, *replacing* the description could be done immediately, without waiting till all consoles support hyperlinks ;-)

However, when you do take the hyperlink route, I'd suggest:
* Link the package name with the `homepage` key.
* New idea: Add an internal link named `[why]` just before the description, linked to `composer why this/package`
* By `repo` you mean the packagist.org URL?

**Comment by Seldaek** [comment]
I realize we could do it now, but I'd rather not lose the description, and I'd also rather not have this output change in every other release, people like stability. So it'll have to wait a bit :)

repo I was thinking the git repo URL, which I'd typically head to to find a changelog, as the homepage is often too vague.

**Comment by ThomasLandauer** [comment]
> So it'll have to wait a bit :)

Sure :-)

Repo: I was assuming most packages would put that into `homepage` ;-) I certainly agree that repo URL is better than any marketing website. But where can you obtain the URL from?

**Comment by Seldaek** [comment]
We can use the homepage and/or support.source which is set for github packages, or source.url worst case..

**Comment by Seldaek** [comment]
> New idea: Add an internal link named [why] just before the description, linked to composer why this/package

This sounds nice but I don't think we can link to a shell command :)
