### ISSUE TITLE
[Monorepo] How to prefer local "path" package with canonical over remote packagist in Composer 2?

### ISSUE THREAD

**Issue by TomasVotruba** [composer/composer#9368]
Hi,

I'm following documentation on how to prevent installing a package from packagist.org - I need to use local "path" one. I've tried to solve it for ~5 hours now, but I'm totally lost in how to make it work with no real clue.

From Documentation https://getcomposer.org/doc/articles/repository-priorities.md#filtering-packages I assume (there is no json code example), this is how to prevent looking for package in packagist

```json
{
    "repositories": [
        {
            "type": "composer",
            "url": "https://packagist.org",
            "exclude": [
                "symplify/package-builder",
                "symplify/coding-standard"
            ]
        },
        {
            "type": "path",
            "url": "../../packages/coding-standard",
            "options": {
                "symlink": false
            },
            "canonical": true
        },
        {
            "type": "path",
            "url": "../../packages/package-builder",
            "options": {
                "symlink": false
            },
            "canonical": true
        }
    ]
}
```

The "symplify/coding-standard" requires "symplify/package-builder" (both in `*` version):

<br>

## Current Output

On running composer install I get one positive from local (first) and one negative from packagist (latte):

```bash
  - Installing symplify/coding-standard (dev-da44236f10a65d28110ffb10a625c2690cf78f3a): Mirroring from ../../packages/coding-standard
  - Installing symplify/package-builder (8.3.48): Downloading (100%)
```

<br>

## Desired Output

Both should be local:

```bash
  - Installing symplify/coding-standard (dev-da44236f10a65d28110ffb10a625c2690cf78f3a): Mirroring from ../../packages/coding-standard
  - Installing symplify/package-builder (dev-da44236f10a65d28110ffb10a625c2690cf78f3a): Mirroring from ../../packages/package-builder
```

As I understand the docummentation, the setup above should work. But it does not. Maybe there is a typo or incorrect bool value.

<br>

Any tips on what I'm doing wrong? 

<br>

Thank you :+1:

**Comment by Seldaek** [comment]
If you're using Composer 2, you're overthinking this :) 

This should be enough:

```json
{
    "repositories": [
        {
            "type": "path",
            "url": "../../packages/coding-standard",
            "options": {
                "symlink": false
            },
        },
        {
            "type": "path",
            "url": "../../packages/package-builder",
            "options": {
                "symlink": false
            },
        }
    ]
}
```

i.e. define your new repos, and as they are first (and everything is canonical by default) they will take precedence over packagist.org (which is added last by default).

If using Composer 1, upgrade to Composer 2..

**Comment by TomasVotruba** [comment]
Thank you for such a quick reply :) :+1: 

Here is the updated `composer.json` paths with your suggestion:
https://github.com/symplify/symplify/pull/2420/checks?check_run_id=1322099265



I actually started with Composer 2, but had bugs I didn't understand at all:
https://github.com/symplify/symplify/pull/2420/checks?check_run_id=1322099322#step:7:14

![image](https://user-images.githubusercontent.com/924196/97471922-88997f00-1949-11eb-90a0-3569af3d1be9.png)

([full failed CI step](https://github.com/symplify/symplify/pull/2420/checks?check_run_id=1322099322#step:7:14))

**Comment by TomasVotruba** [comment]
The `dev-master` version leads to similar, yet shorter error:

![image](https://user-images.githubusercontent.com/924196/97472889-a1eefb00-194a-11eb-9ded-5015f841e7d3.png)

Not sure what that means.

**Comment by TomasVotruba** [comment]
Btw, the last version works locally, but not on Github Actions. We're getting somewhere :)

**Comment by stof** [comment]
well, looks like your path repository does not get its version guessed as `dev-master` but as `dev-9652...`. this seems to be the reason for your issue.

**Comment by TomasVotruba** [comment]
That's why I used `*`, that should mean *anything*, right?

**Comment by TomasVotruba** [comment]
So using `dev-<commit-hash>` does fail too :(

![image](https://user-images.githubusercontent.com/924196/97474057-f8a90480-194b-11eb-9944-08297c5aadd8.png)

![image](https://user-images.githubusercontent.com/924196/97474109-065e8a00-194c-11eb-9203-e05386fb32e6.png)

https://github.com/symplify/symplify/pull/2420/checks?check_run_id=1322217641

**Comment by TomasVotruba** [comment]
Any other ideas?

**Comment by stof** [comment]
@TomasVotruba the issue here is that your `migrify/migrify-kernel` package still wants `^0.3.50` here.

The proper solution is to define a branch alias in your path repository so that the guessed version passes this constraint. https://github.com/composer/composer/pull/9273 might help there

**Comment by Seldaek** [comment]
IMO all you need to do is define in env `COMPOSER_ROOT_VERSION=dev-master`. And then make sure you define a [branch-alias](https://getcomposer.org/doc/articles/aliases.md#branch-alias) so that dev-master is recognized as being `8.4.x-dev`. That should resolve things.

@stof branch-version is not needed here as the versions are the same as the root package AFAICT.

**Comment by TomasVotruba** [comment]
@stof 

> @TomasVotruba the issue here is that your migrify/migrify-kernel package still wants ^0.3.50 here.

migrify is 0.3.50, but it needs Symplify 8.3.x. This was not a problem in Composer 1.
The branch alias 8.4.x is in every Symplify package - [e.g.](https://github.com/symplify/symplify/blob/a4ae31708b8a509c2c0f1f8941599880036c8c97/packages/console-color-diff/composer.json#L29) for last ~4 years.

@Seldaek I'll try it the ENV, thanks! The branch alias 8.4.x is in every Symplify package already.

What is this "branch version" thing? How should it look like in my case? Just want to try it out.

**Comment by TomasVotruba** [comment]
@Seldaek It seems it works :) I can't believe it :sob:  :partying_face: 


![image](https://user-images.githubusercontent.com/924196/97492121-66acf600-1963-11eb-98cf-454c427281d4.png)


Could you share what exactly this does and how did you come to this idea?

**Comment by Seldaek** [comment]
The problem is this: on a local git checkout, you have full git history so when you're on branch foo, composer sees that it was branched off of master, and it assumes the version is dev-master, then it adds the branch-alias for dev-master and everything works.

When you are on CI, you have a shallow clone with only a few commits of history, and usually only the local branch you're building, so it can't guess anything, may not even have the branch name to make it dev-foo, so it ends up as dev-$gitHash for the version.. That's usually no problem for most projects, but when you have path repos like here for subprojects, or if you have circular dependencies with things you depend on depending back on your project, then it can fail to resolve.

Defining COMPOSER_ROOT_VERSION allows you to specify the version, so that it doesn't have to guess from git data (which is missing in CI). So that lets it resolve things.

I hope this helps clarify it.

**Comment by TomasVotruba** [comment]
Thank you for taking time and writing this with just right amount of details. Exactly what I needed.
I feel like understand it very much better now :+1: thank you 

You've saved my day :bow:

**Comment by mxr576** [comment]
Cool, now I fully understand (remember?) why we had to add `COMPOSER_ROOT_VERSION` at the very beginning to our build pipeline where we are using [our monorepo Composer plugin](https://github.com/Pronovix/monorepo-helper). So no change is needed for Composer 2 compatibility.
