### ISSUE TITLE
 auth.json ignored when Symfony 3, 4 or 5 is used

### ISSUE THREAD

**Issue by remicollet** [composer/composer#9372]
Reopening #7124

Can someone try this...

From composer git clone
Update symfony (clean "platform" stuff will pull 5.1.8)

Using a simple composer.json 
```
{
    "repositories": [
        {
            "url": "https://github.com/remicollet/testprivate",
            "type": "git"
        }
    ],
```

And a simple auth.json

```
{
    "http-basic": {
        "https://github.com": {
            "username": "xxx",
            "password": "yyy"
        }
    }
}
```

With symfony 2.8 -(by default in composer.lock, so in composer.phar) => no prompt
With symfony 3, 4 or 5 => credential prompt

Maybe this is not covered by unit test, of not reproducible in travis (no user)

**Comment by remicollet** [comment]
```
$  /work/GIT/composer/bin/composer install
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
Loading composer repositories with package information
Updating dependencies
Username for 'https://github.com': 

```

**Comment by remicollet** [comment]
This mays affects much more user after #9303

**Comment by Seldaek** [comment]
Will have to investigate further.. Can you just check if you get a prompt when passing --no-interaction?

**Comment by remicollet** [comment]
Yes:

```
$ /work/GIT/composer/bin/composer update  --no-interaction
Loading composer repositories with package information
Updating dependencies
Username for 'https://github.com':
```

**Comment by remicollet** [comment]
Both, #7124 was open a lot time ago for v1, and still exists in v2

**Comment by stof** [comment]
> Update symfony (clean "platform" stuff will pull 5.1.8)

Are you updating only Symfony components or also other packages ?

**Comment by remicollet** [comment]
Only Symfony and react-promise (but can't be related to this one which is not used in v1, also affected)

**Comment by Seldaek** [comment]
Modern symfony/process passes the env explicitly by reading $_SERVER, while 2.x used the real process env forwarding so we didn't notice this small bug in Util\Git. I'm hoping this fixes it for you too @remicollet :)

**Comment by remicollet** [comment]
I confirm  2cb9630 fixes this issue.

Thanks a lot.
