### ISSUE TITLE
Not possible to configure a config value beginning with hyphen

### ISSUE THREAD

**Issue by wuuti** [composer/composer#9375]
The composer config command does not respect quotes in values and interpretes values starting with a `-` as a composer option. 

This makes it e.g. impossible in gitlab ci jobs to dynamically use the following config command:

`composer config http-basic.hostname gitlab-ci-token "${CI_JOB_TOKEN}"`

The token sometimes starts with a hypen, and this causes composer config to fail: 

```bash
composer config -a http-basic.hostname gitlab-ci-token "-734t28fa"
                                   
  The "-7" option does not exist.  
    
config [-g|--global] [-e|--editor] [-a|--auth] [--unset] [-l|--list] [-f|--file FILE] [--absolute] [--] [<setting-key>] [<setting-value>]...
```

The usage of variables in CLI commands, esp. for secrets like the above is not unusual, and normally quoting that value should prevent it from being interpreted as an option, as with other CLI commands and programs. 

The problem is additionally hard to debug when it happens, because e.g. in the above gitlab case, _most_ of the tokens being generated do not start with a hyphen and therefore do not produce any problem. But from time to time gitlab generates the problematic tokens, and then your pipelines fail for an unknown (and unreproducable) reason. 

Problem exists at least with composer 1.10.16 and 1.6.3.

**Comment by Seldaek** [comment]
That's really nasty but not sure we can fix this right now. Hopefully symfony/console 4.x has a fix and this will be fixed in composer 2.2.

**Comment by Seldaek** [comment]
Actually you can use `composer config -- http-basic.hostname gitlab-ci-token "${CI_JOB_TOKEN}"` as workaround, `--` indicating that following args are just args and not options anymore.

**Comment by Seldaek** [comment]
Closing as I don't think a newer symfony will fix this, using -- is the correct way to terminate argument parsing IMO

**Comment by whatthefrog** [comment]
https://gitlab.com/gitlab-org/gitlab/-/issues/373842
