### ISSUE TITLE
Composer 2.0.3 ignores config.platform for dependencies

### ISSUE THREAD

**Issue by MightyPork** [composer/composer#9377]
My `composer.json`:

```json
{
  "config": {
    "preferred-install": "dist",
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "7.0.26",
      "ext-gd": "1",
      "ext-soap": "1",
      "ext-mongodb": "1.2.4"
    }
  },
  "minimum-stability": "dev",
  "prefer-stable": true,
  "require": {
    "php": ">=7.0.0",
    "andywer/js-localization": "dev-laravel-5",
    "barryvdh/laravel-ide-helper": "^2.4",
    "doctrine/dbal": "~2.5",
    "fisharebest/ext-calendar": "^2.5",
    "guzzlehttp/guzzle": "^6.2",
    "influxdb/influxdb-php": "^1.15.0",
    "jenssegers/mongodb": "^3.3",
    "jenssegers/mongodb-session": "^1.2",
    "laracasts/flash": "^3.0",
    "laravel-notification-channels/pushover": "^1.2",
    "laravel/framework": "5.5.*",
    "laravel/passport": "~4.0",
    "laravel/tinker": "~1.0",
    "lord/laroute": "^2.4",
    "mightypork/php-sandbox": "^1.0",
    "nexmo/client": "^1.2",
    "phpoffice/phpspreadsheet": "^1.4.0",
    "predis/predis": "^1.1",
    "riimu/kit-phpencoder": "^2.4",
    "spatie/laravel-authorize": "^1.1",
    "spatie/laravel-pjax": "^1.3",
    "tuupola/base58": "^0.1.0"
  },
  "require-dev": {
    "filp/whoops": "~2.0",
    "fzaninotto/faker": "~1.4",
    "laravel/browser-kit-testing": "^2.0",
    "mockery/mockery": "~1.0",
    "phpunit/phpunit": "~6.0"
  }
}

```

Output of `composer diagnose`:

```
composer diagnose
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 2.0.3
PHP version: 7.0.26 - Package overridden via config.platform, actual: 7.3.12
PHP binary path: /usr/bin/php
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
cURL version: 7.73.0 libz 1.2.11 ssl OpenSSL/1.1.1h
zip extension: OK
```

When I run this command:

```
composer install
```

I get the following output:

```
Your Composer dependencies require the following PHP extensions to be installed: gd
```

This worked fine before the update to Composer 2.0, namely 1.10.16 is OK.

The "gd" extension does not work on my system, so I have it disabled. It is not actually used, just some of my dependencies has it listed. Now I have to keep composer from updating...

**Comment by Seldaek** [comment]
The bottom line here is that some requirement requires ext-gd, and you don't have it on your system, so things might go bad somehow, and composer is trying to warn you.

You can add a `"provide": {"ext-gd": "1"}` instead of defining it in the platform, if you want to pretend like it's not required.. This will say to composer that your package satisfies the requirement, and it will not be checking for the extension presence anymore. This should only be used in private code and not in packages that you publish on packagist, as saying your code implements an extension's API is a bad idea when your package will be used by others.

Alternatively you can set `"config": {"platform-check": false}` to disable these warnings entirely (read more about platform check at https://getcomposer.org/doc/07-runtime.md#platform-check first). 

The best solution though would be to install the gd extension, or use a library that works without it.

**Comment by naderman** [comment]
One additional option, if you want to just disable the check for ext-gd on the system where you install, you could run composer install --ignore-platform-req=ext-gd to ignore any dependencies on ext-gd which will also disable the platform check for this extension but keep it in tact for all other extensions and php version.

**Comment by naderman** [comment]
The idea behind the config platform definition is to define a target platform that you actually want to run on. So if you put ext-gd into config.platform you are essentially telling composer that ext-gd will be available on the target platform, which is actually not the case here, hence Jordi's alternative of using "provide" to signal composer that ext-gd should be satisfied without it having to be on the platform.

**Comment by MightyPork** [comment]
I see there's some subtlety between "provide" and "platform". I will disable the checks, it has been nothing but nuisance on development machines. 

But what I don't understand, why did this work in 1.10 and stopped in 2.0?

**Comment by naderman** [comment]
@MightyPork Composer v1 did not yet have the runtime check for dependencies. So while it had the same concept for platform config, you had to explicitly run composer check-platform-reqs in production to get the error you now automatically see at runtime.

**Comment by MightyPork** [comment]
Ok, thanks for the explanation. For future googlers, this fixed it:

```
{
  "config": {
    "preferred-install": "dist",
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "7.0.26"
    }
  },
  "provide": { // <--- moved the extensions here. "provide" is NOT in config!
    "ext-gd": "1",
    "ext-soap": "1",
    "ext-mongodb": "1.2.4"
  },
...
```

**Comment by BoGnY** [comment]
@MightyPork You saved my day!!
