### ISSUE TITLE
handshake failure with self-signed cert on composer 2.0.3

### ISSUE THREAD

**Issue by martyrs** [composer/composer#9381]
I just upgraded to composer 2.0.3 and my self signed cert is not working anymore.
Rolling back to 1.10.5 solves the issue without any changes.

My `composer.json`:

```json
  "repositories": [
    {
      "type": "composer",
      "url": "https://repo.xyz.com",
      "options": {
        "ssl": {
          "verify_peer": false,
          "allow_self_signed": true,
          "local_cert": "/etc/openssl/project/certs/composer.pem"
        }
      }
    }
  ],

```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.3
PHP version: 7.4.11
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
cURL version: 7.58.0 libz 1.2.11 ssl OpenSSL/1.1.1g
zip extension: OK

```

When I run this command:

```
composer install -vvv
```

I get the following output:

```
Reading ./composer.json
Loading config file /home/tamer/.config/composer/auth.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/home/tamer/project/tlcomposerv2): git branch -a --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /home/tamer/.config/composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 2.0.3 (2020-10-28 15:50:55) with PHP 7.4.11 on Linux / 5.4.0-52-generic
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
Loading composer repositories with package information
Updating dependencies
Downloading https://repo.xzy.com/packages.json
Downloading https://repo.xzy.com/packages.json
Downloading https://repo.xzy.com/packages.json

  [Composer\Downloader\TransportException]                                   
  error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure  
                                                                             

Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Util/Http/CurlDownloader.php:303
 Composer\Util\Http\CurlDownloader->tick() at phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php:302
 Composer\Util\HttpDownloader->countActiveJobs() at phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php:270
 Composer\Util\HttpDownloader->wait() at phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php:81
 Composer\Util\HttpDownloader->get() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:1080
 Composer\Repository\ComposerRepository->fetchFile() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:833
 Composer\Repository\ComposerRepository->loadRootServerFile() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:524
 Composer\Repository\ComposerRepository->hasProviders() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:346
 Composer\Repository\ComposerRepository->loadPackages() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/PoolBuilder.php:319
 Composer\DependencyResolver\PoolBuilder->loadPackagesMarkedForLoading() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/PoolBuilder.php:185
 Composer\DependencyResolver\PoolBuilder->buildPool() at phar:///usr/local/bin/composer/src/Composer/Repository/RepositorySet.php:233
 Composer\Repository\RepositorySet->createPool() at phar:///usr/local/bin/composer/src/Composer/Installer.php:412
 Composer\Installer->doUpdate() at phar:///usr/local/bin/composer/src/Composer/Installer.php:251
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php:131
 Composer\Command\InstallCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:309
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:121
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:63
 require() at /usr/local/bin/composer:24
```

And I expected this to happen:

**Comment by Seldaek** [comment]
Can you try with:

```
  "repositories": [
    {
      "type": "composer",
      "url": "https://repo.xyz.com",
      "options": {
        "ssl": {
          "capath": "/etc/openssl/project/certs/composer.pem"
        }
      }
    }
  ],
```

If it fails to validate you can add `"verify_peer": false,` again but that should not be necessary I believe if the certificate is valid for the domain in use.

**Comment by martyrs** [comment]
Hi @Seldaek 
Now I am getting
```
  [Composer\Downloader\TransportException]                               
  SSL certificate problem: self signed certificate in certificate chain  
```

**Comment by Seldaek** [comment]
With verify_peer: false too?

You can try `cafile` instead of `capath`. Not sure what else could help with curl to make it accept self signed certificates.

**Comment by martyrs** [comment]
Tested with `cafile` now and getting same output:
``` 
[Composer\Downloader\TransportException]                                   
  error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```
(And tested with both `verify_peer``true` and `false`)
If I rollback to composer 1.10.5, everything works fine without any change in composer.json
So I believe some prop has renamed or removed with composer 2.
May you investigate this?

**Comment by Seldaek** [comment]
Composer 2 uses curl internally while Composer 1 does not, we do map a few stream options to curl options, but apparently that's not enough to make curl work with self-signed certs. From what I read setting verify_peer false should be enough, cafile should be enough too. I guess I'll have to try locally but this might take a while.

**Comment by martyrs** [comment]
Thanks for the info. However, setting an invalid `cafile` doesn't throw any errors, so I don't think it's ever used in Composer 2.
By the way, in my case, I definitely need `local_cert` [https://www.php.net/manual/en/context.ssl.php]
```
It must be a PEM encoded file which contains your certificate and private key. It can optionally contain the certificate chain of issuers.
```

**Comment by Seldaek** [comment]
Is that what you have in your composer.pem file? The certificate AND private key for it? For curl I think only the certificate is needed.

**Comment by johnstevenson** [comment]
@Seldaek Looking at the curl docs `local_cert` would perhaps need to be set as `CURLOPT_SSLCERT` with the private key as `CURLOPT_SSLKEY` But it looks quite messy to get it working cross-platform. https://curl.haxx.se/libcurl/c/CURLOPT_SSLCERT.html

**Comment by martyrs** [comment]
> Is that what you have in your composer.pem file? The certificate AND private key for it? For curl I think only the certificate is needed.

Yes, i have client certificate and private key in my PEM file. I have my own root CA server and i authenticate to server using client certificates.

**Comment by Seldaek** [comment]
Ok I tried to repro but I somehow can't, maybe I don't have the right SSL setup locally to match what you do. In any case, I don't have time to explore this in depth so for now I disabled curl when self signed certs are in use. I hope this lets you upgrade to Composer 2. If someone has the time and motivation to try to figure this out for curl please do, but otherwise this is also fine IMO.

You can try with latest snapshot: `composer self-update --snapshot`.

**Comment by Seldaek** [comment]
With https://github.com/composer/composer/pull/9384 perhaps you can now use curl.. if you remove `allow_self_signed` from the config it will use curl, if it's there it will use the php streams. That requires you split the cert and key into two files local_cert/local_pk though. I'm not sure from the description here whether your cert is self signed or not.

**Comment by rtm-ctrlz** [comment]
@martyrs actually it (cert and key in one file) is possible and should work without any changes and setting `local_pk`.

I'll try it on my machine within couple hours and post a comment here to let you know.

**Comment by johnstevenson** [comment]
@rtm-ctrlz That will be interesting because the curl docs imply that you need to set `CURLOPT_SSLKEY` in conjunction with `CURLOPT_SSLCERT` (unless you're using curl with SecureTransport)

**Comment by johnstevenson** [comment]
@rtm-ctrlz That's useful to know - thanks for checking and reporting.

**Comment by martyrs** [comment]
Hi @rtm-ctrlz 
Checked with the master branch as well.
Setting the only local_cert worked fine.
Thanks.
