### ISSUE TITLE
php-zip now required

### ISSUE THREAD

**Issue by charlesdeb** [composer/composer#9383]
My `composer.json`:

```json
{
  "name": "xx",
  "description": "yy",
  "require-dev": {
    "phpunit/phpunit": "^8",
    "codeception/codeception": "^3",
    "guzzlehttp/guzzle": "^6.3",
    "codeception/specify": "^1",
    "codeception/stub": "^3",
    "dms/phpunit-arraysubset-asserts": "^0.1.0",
    "codeception/aspect-mock": "^3.1",
    "captbaritone/mailcatcher-codeception-module": "^2.1",
    "donatj/mock-webserver": "^2.1"
  },
  "require": {
    "mailjet/mailjet-apiv3-php": "^1.4",
    "stripe/stripe-php": "^7.14",
    "google/recaptcha": "^1.2"
  }
}
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: xxx
Dev Public Key Fingerprint: xxx
OK
Checking composer version: OK
Composer version: 2.0.3
PHP version: 7.3.22
PHP binary path: /usr/bin/php7.3
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
cURL version: 7.68.0 libz 1.2.11 ssl OpenSSL/1.1.1g
zip extension: OK
```
I did the upgrade to composer v2 and ran `php composer.phar check-platform-reqs` beforehand. It all seemed good, so I went ahead - and then I did a `composer update`. My site stopped working and the browser told me that:

```
Composer detected issues in your platform: Your Composer dependencies require the following PHP extensions to be installed: zip
```
So, I went and did that and all was working again fine. You can see from the composer diagnose output that the zip extension is now installed. I did this all locally first to test for issues - which is good as this error might have taken down our production server had I just done the upgrade there. Is there anyway the composer upgrade package can warn users about the missing `php-zip` extension before the upgrade?

This is what 'composer diagnose' says about our production server:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (1.9.1 => 2.0.3)
Composer version: 1.9.1
PHP version: 7.3.23
PHP binary path: /usr/bin/php
```

There is no mention of the zip extension here. Is this going to cause me grief if I try to upgrade to composer 2 without first yum installing php-zip and unzip?

**Comment by gristoi** [comment]
Our test server has just gone down with the same issue after a deploy a couple of hours ago

**Comment by Seldaek** [comment]
If you install your dependencies then run `composer why ext-zip`, you can see which package is requiring it:

```
$ composer why ext-zip
facebook/webdriver  1.7.1  requires  ext-zip (*)
```

So that's the reason it is required. Composer 2 added the platform check feature at runtime which does error if something is missing.

See https://github.com/composer/composer/issues/9377#issuecomment-719019204 for an explanation on your options here.

One thing though that confuses me is this statement:

> I did the upgrade to composer v2 and ran php composer.phar check-platform-reqs beforehand. It all seemed good, so I went ahead - and then I did a composer update. My site stopped working and the browser told me that:

You should run `composer check-platform-reqs --no-dev` ideally which will read from the lock file. You should then run `composer install` to install the latest dependencies from the lock file, you should never run `update` as part of a deployment. See https://getcomposer.org/doc/03-cli.md#install-i

**Comment by charlesdeb** [comment]
Thanks for getting back to me. However, how would I have known to run `composer why ext-zip` before the upgrade? I only found out about the zip problem when the site broke and composer (helpfully) told me what to check.

I actually ran `php composer.phar check-platform-reqs --no-dev` and it didn't indicate any problems either.

I hear you about the `composer update` issue (updating ALL packages in a project is risky), but:

1. `composer install` (at least with v 1) never seems to pick up any changes in my `composer.json`. It always tells me: 

```
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Nothing to install, update or remove
Package facebook/webdriver is abandoned, you should avoid using it. Use php-webdriver/webdriver instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
```
That always seemed like an odd message to me - of course it's out of date. I have just changed the `composer.josn` and that's why I am running the `install` command. That's at least how it works with `bundler install` in the ruby world. So I just give up, and run `composer update` which acts on the current `composer.json`

I have just spotted that if I run `composer update <package name>` then it does install/update/remove the relevant package and leaves everything else alone. 

2. I have comparatively few packages in my project, and they are all covered with automated tests - so figure I can pick up regressions pretty easily (but it's certainly not ideal).

**Comment by Seldaek** [comment]
Composer isn't bundler, although IIRC bundler works similarly. install applies what is in the lock file to the vendor dir, update generates a new lock file from the composer.json. So in prod you really want to just do install (after deploying a new updated lock file), in dev to update things you should use update.

As for how you would have know to run composer why ext-zip, well in theory if you run check-platform-reqs it should tell you the extension is missing, then you can use why to figure out what is requiring it if needed. If not I'm not sure what's going on, unless you had an outdated facebook/webdriver version which didn't require it yet, and then the composer update pulled in the new package which added the require..

Anyway sorry for the hurdles but glad you could fix it quickly at least.
