### ISSUE TITLE
Invalid PSR-0/4 classes shouldn’t autoload in non-optimized mode as well

### ISSUE THREAD

**Issue by brandonkelly** [composer/composer#9389]
[UPGRADE-2.0.md](https://github.com/composer/composer/blob/master/UPGRADE-2.0.md) states

> Invalid PSR-0 / PSR-4 class configurations will not autoload anymore in optimized-autoloader mode, as per the warnings introduced in 1.10

I’m glad that Composer is getting more strict about autoloading, but I think it should be done consistently. Non-optimized autoloaders shouldn’t support invalid PSR-0 / PSR-4 classes either.

Two reasons:

1. In theory the autoloader can be a lot faster if it knows _exactly_ where each class should live, based on the `autoload` definition, making it less necessary to optimize the autoloader in the first place (especially useful for local development where dependencies may be changing frequently).

2. The current way could lead to unexpected `Class not found` errors on production environments, if you are developing locally without optimizing the autoloader (without errors), but you do optimize dependencies on production, where suddenly some classes aren’t autoloadable anymore.

If this is debatable, then at the very least I think there should be a new `--autoload-strict` option that could be passed (which is only checked if not optimizing the autoloader).

**Comment by Seldaek** [comment]
The message you quoted refers to the fact that PSR-0/4 mapped classes which were not valid were previously autoloadable in optimized mode, and that's now not true anymore. But they were never autoloadable in non-optimized mode. 

I don't think there's anything to fix here, but if you do have a specific example of something which is wrong please say.

**Comment by brandonkelly** [comment]
Ah ok, then I misunderstood. Sorry about that.
