### ISSUE TITLE
Unable to use a proxy

### ISSUE THREAD

**Issue by AbdallaDev2** [composer/composer#9392]
hello everyone I hope all can help me when I set up composer and update 
I am not allowed to remove the check from the box
Do you want to use a proxy?
And after the completion of the installation
I want to download Laravel  to give me this problem, please solve and thank you

**Comment by AbdallaDev2** [comment]
![Screenshot (280)](https://user-images.githubusercontent.com/61882285/97779870-b0772580-1b89-11eb-8a6e-03a90539103d.png)

**Comment by johnstevenson** [comment]
I guess you used Composer-Setup.exe to install composer and the reason that you couldn't uncheck the "Do you want to use a proxy?" is that you already have an `http_proxy` or `https_proxy` environment variable set.

You can check this in cmd.exe by typing: `set http_proxy` or `set https_proxy`

I presume you don't want to use a proxy, so you need to remove the environment variables: type "environment" in the TaskBar search box to open Control Panel System Properties, then click the _Environment Variables_ button.

**Comment by AbdallaDev2** [comment]
johnstevenson  thanks i doing the first step and remove variables 
and run composer create-project --prefer-dist laravel/laravel 
and the same problem happened

**Comment by AbdallaDev2** [comment]
![Screenshot (282)](https://user-images.githubusercontent.com/61882285/97783157-8e3bd280-1b9e-11eb-853f-29b7aae80c54.png)

really i want to use composer normally without proxy

**Comment by AbdallaDev2** [comment]
![Screenshot (283)](https://user-images.githubusercontent.com/61882285/97783200-d5c25e80-1b9e-11eb-8485-63a28bcdf730.png)

that is my environment after delete is that right?

**Comment by AbdallaDev2** [comment]
thank you very very much its work now and i learn new thing thanks very much .

**Comment by johnstevenson** [comment]
You need to open a new cmd.exe - sorry, I shoud have mentioned that (but I guess you worked that one out!)

**Comment by AbdallaDev2** [comment]
yes i doing that and it work  thanks for help
