### ISSUE TITLE
Composer 2 does not respect config.platform in platform-check feature

### ISSUE THREAD

**Issue by zorn-v** [composer/composer#9394]
My `composer.json` like:

```json
    "config": {
        "platform": {
            "ext-oci8": "2.0",
            "php": "7.4.3"
        }
    }
```
There is some extension that may be hard to install on dev machine (or impossible) like oci8,
And there may be some packages to require it. And project use it in rare (but it needed) and not needed on dev machines (maybe except one or two).

Current composer 2 behavior make impossible to develop that project without that ext. 
But that ext can not be installed on platforms other that linux I think... 
And even on linux it not so simple.

More info at https://github.com/yajra/laravel-oci8/issues/546

**Comment by zorn-v** [comment]
Another workaround is
```
    "provide": {
        "ext-oci8": "2.0"
    },
```

**Comment by Seldaek** [comment]
Indeed, see https://github.com/composer/composer/issues/9377#issuecomment-719019204
