### ISSUE TITLE
COMPOSER V2 NOT WORKING WHEN ATTEMPTING TO USE

### ISSUE THREAD

**Issue by Movi1999** [composer/composer#9396]
I cannot use composer v2 whatsoever, I successfully installed it and tried to compose something but then got the error:  if (!$deleted) {
                $error = error_get_last();
                $message = 'Could not delete '.$path.': ' . @$error['message'];
                if (Platform::isWindows()) {
                    $message .= "\nThis can be due to an antivirus or the Windows Search Indexer locking the file while they are analyzed";
                }
I'm not sure what to do, my antivirus is disabled and I even disabled my windows search indexer just to make sure that everything is disabled. Yet it still doesn't work and the same error appears each time, I literally can't go anywhere.

**Comment by stof** [comment]
What you are showing here is an extract of source code, not an error message you get. This won't help much as we won't see the actual error.

**Comment by luceos** [comment]
We've seen an increase in error reports relating to this Exception at @Flarum. It seems users on Windows are running into some kind of timeout (looking at the source of composer which as a usleep just above it). I have no clue how to help these people as I'm unaware why the Antivirus or Indexer could be the cause of this. If I know why the usleep was added and what to look for with these people I might be able to offer a better error report.

Here are some examples of users running into issues:

https://discuss.flarum.org/d/25289
![image](https://user-images.githubusercontent.com/504687/97851429-a8d48f80-1cf5-11eb-95c7-6e8a6ad0fb83.png)

https://discuss.flarum.org/d/25277
https://discuss.flarum.org/d/25276

**Comment by luceos** [comment]
On further investigation, people seem to be able to circumvent this issue by going one directory up and then providing the target as argument instead of `.` as current directory. Will provide this as a solution and see whether it helps for them. This does not solve the issue at hand though.

**Comment by katosdev** [comment]
> On further investigation, people seem to be able to circumvent this issue by going one directory up and then providing the target as argument instead of `.` as current directory. Will provide this as a solution and see whether it helps for them. This does not solve the issue at hand though.
> 
> Update: I get a feeling this might be related to XAMPP.

I've conducted a range of testing on this one, and have even upped the composer time-out to 20000. 
I received the same issue.

Steps taken:
- Composer timeout adjusted to 20000
- Ran a powershell to remove all files recursively from htdocs
- Disabled the search indexer service on windows and restarted (same error)
- Disabled Windows Defender and restarted (same error)

I have rectified this by completing the following:
```composer self-update 1.10.17```
(This to roll back from 2.0.4)

```composer create-project flarum/flarum . --stability=beta --prefer-dist```

Confirmed that this is now showing in my folder and has downloaded successfully.

I confess, I have not yet dug into exactly *why* the composer 2.0.4 failed, but for now this can be offered as a work-around for Flarum :)

**Comment by luceos** [comment]
@katosdev thanks for diving into this 👍 

I can only assume that the timeout is no longer valid for composer v2 under windows environments. 

@Seldaek thanks for assigning the labels. For what it's worth my apologies for the subject of this issue, this is not how you or your team should be treated.

**Comment by katosdev** [comment]
> @katosdev thanks for diving into this 👍
> 
> I can only assume that the timeout is no longer valid for composer v2 under windows environments.
> 
> @Seldaek thanks for assigning the labels. For what it's worth my apologies for the subject of this issue, this is not how you or your team should be treated.

No problem! My apologies that my skills do not go far enough into finding **where** this fails @Seldaek but give me a nudge if you need anything further, happy to help where I can! :)

**Comment by Seldaek** [comment]
Ok I think I got a fix, will push shortly.

**Comment by katosdev** [comment]
> Ok I think I got a fix, will push shortly.

Sounds good! Let me know when pushed and I'm happy to assist in testing again 👍

**Comment by Seldaek** [comment]
Alright please feel free to give it a shot with the latest snapshot (`composer self-update --snapshot`).

The antivirus/search indexer warning was off actually, the reason that the removal is failing is that the directory is open in the terminal. That was only a symptom of the problem though, the real problem is that it should not try to remove the directory it's in while it is working on installing the package there. 

@luceos as for the issue title no worries, not your fault if someone has chewing gum stuck under their caps lock key :p Thanks for giving us workable information to figure out the issue.

**Comment by stof** [comment]
> The antivirus/search indexer warning was off actually, the reason that the removal is failing is that the directory is open in the terminal.

The wording might need to be updated to account for this other kind of directory locking
