### ISSUE TITLE
PHP version support for composer 2.1 and beyond

### ISSUE THREAD

**Issue by morrisonlevi** [composer/composer#9398]
First, thanks for keeping composer v2.0 compatible back to PHP 5. That was very helpful for users of PHP 5 paying for LTS.

According to this blog post: https://blog.packagist.com/composer-2-0-is-now-available/

> Composer 2.1 might still come with PHP 5.3 support, depending on the timeline and which features end up being included, but then at the latest by Composer 2.2 we will drop support for everything older than PHP 7.1.3. According to our stats this allows over 90% of the Composer users to use the latest version, and for the others who are stuck on outdated PHP versions we will keep providing critical bug and security fixes in the 2.0.x or 2.1.x range.

I am curious if there is specific motivation for dropping PHP 7.0. I think it is fairly common to handle PHP 5 and PHP 7 separately, but dropping 7.0 would mean there's another case to handle. If there isn't any specific reason for requiring PHP 7.1 over 7.0 I suggest considering keeping 7.0 support in composer v2.1 and beyond. Thanks for your time.

**Comment by stof** [comment]
Supporting Symfony 7.0 would forbid upgrading the bundled `symfony/*` packages to 4.4, forcing to stay on the 3.4 version. and Symfony 3.4 will stop receiving bug fixes at the end of this month.

See https://github.com/composer/composer/issues/9303 and https://github.com/composer/composer/issues/8785 for the discussion about that.

**Comment by stof** [comment]
The relevant breakpoints for `symfony/*` support of PHP versions are PHP 5.5.9, 7.1.3 and 7.2.5.

**Comment by morrisonlevi** [comment]
I'll close this one and comment in the others.
