### ISSUE TITLE
Composer 2 issue w/ sensio/distribution-bundle

### ISSUE THREAD

**Issue by morrisonlevi** [composer/composer#9402]
I am aware this bundle has been abandoned. This is for running regression tests on legacy Symfony 2.3. I scanned through https://getcomposer.org/upgrade/UPGRADE-2.0.md but didn't see anything particularly that suggests that this part of Events would be broken. Is this expected to the best of your knowledge?

```
Fatal error: Uncaught TypeError: Argument 1 passed to
Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap() must
be an instance of Composer\Script\CommandEvent, instance of
Composer\Script\Event given, called in
phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php
on line 323 and defined in
/home/circleci/datadog/tests/Frameworks/Symfony/Version_2_3/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Composer/ScriptHandler.php:33
Stack trace:
#0
phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(323):
Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap(Object(Composer\Script\Event))
#1
phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(219):
Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('Sensio\\Bundle\\D...',
'buildBootstrap', Object(Composer\Script\Event))
#2
phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(101):
Composer\EventDispatc in
/home/circleci/datadog/tests/Frameworks/Symfony/Version_2_3/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Composer/ScriptHandler.php
on line 33
```

**Comment by Seldaek** [comment]
It's not listed because we deprecated this [6 years ago](https://github.com/composer/composer/commit/3efed220a6c9fd6e4a13ea806879e124941c9fc7) and I assumed everyone migrated already.. As far as I know though [the fix](https://github.com/sensiolabs/SensioDistributionBundle/commit/4fd740b02261672cc4e41a78791af35935424b7f) is in 3.0.36 of the bundle which you should be able to use with symfony 2.3.

**Comment by morrisonlevi** [comment]
My tests have passed using the 3.0 version on Symfony 2.3. Thank you for the info!

**Comment by brocknessmonster** [comment]
How does one incorporate 'the fix' you have hyperlinked? Thanks.
