### ISSUE TITLE
Add command to clear composer cache

### ISSUE THREAD

**Issue by mattfarina** [composer/composer#941]
I've had issues with caching in composer. It would be nice to have a command to manually clear it.

**Comment by croonx** [comment]
Hi all.
I think there is still some bug in composer int
I experience that after first time i used comoser init and then rename composer.json to composer.json.old I can't generate fresh composer.json because :

Package name (<vendor>/<name>) [Bartek/a]: bartek/aaa
Description []: asddf
Author: zzz xxx qww@dfdf.pl
 Invalid author string.  Must be in the format: John Smith <john@example.com>

But what is interesting after clear-cache and change directory I could generate new composer.json without any problems.
I saw that someone suggesting mention about privileges in UNIX OS but currently I'm developing under Windows platform so I don't expect any special issue about privileges.
I simple tried uninstall and install composer again but this doesn't solve the problem.
I hope my symptoms could help little to generally solve this problem at all.

**Comment by Pierstoval** [comment]
I had some issues of this kind with my Composer, as I'm developing on the E: drive, and composer cache is on the C: drive. What I did to fix that is to create a symlink in C: in the composer directory, and this link targets a directory on E:, and it works like a charm, but I don't know if it'll fix your issue that is maybe more related to a package :/

**Comment by croonx** [comment]
No. My D: is just virtual drive. Look this :

C:\D\symfony\a>composer clear-cache
Clearing cache (cache-dir): C:\Users\Bartek\AppData\Local\Composer
Clearing cache (cache-files-dir): C:\Users\Bartek\AppData\Local\Composer\files
Clearing cache (cache-repo-dir): C:\Users\Bartek\AppData\Local\Composer\repo
Cache directory does not exist (cache-vcs-dir):

C:\D\symfony\a>composer init


  Welcome to the Composer config generator



This command will guide you through creating your composer.json config.

Package name (<vendor>/<name>) [Bartek/a]: bartek/my_proj
Description []: My proj
Author: Bartek Xxxx (bartek@xxx.pl)
 Invalid author string.  Must be in the format: John Smith <john@example.com>
Author:

**Comment by croonx** [comment]
I'm just looking at :
https://github.com/composer/composer/blob/master/src/Composer/Command/InitCommand.php
and I found in line 43 regular expression
in public function parseAuthorString($author)

'/^(?P<name>[- \.,\p{L}\'’]+) <(?P<email>.+?)>$/u'

Explanation step by step from :
https://www.regex101.com/
The same explanation i deduced from :
http://www.pcre.org/current/doc/html/pcre2syntax.html#TOC1

^(?P<name>[- \.,\p{L}\'’]+) <(?P<email>.+?)>$/u
^ assert position at start of the string
(?P<name>[- \.,\p{L}\'’]+) Named capturing group name
[- \.,\p{L}\'’]+ match a single character present in the list below
Quantifier: + Between one and unlimited times, as many times as possible, giving back as needed [greedy]
-  a single character in the list -  literally
\. matches the character . literally
, the literal character ,
\p{L} matches any kind of letter from any language
\' matches the character ' literally
’ the literal character ’
 < matches the characters  < literally
(?P<email>.+?) Named capturing group email
.+? matches any character (except newline) [unicode]
Quantifier: +? Between one and unlimited times, as few times as possible, expanding as needed [lazy]
> matches the characters > literally
$ assert position at end of the string
u modifier: unicode: Pattern strings are treated as UTF-16. Also causes escape sequences to match unicode characters

So i think this regular expression is pretty nonsense.

I done some test in my system,

test.php
<?php
preg_match ('/^(?P<name>[- \.,\p{L}\'’]+) <(?P<email>.+?)>$/u','John Smith john@example.com',$match);
echo "Name:$match[0]";

d:\test>php test.php

Warning: preg_match(): Compilation failed: invalid UTF-8 string at offset 22 in D:\test\test.php on line 2
Name:

**Comment by naderman** [comment]
@croonx what does this have to do with clearing the cache? can you make a new issue please to change the regex or even submit a PR?

**Comment by RQuadling** [comment]
^(?P<name>[- \.,\p{L}\'’]+) <(?P<email>.+?)>$
---------------------------------------------

    ^(?P<name>[- \.,\p{L}\'’]+) <(?P<email>.+?)>$

Options: Case insensitive; Exact spacing; Dot doesn't match line breaks; ^$ don't match at line breaks; Greedy quantifiers

* [Assert position at the beginning of the string][1] `^`
* [Match the regex below and capture its match into a backreference named “name” (also backreference number 1)][2] `(?P<name>[- \.,\p{L}\'’]+)`
    * [Match a single character present in the list below][3] `[- \.,\p{L}\'’]+`
        * [Between one and unlimited times, as many times as possible, giving back as needed (greedy)][4] `+`
        * [A single character from the list “- ”][5] `- `
        * [The literal character “.”][6] `\.`
        * [The literal character “,”][5] `,`
        * [A character from the Unicode category “letter” (any kind of letter from any language)][7] `\p{L}`
        * [The literal character “'”][6] `\'`
        * [The literal character “’”][5] `’`
* [Match the character string “ <” literally][5] ` <`
* [Match the regex below and capture its match into a backreference named “email” (also backreference number 2)][2] `(?P<email>.+?)`
    * [Match any single character that is NOT a line break character (line feed)][8] `.+?`
        * [Between one and unlimited times, as few times as possible, expanding as needed (lazy)][9] `+?`
* [Match the character “>” literally][5] `>`
* [Assert position at the end of the string, or before the line break at the end of the string, if any (line feed)][1] `$`

Created with [RegexBuddy](http://www.regexbuddy.com/)

[1]: http://www.regular-expressions.info/anchors.html
[2]: http://www.regular-expressions.info/named.html
[3]: http://www.regular-expressions.info/charclass.html
[4]: http://www.regular-expressions.info/repeat.html
[5]: http://www.regular-expressions.info/characters.html
[6]: http://www.regular-expressions.info/characters.html#special
[7]: http://www.regular-expressions.info/unicode.html#category
[8]: http://www.regular-expressions.info/dot.html
[9]: http://www.regular-expressions.info/repeat.html#lazy

**Comment by naderman** [comment]
Please stop debating regular expressions in this entirely unrelated resolved issue.
