### ISSUE TITLE
[IMPORTANT] Remove Platform check in Runtime in default setup

### ISSUE THREAD

**Issue by jakubboucek** [composer/composer#9411]
In related to #9410 I appeal to You: **Remove Platform check in Runtime in default setup**

**It's now shutdowns websites across the world.**  
Trust me its't very serious problem, try to [**search "Composer detected issues in your platform"**](https://www.google.com/search?q=%22Composer+detected+issues+in+your+platform%22) for proof.

The default setup should be the Composer is not check platform requirements in runtime. It's should conditioned by any switch in `install`/`require` command, setup in `composer.json` or any other setup which is expressly initiated by developer.

## FAQ

**App should never be deployed to production with Dev deps**

You right. But Composer 2 is extremely widespread among developers, regardless of their seniority. A lot of them are juniors. The problem is the platform check is in runtime with the most default usage of Composer, it's no requires any additional configuration in `composer.json`, no specific switch in `install`/`require` command. 

Considering the extent of possible damage is necessary to respect most general cases and a variety of uses.

**Check can be disabled by `--no-platform-reqs`, and similar ways…**

You right. But as I wrote above, platform check is Composer's default behavior and it's should be gently to prevent cause damage.

**Developer should ever check production environment before deploy**

You right. But s*it happens. The App can interfere with Platform requirements for a lot of reasons:

- Web hosting can silently change the server environment. Especially its problem on Shares web hosting.
- Developer can do a seemingly innocent update (`vendor-name/package-name 1.2.3 -> 1.2.4`) and does not expect any problem (Composer is not notified about changing platform-reqs during update).
- Developers just do mistakes - we are just humans.

**Why developer update to Composer v2?**

Unlike to App's dependencies, the Composer engine version is not locked by any code (like a `composer.json`). For example: most of CI/CD workflows is now using Composer 2 without any Developer merits - it was upgraded automatically.

**Comment by Seldaek** [comment]
Closing in favor of https://github.com/composer/composer/issues/9412
