### ISSUE TITLE
Upgrade to Composer 2.0 fails on Laravel Homestead

### ISSUE THREAD

**Issue by titizali** [composer/composer#9425]
My `composer.json`:
```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "repositories": [
        {
            "type": "composer",
            "url": "https://info@memoryco.org:XXXXXXX@nova.laravel.com"
        }
    ],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": "^7.3",
        "anhskohbo/no-captcha": "^3.1",
        "biscolab/laravel-recaptcha": "^4.4",
        "cmgmyr/messenger": "dev-master",
        "fabpot/goutte": "^4.0",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "geoip2/geoip2": "~2.0",
        "google/cloud-translate": "^1.3",
        "graham-campbell/flysystem": "^7.1",
        "guzzlehttp/guzzle": "^7.0.1",
        "intervention/image": "^2.5",
        "jenssegers/agent": "^2.6",
        "kyslik/column-sortable": "^6.0",
        "lab404/laravel-impersonate": "^1.7",
        "laracasts/utilities": "^3.2",
        "laravel/cashier": "^12.3",
        "laravel/framework": "^8.3",
        "laravel/legacy-factories": "^1.0",
        "laravel/nova": "^3.4",
        "laravel/scout": "^8.3",
        "laravel/socialite": "^5.0",
        "laravel/telescope": "^4.0",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^3.0",
        "laravelcollective/html": "^6.2",
        "league/flysystem": "^1.0",
        "league/flysystem-aws-s3-v3": "^1.0",
        "mews/purifier": "3.3",
        "naif/generate-password": "^1.4",
        "nesbot/carbon": "^2.0",
        "pusher/pusher-php-server": "^4.1",
        "spatie/image-optimizer": "^1.1",
        "spatie/laravel-activitylog": "^3.15",
        "spatie/laravel-backup": "^6.11",
        "spatie/laravel-newsletter": "^4.8",
        "stevebauman/location": "^5.0",
        "teamtnt/laravel-scout-tntsearch-driver": "^10.0",
        "willvincent/feeds": "^2.0"
    },
    "require-dev": {
        "barryvdh/laravel-ide-helper": "^2.8",
        "facade/ignition": "^2.3.6",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "@php artisan ide-helper:generate",
            "@php artisan ide-helper:meta"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

Output of `composer diagnose -vvv`:

```
Reading ./composer.json
Loading config file /home/vagrant/.config/composer/config.json
Loading config file /home/vagrant/.config/composer/auth.json
Loading config file ./composer.json
Loading config file /home/vagrant/Code/auth.json
Reading /home/vagrant/Code/auth.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/home/vagrant/Code): git branch -a --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /home/vagrant/.
config/composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcom
poser.org/ "Getting Started" section
Reading /home/vagrant/Code/vendor/composer/installed.json
Running 2.0.4 (2020-10-30 22:39:11) with PHP 7.4.5 on Linux / 4.15.0-96-generic
Checking composer.json: Reading ./composer.json
WARNING
require.mews/purifier : exact version constraints (3.3) should be avoided if the package follo
ws semantic versioning
Checking platform settings: OK
Checking git settings: Executing command (CWD): git config color.ui
OK
Checking http connectivity to packagist: Downloading http://repo.packagist.org/packages.json
[200] http://repo.packagist.org/packages.json
OK
Checking https connectivity to packagist: Downloading https://repo.packagist.org/packages.json
[200] https://repo.packagist.org/packages.json
OK
Checking github.com oauth access: Using GitHub token authentication
Downloading https://api.github.com/
[200] https://api.github.com/
OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: Downloading https://getcomposer.org/versions
[200] https://getcomposer.org/versions
OK
Composer version: 2.0.4
PHP version: 7.4.5
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
cURL version: 7.58.0 libz 1.2.11 ssl OpenSSL/1.1.1g
zip extension: OK
```

When I run this command:

```
composer self-update --2
composer update -vvv
```

I get the following output:

Loading composer repositories with package information
Updating dependencies

                                            
  [Composer\Downloader\TransportException]  
  Port number ended with 'o'                
                                            

update [--with WITH] [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader
] [--no-scripts] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-
o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [
--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--
root-reqs] [--] [<packages>]...

And I expected this to happen:

composer update to function properly after upgrade

**Comment by stof** [comment]
@titizali could you reformat your issue using code blocks (the markdown syntax for the is to enclose them with triple backticks) ? That would make things a lot more readable.
Bonus point: for the composer.json, you can even enable syntax highlighting with ```` ```json ```` as the opening marker

**Comment by stof** [comment]
Als, please run the failing command in verbose mode (with `-v` or even `-vvv`) ti gace more details

**Comment by dkulyk** [comment]
"url": "https://info@memoryco.org:ozdizloz@nova.laravel.com". 
use Base auth config instead pass login with @ in url or urlencode it.

**Comment by stof** [comment]
you are missing the url encoding of the first `@` if your username is `info@memoryco.org`

the URL parsing of this URL is:
- username: `info`
- host: `memoryco.org`
- port `ozdizloz` (or maybe `ozdizloz@nova.laravel.com`)

**Comment by dkulyk** [comment]
Use `composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}` instead

**Comment by dkulyk** [comment]
https://nova.laravel.com/docs/3.0/installation.html#authenticating-nova-in-continuous-integration-ci-environments

**Comment by titizali** [comment]
> "url": "https://info@memoryco.org:ozdizloz@nova.laravel.com".
> use Base auth config instead pass login with @ in url or urlencode it.

please delete comment---seems line our nova password is there :(

**Comment by titizali** [comment]
> you are missing the url encoding of the first `@` if your username is `info@memoryco.org`
> 
> the URL parsing of this URL is:
> 
> * username: `info`
> * host: `memoryco.org`
> * port `xxxxxx` (or maybe `xxxxxx@nova.laravel.com`)

can you please delete comment to protect our password. i changed it but still... :(

**Comment by Seldaek** [comment]
If you configure authentication correctly using instructions from https://nova.laravel.com/docs/3.0/installation.html#authenticating-nova-in-continuous-integration-ci-environments instead of inlining it in the URL, this would not happen.

If you want to inline it in the URL, as your username contains a `@` you need to urlencode it to `%40` so using `info%40memoryco.org:xxxxxxx@nova.laravel.com` for example.

**Comment by Seldaek** [comment]
Also note that if you did configure it correctly via auth.json as per the instructions, your accidental reveal of credentials here would not have happened.. There is a reason passwords should not be put inline in URLs.

**Comment by titizali** [comment]
> Also note that if you did configure it correctly via auth.json as per the instructions, your accidental reveal of credentials here would not have happened.. There is a reason passwords should not be put inline in URLs.

yes--lesson learned! thank you, Jordi!

**Comment by mfn** [comment]
@titizali it's still possible to see the password in the history
![image](https://user-images.githubusercontent.com/87493/98565298-bb2e6a80-22ad-11eb-8a87-97b2d74718c9.png)

As a comment/issue creator you can/should be able also to remove historical edits!

**Comment by stof** [comment]
The password is also in all the mailboxes of people receiving email notifications for comments on this issue. And you can do all the cleanup you want in the Github UI, there is no way you can clean these notification emails.

So the proper action here is actually to change your password. That one is definitely leaked.

**Comment by titizali** [comment]
> @titizali it's still possible to see the password in the history
> ![image](https://user-images.githubusercontent.com/87493/98565298-bb2e6a80-22ad-11eb-8a87-97b2d74718c9.png)
> 
> As a comment/issue creator you can/should be able also to remove historical edits!

how do i do that? i cannot seem to find that option. maybe I can ask @Seldaek to see if he'd be so kind to delete the issue altogether?

**Comment by titizali** [comment]
> The password is also in all the mailboxes of people receiving email notifications for comments on this issue. And you can do all the cleanup you want in the Github UI, there is no way you can clean these notification emails.
> 
> So the proper action here is actually to change your password. That one is definitely leaked.

thanks for your follow-up. i changed my password immediately after i noticed the mistake. i hope i learned my lesson from this incredibly careless mistake

**Comment by Seldaek** [comment]
Sorry but I can't delete either. I reached out to github about deleting it a few days ago but no need yet.

**Comment by Seldaek** [comment]
Ah ha.. I see that deleting is possible but it had to be enabled in the org settings. Will delete this issue now just to avoid leaving your old password exposed :)
