### ISSUE TITLE
Validate does not check if lockfile version is in range

### ISSUE THREAD

**Issue by micheh** [composer/composer#9427]
I would expect that `composer validate` would show a warning or error if the installed version in `composer.lock` is not in range of the version constraint specified in `composer.json`. For example, if the installed version in `composer.lock` is `1.18.0`, you can use the constraint `^1.20.0` in `composer.json` and composer will not complain (see below). 

Is this intended? I think it would be a nice feature of the `validate` command.

My `composer.json`:

```json
{
    "name": "demo/demo",
    "description": "demo",
    "license": "proprietary",
    "require": {
        "symfony/polyfill-mbstring": "^1.20.0"
    }
}
```

My `composer.lock`:

```json
{
    "_readme": [
        "This file locks the dependencies of your project to a known state",
        "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies",
        "This file is @generated automatically"
    ],
    "content-hash": "031bc7f0487c29c0d0f938057343d9cc",
    "packages": [
        {
            "name": "symfony/polyfill-mbstring",
            "version": "v1.18.0",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/polyfill-mbstring.git",
                "reference": "a6977d63bf9a0ad4c65cd352709e230876f9904a"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/symfony/polyfill-mbstring/zipball/a6977d63bf9a0ad4c65cd352709e230876f9904a",
                "reference": "a6977d63bf9a0ad4c65cd352709e230876f9904a",
                "shasum": ""
            },
            "rest removed for the issue ..."
        }
    ],
    "packages-dev": [],
    "aliases": [],
    "minimum-stability": "stable",
    "stability-flags": [],
    "prefer-stable": false,
    "prefer-lowest": false,
    "platform": [],
    "platform-dev": [],
    "plugin-api-version": "2.0.0"
}

```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.4
PHP version: 7.3.23
PHP binary path: /usr/bin/php
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
cURL version: 7.29.0 libz 1.2.7 ssl NSS/3.44
zip extension: OK
```

When I run this command:

```
composer validate --strict
```

I get the following output:

```
./composer.json is valid
```

And I expected this to happen:
Composer should output a warning or error that the installed version in `composer.lock` does not match the version constraint in `composer.json`.

**Comment by Seldaek** [comment]
How did you get this composer.lock though? Because normally if you change the composer.json it would show:

```
$ c validate
./composer.json is valid
The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update` or `composer update <package name>`.
```

So I guess you did a partial update which did not update symfony/polyfill-mbstring?

Anyway I guess it would not hurt to check that the lock file fulfills root requirements in the validate command yes.

**Comment by micheh** [comment]
I don't exactly know how it happened, but I think your idea with a partial update is correct.

I can reproduce it when using `composer update nothing`:

1. Run `composer require symfony/polyfill-mbstring:1.18.0`.
2. Manually update the constraint to `^1.20.0` in composer.json.
3. Run `composer validate`, it correctly shows
> The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update` or `composer update <package name>`.
4. Run `composer update nothing`.
5. Run `composer validate` again. The lockfile is now up to date, but contains the outdated version which does not match the version constraint in `composer.json`.

**Comment by Seldaek** [comment]
This has been fixed at some point, after running step 3 of the msg above you now get:

```
# Lock file errors
- The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update` or `composer update <package name>`.
- Required package "symfony/polyfill-mbstring" is in the lock file as "v1.18.0" but that does not satisfy your constraint "^1.20.0".
```

After step 5 you still get the second warning.
