### ISSUE TITLE
Massive new issue in composer 2.0.5 - "composer install" deleted updated packages and even though it's saying "Installing," none of them show up no matter how many times I run "install"

### ISSUE THREAD

**Issue by archon810** [composer/composer#9431]
My `composer.json`:

```json
Sorry, this is private.
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
require.johnpbloch/wordpress : exact version constraints (5.4.3) should be avoided if the package follows semantic versioning
...
require.wpackagist-plugin/wp-polls : exact version constraints (2.75.5) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.5
PHP version: 7.4.11
PHP binary path: /usr/bin/php
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
cURL version: 7.73.0 libz 1.2.11 ssl OpenSSL/1.1.1h-fips
zip extension: OK
```

When I run this command:

```
composer install
```

I get the following output:

```
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Package operations: 6 installs, 0 updates, 0 removals
  - Installing wpackagist-plugin/contact-form-7 (5.3): Extracting archive
  - Installing wpackagist-plugin/disable-json-api (1.5.1): Extracting archive
  - Installing wpackagist-plugin/members (3.1.3): Extracting archive
  - Installing wpackagist-plugin/post-snippets (3.1.1): Extracting archive
  - Installing wpackagist-plugin/public-post-preview (2.9.2): Extracting archive
  - Installing wpackagist-plugin/regenerate-thumbnails (3.1.4): Extracting archive
```

![image](https://user-images.githubusercontent.com/469543/98416279-a34bb200-2033-11eb-9551-7f2b6e2c5984.png)

And I expected this to happen:
Packages got updated as before.

Rolling back to 2.0.3 (2.0.4 was broken for us due to the bitbucket bug) and rerunning `composer install` fixed the issue, and the directories finally actually appeared.

The worst thing is I updated composer on production without testing that installing still works, but that one's on me.

**Comment by andreymoser** [comment]
I am getting the same problem with this version, I am going to test with 2.0.3.

**Comment by andreymoser** [comment]
I have tested 2.0.3 right now and all dependencies are being extracted correctly. When I use 2.0.5 after installing all deps/folders in vendor folders are empty. I have used `-vvv --no-cache` in order to troubleshoot and both versions has the same output, it seems to be an issue with the dependency extractor from the zipped content which states that they were extracted without errors. The environment tested: Windows 10 x64.

**Comment by Narno** [comment]
Same here with Composer 2.0.5 (on Windows 10 x64): all vendors sub-directories are empty and files from installers (plugins) are not copied/moved.

**Comment by archon810** [comment]
Thank you for confirming I wasn't doing something dumb @andreymoser @Narno.

**Comment by Seldaek** [comment]
Is this only happening for packages installed with custom installers? Can someone try to figure out where the issue lies? Or at least give me an easy way to reproduce this?

**Comment by Narno** [comment]
Hello @Seldaek, I don't know if it's easy to reproduce, but share the case with one of my websites who use an installer to copy "themes" in a specific directory:
- https://github.com/Narno/narno.com/blob/master/composer.json
- A theme: https://github.com/Cecilapp/theme-hyde/blob/master/composer.json
- Installer: https://github.com/Cecilapp/theme-installer

**Comment by andreymoser** [comment]
Hey @Seldaek! I don't have access right now to the environment I tested before, but I rembember there wasn't custom installers there. I would suggest to test this in linux distro and compare with Windows 10 x64.

**Comment by Seldaek** [comment]
Thanks @Narno that allowed me to reproduce and identify 444b91a3ce599163aadc6902b0c402060d4d87a3 as the culprit. I'm working on a fix.

**Comment by Seldaek** [comment]
2.0.6 is now available.

**Comment by Narno** [comment]
Yeah, thanks a lot @Seldaek, good job! 👍
