### ISSUE TITLE
Requirements are resolved differently in composer 2

### ISSUE THREAD

**Issue by brechtdewinne** [composer/composer#9432]
My `composer.json`:

```json
{
    "name": "test/test",
    "type": "project",
    "authors": [
        {
            "name": "test",
            "email": "test@test.test"
        }
    ],
    "require": {
        "symfony/debug": "2.5.*",
        "symfony/http-kernel": "2.5.12"
    }
}
```

In composer 1.10.17, this will be handled correctly. But in composer 2.0.5, an error will be shown saying that requirements could not be resolved:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires symfony/http-kernel 2.5.12 -> satisfiable by symfony/http-kernel[v2.5.12].
    - symfony/http-kernel v2.5.12 requires symfony/debug ~2.5.9|~2.6,>=2.6.2 -> found symfony/debug[v2.6.2, ..., v2.8.52] but it conflicts with your root composer.json require (2.5.*).
```

**Comment by Seldaek** [comment]
Thanks, looks like a bug indeed. Will have to investigate further.

**Comment by PirxDanford** [comment]
We just found an issue regarding the zendframework/zend-code component, which is likely related to this one too (versions are being resolved like this at this point in time):

In composer version 1.10.16
-> the requirement of "doctrine/migrations (^1.4.1)" will resolve to "doctrine/migrations v1.8.1"
-> and it will require "ocramius/proxy-manager (^1.0|^2.0)" and resolve to "ocramius/proxy-manager 2.2.3"
-> and it will require zendframework/zend-code (^3.3.0) and resolve to "zendframework/zend-code 3.4.1"

In composer version 2.0.3 and 2.0.6
-> the requirement of "doctrine/migrations (^1.4.1)" will resolve to "doctrine/migrations v1.8.1"
-> and it will require "ocramius/proxy-manager (^1.0|^2.0)" and resolve to "ocramius/proxy-manager 1.0.2"
-> and it will require zendframework/zend-code (>2.2.5,<3.0) and resolve to "zendframework/zend-code 2.6.3"

**Comment by Seldaek** [comment]
@brechtdewinne alright should be fixed in the next release, it was a case of over-zealous optimization :)

@PirxDanford that seems like an unrelated problem, it is due to ocramius/proxy-manager requiring `ocramius/package-versions` which is incompatible with composer 1 if you are not running php 7.4. You can require `composer/package-versions-deprecated: ^1` which will replace ocramius/package-versions and everything should resolve fine again.

**Comment by PirxDanford** [comment]
@Seldaek after investigating more (before your reply) we had been discussing to fork package-versions and you already did it. Thank you for solving our problem, before we even knew about it! :-D
