### ISSUE TITLE
How to get install-path for a package?

### ISSUE THREAD

**Issue by szepeviktor** [composer/composer#9437]
Let's say I'm a package and I'd like to access/manipulate other packages' files.
How to determine `install-path` of another package?

I saw it in `vendor/composer/installed.json` but even that file has no fixed path as `vendor-dir` can be changed.

Please advise.

**Comment by Seldaek** [comment]
That sounds like a bad idea IMO, messing with another package's files. If needed you can have an API in the other package to retrieve the files' path.

But the installed.json does have a fixed path as your package will be in vendor dir, and the file is also in vendor dir, if vendor dir changes that doesn't affect the relative path from your package.

If running your code as root package, then your package is not in vendor dir, but then it knows where the vendor dir is.

**Comment by szepeviktor** [comment]
Thank you.

> your package will be in vendor dir, and the file is also in vendor dir

I think installer plugins may put files anywhere 👀

**Comment by Seldaek** [comment]
Technically yes anything is possible, but in normal cases custom installers would only relocate specific packages which requested it via a custom type. So IMO it's fine in practice, if someone decides to break it on purpose it's their problem..

**Comment by szepeviktor** [comment]
Yes, because you see packages from the point of view of the project.

When a package is installed it has no way to tell where other packages live.

**Comment by Seldaek** [comment]
But if you know your package will be installed in default path, you know where to locate the composer/installed.json file.

**Comment by Seldaek** [comment]
And that lets you know where other packages are, regardless of custom install paths.

**Comment by szepeviktor** [comment]
> But if you know your package will be installed in default path

Okay.
:) I prepare for users relocating all packages in a random way.
