### ISSUE TITLE
set-time-limit(30)

### ISSUE THREAD

**Issue by coding-musicman** [composer/composer#9438]
When I run this command:

```
composer status
```

I get the following output:

```
Following redirect (1) https://codeload.github.com/symfony/symfony/legacy.zip/96e7dede3ddc9e3b3392f5cc93e26eca77545a89
PHP Fatal error:  Maximum execution time of 30 seconds exceeded in phar://C:/Code/php/composer/composer.phar/src/Composer/Util/Http/CurlDownloader.php on line 275
```

or

```
PHP Fatal error:  Maximum execution time of 30 seconds exceeded in phar://C:/Code/php/composer/composer.phar/src/Composer/Util/HttpDownloader.php on line 288
```

I did some checks and it seems to stem from `Composer/Package/Comparer/Comparer::doTree`. There is an assignment: `set-time-limit(30)`. My `max_execution_time=1200` in the php.ini should be sufficient and is also shown correctly in the phpinfo.

Is the timeout handled correctly?
Background info: I have slow internet, about 4 MBit/s. I think that's why I encounter the problem.

**Comment by devlegacy** [comment]
You can change the option, to read more about the config, follow the next link:

[process-timeout](https://getcomposer.org/doc/06-config.md#process-timeout)

**Comment by coding-musicman** [comment]
@devlegacy nope, it is hardcoded

**Comment by Seldaek** [comment]
@coding-musicman I don't know why this was in there, I think it was an oversight.

Removed now, can you try if it works for you after `composer self-update --snapshot`?

**Comment by coding-musicman** [comment]
@Seldaek thanks, it's fixed
