### ISSUE TITLE
Is possible composer install binary pacage from packagist like npx?

### ISSUE THREAD

**Issue by DasdWaller** [composer/composer#9440]
I want to create a package and i dont want to install as local or as global. Composer have the ability to install executable packages from packagist?

**Comment by henze-housepedia** [comment]
I am not sure what you mean, but yes, you can make composer install binaries. packages like phpunit and sphinx do it. 
https://getcomposer.org/doc/articles/vendor-binaries.md

**Comment by Seldaek** [comment]
yeah `composer exec ...` is the equivalent of `npx ...` for vendor-installed binaries I would think.

**Comment by DasdWaller** [comment]
Npx can execute from modules and the server. `composer exec` execute from the local vendor only.
Example:
I have the package laravel on packagist server and i want to execute without composer install it.

**Comment by Seldaek** [comment]
Yeah sorry that's not supported and I doubt we'll add support for it..

**Comment by DasdWaller** [comment]
Thanks for the replay @Seldaek
You know if exist a plugin for it?

**Comment by Seldaek** [comment]
Never heard of one.. should be possible to do I guess

**Comment by DasdWaller** [comment]
Its ok. Thanks for the replay.
