### ISSUE TITLE
Feature request: Minimum stability flag through a command line option

### ISSUE THREAD

**Issue by soyuka** [composer/composer#9441]
Would you accept a command line option to specify the minimum stability. For example:

```
composer update --minimum-stability=dev
```

This would not persist the flag though, or should it?

**Comment by Seldaek** [comment]
No because this would make the lock file out of sync with the composer.json if it does not persist. If you want to persist it you should rather do `composer config minimum-stability dev` then `composer update`.

**Comment by soyuka** [comment]
Indeed that's silly I should've though about that. Thanks!
