### ISSUE TITLE
Feature Request: CLI flag to hide funding messages

### ISSUE THREAD

**Issue by deanc** [composer/composer#9444]
```
64 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

I'd like to propose a feature flag to hide this output. When debugging failed container builds, I'd like to only see the absolute necessary output from composer to allow me to diagnose the issue. I'm all for keeping it in development, and the supporting of OSS work, but it'd be nice to keep things quiet in our hosting environment where it's only seen or viewed when we have issues.

Perhaps, this could be a consequence of `--no-dev` or `--optimize-autoloader` also?

**Comment by Seldaek** [comment]
We could perhaps hide it in --no-dev, but if you really want minimal output note that there is --quiet :)

**Comment by deanc** [comment]
Perhaps --quiet is a little on the quiet side ;-) Note that npm has this flag: https://2fwd1back.com/til-how-to-remove-npm-fund-message/

**Comment by Seldaek** [comment]
Yeah a config value would be a more explicit/self-documenting alternative to hiding it implicitly sometimes.

**Comment by deanc** [comment]
I could probably give writing a PR for this a go @Seldaek if it's likely to be accepted. If I'm right in understanding the PR would need to have the following:
- New configuration setting e.g. `'hide-funding' => false`
- Patch for the installer to hide the message if the value is set to true

Anything else?

**Comment by Seldaek** [comment]
New config values need to be added to res/composer-schema.json, and the config docs, and Config.php and ConfigCommand so it's editable via CLI.. lots of small changes, but it's not super hard :)

So yeah feel free to have a go I'd say.
