### ISSUE TITLE
Upgrade symfony/console version

### ISSUE THREAD

**Issue by josefglatz** [composer/composer#9445]
Are there plans to upgrade the dependency/console version to the latest stable version? Many useful commands are missing if you like to use symfony/console in an composer-plugin package.

**Comment by josefglatz** [comment]
Or if no plans to upgrade? Are there reasons why not upgrading this component?

**Comment by josefglatz** [comment]
Ah I see.. composer still supports PHP 5.3 and therefore symfony/console:2.8.52

**Comment by Seldaek** [comment]
Yup, this will be fixed in Composer 2.2 once we drop older PHP versions.

**Comment by josefglatz** [comment]
Thank you!
