### ISSUE TITLE
export-ignore ignored

### ISSUE THREAD

**Issue by jamielsharief** [composer/composer#9446]
Previously I could add something like `/tests export-ignore` to `.gitattributes` and when composer installs the package, it will remove those files, however I have noticed when installing packages recently the `.gitattributes` file is being ignored. 

Has composer changed the way it downloads the archive from github?

**Comment by stof** [comment]
Composer does not remove the files. GitHub removes the files when generating the archive.
And this also means that if the package gets installed from source rather than from dist, the files will be there (as `git clone` does not remove the files)

**Comment by jamielsharief** [comment]
Sorry what I meant was when the archive was generated those files are removed (not by composer). I have tried this morning and no problem, so maybe i used the prefer source option.
