### ISSUE TITLE
composer requires credentials from github when downloading from gitlab

### ISSUE THREAD

**Issue by henze-housepedia** [composer/composer#9447]
Output of `composer diagnose`:

```
Checking composer.json: 
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.6
PHP version: 7.4.12
PHP binary path: /usr/local/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
cURL version: 7.69.1 libz 1.2.11 ssl OpenSSL/1.1.1g
zip extension: OK
```

When I run this command inside a docker container:

```
composer require --dev haydenpierce/class-finder
```

I get the following output:

Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+2078118251b3+2020-11-09+1042
to retrieve a token. It will be stored in "/home/www-data/.composer/auth.json" for future use by Composer.
Token (hidden): 

And I expected this to happen:
The package is installed and added to the dev tree in composer.json

Additional information:
The package is hosted on gitlab. So why composer meeps about Github credentials beats me...
I have also reported this bug there, it might be a configuration issue. https://gitlab.com/hpierce1102/ClassFinder/-/issues/16

**Comment by Seldaek** [comment]
Do you have other github repositories in there? Who knows as you did not include full output of -vvv, nor your composer.json.. Please follow the issue template if you want help.

**Comment by henze-housepedia** [comment]
You're right, it was something else.
