### ISSUE TITLE
dev-master as x inline aliasing regressions/issues

### ISSUE THREAD

**Issue by dereuromark** [composer/composer#9448]
My `composer.json`:

```json
"dereuromark/cakephp-ide-helper": "dev-master as 1.8.2",
```
This is also what is already installed (in lock file).

When I run this command:

```
composer require --dev dereuromark/cakephp-ide-helper-extra:dev-master
```

I get the following output:

```
Problem 1
    - Root composer.json requires dereuromark/cakephp-ide-helper-extra dev-master -> satisfiable by dereuromark/cakephp-ide-helper-extra[dev-master].
    - dereuromark/cakephp-ide-helper-extra dev-master requires dereuromark/cakephp-ide-helper ^1.3.0 -> found dereuromark/cakephp-ide-helper[1.3.0, ..., 1.8.2] but it conflicts with your root composer.json require (dev-master as 1.8.2).

```

The installed version already matches the requirements (1.8.2 is inside `^1.3`). So the error here is false positive.
If I manually put the the line in:
```json
"dereuromark/cakephp-ide-helper-extra": "dev-master",
```

It just does
```
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking dereuromark/cakephp-ide-helper-extra (dev-master c9d9c46)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Syncing dereuromark/cakephp-ide-helper-extra (dev-master c9d9c46) into cache
  - Installing dereuromark/cakephp-ide-helper-extra (dev-master c9d9c46): Cloning c9d9c46088 from cache
```
and all works.

So that proves that there is an issue with require calls and inline aliasing (for testing some branch).

Note: the same issue appears also for "composer update -W" and inline aliasing used there, if nothing got changed it still errors here too with "it cannot update".

**Comment by Seldaek** [comment]
This is related to https://github.com/composer/composer/issues/9466 somehow. The fact is that the `as 1.8.2` bit is not stored in lock file initially as the alias is not used/needed, and thus not marked installed.

Then when you add the -extra package, it suddenly becomes required, but the alias is not known to the lock file, and as require does a partial update the dereuromark/cakephp-ide-helper version is simply dev-master without alias.

Doing the require with `-W` fixes it as it loads `dereuromark/cakephp-ide-helper` fully and not only from lock file anymore. Doing the `composer update` way also does that, so it works around the problem.

We need to think a bit about what can be done here: either we always load the root aliases even for locked packages, or we need to always store aliases in lock file even if unused.

**Comment by dereuromark** [comment]
Yeah, our complete tooling has now problems with this.
As we incrementally update certain module constraints using normal `composer update ...` syntax - and now it always fails on every call with this issue. as soon as there is one dev-master involved in the root composer.json.

**Comment by Seldaek** [comment]
Ok weird..

```
$ rm -rf vendor/ composer.*; composer require 'dereuromark/cakephp-ide-helper:dev-master as 1.8.2' -n
./composer.json has been created
Running composer update dereuromark/cakephp-ide-helper
Loading composer repositories with package information
Updating dependencies
Lock file operations: 24 installs, 0 updates, 0 removals
  - Locking aura/intl (3.0.0)
  - Locking cakephp/bake (2.2.0)
  - Locking cakephp/cakephp (4.1.6)
  - Locking cakephp/chronos (2.0.6)
  - Locking cakephp/twig-view (1.1.1)
  - Locking composer/ca-bundle (1.2.8)
  - Locking dereuromark/cakephp-ide-helper (dev-master ab844c2)
  - Locking jasny/twig-extensions (v1.3.0)
  - Locking laminas/laminas-diactoros (2.4.1)
  - Locking laminas/laminas-httphandlerrunner (1.2.0)
  - Locking laminas/laminas-zendframework-bridge (1.1.1)
  - Locking psr/http-client (1.0.1)
  - Locking psr/http-factory (1.0.1)
  - Locking psr/http-message (1.0.1)
  - Locking psr/http-server-handler (1.0.1)
  - Locking psr/http-server-middleware (1.0.1)
  - Locking psr/log (1.1.3)
  - Locking psr/simple-cache (1.0.1)
  - Locking sebastian/diff (4.0.4)
  - Locking squizlabs/php_codesniffer (3.5.8)
  - Locking symfony/polyfill-ctype (v1.20.0)
  - Locking symfony/polyfill-mbstring (v1.20.0)
  - Locking twig/markdown-extra (v3.1.1)
  - Locking twig/twig (v3.1.1)

$ composer require --dev dereuromark/cakephp-ide-helper-extra:dev-master
./composer.json has been updated
Running composer update dereuromark/cakephp-ide-helper-extra
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires dereuromark/cakephp-ide-helper-extra dev-master -> satisfiable by dereuromark/cakephp-ide-helper-extra[dev-master].
    - dereuromark/cakephp-ide-helper-extra dev-master requires dereuromark/cakephp-ide-helper ^1.3.0 -> found dereuromark/cakephp-ide-helper[1.3.0, ..., 1.8.2] but it conflicts with your root composer.json require (dev-master as 1.8.2).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

$ composer require --dev dereuromark/cakephp-ide-helper-extra:dev-master -W
./composer.json has been updated
Running composer update dereuromark/cakephp-ide-helper-extra --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking dereuromark/cakephp-ide-helper-extra (dev-master c9d9c46)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Syncing dereuromark/cakephp-ide-helper-extra (dev-master c9d9c46) into cache
  - Installing dereuromark/cakephp-ide-helper-extra (dev-master c9d9c46): Cloning c9d9c46088 from cache
Generating autoload files
10 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

You can't reproduce this?

**Comment by dereuromark** [comment]
Well, with "we" I man now Spryker and the composer.json used there internally.
A bit more complex setup.
But I think it boils down do a similar issue with the versions not being stored and thus it not being able to positively continue.

**Comment by Seldaek** [comment]
Ok, I am just worried that if -W does not fix it for your setup it may be another issue, but I guess we'll see once I got a fix ready.

**Comment by Seldaek** [comment]
You can try with https://github.com/composer/composer/pull/9468 if that fixes it for you.. some test failures still tho so not sure the fix is correct but I gotta call it a day.

**Comment by Seldaek** [comment]
Ok this took quite a few iterations but I think we got a correct fix now :)

The fix however requires that you update the package with the alias first once, so the alias makes it into the lock file. You can try with `composer self-update --snapshot`.

**Comment by Seldaek** [comment]
FYI 2.0.7 is now out with the fix
