### ISSUE TITLE
ErrorException: proc_open(): fork failed - Cannot allocate memory in phar

### ISSUE THREAD

**Issue by yooper** [composer/composer#945]
ErrorException: proc_open(): fork failed - Cannot allocate memory in phar:///var/www/workspace/MyProject/build/composer/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php on line 943

Call Stack:
    0.0523     765208   1. {main}() /var/www/workspace/MyProject/build/composer/composer.phar:0
    0.0528     763216   2. require('phar:///var/www/workspace/MyProject/build/composer/composer.phar/bin/composer') /var/www/workspace/MyProject/build/composer/composer.phar:15
    0.0830    3504584   3. Composer\Console\Application->run() phar:///var/www/workspace/MyProject/build/composer/composer.phar/bin/composer:13
    0.0865    3865984   4. Symfony\Component\Console\Application->run() phar:///var/www/workspace/MyProject/build/composer/composer.phar/src/Composer/Console/Application.php:66
   31.9725  246198552   5. Symfony\Component\Console\Application->renderException() phar:///var/www/workspace/MyProject/build/composer/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:113
   31.9726  246199624   6. Symfony\Component\Console\Application->getTerminalWidth() phar:///var/www/workspace/MyProject/build/composer/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:771
   31.9726  246199784   7. Symfony\Component\Console\Application->getSttyColumns() phar:///var/www/workspace/MyProject/build/composer/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:848
   31.9727  246202984   8. proc_open() phar:///var/www/workspace/MyProject/build/composer/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:943
   31.9728  246204736   9. Composer\Util\ErrorHandler::handle() phar:///var/www/workspace/MyProject/build/composer/composer.phar/src/Composer/Util/ErrorHandler.php:0

**Comment by sivagurupr** [comment]
I try to insert using ajax,but that's not working,error is:uncaught exception: out of memory

**Comment by KingCrunch** [comment]
@sivagurupr I don't know, what you are talking about, but I've the feeling, that it is not related to this issue. Composer (CLI) doesn't have any ajax-capabilities :confused: However, at the end and after reading the comments "out of memory" should be self-explaining :wink:

**Comment by sivagurupr** [comment]
Anything mistake in this code....

**Comment by crisu83** [comment]
I ran ran into this issue when installing http://github.com/sabre/xml on a Vagrant machine. However I managed to fix it by enabling swapping using the example above.

**Comment by pioneerwebsites** [comment]
I have the same error but with a large instance: 4gb RAM and 4gb swap. The free RAM is never exhausted, let alone the available/cached RAM, and the swap isn't touched!

It's the first time running composer update on this new machine, CentOS/CloudLinux 7.1.

Any ideas? Please?

**Comment by vjroby** [comment]
I had the same error running in my Vagrant Box. I had 2gb of ram when I got the error. I extended the ram to 4gb and it worked. But, still it's weird that it needs so much ram.

**Comment by paparts** [comment]
I ran into this problem again and adding the composer.lock didn't work. But instead I tried to use swap space instead of extending much memory. An article on digitalocean is quite nifty https://www.digitalocean.com/community/tutorials/how-to-configure-virtual-memory-swap-file-on-a-vps

**Comment by c9s** [comment]
I also encountered the problem:

```
PHP Warning:  proc_open(): fork failed - Cannot allocate memory in phar:///home/c9s/netbase-guide/sculpin.phar/vendor/symfony/console/Symfony/Component/Console/Application.php on line 974
```

**Comment by Hukuta** [comment]
> I was also having this issue but increasing the PHP memory_limit solved the problem.

me too

**Comment by dkinzer** [comment]
Was running into the same issue with `memory_limit` set to -1.  The only thing that worked for me was reloading my machine.

**Comment by koriym** [comment]
How To Add Swap on Ubuntu 14.04
https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04

This article helped me for 512M RAM instance.

**Comment by i-allan** [comment]
If you are running this virtual machine, Update memory to 1024MB. 

Worked for me

**Comment by vjrngn** [comment]
Awesome! Thanks for this. Saved me a LOT of headache.

**Comment by sergiohermes** [comment]
Stop mysql httpd or nginx service and run again

Run composer

And restart services

**Comment by KingCrunch** [comment]
HI @sergiohermes 

This only works, when nginx and/or mysql coincidentally consumes that much memory, that composer misses. Also stopping essential services is probably not an option in most cases. You should really invest in memory, either physically, or in form of a swap partition/file

**Comment by sergiohermes** [comment]
I understand, anyway it was a way without having to swap.
The most appropriate but is to create a swap. Without a doubt.
Taking a look found for "centos" an interesting reference.

[https://www.digitalocean.com/community/tutorials/additional-recommended-steps-for-new-centos-7-servers](https://www.digitalocean.com/community/tutorials/additional-recommended-steps-for-new-centos-7-servers)

I believe will add this thread.

**Comment by Wallcg** [comment]
Oh,I use swap solve it,thanks

**Comment by mohitg-bs** [comment]
You can avoid this either by increasing the memory size from `php.ini` file, which is a wrong option. Better delete the cache and rebuild the packages.

    Delete composer cache: `sudo rm -R ~/.composer`
    Delete vendor folder: `sudo rm -R vendor`
    Rebuild the vendor packages: `composer update`

**Comment by KingCrunch** [comment]
@mohitg-bs I guess you mixed something up

- Removing files doesn't free up RAM
- It's not about PHPs `memory_limit`, but the (virtual) memory from the entire system. There is no ini setting, that can create you RAM.

**Comment by oussaka** [comment]
I solved the same problem in Vagrant.
I increased the value of **memory_limit**
and delete composer cache: **sudo rm -R ~/.composer**
and finally vagrant reload.

**Comment by akeif** [comment]
I had the same problem on a Virtual Box running through Vagrant.
Fixed by increasing VBox ram.

Config change from `vb.memory = 512` to `vb.memory = 1024`

**Comment by doingOO7** [comment]
I have added swap memory and it solved my issue.

**Comment by gillera235** [comment]
You ran out of swap memory, try this

/bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
/sbin/mkswap /var/swap.1
/sbin/swapon /var/swap.1

**Comment by shamun** [comment]
To add a swap file:

Determine the size of the new swap file in megabytes and multiply by 1024 to determine the number of blocks. For example, the block size of a 64 MB swap file is 65536.
At a shell prompt as root, type the following command with count being equal to the desired block size:
dd if=/dev/zero of=/swapfile bs=1024 count=65536
Setup the swap file with the command:
mkswap /swapfile
To enable the swap file immediately but not automatically at boot time:
swapon /swapfile
To enable it at boot time, edit /etc/fstab to include the following entry:
/swapfile swap swap defaults 0 0
The next time the system boots, it enables the new swap file.

After adding the new swap file and enabling it, verify it is enabled by viewing the output of the command cat /proc/swaps or free.

**Comment by dnorenavega-EDR** [comment]
thank you!

**Comment by therobyouknow** [comment]
Tips - if adding swap doesn't solve the composer out of memory/couldn't allocate error:
- Restart your machine after adding swap. I found composer error didn't go away after adding 8G of swap. But after restarting it worked.
- I also shut down another VM I was running and closed Chrome with too many tabs

(I'm using composer in a development environment on macOS X Sierra 10.12.4 with 16Gb RAM).

**Comment by artforlife** [comment]
Has this been resolved? I have update the Composer globally. In addition, I created a 1GB swap space per @gillera235 suggestion.  I still get the same error. What can I do to troubleshoot it?

If it helps, I using the free-tier micro EC2 instance.

**Comment by macpatel** [comment]
push the composer.lock file on your server and do 

composer --verbose install

this way it didn't take much memory and was superfast to install the updated packges according to versions in the composer.lock file.

**Comment by vjroby** [comment]
@sagarshah16  What happens if I don't have a mysql service?

**Comment by sagarshah16** [comment]
try to find which one of your running services takes more memory space. if it is not mysql.

**Comment by brutalcrozt** [comment]
yeah ig update composer should solve the problem, sadly i update via git bash. It always throw same error to update. So to windows users just make sure use `cmd.exe`.

**Comment by resting** [comment]
Hit the error earlier. Was on Ubuntu 16.04 on a EC2 micro instance.
Solved by adding a 1G swap file.

**Comment by nadeemse** [comment]
Just followed this link and resolved the issue. 

https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04

**Comment by sergiohermes** [comment]
``` 
$ apt install swapspace 
```
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
Reference:
http://manpages.ubuntu.com/manpages/xenial/man8/swapspace.8.html

Thank you Jeroen T. Vermeulen

````
Enthusiasm is the light of knowledge.
Unknown author.
````

````
O estusiasmo é luz do conhecimento.
Autor desconhecido.
````

**Comment by richRemer** [comment]
This issue can be exacerbated by not having memory over-commit enabled.  Forking is massively inefficient without memory over-commit.  Essentially when you fork, you double the committed memory usage of your current process by creating another identical process.  Much of this memory is shared between the parent and child processes, but is copy-on-write, so any writes will cause the shared memory to get copied.  When over-commit is enabled, your system allows this duplicated shared memory, but if you write to the shared memory, you might not have enough physical RAM to handle it.  With over-commit disabled, your system won't allow you to allocate the memory in the first place.

**Comment by ctrl-f5** [comment]
Getting this error with 1.4GIG available...

`$ free -m; composer require --dev phpro/grumphp
              total        used        free      shared  buff/cache   available
Mem:           2000         416        1277          21         305        1405
Swap:             0           0           0
Using version ^0.14.1 for phpro/grumphp
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 12 installs, 0 updates, 0 removals
  - Installing symfony/dependency-injection (v3.4.11): The following exception is caused by a lack of memory or swap, or not having swap configured
Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details

                                                     
  [ErrorException]                                   
  proc_open(): fork failed - Cannot allocate memory`

**Comment by Dhoot** [comment]
A fix for this problem is to add swap (i.e. paging) space to the instance.

Paging works by creating an area on your hard drive and using it for extra memory, this memory is much slower than normal memory however much more of it is available.

To add this extra space to your instance you type:

sudo /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
sudo /sbin/mkswap /var/swap.1
sudo chmod 600 /var/swap.1
sudo /sbin/swapon /var/swap.1

If you need more than 1024 then change that to something higher.

To enable it by default after reboot, add this line to /etc/fstab:

/var/swap.1   swap    swap    defaults        0   0

**Comment by shreyanshpanchal** [comment]
> @dhorrigan ouch according to the stack trace it looks like the fatal error was triggered while rendering an exception (since that uses proc_open to check for your terminal width). Looks like it's not a php memory limit but rather the machine's memory that ran out, so I would suggest clearing other things, and running it with install instead of update if you can run update somewhere else that has more memory. install from lock file uses very little memory.

Thanks so much, Instead of running `composer update`  i did  `composer install`. Which fixed it!

Its better to than having to increase memory size in php.ini or increasing instance memory itself.

**Comment by jemerocay** [comment]
Turning the swap on resolved my problem.

/bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
/sbin/mkswap /var/swap.1
 /sbin/swapon /var/swap.1

**Comment by er1z** [comment]
How many of you will post something what was written in this thread? @jemerocay, have you read the topic? The same is posted ~10 messages above.

Contributors: close this, please.
