### ISSUE TITLE
Increase phpstan level / introduce a phpstan baseline

### ISSUE THREAD

**Issue by staabm** [composer/composer#9450]
Hey guys!

I was wondering why composer uses phpstan at level 1.
This leaves behind a lot of opportunities, because phpstan will deliver more [important error at higher levels](https://phpstan.org/user-guide/rule-levels).

From my experience we should aim for at least level 5, which enables type-checking of arguments passed to methods and functions.

To ease the transition to higher levels [phpstan supports a baseline feature](https://phpstan.org/user-guide/baseline), which basically allows us to ignore all errors the codebase currently has.

After everything is setup this effectivly means new code introduced to the codebase benefits from those more usefull checks.
Still you could baseline/ignore errors which we think aren‘t worth to be fixed when developing new code.

Any opinions?

**Comment by Seldaek** [comment]
Yes we could do that.. though I'd also like to fix issues as much as possible (5.3 support and BC restrictions might make fixing some of it hard).

I think at latest 2.2 when we drop older PHP it might be a good time to do this.

**Comment by Seldaek** [comment]
This was done in a while back
