### ISSUE TITLE
Does not overwrite "corrupt" lock file with composer update

### ISSUE THREAD

**Issue by phil-davis** [composer/composer#9452]
Typical steps:

1) Have an old PR that has some change to `composer.json` (and thus also to the generated and committed `composer.lock`)
2) Other PRs have been merged to the main branch that changed `composer.json` and `composer.lock`
3) `git rebase main`
4) git finds conflicts in `composer.lock` and (sadly) puts `<<<<<<` `======` `>>>>>>` sections in to "help" a human resolve the conflicts

Actually we do not want any human to manually resolve the conflicts, we just want to tell composer to "regenerate" `composer.lock` from `composer.json`. Normally I just do:

5) `composer update`

And that does its thing from `composer.json`, and I can then proceed with the rebase process.

But with composer 2.0:

```
$ composer update

                                                                    
  [Seld\JsonLint\ParsingException]                                  
  "./composer.lock" does not contain valid JSON                     
  Parse error on line 558:                                          
  ...srv"            ],<<<<<<< HEAD                                 
  --------------------^                                             
  Expected: 'STRING' - It appears you have an extra trailing comma  
```

This is a change in behaviour. In composer 1.* it seems that the content of `composer.lock` was ignored when doing a "general" `composer update`. `composer.json` would be parsed and a whole new `composer.lock` would be generated and would overwrite the existing `composer.lock` without ever needing to look in the existing `composer.lock`

The simple workaround is to do:
```
rm composer.lock
```

Then do the `composer update` and proceed with the rebase.

IMO there may be nothing to do here - the workaround is simple. So feel free to close. But I am reporting because it is a workflow change.

**Comment by Seldaek** [comment]
Thanks for the report, I don't think this was intentional, just a result of some refactorings
