### ISSUE TITLE
composer2 dump-auto :    Cannot declare class Composer\Autoload\ComposerStaticInit

### ISSUE THREAD

**Issue by arsArtD** [composer/composer#9453]
after excute command(my composer version is 2): composer dump-autoload ， when i visit my web api , error like blow:   

Cannot declare class Composer\Autoload\ComposerStaticInit

the error comes from this file:     vendor/composer/autoload_real.php

```
  public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit67371839b8b21190eca0fc0bf9405146', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader();
        spl_autoload_unregister(array('ComposerAutoloaderInit67371839b8b21190eca0fc0bf9405146', 'loadClassLoader'));

        $useStaticLoader = PHP_VERSION_ID >= 50600 && !defined('HHVM_VERSION') && (!function_exists('zend_loader_file_encoded') || !zend_loader_file_encoded());
        if ($useStaticLoader) {
            require __DIR__ . '/autoload_static.php';  // **this should be require_once ?**

            call_user_func(\Composer\Autoload\ComposerStaticInit67371839b8b21190eca0fc0bf9405146::getInitializer($loader));
        } else {
            $map = require __DIR__ . '/autoload_namespaces.php';
            foreach ($map as $namespace => $path) {
                $loader->set($namespace, $path);
            }

            $map = require __DIR__ . '/autoload_psr4.php';
            foreach ($map as $namespace => $path) {
                $loader->setPsr4($namespace, $path);
            }

            $classMap = require __DIR__ . '/autoload_classmap.php';
            if ($classMap) {
                $loader->addClassMap($classMap);
            }
        }

        $loader->register(true);

        if ($useStaticLoader) {
            $includeFiles = Composer\Autoload\ComposerStaticInit67371839b8b21190eca0fc0bf9405146::$files;
        } else {
            $includeFiles = require __DIR__ . '/autoload_files.php';
        }
        foreach ($includeFiles as $fileIdentifier => $file) {
            composerRequire67371839b8b21190eca0fc0bf9405146($fileIdentifier, $file);
        }

        return $loader;
    }
```

**Comment by arsArtD** [comment]
fix usage:   
src/Composer/Autoload/AutoloadGenerator.php

line 840:     require __DIR__ . '/autoload_static.php';  --------------> require_once __DIR__ . '/autoload_static.php';

**Comment by Seldaek** [comment]
How come this gets included twice? The getLoader function caches its result so it should never include the file twice. Are you including autoload_static.php yourself before including `vendor/autoload.php` somehow? Can you perhaps add this to the top of autoload_real.php then see where it gets included from?

```
var_dump(array_map(function($a){ unset($a['args'], $a['object']); return $a; }, debug_backtrace()));
```

**Comment by stof** [comment]
another question. Are you using `pthreads` to fork the process somehow ? Maybe that causes the static state to be reset while the class is loaded.

**Comment by arsArtD** [comment]
> another question. Are you using `pthreads` to fork the process somehow ? Maybe that causes the static state to be reset while the class is loaded.

not use pthreads

**Comment by arsArtD** [comment]
> How come this gets included twice? The getLoader function caches its result so it should never include the file twice. Are you including autoload_static.php yourself before including `vendor/autoload.php` somehow? Can you perhaps add this to the top of autoload_real.php then see where it gets included from?
> 
> ```
> var_dump(array_map(function($a){ unset($a['args'], $a['object']); return $a; }, debug_backtrace()));
> ```

i use thinkphp framework. i found the framework require composer_static.php before inlcude vendor/autoload.php.

this is the cause. so can composer2 fix this? may other framework has this problem so.

**Comment by Seldaek** [comment]
No we are not going to fix this unless someone from the framework can explain why it's a good idea.. I can't think of a good reason to do this.

As far as I can tell, https://github.com/top-think/think/blob/6.0/public/index.php#L15 only requires vendor/autoload.php - I am not sure why anyone would require the static file directly. Are you sure you did not add this yourself somehow?

**Comment by arsArtD** [comment]
> No we are not going to fix this unless someone from the framework can explain why it's a good idea.. I can't think of a good reason to do this.
> 
> As far as I can tell, https://github.com/top-think/think/blob/6.0/public/index.php#L15 only requires vendor/autoload.php - I am not sure why anyone would require the static file directly. Are you sure you did not add this yourself somehow?

https://github.com/top-think/framework/blob/v5.0.24/library/think/Loader.php 
now i use this version of thinkphp framework. line 290; this line requires autoload_static.php

**Comment by Seldaek** [comment]
But this code seems to replace/include the whole composer loader.. Do you really need to include vendor/autoload.php then? I think it might not be necessary.

**Comment by arsArtD** [comment]
> But this code seems to replace/include the whole composer loader.. Do you really need to include vendor/autoload.php then? I think it might not be necessary.

ok. you are right.  this quesiton can close now. thanks a lot!

**Comment by Seldaek** [comment]
Ok great it's resolved.

**Comment by AmnaIqbal-01** [comment]
> Ok great it's resolved.

how you resolved it? I am having the same issue.
