### ISSUE TITLE
Composer-v2 run-script output regression

### ISSUE THREAD

**Issue by ktomk** [composer/composer#9454]
Given a composer-script:

~~~
{
  "scripts": {
    "cat": ["cat vendor/composer/LICENSE"]
  }
}
~~~

When running this script with Composer v1, then following output is given:

~~~
$ VER=1; composer -q self-update --$VER && composer --version
Composer version 1.10.17 2020-10-30 22:31:58
$ composer run-script cat >/dev/null
> cat vendor/composer/LICENSE
~~~
_(the redirection to `/dev/null` effectively hides the cat script output, only the informal message by composer run-script is given on standard error)_

when running this script with Composer v2, then following output is given:

~~~
$ VER=2; composer -q self-update --"$VER" && composer --version
Composer version 2.0.6 2020-11-07 11:21:17
$ composer run-script cat >/dev/null
> cat vendor/composer/LICENSE

Copyright (c) Nils Adermann, Jordi Boggiano

Permission is hereby granted, free of charge, to any person obtaining a copy
[...]
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
~~~
_(shortened, the redirection to `/dev/null` is not in effect [/edit: for the scripts output])_

Expected behaviour:

The redirection is in effect (the behaviour of Composer v1).

Additional Info:

Running on Ubuntu 18.04 LTS in standard bash shell.

Standard error is unchanged.

First noticed it with a php script, then reduced the example to cat for the report.

Also disabled as much as possible in php to run it with the minimal setup possible, in php 7.1/2/3/4 and 8.0

~~~
php -n -dextension=phar.so -dextension=json.so -f "$HOME/bin/composer" -- run-scrip cat >/dev/null
~~~

**Comment by Seldaek** [comment]
Ok this is because Composer 2 enabled TTY forwarding for scripts, which is nice cause they then have access to user input etc, but it also seems to be bypassing the output redirecting done on the composer process.

If you pass -n / --no-interaction TTY mode is disabled and it then pipes all output through composer, which restores the 1.x mode.

I don't *think* there's a way for us to fix this, but if someone has a clue I'm all ears.

**Comment by dzuelke** [comment]
Could you from the calling code use `stream_isatty()` to see whether stdout is a TTY, and if not, auto-disable TTY mode, @Seldaek?

But I am also not sure if I understand the problem here right - does this "TTY forwarding" mean the called program's stdout is redirected to the caller's stderr? It has to, right? Otherwise the output wouldn't show up in the outer call. Can't that be changed?

**Comment by dzuelke** [comment]
Mind the wording in the issue description saying "the redirection to `/dev/null` is not in effect" - that's incorrect. The redirection *is* in effect, it's just that the output from the called program is not going to stdout but somewhere else.

**Comment by dzuelke** [comment]
Also what exactly is "TTY mode"? 🧐 Is that a Symfony Process thing?

**Comment by ktomk** [comment]
Indeed, `-n` gives the previous behaviour.

And just wanted to comment on the same, monkey patched it, this prevents it:

~~~
    protected function executeTty($exec)
    {
        if (function_exists('stream_isatty') && !stream_isatty(STDOUT)) {
            return $this->process->execute($exec);
        }

~~~

@dzuelke: Yes it's in the Symfony Process package.

**Comment by Seldaek** [comment]
TTY forwarding essentially sets the pipes to:

            return array(
                array('file', '/dev/tty', 'r'),
                array('file', '/dev/tty', 'w'),
                array('file', '/dev/tty', 'w'),
            );

See https://github.com/symfony/process/blob/5.x/Pipes/UnixPipes.php#L59

So yeah that explains it I guess. It just goes to the terminal directly.. This helps explain a little https://stackoverflow.com/a/4426291/6512

**Comment by ktomk** [comment]
@dzuelke Yes, it's correct that the redirection to /dev/null still is in effect, just not for the scripts output as you highlight it as well.

The problem however is that now script output can't be redirect any longer on the command-line.

the `stream_isatty()` check on stdout looks good though to leviate the issue while the tty feature can still be the default.

**Comment by Seldaek** [comment]
It doesn't seem to work for me stream_isatty(STDOUT) always returns false (I'm using ubuntu via WSL2 on windows which might be the cause). But that said, `fgets(STDIN);` works fine for me, so not sure I want to disable this based on stream_isatty :/

**Comment by dzuelke** [comment]
What about `posix_isatty` @Seldaek?

**Comment by ktomk** [comment]
No WSL here for testing. I wonder what the output of `php_uname()` gives, also for `s`, `r` and `v` as parameter @Seldaek.

**Comment by Seldaek** [comment]
Also false, posix_ttyname also false. For STDERR though it works tho..

But I think I figured it out, seems to be the [xdebug-handler's passthru](https://github.com/composer/xdebug-handler/blob/6e076a124f7ee146f2487554a94b6a19a74887ba/src/XdebugHandler.php#L263) which messes things up for STDOUT.

I can repro this in a standalone test script, and in Composer it works fine with COMPOSER_ALLOW_XDEBUG=1 set.

So I guess maybe we need to change that to run with proc_open hoping that lets us fix it (cc @johnstevenson if you have time to give this a shot), or.. hopefully xdebug3 won't require us to disable it anymore :)

**Comment by ktomk** [comment]
Indeed `passthru()` effectively redirects, hence not a tty. `proc_open()` does not have this effect, `isatty(STDOUT)` returns `true` within:

~~~
$ php -r "$(cat <<'PHP'
echo "passthru: "; passthru(PHP_BINARY . " -r 'var_dump(stream_isatty(STDOUT));'");

echo "proc_open: "; $h = proc_open(PHP_BINARY . " -r 'var_dump(stream_isatty(STDOUT));'", [], $p);
for (; $s = proc_get_status($h) and $s['running'];) usleep(100);
proc_close($h);

echo "direct: "; var_dump(stream_isatty(STDOUT));
PHP
)"
passthru: Command line code:1:
bool(false)
proc_open: Command line code:1:
bool(true)
direct: Command line code:7:
bool(true)
~~~

Was the close of the issue intended? @Seldaek 

Also I found an alternative location to patch this in composer, which is within the `\Composer\IO\ConsoleIO::isInteractive` implementation.

**Comment by Seldaek** [comment]
Good point, I patched the IO too in https://github.com/composer/composer/commit/380dce9a6b2886f1ff89103ea170092abe8866f5 - I hope this won't cause any regressions but I'm fairly sure someone somewhere will complain :s

**Comment by ktomk** [comment]
Complaints everywhere :) - I hope my report didn't sound too complaining.

Just FYI, when patched in IO, then the earlier patch is not necessary as it is checked on that path, too.

Filed a PR: https://github.com/composer/composer/pull/9461

**Comment by Seldaek** [comment]
Hah no I would not consider this here a complaint.
