### ISSUE TITLE
documentation for another languages

### ISSUE THREAD

**Issue by parsampsh** [composer/composer#9456]
HI. Can you accept changes for documentation in other languages? This means moving the content of `doc/` to `doc/en` and creating documentation for new languages. If you accept, I can translate and maintain the ‍`Persian‍` language for composer documentation.

**Comment by Seldaek** [comment]
I'd prefer if this was done in a fork/different repo, so we don't have to maintain this and merge etc. If you do complete it and publish it somehow I'm happy to link to it from the main doc though.

**Comment by parsampsh** [comment]
yes, you are right. I will complete that soon :)
