### ISSUE TITLE
Version information not yet available in scripts for post-update-cmd and post-install-cmd

### ISSUE THREAD

**Issue by frankvanhest** [composer/composer#9457]
Hi there,

After discussing the issue https://github.com/Roave/you-are-using-it-wrong/issues/95 it seems that the package version is not yet available when running scripts for post-update-cmd and post-install-cmd.
I'm using composer v2.0.6. 

I don't know if this is the correct repo for this issue. It was suggested in the original issue mentioned before.

Thank you in advance and it you need more information, let me know.

Cheers, Frank

**Comment by Seldaek** [comment]
Indeed @adamturcsan the data was not available at runtime, which was an oversight. It was thought of to be used by the project and not by plugins, but plugins are also a valid use case for sure. Please confirm it works with `composer self-update --snapshot`

**Comment by frankvanhest** [comment]
@Seldaek and @adamturcsan Thank you both for your time and effort. I can confirm the correct installed versions are now used.

**Comment by adamturcsan** [comment]
@Seldaek Thanks for the rapid action! It works for me too :)

**Comment by asgrim** [comment]
thank you @Seldaek :tumbler_glass:++
