### ISSUE TITLE
Composer Installation Throwing  SSL certificate problem

### ISSUE THREAD

**Issue by Surbhi27946** [composer/composer#9459]
I am trying to install composer.json inside my dockerfile using the following curl command :

RUN curl -sSk https://getcomposer.org/installer -o /tmp/composer-setup.php && php /tmp/composer-setup.php --install-dir /usr/local/bin --filename=composer

This command was working fine till last week , but now throwing the following error : 

**curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html**

**curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
The command '/bin/sh -c curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php && php /tmp/composer-setup.php --install-dir /usr/local/bin --filename=composer' returned a non-zero code: 60**

Can anyone please tell what is the issue?

**Comment by Seldaek** [comment]
The certificate (Let's encrypt) was issued on September 29th so if it started breaking in the last week it can't be that.

Might be something changed on your base docker environment? Misconfigured CA bundle or something?

**Comment by lukeholder** [comment]
I am also having ssl connection problems with composer v2:

```
➜  ~ composer diagnose   
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: FAIL
[Composer\Downloader\TransportException] Recv failure: Connection reset by peer
Checking https connectivity to packagist: FAIL
[Composer\Downloader\TransportException] OpenSSL SSL_connect: Connection reset by peer in connection to repo.packagist.org:443 
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: FAIL
[Composer\Downloader\TransportException] OpenSSL SSL_connect: Connection reset by peer in connection to getcomposer.org:443 
Composer version: 2.0.6
PHP version: 7.4.12
PHP binary path: /usr/local/Cellar/php/7.4.12/bin/php
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
cURL version: 7.73.0 libz 1.2.11 ssl OpenSSL/1.1.1h
zip extension: OK
```

Everything works fine on Composer 1.

**Comment by Seldaek** [comment]
The fact you got a `Recv failure: Connection reset by peer` on the http (not SSL) check leads me to think there's a deeper network issue at play here than SSL.

Please report a new issue following the issue template carefully, that might give us more useful information.

**Comment by lukeholder** [comment]
Will do.

**Comment by unional** [comment]
I'm also getting `SSL certificate problem: unable to get local issuer certificate` error.
In my case it is in a Windows environment.
The configuration was working with composer 1.x and once I upgrade it to 2.x it stopped working.

My environment connects to Artifactory and is using a self signed certificate.

Simplified `composer.json`:
```js
{
  "config": {
    "disable-tls": true
  },
  "repositories": [
    {
      "type": "composer"
      "url": "https://<artifactory-composer-repo>",
      "options": {
        "ssl": {
          "verify_peer": true,
          "allow_self_signed": true
        }
      }
    }]
}
```

**Comment by Surbhi27946** [comment]
For me the issue got resolved by setting up HTTP_PROXY inside the dockerfile.
