### ISSUE TITLE
Aliases missing from composer.lock in 2.0.6

### ISSUE THREAD

**Issue by brandonkelly** [composer/composer#9466]
My `composer.json`:

```json
{
  "require": {
    "craftcms/cms": "3.5.15.1",
    "craftcms/redactor": "v2.x-dev as 2.8.5"
  }
}
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.6
PHP version: 7.4.11
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
cURL version: 7.68.0 libz 1.2.11 ssl OpenSSL/1.1.1f
zip extension: OK
```

When I run `composer update` with Composer 1, `composer.lock` will list the `craftcms/redactor` alias:

```json
    "aliases": [
        {
            "alias": "2.8.5",
            "alias_normalized": "2.8.5.0",
            "version": "2.9999999.9999999.9999999-dev",
            "package": "craftcms/redactor"
        }
    ],
```

However if I run `composer update` with Composer 2.0.6, the `aliases` array is empty:

```
    "aliases": [],
```

**Comment by Seldaek** [comment]
It's not listed because it is not used/necessary.

i.e. this resolves just fine:

```
{
  "require": {
    "craftcms/cms": "3.5.15.1",
    "craftcms/redactor": "v2.x-dev"
  }
}
```

**Comment by Seldaek** [comment]
Why is this a problem though?

**Comment by brandonkelly** [comment]
Same reason as #9467 – at first I was thinking I’d just parse `composer.lock` to find the alias, but then noticed the array is empty in v2. Having a `getAlias()` method would have been just a little bit cleaner and more performant.

Reported this separately because it feels more like a bug. If it’s intended to not list the aliases, why write out the empty `aliases` array in the first place?

**Comment by Seldaek** [comment]
As I said it lists the alias *if they are used*. But anyway we changed this in https://github.com/composer/composer/pull/9475 so now inline aliases from the composer.json will always be listed.

As for https://github.com/pixelandtonic/craftnet/commit/d6c7eee35aaa29b2137c461360c6ce074520a820 - you could instead check whether the normalized version starts with `dev-`. If it does, it is a non-numeric version and then you probably can't list anything (or maybe you can find it in the aliases).

But if the version is numeric, like in your 2.x-dev case, it'll normalize to `2.9999999.9999999.9999999-dev` which you can use to compare releases just fine I think.
