### ISSUE TITLE
Add InstalledVersions::getAlias()

### ISSUE THREAD

**Issue by brandonkelly** [composer/composer#9467]
It would be great if the new InstalledVersions class could start exposing the alias used (if any) via a new `getAlias()` method, which accepts a package name.

**Comment by Seldaek** [comment]
That's unfortunately not so easy I think as we don't really keep track of which alias is used, but we could possibly list all aliases a package has. 

What's the use case though?

**Comment by brandonkelly** [comment]
Trying to look into whether we (Craft CMS) can provide better update info for plugins with a dev-stability version installed (https://github.com/craftcms/cms/issues/7098), based on version alias that may have been specified in composer.json. 

If it’s not definitive then no big deal.
