### ISSUE TITLE
composer selfupdate -- 1

### ISSUE THREAD

**Issue by boan-jfm** [composer/composer#9472]
I had some constrains on composer 1 and needed to downgrade from version 2, but got this error:

Command: `composer selfupdate -- 1`
```
Upgrading to version 1 (stable channel).
[Composer\Downloader\TransportException]
  The "https://getcomposer.org/download/1/composer.phar.sig" file could not be downloaded (HTTP/2 404 )
```

**Comment by johnstevenson** [comment]
Use `composer selfupdate --1` (there is no space in the option)

**Comment by Chrisreece724** [comment]
that is a basic HTTP error, there is no error on the composer part, as @johnstevenson  has advised above, it should work now
