### ISSUE TITLE
Trying to install any remote deps or self updating results in an SSL error

### ISSUE THREAD

**Issue by lukeholder** [composer/composer#9476]
My `composer.json`:

```json
NA
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: FAIL
[Composer\Downloader\TransportException] OpenSSL SSL_connect: Connection reset by peer in connection to repo.packagist.org:443 
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: FAIL
[Composer\Downloader\TransportException] OpenSSL SSL_connect: Connection reset by peer in connection to getcomposer.org:443 
Composer version: 2.0.6
PHP version: 7.4.12
PHP binary path: /usr/local/Cellar/php/7.4.12/bin/php
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
cURL version: 7.73.0 libz 1.2.11 ssl OpenSSL/1.1.1h
zip extension: OK

```

When I run this command:

```
composer self-update
```

I get the following output:

```
                                                                                      
  [Composer\Downloader\TransportException]                                            
  OpenSSL SSL_connect: Connection reset by peer in connection to getcomposer.org:443  
                                                                                      

self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--1] [--2] [--set-channel-only] [--] [<version>]
```

And I expected this to happen:

For it to self update.

`traceroute repo.packagist.org`

```
➜  ~ traceroute repo.packagist.org
traceroute to repo.packagist.org (142.44.164.249), 64 hops max, 52 byte packets
 1  usg (192.168.77.1)  1.712 ms  6.377 ms  1.431 ms
 2  203-219-198-52.tpgi.com.au (203.219.198.52)  359.614 ms  439.103 ms  493.723 ms
 3  203-219-199-193.tpgi.com.au (203.219.199.193)  644.537 ms  508.031 ms  610.723 ms
 4  syd-tpg-wat-crt2-ge-3-1.static.tpgi.com.au (203.26.22.125)  646.980 ms  679.965 ms  589.441 ms
 5  syd-apt-ros-int1-hu0-3-0-2.tpgi.com.au (203.29.134.3)  663.330 ms  467.109 ms  479.652 ms
 6  100ge13-1.core1.sjc1.he.net (216.218.139.233)  597.528 ms  667.505 ms  720.540 ms
 7  100ge1-1.core1.sjc2.he.net (184.105.65.114)  695.290 ms
    100ge8-2.core1.sjc2.he.net (184.104.195.54)  720.484 ms  672.532 ms
 8  * * *
 9  be100-1368.pao-sv8-bb1-a9.ca.us (178.32.135.158)  878.462 ms  510.235 ms  223.769 ms
10  chi-1-a9.il.us (198.27.73.149)  353.440 ms
    chi-5-a9.il.us (198.27.73.227)  652.207 ms  587.423 ms
11  be103.bhs-g1-nc5.qc.ca (198.27.73.206)  621.463 ms
    be103.bhs-g2-nc5.qc.ca (192.99.146.140)  689.691 ms
    be103.bhs-g1-nc5.qc.ca (198.27.73.206)  802.686 ms
12  * * *
13  be5.bhs-z2g1-a75.qc.ca (178.32.135.215)  310.697 ms
    be7.bhs-z2g1-a75.qc.ca (198.27.73.61)  344.259 ms
    be5.bhs-z2g1-a75.qc.ca (178.32.135.215)  419.926 ms
14  * * *
15  149.56.48.28 (149.56.48.28)  832.524 ms  364.435 ms  458.517 ms
16  * * *
17  ip-142-44-164.eu (142.44.164.249)  663.771 ms  633.008 ms  746.993 ms
```

`ping repo.packagist.org`

```
➜  ~ ping repo.packagist.org
PING repo.packagist.org (142.44.164.249): 56 data bytes
64 bytes from 142.44.164.249: icmp_seq=0 ttl=51 time=346.730 ms
64 bytes from 142.44.164.249: icmp_seq=1 ttl=51 time=440.170 ms
64 bytes from 142.44.164.249: icmp_seq=2 ttl=51 time=657.355 ms
64 bytes from 142.44.164.249: icmp_seq=3 ttl=51 time=635.573 ms
64 bytes from 142.44.164.249: icmp_seq=4 ttl=51 time=832.530 ms
64 bytes from 142.44.164.249: icmp_seq=5 ttl=51 time=495.346 ms
^C
--- repo.packagist.org ping statistics ---
6 packets transmitted, 6 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 346.730/567.951/832.530/159.743 ms
```

Additional Information:

- I have no VPN enabled.
- CLI php version is 7.4.12
- Tried on macOS Catalina and also after upgrading to Big Sur. Happened on both.
- PHP installed with homebrew.

```
➜  ~ which php
/usr/local/bin/php
➜  ~ php --version
PHP 7.4.12 (cli) (built: Oct 29 2020 18:37:21) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologies
➜  ~ php -a
Interactive shell
php > $long_url = "https://google.com";
php > echo file_get_contents($long_url);
<!doctype html><html itemscope="" itemtype="ht .....
```

**Comment by lukeholder** [comment]
Uninstalling brew's php 7.4 installation and using the native php 7.3 that comes with MacOS Big Sur fixes this issue.

**Comment by Seldaek** [comment]
I'd be interested in output of a command run with `-vvv` with the broken one, just to see if anything looks out of the ordinary.

Glad you got it fixed though..

Note that Composer 2 uses curl to download files by default, which might have gotten corrupted by your OS update? While file_get_contents (used by Composer 1) would still work?

**Comment by tomirons** [comment]
I'd prefer to use php from homebrew and I have a minimum version requirement of 7.4 in my project. I get this same issue. 😬 😭 

![image](https://user-images.githubusercontent.com/5089787/99157635-a16b9980-2698-11eb-8de7-591ace86b5e8.png)

@Seldaek here is the full output of the failing `composer diagnose` with `-vvv`.

<details>
<summary>Output</summary>

➜  ~ composer diagnose -vvv
Loading config file /Users/tomirons/.composer/auth.json
Reading /Users/tomirons/.composer/composer.json
Loading config file /Users/tomirons/.composer/auth.json
Loading config file /Users/tomirons/.composer/composer.json
Loading config file /Users/tomirons/.composer/auth.json
Reading /Users/tomirons/.composer/auth.json
Checked CA file /usr/local/etc/openssl@1.1/cert.pem: valid
Executing command (/Users/tomirons/.composer): git branch -a --no-color --no-abbrev -v
Executing command (/Users/tomirons/.composer): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (/Users/tomirons/.composer): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (/Users/tomirons/.composer): hg branch
Executing command (/Users/tomirons/.composer): fossil branch list
Executing command (/Users/tomirons/.composer): fossil tag list
Executing command (/Users/tomirons/.composer): svn info --xml
Reading /Users/tomirons/.composer/vendor/composer/installed.json
Running 2.0.7 (2020-11-13 17:31:06) with PHP 7.4.12 on Darwin / 19.6.0
Loading config file /Users/tomirons/.composer/auth.json
Reading /Users/tomirons/.composer/composer.json
Loading config file /Users/tomirons/.composer/auth.json
Loading config file /Users/tomirons/.composer/composer.json
Loading config file /Users/tomirons/.composer/auth.json
Reading /Users/tomirons/.composer/auth.json
Executing command (/Users/tomirons/.composer): git branch -a --no-color --no-abbrev -v
Executing command (/Users/tomirons/.composer): git describe --exact-match --tags
Executing command (/Users/tomirons/.composer): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (/Users/tomirons/.composer): hg branch
Executing command (/Users/tomirons/.composer): fossil branch list
Executing command (/Users/tomirons/.composer): fossil tag list
Executing command (/Users/tomirons/.composer): svn info --xml
Reading /Users/tomirons/.composer/vendor/composer/installed.json
Checking platform settings: OK
Checking git settings: Executing command (CWD): git config color.ui
OK
Checking http connectivity to packagist: Downloading http://repo.packagist.org/packages.json
FAIL
[Composer\Downloader\TransportException] Recv failure: Connection reset by peer
Checking https connectivity to packagist: Downloading https://repo.packagist.org/packages.json
FAIL
[Composer\Downloader\TransportException] OpenSSL SSL_connect: Connection reset by peer in connection to repo.packagist.org:443
Checking github.com oauth access: Using GitHub token authentication
Downloading https://api.github.com/
[200] https://api.github.com/
OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: Downloading https://getcomposer.org/versions
FAIL
[Composer\Downloader\TransportException] OpenSSL SSL_connect: Connection reset by peer in connection to getcomposer.org:443
Composer version: 2.0.7
PHP version: 7.4.12
PHP binary path: /usr/local/Cellar/php/7.4.12/bin/php
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
cURL version: 7.73.0 libz 1.2.11 ssl OpenSSL/1.1.1h
zip extension: OK
</details>

**Comment by Seldaek** [comment]
I don't see anything special there, just a failing connection.. can you try to remove and reinstall php via homebrew just to make sure it's not a corrupted install somehow? I think we've seen that in the past

**Comment by tomirons** [comment]
I did a complete reinstall of MacOS and it fixed the issue. I've tried to reinstall composer, php, etc but nothing would ever work.

This was such a strange issue, I'm glad it's fixed now!

**Comment by devingray** [comment]
> Uninstalling brew's php 7.4 installation and using the native php 7.3 that comes with MacOS Big Sur fixes this issue.

This worked for me if anybody else is dealing with Bug Sur and PHP

**Comment by devingray** [comment]
@Seldaek 

I have this same issue as above and I don't think I will be reinstalling my OS

This image is output from `composer diagnose -vvv`

<img width="1018" alt="issue@2x" src="https://user-images.githubusercontent.com/11573528/100426445-708d5a80-30c3-11eb-92dd-6bd99ee806a8.png">

I am continuing to debug this

**Comment by devingray** [comment]
And Solution is that that the DNS resolver was not configured correctly. 

In Mac OS: 

open system preferences -> network -> advanced -> DNS

At the top of the list add 1.1.1.1 (Cloudflare) or 8.8.8.8 (Google)

Apply changes.. 

`composer diagnose -vvv`

![Uploading fix@2x.png…]()

**Comment by Seldaek** [comment]
That seems like a different error from the above.. And this is something we already handle, as the error message shows "The following exception probably indicates you have misconfigured DNS resolver(s)".

**Comment by axtho** [comment]
I am also getting this after having upgraded to BigSur. I am using MAMP's PHP version(s). Checked it against 7.4.12, 7.3.24 and 8.0.0. All versions show the same error (CURL 56 and 35).
I run no VPN, my DNS Servers are Cloudflare and Google. I switched the firewall off. Still getting the same reset by peer error. Has anyone managed to find the culprit without reinstalling the OS?

Could it be OpenSSL? 

<img width="739" alt="Bildschirmfoto 2021-01-04 um 11 21 35" src="https://user-images.githubusercontent.com/11181579/103526525-593f4b00-4e81-11eb-9a7b-836a7d7fb6fb.png">
![Bildschirmfoto 2021-01-04 um 11 17 16](https://user-images.githubusercontent.com/11181579/103526533-5b090e80-4e81-11eb-8e7c-0fe99f52833d.png)

**Comment by barnesdc** [comment]
> I am also getting this after having upgraded to BigSur. I am using MAMP's PHP version(s). Checked it against 7.4.12, 7.3.24 and 8.0.0. All versions show the same error (CURL 56 and 35). I run no VPN, my DNS Servers are Cloudflare and Google. I switched the firewall off. Still getting the same reset by peer error. Has anyone managed to find the culprit without reinstalling the OS?
> 
> Could it be OpenSSL?
> 
> <img alt="Bildschirmfoto 2021-01-04 um 11 21 35" width="739" src="https://user-images.githubusercontent.com/11181579/103526525-593f4b00-4e81-11eb-9a7b-836a7d7fb6fb.png">
> 
> EDIT: It seems to be a an issue with permissions. When I use the pre-installed PHP version (7.3.24) composer commands work without issues. The php executables from MAMP, however, do not work (with composer). CuRL is not part of the MAMP package (which has user:admin as permissions). The system PHP has root:wheel as owner:group. I changed the owner:group of the MAMP supplied PHP exec to that of the system PHP, to no avail. Still the same problem.
> 
> Workaround: create an alias in your bash/zsh that uses the system PHP exec (e.g. `alias comp="/usr/bin/php /usr/local/bin/composer"`) and then run the update or install commands (using your alias of course) with the `--ignore-platform-reqs` flag, to avoid required php extensions botching source process). E.g. `comp update --ignore-platform-reqs`.
> 
> Maybe the problem occurs because CuRL is a system owned process and the executing PHP is not?
> 
> Hope that helps someone.

Did you ever get a resolution to this issue?
