### ISSUE TITLE
Using repository type "path" and following dependency resolution works in 1 but not in 2

### ISSUE THREAD

**Issue by mfn** [composer/composer#9479]
I'm currently working on a PR in the project to fix this (no success so far), please see https://github.com/rebing/graphql-laravel/pull/691

In the project I do the following:
- prepare composer.json for installing packages
  => https://github.com/rebing/graphql-laravel/blob/9392e6f9de9c334a9cc3b494984eec5e7221d135/.github/workflows/integration_tests.yml#L24-L26
- install packages
  => https://github.com/rebing/graphql-laravel/blob/9392e6f9de9c334a9cc3b494984eec5e7221d135/.github/workflows/integration_tests.yml#L39
- create a new laravel project
  => https://github.com/rebing/graphql-laravel/blob/9392e6f9de9c334a9cc3b494984eec5e7221d135/tests/integration-laravel.sh#L10-L12
- in this new laravel project, add a repository type "path" referecing the CI checkout of my project
  => https://github.com/rebing/graphql-laravel/blob/9392e6f9de9c334a9cc3b494984eec5e7221d135/tests/integration-laravel.sh#L14-L15
- install the the dependency there
  => https://github.com/rebing/graphql-laravel/blob/9392e6f9de9c334a9cc3b494984eec5e7221d135/tests/integration-laravel.sh#L20
  `composer require --dev "rebing/graphql-laravel:*"`

This approach works with v1 but breaks in v2 with the following error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires rebing/graphql-laravel * -> satisfiable by rebing/graphql-laravel[dev-c515745e405049ce7fa4d2c6400ddf6003c815ea].
    - rebing/graphql-laravel dev-c515745e405049ce7fa4d2c6400ddf6003c815ea requires illuminate/contracts 8.0 -> found illuminate/contracts[v8.0.0] but it conflicts with another require.

Error: Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires rebing/graphql-laravel * -> satisfiable by rebing/graphql-laravel[dev-c515745e405049ce7fa4d2c6400ddf6003c815ea].
    - rebing/graphql-laravel dev-c515745e405049ce7fa4d2c6400ddf6003c815ea requires illuminate/contracts 8.0 -> found illuminate/contracts[v8.0.0] but it conflicts with another require.
```

The `composer.json` of the checked out project, after CI applied some changes (removed unnecessary dependencies):
```json
{
    "name": "rebing/graphql-laravel",
    "description": "Laravel wrapper for PHP GraphQL",
    "keywords": [
        "framework",
        "laravel",
        "graphql",
        "react"
    ],
    "authors": [
        {
            "name": "Rebing OÜ",
            "homepage": "http://www.rebing.ee",
            "role": "Company"
        },
        {
            "name": "Mikk Mihkel Nurges",
            "email": "mikk.nurges@rebing.ee",
            "role": "Developer"
        },
        {
            "name": "Folklore",
            "email": "info@atelierfolklore.ca",
            "homepage": "http://atelierfolklore.ca"
        },
        {
            "name": "David Mongeau-Petitpas",
            "email": "dmp@atelierfolklore.ca",
            "homepage": "http://mongo.ca",
            "role": "Developer"
        },
        {
            "name": "Markus Fischer",
            "email": "markus@fischer.name",
            "role": "Developer"
        }
    ],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">= 7.1",
        "illuminate/contracts": "8.0",
        "illuminate/support": "5.5.*|5.6.*|5.7.*|5.8.*|^6.0|^7.0|^8.0",
        "webonyx/graphql-php": "^0.13",
        "ext-json": "*"
    },
    "require-dev": {
        "orchestra/testbench": "3.5.*|3.6.*|3.7.*|3.8.*|3.9.*|4.0.*|5.0.*|^6.0",
        "phpunit/phpunit": "^5.5|~6.0|~7.0|~8.0",
        "mockery/mockery": "^1.2",
        "friendsofphp/php-cs-fixer": "^2.15"
    },
    "autoload": {
        "psr-4": {
            "Rebing\\GraphQL\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Rebing\\GraphQL\\Tests\\": "tests/"
        }
    },
    "scripts": {
        "phpstan": "phpstan analyse --memory-limit=512M",
        "lint": "php-cs-fixer fix --diff --diff-format=udiff --dry-run",
        "fix-style": "php-cs-fixer fix"
    },
    "extra": {
        "laravel": {
            "providers": [
                "Rebing\\GraphQL\\GraphQLServiceProvider"
            ],
            "aliases": {
                "GraphQL": "Rebing\\GraphQL\\Support\\Facades\\GraphQL"
            }
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

The `composer.json` of the newly created laravel project after I added the repository with type=path:
```json
{
    "name": "laravel/laravel",
    "type": "project",
"repositories": [ { "type": "path", "url": "../graphql-laravel" } ],
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.3|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.12",
        "laravel/tinker": "^2.5"
    },
    "require-dev": {
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "mockery/mockery": "^1.4.2",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
```

Output of `composer diagnose`:
```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 2.0.7
PHP version: 7.4.12
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
cURL version: 7.58.0 libz 1.2.11 ssl OpenSSL/1.1.1g
zip extension: OK
```

I've made other PRs since this came to light where I simply used the setup-php action to switch back to composer v1 which worked, see e.g. https://github.com/rebing/graphql-laravel/runs/1398607123#step:10:11

I'm currently without pointers how to proceed, thank you!

**Comment by naderman** [comment]
Error message makes this look like a duplicate of https://github.com/composer/composer/pull/9360 unrelated to path repos or the rest of the setup.

As a workaround, instead of running composer require in the way you do, add "--no-update" and then manually run a composer update either of all packages, or explicitly for your newly required package as well as any conflicting ones, e.g. `composer update illuminate/contracts rebing/graphql-laravel

**Comment by mfn** [comment]
@naderman hmm, maybe I got it wrong

here's what I tried => https://github.com/rebing/graphql-laravel/pull/691/commits/84f5a3adaa84b51eda16cf037a878b6d99d21626
result's the same => https://github.com/rebing/graphql-laravel/pull/691/checks?check_run_id=1406973869#step:10:76

**Comment by naderman** [comment]
@mfn ah looks like you need to add more packages to the update in this case not listed in the error message, so best i can suggest is a full update.

**Comment by mfn** [comment]
Ok, tried with:
- https://github.com/rebing/graphql-laravel/pull/691/commits/c0f8caa0552a6127e238133b4e48ab820aa8e948
- but still got (this time slightly different) errors => https://github.com/rebing/graphql-laravel/pull/691/checks?check_run_id=1407121567#step:10:74

**Comment by naderman** [comment]
@mfn that's just a regular conflict now, as it says, no bug there.

Your package requires illuminate/contracts 8.0 but laravel/framework replaces other versions (e.g. laravel/framework 8.14 replaces illuminate/contracts 8.14) which do not match the 8.0 require, so your deps can't be resolved.

**Comment by stof** [comment]
@mfn your package should probably require `illuminate/contracts` with a `^8.0` constraint rather than `8.0` (which is a constraint allowing only the 8.0.0 release)

**Comment by mfn** [comment]
> `illuminate/contracts` with a `^8.0` constraint rather than `8.0`

🤦‍♂️

Indeed, this fixed it! In the project I merged a separate PR only containing the necessary changes => https://github.com/rebing/graphql-laravel/pull/693/files

Interestingly, what I noticed:
- the `7.0` and `8.0` did work with composer v1
- the `^7.0` did **not** work with composer v2
- only the `^8.0` **did work** with composer v2

So possible I would have not noticed anything of these issues if I went straight to `^8.0` at some point.

However I'm not chasing this further as the integration tests didn't run on multiple Laravel versions and it was time to go with L8 already which was released some months ago.

So, all fixed from my side and many thanks for your insights!

**Comment by stof** [comment]
@mfn the difference is that when using `7.0` or `8.0` as requirement, composer 1 will install the 7.0.0 or 8.0.0 releases of laravel respectively, and it will install the old 5.1.4 release of `rebing/graphql-laravel` to be compatible with that: https://github.com/rebing/graphql-laravel/runs/1405151596?check_suite_focus=true#step:10:12
With the new repository priorities in composer 2, Composer is forced to use your local version of `rebing/graphql-laravel` coming from the path repository, and so cannot use old laravel releases
