### ISSUE TITLE
Ext require should be added with "*" by default

### ISSUE THREAD

**Issue by mvorisek** [composer/composer#9483]
Example:

`composer require ext-bcmath` should add `require` like:

```
    "require": {
        "ext-php": "*"
    }
```

as php version is already determined by php constraints. This is also how php extensions constraint is defined in almost every package.

Currently, it is added like:

```
    "require": {
        "ext-php": "^7.4"
    }
```

which only complicates version requirements without any extra value.

**Comment by Seldaek** [comment]
I tend to agree, if the extension's version is equal to php version. This is not the case for all extensions, so should be checked IMO.

**Comment by Seldaek** [comment]
To illustrate what I mean, this behavior should not change I'd say, as extensions which are versioned independently can/should be required with proper version ranges:

```
$ composer require ext-xdebug
Using version ^2.9 for ext-xdebug
```

**Comment by mvorisek** [comment]
@Seldaek but 99% of the ext requirements are done using `*`, so IMO we should not complicate deps requirements. If user wants to require specific version, he can do it explicitly.

**Comment by Seldaek** [comment]
I disagree. The overwhelming majority of core extensions now ships with the same version as the engine, so what I said above will solve it for most packages, but pecl extensions etc IMO are versioned much more meaningfully and should keep their existing behavior.

**Comment by mvorisek** [comment]
Oh, now I get your comment - 100% agree, `*` for extensions that are bundled with PHP, otherwise `^installed_version` (this is now implemented for everything)
