### ISSUE TITLE
[Feature request] The Composer JSON schemas published as a package, or exposed via the runtime API

### ISSUE THREAD

**Issue by ezzatron** [composer/composer#9484]
I created [eloquent/composer-config-reader](https://packagist.org/packages/eloquent/composer-config-reader) quite a while ago. The intent was a lightweight package that simplifies parsing and consuming `composer.json` config files. All things considered, it was probably a mistake, because I can't really keep up with the maintenance too well, and parsing JSON isn't really that hard that it needs a whole library 😆

I thought I'd attempt to remove some of the maintenance burden and add a requirement for `composer/composer`, then simply read the schema directly from the `vendor` directory. This would probably work okay, but it kinda sucks because:

1. The location of the schema on disk isn't an explicit part of Composer's API.
2. The `composer/composer` dependency probably isn't super lightweight, and I'm assuming installing it as a dependency isn't "free" even though Composer is obviously already "present" at install time.

So it would be nice to be able to depend on something like `composer/schema`. Or alternatively, if the [Runtime Composer utilities](https://getcomposer.org/doc/07-runtime.md) had something like `Composer\Schema::getSchema()`, in which case I could just add `composer-runtime-api` as a dependency.

**Comment by stof** [comment]
what is the use case for accessing the composer schema at runtime though ?
If the only use case is to ease the maintenance of a library for which you consider yourselves that creating it was over-engineering, maybe there is no reason to do that and instead the library should be deprecated.

**Comment by ezzatron** [comment]
I suppose the use case is for developers creating tools that integrate tightly with Composer. I had assumed that this is why you publish the schema at https://getcomposer.org/schema.json, for example.

While having the schema available via HTTP is nice and all, if tools want to use it, they all separately need to manage their own copies, and require internet access to actually download it in the first place, and even then there's no guarantee that it's the same version of the schema used by the currently running version of Composer.

**Comment by Seldaek** [comment]
Exposing that as API at runtime sounds overkill IMO for this very limited use case. We could publish it as a package, but then we also have to keep that in sync.. I'd say the best is probably to ship it as part of you package like you do. It's not like this changes so often.  Alternatively you could mark your package abandoned because as you say, parsing JSON isn't all that hard :)
