### ISSUE TITLE
What about a Conflict-dev key ?

### ISSUE THREAD

**Issue by VincentLanglet** [composer/composer#9485]
We have a CI running with `--prefer-lowest`.

One of our dev dependencies is using the following dependency
`phpunit/phpunit`: `^7 || ^8 || ^9`.

We don't use personnaly `phpunit/phpunit` because we're using the symfony bridge, but for some reasons, if `phpunit/phpunit` is installed it must be at the version `^9`.

If it was a dependency, we would have declared a conflict with `phpunit/phpunit < 9`.
But here, it's a dev-dependency, and we have no reason to forbid the user to use our bundle with a lower version of `phpunit`, it's just our dev issue. So why not adding a `conflict-dev` key for this ?

Currently the only way we found to solve this is to directly requiring `phpunit/phpunit: ^9`, but I find wrong to require a dependency we're not directly using.

**Comment by Seldaek** [comment]
Why/which dependency of yours requires phpunit directly though? That sounds bad mostly but maybe there are valid use cases..

Anyway IMO the added complexity here is really not worth it as this sort of issue happens so rarely.

**Comment by VincentLanglet** [comment]
> Why/which dependency of yours requires phpunit directly though? That sounds bad mostly but maybe there are valid use cases..

We're using `psalm-plugin-phpunit`.
https://github.com/psalm/psalm-plugin-phpunit/blob/master/composer.json#L21

> Anyway IMO the added complexity here is really not worth it as this sort of issue happens so rarely.

I had another use case when using `psalm@3.x` in our project, we had an issue with one of dependencies of the dependencies of psalm which had a bug on our `--prefer-lowest` build.
 
We had to require a specific version, like `"phpdocumentor/reflection-docblock": "^5.2"`, but I would have prefer adding a conflict instead. Because if one day this dependency of dependency is not required anymore (which can happen any time, we won't follow how every dependencies change), we don't have to remove it from our `composer.json` in order to not download it anymore.

**Comment by Seldaek** [comment]
Yeah, that makes sense.. But these are all specific to --prefer-lowest, which is a bit of a special case. 

So what I am wondering is whether --prefer-lowest should apply to transitive dependencies at all, or only to direct ones, because it's really only ever used for testing the minimum dependencies of a project are valid AFAICT, and now what is happening is you are testing the minimum dependencies of your project's dependencies as well, and that breaks. Any thoughts on this @naderman?

**Comment by VincentLanglet** [comment]
> So what I am wondering is whether --prefer-lowest should apply to transitive dependencies at all, or only to direct ones, because it's really only ever used for testing the minimum dependencies of a project are valid AFAICT, and now what is happening is you are testing the minimum dependencies of your project's dependencies as well, and that breaks. Any thoughts on this @naderman?

Oh that's a great idea indeed.
If `--prefer-lowest` wasn't transitive, I wouldn't have these issues.

The `prefer-lowest` build is made to test that the minimum dependencies of a project are valid. 
If someone require the lowest version of our dependencies, it will generally install the highest version of the dependency of my dependency. So the transitivity of `prefer-lowest` does not have real sens here.

**Comment by naderman** [comment]
@Seldaek That's how --prefer-lowest is designed currently, I don't really want to entirely change around how this works at this point.

The idea is really to be able to check if a library would still work on a project with an old environment. And that old environment is likely to also involve old deps of deps, e.g. like in this case an old phpunit version (if this wasn't require-dev triggered). So I'd say that the current behavior is usually desired, but there may be room for additional options.

That said, I think for require-dev it's reasonable to expect you to define a direct dependency in your dev requires if you want a dependency's dependency to be installed in a specific version range and not in the version range your dependency selected. This also ensures that users of your library are able to require the package without having to manually add additional conflicts themselves, as a conflict-dev would have to be ignored for users of the library, but it cannot be ignored during dependency resolution in your tests, while a require-dev can be ignored as it can only narrow constraints which would have to match anyway.

**Comment by VincentLanglet** [comment]
> This also ensures that users of your library are able to require the package without having to manually add additional conflicts themselves

But they wouldn't have to add additional conflict, since the conflict is supposed to be with my dev-dependencies.
And if I understand correctly composer, dev-dependencies are never installed by someone requiring my library.

The goal of the conflict-dev was to avoid requiring a dependencies of a dependencies if I don't use it personnaly.
First, tool like https://github.com/composer-unused/composer-unused, would report this dependency as unused.
Second, if my dependency will stop to use it, I will keep dev-requiring the dependency of dependency, for nothing, without knowing it.

**Comment by naderman** [comment]
> > This also ensures that users of your library are able to require the package without having to manually add additional conflicts themselves
> 
> But they wouldn't have to add additional conflict, since the conflict is supposed to be with my dev-dependencies.
> And if I understand correctly composer, dev-dependencies are never installed by someone requiring my library.
> 

When you run a composer update on a project it takes all dependencies including require-dev and resolves them. Afterwards it runs the solver again on just the set of packages that already satisfied the first problem but only takes the require dependencies into account. The result is the non-dev set of packages. If you added a conflict-dev you'd have to add it to the first run, and so it would have an impact on the result in your test install in a way not necessarily reproducible by users of your library without also adding the conflict. Sure in your specific case with phpunit that's unlikely but it may happen for all kinds of other conflicts which then end up interfering with packages normally required.

> The goal of the conflict-dev was to avoid requiring a dependencies of a dependencies if I don't use it personnaly.
> First, tool like https://github.com/composer-unused/composer-unused, would report this dependency as unused.
> Second, if my dependency will stop to use it, I will keep dev-requiring the dependency of dependency, for nothing, without knowing it.

Do you not have test classes which inherit from classes defined by phpunit?

**Comment by VincentLanglet** [comment]
> When you run a composer update on a project it takes all dependencies including require-dev and resolves them. 

I wasn't aware of this.
Why resolving the `require-dev` of the dependencies if the devDependencies of the dependencies won't be installed ?

> Do you not have test classes which inherit from classes defined by phpunit?

In the phpunit case, yes indeed.

I have more in mind https://github.com/composer/composer/issues/9485#issuecomment-728371595
We're using `psalm`, but we had no direct use of `"phpdocumentor/reflection-docblock": "^5.2"`.

Anyway, if you think that's not a good idea, we can close this.

**Comment by naderman** [comment]
> > When you run a composer update on a project it takes all dependencies including require-dev and resolves them.
> 
> I wasn't aware of this.
> Why resolving the `require-dev` of the dependencies if the devDependencies of the dependencies won't be installed ?
> 

Because they all need to go into the same lock file, and you don't want the lock file to change when you try to install with dev dependencies because they have a conflict to some version of a package in the lock file which was okay without dev dependencies. So writing the lock file always takes all deps including dev dependencies into account, installation then decides which set of the locked packages to install.

**Comment by VincentLanglet** [comment]
> Because they all need to go into the same lock file, and you don't want the lock file to change when you try to install with dev dependencies because they have a conflict to some version of a package in the lock file which was okay without dev dependencies. So writing the lock file always takes all deps including dev dependencies into account, installation then decides which set of the locked packages to install.

If I require A and devRequire B.
If A require C and devRequire D.
If B require E and devRequire F.

I understand that the lock file need to take in account A, B, C and E.
I was thinking that I would never install the dev-dependency of a dependency (here D or F).
And in a similar way the composer doesn't need to resolve the `conflict-dev` of the dependency A or B.

But when I read you, it seems like I was wrong.

**Comment by naderman** [comment]
What you said is exactly right, I was talking about top level dev dependencies, so B in your example.

But the problem with a potential conflict-dev is that if you define conflict-dev on package A, then you may be able to do a composer update successfully when running in A, but you may not be able to reproduce the same when requiring A. I'm going to leave it at that now and try and focus on actually getting some work done ...

**Comment by stof** [comment]
> But the problem with a potential conflict-dev is that if you define conflict-dev on package A, then you may be able to do a composer update successfully when running in A, but you may not be able to reproduce the same when requiring

@naderman but the same is true with `require-dev`, which might restrict which versions of the non-dev dependencies are usable.
