### ISSUE TITLE
"exclude-from-classmap" leads to "preg_match(): Compilation failed: regular expression is too large"

### ISSUE THREAD

**Issue by Defcon0** [composer/composer#9487]
Hello,

I'm currently struggling due to the implementation of exclude-from-classmap in composer.

I have a large system with hundreds of dependencies. Nearly all of them have `exclude-from-classmap` set with 5 paths.

The line here:

https://github.com/composer/composer/blob/2.0.7/src/Composer/Autoload/ClassMapGenerator.php#L106

takes all of the excludes at once it seems and runs a preg_match. In the large project I get:

`preg_match(): Compilation failed: regular expression is too large at offset 33080`

The solution can't be to reduce the count of excludes. But what might be a solution would be to make composer handle this in chunks, i.e.

1. get all the exludes, build chunks of 90% of phps limit for regexps
2. iterate over the chunks -> if one matches, continue as already in the current implementation

Would that be an option?

Thanks in advance

Bye Defcon0

**Comment by stof** [comment]
Given that each directory is parsed separately to build the classmap, a solution could be to keep separate `exclude-from-classmap` regex per package (and using the right one for each scanning) instead of combining everything in a single regex.

**Comment by Defcon0** [comment]
Sounds reasonable. I also didn't understand the need to combine all in a giant regexp but I thought if it's done, it might have a reason not so obvious.

**Comment by stof** [comment]
> if it's done, it might have a reason not so obvious.

it was probably done this way for simplicity of the implementation, without realizing that it would cause such issue with the size of the regex when lots of packages are using the feature.

**Comment by Seldaek** [comment]
Right this sounds like a mistake which is harmless in most cases.. but probably should be fixed :)

**Comment by Defcon0** [comment]
👍  Thanks for fixing!

**Comment by Seldaek** [comment]
I'm hoping this won't have unexpected side effects, but I did try to cover all cases.
