### ISSUE TITLE
Composer not finding packages after OS update to mac bigSur

### ISSUE THREAD

**Issue by idwellys** [composer/composer#9491]
My `composer.json`:

```json
{
    "name": "temp/package",
    "description": "very slim",
    "type": "library",
    "license": "MIT",
    "authors": [
        {
            "name": "Temp User",
            "email": "tempuser@gmail.com"
        }
    ],
    "minimum-stability": "dev",
    "require": {}
}

```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.7
PHP version: 7.4.7
PHP binary path: /usr/local/Cellar/php/7.4.7/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
cURL version: 7.71.0 libz 1.2.11 ssl OpenSSL/1.1.1g
zip extension: OK
Hinis-MBP:test-directory majestyipad$
```

When I run this command:

```
composer require waavi/sanitizer
```

I get the following output:

```
 [InvalidArgumentException]               
  Could not find package waavi/sanitizer.  
                                           
  Did you mean one of these?               
      waavi/sanitizer               
```

And I expected this to happen:
I expected it to install the package. 
Besides i have tried uninstalling and installing composer severally.

**Comment by idwellys** [comment]
This is what happens; I need help please any suggestion would be helpful. 

![composer not finding packages](https://user-images.githubusercontent.com/55641102/99600866-2e468800-29f6-11eb-851c-0533b1ac09b3.gif)

**Comment by Seldaek** [comment]
Please share the full output of: `composer require waavi/sanitizer -vvv`

**Comment by idwellys** [comment]
Hinis-MBP:dwellyscustapp majestyipad$ composer require waavi/sanitizer -vvv
Reading ./composer.json
Loading config file /Users/majestyipad/.composer/config.json
Loading config file /Users/majestyipad/.composer/auth.json
Loading config file ./composer.json
Checked CA file /usr/local/etc/openssl@1.1/cert.pem: valid
Executing command (/Users/majestyipad/Desktop/active-projects-no-cloud-sync/dwellyscustapp): git branch -a --no-color --no-abbrev -v
Reading /Users/majestyipad/.composer/composer.json
Loading config file /Users/majestyipad/.composer/config.json
Loading config file /Users/majestyipad/.composer/auth.json
Loading config file /Users/majestyipad/.composer/composer.json
Loading config file /Users/majestyipad/.composer/auth.json
Reading /Users/majestyipad/.composer/auth.json
Reading /Users/majestyipad/Desktop/active-projects-no-cloud-sync/dwellyscustapp/vendor/composer/installed.json
Reading /Users/majestyipad/.composer/vendor/composer/installed.json
Running 2.0.7 (2020-11-13 17:31:06) with PHP 7.4.7 on Darwin / 20.1.0
Downloading https://packagist.phpcomposer.com/packages.json
[200] https://packagist.phpcomposer.com/packages.json
Writing /Users/majestyipad/.composer/cache/repo/https---packagist.phpcomposer.com/packages.json into cache
Downloading https://packagist.phpcomposer.com/p2/waavi/sanitizer.json
Downloading https://packagist.phpcomposer.com/p2/waavi/sanitizer~dev.json
[404] https://packagist.phpcomposer.com/p2/waavi/sanitizer.json
[404] https://packagist.phpcomposer.com/p2/waavi/sanitizer~dev.json
Downloading https://packagist.org/search.json?q=waavi/sanitizer&type=
[200] https://packagist.org/search.json?q=waavi/sanitizer&type=

                                           
  [InvalidArgumentException]               
  Could not find package waavi/sanitizer.  
                                           
  Did you mean one of these?               
      waavi/sanitizer                      
      jijoel/sanitization-filters          
                                           

Exception trace:
 () at phar:///usr/local/Cellar/composer/2.0.7/bin/composer/src/Composer/Command/InitCommand.php:796
 Composer\Command\InitCommand->findBestVersionAndNameForPackage() at phar:///usr/local/Cellar/composer/2.0.7/bin/composer/src/Composer/Command/InitCommand.php:430
 Composer\Command\InitCommand->determineRequirements() at phar:///usr/local/Cellar/composer/2.0.7/bin/composer/src/Composer/Command/RequireCommand.php:189
 Composer\Command\RequireCommand->execute() at phar:///usr/local/Cellar/composer/2.0.7/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/Cellar/composer/2.0.7/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/Cellar/composer/2.0.7/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/Cellar/composer/2.0.7/bin/composer/src/Composer/Console/Application.php:310
 Composer\Console\Application->doRun() at phar:///usr/local/Cellar/composer/2.0.7/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/Cellar/composer/2.0.7/bin/composer/src/Composer/Console/Application.php:122
 Composer\Console\Application->run() at phar:///usr/local/Cellar/composer/2.0.7/bin/composer/bin/composer:63
 require() at /usr/local/Cellar/composer/2.0.7/bin/composer:24

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...


![image](https://user-images.githubusercontent.com/55641102/99658386-54e8db00-2a57-11eb-9713-aa36a26727d5.png)

**Comment by idwellys** [comment]
> Please share the full output of: `composer require waavi/sanitizer -vvv`

Hinis-MBP:dwellyscustapp majestyipad$ composer require waavi/sanitizer -vvv
Reading ./composer.json
Loading config file /Users/majestyipad/.composer/config.json
Loading config file /Users/majestyipad/.composer/auth.json
Loading config file ./composer.json
Checked CA file /usr/local/etc/openssl@1.1/cert.pem: valid
Executing command (/Users/majestyipad/Desktop/active-projects-no-cloud-sync/dwellyscustapp): git branch -a --no-color --no-abbrev -v
Reading /Users/majestyipad/.composer/composer.json
Loading config file /Users/majestyipad/.composer/config.json
Loading config file /Users/majestyipad/.composer/auth.json
Loading config file /Users/majestyipad/.composer/composer.json
Loading config file /Users/majestyipad/.composer/auth.json
Reading /Users/majestyipad/.composer/auth.json
Reading /Users/majestyipad/Desktop/active-projects-no-cloud-sync/dwellyscustapp/vendor/composer/installed.json
Reading /Users/majestyipad/.composer/vendor/composer/installed.json
Running 2.0.7 (2020-11-13 17:31:06) with PHP 7.4.7 on Darwin / 20.1.0
Downloading https://packagist.phpcomposer.com/packages.json
[200] https://packagist.phpcomposer.com/packages.json
Writing /Users/majestyipad/.composer/cache/repo/https---packagist.phpcomposer.com/packages.json into cache
Downloading https://packagist.phpcomposer.com/p2/waavi/sanitizer.json
Downloading https://packagist.phpcomposer.com/p2/waavi/sanitizer~dev.json
[404] https://packagist.phpcomposer.com/p2/waavi/sanitizer.json
[404] https://packagist.phpcomposer.com/p2/waavi/sanitizer~dev.json
Downloading https://packagist.org/search.json?q=waavi/sanitizer&type=
[200] https://packagist.org/search.json?q=waavi/sanitizer&type=

                                           
  [InvalidArgumentException]               
  Could not find package waavi/sanitizer.  
                                           
  Did you mean one of these?               
      waavi/sanitizer                      
      jijoel/sanitization-filters          
                                           

Exception trace:
 () at phar:///usr/local/Cellar/composer/2.0.7/bin/composer/src/Composer/Command/InitCommand.php:796
 Composer\Command\InitCommand->findBestVersionAndNameForPackage() at phar:///usr/local/Cellar/composer/2.0.7/bin/composer/src/Composer/Command/InitCommand.php:430
 Composer\Command\InitCommand->determineRequirements() at phar:///usr/local/Cellar/composer/2.0.7/bin/composer/src/Composer/Command/RequireCommand.php:189
 Composer\Command\RequireCommand->execute() at phar:///usr/local/Cellar/composer/2.0.7/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/Cellar/composer/2.0.7/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/Cellar/composer/2.0.7/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/Cellar/composer/2.0.7/bin/composer/src/Composer/Console/Application.php:310
 Composer\Console\Application->doRun() at phar:///usr/local/Cellar/composer/2.0.7/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/Cellar/composer/2.0.7/bin/composer/src/Composer/Console/Application.php:122
 Composer\Console\Application->run() at phar:///usr/local/Cellar/composer/2.0.7/bin/composer/bin/composer:63
 require() at /usr/local/Cellar/composer/2.0.7/bin/composer:24

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...


![image](https://user-images.githubusercontent.com/55641102/99658386-54e8db00-2a57-11eb-9713-aa36a26727d5.png)

**Comment by stof** [comment]
packagist.phpcomposer.com is not the official packagist but an unofficial mirror. Maybe this mirror has broken metadata

**Comment by idwellys** [comment]
> packagist.phpcomposer.com is not the official packagist but an unofficial mirror. Maybe this mirror has broken metadata

Please how may i resolve it ?

**Comment by stof** [comment]
Remove your custom repository config to stop using that mirror (it is probably in your global config file)

**Comment by stof** [comment]
@Seldaek looks like the hack detecting bad mirrors not mirroring the v2 metadata does not catch packagist.phpcomposer.com

**Comment by idwellys** [comment]
> Remove your custom repository config to stop using that mirror (it is probably in your global config file)

{ 
  "config": {
    "github-protocols": [
      "https"
    ]
   },
  "repositories": {
    "packagist.org": {
      "type": "composer",
      "url": "https://packagist.org"
    }
   },
    "require": {
        "laravel/valet": "^2.9",
        "phpunit/phpunit": "^8.5",
    "beyondcode/expose": "^1.3",
    "laravel/installer": "^4.0"
    }
}

here is my global composer config ; anything to do here ?

**Comment by stof** [comment]
Well, check the project-level config too.

On a side note, in your global config, I suggest removing the override of the `packagist.org` repository to use the official `repo.packagist.org` domain (which is load-balanced between official mirrors).

According to the readme of https://github.com/Webysther/packagist-mirror, packagist.phpcomposer.com might be an outdated mirror

**Comment by idwellys** [comment]
my project-level config doesnt have repository information. 

> Well, check the project-level config too.
> 
> On a side note, in your global config, I suggest removing the override of the `packagist.org` repository to use the official `repo.packagist.org` domain (which is load-balanced between official mirrors).
> 
> According to the readme of https://github.com/Webysther/packagist-mirror, packagist.phpcomposer.com might be an outdated mirror

**Comment by stof** [comment]
Then something weird is going on, or the file you pasted before is not the global composer config.

**Comment by idwellys** [comment]
> Then something weird is going on, or the file you pasted before is not the global composer config.

Any help locating the global config ?

**Comment by stof** [comment]
`composer config --editor --global` will open it in your editor (based on the `EDITOR` env variable)

**Comment by idwellys** [comment]
@stof thank you very much for your help. Changing the url in my global composer config fixes the issue;

{
    "config": {},
    "repositories": {
        "packagist": {
            "type": "composer",
            "url": "https://repo.packagist.org"
        }
    }
}

**Comment by Seldaek** [comment]
> @Seldaek looks like the hack detecting bad mirrors not mirroring the v2 metadata does not catch packagist.phpcomposer.com

Right.. I don't think it's worth digging into though as it doesn't seem to be too frequently used.

**Comment by Muhammad-Hassan-Farooq** [comment]
I cannot download composer on my system as it doesnt set the global config on my system
