### ISSUE TITLE
Some require-dev packages could not be installed.

### ISSUE THREAD

**Issue by izniburak** [composer/composer#9495]
Hi,

I'm trying to create a new Laravel application by using following command:
```
composer create-project --prefer-dist laravel/laravel my-project
```

It is created and running. But I noticed something after the installation.

`laravel/laravel` package has a dependency for `laravel/framework` package. And `laravel/framework` package has some `require-dev` packages like doctrine/dbal, filp/whoops, guzzlehttp/guzzle etc...

When I checked the packages which installed via composer, I couldn't see some packages which is in `require-dev` packages. Therefore, I got an error for some operation in Laravel. For example, I'm trying to add new migration in order to change table structure. And as far as I know, as this situtations, `doctrine/dbal` package is used.

<img width="263" alt="Screen Shot 2020-11-18 at 16 26 23" src="https://user-images.githubusercontent.com/4693615/99546504-84e89d80-29c7-11eb-8522-e8a370a78853.png">

I'm not using `--no-dev` flag. And I also tried to install by using `--dev` flag. You know, this flag is default behaviour for composer but I tried my chance. Also, I tried to install another project like Laravel and the result is same.

As a result, I guess some dev packages can not be installed to project. What is the reason of that? What can I do for that problem?

Thanks.

**Comment by stof** [comment]
`require-dev` is a root-only field. The dev requirements of your dependencies don't matter.

**Comment by izniburak** [comment]
Thank you for clear response.
