### ISSUE TITLE
Gitlab private repository : create-project does not work

### ISSUE THREAD

**Issue by squiaios** [composer/composer#9496]
My `composer.json`: I do not have `composer.json` file yet

Output of composer diagnose:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (2.0.0-RC2 => 2.0.7)
Composer version: 2.0.0-RC2
PHP version: 7.2.34
PHP binary path: /usr/bin/php7.2
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
cURL version: 7.58.0 libz 1.2.11 ssl OpenSSL/1.1.1g
zip extension: not loaded
```

When I run this command:

```
composer create-project vendor/my-repo Test "1.0.0" --repository='{"type": "composer", "url": "https://gitlab.vendor.com/api/v4/group/100/-/packages/composer/packages.json"}'
```

I get the following output:

```
The "https://gitlab.vendor.com/api/v4/group/100/-/packages/composer/packages.json" file could not be downloaded (HTTP/2 404 ) 
```

And I expected this to happen:
A download of the repository to init a new project. 

It's impossible to declare the attribute `gitlab-domains` in the cli command, hence the error I guess.

Thanks for your help.

**Comment by Seldaek** [comment]
Yeah that's not going to work if you don't first set `composer config --global gitlab-domains gitlab.vendor.com`

**Comment by squiaios** [comment]
> Yeah that's not going to work if you don't first set `composer config --global gitlab-domains gitlab.vendor.com`

I agree with you if I have a composer.json.
But my goal is to create a project using `composer create-project`, so from there I have not yet the composer.json file.

If it's not possible to pass the gitlab-domains in the cli command, is it possible de create new options on cli for create-project ?

**Comment by squiaios** [comment]
I did try to understand how works gitlab-domains, but it's to huge to me :/

https://github.com/composer/composer/blob/9e279740cd4dea381a77cc48af617a91d835408e/src/Composer/Config.php#L141

In this line, if I understand well, if in my oauth.json file I have gitlab-domains, it's imported, no ?

**Comment by stof** [comment]
> I agree with you if I have a composer.json.

the suggested command uses `composer config --global`, so setting the option in the *global* config, not in the project-level composer.json (which you indeed don't have yet)

**Comment by squiaios** [comment]
Oh my Bad, didn't see the --global option.
I'll try and I'll update my thread

**Comment by squiaios** [comment]
I set the global config, now all works perfectly :+1: 

Thank you both of you
