### ISSUE TITLE
https://getcomposer.org/download/update/composer.phar.sig .....not working when "composer self update" windows

### ISSUE THREAD

**Issue by cmsbhathiya** [composer/composer#9500]
When I run this command:

```
composer self update --stable
```

I get the following output:

```
[Composer\Downloader\TransportException]
  The "https://getcomposer.org/download/update/composer.phar.sig" file could not be downloaded (HTTP/1.1 404 Not Foun
  d)
```

**Comment by Seldaek** [comment]
The command is `self-update` without space, or you can use `selfupdate` too. If you use `self update` you are telling it to update to the version `update`, which is not found.

**Comment by cmsbhathiya** [comment]
Great, Thank you and sorry for the trouble..

**Comment by Seldaek** [comment]
It happens ;) I improved things in https://github.com/composer/composer/commit/35b403b26648d3a0a5a126ea8c9f2cfc0e8a816c so hopefully it's clearer for the next one who does this mistake.
