### ISSUE TITLE
enforce composer v2

### ISSUE THREAD

**Issue by staabm** [composer/composer#9501]
in our project we rely on composer v2 only features and therefore want to enforce composer v2 usage.

therefore we declared `"composer-plugin-api": "^2",` as a requirement for our application.

when invoking `composer update` on our project with composer v1 the user now get the follwing error:
```
$ composer update
    1/6:        http://repo.packagist.org/p/provider-latest$5f9aaca4ca8f003c5ab2bd317b16485a712f43e4719cb8f3cbc643fa04e3a21d.json
    2/6:        http://repo.packagist.org/p/provider-2020-01$836bb431be9f15b4026c81aa798a4eb929352d8a284a0605a1ecc677cf03062e.json
    3/6:        http://repo.packagist.org/p/provider-2020-10$6740fd4922b41c231848ef898a921f9de178f7c104fb60896c48dbdc5fde40e3.json
    4/6:        http://repo.packagist.org/p/provider-2020-04$a4a3e5c186a6c14a177f142f085cb8f93c78c0873f0aeb0f0b98f9c018b8dc21.json
    5/6:        http://repo.packagist.org/p/provider-2020-07$c238e99c32ee4d049cb1b5a20f50923285f354e212bfcb3c5324dbbd3be7a50b.json
    6/6:        http://repo.packagist.org/p/provider-2019$de89eed769796405eb234b4a74c286fa5bc0f187e074e26c14c57708e964ffd7.json
    Finished: success: 6, skipped: 0, failure: 0, total: 6
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package composer-plugin-api ^2 exists as composer-plugin-api[1.1.0] but these are rejected by your constraint.
```

is there a better way to enforce composer v2?

the solution we have right now has the following problems:
- a error message, which doesn't point the user towards a composer v2 update.
- running composer update on our project takes roughly **45 seconds**.. I guess the SAT is trying to resolve how it could get composer v1 working with `composer-plugin-api: v2` - which it will never can

is there a recommended way on how to enforce composer v2 with a better overall developer experience?

**Comment by Seldaek** [comment]
You should rather require `composer-runtime-api: ^2` IMO if you require v2 runtime features, but technically it's going to be the same end result.

Improving the experience would requiring patching composer 1 with a specific message there, so it won't help directly.. Not sure if worth it.

**Comment by staabm** [comment]
I see, so besider documenting the existance of `composer-runtime-api: ^2`  there is not much we can/should do?

**Comment by Seldaek** [comment]
I don't think so.. It's a team-communication and time-will-fix-it problem :)
