### ISSUE TITLE
binaries installed by composer should have option to disable platform checks

### ISSUE THREAD

**Issue by mikk150** [composer/composer#9504]
My `composer.json`:

```json
does not really matter
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.7
PHP version: 7.2.34 - Package overridden via config.platform, actual: 7.4.12
PHP binary path: /usr/bin/php
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
cURL version: 7.73.0 libz 1.2.11 ssl OpenSSL/1.1.1h
zip extension: OK

```

When I run this command:

```
vendor/bin/dep deploy
```

I get the following output:

```
Your Composer dependencies require the following PHP extensions to be installed: <insert extensions here>
```

And I expected this to happen:
my application being deployed

-----

Since I do development on docker container, and my rig has only basic installation of PHP without much of extensions(I do not need them) I cannot deploy my application, because binaries still check if I have all extensions needed for my project

**Comment by stof** [comment]
the platform-check can be disabled in the composer config (note that you need to disable that before you dump the autoloader during `composer install` or `composer dump-autoload` as it removes the platform check from the dumped code. the config is not loaded dynamically by the check code): https://getcomposer.org/doc/06-config.md#platform-check

**Comment by mikk150** [comment]
> the platform-check can be disabled in the composer config (note that you need to disable that before you dump the autoloader during `composer install` or `composer dump-autoload` as it removes the platform check from the dumped code. the config is not loaded dynamically by the check code): https://getcomposer.org/doc/06-config.md#platform-check

I do want platform check on my project, I just do not want platform check on application that resides in `vendor/bin`, solely because I do development on container, where I have all dependnecies, and execute [deployer](https://github.com/deployphp/deployer) on my main machine, because I do not want to put my ssh keys to container

**Comment by stof** [comment]
Well, the thing is, there is a single `vendor/autoload.php` file for everything installed. So you cannot have 2 different config depending on which code is requiring the autoload file.

**Comment by stof** [comment]
@mikk150 a solution that might work in your case (I haven't tried to confirm) could be using https://github.com/bamarni/composer-bin-plugin to install deployer in a separate vendor directory (which then has its own autoload file, and can disable `platform-check` in its own config)

**Comment by Seldaek** [comment]
IMO the better option here is to do `composer config --global platform-check false` so that it's disabled on your machine, but once you deploy the deployment hopefully rebuilds the autoload in optimized form and there it'll have the platform check enabled.
