### ISSUE TITLE
Composer 2 prompts for authentication when Composer 1 doesn't

### ISSUE THREAD

**Issue by elazar** [composer/composer#9506]
My `composer.json`:

```json
{
    "name": "stack-sports/phit-skeleton",
    "type": "project",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "php": ">=7.4",
        "ext-json": "*",
        "guzzlehttp/guzzle": "^6.5",
        "league/plates": "^3.3",
        "stack-sports/phit": "^3",
        "tuupola/cors-middleware": "^1.2",
        "vlucas/phpdotenv": "^4"
    },
    "repositories": {
        "cup": {
            "type": "composer",
            "url": "https://cup.bluestarsports.io/"
        }
    },
    "autoload": {
        "psr-4": {
            "Rainout\\": "src/"
        }
    },
    "require-dev": {
        "phpspec/prophecy-phpunit": "^2.0",
        "phpunit/phpunit": "^9.1",
        "roave/security-advisories": "dev-master"
    },
    "autoload-dev": {
        "psr-4": {
            "Rainout\\Tests\\": "tests/"
        }
    },
    "scripts": {
        "test": "phpunit"
    },
    "config": {
        "sort-packages": true
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.7
PHP version: 7.4.12
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
cURL version: 7.58.0 libz 1.2.11 ssl OpenSSL/1.1.1
zip extension: OK
```

When I run this command:

```
composer require predis/predis
```

I get the following output:

```
    Authentication required (cup.bluestarsports.io):
      Username: 
      Password: 
https://cup.bluestarsports.io could not be fully loaded (Invalid credentials for 'https://cup.bluestarsports.io/p2/predis/predis~dev.json', aborting.), package information was loaded from the local cache and may be out of date

                                                                                                
  [Composer\Downloader\TransportException]                                                      
  Invalid credentials for 'https://cup.bluestarsports.io/p2/predis/predis~dev.json', aborting.  
                                                                                                

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...
```

And I expected this to happen:

```
Using version ^1.1 for predis/predis
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing predis/predis (v1.1.6): Downloading (100%)         
predis/predis suggests installing ext-phpiredis (Allows faster serialization and deserialization of the Redis protocol)
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
34 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

Note that the above is what happens when using Composer 1.10.17, but not 2.0.7.

Potentially relevant: the repository at cup.bluestarsports.io is a Satis repository hosted in a publicly readable S3 bucket. Amazon returns a 403 rather than a 404 when a requested file isn't found, which could be contributing to how Composer 2 is behaving. I tried running `composer clear-cache`, but the issue persists.

The closest potentially related issue I've found thus far is #9369.

**Comment by stof** [comment]
> Potentially relevant: the repository at cup.bluestarsports.io is a Satis repository hosted in a publicly readable S3 bucket. Amazon returns a 403 rather than a 404 when a requested file isn't found, which could be contributing to how Composer 2 is behaving. I tried running `composer clear-cache`, but the issue persists.

Then that's expected. The new metadata format for composer repositories requires that a proper 404 is returned for non-existent files: https://github.com/composer/composer/blob/master/UPGRADE-2.0.md#metadata-url

**Comment by stof** [comment]
@elazar a quick search told me that S3 might be able to return proper 404 responses if you enable the static website hosting option for your bucket.

**Comment by Seldaek** [comment]
Alternatively... [Private Packagist](https://packagist.com) supports Composer 2 correctly and won't waste your time 🙄

**Comment by elazar** [comment]
> @elazar a quick search told me that S3 might be able to return proper 404 responses if you enable the static website hosting option for your bucket: [docs.aws.amazon.com/AmazonS3/latest/dev/CustomErrorDocSupport.html#s3-http-error-codes](https://docs.aws.amazon.com/AmazonS3/latest/dev/CustomErrorDocSupport.html#s3-http-error-codes)

I had this option enabled before I encountered this problem. :confused:

**Comment by stof** [comment]
According to https://www.reddit.com/r/aws/comments/3mwh7q/how_to_return_http404_for_s3_static_website/, you might need to give the `List` permission to `everyone` in the bucket permissions, to make the 404 work.

**Comment by elazar** [comment]
> According to [reddit.com/r/aws/comments/3mwh7q/how_to_return_http404_for_s3_static_website](https://www.reddit.com/r/aws/comments/3mwh7q/how_to_return_http404_for_s3_static_website/), you might need to give the `List` permission to `everyone` in the bucket permissions, to make the 404 work.

That did the trick! Thank you very much for your response and patience!
