### ISSUE TITLE
Using GitLab Pages to host a composer repository works with Composer 1, but not with Composer 2

### ISSUE THREAD

**Issue by dsnopek** [composer/composer#9507]
**My `composer.json`:**

```json
{
    "repositories": {
        "drupal-ckeditor-plugins": {
            "type": "composer",
            "url": "https://panopoly.gitlab.io/drupal-ckeditor-plugins/"
        }
    },
    "require": {
        "drupal-ckeditor-plugin/a11yhelp": "*"
    }
}
```

**Output of `composer diagnose`:**

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.drupal-ckeditor-plugin/a11yhelp : unbound version constraints (*) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.7
PHP version: 7.3.23
PHP binary path: /usr/bin/php7.3
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
cURL version: 7.58.0 libz 1.2.11 ssl OpenSSL/1.1.1g
zip extension: OK
```

**When I run this command (with Composer 2):**

```
composer install
```

**I get the following output (with Composer 2):**

```
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
Loading composer repositories with package information
https://panopoly.gitlab.io/drupal-ckeditor-plugins could not be fully loaded (The "https://gitlab.com/users/sign_in" file could not be downloaded (HTTP/2 503 )), package information was loaded from the local cache and may be out of date

                                                                                     
  [Composer\Downloader\TransportException]                                           
  The "https://gitlab.com/users/sign_in" file could not be downloaded (HTTP/2 503 )  
                                                                                     

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-scripts] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>]...
```

**And I expected this to happen:**

When using Composer 1.10.17, it will successfully download the required package (using the composer repository at https://panopoly.gitlab.io/drupal-ckeditor-plugins/) and all its dependencies.

That composer repository is generated using the latest version of [satis](https://github.com/composer/satis), and it appears to support Composer 2, because when I generate it in the exact same way locally, and update my composer.json to the composer repository on my local hard drive, it works fine with Composer 2! So, doesn't appear that satis is generating data that's incompatible with Composer 2, it seems to be something about GitLab Pages.

Using GitLab Pages in this way is not uncommon - I found a couple tutorials on the internet about doing it (for example, [here's one](https://iqon.net/article/using-gitlab-pages-host-composer-repositories)). You can keep the satis configuration in a repo on GitLab, and have GitLab CI run on every commit, pushing the result to GitLab Pages, making for a pretty nice workflow. So, it'd be nice to get this working again!

I don't know if the issue is on Composer's side or GitLab's side -- if it turns out to be a problem on GitLab's end, I'd be happy to open a ticket over there too. :-)

**Comment by Seldaek** [comment]
This is exactly the same problem as in https://github.com/composer/composer/issues/9506 - please read there, although it uses S3 and not GitLab Pages, the result in the same.

**Comment by dsnopek** [comment]
@Seldaek Can you give any additional insight into what GitLab Pages is doing wrong? I can open an issue or PR to GitLab Pages (since it's Open Source) if I can understand what needs to be changed. It's not exactly the same as #9506 because in that issue S3 was returning 403 (rather than 404) when a file didn't exist, but here it seems like Composer is requesting https://gitlab.com/users/sign_in for some reason, even though this is a totally public repository and it doesn't require login. If there's any documentation on what Composer is expecting from repositories over HTTP that'd be super helpful! Thanks :-)

**Comment by Seldaek** [comment]
@dsnopek from the info you gave me, it looks like https://panopoly.gitlab.io/drupal-ckeditor-plugins returns a redirect to the login page. If you provide the full output of a `composer update -vvv` maybe it'll tell us more though.

**Comment by dsnopek** [comment]
[Here's the output](https://gist.github.com/dsnopek/d1c9d77ae4ed84ac96cd209f69fcf9f8) of `composer update -vvv` using the composer.json that I posted above.

I guess it does look like it's doing a whole series of redirects after trying to download https://panopoly.gitlab.io/panopoly/drupal-ckeditor-plugins/p2/drupal-ckeditor-plugin/a11yhelp.json however that's actually the wrong URL. The right URL for that JSON file is https://panopoly.gitlab.io/drupal-ckeditor-plugins/p2/drupal-ckeditor-plugin/a11yhelp.json

Hm. Perhaps satis is generating the repository incorrectly? Oddly when I try to access the same repo locally on disk it works fine. Anyway, I'll look into that and see what I find... Thanks for the suggestion to try `composer update -vvv`!

**Comment by Seldaek** [comment]
Yeah it just doesn't seem like a composer issue.

**Comment by dsnopek** [comment]
Alright, I found the issue! It's turns out the 'homepage' was wrong in the satis.json, but I never noticed before because apparently that doesn't matter for Composer 1 or when using the Composer 2 repository locally on disk -- it only broke things when using Composer 2 over HTTP.

Thanks for your help! :-)
