### ISSUE TITLE
composer issue while creating laravel project

### ISSUE THREAD

**Issue by Sunilmr028** [composer/composer#9510]
[Composer\Downloader\TransportException]
Unable to use a proxy: malformed http_proxy url

**Comment by johnstevenson** [comment]
Your proxy url should be formatted `scheme://host:port` so that PHP can parse it correctly.

**Comment by Sunilmr028** [comment]
and where can I correct it?

**Comment by johnstevenson** [comment]
The setting comes from the environment. You must have an `http_proxy` environment variable which you either need to set correctly if you want to use a proxy, or remove if you don't.

**Comment by Sunilmr028** [comment]
Still not working..tried almost everything :/

**Comment by Sunilmr028** [comment]
Thanks a lot!! Seldaek :+1:

**Comment by MohammadShakilCSE** [comment]
How i set http_proxy environment variable ? help please i am new in laravel and i face same problem

**Comment by MatiasManevi** [comment]
Can you explain how this should be done? What about if you don't want to use proxy is that possible?

**Comment by 20021179** [comment]
ss

**Comment by Developer-Felix** [comment]
C:\xampp\htdocs>composer require barryvdh/laravel-debugbar --dev

In ProxyManager.php line 89:

  Unable to use a proxy: malformed http_proxy url

Please Help me solve these error

**Comment by sneha-7777** [comment]
first uninstall composer 
and install composer in installation time proxy box is there you dont give anything in that box click next.
thats working
