### ISSUE TITLE
Composer 2 not using ENV COMPOSER_MEMORY_LIMIT

### ISSUE THREAD

**Issue by ianlintner-wf** [composer/composer#9511]
I upgraded to composer 2
```
composer self-update --2
```
output
```
Updating to version 2.0.7 (2 channel).
```

When I run this command:
```bash
export COMPOSER_MEMORY_LIMIT=1
composer update
```

I get the following output:

```
Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 32768 bytes) in phar:///usr/local/sbin/composer/vendor/symfony/console/Helper/DialogHelper.php on line 338
```

And I expected this to happen:

Composer to use the ENV exported previously in my bash session/script as previous composer versions did.

I can workaround but it requires me to update a number of scripts with putting it inline
```
COMPOSER_MEMORY_LIMIT=-1 composer ...
```

**Comment by Seldaek** [comment]
Nothing changed there in v2, so not sure what is going on. By default if no COMPOSER_MEMORY_LIMIT is set it will increase the allowed memory limit to 1.5GB which should be plenty for v2. The only case it would not do that is if ini_set has been disabled somehow.

I see your `export COMPOSER_MEMORY_LIMIT=1` line is set to 1, not sure if it's a typo here or if you actually set it to 1, but that'd be bad. Make sure with `echo $COMPOSER_MEMORY_LIMIT` what it's set to.
