### ISSUE TITLE
composer update with version 2.0.7 fails on Windows and PHP 8 with exit code 1

### ISSUE THREAD

**Issue by ondrejmirtes** [composer/composer#9512]
I tried running with `-vvv` but it doesn't output anything related to the error: https://github.com/phpstan/phpstan-src/runs/1435151739?check_suite_focus=true

It's reliably reproducible on Windows with PHP 8 nightly build (that's what setup-php uses) and it always seem to crash on installing symfony/finder.

Any suggestions on what can I do to get to a useful error message?

It might be related (or not), but I had to make this change to PHP 8 polyfills in PHPStan for the nightly PHP 8 version to continue to work: https://github.com/phpstan/phpstan-src/commit/031621d0d06784a9c590d2a46cb5c55c2fad3894

**Comment by mvorisek** [comment]
To discover error location like this one I often use xdebug tracing, you simply trace all program execution and then look at the end when the script ended/crashed.

**Comment by ondrejmirtes** [comment]
@mvorisek Please send a PR to phpstan-src with the right setup-php arguments if you have experience with this.

**Comment by shivammathur** [comment]
@ondrejmirtes Try running it again

**Comment by terabytesoftw** [comment]
> @ondrejmirtes Intenta ejecutarlo de nuevo

Awesome work fine.

**Comment by ondrejmirtes** [comment]
I confirm it works now. What was the issue @shivammathur?

**Comment by shivammathur** [comment]
composer is failing with JIT in tracing mode `(opcache.jit=1255)` on PHP 8 on `Windows` and `macOS`. I have changed it to function mode `(opcache.jit=1235)`.
Ref: https://wiki.php.net/rfc/jit#phpini_defaults

**Comment by ondrejmirtes** [comment]
Awesome, thanks! Best to keep this issue probably open. Or is it a PHP bug that should be reported?

**Comment by shivammathur** [comment]
Seems like a PHP bug and related to https://bugs.php.net/bug.php?id=80275
