### ISSUE TITLE
composer2 can't find package versions but composer1 finds it fine

### ISSUE THREAD

**Issue by jacques** [composer/composer#9514]
My `composer.json`:

```json
{
    "name": "jacques/php-payfast-parsers",
    "description": "Parsers for PayFast Reconciliation Files",
    "repositories": [
    ],
    "config": {
        "optimize-autoloader": true,
        "sort-packages": true
    },
    "require": {
        "league/csv": "^9.6",
        "moneyphp/money": "^3.3"
    },
    "require-dev": {
        "friendsofphp/php-cs-fixer": "^2.16",
        "phpmd/phpmd": "^2.8",
        "phpro/grumphp": "^0.18",
        "phpunit/php-invoker": "^3.1",
        "phpunit/phpunit": "^9.4",
        "rector/rector": "^0.8.6",
        "squizlabs/php_codesniffer": "^3.5",
        "vimeo/psalm": "^4.1"
    },
    "autoload": {
        "psr-4": {
            "Jacques\\PayFast\\Parsers\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Jacques\\PayFast\\Parsers\\Tests\\": "tests/"
        }
    },
    "license": "mpl",
    "authors": [
        {
            "name": "Jacques Marneweck",
            "email": "jacques@powertrip.co.za"
        }
    ],
    "scripts": {
        "test": "vendor/bin/phpunit --colors --debug --configuration=tests/phpunit.xml --coverage-clover build/logs/clover.xml --coverage-text"
    }
}
```

[Commit after using composer on an older v1.x build](https://github.com/jacques/php-payfast-parsers/commit/d22019e3454a64f9f7cf0d270096f59e045dc181).

Output of `composer diagnose`:

```
23:10 $ composer diagnose
Checking composer.json: WARNING
License "mpl" is not a valid SPDX license identifier, see https://spdx.org/licenses/ if you use an open license.
If the software is closed-source, you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.7
PHP version: 7.4.12
PHP binary path: /usr/local/Cellar/php/7.4.12/bin/php
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
cURL version: 7.73.0 libz 1.2.11 ssl OpenSSL/1.1.1h
zip extension: OK
```

When I run this command:

```
composer update --lock
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies
Unable to find a compatible set of packages based on your non-dev requirements alone.
Your requirements can be resolved successfully when require-dev packages are present.
You may need to move packages from require-dev or some of their dependencies to require.

  Problem 1
    - Root composer.json requires league/csv ^9.6, found league/csv[9.5.0] but it does not match the constraint.
```

And I expected this to happen:

I would expect league/csv to update from 9.5 to 9.6 as the package exists.  On composer v1 on a SmartOS box this updated fine.

**Comment by jacques** [comment]
Might be related to #9481

**Comment by Seldaek** [comment]
What happens if you run it without `--lock`?

**Comment by boboldehampsink** [comment]
I have a similar issue. `composer update --lock` fails but `composer update` works

**Comment by Seldaek** [comment]
Please provide a copy of the composer.json, and composer.lock, and exact command you are running, otherwise we can't help.

**Comment by boboldehampsink** [comment]
```
{
    "name": "robuust/clubee",
    "description": "Clubee",
    "repositories": [
        {
            "type": "path",
            "url": "./plugins/clubee"
        }
    ],
    "require": {
        "php": "7.4.12",
        "ext-gd": "*",
        "ext-intl": "*",
        "ext-redis": "*",
        "aelvan/mailchimp-subscribe": "^3.0",
        "bertoost/craft-mailjet": "^1.2",
        "clubee/clubee": "^1.0",
        "codemix/yii2-streamlog": "^1.2",
        "craftcms/aws-s3": "^1.1",
        "craftcms/cms": "^3.5",
        "craftcms/contact-form": "^2.2",
        "craftcms/redactor": "^2.5",
        "digitick/sepa-xml": "^1.6",
        "hybridinteractive/craft-contact-form-extensions": "^1.1",
        "putyourlightson/craft-snaptcha": "^2.1",
        "robuust/craft-heroku-internal": "^1.0",
        "robuust/craft-sentry-log-target": "^1.0",
        "robuust/craft-turbolinks": "^1.0",
        "sebastianlenz/linkfield": "^1.0",
        "whoisjuan/craft-color-mixer": "^1.0",
        "yiisoft/yii2-redis": "^2.0"
    },
    "require-dev": {
        "codeception/codeception": "^4.0",
        "codeception/module-asserts": "^1.1",
        "codeception/module-webdriver": "^1.0",
        "codeception/module-yii2": "^1.0",
        "friendsofphp/php-cs-fixer": "^2.13",
        "heroku/heroku-buildpack-php": "*"
    },
    "autoload": {
        "psr-4": {
            "modules\\": "modules/",
            "fixtures\\": "fixtures/"
        }
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "scripts": {
        "post-install-cmd": "@composer require clubee/clubee --no-update",
        "compile": "@composer update --no-dev --lock"
    }
}

```

Command:
`composer install && composer compile`

Result:
```
Unable to find a compatible set of packages based on your non-dev requirements alone.
Your requirements can be resolved successfully when require-dev packages are present.
You may need to move packages from require-dev or some of their dependencies to require.

  Problem 1
    - Root composer.json requires clubee/clubee, it could not be found in any version, there may be a typo in the package name.

Script @composer update --no-dev --lock handling the compile event returned with error code 2
```

**Comment by Seldaek** [comment]
I can't repro partly because of this:


  [craft\composer\InvalidPluginException]
  Couldn't install clubee/clubee: Unable to determine the Plugin class


But I don't think fixing that would help me repro though.. as I said without your composer.lock file I can't reproduce this.

**Comment by boboldehampsink** [comment]
Sorry, forgot the lockfile: https://gist.github.com/boboldehampsink/e1adc0518cddba764c22775ce3adf9b7

**Comment by Seldaek** [comment]
Ok thanks, can repro now. I'll investigate in a bit.

**Comment by Seldaek** [comment]
@boboldehampsink ok so.. the lock file does not contain clubee/clubee, so it makes sense to me that it can't be found when you do update --lock, as update --lock really just rebuilds the lock file metadata with the exact versions which are in it.

So if you first `composer update clubee/clubee` then `composer update --lock` should work.

The reason it works in v1 is that v1 is kinda broken there, and not strict enough. 

The problem that remains though in v2 is that the error message is rather unclear, so we should definitely fix that. 

@naderman wdyt here? The issue seems to be that in Installer, the `fixedRootPackage` has no requires, so in this case no knowledge of clubee/clubee, so clubee/clubee does not get loaded in the poolbuilder as it is not required nor locked (as not in lock file yet). So essentially any new root require will break `composer update --lock` in this way. If we make sure the requires are added to the Request then it'd load fine and end up adding it, but then it does a bit more than --lock should do. If we don't do that, we need a way somehow to identify this situation in Problem so we can report it better. Or maybe we should do this earlier in Installer and fail hard early if we find any root require which is not satisfied by the lock file package?

**Comment by boboldehampsink** [comment]
I replaced `composer update --no-dev --lock` with `composer update clubee/clubee --no-dev` and it works fine now. Thanks!

**Comment by naderman** [comment]
@Seldaek I think what's broken is that composer update --lock is trying to satisfy any composer.json requirements at all? If that wasn't the case it'd work fine? But the only way I can see to fix that would be to store the root requires the lock file is based on in the lock file ...

**Comment by naderman** [comment]
@Seldaek (deleted my previous reply cause it was nonsense) Can you provide me with a summary or reproduce case here? I kind of don't understand the problem. New requires shouldn't be considered by composer update --lock and from what I can see they are not considered. So I fail to see adding something to composer.json would need to error or do anything special? update lock just updates the lock file?
