### ISSUE TITLE
Warn about making dev dependency prod dependency

### ISSUE THREAD

**Issue by rpkamp** [composer/composer#9516]
Not really an issue, more of a feature request.

What I've seen happen in our projects several times now is that when people upgrade a package to a newer version they use `composer require` to get the latest version. This is fine, but sometimes they forget `--dev` for packages that were in `dev` dependencies, or sometimes `--dev` is added out of habit and it shouldn't be (it should be a production dependency).

Is there a way that composer can at least warn when a package is moved from dev dependency to prod dependency or vice versa?

**Comment by Seldaek** [comment]
Sounds to me like their habit should be to run `composer update foo/bar` rather than require.. But yeah I think a warning here would make sense, or even perhaps prompting for confirmation if in interactive mode.

**Comment by rpkamp** [comment]
Nice, thanks 👍
