### ISSUE TITLE
Offline/Airgapped Installation

### ISSUE THREAD

**Issue by obeardly** [composer/composer#9518]
I would like to install composer in an airgapped environment. Is this currently possible? If so, can you please point me to any documentation and/or instructions on how to achieve this.

**Comment by Seldaek** [comment]
I am not sure what the restrictions are, but I imagine you have a way to transfer files there somehow.. The composer.phar files you can download from https://getcomposer.org/download/ are really all you need. You can use the sha256 checksums too to verify integrity.

You can then rename composer.phar to composer, make it executable and that's all there is to an installation.

**Comment by WyriHaximus** [comment]
So if you want to have an airgapped install of composer that be done with the instructions above. But what is next? Are you also want to use composer airgapped? Because in that case for any installs you need to have a local cache of all packages you need to install.
