### ISSUE TITLE
[Information] Usage of "optimize-autoloader" & "classmap-authoritative" install options

### ISSUE THREAD

**Issue by noniagriconomie** [composer/composer#9520]
My `composer.json`:

```json
not needed
```

Output of `composer diagnose`:

```
Composer version: 2.0.7
PHP version: 7.4.12
PHP binary path: /usr/local/Cellar/php/7.4.12/bin/php
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
cURL version: 7.73.0 libz 1.2.11 ssl OpenSSL/1.1.1h
```

When I run this command:

```
composer install --no-progress --no-interaction --no-dev --optimize-autoloader 
composer install --no-progress --no-interaction --no-dev --optimize-autoloader --classmap-authoritative
```

I get the following output:

```
Same vendor/composer/autoload_classmap.php as output
```

And I expected this to happen:

Cf this PR https://github.com/symfony/symfony-docs/pull/14618, the question part and the paragraph above and the `Execute this command to generate the class map`

- is it normal that the file is similar with/without the `--classmap-authoritative`
- do we agree that, even without the `--classmap-authoritative`, the file `vendor/composer/autoload_classmap.php` will exists?

thank you

**Comment by stof** [comment]
`--classmap-authoritative` changes the generated autoloader, not the generated classmap.

`vendor/composer/autoload_classmap.php` will exist as soon as Composer needs a classmap in the generated autoloader:

- packages using `classmap` in their autoload config will always end up there
- when enabling level 1 optimizations of the autoloader (`--optimize-autoloader`), Composer will also add all classes found through PSR-0 and PSR-4 in the classmap

So the existence of the file does not even indicate that you have a production autoloader. Even a development autoloader might have a (much smaller) classmap file.

**Comment by noniagriconomie** [comment]
@stof ok i see, but then the documentation on symfony performance page (linked PR) page is "wrong" isnt it?

While reading both symfony doc and composer doc, i understood that somehow the internal composer files generation logic will be different with/without this option, but seems not (at least for the existance of the file we are talking about)

**Comment by stof** [comment]
`--classmap-authoritative` indeed has no effect on the generation of the classmap. what it does is disabling the PSR-0/4 discovery mechanism (so that any class not present in the classmap is not found, without checking the filesystem for that).

the official documentation of composer about that behavior is at https://getcomposer.org/doc/articles/autoloader-optimization.md, not in the symfony doc. If the symfony docs is confusing you, that should be reported to https://github.com/symfony/symfony-docs, not to composer.

**Comment by noniagriconomie** [comment]
perfect lets continue on the related PR, thx!
