### ISSUE TITLE
Composer 1.10 and PHP 8

### ISSUE THREAD

**Issue by stof** [composer/composer#9523]
When reworking the CI setup for symfony/flex, we figured out that we could not actually run tests on PHP 8 and composer 1 without faking the platform as PHP 7.4.99 (which was there in the old Travis setup).
I think it might make sense to allow PHP 8 in composer 1.10 to decouple the PHP upgrade and the composer upgrade.

**Comment by Seldaek** [comment]
We don't have a working build on php8 for v1 though as far as I remember. We can allow it, it'll most likely be fine.. But it's not guaranteed.

**Comment by stof** [comment]
but is there any PHP 8 fixes in 2.x or was it just about changing the constraint ?
Regarding the CI config, we can probably backport it from the master branch

**Comment by Seldaek** [comment]
Ok fixed in https://github.com/composer/composer/commit/2754910dff29972c147ec2a1034f292fd874e4fc - please try if it helps with the flex CI if you can require composer/composer `^1.10@dev`

I don't think we had any php8 specific fixes in this repo.. but maybe I forgot. As for CI, it's probably feasible but I don't have time to spend on this, v1 being kinda EOL..

**Comment by ktomk** [comment]
@Seldaek; do you have a hint to get snapshot versions by self-update for --1 channel?

**Comment by Seldaek** [comment]
There are no snapshots but in this case composer is required directly as a regular package.

**Comment by smoench** [comment]
FYI Composer v1 uses composer/semver:^1.0 but the v1 branch is not compatible (or it just not allowed) with PHP 8 https://packagist.org/packages/composer/semver#1.7.1

**Comment by stof** [comment]
so we probably need the same change in `composer/semver`

**Comment by Seldaek** [comment]
FYI, I released last week a new 1.10 fixing this, and a new semver release too.
