### ISSUE TITLE
parallel zip on windows

### ISSUE THREAD

**Issue by staabm** [composer/composer#9527]
In the release radar stream yesterday @naderman mentioned that parallel zip is a major timesaver, but actually not "available" on windows without using WSL.

I am doing some research on possible alternatives and found e.g. https://stackoverflow.com/questions/38782928/how-to-add-man-and-zip-to-git-bash-installation-on-windows which describes a few ways in which one can make "zip" available on git bash.

I also thought about 7zip which is available on a lot of workstations.

could someone shed in some light what composer expects from the "zip"-cli command and how the parallelization is achieved? maybe we can get some alternative running on windows or at least document some instructions on how to get something working on git bash etc.

I am willing to do further research, but I am not yet sure how composer uses this cli command and what the cli command needs to provide, to be a proper alternative.

PS: I stumbled over some very long "extract archive" processes when installing https://github.com/rectorphp/rector which has a lot of dependencies. thats my use-case.

**Comment by staabm** [comment]
to be more precise: using the steps described in https://stackoverflow.com/a/55749636 I got `zip` running in git bash 4 windows:

```
staabm@staabm_laptop MINGW64 /c/xampp7.3/htdocs/redaxo (rector)
$ zip --help
Copyright (c) 1990-2008 Info-ZIP - Type 'zip "-L"' for software license.
Zip 3.0 (July 5th 2008). Usage:
zip [-options] [-b path] [-t mmddyyyy] [-n suffixes] [zipfile list] [-xi list]
  The default action is to add or replace zipfile entries from list, which
  can include the special name - to compress standard input.
  If zipfile and list are omitted, zip compresses stdin to stdout.
  -f   freshen: only changed files  -u   update: only changed or new files
  -d   delete entries in zipfile    -m   move into zipfile (delete OS files)
  -r   recurse into directories     -j   junk (don't record) directory names
  -0   store only                   -l   convert LF to CR LF (-ll CR LF to LF)
  -1   compress faster              -9   compress better
  -q   quiet operation              -v   verbose operation/print version info
  -c   add one-line comments        -z   add zipfile comment
  -@   read names from stdin        -o   make zipfile as old as latest entry
  -x   exclude the following names  -i   include only the following names
  -F   fix zipfile (-FF try harder) -D   do not add directory entries
  -A   adjust self-extracting exe   -J   junk zipfile prefix (unzipsfx)
  -T   test zipfile integrity       -X   eXclude eXtra file attributes
  -!   use privileges (if granted) to obtain all aspects of WinNT security
  -$   include volume label         -S   include system and hidden files
  -e   encrypt                      -n   don't compress these suffixes
  -h2  show more help
```

**Comment by naderman** [comment]
@staabm I misspoke regarding "zip". The program we use is "unzip". Code is in https://github.com/composer/composer/blob/master/src/Composer/Downloader/ZipDownloader.php - The extract() method currently always tries ZipArchive on Windows first. I think it wouldn't technically be necessary to use WSL if you install unzip on the bash shell and we somehow work this out, but I am basically clueless about Windows, so I'll let someone else answer this ;-)

**Comment by staabm** [comment]
cool, thx for the insight.

when using the official github-desktop client we get a git-bash which supports `unzip`

```
$ unzip
UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send
bug reports using http://www.info-zip.org/zip-bug.html; see README for details.

Usage: unzip [-Z] [-opts[modifiers]] file[.zip] [list] [-x xlist] [-d exdir]
  Default action is to extract files in list, except those in xlist, to exdir;
  file[.zip] may be a wildcard.  -Z => ZipInfo mode ("unzip -Z" for usage).

  -p  extract files to pipe, no messages     -l  list files (short format)
  -f  freshen existing files, create none    -t  test compressed archive data
  -u  update files, create if necessary      -z  display archive comment only
  -v  list verbosely/show version info       -T  timestamp archive to latest
  -x  exclude files that follow (in xlist)   -d  extract files into exdir
modifiers:
  -n  never overwrite existing files         -q  quiet mode (-qq => quieter)
  -o  overwrite files WITHOUT prompting      -a  auto-convert any text files
  -j  junk paths (do not make directories)   -aa treat ALL files as text
  -U  use escapes for all non-ASCII Unicode  -UU ignore any Unicode fields
  -C  match filenames case-insensitively     -L  make (some) names lowercase
  -X  restore UID/GID info                   -V  retain VMS version numbers
  -K  keep setuid/setgid/tacky permissions   -M  pipe through "more" pager
See "unzip -hh" or unzip.txt for more help.  Examples:
  unzip data1 -x joe   => extract all files except joe from zipfile data1.zip
  unzip -p foo | more  => send contents of foo.zip via pipe into program more
  unzip -fo foo ReadMe => quietly replace existing ReadMe if archive file newer
```

I will see what needs to be done to get composer use it on windows based hosts.

**Comment by stof** [comment]
Given that `unzip` allows parallelization in Composer 2, I think it would make sense to try it first on all OS instead of preferring ZipArchive on Windows.

**Comment by staabm** [comment]
I did some local tests, by commenting out https://github.com/composer/composer/blob/0da9e216fc1d52889c5b569fd60b719ef170abaa/src/Composer/Downloader/ZipDownloader.php#L225

with async unzip on windows (in my bash 4 windows):
```
$ rm -rf vendor/ && time ~/Documents/GitHub/composer/bin/composer install
...
real    1m34,384s
user    0m0,000s
sys     0m0,030s
```

with composer on 0da9e21 without further patching:

```
$ rm -rf vendor/ && time ~/Documents/GitHub/composer/bin/composer install
...
real    1m33,317s
user    0m0,000s
sys     0m0,030s
```

I am wondering why async unzip is not faster then sync unzip.
maybe its related that for rector a lot of [serial git-cloning happens](https://github.com/composer/composer/issues/9528) and I just need a better example with more "extraction time"?

I am also wondering why the `composer install` process does not saturate CPU and/or IO subsystem of my windows machine.

> Given that `unzip` allows parallelization in Composer 2, I think it would make sense to try it first on all OS instead of preferring ZipArchive on Windows.

I guess there is a reason why on windows `ZipArchive` is prefered over `unzip`?
if not we could just change the order as stof suggests.

if there is a reason for that maybe we can use some kind of feature detect so people on windows with the proper setup can benefit from the async unzip?

**Comment by Seldaek** [comment]
IIRC cygwyn/gitbash unzip is slower and possibly buggy too with certain archives, which is why we historically prefer ZipArchive on windows.

If you can try it out and prove it works better/faster I'm open to change this, but if not IMO it should stay as is. As someone who's been developing on Windows forever, and played with cygwin, msys and other kinds of hacks, my opinion is now a strong: Use WSL2 with files in the linux partition and that's it. Things run much smoother and much faster.
