### ISSUE TITLE
PHP 8.0.0 Compatibility issue

### ISSUE THREAD

**Issue by khalilst** [composer/composer#9529]
After running `composer update` in a laravel project with PHP 8.0.0, I've got the following error:

```
composer.json requires php ^7.2.5 but your php version (8.0.0) does not satisfy that requirement.
```

Composer version 2.0.7 2020-11-13 17:31:06

**Comment by staabm** [comment]
^7.2.5 does not satisfy 8.x.

Everything korrekt. The defined constraint does not allow 8.x

**Comment by ErdemAkin** [comment]
I have the same problem.  Since I don't want to open a new topic, I wanted to report here.

```
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpunit/phpunit[7.0.0, ..., 7.5.20] require php ^7.1 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires phpunit/phpunit ^7 -> satisfiable by phpunit/phpunit[7.0.0, ..., 7.5.20].

**Comment by staabm** [comment]
the projects you guys are using either needs to define/declare its php8 compatibillity by something like `^7.2.5 || ^8` or `>= 7.2.5` instead of  `^7.2.5`.

no change on the composer side required

**Comment by Seldaek** [comment]
@khalilst in your case, you need to fix the php requirement in your composer.json

@ErdemAkin for you it's the PHPUnit version which is the problem. You need to require PHPUnit `^8.5.13` or `^9.3` to get PHP 8 compatibility.

**Comment by MateenRay** [comment]
delete the composer.lock file
    "require": {
        "php": ">=7.2",
        .....
    },

Update to

    "require": {
        "php": "^7.2||^8.0",
        .....
    },
    
   run composer install
   
   Hope this will help

**Comment by shubham8982700** [comment]
composer install --ignore-platform-reqs

run this command in your terminal i hope its help you.

**Comment by AugustoMgit** [comment]
Para mim estava dando o mesmo erro.
Consegui prosseguir com a ajuda do colega:

composer require tymon/jwt-auth --ignore-platform-reqs

**Comment by adebayo-moses** [comment]
> delete the composer.lock file
> 
> update the composer.json file
> from
> 
> ```
> "require": {
>     "php": ">=7.2",
>     .....
> },
> ```
> 
> Update to
> 
> ```
> "require": {
>     "php": "^7.2||^8.0",
>     .....
> },
> ```
> 
> run composer install
> 
> Hope this will help

Deleting the composer.lock file helped!

**Comment by wayyuNug3** [comment]
puruka

**Comment by IIT-Bhupendra** [comment]
```
{
  "require": {
    "monolog/monolog": "2.0.2"
  }
}
```
```
composer update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires php ^7.2||^8.1 but your php version (8.0.9) does not satisfy that requirement.
  Problem 2
    - Root composer.json requires monolog/monolog 2.0.2 -> satisfiable by monolog/monolog[2.0.2].
    - monolog/monolog 2.0.2 requires php ^7.2 -> your php version (8.0.9) does not satisfy that requirement.
```

**Comment by herndlm** [comment]
@IIT-Bhupendra this is not a composer fault. The monolog version you're requiring is not supporting PHP 8, as it was added in 2.1. Therefore the dependencies cannot be resolved. Try to require `^2.1` instead.
I general I would avoid to pin to a specific version (except you use some tooling that handles that I guess :))

**Comment by mdmuzaffer** [comment]
{
"name": "laravel/laravel",
"type": "project",
"description": "The Laravel Framework.",
"keywords": ["framework", "laravel"],
"license": "MIT",
"require": {
		"php": "^7.3|^8.0",
		"fideloper/proxy": "^4.4",
		"fruitcake/laravel-cors": "^2.0",
		"guzzlehttp/guzzle": "^7.0.1",
		"laravel/framework": "^8.40",
		"laravel/socialite": "^5.3",
		"laravel/tinker": "^2.5",
		"dompdf/dompdf": "^1.0",
		"intervention/image": "^2.5",
		"maatwebsite/excel": "^3.1",
		"softon/indipay": "^1.2"
	},
"require-dev": {
"facade/ignition": "^2.5",
"fakerphp/faker": "^1.9.1",
"laravel/sail": "^1.0.1",
"laravel/ui": "^3.3",
"mockery/mockery": "^1.4.2",
"nunomaduro/collision": "^5.0",
"phpunit/phpunit": "^9.3.3"
},
"autoload": {
	"psr-4": {
		"App\\": "app/"
	},
	"classmap": [
		"database/seeds",
		"database/factories"
	],
	 "files": [
	"app/helper/helpers.php"
	]
},
"autoload-dev": {
	"psr-4": {
		"Tests\\": "tests/"
	}
},

"scripts": {
	"post-autoload-dump": [
		"Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
		"@php artisan package:discover --ansi"
	],
	"post-root-package-install": [
		"@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
	],
	"post-create-project-cmd": [
		"@php artisan key:generate --ansi"
	]
},

"extra": {
"laravel": {
"dont-discover": []
}
},
"config": {
"optimize-autoloader": true,
"preferred-install": "dist",
"sort-packages": true
},
"minimum-stability": "dev",
"prefer-stable": true
}

**Comment by kristiano646** [comment]
> delete the composer.lock file
> 
> update the composer.json file from
> 
> ```
> "require": {
>     "php": ">=7.2",
>     .....
> },
> ```
> 
> Update to
> 
> ```
> "require": {
>     "php": "^7.2||^8.0",
>     .....
> },
> ```
> 
> run composer install
> 
> Hope this will help
than'ks for your help [MateenRay](https://github.com/MateenRay)

**Comment by stof** [comment]
@Shehroz279 please open a new discussion (with all the relevant details) instead of commenting on an issue closed since years. Your project might not have the same dependency conflict that the one discussed here (and there is not enough info in your message to know).
