### ISSUE TITLE
Composer internal dependencies "override" plugin dependencies

### ISSUE THREAD

**Issue by MacFJA** [composer/composer#9531]
When a plugin and Composer have the same dependency, the dependency within Composer is used.

For example if a plugin need `symfony/process=^5`, it won't be the version 5.x that will be used but the version from Composer (which is `2.8.52.0` in Composer v2.0.7), that can create incompatibility.

I create a small example to illustrate the error: https://github.com/MacFJA/composer-plugin-dependencies-error

----

Maybe Composer dependencies should be _scoped_ (with something like [PHP-Scoper](https://github.com/humbug/php-scoper) ? )

----

The issue appear in both Composer 2.x and Composer 1.x (tested with Composer 1.10.17 and Composer 2.0.7)

**Comment by Seldaek** [comment]
That is definitely a known issue, and one of the reasons we try to keep our dependencies to a minimum. I am not going to mess around with PHP-Scoper though. Composer 2.2 should get more modern symfony deps, which hopefully will help out.
