### ISSUE TITLE
is_dir('/etc/xdg') triggers open_basedir error

### ISSUE THREAD

**Issue by fritzmg** [composer/composer#9541]
In 10590dc519fe9b12c8333452c75904155214ca3e support for XDG was added - however, this might trigger an `open_basedir` error in certain hosting environments, when trying to execute the `composer.phar`:

```
[ErrorException]                                                                                                                      
  is_dir(): open_basedir restriction in effect. File(/etc/xdg) is not within the allowed path(s): (/home/:/tmp/:/usr/local/pd-admin2/)
```

Now I realise that `open_basedir` should never be used and we will also remove it in that hosting environment. But I thought I should report this anyway - after all composer should just fall back to the next directory in that case, shouldn't it?

**Comment by fritzmg** [comment]
@Seldaek I think this line needs to be changed as well, otherwise the error will probably still happen:

https://github.com/composer/composer/blob/65b7eeef5f04e20fb10dad3404e553afe1c8ecd5/src/Composer/Factory.php#L662

**Comment by Seldaek** [comment]
Oh yeah I missed that, thanks :)
