### ISSUE TITLE
Starting installation from 2.0.7 and running self-update reverts to version 1

### ISSUE THREAD

**Issue by esserj** [composer/composer#9545]
Running the following wil result in a warning:

```sh
curl https://getcomposer.org/download/2.0.7/composer.phar -o /usr/local/bin/composer && chmod +x /usr/local/bin/composer
composer self-update --2
```

> Warning: You forced the install of 2.0.8 via --2, but 1.10.19 is the latest stable version. Updating to it via composer self-update --stable is recommended.
Upgrading to version 2.0.8 (2.x channel).
Use composer self-update --rollback to return to version 2.0.7

If you run `composer self-update` after that, you will be reverted back to the 1.x channel

Expected result:

when you start from v2, you should be on the 2.x channel and can only revert to version 1 by explicitly passing `--1` to self-update

**Comment by esserj** [comment]
https://blog.packagist.com/composer-2-0-is-now-available/
states:

> If you run composer self-update from 1.x, it will warn you that a new stable major version of Composer is available, and you can use composer self-update --2 to migrate to it.

which makes me believe 2 is stable

**Comment by beutelsend** [comment]
The default installer now also installs 1.10.19 instead of 2.0.7. This is very bad, since if you installed packages with 2.0.7 which target the version 2 api, these packages won't work anymore with 2.0.7. This also breaks peoples builds if they didn't specify the version explicitly.

Was there any announcement about this rollback?

**Comment by vhejda** [comment]
Just came here to report this. Our deployments started failing this morning, as https://getcomposer.org/installer now installs 1.10.19.

**Comment by picks44** [comment]
Same here.

**Comment by esserj** [comment]
referencing #9329

**Comment by Seldaek** [comment]
Fixed now sorry folks

**Comment by vhejda** [comment]
> Fixed now sorry folks

Legend, thank you! Happy weekend everyone.
