### ISSUE TITLE
[RFC] Prefer dist install even for dev versions

### ISSUE THREAD

**Issue by stof** [composer/composer#9546]
Currently, the default behavior of composer is to install from dist for releases and from source for dev versions.
As of composer 2, dist installs are done in parallel (both for downloading the archives and extracting them), while source installs are still sequential.
Would it make sense to change the default behavior to use dist for all versions ?

**Comment by Seldaek** [comment]
Yeah I also wonder how smart this default really is in practice. The thinking is that if you use dev versions you're more likely to have to go patch things in the vendor dir and then sending back commits from a git repo is easier, but it's hard to tell if this is in practice useful or not. I am not sure I like changing this default in a non-major release tho.

**Comment by naderman** [comment]
Given that my impression is that few people actually make use of editing the code there, I tend to agree that dist may be the better default.

I think if we do this we need to have an easy option available to restore the old behavior (preferred install config / command line flag?).

I'm also not sure at what point we can make this kind of a change. Would a 2.x release be okay as it just requires a config change to restore old behavior and the installed code is still usable in the same way, so no BC break? Or is this a BC break cause people would expect to operate on this git repos in an automated fashion that doesn't break on a new feature release?

**Comment by Seldaek** [comment]
> Or is this a BC break cause people would expect to operate on this git repos in an automated fashion that doesn't break on a new feature release?

That is my fear. Although we could argue they can also easily fix it.

preferred-install right now defaults to `auto`, so we could change the default to `dist`, and people could still set it to auto.

**Comment by mfn** [comment]
I would welcome this change!

Another data point for which I would probably get stoned to death publicly: there are still poor souls out there who _version_ (… … …) the `vendor/` there, which basically is consider a no no from the majority. And when you use git for that and then use a dev version which uses a git checkout, you break this general `vendor/` commit in spectacular ways 😅
The fix is easy: make sure you add `--prefer-dist`, but when you forget and don't realize it…

So, yay, would remove one more headache for some peasants.

**Comment by Seldaek** [comment]
@mfn The solution in your case is to set preferred-install to dist really, so you don't have to remember --prefer-dist. https://getcomposer.org/doc/06-config.md#preferred-install

**Comment by stof** [comment]
@mfn my proposal does not change the available modes for `preferred-install`, only the default value.

@Seldaek maybe we need a CLI flag `--prefer-install=dist|auto|source` to allow to apply the `auto` behavior from the CLI too ?

**Comment by naderman** [comment]
That sounds like a decent way to make this available as a CLI option.
