### ISSUE TITLE
The "sort-packages" flag should affect the "replace" section

### ISSUE THREAD

**Issue by DmitryFurs** [composer/composer#9548]
Currently, the **replace** section is not sorted when the **sort-packages** flag is set to **true**.

My `composer.json`:
[flag value](https://github.com/magento/magento2/blob/2.4.1/composer.json#L11)
[replace section](https://github.com/magento/magento2/blob/2.4.1/composer.json#L129-L351)

And I expected this to happen:
When the **sort-packages** flag is set to **true**, the **replace** section should be sorted exactly like **require** and **require-dev**.

### Additional info
It might be more appropriate to add this behavior for all [package links](https://getcomposer.org/doc/04-schema.md#package-links):
- [conflict](https://getcomposer.org/doc/04-schema.md#conflict)
- [replace](https://getcomposer.org/doc/04-schema.md#replace)
- [provide](https://getcomposer.org/doc/04-schema.md#provide)
- [suggest](https://getcomposer.org/doc/04-schema.md#suggest)

**Comment by Seldaek** [comment]
sort-package applies to require/require-dev when the require command is used, as it modifies those. replace/conflict/provide/suggest do not have a way to be modified via CLI, and thus IMO it's kinda sensible they don't get sorted.

You can use https://github.com/ergebnis/composer-normalize if you really care about these things.
