### ISSUE TITLE
Feature request: Powershell bin proxies on Windows

### ISSUE THREAD

**Issue by coldacid** [composer/composer#9551]
In addition to the batch file proxies, please add generation of Powershell script proxies for vendor binaries.

**Comment by johnstevenson** [comment]
Surelt this would only be possible if `PATHEXT` includes the `.ps1` extension (which it does not, by default). Is there a particular reason that you want this?

**Comment by coldacid** [comment]
Sometimes we need to supply multi-line parameters to a vendor binary (most recently, giacocorsiglia/stubs-generator's generate-stubs program) and this is difficult to impossible with batch files due to how environment and command line parsing works with cmd.exe. We can define multi-line parameters easily in Powershell either using heredocs or newline escapes in strings, and then use those with Powershell proxies, just like users on non-Windows systems can do with shell scripts.

`PATHEXT` is unimportant. Most likely, users won't run the Powershell proxies unless they're in Powershell, which doesn't rely on `PATHEXT`.

**Comment by johnstevenson** [comment]
Ah, so you would expect to run `./vendor/bin/stubs-generator.ps1` ?

**Comment by coldacid** [comment]
Yes. In fact PowerShell also prefers `.ps1` to `.bat` when resolving extensions for executable files when called without them, so `./vendor/bin/stubs-generator` when the vendor bins directory has `stubs-generator` shell script, `stubs-generator.bat` batch file, and `stubs-generator.ps1` PS script will appropriately launch the latter when running from PowerShell on Windows. (For PowerShell on Linux, I would assume that it would run the shell script instead, but I tend to stick to bash when I'm in a Linux environment.)

Since the shell script, batch file, and PowerShell proxies can all be treated the same way by callers, there shouldn't be any compatibility issues that I can think of, although anyone who does use PowerShell as their primary shell or for running scripts should probably still verify things work as expected when PS proxies are added. However, I've had no problem with the proxy I've
written myself and stuck in my project's vendor bins directory for using generate-stubs via PowerShell:

```powershell
$bin_target = Join-Path $(Split-Path $script:MyInvocation.MyCommand.Path) `
              '..\giacocorsiglia\stubs-generator\bin\generate-stubs'
php $bin_target $args
```

At least for a first-run, this seems to be all that's necessary. Line 2 would be the only thing different from proxy to proxy, simply a relative path from the vendor/bin directory to the actual PHP script to run.

**Comment by johnstevenson** [comment]
> For PowerShell on Linux, I would assume that it would run the shell script instead, but I tend to stick to bash when I'm in a Linux environment

Yes, that's what happens - unless the `.ps1` extension is used.

**Comment by johnstevenson** [comment]
Looking into this further, there is one major drawback, namely the user's execution policy, which by default does not allow the running of scripts.

So this would be a BC break (and confusing for users who can currently run composer commands from Powershell).

**Comment by coldacid** [comment]
I don't think it's that big a drawback as most developers who would use PowerShell likely would have updated their execution policy to allow local scripts. In Windows settings, on the Update & Security > For developers page, there's even the ability to apply that execution policy change.

If there's a way to make Powershell proxy generation optional, so that a user can enable them with a dotfile in their home directory or something, that would keep this from being a breaking change, wouldn't it? The break would then be changing the default for the option from off to on, and could be held back until Composer 3 comes along.

**Comment by johnstevenson** [comment]
> I don't think it's that big a drawback as most developers who would use PowerShell likely would have updated their execution policy to allow local scripts.

Sure, if they already run local scripts, but not if they are just using Powershell to run a few commands (and remember that Powershell is now promoted as the "default" shell, with its _Open Powershell Window here_ Explorer context menu option).

For these users this would make things unnecessarily complicated because now they've got to find out what the error message means and understand how to fix it. So this big BC break would be a pain point which provides them with absolutely no value.  

Composer does have a `bin-compat` config option, so maybe this could be used to optionally create `.ps1` proxies.

> We can define multi-line parameters easily in Powershell either using heredocs or newline escapes in strings, and then use those with Powershell proxies, just like users on non-Windows systems can do with shell scripts.

So why not just use Git Bash then?

**Comment by coldacid** [comment]
Git Bash is outside of the ecosystem, and there are things that you can do with PowerShell that can't be done with Bash. When one's infrastructure already uses PowerShell, switching over to Bash means redoing everything that already works with PowerShell as Bash scripts instead.

Anyone who does more in PowerShell than just "[running] a few commands" pretty much has to change the execution policy as it is. And Microsoft doesn't make it difficult to do, to the point that someone who is a developer could change the policy to allow local scripts without even having to run PowerShell themselves to do so (as mentioned, it's in the Settings app).

`bin-compat` may be an option. Adding a third value "ps1" could act like "full" with the addition of PowerShell proxies being generated.

**Comment by Seldaek** [comment]
Is this still needed given the Composer 2.2+ bin proxies are now PHP files (+ a .bat on windows)? You can then run `php vendor/bin/lala` in powershell I'd think.

**Comment by coldacid** [comment]
It's been a while since I needed to work on the project that lead to this request. It is still a nice-to-have though.

**Comment by Seldaek** [comment]
Yeah, nice to have but with a single person asking for it and nobody willing to implement, this will just gather more dust.. so closing until someone can come up with a reasonable pull request.
