### ISSUE TITLE
Missing or missplaced files of the composer in the Windows instalation

### ISSUE THREAD

**Issue by mdziczkowski** [composer/composer#9556]
After downloading the latest composer (2.0.8) and installing it on my Windows 10 (64-bit) following files were either not in their correct places or were not existing:

* I was installing composer into Program files (x86) directory (for all users), but it got installed into unknown place (I can't find the composer executable and the files were spreaded thru the disk to make difficult to find them)

* when attempting to check updates or to upgrade, composer complains about non-existing composer.json file in the install directory

**Comment by johnstevenson** [comment]
We cannot help unless you supply more information.

If you used the Windows installer (Composer-Setup.exe), then please open an issue here: https://github.com/composer/windows-setup/issues/new - make sure you supply a log file as per the instructions.

If not, please explain where composer.phar got installed to.

**Comment by mdziczkowski** [comment]
> If not, please explain where composer.phar got installed to.

The problem is that I don't know where it got installed, but when I type the `composer` command into console then it does work

**Comment by johnstevenson** [comment]
What is the output from `where composer` (cmd.exe) or `which composer` (Git Bash)?

**Comment by mdziczkowski** [comment]
> `where composer.exe`
INFO: Could not find files for the given pattern(s).

> `which composer'
'which' is not recognized as an internal or external command, operable program or batch file.

**Comment by johnstevenson** [comment]
So you did use the Windows installer (Composer-Setup.exe) afterall. So what exactly is the problem?

You can run `composer diagnose -vvv` which may highlight any issues.

**Comment by mdziczkowski** [comment]
> So you did use the Windows installer (Composer-Setup.exe) afterall. So what exactly is the problem?

as I wrote before, the problem are that when trying to run  the `composer global update` command, composer complains mainly about missing composer.json file in the instalation folder. The problem is that the composer installation files are spread on the disk and I don't know with folder is the main one and why composer hasn't become installed in the folder I wanted to install it but was thrown over most of the disk

**Comment by johnstevenson** [comment]
> as I wrote before, the problem are that when trying to run the composer global update command

Well, you didn't actually write that, but never mind.

>I don't know with folder is the main one and why composer hasn't become installed in the folder I wanted to install it but was thrown over most of the disk

It looks like the Windows installer has installed composer correctly (if you supplied a log file we'd know for sure, of course). I'm going to guess you have run `composer global update` without actually installing any global packages.

Please supply the output of the command that errors (`composer global update -vvv`) and `composer diagnose -vvv`.

**Comment by mdziczkowski** [comment]
> Please supply the output of the command that errors (composer global update -vvv) and composer diagnose -vvv.

when I attempted to create a project thru composer (with inclided the suggested by you command and parameter), one from the errors I got was (for security reasons the path was replaced with a placeholder):

> Failed to initialize global composer: Composer could not find the config file: <user home path>/AppData/Roaming/Composer/composer.json
