### ISSUE TITLE
Composer remove doesn't respect current indentation

### ISSUE THREAD

**Issue by Taluu** [composer/composer#9557]
My `composer.json` (This is kind of a random composer.json, but the important part is that it's an indent with 2 spaces instead of 4) :

```json
{
  "require": {
    "php": "7.3.*",
    "foo/package": "^1.0"
  }
}
```

When I run this command: 

```
composer remove foo/package
```

Then the output of my composer.json file is :

```json
{
    "require": {
        "php": "7.3.*",
        "foo/package": "^1.0"
    }
}
```

Note the indent level has changed, while I expected :

```json
{
  "require": {
    "php": "7.3.*",
    "foo/package": "^1.0"
  }
}
```

Note that it is fine with `composer require`.

**Comment by Seldaek** [comment]
With this composer.json it works fine for me.. Please give a composer.json where it's actually reproducible.

We do try to respect indentation as long as the JsonManipulator class can do the work, but in some cases it's too complex and it ends up falling back on a json_decode+json_encode, in which case the output is what JSON_PRETTY_PRINT  does.

**Comment by Taluu** [comment]
Hum, closing, as it seems updating to 2.0.8 (I was on 2.0.7) solved this.

**Comment by Seldaek** [comment]
Ah yeah probably was fixed by that last line changed here https://github.com/composer/composer/commit/c7da7e55c96398b85ea13685d637b46cb72bd44a
