### ISSUE TITLE
Autoload files - load vendors first

### ISSUE THREAD

**Issue by Vrtak-CZ** [composer/composer#956]
I'm using autoloading with custom files loader. And I have a problem because my loader depends some classes from vendors. But composer require my loader before vendor loader.

Here is generated `autoloader.php`:

``` php
<?php

// autoload.php generated by Composer
if (!class_exists('Composer\\Autoload\\ClassLoader', false)) {
    require __DIR__ . '/composer' . '/ClassLoader.php';
}

return call_user_func(function() {
    $loader = new \Composer\Autoload\ClassLoader();
    $composerDir = __DIR__ . '/composer';

    $map = require $composerDir . '/autoload_namespaces.php';
    foreach ($map as $namespace => $path) {
        $loader->add($namespace, $path);
    }

    $classMap = require $composerDir . '/autoload_classmap.php';
    if ($classMap) {
        $loader->addClassMap($classMap);
    }

    $loader->register();

    require $baseDir . '/Nella/loader.php'; // <-- my libs
    require $vendorDir . '/nette/nette/Nette/loader.php'; // <-- vendor libs

    return $loader;
});
```

I need load _Nette_ before my libs (_Nella_) because my (_Nella_) loader require some classes from _Nette_.

**Comment by onlyongunz** [comment]
How to mark that our lib should be loaded first?
I mean, it didn't depends on other, but its should be loaded first before anything else load.

**Comment by Wirone** [comment]
I have the same question as @onlyongunz - I have globally installed `apigen/apigen` and `symfony/var-dumper`, but when I use `dump()` version from `tracy/tracy` (required by ApiGen) is called. I want to use VarDumper's version.

**Comment by paslandau** [comment]
Would be nice to be able to define the order. Or even better: have an extra option to define files that need to be loaded first.

Use case: Trying to override the helper functions of laravel as they are specifically defined with that in mind, but there is no way to tell composer that my definition has to come before laravel's native one.

Context: https://laracasts.com/index.php/discuss/channels/general-discussion/override-functions-in-supporthelpersphp

Workaround: https://github.com/funkjedi/composer-include-files

**Comment by onlyongunz** [comment]
Well i think i'll sugest `load_first` to prioritize the package on load when it didn't depend on other liblary (unless it's php or something else), and add `--ignore-order` to ignore the `load_first`.
