### ISSUE TITLE
Can´t download Composer because I need to go to Internet by proxy

### ISSUE THREAD

**Issue by claudiaghi** [composer/composer#9562]
When I run this command: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');". 
I get the following output: failed to open stream: Connection timed out in Command line code on line 1.

The fact is that PHP is not recognizing the specifications I've given as regards the proxy it has to use to go to Internet. My question is: Where should I specify the proxy?

![SudoSu](https://user-images.githubusercontent.com/76055025/102230840-19adc080-3ecc-11eb-9f69-c8930fcc1207.PNG)

**Comment by stof** [comment]
Well, use an alternate way to download the installer script from https://getcomposer.org/installer
Using `php -r "copy(...)"` is handy in the doc because it is a cross-platform one-liner, but it indeed does not support reading HTTP_PROXY.

`curl -LsS -o composer-setup.php https://getcomposer.org/installer` will do the work if you have curl on your system, and that will support all proxy features supported by curl (i.e. it will automatically read the `HTTP_PROXY` env variable, and you can use the `--proxy-*` CLI options if needed)

**Comment by apfelbox** [comment]
Downloading the installer already worked with `wget https://getcomposer.org/installer` ?
If so, you can rename the downloaded file and skip this step.

**Comment by claudiaghi** [comment]
Thanks a lot for your quick answers stof and apfelbox! I answer your question apelbox: yes, it worked with wget. Which name should I give the file? After renaming, can I follow the steps indicated in the site? (
php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');")

**Comment by apfelbox** [comment]
Yes, rename it to `composer-setup.php` and then just proceed with the following steps (like comparing the hashes etc)

**Comment by claudiaghi** [comment]
OK. Thanks a lot!

**Comment by claudiaghi** [comment]
Now, the installation fails when I try to execute php composer-setup.php. The problem is that PHP is not recognizing the proxy.

**Comment by Seldaek** [comment]
How did you configure the proxy exactly?

Can you download `https://getcomposer.org/composer-2.phar` with your browser, rename this to composer.phar and then run `php composer.phar diagnose` -vvv and share the full output?

**Comment by claudiaghi** [comment]
Hi Seldaek!  It´s not me who configures the proxy but the security team. I attach what you asked me for. Hope you can help me. Thanks!

![ComposerPhar](https://user-images.githubusercontent.com/76055025/102253929-bf6e2900-3ee6-11eb-8dc2-3a56597c708e.PNG)

**Comment by Seldaek** [comment]
Ok so you clearly have no network access, and I don't think Composer is detecting any proxy config.

Again I am not sure how your security team configured proxy access, but Composer needs it in an HTTP_PROXY or HTTPS_PROXY environment variable.

**Comment by claudiaghi** [comment]
Hi, stof! As I didn't find the way of installing composer using "php -r ...." I'll use curl, as you suggested.  After executing the command, the file generated (composer-setup.php) has to be renamed composer? Thanks in advance!
