### ISSUE TITLE
Don't print unneeded stuff on composer script execution

### ISSUE THREAD

**Issue by paveldvorak5** [composer/composer#9564]
Could you disable echoing the command class when executing a composer script?
My point is treating an ouput as error when executing a composer script

That line is written at EventDispatcher::executeEventPhpScript
Can you make option to don't print that line or just don't print it?

Thanks a lot

P.S.:
You have an idea. When a cron script is running OK, don't print anything. It's impossible to do that this way

**Comment by Seldaek** [comment]
You can use --quiet to suppress output.

**Comment by paveldvorak5** [comment]
it supresses only composer messages or all?

**Comment by InvisibleSmiley** [comment]
It actually disables all output.

I think in the case of `composer run-script` the `-q`/`--quiet` flag should actually just disable Composer's own output and not the output of the script executed. Alternatively add a new option to the `run-script` command to specifically disable echoing the command to be executed there.

That would bring it in line with `npm run <script> --silent`.

@Seldaek Please let me know what you think and I will create a new issue to have it implemented the one way or the other.

**Comment by Seldaek** [comment]
It disables all output from composer AND scripts, but exceptions from composer will still show.

I am not sure I see such huge value in changing this, as the only thing we output is the command being executed, and that goes to stderr so should not cause any issues with stuff capturing output from the command being run.

**Comment by fredden** [comment]
@christianlerch perhaps the `run-script` could take a flag (like `--changed-only`) and run the other script internally to determine which files to act upon.
