### ISSUE TITLE
[Feature Request] Allow complex constraints with meta information

### ISSUE THREAD

**Issue by Wirone** [composer/composer#9570]
I would like to ask for allowing complex constraints in `require` and `require-dev` that could be used as meta information about **why** such constraint is used. Consider `composer.json`:

```
{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": ">=7.4",
        "doctrine/orm": "2.8.x-dev#2febb4509a4888644fce31e95ad28295dd55da95",
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    }
}

```

Since JSON does not provide comments it's impossible to provide information why `doctrine/orm` was locked to such specific version. I would like to define such requirement like this:

```
{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": ">=7.4",
        "doctrine/orm": {
            "constraint": "2.8.x-dev#2febb4509a4888644fce31e95ad28295dd55da95",
            "info": "This version was used in order to get rid of Psalm error (wrong phpDoc). Bump to stable version when released.",
            "see": [
                "https://github.com/doctrine/orm/pull/8386",
                "https://github.com/doctrine/orm/commit/2febb4509a4888644fce31e95ad28295dd55da95"
            ]
        },
    }
}

```

Composer should simply check if JSON map's value is a string and if not, use `constraint` from the object.

Without this functionality it is hard to find out why it is locked, Git history must be checked and this is time-consuming. Allowing complex constraints would also open the door for some automated operations (e.g. tagging such constraint so Composer could warn user that packge has newer, acceptable version for update - because locking to commit would disable updating with `composer update` and user might not know there is update available).

Would be great if someone from core team responded, because if it is going to be accepted, someone could work on it :slightly_smiling_face:

**Comment by Seldaek** [comment]
Sorry but nope that's not something we're looking at supporting, too much added complexity for the value it'd bring.

You can use as a workaround something like:

```json
"_comment": {
    "doctrine/orm": "This version was used in order to get rid of Psalm error (wrong phpDoc). Bump to stable version when released."
},
"require": {
    "doctrine/orm": "..."
}
```

**Comment by Wirone** [comment]
I know that adding such "comment" is possible but it is out of the constraint's context and as such it can be overlooked. I don't agree that my proposal would add to much complexity, it would only add 2 new requirements: 1) checking that map's value is a string or nested map, 2) nested map contains key `constraint` (for example, could be different) and value is a string. Other fields in the nested map could be ignored, allowing users to put anything there.

But OK, thanks for the quick answer 👍

**Comment by Seldaek** [comment]
There are other tools reading composer.json files, so the complexity is not just these two things in composer, it's having repercussions in the whole ecosystem. That's mainly why it's IMO not worth it.
