### ISSUE TITLE
[v2] Conflict between provide and replace.

### ISSUE THREAD

**Issue by mathieutu** [composer/composer#9572]
Hi, 

We have a problem with heroku installation of a package which `provides` a php extension.

This was the initial issue: https://github.com/phpseclib/bcmath_compat/issues/1

[According to @naderman](https://github.com/phpseclib/bcmath_compat/issues/1#issuecomment-618951036), the problem should be fixed with composer 2:
>Wanted to mention that in Composer v2 a replace will no longer conflict with a provide for the same name. So the underlying problem there will be resolved if you use Composer2.

But actually we still have the same problem. A temporary fix was made on a tag, but we do not have any package update.

Any idea?

Thanks.

My `composer.json`:

```json
{
  "require": {
    "php": "^8.0",
    "ext-json": "*",
    "ext-pgsql": "*",
    "phpseclib/bcmath_compat": "^2.0",
  }
}

```

For information here is the particular way Heroku use composer metadata:
>The issue that follows then is that phpseclib/bcmath_compat via its composer.json metadata provides the ext-bcmath extension, but that extension is marked as replaced (because it's bundled with PHP) by PHP 7.3.13.
>
>A replace is a provide plus a conflict, and that's why PHP 7.3.13 (with ext-bcmath available as a shared extension) conflicts.
>
>This doesn't happen on your local machine because dependency resolution works differently there - your regular composer install step is working, but on Heroku, what's failing is the "platform install" step that installs PHP and all necessary extensions, not userland dependencies, using a special custom repository and installer, and a composer.json generated from your composer.lock.

More information in this comment from @dzuelke: https://github.com/phpseclib/bcmath_compat/issues/1#issuecomment-573112000

Other questions not relevant as this is happening in the Heroku CI and I can't reproduce locally.

**Comment by naderman** [comment]
@mathieutu Could you provide full error output, ideally even all the info we ask for in the issue template in so far as it applies to heroku?

**Comment by dzuelke** [comment]
The platform installation step on Heroku is still performed using Composer 1, so this is expected behavior at the moment.

**Comment by mathieutu** [comment]
Ok si it's clear. Thanks @dzuelke. I'm closing it for now, until heroku release the v2 implementation, and we'll see at the moment if we still have the problem.

**Comment by cja-github** [comment]
Hi. I have this problem. What's the solution? Does this mean I can't use Heroku? (I'm actually using the Digital Ocean Apps feature, which itself seems to use some part of Heroku.)

**Comment by stof** [comment]
@cja-github according to the readme of phpseclib/bcmath_compat, the solution is to pin it to their 1.0.4 release until heroku migrates to composer 2 for the platform installation

**Comment by seanmorris** [comment]
Is this going to be fixed?
