### ISSUE TITLE
Composer install -LMS

### ISSUE THREAD

**Issue by Xanshara** [composer/composer#9578]
After executing `composer install`
It appears
`composer install Do not run Composer as root/super user! See https://getcomposer.org/root for details Continue as root/super user [yes]? yes Installing dependencies from lock file (including require-dev) Verifying lock file contents can be installed on current platform. Nothing to install, update or remove Generating autoload files 6 packages you are using are looking for funding. Use the composer fundcommand to find out more!`
The files are loaded but unfortunately there is no final compilation. How to solve the problem?

**Comment by Seldaek** [comment]
Please follow the issue template, I have no idea how to help you like this..
