### ISSUE TITLE
Broken Color Chars in Windows Terminal

### ISSUE THREAD

**Issue by klodoma** [composer/composer#9581]
```
git version 2.30.0.windows.1
composer version: 2.0.8
```

I am having problems understanding what is going on here.
On `composer update` I do execute some commands, one of them is pulling another repository, for example: `git pull`. 

The output of this command messes up the whole output of the terminal under windows. Screenshots added. 

I created a repo to replicate this use-case: 
https://github.com/klodoma/symfony-demo/tree/invalid-chars

If I run a `composer update`
I get this output:

```
d:\Projects\espos\repos\s55-demo>composer update
> App\Composer\Setup::setup
Some Setup Info
Already up to date.
[32mLoading composer repositories with package information[39m
[32mUpdating dependencies[39m
Nothing to modify in lock file
[32mInstalling dependencies from lock file (including require-dev)[39m
Nothing to install, update or remove
[32mGenerating autoload files[39m
[32mcomposer/package-versions-deprecated:[39m Generating version class...
[32mcomposer/package-versions-deprecated:[39m ...done generating version class
[32m93 packages you are using are looking for funding.[39m
[32mUse the `composer fund` command to find out more![39m

[32mSynchronizing package.json with PHP packages[39m
Don't forget to run [33mnpm install --force[39m or [33myarn install --force[39m to refresh your Javascript dependencies!
Run [33mcomposer recipes[39m at any time to see the status of your Symfony recipes.

Executing script cache:clear [32m[OK][39m
Executing script assets:install --symlink --relative public [32m[OK][39m
```

Notable changes:
in composer.json:

```json
    "scripts": {
        "setup": "App\\Composer\\Setup::setup",
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd"
        },
        "pre-install-cmd": [
            "@setup"
        ],
        "pre-update-cmd": [
            "@setup"
        ],
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
```
src/Composer/Setup.php
```php
namespace App\Composer;

use Composer\Script\Event;

class Setup
{
    protected Event $event;

    public static function setup(Event $event)
    {
        $io = $event->getIO();
        $io->warning('Some Setup Info');
        system('git pull');
    }
}
```

![Screenshot_18](https://user-images.githubusercontent.com/944350/103374608-51298900-4ad8-11eb-8ca0-955f5c3cb09c.png)

If I remove the `system('git pull');` then all looks good. 

```
d:\Projects\espos\repos\s55-demo>git --version
git version 2.30.0.windows.1
```

![Screenshot_19](https://user-images.githubusercontent.com/944350/103374611-51c21f80-4ad8-11eb-9aba-5d065abf694f.png)

Any ideas?

**Comment by Seldaek** [comment]
Which terminal app are you using? And how did you install git?

I'd recommend trying out [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701) if you haven't

**Comment by klodoma** [comment]
It happens in:
- **"cmd.exe"** Not OK
- native powershell OK
- powershell 7("C:\bin\PowerShell\7\pwsh.exe") - Not OK
- If I run it through ConEmu then it works well. 

For Git, I use the portable version from here: https://git-scm.com/download/win


Actually, I noticed this while running commands through [Intelij Idea](https://www.jetbrains.com/idea). 

I am not even sure that "composer" is to blame or the mix between `php` and `git` output.

Screenshots attached.

![Screenshot_31](https://user-images.githubusercontent.com/944350/103986212-a4f83a00-518a-11eb-8ccf-bb5513df4511.png)
![Screenshot_33](https://user-images.githubusercontent.com/944350/103986213-a590d080-518a-11eb-9ee9-579c3596d86e.png)
![Screenshot_32](https://user-images.githubusercontent.com/944350/103986214-a590d080-518a-11eb-8f7c-3c4f8ae6ec75.png)
![Screenshot_26](https://user-images.githubusercontent.com/944350/103985539-69a93b80-5189-11eb-9049-f66dcdcc03f7.png)

**Comment by Seldaek** [comment]
I'm guessing it's a bad combination of the terminal in PHPStorm combined with hacks that git for windows is doing, but I'm not sure.

In any case it does not look like something we can fix so I'm gonna close this.
