### ISSUE TITLE
Allow disabling InstalledVersions

### ISSUE THREAD

**Issue by shyim** [composer/composer#9608]
In a project with multiple vendor folders. I want to have the flexibility to disable `InstalledVersions` for a specific vendor folder to ensure that the correct `InstalledVersions` is loaded

**Comment by Seldaek** [comment]
You can use InstalledVersions::reload() to make sure the correct dataset is in memory.. IMO this is a better approach. If we allow disabling it then people can't rely on composer-runtime-api 2.0 offering this feature consistently, and it'll be a mess, so I'd rather not go there.

https://github.com/composer/composer/blob/de58c5499ebc4d4c0193803e006f46a9eec02fda/src/Composer/InstalledVersions.php#L174-L192

**Comment by shyim** [comment]
Thanks for your point. As a library. I can't do that. So I will just add a rm to my script 😅
