### ISSUE TITLE
Running `composer create-project` runs install script before `post-create-project`

### ISSUE THREAD

**Issue by I-Valchev** [composer/composer#9610]
After running `composer create-project {some/project}`, it appears that the `post-install-cmd` script runs before `post-create-project-cmd`.

Is this intentional? Is there a way around this?

The issue is the following: in a project, there are migrations that need to run only on `post-create-project-cmd`. In `post-install-cmd`, however, there is a check which shows an error if there are missing migrations.

Essentially, if `post-create-project-cmd` runs first, it is OK. The vice-versa is a problem.

Thanks!

**Comment by stof** [comment]
well, this happens because the `create-project` runs an install as a subpart of its work.

A workaround for your case would be to run `create-project --no-install` and run `composer install` separately after that.

**Comment by I-Valchev** [comment]
I see! Thanks @stof , is there a way to pass some variable to the script that detects the post-install is called in that scenario?

**Comment by Seldaek** [comment]
You could perhaps listen to post-root-package-install, but that won't have the dependencies installed yet.. But maybe there you can set a flag so post-install-cmd knows it should not act (and unset the flag in post-create-project-cmd)?
