### ISSUE TITLE
Add missing NL after download progress

### ISSUE THREAD

**Issue by mvorisek** [composer/composer#9621]
this is output from the latest (2.0.8) composer:
```
  - Downloading paypal/merchant-sdk-php (v3.12.0)
 0/2 [>---------------------------]   0%
 1/2 [==============>-------------]  50%
 2/2 [============================] 100%  - Installing composer/package-versions-deprecated (1.11.99.1): Extracting archive
  - Installing doctrine/event-manager (1.1.1): Extracting archive
```

environment: Windows, PHP 7.4, Powershell

expected output:
```
  - Downloading paypal/merchant-sdk-php (v3.12.0)
 0/2 [>---------------------------]   0%
 1/2 [==============>-------------]  50%
 2/2 [============================] 100%
  - Installing composer/package-versions-deprecated (1.11.99.1): Extracting archive
  - Installing doctrine/event-manager (1.1.1): Extracting archive
```

**Comment by stof** [comment]
I think the issue happens only when the terminal does not support the escape sequence used to overwrite the text. The progressbar is replacing each line (which is also why it appears multiple times here)

**Comment by Seldaek** [comment]
Right, seems weird though as powershell should support this AFAIK. Are you in the powershell app itself? Have you tried using the new [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701)?

**Comment by mvorisek** [comment]
Please reopen, this should be fixed.

**Comment by Seldaek** [comment]
If you figure out how we can detect the problematic terminal emulators, sure. But IMO this is supported almost everywhere and thus is not worth investing much time in it.

**Comment by mvorisek** [comment]
Please keep open for a while to give others a change to figure it out. This is a message everyone on Windows see and it should be formatted nicely for better UX :)

**Comment by Seldaek** [comment]
Alright if someone wants to spend time on this great, but I won't :) FWIW, I am on Windows too but I use WSL2 + Windows Terminal and as such never use PowerShell. Things work way smoother this way I find.

**Comment by mvorisek** [comment]
can be reproduced using GH Actions with Windows image:
```
on:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: "Clone repo and run composer install"
        run: |
            git clone https://github.com/atk4/ui.git ./
            composer install --ignore-platform-reqs
```

output:
```
...
  - Downloading phpstan/phpstan (0.12.87)
  - Downloading phpunit/phpcov (8.2.0)
  0/95 [>---------------------------]   0%
  8/95 [==>-------------------------]   8%
 23/95 [======>---------------------]  24%
 36/95 [==========>-----------------]  37%
 47/95 [=============>--------------]  49%
 60/95 [=================>----------]  63%
 70/95 [====================>-------]  73%
 77/95 [======================>-----]  81%
 89/95 [==========================>-]  93%
 94/95 [===========================>]  98%
 95/95 [============================] 100%  - Installing composer/package-versions-deprecated (1.11.99.1): Extracting archive
  - Installing localheinz/diff (1.1.1): Extracting archive
  - Installing justinrainbow/json-schema (5.2.10): Extracting archive
  - Installing ergebnis/json-printer (3.1.1): Extracting archive
  - Installing ergebnis/json-normalizer (1.0.3): Extracting archive
    0 [>---------------------------]    0 [>---------------------------]    0 [>---------------------------]  - Installing ergebnis/composer-normalize (2.13.3): Extracting archive
  - Installing symfony/polyfill-ctype (v1.22.1): Extracting archive
  - Installing symfony/deprecation-contracts (v2.4.0): Extracting archive
...
```

**Comment by mvorisek** [comment]
@Seldaek this issue is present in linux too, see https://github.com/phpstan/phpstan/runs/2574267523#step:6:199

**Comment by Seldaek** [comment]
This is also an escape sequence support issue I suspect. Can be disabled with --no-progress which really makes sense on CI.

**Comment by Seldaek** [comment]
Maybe we should only output progress if ConsoleIO::isDecorated returns true.. That'd possibly fix it. Can you try on your powershell @mvorisek ?

**Comment by Seldaek** [comment]
I mean here https://github.com/composer/composer/blob/master/src/Composer/Installer/InstallationManager.php#L454 adding `&& $this->io->isDecorated()`

**Comment by mvorisek** [comment]
@Seldaek this just works :), PR for it is here: https://github.com/composer/composer/pull/9880

**Comment by Seldaek** [comment]
Looked  a bit closer at this and found a better fix than disabling it outright while looking at ProgressBar sources
