### ISSUE TITLE
Show outdated packages despite conflicting platform config

### ISSUE THREAD

**Issue by umulmrum** [composer/composer#9631]
My `composer.json`:

```json
{
    "require": {
        "roave/doctrine-simplecache": "^2.3"
    },
    "config": {
        "platform": {
            "php": "7.3.26"
        }
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.8
PHP version: 7.3.26 - Package overridden via config.platform, actual: 7.4.14
PHP binary path: /usr/bin/php
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
cURL version: 7.61.1 libz 1.2.7 ssl OpenSSL/1.0.2k
zip: extension present, unzip present
```

When I run this command:

```
composer outdated
```

I get the following output:

```
<empty>
```

And I expected this to happen:

As `roave/doctrine-simplecache` is already available in version 2.4.0, I'd like Composer to provide this information. When removing the platform constraint, output is as expected.

That lib requires PHP 7.4 in its release 2.4.0 but my composer.json sets a platform constraint on PHP 7.3, which is why the new version isn't taken into account. While this behavior might be intended, I think it would be great if `outdated` told me about the new release anyway. After all the PHP constraint isn't so much different from other version constraints (from a user perspective), and it would be helpful if Composer reminded me of keeping infrastructure up-to-date. Maybe a new color code would make sense for this case.

Thanks for considering!

**Comment by Seldaek** [comment]
I think we could add a --ignore-platform-reqs flag here too which would not take the platform into account then..

The point of this default behavior is that it doesn't nag you with packages you would not be able to install due to your PHP version, which is IMO something you should for sure keep up to date, but it should in theory not be because of a dependency that you must upgrade PHP.

**Comment by umulmrum** [comment]
`--ignore-platform-reqs` sounds good :-)

**Comment by jeroennoten** [comment]
I really mis this feature. I just want to see which packages are outdated and see their newest versions, not only when they are compatible with the current platform requirements.

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/pull/10293 which adds --ignore-platform-reqs/--ignore-platform-req to the outdated command.
