### ISSUE TITLE
How to fix undefined index: name in PackageManifest.php line 131 error with Composer

### ISSUE THREAD

**Issue by Sravan2** [composer/composer#9640]
When I run composer Update.

How to fix undefined index: name in PackageManifest.php line 131 error with Composer without changing the code in  PackageManifest.php.

I have changed
$packages = json_decode($this->files->get($path), true);
**$packages = json_decode($this->files->get($path), true)['packages'];**

But I don't want to do this.

 Composer version 2.0.8 2020-12-03 17:20:38
 Laravel Framework 7.0.8
 PHP 7.2.34-8

**Comment by Seldaek** [comment]
No idea how this relates to Composer sorry.
