### ISSUE TITLE
compose.json

### ISSUE THREAD

**Issue by kadirselcuk** [composer/composer#9642]
My `composer.json`:

```json
...replace me...
```

Output of `composer diagnose`:

```
...replace me...
```

When I run this command: 

```
...replace me...
```

I get the following output: 

```
...replace me...
```

And I expected this to happen:

**Comment by lobom4** [comment]
> 
> 
> My `composer.json`:
> 
> ```json
> ...@Lonem4_bot...
> ```
> 
> Output of `composer diagnose`:
> 
> ```
> ...@Lonem4_bot...
> ```
> 
> When I run this command: 
> 
> ```
> ...@Lonem4_bot...
> ```
> 
> I get the following output: 
> 
> ```
> ...@Lonem4_bot...
> ```
> 
> And I expected this to happen:enter banks account 
>
