### ISSUE TITLE
Improvements to InstalledVersions

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#9648]
As per https://github.com/composer/installers/issues/470#issuecomment-740691709 & following comments - we should add a way to retrieve packages by type, and also include a bit more information about each package than only name/version/ref, namely:

- type
- install path

We should also include the root package in all this.

**Comment by ochorocho** [comment]
@Seldaek i'm working on this now. What do you mean by "We should also include the root package in all this."?
Do you want me to include the "Root package name" along with "type" and "install_path" ?

**Comment by Seldaek** [comment]
@ochorocho I mean the root package should also have an install path and all, I don't think it's anything special really, just a reminder to check when reviewing, but I think you can probably ignore this and it'll just work.

**Comment by aimeos** [comment]
@Seldaek When is this feature expected to occur in composer? Is there a planned time frame?

**Comment by Seldaek** [comment]
Hoping to merge @ochorocho 's PR next week, but it'll be shipping in Composer 2.1 for sure, when that ships though I am not sure.
