### ISSUE TITLE
Composer2 removes component that Composer 1 would retain

### ISSUE THREAD

**Issue by rkrx** [composer/composer#9650]
My PHP-Version is 7.4. Start with this composer.json `composer.json`:

```json
{"require": {
    "psr/http-client": "^1.0"
}}
```

Run `composer install`. Now, if you add `ricardofiorani/guzzle-psr18-adapter` in version `v1.0.3`, `psr/http-client` will be removed with Composer2:

```
composer require ricardofiorani/guzzle-psr18-adapter v1.0.3
```

Here are two scripts to demonstrate the behavior of composer v1 vs v2.

## Composer 1:

```
rm -Rf vendor composer.lock
echo "{}" > composer.json 
composer self-update --1
composer require psr/http-client
composer require ricardofiorani/guzzle-psr18-adapter v1.0.3
```

Composer will add `ricardofiorani/guzzle-psr18-adapter` in version `v1.0.3` and will retain `psr/http-client` (with version `1.0.1` currently).

## Composer 2:

```
rm -Rf vendor composer.lock
echo "{}" > composer.json
composer self-update --2
composer require psr/http-client
composer require ricardofiorani/guzzle-psr18-adapter v1.0.3
```

No idea what's so special about the [composer.json](https://github.com/ricardofiorani/guzzle-psr18-adapter/blob/438353d87054237569932ed52552eed831ad7801/composer.json) of ricardofiorani/guzzle-psr18-adapter.

## Full run

You can run both scripts in one run with `composer show -i` at the end of each run:

```
echo '---------- COMPOSER 1 ----------'
rm -Rf vendor composer.lock
echo '{}' > composer.json
composer self-update --1
composer require psr/http-client ^1.0
composer require ricardofiorani/guzzle-psr18-adapter v1.0.3
composer show -i

echo '---------- COMPOSER 2 ----------'
rm -Rf vendor composer.lock
echo '{}' > composer.json
composer self-update --2
composer require psr/http-client ^1.0
composer require ricardofiorani/guzzle-psr18-adapter v1.0.3
composer show -i
```

**Comment by stof** [comment]
the issue is not in Composer 2. It is in `ricardofiorani/guzzle-psr18-adapter`. This packages says it provides the code for `psr/http-client` instead of saying it provides a `psr/http-client-implementation`.

The composer "bug" is actually in composer 1 which ignores part of what the package says in its metadata.

**Comment by stof** [comment]
note that I already submitted a [fix for the package](https://github.com/ricardofiorani/guzzle-psr18-adapter/pull/12) which has been merged but not released.

**Comment by rkrx** [comment]
Thanks for the explanation!
