### ISSUE TITLE
Why is Composer not showing up in Safari's Google search suggestions?

### ISSUE THREAD

**Issue by matronator** [composer/composer#9652]
First of all, I apologize as this might not belong in here, though it is (somewhat) related to the product. Please don't delete this, just lock it and I'll copy the issue's body to the appropriate place. Also if you could please direct me to the appropriate place, that'd be very much appreciated 😅.

This is not so much an issue with Composer itself, more like an annoyance when trying to look up any information about it. Ever since I learned about Composer (few years back), every time I would go to look for something using the Safari's address bar with auto-suggestions from Google and started typing `composer`, there would be absolutely no auto-suggestions showing up.

Tried in incognito, same results. The suggestions show up on Google itself, just not in the Safari search bar. Is it banned by Apple somehow or what's going on? Anyone else has this issue?

Cheers!

**Comment by stof** [comment]
that's something to ask to Apple, not to Composer.

**Comment by Seldaek** [comment]
Absolutely no idea, and no idea who to even ask.. Go ring the doorbell at Apple HQ I guess :)
