### ISSUE TITLE
"Undefined index: file" test failures (running in CI with no network access)

### ISSUE THREAD

**Issue by bryceharrington** [composer/composer#9654]
Ubuntu's CI system is seeing test failures after switching to Composer 2.0.8 from 1.10.19.  After updating to phpunit 9.5 most of the failures resolved, but 3 remain:

1) Composer\Test\Downloader\XzDownloaderTest::testErrorMessages
Failed asserting that 'Undefined index: file' matches PCRE pattern "/(File format not recognized|Unrecognized archive format)/i".

/tmp/autopkgtest.brIUn4/build.2E4/src/tests/Composer/Test/Downloader/XzDownloaderTest.php:80

2) Composer\Test\Downloader\ZipDownloaderTest::testErrorMessages
Failed asserting that 'Undefined index: file' contains "is not a zip archive".

/tmp/autopkgtest.brIUn4/build.2E4/src/tests/Composer/Test/Downloader/ZipDownloaderTest.php:99

3) Composer\Test\InstallerTest::testIntegration with data set "install-branch-alias-composer-repo.test" ('install-branch-alias-composer...o.test', 'Installing branch aliased pac...itory.', null, array(array(array('composer', 'file:///tmp/autopkgtest.brIUn...r-repo')), array('3.2.*@dev')), array(), array(), 'install', array(), null, null, 'Installing a/a (dev-foobar ab...ef0)\n', 0)
<warning>No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.</warning>
Loading composer repositories with package information

In ProxyManager.php line 90:
                                        
  [PHPUnit\Framework\Error\Notice (8)]  
  Undefined index: file                 

Full build and test log:
    https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-hirsute/hirsute/amd64/c/composer/20210126_225632_eecba@/log.gz

For additional context, Ubuntu's CI runs the testsuite with no internet access, which sometimes break casess tests that require it to operate.  I am wondering if this might be a factor here?

**Comment by bryceharrington** [comment]
At least for the third case, ProxyManager.php has the following code:

class ProxyManager
{
    private $fullProxy;
    [...]
    private function __construct()
    {
        $this->fullProxy = $this->safeProxy = array(
            'http' => null,
            'https' => null,
        );
        [...]

    public function getProxyForRequest($requestUrl)
    {
          [...]
          if ($this->hasProxy && $this->fullProxy[$scheme]) { /** <-- Line 90 fault here **/
            if ($this->noProxy($requestUrl)) {
                $formattedProxyUrl = 'excluded by no_proxy';
            } [...]

I am wondering if the issue here might be that something's falling back to a "file:///..." url, but safeProxy doesn't have 'file' defined, only 'http' and 'https' and thus the array access on line 90 fails?

**Comment by Seldaek** [comment]
I fixed the ProxyManager thing as that seemed definitely wrong. If it doesn't fix your other test failures please remove the try/catch from the tests so you can share a full stack trace of the exception.

**Comment by bryceharrington** [comment]
Thanks, I'll put this in and follow-up with a stack trace if there are remaining problems.
