### ISSUE TITLE
Duplicated .git suffix when cloning from repo

### ISSUE THREAD

**Issue by hcerveragarc** [composer/composer#9656]
Starting from version 2.0.9, our deployments fail when trying to download from source. The generated `git clone` command is adding ".git" suffix to the repository url, causing it to fail:

![Composer-double-git-suffix](https://user-images.githubusercontent.com/70745082/106247824-621d0580-6210-11eb-9265-f07b8535f521.png)

If I rollback to version 2.0.8, everything works as expected, with no extra ".git" suffix. 

Is this intended?

**Comment by Seldaek** [comment]
Nope, the fix to actually try to prevent this ended up causing it :D See https://github.com/composer/composer/commit/a20ee1a448337b8de157110a6cbe6da029a2c669#commitcomment-46502862 for details.

**Comment by hcerveragarc** [comment]
Thanks :)
