### ISSUE TITLE
Installer corrupt?

### ISSUE THREAD

**Issue by mitya33** [composer/composer#9659]
I'm new to Composer and am trying to install it on my Centos 7.6 CPanel-powered server. I've copied the below from the [download page](https://getcomposer.org/download/) and pasted it into the Terminal area of CPanel, while logged in as the root server:

```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
```

And I get "Installer corrupt".

![image](https://user-images.githubusercontent.com/30174698/106358245-e51e8880-6302-11eb-8abd-02d723ff9a27.png)

I've read [this thread](https://github.com/composer/composer/issues/5054), but the issue there seemed to be about fopen wrappers not enabled, which isn't the case for me.

I've also read [this thread](https://github.com/composer/composer/issues/5285) and tried the install code suggested in [this reply](https://github.com/composer/composer/issues/5285#issuecomment-217155196) but same result.

What am I doing wrong?

**Comment by Seldaek** [comment]
As fallback, you can use `php -r "copy('https://getcomposer.org/composer-stable.phar', 'composer.phar');"` which will simply download the phar file, then you can try to execute that with `php composer.phar diagnose`, or verify the sha256 signature of the phar yourself against the latest versions' hash (published below at https://getcomposer.org/download/).
