### ISSUE TITLE
Support placeholders in dist URLs

### ISSUE THREAD

**Issue by naderman** [composer/composer#9661]
composer.json dist URLs should support replacement of placeholders like the version number and normalized version, to allow People to reference external dist files without having to modify the composer.json for each release. Useful if you keep a composer.json in your git repository but need a build process for dist files. There is currently already support for this in mirror dist URLs (%package%, %version%, %reference%) so it should work the same for regular dist URLs.

e.g.

```
            "dist": {
                "type": "zip",
                "url": "https://example.com/custom-builds/%package%/%version%/%reference%.%type%",
                "reference": "916356edb5c30fa564d02de94bde51a9c0bb4469",
                "shasum": "",
                "mirrors": [
                    {
                        "url": "https://repo.packagist.com/packagist-conductors/dists/%package%/%version%/%reference%.%type%",
                        "preferred": true
                    }
                ]
            },

**Comment by stof** [comment]
Something to be checked: is the `reference` still guessed automatically based on the VCS commit even when other parts are configured explicitly ? Based on https://github.com/composer/composer/blob/4ade9bd96097992d3986c98199ef63e4348decc0/src/Composer/Repository/VcsRepository.php#L392-L397 I would say the answer is no.

Side note: having the `reference` as part of the `dist` and `src` configs also means it is duplicated, while it should not be different for both cases.
