### ISSUE TITLE
Provide ability to disable parallel downloads 

### ISSUE THREAD

**Issue by sanmai** [composer/composer#9671]
Currently (as of 2.0.9) there no documented way to toggle off or limit the level of parallelization Composer is taking while making downloads. 

I have to run Composer from behind a proxy, and when Composer tries to download all packages at once, the proxy goes haywire. 

As a workaround, for this particular environment I have to use Composer 1.x even though I would be happy to upgrade. If I could limit Composer say, to single thread of downloads, or otherwise emulating the level of activity of Composer 1.x, that'll be a great option to have.

**Comment by Seldaek** [comment]
I guess we can add an env var to make the max concurrent downloads configurable.
