### ISSUE TITLE
Exec command cannot be used to obtain help or version information of the supplied binary

### ISSUE THREAD

**Issue by aadmathijssen** [composer/composer#9675]
I prefer to use `composer exec foo` over `vendor/bin/foo` because this avoids specifying the vendor bin path (which might be different from `vendor/bin`). Options can also be specified (this requires the use of `--`): `composer exec foo -- --bar` vs `vendor/bin/foo --bar`. However, there are two special options for which this doesn't work

* `-h, --help`: this will always print the help message of the Composer exec command itself instead of that of the executed tool;
* `-V, --version`: this will always print the version information of Composer itself instead of that of the executed tool.

The reason seems to be that Symfony Console adds special handling in the [`\Symfony\Component\Console\Application::doRun`](https://github.com/symfony/console/blob/5.x/Application.php#L218-L239) method for these two options.

Do you think it would be possible to remove these special options in the Composer exec command when at least one argument is supplied?

**Comment by stof** [comment]
This will be solved in Composer 2.2 when upgrading symfony/console to a newer version

**Comment by Seldaek** [comment]
Yes, pretty sure there's another issue about this already, but anyway it'll happen implicitly when updating for 2.2, so no need to track this thus closing.

**Comment by aadmathijssen** [comment]
In the meantime, if you want to run a binary without explicitly specifying the vendor bin path, you can use the Composer config command to obtain it for you, and prepend the result to the name of binary:

```sh
$(composer config bin-dir)/foo --bar
```
