### ISSUE TITLE
Allow package names to be referenced with refactorable/statically analysable way

### ISSUE THREAD

**Issue by mvorisek** [composer/composer#9687]
Currently, when package is referenced, name/hardcoded string must be used. When package is renamed, there is no way for static analysers to detect it.

This is a feature request to generate constants of installed versions into `Composer\InstalledVersions` class.

Example:
```
...
class FilesystemRepository extends WritableArrayRepository
{
    public const PKG_COMPOSER_COMPOSER = 'composer/composer';
    public const PKG_SYMFONY_HTTP_FOUNDATION = 'symfony/http-foundation';

    protected $file;
    ...
```

**Comment by stof** [comment]
The list of packages depends on the project. Defining constants for them in Composer cannot be done, as any string (matching the regex for valid package names) can be passed as argument there. And defining constants only for installed packages would not help either, as you would have to check for constants to be defined before actually using them as the list would be dynamic. A dynamically generated list of constants is not statically analysable either.

Btw, your composer.json won't use constants either in the `require` section.

**Comment by mvorisek** [comment]
There is already a private `installed` property generated in that class.

I am thinking in this further and it would be even better to generate a namespaced class for each package like:
```
namespace Composer\InstalledVersion\Symfony;

use Composer\InstalledVersion;

class HttpFoundation implements InstalledVersion
{
    public function getVersion()
    {
    ....
}
```

> And defining constants only for installed packages would not help either, as you would have to check for constants to be defined before actually using them as the list would be dynamic. A dynamically generated list of constants is not statically analysable either.

Static analysers check code against installed deps, thus anything generated by composer install is statically analysable.

**Comment by stof** [comment]
`InstalledVersions` is not only about the `getVersion` method

**Comment by mvorisek** [comment]
of course, getters for all options...

**Comment by Seldaek** [comment]
If you look at https://getcomposer.org/doc/07-runtime.md#installed-versions

From the listed use cases:

- `Knowing whether package X (or virtual package) is present` => You can not rely on the class being there, as it may not be there and that'd be valid. So string seems fine.
- `Knowing whether package X is installed in version Y` => To take care of providers/replacers correctly, this requires a VersionParser and constraint, we could move this to a `Composer\InstalledVersions\Foo\Bar` class but I don't see much benefit to static analysis. I mean sure you get possibly validation of the package name.. but at the cost of a ton of classes and complexity added here, does not seem like the trade-off is worth it.
- `Knowing the version of package X` => Not a good idea as highlighted in the docs, except when self-referencing your own package, but then the static analysis benefits seem irrelevant here.

So all in all I am not very convinced by the benefits of this. Constants *perhaps* could be done but one class per package seems like a messy overhead.

**Comment by Seldaek** [comment]
Closing here as I don't really see the value add sorry :)
