### ISSUE TITLE
Set default PHP version when executing binaries

### ISSUE THREAD

**Issue by m-vo** [composer/composer#9707]
Over at Contao CMS we replaced our post install/update script handler with a binary to prevent autloading conflicts (compare to [#6738](https://github.com/composer/composer/issues/6738#issuecomment-347856605)). We're specifying the binary without a `@php vendor/bin/` prefix because we would need a `\` as path separator to work on Windows (compare [#6968](https://github.com/composer/composer/issues/6968#issuecomment-771035458)).

`composer.json` (excerpt):

```json
{
  "scripts": {
    "post-install-cmd": [
      "contao-setup"
    ],
  }
}
```

Our binary is a PHP executable that must run with the **same PHP version** Composer is running - or put differently: If someone with a default CLI PHP version of 7.4  executes `php8.0 composer run post-install-cmd` they expect the script to run with PHP 8 as well, however it would still execute under 7.4.

**Expected behavior**
```bash
$ php -v 
7.4

$ /usr/bin/php8.0 composer run post-install-cmd
(running under 8.0)
```

**Actual behavior**
```bash
$ /usr/bin/php8.0 composer run post-install-cmd
(running under 7.4)
```

Composer cannot know about the type of the binary but maybe there is a way around dynamically setting the default PHP executable. If I'm using the same example from above but use the `symfony` binary to execute it in different PHP versions this behaves as expected. So maybe we could use the same mechanic in Composer?

```bash
$ echo "8.0" > .php-version
$ symfony php -v
8.0

$ symfony composer run post-install-cmd
(running under 8.0)
```

The binaries being PHP executables is probably very common in the PHP world, so handling this special case is IMHO worth it. Either by solving the path separator issue and allowing something like `@php path/to/my/binary` or by dynamically setting the PHP version to the current executable for the child processes. Right now we're kinda trapped. :cry:

(Btw. this problem exists for all script types not only those that are executed as 'events'. Partly related to #9325.)

**Comment by Seldaek** [comment]
> We're specifying the binary without a @php vendor/bin/ prefix because we would need a \ as path separator to work on Windows

I could not reproduce this even in cmd.exe, but anyway I pushed something which I hope will fix it in https://github.com/composer/composer/commit/057006da4fbfab0241cdcdccce1ff676bedfcb63

So hopefully you can now use `@php path/to/bin`.

I'm looking at fixing https://github.com/composer/composer/issues/9325 too if possible though, but really it's safer IMO to target `@php vendor/foo/bar/bin` because that path is constant while the bin-dir may be changed by  the user.

**Comment by Seldaek** [comment]
See https://github.com/composer/composer/pull/9713

**Comment by m-vo** [comment]
Thanks a lot for looking into this, @Seldaek.

**Comment by fritzmg** [comment]
> I could not reproduce this even in cmd.exe, but anyway I pushed something which I hope will fix it in [057006d](https://github.com/composer/composer/commit/057006da4fbfab0241cdcdccce1ff676bedfcb63)

Interestingly, this works under Windows:

```json
{
    "scripts": {
        "post-install-cmd": [
            "@php path/to/bin"
        ]
    }
}
```

but this does not:

```json
{
    "scripts": {
        "post-install-cmd": [
            "path/to/bin"
        ]
    }
}
```
```
> composer run-script post-install-cmd

> path/to/bin
'path' is not recognized as an internal or external command,
operable program or batch file.
Script path/to/bin handling the post-install-cmd event returned with error code 1
```

This also does not work with the latest 1.x snapshot from https://getcomposer.org/download/ - or does this not yet contain the changes from [057006d](https://github.com/composer/composer/commit/057006da4fbfab0241cdcdccce1ff676bedfcb63)?

**Comment by Seldaek** [comment]
@fritzmg I did not fix this in 1.x, as it's kind of an edge case issue IMO. If 1.x support is absolutely needed I can take a look, but otherwise I rather not waste time backporting non-critical stuff.

It was however also not fixed in 2.x for the non-php-prefixed case. I just fixed that in https://github.com/composer/composer/commit/d855986c391745ac6e8bdd7b8c731815289e96ef

**Comment by fritzmg** [comment]
> @fritzmg I did not fix this in 1.x

Ah, sorry, yeah, I was not looking at the target branch for the commit.

> as it's kind of an edge case issue IMO.

Well, not for me 😁. In our case it was just a nuisance for me, as I was simply unable to execute any of [these scripts](https://github.com/contao/contao/blob/991282912ef0c590b92d25b67785463516a38890/composer.json#L253-L282) while developing for Contao and instead had to simply copy and paste each command manually. But only fixing it in Composer 2.x is perfectly fine for me.

**Comment by Seldaek** [comment]
Yeah I realize it can be annoying, but in the grand scale of things I mean it's a problem affecting only a very small portion of users and they should rather upgrade to v2 :)

Anyway I'll try and get a release out in a bit.

**Comment by Seldaek** [comment]
2.0.10 🚀 https://github.com/composer/composer/releases/tag/2.0.10
