### ISSUE TITLE
The awkward problems encountered when installing composer on windows！！

### ISSUE THREAD

**Issue by heihao9313** [composer/composer#9712]
I tried to install composer using Composer-Setup.exe on a windows computer, but the strange thing is that the process of detecting php is stuck
![image](https://user-images.githubusercontent.com/26619816/108797495-4534e180-75c6-11eb-9367-5e4ce3527b60.png)
After several kill processes, I was surprised to find that phpstorm opened an unknown file and entered debug. This is amazing! !
![image](https://user-images.githubusercontent.com/26619816/108797630-95ac3f00-75c6-11eb-9d60-6124c9d23e0f.png)
Although composer has been successfully installed, I would like to know the reason for entering debug？

**Comment by johnstevenson** [comment]
> After several kill processes, I was surprised to find that phpstorm opened an unknown file and entered debug. This is amazing! !

Indeed. Please supply a log file (as per the instructions at https://github.com/composer/windows-setup/issues/new). I'll take a guess that you are using Xdebug 3 ?

**Comment by heihao9313** [comment]
thank you for your reply [https://github.com/composer/windows-setup/issues/131](url)

**Comment by stof** [comment]
For reference, here is the working link: https://github.com/composer/windows-setup/issues/131 (the previous comment uses a markdown markup to have different link text and url, but fails at providing a working url)
