### ISSUE TITLE
Suggestion: Add color legend to `composer outdated`

### ISSUE THREAD

**Issue by ThomasLandauer** [composer/composer#9716]
I never understood the meaning of the colors yellow and red in the output of `composer outdated`. In https://github.com/composer/composer/issues/5447 it was suggested to switch red and yellow, but I also see the point of staying compatible with npm.

So here's a compromise to make everybody happy:
Just add a "legend" below the list of outdated packages:
> red: patch or minor update available
> yellow: major upgrade available

**Comment by mbrodala** [comment]
Notice that Yarn has a similar feature:

![image](https://user-images.githubusercontent.com/5037116/108964802-41639680-767c-11eb-9666-3100b8934140.png)

**Comment by mbrodala** [comment]
@Seldaek Thanks. :+1:
