### ISSUE TITLE
Do not use VCS repo when user downgrades to stable version after having dev version

### ISSUE THREAD

**Issue by ondrejmirtes** [composer/composer#9719]
If I use the following commands I'd expect `vendor/phpstan/phpstan` directory to NOT have `.git` directory, NOT have files that are excluded with `.gitattributes` etc.:

```
mkdir test && cd test
composer require phpstan/phpstan:dev-master
composer require phpstan/phpstan:0.12.78
ls -lA vendor/phpstan/phpstan
```

My main reason for this is that it seems it makes upgrading slower when the repo needs to fetch newer tags when upgrading to a newer version. It's slower to run `git fetch` and `checkout` instead of downloading a clean .zip from GitHub.

But having unwanted files in `vendor` also impacts user experience especially in case of monorepos - `phpstan/phpstan` repo includes sources for its website, Dockerfile etc. which can lead to the IDE confused by those files.

A side question - I think it should be possible to use `.zip` dist package even when the user requests `dev-master` and similar. What are the reasons why Composer chooses not to do it?

Thank you!

**Comment by mfn** [comment]
I though that the following config will take care of this:
```json
  "config": {
    "preferred-install": "dist",
  },
```

**Comment by stof** [comment]
See https://github.com/composer/composer/issues/9546 for the discussion about changing the default behavior in the future.

**Comment by ondrejmirtes** [comment]
@stof Cool, but to be clear, that's only about the side question, the steps referenced in the original post should still lead to not having the repo checked out in vendor I'd think.

**Comment by Seldaek** [comment]
@ondrejmirtes once https://github.com/composer/composer/pull/9603 is applied, the default of preferred-install changes to dist and as such your repro script will not leave a .git repo behind anymore.

In the meantime you can make sure to use `composer require phpstan/phpstan:dev-master --prefer-dist` or change preferred-install in your config.

Closing already as we have #9546 and #9603 tracking this already.

**Comment by stof** [comment]
@ondrejmirtes the behavior of composer when updating an installed package which was installed from source is to keep it installed from source (the ability to checkout a different commit while git would fetch only the delta is the reason why dev versions are installed from source by default today after all, and it avoids loosing potential commits done locally)
