### ISSUE TITLE
Composer 2.0.10 fails with fatal error on every command (Uncaught TypeError: Argument 3 passed to ...)

### ISSUE THREAD

**Issue by windaishi** [composer/composer#9721]
I updated to composer 2.0.10 this morning. After that I cannot run any composer command in my project anymore. Every commands fails with the error below.

Once I remove the `composer.lock` file and the `vendor` dir, I can run `composer install` again without error. After that, every command fails again. It seems like something is broken somewhere in the `vendor` dir.

Feel free to ask for more information, if you need more.

When I do a roll-back to 2.0.9 everything works fine again.

My `composer.json`:

```json
{
    "name": "shopware/development",
    "type": "project",
    "description": "A Shopware 6 skeleton to run integration tests.",
    "license": "MIT",
    "require": {
        "php": ">=7.2",
        "composer/package-versions-deprecated": "^1.8.0",
        "pickware/shopware-integration-test-plugin": "*",
        "shopware/platform": "6.3.1.*"
    },
    "require-dev": {
        "ext-tokenizer": "*",
        "ext-xmlwriter": "*",
        "bheller/images-generator": "^1.0.1",
        "fzaninotto/faker": "^1.8.0",
        "johnkary/phpunit-speedtrap": "^3.1.0",
        "league/flysystem-memory": "^1.0.2",
        "mbezhanov/faker-provider-collection": "^1.2.1",
        "phpunit/phpunit": "^8.4.0",
        "smalot/pdfparser": "^0.14.0",
        "symfony/browser-kit": "^4.4.4",
        "symfony/dependency-injection": "^4.4.4",
        "symfony/phpunit-bridge": "^4.4.4",
        "symfony/stopwatch": "^4.4.4",
        "symfony/var-dumper": "^4.4.4",
        "symfony/web-profiler-bundle": "^4.4.4"
    },
    "config": {
        "optimize-autoloader": true
    },
    "autoload": {
        "psr-4": {
            "Shopware\\Development\\": "src/"
        }
    },
    "repositories": [
        {
            "type": "path",
            "url": "../../plugins/*",
            "options": {
                "symlink": true
            }
        },
        {
            "type": "path",
            "url": "../../plugins-dev/*",
            "options": {
                "symlink": true
            }
        },
        {
            "type": "path",
            "url": "../../libraries/composer-packages/*",
            "options": {
                "symlink": true
            }
        },
        {
            "type": "path",
            "url": "../../bundles/*",
            "options": {
                "symlink": true
            }
        }
    ],
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-install-cmd": [
            "@remove-lock-file"
        ],
        "post-update-cmd": [
            "@remove-lock-file"
        ],
        "remove-lock-file": [
            "# Workaround as long as ocramius/package-versions is incompatible with composer config `lock: false`",
            "rm composer.lock"
        ]
    }
}
```

Output of `composer diagnose`:

_The command fails_

When I run this command: 

```
composer -vvv
```

I get the following output: 

```
Reading ./composer.json (/Users/manuelkress/Pickware/ShopwareNext/Plugins/shopware-plugins/shopware-projects/plugin-integration-test/composer.json)
Loading config file /Users/manuelkress/.composer/config.json
Loading config file /Users/manuelkress/.composer/auth.json
Loading config file ./composer.json (/Users/manuelkress/Pickware/ShopwareNext/Plugins/shopware-plugins/shopware-projects/plugin-integration-test/composer.json)
Checked CA file /usr/local/etc/openssl@1.1/cert.pem: valid
Executing command (/Users/manuelkress/Pickware/ShopwareNext/Plugins/shopware-plugins/shopware-projects/plugin-integration-test): git branch -a --no-color --no-abbrev -v
Reading /Users/manuelkress/.composer/composer.json
Loading config file /Users/manuelkress/.composer/config.json
Loading config file /Users/manuelkress/.composer/auth.json
Loading config file /Users/manuelkress/.composer/composer.json (/Users/manuelkress/.composer/composer.json)
Loading config file /Users/manuelkress/.composer/auth.json
Reading /Users/manuelkress/.composer/auth.json
Reading /Users/manuelkress/Pickware/ShopwareNext/Plugins/shopware-plugins/shopware-projects/plugin-integration-test/vendor/composer/installed.json
Reading /Users/manuelkress/.composer/vendor/composer/installed.json
Loading plugin PackageVersions\Installer
Loading plugin Pickware\ShopwarePlugins\DependencyLoader\DependencyLoaderComposerPlugin
Loading plugin PackageVersions\Installer_composer_tmp0 (installed globally)
Loading plugin Ergebnis\Composer\Normalize\NormalizePlugin (installed globally)
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Composer\Package\Locker::__construct() must be an instance of Composer\Repository\RepositoryManager, instance of Composer\Installer\InstallationManager given, called in phar:///usr/local/bin/composer/src/Composer/Factory.php on line 411 and defined in /Users/manuelkress/Pickware/ShopwareNext/Plugins/shopware-plugins/shopware-projects/plugin-integration-test/vendor/composer/composer/src/Composer/Package/Locker.php:54
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Factory.php(411): Composer\Package\Locker->__construct(Object(Composer\IO\ConsoleIO), Object(Composer\Json\JsonFile), Object(Composer\Installer\InstallationManager), '{\n    "name": "...', Object(Composer\Util\ProcessExecutor))
#1 phar:///usr/local/bin/composer/src/Composer/Factory.php(595): Composer\Factory->createComposer(Object(Composer\IO\ConsoleIO), Array, false)
#2 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(409): Composer\Factory::create(Object(Composer\IO\ConsoleIO), in /Users/manuelkress/Pickware/ShopwareNext/Plugins/shopware-plugins/shopware-projects/plugin-integration-test/vendor/composer/composer/src/Composer/Package/Locker.php on line 54

Fatal error: Uncaught TypeError: Argument 3 passed to Composer\Package\Locker::__construct() must be an instance of Composer\Repository\RepositoryManager, instance of Composer\Installer\InstallationManager given, called in phar:///usr/local/bin/composer/src/Composer/Factory.php on line 411 and defined in /Users/manuelkress/Pickware/ShopwareNext/Plugins/shopware-plugins/shopware-projects/plugin-integration-test/vendor/composer/composer/src/Composer/Package/Locker.php:54
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Factory.php(411): Composer\Package\Locker->__construct(Object(Composer\IO\ConsoleIO), Object(Composer\Json\JsonFile), Object(Composer\Installer\InstallationManager), '{\n    "name": "...', Object(Composer\Util\ProcessExecutor))
#1 phar:///usr/local/bin/composer/src/Composer/Factory.php(595): Composer\Factory->createComposer(Object(Composer\IO\ConsoleIO), Array, false)
#2 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(409): Composer\Factory::create(Object(Composer\IO\ConsoleIO), in /Users/manuelkress/Pickware/ShopwareNext/Plugins/shopware-plugins/shopware-projects/plugin-integration-test/vendor/composer/composer/src/Composer/Package/Locker.php on line 54
```

**Comment by stof** [comment]
do you have `composer/composer` in your vendor folder ?

**Comment by windaishi** [comment]
Yes, I do:
![image](https://user-images.githubusercontent.com/6232639/108982857-8a244b00-768e-11eb-9d91-c1417d0dcb9d.png)

**Comment by stof** [comment]
I suspect that this might be related to having different versions of composer in `vendor/composer/composer` and in the phar, and a mix of both codebases being loaded.

**Comment by windaishi** [comment]
This actually might be the case. In `vendor/composer/composer` is composer `1.10.10`.
Unfortunately we cannot update
```
11:14 $ composer why composer/composer
pickware/shopware-plugins-dependency-loader  2.3.1    requires  composer/composer (^1.9.1 || ^2.0.0)
shopware/platform                            6.3.1.1  requires  composer/composer (1.10.10)
```
`shopware/core` strictly requires `composer/composer (1.10.10)`

Why did it work with 2.0.9 though?

**Comment by stof** [comment]
why is `pickware/shopware-plugins-dependency-loader` requiring `composer/composer` ? Composer plugins should be requiring `composer-plugin-api` instead, as they get loaded in the composer process.

> Why did it work with 2.0.9 though?

Composer 2.10.0 made some changes to the registration of autoloaders when loading plugins, which might have caused a change in regards to which of the 2 class definitions gets loaded.

**Comment by windaishi** [comment]
> why is `pickware/shopware-plugins-dependency-loader` requiring `composer/composer` ?
Well, it's complicated. It isn't just a composer-plugin. It handles class-autoloading for plugins in Shopware. Since plugin do not get required in the composer.json there, each plugin has to do its own autoloading. Therefore `pickware/shopware-plugins-dependency-loader` instanciates its own composer autoloader and appends it.

>Composer 2.10.0 made some changes to the registration of autoloaders when loading plugins, which might have caused a change in regards to which of the 2 class definitions gets loaded.

Isn't is a breaking change then?

**Comment by stof** [comment]
@windaishi but the `Composer\Autoload\ClassLoader` class is available at runtime already as Composer automatically copies it in the vendor folder (that's the only runtime API in Composer 1.x). You don't need to depend on `composer/composer` to use it.

**Comment by stof** [comment]
> Isn't is a breaking change then?

it was a bugfix for other issues. I guess the case of a composer plugin having a dependency on an older `composer/composer` was not taken into account when evaluating the solution.

**Comment by windaishi** [comment]
> @windaishi but the Composer\Autoload\ClassLoader class is available at runtime already as Composer automatically copies it in the vendor folder (that's the only runtime API in Composer 1.x). You don't need to depend on composer/composer to use it.

Okay, thank you. I will try to remove the dependency and report it here.

**Comment by doganoo** [comment]
@stof as far as I understand the problem relates to composer/composer as a dependency (not dev). I do not have any dependencies to composer/composer but have still the same errors as @windaishi 

![image](https://user-images.githubusercontent.com/6998611/108995128-f1e19280-769c-11eb-810f-bc620ca13b1d.png)

removing composer.lock and vendor did also not help

**Comment by ihor-sviziev** [comment]
Feels like we have the same issue in other projects as well https://github.com/composer/composer/issues/9717

**Comment by windaishi** [comment]
I actually could resolve my issue with the help of @stof 
But the problem was not, that my composer-plugin required `composer/composer`, but it was requiring `shopware/core` which again was requiring `composer/composer`.
So the problem is neither that the plugin is requiring `composer/composer` nor that `composer/composer` v1.10.10 is installed in the project but that the composer-plugin `pickware/shopware-plugins-dependency-loader` is requiring `shopware/core` with again is requiring `composer/composer` v1.10.10.

I luckily could remove this dependency because it wasn't necessary in by composer plugin. But it may still be a general issue.

**Comment by stof** [comment]
@windaishi when loading a composer plugin, transitive dependencies are indeed also loaded, not only direct dependencies.

**Comment by matweew** [comment]
Temporary solution: `composer self-update 2.0.9`

**Comment by doganoo** [comment]
@matweew also this was not possible as once you update you will permanently get the error above. The only solution I see is to download composer manually.

**Comment by windaishi** [comment]
> @matweew also this was not possible as once you update you will permanently get the error above. The only solution I see is to download composer manually.
You can do the rollback if you execute the command `composer self-update 2.0.9` in a directory without a `composer.json`.

**Comment by windaishi** [comment]
@stof
> @windaishi when loading a composer plugin, transitive dependencies are indeed also loaded, not only direct dependencies.

I am not very deep in the dependency loading of the composer plugins but it actually sound weird to me that when `composer/composer` is required directly, the plugin works, if it is required as a transitive dependency, it doesn't.

So this works: 
```json
    "require": {
        "composer-plugin-api": "^1.0.0 || ^2.0.0",
        "composer/composer": "^1.9.1 || ^2.0.0"
    }
```


This doesn't
```json
    "require": {
        "composer-plugin-api": "^1.0.0 || ^2.0.0",
        "composer/composer": "^1.9.1 || ^2.0.0",
        "shopware/core": "6.3.* >= 6.3.1.0"
    }
```

(Remember that `shopware/core` itself requires `composer/composer`)

**Comment by stof** [comment]
@windaishi the difference is that `shopware/core` forces to install composer 1.x. With your first composer.json, the 2.x version would be installed in the vendor folder. So even if the code gets loaded from there rather than the phar, it is the right codebase.

**Comment by stof** [comment]
@Seldaek should the autoloading registration of the plugin manager make a special case to never collect `composer/composer` (and maybe also `composer/semver)` from the vendor folder, ensuring that the code from the running composer gets used ?

**Comment by windaishi** [comment]
@stof
> With your first composer.json, the 2.x version would be installed in the vendor folder. 

I posted a cut out of the `composer.json` of my composer plugin which is NOT the root composer.json
The root `composer.json` is still requiring `shopware/core` which will force to use `composer/composer` v1.10.10.

So in both cases composer/composer v1.10.10 will end up in the vendor dir.

**Comment by stof** [comment]
@windaishi but during plugin loading, only the dependency tree of plugins gets registered in the temporary autoloader, not the whole vendor folder.

**Comment by windaishi** [comment]
@stof
But this `composer.json` is still working:
```
    "require": {
        "composer-plugin-api": "^1.0.0 || ^2.0.0",
        "composer/composer": "1.10.10"
    },
```
Even though it forces to use 1.10.10 directly.

**Comment by aadmathijssen** [comment]
Hi @windaishi, can you please update the issue title such that it mentions Shopware 6? This makes it easier to disintinguish this issue with similar regressions with Composer 2.0.10; currently [Magento 2.4.2](!9717) and [Flex < 1.12.2](!9722). Thanks!

**Comment by Seldaek** [comment]
Ok Composer 2.0.11 is out and should fix this regression, sorry for the trouble.

@stof we can't simply exclude composer/composer, https://github.com/composer-unused/composer-unused/issues/159 shows this can cause issues with any of Composer's dependencies, so I rolled back the whole autoloader-prepending change.

**Comment by windaishi** [comment]
No problem. Thanks for the fast fix. 🙇
