### ISSUE TITLE
composer 2 no longer lists patches in composer.lock file

### ISSUE THREAD

**Issue by mlncn** [composer/composer#9725]
Patches are applied, but they aren't mentioned in subsequent composer updates nor in the composer.lock file.  It's a tad disconcerting.  And is it just me?

**Comment by Seldaek** [comment]
Maybe you want to submit this to https://github.com/cweagans/composer-patches or whatever plugin you use for patches.. This is not native Composer functionality and we are not providing support for it.

**Comment by mlncn** [comment]
Oh, of course!

Already an issue there:  https://github.com/cweagans/composer-patches/issues/338

Thanks!
