### ISSUE TITLE
Invoking vendored script "phpunit" through "composer exec" on different versions of PHP

### ISSUE THREAD

**Issue by amotl** [composer/composer#9726]
Dear @Seldaek, @naderman and contributors,

thanks a stack for conceiving and maintaining Composer.

## Introduction
We just ran into an issue we wanted to share with you. It is related to running `phpunit` (or other vendored scripts) through `composer exec` against different versions of PHP, all on macOS installed through Homebrew. Through `composer self-update`, we have made sure that we are using the most recent version `2.0.11`.

## Observations
So, I have both versions of PHP7 and PHP8 on my machine, installed using `brew install php@7.3 php@8.0`. Using `brew-php-switcher 7.3`, the currently selected version of PHP is 7.3.27:
```sh
$ php --version
PHP 7.3.27 (cli) (built: Feb  4 2021 12:13:46) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v3.0.3, Copyright (c) 2002-2021, by Derick Rethans
    with Zend OPcache v7.3.27, Copyright (c) 1999-2018, by Zend Technologies
```

Now, in order to add PHP8 compatibility to the `crate-pdo` package on behalf of https://github.com/crate/crate-pdo/pull/116, we need to run tests through `phpunit` on different versions of PHP and then merge the coverage reports using `phpunit-merger`.

In order to do that, we created a small program called [`php-multicover.sh`](https://gist.github.com/amotl/964f21cf54fbdc0edf3efa15473324cb) in order to run `phpunit` on both PHP7 and PHP8. However, it turns out that PHP7 is used in both cases.

## Side looks
That is specifically astonishing as the `composer diagnose` command works perfectly in both cases when prefixing the `composer` command with the PHP interpreter, only `composer exec` does not.

#### PHP7
```sh
$ /usr/local/Cellar/php@7.3/7.3.27/bin/php $(which composer) diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.11
PHP version: 7.3.27
PHP binary path: /usr/local/Cellar/php@7.3/7.3.27/bin/php
OpenSSL version: OpenSSL 1.1.1i  8 Dec 2020
cURL version: 7.75.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1j
zip: extension present, unzip present
```

#### PHP8
```sh
$ /usr/local/Cellar/php/8.0.2/bin/php $(which composer) diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.11
PHP version: 8.0.2
PHP binary path: /usr/local/Cellar/php/8.0.2/bin/php
OpenSSL version: OpenSSL 1.1.1i  8 Dec 2020
cURL version: 7.75.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1j
zip: extension present, unzip present
```

## Thoughts and further attempts
Apparently, Composer will run the script through `composer exec` by just using the shebang of `./vendor/bin/phpunit`, which is `#!/usr/bin/env php`, so it will obviously invoke the current/default PHP environment, which happens to be PHP7 in my case, regardless of being run through the designated interpreter.

Recognizing #7850 and #7857, we already tried to define `PHP_BINARY` beforehand like
```sh
export PHP_BINARY=/usr/local/Cellar/php/8.0.2/bin/php
```
but there was no joy.

## Outlook
So, it would be very nice to see if that could work in any way:
```sh
# Running tests with coverage on PHP7
/usr/local/Cellar/php@7.3/7.3.27/bin/php /usr/local/bin/composer exec 'phpunit --coverage-php build/multicover/reports/clover-php7.php'

# Running tests with coverage on PHP8
/usr/local/Cellar/php/8.0.2/bin/php /usr/local/bin/composer exec 'phpunit --coverage-php build/multicover/reports/clover-php8.php'
```

Thank you very much in advance for looking into that.

With kind regards,
Andreas.

**Comment by Seldaek** [comment]
We did improve this slightly in 2.0.10 so that you can now use `composer exec '@php vendor/bin/phpunit ...'` and the `@php` there will make sure things run with the same PHP process that composer runs with.

Doing more than that would mean resolving which binary you are calling from the $PATH, and checking if that's a php file, and then overriding which PHP it wants in its shebang with the current PHP process, and I'm honestly not sure if that'd be a good thing or if it'd cause issues for others..

**Comment by stof** [comment]
The `phpunit` script has a shebang of `/usr/bin/env php`. So this depends on which php executable is in your PATH. Executing `/usr/local/Cellar/php@7.3/7.3.27/bin/php /usr/local/bin/composer` or `/usr/local/Cellar/php/8.0.2/bin/php /usr/local/bin/composer` does not change the PATH.

If you want to execute something with the php executable used to run composer itself, `composer exec` supports the special `@php` command: `composer exec '@php vendor/bin/phpunit` (not that this needs to use `vendor/bin/phpunit` and not `phpunit` as the argument of the php executable is a path to a file, not something resolved in `PATH`)

**Comment by stof** [comment]
@Seldaek a better alternative might be to generate a `php` script forwarding to the right PHP executable, and making sure that this script is in the first folder of the PATH (which is currently `vendor/bin/` in `composer exec` so that it is the one used by `/usr/bin/env php`.
This would avoid the need to alter the scripts.

**Comment by Seldaek** [comment]
You don't need to alter the script? You can call it with `$PHP_BINARY path/to/script`.. I am not sure I understand what you are suggesting or what it'd help with.

**Comment by amotl** [comment]
Hi again,

thank you very much for your quick and excellent answers.

> you can now use `composer exec '@php vendor/bin/phpunit ...'`

I see, but that would render the feature to run vendored scripts through `composer exec` without having to add the `vendor/bin`-prefix defunct, right? I was initially trying to get around this prefixing operation as it seemed convenient to use a Composer feature for that. Then, I decided to report my findings here.

> You can call it with `$PHP_BINARY path/to/script..`

I completely understand the situation now and also believe that we will be better off not invoking those scripts through `composer` at all and will just define shortcut paths to the respective scripts like
```sh
phpunit="$(pwd)/vendor/bin/phpunit"
phpunit_merger="$(pwd)/vendor/bin/phpunit-merger"
```

and then execute them directly on the PHP interpreter as suggested by @Seldaek. I've amended the gist [1] accordingly. I believe - given the current situation - this is more straightforward, but I will be happy to learn if you believe we should be doing it differently.

Thank you very much again, keep up the spirit and with kind regards,
Andreas.

[1] https://gist.github.com/amotl/964f21cf54fbdc0edf3efa15473324cb

**Comment by Seldaek** [comment]
Yup that looks better to me. The vendor/bin/ prefix can be simplified by setting `composer config bin-dir bin` for example so you'd get this in `bin/phpunit`. Slightly shorter but same thing ultimately.

**Comment by amotl** [comment]
Thanks Jordi.

P.S.: Just updated [1] once more to include full rationale and setup documentation. So if you bump into people needing such a thing, feel free to share it.

[1] https://gist.github.com/amotl/964f21cf54fbdc0edf3efa15473324cb

**Comment by stof** [comment]
@Seldaek in my proposal, you don't need to alter the executed command either. The idea would be that `phpunit` is the executed command (which is resolved as `.../vendor/bin/phpunit` based on the PATH. then, this script's shebang tell the shell to run it with `php` resolved from the PATH, and that resolves as `.../vendor/composer/tmp-bin/php` (or whatever the name of the folder used to store that), with `vendor/composer/tmp-bin/php` being a bash script generated as `/usr/local/Cellar/php@7.3/7.3.27/bin/php $@` when running `/usr/local/Cellar/php@7.3/7.3.27/bin/php composer exec`
And this would also work on Windows with a `php.bat` file generated in the same folder

**Comment by Seldaek** [comment]
I don't really understand how this helps. Who calls this tmp-bin/php? What benefit does it have over simply executing `/usr/local/Cellar/php@7.3/7.3.27/bin/php ...` directly? 

One thing I think we could improve is that when doing `@php phpunit` we'd check if `phpunit` is a valid path.. if not then it'll fail so we should rather check if it is found in PATH, and if so we resolve it and execute `$PHP_BINARY path/to/phpunit`, so one could combine `@php` to ensure same-php-as-composer with the shorter paths of `composer exec`.

**Comment by Seldaek** [comment]
> One thing I think we could improve is that when doing @php phpunit we'd check if phpunit is a valid path.. if not then it'll fail so we should rather check if it is found in PATH, and if so we resolve it and execute $PHP_BINARY path/to/phpunit, so one could combine @php to ensure same-php-as-composer with the shorter paths of composer exec.

Did this in https://github.com/composer/composer/commit/bcd862c3dcc6c834bcd2a52b9b40fc1605adc057 which will ship in Composer 2.1 (you can try with `composer self-update --snapshot`)

**Comment by stof** [comment]
@Seldaek the `tmp-bin/php` would be called by the shell when resolving the phpunit `/usr/bin/env php` shebang when running `composer exec 'phpunit'`. That's the whole point of the idea: automatically make `/usr/bin/env php` resolve to the `PHP_BINARY` of the composer process for sub-processes launched by `composer exec` (the `tmp-bin/php` file would also be *created* by `composer exec` to set the right php path in it)

**Comment by Seldaek** [comment]
Ok now I get what you were saying but I think the solution I implemented there is sufficient and possibly better as it doesn't require writing anything to the filesystem.
