### ISSUE TITLE
[RFC] Split the metadata minifier util in its own package

### ISSUE THREAD

**Issue by stof** [composer/composer#9727]
The recommended way to consume package metadata from packagist is to load them from the v2 metadata. But this requires being able to expand the minified metadata.
As the MetadataMinifier is part of `composer/composer`, this forces packages doing such things to depend on `composer/composer` to access it, which can lead to weird issues when composer is in the vendor folder (see the broken 2.10 release for instance).

As this class is meant to be useful for other consumers that the composer CLI, I think it would be worth extracting it to a separate package, as done for `composer/semver` already.

**Comment by Seldaek** [comment]
Yup it probably makes sense to make it available standalone.
