### ISSUE TITLE
Aliased packages not being installed with composer v2

### ISSUE THREAD

**Issue by jon-wyatt-gradwell** [composer/composer#9728]
My `composer.json`:

Note: I've had to alter a few of the strings/names to not expose internals, but the structure and everything involved is the same.

```json
{
	"name": "us/db",
	"description": "Our component",
	"keywords": [
		"component"
	],
	"type": "library",
	"repositories": [
		{
			"type": "composer",
			"url": "https://our.satis.server/"
		}
	],
	"minimum-stability": "dev",
	"prefer-stable": true,
	"require": {
		"ext-pdo": "*",
		"us/config": "dev-custom-branch as 1.4",
		"us/debug": "^3.0",
		"us/log": "^1.2",
		"php": ">=5.6.0"
	},
	"require-dev": {
		"mockery/mockery": "^1",
		"phpunit/phpunit": "^5"
	},
	"autoload": {
		"psr-0": {
			"Namespace": "src/php/"
		}
	},
	"autoload-dev": {
		"psr-0": {
			"Namespace": "tests/"
		}
	}
}

```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: <redacted>
Dev Public Key Fingerprint: <redacted>
OK
Checking composer version: OK
Composer version: 2.0.11
PHP version: 7.0.33
PHP binary path: /usr/local/Cellar/php@7.0/7.0.33/bin/php
OpenSSL version: OpenSSL 1.0.2r  26 Feb 2019
cURL version: 7.73.0 libz 1.2.11 ssl OpenSSL/1.1.1h
zip: extension present, unzip present
```

When I run this command:

```
composer update -vvv
```

I get the following output: 

```
Reading ./composer.json (/Users/me/us_DB/composer.json)
Loading config file /Users/me/.composer/auth.json
Loading config file ./composer.json (/Users/me/us_DB/composer.json)
Checked CA file /private/etc/ssl/cert.pem: valid
Executing command (/Users/me/us_DB): git branch -a --no-color --no-abbrev -v
Executing command (/Users/me/us_DB): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (/Users/me/us_DB): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (/Users/me/us_DB): hg branch
Executing command (CWD): hg branches
Executing command (CWD): hg bookmarks
Failed to initialize global composer: Composer could not find the config file: /Users/me/.composer/composer.json

Reading /Users/me/us_DB/vendor/composer/installed.json
Running 2.0.11 (2021-02-24 14:57:23) with PHP 7.0.33 on Darwin / 19.6.0
Reading ./composer.lock (/Users/me/us_DB/composer.lock)
Loading composer repositories with package information
Downloading https://our.satis.server/packages.json
[200] https://our.satis.server/packages.json
Writing /Users/me/.composer/cache/repo/https---our.satis.server/packages.json into cache
Reading /Users/me/.composer/cache/repo/https---our.satis.server/include-all$30dc8575cb5b26a2b706536dd27ce4e6cb4cccdf.json from cache
Updating dependencies
Generating rules
Resolving dependencies through SAT
Looking at all rules.
Something's changed, looking at all rules again (pass #2)
Dependency resolution completed in 0.002 seconds
Analyzed 318 packages to resolve dependencies
Analyzed 660 rules to resolve dependencies
Nothing to modify in lock file
Generating rules
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.000 seconds
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 0 updates, 0 removals
  - Marking us/config (1.4) as installed, alias of us/config (dev-custom-branch d38b85ce9d70)
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
```
The folder vendor/us/config is created, but is empty. None of the files are downloaded/installed. 

And I expected this to happen:
The files in the aliased branch should be installed as expected.

Reverting to composer v1 works as expected.
Have tried setting `canonical: false` in the repository config section, but did not fix the issue.

**Comment by stof** [comment]
Aliases have no impact on the downloading step, neither on v1 nor on v2 AFAIK. So I suspect that this is not the root cause. And without a reproducable scenario, I don't see what others can do.

**Comment by jon-wyatt-gradwell** [comment]
I'm not sure what you were expecting? This is the issue I am having. It's a big issue. These are the details for how that issue is produced. It is 100% reproducible/consistent for me. And I am going to hazard a guess that others doing the same thing with their own branches will have the same issue. If they don't, well, that's also interesting to know. If you require more information, just ask for it.

**Comment by stof** [comment]
no, the report is full of non-existent package names with a non-existent Satis package. this does **not** allow us to reproduce the issue to debug what is happening in composer. If I run `composer update -vv`, I will only get errors about things not existing.

**Comment by jon-wyatt-gradwell** [comment]
Even if I gave you the package names, it wouldn't be of any use to you. The packages are hosted on our internal Satis server. You wouldn't be able to access them. 
If there isn't a general issue around aliases, it is possible/plausible the the Satis server is the cause? Does it need to be updated to work properly when serving to composer v2 clients?

**Comment by stof** [comment]
well, the metadata exposed by Satis could be the cause of it.
And if they are not, you should be able to reproduce that with only public packages instead.

**Comment by jon-wyatt-gradwell** [comment]
Attempting this with a public package (I tried "mockery/mockery": "0.9.x-dev as 1.0.0") seemed to install as expected. So perhaps it is an issue when using Satis. Is there any I can need/need to do myself to remedy this? Or is it simply a case of waiting for a newer Satis release that fully supports composer 2?

**Comment by stof** [comment]
are you using the master branch of satis or a years old tag ?

**Comment by jon-wyatt-gradwell** [comment]
"This Composer repository is powered by Satis 1.0.0"

Which appears to be the latest release according to https://github.com/composer/satis/releases

**Comment by stof** [comment]
And this is also a totally outdated version:
![image](https://user-images.githubusercontent.com/439401/109194262-892c1000-7799-11eb-9c40-fd37aa426687.png)

Satis is not tagging releases anymore.

**Comment by jon-wyatt-gradwell** [comment]
I see. Next step then, I'll see if I can get it updated and re-verify the issue. Won't be a today job though. Will post again when done.

**Comment by jon-wyatt-gradwell** [comment]
Alas updating to the latest Satis commit (1d9a21ff0252f48eb9fc20f969b2615eb70a34b7) did not resolve the issue. Same behaviour as before. Not sure what else I can try at this point. I can see https://github.com/composer/satis/issues/594 is open, but no idea if completion of it would help at all.

**Comment by jon-wyatt-gradwell** [comment]
Interestingly I can see it saying
`- Syncing mockery/mockery (0.9.x-dev f356e06) into cache`
when aliased, but no such 'syncing' line for the internal package.

Another anomaly is that the output for the installation line misses a new line character for the aliased internal package, but not for any other package, which all correctly new line after each (even mockery). Like so:
```
- Installing gradwell/config (dev-f/201910-bs-cp-2565-ini-scanner-raw d38b85ce9d70):   - Installing psr/log (1.1.3): Extracting archive
- Installing monolog/monolog (1.10.0): Extracting archive
- Installing us/debug (3.0.0): Extracting archive
- Installing us/log (1.2.4): Extracting archive
- Installing hamcrest/hamcrest-php (v1.2.2): Extracting archive
- Installing mockery/mockery (0.9.x-dev f356e06): Cloning f356e061d8 from cache
- Installing symfony/polyfill-ctype (v1.8.0): Extracting archive
```

**Comment by Seldaek** [comment]
Sorry but I won't spend time debugging Satis at this point, I haven't looked at that code in years.. If you like private package hosting that works I can only point you to [Private Packagist](https://packagist.com) and hope you give it a shot. It's up to date for Composer 2 and quite easy to setup with automatic sync. Note that we do offer Composer support as part of the subscription too as a bonus.

If you can find a way to reproduce this without your satis repo I'm happy to have a look though.

**Comment by dlowhorn** [comment]
Disclaimer:  I'm a long-time user of composer at a very high level.  I've never tracked through its internals, so forgive me if I'm stepping into a discussion here without understanding everything fully.

### Steps to Reproduce

**Succeeds With Composer 1.10.21:**

```
mkdir tmp && cd tmp
composer self-update --1
composer clear-cache
composer require tan5en5/codeigniter-debugbar:dev-master --dev -vvv
```

Install output snippet:

```
  - Installing tan5en5/codeigniter-debugbar (dev-master de036b4): 
    Cloning to cache at '/home/daniel/.cache/composer/vcs/https---github.com-Tan5en5-codeigniter-debugbar.git/'
Executing command (CWD): git clone --mirror 'https://github.com/Tan5en5/codeigniter-debugbar.git' '/home/daniel/.cache/composer/vcs/https---github.com-Tan5en5-codeigniter-debugbar.git/'
Executing command (/home/daniel/.cache/composer/vcs/https---github.com-Tan5en5-codeigniter-debugbar.git/): git rev-parse --git-dir
Executing command (/home/daniel/.cache/composer/vcs/https---github.com-Tan5en5-codeigniter-debugbar.git/): git rev-parse --quiet --verify 'de036b46c06a1910f5f3f5f88df5cc4706f2f728^{commit}'
Cloning de036b46c06a1910f5f3f5f88df5cc4706f2f728 from cache
Executing command (CWD): git clone --no-checkout '/home/daniel/.cache/composer/vcs/https---github.com-Tan5en5-codeigniter-debugbar.git/' 'application/third_party/codeigniter-debugbar/' --dissociate --reference '/home/daniel/.cache/composer/vcs/https---github.com-Tan5en5-codeigniter-debugbar.git/' && cd 'application/third_party/codeigniter-debugbar/' && git remote set-url origin 'https://github.com/Tan5en5/codeigniter-debugbar.git' && git remote add composer 'https://github.com/Tan5en5/codeigniter-debugbar.git'
Executing command (application/third_party/codeigniter-debugbar/): git remote set-url --push origin 'git@github.com:Tan5en5/codeigniter-debugbar.git'
Executing command (application/third_party/codeigniter-debugbar/): git branch -r
Executing command (application/third_party/codeigniter-debugbar/): git checkout 'master' --
Executing command (application/third_party/codeigniter-debugbar/): git reset --hard 'de036b46c06a1910f5f3f5f88df5cc4706f2f728' --
    REASON: Required by the root package: Install command rule (install tan5en5/codeigniter-debugbar dev-master)

symfony/var-dumper suggests installing symfony/console (To use the ServerDumpCommand and/or the bin/var-dump-server script)
maximebf/debugbar suggests installing kriswallsmith/assetic (The best way to manage assets)
maximebf/debugbar suggests installing monolog/monolog (Log using Monolog)
maximebf/debugbar suggests installing predis/predis (Redis storage)
Reading /home/daniel/tmp/t/vendor/composer/installed.json
```

Result:  application/third_party/codeigniter-debugbar path exists with the contents of the tan5en5/codeigniter-debugbar package



**Fails With Composer 2.0.12:**

```
mkdir tmp && cd tmp
composer self-update --2
composer clear-cache
composer require tan5en5/codeigniter-debugbar:dev-master --dev -vvv
```

Install output snippet:

```
Executing command (/home/daniel/.cache/composer/vcs/https---github.com-Tan5en5-codeigniter-debugbar.git/): git rev-parse --git-dir
Executing command (/home/daniel/.cache/composer/vcs/https---github.com-Tan5en5-codeigniter-debugbar.git/): git rev-parse --quiet --verify 'de036b46c06a1910f5f3f5f88df5cc4706f2f728^{commit}'
  - Marking tan5en5/codeigniter-debugbar (9999999-dev de036b4) as installed, alias of tan5en5/codeigniter-debugbar (dev-master de036b4)
Executing command (CWD): rm -rf '/home/daniel/tmp/t/vendor/psr/log'
Executing command (CWD): rm -rf '/home/daniel/tmp/t/vendor/composer/5bb0a4f0'
Executing command (CWD): rm -rf '/home/daniel/tmp/t/vendor/symfony/polyfill-php80'
Executing command (CWD): rm -rf '/home/daniel/tmp/t/vendor/composer/5f8a7878'
Executing command (CWD): rm -rf '/home/daniel/tmp/t/vendor/symfony/polyfill-mbstring'
Executing command (CWD): rm -rf '/home/daniel/tmp/t/vendor/composer/11036bbf'
Executing command (CWD): rm -rf '/home/daniel/tmp/t/vendor/symfony/var-dumper'
Executing command (CWD): rm -rf '/home/daniel/tmp/t/vendor/composer/b72c84cb'
Executing command (CWD): rm -rf '/home/daniel/tmp/t/vendor/maximebf/debugbar'
Executing command (CWD): rm -rf '/home/daniel/tmp/t/vendor/composer/f8c87ab3'
Downloading https://packagist.org/downloads/
```

Result:  application/third_party/codeigniter-debugbar path exists but is empty

Notice how with v1 it actually installs the tan5en5/codeigniter-debugbar package, but with v2 it just marks it as installed? 


Yes, these are old packages, but it shows what I think is OP's issue:  nothing is downloaded for tan5en5/codeigniter-debugbar when using composer v2.

The compwright/codeigniter-installers package has this in its composer.json:

**"composer/composer": "1.0.*@dev"**

Could that be causing a problem?

**Comment by Seldaek** [comment]
@dlowhorn yeah your last guest is definitely the problem. This is so old that it still uses the `composer-installer` type, instead of the "newer" `composer-plugin` type, which would have forced the package to declare its requirement on the composer-plugin-api. Since the package does not require the plugin-api ^1, it does not warn you about being incompatible, so it does get loaded but the code is probably too old to function with Composer 2. Seeing as it hasn't been updated in 9years that is not surprising :)

I doubt this is related to the other issue being reported here though, even though the symptoms might be similar. I think we probably should error or at least output a warning for `composer-installer` packages in v2 though instead of letting them silently run in a probably-corrupt way. I'll get that done at least, but that won't help you resolve this, either the installer needs to be updated, or you need to stay on Composer 1.x for this project. I'd suggest shipping a composer.phar in the project repo which can be used to install that old project alone, and have a Composer 2 installed globally on your machine for the rest.
