### ISSUE TITLE
[QUESTION] composer plugin execution sequence

### ISSUE THREAD

**Issue by davidverholen** [composer/composer#9736]
Hi, I'm not sure, if an issue is the right place for this, but I thought it'd be at least better, then to bother anyone per DM somewhere

**Question**:
Is there a way, to force a plugin execution order on project level, when two composer plugins are executed on the same event?

**Our Case**:
So basically, Magento2 defines autoload files in the composer.json, that are not there (yet)
The files are copied from a composer package into the project root on POST_INSTALL_CMD and POST_UPDATE_CMD

Now there is another plugin (in our case grumphp) listening on that events, and for reasons, it seems, that since the last M2 patch (there have been changes, to make the composer plugin composer 2 compatible) it's executed before the files are copied by the magento composer plugin

This of course leads to an autloading error, that the file cannot be found.

So far I did not find anything about that issue, so it might be only our problem. But if I'm right with my assumption, this could of course then affect many more M2 projects

**Comment by apfelbox** [comment]
You can define priorities on your listeners, see here for details: https://github.com/composer/composer/blob/master/src/Composer/EventDispatcher/EventSubscriberInterface.php#L29-L47

For your listener to run after another listener, you just need to have a lower priority.

**Comment by davidverholen** [comment]
@apfelbox a thx, that's already great input. But that means, the plugin provider needs to take care of that and we cannot override that on project level, right? So if both define the priority 0, it's purely random

**Comment by apfelbox** [comment]
Yeah, the event subscriber themselves define the priority. If you had a regular listener, which is externally registered, you could define it yourself.

The priority `0` is just the default, you are free to use for example `-10` to run after all the default listeners.

But yeah, there are no guarantees for listener with the same priority. So either Magento should bump its priority up (to sth >0) or grumphp bump it down (to sth <0). Or both 😄

**Comment by davidverholen** [comment]
@apfelbox ok but that's great, thx. I think it would make sense for magento then to set a high priority bey default, because it breaks other plugins that are executed before. So I should probably open an issue there and can close this :)

thx!
