### ISSUE TITLE
Scripts cannot be "any command-line executable command"

### ISSUE THREAD

**Issue by SteveALee** [composer/composer#9737]
Despite the docs saying the scripts can be any  "any command-line executable command" it appears not to be true.

Also it does not state which shell is used or how you might specify it.

For example I wanted to use "source" to read the `.env'` before running a php script file but it's not working so the shell is not bash etc.

**Comment by SteveALee** [comment]
Indeed it seems the [code uses](https://github.com/composer/composer/blob/72b77721097e8c64468c3b343a6d407f694107da/src/Composer/Util/ProcessExecutor.php#L118) a `Process` not `shell_exec`.

Why is that? It's a shame as it limits what we can run. Could you document it? Thanks.

**Comment by Seldaek** [comment]
If your script is too complex for what Composer can handle, maybe it's best to externalize it and then make the script `"bash foo.sh"`. But at that point anyway I almost wonder what the point is of running things via Composer :)

Anyway this is the first time in 10 years someone asked for executing via shell, so I am not super excited to spend time figuring this out TBH. We've got plenty of higher value work to do.. But if you figure out a reasonable way to make this work feel free to PR.

**Comment by SteveALee** [comment]
Heh  the javascript world is a bit different.

My point was the document statement is inaccurate. I'm not sure WHAT I can
and can't run :)

The only advantage of using in composer / npm scripts is a consistent way
to run common action. You can just look in the file or type run to get a
list.

Anyway, I have scripts and when I started using composer for idiomatic
module pattern with autoload thought I'd do as we do with npm. So no
problem for me.

Thanks.

**Comment by stof** [comment]
It says `any command line executable`. Shell builtins are precisely not command-line executable, but available only as part of a given shell.

**Comment by SteveALee** [comment]
> It says any command line executable.

So it does :)

> Shell builtins are precisely not command-line executable

I didn't try `bash -c` this time as env inheritance would not be what I wanted
