### ISSUE TITLE
composer config --dry-run for idempotent and validated changes

### ISSUE THREAD

**Issue by drzraf** [composer/composer#9741]
I tend to rely heavily on a standardized composer configuration across multiple machines, eg to set-up custom/private repositories.
As such I "provision" this configuration (aka "configuring the composer configuration").

But so far, I can not do that in an:
- **idempotent** way
  When running `composer config` (manually or in an automated way), I can't determinate whether configuration was changed or not. I'd like to know whether it would be changed.

- **safe** (validated) way.
  When triggering `composer config -j repositories.foobar <JSON>`, I've no way to anticipate whether the final configuration is going to be valid or not. But it's not, it would break further call to `composer config`).

I would like a `config --dry-run` flag which, if set, returns whether the configuration is going to be modified, and if the new configuration resulting from the change would be valid wrt the JSON schema.

**Comment by Seldaek** [comment]
The config command now validates the schema of the file it updated and reverts if it is not valid, so that it does not get you stuck.

e.g.

```
$ c conf -j repos.foobar '{"lala":"foo"}'

In JsonConfigSource.php line 285:

  Failed to update composer.json with a valid format, reverting to the original content. Please report an issue to us with details (command you run and a copy of your composer.j
  son).
  repositories.foobar.type : The property type is required
  repositories.foobar.url : The property url is required
  repositories.foobar.package : The property package is required
  repositories.foobar : Failed to match at least one schema
  repositories.foobar : Object value found, but a boolean is required
  repositories.foobar : Does not have a value in the enumeration [false]

```

So I'm closing this, I think it fixes the safety aspect. 

If you still need to know whether something changed I guess you can use git diff as an alternative.
