### ISSUE TITLE
composer dump-autoload cant recognize app classes while composer dump-autoload -o solves the problem.

### ISSUE THREAD

**Issue by larabarb** [composer/composer#9744]
My `composer.json`:

{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=7.0.0",
        "laravel/framework": "5.5.*",
        "laravelcollective/html": "5.5.*",
        "appzcoder/crud-generator": "^1.1",
        "uxweb/sweet-alert": "~1.1",
        "intervention/image": "^2.3",
        "yajra/laravel-datatables-oracle": "~8.0",
        "cornford/googlmapper": "2.*",
        "barryvdh/laravel-dompdf": "^0.8.0",
        "simplesoftwareio/simple-qrcode": "~1",
        "laravel/cashier": "~7.0",
        "doctrine/dbal": "^2.5",
        "pusher/pusher-php-server": "^3.0",
        "bugsnag/bugsnag-laravel": "^2.14",
        "jivesh/laravel-slack": "^1.0",
        "barryvdh/laravel-debugbar": "^2.4",
        "spatie/laravel-backup": "^5.0.0",
        "maatwebsite/excel": "~2.1.0",
        "league/flysystem-aws-s3-v3": "~1.0",
        "laravel/tinker": "~1.0",
        "guzzlehttp/guzzle": "^6.3",
        "barryvdh/laravel-ide-helper": "^2.4",
        "fideloper/proxy": "~3.3",
        "league/oauth2-client": "^2.3",
        "microsoft/microsoft-graph": "^1.4"
    },
    "require-dev": {
        "mockery/mockery": "0.9.*",
        "fzaninotto/faker": "~1.4",
        "phpunit/phpunit": "~6.0",
        "filp/whoops": "~2.0"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    }
}

Output of `composer diagnose`:

Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (1.10.1 => 2.0.11)
Composer version: 1.10.1
PHP version: 7.1.33
PHP binary path: /usr/bin/php7.1
OpenSSL version: OpenSSL 1.1.1j  16 Feb 2021

When I run this command: composer dump-autoload -vvv

I get the following output: 

Reading ./composer.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/home/forge/xxxxx.xxxxx.eo): git branch --no-color --no-abbrev -v
Cannot create cache directory /home/forge/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/forge/.composer/cache/files/, or directory is not writable. Proceeding without cache
Failed to initialize global composer: Composer could not find the config file: /home/forge/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /home/forge/xxxxx.xxxxxxx.com/vendor/composer/installed.json
Running 1.10.1 (2020-03-13 20:34:27) with PHP 7.1.33-34+ubuntu18.04.1+deb.sury.org+1 on Linux / 4.15.0-20-generic
Generating autoload files
> post-autoload-dump: Illuminate\Foundation\ComposerScripts::postAutoloadDump
> post-autoload-dump: @php artisan package:discover
Executing command (CWD): '/usr/bin/php7.1' -d allow_url_fopen='1' -d disable_functions='' -d memory_limit='1536M' artisan package:discover
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: barryvdh/laravel-ide-helper
Discovered Package: cornford/googlmapper
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: laravel/cashier
Discovered Package: laravel/tinker
Discovered Package: laravelcollective/html
Discovered Package: maatwebsite/excel
Discovered Package: spatie/laravel-backup
Discovered Package: uxweb/sweet-alert
Discovered Package: yajra/laravel-datatables-oracle
Package manifest generated successfully.
Generated autoload files

And I expected this to happen:
I expected everything to work fine but my app cant recognise any of its classes.

If i execute composer dump-autoload -o 
evrything works fine

**Comment by stof** [comment]
Is `composer dump-autoload -o` outputting a warning about classes not following PSR-4 rules ?

In composer 1.x, the generation of the optimized autoloader would register all classes found in the folder in the classmap, even though they are actually not autoloadable based on PSR-4. This has been changed in Composer 2 (and Composer 1 displays a warning).
the solution in such case is to fix your autoloading configuration. but without seeing your code and which class cannot be autoloaded, there is nothing we can do to help you identify what is wrong in the config.

**Comment by larabarb** [comment]
Hi there and thanks for replying

 this is the output of the command:  composer dump-autoload -o

Cannot create cache directory /home/forge/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/forge/.composer/cache/files/, or directory is not writable. Proceeding without cache
Generating optimized autoload files
Deprecation Notice: Class PHPExcel_Properties located in ./vendor/phpoffice/phpexcel/Classes/PHPExcel/Chart/Properties.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class PHPExcel_Linear_Best_Fit located in ./vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/trend/linearBestFitClass.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class PHPExcel_Polynomial_Best_Fit located in ./vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/trend/polynomialBestFitClass.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class PHPExcel_Best_Fit located in ./vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/trend/bestFitClass.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class PHPExcel_Exponential_Best_Fit located in ./vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/trend/exponentialBestFitClass.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class PHPExcel_Logarithmic_Best_Fit located in ./vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/trend/logarithmicBestFitClass.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class PHPExcel_Power_Best_Fit located in ./vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/trend/powerBestFitClass.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Faker\Provider\uk_Ua\Payment located in ./vendor/fzaninotto/faker/src/Faker/Provider/uk_UA/Payment.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Egulias\EmailValidator\Exception\ExpectedQPair located in ./vendor/egulias/email-validator/EmailValidator/Exception/ExpectingQPair.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class App\Http\Controllers\Auth\AuthController located in ./app/Http/Controllers/Auth/AuthController__DELETEME.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class App\Http\Requests\TimeusersCreateRequest located in ./app/Http/Requests/TimeUsersCreateRequest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class App\Http\Requests\Sendnewsletter located in ./app/Http/Requests/Sendewsletter.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class App\Http\Middleware\AdminOrAccountmanagerOrNewProjectsAdminOrMaintenanceAdmin located in ./app/Http/Middleware/AdminOrAccountmanagerOrnewprojectsadminOrmaintenanceadmin.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class App\crmo365contactsync located in ./app/Crmo365contactsync.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class App\Crmo365calendarsync located in ./app/crmo365calendarsync.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class App\Appevent located in ./app/AppEvent.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class App\Calendarevent located in ./app/CalendarEvent.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class App\DeltaQueryTest located in ./app/Office365.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class App\Exceptions\Handler located in ./app/Exceptions/Handler_mine.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Warning: Ambiguous class resolution, "App\Exceptions\Handler" was found in both "/home/forge/xxx.xxx.com/app/Exceptions/Handler.php" and "/home/forge/xxxxx.xxxxx.com/app/Exceptions/Handler_mine.php", the first will be used.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: barryvdh/laravel-ide-helper
Discovered Package: cornford/googlmapper
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: laravel/cashier
Discovered Package: laravel/tinker
Discovered Package: laravelcollective/html
Discovered Package: maatwebsite/excel
Discovered Package: spatie/laravel-backup
Discovered Package: uxweb/sweet-alert
Discovered Package: yajra/laravel-datatables-oracle
Package manifest generated successfully.
Generated optimized autoload files containing 6341 classes

**Comment by stof** [comment]
> Deprecation Notice: Class App\Http\Requests\TimeusersCreateRequest located in ./app/Http/Requests/TimeUsersCreateRequest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

PSR-4 discovery is subject to the case sensitivity of the filesystem (as it relies on the filesystem to discover the file. Here, you have `TimeusersCreateRequest` vs `TimeUsersCreateRequest.php`

**Comment by larabarb** [comment]
OK i see your point but I use composer 1. Should this happen?

**Comment by stof** [comment]
Well, even with composer 1, the fact that the PSR-4 discovery (when not using the optimized autoloader) cannot find the class is still true.
The difference in composer 2 is that optimizing the autoloader won't make things work anymore for broken autoloading.

**Comment by larabarb** [comment]
OK and thank you for supporting.
So what should i do??
Correct the case sensitive on the names? 
Thats all??

**Comment by Seldaek** [comment]
Yes, make sure the class name matches the file name exactly, and the deprecation notice will go away, and you won't have problems in Composer 2. Also you should make sure to upgrade to Composer 2 using `composer self-update --2` whenever you fixed the warnings, because it runs much faster than v1 :)
