### ISSUE TITLE
hg was not found in your PATH, skipping source download

### ISSUE THREAD

**Issue by dp-ifacesoft** [composer/composer#9753]
hg: /usr/bin/hg
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

php -d memory_limit=-1 /usr/bin/composer update --prefer-source --optimize-autoloader --apcu-autoloader

affected 2.0.10, 2.0.11

**Comment by Seldaek** [comment]
This is reported if the following code fails:

```
            if (0 === $process->execute('hg --version', $output) && preg_match('/version (\d+(?:\.\d+)+)/m', $output, $matches)) {
                self::$version = $matches[1];
            }
```

Can you tell me what output you get for `hg --version`?

**Comment by dp-ifacesoft** [comment]
www@ebs:~/html/ebs/bin$ hg --version
Распределенная SCM Mercurial (версия 5.6.1)
(see https://mercurial-scm.org for more information)

Copyright (C) 2005-2020 Matt Mackall and others
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
www@ebs:~/html/ebs/bin$ whereis hg
hg: /usr/bin/hg

**Comment by Seldaek** [comment]
Hah ok I did not expect this would be localized. Thanks, shouldn't be too hard to fix.

**Comment by dp-ifacesoft** [comment]
Thanks
