### ISSUE TITLE
No lock file found message is not intuitive

### ISSUE THREAD

**Issue by emodric** [composer/composer#9754]
Couple of times, I got a question about "No lock file found" warning in Composer 2. Newbies that never or rarely worked with Composer (or simply do not use it day-to-day) are asking why should they use `composer update` over `composer install` when no lock file is present. Their questions are mainly due to situations when there are no vendors installed at all, so it is confusing to them to have to run `composer update` because there is nothing to be updated yet.

While I understand and always explain the reasoning behind the message and am aware of potential edge cases (`vendor/` exists, but no lock file etc), I feel that the warning message brings more confusion than it benefits. At the very least, it should not be displayed when both `vendor` and `composer.lock` are not present.

My `composer.json`:

Not relevant

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.11
PHP version: 8.0.2
PHP binary path: /usr/bin/php8.0
OpenSSL version: OpenSSL 1.1.1j  16 Feb 2021
cURL version: 7.68.0 libz 1.2.11 ssl OpenSSL/1.1.1j
zip: extension present, unzip present
```

When I run this command (without `vendor` folder `composer.lock` file present):

```
composer install
```

I get the following output:

```
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
```

And I expected this to happen:

No warning message.

**Comment by stof** [comment]
`composer update` is not about updating your vendor folder. It is about updating the `lock` file (Composer 2 even has an option to do only the lock file update without doing the automatic installation).
`composer install` is about installing locked dependencies in your `vendor` folder.
If you don't have a lock file, you indeed need to update the list of dependencies of the project to have such a list.
This warning was added in Composer 2 precisely to help understand better what each command is about.

The source of truth for what your current dependencies are is the `composer.lock` file, not the `vendor` folder (which is why the `vendor` folder is ignored while committing the lock file is recommended for projects)

**Comment by emodric** [comment]
As I said, I do understand the difference and explain it as such. However, most newbies I had the chance to talk do, do not understand the difference: most of them corelate `install` with installing dependencies and `update` with updating dependencies and that's it.

Which brings me to my original point of having a confusing warning displayed, making them wonder if they did something wrong and for all intents and purposes, they did not.

**Comment by Seldaek** [comment]
Thanks, this is actually great feedback I think, as we are definitely blind to what newcomers experience after spending years working on the project ourselves.

I see that even https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies is rather unclear about this and guides people the wrong way.

I'll try and overhaul this section of the docs a bit, and maybe make an additional article explaining in depth what install and update are and do, so we can link to that from the warning. Hopefully confused souls will go educate themselves then :)
