### ISSUE TITLE
Alternate location for composer.json, like .config/composer.json

### ISSUE THREAD

**Issue by ReedyBear** [composer/composer#9759]
To clean up repos, I've been using `PROJECT_ROOT/.config/whatever-config.json` with libraries I develop.

Composer doesn't seem to support alternate location for `composer.json`.

Someone suggested I run composer from `proj_root/.config/` dir with a custom vendor directory configured. This should be viable for private projects. But I'd like my libraries to also be able to store `composer.json` at `project_root/.config/composer.json`

**Comment by Seldaek** [comment]
Sorry this is not something we're likely to support because we need to be able to find the composer.json file easily and if we have to scan in many places that'll consume many more GitHub API calls.
