### ISSUE TITLE
2.0.11 is scanning every single file while 2.0.8 is not

### ISSUE THREAD

**Issue by michabbb** [composer/composer#9760]
hi,

i don´t really understand why. when running "-vvv -h" i can see with a strace, that 2.0.11 is scanning "every single file" in my project while showing this:

`Reading /home/myproject/vendor/composer/installed.json`

while 2.0.8 is **NOT**.

so a simple "-h" takes:

2.0.8: 17 seconds
2.0.11: 2 minutes and 45 seconds
1.10.20: 11 seconds (btw)

is there a major change between these versions i have missed ?
i should mention: i am running composer via docker (Linux).

update: 2.0.9 behaves like 2.0.11 -> scanning every single file 😕

**Comment by Seldaek** [comment]
Not sure what you mean by "scanning", and definitely can not reproduce such slowness.. Also running `-vvv -h` does not mean anything, which command are you running exactly? Please provide full command and full output..

Here is the full changelog for 2.0.9 as that seems to contain the cause it's relevant https://github.com/composer/composer/compare/2.0.8...2.0.9 - but hard to pinpoint it any further given the lack of info here.

**Comment by michabbb** [comment]
i am running "composer -h -vvv" nothing more. i am running it inside a project with many files and lot installed packages. while watching with strace i can see that composer is reading, opening, scanning, touching -  however you want to call it, "every single PHP file" of my project, while 2.0.8 is not. that's reproducible for me - i am not able to identify the single commit out of 76 which might cause this, that´s why i wrote here in hope, someone has a clue....

**Comment by Seldaek** [comment]
Can you try with `composer -h -vvv --no-plugins --no-scripts`  see if that does it too?

**Comment by Seldaek** [comment]
And for the record, for me this runs in 0.1sec so already your 17 seconds on 2.0.8 seems insanely slow.

**Comment by michabbb** [comment]
when u are a windows user who is using vmware to have a real linux and using a shared mount for your code to see that inside your Linux, you are doomed anyway.. so reading many small files is bad as hell anyway... we don´t have to discuss who stupid that is, but it has nothing to do with the fact, that every composer version above 2.0.8 is touching, opening, reading, scanning every single file inside my project. maybe that is wanted, maybe not, i don´t know. but for everybody who is dealing with shared mounts, that is pure horror. so i am trying to find out, if this is intended or wanted because of some reasons i don´t understand, or if that is not intended and more seen as a bug.

**Comment by michabbb** [comment]
with `--no-plugins` everything is fine, thanks for letting me know, didn´t know that flag. is there any chance to disable each plugin individually so that I'm able to find out, which plugin is causing this scanning?

**Comment by michabbb** [comment]
so when using `-vvv` i see this:

```
Reading ./composer.json (/home/myproject/composer.json)
Loading config file /root/.composer/config.json
Loading config file /root/.composer/auth.json
Loading config file ./composer.json (/home/myproject/composer.json)
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/home/myproject): git branch -a --no-color --no-abbrev -v
Reading /root/.composer/composer.json
Loading config file /root/.composer/config.json
Loading config file /root/.composer/auth.json
Loading config file /root/.composer/composer.json (/root/.composer/composer.json)
Loading config file /root/.composer/auth.json
Reading /root/.composer/auth.json
Reading /home/myproject/vendor/composer/installed.json
Loading plugin UpdateHelper\ComposerPlugin
```

as soon composer prints

`Reading /home/myproject/vendor/composer/installed.json`

that´s the point in time where scanning all of my files begins....

**Comment by michabbb** [comment]
@Seldaek your hint with `--no-plugins` helped me to solve my problem, 1000 thanks !!!
so it´s not docker itself, it´s this plugin that is scanning all my files, don´t know why, but at least i finally know how to stop it.

thanks a lot !
