### ISSUE TITLE
Can't download composer from repo

### ISSUE THREAD

**Issue by Noso4eg** [composer/composer#9762]
When I run this command: 
php composer-setup.php --install-dir=../bin

I get the following output:
All settings correct for using Composer
Downloading...

But nothing happens, after few seconds returns nothing, in file manager I only see file composer-temp.phar - 0kb

I tried do download and run composer.phar mannualy (2.0.11), but it still returns nothing

**Comment by Noso4eg** [comment]
sed -i "s|;*memory_limit =.*|memory_limit = "512M"|i" /etc/php7/php.ini

the problem appeared after this setup, probably 512 was not enough

**Comment by Seldaek** [comment]
No idea why it'd get stuck there sorry .. I doubt it's related to memory as it's only download a few megabytes worth of data there.

Anyway you can download the phar file manually from https://getcomposer.org/download/ and then move it wherever you want and make it executable, that's about all the installer script does anyway.
