### ISSUE TITLE
How to add repositories from multiple private Bitbucket Workspaces?

### ISSUE THREAD

**Issue by vladoa** [composer/composer#9763]
What if we have multiple repositories that we want to include into an application, but they are in different private Bitbucket Workspaces?

For example: 

```
bitbucket.org/my-workspace-1/my-repository-1.git
bitbucket.org/my-workspace-2/my-repository-2.git

 ```

For example, I have my auth.json file, with the following structure:

 

"bitbucket-oauth": {
  "bitbucket.org": { 
        "consumer-key": "",                
        "consumer-secret": "",                
        "access-token": "",
        "access-token-expiration": 99999           
   }    
},

With Bitbucket workspaces, [consumers are defined for each workspace](https://support.atlassian.com/bitbucket-cloud/docs/use-oauth-on-bitbucket-cloud/). 

So if there are multiple consumers/tokens to be added, how can this be done?
Or maybe there is a different approach?

**Comment by Seldaek** [comment]
I guess there is currently no way to achieve this with Composer as it only has a single auth concept for bitbucket.org. They keep changing their API and it's a nightmare to follow tbh.

[Private Packagist](https://packagist.com/) would probably allow you to solve this though as you can sync up multiple workspaces there and then you get all of it exposed in one single Composer repository with one authentication to set up.
