### ISSUE TITLE
Cannot install with brew, wrong SHA256 signature

### ISSUE THREAD

**Issue by sdondley** [composer/composer#9764]
Sorry if this is the wrong place to post this. On a mac, doing `brew install composer`:

```
==> Downloading https://getcomposer.org/download/2.0.11/composer.phar
Already downloaded: /Users/me/Library/Caches/Homebrew/downloads/3555b6c6fce103b369f42c5c4f1b567b76bfb71f838b9bdcadddcffc7d279a22--composer.phar
Error: SHA256 mismatch
Expected: eabf2917072096a94679193762501319e621e2b369a4a1256b2c27f4e6984477
  Actual: d6eee0d4637f4bd82bdae098fceda300dcb3ec35bf502604fbe7510933b8f952
    File: /Users/me/Library/Caches/Homebrew/downloads/3555b6c6fce103b369f42c5c4f1b567b76bfb71f838b9bdcadddcffc7d279a22--composer.phar
To retry an incomplete download, remove the file above.
```

Removing the file per suggestion in last line doesn't work.

**Comment by lukasjuhas** [comment]
@sdondley I'm having some issues. In the meantime, I've uninstalled it in brew (`brew remove composer`) and installed it manually as documented on the composer website. Hope that helps!

**Comment by Seldaek** [comment]
Sorry this was due to https://github.com/composer/composer/issues/9746#issuecomment-793984249 - https://github.com/Homebrew/homebrew-core/pull/72796 has been merged now so I assume it's fixed on the homebrew side.

**Comment by sdondley** [comment]
Yup. Works now. Thanks.
