### ISSUE TITLE
Composer and WSL 

### ISSUE THREAD

**Issue by Goddard** [composer/composer#9766]
Getting an issue in windows composer and also manually downloaded composer in WSL container.

From Windows
composer.bat update
'\\wsl$\Ubuntu\home\goddard\projectDir'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
Composer could not find a composer.json file in C:\Windows
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

From WSL Linux
/usr/local/bin/composer update
Loading composer repositories with package information
The following exception probably indicates you are offline or have misconfigured DNS resolver(s)

  [Composer\Downloader\TransportException]
  curl error 28 while downloading https://api.github.com/repos/Goddard/datatables: Resolving timed out after 10000 milliseconds

Just to verify inside WSL I have a connection.
ping google.com
PING google.com (172.217.2.206) 56(84) bytes of data.
64 bytes from mia09s02-in-f14.1e100.net (172.217.2.206): icmp_seq=1 ttl=116 time=18.1 ms
64 bytes from mia09s02-in-f14.1e100.net (172.217.2.206): icmp_seq=2 ttl=116 time=19.2 ms
64 bytes from mia09s02-in-f14.1e100.net (172.217.2.206): icmp_seq=3 ttl=116 time=17.1 ms
^C
--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 17.056/18.144/19.231/0.887 ms

**Comment by Seldaek** [comment]
Can you show the output of the following from WSL?

```
dig api.github.com
ping -4 api.github.com
```

**Comment by Seldaek** [comment]
The error indicates a dns issue, so I am not sure, you can also check what you have in `/etc/resolv.conf`, that typically points to the host (windows) local IP so WSL can use it as a resolving proxy. Then resolving is done via whatever ipconfig.exe shows.
