### ISSUE TITLE
[Feature] Command to dump files -> package mapping

### ISSUE THREAD

**Issue by morrisonlevi** [composer/composer#9769]
It would be useful for a variety of tools to create an associated map of filenames to package information, such as name, version, git sha, url -- aside from name I'm not 100% sure else what should be included.

For instance, the zend engine has a `filename` field on the `zend_op_array` which it uses to represent user code including functions. We could load up the associated file map described above, look up the file from the function being called and potentially map it back to the package it came from.

I was looking around at the plugin API. It looks like it might be able to do this. Any pointers on where to get started on implementing this?

**Comment by Seldaek** [comment]
I think you could easily make it a runtime library (not plugin) once https://github.com/composer/composer/pull/9699 is merged and 2.1 is released. So you just require composer-runtime-api ^2.1 in your lib, and you're good to go.

The library would essentially fetch the package list with paths, then figure out within which package's base path a given file is located.
