### ISSUE TITLE
Problem with extensions loaded #8828

### ISSUE THREAD

**Issue by AlexG542** [composer/composer#9772]
Getting this error when I open localhost from the browser to login phpmyadmin "Composer detected issues in your platform: Your Composer dependencies require the following PHP extensions to be installed: openssl" . Any help would be highly appreciated!

**Comment by Seldaek** [comment]
This means you need to enable the php_openssl extension in yourphp.ini.

**Comment by AlexG542** [comment]
That works :) Thank you so much!!!

**Comment by williamsOnwuesi** [comment]
Please how do i acces my php.ini settings. I am running on a localhost server. Thanks.
