### ISSUE TITLE
[Composer\Downloader\TransportException] curl error 28 while downloading http://repo.packagist.org/packages.json: Connection timed out after 10014 milliseconds

### ISSUE THREAD

**Issue by sabrina-dermm** [composer/composer#9775]
![composer](https://user-images.githubusercontent.com/59965949/110954698-1601cc80-8349-11eb-899c-8f301dfc041c.PNG)

Facing this issue; 

i tried to run  composer config -g repo.packagist composer https://packagist.org and still not working

**Comment by stof** [comment]
There has been some DNS issue with packagist.org this afternoon, which might explain it if your DNS resolution used one of the dead IPs that were returned by mistake.

**Comment by Seldaek** [comment]
@sabrina-dermm if you can still reproduce the issue, please let us know what you see from `ping repo.packagist.org`

**Comment by Seldaek** [comment]
Most likely it's a bad dns cache though, running `ipconfig /flushdns` in cmd.exe might help if you're on windows.

**Comment by sabrina-dermm** [comment]
at first i had no response for ping repo.packagist.org but it worked after running ipconfig /flushdns 

Thanck you for your help !

**Comment by pentoljoyo** [comment]
i have same problem. i tried running ipconfig /flushdns before ist look same. i need help
