### ISSUE TITLE
[Seld\JsonLint\ParsingException]

### ISSUE THREAD

**Issue by ipwnosx** [composer/composer#9780]
[Seld\JsonLint\ParsingException]               
  "./composer.json" does not contain valid JSON  
  Parse error on line 87:                        
  ...ersion": "3.22.0"}"repositories": [         
  --------------------^                          
  Expected one of: 'EOF', '}', ',', ']'

**Comment by mfn** [comment]
>  ...ersion": "3.22.0"}"repositories": [

You're missing a `,` after the `}`
![image](https://user-images.githubusercontent.com/87493/111266430-d37f0f00-862a-11eb-9f63-6d1926f49ab2.png)

**Comment by ipwnosx** [comment]
How do I fix? Via osx

**Comment by stof** [comment]
open your file in a text editor and add the mixxing comma
