### ISSUE TITLE
Changing working dir using -d/--working-dir behaves strange when there is space between option and argument

### ISSUE THREAD

**Issue by grongor** [composer/composer#9783]
```
$ pwd
/some/path

$ ls
app

$ composer -dapp
// works

$ composer --working-dir=app
// works

$ composer --working-dir app
// same as bellow

$ composer -d app -vvv
Changed CWD to /some/path/app
Reading ./composer.json (/some/path/app/composer.json)
...

  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "app" is not defined.
```

**Comment by Seldaek** [comment]
I think this may depend on which shell you are using, for me it works fine with a space. Maybe you can use `-d=app` otherwise?

**Comment by stasadev** [comment]
This is due to a bug in the symfony/console package v2 that was [fixed](https://github.com/symfony/console/commit/7690bb425af29e419fdbf58a09e6f6f9ac5ddc55) in v3 and higher.
Thus, it will be automatically resolved after dropping support for older PHP versions.

**Comment by Seldaek** [comment]
Ok yeah I suspected something like that, will be autofixed in 2.2 then, closing as we have other issues tracking this already.
