### ISSUE TITLE
why not reuse the existing meta json files in the cache directory

### ISSUE THREAD

**Issue by ym2048** [composer/composer#9785]
I found that each time I import a new component, all json meta need to be downloaded to cache directory again， Why not reuse the existing files in the cache directory？

For example，execute the following command in an empty directory, 
```
composer require dompdf/dompdf -vvv
```
each time you will find these output
```
Downloading https://repo.packagist.org/packages.json
Writing C:/Users/ander/AppData/Local/Composer/repo/https---repo.packagist.org/packages.json into cache
Downloading https://repo.packagist.org/p/provider-2013%2428677fcc9ec823bf0e5c06593f4062c5212c1659c53ec1fdc5a6dc2a23129b83.json
Writing C:/Users/ander/AppData/Local/Composer/repo/https---repo.packagist.org/p-provider-2013.json into cache
Downloading https://repo.packagist.org/p/provider-2014%24eeef2789c9c679f62c0c0e329e29d22fc4b75dc1da8c82b6b8e34caf00c58888.json
Writing C:/Users/ander/AppData/Local/Composer/repo/https---repo.packagist.org/p-provider-2014.json into cache
Downloading https://repo.packagist.org/p/provider-2015%24d93efbc429d0fe79629da2132446d55ffc057b1f1ba6bf0385414ec12df9174b.json
Writing C:/Users/ander/AppData/Local/Composer/repo/https---repo.packagist.org/p-provider-2015.json into cache
Downloading https://repo.packagist.org/p/provider-2016%24b0f0fef6e8437a694a89e8b8165901f64da8065c5d3522e07cff947ea4acf14f.json
Writing C:/Users/ander/AppData/Local/Composer/repo/https---repo.packagist.org/p-provider-2016.json into cache
...
```
Even if these files already exist and are exactly the same as remote files, they will not be reused.
I think we can consider comparing SHA1 values to reduce unnecessary download consumption. I believe this will speed up the introduction of new components with composer, especially for large projects that rely on a large number of resources

**Comment by stof** [comment]
Are these files really exactly the same ?

side note: switch to composer 2 which will not download these files at all, and will load metadata in a format which is much more efficient in term of bandwidth.

**Comment by Seldaek** [comment]
As stof said, composer 2 handles this quite differently and much better, please upgrade. See https://getcomposer.org/2 - Closing this as we are not going to change how Composer 1.x behaves anymore.
