### ISSUE TITLE
Performance improvement (more than 40x-50x times) for autoload_classmap.php

### ISSUE THREAD

**Issue by sirian** [composer/composer#9786]
Inline variables `$vendorDir` and `$baseDir` at `vendor/composer/autoload_classmap.php`

Just see real example
![image](https://user-images.githubusercontent.com/897643/111631921-04b33700-8805-11eb-9975-72dbcec9cccb.png)

On real project we have huge difference:
```
autoload_classmap.php	762.98Kb	277.57ms
autoload_classmap2.php	764.51Kb	0.30ms
```

**Comment by stof** [comment]
A real-world project running on PHP 5.6+ will never load this file, as the generated autoloader will load the `autoload_static.php` file instead. So I don't see how you get such a difference.

**Comment by sirian** [comment]
I know about autoload_static.php. I'm talking about synthetic example (on screenshot). Or maybe smbd still uses php 5.3-5.5

**Comment by Seldaek** [comment]
Sorry but if you are still using php 5.5 or below, you definitely are not interested in performance improvement.. Optimizing this is pointless.
