### ISSUE TITLE
composer metadata not correct somehow

### ISSUE THREAD

**Issue by vidyli** [composer/composer#9790]
```
Dependency resolution completed in 33.367 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package vidy/magento-2-blog-extension ^4.0.2 exists as vidy/magento-2-blog-extension[1.0.0, 2.2.1, 2.2.2, 2.3.0, 2.4.0, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.5.0, 2.6.0, 2.6.1, 2.6.2, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 4.0.0] but these are rejected by your constraint.
  Problem 2
    - The requested package vidy/module-blog-graphql ^1.0.3 exists as vidy/module-blog-graphql[1.0.0, 1.0.1] but these are rejected by your constraint.

```

the above said the `vidy/module-blog-graphql ` only has release [1.0.0, 1.0.1], but I do have [1.0.3 ](https://github.com/vidyli/magento-2-blog-graphql/releases), so does the `vidy/magento-2-blog-extension` package,

anybody knows why?

I added the repo address like this
composer.json
```
 "repositories": [
        {
            "url": "https://github.com/vidyli/magento-2-blog-graphql.git",
            "no-api": true,
            "type": "vcs"
        },
        {
            "url": "https://github.com/vidyli/magento-2-blog.git",
            "no-api": true,
            "type": "vcs"
        }
}
```

**Comment by stof** [comment]
the issue is that your 1.0.3 release has a `version` field in its `composer.json` saying `1.0.1`, making it an invalid release.

When using a VCS repo, you should really omit the `version` field. It provides only drawbacks and no benefits in this case, as the version comes from the VCS metadata.

**Comment by vidyli** [comment]
@stof  thanks, you are right, sorry for the late response.
