### ISSUE TITLE
Please release a version with updated GitHub token regex

### ISSUE THREAD

**Issue by shivammathur** [composer/composer#9800]
Change in GitHub tokens to include capital letters and underscore is now in effect.
https://github.blog/changelog/2021-03-31-authentication-token-format-updates-are-generally-available/

So anyone installing packages after setting the oauth token for GitHub will get this [error](https://github.com/shivammathur/test-setup-php/runs/2241944124?check_suite_focus=true#step:2:18).
``` 
[UnexpectedValueException]                                                                                      
  Your github oauth token for github.com contains invalid characters: "***"  
```

Please make new releases having this patch https://github.com/composer/composer/commit/dc83ba93f3d8a35629f9a387632e8cd373a144d0

**Comment by Seldaek** [comment]
2.0.12 and 1.10.21 are out now with the fix.

**Comment by ENM1989** [comment]
> 2.0.12 and 1.10.21 are out now with the fix.

Thank you, this saved my day. :+1:
