### ISSUE TITLE
on php8.0.3(docker) exit code is 11

### ISSUE THREAD

**Issue by haohetao** [composer/composer#9801]
root@d70ccd6eb7d7:/# composer --version
Composer version 2.0.11 2021-02-24 14:57:23
root@d70ccd6eb7d7:/# echo $?
11
root@d70ccd6eb7d7:/# php --version
PHP 8.0.3 (cli) (built: Mar  5 2021 07:54:13) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies

run in docker

**Comment by mfn** [comment]
Can you share the docker image?

What does `echo $?` yield just after running `php --version`?

**Comment by haohetao** [comment]
I found the problem because there was a conflict with another extension I was using。

**Comment by haohetao** [comment]
This extension will cause exit code is 11 on all phar file.

**Comment by Seldaek** [comment]
Alright then closing as it's unrelated to Composer.
