### ISSUE TITLE
Don't hook "pre-install-cmd" when exists composer.lock and not exists vendor directory

### ISSUE THREAD

**Issue by vjik** [composer/composer#9806]
Composer 2.0.12

I have `composer.lock` and don't have directory `vendor`.

Run `composer install`.

Hook `pre-install-cmd` don't fire.

**Comment by Seldaek** [comment]
How should it fire the pre-install-cmd hooks if the code to be executed is not there? 

pre-install-cmd will be executed if the code is in the project itself, but not if it's in a vendor package. This was always the case.
