### ISSUE TITLE
Missing error checking that Process(...) actually worked

### ISSUE THREAD

**Issue by ValtsS** [composer/composer#9808]
https://github.com/composer/composer/blob/91136213d11630d881bf8ff9c0e1df37daf50d22/src/Composer/Util/ProcessExecutor.php#L261

if process(..) failed then it fails down the line when tries to references job['process'] and does not find the key. Experienced on a PHP installation where certain functions are disabled.

**Comment by Seldaek** [comment]
I am not really sure how to reproduce the failure so am not 100% sure the fix is correct, but if you can check with the latest snapshot (composer self-update --snapshot) that would be great.

**Comment by ValtsS** [comment]
Seems to have worked:

![image](https://user-images.githubusercontent.com/11734687/118979500-33729880-b981-11eb-8e96-07073063830a.png)
