### ISSUE TITLE
composer update --lock also SEEMS to update dev packages, but doesn't really

### ISSUE THREAD

**Issue by rudiedirkx** [composer/composer#9812]
My `composer.json`: full of secrets, sorry, but the important part:

```
{
    "require": {
        "php": ">=7.4",
        "cweagans/composer-patches": "^1.6",
        "kris/laravel-form-builder": "dev-master"
    },
    "extra": {
        "patches": {
            // nothing for kris/laravel-form-builder
        }
    }
}
```

I include `cweagans/composer-patches` because it might be relevant as a composer plugin, even though there are no patches for `kris/laravel-form-builder`.

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.12
PHP version: 7.4.15
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1j  16 Feb 2021
cURL version: 7.58.0 libz 1.2.11 ssl OpenSSL/1.1.1j
zip: extension present, unzip present
```

Full output of `update --lock`:

```
rudie@homeblox:myproject(dev)$ composer -vvv update --lock
Reading ./composer.json (/var/www/myproject/composer.json)
Loading config file /home/rudie/.config/composer/auth.json
Loading config file ./composer.json (/var/www/myproject/composer.json)
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/var/www/myproject): git branch -a --no-color --no-abbrev -v
Reading /home/rudie/.config/composer/composer.json
Loading config file /home/rudie/.config/composer/auth.json
Loading config file /home/rudie/.config/composer/composer.json (/home/rudie/.config/composer/composer.json)
Loading config file /home/rudie/.config/composer/auth.json
Reading /home/rudie/.config/composer/auth.json
Reading /var/www/myproject/vendor/composer/installed.json
Reading /home/rudie/.config/composer/vendor/composer/installed.json
Loading plugin cweagans\Composer\Patches (from cweagans/composer-patches)
Running 2.0.12 (2021-04-01 10:14:59) with PHP 7.4.15 on Linux / 4.15.0-140-generic
> pre-update-cmd: cweagans\Composer\Patches->checkPatches
Gathering patches for root package.
Reading ./composer.lock (/var/www/myproject/composer.lock)
Loading composer repositories with package information
Downloading https://repo.packagist.org/packages.json
[200] https://repo.packagist.org/packages.json
Writing /home/rudie/.cache/composer/repo/https---repo.packagist.org/packages.json into cache
Reading /home/rudie/.cache/composer/repo/https---repo.packagist.org/provider-brick~math.json from cache
Downloading https://repo.packagist.org/p2/brick/math.json if modified
....
[304] https://repo.packagist.org/p2/brick/math.json
....
Downloading https://repo.packagist.org/p2/guzzlehttp/psr7.json if modified
....
Reading /home/rudie/.cache/composer/repo/https---repo.packagist.org/provider-illuminate~mail.json from cache
Downloading https://repo.packagist.org/p2/illuminate/mail.json if modified
....
[304] https://repo.packagist.org/p2/illuminate/bus.json
Updating dependencies
Generating rules
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.038 seconds
Analyzed 4689 packages to resolve dependencies
Analyzed 31374 rules to resolve dependencies
Generating rules
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.001 seconds
Lock file operations: 0 installs, 1 update, 0 removals
Updates: kris/laravel-form-builder:dev-master cd17545
  - Upgrading kris/laravel-form-builder (dev-master 538ed8d => dev-master cd17545)
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
> post-autoload-dump: Illuminate\Foundation\ComposerScripts::postAutoloadDump
54 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

The weird bit in there is:

```
Lock file operations: 0 installs, 1 update, 0 removals
Updates: kris/laravel-form-builder:dev-master cd17545
  - Upgrading kris/laravel-form-builder (dev-master 538ed8d => dev-master cd17545)
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
```

So it pretends to upgrade `kris/laravel-form-builder` to the newest dev, even though `--lock` shouldn't do that, but also it actually doesn't. If I run the same command again, it pretends to upgrade again, and again, etc, and it never does upgrade. Very very confusing.

Happened in Composer 2.0.11, so I upgraded to 2.0.12, and it still happens.

**Comment by rudiedirkx** [comment]
`composer.lock` after this `update --lock`:

        {
            "name": "kris/laravel-form-builder",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/kristijanhusak/laravel-form-builder.git",
                "reference": "538ed8d3010a636663099d27b51400ce32bdaf3b"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/kristijanhusak/laravel-form-builder/zipball/538ed8d3010a636663099d27b51400ce32bdaf3b",
                "reference": "538ed8d3010a636663099d27b51400ce32bdaf3b",
                "shasum": ""
            },
            "require": {
                "illuminate/database": "^5.6@dev|^6|^7|^8",
                "illuminate/validation": "^5.6@dev|^6|^7|^8",
                "laravelcollective/html": "^5.6|^6|^7|^8",
                "php": ">=7.1"
            },
            "require-dev": {
                "orchestra/testbench": "^6.13"
            },
            "default-branch": true,
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "1.16.x-dev"
                },
                "laravel": {
                    "providers": [
                        "Kris\\LaravelFormBuilder\\FormBuilderServiceProvider"
                    ],
                    "aliases": {
                        "FormBuilder": "Kris\\LaravelFormBuilder\\Facades\\FormBuilder"
                    }
                }
            },
            "autoload": {
                "psr-0": {
                    "Kris\\LaravelFormBuilder": "src/"
                },
                "classmap": [
                    "tests/FormBuilderTestCase.php"
                ],
                "files": [
                    "src/helpers.php"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Kristijan Husak",
                    "email": "husakkristijan@gmail.com"
                }
            ],
            "description": "Laravel form builder - symfony like",
            "keywords": [
                "builder",
                "form",
                "laravel",
                "symfony"
            ],
            "support": {
                "issues": "https://github.com/kristijanhusak/laravel-form-builder/issues",
                "source": "https://github.com/kristijanhusak/laravel-form-builder/tree/master"
            },
            "time": "2021-03-27T14:32:16+00:00"
        },

`"reference": "538ed8d3010a636663099d27b51400ce32bdaf3b"` is the 'old' one, so it didn't actually upgrade.

BUT: `"time": "2021-03-27T14:32:16+00:00"` is from the newest dev, not the installed version. Before `update --lock` it said `"time": "2021-03-14T16:24:37+00:00"` which belongs to `538ed8d` which is still installed. (Commits at https://github.com/kristijanhusak/laravel-form-builder/commits/master)

Very very weird this.

**Comment by stof** [comment]
does it also happen without the patch plugin in the project ?

**Comment by rudiedirkx** [comment]
Yes. I don't know why I made the patch plugin important. It makes no difference.

```
Updating dependencies
Lock file operations: 0 installs, 0 updates, 1 removal
  - Removing cweagans/composer-patches (1.7.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 0 updates, 1 removal
  - Removing cweagans/composer-patches (1.7.0)
Generating autoload files
```

And then, still:

```
Lock file operations: 0 installs, 1 update, 0 removals
Updates: kris/laravel-form-builder:dev-master cd17545
  - Upgrading kris/laravel-form-builder (dev-master 538ed8d => dev-master cd17545)
Writing lock file
Installing dependencies from lock file (including require-dev)
Reading ./composer.lock (/var/www/myproject/composer.lock)
Nothing to install, update or remove
Generating autoload files
```

With the weird `composer.lock` diff:

```
-            "time": "2021-03-14T16:24:37+00:00"
+            "time": "2021-03-27T14:32:16+00:00"
```

and without the actual package upgrade.

----

Am I seriously the only one with this issue? That's even weirder! Seems easily reproducible, if you create your own test package and require its `dev-master`. But I haven't tried.

**Comment by Seldaek** [comment]
I created a lock file with your outdated hash, then it updates fine for me:

```
$ c upd
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading kris/laravel-form-builder (dev-master 538ed8d => dev-master cd17545)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Syncing kris/laravel-form-builder (dev-master cd17545) into cache
  - Upgrading kris/laravel-form-builder (dev-master 538ed8d => dev-master cd17545): Checking out cd17545fc8 from cache
Generating autoload files
29 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

The lock file then contains cd17545 and the correct time.. so not sure what to say.

Do you perhaps have custom repositories? 
Can you try if running the update with `--no-cache` results in a different outcome?

**Comment by rudiedirkx** [comment]
But I'm NOT updating. I do a `composer update --lock` to ONLY update the lock file, and NO packages, just like `--lock` promises to do.

If I do a `composer update`, it works fine. The UI/message, the timestamp, the package, all updates as expexted. That's not the problem. The problem is the `composer update --lock`.

**Comment by rudiedirkx** [comment]
> Do you perhaps have custom repositories?

No custom repos.

**Comment by Seldaek** [comment]
Oh right sorry I lost track of that along the way trying to repro.. :) Indeed with --lock I can reproduce your issue. I think the lock file bump to the latest date is expected behavior, but the output should not really list this as an upgrade as there is no actual upgrade happening.

**Comment by stof** [comment]
why would it bump the date if it does not bump the reference ?

**Comment by Seldaek** [comment]
In 2.x, all metadata is updated to latest but the version/reference is kept. The updating of the date though probably should not happen, as it should strictly speaking match the reference. I'll include this in #9821.

**Comment by hostep** [comment]
@Seldaek: I'm seeing a very similar issue over here, maybe not exactly the same

This is using some packages that have a constraint starting with `dev-` (using a branch name) and those packages are hosted on a custom satis repository.

Running `composer update --lock` (using version 2.0.0 or higher), results in an updated `composer.lock` file in the fields:
`dist > url` & `dist > shasum` & `time` and also the `require` section is updated if it got changed in the latest version of that particular branch.
But the packages are not updated themselves (which is good).

For me it's really confusing that composer outputs it updates the packages, but https://github.com/composer/composer/pull/9821 will probably fix that, and that the `composer.lock` file gets changed with some data from the latest version at that branch.
So maybe it's not only the `time` field that shouldn't get updated, but those other fields as well?

Example of diff after `composer update --lock` in my particular case:

<img width="1243" alt="Screenshot 2021-04-08 at 11 49 50" src="https://user-images.githubusercontent.com/85479/114006548-d0a9bf80-9860-11eb-9205-379d3e8151d4.png">

**Comment by Seldaek** [comment]
@hostep right, good point, I'll look into restricting updates of further fields.

**Comment by hostep** [comment]
I just tested the changes from https://github.com/composer/composer/pull/9821 after it got merged and here's what I'm seeing with the case from above:

- No more output of `Upgrading ... ` (good)
- No more changed `time` fields in `composer.lock` (good)
- Those other fields still got updated though (not good)

**Comment by stof** [comment]
updating the URL automatically causes issues if its not a URL in which composer can replace the reference magically (for which we would need https://github.com/composer/composer/issues/9661 to support that on arbitrary sources of archives rather than just for github).
and the shasum should indeed also be kept.

**Comment by stof** [comment]
side note, updating the requirements also look wrong to me, as we kept the same reference. When updating mirrors, we should probably update only URLs (which are safe to update) and keep everything else untouched.

**Comment by hostep** [comment]
Hmm, but that url change scares me, because it is a different version that gets downloaded, or is that url irrelevant when a package uses a constraint that starts with `dev-`? Even when using `--prefer-dist`? Sorry for the many questions 🙂

**Comment by stof** [comment]
@hostep that's why I said `which are safe to update`. When using a github download URL, Composer is able to replace the reference in it to ensure the right commit is still downloaded, even when updating the URL to use the new repo name.
But for generic packages, that's indeed not safe to do when the reference is hardcoded in the URL in a way unknown to composer (which is what #9661 could solve in the future)
