### ISSUE TITLE
Autoloading not work

### ISSUE THREAD

**Issue by ruslanzelinskyy** [composer/composer#9815]
My `composer.json`:

```json
    "type": "project",
    "autoload": {
        "psr-4": {
            "App\\": "server/src/"
        }
    },
    "config": {
        "vendor-dir": "server/vendor/"
    },
    "require": {}
```

Output of `composer diagnose`:

```
The "fxp/composer-asset-plugin" plugin (installed globally) was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking composer version: OK
Composer version: 2.0.12
PHP version: 7.4.3
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 31 Mar 2020
cURL version: missing, using php streams fallback, which reduces performance
zip: extension not loaded, unzip present
```

When I load my index.php 

```
<?php

use App\MyClass;

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
require __DIR__ . '/../vendor/autoload.php';

$myClass = new MyClass();
$myClass ->Load();

```

Files dirs:

```
./composer.json
./server/web/index.php
./server/src/MyClass.php
./server/vendor/
```
MyClass.php:
```
<?php

namespace App;

class MyClass
{
    public function __construct()
    {
    }

    public function Load(): void
    {
    }
}
```

I get the following error (Line $myClass = new MyClass();):

```
Fatal error: Uncaught Error: Class 'App\MyClass' not found in /var/www/public/web/index.php:13 Stack trace: #0 {main} thrown in /var/www/public/web/index.php on line 13
```

And I expected this to happen:

Emm.. Class should be loaded!

**Comment by Seldaek** [comment]
Did you run `composer dump-autoload` or `composer install` to make sure the autoloader is configured with your latest composer.json changes?

**Comment by ruslanzelinskyy** [comment]
> Did you run `composer dump-autoload` or `composer install` to make sure the autoloader is configured with your latest composer.json changes?

Yes ofcourse,
I've tried 
```composer install```
```composer dump```
```composer dump-autoload```

**Comment by Seldaek** [comment]
Then maybe you can try to build a public repo which reproduces the problem so we can have a closer look, because it sounds to me like you're doing something wrong but I can't say what..

**Comment by ruslanzelinskyy** [comment]
solved (wrong volume configuration of php docker container)

**Comment by ccjjmartin** [comment]
This is the first issue that came up for me on google, so I am adding another solution to a similar problem here.  I fought with an autoloading problem recently that turned out to be related to not autoloading php short codes anymore.  I had to change the top of the file from:

```
<?
```

to:
```
<?php
```
