### ISSUE TITLE
Install dependencies as a phar instead on extracting to FS

### ISSUE THREAD

**Issue by mvorisek** [composer/composer#9835]
This is a feature request.

Composer is great tool used daily by developers. One of the most used command is `composer install`. In CI, it is used at least once per php job. This typical usage needs optimal solution.

The install step consists of 3 time consuming operations.

- dependency solving
- download
- install/extract

The 1st operation will be improved shortly by https://github.com/composer/composer/pull/9261, thanks to @Toflar, or by using a lock file.

Download... We can not do here too much, but it is fast when cache is used for repeatable runs.

Install/Extract. This step currently takes quote a lot of time and IOPS as usually thousands of files are written.

This is a feature request to add native support to composer to extract (in-memory) the dependencies to a phar archive during the install step so only one file per dependency is written to the disk.

This feature is expected to reduce the total file count by about 100x, which is helpful because it:

- reduce install/copy time of app releases/bundles to webhosting for end users
- backup time (less files needs to be scanned/indexed)
- integrity (package consists of one file instead of multiple)

**Comment by stof** [comment]
Having one phar per dependency that needs to be loaded and mapped to be able to access classes in it for the autoloader will likely have a runtime performance impact (and I don't know how this works with preloading).
Also, depending on what the package does, it might break when running it inside a phar (for instance if it bundles other resources than PHP code)

**Comment by mvorisek** [comment]
Performace - I do no think so, because phar is basically php entry point + halt compiler instruction. All other data are loaded once they are needed like with regular file. But of coure performace must be verified.

> Also, depending on what the package does, it might break when running it inside a phar (for instance if it bundles other resources than PHP code)

This is correct, for ex. when there is an .js rosource loaded outside from php. I belive this can be solved by introducing some new `composer.json` option in the source package. And when enabled, this optimization can then take a place.

**Comment by Seldaek** [comment]
IMO this is really not worth the hassle. It'd create all sorts of issues and I don't really see the huge value being added by this.
