### ISSUE TITLE
DX: Separate error message for cyclic dependencies

### ISSUE THREAD

**Issue by staabm** [composer/composer#9837]
I get asked from time to time from less experienced composer users why they have errors like

![grafik](https://user-images.githubusercontent.com/120441/115202875-23a03400-a0f7-11eb-8f37-859c0faaac86.png)

the actual problem is, that they have defined a cyclic dependency without realizing it.
would it make sense/feasable to use/print a error/warning message which explicitly states that?

cyclic dependencies lead to a lot of problems, and leaving less experienced people with a error message which they need to interpret and realize that they actually build a circle is not helpful.

maybe its not possible or hard to identify - I have no idea.. just leaving the idea here, to gather some feedback.

**Comment by Seldaek** [comment]
Definitely sounds possible to identify this based on the fact that the root package repo is the top prio package and that is not installable. This is a fairly unique condition I believe. Do you perhaps have a suggested wording that would help, if you have already explained this to less experienced people?

**Comment by stof** [comment]
thus, in case of an _intended_ cyclic dependency involving the root package, the solution is also special (as most of the time, the root cause is due to the need to configure a root version explicitly rather than relying on the guessed one, which might not be guessed properly). The wording might point in that directly.

**Comment by Seldaek** [comment]
https://github.com/composer/composer/pull/9902
