### ISSUE TITLE
Files lost

### ISSUE THREAD

**Issue by cyjobes** [composer/composer#9838]
I have (had) a directory called "htdocs' inside a directory called "Websites"

I Went to add a new Laravel project inside the "Websites" directory, as it was a special site that did not belong to htdocs.

Here is what I ran
composer create-project laravel/laravel package-maker

So the intention is to create a new folder named package-maker and place a new Laravel project within.

BUT, it deleted all the contents of the Websites directory. I lost tons of work. Some yet to be backed up.

WTH? WHY????

**Comment by Seldaek** [comment]
That sounds really bad, sorry this happened to you, but it also does not sound like normal operation. Do you have any more details? Can you reproduce it (in a directory where you don't have sensitive files..)? If you can reproduce it might be helpful to run the command like `composer create-project -vvv laravel/laravel package-maker` and share the full debug output.
