### ISSUE TITLE
Composer Automatically Crashes

### ISSUE THREAD

**Issue by zedd9165** [composer/composer#9839]
Hello Everyone, 

I had a perfectly running composer installed with launcher on my drupal project directory. It was working fine until I came back after a month's break to start working on my project again. To my surprise, when I open the composer from the directory where it is installed, the command prompt opens but automatically kills (Blink some texts & closes) it self in a second. 

Could someone please advise me what could be going wrong in here.

**Comment by stof** [comment]
I have no idea what your mean by `when I open composer from the directory`. Composer is not something you can open. It is a CLI executable.

**Comment by Seldaek** [comment]
Yeah that sounds like you're running composer without any command which would make it simply output help and close itself.. Definitely not how you're supposed to run it. You should open a terminal and then run composer as a command.
