### ISSUE TITLE
vendor/bin/*bat files when using WSL

### ISSUE THREAD

**Issue by staabm** [composer/composer#9841]
when using composer in WSL on windows, the composer cli does not generate *.bat files under vendor/bin/.

phpstorm on the other hand requires e.g. a phpstan.bat file when configuring the integration within phpstorm (.phar and other files are considered invalid).

would it be possible to either create the .bat files all the time (even on non-windows platform), or e.g. feature detect WSL and generate the *.bat files additionally in this case?

![grafik](https://user-images.githubusercontent.com/120441/115553267-81767c80-a2ad-11eb-8567-05e943a5d58a.png)

![grafik](https://user-images.githubusercontent.com/120441/115553282-850a0380-a2ad-11eb-9e00-3a0f6b71577c.png)

![grafik](https://user-images.githubusercontent.com/120441/115553343-97843d00-a2ad-11eb-9592-88347e2dc3d1.png)

tested on phpstorm 2021.1.1

**Comment by stof** [comment]
is there an easy way to feature-detect WSL ?

**Comment by Seldaek** [comment]
You can set `composer config -g bin-compat full` to always generate .bat files https://getcomposer.org/doc/06-config.md#bin-compat

**Comment by Seldaek** [comment]
That said, I believe it's pretty easy to detect WSL so maybe we can do this automatically. Reopening.
