### ISSUE TITLE
Link constructor contains invalid psalm annotation

### ISSUE THREAD

**Issue by boesing** [composer/composer#9844]
Hi, I am working on a plugin and I am instantiating the `Composer\Package\Link` instance.
That class in its latest version (`2.0.12`) contains an invalid `@psalm-param` annotation for the `description` parameter.

```
* @phpstan-param self::TYPE_* $description
```

Same for the property.
The default `__construct` value already has an invalid value, so I guess the whole annotation is just wrong?

If the annotation is correct, the default value would be invalid.

**Comment by stof** [comment]
Indeed, this has been fixed in master but not in the 2.0 branch.

**Comment by Seldaek** [comment]
Yeah I'm unlikely to backport this, you can test your plugin against 2.1-dev for now perhaps if this is really important?
