### ISSUE TITLE
Cannot update to dev version with alias

### ISSUE THREAD

**Issue by InvisibleSmiley** [composer/composer#9845]
Pre-conditions:
- libs my-lib and other-lib exist and are set up correctly (composer.json etc.)
- other-lib version v6.10 has been tagged
- my-lib version v6.4.0 has been tagged; neither v6.99, v6.99.0, 6.99 nor 6.99.0 have been tagged
- branch "fix-stubs" exists in my-lib and is set up correctly (composer.json etc.)
- root project exists and is set up correctly (composer.json, composer.lock etc.)
  - composer.lock contains other/lib version v6.10.0
  - composer.lock contains my/lib version v6.4.0

The project is proprietary so I cannot share the full composer.json etc. but it references dozens of proprietary libraries.

Root project `composer.json` (extract):

```json
{
  "repositories": [
    {
      "type": "vcs",
      "url": "ssh://git@mybitbucket:1234/myproject/my-lib.git"
    },
    {
      "type": "vcs",
      "url": "ssh://git@mybitbucket:1234/myproject/other-lib.git"
    }
  ],
  "require": {
    "other/lib": "^6.10",
    "my/lib": "dev-fix-stubs as v6.99"
  }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.12
PHP version: 7.4.15
PHP binary path: C:\php74\php.exe
OpenSSL version: OpenSSL 1.1.1i  8 Dec 2020
cURL version: 7.70.0 libz 1.2.11 ssl OpenSSL/1.1.1i
zip: extension present, unzip present
```

When I run this command:

```
composer u my/lib
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - other/lib is locked to version v6.10.0 and an update of this package was not requested.
    - my/lib dev-fix-stubs conflicts with my/lib v6.99.
    - other/lib v6.10.0 requires my/lib ^6.2 -> satisfiable by my/lib[v6.99 (alias of dev-fix-stubs)].
    - Root composer.json requires my/lib dev-fix-stubs as v6.99 -> satisfiable by my/lib[dev-fix-stubs].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

Adding -W doesn't help, and I don't want to update `other/lib`.

I'm especially confused by the `my/lib dev-fix-stubs conflicts with my/lib v6.99` part which suggests Composer thinks the lib conflicts with itself.

And I expected this to happen:
Just works

Also checked with Composer 2.0, same result.
Also checked with Composer 1.10.21, almost same result (mentions other libs than other/lib that also depend on my/lib).

Maybe Composer has a problem with the specific branch name, I don't know. :-/

**Comment by InvisibleSmiley** [comment]
FTR: composer.json requires `"my/lib": "^6.3"` initially. The new value `"dev-fix-stubs as v6.99"` was entered by me manually.

**Comment by stof** [comment]
can you show the composer.json of `my/lib` `dev-fix-stubs` ?

**Comment by InvisibleSmiley** [comment]
Removed non-essential stuff like authors and scripts:
```
{
  "name": "my/lib",
  "type": "library",
  "description": "My Lib",
  "license": "proprietary",
  "require": {
    "php": "^7.4"
  },
  "replace": {
    "my/oldlib": "*"
  },
  "conflict": {
    "my/oldlib": "*"
  },
  "require-dev": {
    "ergebnis/composer-normalize": "^2.0",
    "phpunit/phpunit": "^9.0",
    "phpstan/phpstan": "^0.12.71"
  },
  "suggest": {
    "ext-intl": "Used to check emails"
  },
  "autoload": {
    "psr-4": {
      "my\\": "src"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "my\\Test\\": "tests",
      "my\\stubs\\": "stubs"
    }
  }
}
```

**Comment by stof** [comment]
@InvisibleSmiley Can you try removing the `conflict` rule ? I think it might be the cause of the issue. You are conflicting with all versions of `my/oldlib`, but as you are also replacing it, it might be the source of the weird conflict you see.

This conflict rule is also unnecessary. A `replace` rule already forbids installing the replaced package and the replacer package at the same time (that's the difference between `replace` and `provide`)

**Comment by InvisibleSmiley** [comment]
@stof will check that early next week, thanks for the pointer!

**Comment by InvisibleSmiley** [comment]
Indeed `conflict` in my/lib caused the issue so I can "fix" it. Thanks!

So what can we do to help other people not running into this problem? Some ideas:
1. Adapt `conflict` and/or `replace` documentation
2. Let Composer output a more meaningful error/warning message when this case occurs
3. Let Composer handle this "correctly" and ignore the conflict that is not really a conflict

**Comment by Seldaek** [comment]
This is clearly a misuse of conflict as if you replace it you don't need to conflict, the replace already will conflict. I'll see if we can make that clearer in the docs though.

As for the weird output, it is due to an edge case here whereas by defining an alias, you end up with an alias package and the original package which conflicts against itself. I tend to agree this should in theory not fail, but I'm not sure how easy it'd be to fix, nor whether it's really worth it given this is really an edge case.

Leaving open for now until we can investigate further.

**Comment by stof** [comment]
One thing that could improve things here would be to make `composer validate` report warnings when you have a `conflict` rule and a `replace` rule for the same package name, as there is no legitimate need for it.
