### ISSUE TITLE
Composer installing dev-master instead of my version constraint.

### ISSUE THREAD

**Issue by b-hayes** [composer/composer#9851]
My `composer.json`:

```json
"b-hayes/cli": ">=0.0.1",
```

Output of `composer diagnose`:

```
  - Downloading b-hayes/cli (dev-master fc228d7)
  - Installing b-hayes/cli (dev-master fc228d7): Extracting archive
```

When I run this command: 

```
composer clear-cache
rm composer.lock
composer install
```

I get the following output: 

```
  - Downloading b-hayes/cli (dev-master fc228d7)
  - Installing b-hayes/cli (dev-master fc228d7): Extracting archive
```

And I expected this to happen:

I'm expecting a tagged version to be installed. I don't actually care if it's the latest version but it MUST be a tagged version as the latest version may not be on the master branch at all.

I do have `"minimum-stability": "dev",` but shouldn't version constraints still be honoured?

**Comment by stof** [comment]
Well, `dev-master` matches your version constraint (which has no upper bound). So it is still honored.

If you want to use a stable release, either change your minimum stability, use `prefer-stable: true` or change your constraint to have an upper bound excluding dev-master (which is considered to be `9999999-dev` when it does not have a branch alias, and so higher than your release)

**Comment by b-hayes** [comment]
Cool thanks for the workaround.
But it's a minimum, not maximum stability, so it should pick a stable release if there is one right?
None of the other libraries defaults to dev-master with this setting so why does this one?

**Comment by kubawerlos** [comment]
I'll just drop this: ![https://thephp.cc/presentations/2019-international-php-conference-spring-edition-phpunit-best-practices/slide-17.jpg](https://thephp.cc/presentations/2019-international-php-conference-spring-edition-phpunit-best-practices/slide-17.jpg)

Source:
https://thephp.cc/presentations/2019-international-php-conference-spring-edition-phpunit-best-practices/slide-17.jpg
https://thephp.cc/dates/2019/06/international-php-conference-spring-edition/phpunit-best-practices (slide 18)

**Comment by stof** [comment]
> Cool thanks for the workaround.
> But it's a minimum, not maximum stability, so it should pick a stable release if there is one right?
> None of the other libraries defaults to dev-master with this setting so why does this one?

The minimum-stability setting is about removing some candidates from the list of versions to select from (any version that is not stable enough is filtered out). Which version is selected among the candidates is not affected by that. the default composer behavior is to select the highest compatible version (which will often be a dev version if they are allowed), unless you change the algorithm with `--prefer-lowest` or `--prefer-stable`

**Comment by b-hayes** [comment]
Guess it comes down to me not understanding this: https://getcomposer.org/doc/04-schema.md#minimum-stability
`All versions of each package are checked for stability, and those that are less stable than the minimum-stability setting will be ignored when resolving your project dependencies.`

I interpret it as "allow unstable" instead of "use the unstable one even if it is below the requirements".

The tagged version is newer than dev-master and the minimum version constraint. dev-master was far behind v0.0.1 and I required at least that version.

Forgive me If I'm just not getting it.
Makes sense to me if I require v2 or higher than it should follow that even if unstable versions are allowed.

**Comment by stof** [comment]
> The tagged version is newer than dev-master

`newer` is about the time of releases. Composer does not select the newest version. It selects the *highest* version. And that means sorting based on version numbers.

**Comment by stof** [comment]
And `9999999-dev` definitely matches the rule of "v2 or higher"

**Comment by b-hayes** [comment]
Ok, so dev master is considered v9999999 and will always be higher?

**Comment by stof** [comment]
@b-hayes the default branch of the repository is considered v9999999, unless it has a branch alias (in which case, the branch alias defines how it is considered)

**Comment by b-hayes** [comment]
Right ok. Thanks for taking the time to explain it to me.
