### ISSUE TITLE
J'arrive pas à installé des nouveaux bundle, à chaque fois whiteoctober/breadcrumbs-bundle désinstalle automatiquement,  

### ISSUE THREAD

**Issue by manjaryMahasoaRasolondraibe** [composer/composer#9853]
composer require endroid/qr-code:~3.5.9 --ignore-platform-reqs
The "symfony/flex" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
./composer.json has been updated
The "symfony/flex" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Running composer update endroid/qr-code
Loading composer repositories with package information
Updating dependencies
Lock file operations: 6 installs, 0 updates, 1 removal
  - Removing whiteoctober/breadcrumbs-bundle (1.4.5)
  - Locking bacon/bacon-qr-code (2.0.3)
  - Locking dasprid/enum (1.0.3)
  - Locking endroid/qr-code (3.5.9)
  - Locking endroid/qrcode (3.9.7)
  - Locking khanamiryan/qrcode-detector-decoder (1.0.5)
  - Locking setasign/fpdf (1.8.3)
Writing lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
3 package suggestions were added by new dependencies, use `composer suggest` to see details.
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package endroid/qrcode is abandoned, you should avoid using it. Use endroid/qr-code instead.
Package twig/extensions is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
composer/package-versions-deprecated: You should rely on the Composer\InstalledVersions class instead of this package as you are using Composer 2. You can require composer-runtime-api:^2 to ensure it is present.1 package you are using is looking for funding.
Use the `composer fund` command to find out more!
> symfony-cmd
'symfony-cmd' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
Script symfony-cmd handling the auto-scripts event returned with error code 1
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by manjaryMahasoaRasolondraibe** [comment]
PS: je peux changer de version de symfony

**Comment by stof** [comment]
The error message provides the answer: your symfony/flex version is too old to support composer 2.

**Comment by manjaryMahasoaRasolondraibe** [comment]
Merci pour la réponse donc je dois downgrade mon symfony? car je suis sur un projet où je dois pas upgrade le symfony/flex

**Comment by stof** [comment]
the issue is not the version of Symfony. It is the version of Composer. If you cannot upgrade symfony/flex to an uptodate version (why that?) you will need to stay on composer 1.x

**Comment by manjaryMahasoaRasolondraibe** [comment]
Je mets juste à jour des module dans un ancien projet et si je mets à jour le symfony/flex, y a des erreurs du coup je dois rester sur composer d'avant qui est 1.6.3

**Comment by manjaryMahasoaRasolondraibe** [comment]
Merci beaucoup pour l'aide, ça marche très bien maintenant..
