### ISSUE TITLE
Remove HgBitbucketDriver and make GitBitbucketDriver match all bitbucket URLs

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#9856]
Bitbucket has completely removed mercurial support at this point so we can simplify our code a little https://bitbucket.org/blog/sunsetting-mercurial-support-in-bitbucket

**Comment by raphaeldealmeida** [comment]
I create a PR, but it breaks BC.
To me this feels right, so merge into an appropriate release.

**Comment by raphaeldealmeida** [comment]
I created an alias from `git-bitbucket` to `bitbucket` reducing BC break.
Please review my PR
