### ISSUE TITLE
php 8.* incompatible with your PHP version

### ISSUE THREAD

**Issue by donbidon** [composer/composer#9862]
`composer require --dev phpunit/phpunit ^9`
According  to phpunit composer.json >= php 7.4 required.

Output of `composer diagnose`:
```
[InvalidArgumentException]
Package phpunit/phpunit at version 9 has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version
```
Win10/PHP 8.0.1/Composer 2.0.10

**Comment by stof** [comment]
please don't truncate the message

**Comment by donbidon** [comment]
> please don't truncate the message
sorry, fixed.

**Comment by donbidon** [comment]
Same problem can be reproduced at WSL2/Ubuntu 20.04.1 LTS (GNU/Linux 5.4.72-microsoft-standard-WSL2 x86_64)
But composer version isn't up to date (1.10.1).

**Comment by Seldaek** [comment]
I can not reproduce. Please follow the issue report template and give us all the info we ask if you want help. There isn't enough info here.

**Comment by donbidon** [comment]
Oops,
`composer require --dev phpunit/phpunit "^9"` works fine, close issue, please.

**Comment by Seldaek** [comment]
Ah I see, I missed the fact it required version `9` without ^ in your example. Are you running this in cmd.exe or what terminal are you using?
