### ISSUE TITLE
composer-*.phar is returning internal server error

### ISSUE THREAD

**Issue by ostrolucky** [composer/composer#9865]
```
$ curl -I https://getcomposer.org/composer-2.phar
HTTP/2 500
server: nginx
content-type: text/html; charset=UTF-8
cache-control: no-cache, private
date: Mon, 03 May 2021 14:58:50 GMT
strict-transport-security: max-age=31104000
```

Our Vagrant provisioning fails for this reason. We have various teams, some teams using still composer 1.x, for those we use composer-1.phar url, for all the others, composer-2.phar url.

**Comment by emberdyn** [comment]
https://getcomposer.org/composer-1.phar 

Is returning the same.  is there an outage on the composer server?

**Comment by stof** [comment]
should be fixed by https://github.com/composer/getcomposer.org/pull/187

**Comment by ostrolucky** [comment]
Meanwhile, these do work https://getcomposer.org/download/latest-2.x/composer.phar

**Comment by stof** [comment]
should be closed as the fix is not deployed.

**Comment by ostrolucky** [comment]
thx
