### ISSUE TITLE
InstalledVersions is static and thus global

### ISSUE THREAD

**Issue by helhum** [composer/composer#9868]
The Composer class loader is designed to be a unique instance, bound to a specific autoload.php that gets included. This is great for scenarios and use cases, where multiple autoload.php files from different Composer installations are included in a single process.

`InstalledVersions` however is a static class. This means that for the above use case it is impossible to get the package versions of a specific Composer installation, but only for the one that has the highest priority in PHP autoloading.

Is it worth considering such use case and therefore investing time to think about how this can be achieved (not trivial unfortunately)? If so, I'd try to come up with a suggestion.

**Comment by Seldaek** [comment]
I'm afraid this is not something we want to complicate even further. If you are interested in the data of a specific autoloader instance you can include the `installed.php` data source for that vendor dir, and extract info you need from there yourself IMO.

**Comment by stof** [comment]
Well, if you include multiple autoload.php files, your process has access to all of them, so it is not unexpected to see installed versions for all of them.

**Comment by helhum** [comment]
> Well, if you include multiple autoload.php files, your process has access to all of them, so it is not unexpected to see installed versions for all of them.

But this won't be the case. The `InstalledVersions` class that is loaded first "wins", so only exactly one set of installed packages will be available

**Comment by helhum** [comment]
> If you are interested in the data of a specific autoloader instance you can include the installed.php data source for that vendor dir

I wasn't aware this also exists. This should totally cover such edge use cases. Thanks!

**Comment by Seldaek** [comment]
> The InstalledVersions class that is loaded first "wins", so only exactly one set of installed packages will be available

That is not true anymore as of 2.0.9 (https://github.com/composer/composer/releases/tag/2.0.9) we load all installed versions from all autoloaders. So make sure you check latest Composer before building an unnecessary hack around it.

**Comment by helhum** [comment]
> That is not true anymore as of 2.0.9 

Ah, I indeed missed that change. Thanks again!
