### ISSUE TITLE
Composer needs to restart in order to take in Azure Functions npm tools if AF is installed using the MSI file. Expect no need to close and restart Composer.

### ISSUE THREAD

**Issue by hcyang** [composer/composer#9870]
My `composer.json`:

```json
...replace me...
```

Output of `composer diagnose`:

```
...replace me...
```

When I run this command: 

```
...replace me...
```

I get the following output: 

```
...replace me...
```

And I expected this to happen:

**Comment by xabbuh** [comment]
What do you mean with restarting Composer? Are you sure that you are talking about the dependency manager for PHP packages?
