### ISSUE TITLE
svn:// protocol is always considered insecure, even if encrypted connections are enforced by server

### ISSUE THREAD

**Issue by njandreasson** [composer/composer#9872]
Adding a Subversion repository with svn:// scheme is always considered insecure by Composer:

https://github.com/composer/composer/blob/6587715d0f8cae0cd39073b3bc5f018d0e6b84fe/src/Composer/Config.php#L475-L480

[Since Subversion 1.5](https://subversion.apache.org/docs/release-notes/1.5.html#cyrus-sasl) (released more than 10 years ago!) the svn:// protocol can be encrypted using Cyrus SASL (http://svnbook.red-bean.com/nightly/en/svn.serverconfig.svnserve.html#svn.serverconfig.svnserve.sasl) but Composer doesn't seem to consider this. In svnserve, which can be used to host a subversion repository, it is possible (and desirable) to enforce clients to encrypt connections by setting e.g. `min-encryption = 128` to require 128 bit encryption (as detailed in section 6 on [Cyrus SASL + Subversion documentation](https://svn.apache.org/repos/asf/subversion/trunk/notes/sasl.txt)).
The only way to access an encrypted Subversion repository from Composer via svn:// is to set "secure-http: false" in config which feels like very bad security practice as it affects all repositories and will also continue generating warnings that connections are insecure - even if they're not.

I've been looking for a way to reliably detect if a connection to a svn:// repo is encrypted in a version agnostic way but have not found a perfect solution. Without that, I'd at least consider it reasonable to add some kind of repository config that would let me tell Composer that a svn:// repository is secure without having to allow unencrypted connections for ALL repositories.

I'd be happy to contribute with what's needed to achieve this if anyone can just give me a pointer on how to best go about it.

Thanks for a great library!

**Comment by Seldaek** [comment]
I guess we could add a secure-svn-domains array to Config in which you can add hostnames of svn servers which can be trusted.. It could then be checked in prohibitUrlByConfig against the URL's hostname.

**Comment by njandreasson** [comment]
Thanks @Seldaek . I've reviewed the source and that sounds like a perfect plan to me.
It should be said that I researched whether there was a way to auto-detect if an svn connection is encrypted or by default require it to be but unfortunately I did not find any reasonable way to achieve that (otherwise that'd of course be the optimal solution as it would not require any additional configuration).

**Comment by Seldaek** [comment]
Alright please try it out and confirm it works for you with `composer self-update --snapshot` :)

**Comment by njandreasson** [comment]
> Alright please try it out and confirm it works for you with `composer self-update --snapshot` :)

Just tested and it works like a charm! Thanks lot - much appreciated!
