### ISSUE TITLE
Composer autoloads file twice, resulting in an error

### ISSUE THREAD

**Issue by marekdedic** [composer/composer#9882]
Hi, 
I am getting a Fatal error `Cannot declare class Sgdg\Vendor\Google_Service_Drive_DriveFile, because the name is already in use`. I tried to list a backtrace in the file where this class is declared and I got the following results

In my (composer) dependency, there is this line:

```php
if (\property_exists($this, $keyType) && \class_exists($this->{$keyType})) {
```
where `$this->{$keyType}` is `Google_Service_Drive_DriveFile`. This gets executed twice and both times composer `ClassLoader->loadClass` gets called. (I have no idea why it gets called the second time if it sucessfully loads the file the first time). This finds the class using PSR-4 and calls the function `includeFile` in the same file. This function includes the class both times, which causes the error.

Maybe using `include_once` in the `includeFile` function would fix this, but I don't understand the auto-loader to be sure...

Thanks

---

My `composer.json`:

```json
{
    "name": "skaut/google-drive-gallery",
    "description": "A WordPress gallery using Google Drive as file storage",
    "type": "wordpress-plugin",
    "keywords": [
        "WordPress",
        "WordPress plugin",
        "skaut",
        "Google Drive",
        "Google Drive gallery",
        "Image and video gallery from Google Drive",
        "Team drive",
        "Shared drive",
        "image gallery",
        "video gallery",
        "image and video gallery",
        "gallery from Google Drive",
        "gallery",
        "gallery plugin"
    ],
    "homepage": "https://wordpress.org/plugins/skaut-google-drive-gallery",
    "readme": "README.md",
    "license": "MIT",
    "authors": [
    {
        "name": "Marek Dědič",
        "email": "developer@dedic.eu"
    }
    ],
    "support": {
        "issues": "https://github.com/skaut/skaut-google-drive-gallery/issues",
        "wiki": "https://napoveda.skaut.cz/dobryweb/en-skaut-google-drive-gallery",
        "source": "https://github.com/skaut/skaut-google-drive-gallery",
        "docs": "https://napoveda.skaut.cz/dobryweb/en-skaut-google-drive-gallery"
    },
    "require": {
        "php": "^5.6 || ^7.0",
        "google/apiclient": "^2.8.3",
        "monolog/monolog": "^1.25",
        "guzzlehttp/guzzle": "^6.5.4",
        "paragonie/constant_time_encoding": "^1.0.4",
        "paragonie/random_compat": "^2.0.18",
        "guzzlehttp/promises": "^1.4",
        "symfony/polyfill-intl-idn": "^1.19.0 <1.20",
        "symfony/polyfill-intl-normalizer": "^1.19.0 <1.20",
        "symfony/polyfill-php70": "^1.19.0 <1.20",
        "symfony/polyfill-php72": "^1.19.0 <1.20"
    },
    "require-dev": {
        "squizlabs/php_codesniffer": "^3.0",
        "wp-coding-standards/wpcs": "^2.1",
        "phpcompatibility/phpcompatibility-wp": "^2.0",
        "phpmd/phpmd": "^2.6",
        "phan/phan": "^4.0",
        "phpunit/phpunit": "^7.5",
        "skaut/phan-wordpress-stubs": "^1.0.0",
        "symfony/polyfill-mbstring": "^1.20.0 <1.22",
        "humbug/php-scoper": "^0.15.0"
    }
}
```

Output of `composer diagnose`:

```
$ composer diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Composer version: 2.0.9
PHP version: 7.4.15
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1j  16 Feb 2021
cURL version: 7.74.0 libz 1.2.11 ssl OpenSSL/1.1.1k
zip: extension present, unzip present
```

When I run this command: Open a webpage containing composer loading dependencies

I get the following output:
```
Fatal error: Cannot declare class Sgdg\Vendor\Google_Service_Drive_DriveFile, because the name is already in use in /home/user/www/wp-content/plugins/skaut-google-drive-gallery/bundled/vendor/google/apiclient-services/src/Google/Service/Drive/DriveFile.php on line 21
```

And I expected this to happen:

No fatal error.

**Comment by stof** [comment]
Well, the class being declared twice is `Sgdg\Vendor\Google_Service_Drive_DriveFile` while you say that your code is doing `class_exists('Google_Service_Drive_DriveFile')`. This looks like a bad autoloader configuration to me if you tell composer to look in a file containing the `Sgdg\Vendor` namespace to find a class without this namespace.

**Comment by Seldaek** [comment]
That, and also invalid code looking up a class by the wrong name.. and the two mistakes together leading to it autoloading the same file twice. That sounds like the most likely explanation here.

**Comment by marekdedic** [comment]
Thanks, it turns out that's exactly correct. The interplay between composer PSR-0 autoloading and php-scoper caused the wrong class to be autoloaded and I forgot `class_exists` does not respect current namespace... :)
