### ISSUE TITLE
Get parameters from composer.json file

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [composer/composer#9884]
My `composer.json`:

```json
{
    "name": "xxx/yyy",
    "version": "0.1.10  ",
    "license": "MIT"
}

```

Is it possible in some way to get parameters from composer file?
As `InstalledVersions` I am searching for a way to get other parameters not only the installed versions for example the parameter `version` or `license`.

Is it possible?
If not, is the responsibility of this package? If it is the responsibility of this package can I try to make a pull request?

**Comment by Seldaek** [comment]
Sorry but no, we are not going to make the full package data accessible via InstalledVersions. You can load the vendor/composer/installed.json file if you're interested in more information about installed packages.
