### ISSUE TITLE
Can not run gh-pages through scripts

### ISSUE THREAD

**Issue by whizsid** [composer/composer#9886]
I have a PHP project and I am trying to deploy it's documentation using gh-pages. This my composer.json file:-

```json
{
    // Other properties
    "scripts": {
        // Other scripts
        "gh-pages": "gh-pages --repo https://github.com/myorg/myrepo --dist doc/build --branch gh-pages"
    }
}
```
But when I run `composer run gh-pages`, I am getting this error:-
```
> gh-pages --repo https://github.com/myorg/myrepo --dist doc/build --branch gh-pages
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/myorg/myrepo/'

Script gh-pages --repo https://github.com/myorg/myrepo --dist doc/build --branch gh-pages handling the gh-pages event returned with error code 1

```
The script not asked for my credentials.

But  not faced any kind of errors after I manually typed and ran the command in terminal.

This is my auth.json content (`composer config --global --editor --auth`):-
```json
{
    "bitbucket-oauth": {},
    "github-oauth": {},
    "gitlab-oauth": {},
    "gitlab-token": {},
    "http-basic": {},
    "bearer": {}
}

```

# Steps to reproduce

1. Download and install the composer. https://getcomposer.org/download/
2. Install the gh-pages at global scope. `npm install --global gh-pages`
3. Create a minimum `composer.json` file in the working directory. 
```json
{
    "name": "myorg/myrepo",
    "description": "Description",
    "type": "library",
    "license": "MIT",
    "minimum-stability": "dev",
    "scripts": {
        "gh-pages": "gh-pages --repo https://github.com/myorg/myrepo --dist doc --branch gh-pages"
    }
}
```
4. Create a basic html file in the `doc` directory.
```html
# doc/index.html

<html>
    <body>Test</body>
</html>
```
5. Run the script. `composer run gh-pages`

## Environment

```
$ composer --version
Composer version 2.0.11 2021-02-24 14:57:23
$ gh-pages --version
3.1.0
$ uname -a
Linux archlinux 5.11.1-arch1-1 #1 SMP PREEMPT Tue, 23 Feb 2021 14:05:30 +0000 x86_64 GNU/Linux
$ php --version
PHP 8.0.2 (cli) (built: Feb  2 2021 18:26:02) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
$ node --version
v15.10.0
```

**Comment by Seldaek** [comment]
Note that "scripts" is not meant to be a full blown shell environment, and you can also create a simple shell script and run that standalone instead of abusing the composer.json.

I'm not sure why the script did not ask for credentials.. it should be running interactive by default.
