### ISSUE TITLE
How to remove a package via Composer?

### ISSUE THREAD

**Issue by richb201** [composer/composer#9890]
I have been trying to install a package but it is failing. I'd like to completely remove it via Composer and install it again, very carefully by first inspecting the install script. How can I do this?

**Comment by Seldaek** [comment]
You can run `composer remove foo/bar && composer require foo/bar`

**Comment by richb201** [comment]
a little fast on the close trigger? I think part of the reason I have to
keep asking these idiotic questions is that the answers are so cryptic. I
have a directory called /opt/docker-substantiator2/. There is no
subdirectory called sendpulse. Thus of course composer remove
sendpulse/rest-api will fail just as does composer require
sendpulse/rest-api when I try to install. The vendor (sendpulse) has told
me:
"No, there is no need to install or create something previously all you
need is to run
composer require sendpulse/rest-api in any way how it will be more suitable
for you.."

So sendpulse support and composer help are saying two different, cryptic
things. There must be some file where composer place the directory where it
thinks sendpulse is? I am thinking that sendpulse set up the install for
their api with composer wrong. I am just trying to install the API!

Thanks for your help.

**Comment by stof** [comment]
`composer require sendpulse/rest-api` does **not** require having a subdirectory called `sendpulse`.

I think you are confusing how composer works.
when you run `composer require sendpulse/rest-api` in the root of **your project**, this will modify the composer.json of **your project** to add a requirement on `sendpulse/rest-api`. Then, when updating dependencies (which is done for you by `composer require` by default), the package will be installed  (and the default installation path will be a `vendor/sendpulse/rest-api` subfolder inside your project directory, as that's where composer install things by default).

**Comment by richb201** [comment]
Cool, thanks! I just ran it again and got this output from the require. Can
you just confirm  that this is what I should see (from the composer POV)?
***@***.***XPS-13-9370:/opt/docker-substantiator2$ composer require
sendpulse/rest-api
Using version ^1.0 for sendpulse/rest-api
./composer.json has been updated
Running composer update sendpulse/rest-api
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading sendpulse/rest-api (1.0.22 => 1.0.23)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downloading sendpulse/rest-api (1.0.23)
  - Upgrading sendpulse/rest-api (1.0.22 => 1.0.23): Extracting archive
Generating autoload files

I am still getting an error when I try to initialize their API, but if you
tell me the install was correct, then it is clearly a problem with their

**Comment by stof** [comment]
well, if you have an issue when initializing their API and you don't give the error message, it is unlikely that you will get relevant help.

But anyway, composer is not failing here. It managed to install the package.

**Comment by richb201** [comment]
Ok, thanks. At least I know where to look for sure. Thank you.
The error is that composer installed
/vendor/sendpulse/rest-api/ApiClient.php and their code is looking for
"Class 'Sendpulse\RestApi\ApiClient' , which will ne er ever work because
the paths are not the same. This is an error internal to their API, not my
tiny bit of code.

**Comment by stof** [comment]
`Sendpulse\RestApi\ApiClient` is a class name, not a path. And the config of their package defines the right autoloading config AFAICT.

**Comment by richb201** [comment]
Thanks! Any idea why I am getting that error when trying to initialize the
api?
