### ISSUE TITLE
composer run-script ignores interactions / confirmations

### ISSUE THREAD

**Issue by crtl** [composer/composer#9891]
When im running `composer gcp:deploy:dev` the script is executed but I cannot confirm anything.
When you deploy to GCP App Engine you have to confirm first before you deploy but `run-script` just skips it even though I have ***not** passed `--no-interaction` flag.
The confirmation is shown in the console output but it gets just confirmed without me doing anything.

Using `npm run` with the same environment produces the expected result therefore I dont think its an issue with GCP tools.

My `composer.json`:

```json
{
    ...
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ],
        "gcp:deploy:dev": "gcloud app deploy app.yaml --project gcp-project-id"
    },
    ...
}

```

**Comment by Seldaek** [comment]
See https://github.com/composer/composer/issues/9886#issuecomment-842598266
