### ISSUE TITLE
I can't set up laravel with Composer! Error: curl error 60 SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by MuzafferBYRKTR** [composer/composer#9894]
Although I have tried many solutions, I cannot install laravel.I was also getting a certificate error when installing a resource with npm today.The problem may have been caused directly by windows' SSL certificate, but I could not find a solution at all.I followed and did all the ways like php.ini, cacert.pem, but I still didn't succeed.

I really need help, I've been dealing with this problem for days.

```
Error: curl error 60 SSL certificate problem: unable to get local issuer certificate
```

![image](https://user-images.githubusercontent.com/53446676/118882175-90783b00-b8fc-11eb-95a0-3fde10f8f343.png)

**Comment by Seldaek** [comment]
It looks like you have SSL disabled, not sure because you did not provide us all the info we ask for (output of `composer diagnose` would be interesting..) but I would recommend using a modern PHP version with openssl extension enabled, and then modern Composer should work fine.

**Comment by Seldaek** [comment]
Can you run it with `composer diagnose -vvv`? It should show something like `Checked CA file...` early on which should indicate which file it used as a certificate authority. I believe you have a corrupt CA file somehow if it can not authenticate our SSL cert.

**Comment by MuzafferBYRKTR** [comment]
> Can you run it with `composer diagnose -vvv`? It should show something like `Checked CA file...` early on which should indicate which file it used as a certificate authority. I believe you have a corrupt CA file somehow if it can not authenticate our SSL cert.

At first I asked for my update when I ran it and I updated it with ```composer self-update```. Then, when I ran ```composer diagnose -vvv``` the following information came in.And I saw the curl error 60 again.

```
PHP Warning:  Module 'openssl' already loaded in Unknown on line 0

Warning: Module 'openssl' already loaded in Unknown on line 0
Loading config file C:/Users/Muzaffer/AppData/Roaming/Composer/config.json
Loading config file C:/Users/Muzaffer/AppData/Roaming/Composer/auth.json
Reading C:/Users/Muzaffer/AppData/Roaming/Composer/composer.json (C:\Users\Muzaffer\AppData\Roaming\Composer\composer.json)
Loading config file C:/Users/Muzaffer/AppData/Roaming/Composer/config.json
Loading config file C:/Users/Muzaffer/AppData/Roaming/Composer/auth.json
Loading config file C:/Users/Muzaffer/AppData/Roaming/Composer/composer.json (C:\Users\Muzaffer\AppData\Roaming\Composer\composer.json)
Loading config file C:\Users\Muzaffer\AppData\Roaming\Composer/auth.json
Reading C:\Users\Muzaffer\AppData\Roaming\Composer/auth.json (C:\Users\Muzaffer\AppData\Roaming\Composer\auth.json)
You are running Composer with SSL/TLS protection disabled.
Executing command (C:/Users/Muzaffer/AppData/Roaming/Composer): git branch -a --no-color --no-abbrev -v
Executing command (C:/Users/Muzaffer/AppData/Roaming/Composer): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (C:/Users/Muzaffer/AppData/Roaming/Composer): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (C:/Users/Muzaffer/AppData/Roaming/Composer): hg branch
Executing command (C:/Users/Muzaffer/AppData/Roaming/Composer): fossil branch list
Executing command (C:/Users/Muzaffer/AppData/Roaming/Composer): fossil tag list
Executing command (C:/Users/Muzaffer/AppData/Roaming/Composer): svn info --xml
Reading C:/Users/Muzaffer/AppData/Roaming/Composer/composer.json (C:\Users\Muzaffer\AppData\Roaming\Composer\composer.json)
Loading config file C:/Users/Muzaffer/AppData/Roaming/Composer/config.json
Loading config file C:/Users/Muzaffer/AppData/Roaming/Composer/auth.json
Loading config file C:/Users/Muzaffer/AppData/Roaming/Composer/composer.json (C:\Users\Muzaffer\AppData\Roaming\Composer\composer.json)
Loading config file C:\Users\Muzaffer\AppData\Roaming\Composer/auth.json
Reading C:\Users\Muzaffer\AppData\Roaming\Composer/auth.json (C:\Users\Muzaffer\AppData\Roaming\Composer\auth.json)
Running 2.0.14 (2021-05-21 17:03:37) with PHP 7.4.16 on Windows NT / 10.0
Loading config file C:/Users/Muzaffer/AppData/Roaming/Composer/config.json
Loading config file C:/Users/Muzaffer/AppData/Roaming/Composer/auth.json
Reading C:/Users/Muzaffer/AppData/Roaming/Composer/composer.json (C:\Users\Muzaffer\AppData\Roaming\Composer\composer.json)
Loading config file C:/Users/Muzaffer/AppData/Roaming/Composer/config.json
Loading config file C:/Users/Muzaffer/AppData/Roaming/Composer/auth.json
Loading config file C:/Users/Muzaffer/AppData/Roaming/Composer/composer.json (C:\Users\Muzaffer\AppData\Roaming\Composer\composer.json)
Loading config file C:\Users\Muzaffer\AppData\Roaming\Composer/auth.json
Reading C:\Users\Muzaffer\AppData\Roaming\Composer/auth.json (C:\Users\Muzaffer\AppData\Roaming\Composer\auth.json)
Executing command (C:/Users/Muzaffer/AppData/Roaming/Composer): git branch -a --no-color --no-abbrev -v
Executing command (C:/Users/Muzaffer/AppData/Roaming/Composer): git describe --exact-match --tags
Executing command (C:/Users/Muzaffer/AppData/Roaming/Composer): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (C:/Users/Muzaffer/AppData/Roaming/Composer): hg branch
Executing command (C:/Users/Muzaffer/AppData/Roaming/Composer): fossil branch list
Executing command (C:/Users/Muzaffer/AppData/Roaming/Composer): fossil tag list
Executing command (C:/Users/Muzaffer/AppData/Roaming/Composer): svn info --xml
Reading C:/Users/Muzaffer/AppData/Roaming/Composer/composer.json (C:\Users\Muzaffer\AppData\Roaming\Composer\composer.json)
Loading config file C:/Users/Muzaffer/AppData/Roaming/Composer/config.json
Loading config file C:/Users/Muzaffer/AppData/Roaming/Composer/auth.json
Loading config file C:/Users/Muzaffer/AppData/Roaming/Composer/composer.json (C:\Users\Muzaffer\AppData\Roaming\Composer\composer.json)
Loading config file C:\Users\Muzaffer\AppData\Roaming\Composer/auth.json
Reading C:\Users\Muzaffer\AppData\Roaming\Composer/auth.json (C:\Users\Muzaffer\AppData\Roaming\Composer\auth.json)
Checking platform settings: OK
Checking git settings: Executing command (CWD): git config color.ui
OK
Checking http connectivity to packagist: Downloading http://repo.packagist.org/packages.json
[200] http://repo.packagist.org/packages.json
OK
Checking https connectivity to packagist: Downloading https://repo.packagist.org/packages.json
FAIL
[Composer\Downloader\TransportException] curl error 60 while downloading https://repo.packagist.org/packages.json: SSL certificate problem: unable to get local issuer certificate
Composer is configured to disable SSL/TLS protection. This will leave remote HTTPS requests vulnerable to Man-In-The-Middle attacks.
Checking github.com rate limit: Downloading https://api.github.com/rate_limit
FAIL
[Composer\Downloader\TransportException] curl error 60 while downloading https://api.github.com/rate_limit: SSL certificate problem: unable to get local issuer certificate
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: Warning: Accessing getcomposer.org over http which is an insecure protocol.
Downloading http://getcomposer.org/versions
[200] http://getcomposer.org/versions
OK
Composer version: 2.0.14
PHP version: 7.4.16
PHP binary path: C:\xampp\php\php.exe
OpenSSL version: OpenSSL 1.1.1i  8 Dec 2020
cURL version: 7.70.0 libz 1.2.11 ssl OpenSSL/1.1.1i
zip: extension present, unzip not available
```

**Comment by stof** [comment]
If npm also has the problem, this definitely looks like an issue with the root CA store on your system rather than an issue with Composer.
Btw: it could also be an issue with a crappy antivirus software actually doing a MitM on the HTTPS connection. Check whether your Antivirus has a feature like "HTTPS protection" (the name varies by vendor) and tries disabling it.

**Comment by MuzafferBYRKTR** [comment]
> If npm also has the problem, this definitely looks like an issue with the root CA store on your system rather than an issue with Composer.
> Btw: it could also be an issue with a crappy antivirus software actually doing a MitM on the HTTPS connection. Check whether your Antivirus has a feature like "HTTPS protection" (the name varies by vendor) and tries disabling it.

The error may be on the computer in general. Because I also receive a certificate error in the Filezilla FTP program, I cannot contact the certificate.In general, there is definitely an error on windows. That's why I can't solve composer or npm.

**Comment by MuzafferBYRKTR** [comment]
I couldn't find the solution to the problem and didn't want to deal with it any more, so I reset the computer and the problem was solved.Thank you for your support. :)

**Comment by FelipeKreulich** [comment]
I has the same error, but i can't find a solution, but you dont make anything?

**Comment by TioSam989** [comment]
> I has the same error, but i can't find a solution, but you dont make anything?

Helo mate, have you already tried to restart you pc ?

**Comment by FelipeKreulich** [comment]
> > I has the same error, but i can't find a solution, but you dont make anything?
> 
> Helo mate, have you already tried to restart you pc ?

I have tried, but dosen't work for me. :(

**Comment by roeycohen** [comment]
to anyone who sees this: please make sure you don't have a VPN connected, some of these VPN block stuff.

**Comment by solomonts-git** [comment]
In my case it is due to anti-virus program Avast. make sure you disable it till you finish installing.

**Comment by Ali-Alabsi** [comment]
I have The Same Problem

**Comment by a3m-nix** [comment]
I tried disabling avast and everything worked fine

**Comment by AndreiTelteu** [comment]
> I tried disabling avast and everything worked fine

Thank you. Saved my day. I tried everything and avast was the issue.

**Comment by tkleinms** [comment]
Same solution for me: I tried disabling avast and everything worked fine.

**Comment by Seldaek** [comment]
So is everyone with avast problems on windows? And if so can I know which path it's installed in? So I maybe can add some hint in the output when we detect this curl error on windows and avast is installed.

**Comment by br3-mah** [comment]
Its always an Anti-virus blocking important thing - Poor product design by Avast

**Comment by dmisljen** [comment]
Had the same issue, on Windows and with Avast as the cause.

Mine is installed at the (I believe) default location: C:\Program Files\Avast Software\Avast

**Comment by Seldaek** [comment]
@dmisljen thanks, hopefully https://github.com/composer/composer/commit/6ba63dd29c58979d1e9fbfef6a68b77fbfbdf6b7 works

**Comment by umairgul** [comment]
I had the same problem and I had reinstall windows in frustration, the cause was Avast Antivirus, disabling was not the correct way to bypass curl SSL issue so I researched for a while and found the solution below when using Avast.

 Go to Settings, open Protection tab and then open Core Shields, now look for 'Configure shield settings:', in this section disable following check and you are good to go next time without disabling whole Avast thing.

![Image](https://github.com/user-attachments/assets/c5e06278-fa30-479c-8072-10065d5ac588)

**Comment by dozer1412131** [comment]
try to use linux instead

**Comment by DeniceVO** [comment]
> I have the same problem. Here is how i solved it: disable HTTPS scanning and QUIC/HTTP3 scanning options in the Norton home \ Settings\ Safe web and disabled NATV before install the composer.
> 
> ![Image](https://github.com/user-attachments/assets/30fda111-db2e-4313-a360-88083110945c)
> 
> After installation, active the Norton.

Thank you very much, your method works for me!

**Comment by alalm3i** [comment]
> I have the same problem. Here is how i solved it: disable HTTPS scanning and QUIC/HTTP3 scanning options in the Norton home \ Settings\ Safe web and disabled NATV before install the composer.
> 
> ![Image](https://github.com/user-attachments/assets/30fda111-db2e-4313-a360-88083110945c)
> 
> After installation, active the Norton.

Thank you very much. It resolve the issue 👍🏻 much appreciated

**Comment by SotoTomas** [comment]
> If npm also has the problem, this definitely looks like an issue with the root CA store on your system rather than an issue with Composer. Btw: it could also be an issue with a crappy antivirus software actually doing a MitM on the HTTPS connection. Check whether your Antivirus has a feature like "HTTPS protection" (the name varies by vendor) and tries disabling it.

Bro, i love you so much.

**Comment by alfatihart** [comment]
> I had the same problem and I had reinstall windows in frustration, the cause was Avast Antivirus, disabling was not the correct way to bypass curl SSL issue so I researched for a while and found the solution below when using Avast.
> 
> Go to Settings, open Protection tab and then open Core Shields, now look for 'Configure shield settings:', then open Web Shield, in this section disable following check and you are good to go next time without disabling whole Avast thing.
> 
> ![Image](https://github.com/user-attachments/assets/c5e06278-fa30-479c-8072-10065d5ac588)

thanks

**Comment by ndiepp** [comment]
> > I had the same problem and I had reinstall windows in frustration, the cause was Avast Antivirus, disabling was not the correct way to bypass curl SSL issue so I researched for a while and found the solution below when using Avast.
> > Go to Settings, open Protection tab and then open Core Shields, now look for 'Configure shield settings:', then open Web Shield, in this section disable following check and you are good to go next time without disabling whole Avast thing.
> > ![Image](https://github.com/user-attachments/assets/c5e06278-fa30-479c-8072-10065d5ac588)
> 
> This was the solution (after days wasted) but my Antivirus was AVG - under settings, basic protection, web shield, uncheck "Enable HTTPS scanning" - thanks you so much!

i love youuuuuuu <3

**Comment by vadineta** [comment]
> Tuve el mismo problema y tuve que reinstalar Windows por frustración, la causa fue Avast Antivirus, deshabilitarlo no era la forma correcta de evitar el problema de curl SSL, así que investigué un tiempo y encontré la siguiente solución al usar Avast.
> 
> Vaya a Configuración, abra la pestaña Protección y luego abra Core Shields, ahora busque 'Configurar ajustes de escudo:', luego abra Web Shield, en esta sección deshabilite la siguiente verificación y estará listo para la próxima vez sin deshabilitar todo el asunto de Avast.
> 
> ![Image](https://github.com/user-attachments/assets/c5e06278-fa30-479c-8072-10065d5ac588)

muchisimas gracias, estuve arto tiempo intentando solucionar este problema y era el antivirus

**Comment by yanker** [comment]
A mi me ha pasado lo mismo con el Avast, pero ya llevaba un tiempo pensando en quitarlo, pues con el antivirus de windows 11 va bastante bien así que desinstalado.

Gracias por toda la ayuda.

**Comment by zeeid** [comment]
> I have the same problem. Here is how i solved it: disable HTTPS scanning and QUIC/HTTP3 scanning options in the Norton home \ Settings\ Safe web and disabled NATV before install the composer.
> 
> ![Image](https://github.com/user-attachments/assets/30fda111-db2e-4313-a360-88083110945c)
> 
> After installation, active the Norton.

Thank you work

**Comment by sijuas** [comment]
> I have the same problem. Here is how i solved it: disable HTTPS scanning and QUIC/HTTP3 scanning options in the Norton home \ Settings\ Safe web and disabled NATV before install the composer.
> 
> ![Image](https://github.com/user-attachments/assets/30fda111-db2e-4313-a360-88083110945c)
> 
> After installation, active the Norton.

Thank you... you saved my day
