### ISSUE TITLE
Composer 2 will install dev package despite prefer-stable flag

### ISSUE THREAD

**Issue by webhdx** [composer/composer#9917]
While working on the project I noticed little confusing behavior. I'm using `minimum-stability: dev` with `prefer-stable: true`. 

Below `composer.json` is based on `symfony/website-skeleton`. 

```json
{
    "name": "webhdx/website-skeleton",
    "type": "project",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "php": ">=7.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "symfony/flex": "^1.11.0"
    },
    "flex-require": {
        "sensio/framework-extra-bundle": "^5.6.1",
        "symfony/asset": "*",
        "symfony/console": "*",
        "symfony/dotenv": "*",
        "symfony/expression-language": "*",
        "symfony/form": "*",
        "symfony/framework-bundle": "*",
        "symfony/http-client": "*",
        "symfony/intl": "*",
        "symfony/mailer": "*",
        "symfony/mime": "*",
        "symfony/monolog-bundle": "^3.1",
        "symfony/notifier": "*",
        "symfony/orm-pack": "*",
        "symfony/process": "*",
        "symfony/security-bundle": "*",
        "symfony/serializer-pack": "*",
        "symfony/string": "*",
        "symfony/translation": "*",
        "symfony/twig-pack": "*",
        "symfony/validator": "*",
        "symfony/web-link": "*",
        "symfony/yaml": "*"
    },
    "require-dev": {
    },
    "flex-require-dev": {
        "symfony/debug-pack": "*",
        "symfony/maker-bundle": "^1.26.1",
        "symfony/profiler-pack": "*",
        "symfony/test-pack": "*"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*"
    },
    "scripts": {
        "auto-scripts": [],
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": true,
            "require": "5.2.*"
        }
    }
}
```

Running `composer create-project webhdx/website-skeleton` will result in installing stable packages but one package is installed with `dev` stability:
`  - Locking doctrine/dbal (2.13.x-dev 2c19354)`

I started wondering why this happens and went through a few steps to figure it out:

```
➜ composer why-not doctrine/dbal:2.13.1
doctrine/dbal  2.13.1      requires          doctrine/cache (^1.0)
__root__       dev-master  does not require  doctrine/cache (but 2.0.3 is installed)
```

So it looks like `doctrine/cache` was installed in version 2 which blocks installing `doctrine/dbal 2.13.1`.

```
➜ composer why doctrine/cache
doctrine/dbal         2.13.x-dev  requires  doctrine/cache (^1.0|^2.0)
doctrine/orm          2.9.1       requires  doctrine/cache (^1.11|^2.0)
doctrine/persistence  2.2.1       requires  doctrine/cache (^1.11 || ^2.0)
```

To confirm that `doctrine/cache 1.11.3` and `doctrine/dbal 2.13.1` could be installed without any conflicts I ran:
```
➜ composer require doctrine/dbal:2.13.1 -w
./composer.json has been updated
Running composer update doctrine/dbal --with-dependencies
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 2 updates, 0 removals
  - Downgrading doctrine/cache (2.0.3 => 1.11.3)
  - Downgrading doctrine/dbal (2.13.x-dev 2c19354 => 2.13.1)
 (...)
``` 

As you can see these packages could easily be installed as stable.

So it's clear that Composer prioritized higher major version despite it making other packages install with `dev` stability. To me it's confusing when using `prefer-stable: true`.

Is it a bug or simply a side effect of how does the solver work?

**Comment by stof** [comment]
Well, `prefer-stable: true` impacts the selection of which version is preferred when making a decision on each package.

If composer made a choice for `doctrine/cache` before doing a choice on `doctrine/dbal`, it will select `doctrine/cache 2.0.3` (`prefer-stable` won't have any effect on the choice between 1.11.3 and 2.0.3 as they have the same stability). At the time of choosing `doctrine/dbal`, the 2.13.1 version is not a candidate anymore due to the previous choice.

Making `prefer-stable: true` mean "prefer a solver solution minimizing the number on non-stable versions" would be a lot more complex (and a lot slower), as this would involve finding multiple solutions to the solving problem to choose between them.

**Comment by Seldaek** [comment]
Right this can not be fixed. Use minimum-stability of stable if you are concerned about surprises, and flag the specific packages that you need to be installable in dev versions using the `@dev` notation, see also https://getcomposer.org/doc/04-schema.md#package-links
