### ISSUE TITLE
Could not find a version of package vincentle89/module-imageineonline-autocoupon matching your minimum-stability (alpha). Require it with an explicit version constraint allowing its desired stability     .

### ISSUE THREAD

**Issue by vincentle89** [composer/composer#9919]
Hi team

When I run this command: 

composer require vincentle89/module-imageineonline-autocoupon -vvv

I get the following output: 

![image](https://user-images.githubusercontent.com/49143689/119779929-6a056180-bef3-11eb-990b-1b0b0c2af5d1.png)

This is my GitHub repo: https://github.com/vincentle89/prodovo-module-autocoupon
As you observer that I created some release packages. Please advise me on how to resolve it.
We're programing on Magento that requires composer version 1, not 2. Please be noticed! Thank you very much.

**Comment by stof** [comment]
When using composer 1, there is a delay before releases become available on packagist.org. See https://blog.packagist.com/deprecating-composer-1-support/

**Comment by Seldaek** [comment]
Please also see https://gist.github.com/hostep/26de0bf2bb695eb3b6d51858c2e4562e for Magento / Composer 2 instructions.

**Comment by vincentle89** [comment]
Thanks, @Seldaek @stof, and guys
I will ask my clients to consider the upgrade of Composer 2. But that's difficult because a lot of 3rd extensions still required Composer 1. I think that it has to a period. 
Besides. I'm trying to get a package that I uploaded yesterday but it still informed the same error.
My command:
`composer require vincentle89/module-imageineonline-autocoupon -vvv`
![image](https://user-images.githubusercontent.com/49143689/119922574-447f6300-bf9a-11eb-9d55-aa32692015fe.png)
Could you please advise how to resolve it? Thank you very much.

**Comment by Seldaek** [comment]
The first step would be to read https://blog.packagist.com/deprecating-composer-1-support/ carefully which includes instructions.

**Comment by vincentle89** [comment]
Thank you @Seldaek I will try to switch to Composer 2 and pull it.

**Comment by DavaGordon** [comment]
@vincentle89 this module was rebranded i did send out an advisory to all people who had installed it. you can download the latest version using 

`composer require prodovo/module-autocoupon`
