### ISSUE TITLE
Tying package versions together with platform versions

### ISSUE THREAD

**Issue by mohs8421** [composer/composer#9921]
I want to support a php version range from php 7.3 to 8.0, but I want to use a library, which is incompatible to php 7.3 in the current version but incompatible to 8.0 in an older version.

My use case:
```json
        "lcobucci/jwt": "^3.4|^4",
        "php": ">=7.3 <8.1",
```
It does work by now in the way, that it always installs version ^3.4, but that version is not compatible to php 8.
What I would expect is to get a version 4 installation if called in a php 8 environment and a version 3.4 if called in a php 7.3 environment.
Interesting question on that case: what would be written to a composer.lock file for such a scenario?

**Comment by mohs8421** [comment]
> > It does work by now in the way, that it always installs version ^3.4, but that version is not compatible to php 8.
> > What I would expect is to get a version 4 installation if called in a php 8 environment and a version 3.4 if called in a php 7.3 environment.
> 
> this is not true. If you run `composer update` on a PHP 8 platform, you will get the version 4
Sorry, you are right, I might have confused a check with the other version here, now I tried that again and yes it did get version 4.
> 
> > Interesting question on that case: what would be written to a composer.lock file for such a scenario?
> 
> The lock file is generated for a given platform due to platform requirements impacting the selected versions (not that it might not only be PHP but also extensions).
> If you cannot have a solver solution working for both PHP 7 and PHP 8, you won't be able to have a single lock file for both.
Is there a way to handle multiple lock files? by a command line option perhaps? or would I need to juggle these around by renaming them according to my platform?

**Comment by stof** [comment]
> Is there a way to handle multiple lock files? by a command line option perhaps? or would I need to juggle these around by renaming them according to my platform?

composer itself does not have a way to do that. You will have to manage that at a higher level (with a script renaming/symlinking the right file before and after calling composer)

**Comment by Seldaek** [comment]
Really this looks like a huge mess. I guess your best bet would be to switch to require 7.4||8 so you can simply require lcobucci/jwt ^4. It sucks when a dependency of yours corners you into such a situation instead of keeping a broader PHP support range, but that's life.

**Comment by mohs8421** [comment]
Yes it is, dropping php 7.3 now is not an option at least until the beginning of next year. So my only options are delaying support for php 8 until then or implementing this discjockey-mechanic into our test, build and patch processes, and of course the build process has to be version specific then.
A simple --lock composer_73.lock option might help doing that, but that would still be a workaround.

**Comment by mohs8421** [comment]
In case anyone else stumbles upon this issue and needs the easiest possible workaround:
commit two versions of the lockfile and register a "pre-command-run" [script](https://getcomposer.org/doc/articles/scripts.md), that copies the file according to the version into position.
Add a "post-update-cmd" to copy the file back for committing.
Please note, that there is no "post-command-run" or "post-require-cmd", which would ease this solution when requiring some new ressources, so you would need to workaround that yourself.
