### ISSUE TITLE
Composer.json file in on Root and Theme Folder

### ISSUE THREAD

**Issue by blpraveen** [composer/composer#9922]
Hi,
I want customer to upload them and have there own composer installed which is not included in the root folder. How can I achieve this .And also There should not be a two installation in Root and Themes. I have include the composer.json file in themes and root folder. And I do composer install in both. But Only issue is not duplicate installation in the Themes. How to avoid Packages already installed in the root folder.

**Comment by stof** [comment]
I have no idea what root and themes you are talking about. I suspect that your are thinking about a specific project (a CMS maybe ?) without mentioning it, which clearly lacks context.

**Comment by blpraveen** [comment]
I want to build an Laravel Tenancy Application installed on root directory of the hosting . Customer can upload themes into the app Uploaded themes will be moved to subfolder inside root folder say 'themes'. After the upload the the theme I run composer install.  inside the 'theme' folder. I will have two composer.json files one in 'root' folder where Laravel is installed and other in the installed themes.

I will also have two vendor files one in themes and another in root. I dont want to have duplicates packages in themes. I need to verify if the the packages is already installed in the root else otherwise allow the package specific to theme be installed in themes directory.

**Comment by mcaskill** [comment]
I would suggest looking into [https://github.com/wikimedia/composer-merge-plugin](wikimedia/composer-merge-plugin). What you are describing sounds like the implementation used by [October CMS](https://github.com/octobercms/october) and its fork [Winter CMS](https://github.com/wintercms/winter).
