### ISSUE TITLE
Composer show (tree view) infinite loop

### ISSUE THREAD

**Issue by shochdoerfer** [composer/composer#9924]
My `composer.json`:

```json
{
  "require": {
    "magento/module-webapi": "100.4.1"
  },
  "repositories": [
    {
      "type": "composer",
      "url": "https://repo-magento-mirror.fooman.co.nz"
    }
  ]
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.magento/module-webapi : exact version constraints (100.4.1) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: OK
Checking composer version: OK
Composer version: 2.0.14
PHP version: 7.4.18
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
cURL version: 7.68.0 libz 1.2.11 ssl OpenSSL/1.1.1f
zip: extension present, unzip present
```

When I run this command:

```
composer show -vvv -t -f json
```

I get the following output: 

```
Reading ./composer.json (/tmp/composer-test/composer.json)
Loading config file /home/myuser/.composer/config.json
Loading config file /home/myuser/.composer/auth.json
Loading config file ./composer.json (/tmp/composer-test/composer.json)
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/tmp/composer-test): git branch -a --no-color --no-abbrev -v
Executing command (/tmp/composer-test): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (/tmp/composer-test): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (/tmp/composer-test): hg branch
Executing command (/tmp/composer-test): fossil branch list
Executing command (/tmp/composer-test): fossil tag list
Executing command (/tmp/composer-test): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /home/myuser/.composer/composer.json

Reading /tmp/composer-test/vendor/composer/installed.json
Running 2.0.14 (2021-05-21 17:03:37) with PHP 7.4.18 on Linux / 5.4.72-microsoft-standard-WSL2
```

Composer then hangs forever and nothing happens anymore. If I omit the `-t` flag everything is working fine. It looks like that the tree view option runs some recursive logic that fails to terminate at some point. It also seems to happen with other Magento modules like:
```
"require": {
    "magento/module-customer": "102.0.6"
}
```
or
```
"require": {
    "magento/module-indexer" : "100.4.2"
}
```

**Comment by Seldaek** [comment]
I believe it's not really infinite loop but only super inefficient because every magento module requires magento/framework which then requires a ton of magento/* so to list any module you need to list them all and each of them lists magento/framework which then also lists all the modules again.. It just ends up creating a gigantic tree.

I am not sure how to fix this without making the command way less useful for other use cases which aren't as loopy.

**Comment by stof** [comment]
Well, does the tree view handle circular dependencies properly ? If not, it might indeed be an infinite loop

**Comment by Seldaek** [comment]
Of course.. maybe there's a bug somewhere in that handling, but from looking at the code it looks all fine, and does seem to handle circular dependencies in other projects I tested, so either it's something very special here causing a circular dep bug, or it's just too big and it takes ages to generate.

**Comment by Seldaek** [comment]
In case anyone else wants to have a look:

https://github.com/composer/composer/blob/759897e7e855fcac6654c89f40a4283c3d2df1fe/src/Composer/Command/ShowCommand.php#L1030-L1065

and https://github.com/composer/composer/blob/759897e7e855fcac6654c89f40a4283c3d2df1fe/src/Composer/Command/ShowCommand.php#L1130-L1168

**Comment by shochdoerfer** [comment]
@Seldaek fair enough, I let it run for 10mins or so and thought it might be an infinite loop. Your assumption in regards to the magento/framework package could be right. If I use it as the only dependency, it prints the graph properly.

If I find some time in the next few weeks, I'll try to debug the issue.

**Comment by shochdoerfer** [comment]
It looks like that tracking the already parsed packages when navigating in the package tree has an issue. At least in my specific case package information was not properly tracked globally which resulted in lookup problems and the infinite loop. I could fix the problem by making 2 minor changes:
- change the method declaration of [addTree()](https://github.com/composer/composer/blob/759897e7e855fcac6654c89f40a4283c3d2df1fe/src/Composer/Command/ShowCommand.php#L1135) to pass `$packagesInTree` as reference
- change the assignment of [$currentTree = $packagesInTree](https://github.com/composer/composer/blob/759897e7e855fcac6654c89f40a4283c3d2df1fe/src/Composer/Command/ShowCommand.php#L1148) in the foreach loop to also make use of the reference

Since we are dealing with a recursive function, logically this makes sense for me to pass the data via reference. I am just wondering why this works for other use cases and why references have not been used in the first place. Maybe I am missing the bigger picture here. @Seldaek do you have some insights?

Happy to provide a PR if my findings make sense :)

**Comment by Seldaek** [comment]
The point of the current code is that it should not show things already shown above in the tree, but if something was already shown in another sub-tree, it should be shown again in full. That's why it doesn't pass by ref and creates a new tree copy for every sub-tree with `$currentTree = $packagesInTree`. So with that in mind I still think the current implementation is fine.. but maybe I misunderstood you :)

**Comment by shochdoerfer** [comment]
@Seldaek thx for the clarification. Would you be interested in the PR to fix this for larger projects? Or do you feel it's not worth tackling?

**Comment by Seldaek** [comment]
@shochdoerfer if you have a fix that does not mess with the functionality for regular projects, that sure sounds good to me :)

**Comment by Seldaek** [comment]
Closing as timed out, but feel free to get back with a PR if you do have one.
