### ISSUE TITLE
On composer update getting issue

### ISSUE THREAD

**Issue by papnoisanjeev** [composer/composer#9926]
"**Attempted to call an undefined method named "getAllRawData" of class "Composer\InstalledVersions".
Did you mean to call "getRawData"?**"

Suddenly getting this error with **composer 2**  with project when running **composer update**.
But for composer 2 latest version working fine with **2.0.14** and also working well few days ago for other lower version of composer 2 as well.

**Comment by Seldaek** [comment]
That is a bug in ocramius/proxy-manager I believe. You can fix it by making sure you use latest Composer 2.0.14+ or you can require friendsofphp/proxy-manager-lts instead which offers broader compatibility with all Composer 2.0.* versions.

**Comment by xabbuh** [comment]
Or if you want to keep ocramius/proxy-manager make sure to have 2.12.0 installed: https://github.com/Ocramius/ProxyManager/releases/tag/2.12.0

**Comment by papnoisanjeev** [comment]
> That is a bug in ocramius/proxy-manager I believe. You can fix it by making sure you use latest Composer 2.0.14+ or you can require friendsofphp/proxy-manager-lts instead which offers broader compatibility with all Composer 2.0.* versions.

After require  friendsofphp/proxy-manager-lts  it is asking for other packages like symfony/filesystem as well.

**Comment by Seldaek** [comment]
@xabbuh 2.12.0 is exactly the version causing the issue, as it requires Composer 2.0.14 or above to work. Previous versions of ocramius/proxy-manager would function fine on any Composer 2.x, but they would trigger a deprecation notice on 2.0.14+. The best though IMO is to ensure your whole team updates to latest Composer and then keep the package at the latest version and move on.

**Comment by xabbuh** [comment]
Ah indeed, I thought that was the version where the incompatibility has been fixed without breaking compat with older Composer versions.

**Comment by vipin-shrivastava** [comment]
@xabbuh @Seldaek 
when I required the **ocramius/proxy-manage** version **2.0.12** . It is giving me the same error but if I restrict with the **ocramius/proxy-manage** version **2.11.1** . it is working fine with any version of composer 2.
