### ISSUE TITLE
Programmed glitch in tha matrix at major (and minor) releases

### ISSUE THREAD

**Issue by szepeviktor** [composer/composer#9929]
Hello! Many software has the problem of being full of bugs at major (and sometimes at minor) releases.

I open this issue **to explore** ways to avoid 2.1.1 and 2.1.2 being ten fixes each.

E.g. many projects have the habit of creating a test case for each resolves issue,
or simply going slower with releases.

Any thoughts?

**Comment by szepeviktor** [comment]
Two dead ends.

1. lack of resources
2. it is all right to have fixes in subsequent releases

**Comment by xabbuh** [comment]
Can you explain how this is related to Composer?

**Comment by szepeviktor** [comment]
I've spent countless hours with v2.0.* problems.
I've like to prevent all those problems in v2.1.* by resolving them right in v2.1.0

**Comment by Seldaek** [comment]
I have no idea what you are talking about. We fix things whenever we can. And we release patch releases relatively often.

> Please see release notes, almost all of them are "Fix"-es.

Of course most patch releases are "Fixes x", as you really should only do bugfixes in patch releases.

> I'd like to prevent all those problems in v2.1.* by resolving them right in v2.1.0

Which problems? Did you report them?

**Comment by szepeviktor** [comment]
> Which problems? Did you report them?

Somehow fix all those problems that would occur **after** 2.1.0

**Comment by Seldaek** [comment]
Ok so you want us to create more tests for all the things to avoid having to fix things in the future. Sure. Pull requests are open if you want to write quality test cases. It's not always easy though, and not always worth it. We test core things that make sense to be tested, and the rest isn't always tested as much as I'd like to but it's a compromise thing.

Going slower with releases I have no idea what this would help.. We do ship snapshots already of master so people can try it out ASAP, and report issues ASAP. If people do not test snapshots/RCs then yes they're going to have to test things in prod when stable releases come out. Everyone has to take part in the stability of the ecosystem.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by stof** [comment]
> E.g. many projects have the habit of creating a test case for each resolves issue,

this only works when you solve issues. It does not prevent introducing *new* bugs

> simply going slower with releases.

Composer releases RC versions for each new minor or major versions. That can help fix issues before the `.0` release, but only if users actually test the RC releases rather than waiting for the stable release (and that's where things fall shorts generally)

>     2\. it is all right to have fixes in subsequent releases

to me, that's indeed right (especially if patch releases can be done quickly when necessary so that fixes don't stay unreleased for months)
