### ISSUE TITLE
2.1 - Incorrect color legend in `composer outdated`

### ISSUE THREAD

**Issue by mbabker** [composer/composer#9939]
The color legend mentions yellow being a patch/minor release and red being a major release, but in the list below it, red is used for patch/minor releases and yellow for major.

![Screen Shot 2021-06-03 at 2 26 45 PM](https://user-images.githubusercontent.com/368545/120700877-d34b1e80-c477-11eb-8e52-3f1e33588814.png)

**Comment by Seldaek** [comment]
Haha sorry 🤦🏻‍♂️
