### ISSUE TITLE
Composer 2.1.0 doesn't run laravel package discovery

### ISSUE THREAD

**Issue by GrahamCampbell** [composer/composer#9940]
My `composer.json`:

```json
{
    "require": { "laravel/framework": "^8.0" }
}
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.1.0
PHP version: 7.4.19
PHP binary path: /usr/local/Cellar/php@7.4/7.4.19_1/bin/php
OpenSSL version: OpenSSL 1.1.1k  25 Mar 2021
cURL version: 7.77.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1k
zip: extension present, unzip present
```

When I run this command: 

```
composer install
```

I expect the laravel service provider discovery hook to run, but it doesn't. Worked on 2.0.14, not on 2.1.0.

**Comment by mallardduck** [comment]
@GrahamCampbell - forgive me if I'm missing something (i'm guessing I am) but don't you need scripts to hook into those events? For instance:
```json
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ]
    },
```

Or is there some newer method of hooking into composer events that Laravel should be using now?

**Comment by Seldaek** [comment]
For someone having zero clue about Laravel, this issue isn't particularly helpful. I don't know what you expect to see, nor how I can attempt to reproduce.

**Comment by driesvints** [comment]
@GrahamCampbell seems to be working fine for me with Composer v2.1.1:

![Screen Shot 2021-06-04 at 09 01 57](https://user-images.githubusercontent.com/594614/120759706-93397980-c513-11eb-9018-602f2a0ffc38.jpg)

**Comment by driesvints** [comment]
Sorry, that was for the first setup. When no vendor dir is present it also runs fine:

![Screen Shot 2021-06-04 at 09 04 56](https://user-images.githubusercontent.com/594614/120760115-093de080-c514-11eb-87e5-764937fd0215.jpg)

**Comment by GrahamCampbell** [comment]
I think https://github.com/composer/composer/pull/9935 may have been the fix for this. I will confirm rn...

**Comment by GrahamCampbell** [comment]
Confirmed. Composer 2.1.1 works properly. Sorry for the crappy issue report. I was planning on fleshing it out this morning.

**Comment by Seldaek** [comment]
Ok great!
