### ISSUE TITLE
Phar Binaries doesn't work with php cli after update to 2.1.x

### ISSUE THREAD

**Issue by blankse** [composer/composer#9958]
My `composer.json`:

```json
{
    "require": {
        "deployer/dist": "^6.8"
    }
}
```

When I run this command:
```
php composer.phar install
php vendor/bin/dep
```

I get the following output (Version 2.1.2):
```
dir=$(cd "${0%[/\\]*}" > /dev/null; cd '../deployer/dist' && pwd)

if [ -d /proc/cygdrive ]; then
    case $(which php) in
        $(readlink -n /proc/cygdrive)/*)
            # We are in Cygwin using Windows php, so the path must be translated
            dir=$(cygpath -m "$dir");
            ;;
    esac
fi

"${dir}/dep" "$@"
```

And I expected this to happen (Version 2.0.14):
```
Deployer 6.8.0

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -f, --file[=FILE]     Specify Deployer file
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  autocomplete  Install command line autocompletion capabilities
  help          Displays help for a command
  init          Initialize deployer in your project
  list          Lists commands
  run           Run any arbitrary command on hosts
  self-update   Updates deployer.phar to the latest version
  ssh           Connect to host through ssh
 debug
  debug:task    Display the task-tree for a given task
```

**Comment by blankse** [comment]
I'm working on WSL. Seems to be a regression from https://github.com/composer/composer/pull/9855
Can we add a "symlink" option for "bin-compat" to set the old behavior?

**Comment by Seldaek** [comment]
You don't need `php` prefix there. You can simply run `vendor/bin/dep`. We can add a new option for sure but IMO you really don't need it here :)

**Comment by blankse** [comment]
@Seldaek But I have on some servers no global php binary or the global one has an outdated version. I must set the php cli before.

**Comment by Seldaek** [comment]
Yeah then in that case sure you need the prefix, but those servers won't have the WSL fallback behavior I suppose so it shouldn't be a problem.

**Comment by blankse** [comment]
@Seldaek When I remove the PHP CLI I get now a permission error:
`vendor/bin/dep deploy live`
`vendor/bin/dep: 14: vendor/bin/dep: /var/www/html/vendor/deployer/dist/dep: Permission denied`

When Composer creates the proxy file, can it set the permissions to the destination?
