### ISSUE TITLE
Avoid reinitializing plugins with a class copy if not necessary

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#9962]
Refs https://github.com/composer/composer/issues/9952#issuecomment-856515012 

Whereas a composer require does:

```
[...]
Loading plugin Composer\Installers\Plugin (from composer/installers)
Loading plugin cweagans\Composer\Patches (from cweagans/composer-patches)
Loading plugin DrupalComposer\PreservePaths\Plugin (from drupal-composer/preserve-paths)
[...]
Using version ^3.18 for drupal/redis
./composer.json has been updated
[...]
Loading plugin Composer\Installers\Plugin_composer_tmp0 (from composer/installers)
Loading plugin cweagans\Composer\Patches_composer_tmp1 (from cweagans/composer-patches)
Loading plugin DrupalComposer\PreservePaths\Plugin_composer_tmp2 (from drupal-composer/preserve-paths)
[...]
```

The second batch of plugin loading there could perhaps see the class hasn't changed and avoid creating a new temporary class. Not sure if worth the trouble of checking file hashes etc for the little gain of optimizing this away though.

**Comment by stof** [comment]
Is the previous one unloaded or do we end up with plugins registered twice ?

**Comment by Seldaek** [comment]
They aren't unloaded I believe as the old composer instance is simply discarded, but they are also not receiving any events anymore as a new Composer instance will have a whole new EventDispatcher etc. for the new plugins to be registered with, so not too bad in practice, but yes this could probably also be cleaned up.

**Comment by Seldaek** [comment]
Decided against doing the optimization described in OP, not worth it and it's actually good as it forces plugin to play well with the class rewriting if every `require` triggers it, issues will be discovered quickly.
