### ISSUE TITLE
Add `composer` platform package

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#9963]
This should track the composer version, and allow packages to require or conflict with specific composer versions, independently of the composer-runtime-api and composer-plugin-api versioning.

Also needs very good and clear documentation to avoid confusing the hell out of people with all these platform packages.

/cc @lstrojny

**Comment by lstrojny** [comment]
Will give this a shot

**Comment by Seldaek** [comment]
Closed by https://github.com/composer/composer/pull/10313
