### ISSUE TITLE
The requested PHP extension ext-json ^1.6 has the wrong version (8.0.7) installed.

### ISSUE THREAD

**Issue by passerbyxp** [composer/composer#9968]
My `composer.json`:

```json
{
    "require": {
        "ext-curl": "*",
        "ext-fileinfo": "*",
        "ext-pdo": "*",
        "ext-mbstring": "*",
        "ext-iconv": "*",
        "slim/slim": "4.*",
        "slim/psr7": "^1.3",
        "ext-json": "^1.6",
        "monolog/monolog": "^2.2",
        "php-di/php-di": "^6.3",
        "predis/predis": "^1.1",
        "topthink/think-validate": "^2.0",
        "aliyuncs/oss-sdk-php": "^2.4",
        "phpseclib/bcmath_compat": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        }
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (2.1.2 => 2.1.3)
Composer version: 2.1.2
PHP version: 8.0.7
PHP binary path: /usr/bin/php8.0
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
cURL version: 7.64.0 libz 1.2.11 ssl OpenSSL/1.1.1d
zip: extension present, unzip present
```

When I run this command: 

```
composer install
```

I get the following output: 

```
  Problem 1
    - Root composer.json requires PHP extension ext-json ^1.6 but it has the wrong version (8.0.7) installed. Install or enable PHP's json extension.
```

And I expected this to happen:

Perform composer install normally.

This is like issue #8342, except this time the version numbers flip sides: `8.0.7` is not suitable (too high?) for `^1.6`.

Fortunately this is our own project, so we can change to `"ext-json": "*"` and go on. But I think this is incorrect behavior, and should be mentioned here.

**Comment by mfn** [comment]
That's because the versioning scheme of `ext-json` was changed -> https://github.com/php/php-src/pull/4459

But that's just one thing: the other is that starting with PHP 8, ext-json is bundled by default anyway -> https://www.php.net/manual/en/json.installation.php
>  As of PHP 8.0.0, the JSON extension is a core PHP extension, so it is always enabled. 

(I guess the latter means it can be dropped completely, but otherwise `*` should be fine )

**Comment by stof** [comment]
Core PHP extensions are using the PHP version number as the extension version. And ext-json is not special anymore in that regard.
For core extensions, the recommendation from the composer maintainers is to use a `*` requirement (keeping the PHP version requirement handled by the `php` constraint)
