### ISSUE TITLE
Any way to get composer to stop deleting my work?

### ISSUE THREAD

**Issue by liquidcms** [composer/composer#9972]
This is my scenario (which has happened twice now in the past 2 weeks):

- i am working on modifying someone's code which is part of a composer managed project
- i have the work completed (hours of work)
- i need to make a patch of this work but realize i have composer patched copy of the project i am working on
- i remove the patch from my composer.json and run composer install

yes, i realize (now) that was a stupid thing to do as it has just wiped out all of my work.

Is there any option to have composer notify when it is about to delete uncommitted work (I realize this would need to tie in with git to do this) or simply backup files it is removing.

I have written a bash function call to override "composer" to check if install/update were options and then do something: simply spit out "are you sure msg" or possibly just do a backup.. but the backup is slow as i don't know what is about to be wiped and need to backup entire project. If this was built in to composer it could be much more efficient as it knows what it is about to wipe.

**Comment by yakatz** [comment]
You can override the composer.json to link a specific package to a local directory. On many of my projects, I have a `composer-dev.json` (so composer is run as `COMPOSER=composer-dev.json composer update`) with this content:

    "repositories": [
        {
            "type": "path",
            "url": "../library_local_dev",
            "options": {
                "symlink": true
            }
        }
    ],

This will cause composer to look at the local path for a repository and symlink to it instead of downloading it from packagist/git/etc. You then make all changes to the other package in this other folder and they are not overwritten by composer.

**Comment by stof** [comment]
Also, if you install from source (which is not the default), composer already warns you about uncommitted changes in your vendor directory.
If the package was installed from dist by downloading a zip archive (which is the default behavior as downloading the zip archive with the code of a given version is a lot faster than cloning the whole git history), composer has no way to know whether you modified the files, and so cannot warn you.

**Comment by liquidcms** [comment]
@yakatz , thanks for the reply.. although i don't really understand it... for now i have done this bash function to override composer command:

```
function composer() {
  if [ $1 == "install" ]; then 
  	echo "Oops we might be wiping your work!!"
  	ts=$(date +%s)
  	mkdir ~/composer-backups/"${ts}"
  	cp -R ./html/core ~/composer-backups/"${ts}"
  	cp -R ./html/modules/contrib ~/composer-backups/"${ts}"
  	/usr/bin/composer $1 $2 $3 $4
  else 
  	/usr/bin/composer $1 $2 $3 $4
  fi
}
```
which, since i am doing Drupal work, the only code i am likely to be patching is in /core or /modules/contrib. Surprisingly, copying those folders only was very fast so this solution works well.

**Comment by Seldaek** [comment]
Closing as I don't really see what we can do here, this is a workflow problem. If you use source installs for packages you want to edit, you'll be warned and generally avoid losing work: https://getcomposer.org/doc/06-config.md#preferred-install

If you instead edit files at random then yes things can be wiped, Composer considers the vendor dir as its own domain, not something people should edit. I understand this is made a bit more blurry by some CMSs using custom installers to put files in other dirs than vendor/.. but unfortunately that's not something we can fix either.

**Comment by mcaskill** [comment]
Indeed, this is a workflow problem, which has happened to me.

Using `composer status` can help but you need to remember to use it and depending on the situation of the package, Composer might not notice changes.

For posterity, I've created a similar shell function that checks for local changes and creates a backup before executing operations that may overwrite data (such as `install`, `reinstall`, and `update`):

https://gist.github.com/mcaskill/c3063cc6c8dcd7d40e1ca4d6e388b493
