### ISSUE TITLE
Compatibility with PHP 8.1

### ISSUE THREAD

**Issue by andypost** [composer/composer#9981]
Running composer on PHP 8.1 (alpha1) throws deprecation notice
`Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php:48`

The related fix https://github.com/justinrainbow/json-schema/pull/666

**Comment by stof** [comment]
Duplicate of https://github.com/composer/composer/issues/9718

**Comment by andypost** [comment]
Thank you
