### ISSUE TITLE
differentiate dev vs. no-dev in composer-scripts

### ISSUE THREAD

**Issue by staabm** [composer/composer#9982]
is there a supported x-platform way to check in post-install-cmd whether dev-mode is 1 or 0?

googling for a solution I found https://stackoverflow.com/a/53022623 which describes thinks like
```json
"scripts": {
    "post-install-cmd": [
         "[ $COMPOSER_DEV_MODE -eq 0 ] || <your command>"
    ]
}
```

which does not work on windows.

is there a "supported" way to check for dev-mode before invoking a script?

**Comment by staabm** [comment]
I did found [`@putenv`](https://github.com/composer/composer/blob/edf99510061f9be8347267d713d0512132d5cb4a/src/Composer/EventDispatcher/EventDispatcher.php#L263) which defines a ENV var. maybe something similar to if-case on the value of a maybe existing env-var would be helpful?

**Comment by staabm** [comment]
for now, I am just using a simple-script command:

```
<?php

namespace Deployer;

/**
 * Command to be used from the composer.json script-events.
 */
final class GruntCommand
{
    /**
     * @return void
     */
    public static function run(\Composer\Script\Event $event)
    {
        $cmd = 'grunt prod';
        if ($event->isDevMode()) {
            $cmd = 'grunt';
        }

        echo $event->getIO()->writeError($cmd);
        system($cmd);
    }
}
```

and

```
        "post-install-cmd": [
            "Deployer\\GruntCommand::run"
        ],
```

**Comment by Seldaek** [comment]
Yeah I am not sure how to do this except by adding even more hackery, like an `@if something`, but I don't really want to reimplement a shell in script handlers :(
