### ISSUE TITLE
Required PHP extensions not enforced

### ISSUE THREAD

**Issue by aimeos** [composer/composer#9987]
Root `composer.json`:

```json
    "require": {
        "php": "^7.2||^8.0",
        "aimeos/aimeos-laravel": "dev-master",
```

Intermediate "aimeos/aimeos-laravel" `composer.json`:

```json
    "require": {
        "aimeos/aimeos-core": "dev-master",
```

"aimeos/aimeos-core" `composer.json` requireing `ext-intl` and others:

```json
	"require": {
		"php": "~7.1||^8.0.1",
		"ext-curl": "*",
		"ext-dom": "*",
		"ext-fileinfo": "*",
		"ext-gd": "*",
		"ext-intl": "*",
		"ext-json": "*",
		"ext-mbstring": "*",
		"ext-pcre": "*",
		"ext-PDO": "*",
		"ext-zip": "*",
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.1.3
PHP version: 7.4.20
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
cURL version: 7.58.0 libz 1.2.11 ssl OpenSSL/1.1.1
zip: extension present, unzip present
```

When I run this command:

```
php composer create-project aimeos/aimeos myshop
```

I get the following output:

If one PHP extension required by aimeos/aimeos-core isn't available (e.g. `ext-intl` which is rarely installed by default) no error will be displayed and the packages will be installed without any notice. When using the application, a PHP error occurs because the NumberFormatter class provided by `ext-intl` isn't available.

And I expected this to happen:

Stop with an error that an extension isn't installed but required by "aimeos/aimeos-core"

The original bug report is available here: https://github.com/aimeos/aimeos-laravel/issues/385

**Comment by Seldaek** [comment]
I can't reproduce this. For me the create-project fails because intl is not installed. Please show the exact command you run and complete output you're seeing in create-project.

**Comment by Seldaek** [comment]
Ah well, will close here and take this over to your issue tracker as I believe I see what happened.
