### ISSUE TITLE
Composer2 under Windows 10 fails installing packages in WLS2 paths

### ISSUE THREAD

**Issue by Ziggizag** [composer/composer#9993]
This screenshot is self-explanatory:

[https://i.imgur.com/u7OhTVD.png](https://i.imgur.com/u7OhTVD.png)

Briefly:

`file_put_contents(/wsl$/Ubuntu-20.04/home/ziggi/www/mcov/vendor/composer/installed.php): Failed to open stream: No
  such file or directory`

Evidently, it looks like `file_put_contents` command has problem with WLS2 (Windows Subsystem for Linux) UNC paths.

Please notice - the Composer installation here is Windows installation not Linux! If I run Composer directly from Ubuntu subsystem, it is fine, but here I specifically mean cross-OS approach. Simply speaking - this problem makes life harder for WLS2 users who employ IDE run under Windows to develop for Linux.

**Comment by Seldaek** [comment]
Which version are you running? Please try again after running composer self-update. I believe this was fixed but maybe we missed a spot so if latest version doesn't work do tell.

**Comment by Ziggizag** [comment]
@Seldaek Hi - Thank you for prompt feedback!

This is the latest version - installed just today: Composer version 2.1.3 2021-06-09 16:31:20

**Comment by Seldaek** [comment]
Ok thanks, I could reproduce and fixed a few issues related to WSL paths. I'm hoping that's all of it but if you spot more please report.

**Comment by Seldaek** [comment]
FYI you can try the fix already with `composer self-update --snapshot`
