### ISSUE TITLE
name does not match the regex pattern

### ISSUE THREAD

**Issue by gromran** [composer/composer#9998]
My `composer.json`:
no, sensible data...

Output of `composer diagnose`:

   [Composer\Json\JsonValidationException]
   "./composer.json" does not match the expected JSON schema:
    - name : Does not match the regex pattern ^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$

When I run this command:
composer install via phpstorm

And I expected this to happen: 
has to work
How can i supress this "error". No changing foldername is not an option!

**Comment by stof** [comment]
The package name is not related to the folder name, but to the `name` property in your composer.json

**Comment by gromran** [comment]
Have now found a better solution anyway where I don't need the composer nonsense
