### ISSUE TITLE
[ Support | Question ] How can a package creator exclude a file from a package, even when users specify dev-master

### ISSUE THREAD

**Issue by lexidor** [composer/composer#9999]
# Question

Hi, I am a user of hhvm and Hack. I'd like to know, as a library author, how to instruct composer to exclude a file from a package, no matter how it is installed. Hack libraries currently use an export-ignore directive for a directory or file in the dot gitattributes file. This excludes the directory or file when it is being required using a normal version constraint, for example `^1.6`. However, when you require a package using the version `dev-master`, those files and directories are included.

# Why

Most of the ignored files and directories are tests and test artifacts. Downloading this into your vendor directory does not hurt in any way. A new feature of hhvm requires that a file must be excluded from vendor, but not from the git repository of the project. Hhvm 4.109 added support for native autoloading for class-like entities, functions, constants and types. This feature relies on having a single file at the root of your project named `.hhvmconfig.hdf`. When invoking hhvm to run a script or start a server, hhvm will walk upwards through the filesystem until a file with this name is found. This file MUST be at the root of your project and it takes a similar role as `php.ini` does. Problems arise when a dependency declares this file and hhvm incorrectly infers what the root of your code base is.

# Example of how this goes wrong

In order for Hack open source libraries to adopt the new fully native autoloader, they must have this file at their project root. This file must not be git ignored, since everyone contributing to the library needs to have that file present. Projects that depend on this package will have their own `.hhvmconfig.hdf` file at their project root. If both the top level project and the dependency declare such a file, this would break autoloading. `hhvm src/my_file.php` would scan src and find nothing, so it looks in the parent directory and it finds the correct hdf file. However invoking `hhvm vendor/some-vendor/some-package/src/their_file.php` would result in hhvm scanning their src, not finding a file and looking in the parent directory some-package, where it finds the hdf for some-package. Hhvm concludes that it has found the project root, but it has not, it found the root of the library instead. All symbols from the top level project can not be autoloaded, because the project root is incorrect.

**Comment by stof** [comment]
> Hack libraries currently use an export-ignore directive for a directory or file in the dot gitattributes file. This excludes the directory or file when it is being required using a normal version constraint, for example `^1.6`. However, when you require a package using the version `dev-master`, those files and directories are included.

to be exact, this `export-ignore` in `.gitattributes` is an instruction for `git archive`. So it is about ignoring files from the zip archive generated by the git server (github relies on the `git archive` logic when generating the zip file).
So this is not about requiring a stable release vs `dev-master`, but about installing from dist vs from source. And as of composer 2.1, the dist install will be the default for all versions (including dev versions).

When installing from source, there is no way to exclude files, because _by definition_ your vendor folder contains a clone of the git repo. When installing from dist (the default in composer 2.1+, and configurable in all composer versions either through the config file or through `--prefer-dist`), the `.gitattributes` ignore rule will work.

**Comment by lexidor** [comment]
Thank you kindly for your explanation ❤️. It has cleared up a long time confusion I had about the inner workings of composer. I'll upgrade to 2.1 and encourage others to do the same, or failing that --prefer-dist.

**Comment by serbanghita** [comment]
@stof great explanation, thank you, I needed to clear this up for Mobile Detect
